### ISSUE TITLE
Dynamic IPs are being allocated when a bridged NIC device has ipv{n}.address=none

### ISSUE THREAD

**Issue by markylaing** [lxc/lxd#10024]
When setting up firewall rules, the bridged NIC device will allocate IP addresses via DHCP when the device configs "ipv{n}.address" is parsed and found to be `nil` (https://github.com/lxc/lxd/blob/master/lxd/device/nic_bridged.go#L1039-L1072). 

We should check that the `ipv{n}.address` is not `none` before allocating an IP.
We should test that IPs are not allocated when the parent network has DHCP enabled and the `ipv{n}.address` is set to none.
We should test that all protocols are blocked when `ipv{n}.address=none` is set on the NIC.

**Comment by tomponline** [comment]
@markylaing are you seeing that when using a managed parent network with DHCP enabled that if the NIC has `ipv{n}.address=none` set that total protocol blocking isn't applied (because there is an IP being allocated)?

**Comment by markylaing** [comment]
> @markylaing are you seeing that when using a managed parent network with DHCP enabled that if the NIC has `ipv{n}.address=none` set that total protocol blocking isn't applied (because there is an IP being allocated)?

I came across this while testing for #9645 but that seems like another thing we should test for. I'll add it to the description.

**Comment by markylaing** [comment]
@tomponline I think we may not have seen this before because you cannot set `ipv{n}.address=none` for a managed network. I'm writing a test for it now and am hitting this line of validation https://github.com/lxc/lxd/blob/master/lxd/device/nic_bridged.go#L117

**Comment by tomponline** [comment]
Yeah makes sense, as the original feature request for it was for unmanaged parents.

**Comment by markylaing** [comment]
In that case, we will never enter this block https://github.com/lxc/lxd/blob/master/lxd/device/nic_bridged.go#L1039-L1072 when `ipv{n}.address=none` (because the network is unmanaged). So I think this may have been a wild goose chase.

**Comment by tomponline** [comment]
But it should work on a managed network too, which as you point out isn't reachable currently due to the incorrect validation.

**Comment by markylaing** [comment]
Ah I see, from your previous comment I thought you meant that the validation was correct. I'll update the validation too then.
