### ISSUE TITLE
When disk space is 0% you cant delete a backup

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#10030]
I frequently run out of disk space because I mess around with permissions + i'm lazy, as a result my backup software creates a backup on LXD it cant import.

Once the backup is created and the disk space hits 0%, I cant delete a backup using the LXD API.

**Comment by stgraber** [comment]
What error are you getting?

**Comment by turtle0x1** [comment]
It hangs. 

I've manually deleted the backup using `sudo su - && rm -rf /var/snap/lxd/common/lxd/backups/instances/c1/BACKUP_NAME` if really required can probably get back to the state I was in when reported.

**Comment by stgraber** [comment]
I'd expect anything that requires a database change to similarly hang, you should be able to test that easily enough by say modifying or deleting a profile for example.
