### ISSUE TITLE
Add global config option instances.network.host_name to control NIC host_name generation

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10036]
Add an `instances.network.host_name` global config option that can have `random` or `mac`, with a default value of `random`.

If it is set to `random` then use the random host interface names as we do today, but if it's set to mac, then generate a name in the form `lxd<mac_addres>`, e.g. `lxd001122334455` which just happens to fit the 15 bytes we have.

**Comment by presztak** [comment]
@stgraber Can I work on this one?

**Comment by tomponline** [comment]
@presztak sure, thanks!

**Comment by presztak** [comment]
@tomponline couple of questions:

1. Description is saying that we should support interface name in form `lxd001122334455` but here we have info that interface name should not be longer then 13 characters:

https://github.com/lxc/lxd/blob/d988a645c04f1e3c13d9d14cb9cad0edcf94a3b2/lxd/network/network_utils.go#L52-L55

what do you think?

2. Should we generate interface name based on MAC also for VM's?
3. Should we generate interface name for all nic types? I mean: bridge, macvlan, ovn and so on?

**Comment by stgraber** [comment]
Given most MACs will be LXD MACs which all share the same prefix, the best option may be to do `lxd22334455` and so drop the leading 4 digits of the MAC, giving us an interface name of 12 characters.
