### ISSUE TITLE
make getting failed migration logs easy

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#1004]
We have `lxc info --show-log` for regular container logs, but it would also be handy if there was a `lxc info --migration-log` or similar to get the last failed migration log for this container.

This involves a little extra bookkeeping, because the restore happens on the target, but if it fails, the source is the only place the container exists, so the target should send the log back to the source for inspection.

**Comment by stgraber** [comment]
Sounds like we should think through a proper log interface against the container and rebase the existing --show-log onto that.

**Comment by stgraber** [comment]
Thinking about something like GET /1.0/containers/\<container name\>/logs/\<logname\>

**Comment by tych0** [comment]
On Mon, Aug 10, 2015 at 03:09:55PM -0700, Stéphane Graber wrote:
> Sounds like we should think through a proper log interface against the container and rebase the existing --show-log onto that.

Yeah, that would probably be better :)

**Comment by tych0** [comment]
On Mon, Aug 10, 2015 at 03:10:28PM -0700, Stéphane Graber wrote:
> Thinking about something like GET /1.0/containers/\<container name\>/logs/\<logname\>

and a GET on /logs gives you a list of the available logs? (basically
a ls of /var/lib/lxd/foo/logs)? That would be easy enough to do.

**Comment by stgraber** [comment]
yup and POST would let you push a log back to the server for migration.

**Comment by stgraber** [comment]
basically re-implementing webdav :)

**Comment by tych0** [comment]
On Mon, Aug 10, 2015 at 03:14:37PM -0700, Stéphane Graber wrote:
> basically re-implementing webdav :)

But hopefully not as a broken pile of shit :). Sounds good, if I get
bored on a plane I'll hack on this, thanks.

**Comment by stgraber** [comment]
So rough spec is:

| Method | URL | Description |
| ----- | ----- | ----- |
| GET | /1.0/containers/\<container name\>/logs | List all available logs |
| GET | /1.0/containers/\<container name\>/logs/\<log name\> | Retrieve the log |
| PUT | /1.0/containers/\<container name\>/logs/\<log name\> | Push a new log |
| DELETE | /1.0/containers/\<container name\>/logs/\<log name\> | Remove the log |

I'd recommend we come up with a generic list of log files and don't allow arbitrary new ones be created. Querying a non-existing one would return an empty entry.

So the list of available logs would only really vary between LXD various when we have to add a new one.
