### ISSUE TITLE
VMs on non-loop LVM storage pools broken since LXD 4.24 with io_uring

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10061]
Reported from https://discuss.linuxcontainers.org/t/vms-frozen-at-boot-after-snap-lxd-update-4-24-io-uring-problems/13572

```
lxc storage create lvm lvm source=vg0 lvm.vg.force_reuse=true
lxc launch images:ubuntu/focal v1 --vm -s lvm
```

VM start will hang and the QEMU process will have to be forcefully killed.

Disaling io_uring in a custom LXD build fixes the issue.

Also using ZFS ontop of an LVM  (or LUKS) volume has the same problem:

```
lvcreate -n zfs -L 50G vg0
lxc storage create zfs zfs source=/dev/vg0/zfs
lxc launch images:ubuntu/focal v1 --vm -s lvm
```

**Comment by tomponline** [comment]
I tried the Focal HWE kernel and that seems to work with LVM and ZFS atop LVM.

```
sudo apt install --install-recommends linux-generic-hwe-20.04
```

**Comment by stgraber** [comment]
Ok, as discussed on IRC, we'll make 5.13 the minimum cut off version for enabling IO uring in LXD.
