### ISSUE TITLE
 Cryptic "not supported on this server" error when missing (or not refreshed) capabilities for VMs

### ISSUE THREAD

**Issue by Saviq** [lxc/lxd#10078]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 21.10
 * The output of `lxc info`: [lxc-info.txt](https://github.com/lxc/lxd/files/8289604/lxc-info.txt)

# Issue description

When the running system is missing some capabilities to run VMs, trying to launch one results in a cryptic error:

```plain
ubuntu@ubuntu:~$ lxc launch ubuntu: --vm
Creating the instance
Error: Failed instance creation: Failed creating instance record: Instance type "virtual-machine" is not supported on this server
```

In this case it was the `vhost-vsock` module missing. Just loading the module doesn't help, as LXD determines it on startup.

# Steps to reproduce

 1. Flash [Ubuntu 21.10](https://cdimage.ubuntu.com/releases/impish/release/ubuntu-21.10-preinstalled-server-arm64+raspi.img.xz) on a Raspberry Pi
 2. `lxc launch ubuntu: --vm`

**Comment by delmardavis** [comment]
This seems to be a dependency issue. Of the 4 lxd 5 hosts that I have deployed, only the one that had been running kvm's (freebsd jail hosts) before being upgraded to 22.04 and installing the new snap over that. I will run through what isn't on the failing servers in the morning.

**Comment by stgraber** [comment]
So looks like things are going to get a LOT more verbose with my change:
```
Error: Failed instance creation: Failed creating instance record: Instance type "virtual-machine" is not supported on this server: vhost_vsock kernel module not loaded: Failed to run: modprobe -b vhost_vsock2: modprobe: FATAL: Module vhost_vsock2 not found in directory /lib/modules/5.15.0-18-generic
```

**Comment by stgraber** [comment]
Tweaked things a bit more so we get:
```
Error: Failed instance creation: Failed creating instance record: Instance type "virtual-machine" is not supported on this server: vhost_vsock kernel module not loaded
```

**Comment by aceqbaceq** [comment]
# lxc launch local:f1dd0e76efe8 five -v
Creating five
Error: Failed creating instance record: Instance type "virtual-machine" is not supported on this server: vhost_vsock kernel module not loaded


# uname -ar
Linux lenovo 5.4.0-91-generic #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

# lsmod | grep vsock
vhost_vsock            24576  0
vmw_vsock_virtio_transport_common    32768  1 vhost_vsock
vsock                  36864  2 vmw_vsock_virtio_transport_common,vhost_vsock
vhost                  49152  2 vhost_vsock,vhost_net


# snap list | grep lxd
lxd                   5.13-cea5ee2                24758  latest/stable    canonical**    -



what should  i do?
