### ISSUE TITLE
LXD fails to start up successfully until all pools are mounted

### ISSUE THREAD

**Issue by crass** [lxc/lxd#10087]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:  [lxc.info.txt](https://github.com/lxc/lxd/files/8306519/lxc.info.txt)

# Issue description

I have a storage pool that is on a removable disk another pool which is backed by a disk that is always connected. There are several containers, some exclusively utilizing one pool and some anther. When the computer starts up, sometimes the removable disk is not connected. In this case the LXD daemon fails to start, but is repeatedly restarted by systemd until the storage pool is mounted.

Here is a relevant portion of the log:
> lxd.daemon[2920]: t=2022-02-25T13:42:31-0600 lvl=eror msg="Failed to start the daemon" err="Failed initializing storage pool \"pool-WD-WCAW31084296-part3\": Source path \"/var/lib/snapd/hostfs/media/WD-WCAW31084296/part3/lxc-pool-WD-WCAW31084296-part3\" isn't btrfs"
> lxd.daemon[2920]: Error: Failed initializing storage pool "pool-WD-WCAW31084296-part3": Source path "/var/lib/snapd/hostfs/media/WD-WCAW31084296/part3/lxc-pool-WD-WCAW31084296-part3" isn't btrfs
> lxd.activate[2375]: Error: Get "http://unix.socket/1.0": EOF
> lxd.activate[2117]: ====> Activation check failed, forcing activation
> snap.lxd.activate.service: Succeeded.
> systemd[1]: Finished Service for snap application lxd.activate.
> systemd[1]: snap.lxd.activate.service: Consumed 2.561s CPU time.
> wpa_supplicant[1968]: wlp61s0: CTRL-EVENT-SIGNAL-CHANGE above=1 signal=-53 noise=9999 txrate=52000
> lxd.daemon[2699]: => LXD failed to start
> systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=1/FAILURE
> systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
> systemd[1]: snap.lxd.daemon.service: Scheduled restart job, restart counter is at 1.
> systemd[1]: Stopped Service for snap application lxd.daemon.
> systemd[1]: Started Service for snap application lxd.daemon.

First, the error message is misleading because the source path doesn't exist, which I suppose means that its not btrfs. Perhaps it should mention that it does not exist. Also the source path may be confusing because its an implementation detail of lxd, and not one
that the user will normally see because its only in the lxd process namespace. I recommend stripping of the `/var/lib/snapd/hostfs` prefix.

What I would like is for lxd to start up, and start up containers that do not use that storage pool.  It would be nice if it also used inotify to detect when the unmounted storage pool becomes mounted and to then make containers using that storage pool available.

# Steps to reproduce

I haven't tried this, but I think this should reproduce the issue without needing to have a removable drive.

 1. Create file backed loopback mounted btrfs volume and mount at /media/lxd-test
 2. With fresh LXD, add storage pool named lxd-test backed by /media/lxd-test
 3. Create container backed by lxd-test storage pool
 4. Stop LXD daemon
 5. unmount /media/lxd-test
 6. Start LXD daemon

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
Lxd 4.24 has support for this.
https://discuss.linuxcontainers.org/t/lxd-4-24-has-been-released/13550

**Comment by stgraber** [comment]
Closing as this was on 4.23

**Comment by crass** [comment]
Indeed! I meant to submit this several weeks ago. So I'm glad to see you guys have read my mind.
