### ISSUE TITLE
Storage volume total size and used in a single query

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#10085]
**storage volume**, in order to get size and used:

/1.0/storage-pools/{name}/volumes/{type}/{volume}

```
{
  "metadata": {
    "config": {
      "size": "50GiB",
      "zfs.remove_snapshots": "true"
    },
```
and
/1.0/storage-pools/{name}/volumes/{type}/{volume}/state

```
{
   "metadata": {
     "usage": {
       "used": 1693552640
     }
   },
```

It would make sense, getting both size and used which in my opinion are related in one query.
Either:
`/1.0/storage-pools/{name}/volumes/{type}/{volume} `
add **recursion=1**

or:
`/1.0/storage-pools/{name}/volumes/{type}/{volume}/state`
shows total `size` as well.

Preferably both values in same unit. Right now `size` is in Gibibytes and `used` in Bytes.

**Comment by presztak** [comment]
@stgraber Can I work on this?

**Comment by tomponline** [comment]
Thanks!

**Comment by presztak** [comment]
@tomponline

What units do we want to use in both cases?
