### ISSUE TITLE
lxd 4.24 Grafana Dashboard doesn't display networking's data

### ISSUE THREAD

**Issue by gbonazzoli** [lxc/lxd#10080]
# Required information

 * Distribution: Oracle Linux
 * Distribution version: 8.5
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.17-2136.304.4.1.el8uek.x86_64
   * LXC version: 4.24
   * LXD version: 4.24
   * Storage backend in use: btrfs

# Issue description

Followed the instructions to install prometheus and grafana and everything works fine.
The only issue here is that the networking data are not showed on grafana.

See attached screenshots:

![Screen Shot 2022-03-18 at 06 03 57](https://user-images.githubusercontent.com/17742862/158941370-9892e75d-5e22-4340-91e5-b4c1d742775c.png)

![Screen Shot 2022-03-18 at 06 10 53](https://user-images.githubusercontent.com/17742862/158941460-1b2852b1-88a8-4132-b947-b4038fd9b7f8.png)

**Comment by tomponline** [comment]
One for @simondeziel perhaps?

**Comment by stgraber** [comment]
@gbonazzoli what's your version of grafana and prometheus?

**Comment by gbonazzoli** [comment]
Hi @stgraber 

grafana version: 8.4.4
prometheus, version 2.33.4

**Comment by stgraber** [comment]
Can you try running `sum(rate(lxd_network_transmit_bytes_total{device!="lo",job="lxd-ora2",project="default"}[5m]))*8` directly against prometheus?

**Comment by gbonazzoli** [comment]
I've modified job="lxd-ora2" in job="lxd-ora02" to:

sum(rate(lxd_network_transmit_bytes_total{device!="lo",job="lxd-ora02",project="default"}[5m]))*8

and it replies:

{} | 4105220.141542369

**Comment by stgraber** [comment]
It's almost certainly a grafana interval issue then, does the graph appear if you change your interval at the top of the dashboard to some other value, say a few hours or a day?

**Comment by gbonazzoli** [comment]
Unfortunately not. 

I've tried also a custom range, but it is not displaying anything.

**Comment by simondeziel** [comment]
@gbonazzoli could you try editing one of the broken graph and replace `$__rate_interval` by `5m` and see if that helps?

**Comment by gbonazzoli** [comment]
Nope, with the following change:

modified 

`sum(rate(lxd_network_transmit_bytes_total{device!="lo",job="$job",project="$project"}[$__rate_interval]))*8`

into:

`sum(rate(lxd_network_transmit_bytes_total{device!="lo",job="$job",project="$project"}[5m]))*8`

**Comment by stgraber** [comment]
Figured this one out, it happens when you don't have prometheus as a default data source because those specific metrics weren't tied to the data source defined in the dashboard.
