### ISSUE TITLE
Stateless lxc copy freeze container despite allow-inconsistent is set

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxd#10091]
# Required information

   * Kernel version: 5.4.0-91-generic
   * LXC version: 4.0.12
   * LXD version: 4.24
   * Storage backend in use: dir

# Issue description

lxc copy freeze source container despite `--allow-inconsistent` and `--stateless` is set. 

# Steps to reproduce
```
lxc copy remote:a b --stateless --allow-inconsistent
```

**Comment by kautMaks** [comment]
Same problem was described here
https://github.com/lxc/lxd/pull/9833#issuecomment-1047260094

**Comment by stgraber** [comment]
@markylaing can you sort this one out?

**Comment by kautMaks** [comment]
@stgraber @markylaing Hello!
This bug still reproduces on lxd5.0 and lxd5.1. 

When i made `lxc copy a remote_server:a --stateless --allow-inconsistent` container on source still became FROZEN. 

When I made local copying, it works properly `lxc copy a b --stateless --allow-inconsistent` container left RUNNING

**Comment by stgraber** [comment]
@kautMaks what's the version on both source and destination and what storage pool driver is used on source and destination?
@markylaing can you look into this?

**Comment by kautMaks** [comment]
I made tests on 5.0 both source and destination and on 5.1 both source and destination. 
 Storage backend in use: dir

**Comment by kautMaks** [comment]
@stgraber @markylaing Hi! Do you have some news about this problem? Maybe milestone?)

**Comment by tomponline** [comment]
@kautMaks @markylaing is going to be looking at this shortly, with an aim to get it resolved for LXD 5.2 next week.

**Comment by jalbstmeijer** [comment]
Hi,

Came across the same issue with lxd-5.1
I can also confirm that doing a local copy with "--stateless --allow-inconsistent" seems to be the only why not triggering the source to be frozen.
Just one question remaining, should  "--stateless" not be enough to prevent any frozen source state in the  upcoming fix for both local and remote copies?
