### ISSUE TITLE
lxd-4.0.9: Failed to setup virtfs-proxy-helper for device - Required binary "virtfs-proxy-helper" couldn't be found

### ISSUE THREAD

**Issue by juippis** [lxc/lxd#10092]
# Required information

 * Distribution: Gentoo
 * Distribution version: stable

# Issue description

lxd-4.0.8 and lxd-4.0.9 have changed the way they try to locate the `virtfs-proxy-helper` binary for using VMs with lxd. 
4.0.8: https://github.com/lxc/lxd/blob/b49211408791996695f5a2e0cb9e0055040d879a/lxd/device/disk.go#L643
4.0.9: https://github.com/lxc/lxd/blob/5628fc64ee9e750f2f7ce6452f1e0d6b8b8dddd0/lxd/device/disk.go#L556

With 4.0.8 it was easy to change the directory while building lxd with a simple sed:
```
	sed -i \
		-e "s:/usr/lib/qemu/virtfs-proxy-helper:/usr/libexec/virtfs-proxy-helper:g" \
		lxd/device/disk.go || die "Failed to fix virtfs-proxy-helper path."
```

But now this `sed` does nothing and lxd can't use VMs either if it doesn't find `virtfs-proxy-helper` from `$PATH`. Could the previous way of finding the binary be returned, or could you aid me in fixing the current version when `virtfs-proxy-helper` is outside `$PATH`? I.e., what and where do I need to change?

For me when VM fails to start once, I have to reboot before being able to boot it up again even if the binary is provided in an exported PATH.

**Comment by tomponline** [comment]
The logic remains the same it was just moved:

https://github.com/lxc/lxd/blob/stable-4.0/lxd/device/device_utils_disk.go#L244-L250

So you should be able to update your sed to work there.

The line you're linking to is for the pid path not the exec path.

**Comment by juippis** [comment]
Thank you, that should do it!
