### ISSUE TITLE
Remove old operations for offline cluster members

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10124]
If a cluster member abrutly becomes unreachable (perhaps it crashes or is severed from the cluster) then it can leave orphaned operation entries in the global `operations` table.

We should run a periodic process on the leader member that removes operations associated to offline members that are older than 1 hour (to account for brief network connectivity issues).

**Comment by monstermunchkin** [comment]
@tomponline Instead of using a fixed time (1 hour), shouldn't we rather use the configurable offline threshold?

**Comment by tomponline** [comment]
We could, but I don't suppose we would need to. Lets leave it fixed for now and if it becomes a problem we can add a config setting.
