### ISSUE TITLE
lxc remote add cannot take certificate fingerprint as command line argument

### ISSUE THREAD

**Issue by hadmut** [lxc/lxd#10137]
Security problem / feature request

# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 
   * LXC version: 
   * LXD version: 4.24-c92c0b2
   * Storage backend in use: zfs

# Issue description

It is not possible (or not documented how) to add a remote source in an automated and **secure** way. 

When doing a 
lxc remote add someserver somelocation --public

lxc displays the certificate fingerprint and asks for confirmation. This is secure, but requires interaction. 

From within a script or automated installation system this is not possible. There you could do a 

lxc remote add someserver somelocation --public --accept-certificate

which works automated, but insecure, since it accepts any certificate. 

There should be a command line argument for the fingerprint, to add a remote server in an automated, but still secure way. 

# Steps to reproduce

 1. Invite some evil hacker in your network or the common internet to fake the image server and polute it with dirty images. 
 2. lxc remote add someserver somelocation --public --accept-certificate   from within a script, e.g. automated installation with cloud-iniit or similar. 
 3. Be doomed.

**Comment by stgraber** [comment]
```
stgraber@dakara:~$ lxc config trust add --name blah
Client blah certificate add token: eyJjbGllbnRfbmFtZSI6ImJsYWgiLCJmaW5nZXJwcmludCI6IjQwMDI1MTc4N2Q2NzA0ZmY4OTdkYmZkOGQ0Mzg3OTcwYTJkOTVkOWRjOTA1MzAzYTI4OTM3MzE0YWE0YjhhODEiLCJhZGRyZXNzZXMiOlsiMTcyLjE3LjAuMjMyOjg0NDMiLCJbMjYwMjpmYzYyOmI6MTAwMDo1NDM2OjViMjU6NjRlNDpkODFhXTo4NDQzIiwiMTcyLjE3LjI1MC4xOjg0NDMiLCJbMjYwMjpmYzYyOmI6MjUwOjoxXTo4NDQzIiwiWzIwMDE6NDcwOmIyYjU6MTAzNzo6MTAwMF06ODQ0MyJdLCJzZWNyZXQiOiIzOTllY2M1MWMzYjdjZTc5Yjg1MTFmNGZiYzAxZTJjMjJjMGQyNzlkODA2NzZjYjUzMDM5M2JjNDMxNWE2MzFlIn0=
stgraber@dakara:~$ lxc remote add foo eyJjbGllbnRfbmFtZSI6ImJsYWgiLCJmaW5nZXJwcmludCI6IjQwMDI1MTc4N2Q2NzA0ZmY4OTdkYmZkOGQ0Mzg3OTcwYTJkOTVkOWRjOTA1MzAzYTI4OTM3MzE0YWE0YjhhODEiLCJhZGRyZXNzZXMiOlsiMTcyLjE3LjAuMjMyOjg0NDMiLCJbMjYwMjpmYzYyOmI6MTAwMDo1NDM2OjViMjU6NjRlNDpkODFhXTo4NDQzIiwiMTcyLjE3LjI1MC4xOjg0NDMiLCJbMjYwMjpmYzYyOmI6MjUwOjoxXTo4NDQzIiwiWzIwMDE6NDcwOmIyYjU6MTAzNzo6MTAwMF06ODQ0MyJdLCJzZWNyZXQiOiIzOTllY2M1MWMzYjdjZTc5Yjg1MTFmNGZiYzAxZTJjMjJjMGQyNzlkODA2NzZjYjUzMDM5M2JjNDMxNWE2MzFlIn0=
```
