### ISSUE TITLE
LXD docs returning 404

### ISSUE THREAD

**Issue by rsyring** [lxc/lxd#10132]
LXD docs are all coming up 404: https://linuxcontainers.org/lxd/docs/master/

![image](https://user-images.githubusercontent.com/109467/160265200-53bca4c6-2fd3-4cd7-afb5-abfe37bc37f4.png)

**Comment by tomponline** [comment]
Any ideas @stgraber ? I've seen the forums going up and down a lot for the last few hours, maybe related.

In the meantime you can also see the docs here https://github.com/lxc/lxd/tree/master/doc

**Comment by stgraber** [comment]
shiftfs on 5.17 issue apparently, rolling out new kernels to address that

**Comment by stgraber** [comment]
And fixed
