### ISSUE TITLE
Clustering tests ignore lvm and random storage pool modes

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10149]
Four of the clustering storage tests ignore the storage driver if its `lvm` or `random` and fallback silently to `dir`.

E.g.

https://github.com/lxc/lxd/blob/d97a05d03fdd31b7e09e6f42f5b1dfe75416ab1a/test/suites/clustering.sh#L520-L525

- test_clustering_image_refresh
- test_clustering_storage
- test_clustering_storage_single_node
- test_clustering_evacuation

There appears to be an issue creating a cluster using LVM storage pool.
And for the random mode, we should instead juse use the randomly selected pool driver for the standalone pool that is created at the start of all the tests. This way we will still use a random but consistent pool for all cluster members in the tests.

**Comment by tomponline** [comment]
I suspect the issue is that each node is trying to use the same underlying loop image file for its backing store. Although this somehow magically works for ZFS pool types.

**Comment by tomponline** [comment]
Hrm no it cant be that as each LXD node gets it own directory.

**Comment by stgraber** [comment]
Wouldn't it be an issue of having conflicting VG names?

**Comment by tomponline** [comment]
Yes that is an issue, but easily fixed by modifying spawn_lxd_and_join_cluster() to use per-node VGs (like it already has support for per-node ZFS pools).

But after that it fails creating the LVM thinpool ontop of the VG. I've confirmed its down to the fixed sized 1GB thinpool metadata volume being created.

**Comment by tomponline** [comment]
As discussed will introduce a `lvm.thinpool_metadata_size` pool setting and if not set let LVM decide the size.
