### ISSUE TITLE
After upgrade to v4.24: Load average encapsulation no longer working

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxd#10175]
This may be a configuration issue on my end but after a kernel and lxd upgrade on a few host machines one of them no longer simulates load average for my containers.

```
# uname -r
5.13.0-39-generic
# snap get lxd lxcfs.loadavg
true
```

nproc shows 2 cpu's as configured in the container profile

```
# nproc
2
```

But running top or htop shows all CPUs on the system, all RAM and the system overall load average.

The other two systems I upgraded which now have an identical kernel version and lxd version do not have this issue and only show the container load avg, the container CPUs and RAM as set in their profile.

I am not sure if I should try to restart lxd (this would bring down my containers, right?) or how to proceed. Any hints would be appreciated :)

**Comment by stgraber** [comment]
Is that with nested containers?

**Comment by webdock-io** [comment]
No, these are not nested containers

**Comment by stgraber** [comment]
Hmm, that's odd. It may be a case where LXCFS wasn't super happy to upgrade from 4.0.x to 5.0.x and used the emergency fallback to direct file access rather than crashing and breaking all containers. If that's the case. You'd need a full restart of LXCFS which is easiest done by rebooting the entire host or can alternatively be done by stopping all containers, killing lxcfs and then restarting the LXD snap.

**Comment by webdock-io** [comment]
@stgraber OK I'll try that procedure in a maintenance window soon and report back here. The procedure I followed was:

1) Did a full system upgrade
2) Rebooted the machine
3) Once booted no containers were started, they were all kept down
4) Did a snap refresh lxd --channel=latest/stable (no errors from what I could see)
5) Started all containers

Would there be a log entry somewhere I could check if this were the case? Meaning, that lxcfs did this emergency fallback after the upgrade?

**Comment by stgraber** [comment]
I would expect it to log something in the journal for unit snap.lxd.daemon probably around the time it handles its first request following the upgrade.

**Comment by stgraber** [comment]
@webdock-io did you manage to recover? Is it still showing up on fixed systems?

**Comment by webdock-io** [comment]
@stgraber Thanks for following up on this. I will be performing the maintenance on the problematic system tonight where I will attempt to stop all containers / LXD snap - then killall lxcfs processes and start the snap/containers again. As that will be a lot faster than a reboot I think.

Once that's done I'll report back if it worked or not.

PS: I found nothing in my logs unfortunately as they had been vacuumed in the meantime.

**Comment by webdock-io** [comment]
@stgraber Stopping all containers and doing a `snap refresh lxd --channel=latest/stable` (because why not upgrade while I was doing this anyway) cleared up the issue

Interestingly, lxcfs wasn't even running before I did this! So it failed to start entirely for some reason. Anyway, all is well now. Not sure what the core issue was, maybe we will never know :)
