### ISSUE TITLE
Database Refactor: Make transactions less expensive / frequent.

### ISSUE THREAD

**Issue by masnax** [lxc/lxd#10183]
This issue is to track the upcoming changes to the `db` package in LXD. The goals of these changes are:
* To reduce the amount of tables that are automatically queried when retrieving / editing LXD database entities. It should not be necessary to pull `config`, `devices`, `projects, and `profiles` associated with some entity when we just want to aggregate some fields (like names). 
* Perform more database actions within already-open transactions, rather than opening new ones. This will not always make sense (such as for storage volumes), but where appropriate, we should open fewer transactions.
* Move out some API related functions from the database package and instead perform them when handling the API. Namely, this is URL path creation and lists of entities that are using a project or profile.

These changes will be introduced per entity in the `db` package. . To this end, generated methods for those entities will use a `v2` generator, specified with a `version=2` in their generator comments:
```go
//go:generate mapper method -p db -e certificate_project GetMany struct=Certificate version=2
```

Eventually, once all entities are transitioned to `v2`, the `v2` generator will replace the original generator.
## Entities to refactor:
- [x] Certificates
- [x] Projects
- [x] Profiles
- [x] Instances
- [x] Images
- [x] Snapshots
- [x] Operations
- [x] Warnings
- [ ] Cleanup `db` and `cluster` packages
- [x] Replace `v1` generator with `v2`.

**Comment by tomponline** [comment]
@masnax thanks!

**Comment by tomponline** [comment]
@masnax can this be closed now?

**Comment by masnax** [comment]
There’s still 1 more PR I’ll send up which will remove the prepared statements stored in the ClusterTx struct. That one can close this issue.

**Comment by tomponline** [comment]
thanks
