### ISSUE TITLE
Trailing colon on https_address freezes cluster

### ISSUE THREAD

**Issue by masnax** [lxc/lxd#10181]
# Issue description

Assigning a `core.https_address` or `cluster.https_address` with a trailing colon will result in no port being assigned to the endpoints, thus causing cluster initialization to never complete.

# Steps to reproduce
```bash
lxd init --auto
lxc config set core.https_address 127.0.0.1: 
# Or `cluster.https_address` above.
lxc cluster enable test1
# This never returns.
```

**Comment by tomponline** [comment]
@masnax why do we need to accept a trailing colon rather than just rejecting it as invalid?
