### ISSUE TITLE
How to create a container based on image downloaded into a specific repo?

### ISSUE THREAD

**Issue by diegopivoto** [lxc/lxd#10205]
Hello!

There is a project that was inserted into a repository from its university and I need to test this project. Basically, this project involves some technologies, and LXC/LXD is one of them. There is an image called "_**MQTT_Publisher.img**_" which is an application responsible for generate random values of temperature and send them to a MQTT Gateway. This _**MQTT_Publisher.img**_ is the image used in a LXC/LXD container. Now, for testing this project, I downloaded this image and I need to create a container based on it.

How can I create a container based on an image that I've downloaded? I've searched about it, but I had obtained results about images like Ubuntu, Debian, and other ones that are available in default LXC/LXD repositories. But my image is an ready application that I need to use to create the container. So, do I need to put this MQTT_Publisher.img in some specific repository in order to use it to create a container? Or there is another way to access this image donwloaded in my computer to create the container? What are the commands needed for doing it?

Thank you.

**Comment by stgraber** [comment]
Support questions should go to https://discuss.linuxcontainers.org
