### ISSUE TITLE
lxc update make lxd containers start failed

### ISSUE THREAD

**Issue by antitoine** [lxc/lxd#1020]
Hi,

After an update of LXC on Ubuntu 14.04, when I want to start LXD containers, I have this error : 
*lxc update make lxd containers start failed*

This is the debug version :
```DBUG[08-17|19:04:17] fingering the daemon
DBUG[08-17|19:04:17] raw response:{"type":"sync","status":"Success","status_code":200,"metadata":{"api_compat":1,"auth":"trusted","config":{},"environment":{"architectures":[2,1],"backing_fs":"ext4","driver":"lxc","driver_version":"1.1.3","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"3.16.0-45-generic","version":"0.15"}}}
DBUG[08-17|19:04:17] pong received
DBUG[08-17|19:04:17] putting {"action":"start","force":false,"timeout":-1}
 to http://unix.socket/1.0/containers/gp-insa/state
DBUG[08-17|19:04:17] raw response: {"type":"async","status":"OK","status_code":100,"operation":"/1.0/operations/64dd67f8-c862-4f3d-ae0f-526743785e82","resources":null,"metadata":null}
DBUG[08-17|19:04:17] 1.0/operations/64dd67f8-c862-4f3d-ae0f-526743785e82/wait*
DBUG[08-17|19:04:17] raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"created_at":"2015-08-17T19:04:17.388991677+02:00","updated_at":"2015-08-17T19:04:17.391448936+02:00","status":"Failure","status_code":400,"resources":null,"metadata":"saving config file for the container failed","may_cancel":false}}
error saving config file for the container failed```

LXC and LXD versions are 0.15

**Comment by stgraber** [comment]
Can you please paste:
 dpkg -l lxd
 dpkg -l lxc
 dpkg -l liblxc1

**Comment by stgraber** [comment]
The error you're getting matches what you'd get if running the wrong version of liblxc with a slight ABi difference compared to what LXD was built with.

**Comment by antitoine** [comment]
Like in this issue https://github.com/lxc/lxd/issues/739 ?

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                             Version               Architecture          Description
+++-================================-=====================-=====================-=====================================================================
ii  lxd                              0.15-0ubuntu1~ubuntu1 amd64                 Container hypervisor based on LXC - daemon
ii  lxc                              1.1.3-0ubuntu1~ubuntu amd64                 Linux Containers userspace tools
ii  liblxc1                          1.1.3-0ubuntu1~ubuntu amd64                 Linux Containers userspace tools (library)

How can I solve it ? It's the default PPA of ubuntu, I think.

**Comment by stgraber** [comment]
your LXD is out of date, it should be 0.15-0ubuntu2

**Comment by antitoine** [comment]
I switch from the LXD master PPA to the stable, and it's fixed the problem.
I think they are a version problem on this repository.

**Comment by stgraber** [comment]
yeah, the problem should now have been fixed. The daily PPA requires manual copying which I forgot about.
