### ISSUE TITLE
Add ZFS snapshot support to lxd-migrate

### ISSUE THREAD

**Issue by danboid** [lxc/lxd#10265]
I used lxd-migrate for the first time yesterday. It is definitely easier to use and an improvement over lxdp2c or having to use tarballs via `lxc image` but it would be better if it could migrate ZFS snapshots too.

I backup my ZFS based containers using `syncoid` so that all of the snapshots are retained. `lxd-migrate` currently uses `rsync` which is blind to ZFS snapshots so I'd like to see `lxd-migrate` gain support for using `syncoid` (which is part of the `sanoid` package in Ubuntu) instead of `rsync` when you are migrating ZFS datasets or maybe it could replicate the snapshot syncing abilities of syncoid to avoid the extra dependency.

**Comment by stgraber** [comment]
I don't think we'll be doing that. Adding support for full ZFS based migration to lxd-migrate would be a LOT of work as we would need to do far more than just shelling out to ZFS but also need to handle the full ZFS based migration protocol which LXD uses internally, including feature negotiation and fallback to rsync.

This doesn't really make sense given that lxd-migrate is a tool meant for lift and shift.
So it's goal in life is to take an existing physical or virtual server and convert that to a LXD container or VM.

It's not meant to be used to restore backups made by a third party tool.

**Comment by stgraber** [comment]
In your case, given what you're working with, I suspect your best bet would be to generate a LXD backup tarball from what you have.

You'd need to extract the existing `backup.yaml` from the instance on ZFS, generate a `backup.yaml` and then do a zfs send/zfs receive of each snapshot as their own binary files. Put that in a tarball and you can feed it to `lxc import` for restoration.

The easiest to get an idea of what you need to generate would be to do:
 - lxc init images:alpine/edge a1
 - lxc snapshot a1
 - lxc snapshot a1
 - lxc export a1 --optimized-storage

And look at the resulting tarball to see the structure LXD expects.
