### ISSUE TITLE
Up-to-date vagrant/kvm/ec2 lxd host images 

### ISSUE THREAD

**Issue by rrva** [lxc/lxd#1026]
Would be great if there was an official LXD host virtual machine image, which is kept up-to-date with LXD preinstalled, for example using packer templates (http://packer.io), and which outputs at least vagrant virtualbox+vmware box files.

I guess ubuntu cloud server or ubuntu server wily would be a good base?

Also, this machine image could implement lxd config best practices, like btrfs for /var/lib/lxd and would give a plug-and-play experience. 

This is similar to boot2docker, docker machine etc. Make it easy to run LXD on virtualbox+vmware.

**Comment by stgraber** [comment]
So we've got vagrant support in tree, isn't that sufficient?

**Comment by rrva** [comment]
Only seems to support virtualbox, not vmware:

vagrant up --provider=vmware_fusion

fails because the ubuntu/trusty64 is a virtualbox-only build. That goes for all official ubuntu images on vagrant cloud it seems.

Also, it's based on Ubuntu 14.04, which is a bit old, and no btrfs.

I'm trying to run it now by changing the base box to box-cutter/ubuntu1404

**Comment by rrva** [comment]
https://github.com/lxc/lxd/pull/1028

**Comment by stgraber** [comment]
Branch merged, closing this issue. Thanks!
