### ISSUE TITLE
lxd network zone invalid zone name allow create but not delete

### ISSUE THREAD

**Issue by aal-zwork** [lxc/lxd#10274]
lxc network zone create /test/1 - success
lxc network zone list - success
lxc network zone delete /1 - 404 not found (lxd server not parse %2ftest%2f1 as name)

https://github.com/lxc/lxd/blob/74496dce49041e7f5deda53d81816f6bd631d385/lxd/network_zones.go#L268

**Comment by tomponline** [comment]
@stgraber https://github.com/lxc/lxd/pull/10276 fixes this issue, but not sure if you would also want to tighten up the DNS zones validation to prevent creation of invalid zone names in the first place? (I vaguely remember discussing validation when adding this feature and you purposefully went for allowing invalid zone names).

**Comment by stgraber** [comment]
We can do some validation but it's worth noting that in this case, a / is a valid character for a DNS zone name. Just not valid as a leading character.
