### ISSUE TITLE
VM stateful migration doesn't work on s390x

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10278]
```
lxc stop v1 --stateful
Error: Migration is disabled when VirtFS export path '/var/snap/lxd/common/lxd/devices/v1/config.mount' is mounted in the guest using mount_tag 'config'
Try `lxc info --show-log v1` for more info
```

**Comment by stgraber** [comment]
Hmm, so 9p doesn't work for migration on s390x but does on other architectures?

**Comment by stgraber** [comment]
Is that a QEMU error? If so, then there's likely not much we can do about it.
`migration.stateful` already turns off virtiofs in favor of 9p to allow the dump to work.

**Comment by tomponline** [comment]
Yes thats a QEMU error.

**Comment by stgraber** [comment]
Odd that this is architecture specific though.
Maybe it's got to do with all the ccw stuff on s390x?

**Comment by tomponline** [comment]
Yeah maybe, I thought I'd log the issue as I noticed it, in case we want to spend some time figuring out if it can be fixed.

**Comment by stgraber** [comment]
Actually, that's normal behavior for 9p, but we work around that by not keeping things mounted.

**Comment by stgraber** [comment]
Our current `lxd-agent-setup` script copies the data and then unmounts.
Were you trying with a 22.04 image which should have the current lxd-agent-loader logic?

**Comment by tomponline** [comment]
Interesting, so it suggests the lxd-agent unmount isn't working on s390x?

**Comment by stgraber** [comment]
@tomponline most likely you used a 20.04 image from `ubuntu:` which has the old lxd-agent-loader unlike our own images on `images:` (which lack s390x support).

**Comment by tomponline** [comment]
I was using the `ubuntu:focal` image I think, as `images:` doesn't produce s390x images right?

**Comment by stgraber** [comment]
```
root@s5lp3:~# lxc launch ubuntu-daily:22.04 v1 --vm
Creating v1
Starting v1                                 
root@s5lp3:~# lxc snapshot v1 --stateful
Error: Stateful stop requires migration.stateful to be set to true
root@s5lp3:~# lxc stop v1
root@s5lp3:~# lxc config set v1 migration.stateful=true
root@s5lp3:~# lxc config device override v1 root size.state=2GiB
Device root overridden for v1
root@s5lp3:~# lxc start v1
root@s5lp3:~# lxc snapshot v1 --stateful
root@s5lp3:~# lxc restore v1 snap0
root@s5lp3:~# 
```
