### ISSUE TITLE
Redirection to http://linuxcontainers.org/lxd/docs/master/rest-api/ is not protocol aware

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10270]
This isn't a really a LXD issue, but wasn't sure where to open the issue.

When following a link from https://linuxcontainers.org/lxd/rest-api/ to https://linuxcontainers.org/lxd/docs/master/rest-api (without the trailing `/`) the web server responds with a redirect to `http://linuxcontainers.org/lxd/docs/master/rest-api/` (note the `http://`).

This causes Firefox's HTTPS only mode to say that the target web site doesn't support HTTPS, when in fact if that URL followed then it is redirected back to HTTPS again:

```
curl https://linuxcontainers.org/lxd/docs/master/rest-api -I
HTTP/1.1 301 Moved Permanently
server: nginx/1.18.0 (Ubuntu)
date: Tue, 19 Apr 2022 09:06:27 GMT
content-type: text/html
content-length: 178
location: http://linuxcontainers.org/lxd/docs/master/rest-api/
```

```
curl http://linuxcontainers.org/lxd/docs/master/rest-api/ -I
HTTP/1.1 301 Moved Permanently
content-length: 0
location: https://linuxcontainers.org/lxd/docs/master/rest-api/
```

It would be better to have the initial redirection be protocol aware.

**Comment by stgraber** [comment]
Fixed by using non-absolute redirects.
