### ISSUE TITLE
systemd .service startup script

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1029]
Is there a .service script that will allow dev version of LXD to be run at startup on systemd system (Fedora 22)?

**Comment by rrva** [comment]
I use something like this (but without --tcp since that option no longer exists)

https://github.com/lxc/lxd-pkg-ubuntu/blob/dpm-wily/debian/lxd.service

**Comment by stgraber** [comment]
Right, we have the unit above and a .socket in there too. Moving the init scripts to LXD upstream would probably be fine and we may do that soon.

**Comment by stgraber** [comment]
(the main issue is that Go doesn't allow easy build-time paths like autoconf does, so anything we'd commit upstream would make a lot of assumptions with regard to paths).
