### ISSUE TITLE
(Some) LXD Images from lxd.images.canonical.com no longer have their default network managers present

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxd#10309]
I had little luck figuring out where to specifically to report this so I am trying here. I realize this is not an LXD issue per se and probably doesn't belong here. So please let me know if there is a better place for this report.

Nb: I am speaking of the /default images here, not the /cloud images.

Anyway, a week or so ago our deployments of Debian started failing. It turned out that networking was no longer being managed with ifupdown in Debian images but SystemdNetworkd. Despite not finding anything refering to this online I assumed this was just an upstream change in Debian.

However, just today suddenly all the OS's we support (besides Ubuntu which still works as it always has) namely Debian 11, Almalinux 8 and Centos 8 all failed as we can no longer configure networking in these containers.

We detect whether a container uses "centos style" networking, ifupdown, SystemdNetworkd or netplan and take it from there.

In none of the recently updated images for these OS'es can I find any of these network managers present. I am not well versed enough to figure out what, if anything, is managing networking in these images - but it strikes me as extremely odd that these 3 OS's all start failing at the same time and all have their "usual" network configuration schemes disabled or removed or whatever it is that has happened.

Any input here would be greatly appreciated. I can provide access to a test system with these failing containers if need be.

**Comment by tomponline** [comment]
@monstermunchkin I am seeing this also on `images:ubuntu/focal`, no IPv4 via DHCP.

**Comment by webdock-io** [comment]
@tomponline Whew I'm almost relieved this seems to be something on your side of the fence :D Let's hope @monstermunchkin knows what's up.

To clarify: I said Ubuntu works as it always has - in the sense that in Ubuntu default netplan is present and correct and by writing a netplan config file in an Ubuntu container networking works. I can't speak to what @tomponline is seeing specifically but the issue I see in the other operating systems is that their network managers are simply *poof* gone and I can find no way of successfully configure networking by hand in these guys.

Ok that's enough clarification let's see what @monstermunchkin  says (love that handle btw)

**Comment by monstermunchkin** [comment]
Yeah, I know what's up. The available images are currently broken due to a bug in distrobuilder. This has been fixed, and images built with the fixed distrobuilder will work fine again.

**Comment by webdock-io** [comment]
@monstermunchkin what's the ETA on that? 

I should probably make sure to remove all cached images on my systems once the fixed images are available?

**Comment by tomponline** [comment]
There should be rebuilt images within the next 24 hours.

**Comment by tomponline** [comment]
It is possible also to use images that are up to 3 days old see https://discuss.linuxcontainers.org/t/new-containers-not-getting-ipv4-address-broken-base-images/13916/12?u=tomp for more details

**Comment by xiki808** [comment]
Is this still an issue? Works fine for debian/10 but not for debian/11 or debian/11/armhf

![image](https://user-images.githubusercontent.com/8024321/165373524-c159a7e6-e097-4742-b42f-cc66a466d140.png)

**Comment by webdock-io** [comment]
@xiki808 How do you mean "works fine" vs. "does not work fine" ? 

We see all images we use work as they used to and everything is OK. We are running Debian 11 (amd64) and that works as it should now - maybe you are hitting the issue I touched on in my original post: It seems to us they have changed the way network is configured in newer debian. You now need to use SystemdNetworkd:

https://wiki.debian.org/SystemdNetworkd

Hope that helps

**Comment by xiki808** [comment]
I meant as regards to network as you pointed out in the issue.

Thanks for that, will give it a look!

**Comment by tomponline** [comment]
> Is this still an issue? Works fine for debian/10 but not for debian/11 or debian/11/armhf

Please can you use `lxc image delete <fingerprint>` to delete any affected images that were previously downloaded and try re-creating a fresh instance from the image so its downloaded, that way you can ensure you get the latest build.

**Comment by xiki808** [comment]
@tomponline I'm working on a raspberry pi and I did format the card and reinstall LXD using snap

**Comment by tomponline** [comment]
> @tomponline I'm working on a raspberry pi and I did format the card and reinstall LXD using snap

Do the `ubuntu:` images work? e.g. `ubuntu:focal`

**Comment by xiki808** [comment]
I actually tried again just right now fresh install and all images I tried so far are working fine obtaining an IPV4

So now not sure what was the matter yesterday, but I couldn't get network to work in my container, also from a fresh install.
