### ISSUE TITLE
Add profiles to backup data (and add flag to restore)

### ISSUE THREAD

**Issue by m-ueberall** [lxc/lxd#10329]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
    * LXD version: 5.0 (latest/stable)

# Issue/feature description

When exporting a container, `backup/container/backup.yaml` contains a list of assigned profiles, but the profiles themselves are not included. However, for archival/debugging/documentation purposes, having a copy of said profiles is often necessary (and thus currently requires an extra step).
* It would be helpful to have an option `--include-profiles` that would store a copy in, e.g., `backup/profiles/<name-of-profile[s]>` upon `lxc export`.
* Upon `lxc import --include-profiles`, those archived profiles then could be handled like configuration files shipped with `.deb` packages that can be viewed, compared, renamed/selected.
* In a second step, maybe even a filter selecting individual profiles to include/process this way could be added.

**Comment by stgraber** [comment]
@presztak absolutely!

**Comment by stgraber** [comment]
I think we should just always include the profile data in the backup.yaml.

For restoration, it's a bit harder. We may indeed need a flag to control this but I think that can be made at a later time, so long as we have the data in the backup, it would at least allow for manual restoration.

The issue I have with the restoration through a flag is that we'll need to decide what to do with it already exists, do we attempt to update it, ... and this could be security sensitive.

**Comment by presztak** [comment]
@stgraber,

just to clarify, in this change we will:

- add profiles to backup by default (without any additional flag) upon `lxc export`
- not implement import of profiles

that's correct?

And one more because I'm not sure. What will be the best place for profiles? `backup/profiles/<name-of-profile>` or profiles should be stored directly into `backup/container/backup.yaml` file?

**Comment by stgraber** [comment]
Yeah, that's correct.

I think we can put directly in backup.yaml, similar to what we're doing with storage pools.
