### ISSUE TITLE
suggestion: lxc delete should check that all requested instances exist before deleting any of them

### ISSUE THREAD

**Issue by melato** [lxc/lxd#10338]
# Required information

Client version: 5.0.0
Server version: 5.0.0

# Issue description

On multiple occations, I have accidentally deleted a container instead of deleting a snapshot. This happens because of inconsistent usage of various commands that handle snapshots:

```
lxc snapshot <instance> <snapshot>
lxc restore <instance> <snapshot>
lxc delete <instance>/<snapshot>

```
As you can see, lxc delete differs from the other two in how you specify the snapshot you want to delete. While working with snapshots, I forgot that and did this instead:

`lxc delete <instance> <snapshot>
`

I suggest that "lxc delete" checks that all requested instances or snapshots exist before deleting any of them, rather than trying to delete each one in turn.

A flag could also specify to delete what it can, as before.

This flag could be the already proposed --idempotent flag:  https://github.com/lxc/lxd/issues/2283#issuecomment-239835173

I also suggest that the existing lxc delete -f flag does the same as the proposed --idempotent flag:
> -f, --force Force the removal of running instances. Ignore any instances that do not exist.

See also https://discuss.linuxcontainers.org/t/lxc-delete-usability-accidental-deletion-of-containers/13962

# Steps to reproduce
 1. lxc launch images:alpine/3.15 a
 2. lxc snapshot a s1
 3. lxc snapshot a s2
 4. lxc restore a s1
 5. Error: Snapshot "s1" cannot be restored due to subsequent snapshot(s). Set zfs.remove_snapshots to override
 6. lxc delete a s2
 7. Error: Instance not found
 8. lxc restore a s1
 9. Error: Instance not found
 10. Result:  instance a is deleted

**Comment by tomponline** [comment]
I would prefer to not overload the `-f` flag (which means a forced stop of running instances) with the `--idempotent` flag (which would mean don't error on missing instances).

**Comment by simondeziel** [comment]
As for the flag name, there is also `--ignore-missing` that's used by `sha256sum` and friends.

**Comment by tomponline** [comment]
And also `lxc stop` would ignore if it the instance is already stopped.
