### ISSUE TITLE
Building from source - package net/netip is not in GOROOT

### ISSUE THREAD

**Issue by killua-eu** [lxc/lxd#10354]
# Required information

 * Distribution: centros-stream
 * Distribution version: 9

# Issue description

I built raft and dqlite manually. Following with  `make deps` and `make` in the lxd directory, the build fails with

```
[root@centos-ansibletest lxd]# make
CC="cc" CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)" go install -v -tags "libsqlite3"  ./...
/root/go/pkg/mod/github.com/mdlayher/ndp@v0.10.0/addr.go:6:2: package net/netip is not in GOROOT (/usr/lib/golang/src/net/netip)
make: *** [Makefile:33: build] Error 1
```

Building binaries and using go is definitely not my forte, so I plead for patience with my ignorance on how to fix a simple build issue.

# Rationale

I'm using ansible to manage lxd containers. The connection plugin for lxd containers is a simple thing requiring the lxc binary. For easier job scheduling and event-based automation I'm setting up to orchestrate everything via AWX (the frontend+scheduler to ansible). The only supported distribution method AWX upstream supports is via a kubernetes operator into k8s. The containers in the AWX pod are all centos based. Centos lacks lxd packages, also running snapd just to install the lxc binary inside a docker container is an abomination (docker containers don't have systemd, running snapd (with or without systemd) in a docker container requires privilege and security compromises, etc.). Hence I'm building lxd from source on centos with the intention to just add a lxc/lxd docker layer to my AWX pod containers.

# Steps to reproduce

```
lxc launch images:centos/9-Stream centos-ansibletest
lxc exec centos-ansibletest -- bash
```

inside the container

```
#!/bin/bash
dnf -y --enablerepo=extras swap centos-linux-repos centos-stream-repos
dnf -y config-manager --set-enabled powertools
dnf -y config-manager --set-enabled crb
dnf install-y  mc ansible-core
dnf install -y dnf-plugins-core
dnf install -y epel-release

dnf makecache --refresh
dnf install -y autoconf
dnf install -y automake
dnf install -y libtool
dnf install -y golang
dnf install -y acl
dnf install -y attr
dnf install -y dnsmasq
dnf install -y shadow-utils
dnf install -y libacl
dnf install -y libcap
dnf install -y libseccomp
dnf install -y libuv
dnf install -y libuv-devel
dnf install -y sqlite
dnf install -y sqlite-devel
dnf install -y lz4-devel
dnf install -y lz4
dnf install -y lz4-libs
```
build the whole stack

```
git clone https://github.com/canonical/raft.git
pushd ./raft
autoreconf -i
./configure --enable-example
make 
make install 
libtool --finish /usr/local/lib
PATH="/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/var/lib/snapd/snap/bin:/sbin" ldconfig -n /usr/local/lib 
popd

git clone https://github.com/canonical/dqlite.git
pushd ./dqlite
autoreconf -i
./configure
make
make install
popd

git clone https://github.com/lxc/lxd
pushd ./lxd
make deps

export CGO_CFLAGS="-I/root/go/deps/raft/include/ -I/root/go/deps/dqlite/include/"
export CGO_LDFLAGS="-L/root/go/deps/raft/.libs -L/root/go/deps/dqlite/.libs/"
export LD_LIBRARY_PATH="/root/go/deps/raft/.libs/:/root/go/deps/dqlite/.libs/"
export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

make
```

**Comment by stgraber** [comment]
You need Go 1.18 or higher.

**Comment by stgraber** [comment]
The netip package was introduced in Go 1.18 so the error you're getting is indicating you're building with an older Go version.

**Comment by killua-eu** [comment]
Right! Thanks lots
