### ISSUE TITLE
Misleading/wrong error message when adding a certificate that already exists

### ISSUE THREAD

**Issue by aivanise** [lxc/lxd#10350]
* LXC version: 5.0.0-b0287c1
   * LXD version: 5.0.0-b0287c1

# Issue description

adding the same cert twice via a token says 

"Error: Failed to create certificate: Invalid certificate type" 

when trying to add a certificate that is already in the server trust store

# Steps to reproduce

token=$(ssh root@myserver lxc config trust add --name whatever --quiet)
lxc remote add myserver $token
lxc remote remove myserver
token=$(ssh root@myserver lxc config trust add --name whatever --quiet)
lxd add remote myserver $token
Error: Failed to create certificate: Invalid certificate type 

Not sure what should happen here, either a different error message, or a silent adding like what happens if you readd a remote without a token, everything is better than this misleading message

**Comment by stgraber** [comment]
@monstermunchkin can you take a look?
