### ISSUE TITLE
`lxd-import` vs `lxc image import`

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1036]
Are there any plans to replace `lxd-import` with `lxc image import`?

```
lxc image import <tarball> [rootfs tarball] [target] [--public] [--created-at=ISO-8601]
                       [--expires-at=ISO-8601] [--fingerprint=FINGERPRINT] [prop=value]
```

```
usage: lxd-images [-h] {import} ...
```

Both command line helps are somewhat indescriptive. For example, how far is it to replace the following README.md instructions
```
$GOPATH/src/github.com/lxc/lxd/scripts/lxd-images import ubuntu --alias ubuntu
$GOPATH/src/github.com/lxc/lxd/scripts/lxd-images import lxc debian wheezy amd64
                --alias debian --alias debian/wheezy --alias debian/wheezy/amd64
```
to
```
lxc remote add cloud images.linuxcontainer.org
lxc image import cloud:ubuntu
lxc image import cloud:debian/wheezy/amd64 lxc --alias debian
```

**Comment by stgraber** [comment]
We will very likely deprecate the lxd-images import function for LXC since we've got the image server which works much better for this.

We'll however keep it around for the Ubuntu cloud images and for busybox.

We've got no plans to merge lxd-images into lxc itself as lxd-images is meant as a temporary workaround and not as something we intend on keeping on the long run.

**Comment by techtonik** [comment]
And how to get image from the server?

**Comment by stgraber** [comment]
lxc image copy source:blah local:

**Comment by stgraber** [comment]
or just lxc launch from the remote server, LXD will import it for you and cache it for 10 days

**Comment by techtonik** [comment]
Helps needs an update. But I am blocked by .https://github.com/lxc/lxd/issues/830#issuecomment-133634028

**Comment by techtonik** [comment]
@stgraber so what to do with this issue? If it won't budge, then at least a distinction between two needs to be clearly specified.

**Comment by stgraber** [comment]
Closing this as we have #1462 which will effectively kill lxd-images.
