### ISSUE TITLE
API extension: Support for `attach` feature in the API

### ISSUE THREAD

**Issue by kellianoy** [lxc/lxd#10371]
## Required information

    Distribution: NixOs
    Distribution version: 22.05
    The output of "lxc info" or if that fails:
        Kernel version: 5.15.34
        LXC version: 5.0.0
        LXD version: 5.0.0
        Storage backend in use: ZFS

## Issue description

Hello, I noticed that we can't use the attach feature only using the RESTful API that you provide. It would be useful to be able to attach volumes or networks through the API.

For instance, I would like to be able to do `lxc storage volume attach {pool} {volume} {container}` through the API to handle separate volumes for my k8s cluster.

Maybe this functionality exists, but I can't seem to find it [here](https://raw.githubusercontent.com/lxc/lxd/master/doc/rest-api.yaml).

## Fix proposition

A new path could be created, that we can access with requests to attach, delete, modify or get the attachment.

Path proposition: `/1.0/storage-pools/{name}/volumes/{type}/{volume}/attach/{container}`

**Comment by tomponline** [comment]
Are you aware you can achieve this by adding a `disk` device to the instance in question? This is what the `lxc` command does today.

**Comment by kellianoy** [comment]
@tomponline What do you mean by that ? You mean like setting the configuration of a container with a new disk ? 
I want the volume to be attached after the creation of the container, not before. Do you mean like I could do a put request to modify the disk of an instance ?

**Comment by tomponline** [comment]
Yes thats right. Everything that the `lxc` command can do can be done via the API (because `lxc` only talks LXD via its own API). 
So whilst there isn't a direct `attach` endpoint in the API, it can be done using the same approach as `lxc` command uses.

See

https://github.com/lxc/lxd/blob/master/lxc/storage_volume.go#L212-L224
https://github.com/lxc/lxd/blob/1001aa5cbba0e136d2fd90a68a9ca808cdd3b794/lxc/utils.go#L41-L62

**Comment by kellianoy** [comment]
Thank you for the answer. Sorry to have used your time.
