### ISSUE TITLE
Issue in LXD VM which create the Ubuntu 20.04

### ISSUE THREAD

**Issue by dkadkadkal** [lxc/lxd#10373]
+-------------------+---------+-----------------------+---------------------------------------------+-----------------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+-------------------+---------+-----------------------+---------------------------------------------+-----------------+-----------+
| informed-dinosaur | **ERROR** | | | VIRTUAL-MACHINE | 0 |
+-------------------+---------+-----------------------+---------------------------------------------+-----------------+-----------+

I have used the below command

**lxc config set informed-dinosaur limits.cpu 3**

**lxc config device add informed-dinosaur eth2 nic nictype=physical parent=ens5f3**

I am getting the below issue in ubuntu 20.04. Is there any possibility to resolve these issue please inform me.

KVM internal error. Suberror: 3
extra data[0]: 0x0000000080000b0e
extra data[1]: 0x0000000000000031
extra data[2]: 0x0000000000000981
extra data[3]: 0x000000000002b570
KVM internal error. Suberror: 3
extra data[0]: 0x0000000080000b0e
extra data[1]: 0x0000000000000031
extra data[2]: 0x0000000000000d82
extra data[3]: 0x000000000002b570
RAX=0000000000000000 RBX=0000000000000009 RCX=0000000000000005 RDX=0000000000000009
RSI=ffff96a1801b8080 RDI=ffff96a1bcd2d400 RBP=ffffb1ab80067ce0 RSP=ffffb1ab80067ce0
R8 =0000000000000000 R9 =0000000000000000 R10=ffff96a1bcd1b148 R11=0000000000000000
R12=ffff96a1bcd2d400 R13=ffff96a1801b8080 R14=0000000000000009 R15=ffff96a1bcd2d380
RIP=ffffffff914ddb14 RFL=00010086 [--S--P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 0000000000000000 ffffffff 00c00000
CS =0010 0000000000000000 ffffffff 00a09b00 DPL=0 CS64 [-RA]
SS =0000 0000000000000000 ffffffff 00c00000
DS =0000 0000000000000000 ffffffff 00c00000
FS =0000 0000000000000000 ffffffff 00c00000
GS =0000 ffff96a1bcd00000 ffffffff 00c00000
LDT=0000 0000000000000000 ffffffff 00c00000
TR =0040 fffffe0000075000 0000206f 00008b00 DPL=0 TSS64-busy
GDT= fffffe0000073000 0000007f
IDT= fffffe0000000000 00000fff
CR0=80050033 CR2=ffffb1ab80067cd8 CR3=000000000e40a001 CR4=001606a0
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000
DR6=00000000fffe0ff0 DR7=0000000000000400
EFER=0000000000000d01
Code=0b 48 8b 75 f0 e9 48 ff ff ff 66 0f 1f 44 00 00 55 48 89 e5 <41> 57 41 56 41 55 41 54 49 89 fc 53 48 83 ec 08 4c 8b af 30 01 00 00 48 8b 5f 48 41 83 bd
RAX=0000000000000000 RBX=0000000000000000 RCX=0000000000000000 RDX=0000000000000000
RSI=ffffffff91c0156a RDI=ffffffff92603d78 RBP=ffffffff92603d79 RSP=ffffb1ab80004000
R8 =0000000000000000 R9 =0000000000000000 R10=0000000000000000 R11=0000000000000000
R12=0000000000000000 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=ffffffff91c009dd RFL=00010056 [---ZAP-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 0000000000000000 ffffffff 00c00000
CS =0010 0000000000000000 ffffffff 00a09b00 DPL=0 CS64 [-RA]
SS =0000 0000000000000000 ffffffff 00c00000
DS =0000 0000000000000000 ffffffff 00c00000
FS =0000 0000000000000000 ffffffff 00c00000
GS =0000 ffff96a1bcc00000 ffffffff 00c00000
LDT=0000 0000000000000000 ffffffff 00c00000
TR =0040 fffffe0000003000 0000206f 00008b00 DPL=0 TSS64-busy
GDT= fffffe0000001000 0000007f
IDT= fffffe0000000000 00000fff
CR0=80050033 CR2=ffffb1ab80003ff8 CR3=000000000e40a001 CR4=001606b0
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000
DR6=00000000fffe0ff0 DR7=0000000000000400
EFER=0000000000000d01
Code=75 12 65 48 89 3c 25 f8 5f 00 00 65 48 8b 24 25 d0 ab 01 00 <57> ff 77 f8 c3 48 83 04 24 80 e8 34 ff ff ff e8 ef 12 00 00 eb 1c 66 66 2e 0f 1f 84 00 00

**Here kernel is getting hang**

mavenir@blr-r740:~$ **lxc config show informed-dinosaur --expanded**
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20220419)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20220419"
  image.type: disk-kvm.img
  image.version: "20.04"
  limits.cpu: "3"
  volatile.base_image: 97251b450155a2daa46b88cab190322430d4c1f0729df5c791a89a989ee5faa3
  volatile.eth0.host_name: tap696981bc
  volatile.eth0.hwaddr: 00:16:3e:f3:5f:6e
  volatile.last_state.power: RUNNING
  volatile.uuid: 22b6de3c-c5a2-4761-bf2a-421f1eb2a1b0
  volatile.vsock_id: "40"
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  eth1:
    nictype: physical
    parent: ens5f4
    type: nic
  eth2:
    nictype: physical
    parent: ens5f3
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

**mavenir@blr-r740:~$ lxc monitor**
location: none
metadata:
  context:
    listener: b6c8e065-c1b1-4bfb-b68a-3d2702d84899
    local: /var/snap/lxd/common/lxd/unix.socket
    localOnly: "false"
    remote: '@'
  level: dbug
  message: Event listener server handler started
timestamp: "2022-05-06T10:37:14.83578848Z"
type: logging

**Comment by stgraber** [comment]
This is a hypervisor crash (QEMU) so not something we can do anything about in LXD itself :(

We've seen this a few times in the past, I'd recommend you try to increase `limits.memory` to `2GiB` or more, we've seen this help in the past.

If that doesn't help, look at `dmesg` for a potential hardware/kernel error.

**Comment by stgraber** [comment]
Let us know if bumping the amount of memory helps with the issue, if it doesn't, it may be worth reporting the crash to QEMU upstream.
