### ISSUE TITLE
Cant move container from LXD5 to LXD4

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#10391]
If you try to move an instance from lxd5 to lxd4 it fails with the error 

`Error: Failed instance creation: Failed creating instance record: Unknown configuration key: volatile.cloud-init.instance-id`

If you copy instead it doesn't fail

**Comment by stgraber** [comment]
Right, that's normal, newer LXD can have new configuration keys which older releases don't support.
In this case, it's `volatile.cloud-init.instance-id` which LXD 4.0 doesn't have.

When you `lxc move`, all `volatile.*` config keys are kept and sent to the target server, when you `lxc copy`, the volatile keys are all reset as the new instance is expected to be able to live alongside the old new.

If you want `lxc move` to work in this particular case, you can do a `lxc config unset NAME volatile.cloud-init.instance-id` prior to the `lxc move`.
