### ISSUE TITLE
Static analysis github action

### ISSUE THREAD

**Issue by markylaing** [lxc/lxd#10392]
The static analysis script we are currently running works well for the majority of cases, however it does need to be run in jenkins along with other integration tests which can take time to queue. Additionally, we could use `golangci-lint` to invoke many more linters and strictly enforce a code style.

This issue will be addressed with numerous PRs. We first need to fix linting errors from the default linters enabled by `golangci-lint`, then those from the extra linters we will enable. Finally we'l set up a github action for static analysis to run separately from the main test suite.

See discussion in https://github.com/lxc/lxd/pull/10384.

**Comment by markylaing** [comment]
@tomponline @stgraber I'm having issues enabling the [errcheck linter](https://github.com/kisielk/errcheck) because of [this issue](https://github.com/kisielk/errcheck/issues/55).

I think the linter is too useful to discard entirely but there are no options to ignore all deferred calls. We have five options as far as I can tell:
1. Disable the linter entirely.
2. Inline a `//nolint:errcheck` comment on all deferred calls.
3. Add a massive list of functions to ignore to the `.golangci.yml` configuration file for `golangci-lint` (I've already found this to be difficult to work with).
4. Wrap all deferred calls that return an error with another function, e.g. `defer f.Close()` becomes `defer func(){ _ = f.Close()}()`.
5. Big refactor to expand our usage of the `reverter` package. We could change reverter hook functions to return an error and log it if it is non-nil on execution. We'd then change most if not all deferred function calls to use a reverter instead.

Probably some combination of the above is necessary. I've spent quite a while trying to simply ignore errors on defer but have found no way of doing it.

**Comment by tomponline** [comment]
From IRC:

* for revert, I agree we can update the revert function passed in to return an error and have the reverter log (as a warning) the reversion error
* for defer, I think we just need to handle the errors based on what is appropriate (it may be that the end result is that the defer is removed and the cleanup on success/failure is handled properly rather than partially using defer)
