### ISSUE TITLE
Remove user.meta-data config key

### ISSUE THREAD

**Issue by pyfisch** [lxc/lxd#10417]
In [[LXD] First class cloud-init support ](https://discuss.linuxcontainers.org/t/lxd-first-class-cloud-init-support/12559/18) @stgraber noted that `user.meta-data` "will just go away completely".

Is this still the plan? I don't have a specific use-case however I contemplated to use it pass additional data to cloud-init before deciding that I can just as easily modify the scripts or YAML.

**Comment by stgraber** [comment]
`user.meta-data` is being replaced by `cloud-init.meta-data`. If the latter works for you, use that as it will be more future proof.

LXD itself doesn't have any particular handling of `user.meta-data`, it's normally handled by templates in the images. As we don't control all of those, we don't have a clear timeline for the full disappearance of `user.user-data` in favor of `cloud-init.user-data`.

**Comment by pyfisch** [comment]
I'm confused. First you talk about `user.meta-data` but then about `user.meta-data`, which are different config keys.

The `user.meta-data` config key has special handling: [it is added to the container meta-data in the instance API](https://github.com/lxc/lxd/blob/620c5aa64336002d3358ef2c41a89068cac1ade4/lxd-agent/devlxd.go#L118-L119).
