### ISSUE TITLE
'MISSING' added to cloud-init userdata 

### ISSUE THREAD

**Issue by TheRealFalcon** [lxc/lxd#10422]
This may be a regression or duplicate of #10231 .

# Required information

 * Distribution: Jammy
 * The output of "lxc info": https://paste.ubuntu.com/p/JbtrDY5QZT/
 
# Issue description

On a Jammy VM (not container), I have a "%h" in my userdata. This gets transformed into `%!h(MISSING)` on my instance.

# Steps to reproduce
```
newt:~ $ cat /tmp/bug.yaml 
#cloud-config
bootcmd:
  - echo "Hello %h from cloud-init"

newt:~ $ lxc launch ubuntu-daily:jammy bug --vm -c cloud-init.user-data="$(cat /tmp/bug.yaml)"
Creating bug
Starting bug
newt:~ $ lxc shell bug
root@bug:~# curl --unix-socket /dev/lxd/sock http://1.0/1.0/config/cloud-init.user-data
#cloud-config
bootcmd:
  - echo "Hello %!h(MISSING) from cloud-init"
```

**Comment by stgraber** [comment]
@monstermunchkin can you take care of this one?
