### ISSUE TITLE
Why Shorewall/Iptables writes logs into guest LXC container's /var/log/syslog?

### ISSUE THREAD

**Issue by robozb** [lxc/lxd#10444]
Thank you so much any infos!

Regards: Bela

**Comment by stgraber** [comment]
Support questions should be asked at https://discuss.linuxcontainers.org

Most likely what you're seeing here though is those logs coming from the kernel and therefore being visible to all containers.

**Comment by robozb** [comment]
OH, ok, sorry! Thank you!
