### ISSUE TITLE
Error: read unix @->/proc/self/fd/30/forkfile.sock: read: connection reset by peer 

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#10448]
Pushing a directory (in the case something with a `.git` folder) eventually leads to `Error: read unix @->/proc/self/fd/30/forkfile.sock: read: connection reset by peer ` without completing the transfer.

Command
`lxc file push -r /var/www/LxdMosaic lxdmosaic-snap-build-01/root`

LXD Info

```
snap list lxd
Name  Version      Rev    Tracking     Publisher   Notes
lxd   git-511bfc3  23114  latest/edge  canonical✓  -
```

**Comment by tomponline** [comment]
Can we get the debug logs from the server too please as nothing to go on in your report so far I'm afraid. Also please could you expand on "eventually" does it sometimes fail or does it always fail but at different intervals?

**Comment by turtle0x1** [comment]
Its inconsistent where it stops running...

I've forgot the command I need for the best debug logs, `lxc monitor --debug` isn't particularly interesting, could you remind me?

**Comment by tomponline** [comment]
Are we talking seconds or minutes? Are you running it repeatedly to get it to fail?

Yes runninh lxc monitor --debug --pretty at the same time should get us the requests occurring on the server at the time it disconnects. Is it only pushing directories that cause this? Are all files accessible within?

**Comment by tomponline** [comment]
Running the lxc command with --debug may reveal something useful too.

**Comment by turtle0x1** [comment]
There is no definitive time to failure, sometimes its 10-20s sometimes its over 1 minute. 

It also appear doesn't fail consistently at specific file or folder.

There are lots of seemingly uninteresting lines like;

```
INFO   [2022-05-23T21:40:23+01:00] Action: instance-file-pushed, Source: /1.0/instances/snap-lxdmosaic-02  path=/root/LxdMosaic/node_modules/@fortawesome/fontawesome-free/svgs/solid/teeth.svg
DEBUG  [2022-05-23T21:40:23+01:00] Handling API request                          ip=@ method=POST protocol=unix url="/1.0/instances/snap-lxdmosaic-02/files?path=%2Froot%2FLxdMosaic%2Fnode_modules%2F%40fortawesome%2Ffontawesome-free%2Fsvgs%2Fsolid%2Ftemperature-high.svg" username=blah
```
_I tried a later image to test if it was an error with an old image, ignore the name change, I can go back to the original intsance if require_

> Is it only pushing directories that cause this? Are all files accessible within?
It doesn't happen on squash.fs files, it does happen on other directories, if i do the old `chmod -R 777 /path/to/some/dir` that doesn't fix it either

**Comment by stgraber** [comment]
I've managed to reproduce this by transferring an entire Linux kernel tree, looking into it now.

**Comment by stgraber** [comment]
forkfile exits with a 0 return code, so that suggests we're somehow hitting the auto-exit code.
