### ISSUE TITLE
Documentation lacks of "operations" manual and limitations

### ISSUE THREAD

**Issue by jadjay** [lxc/lxd#10446]
Hi there,

I was reading the documentation, seeking for clear instructions on how to transfer properly instances between remotes with few differences (storage names, network configuration, etc...).

As I can see, there no such documentation : documentation is mostly on configuration, specials functionnality like cloud-init.

But it seems that it lacks "operational manual", like day to day actions, built actions, snapshot, backups, and so...

This is not an aggressive remark, it's just ascertainment and I think that it could be a good thing to create a chapter for those.

I based my reads on : 
* https://linuxcontainers.org/lxd/docs/master/
* https://linuxcontainers.org/lxd/advanced-guide/

I don't take account of @stgraber blogs, as I think it can't be consider as an up-to-date, trusty and as official as the inline documentation 😋 . Hence it's a damn good reference 😄 
Hashtag No offence 😸

**Comment by jadjay** [comment]
I add the need of "good practices" for every "basic needs" : backup, remote copy, creation, use of profile etc...

**Comment by tomponline** [comment]
I believe @ru-fu is working through our docs and refreshing them with proper usage examples section by section.

**Comment by tomponline** [comment]
If you have a specific question that is missing from the docs today please could you post on the forum https://discuss.linuxcontainers.org thanks

**Comment by ru-fu** [comment]
Yes, I agree 100%, and as Tom says, the plan is to make the documentation more instructional bit by bit - we've started with the networking documentation and are currently working on storage.
There's also a lot of helpful information in the Tutorials on the forum and in @stgraber 's YouTube videos. For now, most of that content is just linked, but we want to incorporate the most relevant parts into the docs as well.

**Comment by jadjay** [comment]
I may participate with pleasure, but I need "someone over my shoulder" who may correct if it's good practise or not.

Is there any way to do so?

**Comment by ru-fu** [comment]
If you have any "how to"s that you'd like to contribute, either based on your own experience or on the YouTube videos, that would be highly appreciated. :+1: 
You could either make pull requests with new sections or pages to extend the current documentation (and I can review to make sure they fit in nicely), or just add them as tutorials on the forum and we can integrate them in the docs later.

**Comment by tomponline** [comment]
The documentation has now been much improved. With usage examples for common actions. 
 
And we will continue to improve it.

I'll close this for now, but please do open an issue or pull request if you feel specific items are still missing.
