### ISSUE TITLE
VMs on ZFS pools unbootable on hosts running kernel >=5.17.

### ISSUE THREAD

**Issue by dmtrbm** [lxc/lxd#10464]
Every VM drops into grub shell, unable to detect partitions.

```
grub> ls
(proc) (hd0)
```

Tested on Arch, openSUSE Tumbleweed, Fedora 36, all with ZFS 2.1.4. Both native (where available) and snaps versions 4.24/5/5.1.

Same VMs boot as expected if the host is rebooted with kernel <=5.16.20.

**Comment by stgraber** [comment]
This will most likely need to move to https://github.com/zfsonlinux/zfs as LXD isn't doing anything special on this kernel release.
Is there anything useful in `lxc info --show-log NAME`?

My gut feeling is that something changed in Linux 5.17 with regard to io_uring which is tickling ZFS zvol the wrong way.

@brauner I believe you recently mentioned something related to io_uring and newer kernels breaking, could it be related?

**Comment by brauner** [comment]
Hm, io_uring changes shouldn't cause this so not sure...

**Comment by stgraber** [comment]
We're rolling out QEMU 7.0 with LXD 5.2 so maybe that will help, who knows.

**Comment by dmtrbm** [comment]
>Is there anything useful in lxc info --show-log NAME?

Nope, you can zfs clone its zvol and boot it with qemu/libvirt 6.2/7. It does not affect btrfs/lvm pools.

**Comment by stgraber** [comment]
@adamcstephens that's pretty weird but also likely quite a different issue. In your case you appear to be using LVM?

**Comment by stgraber** [comment]
@dmtrbm any chance you could retry the snap as we now have LXD 5.2 in there which comes with QEMU 7.0 so maybe that helped somehow?

**Comment by adamcstephens** [comment]
> @adamcstephens that's pretty weird but also likely quite a different issue. In your case you appear to be using LVM?

No, I'm using ZFS. I'll downgrade the kernel and test again to see if it still occurs.

**Comment by stgraber** [comment]
> > @adamcstephens that's pretty weird but also likely quite a different issue. In your case you appear to be using LVM?
> 
> No, I'm using ZFS. I'll downgrade the kernel and test again to see if it still occurs.

Oh, sorry, the /dev/XYZ path looked like an LVM pattern. I'm used to /dev/zvol/XYZ for the ZFS ones :)

**Comment by stgraber** [comment]
@adamcstephens a `zfs get all DATASET` during and after would be interesting too to see what size property may have changed.

**Comment by adamcstephens** [comment]
> @adamcstephens a `zfs get all DATASET` during and after would be interesting too to see what size property may have changed.

The zfs dataset doesn't change, before or after, and still shows the correct data size. 

```
NAME                                        PROPERTY              VALUE                  SOURCE
fast/lxd-snap/virtual-machines/nixos.block  type                  volume                 -
fast/lxd-snap/virtual-machines/nixos.block  creation              Tue May 31 17:56 2022  -
fast/lxd-snap/virtual-machines/nixos.block  used                  2.93G                  -
fast/lxd-snap/virtual-machines/nixos.block  available             307G                   -
fast/lxd-snap/virtual-machines/nixos.block  referenced            2.93G                  -
fast/lxd-snap/virtual-machines/nixos.block  compressratio         2.31x                  -
fast/lxd-snap/virtual-machines/nixos.block  reservation           none                   default
fast/lxd-snap/virtual-machines/nixos.block  volsize               74.5G                  local
...
```

I rebooted to jammy 5.15.0-33.34 and everything works correctly. I'm able to start and use the volume, even the one that I provisioned while on 5.17. 

Rebooting into 5.17.9-051709 and the problem occurs again. The correct disk is actually mounted, as the bootloader does start, but since the VM cannot access the entire disk the boot fails. This is consistent with @dmtrbm as you can see they are getting into grub.

I tried to test 5.18.0-051800 but zfs-dkms fails to compile for this newer kernel.

**Comment by stgraber** [comment]
That's pretty weird as you're seeing this through fdisk outside of LXD... Does the same VM behave properly after booting back on 5.15?

Trying to figure out if it's an issue that's modifying/damaging the zvol or if it's some kind of odd read issue.

**Comment by adamcstephens** [comment]
@stgraber yes, everything works properly when reverting to 5.15. There appears to be no data loss and the VM behaves properly. 

It seems when the zvol dev is created on VM start it has the wrong configuration.

**Comment by cbc02009** [comment]
not sure exactly when this was fixed, but I can now create VMs again with linux kernel `5.18.11-arch1-1`

**Comment by stgraber** [comment]
Okay, so that seems to confirm what I suspected, it must have been a kernel io_uring regression which has now been addressed.
