### ISSUE TITLE
DHCP Doesnt work by default

### ISSUE THREAD

**Issue by PenguinzPlays** [lxc/lxd#10470]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-33-generic
   * LXC version:
   * LXD version:  5.1
   * Storage backend in use: btrfs block drive (/dev/sdb1)

# Issue description
My LXD containers are not pulling DHCP, no address is assigned nor are any DNS nameservers.
Container OS: Ubuntu/22.04/cloud
Network: LxdBr0 (auto-created by LXD init)
Managed: yes
Config tried: default and the following:
config:
  dns.domain: devpod.penguintech.group
  ipv4.address: 10.108.120.1/24
  ipv4.dhcp: "true"
  ipv4.dhcp.ranges: 10.108.120.2-10.108.120.200
  ipv4.firewall: "false"
  ipv6.address: fd42:b34b:c13c:f3d4::1/64
  ipv6.firewall: "true"
Profile:
`config:
  boot.autostart: "true"
  boot.autostart.delay: "10"
  limits.cpu: "2"
  limits.memory: 8GB
  security.nesting: "true"
  security.syscalls.intercept.mknod: "true"
  security.syscalls.intercept.setxattr: "true"
  snapshots.expiry: 3d
  snapshots.schedule: '@daily'
description: Default LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    size: 50GB
    type: disk
`

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

Do a default setup of LXD and deploy 22.04/cloud image and it doesnt get DHCP, additionally dhclient forever hangs. When I go manually in and add a static IP, I can reach out.  I later figure out this is caused by the fact the LxdBr0 is not added to UFW, which is enabled by default in 22.04. Maybe, like Docker, add a rule to allow the interface to dnsmasq as part of init?

# Steps to reproduce

 1. LXD Init
 2. lxc launch image:ubuntu/22.04/cloud
 3. Cry you have to go statically apply IP and your cloud-init fails (no network section in cloud-init)

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 `
[ 5165.321737] [UFW BLOCK] IN=lxdbr0 OUT=lxdbr0 PHYSIN=veth0ae6e472 PHYSOUT=vethc715713f MAC=ff:ff:ff:ff:ff:ff:00:16:3e:82:57:c0:08:00 SRC=0.0.0.0 DST=255.255.255.255 LEN=328 TOS=0x10 PREC=0x00 TTL=128 ID=0 PROTO=UDP SPT=68 DPT=67 LEN=308
[ 5179.863129] [UFW BLOCK] IN=lxdbr0 OUT= PHYSIN=veth0ae6e472 MAC=00:16:3e:fc:07:60:00:16:3e:82:57:c0:86:dd SRC=fe80:0000:0000:0000:0216:3eff:fe82:57c0 DST=fe80:0000:0000:0000:0216:3eff:fefc:0760 LEN=84 TC=0 HOPLIMIT=64 FLOWLBL=499629 PROTO=UDP SPT=58468 DPT=53 LEN=44
[ 5185.005806] [UFW BLOCK] IN=lxdbr0 OUT=lxdbr0 PHYSIN=vethc715713f PHYSOUT=veth0ae6e472 MAC=33:33:00:01:00:02:00:16:3e:f6:bd:93:86:dd SRC=fe80:0000:0000:0000:0216:3eff:fef6:bd93 DST=ff02:0000:0000:0000:0000:0000:0001:0002 LEN=90 TC=0 HOPLIMIT=1 FLOWLBL=364419 PROTO=UDP SPT=546 DPT=547 LEN=50
[ 5194.517196] [UFW BLOCK] IN=lxdbr0 OUT=lxdbr0 PHYSIN=veth0ae6e472 PHYSOUT=vethc715713f MAC=ff:ff:ff:ff:ff:ff:00:16:3e:82:57:c0:08:00 SRC=0.0.0.0 DST=255.255.255.255 LEN=328 TOS=0x10 PREC=0x00 TTL=128 ID=0 PROTO=UDP SPT=68 DPT=67 LEN=308
[ 5199.888669] [UFW BLOCK] IN=lxdbr0 OUT= PHYSIN=veth0ae6e472 MAC=00:16:3e:fc:07:60:00:16:3e:82:57:c0:86:dd SRC=fe80:0000:0000:0000:0216:3eff:fe82:57c0 DST=fe80:0000:0000:0000:0216:3eff:fefc:0760 LEN=84 TC=0 HOPLIMIT=64 FLOWLBL=120128 PROTO=UDP SPT=36450 DPT=53 LEN=44
[ 5203.113083] [UFW BLOCK] IN=enp1s0 OUT= MAC=0c:c4:7a:88:d4:3a:3c:2c:99:ec:63:7a:08:00 SRC=185.156.73.107 DST=107.191.43.209 LEN=40 TOS=0x00 PREC=0x00 TTL=246 ID=36393 PROTO=TCP SPT=42733 DPT=22890 WINDOW=1024 RES=0x00 SYN URGP=0
[ 5205.549580] [UFW BLOCK] IN=enp1s0 OUT= MAC=0c:c4:7a:88:d4:3a:3c:2c:99:ec:63:7a:08:00 SRC=78.128.113.250 DST=107.191.43.209 LEN=40 TOS=0x00 PREC=0x00 TTL=245 ID=30195 PROTO=TCP SPT=59294 DPT=2652 WINDOW=1024 RES=0x00 SYN URGP=0
`
 - [ ] Container log (`lxc info NAME --show-log`)
 `config:
  boot.autostart: "true"
  boot.autostart.delay: "10"
  limits.cpu: "2"
  limits.memory: 8GB
  security.nesting: "true"
  security.syscalls.intercept.mknod: "true"
  security.syscalls.intercept.setxattr: "true"
  snapshots.expiry: 3d
  snapshots.schedule: '@daily'
description: Default LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    size: 50GB
    type: disk
name: devpod
used_by:
- /1.0/instances/archer-devpod
- /1.0/instances/test-devpod
root@devpod:~/devpod# lxc info test-devpod --show-log
Name: test-devpod
Status: RUNNING
Type: container
Architecture: x86_64
PID: 27885
Created: 2022/05/28 04:14 UTC
Last Used: 2022/05/28 04:24 UTC

Resources:
  Processes: 15
  Disk usage:
    root: 98.29MiB
  CPU usage:
    CPU usage (in seconds): 2
  Memory usage:
    Memory (current): 38.88MiB
  Network usage:
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)
    eth0:
      Type: broadcast
      State: UP
      Host interface: vethc715713f
      MAC address: 00:16:3e:f6:bd:93
      MTU: 1500
      Bytes received: 994B
      Bytes sent: 7.90kB
      Packets received: 7
      Packets sent: 48
      IP addresses:
        inet6: fd42:b34b:c13c:f3d4:216:3eff:fef6:bd93/64 (global)
        inet6: fe80::216:3eff:fef6:bd93/64 (link)

Log:

lxc test-devpod 20220528042400.443 WARN     conf - conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc test-devpod 20220528042400.443 WARN     conf - conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc test-devpod 20220528042400.444 WARN     conf - conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc test-devpod 20220528042400.444 WARN     conf - conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc test-devpod 20220528042429.820 WARN     conf - conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc test-devpod 20220528042429.821 WARN     conf - conf.c:lxc_map_ids:3598 - newgidmap binary is missing
`

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 `
root@devpod:~/devpod# cat /var/snap/lxd/common/lxd/logs/lxd.log
time="2022-05-28T04:23:36Z" level=warning msg=" - Couldn't find the CGroup network priority controller, network priority will be ignored"
`
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
`root@devpod:~/devpod# lxc monitor
location: none
metadata:
  context:
    listener: 10357a73-5986-426e-acfd-f64b88334429
    local: /var/snap/lxd/common/lxd/unix.socket
    remote: '@'
  level: debug
  message: Event listener server handler started
timestamp: "2022-05-28T04:37:03.272299594Z"
type: logging
fm`

**Comment by PenguinzPlays** [comment]
To be clear..  I know the issue here is UFW... but LXD init should add an entry for LXDBr0 in UFW / iptables.

**Comment by stgraber** [comment]
It's usually very bad practice and actually against most distributions packaging policies to alter the system configuration of another package, so we're not likely to go and edit ufw configuration for you.

Instead we do have documentation for what's needed in a number of those cases:
https://linuxcontainers.org/lxd/docs/latest/howto/network_bridge_firewalld/#ufw-add-rules-for-the-bridge
