### ISSUE TITLE
VM exec broken

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10506]
One of these commits broke VM exec (from PR https://github.com/lxc/lxd/pull/10471):

Commit that broke it:
https://github.com/tarruda/lxd/commit/e667a8a73ace0c9ef0d938eae666268bce412a8d

**Comment by tarruda** [comment]
lxc/lxd@53d793c3de
lxc/lxd@3133d41e16
lxc/lxd@b1d76cc3c7
