### ISSUE TITLE
Client certificate add token should have an expiry

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#10505]
When running `lxc config trust add --name foo`, a token is created with a corresponding operation. That operation remains running until a client consumes the token via `lxc remote add my-rmt <token>`. If the client forgets to consume it, the operation will be left running indefinitely which is not ideal, especially since it relates to granting access to the remote.

To avoid the problem, tokens should have an expiry after which they become unusable and the operation is closed.

**Comment by tomponline** [comment]
Agree with premise. But also worth noting the tokens only remain until lxd is restarted next, not indefinitely.

**Comment by stgraber** [comment]
Right, I've actually seen more concerns for the other way around. That is, LXD restarting and the remote join token no longer being valid.

For cluster join, I'd probably be happy with say a 3h default expiry, documented in doc/cluster.md as realistically, you're not going to be joining a cluster a week later.

For remote add, I don't think those should expire at all unless directly requested by the user.

I also think we should have both kind persist across LXD restarts. For cluster, that may help with LXD crashes and for remote add, well, this would be a necessity for the default of no expiry.

We should be able to achieve this pretty easily with just an extra `tokens` DB table to hold them.
We'd effectively have LXD spawn Token type operations on startup from what's saved in the DB.

**Comment by simondeziel** [comment]
IMHO remote add token should expire too, people forget about things all the time. I myself found an unused token left over from a previous test. How about 24h? Or even 7d?

**Comment by tomponline** [comment]
> We should be able to achieve this pretty easily with just an extra `tokens` DB table to hold them.
> We'd effectively have LXD spawn Token type operations on startup from what's saved in the DB.

I'm thinking perhaps just use a dedicated table for the tokens concept without linking it to (and respawning) operations. Would be more inline with other entity types (instances, warnings etc) especially if they are to cease being transient like operations are.

**Comment by tomponline** [comment]
Originally we didn't go that route because we wanted tokens to be back ported to 4.0 LTS without a schema change. But if we are introducing a schema change it would be more consistent to just use the table as authoritative truth.

**Comment by stgraber** [comment]
> I'm thinking perhaps just use a dedicated table for the tokens concept without linking it to (and respawning) operations. Would be more inline with other entity types (instances, warnings etc) especially if they are to cease being transient like operations are.

Yeah but the fact that token are operations is now API... That's how we list and revoke them from the CLI.
I'm not necessarily opposed to a full fledged `/1.0/tokens` type API, but we're going to have to keep backward compatibility at least for a little while.

**Comment by stgraber** [comment]
> IMHO remote add token should expire too, people forget about things all the time. I myself found an unused token left over from a previous test. How about 24h? Or even 7d?

It depends on what you're doing with them. The requests I've had are from people who do cloud-like hosting and that's the creds that are issued to individual users. Having those expire at all is problematic.

**Comment by stgraber** [comment]
Well, to them, the token is no worse than a password or client certificate.

**Comment by stgraber** [comment]
I'm not fundamentally opposed to having a configurable default expiry, but when unset, I would expect them no to expire, to keep the current behavior. Again, I think it's fine for cluster join tokens to expire by default as those have no reason to be long lived and also are far more dangerous than remote join token (well, at least compared to a remote join token that's restricted to a project).
