### ISSUE TITLE
Error: Instance snapshot record count doesn't match instance snapshot volume record count after upgrade to lxd 5.2

### ISSUE THREAD

**Issue by robe2** [lxc/lxd#10501]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 20.04.4 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-109-generic
   * LXC version:  5.2
   * LXD version: 5.2
   * Storage backend in use: zfs

# Issue description

After the snap upgrade from 5.1 to 5.2 I noticed several of my containers were failing doing their scheduled daily snapshot which have a retention of 30 days.

The error in many cases was: `Error: Instance snapshot record count doesn't match instance snapshot volume record`

I've detailed the issue in - https://discuss.linuxcontainers.org/t/lxc-snapshot-and-lxc-start-error-instance-snapshot-record-count-doesnt-match-instance-snapshot-volume-record-count/14245 .  The issue is mostly with relatively old containers.

# Steps to reproduce

 1. lxc snapshot somecontainer

Other people have complained on the above thread about the same issue, and that reverting to lxd 5.1 fixed the issue.  So I suspect maybe it's just the lxd 5.2 checking is more robust and that these issues might have existed for a while, but lxd 5.2, prevents normal snapshot / restart when these issues are noted.

# Information to attach

I confirmed in the database, that the counts are off on these with these queries:

```
SELECT count(*) FROM storage_volumes AS v INNER JOIN storage_volumes_snapshots AS vs ON v.id = vs.storage_volume_id WHERE v.name = 'container-name';


SELECT count(*) FROM instances AS v INNER JOIN instances_snapshots AS vs ON v.id = vs.instance_id WHERE v.name = 'container-name';

```

Return different coutns for the instances with the issue

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ x ] Container configuration (`lxc config show NAME --expanded`)
  architecture: x86_64
  config:
    environment.LANG: en_US.UTF-8
    environment.LC_ALL: en_US.UTF-8
    environment.LC_COLLATE: POSIX
    limits.cpu: "2"
    limits.cpu.allowance: 5%
    limits.memory: 4GB
    raw.lxc: lxc.mount.entry = none dev/shm tmpfs rw,nosuid,nodev,create=dir
    snapshots.expiry: 30d
    snapshots.schedule: 20 18 * * *
    volatile.eth0.host_name: veth5a7a2944
    volatile.eth0.hwaddr: 00:16:3e:c6:1e:15
    volatile.idmap.base: "0"
    volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
    volatile.uuid: 31e6e46c-4511-4e4f-944f-b9827dc06b3b
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      size: 50GB
      type: disk
  ephemeral: false
  profiles:
  - default
  stateful: false
  description: ""

**Comment by tomponline** [comment]
This is historical issue has been surfaced by a new consistency check in the function that writes out the backup.yaml file at instance start time in lxd 5.2 and is checking the instance snapshot and instance snapshot volume records are consistent.

As its undesirable to have the database and backup.yaml in an inconsistent state I think the best plan is to add a patch to lxd to repair the database on next start by recreating the missing instance snapshot volume db records using a default config.

**Comment by tomponline** [comment]
Check that highlighted the problem snapshots 

https://github.com/lxc/lxd/blob/40ed5bfcfaca0ae3e2f2b21486d474e546fb61d9/lxd/storage/backend_lxd.go#L4591

**Comment by tomponline** [comment]
> Also we need to review whether the instance snapshot record creation revert is working correctly for failed snapshots.

I've checked and can't see a way in the current code base that if a snapshot failed midway through that the instance snapshot record and the instance snapshot volume record wouldn't be deleted correctly, so suspect these mismatches records are due historical problems.

**Comment by tomponline** [comment]
Working on this now.
