### ISSUE TITLE
Physical PCI Devices - qemu.conf always assigns `bootIndex` arg

### ISSUE THREAD

**Issue by masnax** [lxc/lxd#10531]
# Issue Description
When adding a physical PCI device to an instance, the corresponding block in qemu.conf will contain a `bootIndex` argument, but not all drivers will support this.

# Steps to reproduce

`lxc init images:ubuntu/22.04/cloud vm --vm`
`lxc config device add vm dev pci address=...`
`lxc start vm         # This fails.`

Output of `lxc info --show-log vm`:
`qemu-system-x86_64:/var/log/lxd/vm/qemu.conf:266: Property 'vfio-pci.bootIndex' not found`

# Information to attach
This seems to be connected to a3cf5ec0d, particularly [here](https://github.com/lxc/lxd/commit/a3cf5ec0d1968ae70574a4d66cb667c20ba36cc1#diff-451c9f8fe94f3f932d8bb04a03d9dd963155f1b00f138137e7886595ae39dcb4R666-R683), with the following snippet: 
```go
type qemuPCIPhysicalOpts struct {
	dev         qemuDevOpts
	devName     string
	pciSlotName string
	bootIndex   int
}

func qemuPCIPhysicalSections(opts *qemuPCIPhysicalOpts) []cfgSection {
	deviceOpts := qemuDevEntriesOpts{
		dev:     opts.dev,
		pciName: "vfio-pci",
		ccwName: "vfio-ccw",
	}

	entries := append(qemuDeviceEntries(&deviceOpts), []cfgEntry{
		{key: "host", value: opts.pciSlotName},
		{key: "bootIndex", value: fmt.Sprintf("%d", opts.bootIndex)},
	}...)
```

**Comment by tomponline** [comment]
@masnax thanks! Out of interest what sort of PCI device were you passing through to find this?

**Comment by masnax** [comment]
@tomponline Oh just the audio device for my GPU.
