### ISSUE TITLE
Unable to set some default volume config keys

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#10540]
According to https://linuxcontainers.org/lxd/docs/master/howto/storage_configure/, one should be able to set default volume config keys like that but that doesn't work:

```
$ lxc storage set default volume.snapshots.expiry=31d
Error: Invalid option "volume.snapshots.expiry"
```

**Comment by stgraber** [comment]
Yeah, those are pretty much hardcoded and not very consistent, shouldn't be very hard to fix but we'll likely find some corner cases.

**Comment by stgraber** [comment]
Yeah, I think the behavior I'd expect is for any such `volume.*` key to be copied with the `volume.` prefix stripped at volume creation time. So unlike profiles, altering `volume.XYZ` on the pool after the fact would not apply to existing volumes.

**Comment by presztak** [comment]
@stgraber I'd happy to work on this!

**Comment by tomponline** [comment]
thanks!

**Comment by presztak** [comment]
@tomponline 
Is there any specific reason why for ceph driver pool key `volume.block.filesystem` and `block.filesystem` for volume have different validators (`validate.IsOneOf(cephAllowedFilesystems...)` and `validate.IsAny` respectively)? Can we make this more consistent?

Here we have validator for pool:
https://github.com/lxc/lxd/blob/6d73e2a3d0c53adbfa1503d692f88e88a75ebfe0/lxd/storage/drivers/driver_ceph.go#L266

and here for volume:
https://github.com/lxc/lxd/blob/6d73e2a3d0c53adbfa1503d692f88e88a75ebfe0/lxd/storage/drivers/driver_ceph_volumes.go#L773

**Comment by tomponline** [comment]
I think they should both use `validate.Optional(validate.IsOneOf(cephAllowedFilesystems...))` like the LVM driver does. Good spot.
