### ISSUE TITLE
Support User Mode Linux (UML) virtualization

### ISSUE THREAD

**Issue by crass** [lxc/lxd#10564]
# Issue description

This is a feature request. It would be nice to support User Mode Linux (UML) as a backend. Its a nice compromise between the lightness of a container which must use the host kernel and the heaviness of a fullbown VM. I suspect this will play nicely with currently existing container images. I suggest that the `--vm` parameter take an option to support this, eg. `--vm uml`. Perhaps one wrinkle is that this would not be able to be supported on non-Linux hosts and currently only x86 and ppc (with maybe arm in the works). Also, Ubuntu repos do not have a user-mode-linux package (they used to, but it got dropped), though Debian does. There would probably need to be some way to tell lxd where an alternative location is for the uml kernel and modules.

**Comment by stgraber** [comment]
Thanks for the request, this made me look into UML again which I haven't done in quite a few years.

Unfortunately, I don't think it's something we're very likely to ever want to support.
The main reason for this is that adding a new instance driver in LXD takes a fair amount of time and significantly increases our testing and maintenance effort, so for us to do this, we'd need a very very good reason. We did it for virtual machines as containers alone couldn't do everything we wanted, but I don't see that strong a case for UML.

Looking at the current UML documentation, it shows UML as being a great way to experiment with the Linux kernel, debug it and try new kernel features. It is however not a good solution for general purpose workloads as all user space calls must be intercepted by UML, very severely affecting the performance of the workload that's being run. And maybe even worse given today's software landscape, UML is single processor. With most systems today having access to at least 4 CPU threads, software is less and less designed to work in such pure single-processor environments.

That said, I still find UML to be a very neat concept and should consider using it again next time I'm doing kernel development, it sure looks more enjoyable to use for debugging than a full fledged VM or physical system.
