### ISSUE TITLE
Go: Can you make some api constants available?

### ISSUE THREAD

**Issue by dionysius** [lxc/lxd#10561]
Hi, I'd like to refer to those constants in my code

This won't be a exhaustive list, right now I see a need in the `Event` API:
- `api.Event.Type` can be `logging`, `lifecycle`, `operation`, [etc. (full list)](https://github.com/lxc/lxd/blob/master/doc/events.md#event-types)
  - https://github.com/lxc/lxd/blob/master/shared/api/event.go#L40
  - https://github.com/lxc/lxd/blob/master/shared/api/event.go#L60
  - https://github.com/lxc/lxd/blob/master/shared/api/event.go#L87
- `api.EventLifecycle.Action` can be `instance-started`, `instance-stopped`, [etc. (full list)](https://github.com/lxc/lxd/blob/master/doc/events.md#supported-lifecycle-events)
  - https://github.com/lxc/lxd/blob/master/shared/api/event.go#L22

**Comment by tomponline** [comment]
Reopening so we remember to use (and maintain) these likecycle constants in lxd.
