### ISSUE TITLE
 bug??? lxc config device add cuda gpu gpu id=0 or 1

### ISSUE THREAD

**Issue by jieguolove** [lxc/lxd#10566]
omnisky@omnisky-Super-Server:~$ lxd --version
5.2
omnisky@omnisky-Super-Server:~$ lxc --version
5.2
omnisky@omnisky-Super-Server:~$ cat /etc/issue
Ubuntu 18.04.6 LTS \n \l

according to url:
[https://ubuntu.com/blog/nvidia-cuda-inside-a-lxd-container](url)
![image](https://user-images.githubusercontent.com/96612712/174206637-bd2907aa-0cff-4da9-8d1b-7b86ff66a5be.png)
![image](https://user-images.githubusercontent.com/96612712/174206719-6a6229e6-7663-4c96-8cf5-b365a59b25d4.png)
I use the command:sudo lxc config device add test02 gpu gpu id=0
or sudo lxc config device add test02 gpu gpu id=1
**but see 2 gpus，i think it's bug???**
![image](https://user-images.githubusercontent.com/96612712/174206799-d8cfc928-fe2e-4a21-8c6c-52fdcf51111e.png)

then i use sudo lxc config device add test01 gpu1 gpu vendorid=10de productid=1b06 is ok
![image](https://user-images.githubusercontent.com/96612712/174209441-298f8952-ddf9-4ae8-b9ad-4df6a1e4a76f.png)

omnisky@omnisky-Super-Server:~$ sudo lxc config device remove test01 gpu1
Device gpu1 removed from test01
omnisky@omnisky-Super-Server:~$ sudo lxc exec test01 -- nvidia-smi
Failed to initialize NVML: Unknown Error
omnisky@omnisky-Super-Server:~$ sudo lxc config device add test01 gpu0 gpu pci=00000000:03:00.0
Error: Invalid devices: Device validation failed for "gpu0": Invalid value for device option "pci": Invalid PCI address

omnisky@omnisky-Super-Server:~$ sudo lxc config device add test01 gpu0 gpu pci=0000:03:00.0
Device gpu0 added to test01

**and i use pic is part ok，we can see 
PCI has 8 zeros，but we must use 4 zeros.**

omnisky@omnisky-Super-Server:~$ sudo lxc exec test01 -- nvidia-smi
Fri Jun 17 02:12:33 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:03:00.0 Off |                  N/A |
| 27%   33C    P8    20W / 250W |     35MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1672      G                                      33MiB |
+-----------------------------------------------------------------------------+
omnisky@omnisky-Super-Server:~$

**Comment by stgraber** [comment]
The `id` refers to the DRM card ID, not NVIDIA's own ID.

Can you show `lxc info --resources`?

**Comment by jieguolove** [comment]
> The `id` refers to the DRM card ID, not NVIDIA's own ID.
> 
> Can you show `lxc info --resources`?

omnisky@omnisky-Super-Server:~$ sudo lxc list
+--------+---------+----------------------+-----------------------------------------------+-----------+-----------+
|  NAME  |  STATE  |         IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS |
+--------+---------+----------------------+-----------------------------------------------+-----------+-----------+
| test01 | RUNNING | 10.246.171.8 (eth0)  | fd42:496f:8749:2ad5:216:3eff:fe89:96fc (eth0) | CONTAINER | 0         |
+--------+---------+----------------------+-----------------------------------------------+-----------+-----------+
| test02 | RUNNING | 10.246.171.58 (eth0) | fd42:496f:8749:2ad5:216:3eff:fed7:fce6 (eth0) | CONTAINER | 0         |
+--------+---------+----------------------+-----------------------------------------------+-----------+-----------+
omnisky@omnisky-Super-Server:~$ sudo lxc info --resources
CPUs (x86_64):
  Socket 0:
    Vendor: GenuineIntel
    Name: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
    Caches:
      - Level 1 (type: Data): 32KiB
      - Level 1 (type: Instruction): 32KiB
      - Level 2 (type: Unified): 256KiB
      - Level 3 (type: Unified): 20MiB
    Cores:
      - Core 0
        Frequency: 1201Mhz
        Threads:
          - 0 (id: 0, online: true, NUMA node: 0)
          - 1 (id: 16, online: true, NUMA node: 0)
      - Core 1
        Frequency: 1200Mhz
        Threads:
          - 0 (id: 1, online: true, NUMA node: 0)
          - 1 (id: 17, online: true, NUMA node: 0)
      - Core 2
        Frequency: 1200Mhz
        Threads:
          - 0 (id: 18, online: true, NUMA node: 0)
          - 1 (id: 2, online: true, NUMA node: 0)
      - Core 3
        Frequency: 1201Mhz
        Threads:
          - 0 (id: 19, online: true, NUMA node: 0)
          - 1 (id: 3, online: true, NUMA node: 0)
      - Core 4
        Frequency: 1200Mhz
        Threads:
          - 0 (id: 20, online: true, NUMA node: 0)
          - 1 (id: 4, online: true, NUMA node: 0)
      - Core 5
        Frequency: 1199Mhz
        Threads:
          - 0 (id: 21, online: true, NUMA node: 0)
          - 1 (id: 5, online: true, NUMA node: 0)
      - Core 6
        Frequency: 1201Mhz
        Threads:
          - 0 (id: 22, online: true, NUMA node: 0)
          - 1 (id: 6, online: true, NUMA node: 0)
      - Core 7
        Frequency: 1200Mhz
        Threads:
          - 0 (id: 23, online: true, NUMA node: 0)
          - 1 (id: 7, online: true, NUMA node: 0)
    Frequency: 1200Mhz (min: 1200Mhz, max: 3000Mhz)
  Socket 1:
    Vendor: GenuineIntel
    Name: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
    Caches:
      - Level 1 (type: Data): 32KiB
      - Level 1 (type: Instruction): 32KiB
      - Level 2 (type: Unified): 256KiB
      - Level 3 (type: Unified): 20MiB
    Cores:
      - Core 0
        Frequency: 1317Mhz
        Threads:
          - 0 (id: 24, online: true, NUMA node: 1)
          - 1 (id: 8, online: true, NUMA node: 1)
      - Core 1
        Frequency: 1200Mhz
        Threads:
          - 0 (id: 25, online: true, NUMA node: 1)
          - 1 (id: 9, online: true, NUMA node: 1)
      - Core 2
        Frequency: 1275Mhz
        Threads:
          - 0 (id: 10, online: true, NUMA node: 1)
          - 1 (id: 26, online: true, NUMA node: 1)
      - Core 3
        Frequency: 1200Mhz
        Threads:
          - 0 (id: 11, online: true, NUMA node: 1)
          - 1 (id: 27, online: true, NUMA node: 1)
      - Core 4
        Frequency: 1200Mhz
        Threads:
          - 0 (id: 12, online: true, NUMA node: 1)
          - 1 (id: 28, online: true, NUMA node: 1)
      - Core 5
        Frequency: 1205Mhz
        Threads:
          - 0 (id: 13, online: true, NUMA node: 1)
          - 1 (id: 29, online: true, NUMA node: 1)
      - Core 6
        Frequency: 1201Mhz
        Threads:
          - 0 (id: 14, online: true, NUMA node: 1)
          - 1 (id: 30, online: true, NUMA node: 1)
      - Core 7
        Frequency: 1207Mhz
        Threads:
          - 0 (id: 15, online: true, NUMA node: 1)
          - 1 (id: 31, online: true, NUMA node: 1)
    Frequency: 1225Mhz (min: 1200Mhz, max: 3000Mhz)

Memory:
  NUMA nodes:
    Node 0:
      Free: 188.60GiB
      Used: 3.40GiB
      Total: 192.00GiB
    Node 1:
      Free: 60.47GiB
      Used: 3.53GiB
      Total: 64.00GiB
  Free: 249.01GiB
  Used: 6.99GiB
  Total: 256.00GiB

GPUs:
  Card 0:
    NUMA node: 0
    Vendor: ASPEED Technology, Inc. (1a03)
    Product: ASPEED Graphics Family (2000)
    PCI address: 0000:06:00.0
    Driver: ast (5.4.0-117-generic)
    DRM:
      ID: 0
      Card: card0 (226:0)
      Control: controlD64 (226:0)
  Card 1:
    NUMA node: 0
    Vendor: NVIDIA Corporation (10de)
    Product: TU102 [GeForce RTX 2080 Ti] (1e04)
    PCI address: 0000:03:00.0
    Driver: nvidia (510.60.02)
    DRM:
      ID: 1
      Card: card1 (226:1)
      Render: renderD128 (226:128)
    NVIDIA information:
      Architecture: 7.5
      Brand: GeForce
      Model: NVIDIA GeForce RTX 2080 Ti
      CUDA Version: 11.6
      NVRM Version: 510.60.02
      UUID: GPU-ba320978-affc-8e3e-1c78-adab016a3a2b
  Card 2:
    NUMA node: 1
    Vendor: NVIDIA Corporation (10de)
    Product: GP102 [GeForce GTX 1080 Ti] (1b06)
    PCI address: 0000:82:00.0
    Driver: nvidia (510.60.02)
    DRM:
      ID: 2
      Card: card2 (226:2)
      Render: renderD129 (226:129)
    NVIDIA information:
      Architecture: 6.1
      Brand: GeForce
      Model: NVIDIA GeForce GTX 1080 Ti
      CUDA Version: 11.6
      NVRM Version: 510.60.02
      UUID: GPU-0d5164be-8a15-98be-72f2-07f11106e43e

NICs:
  Card 0:
    NUMA node: 1
    Vendor: Intel Corporation (8086)
    Product: I350 Gigabit Network Connection (1521)
    PCI address: 0000:81:00.0
    Driver: igb (5.6.0-k)
    Ports:
      - Port 0 (ethernet)
        ID: eno1
        Address: ac:1f:6b:96:e2:80
        Supported modes: 10baseT/Half, 10baseT/Full, 100baseT/Half, 100baseT/Full, 1000baseT/Full
        Supported ports: twisted pair
        Port type: twisted pair
        Transceiver type: internal
        Auto negotiation: true
        Link detected: true
        Link speed: 1000Mbit/s (full duplex)
    SR-IOV information:
      Current number of VFs: 0
      Maximum number of VFs: 7
  Card 1:
    NUMA node: 1
    Vendor: Intel Corporation (8086)
    Product: I350 Gigabit Network Connection (1521)
    PCI address: 0000:81:00.1
    Driver: igb (5.6.0-k)
    Ports:
      - Port 0 (ethernet)
        ID: eno2
        Address: ac:1f:6b:96:e2:81
        Supported modes: 10baseT/Half, 10baseT/Full, 100baseT/Half, 100baseT/Full, 1000baseT/Full
        Supported ports: twisted pair
        Port type: twisted pair
        Transceiver type: internal
        Auto negotiation: true
        Link detected: false
    SR-IOV information:
      Current number of VFs: 0
      Maximum number of VFs: 7
  Card 2:
    NUMA node: 0
    Vendor: Mellanox Technologies (15b3)
    Product: MT27700 Family [ConnectX-4] (1013)
    PCI address: 0000:02:00.0
    Driver: mlx5_core (5.0-0)

Disk:
  NUMA node: 0
  ID: sda
  Device: 8:0
  Model: SDLF1DAR-960G-1HA1
  Type: sata
  Size: 894.25GiB
  Read-Only: false
  Removable: false
  Partitions:
    - Partition 1
      ID: sda1
      Device: 8:1
      Read-Only: false
      Size: 894.25GiB

**Comment by stgraber** [comment]
```
GPUs:
Card 0:
NUMA node: 0
Vendor: ASPEED Technology, Inc. (1a03)
Product: ASPEED Graphics Family (2000)
PCI address: 0000:06:00.0
Driver: ast (5.4.0-117-generic)
DRM:
ID: 0
Card: card0 (226:0)
Control: controlD64 (226:0)
Card 1:
NUMA node: 0
Vendor: NVIDIA Corporation (10de)
Product: TU102 [GeForce RTX 2080 Ti] (1e04)
PCI address: 0000:03:00.0
Driver: nvidia (510.60.02)
DRM:
ID: 1
Card: card1 (226:1)
Render: renderD128 (226:128)
NVIDIA information:
Architecture: 7.5
Brand: GeForce
Model: NVIDIA GeForce RTX 2080 Ti
CUDA Version: 11.6
NVRM Version: 510.60.02
UUID: GPU-ba320978-affc-8e3e-1c78-adab016a3a2b
Card 2:
NUMA node: 1
Vendor: NVIDIA Corporation (10de)
Product: GP102 [GeForce GTX 1080 Ti] (1b06)
PCI address: 0000:82:00.0
Driver: nvidia (510.60.02)
DRM:
ID: 2
Card: card2 (226:2)
Render: renderD129 (226:129)
NVIDIA information:
Architecture: 6.1
Brand: GeForce
Model: NVIDIA GeForce GTX 1080 Ti
CUDA Version: 11.6
NVRM Version: 510.60.02
UUID: GPU-0d5164be-8a15-98be-72f2-07f11106e43e
```

So this shows that ID 0 is an aspeed BMC GPU, so it's normal that id=0 didn't result in an NVIDIA GPU being passed through.

**Comment by jieguolove** [comment]
> ```
> GPUs:
> Card 0:
> NUMA node: 0
> Vendor: ASPEED Technology, Inc. (1a03)
> Product: ASPEED Graphics Family (2000)
> PCI address: 0000:06:00.0
> Driver: ast (5.4.0-117-generic)
> DRM:
> ID: 0
> Card: card0 (226:0)
> Control: controlD64 (226:0)
> Card 1:
> NUMA node: 0
> Vendor: NVIDIA Corporation (10de)
> Product: TU102 [GeForce RTX 2080 Ti] (1e04)
> PCI address: 0000:03:00.0
> Driver: nvidia (510.60.02)
> DRM:
> ID: 1
> Card: card1 (226:1)
> Render: renderD128 (226:128)
> NVIDIA information:
> Architecture: 7.5
> Brand: GeForce
> Model: NVIDIA GeForce RTX 2080 Ti
> CUDA Version: 11.6
> NVRM Version: 510.60.02
> UUID: GPU-ba320978-affc-8e3e-1c78-adab016a3a2b
> Card 2:
> NUMA node: 1
> Vendor: NVIDIA Corporation (10de)
> Product: GP102 [GeForce GTX 1080 Ti] (1b06)
> PCI address: 0000:82:00.0
> Driver: nvidia (510.60.02)
> DRM:
> ID: 2
> Card: card2 (226:2)
> Render: renderD129 (226:129)
> NVIDIA information:
> Architecture: 6.1
> Brand: GeForce
> Model: NVIDIA GeForce GTX 1080 Ti
> CUDA Version: 11.6
> NVRM Version: 510.60.02
> UUID: GPU-0d5164be-8a15-98be-72f2-07f11106e43e
> ```
> 
> So this shows that ID 0 is an aspeed BMC GPU, so it's normal that id=0 didn't result in an NVIDIA GPU being passed through.

So what's the gpu id? we should use which id? thanks!

**Comment by stgraber** [comment]
The LXD GPU id is the same id that's shown in `lxc info --resources` and corresponds to the Linux DRM id.
NVIDIA has its own ID which is separate and that we have no control over.

**Comment by jieguolove** [comment]
> https://ubuntu.com/blog/nvidia-cuda-inside-a-lxd-container

but you can see the url , it set gpu id=0 test ok,how explained?
[https://ubuntu.com/blog/nvidia-cuda-inside-a-lxd-container](url)
![image](https://user-images.githubusercontent.com/96612712/174234271-a241463b-f3bc-47b0-b41c-139d420a94b0.png)

**Comment by stgraber** [comment]
The system used in that blog post didn't have non-NVIDIA GPUs.
