### ISSUE TITLE
Can't understand how to use known remote as source server when creating instance with API

### ISSUE THREAD

**Issue by jadjay** [lxc/lxd#10573]
Hello all,

In the API documentation : https://linuxcontainers.org/lxd/api/master/#/instances/instances_post

It is said that : 
> this can create an instance from an existing local image, remote image, existing local instance or snapshot

But in the example there's only server as a "simplestream" https URL : ```"server": "https://images.linuxcontainers.org",```

So is it possible to set the source to a image in an already set remote ?
e.g. : myremote:myimage

And how can we set this in the API ?

Thanks for your attention,

Regards,

**Comment by stgraber** [comment]
The concept of a remote like `myremote` is a purely client side concept of the `lxc` tool.

What the CLI tool sends LXD is a request to fetch an image from a given server (URL to other LXD), with a specific certificate and image alias.

You can always run the matching `lxc` command with `--debug` to see exactly what's sent to LXD over the REST API.
