### ISSUE TITLE
LVM-backed devices misreporting disk space

### ISSUE THREAD

**Issue by oddomatik** [lxc/lxd#10589]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04.4 LTS
 * The output of "lxc info":
[lxcinfo.txt](https://github.com/lxc/lxd/files/8952928/lxcinfo.txt)

# Issue description

On lxc 4.19 (and probably others), We consistently have containers that are alerting on a lack of free space (as reported by df -h /). This does not match the output of du, or as far as we can tell, the "actual" container usage.

```
root@<redacted_containername>:~# df -h /
Filesystem                                                                                   Size  Used Avail Use% Mounted on
/var/snap/lxd/common/lxd/storage-pools/lvm-pool/containers/<redacted_containername>/rootfs   20G   19G  1.6G  93% /
root@<redacted_containername>:~# du -xh --max-depth=0 /
6.2G	/
```

lsof shows many references for "No such file or directory", that are all referencing the mmap'd file (the path outside the container) Example:

```
lsof      2083010            root  mem    REG 253,230            38020 /var/snap/lxd/common/lxd/storage-pools/lvm-pool/containers/<redacted_containername>/rootfs/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache (stat: No such file or directory)
sshd      2083007            sshd  mem    REG 253,230            12612 /var/snap/lxd/common/lxd/storage-pools/lvm-pool/containers/<redacted_containername>/rootfs/usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1 (stat: No such file or directory)
pickup    2081909         postfix  mem    REG 253,230            10012 /var/snap/lxd/common/lxd/storage-pools/lvm-pool/containers/<redacted_containername>/rootfs/usr/lib/x86_64-linux-gnu/libnss_files-2.31.so (stat: No such file or directory)
```
lsof also shows a few references to (deleted) files with the "proper" path (as inside container).

On this particular container we have a discrepancy of abut 12.8G, but when I add up all the files with what we would traditionally consider open handles, they only add up to around 1G (even when considering most files are duplicated several times in the lsof output).

Rebooting the container seems to be the only way to free up this mystery space. Restarting processes mentioned in lsof has no effect in freeing the references or space.

# Steps to reproduce

We have so far found this issue very hard to reproduce in testing.

 1. Provision thin-provisioned, lvm-backed container with an apache instance and website running on ext4 / device
 2. Wait?

# Information to attach
We almost always have a few identifiable containers in this state that I can provide information from as desired. 

 - [ ] Container log (`lxc info NAME --show-log`) [info.txt](https://github.com/lxc/lxd/files/8953044/info.txt)
 - [ ] Container configuration (`lxc config show NAME --expanded`) [cont_config.txt](https://github.com/lxc/lxd/files/8953052/cont_config.txt)
 - [ ] lxc storage list  `lvm-pool,lvm,lvm-pool,,393`
 - [ ] dumpe2fs [dumpe2fs.txt](https://github.com/lxc/lxd/files/8953073/dumpe2fs.txt)
 - [ ] mount as reported in container: `/var/snap/lxd/common/lxd/storage-pools/lvm-pool/containers/<redacted_containername>/rootfs on / type shiftfs (rw,relatime,passthrough=3)`

**Comment by stgraber** [comment]
Closing this in general as there's nothing LXD can do about this. This is all in kernel.

Now, this is indeed something I've seen before and can be one of two things:
 - Files that are open by running software but deleted from disk
 - A similar inode tracking bug in shiftfs

The former is purely a userspace error. You can totally create a 10GB file, have something hold it open and then delete it.
`du` won't count it anymore but it can't go away from the filesystem until that software exits and the file isn't open anymore.

The latter is a bug but sadly not one we expect to see fixed as shiftfs was always kept experimental (requires manual enablement) and is being replaced with VFS idmap shifting which doesn't suffer from such issues.

**Comment by stgraber** [comment]
You mentioned LVM here, so that likely means ext4 is the actual filesystem. If you are indeed using that with shiftfs, I'd strongly recommend you upgrade to the HWE kernel. This will get you VFS idmap shifting on your same setup and take care of this issue.

**Comment by stgraber** [comment]
linux-generic-hwe-20.04 gets you 5.13 which should be sufficient for ext4.
linux-generic-hwe-20.04-edge gets you the same 5.15 as Ubuntu 22.04 LTS.

I personally would go with the latter as that also makes you one step closer to an upgrade to 22.04 should that be on your roadmap.

**Comment by stgraber** [comment]
> Is there a minimum LXD version needed to take advantage?

It was introduced in LXD 4.16 and backported in LXD 4.0.7, so anything after that should be fine.

> If the kernel is upgraded on focal hosts, will our existing containers use the new feature or will the need to be recreated or reconfigured?

Any container that's on shiftfs will start using it automatically, so will all new containers.

> Are there _any_ configurations needed to select this feature over shiftfs?

No. LXD will automatically try to use it whenever possible.
If the filesystem you're using isn't supported, it will then fallback to shiftfs if enabled and to the slow shifting logic if not.

So in fact, for VFS idmap, there's less configuration needed as you will get it even if shiftfs isn't enabled.
