### ISSUE TITLE
lxd on a computer without wired network (eth0)

### ISSUE THREAD

**Issue by gunterkoenigsmann** [lxc/lxd#10585]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info": [lxcinfo.txt](https://github.com/lxc/lxd/files/8946021/lxcinfo.txt)

# Issue description

My computer has no wired ethernet (eth0). Instead it uses a wifi (wlp2s0). If I run `lxd init` I get:

````
Error: Failed to update profile "default": Device validation failed for "eth0": Cannot use "nictype" property in conjunction with "network" property
````

...and my comtainers have no network connection, which is why I cannot build any snaps.

# Steps to reproduce

 1. Take a laptop without wired ethernet interface
 2. lxd init

**Comment by stgraber** [comment]
Wifi or wired really doesn't matter, that eth0 in the default profile is the name of the network interface that goes inside of the containers.

What exactly did you pick during `lxd init` to get to that result?

**Comment by gunterkoenigsmann** [comment]
lxd init --auto

**Comment by stgraber** [comment]
Sounds like the system may already have been initialized prior to the `lxd init --auto`?

**Comment by stgraber** [comment]
The error is consistent with a pre-existing entry in `lxc profile show default`.
`lxd init --auto` went to create the network but when adding it, it conflicted with something in there.

**Comment by tomponline** [comment]
@gunterkoenigsmann if you're able to reproduce the issue with a fresh install we would be happy to reopen this (or if you have additional info).
