### ISSUE TITLE
Some LXD VM Agent commands don't work

### ISSUE THREAD

**Issue by masnax** [lxc/lxd#10596]
# Description
Currently on master, certain commands on a VM don't work. This seems to be happening since #10580. 

# Steps to reproduce
```bash
lxc launch images:ubuntu/22.04/cloud vm --vm
# Wait for lxd agent to start...

lxc exec vm -- bash
  Error: dial tcp: lookup custom.socket: no such host

lxc file push something vm/
  Error: Post "http://unix.socket/1.0/instances/foo/files?path=%2Fsomething": EOF
```

**Comment by tomponline** [comment]
Thanks, our daily tests would have detected this once the edge snap rebuilt but  you beat it to it.
