### ISSUE TITLE
`lxc list --fast -f csv` wrong formatted with multi profiles on containers.

### ISSUE THREAD

**Issue by carlzhc** [lxc/lxd#10601]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version: 5.0.0
   * Storage backend in use: 

# Issue description

If one container has multi profiles, when run `lxc list --fast -f csv`, it wraps the lines at profile names.
# Steps to reproduce
```
# lxc list --fast
+----------------+---------+--------------+----------------------+----------+-----------+
|      NAME      |  STATE  | ARCHITECTURE |      CREATED AT      | PROFILES |   TYPE    |
+----------------+---------+--------------+----------------------+----------+-----------+
| Centos8-Stream | RUNNING | x86_64       | 2022/06/23 03:53 UTC | default  | CONTAINER |
|                |         |              |                      | macvlan  |           |
+----------------+---------+--------------+----------------------+----------+-----------+

# lxc list --fast -f csv
Centos8-Stream,RUNNING,x86_64,2022/06/23 03:53 UTC,"default
macvlan",CONTAINER
```

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
CSV files can contain line breaks in values, it's still valid.
This indeed happens with LXD output for things like IPv4/IPv6 addresses and for profiles.

```
stgraber@castiana:~$ python3
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import csv
>>> with open("a.csv", "r") as fd:
...   reader = csv.reader(fd)
...   list(reader)
... 
[['Centos8-Stream', 'RUNNING', 'x86_64', '2022/06/23 03:53 UTC', 'default\nmacvlan', 'CONTAINER']]
>>> 
stgraber@castiana:~$ 
```

**Comment by carlzhc** [comment]
Checked the RFC4180, csv fields can contain line breaks indeed.
