### ISSUE TITLE
rest-api docu

### ISSUE THREAD

**Issue by jensg-st** [lxc/lxd#1060]
Hi,

just have been through the doco after a while and in the error section it says:

```
{
    'type': "error",
    'status': "Failure",
    'status_code': 400,
    'metadata': {}                      # More details about the error
}
```

Isn't it more like this:

```
{
    'type': "error",
    'error': "This is an error",
    'error_code': 400,
    'metadata': {}                      # More details about the error
}
```

**Comment by stgraber** [comment]
We had a plan to use a common terminology for all return values but that never quite happened. I'd be happy to merge a branch which makes the rest api doc reflect reality.
