### ISSUE TITLE
Not the able to see the vhost_net driver in lxc vm kernel in the path "/lib/modules/5.4.0-1070-kvm/kernel/drivers/vhost" to create the tap interfaces

### ISSUE THREAD

**Issue by dkadkadkal** [lxc/lxd#10615]
**LXC VM Ubuntu Version**
 **lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	**Ubuntu 20.04.4 LTS**
Release:	20.04
Codename:	focal

**Kernel Version**
**uname -a**
Linux Test-Setup-01-Dell-ens5f1 **5.4.0-1070-kvm** #75-Ubuntu SMP Fri Jun 10 19:57:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

I have tried many way for installing vhost_net driver. But It didn't got any idea because it is not part of kernel.
Here the **lsmod | grep vhost**  shows only the **vhost**, It doesn't shows the **vhost_net** driver.

Is there any solution to use the vhost_net or Is there any other way for installing vhost_net driver in kvm.

**Comment by stgraber** [comment]
Not a LXD issue but an issue with the Ubuntu kernel. I'd recommend you file a bug against the linux-kvm Ubuntu package.

You may also be able to install linux-virtual or linux-generic to get a kernel which may have that module built-in.

**Comment by simondeziel** [comment]
Indeed, `linux-image-kvm` doesn't have the module enabled while `linux-image-virtual` and `linux-image-generic` have it:

```
# grep CONFIG_VHOST_NET /boot/config-5.4.0-1*
/boot/config-5.4.0-1070-kvm:# CONFIG_VHOST_NET is not set
/boot/config-5.4.0-121-generic:CONFIG_VHOST_NET=m
```

**Comment by simondeziel** [comment]
> Is there any solution to enable the CONFIG_VHOST_NET in kvm

Yes, please make that request by filling a bug here: https://launchpad.net/ubuntu/+source/linux-meta-kvm/+filebug

**Comment by dkadkadkal** [comment]
Sure Simon

Thanks for Reply

**Comment by simondeziel** [comment]
Thanks for reporting it! https://bugs.launchpad.net/ubuntu/+source/linux-meta-kvm/+bug/1980122
