### ISSUE TITLE
Use edge packages for liblxc and dqlite in static-analysis workflow

### ISSUE THREAD

**Issue by markylaing** [lxc/lxd#10624]
The current static analysis workflow uses `make deps` to build dependencies from scratch which is unnecessary.

This PR should get the `latest/edge` versions of dqlite and liblxc from their respective ppa's and remove `make deps` from the static analysis github action.

**Comment by tomponline** [comment]
- https://launchpad.net/~dqlite/+archive/ubuntu/dev
- https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxc-git-master
