### ISSUE TITLE
Use specific version of shellcheck in static analysis

### ISSUE THREAD

**Issue by markylaing** [lxc/lxd#10623]
The current static-analysis github workflow is using a version of `shellcheck` that comes with the `ubuntu-latest` image. Additionally, when running locally `make static-analysis` may fail depending on shellcheck version.

This PR should:
- [ ] Install an up to date, stable shellcheck in github actions.
- [ ] Check the shellcheck version in `make static-analysis` and warn if it is not the same.

**Comment by tomponline** [comment]
Thanks for that. Yes I suppose we should, although first we should fix the shellcheck errors from `make static-analysis` first :)
