### ISSUE TITLE
Create instance from backup: Cannot restore volume

### ISSUE THREAD

**Issue by zjiel** [lxc/lxd#10639]
# Required information

 * Distribution: Gentoo
 * Distribution version: 5.18.2
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.18.2
   * LXC version: 5.0.0
   * LXD version: 5.0.0
   * Storage backend in use: dir

# Issue description
lxc export NCCM /root/NCCM.tar.xz --optimized-storage

lxc import /media/usb/lxd/NCCM.tar.xz -s pool
Error: Create instance from backup: Cannot restore volume, already exists on target

/var/lib/lxd/containers # ls -lart
NCCM -> /var/lib/lxd/storage-pools/pool/containers/NCCM

But I am not able to see thru cmd: lxc list

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 # lxc info --show-log NCCM
Error: Not Found
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
 
location: none
metadata:
  context: {}
  level: debug
  message: 'Failure for task operation: 35fd3773-3f46-42b1-b2b6-06f6ed277a97: Create
    instance from backup: Cannot restore volume, already exists on target'
timestamp: "2022-07-06T15:09:48.868251643+08:00"
type: logging

location: none
metadata:
  class: task
  created_at: "2022-07-06T15:09:48.574591138+08:00"
  description: Restoring backup
  err: 'Create instance from backup: Cannot restore volume, already exists on target'
  id: 35fd3773-3f46-42b1-b2b6-06f6ed277a97
  location: none
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/virl
    instances:
    - /1.0/instances/virl
  status: Failure
  status_code: 400
  updated_at: "2022-07-06T15:09:48.574591138+08:00"
project: default
timestamp: "2022-07-06T15:09:48.868511267+08:00"
type: operation

location: none
metadata:
  context:
    listener: 2f1135e0-c420-4afb-8875-11be8bddd69d
    local: /var/lib/lxd/unix.socket
    remote: '@'
  level: debug
  message: Event listener server handler stopped
timestamp: "2022-07-06T15:09:48.869689673+08:00"
type: logging

**Comment by tomponline** [comment]
Did you do a `lxc delete NCCM` before running `lxc import`?

**Comment by tomponline** [comment]
Removing `/var/lib/lxd/storage-pools/pool/containers/NCCM` (assuming there's nothing you want in it) should allow import.

**Comment by tomponline** [comment]
I'll close this for now, but will reopen if you are able to provide reproducer steps around how that directory gets left behind and/or still experience issues after removing it. Thanks
