### ISSUE TITLE
Ensure static analysis respects go mod

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10630]
Static analysis started failing on this upstream change. But should not have based on the go mod config.

```
Error: lxd/daemon.go:1814:17: cannot use idmClient (variable of type *candidclient.Client) as "gopkg.in/macaroon-bakery.v2/bakery/identchecker".IdentityClient value in struct literal: *candidclient.Client does not implement "gopkg.in/macaroon-bakery.v2/bakery/identchecker".IdentityClient (wrong type for method DeclaredIdentity)
		have DeclaredIdentity(ctx "context".Context, declared map[string]string) ("gopkg.in/macaroon-bakery.v3/bakery/identchecker".Identity, error)
		want DeclaredIdentity(ctx "context".Context, declared map[string]string) ("gopkg.in/macaroon-bakery.v2/bakery/identchecker".Identity, error) (typecheck)
		client:       idmClient,
		              ^
make: *** [Makefile:250: static-analysis] Error 1
```

**Comment by tomponline** [comment]
Need to switch to gopkg.in/macaroon-bakery.v3/bakery/identchecker

**Comment by stgraber** [comment]
How did that show up? gomod should have prevented this from being an issue until my next schedule refresh of our dependencies.

**Comment by tomponline** [comment]
It just started yesterday in the static analysis test.
I agree though go mod should have stopped that. Perhaps something in the static analysis tests arent using go mod.

Cc @markylaing

**Comment by stgraber** [comment]
Yeah, that'd be a bug in static analysis then. Our dependencies do occasionally break things but I usually handle all of those when I perform a gomod update. Until that point, nothing should be breaking.

**Comment by tomponline** [comment]
Ive clarified the issue subject
