### ISSUE TITLE
build github.com/lxc/lxd/lxd: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

### ISSUE THREAD

**Issue by benzmuircroft** [lxc/lxd#10652]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

build fails with `build github.com/lxc/lxd/lxd: cannot load io/fs: malformed module path "io/fs": missing dot in first path element`

# Steps to reproduce

wget https://github.com/lxc/lxd/releases/download/lxd-5.3/lxd-5.3.tar.gz
tar zxvf lxd-5.3.tar.gz 
cd lxd-5.3
apt install acl attr autoconf automake dnsmasq-base git golang libacl1-dev libcap-dev liblxc1 liblxc-dev libsqlite3-dev libtool libudev-dev liblz4-dev libuv1-dev make pkg-config rsync squashfs-tools tar tcl xz-utils ebtables
make deps
export CGO_CFLAGS="-I/home/ubuntu/lxd-5.3/vendor/raft/include/ -I/home/ubuntu/lxd-5.3/vendor/dqlite/include/"
export CGO_LDFLAGS="-L/home/ubuntu/lxd-5.3/vendor/raft/.libs -L/home/ubuntu/lxd-5.3/vendor/dqlite/.libs/"
export LD_LIBRARY_PATH="/home/ubuntu/lxd-5.3/vendor/raft/.libs/:/home/ubuntu/lxd-5.3/vendor/dqlite/.libs/"
export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"
make

**Comment by tomponline** [comment]
Are you using go 1.18 or above to build?

**Comment by benzmuircroft** [comment]
I now have reinstalled my entire ubuntu 20.04 and have `go version go1.18.3 linux/amd64` and I followed the above steps (lxd-5.3) but, `lxd version4.0.9` how can this be if I used https://github.com/lxc/lxd/releases/download/lxd-5.3/lxd-5.3.tar.gz to install?

**Comment by benzmuircroft** [comment]
@tomponline please reopen

**Comment by tomponline** [comment]
How did you install lxd 4.0.9?

**Comment by tomponline** [comment]
Can you confirm if you are still getting the originally reported build error?

**Comment by benzmuircroft** [comment]
no build error but i cant use updated commands and it built an old version

the goal right from the start of this issue is to install lxd-5.3

**Comment by benzmuircroft** [comment]
Ok so I reinstalled a fresh ubuntu 20.04 again again without installing anything whatsoever

```
lxc version
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:20.04
Or for a virtual machine: lxc launch ubuntu:20.04 --vm

Client version: 4.0.9
Server version: 4.0.9
```
and
```
lxd version
4.0.9

```

they are there already?

I'd need to remove them before I install the latest but:

```
apt-get remove lxc -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'lxc' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by benzmuircroft** [comment]
Lots of lxc stuff for it to not be installed ...
```
locate lxc
/snap/bin/lxc
/snap/bin/lxd.lxc
/snap/bin/lxd.lxc-to-lxd
/snap/lxd/22753/lxc
/snap/lxd/22753/lxcfs
/snap/lxd/22753/bin/lxc
/snap/lxd/22753/bin/lxc-checkconfig
/snap/lxd/22753/bin/lxc-to-lxd
/snap/lxd/22753/bin/lxcfs
/snap/lxd/22753/commands/lxc
/snap/lxd/22753/commands/lxc-to-lxd
/snap/lxd/22753/etc/bash_completion.d/snap.lxd.lxc
/snap/lxd/22753/lib/liblxc.so.1
/snap/lxd/22753/lib/liblxc.so.1.7.0
/snap/lxd/22753/lib/liblxcfs.so
/snap/lxd/22753/lxc/config
/snap/lxd/22753/lxc/hooks
/snap/lxd/22753/lxc/config/common.conf.d
/snap/lxd/22753/lxc/config/common.conf.d/00-lxcfs.conf
/snap/lxd/22753/lxc/config/common.conf.d/01-local.conf
/snap/lxd/22753/lxc/hooks/nvidia
/snap/lxd/22753/lxcfs/lxc.mount.hook
/snap/lxd/22753/lxcfs/lxc.reboot.hook
/usr/lib/modules/5.4.0-121-generic/kernel/drivers/i2c/busses/i2c-mlxcpld.ko
/usr/lib/modules/5.4.0-121-generic/kernel/drivers/i2c/muxes/i2c-mux-mlxcpld.ko
/usr/lib/modules/5.4.0-121-generic/kernel/drivers/leds/leds-mlxcpld.ko
/usr/share/bash-completion/completions/lxc
/usr/share/bash-completion/completions/lxd.lxc
/usr/src/linux-headers-5.4.0-121/include/linux/platform_data/x86/mlxcpld.h
/usr/src/linux-headers-5.4.0-121-generic/include/config/i2c/mlxcpld.h
/usr/src/linux-headers-5.4.0-121-generic/include/config/i2c/mux/mlxcpld.h
/usr/src/linux-headers-5.4.0-121-generic/include/config/leds/mlxcpld.h
/var/cache/apparmor/26b63962.0/snap.lxd.lxc
/var/cache/apparmor/26b63962.0/snap.lxd.lxc-to-lxd
/var/cache/apparmor/f711f548.0/snap.lxd.lxc
/var/cache/apparmor/f711f548.0/snap.lxd.lxc-to-lxd
/var/lib/snapd/apparmor/profiles/snap.lxd.lxc
/var/lib/snapd/apparmor/profiles/snap.lxd.lxc-to-lxd
/var/lib/snapd/seccomp/bpf/snap.lxd.lxc-to-lxd.bin
/var/lib/snapd/seccomp/bpf/snap.lxd.lxc-to-lxd.src
/var/lib/snapd/seccomp/bpf/snap.lxd.lxc.bin
/var/lib/snapd/seccomp/bpf/snap.lxd.lxc.src
/var/snap/lxd/common/lxc
/var/snap/lxd/common/lxcfs.pid
/var/snap/lxd/common/lxc/local.conf
/var/snap/lxd/common/var/lib/lxcfs
```

**Comment by benzmuircroft** [comment]
snap remove lxd

gets rid of most

**Comment by benzmuircroft** [comment]
> ok so after removing lxd I installed go1.18.3 then I followed the original instructions to install lxd-5.3
> 
> result:
> 
> ```
> lxc version
> 
> Command 'lxc' not found, but can be installed with:
> 
> apt install lxd-installer  # version 1, or
> apt install lxd            # version 1:0.10
> 
> root@ns516449:/home/ubuntu/lxd-5.3# lxd version
> 
> Command 'lxd' not found, but can be installed with:
> 
> apt install lxd-installer  # version 1, or
> apt install lxd            # version 1:0.10
> ```

If if follow this advice and do `apt install lxd` then it installs but, after `lxc version` just prints the same "Command 'lxd' not found" message (stuck in a loop)

**Comment by benzmuircroft** [comment]
Fixed!
```
snap install lxd --channel=5.3/stable
lxd (5.3/stable) 5.3-91e042b from Canonical✓ installed
lxd version
5.3
lxc version
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:22.04
Or for a virtual machine: lxc launch ubuntu:22.04 --vm

Client version: 5.3
Server version: 5.3
```
