### ISSUE TITLE
Error: unknown command "forward" for "lxc network"

### ISSUE THREAD

**Issue by benzmuircroft** [lxc/lxd#10651]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails: 
   * Kernel version:
   * LXC version: 4.0.9
   * LXD version: 4.0.9
   * Storage backend in use: zfs

# Issue description

Per the official tutorial video https://www.youtube.com/watch?v=B-Uzo9WldMs and webpage https://linuxcontainers.org/lxd/docs/master/howto/network_forwards/#create-a-network-forward `lxc network forward create <network_name> <listen_address> [configuration_options...]` create should work but, instead it throws `Error: unknown command "forward" for "lxc network"`

**Comment by tomponline** [comment]
You need to run Lxd 5.0 LTS or later.
