### ISSUE TITLE
lxd vm how to boot to resecure mode to repare rootfs

### ISSUE THREAD

**Issue by askgh** [lxc/lxd#10670]
the kernel is hang, need boot to resecure mode to repare rootfs

#lxc version
Client version: 5.3
Server version: 5.3

**Comment by stgraber** [comment]
Support questions are better handled at https://discuss.linuxcontainers.org

In general, you'll want to get the VGA console with `lxc console NAME --type vga`. If the disk is completely corrupted, then similar to how you'd recover a normal system, you may want to attach an install ISO or some recovery disk image to the instance and boot from that.
