### ISSUE TITLE
Return migration error to user

### ISSUE THREAD

**Issue by Ahmadamir06** [lxc/lxd#10672]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04.4 LTS (Focal Fossa)
 * The output of "lxc info" or if that fails: 
  [lxc_info.txt](https://github.com/lxc/lxd/files/9130744/lxc_info.txt)
   * Kernel version: 5.4.0-121-generic
   * LXC version: 5.3
   * LXD version: 5.3
   * Storage backend in use: ZFS

# Issue description

I am trying to migrate a live container from server A to server B . Both the servers are using same distribution version , same lxc,lxd verion and same criu version as well. After launching a container i am trying to migrate it but it is not successful. 

First of all the transferring speed is quite low (around 9-11 Mbps) although both the servers are on the same physical server. Secondly i am getting error **websocket: close 1000 (normal)** due to which migration channels get disconnected on source and migration fails.

# Steps to reproduce
Following are the steps which i used 

to create a container
lxc launch ubuntu:18.04 t

to migrate a container
lxc move t mec2:t -v # t is the name of container i created

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)

[lxc-info-container.txt](https://github.com/lxc/lxd/files/9130861/lxc-info-container.txt)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 [lxc-config-show.txt](https://github.com/lxc/lxd/files/9130860/lxc-config-show.txt)
 - [ ] Main daemon log (at /var/log/lxd/lxd

.log or /var/snap/lxd/common/lxd/logs/lxd.log)
[lxd-logs.txt](https://github.com/lxc/lxd/files/9130862/lxd-logs.txt)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
[lxc_monitor.txt](https://github.com/lxc/lxd/files/9130859/lxc_monitor.txt)

**Comment by tomponline** [comment]
@monstermunchkin are you able to take a look at this, sounds like a potential optimized refresh issue. Thanks

**Comment by monstermunchkin** [comment]
This issue doesn't seem to be related to optimized refresh as I get the same error when using the `dir` driver.

**Comment by tomponline** [comment]
What are your reproducer steps @monstermunchkin as I was doing a cross-host migration yesterday (between LVM in that case) and it worked. Is it just dir and ZFS affected?

**Comment by monstermunchkin** [comment]
@tomponline I tried it two different ways:

#### Way 1

- 2 VMs, both running ubuntu:18.04
- Storage: dir
- LXD version: 5.3 (snap)

```
ubuntu@v1:~$ lxc launch ubuntu:18.04 t
ubuntu@v1:~$ lxc move t v2:t -v
Error: Failed instance creation: Error transferring instance data: migration pre-dump failed
(00.172484) Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 8836 with interrupted system call
(00.176329) Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 8837 with interrupted system call
(00.186545) Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 8838 with interrupted system call
(00.196136) Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 8839 with interrupted system call
(00.204610) Warn  (compel/arch/x86/src/lib/infect.c:352): Will restore 8842 with interrupted system call
pie: 212: Error (criu/pie/parasite.c:92): Can't splice pages to pipe (-11/4/27)
(00.212641) Error (compel/src/lib/infect-rpc.c:68): Command 66 for daemon failed with -1
(00.212724) Error (criu/mem.c:625): Can't dump page with parasite
(00.221869) Error (criu/cr-dump.c:1853): Pre-dumping FAILED.
```

#### Way 2

- Single host (Ubuntu 22.10) running 2 separate LXD servers
- LXD version: master branch (not snap)
- Storage: dir

```
$ lxc launch ubuntu:18.04 t
$ lxc move t l2:t -v
Error: Failed instance creation: Error transferring instance data: Failed to run: /home/thomas/go/bin/lxd forkmigrate t /home/thomas/work/lxd/server/containers /home/thomas/work/lxd/server/logs/t/lxc.conf /tmp/lxd_restore_3240589852/final false:
```

**Comment by monstermunchkin** [comment]
> Does it work with criu unistalled/disabled in the snap?

No, because live migration doesn't work without criu.

> As neither of those errors look like the one the OP posted.

The logs on the source show
```
ERROR  [2022-07-20T10:49:36+02:00] Migration failed on source                    err="websocket: close 1000 (normal)" instance=t project=default
```

However, I just looked at the @Ahmadamir06's  `lxd-logs.txt` which reads `time="2022-07-18T08:06:26Z" level=error msg="Failed initialising instance" err="Invalid devices: Failed detecting root disk device: No root device could be found" instance=t project=default type=container`.

This means the root device is missing, and needs to be set in the default profile.

**Comment by tomponline** [comment]
Thanks, I've missed the "live" part of this issue somehow. CRIU live migration of containers basically doesn't work in the majority of normal situations. It only works to my knowledge in very limited scenarios. 

@Ahmadamir06 can you retry the migration with the instance stopped and report any error (if any) you get then please?

**Comment by tomponline** [comment]
What we could do with doing though @monstermunchkin is to find a way to better report the error to the user, as `websocket: close 1000 (normal)` is not useful but `Invalid devices: Failed detecting root disk device: No root device could be found` is.

**Comment by monstermunchkin** [comment]
> The output of **sudo lxc profile show default** shows the root device as well

@Ahmadamir06 Is this on the target?

**Comment by Zplusless** [comment]
Same problem when trying to live migrating container from one lxc node to another.

both on :
1) live migration between two  Ubunru18.04 server (5.4.0-124-generic,  lxd v5.4(install from snap), criu v3.6 )
1) live migration between two  Ubunru22.04 server (5.15.0-46-generic,  lxd v5.4(install from snap), criu v3.16.1 )


the container image is Ubuntu16.04, since container images using systemd (e.g. ubuntu18.04) cannot even `snapshot --stateful` because of a criu error: "Can't dump nested uts namespace"

**Comment by tomponline** [comment]
We're just keeping this case open until we fix the migration to better reveal the error. See https://github.com/lxc/lxd/issues/10672#issuecomment-1190032424

**Comment by Zplusless** [comment]
> Yeah CRIU isn't working with systemd containers AFAIK.

Thanks for your work!!!

It is frustrating since even busybox cannot be moved

**Comment by tomponline** [comment]
I believe you have to remove the NIC from an alpine container to live migrate it.

**Comment by tomponline** [comment]
@monstermunchkin happy for me to take this one to see if we can expose the migration error to the user?
