### ISSUE TITLE
Set container hostname based on container name

### ISSUE THREAD

**Issue by dpb1** [lxc/lxd#1069]
Would be great if when creating a container (when renaming as well, though I could understand that is harder), the name you select for the container would be reflected in the real hostname of the container created.  So, when I did:

    lxc launch images:ubuntu/trusty/amd64 my-new-container
    ping my-new-container.local

it **just worked**.

**Comment by stgraber** [comment]
This is already the case:

    stgraber@dakara:~$ lxc launch images:ubuntu/trusty/amd64 my-new-container
    Creating my-new-container done.
    Starting my-new-container done.
    stgraber@dakara:~$ lxc exec my-new-container hostname
    my-new-container
    stgraber@dakara:~$ lxc exec my-new-container cat /etc/hostname
    my-new-container
    stgraber@dakara:~$ lxc exec my-new-container cat /proc/sys/kernel/hostname
    my-new-container
    stgraber@dakara:~$ 

That fact that you can't ping it through .local is because the Ubuntu images don't come with a running mdns daemon (avahi). Installing avahi-daemon inside the container should fix that for you.

**Comment by tych0** [comment]
On Wed, Sep 02, 2015 at 09:36:26AM -0700, David Britton wrote:
> Would be great if when creating a container (when renaming as well, though I could understand that is harder), the name you select for the container would be reflected in the real hostname of the container created.  So, when I did:

The container should have this hostname once created, if it doesn't
that's a bug.

>     lxc launch images:ubuntu/trusty/amd64 my-new-container
>     ping my-new-container.local

Unfortunately, this requires the container to broadcast on mDNS, which
it may or may not do (e.g. if it doesn't have avahi or something
similar installed). I suppose we could have LXD do some mDNS stuff,
but that seems like a slight abuse. So the ping you have here won't
work by default (but it will if you install avahi-daemon via your
favorite method).

**Comment by dpb1** [comment]
Ah, maybe I'm running out of date code, as I'm just pulling from what is in ubuntu vivid.  I'll use the ppa and retry.

```
dpb@helo:release-17[0]$ lxc exec lds-proposed bash
root@lds-proposed:~#
root@lds-proposed:~#
root@lds-proposed:~# sudo su -
sudo: unable to resolve host lds-proposed
root@lds-proposed:~# cat /etc/hosts
127.0.0.1   localhost
127.0.1.1   LXC_NAME

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
root@lds-proposed:~# cat /etc/hostname
LXC_NAME
root@lds-proposed:~# cat /proc/sys/kernel/hostname
lds-proposed
root@lds-proposed:~#
```

And, me having to install avahi is fine, thanks for the tip.

**Comment by stgraber** [comment]
Oh yeah, looks like your LXD doesn't support templating, it must indeed be pretty old as we've had that feature for months now.
