### ISSUE TITLE
Test suite support for snap LXD

### ISSUE THREAD

**Issue by gustavosr98** [lxc/lxd#10718]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Focal fossa
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-41-generic
   * LXC version: 5.1
   * LXD version: snap 5.1
   * Storage backend in use: dir

# Issue description

We are installing LXD for a customer and I would like a way to validate the installation works properly as an artifact for support before handing the cloud over.

Kind of the tempest acceptance test we run on Openstack.

An option I have is to write some scripts executing basic operation on LXD but I understand that is what the test suite does so I wanted to reuse that extensive testing.

I am trying to run the tests but hit different error since it seems test suite can only be executed from lxd source build.

**Comment by stgraber** [comment]
Yeah, you're not going to be able to use the snap to run through the normal testsuite as it heavily relies on being able to run up to 8 concurrent LXD daemons, needs direct access to the storage paths and a lot of behind the scenes access.

What we use to validate the snap automatically on our side is: https://github.com/lxc/lxc-ci/blob/master/bin/test-lxd-snapd

Closing as this isn't something that's going to be really possible for us to do.
