### ISSUE TITLE
TestGetAllXattr failing due to llistxattr() returning different lengths

### ISSUE THREAD

**Issue by gibmat** [lxc/lxd#10731]
* Distribution: Debian
 * Distribution version: sid
 * LXD version: 5.0.0 LTS
 * Go version: 1.18.4

This issue was discovered by another individual while reviewing the Debian LXD packaging and is reproducible in Debian's CI pipeline, but I have not been able to reproduce it myself locally.

When the tests are run, `TestGetAllXattr` fails:

```
=== RUN   TestGetAllXattr
    util_linux_test.go:79: numerical result out of range
--- FAIL: TestGetAllXattr (0.00s)
```

Adding some additional debugging output, I can see that for whatever reason the initial reported length of the extended attributes for the directory created (but not the file) is unexpectedly 23 bytes longer than it really is which causes the buffer to be padded with NULLs at the end:

```
=== RUN   TestGetAllXattr
I got pre=37 and post=37
00000000  75 73 65 72 2e 63 68 65  63 6b 73 75 6d 00 75 73  |user.checksum.us|
00000010  65 72 2e 72 61 6e 64 6f  6d 00 75 73 65 72 2e 65  |er.random.user.e|
00000020  6d 70 74 79 00                                    |mpty.|
I split into 3 strings
xattr -> user.checksum
xattr -> user.random
xattr -> user.empty
I got pre=60 and post=37
00000000  75 73 65 72 2e 63 68 65  63 6b 73 75 6d 00 75 73  |user.checksum.us|
00000010  65 72 2e 65 6d 70 74 79  00 75 73 65 72 2e 72 61  |er.empty.user.ra|
00000020  6e 64 6f 6d 00 00 00 00  00 00 00 00 00 00 00 00  |ndom............|
00000030  00 00 00 00 00 00 00 00  00 00 00 00              |............|
I split into 26 strings
xattr -> user.checksum
xattr -> user.empty
xattr -> user.random
xattr -> 
    util_linux_test.go:79: numerical result out of range
--- FAIL: TestGetAllXattr (0.00s)
```

If I make a slice of the buffer to truncate the excess NULLs with the following one line change, then the test passes:

```
diff --git a/shared/util_linux.go b/shared/util_linux.go
index 24cbed542..cbdfd3384 100644
--- a/shared/util_linux.go
+++ b/shared/util_linux.go
@@ -115,7 +115,7 @@ func GetAllXattr(path string) (xattrs map[string]string, err error) {
                return nil, fmt.Errorf("Extended attribute list size increased from %d to %d during retrieval", pre, post)
        }
 
-       split := strings.Split(string(dest), "\x00")
+       split := strings.Split(string(dest[:post]), "\x00")
        if split == nil {
                return nil, fmt.Errorf("No valid extended attribute key found")
        }
```

```
=== RUN   TestGetAllXattr
I got pre=37 and post=37
00000000  75 73 65 72 2e 65 6d 70  74 79 00 75 73 65 72 2e  |user.empty.user.|
00000010  63 68 65 63 6b 73 75 6d  00 75 73 65 72 2e 72 61  |checksum.user.ra|
00000020  6e 64 6f 6d 00                                    |ndom.|
00000000  75 73 65 72 2e 65 6d 70  74 79 00 75 73 65 72 2e  |user.empty.user.|
00000010  63 68 65 63 6b 73 75 6d  00 75 73 65 72 2e 72 61  |checksum.user.ra|
00000020  6e 64 6f 6d 00                                    |ndom.|
I split into 3 strings
xattr -> user.empty
xattr -> user.checksum
xattr -> user.random
I got pre=60 and post=37
00000000  75 73 65 72 2e 65 6d 70  74 79 00 75 73 65 72 2e  |user.empty.user.|
00000010  72 61 6e 64 6f 6d 00 75  73 65 72 2e 63 68 65 63  |random.user.chec|
00000020  6b 73 75 6d 00 00 00 00  00 00 00 00 00 00 00 00  |ksum............|
00000030  00 00 00 00 00 00 00 00  00 00 00 00              |............|
00000000  75 73 65 72 2e 65 6d 70  74 79 00 75 73 65 72 2e  |user.empty.user.|
00000010  72 61 6e 64 6f 6d 00 75  73 65 72 2e 63 68 65 63  |random.user.chec|
00000020  6b 73 75 6d 00                                    |ksum.|
I split into 3 strings
xattr -> user.empty
xattr -> user.random
xattr -> user.checksum
--- PASS: TestGetAllXattr (0.00s)
```

However, I don't know if that's a safe thing to do because I don't understand what's causing the initial call to `llistxattr()` to return a longer length than the actual data.

I've tried to reproduce this locally, but haven't been able to do so. I have tried running the test directly on a physical machine, within a LXD container, and within a docker container. I have tried with `/tmp/` mounted on ext4, zfs, and overlay filesystems. When `/tmp/` is mounted with `noxattr` or as tmpfs, the test correctly short-circuits out and passes.

This is being seen in LXD 5.0.0 LTS; I've looked at the git history for `shared/util_linux.go` since that release and don't see anything that I think would affect this behavior. Since I can't reproduce this locally I haven't been able to try building the master branch of LXD to confirm that. If anyone is able to share steps to reproduce or give suggestions on what I could try, I'd appreciate it!

**Comment by tomponline** [comment]
There's a package for handling extended attribute listing:

https://github.com/pkg/xattr

It only depends on `golang.org/x/sys` which we already use, and we already use other packages from `https://github.com/pkg/`
