### ISSUE TITLE
Unable to live migrate Windows VM between 2 remote hosts

### ISSUE THREAD

**Issue by jeff-hillman** [lxc/lxd#10730]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: Jammy 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-43-generic
   * LXC version: 5.0.0-b0287c1
   * LXD version: 5.0.0-b0287c1
   * Storage backend in use: ZFS on dedicated block device

# Issue description

Live migrate a Windows VM between 2 remote hosts.  They are not in a cluster, just independent remote host.  Local client is also Jammy and the same 5.0/stable snap of lxd.  Command fails with

Error: Failed instance creation: Error transferring instance data: Failed decoding migration header: invalid character '\x00' looking for beginning of value.  This also causes VM to stop.

# Steps to reproduce

 1. configure jammy and snap 5.0/stable on both remote machines
 2. sudo snap set lxd criu.enable=true
 3. sudo snap restart
 4. Add remote hosts to local client
 5. Build a windows VM

- a. lxc init win2k19 --vm --empty
- b. lxc config device override win2k19 root size=50GiB
- c. lxc config set win2k19 limits.cpu=4 limits.memory=4GiB
- d. lxc config device add win2k19 install disk source=/home/ubuntu/windows-2019-lxd.iso boot.priority=10
- e. lxc config set win2k19 migration.stateful=true
- f. lxc config device set win2k19 root size.state=50GiB

 6. After install completes detach ISO file
 a. lxc config device remove win2k19 install
 8. Attempt to move the VM 

-  a. lxc move 172.27.45.24:win2k19 172.27.45.25:win2k19 --verbose

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
$ lxc info win2k19 --show-log
Name: win2k19
Status: STOPPED
Type: virtual-machine
Architecture: x86_64
Created: 2022/08/02 19:31 CDT
Last Used: 2022/08/02 20:28 CDT

Log:

 - [ ] Container configuration (`lxc config show NAME --expanded`)
 $ lxc config show win2k19 --expanded
architecture: x86_64
config:
  limits.cpu: "4"
  limits.memory: 4GiB
  migration.stateful: "true"
  volatile.cloud-init.instance-id: e517de31-2059-4a01-8d2b-6a5d12be6916
  volatile.eth0.hwaddr: 00:16:3e:e9:a3:5b
  volatile.last_state.power: STOPPED
  volatile.uuid: 0905070b-98a6-4eb2-a866-a5a914f360bd
  volatile.vsock_id: "6"
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: local
    size: 50GiB
    size.state: 50GiB
    type: disk
ephemeral: false
profiles:
- default
stateful: true
description: ""

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
time="2022-08-03T01:16:39Z" level=warning msg=" - Couldn't find the CGroup network priority controller, network priority will be ignored"
time="2022-08-03T01:16:40Z" level=warning msg="Unable to use virtio-fs for config drive, using 9p as a fallback" err="Stateful migration unsupported" instance=win2k19 instanceType=virtual-machine project=default
time="2022-08-03T01:16:43Z" level=warning msg="Failed to update instance types: Get \"https://images.linuxcontainers.org/meta/instance-types/.yaml\": Unable to connect to: images.linuxcontainers.org:443 ([dial tcp 45.45.148.8:443: connect: no route to host dial tcp [2602:fc62:a:1::8]:443: connect: network is unreachable])"
time="2022-08-03T01:22:20Z" level=warning msg="Unable to use virtio-fs for config drive, using 9p as a fallback" err="Stateful migration unsupported" instance=win2k19 instanceType=virtual-machine project=default
time="2022-08-03T01:28:43Z" level=warning msg="Unable to use virtio-fs for config drive, using 9p as a fallback" err="Stateful migration unsupported" instance=win2k19 instanceType=virtual-machine project=default
time="2022-08-03T01:30:25Z" level=warning msg="Could not get VM state from agent" err="dial unix /var/snap/lxd/common/lxd/logs/win2k19/qemu.monitor: connect: no such file or directory" instance=win2k19 instanceType=virtual-machine project=default
time="2022-08-03T01:30:25Z" level=warning msg="Failed getting host interface state for MTU" device=eth0 driver=nic err="route ip+net: invalid network interface name" host_name= instance=win2k19 project=default

 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Are both source and destination servers running the same version of LXD?
And are they both using ZFS storage pools?

There's a very good chance that this is an issue we've already resolved in latter releases which will be fixed in 5.0.1 as we fixed a number of issues with storage migration since 5.0.0 first released.

**Comment by tomponline** [comment]
If its possible to try the same setup using snap channel `latest/snap` (which is currently LXD 5.4) it would be helpful to find out if the issue remains or is already fixed and will be in LXD 5.0.1.

Warning: Do not upgrade your current LXD installations to LXD 5.4 unless you are happy to remain on the feature branches and not on the LTS branch, as you won't be able to downgrade back to the LTS.

**Comment by jeff-hillman** [comment]
I can confirm that updated to latest/stable resolved the issue.  5.4-82d05d6

**Comment by tomponline** [comment]
Excellent, I will close this issue now as the fix will be in LXD 5.0.1.
Thanks!
