### ISSUE TITLE
Corner case: Profile may not be added to instance with identical name

### ISSUE THREAD

**Issue by holmanb** [lxc/lxd#10739]
I have a temp instance `me`, that I wanted to add a profile to. I named this temp profile `me`, but I was unable to add it to the instance:
```
arc~/cloud-init-g(:ffa91d41|✔) lxc profile add me me
Error: Duplicate profile found in request
```

It's easy enough to work around (`lxc profile copy me <something unique> && lxc profile add me <something unique>`), but I figured I would report, because I was surprised that name collision between a profile and instance are not allowed.

Looks to be caused by this chunk of code:
https://github.com/lxc/lxd/blob/bc0375a8fa7cf1731eeab91510ca809a023b1ce8/lxd/instance/drivers/driver_lxc.go#L3944

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc launch images:alpine/edge me
Creating me
Starting me                                 
stgraber@castiana:~$ lxc profile create me
Profile me created
stgraber@castiana:~$ lxc profile add me me
Profile me added to me
stgraber@castiana:~$ 
```

**Comment by stgraber** [comment]
The error you're hitting is what you'd get if the instance already had the `me` profile applied to it which I'm getting if I was to run the `add` command again after doing the above:

```
stgraber@castiana:~$ lxc profile add me me
Error: Duplicate profile found in request
stgraber@castiana:~$ 
```

**Comment by holmanb** [comment]
@stgraber Oops. I must not have been using a fresh instance and thought I was. My bad, apologies for the noise.
