### ISSUE TITLE
Ubuntu PPA is not updated for 0.17

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1073]
https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxd-git-master still lists 0.15 version.

   lxd (0.15-0ubuntu2~ubuntu15.04.1~ppa1)
   lxd-client (0.15-0ubuntu2~ubuntu15.04.1~ppa1)

**Comment by zfil** [comment]
Moreover https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxd-stable has not been updated yet has well.

It would be nice to automate this after each releases ...

**Comment by stgraber** [comment]
It's automated, once the package hits Ubuntu which it hasn't yet.

**Comment by stgraber** [comment]
lxd-git-master will eventually be getting actual daily builds but we haven't had time to set that up yet.

**Comment by stgraber** [comment]
I've updated lxd-git-master to 0.16 now and will tweak our scripts so it at least stays in sync with lxd-stable.

**Comment by techtonik** [comment]
> It's automated, once the package hits Ubuntu which it hasn't yet.

What does `package hits Ubuntu` mean?

> I've updated lxd-git-master to 0.16 now and will tweak our scripts so it at least stays in sync with lxd-stable.

Why not to 0.17?

**Comment by stgraber** [comment]
Packages automatically show up in the PPA a couple of hours after it's been uploaded to the Ubuntu development release at archive.ubuntu.com

**Comment by stgraber** [comment]
0.17 isn't there yet because I'm looking at doing some packaging changes for it, that and I was sick yesterday so couldn't get much done.

**Comment by techtonik** [comment]
Yea, I am sick of packaging in Linuxes too. Those undecipherable bash scripts and magic conventions tied to disty tomes of policies are discouraging.
