### ISSUE TITLE
lxc file mount panic

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#10734]
Both running LXD 5.4.

Remote server is running stock ubuntu 18.04.2 LTS and client is stock Ubuntu 20.04.3 LTS.

```
$ lxc file mount work-stage-machine:fs-design-dev/ tmp-remote/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x95a130]

goroutine 1 [running]:
github.com/lxc/lxd/client.(*ProtocolLXD).rawSFTPConn(0xc00018a480, 0xc000272510)
	/build/lxd/parts/lxd/src/client/lxd_instances.go:1381 +0x250
github.com/lxc/lxd/client.(*ProtocolLXD).GetInstanceFileSFTPConn(0xc00018a480, {0x7fff866abff3, 0xd})
	/build/lxd/parts/lxd/src/client/lxd_instances.go:1429 +0x12d
main.(*cmdFileMount).sshfsMount(0x0?, {0xd44078, 0xc000028130}, {{0x7fff866abfe0, 0x12}, {0xd4e628, 0xc00018a480}, {0x7fff866abff3, 0xe}}, {0x7fff866abff3, ...}, ...)
	/build/lxd/parts/lxd/src/lxc/file.go:1041 +0xaf
main.(*cmdFileMount).Run(0xc0001f8a80, 0xc00027a500, {0xc000253060?, 0x2, 0x0?})
	/build/lxd/parts/lxd/src/lxc/file.go:1032 +0x492
github.com/spf13/cobra.(*Command).execute(0xc00027a500, {0xc000253000, 0x2, 0x2})
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000248000)
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/build/lxd/parts/lxd/src/lxc/main.go:276 +0x1a33
```

**Comment by tomponline** [comment]
Is this reproducible all the time when doing a single command invocation, or does it require other environmental scenarios?

**Comment by tomponline** [comment]
Is this a VM or a container?

**Comment by turtle0x1** [comment]
Its a container, re-running the command results in the same error.

This is work so I haven't tried to reproduce to the same extent I would normally.

The only thing I can think that might be note worthy is that its over Wireguard but `exec bash` and other commands work fine.

**Comment by tomponline** [comment]
Does it work if run on the same host where the container is?

**Comment by tomponline** [comment]
I have a theory its this that introduced the regression https://github.com/lxc/lxd/commit/9cda9c2135601e223a462f2fbd8a4e0f8dc0e017

Will try and reproduce.

**Comment by turtle0x1** [comment]
Yes it works when run locally but I have to use sudo and had to install sshfs.

Checked again after installing sshfs and it still hasn't helped :disappointed:

**Comment by tomponline** [comment]
@turtle0x1 reproduced and fixed ^

**Comment by turtle0x1** [comment]
My hero :smile:
