### ISSUE TITLE
Expose a way to tune file system properties for instance and volume storage

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#10748]
It'd be nice for LXD to provide a way to tune file system properties for file systems. Here's a list of configuration options that I make use personally:

- atime
- compression
- devices
- exec
- relatime
- setuid

It'd also be nice if those properties could be carried through `lxc copy` and `lxc storage volume copy`.

**Comment by stgraber** [comment]
That's not really practical though as most of those are superblock options and so cannot be handled on a per mount basis.

The main exception here would be ZFS.

For the cases where a separate superblock is available, namely for LVM and for Ceph, we already do have a volume config option to handle this.

**Comment by stgraber** [comment]
`block.mount_options` does exactly this on LVM and Ceph. btrfs and dir cannot do it per volume.

This leaves us with zfs which I guess could get a zfs.properties with a key/value list of stuff to set on the dataset. I believe this was already suggested in another issue, so this issue may be a duplicate.

**Comment by simondeziel** [comment]
Some but not all mount options can be applied per subvolume with BTRFS, https://btrfs.readthedocs.io/en/latest/btrfs-man5.html#mount-options. I /think/ the generic mount options (nosuid, nodev, noexec, noatime, ...) are all supported per subvol.

**Comment by simondeziel** [comment]
The BTRFS man page says the output of `mount` shows which options were applied to a given subvolume so here's my test using 2 subvolumes with different "generic" option sets:

```
# mount | grep btrfs
/dev/sda3 on / type btrfs (rw,noatime,space_cache=v2,subvolid=256,subvol=/@)
/dev/sda3 on /home type btrfs (rw,nosuid,nodev,noexec,relatime,space_cache=v2,subvolid=257,subvol=/@home)
```

**Comment by stgraber** [comment]
That however requires you to actually mount the subvol as a separate mount which isn't something we do.

There's no way to do `btrfs subvol create -o nodev,nosuid` and have this persist in the subvol config.

**Comment by stgraber** [comment]
Closing as I don't see a good way to provide this without making it specific to containers on ZFS.
