### ISSUE TITLE
Implement all-projects query parameter for storage volumes

### ISSUE THREAD

**Issue by markylaing** [lxc/lxd#10753]
In order to complete https://github.com/canonical/lxd-cloud/issues/136, upstream servers need to synchronise instance and storage volume records when the make a connection to a downstream. 

To accomplish this, we can call `/1.0/instances?all-projects=true` for instances, but there is currently no equivalent for volumes. We could iterate over projects and make a separate call for each but this would result in lots of unnecessary requests.

**Comment by tomponline** [comment]
Is this all projects and all storage pools or just all projects for a single storage pool?

**Comment by markylaing** [comment]
Just all projects for a single storage pool.

**Comment by tomponline** [comment]
Will you iterate over each storage pool separately then?

**Comment by markylaing** [comment]
The `remote` and `remote-fs` pools will be handled entirely by the region so we just need to call `GET `/1.0/storage-pools/local/volumes?all-projects=true`. 

https://github.com/canonical/lxd-cloud/issues/136#issuecomment-1177743822

**Comment by tomponline** [comment]
Right so there's only 1 local pool in this context?
