### ISSUE TITLE
QEMU failed to run a feature check for virtual-machine

### ISSUE THREAD

**Issue by gozssky** [lxc/lxd#10771]
# Required information

 * Distribution: CentOS 7
 * Distribution version: 7
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.10.0-957.el7.x86_64
   * LXC version: 5.3
   * LXD version: 5.3
   * Storage backend in use: lvm

# Issue description

LXD failed to run a feature check for `virtual-machine`. As a result, I am unable to create a virtual machine. This node supports creating virtual machines. There are 4 existing virtual machines running on this node. They were created by LXD.
LXD log:
```
Aug 11 14:01:08 KS-22 lxd.daemon[3064906]: time="2022-08-11T14:01:08+08:00" level=error msg="Unable to run io_uring check during QEMU initialization: open /tmp/464998873: no such file or directory"
Aug 11 14:01:08 KS-22 lxd.daemon[3064906]: time="2022-08-11T14:01:08+08:00" level=warning msg="Instance type not operational" driver=qemu err="QEMU failed to run a feature check" type=virtual-machine
```
LXC error when creating a virtual machine:
```
[root@KS-22 ubuntu]# lxc launch images:ubuntu/22.04/cloud dev04 --vm --storage nvme0n1 --target=ks-22
Creating dev04
Error: Failed instance creation: Failed creating instance record: Instance type "virtual-machine" is not supported on this server: QEMU failed to run a feature check
```

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by gozssky** [comment]
It seems the error is returned from this function:
https://github.com/lxc/lxd/blob/a5b9cb5ab9ea0306a1f31d9b07aa890331ebffde/lxd/instance/drivers/driver_qemu.go#L6216-L6220
But I have no idea why the temporary is not found and which line return this error.

**Comment by stgraber** [comment]
Is that using the snap?

If so, most likely what happened is that you or some piece of software on your system decided to cleanup /tmp on the host.
Specifically, something deleted `/tmp/snap.lxd` which then breaks `/tmp` in the entire snap and will cause such errors every time something in LXD attempts to create a temporary file.

If that's your issue, try to figure out what would have caused `/tmp/snap.lxd` to be deleted, then fix that and reboot your system.

**Comment by gozssky** [comment]
Yes, LXD is installed by the snap. I checked the tmpfiles.d config and it will automatically clean up the `/tmp/snap.lxd` directory. I excluded it from the cleanup and remount all `var-lib-snapd-snap-*-.mount`  in `/etc/systemd/system/`. Then the problem is solved.

Thanks for your reply very much!
