### ISSUE TITLE
lxd-5.0.1: shellcheck is called when attempting to "build-mo"

### ISSUE THREAD

**Issue by juippis** [lxc/lxd#10795]
# Issue description

Whenever you call **make build-mo** it executes `$(shell shellcheck --version | grep version: | cut -d ' ' -f2)` even though that seems to be related to **static-analysis** phase. I can't see how shellcheck is required outside **static-analysis, so maybe the `
SHELLCHECK_VERSION := $(shell shellcheck --version | grep version: | cut -d ' ' -f2)` can be moved downwards away from **build-mo**? 

It prints a warning that's not fatal.

**Comment by tomponline** [comment]
I've seen this too. Agreed its weird.

**Comment by tomponline** [comment]
Any ideas @markylaing ?
