### ISSUE TITLE
Perform case insensitive match when checking for duplicate instance names at create time

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10797]
Suggested from https://github.com/lxc/lxd/pull/10789#issuecomment-1216973016

Because the instance name is used to set the DNS name and DNS names are case insensitive, we need to check if another instance exists using the same name using a case insensitive check to avoid DNS name conflicts.

**Comment by DarthBenro008** [comment]
Hi @tomponline, 

I'd like to work on this issue, being new to the codebase, i did some digging. 

I figured that the following function needs the change

https://github.com/lxc/lxd/blob/03d641b7b566361af9af6fa7bc6f457efaea6956/lxd/db/cluster/instances.mapper.go#L721-L732

However, i just wanted to confirm, is this a `generated` file? Can i directly make the changes in the `instances.mapper.go` file or do i have to change some definitions elsewhere? Any help would be appreciated!

**Comment by tomponline** [comment]
@DarthBenro008 thanks! 

So I think we'll need to be a bit more fine grained than that as we want to minimise the chances of breaking existing users' workflows.

For this particular issue we are only interested in instances that are connected to a managed network that is capable of generating DNS records from instance names. This narrows it down to instances connected to `bridge` and `ovn` networks types.

Further more we are only interested in checking that the instance name doesn't conflict with any other instance that happens to be connected to the network at that time (which could be after instance creation if a NIC device is added later). This also means we cannot restrict the name conflict check to just those instances within the same project (as for `bridged` networks we can connect instances from multiple projects).

Instead I think the lightest touch place and safest will be adding a check to the `bridged` and `ovn` NIC types' `checkAddressConflict` function:

* `bridged` https://github.com/lxc/lxd/blob/master/lxd/device/nic_bridged.go#L360
* `ovn` https://github.com/lxc/lxd/blob/master/lxd/device/nic_ovn.go#L230

I think this is a good place to do it because:

* We already use `network.UsedByInstanceDevices` in those functions to load all instances and check which ones are connected to the network, so no additional DB queries required.
* The NIC's instance name and the instance being checked's name is available in Go.
* Comparison be done using a Go function.
* Will only apply check if the instance has a NIC connected to the network (but will check after instance creation time too).

**Comment by tomponline** [comment]
I think having a bew common function called from `checkAddressConflict` functions will be good to avoid logic duplication.
You could call it `nicCheckDNSNameConflict(nameA string, nameB string) error` and add it to `lxd/device/nic.go` file.

**Comment by tomponline** [comment]
@DarthBenro008 how are you getting on with this? Thanks
