### ISSUE TITLE
Add support for device overrides when creating/launching instance

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10796]
Suggested at https://discuss.linuxcontainers.org/t/how-to-make-ips-fixed-to-an-instance-from-the-managed-bridge/14838/4?u=tomp

Proposal to add `--device` and `-d` flags to `lxc launch` and `lxc init` that would allow device override at create time.
Similar to what we have now for `lxc copy` and `lxc move`.

The format of the flag value would be the same, i.e `-d <device_name>,<key>=<value>`.

**Comment by markylaing** [comment]
@stgraber @tomponline if overriding a single key from a profile (e.g. `lxc launch images:alpine/edge c1 -d root,pool=remote`) we don't know which profile contains the device that is having it's config key overridden, but we also cannot provide an incomplete device configuration on the instance.

We can either:
1. Query LXD for each profile until we have a matching device name and then fully populate the device config by combining the profile and the overridden key(s).
2. Force users to always specify a full device configuration, e.g. `lxc launch images:alpine/edge c1 -d root,type=disk -d root,path=/ -d root,pool=remote`. 

I don't mind either way but for option 2 I wonder if there is a better syntax we can use, e.g. `-d root:[type=disk path=/ pool=remote]` (or something along those lines).

**Comment by tomponline** [comment]
What is the current behavior for lxc copy, as we want it to mirror that.

**Comment by stgraber** [comment]
You'd just pick the ExpandedDevices struct, copy the device from there and override the one key they provided.

**Comment by tomponline** [comment]
Yeah I suspect thats what the current behaviour is.

**Comment by tomponline** [comment]
So this is effectively the same as doing `lxc init ...` followed by `lxc config device override ...`
