### ISSUE TITLE
VM: Restart force after doing lxc file push makes file contents go away (ZFS backed)

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxd#10800]
```
# uname -a
Linux yar 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
# lxc --version
5.4
```

Issuing `lxc restart --force` quickly after having done an `lxc file push` operation results in that file being truncated. This is on a zfs backed system. Steps to reproduce:

```
# lxc launch images:ubuntu/focal testvm --profile testvm --vm
..> Wait for the container to spin up and the agent to be ready
# echo "Hello" > /tmp/foobar
# lxc file push /tmp/foobar testvm/home/foobar --create-dirs
# lxc exec testvm bash
root@testvm:~# cat /home/foobar
Hello
root@testvm:~# exit
exit
# lxc restart --force testvm #Do this within some seconds of pushing the file
..> Wait for the container to spin up and the agent to be ready
# lxc exec testvm bash
root@testvm:~# cat /home/foobar
cat: /home/foobar: No such file or directory
```

Why??? This seems to be time variant somehow. If I immediately lxc exec into the VM and cat the contents it's there. But if I do a restart --force within about 5-10 seconds (at least on my system) once restarted, the file contents is gone

This seems to be somehow related to data not being synched to disk for some reason - maybe my zfs settings are at fault here? I do have `sync=disabled ` set on my zfs dataset but I thought that would only be an issue if the host went down suddenly - but I guess maybe in the case of VMs the zfs dataset is handled differrently so if the VM suddenly reboots this causes the loss of data?

**Comment by tomponline** [comment]
Yes `sync=disabled` would most likely be the issue as issuing `lxc restart --force` effectively crashes the instance.
Can you try doing `lxc exec <instance> -- sync` before doing the restart and see if it fixes it.

**Comment by tomponline** [comment]
Where is `sync=disabled` set on the LXD host or inside the VM?

**Comment by webdock-io** [comment]
`sync=disabled` is set on the host

As the host hasn't crashed, I am wondering why the dataset isn't being synced like it does with containers. I guess you are using/mounting zfs in a very different way than with containers in this case.

Doing

`lxc file push /tmp/foobar testvm/home/foobar --create-dirs; lxc exec testvm -- sync; lxc restart --force testvm;`

Does indeed make this issue go away, while

`lxc file push /tmp/foobar testvm/home/foobar --create-dirs; lxc restart --force testvm;`

Consistently means the file is truncated or never written to disk. (I'm making sure to wait at least 10 seconds between each test or doing graceful reboot so the tests are valid) So it seems we have found the underlying issue.

**Comment by stgraber** [comment]
Yeah, I don't think this is a bug. If you copy a file to your machine and yank out the power a second later, chances are your filesystem won't have synced there either.

The issue here isn't on the ZFS side (host) but instead to do with the filesystem inside of the VM.
`ext4` normally performs full journal flushes every 5 to 30s and it can be tweaked to be much longer.

With a container, a `lxc restart --force` just forcefully kills all processes, which can incur data loss for anything that wasn't sent to the filesystem but anything that did hit the filesystem will be saved as it's the host kernel that will handle the final flush.

In the case of a VM, LXD provides a block device to the VM, the VM kernel then handles the writes and filesystem.
If power is lost prior to things being flushed by the VM kernel to the underlying block device, data loss will occur.

**Comment by webdock-io** [comment]
@stgraber Thank you for the detailed explanation. I wasn't aware of this behavior in ext4 and was stuck in the container mindset where the operations are happening directly against the zfs dataset, hence the surprise when I saw dataloss on a restart --force operation.

I will continue our journey towards KVM compatibility with our current tooling so don't be surprised if I pop back up with further perceived weirdness ;)

**Comment by tomponline** [comment]
When running a VM ontop of ZFS, LXD uses ZFS zvols (which present as just block devices) and then the VM guest itself has its own partitions and filesystem(s). By default the LXD built VM images use ext4 as the VM guest filesystem, but if you install a VM using a custom image or using the `--empty` flag and perform an installation by booting from ISO/network then the VM guest can use any partition and filesystem type.
