### ISSUE TITLE
lxc launch/init with image name from config

### ISSUE THREAD

**Issue by M1cha** [lxc/lxd#10819]
Before I go ahead and implement it, I wanna make sure there's not objections.

I have one yaml-file per instance which I use to specify a full container config. It contains configs, devices, profiles, the cloud-init config and sometimes even `volatile.eth0.hwaddr`. The only thing that's missing is the image name.

There's already a copy of the image properties in `image.*`. But that seems to be missing remote and alias. There's also `volatile.base_image`. While this might in theory work if LXD queries  all remotes and looks for an image with that hash it's both inefficient and not flexible enough since you might also want to specify a remote and image name to pull from.

So I guess what we'd have to do is introduce a new config like `volatile.image_spec` which you could set to e.g. `images:ubuntu/kinetic`.

Side-note: You might want to enable GitHub discussion for such non-issues.

**Comment by tomponline** [comment]
I think @stgraber will have thoughts on this.

@M1cha for discussions we use https://discuss.linuxcontainers.org/ so would be better to post there first in the future.

**Comment by stgraber** [comment]
So currently we've got `lxc launch` and `lxc init` parse stdin as InstancePut.
We could change that to instead parse stdin as InstancePost when no arguments are passed.

So this would allow `lxc launch < definition.yaml` where definition.yaml would include the instance name as well as its source.
Note however that the source will need to be an InstanceSource meaning it will need to include the address of the source server, alias name, certificate, ... It can't be a `remote` as there's no such concept in LXD itself, it's just a convenience provided by the CLI.

**Comment by M1cha** [comment]
> So this would allow `lxc launch < definition.yaml` where definition.yaml would include the instance name as well as its source.

It'd be great if we could still override the instance name so you can create multiple instances using the same generic config.

> Note however that the source will need to be an InstanceSource meaning it will need to include the address of the source server, alias name, certificate, ... It can't be a `remote` as there's no such concept in LXD itself, it's just a convenience provided by the CLI.

That'd kinda sad. Couldn't we have the CLI parse part of the yaml config so it can resolve that?

**Comment by stgraber** [comment]
No, I don't want to introduce custom YAML wrappers or structs just for this. It would also confuse users into thinking this can be sent over the REST API when it can't.

Since you want to still override the name and so not provide the entire thing, I'm not sure what's wrong with the current way.
`lxc launch images:foo name < config.yaml` seems to be giving you the best of all worlds, you get to easily script a different name, you have the CLI parse the remote and image for you, expending that into an InstanceSource for you and you still get to control the config, devices and profiles.
