### ISSUE TITLE
Adding member to a cluster doesn't work somethimes due to wrong TLS certificate name

### ISSUE THREAD

**Issue by k-kacprzak-vercom** [lxc/lxd#10811]
# Required information

 * Distribution: Ubuntu Server
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-46-generic
   * LXD version: 5.4-1ff8d34
   * Storage backend in use: dir

# Issue description

Sometimes when adding a member to a cluster with "lxd init" it fails due to wrong name of TLS certificate generated on cluster machine. Error is:
`Existing server certificate with different name "[hostname]" already in trust store`
Despite never adding server to trust store. Observed behavior is, that during adding member to a cluster it generates TLS cert with new member's hostname, instead of characteristic name given during "lxc cluster add" or "lxd init". Problem exists both when using token and password. 
Reinstall of LXD fixes the issue.

# Steps to reproduce

1. Try to add new member to cluster
2. Give member characteristic name
3. TLS cert is generated from hostname, not given characteristic name

**Comment by tomponline** [comment]
Do you have a reproducer that always occurs?
