### ISSUE TITLE
agent.nic_config does nothing on CentOS / AlmaLinux

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxd#10838]
I have read the pull requests (https://github.com/lxc/lxd/pull/9967) and looked at the implementation of agent.nic_config but I see no mention of specific OS support (or lack thereof)

In short, spinning up a number of VMs I see that setting `agent.nic_config = true` works as expected for Ubuntu 20.04 22.04 and Debian 11 but not for CentOS 8 and Almalinux 8 (these are all the OSes I have tested thus far - I may test more/other versions at a later date)

I am using the images:xxx/xxx/cloud images

Is this expected or a failure in LXD to apply the config as it's supposed to?

**Comment by stgraber** [comment]
You can check `/run/lxd_agent/` to check that the config did make it through.
Assuming it did and lines up with your interfaces, then look at the journalctl entries for the agent unit.

**Comment by webdock-io** [comment]
@stgraber The plot thickens :)

```
[root@testalma ~]# ls -lah /run/lxd_agent/
total 12M
drwx------  6 root root 240 Aug 23 12:59 .
drwxr-xr-x 25 root root 640 Aug 23 13:00 ..
-r--------  1 root root   2 Aug 23 12:59 agent-mounts.json
-r--------  1 root root 725 Aug 23 12:59 agent.crt
-r--------  1 root root 288 Aug 23 12:59 agent.key
dr-x------  2 root root  60 Aug 23 12:59 files
-rwx------  1 root root 889 Aug 23 12:59 install.sh
-r-x------  1 root root 12M Jul 22 17:34 lxd-agent
dr-x------  2 root root  60 Aug 23 12:59 nics
-r--------  1 root root 692 Aug 23 12:59 server.crt
dr-x------  2 root root  80 Aug 23 12:51 systemd
dr-x------  2 root root  60 Aug 23 12:51 udev

[root@testalma ~]# grep -iIr "eth0" /run/lxd_agent
/run/lxd_agent/nics/eth0.json:{"device_name":"eth0","nic_name":"eth0","mac_address":"00:16:3e:1a:86:b5","mtu":1500}
/run/lxd_agent/files/metadata.yaml:  /etc/sysconfig/network-scripts/ifcfg-eth0:
/run/lxd_agent/files/metadata.yaml:    template: ifcfg-eth0.lxd.tpl

# journalctl -u lxd-agent
-- Logs begin at Tue 2022-08-23 12:59:38 UTC, end at Wed 2022-08-24 08:52:28 UTC. --
Aug 23 12:59:40 testalma systemd[1]: Started LXD - agent.

[root@testalma ~]# systemctl status lxd-agent
● lxd-agent.service - LXD - agent
   Loaded: loaded (/usr/lib/systemd/system/lxd-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2022-08-23 12:59:40 UTC; 19h ago
     Docs: https://linuxcontainers.org/lxd
  Process: 673 ExecStartPre=/lib/systemd/lxd-agent-setup (code=exited, status=0/SUCCESS)
 Main PID: 709 (lxd-agent)
    Tasks: 23 (limit: 118728)
   Memory: 60.9M
   CGroup: /system.slice/lxd-agent.service
           ├─ 709 /run/lxd_agent/lxd-agent
           ├─2120 bash
           ├─2160 systemctl status lxd-agent
           └─2161 more

Aug 23 12:59:40 testalma systemd[1]: Started LXD - agent.
```

So, the config made it but the agent didn't act on it, for whatever reason?

**Comment by webdock-io** [comment]
@stgraber I had a little time to further diagnose this

If I lxc exec into the VM and issue `systemctl restart lxd-agent` well what do you know, the ethernet interface is renamed and all is well. If I reboot the VM then after boot the agent has done nothing.

The agent is running however, so it's not because it hasn't been started.

So, for some reason, on boot of Centos or Almalinux the agent fails to rename the nic and set mtu etc. - but if restarted after the system has booted it manages to do it.

I'm guessing maybe the system isn't quite ready yet when the agent starts "doing its thing" ?

I tried adding a crontab for root with `@reboot systemctl restart lxd-agent` and this gets triggered a while after the VM is otherwise ready presumably as it's one of the last things to run after a boot, and sure enough then the interface is renamed and mtu is in order.

This may be what I'll do for now as a quick and dirty fix for this issue - but I think this warrants a closer look by you guys potentially.

**Comment by webdock-io** [comment]
So this is a possible wontfix - got it

We are getting around this now by adding a "systemctl restart lxd-agent" to crontab @reboot - which works, but causes the machine to act a bit flaky on startup but it eventually settles down and everything works.

**Comment by stgraber** [comment]
Closing as indeed, not something we can do lots about from our side.
An alternative to your approach may be to locate the conflicting udev rule and remove/comment it out?
