### ISSUE TITLE
lxd-generate join config tag not working as expected

### ISSUE THREAD

**Issue by markylaing** [lxc/lxd#10844]
I'm working on a follow up to https://github.com/canonical/lxd-cloud/pull/151. Many (if not all) methods that use the resources table would be greatly simplified by changing the `Resource` database type from 
```go
type Resource struct {
	ID        int
	Name      string       `db:"primary=true"`
	Type      ResourceType `db:"primary=true"`
	Cluster   string       `db:"join=clusters.name"`
	ProjectID int          `db:"primary=true"`
}
```
to
```go
type Resource struct {
	ID      int
	Name    string       `db:"primary=true"`
	Type    ResourceType `db:"primary=true"`
	Cluster string       `db:"join=clusters.name"`
	ProjectUUID string       `db:"primary=true&join=projects.uuid"`
}
```

i.e. changing `ProjectID` to `ProjectUUID` and using joins.

However I'm having problems generating the statements and methods.

Firstly, there is an incorrect table name in the `ORDER BY` clause of all `objects` statements. E.g:
```sql
SELECT resources.id, resources.name, resources.type, clusters.name AS cluster, projects.uuid AS project_uuid
  FROM resources JOIN clusters ON resources.cluster_id = clusters.id JOIN projects ON resources.project_id = projects.id
  ORDER BY resources.name, resources.type, project_uuids.id
```
where `project_uuids.id` is incorrect.

Secondly, the `delete`, `rename`, and `update` statements perform subselects on both the wrong table, and the wrong column. E.g.
```sql
DELETE FROM resources WHERE name = ? AND type = ? AND project_uuid_id = (SELECT projects_uuids.id FROM projects_uuids WHERE projects_uuids.name = ?)
```
where `project_uuids` is the wrong table, and `name` is the wrong column.

I've tried changing `ProjectUUID` to `Project` and this solves the first issue, but not the second (i.e. the subselect still uses the `name` column). This is also not ideal as the field name becomes more ambiguous.

Ideally the table name and column for performing joins and selects should come directly from the config.

@masnax is this feasible?

**Comment by tomponline** [comment]
@markylaing how is this working in LXD when we filter on `Project` in `type Instance struct` for example?

**Comment by markylaing** [comment]
Taking the profile database type as an example in LXD:

https://github.com/lxc/lxd/blob/3f28c0fc867b72e9166f3292c2f51b0b87262a23/lxd/db/cluster/profiles.go#L39-L45

This is currently working fine because a) the field `Project` is the uppercased and singular version of the table `projects`, and b) it is joining on `name`. All joins in LXD so far seem to be of this form, so we haven't encountered it until now.

The table against which the join is performed is coming from the struct field name and not from the tag, and in some cases using name in subselects was previously hardcoded.

**Comment by tomponline** [comment]
@masnax @markylaing so it the route cause of this problem the DB generators incorrect assumptions/conversions of struct field names to table column names?

**Comment by markylaing** [comment]
I think I missed this comment earlier sorry. Yes, in the example in the issue description the generator assumed that the table name against which to perform the join would be the snake cased, pluralised version of `ProjectUUID`, leading to `project_uuids`.
