### ISSUE TITLE
dnsmasq allocates wrong IP after a reboot, when doing a rebuild of an instance

### ISSUE THREAD

**Issue by cricalix** [lxc/lxd#10853]
Problem:

A combination of `start`, `stop`, `launch` actions and a host reboot results in dnsmasq recording the wrong IP for an instance name, breaking name resolution between instances on the bridge.

Short repro:
* Spin up two instances (ubuntu/22.04/cloud)
* Stop, start the first instance
* Reboot
* Stop, delete, launch the second instance
* Name resolution breaks

# Reproduction
## Environment

OS
`cat /etc/os-release`
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
```

Kernel
`uname -a`
```
Linux barracuda.local 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

LXD version
```
Name  Version      Rev    Tracking       Publisher   Notes
lxd   5.4-82d05d6  23339  latest/stable  canonical✓  disabled
lxd   5.4-1ff8d34  23367  latest/stable  canonical✓  -
```

Network configuration
```
lxc network show lxdbr0
config:
  ipv4.address: 10.68.0.1/24
  ipv4.dhcp.expiry: 1d
  ipv4.nat: "true"
  raw.dnsmasq: no-hosts
description: ""
name: lxdbr0
type: bridge
```

Verify no leases

`ls -l /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases`
```
-rw-r--r-- 1 root root 0 Aug 26 07:15 /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases
```

`lxc network list-leases lxdbr0`
```
+----------+-------------+------------+------+
| HOSTNAME | MAC ADDRESS | IP ADDRESS | TYPE |
+----------+-------------+------------+------+
```

`lxc list`
```
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
```

## Init

`lxc launch --profile default images:ubuntu/22.04/cloud first`
`lxc launch --profile default images:ubuntu/22.04/cloud second`

## Confirm the network status
`lxc list`
```
+--------+---------+--------------------+------+-----------+-----------+
|  NAME  |  STATE  |        IPV4        | IPV6 |   TYPE    | SNAPSHOTS |
+--------+---------+--------------------+------+-----------+-----------+
| first  | RUNNING | 10.68.0.112 (eth0) |      | CONTAINER | 0         |
+--------+---------+--------------------+------+-----------+-----------+
| second | RUNNING | 10.68.0.49 (eth0)  |      | CONTAINER | 0         |
+--------+---------+--------------------+------+-----------+-----------+
```

`lxc network list-leases lxdbr0`
```
+----------+-------------------+-------------+---------+
| HOSTNAME |    MAC ADDRESS    | IP ADDRESS  |  TYPE   |
+----------+-------------------+-------------+---------+
| first    | 00:16:3e:3d:16:be | 10.68.0.112 | DYNAMIC |
+----------+-------------------+-------------+---------+
| second   | 00:16:3e:0d:6a:bf | 10.68.0.49  | DYNAMIC |
+----------+-------------------+-------------+---------+
```

Leases file shows (as I understand it) that opaque IDs are being used based on `/etc/machine-id` of each instance.

`cat /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases`
```
1661581185 00:16:3e:0d:6a:bf 10.68.0.49 second ff:ca:1a:24:ae:00:02:00:00:ab:11:57:17:bb:18:77:8d:5d:a4
1661581181 00:16:3e:3d:16:be 10.68.0.112 first ff:8f:d1:24:21:00:02:00:00:ab:11:e9:8c:68:97:54:98:24:ea
```
Record machine IDs

`lxc exec first -- cat /etc/machine-id`
```c1beef4fdf0c4d92ada054a1d9b2a1c6```

`lxc exec second -- cat /etc/machine-id`
```2a8c95a63a974b3781c4c1913ac81ff9```

## Trigger an IP expiration in dnsmasq

This has to be done with the first instance, and not the second. Restarting the second instance does not trigger an expiration event in dnsmasq, despite using the same commands. Some kind of ordering issue in the leases file?

`lxc stop first && lxc start first`

`lxc list`
```
+--------+---------+--------------------+------+-----------+-----------+
|  NAME  |  STATE  |        IPV4        | IPV6 |   TYPE    | SNAPSHOTS |
+--------+---------+--------------------+------+-----------+-----------+
| first  | RUNNING | 10.68.0.112 (eth0) |      | CONTAINER | 0         |
+--------+---------+--------------------+------+-----------+-----------+
| second | RUNNING | 10.68.0.49 (eth0)  |      | CONTAINER | 0         |
+--------+---------+--------------------+------+-----------+-----------+
```

`lxc network list-leases lxdbr0`
```
+----------+-------------------+-------------+---------+
| HOSTNAME |    MAC ADDRESS    | IP ADDRESS  |  TYPE   |
+----------+-------------------+-------------+---------+
| *        | 00:16:3e:3d:16:be | 10.68.0.113 | DYNAMIC |
+----------+-------------------+-------------+---------+
| first    | 00:16:3e:3d:16:be | 10.68.0.112 | DYNAMIC |
+----------+-------------------+-------------+---------+
| second   | 00:16:3e:0d:6a:bf | 10.68.0.49  | DYNAMIC |
+----------+-------------------+-------------+---------+
```

Check leases file
`cat /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases`
```
1661581356 00:16:3e:3d:16:be 10.68.0.113 * 01:00:16:3e:3d:16:be
1661581185 00:16:3e:0d:6a:bf 10.68.0.49 second ff:ca:1a:24:ae:00:02:00:00:ab:11:57:17:bb:18:77:8d:5d:a4
1661581357 00:16:3e:3d:16:be 10.68.0.112 first ff:8f:d1:24:21:00:02:00:00:ab:11:e9:8c:68:97:54:98:24:ea
```

A new IP has shown up, but it's expired. The identifier is the MAC of the `first` instance.

## Reboot the host

This appears to be a critical event; not rebooting and trying the rebuild step that comes next does not result in dnsmasq swapping IPs.

Post reboot, check the configuration.

```
+--------+---------+--------------------+------+-----------+-----------+
|  NAME  |  STATE  |        IPV4        | IPV6 |   TYPE    | SNAPSHOTS |
+--------+---------+--------------------+------+-----------+-----------+
| first  | RUNNING | 10.68.0.112 (eth0) |      | CONTAINER | 0         |
+--------+---------+--------------------+------+-----------+-----------+
| second | RUNNING | 10.68.0.49 (eth0)  |      | CONTAINER | 0         |
+--------+---------+--------------------+------+-----------+-----------+

+----------+-------------------+-------------+---------+
| HOSTNAME |    MAC ADDRESS    | IP ADDRESS  |  TYPE   |
+----------+-------------------+-------------+---------+
| *        | 00:16:3e:3d:16:be | 10.68.0.113 | DYNAMIC |
+----------+-------------------+-------------+---------+
| first    | 00:16:3e:3d:16:be | 10.68.0.112 | DYNAMIC |
+----------+-------------------+-------------+---------+
| second   | 00:16:3e:0d:6a:bf | 10.68.0.49  | DYNAMIC |
+----------+-------------------+-------------+---------+
```

IP addresses still line up between `list` and `list-leases`.

## Rebuild second to get a new IP assigned

`lxc stop second && lxc delete second && lxc launch --profile default images:ubuntu/22.04/default second`

`lxc list`
```
+--------+---------+--------------------+------+-----------+-----------+
|  NAME  |  STATE  |        IPV4        | IPV6 |   TYPE    | SNAPSHOTS |
+--------+---------+--------------------+------+-----------+-----------+
| first  | RUNNING | 10.68.0.112 (eth0) |      | CONTAINER | 0         |
+--------+---------+--------------------+------+-----------+-----------+
| second | RUNNING | 10.68.0.204 (eth0) |      | CONTAINER | 0         |
+--------+---------+--------------------+------+-----------+-----------+
```

`lxc network list-leases lxdbr0`
```
+----------+-------------------+-------------+---------+
| HOSTNAME |    MAC ADDRESS    | IP ADDRESS  |  TYPE   |
+----------+-------------------+-------------+---------+
| *        | 00:16:3e:3d:16:be | 10.68.0.112 | DYNAMIC |
+----------+-------------------+-------------+---------+
| first    | 00:16:3e:3d:16:be | 10.68.0.113 | DYNAMIC |
+----------+-------------------+-------------+---------+
| second   | 00:16:3e:60:36:0f | 10.68.0.204 | DYNAMIC |
+----------+-------------------+-------------+---------+
```

`cat /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases`
```
1661581623 00:16:3e:60:36:0f 10.68.0.204 second 01:00:16:3e:60:36:0f
1661581556 00:16:3e:3d:16:be 10.68.0.112 * ff:8f:d1:24:21:00:02:00:00:ab:11:e9:8c:68:97:54:98:24:ea
1661581356 00:16:3e:3d:16:be 10.68.0.113 first 01:00:16:3e:3d:16:be
```

`lxc exec first -- cat /etc/machine-id`
```
c1beef4fdf0c4d92ada054a1d9b2a1c6
```

`lxc exec second -- cat /etc/machine-id`
```
459309bd75f04c0489445524321bdca5
```

Outcome: Name resolution is now broken on `second` if it tries to find `first`.

`lxc info first`
```
Name: first
Status: RUNNING
Type: container
Architecture: x86_64
PID: 2475
Created: 2022/08/26 07:19 IST
Last Used: 2022/08/26 07:25 IST

Resources:
  Processes: 18
  CPU usage:
    CPU usage (in seconds): 1
  Memory usage:
    Memory (current): 133.42MiB
  Network usage:
    eth0:
      Type: broadcast
      State: UP
      Host interface: vethff08f011
      MAC address: 00:16:3e:3d:16:be
      MTU: 1500
      Bytes received: 5.98kB
      Bytes sent: 1.81kB
      Packets received: 50
      Packets sent: 17
      IP addresses:
        inet:  10.68.0.112/24 (global)
        inet6: fe80::216:3eff:fe3d:16be/64 (link)
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)
```

`lxc info second`
```
Name: second
Status: RUNNING
Type: container
Architecture: x86_64
PID: 3843
Created: 2022/08/26 07:27 IST
Last Used: 2022/08/26 07:27 IST

Resources:
  Processes: 13
  CPU usage:
    CPU usage (in seconds): 0
  Memory usage:
    Memory (current): 41.98MiB
  Network usage:
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)
    eth0:
      Type: broadcast
      State: UP

      Host interface: veth2eeba6b9
      MAC address: 00:16:3e:60:36:0f
      MTU: 1500
      Bytes received: 1.33kB
      Bytes sent: 1.79kB
      Packets received: 12
      Packets sent: 17
      IP addresses:
        inet:  10.68.0.204/24 (global)
        inet6: fe80::216:3eff:fe60:360f/64 (link)
```
[lxc.monitor.txt](https://github.com/lxc/lxd/files/9430503/lxc.monitor.txt)

**Comment by cricalix** [comment]
I only ran in to this problem because I'm doing a lot of stops, starts, and re-launches of instances as I test a new setup (splitting a monolithic VPS into lxd containers), and it's on my home PC that gets shut down at night.

dnsmasq itself, as spawned from lxd, does not appear to log anything in /var/snap.

**Comment by tomponline** [comment]
I think the thing that stands out as a problem for me is the rogue extra lease allocation for `first`'s MAC address.
Can you `lxc config show <instance> --expanded` for each instance please.

Also can you try and see if you get the same issue using `images:ubuntu/22.04` without the `/cloud` part.

**Comment by tomponline** [comment]
Ive reproduced the issue but it only occurs for me when using the `images:ubuntu/22.04/cloud` images.

@monstermunchkin is there anything in the `/cloud` images that could be performing when the instance is stopped?

```
lxc launch images:ubuntu/jammy/cloud c1
Creating c1
Starting c1                               

lxc network list-leases lxdbr0
+----------+-------------------+----------------------------------------+---------+
| HOSTNAME |    MAC ADDRESS    |               IP ADDRESS               |  TYPE   |
+----------+-------------------+----------------------------------------+---------+
| c1       | 00:16:3e:8f:13:15 | 10.21.203.217                          | DYNAMIC |
+----------+-------------------+----------------------------------------+---------+
| c1       | 00:16:3e:8f:13:15 | fd42:ffdb:caff:baf7:216:3eff:fe8f:1315 | DYNAMIC |
+----------+-------------------+----------------------------------------+---------+

lxc stop c1
lxc network list-leases lxdbr0
+----------+-------------------+----------------------------------------+---------+
| HOSTNAME |    MAC ADDRESS    |               IP ADDRESS               |  TYPE   |
+----------+-------------------+----------------------------------------+---------+
| *        | 00:16:3e:8f:13:15 | 10.21.203.217                          | DYNAMIC |
+----------+-------------------+----------------------------------------+---------+
| c1       | 00:16:3e:8f:13:15 | 10.21.203.218                          | DYNAMIC |
+----------+-------------------+----------------------------------------+---------+
| c1       | 00:16:3e:8f:13:15 | fd42:ffdb:caff:baf7:216:3eff:fe8f:1315 | DYNAMIC |
+----------+-------------------+----------------------------------------+---------+
```

There's a weird extra allocation created on stop.

**Comment by cricalix** [comment]
I forgot to include the netplan config, but all it says is "dhcp for ipv4", nothing about use MAC address as the client identifier.

**Comment by tomponline** [comment]
This does seem like a cloud-init issue as its present in the `ubuntu:22.04` image too, which isn't built by the LXD team.

**Comment by stgraber** [comment]
I suspect that cloud-init generated netplan does not tell systemd to use the MAC as the identifier, so it instead uses a GUID which prevents us from assigning a static IP.

**Comment by stgraber** [comment]
I'm closing the issue because there's nothing we can do on LXD's side when this occurs.

But maybe we can convince the cloud-init folks to change their configuration.

In your particular case, I expect you can override that default cloud-init configuration through cloud-init.network-config

**Comment by stgraber** [comment]
@blackboxsw

**Comment by cricalix** [comment]
Yeah, I was quite happy with non-static addresses; less to manage that way. If something about how cloud-init runs is mucking with dnsmasq's visibility, I'm ok with this closing. It's just really weird that the identifier switches "mid-run" from opaque ID to MAC.

**Comment by cricalix** [comment]
I'll poke the config to see if I can switch it to MAC. Do you feel this issue is worth noting somewhere in the LXD documentation as "beware, potentially unwanted interaction" @stgraber ?

**Comment by stgraber** [comment]
Yeah, I think it'd make sense to add a note to the bridged and ovn docs that says that static DHCP assignments are dependent on the client using its MAC as identifier.

@ru-fu

**Comment by tomponline** [comment]
Did it also fail when using static allocations as well?

**Comment by stgraber** [comment]
I would expect it to but it'd be worth checking.

And I guess we should make the note a bit clearer by saying that MAC based DHCP identifier should be used so statically assigned leases may work properly and so copying an instance doesn't result in conflicting leases.

**Comment by cricalix** [comment]
> MAC based DHCP identifier should be used so statically assigned leases may work properly and so copying an instance doesn't result in conflicting leases

This makes me wonder a bit; in a `/etc/machine-id` based world, does copying the instance result in a new UUID in that file? (I saw an issue back in January related to this, but can't remember if it covered that.)

**Comment by cricalix** [comment]
I added the following to my profile templates:
```
  cloud-init.network-config: |
    version: 2
    ethernets:
      eth0:
        dhcp-identifier: mac
        dhcp4: true
```
It seems to cure the issue; the instances are not sending opaque IDs as the DHCP client identifier any more, and I cannot get an expired record to show up in dnsmasq's leases file by stopping a running instance.

This leaves dnsmasq as the arbiter of IP assignments (which is fine from my perspective) and name resolution.
