### ISSUE TITLE
Tutorial on how to build images

### ISSUE THREAD

**Issue by rrva** [lxc/lxd#1085]
I think a tutorial describing how build images from scratch is needed. This is not clear from the docs at all. What is evident is that I must provide a rootfs tarball of an already created system, but do I build one?

Best I got now was using the old scripts

    lxc-create --name fedora -t fedora
    tar -cvzf fedora-rootfs.tar.gz -C /var/lib/lxc/fedora/rootfs .

and then?

    lxc image import <other tarball created how?> <fedora-rootfs.tar.gz>

**Comment by stgraber** [comment]
The first tarball must contain at least a single metadata.yaml file, the content of which is described at https://github.com/lxc/lxd/blob/master/specs/image-handling.md

**Comment by stgraber** [comment]
We have a generic work item to better surface our specifications on our website, but the information is there, so I think this can be closed.
