### ISSUE TITLE
LXD 0.16 taking up 500Mb with no running containers

### ISSUE THREAD

**Issue by emilebosch** [lxc/lxd#1086]
Hi! 
I'm trying to work out why my LXD 0.16  takes up 500 mb doing nothing. I've used it quite extensively. And then after stopping all containers it takes about 580 mb.

I am using BTRFS, vagrant.

This is what i use to iterate over the processes:

```
 ps -eo size,pid,user,command --sort -size | awk '{ hr=$1/1024 ; printf("%13.2f Mb ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }'
```
Here's the list.

``` 
584.93 Mb /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log 
216.66 Mb /usr/lib/accountsservice/accounts-daemon 
216.53 Mb /usr/lib/policykit-1/polkitd --no-debug 
216.47 Mb /usr/sbin/rsyslogd -n 
212.25 Mb /usr/sbin/VBoxService 
112.97 Mb /usr/bin/ruby /usr/bin/puppet agent 
72.36 Mb /lib/systemd/systemd-timesyncd 
````

Any idea why or how? I am currently not running any containers. Is this normal?

**Comment by tych0** [comment]
Can you run the same tests again with --memprofile /tmp/mem and post the result? (There is a full example in /tests/profilling.sh for how to use memprofile)

**Comment by emilebosch** [comment]
Hi I will try to figure it out. I am just using a binary build not from source thing so this will take some time.

**Comment by stgraber** [comment]
What's the resident memory usage of that LXD?

The total memory footprint according to ps includes on-disk shared libraries and any other shared memory. The RSS is what's actually interesting and here it seems to be around 20MB for me.

    ps -eo rss,pid,user,command --sort -rss | awk '{ hr=$1/1024 ; printf("%13.2f Mb ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }'

**Comment by emilebosch** [comment]
Alright let me figure this out and come back to you guys soon.

**Comment by stgraber** [comment]
@emilebosch  Any update on this?

**Comment by emilebosch** [comment]
Hi stephan! Not yet, i will take some time soon to see if i can reproduce the issue and then check where the memory resides.

**Comment by stgraber** [comment]
@emilebosch  Still no news on this?

**Comment by stgraber** [comment]
I'm going to close this for now as there doesn't appear to be anything to do on our side. May re-open when you get around to getting updated numbers.
