### ISSUE TITLE
forkstart failure since upgrading to Ubuntu 22.04

### ISSUE THREAD

**Issue by mardy** [lxc/lxd#10867]
# Required information

[lxc-info.log](https://github.com/lxc/lxd/files/9464874/lxc-info.log)

# Issue description

Trying to start a container with [crossbuilder](https://github.com/ubports/crossbuilder) in Ubuntu 22.04. The same container worked fine a few days ago; I assume that what broke it was the upgrade from 20.04 that I did a couple of days ago, but it's only a guess.

# Steps to reproduce

1. git clone https://gitlab.com/ubports/development/core/address-book-app.git
2. cd address-book-app.git
3. git checkout ubports/xenial
4. crossbuilder --architecture=arm64

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [X] Container log (`lxc info NAME --show-log`): [container.log](https://github.com/lxc/lxd/files/9464890/container.log)
 - [X] Container configuration (`lxc config show NAME --expanded`): [container-conf.log](https://github.com/lxc/lxd/files/9464894/container-conf.log)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
Can you try this fix please https://discuss.linuxcontainers.org/t/help-help-help-cgroup2-related-issue-on-ubuntu-jammy/14705/4?u=tomp

**Comment by mardy** [comment]
> Can you try this fix please https://discuss.linuxcontainers.org/t/help-help-help-cgroup2-related-issue-on-ubuntu-jammy/14705/4?u=tomp

Indeed unmounting the `net_cls` cgroup fixes the issue, thanks! I'll try to figure out who mounts that cgroup V1 controller, then.

Feel free to close this issue, and thanks again! :-)

**Comment by tomponline** [comment]
Thanks!

If you do find it could you reply to @stgraber on https://discuss.linuxcontainers.org/t/help-help-help-cgroup2-related-issue-on-ubuntu-jammy/14705/7?u=tomp with what is setting it. Thanks
