### ISSUE TITLE
lxc-to-lxd doesn't understand LXC's "linux64" architecture

### ISSUE THREAD

**Issue by ru-fu** [lxc/lxd#10865]
When I create a LXC container and select "amd64" as architecture, the config file for the container contains:

    lxc.arch = linux64

When I then run the `lxc-to-lxd` tool, it gives the following error:

    Skipping container 'lxc-u1': Architecture isn't supported: linux64

I can get rid of that error by changing the architecture in the LXC container config file to either `amd64` or `x86_64`.

This seems to be the same issue as reported in https://github.com/lxc/lxd/issues/5829.

**Comment by stgraber** [comment]
@monstermunchkin can you fix this one please?
