### ISSUE TITLE
Setting ephmeral after copy or via config.

### ISSUE THREAD

**Issue by emilebosch** [lxc/lxd#1088]
Hi, i've made a base image and clone from that image for my pull request previews. However i wish them to delete themselves after they are shut down. However, since the base image isn't ephemeral the rest isn't either.

Is there a way to make a container ephemeral after a clone? I've tried setting it using config but to no avail. Maybe a `clone --ephemeral` would work? Or `config set <container> ephemeral true` might do the job?

**Comment by stgraber** [comment]
Hi,

Adding a --ephemeral flag to copy would be fine with me and should be pretty trivial to do.

As an alternative, you could just publish your base container as an actual image, which would then let you use it with launch and pass the ephemeral flag then.

    lxc publish basecontainer --alias base
    lxc launch base container-name --ephemeral
