### ISSUE TITLE
Architecture isn't supported: armv8l

### ISSUE THREAD

**Issue by gibmat** [lxc/lxd#10909]
LXD 5.0.0 has been uploaded to the Debian archive for the first time, and is hitting the various buildds. Builds for both the `armel` and `armhf` architectures compile fine, but several of the tests fail with the error "Architecture isn't supported: armv8l". For example,

```
=== RUN   TestIntegration_UnixSocket
    testing.go:37: 
        	Error Trace:	/<<PKGBUILDDIR>>/_build/src/github.com/lxc/lxd/lxd/testing.go:37
        	            				/<<PKGBUILDDIR>>/_build/src/github.com/lxc/lxd/lxd/daemon_integration_test.go:36
        	            				/<<PKGBUILDDIR>>/_build/src/github.com/lxc/lxd/lxd/daemon_integration_test.go:19
        	Error:      	Received unexpected error:
        	            	Architecture isn't supported: armv8l
        	Test:       	TestIntegration_UnixSocket
--- FAIL: TestIntegration_UnixSocket (0.00s)
```

It looks like the logic for testing supported platforms is in `shared/osarch/architectures.go`. I'm not super familiar with all the different ways arm architectures are identified, but given that LXD compiled and lots of other tests pass during each build, I hope it won't be too difficult extend the supported architecture matrix so the tests can be run on these two additional architectures.

I am working on uploading LXD 5.0.1, but I don't think that will have any affect on this issue.

Buildd logs:
https://buildd.debian.org/status/fetch.php?pkg=lxd&arch=armel&ver=5.0.0-1&stamp=1662903087&raw=0
https://buildd.debian.org/status/fetch.php?pkg=lxd&arch=armhf&ver=5.0.0-1&stamp=1662902755&raw=0

**Comment by stgraber** [comment]
Ah yeah, armv8l isn't really a normal architecture, it's the 32bit personally of some arm64 architectures.

We can likely fix it by adding it as an alias for armhf which is true enough.
