### ISSUE TITLE
lxc-to-lxd / lxd-benchmark: Building with "go get" deprecated

### ISSUE THREAD

**Issue by ru-fu** [lxc/lxd#10927]
With the current Go version, I cannot build `lxc-to-lxd` with `go get` anymore:

```
root@ubuntu-container:~# go get github.com/lxc/lxd/lxc-to-lxd
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

Can we provide another way for users to get the tool if they don't use the snap?

The same applies to the `lxd-benchmark` tool.

**Comment by tomponline** [comment]
Does "go install ..." work?

**Comment by monstermunchkin** [comment]
```
ubuntu@c1:~$ go install github.com/lxc/lxd/lxc-to-lxd@latest
go: github.com/lxc/lxd/lxc-to-lxd@latest (in github.com/lxc/lxd@v0.0.0-20220916193734-5938f747f646):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by ru-fu** [comment]
I think the issue is the building:

> In Go 1.18, go get will no longer build packages; it will only be used to add, update, or remove dependencies in go.mod. Specifically, go get will always act as if the -d flag were enabled.

https://go.dev/doc/go-get-install-deprecation

**Comment by monstermunchkin** [comment]
Can't we just make them Go modules?

**Comment by tomponline** [comment]
I think it could be this line

https://github.com/lxc/lxd/blob/master/go.mod#L5

**Comment by tomponline** [comment]
> I think the issue is the building:
> 
> > In Go 1.18, go get will no longer build packages; it will only be used to add, update, or remove dependencies in go.mod. Specifically, go get will always act as if the -d flag were enabled.
> 
> https://go.dev/doc/go-get-install-deprecation

Yes we need to use "go install" but I think that replace directive is causing issues (it has on other issues too).

**Comment by tomponline** [comment]
For now @ru-fu if you build lxd as normal from source you will get a lxc-to-lxd binary built too.
