### ISSUE TITLE
changing snap channels from candidate to stable prevents lxd from starting

### ISSUE THREAD

**Issue by VariableDeclared** [lxc/lxd#10937]
# Required information

 * Distribution: 22.04
 * Distribution version: 22.04.1
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-48-generic
   * LXC version: 5.5 (was 5.6)
   * LXD version: 5.5 (was 5.6)
   * Storage backend in use: default

# Issue description

When changing the lxd snap from latest/candidate to latest/stable lxc was no longer in a functioning state. lxd has the following logs in syslog: 
```
Sep 23 10:56:09 pjds-ubuntu lxd.daemon[51361]: Error: Failed to initialize global database: failed to ensure schema: schema version '66' is more recent than expected '65'
```

# Steps to reproduce

 1. Install latest/candidate
 2. Change the snap channel to latest/stable with snap refresh
 3. LXC should be in a non-functional state

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 
 - [x] Output of the client with --debug
```
➜  server20-iso git:(master) ✗ lxc list --all-projects --debug
DEBUG  [2022-09-23T11:04:58+01:00] Connecting to a local LXD over a Unix socket 
DEBUG  [2022-09-23T11:04:58+01:00] Sending request to LXD                        etag= method=GET url="http://unix.socket/1.0"
Error: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused
```
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

# Workaround

Refresh back onto the candidate channel

**Comment by stgraber** [comment]
LXD does not allow for downgrade.

Candidate currently contains 5.6, stable contains 5.5, so it's normal that this will not work.

**Comment by VariableDeclared** [comment]
Hi @stgraber how do I migrate back down to Stable to prevent breaking changes in future? I appreciate it doesnt allow for downgrade but I think this is a feature that people would need in cases where breaking changes occur.

**Comment by stgraber** [comment]
You need to wait until stable gets the same version of LXD as is currently in candidate, then you'll be able to refresh back to stable.

**Comment by VariableDeclared** [comment]
okay, thank you

**Comment by stgraber** [comment]
That should normally happen somewhere between Monday and Wednesday next week as that's when we normally push a new release to users.
