### ISSUE TITLE
Unable to add global remotes on snap version of lxd

### ISSUE THREAD

**Issue by MrDaGree** [lxc/lxd#10934]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-1075-kvm
   * LXC version: 5.0.1
   * LXD version: 5.0.1
   * Storage backend in use: btrfs
   * Snap Version: 5.0/stable

# Issue description

Unable to add global remotes to the host for all users to use that was implemented in [#7322](https://github.com/lxc/lxd/issues/7322) by following the [docs](https://linuxcontainers.org/lxd/docs/master/remotes/#global-per-system) page as well as utilizing the [release notes](https://discuss.linuxcontainers.org/t/lxd-4-13-has-been-released/10737) for snap specific directory.

While following these directions I was unable to see any remotes listed in `lxc remote list` that were added in the `config.yml` in the numerous directories tried.

Directories tried:
* `/etc/lxc`
* `/etc/lxd`
* `/var/snap/lxd/common`

Each directory tried had the sub-folder of `servercerts` that contained the `*.crt` file that had a name that matched the entry in the `config.yml`

# Steps to reproduce

 1. Install LXD via snap
 2. Create `config.yml` based off [documentation](https://linuxcontainers.org/lxd/docs/master/remotes/#global-per-system) in any of the 3 folders listed above
 3. run `lxc remote list` to see no newly added remotes
 4. repeat steps 2 & 3 for the directories mentioned above along with making sure the `*.crt` files exist in `servercerts` under the folders tried

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Try `/var/snap/lxd/common/global-conf/`

**Comment by MrDaGree** [comment]
> Try `/var/snap/lxd/common/global-conf/`

That worked perfectly! 

I created a [MR](https://github.com/lxc/lxd/pull/10935) for adding it to the docs page to help avoid confusion for the next person that needs to use this
