### ISSUE TITLE
lxd-generate: Supporting more handwritten queries

### ISSUE THREAD

**Issue by masnax** [lxc/lxd#10944]
## Background
Considering the comments in #10936, and @markylaing's request for using `lxd-generate` to create some basic boilerplate functions that we can just pass our own statements to, I've been thinking about how we can improve the `GetMany` functions produced by `lxd-generate`. 

In my opinion, the `GetMany` functions should do two things:
* Reduce the amount of virtually identical code we have to duplicate by hand (copy/pasting a function and changing type/field names). 
* Prevent us from making unexpected queries by labelling arguments with the `EntityFilter`s, and only executing the appropriate query for the non-nil fields.

I didn't want to generate a function that just takes `args ...any`, as that has no validation. Writing handwritten functions with `Filter` structs is tedious, however. So it would be nice if we could parse more types of handwritten queries and generate functions for them.

## Current Behavior
Currently, `lxd-generate` can support some handwritten queries, if we don't generate one with the same name:
```go
var <entity>Objects = RegisterStmt(`SELECT...`)
```

This will get used in the `Get<Entities>` function, and any `lxd-generate` directives of the form `objects-by-Field1-And-Field2` for that entity will also append a `WHERE` clause to that original query as a new variable. 

This has 2 pitfalls in practice:
* Naming collisions: 
  * We only accept 1 query for each filter. If two queries can use the same filter, the second one needs its own function.
* Additional parameters not in the `Filter` structs: 
  * If, maybe because of a `JOIN`, we need more arguments, we need a new function that can take those arguments.

 ## Proposed Changes
Change the naming structure for parsed statements to be more complex, and generate more functions with the`lxd-generate` `GetMany` directive based on all statements with that naming scheme for the entity.

The variable naming scheme would be as follows:
```go
var <entity>Objects<Label>With<Arg...>By<Filter...> = RegisterStmt(`SELECT...`)
```
`lxd-generate` would detect a variable of this name and produce a function of the form 
```go
func GetEntities<Label>With<Arg>(ctx, tx, arg1, filter) 
```

So that's a lot of hard to read placeholders, I'll define them and then give some examples:
* `<Label>` -- This is a unique description that scopes a function and its queries, so we can have multiple statements with the same filter combinations.

* `With<Arg...>` -- The `And`-separated `Arg`s will be added as arguments to the resulting `lxd-generate` function. Anything with the suffix `Name`, `UUID`, or `Fingerprint` will be a string, and `ID` would be an int. Everything else would be rejected.

## Examples
Using `Certificate` as the entity, here are some examples. All the functions associated to each example are created at the same time with a single invocation of `GetMany`. Also, there would be no changes to the current generated functions.

This is an example using a `<Label>` but no extra arguments:
```go
  // A handwritten statement fetching all the certificates that belong to a project.
  var certificateObjectsInAnyProject = RegisterStmt(`
  SELECT * FROM certificates
    JOIN certificates_projects ON certificate.id = certificates_projects.certificate_id
  `)

  // `InAnyProject` is used both in the function name, and all considered statements.
  func GetCertificatesInAnyProject(ctx, tx, filters ...CertificateFilter) ([]Certificate, error)
```

This is an example with a single extra argument (`With<Arg...>`), but no `<Label>`:
```go
  // A handwritten statement fetching all the certificates matching the project and fingerprint.
  var certificateObjectsWithProjectIDByFingerprint = RegisterStmt(`
  SELECT * FROM certificates
    JOIN certificates_projects ON certificate.id = certificates_projects.certificate_id
    WHERE ( certificate_projects.project_id = ? AND certificates.fingerprint = ? )
  `)

  // This function is suffixed with `WithProjectID`, and and uses `projectID` in the query parameters.
  func GetCertificatesWithProjectID(ctx, tx, projectID int, filters ...CertificateFilter) ([]Certificate, error)
```

This example uses every option. There is a `<Label>`, an extra arg, and a filter:
```go
  // A handwritten statement fetching all the server type certificates matching the project and fingerprint.
  var certificateObjectsOfTypeServerWithProjectIDByFingerprint = RegisterStmt(`
  SELECT * FROM certificates
    JOIN certificates_projects ON certificate.id = certificates_projects.certificate_id
    WHERE ( certificate_projects.project_id = ? AND certificates.type = 2 AND certificates.fingerprint = ? )
  `)

  // This function is similar to the above example, 
  // but like the `InAnyProject` example, all statements it considers must have the same label.
  func GetCertificatesOfTypeServerWithProjectID(ctx, tx, projectID int, filters ...CertificateFilter) ([]Certificate, error)
```

**Comment by masnax** [comment]
@tomponline @markylaing @stgraber If any of you have some opinions on this, I would appreciate it!

There's also a draft PR #10946 that shows how this would work in practice using the `Certificate` struct. `certificates.go` and `certificates.mapper.go` have all the relevant changes.

**Comment by tomponline** [comment]
@masnax thanks I'll take a look at this ASAP

**Comment by tomponline** [comment]
> ```go
>   // A handwritten statement fetching all the certificates matching the project and fingerprint.
>   var certificateObjectsWithProjectIDByFingerprint = RegisterStmt(`
>   SELECT * FROM certificates
>     JOIN certificates_projects ON certificate.id = certificates_projects.certificate_id
>     WHERE ( certificate_projects.project_id = ? AND certificates.fingerprint = ? )
>   `)
> 
>   // This function is suffixed with `WithProjectID`, and and uses `projectID` in the query parameters.
>   func GetCertificatesWithProjectID(ctx, tx, projectID int, filters ...CertificateFilter) ([]Certificate, error)
> ```

This 2nd example lost me a bit. I couldn't figure out where the `AND certificates.fingerprint = ?` argument would come from?
I figured the `projectID int` would be passed to the query as the first argument, and then the filters would be added afterwards, but I couldn't figure out where the certificates.fingerprint would be added?

**Comment by masnax** [comment]
> ```go
> ```go
>   // A handwritten statement fetching all the certificates matching the project and fingerprint.
>   var certificateObjectsWithProjectIDByFingerprint = RegisterStmt(`
>   SELECT * FROM certificates
>     JOIN certificates_projects ON certificate.id = certificates_projects.certificate_id
>     WHERE ( certificate_projects.project_id = ? AND certificates.fingerprint = ? )
>   `)
> 
>   // This function is suffixed with `WithProjectID`, and and uses `projectID` in the query parameters.
>   func GetCertificatesWithProjectID(ctx, tx, projectID int, filters ...CertificateFilter) ([]Certificate, error)
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> This 2nd example lost me a bit. I couldn't figure out where the AND certificates.fingerprint = ? argument would come from?
> I figured the projectID int would be passed to the query as the first argument, and then the filters would be added afterwards, but I couldn't figure out where the certificates.fingerprint would be added?
> ```

That's just part of the filter struct. That particular statement will only execute if `filter.Fingerprint` is not nil. The args passed to the query would be `[]any{projectID, filter.Fingerprint}`.

**Comment by tomponline** [comment]
> That particular statement will only execute if `filter.Fingerprint` is not nil.

So I would have to define my custom SQL statements for every possible combination of the filters?

**Comment by masnax** [comment]
> An additional thing I've often wondered about the DB generator (given its aim is to reduce manually written boiler plate code) is why do we need to write define every statement that could be needed by the `Get<Entity>(ctx, tx, filters... <Entity>Filter) []<Entity>` functions?
> 
> If we take `instances` as an example, there are many statement lines required to support all of the filter scenarios that could be used:
> 
> ```
> //go:generate mapper stmt -e instance objects
> //go:generate mapper stmt -e instance objects-by-ID
> //go:generate mapper stmt -e instance objects-by-Project
> //go:generate mapper stmt -e instance objects-by-Project-and-Type
> //go:generate mapper stmt -e instance objects-by-Project-and-Type-and-Node
> //go:generate mapper stmt -e instance objects-by-Project-and-Type-and-Node-and-Name
> //go:generate mapper stmt -e instance objects-by-Project-and-Type-and-Name
> //go:generate mapper stmt -e instance objects-by-Project-and-Name
> //go:generate mapper stmt -e instance objects-by-Project-and-Name-and-Node
> //go:generate mapper stmt -e instance objects-by-Project-and-Node
> //go:generate mapper stmt -e instance objects-by-Type
> //go:generate mapper stmt -e instance objects-by-Type-and-Name
> //go:generate mapper stmt -e instance objects-by-Type-and-Name-and-Node
> //go:generate mapper stmt -e instance objects-by-Type-and-Node
> //go:generate mapper stmt -e instance objects-by-Node
> //go:generate mapper stmt -e instance objects-by-Node-and-Name
> //go:generate mapper stmt -e instance objects-by-Name
> ```
> 
> This is left to the developer to write (and likely miss a combination).
> 
> Could we instead use the metadata on the entity return type to generate these statements automatically, so I just have to add:
> 
> ```
> //go:generate mapper method -i -e instance GetMany references=Config,Device
> ```
> 
> And from that the necessary statements are generated?

I actually recall suggesting this behaviour early on, but we decided against it, as we would have to produce queries for every possible filter combination of nil and non-nil fields, and some dont always make sense. (Like getting instances by project and type). 

So instead we decided to use the `-by-` declarations to specify exactly which combinations of filter fields we will actually consider, or error out.

**Comment by masnax** [comment]
> > That particular statement will only execute if `filter.Fingerprint` is not nil.
> 
> So I would have to define my custom SQL statements for every possible combination of the filters?

No, `lxd-generate` is capable of parsing the non-filtered statement to produce filtered ones. So you would write `certificateObjectsWithProjectID` and then a generator comment with `objects-by-Fingerprint` would generate a new statement using your custom statement, but add a filter in the WHERE clause. 

You would only have to define "irregular" statements, and the non-filtered one.

**Comment by tomponline** [comment]
> No, `lxd-generate` is capable of parsing the non-filtered statement to produce filtered ones. So you would write `certificateObjectsWithProjectID` and then a generator comment with `objects-by-Fingerprint` would generate a new statement using your custom statement, but add a filter in the WHERE clause.
> 
> You would only have to define "irregular" statements, and the non-filtered one.

Interesting. So this would be a dynamic query directly executed and not using a prepared statement (only the SQL from the static definition)? 

As an aside, can you confirm that in that scenario we don't prepare a single custom query, execute it and then throw away the prepared statement?

I'm thinking:

1. We could use the ability you describe that generates adhoc filtering from the base query to fulfil queries for filter combinations that haven't been explicitly defined.
2. This would then mean we would only need to static define the ones where we want to gain the performance benefit of having them prepared up front (those that are hit frequently).

And then back to the topic in hand:

If we have the ability to generate filter queries adhoc based on the table info stored in the returned entity type, then could we add the ability to generate that SQL as a separate function for a specified entity type that took the filters and a pointer to a strings.Builder, and populated it with the WHERE statements?

We could then use this in custom functions to add filtering support by writing the initial query by hand inside the custom function and then passing the strings.Builder to this generated function to add the additional WHERE statements based on the filters provided (if any).

This would avoid needing to define any queries up front.

**Comment by masnax** [comment]
> > No, `lxd-generate` is capable of parsing the non-filtered statement to produce filtered ones. So you would write `certificateObjectsWithProjectID` and then a generator comment with `objects-by-Fingerprint` would generate a new statement using your custom statement, but add a filter in the WHERE clause.
> > You would only have to define "irregular" statements, and the non-filtered one.
> 
> Interesting. So this would be a dynamic query directly executed and not using a prepared statement (only the SQL from the static definition)?
> 
> As an aside, can you confirm that in that scenario we don't prepare a single custom query, execute it and then throw away the prepared statement?

Not quite, we actually create a whole new prepared statement from the original query. The dynamic queries are only used when there's multiple filter structs.

So lets say we have `certificateObjects` (generated) and `certificateObjectsWithProjectID` (handwritten).

The `objects-by-<FIELD>` generator comments parse the syntax tree for any variable defined as a call to `RegisterStmt`, whose name has the prefix `certificateObjects` and no `By...` suffix. `lxd-generate` then writes new variables that do have a `By...` suffix for the given `<FIELD>`. 

So for `objects-by-Fingerprint`, on the `certificate` entity, we will generate new global variables `certificateObjectsByFingerprint` and `certificateObjectsWithProjectIDByFingerprint`, which are prepared statements. 

> I'm thinking:
> 
>     1. We could use the ability you describe that generates adhoc filtering from the base query to fulfil queries for filter combinations that haven't been explicitly defined.
> 
>     2. This would then mean we would only need to static define the ones where we want to gain the performance benefit of having them prepared up front (those that are hit frequently).
> 
> 
> And then back to the topic in hand:
> 
> If we have the ability to generate filter queries adhoc based on the table info stored in the returned entity type, then could we add the ability to generate that SQL as a separate function for a specified entity type that took the filters and a pointer to a strings.Builder, and populated it with the WHERE statements?
> 
> We could then use this in custom functions to add filtering support by writing the initial query by hand inside the custom function and then passing the strings.Builder to this generated function to add the additional WHERE statements based on the filters provided (if any).
> 
> This would avoid needing to define any queries up front.

This would certainly be possible, but we would lose the performance benefit of the prepared statements.

**Comment by markylaing** [comment]
I have a feeling that we could make the generated code more flexible without needing such a large change or complicating the generator any further.

If any of the handwritten statements are grossly incorrect, lxd/lxd-cloud/microcloud etc will fail to start and will fail all tests, so we'll never ship anything completely broken.

The existing `GetMany` with multiple filters works in > 90% of situations, I've only needed to write custom queries in a few cases:
1. Where we need a `JOIN` instead of a `LEFT JOIN` to ensure a value is not null.
2. To join on an association table.
3. Where we need an OR clause in an update or delete statement.

#### Cases 1 & 2 (SELECT statements)
I think the main thing we are likely to miss is if a column is added to a table and a new field is added to the database representation type. Handwritten statements will then become out of date and omit that column, and the `rowFunc` that is passed into `query.SelectObjects` will omit that field.

I think we can get around this by a) generating a string `<typeName>Columns` for use in handwritten statements containing the columns we need to select fully populate the type, and b) generating an unexported function `select<typename>Objects(ctx context.Context, tx *sql.Tx, stmt int, args any...) ([]<type>, error)` for internal use. We would then write a statement like this:

```golang
var getCustom<typeName>Objects = RegisterStmt(fmt.Sprintf("SELECT %s FROM <tableName> WHERE ...", <typeName>Columns))
```
and we would also write a function like this:
```golang
func GetCustom<typeName>s (ctx, tx, <concretely defined arguments>) ([]<type>, error) {
    return select<typeName>Objects(ctx, tx, <pass arguments directly>)
}
```

This way, the `rowFunc` will be kept up to date via the generated generic method, and we will always select all of the columns necessary to populate the type. If a column is added that requires a join and the handwritten statement does not already join that table, the handwritten statement will fail to prepare until it has been updated.

#### Case 3 (UPDATE / DELETE statements)
The boilerplate here is already quite minimal so I don't think we need to make any changes to handle this case.

--------------------

With all that being said, my experience using the generator has been primarily with LXD Cloud and if this change will benefit generation elsewhere I'm not opposed to it. If this is the case, my only concern is with the argument specification for custom queries. The proposal has

>So that's a lot of hard to read placeholders, I'll define them and then give some examples:
>
> `<Label>` -- This is a unique description that scopes a function and its queries, so we can have multiple statements with the same filter combinations.
>
>`With<Arg...>` -- The And-separated Args will be added as arguments to the resulting lxd-generate function. Anything with the suffix Name, UUID, or Fingerprint will be a string, and ID would be an int. Everything else would be rejected.

In LXD Cloud we have types like `ClusterState`, so to use that in the generated function we'd need to write `WithClusterStateID` and then cast the `ClusterState` to an int when calling the generated function which doesn't seem quite right. That being said, I'm not sure there is a way of fully specifying the type using just the name of the registered statement variable.

**Comment by tomponline** [comment]
> I think we can get around this by a) generating a string `<typeName>Columns` for use in handwritten statements containing the columns we need to select fully populate the type, and b) generating an unexported function `select<typename>Objects(ctx context.Context, tx *sql.Tx, stmt int, args any...) ([]<type>, error)` for internal use.

I like this idea. As that could be used as part of a custom select statement.

Although I think we should get away from requiring these custom queries to be per-registered as statements. 

As this is by definition a custom scenario, we don't know how frequently its going to be called, and I wouldn't want us to end up registering every possible custom query in the database on all cluster members.

Additionally, when using filtering there's a good possibility the pre-registered query isn't going to be used anyway.

Having generated helper functions that custom handwritten functions can use to simplify SELECTing the right columns and generating WHERE statements from the provided filters would be useful, and then that can be passed to the traditional query functions we use.

And in cases where this custom function is restrictive enough and called frequently enough to justify pre-registering it, then this can still be done after the SQL is generated.

**Comment by markylaing** [comment]
> As this is by definition a custom scenario, we don't know how frequently its going to be called, and I wouldn't want us to end up registering every possible custom query in the database on all cluster members.

How costly are prepared statements? I don't think we need to prepare statements for single usage but all the statements I've been writing are for use either in API calls or in response to downstream events. In any case, I think a major benefit of using prepared statements is that they will cause tests to fail if any queries are invalid. So I'd be in favour of using them wherever possible until there is a significant performance cost.

**Comment by markylaing** [comment]
> I don't think we need to prepare statements for single usage but all the statements I've been writing are for use either in API calls or in response to downstream events.

Just to add to this. I wouldn't really call the queries "custom", they are just standard queries that need to be handwritten because they can't be easily generated.

**Comment by tomponline** [comment]
Sure you can use prepared statements where you feel its worth it. My point being for custom queries we shouldn't *force* it (by having the generator only support using the helpers with prepared statements). Especially seeing as the DB generator already is using dynamic queries when some filtering combinations are used.


> Just to add to this. I wouldn't really call the queries "custom", they are just standard queries that need to be handwritten because they can't be easily generated.

Thats my definition of custom :)

**Comment by markylaing** [comment]
Ahh ok I get your meaning now, thanks.

**Comment by tomponline** [comment]
Thanks. It may be a tangent, but I would value being able to get this straightened out in my head as to specifically what the DB generator requires/does.

I'm still not quite following, you're saying its a non issue because it can generate prepared statements automatically from the base statement if a required query is needed, but at the same time your saying that it doesn't generate all prepared statements it may possible need due for all the filter combinations.

As someone who is not familiar with that part of the code base that feels a bit counter intuitive. 
Both approaches make sense for different reasons, but I am struggling to understand how/when it does both. :)

**Comment by tomponline** [comment]
Also I don't feel its too much of a tangent as we were originally talking about modifying the generator to aid in handwritten queries.
If those handwritten queries are dynamically generated at run time (so handwritten logic that generates the query based on some input) then if the solution we come up requires prepared statements to be defined at generation time to work then it won't be useful in those scenarios.

**Comment by masnax** [comment]
As for making prepared statements optional, currently that behaviour is from parsing variable names of the form `<entity>Objects...` in the current package. We don't actually care if they're a call to `RegisterStmt`, but we can detect that. If we find that the variable just points to a string, rather than a `RegisterStmt` call, we can have the produced `GetMany` function properly handle it like a query string.

**Comment by tomponline** [comment]
But they do need to exist at generate time though? Right?

**Comment by masnax** [comment]
Can you give me an example of such a run-time query?

**Comment by masnax** [comment]
> Great examples thank you!
> 
> Straight away what caught my eye in the first example is, as a developer, how would I know to produce a SQL statement named using `certificateObjectsWithProjectID`? As the `// go:generate` lines don't mention ProjectID at all.
> 
> Would including the var name to use in the `// go:generate` line make things more clearer to someone who doesn't know the internal name mapping (I'm assuming the WithProjectID part is somehow derived from the properties on the certificates struct type).

The whole point of `certificateObjectsWithProjectID` is that it requires a parameter `projectID` which isn't part of the struct-table mapping, and so `lxd-generate` can't pick it up.

Rather, `lxd-generate` is just picking up that we have a variable defined of the form
```go
var <entity>Objects<Suffix> = RegisterStmt(...)
```

We would then have a set of possible suffixes, separated by keywords `With` and `By`:
* Immediately after `<entity>Objects`, we can specify any descriptive text, which will be suffixed to all generated statements and methods based on the base query, so that we can have multiple queries using the same combination of filters.
* Next, prefixed with `With`, is additional arguments like `projectID`, which will become a parameter on the `GetMany` function.
* Next, prefixed with `By` are any filters.

**Comment by tomponline** [comment]
> Can you give me an example of such a run-time query?

Certainly. Say I want to load all instances using a custom filter (perhaps a series of instance IDs from a previous query extracted based on a different table, perhaps all instances with a device connected to a particular network - something that isn't possible from a join because it needs to have profiles applied), but I also want to combine that filter with the existing filter sets we support for instances.

This presents me with 2 problems:

1. I would have to implement all of the filter sets logic to generate the WHERE statements - and that risks me introducing a bug where I miss fields (especially ones added in the future).
2. I would have to select all of the fields needed, which would mean maintaining that list of fields in multiple places (this is @markylaing point above).

It would be great if the DB generator would provide me a function I can use to generate WHERE statements from filters for an entity type, and to generate the column names for the SELECT part for an entity type.

**Comment by masnax** [comment]
Having generated helpers for columns and WHERE statements is something we can definitely do, but I don't see the connection with lxd-generate being unable to find the queries before run-time.

Since these helpers are defined from `lxd-generate`, they would exist before the new query we're making. If we just add some other function than `RegisterStmt`:

```go
// Use lxd-generate to produce these 2 helpers:
func certificateColumns() string // gets the columns for the `certificates` table.
func certificateFilterFingerprintAndName() string // gets a filter including `fingerprint` and `name`

// Then we would define this ourselves.
var certificateObjectsCustom = CustomStmt(SQL, certificateColumns(), certificateFilterFingerprintAndName())
```

And `lxd-generate` would pick up `certificateObjectsCustom` as a complete query.

**Comment by tomponline** [comment]
> ```go
> var certificateObjectsCustom = CustomStmt(SQL, certificateColumns(), certificateFilterFingerprintAndName())
> ```

The SQL var wouldn't be known until later though.

**Comment by tomponline** [comment]
"By directly invoking objects-by-FIELD, we ensure we only produce the statements we are actually going to use."

What happens if a filter combination is passed to GetMany at tun time that wasnt defined up front as a prepared statement?

**Comment by tomponline** [comment]
> You would still have to create your own set of filter structs to pass to the `certificateFilters` helper, which means you're still going through the whole process of considering which filters to use, and could miss some.

This can happen now so not really relevant. But what I dont want to have is a situation where a filter field supplied is ignored.

**Comment by tomponline** [comment]
> This actually still confuses me a bit though. Wouldn't the `SQL` var just be something like
> 
> ```sql
> SELECT %s
> FROM <table>
> JOIN <other table>
> JOIN <other table>
> JOIN <other table>
> WHERE %s
> ```
> 
> where the `%s` would be replaced with the outputs of the column and filter helpers, respectively?

My thinking is this would allow us to create a function that accepts custom filters and then layers on additional custom ones not supported by the filter framework, but not known about at build time. It would also allow us to do custom joins too, which was one of the other requirements. This dynamic SQL could then just be run.

And as you rightly say all of these scenarios are somewhat unusual and infrequent that hopefully if we just get the generator to build functions to return field names and where statements then we get plenty of flexibility for these edge cases without having to extend the db generator much and still have the safety net that as entity fields and filter fields change over time these custom functions keep working.

**Comment by masnax** [comment]
> "By directly invoking objects-by-FIELD, we ensure we only produce the statements we are actually going to use."
> 
> What happens if a filter combination is passed to GetMany at run time that wasnt defined up front as a prepared statement?

The last block of the filter nil/non-nil checks is
```go
    } else {
      return nil, fmt.Errorf("No statement exists for the given Filter")
    }
``` 

>My thinking is this would allow us to create a function that accepts custom filters and then layers on additional custom ones (by appending to the SQL string) not supported by the filter framework (for example negated comparison or quantity), but not known about at build time. It would also allow us to do custom joins too, which was one of the other requirements. This dynamic SQL could then just be run.
>
>And as you rightly say all of these scenarios are somewhat unusual and infrequent that hopefully if we just get the generator to build functions to return field names and where statements then we get plenty of flexibility for these edge cases without having to extend the db generator much and still have the safety net that as entity fields and filter fields change over time these custom functions keep working.

I'm not so sure about this. Do you think it's wise to obfuscate our queries behind a bunch of `go` functions such that if we ever wanted to figure out what any of these queries are doing, we would have to manually do filter arithmetic, or put a bunch of print statements right before we perform the query? Right now this is already happening with the multiple filter structs and I feel it's caused enough confusion that we barely use that feature, and that just appends an existing `WHERE` clause to another query. Supporting negated comparison or other alternate filter behaviour would require some painful string manipulation of the `WHERE` clause produced by the `<entity>Filters()` function. 

Additionally we would still need a way to "sync" the parameters in the resulting query to the args passed to the function that actually executes the query. How would we verify that the parameters and args are all in the right place if we're manipulating the string produced from the `<entity>Filters()` function? And what about additional parameters, how would the resulting function know that these statements require extra parameters that are not part of the filter struct?

I'm fine with including this functionality into lxd-generate, but I'm not sure if it should be a pattern that we should encourage. And if we want to support both implementations, we would need two `GetMany` functions for each of the different query implementations, which is also not ideal.

**Comment by tomponline** [comment]
Let's jump on a call tomorrow if around as I'm not getting across what I mean. I dont want to extend the filter framework, that was not my meaning. So something is getting lost here.

**Comment by tomponline** [comment]
> The last block of the filter nil/non-nil checks is

Ok that helps me understand the current situation. Thanks

**Comment by markylaing** [comment]
For now, the plan is:
1. Generate a function for dynamically getting the column names from a struct. e.g.
```go
type Thing struct {
    ID int
    Name string
    Stuff string
    Custom_fieldName string `db:"sql=things.attribute"` // Specify column names
}

// Not exported, we should write all custom queries inside the database package
func thingColumns() string {
    return "things.id, things.name, things.stuff, things.attribute"
}

// Also generate function like below whose row func matches with thingColumns()
func getThings(ctx, tx, stmt, args ...any) { ... }
```
2. It is expected that the user will write the SQL statements, register them, and will also write the exported function which calls `getThings` and concretely types the arguments in the correct order. Ideally, we want all custom queries to live in the same package as the `RegisterStmt` function, it would be good to move networks and storage in LXD to follow this model.


If in future we find that we need filtering on custom statements, we know it's possible...  if the statement does not already contain a WHERE clause we can do it without any conflicts, if it does contain a where clause things get very tricky....

**Comment by tomponline** [comment]
LGTM! thanks
