### ISSUE TITLE
Allow proxy devices to be added on the fly for VMs

### ISSUE THREAD

**Issue by maran** [lxc/lxd#10940]
It appears right now it's not possible to add a proxy device to a running VM: `Device cannot be added when instance is running.`

It seems that applying it live could be done. I am willing to submit a PR; would it be as easy as implementing CanHotPlug() to always return true on proxies?

**Comment by bakhtiar56** [comment]
Hello, I am a coming from hacktoberfest. I am a beginner in contributing to open source. Is this an issue where I can contribute? Thank you

**Comment by tomponline** [comment]
@bakhtiar56 assigned to you, thanks!

**Comment by tomponline** [comment]
Take a look at https://github.com/lxc/lxd/blob/master/lxd/device/proxy.go and https://linuxcontainers.org/lxd/docs/master/installing/#installing-lxd-from-source

**Comment by bakhtiar56** [comment]
I understand somewhat that once the instance is running, we have to again call the runConfig function. I am sorry but I am not very proficient in OS programming. It would be helpful if you could guide me how to accomplish my task? Again, I apologize. Its just that I am very enthusiastic about my first open-source contribution but have limited understanding of intensive OS programming. I have only taken 1 OS course in my college.
