### ISSUE TITLE
After bind mount /var/snap/lxd container won't start. Error: Daemon failed to setup shared mounts base. Does security.nesting need to be turned on?

### ISSUE THREAD

**Issue by geekstuff99** [lxc/lxd#10971]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version:  5.15.0-48-generic
   * LXC version: 5.6
   * LXD version: 5.6
   * Storage backend in use: dir

# Issue description

After bind mount the `/var/snap/lxd` -> `/media/disk2/lxd`, 
Then I installed the **lxd** with command `sudo snap install lxd`
Completed the _lxd init_ setup, then created the container.
Now i can stop and start container. Every thing works fine up to here.

After restarting,  I manually mounted /media/disk2 ( _fstab_ auto mount was disabled and i required it so).
and restarted lxd snap deamon with `sudo snap restart lxd` 
Now i can list the containers with l`xc list`
But I can not start container with `lxc start c1` --> c1 is container name.
Getting this message.
`Error: Daemon failed to setup shared mounts base. Does security.nesting need to be turned on?`

# My requirement 
The `/var/snap/lxd` should not be in OS partition, and should be on different disk for some reason.
I tried symbolic link also, but not works. 
Please suggest me, if any better alternative available.

 
# Steps to reproduce

 1. `sudo mount -o defaults,noatime,nodiratime /dev/mapper/disk2   /media/disk2`
 2. `sudo mkdir /media/disk2/lxd`
 3. `sudo mkdir /var/snap/lxd`
 4. `sudo mount --bind /media/disk2/lxd   /var/snap/lxd`
 5. `sudo snap install lxd`
 6. `lxd init`
 7. `lxc image import c1.tar.gz --alias c1`
 8. `lxc launch c1 c1`
 9. `lxc list` , `lxc stop c1` , `lxc start c1`, `lxc shell c1` --> all commands are works fine here.
 10. After restart, I manually mounting the partition as per _step:1_, and done bind mount as in _step:4_
 11. Now restarting the lxd daemon with `sudo snap restart lxd`
 12. Some times `lxc list` fails, and getting error message :` Error: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused.`  Then I have manged with `sudo rmdir /var/snap/lxd/common/var/lib/lxcfs`. (don't know better alternative). Now `lxc list` listing containers.
 13. But container remain in STOPPED status. While issuing `lxc start c1` getting this message, `Error: Daemon failed to setup shared mounts base. Does security.nesting need to be turned on?`. Unable to fix this issue.

Kindly help.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`): 
 audit: type=1400 audit(1664455783.032:633): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="lxd_dnsmasq-lxdbr0_</var/snap/lxd/common/lxd>" pid=22487 comm="apparmor_parser"

 - [ ] Container log (`lxc info c1 --show-log`): 
      Name: c1
      Status: STOPPED
      Type: container
      Architecture: x86_64
      Created: 2022/09/29 15:38 IST
      Last Used: 2022/09/29 15:41 IST
      
      Log:
      
      lxc c1 20220929101118.534 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
      lxc c1 20220929101118.534 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
      lxc c1 20220929101118.535 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
      lxc c1 20220929101118.535 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
      lxc c1 20220929101205.297 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
      lxc c1 20220929101205.297 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing

 - [ ] Container configuration (`lxc config show c1 --expanded`):
      architecture: x86_64
      config:
        image.architecture: x86_64
        image.description: Ubuntu 22.04 LTS server (20220923)
        image.os: ubuntu
        image.release: jammy
        volatile.base_image: 27eb19fd23cfc1eef01422736adef7672bb67a00613c14705f0238db5de04dbb
        volatile.cloud-init.instance-id: 1405ff53-1c49-4e86-80d1-0b97c8567b10
        volatile.eth0.hwaddr: 00:16:3e:ef:f7:21
        volatile.idmap.base: "0"
        volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
        volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
        volatile.last_state.idmap: '[]'
        volatile.last_state.power: RUNNING
        volatile.uuid: 4b6955c6-2658-4a9b-809e-370bf26fe1d5
      devices:
        eth0:
          name: eth0
          network: lxdbr0
          type: nic
        root:
          path: /
          pool: default
          type: disk
      ephemeral: false
      profiles:
      - default
      stateful: false
      description: ""

 - [ ] Main daemon log (at  /var/snap/lxd/common/lxd/logs/lxd.log):
         time="2022-09-29T16:29:57+05:30" level=warning msg=" - Couldn't find the CGroup network priority controller, network priority will be ignored"
        time="2022-09-29T16:29:57+05:30" level=warning msg="Failed setting up shared mounts" err="no such file or directory"
        time="2022-09-29T16:29:58+05:30" level=error msg="Failed initializing network" err="Failed starting: The DNS and DHCP service exited prematurely: Process exited with non-zero value 2 (\"dnsmasq: failed to create listening socket for 10.1.1.1: Address already in use\")" network=lxdbr0 project=default
        time="2022-09-29T16:29:58+05:30" level=warning msg="Failed auto start instance attempt" attempt=1 err="Daemon failed to setup shared mounts base. Does security.nesting need to be turned on?" instance=c1 maxAttempts=3 project=default
        time="2022-09-29T16:30:03+05:30" level=warning msg="Failed auto start instance attempt" attempt=2 err="Daemon failed to setup shared mounts base. Does security.nesting need to be turned on?" instance=c1 maxAttempts=3 project=default
        time="2022-09-29T16:30:08+05:30" level=warning msg="Failed auto start instance attempt" attempt=3 err="Daemon failed to setup shared mounts base. Does security.nesting need to be turned on?" instance=c1 maxAttempts=3 project=default
        time="2022-09-29T16:30:08+05:30" level=error msg="Failed to auto start instance" err="Daemon failed to setup shared mounts base. Does security.nesting need to be turned on?" instance=c1 project=default
        time="2022-09-29T16:30:58+05:30" level=error msg="Failed initializing network" err="Failed starting: The DNS and DHCP service exited prematurely: Process exited with non-zero value 2 (\"dnsmasq: failed to create listening socket for 10.1.1.1: Address already in use\")" network=lxdbr0 project=default
        time="2022-09-29T16:31:58+05:30" level=error msg="Failed initializing network" err="Failed starting: The DNS and DHCP service exited prematurely: Process exited with non-zero value 2 (\"dnsmasq: failed to create listening socket for 10.1.1.1: Address already in use\")" network=lxdbr0 project=default
        time="2022-09-29T16:32:59+05:30" level=error msg="Failed initializing network" err="Failed starting: The DNS and DHCP service exited prematurely: Process exited with non-zero value 2 (\"dnsmasq: failed to create listening socket for 10.1.1.1: Address already in use\")" network=lxdbr0 project=default

 - [ ] Output of the client with `lxc start c1 --debug`
        DEBUG  [2022-09-29T18:31:50+05:30] Sending request to LXD                        etag= method=GET url="http://unix.socket/1.0/operations/b9285b7b-5265-4989-a404-77e6c327beb6"
        DEBUG  [2022-09-29T18:31:50+05:30] Got response struct from LXD                 
        DEBUG  [2022-09-29T18:31:50+05:30] 
                {
                        "id": "b9285b7b-5265-4989-a404-77e6c327beb6",
                        "class": "task",
                        "description": "Starting instance",
                        "created_at": "2022-09-29T18:31:50.748966525+05:30",
                        "updated_at": "2022-09-29T18:31:50.748966525+05:30",
                        "status": "Failure",
                        "status_code": 400,
                        "resources": {
                                "instances": [
                                        "/1.0/instances/c1"
                                ]
                        },
                        "metadata": null,
                        "may_cancel": false,
                        "err": "Daemon failed to setup shared mounts base. Does security.nesting need to be turned on?",
                        "location": "none"
                } 
        Error: Daemon failed to setup shared mounts base. Does security.nesting need to be turned on?

 - [ ] Output of output of `lxc monitor` while reproducing the issue

        location: none
        metadata:
          context:
            id: 00ac9bf7-0af9-4c84-9ebf-55a042ad7683
            local: /var/snap/lxd/common/lxd/unix.socket
            remote: '@'
          level: debug
          message: Event listener server handler started
        timestamp: "2022-09-29T18:27:06.728039461+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            ip: '@'
            method: GET
            protocol: unix
            url: /1.0
            username: user1
          level: debug
          message: Handling API request
        timestamp: "2022-09-29T18:27:18.749646296+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            ip: '@'
            method: GET
            protocol: unix
            url: /1.0/instances/c1
            username: user1
          level: debug
          message: Handling API request
        timestamp: "2022-09-29T18:27:18.750688501+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            ip: '@'
            method: GET
            protocol: unix
            url: /1.0/events
            username: user1
          level: debug
          message: Handling API request
        timestamp: "2022-09-29T18:27:18.751861759+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            id: 5532a1c8-660a-4450-8046-2a49ffc25407
            local: /var/snap/lxd/common/lxd/unix.socket
            remote: '@'
          level: debug
          message: Event listener server handler started
        timestamp: "2022-09-29T18:27:18.751978132+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            ip: '@'
            method: PUT
            protocol: unix
            url: /1.0/instances/c1/state
            username: user1
          level: debug
          message: Handling API request
        timestamp: "2022-09-29T18:27:18.752191693+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            class: task
            description: Starting instance
            operation: 3306b379-47df-4c5d-81ab-05c20e908070
            project: default
          level: debug
          message: New operation
        timestamp: "2022-09-29T18:27:18.77864023+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            instance: c1
            instanceType: container
            project: default
            stateful: "false"
          level: debug
          message: Start started
        timestamp: "2022-09-29T18:27:18.778933643+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            class: task
            description: Starting instance
            operation: 3306b379-47df-4c5d-81ab-05c20e908070
            project: default
          level: debug
          message: Started operation
        timestamp: "2022-09-29T18:27:18.77872802+05:30"
        type: logging
        
        
        location: none
        metadata:
          class: task
          created_at: "2022-09-29T18:27:18.752828696+05:30"
          description: Starting instance
          err: ""
          id: 3306b379-47df-4c5d-81ab-05c20e908070
          location: none
          may_cancel: false
          metadata: null
          resources:
            instances:
            - /1.0/instances/c1
          status: Pending
          status_code: 105
          updated_at: "2022-09-29T18:27:18.752828696+05:30"
        project: default
        timestamp: "2022-09-29T18:27:18.778710169+05:30"
        type: operation
        
        
        location: none
        metadata:
          class: task
          created_at: "2022-09-29T18:27:18.752828696+05:30"
          description: Starting instance
          err: ""
          id: 3306b379-47df-4c5d-81ab-05c20e908070
          location: none
          may_cancel: false
          metadata: null
          resources:
            instances:
            - /1.0/instances/c1
          status: Running
          status_code: 103
          updated_at: "2022-09-29T18:27:18.752828696+05:30"
        project: default
        timestamp: "2022-09-29T18:27:18.778751987+05:30"
        type: operation
        
        
        location: none
        metadata:
          context:
            action: start
            instance: c1
            project: default
            reusable: "false"
          level: debug
          message: Instance operation lock created
        timestamp: "2022-09-29T18:27:18.779283281+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            instance: c1
            instanceType: container
            project: default
            stateful: "false"
          level: debug
          message: Start finished
        timestamp: "2022-09-29T18:27:18.779370536+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            action: start
            err: Daemon failed to setup shared mounts base. Does security.nesting need to
              be turned on?
            instance: c1
            project: default
            reusable: "false"
          level: debug
          message: Instance operation lock finished
        timestamp: "2022-09-29T18:27:18.779329382+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            class: task
            description: Starting instance
            err: Daemon failed to setup shared mounts base. Does security.nesting need to
              be turned on?
            operation: 3306b379-47df-4c5d-81ab-05c20e908070
            project: default
          level: debug
          message: Failure for operation
        timestamp: "2022-09-29T18:27:18.779400887+05:30"
        type: logging
        
        
        location: none
        metadata:
          class: task
          created_at: "2022-09-29T18:27:18.752828696+05:30"
          description: Starting instance
          err: Daemon failed to setup shared mounts base. Does security.nesting need to be
            turned on?
          id: 3306b379-47df-4c5d-81ab-05c20e908070
          location: none
          may_cancel: false
          metadata: null
          resources:
            instances:
            - /1.0/instances/c1
          status: Failure
          status_code: 400
          updated_at: "2022-09-29T18:27:18.752828696+05:30"
        project: default
        timestamp: "2022-09-29T18:27:18.779446498+05:30"
        type: operation
        
        
        location: none
        metadata:
          context:
            ip: '@'
            method: GET
            protocol: unix
            url: /1.0/operations/3306b379-47df-4c5d-81ab-05c20e908070
            username: user1
          level: debug
          message: Handling API request
        timestamp: "2022-09-29T18:27:18.780177567+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            listener: 5532a1c8-660a-4450-8046-2a49ffc25407
            local: /var/snap/lxd/common/lxd/unix.socket
            remote: '@'
          level: debug
          message: Event listener server handler stopped
        timestamp: "2022-09-29T18:27:18.781923259+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            driver: bridge
            network: lxdbr0
            project: default
          level: debug
          message: Setting up network
        timestamp: "2022-09-29T18:27:46.171710261+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            driver: bridge
            network: lxdbr0
            project: default
          level: debug
          message: Start
        timestamp: "2022-09-29T18:27:46.171667175+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            driver: bridge
            hwAddr: 00:16:3e:bf:69:fb
            network: lxdbr0
            project: default
            seed: d779d118237169ae28d08f6c372fd2c064962770476ad6e87c7a40adbc9dc6c0.0.1
          level: debug
          message: Stable MAC generated
        timestamp: "2022-09-29T18:27:46.181745619+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            driver: bridge
            network: lxdbr0
            project: default
          level: debug
          message: Clearing firewall
        timestamp: "2022-09-29T18:27:46.183933857+05:30"
        type: logging
        
        
        location: none
        metadata:
          context:
            err: 'Failed starting: The DNS and DHCP service exited prematurely: Process exited
              with non-zero value 2 ("dnsmasq: failed to create listening socket for 10.1.1.1:
              Address already in use")'
            network: lxdbr0
            project: default
          level: error
          message: Failed initializing network
        timestamp: "2022-09-29T18:27:46.475513662+05:30"
        type: logging

**Comment by tomponline** [comment]
> The `/var/snap/lxd` should not be in OS partition, and should be on different disk for some reason.

Is the reason disk space of the storage pool volumes?

**Comment by geekstuff99** [comment]
Wants that entire lxd related stuff in LUKS volume

**Comment by stgraber** [comment]
You really need to ensure that your bind-mount is in place before LXD gets even the slightest chance of starting up.
Otherwise you'll have a new snapd mount namespace setup and populated with the wrong mounts.

**Comment by stgraber** [comment]
If /etc/fstab isn't an option, you should probably disable all the LXD systemd units (snap.lxd.activate, snap.lxd.daemon, ...) and only re-enable and trigger them after your mount is in place.

**Comment by geekstuff99** [comment]
Great. Thanks for the idea.
How can i disable & enable with CLI commands .. ?
[Some times i may be in struggle with this, rather than right way.].
Please ...

**Comment by geekstuff99** [comment]
Is `sudo snap stop|start lxd ` right method ?

**Comment by tomponline** [comment]
`systemctl stop snap.lxd.daemon.service snap.lxd.daemon.unix.socket`

**Comment by geekstuff99** [comment]
Thanks a lot. You saved me.
Let me try this way.
