### ISSUE TITLE
Kernel 6.0.0 triggers snap bug with LXD on ubuntu 22.04.1

### ISSUE THREAD

**Issue by odtgit** [lxc/lxd#11005]
# Required information
 
 * Distribution: Ubuntu
 * Distribution version: 22.04.1
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux cube 6.0.0-060000-generic #202210022231 SMP PREEMPT_DYNAMIC Sun Oct 2 22:35:09 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
   * LXD version:
lxd     5.6-794016a  23680  latest/stable  canonical✓  -
   * Storage backend in use: Directory

# Issue description
After upgrading to mainline 6.0.0 lxc runs for couple of hours stable then starts bugging out with the error below:

odt@cube ~> lxc version
sed: /lib/x86_64-linux-gnu/libdl.so.2: unsupported version 0 of Verdef record
sed: error while loading shared libraries: /lib/x86_64-linux-gnu/libdl.so.2: unsupported version 0 of Verneed record
grep: error while loading shared libraries: /lib/x86_64-linux-gnu/libdl.so.2: unsupported version 0 of Verneed record

The containers will continue running normally, but there is no way to interact with them using the lxc CLI.

# Steps to reproduce

 1. Step one: Ubuntu 22.04.1, install mainline 6.0.0

# Information to attach

https://www.spinics.net/lists/kernel/msg4534165.html

Something similar for firefox.

**Comment by odtgit** [comment]
Added strace -f

[strace.log.gz](https://github.com/lxc/lxd/files/9742054/strace.log.gz)

**Comment by brauner** [comment]
Is there something in `dmesg`?

**Comment by odtgit** [comment]
Nothing obvious, no... According to my some cron lxc exec outputs it stopped responding at around 19:00 on Oct 8th.
[dmesg.log.gz](https://github.com/lxc/lxd/files/9742164/dmesg.log.gz)

**Comment by odtgit** [comment]
I have reproduced this on a different machine running the same snap from Ubuntu 22.04.1 and the 6.0.0 kernel:

/snap/snapd/17029/usr/lib/snapd/snap-confine: symbol lookup error: /snap/snapd/17029/usr/lib/snapd/snap-confine: undefined symbol: , version GLIBC_2.2.5

**Comment by stgraber** [comment]
The trace above suggests an issue with snap-confine which runs prior to any of the LXD code or even LXD's packaging scripts.
This feels like some kind of issue with snapd and that new kernel.

Could you report this at https://forum.snapcraft.io so the snapd team can take a look?

**Comment by Bixilon** [comment]
Acutally I can fully reproduce it, probably a snap issue.

**Comment by sanderjo** [comment]
Certainly related to snap: I get it with the snap version of firefox:

```
sander@zwart2204:~$ firefox
/bin/bash: /lib/x86_64-linux-gnu/libdl.so.2: unsupported version 0 of Verdef record
/bin/bash: error while loading shared libraries: /lib/x86_64-linux-gnu/libdl.so.2: unsupported version 0 of Verneed record
sander@zwart2204:~$ 
sander@zwart2204:~$ which firefox
/snap/bin/firefox

sander@zwart2204:~$ uname -a
Linux zwart2204 6.0.0-060000-generic #202210022231 SMP PREEMPT_DYNAMIC Sun Oct 2 22:35:09 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dontlaugh** [comment]
Pop!_OS updated my kernel today, and I hit this on 6.0.2

They ship a utility that wraps systemd-boot called `kernelstub` https://support.system76.com/articles/kernelstub

If you run Pop, see that article to learn how to boot a previous kernel until this bugfix rolls out.
