### ISSUE TITLE
Creating OVS bridge fails and complains Open vSwitch is not installed

### ISSUE THREAD

**Issue by mkgvt** [lxc/lxd#11004]
# Required information

 * Distribution: NixOS
 * Distribution version: 22.05
 * The output of "lxc info" or if that fails: [lxc.info.txt](https://github.com/lxc/lxd/files/9737251/lxc.info.txt)
   * Kernel version: 5.15.60
   * LXC version: 4.0.12
   * LXD version: 5.1
   * Storage backend in use: zfs

# Issue description

Attempting to create a second network using OVS in addition to default lxdbr0. The command
```
$ lxc network create ovsnet --type=bridge bridge.driver=openvswitch
```
gives the error message
```
Error: Open vSwitch isn't installed on this system
```
but ovs-vsctl is installed:
```
$ ovs-vsctl --version
ovs-vsctl (Open vSwitch) 2.17.0
DB Schema 8.3.0
```
Expected behavior is for the network to be created.

# Steps to reproduce

 1. Step one: start with a fresh installation of LXD with only the default `lxdbr0` bridge
 2. Step two: execute, either as user or as root:
 ```
$ lxc network create ovsnet --type=bridge bridge.driver=openvswitch
```
There are no error messages in the systemd journal. The [source code](https://github.com/lxc/lxd/blob/master/lxd/network/driver_bridge.go#L602-L604) checks if [ovs-vsctl](https://github.com/lxc/lxd/blob/master/lxd/network/openvswitch/ovs.go#L38-L42) is installed, which should succeed considering the command is in the path.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Yeah, only way for this to fail is if `ovs-vsctl` isn't in the PATH.
My guess would be that your LXD daemon is running with a different PATH than your shell and that its PATH doesn't include what's needed for ovs-vsctl.

Can you show `which ovs-vsctl` as well as `cat /proc/PID-OF-LXD/environ | tr '\0' '\n' | grep PATH`?

**Comment by mkgvt** [comment]
Well spotted. As the user:
```
$ which ovs-vsctl
/run/current-system/sw/bin/ovs-vsctl
$ readlink $(which ovs-vsctl)
/nix/store/m7gvl62d3bn3cnbbglm21dgyqfsxpilc-openvswitch-2.17.0/bin/ovs-vsctl
```

which is exactly the same package as root:
```
# which ovs-vsctl
/run/current-system/sw/bin/ovs-vsctl
# readlink $(which ovs-vsctl)
/nix/store/m7gvl62d3bn3cnbbglm21dgyqfsxpilc-openvswitch-2.17.0/bin/ovs-vsctl
```

The LXD daemon path should contain the path to the ovs-vsctl binary but does not:
```
$ ps aux | awk '/bin\/lxd/{print $2}'
2325233
$ sudo cat /proc/2325233/environ | tr '\0' '\n' | grep PATH | sed 's/PATH=//;s/:/\n/g'
/nix/store/1j8bp97d7m9j7pzm58q2fhqfm1p3pnzi-iptables-1.8.7/bin
/nix/store/b9cgfd1ly01khk5kfrqq3gjrjfhxqxj5-acl-2.3.1-bin/bin
/nix/store/l2cvi0rfkrm14axd6fidixldayf2x1q7-rsync-3.2.3/bin
/nix/store/mnln1nxdhxx5qj8rcyvllhhs6d4h668b-gnutar-1.34/bin
/nix/store/plwz40xsmqsiq5gqavij50lp9vzpn2p6-xz-5.2.5-bin/bin
/nix/store/71kz0gns59s0ixwpjrp96wgxwdzhsf2d-btrfs-progs-5.17/bin
/nix/store/6707csjy3qf4p9anrrg3lbsjlh7il7lh-gzip-1.12/bin
/nix/store/ffsaal905zxdgdc39r5gqini7ls2wid3-dnsmasq-2.86/bin
/nix/store/n5fdwh6ay0h5217wbc7qxl6ps34hi0w3-squashfs-4.5.1/bin
/nix/store/fjbhss3462zaf8dwgbw7fz0w3kqynv3k-iproute2-5.17.0/bin
/nix/store/xbdqbi2mscmhl5wcpbgpjdwxbsrvpkil-bash-5.1-p16/bin
/nix/store/mkjh5k224ch5wb51rqmp3a8mgn1g2ykk-criu-3.15/bin
/nix/store/gdh49qwa3diyfdsxg9azh738pyarmdaw-attr-2.5.1-bin/bin
/nix/store/99vgmb9xbdlfrvdgv3b84i6w7j1qmyh8-apparmor_parser/bin
/nix/store/56cnxji4339lgb3my8fpg289cgs8q5f9-zfs-user-2.1.5/bin
/nix/store/p643r4aczmzb0dhyrx3dj592f0s5v7xj-coreutils-9.0/bin
/nix/store/7g48ahc3xnmb5b851vw60nbdgvk0wsf8-findutils-4.9.0/bin
/nix/store/ja8bi2cbpm36nwqy1hvklm3y9n7s3247-gnugrep-3.7/bin
/nix/store/lrxxki2m4gr4w3lxw08qpd465skpa04y-gnused-4.8/bin
/nix/store/vqy0ljiks17602r88abb4z3lwzny70qh-systemd-250.4/bin
/nix/store/56cnxji4339lgb3my8fpg289cgs8q5f9-zfs-user-2.1.5/sbin
/nix/store/p643r4aczmzb0dhyrx3dj592f0s5v7xj-coreutils-9.0/sbin
/nix/store/7g48ahc3xnmb5b851vw60nbdgvk0wsf8-findutils-4.9.0/sbin
/nix/store/ja8bi2cbpm36nwqy1hvklm3y9n7s3247-gnugrep-3.7/sbin
/nix/store/lrxxki2m4gr4w3lxw08qpd465skpa04y-gnused-4.8/sbin
/nix/store/vqy0ljiks17602r88abb4z3lwzny70qh-systemd-250.4/sbin
```

As is likely obvious from above, NixOS is a very different Linux distribution, particularly where paths and packages are concerned. I activated Open vSwitch in my system configuration which also installs ovs-vsctl accessible to both root and user. But as can be seen, it isn't available in the LXD package. (All NixOS packages are self-contained and independent.) I'll need to figure out how to add OVS as a dependency to LXD to solve the problem.

Thanks for your help Stéphane. I'll move this discussion to the [NixOS Forum](https://discourse.nixos.org/) and close the issue.
