### ISSUE TITLE
yaml and json formats in "lxc list" ignore filtering

### ISSUE THREAD

**Issue by cquike** [lxc/lxd#11010]
# Required information

 * Distribution: Debian 
 * Distribution version: bullseye
[lxc_info_out.txt](https://github.com/lxc/lxd/files/9749347/lxc_info_out.txt)

   * Kernel version:5.10.0-18
   * LXC version:  5.0.1-1 (as installed from deb in repo https://apt.calenhad.com/debian )
   * LXD version: 5.0.1-2
   * Storage backend in use: LVM

# Issue description

The lxc list can accept a filter based on container configuration. That filter works usually fine but if the output format is either yaml or json it seems that the filtering is ignored.
Here is an example from one server:

# lxc list  image.jenkins.node=true               
+-----------------------------+---------+----------------------+-----------------------------------------------+-----------+-----------+
|            NAME             |  STATE  |         IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS |
+-----------------------------+---------+----------------------+-----------------------------------------------+-----------+-----------+
| cifedora36-amd64-x07   | RUNNING | x.x.x.x (eth0)  | x:x:x:x (eth0) | CONTAINER | 0         |
+-----------------------------+---------+----------------------+-----------------------------------------------+-----------+-----------+
| ciubuntu2204-amd64-x07 | RUNNING | x.x.x.x. (eth0) | x:x:x:x | CONTAINER | 0         |
+-----------------------------+---------+----------------------+-----------------------------------------------+-----------+-----------+
 
# lxc list  image.jenkins.node=true -f yaml | grep "^  name:"
  name: cifedora36-amd64-x07
  name: ciubuntu2204-amd64-x07
  name: debian11-test
  name: f36-test
  name: fedora36-amd64-dev07

As you see there are in this case 5 containers listed, rather than the two that are matched only with the filter. This seems to be a regression, since in older versions (I have checked 3.0.3 and 4.0.7) this was working properly.

**Comment by stgraber** [comment]
See #10396

**Comment by cquike** [comment]
Thanks,
sorry, I didn't see the duplicate.
