### ISSUE TITLE
Port Forwarding with Multiple Network Interfaces

### ISSUE THREAD

**Issue by ak5** [lxc/lxd#1102]
Hi!

I have a strange issue where I can access my container via iptables forwarded port on one interface, but not on another.

I have 2 interfaces with a public IP for each and a container running on 10.0.3.253 with a simple webservice.

From the LXD host:

```bash
$ curl -L 10.0.3.253
Hello World
````

So that works.

Here is my iptables config:

```bash
$ iptables -t nat -nVL
Chain PREROUTING (policy ACCEPT 2931 packets, 180K bytes)
 pkts bytes target     prot opt in     out     source               destination         
   47  2588 DNAT       tcp  --  eth+   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:10.0.3.253:80

Chain INPUT (policy ACCEPT 2924 packets, 179K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 17669 packets, 1276K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 17684 packets, 1277K bytes)
 pkts bytes target     prot opt in     out     source               destination         
    4   304 MASQUERADE  all  --  *      *       10.0.3.0/24         !10.0.3.0/24
```

```bash
$ iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A PREROUTING -i eth+ -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.0.3.253:80
-A POSTROUTING -s 10.0.3.0/24 ! -d 10.0.3.0/24 -j MASQUERADE
```

My interfaces are eth0 and eth1 - public IP of eth0 works, while that of eth1 does not (timeout). I am testing this from my laptop.

I asked on ##linux on freenode if my iptables is setup ok - answer was yes - it "should" work.

So now I am thinking if it's not that, it must be something on LXD side, but I didn't find anything related to this. Please let me know if this can possibly be LXD related.

**Comment by stgraber** [comment]
Sounds to me like this is a simple case of asymmetric routing. Presumably your default gateway is eth0, so the container will get the connection through your NAT rule but when answering to the source IP will be routed through eth0 causing the response to be lost.

One easy way to debug this is to have your container ping that source IP, once it does ping and you confirm that the traffic goes out through eth1 on the host (using tcpdump or similar), then an incoming connection should work as expected.

If you don't have a specific set of subnets that should be routed through eth1 but instead can have any number of hosts connecting to either eth0 or eth1, as would be the case with two WAN connections, then you'll instead want to look at doing source based routing, basically marking the incoming connection through iptables rules and force the response to go through the same interface.

A quick and dirty workaround here though would be to add a SNAT rule too, basically rewriting the source address to be the host's, therefore avoiding the outgoing routing issue, but note that doing so will prevent the service inside your container from knowing who connected to it.

Anyway, this is a standard issue which isn't in any way specific to LXC or LXD. You should be able to find a good number of documentation and howtos on how to make that kind of setup work by looking for multiwan.

Closing this issue as it's not a LXD bug.
