### ISSUE TITLE
feature request: location field for non clustered hosts

### ISSUE THREAD

**Issue by aivanise** [lxc/lxd#11033]
Hi,

would be nice and consistent if the "location" field in the response to local socket request is filled in with the host name, instead of "none" for non clustered hosts, since it is already filled in for clustered ones

non-clustered:

$ echo -e "GET /1.0 HTTP/1.0\n" | sudo socat stdio unix-connect:/dev/lxd/sock
HTTP/1.0 200 OK
Content-Type: application/json
Date: Tue, 18 Oct 2022 07:33:21 GMT
Content-Length: 86

{"state":"Started","api_version":"1.0","instance_type":"container","location":"none"}

clustered:

$ echo -e "GET /1.0 HTTP/1.0\n" | sudo socat stdio unix-connect:/dev/lxd/sock
HTTP/1.0 200 OK
Content-Type: application/json
Date: Tue, 18 Oct 2022 07:37:08 GMT
Content-Length: 87

{"state":"Started","api_version":"1.0","instance_type":"container","location":"lxd13"}

**Comment by tomponline** [comment]
The `location` field is the cluster member name. So for standalone servers the `location` is "none" because there are no cluster members.

**Comment by aivanise** [comment]
yeah, but maybe you could use core.https_address (without the port) or have an extra name field in core namespace if thats a security concern

I got really used to know the name of the host where the container is running, so that I can quickly hop to the host while investigating issues, only to realize that its not there if I'm not in the cluster :(

**Comment by stgraber** [comment]
But let's not do that for all other Location fields in the main API, just keep that to /dev/lxd
