### ISSUE TITLE
I/O disk limits on  not work with HW RAID but work with mdadm, with all some settings

### ISSUE THREAD

**Issue by gribchenko** [lxc/lxd#11056]
# Required information

 * Distribution:
 Ubuntu 
 * Distribution version:
 20.04.5 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version:
 5.4.0-131-generic
  * LXC version:
5.7
   * LXD version:
5.7

   * Storage backend in use:
 lxc storage show default 

config:
  rsync.compression: "false"
  source: /var/lib/lxd/storage-pools/default
description: Default DIR storage backend
name: default
driver: dir
used_by:
- /1.0/instances/ct3020
- /1.0/profiles/default
status: Created
locations:
- none

# Issue description

1) /dev/sdc1        14T  3.9T  9.4T  29% /var/lib/lxd   - not work

  read: IOPS=111k, BW=433MiB/s (454MB/s)(3070MiB/7090msec)
   bw (  KiB/s): min=339544, max=569668, per=100.00%, avg=445066.57, stdev=68591.63, samples=14
   iops        : min=84886, max=142417, avg=111266.64, stdev=17147.95, samples=14
  write: IOPS=37.0k, BW=145MiB/s (152MB/s)(1026MiB/7090msec); 0 zone resets
   bw (  KiB/s): min=111824, max=190674, per=100.00%, avg=148729.29, stdev=23387.51, samples=14
   iops        : min=27956, max=47668, avg=37182.29, stdev=5846.81, samples=14

    /dev/md1         21T  8.2T   12T  42% /var/lib/lxd  - work

  read: IOPS=2006, BW=8027KiB/s (8220kB/s)(53.4MiB/6809msec)
   bw (  KiB/s): min= 8000, max= 8000, per=99.66%, avg=8000.00, stdev= 0.00, samples=13
   iops        : min= 2000, max= 2000, avg=2000.00, stdev= 0.00, samples=13
  write: IOPS=665, BW=2664KiB/s (2727kB/s)(17.7MiB/6809msec); 0 zone resets
   bw (  KiB/s): min= 2400, max= 2984, per=100.00%, avg=2664.00, stdev=168.67, samples=13
   iops        : min=  600, max=  746, avg=666.00, stdev=42.17, samples=13
  cpu          : usr=0.47%, sys=3.00%, ctx=247, majf=0, minf=6

lxc config show ct3020 --expanded

architecture: x86_64
config:
  boot.autostart: "true"
  limits.cpu: "6"
  limits.hugepages.1GB: 4GiB
  limits.hugepages.2MB: 100MiB
  limits.memory: 16GiB
  limits.memory.enforce: hard
  limits.memory.swap: "false"
  limits.processes: "800"
  raw.lxc: lxc.cgroup.memory.oom_control=1
  security.idmap.base: "30234800"
  security.idmap.isolated: "true"
  user.fqdn: *****
  volatile.cloud-init.instance-id: 12864e62-753a-4a00-9e47-9a51b6cb9586
  volatile.eth0.host_name: vethaee2e5e9
  volatile.eth0.hwaddr: 00:16:3e:83:13:3c
  volatile.idmap.base: "30234800"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":30234800,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":30234800,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":30234800,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":30234800,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":30234800,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":30234800,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: ac571687-2fe6-4e4e-a6cb-948472868f8e
devices:
  eth0:
    ipv4.address: ******
    mtu: "1500"
    name: eth0
    nictype: routed
    type: nic
  resolvconf:
    path: /etc/resolv.conf
    readonly: "true"
    source: /etc/resolv.conf
    type: disk
  root:
    limits.read: 2000iops
    limits.write: 1000iops
    path: /
    pool: default
    size: 256GiB
    type: disk
  shared:
    path: /shared
    readonly: "true"
    source: /shared
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

# Steps to reproduce

 1. Step one
 Run ct on node with mdadm - iops limit - work
 3. Step two
 move ct on node with  HPE Smart Array P408i-a SR Gen10
limit stop working
 5. Step three

:((
# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
That's not under LXD's control. Some devices expose blkio counters/throttles, some don't.

In this case, recent systems use scsi-mq for their disk I/O which cannot be combined with scheduling limits on I/O, putting something like a md layer on top will cause it to have queuing handled by the kernel which then can be throttled.
