### ISSUE TITLE
Lxc profile edit gets killed with large amounts of user-data (~31Mb)

### ISSUE THREAD

**Issue by klaasvakie** [lxc/lxd#11064]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-1020-kvm
   * LXC version: 5.0.1
   * LXD version: 5.0.1
   * Storage backend in use: zfs

Not sure if it makes a difference, but the lxc commands are being run inside a lxd guest vm, so:
```
host - bare metal
  guest - lxd vm (lxd launch ubuntu: myvm --vm)
```
All the `lxc` commands below are being run on guest.

# Issue description

When adding a large amount of cloud-init.user-data to a profile, the "lxc profile edit" operation gets killed once the file is saved

# Steps to reproduce

Make a lxc profile like this:
```
$ lxc profile copy default testprof
$ lxc profile edit testprof
```
contents:
```
 config:
  boot.autostart: "true"
  boot.autostart.delay: "30"
  boot.autostart.priority: "100"
  cloud-init.network-config: |
    network:
      version: 2
      ethernets:
        eth0:
          dhcp4: true
  cloud-init.user-data: |
    #cloud-config
    write_files:
      - path: /usr/local/bin/testbinary
        encoding: b64
        owner: 'root:root'
        permissions: '0644'
        content: |
          "Add 31Mb of base64 data here"
description: Profile for test
devices:
  eth0:
    nictype: bridged
    parent: internalbr
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: testprof
used_by: []

```

Once the file is saved, the word "Killed" is printed on the console
```
$ lxc profile edit testprof 
Killed
$ 
```

`$ lxc profile edit testprof --debug` 
just prints an copy of the entire profile with a "Killed" as the last line 

```
$ lxc monitor --loglevel debug -f pretty
DEBUG  [2022-10-27T21:47:56Z] Event listener server handler started         id=645966a1-36e0-412f-8a36-2013cc5868d4 local=/var/snap/lxd/common/lxd/unix.socket remote=@
DEBUG  [2022-10-27T21:48:02Z] Handling API request                          ip=@ method=GET protocol=unix url=/1.0 username=root
DEBUG  [2022-10-27T21:48:02Z] Handling API request                          ip=@ method=GET protocol=unix url=/1.0/profiles/testprof username=root
Error: websocket: close 1006 (abnormal closure): unexpected EOF
```

Subsequent attempts at editing the profile fail in a similar manner:

```
$ lxc profile edit testprof
Error: unexpected EOF
$
```

**Comment by stgraber** [comment]
That suggests your system is running out of memory, can you look at the output of `dmesg`?

**Comment by klaasvakie** [comment]
Yes, OOM was the issue. I didn't realize the default mem limits for VMs were so low.
