### ISSUE TITLE
Found a way to add a Description to my LXC 5.1 containers from shell

### ISSUE THREAD

**Issue by cilex-ft** [lxc/lxd#11062]
This not an issue, rather a solution! (or a hack?)

I just discovered that I can add a description on my LXD 5.1, for container `abcd`, using good ol' redirections:

```
lxc config show abcd > container_abcd
sed -i 's/description: ""/description: "This works"/' container_abcd
lxc config edit abcd < container_abcd
```

Sorry if I just re-discovered something obvious - otherwise Enjoy!

**Comment by stgraber** [comment]
Yeah, show, then sed, then edit is how we test this stuff.
