### ISSUE TITLE
Default profile for TPM for both containers and VMs

### ISSUE THREAD

**Issue by xnox** [lxc/lxd#11073]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04 Jammy
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-52-generic
   * LXC version: 5.7
   * LXD version: 5.7
   * Storage backend in use: 

# Issue description

I would like to launch all containers and all VMs with TPM device by default

# Steps to reproduce

 1. `lxc profile device add default tpm tpm path=/dev/tpm0`
 2. Launch lxd vm
 3. Launch lxd container

the lxc profile command fails validation, because config validation says that path key is unknown. One can drop the path key to add the tpm to the profile, and it works for VMs.

Launching regular container however fails, with mandatory argument path missing.

**Comment by stgraber** [comment]
Ah yeah, that seems like a validation error as we normally have handling for such cases where a device inside of a profile has a slightly relaxed validation to account for differences in config between containers and VMs.

**Comment by xnox** [comment]
I found this https://github.com/lxc/lxd/blob/master/lxd/device/tpm.go#L31 and it did look, as if in needs to be relaxed to allow path key as optional during "profile update, not bound to any instance type", ignored when bound to VM, and enforced when bound to a container.

**Comment by tomponline** [comment]
Yep indeed. We have similar checks in other device types.

**Comment by tomponline** [comment]
We have an instancetype.Any to indicate profile validation.

**Comment by tomponline** [comment]
Or in some places I think, because we do a 2 stage validation, we can check if d.inst != nil and then only do the validation once there is a concrete instance (with its type) associated to the device.

**Comment by tomponline** [comment]
Like this https://github.com/lxc/lxd/blob/master/lxd/device/nic_bridged.go#L290-L297
