### ISSUE TITLE
LXD returning incorrect profile projects names

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#11083]
Not even sure where to start with this one, its seems LXD is returning entity names as part of the `?project` instead of the project name?

```
lxc query /1.0/profiles?project=ASDF
[
	"/1.0/profiles/9kupATDcL7tq?project=9kupATDcL7tq", # Was wrong about this on init submit
                                                                                              # this is in-fact part of ASDF
	"/1.0/profiles/asdf-profile?project=asdf-profile", # should be in a project called ASDF
]
```
```
snap info lxd
...
snap-id:      J60k4JY0HppjwOjW8dZdYc8obXKxujRu
tracking:     latest/edge
refresh-date: yesterday at 23:38 GMT
...
```

**Comment by tomponline** [comment]
Can you show output of lxc profile list please

**Comment by turtle0x1** [comment]
Speculating that its caused on this line https://github.com/lxc/lxd/blob/master/lxd/profiles.go#L182

```
# p.Name should be the project name no?
urls[i] = p.URL(version.APIVersion, p.Name).String()
```

**Comment by turtle0x1** [comment]
Okay I was wrong the filtering still applies because `lxc profile list` uses `recursion=1`.

`lxc profile list --project="ASDF"` does infact return the correct result

**Comment by tomponline** [comment]
Yeah so its incorrectly passing profile name for project name I would say, will get that fixed.

**Comment by tomponline** [comment]
But only in  non recursive mode

**Comment by turtle0x1** [comment]
_Wilder speculation_ looks like a cheeky reallocation of the `p` variable is causing that one, its used at the top to extract project details and then re-declared at the start of the for loop

**Comment by tomponline** [comment]
Yes exactly
