### ISSUE TITLE
ephemeral instances should have their storage backend tuned for speed rather than reliability

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#11096]
It'd be nice for ephemeral instances to have their backing ZFS configured with `sync=disabled`.

**Comment by simondeziel** [comment]
This would potentially be handy to speed up CI runs using guest VMs.

**Comment by stgraber** [comment]
I don't actually think that this is a good idea. We shouldn't assume that ephemeral means we're happy to lose data.
What ephemeral means is that when the instance shuts itself down or when the user stops it, that we want it to go away.

If the machine crashes for some reason, we will bring the ephemeral instances back online on boot, we won't delete them.
Making this change would therefore expose us to data loss.
