### ISSUE TITLE
broken usb device Passthrough 

### ISSUE THREAD

**Issue by 13werwolf13** [lxc/lxd#11105]
* Distribution: openSUSE Tumbleweed
 * Distribution version: 20221105
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.0.6
   * LXC version: 5.7
   * LXD version: 6.0.6
   * Storage backend in use: btrfs

# Issue description

broken usb device Passthrough 

# Steps to reproduce

 1. create container
 2. Passthrough usb bluetooth dongle
 3. try install & start bluetoothd

# Information to attach
homeassistant lives on my home server inside lxc/lxd container. a year ago I Passthrough usb zygbee sonoff (as tty) into it and it works, and today I tried the same Passthrough usb bluetooth (which works on the host itself) and it doesn't work.

```
[werwolf@power] ~  
❯ lxc config show ha
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: Opensuse 15.3 amd64 (20220505_04:20)
  image.os: Opensuse
  image.release: "15.3"
  image.serial: "20220505_04:20"
  image.type: squashfs
  image.variant: default
  limits.cpu: "2"
  limits.memory: 4096MB
  volatile.base_image: d5e5c6c1ca09f32624d9f81d2568436aca3c9e4ab8b96cdb86470b8204f51df8
  volatile.eth0.host_name: veth2ff496e5
  volatile.eth0.hwaddr: 00:16:3e:ae:ed:77
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":400000000,"Nsid":0,"Maprange":500000001},{"Isuid":false,"Isgid":true,"Hostid":400000000,"Nsid":0,"Maprange":500000001}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":400000000,"Nsid":0,"Maprange":500000001},{"Isuid":false,"Isgid":true,"Hostid":400000000,"Nsid":0,"Maprange":500000001}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: 81b6038a-ad88-4d4a-83d1-a377cbbf5ee6
devices:
  zgb_snff:
    mode: "0777"
    path: /dev/ttyUSB0
    required: "false"
    type: unix-char
  bt_usb:
    productid: "0001"
    type: usb
    vendorid: 0a12
  esphomeport:
    connect: tcp:127.0.0.1:6052
    listen: tcp:0.0.0.0:6052
    type: proxy
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  haport:
    connect: tcp:127.0.0.1:8123
    listen: tcp:0.0.0.0:8123
    type: proxy
  sharedmedia:
    path: /root/.homeassistant/media/
    source: /home/werwolf/media
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

[werwolf@power] ~  
❯ lxc shell ha      
ha:~ # systemctl status bluetooth
x bluetooth.service - Bluetooth service
     Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; vendor preset: disabled)
    Drop-In: /run/systemd/system/service.d
             `-zzz-lxc-service.conf
     Active: failed (Result: exit-code) since Wed 2022-11-09 22:19:44 +05; 17min ago
       Docs: man:bluetoothd(8)
    Process: 27894 ExecStart=/usr/lib/bluetooth/bluetoothd (code=exited, status=1/FAILURE)
   Main PID: 27894 (code=exited, status=1/FAILURE)
     Status: "Starting up"
        CPU: 18ms

Nov 09 22:19:44 ha systemd[1]: Starting Bluetooth service...
Nov 09 22:19:44 ha bluetoothd[27894]: Bluetooth daemon 5.62
Nov 09 22:19:44 ha systemd[1]: Started Bluetooth service.
Nov 09 22:19:44 ha bluetoothd[27894]: src/adapter.c:adapter_init() Failed to access management interface
Nov 09 22:19:44 ha bluetoothd[27894]: src/main.c:main() Adapter handling initialization failed
Nov 09 22:19:44 ha systemd[1]: bluetooth.service: Main process exited, code=exited, status=1/FAILURE
Nov 09 22:19:44 ha systemd[1]: bluetooth.service: Failed with result 'exit-code'.

```

**Comment by 13werwolf13** [comment]
```
power:~ # zypper info lxd
Loading repository data...
Reading installed packages...


Information for package lxd:
----------------------------
Repository     : Основной репозиторий (OSS)
Name           : lxd
Version        : 5.7-1.1
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 220.5 MiB
Installed      : Yes
Status         : up-to-date
Source package : lxd-5.7-1.1.src
Upstream URL   : https://linuxcontainers.org/lxd
Summary        : Container hypervisor based on LXC
Description    : 
    LXD is a system container manager. It offers a user experience
    similar to virtual machines but uses Linux containers (LXC) instead.

[werwolf@power] ~  
❯ lxc shell ha                                                                                                                                                                                                                                                             ⏎
ha:~ # ls -la /sys/class/bluetooth/hci0/
total 0
drwxr-xr-x 4 nobody nobody    0 Nov  9 20:02 .
drwxr-xr-x 3 nobody nobody    0 Nov  9 20:02 ..
lrwxrwxrwx 1 nobody nobody    0 Nov  9 22:23 device -> ../../../2-6:1.0
drwxr-xr-x 2 nobody nobody    0 Nov  9 20:13 power
drwxr-xr-x 3 nobody nobody    0 Nov  9 20:02 rfkill0
lrwxrwxrwx 1 nobody nobody    0 Nov  9 20:02 subsystem -> ../../../../../../../../class/bluetooth
-rw-r--r-- 1 nobody nobody 4096 Nov  9 20:02 uevent
```

**Comment by stgraber** [comment]
I don't believe this is a LXD bug.

The USB passthrough only affects /dev/usb/XXX/YYY devices. It doesn't support devices that use specific in-kernel drivers like a bluetooth dongle.

I believe there is a full userspace stack for bluetooth which does use /dev/usb/XXX/YYY devices, but I don't know if this can be used by homeassistant. The in-kernel bluetooth stack (hci devices) does not support namespacing, or at least did not support it last I checked, so there was no way to move such a device into a container.

Should the bluetooth stack end up supporting namspacing, then LXD would introduce a new `bluetooth` device type specifically for this.

**Comment by 13werwolf13** [comment]
@stgraber If I understand you correctly it means that at the moment I will not be able to use this Bluetooth device in the container. It's very sad. 
But thank you for the detailed answer. And sorry for the unnecessary issue.

**Comment by stgraber** [comment]
That's correct. Bluetooth has always been an odd case as it's kinda like normal networking but also not fully integrated with the network namespace making its use in containers difficult or even impossible.

**Comment by getwildr** [comment]
Hi, 

I don't know if this is the right place but this is definitely the issue title I was looking for.
I have a USB pass through that was working before (a few changes and updates) and not working anymore.

Using LXD over Ubuntu 22.04.1 LTS + snapd
```
snapd:
  Installed: 2.57.5+22.04

lxd     5.7-c62733b  23889  latest/stable  canonical✓  -
```

Before I would simply do this
`lxc config device add cn02 ledger usb vendorid=2c97`

And it worked.
Now I can't reach the USB device from inside my cn02.

Any idea how we could debug this ?

NB : I can reach the USB from the host.
The needed command exec'd on my USB returns OK.

**Comment by getwildr** [comment]
@stgraber Can you confirm we can restart the discussion here or if I should open another new issue ?

**Comment by tomponline** [comment]
Please can you post over at https://discuss.linuxcontainers.org/ as that is where we prefer to provide initial support. Thanks

**Comment by getwildr** [comment]
Yes !

Just did:

https://discuss.linuxcontainers.org/t/cannot-use-usb-dev-inside-container-anymore/15661
