### ISSUE TITLE
Failed to query /1.0/resources

### ISSUE THREAD

**Issue by alesstimec** [lxc/lxd#11131]
# Required information

 * Distribution: ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-1017-raspi
   * Kernel architecture: aarch64
   * LXC version: 5.0.1
   * LXD version: 5.0.1
   * Storage backend in use: dir

# Issue description

Running on Raspberry Pi, without an ethernet connection (only Wifi), trying to run 
   sudo lxc query /1.0/resources
gives the following output:
   Error: Failed to retrieve network information: Failed to add device information for "/sys/class/net/eth0/device": Failed to add port info: Failed to ETHTOOL_GSET: invalid argument

Debug output available at: https://pastebin.com/NLBjvxUd

# Steps to reproduce

 1. Install Ubuntu 20.04 on Raspberry Pi
 2. Run: sudo snap install lxd --channel latest/stable
 3. Run: sudo lxc query /1.0/resources

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
Can you show `ip a` and `ip r` on the host please.

**Comment by stgraber** [comment]
I think we may have fixed that already.

**Comment by stgraber** [comment]
d8d2662e27f6cc8493f30211b94ecbd0694cd3dc

**Comment by stgraber** [comment]
Hmm, actually, no, the error here is EINVAL which isn't one of those we're catching.

**Comment by stgraber** [comment]
anyway, running `ethtool eth0` would be interesting too

**Comment by petermakowski** [comment]
I'm getting a similar issue using a similar setup (RaspberryPi with WiFi connection and no ethernet connection).
More info below.

#### lxd/lxc version
5.8
#### Kernel
Linux version 5.15.61-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34)


#### sudo lxc info --resources
```
Error: Failed to retrieve network information: Failed to add device information for "/sys/class/net/wlan0/device": Failed to add port info: Failed to ETHTOOL_GLINK: operation not supported
```

#### sudo iwconfig wlan0
```
wlan0     IEEE 802.11  ESSID:"X"
          Mode:Managed  Frequency:5.18 GHz  Access Point: 74:24:9F:D9:FA:23
          Bit Rate=351 Mb/s   Tx-Power=31 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
          Link Quality=48/70  Signal level=-62 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

#### ip a

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether e4:5f:01:d9:b6:8c brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether e4:5f:01:d9:b6:8d brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.236/24 brd 192.168.1.255 scope global dynamic noprefixroute wlan0
       valid_lft 40640sec preferred_lft 35240sec
    inet6 fd5e:9a9e:c5bd:10::7d5/128 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fd5e:9a9e:c5bd:10:cb40:e41b:93d9:6b75/64 scope global mngtmpaddr noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::ae29:f6f1:7bc:69e0/64 scope link
       valid_lft forever preferred_lft forever
4: lxdbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:16:3e:9b:58:07 brd ff:ff:ff:ff:ff:ff
    inet 10.250.52.1/24 scope global lxdbr0
       valid_lft forever preferred_lft forever
    inet6 fd42:8a3f:668a:ff03::1/64 scope global
       valid_lft forever preferred_lft forever
```

#### ip r
```
default via 192.168.1.1 dev wlan0 proto dhcp src 192.168.1.236 metric 303
10.250.52.0/24 dev lxdbr0 proto kernel scope link src 10.250.52.1 linkdown
192.168.1.0/24 dev wlan0 proto dhcp scope link src 192.168.1.236 metric 303
```

**Comment by stgraber** [comment]
@petermakowski that's different, your error is about a wifi card, the original report was about a wired card.

But looks like in general we should just ignore all errors from this call as drivers appear to be returning a very wide range of error for this one...
