### ISSUE TITLE
LXD tries to access the host's /run/systemd/resolve/stub-resolv.conf

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#11149]
Starting a VM results in this Apparmor denial:

```
apparmor="DENIED" operation="open" profile="lxd-selected-dassie_</var/snap/lxd/common/lxd>" name="/var/lib/snapd/hostfs/run/systemd/resolve/stub-resolv.conf" pid=1111041 comm="lxd" requested_mask="r" denied_mask="r" fsuid=0 ouid=101
```
If I read this correctly, that's `lxd` itself trying to read that file rather than the expected `dnsmasq`.

Steps to reproduce:

```
$ lxc launch images:ubuntu/22.04 --vm
Creating the instance
Instance name is: upright-newt
Starting upright-newt
```

```
$ journalctl -k --grep 'apparmor="DENIED" operation="open" profile="lxd-'
... apparmor="DENIED" operation="open" profile="lxd-upright-newt_</var/snap/lxd/common/lxd>" name="/var/lib/snapd/hostfs/run/systemd/resolve/stub-resolv.conf" pid=1127144 comm="lxd" requested_mask>
```

Additional information:

```
$ snap list lxd
Name  Version      Rev    Tracking       Publisher   Notes
lxd   5.8-ee04373  23972  latest/stable  canonical✓  -

$ uname -a
Linux sdeziel-lemur 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -rd
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
```

**Comment by stgraber** [comment]
Looks like qemu trying to resolve something through libnss and not being able to parse the resolv.conf symlink due to apparmor.

**Comment by tomponline** [comment]
I'll look at adding it to the qemu apparmor profile to cut down on the log noise.

**Comment by tomponline** [comment]
Want to take this one @Viktor-Yakovchuk ?

**Comment by Viktor-Yakovchuk** [comment]
Yes. I'll take

**Comment by tomponline** [comment]
Thanks!

**Comment by tomponline** [comment]
@Viktor-Yakovchuk do you need any help with this?

**Comment by Viktor-Yakovchuk** [comment]
Hello Tom, thanks, yes I need a suggestion on how to debug lxd in snap package. Now I am trying to rebuild snap package using snapcraft and it takes lot of time even on 'hellow world' and I don't fully understand haw to put lxd into snap package.

**Comment by tomponline** [comment]
If you build LXD on a Focal machine (or inside a Focal container/VM) then you can copy the resulting `lxd` binary over the top of an existing snap installation (recommend using channel `latest/edge` so you know you've got the latest contents of the snap) by doing the following:

```
sudo mv lxd.debug /var/snap/lxd/common/lxd.debug
sudo snap set lxd daemon.debug=true # optional but recommended for development
sudo systemctl reload snap.lxd.daemon
```

This will sideload a custom LXD binary into the snap package.
You can see if its being used by doing `ps aux | grep lxd.debug`

**Comment by simondeziel** [comment]
@Viktor-Yakovchuk thank you very much!
