### ISSUE TITLE
Feature request: create DNS records for non-default projects (i.e. in multi user setup)

### ISSUE THREAD

**Issue by invizus** [lxc/lxd#11145]
Following the discussion in https://discuss.linuxcontainers.org/t/dns-not-created-for-containers-created-in-user-projects/15668

Hope this is acceptable format to request additional functionality. I have been hacking the most out of LXD for my use case and possibly it is not intended use, so low priority and not important if this is going to be dismissed.

## Summary
LXD server is configured in multi-user setup. The network is shared across all projects. Zone is configured for the network.

When container is created in default project, DNS record is also created for this project.
## Issue description

If container is created in a user project, which is not a default project, DNS record is not created (see links below).

Maybe enable this via project config, features or restrictions? https://linuxcontainers.org/lxd/docs/master/projects/

## Steps to reproduce
Configure zones for your network, ensure network is shared across all projects. Create containers in default and non default projects. Monitor zone transfer and check whether all DNS records are created/exported.

## Relevant info
multi user setup: https://discourse.ubuntu.com/t/easy-multi-user-lxd-setup/26215
create dns zone: https://linuxcontainers.org/lxd/docs/master/howto/network_zones/

**Comment by tomponline** [comment]
I'm already working on this.

**Comment by stgraber** [comment]
I don't see how option 2 can work.

The DNS server can only have one version of the zone. We can't allow the same zone to exist in two projects at the same time or we won't know what to serve.

**Comment by stgraber** [comment]
Ah, I see, you'd still keep the zones unique but allow linking to multiple zones and then filter by the protect the zone is tied to.

I think that would work and shouldn't be too big a change if we go with comma separated zone names.

**Comment by tomponline** [comment]
Yep exactly, thanks.
