### ISSUE TITLE
Heavy CPU load from device monitor (tun device, openvpn on the host)

### ISSUE THREAD

**Issue by mihalicyn** [lxc/lxd#11151]
# Required information

 * Distribution: debian
 * Distribution version:11.5 bullseye
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.10.0-19-amd64
   * LXC version: 5.0.1
   * LXD version: 5.7
   * Storage backend in use: zfs

# Issue description

As reported by @aivanise https://discuss.linuxcontainers.org/t/lxd-daemon-high-cpu-usage-processing-inotify-watch-on-dev-net-tun

Our devmonitor fsnotify watcher makes heavy load on the CPU if user has some activity on `/dev/net/tun` (like OpenVPN server/client, etc).

The reason is that in golang fsnotify implementation we have watches for `IN_MODIFY` event:
https://github.com/fsnotify/fsnotify/blob/main/backend_inotify.go#L256
even if we only need to watch for file creations/deletion in `/dev`.

# Steps to reproduce

 1. Run LXD server
 2. Run OpenVPN client (or server) on host and make some network load
 3. That's it

**Comment by tomponline** [comment]
@mihalicyn im trying to get a simpler reproducer than just "Run OpenVPN client (or server) on host and make some network load" as that is non-trivial in itself :)

**Comment by tomponline** [comment]
I've got a simpler reproducer, by logging the events I can see a continuous stream of writes to /dev/tty

```
ERROR  [2022-11-24T10:24:57Z] tomp got event                                driver=fsnotify event="WRITE         \"/dev/tty\""
```

**Comment by mihalicyn** [comment]
Ha-ha! Yes, I can guess that you've run the LXD server in interactive mode, so, it's constantly writing logs to `/dev/tty` and creates events for itself.

**Comment by tomponline** [comment]
OK so it has to be a write directly to the file, so `dd if=/dev/urandom /dev/sda1` generates events, but mounting /dev/sda1 and writing to the filesystem doesn't.
