### ISSUE TITLE
Inconsistency with boolean configuration options

### ISSUE THREAD

**Issue by edlerd** [lxc/lxd#11153]
# Required information

 * lxc --version 5.8

# Issue description

When setting the `acme.agree_tos` option to false, it is listed in the `metadata.config` section of the response from a `/1.0` `GET` request to the REST API. It should not be contained in the response, as `false` is the default for the option.

After a second request to set the `acme.agree_tos` option to false, the option is not part of the  `/1.0` `GET` response anymore.

For options like `core.metrics_authentication` with a default of `true`, the behavior is as expected. So after setting it from `false` to `true` via REST API, the option vanishes from the `/1.0` `GET` response. Even after the first request of setting it to true.

# Steps to reproduce

 1. Set `acme.agree_tos` to `true` via REST API
 2. Set `acme.agree_tos` to `false` via API
 3. Query the `/1.0` `GET` endpoint. The option is part of the result, if though it should probably not be listed there.

```
curl 'https://localhost:9443/1.0' \
  -X 'PATCH' \
  --data-raw '{"config":{"acme.agree_tos":"true"}}'
```

```
curl 'https://localhost:9443/1.0' \
  -X 'PATCH' \
  --data-raw '{"config":{"acme.agree_tos":"false"}}'
```

```
curl 'https://localhost:9443/1.0' \
  -X 'GET'
```

> contains metadata":{"config":{"acme.agree_tos":"false" ...

```
curl 'https://localhost:9443/1.0' \
  -X 'PATCH' \
  --data-raw '{"config":{"acme.agree_tos":"false"}}'
```

```
curl 'https://localhost:9443/1.0' \
  -X 'GET'
```
> no trace of acme.agree_tos in the response

**Comment by tomponline** [comment]
@edlerd you mentioned this happened with other keys too?

**Comment by edlerd** [comment]
Only with this option. I suspect the reason could be, this is the only option with a default of false.

**Comment by tomponline** [comment]
@monstermunchkin fancy taking this one as this key was added with the ACME stuff you worked on? (Although might not be just that key affected mind you).
