### ISSUE TITLE
lxd.lxc-to-lxd Creating container Freeze

### ISSUE THREAD

**Issue by Rafael-Puerta** [lxc/lxd#11176]
I'm trying to migrate my old lxc container to lxd with the tool but freezes in creating container, if in another terminal i list the containers, they appear, i dont know what i do wrong.... help please.

s <- my old lxc
u1 <- new lxc created for test the tool

Distribution: ubuntu 22.04.1 LTS
![image](https://user-images.githubusercontent.com/95918532/204773381-162c4e91-a80b-4d0a-8cd0-fffb1bc0f975.png)

**Comment by tomponline** [comment]
Any ideas @monstermunchkin (I ask because IIRC you worked on this recently) ?

@Rafael-Puerta please can you enable debug mode on the LXD by doing:

```
sudo snap set lxd daemon.debug=true; sudo systemctl reload snap.lxd.daemon
```

And then run the import again and capture the contents of `/var/snap/lxd/common/lxd/logs/lxd.log` for us to look at. Thanks

**Comment by Rafael-Puerta** [comment]
> Any ideas @monstermunchkin (I ask because IIRC you worked on this recently) ?
> 
> @Rafael-Puerta please can you enable debug mode on the LXD by doing:
> 
> ```
> sudo snap set lxd daemon.debug=true; sudo systemctl reload snap.lxd.daemon
> ```
> 
> And then run the import again and capture the contents of `/var/snap/lxd/common/lxd/logs/lxd.log` for us to look at. Thanks

First of all, thanks for the help, here is the log file (maybe, the problem is im in virtual machine).
![image](https://user-images.githubusercontent.com/95918532/205582755-52f4c378-3818-4d2d-a2be-5e31c4648128.png)
![image](https://user-images.githubusercontent.com/95918532/205582902-eb745cbc-5c8e-4ff0-8f79-401e39a48389.png)
![image](https://user-images.githubusercontent.com/95918532/205583011-5821d2c6-0c0d-47a9-adc2-8cb3fef94028.png)
![image](https://user-images.githubusercontent.com/95918532/205583109-396c850a-eddd-494a-9cf1-a81c69cf3458.png)

i have lxd.log.1 but that log is older.... maybe its log of my testing failures, here is
![image](https://user-images.githubusercontent.com/95918532/205583349-f29ea1ad-d290-48b2-a8c4-b98f1a73bcfc.png)

A lot of thanks, i'm new in this things (containers)

**Comment by Rafael-Puerta** [comment]
I tried in my ssh cloud server (ubuntu 20.04.5 LTS) and... WORKED PERFECTLY
I dont know why in my virtual machine dont work... maybe the version of ubuntu , maybe because its a virtual box machine....

Well... i dont need the help now, i was testing in a virtual machine to avoid make another server to test that....
Thanks for the help, if want, can close this issue.
