### ISSUE TITLE
Does the `sriov` NIC type have a `host_name` option?

### ISSUE THREAD

**Issue by ru-fu** [lxc/lxd#11179]
The [docs](https://linuxcontainers.org/lxd/docs/latest/reference/devices_nic/#sr-iov) say:

> To tell LXD to use a specific unused VF add the `host_name` property and pass it the name of the enabled VF.

But `host_name` is not in the list of device options for NICs of type `sriov`.

Is `host_name` just missing from the list, or is the statement in the docs wrong?
And if the statement is correct and `host_name` is missing, is that feature actually working as expected and being tested?

**Comment by tomponline** [comment]
I've had a look and it doesn't appear that this is a feature anymore (if it ever was).

@stgraber is this something we want the `sriov` NIC to support (the ability to pin a NIC to a specific VF via its host interface name)?

**Comment by tomponline** [comment]
Chatted with @stgraber about this and we've come to the conclusion that the `sriov` NIC shouldn't support this option and instead if people want to use a specific VF they use `physical` NIC with `parent` set to the VF name.

@ru-fu are you OK to update the docs for this?
