### ISSUE TITLE
Unable to add per-user remotes on snap version of lxd

### ISSUE THREAD

**Issue by AnubisFUp** [lxc/lxd#11171]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-53-generic
   * LXC version: 5.0.1
   * LXD version: 5.8
   * Storage backend in use: btrfs
   * Snap Version: 5.0/stable

# Issue description

* It is not possible to add remotes from the `config.yml` configuration file in the home directory located at `~/.config/lxd/` or `~/.config/lxc/` as mentioned at [docs](https://linuxcontainers.org/lxd/docs/master/remotes/#local-per-user)
* The file specified with the environment variable `LXD_CONF` doesn't work either. Passing the `config.yml` configuration file using a variable `LXD_CONF`

# Steps to reproduce
1. Install LXD vias snap (channel=5.0/stable)
* with file:
     2. create  `config.yml` in any of this dirs: `~/.config/lxd/`, `~/.config/lxc/` 
     3. run `lxc remote ls` to see no newly added remotes
* with variable:
     2. export lxd config variable `export LXD_CONF=~/.config/lxc/config.yml`
     3. run `lxc remote ls` to see no newly added remotes

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by AnubisFUp** [comment]
I tried to reinstall(remove && install) the lxd via snap, as a result I was able to see the *remotes* from the '~/.config/lxc/config.yml' via `lxc remote ls`, but after adding new ones or changing nothing happens. 
Attempts to reboot the lxd daemon will lead to nothing. I tried both:
1) `systemctl restart snap.lxd.daemon` 
2) `systemctl reload snap.lxd.daemon`

What did I miss?

**Comment by stgraber** [comment]
With the snap, it's `~/snap/lxd/common/config/config.yml`.

**Comment by stgraber** [comment]
The reason why you saw it work once is because LXD will do a one time transfer from `~/.config/lxc` to `~/snap/lxd/common/config/` on the first run for a given user. But it's a copy so modifying the original doesn't help.

`LXD_CONF` may work but it requires an absolute path, LXD doesn't perform shell expansion when processing paths, so putting in `~/` in LXD_CONF or LXD_DIR will either lead to errors or to a fallback mode.

**Comment by AnubisFUp** [comment]
Thanks, `~/snap/lxd/common/config/` work nice!
