### ISSUE TITLE
lxd.service doesn't start at boot.

### ISSUE THREAD

**Issue by IshwarKanse** [lxc/lxd#1117]
I'm using Ubuntu 15.04 with lxd 0.18. After updating from 0.17 to 0.18 the lxd.service didn't start at boot.

systemctl status lxd.service shows:
Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)

**Comment by stgraber** [comment]
That's normal, lxd is socket activated, the daemon will start when you first connect to it.
I still need to add another unit to poke the daemon if there's any auto-started containers or if the daemon is supposed to bind to the network though.

**Comment by IshwarKanse** [comment]
I've same configuration on my laptop. Updated from 0.17 to 0.18. The systemd unit on it shows.
Loaded: loaded (/lib/systemd/system/lxd.service; enabled; vendor preset: enabled)
The service get activated on boot and container autostart works. While on my work pc the service doesn't get activated until I do something like lxc list. Both are on the stable repository.

**Comment by stgraber** [comment]
I've fixed the packaging yesterday and LXD 0.19 will contain the needed bugfixes to have activateifneeded work properly.
