### ISSUE TITLE
Lxc copy --refresh from/to zfs backed storage pool leaves @migration-xxxx zfs snapshots behind

### ISSUE THREAD

**Issue by aivanise** [lxc/lxd#11194]
as  instructed in https://discuss.linuxcontainers.org/t/lxc-copy-refresh-from-to-zfs-backed-storage-pool-leaves-migration-xxxx-zfs-snapshots-behind/15806/17 I'm opening this ticket.

how to reproduce: 

```
~$ lxc launch u20 migtest --target lxd12
Creating migtest
Starting migtest
~$ ssh lxd12 zfs list lxd12/lxd/containers/migtest -r -t all
NAME                           USED  AVAIL     REFER  MOUNTPOINT
lxd12/lxd/containers/migtest  10.3M  14.4G      645M  legacy
~$ lxc copy --refresh migtest alexsv:
~$ ssh lxd12 zfs list lxd12/lxd/containers/migtest -r -t all
NAME                           USED  AVAIL     REFER  MOUNTPOINT
lxd12/lxd/containers/migtest  10.3M  14.4G      645M  legacy
~$ lxc copy --refresh migtest alexsv:
~$ ssh lxd12 zfs list lxd12/lxd/containers/migtest -r -t all
NAME                                                                          USED  AVAIL     REFER  MOUNTPOINT
lxd12/lxd/containers/migtest                                                 10.6M  14.4G      645M  legacy
lxd12/lxd/containers/migtest@migration-b893e86b-66e6-407f-85d7-d4dab43ce20c   304K      -      645M  -
```

**Comment by aivanise** [comment]
Hmmm, I have now tried with 5.9-76c110d and while it does not leave snapshots behind any more, copy --refresh does not do incremental copy either, it starts from scratch every time, which kind of beats the purpose.

this is on a 1.5G container:

~$ time lxc copy --refresh qbs02:unifi qbs01:unifi-failover

real    0m33.019s
user    0m0.196s
sys     0m0.044s
~$ time lxc copy --refresh qbs02:unifi qbs01:unifi-failover

real    0m35.821s
user    0m0.176s
sys     0m0.057s

~$ time lxc copy --refresh qbs02:unifi qbs01:unifi-failover

real    0m34.932s
user    0m0.198s
sys     0m0.041s

however, on the same host it is as fast as it is supposed to be

~$ time lxc copy --refresh qbs02:unifi qbs02:unifi-failover

real    0m1.524s
user    0m0.148s
sys     0m0.030s
~$ time lxc copy --refresh qbs02:unifi qbs02:unifi-failover

real    0m1.560s
user    0m0.143s
sys     0m0.038s
~$ time lxc copy --refresh qbs02:unifi qbs02:unifi-failover

real    0m1.794s
user    0m0.158s
sys     0m0.024s

but it does leave a snapshot, which is to be expected

$ ssh qbs02 sudo zfs list -r -t all qbs02/lxd/containers/unifi
NAME                                                                   USED  AVAIL     REFER  MOUNTPOINT
qbs02/lxd/containers/unifi                                            1.41G   212G     1.40G  legacy
qbs02/lxd/containers/unifi@copy-f2c991e8-1b3e-4b75-a9d2-39f55fc02fea   818K      -     1.40G  -


can we please make copy --refresh between different hosts behave the same as copy --refresh on the same host?

**Comment by tomponline** [comment]
Is that a regression related to this change or a separate bug? I.e was it doing full sync before?

**Comment by tomponline** [comment]
> but it does leave a snapshot, which is to be expected

What do you mean by this? I don't follow. It shouldn't leave snapshots behind.

**Comment by aivanise** [comment]
and yes, it is definitely a regression, it was doing an incremental before.

**Comment by tomponline** [comment]
Its not supposed to leave snapshots, that's for sure.
It does differential between snapshots taken using "lxc snapshot".
The temporary snapshot it was leaving behind was part of the multi stage sync mode where it was (unnecessarily) doing 2 passes of the sync, which is what the temporary snapshot was for (and for having a consistent filesystem view for zfs send/recv). It wasnt supposed to be left behind.

Is that your understanding @monstermunchkin that optimized refresh only does differential between formal snapshots taken using lxc snapshot command?

**Comment by tomponline** [comment]
Also discussed here

https://discuss.linuxcontainers.org/t/lxc-copy-refresh-workaround-efficient-incremental-zfs-snapshot-sync-with-send-receive/10336/15?u=tomp

 https://discuss.linuxcontainers.org/t/lxc-copy-refresh-workaround-efficient-incremental-zfs-snapshot-sync-with-send-receive/10336/15?u=tomp

**Comment by aivanise** [comment]
ups, looks like you are right, on this host pair I did not have any snapshots, whereas on the others I did, so please ignore me (for now, while I test further) ;)

**Comment by tomponline** [comment]
Thanks, no worries, glad its working .
