### ISSUE TITLE
Add support for setting txqueuelen on veth based NICs

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#11198]
Add a setting for controlling veth-based NIC txqueuelen setting.

See https://discuss.linuxcontainers.org/t/setting-network-options-e-g-txqueuelen-for-all-containers-via-profile/15813

**Comment by Viktor-Yakovchuk** [comment]
Hello, I would like to do it but I want to clarify some points:
- where should new parameters be added, I mean exactly how the user will change the new settings
- what way of applying settings should be chose: maybe it is better to add new settings on creation veth device in lxc code [here](https://github.com/lxc/lxc/blob/6ab35516151209b14de75d8823ba23a0db2b89a8/src/lxc/network.c#L2074) or maybe to add it in some other place?

**Comment by Viktor-Yakovchuk** [comment]
@tomponline gentle ping

**Comment by tomponline** [comment]
This is on my list to look at soon :)

**Comment by tomponline** [comment]
> where should new parameters be added, I mean exactly how the user will change the new settings

Something like adding `txqueuelen` to the NIC device (bridge, p2p and routed) settings, e.g.

https://linuxcontainers.org/lxd/docs/master/reference/devices_nic/#nictype-bridged

E.g. `lxc config device set c1 eth0 txqueuelen=100`

**Comment by tomponline** [comment]
> * what way of applying settings should be chose: maybe it is better to add new settings on creation veth device in lxc code [here](https://github.com/lxc/lxc/blob/6ab35516151209b14de75d8823ba23a0db2b89a8/src/lxc/network.c#L2074) or maybe to add it in some other place?

Depending on whether or not we can/need to change the setting on both sides of a veth pair will indicate to us whether this setting is consider "live updatable". And if not then LXD will remove and re-add the device if that setting is changed.

E.g. https://github.com/lxc/lxd/blob/master/lxd/device/nic_bridged.go#L446-L454

For actually applying the setting I think we would just use `ip` tool.

**Comment by Viktor-Yakovchuk** [comment]
I looked on veth devices and how changing txqueuelen works:
```
sudo ip netns add myct
sudo ip link add veth10 type veth peer name veth11
sudo ip link set veth11 netns myct
sudo ip link set veth10 txqueuelen 999
```
Watch to 'ip a' to check txqueuelen and then
```
sudo nsenter --net=/run/netns/myct
ip a
```
and find, that txqueuelen is still 1000. So we need ti change this setting on both devices.
