### ISSUE TITLE
Improve error "Backup is missing index.yaml" when importing storage volume to indicate which directory it is looking for it in

### ISSUE THREAD

**Issue by slapcat** [lxc/lxd#11211]
# Required information

 * Distribution:  Ubuntu
 * Distribution version: 22.04.1 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-56-generic
   * LXC version: 5.8
   * LXD version: 5.8-bb9c9b1 (23983)
   * Storage backend in use: zfs

# Issue description

When running the command `lxc storage volume import` for a block storage device, it requires the tarball to have a folder called "backup" with `index.yaml` and `volume.img` inside it. If the entire structure and contents are the same, but the folder is named anything else, the import will fail with "Error: Backup is missing index.yaml". It seems like it specifically looks for the path `backup/index.yaml` instead of just finding the `index.yaml` file.

```bash
$ tar -tf test2.tar.gz 
test2/
test2/volume.img
test2/index.yaml
$ lxc storage volume import lxd test2.tar.gz 
Importing custom volume: 100% (496.85MB/s)Error: Backup is missing index.yaml
$
$ tar -tf test3.tar.gz 
backup/
backup/volume.img
backup/index.yaml
$ lxc storage volume import lxd test3.tar.gz 
$
```

This is an issue when attempting to import custom images as storage volumes. As far as I know, there is no documentation specifying that the folder must be called `backup`. Either this restriction should be lifted, or the requirement should be documented.

**Note:** the same issue occurs with filesystem storage volumes, but the expected directory structure is slightly different.

# Steps to reproduce

I used the process to import my own image, not an exported one, but this will cause the same error:

 1. Export the storage volume of a block device:
 ```
 lxc storage volume export lxd test
 ```
 
 2. Extract and rename the folder:
  ```
 tar -xzvf backup.tar.gz
 mv backup/ test/
 ```

 3. Compress:
  ```
 tar -czvf test.tar.gz test/
 ```
 
 4. Attempt import:
  ```
 lxc storage volume import lxd test.tar.gz
 ```

# Information to attach

Included above.

**Comment by tomponline** [comment]
The internal layout of the export file format isn't designed to be directly interacted with.
Rather is is expected to be created from using `lxc storage volume export` command.

But of-course it is possible to generate a valid export file manually.

Why is it a problem to use the correct layout that LXD expects when creating these files manually?

**Comment by slapcat** [comment]
Our use-case was migrating data disks from old Hyper-V instances over to LXD storage, so we had to craft the tarballs manually from the raw images. It took a bit of time to figure out why LXD was throwing an error about the index.yaml file when it was clearly there.

At the very least, the error message here is unclear, but it would be nice to know the required layout ahead of time to save others the time of troubleshooting this.

**Comment by tomponline** [comment]
OK we can improve the error. But the format is considered an internal representation and isn't guaranteed to stay the same.
Although because it is used for backups, we do need to support older versions.
