### ISSUE TITLE
"lxc list" has no timeout in the event of a stuck container not responding

### ISSUE THREAD

**Issue by ewildgoose** [lxc/lxd#11227]
Using LXD 5.9 on gentoo/openrc with kernel 6.0.12

I'm seeing intermittent failures where container instances stop responding on both startup/shutdown (will post separate report about this). However, once a container stops responding, then the lxd/lxc tooling also gets "stuck" and this makes recovery more difficult

Basic symptom is:
- Say container v1 is not responding
- "lxc list" will hang and not give any output
- it is still possible to start/stop instances if you know their names, but I'm not familiar enough with the tooling to otherwise know how to list instances and figure out which one is stuck

To reproduce you need a stuck container

Then observe that "lxc list" will never return any result

I can use side effects such as looking at the results from "mount" or "ps ax|grep monitor" to determine which containers are running (is there some other way?). Then I can do things such as "lxc exec instance something" to try and discover if that instance is locked up.

Interestingly, "lxc exec stuckinstance ls" will timeout after a few seconds with a "not running" or "instance in error state" message. However, "lxc list" appears to sit forever

Could the underlying implementation of "lxc list" and other tools have a timeout implemented please. Perhaps in the case of a stuck container it could show status "not responding" or similar?

**Comment by tomponline** [comment]
Please provide output of `lxc config show <instance> --expanded` along with any additional customization you are doing to the container (you mentioned bind mounts in the forum post).

Please also provide reproducer steps to getting the container "stuck" as that is very important to understand what is going on and provide a fix.

Thanks

**Comment by tomponline** [comment]
Please can you also fill in the github issue template that is asked for when opening an issue. Thanks

**Comment by tomponline** [comment]
> (will post separate report about this)

Lets keep it to one issue for now please.

**Comment by tomponline** [comment]
Related issue https://github.com/lxc/lxd/issues/11228

**Comment by ewildgoose** [comment]
It's your issue tracker, will defer to you. Feels like a separate issue to me?

I've updated the title, on further reflection, *some* of the lxc tooling has timeouts and will exit after a few seconds with some result. However, "lxc list" freezes indefinitely in the event that some container is not responding. 

Most other commands seem to timeout. Only "lxc stop" also freezes indefinitely, but I'm not sure if that's a deliberate feature?

So my bug report is:
- In the event of a misbehaving container which isn't responding, lxc list should have a timeout and return results for the remaining containers, and showing some error report for the stuck container

Is that a simple fix? (Seems like it is a handled case already in other tools?)

**Comment by stgraber** [comment]
Yeah, I think we should probably move this stuff over to a liblxc issue. It's not a new problem with the monitor being single threaded and potentially blocking when something goes wrong. It would make sense for liblxc to have some kind of timeout by default on those.

@tomponline want to file something over there, possibly assigned to @mihalicyn and then close the two LXD issues?

**Comment by tomponline** [comment]
Created https://github.com/lxc/lxc/issues/4257 for this.
