### ISSUE TITLE
Container Names With Symbols

### ISSUE THREAD

**Issue by Ziris85** [lxc/lxd#1122]
I've found that lxd will allow one to create a container name with symbols, but simply says "error: not found" when anything is attempted to be done to them. 

Some names I've tried:
>Awesome?_Name
>SWEET!
>almost_lions?

(In case you're wondering, I happened to be watching the Lions today)

Example:
```
lxc launch ubuntu Best_#1 -e
Creating Best_#1 done.
Starting Best_#1 error: not found

lxc delete Best_#1
error: not found

lxc list
+----------------+---------+------------+------+-----------+-----------+
|      NAME      |  STATE  |    IPV4    | IPV6 | EPHEMERAL | SNAPSHOTS |
+----------------+---------+------------+------+-----------+-----------+
| Awesome?_Name  | STOPPED |            |      | YES       | 0         |
| Best_#1        | STOPPED |            |      | YES       | 0         |
| SWEET!         | STOPPED |            |      | YES       | 0         |
| almost_lions?  | STOPPED |            |      | YES       | 0         |
| regular        | RUNNING | 10.0.3.140 |      | YES       | 0         |
+----------------+---------+------------+------+-----------+-----------+
```
This obviously presents a problem, since there are stopped ephemeral containers on the system now - a situation that should of course never happen. I've tried any number of single quotes, double quotes, escaping the symbols, etc...nothing allowed me to convince lxd to interact with those containers.

I'm not sure how to clean up the stopped ephemeral containers at this point, but I thought I would submit this bug so you folks would be aware of it :)

Stats of system I'm on:

```
lxc version                                                                                            
0.18

apt list lxd
Listing... Done                                                                                                                     
lxd/trusty,trusty,now 0.18-0ubuntu1~ubuntu14.04.1~ppa1 amd64 [installed]

cat /etc/lsb-release                                                                                   
DISTRIB_ID=Ubuntu                                                                                                                   
DISTRIB_RELEASE=14.04                                                                                                               
DISTRIB_CODENAME=trusty                                                                                                             
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
```
If you would like any more information that I haven't provided, let me know.

**Comment by stgraber** [comment]
LXD should enforce the following rules:
 - names to be between 1 and 63 characters long
 - made solely of alphanumerical characters and hyphens
 - name may not start with a numerical character or hyphen
 - name may not end with an hyphen

The rules above are the intersection of the hostname rules and DNS rules which are needed to get a hostname that's both valid for the kernel and for representation inside a DNS record (as can be synthesized by a dhcp server).
