### ISSUE TITLE
`limits.memory` incorrectly set `memory.low` in cgroup2

### ISSUE THREAD

**Issue by ko-zu** [lxc/lxd#11239]
# Required information

 * Distribution: Ubuntu 22.04
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-56-generic (with cgroup2, memory/swap accounting enabled by the distribution)
   * LXC version: driver_version: 5.0.1
   * LXD version: Server version: 5.9 ( snap  5.9-76c110d  24164  latest/stable/…)
   * Storage backend in use: btrfs

# Issue description

The container resource control configuration `limits.memory` sets `memory.low` in cgroup2 environment. This is not an expected behavior, I think.

From reading the configuration documents, I thought that `memory.max` would be set for hard enforcement and `memory.high` for soft *enforcement* as `memory.high` allows the kernel to reclaim memory more aggressively but does not invoke OOM killer.
However, LXD 5.9 sets `memory.low` for both of the enforcement modes. (90% of limits when hard enforcement)

The cgroup2 `memory.low` asks the kernel to protect memory from being reclaimed. It does not limit the amount of usable memory but prioritizes the usage by the container.
As it virtually limits the other processes by deprioritizing their memory, it may harm system stability if the sum of `memory.low` is too high. Note that cgroup2 `memory` includes page cache, which means that low RSS processes may still lock memory upto `memory.low` for disk io.

Because of this behavior, high `limits.memory` allocate protected memory for containers regardless of their activity. If a user considers this param as just an upper bound and set for safety against malloc-bomb, it may cause an adverse effect.

I think the following change would be expected.
soft: memory.max=max, memory.high=limits.memory
hard: memory.max=limits.memory
 (not touch memory.low for both)

# Steps to reproduce

Limit memory and check respective cgroup2 settings.
```
lxc config set cname limits.memory=512MB
lxc config set cname limits.memory.enforce=hard
grep . /sys/fs/cgroup/lxc.payload.*/memory.{low,high,max}

/sys/fs/cgroup/lxc.payload.cname/memory.low:460800000
/sys/fs/cgroup/lxc.payload.cname/memory.high:max
/sys/fs/cgroup/lxc.payload.cname/memory.max:512000000
```
for soft.
```
lxc config set cname limits.memory.enforce=soft
grep . /sys/fs/cgroup/lxc.payload.*/memory.{low,high,max}

/sys/fs/cgroup/lxc.payload.cname/memory.low:512000000
/sys/fs/cgroup/lxc.payload.cname/memory.high:max
/sys/fs/cgroup/lxc.payload.cname/memory.max:max
```

Workaround to get expected result, remove the limits and put raw config, then restart.
```
raw.lxc: lxc.cgroup2.memory.max = 512000000
or
raw.lxc: lxc.cgroup2.memory.high = 512000000
```

# Information to attach

ref: https://www.kernel.org/doc/Documentation/admin-guide/cgroup-v2.rst

**Comment by tomponline** [comment]
Any thoughts on this @stgraber @mihalicyn ?

**Comment by tomponline** [comment]
@mihalicyn I've assigned this one to you just for now to look into what you think should be the correct behaviour, is that OK?

**Comment by mihalicyn** [comment]
Thanks @tomponline !

Yes, I agree with this rationale from @ko-zu
I'll prepare PR for lxd
