### ISSUE TITLE
lxc config problem

### ISSUE THREAD

**Issue by antitoine** [lxc/lxd#1123]
Hi,

I try to set the listen on IPv4 port 8443 with the command :
```lxc config set core.https_address [::]:8443```
But after entering a bad address and restart daemon lxd, it can't restart and it's impossible to change again this value. Every command (lxc list, lxc config ...) display an error :
```error: Get http://unix.socket/1.0/containers?recursion=1: dial unix ///var/lib/lxd/unix.socket: connect: connection refused```

The only way i found to fix it, it's to delete or update the config table in the sqlite file (lxd.db).

The daemon is required to use ```lxc config set``` ?

**Comment by stgraber** [comment]
Yes, "lxc config set" talks to the daemon over the unix socket.

What version of LXD are you using and on what Ubuntu release (if Ubuntu) and how did you restart LXD?

Also note that you don't have to restart lxd after setting core.https_address, the daemon will immediately start listening when this is set.

**Comment by antitoine** [comment]
LXD 0.18 on Ubuntu Trusty (14.04).
I restart lxd with the service command : ```service lxd restart```

**Comment by stgraber** [comment]
what do you have in /var/log/upstart/lxd.log?

**Comment by antitoine** [comment]
I have this error :
```error: cannot listen on https socket: listen tcp 78.192.XXX.XXX:8443: bind: cannot assign requested address```

**Comment by stgraber** [comment]
that doesn't match what you said in the bug report, in the bug report you said you set it to "[::]:8443", here it looks like you actually set it to "78.192.xxx.xxx:8443" which presumably isn't bindable on your host, leading to that failure.

**Comment by stgraber** [comment]
oops, didn't mean to close the issue

**Comment by antitoine** [comment]
Ah yes, sorry, I expressed myself badly, I copied the command help.
Indeed, I have entered an IP address.
The problem is that if the given configuration is not good, on reboot, then it is impossible to reconsider this configuration because the daemon doesn't work.

**Comment by stgraber** [comment]
Yeah, we definitely shouldn't be failing hard at startup if an address can't be bound.
What's also weird is that it should have failed the "lxc config set"... not sure why that one succeeded.
