### ISSUE TITLE
Stopping conatiner hangs

### ISSUE THREAD

**Issue by gozssky** [lxc/lxd#11233]
# Required information

 * Distribution: CentOS
 * Distribution version: 7
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.10.0-957.el7.x86_64
   * LXC version: 5.3
   * LXD version: 5.3
   * Storage backend in use: lxm

# Issue description

I want to stop some containers, but the operation seems to hang forever. Now I have no way to connect to the container. I noticed that log shows:
```
2022-12-19T15:32:06+08:00 lxd.daemon[3641763]: time="2022-12-19T15:32:06+08:00" level=error msg="Error calling 'lxd forknet" err="Failed to run: /snap/lxd/current/bin/lxd forknet info -- 2559000 -1: Failed setns to container network namespace: No such file or directory" instance=jinling-lingjin-4 instanceType=container pid=2559000 project=tispace
```
It seems there is something wrong with network namespace.

When I list instances. The result shows containers are running. But I was unable to stop or force delete them.
```
[root@KS-14 ~]# lxc ls jinling
+-------------------+---------+------+------+-----------+-----------+----------+
|       NAME        |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS | LOCATION |
+-------------------+---------+------+------+-----------+-----------+----------+
| jinling-lingjin-1 | RUNNING |      |      | CONTAINER | 0         | ks-14    |
+-------------------+---------+------+------+-----------+-----------+----------+
| jinling-lingjin-4 | RUNNING |      |      | CONTAINER | 0         | ks-14    |
+-------------------+---------+------+------+-----------+-----------+----------+
| jinling-lingjin-7 | RUNNING |      |      | CONTAINER | 0         | ks-14    |
+-------------------+---------+------+------+-----------+-----------+----------+
```

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 ```
[root@KS-14 ~]# lxc info jinling-lingjin-4 --show-log
Name: jinling-lingjin-4
Status: RUNNING
Type: container
Architecture: x86_64
Location: ks-14
PID: 2559000
Created: 2022/12/14 15:34 CST
Last Used: 2022/12/14 15:35 CST

Resources:
  Processes: 3
  Disk usage:
    root: 1.32GiB
  CPU usage:
    CPU usage (in seconds): 146
  Memory usage:
    Memory (current): 19.34MiB
    Memory (peak): 584.81MiB

Log:
```
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by leliuga** [comment]
@gozssky did you solve this issue? if no, please provide more data and logs (dmesg and /var/log/lxd/lxd.log)

**Comment by leliuga** [comment]
Hello @stgraber out of topic question. Why this repo not using [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) it's more easy way to submit issue

**Comment by gozssky** [comment]
Hi @leliuga, I have solved this issue by restarting the host. I will close this issue and provide more details if I encounter this problem again in the future.

**Comment by leliuga** [comment]
Hello @gozssky great :)
