### ISSUE TITLE
 curl/git don't work properly inside an lxd container on wsl/ubuntu instance and disconnects frequently

### ISSUE THREAD

**Issue by phr34k** [lxc/lxd#11246]
Using curl inside the lxd container to download an (large) network resource has peer disconnects, whereas running it outside the lxd container nothing happens and curl finishes nicely.  

# Required information

Ubuntu 22.10
Kernel (5.15.79.1)
Snapcraft (7.2.9.post31+git31a3990c)
LXD (5.9-76c110d)
curl (7.81.0)

# Issue description

The issue is intermittant, but when run inside the lxd container curl and git terminate the download due to a peer disconnected error. The behavior seems affected by the internet connection i.e. some wireless networks the problem doesn't occur at all, on others the problem always occurs.

# Steps to reproduce

Use snapcraft (https://snapcraft.io/docs/snapcraft-yaml-reference) and run command(s) inside the (lxd-)container that fetches a large resource from internet such as git clone or flutter precache (invokes curl to download the flutter sdk and dart sdk ). For more details see: https://stackoverflow.com/questions/74989653/how-to-fix-unstable-network-for-lxc-lxd-container-that-causes-curl-git-commands

**Comment by tomponline** [comment]
Hi, this is most likely an environmental issue, rather than a bug, so please re-post over at https://discuss.linuxcontainers.org/ and we'll take a look at your setup and see what is going wrong. Thanks

**Comment by phr34k** [comment]
moved to here: https://discuss.linuxcontainers.org/t/curl-git-dont-work-properly-inside-an-lxd-container-on-wsl-ubuntu-instance-and-disconnects-frequently/16036
