### ISSUE TITLE
Empty Image list

### ISSUE THREAD

**Issue by Nerus87** [lxc/lxd#11240]
# Required information

 * Distribution: ubuntu 
 * Distribution version: 22.04 (jammy)
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.1.0-x64v1-xanmod1
   * LXC version: 5.4.1
   * LXD version: 5.4.1
   * Storage backend in use:

# Issue description

lxc image list empty

**Comment by monstermunchkin** [comment]
`lxc image list` will always be empty if you don't have any images stored locally.

**Comment by tomponline** [comment]
To see available images you need to specify a remote, e.g.

For the LXD provided images use:

```
lxc image list images:
```

For Official Ubuntu images used:

```
lxc image list ubuntu:
```
