### ISSUE TITLE
activateifneeded commandline option panics lxd

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1125]
The systemd service lxd-startup.service contains the commandline option activateifneeded:

```
[Service]
Type=oneshot
ExecStart=/usr/bin/lxd activateifneeded
TimeoutSec=30s
```

However, this causes lxd to panic at bootup:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4b6e94]

goroutine 1 [running]:
main.(*containerLXD).mkdirAllContainerRoot(0xc8200f62d0, 0xc8200ebe00, 0x26, 0x1ed, 0x0, 0x0)
        /build/lxd-Qwev5E/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/container.go:1854 +0x64
main.(*containerLXD).mountShared(0xc8200f62d0, 0x0, 0x0)
        /build/lxd-Qwev5E/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/container.go:1869 +0x250
main.(*containerLXD).init(0xc8200f62d0, 0x0, 0x0)
        /build/lxd-Qwev5E/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/container.go:566 +0x1609
main.containerLXDLoad(0xc820093b80, 0xc8200e0490, 0x10, 0x0, 0x0, 0x0, 0x0)
        /build/lxd-Qwev5E/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/container.go:421 +0x85c
main.doContainerGet(0xc820093b80, 0xc8200e0490, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /build/lxd-Qwev5E/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/containers_get.go:61 +0x7d
main.doContainersGet(0xc820093b80, 0xc27201, 0x0, 0x0, 0x0, 0x0)
        /build/lxd-Qwev5E/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/containers_get.go:45 +0x6ba
main.activateIfNeeded(0x0, 0x0)
        /build/lxd-Qwev5E/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/main.go:269 +0x285
main.run(0x0, 0x0)
        /build/lxd-Qwev5E/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/main.go:106 +0xe0d
main.main()
        /build/lxd-Qwev5E/lxd-0.18/dist/src/github.com/lxc/lxd/lxd/main.go:41 +0x24

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
database/sql.(*DB).connectionOpener(0xc820091ea0)
        /usr/lib/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
        /usr/lib/go/src/database/sql/sql.go:481 +0x336
```

Version detail:
Running latest test version of Ubuntu 15.10

lxc 1.1.3-0ubuntu1 amd64
lxd 0.18-0ubuntu2 amd64

**Comment by stgraber** [comment]
I've never seen this happen in testing but that may depend on the backing store being used and on whether LXD was ever started before (though package install does start LXD so that shouldn't really be possible).

**Comment by jsimonetti** [comment]
Lxd was started before. So that can't be it.

I did this in a virtual machine testing some stuff.
What I did was the folowing (roughly, i probably am forgetting some steps)

- install minimal 15.10 from netinstall mini.iso
- create new btrfs subvolume named @lxc on dedicated raid6 btrfs disks
- mkdir /var/lib/lxd
- created fstab entry to mount said subvol on /var/lib/lxd (and mount it)
- apt-get install lxd (from wily repos)
- added images.linuxcontainer.org as remote
- lxc launch images.linuxcontainer.org:ubuntu/trusty/amd64 testct
- wait till testct was finished starting
- reboot the host (with the container still running)

After reboot lxd paniced. I removed the activateifneeded parameter from execstart, manually started lxd with systemctl start lxd.service (wich resulted in the testct container starting). I then rebooted the system and it now appears tot be working correctly except for an error message that lxd couldn't bind because it was allready in use.

I have access to the host again tomorrow and can give some additional information if needed.

**Comment by stgraber** [comment]
reproduced the crash

**Comment by stgraber** [comment]
I believe I accidentally fixed this on Friday actually. Testing with a current git build.

**Comment by stgraber** [comment]
Confirmed, current git master doesn't suffer from this anymore.

I'll contribute a test though so we don't accidentally regress this.
