### ISSUE TITLE
Work toward better OpenSSF Best Practices badge

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#11260]
Currently, LXD meets all the criteria to obtain the [passing](https://bestpractices.coreinfrastructure.org/en/projects/1086) badge. When checking the criteria to meet the [silver](https://bestpractices.coreinfrastructure.org/en/projects/1086?criteria_level=1) badge, it seems that most of them only need to be filled out as we already apply those best practices. Same goes for the [gold](https://bestpractices.coreinfrastructure.org/en/projects/1086?criteria_level=2) badge.

As of today, LXD compliance level with the 3 badges is:

Passing: 100%
Silver: 13%
Gold: 17%

**Comment by stgraber** [comment]
I've updated our responses now though that still doesn't clear us for anything but passing.
There are some no-go items in both silver and gold so we're unlikely to ever qualify.

**Comment by simondeziel** [comment]
Thanks @stgraber! Just for the record, here are the new compliance levels:

Passing: 100%
Silver: 80%
Gold: 30%
