### ISSUE TITLE
Juju 2.9 failing to deploy lxd containers with lxd latest/stable as lxd version 5.x is promoted to latest/stable

### ISSUE THREAD

**Issue by dparv** [lxc/lxd#11265]
As mentioned in https://juju.is/docs/olm/lxd juju 2.9 only works with lxd 4.x and juju 3.x works with lxd 5.x.

Current deployments that haven't upgraded to 3.x will have issues deploying new containers as the default value for juju model-config lxd-snap-channel is "latest/stable"

Workaround to fix this is to change juju model-config lxd-snap-channel="4.0/stable" and sudo snap remove lxd on the affected machines, as snap lxd downgrades are not supported.

Juju should be able to detect that it is running 2.9 and not 3.x and deploy the latest working lxd snap on the new machines, or at least warn (even better error out) if the user tries to deploy containers with lxd-snap-channel pointing to latest/stable that has 5.x promoted.

Another important point here is, if you set to 4.0/stable and add a container to a machine that already has containers running juju will try to downgrade lxd and break all existing containers:

t=2023-01-09T11:59:33+0000 lvl=eror msg="Failed to start the daemon" err="Error creating database: schema version '43' is more recent than expected '42'"
Error: Error creating database: schema version '43' is more recent than expected '42'
=> LXD failed to start

So the workaround for new machines would be to set to 4.0/stable, snap remove lxd, add new container so that juju can properly configure netplan and then rollback to latest/stable and during this time you should not add any containers to machines already hosting live containers.

Juju tracking this: https://bugs.launchpad.net/juju/+bug/2002309

We need a downgrade procedure from lxd 5 to lxd 4.

Edit: Additionally if running with the workaround and adding containers that don't have all juju spaces/bindings and reverting to latest/stable to be sure you don't break anything else on machines that already have containers deployed, you can't add that new container as the networking API will fail to configure netplan and the only way is to delete all containers and re-do them.

**Comment by stgraber** [comment]
Closing as while unfortunate, none of this sounds like a LXD issue.
LXD cannot be downgraded and it's not something we plan on ever supporting.

A manual alternative is to export all your containers, reset the system and re-import them afterwards.

**Comment by dparv** [comment]
For anyone landing here: issue was observes with juju 2.9.22, seems juju 2.9.37 already has fixes to work with 5.0/stable and 5.9/stable (current versions: 5.9-9879096). But best keep it to 5.0/stable until an upgrade to juju 3.x
