### ISSUE TITLE
Live migration fail with "Error transferring container data: migration failed 1"

### ISSUE THREAD

**Issue by Mutahar789** [lxc/lxd#11281]
# Required Information
- Distribution: Ubuntu 18.04
- Kernel version: 4.15.0-187-generic
- LXD version: 3.0.3
- Storage backend in use: dir (also tried with btrfs, same error)

# Issue description
Live migration of container (busybox 1.34.1 image) end up with the following error:
`Error transferring container data: migration failed 1`

`/var/log/lxd/lxd.log` and `/var/log/lxd/test/lxc.log` attached
[var_log_lxd_lxd.log](https://github.com/lxc/lxd/files/10406081/var_log_lxd_lxd.log)
[var_log_lxd_test_lxc.log](https://github.com/lxc/lxd/files/10406082/var_log_lxd_test_lxc.log)

# Steps to reproduce
Basic installation of lxd and criu using apt
Migrating running container using `lxc move` or `lxc copy` command
(Migration after stopping container works fine)

**Comment by tomponline** [comment]
CRIU doesnt really work with recent full system containers as its very picky about what is running inside it and what device types are being used (even just veth NICs). 

There needs to be some work on the upstream project first to better support LXD containers. We have plans to investigate and contribute changes where possible.

However you are using a version of LXD that is in security maintenance only and thus will not be receiving bug fixes at this point. You would need to be on LXD 5.0 LTS to receive all bug fixes in the future.
