### ISSUE TITLE
lxd + vivid + 4.3.0-rc2 containers fail to start

### ISSUE THREAD

**Issue by tim-seoss** [lxc/lxd#1128]
Hi,

Don't know if this is a bug in lxc, lxd, or the upstream kernel (or none of the above), but I've been trying to debug a (hopefully) unrelated issue of lockups on a server running vivid amd64, and I found that lxd managed containers fail to start with a 4.3.0-rc2 kernel (4.2.0 works tho').  Failing kernel package:

http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.3-rc2-unstable/linux-image-4.3.0-040300rc2-generic_4.3.0-040300rc2.201509201830_amd64.deb

I also verified this with a kernel build I made yesterday (similar, but .config derived from 4.2.0 and with some lock debugging options turned on).  In both cases, the kernel passed lxc-checkconfig

lxc               1.1.3-0ubuntu 
lxd               0.18-0ubuntu2 

Didn't try lxd git yet.

Tim.

Sep 23 09:12:32 magic kernel: [ 2550.981007] audit: type=1400 audit(1442995952.168:22): apparmor="STATUS" operation="profile_load" name="lxd-agent57" pid=8026 comm="apparmor_parser"
Sep 23 09:12:33 magic kernel: [ 2552.026444] device vethAT3YXR entered promiscuous mode
Sep 23 09:12:33 magic kernel: [ 2552.026775] IPv6: ADDRCONF(NETDEV_UP): vethAT3YXR: link is not ready
Sep 23 09:12:33 magic systemd-udevd[8042]: Could not generate persistent MAC address for vethS6FCMG: No such file or directory
Sep 23 09:12:33 magic systemd[1]: Started ifup for vethAT3YXR.
Sep 23 09:12:33 magic systemd[1]: Starting ifup for vethAT3YXR...
Sep 23 09:12:33 magic systemd[1]: Started ifup for vethS6FCMG.
Sep 23 09:12:33 magic systemd[1]: Starting ifup for vethS6FCMG...
Sep 23 09:12:33 magic systemd[1]: Stopping ifup for vethS6FCMG...
Sep 23 09:12:33 magic sh[8090]: Unknown interface vethAT3YXR
Sep 23 09:12:33 magic kernel: [ 2552.109063] eth0: renamed from vethS6FCMG
Sep 23 09:12:33 magic sh[8091]: Unknown interface vethS6FCMG
Sep 23 09:12:33 magic ifdown[8095]: /sbin/ifdown: interface vethS6FCMG not configured
Sep 23 09:12:33 magic systemd[1]: Stopped ifup for vethS6FCMG.
Sep 23 09:12:33 magic kernel: [ 2552.272178] br0: port 3(vethAT3YXR) entered disabled state
Sep 23 09:12:33 magic kernel: [ 2552.274096] device vethAT3YXR left promiscuous mode
Sep 23 09:12:33 magic kernel: [ 2552.274099] br0: port 3(vethAT3YXR) entered disabled state
Sep 23 09:12:33 magic systemd[1]: Stopping ifup for vethAT3YXR...
Sep 23 09:12:33 magic systemd[1]: Stopped ifup for vethAT3YXR.
Sep 23 09:12:33 magic ifdown[8203]: /sbin/ifdown: interface vethAT3YXR not configured

**Comment by stgraber** [comment]
Might very well be due to missing Ubuntu changes in those mainline builds, specifically related to AppArmor.

**Comment by tim-seoss** [comment]
OK, that makes sense - I'll try and confirm this.

**Comment by tim-seoss** [comment]
Yes, this appears to be the issue.

However , I couldn't see this documented anywhere, and similarly it would be difficult to reach the correct conclusion with the error messages which lxd produces...  Should I open a bug for error reporting / docs?

**Comment by stgraber** [comment]
well, the main issue is that LXD doesn't get that info reported back from LXC so not much we can automatically do :)

**Comment by stgraber** [comment]
Might be worth covering in a new specs/requirements.md document
