### ISSUE TITLE
Dnsmasq version number parsing depends on env variables

### ISSUE THREAD

**Issue by ppepos** [lxc/lxd#11294]
# Required information

 * Distribution: Arch
 * Distribution version: Rolling
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.1.6-arch1-1
   * LXC version: 5.10
   * LXD version: 5.10
   * Storage backend in use: btrfs 6.1.2

# Issue description

Cannot parse `dnsmasq` version number if LANGUAGE environment variable is set. I know you even run `dnsmasq` with a specific locale when trying to parse the version number but `dnsmasq` seems convoluted with its locale priorities. This is linked to #6111. Setting `LANG=C.UTF-8` does not work with dnsmasq as it does not ship with that locale file.

# Steps to reproduce

Most basic example.

```bash
$ env -i LANGUAGE=en:fr LANG=C.UTF-8 dnsmasq --version
Version de Dnsmasq 2.88  Copyright (c) 2000-2022 Simon Kelley
...

Ce logiciel est fourni sans AUCUNE GARANTIE.
```

This happens because `dnsmasq` does not ship with a C.UTF-8 locale. When it cannot find the specified locale, it falls back to default, the builtin english after trying other environment variables specifying the locale. Dnsmasq actually uses all four `LANG`, `LANGUAGE`, `LC_ALL`, `LC_MESSAGES` with quirky priorities. 

The expected behaviour would be the one you get when running with LANG=C

```bash
$ env -i LANGUAGE=en:fr LANG=C dnsmasq --version
Dnsmasq version 2.88  Copyright (c) 2000-2022 Simon Kelley
...

This software comes with ABSOLUTELY NO WARRANTY.
```

# Information to attach

I have sent the quirk to the dnsmasq mailing list. For more info on what I have reported, here is the verbatim report.

>I have noticed that when setting the LANGUAGE environment variable, dnsmasq looks for the right locale for messages in `usr/share/locale/XXXX/LC_MESSAGES/`. 
Using `LANGUAGE=en`, shows messages in english, which is the appropriate behaviour but not for the right reasons. It actually looks in `usr/share/locale/en/LC_MESSAGES/dnsmasq.mo` and doesn't find anything, then falls back to default, english.
>
>Using a locale of multiple languages with english as priority will not work. `LANGUAGE=en:fr` will look for the english locale and fail, look for french and succeed. Even though english should be chosen in priority but the result is french.
>
>An example:
>```
>$ env LANGUAGE=en:fr dnsmasq --version
>Version de Dnsmasq 2.88  Copyright (c) 2000-2022 Simon Kelley
> Options à la compilation IPv6 GNU-getopt .......```

**Comment by tomponline** [comment]
So we should clear `LANGUAGE` from the environment when we run dnsmasq for version detection?

**Comment by tomponline** [comment]
Or set it explicitly to english
