### ISSUE TITLE
Killing a hanging container results in lock, "Instance is busy running a "stop" operation"

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxd#11300]
lxd v51
Ubuntu Jammy

We had a hanging container and could not do lxc stop --force. We tried killing the lxc monitor process, which then allowed us to stop the container. However, any subsequent operations resulted in a `Instance is busy running a "stop" operation` message.

What's bizarre is that lxd would let us delete the instance. Once deleted however, some lock is still remaining and the zfs storage volume is still in use/locked

```
# lxc stop --force idebureauet
lxError: Instance not found
root@leeta:/home/master# lxc init ubuntu:focal idebureauet
Creating idebureauet
Error: Failed instance creation: Failed creating instance record: Instance is busy running a "stop" operation

```
We tried dumping the database but we see no references to the instance there. What is keeping a lock on this container and how can we clean it up?

Thanks :)

**Comment by tomponline** [comment]
> lxd v51

Which version of LXD?

**Comment by tomponline** [comment]
No worries. You'll need to reload the LXD process (not the instances) to clear the locks.

By the way LXD 5.1 is quite old now and is one of the monthly releases which means its not supported from the point that the next monthly release is out. This means its not getting bug or security fixes.

We're now on LXD 5.10 for the monthly releases, which is the one currently getting support.
Or you can use the LXD 5.0.x LTS release.

Are you able to reproduce the issue on LXD 5.10, as there have been quite a few fixes related to instance lifecycle and locking over the last 9 releases.

If so let us know and we'll investigate, but for now, as this is occurring on an unsupported version I'll close this case.
Thanks

**Comment by tomponline** [comment]
Also here is a couple of links about the different snap channels we have and their support levels:

https://discuss.linuxcontainers.org/t/managing-the-lxd-snap/8178
https://linuxcontainers.org/lxd/docs/master/explanation/security/#supported-versions

**Comment by webdock-io** [comment]
Oh I see. Great! I'll give it a spin tomorrow and hopefully nothing blows up. I'll report back here with my results.

**Comment by webdock-io** [comment]
We try and avoid upgrading LXD unless we need to do a system reboot anyway as uptime is essential for us and our clients. So that's why we sometimes get into slightly weird version numbers. We always pull from --channel=latest/stable but maybe we should just start sticking to the latest LTS release

In any case `systemctl reload snap.lxd.daemon` released all locks as promised and we could recreate the server. Awesome. Thanks for the help here.

**Comment by tomponline** [comment]
Yes if you want a slower moving release channel then `5.0/stable` LTS is for you, as it will still get bug and security fixes but not new features.

Although you cannot downgrade from LXD 5.x to LXD 5.0.x channels so would need to be a fresh installation.
