### ISSUE TITLE
raw.mount.options not accepted in block device mount of ext4 disk device

### ISSUE THREAD

**Issue by chuckolboy** [lxc/lxd#11303]
# Required information

 * Distribution:  debian bullseye in both host and container
 * Distribution version:   debian 11.6, lxd 5.0.1 from snap stable channel (since 5.02 has not yet transitioned from candidate to stable)
   Not using shiftfs or any id mapping (files in the to-be-mounted partition have ownership 1001001 for access by user 1001 in the container)
 * The output of "lxc info" 
[output_of_lxc_info.txt](https://github.com/lxc/lxd/files/10476534/output_of_lxc_info.txt)

# Issue description
Trying to add (to a container instance) a disk device to do a block device mount of the host's existing ext4 partition `/dev/sda10`

`/dev/sda10` is not mounted in the host to maintain isolation between host and container

When `lxc config device add` specifies `raw.mount.options=nosuid`, it fails with this error message:
```
Error: Failed to start device "blockmount": Unable to mount "/proc/self/fd/54" at "/var/snap/lxd/common/lxd/devices/test-raw-mount-options/disk.blockmount.mountpoint" with filesystem "ext4": invalid argument
```
At this point, dmesg output from the host's kernel shows
```
EXT4-fs (sda10): Unrecognized mount option "nosuid" or missing value
```
But if I try a mount with the same options directly _on the host_, it works fine:
```
mount -o nosuid  /dev/sda10  /mnt/sda10
findmnt 
...
/mnt/sda10           /dev/sda10       ext4        rw,nosuid,relatime
 ...
```

# Steps to reproduce

1. Host needs to have an existing ext4 partition (which I'll call `/dev/sdaN`)

2. `/dev/sdaN` should _not_ be mounted in the host.

3. Launch a (non-cloud) container instance, named e.g., `test-raw-mount-options`

4. As root in the instance
                  `mkdir /mountpoint`
  and keep the instance running.

5. In the host,
```
lxc config device add test-raw-mount-options blockmount disk source=/dev/sdaN  path=/mountpoint  raw.mount.options=nosuid 
```
6. You've reproduced the issue if you then see an error message similar to this:
```
Error: Failed to start device "blockmount": Unable to mount "/proc/self/fd/54" at "/var/snap/lxd/common/lxd/devices/test-raw-mount-options/disk.blockmount.mountpoint" with filesystem "ext4": invalid argument
```
and dmesg output similar to this:
```
EXT4-fs (sda10): Unrecognized mount option "nosuid" or missing value
```

_To further reproduce_, replace `raw.mount.options=nosuid` in the `lxc config device add` commmand above with any of the following;
```
raw.mount.options=nodev
raw.mount.options=noexec
raw.mount.options=relatime
raw.mount.options=ro
raw.mount.options=rw
```
In my tests, each of the above lines resulted in a similar error message and similar dmesg output as the initial test above.

This issue seems to be specific to the `raw.mount.options` property. That is, if `raw.mount.options=nosuid` in the `lxc config device add` commmand above is replaced with:
```
readonly="true"
```
then the mount works fine,as shown by this line from the output of `findmnt` in the instance:
```
/mountpoint                       /proc/self/fd/35       ext4       ro,relatime
```
Similarly, the mount works fine for `readonly="false"`

# Information to attach
 
- [ ] Any relevant kernel output (`dmesg`)
[output_of_dmesg_tail-25.txt](https://github.com/lxc/lxd/files/10476636/output_of_dmesg_tail-25.txt)

 - [ ] Container log (`lxc info NAME --show-log`)
[output_of_lxc_info_test-raw-mount-options--show-log.txt](https://github.com/lxc/lxd/files/10476622/output_of_lxc_info_test-raw-mount-options--show-log.txt)

 - [ ] Container configuration (`lxc config show NAME --expanded`)
[container_config--expanded.txt](https://github.com/lxc/lxd/files/10476643/container_config--expanded.txt)

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
[lxd.log](https://github.com/lxc/lxd/files/10476715/lxd.log)

 - [ ] Output of the client with --debug
[output_of_device_add_using_nosuid.txt](https://github.com/lxc/lxd/files/10476668/output_of_device_add_using_nosuid.txt)
[output_of_device_add_using_nodev.txt](https://github.com/lxc/lxd/files/10476671/output_of_device_add_using_nodev.txt)
[output_of_device_add_using_noexec.txt](https://github.com/lxc/lxd/files/10476672/output_of_device_add_using_noexec.txt)
[output_of_device_add_using_relatime.txt](https://github.com/lxc/lxd/files/10476673/output_of_device_add_using_relatime.txt)
[output_of_device_add_using_ro.txt](https://github.com/lxc/lxd/files/10476674/output_of_device_add_using_ro.txt)
[output_of_device_add_using_rw.txt](https://github.com/lxc/lxd/files/10476675/output_of_device_add_using_rw.txt)

 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
[output_of_lxc_monitor--debug.txt](https://github.com/lxc/lxd/files/10476679/output_of_lxc_monitor--debug.txt)

**Comment by tomponline** [comment]
Thanks, I've reproduced this issue and looking a fix now.
