### ISSUE TITLE
Can't start/create VMs on LXD 5.9, can on 5.8

### ISSUE THREAD

**Issue by gpl** [lxc/lxd#11301]
# Required information

 * Distribution: nixos
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 5.9
   * LXD version: 5.9
   * Storage backend in use: dir

# Issue description

Can't launch virtual machines on at least x86_64/amd64 machines when using 5.9.

# Steps to reproduce

lxc launch ubuntu --vm

fails, look at log:
level=error msg="Unable to run feature checks during QEMU initialization: exit status 1"

we think it might be related to the change in #11254? 

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
Please check if still an issue on lxd 5.10 as there were several fixes related to vm support detection.
