### ISSUE TITLE
image types steal aliases from each other

### ISSUE THREAD

**Issue by hadmut** [lxc/lxd#11316]
Using LXD from snap channel 5.10/stable:

when downloading (lxc copy ubuntu:..  local: ... --copy-aliases) both the container and the virtual image, lxc image list does not show the alias for other than the first, because it (falsely) detects alias collision:

 lxc image list                    
+------------------------+--------------+--------+---------------------------------------------+--------------+-----------------+----------+-------------------------------+
|         ALIAS          | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 | ARCHITECTURE |      TYPE       |   SIZE   |          UPLOAD DATE          |
+------------------------+--------------+--------+---------------------------------------------+--------------+-----------------+----------+-------------------------------+
| j (11 more)            | bd528c90d20d | yes    | ubuntu 22.04 LTS amd64 (release) (20230107) | x86_64       | VIRTUAL-MACHINE | 603.19MB | Jan 29, 2023 at 12:29am (UTC) |
+------------------------+--------------+--------+---------------------------------------------+--------------+-----------------+----------+-------------------------------+
|                        | ed7509d7e83f | yes    | ubuntu 22.04 LTS amd64 (release) (20230107) | x86_64       | CONTAINER       | 432.03MB | Jan 7, 2023 at 1:43pm (UTC)   |
+------------------------+--------------+--------+---------------------------------------------+--------------+-----------------+----------+-------------------------------+

The alias column of the second row is empty, although there is no other container with the same aliases, just the virtual-machine. 

It's rather cosmetical, because using it seems to work.

**Comment by stgraber** [comment]
That's normal. LXD image servers cannot have the same alias applied to two images.

That's different from simplestreams servers like the source image server here where it is possible to have two image with the same aliases, letting the client figure out which one it wants to get.

This is the same design different as is described in https://github.com/lxc/lxd/issues/6881

In your case, LXD will simply set the aliases on whichever image is copied last.
If you're copying with the intent to launch from the original source path, then you don't need to copy the aliases at all.
If you do need aliases, then I'd recommend you don't copy them but instead use --alias to set an alias on each image.
