### ISSUE TITLE
High Response Time & Low Transaction Numbers on LXC above kernel version 5.4

### ISSUE THREAD

**Issue by speedrunzz** [lxc/lxd#11314]
# Required information

 * Distribution:  Ubuntu Focal Fossa
 * Distribution version: Ubuntu 20.04.3 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.13
   * LXC version: 5.0.1
   * LXD version: 5.0.1
   * Storage backend in use: ZFS

# Issue description

There is a noticeable performance regression on Kernel 5.8, 5.11, 5.13 and 5.15 versus kernel 5.4 when running LXC containers with apps using php like WordPress.

# Steps to reproduce
1) Create a container with NGINX (cache disabled), MariaDB, PHP. Install default WordPress and configure its wp-config.php to accept any urls using the parameters below.

define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);

2) Clone the containers into 100+ (or any number that your machine type can handle).
3) Generate the list of containers along with their internal IP with the sample format: http://internalip/
The list should have a sample content below.

http://10.0.1.2/
http://10.0.1.3/ (and so on)

4) Run siege using the sample command below. (we're using a machine with 30 CPUs so we matched it with siege).
`siege -c 30 -b -t 60S -f urls.txt`

Here are the results when I benchmarked it with different kernel versions and you can see that 5.4 is way faster than other kernel versions.

# Kernel 5.4.0-1093-gcp
Transactions:                       28261 hits
Availability:                      100.00 %
Elapsed time:                       59.21 secs
Data transferred:              103.85 MB
Response time:                        0.06 secs
Transaction rate:              477.30 trans/sec
Throughput:                        1.75 MB/sec
Concurrency:                       29.91
Successful transactions:       28261
Failed transactions:                   0
Longest transaction:                0.38
Shortest transaction:                0.00

# Kernel 5.8.0-1039-gcp
Transactions:		       20052 hits
Availability:		      100.00 %
Elapsed time:		       59.71 secs
Data transferred:	       73.68 MB
Response time:		        0.09 secs
Transaction rate:	      335.82 trans/sec
Throughput:		        1.23 MB/sec
Concurrency:		       29.87
Successful transactions:       20052
Failed transactions:	           0
Longest transaction:	        0.56
Shortest transaction:	        0.00

# Kernel 5.13.0-1033-gcp
Transactions:               9368 hits
Availability:             100.00 %
Elapsed time:              59.70 secs
Data transferred:          34.42 MB
Response time:              0.19 secs
Transaction rate:         156.92 trans/sec
Throughput:             0.58 MB/sec
Concurrency:               29.79
Successful transactions:        9368
Failed transactions:               0
Longest transaction:            2.13
Shortest transaction:           0.00

# Kernel 5.15.0-1022-gcp
Transactions:              14192 hits
Availability:             100.00 %
Elapsed time:              59.66 secs
Data transferred:          52.15 MB
Response time:              0.13 secs
Transaction rate:         237.88 trans/sec
Throughput:             0.87 MB/sec
Concurrency:               29.88
Successful transactions:       14192
Failed transactions:               0
Longest transaction:            2.62
Shortest transaction:           0.00

I tried bisecting each kernel versions to see what caused the performance regression but I couldn't find the relevant information. There's a reported performance regressions found by VMWare on this [link](https://www.phoronix.com/news/VMware-ESXi-Nasty-Linux-5.13) from the commit below but they didn't work at all even when following the link below: https://lore.kernel.org/lkml/BYAPR05MB483975D437F293A40BEF3189A6EC9@BYAPR05MB4839.namprd05.prod.outlook.com/

https://github.com/torvalds/linux/commit/8a99b6833c884fa0e7919030d93fecedc69fc625

Hopefully someone can shed some light on this 🙏.

**Comment by stgraber** [comment]
Closing as not a LXD bug and so not something we can do a lot about.

@brauner any ideas of what may have regressed in the kernel?

**Comment by speedrunzz** [comment]
@brauner when able, please help us shed some light on this 🙏 .
