### ISSUE TITLE
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart - System limit being hit, or something else?

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxd#11312]
LXD v5.1
Ubuntu Jammy

We do not believe this issue is tied to a specific LXD version (we know 5.1 is a bit old now) as we have seen this on-and-off for a loooong time now, since lxd 4.0 series at least, and have spent some effort in trying to identify the issue. However, this issue tends to go away on its own, presumably when system activity decreases, so it has not been critical for us. We have simply blocked any intake of new containers on a given system that shows this behavior and left it at that.

In any case, this issue tends to crop up once we have 100+ containers on a host system and looks something like this:

```
root@leeta:/home/master# lxc stop --force kakpishetsya
Error: The instance is already stopped
root@leeta:/home/master# lxc delete kakpishetsya
root@leeta:/home/master# zfs list | grep kakpi
root@leeta:/home/master# lxc launch ubuntu:focal kakpishetsya
Creating kakpishetsya
Starting kakpishetsya
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart kakpishetsya /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/kakpishetsya/lxc.conf:
Try `lxc info --show-log local:kakpishetsya` for more info
```

Now, after having looked into this many times now and concluding that we do indeed have our system limits set very high and all the limits as per your production setup documentation, this keeps happening from time to time.

We thought it wise to check with the experts here if you have any hints or pointers on where to look next. 

Please ask for any relevant information you need - or even system access which we can grant you no problem. It would be interesting to find out why this is happening.

Thanks.!

**Comment by tomponline** [comment]
Can you get `lxc info --show-log local:kakpishetsya` for when it happens?

**Comment by webdock-io** [comment]
Sure

```
root@leeta:/home/master# lxc launch ubuntu:focal kakpishetsya
Creating kakpishetsya
Starting kakpishetsya
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart kakpishetsya /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/kakpishetsya/lxc.conf:
Try `lxc info --show-log local:kakpishetsya` for more info
root@leeta:/home/master# lxc info --show-log local:kakpishetsya
Name: kakpishetsya
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2023/01/27 10:48 CET
Last Used: 2023/01/27 10:49 CET

Log:

lxc kakpishetsya 20230127094907.547 WARN     conf - conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc kakpishetsya 20230127094907.547 WARN     conf - conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc kakpishetsya 20230127094907.551 WARN     conf - conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc kakpishetsya 20230127094907.551 WARN     conf - conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc kakpishetsya 20230127094907.562 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1252 - No such file or directory - Failed to fchownat(42, memory.oom.group, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc kakpishetsya 20230127094907.986 ERROR    seccomp - seccomp.c:lxc_seccomp_load:1256 - Operation canceled - Error loading the seccomp policy
lxc kakpishetsya 20230127094907.986 ERROR    sync - sync.c:sync_wait:34 - An error occurred in another process (expected sequence number 4)
lxc kakpishetsya 20230127094907.997 WARN     network - network.c:lxc_delete_network_priv:3617 - Failed to rename interface with index 0 from "eth0" to its initial name "veth0e69acb1"
lxc kakpishetsya 20230127094907.997 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:877 - Received container state "ABORTING" instead of "RUNNING"
lxc kakpishetsya 20230127094907.998 ERROR    start - start.c:__lxc_start:2074 - Failed to spawn container "kakpishetsya"lxc kakpishetsya 20230127094907.998 WARN     start - start.c:lxc_abort:1039 - No such process - Failed to send SIGKILL via pidfd 43 for process 3707603
lxc kakpishetsya 20230127094913.339 WARN     conf - conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc kakpishetsya 20230127094913.339 WARN     conf - conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc 20230127094913.365 ERROR    af_unix - af_unix.c:lxc_abstract_unix_recv_fds_iov:218 - Connection reset by peer - Failed to receive response
lxc 20230127094913.366 ERROR    commands - commands.c:lxc_cmd_rsp_recv_fds:127 - Failed to receive file descriptors for command "get_state"
```

**Comment by tomponline** [comment]
Looks like the issue:

> lxc kakpishetsya 20230127094907.986 ERROR    seccomp - seccomp.c:lxc_seccomp_load:1256 - Operation canceled - Error loading the seccomp policy

**Comment by tomponline** [comment]
Anything in dmesg about seccomp?

**Comment by tomponline** [comment]
Sounds similar, sadly no solution in that thread:

https://discuss.linuxcontainers.org/t/scaling-past-1350-containers-seccomp-errors/8165

**Comment by tomponline** [comment]
See https://discuss.linuxcontainers.org/t/lxd-cannot-scale-over-597-containers-seccomp-errors/7046/12?u=tomp that might help.

**Comment by webdock-io** [comment]
Hey that works!

```
root@leeta:/home/master# cat /proc/sys/net/core/bpf_jit_limit
264241152
root@leeta:/home/master# echo "400000000" > /proc/sys/net/core/bpf_jit_limit
root@leeta:/home/master# lxc launch ubuntu:focal kakpishetsya
Creating kakpishetsya
Starting kakpishetsya
```

And this immediately revealed the issue to me: Newer hosts already have a very high bpf_jit_limit while this particular system is old and never received that limit raise - this went unnoticed. We will now raise the bpf_jit_limit infrastructure-wide.

Thank you for "googling this for me" :) This can be closed

**Comment by tomponline** [comment]
@ru-fu I wonder if we should add a mention of this setting in https://linuxcontainers.org/lxd/docs/master/reference/server_settings/ ?

**Comment by webdock-io** [comment]
> @ru-fu I wonder if we should add a mention of this setting in https://linuxcontainers.org/lxd/docs/master/reference/server_settings/ ?

Yes this is currently not documented for some reason. I see that @brauner had a commit for this at some point to the docs way back in 2020, but that's somehow gotten lost it seems
