### ISSUE TITLE
Different ceph client behavior when launching VMs vs Containers

### ISSUE THREAD

**Issue by nihr43** [lxc/lxd#11352]
# Required information

 * Distribution: snap on debian 12
 * Distribution version: 5.10/stable
 * The output of "lxc info" or if that fails: (lxc info is a very large document)
   * Kernel version: 6.1.0-3-amd64
   * LXC version: 5.10
   * LXD version: 5.10
   * Storage backend in use: ceph via [rook](https://rook.io/docs/rook/v1.10/Getting-Started/intro/)
 
This is a two-node cluster, with lxd running alongside microk8s serving ceph via rook.  Unless stated otherwise, client is my desktop.  Ceph client access is [configured](https://github.com/nihr43/ceph_client-ansible/blob/main/tasks/main.yml) on the cluster nodes, but not on my desktop.  For what its worth, my desktop is also debian 12 with the 5.10/stable snap installed.

# Issue description

It appears as if lxd is searching for non-existent keyring `/etc/ceph/ceph.client.admin.keyring` when launching VMs; though it is correctly using the [configured keyring](https://github.com/nihr43/ceph_client-ansible/blob/main/templates/ceph.conf#L5) `/etc/ceph/keyring` when launching containers.

# Steps to reproduce

Starting with empty cluster:

```
~$ lxc cluster ls
+--------------------+-------------------------+------------------+--------------+----------------+-------------+--------+-------------------+
|        NAME        |           URL           |      ROLES       | ARCHITECTURE | FAILURE DOMAIN | DESCRIPTION | STATE  |      MESSAGE      |
+--------------------+-------------------------+------------------+--------------+----------------+-------------+--------+-------------------+
| x10slhf-xeon-920ea | https://10.0.200.5:8443 | database-leader  | x86_64       | default        |             | ONLINE | Fully operational |
|                    |                         | database         |              |                |             |        |                   |
+--------------------+-------------------------+------------------+--------------+----------------+-------------+--------+-------------------+
| x470d4u-zen-3700f  | https://10.0.200.2:8443 | database-standby | x86_64       | default        |             | ONLINE | Fully operational |
+--------------------+-------------------------+------------------+--------------+----------------+-------------+--------+-------------------+
~$ lxc storage ls
+-------+--------+-------------+---------+---------+
| NAME  | DRIVER | DESCRIPTION | USED BY |  STATE  |
+-------+--------+-------------+---------+---------+
| local | dir    |             | 0       | CREATED |
+-------+--------+-------------+---------+---------+
| rook  | ceph   |             | 4       | CREATED | 
+-------+--------+-------------+---------+---------+
~$ lxc storage show rook
config:
  ceph.cluster_name: ceph
  ceph.osd.pg_num: "32"
  ceph.osd.pool_name: lxdpool
  ceph.user.name: admin
  volatile.pool.pristine: "true"
description: ""
name: rook
driver: ceph
used_by:
- /1.0/images/656e115974ee93fc0a67b899af1e26ec86613f1053c0f99c8ace12f904565051
- /1.0/images/75e20d86e930ed0b07e747ac263d68c7a00946b68d4a651f742d1157aa225b66
- /1.0/images/98e169bc5412557c9592c6c2a8f36ea5240e1b745639d1279ba86145e70b5a9d
- /1.0/profiles/default
status: Created
locations:
- x10slhf-xeon-920ea
- x470d4u-zen-3700f
~$ lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: rook
    type: disk
name: default
used_by: []
```

Launch three functioning containers:

```
~$ lxc launch images:debian/12 deb-cntr-0
Creating deb-cntr-0
Starting deb-cntr-0
~$ lxc launch images:debian/12 deb-cntr-1
Creating deb-cntr-1
Starting deb-cntr-1
~$ lxc launch images:debian/12 deb-cntr-2
Creating deb-cntr-2
Starting deb-cntr-2
```

...whose /dev/rbd enumeration looks correct:

```
~$ lxc exec deb-cntr-0 -- df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd0       9.8G  419M  8.9G   5% /
~$ lxc exec deb-cntr-1 -- df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd0       9.8G  419M  8.9G   5% /
~$ lxc exec deb-cntr-2 -- df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd1       9.8G  419M  8.9G   5% /
```

but --vm fails:

```
~$ lxc launch images:debian/12 --vm deb-vm-0
Creating deb-vm-0
Starting deb-vm-0
Error: Failed setting up disk device "root": Failed to open "/etc/ceph/ceph.client.admin.keyring": open /etc/ceph/ceph.client.admin.keyring: no such file or directory
Try `lxc info --show-log 10.0.200.5:deb-vm-0` for more info
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by nihr43** [comment]
this looks like the culprit for the path its looking for, but doesn't explain why containers are working:

https://github.com/lxc/lxd/blob/19286a79549a7b627329a0d9c4b358aca441c470/lxd/storage/drivers/utils_ceph.go#L148

**Comment by nihr43** [comment]
lxd uses `shared.RunCommand()` to perform all this rbd setup yes?   I'm thinking that the qemu side of things is 'correctly' [looking for the cephKeyring](https://github.com/lxc/lxd/blob/dac618b423eff76a2ef7ef80de19f38d198d58cc/lxd/instance/drivers/driver_qemu.go#L3319) as expected by the storageDriver - but somewhere on the container side, a flag or cephKeyring parameter missing somewhere, and the underlying rbd command is correctly using the OS default as configured.

**Comment by stgraber** [comment]
qemu has its own ceph client which we must feed connection information to, so we'll indeed need to expanded our logic to parse ceph.conf for the keyring key to handle such cases.

**Comment by stgraber** [comment]
@monstermunchkin want to take that one?
