### ISSUE TITLE
Remove the trust password part of lxd init and just ask if the user wants to listen to the network

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#11354]
# Issue description

Making LXD available over the network during `lxd init` should have it report its certificate fingerprint.

```
# lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: 
...
Would you like the LXD server to be available over the network? (yes/no) [default=no]: yes
Address to bind LXD to (not including port) [default=all]: 
Port to bind LXD to [default=8443]: 
Trust password for new clients: 
Again: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes]: no
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: 
```

Having the following text (with optionally a blank line to separate it from the question section) would be nice:

```

LXD listens on the network (https://[::]:8443) and the certificate fingerprint is:
617d787595552e2302183c6161afc9956b7dd463c1b02d7861ec056ca9aa4dff
```

This would encourage fingerprint verification without requiring users to know about `lxc info | grep certificate_fingerprint`

**Comment by stgraber** [comment]
I don't thing that I buy that argument.
The user setting up a LXD server is very unlikely to write down the fingerprint at that point or to somehow remember it. It would also require that the person setting up the server and the client is the same person.

What we want instead is for users to rely on `lxc config trust add` to get a join token. The join token includes the server certificate making this whole step moot.

**Comment by simondeziel** [comment]
> It would also require that the person setting up the server and the client is the same person.

Does that matter? Once a trust password is set, it can't be used (securely) without the fingerprint.

Join tokens are preferable but `lxd init` asking for a trust password encourages using this feature. People are lazy and it's not directly obvious how to get the fingerprint.

**Comment by stgraber** [comment]
Yeah, we should remove the trust password part of `lxd init` and just ask if the user wants to listen to the network.

**Comment by simondeziel** [comment]
Yeah, that'd be even better, great!
