### ISSUE TITLE
Instances query returns only instances on local node when filtering by status

### ISSUE THREAD

**Issue by pgrobelniak** [lxc/lxd#11375]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 20.04 LTS
 * Kernel version: 5.4.0-37-generic
 * LXC version: 5.0.2
 * LXD version: 5.0.2

# Issue description

When using lxc query, or the rest api, I get results only from the local node when I filter by status. Without filter, or with recursion I get instances from all nodes.

# Steps to reproduce

 1. Create lxd cluster with two nodes
 2. Add first instance: 
   lxc launch ubuntu: c1 --target n1
 4. Add second instance: 
   lxc launch ubuntu: c2 --target n2
 5. Following command returns both instances: 
   lxc query "/1.0/instances" 
 6. Following command returns only instance from local node: 
   lxc query "/1.0/instances?filter=status+eq+running"

**Comment by stgraber** [comment]
Apparently it's a bug when no recursion is enabled. If you use `&recursion=1` then things work as expected.

**Comment by stgraber** [comment]
@tomponline I had a quick look but couldn't immediately figure it out. Can you take a look at it next week? I think it's in the chunk of DB code you've been playing with somewhat recently so might be fresher in your mind than mine.

**Comment by tomponline** [comment]
Yep will do.

**Comment by tomponline** [comment]
working on this now.
