### ISSUE TITLE
lxc query -x HEAD does not work

### ISSUE THREAD

**Issue by gboutry** [lxc/lxd#11383]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.0
   * LXC version: 5.10
   * LXD version: 5.10
   * Storage backend in use: zfs

# Issue description

Using lxc query --request HEAD fails with bad request error.

# Steps to reproduce

 1. Use LXC query to request file metadata

```bash
lxc query --request HEAD '/1.0/instances/promoted-ladybird/files?path=/etc/hosts'
Error: Failed to fetch http://unix.socket/1.0/instances/promoted-ladybird/files?path=/etc/hosts: 400 Bad Request
```

 2. Using curl works as expected:

```bash
curl --unix-socket /var/snap/lxd/common/lxd/unix.socket --head 'lxd/1.0/instances/promoted-ladybird/files?path=/etc/hosts'
HTTP/1.1 200 OK
Content-Type: application/json
X-Lxd-Gid: 0
X-Lxd-Mode: 0644
X-Lxd-Modified: 2023-02-20 11:15:16 +0000 UTC
X-Lxd-Type: file
X-Lxd-Uid: 0
Date: Mon, 20 Feb 2023 11:17:01 GMT
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
The `query` tool doesn't show headers, so even if we fixed this (and I fixed the root issue), it would just get you an empty response as no data is included with a `HEAD` call.

I'm sending a PR which has `lxc query` validate the actions and give a clear error.
