### ISSUE TITLE
Non-JSON messages output with `--format json`

### ISSUE THREAD

**Issue by feileacan** [lxc/lxd#11382]
# Required information

Happens on LXC 3, 4, and reading the code it looks like it's still present on current master for all platforms: https://github.com/lxc/lxd/blob/f25446c8ac870eb42fe1f087b787c2ff5f80ae7e/lxc/main.go#L353-L383

# Issue description

Sometimes (e.g. first call to lxc after a fresh install) extra messages are printed. These messages ignore the requested output format (e.g. `lxc list --format json` outputs text + json, instead of just a valid json blob).
This is easy enough to work around (call another command first, preprocess output, etc).

# Steps to reproduce

 1. Fresh install of LXD
 2. `lxc list --format json`
 Expected Output:
```
[]
```

Actual output:
```
To start your first instance...

[]
```

**Comment by stgraber** [comment]
The message is correctly sent out to stderr instead of stdout. When scripting a CLI tool, you're supposed to be parsing its stdout, not stderr.
