### ISSUE TITLE
lxc query -x GET does not work for empty files

### ISSUE THREAD

**Issue by tobias-chc** [lxc/lxd#11388]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.19.0-32-generic
   * LXC version: 5.10
   * LXD version: 5.10
   * Storage backend in use: zfs

# Issue description

Using `lxc query --request GET` on empty files throws the following error:
```
Error: EOF
```

# Steps to reproduce

 1. Launch an instance
   ```bash
  lxc launch images:alpine/3.17 test-alpine-317
  ```
 2. Create an empty file
   ```bash
  lxc exec test-alpine-317 -- touch /root/empty_file
  ```
 3. Use LXC query to request file content
   ```bash
   lxc query --request GET '/1.0/instances/test-alpine-317/files?path=/root/empty_file'
   Error: EOF
   ```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by jeffreyxie0615** [comment]
Hey! My partner and I are students from UT Austin as part of their virtualization class, and we were wondering if we could tackle this issue! If so, we would appreciate any assistance in getting things setup/any background knowledge that can be offered.

**Comment by tomponline** [comment]
Thanks! 

The first step will be to get a working LXD build, take a look at https://linuxcontainers.org/lxd/docs/master/installing/#install-lxd-from-source

**Comment by jeffreyxie0615** [comment]
Hey,

After looking through this issue, we believe the problem might lie in the Go source code. It seems that in Go's server code, when it reads a response, it checks through the response body to make sure it's not malformed, and one of the checks it does is the EOF check. Once it sees the EOF, it returns an error. We're unsure the expected behavior from here. Could we get some guidance as to what needs to be done?

**Comment by stgraber** [comment]
@jeffreyxie0615 `lxc query` does have some logic to detect that the output isn't a normal response and to re-do it as a normal plain text query, that plain text query should not fail on EOF.
