### ISSUE TITLE
s390x VM limited to 1 CPU

### ISSUE THREAD

**Issue by john-cabaj** [lxc/lxd#11426]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.19.0-32-generic
   * LXC version: 5.11
   * LXD version: 5.11
   * Storage backend in use: zfs

# Issue description

On a s390x LXD VM, I'm unable to increase the limits.cpu past 1.

# Steps to reproduce

 1. Step one
 ```
$ lxc config set jammy-s390x limits.cpu 4
 ```
 2. Step two
 ```
$ lxc start jammy-s390x
 ```
 3. Step three
 Observe:
 
 ```
Error: Failed to add CPUs: Failed to add device: Property 'host-s390x-cpu.thread-id' not found
Try `lxc info --show-log jammy-s390x` for more info

$ lxc info --show-log jammy-s390x
Name: jammy-s390x
Status: STOPPED
Type: virtual-machine
Architecture: s390x
Created: 2023/03/01 10:47 CST
Last Used: 2023/03/01 10:48 CST

Log:

qemu-system-s390x: Setting device address of a display device: Not a PCI device.
```

**Comment by ittner** [comment]
Can confirm, I got the same issue running lxd 5.11-ad0b61e (snap rev 24486) in jammy on a LPAR.  Also happened with with lxd 5.0.2-838e1b2 (rev 24325).
