### ISSUE TITLE
Add Generation ID support for Virtual Machines

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#11449]
QEMU supports the concept of a VM Generation ID that is exposed to the guest OS.

This can be used by the hypervisor to indicate to the guest OS that its place in time has moved backwards (such as when an instance is restored from a snapshot or backup).

This allows for the VM guest OS to reinitialize any state it needs to avoid any invalid data that could have occurred since the snapshot or backup was taken (the classic example being replication in a distributed system).

The initial attempt at adding this feature (https://github.com/lxc/lxd/pull/11385) had an issue in that it caused the VM's machine ID to be changed on snapshot and backup restore. This is problematic because it can cause the the guest OS' identity to change, and can also cause it to reconfigure network identifiers.

Instead we need the following changes to support VM generation ID properly:

- [ ] The instance `volatile.uuid` key should remain unchanged during snapshot and backup restores (effectively reverting https://github.com/lxc/lxd/pull/11385). It should also remain unchanged when moved between servers. However it should change when a new instance is created by copying and existing instance (or snapshot). This should be existing behaviour and require no code changes. But worth checking.
- [ ] A new instance key called `volatile.uuid.generation` should be added. This should be set to the same value as `volatile.uuid` at instance creation time (`instance.CreateInternal`) and should also be populated if not populated to the same value as `volatile.uuid` during `qemu.Start()`.
- [ ] Whenever the `volatile.uuid` key is changed the `volatile.uuid.generation` key should be changed to match the `volatile.uuid` value.
- [ ] The `volatile.uuid.generation` value should be passed to QEMU as the VM's generation ID.
- [ ] On snapshot and backup restore a new `volatile.uuid.generation` value should be generated and stored in the restored instance's DB record (the snapshot record should not be modified). And the `volatile.uuid` key should remain unchanged.
- [ ] The daily test for VMs should check that the QEMU process contains the correct Machine ID and VM generation ID flag.
- [x] Depending on the answer to https://github.com/lxc/lxd/issues/11449#issuecomment-1459743902 the test suite can test for the correct population of the `volatile.uuid` and generation UUID keys for containers too.

**Comment by tomponline** [comment]
@stgraber Please can you look through this and check you're happy with this spec?

Also shall we call the new key `volatile.uuid.generation` rather than `volatile.uuid.vmgenid` and then maintain it for both VMs and containers. 

As well as being consistent between instance types, it also, potentially, allows us to pass that info through to the container somehow in the future if needed.

Or shall we just populate it for VMs?

**Comment by stgraber** [comment]
Having it for both doesn't hurt and could indeed be useful at some point in the future.

**Comment by tomponline** [comment]
@gabrielmougard I've updated the spec to use `volatile.uuid.generation`
