### ISSUE TITLE
Feature Request for LXD-Based APX?

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [lxc/lxd#11448]
https://github.com/Vanilla-OS/apx

https://documentation.vanillaos.org/docs/apx/

Apx (/à·peks/) is the default package manager in Vanilla OS. It is a wrapper around multiple package managers to install packages and run commands inside a managed container.

Special thanks to distrobox for making this possible.

Apx is a package manager with support for multiple sources allowing you to install packages in a managed container.

Usage:
  apx [command]

Available Commands:
  autoremove  Remove all unused packages automatically
  clean       Clean the apx package manager cache
  completion  Generate the autocompletion script for the specified shell
  enter       Enter in the container shell
  export      Export/Recreate a program's desktop entry from a managed container
  help        Help about any command
  init        Initialize the managed container
  install     Install packages inside a managed container
  list        List installed packages.
  purge       Purge packages inside a managed container
  remove      Remove packages inside a managed container.
  run         Run a program inside a managed container.
  search      Search for packages in a managed container.
  show        Show details about a package
  unexport    Unexport/Remove a program's desktop entry from a managed container
  update      Update the list of available packages
  upgrade     Upgrade the system by installing/upgrading available packages.

Global Flags:
      --apk           Install packages from the Alpine repository.
      --apt           Install packages from the Ubuntu repository.
      --aur           Install packages from the AUR (Arch User Repository).
      --dnf           Install packages from the Fedora's DNF (Dandified YUM) repository.
      --zypper        Install packages from the openSUSE repository.
      --xbps          Install packages from the Void (Linux) repository.
  -h, --help          help for apx
  -n, --name string   Create or use custom container with this name.
  -v, --version       version for apx

Use "apx [command] --help" for more information about a command.

**Comment by OpenOS-Project-Creator-Founder** [comment]
> https://github.com/Vanilla-OS/apx
> 
> https://documentation.vanillaos.org/docs/apx/
> 
> Apx (/à·peks/) is the default package manager in Vanilla OS. It is a wrapper around multiple package managers to install packages and run commands inside a managed container.
> 
> Special thanks to distrobox for making this possible.
> 
> Apx is a package manager with support for multiple sources allowing you to install packages in a managed container.
> 
> Usage:
>   apx [command]
> 
> Available Commands:
>   autoremove  Remove all unused packages automatically
>   clean       Clean the apx package manager cache
>   completion  Generate the autocompletion script for the specified shell
>   enter       Enter in the container shell
>   export      Export/Recreate a program's desktop entry from a managed container
>   help        Help about any command
>   init        Initialize the managed container
>   install     Install packages inside a managed container
>   list        List installed packages.
>   purge       Purge packages inside a managed container
>   remove      Remove packages inside a managed container.
>   run         Run a program inside a managed container.
>   search      Search for packages in a managed container.
>   show        Show details about a package
>   unexport    Unexport/Remove a program's desktop entry from a managed container
>   update      Update the list of available packages
>   upgrade     Upgrade the system by installing/upgrading available packages.
> 
> Global Flags:
>       --apk           Install packages from the Alpine repository.
>       --apt           Install packages from the Ubuntu repository.
>       --aur           Install packages from the AUR (Arch User Repository).
>       --dnf           Install packages from the Fedora's DNF (Dandified YUM) repository.
>       --zypper        Install packages from the openSUSE repository.
>       --xbps          Install packages from the Void (Linux) repository.
>   -h, --help          help for apx
>   -n, --name string   Create or use custom container with this name.
>   -v, --version       version for apx
> 
> Use "apx [command] --help" for more information about a command.



[ Special thanks to distrobox for making this possible. ]

https://github.com/89luca89/distrobox

Use any Linux distribution inside your terminal. Enable both backward and forward compatibility with software and freedom to use whatever distribution you’re more comfortable with. Distrobox uses podman or docker to create containers using the Linux distribution of your choice. The created container will be tightly integrated with the host, allowing sharing of the HOME directory of the user, external storage, external USB devices and graphical apps (X11/Wayland), and audio.

I suggest replacing Distrobox with Tins...

I would contract the Tins Maintainer to upstream & create a core team around Tins. Then deploy Tins in place of Distrobox. 

https://github.com/marbetschar/tins

Tins uses LXD to easily create and manage Containers providing a Desktop Environment (Graphical User Interface). The usability is similar to VirtualBox, but without the downsides of traditional Virtual Machines: Unprivileged, lightweight Linux Containers provide good isolation along with superior performance.

**Comment by stgraber** [comment]
Not something that the LXD team itself would be working on, this looks like a request for an entirely new project, which would certainly be fun and could be done by using LXD should someone want to do this.
