### ISSUE TITLE
lxc image import Stuck on fingering daemon

### ISSUE THREAD

**Issue by bendacoder** [lxc/lxd#1146]
I am trying to import and image of Ubuntu into LXD using the command 
```
sudo lxc image import ubuntuLxd.tar.gz --debug --alias ubuntu
```
And I am stuck on the message `fingering daemon` for about 10 minutes.
![screenshot from 2015-09-25 18 22 40](https://cloud.githubusercontent.com/assets/13733017/10113449/741e51f6-63b2-11e5-9985-c8090c30ecad.png)

**Comment by tych0** [comment]
On Fri, Sep 25, 2015 at 03:09:17PM -0700, Ben Dacoder wrote:
> I am trying to import and image of Ubuntu into LXD using the command 
> ```
> sudo lxc image import ubuntuLxd.tar.gz --debug --alias ubuntu
> ```
> And I am stuck on the message `fingering daemon` for about 10 minutes.

Sounds like your lxd might be hung. Is it running? If you strace it,
is it doing anything interesting?

**Comment by bendacoder** [comment]
There was a process called lxd-images. I ended it, and nothing changed.

**Comment by tych0** [comment]
On Fri, Sep 25, 2015 at 03:55:50PM -0700, Ben Dacoder wrote:
> There was a process called lxd-images. I ended it, and nothing changed.

Sounds like your lxd isn't running then; what happens if you start it
and try again?

**Comment by bendacoder** [comment]
I had to reinstall the application and then it worked

**Comment by stgraber** [comment]
Sounds like this got resolved.
