### ISSUE TITLE
Specifying a remote when adding a token fails

### ISSUE THREAD

**Issue by jbernard** [lxc/lxd#11466]
# Required information
 * Distribution: Ubuntu
 * Distribution version: 22.04
 * LXD version: 5.11-ad0b61e (snap)

# Issue description

When creating an auth token, if the remote name is specified on the command line then the command will fail.

# Steps to reproduce

 1. lxc config trust add xeon: --name test

This command will fail with the following error:

Error: open xeon:: no such file or directory

If the remote is omitted (the default is used) OR a certificate file is provided, everything works fine.  Simon on IRC (#lxc) was able to reproduce this as well.

**Comment by presztak** [comment]
@stgraber can I work on this?

**Comment by tomponline** [comment]
Thanks!
