### ISSUE TITLE
zfs.block_mode should be honored when containers are copied or moved between different storages

### ISSUE THREAD

**Issue by kattunga** [lxc/lxd#11471]
This issue is opened from #3873

I have a lxd server with 2 storages:

The old one: with LVM controller (where I run all my non zfs compatible containers)
The new one: with ZFS driver, zfs.block_mode = true

When I copy or move containers from LVM storage to ZFS storage, the zfs.block_mode flag is not honored and the containers are created on ZFS storage as a dataset.
Also if I export containers from the LVM storage and I import them into ZFS storage they are created as dataset instead of zvols.

I understand that “existing instances using datasets will not be converted to zvols” when they are copied or moved between zfs storages, but why zfs.block_mode = true can’t be honored when storages use different drivers?

I found no way to migrate my db/docker containers (that are not compatible with zfs datasets) from LVM to ZFS, and create all of them from scratch is not an option, is there any solution?

I also found this function useless on clusters with different storage and different controllers, because if you mistakenly move a container configured with block mode to a non-zfs storage, you can never go back to zfs block mode.

Regards

**Comment by monstermunchkin** [comment]
Fixed by #11771
