### ISSUE TITLE
lxc image ls remote: does not respect proxy setting

### ISSUE THREAD

**Issue by jellehelsen** [lxc/lxd#11470]
# Required information

 * Distribution: Ubuntu 20.04.4 LTS
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-144-generic
   * LXC version: 5.11
   * LXD version: 5.11
   * Storage backend in use: dir

# Issue description

Although lxd is configured to use a proxy, when running `lxc image ls ubuntu:` the proxy server is not respected. Since this proxy is our only way to connect to the internet, I cannot list the images available on any image server on the internet.

```
tc@lab-dev-vm-host:~$ lxc config show
config:
  core.https_address: '[::]:8443'
  core.proxy_http: http://proxy-telcocloud.int.inet.telenet.be:8080
  core.proxy_https: http://proxy-telcocloud.int.inet.telenet.be:8080
  core.proxy_ignore_hosts: telenet.be,127.0.0.1,localhost
  core.trust_password: true
tc@lab-dev-vm-host:~$ lxc image ls ubuntu:
Error: Failed parsing stream: Get "https://cloud-images.ubuntu.com/releases/streams/v1/index.json": Unable to connect to: cloud-images.ubuntu.com:443 ([dial tcp 185.125.190.40:443: i/o timeout dial tcp 185.125.190.37:443: i/o timeout dial tcp [2620:2d:4000:1::17]:443: connect: network is unreachable dial tcp [2620:2d:4000:1::1a]:443: connect: network is unreachable])

```

# Steps to reproduce

 1. configure lxd to use a proxy
 2. block other routes to the internet
 3. run `lxc image ls ubuntu:`

**Comment by stgraber** [comment]
`lxc image ls` is done client side, it doesn't talk to the daemon at all.
As a result, it respects the `http_proxy` and `https_proxy` environment variables but cannot look at the server configuration.

**Comment by jellehelsen** [comment]
That's a bit confusing, but OK.
Tested, confirmed to work. Thanks.
