### ISSUE TITLE
Debian/Sid lxd package, not starting vm 

### ISSUE THREAD

**Issue by manchelsi** [lxc/lxd#11482]
# Required information

 * Distribution: Debian
 * Distribution version: bookworm/sid
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.1.0-6-amd64
   * LXC version: 5.0.2
   * LXD version: 5.0.2
   * qemu-system-x86_64 --version QEMU emulator version 7.2.0 (Debian 1:7.2+dfsg-4)

If I run with default parameters I get an error:

```
root@debtest:~# lxc launch images:debian/11 debian --vm 
Creating debian
Starting debian
Error: Failed setting up device via monitor: Failed setting up device "eth0": Failed adding NIC netdev: Monitor is disconnected
Try `lxc info --show-log local:debian` for more info
root@debtest:~# lxc info --show-log local:debian
Name: debian
Status: STOPPED
Type: virtual-machine
Architecture: x86_64
Created: 2023/03/19 11:20 MSK

Log:

warning: tap: open vhost char device failed: Permission denied
warning: tap: open vhost char device failed: Permission denied
qemu-system-x86_64: ../../net/net.c:1106: net_client_init1: Assertion `nc' failed.
```

however, if I grant full access to /dev/vhost-net, the vm starts up:

```
root@debtest:~# chmod 777 /dev/vhost-net 
root@debtest:~# lxc start debian
root@debtest:~# lxc list -c nst4
+--------+---------+-----------------+------------------------+
|  NAME  |  STATE  |      TYPE       |          IPV4          |
+--------+---------+-----------------+------------------------+
| debian | RUNNING | VIRTUAL-MACHINE | 10.215.205.98 (enp5s0) |
+--------+---------+-----------------+------------------------+
```

Looks like lxd lacks permissions...

**Comment by manchelsi** [comment]
When auditing the /dev/vhost-net file, you can see that qemu is accessing it with permissions UID="nobody" GID="nogroup"

```
root@debtest:~# cat /var/log/audit/audit.log 
type=ANOM_PROMISCUOUS msg=audit(1679247910.913:449): dev=tap0330d977 prom=256 old_prom=0 auid=4294967295 uid=0 gid=0 ses=4294967295AUID="unset" UID="root" GID="root"
type=SYSCALL msg=audit(1679247910.913:449): arch=c000003e syscall=46 success=yes exit=40 a0=3 a1=7ffdb3ee3cd0 a2=0 a3=0 items=0 ppid=6222 pid=13974 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="ip" exe="/usr/bin/ip" subj=unconfined key=(null)ARCH=x86_64 SYSCALL=sendmsg AUID="unset" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
type=SOCKADDR msg=audit(1679247910.913:449): saddr=100000000000000000000000SADDR={ saddr_fam=netlink nlnk-fam=16 nlnk-pid=0 }
type=PROCTITLE msg=audit(1679247910.913:449): proctitle=6970006C696E6B0073657400646576007461703033333064393737006D6173746572006C7864627230
type=AVC msg=audit(1679247910.933:450): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-deb1_</var/lib/lxd>" pid=13980 comm="apparmor_parser"
type=SYSCALL msg=audit(1679247910.933:450): arch=c000003e syscall=1 success=yes exit=16569 a0=6 a1=559869fbf5e0 a2=40b9 a3=0 items=0 ppid=13979 pid=13980 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="apparmor_parser" exe="/usr/sbin/apparmor_parser" subj=unconfined key=(null)ARCH=x86_64 SYSCALL=write AUID="unset" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
type=PROCTITLE msg=audit(1679247910.933:450): proctitle=61707061726D6F725F706172736572002D72574C002F7661722F6C69622F6C78642F73656375726974792F61707061726D6F722F6361636865002F7661722F6C69622F6C78642F73656375726974792F61707061726D6F722F70726F66696C65732F6C78642D64656231
type=SYSCALL msg=audit(1679247911.257:451): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=55fdf2445f4a a2=2 a3=0 items=1 ppid=1 pid=13992 auid=4294967295 uid=65534 gid=65534 euid=65534 suid=65534 fsuid=65534 egid=65534 sgid=65534 fsgid=65534 tty=(none) ses=4294967295 comm="qemu-system-x86" exe="/usr/bin/qemu-system-x86_64" subj=lxd-deb1_</var/lib/lxd> key=(null)ARCH=x86_64 SYSCALL=openat AUID="unset" UID="nobody" GID="nogroup" EUID="nobody" SUID="nobody" FSUID="nobody" EGID="nogroup" SGID="nogroup" FSGID="nogroup"
type=CWD msg=audit(1679247911.257:451): cwd="/"
type=PATH msg=audit(1679247911.257:451): item=0 name="/dev/vhost-net" inode=365 dev=00:05 mode=020660 ouid=0 ogid=104 rdev=0a:ee nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="root" OGID="kvm"
type=PROCTITLE msg=audit(1679247911.257:451): proctitle=2F7573722F62696E2F71656D752D73797374656D2D7838365F3634002D53002D6E616D650064656231002D757569640037663465396239612D353139352D343932372D393639652D393566373931393331376639002D6461656D6F6E697A65002D63707500686F73742C68765F706173737468726F756768002D6E6F67726170
type=SYSCALL msg=audit(1679247911.257:452): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=55fdf2445f4a a2=2 a3=0 items=1 ppid=1 pid=13992 auid=4294967295 uid=65534 gid=65534 euid=65534 suid=65534 fsuid=65534 egid=65534 sgid=65534 fsgid=65534 tty=(none) ses=4294967295 comm="qemu-system-x86" exe="/usr/bin/qemu-system-x86_64" subj=lxd-deb1_</var/lib/lxd> key=(null)ARCH=x86_64 SYSCALL=openat AUID="unset" UID="nobody" GID="nogroup" EUID="nobody" SUID="nobody" FSUID="nobody" EGID="nogroup" SGID="nogroup" FSGID="nogroup"
type=CWD msg=audit(1679247911.257:452): cwd="/"
type=PATH msg=audit(1679247911.257:452): item=0 name="/dev/vhost-net" inode=365 dev=00:05 mode=020660 ouid=0 ogid=104 rdev=0a:ee nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="root" OGID="kvm"
type=PROCTITLE msg=audit(1679247911.257:452): proctitle=2F7573722F62696E2F71656D752D73797374656D2D7838365F3634002D53002D6E616D650064656231002D757569640037663465396239612D353139352D343932372D393639652D393566373931393331376639002D6461656D6F6E697A65002D63707500686F73742C68765F706173737468726F756768002D6E6F67726170
type=ANOM_ABEND msg=audit(1679247911.257:453): auid=4294967295 uid=65534 gid=65534 ses=4294967295 subj=lxd-deb1_</var/lib/lxd> pid=13992 comm="qemu-system-x86" exe="/usr/bin/qemu-system-x86_64" sig=6 res=1AUID="unset" UID="nobody" GID="nogroup"
type=ANOM_PROMISCUOUS msg=audit(1679247911.261:454): dev=tap0330d977 prom=0 old_prom=256 auid=4294967295 uid=0 gid=0 ses=4294967295AUID="unset" UID="root" GID="root"
type=SYSCALL msg=audit(1679247911.261:454): arch=c000003e syscall=46 success=yes exit=40 a0=3 a1=7fff022974c0 a2=0 a3=7fff02296ee4 items=0 ppid=6222 pid=14003 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="ip" exe="/usr/bin/ip" subj=unconfined key=(null)ARCH=x86_64 SYSCALL=sendmsg AUID="unset" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
type=SOCKADDR msg=audit(1679247911.261:454): saddr=100000000000000000000000SADDR={ saddr_fam=netlink nlnk-fam=16 nlnk-pid=0 }
type=PROCTITLE msg=audit(1679247911.261:454): proctitle=6970006C696E6B0073657400646576007461703033333064393737006E6F6D6173746572
```

And 'chown nobody /dev/vhost-net',  also solves the startup problem.

Need to figure out why qemu is calling using UID="nobody" GID="nogroup"

**Comment by tomponline** [comment]
The warning 

"
warning: tap: open vhost char device failed: Permission denied"

Has been happening for quite a while without any noticeable problems.

However the recent assert crash started occurring in qemu 7.2.0 see https://discuss.linuxcontainers.org/t/failed-adding-nic-netdev-monitor-is-disconnected/15946

Its perhaps possible that we can solve both issues by passing the fd to vhost-net (as lxd runs qemu was unprivileged user).

**Comment by manchelsi** [comment]
No I tried qemu 5.6, 7.1, 7.2. Everywhere the same results.

**Comment by tomponline** [comment]
Then warming or the assert crash (they are different).

**Comment by tomponline** [comment]
The LXD snap package bundles qemu 7.1.0 and we've not seen the crash issue. The snap  hasn't moved ro 7.2.0 yet. Ive also used the qemu native package that comes with ubuntu jammy and also do not experience the crash.

**Comment by manchelsi** [comment]
Perhaps so, he described his findings here:
https://gitlab.com/qemu-project/qemu/-/issues/1486

**Comment by tomponline** [comment]
Yes its not surprising as lxd runs qemu as non root user. Perhaps there is a way of passing by fd (its what we do for other nic types already) as we do lock down the qemu process a fair bit. I did try this approach in the past (at the time I was adding multi queue fd support for macvlan) but it didn't work out and at the time the warning itself wasn't causing any problems.

**Comment by tomponline** [comment]
When the snap moves to qemu 7.2.0 we will likely have to solve this or if its an upstream regression have to hold until its fixed.

**Comment by stgraber** [comment]
A QEMU crash isn't a LXD bug, it's a QEMU one.

As mentioned, we're aware of 7.2 just being plain broken (crashes) so have been staying away from it.
When comes 7.3, we'll test again and adjust anything that needs adjusting in LXD.

**Comment by ogelpre** [comment]
I see the same issue as @manchelsi describes on gentoo. Changing permissions on /dev/vhost-net /dev/vhost-vsock fixes the issue. It looks like the issue is, that qemu 7.2.0 need access to those files to work properly. It has to be started with group kvm. But  instead it is started with group nogroup.

**Comment by benaryorg** [comment]
> A QEMU crash isn't a LXD bug, it's a QEMU one.

@stgraber Considering this is a permission issue and can be narrowed down to LXD starting the qemu process with too little privileges to run this does indeed seem to be an LXD issue, I'd like to ask you to reconsider your stance on this.

Current Gentoo does not ship with anything *but* qemu 7.2, Debian *bullseye-backports* already ships qemu 7.2, *bookworm* will be shipping 7.2, Ubuntu *lunar* will ship with 7.2, Arch is shipping 7.2, Alpine *edge* is shipping 7.2.…
This is a showstopper for many people.

LXD runs as root and to my understanding is starting qemu directly (I can't check right now because VMs don't work :roll_eyes:).
Permissions of the relevant devices, IMHO rightfully so, look like this:

```text
0 crw-rw---- 1 root kvm  10, 238 2023-04-15 18:22 /dev/vhost-net
0 crw-rw---- 1 root kvm  10, 241 2023-04-15 18:22 /dev/vhost-vsock
```

The *kvm* group has exactly one user in it, which is *qemu*.
VMs started by e.g. libvirt also run as user *qemu*, which allow libvirt to properly start qemu.
Considering that LXD does *not* do that, I'd say that is a problem on LXDs behalf and should be fixed.
Much less should qemu be blamed for this in any capacity.

**Comment by stgraber** [comment]
We don't support QEMU 7.2.

8.0 is around the corner and should have the fixes we need.

**Comment by tomponline** [comment]
The latest/edge channel has been updated to QEMU 8.0 which still has the issue.
We have a workaround at the moment (disable the vhost-dev accelerator option), but we are investigating a proper solution. This should also solve the QEMU 7.2 issue too.

**Comment by tomponline** [comment]
https://github.com/lxc/lxd/pull/11594 should get veth based NICs working again in QEMU >= 7.2

**Comment by tomponline** [comment]
@gibmat We have a fix for this now in https://github.com/lxc/lxd/pull/11594

**Comment by gibmat** [comment]
Thanks! I can confirm this cleanly fixes the issue in Debian's packaging, and I'll be uploading the fix shortly to sid.

**Comment by stgraber** [comment]
Worth noting that it's not ideal from a performance standpoint, though it's also unlikely that we ever benefited from the expected performance boost in the first place. We're still looking at adding proper logic to passthrough /dev/vhost-net as an fd. QEMU has logic for it but it's been failing in our tests so far.

**Comment by tomponline** [comment]
@gibmat FYI we now have a proper fix for this LXD 5.14 https://github.com/lxc/lxd/pull/11715

**Comment by tomponline** [comment]
@gibmat you'll also want https://github.com/lxc/lxd/pull/11732

**Comment by mmokrejs** [comment]
Hi,
  I also hit this issue because the 
```
$ lxc list
+---------+---------+------+------+-----------------+-----------+
|  NAME   |  STATE  | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+---------+---------+------+------+-----------------+-----------+
| default | RUNNING |      |      | VIRTUAL-MACHINE | 0         |
+---------+---------+------+------+-----------------+-----------+
$ lxc network attach ubuntu default
Error: Failed to start device "ubuntu": Failed setting up device "ubuntu": Failed adding NIC netdev: Monitor is disconnected
$ lxc list
+---------+---------+------+------+-----------------+-----------+
|  NAME   |  STATE  | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+---------+---------+------+------+-----------------+-----------+
| default | STOPPED |      |      | VIRTUAL-MACHINE | 0         |
+---------+---------+------+------+-----------------+-----------+
$ lxc start default
Error: Failed setting up device via monitor: Failed setting up device "ubuntu": Failed adding NIC netdev: Monitor is disconnected
$
$ lxc info --show-log default
Name: default
Status: STOPPED
Type: virtual-machine
Architecture: x86_64
Created: 2023/09/11 10:53 CEST
Last Used: 2023/09/11 10:59 CEST

Log:

warning: tap: open vhost char device failed: Permission denied
warning: tap: open vhost char device failed: Permission denied
qemu-system-x86_64: ../net/net.c:1158: net_client_init1: Assertion `nc' failed.

$
```
is totally uninformative and as I am a newbie , it took me a while to realize the VM got stopped.

It turned out I did not have `/dev/vhost-net` because `vhost_net` module was not loaded at all.

But after loading it, I yielded 

```
$ ls -latr /dev/vhost-net /dev/vhost-vsock
crw-rw---- 1 root kvm 10, 241 Sep  8 16:10 /dev/vhost-vsock
crw-rw---- 1 root kvm 10, 238 Sep 11 11:16 /dev/vhost-net
$
```

```
$ lxc start default
Error: Failed setting up device via monitor: Failed setting up device "ubuntu": Failed adding NIC netdev: Monitor is disconnected
Try `lxc info --show-log default` for more info
mokrejs@dell_e5580$ lxc info --show-log default
Name: default
Status: STOPPED
Type: virtual-machine
Architecture: x86_64
Created: 2023/09/11 10:53 CEST
Last Used: 2023/09/11 10:59 CEST

Log:

warning: tap: open vhost char device failed: Permission denied
warning: tap: open vhost char device failed: Permission denied
qemu-system-x86_64: ../net/net.c:1158: net_client_init1: Assertion `nc' failed.
```

Credit goes to @benaryorg for `sudo useradd -r -M -G kvm -d /var/lib/lxd -g lxd lxd`

I am on Gentoo Linux too. I wonder if this wasn't supposed to be fixed in qemu-8.1:

```
# emerge -pv qemu lxc lxd

[ebuild   R    ] app-containers/lxc-5.0.3:0/1.502::gentoo  USE="caps pam seccomp ssl tools -apparmor -examples -io-uring -lto -man (-selinux) -systemd -test -verify-sig" 0 KiB
[ebuild   R    ] app-emulation/qemu-8.1.0::gentoo  USE="aio alsa bzip2 curl fdt filecaps gnutls gtk jpeg ncurses nfs nls opengl oss pam pin-upstream-blobs png python seccomp slirp smartcard spice ssh udev usb usbredir vhost-net virtfs vnc xattr zstd -accessibility -bpf -capstone -debug -doc -fuse -glusterfs -infiniband -io-uring -iscsi -jack -jemalloc -lzo -multipath -numa -pipewire -plugins -pulseaudio -rbd -sasl -sdl -sdl-image (-selinux) -snappy -static-user -systemtap -test -vde -virgl -vte -xen" PYTHON_TARGETS="python3_10 python3_11 -python3_12" QEMU_SOFTMMU_TARGETS="x86_64 -aarch64 -alpha -arm -avr -cris -hppa -i386 -loongarch64 -m68k -microblaze -microblazeel -mips -mips64 -mips64el -mipsel -nios2 -or1k -ppc -ppc64 -riscv32 -riscv64 -rx -s390x -sh4 -sh4eb -sparc -sparc64 -tricore -xtensa -xtensaeb" QEMU_USER_TARGETS="-aarch64 -aarch64_be -alpha -arm -armeb -cris -hexagon -hppa -i386 -loongarch64 -m68k -microblaze -microblazeel -mips -mips64 -mips64el -mipsel -mipsn32 -mipsn32el -nios2 -or1k -ppc -ppc64 -ppc64le -riscv32 -riscv64 -s390x -sh4 -sh4eb -sparc -sparc32plus -sparc64 -x86_64 -xtensa -xtensaeb" 0 KiB
[ebuild   R    ] app-containers/lxd-5.0.2-r2::gentoo  USE="nls -apparmor -verify-sig" 0 KiB

Total: 3 packages (3 reinstalls), Size of downloads: 0 KiB
#
```

I think LXC should be more thorough and tell me the kernel module was not loaded right in the cmdline error.  `lxc info --show-log ubuntu-2204` is maybe helpful to keep logs in general but how does one delete the log to get rid of old messages?

Either way, `Error: Failed setting up device via monitor: Failed setting up device "ubuntu": Failed adding NIC netdev: Monitor is disconnected` if just confusing. I really propose to LXC/LXD devs to unload kernel modules and deconfigure partly their systems to check what error message are being out and how to improve them.

Anyway, I am looking for to get the LXC running. At the moment it is quite tough.

**Comment by tomponline** [comment]
The fix is already in LXD main branch for this, and will be backported into the next LXD LTS release, which eventually should make it into Debian's package.

**Comment by mmokrejs** [comment]
Please include a link to the fixing commit, I am on Gentoo Linux so I will patch it for myself.

**Comment by tomponline** [comment]
They are linked above your post, but due to the org change dont work anymore:

https://github.com/canonical/lxd/pull/11715
https://github.com/canonical/lxd/pull/11732
