### ISSUE TITLE
vhost_vsock is built-in and lxd seems to complain about module loading

### ISSUE THREAD

**Issue by rafaeldtinoco** [lxc/lxd#11484]
# Required information

 * Distribution: WSL2 Ubuntu 22.04 (latest 5.15.90.1)
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.90.1 (latest WSL2 kernel)
   * LXC version: 5.11-ad0b61e
   * LXD version: 5.11-ad0b61e
   * Storage backend in use: dir

# Issue description

WSL2 supports nested virtualization. The kernel source is available and it is able to generate bzImage file (with all modules as builtin) and have linux kernel functionalities added.

Trying to run LXD VM machines I'm facing:

```
$ lxc launch ubuntu:jammy --vm -p ubuntu
Creating the instance
Error: Failed instance creation: Failed creating instance record: Instance type "virtual-machine" is not supported on this server: vhost_vsock kernel module not loaded
```

From https://github.com/lxc/lxd/blob/212558e9fec5f16a90d0ce9d39d1ea615f509cde/lxd/instance/drivers/driver_qemu.go#L6900

Looks like you're trying to load the module either way (as I do have the VHOST_VSOCK module as builtin as you an see in the dmesg:

```
$ dmesg | grep -i vsock
[    0.395493] NET: Registered PF_VSOCK protocol family
```

and all permissions given to the 3 files:

```
$ sudo ls -lah /dev/vsock /dev/kvm /dev/vhost-net
Permissions   Size User Date Modified Name
crwxrwxrwx  10,232 root 20 Mar 04:38  /dev/kvm
crwxrwxrwx  10,238 root 20 Mar 04:38  /dev/vhost-net
crwxrwxrwx  10,126 root 20 Mar 04:38  /dev/vsock
```

Looks like the code checks for "/dev/vsock" existence but, somehow, still tries to load the kernel module and it is not able to.

# Steps to reproduce

Run WSL2 with /etc/wsl.conf as:

```
[boot]
systemd=true
command = /bin/bash -c 'chown -v root:kvm /dev/kvm && chmod 660 /dev/kvm'

[automount]
enabled = true
root = /
options = "metadata,uid=1000,gid=1000,umask=077,fmask=11,case=off"
mountFsTab = true

[network]
hostname = ruggedbuntu
generateHosts = false
generateResolvConf = false

[interop]
enabled = true
appendWindowsPath = true

[user]
default = rafaeldtinoco

[wsl2]
nestedVirtualization = true
```

and install lxd and try to run a VM.

**Comment by tomponline** [comment]
What does `lsmod` show?

**Comment by rafaeldtinoco** [comment]
> (and it likely won't as that's what LXD and modprobe both check), then you have some subset of vsock but not the subset we require.

Alright, let me find the kernel options and document here before closing this one the. Thanks for the answer @stgraber

**Comment by stgraber** [comment]
I suspect you get the kernel entry you showed from the `vsock` module getting loaded (built-in in your case), but what LXD needs is `vhost_vsock`.

**Comment by rafaeldtinoco** [comment]
Hum, funny.. I believe the missing kconfig option is CONFIG_VIRTIO_VSOCKETS but, when enabled, WSL2 won't boot. That might be because WSL2 CONFIG_HYPERV_VSOCKETS built-in (probably because of HyperV for the first hypervisor, which might also use CONFIG_VIRTIO_VSOCKETS_COMMON). I'll try to dig into that later today/tomorrow.

Thanks for now!

**Comment by rafaeldtinoco** [comment]
Alright, my bad.. I think I made it work now.. I added `CONFIG_VIRTIO_VSOCKETS_COMMON` and it seems to have worked. I thought I had it yesterday... if you did not change the release from yesterday to today (snap would automatically update) then it seems okay now (if you did, then the latest release fixed the issue).

**Comment by rafaeldtinoco** [comment]
Feel free to close this issue after reading my comments. Thanks a lot for the support, as usual. You know I'm a big fan of the project.

**Comment by tomponline** [comment]
Thanks!
