### ISSUE TITLE
Example YAML in project configuration is wrong

### ISSUE THREAD

**Issue by ru-fu** [lxc/lxd#11493]
When editing the project configuration, the description at the top of the YAML file says:

```
### This is a YAML representation of the project.
### Any line starting with a '# will be ignored.
###
### A project consists of a set of features and a description.
###
### An example would look like:
### name: my-project
### features:
###   images: True
###   profiles: True
### description: My own project
###
### Note that the name is shown but cannot be changed
```

However, you have to specify features as:
```
config:
  features.images: "true"
  features.profiles: "false"
```
Not under a `features` field.

**Comment by sri-srikanth** [comment]
Hey!
I am a Computer Science student at the University of Texas at Austin taking a Virtualization course. My two groupmates and I were wondering if we could contribute to resolving this issue. Please let me know if this would be possible and we can get started.

**Comment by tomponline** [comment]
Thanks!
