### ISSUE TITLE
`lxc launch ubuntu-daily:lunar` fails with `i/o timeout` on `ppc64el`

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#11501]
# Required information

LXD snap version: `lxd 5.11-ad0b61e`
Arch: `ppc64el`

# Issue description

The Canonical server team is trying to run DEP8 tests on all the supported architectures. One test that is passing on all arches but `ppc64el` due to a `i/o timeout` during the first `lxc launch`.

LXD debug logs can be found at https://autopkgtest.ubuntu.com/results/autopkgtest-lunar-ahasenack-samba-dep8-troubleshooting/lunar/ppc64el/s/samba/20230322_131759_d1066@/log.gz, search for `13:16:45`:

```
Mar 22 13:16:45 autopkgtest lxd.daemon[4292]: time="2023-03-22T13:16:45Z" level=debug msg="Instance operation lock created" action=create instance=member-server project=default reusable=false
...
Mar 22 13:16:45 autopkgtest lxd.daemon[4292]: time="2023-03-22T13:16:45Z" level=info msg="Image unpack started" imageFile=/var/snap/lxd/common/lxd/images/6e24b9324ad0e87a7ff8387d4d7bbea6478342056b1c083565650b6e7f002e89 volName=member-server
...
Mar 22 13:17:35 autopkgtest lxd.daemon[4292]: time="2023-03-22T13:17:34Z" level=debug msg="Instance operation lock finished" action=create err="Instance \"create\" operation timed out after 30s" instance=member-server project=default reusable=false
...
Mar 22 13:17:44 autopkgtest lxd.daemon[4292]: time="2023-03-22T13:17:44Z" level=info msg="Image unpack stopped" imageFile=/var/snap/lxd/common/lxd/images/6e24b9324ad0e87a7ff8387d4d7bbea6478342056b1c083565650b6e7f002e89 volName=member-server
```

**Comment by tomponline** [comment]
My thinking is that we should remove the instance create operation lock timeout (set it to -1) as we don't know the upper bounds of how long an instance unpack should take for every combination of host system and image size.

**Comment by panlinux** [comment]
[ppc64el-lxc-launch-timeout-13:16:45.log](https://github.com/lxc/lxd/files/11043877/ppc64el-lxc-launch-timeout-13.16.45.log)
I attached the log file because the link will expire as soon as the PPA is destroyed.
