### ISSUE TITLE
Lint issues with autogenerated code from lxd-generate

### ISSUE THREAD

**Issue by hemanthnakkina** [lxc/lxd#11505]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04

# Issue description

Project https://github.com/openstack-snaps/sunbeam-microcluster uses lxd-generate to autogenerate database mapper files.
However ``make check`` has lint issues with respect to autogenerated code

```
$ make check
CGO_LDFLAGS_ALLOW="-Wl,-z,now" golangci-lint run --timeout 5m
revive -set_exit_status ./...
database/config.mapper.go:273:23: parameter 'ctx' seems to be unused, consider removing or renaming it as _
database/jujuuser.mapper.go:273:21: parameter 'ctx' seems to be unused, consider removing or renaming it as _
database/node.mapper.go:373:17: parameter 'ctx' seems to be unused, consider removing or renaming it as _
make: *** [Makefile:30: check-static] Error 1
```

This is specifically in Delete<> function generated by ``//go:generate mapper method -i -d github.com/canonical/microcluster/cluster -e ConfigItem DeleteOne-by-Key table=<>``.
 
Following has fixed the issue
```
$ git diff database/config.mapper.go
diff --git a/database/config.mapper.go b/database/config.mapper.go
index 88e37a9..ba47988 100644
--- a/database/config.mapper.go
+++ b/database/config.mapper.go
@@ -270,7 +270,7 @@ func CreateConfigItem(ctx context.Context, tx *sql.Tx, object ConfigItem) (int64
 
 // DeleteConfigItem deletes the ConfigItem matching the given key parameters.
 // generator: ConfigItem DeleteOne-by-Key
-func DeleteConfigItem(ctx context.Context, tx *sql.Tx, key string) error {
+func DeleteConfigItem(_ context.Context, tx *sql.Tx, key string) error {
        stmt, err := cluster.Stmt(tx, configItemDeleteByKey)
        if err != nil {
                return fmt.Errorf("Failed to get \"configItemDeleteByKey\" prepared statement: %w", err)
```

# Steps to reproduce

 1. git clone https://github.com/openstack-snaps/sunbeam-microcluster.git
 2. CGO_LDFLAGS_ALLOW="-Wl,-z,now" make check

**Comment by tomponline** [comment]
@masnax are you able to take a look at this? (I've optimistically assigned it to you but can change if not suitable, thanks).
