### ISSUE TITLE
LXD selects disk-kvm.img for Ubuntu VMs by default and it's not suitable for general purposes

### ISSUE THREAD

**Issue by nobuto-m** [lxc/lxd#11516]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: `5.19.0-35-generic #36~22.04.1-Ubuntu`
   * LXD version: `5.12-c63881f`
   * Storage backend in use: dir

# Issue description

LXD selects disk-kvm.img over disk1.img by putting the `22.04`/`jammy` alias on it.

```
$ lxc image list ubuntu: release=jammy arch=amd64 type=virtual-machine serial=20230302 -c lfpts
+------------+--------------+--------+-----------------+----------+
|   ALIAS    | FINGERPRINT  | PUBLIC |      TYPE       |   SIZE   |
+------------+--------------+--------+-----------------+----------+
| j (9 more) | 8b150d2b1813 | yes    | VIRTUAL-MACHINE | 620.06MB |  ## <- disk-kvm.img
+------------+--------------+--------+-----------------+----------+
|            | d900c08af2be | yes    | VIRTUAL-MACHINE | 652.50MB |  ## <- disk1.img
+------------+--------------+--------+-----------------+----------+
```

So by creating an Ubuntu VM, that's going to be half functional state for some cases and it can cause mixed user experience.

1. the VM won't recognized CPU threads more than 64
https://bugs.launchpad.net/ubuntu/+source/linux-kvm/+bug/1967131
2. the VM won't have some kernel modules available in a normal system

As you can see in a response to the bug report above, -kvm flavor wasn't supposed to be used for general purposes.

# Steps to reproduce

1. Create a VM with `ubuntu:22.04`
1. Check the running kernel and the existence of `iavf` and `i40evf` module for example.

```
$ lxc launch -e ubuntu:22.04 --vm test

$ lxc exec test -- uname -a
Linux test 5.15.0-1028-kvm #33-Ubuntu SMP Tue Jan 24 18:41:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ lxc exec test -- modinfo iavf i40evf
modinfo: ERROR: Module iavf not found.
modinfo: ERROR: Module i40evf not found.
```

or check the maximum number of CPU threads that can be recognized

```
$ lxc exec test -- grep -w CONFIG_NR_CPUS /boot/config-5.15.0-1028-kvm
CONFIG_NR_CPUS=64
```

# Information to attach

```
$ lxc image list ubuntu: release=jammy arch=amd64 type=virtual-machine serial=20230302 --format yaml
- auto_update: false
  properties:
    architecture: amd64
    description: ubuntu 22.04 LTS amd64 (release) (20230302)
    label: release
    os: ubuntu
    release: jammy
    serial: "20230302"
    type: disk-kvm.img
    version: "22.04"
  public: true
  expires_at: 2027-04-21T00:00:00Z
  profiles: []
  aliases:
  - name: "22.04"
    description: ""
  - name: 22.04/amd64
    description: ""
  - name: j
    description: ""
  - name: j/amd64
    description: ""
  - name: jammy
    description: ""
  - name: jammy/amd64
    description: ""
  - name: lts
    description: ""
  - name: lts/amd64
    description: ""
  - name: default
    description: ""
  - name: default/amd64
    description: ""
  architecture: x86_64
  cached: false
  filename: ubuntu-22.04-server-cloudimg-amd64-lxd.tar.xz
  fingerprint: 8b150d2b1813da98b1fe2984a8ad7f9531c57c4a0689bbabf1f8322e853c4032
  size: 650183064
  type: virtual-machine
  created_at: 2023-03-02T00:00:00Z
  last_used_at: 0001-01-01T00:00:00Z
  uploaded_at: 2023-03-02T00:00:00Z
- auto_update: false
  properties:
    architecture: amd64
    description: ubuntu 22.04 LTS amd64 (release) (20230302)
    label: release
    os: ubuntu
    release: jammy
    serial: "20230302"
    type: disk1.img
    version: "22.04"
  public: true
  expires_at: 2027-04-21T00:00:00Z
  profiles: []
  aliases: []
  architecture: x86_64
  cached: false
  filename: ubuntu-22.04-server-cloudimg-amd64-lxd.tar.xz
  fingerprint: d900c08af2be6e31f1f452a510b27ea6b1046df578d4460b009d6b3a701990f0
  size: 684196248
  type: virtual-machine
  created_at: 2023-03-02T00:00:00Z
  last_used_at: 0001-01-01T00:00:00Z
  uploaded_at: 2023-03-02T00:00:00Z
```

**Comment by stgraber** [comment]
Hey there,

I personally agree that the linux-kvm kernel causes us a lot of issues for no real benefit.

However the problem isn't with the image that LXD selects so much as the decision of what kernel is put into that image.

Would you mind reporting this against the linux-kvm package on Launchpad so the kernel config can be tweaked to work in your case?

I seem to remember @xnox telling me that linux-kvm is getting phased out starting with lunar, effectively using linux-virtual there instead.

The problem is with the older releases as any change we make there will break someone... We can't just have CPC switch the images to linux-virtual overnight so our best bet is to fix specific kernel config issues on the older releases and move away from the kernel on newer ones.


Note that the LXD team also produces Ubuntu images on the community image server and those all come with the virtual kernel out of the box. You'd launch such images with `images:ubuntu/22.04/cloud`

**Comment by nobuto-m** [comment]
> Would you mind reporting this against the linux-kvm package on Launchpad so the kernel config can be tweaked to work in your case?

As above, I did
https://bugs.launchpad.net/ubuntu/+source/linux-kvm/+bug/1967131
and probably more reports but as you understand there was nobody seriously trying to "fix" it since all knew -kvm is not going to be used for serious workload.

> Note that the LXD team also produces Ubuntu images on the community image server and those all come with the virtual kernel out of the box. You'd launch such images with images:ubuntu/22.04/cloud

I'm aware of it and I can request non-kvm flavor explicitly with ubuntu: too. So I thought it was LXD who is putting the alias on the kvm flavor instead of cloud-images.ubuntu.com's server side.

```
$ lxc image list ubuntu: release=jammy arch=amd64 type=virtual-machine serial=20230302 -c lfpts
+------------+--------------+--------+-----------------+----------+
|   ALIAS    | FINGERPRINT  | PUBLIC |      TYPE       |   SIZE   |
+------------+--------------+--------+-----------------+----------+
| j (9 more) | 8b150d2b1813 | yes    | VIRTUAL-MACHINE | 620.06MB |  ## <- disk-kvm.img
+------------+--------------+--------+-----------------+----------+
|            | d900c08af2be | yes    | VIRTUAL-MACHINE | 652.50MB |  ## <- disk1.img
+------------+--------------+--------+-----------------+----------+
```

**Comment by stgraber** [comment]
Yes, LXD is the one setting the alias on the disk-kvm when available, but we can't change that as that will break everyone who actually relies on this today. `disk-kvm.img` is also the correct filetype for a cloud image to be run on qemu/kvm, so it would be wrong to change it anyway.

**Comment by nobuto-m** [comment]
> Yes, LXD is the one setting the alias on the disk-kvm when available, but we can't change that as that will break everyone who actually relies on this today.

I totally understand the importance of the backward compatibility and protecting the current user workflow. At the same time, I just hoped we could change this behavior in some major versions of LXD with release notes.

> disk-kvm.img is also the correct filetype for a cloud image to be run on qemu/kvm, so it would be wrong to change it anyway.

I totally get what you are stating and I agree that's the right way. On the other hand, in reality, disk1.img is already using linux-virtual meta flavor instead of -generic and it's widely (widely is subjective) used on QEMU/kvm. glance-simplestreams-sync charm pulls disk1.img instead of disk-kvm.img for QEMU/KVM on Charmed OpenStack, multipass also pulls an image with linux-virtual for QEMU/KVM, and uvt-kvm pulls non-kvm flavor QEMU/KVM and so on.

I've seen you reopened:
https://bugs.launchpad.net/ubuntu/+source/linux-kvm/+bug/1967131
Let's see how it goes.
