### ISSUE TITLE
Report download progress over events API

### ISSUE THREAD

**Issue by rrva** [lxc/lxd#1151]
If I do 

```
lxc launch images:centos/7/amd64 my-container
```

And the image does not exist locally, I get no feedback whatsoever, command just blocks.

In the lxd.log I have

msg="Image not in the db, downloading it"

But that's not enough. I want to know the size of the image being downloaded and that it is being downloaded ad the lxc launch terminal. Progress bar would be nice as well.

**Comment by stgraber** [comment]
Yeah, progress information on server side downloads is blocked on #167
