### ISSUE TITLE
Discoverability of a way to change the # of CPU cores and memory amount for a VM

### ISSUE THREAD

**Issue by nobuto-m** [lxc/lxd#11518]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: `5.15.0-67-generic #74-Ubuntu`
   * LXD version: `5.0.2-838e1b2`
   * Storage backend in use: dir

# Issue description

By default, LXD creates an instance with 1 CPU core and 1GB of memory when `--vm` is specified but nothing else. That's okay for the initial testing. However, whenever an user starts running their workload it's easy to invoke OOM even in an idle state (e.g. https://github.com/canonical/microceph/issues/112).

In the help of `launch`, it's actually hard to see how those CPU and memory limits can be changed although I personally know the answer as:
https://linuxcontainers.org/lxd/docs/latest/howto/instances_create/#launch-a-virtual-machine

A few suggestions here,

1. it might be a good idea to have abbreviated config options.
   - `--cpu 4` instead of `--config limits.cpu=4`
   - `--memory 8` instead of `--config limits.memory=8GiB`
   - `--disk 32` instead of `-d root,size=32GiB`
1. it might be a good idea to create some preset VM profiles(flavors) in `lxd init`
   - e.g. "Do you want to create preset flavors for VMs?"
   - So users leverage it easily such as `lxc launch --vm --profile vm.large`
1. or extend the description of `--type`
   - including putting a link to https://aws.amazon.com/ec2/instance-types/ if we really want to encourage to use this flag (I doubt so due to the difficulty to keep it up with each public cloud update though)

```
$ lxc launch -h
Description:
  Create and start instances from images

Usage:
  lxc launch [<remote>:]<image> [<remote>:][<name>] [flags]

Examples:
  lxc launch ubuntu:22.04 u1

  lxc launch ubuntu:22.04 u1 < config.yaml
      Create and start a container with configuration from config.yaml

  lxc launch ubuntu:22.04 v1 --vm
      Create and start a virtual machine

Flags:
  -c, --config                Config key/value to apply to the new instance
      --console[="console"]   Immediately attach to the console
  -d, --device                New key/value to apply to a specific device
      --empty                 Create an empty instance
  -e, --ephemeral             Ephemeral instance
  -n, --network               Network name
      --no-profiles           Create the instance with no profiles applied
  -p, --profile               Profile to apply to the new instance
  -s, --storage               Storage pool name
      --target                Cluster member name
  -t, --type                  Instance type
      --vm                    Create a virtual machine
```

**Comment by tomponline** [comment]
> 1. `--disk 32` instead of (is there a way to specify disk space on the fly actually?)

Yes, see https://discuss.linuxcontainers.org/t/lxd-5-8-has-been-released/15686#device-override-on-init-and-launch-4

**Comment by nobuto-m** [comment]
> > 1. `--disk 32` instead of (is there a way to specify disk space on the fly actually?)
> 
> Yes, see https://discuss.linuxcontainers.org/t/lxd-5-8-has-been-released/15686#device-override-on-init-and-launch-4

Thank you for the pointer. I've updated the description :-)

**Comment by stgraber** [comment]
1) I'm very strongly opposed to adding more flags to those commands, it's a very slippery slope and I don't want LXD's init/launch to turn into `docker run`
2) We used to have some of those in the past, but that was causing more confusion that good as you then get into having to immediately understand profile ordering as well as having to also populate those across projects.
3) The instance type could indeed be used for that though we've seen somewhat little use of that feature so far.

I think the way we're going to address this issue is by extending the help message for init/launch to include two more examples, one using a cloud instance type and one using `-c` to specify limits.
