### ISSUE TITLE
Images being downloaded during server restart get stuck in downloading state

### ISSUE THREAD

**Issue by rrva** [lxc/lxd#1152]
If I do

lxc launch images:centos/7/amd64 my-container

And then, while the image is downloading

systemctl restart lxd

This image download does not seem to progress but is stuck in downloading state.

**Comment by stgraber** [comment]
What do you mean by stuck in downloading state?

Server operation state isn't persistent and as the download is performed by the server, it can't possibly be stuck in downloading state. Instead when the server returns, it will have not know about that image.

**Comment by stgraber** [comment]
Been a couple of months without more details, closing.
