### ISSUE TITLE
Make sure devices are cleaned up on QEMU crashes

### ISSUE THREAD

**Issue by markrattray** [lxc/lxd#11520]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info": see attached `lxd-issues_11520_lxc-info.txt`

# Issue description

Very similar situation with ticket [#11089](https://github.com/lxc/lxd/issues/11089) where a VM crashes for some reason and then cannot start because the MAC address is still bound to an old virtual macvlan interface.

```
someadmin@ud2204-iph-lxd03:~$ lxc start mw2022-ivm-cxv01
Error: Failed to start device "eth0": Failed adding link: Failed to run: ip link add name mac03537ca4 link eno1 address 00:16:3e:d1:00:d7 allmulticast on up type macvtap mode bridge: exit status 2 (RTNETLINK answers: Address already in use)
Try `lxc info --show-log mw2022-ivm-cxv01` for more info

someadmin@ud2204-iph-lxd03:~$ lxc info --show-log mw2022-ivm-cxv01
Name: mw2022-ivm-cxv01
Status: STOPPED
Type: virtual-machine
Architecture: x86_64
Location: ud2204-iph-lxd03.domain.tld
Created: 2023/03/02 16:01 EST
Last Used: 2023/03/26 09:34 EDT
Error: open /var/snap/lxd/common/lxd/logs/mw2022-ivm-cxv01/qemu.log: no such file or directory

someadmin@ud2204-iph-lxd03:~$ ip link show | grep -B 1 '00:16:3e:d1:00:d7'
184: mac80680caa@eno1: <BROADCAST,MULTICAST,ALLMULTI,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 500
    link/ether 00:16:3e:d1:00:d7 brd ff:ff:ff:ff:ff:ff

someadmin@ud2204-iph-lxd03:~$ ip link delete mac80680caa

someadmin@ud2204-iph-lxd03:~$ lxc start mw2022-ivm-cxv01
```

# Steps to reproduce

I am unable to reproduce the crash at the moment however 3 Windows VMs have recently crashed and required the same `ip link delete` command to release the MAC address to start the VM.

# Information to attach

 - [x] Any relevant kernel output (`dmesg`): see attached `lxd-issues_11520_dmesg-T.txt`
 - [ ] Container log (`lxc info NAME --show-log`): `Error: open /var/snap/lxd/common/lxd/logs/mw2022-ivm-cxv01/qemu.log: no such file or directory`
 - [x] Container configuration (`lxc config show NAME --expanded`): see attached `lxd-issues_11520_lxc-config-show_mw2022-ivm-cxv01.txt`
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log): see attached `lxd-issues_11520_lxd-daemon-log*.txt`
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
 - [x] VM qemu.old.log: see attached `lxd-issues_11520_mw2022-ivm-cxv01_qemu-old-log.txt`
 - [x] Snap LXD auto refresh date: does not match VM crash `5.12-c63881f @ 6 days ago, at 09:15 EDT`
 - [x] grep syslog for crashed VMs: see attached `lxd-issues_11520_syslog-grep-vms.txt`

[lxd-issues_11520_lxc-info.txt](https://github.com/lxc/lxd/files/11088411/lxd-issues_11520_lxc-info.txt)
[lxd-issues_11520_dmesg-T.txt](https://github.com/lxc/lxd/files/11088414/lxd-issues_11520_dmesg-T.txt)
[lxd-issues_11520_lxc-config-show_mw2022-ivm-cxv01.txt](https://github.com/lxc/lxd/files/11088419/lxd-issues_11520_lxc-config-show_mw2022-ivm-cxv01.txt)
[lxd-issues_11520_lxd-daemon-log.txt](https://github.com/lxc/lxd/files/11088421/lxd-issues_11520_lxd-daemon-log.txt)
[lxd-issues_11520_mw2022-ivm-cxv01_qemu-old-log.txt](https://github.com/lxc/lxd/files/11088426/lxd-issues_11520_mw2022-ivm-cxv01_qemu-old-log.txt)
[lxd-issues_11520_syslog-grep-vms.txt](https://github.com/lxc/lxd/files/11088432/lxd-issues_11520_syslog-grep-vms.txt)

**Comment by tomponline** [comment]
Have you checked for OOM situations?

**Comment by markrattray** [comment]
Good morning... Thanks for the super quick response.

No. Will do now.

FYI I'm just uploading the attachments now, needed to create the ticket for the ticket number.

**Comment by markrattray** [comment]
Memory info:
```
someadmin@us2204-iph-lxd03:/home/someadmin# free -h
               total        used        free      shared  buff/cache   available
Mem:           377Gi       247Gi        38Gi        80Gi        91Gi        45Gi
Swap:          8.0Gi       3.3Gi       4.7Gi

someadmin@us2204-iph-lxd03:/home/someadmin# grep -i kill /var/log/syslog

someadmin@us2204-iph-lxd03:/home/someadmin# grep -i memory /var/log/syslog

someadmin@us2204-iph-lxd03:/home/someadmin# grep -i ooo /var/log/syslog/
```

**Comment by markrattray** [comment]
I think the crash for Windows VM instance mw2022-ivm-cxv01 was this line in the attached [lxd-issues_11520_dmesg-T.txt](https://github.com/lxc/lxd/files/11088414/lxd-issues_11520_dmesg-T.txt):
```
[Mon Mar 27 22:10:47 2023] set kvm_intel.dump_invalid_vmcs=1 to dump internal KVM state.
```
because the `qemu.old.log` [lxd-issues_11520_mw2022-ivm-cxv01_qemu-old-log.txt](https://github.com/lxc/lxd/files/11088426/lxd-issues_11520_mw2022-ivm-cxv01_qemu-old-log.txt) has a similar mod time:
```
someadmin@us2204-iph-lxd03:/home/someadmin# ls -lh /var/snap/lxd/common/lxd/logs/mw2022-ivm-cxv01/
total 16K
-rw-r----- 1 root root 4.7K Mar 26 09:34 qemu.conf
srwxr-x--- 1 root root    0 Mar 26 09:34 qemu.console
-rw-r--r-- 1 root root    0 Mar 26 09:34 qemu.early.log
-rw-r--r-- 1 root root 1.3K Mar 27 22:11 qemu.log.old
srwxr-x--- 1 root root    0 Mar 26 09:34 qemu.monitor
srwxr-x--- 1 root root    0 Mar 26 09:34 qemu.spice
srwxr-xr-x 1 root root    0 Mar 26 09:34 virtio-fs.config.sock
-rw-r--r-- 1 root root  198 Mar 26 09:34 virtiofsd.pid

```

**Comment by tomponline** [comment]
Sounds like it could be a kernel issue:

https://forum.proxmox.com/threads/vm-shutdown-kvm-entry-failed-hardware-error-0x80000021.109410/

**Comment by markrattray** [comment]
Could very well be.... 5.19.0-35 has messed with my devices at home so I now have missing graphics and sound devices in them. I've done an update to -38 and other things then rebooted the host, but I think these are just security related fixes.

**Comment by markrattray** [comment]
No joy after the update and reboot. Just created a new Windows VM and during the sysprep stage it died and I have to delete the macvlan interface manually.

from `qemu.log.old`:
```
someadmin@us2204-iph-lxd03:/home/someadmin# cat /var/snap/lxd/common/lxd/logs/mw2022-ivm-test01/qemu.log.old
qemu-system-x86_64: Issue while setting TUNSETSTEERINGEBPF: Invalid argument with fd: 48, prog_fd: -1
KVM: entry failed, hardware error 0x80000021

If you're running a guest on an Intel machine without unrestricted mode
support, the failure can be most likely due to the guest entering an invalid
state for Intel VT. For example, the guest maybe running in big real mode
which is not supported on less recent Intel processors.

EAX=00000008 EBX=00040ee0 ECX=800003ac EDX=00000000
ESI=32e2f000 EDI=32e26040 EBP=813d2810 ESP=813d2790
EIP=00008000 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=1 HLT=0
ES =0000 00000000 ffffffff 00809300
CS =8000 7ff80000 ffffffff 00809300
SS =0000 00000000 ffffffff 00809300
DS =0000 00000000 ffffffff 00809300
FS =0000 00000000 ffffffff 00809300
GS =0000 00000000 ffffffff 00809300
LDT=0000 00000000 00000000 00000000
TR =0040 ff2a0000 00000067 00008b00
GDT=     ff2a1fb0 00000057
IDT=     00000000 00000000
CR0=00050032 CR2=7c3fa0b0 CR3=001ae002 CR4=00000000
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000000
Code=qemu-system-x86_64: ../hw/core/cpu-sysemu.c:77: cpu_asidx_from_attrs: Assertion `ret < cpu->num_ases && ret >= 0' failed.
```

**Comment by markrattray** [comment]
Good morning

So this ticket is mainly about not being able to start the instances following a crash due to the MAC address still being used on the previous iteration of the macvlan NIC. We know what to do and it's not too bad:

Try start the instance
```
lxc start {instance}
```
Get the MAC in the error and find the macvlan interface using it
```
ip link | grep -B 1 {mac-address}
```
Copy the macvlan NIC name before the @ and delete it
```
ip link delete {macvlan-nic-name}
```

The other reason is to help us to find a workable solution to run WS2022 VMs in LXD when we run into this scenario, which looks like a combination of things, but mainly older CPUs, TDP MMU, and not so good kernel updates.

Thanks for the thread link and I've read through all of it. It helped me find this document which has some (hopefully) useful advice:
https://pve.proxmox.com/wiki/Upgrade_from_6.x_to_7.0#KVM:_entry_failed.2C_hardware_error_0x80000021

- intel-microcode is already up to date by default.
- I've gone for disabling `tdp_mmu` via the modprobe config module option.

I did this late last night, so we should know by Monday whether this helps.

Have a great weekend !

**Comment by markrattray** [comment]
Good morning, and hope you had a good weekend.

Some good news is that that modprobe method disabling TDP MMU / Intel EPT from the Proxmox upgrade KB above, seems to have stabilised these Windows Sever 2022 VMs.

Sadly the CPU is old but does support this apparently (last feature right at the bottom):
https://www.intel.com/content/www/us/en/products/sku/75277/intel-xeon-processor-e52680-v2-25m-cache-2-80-ghz/specifications.html

**Question:** would the LXD team recommend that I should report it to the Canonical Kernel Team as I do know that 5.19.0-35 onwards is causing a bit of havoc with other things as well ?

Thanks

**Comment by markrattray** [comment]
Raised ticket:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2015455
