### ISSUE TITLE
Snapshot delete with the API race

### ISSUE THREAD

**Issue by edlerd** [lxc/lxd#11538]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04.2
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.19.0-38-generic
   * LXC version: 5.12
   * LXD version: 5.12
   * Storage backend in use: zfs

# Issue description

I hit the single-snapshot-delete API endpoint with 50 parallel requests `1.0/instances/foo/snapshots/bar` `DELETE` and fetch the operations for each of them `1.0/operations/my-id/wait?timeout=10`.
For many of the operations, I get an error back:
"Instance snapshot record count doesn't match instance snapshot volume record count"
This seems like a race condition due to the many parallel requests.
Eventually, after some time, all 50 snapshots are removed successfully.
I'd expect no error in that case.

# Steps to reproduce

 1. Create a lot of snapshots for an instance
 2. Trigger 50 parallel delete snapshot requests on that instance via the HTTP API
 3. Fetch the operation for all 50 delete requests via the HTTP API
 4. See some operations return the error "Instance snapshot record count doesn't match instance snapshot volume record count"

**Comment by gabrielmougard** [comment]
@tomponline indeed, I don't see any lock mechanism based on the snapshot name between  `DeleteInstanceSnapshot` and `GenerateInstanceBackupConfig` (both in `lxd/storage/backend_lxd.go`). Is there a reason for it ?

**Comment by tomponline** [comment]
@gabrielmougard yes I think we should make use of something like this:

```
parentName, _, _ := api.GetParentAndSnapshotName(d.name)
unlock := locking.Lock(context.TODO(), fmt.Sprintf("instance_delete_%s_%s",d.Project().Name, d.Name()))
defer unlock()
```

at the top of `func (d *lxc) delete(force bool)` and `func (d *qemu) delete(force bool)`.

**Comment by gabrielmougard** [comment]
@tomponline While working on a test scenario, I discovered something else : Having an instance, let's say I want to concurrently create 100 snapshots of like so : 

```go
...
// Create a lot of snapshots for an instance
var wg sync.WaitGroup
for i := 0; i < 100; i++ {
	go func(i int) {
		wg.Add(1)
		fmt.Println(fmt.Sprintf("Creating snapshot snap-%d", i))
		snap := api.InstanceSnapshotsPost{
			Name: fmt.Sprintf("snap-%d", i),
		}

		opCreate, err := srv.CreateInstanceSnapshot("snap-del-api-race", snap)
		if err != nil {
			panic(err)
		}

		err = opCreate.Wait()
		if err != nil {
			panic(err)
		}

		wg.Done()
		fmt.Println(fmt.Sprintf("snap-%d created", i))
	}(i)
}

wg.Wait()
fmt.Println("All snapshots created")
```

I aslo end up panicking in the snapshot creation after a random Wait() with the exact same mentionned error `Instance snapshot record count doesn't match instance snapshot volume record count`

**Comment by gabrielmougard** [comment]
@tomponline should I apply your comment for `startCommon()` as well ?
