### ISSUE TITLE
REST API state lags

### ISSUE THREAD

**Issue by saschathiergart** [lxc/lxd#11532]
# Required information

 * Distribution: Ubuntu 
 * Distribution  `Linux 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`
   * LXC version: 5.12
   * LXD version: 5.12

# Issue description

After a POST request to the `1.0/instances` endpoint, i get a valid 201 response. When making a GET request to the same resource that i just created i get a 404. It seems like i have to add a delay between the two operations to make it work. 

# Steps to reproduce
see issue description

**Comment by tomponline** [comment]
Can you show the full api request including post payload and response. I suspect you are getting an operation response and you need to then wait for the operation to complete successfully.

**Comment by stgraber** [comment]
Closing as I'd be shocked if it was something else ;)

Indeed most of our API endpoints don't block, they create a background operation and return the initial details about that.
It's then your responsibility to wait for the operation to complete, either by calling `GET /1.0/operations/UUID/wait` or if you've got yourself a fancier client, by leveraging `/1.0/events` to get live events about operations (in which case you should make sure to connect to the events endpoint prior to sending requests through).
