### ISSUE TITLE
LXD API: cannot stop a container if an SFTP session is open

### ISSUE THREAD

**Issue by dmitry-lyfar** [lxc/lxd#11539]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * LXD version: 5.12
   * Storage backend in use: dir

# Issue description

There is a bit of unexpected API’s behaviour when I’m trying to forcefully or non-forcefully stop a container instance whilst having an open SFTP session for the given instance. The UpdateInstanceState operation never returns on Wait(). It is fixable if I close the SFTP session prior to stopping the container.

On one hand, that seems reasonable (?) if the stop is not forceful given the open connection that we might not want to touch. However, when doing it forcefully, I would expect the container to shutdown regardless. I’ve created a minimal example to reproduce the issue, see below.

# Steps to reproduce

```
package main

import (
	"fmt"

	lxd "github.com/lxc/lxd/client"
	"github.com/lxc/lxd/shared/api"
)

const LxdSock = "/var/snap/lxd/common/lxd/unix.socket"

func main() {
	if srv, err := lxd.ConnectLXDUnix(LxdSock, nil); err == nil {
		imageServer, err := lxd.ConnectSimpleStreams("https://cloud-images.ubuntu.com/releases/", nil)
		if err != nil {
			panic(err)
		}

		alias, _, err := imageServer.GetImageAlias("22.04/amd64")
		if err != nil {
			panic(err)
		}

		image, _, err := imageServer.GetImage(alias.Target)
		if err != nil {
			panic(err)
		}

		req := api.InstancesPost{
			Name: "sftp-issue",
			Type: api.InstanceType("container"),
			Source: api.InstanceSource{
				Type:        "image",
				Fingerprint: image.Fingerprint,
				Project:     "default",
			},
		}
		op, err := srv.CreateInstanceFromImage(imageServer, *image, req)
		if err != nil {
			panic(err)
		}
		op.Wait()

		start := api.InstanceStatePut{
			Action:  "start",
			Timeout: 5,
			Force:   true,
		}

		upd, err := srv.UpdateInstanceState("sftp-issue", start, "")
		if err != nil {
			panic(err)
		}
		upd.Wait()

		sftp, err := srv.GetInstanceFileSFTP("sftp-issue")
		if err != nil {
			panic(err)
		}
		wd, _ := sftp.Getwd()
		fmt.Println(wd)

		stop := api.InstanceStatePut{
			Action:  "stop",
			Timeout: 5,
			Force:   true,
		}

		upd, err = srv.UpdateInstanceState("sftp-issue", stop, "")
		if err != nil {
			panic(err)
		}

		// sftp.Close() <-- uncomment it here to work
		err = upd.Wait()
		if err != nil {
			panic(err)
		}
		fmt.Print("We'll never be here unless we call sftp.Close() before Wait()")
	}
}
```

# Additional Information

I gave it a brief look out of curiosity, it seems that the problem is that on stopping, the stopForkfile() method cannot get the lock which is captured by the SFTP server here: [https://github.com/lxc/lxd/blob/master/lxd/instance/drivers/driver_lxc.go#L6634 1](https://github.com/lxc/lxd/blob/master/lxd/instance/drivers/driver_lxc.go#L6634)

LXD kills the operation after 5 mins then, which moves the instance state to STOPPED, but it does not seem to stop properly in this case.

**Comment by gabrielmougard** [comment]
@tomponline after analysing the problem, I had an idea on this but not sure if it's a good practice or if it's even a wishable feature : 
Basically some tasks like `stopForkFile()` have a rather 'high' priority over others (like an underlying SFTP session that is running and locking the forkfile forever if not closed) and shall be executed first. My question is, in these situations, could we implement a **priority lock** mechanism (in the `lxd/locking` package) that will force low priority lockers to wait until the high priority queue is drained before they are able to access the underlying lock. Following this concept : 

```go
defer func() { locking.HighPriorityLock(context.TODO(), d.forkfileRunningLockName())() }() // line 6805, in `stopForkFile()`
```

Would always be acquired before : 

```go
runUnlock := locking.Lock(context.TODO(), d.forkfileRunningLockName()) // A "normal" lock (understand low-priority), line 6634 in `FileSFTPConn()`
```

Could it solve the issue ?

**Comment by tomponline** [comment]
@gabrielmougard Hi, I don't think there is a need to introduce the concept of lock priorities, but rather manage the SFTP go routines differently. At the moment the management is rather simplistic, and the go routine running the SFTP server holds the lock for its entire duration.

However I think something more akin to how we manage the S3 miniod processes would be more appropriate, by maintaining a map of active SFTP routines, and manage adding/retrieving/removing entries via a short lived lock. Each entry could store a `Process` struct that would provide a cancellation function when we want to stop the session after a particular timeout.

https://github.com/lxc/lxd/blob/master/lxd/storage/s3/miniod/miniod.go

**Comment by gabrielmougard** [comment]
Thanks, I will look into it.
