### ISSUE TITLE
No mention about valid network types

### ISSUE THREAD

**Issue by nobuto-m** [lxc/lxd#11531]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: `5.15.0-67-generic #74-Ubuntu`
   * LXD version: 5.0.2-838e1b2

# Issue description

`lxc network create` takes `--type` but there is no explanation what are the valid networking types in the help.

It would be nice if the help itself gets extended into details. Or putting link the documentation[1] into the help may not be a bad idea so users can open it and continue reading it using their web browser (it's not ideal for airgapped environment though).

[1] https://linuxcontainers.org/lxd/docs/latest/howto/network_create/

`network create` is just one example but I see helps are sometimes brief and I had to look up the documentation anyway to come up with proper command line arguments.

```
$ lxc network create -h
Description:
  Create new networks

Usage:
  lxc network create [<remote>:]<network> [key=value...] [flags]

Flags:
      --target   Cluster member name
  -t, --type     Network type

Global Flags:
      --debug          Show all debug messages
      --force-local    Force using the local unix socket
  -h, --help           Print help
      --project        Override the source project
  -q, --quiet          Don't show progress information
      --sub-commands   Use with help or --help to view sub-commands
  -v, --verbose        Show all information messages
      --version        Print version number
```

**Comment by stgraber** [comment]
The reason why we keep it terse and indeed prefer people lookup the suitable documentation is that the CLI has no way to know what a particular LXD server may be supporting. Putting an exhaustive list there is also bound to get outdated and cause more confusion.

We have a similar issue with linking to the documentation. We don't know what LXD version the server you're talking to may be using and so linking to the latest documentation when you may be using 3.0 on the server side with none of the features being supported would lead to even more confusion.

In general, we prefer users go the other way around, that they look up the documentation for their LXD version which then gives them examples of how to use the CLI.

I'd rather we spend more effort in improving the documentation and its examples, than we spend efforts duplicating content in the CLI. In this instance, I think having a couple of examples in the CLI would be fine given how terse it is, but I wouldn't go further than that.
