### ISSUE TITLE
Unable to create containers after renaming cluster members

### ISSUE THREAD

**Issue by dbuteyn** [lxc/lxd#11534]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-69-generic
   * LXC version: 5.1.2
   * LXD version: latest/edge (git-b78805c)
   * Storage backend in use: ceph

# Issue description

Joined several nodes together using join tokens, tried to launch containers but unable to launch a container on any of the nodes.

# Steps to reproduce

 1. Create cluster using join tokens. Cluster members will be named by their IP address, regardless of `--name` value.
 2. Rename all members to something logical (eg. node1, node2, node3, etc) with `lxc cluster rename IP NAME`
 3. Trying to launch a container on any node will fail with `Error: Missing event connection with target cluster member`.

After renaming cluster members back to their original IP "names", it became possible to launch containers once again.

**Comment by tomponline** [comment]
Wrt to clusters being named by their ip please can you show the specific process you are using as that is not my experience with join tokens.

**Comment by dbuteyn** [comment]
Yea sure.

On the first node I ran `lxd init`, answering to make a new cluster.
For the remaining nodes I ran `lxd init`, answering to join the new cluster using a join token.

Join tokens were generated with `lxc cluster add "IP" --name "NAME"`

Note the node name being an IP address:
```
$ lxc cluster list-tokens
+---------------+-------------------+----------------------+
|     NAME      |    TOKEN          |      EXPIRES AT      |
+---------------+-------------------+----------------------+
| 192.168.6.123 | eyJzZXJ2ZXJfbm... | 2023/04/02 17:06 UTC |
+---------------+-------------------+----------------------+
```

**Comment by tomponline** [comment]
Hrm ok I usually just use "lxc cluster add {name}" the join token will contain the ips of server automatically.

**Comment by tomponline** [comment]
But the --name flag looks confusing so I'll check it out

**Comment by dbuteyn** [comment]
Documentation issue?
```
$ lxc cluster add
Description:
  Request a join token for adding a cluster member

Usage:
  lxc cluster add [[<remote>:]<member>] [flags]

Flags:
      --name   Cluster member name

Global Flags:
      --debug          Show all debug messages
...
```

**Comment by dbuteyn** [comment]
Aside from the `--name` flag, doesn't explain why commands break after renaming cluster members.

**Comment by tomponline** [comment]
Yes something's not right there

**Comment by stgraber** [comment]
`--name` is supported to align with `lxc config trust add`, but we shouldn't allow for both `--name` and a name being passed as an argument at the same time.

**Comment by stgraber** [comment]
I've confirmed that on a cluster of 3 servers, renaming two of them causes a lot of weirdness, inability to launch instances and errors accessing existing ones. We clearly seem to be missing some kind of notification when this happens (probably should trigger a round of heartbeats) as well as update to the existing event connections.
