### ISSUE TITLE
Starting User Services inside of LXD inside of Virtuozzo VPS failed

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#11548]
# Required information

 * Distribution: Ubuntu 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux 5.2.0 #1 SMP Tue Jan 25 12:49:12 MSK 2022 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 5.12
   * LXD version: 5.12
   * Storage backend in use: dir

# Issue description

User daemons don't start because the systemd user daemon does not start.

Everything else works except this (i.e. creating/starting/stopping/deleting containers, shell into the container, ssh into the container etc. etc.)

# Steps to reproduce

1. install LXD from source inside of a Virtuozzo VPS
2. spawn a LXD container
3. in container, create a new user
4. in container, loginctl enable-lingering
5. in container, start a simple user daemon

# Information to attach
```
root@container:~# systemctl start user@1001.service
Job for user@1001.service failed because the control process exited with error code.
See "systemctl status user@1001.service" and "journalctl -xeu user@1001.service" for details.
root@container:~# systemctl status user@1001.service
× user@1001.service - User Manager for UID 1001
     Loaded: loaded (/lib/systemd/system/user@.service; static)
    Drop-In: /usr/lib/systemd/system/user@.service.d
             └─timeout.conf
     Active: failed (Result: exit-code) since Wed 2023-04-05 15:27:45 UTC; 4s ago
       Docs: man:user@.service(5)
    Process: 484 ExecStart=/lib/systemd/systemd --user (code=exited, status=1/FAILURE)
   Main PID: 484 (code=exited, status=1/FAILURE)
     CGroup: /lxc.payload.container/user.slice/user-1001.slice/user@1001.service

Apr 05 15:27:45 container systemd[1]: Starting User Manager for UID 1001...
Apr 05 15:27:45 container systemd[484]: pam_unix(systemd-user:session): session opened for user mynewuser(uid=1001) by (uid=0)
Apr 05 15:27:45 container systemd[484]: Failed to create /lxc.payload.container/user.slice/user-1001.slice/user@1001.service/init.scope control group: Permission denied
Apr 05 15:27:45 container systemd[484]: Failed to allocate manager object: Permission denied
Apr 05 15:27:45 container systemd[1]: user@1001.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 15:27:45 container systemd[1]: user@1001.service: Failed with result 'exit-code'.
Apr 05 15:27:45 container systemd[1]: Failed to start User Manager for UID 1001.
```

**Comment by stgraber** [comment]
Can you test in a normal LXD setup, that is with LXD running on a physical system or VM?
I suspect it's Virtiozzo playing tricks with how the cgroup hierarchy is setup and not something we can do much about.

**Comment by srkunze** [comment]
I wanted to move my setup from a Raspberry Pi to a VPS. What I could do is to reset the new host and recreate it with a KVM. The hoster seem to offer both. Do you think it will not exhibit the same issue?

Is there anything else I can run on the host or container to provide you more information (before I format the host)?

**Comment by stgraber** [comment]
Having it run under KVM should avoid the issue.
I don't know that there's anything obvious we can capture to further debug this. OpenVZ/Virtuozzo kernels are known for having absolutely gigantic patchsets applied to them which can change a fair bit of how features like CGroups function, causing this kind of issue.

@mihalicyn has some past experience on that, but given this is a pretty unusual setup, I don't think it's worth the potentially massive amount of efforts to isolate what's wrong and trying to get the Virtuozzo folks to tweak their kernels.

**Comment by srkunze** [comment]
Using KVM now, systemd user services work.

**Comment by stgraber** [comment]
Good to hear!
