### ISSUE TITLE
Ceph volume of a crashed VM wasn't cleaned up

### ISSUE THREAD

**Issue by nobuto-m** [lxc/lxd#11546]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: `5.15.0-67-generic #74-Ubuntu`
   * LXD version: 5.12-c63881f
   * Storage backend in use: Ceph RBD

# Issue description

A Ceph RBD volume previously attached to a VM that crashed stays in the Ceph backend even after LXD deletes it from its index.

# Steps to reproduce

 1. Create a VM with Ceph RBD volume
 2. Crash the VM like having system OOM or sending a signal to intentionally trigger a crash
 3. Delete the VM
    - This step may give an error as follows. It succeeds at the second time or so.
```
$ lxc delete -f test-vm-1                                                                                                                                                               
Error: Error deleting storage volume: Failed to run: rbd --id admin --cluster ceph --pool lxd_remote unmap virtual-machine_test-vm-1: exit status 16 (rbd: sysfs write failed
rbd: unmap failed: (16) Device or resource busy)
```
 4. Check the backend status

```
$ lxc storage show remote
config:
  ceph.cluster_name: ceph
  ceph.osd.pg_num: "32"
  ceph.osd.pool_name: lxd_remote
  ceph.rbd.du: "false"
  ceph.rbd.features: layering,striping,exclusive-lock,object-map,fast-diff,deep-flatten
  ceph.user.name: admin
  volatile.pool.pristine: "true"
description: Distributed storage on Ceph
name: remote
driver: ceph
used_by:
- /1.0/images/72565f3fbae414d317b90569b6d7aa308c482fdf562aaf0c2eaa6e50fa39747b
- /1.0/images/8b150d2b1813da98b1fe2984a8ad7f9531c57c4a0689bbabf1f8322e853c4032
- /1.0/profiles/default
status: Created
locations:
- mc-1
- mc-2
- mc-3
```

^^^ volume for test-vm-1 has gone.

```
$ sudo microceph.rbd ls lxd_remote
image_72565f3fbae414d317b90569b6d7aa308c482fdf562aaf0c2eaa6e50fa39747b_ext4
image_8b150d2b1813da98b1fe2984a8ad7f9531c57c4a0689bbabf1f8322e853c4032_ext4
image_8b150d2b1813da98b1fe2984a8ad7f9531c57c4a0689bbabf1f8322e853c4032_ext4.block
lxd_lxd_remote
virtual-machine_test-vm-1
```

^^^ the volume is still in the backend

```
$ sudo microceph.rbd rm lxd_remote/virtual-machine_test-vm-1
2023-04-06T14:35:02.599+0000 7f5466a43640 -1 librbd::image::PreRemoveRequest: 0x55da0adc5b10 check_image_watchers: image has watchers - not removing
Removing image: 0% complete...failed.
rbd: error: image still has watchers
This means the image is still open or the client using it crashed. Try again after closing/unmapping it or waiting 30s for the crashed client to timeout.
```

^^^ can't be deleted.

```
ubuntu@mc-3:~$ sudo microceph.rbd info lxd_remote/virtual-machine_test-vm-1
rbd image 'virtual-machine_test-vm-1':
        size 100 MiB in 25 objects
        order 22 (4 MiB objects)
        snapshot_count: 0
        id: db08d2d43b8
        block_name_prefix: rbd_data.db08d2d43b8
        format: 2
        features: layering, exclusive-lock, object-map, fast-diff, deep-flatten
        op_features: 
        flags: 
        create_timestamp: Thu Apr  6 05:53:29 2023
        access_timestamp: Thu Apr  6 05:53:29 2023
        modify_timestamp: Thu Apr  6 05:53:29 2023
        parent: lxd_remote/image_8b150d2b1813da98b1fe2984a8ad7f9531c57c4a0689bbabf1f8322e853c4032_ext4@readonly
        overlap: 100 MiB

ubuntu@mc-3:~$ sudo microceph.rbd status lxd_remote/virtual-machine_test-vm-1
Watchers:
        watcher=192.168.122.205:0/718643190 client.46075 cookie=18446462598732840963
```

^^^ there is a watcher from a LXD host.

```
ubuntu@mc-2:~$ ip -br a
lo               UNKNOWN        127.0.0.1/8 ::1/128 
enp1s0           UP             192.168.122.205/24 metric 100 fe80::5054:ff:fed6:72cc/64 
enp7s0           UP             fe80::5054:ff:fe09:963e/64 
ovs-system       DOWN           
br-int           DOWN           
genev_sys_6081   UNKNOWN        fe80::9098:41ff:fe6f:ded3/64 
lxdovn1          DOWN           
tap5568b166      DOWN           


ubuntu@mc-2:~$ lsblk -I 251
NAME MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
rbd1 251:16   0  100M  0 disk 
```

^^^ on the host, the RBD volume is still attached to the host.

**Comment by tomponline** [comment]
Did the command `lxc delete -f test-vm-1` succeed? It looks like it failed from your report.

**Comment by tomponline** [comment]
> even after LXD deletes it from its index

I wasn't sure what you meant by that ^ What index?

**Comment by nobuto-m** [comment]
> Did the command `lxc delete -f test-vm-1` succeed? It looks like it failed from your report.

It eventually succeeded.

> This step may give an error as follows. It succeeds at the second time or so.

**Comment by nobuto-m** [comment]
> > even after LXD deletes it from its index
> 
> I wasn't sure what you meant by that ^ What index?

More precisely, it has gone from LXD database and command output (like lxc storage ...) I would say.

**Comment by tomponline** [comment]
Right, so when the `lxc delete` command succeeded everything was correctly cleaned up?

But the problem is that when the VM crashed it didn't clean up its active mounts/devices?

**Comment by nobuto-m** [comment]
> But the problem is that when the VM crashed it didn't clean up its active mounts/devices?

Please note that LXD is a hypervisor in this case. If I'm not mistaken, LXD is responsible for mounting an RBD volume on the host, then exposing it to a VM as a block device. It might be a QEMU issue, but I'm staring a report to the virtualization platform first.

**Comment by tomponline** [comment]
I'm still not clear precisely what the problem is though.
Are you saying that the problem is that the `lxc delete` command initially failed after the VM crash?

**Comment by nobuto-m** [comment]
> Are you saying that the problem is that the `lxc delete` command initially failed after the VM crash?

I just can't pinpoint what the root cause is. I'm reporting that by following the reproduction steps above, a discrepancy between LXD and a storage backend can happen.

**Comment by nobuto-m** [comment]
> Is the discrepancy gone after the `lxc delete` command has eventually succeeded?

Okay, to recap, the discrepancy is there even after `lxc delete` succeeded.

1. Create a VM with Ceph RBD volume
1. Crash the VM like having system OOM or sending a signal to intentionally trigger a crash
1. Delete the VM (by executing `lxc delete` multiple times until it succeeds)
1. Check the backend status (then there is a discrepancy)

**Comment by tomponline** [comment]
OK thanks for the clarification. Its the `lxc delete` lack of cleanup that is of primary concern, as that should have succeeded in cleaning up the resources. WRT to the crash not cleaning up resources, LXD doesn't currently detect when a guest VM has crashed and so would not trigger resource clean up.

**Comment by stgraber** [comment]
Yeah, there's no way for us to detect an hypervisor crash as the QMP hooks obviously don't get called in this situation.
We also can't wait on the process as we can only do that on our own children and so the logic would fail when LXD gets reloaded.

Given we should have had an established QMP connection at the moment of the crash, maybe we can detect that happening, then check for the QEMU process through its PID file and if absent, kicking the stop hook? @tomponline
