### ISSUE TITLE
Add request/response hooks to LXD client interface.

### ISSUE THREAD

**Issue by markylaing** [lxc/lxd#11545]
In LXD Cloud, for the region to create a resource in a particular cluster it is necessary to set a `LXD-Cloud-Cluster-Name` header on the request. This informs the cell of the cluster it should forward the request to (ignoring any other logic, such as colocating with other project resources). In addition, in order for the region to be aware of which cluster a resource is contained in, we set a `LXD-Cloud-Cluster-Name` header on response to a `GET` request for the resource as it passes through the cell.

As the LXD Client doesn't allow access to the raw request or response headers, so far we have been using a raw HTTP client to perform requests. This is ok but is clearly more brittle than using the proper client. See:
1. https://github.com/canonical/lxd-cloud/blob/11b942b9fba05c6853f062582fcb3b3faec75846/internal/storage/region/migration.go#L83-L97
2. https://github.com/canonical/lxd-cloud/blob/11b942b9fba05c6853f062582fcb3b3faec75846/internal/storage/region/migration.go#L137-L140
3. https://github.com/canonical/lxd-cloud/blob/11b942b9fba05c6853f062582fcb3b3faec75846/internal/storage/region/migration.go#L201-L231
4. https://github.com/canonical/lxd-cloud/blob/11b942b9fba05c6853f062582fcb3b3faec75846/internal/rest/consumer/instances_region.go#L1028-L1052
5. https://github.com/canonical/lxd-cloud/blob/11b942b9fba05c6853f062582fcb3b3faec75846/internal/rest/consumer/instances_region.go#L1054-L1082

In order to implement https://warthogs.atlassian.net/jira/software/c/projects/LXD/boards/54?modal=detail&selectedIssue=LXD-346 we need to set the cluster name header to target requests to a specific cluster when the certificate fingerprint has a match in the `targets` table. It would be problematic to change all instance, storage volume, and project creation requests to use a raw http client as in the examples above.

I would like to add two methods to the LXD Client interface to be listed under "Internal functions" as:
```golang
	HTTPRequestHook(func(request *http.Request) error)
	HTTPResponseHook(func(response *http.Response) error)
```

If the `HTTPRequestHook` hook is set, it will be run during `(*ProtocolLXD).rawQuery` just before the request is made. We can use this to set headers or perform any request transformations that may be required. Immediately after the hook is run it will be set back to nil to avoid any confusing behaviour when reusing the client. 

Similarly, if the `HTTPResponseHook` is set it will be run immediately after the HTTP response is returned (before it is parsed). We would use this to extract any response headers. Again after the hook is run it will be set to nil.

Each hook will need a mutex if we guarantee the client is safe for concurrent use (but I'm not sure that holds true for the internal methods?).

@stgraber discussed implementing something like this a number of ways, such as a method for setting headers to be used on the next request, and locking the client until response headers are read. I think this is the simplest and cleanest way of doing it. It does mean the user needs to be careful about manipulating the request/response body... but that's fairly obvious and the reason why it would be listed under internal.

@stgraber @tomponline what do you think?

**Comment by tomponline** [comment]
@markylaing would it be possible to use a transport round tripper wrapper as support was added for this in:

https://github.com/lxc/lxd/pull/11321

**Comment by tomponline** [comment]
See also https://github.com/lxc/lxd/pull/11318

**Comment by markylaing** [comment]
Ok thanks I'll look into that :+1:

**Comment by markylaing** [comment]
Yep we can use a `lxd.HTTPTransporter` wrapper to do this without changes to the interface (see https://github.com/canonical/lxd-cloud/pull/253). Thanks :+1:

**Comment by tomponline** [comment]
Excellent!
