### ISSUE TITLE
Packaging for Fedora 22 part 2

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1154]
This is a summary and continuation of #830. The target platform is Fedora 22.

##### Build LXD
```
sudo dnf install go lxc-devel
# ~/p is the working dir
export GOPATH=$HOME/p/go
mkdir -p $GOPATH
go get -v -u github.com/lxc/lxd
cd $GOPATH/src/github.com/lxc/lxd
make
```
##### Create a range of user and group id reserved for containers
```
echo "root:1000000:65536" | sudo tee -a /etc/subuid /etc/subgid
```
##### Start LXD server
```
sudo -E $GOPATH/bin/lxd --group wheel --verbose
```
```
WARN[09-28|12:37:41] apparmor_parser binary not found or apparmor fs not mounted. AppArmor disabled. 
INFO[09-28|12:37:41] LXD is starting                          path=/var/lib/lxd
INFO[09-28|12:37:41] Default uid/gid map: 
INFO[09-28|12:37:41]  - u 0 1000000 65536 
INFO[09-28|12:37:41]  - g 0 1000000 65536 
INFO[09-28|12:37:41] Init                                     driver=storage/dir
INFO[09-28|12:37:41] Looking for existing certificates        cert=/var/lib/lxd/server.crt key=/var/lib/lxd/server.key
INFO[09-28|12:37:43] LXD isn't socket activated 
INFO[09-28|12:37:43] REST API daemon: 
INFO[09-28|12:37:43]  - binding socket                        socket=/var/lib/lxd/unix.socket
```
##### Setup environment for LXD client
```
export GOPATH=$HOME/p/go
export PATH=$PATH:$GOPATH/bin
lxc version
```
##### Initialize new container named `u1` from `ubuntu` image
```
lxc init ubuntu u1
```

**Comment by stgraber** [comment]
With that issue out of the way, is there anything else you need to be able to package LXD on Fedora?

Wondering whether this issue can be closed.

**Comment by techtonik** [comment]
Well, the check is to be able to run Fedora container on Fedora using advice from https://github.com/lxc/lxd/issues/1156#issuecomment-144098657 I just need a few days to get to that machine.

Then a `.spec` file needs to be written (which is a new area for me), and then upload and test .rpm.

**Comment by kianmeng** [comment]
Is there any updates on this? If not, how can I help?

**Comment by techtonik** [comment]
No progress from my side. I stuck with network configuration for remote access to deployed application.

**Comment by q2dg** [comment]
Can use of systemd-nspawn /systemd-networkd help?

**Comment by techtonik** [comment]
I switched to using Ubuntu for my nodes, so don't expect me to get back to it.

**Comment by stgraber** [comment]
Based on above, closing this now.

As far as I'm aware, there is nothing LXD upstream can do to help with Fedora packaging. All issues directly reported by @techtonik have been addressed one way or another.

Also, specific bug reports should always be preferred over such generic report.

**Comment by brauner** [comment]
Note that as of a few days ago `snapd` is available natively on `Ubuntu`. If you do a:

```
dnf install snapd
snap install lxd
```

You should be able to use `LXD` without having to compile from source.
