### ISSUE TITLE
proxy ssh:  how?

### ISSUE THREAD

**Issue by tarkhil** [lxc/lxd#11550]
# Required information

 * Distribution: Alt linux
 * Distribution version: ALT Virtualization Server 10 (Actinoform)
 * The output of "lxc info" or if that fails:
 * 
https://pastebin.com/DZQ6gAdy

# Issue description

I'm trying to make lxc container available from outside world. 

# Steps to reproduce

## Attempt 1

`lxc config device add gitlab ssh proxy listen=tcp:0.0.0.0:2222 connect=tcp:127.0.0.1:22 proxy_protocol=true`

Than, attempt to connect to port 2222 results in

```
Escape character is '^]'.
SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
Invalid SSH identification string.
Connection closed by foreign host.
```

## Attempt 2

```
# lxc config device add gitlab ssh proxy_nat listen=tcp:0.0.0.0:2222 connect=tcp:127.0.0.1:22 proxy_protocol=true
Error: Invalid devices: Device validation failed for "ssh": Failed loading device "ssh": Unsupported device type
```

**Comment by stgraber** [comment]
Support questions should go to https://discuss.linuxcontainers.org

The problem here is your use of proxy_protocol=true, I suspect openssh doesn't understand that particular proxy header, causing the issue.

**Comment by tarkhil** [comment]
Yes, I've got it; however, I could not see any reasonable reference documentation.
