### ISSUE TITLE
Duplicated metrics

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#11560]
With LXD 5.12, I see duplicated metrics:

```
$ lxc query local:/1.0/metrics | grep -wF lxd_procs_total | sort | uniq -cd
      2 lxd_procs_total{name="juju-lxd",project="default",type="virtual-machine"} 204
      2 lxd_procs_total{name="u1",project="default",type="container"} 13
```
Above, `lxd_procs_total` was filtered for brievty but all metrics seems to be affected. It shows that both VMs and containers are affected. I check and could **not** reproduce with LXD 5.0.2.

Version info:

```
$ snap list lxd
Name  Version       Rev    Tracking       Publisher   Notes
lxd   5.12-c63881f  24643  latest/stable  canonical✓  -
```

**Comment by stgraber** [comment]
Likely just an issue with `lxc query`. We're not getting this behavior using curl.

**Comment by stgraber** [comment]
Ah, no, the first query is fine, the second one within the same cache window has the issue.
