### ISSUE TITLE
LXD container not auto start dhcp to get IP

### ISSUE THREAD

**Issue by laikee99** [lxc/lxd#11576]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.10.0-15-cloud-amd64
   * LXC version: 5.0.2
   * LXD version: 5.12
   * Storage backend in use: dir

# Issue description
I can get dhcp IP when I use Centos as a host, but when I use debian, I have to attach to the container to run `dhcpclient -v eth0` to the network works.
I have seen the issue #10470 about this problem said about UFW. I would like to know how to solve it and why this happend. Thanks.
# Steps to reproduce

 1. lxc launch centos a
 2. lxc info a
 3. lxc exec a bash
 5. dhcpclient -v eth0

**Comment by stgraber** [comment]
Sorry, this is too light in details.

 - What distribution (name and version) is used on the host?
 - What distribution (name and version) is used in the container?

**Comment by laikee99** [comment]
> Sorry, this is too light in details.
> 
> * What distribution (name and version) is used on the host?
> * What distribution (name and version) is used in the container?

Thanks for your reply,
The host is running `Debian GNU/Linux 11`
The container can auto get dhcp ip is Ubuntu 20.04 and the other is Centos 7

**Comment by stgraber** [comment]
How did you create that CentOS 7 container?

Reproducing your setup here, I'm getting a pretty clear:
```
root@v1:~# lxc launch images:centos/7 c2
Creating c2
Starting c2                                 
Error: The image used by this instance requires a CGroupV1 host system
Try `lxc info --show-log local:c2` for more info
```

Which highlights the potential problem with running CentOS 7 on a Debian 11 system.

**Comment by stgraber** [comment]
```
root@v1:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
root@v1:~# lxc version
Client version: 5.12
Server version: 5.12
root@v1:~# lxc launch images:ubuntu/20.04 c1
Creating c1
Starting c1                               
root@v1:~# lxc launch images:centos/7 c2
Creating c2
Starting c2                               
root@v1:~# lxc list
+------+---------+---------------------+-----------------------------------------------+-----------+-----------+
| NAME |  STATE  |        IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS |
+------+---------+---------------------+-----------------------------------------------+-----------+-----------+
| c1   | RUNNING | 10.53.67.222 (eth0) | fd42:4d68:166d:8f75:216:3eff:fed0:6291 (eth0) | CONTAINER | 0         |
+------+---------+---------------------+-----------------------------------------------+-----------+-----------+
| c2   | RUNNING | 10.53.67.198 (eth0) | fd42:4d68:166d:8f75:216:3eff:fe26:ee86 (eth0) | CONTAINER | 0         |
+------+---------+---------------------+-----------------------------------------------+-----------+-----------+
root@v1:~# 
```

**Comment by stgraber** [comment]
Seems to work perfectly fine once you force the system to run with cgroup1 instead of cgroup2 as the error during launch time implies.
