### ISSUE TITLE
Unify syntax for "device add" throughout conainers/vm

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#11618]
Discussion:
[adding-block-device-to-vm](https://discuss.linuxcontainers.org/t/adding-block-device-to-vm-with-different-device-name/16708)
There are two ways:
Point of view storage:
`lxc storage volume attach ...`
Point of view instance:
`lxc config device add ...`
It causes confusions, Point of view instance seems to be better or easier, I suggest weighing this as preferred in docs. 

Syntax for VM and Container is different, each has it's own style and limitations.
Restrictions:

1. Type **Block** can not be attached to container
though it was previously possible by device unix-block, using any host’s block device, zvol … through its path /home/dev.img or /dev/zd1 …

2. Type **file system** can be attached to containers as well as vm
Limitations VM:
 2.a path must be defined. This can be eliminated by using device name as path in VM, when applicable and path is not explicitly passed as variable.
2.b. Cannot attach directory while instance is running. Yet at least instance should not hard reject but accept the new config and apply it after a restart.

**Comment by tomponline** [comment]
> Yet at least instance should not hard reject but accept the new config and apply it after a restart.

I'm not sure about this bit.

**Comment by stgraber** [comment]
Yeah, no, I definitely don't agree about things applying after a restart, this gets pretty confusing unless you track both an effective and next config like libvirt does for example, which in my experience confuses the heck out of users.

That said, you can effectively achieve this through profiles as profiles are lenient in that regard, not requiring the change to successfully apply to all downstream to get committed to the database.

**Comment by stgraber** [comment]
As for the rest of this, I'm inclined to agree that always using `lxc config device add` is better. It's a bit of a longer syntax but the consistency of it makes it easier overall.

I've personally never been fond of the `attach` and `attach-profile` type commands. They were requested by some users quite a while back and have been added pretty consistently, but I personally tend to prefer doing everything from the instance or the profile's point of view.

@ru-fu what do you think about that?

**Comment by kamzar1** [comment]
Thing with profile is, it is not always 1:1 profile:container. One profile can be shared among many, so passing config to profile is not always doable.

> unless you track both an effective and next config like libvirt does for example

A config or task scheduling would solve some issues related to power status of a VM. Next config/Next reboot ...

As for attaching block device to a container, can it be re-introduced?
It was available pre-snap era.

**Comment by ru-fu** [comment]
> As for the rest of this, I'm inclined to agree that always using `lxc config device add` is better. It's a bit of a longer syntax but the consistency of it makes it easier overall.
> 
> I've personally never been fond of the `attach` and `attach-profile` type commands. They were requested by some users quite a while back and have been added pretty consistently, but I personally tend to prefer doing everything from the instance or the profile's point of view.
> 
> @ru-fu what do you think about that?

I agree that it is confusing to have different ways of doing the same thing.
But if you're a newbie user, it is a lot easier to find a `lxc network attach` or `lxc storage volume attach` command to use the thing you just created than to understand and figure out what devices are so you can use `lxc config device add`.

**Comment by stgraber** [comment]
> As for attaching block device to a container, can it be re-introduced?

`lxc config device add FOO BAR unix-block` has never stopped working and we actively rely on it in our image builds.

**Comment by stgraber** [comment]
> I agree that it is confusing to have different ways of doing the same thing.
> But if you're a newbie user, it is a lot easier to find a `lxc network attach` or `lxc storage volume attach` command to use the thing you just created (with a similar command) than to understand and figure out what devices are so you can use `lxc config device add`.

Should we add a note block or something that points to `lxc config device add` for more complex configs?
The problem with the `attach` other than the argument order being different as it operates from the point of view of the storage or network rather than from the instance/profile point of view, is that it also doesn't support any of the device config options, so if you want to set any config key, you need to then do a `lxc config device set`.

**Comment by ru-fu** [comment]
> Should we add a note block or something that points to `lxc config device add` for more complex configs?

We already have that for networks (https://linuxcontainers.org/lxd/docs/latest/howto/network_create/#attach-a-network-to-an-instance).
I can add it for storage volumes. Are there any other `attach` commands I'm not aware of?

**Comment by stgraber** [comment]
@ru-fu nope, I think we just have storage and networks, thanks!
