### ISSUE TITLE
Cleanup unused images

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#11617]
Reference discussions:
[ghost-zfs-images-dataset-clean-up](https://discuss.linuxcontainers.org/t/ghost-zfs-images-dataset-clean-up/13454)
[local-image-cache-cleanup](https://discuss.linuxcontainers.org/t/local-image-cache-cleanup/16864)

When deleting an instance, it's base image persists, even if it is not used by any other instance.
Especially VM base images can be of large size and by time ghost images occupy a lot of space on storage pools.

As there is no easy way to determine an unused image [lxc image list missing field "used_by"](https://github.com/lxc/lxd/issues/11616), even a manual clean-up is a challenge.

**Comment by tomponline** [comment]
See `images.remote_cache_expiry` in https://linuxcontainers.org/lxd/docs/master/server/#images-configuration

**Comment by tomponline** [comment]
If you feel this does not address the issue please advise and we can discuss further, but please show reproducer steps to the problem.

**Comment by kamzar1** [comment]
Thanks for the hint.
I never really understood, how to let it purge immediately.
I have
_images.remote_cache_expiry 0_
I guess, this will cause them to stick around forever.
Do I need a -1 for immediate purge? Or just live with the minimum 1 day when choosing 1?

Also some images are not from remote source but created through lxc image copy, lxc image import tarball
Will _images.remote_cache_expiry 0_ apply to them too?

**Comment by tomponline** [comment]
Non cached images have to be removed manually, they are not related to instance creation (unlike cached remote images).

I do not believe we have instant clearance of cached remote images and minimum is 1 day.
