### ISSUE TITLE
`GetTotalProcesses()` looks at the wrong cgroup file `pids.current` rather then `pids.max`

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#11639]
https://github.com/lxc/lxd/blob/master/lxd/cgroup/abstraction.go#L1083-L1107 shows that for both cgroupv1 and v2, `pids.current` is used. That essentially duplicate what's done by `GetProcessesUsage()` except that the former is missing the `fallthrough` for `V1`.

With cgroupv2, the right file seems to be `pids.max` which contains `max` when no limit is set or the integer corresponding to `limits.processes` otherwise. If that's the same behaviour in cgroupv1, a fallthrough clause should be added, if not, the right file should be read.

**Comment by tomponline** [comment]
Good spotting. Lets remove `GetTotalProcesses` and then use `GetProcessesUsage` instead.

**Comment by tomponline** [comment]
As discussed as everywhere these functions are used expect the current process count inside an instance, lets just remove the duplicate implementation and close this without adding the handling of maximum pids as this isn't being used currently.
