### ISSUE TITLE
lxc sorts by first column and not by "name"

### ISSUE THREAD

**Issue by markylaing** [lxc/lxd#11645]
Under `lxc/utils` we have a number implementations of `sort.Interface` that are used to sort lists. One of these implementations is named `ByName`, but it doesn't sort by name, it sorts the given data by the first column. Therefore, if a user specifies columns and the first column is not "n", then the data is being sorted by whatever is in the first column, and not by name.

We should at least rename these implementations to reflect how they actually perform sorting (e.g. `SortByFirstColumn`). We can also implement a proper "ByName" sorter if this is of interest, if so we will need to tell this sorter which column is the name column.

**Comment by Regis-Caelum** [comment]
@tomponline I would like to work on this one. please tell me what needs to be done

**Comment by markylaing** [comment]
> It doesn't only sort by the first column, so changing it to `SortByFirstColumn` would be misleading in my view.
> 
> It sorts naturally using all of the columns being displayed, starting with the 1st from the left, and then the 2nd etc.
> 
> So perhaps we should just rename this implementation to `SortNatural`.

Ah yes I realised afterwards but forgot to update the issue. I'm happy with renaming to `SortNatural` though given that we only use this for displaying tables perhaps `SortLeftToRight` will more clearly indicate it's purpose.

**Comment by tomponline** [comment]
Hrm, not a fan of that as it doesn't say how its sorted, how about:

```
SortColumnsNaturally()
```

**Comment by tomponline** [comment]
@Regis-Caelum are you ok if @MusicDin takes this one?

**Comment by Regis-Caelum** [comment]
Apologies, for late response
Yeah sure
