### ISSUE TITLE
Implement disk resource limits

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1164]
It would be nice if more cgroup limits could be configured with LXD instead of using raw.lxc. Currently only cpu number (not even affinity) and hard memory limit can be set.

I might be nice to allow any arbitrary name under limits.* to map directly to lxc.cgroup.*
Or maybe create a new cgroup.* config key.

From lxc.container.conf(5):
lxc does not check the correctness of the subsystem name.This has the disadvantage of not detecting configuration errors until the container is started, but has the advantage of permitting any future subsystem.

Examples of useful limits in a shared environment:

* limits.swap:
To prevent a container from using up all of the hosts' swap memory it would be nice to add a limits.swap option. This would set the lxc.cgroup.memory.memsw.limit_in_bytes value.

** This option is somewhat mandatory if you wish to oversubscribe the hosts' physical memory.

** Please note that lxcfs does not provide an overlay for /proc/swaps for this yet, so the effect will not be visible inside the container.

* limits.memory_soft:
Similar to above case to set lxc.cgroup.memory.soft_limit_in_bytes

* limits.cpu_shares:
Allow setting the lxc.cgroup.cpu.shares value to 'schedule' cpu cycles.

* limits.blkio_weight:
Allow setting the lxc.cgroup.blkio.weight value to 'schedule' disk io.

**Comment by stgraber** [comment]
It's planned but we're waiting on internal review of our plan for limits.

**Comment by stgraber** [comment]
As I said, this is waiting on internal review, so marking as blocked, hopefully we'll make progress on this within the next month or so.

**Comment by stgraber** [comment]
We actually sorted out approval of the resource limit specs, just need to file separate issues to track the different bits. Hoping to have it all implemented over the next couple of months.

**Comment by jsimonetti** [comment]
Can this spec be made public yet? I am certainly not a pro at go, but if there are some parts where i can contribute, I would be happy to.

**Comment by stgraber** [comment]
It's a private google doc right now, I intend to convert chunks of it into github issues so folks can join in :)

I'm currently working on the CPU side of it, dealing with cpu hotplug on the host and re-scheduling all containers.

**Comment by jsimonetti** [comment]
Looks like only blckio weight is left. Awesome work getting lxd ready for shared environments!

**Comment by stgraber** [comment]
We actually have a bunch more things for storage and network I/O coming next.

For storage:
 - limits.block.priority (global container I/O priority)
 - device.limits.size (GB)
 - device.limits.read (MB/s or iops)
 - device.limits.write (MB/s or iops)
 - device.limits.max (alias for read + write)

For network:
 - limits.network.priority (global container I/O priority)
 - device.limits.ingress (limit in Mbps)
 - device.limits.egress (limit in Mbps)
 - device.limits.max (alias for ingress + egress)

After that, we'll probably want to offer an interface to the pid cgroup too (kernel 4.3 and higher).

**Comment by jsimonetti** [comment]
Purely out of curiosity, can you link some info on pid cgroups? I tried google, but it is a bit convoluted with generic cgroup management.
What can be done with the pid cgroup?

**Comment by jsimonetti** [comment]
Nevermind, I found it at https://www.kernel.org/doc/Documentation/cgroups/pids.txt :)

**Comment by stgraber** [comment]
Re-purposing this one for just disk storage limits, the rest is covered in separate issues targeted for the next milestone.
