### ISSUE TITLE
Have `--reuse` in `lxc publish` only perform alias and image deletion after image creation

### ISSUE THREAD

**Issue by diabolusss** [lxc/lxd#11657]
Issue description
-----------

Right now, the feature works as stated - on issuing ```lxc publish``` it deletes the current image with matched alias name and re-creates a new one.
But sometimes that process may fail for some reason (and it may happen multiple times in a year).

Is it possible to back a --reuse with an additional flag, to make it reuse that name only after successful creation of a new image?
I mean, if lxd will fail to create new image, for example, because of missing free space or some other bug will arise, then i suppose old published image will be gone already?

In a sense, when there is no enough space to keep both images at the same time, current behavior should be kept, too. But i believe that there should be a way to choose between current "--reuse" and failsafe "--reuse", that will delete old image only after successful publish.
And, maybe, to be on the safe side, it should be "failsafe" by default.

Example
-----------

_NB error of ```lxc publish``` in the example is not related to this feature request._

```
10:38:01 [@LIVE ~]$ lxc image list
+-------------------+--------------+--------+------------------------------------+--------------+-----------+-----------+------------------------------+
|       ALIAS       | FINGERPRINT  | PUBLIC |            DESCRIPTION             | ARCHITECTURE |   TYPE    |   SIZE    |         UPLOAD DATE          |
+-------------------+--------------+--------+------------------------------------+--------------+-----------+-----------+------------------------------+

| xpraserver-export | 906b06ba649c | no     | Archlinux  x86_64 (20201120_04:33) | x86_64       | CONTAINER | 2529.13MB | Mar 10, 2023 at 9:48am (UTC) |
```

```
11:14:12 [@LIVE ~]$ lxc publish messangers2207/230110 --alias xpraserver-export --reuse
Error: Failed to activate LVM logical volume "/dev/lvmTPoolVG01/containers_messangers2207-230110": Failed to run: lvchange --activate y --ignoreactivationskip /dev/lvmTPoolVG01/containers_messangers2207-230110: exit status 5 (Check of pool lvmTPoolVG01/devbox failed (status:64). Manual repair required!)
```

After issuing ```lxc publish```, but before seeing the error message - the published image is already gone.

-------------

```
$ lxd --version
5.13
```

**Comment by stgraber** [comment]
I think the current logic should be changed so existing image cleanup is performed right before the `ensureImageAliases` step and so after the image has been created.

**Comment by presztak** [comment]
@stgraber I can improve this if you don't mind.

PS. For snapshots and storage volumes also in first place we delete snapshot/storage volume and then create a new one. Should we also improve snapshots/storage volumes?

**Comment by diabolusss** [comment]
> I think the current logic should be changed so existing image cleanup is performed right before the `ensureImageAliases` step and so after the image has been created.

While this does not conflict with my suggestion, I just want to emphasize that having both options is desirable.

> In a sense, when there is no enough space to keep both images at the same time, current behavior should be kept, too. But i believe that there should be a way to choose between current "--reuse" and failsafe "--reuse", that will delete old image only after successful publish.

**Comment by stgraber** [comment]
Well, with the change described above, it would effectively be the failsafe by default, no point in offering a potential risky option with no real benefit.

The logic should basically be:
 - Publish the instance as a new image
 - Delete the image alias if already used
 - Add the new image alias
 - Delete the old image

So should any of the step fail, you're not left with a broken state.

**Comment by diabolusss** [comment]
Of course, i don't argue that it should be failsafe by default. I'm just saying that there should be a way to immediately remove the old alias image, too.

My scenario is simple:
I have a container on cloud, and there i have a limited space. 
I've configured lxd-snapper to make daily snapshots and using hooks it's calling ```lxc publish ... --alias xxx --reuse```. 
For X days i do ```lxc export ...```, because i can't rely on lxc storage pool as it has failed before.
Published container image is around 18GB in size, so for failsafe publish i'll need additional 18GB of free space, which i couldn't add there so easily.  With this fix, i suppose it will fail.
Taking into account that container has enough snapshots and i have exported images, i can take a risk to lose a published image by calling, for example ```lxc publish --alias ... --purge-and-reuse```.

Taking into account this scenario, the **benefit** is the **ease of use** of lxd (_there will be no need to manually delete image before publishing_) and **backward compatibility** with current release _(i'll need to change a flag only)_. 
Anyway, **thank you**, for considering this option.

**Comment by stgraber** [comment]
I think that if you're so low on space to not be able to hold two copies of the data, you're going to have other problems.

Deleting the image from the current project as would happen here is actually no guarantee that the image will be gone from disk at the same time. LXD will only delete the image when no project references it.

Instead what you may want to look at is the images.storage_volume config option which allows you to store the images as part of your storage pool rather than on the host's filesystem.

**Comment by diabolusss** [comment]
> Deleting the image from the current project as would happen here is actually no guarantee that the image will be gone from disk at the same time. LXD will only delete the image when no project references it.

Good to know, thank you. But the only reason i'm publishing it is to get an exported image file, so i'm safe here. _(I didn't find a way to do it directly.)_


> Instead what you may want to look at is the images.storage_volume config option which allows you to store the images as part of your storage pool rather than on the host's filesystem.

Thanks for a tip, but in my scenario, I don't think that this will solve the free space issue, because that way it will consume the space meant for the container. 
However, if there is a way to specify some intermediate point to temporary store the old image, then this may help a lot.

**Comment by stgraber** [comment]
You could create another storage pool that's only used to store things like images and backups and use `storage.images_volume` and `storage.backups_volume` for that.

**Comment by diabolusss** [comment]
> My scenario is simple:
> I have a container in the cloud, and i have a limited space there.

Anyway, thank you for suggestions. When possible, I'll do that for sure.

And could you, please, provide a link to a description or give more details about ```storage.backups_volume```?
I've found a link https://discuss.linuxcontainers.org/t/configuring-backups-directory/7113/2 and brief description in docs, but i didn't understand how and where it's used _(there are commands to create images, are there any for backups, too?)_.

> storage.backups_volume string local Volume to use to store the backup tarballs (syntax is POOL/VOLUME)
> storage.images_volume string local Volume to use to store the image tarballs (syntax is POOL/VOLUME)

**Comment by diabolusss** [comment]
Hello!
@tomponline @stgraber @presztak 
I apologize for bothering you, but could you please clarify whether this change is applied only to LXD 5.15, or if it has been merged with earlier versions as well?
In other words, which version from the snap can I install to avoid the new behavior?
I believe that 5.14 should be okay, but I'm confused by the update timestamp - it matches the timestamp of the #11760 merge event.
```
  5.14/stable:      –                                      
  5.14/candidate:   5.14-7072c7b  2023-05-31 (24918) 178MB -
  5.14/beta:        ↑                                      
  5.14/edge:        ↑                                      
  5.13/stable:      5.13-8e2d7eb  2023-05-31 (24846) 174MB -
  5.13/candidate:   ↑                                      
  5.13/beta:        ↑                                      
  5.13/edge:        ↑ 
```
