### ISSUE TITLE
lxd-ui.pfx does not work on a Mac because of empty password.

### ISSUE THREAD

**Issue by jaminmc** [lxc/lxd#11655]
When using any browser on a Mac, it uses the OS for certificates. Macos, at least Ventura doesn't allow blank passwords for PFX files. The easy fix would be for the generator on LXD US to prompt for a password when generating the certs, that way the user can type that in when they add it to the MacOS keychain. 

I did figure out a workaround... 
If I run this in the trerminal on my Mac, it will ass a password to a new file:
`openssl pkcs12 -in lxd-ui.pfx -password pass:"" -passin pass:"" -passout pass:"InsertPasswordHere" -out "lxd-ui-mac.pfx"`

Then all I had to do is double click on the lxd-ui-mac.pfx file, and enter the password I put in above. Now I have access!

**Comment by stgraber** [comment]
You most likely wanted to file this against the UI repo: https://github.com/canonical/lxd-ui
