### ISSUE TITLE
Operation url from rest api inconsistency

### ISSUE THREAD

**Issue by edlerd** [lxc/lxd#11664]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 5.13

# Issue description

When launching an instance on a single LXD host via the rest API, it returns an operation like this: `/1.0/operations/db23af24-3e7a-42cc-9dda-2675769fc46f`. When the LXD server is clustered, the operation changes to `/1.0/operations/db23af24-3e7a-42cc-9dda-2675769fc46f?project=default`.

So the clustered response adds a `?project=default`, while the single host setup omits it. Both cases should probably return the same URL structure.

# Steps to reproduce

 1. Create an instance via rest API with a POST to `1.0/instances` on a single LXD host
 2. Create an instance via rest API with a POST to `1.0/instances` on a clustered LXD host
 3. Compare the operation field in the returned JSON. 1. is without 2. is with the project in the URL.

**Comment by roosterfish** [comment]
@tomponline please assign it to me.

**Comment by roosterfish** [comment]
Hi @edlerd,

I am trying to reproduce the issue but cannot see the behavior you are describing. I have tried with both 5.13 and the latest 5.14 (for each in clustered and standalone mode).

When using `lxc query` I am getting the following responses from the API:

### standalone

```bash
lxc query -X POST --raw /1.0/instances -d '
{
	"architecture": "",
	"config": {},
	"devices": {},
	"ephemeral": false,
	"profiles": null,
	"stateful": false,
	"description": "",
	"name": "test",
	"source": {
		"type": "image",
		"certificate": "",
		"alias": "ubuntu/22.04",
		"server": "https://images.linuxcontainers.org",
		"protocol": "simplestreams",
		"mode": "pull",
		"allow_inconsistent": false
	},
	"instance_type": "",
	"type": "container"
}'
```
returns

```json
{
    "type": "async",
    "status": "Operation created",
    "status_code": 100,
    "operation": "/1.0/operations/21a06d12-9ab7-46e6-9f7c-50cff8c5633b",
    "error_code": 0,
    "error": "",
    "metadata": {
	    "id": "21a06d12-9ab7-46e6-9f7c-50cff8c5633b",
	    "class": "task",
	    "description": "Creating instance",
	    "created_at": "2023-06-02T10:00:39.462886317Z",
	    "updated_at": "2023-06-02T10:00:39.462886317Z",
	    "status": "Running",
	    "status_code": 103,
	    "resources": {
		    "containers": [
			    "/1.0/containers/test"
		    ],
		    "instances": [
			    "/1.0/instances/test"
		    ]
	    },
	    "metadata": null,
	    "may_cancel": false,
	    "err": "",
	    "location": "none"
    }
}
```

The `operation` field shows the URL without the project query param.

### clustered

Using the same command from above, the server returns this:

```json
{
    "type": "async",
    "status": "Operation created",
    "status_code": 100,
    "operation": "/1.0/operations/3e9d6b88-9ee2-4d77-bc86-d84b280ea4b3",
    "error_code": 0,
    "error": "",
    "metadata": {
	    "id": "3e9d6b88-9ee2-4d77-bc86-d84b280ea4b3",
	    "class": "task",
	    "description": "Creating instance",
	    "created_at": "2023-06-02T10:13:55.866304271Z",
	    "updated_at": "2023-06-02T10:13:55.866304271Z",
	    "status": "Running",
	    "status_code": 103,
	    "resources": {
		    "containers": [
			    "/1.0/containers/test"
		    ],
		    "instances": [
			    "/1.0/instances/test"
		    ]
	    },
	    "metadata": null,
	    "may_cancel": false,
	    "err": "",
	    "location": "c1-153"
    }
}
```

In both modes the `default` project is selected as current:

```bash
root@c1-153:~# lxc project list
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
|       NAME        | IMAGES | PROFILES | STORAGE VOLUMES | STORAGE BUCKETS | NETWORKS | NETWORK ZONES |     DESCRIPTION     | USED BY |
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
| default (current) | YES    | YES      | YES             | YES             | YES      | YES           | Default LXD project | 3       |
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
```

**Comment by edlerd** [comment]
> Hi @edlerd,
> 
> I am trying to reproduce the issue but cannot see the behavior you are describing. I have tried with both 5.13 and the latest 5.14 (for each in clustered and standalone mode).

My cluster is running LXD 5.0.2 and adding the `project` query parameter to the operation url. My unclustered backend was recent version 5.14. On 5.14 the operation url without project works in any case - also if the operation is not on the default project.

So probably everything works as expected and nothing needs to be changed. Sorry for the confusion caused.

**Comment by tomponline** [comment]
Thanks.

@roosterfish while you have this setup, can you check it does the right thing for an instance in a non-default project?

**Comment by roosterfish** [comment]
@tomponline Running `lxc query -X POST --raw /1.0/instances?project=test -d '...'` also doesn't append the query param to the URL of the `operation` field. In both standalone and cluster mode.

**Comment by tomponline** [comment]
OK I think thats fine as the `operationGet` function doesn't take into account project as the `uuid` column on the `operations` table has a unique index on it, making the ID globally unique.
