### ISSUE TITLE
swtpm isn't properly cleaned up on QEMU crashes

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#11670]
If QEMU crashes or is otherwise terminated, swtpm keeps running, preventing the VM from starting back up again.

**Comment by tomponline** [comment]
Sounds like the fix proposed in https://github.com/lxc/lxd/issues/11546 (of detecting a crashed qemu process and triggering device cleanup) would also fix this issue.

**Comment by stgraber** [comment]
Yep
