### ISSUE TITLE
LXD_SECURITY_APPARMOR=false broken

### ISSUE THREAD

**Issue by antifob** [lxc/lxd#11675]
# Required information

 * Distribution: Debian
 * Distribution version: bullseye
 * The output of "lxc info" or if that fails:
   * Kernel version: `uname -rv` `5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022`
   * LXC version: `lxc --version` `5.13` built from master 3 weeks ago
   * LXD version: `lxd --version` `5.13` built from master 3 weeks ago 
   * Storage backend in use: `dir`

# Issue description

I'm attempting to run lxd in the following configuration:
- host: Ubuntu, using snapd
  - ctn: Ubuntu, using snapd
    - ctn: ??

Containers run with nesting enabled and the containers unprivileged.

AppArmor prevents running various pieces of lxd and the `LXD_SECURITY_APPARMOR` envvar is not working as expected.

# Steps to reproduce

Running `snapd` in the inner container fails due to AppArmor so I attempted my build at https://github.com/antifob/lxd-ci/
AppArmor then caused a failure to run `dnsmasq`:

```
root@ctn:~# lxc network create lxdbr0
Error: The DNS and DHCP service exited prematurely: Process exited with non-zero value 1 ("aa-exec: ERROR: profile 'lxd_dnsmasq-lxdbr0_</var/lib/lxd>' does not exist")
```

So I set `LXD_SECURITY_APPARMOR=false` according to https://linuxcontainers.org/lxd/docs/latest/environment/
Same error regarding `dnsmasq` so I hacked around it by setting `raw.dnsmasq`.

```
root@ctn:~# lxc network create lxdbr0 raw.dnsmasq='#'
Network lxdbr0 created
```

Then, I cannot launch a container because `tar` runs with an AppArmor profile:
```
root@ctn:~# lxc launch images:alpine/edge z
Creating z
Error: Failed instance creation: Failed creating instance from image: Unpack failed: Failed to run: tar --wildcards --exclude=dev/* --exclude=./dev/* --exclude=rootfs/dev/* --exclude=rootfs/./dev/* --restrict --force-local -C /var/lib/lxd/storage-pools/default/containers/z --numeric-owner --xattrs-include=* -Jxf -: Process exited with non-zero value 1 (aa-exec: ERROR: profile 'lxd_archive-var-lib-lxd-storage-pools-default-containers-z' does not exist)
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
How did you set the environment variable exactly?

**Comment by antifob** [comment]
I didn't use the snap version, but a source-built version.
https://github.com/antifob/lxd-ci/blob/main/etc/lxd.service#L14

I confirmed it was picked up by `cat`-ing `/proc/$lxdpid/environ`.

**Comment by stgraber** [comment]
When looking at the LXD startup log, do you see `AppArmor support has been manually disabled` getting logged?

**Comment by antifob** [comment]
Yes :)
