### ISSUE TITLE
Persistent IP for Containers

### ISSUE THREAD

**Issue by gulfpearl** [lxc/lxd#1168]
There is no documentation on how to set a persistent IP for containers, are you supposed to edit the dnsmasq config or is there a setting/command using lxc.

**Comment by stgraber** [comment]
That's because LXD doesn't deal with IPs at all.

You can either just configure the container with a static IP address from inside the container, or indeed configure the DHCP server (dnsmasq or other) which is providing the DHCP service to whatever bridge your container is attached to.

**Comment by gulfpearl** [comment]
OK thanks, that's how I have already done it (dnsmasq). Since people are coming from LXC it would be good to have a cookbook type section that demonstrates on common ways to map things over.
