### ISSUE TITLE
API instance link inconsistency from snapshots operations

### ISSUE THREAD

**Issue by edlerd** [lxc/lxd#11713]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04.2
   * LXC version: 5.13
   * LXD version: 5.13

# Issue description

The response of `GET 1.0/operations` for snapshot delete and update operations contains the wrong url under the `metadata.success[0].resources.instances[0]` field. See screenshots below, the relevant field is the last line. I'd expect the url to always be like in the snapshot restore case.

- snapshot update operation links to the snapshot name instead of the instance name:
![Screenshot from 2023-05-22 21-47-27](https://github.com/lxc/lxd/assets/1155472/9d8a4226-1ddc-4fc5-803d-9f0ee983016a)

- snapshot delete operation links to instance/snapshot
![Screenshot from 2023-05-22 21-54-41](https://github.com/lxc/lxd/assets/1155472/789ab399-a3aa-445f-aa6c-91032d6ab98a)

- snapshot restore is as expected:
![Screenshot from 2023-05-22 21-49-11](https://github.com/lxc/lxd/assets/1155472/62db8b2a-8a99-4185-9836-541ddad78c0c)

# Steps to reproduce

 1. Update or delete a snapshot
 2. Query the `1.0/operations` `GET` endpoint
 3. Check the `metadata.success[0].resources.instances[0]` field in the response

**Comment by edlerd** [comment]
> Do you think it should always refer to the parent instance and not to the snapshot?

For my current use case, most convenient is the parent instance. I agree, technically more correct is to link to `1.0/instances/{name}/snapshots/{snapshot}` in all three cases.

**Comment by roosterfish** [comment]
Hi, please assign it to me @tomponline
