### ISSUE TITLE
failed lxd recover does not roll back completely

### ISSUE THREAD

**Issue by aivanise** [lxc/lxd#11728]
as discussed at https://discuss.linuxcontainers.org/t/phantom-db-entries-after-somewhat-botched-lxd-recover/17232

failed lxd recover does not roll back completely, it leaves stray entries in storage_volumes

see above forum entry for a reproducer

**Comment by tomponline** [comment]
Confirmed that `pool.ImportInstance` and `pool.ImportCustomVolume` need to return `cleanup` functions that can be used by the reverter.

**Comment by tomponline** [comment]
Got a fix for this now.
