### ISSUE TITLE
When deleting a VM with forward associated with its address - the forwards stays in place

### ISSUE THREAD

**Issue by grebennikov** [lxc/lxd#11743]
For OVN usecase, for getting external access to the VM it is required to create a forward to the internal address of the VM.
It is expected that when the VM gets deleted - the forward should be deleted as well.
Otherwise it will be impossible to track utilization of the addresses consumed by the forwards as users won't have a mechanism to automatically purge resources associated with VMs.

**Comment by stgraber** [comment]
LXD's forwards aren't 1:1 like they are in OpenStack and some public clouds but they can be 1:many, making it incorrect for us to automatically delete. Floating addresses in the cloud remaining after the instance is deleted is also a pretty common pattern as a way to keep an address reservation.
