### ISSUE TITLE
Setting limits.cpu config for running VM doesn't update the core count

### ISSUE THREAD

**Issue by grebennikov** [lxc/lxd#11745]
There is the expectation from the customer that the CPU count can be updated in live mode (it's been explicitly stated that the RAM amount can't be changed).

The instance is running with a single vcore:
$ lxc exec task1-from-snap -- cat /proc/cpuinfo|grep ^proce
processor       : 0

Updating the limits:
$ lxc config set task1-from-snap limits.cpu=4

The core count stays the same:
$ lxc exec task1-from-snap -- cat /proc/cpuinfo|grep ^proce 
processor       : 0

**Comment by simondeziel** [comment]
CPU are hot plugged but not put online:

```
$ lxc exec task1-from-snap -- dmesg | tail -n 3
[    9.012074] CPU1 has been hot-added
[    9.062685] CPU2 has been hot-added
[    9.125224] CPU3 has been hot-added

$ lxc exec task1-from-snap -- nproc
1

$ echo 1 | lxc exec task1-from-snap -- tee /sys/devices/system/cpu/cpu1/online
1

$ lxc exec task1-from-snap -- nproc
2
```

We should update our doc to mention it in https://linuxcontainers.org/lxd/docs/master/reference/instance_options/#instance-options-limits-cpu. @ru-fu is this something you can do or maybe I just missed it?

**Comment by stgraber** [comment]
Should indeed be mentioned but we need to be careful with wording as the behavior completely depends on the OS or even distribution used. I don't know if Windows brings up CPUs automatically when plugged in and it would be easy for a Linux distribution to also have it be done automatically with a simple udev rule.

So we should just say that LXD will hotplug the CPU and that bringing it online may require further action depending on the guest operating system.

**Comment by grebennikov** [comment]
I've just found out the same, that the hypervisor actually making the adjustment. I completely agree this is more a documentation than missing functionality.
