### ISSUE TITLE
When creating a VM with the profile where limits.memory is set - getting error

### ISSUE THREAD

**Issue by grebennikov** [lxc/lxd#11748]
Create a profile setting cpu and memory limits:
lxc profile set test limits.cpu=2
lxc profile set test limits.memory=2GB

Creating a VM
$ lxc launch images:ubuntu/22.04/cloud task2 --storage remote --vm -c migration.stateful=true -d root,size.state=1GiB --profile test
Creating task2
Starting task2
Error: Stateful start requires that the instance limits.memory is less than size.state on the root disk device

$ lxc launch images:ubuntu/22.04/cloud task2 --storage remote --vm -c migration.stateful=true -d root,size=5GiB --profile test
Creating task2
Starting task2
Error: Stateful start requires that the instance limits.memory is less than size.state on the root disk device

**Comment by stgraber** [comment]
Right, you're setting `migration.stateful=true` which per the error requires `size.state` on the root disk to be equal or greater to `limits.memory`.

Change your `-d root,size=5GiB` to `-d root,size=5GiB -d root,size.state=2GB` and it will be happy.
