### ISSUE TITLE
Cannot add OVN-based nic to a running VM

### ISSUE THREAD

**Issue by grebennikov** [lxc/lxd#11746]
When trying to add the nic to a running VM I'm getting the following:

$ lxc config device add task1 eth1 nic nictype=ovn network=newnet
Error: Failed to add device "eth1": Device cannot be added when instance is running

For the stopped VM the same command works correctly and nic is being added.
The secondary nic doesn't get the IP address though, even though the network is "managed" and displays the subnet in the network list.

**Comment by stgraber** [comment]
@tomponline any reason we wouldn't be allowing hotplug of OVN devices?

**Comment by grebennikov** [comment]
I just spoke to the customer and apparently this is absolute must, as this is a very basic feature of VMWare.

**Comment by stgraber** [comment]
We generally do have NIC hotplug so the question is why the particular implementation (OVN in this case) wasn't marked as safe for hotplug.

**Comment by tomponline** [comment]
> @tomponline any reason we wouldn't be allowing hotplug of OVN devices?

No, this was just an oversight.

The common device defaults to allowing hotplug for containers, but not for VMs (as VMs don't support hotplugging all devices).

Then we needed to override that default for each NIC type, as some like `ipvlan` don't hotplugging at all.

But the `ovn` NIC can support hotplugging, so it just needed an override added:

https://github.com/lxc/lxd/pull/11749
