### ISSUE TITLE
Use `fallocate()` to create loop devices pools

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#11754]
LXD uses `ftruncate()` to create the loop devices pools so the backing files are ordinary sparse files. If the underlying FS runs out of space before the loop device has grown to 100%, the pool will lockup/pause all IOs.

Switching to `fallocate()` would have the sparse files pre-allocated so they'd be guarantied to not run out of space. For rotating disks, this should also improve the performance slightly as there should be less fragmentation because the underlying FS would try to reserve contiguous blocks/extents.

One drawback is that not all FS support `fallocate()` so `ftruncate()` should probably be kept as fallback.

**Comment by stgraber** [comment]
The fact that we allow overprovisioning is a deliberate. Especially as we start installing LXD by default on more and more systems, we don't want to have it show as consuming 20-30GB of reserved disk space.

In general, we should try to have LXD handle ENOSPC conditions as well as can be which we've already been improving over the years.

**Comment by tomponline** [comment]
Thanks for confirming, i suspected this may be tge case.

The main drawback to allowing over provisioning is his the underlying storage drivers react when the loop file runs out of backing disk space. Some, like zfs, treat this as an I/o error and put the pool into read only mode.
