### ISSUE TITLE
Add support for fs-specific container transfer mechanism

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#1176]
Both btrfs and ZFS support improved transfer methods (compared to rsync) which we should use when we detect both the source and target host use the same storage backend.

This should be an addition to the internal storage API so that any other storage backend can make use of this transparently. rsync will be used as fallback method.

**Comment by tomposmiko** [comment]
hi @tych0 

Is this going to be implemented in the 1.0 release?

**Comment by stgraber** [comment]
We'll actually be skipping straight to 2.0 but yes, it's planned to be in there.

**Comment by stgraber** [comment]
I guess we're just missing btrfs right now, right?

**Comment by stgraber** [comment]
I've got a rough first pass of this, basically copy/paste from zfs, will try and get it working.
