### ISSUE TITLE
Unable to Publish LXC Container Snapshot to Local or Remote Image Repo

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#11773]
# Required information

 * Distribution: **Ubuntu 18.04.4 LTS**
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: **3.0.3**
   * LXD version: **3.0.3**
   * Storage backend in use: **btrfs**

# Issue description 

When trying to create an image backup for a specific container, i get the following error. 
`lxc publish ss-n1-service/ss-n1-service-01-06-2023 --alias ss-n1-service-01-06-2023`

Output:
> Error: Failed to read xattr for '/var/lib/lxd/snapshots/ss-n1-service/ss-n1-service-01-06-2023/rootfs/var/cache/dnf/AppStream-d7987f026ef99c82/repodata/d8472d61c5e53a3e9cbffb68e0dddbd04a07c2b7d864b07ddd211c6ad1380c6e-primary.xml.gz': argument list too long

# Steps to reproduce

Not sure if this is reproducible. 

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
[ss-n1-service-info.log](https://github.com/lxc/lxd/files/11624219/ss-n1-service-info.log)

**Comment by tomponline** [comment]
Please can you confirm whether this is an issue with LXD 5.14, as LXD 3.0.3 is EOL now (see https://discuss.linuxcontainers.org/t/lxd-3-0-0-has-been-released/1491).
I did a quick check with LXD 5.14 and it seems possible to publish a snapshot fine.

**Comment by elbrinke** [comment]
Hi Tom, 

Thanks for the quick response. I think i figured out the issue. I just had to remove the /var/cache/dnf folder. Then created a new snapshot and were able to publish the snapshot to image. 

Regards
Eddy
