### ISSUE TITLE
Update client package to be more suitable to downstreams

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#1177]
The current client module was basically written for use by the lxc command line tool. Now that we have some downstreams user, we should consider some improvements, reduce its dependencies further and provide an API that's closer to the REST API.

**Comment by jsimonetti** [comment]
Will this also fix having to compile the entirety of LXD when all you want to use just a lxd.NewClient in your code?

**Comment by tych0** [comment]
On Thu, Dec 03, 2015 at 04:29:52AM -0800, Jeroen Simonetti wrote:
> Will this also fix having to compile the entirety of LXD when all you want to use just a lxd.NewClient in your code?

You shouldn't have to compile all of lxd if you import
github.com/lxc/lxd.

This is mostly making the API nicer, e.g. allowing people to pass
their own config directories, etc.

**Comment by stgraber** [comment]
I think we've done as much as we'll realistically do for 2.0, so closing this. I'd really like us to re-evaluate our client after 2.0 and see if we can make a clearer split between the client package and the client binary.
