### ISSUE TITLE
Sometimes lxd does not download the correct image from the customized image mirror

### ISSUE THREAD

**Issue by zhhuabj** [lxc/lxd#11847]
### Required information
$ juju --version
2.9.38-ubuntu-amd64

$ lxd --version
5.0.2

### Issue description
This issue was initially reported in lp bug 2008993[1], juju's config option container-image-metadata-url doesn't work intermittently. Aftering spending some time on this bug, it seems this problem is not on juju's side, but may be on lxd's side.

Sometimes we can successfully reprodcue the problem through these steps (see https://paste.ubuntu.com/p/V7zdZyt6CG/) through an isolated multipath instance, sometimes we cannot (see https://bugs.launchpad.net/juju/+bug/2008993/comments/22). So this problem looks intermittent. We can also refer to this link (https://bugs.launchpad.net/juju/+bug/2008993/comments/33) for more details.

We have determined that LXD is indeed requesting the simplestream mirror (because we are seeing nginx logs) and therefore juju is correctly taking into account the `container-image-metadata-url` config and passing it to LXD. So no bug in juju concerning the container-image-metadata-url config.

Now, when we check the nginx logs, we see these lines:
```
10.84.44.208 - - [08/Jun/2023:03:17:22 +0000] "GET /streams/v1/index.json HTTP/2.0" 200 28263 "-" "Go-http-client/2.0"
10.84.44.208 - - [08/Jun/2023:03:17:22 +0000] "GET /streams/v1/com.ubuntu.cloud:released:gce.json HTTP/2.0" 200 3391252 "-" "Go-http-client/2.0"
```
these lines are strange for two reasons:
1) lxd is trying to download a gce image
2) the HTTP protocol being used is HTTP/2.0, which may be HTTP/1.1

As a comparison, when we cannot reproduce the problem, we also have some apaches logs(https://paste.ubuntu.com/p/xdbhv78g6T/)

I'm not particularly familiar with juju's code, but juju team told me that juju just passes the URL of mirror image to lxd, juju does not decide which image it want to download specifically, which should be decided by lxd. So, the above apache logs do show that the problem is likely to be on the lxd side (juju has already passed the URL of mirror image to lxd, but lxd is downloading gce image from the image mirror).

[1] https://bugs.launchpad.net/juju/+bug/2008993

### Steps to reproduce

Pls see this paste mentioned above - https://paste.ubuntu.com/p/V7zdZyt6CG/

**Comment by stgraber** [comment]
Can you show your `index.json`?

The simplestreams parser in LXD should skip over any entries that aren't of type `image-downloads`.

**Comment by stgraber** [comment]
We should have an entry like this:
```
    "com.ubuntu.cloud:released:download": {
      "datatype": "image-downloads",
      "path": "streams/v1/com.ubuntu.cloud:released:download.json",
      "updated": "Sat, 17 Jun 2023 04:40:35 +0000",
      "products": [
...
      ],
      "format": "products:1.0"
    },
```

Your server log suggests something being a fair bit wrong with the index.

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/blob/master/shared/simplestreams/simplestreams.go#L295 is the parsing logic

**Comment by zhhuabj** [comment]
Hi @stgraber , thanks for your review. The following paste is our index.json I got it by 'curl https://lp2008993.com:443/streams/v1/index.json -k'.

https://paste.ubuntu.com/p/q6KxBNxK8S/

I took a look and it seems to have the following entry.

  "com.ubuntu.cloud:released:download": {
   "datatype": "image-downloads", 
   "path": "streams/v1/com.ubuntu.cloud:released:download.json", 
   "updated": "Wed, 07 Jun 2023 20:38:49 +0000", 
   "products": [
      ...
   "format": "products:1.0"
  }, 

I created above image mirror using the following sstream-mirror command according to the record in reproducer(https://paste.ubuntu.com/p/V7zdZyt6CG/). Did I miss something with this command? 

sudo sstream-mirror --keyring=/usr/share/keyrings/ubuntu-cloudimage-keyring.gpg --progress --max=1 --path=streams/v1/index.json https://cloud-images.ubuntu.com/releases/ $workdir 'arch=amd64' 'release~(bionic)' 'ftype~(lxd.tar.xz|squashfs|root.tar.xz|root.tar.gz|disk1.img|.json|.sjson)'

**Comment by stgraber** [comment]
That index looks fine, I don't see why LXD wouldn't follow the download.json link in this case.

After getting a failure on a system, can you grab a tarball of the content of /var/snap/lxd/common/lxd/cache?

That should give us a copy of the index files as LXD downloaded them.

**Comment by zhhuabj** [comment]
Hi @stgraber , this testing env is on stsstack, so I can still grap this tarball for you now. 

But our reproducer is to first create a mulipath VM, then create an lxd controller and an lxd machine 0 inside this multipath VM, finally create lxd contrainer inside this lxd machine 0. This lxd machine 0 is a container so there is no snap here, lxd is installed through the deb package instead of snap.

So I checked the dir '/var/cache/lxd/' instead of '/var/snap/lxd/common/lxd/cache', there is only one file instance_types.yaml in the dir '/var/cache/lxd/', I didn't see any image cache inside.

ubuntu@test:~$ juju ssh -m m 0 -- ls /var/snap/lxd/common/lxd/cache
ls: cannot access '/var/snap/lxd/common/lxd/cache': No such file or directory
Connection to 10.84.44.246 closed.

ubuntu@test:~$ juju ssh -m m 0 -- snap list
No snaps are installed yet. Try 'snap install hello-world'.
Connection to 10.84.44.246 closed.
ubuntu@test:~$ juju ssh -m m 0 -- dpkg -l |grep lxd
ii  lxd                       3.0.3-0ubuntu1~18 amd64             Container hypervisor based on LXC - daemon
ii  lxd-client                3.0.3-0ubuntu1~18 amd64             Container hypervisor based on LXC - client
Connection to 10.84.44.246 closed.

ubuntu@test:~$ juju ssh -m m 0 -- sudo ls /var/cache/lxd/
instance_types.yaml
Connection to 10.84.44.246 closed.

**Comment by stgraber** [comment]
Oh, that's on LXD 3.0.x?
I don't know that the logic necessarily changed since then, but 3.0 is in the security only part of its lifespan and is actually hitting its final EOL upstream this week. So it'd be good to try to reproduce with something a bit more current as we're not going to be fixing 3.0.

**Comment by zhhuabj** [comment]
Hi @stgraber , yes, as I just explained, this reproducer(https://paste.ubuntu.com/p/V7zdZyt6CG/) is running in a container machine 0 inside a multipass VM so it's deb lxd 3.0(deb instead of snap). At that time, juju team believed that network isolation was necessary so they suggested using multipass + lxd container provider, so I started switching the test env to multipass, see https://bugs.launchpad.net/juju/+bug/2008993/comments/33

Actually, the customer is using lxd 5.0.2. 

Actaully, at the beginning of my test, my initail test was also using snap 5.0.2, I didn't use multipass + lxd container provider, I used a openstack over openstack env locally, so machine 0 here is a VM rather than a container, in this way, it's snap lxd 5.0.2 rather than deb lxd 3.0 . And this env is also there now, so I can still grap tarball for you now.

hua@minipc:~$ juju ssh -m m 0 -- sudo snap list |grep lxd
lxd     5.0.2-838e1b2  24322  5.0/stable/…   canonical✓  -
Connection to 10.0.0.54 closed.

hua@minipc:~$ juju ssh -m m 0 -- sudo ls /var/snap/lxd/common/lxd/cache
instance_types.yaml
Connection to 10.0.0.54 closed.

You can see, there is only one file instance_types.yaml in the dir '/var/snap/lxd/common/lxd/cache' as well.

So whether it's snap lxd 5.0.2 or deb lxd 3.0, this problem exists.

**Comment by stgraber** [comment]
Right, so a few things here:
 - If LXD had accessed your simplestreams server, there would be cached files
 - LXD never uses `Go-http-client/2.0` as a user-agent, it always shows up as `LXD 5.0.2 ...` and LXD has HTTP/2 disabled pretty much everywhere

I'm really not familiar with what Juju does, but as far as I can tell, your LXD server was never directly instructed to fetch from anything and the downloads you're seeing on your web server aren't from LXD, they're from another piece of Go software, my guess would be Juju.

If you want to be sure that nothing's actually talking to LXD at this stage, you can run `lxc monitor` which will show you any request being processed by LXD.

**Comment by zhhuabj** [comment]
Hi @stgraber, answer your two questions:

1, If LXD had accessed your simplestreams server, there would be cached files

We have already used tcpdump to capture pacakges, the tcpdump result shows our image mirror (simplestreams server) has indeed been called, we can refer to this comment for more details - https://bugs.launchpad.net/juju/+bug/2008993/comments/32

2, LXD never uses Go-http-client/2.0 as a user-agent, it always shows up as LXD 5.0.2 ... and LXD has HTTP/2 disabled pretty much everywhere

As for this issue, it is precisely why we feel strange and why we have opened this bug. juju team thought there are two starnge reasons at that time: 1) lxd is trying to download a gce image 2) the HTTP protocol being used is HTTP/2.0, which may be HTTP/1.1

I didn't search anything from codes of juju and lxd using the keyword 'Go-http-client'. More importantly, I have isolated the network through multipass, so it seems that there are only juju and lxd matters inside. juju team believes that the following apache logs can only come from lxd and cannot be from juju.

10.84.44.208 - - [08/Jun/2023:03:17:22 +0000] "GET /streams/v1/index.json HTTP/2.0" 200 28263 "-" "Go-http-client/2.0"

Because juju only passes the URL of the simplestreams server to lxd, who is responsible for downloading specific images, and tcpdump result show that the simplestreams server has indeed been accessed, but no images have been downloaded there (there is no image in the dir /var/snap/lxd/common/lxd/cache).

Why there is no image in the dir /var/snap/lxd/common/lxd/cache, as we can see from the log 'no matching image found' in juju status, it's because 'no matching image found'.

Why does it have 'no matching image found', it looks lxd is using Go-http-client/2.0 to download gce image. We don't have gce here so it have 'no matching image found'.

10.84.44.208 - - [08/Jun/2023:03:17:22 +0000] "GET /streams/v1/com.ubuntu.cloud:released:gce.json HTTP/2.0" 200 3391252 "-" "Go-http-client/2.0"

I think why lxd parsed gce from /streams/v1/index.json should be the key to the problem, I'm not familiar with juju and lxd, but I believe it's obvious that the logic of this is done by lxd rather than juju.

**Comment by stgraber** [comment]
```
stgraber@dakara:~/data/code/juju (develop)$ grep -ri 'no matching image found' .
./container/lxd/image.go:	lastErr := fmt.Errorf("no matching image found")
```

That's where that error comes from and that's from within the Juju code, not LXD's.

LXD doesn't have any code path which would cause it to access a simplestreams image server without its user agent string being set to `LXD <version>`. We're pretty sure of that given that we actively rely on that user agent string being correct across all LXD releases as that's how we get statistics on LXD usage from our image servers.

Picking a random image server, I've confirmed that for `index.json` specifically, we've had over 7000 downloads with the expected user agent as opposed to 55 without it. Those 55 are mostly from crawlers indexing the image server.
```
root@shell01:/data/images.linuxcontainers.org-logs# zcat nginx01.20230619-0000.log.gz | grep index.json | grep "LXD " | wc -l
7456
root@shell01:/data/images.linuxcontainers.org-logs# zcat nginx01.20230619-0000.log.gz | grep index.json | grep "LXD 5.0.2" | wc -l
612
root@shell01:/data/images.linuxcontainers.org-logs# zcat nginx01.20230619-0000.log.gz | grep index.json | grep -v "LXD " | wc -l
55
```

For good measure, you can also see that `5.0.2` above does report itself correctly.


So again, any download coming from LXD itself will show up as something like `"LXD 5.0.2 (Linux; x86_64; 5.15.0; Ubuntu; 22.04)"`, if you're not seeing that on your image server, then LXD wasn't what was talking to it.

**Comment by zhhuabj** [comment]
I continued to do some tests

1, Still use multipass to isolate the network, but use jammy instead of focal. At this point, machine 0 remains the container and will also use snap 5.0.2 instead of deb 3.0, but still able to successfully reproduce the problem, see https://paste.ubuntu.com/p/DMrRKzgBFV/

I see the following apache logs (this time it's aws, last time it's gce)

10.170.161.177 - - [20/Jun/2023:13:58:18 +0800] "GET /streams/v1/index.json HTTP/2.0" 200 28263 "-" "Go-http-client/2.0"
10.170.161.177 - - [20/Jun/2023:13:58:18 +0800] "GET /streams/v1/com.ubuntu.cloud:released:aws.json HTTP/2.0" 200 12675011 "-" "Go-http-client/2.0"

2, But sometimes I can't see any apache logs, so I removed iptables in the controller (juju ssh -m controller 0 -- sudo iptables -D OUTPUT -d 185.125.190.37 -j DROP && juju ssh -m controller 0 -- sudo iptables -D OUTPUT -d 185.125.190.40 -j DROP) then retested it, but I can see apache logs sometimes. however, the result is the same, still reproducing the problem, see - https://paste.ubuntu.com/p/ps3w27PYDR/

**Comment by zhhuabj** [comment]
Hi lxd team, the root cause has been identified now, that's because jujud-machine-0.service on machine0 needs to be restarted after installing the cert on it. So now this case can be closed. Thank you very much for your help.
