### ISSUE TITLE
How to use variables in profiles

### ISSUE THREAD

**Issue by joaocc** [lxc/lxd#1186]
Hi,
Is there any way to use a variable inside a profile file?
I would like to have a profile that added a disk to something like "/my/lxd/data/{{ container_name }}".
This would enable some very interesting scenarios of nearly-totally-declarative configuration of containers.

An alternative could be to have "lxc init" or "lxc launch" accept a YAML/JSON config file, which could be dynamically generated (via ansible for instance).

I thought of generating 1 profile file per host, but it seems badly aligned with the concept of profiles.

Thx

**Comment by jsimonetti** [comment]
I believe d176b6108e8567b3b2f901bb32d68603ccc0c651 does exactly what you are looking for. Just have to compile the latest master yourself or wait for the next release.

**Comment by joaocc** [comment]
Perfect!

**Comment by stgraber** [comment]
Not quite, this change allows you to pass key/value pairs on init/launch but this doesn't include modifying devices nor is it clear how such a syntax would look like given how much more complex devices are.

**Comment by joaocc** [comment]
hum... I see.. with something like what is below, it would be difficult to deal with consecutive applications.
```
lxc profile device add profile2 "mnt2" disk "source=/lxd-mnt/guests/{{conf.myVarA}}"  "path=/lxd-mnt/_shared" readonly=false
```
Any chance of adding the ability to specify a json/yaml file on lxc init? 
This way, those addicted to dynamically generating configurations (like myself) would have a much easier life :)

**Comment by stgraber** [comment]
yeah, having it read stdin like some of the other commands may be fine.

Until then, you can "lxc init image container" and the "lxc config edit container < yourconfig.yml", that's already supported.

**Comment by joaocc** [comment]
That will do it. I must have missed that one. Thx!
