### ISSUE TITLE
`getTotalProcesses()` should use `cgroup`'s `pids.current` for containers

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#11870]
ATM, [getTotalProcesses()](https://github.com/lxc/lxd/blob/master/lxd-agent/metrics.go#L161) is counting processes by walking `/proc` and counting dirs belonging to processes. It also does some basic validation to only count real processes and skip kernel threads. However, as the number of PIDs on an instance goes up so does the cost of counting them.

While I couldn't think of a simpler way for VMs, for containers, it should be faster and simpler to instead get the `pids.current` value from `cgroup`.

Here's what I got from a container (`lxd-cloud-mgr`) running inside a project named `lxd-cloud` on a `cgroup2` host:

```
# lxc query /1.0/metrics | grep '^lxd_procs_total{name="lxd-cloud-mgr"'
lxd_procs_total{name="lxd-cloud-mgr",project="lxd-cloud",type="container"} 219
# cat /sys/fs/cgroup/lxc.payload.lxd-cloud_lxd-cloud-mgr/pids.current
219

$ lxc info | grep cgroup2
    cgroup2: "true"
$ uname -a
Linux sdeziel-lemur 5.19.0-45-generic #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 x86_64 x86_64 x86_64 GNU/Linux
$ snap list lxd
Name  Version       Rev    Tracking       Publisher   Notes
lxd   5.14-7072c7b  24918  latest/stable  canonical✓  -
```

On another system (also `cgroup2`) and looking at a container (`vpn`) running inside the `default` project:

```
# cat /sys/fs/cgroup/pids/lxc.payload.vpn/pids.current
25
# lxc query /1.0/metrics | grep '^lxd_procs_total{name="vpn"'
lxd_procs_total{name="vpn",project="default",type="container"} 25

$ lxc info | grep cgroup2
    cgroup2: "true"
$ uname -a
Linux mars 5.15.0-75-generic #82~20.04.1-Ubuntu SMP Wed Jun 7 19:37:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ snap list lxd
Name  Version        Rev    Tracking    Publisher   Notes
lxd   5.0.2-838e1b2  24322  5.0/stable  canonical✓  -
```

**Note**: I didn't check with a `cgroup1` system if the same `pids.current` is also available and under which path.

**Comment by monstermunchkin** [comment]
If supported, we already read `pids.current` for containers. Walking through `/proc` is only a fallback: [processesState()](https://github.com/lxc/lxd/blob/master/lxd/instance/drivers/driver_lxc.go#L7264)

**Comment by simondeziel** [comment]
Thanks @monstermunchkin and @tomponline I see that's already optimized and I simply missed it, thanks for pointing me in the right direction!
