### ISSUE TITLE
Feature request: network and device override support for lxc import command

### ISSUE THREAD

**Issue by adamryczkowski** [lxc/lxd#11889]
I need to recover a backup of my LXC machine done on a different host. That backup has a different network interface encoded in its content, and that fact throws an error when doing `lxc import backup.tar.gz` like this one:

```
Error: Failed importing backup: Failed creating instance record: Failed initialising instance: Invalid devices: Device validation failed for "eth0": Failed loading device "eth0": Failed to load network "lxcbr0" for project "default": Network not found
```

I don't care for the network interface at all - I just want to `lxc exec <lxc-container> bash` and run the data extraction script. If I wanted to keep the container alive, I could also re-configure the networking later. But first I need to import the container in the first place.

**Comment by stgraber** [comment]
Unfortunately, on the LXD front, all we get is a tarball upload and when we do that, we don't get to send rich formatted data (json) alongside it. We can do a few basic overrides using HTTP header, like what we do for the instance name, but something more complex like rewriting devices is unlikely to get added.

In this particular scenario you have two pretty easy ways around the problem:
 - Create the network (`lxc network create lxcbr0`) and then delete it later
 - Edit backup.tar.gz, change backup.yaml inside of it to match what you want the instance to look like, then import it

**Comment by adamryczkowski** [comment]
I've already tried creation of the network before turning here. Unfortunately it does not work. 

```
$ lxc network create lxcbr0
Error: Network interface "lxcbr0" already exists
⏚ [adam:~] 1 $ lxc import radicale.tar.gz 
Error: Failed importing backup: Failed creating instance record: Failed initialising instance: Invalid devices: Device validation failed for "eth0": Failed loading device "eth0": Failed to load network "lxcbr0" for project "default": Network not found
```

What worked, was editing the `backup.tar.gz`, but that is very cumbersome, as simple "untar" would not preserve the special devices in the stream.

**Comment by adamryczkowski** [comment]
For future reference (for me and others), here is the tar command pair that eventually worked:

```
cd target-directory
sudo tar -xvzf /path/to/backup.tar.gz
```

~~ edit the configuration ~~

```
$ sudo tar -czvf edited-backup.tar.gz --preserve-permissions --same-owner target-directory/backup
```

**Comment by stgraber** [comment]
Ah,

```
$ lxc network create lxcbr0
Error: Network interface "lxcbr0" already exists
```

This indicates that you already have a network on your system named `lxcbr0` but that this isn't a network that's managed by LXD whereas your instance expects a LXD-managed network called lxcbr0.

You could have worked around that with:
 - ip link del lxcbr0
 - lxc network create lxcbr0

But that may have seriously impacted any container running on lxcbr0 (if any).
