### ISSUE TITLE
Assigning profile with empty device list causes error when stopping/deleting instance

### ISSUE THREAD

**Issue by pcgeek86** [lxc/lxd#11900]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-75-generic
   * LXC version: 5.13
   * LXD version: 5.13
   * Storage backend in use: `dir`

# Issue description

If an empty profile is applied to an LXD virtual machine, and you then attempt to delete the virtual machine, an error is thrown regarding the VM's root device (filesystem).

# Steps to reproduce

 1. Launch new VM with default profile: `lxc launch --vm images:ubuntu/23.04 u01`
 2. Create empty profile `lxc profile create trevor`
 3. Assign profile to VM `lxc profile assign u01 trevor`
 4. Attempt to delete VM: `lxc delete u01 --force`
 5. Notice error message: `Error: Stopping the instance failed: Failed unmounting instance: No root device could be found`
 6. Run the delete command again, and the VM is destroyed `lxc delete u01 --force`

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
Confirmed affects containers as well.

LXD should not allow an instance to exist that has no `/` disk after it has applied its expanded config from profiles.
