### ISSUE TITLE
Support providing the path to the config file.

### ISSUE THREAD

**Issue by ericsnowcurrently** [lxc/lxd#1196]
Currently the path to the config dir/file is hard-coded (see https://github.com/lxc/lxd/blob/master/config.go#L45).  It would be good if the relevant functions (e.g. LoadConfig) took an extra arg for the filename, defaulting to the current location.

(Though likely a separate feature request, the CLI could also be extended accordingly.)

**Comment by stgraber** [comment]
Yeah, that'd probably be fine, we may also want to move the LXD_CONF env variable to config.go instead of lxc/main.go

**Comment by tych0** [comment]
Yeah, I think this is part of https://github.com/lxc/lxd/issues/1177. Basically, the API has some warts in places, but I'd like to work on improving it next cycle.
