### ISSUE TITLE
unimplemented lxc device results in unusable container

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1200]
I tried experimenting with lxd chardevices.
I did the following:

``` 
% lxc config device add agocontrol zwavedongle unix-char path=/dev/ttyUSB0
Device zwavedongle added to agocontrol
```
At this point, I cannot really do much with the container anymore:

```
1 jeroen@server ~ % lxc start agocontrol
error: Failed configuring device zwavedongle: Not implemented

1 jeroen@server ~ % lxc config device remove agocontrol zwavedongle
error: Failed configuring device zwavedongle: Not implemented

1 jeroen@server ~ % lxc config edit agocontrol
error: Failed configuring device zwavedongle: Not implemented

```
If a device type is not implemented, it should not be accepted to add it in the first place.

Edit: even deleting is now impossible:
```
% lxc delete agocontrol
error: Failed configuring device zwavedongle: Not implemented

```
This specific container is now also invisible from 'lxc list'.

**Comment by stgraber** [comment]
That seems like a bit of a problem :)

@hallyn can you either implement those missing bits (should be pretty easy really) or have things fail in a better way? :)

**Comment by jsimonetti** [comment]
Also, there's not really a reason why you'd need to configure devices when deleting the container, is there?

**Comment by stgraber** [comment]
Not really, no, I think what's happening is that the containerload function resolves the final container config whenever it's called, which it is during delete to figure out snapshots and other things. The device config part is never used, but some of the rest is.

**Comment by hallyn** [comment]
That's spectacular.  Thanks for pointing it out.
