### ISSUE TITLE
implement tunnel interfaces inside container (sit, gre, etc)

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1204]
AFAICT is is currently not possible to create tunnel interfaces inside the container without some help of the host.
The lxc network type is not implemented by LXD.
I'm not sure if this is a limitation of LXD or of LXC and or what peaces are missing to complete this.

It would be nice to be able to create tunnel interfaces inside a container.
Currently you get an error as:
```
root@ct:~# ip tunnel add tunname mode sit remote 10.1.1.1 local 10.10.1.1 ttl 255
add tunnel "sit0" failed: No such device
```

**Comment by jsimonetti** [comment]
After soms research I think that when #1200 is solved, adding /dev/net/tun as chardev tot the container would be all that is needed tot resolve this.
I will test when it is releases.

**Comment by jsimonetti** [comment]
This was indeed reolved by said fix.
`lxc config device add container net-tun unix-char path=/dev/net/tun` was enough to be able to add tunnels inside the container.

**Comment by stgraber** [comment]
Perfect!

**Comment by dkruyt** [comment]
This solution didn't help me, I run lxd version 2.15 on ubuntu 16.04

```
root@testtun:~# ip tunnel add tunname mode sit remote 10.1.1.1 local 10.10.1.1 ttl 255
add tunnel "sit0" failed: No such device
root@testtun:~# exit
root@lxdhost:~# lxc config device add testtun net-tun unix-char path=/dev/net/tun
error: The device already exists
```

If I set the container testtun to security.privileged true it works.

**Comment by stgraber** [comment]
@dkruyt that's because you're creating a sit tunnel, not a tun/tap tunnel.

You're most likely just missing the needed kernel module.

    lxc config set testtun linux.kernel_modules sit

Should fix that.

**Comment by dkruyt** [comment]
@stgraber yes, this fixed it. thanks. Because of the previous post/answer i misinterpreted.

**Comment by caitlinbestler** [comment]
I'm also running on ubunutu 16.04, and I am getting an "error: not found" response.
I have no idea where the 'testun' label comes from, and I suspect that is related to what isn't working.
