### ISSUE TITLE
lvm: allow lv resizing

### ISSUE THREAD

**Issue by epicfilemcnulty** [lxc/lxd#1205]
When using lvm as storage backend, upon creating a container lxd creates a new fixed sized lv, the size is hardcoded and equals to 100Gb. It would be very nice to have an option to change it through lxd config, at least globally. Though, I guess, it would be just awesome if we could specify the size per container as well.

**Comment by stgraber** [comment]
Yeah, I'd prefer we make it a property on the storage device of the container, that way we can resize containers and can also set quotas for zfs and btrfs the same way.

**Comment by austinjp** [comment]
Hi both.

I'm confused by this. Does LVM work as a storage backend in LXD? It seems from this issue that the size cannot be set, but I'm having trouble getting LVM working in LXD at all.

I've mentioned this on the lxc-users mailing list, although no replies there currently: http://permalink.gmane.org/gmane.linux.kernel.containers.lxc.general/10219

Incidentally -- I hugely appreciate LXC and I'm very much looking forward to using LXD. Great work all round.

**Comment by mikemccracken** [comment]
Hi @austinjp, I've replied on the list, thanks for bringing that up.
For completeness' sake, I'll mention here too that the `storage.lvm_vg_name` config is a server setting, not a per-container setting, so you set it using `lxc config set storage.lvm_vg_name vgname` , and you don't need to add it to a profile as you were doing. 

Then the volume group will be used for any future containers or images you create (but we don't convert existing containers or images.)

**Comment by stgraber** [comment]
I have updated our internal specification to cover storage quotas in a generic way, I'm hoping I'll be allowed to publish this work very soon.

**Comment by austinjp** [comment]
Both -- many thanks. Once again, very excited by containers. It's enabling me to build a project that's been a pipe-dream for months.

**Comment by aarnaud** [comment]
Hi @stgraber,

I hope to test this feature.  When it's available?

Thanks

**Comment by stgraber** [comment]
I've implemented CPU and memory limits, storage and network are the next ones in line.

**Comment by austinjp** [comment]
Many thanks Stéphane.

**Comment by stgraber** [comment]
Ok, so the size= option on disk devices now exists and is supported with btrfs and zfs. LVM is much trickier because we can't just go and resize things while the container is running.

For LVM, I expect we'd need:
 - Restrict the change to size= on LVM backed containers to only be valid when stopped.
 - If not stopped (we must support this because of profiles), a "volatile.lvm_resize" property should be set to true so that the container gets resized on next startup.
 - Resize code in the LVM backend must be added to first resize the inner filesystem (ext4 or xfs) and then the LV itself.

It's not a priority for my team to do so, so a branch by an interested party would be great.

**Comment by aarnaud** [comment]
Thanks @stgraber 

I use btrfs on some host, now.

I will try when i have some time

**Comment by austinjp** [comment]
Thanks Stéphane, appreciate the update.

I'll check out btrfs for now.

Austin.

**Comment by brauner** [comment]
Right, I misunderstood the issue to some extent. I thought it was about adding quota support for users and groups. This issue should be renamed to reflect the fact that it is about resizing an existing lv and not about setting quota in the {btrfs,zfs} sense.
