### ISSUE TITLE
boot.autostart blocks lxc/lxd commands

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1209]
When having multiple containers start automatically at boot time, it appears LXD is blocked until all autostart containers have finished booting. This is best seen when containers have an autostart delay.

I see this behavior when running 3 containers, each with the following configuration.

1:
config:
  boot.autostart: "true"
  boot.autostart.delay: "30"
  boot.autostart.priority: "100"

2:
  boot.autostart: "true"
  boot.autostart.delay: "5"
  boot.autostart.priority: "1"

3:
  boot.autostart: "true"
  boot.autostart.delay: "5"
  boot.autostart.priority: "0"

When the server has just booted (and container 1 has just started), 'lxc list' blocks until all containers are fully started and then returns the list of containers.

**Comment by stgraber** [comment]
That's correct, we currently perform that action before starting the http server. This seemed sane at the time, basically ensuring things would be all ready by the time we start responding, but is indeed a problem when running a lot of containers.

I'll change this code to be in a go routine instead.
