### ISSUE TITLE
Ssh hangs with CentOS image

### ISSUE THREAD

**Issue by pratz** [lxc/lxd#1215]
I am using centos image from http://images.linuxcontainers.org/images/centos/7/amd64/
ssh server is installed and running, but I can not ssh to centos from host os (Ubuntu)

NOTE:
ssh works fine with ubuntu/debian images.

Can anyone guide.

**Comment by stgraber** [comment]
Anything in /var/log/auth.log or similar?

This is pretty much guaranteed not to be a LXD issue, but instead something broken in centos 7 as far as running inside a container.

**Comment by pratz** [comment]
I think, on centos ssh logs are logged to /var/log/secure, I checked the logs but nothing there.

Even I am sure its not related to LXD, but the image is downloaded from images.linuxcontainers.org, so if anyone using centos with lxd will face this issue.

Also, can I add different remote ?

**Comment by pratz** [comment]
@stgraber 
Just tested with centos 6 http://images.linuxcontainers.org/images/centos/6/amd64 and ssh works fine.

So, the issue is with centos 7 image, can this issue be redirected to the person/community how uploads the images?

**Comment by stgraber** [comment]
Images are generated by using the lxc-centos template from LXC upstream, so you could file a bug against lxc instead for that template to be fixed to workaround/fix whatever this bug is.

Unfortunately the lxc-fedora/lxc-centos template maintainer hasn't been very active lately, so you may have to help contribute to the solution.

**Comment by stgraber** [comment]
Closing this as not an issue with LXD itself, instead with the distro and/or the LXC template used to generate the image.
