### ISSUE TITLE
Windows undefined: syscall.SIGWINCH

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1226]
I believe this is the last change needed to resolve #825.
```
>go install -v ./lxc
github.com/lxc/lxd/lxc
# github.com/lxc/lxd/lxc
lxc\exec.go:90: undefined: syscall.SIGWINCH
```

https://github.com/lxc/lxd/blob/master/lxc/exec.go#L88

Something tells me that this can be replaced by [terminal.SetSize](https://godoc.org/golang.org/x/crypto/ssh/terminal#Terminal.SetSize), but I don't completely understand the logic to understand what exactly is going on there.

**Comment by tych0** [comment]
On Sun, Oct 18, 2015 at 12:01:19PM -0700, anatoly techtonik wrote:
> I believe this is the last change needed to resolve #825.
> ```
> >go install -v ./lxc
> github.com/lxc/lxd/lxc
> # github.com/lxc/lxd/lxc
> lxc\exec.go:90: undefined: syscall.SIGWINCH
> ```
> 
> https://github.com/lxc/lxd/blob/master/lxc/exec.go#L88
> 
> Something tells me that this can be replaced by [terminal.SetSize](https://godoc.org/golang.org/x/crypto/ssh/terminal#Terminal.SetSize), but I don't completely understand the logic to understand what exactly is going on there.

This is for receiving SIGWINCH so we can send it across to the daemon
to send to the actual process that's running, so I don't think SetSize
will help us here.

However, I think we can dump most of this code in a _linux.go file, so
I'll send a patch to do that. (I also found what looks like a bug, so
I'll send a patch for that too.)

**Comment by techtonik** [comment]
Awesome! Let me test the build.
