### ISSUE TITLE
What can I do with Windows client?

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1236]
Now that #825 is almost fixed I have `lxc.exe` binary. What can I do with it? And test that it works?

**Comment by tych0** [comment]
On Thu, Oct 22, 2015 at 01:59:07PM -0700, anatoly techtonik wrote:
> Now that #825 is almost fixed I have `lxc.exe` binary. What can I do with it? And test that it works?

Try something like:

lxc remote add foo $an_lxd_server
lxc remote set-default foo
lxc list

and see if it works.

**Comment by techtonik** [comment]
Yes. That works ok. =) What else can be done?
```
>lxc remote add lxc images.linuxcontainers.org
>lxc remote list
+-------+-----------------------------------------+--------+
| NAME  |                   URL                   | PUBLIC |
+-------+-----------------------------------------+--------+
| local | unix://                                 | NO     |
| lxc   | https://images.linuxcontainers.org:8443 | YES    |
+-------+-----------------------------------------+--------+
>lxc remote set-default lxc
>lxc remote get-default
lxc
```

**Comment by tych0** [comment]
On Thu, Oct 22, 2015 at 09:52:16PM -0700, anatoly techtonik wrote:
> Yes. That works ok. =) What else can be done?

https://github.com/lxc/lxd/blob/master/specs/command-line-user-experience.md
lxc --help

all have more information on how to use the client.

**Comment by techtonik** [comment]
Stuff that doesn't work references this ticket as separate issues. Stuff that works:
```
> lxc.exe image list lxc:
```

**Comment by techtonik** [comment]
I was able to connect to remote LXD server. Now I need to import some images there, because `lxc init ubuntu u1` fails with `can't get info for image 'ubuntu'`

**Comment by techtonik** [comment]
Reminder. LXD server side:
```
sudo ip addr
sudo lxc config set core.https_addresses 192.168.1.15
sudo lxc config set core.trust_password 123456
```
LXC client side:
```
lxc remote add mote https://192.168.1.15
lxc remote add lxc images.linuxcontainers.org
lxc remote set-default mote
```

Then copy Ubuntu 15.10 image from remote `lxc` storage to local `mote` machine:
```
lxc image copy lxc:ubuntu/wily/amd64 mote: --alias=ubuntu
```

**Comment by stgraber** [comment]
Lets just go with one issue per actual problem instead of catch-all issues. Looks like we've got one for the arrow keys support so I'm closing this one.
