### ISSUE TITLE
cap_set_file not permitted

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1245]
Running a Centos7 container (669aa1973610) I'm getting below error when trying to install httpd.

This seems to be identical to the docker issue at https://github.com/docker/docker/issues/6980
Unfortunately, in that issue they blame aufs and suggest using btrfs.
However, I am already running btrfs.
I have no idea how to troubleshoot this further. Any advise is welcome.

```
[root@server ~]# yum install httpd
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.netnitco.net
 * extras: centos.netnitco.net
 * updates: centos.netnitco.net
Resolving Dependencies
--> Running transaction check
---> Package httpd.x86_64 0:2.4.6-31.el7.centos.1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================================================================
 Package                                  Arch                                      Version                                                  Repository                                  Size
==============================================================================================================================================================================================
Installing:
 httpd                                    x86_64                                    2.4.6-31.el7.centos.1                                    updates                                    2.7 M

Transaction Summary
==============================================================================================================================================================================================
Install  1 Package

Total download size: 2.7 M
Installed size: 9.4 M
Is this ok [y/d/N]: y
Downloading packages:
httpd-2.4.6-31.el7.centos.1.x86_64.rpm                                                                                                                                 | 2.7 MB  00:00:02
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : httpd-2.4.6-31.el7.centos.1.x86_64                                                                                                                                         1/1
Error unpacking rpm package httpd-2.4.6-31.el7.centos.1.x86_64
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file
  Verifying  : httpd-2.4.6-31.el7.centos.1.x86_64                                                                                                                                         1/1

Failed:
  httpd.x86_64 0:2.4.6-31.el7.centos.1

Complete!
[root@server ~]#
```

**Comment by stgraber** [comment]
Is that an unprivileged container (security.privileged isn't set to true)?

If so, then that's most likely a kernel restriction as current upstream kernel doesn't allow users to set fs capabilities. @hallyn started doing some design work to fix that upstream.

**Comment by jsimonetti** [comment]
Yes, this is indeed an unprivileged container.
Thanks for the explaination. I will await the upstream fixes.

**Comment by kaistian** [comment]
What's the workaround for this?

I tried ```lxc config set centos7 security.nesting true``` but still get this error message:
```
  Installing : httpd-2.4.6-40.el7.centos.1.x86_64
Error unpacking rpm package httpd-2.4.6-40.el7.centos.1.x86_64
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file
  Verifying  : httpd-2.4.6-40.el7.centos.1.x86_64

Failed:
  httpd.x86_64 0:2.4.6-40.el7.centos.1
```

**Comment by hallyn** [comment]
On Sat, Jul 16, 2016 at 01:13:28PM -0700, Kai Stian Olstad wrote:
> What's the workaround for this?
> 
> I tried ```lxc config set centos7 security.nesting true``` but still get this error message:
> ```
>   Installing : httpd-2.4.6-40.el7.centos.1.x86_64
> Error unpacking rpm package httpd-2.4.6-40.el7.centos.1.x86_64
> error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file

Currently there is no workaround for this.  You cannot set file capabilities
from a user namespace other than the initial one.

**Comment by stgraber** [comment]
Until the kernel supports unprivileged fs capabilities you need security.privileged set to true which should then fix your problem, at the cost of much degraded container security.

**Comment by kaistian** [comment]
Of course ```security.nesting != security.privileged```.
```lxc config set centos7 security.privileged true``` did the trick.

Thank you @stgraber

**Comment by candlerb** [comment]
Is it a reasonable workaround to set the container to privileged, install httpd, and then set it back again?

**Comment by hallyn** [comment]
On Fri, Oct 14, 2016 at 02:46:11AM -0700, Brian Candler wrote:
> Is it a reasonable workaround to set the container to privileged, install httpd, and then set it back again?

You may then need to change the file ownerships afterward, but sure.  Or
it may be easier to just create a private package which skips the
filecaps, install that, then set the filecaps from the host.

Fwiw I'm supposed to give an update on this at the plumbers containers
track so there's a chance I'll whip up a new patch before then, and
maybe we can get something agreed on by the end of the year :)

**Comment by stiobhan** [comment]
Does anybody know if a kernel patch exists or if someone is working on it?

I'm running into similar problems when running yum update in a CentOS 7 container:
```
Running transaction
  Updating   : filesystem-3.2-21.el7.x86_64                                                                                                                                                              1/4 
Error unpacking rpm package filesystem-3.2-21.el7.x86_64
error: unpacking of archive failed on file /proc: cpio: chown
  Updating   : iputils-20160308-8.el7.x86_64                                                                                                                                                             2/4 
Error unpacking rpm package iputils-20160308-8.el7.x86_64
error: filesystem-3.2-21.el7.x86_64: install failed
error: unpacking of archive failed on file /usr/bin/ping;5877ab33: cpio: cap_set_file
filesystem-3.2-20.el7.x86_64 was supposed to be removed but is not!
  Verifying  : filesystem-3.2-20.el7.x86_64                                                                                                                                                              1/4 
iputils-20121221-7.el7.x86_64 was supposed to be removed but is not!
  Verifying  : iputils-20121221-7.el7.x86_64                                                                                                                                                             2/4 
  Verifying  : iputils-20160308-8.el7.x86_64                                                                                                                                                             3/4 
  Verifying  : filesystem-3.2-21.el7.x86_64                                                                                                                                                              4/4 

Failed:
  filesystem.x86_64 0:3.2-20.el7                    filesystem.x86_64 0:3.2-21.el7                    iputils.x86_64 0:20121221-7.el7                    iputils.x86_64 0:20160308-8.el7                   

Complete!
```

Is there really no better workaround?

**Comment by brauner** [comment]
@hallyn has a working patchset as far as I know.

**Comment by hallyn** [comment]
Yes, see this thread https://lkml.org/lkml/2016/11/19/158

**Comment by hallyn** [comment]
This is finally fixed upstream in Linus' kernel (not yet available in distro kernels, I assume).

**Comment by stiobhan** [comment]
Thanks for the update. Is this the commit? https://github.com/torvalds/linux/commit/8db6c34f1dbc8e06aa016a9b829b06902c3e1340

**Comment by hallyn** [comment]
Yup.

**Comment by slesru** [comment]
>is there really no better workaround?

Just because I'm root on host and both host and container are cenots 7 , I just did chroot to container's fs and yum update - it installed iputils in centos 7 container without need to comment out 

lxc.cap.drop = mac_admin mac_override
# setfcap
in centos.common.conf 
and container restart :-)

**Comment by lhorace** [comment]
> > is there really no better workaround?
> 
> Just because I'm root on host and both host and container are cenots 7 , I just did chroot to container's fs and yum update - it installed iputils in centos 7 container without need to comment out setfcap in
> 
> lxc.cap.drop = mac_admin mac_override setfcap
> in centos.common.conf
> and container restart :-)

This did not work for me at all, in fact, it made the filesystem read-only.
