### ISSUE TITLE
End of support date for development lxd on Ubuntu 15.04 Vivid is not documented

### ISSUE THREAD

**Issue by tim-seoss** [lxc/lxd#1249]
Documentation bug...

The lxd stable ppa has been targeting Ubuntu 15.04 Vivid, but it's not currently documented (e.g. at https://insights.ubuntu.com/2015/03/20/installing-lxd-and-the-command-line-tool/ and http://www.ubuntu.com/cloud/tools/lxd or https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxd-stable etc.) when this support will cease in favour of 15.10 Wily.

For users who are evaluating / tracking the lxd stable ppa with Vivid at the moment, publishing this information would be useful...

**Comment by stgraber** [comment]
The PPA builds are automated so they'll be happening until Ubuntu 15.04 goes end of life in January.

**Comment by stgraber** [comment]
Unless otherwise specified, we support things until the Ubuntu release in question goes end of life.

**Comment by tim-seoss** [comment]
That's good to know thanks - most Ubuntu users wanting to try lxd are likely to hit:

https://insights.ubuntu.com/2015/03/20/installing-lxd-and-the-command-line-tool/

... as this is linked to from http://www.ubuntu.com/cloud/tools/lxd

I believe that some features present on lxd on 15.04 aren't available with lxd on 14.04 due to kernel differences etc., so somewhere which documents which releases have available lxd builds (and maybe which are the latest versions and features available across the latest build on each release) would be really helpful.

I'm expecting to upgrade my eval 15.04 box to 15.10 at some point, but some indication in the online docs of when that should be would be really helpful.

Cheers,

Tim.

**Comment by tim-seoss** [comment]
...  and indeed which releases are supported at all - this is mentioned on https://insights.ubuntu.com/2015/04/28/getting-started-with-lxd-the-container-lightervisor/ - but that's not so easily found, and may be out of date - e.g. I couldn't find any mention on lxd stable with wily.

**Comment by stgraber** [comment]
We're now publishing backports as far back as 14.04. Anything that's in an Ubuntu release or is the latest upstream is supported so I don't see the need for further clarification.

We will have a long term support release in 16.04 which will have a clear support statement as we do for LXC itself.
