### ISSUE TITLE
VLAN support for containers

### ISSUE THREAD

**Issue by dodoadoodoo** [lxc/lxd#1256]
I'd like to assign a host VLAN as the container network connection, somewhat similar to:
```
lxc.network.type   =   macvlan
lxc.network.macvlan.mode = bridge                                                    
lxc.network.link   =   eth0.10 
```

Is there a way to do this?

**Comment by stgraber** [comment]
LXD currently doesn't have macvlan support though it's something we could add.

For now, you'd have to define a new bridge say br10 with eth0.10 bridged into it and then specify that as the bridge for your container.

**Comment by dodoadoodoo** [comment]
Bridges confuse me, so explicit macvlan support would be very welcome indeed

**Comment by robsanderson** [comment]
+1 for macvlan support in LXD.
