### ISSUE TITLE
lxd-images sync improvements

### ISSUE THREAD

**Issue by rcj4747** [lxc/lxd#1257]
When there are multiple images with the lxd-images.sync property a call to sync will not log the name of the image being updated and it will download the same gpg key and simplestreams each time.

Here is a sync of precise, trusty, vivid, and wily ubuntu-cloud images:
```
$ lxd-images sync
Downloading the GPG key for http://cloud-images.ubuntu.com
Validating the GPG signature of /tmp/tmpd7t88yga/download.json.asc
Downloading the GPG key for http://cloud-images.ubuntu.com
Validating the GPG signature of /tmp/tmpes5s32ma/download.json.asc
Downloading the GPG key for http://cloud-images.ubuntu.com
Validating the GPG signature of /tmp/tmpzgn2xn2o/download.json.asc
Downloading the GPG key for http://cloud-images.ubuntu.com
Validating the GPG signature of /tmp/tmpt6clxwoe/download.json.asc
```

It would be nice to have some output on the current image like alias and fingerprint:
```
$ lxd-images sync
Performing sync for image 'precise' with fingerprint 3c5d21d3912e
Downloading the GPG key for http://cloud-images.ubuntu.com
Validating the GPG signature of /tmp/tmpd7t88yga/download.json.asc
Performing sync for image 'trusty' with fingerprint b739c004c56e
Downloading the GPG key for http://cloud-images.ubuntu.com
Validating the GPG signature of /tmp/tmpt6clxwoe/download.json.asc
```

And it would be ideal if the same gpg key and simplestreams were cached from the first operation.

**Comment by stgraber** [comment]
Hi,

We'd certainly welcome a patch/branch to improve those things but will not spend much engineering time on this ourselves as lxd-images is going away this cycle in favor of native simplestreams support directly in LXD.

**Comment by stgraber** [comment]
As stated, we will not be spending time on this as simplestream support will be implemented directly into LXD. Things are unlikely to be much more transparent there since it'll all be run by the main daemon without user intervention, though one could inspect the ongoing operations and see download percentage and other details there.

Anyway, we won't be doing any work on lxd-images, so closing this issue.
