### ISSUE TITLE
Unable to connect to: images.linuxcontainers.org:8443

### ISSUE THREAD

**Issue by KIVagant** [lxc/lxd#1260]
Hello.
I'm trying to run my first centos container with LXD and I get this error:

```
lxc remote add images images.linuxcontainers.org
lxc launch images:centos/7/amd64 centos
# error: Get https://images.linuxcontainers.org:8443/1.0: Unable to connect to: images.linuxcontainers.org:8443
```
When I trying to download container manually, I see this: 
```
wget http://images.linuxcontainers.org/images/centos/7/amd64/default/20151102_02:16/lxd.tar.xz
--2015-11-02 20:30:51--  http://images.linuxcontainers.org/images/centos/7/amd64/default/20151102_02:16/lxd.tar.xz
Resolving images.linuxcontainers.org... 192.99.34.219, 2001:470:b368:1020:1::2
Connecting to images.linuxcontainers.org|192.99.34.219|:80... failed: Operation timed out.
Connecting to images.linuxcontainers.org|2001:470:b368:1020:1::2|:80... failed: No route to host.
```

Can you help me to create Centos 7 container for LXD?
Thank you.

P.S.: I don't have any problems with ubuntu containers when I run commands from manual:

```
 #both works fine
lxd-images import busybox --alias busybox
lxd-images import ubuntu --alias ubuntu
```

**Comment by cybe** [comment]
The host seems to be somewhat overloaded. I'm getting either timeouts or transfer rates of about 5 kB/s.

**Comment by stgraber** [comment]
This should now be resolved.

The problem was 800Gb/s (yes, Gb/s) worth of fiber being cut next to the datacenter running the main linuxcontainers.org server. They are still busy splicing all the fibers back together (it was the main bundle connecting the datacenter in Canada to the US) but brought online around 300Gb/s of new fibers that workaround the incident.

**Comment by KIVagant** [comment]
Thank you for information, @stgraber

**Comment by jjaone** [comment]
I'm having problems to create a LXD/LXC container, the linuxcontainers.org -site is unreachable:
$ wget http://images.linuxcontainers.org//meta/1.0/index-system
`--2016-07-12 12:21:00--  http://images.linuxcontainers.org//meta/1.0/index-system
Resolving images.linuxcontainers.org (images.linuxcontainers.org)... 149.56.148.5, 2001:470:b368:1020:1::2
Connecting to images.linuxcontainers.org (images.linuxcontainers.org)|149.56.148.5|:80... failed: No route to host.
Connecting to images.linuxcontainers.org (images.linuxcontainers.org)|2001:470:b368:1020:1::2|:80... failed: Network is unreachable.`

**Comment by stgraber** [comment]
Should be back now, there was some hardware maintenance going on in the datacenter causing about a 30min outage while they were replacing the cooling system.

**Comment by luborj** [comment]
Very similar issue:
"Unable to fetch https://images.linuxcontainers.org/images/debian/buster/amd64/default/20200421_05:24/lxd.tar.xz: 404 Not Found"


![Screenshot from 2020-04-21 08-35-00](https://user-images.githubusercontent.com/60156551/79833070-04b77680-83ab-11ea-9ae9-8457335e62e2.png)

**Comment by dankegel** [comment]
I'm hitting this now.
```
Error: Failed instance creation: Unable to fetch https://images.linuxcontainers.org/images/fedora/31/amd64/default/20200525_20:33/lxd.tar.xz: 404 
```
The image in question is present at us.images.linuxcontainers.org; is there any way to redirect?  Editing /etc/hosts doesn't seem to do it :-(

**Comment by stgraber** [comment]
This occasionally happens when the frontends sync at the same time the backend finishes refreshing.
It will clear within the hour.

**Comment by dankegel** [comment]
s'ok, I just used virtualbox instead.

**Comment by dankegel** [comment]
Frankly, though, you might want to look into making the mirrors atomic.  That kind of behavior isn't ok with apt, and it's not ok with lxd.  You really don't want hours of downtime in core infrastructure.

**Comment by stgraber** [comment]
The master mirror is switched atomically, mirrors getting interrupted mid-transfer and resuming is the problem and it's also a problem with apt mirros.

**Comment by dankegel** [comment]
Well, yes.
