### ISSUE TITLE
Can I read lxd.db directly?

### ISSUE THREAD

**Issue by KIVagant** [lxc/lxd#1263]
Hello.

I've read manual about lxd [sqlite storage](https://github.com/lxc/lxd/blob/master/specs/database.md) and then I tried to open the database:
```
sqlite /var/lib/lxd/lxd.db
Unable to open database "/var/lib/lxd/lxd.db": file is encrypted or is not a database
```

Could you tell me, please, can I open this db directly or this file can be used only by lxd utility?

Thank you.

**Comment by tych0** [comment]
On Tue, Nov 03, 2015 at 12:10:46AM -0800, Eugene Glotov wrote:
> Hello.
> 
> I've read manual about lxd [sqlite storage|https://github.com/lxc/lxd/blob/master/specs/database.md] and then I tried to open the database:
> ```
> sqlite /var/lib/lxd/lxd.db
> Unable to open database "/var/lib/lxd/lxd.db": file is encrypted or is not a database
> ```

try sqlite3 instead.

> Could you tell me, please, can I open this db directly or this file used only by lxd utility?

You can read it directly, but this is not a public API and we reserve
the right to change its format at any time.
