### ISSUE TITLE
Unable to copy images from images.linuxcontainers.org:8443

### ISSUE THREAD

**Issue by kkptNinja** [lxc/lxd#1264]
Hi,

It's been a while since i've last used lxd. So, today i tried to check things out again and to my surprise the following command is failing:

```
$ lxc image copy lxc-org:ubuntu/wily/amd64 local: ubuntu_15.10
error: wrong number of subcommand arguments
```
When i check the status like so:

```
$ systemctl status -l lxd
● lxd.service - Container hypervisor based on LXC
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: active (running) since Tue 2015-11-03 10:01:36 EET; 32min ago
 Main PID: 809 (lxd)
   Memory: 400.0K
      CPU: 2ms
   CGroup: /system.slice/lxd.service
           ‣ 809 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log

Nov 03 10:01:36 Base systemd[1]: Started Container hypervisor based on LXC.
Nov 03 10:11:47 Base lxd[809]: t=2015-11-03T10:11:47+0200 lvl=eror msg="Failed to download image metadata" image=2074453abb29a317de60394c54eaa0d0bb46ac69174ee376aa491c7dfcc4c8c4 err="Get https://images.linuxcontainers.org:8443/1.0/images/2074453abb29a317de60394c54eaa0d0bb46ac69174ee376aa491c7dfcc4c8c4: Unable to connect to: images.linuxcontainers.org:8443"
```
It tells that there is no connection to images.linuxcontainers.org:8443

Yet running wget on the URL it was trying to reach works out fine. For instance,
```
$ wget https://images.linuxcontainers.org:8443/1.0/images/2074453abb29a317de60394c54eaa0d0bb46ac69174ee376aa491c7dfcc4c8c4 -O -
--2015-11-03 10:39:44--  https://images.linuxcontainers.org:8443/1.0/images/2074453abb29a317de60394c54eaa0d0bb46ac69174ee376aa491c7dfcc4c8c4
Connecting to 10.144.1.10:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 517 [application/json]
Saving to: ‘STDOUT’

-                                                     0%[                                                                                                                     ]       0  --.-KB/s             {"metadata": {"expires_at": 0, "aliases": [{"description": "", "target": "ubuntu/wily/amd64/default"}, {"description": "", "target": "ubuntu/wily/amd64"}], "uploaded_at": 1446526182, "properties": {"description": "Ubuntu wily (amd64)"}, "fingerprint": "2074453abb29a317de60394c54eaa0d0bb46ac69174ee376aa491c7dfcc4c8c4", "architecture": 2, "created_at": 1446526182, "filename": "ubuntu-wily-amd64-default-20151103_03:49.tar.xz", "public": 1, "size": 77535144}, "type": "sync", "status": "Success", "status_code": 200}
-                                                   100%[====================================================================================================================>]     517  --.-KB/s   in 0s     

2015-11-03 10:39:46 (34.9 MB/s) - written to stdout [517/517]
```
One thing to note is that I am behind a proxy and the environment vars `http_proxy` and `https_proxy` have been configured correctly (E.g. wget above works). 

Would someone know what I am missing in order to get the image copy command to work?

**Comment by tych0** [comment]
On Tue, Nov 03, 2015 at 12:42:06AM -0800, kkptNinja wrote:
> Hi,
> 
> It's been a while since i've last used lxd. So, today i tried to check things out again and to my surprise the following command is failing:
> 
> ```
> $ lxc image copy lxc-org:ubuntu/wily/amd64 local: ubuntu_15.10
> error: wrong number of subcommand arguments
> ```
> When i check the status like so:
> 
> ```
> $ systemctl status -l lxd
> ● lxd.service - Container hypervisor based on LXC
>    Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
>    Active: active (running) since Tue 2015-11-03 10:01:36 EET; 32min ago
>  Main PID: 809 (lxd)
>    Memory: 400.0K
>       CPU: 2ms
>    CGroup: /system.slice/lxd.service
>            ‣ 809 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
> 
> Nov 03 10:01:36 Base systemd[1]: Started Container hypervisor based on LXC.
> Nov 03 10:11:47 Base lxd[809]: t=2015-11-03T10:11:47+0200 lvl=eror msg="Failed to download image metadata" image=2074453abb29a317de60394c54eaa0d0bb46ac69174ee376aa491c7dfcc4c8c4 err="Get https://images.linuxcontainers.org:8443/1.0/images/2074453abb29a317de60394c54eaa0d0bb46ac69174ee376aa491c7dfcc4c8c4: Unable to connect to: images.linuxcontainers.org:8443"
> ```
> It tells that there is no connection to images.linuxcontainers.org:8443
> 
> Yet running wget on the URL it was trying to reach works out fine. For instance,
> ```
> $ wget https://images.linuxcontainers.org:8443/1.0/images/2074453abb29a317de60394c54eaa0d0bb46ac69174ee376aa491c7dfcc4c8c4 -O -
> --2015-11-03 10:39:44--  https://images.linuxcontainers.org:8443/1.0/images/2074453abb29a317de60394c54eaa0d0bb46ac69174ee376aa491c7dfcc4c8c4
> Connecting to 10.144.1.10:8080... connected.
> Proxy request sent, awaiting response... 200 OK
> Length: 517 [application/json]
> Saving to: ‘STDOUT’
> 
> -                                                     0%[                                                                                                                     ]       0  --.-KB/s             {"metadata": {"expires_at": 0, "aliases": [{"description": "", "target": "ubuntu/wily/amd64/default"}, {"description": "", "target": "ubuntu/wily/amd64"}], "uploaded_at": 1446526182, "properties": {"description": "Ubuntu wily (amd64)"}, "fingerprint": "2074453abb29a317de60394c54eaa0d0bb46ac69174ee376aa491c7dfcc4c8c4", "architecture": 2, "created_at": 1446526182, "filename": "ubuntu-wily-amd64-default-20151103_03:49.tar.xz", "public": 1, "size": 77535144}, "type": "sync", "status": "Success", "status_code": 200}
> -                                                   100%[====================================================================================================================>]     517  --.-KB/s   in 0s     
> 
> 2015-11-03 10:39:46 (34.9 MB/s) - written to stdout [517/517]
> ```
> One thing to note is that I am behind a proxy and the environment vars `http_proxy` and `https_proxy` have been configured correctly (E.g. wget above works). 
> 
> Would someone know what I am missing in order to get the image copy command to work?

Looks like it was just a small oversight, as we didn't have LXD look
for a proxy. Once the branch I just sent is merged, assuming you have
the right configuration set in LXD's environment, it should work
correctly.

Thanks!
