### ISSUE TITLE
Implement "lxd init" command

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#1267]
"lxd init" is a new lxd (not lxc) subcommand which should let the user interactively:
 - Setup ZFS (if zfs is available)
   - Setup a new zpool (file backed at /var/lib/lxd/zfs.img)
   - Or offer to use an existing one (or subset of one)
 - Allow enabling network access to LXD
 - If enabling network access, set trust password

**Comment by srkunze** [comment]
Nice but why not via lxc?

**Comment by stgraber** [comment]
Because we don't want to allow such reconfiguration over the API and such configuration should happen before any client connects to the API.

**Comment by stgraber** [comment]
If misused this command will allow you to fill your disk entirely or even worse, destroy existing disk partitions, so we want to make it absolutely sure that you are root on the system in question.

**Comment by srkunze** [comment]
Sounds good. :)
