### ISSUE TITLE
lxc publish produces Image with ARCH unknown

### ISSUE THREAD

**Issue by derEremit** [lxc/lxd#1271]
created a container based on ubuntu wily amd64
lxc publish logging  --alias=rabbitELK

lxc image list shows ARCH unknown

**Comment by stgraber** [comment]
What version of LXD is that happening with?

**Comment by stgraber** [comment]
I just tried here and I'm getting an x86_64 image as expected using current git master.

**Comment by derEremit** [comment]
0.21
I tried to reproduce it 2 times
and couldn't 
closing for now

**Comment by stgraber** [comment]
Okay, let us know if you can figure out how that happened and we'll sure look into it!
