### ISSUE TITLE
How to make LXD server public?

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1281]
I couldn't find documentation how to make LXD server accessible from local network? Is there any command a local client can do?

`lxc config get core.https_address` doesn't work.

**Comment by stgraber** [comment]
lxc config set core.https_address ::

Or replace "::" by the IP you want it to bind to. ip:port combination is also supported.

    lxc config show

Can be used to see the current config.

And indeed it looks like config get needs fixing.

**Comment by techtonik** [comment]
`lxc config show` works. But I found that I also need to setup password so that remote client can connect. Right?

**Comment by techtonik** [comment]
I can connect to Ubuntu server from Windows machine. He-he. =)

**Comment by stgraber** [comment]
There are two ways you can setup a trust relationship with a LXD server, either by setting core.trust_password and then entering the password in the client or by copying the client certificate (.config/lxc/client.crt) to the server and then doing "lxc config trust add client.crt" on the server.

**Comment by techtonik** [comment]
Nice. Do you know a place where this documentation could be moved? The the answer to [How can I live migrate a container using LXD?](https://github.com/lxc/lxd#when-i-do-a-lxc-remote-add-over-https-it-asks-for-a-password) can be changed to "Remote LXD server is not configured for remote access".
