### ISSUE TITLE
Can a unprivileged container created by an user be accessed by another user of the same host?

### ISSUE THREAD

**Issue by thhgcn** [lxc/lxd#1285]
Hi,

I'm playing with LXC a while and decided to try LXD. It's really amazing and devs have been done a awesome work.

I install LXD on my laptop from official repo (I'm using Ubuntu 15.10) and configure LXD to use BTRFS backend.

I copy an image from [images.linuxcontainers.org](images.linuxcontainers.org) and create a new container. I executed some commands using `lxc exec` and all did good.

So I created another user (foo) on my laptop who isn't on any LXC/LXD related group and tried to access the container that I created with my normal user.

I tried `lxc exec c1 -- /bin/bash` with the foo user on c1 container created by my normal user and I was able to get root inside the container.

Now I have a doubt. Is this the normal behavior? Is it possible to attach to a container created by another user, even if the current user isn't member of any LXC/LXD related group?

Is this not insecure?

Thanks for your time.

**Comment by stgraber** [comment]
No, users must be in the lxd group to be able to talk to LXD.
At package install time, all members of the sudo and admin groups are automatically added to the lxd group.

Access is done through good old unix permissions, any user which can access /var/lib/lxd/unix.socket can control lxd.

The default permissions should be: root:lxd 0660

**Comment by thhgcn** [comment]
I found the problem. 

The problem is the permission for `/var/lib/lxd/unix.socket`. It was root:lxd 0666, so anyone could access it.
 
I changed the permission manually to 0660 as you said, and it worked just as expected, my foo user couldn't access the container since it isn't member of LXD group. 

But I don't know why, when I restarted the service via systemd or when the service is started after boot, the default permission is root:lxd 0666.

**Comment by hallyn** [comment]
Yikes.  Does it continue to do so whenever you restart it?

**Comment by thhgcn** [comment]
Yes. Whenever I restart it, I got the permission 0666.

**Comment by thhgcn** [comment]
I'm closing this issue because I saw no problem with `unix.socket` permission in the release 0.22.
When I got the problem, I was running the release 0.20 from official Wily repo; now I'm using the PPA version. So, whatever it was, devs fixed.

Thanks for your time and for your great work.
