### ISSUE TITLE
lxc move local1 local2 is not a live migration

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#1286]
This command simply stops the container and moves it, as opposed to doing something fancy like live migration. We used to not allow this, but it seems in relaxing that we may have an unexposed bug. If we decide not to allow local live migration, we should explicitly disallow it instead of just stopping your container.

**Comment by stgraber** [comment]
Hmm, so a rename should be possible without the container stopping and without live migration.

So:
 - "lxc move a b" just renames the DB entry and the container storage but doesn't stop the container.
 - "lxc move a other-host:" if stopped does a normal move, if running does live migration.
 - "lxc move a other-host:b" if stopped does a normal move (and rename), if running does a live migration (and rename)

When running, a rename only really applies to the LXD container name and storage directory, we don't try and mess with files inside the container or try to alter the existing utsname.

**Comment by srkunze** [comment]
> When running, a rename only really applies to the LXD container name and storage directory, we don't try and mess with files inside the container or try to alter the existing utsname.

Aren't there file template hooks that get triggered once a container is moved/renamed?

**Comment by stgraber** [comment]
Not right now. The copy hook is documented as running on move, but that's wrong and I'll update the spec to change that bit.

I believe in the original spec I had a rename hook which never got implemented, that's the hook while should be triggered when a container changes name and there wouldn't be any problem with running it even if the container is already running.

**Comment by tych0** [comment]
On Sat, Nov 07, 2015 at 08:27:28AM -0800, Stéphane Graber wrote:
> Hmm, so a rename should be possible without the container stopping and without live migration.
> 
> So:
>  - "lxc move a b" just renames the DB entry and the container storage but doesn't stop the container.

I think this might be a bad idea. If we just rename the DB entry,
we'll get confused on subsequent operations because the db name will
be different, but the abstract socket name will be the old name. We
could keep track of lastContainerName like we do lastIdMap, but I
think this is enough of a corner case that it doesn't warrant the
extra code.

>  - "lxc move a other-host:" if stopped does a normal move, if running does live migration.

This happens today correctly,

>  - "lxc move a other-host:b" if stopped does a normal move (and rename), if running does a live migration (and rename)

as does this (and we have tests for both)

**Comment by stgraber** [comment]
Yeah, after messing with that code again, I agree. We can't rename a running container.

On top of the socket path issue, we also have the problem that there are a bunch of mounts that we just can't rename while the container is running.

**Comment by srkunze** [comment]
@stgraber Not that understand it all what might go wrong. I can easily rename a running OS installed on bare metal (locally+DNS-wise). So, this seems like an (artificial?) restriction of system containers.

Especially, considering that
> >   - "lxc move a other-host:b" if stopped does a normal move (and rename), if running does a live migration (and rename)

> as does this (and we have tests for both)

what would prevent you from applying the same mechanism (live migration) for local-moving?

For me "one size fits all" is still the best approach. If live migration works for remote hosts, it also works when the remote host is called 'localhost'.

**Comment by stgraber** [comment]
Changing the hostname is a bit different from renaming the whole thing. We need to also move any bind-mounted devices, directories, ... rename the container's storage backend, generate new apparmor and seccomp profiles, ...

Local live migration would certainly work though, even if maybe a bit odd looking :)

@tych0 thoughts on doing a local dump/restore when renaming a running container?

**Comment by srkunze** [comment]
@stgraber Is d683ca0 the local live migration solution or something else? I couldn't deduce it from the commit.

**Comment by stgraber** [comment]
@srkunze yeah, it kinda is. Basically what my change does is leave it up to the server on whether to allow renaming of a running container or not.

Right now, the answer is that the server will always refuse it. But when/if we add some CRIU smarts to the server, then we can change that and the client will just work.
