### ISSUE TITLE
Permission issue with LXD after restart

### ISSUE THREAD

**Issue by nevi-me** [lxc/lxd#1287]
Using: Trusty server

I installed LXD using the guide on the Ubuntu site. Everything worked well until I restarted my host.

I can't run `lxc` commands, getting error:

```bash
$ lxc list
error: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: permission denied
```

If I try `newgrp lxd` I am asked for a password, both my password and the root password don't work. I get `crypt: invalid argument`.

Running with sudo seems to work, but that's not ideal as on my previous host I can run `lxc` commands without sudo. Anything I can do to fix the issue?

My goal is to be able to autostart lxd containers.

**Comment by stgraber** [comment]
Sounds like your user isn't in the lxd group.

**Comment by stgraber** [comment]
Note that lxd itself supports autostart, look at https://github.com/lxc/lxd/blob/master/specs/configuration.md specifically the boot.* container keys.

**Comment by nevi-me** [comment]
I've added myself into the lxd group, but still getting error. I'll restart server when things are a bit quiet and revert with an update.

**Comment by stgraber** [comment]
Unless you completely closed and reopened you user's session, you'll need to do "newgrp lxd" before running any lxc command.

**Comment by nevi-me** [comment]
Great! Working, thanks @stgraber , I can now run lxc without sudo
