### ISSUE TITLE
Access container from the network

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1292]
It looks like the only way to access container is through lxc client. How to access web server running on that container from the local network of the host?

**Comment by pcdummy** [comment]
You need to configure a [bridge](https://help.ubuntu.com/community/NetworkConnectionBridge) of ?eth0? and use that configure it for that host or the profile.

see (profile):

    lxc profile show default
    lxc profile edit default

or (host):

    lxc config show <hostname>
    lxc config edit <hostname>

**Comment by techtonik** [comment]
I don't understand what I need to change:
```
> lxc profile show default
name: default
config: {}
devices:
  eth0:
    nictype: bridged
    parent: lxcbr0
    type: nic

>lxc config show node:
config:
  core.https_address: 192.168.1.15
  core.trust_password: true
  images.remote_cache_expiry: "10"
```

**Comment by hallyn** [comment]
What pcdummy was pointing to is not lxd configuration, but host network
configuration.

See https://help.ubuntu.com/community/NetworkConnectionBridge for an example.

**Comment by techtonik** [comment]
Wiki pages contain rather low level explanation of implementation. How about some user level docs? If I understand there are 4 options for network configuration of container:

  - host-only - node is not accessible from host and network
  - host-only network - node is not accessible from host and other nodes on that host
  - nat - node is not accessible from outside, but can make outgoing requests
  - enabled - node is visible from host network as an independent machine

Every mode needs to be configured both on host and on guest, right? So what is the default mode? Also, is there a programmatic way to detect in which mode the node currently is?

**Comment by pcdummy** [comment]
- host-only - means a bridge which isn't briding a physical interface and doesn't have NAT.
- host-only network - just no network configuration or else on bridge per host maybe.
- nat - this is what lxcbr0 by default does.
- enabled a bridge which is connected to the physical interface AND the guest's interface.

On which OS are you on, may i can help you to get a bridge (something like a software switch) up and running.

**Comment by srkunze** [comment]
@techtonik I have absolutely no idea why networking worked out of the box for me after a restart (lxc/lxc#690), but have a look. Note, that `ubuntu` is a running container.

```
>>> lxc info ubuntu
Name: ubuntu
Status: Running
Init: 27564
Ips:
  eth0:	IPV4	10.0.3.143
  lo:	IPV4	127.0.0.1
  lo:	IPV6	::1
```

`10.0.3.143` seems to be the IP address of the container. I was able to install sshd or run this micro python webserver https://docs.python.org/2/library/simplehttpserver.html on port 8000. Both services worked and were available for the local network of the host.

I hope the lxc/lxd experts can tell us more here.

**Comment by techtonik** [comment]
@srkunze thank for the example. I checked info for my own `ubuntu` container and it uses the same `10.0.3.0` subnet. And because my host and other nodes in the network belong to `192.168.1.0` address space, even if node is available, I won't be able to ping it.

So, is there any other way to see that the guest is present in local net? By discovering MAC address, or forcing node to make a broadcast request and catching it on my remote client machine?

```
>lxc info py
Name: py
Status: Running
Init: 21617
Ips:
  eth0: IPV4    10.0.3.103
  lo:   IPV4    127.0.0.1
  lo:   IPV6    ::1

>ping 10.0.3.103

Pinging 10.0.3.103 with 32 bytes of data:
Request timed out.
Reply from 93.85.80.53: TTL expired in transit.
Reply from 93.85.80.53: TTL expired in transit.
Reply from 93.85.80.53: TTL expired in transit.
```

**Comment by srkunze** [comment]
@pcdummy @hallyn Some ideas?

@techtonik I guess it's bloody easy to configure your network to get what you want. But I have absolutely no idea. :/ To me, networking config is somehow cryptic.

**Comment by srkunze** [comment]
@techtonik I dug deeper into this issue because I am curious, too, on how to at least ping the container from another host (my odroid this time).

Turned out that it would be as simple as:

```
apt install bridge-utils
brctl addbr br0
brctl addif br0 eth0 lxcbr0
```

**IF** you have to connect eth0 (192.168.1.x) and lxcbr0 (10.0.3.103).
cf. https://wiki.debian.org/BridgeNetworkConnections#Manual_bridge_setup


HOWEVER, if you need to connect a wlan0 interface (like I have) with lxcbr0, you are out of luck because:

```
>>> brctl addif br0 wlan0 lxcbr0
can't add wlan0 to bridge br0: Operation not supported
```

That actually means: "you cannot link ethernet and wifi, please use cumbersome ebtables rules and hacky scripts instead": https://wiki.debian.org/BridgeNetworkConnections#Bridging_with_a_wireless_NIC

**Comment by pcdummy** [comment]
Not very nice that "brctl addif br0 eth0 lxcbr0" cause then you have two dhcp servers running in your network.

One for 192.168.1.x on eth0 and one for 10.0.3.103 on lxcbr0.

Just create a bridge and add eth0, then connect your lxd containers to it by changeing the default profile or a containers config.

**Comment by srkunze** [comment]
> Just [...]

Could you put this into some sort of cmds that newbies could simple copy'n'paste?

**Comment by pcdummy** [comment]
### On Debian like systems edit **/etc/network/interfaces**:

#### For **Host only** add **honly_br0**:

    auto honly_br0
    iface honly_br0 inet static
        address 10.167.161.1
        netmask 255.255.255.0
        bridge_fd 0
        bridge_maxwait 0
        bridge_ports none
        bridge_stp off

Then start `honly_br0`:

    $ ifup honly_br0

#### For **Bridged** (as asked here) add **br0**:

    auto br0
    iface br0 inet dhcp
        bridge_fd 0
        bridge_maxwait 0
        bridge_ports eth0
        bridge_stp on

Then start `br0`

    $ ifup br0

#### Now you need to **edit** either the **profile** or the **containers config**:

**profile**:

    lxc profile device remove default eth0 # Remove lxcbr0 eth0
    lxc profile device add default eth0 nic nictype=bridged parent=br0 # add br0 or honly_br0

**containers config**:

    lxc config device add foo_container_name eth0 nic nictype=bridged parent=br0 # add br0 or honly_br0

If you add a device to the container you will get a eth0 on lxcbr0 (from the profile) and a eth1 on br0.

**Comment by srkunze** [comment]
@pcdummy Wow. Thanks. Let's if this works.

**Comment by srkunze** [comment]
@pcdummy I forgot that this won't work for me. Is there a corresponding way for wlan?

Btw. I have my network managed by NetworkManager. So, I actually would not want to interfere with it. Is that possible somehow? Or even better setting up this whole thing via the NetworkManager?

**Comment by pcdummy** [comment]
@srkunze See [How to configure a Linux bridge with Network Manager on Ubuntu](http://ask.xmodulo.com/configure-linux-bridge-network-manager-ubuntu.html)

**Comment by srkunze** [comment]
@pcdummy Thanks. :) I found another way by using routing: configure the DHCP server of my home router. Interestingly, my Ubuntu 14.04 automatically had routing activated. So, this solution works as well.

**Comment by techtonik** [comment]
@pcdummy thanks for the help. Among these two choices:

* nat - this is what lxcbr0 by default does.
* enabled a bridge which is connected to the physical interface AND the guest's interface.

I currently have the 1st (can ping Google) and want the 2nd (want to access node from LAN). On host I already have `lxcbr0` device. If I understand it correctly, it is possible to switch it from NAT to bridge mode, right?
```
lxcbr0    Link encap:Ethernet  HWaddr fe:4f:b0:fa:3f:e2
          inet addr:10.0.3.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::f48b:86ff:fec6:6124/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:41479 errors:0 dropped:0 overruns:0 frame:0
          TX packets:70058 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2544052 (2.5 MB)  TX bytes:102560951 (102.5 MB)
```

**Comment by techtonik** [comment]
@pcdummy I edited my comment https://github.com/lxc/lxd/issues/1292#issuecomment-154977786 because it contained mistake in `host-only network definition`.

**Comment by techtonik** [comment]
I reticketed this as #1343 and #1344 with the hope to get more explanation about how it works.

**Comment by techtonik** [comment]
It also seems to me that there should be some tag wrt networking, because the stuff is non-trivial.

**Comment by srkunze** [comment]
> It also seems to me that there should be some tag wrt networking, because the stuff is non-trivial.

I agree. Might make it easier to filter for them when looking for similar issues.

**Comment by isantop** [comment]
@pcdummy 

Earlier you said:

For Bridged (as asked here) add br0:

auto eth0
iface eth0 inet manual

auto br0
iface br0 inet dhcp
    bridge_fd 0
    bridge_maxwait 0
    bridge_ports eth0
    bridge_stp on

How does this work when eth0 has (multiple) static IPs assigned?

**Comment by pcdummy** [comment]
hi,

Normaly you assign Addresses to br0 in that case, not to eth0.

Just change "iface br0 inet dhcp" to "
iface br0 inet manual
address 192.168.0.5
netmask 255.255.255.0
gateway 192.168.0.254

auto br0:1
iface br0:1 inet manual
address 192.168.1.5
netmask 255.255.255.1
"

Something like that should work.
