### ISSUE TITLE
CLI command for operations

### ISSUE THREAD

**Issue by uglide** [lxc/lxd#1299]
Currently cli client `lxc` doesn't have options to work with operations.

**Comment by stgraber** [comment]
That's because you're never supposed to directly deal with operations, what would you like the client to do with them?

**Comment by srkunze** [comment]
@uglide What are operations?

**Comment by stgraber** [comment]
Closing this as there's no plan on adding a user interface to operations. The only exception being a way to monitor them, which we added recently through the (hidden) "monitor" command.
