### ISSUE TITLE
Backup of LXD Database

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1302]
Reading this https://github.com/lxc/lxd/blob/master/specs/database.md I wonder how to make a backup?

You argue that the data wouldn't be terribly useful. However, when trying to re-create the host because of a hardware failure, then we should be able to recreate it from other sources (such as the containers backups) or get it from some type of backup.

**Comment by stgraber** [comment]
You can just backup the /var/lib/lxd/lxd.db file itself, or if you want a SQL dump of it, use "sqlite3 /var/lib/lxd/lxd.db .dump".

**Comment by srkunze** [comment]
Thanks. Not sure how much of MVCC sqlite3 supports, but I would choose the sqlite3 dump variant in order to ensure an atomic dump.

I gather that the LXD database contains data that cannot be recreated from its managed containers?

**Comment by stgraber** [comment]
Correct, nowadays it does store a good number of container settings, image settings, profiles, ... which cannot be recreated from the filesystem alone.

**Comment by stgraber** [comment]
And yeah, .dump would be preferred to ensure consistency, though a dump of the binary should work or at least be easily repairable in 99.9% of the cases.

**Comment by srkunze** [comment]
Understood. :)
