### ISSUE TITLE
lxd-unix.socket systemd file does not set mode

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1307]
I'm not sure where the lxd packages are created, hence the bugreport here.

The lxd-unix.socket systemd unit file needs 'SocketMode=0660' to prevent the socket from being world writable.

**Comment by jsimonetti** [comment]
Also see #1308 which should be combined with this fix.

**Comment by stgraber** [comment]
As mentioned in the pull request, I don't think it's LXD's job to check and enforce the right mode on inherited sockets. However this is a critical issue with the Ubuntu packaging which I'm now fixing.

Thanks!

**Comment by stgraber** [comment]
Fix uploaded to the Ubuntu archive for xenial and trusty-backports, wily security fix is being tested and will land within the hour.

Closing this issue.

Thanks!
