### ISSUE TITLE
Name or Format of ppa:ubuntu-lxc/lxd-stable Seems Incorrect

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1309]
https://linuxcontainers.org/lxd/getting-started-cli/#ubuntu-desktop-and-ubuntu-server

```
>>> sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable
Cannot add PPA: 'ppa:ubuntu-lxc/lxd-stable'.
Please check that the PPA name or format is correct.
>>> sudo add-apt-repository ppa:ubuntu-lxc/lxc-stable
Cannot add PPA: 'ppa:ubuntu-lxc/lxc-stable'.
Please check that the PPA name or format is correct.

```

**Comment by stgraber** [comment]
Works fine here, both of them on both Ubuntu 14.04 and Ubuntu 16.04.

**Comment by stgraber** [comment]
What Ubuntu version are you running and are you sure you don't have a firewall or proxy that's messing with apt-add-repository somehow?

**Comment by srkunze** [comment]
Ubuntu 14.04. You are right. At my home PC, that cmd works perfectly fine.

The proxy seems to be the issue here. Let me check again.

**Comment by srkunze** [comment]
The proxy seem to be the issue here. Does apt-add-repository not use the proxy configured in apt.conf?

Anyway, strange error message but thanks for the hint. :)
