### ISSUE TITLE
error: Can not change LVM config. Images or containers are still using LVs

### ISSUE THREAD

**Issue by sgireddy** [lxc/lxd#1311]
Requirement: Create two trusty containers each on its own disk so I could setup a 2-node mongodb replica set. My idea was to create two LVM volume groups so that each container owns its own volume group (and disks associated).

sgireddy@sbox02:/var/lib$ lxc config show
config:
  images.remote_cache_expiry: "10"
  storage.lvm_thinpool_name: thinpool1
  storage.lvm_vg_name: vgpool1
Then I was able to create a container on this new volume group.

Now I wan to switch over to my second volume group, but lxc is not letting me to do do that.

sgireddy@sbox02:/var/lib$ lxc config set storage.lvm_vg_name vgpool2
error: Can not change LVM config. Images or containers are still using LVs: [db01 ***]

Is there any alternate way to achieve what I want?

**Comment by hallyn** [comment]
I think right now the easiest way would be to run two lxd instances.  Register them in your client as remotes r1 and r2, and 'lxc start r1:mongo1; lxc start r2:mongo2'.

**Comment by stgraber** [comment]
I think I replied to this earlier today on askubuntu or stackoverflow.

My suggestion there was to use one VG or no LVM at all for the containers, then create one LV on each VG which you then mount into the right containers using a device disk entry.

**Comment by sgireddy** [comment]
Thank you.

I followed the procedure described here: http://askubuntu.com/questions/528161/how-to-make-a-hdd-device-file-dev-sdxy-available-in-lxc-container

sgireddy@sboxv1:~$ ls -l /dev/sd*
brw-rw---- 1 root disk 8,  0 Nov 29 18:46 /dev/sda
brw-rw---- 1 root disk 8,  1 Nov 29 18:46 /dev/sda1
brw-rw---- 1 root disk 8,  2 Nov 29 18:46 /dev/sda2
brw-rw---- 1 root disk 8,  5 Nov 29 18:46 /dev/sda5
brw-rw---- 1 root disk 8, 16 Nov 29 18:46 /dev/sdb
brw-rw---- 1 root disk 8, 17 Nov 29 18:46 /dev/sdb1
sgireddy@sboxv1:~$ sudo cat /var/lib/lxd/containers/db01/fstab
/dev/sdb1 mnt/sdb ext4 noatime 0 0
sgireddy@sboxv1:~$ sudo cat /var/lib/lxd/containers/db01/config
lxc.mount = /var/lib/lxd/containers/db01/fstab

But got the following error (in log) and the container won't even start:

 lxc 1448851772.747 ERROR    lxc_utils - utils.c:open_without_symlink:1575 - No such file or directory - Error examining sdb in /usr/lib/x86_64-linux-gnu/lxc/mnt/sdb
            lxc 1448851772.747 ERROR    lxc_conf - conf.c:mount_entry:1731 - No such file or directory - failed to mount '/dev/sdb1' on '/usr/lib/x86_64-linux-gnu/lxc/mnt/sdb'

Why is it looking @ x86_64-linux-gnu/lxc? Did I do anything wrong?

**Comment by stgraber** [comment]
No, the path is correct, it's the temporary LXC mountpoint.

Do both /dev/sdb1 on the host and /mnt/sdb in the container exist?

**Comment by sgireddy** [comment]
/dev/sdb1 exists on the host but the container wont event start. 
sgireddy@sboxv1:~$ lxc start db01
error: Error calling 'lxd forkstart db01 /var/lib/lxd/containers /var/log/lxd/db01/lxc.conf': err='exit status 1'
Try `lxc info --show-log db01` for more info

**Comment by stgraber** [comment]
Oh, hold on, you followed a LXC procedure with LXD, yeah, that's likely to cause you some trouble.
LXD doesn't use container config files at all, it's all DB driven.

A device entry to get /dev/sdb1 from the host mounted into /mnt of the container using LXD is:

    lxc config device add db01 mnt disk source=/dev/sdb1 path=/mnt/sdb

Though as I said before, current LXD requires /mnt/sdb to already exist in the container. I'll push a commit to change that since creating the path if missing seems reasonable.

What's the output of "lxc info --show-log db01" and "lxc config show db01"?
