### ISSUE TITLE
Multiple Instances of the Same Container

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1314]
What's the differences between images and snapshots?

My initial use-case was to create n instances of the same container (5 Apaches configured completely equally). So, I thought I could create a development container from a Ubuntu template, change it, make a snapshot and then run multiple instances of that snapshot at once.

Maybe, that's completely wrong, but I think you get the idea.

**Comment by jsimonetti** [comment]
Management of the inside of a container is entirely up to the user.
This is where tools such as CFengine, puppet and chef come into play.

**Comment by srkunze** [comment]
@jsimonetti I prefer salt for that purpose, but I see where you are coming from. Thanks. :)
