### ISSUE TITLE
Setting Up PostgreSQL Failes

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1316]
```
>>> ssh root@10.0.3.143 -a
root@ubuntu:~# pg_createcluster 9.4 main
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_PAPER = "de_DE.UTF-8",
	LC_ADDRESS = "de_DE.UTF-8",
	LC_MONETARY = "de_DE.UTF-8",
	LC_NUMERIC = "de_DE.UTF-8",
	LC_TELEPHONE = "de_DE.UTF-8",
	LC_IDENTIFICATION = "de_DE.UTF-8",
	LC_MEASUREMENT = "de_DE.UTF-8",
	LC_TIME = "de_DE.UTF-8",
	LC_NAME = "de_DE.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Error: The locale requested by the environment is invalid.
```

Is there something more I need to make sure of when installing daemons into containers?

**Comment by stgraber** [comment]
Are you doing that over lxc exec or over ssh?

The problem appears to be that you have your locale set as a mix of en_US.UTF-8 and de_DE.UTF-8 an are missing the matching language packs in your container.

Installing language-pack-en and language-pack-de should help.

**Comment by srkunze** [comment]
Over ssh. Installing fixed it `language-pack-de` when setting LC_ALL=de_DE.UTF8.

Or, by setting LC_ALL="en_US.utf8" in /etc/environment.

Why isn't working out of the box this way?

**Comment by stgraber** [comment]
SSH carries your locale by default for you, which is causing the problem there.

So it'd be working out of the box if your ssh client wasn't trying to be clever :)

**Comment by srkunze** [comment]
Damn environment variables. Thanks for the help. :)
