### ISSUE TITLE
Units mismatch for limits.memory

### ISSUE THREAD

**Issue by erikmack** [lxc/lxd#1319]
1. Note specs/configuration.md
    > limits.memory ... Size in MB of the memory allocation for the container

1. Limit container memory to 512MB
    `lxc config set genttmp limits.memory 512`
1. `lxc start genttmp` ... failure
1. `lxc info --show-log genttmp`

    > lxc 1447813188.958 DEBUG    lxc_cgmanager - cgmanager.c:cgm_setup_limits:1393 - cgroup 'memory.limit_in_bytes' set to '512'
1. `lxc config set genttmp limits.memory $((1024*1024*512))`
1. `lxc start genttmp` ... success!  And `free -m` in the container (with lxcfs) shows ~512M

So, either change MB to bytes in the doc, or convert in the code :-D

**Comment by stgraber** [comment]
Yeah, all that code is experimental at best and is planned to be entirely rewritten, see #1164

**Comment by erikmack** [comment]
I understand, thank you.

**Comment by stgraber** [comment]
@mjeanson actually fixed the documentation for now so closing this issue now.
