### ISSUE TITLE
Ability to use zfs filesystem (dataset) instead of pool

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1323]
Currently the command ```lxc config set storage.zfs_pool_name tank``` does not work, if existing filesystems are available in the pool.
It would be much usable and actually desirable, if a filesystem could be defined, like tank/lxd.

**Comment by stgraber** [comment]
How is it failing for you? I understand it could be confusing and may well fail if you somehow have paths that already exist, but it shouldn't refuse to use a pool that already has some filesystems created.

As for using a sub-section of a pool, that's already supported. Just:

    zfs create tank/lxd -o mountpoint=none
    lxc config set storage.zfs_pool_name tank/lxd

**Comment by tomposmiko** [comment]
After creating the dataset I was able to change to something else. But why is it failing, if it doesn't exist?
If it ever fails, then it should be when it's set AND doesn't exist.

**Comment by stgraber** [comment]
Agreed, we seem to be missing a check for the case where it plain doesn't exist.

We don't want LXD to create filesystems for you, so we won't be doing that, but failing at set time should definitely happen. I'll send a fix.

**Comment by tomposmiko** [comment]
Cool, thanks!
