### ISSUE TITLE
Treating Snapshots/Containers Like Images

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1328]
I knew I already asked a similar question: #1314 Outcome was: "Snapshots, Containers, Images: all the same".

However, I found `lxc copy` not exactly working like `lxc init`. From what I gather, `lxc copy` works on containers and snapshots whereas `lxc init` works on images.

Thus, when I copy a container called "ssh", call the new container "bdr" and I connect via ssh, it still greets me with "root@ssh". It seems like `lxc init` involves more magic than a simple copying.

So, I basically have two (feature?) requests:

1) Is it possible to create a clean image out of a container/snapshot? (to share it, and use `lxc init` on it)
2) Is it possible to use `lxc init` on a container/snapshot in order to create another container?

**Comment by stgraber** [comment]
It could be that we're not running all the right hooks on copy or that the image you used to create the first container didn't have the right hook to handle container rename.

1) lxc publish container-name/snapshot-name --alias image-alias
2) Nope, that's what copy is for and init really doesn't have extra logic about this except for running a different set of hooks.

**Comment by srkunze** [comment]
@stefanv That might be. I am using the Ubuntu Wily containers from linuxcontainers.

1) Thanks. :)
2) I see. Looks somewhat fragile if you ask me.

Why providing different methods for the same functionality? 
A) compression off/on (snapshot vs. image)
B) duplication (copy vs. init)
C) duplication + starting (copy --stateful vs. launch)

I think I am missing something here that would make distinguishing images and snapshots/containers sensible to me. It's just that as a newbie it confuses me more than it helps.

**Comment by srkunze** [comment]
@stgraber  That might be. I am using the Ubuntu Wily containers from linuxcontainers.

1) Thanks. :)
2) I see. Looks somewhat fragile if you ask me.

Why providing different methods for the same functionality? 
A) compression off/on (snapshot vs. image)
B) duplication (copy vs. init)
C) duplication + starting (copy --stateful vs. launch)

I think I am missing something here that would make distinguishing images and snapshots/containers sensible to me. It's just that as a newbie it confuses me more than it helps.

**Comment by srkunze** [comment]
@stgraber Can this be closed?

**Comment by srkunze** [comment]
@stgraber Can this be closed?

**Comment by stgraber** [comment]
sure

**Comment by srkunze** [comment]
Nice. All issue of mine are closed. :)

Btw. nice work on LXD, @stgraber
