### ISSUE TITLE
SSH authorized keys: Permission denied (publickey).

### ISSUE THREAD

**Issue by thhgcn** [lxc/lxd#1329]
I was trying to pass a pub key as a config value to a container using user.user-data but I got a `Permission denied (publickey).` Attaching to the container I verified that `~/.ssh/authorized_keys` was empty for both root and ubuntu users.

So I pushed the pub key to `~/.ssh/authorized_keys` using `lxc file push` for both users. Doing that, I could access the container using root user, but got a `Permission denied (publickey)` for ubuntu user again.

In the first case, nothing worked, in the second, only root works. I don't know what I'm missing here.

**Comment by tych0** [comment]
Can you post what you put in the user.user-data section?

For the second problem, sounds like you only imported the key into root's authorized_keys, not ubuntu's.

**Comment by stgraber** [comment]
Or that the file ownership/permission isn't correct.

**Comment by stgraber** [comment]
You may want to look at my example in https://github.com/lxc/lxd/issues/1289

**Comment by thhgcn** [comment]
In the second case, the problem was really an ownership problem. I didn't set the --uid flag, so the key was copied with root ownership. 

In the first case, I followed the @stgraber example in #1289 but it didn't work.

**Comment by stgraber** [comment]
What image are you using and where did you grab it from?

**Comment by thhgcn** [comment]
I used the lxd-images script and imported the ubuntu image.

**Comment by stgraber** [comment]
hmm, that should work. How long did you wait when testing with my example?

cloud-init isn't exactly fast, it can easily take 30+ seconds even on an SSD.

**Comment by thhgcn** [comment]
@stgraber 30+ seconds? Mine took 8- seconds. So I decided delete all containers and all images. I imported again an image using `lxd-images` and followed your example. This time it worked as expected. I don't know why, but it worked. Also, it took only 8 seconds to ssh into the container.
