### ISSUE TITLE
[error] Missing Dependency of LXD

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1332]
Setting up two LXD instances and trying to pulling a snapshot from the other one failed:

```
>>> lxc copy mexico:bdr local:bdr
error: Couldn't find criu binary on the source server. Is it installed in LXD's path?
```

**Comment by stgraber** [comment]
You can't copy or move a running container unless you're using CRIU.

LXD doesn't depend on CRIU because the right version of it isn't available in Ubuntu (nor upstream really) and isn't available on all architectures.

**Comment by srkunze** [comment]
> You can't copy or move a running container unless you're using CRIU.
Oh, I didn't know that. Could we add that to the error message?

> LXD doesn't depend on CRIU because the right version of it isn't available in Ubuntu (nor upstream really) and isn't available on all architectures.
If I understand correctly, it will be a long way before we get live migrations of LXD containers working out of the box.

Thanks for your help, @stgraber .
