### ISSUE TITLE
Cannot Stop Container Gently

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1336]
I've learned to stop my Ubuntu Wily containers with the --force flag. Otherwise the following will happen (reproducible on different Ubuntu 14.04 hosts):

```
>>> lxc list
+--------+---------+------+------+-----------+-----------+
|  NAME  |  STATE  | IPV4 | IPV6 | EPHEMERAL | SNAPSHOTS |
+--------+---------+------+------+-----------+-----------+
| ubuntu | RUNNING |      |      | NO        |         0 |
+--------+---------+------+------+-----------+-----------+
>>> lxc stop ubuntu
^C>>> lxc list
+--------+---------+------+------+-----------+-----------+
|  NAME  |  STATE  | IPV4 | IPV6 | EPHEMERAL | SNAPSHOTS |
+--------+---------+------+------+-----------+-----------+
| ubuntu | RUNNING |      |      | NO        |         0 |
+--------+---------+------+------+-----------+-----------+
>>> lxc stop ubuntu --force
error: exit status 254
Try `lxc info --show-log ubuntu` for more info
```

I can get you `lxc info --show-log ubuntu´, however it's quite large.

**Comment by stgraber** [comment]
That's currently expected. The first stop request is still handled by LXD even if you ctrl+c on the client side. So when you do it with --force then, both requests are running in the server and depending on luck, the first one may return first, causing the second one to fail.

**Comment by srkunze** [comment]
@stgraber Okay, I got that.

However, I get the feeling that the `lxc stop ubuntu` command never returns and run into the 30 secs timeout, then doing a --force itself. That is not really what I mean by gently.

**Comment by srkunze** [comment]
Just gave it a try and the `lxc stop ubuntu` command runs for 10 minutes now.

**Comment by stgraber** [comment]
Could you file a bug at https://launchpad.net/ubuntu/+source/lxd/+filebug ?

This is an Ubuntu/systemd issue, not a LXD one, so it's best to file it there, we'll make sure it contains enough information and will then send it over to our systemd maintainer.

The problem here is that SIGPWR doesn't always lead to shutdown.

**Comment by srkunze** [comment]
@stgraber Here, you are: https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1519499

**Comment by pgassmann** [comment]
I now use `lxc exec constainer -- reboot` and `lxc exec constainer -- shutdown -h 0`, this is more reliable than lxc stop and restart.
