### ISSUE TITLE
How to check network configuration?

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1344]
From #1292. I can query profile information with network configuration:
```
> lxc profile show default
name: default
config: {}
devices:
  eth0:
    nictype: bridged
    parent: lxcbr0
    type: nic
```

1. But how actually check that host configuration matches this profile?
2. Also, how to check in mode of lxcbr0 (NAT, full bridge, host-only, host-only network)?

**Comment by srkunze** [comment]
> 1. But how actually check that host configuration matches this profile?

What do you mean by that exactly? As far as I understand it a profile is applied to a container not the host.

> 2. Also, how to check in mode of lxcbr0 (NAT, full bridge, host-only, host-only network)?

Doesn't `nictype: bridged` tells you exactly that?

**Comment by techtonik** [comment]
>> But how actually check that host configuration matches this profile?

I mean check that guest initialized with this profile can be run on this host. That host has necessary interfaces and other prerequisites mentioned in profile.

> Do you want to see all containers with that specific profile?

That is another piece of info, but that will be useful too. All containers that match requirements specified by this profile.

>> Also, how to check in mode of lxcbr0 (NAT, full bridge, host-only, host-only network)?
> Doesn't nictype: bridged tells you exactly that?

Well, because I can not access my container from the LAN, it is NATed, not bridged. Also, it is not clear what `bridged` applies to - `eth0 on guest`, `eth0 on host` or `lxcbr0`. So what is bridged with what? It is `host lxcbr0 --> ...` bridge or `guest eth0 --> lxcbr0` bridge or both?

**Comment by srkunze** [comment]
> I mean check that guest initialized with this profile can be run on this host. That host has necessary interfaces and other prerequisites mentioned in profile.

I think a profile comprises the **virtual** devices of a guest system.

> So what is bridged with what?

I think it's the bridge created by LXD called `lxcbr0` on my host system. This bridge connects all LXC containers on my system and puts them into the 10.0.3.0/24 network.

```
>>> ip addr
4: lxcbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether fe:ed:d1:0c:20:c4 brd ff:ff:ff:ff:ff:ff
    inet 10.0.3.1/24 scope global lxcbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::88aa:10ff:fe00:a56b/64 scope link 
       valid_lft forever preferred_lft forever
6: vethIGFQD8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master lxcbr0 state UP group default qlen 1000
    link/ether fe:ed:d1:0c:20:c4 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fced:d1ff:fe0c:20c4/64 scope link 
       valid_lft forever preferred_lft forever
```

`vethIGFQD8` is the veth device that @jsimonetti mentioned. As this one provides the interface for the host system to join in (if I understand this correctly).

**Comment by jsimonetti** [comment]
This is correct. The host creates a veth (virtual ethernet) device and this veth is bridged to lxcbr0. The veth device is then handed of to the container to be used as eth0.

The host runs a dhcp daemon on lxcbr0 which hands out ips in the 10.3.0/24 range to the containers. The default gateway for containers is the 10.3.0.1 which is configured on lxcbr0.
This creates a host only network for the containers. In addition (for convenience) the host does SNAT for all traffic entering lxcbr0 destined for other Networks.

**Comment by techtonik** [comment]
I wish I could draw this as a diagram.

> In addition (for convenience) the host does SNAT for all traffic entering lxcbr0 destined for other Networks.

Which SNAT is that? https://en.wikipedia.org/wiki/Network_address_translation#SNAT Does that mean that rogue container can scan my LAN?

**Comment by jsimonetti** [comment]
Yes, the default setup allows containers access to all network resources the host can access (at network level obviously).
If you wish to restrict containers more, you need to do firewalling on the host or choose a different network setup.

And when I say SNAT, I mean this in the common unix definition of source network address translation.

**Comment by techtonik** [comment]
Hmm.. I think that then I can do it the different way - instead of messing with `sudo` and `iptables` rules on my host machine I can just run `netcat` on my local machine and ask guest to connect with forwarded port to it.

**Comment by techtonik** [comment]
No, doesn't work. There is no route/gateway between host:eth0 and lxcbr0:eth0 subnets.

**Comment by jsimonetti** [comment]
FYI, i have just updated my servers to use macvlan which is now available in master thanks to PR #1355 and it has been working wonderfully!
Gone are my bridge interfaces and the huge amount of veth interfaces.

Also, container to container network performance has increased by roughly 10%.

**Comment by srkunze** [comment]
@jsimonetti Cool, how did you benchmark this?

**Comment by jsimonetti** [comment]
No benchmark, just human observation of pre- and post-migration speed of common upload tasks (like backups, etc). So take the figure with a big grain of salt :)

**Comment by srkunze** [comment]
@techtonik Can this issue be closed? I think we summarized what's necessary in other issues.

**Comment by techtonik** [comment]
Ok. Let's close it for now. Does `macvlan` needs to be specifically enabled or it is new default?
