### ISSUE TITLE
Show PID in lxc list

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1353]
Providing more data for https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1519499 required me to determine the correct PID of a running container. I recently had a larger setup of LXD containers.

So, it would be nice to have another column which presents the PID of the container, e.g.:

```
>>> lxc list
+--------+---------+----------------------+------+-----------+-----------+-----+
|  NAME  |  STATE  |         IPV4         | IPV6 | EPHEMERAL | SNAPSHOTS | PID |
+--------+---------+----------------------+------+-----------+-----------+-----+
| bdr    | STOPPED |                      |      | NO        |         7 |     |
| ssh    | STOPPED |                      |      | NO        |         0 |     |
| test   | RUNNING | 10.0.3.157, 10.0.4.1 |      | NO        |         0 | 345 |
| ubuntu | STOPPED |                      |      | NO        |         0 |     |
+--------+---------+----------------------+------+-----------+-----------+-----+
```

**Comment by stgraber** [comment]
I wouldn't show this by default, but if we can sort out how to have optional columns, then that'd be fine.

**Comment by srkunze** [comment]
Okay, sounds good. What's you reasoning for not showing this by default?

**Comment by srkunze** [comment]
I looked into the implementation and it seems as if I could do that for you.

**Comment by stgraber** [comment]
We're already using a lot of horizontal screen space and it's very rare for a user to actually have to interact with the host's view of the container's init pid. So having it as an optional column for people for whom this is important is fine, but adding the column for everyone by default isn't.

Same goes with reporting of resource usage, we'll soon be adding reporting of memory, swap, disk, network, cpu, ... we can't show all of those all the time.

I believe the spec defines a -F argument (or similar name) that takes a comma separate list of column names to display, that'd be the right place to add such things.

**Comment by techtonik** [comment]
> Okay, sounds good. What's you reasoning for not showing this by default?

What do I need this PID for?

**Comment by srkunze** [comment]
> What do I need this PID for?

For killing the container process if LXD is broken/overloaded (lately I had this).

Or for another issue as referenced above for bug tracking and issue reporting.

**Comment by techtonik** [comment]
So there is a separate process per containers. Interesting..

**Comment by srkunze** [comment]
@techtonik Yep; actually it's a complete process tree underneath it (check `ps auxf`). That's why I'd like to see it by default to make it explicit. But I won't insist on it.

**Comment by techtonik** [comment]
Wow, I was always using `aux`, but `faux` was just what I need. =)

**Comment by srkunze** [comment]
You could use this one:

`lxc list -c p --format=csv ^CONTAINER_NAME$`

**Comment by stgraber** [comment]
```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc query /1.0/containers/snapcraft/state | jq  .pid
10953
```

**Comment by mhkabir123** [comment]
@stgraber root@kabir:~# lxc query /1.0/containers/snapcraft/state | jq .pid
No command 'lxc' found, did you mean:
 Command 'axc' from package 'afnix' (universe)
 Command 'llc' from package 'llvm' (universe)
 Command 'lc' from package 'mono-devel' (main)
 Command 'lpc' from package 'cups-bsd' (main)
 Command 'lpc' from package 'lprng' (universe)
 Command 'lpc' from package 'lpr' (universe)
lxc: command not found

**Comment by stgraber** [comment]
@mhkabir123 then you're not running LXD :)
That error says that you don't have the `lxc` command, which is the main command to interact with LXD.

**Comment by mhkabir123** [comment]
@stgraber I'm using lxc (ubuntu container). 
Below command I'm using for docker that's working fine . And now I'm looking something like below commands for my lxc container. Please help me if you can. thanks. 
#for docker commands 
r=container_name
sudo docker start $r
sudo pid=$(docker inspect -f '{{.State.Pid}}' $r)

**Comment by stgraber** [comment]
If you're using LXC instead of LXD, then you'll need to look at the lxc-info tool.

**Comment by mhkabir123** [comment]
@stgraber yes I know that. But I want to take PID from variable like docker command (mentioned above), so if I use from variable I will not need take PID manually every starting time.

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc-info --help
Usage: lxc-info --name=NAME

lxc-info display some information about a container with the identifier NAME

Options :
  -n, --name=NAME       NAME of the container
  -c, --config=KEY      show configuration variable KEY from running container
  -i, --ips             shows the IP addresses
  -p, --pid             shows the process id of the init container
  -S, --stats           shows usage stats
  -H, --no-humanize     shows stats as raw numbers, not humanized
  -s, --state           shows the state of the container
  --rcfile=FILE         Load configuration file FILE

Common options :
  -o, --logfile=FILE               Output log to FILE instead of stderr
  -l, --logpriority=LEVEL          Set log priority to LEVEL
  -q, --quiet                      Don't produce any output
  -P, --lxcpath=PATH               Use specified container path
  -?, --help                       Give this help list
      --usage                      Give a short usage message
      --version                    Print the version number

Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.

See the lxc-info man page for further information.
```

This shows that you can use `lxc-info -p -n NAME` to get only the PID.
