### ISSUE TITLE
libusb support in containers

### ISSUE THREAD

**Issue by dodoadoodoo** [lxc/lxd#1359]
I would like to be able to add host usb devices to the container and access them through libusb

**Comment by srkunze** [comment]
Not that I would have an immediate use-case for it but when I need it, it would come in quite handy. +1

**Comment by stgraber** [comment]
Unfortunately the USB kernel interface isn't container aware so proper libusb interactions won't work (and there's been a lot of pushback for getting a device namespace in the kernel, so I wouldn't expect things to change any time soon).

That being said, you can pass a specific USB device using the unix-char device type in LXD and it should work, depending on what you'll be doing with it.

```
stgraber@castiana:~$ lxc exec blah -- lsusb
unable to initialize libusb: -99

stgraber@castiana:~$ lsusb 
Bus 003 Device 002: ID 8087:8001 Intel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 04f2:b449 Chicony Electronics Co., Ltd 
Bus 001 Device 002: ID 058f:9540 Alcor Micro Corp. AU9540 Smartcard Reader
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

stgraber@castiana:~$ lxc exec blah -- mkdir -p /dev/bus/usb/001

stgraber@castiana:~$ lxc config device add blah smartcard unix-char path=/dev/bus/usb/001/002 
Device smartcard added to blah

stgraber@castiana:~$ lxc exec blah -- lsusb
Bus 003 Device 002: ID 8087:8001 Intel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 04f2:b449 Chicony Electronics Co., Ltd 
Bus 001 Device 002: ID 058f:9540 Alcor Micro Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

stgraber@castiana:~$ lxc exec blah -- pcsc_scan
PC/SC device scanner
V 1.4.22 (c) 2001-2011, Ludovic Rousseau <ludovic.rousseau@free.fr>
Compiled with PC/SC lite version: 1.8.10
Using reader plug'n play mechanism
Scanning present readers...
0: Alcor Micro AU9540 00 00

Thu Nov 26 17:56:04 2015
Reader 0: Alcor Micro AU9540 00 00
  Card state: Card removed, 
```

I'll send a branch to remove the need for that mkdir.

**Comment by theoryno3** [comment]
Thanks, this is useful on raspberry pi (and the like). +1

**Comment by srkunze** [comment]
> there's been a lot of pushback for getting a device namespace in the kernel, so I wouldn't expect things to change any time soon

What's the reason for it? It appears to be the next logical step to me considering all the other namespace technologies.

**Comment by stgraber** [comment]
Namespaces aren't very popular with kernel developers to begin with and having to tag and track them into every single device driver in addition to devtmpfs, procfs and sysfs isn't popular at all.

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/pull/1360 contains a bunch of fixes for device attach which will help you quite a bit for usb devices.

**Comment by stgraber** [comment]
With that branch merged, I'm going to close this. USB device access in containers can be done using the unix-char device type, anything better would need major kernel rework before LXD can do anything about it.
