### ISSUE TITLE
LAN Access: Port Forwarding Plan

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1363]
Reticketed from https://github.com/lxc/lxd/issues/591#issuecomment-99900927
1. Use `iptables` for adding [commented rules](https://unix.stackexchange.com/questions/245151/firewall-that-allows-to-tag-or-comment-rules-for-easy-filtering/245239#245239) when
   - [ ] container is started
2. [Remove commented rule](https://unix.stackexchange.com/questions/245366/find-my-rules-in-iptables/245372#245372) when
   - [ ] container is stopped
3. Fail with sane error message if
   - [ ] port is busy

Rule example:

```
iptables -t nat -A PREROUTING -p tcp -i eth0 -d 192.168.1.15 --dport 587 -j DNAT \
    --to-destination 10.0.3.100:587  -m comment --comment "LXC (ubuntu1) port forward"
```

Which says that all packets arriving to host (192.168.1.15) port 587 should be routed to address:port 10.0.3.100:587

So, is that possible?

**Comment by tomposmiko** [comment]
It would be better, like this:

iptables -t nat -A PREROUTING -p tcp -i eth0 -d <IP_ETH0> --dport 587 -j DNAT \
    --to-destination 10.0.3.100:587

Otherwise I had problems in the past with various providers.

**Comment by srkunze** [comment]
@techtonik Nice work on making things atomic. You might include a comment to your example to make complete.

**Comment by techtonik** [comment]
I am not sure what `-d` does, but I fixed the example.

**Comment by tomposmiko** [comment]
@techtonik 
Ssshhhh.... Sorry, github cut my comment.
The right one would be:

iptables -t nat -A PREROUTING -p tcp -i eth0 -d **ETH0_ADDRESS** --dport 587 -j DNAT \
    --to-destination 10.0.3.100:587  -m comment --comment "LXC (ubuntu1) port forward"

The basic concept is that some providers send every traffic everywhere (I don't know, why). It's not problematic, if there is no DNAT.
But if it is the case traffic can be forwarded to the machines/containers on the private network, and those instances knows nothing about this, they believe that traffic belongs to them and they will respond.

FIXME if I'm wrong.

**Comment by techtonik** [comment]
Fixed. I guess that's only the case when eth0 somehow has multiple IP addresses. Otherwise I don't see why `iptables` need additional selection rule by IP.

**Comment by aarnaud** [comment]
Hi,
I use "rinetd" on host for forward port from 127.0.0.1 and other interfaces

https://www.debian-administration.org/article/601/Easily_forwarding_arbitrary_TCP_connections_with_rinetd

**Comment by techtonik** [comment]
`rinetd` is interesting, and I also found this - https://github.com/evanhempel/lxc-portforward to setup some stuff to be automatic. I may actually be able to give both a test this weekend.

**Comment by techtonik** [comment]
`rinetd` looks nice, but it still requires SSH access to LXD server both for initial setup and for modifications. Initial setup:
```
sudo apt-get install rinetd
```
Then the algorithm:

1. [ ] get IP of running container
```
>lxc list -c4
+-------------------+
|       IPV4        |
+-------------------+
| 10.0.3.165 (eth0) |
+-------------------+
|                   |
+-------------------+
|                   |
+-------------------+
```
2. [ ] parse the output to get the IP
3. [ ] get the port that needs to be forwarded (8536 in mycase)
4. [ ] SSH to LXD server and edit `rinetd` config
```
sudo vim /etc/rinetd.conf
```
5. [ ] add rule to make 10.0.3.165:8536 accessible from LAN 192.168.1.2:8580
```
bindaddress  bindport  connectaddress  connectport
192.168.1.2  8580      10.0.3.165      8536
```

This is very inconvenient, especially because of SSH and sudo operation with manual file edit. Is there anything that could be used as user-space daemon or something that LXD can forward commands to?

**Comment by aarnaud** [comment]
Hi @techtonik,

Maybe a small daemon run as root which checks the config forward port in metadata of container configuration to edit rinetd file and restart the service is a good idea.

**Comment by techtonik** [comment]
@aarnaud there is already LXD daemon running, so maybe it is possible to patch it instead. https://github.com/evanhempel/lxc-portforward already has code for LXC, so maybe port settings from there can be moved into `lxc config edit`..

**Comment by patrakov** [comment]
FWIW, lxc-portforward doesn't handle container-to-container communication correctly. That's why I created my own workalike (for LXC only, not LXD): https://github.com/patrakov/lxc-expose-port, and it is configurable from the container configuration file.

**Comment by techtonik** [comment]
Getting back to it.. Now I think that the most convenient usage would be command/plugin to do port forwarding **through LXD** to avoid messing with host system for temporary development sessions. LXD already has a channel to the host userspace, and I don't need anything more complicated than:

    lxd teleport named_container there=localhost:2323 here=localhost:2828

I don't mind if LXD is active in background doing the forwarding and encryption. Is that feasible?

**Comment by Kentoseth** [comment]
I think we need to set out a bunch of rules to make a modular port-forwarding tool work with LXD.

The rules I can think of so far are:

- [ ] Forward port from host to container
- [ ] Only forward `if` container: exists, is started
- [ ] Check `if` container exists, if not, remove port-forwarding rule
- [ ] Make communication between containers possible

The modular library needs to handle quite a few use-cases to give LXD dockerlike port-forwarding rules.

If anybody is hosting LXD containers at scale and in production, please share/add to the rules so that we can build on all edge-cases.

**Comment by patrakov** [comment]
Some important edge cases are:

- [ ] Make sure that, if access to the forwarded port is not from the subnet dedicated to our containers, the containers can get the source IP of the connection in the usual way (port-forwarding via iptables DNAT rule satisfies this trivially, a non-transparent user-space proxy doesn't)
- [ ] Make access to the forwarded port possible from other containers
- [ ] Make access to the forwarded port possible from the container itself (i.e. self-communication over the forwarded port)
- [ ] Don't break IPv6 SLAAC while implementing the previous bullet point

Also a feature request for these use cases:

- [ ] Forward port from unspecified IP address to the container, so that it is available on any IP address of a multi-homed host
- [ ] Forward port from 127.0.0.1 to the container (i.e. so that it is accessible from the host only)
- [ ] Forward port from a specified IP or interface to the container, so that it is available only via a specific IP address of a multi-homed host

**Comment by Kentoseth** [comment]
(LXD module port-forwarding plugin)[https://gist.github.com/Kentoseth/07a8756b5e7ef798c6273a508134fd22]  - Link to gist

Do you guys prefer using C or Python3 for this plugin?

**Comment by JustinJudd** [comment]
I wrote a tool that can monitor LXD and make changes to IPTable rules as containers come up or down. [https://github.com/JustinJudd/lxd-port-forward](https://github.com/JustinJudd/lxd-port-forward)

I really love the `lxd teleport` idea to be able to make these changes on lxd remotes and not having to ssh over. In the meantime, I have added daemon and systemd support so it should be really easy to just throw onto an LXD host and add a configuration file and let it go.

**Comment by patrakov** [comment]
I have looked at the code. Unfortunately, it only inserts one iptables rule per container, which is good enough only for forwarding external connections to the container. The use cases regarding connections from other containers, or from the container itself, or from the host to the forwarded port, are not covered.

**Comment by jamesbeedy** [comment]
How about tying into openvswitch through something like https://github.com/socketplane/libovsdb 

Ovs would definitely provide a more flexible and durable host->network->container coordination. But why reinvent the wheel when there exists lxd openstack? Ahhh I think I see it now, lxd needs something equivalent to what flannel is for docker, provider agnostic network plane?

**Comment by JustinJudd** [comment]
Thanks @patrakov. I looked at the script you provided for LXC support and added OUTPUT and POSTROUTING rules that should match the rules that you are generating.

**Comment by eumel8** [comment]
Is there a way for transparent proxy mode? A lot of services in container need the real source address from outside (i.e. access-list in postfix, named, apache...). With DNAT only the LXD host address is visible as source address in LXD container.

**Comment by eumel8** [comment]
want to share my solution if you want to see the real source address in requests from outside into containter via bridge:
remove general packet masquerading in iptables nat postrouting (-A POSTROUTING -j MASQUERADE)
add new snat rule to the set:

-A POSTROUTING -s 10.176.65.0/24 -j SNAT --to-source  192.168.0.42

10.176.65.0/24 = container network
192.168.0.42 = ip alias of network interface on lxd host

services running in container are now seen the real ip-address requests from outside.

**Comment by stamster** [comment]
I'm quite surprised this core feature haven't been implemented yet. 
Really, what is the use of containers if no one is able to use them from external world? The very basic feature set over which Internet was conceived  was exactly computer connectivity at first place.

How I see this general problem - same as with other stuff working in a LAN only. Let master (LAN) DHCP server assign addresses to containers instead of using bridged interface. From there it goes as usual.

**Comment by techtonik** [comment]
@stamster I solved container access problem from LAN with `macvlan` interface. But I still consider it insecure for development setup in public spaces, so I am still looking for a solution to forward ports over secure channels. The most obvious way was to reuse LXD channel, but I don't know Go good enough to complete the code.

**Comment by ProjectInfinity** [comment]
@srkunze I can't speak for _all_ of the features discussed in here but VMware and VirtualBox sure supports forwarding ports from guest to host which is what this ticket originally discussed.

**Comment by techtonik** [comment]
@srkunze and speaking of containers, port exposure is a core feature of Docker.

**Comment by stgraber** [comment]
#2504 is our preferred implementation for such port/socket forwarding. Obviously in a production environment we still expect most people will not need to use something like that as their containers won't be connected to a host-local bridge but instead connected to their normal network and firewalling infrastructure.

**Comment by srkunze** [comment]
@stgraber I like the proposal over there in #2504. Let's see if others think so as well.

**Comment by stgraber** [comment]
Closing as proxy devices are a thing now. There will be more work to expand them and it may not be for everyone but it should take care of a lot of the current issues.

For workflow discussions, it's preferred to use our forum at https://discuss.linuxcontainers.org nowadays, using Github for clear feature requests and bugs.
