### ISSUE TITLE
LXC start fails -  Operation not permitted - error mounting proc

### ISSUE THREAD

**Issue by dmacbride** [lxc/lxd#1364]
Attempting to start LXD container fails with message:

$ lxc start wc1
error: Error calling 'lxd forkstart wc1 /var/lib/lxd/containers /var/log/lxd/wc1/lxc.conf': err='exit status 1'
Try `lxc info --show-log wc1` for more info

This is on 
Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-33-generic x86_64)

In the log:
lxc 1448848147.718 ERROR    lxc_utils - utils.c:safe_mount:1686 - Operation not permitted - Failed to mount proc onto /usr/lib/x86_64-linux-gnu/lxc/proc
lxc 1448848147.718 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:828 - Operation not permitted - error mounting proc on /usr/lib/x86_64-linux-gnu/lxc/proc flags 14
lxc 1448848147.718 ERROR    lxc_conf - conf.c:lxc_setup:3910 - failed to setup the automatic mounts for 'wc1'
lxc 1448848147.718 ERROR    lxc_start - start.c:do_start:731 - failed to setup the container
lxc 1448848147.718 ERROR    lxc_sync - sync.c:__sync_wait:51 - invalid sequence number 1. expected 2
lxc 1448848147.718 WARN     lxc_conf - conf.c:lxc_delete_network:3114 - failed to remove interface '(null)'
lxc 1448848147.718 ERROR    lxc_start - start.c:__lxc_start:1213 - failed to spawn 'wc1'
lxc 1448848147.733 INFO     lxc_conf - conf.c:run_script_argv:362 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'wc1', config section 'lxc'
lxc 1448848148.238 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_init_pid failed to receive response
lxc 1448848148.239 WARN     lxc_cgmanager - cgmanager.c:cgm_get:994 - do_cgm_get exited with error

It seems to be very similar to or the same as issue # 946.  I am opening this issue in case the issue was expected to be resolved in kernel 3.19.0-33-generic.

The problem goes away when booting with older kernel:
Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64)

**Comment by stgraber** [comment]
What version of liblxc1 do you have on this machine?

**Comment by dmacbride** [comment]
Hi.  Thanks for the quick reply. According to dpkg, liblxc1 is at version 1.1.5-0ubuntu3~ubuntu14.04.1~ppa1

**Comment by stgraber** [comment]
Just got confirmation from Seth Forshee (Canonical kernel team) that this is a recent breakage introduced in the 3.19 Ubuntu kernel. The bug will be fixed in a later kernel update, until then you can boot an older kernel or use the 4.2 backport kernel which shouldn't have that particular bug.

Closing this issue as it's not a LXD bug.

**Comment by sforshee** [comment]
FYI, here's the bug in launchpad for this issue:

https://bugs.launchpad.net/ubuntu/vivid/+source/linux/+bug/1519106

The fix has already been committed and should already be released in a few weeks.

https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/vivid/commit/?h=master-next&id=6fc0dfd68682b0e2cc7e340ae026cf5eaefd7e4c

**Comment by dmacbride** [comment]
Thanks, gents.

**Comment by princeblr** [comment]
Not sure but i am still getting this in ubuntu 16.04 , this is inside a nested container

root@c12:~# cat /etc/sub*
lxd:100000:65536
ubuntu:165536:65533
root:131069:65536
lxd:100000:65536
root:100000:65536
lxd:100000:65536
root:131069:65536
ubuntu:165536:65536
lxd:100000:65536
root:100000:65536

root@c12:~# lxc list
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| c123 | STOPPED |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+


root@c12:~# lxc launch ubuntu:16.04 c123
Creating c123
error: Failed to change ownership of: /var/lib/lxd/containers/c123/rootfs/var/lib/lxd

Logs here :

lxc 20160720093544.500 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160720093544.500 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 8
            lxc 20160720093544.546 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /var/lib/lxd/containers c123
            lxc 20160720093544.546 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 8
            lxc 20160720093544.546 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
            lxc 20160720093544.546 INFO     lxc_seccomp - seccomp.c:use_seccomp:551 - Already seccomp-confined, not loading new policy
            lxc 20160720093544.547 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 5 start' for container 'c123', config section 'lxc'
            lxc 20160720093544.547 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160720093544.547 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 8
            lxc 20160720093544.549 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/d78a9d7e97b4b375//var/lib/lxd/containers
            lxc 20160720093544.575 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
            lxc 20160720093544.575 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 131069 range 65536
            lxc 20160720093544.575 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 131069 range 65536
            lxc 20160720093544.575 DEBUG    lxc_console - console.c:lxc_console_peer_default:469 - no console peer
            lxc 20160720093544.575 INFO     lxc_start - start.c:lxc_init:488 - 'c123' is initialized
            lxc 20160720093544.576 DEBUG    lxc_start - start.c:__lxc_start:1326 - Not dropping cap_sys_boot or watching utmp
            lxc 20160720093544.576 INFO     lxc_start - start.c:resolve_clone_flags:1013 - Cloning a new user namespace
            lxc 20160720093544.578 DEBUG    lxc_conf - conf.c:instantiate_veth:2614 - instantiated veth 'vethLIN6T2/vethPXVO0J', index is '4'
            lxc 20160720093544.579 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for c123
            lxc 20160720093544.666 DEBUG    lxc_conf - conf.c:lxc_assign_network:3048 - move 'eth0' to '1134'
            lxc 20160720093544.667 NOTICE   lxc_start - start.c:do_start:777 - switching to gid/uid 0/0 in new user namespace
            lxc 20160720093544.667 DEBUG    lxc_conf - conf.c:setup_rootfs:1215 - mounted '/var/lib/lxd/containers/c123/rootfs' on '/usr/lib/x86_64-linux-gnu/lxc'
            lxc 20160720093544.667 INFO     lxc_conf - conf.c:setup_utsname:843 - 'c123' hostname has been setup
            lxc 20160720093544.682 DEBUG    lxc_conf - conf.c:setup_hw_addr:2145 - mac address '00:16:3e:67:1e:24' on 'eth0' has been setup
            lxc 20160720093544.683 DEBUG    lxc_conf - conf.c:setup_netdev:2372 - 'eth0' has been setup
            lxc 20160720093544.683 INFO     lxc_conf - conf.c:setup_network:2393 - network has been setup
            lxc 20160720093544.683 INFO     lxc_conf - conf.c:mount_autodev:1072 - Mounting container /dev
            lxc 20160720093544.683 INFO     lxc_conf - conf.c:mount_autodev:1095 - Mounted tmpfs onto /usr/lib/x86_64-linux-gnu/lxc/dev
            lxc 20160720093544.683 INFO     lxc_conf - conf.c:mount_autodev:1113 - Mounted container /dev
            lxc 20160720093544.683 ERROR    lxc_utils - utils.c:safe_mount:1692 - Operation not permitted - Failed to mount proc onto /usr/lib/x86_64-linux-gnu/lxc/proc
            lxc 20160720093544.683 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:743 - Operation not permitted - error mounting proc on /usr/lib/x86_64-linux-gnu/lxc/proc flags 14
            lxc 20160720093544.683 ERROR    lxc_conf - conf.c:lxc_setup:3721 - failed to setup the automatic mounts for 'c123'
            lxc 20160720093544.683 ERROR    lxc_start - start.c:do_start:833 - failed to setup the container
            lxc 20160720093544.683 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20160720093544.683 WARN     lxc_conf - conf.c:lxc_delete_network:2909 - failed to remove interface 4 'eth0'
            lxc 20160720093544.683 ERROR    lxc_start - start.c:__lxc_start:1353 - failed to spawn 'c123'
            lxc 20160720093544.714 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'c123', config section 'lxc'
            lxc 20160720093545.260 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 5 stop' for container 'c123', config section 'lxc'
            lxc 20160720093545.283 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160720093545.283 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160720093545.285 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 131069 range 65536
            lxc 20160720093545.285 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 131069 range 65536
            lxc 20160720093623.810 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 131069 range 65536
            lxc 20160720093623.810 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 131069 range 65536
            lxc 20160720093623.818 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 131069 range 65536
            lxc 20160720093623.818 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 131069 range 65536

Regs
Prasoon
