### ISSUE TITLE
`lxc exec` shell is not seccomp protected

### ISSUE THREAD

**Issue by martinpitt** [lxc/lxd#1370]
This is lxd on Ubuntu 15.10 on arm64. With https://github.com/hallyn/lxc/commit/c3863ddbb I can start both arm64 and armhf containers now, and they work equally well. The actual processes in the container are seccomp restricted:
```
$ lxc exec w1 grep Seccomp /proc/1/status
Seccomp:        2
```
`w1` is a wily armhf container; I checked a few other processes like D-Bus.

However, the process you launch in the container via `lxc exec` is *not* protected:
```
$ lxc exec w1 grep Seccomp /proc/self/status
Seccomp:        0
```

This is a standard Ubuntu 15.10 armhf cloud image (`lxd-images import ubuntu wily armhf --alias wily/armhf`) and no customizations of the config. Also tested with an arm64 image, same behaviour.

**Comment by martinpitt** [comment]
I confirmed that on an Ubuntu xenial amd64 host and a trusty amd64 container, same issue. So not architecture specific.

**Comment by stgraber** [comment]
We still have that problem even after my massive container rework, so I'll need to add a ton more debugging to figure out what's going on here.

**Comment by stgraber** [comment]
That's actually a liblxc bug, I just tracked it down and sent a fix for it to the upstream mailing list.

https://lists.linuxcontainers.org/pipermail/lxc-devel/2015-December/013057.html

Closing the LXD issue.
