### ISSUE TITLE
lxd client as own package

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1375]
Would you consider a pullrequest that gives client.go its own package name? This would greatly reduce the amount of dependecies for code just interested in being a lxd client.

**Comment by jsimonetti** [comment]
Meh, nvm. It does have its own package name, but its just weirdly named :)

**Comment by tych0** [comment]
On Fri, Dec 04, 2015 at 02:38:46PM -0800, Jeroen Simonetti wrote:
> Would you consider a pullrequest that gives client.go its own package name? This would greatly reduce the amount of dependecies for code just interested in being a lxd client.

Thus far we've been trying to decouple things in shared/ that aren't
really shared, and I think it would be best to continue that approach.
Is there something in particular you're seeing being imported that you
don't like?

**Comment by jsimonetti** [comment]
Its not so much about not liking, but my gut says they are unneeded purely from a lxd client perspective. These would be (imho) in random order:

github.com/mattn/go-colorable
gopkg.in/inconshreveable/log15.v2/term
github.com/gosexy/gettext
gopkg.in/inconshreveable/log15.v2/stack
gopkg.in/inconshreveable/log15.v2
github.com/lxc/lxd/i18n

**Comment by jsimonetti** [comment]
Btw, they might be entirely needed for a client implementation. I am not overly familiar with all the code and what those dependencies pull in. ;)

**Comment by jsimonetti** [comment]
Reopen for further discussion.

**Comment by tych0** [comment]
On Fri, Dec 04, 2015 at 03:23:01PM -0800, Jeroen Simonetti wrote:
> Its not so much about not liking, but my gut says they are unneeded purely from a lxd client perspective. These would be (imho) in random order:
> 
> github.com/mattn/go-colorable

I don't think you should get this, the only import we have of this is
in github.com/lxc/lxd/lxc.

> gopkg.in/inconshreveable/log15.v2/term
> gopkg.in/inconshreveable/log15.v2/stack
> gopkg.in/inconshreveable/log15.v2

We use this for logging in the shared/ package, so I'm not sure it can
go away unless we get rid of logging (or use some sort of proxy).

> github.com/gosexy/gettext
> github.com/lxc/lxd/i18n

These we use for i18n in the client. They're unavoidable if we keep
doing that, although I think stgraber said something about that going
away, but maybe that was i18n somewhere else :)

**Comment by jsimonetti** [comment]
Go-colorable is being pulled in even though i am not manually importing it.

Currently all i use are:
lxd.ConfigDir
lxd.LoadConfig
lxd.NewClient
shared.ReaderToChannel
lxd.Client
shared.ContainerExecControl

**Comment by tych0** [comment]
On Fri, Dec 04, 2015 at 03:57:06PM -0800, Jeroen Simonetti wrote:
> Go-colorable is being pulled in even though i am not manually importing it.

Oh, right. I think it's imported as part of the logging package.

**Comment by jsimonetti** [comment]
About logging, shouldnt that be done in a client package instead of a shared package? 
The shared part should only return errors and the client should form its logging and/or translated error around it.

**Comment by tych0** [comment]
On Fri, Dec 04, 2015 at 04:01:58PM -0800, Jeroen Simonetti wrote:
> About logging, shouldnt that be done in a client package instead of a shared package? 
> The shared part should only return errors and the client should form its logging and/or translated error around it.

No, surely library bits can log their own stuff as well right? Lots of
python modules use the logging library, which serves as a proxy for
various output modes. It's possible that we need to change how we do
logging there to make it disable-able, but I think simply deleting all
the logging is non-starter.

**Comment by jsimonetti** [comment]
Hmm, I kind of disagree there, but I understand what you mean.
What about using a null function as default logger function which can be replaced at use time with their own function?
This way every user of the shared library can use their own logging implementation.

What is your opinion about translated error messages in a library btw?

**Comment by jsimonetti** [comment]
I mean localized, not translated error messages.

**Comment by tych0** [comment]
On Fri, Dec 04, 2015 at 05:06:36PM -0800, Jeroen Simonetti wrote:
> Hmm, I kind of disagree there, but I understand what you mean.
> What about using a null function as default logger function which can be replaced at use time with their own function?
> This way every user of the shared library can use their own logging implementation.

Sure, you could hook something like this up if you wanted, that'd be
fine with me. As long as we still have the option (and --debug works
with both client and server as it does today) to log stuff, that's
fine with me.

> What is your opinion about translated error messages in a library btw?

I'll leave that to stgraber :)

**Comment by stgraber** [comment]
Sounds like one has been dealt with.
