### ISSUE TITLE
Update the dependencies at build time

### ISSUE THREAD

**Issue by kianmeng** [lxc/lxd#1391]
Encounter this error while building 0.24 from source. Any ideas?

Environment
````
>>> go version
go version go1.5.2 linux/amd64

>>> git branch
* (HEAD detached at lxd-0.24)
  master
````

Compiling.
````
>>> make
go get -t -v -d ./...
go get -t -v -d ./...
go install -v ./...
github.com/lxc/lxd/lxd
# github.com/lxc/lxd/lxd
lxd/container_lxc.go:2475: cc.DetachInterfaceRename undefined (type *lxc.Container has no field or method DetachInterfaceRename)
Makefile:15: recipe for target 'default' failed
make: *** [default] Error 2
````

**Comment by stgraber** [comment]
You have an older copy of go-lxc on your local system, you should update your go libraries.

Something like: go get -u -v -d ./...

**Comment by kianmeng** [comment]
Thanks. Seems to work for me. 

If I need to rebuild for any new release, the steps should be as follows?
````
>>> git pull
>>> git checkout tags/lxd-0.24
>>> go get -u -v -d ./...
>>> make
````
Should I modify Makefile target so that it will update the go libraries? For example the default target.
````
 14 default:
 15     -go get -t -u -v -d ./...
````

Please advise. Thanks.

**Comment by stgraber** [comment]
Sure, doing it with errors ignored would be fine, we need to ignore errors because in some cases (distribution builders) we're building in environments without internet access or with a read-only gopath.

**Comment by srkunze** [comment]
> Should I modify Makefile target so that it will update the go libraries?

Why not presenting a better error message?

Upgrading my go installation magically when building lxd sounds strange.

**Comment by stgraber** [comment]
Could make it a separate target.

We don't really control the error message, you'll get various Go error messages when not up to date:
 - Missing package in GOPATH
 - Mis-implemented interface
 - Missing function name
 - ...

So unless we have a rather advanced parser, it's almost impossible to know whether the problem is a locally introduced bug or if it's due to missing or out of date dependencies.

**Comment by srkunze** [comment]
> Could make it a separate target.

That could be a solution.

I am not so much familiar with the Linux build process; mostly a mere user in that regard. But isn't exactly that what `configure` is supposed to do? I just remembered that `configure` usually tells me that I would need to install/update this or that package.

**Comment by stgraber** [comment]
Yeah, unfortunately there is no such thing as autoconf (the thing behind the configure script) for Go as the Go compiler is the one pulling dependencies, not the user.
