### ISSUE TITLE
lxc edit, push and pull on stopped containers

### ISSUE THREAD

**Issue by pgassmann** [lxc/lxd#1394]
lxc edit, push and pull currently only work for running containers.

It should be possible to edit files when a container is not running. Eg. after lxc init, before starting.

```
lxc init <image> <container name>
lxc file edit newcontainer1/etc/network/interfaces
lxc start <container name>
```

**Comment by stgraber** [comment]
Actually not so easy. We need to add file pull/push to the container interface and the LXC container backend, then add some new code to forkgetfile and forkputfile to chroot into the container rootfs and pull/push the file.

**Comment by stgraber** [comment]
Done
