### ISSUE TITLE
lxc enter <container name>

### ISSUE THREAD

**Issue by pgassmann** [lxc/lxd#1395]
I would like to have a shortcut to access a container. similar to `virsh console vm`

Especially because the container name is the last argument

```
lxc enter mycontainer
lxc console mycontainer
# instead of
lxc exec mycontainer -- bash
```

**Comment by stgraber** [comment]
I don't like the idea of adding a bunch of new commands, but we can improve our aliasing mechanism to make what you want trivial to do on your own, I have sent a branch that does just that.

**Comment by pgassmann** [comment]
Wow, you're fast. Thanks!

**Comment by techtonik** [comment]
And how to actually add that alias?

**Comment by stgraber** [comment]
Edit .config/lxc/config.yml and add it to the aliases section. Adding a new "lxc alias" command to add/remote/change aliases would probably be welcome, a branch would be appreciated.

**Comment by pgassmann** [comment]
shouldn't that be below lxc config, "lxc config alias set enter = exec @ARGS@ -- bash" and "lxc config alias remove enter"

**Comment by stgraber** [comment]
I don't think so, "lxc config" is for containers and container hosts, having it also configure the local client tool seems a bit odd to me.

**Comment by techtonik** [comment]
Well, to me it is logical if `lxc config` manages local config and `lxc conf container`, `lxc conf host` is for remotes.
