### ISSUE TITLE
deny access to dmesg or use SYSLOG namespace

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1397]
Unsure if this is a LXD thing or LXC thing, but running dmesg in a container you see messages from all containers (including the host) which also include apparmor messages.

It would be nice if SYSLOG namespace is used to filter ksyslog messages belonging to the containers' namespace.

**Comment by stgraber** [comment]
There is no such thing as a syslog namespace. @hallyn worked on patches in the past but nothing ever made it to the kernel.

I did plan for blocking access to the kernel log buffer as a security flag in #1084

**Comment by jsimonetti** [comment]
AH, well one way or the other would be fine :)

**Comment by jsimonetti** [comment]
I fixed this globally by setting dmesg_restrict on the host:

echo 1 | sudo tee /proc/sys/kernel/dmesg_restrict
or
kernel.dmesg_restrict = 1 in /etc/sysctl.conf

This prevents any non-root user from using dmesg.

**Comment by jsimonetti** [comment]
As it is already planned as a security knob, let's close this.

**Comment by vince06fr** [comment]
Why this issue is closed since the problem is always alive

```
$ $ lxd --version
2.0.4
$ lxc launch ubuntu-daily:xenial
Creating unpiqued-salley
Starting unpiqued-salley
$ lxc exec unpiqued-salley dmesg
 ```
and I see messages from all containers (including the host) which also include apparmor messages.

the dmesg_restrict=1 method is the only way to fix this for the moment, thanks to jsimonetti

**Comment by stgraber** [comment]
dmesg_restrict is the way to go until we get a kernel API that lets us do it per container (which would most likely then come with a syslog namespace).

Since dmesg_restrict is a global flag, it's not reasonable for LXD itself to set it.

A branch that updates doc/production-setup.md to add a mention of it would be welcome though.
