### ISSUE TITLE
Windows LXD

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1404]
I know that sounds a bit weird given that the 'L' stands for Linux but are there any plans for the LXD server to run under Windows? Or vice versa, are there definite plans NOT to do it?

[inspired by the issue concerning the Windows client]

**Comment by jsimonetti** [comment]
Lxd is not portable to Windows as it is completely dependant on the linux kernel. 

Microsoft is working on their own container technology though and it is allready available on technet afaik.
See https://msdn.microsoft.com/en-us/virtualization/windowscontainers/

**Comment by srkunze** [comment]
@jsimonetti Thanks for your quick reply.

From what I understand is that LXD is a wrapper for LXC. So, wouldn't it be theoretically possible to wrap windowscontainer as well?

**Comment by stgraber** [comment]
It's something we've been discussing in the past and that we're keeping in mind when doing API design. We're not working on it but someone else might at some point in the future.

**Comment by srkunze** [comment]
Alright. Shall I leave this open?
