### ISSUE TITLE
"lxc copy" to remote put data on wrong directory

### ISSUE THREAD

**Issue by arsiesys** [lxc/lxd#1405]
Hello,

It seems that after a "lxc copy" to a remote server (from a stopped container) , the data are put in the wrong directory.
In my case, after migration, containers data (roofs & metadata.yaml & templates & dev) was stored in : 
/var/lib/lxd/containers/<containername>/rootfs/ instead of /var/lib/lxd/containers/<containername>/, so lxc start failed... If I move data to the parent directory, container start.

On both side, server infos are : 
LXD version : 0.24
OS : Ubuntu 14.04 Server x64
Storage /var/lib/lxd => BTRFS

Thanks for you work.

**Comment by arsiesys** [comment]
New details : 
- If I start a copy between remote A to remote B, I get the issue explained before.

- If I start a copy between remote B to remote A, I get a different issue : 
strace Rsync is hanging on 
```select(0, NULL, NULL, NULL, {0, 20000}) = 0 (Timeout)
gettimeofday({1450016176, 586359}, NULL) = 0
wait4(1182, 0x7ffd81ae57cc, WNOHANG, NULL) = 0
```
It it's probably related to https://lists.samba.org/archive/rsync/2011-August/026749.html because on the container directory (on the destination server), this time, it's the content of rootfs which is present (container os files directly).

**Comment by stgraber** [comment]
Can you try again with LXD 0.27? I seem to remember some fixes being merged around this kind of thing.

**Comment by arsiesys** [comment]
Hey stgraber, it seems to work like a charm now. Thanks :)

**Comment by stgraber** [comment]
Very good to hear, closing this issue then!
