### ISSUE TITLE
Question : Debian 8 support 

### ISSUE THREAD

**Issue by yassirh** [lxc/lxd#1414]
Is there a package for debian? if not are there instructions to build from the source?

**Comment by tych0** [comment]
On Tue, Dec 15, 2015 at 12:12:27PM -0800, Hannoun Yassir wrote:
> Is there a package for debian? if not are there instructions to build from the source?

I'm not aware of a debian package, but there are instructions for
building from source in the readme:

https://github.com/lxc/lxd#building-from-source

**Comment by yassirh** [comment]
@tych0 I did try that but it didn't work. i ran : 
```
$ add-apt-repository ppa:ubuntu-lxc/lxd-git-master
$ apt-get update
```
And i end up with the following error which is normal : 

```
Err http://ppa.launchpad.net jessie/main amd64 Packages
  404  Not Found
```

Are there any other alternatives for debian?

**Comment by tych0** [comment]
On Wed, Dec 16, 2015 at 09:54:04AM -0800, Hannoun Yassir wrote:
> @tych0 I did try that but it didn't work. i ran : 
> ```
> $ add-apt-repository ppa:ubuntu-lxc/lxd-git-master
> $ apt-get update
> ```
> And i end up with the following error which is normal : 
> 
> ```
> Err http://ppa.launchpad.net jessie/main amd64 Packages
>   404  Not Found
> ```
> 
> Are there any other alternatives for debian?

Right, that's a PPA provided for convenience for ubuntu users. You
*might* be able to s/jessie\/main/xenial/g and get it to work, but I
wouldn't bet on it.

Instead, you should install the versions of the stuff required (i.e.
liblxc >= 1.1, golang >= 1.3) using the debian packages for those, and
build from source as described. Most of the package names will
hopefully be the same, so you can just copy and paste the apt-get
commands.

**Comment by yassirh** [comment]
Thank you for the response. I did try to install the required packages but i couldn't find lxc-dev in the "stable channel". So my questions is why is this package required?

**Comment by tych0** [comment]
On Thu, Dec 17, 2015 at 04:38:36AM -0800, Hannoun Yassir wrote:
> Thank you for the response. I did try to install the required packages but i couldn't find lxc-dev in the "stable channel". So my questions is why is this package required?  

lxc-dev are the headers for liblxc, which we need to build go-lxc, the
binding lxd uses to manipulate containers.

It's likely the package is called something else on debian, although
I'm not sure what.

**Comment by NathOC** [comment]
@yassirh you should be able to install lxd on debian, but be prepare to run into some problems, mainly kernel related (cgroup or other stuff). I've tried myself to run lxd on debian jessie but i drop that idea and now i'm on ubuntu 15.10 wily and it's much more easy... 
You could start by reading this:
https://lists.linuxcontainers.org/pipermail/lxc-users/2015-June/009575.html

**Comment by stgraber** [comment]
LXD upstream isn't doing packaging, we just push out upstream tarballs.

It so happens that I'm also the maintainer for container related packages in Ubuntu, but that's more of an accident than anything else :)

From an upstream point of view, we're very happy to help distribution packagers and maintainers in any way we can to simplify their job (merge patches, look into using alternative dependencies, ...), however we will not do the packaging work ourselves.

As a result, I'm closing this bug report.

**Comment by yassirh** [comment]
@stgraber Is there any chance we get a build from the source instructions for debian?

**Comment by stgraber** [comment]
Yep, following the README on recent Debian (golang 1.4 or higher) should work fine.
