### ISSUE TITLE
LXC Publish - error: UNIQUE constraint failed: images.fingerprint

### ISSUE THREAD

**Issue by bitnumus** [lxc/lxd#1428]
Documentation seems to be pretty non existent so excuse me if i did something wrong.

I was trying to make an image of a container, so i stopped my container and used "lxc publish" without --public flag. Now, i was given a fingerprint, and thats it. I can't find anywhere where the compressed images was supposed to go, no docs and no google results.

I then tried to create the image again today to see if the fingerprint meant anything and received this error:

command - lxc publish ubuntu
response - "error: UNIQUE constraint failed: images.fingerprint"

then i tried:

command - lxc publish ubuntu-2
repsonse - error: sql: no rows in result set

Now, i found this project when getting frustrated at docker not doing what i feel its marketed to do, and i know its early days for this project, but the docs really seem to be lacking, so any help on private publishing or image making would be really appreciated.

**Comment by stgraber** [comment]
That's most likely a DB issue I've noticed a few days back and that will be fixed in 0.25.

**Comment by bitnumus** [comment]
Ok great. Could you point me in the right direction for local published images and their locations?

**Comment by stgraber** [comment]
"lxc image list" will show you a list of your images.
"lxc image export" will let you export the tarball.

The tarballs themselves are stored in /var/lib/lxd/images/

**Comment by bitnumus** [comment]
Thanks i'll give that a go. Whats the difference between this and "publish", i've not even seen the way you describe mentioned!

**Comment by stgraber** [comment]
You still need to publish. The steps I told you are to extract the generated image from the built-in store into a tarball.

**Comment by bitnumus** [comment]
ah i see, so "lxc publish", then "lxc image export" will produce a tarball that can be moved to another machine, and "lxc image import" will run just fine.

You need some docs!
