### ISSUE TITLE
Can't stop container

### ISSUE THREAD

**Issue by aarnaud** [lxc/lxd#1430]
Hi, 

On ubuntu 14.04 with linux kernel 3.13.0

```bash
lxc launch images:debian/jessie/amd64 jessie
sleep 60
lxc stop jessie  # this command is blocked
```

**Comment by stgraber** [comment]
That's not a LXD issue, it's just that this particular container doesn't seem to shut down when receiving SIGPWR.

You may want to pass --force instead.

**Comment by Lillecarl** [comment]
I can't shut down my container from within it either, 

```
root@nginx:~# reboot
Warning! D-Bus connection terminated.
Failed to wait for response: Connection reset by peer
Failed to open /dev/initctl: No such device or address
Failed to talk to init daemon.
```


this is with ubuntu/xenial image and pretty much no custom stuff.
