### ISSUE TITLE
Container launch time

### ISSUE THREAD

**Issue by mayanklahiri** [lxc/lxd#1434]
On my workstation, `lxc launch ubuntu` consistently takes the following:

    real	0m11.094s
    user	0m0.008s
    sys	0m0.004s

The equivalent operation is roughly `docker run`, which takes:

    real	0m0.270s
    user	0m0.016s
    sys	0m0.004s

Are there any plans to decrease container startup time in the future?

**Comment by stgraber** [comment]
That's because you're creating a new container from scratch by unpacking a massive tarball.

If you were using btrfs, zfs or LVM, creation + startup time would be less than a second.

See https://linuxcontainers.org/lxd/try-it for an example of a well configured LXD (btrfs backend in this case).

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/blob/master/specs/storage-backends.md has some more details.

**Comment by mayanklahiri** [comment]
Perhaps it would be good to mention using btrfs in the Getting Started guide for significantly better performance (more than an order of magnitude). It would certainly help those familiar with Docker, where the filesystem layering happens transparently.

**Comment by stgraber** [comment]
Done
