### ISSUE TITLE
caution with upgrading to 0.25

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1435]
When upgrading lxd 0.24 to 0.25 interface ordering inside the container got scrambled.
This caused ip addresses for eth0 and eth1 to be swapped.

I'm not sure if this is a result of some code changes or something else, but I wanted to give the headsup.

**Comment by jsimonetti** [comment]
actually, the interface names inside the container where swapped
where previously interface with mac X was named eth0, it is now named eth1
and where interface with mac Y was previously named eth1, it is now named eth0.

**Comment by stgraber** [comment]
Oh, that's odd. I'm assuming those were interfaces that didn't have a fixed name in the configuration?

**Comment by jsimonetti** [comment]
Thats the weird part. They where named eth0 and eth1 in the attached profile. I dont have time anymore today to upgrade the other servers so i will do that tomorrow. I will update when I know more.

**Comment by stgraber** [comment]
The device name in the config isn't guaranteed to be the device name in the container, you need to set the "name" property for that (yeah, kinda confusing).

```
devices:
  eth10:
    type: nic
    nictype: macvlan
    parent: eth0
```

Will use the next available ethX, this used to be racy (depending on parsing at startup), it's now not racy by having it stored in a volatile key, shuffling stuff around may clear the volatile key though in which case, the next one will be allocated again.

To guarantee the name, you can do:

```
devices:
  eth10:
    type: nic
    nictype: macvlan
    parent: eth0
    name: eth2
```

Which will guarantee the device is called "eth2".

I've voluntarily used confusing device entry names in my examples to hopefully clarify that those do not influence the resulting container config in any way.

**Comment by jsimonetti** [comment]
your last post is exactly what happened...
in my profile i did not have the name configured for the device... I had 2 extra containers on a not-upgraded server where i changed the profile for one of the containers to add the name attribute.
This container functioned fine after the upgrade, the other container had it's interfaces swapped.

this is indeed a bit confusing but understandable as the device eth10 is just an identifier to the device configuration and not so much the actual interface... :)

I added the name to the profile and now it is working as before the upgrade

I think many more people will make this same mistake, so it might be wise to add the name parameter to the default profiles aswell, so at least people will copy/paste the correct stuff.
This should not matter in single nic containers, but will play a role in multi nic containers.

**Comment by stgraber** [comment]
Going to track this in #1491.
