### ISSUE TITLE
lxc edit file inconsistent results

### ISSUE THREAD

**Issue by Debianer** [lxc/lxd#1438]
I edited config files and got inconsistent results.

Host ist wily with the lxd with the Ubuntu Containers Team ppa. Guests were this happened are Debian and CentOS. Sometimes edits don't execute. I also had at least one very strange result where the last couple lines in a config file appeared twice.

Unfortunately I wasn't able to reproduce the issue consistently and do not have log entries. Feel free to close this one for now. I will add more details, if I encounter this issue again. 

I just wanted to mention this as a warning to others. For some simple server work I wanted to forgo the installation of an editor and simply use lxc edit file. That could be a bad idea. If anyone wants to use lxc file edit, they should always double check if the changes went through.

**Comment by tych0** [comment]
What do you mean by "sometimes edits don't execute"? You mean you can run the command, edit the file, and then the resulting config is not applied?

**Comment by Debianer** [comment]
Yes, I edited a file and wrote the results to disk. Next time I opened it, I discovered that the changes were not committed. This happened a couple times. But I currently can't reproduce it on purpose. Though it did happen in more than one guest on more than one occasion. The day before yesterday I was able to reproduce it a couple times in a row. But I was in a hurry, so I just installed an editor and finished what I was doing. I can't find the timestamps for the log entries in the lxd logs, so I wasn't even able to pinpoint the appropriate logs and take a look later on.

**Comment by tych0** [comment]
On Wed, Dec 23, 2015 at 11:53:39AM -0800, Debianer wrote:
> Yes, I edited a file and wrote the results to disk. Next time I opened it, I discovered that the changes were not committed.

Sorry, just to be clear, this is with `lxc file edit`? Can you post an
example sequence of commands that you ran and what didn't work?

Just looking through the file put code, it's not obvious how this
would happen without some sort of error being raised; did `lxc`
exit(1) or something?

**Comment by Debianer** [comment]
Then close it. I am sorry I currently don't have more information. I used lxc file edit guest/path/to/file Then :wq and then opened the same file again. The changes weren't committed. 

I will comment if I come across this again, though for now, I think I will stick with an editor on the guest.

**Comment by tych0** [comment]
On Fri, Dec 25, 2015 at 03:08:27PM -0800, Debianer wrote:
> Then close it. I am sorry I currently don't have more information. I used lxc file edit guest/path/to/file Then :wq and then opened the same file again. The changes weren't committed. 
> 
> I will comment if I come across this again, though for now, I think I will stick with an editor on the guest.

Well, it's worth investigation at least :). I'm on holiday now for a
bit, but I'll leave this open until I get back and can try and
reproduce myself.

Thanks!

**Comment by Debianer** [comment]
I am pretty sure this only happened to me with Debian 8 guests. I used lxc file edit, because Debian 8 doesn't come with an editor. The Centos images come with vi preinstalled. I had to edit /etc/network/interfaces before being able to connect to the internet. I think that is also the file I first noticed this problem on. Though not with the changes not being committed, but even worse. The file got mangled. Lines moved around.

There is some other things I can't explain. Probabely unrelated, but in lieu of other information:

Cron spams my log with this every minute:
CRON[1550]: (root) CMD (/usr/local/rtm/bin/rtm 13 > /dev/null 2> /dev/null)

Also I had a whole bunch of error messages about lxc not being able to delete certain files when removing said guests. I only found out about those messages later on and didn't even save them. They are gone now, because I don't have persistent logs turned on. I am going to close this for now and will reopen, when I have more information and log entries.

**Comment by Debianer** [comment]
I encountered the problem again. I forgot to ask last time what logs you would like to see.

Host: AMD64 Wily current with lxd stable repo 
Guest: Debian Jessie, image pulled yesterday
Both upgraded to latest.

Very little deviation from standard, fresh install. Guest directly attached to Host bridge br0 for direct internet access.

lxc profile show jessie

name: jessie
config: {}
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic


What I do:

lxc file edit jessie/etc/network/interfaces

dd to remove line
line is gone
:wq

lxc file edit jessie/etc/network/interfaces

line is back

Rinse, repeat n times. 

What I did before this happened: I set up the container and networking. Then I rebooted the host at some point. So I had to shut down the guest with the force command. Then I started the container, logged in via lxc exec jessie /bin/bash and started installing packages (mysql, postfix, etc.). When using "exit" after this, it didn't drop me back to the host. That console just hangs. After shutting down the guest (lxc stop jessie --force) from a different console, I got the hanging console back. It dropped me to the host with this message:

60122 22:32:55 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended

I rebooted guest and host and get the same result consistently. When writing on the deleted line, I get garbled results. Part of the old deleted line appears below.

Nothing in /var/log/lxd/jessie/lxc.log

Corresponding /var/log/lxd/lxd.log pasted below:

t=2016-01-22T23:18:30+0100 lvl=info msg=handling method=POST url="/1.0/containers/jessie/files?path=etc%2Fnetwork%2Finterfaces" ip=@
t=2016-01-22T23:22:40+0100 lvl=info msg=handling method=GET url=/1.0/profiles/jessie ip=@
t=2016-01-22T23:24:40+0100 lvl=info msg=handling ip=@ method=GET url="/1.0/containers/jessie/files?path=etc%2Fnetwork%2Finterfaces"
t=2016-01-22T23:24:44+0100 lvl=info msg=handling method=POST url="/1.0/containers/jessie/files?path=etc%2Fnetwork%2Finterfaces" ip=@
t=2016-01-22T23:24:46+0100 lvl=info msg=handling method=GET url="/1.0/containers/jessie/files?path=etc%2Fnetwork%2Finterfaces" ip=@
t=2016-01-22T23:24:56+0100 lvl=info msg=handling method=POST url="/1.0/containers/jessie/files?path=etc%2Fnetwork%2Finterfaces" ip=@
t=2016-01-22T23:26:04+0100 lvl=info msg=handling url="/1.0/containers/jessie/files?path=etc%2Fnetwork%2Finterfaces" ip=@ method=GET
t=2016-01-22T23:26:09+0100 lvl=info msg=handling method=POST url="/1.0/containers/jessie/files?path=etc%2Fnetwork%2Finterfaces" ip=@
t=2016-01-22T23:27:42+0100 lvl=info msg=handling url="/1.0/containers/jessie/files?path=etc%2Fnetwork%2Finterfaces" ip=@ method=GET
t=2016-01-22T23:27:46+0100 lvl=info msg=handling url="/1.0/containers/jessie/files?path=etc%2Fnetwork%2Finterfaces" ip=@ method=POST

**Comment by stgraber** [comment]
I'm seeing the issue here, looks like the problem is related to pushing a file which is shorter than the existing one, we're missing a truncate call somewhere.
