### ISSUE TITLE
Avahi on trusty LXD container does not publish services, but does in xenial

### ISSUE THREAD

**Issue by earnubs** [lxc/lxd#1440]
Avahi on a trusty LXD container does not publish hostname or any service, `avahi-browse -at` returns empty, but avahi on a xenial LXD container works fine, as does avahi on a LXC trusty container.

Same result if the container is from lxd-images or lxd remote, avahi runs with no obvious errors but does not publish hostname (`avahi-browse -at` returns empty).

Steps to reproduce:

```
$ lxc remote add images images.linuxcontainers.org
$ lxc launch images:ubuntu/trusty/amd64 trusty
$ lxc exec trusty -- apt-get install avahi-daemon avahi-utils
$ lxc restart trusty
$ lxc exec trusty -- avahi-browse -at
```

**Comment by vilagithub** [comment]
Same here (from a xenial host), but it works for a xenial image from the same xenial host.

**Comment by stgraber** [comment]
That'd be an avahi bug. IIRC avahi used to try to do something which would exceed normal ulimits, I'm assuming the code was fixed upstream at some point.

I'd recommend you file an Ubuntu bug against avahi to have whatever fix was pushed in newer releases backported to trusty.

**Comment by vilagithub** [comment]
hmm, weird, if you referring to the rlimit-nproc=3 in /etc/avahi/avahi-daemon.conf, I've been carrying commenting the line out for years as I ran into the issue with *lxc* containers but trying again recently, leaving the line active, it seems to be useless now.

The issue doesn't occur when using *lxc* containers so if the bug is in avahi it's only triggered with *lxd* containers... not sure how to dig from that though.

**Comment by vilagithub** [comment]
So there is a difference in /var/log/syslog when avahi-daemon starts.

Working lxc container:

Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: Found user 'avahi' (UID 106) and group 'avahi' (GID 111).
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: Successfully dropped root privileges.
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: avahi-daemon 0.6.31 starting up.
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: Successfully called chroot().
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: Successfully dropped remaining capabilities.
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: No service file found in /etc/avahi/services.
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: Joining mDNS multicast group on interface eth0.IPv6 with address fe80::216:3eff:fe7e:ad07.
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: New relevant interface eth0.IPv6 for mDNS.
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.0.130.
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: New relevant interface eth0.IPv4 for mDNS.
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: Network interface enumeration completed.
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: Registering new address record for fe80::216:3eff:fe7e:ad07 on eth0.*.
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: Registering new address record for 192.168.0.130 on eth0.IPv4.
Jan  6 12:30:51 sca-trusty-codetree avahi-daemon[2110]: Registering HINFO record with values 'X86_64'/'LINUX'.
Jan  6 12:30:52 sca-trusty-codetree avahi-daemon[2110]: Server startup complete. Host name is sca-trusty-codetree.local. Local service cookie is 2288056058.


Non-working lxd container:

Jan  6 11:26:15 trusty avahi-daemon[2988]: Found user 'avahi' (UID 106) and group 'avahi' (GID 111).
Jan  6 11:26:15 trusty avahi-daemon[2988]: Successfully dropped root privileges.
Jan  6 11:26:15 trusty avahi-daemon[2988]: avahi-daemon 0.6.31 starting up.
Jan  6 11:26:15 trusty avahi-daemon[2988]: Successfully called chroot().
Jan  6 11:26:15 trusty avahi-daemon[2988]: Successfully dropped remaining capabilities.
Jan  6 11:26:15 trusty avahi-daemon[2988]: No service file found in /etc/avahi/services.
Jan  6 11:26:15 trusty avahi-daemon[2988]: Registering HINFO record with values 'X86_64'/'LINUX'.
Jan  6 11:26:15 trusty avahi-daemon[2988]: Server startup complete. Host name is trusty.local. Local service cookie is 2572201958.

Could it be that "Network interface enumeration" (whatever that means) is not allowed ?

**Comment by stgraber** [comment]
Did you compare lxd to unprivileged lxc containers or to privileged lxc containers?

I expect this behavior from avahi to only occur with unprivileged containers which are the default for lxd but not for lxc.

**Comment by vilagithub** [comment]
unprivileged indeed !

I should have thought about checking that.

Any idea about allowing what avahi needs for unprivileged containers or is this hopeless ?

Hmm, I suspect a better understanding about that need is required to reply ;)

Is there a place I can look to find what that need is ? Some *other* log file ?

**Comment by vilagithub** [comment]
In case the above wasn't clear: avahi works with an lxc container created with lxc-create (privileged by default IIIUC) but doesn't with an unprivileged container (lxd default which I prefer to use as much as possible).

**Comment by stgraber** [comment]
From what I remember, it's avahi attempting to set a much higher than normal ulimit, only real root can do that and the kernel will prevent anyone else from attempting to do so.

So that means there's nothing LXC or LXD can really do about it, the right fix is to have avahi cope with not being real root and move on (which it appears is what they've done in recent releases).

**Comment by stgraber** [comment]
As for finding what avahi is doing, running it under strace should do the trick, assuming it exits reasonably quickly after failure.

**Comment by vilagithub** [comment]
Thanks for confirming, I was realizing that indeed avahi did fix something since it works in xenial.
