### ISSUE TITLE
Could not lxc-import anything

### ISSUE THREAD

**Issue by maniaque** [lxc/lxd#1441]
Clean Ubuntu 15.10. PPA added
`deb http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu wily main`

lxd = 0.24-0ubuntu4~ubuntu15.10.1~ppa1
lxc = 1.1.5-0ubuntu3~ubuntu15.10.1~ppa1 amd64

Added images.linuxcontainers.org as images source:
`lxc remote add images images.linuxcontainers.org`

Trying to import 

`lxd-images import busybox --alias busybox`
`error: 'NoneType' object is not subscriptable`

Same for Ubuntu. What could be wrong?

**Comment by maniaque** [comment]
Clean Ubuntu 15.10. No PPA added, just installed lxd.

`sudo lxd-images import ubuntu --alias ubuntu`
`Downloading the GPG key for http://cloud-images.ubuntu.com`
`Validating the GPG signature of /tmp/tmp9p9sckfe/download.json.asc`
`Downloading the image.`
`Image manifest: http://cloud-images.ubuntu.com/server/releases/trusty/release-20151218/ubuntu-14.04-server-cloudimg-amd64.manifest`
`error: Failed to upload the image: 500`

**Comment by hallyn** [comment]
Could you try doing a 'lxd waitready && lxd-images import ubuntu --alias ubuntu' ?

My guess is that lxd is still coming up (socket activated), and lxd-images needs to be taught to wait.

**Comment by maniaque** [comment]
Will try in a minute. Digging through syslog gave me this:

`Dec 24 01:37:43 ubuntu lxd[5413]: t=2015-12-24T01:37:43+0300 lvl=eror msg=LVMCreateThinLV driver=storage/lvm err="Could not create thin LV named 7bbb039b3eac895bbef9b3e90a637f95e15869957362a38792189372bf721e07"`
`Dec 24 01:37:43 ubuntu systemd-udevd[26471]: Process 'watershed sh -c '/sbin/lvm vgscan; /sbin/lvm vgchange -a y'' failed with exit code 5.`

**Comment by maniaque** [comment]
On clean 15.10 without PPA I get `error: Unknown arguments`

Should I use PPA version?

**Comment by hallyn** [comment]
On Wed, Dec 23, 2015 at 02:40:33PM -0800, maniaque wrote:
> Will try in a minute. Digging through syslog gave me this:
> 
> `Dec 24 01:37:43 ubuntu lxd[5413]: t=2015-12-24T01:37:43+0300 lvl=eror msg=LVMCreateThinLV driver=storage/lvm err="Could not create thin LV named 7bbb039b3eac895bbef9b3e90a637f95e15869957362a38792189372bf721e07"`
> `Dec 24 01:37:43 ubuntu systemd-udevd[26471]: Process 'watershed sh -c '/sbin/lvm vgscan; /sbin/lvm vgchange -a y'' failed with exit code 5.`

Oh, you didn't mention that you had set up lxc to use lvm.  (If you didn't set it up then something is very wrong)

**Comment by maniaque** [comment]
Sorry, my bad. Yes, I use LVM, set it up like this:

`lxc config set storage.lvm_vg_name lxc`

`sudo lvs`
`  VG   #PV #LV #SN Attr   VSize  VFree`
`  lxc    1   1   0 wz--n- 32.00g    0`

**Comment by maniaque** [comment]
Everything works. Just forgot to use `sudo lxd init`
