### ISSUE TITLE
LXD needs to be able to set veth.pair name for nova compute driver

### ISSUE THREAD

**Issue by bkuschel** [lxc/lxd#1444]
I patched the nova-lxd openstack compute driver to be able to handle linux_bridge vxlan networks. In order to do this nova compute passes the name of the tap device that should be created to the driver. This tap device needs to be prefixed with tap* in order for the bridge agent to pick up the interface and know that the vif port is plugged allowing neutron to notify nova that the network is setup up.
I passed the name to LXD using the devices structure as follows:
  
config:
  ...                  
  volatile.tap9f815aef-23.name: eth0
devices:
  tap9f815aef-23:
    hwaddr: fa:16:3e:0e:b8:2e
    nictype: bridged
    parent: brqf781634d-6e
    type: nic

I then added this to the container_lxc.go file in order to rename the veth pair device:

                       if shared.StringInSlice(m["nictype"], []string{"bridged"}) {
                                err = lxcSetConfigItem(cc, "lxc.network.veth.pair", k)
                                if err != nil {
                                        return err
                                }
                        }
Perhaps there is a better way of doing this but as it stands, the veth.pair name needs to be passed otherwise instance creation in compute will not complete properly

**Comment by stgraber** [comment]
Using the device name seems like a bad idea as it will trivially conflict if used within a profile.

But having an appropriately named property available for when a veth pair is generated (bridged and p2p mode) would be fine I think. We obviously don't want to hardcode a name by default as the kernel is way better than we are at preventing clashes, but having an optional property for it would be fine.

**Comment by bkuschel** [comment]
Maybe something like:

config:
...

volatile.something.name: eth0
devices:
something:
hwaddr: fa:16:3e:0e:b8:2e
nictype: bridged
parent: brqf781634d-6e
type: nic
veth.pair: tap9f815aef-23 (optional, otherwise generated)

**Comment by stgraber** [comment]
would probably go with something like name_host as property name, but yeah.

**Comment by stgraber** [comment]
That has now been implemented, closing.
