### ISSUE TITLE
firewall in guest

### ISSUE THREAD

**Issue by Debianer** [lxc/lxd#1451]
Instead of lxcbr0 I attached the lxd containers directly to br0 and assigned them public ip addresses. To protect them, a firewall would be nice. firewalld in a CentOS 7 container works, if I do

 lxc config set centos  'security.privileged' true

I didn't find anything on firewalls running in guests, so I would like to know if this feature is supported or just an accident. If it stops working, will it be treated as a regression? Is this being tested? Do you have suggestions for Debian or Ubuntu guests?

**Comment by stgraber** [comment]
netfilter is namespace aware, so iptables, ebtables, ip6tables, ... all work properly inside containers.

The one thing to remember though is that a container cannot trigger a kernel module load, so if you need access to a particular filtering table and the matching kernel module isn't loaded, iptables will fail.

In such case, make sure you load the relevant kernel modules on the host at startup time before starting your container.

**Comment by stgraber** [comment]
closing this issue as there doesn't appear to actually be anything to fix :)
