### ISSUE TITLE
[Testsuite] Is testing commits necessary?

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1454]
When running the testsuite, it complains about missing committed files. Is that really necessary?

I run the testsuite in order to determine whether I can commit or I'd better go back to the IDE.

**Comment by stgraber** [comment]
Hmm, I don't recall seeing this behavior before, can you paste a log?

The testsuite in the sign-off test (I think), does print some git status information, but I don't believe this causes failures, in fact, I quite regularly run the testsuite with uncommitted changes.

**Comment by srkunze** [comment]
Hmm, cannot reproduce right now. Closing.
