### ISSUE TITLE
[Testsuite] Internet Connectivity necessary?

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1455]
I was offline when I was fixing up my pull request. Turned out the testsuite needs Internet connectivity. That seems odd to me.

**Comment by stgraber** [comment]
There is an environment variable you can set to skip those tests.
It's currently LXD_DRADOCNIAN_PROXY=1 but I sent a branch yesterday that changes it to LXD_OFFLINE=1 and adds it to a new README to make it easier to find.
