### ISSUE TITLE
lxc move fails

### ISSUE THREAD

**Issue by robertfoss** [lxc/lxd#1456]
$ lxc move ubt lxd2:ubt
    error: json: cannot unmarshal string into Go value of type shared.jmap

I realize that this error message isn't all that helpful for debugging, but please ask me to provide any additional information that would make this easier for you.

**Comment by stgraber** [comment]
can you confirm both the source and target lxds are running the same version?

We did fix a few REST API mis-implementations around that code recently and the error you're getting would be consistent with your client being on an older version than the server.

lxd --version and lxc version on both machines would be useful.

**Comment by robertfoss** [comment]
I was running 0.25 and 0.20.

Thanks for catching my error.

**Comment by stgraber** [comment]
Good to hear that was the issue.

Note that this kind of thing should only happen until we finally mark our REST API as stable, after that, we should have backward compatibility to take care of version differences like that.
