### ISSUE TITLE
Implement network limits

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#1461]
This is to track the implementation of network limits (per-interface Mbps limits).

**Comment by stgraber** [comment]
Sorry about that, clicked on the wrong name when assigning :)

**Comment by benaryorg** [comment]
And I wondered why I got mail.…

Well, no problem.


And just to contribute: Will you make Mbit/s limits only integers or also floating point? Or will you support suffixes?

**Comment by stgraber** [comment]
Like the other limits, it's going to be treated internally as a number of bits with most suffixes supported (kb, Mb, Gb, Tb, Pb, Eb)
