### ISSUE TITLE
Implement native simplestream client

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#1462]
This includes a few pieces of work:
 - The command line client should come with two hardcoded (can't be removed, changed or renamed) remotes:
    - local (unix://)
    - ubuntu (https://cloud-images.ubuntu.com/releases/streams/v1/)
 - We should write a minimal simplestream client (may replace by JuJu's once easier to integrate), put it in shared/ and use it for image operations in the client and daemon.

**Comment by techtonik** [comment]
`simplestream` is some kind of video streaming service. Is there a link to speccy of the `simplestream` that is referenced in this issue?

**Comment by stgraber** [comment]
https://launchpad.net/simplestreams

**Comment by techtonik** [comment]
Doesn't look like a good doc.

**Comment by stgraber** [comment]
I can certainly agree with that statement.

**Comment by techtonik** [comment]
@stgraber at least what problem it tries to solve? and why there is nothing that can be used already?

**Comment by stgraber** [comment]
Simplestreams is what's used by lxd-images to fetch the Ubuntu images, we want to kill the external script and have support for the protocol in LXD itself.

**Comment by techtonik** [comment]
So it is only for steaming release images?

**Comment by stgraber** [comment]
It's basically a repository of Ubuntu images, at least for the simplestreams server we want to support.

It's got a bunch of index files that list all of the images available for all the Ubuntu releases, architectures and a bunch of tags so we can pull exactly what we want.

**Comment by techtonik** [comment]
How about renaming that simplestream project? If I understand it right, I can't watch movies with it from the middle of the stream distributed over cloud like I do with bittorent. It is not a stream and it is not simple (without docs for sure).

For a simplestream project I'd expect a streaming data format similar to JSON or YAML that I can query or start working with right from the middle. Like for streaming graph data when new nodes suddenly occur. But for index of repository images, which is not updated live (or is it?) - that is a strange name.

**Comment by techtonik** [comment]
The `channel` is a more appropriate name for that stuff than `stream`. If this index is updated live, I would call it `liveimageidx`.

**Comment by stgraber** [comment]
Done
