### ISSUE TITLE
Re-enable /dev/console by default

### ISSUE THREAD

**Issue by hallyn** [lxc/lxd#1463]
Ubuntu lxc containers want 5:1.  When root creates a container, it sets devices cgroup
limits and allows 5:1.

For the sake of migrateable containers, lxd is explicitly setting 5:1 in devices.deny.

When we start unprivileged lxd container, we do not set devices cgroup limits, so
we can (if security.nesting = true) create nested lxc containers.

However for privileged containers we set 5:1 in devices.deny, and so root in the
container fails to start child containres which want 5:1 in devices.allow.

We need to either

1. not set 5:1 (go back to a separate migrateable profile?)
2. change lxc to only set 5:1 if possible
3. ?

**Comment by stgraber** [comment]
I'd prefer 2), having to deal with a separate profile is a pain.

**Comment by hallyn** [comment]
The ugliness there is that 5:1 rwm is added using configuration.

Do we changes this for all devices.allow's?  If anything fails, WARN and proceed?

**Comment by tych0** [comment]
On Mon, Jan 04, 2016 at 05:32:49PM -0800, Serge Hallyn wrote:
> Ubuntu lxc containers want 5:1  When root creates a container, it sets devices cgroup
> limits and allows 5:1
> 
> For the sake of migrateable containers, lxd is explicitly setting 5:1 in devicesdeny
> 
> When we start unprivileged lxd container, we do not set devices cgroup limits, so
> we can (if securitynesting = true) create nested lxc containers
> 
> However for privileged containers we set 5:1 in devicesdeny, and so root in the
> container fails to start child containres which want 5:1 in devicesallow
> 
> We need to either
> 
> 1 not set 5:1 (go back to a separate migrateable profile?)
> 2 change lxc to only set 5:1 if possible
> 3 ?

or 4, figure out how to support migrating 5:1 devices. I think avagin
posted a patchset for this over the break that is in CRIU master now,
but I haven't had a chance to read it or play with it at all yet.

**Comment by stgraber** [comment]
Ok, so we're not going to release LXD 2.0 with /dev/console disabled and I'd also rather not have to keep a migratable profile as we want default containers to be migratable.

@tych0 what's the state of CRIU dumping /dev/console?

**Comment by tych0** [comment]
On Tue, Jan 26, 2016 at 01:39:38PM -0800, Stéphane Graber wrote:
> Ok, so we're not going to release LXD 2.0 with /dev/console disabled and I'd also rather not have to keep a migratable profile as we want default containers to be migratable.
> 
> @tych0 what's the state of CRIU dumping /dev/console?

I don't know, unfortunately. I got distracted by some other stuff and
then the travel apocalypse hit. I'll try and test it soon.

**Comment by stgraber** [comment]
Great, thanks.
