### ISSUE TITLE
Implement mount options

### ISSUE THREAD

**Issue by tssge** [lxc/lxd#1466]
We are in need of specifying mount options, or rather adding them for user quota inside an LXC container. I am not sure whether user quota works if you set the mount options, but it would be good to try.

There might be other applications for user specifiable mount options as well.

Please see lxc.rootfs.options from http://man7.org/linux/man-pages/man5/lxc.container.conf.5.html

**Comment by tssge** [comment]
I am not that good in Go, but made a patch. How does this look?

https://github.com/tssge/lxd/commit/906b30c7ac211473cae09f4c62bdb1b65298b934

I am unable to test it right now because LXD + LVM for some reason doesn't work on my machine in the newest version.

**Comment by tych0** [comment]
On Wed, Jan 06, 2016 at 09:45:11PM -0800, Teemu Grönqvist wrote:
> I am not that good in Go, but made a patch. How does this look?
> 
> https://github.com/tssge/lxd/commit/906b30c7ac211473cae09f4c62bdb1b65298b934

I think we'd want to apply this to all the fs backends, not just LVM.

> I am unable to test it right now because LXD + LVM for some reason doesn't work on my machine in the newest version.

What's the error you're getting?

**Comment by tssge** [comment]
> I think we'd want to apply this to all the fs backends, not just LVM.
I think LVM is currently the only backend doing mounting. I mean btrfs just creates a subvolume, don't know about zfs and directory is just a directory.

That is why LVM is the only backend supporting mount flags.
>What's the error you're getting?
On lvcreate something about path existing. It doesn't however tell what it used as a path, even when I try initting container with --debug and --verbose.

I installed LXD from the newest source. Doesn't work without my edits either, maybe it's one of those LVM issues on Github currently. Whatever, I'll try again later.

**Comment by stgraber** [comment]
Just a heads up that I'm working on requiring a device entry for the rootfs, so mount options should instead be a property against disk-type entries. When my change lands, you'll then be able to set that property for the rootfs disk entry.

**Comment by tssge** [comment]
@stgraber So do you mean that I shouldn't work on this patch because things are about to change quite soon, so that the patch has no purpose?

Just asking if you want me to work on this or not.

**Comment by stgraber** [comment]
Hi, the change I was talking about has since landed, all containers now have an entry for their root device.

**Comment by tssge** [comment]
Thank you. I'll go read the commits and close this issue if it's has been corrected already.

**Comment by stgraber** [comment]
I didn't implement custom mount options, so this hasn't been fixed, but you now have a better place to implement your option against.

Instead of making it a global LXD server option, you can now make it a disk device option.

**Comment by tssge** [comment]
It seems that this has been implemented: https://github.com/lxc/lxd/commit/81cafeba51a73d3b920c9e418dbb9389e5b40771

Should I close it?

**Comment by stgraber** [comment]
Yep
