### ISSUE TITLE
LVM storage: unable to allocate thin pool on Ubuntu 14.04

### ISSUE THREAD

**Issue by javacruft** [lxc/lxd#1467]
The volume group is configured on a 40G dedicated block device; LXD is unable to create the thin pool ontop of this:

Error: insufficient suitable allocatable extents for logical volume LXDPool: 10239 more required

```
t=2016-01-05T12:22:40+0000 lvl=dbug msg="Container load" container=instance-00000005
t=2016-01-05T12:22:40+0000 lvl=dbug msg="\n\t{\n\t\t\"error\": \"not found\",\n\t\t\"error_code\": 404,\n\t\t\"type\": \"error\"\n\t}"
t=2016-01-05T12:22:40+0000 lvl=info msg=handling method=GET url=/1.0/images/aliases/51e1265f-ac03-4c43-9f55-1a78255fca22 ip=@
t=2016-01-05T12:22:40+0000 lvl=dbug msg="\n\t{\n\t\t\"error\": \"not found\",\n\t\t\"error_code\": 404,\n\t\t\"type\": \"error\"\n\t}"
t=2016-01-05T12:22:42+0000 lvl=info msg=handling method=POST url=/1.0/images ip=@
t=2016-01-05T12:22:55+0000 lvl=dbug msg="\n\t{\n\t\t\"type\": \"async\",\n\t\t\"status\": \"OK\",\n\t\t\"status_code\": 100,\n\t\t\"operation\": \"/1.0/operations/dde4870a-728f-4e3e-940c-5742a601fb69\",\n\t\t\"resources\": null,\n\t\t\"metadata\": null\n\t}"
t=2016-01-05T12:22:55+0000 lvl=info msg=handling method=GET url="/1.0/operations/dde4870a-728f-4e3e-940c-5742a601fb69/wait?status_code=200&timeout=-1" ip=@
t=2016-01-05T12:22:56+0000 lvl=dbug msg=ImageCreate driver=storage/lvm fingerprint=265ac698cbe6d2df72f596c9a7fe74ac25ed563f229bcb5a2068d57132334d7c
t=2016-01-05T12:22:56+0000 lvl=dbug msg="Could not create thin pool" driver=storage/lvm name=LXDPool err="exit status 5" output="  Insufficient suitable allocatable extents for logical volume LXDPool: 10239 more required\n"
t=2016-01-05T12:22:56+0000 lvl=eror msg=LVMCreateThinLV driver=storage/lvm err="Error creating LVM thin pool: Could not create LVM thin pool named LXDPool"
t=2016-01-05T12:22:56+0000 lvl=dbug msg="Operation %!s(func(string) shared.OperationResult=0x5ec2c0) finished: { Error Creating LVM LV for new image: Error creating LVM thin pool: Could not create LVM thin pool named LXDPool}"
t=2016-01-05T12:22:56+0000 lvl=dbug msg="\n\t{\n\t\t\"type\": \"sync\",\n\t\t\"status\": \"Success\",\n\t\t\"status_code\": 200,\n\t\t\"metadata\": {\n\t\t\t\"id\": \"dde4870a-728f-4e3e-940c-5742a601fb69\",\n\t\t\t\"created_at\": \"2016-01-05T12:22:55.2523506Z\",\n\t\t\t\"updated_at\": \"2016-01-05T12:22:56.988949854Z\",\n\t\t\t\"status\": \"Failure\",\n\t\t\t\"status_code\": 400,\n\t\t\t\"resources\": null,\n\t\t\t\"metadata\": \"Error Creating LVM LV for new image: Error creating LVM thin pool: Could not create LVM thin pool named LXDPool\",\n\t\t\t\"may_cancel\": false\n\t\t}\n\t}"
```

**Comment by tssge** [comment]
LXD normally creates volumes for containers with 100GB space. It might try to create a thinpool that has 100GB minimum amount of space which means 40GB in volume group is not sufficient.

You may also create the thinpool yourself by using:

lvcreate -L 40G -T <vg>/<thinpool name>

then set it to LXD config by using:

lxc config set storage.lvm_thinpool_name <thinpool name>

This way your thinpool should be ready and usable on LXD.

**Comment by javacruft** [comment]
Creating the configuring the thinpool got me a little futher, then I tripped on:

t=2016-01-05T14:35:59+0000 lvl=dbug msg="Could not create LV snapshot" driver=storage/lvm output="lvcreate: invalid option -- 'k'\n  Error during parsing of command line.\n" lvname=instance--00000013 origlvname=27de3aa8840cc2c86700472fca176536248d515f670e117ea9bc346356603387

**Comment by stgraber** [comment]
Hi James,

I actually fixed that bug back in 0.25. What version are you running?

(LXD CI is running on trusty and does run the LVM tests)

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/commit/9b944e91e287bc9a3c7f40a0e215ab11b202383d specifically is the fix for the issue you're getting.

**Comment by javacruft** [comment]
I'm using the version currently in trusty backports - trying with the stable PPA to check if this is resolved.

**Comment by stgraber** [comment]
Oh right, 0.25 is in the backports queue but hasn't been approved yet, so I guess that's the problem and this issue has actually been fixed.

**Comment by stgraber** [comment]
Closing this as we know LVM works on 14.04, it's on thing more recent than 14.04 that we had some regressions :)
