### ISSUE TITLE
allow lxc exec on stopped containers

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1468]
Besides now being able to pull/push/edit files of a stopped container, it would be nice if you could do exec to a stopped container also.

This will probably require some more work (and I'm not even sure if it is at all possible to allocate a tty on a stopped container), but might be handy if you need to open a bash shell or other program inside the container rootfs with the proper namespace attached.

**Comment by stgraber** [comment]
I don't think we want to do that.

A straight exec into a stopped container would be missing the various mounts, would be using the wrong uid/gid map and would be entirely unprotected so could easily cause damage to the host.

Fixing those would basically equate to starting the container, so I believe the current behavior of requiring the container to be started is appropriate.
