### ISSUE TITLE
preserve file permissions on lxc file push

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1472]
When pushing a file to a container it's permissions are reset.
When a source file is 400, the destination becomes 644.

File permissions should be preserved in pushing files in the same way permissions are kept when copying files.

**Comment by stgraber** [comment]
Yep, that'd be good. A branch would be welcome (API already supports passing the wanted mode, so we just need to change the default to the source file's current value).

**Comment by jsimonetti** [comment]
I'll work on a pr somewhere this week.



Op 6 jan. 2016 18:17, bij 18:17, "Stéphane Graber" <notifications@github.com> schreef:

**Comment by stgraber** [comment]
Hey @jsimonetti any progress on this?

**Comment by jsimonetti** [comment]
Unfortunately none sofar. I have been otherwise occupied. I should have some time this weekend or next week at the latest to get this done.
