### ISSUE TITLE
[Testsuite] File Explorer Opens on Ubuntu 14.04

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1473]
Seems the test mount some stuff and thus nautilus opens up. Is there some way to prevent that?

It's not a big issue however it's annoying when running in the background and suddenly a windows pops up out of nowhere.

**Comment by stgraber** [comment]
Here I just see new drives show up but they don't get mounted, maybe it's some nautilus setting somewhere.

Anyway, no, there's nothing we can do about it in the testsuite, distros that monitor /proc/partitions or uevents for new devices will trigger when we create new loop devices in the testsuite.

**Comment by srkunze** [comment]
Alright. Thanks for clarifying.
