### ISSUE TITLE
[Testsuite] Unexpected Staging of Changes

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#1474]
When trying to reproduce for #1454, I found the following weird behavior:

```
>>> ~/go/src/github.com/srkunze/lxd$ git status
On branch feature/pids
Your branch is up-to-date with 'origin/feature/pids'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   lxc/list.go

... # testsuite

no changes added to commit (use "git add" and/or "git commit -a")
>>> ~/go/src/github.com/srkunze/lxd$ git status
On branch feature/pids
Your branch is up-to-date with 'origin/feature/pids'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   lxc/list.go
```

**Comment by tych0** [comment]
On Wed, Jan 06, 2016 at 09:21:24AM -0800, Sven R. Kunze wrote:
> When trying to reproduce for #1454, I found the following weird behavior:
> 
> ```
> >>> ~/go/src/githubcom/srkunze/lxd$ git status
> On branch feature/pids
> Your branch is up-to-date with 'origin/feature/pids'
> Changes not staged for commit:
>   (use "git add <file>" to update what will be committed)
>   (use "git checkout -- <file>" to discard changes in working directory)
> 
> 	modified:   lxc/listgo
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> >>> ~/go/src/githubcom/srkunze/lxd$ git status
> On branch feature/pids
> Your branch is up-to-date with 'origin/feature/pids'
> Changes to be committed:
>   (use "git reset HEAD <file>" to unstage)
> 
> 	modified:   lxc/listgo
> ```

The test suite does a git add, so that's expected. (This is to prevent
go fmt from eating any of your changes.)

**Comment by srkunze** [comment]
I just wondered.

Well, if there's no other way, just close the issue. :)

**Comment by stgraber** [comment]
Well, I suppose we could silence the git output in the testsuite but we still need to run the git add if we want to figure out what go fmt did.

**Comment by srkunze** [comment]
It's not so much about the git output but staging things.

As this seems not fixable for now, I close this.
