### ISSUE TITLE
container eth0 device named eth1?

### ISSUE THREAD

**Issue by heinsaris** [lxc/lxd#1491]
After updating from 0.20 to 0.26, some of my containers did nig get an IP address. After investigating, I found that those containers had their ethernet port named eth1.

I placed named: eth0 in the profile to fix this, but why did this happen? And why did it only happen to some containers?

**Comment by stgraber** [comment]
Sounds like you're confusing the device entry name with the network interface name inside the container.

Try setting the "name" property to "eth0", that should do it.

**Comment by heinsaris** [comment]
Hello,

I already added the name property inside the profile, and this indeed solved the problem. But I do not understand why the device suddenly became known as eth1 inside some of the containers. It was ethic before the update and nothing was changed in the configuration. 

On 11 January 2016 at 14:57:14, Stéphane Graber (notifications@github.com) wrote:

Sounds like you're confusing the device entry name with the network interface name inside the container.

Try setting the "name" property to "eth0", that should do it.

**Comment by pcdummy** [comment]
I had the same Problem on one of my hosts, thought its my fault so just fixed that on my containers.

**Comment by jsimonetti** [comment]
Same here, see #1435

**Comment by stgraber** [comment]
Has anyone seen this happen again?

The only thing I can think of right now about this issue is that if you were to modify a profile that contains network devices (say the default one), after upgrading to 0.25 or higher and before all containers got restarted, then some containers may see their interface temporarily renamed until next reboot.

**Comment by stgraber** [comment]
It doesn't appear to ever affect new containers as looking at our testing logs, we've never seen an eth1 show up out of the millions of containers our jenkins server created over the last month.

I've also never seen this happen on any of my production servers, so I suspect it very much was an upgrade weirdness. Albeit one we should have seen and handled properly.

Unless someone is reporting this as still happening for new containers, we'll close it as there's little point trying to handle the upgrade now, by the point someone would run any new update code we add now, the damage would already have been done...

**Comment by stgraber** [comment]
Oh, also, I'm wrong, the interface rename would actually survive a reboot as a volatile entry will be created... Again, that's very annoying but not something we can detect right now (detecting an accidently renamed eth0 which become eth1 vs a user which had eth0 and eth1 and removed eth0).

**Comment by jsimonetti** [comment]
Maybe to prevent any of this in the future, add the name attribute in the default profile.
I have done this myself for all my profiles just to be sure this never happens again.

**Comment by ChlorideCull** [comment]
I just had an issue when cloning containers because of this, and went on debugging for a few hours - I'd really suggest adding "name" entries to the defaults.
