### ISSUE TITLE
lxc launch ilo:ubuntu/wily/amd64 apitrace

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1492]
Command line description for `lxc launch` is insufficient.
```
Launch a container from a particular image.

lxc launch [remote:]<image> [remote:][<name>] [--ephemeral|-e] [...

Launches a container using the specified image and name.
```

For example:

    lxc launch ilo:ubuntu/wily/amd64 apitrace

Where this container will be run?

Will it persist?

**Comment by stgraber** [comment]
On your default remote (local most likely) and it will persist as your not explicitly making it ephemeral.

**Comment by techtonik** [comment]
> On your default remote (local most likely) 

Is it possible to add DEFAULT flag into `lxc remote list`?

> and it will persist as your not explicitly making it ephemeral.

Is it possible to check the status while it is still running? I don't want to lose it on reboot.

**Comment by stgraber** [comment]
We can definitely mark the default remote in lxc remote list. I actually thought I did that last time I reworked it, guess I didn't. 

As for ephemeral, there's a column for it in lxc list already. lxc info doesn't mention anything about it though, I'll fix that too.

**Comment by techtonik** [comment]
It will still not clear from command line help where what will be executed. It is worthy to add an example.
