### ISSUE TITLE
Error when launching container using Ubuntu Xenial PPC64el image

### ISSUE THREAD

**Issue by lucastadeu** [lxc/lxd#1494]
Hey guys,

I'm trying to get LXD to create a container for me on a PPC64el system but no luck so far.
I manually downloaded the ppc64el image from http://cloud-images.ubuntu.com/xenial/current/, specifically this one: http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-ppc64el-lxd.tar.xz

I then ran the following commands:

```
# lxc image import xenial-server-cloudimage-ppc64el-lxd.tar.xz --alias xenial
# lxc launch xenial teste
```

The container was created ok but I got an error when the container was started:
```
Creating teste done.
Starting teste error.
error: Error calling 'lxd forkstart teste /var/lib/lxd/containers /var/log/lxd/teste/lxc.conf': err='exit status 1'
Try `lxc info --show-log teste` for more info
```
I attached the log file to this issue.

Could this be something CRIU-related?

Thanks in advance!

[show-log.teste.txt](https://github.com/lxc/lxd/files/87880/show-log.teste.txt)

**Comment by stgraber** [comment]
Hi,

That's because you only imported the metadata tarball which doesn't contain a container rootfs :)

You either need to download both http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-ppc64el-lxd.tar.xz and http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-ppc64el-root.tar.xz

And import them both together with:

    lxc image import xenial-server-cloudimg-ppc64el-lxd.tar.xz xenial-server-cloudimg-ppc64el-root.tar.xz -- alias xenial

Or just tell lxd-images to do exactly that for you:

    lxd-images import ubuntu xenial ppc64el --alias xenial

**Comment by ferseiti** [comment]
Hello.

Just FYI, this:

```
lxd-images import ubuntu xenial ppc64el --alias xenial
```
Is not working, as far as I can tell. Apparently, the json files within cloud-images.ubuntu.com/daily/streams/v1/ and cloud-images.ubuntu.com/releases/streams/v1/ do not contain data for ppc64el-lxd.
I checked for other releases as well, but it seems that there just isn't any ppc64el-lxd at all in the json.

So the way to go seems to be downloading them manually.
Is this correct?

Cheers.

**Comment by stgraber** [comment]
No, the way to go is to get the guys publishing those images to fix their metadata.

@OddBloke said he was working on it

**Comment by lucastadeu** [comment]
@stgraber hah, I see.

Thanks :smile:

**Comment by stgraber** [comment]
lxd-images is now capable of importing working ppc64el images, closing this issue.
