### ISSUE TITLE
Error importing using "lxd-images" after deleting image

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1500]
Somehow I managed to wedge my LXD install. Currently trying to re import ubuntu I get:
jameinel@ubuntu:~/jc$ lxd-images import ubuntu --alias ubuntu
Downloading the GPG key for http://cloud-images.ubuntu.com
Validating the GPG signature of /tmp/tmpcyeguz33/download.json.asc
Downloading the image.
Image manifest: http://cloud-images.ubuntu.com/server/releases/trusty/release-20151218/ubuntu-14.04-server-cloudimg-amd64.manifest
error: 'NoneType' object is not subscriptable
usage: lxd-images [-h] [--quiet] {import,sync} ...
...

**Comment by jameinel** [comment]
I stripped out the actual certificates, but my lxd.db is quite small:
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE certificates (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    fingerprint VARCHAR(255) NOT NULL,
    type INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    certificate TEXT NOT NULL,
    UNIQUE (fingerprint)
);
CREATE TABLE config (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    key VARCHAR(255) NOT NULL,
    value TEXT,
    UNIQUE (key)
);
INSERT INTO "config" VALUES(1,'storage.zfs_pool_name','lxd-pool');
INSERT INTO "config" VALUES(6,'core.https_address','[::]');
CREATE TABLE containers (
    id INTEGER primary key AUTOINCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    architecture INTEGER NOT NULL,
    type INTEGER NOT NULL,
    ephemeral INTEGER NOT NULL DEFAULT 0,
    UNIQUE (name)
);
CREATE TABLE containers_config (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    container_id INTEGER NOT NULL,
    key VARCHAR(255) NOT NULL,
    value TEXT,
    FOREIGN KEY (container_id) REFERENCES containers (id) ON DELETE CASCADE,
    UNIQUE (container_id, key)
);
CREATE TABLE containers_devices (
    id INTEGER primary key AUTOINCREMENT NOT NULL,
    container_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    type INTEGER NOT NULL default 0,
    FOREIGN KEY (container_id) REFERENCES containers (id) ON DELETE CASCADE,
    UNIQUE (container_id, name)
);
CREATE TABLE containers_devices_config (
    id INTEGER primary key AUTOINCREMENT NOT NULL,
    container_device_id INTEGER NOT NULL,
    key VARCHAR(255) NOT NULL,
    value TEXT,
    FOREIGN KEY (container_device_id) REFERENCES containers_devices (id) ON DELETE CASCADE,
    UNIQUE (container_device_id, key)
);
CREATE TABLE containers_profiles (
    id INTEGER primary key AUTOINCREMENT NOT NULL,
    container_id INTEGER NOT NULL,
    profile_id INTEGER NOT NULL,
    apply_order INTEGER NOT NULL default 0,
    UNIQUE (container_id, profile_id),
    FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE CASCADE,
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);
CREATE TABLE images (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    cached INTEGER NOT NULL DEFAULT 0,
    fingerprint VARCHAR(255) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    size INTEGER NOT NULL,
    public INTEGER NOT NULL DEFAULT 0,
    architecture INTEGER NOT NULL,
    creation_date DATETIME,
    expiry_date DATETIME,
    upload_date DATETIME NOT NULL,
    last_use_date DATETIME,
    UNIQUE (fingerprint)
);
CREATE TABLE images_aliases (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    image_id INTEGER NOT NULL,
    description VARCHAR(255),
    FOREIGN KEY (image_id) REFERENCES images (id) ON DELETE CASCADE,
    UNIQUE (name)
);
CREATE TABLE images_properties (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    image_id INTEGER NOT NULL,
    type INTEGER NOT NULL,
    key VARCHAR(255) NOT NULL,
    value TEXT,
    FOREIGN KEY (image_id) REFERENCES images (id) ON DELETE CASCADE
);
CREATE TABLE profiles (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    UNIQUE (name)
);
INSERT INTO "profiles" VALUES(1,'default');
INSERT INTO "profiles" VALUES(2,'juju-lxd');
CREATE TABLE profiles_config (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    profile_id INTEGER NOT NULL,
    key VARCHAR(255) NOT NULL,
    value VARCHAR(255),
    UNIQUE (profile_id, key),
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);
INSERT INTO "profiles_config" VALUES(2,2,'boot.autostart','true');
INSERT INTO "profiles_config" VALUES(3,2,'security.nesting','true');
CREATE TABLE profiles_devices (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    profile_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    type INTEGER NOT NULL default 0,
    UNIQUE (profile_id, name),
    FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
INSERT INTO "profiles_devices" VALUES(1,1,'eth0',1);
CREATE TABLE profiles_devices_config (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    profile_device_id INTEGER NOT NULL,
    key VARCHAR(255) NOT NULL,
    value TEXT,
    UNIQUE (profile_device_id, key),
    FOREIGN KEY (profile_device_id) REFERENCES profiles_devices (id) ON DELETE CASCADE
);
INSERT INTO "profiles_devices_config" VALUES(1,1,'type','nic');
INSERT INTO "profiles_devices_config" VALUES(2,1,'nictype','bridged');
INSERT INTO "profiles_devices_config" VALUES(3,1,'parent','lxcbr0');
CREATE TABLE schema (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    version INTEGER NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE (version)
);
INSERT INTO "schema" VALUES(1,20,1452692121);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('schema',1);
INSERT INTO "sqlite_sequence" VALUES('profiles',2);
INSERT INTO "sqlite_sequence" VALUES('profiles_devices',1);
INSERT INTO "sqlite_sequence" VALUES('profiles_devices_config',3);
INSERT INTO "sqlite_sequence" VALUES('config',6);
INSERT INTO "sqlite_sequence" VALUES('images',1);
INSERT INTO "sqlite_sequence" VALUES('images_properties',4);
INSERT INTO "sqlite_sequence" VALUES('images_aliases',2);
INSERT INTO "sqlite_sequence" VALUES('certificates',5);
INSERT INTO "sqlite_sequence" VALUES('profiles_config',3);
INSERT INTO "sqlite_sequence" VALUES('containers',4);
INSERT INTO "sqlite_sequence" VALUES('containers_config',68);
INSERT INTO "sqlite_sequence" VALUES('containers_profiles',24);
COMMIT;

**Comment by jameinel** [comment]
This is the traceback:
Traceback (most recent call last):
  File "/usr/bin/lxd-images", line 763, in <module>
    args.func(parser, args)
  File "/usr/bin/lxd-images", line 602, in import_ubuntu
    msg(_("Image imported as: %s" % r['fingerprint']))
TypeError: 'NoneType' object is not subscriptable

**Comment by stgraber** [comment]
Anything interesting in /var/log/lxd.log?

If not, I'd recommend stopping lxd and restarting it with "lxd --debug --group lxd", then doing the import again, hopefully the output will include some clue as to what's going on.

**Comment by tych0** [comment]
Can you post `tree /var/lib/lxd`?

**Comment by jameinel** [comment]
Tree is really big, as it seems to have an unpacked image. Note that "lxc list" shows no active entries. I'm guessing the image is on disk, but the metadata is deleted.
.
├── containers
│   └── lxc-monitord.log
├── devices
├── devlxd
│   └── sock
├── images
│   ├── 0afd3f6ac0d751fb121ad9a77a163926208ee71c57d68bd75cc253ce2c733a60
│   ├── 0afd3f6ac0d751fb121ad9a77a163926208ee71c57d68bd75cc253ce2c733a60.rootfs
│   └── 0afd3f6ac0d751fb121ad9a77a163926208ee71c57d68bd75cc253ce2c733a60.zfs
│       ├── metadata.yaml
...
│       └── templates
│           ├── cloud-init-meta.tpl
│           ├── cloud-init-user.tpl
│           ├── cloud-init-vendor.tpl
│           └── upstart-override.tpl
├── lxd.db
├── security
│   ├── apparmor
│   │   ├── cache
│   │   └── profiles
│   └── seccomp
├── server.crt
├── server.key
├── shmounts
├── snapshots
├── unix.socket
└── zfs.img

2756 directories, 29022 files

**Comment by jameinel** [comment]
/var/log/lxd.log doesn't have anything particularly interesting:
t=2016-01-13T20:17:01+0400 lvl=info msg=handling method=GET url="/1.0/images?recursion=1" ip=@
t=2016-01-14T11:09:34+0400 lvl=info msg=handling url=/1.0/images ip=@ method=GET
t=2016-01-14T11:10:14+0400 lvl=info msg=handling ip=@ method=POST url=/1.0/images
t=2016-01-14T11:10:33+0400 lvl=info msg=handling method=GET url=/1.0/operations/78fab4b8-51ce-4505-934b-9e86de4a7647/w
t=2016-01-14T11:14:36+0400 lvl=info msg=handling url="/1.0/containers?recursion=1" ip=@ method=GET
t=2016-01-14T11:15:24+0400 lvl=info msg=handling method=GET url="/1.0/images?recursion=1" ip=@
t=2016-01-14T11:17:02+0400 lvl=info msg=handling method=GET url="/1.0/images?recursion=1" ip=@

**Comment by stgraber** [comment]
Wow, that's weird, you seem to have a partly unpacked metadata tarball directly in /var/lib/lxd/images, I've never seen that before...

So with an empty "lxc image list", it'd suggest that something failed during image delete and removed the DB entry while failing to remove the fs entries.

Manually removing the zfs filesystem and related entries in /var/lib/lxd/images should fix things for you.

We should investigate why LXD allows the DB entry to go away before the fs entries are gone.

**Comment by jameinel** [comment]
I do have a lot more fs entries in that one directory, but yeah, delete failed with "error code 2" back when I deleted the image the first time, but didn't have a traceback, etc. If you're happy, I'll clean it out and move on.

**Comment by jameinel** [comment]
Trying to just delete those directories I get:
rm: cannot remove ‘lxd/images/0afd3f6ac0d751fb121ad9a77a163926208ee71c57d68bd75cc253ce2c733a60.zfs/rootfs/etc/ca-certificates.conf’: Read-only file system

Which looks that zfs-fuse is refusing to let you delete the directories.

**Comment by stgraber** [comment]
Right, short of having the debug log of back when it happened, there's not much we can do there, we'll just make sure that next time something fails the DB entry doesn't get removed.

You need to do "zfs destroy lxd/images/0afd3f6ac0d751fb121ad9a77a163926208ee71c57d68bd75cc253ce2c733a60", you can't remove a zfs filesystem with rm.

**Comment by stgraber** [comment]
I'm closing this as we now have re-ordered the image delete code to avoid this kind of situation.
