### ISSUE TITLE
Unable to connect to: images.linuxcontainers.org:8443 when using proxy

### ISSUE THREAD

**Issue by robcarGIT** [lxc/lxd#1509]
I am behind a proxy and when I type:

    $ lxc image list images:

I got:

    error: Get https://images.linuxcontainers.org:8443/1.0: Unable to connect to: images.linuxcontainers.org:8443

_wget_ ting the same image works fine instead.

**Comment by tych0** [comment]
On Fri, Jan 15, 2016 at 07:13:30AM -0800, Roberto Carraro wrote:
> I am behind a proxy and when I type:
> 
>     $ lxc image list images:
> 
> I got:
> 
>     error: Get https://imageslinuxcontainersorg:8443/10: Unable to connect to: imageslinuxcontainersorg:8443
> 
> _wget_ ting the same image works fine instead

Do you have some proxy configuration in your environment? What is it?

**Comment by robcarGIT** [comment]
Oh sorry, I had proxy set for .wgetrc, but NOT in /etc/environment.
Once I added it image list appeared fine.
Thank you

**Comment by stgraber** [comment]
Good to hear!
