### ISSUE TITLE
Upgrade stops containers

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1522]
Upgrading to the latest version stops running containers:

0.26-0ubuntu3~ubuntu14.04.1~ppa

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

**Comment by stgraber** [comment]
Were they restarted after the update was applied? If yes, then that's unfortunately the expected behavior right now as we haven't yet found a way to tell upstart/systemd to behave differently on daemon restart (for update) instead of host restart (when rebooting).

**Comment by stgraber** [comment]
Closing due to lack of response. Feel free to re-open.
