### ISSUE TITLE
lxc command to just create a container

### ISSUE THREAD

**Issue by kkobashi** [lxc/lxd#1529]
From what I see, there is no lxc command to just create a container. The launch command creates and  runs a container.

There isn't the equivalent of a lxc-create only command in lxc client to stay with backwards "compatability".

**Comment by hallyn** [comment]
lxc init

**Comment by kkobashi** [comment]
Thanks hallyn, just as you wrote this I saw the init command. Very confusing though. Why not just call it create?

**Comment by stgraber** [comment]
The naming of that particular command was an executive decision which we can't really do much about. Create was one of the proposed alternatives which was then rejected.

Note that with the alias mechanism, you can edit your .config/lxc/config.yml and define an alias for "create: init" which will do what you want.
