### ISSUE TITLE
"No client certificate provided" error during POST request

### ISSUE THREAD

**Issue by And-Sm** [lxc/lxd#1546]
If I do REST POST to /1.0/certificates I receive:

> {"error":"No client certificate provided","error_code":400,"type":"error"}

I have client.crt on client machine, configured trust_password on server. Also "remote add" was done on client machine for server and after thumbprint - server password was successfully entered.

LXD 2.0.0 beta1

**Comment by stgraber** [comment]
What exactly are you posting to that URL and with what?

**Comment by And-Sm** [comment]
{'type': "client",'password': "test1"}
As I understand - name and certificate aren't necessary options, right?

**Comment by stgraber** [comment]
You either must pass the certificate you want to add in the certificate field, or if you don't set it, you must have your client send the client certificate in the tls request.

The error you got back means that LXD didn't find any TLS client certificate in your request.

**Comment by And-Sm** [comment]
Can you please provide valid TLS request or some basic steps to achieve that? Didn't find those steps in documentation.

**Comment by stgraber** [comment]
curl -k -X POST -d '{"type": "client", "password": "test1"}' --cert your-client.crt --key your-client.key

Something like that should do it. That's going to add the certificate your-client.crt to the server's trust store.

**Comment by And-Sm** [comment]
Yes, I was able to use following commands

**Adding a new trusted certificate**
`sudo curl -k -X POST -d '{"type": "client", "password": "test1","name":"client_cert"}' --cert /home/test/.config/lxc/client.crt --key /home/test/.config/lxc/client.key --url https://url:8443/1.0/certificate
`

Response was:

> {"type":"sync","status":"Success","status_code":200,"metadata":{},"operation":""}

But anyway **List of containers** command works only if I send it with --cert and --key arguments. 
`sudo curl -k -X GET -d '{"type": "client", "password": "test1"}' --cert /home/test/.config/lxc/client.crt --key /home/test/.config/lxc/client.key --url https://url:8443/1.0/containers
`

Response if using --cert and --key:

> {"type":"sync","status":"Success","status_code":200,"metadata":[],"operation":""}

Response without --cert and --key:

> {"error":"not authorized","error_code":403,"type":"error"}


So, it is "by design" and I should use certificate args with any trusted request, or something wasn't added on the server side?

**Comment by stgraber** [comment]
There's no way for the server to authenticate you if you're not using your client certificate, so yes, you must always set it when doing requests over https.

Requests going through the local socket (/var/lib/lxd/unix.socket) are the only ones which do not require authentication as authentication is done for you by the filesystem (whoever can write to the socket can talk to LXD).

**Comment by And-Sm** [comment]
Thanks for the explanation, but I'm using client certificate, it was added to %user%/.config/lxc and it can be seen if using **lxc config trust list** command...

**Comment by stgraber** [comment]
Sure and the "lxc" command will use it automatically from that location, but curl or any other http client doesn't know where those files are and so won't be using them unless you ask it to (which is what --cert and --key do).

**Comment by And-Sm** [comment]
Ok, thanks again.
