### ISSUE TITLE
using lxd init on xenial

### ISSUE THREAD

**Issue by gaughen** [lxc/lxd#1547]
On a fresh instance instance running Ubuntu Xenial, I was using 'lxd init' to configure a zfs pool.   It wasn't until I finish answering all the questions that it informs me that the zfs tool isn't available. Would it make sense to error out earlier or tell me more specifically what I should apt install to address the deficiency?

ubuntu@ip-172-31-13-135:~$ sudo lxd init
Name of the storage backend to use (dir or zfs): zfs
Create a new ZFS pool (yes/no)? yes
Name of the new ZFS pool: testpool
Would you like to use an existing block device (yes/no)? no
Size in GB of the new loop device (1GB minimum): 10
Would you like LXD to be available over the network (yes/no)? no
error: The 'zfs' tool isn't available

Also, once I do install the zfsutils-linux package, it still requires me to manually load the zfs module. Is this expected (better error message though)?

ubuntu@ip-172-31-3-173:~$ sudo lxd init
Name of the storage backend to use (dir or zfs): zfs
Create a new ZFS pool (yes/no)? yes
Name of the new ZFS pool: testpool
Would you like to use an existing block device (yes/no)? no
Size in GB of the new loop device (1GB minimum): 10
Would you like LXD to be available over the network (yes/no)? no
error: Failed to create the ZFS pool: The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.

**Comment by stgraber** [comment]
I believe both errors are reasonably clear so I think LXD is doing an appropriate job here at surfacing the error it's getting from its storage backend.

lxd init goes through an interactive configuration stage where it goes through a tree of questions, then it attempts to implement what you asked, which is when it fails. Validating every input as you enter it would save the user a bit of time but would also cause a significant amount of code duplication on our end (the duplication coming from the --auto mode where the interactive stage is skipped and the config is read from command line arguments instead).

The fact that zfs doesn't modprobe on install is annoying, especially as it does at boot time. It'd be great if you could file a bug against zfs on Launchpad to have the zfs packaging fixed for this (Colin King on the server time is taking care of it).

**Comment by stgraber** [comment]
Oh and as much as we'd like to, we can't really depend on zfs from LXD as it's only really viable on amd64, ppc64el and arm64 right now and only on some specific Ubuntu kernels, so it has to be a user opt-in for now. There is however hope that some 16.04 images will ship with it pre-installed, which would fix both of your issues.

I'd still strongly recommend you file a Launchpad bug against zfs to have it do the modprobe at install time, that'd make a lot of people's life easier.

**Comment by stgraber** [comment]
Does that sound reasonable to you or do you still think there's something that LXD could be doing to make things better (considering the above limitations)?

**Comment by gaughen** [comment]
One of the reasons I raised this is that when I setup the zfs pool manually (using zpool create), I did not need to manually load the module.  Anyhow, I'll followup with the kernel team tomorrow and see what's possible.

**Comment by stgraber** [comment]
Oh, that's odd. I certainly remember "zpool create" failing for me on a clean xenial install last I tried, with the same modprobe error.

To be clear, LXD doesn't do anything special there, it literally calls "zpool create <name> /some/path -m none" for you :)

I'm closing the LXD issue, let me know if you'd like me to comment in the Launchpad bug to get zfs to do the right thing by default.

**Comment by dustinkirkland** [comment]
I totally agree with Pat, and would like to see this bug reopened.

As soon as you enter "zfs" to the first question, lxd init should check if "zpool" executable is found.  If not, exit non zero, and ask the user to please 'apt install zfs'.
