### ISSUE TITLE
Add resource tracking

### ISSUE THREAD

**Issue by zulcss** [lxc/lxd#1548]
Now that we have the option for restricting container resources, can we have a way to measure these resources.

**Comment by arsiesys** [comment]
Very good idea, how do you "see" this feature ? Data metrics avaiable by the API (like CPU, Network, I/O) ?
What do you think to integrate a collector to push data to an IOT database (like openstdb). It will allow users to generate many grafana dashboard to follow their containers (as they want). Also, yes we can install ourself something like scollector on each container but if it was integrated... could be... awesome ? :)

**Comment by stgraber** [comment]
My current plan is to rework/extend the container status information we've got today in the API to also expose cgroups limits, that should do the trick for @zulcss (who's working on LXD OpenStack integration) and should allow for someone to write a reasonably simple script that uses the LXD API to retrieve all the stats and push them to whatever backend you want.
