### ISSUE TITLE
Allow for stateful stop/start

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#1558]
So I was recently discussing LXD in HPC environnents and one thing that came up was that it'd be nice if we could suspend a container to disk so that next time it starts, it just keeps doing what it was when it got stopped. 

From an API point of view that would be an additional stateful keyword that would be accepted in the force stop action. 

In that case LXD would freeze the container, dump state to the current container directory and kill the container. 
On startup, if state files are present the LXD would restore the container state. 

This would all be done without having to use LXD snapshots.

**Comment by nevi-me** [comment]
I've noticed that everytime I update lxd with apt-get all my containers seem to restart. It would be useful to be able to enable stateful restart when upgrading lxd. 
Would this be feasible, or is it a requirement that all containers restart?
