### ISSUE TITLE
ssh hangs after install lxd on Ubuntu 14.04

### ISSUE THREAD

**Issue by DavidPu** [lxc/lxd#1561]
install lxd on Ubuntu 14.04 by following https://insights.ubuntu.com/2015/04/28/getting-started-with-lxd-the-container-lightervisor, ssh server is stop working after that:
 sudo aptitude install lxd

ssh -vvvv dpu@localhost
.....
dpu@localhost's password: 
debug3: packet_send2: adding 64 (len 54 padlen 10 extra_pad 64)
debug2: we sent a password packet, wait for reply
debug1: Authentication succeeded (password).
Authenticated to localhost ([127.0.0.1]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
............hangs forever here.....

**Comment by stgraber** [comment]
That's a known issue which @hallyn is fixing now.

Installing the "cgroup-lite" package on your system will fix login again.

This isn't a LXD issue but an Ubuntu packaging issue of lxcfs, so closing this report now.

Sorry about the temporary breakage!

**Comment by DavidPu** [comment]
Thanks @stgraber for quick response!
