### ISSUE TITLE
sharing Unix sockets

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1582]
Would it be possible to shared Unix sockets between containers for more secure container to container communication?

Use case i am looking at is using dovecot in one container and postfix in another but enable postfix to authenticate using dovecot sasl which by design would be insecure over a tcp socket compared to using a Unix socket.

**Comment by stgraber** [comment]
You can certainly bind-mount unix sockets using lxd's "disk" device entry.

The one catch though is that the inode number of a unix socket changes every time you bind it, so a bind-mounted unix socket will become useless as soon as the daemon is restarted.

As a result, you're most likely better off creating a shared directory which is bind-mounted into both containers and use that directory to write your sockets into.

**Comment by jsimonetti** [comment]
I feel stupid not thinking about that sooner :p
