### ISSUE TITLE
"lxc exec foo" default to "bash"

### ISSUE THREAD

**Issue by dustinkirkland** [lxc/lxd#1586]
lxc exec is a phenomenal command.  It seems that 99.9% of the time, I end up execing bash.  Sounds like a good sensible UI/UX to me.

**Comment by stgraber** [comment]
We should only do so once we figure out a way to properly return errors when the request binary isn't found or can't be executed, right now, go-lxc doesn't surface that information to us and as a result, lxc exec just shows nothing and exits -1 (with no way for it to differentiate between that case and a binary exitting -1 without printing anything).

**Comment by tych0** [comment]
As a workaround, `printf "aliases:\n  shell: exec @ARGS@ bash" >> ~/.config/lxc/config.yml` and then `lxc shell foo` should get you a shell in foo.

**Comment by dustinkirkland** [comment]
Oh, even better...

Can we have an lxc shell command, in addition to exec?  Perhaps it tries a
list of shells in a pre-determined order...  bash, sh, dash, ash, csh, etc.


:-Dustin

**Comment by stgraber** [comment]
Would run into the same problem though, once we figure out a way to differentiate the command exitting -1 without any output vs the command not existing, then we could do something like that, yeah.

**Comment by stgraber** [comment]
And the command aliases let you define such a command for yourself until then, I have this in my local .config/lxc/config.yml:

```
aliases:
  shell: exec @ARGS@ -- bash
```

**Comment by xose** [comment]
How about `login -f root` as default instead of bash/sh?

No need to guess the shell, proper environment (uses the locale configured in the container for example), displays motd, logs the session, ...

**Comment by JohnstonJ** [comment]
I also like the idea of defaulting to `login`.  Also, once some users are set up in the container, it might be better not to automatically log in as `root`, either.  Benefit is it looks like logging into a regular Linux system over SSH or on the local console.
