### ISSUE TITLE
error: Disk is missing /sys/class/block entry 

### ISSUE THREAD

**Issue by j3dd4h** [lxc/lxd#1590]
I tried to create container on virtual disk (hw/bios raid) .

===============
user@server:~$ lxc launch ubuntu1404 dbserver
Creating dbserver
error: Disk is missing /sys/class/block entry
===============
/dev/cciss/c0d0p1  909G  2.1G  861G   1% /

**Comment by stgraber** [comment]
Please upgrade to LXD 2.0.0.beta2 which we released yesterday with a fix for this.
