### ISSUE TITLE
Containers not started after boot automatically

### ISSUE THREAD

**Issue by dhenrich** [lxc/lxd#1591]
I rebooted a xenial host with /sbin/reboot. The next morning I logged in and ran the following commands. Notice how the first one indicated the container was stopped and the second one indicated it was running. These commands were in quick succession (I was using ifconfig to see if the bridge was up). I don't know if running the lxc command caused lxd to do something that started the container or what. It was weird. The container definitely started after I ran lxc list and the machine had been up for hours at that point.

<dean@courage>:~$ lxc list
+-------+---------+------+------+-----------+-----------+
| NAME  |  STATE  | IPV4 | IPV6 | EPHEMERAL | SNAPSHOTS |
+-------+---------+------+------+-----------+-----------+
| lsdev | STOPPED |      |      | NO        |         0 |
+-------+---------+------+------+-----------+-----------+
| maast | STOPPED |      |      | NO        |         0 |
+-------+---------+------+------+-----------+-----------+
| maasx | STOPPED |      |      | NO        |         0 |
+-------+---------+------+------+-----------+-----------+
<dean@courage>:~$ ifconfig
br0       Link encap:Ethernet  HWaddr 00:24:9b:16:77:19
          

enp3s0    Link encap:Ethernet  HWaddr 78:2b:cb:8e:56:6b
 

enx0023552c5378 Link encap:Ethernet  HWaddr 00:23:55:2c:53:78
   

enx00249b167719 Link encap:Ethernet  HWaddr 00:24:9b:16:77:19
      
lo        Link encap:Local Loopback
       

lxcbr0    Link encap:Ethernet  HWaddr 06:59:06:34:88:5f
        
vethG8PSVM Link encap:Ethernet  HWaddr fe:cc:22:08:ee:87
         

<dean@courage>:~$ lxc list
+-------+---------+-----------------+------+-----------+-----------+
| NAME  |  STATE  |      IPV4       | IPV6 | EPHEMERAL | SNAPSHOTS |
+-------+---------+-----------------+------+-----------+-----------+
| lsdev | STOPPED |                 |      | NO        |         0 |
+-------+---------+-----------------+------+-----------+-----------+
| maast | STOPPED |                 |      | NO        |         0 |
+-------+---------+-----------------+------+-----------+-----------+
| maasx | RUNNING | 10.7.0.3 (eth0) |      | NO        |         0 |
+-------+---------+-----------------+------+-----------+-----------+
<dean@courage>:~$

**Comment by stgraber** [comment]
Yeah, lxd is socket activated so I guess it only started for real when you issued the first command, then noticed it had containers that were supposed to be running and started them then.

That's not how things are supposed to work though, we have another unit that should have kicked in at boot time, noticed you had containers that needed to be started and spawned those then...

I'll take a look.

**Comment by dhenrich** [comment]
This is still not working with 2.0.0~rc1-0ubuntu3

**Comment by stgraber** [comment]
That's expected, the fix is in rc2.

**Comment by dhenrich** [comment]
I confirm it is fixed for me in rc2
