### ISSUE TITLE
error: Get http://unix.socket/1.0/containers?recursion=1

### ISSUE THREAD

**Issue by robcarGIT** [lxc/lxd#1595]
Hello,
I'm experimenting a bit with lxd and I have to say that it is really promising, so first of all congrats to all people involved in its development!

Today I did an _apt-get upgrade_; during the process it hanged forever while configuring lxd.conf and since then I cannot use my lxd infrastructure anymore.
I also tried to remove lxd and reinstall it.

```
$ lxc version
2.0.0.beta2
$ sudo service lxd start
start: Job is already running: lxd
$ sudo lxc list
error: Get http://unix.socket/1.0/containers?recursion=1: dial unix /var/lib/lxd/unix.socket: connect: no such file or directory
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```
Please, let me know if you need logs or other.
thanks

rob

**Comment by robcarGIT** [comment]
```
# tail /var/log/upstart/lxd.log
error: LXD still not running after 600s timeout.
WARN[02-12|10:13:01] CGroup memory swap accounting is disabled, swap limits will be ignored.
error: no such column: creation_date
error: LXD still not running after 600s timeout.
```
Ok, I saw this issue in the lxd-users mailing list yesterday, I'll have a look at it.

**Comment by robcarGIT** [comment]
uhmm...
that above was an old message. I tried to do:

`sudo sqlite3 /var/lib/lxd/lxd.db "ALTER TABLE containers ADD COLUMN creation_date DATETIME NOT NULL DEFAULT 0;"`

but then 

```
sudo tail /var/log/upstart/lxd.log

WARN[02-12|16:04:06] CGroup memory swap accounting is disabled, swap limits will be ignored.
error: duplicate column name: creation_date
```

damn! :)

**Comment by stgraber** [comment]
You're the second person reporting a problem with that particular DB update, I'm really not sure what's going on...

As for your second error, the following should fix it:

    sudo sqlite3 /var/lib/lxd.db 'INSERT INTO schema (version, updated_at) VALUES (22, strftime("%s"));'

**Comment by robcarGIT** [comment]
Yep! 
It is working now, of course the correct path of the db is:

`/var/lib/lxd/lxd.db`

Thanks and keep up the great work! :)

**Comment by stgraber** [comment]
And that particular bug has now been fixed upstream and uploaded to Ubuntu, closing this issue.
