### ISSUE TITLE
New beta cannot init containers with zfs root

### ISSUE THREAD

**Issue by Calrama** [lxc/lxd#1602]
Steps to reproduce (I hope):
- rootfs on a zfs dataset (e.g. "system/funtoo/root")
- set lxd to use a dataset on the same zpool as the rootfs (e.g. "system/lxd")

With lxd 0.27 this works as expected. However, the new betas (1 and 2) yield
```
error: Disk system is missing /sys/class/block entry
```

(where "system" is my zpool). ZFS pools&datasets don't have such entries. The offending line is [this](https://github.com/lxc/lxd/blob/596a1a983d6521454982f74ad8748cb8af5c02fe/lxd/container_lxc.go#L3518) and the fix could be similar to https://github.com/lxc/lxd/commit/596a1a983d6521454982f74ad8748cb8af5c02fe in nature, though I'm not familiar enough with lxd internals to be sure.

**Comment by stgraber** [comment]
Sounds like you're using beta1, that error message doesn't exist in beta2.

**Comment by Calrama** [comment]
Hm, you're right, I just double checked and there was a bug in my build script for beta2, resulting in the old tarball being used. Sorry about that, I will close for now.
