### ISSUE TITLE
systemd PrivateNetwork fails due to AppArmor

### ISSUE THREAD

**Issue by ChlorideCull** [lxc/lxd#1603]
Simply put, plenty of systemd services require PrivateNetwork (basically creates a new network namespace with only a loopback network) which fails on the latest PPA build on Ubuntu Wily.

Log on host:

    -- Logs begin at Sun 2016-02-14 19:13:49 UTC, end at Sun 2016-02-14 23:29:34 UTC. --
    Feb 14 23:29:34 changeling kernel: audit: type=1400 audit(1455492574.134:46): apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
    Feb 14 23:29:34 changeling kernel: audit: type=1400 audit(1455492574.134:45): apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
    Feb 14 23:29:34 changeling kernel: audit: type=1400 audit(1455492574.134:44): apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
    Feb 14 23:29:34 changeling kernel: audit: type=1400 audit(1455492574.134:43): apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
    Feb 14 23:29:34 changeling audit[6396]: AVC apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
    Feb 14 23:29:34 changeling audit[6396]: AVC apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
    Feb 14 23:29:34 changeling audit[6396]: AVC apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
    Feb 14 23:29:34 changeling audit[6396]: AVC apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none

[Service in question](https://github.com/systemd/systemd/blob/b95292a1523fb119a1cfa11a461f605566b41cec/test/test-execute/exec-privatenetwork-yes.service) being used is from the systemd testing suite, and is run on the child container (and fails with `225/NETWORK` and Permission Denied):

    [Unit]
    Description=Test for PrivateNetwork
    
    [Service]
    ExecStart=/bin/sh -x -c 'i=$$(ip link | grep ": " | grep -v ": lo:"); test -z "$$i"'
    Type=oneshot
    PrivateNetwork=yes

**Comment by stgraber** [comment]
Would you mind filing this against github.com/lxc/lxc instead? The apparmor profile used by LXD is the one coming directly from LXC and used by some other projects (like Docker).

**Comment by stgraber** [comment]
It's not clear to me what in our profile is causing that denial as I'd expect this failure to fall under the "network" apparmor policy type which is completely allowed in our policy... Anyway, once the bug is filed against LXC I'll nag one of our security guys and apparmor upstream person to look into this.

**Comment by stgraber** [comment]
Also, please include what version of the Linux kernel, lxc and lxd you're using as I just tried to reproduce this failure locally here (3.13 kernel, lxc 2.0.0.beta2 and lxd 2.0.0.beta2 and couldn't, the unit starts quite happily here).

**Comment by ChlorideCull** [comment]
Alright, filed it on LXC as [issue #820](https://github.com/lxc/lxc/issues/820). Put the information you wanted there as well.
