### ISSUE TITLE
Autostart doesn't work for me

### ISSUE THREAD

**Issue by Debianer** [lxc/lxd#1608]
Host Wily AMD64, LXD stable repo from Ubuntu containers team enabled and updatet. Host running as a KVM guest that I rent.

2 Guests: Debian 8 + Ubuntu Wily

For both:

boot.autostart: true (I also tried boot.autostart: 1 at first, but then changed it to "true")

I tried without boot.autostart.priority and boot.autostart.delay and I used different integers between 1 und 90 and a couple different combinations.

No matter what I do, the guests do not start automatically. Reboot or cold start, guests running or stopped before the reboot. Once I start using lxd commands on the host, they start up. lxc list will show the guests as stopped, but will show them as running a short while later. lxc list seems to start the guests. lxc exec will also start them.

**Comment by stgraber** [comment]
This has been fixed by https://github.com/lxc/lxd/commit/baa728088e2323270470eb36b178f151e32d275f
