### ISSUE TITLE
Show some progress on `lxc image import`

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1610]
I am trying to add a big 4 Gb image to LXD through a network:

    lxc image import 2016-02-09-raspbian-jessie.img --alias rpi --verbose --debug

And lxc hangs without any response for more than 5 minutes. Is it possible to provide something like progress bar for this process (and maybe increase buffer or something)? I also suspect that the image format is wrong, so is it possible to get know about this early?

**Comment by thuandt** [comment]
+1

**Comment by stgraber** [comment]
We can't really show progress once the file made it to LXD as that's basically up to sub processes like tar and xz, but we should be able to show some upload progress at least (which for a local LXD would be near instant).

**Comment by stgraber** [comment]
stgraber@dakara:/tmp$ lxc image import sl-6.tar.xz s-chulak:
Transfering image: 37%

**Comment by techtonik** [comment]
I can't test it right now, but it looks fine. =)
