### ISSUE TITLE
Implement publishing empheral containers.

### ISSUE THREAD

**Issue by vskubriev** [lxc/lxd#1611]
Empheral containers is most useful feature for me. But how to publish this containers ?

It is impossible now. Because for publish you need to stop, after stop container is absent.

But it is kill feature to use lxd as docker workflow.

For example I can explain what's I mean below:

1. Suppose we have make.d folder with custom scripts, which are divided into some stages.
2. Each of this script setting up container and publish image with it stage.
3. Next stage using previously published image as checkpoint.
4. This way we can reduce the development time.

This is a feature request.

I think it will be possible to publish container image and then will delete source empheral container.

Or may be something else flag, option to achive my goal.

Thank you.

**Comment by stgraber** [comment]
Sounds like the client could be a bit more clever indeed by unsetting the ephemeral flag first, then stopping the container, then restoring the ephemeral flag and finally publishing.

Should be reasonably easy to fix.

**Comment by vskubriev** [comment]
Stages to publish more clever (IMHO):

1. when publish check if container is ephemeral, and unset if it has.
2. stopping container
3. publish
4. restoring ephemeral flag
5. start the container again if it was launched (returns the original state of published container)

**Comment by stgraber** [comment]
I would actually switch step 3 and 4. So restoring the ephemeral flag as soon as we can.

**Comment by vskubriev** [comment]
Good there is no problem.
