### ISSUE TITLE
Add default unix-like command aliases

### ISSUE THREAD

**Issue by mjeanson** [lxc/lxd#1615]
A simple usability fix for the lxc client would be adding default *unix-like* command aliases, for example :

 * ls -> list
 * rm -> delete
 * mv -> move
 * cp -> copy

**Comment by stgraber** [comment]
Let's block that on #490 for now

**Comment by stgraber** [comment]
I'm fine with the idea of having those default aliases, so long as we make very sure we never use the aliases in example commands, documentation or error messages where we should always use the long keywords for clarity.

**Comment by mjeanson** [comment]
As long as I can type `lxc ls` and get a list of containers, I'll be happy.

**Comment by tych0** [comment]
On Tue, Feb 16, 2016 at 12:11:04PM -0800, Michael Jeanson wrote:
> As long as I can type `lxc ls` and get a list of containers, I'll be happy.

you can today,

printf "aliases:\n  ls: list" >> ~/.config/lxc/config.yml

**Comment by mjeanson** [comment]
I'll be happier if I don't have to use an undocumented feature, and I'll be even happier if it works out of the box. :)

Thanks for the tip, that's what I'm using currently, following Stéphane's advice.

**Comment by sean-jc** [comment]
This is what the default config would look like if the traditional unix aliases were added to all commands and subcommands.  Any reason not to go this route?  If there are no objections then I'll start working on tests.

This depends on #2096 so I don't want to submit a PR yet.

```go
var DefaultConfig = Config{
	Remotes:       DefaultRemotes,
	DefaultRemote: "local",
	Aliases: map[string]string{
		"shell": "exec @ARGS@ -- login -f root",

		// Unix-like aliases for subcommands and sub-subcommands
		"cp": "copy",
		"ls": "list",
		"mv": "move",
		"rm": "delete",

		"image cp": "image copy",
		"image ls": "image list",
		"image rm": "image delete",

		"image alias ls": "image alias list",
		"image alias rm": "image alias delete",

		"remote ls": "remote list",
		"remote mv": "remote rename",
		"remote rm": "remote remove",

		"config device list": "config device ls",
		"config device rm":   "config device remove",
	},
}
```

**Comment by mjeanson** [comment]
That would be awesome

**Comment by stgraber** [comment]
My main concern with us adding default aliases there is that they won't apply to existing users. To get new aliases, you'd have to either manually add them yourself or remove your config.yml, which doesn't seem quite right to me.

We probably ought to have a separate map for default aliases and have those be applied to everyone, keeping the map in DefaultConfig empty.

The alias code would then first look at a matching alias in the user's config and if none is found, fallback to those we have hardcoded in LXD.

**Comment by sean-jc** [comment]
@stgraber Agreed, I'll work on that approach.
