### ISSUE TITLE
Question: Setting fqdn hostname which differs from original container name

### ISSUE THREAD

**Issue by vskubriev** [lxc/lxd#1617]
Earlier I saw some docs in the internet, which talked that lxd sets hostname to container name each time container starts. I cannot find appropriate links now. It would be cool if you show me their.

Suppose I want to change fqdn hostname of running container `ldap1` from `ldap1` to `ldap`.

Earlier with hw-installed linux or lxc containers I can do this with `/etc/hosts`. I had only add one line like this:

```
192.168.1.10 ldap.example.com ldap
```

Also I could do this with properly configured dns instead of static `hosts`

But in lxd it seems not a work solution.

That is an error:

```
root@ldap1:~# hostname -f
hostname: Name or service not known
```
With lxd container this method not work.

If I want to setup different hostname like `ldap` in my case I should rename container and then I can use my old methods with custom `hosts` or setting up via dns server.

Why this happening with lxd containers?

I use init image `images:ubuntu/xenial/amd64`

**Comment by vskubriev** [comment]
Excusme, I just did a test.

I just write a new `ldap` hostname to `/etc/hostname`, reboot container and it seems to work. 

```
root@ldap:~# hostname -f
ldap.cvision.lab
```

You can close this question. Excusme for spam.

**Comment by vskubriev** [comment]
Can I override replacing /etc/hosts and /etc/hostname when I initialize a new container from my own published image ?

**Comment by stgraber** [comment]
If you're publishing your own image, you can change the templates contained in it to do whatever you want, whenever you want it.

See specs/image-handling.md in the repository.

**Comment by jgillich** [comment]
@stgraber Could this be added as described in #954? I have a case where container names are a unique numerical id, but I'd still like to set the hostname to a non-unique string value. Having to build custom images for that would be a bit silly. (I could also work on this, just interested in what your thoughts are since this used to be possible or was intended?)
