### ISSUE TITLE
`lxc exec` converts Unix line-endings to DOS line-endings

### ISSUE THREAD

**Issue by OddBloke** [lxc/lxd#1652]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 15.10
 * The output of "lxc info" or if that fails:
   * LXC version: 2.0.0~rc2-0ubuntu2~ubuntu15.10.1~ppa1
   * LXD version: 2.0.0~beta4-0ubuntu4~ubuntu15.10.1~ppa1

# Issue description

Output from commands within the container has Unix newlines replaced with DOS newlines. Compare these two outputs (noting where `hd` is run in each case):

```
$ lxc exec reproduce-20160225-114429 -- /bin/bash -c "ls -1 /root/ | hd"
00000000  61 0a 62 0a 63 0a                                 |a.b.c.|
00000006
$ lxc exec reproduce-20160225-114429 -- /bin/bash -c "ls -1 /root/" | hd
00000000  61 0d 0a 62 0d 0a 63 0d  0a                       |a..b..c..|
00000009
```

This breaks iteration over the output of `lxc exec` output in bash.

# Steps to reproduce

This script demonstrates the problem with a real-world application:

```
#!/bin/sh -eux

CONTAINER_NAME="reproduce-$(date "+%Y%m%d-%H%M%S")"

lxc launch images:ubuntu/precise/amd64 "$CONTAINER_NAME"
trap "lxc delete --force $CONTAINER_NAME" EXIT
lxc exec "$CONTAINER_NAME" -- touch /root/a /root/b /root/c
for file in $(lxc exec "$CONTAINER_NAME" -- ls /root/ | dos2unix); do
    lxc file pull "$CONTAINER_NAME/root/$file" .
done
for file in $(lxc exec "$CONTAINER_NAME" -- ls /root/); do
    lxc file pull "$CONTAINER_NAME/root/$file" .
done
```

**Comment by tych0** [comment]
Arg. I thought we fixed this a while ago :(

**Comment by tych0** [comment]
So it turns out this is "expected". When using a pts device to exec, the pts device does this \r\n replacement for us, which is kind of annoying, but it's out of LXD's control. If you close stdin, it should work as expected:

```
$ nohup lxc exec foo -- bash -c "ls -1 /root/" | hd
nohup: ignoring input and redirecting stderr to stdout
00000000  61 0a 6e 6f 68 75 70 2e  6f 75 74 0a              |a.nohup.out.|
0000000c
```

**Comment by tych0** [comment]
although it doesn't happen with ssh, which has been our model for this environment:

```
ssh home.tycho.ws "bash -c \"ls -alh /\" | head -n1" | hd
```

so maybe there is an ioctl we can use to set this behavior. I'm looking now.

**Comment by tych0** [comment]
And indeed there is, thanks!
