### ISSUE TITLE
lxd init does not write container name after upgrade

### ISSUE THREAD

**Issue by vskubriev** [lxc/lxd#1663]
lxd init does not write container name after upgrade

# Required information

 * Distribution: ubuntu
 * Distribution version: 14.04.4 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.16.0-61-generic
   * LXC version: 1.1.5-0ubuntu3~ubuntu14.04.1
   * LXD version: 2.0.0~beta4-0ubuntu5~ubuntu14.04.1
   * Storage backend in use: btrfs

# Issue description

```
skubriev@server:~/ldap/test$ lxc init ldap/image/latest
Creating the container
Container name is: skubriev@server:~/ldap/test$ 
```

Later this command prints created container name.

How to call init with config option `-c` for set container name manually ?

**Comment by stgraber** [comment]
lxc init ldap/image/latest container-name

**Comment by vskubriev** [comment]
It is to be expected )

Thank you.

But what's about --config flag use case ?

**Comment by stgraber** [comment]
--config is to override configuration keys, see specs/configuration.md

With --config you can do things like: lxc init some-image some-name -c security.nesting=true -c limits.memory=2GB -c limits.cpu=2

**Comment by vskubriev** [comment]
Good. Thank you.

How can I generate container names `apheliotropic-dannielle, conformable-maximus, etc`  like lxc init do that ?

What's lib or dictionary is used by lxd to generate this human readable hostnames?

**Comment by stgraber** [comment]
it's using the go-petname library
