### ISSUE TITLE
Cloud Image on images.linuxcontainers.org

### ISSUE THREAD

**Issue by aarnaud** [lxc/lxd#1664]
Hi,

Is it possible to have container images with the cloud-config feature on images.linuxcontainers.org ? 

Thanks

**Comment by stgraber** [comment]
I don't really see the point in duplicating those images and adding extra latency in their publishing.

lxd-images is indeed a bit of a pain to deal with right now but https://github.com/stgraber/lxd/tree/simplestreams will fix that very soon at which point LXD by default will come with two new "ubuntu" and "ubuntu-daily" remotes which will work just like images: but directly talking to the cloud images server.

**Comment by aarnaud** [comment]
Thanks,

Maybe  I do not manage to work cloud-config : "http://cloudinit.readthedocs.org/en/latest/topics/examples.html"

I want to personalize my container installation during creation.

**Comment by rdab** [comment]
Hi,

I'm using cloud-init with the images from "ubuntu" and "ubuntu-daily" remotes successfully. But I'd like to use it with other distros as well (CentOS right now). 

Do you have any idea where I can get a CentOS image with cloud-init? 

My intention is to use the same profiles to initialize users and ssh-keys in every container. If you have another approach than using cloud-init, please let me know. 

Thanks
