### ISSUE TITLE
LXD service won't start after upgrade

### ISSUE THREAD

**Issue by timtierney** [lxc/lxd#1669]
# Required information

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily

uname -a
Linux server1 4.2.0-30-generic #35-Ubuntu SMP Fri Feb 19 13:51:55 UTC 2016 i686 i686 i686 GNU/Linux

lxc version
2.0.0.beta4

lxd --version
2.0.0.beta4
```

# Issue description

After the upgrade this morning, LXD won't start with `systemctl start lxd`

# Steps to reproduce

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```

# Information to attach

[upgrade.txt](https://github.com/lxc/lxd/files/148701/upgrade.txt) - `apt-get upgrade` since 2/23 showing errors trying to start lxd after upgrade

[LXDStatus.txt](https://github.com/lxc/lxd/files/148708/LXDStatus.txt) - systemd LXD status

[journalctl.txt](https://github.com/lxc/lxd/files/148714/journalctl.txt) - `journalctl -xe -u lxd`

**Comment by pcdummy** [comment]
Please attach /var/log/lxd/lxd.log

**Comment by stgraber** [comment]
Fixed already, I messed up the init script on non-amd64.

Package is in Ubuntu now and going through testing, should hit the PPA without 3-4 hours.

**Comment by stgraber** [comment]
You can fix things by manually editing /lib/systemd/services/lxd.service, fixing the ExecStartPre line, specifically replacing the x86_64 bit by i686 (I think).

**Comment by timtierney** [comment]
Appreciate it stgraber.  So sorry to post an issue that's already been fixed.  Just for the learning experience (I'm a GitHub n00b), Is there an easy way I could have found this info out without posting an issue?  I tried to search for it but didn't know where to look on GitHub.

**Comment by stgraber** [comment]
Not really as this was a packaging bug, the PPAs are fed by the uploads to the Ubuntu main archive so you could check at https://launchpad.net/ubuntu/+source/lxd for new uploads that haven't made it to the PPA yet.

That being said, I was made aware and fixed that issue about an hour ago so you almost were the first person to report it ;)

**Comment by timtierney** [comment]
Appreciate it.  I love LXD.  Coolest project ever.  :)

**Comment by timtierney** [comment]
Your fix worked.  For future reference the filter path was: ` ExecStartPre=/usr/lib/i386-linux-gnu/lxc/lxc-apparmor-load`
