### ISSUE TITLE
beta4: no containers in list after upgrade

### ISSUE THREAD

**Issue by skyxx** [lxc/lxd#1687]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu Xenial
 * Distribution version: sever 16.04 daily
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-6-generic
   * LXC version: 2.0.0.beta4
   * LXD version: 2.0.0.beta4
   * Storage backend in use: btrfs
   * storageversion: "4.4"
   * driverversion: 2.0.0.rc4

# Issue description

After last upgrade 2.0.0.rc4 -> 2.0.0.rc4 when run LXC LIST .. i get empty list of containers.

What i see that difference after upgrade is in driverversion from 2.0.0.rc3 to 2.0.0.rc4
Its related to changes of REST API ? If yes how to upgrade containers or config.

Thanks for help.

# Information to attach

 - [ ] any relevant kernel output (dmesg)
Mar  1 13:12:54 lxd-test lxd[1021]: t=2016-03-01T13:12:54+0100 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
Mar  1 13:12:54 lxd-test lxd[1021]: t=2016-03-01T13:12:54+0100 lvl=warn msg="Error reading idmap" err="gidrange less than 65536"
Mar  1 13:12:54 lxd-test lxd[1021]: t=2016-03-01T13:12:54+0100 lvl=warn msg="Only privileged containers will be able to run"

 - [ ] main daemon log (/var/log/lxd.log)
t=2016-03-01T13:12:54+0100 lvl=info msg="LXD is starting" path=/var/lib/lxd
t=2016-03-01T13:12:54+0100 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
t=2016-03-01T13:12:54+0100 lvl=warn msg="Error reading idmap" err="gidrange less than 65536"
t=2016-03-01T13:12:54+0100 lvl=warn msg="Only privileged containers will be able to run"
t=2016-03-01T13:12:54+0100 lvl=info msg=Init driver=storage/btrfs
t=2016-03-01T13:12:54+0100 lvl=info msg="Looking for existing certificates" cert=/var/lib/lxd/server.crt key=/var/lib/lxd/server.key
t=2016-03-01T13:12:54+0100 lvl=info msg="LXD is socket activated"
t=2016-03-01T13:12:54+0100 lvl=info msg="REST API daemon:"
t=2016-03-01T13:12:54+0100 lvl=info msg=" - binding socket" socket=/var/lib/lxd/unix.socket
t=2016-03-01T13:12:54+0100 lvl=info msg=" - binding socket" socket=192.168.1.3:8443
t=2016-03-01T13:12:54+0100 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-03-01T13:12:54+0100 lvl=info msg=handling ip=@ method=GET url=/1.0
t=2016-03-01T13:14:04+0100 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-03-01T13:14:04+0100 lvl=info msg=handling ip=@ method=GET url="/1.0/containers?recursion=1"
t=2016-03-01T13:17:01+0100 lvl=info msg=handling method=GET url="/1.0/images?recursion=1" ip=@
t=2016-03-01T14:17:01+0100 lvl=info msg=handling method=GET url="/1.0/images?recursion=1" ip=@
t=2016-03-01T14:18:21+0100 lvl=info msg=handling method=GET url="/1.0/images?recursion=1" ip=@
t=2016-03-01T14:18:25+0100 lvl=info msg=handling method=GET url=/1.0 ip=@

**Comment by stgraber** [comment]
Can you attempt to run "lxc info" against one of the now missing containers?

One error that's being shown here is that your uid/gid map appears to be too small (or maybe completely missing) so LXD can't process unprivileged containers (those without security.privileged=true).
Would be useful if you could include the content of /etc/subuid and /etc/subgid.

Thanks

**Comment by skyxx** [comment]
Hi,
here are the detailed info:

**[tester@lxd-test]$ lxc info websrv**
error: LXD doesn't have a uid/gid allocation. In this mode, only privileged containers are supported.

**[tester@lxd-test]$ cat /etc/subuid**
systemd-timesync:100000:65536
systemd-network:165536:65536
systemd-resolve:231072:65536
systemd-bus-proxy:296608:65536
_apt:362144:65536
syslog:427680:65536
messagebus:493216:65536
uuidd:558752:65536
sshd:624288:65536
tester:689824:65536
dnsmasq:755360:65536
lxc-dnsmasq:820896:65536
lxd:886432:65536
lxd:951968:65536
root:951968:65536
statd:1017504:65536

**[tester@lxd-test]$ cat /etc/subgid**
root:1100:1
systemd-timesync:100000:65536
systemd-network:165536:65536
systemd-resolve:231072:65536
systemd-bus-proxy:296608:65536
_apt:362144:65536
syslog:427680:65536
messagebus:493216:65536
uuidd:558752:65536
sshd:624288:65536
tester:689824:65536
dnsmasq:755360:65536
lxc-dnsmasq:820896:65536
lxd:886432:65536
lxd:951968:65536
root:951968:65536
statd:1017504:65536


I dont make any system changes manualy. With lxd upgrade i update some sytem packages.

The following packages will be upgraded:
  byobu gcc-5-base gcc-6-base isc-dhcp-client isc-dhcp-common language-pack-en language-selector-common less libgcc1 liblxc1 libpam-systemd libpcre3 libstdc++6 libsystemd0 libudev1 lxc lxc-common
  lxc-templates lxc1 lxd lxd-client lxd-tools popularity-contest python3-lxc resolvconf systemd systemd-sysv ucf udev
29 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

**Comment by stgraber** [comment]
@hallyn any idea? looks to me like he has enough uids and gids available so why is he getting "gidrange less than 65536"?

**Comment by hallyn** [comment]
I assume it's bc the first entry is root:1100:1, and lxd bailing out after the first entry?

**Comment by hallyn** [comment]
Indeed adding such an entry at the front of my subgid file gives me the same result.  Working on a patch.

**Comment by stgraber** [comment]
oh, I guess the root:1100:1 was a failed attempt at mapping a given uid into the container or something along those lines.

**Comment by stgraber** [comment]
Anyway, patch looks good, will merge once Jenkins is happy.

**Comment by skyxx** [comment]
Thanks guys. Great work.

**Comment by stgraber** [comment]
Looks good to me, lets see if Jenkins agrees.

jenkins: test this please
