### ISSUE TITLE
lxc stop host1: fails with bad error message

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#1689]
```
$ lxc stop host1:
error: unexpected end of JSON input
```

I didn't supply a container name here, so I'd expect either "not found" or "you didn't supply a container name dumbass" :)

**Comment by tych0** [comment]
Happy to fix this myself, just in the middle of something else right now, filing it so i won't forget.

**Comment by stgraber** [comment]
Here I'm getting:

    error: json: cannot unmarshal array into Go value of type shared.ContainerInfo

Anyway, that's still wrong and yeah, the client should know better :)

I expect this to be a client-only bug as the server will just 404 when you try to reach /containers//state
