### ISSUE TITLE
2.0.0~rc1-0ubuntu2~ubuntu14.04.1~ppa1 reports itself as 2.0.0.beta4

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1698]
I just upgraded my Trusty VM to the latest version of LXD in the PPA. However:

$ dpkg -l lxd
... 2.0.0~rc1-0ubuntu2~ubuntu14.04.1~ppa1 ...
$ lxd --version
2.0.0.beta4

**Comment by aarnaud** [comment]
Same for me

**Comment by marcoroest87** [comment]
Here as well:
$ dpkg -l lxd
2.0.0~rc1-0ubuntu2~ub amd64

$ lxd --version
2.0.0.beta4

**Comment by stgraber** [comment]
Crap, I apparently messed up the upstream release tarball... it contains everything except the actual tag...

**Comment by stgraber** [comment]
So the good news is that you are absolutely running rc1, the bad news is that LXD doesn't know it is... I'll push a fix to the package right now and we'll get an rc2 out soon which will fix that for anyone else using the rc1 tarball directly...

**Comment by stgraber** [comment]
Fix uploaded to the Ubuntu archive, it's literally a one line fix to the version. It should make it to the PPA once it's done going through CI, so should be there within the next 5-6 hours.
