### ISSUE TITLE
Don't set ip_forward when no subnet is set in bridge config

### ISSUE THREAD

**Issue by OddBloke** [lxc/lxd#1699]
The lxd-bridge code enables net.ipv4.ip_forward by default. In the Ubuntu images that the Certified Public Cloud team produce for Google Compute Engine, we explicitly disable net.ipv4.ip_forward, which is overriden when lxd-bridge starts up. As such, automatically enabling it has a (minor) security surface, as it breaks our user's expectations.

We would like it if you would move away from automatically enabling it in the future.

**Comment by OddBloke** [comment]
N.B. stgraber has already told me that this is the plan (when moving to lxdbr0 instead of lxcbr0), but I wanted an open bug so that (a) it doesn't get lost in the shuffle, and (b) I have something that I can point GCE folks at.

**Comment by stgraber** [comment]
Updating the issue for the part that's actually relevant to LXD upstream.

The rest of the bridge stuff is a distro specific thing which isn't done by LXD upstream.
