### ISSUE TITLE
lxd init fails when not run as root

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#1700]
```
/home/ubuntu/packages/go/bin/lxd init --auto --storage-backend zfs --storage-pool lxd --storage-create-loop 5
error: Failed to open /var/lib/lxd/zfs.img: open /var/lib/lxd/zfs.img: permission denied
```

I thought we used to have an "are we root check" in LXD, as I think every command needs to be run as root. Perhaps we should add one.

**Comment by stgraber** [comment]
Hmm, yeah, directory backend configuration can work as a non-root user, but it's probably best to restrict the whole thing to root. I'll take care of it.
