### ISSUE TITLE
can't `lxc init` on a remote host

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#1701]
```
$ lxc remote list | grep host1
| host1           | https://192.168.122.135:8443             | lxd           | NO     | NO     |
$ lxc init xenial host1:unpriv
Creating unpriv
error: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: connection refused
```

It tries to talk to my local host, which doesn't have a LXD.

**Comment by stgraber** [comment]
That's normal, you're telling LXD to start the image "xenial" from the local: remote as "unpriv" on "host1".

I suspect you instead wanted "lxc init xenial:unpriv host1:unprix"

**Comment by tych0** [comment]
Ah, I guess you meant `lxc init host1:xenial host1:unpriv`, but yep, that works thanks.

**Comment by stgraber** [comment]
Oh yeah, sorry, I did :)
