### ISSUE TITLE
Support for partial container names in lxc

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#171]

**Comment by stgraber** [comment]
When specifying container names, the user should only have to type as many characters as required to uniquely identify it.

That is, if I have a container called "test" and no other containers, doing "lxc exec t" should work.

**Comment by hallyn** [comment]
Hm.  So we can't do it on the server bc that would involve redirection of /1.0/containers/t -> /1.0/conainers/<uuid-of-test1>.

Do we want this to work like tab-completion (perhaps just done through bash using 'lxc list' to get the list)?  Or do we want it to be more like old vax/vms, where you really type "lxc exec t\n" and the client decides whta container that expands to?

**Comment by stgraber** [comment]
I'd be fine with a good bash completion profile for the container names at least.

Having short aliases for the command names or being able to just type part of them would be convenient too.

**Comment by techtonik** [comment]
This seems to be fixed.
```
$ lxc image list 
+--------+--------------+--------+------------------------------------+--------+-------------------------------+
| ALIAS  | FINGERPRINT  | PUBLIC |            DESCRIPTION             |  ARCH  |          UPLOAD DATE          |
+--------+--------------+--------+------------------------------------+--------+-------------------------------+
| ubuntu | 1abfe3caf99d | no     | Ubuntu 14.04 LTS server (20150818) | x86_64 | Aug 20, 2015 at 11:59pm (MSK) |
+--------+--------------+--------+------------------------------------+--------+-------------------------------+
$ lxc image show 1ab
architecture: x86_64
description: Ubuntu 14.04 LTS server (20150818)
os: ubuntu
release: trusty
```

**Comment by stgraber** [comment]
We do have a bash completion profile right now and for images, partial hashes are supported, so yeah, this should be good enough.

**Comment by techtonik** [comment]
Which milestone?

**Comment by stgraber** [comment]
bash completion was done months ago, don't know when exactly.
