### ISSUE TITLE
host dns resolution is not working

### ISSUE THREAD

**Issue by giminni** [lxc/lxd#1713]
# Required information
 * Distribution: Ubuntu
 * Distribution version: 14.04.4 LTS
 * The output of "lxc info":
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  certificate: |
  driver: lxc
  driverversion: 2.0.0.rc5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-30-generic
  server: lxd
  serverpid: 1125
  serverversion: 2.0.0.rc1
  storage: btrfs
  storageversion: "4.0"
config: {}
public: false

# Issue description
Enabling lxc domain to lxc-dnsmasq and installing a host dnsmasq I could not resolve
the container by name

# Steps to reproduce
- Enabled LXC_DOMAIN in /etc/default/lxc-net
- Added server=/lxc/10.0.3.1 to /etc/dnsmasq.d/lxc
- Installed a host dnsmasq
- Rebooted lxd host 

# Information to attach
- ps info about running lxc & host dnsmasq
1) dnsmasq -s lxc -S /lxc/ -u lxc-dnsmasq --strict-order -bind-interfaces --pid-file=/run/lxc/dnsmasq.pid --listen-address 10.0.3.1 --dhcp-range 10.0.3.2,10.0.3.254 --dhcp-lease-max=253 --dhcp-no-override --except-interface=lo --interface=lxcbr0 --dhcp-leasefile=/var/lib/misc/dnsmasq.lxcbr0.lease --dhcp-authoritative

2) /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnmasq -r /var/run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new,.cur,.org

- DNS container resolution error on host
user@lxchost:/$ nslookup alps02 10.0.3.1
Server:		10.0.3.1
Address:	10.0.3.1#53

** server can't find alps02: NXDOMAIN

`+--------+---------+-------------------+------+------------+-----------+`
`|  NAME  |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |`
`+--------+---------+-------------------+------+------------+-----------+`
`| alps00 | STOPPED |                   |      | PERSISTENT | 0         |`
`+--------+---------+-------------------+------+------------+-----------+`
`| alps01 | RUNNING | 10.0.3.x (eth0)  |      | PERSISTENT | 1         |`
`+--------+---------+-------------------+------+------------+-----------+`
`| alps02 | RUNNING | 10.0.3.y (eth0) |      | PERSISTENT | 0         |`
`+--------+---------+-------------------+------+------------+-----------+`

**Comment by stgraber** [comment]
This isn't going to be a LXD issue as LXD doesn't do any bridge, dnsmasq or network configuration at all.

I'd suggest making sure that the hostnames are correct in /var/lib/misc/dnsmasq.lxcbr0.leases

**Comment by giminni** [comment]
@stgraber: You point me to the right direction, and yes the problem is outside lxd.

I am trying to get alpine linux running on lxd. Everything looks apparently good, only the busybox implementation of udhcpc is buggy no hostname is set and therefore I get a star. This
prevents indeed naming resolution.

I got rid of this nasty behavior by adding in /usr/lib/x86_64-linux-gnu/lxc/lxc-net an option --dhcp-script=<....>  to trigger insertion and removal of hosts and change /etc/hosts accordingly.

If someone has a better implementation, feel free to enlighten me.

**Comment by IshwarKanse** [comment]
@giminni Can you try with the image built using the following script for Alpine.
https://github.com/saghul/lxd-alpine-builder

**Comment by giminni** [comment]
@IshwarKanse thx for this info, yes I use the script and it works like a charm, my dns problem was solved by myself. Here my findings:
- busybox dhcp client implementation inside alpine linux is buggy, I installed dhcpcd from alpine repo and it works as expected I get now an hostname inside my dhcp lease file.
- Using a system dnsmasq on the lxd-host is not so trivial as I imagined, 
I made the lxc-dnsmasq dumb (no-host, no-resolv) 
added some useful options (expand-hosts, domain-needed, bogus-priv)
and even dns nameserver that are added automatically inside the lxc container
(lxc-net-dns, lxd-host-dns, area-dns)
the second dns server running on the lxd host has specific dns routes like:
server=/lxc/10.0.3.1
server=/3.0.10.in-addr.arpa/10.0.3.1

At the end every thing works fine being able to work with forward and reverse dns resolution
