### ISSUE TITLE
apicompat mismatch between snappy-lxd and ubuntu-lxd

### ISSUE THREAD

**Issue by giminni** [lxc/lxd#1717]
I am trying to add a remote ubuntu-lxd server from a snappy-lxd system. 
snappy-lxd has api 1.0 and ubuntu-lxd has api 0

**I get the error: Response was missing `api_compat`**

Am I doing something wrong?

Here my snappy-lxd info:
apicompat: 1
auth: trusted
environment:
  addresses: []
  architectures:
  `- 2`
  `- 1`
  driver: lxc
  driverversion: 1.1.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.19.0-51-generic
  server: lxd
  serverpid: 945
  serverversion: "0.21"
  storage: dir
  storageversion: ""
config:
  images.remote_cache_expiry: "10"
public: false

ubuntu-lxd info:
apicompat: 0
auth: trusted
environment:
  addresses: 
  `- <local-address>:8443`
  architectures:
  certificate: |
  driver: lxc
  driverversion: 2.0.0.rc5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-30-generic
  server: lxd
  serverpid: 1125
  serverversion: 2.0.0.rc1
  storage: btrfs
  storageversion: "4.0" 
config: 
  core.https_address: <local-address>:8443
  core.trust_password: true
public: false

**Comment by stgraber** [comment]
Yeah, LXD in snappy is completely out of date and unsupported at this stage.

**Comment by giminni** [comment]
Does it mean the snappy-lxd project is abandoned, or is there any roadmap to merge LXC 2.0 into it?

**Comment by stgraber** [comment]
Snappy itself has been changing too much lately for us to be able to build newer versions of the snap without investing significant efforts into it.

We still intend to get a working LXD snap for 16.04 but it's not a priority for us right now, getting LXD 2.0 out the door is.

**Comment by stgraber** [comment]
Going to close this issue as there is no actual LXD bug for us to fix.

Packaging is tracked in the lxc/lxd-pkg-ubuntu repository, including the snappy stuff.
