### ISSUE TITLE
PPA repository update (2.0.0.rc2)

### ISSUE THREAD

**Issue by aarnaud** [lxc/lxd#1719]
Hi,

The PPA repository is not update to lxd 2.0.0.rc2.  it's normal?

https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxd-stable

Thanks,

**Comment by stgraber** [comment]
Yep, rc2 is still not in the Ubuntu archive. It was uploaded yesterday but there is a massive backlog in Ubuntu CI right now so it hasn't run its test yet.

**Comment by aarnaud** [comment]
thanks for this information and for your quickly answer ;-)
