### ISSUE TITLE
Inaccurate error message when snapshotting container with existing snapshot name

### ISSUE THREAD

**Issue by jsavikko** [lxc/lxd#1725]
When snapshotting container using existing snapshot name the error message displayed is inaccurate. Now the error message is "The container already exists" even though I am trying to create a snapshot, not a container. It is also possible to have snapshots named after containers (container foo with snapshot bar, see steps to reproduce), so for this reason too the error message is misleading.

I propose that the error message is modified to print "error: Snapshot 'wily/bar' already exists" or similar indicating the name of the container snapshotted and the name of the existing (duplicate) snapshot.

If above mentioned error message is deemed appropriate (or some other is more fitting), I can implement the modifications to lxd/container.go#L597 and create a PR.

# Steps to reproduce

 1. lxc launch ubuntu:wily foo
 2. lxc launch ubuntu:wily bar
 3. lxc snapshot foo bar
 5. lxc snapshot foo bar

**Comment by tych0** [comment]
Sure, that sounds reasonable. A PR would be great, thanks!

**Comment by jsavikko** [comment]
Fixed in 58835f9
