### ISSUE TITLE
Launching a container hangs. Removing binfmt_misc from /lib/init/fstab and restarting container allow it to start

### ISSUE THREAD

**Issue by jrwren** [lxc/lxd#1727]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu 
 * Distribution version: wily
 * The output of "lxc info" or if that fails:
apicompat: 0
auth: trusted
environment:
  addresses:
  - 68.40.59.93:8443
  - 192.168.15.101:8443
  - '[2601:400:8000:341a:21f:d0ff:fe85:d98b]:8443'
  - 192.168.122.1:8443
  - 10.0.3.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |...
  driver: lxc
  driverversion: 2.0.0.rc5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.19.0-23-generic
  server: lxd
  serverpid: 20408
  serverversion: 2.0.0.rc2
  storage: btrfs
  storageversion: "4.0"
config:
  core.https_address: '[::]'
public: false

# Issue description

    $ lxc launch ubuntu-trusty test

The test container does not listen on ssh, even after waiting a while.

# Steps to reproduce

    $ lxc launch ubuntu-trusty test  #  The instance never starts ssh.
    $ lxc exec test ps -ef   #  Shows not much is running, mountall --daemon is still running
    $ lxc exec test bash 
    # mountall -v   #  shows some binfmt mounts, but the stops and hangs.
    
# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)

            lxc 20160309111449.246 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160309111449.246 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160309111450.792 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160309111450.792 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160309111450.841 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160309111450.841 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 8
            lxc 20160309111450.844 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /var/lib/lxd/containers test
            lxc 20160309111450.845 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 8
            lxc 20160309111450.845 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for reject_force_umount action 0
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for reject_force_umount action 0
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .[all].
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .kexec_load errno 1.
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for kexec_load action 327681
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for kexec_load action 327681
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .open_by_handle_at errno 1.
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for open_by_handle_at action 327681
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for open_by_handle_at action 327681
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .init_module errno 1.
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for init_module action 327681
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for init_module action 327681
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .finit_module errno 1.
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for finit_module action 327681
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for finit_module action 327681
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .delete_module errno 1.
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for delete_module action 327681
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for delete_module action 327681
            lxc 20160309111450.845 INFO     lxc_seccomp - seccomp.c:parse_config_v2:456 - Merging in the compat seccomp ctx into the main one
            lxc 20160309111450.845 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 507 start' for container 'test', config se
            lxc 20160309111450.845 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160309111450.845 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 8
            lxc 20160309111450.847 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/d78a9d7e97b4b375//var/lib/lxd/containers
            lxc 20160309111450.932 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160309111450.932 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160309111450.934 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
            lxc 20160309111450.934 DEBUG    lxc_console - console.c:lxc_console_peer_default:473 - no console peer
            lxc 20160309111450.934 INFO     lxc_start - start.c:lxc_init:488 - 'test' is initialized
            lxc 20160309111450.935 DEBUG    lxc_start - start.c:__lxc_start:1259 - Not dropping cap_sys_boot or watching utmp
            lxc 20160309111450.938 INFO     lxc_start - start.c:resolve_clone_flags:956 - Cloning a new user namespace
            lxc 20160309111450.942 DEBUG    lxc_conf - conf.c:instantiate_veth:2609 - instantiated veth 'vethIFIGVT/vethL75XB4', index is '1460'
            lxc 20160309111450.942 INFO     lxc_cgroup - cgroup.c:cgroup_init:65 - cgroup driver cgroupfs initing for test
            lxc 20160309111451.010 DEBUG    lxc_conf - conf.c:lxc_assign_network:3043 - move 'eth0' to '15605'
            lxc 20160309111451.018 NOTICE   lxc_start - start.c:do_start:761 - switching to gid/uid 0/0 in new user namespace
            lxc 20160309111451.022 DEBUG    lxc_conf - conf.c:setup_rootfs:1210 - mounted '/var/lib/lxd/containers/test/rootfs' on '/usr/lib/x86_64-linux-gnu/lxc'
            lxc 20160309111451.022 INFO     lxc_conf - conf.c:setup_utsname:842 - 'test' hostname has been setup
            lxc 20160309111451.028 DEBUG    lxc_conf - conf.c:setup_hw_addr:2140 - mac address '00:16:3e:c4:e5:d8' on 'eth0' has been setup
            lxc 20160309111451.028 DEBUG    lxc_conf - conf.c:setup_netdev:2367 - 'eth0' has been setup
            lxc 20160309111451.028 INFO     lxc_conf - conf.c:setup_network:2388 - network has been setup
            lxc 20160309111451.028 INFO     lxc_conf - conf.c:mount_autodev:1071 - Mounting container /dev
            lxc 20160309111451.029 INFO     lxc_conf - conf.c:mount_autodev:1094 - Mounted tmpfs onto /usr/lib/x86_64-linux-gnu/lxc/dev
            lxc 20160309111451.029 INFO     lxc_conf - conf.c:mount_autodev:1112 - Mounted container /dev
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1703 - mounted 'mqueue' on '/usr/lib/x86_64-linux-gnu/lxc/dev/mqueue', type 'mqueue'
            lxc 20160309111451.029 ERROR    lxc_utils - utils.c:safe_mount:1691 - Too many levels of symbolic links - Failed to mount /proc/sys/fs/binfmt_misc onto /usr/lib/x86_64
            lxc 20160309111451.029 INFO     lxc_conf - conf.c:mount_entry:1642 - failed to mount '/proc/sys/fs/binfmt_misc' on '/usr/lib/x86_64-linux-gnu/lxc/proc/sys/fs/binfmt_mi
            lxc 20160309111451.029 ERROR    lxc_utils - utils.c:open_without_symlink:1625 - No such file or directory - Error examining efi in /usr/lib/x86_64-linux-gnu/lxc/sys/fi
            lxc 20160309111451.029 INFO     lxc_conf - conf.c:mount_entry:1642 - failed to mount '/sys/firmware/efi/efivars' on '/usr/lib/x86_64-linux-gnu/lxc/sys/firmware/efi/efi
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1653 - remounting /sys/fs/fuse/connections on /usr/lib/x86_64-linux-gnu/lxc/sys/fs/fuse/connections to re
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1668 - (at remount) flags for /sys/fs/fuse/connections was 4096, required extra flags are 0
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1677 - mountflags already was 20480, skipping remount
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1703 - mounted '/sys/fs/fuse/connections' on '/usr/lib/x86_64-linux-gnu/lxc/sys/fs/fuse/connections', typ
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1653 - remounting /sys/fs/pstore on /usr/lib/x86_64-linux-gnu/lxc/sys/fs/pstore to respect bind or remoun
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1668 - (at remount) flags for /sys/fs/pstore was 4110, required extra flags are 14
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1703 - mounted '/sys/fs/pstore' on '/usr/lib/x86_64-linux-gnu/lxc/sys/fs/pstore', type 'none'
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1653 - remounting /sys/kernel/debug on /usr/lib/x86_64-linux-gnu/lxc/sys/kernel/debug to respect bind or
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1668 - (at remount) flags for /sys/kernel/debug was 4110, required extra flags are 14
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1703 - mounted '/sys/kernel/debug' on '/usr/lib/x86_64-linux-gnu/lxc/sys/kernel/debug', type 'none'
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1653 - remounting /sys/kernel/security on /usr/lib/x86_64-linux-gnu/lxc/sys/kernel/security to respect bi
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1668 - (at remount) flags for /sys/kernel/security was 4110, required extra flags are 14
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1703 - mounted '/sys/kernel/security' on '/usr/lib/x86_64-linux-gnu/lxc/sys/kernel/security', type 'none'
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1653 - remounting /var/lib/lxd/devlxd on /usr/lib/x86_64-linux-gnu/lxc/dev/lxd to respect bind or remount
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1668 - (at remount) flags for /var/lib/lxd/devlxd was 4096, required extra flags are 0
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1677 - mountflags already was 4096, skipping remount
            lxc 20160309111451.029 DEBUG    lxc_conf - conf.c:mount_entry:1703 - mounted '/var/lib/lxd/devlxd' on '/usr/lib/x86_64-linux-gnu/lxc/dev/lxd', type 'none'
            lxc 20160309111451.030 DEBUG    lxc_conf - conf.c:mount_entry:1653 - remounting /var/lib/lxd/shmounts/test on /usr/lib/x86_64-linux-gnu/lxc/dev/.lxd-mounts to respect
            lxc 20160309111451.030 DEBUG    lxc_conf - conf.c:mount_entry:1668 - (at remount) flags for /var/lib/lxd/shmounts/test was 4096, required extra flags are 0
            lxc 20160309111451.030 DEBUG    lxc_conf - conf.c:mount_entry:1677 - mountflags already was 4096, skipping remount
            lxc 20160309111451.030 DEBUG    lxc_conf - conf.c:mount_entry:1703 - mounted '/var/lib/lxd/shmounts/test' on '/usr/lib/x86_64-linux-gnu/lxc/dev/.lxd-mounts', type 'non
            lxc 20160309111451.030 INFO     lxc_conf - conf.c:mount_file_entries:1922 - mount points have been setup
            lxc 20160309111451.031 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.mount.hook' for container 'test', config section 'lxc'
            lxc 20160309111451.068 INFO     lxc_conf - conf.c:fill_autodev:1140 - Creating initial consoles under container /dev
            lxc 20160309111451.068 INFO     lxc_conf - conf.c:fill_autodev:1151 - Populating container /dev
            lxc 20160309111451.068 INFO     lxc_conf - conf.c:fill_autodev:1184 - Populated container /dev
            lxc 20160309111451.068 INFO     lxc_conf - conf.c:setup_dev_console:1433 - console has been setup
            lxc 20160309111451.068 INFO     lxc_utils - utils.c:mount_proc_if_needed:1725 - I am 1, /proc/self points to '1'
            lxc 20160309161451.076 DEBUG    lxc_conf - conf.c:setup_rootfs_pivot_root:1049 - pivot_root syscall to '/usr/lib/x86_64-linux-gnu/lxc' successful
            lxc 20160309161451.076 INFO     lxc_conf - conf.c:setup_tty:994 - 0 tty(s) has been setup
            lxc 20160309161451.076 INFO     lxc_conf - conf.c:setup_personality:1388 - set personality to '0x0'
            lxc 20160309161451.076 DEBUG    lxc_conf - conf.c:setup_caps:2051 - drop capability 'mac_admin' (33)
            lxc 20160309161451.076 DEBUG    lxc_conf - conf.c:setup_caps:2051 - drop capability 'mac_override' (32)
            lxc 20160309161451.076 DEBUG    lxc_conf - conf.c:setup_caps:2051 - drop capability 'sys_time' (25)
            lxc 20160309161451.076 DEBUG    lxc_conf - conf.c:setup_caps:2051 - drop capability 'sys_module' (16)
            lxc 20160309161451.076 DEBUG    lxc_conf - conf.c:setup_caps:2060 - capabilities have been setup
            lxc 20160309161451.076 NOTICE   lxc_conf - conf.c:lxc_setup:3832 - 'test' is setup.
            lxc 20160309161451.076 INFO     lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:238 - changed apparmor profile to lxd-test_</var/lib/lxd>
            lxc 20160309161451.076 NOTICE   lxc_start - start.c:start:1368 - exec'ing '/sbin/init'
            lxc 20160309111451.079 NOTICE   lxc_start - start.c:post_start:1379 - '/sbin/init' started with pid '15605'
            lxc 20160309111451.079 WARN     lxc_start - start.c:signal_handler:337 - invalid pid for SIGCHLD

 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by jrwren** [comment]
Looks like this is not a bug with lxd.

I restarted binfmt manually by running:

    sudo /usr/sbin/update-binfmts --disable
    sudo /usr/sbin/update-binfmts --enable

I think using systemd to do this would have also worked:

    sudo service binfmt-support restart

Hopefully this being documented will help others.

**Comment by stgraber** [comment]
Yeah, the directory being a broken autofs causing a symlink loop is clearly a problem here. I've seen this once but never was able to reproduce.

Can you please file a bug against systemd at https://launchpad.net/ubuntu/+source/systemd and subscribe ~ubuntu-lxc to it so we can help the systemd maintainer fix this ASAP?

Thanks

And closing this issue as there's nothing we can do about this from a LXD point of view...

**Comment by jrwren** [comment]
If others run into this issue it is being tracked here: https://bugs.launchpad.net/ubuntu/+source/binfmt-support/+bug/1555760
