### ISSUE TITLE
lxc client on 2.0.0rc2 crashes when trying to list a remote lxd server on version 0.21 - 0.25

### ISSUE THREAD

**Issue by basvanbeek** [lxc/lxd#1728]
We have various LXD / LXC servers and clients running but notice a breaking change between remote connections since we have updated some of our systems to 2.0.0rc2.

new lxc client refuses to install remote server certificate with older servers on 0.21 / 0.25
new lxc client crashes with nil pointer dereference with older servers on 0.21 / 0.25 (after manual install certificate)
old lxc client shows empty rows when listing newer servers on 2.0.0.rc2

we'd like to move all to 2.0.0rc2 but one of our host servers is running snappy and that is still at 0.21 as latest available version.

**Comment by stgraber** [comment]
LXD doesn't guarantee any API stability until 2.0 final is out.

We've done a number of big API changes around beta4 and rc1 that indeed makes recent LXD incompatible with older versions.

Once 2.0 is out, we'll consider the 1.0 REST API as stable and will not be making any backward incompatible change, only additions combined with a new feature flag will be allowed.

I'm closing this issue as it's not something we're going to fix, we just expect everyone to upgrade at this point.

We will eventually find time to update the snappy version of LXD but that's proven way more difficult than expected...
