### ISSUE TITLE
Container stalled at start/stop action

### ISSUE THREAD

**Issue by rchincholkar** [lxc/lxd#1731]
Hi team,
Thanks for introducing LXD, its awesome since we are migrated from docker to LXD.
We are using LXD in production since Nov, 2015 ( now we are on lxd 2.0.0.beta4). 

 * Distribution: Ubuntu 14.04.4 LTS
 * The output of "lxc info" : 
$ lxc info
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.0.rc5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.16.0-62-generic
  server: lxd
  serverpid: 1279
  serverversion: 2.0.0.beta4
  storage: btrfs
  storageversion: "3.12"
config: {}
public: false

   * Kernel version: 3.16.0-62-generic
   * LXC version: 2.0.0.beta4
   * LXD version: 2.0.0.beta4
   * Storage backend in use: btrfs

# Issue description

It was running good before upgrade, now we are facing issues like container doesn't start/stop and the process keeps hanging at terminal with no output.
In ps output we observed that ther start stop process for containers went into Sl+ state and kept running for hours without any output/error. 

# Steps to reproduce
We are unable to reproduce as it is happening randomly.

**Comment by stgraber** [comment]
You are quite a bit behind in both LXD and LXC versions, could you try updating your system?

You should be getting LXD 2.0.0 rc2 and LXC 2.0.0 rc9 instead of your current beta4 and rc5.

**Comment by rchincholkar** [comment]
Thanks for your quick response @stgraber .
Yeah, I will upgrade it today and will observe.
and let you guys know if faced same issue.. :)

**Comment by rchincholkar** [comment]
Hello team,
After upgrading lxd, the issue is not observed since long.
The upgrade was helpful in my case.
Thanks!

**Comment by stgraber** [comment]
Perfect, closing this then.
