### ISSUE TITLE
cannot upgrade from localhost to [::] on the same port

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1732]
# Required information

 * Distribution: trusty
 * Distribution version: 14.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.13.0-79-generic
   * LXC version: 2.0.0.rc2
   * LXD version: 2.0.0.rc9
   * Storage backend in use: zfs

# Issue description

I ran "sudo lxd init" to configure lxd to listen on "localhost:8443".  
I then wanted to change it so that it listens to all addresses, so I did:
 lxc config set core.https_address "[::]:8443"

It fails with 
  error: cannot listen on https socket: listen tcp [::]:8443: bind: address already in use

The problem is that it is LXD itself that is listening on that port. I'm not sure what a possible fix is, or what the best workaround would be.

We need something like this in Juju, because we want to ensure that the LXD agent is available for the Juju API server (running in a container) to talk to.

**Comment by stgraber** [comment]
Does unsetting it and setting it again work?

lxc config unset core.https_address
lxc config set core.https_address "[::]:8443"

**Comment by jameinel** [comment]
no. because "unset core.https_address" does not stop the agent from listening. Probably related to issue #1733 .
If I do:
lxc config set core.https_address localhost:8443
I then can load the "https://localhost:8443" URL.
I then do:
 lxc config unset core.https_address
I can see that it isn't there in
 lxc config show
However, I can still load "https://localhost:8443".
If I do:
lxc config unset core.https_address
sudo service lxd restart
lxc config set core.https_address [::]:8443

Then it works as expected.

**Comment by stgraber** [comment]
```
stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc config set core.https_address "127.0.0.1:8443"

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ netstat -lnp | grep 8443
tcp        0      0 127.0.0.1:8443          0.0.0.0:*               LISTEN      -               

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc config unset core.https_address

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ netstat -lnp | grep 8443

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc config set core.https_address "[::]:8443"

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ netstat -lnp | grep 8443
tcp6       0      0 :::8443                 :::*                    LISTEN      -               
```

**Comment by stgraber** [comment]
without ever restarting the daemon

**Comment by stgraber** [comment]
So this is certainly supposed to work, and at least here, does appear to work. Though I do run in similar problems when doing a straight configuration replace. I'll look into the code some more tomorrow.

We may be missing a case or there may be a race condition when we have existing open connections.

**Comment by jameinel** [comment]
This is not what I see when doing the same test:
After he "lxc config unset core.https_address"
net stat still reports the port as open.
It continues to report it as open about 1 minute later.

This is on Trusty running the lastest lxd from the ppa.
2.0.0~rc2-0ubuntu3~ubuntu14.04.1~ppa1

**Comment by jameinel** [comment]
I see the same behavior (lxd has not stopped listening on 8443) with the latest packages on Xenial lxd = 2.0.0~rc2-0ubuntu3 and lxc = 2.0.0~rc9-0ubuntu1

**Comment by stgraber** [comment]
Are you trying with localhost or 127.0.0.1? It looks like we have a problem in our logic to catch names vs IPs.

**Comment by jameinel** [comment]
Starting from scratch:
$ sudo service lxd restart
$ netstat -lnp | grep 8443
(intentionally left blank)
$ lxc config set core.https_address 127.0.0.1:8443
$ netstat -lnp | grep 8443
tcp  0 0 127.0.0.1:8443 0.0.0.0:* LISTEN -
$ lxc config unset core.https_address
$ netstat -lnp | grep 8443
(intentionally left blank)
$ lxc config set core.https_address localhost:8443
$ netstat -lnp | grep 8443
tcp  0 0 127.0.0.1:8443 0.0.0.0:* LISTEN -
$ lxc config unset core.https_address
$ netstat -lnp | grep 8443
tcp  0 0 127.0.0.1:8443 0.0.0.0:* LISTEN -


So, indeed. If you set it to listen on "localhost" then it fails to stop listening when you unset the field. But if you set it to 127.0.0.1:8443 then it stops listening correctly.
