### ISSUE TITLE
using lxd init to stop listening publicly does not stop listening on the port

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1733]
# Required information

 * Distribution: trusty
 * Distribution version: 14.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.13.0-79-generic
   * LXC version: 2.0.0.rc2
   * LXD version: 2.0.0.rc9
   * Storage backend in use: zfs

# Issue description

1. lxd init --network-address localhost --network-port 8443
2. lxd init (say no to publicly exposing lxd)
  2a. I can still go to https://localhost:8443 and see that LXD is responding there
  2b. 'lxc config show' shows me that there is no https_address configured
3. lxd init --network-address [::] --network-port 8443
 fails saying port is already in use

That means that step (2) did not actually stop listening on the https port. Bouncing the service (sudo service lxd restart) did. But it seems that whatever "lxd init" is doing, it isn't causing the service to notice the new configuration.

**Comment by stgraber** [comment]
Same as #1732
