### ISSUE TITLE
Allow running "lxd init" on an already configured LXD daemon

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1734]
# Issue description

$ lxd --version
2.0.0.rc2
$ lxc --version
2.0.0.rc2

I was trying to investigate issue #1733, and just wanted to use "lxd init" to fix what lxd was listening to. I ran: sudo lxd init --network-address localhost --network-port 8443
And it failed with:
  error: You have existing containers or images. lxd init requires an empty LXD

I realize that I can use "lxc config set" to do something similar, but it seems like the "existing containers" check only applies if I'm changing the storage information.

**Comment by stgraber** [comment]
@brauner we should be able to fix that one now that we have the storage branch merged.
