### ISSUE TITLE
lxd init ignores CLI parameters if not fully specified

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1735]
$ lxd --version
2.0.0.rc2

I just wanted to change --network-port and --network-address, so I ran
sudo lxd init --network-address localhost --network-port 8443
But then lxd init immediately prompted me to configure the storage backend, and *then* asked me questions about whether I want LXD to be available over the network, and what ports it should listen to. Which I had *just* supplied on the CLI.

This may be the root of issue #1734 because 'lxd init' always configures everything. Ideally you could only specify the portion of the configuration you want to change, and lxd init would apply just that.

**Comment by stgraber** [comment]
The command line arguments are only used in auto mode, they are otherwise ignored.
