### ISSUE TITLE
lxd.NewClient(&lxd.DefaultConfig, "ubuntu") creates "client.crt" and "client.key" in local dir

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1738]
In commit: 45d6b5a766b34027528fae259d5c247e7f138e8e

Tycho gave us a nice patch to connect directly to cloud-images.ubuntu.com during "juju bootstrap" of the lxd provider. However it turns out that 
	client, err := lxd.NewClient(&lxd.DefaultConfig, "ubuntu")
Ends up creating a client.crt and client.key in $PWD. Even though it doesn't need a client certificate at all to connect to Ubuntu, and it certainly shouldn't be in $PWD.
My patch that changes NewClientFromInfo can work around this because it can pass in anything that we might need (it *might* still create crt files if you don't pass them in? I'm not sure about that).

See https://pad.lv/1555585 for the Juju side of this bug.

You can run the attached file with "go run ./mytest.go" (after renaming it from .txt cause github doesn't support .go files)
[mytest.txt](https://github.com/lxc/lxd/files/167079/mytest.txt)

**Comment by pcdummy** [comment]
this should work for you:
