### ISSUE TITLE
lxd file push gives unhelpful error when specifying a target directory without trailing slash

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#1740]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Xenial
 * The output of "lxc info" or if that fails:
% lxc info
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
<snip cert>
  driver: lxc
  driverversion: 2.0.0.rc1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-6-generic
  server: lxd
  serverpid: 27171
  serverversion: 2.0.0.rc2
  storage: zfs
  storageversion: "5"
config:
  core.trust_password: true
  storage.zfs_pool_name: lxd_zfs

# Issue description

`lxc file push <file> <container>/<dir>` returns obtuse error message and does not push the file.

This occurs when the target path in the container is an existing directory and does not have a trailing slash.  I suspect it's attempting to write to the <dir> as a file which fails.

`% lxc file push tgt_1.0.63-1ubuntu1_amd64.deb x1/tmp
error: Error calling 'lxd forkputfile /tmp/lxd_forkputfile_515851167 27315 tmp 101000 101000 436': err='exit status 255'`

If you add the trailing slash, it works fine
`% lxc file push tgt_1.0.63-1ubuntu1_amd64.deb x1/tmp/`

# Steps to reproduce

 1. `lxc launch xenial x1`
 2. `echo "hello" > hello.txt`
 3. `lxc file push hello.txt x1/tmp`

**Comment by stgraber** [comment]
Yeah, it should tell you "File already exists" or something along those lines.
