### ISSUE TITLE
Unable to install Lxd on Ubuntu Trusty

### ISSUE THREAD

**Issue by AndrewPashkin** [lxc/lxd#1743]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Clean Vagrant Ubuntu Trusty 64 image
 * Distribution version: Trusty

# Issue description
Here is what I get, trying to install Lxd:
```
$ sudo apt-get install lxd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lxd : Depends: liblxc1 (>= 1.1.0~) but it is not going to be installed
       Depends: lxc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
`apt-get update` and `apt-get dist-upgrade` were performed before that.

The problem occurs not only on Vagrant image, Vagrant is used just to get clean OS.

**Comment by stgraber** [comment]
LXD in trusty is only available through backports so you must use:

apt-get -t trusty-backports install lxd

**Comment by AndrewPashkin** [comment]
@stgraber That was fast, thank you, it works :+1:

**Comment by aarnaud** [comment]
Thanks, i have the same issue with Packer for make virtualbox image from trusty ISO.

**Comment by sforteva** [comment]
Thank you two!

**Comment by mrmuli** [comment]
thank you
