### ISSUE TITLE
parity of image sync with old lxd-image behavior

### ISSUE THREAD

**Issue by smoser** [lxc/lxd#1746]
Hey,
Its possible this is just documentation or misunderstanding of a user (me).

However, previously I would do something like this:
  `lxd-images import ubuntu --alias wily wily --stream=daily`

That did at least these things:

1. imported a new image
1. set up that thing to magically keep in sync
1. added an alias 'wily', such that subsequently this would work

   `lxc launch wily x1`

Now the command for doing something similar is:

 `lxc launch ubuntu-daily:xenial x1`

But what I'm missing is from the previous behavior is:

1. ability to request sync without launching (or even init a container).
This isn't a huge thing as I assume I can `lxc init ubuntu-daily:xenial somename` and then `lxc delete somename`, but that is less direct.

1. ability to add aliases to the magical up to date image
Essentially I want what this would seem to imply:  `lxc image alias create x ubuntu-daily:xenial `.  After the 'launch' above, i can list the image, and i could alias to the fingerprint of that image, but I assume the alias would be on the fingerprint then, and not on the more complex and mutable "latest ubuntu-daily:xenial"

**Comment by stgraber** [comment]
You want:

lxc image copy ubuntu-daily:xenial local: --alias xenial --auto-update

and

You can add aliases to the cache entries by looking up their hash in "lxc image list" and adding aliases with "lxc image alias create"

Aliases are moved forward as the image is updated so you won't loose those when we auto-update the image.

**Comment by smoser** [comment]
image copy is great. thank you.

> Aliases are moved forward as the image is updated so you won't loose those when we auto-update the image.

Is there a way to *not* have aliases moved forward?
This seems a reasonable desire:
```
   $ lxc image list xenial
   +--------+--------------+--------+--------------------------------------+--------+----------+-----------------------------+
   | ALIAS  | FINGERPRINT  | PUBLIC |             DESCRIPTION              |  ARCH  |   SIZE   |         UPLOAD DATE         |
   +--------+--------------+--------+--------------------------------------+--------+----------+-----------------------------+
   | xenial | 079a91b7443d | no     | Ubuntu 16.04 LTS server (20160308.1) | x86_64 | 139.26MB | Mar 8, 2016 at 7:38pm (UTC) |
   +--------+--------------+--------+--------------------------------------+--------+----------+-----------------------------+
   
  $ lxc image alias create xenial-20160308.1 079a91b7443d
```


Would lxc then move my alias 'xenial-20160308.1' forward the next time it syncs ?

**Comment by stgraber** [comment]
Images marked as auto-update will be replaced by their latest version whenever one shows up.

If you want to keep it around, use "lxc image edit" to turn off the auto-update flag at which point lxd will keep the image around.

You can also achieve the same by doing a "lxc image copy" without the --auto-update flag.

**Comment by smoser** [comment]
Generally, i'm really happy with this. it works really well.
I do still think its odd that above, i aliased a very specific thing (by its fingerprint).  I'd not expect that to magically move.  My use case would be wanting to generally track releases or daily, but have tests in place that manage the alias 'last-good'' or something.  So i could always launch the last tested version, but still have the automagic syncing happening for me.
