### ISSUE TITLE
Proper error message when a remote doesn't support a command

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1762]
Trusty with lxc ---version
 2.0.0.rc3

Running
 $ lxc info
Usually gives a lot of interesting information about a remote. Architectures, etc. However if you try to do info for a "simplestreams" remote it seems it is doing something wrong:
 $ lxc info ubuntu:
error: invalid character '<' looking for beginning of value

I can understand "info" not being implemented for simplestream sources, though it would be nice to at least get things like the URL of the remote. Regardless it should handle it more gracefully than "invalid character".

**Comment by stgraber** [comment]
Yeah, we need some logic to reject a whole bunch of things for public and simplestreams remote with a clear error message.

Note that info doesn't give you the URL for LXD remotes either, I suspect "lxc remote list" is what you'd want for that.
