### ISSUE TITLE
Error creating a snapshot

### ISSUE THREAD

**Issue by slava-vishnyakov** [lxc/lxd#1765]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 15.10
 * The output of "lxc info":

```sh
    apicompat: 0
    auth: trusted
    environment:
      addresses: []
      architectures:
      - x86_64
      - i686
      certificate: |
        -----BEGIN CERTIFICATE-----
        ...omitted...
        -----END CERTIFICATE-----
      driver: lxc
      driverversion: 2.0.0.rc10
      kernel: Linux
      kernelarchitecture: x86_64
      kernelversion: 4.2.0-27-generic
      server: lxd
      serverpid: 636
      serverversion: 2.0.0.rc3
      storage: dir
      storageversion: ""
    config: {}
    public: false
```
# Issue description

lxc-snapshot of a new container fails with `lxc_snapshot.c: do_snapshot: 185 Error creating a snapshot`

# Steps to reproduce

Ubuntu 15.10

```sh
sudo add-apt-repository ppa:ubuntu-lxc/lxd-git-master && sudo apt-get update
sudo apt-get install lxd
newgrp lxd
lxc launch ubuntu:14.04
lxc list
lxc-snapshot -n unpieced-marcelo
```

(replace with the name of actual container) fails with 

```sh
lxc-snapshot: lxc_snapshot.c: do_snapshot: 185 Error creating a snapshot
```

running it with `strace` seems to look for 

```
stat("/var/lib/lxc/unpieced-marcelo/config", 0x7ffe8d244470) = -1 ENOENT (No such file or directory)
stat("/var/lib/lxc/unpieced-marcelo/partial", 0x7ffe8d2443d0) = -1 ENOENT (No such file or directory)
```

but those files are absent on my system for some reason. (This was a clean install, I didn't change any config options of lxc/lxd)

```
root@ubuntu-lxd-test:~# ls -la /var/lib/lxc/
total 8
drwx------  2 root root 4096 Mar 11 15:34 .
drwxr-xr-x 45 root root 4096 Mar 16 15:44 ..
```

```sh
root@ubuntu-lxd-test:~# lxd --version
2.0.0.rc3
root@ubuntu-lxd-test:~# lxc --version
2.0.0.rc3
```

**Comment by stgraber** [comment]
try "lxc snapshot unpieced-marcelo" instead.

You seem to be mixing the old LXC tools with the LXD tools, that's not gonna work.

**Comment by slava-vishnyakov** [comment]
:+1: Awesome, thanks @stgraber ! That worked :) It's hard to orient with all lxc guides around! Sorry for wasting your time :)

Thanks for a great job, guys!
