### ISSUE TITLE
Fresh install of lxd fails to start containers

### ISSUE THREAD

**Issue by bradclawsie** [lxc/lxd#1778]
(Before proceeding I would like to note that on 3/17 PDT, I was able to run containers using lxd. On 3/18 PDT , I did an update and it no longer works. Below are the details)

# Required information

 * Distribution: Ubuntu Server 15.10 running as a kvm on Ubuntu Desktop 15.10
 * Distribution version: 15.10
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux ubuntu 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 2.0.0.rc4
   * LXD version: 2.0.0.rc4
   * Storage backend in use: dir (no zfs, no lvm...a kvm instance with default partitioning)

# Issue description

On 3/17 PDT I was able to try out some lxd containers. On 3/18 I performed an `apt-get update` and now containers don't work at all. I don't know if the update is related. To confirm, I purged lxd and removed `/var/lib/lxd` and `/var/log/lxd`. I reinstalled. I attempted to start an ubuntu 15.10 image. No luck.

# Steps to reproduce

 1. Purge lxd
 2. Install lxd
 3. Attempt to start a container

# Information to attach

 - [ x] container log (lxc info NAME --show-log)
 - [x ] output of the client with --debug

[client-start-debug.txt](https://github.com/lxc/lxd/files/180296/client-start-debug.txt)
[container-info.txt](https://github.com/lxc/lxd/files/180297/container-info.txt)

**Comment by bradclawsie** [comment]
adding lxc --
[lxcinfo.txt](https://github.com/lxc/lxd/files/180299/lxcinfo.txt)
info

**Comment by stgraber** [comment]
Looks like /usr/share/lxcfs/lxc.mount.hook is failing for you somehow

**Comment by bradclawsie** [comment]
I believe I have a clue that may help narrow this down. Somehow, possibly after a purge of lxd, the directory `/var/lib/lxcfs` seems to have become corrupted somehow, it had a timestamp of Dec 31, 1969. I had been making sure to manually remove `/var/{lib,log}/lxc` and `/var/{lib,log}/lxd` but I had been ignoring `/var/lib/lxcfs`...but I don't know at what point it became corrupt.

So, I once again purged everything, lxd and its dependencies, removed the dirs as above, and also removed `/var/lib/lxcfs`. I installed lxd once again, and then `/var/lib/libxcfs` had a normal timestamp.

After this, I was able to use lxd again (I tested by pulling an alpine image since it was the fastest option)

Hopefully Stéphane I have not wasted your time, this may or may not even be a bug. I will allow you to mark this as you see fit.

thanks
Brad

**Comment by timtierney** [comment]
I think I may be running into the same issue as bradclawsie.  After the latest update, I ended up rebooting the LXD host and none of my containers will start now.

Running Ubuntu Server 15.10 (i386)
Kernel:  4.2.0-34-generic
lxc/lxd version:  2.0.0.rc4

Error Message: `Error calling 'lxd forkstart web1 /var/lib/lxd/containers /var/log/lxd/web1/lxc.conf': err='exit status 1'`
`Try lxc info --show-log web1 for more info`

See attached 'show-log' attachment
[show-log.txt](https://github.com/lxc/lxd/files/180526/show-log.txt)

**Comment by stgraber** [comment]
Yeah, same error. I suspect this has to do with the new liblxc (rc11).

**Comment by stgraber** [comment]
There are a couple of LXC bugs that people have run into it looks like with this latest rc. I'll take a look.

If you still have liblxc1 rc10 around somewhere, try downgrading to that.

**Comment by stgraber** [comment]
This has been resolved now with a new lxcfs upload. It should hit the various PPAs over the next couple of hours.

**Comment by timtierney** [comment]
Once again, you've fixed my issue.  Thanks stgraber!
