### ISSUE TITLE
Failure to delete container with very long filename

### ISSUE THREAD

**Issue by howbazaar** [lxc/lxd#1781]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Trusty
 * The output of "lxc info" or if that fails:

$ lxc info
```
apicompat: 0
auth: trusted
environment:
  addresses:
  - 192.168.2.4:8443
  - 10.0.3.1:8443
  - 192.168.122.1:8443
  architectures:
  - x86_64
  - i686
  certificate:  <snip>
  driver: lxc
  driverversion: 1.1.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.13.0-79-generic
  server: lxd
  serverpid: 8479
  serverversion: 2.0.0.rc4
  storage: dir
  storageversion: ""
```

# Issue description

Due to a bug in juju we were able to produce a very long filename, deep nested directories that made the lxc command fail in its removal of the container.

$ lxc delete juju-c0518c0b-97b5-47ab-8c1b-541906fb2c73-machine-0
error: Error cleaning up /var/lib/lxd/containers/juju-c0518c0b-97b5-47ab-8c1b-541906fb2c73-machine-0: lstat /var/lib/lxd/containers/juju-c0518c0b-97b5-47ab-8c1b-541906fb2c73-machine-0/rootfs/.config/lxc/juju-target/juju-to-move/juju-to-move/juju-target/juju-target/juju-to-move/juju-to-move/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-target/juju-to-move/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-to-move/juju-target/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-target/juju-to-move/juju-to-move/juju-target/juju-to-move/juju-to-move/juju-target/juju-target/juju-target/juju-target/juju-to-move/juju-to-move/juju-to-move/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-target/juju-to-move/juju-to-move/juju-to-move/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-to-move/juju-to-move/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-to-move/juju-target/juju-to-move/juju-target/juju-target/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-to-move/juju-target/juju-to-move/juju-target/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-to-move/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-target/juju-to-move/client.crt: file name too long

**Comment by stgraber** [comment]
I just took a look and all we do in the directory backend for container removal is "os.RemovaAll(path)".
Which does seem like an appropriate thing to do. I suspect that this bug is therefore an upstream Golang bug as they could (and arguably should) detect this case and just fallback to removing things by doing a reverse walk through the target.

**Comment by stgraber** [comment]
There appears to be a similar issue on Windows https://github.com/golang/go/issues/3358

**Comment by stgraber** [comment]
We could workaround the issue by forking "rm -Rf PATH" but that seems a bit silly.

**Comment by stgraber** [comment]
Marking as a bug, though I'm not sure whether it's LXD's job to workaround this...
