### ISSUE TITLE
REST API does not provide remote Image list

### ISSUE THREAD

**Issue by dobin** [lxc/lxd#1782]
# Issue description

REST API does not provide "lxc image list ubuntu:" command. 

# Details

I'd like to provide a web gui which enables the user to easily create and deploy new containers. Sadly is not really possible to comfortably import new images into LXD via the REST, as no "lxc image list ubuntu:/ubuntu-daily:/images:" is provided. 

So this workflow not possible:
- Insert container name
- Select container image (-> where to get it from if not in image list?)
- Create container

## More details

The user currently has to either:
  - manually import the image via the command line
  - or Use the "Import image" API (source.type="url"), and specify a URL to a image, but has to manually search through the following websites and find the correct archive file:
    - https://images.linuxcontainers.org
    - https://cloud-images.ubuntu.com/releases

This is not really user friendly. 

## To image or not to image?

I'm also a bit confused. It is possible to start new container with a remote image. After the command, the image is imported into the image store:
```
lxc launch ubuntu:14.04 my-ubuntu
```

But its NOT possible to import this image like:
```
lxc image import ubuntu: 14.04
```

So, what's the preferred way to create a new container? just specify a remote image location, or to import the image and start the container with that image?

# My Solutions

Possible solutions for my problem with the image import for the web gui:

1. Update REST API to include the image list command
2. Or: I have to create a GO web server which implements the image list, using the functionality from this lxd project
3. Or: I need to create a 3rd party website which parses the ubuntu:/ubuntu-daily:/images: JSON and displays it nicely, so the user is able to copy paste the url to the archive
4. Or: I manually download the JSON with the image list (https://cloud-images.ubuntu.com/releases/streams/v1/index.json etc.) and publish it with my webapp, including regular updates to include new versions. 

So, is it possible to implement 1? Or what alternatives do i have here?

**Comment by tych0** [comment]
On Mon, Mar 21, 2016 at 03:57:41AM -0700, Dobin Rutishauser wrote:
> # Issue description
> 
> REST API does not provide "lxc image list ubuntu:" command. 
> 
> # Details
> 
> I'd like to provide a web gui which enables the user to easily create and deploy new containers. Sadly is not really possible to comfortably import new images into LXD via the REST, as no "lxc image list ubuntu:/ubuntu-daily:/images:" is provided. 
> 
> So this workflow not possible:
> - Insert container name
> - Select container image (-> where to get it from if not in image list?)
> - Create container
> 
> ## More details
> 
> The user currently has to either:
>   - manually import the image via the command line
>   - or Use the "Import image" API (source.type="url"), and specify a URL to a image, but has to manually search through the following websites and find the correct archive file:
>     - https://images.linuxcontainers.org
>     - https://cloud-images.ubuntu.com/releases
> 
> This is not really user friendly. 
> 
> ## To image or not to image?
> 
> I'm also a bit confused. It is possible to start new container with a remote image. After the command, the image is imported into the image store:
> ```
> lxc launch ubuntu:14.04 my-ubuntu
> ```
> 
> But its NOT possible to import this image like:
> ```
> lxc image import ubuntu: 14.04
> ```
> 
> So, what's the preferred way to create a new container? just specify a remote image location, or to import the image and start the container with that image?
> 
> # My Solutions
> 
> Possible solutions for my problem with the image import for the web gui:
> 
> 1. Update REST API to include the image list command
> 2. Or: I have to create a GO web server which implements the image list, using the functionality from this lxd project
> 3. Or: I need to create a 3rd party website which parses the ubuntu:/ubuntu-daily:/images: JSON and displays it nicely, so the user is able to copy paste the url to the archive
> 4. Or: I manually download the JSON with the image list (https://cloud-images.ubuntu.com/releases/streams/v1/index.json etc.) and publish it with my webapp, including regular updates to include new versions. 
> 
> So, is it possible to implement 1? Or what alternatives do i have here?

Why not 5. query the simplestreams data and parse it from within your
app? Why do you have to do it over a REST api or cache it or whatever?
There is golang code in LXD to parse simplestreams, or there is a
python library to do the same: https://launchpad.net/simplestreams

**Comment by dobin** [comment]
Yeah I can parse the simplestreams (like https://cloud-images.ubuntu.com/releases/streams/v1/index.json), which give me the stuff from ubuntu: and ubuntudaily:, but not images: (that is just plain HTML?) . Therefore need to implement not only one, but two different modules, just to gain access to the list of available images.  

Note that for simplicity's sake, i wanted to create a HTML/JS only app, without a backend. As the simplestreams JSON files on cloud-images.ubuntu.com dont have an open Access-Control-Origin header, I have to resort to implement a backend just for the sake of querying a public JSON service. 

Of course if it's a deliberate design decision to not expose the "list" command via the REST API, I'll do no. 5 (which is my no. 2).

**Comment by tych0** [comment]
On Mon, Mar 21, 2016 at 07:04:16AM -0700, Dobin Rutishauser wrote:
> Yeah I can parse the simplestreams (like https://cloud-images.ubuntu.com/releases/streams/v1/index.json), which give me the stuff from ubuntu: and ubuntudaily:, but not images: (that is just plain HTML?) .

It's just a text file.

> Therefore need to implement not only one, but two different modules, just to gain access to the list of available images.  

Yes, there are multiple formats.

> Note that for simplicity's sake, i wanted to create a HTML/JS only app, without a backend. As the simplestreams JSON files on cloud-images.ubuntu.com dont have an open Access-Control-Origin header, I have to resort to implement a backend just for the sake of querying a public JSON service. 

Hmm. We might be able to help you there, let me inquire.

> Of course if it's a deliberate design decision to not expose the "list" command via the REST API, I'll do no. 5 (which is my no. 2). 

Well, "list" /is/ implemented in LXD's rest api. What you're asking
LXD to do is go to some other remote and report that remote's images,
as opposed to just parsing that remote yourself. I'm not sure this
makes a lot of sense.

**Comment by tych0** [comment]
Can you elaborate a bit about Access-Control-Origin? I'm not too familiar with how webapps are developed. What would you need it set to?

**Comment by dobin** [comment]
Concerning the Access-Control-Origin:

A web-accessible index of the ubuntu images would be awesome for me :-) 

The simplestreams JSON should be delivered containing the following HTTP header in the HTTP response:
`Access-Control-Allow-Origin: *`

This probably includes at least the following URLs:
```
https://cloud-images.ubuntu.com/releases/streams/v1/index.json
https://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json
```

Setting access-control-origin to "*" (everyone) will allow every website to read the content of the JSON. 
If this header is NOT set, the same origin policy of the browser prohibits accessing that JSON from all domains except the origin (cloud-images.ubuntu.com). As this is public read-only data, there should be no security concerns, but imho a security guy at ubuntu should give an OK to perform this change. 

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
- http://stackoverflow.com/questions/7015782/how-do-i-use-access-control-allow-origin-does-it-just-go-in-between-the-html-he

**Comment by dobin** [comment]
> Well, "list" /is/ implemented in LXD's rest api. What you're asking
> LXD to do is go to some other remote and report that remote's images,
> as opposed to just parsing that remote yourself. I'm not sure this
> makes a lot of sense.

If you phrase it like this: Yes, it does not appear to make a lot of sense :-)

Nevertheless: lxd supports working on the remote images and their aliases natively. 
The very first command to set-up a container described on lxcontainers.org uses remote images: https://linuxcontainers.org/lxd/getting-started-cli/#using-the-built-in-image-remotes and the command "lxc image list images:". Therefore i assumed that working on remote images is a natural way, and this includes searching through them. 

Also, searching through "private" images need authentication (client certificate), which lxd already has, but other software (as in browsers or 3rd party websites) do not. 

Afaik there is also no support in the REST api to see the "remotes" (URL's and protocols) of an lxd server.

**Comment by tych0** [comment]
On Mon, Mar 21, 2016 at 09:35:11AM -0700, Dobin Rutishauser wrote:
> > Well, "list" /is/ implemented in LXD's rest api. What you're asking
> > LXD to do is go to some other remote and report that remote's images,
> > as opposed to just parsing that remote yourself. I'm not sure this
> > makes a lot of sense.
> 
> If you phrase it like this: Yes, it does not appear to make a lot of sense :-)
> 
> Nevertheless: lxd supports working on the remote images and their aliases natively. 
> The very first command to set-up a container described on lxcontainers.org uses remote images: https://linuxcontainers.org/lxd/getting-started-cli/#using-the-built-in-image-remotes and the command "lxc image list images:". Therefore i assumed that working on remote images is a natural way, and this includes searching through them. 

It is with the command line client, but that's just a feature that
exists in our command line client. If you're using the API, you want
to look at the api docs instead:
https://github.com/lxc/lxd/blob/master/doc/rest-api.md

> Also, searching through "private" images need authentication (client certificate), which lxd already has, but other software (as in browsers or 3rd party websites) do not. 

Right, naturally the third party software needs to authenticate the
same as everyone else.

> Afaik there is also no support in the REST api to see the "remotes" (URL's and protocols) of an lxd server. 

There are no remotes on the server, just on the client. The client
tells the server exactly what stuff to download from who each time.

You can do `lxc remote list` to see the remotes on your local client.

**Comment by dobin** [comment]
Ah, gotcha! LXD, the "server", does not know anything about remotes or image locations, only lxc, the client, does. The REST interface only accesses the lxd server, and therefore can't provide the remote-image search. I mixed-up the components/architecture. Now it makes sense. 

I'll wait a bit for feedback on the access-control-origin thingy until i close this issue.

**Comment by dobin** [comment]
Maybe its also possible to put the Access-Control-Allow-Origin on:
```
https://images.linuxcontainers.org/meta/1.0/*
```

**Comment by aarnaud** [comment]
hey @dobin 

Same idea !

https://github.com/aarnaud/lxd-webui with angular2 and webpack

**Comment by dobin** [comment]
@aarnaud lol, we even have nearly identical names... https://github.com/dobin/lxd-webgui
Mine is already working pretty well and usable. 

Maybe we should join forces? drop me an email; dobin@broken.ch or dobin on freenode

**Comment by aarnaud** [comment]
I take this opportunity to learn angular2 ;-)
I will try it lxd-webgui ;-) and maybe i will contribute of course!

**Comment by stgraber** [comment]
Allowed-Origin set to * for images.linuxcontainers.org

**Comment by aarnaud** [comment]
Thanks @stgraber

**Comment by dobin** [comment]
thanks @stgraber!

Concerning images.linuxcontainers.org:
I cant seem to find the hash of the image (which the client needs to give to LXD REST API to import an image). Can you tell where/how to find it, or add it to the index-user/index-system files?

### Details

there is a file with the available images on:
- https://images.linuxcontainers.org/meta/1.0/index-user

which contains lines like:
```
ubuntu;xenial;s390x;default;20160322_03:49;/images/ubuntu/xenial/s390x/default/20160322_03:49/
```

But this file does not include the hash of the images,unlike `lxc image list images:`
```
|                                 | 23a78772d68e | yes    | Ubuntu xenial (s390x) (20160322_03:49)    | s390x   | 73.88MB  | Mar 22, 2016 at 4:35am (UTC)  |
```

The has is also not written in the image directories, e.g.:
- https://images.linuxcontainers.org/images/alpine/3.1/i386/default/20160322_17:50/

And the following directory seems to be not accessible:
- https://images.linuxcontainers.org/meta/lxd/

**Comment by stgraber** [comment]
Yeah, sounds like you got confused by that server providing both the lxc-download API and the LXD api.

When using it with LXD, just stick to what you find under https://images.linuxcontainers.org:8443/1.0

**Comment by dobin** [comment]
Linuxcontainers.org has the allow-origin header, cloud-images.ubuntu.com not. 

My app works pretty good right now: https://github.com/dobin/lxd-webgui

I'll close this issue, and maybe open a new one later, for adding the http header to cloud-images.ubuntu.com
