### ISSUE TITLE
DELETE /images/<fingerprint> asynchronous?

### ISSUE THREAD

**Issue by jeffshantz** [lxc/lxd#1786]
The REST API documentation for `DELETE /1.0/images/<fingerprint>` indicates that it is an asynchronous operation:

```
DELETE

Description: Remove an image
Authentication: trusted
Operation: async
Return: background operaton or standard error
Input (none at present):

{
}
HTTP code for this should be 202 (Accepted).
```

However, when I issue a DELETE on an image, it is indeed deleted, but the response is synchronous:

```
{:type=>"sync", :status=>"Success", :status_code=>200, :metadata=>{}}
```

Is this a doc bug, or is the operation truly intended to be asynchronous?  If the former, I'm happy to update the API docs.

**Comment by stgraber** [comment]
Crap, I was really hoping that I wouldn't have to do any last minute API fixes...

Anyway, you're right, this absolutely should be Async as documented. I've now fixed it.

Doesn't look like this will affect any of our existing downstreams but it will break backward compatibility for that one call with older clients...

**Comment by jeffshantz** [comment]
Sorry to be the bearer of bad news. :)

**Comment by stgraber** [comment]
Better now than after 2.0 is tagged, then it'd be too late to do any API change that'd break backward compatibility :)

I've quickly gone through the rest-api.md doc to check all the other asyncs and the rest does appear to be properly implemented at least.
