### ISSUE TITLE
Abnormal asynchronous behaviour for POST /1.0/images/<fingerprint>/secret

### ISSUE THREAD

**Issue by jeffshantz** [lxc/lxd#1790]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04.4
 * Kernel version: 3.19.0-43-generic
 * LXC version: 1.1.5
 * LXD version: 2.0.0.rc2
 * Storage backend in use: btrfs

# Issue description

This may just be my misunderstanding in the way asynchronous operations work in LXD.  For all async operations I've implemented in my API client to date, the workflow is this:

* Make the API call
* Get the operation ID
* Call `/1.0/operations/<uuid>/wait`
* Get the result of the operation

When I call `POST /1.0/images/<fingerprint>/secret` to generate a secret, however, the result of the `POST` is this (shown in Ruby syntax):

```ruby
{:type=>"async",
 :status=>"Operation created",
 :status_code=>100,
 :metadata=>
  {:id=>"510af38c-6963-4566-864e-d2c39c3e6fef",
   :class=>"token",
   :created_at=>2016-03-22 15:26:06 -0400,
   :updated_at=>2016-03-22 15:26:06 -0400,
   :status=>"Running",
   :status_code=>103,
   :resources=>
    {:images=>
      ["/1.0/images/097e75d6f7419d3a5e204d8125582f2d7bdd4ee4c35bd324513321c645f0c415"]},
   :metadata=>
    {:secret=>
      "a5571936889183509a013b013b4adbdec5f2352379fb9fe1fa64314c46af929a"},
   :may_cancel=>true,
   :err=>""},
 :operation=>"/1.0/operations/510af38c-6963-4566-864e-d2c39c3e6fef"}
```

The secret is already there, but is it always guaranteed to be in that response?  If I try waiting on the operation ID, it just sits there waiting indefinitely and never returns.

Also, if I `GET /1.0/operations`, the ID appears in the result, but is seemingly never removed.

# Steps to reproduce

**Create the secret:**

```
curl --key ~/.config/lxc/client.key --cert ~/.config/lxc/client.crt -k \
      -X POST \  
 https://127.0.0.1:8443/1.0/images/097e75d6f7419d3a5e204d8125582f2d7bdd4ee4c35bd324513321c645f0c415/secret
```

Sample result:

```json
{
  "type":"async",
  "status":"Operation created",
  "status_code":100,
  "metadata":{
    "id":"d000da3e-16bd-4be2-88d4-0a842e1db6c6",
    "class":"token",
    "created_at":"2016-03-22T15:34:13.212815555-04:00",
    "updated_at":"2016-03-22T15:34:13.212815555-04:00",
    "status":"Running",
    "status_code":103,
    "resources":{
      "images":[
        "/1.0/images/097e75d6f7419d3a5e204d8125582f2d7bdd4ee4c35bd324513321c645f0c415"
      ]
    },
    "metadata":{
      "secret":"b23bd0be44cd8ecaec7ecf75e37df8107f4097431671adc1c28cde87e4f72fcf"
    },
    "may_cancel":true,
    "err":""
  },
  "operation":"/1.0/operations/d000da3e-16bd-4be2-88d4-0a842e1db6c6"
}
```

**Quickly call `wait` on the operation ID:**

```
curl --key ~/.config/lxc/client.key --cert ~/.config/lxc/client.crt -k \
  https://127.0.0.1:8443/1.0/operations/d000da3e-16bd-4be2-88d4-0a842e1db6c6/wait
```

This hangs indefinitely.

**Check `/1.0/operations`:**

```
curl --key ~/.config/lxc/client.key --cert ~/.config/lxc/client.crt -k \
  https://127.0.0.1:8443/1.0/operations
```

Observe that the operation is listed as running (along with a whole bunch of other similar operations that are currently stuck in there):

```json
{
  "type":"sync",
  "status":"Success",
  "status_code":200,
  "metadata":{
    "running":[
      "/1.0/operations/6e89816b-5d62-4984-9e58-21df7ef024ee",
      "/1.0/operations/bd6abde6-c582-4688-a2ba-f6c50bae4e7c",
      "/1.0/operations/060a7e12-291c-42a2-a478-35ea41a6e713",
      "/1.0/operations/1c4e44f1-9a15-4632-bcbe-c1407c5cf294",
      "/1.0/operations/7863b0ec-c645-4ca2-89e8-93cf0c4a7776",
      "/1.0/operations/d000da3e-16bd-4be2-88d4-0a842e1db6c6",      <--- note the operation ID
      "/1.0/operations/1bc66eab-e435-4e83-82c9-0a23bdf54003",
      "/1.0/operations/510af38c-6963-4566-864e-d2c39c3e6fef",
      "/1.0/operations/2d2bce07-98da-4e02-b3c3-73ea7e837b03"
    ]
  }
}
```

**Comment by jeffshantz** [comment]
The stuck operations persist until I restart the lxd service.

**Comment by stgraber** [comment]
It's normal, yes.

The way "token" type operations work is that they don't do any actual work, they are just place holders. They do contain some data in the initial response (in this case, a secret).

The operation only ever disappears when it's canceled. You can cancel it manually by calling DELETE on it or in this case, by using the secret in question.

The intent for the image secret is that you do:
 - POST on host-1 /1.0/images/FINGERPRINT/secret
 - Grab the secret in the response
 - POST on host-2 /1.0/containers with the URL of host-1 and the secret you received
 - host-2 will fetch the image using that secret
 - 5s after the secret has been used, the operation is flushed and the secret is invalidated

**Comment by jeffshantz** [comment]
Good to know.  Thank you!

**Comment by stgraber** [comment]
Note that wait on a token operation will return, but only once the operation is canceled. If you never call DELETE or use the secret, then it will indeed stick around until the daemon gets restarted.

Having an expiry on token type operations would probably make sense though.
