### ISSUE TITLE
Feature request: 'lxc image alias list [remote:] [filter]'

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1798]
Using lxc version 2.0.0.rc5 from on Trusty from the ppa.

It would be nice if you could pass a filter to "lxc image alias list". Especially now that you support Simplestreams remotes doing:
  lxc image alias list ubuntu:
is  3603 lines long. Which means I always have to dump it into a text editor to find what I want. Being able to do:
 lxc image alias list ubuntu:trusty*
or some variant of that "trusty.*" as a regex, trusty* as a glob, "ubuntu:" "trusty*" as 2 commandline parameters, or "--filter trusty" as a simple string match from a named parameter.

Just something that would let me see a subset so I can get a quick answer (is my local hash the same as the official source?)

**Comment by stgraber** [comment]
Should be pretty easy to add since we already have the logic in lxc list and lxc image list.

Until then you can do the same search using "lxc image list [filter]" as it will filter based on alias name if provided.
