### ISSUE TITLE
lxc exec can hang randomly

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#1803]
If you start a container, and then run

`for i in $(seq 100); do echo $i; lxc exec host2:unpriv ps auxf; done`

in two different shells, eventually they'll both hang (it might take a few tries, but it worked for me on the first one).

**Comment by stgraber** [comment]
Reproduced it here, it also looks like the daemon forked at some point and its child doesn't get cleaned on exit so a restart of the daemon fails to bind the tcp socket here.
