### ISSUE TITLE
lxc stop and restart should be successful on stopped containers

### ISSUE THREAD

**Issue by pgassmann** [lxc/lxd#1804]
# Issue description

lxc stop should return exit code 0 
lxc restart should start a stopped container

compare to `service xyz stop` or `service xyz restart`

# Steps to reproduce
```
# lxc stop testx1 
error: container is not running
Try `lxc info --show-log testx1` for more info
# echo $?
1
# lxc restart testx1 
error: container is not running
Try `lxc info --show-log testx1` for more info
```

same with `lxc restart testx1`

# System information

 * Distribution: Ubuntu
 * Distribution version: trusty
 * The output of "lxc info" or if that fails:
```
  driver: lxc
  driverversion: 2.0.0.rc12
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-30-generic
  server: lxd
  serverpid: 1696
  serverversion: 2.0.0.rc5
  storage: btrfs
  storageversion: "3.12"
```

**Comment by stgraber** [comment]
I disagree, in both case the action you requested failed so returning an error is absolutely appropriate.

For that matter the behavior of the "service" command always felt weird to me, instead what upstart's initctl was doing made a lot more sense which was to return an error and non-zero exit code if the action the user requested couldn't be completed.

**Comment by stgraber** [comment]
We would probably accept a branch which changes the return value for the "already running" and "already stopped" cases from the current generic error one "1" to say "2" so shell scripts can distinguish this case.
