### ISSUE TITLE
nictype reset in RC6

### ISSUE THREAD

**Issue by jasonbayton** [lxc/lxd#1812]
# Required information

driver: lxc
  driverversion: 2.0.0.rc13
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-34-generic
  server: lxd
  serverpid: 1102
  serverversion: 2.0.0.rc6
  storage: dir

# Issue description

On updating to RC6 this evening and rebooting (the reboot being for something else) I lost all network access to my containers. On inspecting the default profile the `nictype` I set as `br0` had changed to `lxdbr0`.

Changing this back to br0 resolved the problem.

# Steps to reproduce

 1. Update from RC5 to RC6
 2. Reboot/restart networking
 3. lxc list will show IPs missing

**Comment by stgraber** [comment]
Hmm, that's not a LXD problem but a potential packaging problem.

2.0.0~rc6-0ubuntu2 introduces a new lxdbr0 bridge. However there is logic in place to only switch to that new bridge if you touch /etc/default/lxd-bridge or if you somehow reconfigure the lxd package.

A straight upgrade shouldn't have caused lxd to switch over to it...

Anyway, I have a bit more testing to do on 15.10 as there was another report of some oddities following the upgrade to that new packaging so hopefully I can figure out what's wrong in the logic.

Closing this report as all that logic is in distro packaging, not in LXD itself.

**Comment by stgraber** [comment]
To make sure that nothing is horribly wrong, I just checked a dozen productions systems that automatically upgraded to rc6 and all of them are still on lxcbr0 as expected, so that seems to confirm that most of the logic is right and that whatever happened here is going to be a tiny corner case.

**Comment by jasonbayton** [comment]
No worries, thank you for looking into it. I can definitely confirm all I did was run apt-get upgrade and later reboot. Having already setup networking as I wanted there would be no need for me to poke around anything network related.

Within the default profile I've setup two nics. It's interesting to note it didn't reset the whole profile to one nic with nictype lxdbr0, as if a file had been replaced, but just swapped br0 to lxdbr0 as mentioned above.

**Comment by stgraber** [comment]
Yeah, I made sure our scripts don't wipe the default profile clean, they only do change the couple of keys they need to limit potential collateral damage.

We'll have another package update in a few days that will switch everyone to the lxdbr0 bridge as we retire lxcbr0. Unfortunately as that will happen in the middle of a package upgrade, we won't have access to the LXD daemon so can't check what bridge you're using right now... The plan though is to have the upgrade show you a warning message followed by a set of questions to configure LXD networking, so as long as a human being is doing the upgrade (as opposed to unattended-upgrade or a package manager), you will be able to tell the upgrader that you want to use your own bridge and what's its name. If you don't, then the default profile will be changed to use lxdbr0 and you'll have to configure /etc/default/lxd-bridge post-upgrade and then restart lxd-bridge and lxd.

To prevent potential breakage during that upgrade, you could go and configure /etc/default/lxd-bridge ahead of time. In your case, setting USE_LXD_BRIDGE to false and LXD_BRIDGE either to an empty string or to the name of your hand-created bridge.

**Comment by jasonbayton** [comment]
This definitely clarifies things thanks, and the addition of a warning message going forward will save a lot of headaches.

Do you mind though elaborating on lxd-bridge vs editing the default profile? Up to this point every write-up on the subject has always made a point of saying LXD doesn't use a file as LXC did, and to create/edit profiles for LXD. With the (re?)introduction of a file, where will we stand in terms of what to edit, why and when?

**Comment by stgraber** [comment]
LXD doesn't read that configuration file, the configuration file is very similar in scope to what lxcbr0 has at /etc/default/lxc-net.

The init scripts do however change the LXD profile configuration for you when the file changes as there are a few cases where that's needed. Specifically, lxdbr0 is brought up with no IPv4 or IPv6 configuration, that's to avoid clashing with a user's network. But to get basic connectivity working, a minimal http proxy server is running on a link-local address. The init script configures LXD to set the appropriate environment variable so the user can use the proxy right after installing LXD.

Once the user configures the bridge to actually have a working subnet, the init script will unset those environment variables. Similarly if the user disables the bridge in the config file, the default profile will be update to remove those environment variables and if the user specified one, change the bridge over to the one the user configured.

Those profiles changes only happen when the configuration file was changed. The profile will not be changed at every startup, so once you've configured or turned off lxdbr0, no change will occur.


I agree that this is not ideal, but it's us having to walk the fine line between our current stance which is that LXD itself shouldn't have to setup networking, only caring about having a valid layer2 network to use for containers and our users expecting things to work out of the box while not breaking their connectivity.

The transition period from lxcbr0 to lxdbr0 will likely be a bit rough for some users, we've tried to make the upgrade scripts as clever as we can to limit the impact, but it's still a big change...

**Comment by jasonbayton** [comment]
Thanks for taking the time to explain this @stgraber. Makes sense to me now.

**Comment by jasonbayton** [comment]
Just updated again this evening to rc8 and once again the default profile was changed from my bridge (br0) to lxdbr0. 

lxdbr0 is configured with a subnet of my choosing, so is enabled and hasn't changed that, but it is enabled on eth1, not eth0. The update changes eth0 in the default profile.

`description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: **br0**
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: lxdbr0
    type: nic
`

**Comment by stgraber** [comment]
Oh, that's a setup we've not thought about, the "using lxdbr0 but not on eth0".

We do support turning lxdbr0 off entirely which then means that your default profile won't get changed anymore, but your setup isn't something we support right now :)

So there are a few workarounds you could consider:
 - Not use lxdbr0, set it to false in /etc/default/lxd-bridge and do your own thing for your interfaces
 - Change the lxd.service systemd unit, replacing the existing "ExecStartPost=/usr/lib/lxd/profile-config" by "ExecStartPost=-lxd ready" which will prevent systemd from calling the profile-config script.

**Comment by stgraber** [comment]
I'll look into adding a configuration option to have lxdbr0 but not touch the lxd profile.

**Comment by jasonbayton** [comment]
Ah, never one to follow the beaten track me :)

The intention is to swap out lxcbr0 to lxdbr0 right? 

Can you not add one more if statement to check for the existence of lxcbr0 on that line before you change it?

I'll likely go for option two there. Is that dash supposed to be in front of LXD ready? Not sure if it's a typo..

**Comment by stgraber** [comment]
The dash is to ignore failures.

Just uploaded a new lxd package which adds an extra config option to turn updating the profile off.

And we can't just check the bridge name because folks can rename their bridges at will and it would be weird not to accept some specific values.

**Comment by jasonbayton** [comment]
Having never bothered trying to rename lxcbr0 to anything else (equally the same with lxdbr0) that didn't even occur to me.. oh well! I'll see how the next update goes and take it from there!
