### ISSUE TITLE
LXD failed to start after upgrade

### ISSUE THREAD

**Issue by fabfurnari** [lxc/lxd#1820]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Trusty
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.2.0-27-generic #32~14.04.1-Ubuntu
   * LXC version: 2.0.0.rc6
   * LXD version: 2.0.0.rc6
   * Storage backend in use: LVM

# Issue description

After upgrading using the ubuntu repositories LXD refuses to be configured by post-installation script and to start.

# Information to attach

- /var/log/upstart/lxd.log

```
RTNETLINK answers: Permission denied
Failed to setup lxd-bridge.
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: No chain/target/match by that name.
lxd-bridge isn't running
```

**Comment by tomposmiko** [comment]
The same here.
Reason: bridge cannot get up.
```
+ ifup lxdbr0  
+ ip addr add fe80::1/64 dev lxdbr0
RTNETLINK answers: Permission denied
+ cleanup
+ set +e
+ [ 1 = 1 ]
+ echo Failed to setup lxd-bridge.
Failed to setup lxd-bridge.
```

On my instance ipv6 isn't enabled.

**Comment by tomposmiko** [comment]
```
    ip addr add fe80::1/64 dev "${1}" 
```
=>
``` 
    ip addr add fe80::1/64 dev "${1}" || true
```

This works temporarily.

**Comment by jasonbayton** [comment]
Possibly related to https://github.com/lxc/lxd/issues/1811

**Comment by tomposmiko** [comment]
The above fix is good for the successful package upgrade but not enough to get the existing system working.
The default network interface was changed to lxdbr0.
Long term fix:

dpkg-reconfigure lxd
-> no
-> yes
-> lxcbr0

**Comment by stgraber** [comment]
The permission denied issue is fixed in rc7 which should now be available through the PPA.
