### ISSUE TITLE
REST API error while updating container config

### ISSUE THREAD

**Issue by patademahesh** [lxc/lxd#1822]
Hi

I am trying to update container config using REST API. I am getting below error.

URL: https://xx.xx.xx.xx:8443/1.0/containers/CentOS2
JSON Data: {"config":{"limits.cpu":"3","limits.memory":"1GB"}}
Error Code 400 
Error : **Container is lacking rootfs entry**

LXD Version  :  2.0.0~rc4-0ubuntu1~ubuntu14.04.1~ppa1
Ubuntu 14.04

Thanks
Mahesh

**Comment by stgraber** [comment]
yup, that's normal.

A REST PUT request replaces the whole target with the new provided data, it doesn't just update the key you provide (that would be PATCH which we don't implemented yet).

So your request above requests that LXD removes all configuration and devices from the container and replace it with just your cpu and memory limits.

That removes the container rootfs device entry which isn't allowed.


Instead, do a GET of the container, then apply your changes and then PUT that.

**Comment by patademahesh** [comment]
ohhh.. I'll try that way. One more thing I want to know, is it possible to attach disk/device to Container through REST API. Didnt find any information in rest api docs. 

Thanks for the information.

Mahesh

**Comment by stgraber** [comment]
Yep, everything LXD does is through the REST API.

Attaching a new disk/device is done by adding an entry to the "devices" map.

By default you probably have something like:
```
devices = {
    "root": {
        "type": "disk"
    }
}
```

To add a bind-mounted path, change that to:
```
devices = {
    "root": {
        "type": "disk"
    },
    "some-name": {
        "type": "disk",
        "path": "/mnt/home",
        "source": "/home"
    }
}
```

And you'll end up with the host /home mounted into your container at /mnt/home

**Comment by patademahesh** [comment]
Wow. Thanks a lot Stéphane

Mahesh
