### ISSUE TITLE
Ubuntu cloud image not resolvable on *.lxc domain name

### ISSUE THREAD

**Issue by henrylawson** [lxc/lxd#1828]
# Required information

Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```
  driver: lxc
  driverversion: 2.0.0.rc5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-30-generic
  server: lxd
  serverpid: 936
  serverversion: 2.0.0.rc2
  storage: dir
  storageversion: ""
```

# Issue description

I have configured my LXC to provide a DNS name to new containers. When launching a container from `images.linuxcontainers.org`, it is resolvable with the container name appended with ".lxc". When launching the "ubuntu" image from `lxd-images` it is not resolvable.

Is there some special config required for the Ubuntu cloud images?

# Steps to reproduce

Below using an image from `images.linuxcontainers.org`.
```bash
me@hosti:~$ lxc launch images:ubuntu/trusty/i386 ubuntu-working
Creating ubuntu-working
Starting ubuntu-working

me@host:~$ ping ubuntu-working.lxc
PING ubuntu-working.lxc (10.0.3.196) 56(84) bytes of data.
64 bytes from ubuntu-working.lxc (10.0.3.196): icmp_seq=1 ttl=64 time=0.071 ms
64 bytes from ubuntu-working.lxc (10.0.3.196): icmp_seq=2 ttl=64 time=0.077 ms
^C
--- ubuntu-working.lxc ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.071/0.074/0.077/0.003 ms
```

Below using an image from `lxd-images` which is an Ubuntu cloud image.
```bash
me@host:~$ lxd-images import ubuntu --alias ubuntu
Redirecting to: lxc image copy ubuntu: local: --alias ubuntu
Image copied successfully!

me@host:~$ lxc launch ubuntu ubuntu-not-working
Creating ubuntu-not-working
Starting ubuntu-not-working

me@host:~$ ping ubuntu-not-working.lxc
ping: unknown host ubuntu-not-working.lxc
```

**Comment by stgraber** [comment]
Does rebooting the container fix it?

If so, then it's likely to be a race between cloud-init (which sets the hostname) and the dhcp client (which uses it). Nothing LXD can do about this and you'd see the exact same issue on physical hardware or VM.

**Comment by henrylawson** [comment]
You are correct! Doing a reboot fixed it all :)

```bash
$ lxc exec test /sbin/reboot

$ ping test.lxc
PING test.lxc (10.0.3.236): 56 data bytes
Request timeout for icmp_seq 0
64 bytes from 10.0.3.236: icmp_seq=0 ttl=64 time=1425.464 ms
64 bytes from 10.0.3.236: icmp_seq=1 ttl=64 time=422.378 ms
64 bytes from 10.0.3.236: icmp_seq=2 ttl=64 time=342.755 ms
64 bytes from 10.0.3.236: icmp_seq=3 ttl=64 time=365.066 ms
```

For others who stumble on this, I had to do an actual reboot i.e. `lxc exec test /sbin/reboot`, restarting the container with `lxc restart test` did not fix it for me.
