### ISSUE TITLE
recent xenial 'ubuntu:' (and 'ubuntu-daily:') images don't feed cloud-init anymore

### ISSUE THREAD

**Issue by vilagithub** [lxc/lxd#1829]
xenial 'ubuntu:' images don't feed /var/lib/cloud/seed/nocloud-net/user-data since at least last Friday.

I.e. cloud-init runs but /var/lib/cloud/seed/nocloud-net/user-data is empty

Reproduced with:
lxc init ubuntu:xenial blah -p br0
cat <<EOF | lxc config set blah user.user-data -
#cloud-config
password: ubuntu
apt_update: true
apt_upgrade: true
packages:
 - bzr
EOF
lxc start blah
lxc exec blah cat /var/lib/cloud/seed/nocloud-net/user-data

results in:

#cloud-config
{}

Doing the same with a trusty image results in:
#cloud-config
password: ubuntu
apt_update: true
apt_upgrade: true
packages:
 - bzr

**Comment by vilagithub** [comment]
Meh, forget about '-p br0' to reproduce, it's to setup my local bridge.

**Comment by stgraber** [comment]
That's intentional. Per cloud-init upstream's request (@smoser), LXD only feeds cloud-init at container create and copy time, not at startup time.

**Comment by vilagithub** [comment]
Errr, how can I feed cloud-init at create time then ? That's what I was intending by doing init/config/start.

**Comment by stgraber** [comment]
From the command line you can't, unless you're using a profile.

I'll look into changing the time we apply the template from being at actual creation time to instead be at the first start after it which would make more sense, but it may be tricky to do...

**Comment by vilagithub** [comment]
oh, right, so instead of using lxc config I should put that into a profile and pass the profile at init time, will try asap and report

**Comment by stgraber** [comment]
Yeah, that should work until I fix the logic in LXD to be a bit more user friendly.

**Comment by smoser** [comment]
So just to clarify, I haven't thought enough about it to have feelings on when files user-data and meta-data should be written.  What I did not like is that they were being written on every 'start'.

It seemed much more reasonable that the user would want lxd to insert files once than every time a start occurred (such as host reboot).

**Comment by stgraber** [comment]
Yeah, I think I have a way to get us the best of both worlds, I'll work on a solution later tonight.

The idea is basically that we only run the templates when the container starts, so when creating or cloning, we just mark the container as "must run XYZ templates" but those are only actually run at next startup.

This allows for the init + set + start workflow and also fixes an issue I had in the past where not all container metadata is available at create time.

**Comment by vilagithub** [comment]
Ack, thanks for the fix !
Until it's available, I went with 'lxc push user-data blah/var/lib/cloud/seed/nocloud-net/user-data' instead of 'lxc config set' (I'll revert that once the fix is available)
