### ISSUE TITLE
Permission denied - failed to create directory '/usr/lib/x86_64-linux-gnu/lxc/sys/firmware/efi/'

### ISSUE THREAD

**Issue by patademahesh** [lxc/lxd#1839]
Hi,

I am getting below error while trying to start container.

lxd Version: 2.0.0~rc6-0ubuntu2~ubuntu14.04.1~ppa1
Ubuntu 14.04.4 LTS

```
root@vod-mc2:~# lxc info --show-log mc-videos-vod2|grep ERROR
            lxc 20160329054823.207 ERROR    lxc_utils - utils.c:mkdir_p:253 - Permission denied - failed to create directory '/usr/lib/x86_64-linux-gnu/lxc/sys/firmware/efi/'
            lxc 20160329054823.208 ERROR    lxc_utils - utils.c:safe_mount:1691 - No such file or directory - Failed to mount /dev/mqueue onto /usr/lib/x86_64-linux-gnu/lxc/dev/mqueue
            lxc 20160329110801.476 ERROR    lxc_utils - utils.c:mkdir_p:253 - Permission denied - failed to create directory '/usr/lib/x86_64-linux-gnu/lxc/sys/firmware/efi/'
            lxc 20160329110801.476 ERROR    lxc_utils - utils.c:safe_mount:1691 - No such file or directory - Failed to mount /dev/mqueue onto /usr/lib/x86_64-linux-gnu/lxc/dev/mqueue
            lxc 20160330145643.237 ERROR    lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
            lxc 20160330145643.237 ERROR    lxc_start - start.c:lxc_fini:554 - failed to run post-stop hooks for container 'mc-videos'.
            lxc 20160330145729.650 ERROR    lxc_utils - utils.c:mkdir_p:253 - Permission denied - failed to create directory '/usr/lib/x86_64-linux-gnu/lxc/sys/firmware/efi/'
            lxc 20160330145729.650 ERROR    lxc_utils - utils.c:safe_mount:1691 - No such file or directory - Failed to mount /dev/mqueue onto /usr/lib/x86_64-linux-gnu/lxc/dev/mqueue
            lxc 20160330163733.817 ERROR    lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
            lxc 20160330163733.817 ERROR    lxc_start - start.c:lxc_fini:554 - failed to run post-stop hooks for container 'mc-videos'.
            lxc 20160330164345.275 ERROR    lxc_utils - utils.c:mkdir_p:253 - Permission denied - failed to create directory '/usr/lib/x86_64-linux-gnu/lxc/sys/firmware/efi/'
            lxc 20160330164345.275 ERROR    lxc_utils - utils.c:safe_mount:1691 - No such file or directory - Failed to mount /dev/mqueue onto /usr/lib/x86_64-linux-gnu/lxc/dev/mqueue
            lxc 20160330170312.266 ERROR    lxc_utils - utils.c:mkdir_p:253 - Permission denied - failed to create directory '/usr/lib/x86_64-linux-gnu/lxc/sys/firmware/efi/'
            lxc 20160330170312.266 ERROR    lxc_utils - utils.c:safe_mount:1691 - No such file or directory - Failed to mount /dev/mqueue onto /usr/lib/x86_64-linux-gnu/lxc/dev/mqueue
            lxc 20160330215035.149 ERROR    lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
            lxc 20160330215035.149 ERROR    lxc_start - start.c:lxc_fini:554 - failed to run post-stop hooks for container 'mc-videos'.
            lxc 20160330215307.210 ERROR    lxc_utils - utils.c:mkdir_p:253 - Permission denied - failed to create directory '/usr/lib/x86_64-linux-gnu/lxc/sys/firmware/efi/'
            lxc 20160330215307.211 ERROR    lxc_utils - utils.c:safe_mount:1691 - No such file or directory - Failed to mount /dev/mqueue onto /usr/lib/x86_64-linux-gnu/lxc/dev/mqueue
            lxc 20160401213242.228 ERROR    lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
            lxc 20160401213242.228 ERROR    lxc_start - start.c:lxc_init:464 - failed to run pre-start hooks for container 'mc-videos-vod2'.
            lxc 20160401213242.228 ERROR    lxc_start - start.c:__lxc_start:1245 - failed to initialize the container

```

Thanks
Mahesh

**Comment by stgraber** [comment]
The mqueue and firmware stuff aren't the problem, the pre-start failing to execute is.

Hopefully /var/log/lxd/lxd.log has some more information.

We also need at least the output of "lxc info".

Note that in the future it is a good idea to fill our bug reporting template as it's designed specifically so I don't have to ask you for all of those again...

**Comment by patademahesh** [comment]
Sure i'll follow the template way.

apicompat: 0
auth: trusted
environment:
  addresses:
  - 172.29.141.132:8443
  - 10.0.3.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIF3DCCA8SgAwIBAgIQczBkC+cwZ7x02UAhE4irJDANBgkqhkiG9w0BAQsFADA8
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRwwGgYDVQQDDBNyb290QHZv
    ZC1tYzIuaW4uY29tMB4XDTE2MDMyODEwMzI0MloXDTI2MDMyNjEwMzI0MlowPDEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEcMBoGA1UEAwwTcm9vdEB2b2Qt
    bWMyLmluLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMgLL1jP
    OxyZNNbolz6Dj7sYZJ04enBXq7OMNH+3nLdvqOOHUFkBuyOxfFxsIyKoDejeB4cJ
    WUPc6ID+F6iLDHNC/+Tm8X4bztnoBNAx83PchMapyaSIf8kxWXT/ZTYlvSC2Js2C
    ldry9iDKrfs5O44nLiQ6UYV9WjWoVfvNvbBw4a96qDLtwY5JKRGYPDdPqH0yi+gL
    svrpTbCwtKNNn8Uy4q0XfWjefn8mkkcmyaUsh8v4CiOT/eKDz9RadEtNcxxDo3dA
    CzySpR7F6MSC9M41BtLHOw6ojl9+TsoBGIlopiqju3oXKXI98Ty5d0blX3Dr9tIy
    KU4O5btDc9Cjj51D4pnogUJv1C+7yNgiJwpTyXk/dhlYE34CHPZMJQX97zS9C56j
    zfqLLiADWVLPqjg0Dm6CMzpdGy+IKKuBNMhnp8YPTtpJUKOiOtcNZVXQC3juv27F
    tR8S7TcTN5rLFFmivt7CCNUUO/O4zeh5X4PFnmQiJkCociNuYKq67V+Z137zzjng
    1ION0w/x0lzdYyXyf5/f2rnvFd66JFOSpKlUrw7XmmK7OoC2kUfS0qqgCI0gBxxA
    tGRkHDpsv9Gss+DSm6w5RCOKeJm0SRbq2Djaglf0uZalxfN5EEMOdykqvQbk5ile
    HFGHO9hATYUbQS8uaOEEbrWyfMI0EupXhQm7AgMBAAGjgdkwgdYwDgYDVR0PAQH/
    BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwgaAGA1Ud
    EQSBmDCBlYIOdm9kLW1jMi5pbi5jb22CETE3Mi4yOS4xNDEuMTMyLzE2ghtmZTgw
    Ojo1ZWI5OjFmZjpmZWUxOjQ3MzgvNjSCCzEwLjAuMy4xLzI0ghxmZTgwOjo1MDUx
    OjhmZmY6ZmVkMzo2OTk1LzY0ghxmZTgwOjo4NDQ1OjZkZmY6ZmUzMjpiNmEzLzY0
    ggpmZTgwOjoxLzY0MA0GCSqGSIb3DQEBCwUAA4ICAQCm6O6AUDL81v5kTvv+9lyV
    pyq3x36c34G1TwWiIO5mJNcSoRHnwKXPHxgXAoU4uluq06U3PpLXFABR+mZrpJJ/
    HZLnQqCZ/SsyMGKoxn5jQY1RZRydUUneWvO2uIZXRIYkA8uMi51a/+a9d0j4uTKy
    SemC38JMYpJPMpIfciFxhppC1hv/PITss9AeJI4/1TdxDNbNUMzNRn858TQjX+5b
    qSoIubcKIzmVSKTSWCMUHdr7XChzKryKwxaUGFe1V9d5nuYYdJVqIIni/WZn5gsw
    HxeXQfPpgl0VFH6KsbwdhKGI3ImgIo/gWcJVeBdn11XOmrfeH3kI3/OXOk0iq1dg
    I7WuwNSDYaTMl5yr8Q90dMyEWL6gaNUZGFLHRTK36nUT/eaEj9sLce7KutxBOplW
    roqrjWnhgWFIjiH+jxPo0BcuHo+zqVBlDEpBYBA/CoQiuytmKKNp31t2tczns+Nc
    +D8K3/ihpa4hTOqFMx/iRdEAS3Vb7JXJU8qJaCFjYK3iabg6uwKfvKFeocEzbV4w
    R4/SwmsO3M6/79fhC5ip8x4ekbWCelurGsTdR/rYxr/rfY8V/eXSzYVBYp1zGped
    pz3+/jdpc0zsj3+4uW2LKORAMhxHcN5kzg4xuNJOzNm8V/AQRu7o7AqsIykBoOXs
    0we/Tk6upvhOyIAunC29iQ==
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc13
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.19.0-56-generic
  server: lxd
  serverpid: 1863
  serverversion: 2.0.0.rc6
  storage: lvm
  storageversion: 2.02.98(2) (2012-10-15) / 1.02.77 (2012-10-15) / 4.29.0
config:
  core.https_address: '[::]'
  core.trust_password: true
  storage.lvm_thinpool_name: lxc
  storage.lvm_vg_name: lxc
public: false

- /var/log/lxd/lxd.log
`t=2016-04-01T22:03:18+0530 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-04-01T22:03:18+0530 lvl=info msg=handling ip=@ method=GET url=/1.0/containers/mc-videos-vod2
t=2016-04-01T22:03:18+0530 lvl=info msg=handling url=/1.0/containers/mc-videos-vod2/state ip=@ method=PUT
t=2016-04-01T22:03:18+0530 lvl=info msg=handling method=GET url=/1.0/operations/7db552c2-0ffc-4437-a160-ffcea7c2866b/wait ip=@
t=2016-04-01T22:03:18+0530 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-04-01T22:03:18+0530 lvl=info msg=handling method=GET url=/internal/containers/9/onstart ip=@
t=2016-04-01T22:04:45+0530 lvl=info msg=handling ip=@ method=GET url=/1.0
t=2016-04-01T22:04:45+0530 lvl=info msg=handling method=GET url="/1.0/containers?recursion=1" ip=@
t=2016-04-01T22:04:45+0530 lvl=info msg=handling method=GET url="/1.0/containers/ibnkhabar-vod2/snapshots?recursion=1" ip=@
t=2016-04-01T22:04:45+0530 lvl=info msg=handling url="/1.0/containers/mc-videos-vod2/snapshots?recursion=1" ip=@ method=GET
t=2016-04-01T22:04:45+0530 lvl=info msg=handling method=GET url="/1.0/containers/mc-shows-vod2/snapshots?recursion=1" ip=@
t=2016-04-01T22:04:45+0530 lvl=info msg=handling method=GET url=/1.0/containers/ibnkhabar-vod2/state ip=@
t=2016-04-01T22:05:12+0530 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-04-01T22:05:12+0530 lvl=info msg=handling method=GET url=/1.0/containers/mc-videos-vod2 ip=@
t=2016-04-01T22:05:12+0530 lvl=info msg=handling method=PUT url=/1.0/containers/mc-videos-vod2/state ip=@
t=2016-04-01T22:05:12+0530 lvl=info msg=handling method=GET url=/1.0/operations/8af35f5f-3bda-40e8-928d-73b9a0cb62ae/wait ip=@
t=2016-04-01T22:05:12+0530 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-04-01T22:05:12+0530 lvl=info msg=handling method=GET url=/internal/containers/9/onstart ip=@
`
/var/log/lxd/lxd.log (END)

[info_logs.txt](https://github.com/lxc/lxd/files/199996/info_logs.txt)



- output of the client with --debug
```
# lxc start mc-videos-vod2 --debug
DBUG[04-01|22:05:12] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_extensions":[],"api_status":"development","api_version":"1.0","auth":"trusted","config":{"core.https_address":"[::]","core.trust_password":true,"storage.lvm_thinpool_name":"lxc","storage.lvm_vg_name":"lxc"},"environment":{"addresses":["172.29.141.132:8443","10.0.3.1:8443"],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\nMIIF3DCCA8SgAwIBAgIQczBkC+cwZ7x02UAhE4irJDANBgkqhkiG9w0BAQsFADA8\nMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRwwGgYDVQQDDBNyb290QHZv\nZC1tYzIuaW4uY29tMB4XDTE2MDMyODEwMzI0MloXDTI2MDMyNjEwMzI0MlowPDEc\nMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEcMBoGA1UEAwwTcm9vdEB2b2Qt\nbWMyLmluLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMgLL1jP\nOxyZNNbolz6Dj7sYZJ04enBXq7OMNH+3nLdvqOOHUFkBuyOxfFxsIyKoDejeB4cJ\nWUPc6ID+F6iLDHNC/+Tm8X4bztnoBNAx83PchMapyaSIf8kxWXT/ZTYlvSC2Js2C\nldry9iDKrfs5O44nLiQ6UYV9WjWoVfvNvbBw4a96qDLtwY5JKRGYPDdPqH0yi+gL\nsvrpTbCwtKNNn8Uy4q0XfWjefn8mkkcmyaUsh8v4CiOT/eKDz9RadEtNcxxDo3dA\nCzySpR7F6MSC9M41BtLHOw6ojl9+TsoBGIlopiqju3oXKXI98Ty5d0blX3Dr9tIy\nKU4O5btDc9Cjj51D4pnogUJv1C+7yNgiJwpTyXk/dhlYE34CHPZMJQX97zS9C56j\nzfqLLiADWVLPqjg0Dm6CMzpdGy+IKKuBNMhnp8YPTtpJUKOiOtcNZVXQC3juv27F\ntR8S7TcTN5rLFFmivt7CCNUUO/O4zeh5X4PFnmQiJkCociNuYKq67V+Z137zzjng\n1ION0w/x0lzdYyXyf5/f2rnvFd66JFOSpKlUrw7XmmK7OoC2kUfS0qqgCI0gBxxA\ntGRkHDpsv9Gss+DSm6w5RCOKeJm0SRbq2Djaglf0uZalxfN5EEMOdykqvQbk5ile\nHFGHO9hATYUbQS8uaOEEbrWyfMI0EupXhQm7AgMBAAGjgdkwgdYwDgYDVR0PAQH/\nBAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwgaAGA1Ud\nEQSBmDCBlYIOdm9kLW1jMi5pbi5jb22CETE3Mi4yOS4xNDEuMTMyLzE2ghtmZTgw\nOjo1ZWI5OjFmZjpmZWUxOjQ3MzgvNjSCCzEwLjAuMy4xLzI0ghxmZTgwOjo1MDUx\nOjhmZmY6ZmVkMzo2OTk1LzY0ghxmZTgwOjo4NDQ1OjZkZmY6ZmUzMjpiNmEzLzY0\nggpmZTgwOjoxLzY0MA0GCSqGSIb3DQEBCwUAA4ICAQCm6O6AUDL81v5kTvv+9lyV\npyq3x36c34G1TwWiIO5mJNcSoRHnwKXPHxgXAoU4uluq06U3PpLXFABR+mZrpJJ/\nHZLnQqCZ/SsyMGKoxn5jQY1RZRydUUneWvO2uIZXRIYkA8uMi51a/+a9d0j4uTKy\nSemC38JMYpJPMpIfciFxhppC1hv/PITss9AeJI4/1TdxDNbNUMzNRn858TQjX+5b\nqSoIubcKIzmVSKTSWCMUHdr7XChzKryKwxaUGFe1V9d5nuYYdJVqIIni/WZn5gsw\nHxeXQfPpgl0VFH6KsbwdhKGI3ImgIo/gWcJVeBdn11XOmrfeH3kI3/OXOk0iq1dg\nI7WuwNSDYaTMl5yr8Q90dMyEWL6gaNUZGFLHRTK36nUT/eaEj9sLce7KutxBOplW\nroqrjWnhgWFIjiH+jxPo0BcuHo+zqVBlDEpBYBA/CoQiuytmKKNp31t2tczns+Nc\n+D8K3/ihpa4hTOqFMx/iRdEAS3Vb7JXJU8qJaCFjYK3iabg6uwKfvKFeocEzbV4w\nR4/SwmsO3M6/79fhC5ip8x4ekbWCelurGsTdR/rYxr/rfY8V/eXSzYVBYp1zGped\npz3+/jdpc0zsj3+4uW2LKORAMhxHcN5kzg4xuNJOzNm8V/AQRu7o7AqsIykBoOXs\n0we/Tk6upvhOyIAunC29iQ==\n-----END CERTIFICATE-----\n","driver":"lxc","driver_version":"2.0.0.rc13","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"3.19.0-56-generic","server":"lxd","server_pid":1863,"server_version":"2.0.0.rc6","storage":"lvm","storage_version":"2.02.98(2) (2012-10-15) / 1.02.77 (2012-10-15) / 4.29.0"},"public":false}}

DBUG[04-01|22:05:12] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"architecture":"x86_64","config":{"boot.autostart":"on","limits.cpu":"12","limits.memory":"12GB","security.privileged":"true","volatile.base_image":"a41714ac7035561a04019ecdd8a0fc2ae68a0b01c656f5b166f8754b2d77e30c","volatile.eth0.hwaddr":"00:16:3e:2d:3b:b2","volatile.last_state.idmap":"[]"},"created_at":"2016-03-29T09:43:27Z","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"boot.autostart":"on","limits.cpu":"12","limits.memory":"12GB","security.privileged":"true","volatile.base_image":"a41714ac7035561a04019ecdd8a0fc2ae68a0b01c656f5b166f8754b2d77e30c","volatile.eth0.hwaddr":"00:16:3e:2d:3b:b2","volatile.last_state.idmap":"[]"},"expanded_devices":{"eth0":{"name":"eth0","nictype":"macvlan","parent":"mvlan0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"mc-videos-vod2","profiles":["default"],"stateful":false,"status":"Stopped","status_code":102}}

DBUG[04-01|22:05:12] Putting {"action":"start","force":false,"stateful":false,"timeout":-1}
 to http://unix.socket/1.0/containers/mc-videos-vod2/state
DBUG[04-01|22:05:12] Raw response: {"type":"async","status":"Operation created","status_code":100,"metadata":{"id":"8af35f5f-3bda-40e8-928d-73b9a0cb62ae","class":"task","created_at":"2016-04-01T22:05:12.239471793+05:30","updated_at":"2016-04-01T22:05:12.239471793+05:30","status":"Running","status_code":103,"resources":{"containers":["/1.0/containers/mc-videos-vod2"]},"metadata":null,"may_cancel":false,"err":""},"operation":"/1.0/operations/8af35f5f-3bda-40e8-928d-73b9a0cb62ae"}

DBUG[04-01|22:05:12] 1.0/operations/8af35f5f-3bda-40e8-928d-73b9a0cb62ae/wait
DBUG[04-01|22:05:27] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"id":"8af35f5f-3bda-40e8-928d-73b9a0cb62ae","class":"task","created_at":"2016-04-01T22:05:12.239471793+05:30","updated_at":"2016-04-01T22:05:12.239471793+05:30","status":"Failure","status_code":400,"resources":{"containers":["/1.0/containers/mc-videos-vod2"]},"metadata":null,"may_cancel":false,"err":"Error calling 'lxd forkstart mc-videos-vod2 /var/lib/lxd/containers /var/log/lxd/mc-videos-vod2/lxc.conf': err='exit status 1'"}}

error: Error calling 'lxd forkstart mc-videos-vod2 /var/lib/lxd/containers /var/log/lxd/mc-videos-vod2/lxc.conf': err='exit status 1'
Try `lxc info --show-log mc-videos-vod2` for more info
```

**Comment by patademahesh** [comment]
# lxc info
`apicompat: 0
auth: trusted
environment:
  addresses:
  - 172.29.141.132:8443
  - 10.0.3.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIF3DCCA8SgAwIBAgIQczBkC+cwZ7x02UAhE4irJDANBgkqhkiG9w0BAQsFADA8
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRwwGgYDVQQDDBNyb290QHZv
    ZC1tYzIuaW4uY29tMB4XDTE2MDMyODEwMzI0MloXDTI2MDMyNjEwMzI0MlowPDEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEcMBoGA1UEAwwTcm9vdEB2b2Qt
    bWMyLmluLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMgLL1jP
    OxyZNNbolz6Dj7sYZJ04enBXq7OMNH+3nLdvqOOHUFkBuyOxfFxsIyKoDejeB4cJ
    WUPc6ID+F6iLDHNC/+Tm8X4bztnoBNAx83PchMapyaSIf8kxWXT/ZTYlvSC2Js2C
    ldry9iDKrfs5O44nLiQ6UYV9WjWoVfvNvbBw4a96qDLtwY5JKRGYPDdPqH0yi+gL
    svrpTbCwtKNNn8Uy4q0XfWjefn8mkkcmyaUsh8v4CiOT/eKDz9RadEtNcxxDo3dA
    CzySpR7F6MSC9M41BtLHOw6ojl9+TsoBGIlopiqju3oXKXI98Ty5d0blX3Dr9tIy
    KU4O5btDc9Cjj51D4pnogUJv1C+7yNgiJwpTyXk/dhlYE34CHPZMJQX97zS9C56j
    zfqLLiADWVLPqjg0Dm6CMzpdGy+IKKuBNMhnp8YPTtpJUKOiOtcNZVXQC3juv27F
    tR8S7TcTN5rLFFmivt7CCNUUO/O4zeh5X4PFnmQiJkCociNuYKq67V+Z137zzjng
    1ION0w/x0lzdYyXyf5/f2rnvFd66JFOSpKlUrw7XmmK7OoC2kUfS0qqgCI0gBxxA
    tGRkHDpsv9Gss+DSm6w5RCOKeJm0SRbq2Djaglf0uZalxfN5EEMOdykqvQbk5ile
    HFGHO9hATYUbQS8uaOEEbrWyfMI0EupXhQm7AgMBAAGjgdkwgdYwDgYDVR0PAQH/
    BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwgaAGA1Ud
    EQSBmDCBlYIOdm9kLW1jMi5pbi5jb22CETE3Mi4yOS4xNDEuMTMyLzE2ghtmZTgw
    Ojo1ZWI5OjFmZjpmZWUxOjQ3MzgvNjSCCzEwLjAuMy4xLzI0ghxmZTgwOjo1MDUx
    OjhmZmY6ZmVkMzo2OTk1LzY0ghxmZTgwOjo4NDQ1OjZkZmY6ZmUzMjpiNmEzLzY0
    ggpmZTgwOjoxLzY0MA0GCSqGSIb3DQEBCwUAA4ICAQCm6O6AUDL81v5kTvv+9lyV
    pyq3x36c34G1TwWiIO5mJNcSoRHnwKXPHxgXAoU4uluq06U3PpLXFABR+mZrpJJ/
    HZLnQqCZ/SsyMGKoxn5jQY1RZRydUUneWvO2uIZXRIYkA8uMi51a/+a9d0j4uTKy
    SemC38JMYpJPMpIfciFxhppC1hv/PITss9AeJI4/1TdxDNbNUMzNRn858TQjX+5b
    qSoIubcKIzmVSKTSWCMUHdr7XChzKryKwxaUGFe1V9d5nuYYdJVqIIni/WZn5gsw
    HxeXQfPpgl0VFH6KsbwdhKGI3ImgIo/gWcJVeBdn11XOmrfeH3kI3/OXOk0iq1dg
    I7WuwNSDYaTMl5yr8Q90dMyEWL6gaNUZGFLHRTK36nUT/eaEj9sLce7KutxBOplW
    roqrjWnhgWFIjiH+jxPo0BcuHo+zqVBlDEpBYBA/CoQiuytmKKNp31t2tczns+Nc
    +D8K3/ihpa4hTOqFMx/iRdEAS3Vb7JXJU8qJaCFjYK3iabg6uwKfvKFeocEzbV4w
    R4/SwmsO3M6/79fhC5ip8x4ekbWCelurGsTdR/rYxr/rfY8V/eXSzYVBYp1zGped
    pz3+/jdpc0zsj3+4uW2LKORAMhxHcN5kzg4xuNJOzNm8V/AQRu7o7AqsIykBoOXs
    0we/Tk6upvhOyIAunC29iQ==
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc13
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.19.0-56-generic
  server: lxd
  serverpid: 1863
  serverversion: 2.0.0.rc6
  storage: lvm
  storageversion: 2.02.98(2) (2012-10-15) / 1.02.77 (2012-10-15) / 4.29.0
config:
  core.https_address: '[::]'
  core.trust_password: true
  storage.lvm_thinpool_name: lxc
  storage.lvm_vg_name: lxc
public: false`

**Comment by patademahesh** [comment]
Steps to reproduce.
1. set "lxc config set test security.privileged true"
2. start container

**Comment by stgraber** [comment]
Reproduced here, looks like it's a combination of privileged containers and lvm which is causing some problems. Oddly enough, not during the testsuite though.

**Comment by stgraber** [comment]
ah, not related to privileged actually, just related to whether the filesystem was remapped or not.

**Comment by patademahesh** [comment]
do i need to update my LXD version to solve this ?

**Comment by stgraber** [comment]
You'll need to wait for the next rc, yes, should be just a few days.

Until then you can do "sudo umount /var/lib/lxd/containers/NAME" before starting the container again, that should do the trick.

**Comment by patademahesh** [comment]
Oh.. that did the trick.. Thank you so much stgraber. Just for my knowledge, could you tell me In which log you saw that error ?

**Comment by patademahesh** [comment]
umount trick is working only if try to start container after failing. To reproduce

1. create container
2. stop container
3. umount /var/lib/lxd/containers/NAME - this will fail with error not mounted
3. start container (It will fail even if device is not mounted, checked in df -h)
4. now umount /var/lib/lxd/containers/NAME
5. start container - This time it starts

Thanks
Mahesh

**Comment by stgraber** [comment]
The error was showing up in debug mode.

**Comment by patademahesh** [comment]
I got the actual issue. Issue was i am trying to set security.privileged config key after creating container. After removing the config key container started without any errors. May be this is because of rootfs permissions ?

Thanks,
Mahesh

**Comment by patademahesh** [comment]
and that too i was trying to set while the container is in running state. It works If I try to to set it when container is in shutdown state.

@stgraber - I think one should have checks / warnings while setting such keys which requires container to be in shutdown state. ? Please suggest.


Thanks,
Mahesh

**Comment by stgraber** [comment]
you can change that key just fine while the container is running

**Comment by stgraber** [comment]
It does require a restart to be effective (as documented in doc/configuration.md)

The issue here was a storage bug and it's fixed in rc9.

**Comment by patademahesh** [comment]
Ok. Thanks for the quick response Stephane :+1:
