### ISSUE TITLE
Inaccessible partitions created inside container

### ISSUE THREAD

**Issue by robsanderson** [lxc/lxd#1841]
* Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
lxc info
apicompat: 0
auth: trusted
environment:
  addresses:
  - 10.10.8.11:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc12
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-15-generic
  server: lxd
  serverpid: 22440
  serverversion: 2.0.0.rc5
  storage: dir
  storageversion: ""
config:
  core.https_address: 10.10.8.11:8443
  core.trust_password: true
public: false

   * Kernel version: 4.4.0-15-generic
   * LXC version: 2.0.0~rc12-0ubuntu1
   * LXD version: 2.0.0~rc5-0ubuntu1
   * Storage backend in use: dir

# Example container config
config:
  raw.lxc: |
    lxc.aa_profile=unconfined
    lxc.cgroup.devices.allow = b 8:* rwm
  security.privileged: "true"
  volatile.base_image: 4e8bb333466929ed0c7d25ff5dcc42e7241fd2dad22c5e4e40ae0b60be6d9f53
  volatile.eth0.hwaddr: 00:16:3e:54:8d:0a
  volatile.last_state.idmap: '[]'
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: eth0
    type: nic
  root:
    path: /
    type: disk
  sda:
    path: /dev/sda
    type: unix-block

# Issue description
$ parted /dev/sda mklabel gpt
$ parted /dev/sda mkpart data xfs 1 100G
$ parted /dev/sda p
Partition Table: gpt
Disk Flags:

Number  Start   End    Size   File system  Name  Flags
 1      1049kB  100GB  100GB  xfs          data

$ grep sda /proc/partitions
   8        0 1953514584 sda
   8        1   97654784 sda1

ls -la /dev/sda*
brw-r----- 1 root root 8, 0 Apr  1 20:56 /dev/sda

**Comment by stgraber** [comment]
That's not a bug. Unprivileged containers cannot create device nodes and even if they could, the device cgroup policy wouldn't allow it.

If you partition a disk inside the container you must then add a matching disk entry for every partition in the container config.

**Comment by stgraber** [comment]
Oh, sorry, only noticed now that you container is privileged and unconfined and has a whitelist entry for cgroups.

**Comment by stgraber** [comment]
Assuming the container is Ubuntu 16.04, the problem is very likely that systemd refuses to run udev in a container so device nodes never get created for you, doing a manual mknod would fix that.

**Comment by robsanderson** [comment]
Thanks for the fast response. I'll see if I can get lxc.hook.autodev working.

**Comment by stgraber** [comment]
You may be able to get it working with:

security.privileged: true
raw.lxc: |-
  lxc.aa_profile=unconfined
  lxc.cgroup.devices.allow = b 8:* rwm
  lxc.mount.auto=
  lxc.mount.auto=sys:rw proc:mixed cgroup:mixed

That should make systemd happy about starting udev in the container. Note that this may mess some of your host settings though, on my system it reset the soundcard volume for some reason :)

**Comment by robsanderson** [comment]
Doesn't appear to although I do see a strange line in dmesg:

[856923.560494]  sda: sda1

**Comment by stgraber** [comment]
Looks like the normal kernel message for when it's asked to reload the partition table.

**Comment by robsanderson** [comment]
Appears to be just failing to mknod then.
