### ISSUE TITLE
Show the remote name in client status and error messages (especially in bulk mode)

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#1843]
When a command fails on a remote lxd, the `lxc info` hint doesn't include the remote name:

$ lxc launch n-team00:75182b1241be n-team00:foo01
 Creating foo01
 Starting foo01
 error: Error calling 'lxd forkstart foo01 /var/lib/lxd/containers /var/log/lxd/foo01/lxc.conf': err='exit status 1'
 Try `lxc info --show-log foo01` for more info

Preserving the remote name would be nice.

**Comment by stgraber** [comment]
Might be a bit tricky, but I agree, especially for commands supporting bulk mode like:

lxc start remote1:abc remote2:abc remote3:abc
