### ISSUE TITLE
Ubuntu 16.04 LXD/LXC container network - gets 2 LXCBR0 bridges & no IP addresses

### ISSUE THREAD

**Issue by bmullan** [lxc/lxd#1844]
# Required information

 * Distribution: ubuntu
 * Distribution version:  16.04 beta
 * The output of "lxc info" or if that fails:

bmullan@ip-10-169-232-106:~$ lxc info
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
**< removed >**
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc15
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-16-generic
  server: lxd
  serverpid: 3063
  serverversion: 2.0.0.rc8
  storage: dir
  storageversion: ""
config: {}
public: false
bmullan@ip-10-169-232-106:~$   

 * Kernel version:

bmullan@ip-10-169-232-106:~$ **uname -a**
Linux ip-10-169-232-106 4.4.0-16-generic #32-Ubuntu SMP Thu Mar 24 22:38:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

   * LXC version:

bmullan@ip-10-169-232-106:~$ **lxc --version**
2.0.0.rc8

# Issue description

Installed & updated/upgraded Ubuntu 16.04 server on AWS (ami-f95a5593).
Added LXD/LXC to it & created 2 LXC containers CN1, CN2.

Before I "start" CN1 & CN2 everything looks OK & there is a single LXCBR0 bridge with a 10.0.3.x address on it.

I start both CN1 & CN2 each as a Privileged Container:

lxc launch images:ubuntu/xenial/amd64 cn1 -c security.privileged=true
lxc launch images:ubuntu/xenial/amd64 cn2 -c security.privileged=true

As soon as I do that I find that neither CN1 or CN2 get an IP address (a 10.0.3.x).

I also now see that there is an LXCBR0 & a LXDBR0 Bridges in existence 

# Steps to reproduce

# NOTE:  Neither LXC Container CN1 or CN2 have been started yet.
   and **only** a **single** LXCBR0 bridge exists w/10.0.3.1 address.

bmullan@ip-10-169-232-106:~$ **ifconfig**
eth0      Link encap:Ethernet  HWaddr 22:00:0b:93:00:9d  
          inet addr:10.169.232.106  Bcast:10.169.232.255  Mask:255.255.255.0
          inet6 addr: fe80::2000:bff:fe93:9d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:276 errors:0 dropped:0 overruns:0 frame:0
          TX packets:367 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:33472 (33.4 KB)  TX bytes:38668 (38.6 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:549 (549.0 B)  TX bytes:549 (549.0 B)

**lxcbr0**    Link encap:Ethernet  HWaddr 1a:39:fe:de:1a:78  
          inet addr:10.0.3.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::1839:feff:fede:1a78/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:37 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:5218 (5.2 KB)

# Confirmation that both CN1 & CN2 are STOPPED....

bmullan@ip-10-169-232-106:~$ **lxc list**
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| cn1  | STOPPED |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+
| cn2  | STOPPED |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+

# ***Start CN1 & CN2*** 

bmullan@ip-10-169-232-106:~$ lxc start cn1
bmullan@ip-10-169-232-106:~$ lxc start cn2

# lxc list now shows CN1 & CN2 running but NO IP addresses ?

bmullan@ip-10-169-232-106:~$ **lxc list**
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| cn1  | RUNNING |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+
| cn2  | RUNNING |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+

#  **Now there is an LXCBR0 and a LXDBR0 bridge but the CN1 & CN2 containers still don't have an IP address **

bmullan@ip-10-169-232-106:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 22:00:0b:93:00:9d  
          inet addr:10.169.232.106  Bcast:10.169.232.255  Mask:255.255.255.0
          inet6 addr: fe80::2000:bff:fe93:9d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:512 errors:0 dropped:0 overruns:0 frame:0
          TX packets:555 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:54610 (54.6 KB)  TX bytes:65515 (65.5 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:549 (549.0 B)  TX bytes:549 (549.0 B)

**lxcbr0**    Link encap:Ethernet  HWaddr fe:62:fe:f7:6a:be  
          inet addr:10.0.3.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::1839:feff:fede:1a78/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:29 errors:0 dropped:0 overruns:0 frame:0
          TX packets:42 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2663 (2.6 KB)  TX bytes:6224 (6.2 KB)

**lxdbr0**   Link encap:Ethernet  HWaddr b2:b4:03:32:40:6c  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:310 (310.0 B)

vethA761UC Link encap:Ethernet  HWaddr fe:62:fe:f7:6a:be  
          inet6 addr: fe80::fc62:feff:fef7:6abe/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:33 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:648 (648.0 B)  TX bytes:4515 (4.5 KB)

vethQOLNOK Link encap:Ethernet  HWaddr fe:a3:62:09:8d:1a  
          inet6 addr: fe80::fca3:62ff:fe09:8d1a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:21 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2421 (2.4 KB)  TX bytes:4428 (4.4 KB)

bmullan@ip-10-169-232-106:~$ 

bmullan@ip-10-169-232-106:~$ **lxc list**
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| cn1  | RUNNING |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+
| cn2  | RUNNING |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+

**Comment by stgraber** [comment]
The second bridge is "lxdbr0" and that part is normal, we are going to move all LXD users to using that bridge and lxcbr0 will disappear unless you also use good old LXC alongside LXD.

What's not normal, but we have a few reports of it before is that your system already switched over to lxdbr0 despite us having some code in the upgrade process to prevent this from happening.

For the time being, the easiest way back to normal behavior is: lxc profile device set default eth0 parent lxcbr0

**Comment by stgraber** [comment]
We plan on moving everyone to lxdbr0 at some point next week. I've got the new package ready for upload already.

**Comment by bmullan** [comment]
Thanks Stephane !

The command below worked:

$ **lxc profile device set default eth0 parent lxcbr0**

and lxc list now shows the Containers with a 10.0.3.x ip.

Brian

**Comment by aarnaud** [comment]
Hi @stgraber,

The plan to moving everyone to lxdbr0 will use the same network and netmask configuration which is set in `/etc/default/lxc-net` ?

Else, where is the ipv4 and DHCP configuration for lxdbr0 ?

**Comment by stgraber** [comment]
Nope, lxdbr0 is configured in /etc/default/lxd-bridge, typically by running "dpkg-reconfigure lxd".

The new package will improve dpkg-reconfigure quite a bit by giving examples and being more clear as to what's expected as far as input.

**Comment by bungle** [comment]
What is the correct procedure to migrate to lxdbr0 from lxcbr0? I'm running lxcbr0 with default settings.

**Comment by tych0** [comment]
http://tycho.ws/blog/2016/04/lxdbr0.html touches on that, basically `dpkg-reconfigure lxd` should get you there with reasonable answers to the questions.

**Comment by bungle** [comment]
@tych0 Thank you fo the article! Got it to work now.
