### ISSUE TITLE
Add import/export feature for images in the lxc command line tool

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#185]

**Comment by vtolstov** [comment]
Does it mean that can be possible to export container to tar.gz file ? Or something different

**Comment by stgraber** [comment]
So the feature is mostly meant for images import and export as tarballs, but since we support making images of an existing container, the client can certainly be made to get you a tarball for an existing container.

**Comment by stgraber** [comment]
Specification work done, hallyn is working on import now, assigning to him.

**Comment by vtolstov** [comment]
So it implemented now or not?

**Comment by stgraber** [comment]
Import was implemented, yes.

**Comment by vtolstov** [comment]
what about export ?

**Comment by hallyn** [comment]
On Tue, Feb 24, 2015 at 08:28:03AM -0800, Vasiliy Tolstov wrote:
> what about export ?

That is targeted for 0.3
