### ISSUE TITLE
Example authenticated/unauthenticated HTTP(s) REST API usage.

### ISSUE THREAD

**Issue by monokal** [lxc/lxd#1858]
It's somewhat a struggle (speaking for myself of-course) to understand how to use LXD's HTTP(s) REST API using anything other than the actual LXD client. For example, how about a basic example using cURL with and without authentication.

In my specific case, I'm running an LXD server in a local Vagrant box (Ubuntu Snappy) with LXD's port 8443 exposed to the local host.

Now, I can hit `https://127.0.0.1:8443/1.0` and get the response...

`{"type":"sync","status":"Success","status_code":200,"metadata":{"api_extensions":[],"api_status":"development","api_version":"1.0","auth":"untrusted","public":false}}`

...but how about deploying a new container for example.

Can we disable authentication completely while using TCP, for local development? If not, could we please have a "real world" usage example please! If you let me know I'd be more than happy to drop a documentation PR for others.

Kind Regards,
Daniel.

**Comment by stgraber** [comment]
No, you can't turn off authentication on the https socket, you can however use the unix socket instead (/var/lib/lxd/unix.socket) given sufficiently recent curl (--unix-socket option).

As for authentication, as documented, it uses a SSL client certificate, so you need to have this be trusted by LXD then, for curl, pass it with the --key and --cert arguments.

For example, do:
    lxc config trust add ~/.config/lxc/client.crt
    curl -k -s --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key https://127.0.0.1:8443

**Comment by monokal** [comment]
Brilliant @stgraber, thanks for the speedy response!
