### ISSUE TITLE
lxd in Debian Testing - missing CGroup memory and pids controller

### ISSUE THREAD

**Issue by pipatron** [lxc/lxd#1861]
I wanted to try lxd on my Debian Testing server, but after building it and starting `lxd` I get the following output:
>WARN[04-06|20:24:39] AppArmor support has been disabled because of lack of kernel support 
WARN[04-06|20:24:39] Couldn't find the CGroup memory controller, memory limits will be ignored. 
WARN[04-06|20:24:39] CGroup memory swap accounting is disabled, swap limits will be ignored. 

I suppose I don't care or know much about the AppArmor part, but the memory part would be nice to take care of. Problem is, I don't know how or why it is missing.

I read the very similar report #1554 but I don't think the solution applies to me because I _have_ most of the `cgroup` mounts already mounted by `systemd`:

>cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,clone_children)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event)

Curiously, nothing about memory there. When I look at the `dmesg` output I find this:

>...
[    0.019272] Initializing cgroup subsys io
[    0.019279] Initializing cgroup subsys memory
[    0.019399] *Disabling memory control group subsystem*
[    0.019401] Initializing cgroup subsys devices
[    0.019405] Initializing cgroup subsys freezer
...

I'm trying this in a recent-as-of-today Debian Testing machine using a `4.4.0-1-amd64` kernel, systemd 229, lxd 2.0.0.rc8.

Just tell me if you need any other information. Presumably there is something I have to tell systemd to stop disabling the memory control.

**Comment by stgraber** [comment]
Debian requires a custom boot parameter to have the memory cgroup enabled.

**Comment by stgraber** [comment]
cgroup_enable=memory must be on your kernel command line apparently.

If you also want swap accounting, you'll need to also add: swapaccount=1

**Comment by stgraber** [comment]
Note that this is purely a Linux distribution problem, distributions have different kernel configurations, some disabling things entirely, some requiring a boot flag. LXD detects what you actually have at run time, turning things on is something that you need to do yourself or convince your distribution to do it for you.

**Comment by pipatron** [comment]
Thank you for the quick response! I will have to read more about the implications of enabling it and why Debian leaves it out by default.

**Comment by Laguna-x** [comment]
what about pids controller? can't find info about it
