### ISSUE TITLE
LXD upgrade dialog.

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1864]
"Empty values are not allowed                                       
The question you just answered requires you to provide a value.    
An example value is usually provided in the question description. "

LXD 2.0.0~rc8-0ubuntu5

On upgrade the above dialog message appears continuously. No cancel or skip button, just OK which drives back to the same dialog.

The problem is probably with this:

```
$ cat /etc/default/lxd-bridge|grep -v ^$|grep -v ^#
USE_LXD_BRIDGE="true"
LXD_BRIDGE="lxdbr0"
LXD_CONFILE=""
LXD_DOMAIN="lxd"
LXD_IPV4_ADDR="10.219.0.1"
LXD_IPV4_NETMASK="255.255.255.0"
LXD_IPV4_NETWORK="10.219.0.1/24"
LXD_IPV4_DHCP_RANGE="10.219.0.100,10.219.0.199"
LXD_IPV4_DHCP_MAX=""
LXD_IPV4_NAT="true"
LXD_IPV6_ADDR=""
LXD_IPV6_MASK=""
LXD_IPV6_NETWORK=""
LXD_IPV6_NAT="false"
LXD_IPV6_PROXY="false"
```

BTW, *_NETWORK is totally useless, isn't it?

**Comment by stgraber** [comment]
Hmm, yeah, there's clearly a logic problem I'll fix for the upgrade.

Your config is invalid though, LXD_IPV4_DHCP_MAX is a required option, that's what's causing the loop.

Set that to 99 (or smaller if you want) and it should all work again.
