### ISSUE TITLE
"No such object" error using LXD REST API via cURL

### ISSUE THREAD

**Issue by monokal** [lxc/lxd#1865]
Using the LXD REST API via cURL I see the following error: 
`{"error":"No such object","error_code":500,"type":"error"}`

Here's the cURL command I'm using:
```
curl -k \
     --cert lxd/client.crt \
     --key lxd/client.key \
     -H "Content-Type: application/json" \
     -X POST \
     --data "@ubuntu.json" \
     https://127.0.0.1:8443/1.0/containers
```

And here's the JSON (validated using JSON Lint):
```
{
    "name":"my-new-container",
    "architecture":"x86_64",
    "profiles":[
        "default"
    ],
    "ephemeral":true,
    "config":{
        "limits.cpu":"2"
    },
    "source":{
        "type":"image",
        "alias":"ubuntu/devel"
    }
}
```

Anything you see I'm doing wrong please?

**Comment by pcdummy** [comment]
Did you try to create a container with the lxc command and the same parameters?

**Comment by monokal** [comment]
I'm able to create the container via the `lxc` command-line client. I noticed that setting "type":"image", to "type":"none" in my JSON allows the call to return success which would suggest it's not a syntax error.

**Comment by pcdummy** [comment]
You created the container with the image "ubuntu/devel" ?

**Comment by monokal** [comment]
I switched to `ubuntu:14.04` and re-tested using both `cURL` and the `lxc` client. `lxc` works fine where as `cURL` still throws the same `No such object` error.

**Comment by stgraber** [comment]
That's because "ubuntu:14.04" actually means from an API point of view:

```
    "source":{
        "type":"image",
        "mode":"pull",
        "protocol":"simplestreams",
        "server":"https://cloud-images.ubuntu.com/releases",
        "alias":"14.04"
    }
```

**Comment by monokal** [comment]
@stgraber, sorry, but I still don't quite understand the issue. `https://cloud-images.ubuntu.com/releases` shows the releases for 14.04 but obviously I'm missing something. I've tried "`alias":"ubuntu/14.04/14.04`" too as I see the image is in a 2nd level directory by the same name on the image server but still get `No such object`.

I'd be happy to open a documentation PR to clarify this usage if you let me know what's going on. Thanks in advance.

**Comment by stgraber** [comment]
DId you try using the source dict I listed above?

**Comment by stgraber** [comment]
Just confirmed that the following (as I suggested above) works perfectly fine:
```
{
    "name":"my-new-container",
    "architecture":"x86_64",
    "profiles":[
        "default"
    ],
    "ephemeral":true,
    "config":{
        "limits.cpu":"2"
    },
    "source": {
        "type":"image",
        "mode":"pull",
        "protocol":"simplestreams",
        "server":"https://cloud-images.ubuntu.com/releases",
        "alias":"14.04"
    }
}
```

**Comment by monokal** [comment]
Sorry, I misunderstood your previous reply. By "from an API point of view" I thought you meant the internals translated "Ubuntu:14.04" in to the source dict.

Thanks for clearing it up, I'll document the usage appropriatey and open a PR to prevent such confusion in future.

**Comment by stgraber** [comment]
Right, remotes aren't a thing as far as the API and daemon is concerned, it's just a convenience implemented in the Go client tool, nova-lxd for example (another client) doesn't need such a thing at all.

**Comment by monokal** [comment]
Understood pal. Thanks again for clarifying. The API documentation was just a little lacking, which is understandable given its still experimental.
