### ISSUE TITLE
GET /1.0/containers/<name>/files?path=<path> always returns a UID and GID of 0

### ISSUE THREAD

**Issue by jeffshantz** [lxc/lxd#1869]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04.4
   * Kernel version: 3.13.0-71-generic
   * LXC version: 2.0.0.rc8
   * LXD version: 2.0.0.rc8
   * Storage backend in use: btrfs

# Issue description

When pushing files with `POST /1.0/containers/<name>/files?path=...`, one can specify the headers `X-LXD-uid` and `X-LXD-gid` to set the owner and group of an uploaded file.  This works properly.

However, when pulling a file, the UID and GID returned in the `X-LXD-uid` and `X-LXD-gid` headers always appears to be `0`.

# Steps to reproduce

 1. Upload a file to container and set its UID and GID

```
curl -k \
     --cert ~/.config/lxc/client.crt \
     --key ~/.config/lxc/client.key \
     -X POST \
     --data-binary @test.txt \
     -H 'Content-type: application/octet-stream' \
     -H 'X-LXD-uid: 1000' \
     -H 'X-LXD-gid: 1000' \
     https://localhost:8443/1.0/containers/test/files?path=/tmp/test.txt

{"type":"sync","status":"Success","status_code":200,"metadata":{}}
```

2. Verify the UID and GID are correct in the container:

```
# ls -la /tmp
total 4
drwxrwxrwt    1 root     root            32 Apr  7 21:27 .
drwxr-xr-x    1 root     root           154 Apr  6 16:43 ..
-rw-r--r--    1 cirros   cirros           8 Apr  7 21:27 test.txt

~ # grep cirros /etc/passwd
cirros:x:1000:1000:non-root user:/home/cirros:/bin/sh

~ # grep cirros /etc/group
cirros:x:1000:
```

3. Retrieve the file and observe that the UID and GID are returned as `0`:

```
curl -i -k \
     --cert ~/.config/lxc/client.crt \
     --key ~/.config/lxc/client.key \
     -H 'Content-type: application/json' \
     https://localhost:8443/1.0/containers/test/files?path=/tmp/test.txt

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Disposition: inline;filename=test.txt
Content-Length: 8
Content-Type: application/octet-stream
Last-Modified: Thu, 07 Apr 2016 20:29:28 GMT
X-Lxd-Gid: 0
X-Lxd-Mode: 0600
X-Lxd-Uid: 0
Date: Thu, 07 Apr 2016 20:29:28 GMT

testing
```

**Comment by stgraber** [comment]
Taking care of this now, the code is indeed quite broken...

**Comment by stgraber** [comment]
Was slightly harder than expected, but got it working ^

**Comment by stgraber** [comment]
< X-Lxd-Gid: 456
< X-Lxd-Mode: 0642
< X-Lxd-Uid: 123

**Comment by jeffshantz** [comment]
Thank you!  My tests are now passing. :)
