### ISSUE TITLE
unix.socket wrong group and permissions when installing lxd

### ISSUE THREAD

**Issue by wallyworld** [lxc/lxd#1882]
Installing lxd on a xenial machine results in the unix.socket file having ownership of root.root with perms of 600. I had to change the group to lxd and a g+rw for things to work. I'm guessing we'd want to ensure the unit.socket file is correctly set up out of the box.

lxd:                                                                                                                                                                                                  
  Installed: 2.0.0~rc9-0ubuntu4                                                                                                                                                                       
  Candidate: 2.0.0~rc9-0ubuntu4                                                                                                                                                                       
  Version table:                                                                                                                                                                                      
 *** 2.0.0~rc9-0ubuntu4 500                                                                                                                                                                           
        500 http://au.archive.ubuntu.com/ubuntu xenial/main amd64 Packages                                                                                                                            
        100 /var/lib/dpkg/status 

Linux host 4.4.0-6-generic #21-Ubuntu SMP Tue Feb 16 20:32:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stgraber** [comment]
Not a LXD bug. We've seen this a few times and current suspect is systemd as LXD itself isn't creating that socket (and when it is creating the socket itself, our code does it correctly).

**Comment by stgraber** [comment]
Feel free to file a bug against systemd on Launchpad. Our socket activation unit quite clearly requires the socket to be 640 and owned by root:lxd. The lxd user and group is created in the preinst of our package so prior to systemd picking up the unit so if the owner is incorrect, this very much is a systemd issue.

**Comment by stgraber** [comment]
Oh and if you can reproduce this somewhat consistently, it'd be great! So far we've only had two reports of this and in both cases, the issue never happened again for the reporter...
