### ISSUE TITLE
Unable to install 2.0.0~rc9 from trusty-backports

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#1883]
I just created a fresh AWS machine with a Trusty image (juju bootstrap), I then went on to it and manually ran "sudo apt-get -t trusty-backports install lxd" to test, and I found
Setting up lxd (2.0.0~rc9-0ubuntu5~ubuntu14.04.1) ...
start: Job failed to start
invoke-rc.d: initscript lxd, action "start" failed.
dpkg: error processing package lxd (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 lxd
E: Sub-process /usr/bin/dpkg returned an error code (1)
ubuntu@ip-10-84-15-119:~$ sudo dpkg-reconfigure lxd
/usr/sbin/dpkg-reconfigure: lxd is broken or not fully installed
ubuntu@ip-10-84-15-119:~$ sudo apt-get -t trusty-backports install lxd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
lxd is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up lxd (2.0.0~rc9-0ubuntu5~ubuntu14.04.1) ...
start: Job failed to start
invoke-rc.d: initscript lxd, action "start" failed.
dpkg: error processing package lxd (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 lxd
E: Sub-process /usr/bin/dpkg returned an error code (1)

Note that the machine was created with the official juju-2.0.0beta3 which was built with golang 1.2, so it doesn't have LXD support, I was just checking that the package should be available (it seems something is broken on MaaS images), but it also seems that something is wrong with the packaging for 2.0.0~rc9 on Trusty.

"/var/log/dpkg.log" just says "status half-configured lxd:amd64 ..."
/var/log/lxd is empty
Is there another log file I can give you guys to help track this down?

**Comment by stgraber** [comment]
Fixed.

As a workaround until the new package hits (probably an hour or so), just "apt-get -t trusty-backports install lxc".
