### ISSUE TITLE
config is sometimes not populated on launch

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#1885]
I have seen cases where a container doesn't have stuff like the base_image and root disks on launch. It doesn't reproduce every time, though.

If I subsequently edit the configuration, my edits are not remembered or applied, like somehow something is invalid in the database. However, `lxc config edit` doesn't error out or anything.

**Comment by tych0** [comment]
They also don't have the default profile applied, or an ephemeral entry when doing a "lxc config edit"

**Comment by stgraber** [comment]
Having a reproducer for this would certainly be interesting :)

**Comment by stgraber** [comment]
A probably a ".dump" of the lxd database as this very much sounds like a broken/corrupted DB to me.

**Comment by tych0** [comment]
On Mon, Apr 11, 2016 at 02:59:47PM -0700, Stéphane Graber wrote:
> A probably a ".dump" of the lxd database as this very much sounds like a broken/corrupted DB to me.

Ok, next time I see it I'll get one. I didn't realize what was
happening at first so I just deleted the container and started over.
I've seen it twice today, though.

**Comment by stgraber** [comment]
Have you ever see this happen again?

**Comment by tych0** [comment]
No :)
