### ISSUE TITLE
User human readable dates in log files

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1887]
Currently:

```
lxc 20160412143206.433 INFO     lxc_cgfsng - cgfsng.c:do_secondstage_mounts_if_needed:1292 - Remounted /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/blkio read-only
```

Something like this would be friendlier and more useful:
2016-04-12 14:32:06.43 '.433' there?

Does one really want to know the '.433' seconds there?

**Comment by stgraber** [comment]
Not a LXD bug, those timestamps come from LXC. And yeah, I'm not against some formatting there.

Feel free to file this at github.com/lxc/lxc if it's not been reported yet.
