### ISSUE TITLE
ZFS dataset not mounted or gets umounted on first start

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1888]
ii  lxd                                                   2.0.0~rc8-0ubuntu2~ubuntu14.04. amd64                           Container hypervisor based on LXC - daemon

$ lxc launch ..
$ lxc stop ..
$ lxc start

BUT I could have not directly reproduce it yet.
Maybe it's related to package upgrade, I'm not sure.

**Comment by stgraber** [comment]
We'd need a reproducer and some logs to be able to investigate...

**Comment by tomposmiko** [comment]
I'm working on it:)
I posted, because others could face the issue as well and help in reporting.

**Comment by stgraber** [comment]
Have you ever found a reproducer for this?

**Comment by stgraber** [comment]
Just wrote some code to mount the zfs filesystem if it's not mounted, will fix this if it ever happens again.

**Comment by shark0der** [comment]
Maybe related: http://askubuntu.com/questions/774097/lxd-managed-containers-on-zfs-vanish-after-deleting-a-different-one

**Comment by stgraber** [comment]
Yeah, seems to be the same issue. The next bugfix release should paper over that problem with the code I wrote. Still suspect the release problem is some zfs bug.

**Comment by tomposmiko** [comment]
Ooops, this issue skipped my mind completely.
Sorry about that, thanks @stgraber for your patient:)

BTW, why is it ever gets unmounted? Do I understand correctly, this is a workaround and the root cause has not been fixed yet?

**Comment by stgraber** [comment]
We have no code to cause an unmount, so my best guess is that it's a zfs bug somewhere. So yeah, this absolutely is a workaround, but that should do the trick.
