### ISSUE TITLE
Speed up zfs send/recv

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1890]
Currently ```lxc copy``` is terribly slow.

mbuffer can speed up send/recv a lot.

Copying from a script:

```
c_mbuffer_send="mbuffer -q -v 0 -s 128k -m 1G"
c_mbuffer_recv="mbuffer -s 128k -m 1G"

zfs send [...] | $c_mbuffer_send" | $c_mbuffer_recv | zfs recv [...]
```

**Comment by stgraber** [comment]
It's probably a bit more difficult than this given that we then have to use the websocket framing to transport things over the remote server, but a similar trick should be possible in the Go code I'd expect.

**Comment by tych0** [comment]
On Wed, Apr 13, 2016 at 01:01:49AM -0700, Tamas Papp wrote:
> Currently ```lxc copy``` is terribly slow.
> 
> mbuffer can speed up send/recv a lot.
> 
> Copying from a script:
> 
> ```
> c_mbuffer_send="mbuffer -q -v 0 -s 128k -m 1G"
> c_mbuffer_recv="mbuffer -s 128k -m 1G"
> 
> zfs send [...] | $c_mbuffer_send" | $c_mbuffer_recv | zfs recv [...]
> ```

We could probably do this in LXD itself (i.e. buffer zfs output
instead of just copying it directly to websockets in the chunks it
comes in), I'll have a look.

**Comment by tych0** [comment]
So I started fiddling with this today, and came up with this:

https://github.com/tych0/lxd/commit/5625a67cc956250574ba24492b6a66523361a398

Unfortunately it seems like zfs doesn't like whatever is happening, so it seems something might be broken at the websocket framing level.

**Comment by tych0** [comment]
An update on this: I profiled what happens on the sender and receiver CPU side, and it looks like basically all of the CPU time is spent in golang's crypto libraries encrypting and decrypting the websocket frames. I don't think there's really anything more we can do about that (golang is apparently smart enough to take advantage of hardware coprocessors when they're present) besides potentially adding some sort of "insecure transfer" mode.

In any case, we are doing smarter buffering now which was the focus of this issue, so I'm going to close it. Thanks!
