### ISSUE TITLE
Show progress data during container migration

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1891]
A progress bar would be nice for lxc copy and similar actions.

Like with pv or (clp)bar.

**Comment by stgraber** [comment]
The difficulty here is that we have no idea how large the transfer will be, so we could tell you how fast it's going but not how far it's at.

**Comment by tomposmiko** [comment]
It's extremely better than nothing.

Why can't you tell the size? If it's any kind of volume (btrfs, zfs, lvm) the size info is available, isn't it?

**Comment by stgraber** [comment]
The size of the LVM partition doesn't equate the size of the compressed rsync stream, same goes for the others.

We also have logic to pre-unpack the source image on the target to limit the delta and look for existing parent snapshots to limit the delta of zfs or btrfs, so a 15G container may very well just require a few MB of bandwidth.

**Comment by tomposmiko** [comment]
I see, cool.
In that case a speed counter or something would be just useful. Something that indicates, it is really working, not stuck etc.

**Comment by stgraber** [comment]
Someone willing to work on this should look at the progress code used for image transfers. Rather than a percentage value, we'd like to send a download speed in the case of container migration, possibly alongside how much data was transferred, so updating the operation to include as its progress data "234MB transferred (15MB/s)" or something along those lines.

**Comment by cryptofuture** [comment]
+1. It will be very useful for lxc copy with remote containers.   
And is there any way to tell lxc copy state beside watching rsync process running?

**Comment by cryptofuture** [comment]
I can't wait to test it. Best news ever!

**Comment by tomposmiko** [comment]
@stgraber Thanks so much!

**Comment by stgraber** [comment]
Note that the change we landed is just the backend side, so you'll see progress information if you use "lxc monitor" but won't see progress in the client quite yet.

That's because I'm working on a re-design of the client library (#1926) which will then be used to surface that information.

**Comment by voxsoftware** [comment]
Why not use zfs send and zfs recv for zfs storage pools? In that way progress can be shown and copy is efficient.

**Comment by tomponline** [comment]
We do when appropriate.
