### ISSUE TITLE
New feature: lxd-bridge manage several bridges

### ISSUE THREAD

**Issue by crashtua** [lxc/lxd#1893]
Hello everyone. It will be great to make lxd-bridge scripts manage list of bridges to create groups of containers bind to specified bridge using profiles.
But I am not sure that this feature are in scope of lxd, because I see several similar bugs(like "lxd network configuration too complicated" etc).

**Comment by stgraber** [comment]
It's not in scope right now but we may reconsider having LXD itself do network management at some point, if that happens, then we'd certainly allow for more than one bridge to be defined.

As it stands right now, lxd-bridge is basically just a helper for Linux distributions to use. They could absolutely pass it multiple configuration files to spawn more than one bridge if they wanted, Ubuntu however does not.

I'm closing this as it's indeed out of scope for now, but putting this in scope is something we're currently considering.

**Comment by crashtua** [comment]
Thanks a lot for reply.
