### ISSUE TITLE
mesg: ttyname failed: Success

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1896]
guest:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Xenial Xerus (development branch)
Release:	16.04
Codename:	xenial
```
host:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

```
root@zebra:~# lxc exec ldap bash
root@ldap:~# sudo -i
mesg: ttyname failed: Success
root@ldap:~# 
```

Is this actually a bug?

**Comment by stgraber** [comment]
Looks like the same issue as #1724 

Basically the GNU C library returns an empty string on ttyname() if it can't deref /proc/self/fd/0. It however still returns true when asked if that same path is a tty causing some confusion :)

Closing as duplicate.
