### ISSUE TITLE
Pushing Container to Remote Host

### ISSUE THREAD

**Issue by timtierney** [lxc/lxd#1898]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:
   * Container Source Host:  Ubuntu 14.04 (x64)
   * Container Destination Host:  Ubuntu 15.10 (i386)
 * LXC version:
   * Container Source Host:  2.0.0
   * Container Destination Host:  2.0.0
 * LXD version:
   * Container Source Host:  2.0.0
   * Container Destination Host:  2.0.0
   * Storage backend in use:  File Directory Type (Both Hosts)

# Issue description

My use-case is to configure a new web server type container on a laptop.  Now I'm finished and I'm ready to copy the container to a production server.  I can access the remote server with `lxc list` so I know that I've got LXD remote access setup correctly.  However, when I run the `lxc copy` command, I get the message:

`error: The source remote isn't available over the network`

# Steps to reproduce
Note:  server1 is the remote destination I'm trying to copy the container to.  newweb is the container I'm trying to copy to server1.
`lxc stop newweb`
`lxc list` - Works (locally)
`lxc list server1:` - Works
`lxc copy newweb server1:web1` fails with the error message above.

I've also tried:  `lxc copy local:newweb server1:web1`.  The result is the same.

# Information to attach
- [CommandOutput.txt](https://github.com/lxc/lxd/files/220099/CommandOutput.txt)

**Comment by stgraber** [comment]
The error message seems pretty clear :)
Your local LXD isn't accessible from the network so there is no way for the target LXD to copy the container from its source.

I covered this particular issue in a recent blog post here: https://www.stgraber.org/2016/04/12/lxd-2-0-remote-hosts-and-container-migration-612/

**Comment by timtierney** [comment]
*sigh*, I didn't see your new blog entry (I've been following) .  Clearly, I'm a little slow.  :)  It seems to be copying now.  Sorry for the false alarm.

**Comment by stgraber** [comment]
Cool, good to hear that you didn't have any nasty firewall or NAT in the way :)

**Comment by aarnaud** [comment]
Hi @stgraber 

is it possible to add push option with image copy in order to works behing a NAT?

Thanks

**Comment by stgraber** [comment]
Yeah, that'll be dealt with as part of #553
