### ISSUE TITLE
lxc copy x:c1 y:c1 makes many assumptions about network topology, firewalls etc.

### ISSUE THREAD

**Issue by tim-seoss** [lxc/lxd#1899]
With lxd 2.0.0-0ubuntu3~ubuntu15.1

This works fine:

nated-machine# lxc exec remotemachine:c57 bash

... however it doesn't appear possible to copy a container from a machine behind a firewall and/or nat and a machine elsewhere:

nated-machine# lxc copy c1 remotemachine:c2

... since the remote machine expects to be able to contact the IP address of the local machine to 'pull' the container over.

It's also not possible to copy containers over ssh at all (I assume this was a design decision, but it is a total pain for system administration - ssh is the universal transport for most sysadmins, and having to fart around with firewalls to open up specific TCP ports is cumbersome and arguably less secure too).

**Comment by aarnaud** [comment]
Linked #1898

**Comment by stgraber** [comment]
That's going to be dealt with #553 which will have us implement push mode too, we'll then be able to:
 - Have the target pull from the source
 - Or have the source push to the target
 - Or have the client pull from the source and push to the target

Closing as duplicate
