### ISSUE TITLE
No way to delete stuck containers. Don't know why they got stuck initially.

### ISSUE THREAD

**Issue by bsod90** [lxc/lxd#1902]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.4.0-15-generic
   * LXC version: 2.0.0
   * LXD version: 2.0.0
   * Storage backend in use: zfs

# Issue description

Containers are stuck after a while. No way to delete stuck containers.
http://d.pr/i/1j8mn

# Information to attach

 - [x] any relevant kernel output (dmesg) [bug_dmesg.txt](https://github.com/lxc/lxd/files/222877/bug_dmesg.txt)
 - [ ] container log (lxc info NAME --show-log) - stuck
 - [x] main daemon log (/var/log/lxd.log) [lxd.log.txt](https://github.com/lxc/lxd/files/222865/lxd.log.txt)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug
 - [x] ps fauxww [bug_ps.txt](https://github.com/lxc/lxd/files/222879/bug_ps.txt)

**Comment by stgraber** [comment]
a "dmesg" and "ps fauxww" output would probably be useful.

**Comment by bsod90** [comment]
@stgraber attached the logs to the main message

**Comment by stgraber** [comment]
You appear to have multiple concurrent copy of the lxd daemon running on your system, that may well be causing your problems.

Try killing 482075 and 482079, see if things get unstuck somehow.

**Comment by bsod90** [comment]
Hmm. Killing those extra LXDs helped. Now I'm able to delete my stuck container.
But I'm now wondering how they got started. I remember rebooting the machine quite recently and I definitely did not start another lxd manually. 
The only way how might've been started is when I tried running 'service lxd restart'. But by that time containers were already stuck.

Anyways, thank you!

**Comment by stgraber** [comment]
Yeah, I think we had such a behavior with a bug in one of the late rcs, but 2.0 final was supposed to be fixed, so not sure what's causing that.

**Comment by stgraber** [comment]
If you have any way to reproduce the leftover lxd daemon that'd be very useful as short of having that, there's little we can do :(

**Comment by bsod90** [comment]
It's never happened again during this week. So, let's consider this a random bug and close the issue.
Thank you!
