### ISSUE TITLE
Log file is not readable

### ISSUE THREAD

**Issue by zulcss** [lxc/lxd#1904]
When turning on verbose and debug and capturing the log in a log file. Some of it its unreadable.

0/containers/instance-00000059\",\n\t\t\t\"/1.0/containers/instance-0000005c\",\n\t\t\t\"/1.0/containers/instance-0000005f\",\n\t\t\t\"/1.0/containers/instance-00000062\",\n\t\t\t\"/1.0/containers/instance-00000065\",\n\t\t\t\"/1.0/containers/instance-00000066\",\n\t\t\t\"/1.0/containers/instance-00000069\",\n\t\t\t\"/1.0/containers/instance-0000006c\",\n\t\t\t\"/1.0/containers/instance-0000006f\",\n\t\t\t\"/1.0/containers/instance-00000072\",\n\t\t\t\"/1.0/containers/instance-00000074\",\n\t\t\t\"/1.0/containers/instance-00000076\",\n\t\t\t\"/1.0/containers/instance-00000079\"\n\t\t]\n\t}"

**Comment by stgraber** [comment]
What did you run exactly?

**Comment by stgraber** [comment]
We have a --logfile option which is supposed to write a logger friendly log file as opposed to what's going to stdout which is meant for a terminal
