### ISSUE TITLE
Profile replication between multiple LXD hosts

### ISSUE THREAD

**Issue by hex2a** [lxc/lxd#1906]
currently all profile related configuration is stored in lxd.db, where it can't be easily replicated between servers.

A file based approach would be supported by (most) configuration management tools. (eg: puppet,ansible,..)

**Comment by stgraber** [comment]
yeah, having a copy function added to lxc profile should be easy to do.

**Comment by stgraber** [comment]
To clarify, I'm not suggesting we support API-level copy but just that the client tool get a "lxc profile copy" option which reads the profile on the source and create an identical profile on the target.

**Comment by sts** [comment]
I'd rather like to suggest an approach which would allow you to store configuration data under version control in a configuration management system.

Is it possible to use pylxd in the meantime (found most of the files in LXD are in a 'deprecated' folder)?  

We thought about having a script reading all profiles (JSON files) from a directory, each file representing a profile and comparing them against the local LXD API.

* In case the profile doesn't exist it will simply create it.
* In case the profile exists, the compares a version field (currently the description can be abused for this) and update if appropriate.
* Maybe even delete any profiles which don't exist in the directory but on LXD?

Is there anything one needs to watch out for when updating profiles? Eg. do only some of configuration values apply in realtime?

**Comment by stgraber** [comment]
We don't expect to move any of that stuff away from the database, so having the client support syncing profiles is your best bet. You can obviously script things with "lxc profile show abc" and "cat dump.yml | lxc profile edit abc" if you'd prefer.

pylxd would probably be fine too but as you've noticed they've been rewriting a good chunk of it, @rockstar may now.

**Comment by stgraber** [comment]
Apparently I completely missed the fact that we actually do have one already :)

    lxc profile copy <profile> <remote>            Copy the profile to the specified remote.

**Comment by sts** [comment]
The issues here are:
 - how do you manage that one/all LXD hosts, knows about all the others?  
 - how do you know that all LXD hosts, store the latest version of a profile?
 - how do you provision a new LXD host?

We created our own script, which pushes profiles from YAML or Json files, which are found in ```/etc/lxd/profiles```, via the REST API to LXD, so we are able to manage profile changes via Puppet.

The script basically compares a version string, which is currently stored in the description field and overwrites any older versions found. The normal LXD API was totally sufficient to implement this.

**Comment by CalebEverett** [comment]
How about `lxc profile apply <remote>:<container> <remote>:<container>` so you could keep all your profiles in one place?

**Comment by ge-fa** [comment]
@sts Could you share the code you're using?
