### ISSUE TITLE
error in using lxd rest api

### ISSUE THREAD

**Issue by DilipRenkila** [lxc/lxd#1907]
$ sudo lxc info
apicompat: 0
auth: trusted
environment:
  addresses:
  - 194.47.151.93:8443
  - 192.168.122.1:8443
  - 10.0.3.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
##certificate
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-15-generic
  server: lxd
  serverpid: 19741
  serverversion: 2.0.0
  storage: zfs
  storageversion: "5"
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  storage.zfs_pool_name: lxd
public: false

I am getting non-readable output while curling

$  curl -i -H "Accept: application/json" -H "Content-Type: application/json" --key ~/.config/lxc/client.key --cert ~/.config/lxc/client.crt -X GET http://194.47.151.93:8443/



**Comment by stgraber** [comment]
You are trying to do plain text HTTP over an HTTPs socket, that's not going to work :)

Use https://194.47.151.93:8443 and things should work much better.

**Comment by DilipRenkila** [comment]
I got it. Thank you
