### ISSUE TITLE
Messed up http_proxy env var set

### ISSUE THREAD

**Issue by robsanderson** [lxc/lxd#1909]
# Required information

* Distribution: Ubuntu
* Distribution version: 16.04
* The output of "lxc info" or if that fails:

```
$ lxc info
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
...
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-15-generic
  server: lxd
  serverpid: 8176
  serverversion: 2.0.0
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd
public: false
```

* Kernel version: 4.4.0-15-generic

* LXC version: 2.0.0~rc12-0ubuntu1
* LXD version: 2.0.0-0ubuntu4

# Issue description
Containers are unable to connect to http endpoints due to a bad http_proxy environment variable.

# Steps to reproduce

```
$ lxc launch images:ubuntu/xenial/amd64 t1
$ lxc exec t1 -- bash
root@t1:~# apt-get update
0% [Connecting to fe80::1%eth0 (fe80::1%eth0)] [Connecting to fe80::1%eth0 (fe80::1%eth0)]
root@t1:~# echo $http_proxy
http://[fe80::1%eth0]:13128
```

**Comment by stgraber** [comment]
Did you configure LXD with "lxd init" or "dpkg-reconfigure -p medium lxd"?

Doing so and answering the questions should unset the proxy variable for you once it's no longer needed.

if you did something else manually, then: "lxc profile unset core.proxy_http" will do it.

**Comment by robsanderson** [comment]
Hi,

I used `lxd init --auto` but did not set http_proxy so something must auto set it?

**Comment by stgraber** [comment]
It's set for you by default until an IPv4 subnet is configured as it's the only way containers can reach the internet until then.

**Comment by robsanderson** [comment]
If I do

```
lxc config show
config:
  storage.zfs_pool_name: lxd
```

I don't see that core.http_proxy is set and the value that is set is definitely wrong.

```
root@t1:~# echo $http_proxy
http://[fe80::1%eth0]:13128
```

the container has an ipv4 interfaces but still retain the incorrect http_proxy environment variable.

Obviously I can easily unset it inside the container but thought this looked like a bug.

**Comment by stgraber** [comment]
lxc profile show default

**Comment by robsanderson** [comment]
```
$ lxc profile show default
name: default
config:
  environment.http_proxy: http://[fe80::1%eth0]:13128
  user.network_mode: link-local
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
```

**Comment by stgraber** [comment]
yep, there it is ^

lxc profile unset default environment.http_proxy
lxc profile unset default user.network_mode

That should fix it for you.
