### ISSUE TITLE
lxc list without 'head'

### ISSUE THREAD

**Issue by aguytech** [lxc/lxd#1912]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04

### Is there a way to have a list of container without head ?
For example just a list of result separate with space, like "lxc list --format list"
I look around lxc list --help && man lxc and don't see anything about this. it's particularly efficient to manipulate few containers within a loop after selecting the right containers.
The system of selecting with filtering is very appreciate ;o)

**Comment by stgraber** [comment]
stgraber@castiana:~$ lxc list --format=json | jq '.[] .name'
"downloader"
"nesting"
"streamer"
"streamer1"

Requires jq to extract exactly the information you want. We may add more formats but right now, the json output if by far the most flexible.
