### ISSUE TITLE
Validate that the imported image is valid (has a parsable metadata.yaml and has a rootfs/ directory)

### ISSUE THREAD

**Issue by DilipRenkila** [lxc/lxd#1913]
`$ lxc info`
`apicompat: 0`
`auth: trusted`
`environment:`
 ` addresses:`
  `- 192.168.1.6:8443`
  `- 192.168.122.1:8443`
  `- 10.0.3.1:8443`
  `architectures:`
  `- x86_64`
  `- i686`
  `certificate: |`
   ` -----BEGIN CERTIFICATE----`  
    `-----END CERTIFICATE-----`
  `driver: lxc`
  `driverversion: 2.0.0`
  `kernel: Linux`
  `kernelarchitecture: x86_64`
  `kernelversion: 4.4.0-18-generic`
  `server: lxd`
  `serverpid: 2967`
  `serverversion: 2.0.0`
  `storage: zfs`
  `storageversion: "5"`
`config:`
 ` core.https_address: '[::]:8443'`
  `core.https_allowed_headers: Content-Type`
  `core.https_allowed_methods: GET, POST, PUT, DELETE, OPTIONS`
  `core.https_allowed_origin: '*'`
  `core.trust_password: true`
  `storage.zfs_pool_name: lxd`
`public: false`
`$ lxc image list`
+--------+--------------+--------+------------------------------------+--------+----------+------------------------------+
| ALIAS  | FINGERPRINT  | PUBLIC |            DESCRIPTION             |  ARCH  |   SIZE   |         UPLOAD DATE          |
+--------+--------------+--------+------------------------------------+--------+----------+------------------------------+
| xenial | 75e45fba5025 | no     | Ubuntu 16.04 LTS server (20160420) | x86_64 | 214.08MB | Apr 20, 2016 at 6:08pm (UTC) |
+--------+--------------+--------+------------------------------------+--------+----------+------------------------------+
`$ lxc launch xenial first`
`Creating first`
`error: lstat /var/lib/lxd/containers/first.zfs/rootfs: no such file or directory`

**Comment by stgraber** [comment]
Can you paste the output of:
 - sudo zfs list -t all
 - sudo ls -lh /var/lib/lxd/containers/

I can't recall ever seeing this error so that's certainly new :)

**Comment by DilipRenkila** [comment]
$ sudo zfs list -t all
```NAME                                                                                   USED  AVAIL  REFER  MOUNTPOINT
lxd                                                                                   6,07M  30,8G    19K  /lxd
lxd/containers                                                                         378K  30,8G    19K  /lxd/containers
lxd/containers/u1                                                                      360K  30,8G  5,50M  /var/lib/lxd/containers/u1.zfs
lxd/images                                                                            5,24M  30,8G    19K  /lxd/images
lxd/images/bad1225246cfd659bd0f421fde9ec6542a1bc0b9bd366a58025baad2baede3a5           5,22M  30,8G  5,22M  /var/lib/lxd/images/bad1225246cfd659bd0f421fde9ec6542a1bc0b9bd366a58025baad2baede3a5.zfs
lxd/images/bad1225246cfd659bd0f421fde9ec6542a1bc0b9bd366a58025baad2baede3a5@readonly      0      -  5,22M  -```
$ sudo ls -lh /var/lib/lxd/containers/
total 4,5K
```-rw-r--r-- 1 root   root   1,1K apr 20 21:54 lxc-monitord.log
lrwxrwxrwx 1 root   root     30 apr 20 21:33 u1 -> /var/lib/lxd/containers/u1.zfs
drwxr-xr-x 4 165536 165536    5 apr 20 21:24 u1.zfs```

**Comment by DilipRenkila** [comment]
I actually downloaded root.tar.gz image from ubuntu cloud archive and imported it to lxd.

**Comment by stgraber** [comment]
Ah, that's the problem then. You can't do that :)

LXD should probably be validating images a bit harder, but if importing a single tarball, that tarball must have the rootfs inside a "rootfs" directory and must have metadata.yaml file at the root.,

If importing from multiple tarballs, as you must for a cloud image, you need to pass the metadata tarball (lxd.tar.xz) as first argument and then the rootfs as the second argument.

But also, you could just do: lxc launch ubuntu-daily:xenial

Which will pull the cloud image for you :)

**Comment by DilipRenkila** [comment]
How can i pass metadata argument and rootfs argument can you give me an example as i haven't any options in lxc launch?

**Comment by DilipRenkila** [comment]
can you give me an example of how i can pass metadata to container?

**Comment by stgraber** [comment]
You do that when you import the image:

    lxc image import lxd.tar.xz rootfs.tar.gz --alias some-name
    lxc launch some-name my-container-name
