### ISSUE TITLE
Add configuration option to have LXD remove newer zfs snapshots on restore

### ISSUE THREAD

**Issue by SvenWiltink** [lxc/lxd#1919]
Right now it is not possible to revert a container to a snapshot that is not the latest one. Zfs does however support it using the -r argument: 
http://manpages.ubuntu.com/manpages/wily/man8/zfs.8.htm

This does discard any data of the snapshots made after it, so I would suggest adding a -f option to the lxc restore command instead of throwing an error.

The check that is causing this can be found here:
https://github.com/lxc/lxd/blob/349131c6386e29a7c727ec05ee1581f60ab275b4/lxd/storage_zfs.go#L181

A force option would be needed here as well: https://github.com/lxc/lxd/blob/349131c6386e29a7c727ec05ee1581f60ab275b4/lxd/storage_zfs.go#L928

**Comment by stgraber** [comment]
Yeah, I'm well aware of the -r option, however doing so would cause some LXD corruption as LXD would have the snapshot in its database but not on disk anymore. So we went the easy way which is to just not allow it at all and instead require the user to actually do it.

A -f flag in LXD would also be a bit awkward as it would only be meaningful for zfs and so doesn't really fit the scope of our API which is meant to be generic.

**Comment by SvenWiltink** [comment]
I agree on the -f option. We could however cleanup the snapshots removed by the -r option. It shouldn't be too hard to list that as well (eg: remove all the snapshots being rolled back if the rollback is successful)

**Comment by stgraber** [comment]
Yes, we could add a "storage.zfs_snapshot_erase" config option which would have LXD remove any needed snapshot in order to make restore work.

**Comment by SvenWiltink** [comment]
Yes, that is what meant :)
I'll see if I can come up with a MR

**Comment by SvenWiltink** [comment]
Thanks for fixing it this quickly. You guys are awesome!
