### ISSUE TITLE
Containers names do not allow the use of FQDN.

### ISSUE THREAD

**Issue by major0** [lxc/lxd#1921]
* Distribution: Ubuntu
* Distribution version: 14.04
* Kernel version:
* LXC version: 1.1.5
* LXD version: 2.0.0
* Storage backend in use: dir

# Issue description

Container names prohibited from using Fully Qualified Domain Names.  This looks to have been introduced by bbf6380acc937bf4df302b3da82088954e428107.

# Steps to reproduce

lxc init ubuntu: host.domain.com

# Output

Creating host.domain.com
error: Container name isn't a valid hostname.

**Comment by stgraber** [comment]
Yep, not a bug, this is very much intentional.

Container names are used to set the UTSNAME which in turn is used as the hostname, that hostname is then picked up as the leading part of the FQDN by various piece of software. We therefore restrict the container name to match the smallest common subset of both the DNS record and hostname RFCs of all operating systems implementing containers.

**Comment by stgraber** [comment]
If lookup by fqdn is important to you, you can for example do:

    lxc config set container-name user.fqdn a.b.c.d

At which point you can use this property in lxc list to search for it:

    lxc list user.fqdn=a.b.c.d

**Comment by major0** [comment]
##### /etc/hosts not a solution

While I understand that there is confusion regarding hostname resolution and interface resolution for many, that does not imply that assigning FQDN to the UTSNAME is invalid (which seems to be the claim), and I believe it is a fairly common operation.  There is a large body of software which relies on gethostname() to return the FQDN (as it does on many platforms) but which on GLIBC is a wrapper to uname(2) and which does *not* pass through name resolution.  As such the recommendation has been to assign the FQDN to sethostname() such that gethostname() behaves as expected.  This subject is well hashed out already and the common solution has been to follow GLIBC's recommendation:
```
The host name should always be a fully qualified domain name,
like `crispy-wheats--chicken.ai.mit.edu', not a simple name like
just `crispy-wheats-n-chicken'.
```

##### FQDN in UTSNAME is valid

Setting the UTSNAME to an FQDN is perfectly valid (not to mention it was recommended by GLIBC and others):
```
 # sysctl -w kernel.hostname=host.domain.com
 kernel.hostname = host.domain.com
 # hostname
 host.domain.com
 # uname -n
 host.domain.com
```

From hostname(1):
```
FILES
      /etc/hostname Historically this file was supposed to only contain the
      hostname and not the full canonical FQDN. Nowadays most software is
      able to cope with a full FQDN here. This file is read at boot time by
      the system initialization scripts to set the hostname.
```

*Note: The FQDN section of hostname(1) references a recommendation (not a requirement) that looks to be targeting system environments which have multiple IP/Name resolutions, which is outside the scope of a simple host/container.*

##### Some software expects FQDN

There is plenty of software out there which expects an FQDN from gethostname() (and or has learned to code around the behaviour found in glibc's gethostname()). In the past I have seen this expectation with Oracle, SSH, and Kerberos. (SSH+Kerberos expects the SSH principal to be named 'host/<fqdn>' where the FQDN is acquired by gethostbyname()). I also have concerns regarding SSH's handling of hostnames in SSH CA signed principals (See https://www.digitalocean.com/community/questions/how-to-set-fqdn-in-ubuntu)

##### The simplest use case

In the simplest use case we have a container with a single interface and a single IP assignment, and that interfaces resolution (externally) matches the container name. So we can have `{www,db,mail}.domain1.com` and `{www,db.mail}.domain2.com` and `{www,db.mail}.domain3.com`, etc.  Basically, the simplest and most straight-forward environment to deal with.  The proposed solution to this seems to be to come up with unique container names which are not hostnames (domain_web01, domain_mail02) and rework all the templates to use user.fqdn instead since the container.name can't be used in the generic case.  Going down this route we find that ignoring container.name also works for the complex case in which we have multiple interfaces on the system, so any tools written to wrap up the LXC command and handle the simple case will also work for the complex case, universally making container.name more or less pointless.

**Comment by stgraber** [comment]
You are obviously welcome to run sethostname inside your container or even just set /etc/hostname to whatever value you feel like and then deal with the consequences.

You can even instruct LXD to tell LXC to set the initial utsname to whatever value with:

    lxc config set container-name raw.lxc lxc.utsname=whatever.you.want

We however at the LXD level will not allow setting container names to value which some operating systems document as invalid as we intend for the REST API to be implementable on other platforms with container support (Solaris, BSD, Windows) and want to keep the API generic in that regard.

**Comment by major0** [comment]
As covered in depth already, the default on Linux, and the recommendation for years was to hand off the FQDN when setting the node name via sethostname().  As it is standard practice and in use .. I am not entirely certain which "consequences" you are hinting at, outside of the realm of FUD.  It doesn't help that BSD and Solaris happily accept an FQDN as the node name (no idea about Windows).

To be fair, a lot of Unices, Solaris included, give the illusion that they do not support FQDN node names when attempting to set the name via 'setuname -n', and I am honestly not certain if this is by design or just a failure to update the command-line tools.

From Solaris10:
```
# uname -s
SunOS
# setuname -n host.domain.com
Network node-name invalid: host.domain.com
# ./utsname host.domain.com
hostname: host.domain.com
# uname -n
host.domain.com
```

**Comment by major0** [comment]
From FreeBSD:
```
root@:~ # uname -v
FreeBSD 10.2-STABLE #0 r293802: Wed Jan 13 06:11:43 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
root@:~ # hostname host.domain.com
root@:~ # hostname
host.domain.com
root@:~ # uname -n
host.domain.com
```

**Comment by major0** [comment]
From NetBSD:
```
# uname -a
NetBSD vagrant 7.0 NetBSD 7.0 (GENERIC.201509250726Z) amd64
vagrant# hostname host.domain.com
vagrant# hostname
host.domain.com
vagrant# uname -n
host.domain.com
```

**Comment by major0** [comment]
From OpenBSD:
```
# uname -a                                                                                                                                                      
OpenBSD openbsd54.core.reaktor.fi 5.4 GENERIC#37 amd64
# hostname host.domain.com
# hostname
host.domain.com
# uname -n
host.domain.com
```

**Comment by major0** [comment]
Repeating Solaris to show that the UTSNAME can be set w/ standard tools and that it is purely setuname that seems to contain a bug:
```
SunOS node1 5.10 Generic_147148-26 i86pc i386 i86pc
# setuname -n host.domain.com
Network node-name invalid: host.domain.com
# hostname host.domain.com
# hostname
host.domain.com
# uname -n
host.domain.com
```

**Comment by major0** [comment]
Solaris11 seems to have simply removed the buggy `setuname` command which existed on Solaris10:
```
SunOS localhost 5.11 11.2 i86pc i386 i86pc Solaris
root@localhost:~# setuname -n host.domain.com
-bash: setuname: command not found
root@localhost:~# hostname host.domain.com
root@localhost:~# hostname
host.domain.com
root@localhost:~# uname -n
host.domain.com
```
