### ISSUE TITLE
Cleanup logging

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#1928]
There are a few things we should really sort out with logging as identified by recent bug reports:
 - Fix the log15 text logger to use consistent field ordering (makes it easier to grep or visually check)
 - Ensure we export context everywhere we can
 - Have wrapper functions for:
    - Debug
    - Info
    - Warn
    - Error
    - Critical
 - Make all wrapper functions look like LogError(msg string, ctx map[string]interface{})
 - Go through the whole daemon code and move debug strings between log levels so that we have:
  - Critical: Should never hit, daemon will be exiting or panicing as a result
  - Error: The function is failing despite valid user input
  - Warn: An optional feature is disabled due to lack of a required component or an invalid request was received from the user
  - Info: Normal user interactions, object creation, deletion, update, ...
  - Debug: HTTP server access, operation status, raw json dump of requests and replies, helper commands output, low level function calls (storage, ...)

The idea being that users can run our daemon with verbosity set to info and typically only see one log entry per call, on success, clearly stating what was done and on failure, what was requested and what went wrong.

For example for container launch which means a few background actions, we should see:
 - Creating container {name: "abc", operation: UUID, image: ...}
 - Downloading image {trigger: "/1.0/containers/abc", operation: UUID, image: ...}
 - Image downloaded {operation: UUID, fingerprint: HASH, image:...}
 - Container created {name: "abc", operation: UUID, image: ...}
 - Starting container {name: "abc", operation: UUID}
 - Container started {name: "abc", operation: UUID}

All of the above would be at the INFO log level.

**Comment by sts** [comment]
Ad Image download:
- Log which sha256 sum you expected and what was found in simplestreams json if it doesn't match.
- Always log which file lxd tried to download and the http status code, unless its taken from cache.

**Comment by stgraber** [comment]
@sts Tycho fixed the checksum issue a few days ago I think.

**Comment by sts** [comment]
Indeed!

**Comment by brauner** [comment]
Hm, wouldn't be  `LogError(msg string, ctx log.Ctx)` better than `LogError(msg string, ctx map[string]interface{})`. Else the interface functions like `Error()` will complain about being passed an odd number of arguments. So a wrapper would now look like:

```
func LogDebug(msg string, ctx log.Ctx) {
	if Log != nil {
		Log.Debug(msg, ctx)
	}
}

```

**Comment by brauner** [comment]
Hm, I guess we can easily cast.

**Comment by brauner** [comment]
So
```
func LogDebug(msg string, ctx map[string]interface{}) {
	if Log != nil {
		Log.Warn(msg, log.Ctx(ctx))
	}
}
```
would be doable. It seems the `log.Ctx()` cast is needed otherwise the daemon will panic because `log15` will complain about needing to append `nil` because of an odd sized `log.Ctx` being passed to it.

**Comment by stgraber** [comment]
Not sure that we caught everything, but certainly enough progress has been made to consider this issue closed. We'll tweak the rest as we notice them.
