### ISSUE TITLE
CGroup network class/pids controller & cpuset.effective_cpus

### ISSUE THREAD

**Issue by muradm** [lxc/lxd#1929]
Hi, trying lxd on up to date Ubuntu 14.04 LTS, and get the following in /var/log/upstart/lxd.log:
```
WARN[04-23|15:50:28] Couldn't find the CGroup network class controller, network limits will be ignored. 
WARN[04-23|15:50:28] Couldn't find the CGroup pids controller, process limits will be ignored. 
EROR[04-23|15:50:28] Error reading host's cpuset.effective_cpus 
```
There was more, but after digging, kernel command line parameters helped but not completely:
```
GRUB_CMDLINE_LINUX_DEFAULT="quiet cgroup_enable=memory swapaccount=1"
```
But above logs still there.

lxc-checkconfig:
```
root@node03:~# lxc-checkconfig 
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-3.13.0-83-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```

 * Distribution: Ubuntu
 * Distribution version: 14.04.4 LTS (trusty)
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.13.0-83-generic
   * LXC version: 2.0.0-0ubuntu2~ubuntu14.04.1~ppa1
   * LXD version: 2.0.0-0ubuntu4~ubuntu14.04.1~ppa1
   * Storage backend in use: ZFS

**Comment by stgraber** [comment]
Yeah, you'll need a newer kernel for the rest, LXD will still work fine though, just without those features. 

net_prio needs 3.16
pids needs 4.4

Can't remember for the cpuset bit.

**Comment by muradm** [comment]
After digging some code, it seems that WARNs handled gracefully without impact, while EROR with cpuset.effective_cpus wasn't..
Decided to move to 4.4 kernel on top of 14.04, because without it lxd seems meaningless if I can't enforce CPU/memory/network policies..

Didn't face any problem apart of promisc mode on bridge interface

**Comment by stgraber** [comment]
@hallyn any idea what that cpuset ERROR on 3.13 is about?

**Comment by hallyn** [comment]
...  well effective_cpus() is new as of

commit e2b9a3d7d8f4ab2f3491b8ed2ac6af692a2269b2
Author: Li Zefan <lizefan@huawei.com>
Date:   Wed Jul 9 16:47:03 2014 +0800

**Comment by stgraber** [comment]
@hallyn so we should fallback to copying cpus instead of effective_cpus if the latter doesn't exist?

**Comment by hallyn** [comment]
> @hallyn so we should fallback to copying cpus instead of effective_cpus if the latter doesn't exist?

yeah.

**Comment by stgraber** [comment]
@hallyn sending a branch?

**Comment by hallyn** [comment]
Sure I'll whip one up in a bit.
