### ISSUE TITLE
lxd init should offer to import ubuntu images

### ISSUE THREAD

**Issue by markshuttle** [lxc/lxd#1931]
With simplestreams support, it would be useful to import Ubuntu images by default and keep them up to date.

It would be necessary to turn that off or ask for a different outcome, but by default "lxd init" on its own should result in the ability to "lxc launch ubuntu" and get a sensible outcome (latest LTS).

**Comment by stgraber** [comment]
"lxc launch ubuntu:" or "lxc launch ubuntu:16.04" work out of the box. 

That said, both of those will cause an I initial image download when creating the first container. 

We can certainly add an option to lxd init to do an initial image copy. But note that you won't be saving any time in the usual case:

    sudo lxd init
    lxc launch ubuntu:

And in the event that you don't immediately use lxd, you may end up not even using that initial image (if one is released in between).

**Comment by markshuttle** [comment]
OK, we need to work on the UX, the colon is a passion killer :)

Mark

**Comment by stgraber** [comment]
The separator is unfortunately needed as a way to distinguish remote images (as is the case here with images coming from either the "ubuntu" or "ubuntu-daily" image servers) vs image aliases inside the local LXD image store.

That being said, we've been meaning for a bit to improve the UX by:
 - Adding the colon for you (with a note telling you we did) on launch and init when you don't happen to have a local image with the same name.
 - Adding another initial message alongside the "please run: sudo lxd init" one to suggest you run "lxc launch ubuntu:16.04" to create your first container.

**Comment by markshuttle** [comment]
Appreciate it's had some discussion, but I think we can do better, so
let's talk it over next time we meet.

Mark

**Comment by stgraber** [comment]
Just implemented my suggestion above, as expected, it's a tiny change on top of the existing client and gets you (on a newly setup LXD):

```
stgraber@dakara:~$ lxc launch ubuntu
The local image 'ubuntu' couldn't be found, trying 'ubuntu:' instead.
Creating archoplasmic-leeanne
Retrieving image: 100%
Starting archoplasmic-leeanne

stgraber@dakara:~$ lxc init ubuntu-daily
Creating the container
The local image 'ubuntu-daily' couldn't be found, trying 'ubuntu-daily:' instead.
Retrieving image: 100%
Container name is: excurvate-adele
```

This change doesn't break any existing use cases and basically just does what you mean in the couple of awkward cases that we have today "ubuntu:" and "ubuntu-daily:".

**Comment by markshuttle** [comment]
Thank you, that's pretty good. Is the "ubuntu" image in this case the
latest QA'd LTS image? IIRC we publish new images when there is a
secuirty update, or when we have two weeks worth of non-security updates
to roll up.

Mark

**Comment by stgraber** [comment]
The meaning of "ubuntu" there is server controlled, right now it points to the latest QAed Ubuntu 14.04 image with plan to switching it to 16.04 at the same time we flip the switch for people to get upgrade prompts from 14.04 to 16.04.

**Comment by stgraber** [comment]
There is no hardcoded logic in LXD itself, everything is advertised by the server through stream metadata, so we can make server side changes which will apply identically to all LXD users (and anyone else that consumes that particular bit of metadata).
