### ISSUE TITLE
sane defaults for lxd init

### ISSUE THREAD

**Issue by dustinkirkland** [lxc/lxd#1933]
Please add sane defaults to the lxd init questions, like we do for the debconf questions for lxd networking:

⟫ sudo lxd init
Name of the storage backend to use (dir or zfs) [zfs]: zfs
Create a new ZFS pool (yes/no) [YES]? yes
Name of the new ZFS pool [lxd]: lxd
Would you like to use an existing block device (yes/no) [YES]? no
Size in GB of the new loop device (1GB minimum) [10]: 10
Would you like LXD to be available over the network (yes/no) [NO]? no
Do you want to configure the LXD bridge (yes/no) [YES]? yes

The idea here is that "just hitting enter" will get you a decent, sane working setup.  Don't try to be perfect for everything, but we should be able to get this working well enough for most people.

Also, let's smart about this, too.  If I do choose yes on the network question, then when I'm prompted for the address to bind to, please pre-populate with a sane ip address.  Same with the default port, 8443.

**Comment by thomir** [comment]
I came here to report the same bug.

The lxd 'getting started' guide doesn't contain this information either (https://linuxcontainers.org/lxd/getting-started-cli/). As a new lxd user, I have no idea what the correct answer to any of these questions is. As well as adding sane defaults to the cli, adding more information to the getting started guide would help new users pick sensible answers.

**Comment by rayj00** [comment]
Defaults are always a good thing, but what about choosing something other than the default?   What are the implications?  And why and when to use something other than the defaults?  This information could ne even more important than using the default!
