### ISSUE TITLE
How to use lxd to provide containers (VPS) like digital ocean droplets?

### ISSUE THREAD

**Issue by DilipRenkila** [lxc/lxd#1937]
I have to set up a public cloud like digital ocean that can offer virtual private servers by using LXD. I have gone through LXD rest api but it requires authentication by ssl certs. Suppose lets assume that i have a server with lxd installed how can a user create a containers through web interface. Please guide me how can i acheive this?

**Comment by stgraber** [comment]
Not really in scope for the upstream LXD bug tracker.

If you want to build a full VPS solution on top of LXD, you'll most likely want to create your own API service which your customers would talk to and would handle billing, instance types, ... for you, then dispatching the actual LXD container creation to the right physical host behind the scenes.

You'll also need that custom code to handle things like public IPs, routing, firewall rules, ... all of which would be kinda expected from a public VPS provider.


One way to do all that at large scale would be to use OpenStack with nova-lxd, OpenStack supports creating API keys for users with different resource limits and then allow them to spawn containers themselves as they want.

A very simple of a standalone API client which offers its own minimal API for people to create and use containers is what we're using at https://linuxcontainers.org/lxd/try-it the code of which can be found at:
 - https://github.com/lxc/lxd-demo-server (the daemon)
 - https://github.com/lxc/linuxcontainers.org (the client)


Closing this issue as it's out of scope for the LXD issue tracker.

**Comment by DilipRenkila** [comment]
Please explain me about https://github.com/lxc/linuxcontainers.org (the client)

**Comment by stgraber** [comment]
https://github.com/lxc/linuxcontainers.org/blob/master/static/js/tryit.js is the javascript code that talks over the public REST API exported by lxd-demo-server.
