### ISSUE TITLE
better support for iterative live migration

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#1938]
This really has two parts:
1. we need to support iterative memory migration in the first place (via p.haul), so that in case the container has allocated a bunch of memory, the downtime during a live migration doesn't include all the time it takes to send this memory
2. we need to support more than one iteration of sending filesystems. Right now we do one iteration, but we should iterate as necessary. To do this, we'll need a nice way to figure out the filesystem delta, which may only be possible with zfs and btrfs.

**Comment by stgraber** [comment]
Closed as we now have the memory pre-migration support and there's no more upstream activity on p-haul.
