### ISSUE TITLE
Add a low level scripting mode to the Go client

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#1943]
Our command line client is pretty good at getting things done when a user is controlling it. It's however not so great for scripting purposes.

We could implement a scripting action in the existing client which would let you perform API calls directly, having the Go client just take care of operation handling for you.

**Comment by sean-jc** [comment]
Are you thinking the command would essentially be a pass-through to the REST API, with the versioning taken care of by LXC?  For example, `lxc rest containers` would be the equivalent of `curl -s --unix-socket /var/lib/lxd/unix.socket ./1.0/containers`.

**Comment by stgraber** [comment]
I'm not sure yet. I think I'll first re-design client.go so that it covers 100% of the existing LXD API and uses all the relevant features, then will look whether it's best for the scripting interface to be a tiny wrapper on the raw REST API or a wrapper for the Go client API.

**Comment by stgraber** [comment]
So my current thought for what would be useful to do here is adding a new "query" command to the "lxc" command line tool. This would be one of those commands that are hidden by default.

It would effectively work like this:

    lxc query [-X <action>] [-d <data>] [--wait] [--raw] [<remote>]:<API path> 

Where:
 - -X indicates the http action (GET, POST, PUT, PATCH or DELETE), defaults to "GET"
 - -d is the data to send as part of the query. We'll support the "@path" syntax from curl there too.
 - --wait is used to wait for a background operation to complete. If not passed, the operation information is output and we return immediately.
 - --raw has "lxc query" return the server's output without any attempt to extract a clean error message or format the JSON output to be more user readable.

**Comment by stgraber** [comment]
This should effectively make "lxc query" work much like curl but with the convenience of LXD remotes (so authentication is taken care of), clean JSON output and with some LXD-specific features like being able to wait for a background operation to complete.
