### ISSUE TITLE
container copy on dir backend on xenial hangs

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#1944]
It seems that something is different with how xenial's rsync behaves w.r.t. exiting when it gets EOF (I think, this is all just based on a 5 minute look at the problem). The result of this is that `lxc copy foo otherhost:foo` hangs indefinitely when using the directory backend. The workaround here is just to use ZFS.

**Comment by stgraber** [comment]
Container copy and move on the try-it server appear to work fine and those I believe are using rsync, so it may be a bit trickier than we first thought.

Our testsuite also does rsync migration and it's been similarly passing for me on Xenial.
