### ISSUE TITLE
Cron doesn't start the container sometimes

### ISSUE THREAD

**Issue by rchincholkar** [lxc/lxd#1945]
Hi Team,

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 14.04.4 LTS

   * Kernel version: 3.16.0-62-generic
   * LXC version: 2.0.0.rc12
   * LXD version: 2.0.0.rc5
   * Storage backend in use: btrfs

# Issue description
I have set daily cron to check the if the container running, 
if its running then it executes -
lxc stop containername
lxc start containername
and if its not running then it simply starts it.

If I run the script manually, it works. It even works in cron but sometimes cron doesnt start the container. 
I found some debug logs when the cron failed to start the container : 

            lxc 20160426060046.730 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/d78a9d7e97b4b375//var/lib/lxd/containers
            lxc 20160426060046.730 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
            lxc 20160426060046.731 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'app-container' is in 'RUNNING' state
            lxc 20160426060046.731 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
            lxc 20160426060050.032 DEBUG    lxc_start - start.c:signal_handler:341 - container init process exited
            lxc 20160426060050.032 DEBUG    lxc_start - start.c:__lxc_start:1314 - Container halting
            lxc 20160426060050.032 DEBUG    lxc_start - start.c:__lxc_start:1329 - Pushing physical nics back to host namespace
            lxc 20160426060050.032 DEBUG    lxc_start - start.c:__lxc_start:1332 - Tearing down virtual network devices used by container
            lxc 20160426060050.032 WARN     lxc_conf - conf.c:lxc_delete_network:2907 - failed to remove interface 412 'eth0'
            lxc 20160426060050.032 INFO     lxc_error - error.c:lxc_error_set_and_log:55 - child <4079> ended on signal (2)
            lxc 20160426060050.032 WARN     lxc_conf - conf.c:lxc_delete_network:2907 - failed to remove interface 412 'eth0'
            lxc 20160426060050.101 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'app-container', config section 'lxc'
            lxc 20160426060050.159 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type u nsid 0 hostid 165536 range 65536
            lxc 20160426060050.159 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type g nsid 0 hostid 165536 range 65536
            lxc 20160426060050.605 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 7 stop' for container 'app-container', config section 'lxc'
            lxc 20160426060050.731 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response

Thanks!
Rahul C

**Comment by IshwarKanse** [comment]
Hi @rchincholkar , can you update to the latest stable release and see if it solves your problem ? LXD 2.0 has been released.

**Comment by stgraber** [comment]
There's nothing obviously wrong in the provided log and it would indeed be good to check if 2.0 final fixes this.

**Comment by rchincholkar** [comment]
Thanks @stgraber @IshwarKanse..
will upgrade and share the result soon..

**Comment by rchincholkar** [comment]
I upgraded LXD to 2.0 . 
I checked the script logs today and found following logs, 

Logs:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x428e37]

goroutine 1 [running]:
panic(0x8c47e0, 0xc82000e0c0)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
main.(*listCmd).IP4ColumnData(0xc820073e00, 0xc820152230, 0x6, 0xc8201541b0, 0xece7b2227, 0x0, 0xdab120, 0xc8201541e0, 0x0, 0xc820154240, ...)
	/build/lxd-bvH6ID/lxd-2.0.0/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:402 +0x97
main.(*listCmd).IP4ColumnData-fm(0xc820152230, 0x6, 0xc8201541b0, 0xece7b2227, 0x0, 0xdab120, 0xc8201541e0, 0x0, 0xc820154240, 0xc820154270, ...)
	/build/lxd-bvH6ID/lxd-2.0.0/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:365 +0x94
main.(*listCmd).listContainers(0xc820073e00, 0xc8200f05a0, 0xc8201a6000, 0xd, 0xd, 0xc8201057d8, 0x0, 0x0, 0xc8201ae000, 0x6, ...)
	/build/lxd-bvH6ID/lxd-2.0.0/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:284 +0x12ef
main.(*listCmd).run(0xc820073e00, 0xc820073f80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/lxd-bvH6ID/lxd-2.0.0/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:390 +0x119e
main.run(0x0, 0x0)
	/build/lxd-bvH6ID/lxd-2.0.0/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:150 +0x1098
main.main()
	/build/lxd-bvH6ID/lxd-2.0.0/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:23 +0x3a

This logs thrown when the script executed lxc list command to check the container status after stopping the container.
But the script ran successfully and restarted the container via cron. 

Thanks,
Rahul C

**Comment by stgraber** [comment]
We fixed that particular issue with 85ba871719b44036a6a7d231cf2d7391ae41ed56 it will make it in the next stable release.

This is most likely racy so re-trying has a good chance of working.
