### ISSUE TITLE
Can lxd container support --ip as docker does ?

### ISSUE THREAD

**Issue by nuxxer** [lxc/lxd#1946]
Currently my company's trying to leverage lxd for critical project. (shifting direction from docker to lxd). 
However the road block is that lxd (lxc cmd) lacking optional flag to launch a lxd container with specific IP address. Is there a plan to support this in near future ? Thanks. 

-jin

**Comment by hallyn** [comment]
The recommended way to do this would be to assign a hardware address to the container and use your dhcp server to assign the specific ip address.

**Comment by stgraber** [comment]
Right now networking is managed outside of LXD, all that LXD does is give you a stable MAC address and connect your layer-2, so indeed to use static network, either configure your networking INSIDE the container to use a static IP or configure your DHCP server to give the IP you want to that MAC address.

We are considering adding basic bridge networking configuration to LXD itself in the future, at which point you would be offered a way to configure a static address that would then be served by the LXD run DHCP server, but there's no clear timeline for that.

You can also pre-configure your network namespace today by using some raw.lxc configuration keys, however note that this is a bit of a workaround and not something we really support:

```
raw.lxc: |
    lxc.network.0.ipv4 = 10.0.2.3/24
    lxc.network.0.gateway = 10.0.2.1
```

**Comment by nuxxer** [comment]
Appreciate the ideas. You guys rock. 👍

**Comment by stgraber** [comment]
Going to close this issue for not as besides the workaround given above, this is currently out of scope for LXD. Currently LXD only sets up networking layer-2.

If we do add bridge configuration directly to LXD in the future, setting static DHCP entries will certainly be part of it.

**Comment by eumel8** [comment]
just found out, dnsmasq is running for mapping container names to dynamic ip-addresses:

```
root@c1:~# nslookup c1
Server:         10.21.37.1
Address:        10.21.37.1#53

Name:   c1.lxd
Address: 10.21.37.80
```
so it's possible to build container-container-connection via hostnames (i.e. webserver-database container)

**Comment by nuxxer** [comment]
@stgraber yes. it will be certainly an appreciated feature. !
