### ISSUE TITLE
last_used_at field

### ISSUE THREAD

**Issue by aarnaud** [lxc/lxd#1958]
Hi,

It's possible to add the "last starting date" field in LXD ?

I wan't to implement a auto clean container, but i should use the starting date and not the creation date.

I can try a merge request, but i am not a expert of golang.

Thanks,

**Comment by stgraber** [comment]
Yes it should be possible to record and export it, we'd probably call it last_used_at in the API for consistency with the image field of the same name.

Implementing this would require:
 - Addition to DB schema + DB update script
 - Addition to the API, including an API extension entry and updated documentation
 - Support in the client, including support for the field being missing (older LXD daemons)
 - Code that bumps the value on container start, be that from regular start or from migration (startCommon should do).

**Comment by tomposmiko** [comment]
Is there a like button somewhere on github?:)

**Comment by anasdox** [comment]
+1

**Comment by ctrlrsf** [comment]
Almost done working on a PR to implement this. 

@stgraber what do you suggest we initialize last_used_at to? This date will be visible when a container is created but not yet started.

last_used_at for images is initialized with time.Time{} but is quickly "used" and becomes time.Now() so 1754 date not very visible. Should a container's last_used_at initial value be the same, or should it be the friendlier 1970 date?

golang time.Time{} zero value:
```
    "last_used_at": "1754-08-30T22:43:41.128654848Z"
```
or just time.Unix(0, 0).UTC()?
```
    "last_used_at": "1970-01-01T00:00:00Z"
```

**Comment by stgraber** [comment]
I think the other similar timestamps (on images) are set to the 0 EPOCH and simply don't show up in "lxc info" when they're set to 0.
