### ISSUE TITLE
API : upload a file to the container not keep lines returns.

### ISSUE THREAD

**Issue by tozaz** [lxc/lxd#1959]
I tryed some curl tricks with no luck, so I don't think this is a curl issue.
Hope somebody could help.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 15.10
 * The output of "lxc info":
# lxc info
apicompat: 0
auth: trusted
environment:
  addresses:
  - 192.168.0.240:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFjTCCA3WgAwIBAgIQdyLTVbtyVvDOcecAc84QAjANBgkqhkiG9w0BAQsFADAy
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRIwEAYDVQQDDAlyb290QHRl
    c3QwHhcNMTYwNDIzMjEwMDUwWhcNMjYwNDIxMjEwMDUwWjAyMRwwGgYDVQQKExNs
    aW51eGNvbnRhaW5lcnMub3JnMRIwEAYDVQQDDAlyb290QHRlc3QwggIiMA0GCSqG
    SIb3DQEBAQUAA4ICDwAwggIKAoICAQCeHiJLvnEMeG2HytpKqisJmFE8UxLxzqov
    sINfTnwcqIg9ArDNBtK/WjptCyQmraVUkOrtpyytQgmRtVk9OMOf2+eUXRBEOZXU
    LIvfwTQd1TKszzUQU0TrJUdl3GXFYf9ArdEiqIh0hKQuC9Dt1LYCwFqSlJGyYLZu
    czDvZrQAQ72gZ0OrXPwxUXO3H6k8LMyzKecZXXtM8gzBb/at3vHTyCAr1K5MRX0P
    rcNqknI+ItHzdT1EOZmuezlFU0aJvBHS46P9wPq/ptZ3VU+ux5op7CNkzKBmw8NO
    hAZrSl/OXzkKvE3YO2kHmwHuhqJBlGonxgZiopHcUx5bhbH+MLyiyB3mO/5EwLvA
    EcXxK5jx/z0CLFpmtp6G9qP0n2kXfqKX2JEvzvRjFXmv3s/QVKoWiPKDKgc9WfXG
    N6p7JkmCrk40pm8rhLBZ8mpvcKX/q4VkxA6OAlwirm+kcQ4UPJcHSs8ldNkqYy5w
    pGkJj9Iv/+TedSjIeXgkCJOsmtvn/oUlPqd8sTNqhceoE3WSzD25V0Jk8ijTax/7
    f4MOXVyuvYOK9fva5aAoONclKKbOyOvqg9YTrgO071nTkaeU+ejIxc6m4qu3DB5a
    xSRsu7sPaW7WYAJuts5eYhfAlxwDImDsAenHk4LEcchAkG9h4IOSgm1TXAzIQOKH
    8te1RsIcswIDAQABo4GeMIGbMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMGYGA1UdEQRfMF2CBHRlc3SCDzE5Mi4xNjgu
    MC41NC8yNIIcZmU4MDo6YmE5Nzo1YWZmOmZlMGQ6NTlkMi82NIIaZmU4MDo6M2Nj
    ZjpmZjpmZWY4OmUwOTYvNjSCCmZlODA6OjEvNjQwDQYJKoZIhvcNAQELBQADggIB
    AICFJNaLtZfvxWxsBYEanV16JE4kuQxIcmaRTpHudOj/YBkrVws+TQva2Y8n82/E
    BOfdF5uuCRenbTz0wM5nQ2j/VJDJLepmXVUj/4mStuZgbOsJ3z/SR5tJxlEmDfaW
    G/hEAKUgMXL3Nn3H6dQdeMaTILVZmiLOx16Uw38M4VIUZ40Iuj8M+e4j+aL2LXbV
    1QN8XRwckSXAThi5TKQlZUxpKG9Zf21DVzpeDRJWOddgJxq1MuDX5q53HOeM2YB7
    6rrZ5Xh3qmrkkW51KyYYiRo4I0/S7+FDlhx8i5Vg8sookj3lXSLWzKHnydzH7Xfe
    j2xjnis9hLsBgCsuF2xPR/ACTDxIzuilNAIehuOADzO1blB2HzIkT7HwQrpZlV2N
    Q6tFJ3LqppXAbbUxbtMPq6Mr6tTKQ8ztQex9Iisf8zk9ifCwWZpwzIL7cpZYYP9o
    1NITnxNYVNAbPxMq6tNN5nKp5U5Lot9hwwIfW7QIQAjb5SmBVvoFhmU6JyuwwtyA
    OrMsuq+c4QexJAOGqdgfLlZJYT9k2p9kfK2kdhm/jL5A
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 1122
  serverversion: 2.0.0
  storage: zfs
  storageversion: "5"
config:
  core.https_address: 192.168.0.240:8443
  core.trust_password: true
  storage.zfs_pool_name: zfspool
public: false

# Issue description

When I upload a text file to a container the destination file has no line return.

# Steps to reproduce

 1. Step one

cat test
one line
another line

 2. Step two

curl -k --cert client.pem --key client.key -H "X-LXD-uid: 0" -H "X-LXD-gid: 0" -H "X-LXD-mode: 0700" -H "Content-Type: application/octet-stream" -X POST -d '@test' https://mylxdhost:8443/1.0/containers/fedora/files?path=/tmp/test
 
3. Step three

lxc exec fedora cat /tmp/test

one lineanother line

**Comment by stgraber** [comment]
Do you see the same behavior if you use "lxc file push"?

**Comment by stgraber** [comment]
You need to use --data-binary instead of -d apparently, otherwise curl messes it up.

**Comment by stgraber** [comment]
So:

    curl -k --cert client.pem --key client.key -H "X-LXD-uid: 0" -H "X-LXD-gid: 0" -H "X-LXD-mode: 0700" -H "Content-Type: application/octet-stream" -X POST --data-binary '@test' https://mylxdhost:8443/1.0/containers/fedora/files?path=/tmp/test

**Comment by tozaz** [comment]
Thanks you Stéphane.
That's works with --data-binary.
I had not the same issue when using lxc file push

`lxc file push test fedora/tmp/test`
`lxc exec fedora cat /tmp/test`
one line
another line
