### ISSUE TITLE
lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123'

### ISSUE THREAD

**Issue by rchincholkar** [lxc/lxd#1961]
Hi,

I am getting following error when I try to start any stopped container and when I try to launch a new container.

root@lxd-prod3:~# lxc start test123
error: Error calling 'lxd forkstart test123 /var/lib/lxd/containers /var/log/lxd/test123/lxc.conf': err='exit status 1'
Try `lxc info --show-log test123` for more info

root@lxd-prod3:~# lxc info --show-log test123
Name: test123
Architecture: x86_64
Created: 2016/04/28 05:42 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20160428111210.781 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type u nsid 0 hostid 165536 range 65536
            lxc 20160428111210.781 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type g nsid 0 hostid 165536 range 65536
            lxc 20160428111214.394 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type u nsid 0 hostid 165536 range 65536
            lxc 20160428111214.394 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type g nsid 0 hostid 165536 range 65536
            lxc 20160428111214.615 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3 
            lxc 20160428111214.615 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 7 
            lxc 20160428111214.617 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /var/lib/lxd/containers test123
            lxc 20160428111214.617 INFO     lxc_utils - utils.c:setproctitle:1460 - setting cmdline failed - Invalid argument
            lxc 20160428111214.617 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 7 
            lxc 20160428111214.617 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
            lxc 20160428111214.617 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
            lxc 20160428111214.617 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for reject_force_umount action 0
            lxc 20160428111214.617 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160428111214.617 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for reject_force_umount action 0
            lxc 20160428111214.617 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .[all].
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .kexec_load errno 1.
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for kexec_load action 327681
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for kexec_load action 327681
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .open_by_handle_at errno 1.
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for open_by_handle_at action 327681
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for open_by_handle_at action 327681
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .init_module errno 1.
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for init_module action 327681
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for init_module action 327681
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .finit_module errno 1.
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for finit_module action 327681
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for finit_module action 327681
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for finit_module action 327681
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .delete_module errno 1.
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for delete_module action 327681
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for delete_module action 327681
            lxc 20160428111214.618 INFO     lxc_seccomp - seccomp.c:parse_config_v2:456 - Merging in the compat seccomp ctx into the main one
            lxc 20160428111214.618 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 21 start' for container 'test123', config section 'lxc'
            lxc 20160428111214.618 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160428111214.618 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 7
            lxc 20160428111214.620 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/d78a9d7e97b4b375//var/lib/lxd/containers
            lxc 20160428111214.733 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
            lxc 20160428111214.734 DEBUG    lxc_console - console.c:lxc_console_peer_default:473 - no console peer
            lxc 20160428111214.734 INFO     lxc_start - start.c:lxc_init:488 - 'test123' is initialized
            lxc 20160428111214.734 DEBUG    lxc_start - start.c:__lxc_start:1259 - Not dropping cap_sys_boot or watching utmp
            lxc 20160428111214.735 INFO     lxc_start - start.c:resolve_clone_flags:956 - Cloning a new user namespace
            lxc 20160428111214.736 DEBUG    lxc_conf - conf.c:instantiate_macvlan:2685 - instantiated macvlan 'mc7JSSIO', index is '470' and mode '4'
            lxc 20160428111214.736 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for test123
            lxc 20160428111214.737 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123'
            lxc 20160428111214.737 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123: No space left on device
            lxc 20160428111214.737 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-1'
            lxc 20160428111214.737 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-1: No space left on device
            lxc 20160428111214.737 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-2'
            lxc 20160428111214.737 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-2: No space left on device
            lxc 20160428111214.738 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-3'
            lxc 20160428111214.738 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-3: No space left on device
            lxc 20160428111214.738 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-4'
            lxc 20160428111214.738 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-4: No space left on device

We cant upgrade this server now, Its in production. 
Is there any workaround for this?

Thanks!

**Comment by stgraber** [comment]
That's pretty odd, I'm unsure under what kind of condition this would happen...

Can you paste the output of:
 - cat /proc/self/mountinfo
 - df -a
 - df -a -i
 - dmesg

Unless you have something very wrong going on with /sys/fs/cgroup/memory, this smells very much like a kernel bug to me.

**Comment by rchincholkar** [comment]
Hi @stgraber thanks for reply..
When I stopped all containers on the server and then started one by one, It resolved the issue.
Later on, I did proceed with lxd upgrade to stable 2.0.0 because everyone opted for an upgrade. Now things are fine. Do you still want me to get the output of the mentioned commands, If yes I will post it tomorrow..
I am not sure If I can reproduce this issue. 

Thanks, 
Rahul C

**Comment by stgraber** [comment]
Nope, those would only have been useful on a system currently exhibiting the problem.

I'll close the issue for now, feel free to update it if you ever run into this again.

**Comment by yogeshbodke** [comment]
Hi stgraber,

We faced simmiler issue today in one of our LXD host. Following are container logs.

Log:

			lxc 20160602083833.623 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-984: No space left on device
            lxc 20160602083833.650 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-985'
            lxc 20160602083833.650 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-985: No space left on device
            lxc 20160602083833.651 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-986'
            lxc 20160602083833.651 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-986: No space left on device
            lxc 20160602083833.651 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-987'
            lxc 20160602083833.651 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-987: No space left on device
            lxc 20160602083833.652 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-988'
            lxc 20160602083833.652 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-988: No space left on device
            lxc 20160602083833.652 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-989'
            lxc 20160602083833.652 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-989: No space left on device
            lxc 20160602083833.653 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-990'
            lxc 20160602083833.653 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-990: No space left on device
            lxc 20160602083833.660 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-991'
            lxc 20160602083833.660 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-991: No space left on device
            lxc 20160602083833.661 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-992'
            lxc 20160602083833.661 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-992: No space left on device
            lxc 20160602083833.661 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-993'
            lxc 20160602083833.661 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-993: No space left on device
            lxc 20160602083833.662 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-994'
            lxc 20160602083833.662 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-994: No space left on device
            lxc 20160602083833.662 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-995'
            lxc 20160602083833.662 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-995: No space left on device
            lxc 20160602083833.662 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-996'
            lxc 20160602083833.662 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-996: No space left on device
            lxc 20160602083833.663 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-997'
            lxc 20160602083833.663 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-997: No space left on device
            lxc 20160602083833.663 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-998'
            lxc 20160602083833.663 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-998: No space left on device
            lxc 20160602083833.806 ERROR    lxc_utils - utils.c:mkdir_p:253 - No space left on device - failed to create directory '/sys/fs/cgroup/memory//lxc/test123-999'
            lxc 20160602083833.806 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1086 - No space left on device - Failed to create /sys/fs/cgroup/memory//lxc/test123-999: No space left on device
            lxc 20160602083833.806 ERROR    lxc_cgfsng - cgfsng.c:cgfsng_create:1078 - Too many conflicting cgroup names
            lxc 20160602083833.806 ERROR    lxc_start - start.c:lxc_spawn:1043 - failed creating cgroups
            lxc 20160602083833.951 ERROR    lxc_start - start.c:__lxc_start:1286 - failed to spawn 'test123'
            lxc 20160602083833.951 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'test123', config section 'lxc'
            lxc 20160602083834.454 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 28 stop' for container 'test123', config section 'lxc'
            lxc 20160602083834.572 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160602083834.572 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160602083834.572 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160602083835.034 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type u nsid 0 hostid 165536 range 65536
            lxc 20160602083835.034 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type g nsid 0 hostid 165536 range 65536
            lxc 20160602083846.780 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type u nsid 0 hostid 165536 range 65536
            lxc 20160602083846.780 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type g nsid 0 hostid 165536 range 65536
            lxc 20160602083846.784 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type u nsid 0 hostid 165536 range 65536
            lxc 20160602083846.784 INFO     lxc_confile - confile.c:config_idmap:1495 - read uid map: type g nsid 0 hostid 165536 range 65536

Command Output:

# cat /proc/self/mountinfo
16 21 0:15 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
17 21 0:3 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
18 21 0:5 / /dev rw,relatime - devtmpfs udev rw,size=49485792k,nr_inodes=12371448,mode=755
19 18 0:12 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=000
20 21 0:16 / /run rw,nosuid,noexec,relatime - tmpfs tmpfs rw,size=9899420k,mode=755
21 0 0:17 /@ / rw,relatime - btrfs /dev/dm-0 rw,space_cache
22 16 0:20 / /sys/fs/cgroup rw,relatime - tmpfs none rw,size=4k,mode=755
23 16 0:21 / /sys/fs/fuse/connections rw,relatime - fusectl none rw
24 16 0:6 / /sys/kernel/debug rw,relatime - debugfs none rw
25 16 0:10 / /sys/kernel/security rw,relatime - securityfs none rw
26 20 0:22 / /run/lock rw,nosuid,nodev,noexec,relatime - tmpfs none rw,size=5120k
27 20 0:23 / /run/shm rw,nosuid,nodev,relatime - tmpfs none rw
29 20 0:25 / /run/user rw,nosuid,nodev,noexec,relatime - tmpfs none rw,size=102400k,mode=755
30 16 0:26 / /sys/fs/pstore rw,relatime - pstore none rw
41 21 8:1 / /boot rw,relatime - ext2 /dev/sda1 rw
42 21 0:17 /@home /home rw,relatime - btrfs /dev/dm-0 rw,space_cache
43 22 0:39 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime - cgroup systemd rw,name=systemd
44 20 0:40 / /run/lxcfs/controllers rw,relatime - tmpfs tmpfs rw,size=100k,mode=700
45 44 0:39 / /run/lxcfs/controllers/name=systemd rw,relatime - cgroup name=systemd rw,name=systemd
46 44 0:36 / /run/lxcfs/controllers/hugetlb rw,relatime - cgroup hugetlb rw,hugetlb
47 44 0:35 / /run/lxcfs/controllers/net_prio rw,relatime - cgroup net_prio rw,net_prio
48 44 0:34 / /run/lxcfs/controllers/perf_event rw,relatime - cgroup perf_event rw,perf_event
49 44 0:33 / /run/lxcfs/controllers/blkio rw,relatime - cgroup blkio rw,blkio
50 44 0:32 / /run/lxcfs/controllers/net_cls rw,relatime - cgroup net_cls rw,net_cls
51 44 0:31 / /run/lxcfs/controllers/freezer rw,relatime - cgroup freezer rw,freezer
52 44 0:30 / /run/lxcfs/controllers/devices rw,relatime - cgroup devices rw,devices
53 44 0:29 / /run/lxcfs/controllers/memory rw,relatime - cgroup memory rw,memory
54 44 0:28 / /run/lxcfs/controllers/cpuacct rw,relatime - cgroup cpuacct rw,cpuacct
55 44 0:27 / /run/lxcfs/controllers/cpu rw,relatime - cgroup cpu rw,cpu
56 44 0:24 / /run/lxcfs/controllers/cpuset rw,relatime - cgroup cpuset rw,cpuset
57 21 0:41 / /var/lib/lxcfs rw,nosuid,nodev,relatime - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
28 22 0:24 / /sys/fs/cgroup/cpuset rw,relatime - cgroup cgroup rw,cpuset
31 22 0:27 / /sys/fs/cgroup/cpu rw,relatime - cgroup cgroup rw,cpu
32 22 0:28 / /sys/fs/cgroup/cpuacct rw,relatime - cgroup cgroup rw,cpuacct
33 22 0:29 / /sys/fs/cgroup/memory rw,relatime - cgroup cgroup rw,memory
34 22 0:30 / /sys/fs/cgroup/devices rw,relatime - cgroup cgroup rw,devices
35 22 0:31 / /sys/fs/cgroup/freezer rw,relatime - cgroup cgroup rw,freezer
36 22 0:32 / /sys/fs/cgroup/net_cls rw,relatime - cgroup cgroup rw,net_cls
37 22 0:33 / /sys/fs/cgroup/blkio rw,relatime - cgroup cgroup rw,blkio
38 22 0:34 / /sys/fs/cgroup/perf_event rw,relatime - cgroup cgroup rw,perf_event
39 22 0:35 / /sys/fs/cgroup/net_prio rw,relatime - cgroup cgroup rw,net_prio
40 22 0:36 / /sys/fs/cgroup/hugetlb rw,relatime - cgroup cgroup rw,hugetlb
58 21 0:17 /@/var/lib/lxd/shmounts /var/lib/lxd/shmounts rw,relatime shared:1 - btrfs /dev/dm-0 rw,space_cache

# df -a
Filesystem     1K-blocks      Used Available Use% Mounted on
sysfs                  0         0         0    - /sys
proc                   0         0         0    - /proc
udev            49485792         4  49485788   1% /dev
devpts                 0         0         0    - /dev/pts
tmpfs            9899420       868   9898552   1% /run
/dev/dm-0      875810816 491519464 380338520  57% /
none                   4         0         4   0% /sys/fs/cgroup
none                   0         0         0    - /sys/fs/fuse/connections
none                   0         0         0    - /sys/kernel/debug
none                   0         0         0    - /sys/kernel/security
none                5120         0      5120   0% /run/lock
none            49497084         0  49497084   0% /run/shm
none              102400         0    102400   0% /run/user
none                   0         0         0    - /sys/fs/pstore
/dev/sda1         240972     69674    158857  31% /boot
/dev/dm-0      875810816 491519464 380338520  57% /home
systemd                0         0         0    - /sys/fs/cgroup/systemd
tmpfs                100         0       100   0% /run/lxcfs/controllers
name=systemd           -         -         -    - /run/lxcfs/controllers/name=systemd
hugetlb                -         -         -    - /run/lxcfs/controllers/hugetlb
net_prio               -         -         -    - /run/lxcfs/controllers/net_prio
perf_event             -         -         -    - /run/lxcfs/controllers/perf_event
blkio                  -         -         -    - /run/lxcfs/controllers/blkio
net_cls                -         -         -    - /run/lxcfs/controllers/net_cls
freezer                -         -         -    - /run/lxcfs/controllers/freezer
devices                -         -         -    - /run/lxcfs/controllers/devices
memory                 -         -         -    - /run/lxcfs/controllers/memory
cpuacct                -         -         -    - /run/lxcfs/controllers/cpuacct
cpu                    -         -         -    - /run/lxcfs/controllers/cpu
cpuset                 -         -         -    - /run/lxcfs/controllers/cpuset
lxcfs                  0         0         0    - /var/lib/lxcfs
cgroup                 0         0         0    - /sys/fs/cgroup/cpuset
cgroup                 0         0         0    - /sys/fs/cgroup/cpu
cgroup                 0         0         0    - /sys/fs/cgroup/cpuacct
cgroup                 0         0         0    - /sys/fs/cgroup/memory
cgroup                 0         0         0    - /sys/fs/cgroup/devices
cgroup                 0         0         0    - /sys/fs/cgroup/freezer
cgroup                 0         0         0    - /sys/fs/cgroup/net_cls
cgroup                 0         0         0    - /sys/fs/cgroup/blkio
cgroup                 0         0         0    - /sys/fs/cgroup/perf_event
cgroup                 0         0         0    - /sys/fs/cgroup/net_prio
cgroup                 0         0         0    - /sys/fs/cgroup/hugetlb
/dev/dm-0      875810816 491519464 380338520  57% /var/lib/lxd/shmounts

# df -a -i
Filesystem       Inodes IUsed    IFree IUse% Mounted on
sysfs                 0     0        0     - /sys
proc                  0     0        0     - /proc
udev           12371448   500 12370948    1% /dev
devpts                0     0        0     - /dev/pts
tmpfs          12374271   788 12373483    1% /run
/dev/dm-0             0     0        0     - /
none           12374271    13 12374258    1% /sys/fs/cgroup
none                  0     0        0     - /sys/fs/fuse/connections
none                  0     0        0     - /sys/kernel/debug
none                  0     0        0     - /sys/kernel/security
none           12374271     2 12374269    1% /run/lock
none           12374271     1 12374270    1% /run/shm
none           12374271     3 12374268    1% /run/user
none                  0     0        0     - /sys/fs/pstore
/dev/sda1         62248   306    61942    1% /boot
/dev/dm-0             0     0        0     - /home
systemd               0     0        0     - /sys/fs/cgroup/systemd
tmpfs          12374271    13 12374258    1% /run/lxcfs/controllers
name=systemd          -     -        -     - /run/lxcfs/controllers/name=systemd
hugetlb               -     -        -     - /run/lxcfs/controllers/hugetlb
net_prio              -     -        -     - /run/lxcfs/controllers/net_prio
perf_event            -     -        -     - /run/lxcfs/controllers/perf_event
blkio                 -     -        -     - /run/lxcfs/controllers/blkio
net_cls               -     -        -     - /run/lxcfs/controllers/net_cls
freezer               -     -        -     - /run/lxcfs/controllers/freezer
devices               -     -        -     - /run/lxcfs/controllers/devices
memory                -     -        -     - /run/lxcfs/controllers/memory
cpuacct               -     -        -     - /run/lxcfs/controllers/cpuacct
cpu                   -     -        -     - /run/lxcfs/controllers/cpu
cpuset                -     -        -     - /run/lxcfs/controllers/cpuset
lxcfs                 0     0        0     - /var/lib/lxcfs
cgroup                0     0        0     - /sys/fs/cgroup/cpuset
cgroup                0     0        0     - /sys/fs/cgroup/cpu
cgroup                0     0        0     - /sys/fs/cgroup/cpuacct
cgroup                0     0        0     - /sys/fs/cgroup/memory
cgroup                0     0        0     - /sys/fs/cgroup/devices
cgroup                0     0        0     - /sys/fs/cgroup/freezer
cgroup                0     0        0     - /sys/fs/cgroup/net_cls
cgroup                0     0        0     - /sys/fs/cgroup/blkio
cgroup                0     0        0     - /sys/fs/cgroup/perf_event
cgroup                0     0        0     - /sys/fs/cgroup/net_prio
cgroup                0     0        0     - /sys/fs/cgroup/hugetlb
/dev/dm-0             0     0        0     - /var/lib/lxd/shmounts

# dmesg

[6090047.555971] audit: type=1400 audit(1464827442.582:507): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-test456_</var/lib/lxd>" pid=13215 comm="apparmor_parser"
[6090049.724050] audit: type=1400 audit(1464827444.750:508): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-test456_</var/lib/lxd>" pid=13279 comm="apparmor_parser"
[6090054.917618] BTRFS: could not find root 8
[6090054.923928] BTRFS: could not find root 8
[6090054.925368] BTRFS: could not find root 8
[6090054.934136] BTRFS: could not find root 8
[6090054.996186] BTRFS: could not find root 8
[6090060.364107] BTRFS: could not find root 8
[6090060.374237] BTRFS: could not find root 8
[6090060.395661] BTRFS: could not find root 8
[6090060.406032] BTRFS: could not find root 8
[6090060.406157] BTRFS: could not find root 8
[6098925.910980] BTRFS: could not find root 8
[6098925.917028] BTRFS: could not find root 8
[6098925.927183] BTRFS: could not find root 8
[6098925.938810] BTRFS: could not find root 8
[6098925.941103] BTRFS: could not find root 8
[6098931.267004] BTRFS: could not find root 8
[6098931.280246] BTRFS: could not find root 8
[6098931.284497] BTRFS: could not find root 8
[6098931.291051] BTRFS: could not find root 8
[6098931.298579] BTRFS: could not find root 8
[6098984.581595] BTRFS: could not find root 8
[6098984.589333] BTRFS: could not find root 8
[6098984.624966] BTRFS: could not find root 8
[6098984.631305] BTRFS: could not find root 8
[6098984.634047] BTRFS: could not find root 8
[6098999.049959] audit: type=1400 audit(1464836391.468:509): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-test456_</var/lib/lxd>" pid=21221 comm="apparmor_parser"
[6099000.236202] audit: type=1400 audit(1464836392.656:510): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-test456_</var/lib/lxd>" pid=21260 comm="apparmor_parser"
[6099247.643113] BTRFS: could not find root 8
[6099247.646130] BTRFS: could not find root 8
[6099247.650364] BTRFS: could not find root 8
[6099247.658960] BTRFS: could not find root 8
[6099247.705501] BTRFS: could not find root 8
[6099250.639126] audit: type=1400 audit(1464836642.984:511): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-test456_</var/lib/lxd>" pid=22536 comm="apparmor_parser"
[6099256.039594] audit: type=1400 audit(1464836648.384:512): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-test456_</var/lib/lxd>" pid=22592 comm="apparmor_parser"
[6099268.865178] audit: type=1400 audit(1464836661.204:513): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-test123_</var/lib/lxd>" pid=22678 comm="apparmor_parser"
[6099274.058607] audit: type=1400 audit(1464836666.396:514): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-test123_</var/lib/lxd>" pid=22723 comm="apparmor_parser"
[6099491.090856] BTRFS: could not find root 8
[6099491.104232] BTRFS: could not find root 8
[6099491.115881] BTRFS: could not find root 8
[6099491.119660] BTRFS: could not find root 8
[6099491.127575] BTRFS: could not find root 8
[6099515.805400] audit: type=1400 audit(1464836908.073:515): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-test123_</var/lib/lxd>" pid=23782 comm="apparmor_parser"
[6099522.296781] audit: type=1400 audit(1464836914.565:516): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-test123_</var/lib/lxd>" pid=23895 comm="apparmor_parser"
[6099842.042908] BTRFS: could not find root 8
[6099842.147431] BTRFS: could not find root 8
[6099842.152697] BTRFS: could not find root 8
[6099842.155525] BTRFS: could not find root 8
[6099842.182175] BTRFS: could not find root 8
[6101518.709856] BTRFS: could not find root 8
[6101518.720667] BTRFS: could not find root 8
[6101518.733387] BTRFS: could not find root 8
[6101518.739953] BTRFS: could not find root 8
[6101518.748757] BTRFS: could not find root 8
[6101987.761735] BTRFS: could not find root 8
[6101987.770450] BTRFS: could not find root 8
[6101987.786583] BTRFS: could not find root 8
[6101987.800053] BTRFS: could not find root 8
[6101987.819898] BTRFS: could not find root 8

This happens twice in the week for diffrent hosts. Please look into this isssue as we are facing this on our production boxes. 

Thanks.

**Comment by rchincholkar** [comment]
Hi Team,
Any update on this ?
This is happening every second week.
Please let us know if there is any fix on this.

Thanks,
Rahul C

**Comment by stgraber** [comment]
So there are a few potential issues with your setup:
 - LXC should be 2.0.3 not 2.0.1
 - LXD should be 2.0.3 not 2.0.2
 - As far as I know, the 3.16 kernel isn't supported anymore on 14.04, I'd strongly recommend you upgrade to linux-generic-lts-xenial which will get you a 4.4 kernel
