### ISSUE TITLE
Please rename lxc command to something lxd

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1963]
LXD is awesome but it's quite hard to search the internet for lxc example commands and helps because search engines are confused about ```lxc``` and ```lxc-*``` commands.

Also it's always confusing when one talks about lxc, whether it is about the LXC application or the lxc command.

**Comment by stgraber** [comment]
I certainly agree about some of the confusion around this but it's something our management felt strongly about and not something we can do anything about unfortunately.
