### ISSUE TITLE
Containers can't be started or stopped via REST API.

### ISSUE THREAD

**Issue by sezuan** [lxc/lxd#1965]
* Distribution: Ubuntu
 * Distribution version: Ubuntu 14.04.4 LTS
 * The output of "lxc info"

.

    apicompat: 0
    auth: trusted
    environment:
      addresses:
      - 127.0.0.1:8443
      architectures:
      - x86_64
      - i686
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIIFsjCCA5qgAwIBAgIRAOQiwOes71a+4eBfiuDfOpgwDQYJKoZIhvcNAQELBQAw
        NDEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEUMBIGA1UEAwwLcm9vdEBo
        b3N0NjMwHhcNMTYwMzA4MTEwMzE4WhcNMjYwMzA2MTEwMzE4WjA0MRwwGgYDVQQK
        ExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QGhvc3Q2MzCCAiIw
        DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAM0hVEhLnRQgsesVu8uvlLyNj3LM
        n3YtmNfJCe2lfp2ms7ah/WDvUILrx/plw1MosklrP/fEhsB2G3gu5W2eGu8PHeCK
        4q/1St2GZT5HFvN6CTOI+5N/42MAyacGki/UsTlPmL2pNAsEtO5D8bneDXnR6ITh
        EINaotx/p83OcuiaLWanN/a7S8ijbaJwUiGsH6dkqmaG8GXYUISOg6wEoJNfA5QG
        PPVyqArjy2v75E+ivneGbthzOgPyOI1pkF6Wp+jDugXEgwy3osy245LS+xsJUPXh
        OH2Fw3DgHzz0qaKi7SrGZvsHBJG1ukohHx6JHRI4H1KvsGQH0phON6xvNzfQ2Gej
        pgGoe32zz9Qes/SpsC7C6MzAV2iEXZMBdbgA/MPWaZ03zse+m+A+1190mroEVAvO
        /wiSa4Gqi08Zp4vvA7CIAy06Pto+CXKFotqjs2vT7yLOi8gnOHuixq3M8y3mvK/R
        zhwB0CMENjMN2x6S9SfzR8VEbOJsjgN2cOG+Ty7ORQMlwpHnc+SQZJXR7Lnb3YMd
        aFx1AFmjBodIPobqiVxVHUMEhXs+nxB4pZ8VU0Sz1fHa3SpkZfzonJ1iWe105b2w
        Wjhkq2CV7R+Wvmzh4Kq9b9kk2fMaVh6mikaAgxuys/vMmocZWVrLlAP5TV0Txa6Y
        cc99tQElAqsxuAcXAgMBAAGjgb4wgbswDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQM
        MAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwgYUGA1UdEQR+MHyCBmhvc3Q2M4IR
        MTM4LjIwMS4zMS4yMjMvMjaCFzJhMDE6NGY4OjE3MTozMzVlOjoyLzY0ghtmZTgw
        Ojo5MjFiOmVmZjpmZTkxOmM0ZjcvNjSCCzEwLjAuMy4xLzI0ghxmZTgwOjplY2Rh
        OmEyZmY6ZmU2YjphMTdlLzY0MA0GCSqGSIb3DQEBCwUAA4ICAQCTaLFBGJufnwbz
        A53elGoGV0DPNfUPCh5FqiS7N6p6F/DRn+2bEXIdNlFPLpOnoyGWYwutfUnU3Jij
        4q4q9gKKzTsGkCIBi2lSHBu9Vunw6L4VM8H+o5N6+3UkxVr090kUwzBdqILNlFx8
        N5iAsUfZLGP06kYWXKRXt6cUjjjy6a7vqSxPDOhNnANCrmHuzr707Ixp26zPn5I+
        247nxl2rqL+RgXP7kiHCuoq4quxCoVw/JFQJKiocp6iy10gPmR9kfyhFZ7LwEDVn
        hYo2msr7AI42D2/5HO7VRlwBdF+mDijBawlypLhwVGf0OU4MNgEaHR7Xt1G73zKH
        TiAJIo5MqcVzqvfvkKMPRcvU3hxgbJJUNn0Plt8kHjzHOHdNlX2skNXbsjaMoY+3
        +NSXdIARijvYVxje0lv3DGCGvazYSNFaGpOJKe1dvoaapuRIOAuD2XuP9wWVWhKY
        pVCNoYMuPbnXBxWBuUUP6W2YSlHz9eeim5RHLRGhV/SC/5EYIzGtykTcfebjMvLJ
        3ERWq8iwH2dnSw0T+fhoqTXuz1Qtss9WCytGJL/9/jCbC8JPmJZKqHrcFEb3ZB+D
        Z8If+4PNjIc6f4wd+pCCr4r8dyKiXupgfEky9SUhlgUqrwgVm2deDNmmsi7BvlsP
        gixqTsX8BbMfQn/NOpputjj0EWz/7A==
        -----END CERTIFICATE-----
      driver: lxc
      driverversion: 2.0.0
      kernel: Linux
      kernelarchitecture: x86_64
      kernelversion: 4.2.0-35-generic
      server: lxd
      serverpid: 1303
      serverversion: 2.0.0
      storage: btrfs
      storageversion: "4.4"
    config:
      core.https_address: 127.0.0.1:8443
      core.trust_password: true
    public: false

# Issue description

I can't start containers that I've created with the REST API. Maybe I'm doing it
wrong, but creation works as expected.

Create VM and check if it's running:

    $ lxc info teeeesting 
        Name: teeeesting
        Architecture: x86_64
        Created: 2016/04/28 15:34 UTC
        Status: Stopped
        Type: persistent
        Profiles: default

then

    $ /usr/bin/curl -s -k --cert /root/.config/lxc/client.crt --key /root/.config/lxc/client.key \
                    -XPUT -d '{"action": "start", "timeout": 30, "stateful": false}'\
                    https://localhost:8443/1.0/containers/teeeesting/state'
    
    {
      "operation": "/1.0/operations/1c62d264-47cb-4cd0-87f0-2caff645659c",
      "metadata": {
        "err": "",
        "may_cancel": false,
        "id": "1c62d264-47cb-4cd0-87f0-2caff645659c",
        "class": "task",
        "created_at": "2016-04-28T17:37:38.589023011+02:00",
        "updated_at": "2016-04-28T17:37:38.589023011+02:00",
        "status": "Running",
        "status_code": 103,
        "resources": {
          "containers": [
            "/1.0/containers/teeeesting"
          ]
        },
        "metadata": null
      },
      "status_code": 100,
      "status": "Operation created",
      "type": "async"
    }

and again:

    $ lxc info teeeesting 
        Name: teeeesting
        Architecture: x86_64
        Created: 2016/04/28 15:34 UTC
        Status: Stopped
        Type: persistent
        Profiles: default

and:

    /usr/bin/curl -s -k --cert /root/.config/lxc/client.crt --key /root/.config/lxc/client.key \
                  -XGET https://localhost:8443/1.0/operations/1c62d264-47cb-4cd0-87f0-2caff645659c
    {
      "type": "error",
      "error_code": 404,
      "error": "not found"
    }

# Steps to reproduce

 1. Create VM
 2. Start VM via API
 3. Verify result

# Information to attach

 - [ ] container log (lxc info NAME --show-log)

    lxc 20160428173834.034 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 100000 range 65536
    lxc 20160428173933.907 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 100000 range 65536
    lxc 20160428173933.907 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 100000 range 65536
    lxc 20160428173937.010 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 100000 range 65536
    lxc 20160428173937.010 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 100000 range 65536
    lxc 20160428173937.021 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 100000 range 65536
    lxc 20160428173937.021 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 100000 range 65536

**Comment by stgraber** [comment]
```
stgraber@dakara:~$ curl --unix-socket /var/lib/lxd/unix.socket -X PUT -d '{"action": "start", "timeout": 30, "stateful": false}' lxd/1.0/containers/snappy/state
{"type":"async","status":"Operation created","status_code":100,"metadata":{"id":"c65e4e9b-8e3b-4d3a-b47a-1d30962545e7","class":"task","created_at":"2016-04-28T11:49:53.393120687-04:00","updated_at":"2016-04-28T11:49:53.393120687-04:00","status":"Running","status_code":103,"resources":{"containers":["/1.0/containers/snappy"]},"metadata":null,"may_cancel":false,"err":""},"operation":"/1.0/operations/c65e4e9b-8e3b-4d3a-b47a-1d30962545e7"}

stgraber@dakara:~$ lxc list snappy
+--------+---------+-----------------------+----------------------------------------------+------------+-----------+
|  NAME  |  STATE  |         IPV4          |                     IPV6                     |    TYPE    | SNAPSHOTS |
+--------+---------+-----------------------+----------------------------------------------+------------+-----------+
| snappy | RUNNING | 10.178.150.233 (eth0) | 2001:470:b368:4242:216:3eff:fe92:156f (eth0) | PERSISTENT | 0         |
+--------+---------+-----------------------+----------------------------------------------+------------+-----------+
```

So works fine here, my guess is that there's something else wrong with your container and since you're not quick enough to pull the operation metadata (it expires after 5s), you're missing the actual error.

Try doing a normal "lxc start" to see what's wrong with your container.

**Comment by patademahesh** [comment]
operations log is only kept for 5 seconds.  Are you able to start your
container using lxc command ?

Mahesh

**Comment by sezuan** [comment]
It can be started with `lxc start`. When I fetch the operation metadata within 5s I get the following result:


Right after the VM start:

    {
      "metadata": {
        "err": "",
        "may_cancel": false,
        "id": "1ee39cad-f118-44e9-b05e-4551a7f00ce1",
        "class": "task",
        "created_at": "2016-04-29T09:44:16.228603919+02:00",
        "updated_at": "2016-04-29T09:44:16.228603919+02:00",
        "status": "Running",
        "status_code": 103,
        "resources": {
          "containers": [
            "/1.0/containers/teeeesting"
          ]
        },
        "metadata": null
      },
      "status_code": 200,
      "status": "Success",
      "type": "sync"
    }

And then:

    {
      "metadata": {
        "err": "Container has no existing state to restore.",
        "may_cancel": false,
        "id": "1ee39cad-f118-44e9-b05e-4551a7f00ce1",
        "class": "task",
        "created_at": "2016-04-29T09:44:16.228603919+02:00",
        "updated_at": "2016-04-29T09:44:16.228603919+02:00",
        "status": "Failure",
        "status_code": 400,
        "resources": {
          "containers": [
            "/1.0/containers/teeeesting"
          ]
        },
        "metadata": null
      },
      "status_code": 200,
      "status": "Success",
      "type": "sync"
    }

After setting  "stateful" to false it worked. **I thought I tried both...** Thanks for your help!
