### ISSUE TITLE
API : X-LXD-mode: 0700 : not working

### ISSUE THREAD

**Issue by tozaz** [lxc/lxd#1975]
Hi,

I would like to be able to set a correct file mode to an api pushed file, but can't get it working.

# Required information
 * Distribution: Ubuntu
 * Distribution version: 15.10
 * The output of "lxc info" or if that fails:
apicompat: 0
auth: trusted
environment:
  addresses:
  - 192.168.0.240:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIGFTCCA/2gAwIBAgIRANcAwrUd1PEbZbGNKfziMnIwDQYJKoZIhvcNAQELBQAw
    NjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEB0
    ZXN0aG9zdDAeFw0xNjA0MjkxODIwMTVaFw0yNjA0MjcxODIwMTVaMDYxHDAaBgNV
    BAoTE2xpbnV4Y29udGFpbmVycy5vcmcxFjAUBgNVBAMMDXJvb3RAdGVzdGhvc3Qw
    ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC0FaSdWd9oA51tHy/vYUsM
    XPlGUkNbaaAuGcAhigNeRhgj8ipepAFvNOC+1yPD9a7mJlUCoeou/+sBgUH75WPE
    W1Lz/tMSyeevzSszPxgYGGPX4RDOkvqV+Qgq8te56xuenCs0UJZSl1qiyVwfyJyO
    +q5p8vdb8L/3YQM8hSrWntWbRifxAKP10/+Nbq5lqQA/mtv6CLr230V6vH0HMZSN
    uIpDt1onBLJTqtYgywumcZNiWb+DVJxBnZW/hxlP1fJAGMjEDe1feCvN5pHeknpC
    aBR3rwg7lH58BxQBD44AU4jnt/7nlPnnqbk+/QTz9qHxl9xLJ4ttr9bdEt21quoZ
    fnGD9tjSo+eMomRDPAZpXyLSF7WiWzlwMXmyj2g7ZSq3NSQjGidBROWes7ESu9mr
    f02OOyIY+HVXLk/xNMINsGr0EXDEkeGu6WXdVzllgI7u8sWnsrjr4capvYwEFUpJ
    rSBfhaeJMkYUSgAgWCgOmNw7KKIqVhYoYuTcyjdEDgf/6EHdogxH6OcmDWx9sE4i
    jHKhxCGCSFrsBosGT/ZEIJwognFY5TDFIgQBqDJPEM6Rr+YDxIGhL5WJhOWafPTY
    hVS7jRrqcPnbfNFrZsYlinXIw1i2csY2NRE0C6vsuuXf146UTnTGQrSV75ugjgNS
    30VI2eziOWtEDdHX9rxHFQIDAQABo4IBHDCCARgwDgYDVR0PAQH/BAQDAgWgMBMG
    A1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwgeIGA1UdEQSB2jCB14II
    dGVzdGhvc3SCHGZlODA6OmJhOTc6NWFmZjpmZTBkOjU5ZDIvNjSCEDE5Mi4xNjgu
    MC4yNDAvMjSCKDJhMDE6ZTM1OjJmMzE6MWU3MDpjNTY3OjEzMzg6MTJiOjllNjEv
    NjSCKTJhMDE6ZTM1OjJmMzE6MWU3MDpiYTk3OjVhZmY6ZmUwZDo1OWQyLzY0ghxm
    ZTgwOjpiYTk3OjVhZmY6ZmUwZDo1OWQyLzY0ghxmZTgwOjozMGQ5OjhhZmY6ZmU2
    Njo3NDViLzY0ggpmZTgwOjoxLzY0MA0GCSqGSIb3DQEBCwUAA4ICAQAZ+hzAexjH
    dfXLdS7DDME4qjy9hs2PkYxTNI1phbU5UTBA08RzrQjKfplnmmkiW+3kYLy5UDGo
    bGO/ZdpxMugZf73Cltpry7Hjxgazogfz714xtSDKnp0Yf3wlIvytjHTfVXZIUWyw
    6L1HirWyikVRb9IJRtOI/9HaSjrASfrZCy8PGyAhyxNgaIb7CZD7ecF/HoEmRJFb
    iKOYbha05RUroia9ko/LvU9a6mALUmACNo5gQyvi81Rd6yLK/FLEQJKCYUzd9pL3
    YDZehiEdWj+Oi+GS2wjXJqgSaTwj73qo54dTz4YApQxisM0wKAHQRhYOvzohTZ2f
    6AM2DUO4ylUbl+CWgBGoZXztj9ehGNNfblKHVo2I+/X/8mkUNzjSGEN0MRuR6BHZ
    WR4SAYHLxdjwab/TTKETSndvtSvN9ede/AA1uwFgHcp32aUGiJOqKAQK6e+t2wRF
    6SjyDM2LlK9SbRnYv+IlAqQaUg4UDsADUjZligRLZWJGrE+QsaknaiItkhh7du3Z
    yrTHCnY5pbbXsBvt8jM6FZZgO8gnBKmG8z252H0DIwj15JLQiFkCvKQxs2eg5gjl
    NS40AUvPa0PgwZ0sl29gNFmDDpmKcvb0DE2Cs6ceZxlYu/S3fJRc5wW/JWrYo9BM
    opDPZ+tzWnwR6at7wsGNUWXPakhVs87Y9w==
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 1366
  serverversion: 2.0.0
  storage: zfs
  storageversion: "5"
config:
  core.https_address: 192.168.0.240:8443
  core.trust_password: true
  storage.zfs_pool_name: zfspool
public: false
   * Storage backend in use: ZFS

# Issue description

When I push a file via the API, X-LXD-mode: is not working.

# Steps to reproduce

 1. Step one

`curl -k --cert client.pem --key client.key -H "X-LXD-uid: 0" -H "X-LXD-gid: 0" -H "X-LXD-mode: 0700" -H "Content-Type: application/octet-stream" -X POST --data-binary '@test' https://mylxdhost:8443/1.0/containers/ubuntu-vm/files?path=/etc/resolv.conf`
 2. Step two
 
`ls -la /etc/resolv.conf

-rw-r--r-- 1 root root 0 Apr 29 21:40 /etc/resolv.conf`

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
Hmm, we had a problem like that until rc9 but you seem to be running final...

**Comment by tozaz** [comment]
Did you manage to reproduce the issue ? Will it be fixed in the next release ?
Thanks

**Comment by stgraber** [comment]
```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ curl --unix-socket /var/lib/lxd/unix.socket -H "X-LXD-uid: 0" -H "X-LXD-gid: 0" -H "X-LXD-mode: 0700" -H "Content-Type: application/octet-stream" -X POST --data-binary '@data' lxd/1.0/containers/test/files?path=/tmp/a
{"type":"sync","status":"Success","status_code":200,"metadata":{}}

stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc exec test -- ls -lh /tmp/a
-rwx------ 1 root root 4 May  1 14:33 /tmp/a
```

I think the source of your problem is that LXD doesn't change file ownership or permissions on existing files. Those fields are only used for new files.

**Comment by stgraber** [comment]
I'll send a commit to clarify the documentation in that regard.

**Comment by stgraber** [comment]
Actually, looks like we can do what you want without breaking the API, taking a stab at that.
