### ISSUE TITLE
Custom capabilities in LXD

### ISSUE THREAD

**Issue by kirgene** [lxc/lxd#1982]
Hello,

How can I define custom capabilities in LXD container?

**Comment by stgraber** [comment]
We don't offer an official direct way to configure those as we try to keep our API implementation agnostic and capabilities are very much Linux specific. 

Also as we default to unprivileged containers, those aren't so relevant. 

You can still mess with them through raw. lxc though. 

lxc config set container-name raw.lxc=lxc.cap.drop=some-cap

**Comment by CarltonSemple** [comment]
@stgraber is it possible to do this for multiple lxc rules?
i.e. 
`lxc config set container-name raw.lxc=lxc.cap.keep=some-cap raw.lxc=lxc.cap.keep=some-cap2`

**Comment by stgraber** [comment]
```
(
cat << EOF
lxc.cap.keep=some-cap
lxc.cap.keep=some-cap2
EOF
) | lxc config set container-name raw.lxc -
```

**Comment by CarltonSemple** [comment]
awesome, thanks

**Comment by pkrnjevic** [comment]
@stgraber this seems to no longer work in Ubuntu 18.04.
