### ISSUE TITLE
Ability to "pre-migrate" and/or replicate a container

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1987]
I'm not sure, "pre-migrate" is the right word.
It would be great to be able to 
1. Create container replicas.
   In case of LXC it's easy, just zfs snap & transfer container to a remote machine and that's it.
   With LXD it's different, because uid is not fixed and container configurations are not stored with the container.
   NB: this way it's easy to create clones of online containers too.
2. Create a preliminary container (dataset) migration.
   In case of LXC it's easy because either via rsync or zfs send data could be transferred to a remote machine. When it's done even after a long time container can be stopped, transfer deltas and finish migration easily.

**Comment by stgraber** [comment]
lxc snapshot source:container1 pre-migrate
lxc copy container1/pre-migrate target:container2

Doesn't that do what you want?

**Comment by tomposmiko** [comment]
Serge,

Sorry, somehow I missed emails from github.
No, I don't think that's what I want or I don't get the point.

This is the workflow I usually follow:

1. replicated containers (poor men's HA)
Container is time to time zfs replicated to/from a remote machine.
If the source is off for any reason, the container on destination can be easily started.

2. replicated containers (dev instances)
Container is time to time zfs replicated to/from a remote machine.
On the remote machine container is started, used as an exact copy of the production environment. Development changes can be implemented, tests are running fine on production data. On next time of replication changes are dropped on the development instance and delta is copied from the production one.

3. preliminary container migration
Container is zfs replicated to/from a remote machine. The original system is still running, the target not yet.
When it's done the the replication process can be repeated number of times and if it's needed for some reason the last step can be done much later (basically the same as ##1).

4. Backup (bonus)
Container get's snapshotted and replicated via a backup tool (script).
It's must be restorable, there is a database of container settings, not just the dataset itself.


AFAIK a copy of a container is independent of the source, it's not like zfs snapshots and send/recv.
In case of zfs if there a common snapshot, the replication 'stream' works.
Let me know, if I'm not clear.

**Comment by tomposmiko** [comment]
@stgraber if the above makes sense, please reopen.

**Comment by tomposmiko** [comment]
@stgraber 

Thanks so much, much appreciated!

**Comment by tomposmiko** [comment]
@stgraber 
Do you want me to separate this to smaller issues?
Specifically ##4 looks a bit different.

**Comment by stgraber** [comment]
We can keep it in one place for now and we'll split it once someone has time to work on it.

**Comment by stgraber** [comment]
So looking through this issue, I think we actually have all that these days through support for `--refresh` on `lxc copy`.

So a container can be copied from a system to another, then changes further changes to the source can be copied without requiring a full copy. This effectively resets the destination to once again match the source.

We also have the backup API which allows for downloading tarballs of containers (including ZFS optimized blobs) and storing/restoring them which should fit the needs of the last point.
