### ISSUE TITLE
Containers not started automatically

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1989]
ii  lxd                                                   2.0.0-0ubuntu4~ubuntu14.04.1~pp amd64                           
ii  lxc                                                   2.0.0-0ubuntu2~ubuntu14.04.1~pp all                   

Uptodate Ubuntu 14.04.

Containers are running, machine gets stopped/started and containers are not running after the start.
Storage backend:

  storage.zfs_pool_name: tank/lxd

**Comment by stgraber** [comment]
Please include the information we request in the bug report form.

**Comment by tomposmiko** [comment]
* Distribution: Ubuntu
 * Distribution version: 14.04 LTS
 * The output of "lxc info" or if that fails: 
```
apicompat: 0
auth: trusted
environment:
  addresses:
  - '[127.0.0.1]:8443'
  architectures:
  - x86_64
  - i686
  certificate: [...]
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 2313
  serverversion: 2.0.0
  storage: zfs
  storageversion: "5"
config:
  core.https_address: '[127.0.0.1]'
  core.trust_password: true
  storage.zfs_pool_name: tank/lxd
public: false
```
   * Kernel version: 4.2.0-35-generic
   * LXD version: 2.0.0-0ubuntu4~ubuntu14.04.1~pp
   * LXC version: 2.0.0-0ubuntu2~ubuntu14.04.1~pp
   * Storage backend in use: zfs

# Issue description

Containers does not start automatically, however they are started before reboot.

# Steps to reproduce

# create and start container
$ lxc launch images:ubuntu/xenial/amd64 foo
$ reboot
$ lxc info miko|grep Status

# Information to attach
 - [ ] any relevant kernel output (dmesg)

I see no relevant message.

 - [ ] container log (lxc info NAME --show-log)



            lxc 20160505092757.524 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 110000 range 65536
            lxc 20160505092757.524 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 110000 range 65536
            lxc 20160505093235.857 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 110000 range 65536
            lxc 20160505093235.857 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 110000 range 65536
            lxc 20160505093235.922 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 110000 range 65536
            lxc 20160505093235.922 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 110000 range 65536
            lxc 20160505093819.788 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 110000 range 65536
            lxc 20160505093819.788 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 110000 range 65536
            lxc 20160505110852.598 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 110000 range 65536
            lxc 20160505110852.598 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 110000 range 65536
            lxc 20160505110915.498 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 110000 range 65536
            lxc 20160505110915.498 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 110000 range 65536
```


 - [ ] main daemon log (/var/log/lxd.log)
```
t=2016-05-04T14:10:22+0200 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
t=2016-05-04T14:10:22+0200 lvl=info msg="Default uid/gid map:"
t=2016-05-04T14:10:22+0200 lvl=info msg=" - u 0 110000 65536"
t=2016-05-04T14:10:22+0200 lvl=info msg=" - g 0 110000 65536"
t=2016-05-04T14:10:22+0200 lvl=info msg=Init driver=storage/zfs
t=2016-05-04T14:10:22+0200 lvl=info msg="Looking for existing certificates" cert=/var/lib/lxd/server.crt key=/var/lib/lxd/server.key
t=2016-05-04T14:10:22+0200 lvl=info msg="LXD is socket activated"
t=2016-05-04T14:10:22+0200 lvl=info msg="REST API daemon:"
t=2016-05-04T14:10:22+0200 lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket
t=2016-05-04T14:10:22+0200 lvl=info msg=" - binding TCP socket" socket=[::]:20004
t=2016-05-04T14:10:22+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T14:10:22+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T14:10:22+0200 lvl=info msg=handling method=GET url=/internal/ready ip=@
t=2016-05-04T14:18:53+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T14:18:53+0200 lvl=info msg=handling method=GET url="/1.0/containers?recursion=1" ip=@
t=2016-05-04T14:18:57+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T14:18:57+0200 lvl=info msg=handling method=GET url="/1.0/images?recursion=1" ip=@
t=2016-05-04T14:19:13+0200 lvl=info msg=handling ip=@ method=GET url=/1.0
t=2016-05-04T14:19:14+0200 lvl=info msg=handling ip=@ method=GET url=/1.0
t=2016-05-04T14:19:18+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T14:19:18+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T14:19:26+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T14:19:26+0200 lvl=info msg=handling ip=@ method=GET url=/1.0
t=2016-05-04T14:19:27+0200 lvl=info msg=handling method=POST url=/1.0/containers ip=@
t=2016-05-04T14:19:27+0200 lvl=info msg=handling url="/1.0/events?type=operation" ip=@ method=GET
t=2016-05-04T14:19:27+0200 lvl=info msg=handling method=GET url=/1.0/operations/381359f0-a0da-4cf6-bb7a-17ed43aa6f5e/wait ip=@
t=2016-05-04T14:19:28+0200 lvl=info msg="Image not in the db, downloading it" image=aa8b21991cd6b3196b37a382d1b0fc2ee42b3cfea501cf405162d182eccce368 server=https://images.linuxcontainers.org:8443
t=2016-05-04T14:19:28+0200 lvl=info msg="Downloading the image" image=aa8b21991cd6b3196b37a382d1b0fc2ee42b3cfea501cf405162d182eccce368
t=2016-05-04T14:20:19+0200 lvl=info msg="Download succeeded" image=aa8b21991cd6b3196b37a382d1b0fc2ee42b3cfea501cf405162d182eccce368
t=2016-05-04T14:20:21+0200 lvl=info msg=handling method=PUT url=/1.0/containers/miko/state ip=@
t=2016-05-04T14:20:21+0200 lvl=info msg=handling ip=@ method=GET url=/1.0/operations/7c2fbf3c-b768-4dea-b3a1-a44843bba9d9/wait
t=2016-05-04T14:20:21+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T14:20:21+0200 lvl=info msg=handling url=/internal/containers/11/onstart ip=@ method=GET
t=2016-05-04T14:22:51+0200 lvl=info msg=handling url=/1.0 ip=@ method=GET
t=2016-05-04T14:22:51+0200 lvl=info msg=handling ip=@ method=POST url=/1.0/containers/miko/exec
t=2016-05-04T14:22:51+0200 lvl=info msg=handling method=GET url="/1.0/operations/496b43cd-c503-4841-9ea3-2e4cee4ec5fa/websocket?secret=40ff70a1aca973547aee0c9eef93ce12425c561d77378867d25ebea2a627ed47" ip=@
t=2016-05-04T14:22:51+0200 lvl=info msg=handling method=GET url="/1.0/operations/496b43cd-c503-4841-9ea3-2e4cee4ec5fa/websocket?secret=495b1a90487207c62fa88e5cfdcbff53cfaf189999ad2a18e572812a042dd9ee" ip=@
t=2016-05-04T15:23:23+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T15:23:23+0200 lvl=info msg=handling method=GET url=/1.0/profiles/miko ip=@
t=2016-05-04T15:23:27+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T15:23:27+0200 lvl=info msg=handling method=GET url="/1.0/containers?recursion=1" ip=@
t=2016-05-04T15:23:27+0200 lvl=info msg=handling method=GET url="/1.0/containers/miko/snapshots?recursion=1" ip=@
t=2016-05-04T15:23:27+0200 lvl=info msg=handling method=GET url=/1.0/containers/miko/state ip=@
t=2016-05-04T15:24:15+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T15:24:15+0200 lvl=info msg=handling method=GET url=/1.0/containers/miko ip=@
t=2016-05-04T15:25:29+0200 lvl=info msg=handling method=PUT url=/1.0/containers/miko ip=@
t=2016-05-04T15:25:29+0200 lvl=info msg=handling ip=@ method=GET url=/1.0/operations/269c9f36-26b6-4656-b6d8-245078b35cd7/wait
t=2016-05-04T15:25:32+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T15:25:32+0200 lvl=info msg=handling method=GET url=/1.0/containers/miko ip=@
t=2016-05-04T15:25:32+0200 lvl=info msg=handling url=/1.0/containers/miko/state ip=@ method=PUT
t=2016-05-04T15:25:32+0200 lvl=info msg=handling method=GET url=/1.0/operations/973fccc3-ba15-4789-ba66-71140951570a/wait ip=@
t=2016-05-04T15:25:34+0200 lvl=info msg=handling method=GET url=/1.0/operations/496b43cd-c503-4841-9ea3-2e4cee4ec5fa/wait ip=@
t=2016-05-04T15:25:35+0200 lvl=info msg=handling url=/1.0 ip=@ method=GET
t=2016-05-04T15:25:35+0200 lvl=info msg=handling method=GET url="/internal/containers/11/onstop?target=stop" ip=@
t=2016-05-04T15:25:35+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T15:25:35+0200 lvl=info msg=handling method=GET url=/1.0/containers/miko ip=@
t=2016-05-04T15:25:35+0200 lvl=info msg=handling method=PUT url=/1.0/containers/miko/state ip=@
t=2016-05-04T15:25:35+0200 lvl=info msg=handling url=/1.0/operations/5405c991-0231-465b-9926-9ddd49faa0b0/wait ip=@ method=GET
t=2016-05-04T15:25:35+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T15:25:35+0200 lvl=info msg=handling ip=@ method=GET url=/internal/containers/11/onstart
t=2016-05-04T15:25:58+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T15:25:58+0200 lvl=info msg=handling method=POST url=/1.0/containers/miko/exec ip=@
t=2016-05-04T15:25:58+0200 lvl=info msg=handling method=GET url="/1.0/operations/575886f7-81a1-4399-8954-862dda6e39bc/websocket?secret=4e7d3000ada65df4ee95ef2c126317e14209000023c811084d24bf1b9ec2e1e9" ip=@
t=2016-05-04T15:25:58+0200 lvl=info msg=handling method=GET url="/1.0/operations/575886f7-81a1-4399-8954-862dda6e39bc/websocket?secret=7ab099aa277c12101d0dcc7f46322a4ddca272f60cc24ab17e52c935ecff44ed" ip=@
t=2016-05-04T15:37:43+0200 lvl=info msg=handling url=/1.0/operations/575886f7-81a1-4399-8954-862dda6e39bc/wait ip=@ method=GET
t=2016-05-04T15:41:46+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T15:41:46+0200 lvl=info msg=handling method=POST url=/1.0/containers/miko/exec ip=@
t=2016-05-04T15:41:46+0200 lvl=info msg=handling method=GET url="/1.0/operations/c8911301-a897-4f6c-88dd-8df3e483b560/websocket?secret=f2be6fa0fdacd1086de8c6cc884ceea1b7190cd746d68a09f5287c86dee61c72" ip=@
t=2016-05-04T15:41:46+0200 lvl=info msg=handling method=GET url="/1.0/operations/c8911301-a897-4f6c-88dd-8df3e483b560/websocket?secret=d377bd9f07a2990e8d85ec9f6c3ee26712e1c64c7ebbad1a10a3a7b03babc90f" ip=@
t=2016-05-04T15:43:13+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T15:43:13+0200 lvl=info msg=handling method=POST url=/1.0/containers/miko/exec ip=@
t=2016-05-04T15:43:13+0200 lvl=info msg=handling method=GET url="/1.0/operations/832cd8e7-a8c6-4934-ab67-2967243dd816/websocket?secret=f50d4ac5402bf1e1a6250a08d6f4c79fd36a79814eafd9e6105dfc03ee7f3787" ip=@
t=2016-05-04T15:43:13+0200 lvl=info msg=handling method=GET url="/1.0/operations/832cd8e7-a8c6-4934-ab67-2967243dd816/websocket?secret=e9bdb9b90a817e19338eb02794fe1bccca1b0909cb7b54e7dbc15e86765f4d94" ip=@
t=2016-05-04T15:43:34+0200 lvl=info msg=handling ip=@ method=GET url=/1.0
t=2016-05-04T15:43:34+0200 lvl=info msg=handling method=POST url=/1.0/containers/miko/exec ip=@
t=2016-05-04T15:43:34+0200 lvl=info msg=handling method=GET url="/1.0/operations/28f866a1-9816-4600-a90c-73289af9cb85/websocket?secret=79d9ff8516684cd612f4f896e38200fc163ce3972ab914832dbca52dc204f38a" ip=@
t=2016-05-04T15:43:34+0200 lvl=info msg=handling ip=@ method=GET url="/1.0/operations/28f866a1-9816-4600-a90c-73289af9cb85/websocket?secret=c3e4bba5b9031a7c438edebae90ecb4557067d171f54cc873bfd348a5b2cd7fd"
t=2016-05-04T15:50:49+0200 lvl=info msg=handling method=GET url=/1.0/operations/28f866a1-9816-4600-a90c-73289af9cb85/wait ip=@
t=2016-05-04T15:50:52+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-04T15:50:52+0200 lvl=info msg=handling url=/1.0/containers/miko ip=@ method=GET
t=2016-05-04T15:50:52+0200 lvl=info msg=handling method=GET url=/1.0/containers/miko/state ip=@
t=2016-05-04T15:50:52+0200 lvl=info msg=handling url="/1.0/containers/miko/snapshots?recursion=1" ip=@ method=GET
t=2016-05-05T09:27:57+0200 lvl=info msg="LXD is starting in normal mode" path=/var/lib/lxd
t=2016-05-05T09:27:57+0200 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
t=2016-05-05T09:27:57+0200 lvl=info msg="Default uid/gid map:"
t=2016-05-05T09:27:57+0200 lvl=info msg=" - u 0 110000 65536"
t=2016-05-05T09:27:57+0200 lvl=info msg=" - g 0 110000 65536"
t=2016-05-05T09:27:57+0200 lvl=info msg=Init driver=storage/zfs
t=2016-05-05T09:27:57+0200 lvl=info msg="Looking for existing certificates" cert=/var/lib/lxd/server.crt key=/var/lib/lxd/server.key
t=2016-05-05T09:27:57+0200 lvl=info msg="LXD is socket activated"
t=2016-05-05T09:27:57+0200 lvl=info msg="REST API daemon:"
t=2016-05-05T09:27:57+0200 lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket
t=2016-05-05T09:27:57+0200 lvl=info msg=" - binding TCP socket" socket=[::]:20004
t=2016-05-05T09:27:57+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-05T09:27:57+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-05T09:27:57+0200 lvl=info msg=handling ip=@ method=GET url=/internal/ready
t=2016-05-05T09:27:58+0200 lvl=info msg="Image not in the db, downloading it" image=640b2b732a80b8eebba3dcb030b08a81b72c0d6ab70673258cacfa05d9bc3f92 server=https://images.linuxcontainers.org:8443
t=2016-05-05T09:27:58+0200 lvl=info msg="Downloading the image" image=640b2b732a80b8eebba3dcb030b08a81b72c0d6ab70673258cacfa05d9bc3f92
t=2016-05-05T09:28:27+0200 lvl=info msg="Download succeeded" image=640b2b732a80b8eebba3dcb030b08a81b72c0d6ab70673258cacfa05d9bc3f92
t=2016-05-05T09:32:35+0200 lvl=info msg=handling ip=@ method=GET url=/1.0
t=2016-05-05T09:32:35+0200 lvl=info msg=handling ip=@ method=PUT url=/internal/shutdown
t=2016-05-05T09:32:35+0200 lvl=info msg="Asked to shutdown by API, shutting down containers."
t=2016-05-05T09:32:35+0200 lvl=info msg=handling method=GET url=/1.0/events ip=@
t=2016-05-05T09:32:35+0200 lvl=info msg="Stopping REST API handler:"
t=2016-05-05T09:32:35+0200 lvl=info msg=" - closing socket" socket=[::]:20004
t=2016-05-05T09:32:35+0200 lvl=info msg=" - skipping socket-activated socket" socket=/var/lib/lxd/unix.socket
t=2016-05-05T09:38:19+0200 lvl=info msg="LXD is starting in normal mode" path=/var/lib/lxd
t=2016-05-05T09:38:19+0200 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
t=2016-05-05T09:38:19+0200 lvl=info msg="Default uid/gid map:"
t=2016-05-05T09:38:19+0200 lvl=info msg=" - u 0 110000 65536"
t=2016-05-05T09:38:19+0200 lvl=info msg=" - g 0 110000 65536"
t=2016-05-05T09:38:19+0200 lvl=info msg=Init driver=storage/zfs
t=2016-05-05T09:38:19+0200 lvl=info msg="Looking for existing certificates" cert=/var/lib/lxd/server.crt key=/var/lib/lxd/server.key
t=2016-05-05T09:38:19+0200 lvl=info msg="LXD is socket activated"
t=2016-05-05T09:38:19+0200 lvl=info msg="REST API daemon:"
t=2016-05-05T09:38:19+0200 lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket
t=2016-05-05T09:38:19+0200 lvl=info msg=" - binding TCP socket" socket=[::]:20004
t=2016-05-05T09:38:19+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-05T09:38:19+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-05T09:38:19+0200 lvl=info msg=handling method=GET url=/internal/ready ip=@
t=2016-05-05T11:08:52+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-05T11:08:52+0200 lvl=info msg=handling method=GET url="/1.0/containers?recursion=1" ip=@
t=2016-05-05T11:08:52+0200 lvl=info msg=handling method=GET url="/1.0/containers/miko/snapshots?recursion=1" ip=@
t=2016-05-05T11:09:10+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-05T11:09:10+0200 lvl=info msg=handling url=/1.0 ip=@ method=GET
t=2016-05-05T11:09:11+0200 lvl=info msg=handling method=POST url=/1.0/containers ip=@
t=2016-05-05T11:09:11+0200 lvl=info msg=handling url="/1.0/events?type=operation" ip=@ method=GET
t=2016-05-05T11:09:11+0200 lvl=info msg=handling url=/1.0/operations/a96fab23-2b96-4aa3-8234-624d2a6b34e9/wait ip=@ method=GET
t=2016-05-05T11:09:15+0200 lvl=info msg=handling method=PUT url=/1.0/containers/chemicalize-dev/state ip=@
t=2016-05-05T11:09:15+0200 lvl=info msg=handling url=/1.0/operations/b5ee1f1f-953e-477a-8f4f-44d4e8e91b30/wait ip=@ method=GET
t=2016-05-05T11:09:15+0200 lvl=info msg=handling url=/1.0 ip=@ method=GET
t=2016-05-05T11:09:15+0200 lvl=info msg=handling method=GET url=/internal/containers/12/onstart ip=@
t=2016-05-05T11:12:44+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-05-05T11:12:44+0200 lvl=info msg=handling method=GET url=/1.0/containers/miko ip=@
t=2016-05-05T11:12:44+0200 lvl=info msg=handling ip=@ method=GET url=/1.0/containers/miko/state
t=2016-05-05T11:12:44+0200 lvl=info msg=handling method=GET url="/1.0/containers/miko/snapshots?recursion=1" ip=@
t=2016-05-05T11:12:44+0200 lvl=info msg=handling method=GET url=/1.0/containers/miko/logs/lxc.log ip=@
```

 - [ ] output of the client with --debug
N/A

 - [ ] output of the daemon with --debug
N/A

**Comment by stgraber** [comment]
```
root@trusty:~# lxc launch images:ubuntu/xenial/amd64 foo
Generating a client certificate. This may take a minute...
If this is your first time using LXD, you should also run: sudo lxd init

Creating foo
Retrieving image: 100%
Starting foo

root@trusty:~# lxc info foo|grep Status
Status: Running

root@trusty:~# reboot
Broadcast message from root@trusty
	(/dev/pts/0) at 17:21 ...

The system is going down for reboot NOW!
Connection to 208.113.131.156 closed.

stgraber@castiana:~$ ssh root@208.113.131.156
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Thu May  5 17:22:14 UTC 2016

  System load: 0.0               Memory usage: 9%   Processes:       55
  Usage of /:  1.9% of 78.71GB   Swap usage:   0%   Users logged in: 0

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud


Last login: Thu May  5 17:15:26 2016 from 12.39.178.125

root@trusty:~# lxc info foo|grep Status
Status: Running
```

**Comment by stgraber** [comment]
Do you have some kind of reliable reproducer for this as I couldn't reproduce it myself on a clean system?
