### ISSUE TITLE
Automatically promote ZFS dataset after clone

### ISSUE THREAD

**Issue by sts** [lxc/lxd#1991]
I would like to request a configuration option for LXD, which runs ```zfs promote``` after a container dataset was successfully created, so the created dataset doesn't depend on the origin, the image, anymore.

**Comment by stgraber** [comment]
We can't do that. "zfs promote" doesn't untie the clone from its source, it just reverses the relation.

So if we were to do that, the image would now depend on the container, making things an even bigger mess.
