### ISSUE TITLE
LXD doesn't respect dnsmasq config for alpine images

### ISSUE THREAD

**Issue by Lisio** [lxc/lxd#1995]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-21-generic
   * LXC version: 2.0.0-0ubuntu2
   * LXD version: 2.0.0-0ubuntu4
   * Storage backend in use: zfs

# Issue description

I have a following line in dnsmasq config file:
```
dhcp-host=memcached,10.100.0.99
```
If I create container from ubuntu image it receives IP 10.100.0.99:
```
root@server:/etc# lxc launch images:ubuntu/xenial/amd64 memcached
Creating memcached
Starting memcached
root@server:/etc# lxc list | grep memcached
| memcached | RUNNING | 10.100.0.99 (eth0) |      | PERSISTENT | 0         |
```

But if I create if from alpine image, LXD ignores IP settings:
```
root@server:/etc# lxc launch images:alpine/3.3/amd64 memcached
Creating memcached
Starting memcached
root@server:/etc# lxc list | grep memcached
| memcached | RUNNING | 10.100.0.182 (eth0) |      | PERSISTENT | 0         |
```

**Comment by stgraber** [comment]
That's an alpine problem, not a LXD one.

The dnsmasq config entry you set can only be applied if the container sends its hostname to the DHCP server. That's the case for Ubuntu (which uses isc-dhcp) but that's not the case for alpine (which uses udhcpc).
