### ISSUE TITLE
DCO verifier script

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#1997]
Google implemented nice GitHub integration for its CLA - https://github.com/google/support-tools/pull/186

The code seems to be here - https://github.com/angular/google-cla-verifier-for-github/blob/master/cla-verifier.gs

So, where is the code for Jenkins job that does the same? It may be improved do provide the check similarly.

**Comment by stgraber** [comment]
Our DCO validation script is very simple as we only need to validate the Signed-off-by and nothing else, no versioning, no persistent state, ...

http://paste.ubuntu.com/16241968/ is what we're running right now

We have no intention to switch to something else as this one works great and never gave us a false positive or false negative.

**Comment by techtonik** [comment]
Well, except that it generates invalid links that lead to 404 pages, such as https://jenkins.linuxcontainers.org/job/lxd-github-pull-dco/757/

Why these scripts are not version controlled?

**Comment by stgraber** [comment]
We don't keep the whole Jenkins history for disk consumption reason, changing the script wouldn't change that. As I said, we never had a false positive or negative, so in practice we never go look at the jenkins job.

**Comment by techtonik** [comment]
Still it is not clear how the script is triggered. If it was in repository, I'd try to patch it to produce checkmark like Google's.
