### ISSUE TITLE
How to mount a network resource inside a container and allow rw on the resource?

### ISSUE THREAD

**Issue by typhoe** [lxc/lxd#2005]
Hi,

assuming the container is on the same lan (bridged network), is there a way to mount a network resource (nfs or cifs) directly from inside the container?

Here is that I would like to do:

`lxc create ubuntu:xenial c1`
`lxc exec c1 bash`
`mount -o username=SAMBAUSER,password=SAMBAPASSWD,iocharset=utf8,file_mode=0777,dir_mode=0777 -t cifs //nas/share /mnt`

And be able to read and write to /mnt from inside the container.

I tried to mount the network resource from the host and then issue a bind mount without success.
`lxc config device add c1 MyShare disk source=/mnt path=/mnt`

Thank you!

**Comment by tych0** [comment]
On Sun, May 08, 2016 at 01:57:26PM -0700, typhoe wrote:
> Hi,
> 
> assuming the container is on the same lan (bridged network), is there a way to mount a network resource (nfs or cifs) directly from inside the container?
> 
> Here is that I would like to do:
> 
> `lxc create ubuntu:xenial c1`
> `lxc exec c1 bash`
> `mount -o username=SAMBAUSER,password=SAMBAPASSWD,iocharset=utf8,file_mode=0777,dir_mode=0777 -t cifs //nas/share /mnt`
> 
> And be able to read and write to /mnt from inside the container.
> 
> I tried to mount the network resource from the host and then issue a bind mount without success.
> `lxc config device add c1 MyShare disk source=/mnt path=/mnt`

This looks reasonable, can you elaborate about what "without success"
means?

**Comment by stgraber** [comment]
A straight mount inside the container isn't going to work due to nfs and cifs not being mountable by unprivileged users, but mounting on the host and bind-mounting into the container should work.

Though you will most likely have to pass uid= and gid= to your host side mount too to set owner uid and gid which make sense in the container.

**Comment by typhoe** [comment]
Sorry I took so much time to follow up my first post. And thank you for your answers.

In the following, lxc is my host (ubuntu xenial 64 bits, up to date on the 13th of mai 2016) and c1 is the container.
The network resource I use is a cifs share from a Synology NAS.
Here are the tests I made:

## Check CIFS mount from host (uid 1056 is my samba user on my nas)
root@lxc:~# 
`mount -o username=***,password=***,iocharset=utf8,file_mode=0777,dir_mode=0777 -t cifs //nas/downloads /mnt`
`ls -lh /mnt`
total 0
drwxrwsrwx 2 root users 0 mai    8 13:27 test
`echo "foo" > /mnt/test/foo.file`
`ls -lh /mnt/test/foo.file`
-rw-r--r-- 1 1056 users 4 mai   11 15:04 /mnt/test/foo.file
#=> So, network cifs share seems to work perfectly from the host
`umount /mnt`

## Check mounting network resource without any special configuration
root@lxc:~# 
`lxc init ubuntu:xenial c1`
Creating c1
`lxc start c1`
`lxc exec c1 bash`
root@c1:~# 
`apt-get -y install cifs-utils`
<...........>
The following NEW packages will be installed:
  cifs-utils keyutils libavahi-client3 libavahi-common-data libavahi-common3 libcups2 libldb1 libpython-stdlib libpython2.7 libpython2.7-minimal libpython2.7-stdlib libtalloc2  libtdb1 libtevent0 libwbclient0 python python-crypto python-ldb python-minimal python-samba python-talloc python-tdb python2.7 python2.7-minimal samba-common samba-common-bin  samba-libs
<...........>
`mount -o username=***,password=***,iocharset=utf8,file_mode=0777,dir_mode=0777 -t cifs //nas/downloads /mnt`
#=>
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
root@lxc:~# 
`tail -f /var/log/syslog`
May 13 16:27:17 lxc kernel: [442532.401588] audit: type=1400 audit(1463149637.775:62): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxd-c1_</var/lib/lxd>" name="/mnt/" pid=13085 comm="mount.cifs" fstype="cifs" srcname="//nas/downloads"

## Check mounting network resource with apparmor unconfined
root@lxc:~# 
`lxc stop c1`
`lxc delete c1`
`lxc init ubuntu:xenial c1`
`lxc config set c1 raw.lxc lxc.aa_profile=unconfined`
`lxc start c1`
`lxc exec c1 bash`
root@c1:~# 
`apt-get -y install cifs-utils`
`mount -v -o username=***,password=***,iocharset=utf8,file_mode=0777,dir_mode=0777 -t cifs //nas/downloads /mnt`
#=>
mount error(1): Operation not permitted
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
#=>Nothing in various logs... /var/log/syslog /var/log/lxd/lxd.log /var/log/lxd/c1/lxc.log

## Check mounting network resource with container priviledged
root@lxc:~# 
`lxc stop c1`
`lxc delete c1`
`lxc init ubuntu:xenial c1`
`lxc config set c1 security.privileged true`
`lxc start c1`
`lxc exec c1 bash`
root@c1:~# 
`apt-get -y install cifs-utils`
`mount -v -o username=***,password=***,iocharset=utf8,file_mode=0777,dir_mode=0777 -t cifs //nas/downloads /mnt`
#=>
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
#=>Nothing in various logs... /var/log/syslog /var/log/lxd/lxd.log /var/log/lxd/c1/lxc.log

## Check mounting network resource with apparmor unconfined and container priviledged
root@lxc:~# 
`lxc stop c1`
`lxc delete c1`
`lxc init ubuntu:xenial c1`
`lxc config set c1 security.privileged true`
`lxc config set c1 raw.lxc lxc.aa_profile=unconfined`
`lxc start c1`
`lxc exec c1 bash`
root@c1:~# 
`apt-get -y install cifs-utils`
`mount -o username=***,password=***,iocharset=utf8,file_mode=0777,dir_mode=0777 -t cifs //nas/downloads /mnt`
root@c1:~# 
`ls -lh /mnt/`
total 0
drwxrwsrwx 2 root users 0 May 11 13:04 test
`echo "bar" > /mnt/test/bar.file`
`ls -lh /mnt/test/bar.file`
-rw-r--r-- 1 1056 users 4 May 11 14:29 /mnt/test/bar.file
#=>Seems ok! And if I change umask, I can create file with 666 rights.

So it is a solution. Not the best I think, but a solution.

@stgraber Is it possible to allow the container to mount network resource but stay unpriviledged? So just allow the mount permission? How? And same, is it possible to create a container with only the apparmor right to mount resource?
Possibly using a profile?

Thank you very much!

**Comment by JohnstonJ** [comment]
See my comment in #2025...

**Comment by typhoe** [comment]
@JohnstonJ Interesting! 
That's not a solution to mount the resource inside the container, but I'll try by mounting on the host and sharing the resource with the container. 
And at least, It doesn't need unprivileged or messing with apparmor.
Thank you!

**Comment by stgraber** [comment]
@typhoe Nope. Only filesystems which are user namespace aware can be mounted inside an unprivileged container. That's a kernel enforced policy, not something we're doing with some kind of security profile in userspace, so there's no way for you to allow it.

If doing a privileged container, then the mount restrictions are applied through apparmor rather than enforced directly by the kernel, in which case, you can set raw.apparmor to "mount," which would allow all mounts.

**Comment by typhoe** [comment]
Ok, thank you @stgraber for the clarification, I'll try the solution offered by @JohnstonJ  then to stay with an unpriviledged container approch!

**Comment by ludwig-gramberg** [comment]
so it is safe to assume that an unprivileged container can never mount an nfs share directly?
i'm mounting nfs in the host and only giving each container a subfolder as their own mount entry point. container a must never be able to access container b's files. so thats the case right?

**Comment by stgraber** [comment]
Right now, that's correct. It's not a limitation imposed by LXD but by the Linux kernel. The NFS filesystem isn't marked as being safe for unprivileged users to mount.
