### ISSUE TITLE
lxc create doesn't exist

### ISSUE THREAD

**Issue by hatched** [lxc/lxd#201]
Following the guide in the readme.md. After installing via the ppa on 14.04 and with the lxd daemon running the `lxc create foo` just lists the -h output which also doesn't include a create.

**Comment by tych0** [comment]
Hi, thanks for pointing that out. We had some discussion and we like the `launch` mnemonic better than `create` and then `start`, boneheaded me had just forgotten to update the docs, but the code is there.

If you're still interested in the two step process, you can do `init` and then `start`.
