### ISSUE TITLE
Mounting WebDAV resource (using FUSE-based Davfs) fails due to faulty LXC apparmor rule

### ISSUE THREAD

**Issue by eugene-chow** [lxc/lxd#2015]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-22-generic
  server: lxd
  serverpid: 1539
  serverversion: 2.0.0
  storage: btrfs
  storageversion: "4.4"

# Issue description

I tried to mount a WebDAV resource in a container but received this error:
> Error msg: [  179.551611] audit: type=1400 audit(1462871078.544:28): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxd-container_</var/lib/lxd>" name="/mnt/" pid=6524 comm="mount.davfs" fstype="fuse" srcname="https://cloud.local" flags="rw, nosuid, nodev"

Adding the apparmor profile to the container `lxc config set <container> raw.apparmor 'mount fstype=fuse,'` solved the issue. However, I noticed that the default LXC apparmor profile at `/etc/apparmor.d/abstractions/lxc` had this entry

 ```
# allow fuse mounts everywhere
 mount fstype=fuse.*,
```

By its description, it is supposed to allow FUSE mounts by default in any newly launched containers. I changed it to `mount fstype=fuse,` and the mounting worked without applying the mentioned `raw.apparmor` rule.

Is `mount fstype=fuse.*,` a bug?

Here are the steps to enable FUSE mounts for a particular container, without modifying the default LXC apparmor template. I got some of the steps from [this page](http://www.forshee.me/2016/02/22/container-mounts-in-ubuntu-1604.html).
 1. In the container's host, install the necessary packages for the desired FUSE fs. In my case, it was Davfs.

 `apt install davfs2`

 2. Enable user mounts in FUSE

 `echo Y > /sys/module/fuse/parameters/userns_mounts`

 3. Allow FUSE mounts in container
 
`lxc config set <container> raw.apparmor 'mount fstype=fuse,'

4. Create FUSE device in container

 `lxc config device add <container> fuse unix-char path=/dev/fuse`

5. Restart the container and FUSE mounts should work

Last but not least, a huge thanks to the LXD team for building this awesome piece of software!

**Comment by stgraber** [comment]
That's odd, fuse certainly used to show up as fuse.NAME.

@sforshee any idea why that would have changed?

I certainly don't mind allowing fstype=fuse too so long as it doesn't allow some internal fuse filesystem thing that we wouldn't want containers to mount.

**Comment by sforshee** [comment]
I'm not sure about the fuse.* thing ... it seems to be permitted by the kernel but I don't recall ever seeing it show up as fuse.NAME. It might depend on what version of the fuse userspace bits you're using.

From the kernel perspective fuse.* and fuse aren't really any different though, both end up doing the same thing afaict (the kernel matches the fstype to whatever precedes the dot, and the fuse module doesn't pay any attention to it). What's after the dot doesn't even matter - you could change the userspace code to pass fuse.ANYTHING to mount(2), apparmor would be happy and the kernel would just treat it like you passed fuse.

So I think it's completely safe to allow fstype=fuse, or at minimum no less safe.

**Comment by stgraber** [comment]
I sent https://github.com/lxc/lxc/pull/1020 which should fix that.
