### ISSUE TITLE
Copying a remote snapshot losses the container config/devices

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#2017]
When copying a remote container snapshot into a new local container, the remote container's configuration and devices are lost.

**Comment by tych0** [comment]
On Wed, May 11, 2016 at 10:03:06AM -0700, Stéphane Graber wrote:
> When copying a remote container snapshot into a new local container, the remote container's configuration and devices are lost.

Oh, derp. I'll take a look, this is probably a simple fix.

**Comment by stgraber** [comment]
@tych0 I think it's a client bug, not something done in the daemon. On local copy, the daemon does the copy of the config and devices, on remote copies, the client should be sending those bits.

Our client code currently doesn't support commands like "lxc config show" against snapshots, so it probably makes sense that it also doesn't know how to fetch the snapshot config and devices on copy.

I'm pretty sure the fix is just going to be a couple lines of code at the right place in the remote copy code, then possibly a bit more to also make "lxc config show" work with snapshots.

**Comment by tych0** [comment]
Yeah, turns out we don't have an API call for getting a single snapshot's info either, so we'll need that too.

**Comment by stgraber** [comment]
@tych0 I'm pretty sure I added that stuff to GET /1.0/containers/NAME/snapshots/SNAP a bit before 2.0 release.

**Comment by stgraber** [comment]
```
stgraber@dakara:~$ curl -s --unix-socket /var/lib/lxd/unix.socket lxd/1.0/containers/snappy/snapshots/abc | jq .
{
  "type": "sync",
  "status": "Success",
  "status_code": 200,
  "metadata": {
    "architecture": "x86_64",
    "config": {
      "volatile.base_image": "510c27eb5e30ac53c6cf8b423d4e145bd2e40b8845e89bd66a5d78e2a087727a",
      "volatile.eth0.hwaddr": "00:16:3e:92:15:6f",
      "volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]"
    },
    "created_at": "2016-05-11T17:19:10Z",
    "devices": {
      "root": {
        "path": "/",
        "type": "disk"
      }
    },
    "ephemeral": false,
    "expanded_config": {
      "volatile.base_image": "510c27eb5e30ac53c6cf8b423d4e145bd2e40b8845e89bd66a5d78e2a087727a",
      "volatile.eth0.hwaddr": "00:16:3e:92:15:6f",
      "volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]"
    },
    "expanded_devices": {
      "eth0": {
        "name": "eth0",
        "nictype": "bridged",
        "parent": "lxdbr0",
        "type": "nic"
      },
      "root": {
        "path": "/",
        "type": "disk"
      }
    },
    "name": "snappy/abc",
    "profiles": [
      "default"
    ],
    "stateful": false
  }
}
```

**Comment by tych0** [comment]
in client.go, not in the rest api :)

**Comment by stgraber** [comment]
Ah yeah :)
