### ISSUE TITLE
used memory discrepancies

### ISSUE THREAD

**Issue by davereiner** [lxc/lxd#2023]
I'm trying to figure out why is there a huge difference between the reported used memory and the actual used memory. I have a server with 204GB RAM running 85 containers.

```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          204G       178G        26G        10G        95M        23G
-/+ buffers/cache:       154G        50G
```

When adding up the memory usage of each container from lxc info I get **63.4 GB** in total. When running _ps -eo rss --sort -rss | awk '{ hr=$1/1024 ; printf("%13.2f ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }'_ on the host and adding up the numbers I get **76,984 MB**. I have absolutely no idea where the rest of the 154 - 77 GBs are.

Worst of all it just keeps growing with no end in sight:
![Memory Usage](http://i.imgur.com/8ka875S.png)

This is an Ubuntu 15.10 host with mostly 16.04 containers.

**Comment by stgraber** [comment]
Are you using zfs?

**Comment by davereiner** [comment]
Yes.

**Comment by stgraber** [comment]
So there is a very good chance all that memory is being used by ZFS for its cache. Unless you configured it otherwise.

As ZFS isn't a normal Linux filesystem, such memory usage wouldn't be counted as buffers/cached but as actual used memory instead.

**Comment by stgraber** [comment]
You can check with:

```cat /proc/spl/kstat/zfs/arcstats | grep ^c```

**Comment by davereiner** [comment]
That's probably it then, I'm reading everything about ARC (and watching all the Iron Man movies for good measure) now and will keep monitoring. Thanks for the quick reply Stéphane!

**Comment by davereiner** [comment]
One more question regarding this: what happens when ZFS reserves all the free memory, will containers be able to "take it back" from ARC or will it get into an OOM situation?

**Comment by stgraber** [comment]
Yeah, zfs is supposed to release ARC memory when under memory pressure.

**Comment by davereiner** [comment]
Excellent, thanks for the quick responses. Closing this now.
