### ISSUE TITLE
Feature: Add container timeout as a configuration option

### ISSUE THREAD

**Issue by JohnstonJ** [lxc/lxd#2027]
# Required information

 * Distribution: N/A (applies to master branch, commit b588fe35c359eca860d5230919cb9818ed4d6dac)

# Issue description

Container shutdown timeout is currently hard-coded to 30 seconds, as per:

* https://github.com/lxc/lxd/blob/b588fe35c359eca860d5230919cb9818ed4d6dac/doc/daemon-behavior.md#sigpwr
* https://github.com/lxc/lxd/blob/b588fe35c359eca860d5230919cb9818ed4d6dac/lxd/containers.go#L158

In case a container needs extra time to shutdown, it would be nice to be able to customize this with a configuration option (especially if, for whatever reason, some service inside the container has its own timeout that is longer than 30s).  It could be a per-server option, or a per-container option.

A comparison from another project would be when using libvirt with KVM, we can edit `/etc/default/libvirt-guests` and set `SHUTDOWN_TIMEOUT` to a long value if we think the timeout is too short.

**Comment by stgraber** [comment]
So one thing to keep in mind here is that the init systems themselves typically come with a similar timeout, so we can certainly make it possible to bump the timeout in LXD but that will most likely result in your init system killing LXD which will then fail to record what containers were running and all your containers will get SIGKILLED.

This is likely to depend on the init system you use and what kind of policy it applies as far as timeouts though.

**Comment by JohnstonJ** [comment]
That's true.  I know with systemd one could set the lxd service to have an infinite timeout, though it would mean a bug in lxd could mean that the system never shuts down.

On my libvirt installation:

    $ systemctl cat libvirt-guests.service
    [Service]
    <snip>
    TimeoutStopSec=0

So it looks like that's exactly how they did it there: tell the init system "trust me, I have my own timeouts."
