### ISSUE TITLE
exec chained commands with rest api

### ISSUE THREAD

**Issue by azazdeaz** [lxc/lxd#2028]
Hi,

I tried the [exec route](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#10containersnameexec) and it's working well, (ex: ```{command: ['ip', 'addr'], 'wait-for-websocket': true}```) but i dont know how to execute chained commands like ```A && B```.

Thanks for your help and your work on this project!

**Comment by stgraber** [comment]
Such a command is meant to be interpreted by a shell rather than just execed by the operating system.

To do something like that, do: {command: ["sh", "-c", "a && b"]}

**Comment by azazdeaz** [comment]
Thanks a lot!
