### ISSUE TITLE
Benefits of Xenial and kernel 4.6?

### ISSUE THREAD

**Issue by davereiner** [lxc/lxd#2029]
Are there any known benefits to upgrading to the 4.6 kernel line with Xenial based LXDs? I know for example that CRIU wasn't working with kernels before 4.6 (and backported to 4.4 Ubuntu) so that's why I'm asking. Thanks!

**Comment by tych0** [comment]
On Mon, May 16, 2016 at 01:59:59AM -0700, davereiner wrote:
> Are there any known benefits to upgrading to the 4.6 kernel line with Xenial based LXDs? I know for example that CRIU wasn't working with kernels before 4.6 (and backported to 4.4 Ubuntu) so that's why I'm asking. Thanks!

There are some autofs-related commits that went into 4.6 for CRIU, but
other than that they should be effectively the same as 4.4. What about
4.4 and CRIU didn't work for you?

**Comment by stgraber** [comment]
Also note that the upstream 4.6 kernel won't have all the AppArmor bits that the Ubuntu kernel carries, so  it may actually be slightly worse.

**Comment by davereiner** [comment]
I haven't tried CRIU yet as the Wily install on GCE was still on 4.2, that's one of the reasons we're moving to Xenial and 4.4 based servers now. And before moving I thought I'd ask about the kernel thing seeing that 4.6 came out yesterday :) It's good to know that I can proceed with the official/Ubuntu version of the 4.4 then. Thanks guys!
