### ISSUE TITLE
Support specifying list of SSL/TLS ciphers for lxd, or just add additional ciphers

### ISSUE THREAD

**Issue by JohnstonJ** [lxc/lxd#2034]
Currently it does not seem possible to specify a custom list of ciphers.  This is OK if the lxc command line tool is used, but it breaks some front-ends.

This is a useful request because of projects like:

- https://github.com/dobin/lxd-webgui
- https://github.com/aarnaud/lxd-webui

which aim to provide a web GUI front-end to the lxd service. (they are the only LXD front-ends i've found so far).  They are client-side code only; the server is just serving static content.  The client web browser directly connects to the lxd REST API.

However the problem is that lxd only supports TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 cipher, which is not supported by Internet Explorer 11 on Windows 7, for example (reference: https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%208.1).  So it is not possible to use these user agents with a web GUI as listed above.  It seems like it would be reasonable to allow a few other cipher suites to be specified, which have better web browser support.

**Comment by stgraber** [comment]
Hmm, this doesn't make sense to me. According to the code, we allow two ciphers:
 - tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 - tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256


According to the document you linked to, IE doesn't support the first, but it supports the second, so there should be no problem.

**Comment by JohnstonJ** [comment]
I assume you refer to https://github.com/lxc/lxd/blob/57bfe90f4d4e79696d678e74b95676731d652830/shared/network.go#L41 and https://github.com/lxc/lxd/blob/256460d6c45596ad0d27f771d559432341c5bdab/lxd/daemon.go#L806 ?

I see what you mean.  But something is wrong because:

```
$ dpkg -s lxd
Version: 2.0.2-0ubuntu1~16.04.1
```
(I confirmed that this version does declare both ciphers in above linked locations).

Scanning the endpoint with Digicert's tool:

![image](https://cloud.githubusercontent.com/assets/13113915/15860010/e6391816-2cb6-11e6-9fe2-65ac52bfec13.png)

I also tested in Wireshark and confirmed the findings:
 - IE11 indeed offers to use `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256` but not `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`
 - The server replies with TLS alert 21: handshake failure. (Alert 21 record, message level == 2 == fatal, description == 40 == Handshake Failure).

**Comment by stgraber** [comment]
Ah, the problem is that ECDHE_ECDSA can only be selected if the server certificate is using ECDSA... so we need to find another reasonable RSA one instead.
