### ISSUE TITLE
lxd reports https endpoint for images, even though http transport is used

### ISSUE THREAD

**Issue by pontillo** [lxc/lxd#2035]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: xenial
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-22-generic
   * LXC version: (none)
   * LXD version: 2.0.0-0ubuntu4
   * Storage backend in use: zfs

# Issue description

When I look at `lxc remote list`, I see that the https protocol is in use for the simplestreams endpoints. (I had considered this a bug, because I want them to use HTTP -- since the .gpg signatures are presumably verified, and so that I can use a DNS man-in-the-middle in order to easily create a local mirror.)

```
$ lxc remote list
+-----------------+------------------------------------------+---------------+--------+--------+
|      NAME       |                   URL                    |   PROTOCOL    | PUBLIC | STATIC |
+-----------------+------------------------------------------+---------------+--------+--------+
| images          | https://images.linuxcontainers.org       | lxd           | YES    | NO     |
+-----------------+------------------------------------------+---------------+--------+--------+
| local (default) | unix://                                  | lxd           | NO     | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
| ubuntu          | https://cloud-images.ubuntu.com/releases | simplestreams | YES    | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
| ubuntu-daily    | https://cloud-images.ubuntu.com/daily    | simplestreams | YES    | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+

```
It is misleading to advertise that we are using https when http transport is being used. We should be honest about it, and (assuming the signatures are properly verified) default to the http endpoint.

Wireshark output (after following the TCP stream opened to cloud-images.ubuntu.com):
https://paste.ubuntu.com/16510454/

Related MAAS bug: https://bugs.launchpad.net/maas/+bug/1582836

# Steps to reproduce

 - verify that `lxc remote list` output matches the above
 - launch wireshark or tcpdump and start capturing packets
 - launch an ubuntu image which is not cached locally
 - note that LXD is talking to cloud-images.ubuntu.com via port 80, unencrypted

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
That's absolutely correct.

**Comment by stgraber** [comment]
20:07 < stgraber> mpontillo: we always fetch the index over https and then attempt to fetch the content over http, if the http fetched content doesn't match the index then we re-fetch over https
20:08 < stgraber> mpontillo: so having it show as https is absolutely correct, we don't support connecting to http-only simplestreams, but we do fetch the content over http whenever possible

**Comment by smoser** [comment]
I really kind of disagree with this being closed.  Requiring secure transport for verification is a bug, and quite limiting on anyone interested in mirroring or even just caching data.  The current lxd implementation requires someone interested in offline mirror to offer https and get the certificate into the system's they're using it on.  To cache via caching http proxy they *also* have to open up outbound https access.

we have a trusted gpg key that was delivered out of band and have signed the data with that key.  Relying on secure tranport may be a temporary work around, but it is still much less than ideal.

**Comment by pontillo** [comment]
I'm torn on this issue, because I love my zero-configuration local mirrors. ;-)

But when I think about this with my security hat on, there *is* one issue with defaulting to non-HTTPS transport: an attacker could purposely inject an old set of images with known security issues.

Go down that road, and then you think maybe the image index could have some sort of a "valid lifetime", whereby we no longer trust the signed index if it's too old. But then, it feels like we're re-implementing X.509, doesn't it?

At the end of the day, using TLS for fetching the index should be optional, to support both use cases. But I think it violates the principle of least surprise to specify http and see it connect to https, or specify https and see it connect via http.
