### ISSUE TITLE
Cannot start unprivileged container, failed to remove mac_admin

### ISSUE THREAD

**Issue by longsleep** [lxc/lxd#2039]
# Required information

 * Distribution: Ubuntu 16.04
 * Distribution version: core on arm64
 * The output of "lxc info" or if that fails:
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: aarch64
  kernelversion: 3.10.101-2-pine64-longsleep
  server: lxd
  serverpid: 2850
  serverversion: 2.0.0
  storage: dir
  storageversion: ""

# Issue description

For some reason unprivileged container startup cannot drop capabilities. I am fairly sure it is related to my custom Kernel and i am looking for ways to figure out what needs to change.

# Steps to reproduce

lxc start my-ubuntu

# Information to attach

It works just fine for privileged containers (after running lxc config set my-ubuntu security.privileged true).

Relevant log output.

```
lxc 20160521150911.045 DEBUG    lxc_conf - conf.c:setup_caps:2055 - drop capability 'mac_admin' (33)
            lxc 20160521150911.045 ERROR    lxc_conf - conf.c:setup_caps:2058 - Operation not permitted - failed to remove mac_admin capability
            lxc 20160521150911.045 ERROR    lxc_conf - conf.c:lxc_setup:3834 - failed to drop capabilities
```

Kernel tree is 3.10 as found in the Allwinner A64 BSP packages + fixes and the Apparmor backports as found at http://kernel.ubuntu.com/git/ppisati/ubuntu-vivid.git/log/?h=snappy_v3.10

**Comment by stgraber** [comment]
Seems like the kernel is the problem here. @hallyn thoughts?

**Comment by hallyn** [comment]
Could you show what you get from:

sudo capsh --drop=cap_mac_admin -- -c "/sbin/capsh --print"

**Comment by hallyn** [comment]
gah, part of my comment got deleted, also please show:

lxc-usernsexec -- capsh --drop=cap_mac_admin -- -c "/sbin/capsh --print"

**Comment by longsleep** [comment]
Here it comes

```
root@pine64:~# sudo capsh --drop=cap_mac_admin -- -c "/sbin/capsh --print"
Current: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_syslog,cap_wake_alarm,cap_block_suspend+ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_syslog,cap_wake_alarm,cap_block_suspend
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=0(root)
gid=0(root)
groups=0(root)
```
This seems to have dropped fine.

```
root@pine64:~# lxc-usernsexec -- capsh --drop=cap_mac_admin -- -c "/sbin/capsh --print"
failed to drop [cap_mac_admin=33]
```
Failed.


And for completeness sake
```
root@pine64:~# lxc-usernsexec -- capsh -- -c "/sbin/capsh --print"
Current: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend+ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=0(root)
gid=0(root)
groups=
```
Have cap_mac_admin without dropping.

**Comment by longsleep** [comment]
So without knowing much about lxc, it seems that whatever lxc-usernssexec is doing causes the problem. I also hat to do an 'apt-get install lxc' to actually get that tool as its not a dependency for lxd.

**Comment by hallyn** [comment]
You are running kernel version

: aarch64 kernelversion: 3.10.101-2-pine64-longslee

Where does that come from?  Can you point to the config (maybe in
/boot/config-3.10.101-*) and the source?

Can you show any new syslog messages which get created while you do

lxc-usernsexec -- capsh --drop=cap_mac_admin -- -c "/sbin/capsh --print"

?

(maybe do 'sudo dmesg -w' whilt you run the command)

**Comment by longsleep** [comment]
Sure, its the tree i maintain for the Pine64 board. Config and tree found at https://github.com/longsleep/linux-pine64/blob/pine64-hacks-1.2/arch/arm64/configs/sun50iw1p1smp_linux_defconfig - fully expaned Kernel config as compiled: http://paste.ubuntu.com/16661875/

Unfortunately no new messages in dmesg when running `lxc-usernsexec -- capsh --drop=cap_mac_admin -- -c "/sbin/capsh --print"` :/

**Comment by hallyn** [comment]
if this is the right branch,

https://github.com/longsleep/linux-pine64/blob/pine64-hacks-1.2/security/commoncap.c

cap_prctl_drop() there is wrong.  The check for capable(CAP_SETFCAP) needs to become
ns_capable or it will never be granted in a user namespace.  Please see upstream for
a fix.

**Comment by longsleep** [comment]
Awesome, thanks for taking the time to look into this!

**Comment by longsleep** [comment]
I have cherry-picked https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/security/commoncap.c?id=160da84dbb39443fdade7151bc63a88f8e953077 and it works just fine now. Thanks again!
