### ISSUE TITLE
lxc launch ubuntu-daily:xenial c4 hangs but lxc launch images:ubuntu/xenial/amd64 x5 OK

### ISSUE THREAD

**Issue by niccolox** [lxc/lxd#2040]
`lxc launch ubuntu-daily:xenial c4 `

just hangs, waits... 

but 

`lxc launch images:ubuntu/xenial/amd64 x5 `

works OK

**Comment by stgraber** [comment]
They come from two separate image servers, so it most likely is that accessing https://cloud-images.ubuntu.com is hanging or being very very slow for you for some reason while accessing https://images.linuxcontainers.org works properly.

**Comment by stgraber** [comment]
Some tcpdump'ing may give you a better idea of what's going on.

**Comment by stgraber** [comment]
If it would just entirely fail to connect, LXD would have given you an error message. The fact that it didn't suggest that something's answering and then either hanging or taking a long long time to send bits across.

**Comment by niccolox** [comment]
Havent checked yet. But suspect ipv6

**Comment by stgraber** [comment]
Ah yeah, broken IPv6 connectivity, especially an invalid MTU somewhere on the path to the server could make you loose some packets, hanging your connection.

**Comment by niccolox** [comment]
Getting ipv6 errors in all sorts of annoying and suprizing places

**Comment by stgraber** [comment]
For what it's worth, your problem is most likely to be on your end of the network.

My home network is IPv6 only (DNS64 & NAT64 at the gateway) and it's all working perfectly well :)

**Comment by niccolox** [comment]
I am running static ipv4 bridged as described here
https://github.com/juju/juju/issues/5439#issuecomment-220808972

my ipv6 is dynamic and I cant use it for dns or I would also be probably
ipv6, via comcast and I havent been doing any management of ipv6

I am going to turn off ipv6 completely and see if that helps

I think ALSO I am having issues with a LXD non standard bridge

On Tue, May 31, 2016 at 7:05 PM, Stéphane Graber <notifications@github.com>
wrote:

> For what it's worth, your problem is most likely to be on your end of the
> network.
>
> My home network is IPv6 only (DNS64 & NAT64 at the gateway) and it's all
> working perfectly well :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lxc/lxd/issues/2040#issuecomment-222873452>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAbsptip2aGDQVk5S9AK9PFZOsHhHHesks5qHOkFgaJpZM4Ij5Iq>
> .
>



-- 

-- 
Nicholas Roberts
www.niccolox.org

**Comment by niccolox** [comment]
correction, my ipv6 is not assignable for dns so I cant really use it,
otherwise I would be quite happy to escape the expensive ip4 scarcity thing

will turn off ipv6 and see if that helps (pretty sure its part of my
problem)

the other is my non standard LXD bridge

it works for LXD and Ansible LXD cloud provider, but not Juju

On Tue, May 31, 2016 at 7:15 PM, Nicholas Roberts <niccolo.roberts@gmail.com
> wrote:

> my ipv6 is dynamic and I cant use it for dns or I would also be probably
> ipv6, via comcast and I havent been doing any management of ipv6





-- 

-- 
Nicholas Roberts
www.niccolox.org

**Comment by niccolox** [comment]
you where right about the networking (unsurprisingly) apologies for that

the gotcha was /etc/network/interfaces.d already had an eth0.cfg in one case

even more obscure, sendmail was previously uninstalled and it left config files that prevented networking systemd to start cleanly but still run

cant get the non standard bridge to work for lxd with juju but thats not your problem!
