### ISSUE TITLE
snappy: lxc list /home/ubuntu/apps/lxd/2.0.0-2/.config/lxc/config.yml: permission denied

### ISSUE THREAD

**Issue by erickeller** [lxc/lxd#2044]
# Required information

 * Distribution: ubuntu core snappy (raspberry pi 2)
 * Distribution version:15.10
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux localhost.localdomain 4.2.0-1022-raspi2 #29-Ubuntu SMP Fri Jan 22 16:28:44 UTC 2016 armv7l armv7l armv7l GNU/Linux
   * LXC version: 2.0.0
   * LXD version: 2.0.0-2
   * Storage backend in use:

# Issue description

missing config.yml file

A brief description of what failed or what could be improved.

# Steps to reproduce

 1. 
```
sudo lxc image list
error: cannot read config file: open /home/ubuntu/apps/lxd/2.0.0-2/.config/lxc/config.yml: permission denied
```

fixed as soon as you grab an image from the remote:

```
lxc launch images:debian/jessie/armhf jessie
```
# Information to attach
none

**Comment by stgraber** [comment]
Don't use the "lxc" command under "sudo" with snappy, it just doesn't work.

**Comment by stgraber** [comment]
(It's not a LXD issue, it's the snappy apparmor layer preventing it from working under sudo, just run it as a normal user and it'll be fine)

**Comment by jhautefeuille** [comment]
Chown -R solve the problem on /lxc/config.yml
