### ISSUE TITLE
The displayed tables are not formatted correctly when accented characters are used

### ISSUE THREAD

**Issue by brunonova** [lxc/lxd#2051]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * LXD version: 2.0.1

# Issue description

This is just a very small display bug, but it's probably also very easy to fix.

When `lxc` displays tables (in the terminal) that contain accented characters and other special characters, the table is not formatted correctly.

Example (in Portuguese):

```
$ lxc image list
+--------+--------------------+----------+-----------------------------------------------+--------+----------+------------------------------+
| ALIAS  | IMPRESSÃO DIGITAL | PÚBLICO |                  DESCRIÇÃO                  |  ARCH  | TAMANHO  |         UPLOAD DATE          |
+--------+--------------------+----------+-----------------------------------------------+--------+----------+------------------------------+
| xenial | d23ee1f4fd28       | não     | ubuntu 16.04 LTS amd64 (release) (20160516.1) | x86_64 | 138.85MB | May 26, 2016 at 8:04pm (UTC) |
+--------+--------------------+----------+-----------------------------------------------+--------+----------+------------------------------+
```

Notice that most `|` characters are not aligned.

Accented and special characters in UTF-8 span multiple chars/bytes.
You should take that into account when calculating the length of strings (according to the `utf8` manpage, just count all chars whose most significant bits are not `10`).

**Comment by stgraber** [comment]
Oh, interesting. Can you report this against https://github.com/olekukonko/tablewriter as the table rendering is handled by that library and not by LXD itself?

I suspect they count a unicode codepoint as two bytes and assume that one byte means one character rendered on screen which isn't quite right.

**Comment by brunonova** [comment]
Will do (tomorrow).

**Comment by brunonova** [comment]
Reported: <https://github.com/olekukonko/tablewriter/issues/35>

**Comment by stgraber** [comment]
Thanks!

**Comment by olekukonko** [comment]
This has been fixed before .. can you please update the version of `tablewriter` and confirm if you still having the same issues ???  We are currently using github.com/mattn/go-runewidth to determine the string width.

**Comment by brunonova** [comment]
@stgraber, have you checked that yet?

**Comment by stgraber** [comment]
We always bundle the latest library version in our release tarballs, so 2.0.3 should have it.
