### ISSUE TITLE
Documentation - Snapshots and images on a separate disk

### ISSUE THREAD

**Issue by tozaz** [lxc/lxd#2052]
Hi,

Actually lxd init allow one volume for all types.

I would like to ask for a documentation on how to have containers on a disk and snapshots and images on an other disk.

Typically containers on a ZFS high performance SSD volumes and snapshots and images on a ZFS low performance standard disk.

Thanks for your help.

Regards,
Xavier

**Comment by stgraber** [comment]
That's simply not possible. btrfs, zfs and LVM all require the snapshots to be on the same disk as the snapshotted object.

Similarly since containers are themselves clones from an image, the images also must be part of the same storage pool.
