### ISSUE TITLE
lxc exec commands with && and | operators

### ISSUE THREAD

**Issue by prabhu** [lxc/lxd#2057]
How can I issue commands with && and | operator with lxc exec? Tried wrapping them within single or double quotes with no effect.

Eg:
```bash
lxc exec <container> -- cd /tmp && ls -l
(Yes I know ls -l /tmp but that's not the point)
```

**Comment by stgraber** [comment]
lxc exec container-name -- sh - c "ls && ps"

**Comment by spyderdyne** [comment]
perfect.  thanks!
