### ISSUE TITLE
GET on non-existent container files should 404

### ISSUE THREAD

**Issue by rockstar** [lxc/lxd#2059]
# Required information

 * Distribution: ubuntu
 * Distribution version: xenial
 * The output of "lxc info" or if that fails:
   * Kernel version: N/A
   * LXC version: N/A
   * LXD version: 2.0.1
   * Storage backend in use: N/A

# Issue description

Getting a non-existent file from a container results in a 500 HTTP status. It should result in a 404 rather than a 500.

# Steps to reproduce

 1. GET /1.0/containers/<container>/files
 2. See the response code is 500

**Comment by stgraber** [comment]
Yeah, I'd expect a Bad Request for /1.0/containers/files when a path isn't provided and then a 404 if a path is provided and the file doesn't exist (may involve some errno parsing on our end though).
