### ISSUE TITLE
Request LXD API list all containers of remote server

### ISSUE THREAD

**Issue by dattengichaduoc** [lxc/lxd#2061]
LXD API Publish on port 8443.

I create a server controller add remote .

```lxd remote list```

and
```lxc list name_remote:```

How to get all container with LXD Controller API

/1.0/containers/name_remote/ .. etc

Please help me .

**Comment by stgraber** [comment]
It's just a simple "GET /1.0/containers" against each of your hosts.

The concept of "remote" only exists in the command line client, there is no such concept in the API so the URL you mentioned above doesn't make any sense.

You'd instead just query:
 - https://host-a:8443/1.0/containers
 - https://host-b:8443/1.0/containers
 - ...

**Comment by stgraber** [comment]
Also, you may want to read https://www.stgraber.org/2016/04/18/lxd-api-direct-interaction/

**Comment by dattengichaduoc** [comment]
Thanks stgraber. :D

**Comment by jaytaylor** [comment]
Note: You can also [use curl to query the LXD unix.socket file descriptor directly](https://gist.github.com/jaytaylor/56a9989c9e974960200ea1be64396b03).

Example:

```bash
curl --unix-socket /var/lib/lxd/unix.socket http:/1.0/containers
```

See the linked gist for example output.

https://gist.github.com/jaytaylor/56a9989c9e974960200ea1be64396b03

**Comment by stgraber** [comment]
`lxc image list <name>:`

**Comment by stgraber** [comment]
Also for local queries, recent LXD lets you do:

```
lxc query /1.0/containers
```

Which works kinda like curl but lets you use remotes and has some amount of knowledge about LXD operations and other weirder aspects of the API.

**Comment by jaytaylor** [comment]
That is fantastic, thank you for following up @stgraber !!!
