### ISSUE TITLE
port forwarding from host to container

### ISSUE THREAD

**Issue by pgassmann** [lxc/lxd#2074]
If I have a Webserver (or Proxy) in a lxd container and forward the host port 80 to the container, the resource is available from outside, but not from the host and not from other containers.

E.g. Host IP: 10.7.0.202
Container test1 ip: 10.54.20.213 (with apache2 installed)
Container test2 ip: 10.54.20.200

Test command: `curl -vI 10.7.0.202`

IPtable rule:
`iptables -t nat -A PREROUTING -i enp0s3 -p tcp -m multiport --dports 80 -j DNAT --to-destination 10.54.20.213:80`
with only this rule, on the host itself  `curl -vI 10.7.0.202` returns "Connection refused.

to enable forwarding from host i found that you have to add:
`iptables -t nat -A OUTPUT -o lo -p tcp -m multiport --dports 80 -j DNAT --to-destination 10.54.20.213:80`

I tried to add an additional forward rule from lxdbr0 specifically to host ip (required, otherwise all outgoing web traffic from containers is captured)
`iptables -A PREROUTING -i lxdbr0 -p tcp -m multiport -d 10.7.0.202 --dports 80 -j DNAT --to-destination 10.54.20.213:80 -t nat`

from the containers test1 and test2 I get connection timed out. which suggests that the packages do go somewhere. 

**How can I forward packages from any source (incl. containers) destined to the Host 10.7.0.202:80 to the container test1 10.54.20.213:80 ?**

All Iptables rules on host:
```
# Generated by iptables-save v1.6.0 on Thu Jun  2 18:28:50 2016 
*mangle
:PREROUTING ACCEPT [11084:12784293]
:INPUT ACCEPT [8953:837108]
:FORWARD ACCEPT [2125:11944715]
:OUTPUT ACCEPT [5915:927119]
:POSTROUTING ACCEPT [7969:12865866]
-A POSTROUTING -o lxdbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
COMMIT
# Completed on Thu Jun  2 18:28:50 2016
# Generated by iptables-save v1.6.0 on Thu Jun  2 18:28:50 2016
*nat
:PREROUTING ACCEPT [1:72]
:INPUT ACCEPT [1:72]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -i enp0s3 -p tcp -m multiport --dports 80 -j DNAT --to-destination 10.54.20.213:80
-A PREROUTING -i lxdbr0 -p tcp -m multiport -d 10.7.0.202 --dports 80 -j DNAT --to-destination 10.54.20.213:80
-A OUTPUT -o lo -p tcp -m multiport --dports 80 -j DNAT --to-destination 10.54.20.213:80
-A POSTROUTING -s 10.54.20.0/24 ! -d 10.54.20.0/24 -j MASQUERADE
COMMIT
# Completed on Thu Jun  2 18:28:50 2016
# Generated by iptables-save v1.6.0 on Thu Jun  2 18:28:50 2016
*filter
:INPUT ACCEPT [3365:297101]
:FORWARD ACCEPT [304:592713]
:OUTPUT ACCEPT [2043:270670]
COMMIT
# Completed on Thu Jun  2 18:28:50 2016
```

All with latest Ubuntu 16.04

**Comment by stgraber** [comment]
Not really specific to LXD, you'd see the same running VMs.

I think the problem you're running into is that your container talks to a host IP, gets NATed to the right container but then the container running the web server responds directly to the source bypassing the host since they are in the same subnet.

This then gets dropped by the source container as the incoming source IP doesn't match the IP it connected to.

Step by step from a network layer:
 - container-a connects to host IP on port 80
 - host nats the request, rewriting the destination to point to container-b, source address remains intact
 - container-b receives the request from the host with the source address pointing to container-a
 - container-b answers the request, sending the reply to the source which is container-a
 - container-a receives a response but with container-b's address as the source rather than the IP it connected to, it drops the packet as invalid
 - request hangs

**Comment by stgraber** [comment]
One way to workaround this particular problem would be to also SNAT the packets on the host, at which point container-b would send the reply back to the host which will then send it to container-a as expected.

**Comment by pgassmann** [comment]
thank you. LXD is a great project. By using it you really learn linux networking and ip networking. ;-)

I added the following rule:

`iptables -t nat -A POSTROUTING -o lxdbr0 -s 10.54.20.0/24 -p tcp -m multiport --dports 80 -j SNAT --to-source 10.7.0.202 `

For traffic from the lxd net to lxdbr0 to port 80, change the source address to host ip. Like that, traffic from outside keep their original source address.

All rules:

```
# Generated by iptables-save v1.6.0 on Fri Jun  3 16:06:30 2016
*mangle
:PREROUTING ACCEPT [15765:22772727]
:INPUT ACCEPT [4551:359679]
:FORWARD ACCEPT [11214:22413048]
:OUTPUT ACCEPT [3558:1482804]
:POSTROUTING ACCEPT [14758:23894628]
-A POSTROUTING -o lxdbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
COMMIT
# Completed on Fri Jun  3 16:06:30 2016
# Generated by iptables-save v1.6.0 on Fri Jun  3 16:06:30 2016
*nat
:PREROUTING ACCEPT [103:17480]
:INPUT ACCEPT [103:17480]
:OUTPUT ACCEPT [10:868]
:POSTROUTING ACCEPT [11:928]
-A PREROUTING -d 10.7.0.202/32 -i lxdbr0 -p tcp -m multiport --dports 80 -j DNAT --to-destination 10.54.20.213:80
-A PREROUTING -i enp0s3 -p tcp -m multiport --dports 80 -j DNAT --to-destination 10.54.20.213:80
-A OUTPUT -o lo -p tcp -m multiport --dports 80 -j DNAT --to-destination 10.54.20.213:80
-A POSTROUTING -s 10.54.20.0/24 ! -d 10.54.20.0/24 -j MASQUERADE
-A POSTROUTING -s 10.54.20.0/24 -o lxdbr0 -p tcp -m multiport --dports 80 -j SNAT --to-source 10.7.0.202
COMMIT
# Completed on Fri Jun  3 16:06:30 2016
# Generated by iptables-save v1.6.0 on Fri Jun  3 16:06:30 2016
*filter
:INPUT ACCEPT [4520:356540]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [3544:1481580]
-A INPUT -i lxdbr0 -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -i lxdbr0 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i lxdbr0 -p tcp -m tcp --dport 67 -j ACCEPT
-A INPUT -i lxdbr0 -p udp -m udp --dport 67 -j ACCEPT
-A FORWARD -o lxdbr0 -j ACCEPT
-A FORWARD -i lxdbr0 -j ACCEPT
COMMIT
# Completed on Fri Jun  3 16:06:30 2016
```
