### ISSUE TITLE
API : change the profile of a conatainer

### ISSUE THREAD

**Issue by tozaz** [lxc/lxd#2077]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 15.10
 * The output of "lxc info"
`lxc info
apicompat: 0
auth: trusted
environment:
  addresses:
  - 192.168.0.240:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIGFTCCA/2gAwIBAgIRANcAwrUd1PEbZbGNKfziMnIwDQYJKoZIhvcNAQELBQAw
    NjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEB0
    ZXN0aG9zdDAeFw0xNjA0MjkxODIwMTVaFw0yNjA0MjcxODIwMTVaMDYxHDAaBgNV
    BAoTE2xpbnV4Y29udGFpbmVycy5vcmcxFjAUBgNVBAMMDXJvb3RAdGVzdGhvc3Qw
    ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC0FaSdWd9oA51tHy/vYUsM
    XPlGUkNbaaAuGcAhigNeRhgj8ipepAFvNOC+1yPD9a7mJlUCoeou/+sBgUH75WPE
    W1Lz/tMSyeevzSszPxgYGGPX4RDOkvqV+Qgq8te56xuenCs0UJZSl1qiyVwfyJyO
    +q5p8vdb8L/3YQM8hSrWntWbRifxAKP10/+Nbq5lqQA/mtv6CLr230V6vH0HMZSN
    uIpDt1onBLJTqtYgywumcZNiWb+DVJxBnZW/hxlP1fJAGMjEDe1feCvN5pHeknpC
    aBR3rwg7lH58BxQBD44AU4jnt/7nlPnnqbk+/QTz9qHxl9xLJ4ttr9bdEt21quoZ
    fnGD9tjSo+eMomRDPAZpXyLSF7WiWzlwMXmyj2g7ZSq3NSQjGidBROWes7ESu9mr
    f02OOyIY+HVXLk/xNMINsGr0EXDEkeGu6WXdVzllgI7u8sWnsrjr4capvYwEFUpJ
    rSBfhaeJMkYUSgAgWCgOmNw7KKIqVhYoYuTcyjdEDgf/6EHdogxH6OcmDWx9sE4i
    jHKhxCGCSFrsBosGT/ZEIJwognFY5TDFIgQBqDJPEM6Rr+YDxIGhL5WJhOWafPTY
    hVS7jRrqcPnbfNFrZsYlinXIw1i2csY2NRE0C6vsuuXf146UTnTGQrSV75ugjgNS
    30VI2eziOWtEDdHX9rxHFQIDAQABo4IBHDCCARgwDgYDVR0PAQH/BAQDAgWgMBMG
    A1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwgeIGA1UdEQSB2jCB14II
    dGVzdGhvc3SCHGZlODA6OmJhOTc6NWFmZjpmZTBkOjU5ZDIvNjSCEDE5Mi4xNjgu
    MC4yNDAvMjSCKDJhMDE6ZTM1OjJmMzE6MWU3MDpjNTY3OjEzMzg6MTJiOjllNjEv
    NjSCKTJhMDE6ZTM1OjJmMzE6MWU3MDpiYTk3OjVhZmY6ZmUwZDo1OWQyLzY0ghxm
    ZTgwOjpiYTk3OjVhZmY6ZmUwZDo1OWQyLzY0ghxmZTgwOjozMGQ5OjhhZmY6ZmU2
    Njo3NDViLzY0ggpmZTgwOjoxLzY0MA0GCSqGSIb3DQEBCwUAA4ICAQAZ+hzAexjH
    dfXLdS7DDME4qjy9hs2PkYxTNI1phbU5UTBA08RzrQjKfplnmmkiW+3kYLy5UDGo
    bGO/ZdpxMugZf73Cltpry7Hjxgazogfz714xtSDKnp0Yf3wlIvytjHTfVXZIUWyw
    6L1HirWyikVRb9IJRtOI/9HaSjrASfrZCy8PGyAhyxNgaIb7CZD7ecF/HoEmRJFb
    iKOYbha05RUroia9ko/LvU9a6mALUmACNo5gQyvi81Rd6yLK/FLEQJKCYUzd9pL3
    YDZehiEdWj+Oi+GS2wjXJqgSaTwj73qo54dTz4YApQxisM0wKAHQRhYOvzohTZ2f
    6AM2DUO4ylUbl+CWgBGoZXztj9ehGNNfblKHVo2I+/X/8mkUNzjSGEN0MRuR6BHZ
    WR4SAYHLxdjwab/TTKETSndvtSvN9ede/AA1uwFgHcp32aUGiJOqKAQK6e+t2wRF
    6SjyDM2LlK9SbRnYv+IlAqQaUg4UDsADUjZligRLZWJGrE+QsaknaiItkhh7du3Z
    yrTHCnY5pbbXsBvt8jM6FZZgO8gnBKmG8z252H0DIwj15JLQiFkCvKQxs2eg5gjl
    NS40AUvPa0PgwZ0sl29gNFmDDpmKcvb0DE2Cs6ceZxlYu/S3fJRc5wW/JWrYo9BM
    opDPZ+tzWnwR6at7wsGNUWXPakhVs87Y9w==
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 1413
  serverversion: 2.0.1
  storage: zfs
  storageversion: "5"
config:
  core.https_address: 192.168.0.240:8443
  core.trust_password: true
  storage.zfs_pool_name: zfspool
public: false`
   * Storage backend in use: ZFS

# Issue description

I can't manage to  change/apply a profile of a container with the API, I have 2 profiles that exist (default) and (newprofile)

# Steps to reproduce

 1. `curl -k --cert client.pem --key client.key https://192.168.0.240:8443/1.0/containers/test
{"type":"sync","status":"Success","status_code":200,"metadata":{"architecture":"x86_64","config":{"volatile.base_image":"950fa0cf35a1fc499738521be1c6584fe081d800caa137739d9f216c4637b3d3","volatile.eth0.hwaddr":"00:16:3e:84:b5:8a","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"created_at":"2016-06-02T09:36:50Z","devices":{},"ephemeral":false,"expanded_config":{"limits.cpu":"2","limits.cpu.priority":"1","limits.disk.priority":"2","limits.memory":"256MB","limits.memory.swap.priority":"1","limits.network.priority":"1","volatile.base_image":"950fa0cf35a1fc499738521be1c6584fe081d800caa137739d9f216c4637b3d3","volatile.eth0.hwaddr":"00:16:3e:84:b5:8a","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"expanded_devices":{"eth0":{"name":"eth0","nictype":"macvlan","parent":"br0","type":"nic"},"kvm":{"path":"/dev/kvm","type":"unix-char"},"root":{"path":"/","size":"5GB","type":"disk"},"tun":{"path":"/dev/net/tun","type":"unix-char"}},"name":"test","profiles":["default"],"stateful":false,"status":"Running","status_code":103}}`
 2. `curl -X PUT -d '{"profiles": ["newprofile"]}' -k --cert client.pem --key client.key https://192.168.0.240:8443/1.0/containers/test
{"type":"async","status":"Operation created","status_code":100,"metadata":{"id":"6068b043-026c-410d-82db-7995dc610b4c","class":"task","created_at":"2016-06-02T23:41:57.029721154+02:00","updated_at":"2016-06-02T23:41:57.029721154+02:00","status":"Running","status_code":103,"resources":{"containers":["/1.0/containers/test"]},"metadata":null,"may_cancel":false,"err":""},"operation":"/1.0/operations/6068b043-026c-410d-82db-7995dc610b4c"}`
 3. curl -k --cert client.pem --key client.key https://192.168.0.240:8443/1.0/containers/test
`{"type":"sync","status":"Success","status_code":200,"metadata":{"architecture":"x86_64","config":{"volatile.base_image":"950fa0cf35a1fc499738521be1c6584fe081d800caa137739d9f216c4637b3d3","volatile.eth0.hwaddr":"00:16:3e:84:b5:8a","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"created_at":"2016-06-02T09:36:50Z","devices":{},"ephemeral":false,"expanded_config":{"limits.cpu":"2","limits.cpu.priority":"1","limits.disk.priority":"2","limits.memory":"256MB","limits.memory.swap.priority":"1","limits.network.priority":"1","volatile.base_image":"950fa0cf35a1fc499738521be1c6584fe081d800caa137739d9f216c4637b3d3","volatile.eth0.hwaddr":"00:16:3e:84:b5:8a","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]"},"expanded_devices":{"eth0":{"name":"eth0","nictype":"macvlan","parent":"br0","type":"nic"},"kvm":{"path":"/dev/kvm","type":"unix-char"},"root":{"path":"/","size":"5GB","type":"disk"},"tun":{"path":"/dev/net/tun","type":"unix-char"}},"name":"test","profiles":["default"],"stateful":false,"status":"Running","status_code":103}}`

Thanks.

**Comment by tych0** [comment]
Try waiting on the operation ID that you get back and see what error it gives you, that may be instructive.

That said, I think what you're really looking for is the http method PATCH, not PUT. However, PATCH is unimplemented right now, so your best bet is to GET the container's config, make the changes you want, and then PUT the full result back.

**Comment by tozaz** [comment]
I am right if I understand that if I GET /1.0/containers/test then change the profile into the json then PUT /1.0/containers/test should do what I want ?

So just send a json file with just the profile can't works, I have to PUT the complete result of GET /1.0/containers/test ?

I will look at operation too.
Thanks

**Comment by tozaz** [comment]
Hum, That's works, but I will need to wait for the PATCH method. Any timeline for the PATCH method
?

Thanks you.

**Comment by tych0** [comment]
Not high on our list right now, but it shouldn't be hard to do if you want to send a patch yourself.

**Comment by tozaz** [comment]
Thanks for your answer, but sorry I am not very familiar with goland.
