### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by zulcss** [lxc/lxd#2080]
INFO[06-03|15:49:33] handling                                 method=GET url=/1.0/operations/b088d9ee-f4f1-499b-9625-e44fce6b37cc/wait ip=@ 
DBUG[06-03|15:49:33] ContainerStop                            driver=storage/zfs container=instance-0000001c
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x43d4ec]

goroutine 2952 [running]:
panic(0xab02c0, 0xc82000e0f0)
        /usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
main.(*containerLXC).tarStoreFile(0xc8202ee000, 0xc820340990, 0x2a, 0xc82008e000, 0xc82029f960, 0x6f, 0x0, 0x0, 0x0, 0x0)
        /build/lxd-ma7bPQ/lxd-2.0.2/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/container_lxc.go:3236 +0x6c
main.(*containerLXC).Export.func1(0xc82029f960, 0x6f, 0x0, 0x0, 0x7fac753fcb78, 0xc820340240, 0x0, 0x0)
        /build/lxd-ma7bPQ/lxd-2.0.2/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/container_lxc.go:2617 +0x8d
path/filepath.walk(0xc82029efc0, 0x61, 0x7fac753fcba0, 0xc82030f930, 0xc8200d3950, 0x0, 0x0)
        /usr/lib/go-1.6/src/path/filepath/path.go:370 +0x415
path/filepath.walk(0xc820558960, 0x56, 0x7fac753fcba0, 0xc82030f2b0, 0xc8200d3950, 0x0, 0x0)
        /usr/lib/go-1.6/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc82017a730, 0x4e, 0x7fac753fcba0, 0xc82044cdd0, 0xc8200d3950, 0x0, 0x0)
        /usr/lib/go-1.6/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc820354600, 0x40, 0x7fac753fcba0, 0xc82044cc30, 0xc8200d3950, 0x0, 0x0)
        /usr/lib/go-1.6/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc8203f5600, 0x38, 0x7fac753fcba0, 0xc820557930, 0xc8200d3950, 0x0, 0x0)
        /usr/lib/go-1.6/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc820499240, 0x34, 0x7fac753fcba0, 0xc8202ec750, 0xc8200d3950, 0x0, 0x0)
        /usr/lib/go-1.6/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc820340b10, 0x30, 0x7fac753fcba0, 0xc820557790, 0xc8200d3950, 0x0, 0x0)
        /usr/lib/go-1.6/src/path/filepath/path.go:374 +0x4fc
path/filepath.Walk(0xc820340b10, 0x30, 0xc8200d3950, 0x0, 0x0)
        /usr/lib/go-1.6/src/path/filepath/path.go:396 +0xe1
main.(*containerLXC).Export(0xc8202ee000, 0x7fac753fc358, 0xc82017e148, 0x0, 0x0)
        /build/lxd-ma7bPQ/lxd-2.0.2/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/container_lxc.go:2704 +0xc4e
main.imgPostContInfo(0xc82000cc80, 0xc8201ee460, 0x0, 0x0, 0x0, 0xc8202b2720, 0xc8202b2750, 0x0, 0xc8202b2690, 0x27, ...)
        /build/lxd-ma7bPQ/lxd-2.0.2/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/images.go:227 +0x45e
main.imagesPost.func2(0xc8200c2160, 0x0, 0x0)
        /build/lxd-ma7bPQ/lxd-2.0.2/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/images.go:709 +0x574
main.(*operation).Run.func1(0xc8200c2160, 0xc8201fe660)
        /build/lxd-ma7bPQ/lxd-2.0.2/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/operations.go:110 +0x3a
created by main.(*operation).Run
        /build/lxd-ma7bPQ/lxd-2.0.2/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/operations.go:137 +0x127

**Comment by tych0** [comment]
So this points to,
https://github.com/lxc/lxd/blob/65928918fe72633e6ede2c37a6a841b3e65995a8/lxd/container_lxc.go#L2616

which I think means that the file info we got from filepath.Walk was nil, which seems like something in the stdlib is Really Broken. Do you have a reproducer for this?

**Comment by stgraber** [comment]
That was two months ago, lets close this. We can re-open should @zulcss get a reproducer on current stable.
