### ISSUE TITLE
Honor boot.autostart.priority when stopping lxd service

### ISSUE THREAD

**Issue by JohnstonJ** [lxc/lxd#2082]
Currently, it appears that `boot.autostart.priority` is only used when starting lxd.  It would be useful to have this priority be honored when stopping lxd.  lxd would wait for all containers at a given priority level to stop before asking the next priority level of containers to stop.

This would be useful if a service in one container is dependent on a service in another container.  Currently, the existing `boot.autostart` options can be used to make this happen.  But shutdown isn't clean, because those options don't affect shutdown.  By controlling the order of container shutdown, we can make sure that the dependent container is completely stopped before stopping the first container.

Some variations of the scheme to consider:
- Introduce a new `boot.stop.priority` or similar option instead, which defaults to the value of `boot.autostart.priority` - this way there can be different start & stop priorities.
- Add a global lxd option to control whether to honor stop priorities, for compatibility reasons.

Here we can see the sorting of containers by priority when starting lxd: https://github.com/lxc/lxd/blob/2beafc073e5723f669da1dfd81714a2a0175b31b/lxd/containers.go#L104

Here we can see the stopping of containers; note there is no sorting: https://github.com/lxc/lxd/blob/2beafc073e5723f669da1dfd81714a2a0175b31b/lxd/containers.go#L135

**Comment by JohnstonJ** [comment]
To workaround the absence of this feature, I made this systemd template unit named `lxd-priority-stop@.service`.  Any container enabled by this unit will be stopped before the rest of the containers.  It's kind of a hack and doesn't support multiple priority levels:

```
[Unit]
Description=Prioritized shutdown for %I
Requires=lxd-containers.service
After=lxd-containers.service

[Install]
WantedBy=multi-user.target

[Service]
Type=oneshot
RemainAfterExit=yes
# Don't call lxc start because that would disrespect
# boot.autostart.delay/priority settings.
ExecStart=/bin/true
ExecStop=/usr/bin/lxc stop %I
```

**Comment by stgraber** [comment]
Not convinced that this qualifies as a bug nor that we'd want that kind of behavior to be the default.

In most cases we want the whole system to be brought down as quickly as possible, shutting down all the containers at once is the best way to achieve this.

Shutting them down by chunks would significantly increase the shutdown time in some cases, quite possibly past the shutdown budget that's given by the init system, causing all the containers to be SIGKILLED instead, possibly loosing data in the process. Or worse, the system may have been brought down due to a UPS battery warning, where holding shutdown for a long period of time would cause the whole system to loose power.

**Comment by stgraber** [comment]
Staged bring up does make sense because you may have boot time services that would get stuck or fail if not brought up in order. At shutdown, what we want is for all processes to be killed cleanly so they can flush their data to disk and do so as fast as possible so the host can itself go down.

**Comment by JohnstonJ** [comment]
> In most cases we want the whole system to be brought down as quickly as possible, shutting down all the containers at once is the best way to achieve this.

In general yes, but dependencies should be honored.  E.g. systemd shuts down system services in parallel, while honoring dependencies - you therefore get a fast _and correct_ shutdown.  A particularly bad situation would be if the dependent container waits a long time with a timeout to communicate with the first container, which already shut down (whereas correct shutdown might be much faster).  Or, imagine if you have a database in one container and an application in another in some small deployment - maybe we might want to safely shut down the application first, and then the database, lest some in-flight data be lost.

> Shutting them down by chunks would significantly increase the shutdown time in some cases, quite possibly past the shutdown budget that's given by the init system

That can be fixed.  libvirt had a similar shutdown problem and their solution was to disable the systemd stop timeout.  You can see the commit here - also there are some links in the commit to longer discussions about the issue: libvirt-guests: Disable shutdown timeout - https://github.com/libvirt/libvirt/commit/ba08d16d6cec81656b333435650aef36a012034c

That makes sense to me, since the containers (or virtual machines, in libvirt's case) have their own shutdown timeouts attached to them.  At the very least, the system administrator could trivially modify the systemd service themselves to set an appropriate timeout for lxd-containers.service.

> UPS battery warning, .... would cause the whole system to loose power

Then maybe the sysadmin should not be so stupid as to set lengthy timeouts on a series of containers along a critical dependency path, if the UPS battery will not last long?

> Staged bring up does make sense because you may have boot time services that would get stuck or fail if not brought up in order.

By the same logic, shouldn't they be stopped in the reverse order?
