### ISSUE TITLE
lxd init won't use existing ZFS pool

### ISSUE THREAD

**Issue by tlc** [lxc/lxd#2088]
Ubuntu 16.04
lxc version 2.0.2

I previously had lxd working with a zfs pool created by lxd and **named lxdpool**.
I want lxd to use another, existing pool.
I removed all containers and images, apt-get purged and reinstalled lxd, and destroyed lxdpool.
But there is apparently still a reference to lxdpool somewhere.

$ sudo zpool list
NAME    SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
pool1  2.72T  1.33T  1.39T         -     5%    49%  1.00x  ONLINE  -
$ **sudo lxd init**
Name of the storage backend to use (dir or zfs): zfs
Create a new ZFS pool (yes/no)? no
**Name of the existing ZFS pool or dataset: pool1**
Would you like LXD to be available over the network (yes/no)? no
Do you want to configure the LXD bridge (yes/no)? no
error: Error checking if a pool is already in use: Failed to list ZFS filesystems: cannot open '**lxdpool**': dataset does not exist

**Comment by tych0** [comment]
As a workaround, you can delete /var/lib/lxd after purging it and that should get rid of any references.

**Comment by tlc** [comment]
Thanks, after I posted I spotted the lxd.db.  I moved it and reinstalled lxd and then init worked.

**Comment by stgraber** [comment]
It's not that it won't use your existing zfs pool, it's that it was configured to use another pool which you apparently destroyed before cleaning up LXD :)

**Comment by tlc** [comment]
Which lxd command "cleans up"?  Shouldn't apt-get purge remove any remaining traces of an lxd config?

**Comment by stgraber** [comment]
What you should have done is destroy any container and image you had and then unset storage.zfs_pool_name prior to destroying the ZFS pool.

We probably should look into removing everything on package purge, though I've refrained from doing so thus far in fear that "apt-get install --purge some-package" where some-package somehow conflicts with LXD would remove lxd and all your containers without you noticing...
