### ISSUE TITLE
Easy way to get server fingerprint

### ISSUE THREAD

**Issue by suutari** [lxc/lxd#2098]
Is there an easy way to get fingerprint of LXD server's certificate?

I have LXD 2.0.2. This is currently the "easiest" way I've found:
```
lxc info | sed -n '/---BEGIN CERT/,/---END CERT/s/^ *//;p' | openssl x509 -noout -fingerprint -sha256
```

It would also be very useful if the `lxc remote add` command would tell such command in its output. (I don't think anyone will check the fingerprint if they don't know how to see it.) E.g.:

```
$ lxc remote add some-remote 1.2.3.4
Certificate fingerprint: 
ed00df4a9793412f89e7bb52c201dfac1641fdacb2783d18b22a8b4268fc842a

Run following command on the remote server to see its fingerprint:
    lxc info --fingerprint

ok (y/n)?
```

**Comment by suutari** [comment]
@stgraber: Hey, nice! Thanks for implementing this! :smile:

**Comment by ogai** [comment]
@stgraber  Trying to check the fingerprint manually after issuing in my laptop:

    lxc remote add <name> <ip>

The command above shows:

    Certificate fingerprint: <a long decimal number>
    ok (y/n)?

However, `lxc info` on the server shows

    certificatefingerprint: <an hexadecimal long number, lowercase, without colons>

Both systems are running Ubuntu 16.04. How are you supposed to check certificate matching?!

**Comment by stgraber** [comment]
@ogai yes, that's a bug which was fixed in LXD 2.14 and LXD 2.0.10, a format string got messed up and the fingerprint was shown in decimal form rather than hexadecimal which made comparing a bit difficult.

**Comment by ogai** [comment]
@stgraber Ubuntu Xenial has 2.0.9 at the time of writing: Mo 5. Jun 09:23:57 CEST 2017. Is it getting 2.0.10 soon? Otherwise, I wonder how can one of the strings be converted to match the other.

**Comment by suutari-ai** [comment]
Try
```sh
echo 623365...83433 | xxd -r -p
```
as suggested in https://github.com/lxc/lxd/issues/3293#issuecomment-300099477

**Comment by stgraber** [comment]
@ogai yes, I uploaded it but it's waiting for review by the SRU team. Once reviewed, it's going to sit for 7 days in xenial-proposed before being released to xenial-updates. That's all assuming that no regressions are found.
