### ISSUE TITLE
lxd copy doesn't change hostnames

### ISSUE THREAD

**Issue by sokoow** [lxc/lxd#2103]
Why is lxc copy command not changing internal container hostnames ? lxc-clone used to do it..

**Comment by simos** [comment]
You do not follow the template and it is not clear what you mean.

The /etc/hosts content is not adapted when you copy containers, etc.

**Comment by sokoow** [comment]
Apologies for not follwing the template.

What I mean is that in lxc, when you were doing lxc-clone on a container with a new name, /etc/hostname was being updated. With LXD this is only true when you create a new container, lxd copy command to a new name doesn't update the container hostname. This is very important if you run dynamic ip updates in dhcp. Thanks for looking into this.

**Comment by simos** [comment]
I just tried it on my computer and it works.
Specifically, I had a container "c1" and I run

`lxc copy c1 c2
`
Then, 

```
$ cat /var/lib/lxd/containers/c2.zfs/rootfs/etc/hostname
c2
$ _

```

Something wrong is specific to your case and causes the problem. 

You can still follow the template, if you want to have this resolved. You can edit the initial post and provide the list of information that is mentioned in the template.

**Comment by sokoow** [comment]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: 
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-24-generic
  server: lxd
  serverpid: 2994
  serverversion: 2.0.2
  storage: dir
  storageversion: ""
config: {}
public: false


# Issue description

upon copying the container, hostnames aren't changed to new container name

# Steps to reproduce

 1. lxc create ubuntu:16.04 first
 2. lxc start first && lxc stop first
 3. lxc copy first second
 4. cat /var/lib/lxd/containers/second/rootfs/etc/hostname = first


# Information to attach

strange thing is that logs say:

            lxc 20160612165326.074 INFO     lxc_conf - conf.c:setup_utsname:843 - 'second' hostname has been setup

**Comment by stgraber** [comment]
So that's actually expected behavior, in that the image you're using (ubuntu:16.04) has in its metadata that the cloud-init information should only be written at initial create and not on copy.

**Comment by stgraber** [comment]
Hmm, actually, no, this was fixed.

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc launch ubuntu:16.04 first
Creating first
Starting first
stgraber@castiana:~$ lxc copy first second
stgraber@castiana:~$ lxc file pull first/etc/hostname -
first
stgraber@castiana:~$ lxc file pull second/etc/hostname -
first
stgraber@castiana:~$ lxc start second
stgraber@castiana:~$ lxc file pull second/etc/hostname -
second
```

So the hostname does change as it should. But since Ubuntu uses cloud-init, you need to start the container for the change to happen.
