### ISSUE TITLE
Regression: lxd-containers.service now dies with "error: open /var/lib/lxd/containers: no such file or directory" on otherwise-clean Ubuntu 16.04 installation

### ISSUE THREAD

**Issue by JohnstonJ** [lxc/lxd#2104]
# Required information

 * Distribution: Ubuntu 16.04 LTS
 * The output of "lxc info":

```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    <snip>
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-21-generic
  server: lxd
  serverpid: 2052
  serverversion: 2.0.2
  storage: dir
  storageversion: ""
config: {}
public: false
```

# Issue description

The `lxd-containers.service` service fails on a clean install of Ubuntu 16.04 that has been upgraded to latest packages.

# Steps to reproduce

1. Do a clean install of Ubuntu 16.04 server.  Note this installed lxd package version `2.0.0-0ubuntu4`.
1. Note that `systemctl status lxd-containers.service` reports that it started successfully with no errors.
1. Upgrade lxd:
```
$ sudo apt-get update
$ sudo apt-get install lxd
$ dpkg -s lxd
Version: 2.0.2-0ubuntu1~16.04.1
```
1.  Observe that the `lxd-containers.service` no longer starts successfully:
```
$ sudo systemctl status lxd-containers.service
   Active: failed (Result: exit-code) since Sat 2016-06-11 15:57:37 CDT; 1min 6s ago
Jun 11 15:57:37 lxderror lxd[1908]: error: open /var/lib/lxd/containers: no such file or directory
Jun 11 15:57:37 lxderror systemd[1]: lxd-containers.service: Main process exited, code=exited, status=1/FAILURE
Jun 11 15:57:37 lxderror systemd[1]: Failed to start LXD - container startup/shutdown.
```

While no doubt easy to work around this issue, it's a reasonable expectation that a clean Ubuntu install should boot without any services failing on startup after a simple `apt-get upgrade` is done post-installation.

**Comment by simos** [comment]
The reported issue is ``error: open /var/lib/lxd/containers: no such file or directory``
which means that this directory is merely missing. 
A possible workaround might be a ``sudo mkdir -p /var/lib/lxd/containers``.
Still, the installation process should make that directory.

Did you run ``sudo lxd init`` at the start, and select whether you want ``dir`` or ``zfs``?

**Comment by stgraber** [comment]
This was fixed upstream already. It was a regression from the recent security fix...

The issue only seems to hit very few folks so we haven't rushed a fix yet. If you do hit that, a "mkdir /var/lib/lxd/containers" should take care of it.

LXD 2.0.3 will have the fix.

**Comment by JohnstonJ** [comment]
@stgraber Cool; apologies for raising this.

**Comment by chappjc** [comment]
I have an AWS instance that is unrecoverable.  This seems like a major issue for headless systems.
