### ISSUE TITLE
 Cannot create a container with the specific alias "tasks"

### ISSUE THREAD

**Issue by simos** [lxc/lxd#2105]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 15.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.2.0-38-generic
   * LXC version: 2.0.1
   * LXD version: 2.0.2
   * Storage backend in use: zfs

# Issue description

When trying to launch a container with the specific alias "tasks", it fails to launch.

# Steps to reproduce

 1. Run  "lxc launch ubuntu:x tasks"
 2. The output is
Creating tasks
Starting tasks
error: Error calling 'lxd forkstart tasks /var/lib/lxd/containers /var/log/lxd/tasks/lxc.conf': err='exit status 1'
Try `lxc info --show-log tasks` for more info
Exit 1

# Explanation

The reason is that in /sys/fs/cgroup/systemd/lxc/ there is already a sysfs file called "tasks". In that directory, any new container is created as a new directory that has their alias as their name.
Since "tasks" is reserved", lxc fails to create the directory and fails to continue.

Here are the contents of the directory
$ ls -l /sys/fs/cgroup/systemd/lxc/
total 0
drwxrwxr-x 5 root 165536 0 Ιούν 10 12:32 c1
-rw-r--r-- 1 root root 0 Ιούν 10 12:53 cgroup.clone_children
-rw-r--r-- 1 root root 0 Ιούν 10 12:53 cgroup.procs
-rw-r--r-- 1 root root 0 Ιούν 10 12:53 notify_on_release
-rw-r--r-- 1 root root 0 Ιούν 10 12:53 tasks

Currently, there is only potential conflict with "tasks" as the other filenames are invalid hostnames (contain dots or underscores).
Presumably in the future there might be more such files.

Among the solutions,
1. the container directories in /sys/fs/cgroup/systemd/lxc/ should have something like ".lxd" appended to them so that there is no future conflict.

**Comment by stgraber** [comment]
Can you file this against github.com/lxc/lxc instead?

LXD doesn't pick the cgroup name, it's done by the LXC library (and github doesn't let us move issues between repos...).

**Comment by simos** [comment]
Done, it's at https://github.com/lxc/lxc/issues/1046
