### ISSUE TITLE
Ram report is incorrect.

### ISSUE THREAD

**Issue by loru** [lxc/lxd#2108]
# Required information

 * Distribution: Ubuntu 16.04
 * Distribution version: Ubuntu 16.04
   * Kernel version: 4.4.0-22-generic
   * LXD version: 2.0.2
   * Storage backend in use: ZFS

# Issue description

When a container is created, the ram reported in htop is alright, for example 4MB out of 256MB.

![screen shot 2016-06-06 at 5 04 59 pm](https://cloud.githubusercontent.com/assets/19887885/15990525/31bb1c1c-3095-11e6-8a1e-4dbe61a55d91.png)

But after some time, the ram report becomes incorrect:

![screen shot 2016-06-06 at 5 05 26 pm](https://cloud.githubusercontent.com/assets/19887885/15990527/428d33c2-3095-11e6-9ff7-faa401f6fb3b.png)

Container's meminfo:

```
MemTotal:         524288 kB
MemFree:          404444 kB
MemAvailable:     404444 kB
Buffers:               0 kB
Cached:           115540 kB
SwapCached:            0 kB
Active:           829940 kB
Inactive:         137444 kB
Active(anon):     110492 kB
Inactive(anon):    65644 kB
Active(file):     719448 kB
Inactive(file):    71800 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                56 kB
Writeback:             0 kB
AnonPages:         88216 kB
Mapped:            76532 kB
Shmem:             87872 kB
Slab:               0 kB
SReclaimable:     101908 kB
SUnreclaim:       701924 kB
KernelStack:       11440 kB
PageTables:         6332 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     1983828 kB
Committed_AS:     643708 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:     26624 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      146020 kB
DirectMap2M:     3973120 kB

```

# Steps to reproduce

1. lxc create ubuntu:16.04 [your-container]
2. Wait for one or two days.
3. Run htop in the container.

Could it be a htop bug instead? In this case, sorry I opened an issue here.

**Comment by simos** [comment]
It says 16.0Z, would that be Zetabytes?
If you restart ``htop``, does it show a saner value? If you restart ``htop`` and you get a proper value, then it probably is a bug in that program.

If you have ``htop`` running in the background for several days, most probably it is a bug in htop. It might get a negative value on an unsigned int.

**Comment by loru** [comment]
Zettabytes? As in Terabytes of Terabytes? I don't think so.

It's not after hours, it's just directly when I run htop. Sometimes it appears right after I start the container. If you think it is an htop bug then I'm going to close this issue.

**Comment by stgraber** [comment]
It's most likely a lxcfs issue. It'd be good if you could catch the problem when it shows up in /proc/meminfo and file a bug at github.com/lxc/lxcfs

I'm closing the LXD issue as we only set limits (which worked in this case), the consumption reporting is done through the lxcfs overlay.
