### ISSUE TITLE
pam/ldap problems

### ISSUE THREAD

**Issue by sokoow** [lxc/lxd#2111]
**Required info**
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-24-generic
  server: lxd
  serverpid: 1981
  serverversion: 2.0.2
  storage: dir
  storageversion: ""
config: {}
public: false

Distribution: Ubuntu Xenial

**Issue description**

After configuring ldap/sssd inside lxd container, I'm getting following errors in auth.log:
```
Jun 13 02:05:39 xenial-template sshd[390]: Accepted password for sokoow from 10.21.34.100 port 37532 ssh2
Jun 13 02:05:39 xenial-template sshd[390]: pam_keyinit(sshd:session): Unable to change GID to 99000 temporarily
Jun 13 02:05:39 xenial-template sshd[390]: pam_unix(sshd:session): session opened for user sokoow by (uid=0)
Jun 13 02:05:39 xenial-template sshd[390]: pam_motd(sshd:session): pam_modutil_drop_priv: change_gid failed: Success
Jun 13 02:05:39 xenial-template sshd[390]: pam_motd(sshd:session): Unable to change UID to 10003 temporarily
Jun 13 02:05:39 xenial-template sshd[390]: pam_motd(sshd:session): pam_modutil_regain_priv: called with invalid state
Jun 13 02:05:39 xenial-template sshd[390]: pam_motd(sshd:session): Unable to change UID back to -1
Jun 13 02:05:39 xenial-template sshd[390]: pam_motd(sshd:session): pam_modutil_drop_priv: change_gid failed: Success
Jun 13 02:05:39 xenial-template sshd[390]: pam_motd(sshd:session): Unable to change UID to 10003 temporarily
Jun 13 02:05:39 xenial-template sshd[390]: pam_motd(sshd:session): pam_modutil_regain_priv: called with invalid state
Jun 13 02:05:39 xenial-template sshd[390]: pam_motd(sshd:session): Unable to change UID back to -1
Jun 13 02:05:39 xenial-template sshd[390]: pam_mail(sshd:session): pam_modutil_drop_priv: change_gid failed: Success
```
this works fine in lxc.

**Comment by stgraber** [comment]
That's because the unprivileged container only has uid 0 through 65536 mapped so uid 99000 doesn't exist.

I'm assuming this is working for you with LXC because you're using privileged containers or because you configured a bigger id map in /etc/subuid or /etc/subgid.

**Comment by sokoow** [comment]
How can I change the mapping in lxd? Is it through lxc raw?

**Comment by stgraber** [comment]
Edit /etc/subuid and /etc/subgid and grow the allocation of the lxd and root user (should be the same map for both).

**Comment by stgraber** [comment]
lxd:1000000:1000000
root:1000000:1000000

That's what I've got on my main server (and I'm also using sssd in my containers)

**Comment by stgraber** [comment]
Oh, note that the map I gave you above is very likely to begin at a completely different place than your existing one. This is fine if you don't have any existing containers on your system, but if you do have some containers already, make sure that the beginning of the map (first number) matches your existing one.

**Comment by sokoow** [comment]
that works just fine, thank you :)
