### ISSUE TITLE
Deadlock when direct importing multiple images simultaneously

### ISSUE THREAD

**Issue by dacohen** [lxc/lxd#2114]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04 "Trusty"
 * The output of "lxc info" or if that fails:
apicompat: 0  
auth: trusted  
environment:  
  addresses: []  
  architectures:  
  - x86_64  
  - i686  
  driver: lxc  
  driverversion: 1.1.4  
  kernel: Linux  
  kernelarchitecture: x86_64  
  kernelversion: 3.13.0-88-generic  
  server: lxd  
  serverpid: 2032  
  serverversion: 2.0.0.beta4  
  storage: dir  
  storageversion: ""  
config: {}  
public: false  

# Issue description

If there are many privileged containers running on the same host, and a direct import (i.e. from a URL using the LXD-Image-Hash and LXD-Image-URL Headers) of the **same** image is started at roughly the same time on two or more of these containers, they deadlock, reaching a state where each lxd instance thinks another one is currently downloading the image. Thus, no image is downloaded, and all the lxc image import commands hang indefinitely.

It would be convenient to be able to download the same image in multiple privileged containers without having to worry about deadlocking.

# Steps to reproduce

 1. Launch two or more privileged containers
 2. Direct import the same image in both containers simultaneously

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)  
t=2016-06-13T17:24:13+0000 lvl=info msg=handling method=GET url=/1.0/operations/30ed6fbd-60b3-4f19-931c-780ce48de391/wait ip=@  
t=2016-06-13T17:24:13+0000 lvl=info msg="Image not in the db, downloading it" image=#HASH# server=#URL#  
t=2016-06-13T17:24:13+0000 lvl=info msg="Already downloading the image, waiting for it to succeed" image=#HASH#  
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
Hmm. looking at the code, I don't see how it's possible to have both of them think the other is already downloading.

The potential race I see is that both of them may start downloading the image but that's the opposite of what you're reporting.

You log also shows the expected logging entries for the second request being held while the first is downloading.

**Comment by stgraber** [comment]
You also appear to be running a rather old LXD, you may want to update to 2.0.2.

**Comment by dacohen** [comment]
I upgraded my system to 2.0.2, and it appears the problem has been solved. Thanks for the suggestion!
