### ISSUE TITLE
error: Error calling 'lxd forkstart gitlab /var/lib/lxd/containers /var/log/lxd/gitlab/lxc.conf': err='exit status 1'

### ISSUE THREAD

**Issue by tebanep** [lxc/lxd#2121]
# Required information

 * Distribution:
Ubuntu Server 16.04
 * Distribution version:
16.04
 * The output of "lxc info":
apicompat: 0                                                                                                                              
auth: trusted                                                                                                                             
environment:                                                                                                                              
  addresses:                                                                                                                              
  - 158.69.223.54:8443                                                                                                                    
  - 10.176.111.1:8443                                                                                                                     
  architectures:                                                                                                                          
  - x86_64                                                                                                                                
  - i686                                                                                                                                  
  certificate: |                                                                                                                        
    -----BEGIN CERTIFICATE-----                                                                                                        
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-21-generic
  server: lxd
  serverpid: 3818
  serverversion: 2.0.2
  storage: zfs
  storageversion: "5"
config:
  core.https_address: 0.0.0.0:8443
  core.trust_password: true
  storage.zfs_pool_name: lxd
public: false

   * Kernel version: 
4.4.0-24-generic
   * LXC version:
 2.0.2
   * LXD version:
2.0.2
   * Storage backend in use:
ZFS

# Issue description
LXC container doesn't start anymore after calling "reboot" inside it. The only application inside it is gitlab. The following error raises:

error: Error calling 'lxd forkstart gitlab /var/lib/lxd/containers /var/log/lxd/gitlab/lxc.conf': err='exit status 1'                     
Try `lxc info --show-log gitlab` for more info

Though, when issuing a copy of the container with `lxc copy gitlab gitlab2`, the new container starts normally.
 
A brief description of what failed or what could be improved.

When 

# Steps to reproduce

Couldn't reproduce the error. When using reboot inside a brand new ubuntu:16.04 container, the container restarts and keeps on working normally.

# Information to attach

uname -a:
Linux nubark 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

lxc info --show-log gitlab:
Name: gitlab
Architecture: x86_64
Created: 2016/05/16 14:13 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20160615095115.309 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160615095115.309 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 10
            lxc 20160615095115.313 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /var/lib/lxd/containers gitlab
            lxc 20160615095115.314 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 10
            lxc 20160615095115.315 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
            lxc 20160615095115.315 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for reject_force_umount action 0
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for reject_force_umount action 0
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .[all].
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .kexec_load errno 1.
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for kexec_load action 327681
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for kexec_load action 327681
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .open_by_handle_at errno 1.
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for open_by_handle_at action 327681
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for open_by_handle_at action 327681
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .init_module errno 1.
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for init_module action 327681
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for init_module action 327681
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .finit_module errno 1.
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for finit_module action 327681
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for finit_module action 327681
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .delete_module errno 1.
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for delete_module action 327681
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for delete_module action 327681
            lxc 20160615095115.316 INFO     lxc_seccomp - seccomp.c:parse_config_v2:456 - Merging in the compat seccomp ctx into the main one
            lxc 20160615095115.316 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 3 start' for container 'gitlab', config section 'lxc'
            lxc 20160615095115.316 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160615095115.316 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 10
            lxc 20160615095115.319 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/d78a9d7e97b4b375//var/lib/lxd/containers
            lxc 20160615095115.373 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
            lxc 20160615095115.374 DEBUG    lxc_console - console.c:lxc_console_peer_default:469 - no console peer
            lxc 20160615095115.374 INFO     lxc_start - start.c:lxc_init:488 - 'gitlab' is initialized
            lxc 20160615095115.375 DEBUG    lxc_start - start.c:__lxc_start:1326 - Not dropping cap_sys_boot or watching utmp
            lxc 20160615095115.375 INFO     lxc_start - start.c:resolve_clone_flags:1013 - Cloning a new user namespace
            lxc 20160615095115.380 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160615095115.380 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160615095115.384 DEBUG    lxc_conf - conf.c:instantiate_veth:2614 - instantiated veth 'vethQ4UJEG/vethJS9WS0', index is '33'
            lxc 20160615095115.384 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for gitlab
            lxc 20160615095115.449 DEBUG    lxc_conf - conf.c:lxc_assign_network:3048 - move 'eth0' to '8576'
            lxc 20160615095115.449 NOTICE   lxc_start - start.c:do_start:777 - switching to gid/uid 0/0 in new user namespace
            lxc 20160615095115.450 ERROR    lxc_conf - conf.c:mount_rootfs:807 - No such file or directory - failed to get real path for '/var/lib/lxd/containers/gitlab/rootfs'
            lxc 20160615095115.450 ERROR    lxc_conf - conf.c:setup_rootfs:1221 - failed to mount rootfs
            lxc 20160615095115.450 ERROR    lxc_conf - conf.c:do_rootfs_setup:3612 - failed to setup rootfs for 'gitlab'
            lxc 20160615095115.450 ERROR    lxc_conf - conf.c:lxc_setup:3694 - Error setting up rootfs mount after spawn
            lxc 20160615095115.450 ERROR    lxc_start - start.c:do_start:833 - failed to setup the container
            lxc 20160615095115.450 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20160615095115.450 WARN     lxc_conf - conf.c:lxc_delete_network:2909 - failed to remove interface 33 'eth0'
            lxc 20160615095115.450 ERROR    lxc_start - start.c:__lxc_start:1353 - failed to spawn 'gitlab'
            lxc 20160615095115.473 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'gitlab', config section 'lxc'
            lxc 20160615095115.976 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 3 stop' for container 'gitlab', config section 'lxc'
            lxc 20160615095116.102 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160615095116.102 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160615095116.116 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160615095116.116 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160615095127.096 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160615095127.096 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160615095127.108 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160615095127.108 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 100000 range 65536

**Comment by tych0** [comment]
On Wed, Jun 15, 2016 at 06:56:07AM -0700, Esteban Echeverry wrote:
>             lxc 20160615095115.450 ERROR    lxc_conf - conf.c:setup_rootfs:1221 - failed to mount rootfs
>             lxc 20160615095115.450 ERROR    lxc_conf - conf.c:do_rootfs_setup:3612 - failed to setup rootfs for 'gitlab'
>             lxc 20160615095115.450 ERROR    lxc_conf - conf.c:lxc_setup:3694 - Error setting up rootfs mount after spawn
>             lxc 20160615095115.450 ERROR    lxc_start - start.c:do_start:833 - failed to setup the container

Looks like something went wrong in the LXD storage driver. Do you have
the lxd logs as well?

**Comment by tebanep** [comment]
@tycho0 Unfortunately I had to delete the container and keep on working in the copy I made of it. Everything seems working fine right now. If the problem shows up again, I will post it here again. Thanks.

**Comment by stgraber** [comment]
I'm 99% sure that this is our "usual" zfs unmount bug where the container rootfs sometimes gets unmounted by ZFS for no good reason.

I did include a "fix" for this issue in 2.0.3 which now simply issues a "zfs mount" whenever it detects a container isn't mounted at startup time.

Assuming this is fixed now and so closing it.

**Comment by tebanep** [comment]
The error happened again today and I confirm that after upgrading from version 2.0.2 to 2.0.3 the problem is gone and the failing container now starts normally. Awesome! Thanks a lot!

**Comment by stgraber** [comment]
cool
