### ISSUE TITLE
mark lxd managed iptable rules with a comment

### ISSUE THREAD

**Issue by pgassmann** [lxc/lxd#2125]
LXD manages some firewall rules for NAT etc.

It would be useful if these rules are marked as managed by lxd. a comment can be set for iptables rules.  `-m comment --comment "managed by lxd-bridge"`

This would be helpful to identify what is managed by lxd-brige and what is defined by other sources.

This could also help to properly cleanup managed rules when configuration changes. I don't know if that could be an issue or how lxd-bridge tracks the firewall rules.

https://major.io/2010/07/26/adding-comments-to-iptables-rules/

**Comment by stgraber** [comment]
A pull request doing that would be welcome.
