### ISSUE TITLE
Unable to resolve dns in containers

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2126]
Hi,
I am new to the lxc community and trying to understand the containers.
The setup for my server is as follows.

The server is booted with PXE boot on to Ubuntu Xenial image.
I am able to create the lxc container, and get the IP address from lxdbr0 dnsmasq service.

However, I am unable to communicate to the outside world from the container.

I tried using tcpdump on the lxdbr0 interface, but it didn't dump any results.

My ubuntu server doesn't have Network Manager installed, since it is network boot image, and thus dnsmasq is not being run on localhost.
/etc/resolv.conf contains the local nameserver, which resolves all the DNS queries and this nameserver is running on Debian Image with bind protocol.

I created a ubuntu Virtual machine and installed ubuntu on the VM, and followed the same steps and it worked on that. 
Since it was a complete install it does have networking manager, and dnsmasq being run on localhost.

Can someone help how to get networking connectivity inside the container for this kind of configuration?

**Comment by stgraber** [comment]
Did you configure your lxdbr0? Otherwise the default bridge comes up with no ipv4 or ipv6 subnet and only minimal ipv6 link-local connectivity, which would indeed prevent it from doing any DNS queries.

**Comment by upuvvad1** [comment]
@stgraber 
Thanks for quick reply.
Yes I did configure the lxdbr0, and below is the generated config file

 cat /etc/default/lxd-bridge
# WARNING: This file is generated by a debconf template!
# It is recommended to update it by using "dpkg-reconfigure -p medium lxd"

# Whether to setup a new bridge or use an existing one
USE_LXD_BRIDGE="true"

# Bridge name
# This is still used even if USE_LXD_BRIDGE is set to false
# set to an empty value to fully disable
LXD_BRIDGE="lxdbr0"

# Update the "default" LXD profile
UPDATE_PROFILE="true"

# Path to an extra dnsmasq configuration file
LXD_CONFILE=""

# DNS domain for the bridge
LXD_DOMAIN="lxd"

# IPv4
## IPv4 address (e.g. 10.0.8.1)
LXD_IPV4_ADDR="10.200.0.49"

## IPv4 netmask (e.g. 255.255.255.0)
LXD_IPV4_NETMASK="255.0.0.0"

## IPv4 network (e.g. 10.0.8.0/24)
LXD_IPV4_NETWORK="10.200.0.49/8"

## IPv4 DHCP range (e.g. 10.0.8.2,10.0.8.254)
LXD_IPV4_DHCP_RANGE="10.200.0.50,10.200.0.54"

## IPv4 DHCP number of hosts (e.g. 250)
LXD_IPV4_DHCP_MAX="4"

## NAT IPv4 traffic
LXD_IPV4_NAT="true"

# IPv6
## IPv6 address (e.g. 2001:470:b368:4242::1)
LXD_IPV6_ADDR=""

## IPv6 CIDR mask (e.g. 64)
LXD_IPV6_MASK=""

## IPv6 network (e.g. 2001:470:b368:4242::/64)
LXD_IPV6_NETWORK=""

## NAT IPv6 traffic
LXD_IPV6_NAT="false"

# Run a minimal HTTP PROXY server
LXD_IPV6_PROXY="false"


And the lxc list is as follows

sudo lxc list
+------+---------+--------------------+------+------------+-----------+
| NAME |  STATE  |        IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+--------------------+------+------------+-----------+
| c101 | RUNNING | 10.200.0.50 (eth0) |      | PERSISTENT | 0         |
+------+---------+--------------------+------+------------+-----------+

ps aux | grep dnsmasq

lxd       4032  0.0  0.0  45268   376 ?        S    Jun15   0:00 dnsmasq -s lxd -S /lxd/ -u lxd --strict-order --bind-interfaces --pid-file=/run/lxd-bridge//dnsmasq.pid --dhcp-no-override --except-interface=lo --interface=lxdbr0 --dhcp-leasefile=/var/lib/lxd-bridge//dnsmasq.lxdbr0.leases --dhcp-authoritative --listen-address 10.200.0.49 --dhcp-range 10.200.0.50,10.200.0.54 --dhcp-lease-max=4

**Comment by stgraber** [comment]
According to the ip addr you pasted, you configured lxdbr0 as a /8, that's going to be the problem here.

By the looks of it, you really want it to be a /24, otherwise the container will (rightfully) assume that it can directly reach all addresses from 10.0.0.0 to 10.255.255.255 which isn't actually the case.

**Comment by upuvvad1** [comment]
Yes, my bad.
That worked.
Thanks @stgraber
