### ISSUE TITLE
LXD lose snapshot after creating containers from them, if using zfs, and deleting containers

### ISSUE THREAD

**Issue by juan-leon** [lxc/lxd#2127]
I am having issues when creating containers from snaphots, when using lxd with
zfs as backstorage.  I can create the container, but when I delete it, the
snapshot gets deleted at zfs level (not at lxd).

I am using lxd in Ubuntu 16.04, and the funny thing is that does not happen in
every box: some work fine, others never did, and others worked fine for a while
and then broke.

I wonder now if creating containers from snapshots is legit, or if operation
semantics are unspecified.

This can be seen in this example

    $ lxc launch ubuntu:14.04 mycontainer
    $ lxc stop mycontainer
    $ lxc snapshot mycontainer mysnap0
    $ lxc copy mycontainer/mysnap0 mycontainer1
    $ lxc delete mycontainer1
    $ lxc copy mycontainer/mysnap0 mycontainer2
    error: rsync failed: rsync: change_dir "/var/lib/lxd/snapshots/mycontainer/mysnap0" failed: No such file or directory (2)
    rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

But lxd still thinks the snapshot is good.

    $ lxc info mycontainer
    Name: mycontainer
    Architecture: x86_64
    Created: 2016/06/16 10:53 UTC
    Status: Stopped
    Type: persistent
    Profiles: default
    Snapshots:
      mysnap0 (taken at 2016/06/16 10:54 UTC) (stateless)

Another example that makes me think is lxd who request zfs to delete the snapshot:

    $ lxc snapshot mycontainer mysnap1
    $ lxc copy mycontainer/mysnap1 mycontainer2
    $ lxc copy mycontainer/mysnap1 mycontainer3
    $ lxc delete mycontainer2
    error: Failed to destroy ZFS filesystem: cannot destroy 'debtool/containers/mycontainer@snapshot-mysnap1': snapshot has dependent clones

And some info on the versions I use:

    zfs-zed                   0.6.5.6-0ubuntu8
    zfsutils-linux            0.6.5.6-0ubuntu8
    lxd                       2.0.2-0ubuntu1~16.04.1
    lxd-client                2.0.2-0ubuntu1~16.04.1
    lxd-tools                 2.0.2-0ubuntu1~16.04.1
    liblxc1                   2.0.0-0ubuntu2
    lxc                       2.0.0-0ubuntu2
    lxc-common                2.0.0-0ubuntu2
    lxc-templates             2.0.0-0ubuntu2
    lxc1                      2.0.0-0ubuntu2
    lxcfs                     2.0.0-0ubuntu2.1

    $ lxc info
    apicompat: 0
    auth: trusted
    environment:
      addresses:
      - 127.0.0.1:8443
      architectures:
      - x86_64
      - i686
      driver: lxc
      driverversion: 2.0.0
      kernel: Linux
      kernelarchitecture: x86_64
      kernelversion: 4.4.0-15-generic
      server: lxd
      serverpid: 9200
      serverversion: 2.0.2
      storage: zfs
      storageversion: "5"
    config:
      core.https_address: 127.0.0.1:8443
      core.trust_password: true
      storage.zfs_pool_name: debtool
    public: false

    $ lxc copy --debug mycontainer/mysnap0 mycontainer4
    DBUG[06-16|13:22:43] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_extensions":[],"api_status":"stable","api_version":"1.0","auth":"trusted","config":{"core.https_address":"127
    .0.0.1:8443","core.trust_password":true,"storage.zfs_pool_name":"debtool"},"environment":{"addresses":["127.0.0.1:8443"],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\nMIIFdDCCA1ygAw
    ...
    --END CERTIFICATE-----\n","driver":"lxc","driver_version":"2.0.0","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.4.0-15-generic","server":"lxd","server_pid":9200,"server_version":"2.0.2","stor
    age":"zfs","storage_version":"5"},"public":false}}

    DBUG[06-16|13:22:43] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"architecture":"x86_64","config":{"volatile.base_image":"d02d6cf5a494df1c88144c7cbfec47b6d010a79baf18975a7c17abbf3
    1cbae40","volatile.eth0.hwaddr":"00:16:3e:a6:d4:53","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":427680,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":427680,
    \"Nsid\":0,\"Maprange\":65536}]"},"created_at":"2016-06-16T12:54:20+02:00","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.base_image":"d02d6cf5a494df1c88144c7cbfec47b6
    d010a79baf18975a7c17abbf31cbae40","volatile.eth0.hwaddr":"00:16:3e:a6:d4:53","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":427680,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\
    ":true,\"Hostid\":427680,\"Nsid\":0,\"Maprange\":65536}]"},"expanded_devices":{"eth0":{"name":"eth0","nictype":"bridged","parent":"lxdbr0","type":"nic"},"root":{"path":"/","type":"disk"}},"name":"mycontainer/mysna
    p0","profiles":["default"],"stateful":false}}

    DBUG[06-16|13:22:43] Posting {"config":{},"ephemeral":false,"name":"mycontainer4","profiles":["default"],"source":{"source":"mycontainer/mysnap0","type":"copy"}}
     to http://unix.socket/1.0/containers
    DBUG[06-16|13:22:43] Raw response: {"type":"async","status":"Operation created","status_code":100,"metadata":{"id":"58c11824-a5ba-4ba5-a5d2-5f14984804e7","class":"task","created_at":"2016-06-16T13:22:43.391166781+
    02:00","updated_at":"2016-06-16T13:22:43.391166781+02:00","status":"Running","status_code":103,"resources":{"containers":["/1.0/containers/mycontainer4","/1.0/containers/mycontainer/mysnap0"]},"metadata":null,"may
    _cancel":false,"err":""},"operation":"/1.0/operations/58c11824-a5ba-4ba5-a5d2-5f14984804e7"}

    DBUG[06-16|13:22:43] 1.0/operations/58c11824-a5ba-4ba5-a5d2-5f14984804e7/wait
    DBUG[06-16|13:22:43] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"id":"58c11824-a5ba-4ba5-a5d2-5f14984804e7","class":"task","created_at":"2016-06-16T13:22:43.391166781+02:00","upd
    ated_at":"2016-06-16T13:22:43.391166781+02:00","status":"Failure","status_code":400,"resources":{"containers":["/1.0/containers/mycontainer4","/1.0/containers/mycontainer/mysnap0"]},"metadata":null,"may_cancel":fa
    lse,"err":"rsync failed: rsync: change_dir \"/var/lib/lxd/snapshots/mycontainer/mysnap0\" failed: No such file or directory (2)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) a
    t main.c(1183) [sender=3.1.1]\n"}}

    error: rsync failed: rsync: change_dir "/var/lib/lxd/snapshots/mycontainer/mysnap0" failed: No such file or directory (2)
    rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

**Comment by stgraber** [comment]
Ok, so it doesn't look like LXD actually lost anything, instead it looks like it's got an extra temporary snapshot around which is blocking things.

Can you paste the output of "zfs list -t all" on an affected system?

**Comment by juan-leon** [comment]
Output of zfs list -t all (the one named mycontainer is the one with a no longer working snapshot, as I did the steps I described above):

    NAME                                                                                                        USED  AVAIL  REFER  MOUNTPOINT
    debtool                                                                                                    4,70G  24,1G    19K  none
    debtool/containers                                                                                         1,38G  24,1G    19K  none
    debtool/containers/debtool-precise-base                                                                     381M  24,1G   868M  /var/lib/lxd/containers/debtool-precise-base.zfs
    debtool/containers/debtool-precise-base@snapshot-debtool-precise-snapshot                                  3,84M      -   868M  -
    debtool/containers/debtool-trusty-base                                                                      385M  24,1G   806M  /var/lib/lxd/containers/debtool-trusty-base.zfs
    debtool/containers/debtool-trusty-base@snapshot-debtool-trusty-snapshot                                       1K      -   806M  -
    debtool/containers/debtool-xenial-base                                                                      475M  24,1G   975M  /var/lib/lxd/containers/debtool-xenial-base.zfs
    debtool/containers/debtool-xenial-base@snapshot-debtool-xenial-snapshot                                       1K      -   975M  -
    debtool/containers/lxctest                                                                                  167M  24,1G   867M  /var/lib/lxd/containers/lxctest.zfs
    debtool/containers/mycontainer                                                                             7,54M  24,1G   572M  /var/lib/lxd/containers/mycontainer.zfs
    debtool/deleted                                                                                            1,42G  24,1G    19K  none
    debtool/deleted/containers                                                                                  813M  24,1G    19K  none
    debtool/deleted/containers/5df6b116-673e-4fdc-8a73-a7cfedfc9ff8                                             474M  24,1G   972M  none
    debtool/deleted/containers/5df6b116-673e-4fdc-8a73-a7cfedfc9ff8@copy-9542b6f8-6caa-4f1c-9b96-2846767ede9f   999K      -   972M  -
    debtool/deleted/containers/b55c7d38-8b51-4b08-92cc-11f19c626e98                                             339M  24,1G   832M  none
    debtool/deleted/containers/b55c7d38-8b51-4b08-92cc-11f19c626e98@copy-63b474dc-209f-40bb-91ef-d443425c2b1b   385K      -   832M  -
    debtool/deleted/images                                                                                      640M  24,1G    19K  none
    debtool/deleted/images/d23ee1f4fd284aeaba6adeb67cccf7b871e96178d637fec96320aab7cc9634b1                     640M  24,1G   640M  none
    debtool/deleted/images/d23ee1f4fd284aeaba6adeb67cccf7b871e96178d637fec96320aab7cc9634b1@readonly               0      -   640M  -
    debtool/images                                                                                             1,89G  24,1G    19K  none
    debtool/images/98dc4bd7cca2fcd24c82ee403baaca3a5bd1845f925540786d0954a5973c181c                             643M  24,1G   643M  /var/lib/lxd/images/98dc4bd7cca2fcd24c82ee403baaca3a5bd1845f925540786d0954a5973c181c.zfs
    debtool/images/98dc4bd7cca2fcd24c82ee403baaca3a5bd1845f925540786d0954a5973c181c@readonly                       0      -   643M  -
    debtool/images/d02d6cf5a494df1c88144c7cbfec47b6d010a79baf18975a7c17abbf31cbae40                             571M  24,1G   571M  /var/lib/lxd/images/d02d6cf5a494df1c88144c7cbfec47b6d010a79baf18975a7c17abbf31cbae40.zfs
    debtool/images/d02d6cf5a494df1c88144c7cbfec47b6d010a79baf18975a7c17abbf31cbae40@readonly                       0      -   571M  -
    debtool/images/fa13d1486d449e960c6adaf02a225ac1d56e5a52228e145c9e32a26abf760455                             718M  24,1G   718M  /var/lib/lxd/images/fa13d1486d449e960c6adaf02a225ac1d56e5a52228e145c9e32a26abf760455.zfs
    debtool/images/fa13d1486d449e960c6adaf02a225ac1d56e5a52228e145c9e32a26abf760455@readonly                       0      -   718M  -

**Comment by stgraber** [comment]
reproduced the issue, looking into this

**Comment by stgraber** [comment]
Oh wow, that's a pretty serious bug indeed, LXD very much shouldn't consider a snapshot-* snapshot as being deletable...
