### ISSUE TITLE
lxd --help is missing a '\n'

### ISSUE THREAD

**Issue by brunonova** [lxc/lxd#2131]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-24-generic
   * LXD version: 2.0.2

# Issue description

A very small issue.
The help output of `lxd --help` is missing a `\n` at the end, causing the shell command prompt to be printed along with the last line of output, instead of in a new line.

The output of an unknown subcommand, like `lxd help`, does have a newline at the end.
It prints the same as `lxd --help`, plus `error: Unknown arguments`. However, there isn't a newline between the two.

# Steps to reproduce

 1. Just run `lxd --help`

**Comment by stgraber** [comment]
Yep, I fixed that one a bit ago, will be in 2.0.3.

**Comment by brunonova** [comment]
Great! Thanks!
