### ISSUE TITLE
Unable to live migrate when a background job is running inside container.

### ISSUE THREAD

**Issue by pulnarayana1** [lxc/lxd#2134]
Running on ubuntu 16.04 

sudo lxc info lxd-cnt-1071
Name: lxd-cnt-1071
Architecture: x86_64
Created: 2016/06/17 18:52 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 13994
Ips:
  eth0:	inet	10.200.3.202	vethE6BH4L
  eth0:	inet6	fe80::216:3eff:fedb:be32	vethE6BH4L
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 20
  Disk usage:
    root: 643.95MB
  Memory usage:
    Memory (current): 15.69MB
    Memory (peak): 38.77MB
  Network usage:
    eth0:
      Bytes received: 2.78kB
      Bytes sent: 1.01kB
      Packets received: 18
      Packets sent: 10
    lo:
      Bytes received: 288 bytes
      Bytes sent: 288 bytes
      Packets received: 4
      Packets sent: 4

**Steps to reproduce :**
sudo lxc exec lxd-cnt-101 bash
root@lxd-cnt-1071:~# yes >& /dev/null &
[1] 368
root@lxd-cnt-1071:~# exit

Terminal hangs up as posted in the previous issue. #2133 
Live migration fails as below

sudo lxc move lxd-cnt-1071 r520-51.es2.int:
error: Error transferring container data: checkpoint failed:
(00.110657) Error (namespaces.c:256): Can't dump nested cgroup namespace for 14567
(00.110659) Error (namespaces.c:502): Can't make cgroup id
(00.113373) Error (util.c:670): exited, status=1
(00.115782) Error (util.c:670): exited, status=1
(00.115893) Error (cr-dump.c:1600): Dumping FAILED.

**Comment by stgraber** [comment]
This is a CRIU bug which should instead be reported at https://launchpad.net/ubuntu/+source/criu/+filebug

This also sounds familiar so it could be that someone already filed it there. You can check the current list at https://launchpad.net/ubuntu/+source/criu/+bugs
