### ISSUE TITLE
Running 'lxd publish <container>' builds image on rootfs when zfs backend is in use

### ISSUE THREAD

**Issue by bmcgough** [lxc/lxd#2135]
* Distribution: Ubuntu
 * Distribution version: 16.04 LTS
 * The output of "lxc info" or if that fails:
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-22-generic
  server: lxd
  serverpid: 19670
  serverversion: 2.0.2
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd
public: false

# Issue description

It certainly appears to me that the 'lxc publish' process builds an image from a container using the rootfs rather than ZFS if ZFS is used as the storage backend.

# Steps to reproduce

 1. Set up LXD with ZFS backend
 2. Create a container larger than your rootfs
 3. Run `lxc publish <container name>` and get something like:

error: write /var/lib/lxd/images/lxd_build_961895608/lxd_build_tar_654764714: no space left on device

I can see from `zfs list` that lxd is creating filesystems on my zpool for containers and images, but I don't see one being created for lxd_build_... when building an image from a container. I would expect lxd to use ZFS for image building.

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
Images are a .tar.gz tarball of the container, so yes, it does generate a tarball for you.

**Comment by stgraber** [comment]
That tarball may then be stored as a zfs filesystem too to make container creation faster, but the authoritative source of an image is always its tarball, that's what's hashed and makes the image fingerprint.

**Comment by bmcgough** [comment]
It cannot create a tarball because my rootfs is not large enough. All the local space on my host is in the zfs pool and /var/lib/lxd/images/lxd_build_<id>/... is not created on the zpool, but is simply a directory on the rootfs.

**Comment by stgraber** [comment]
Right. You could manually move /var/lib/lxd/images to a zfs filesystem which would fix your space problem.

LXD doesn't set it up that way because we do need to support changing your zpool, converting pre-zfs images to zfs filesystems and support containers that aren't zfs backed.

**Comment by stgraber** [comment]
Moving /var/lib/lxd/images to a zfs filesystem typically involves something along the lines of:
 - "sudo zfs umount" of anything under /varlib/lxd/images
 - "mv /var/lib/lxd/images /var/lib/lxd/images.pre
 - "zfs create POOL/lxd/images -o mountpoint=/var/lib/lxd/images"
 - "mv /var/lib/lxd/images.pre/* /var/lib/lxd/images/"
 - "rmdir /var/lib/lxd/images.pre"
 - "sudo zfs mount" of anything under /var/lib/lxd/images

**Comment by bmcgough** [comment]
OK, sounds good. You might want to point out in the documentation that having space available on the rootfs is also required; I assumed if I was using the ZFS storage backend I would only be constrained by the storage space of my zpool.

Thanks for the instruction - I was able to replace /var/lib/lxd/images with a ZFS filesystem and then my 'lxd publish' ran to completion.
