### ISSUE TITLE
Test if lxd init was run

### ISSUE THREAD

**Issue by killua-eu** [lxc/lxd#2137]
This is probably mostly a documentation request. I'm currently using ansible to automate deployment of lxd over multiple machines. I want to test if lxd init --auto --.... was already called on a system. What does actually `lxd init` do? Just setting the defaults of core.https_address, etc.? How can I test that lxd has been initialized properly (i.e. via the lxd init). How can I reset the package (on ubuntu) to an uninitalized state?

Sofar I could fingure only to test against
lxc info | grep "If this is your first time using LXD, you should also run: sudo lxd init"
which is not really elegant. Thanks in advance for a reply

**Comment by stgraber** [comment]
It sets core.https_address, core.trust_password and storage.zfs_pool_name

Depending on what options you choose.

**Comment by killua-eu** [comment]
so it's mostly a convenience thing ... thanks a lot for explaining! one more question: the ncurses setup of the bridge for lxd in the interactive versionon of lxd init is something which is ubuntu-specific, or is it a distro-agnostic thing? on ubuntu it only sets /etc/defaults/lxd-bridge, or does it further setup something, i.e. the default profile, or start services?

**Comment by stgraber** [comment]
lxd-bridge is currently Ubuntu specific, which is why "lxd init" is patched on Ubuntu to trigger the ncurses configuration screens.

We will be adding native bridge configuration support to LXD in the near future, which will then be exposed directly in lxd init and the current Ubuntu lxdbr0 bridge will be replaced by this.

**Comment by killua-eu** [comment]
Thanks lots for the explanation @stgraber, I can now die in peace (or close this ticket). Please feel free to reopen it if you feel like some of this is worth documenting somewhere.
