### ISSUE TITLE
Directory /var/lib/lxd/containers/*.zfs is empty

### ISSUE THREAD

**Issue by bestreyer** [lxc/lxd#2139]
I stopped container. When I tried to start container, i got error. Directory /var/lib/lxd/containers/*.zfs has been removed.

Name: forum-db
Architecture: x86_64
Created: 2016/06/05 17:46 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20160620104209.620 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160620104209.620 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 9
            lxc 20160620104209.626 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /var/lib/lxd/containers forum-db
            lxc 20160620104209.627 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 9
            lxc 20160620104209.628 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for reject_force_umount action 0
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for reject_force_umount action 0
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .[all].
lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .kexec_load errno 1.
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for kexec_load action 327681
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for kexec_load action 327681
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .open_by_handle_at errno 1.
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for open_by_handle_at action 327681
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for open_by_handle_at action 327681
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .init_module errno 1.
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for init_module action 327681
            lxc 20160620104209.628 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for init_module action 327681
            lxc 20160620104209.629 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .finit_module errno 1.
            lxc 20160620104209.629 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for finit_module action 327681
            lxc 20160620104209.629 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for finit_module action 327681
            lxc 20160620104209.629 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .delete_module errno 1.
            lxc 20160620104209.629 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for delete_module action 327681
            lxc 20160620104209.629 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for delete_module action 327681
            lxc 20160620104209.629 INFO     lxc_seccomp - seccomp.c:parse_config_v2:456 - Merging in the compat seccomp ctx into the main one
            lxc 20160620104209.629 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 11 start' for container 'forum-db', config section 'lxc'
            lxc 20160620104209.630 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160620104209.630 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 9
            lxc 20160620104209.637 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/d78a9d7e97b4b375//var/lib/lxd/containers
            lxc 20160620104209.691 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
            lxc 20160620104209.692 DEBUG    lxc_console - console.c:lxc_console_peer_default:469 - no console peer
lxc 20160620104209.692 INFO     lxc_start - start.c:lxc_init:488 - 'forum-db' is initialized
            lxc 20160620104209.694 DEBUG    lxc_start - start.c:__lxc_start:1326 - Not dropping cap_sys_boot or watching utmp
            lxc 20160620104209.694 INFO     lxc_start - start.c:resolve_clone_flags:1013 - Cloning a new user namespace
            lxc 20160620104209.696 DEBUG    lxc_conf - conf.c:instantiate_veth:2614 - instantiated veth 'vethG0VLT2/vethQ4414P', index is '200'
            lxc 20160620104209.696 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for forum-db
            lxc 20160620104209.707 DEBUG    lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1667 - cgroup 'memory.limit_in_bytes' set to '8589934592'
            lxc 20160620104209.707 INFO     lxc_cgfsng - cgfsng.c:cgfsng_setup_limits:1671 - cgroup has been setup
            lxc 20160620104209.717 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 296608 range 65536
            lxc 20160620104209.717 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 296608 range 65536
            lxc 20160620104209.849 DEBUG    lxc_conf - conf.c:lxc_assign_network:3048 - move 'eth0' to '20413'
            lxc 20160620104209.849 NOTICE   lxc_start - start.c:do_start:777 - switching to gid/uid 0/0 in new user namespace
            lxc 20160620104209.850 ERROR    lxc_conf - conf.c:mount_rootfs:807 - No such file or directory - failed to get real path for '/var/lib/lxd/containers/forum-db/rootfs'
            lxc 20160620104209.850 ERROR    lxc_conf - conf.c:setup_rootfs:1221 - failed to mount rootfs
            lxc 20160620104209.850 ERROR    lxc_conf - conf.c:do_rootfs_setup:3612 - failed to setup rootfs for 'forum-db'
            lxc 20160620104209.850 ERROR    lxc_conf - conf.c:lxc_setup:3694 - Error setting up rootfs mount after spawn
            lxc 20160620104209.850 ERROR    lxc_start - start.c:do_start:833 - failed to setup the container
            lxc 20160620104209.850 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20160620104209.851 WARN     lxc_conf - conf.c:lxc_delete_network:2909 - failed to remove interface 200 'eth0'
            lxc 20160620104209.851 ERROR    lxc_start - start.c:__lxc_start:1353 - failed to spawn 'forum-db'
            lxc 20160620104209.973 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'forum-db', config section 'lxc'
            lxc 20160620104210.482 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 11 stop' for container 'forum-db', config section 'lxc'
lxc 20160620104210.583 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160620104210.583 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160620104210.619 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 296608 range 65536
            lxc 20160620104210.619 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 296608 range 65536
            lxc 20160620104221.885 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 296608 range 65536
            lxc 20160620104221.885 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 296608 range 65536
            lxc 20160620104221.895 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 296608 range 65536
            lxc 20160620104221.895 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 296608 range 65536
            lxc 20160620105215.149 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 296608 range 65536
            lxc 20160620105215.149 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 296608 range 65536
            lxc 20160620105215.159 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 296608 range 65536
            lxc 20160620105215.159 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 296608 range 65536
            lxc 20160620105606.234 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 296608 range 65536
            lxc 20160620105606.235 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 296608 range 65536
            lxc 20160620105606.243 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 296608 range 65536
            lxc 20160620105606.244 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 296608 range 65536

**Comment by stgraber** [comment]
Does 'sudo zfs mount -a" fix this?

If so, it's a bug we've already fixed and which will be sorted out with LXD 2.0.3.

Well, we haven't fixed the actual bug since that's a ZFS issue not a LXD one, but we did add a workaround for it :)

**Comment by bestreyer** [comment]
@stgraber Thanks ! Command 'sudo zfs mount -a'  fixed the problem.
