### ISSUE TITLE
Unable to do live migration of container.

### ISSUE THREAD

**Issue by pulnarayana1** [lxc/lxd#2140]
Hi,
I am trying to do live migration of a container running ubuntu template, but the migration fails throwing the error message as follows.

sudo lxc move lxd-cnt-1072 r520-53.es2.int:
error: Error transferring container data: restore failed:
(00.129853)      1: Error (mount.c:2599): mnt: Can't create a temporary directory: Permission denied
(00.142257) Error (cr-restore.c:1352): 5257 killed by signal 9
(00.191549) Error (cr-restore.c:2182): Restoring FAILED.

And the syslog at the destination is as follows.

Jun 20 13:52:55 r520-53 kernel: [  816.349169] audit: type=1400 audit(1466445175.683:27): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-lxd-cnt-1072_</var/work/lxd>" pid=5251 comm="apparmor_parser"
Jun 20 13:52:55 r520-53 kernel: [  816.432442] cgroup: new mount options do not match the existing superblock, will be ignored
Jun 20 13:52:55 r520-53 systemd-udevd[5259]: Could not generate persistent MAC address for vethTSH37G: No such file or directory
Jun 20 13:52:55 r520-53 kernel: [  816.460475] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Jun 20 13:52:56 r520-53 kernel: [  817.213730] audit: type=1400 audit(1466445176.547:28): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-lxd-cnt-1072_</var/work/lxd>" pid=5323 comm="apparmor_parser"
Jun 20 13:52:56 r520-53 lxd[2715]: t=2016-06-20T13:52:56-0400 lvl=eror msg="Error during migration sink" err="restore failed:\n(00.129853)      1: Error (mount.c:2599): mnt: Can't create a temporary directory: Permission denied\n(00.142257) Error (cr-restore.c:1352): 5257 killed by signal 9\n(00.191549) Error (cr-restore.c:2182): Restoring FAILED."

Can some one please help me out with this.

**Comment by stgraber** [comment]
@tych0 

This does seem to be a CRIU issue though, I'd recommend you follow the bug reporting instructions here: https://www.stgraber.org/2016/04/25/lxd-2-0-live-migration-912/

We track CRIU issues on Launchpad at https://launchpad.net/ubuntu/+source/criu/+bugs

**Comment by tych0** [comment]
On Mon, Jun 20, 2016 at 10:55:51AM -0700, pulnarayana1 wrote:
> Hi,
> I am trying to do live migration of a container running ubuntu template, but the migration fails throwing the error message as follows.
> 
> sudo lxc move lxd-cnt-1072 r520-53.es2.int:
> error: Error transferring container data: restore failed:
> (00.129853)      1: Error (mount.c:2599): mnt: Can't create a temporary directory: Permission denied
> (00.142257) Error (cr-restore.c:1352): 5257 killed by signal 9
> (00.191549) Error (cr-restore.c:2182): Restoring FAILED.

Do you have /tmp mounted read-only (or some other perms issue on
/tmp)?

**Comment by pulnarayana1** [comment]
@tych0 and @stgraber 
Thanks for reply.

No /tmp is mounted as tempfs with rw permission, and I am able to write a file to /tmp

tmpfs /tmp tmpfs rw,relatime 0 0

And was able to write normal file as follows
touch /tmp/1

**Comment by pulnarayana1** [comment]
If I create new container, and try to migrate it does works.. I don't know why the old container fails.
