### ISSUE TITLE
Live Migartion Fail

### ISSUE THREAD

**Issue by davereiner** [lxc/lxd#2153]
I'm not able to do a live migration between two 100% identical Google Cloud machines (in the same zone) both running Ubuntu 16.04 and the same (latest) LXD + CRIU.

`
lxc move zJY-movetest06241 lxd-uscentral-2:zJY-movetest06241
error: Error transferring container data: restore failed:
(10.727191)    683: Error (pipes.c:226): Can't restore pipe size: Operation not permitted
(10.728790)    417: Error (pipes.c:226): Can't restore pipe size: Operation not permitted
(10.729151)    680: Error (cr-restore.c:1350): 683 exited, status=1
(10.731129)    680: Error (pipes.c:226): Can't restore pipe size: Operation not permitted
(10.885172) Error (cr-restore.c:1352): 20679 killed by signal 9
(10.914615) Error (files-reg.c:516):  - XFail [/tmp/.ZendSem.DwwGDn.cr.1.ghost] ghost: No such file or directory
(10.914625) Error (files-reg.c:516):  - XFail [/tmp/.ZendSem.hbp7Hn.cr.2.ghost] ghost: No such file or directory
(10.950649) Error (cr-restore.c:2182): Restoring FAILED.
`
On next try I got this:
`
lxc move lxd-uscentral-2:zJY-movetest06241 zJY-movetest06241
error: Error transferring container data: restore failed:
(00.637016)    371: Error (files.c:594): 371: Can't setup 15 file owner pid: No such process
(00.638986)      1: Error (cr-restore.c:1350): 371 exited, status=1
(00.690242) Error (cr-restore.c:1352): 765 killed by signal 9
(00.725849) Error (files-reg.c:516):  - XFail [/tmp/.ZendSem.CA5pel.cr.1.ghost] ghost: No such file or directory
(00.725855) Error (files-reg.c:516):  - XFail [/tmp/.ZendSem.wA0ZNk.cr.2.ghost] ghost: No such file or directory
(00.756351) Error (cr-restore.c:2182): Restoring FAILED.
`

Please advise.
Update: when creating a new Ubuntu 16.04 based, empty/plain container live migration works.

**Comment by tych0** [comment]
On Fri, Jun 24, 2016 at 06:22:45AM -0700, David Reiner wrote:
> I'm not able to do a live migration between two 100% identical Google Cloud machines (in the same zone) both running Ubuntu 16.04 and the same (latest) LXD + CRIU.
> 
> `
> lxc move zJY-movetest06241 lxd-uscentral-2:zJY-movetest06241
> error: Error transferring container data: restore failed:
> (10.727191)    683: Error (pipes.c:226): Can't restore pipe size: Operation not permitted
> (10.728790)    417: Error (pipes.c:226): Can't restore pipe size: Operation not permitted
> (10.729151)    680: Error (cr-restore.c:1350): 683 exited, status=1
> (10.731129)    680: Error (pipes.c:226): Can't restore pipe size: Operation not permitted
> (10.885172) Error (cr-restore.c:1352): 20679 killed by signal 9
> (10.914615) Error (files-reg.c:516):  - XFail [/tmp/.ZendSem.DwwGDn.cr.1.ghost] ghost: No such file or directory
> (10.914625) Error (files-reg.c:516):  - XFail [/tmp/.ZendSem.hbp7Hn.cr.2.ghost] ghost: No such file or directory
> (10.950649) Error (cr-restore.c:2182): Restoring FAILED.
> `

This looks like a CRIU bug; the F_SETPIPE_SZ fcntl requires real root,
and this doesn't go through the usernsd proxy that criu sets up. Can
you file a bug here: https://bugs.launchpad.net/ubuntu/+source/criu

> On next try I got this:
> `
> lxc move lxd-uscentral-2:zJY-movetest06241 zJY-movetest06241
> error: Error transferring container data: restore failed:
> (00.637016)    371: Error (files.c:594): 371: Can't setup 15 file owner pid: No such process
> (00.638986)      1: Error (cr-restore.c:1350): 371 exited, status=1
> (00.690242) Error (cr-restore.c:1352): 765 killed by signal 9
> (00.725849) Error (files-reg.c:516):  - XFail [/tmp/.ZendSem.CA5pel.cr.1.ghost] ghost: No such file or directory
> (00.725855) Error (files-reg.c:516):  - XFail [/tmp/.ZendSem.wA0ZNk.cr.2.ghost] ghost: No such file or directory
> (00.756351) Error (cr-restore.c:2182): Restoring FAILED.
> `

This looks like another CRIU bug where we need a pid helper for dead
pids who still own files. Can you file another bug with this log at
the URL above?

Thanks!

**Comment by stgraber** [comment]
As @tych0 mentioned, we're tracking CRIU bugs at https://launchpad.net/ubuntu/+source/criu rather than here. Unless the issue is with how LXD itself interacts with CRIU.

Please file a bug on Launchpad and we'll pick it up from there, thanks!
