### ISSUE TITLE
lxd removes  the default gateway. 

### ISSUE THREAD

**Issue by techgsgithub** [lxc/lxd#2156]
I find LXD very amazing.

However I have noticed following problem.

The moment I execute any lxc/lxd command,  the default gateway is lost and to enable net connectivity I need to manually following command to enable Internet.

sudo route add default gw 192.168.1.1
This is very annoying. 

Following are my system  details.
1  Distribution :  Ubuntu-mate 16.04 64 bit ( Intel platform ) # updated on daily basis. 
2.  Disabled the network-manager.( manual network configuration )
3.  Configured networking manually in /etc/network/interfaces file.
     
Details of my /etc/network/interfaces file 
# Standard Loopback Address
auto lo
iface lo inet loopback
# Set  ethernet to manual
#auto enp1s0
iface enp1s0 inet manual
# Set br0 static bridge
auto br0
iface br0 inet static
	address 192.168.1.100
	netmask 255.255.255.0
	gateway 192.168.1.1
	dns-nameservers 192.168.1.1
	bridge_ports enp1s0
	bridge_stp off
	bridge_maxwait 0
# end of /etc/network/interfaces file

After lxd installation and lxd init,  have reconfigured the lxd networking using following command.
sudo dpkg-reconfigure -p medium lxd
 
and directed lxd to use existing bridge.  This facilitates that the container can resides on the same network and I can access the containers in my local network.

Any solution is welcome. 

PS :  There should be a separate forum for lxd - which I am unable to find hence the issue raised in git.

**Comment by stgraber** [comment]
Hmm, LXD doesn't have any code which would mess with the default gateway, so this is a bit odd.

Can you include the content of your /etc/default/lxd-bridge file as well as the output of "sudo systemctl status lxd-bridge"?

Also, triple-check that NetworkManager isn't running on your system. Your manual configuration should have it stay away from those interfaces but that doesn't appear to always be the case and I've certainly seen it remove my default gateway in the past after bringing unrelated VPN interfaces up and down...

**Comment by techgsgithub** [comment]
Thanks for your attention.  

Listing of /etc/default/lxd-bridge 
# WARNING: This file is generated by a debconf template!
# It is recommended to update it by using "dpkg-reconfigure -p medium lxd"

# Whether to setup a new bridge or use an existing one
USE_LXD_BRIDGE="true"

# Bridge name
# This is still used even if USE_LXD_BRIDGE is set to false
# set to an empty value to fully disable
LXD_BRIDGE="br0"

# Update the "default" LXD profile
UPDATE_PROFILE="true"

# Path to an extra dnsmasq configuration file
LXD_CONFILE=""

# DNS domain for the bridge
LXD_DOMAIN="lxd"

# IPv4
## IPv4 address (e.g. 10.0.8.1)
LXD_IPV4_ADDR="192.168.1.100"

## IPv4 netmask (e.g. 255.255.255.0)
LXD_IPV4_NETMASK="255.255.255.0"

## IPv4 network (e.g. 10.0.8.0/24)
LXD_IPV4_NETWORK="192.168.1.100/24"

## IPv4 DHCP range (e.g. 10.0.8.2,10.0.8.254)
LXD_IPV4_DHCP_RANGE="192.168.1.101,192.168.1.125"

## IPv4 DHCP number of hosts (e.g. 250)
LXD_IPV4_DHCP_MAX="25"

## NAT IPv4 traffic
LXD_IPV4_NAT="true"

# IPv6
## IPv6 address (e.g. 2001:470:b368:4242::1)
LXD_IPV6_ADDR=""

## IPv6 CIDR mask (e.g. 64)
LXD_IPV6_MASK=""

## IPv6 network (e.g. 2001:470:b368:4242::/64)
LXD_IPV6_NETWORK=""

## NAT IPv6 traffic
LXD_IPV6_NAT="false"

# Run a minimal HTTP PROXY server
LXD_IPV6_PROXY="false"

Output for sudo systemctl status lxd-bridge.

sudo systemctl status lxd-bridge

● lxd-bridge.service - LXD - network bridge
   Loaded: loaded (/lib/systemd/system/lxd-bridge.service; static; vendor preset
   Active: active (exited) since Sat 2016-06-25 13:23:52 IST; 18min ago
     Docs: man:lxd(1)
  Process: 7933 ExecStart=/usr/lib/lxd/lxd-bridge.start (code=exited, status=0/S
 Main PID: 7933 (code=exited, status=0/SUCCESS)
    Tasks: 0
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/lxd-bridge.service

**Comment by stgraber** [comment]
So your bridge configuration looks invalid for a bridge that's defined outside of LXD.

USE_LXD_BRIDGE should be false

Can you re-run "dpkg-reconfigure -p medium lxd" and make sure you answer No to the first question, then tell it you already have an existing bridge?

**Comment by techgsgithub** [comment]
You are right ....  
I made necessary changes .. 
Its working as expected.
Thanks for your brilliant answer.
