### ISSUE TITLE
lxd container start error.

### ISSUE THREAD

**Issue by techgsgithub** [lxc/lxd#2157]
I was getting the error while starting any created container.

Finally it was solved using 
sudo lxc profile set default raw.lxc 'lxc.aa_allow_incomplete = 1'

This solution was found in searching net.

My Question 
1)  First of all, why it is required ?
2)  Is this right way to it ?
3)  Will it be corrected in near future instead of using hackish way ?
# Required information

 * Distribution: Ubuntu-mate
 * Distribution version:16.04 x64
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.6.2 ( latest one )
   * LXC version: 2.0.2
   * LXD version: 2.0.2
   * Storage backend in use: standard (ext4 ) and not zfs

**Comment by stgraber** [comment]
That's because you're running an unsupported kernel which doesn't include full apparmor support.

**Comment by stgraber** [comment]
Passing this flag tells LXC to start the container despite it not being properly contained by apparmor.

It's the only way to have LXC actually start the container for you on such a kernel.

**Comment by techgsgithub** [comment]
I agree with you.  Tried with stock kernel --- no issue found.
