### ISSUE TITLE
'lxd init' fails to set up ZFS on ARM

### ISSUE THREAD

**Issue by xose** [lxc/lxd#2158]
## Required information

 * Distribution: Ubuntu Server 16.04 ARM
 * Kernel version: 4.4.0-1012-raspi2
 * LXD version: 2.0.2-0ubuntu1~16.04.1

## Issue description

Using a clean install of the new ["classic" server image](http://blog.dustinkirkland.com/2016/06/howto-classic-apt-based-ubuntu-server.html) for Raspberry Pi.

I'm trying to initialize LXD with a ZFS loopback file, but it fails with an error complaining about the size of the ZFS device.

## Steps to reproduce

```
ubuntu@ubuntu:~$ sudo lxd init
Name of the storage backend to use (dir or zfs): zfs
Create a new ZFS pool (yes/no)? yes
Name of the new ZFS pool: lxd
Would you like to use an existing block device (yes/no)? no
Size in GB of the new loop device (1GB minimum): 8
Would you like LXD to be available over the network (yes/no)? no
Do you want to configure the LXD bridge (yes/no)? no
error: Failed to create the ZFS pool: cannot create 'lxd': one or more devices is less than the minimum size (64M)
```

## Information to attach

- The /var/lib/lxd/zfs.img file has the correct permissions but is 0 bytes long. I guess the f.Truncate() call is not working correctly.
- Running "zpool create ..." on that file fails with the previous error.

## Workaround:

```
ubuntu@ubuntu:~$ sudo truncate -s 8G /var/lib/lxd/zfs.img
ubuntu@ubuntu:~$ sudo zpool create lxd /var/lib/lxd/zfs.img -f -m none
ubuntu@ubuntu:~$ sudo lxd init
Name of the storage backend to use (dir or zfs): zfs
Create a new ZFS pool (yes/no)? no
Name of the existing ZFS pool or dataset: lxd
Would you like LXD to be available over the network (yes/no)? no
Do you want to configure the LXD bridge (yes/no)? no
LXD has been successfully configured.
```

EDIT: better to create the ZFS loopback file somewhere else for the workaround. `/var/lib/lxd/zfs.img` gets deleted after `lxd init`, so everything appears to work fine until the kernel panics a while later (found out the hard way) or you reboot the machine.

**Comment by stgraber** [comment]
So a simple Truncate test with Go 1.6 on ARM appears to work fine for me, creating a 16.04 system now to test again.
