### ISSUE TITLE
New Idea...

### ISSUE THREAD

**Issue by techgsgithub** [lxc/lxd#2159]
This is just a idea stuck but do not perceive as an issue.
Lxd is a system container.
Ipfire is a linux firewall distribution.  
Firewall container providing firewall services could be a great idea.
Only thing we need to tell the host system that it should use the container as the gateway.  

Especially when you can have container in containers.  So each container gives a single service of firewall .
Any takers ???

By the way,  where can i get documentation on how to create lxc/lxd image from iso ?  A link would be a great help.  I want to try myself.

**Comment by stgraber** [comment]
There is nothing preventing you from running a firewall inside a container. Many people do exactly that.

The documentation on the image format used by LXD can be found here: https://github.com/lxc/lxd/blob/master/doc/image-handling.md

**Comment by techgsgithub** [comment]
Nice.. thanks...
