### ISSUE TITLE
Creating container...error: shared's user has no subuids

### ISSUE THREAD

**Issue by guillaumevincent** [lxc/lxd#216]
Hi,

I try to follow the first step without any success.

```console
oslab@oslab:~$ lxc launch ubuntu
Creating container...error: shared's user has no subuids
```
I installed lxd (v0.1) from ppa on Ubuntu 14.04.2 LTS  dedicated server 
I'm running lxc (v0.1)

other info :

```console
oslab@oslab:~$ uname -a
Linux oslab 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
oslab@oslab:~$ cat /etc/subuid
oslab:165536:65536
oslab@oslab:~$ cat /etc/subgid
oslab:165536:65536
oslab@oslab:~$ lxc-start --name ubuntu
lxc-start: lxc_start.c: main: 295 Executing '/sbin/init' with no configuration file may crash the host
oslab@oslab:~$ lxc-start --name ubuntu -f config
lxc-start: lxc_start.c: main: 252 Failed to load rcfile
```

```console
-rw-r--r--  1 root root     19 Feb 21 09:38 subgid
-rw-r--r--  1 root root     19 Feb 21 09:38 subuid
```

what I'm doing wrong ?

**Comment by stgraber** [comment]
Hi,

We'll be updating the packages to do that automatically soon, but currently you need to add a uid and gid allocation for the root user in /etc/subuid and /etc/subgid.

Typically the following line in both files will do the trick:
    root:165536:65536

**Comment by guillaumevincent** [comment]
Thank you @stgraber 
add `root:165536:65536` in `/etc/subuid` and `/etc/subgid` do the trick 
Restart my server and bingo :+1: 

```console
root@oslab:~# lxc launch ubuntu
Creating container...done
Starting container...done
```
