### ISSUE TITLE
debug symbols in ubuntu

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2160]
Can someone provide lxd debug symbols for recent lxd version (2.0.2)
I can't see them in the repository.

**Comment by stgraber** [comment]
Ubuntu splits the debug symbols at build time and puts them in special -dbgsym packages available in a separate package repository. See https://wiki.ubuntu.com/DebuggingProgramCrash

**Comment by upuvvad1** [comment]
Yes.
lxd-dbgsym is available for older version of lxd( = 2.0.1-0ubuntu1~16.04.1), but not for the recent version of 2.0.2

sudo apt-get install lxd-dbgsym 

The following packages have unmet dependencies:
 lxd-dbgsym : Depends: lxd (= 2.0.1-0ubuntu1~16.04.1) but 2.0.2-0ubuntu1~16.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

And also  lxd 2.0.1-0ubuntu1 is not available in the repository.

**Comment by stgraber** [comment]
Ok, looks like there's an issue with whatever's generating ddebs.ubuntu.com.

I pinged @martinpitt about it.

In the mean time, you can find them on Launchpad directly: https://launchpad.net/ubuntu/xenial/+package/lxd-dbgsym

**Comment by stgraber** [comment]
```
15:21 < cjwatson> ddeb-retriever has been having trouble for a while though I can't remember quite how long
15:21 < cjwatson> I killed it today to see if it'll catch up
```
