### ISSUE TITLE
lxc image copy ubuntu:xenial host1: --alias xenial --auto-update fails

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#2162]
```
+ lxc image copy ubuntu:xenial host1: --alias xenial --auto-update
error: Error adding alias xenial: not found
```

reverting 719da1be34c2617af5e8cc305a0eecad9b25fbf8 makes it work again.

**Comment by stgraber** [comment]
So presumably your client is on current git and host1 isn't?

**Comment by stgraber** [comment]
Hmm, though I really wouldn't expect it to matter in this case...

**Comment by tych0** [comment]
They were both on current git.
