### ISSUE TITLE
lxc copy does not change new container hostname

### ISSUE THREAD

**Issue by naisanza** [lxc/lxd#2169]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 Desktop
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-22-generic
   * LXC version: 2.0.2
   * LXD version: 2.0.2
   * Storage backend in use: ZFS

# Issue description

When copying a container, the new container's hostname does not change to the new container name

# Steps to reproduce

 1. Create new base container
 2. Copy container
 3. `lxc exec` <container-name> hostname

**Comment by stgraber** [comment]
```
stgraber@dakara:~/data/code/lxc$ lxc launch ubuntu:16.04 test
Creating test
Retrieving image: 100%
Starting test
stgraber@dakara:~/data/code/lxc$ lxc exec test -- hostname
test
stgraber@dakara:~/data/code/lxc$ lxc copy test blah
stgraber@dakara:~/data/code/lxc$ lxc start blah
stgraber@dakara:~/data/code/lxc$ lxc exec blah -- hostname
blah
```

**Comment by stgraber** [comment]
Note that since the hostname is updated by cloud-init in the container, it can take a few seconds for it to happen. Also, if cloud-init fails for some reason (such as an invalid user.user-data or user.vendor-data key), the hostname may not update.

**Comment by naisanza** [comment]
@stgraber it seems to have issues copying a container when it's running. It copies the container, but has certain filelocks to the originating container. If the proper way is to stop the container first, it shouldn't let you copy the container while it's running

This is the error when using `hostnamectl set-hostname <name>`on the copied container:

```
root@base-elasticsearch-2-3-4:~# hostnamectl set-hostname test
Could not set property: Failed to activate service 'org.freedesktop.hostname1': timed out
```

Relevant dmesg error:

```
[238636.188439] audit: type=1400 audit(1470025546.222:333): apparmor="DENIED" operation="file_lock" profile="lxd-base-elasticsearch-2-3-4_</var/lib/lxd>" pid=22164 comm="(ostnamed)" family="unix" sock_type="dgram" protocol=0 addr=none
```

It's useful to copy a container while it's running, because I have all the containers auto boot, and if that flag is set, it's also going to boot the base images you cloned the container from. 

`base image: f452cda3bccb2903e56d53e402b9d35334b4276783d098a879be5d74b04e62e2`
