### ISSUE TITLE
Meaning of httpAddr

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2170]
I am trying to implement a command to forward port from container. I don't get what `httpAddr` field in command structure does - it is not referenced anywhere.

https://github.com/lxc/lxd/blob/master/lxc/finger.go#L9

**Comment by tych0** [comment]
On Fri, Jul 01, 2016 at 02:10:42AM -0700, anatoly techtonik wrote:
> I am trying to implement a command to forward port from container. I don't get what `httpAddr` field in command structure does - it is not referenced anywhere.
> 
> https://github.com/lxc/lxd/blob/master/lxc/finger.go#L9

looks like it is unused, I just sent a patch to remove it.
