### ISSUE TITLE
Container fails to start after reconfiguring the bridge interface

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#2177]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * The output of "lxc info" or if that fails: 
```
error: Error calling 'lxd forkstart test /var/lib/lxd/containers /var/log/lxd/test/lxc.conf': err='exit status 1'
Try `lxc info --show-log test` for more info
```

   * Kernel version: 3.19.0-25-generic
   * LXC version:
   * LXD version: 2.0.3
   * Storage backend in use: dir

# Issue description
After reconfiguring the bridge IP address/range with `sudo dpkg-reconfigure -p medium lxd` container stops to start (see above)
And here the failed error message:

``` 
lxc_conf - conf.c:instantiate_veth:2595 - failed to attach 'vethRHIJUE' to the bridge 'lxdbr0': Operation not permitted
            lxc 20160703181857.666 ERROR    lxc_conf - conf.c:lxc_create_network:2872 - failed to create netdev
            lxc 20160703181857.666 ERROR    lxc_start - start.c:lxc_spawn:1080 - failed to create the network
            lxc 20160703181857.666 ERROR    lxc_start - start.c:__lxc_start:1353 - failed to spawn 'test'
```

# Steps to reproduce

 1. stop all running container
 2. run `sudo dpkg-reconfigure -p medium lxd`
 3. Try to start container

**Comment by stgraber** [comment]
That usually happens when your bridge configuration is invalid. The current setup mechanism can't do much sanity checking unfortunately (we're working on that).

Can you paste the content of /etc/default/lxd-bridge and the output of "systemctl status lxd-bridge"?

**Comment by huegelc** [comment]
```
# WARNING: This file is generated by a debconf template!
# It is recommended to update it by using "dpkg-reconfigure -p medium lxd"

# Whether to setup a new bridge or use an existing one
USE_LXD_BRIDGE="true"

# Bridge name
# This is still used even if USE_LXD_BRIDGE is set to false
# set to an empty value to fully disable
LXD_BRIDGE="lxdbr0"

# Update the "default" LXD profile
UPDATE_PROFILE="true"

# Path to an extra dnsmasq configuration file
LXD_CONFILE=""

# DNS domain for the bridge
LXD_DOMAIN="lxd"

# IPv4
## IPv4 address (e.g. 10.0.8.1)
LXD_IPV4_ADDR="10.0.3.1"

## IPv4 netmask (e.g. 255.255.255.0)
LXD_IPV4_NETMASK="255.255.255.0"

## IPv4 network (e.g. 10.0.8.0/24)
LXD_IPV4_NETWORK="10.0.3.1/24"

## IPv4 DHCP range (e.g. 10.0.8.2,10.0.8.254)
LXD_IPV4_DHCP_RANGE="10.0.3.20,10.0.3.254"

## IPv4 DHCP number of hosts (e.g. 250)
LXD_IPV4_DHCP_MAX="232"

## NAT IPv4 traffic
LXD_IPV4_NAT="true"

# IPv6
## IPv6 address (e.g. 2001:470:b368:4242::1)
LXD_IPV6_ADDR="fd63:dde7:1295:657d::1"

## IPv6 CIDR mask (e.g. 64)
LXD_IPV6_MASK="64"

## IPv6 network (e.g. 2001:470:b368:4242::/64)
LXD_IPV6_NETWORK="fd63:dde7:1295:657d::1/64"

## NAT IPv6 traffic
LXD_IPV6_NAT="true"

# Run a minimal HTTP PROXY server
LXD_IPV6_PROXY="false"
```
Ubuntu 14.04 doesn´ t use systemd

ifconfig 

```
lxcbr0    Link encap:Ethernet  HWaddr 96:70:6d:c5:bd:80  
          inet addr:10.0.3.1  Bcast:10.0.3.255  Mask:255.255.255.0
          inet6 addr: fe80::9470:6dff:fec5:bd80/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:205 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:45259 (45.2 KB)
```

**Comment by huegelc** [comment]
OK, I´ve deleted all lxc/lxd packages. I must say lxc/lxd leaves a pretty mess behind. Configuration files aren´t removed 
+ `/etc/defaults/lxc*` 
+ ` /var/lib/lxc`
+ iptables NAT
etc
then with `ip link set lxcbr0 down` and `brctl delbr lxcbr0` deleted the bridge

After a reboot I could reconfigure the lxd bridge.

**Comment by stgraber** [comment]
Sounds like it was some invalid config or conflict between lxcbr0/lxdbr0.
