### ISSUE TITLE
TLS handshake error with lxc list remote:

### ISSUE THREAD

**Issue by cruejones** [lxc/lxd#2186]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-29-generic
   * LXC version: 2.0.3
   * LXD version: 2.0.3
   * Storage backend in use: ZFS

# Issue description

ubuntu@darthbawlz:~$ date; lxc list darthbawlz:
Thu Jul  7 15:24:47 UTC 2016
+-----------+--------------+-----------------------+------+------------+--------------------+
|   NAME    |  STATE  |         IPV4          | IPV6 |    TYPE    | SNAPSHOTS |
+-----------+----------------+-----------------------+------+------------+-------------------+
| container | RUNNING | 10.241.125.214 (eth0) |      | PERSISTENT | 0         |
+-----------+----------------+-------------------------------+------+------------+----------------------+

ubuntu@darthbawlz:~$ tail -1 /var/log/syslog
Jul  7 15:24:47 darthbawlz lxd[2276]: 2016/07/07 15:24:47 http: TLS handshake error from 172.16.0.5:52524: EOF

ubuntu@darthbawlz:~$ lxc remote list | grep darthbawlz
| darthbawlz      | https://darthbawlz.maas:8443             | lxd           | NO     | NO     |

**Comment by stgraber** [comment]
Yeah, I've noticed some of those too, they don't seem to impact performance at all but it's still a bit weird.

It's probably caused by the multi-threading code of lxc list somehow upsetting the daemon.

**Comment by stgraber** [comment]
Reproduced reliably over https, not reproducible over unix socket.
