### ISSUE TITLE
lxd registry is not reachable.

### ISSUE THREAD

**Issue by kunalkushwaha** [lxc/lxd#219]
I understand, now LXD remote images wont be part of LXD, and third party tool will be used for managing images from remote servers.

I was thinking, and reusing my code for building that third party tool for remote image management.

But https://registry.linuxcontainers.org/ is unreachable. Will such registry wont be part of official protocol for LXC images?

**Comment by stgraber** [comment]
Hi,

The registry isn't needed anymore as it was a way to aggregate remote image servers for the client. As the client no longer knows about those, the server wasn't needed anymore.

Instead what will replace that mechanism is:
 - The https://images.linuxcontainers.org itself will start offering a minimal version of the LXD API to act as an image server which LXD can use.
 - We'll have a few scripts in the main LXD tree which will pull cloud images (or similar minimal images) for a set of Linux distributions, convert them to be valid LXD images (per specs/image-handling.md) and push them to LXD's image store.
