### ISSUE TITLE
Improve error reporting when bridge does not exist

### ISSUE THREAD

**Issue by candlerb** [lxc/lxd#2190]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info"

~~~
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: <<snip>>
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-28-generic
  server: lxd
  serverpid: 2178
  serverversion: 2.0.2
  storage: zfs
  storageversion: "5"
config:
  images.auto_update_cached: "false"
  images.auto_update_interval: "0"
  storage.zfs_pool_name: lxd
public: false
~~~

# Issue description

If you assign an instance to a bridge which does not exist, then it fails to start. However the error message returned is not helpful: `Error calling 'lxd forkstart ...': err='exit status 1'`

# Steps to reproduce

* Create a profile which points to a non-existent bridge
* Launch an instance which uses this profile. It fails.

~~~
# lxc start nagios1
error: Error calling 'lxd forkstart nagios1 /var/lib/lxd/containers /var/log/lxd/nagios1/lxc.conf': err='exit status 1'
Try `lxc info --show-log nagios1` for more info
~~~

The `--show-log` output is very verbose. If you filter it down to just ERROR lines then the error *does* appear:

~~~
# lxc info --show-log nagios1 | grep ERROR
            lxc 20160708102038.108 ERROR    lxc_conf - conf.c:instantiate_veth:2595 - failed to attach 'veth0XL36W' to the bridge 'br-int1': Operation not permitted
            lxc 20160708102038.131 ERROR    lxc_conf - conf.c:lxc_create_network:2872 - failed to create netdev
            lxc 20160708102038.131 ERROR    lxc_start - start.c:lxc_spawn:1080 - failed to create the network
            lxc 20160708102038.131 ERROR    lxc_start - start.c:__lxc_start:1353 - failed to spawn 'nagios1'
~~~

...although to be 100% accurate, the error is not that permission is denied, but that the bridge does not exist at all.

Ideas:

* For this particular error, lxc start could test for the existence of the necessary bridge(s) before trying to start the instance, and then return a better error via the API. This would also help cases when starting instances via the API (in particular, the ansible lxd_container module)
* More generally, logs of ERROR and above could be displayed to stderr automatically - although that's mainly of help for CLI users

In addition, the "failed to attach ... to the bridge" error could be more specific than "Operation not permitted". I thought this could simply be the return code from [SIOCBRADDIF](https://github.com/lxc/lxc/blob/master/src/lxc/network.c#L1480)

However, brctl is able to make the distinction:

~~~
# brctl addif foo eth0
bridge foo does not exist!
~~~~

and strace on this command shows ENODEV as the result:

~~~
socket(PF_LOCAL, SOCK_STREAM, 0)        = 3
access("/proc/net", R_OK)               = 0
access("/proc/net/unix", R_OK)          = 0
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 4
ioctl(4, SIOCGIFINDEX, {ifr_name="eth0", }) = 0
close(4)                                = 0
ioctl(3, SIOCBRADDIF)                   = -1 ENODEV (No such device)
ioctl(3, SIOCDEVPRIVATE, 0x7ffde2c1e040) = -1 ENODEV (No such device)
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 4
ioctl(4, SIOCGIFINDEX, {ifr_name="eth0", }) = 0
close(4)                                = 0
write(2, "bridge foo does not exist!\n", 27bridge foo does not exist!
) = 27
exit_group(1)                           = ?
+++ exited with 1 +++
~~~

**Comment by stgraber** [comment]
brctl uses the old kernel API, LXC talks directly over netlink, so I suspect the netlink error is a bit different.

**Comment by candlerb** [comment]
I grepped for the message "failed to attach" in the lxd and lxc trees, and I could only find it in [instantiate_veth](https://github.com/lxc/lxc/blob/master/src/lxc/conf.c#L2595) which in turn calls [lxc_bridge_attach](https://github.com/lxc/lxc/blob/master/src/lxc/network.c#L1458) and that appears to use ioctl() rather than netlink - although there's a lot of other netlink code in that file.

But maybe I have missed something?
