### ISSUE TITLE
On image pull request - Not enough space problem

### ISSUE THREAD

**Issue by rst0git** [lxc/lxd#2194]
# Required information

 * Distribution:  Ubuntu Server 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
  * driver: lxc
  * driverversion: 2.0.1
  * kernel: Linux
  * kernelarchitecture: x86_64
  * kernelversion: 4.4.0-28-generic
  * server: lxd
  * serverpid: 2674
  * serverversion: 2.0.2
  * storage: zfs
  storageversion: "5"

# Issue description:
Not enough space in the zfs pool, makes LXD to stop the download process of the image with Fail message in "lxc monitor". However, the "incomplete" files that were downloaded in '/var/lib/lxd/images/'  are filling the zfs pool but since the "image copy" operation was not complete, they are not visible by lxd ("lxc image list"). So, LXD is not able to delete them with "lxc delete".
 
To solve this:
- LXD should check if there is enough space on the zfs pool before start the download process, and somehow reserve that space.
- When the image download process fails: either pause and then continue (if it is a connection problem) or delete the incomplete files (if the problem is not the connection).
 

# Steps to reproduce:

1. **Step one:** Make a few POST requests to https://**server**:**port**/1.0/images,  on LXD instance with  _**small**_ zfs pool:

Example:
```
{
"public": false,
"auto_update": true, 
"properties": {
                           "os": "...", 
},
"source": {
                      "type": "image",
                      "mode": "pull",  
                       "server": "...", 
                       "protocol": "lxd",
                       "alias": "..."      
    } 
}
```

2. **Step two**: Wait until the download process fails, because of "Not enough space".

3. **Step three**: Chack the zfs pool status with "zpool list", check how much images were copied with "lxc image list".

**Comment by sean-jc** [comment]
Can you provide the output from `lxc image list`, `sudo zfs list`, `sudo ls -l /var/lib/lxd/images` and `sudo tail -n 50 /var/log/lxd/lxd.log` after a failed image pull?  I can partially reproduce the failure, but I only end up with a dangling empty subvolume directory, I don't see significant disk usage from the failed pull.
