### ISSUE TITLE
error: Error calling 'lxd forkstart key-scale-ms-2 /var/lib/lxd/containers /var/log/lxd/key-scale-ms-2/lxc.conf': err='exit status 1'

### ISSUE THREAD

**Issue by Schachte** [lxc/lxd#2196]
# Required information

  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.16.0-76-generic
  server: lxd
  serverpid: 1443
  serverversion: 2.0.3
  storage: dir
  storageversion: ""
config:
  core.https_address: 127.0.0.1:8444
public: false

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

# Issue description

Launching custom container image yields forkstart failure

# Steps to reproduce

 1. import the custom image
 2. lxc launch image-name container-name
 3. error: Error calling 'lxd forkstart key-scale-ms-2 /var/lib/lxd/containers /var/log/lxd/key-scale-ms-2/lxc.conf': err='exit status 1'

# Log Information

Name: key-scale-ms-2
Architecture: x86_64
Created: 2016/07/10 15:14 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:
Name: tester3
Architecture: x86_64
Created: 2016/07/10 15:43 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20160710154410.984 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160710154410.985 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 8
            lxc 20160710154410.990 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /var/lib/lxd/containers tester3
            lxc 20160710154410.990 INFO     lxc_utils - utils.c:setproctitle:1460 - setting cmdline failed - Invalid argument
            lxc 20160710154410.991 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 8
            lxc 20160710154410.991 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for reject_force_umount action 0
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for reject_force_umount action 0
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .[all].
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .kexec_load errno 1.
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for kexec_load action 327681
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for kexec_load action 327681
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .open_by_handle_at errno 1.
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for open_by_handle_at action 327681
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for open_by_handle_at action 327681
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .init_module errno 1.
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for init_module action 327681
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for init_module action 327681
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .finit_module errno 1.
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for finit_module action 327681
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for finit_module action 327681
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .delete_module errno 1.
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for delete_module action 327681
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for delete_module action 327681
            lxc 20160710154410.992 INFO     lxc_seccomp - seccomp.c:parse_config_v2:456 - Merging in the compat seccomp ctx into the main one
            lxc 20160710154410.992 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 6 start' for container 'tester3', config section 'lxc'
            lxc 20160710154410.994 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160710154410.994 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 8
            lxc 20160710154410.998 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/d78a9d7e97b4b375//var/lib/lxd/containers
            lxc 20160710154411.118 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
            lxc 20160710154411.119 DEBUG    lxc_console - console.c:lxc_console_peer_default:469 - no console peer
            lxc 20160710154411.119 INFO     lxc_start - start.c:lxc_init:488 - 'tester3' is initialized
            lxc 20160710154411.120 DEBUG    lxc_start - start.c:__lxc_start:1326 - Not dropping cap_sys_boot or watching utmp
            lxc 20160710154411.120 INFO     lxc_start - start.c:resolve_clone_flags:1013 - Cloning a new user namespace
            lxc 20160710154411.123 DEBUG    lxc_conf - conf.c:instantiate_veth:2614 - instantiated veth 'vethAXBBAV/vethDYADF2', index is '14'
            lxc 20160710154411.123 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for tester3
            lxc 20160710154411.130 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 3442336 range 65536
            lxc 20160710154411.130 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 3442336 range 65536
            lxc 20160710154411.188 DEBUG    lxc_conf - conf.c:lxc_assign_network:3048 - move 'eth0' to '26355'
            lxc 20160710154411.188 NOTICE   lxc_start - start.c:do_start:777 - switching to gid/uid 0/0 in new user namespace
            lxc 20160710154411.189 DEBUG    lxc_conf - conf.c:setup_rootfs:1215 - mounted '/var/lib/lxd/containers/tester3/rootfs' on '/usr/lib/x86_64-linux-gnu/lxc'
            lxc 20160710154411.189 INFO     lxc_conf - conf.c:setup_utsname:843 - 'tester3' hostname has been setup
            lxc 20160710154411.212 DEBUG    lxc_conf - conf.c:setup_hw_addr:2145 - mac address '00:16:3e:24:b0:10' on 'eth0' has been setup
            lxc 20160710154411.212 DEBUG    lxc_conf - conf.c:setup_netdev:2372 - 'eth0' has been setup
            lxc 20160710154411.212 INFO     lxc_conf - conf.c:setup_network:2393 - network has been setup
            lxc 20160710154411.212 INFO     lxc_conf - conf.c:mount_autodev:1072 - Mounting container /dev
            lxc 20160710154411.212 INFO     lxc_conf - conf.c:mount_autodev:1095 - Mounted tmpfs onto /usr/lib/x86_64-linux-gnu/lxc/dev
            lxc 20160710154411.212 INFO     lxc_conf - conf.c:mount_autodev:1113 - Mounted container /dev
            lxc 20160710154411.213 ERROR    lxc_utils - utils.c:safe_mount:1692 - Operation not permitted - Failed to mount proc onto /usr/lib/x86_64-linux-gnu/lxc/proc
            lxc 20160710154411.213 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:743 - Operation not permitted - error mounting proc on /usr/lib/x86_64-linux-gnu/lxc/proc flags 14
            lxc 20160710154411.213 ERROR    lxc_conf - conf.c:lxc_setup:3721 - failed to setup the automatic mounts for 'tester3'
            lxc 20160710154411.213 ERROR    lxc_start - start.c:do_start:833 - failed to setup the container
            lxc 20160710154411.213 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20160710154411.213 WARN     lxc_conf - conf.c:lxc_delete_network:2909 - failed to remove interface 14 'eth0'
            lxc 20160710154411.213 ERROR    lxc_start - start.c:__lxc_start:1353 - failed to spawn 'tester3'
            lxc 20160710154411.256 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'tester3', config section 'lxc'
            lxc 20160710154411.764 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 6 stop' for container 'tester3', config section 'lxc'
            lxc 20160710154411.883 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160710154411.883 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160710154411.901 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 3442336 range 65536
            lxc 20160710154411.901 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 3442336 range 65536
            lxc 20160710154530.697 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 3442336 range 65536
            lxc 20160710154530.697 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 3442336 range 65536
            lxc 20160710154530.701 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 3442336 range 65536
            lxc 20160710154530.701 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 3442336 range 65536

**Comment by Schachte** [comment]
I did the following : chmod +x /var/lib/lxd

**Comment by stgraber** [comment]
That chmod shouldn't be necessary at all as /var/lib/lxd should already be 755 by default.

How did you create the image exactly?

**Comment by stgraber** [comment]
And what's the output of "ls -lh /var/lib/lxd/containers/key-scale-ms-2/rootfs"?


The updated logs now match your other issue, that is, the kernel refuses to mount /proc:

        lxc 20160710154411.213 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:743 - Operation not permitted - error mounting proc on /usr/lib/x86_64-linux-gnu/lxc/proc flags 14

**Comment by stgraber** [comment]
This can either be a kernel issue (see #2195) or maybe it's because your image's rootfs is very wrong and is somehow lacking a proc directory for LXC to mount procfs on.

**Comment by Schachte** [comment]
Basically I just published it, exported as a tarball and transferred the tarball to the server. I tried two different machines, same issue. How can I fix the rootfs issue?

**Comment by Schachte** [comment]
I also tried with a standard 14.04 and 16 Ubuntu image. Issue on both.

**Comment by Schachte** [comment]
**output of ls -ls /var/lib/lxd/containers/key-scale-ms-2/rootfs**

total 80K
drwxr-xr-x  2 3442336 3442336 4.0K Jun 27 21:08 bin
drwxr-xr-x  3 3442336 3442336 4.0K Jun 27 21:26 boot
drwxr-xr-x  6 3442336 3442336 4.0K Jun 27 21:26 dev
drwxr-xr-x 88 3442336 3442336 4.0K Jun 27 21:26 etc
drwxr-xr-x  2 3442336 3442336 4.0K Apr 10  2014 home
drwxr-xr-x 19 3442336 3442336 4.0K Jun 27 21:26 lib
drwxr-xr-x  2 3442336 3442336 4.0K Jun 27 20:59 lib64
drwx------  2 3442336 3442336 4.0K Jun 27 21:09 lost+found
drwxr-xr-x  2 3442336 3442336 4.0K Jun 27 20:57 media
drwxr-xr-x  2 3442336 3442336 4.0K Apr 10  2014 mnt
drwxr-xr-x  2 3442336 3442336 4.0K Jun 27 20:57 opt
drwxr-xr-x  2 3442336 3442336 4.0K Apr 10  2014 proc
drwx------  2 3442336 3442336 4.0K Jun 27 21:08 root
drwxr-xr-x  3 3442336 3442336 4.0K Jun 27 21:09 run
drwxr-xr-x  2 3442336 3442336 4.0K Jun 27 21:08 sbin
drwxr-xr-x  2 3442336 3442336 4.0K Jun 27 20:57 srv
drwxr-xr-x  2 3442336 3442336 4.0K Mar 13  2014 sys
drwxrwxrwt  2 3442336 3442336 4.0K Jun 27 21:26 tmp
drwxr-xr-x 10 3442336 3442336 4.0K Jun 27 20:57 usr
drwxr-xr-x 12 3442336 3442336 4.0K Jun 27 21:08 var

**Comment by stgraber** [comment]
Ok, so /proc does exist and all the paths look correct for an unprivileged container.

That failures to mount proc makes me think of a kernel issue...

Any chance you can install "linux-generic-lts-xenial" and reboot so you can test again with a 4.4 kernel?

**Comment by stgraber** [comment]
We do support 3.13 for LXD, but it comes with quite a few less features around resource management and is quite a bit slower when running Ubuntu 16.04 containers due to not having the cgroup namespace feature which was introduced in 4.4.

Overall since our main supported platform is Ubuntu 16.04, it's best to use the Ubuntu 16.04 kernel (4.4) whenever possible.

**Comment by Schachte** [comment]
@stgraber I'm not very experienced with this and pretty sure my attempt to downgrade the kernel on 1/2 of my dev machines took it down... Can you explain how I can upgrade this? I only have ssh access and outbound connections are blocked on the machine. . .

**Comment by stgraber** [comment]
So you'd need to install "linux-signed-generic-lts-xenial" which will at the very least bring:

```
ii  linux-headers-4.4.0-28                4.4.0-28.47~14.04.1               all          Header files related to Linux kernel version 4.4.0
ii  linux-headers-4.4.0-28-generic        4.4.0-28.47~14.04.1               amd64        Linux kernel headers for version 4.4.0 on 64 bit x86 SMP
ii  linux-headers-generic-lts-xenial      4.4.0.28.18                       amd64        Generic Linux kernel headers
ii  linux-image-4.4.0-28-generic          4.4.0-28.47~14.04.1               amd64        Linux kernel image for version 4.4.0 on 64 bit x86 SMP
ii  linux-image-extra-4.4.0-28-generic    4.4.0-28.47~14.04.1               amd64        Linux kernel extra modules for version 4.4.0 on 64 bit x86 SMP
ii  linux-signed-generic-lts-xenial       4.4.0.28.18                       amd64        Complete Signed Generic Linux kernel and headers
ii  linux-signed-image-4.4.0-28-generic   4.4.0-28.47~14.04.1               amd64        Signed kernel image generic
ii  linux-signed-image-generic-lts-xenial 4.4.0.28.18                       amd64        Signed Generic Linux kernel image
```

So having your machine be able to access one of the Ubuntu archive mirrors is kinda critical as manually downloading all of those and installing them by hand would be a lot of pain.

Once installed, rebooting will have grub pick the latest kernel and boot it.

**Comment by Schachte** [comment]
@stgraber Bummer. I'll have to ping the server admin tomorrow and see if we can upgrade the kernel. I'll update this issue to see if it fixes the mounting problem. Thanks for the help.

**Comment by stgraber** [comment]
In general you really want some way to reach the Ubuntu archive on your system, if only for bugfix and security updates of things like LXD itself, so having a hole punched through your firewall or have some kind of http proxy setup for it is usually a good idea.

**Comment by Schachte** [comment]
@stgraber For the time being. Every server I import the image into, any time I launch, the first log of errors outputs:

```
            lxc 20160710201353.956 NOTICE   lxc_start - start.c:do_start:777 - switching to gid/uid 0/0 in new user namespace
            lxc 20160710201353.956 ERROR    lxc_start - start.c:print_top_failing_dir:112 - Permission denied - could not access /var/lib/lxd.  Please grant it 'x' access, or add an ACL for the container root.
            lxc 20160710201353.956 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20160710201353.956 WARN     lxc_conf - conf.c:lxc_delete_network:2909 - failed to remove interface 10 'eth0'
            lxc 20160710201353.956 ERROR    lxc_start - start.c:__lxc_start:1353 - failed to spawn 'key-scale'
            lxc 20160710201353.991 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'key-scale', config se
```

**Comment by stgraber** [comment]
What's the output of "stat /var/lib/lxd"?

**Comment by Schachte** [comment]
`  File: '/var/lib/lxd'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 806h/2054d	Inode: 3934969     Links: 9
Access: (0700/drwx------)  Uid: (  105/     lxd)   Gid: (65534/ nogroup)
Access: 2016-07-10 20:06:05.247231287 +0000
Modify: 2016-07-10 20:13:53.893118969 +0000
Change: 2016-07-10 20:13:53.893118969 +0000
 Birth: -`

**Comment by stgraber** [comment]
Well, that's odd, it should be 0711

**Comment by stgraber** [comment]
Let me try a clean install on 14.04 to make sure we didn't screw this up somehow.

**Comment by stgraber** [comment]
```
root@trusty-cloud:~# apt -t trusty-backports install lxd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfreetype6 os-prober
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  acl cgroup-lite dnsmasq-base liblxc1 liblzo2-2 libmnl0
  libnetfilter-conntrack3 libseccomp2 lxc-common lxcfs lxd-client
  squashfs-tools uidmap
Suggested packages:
  criu lxd-tools
The following NEW packages will be installed:
  acl cgroup-lite dnsmasq-base liblxc1 liblzo2-2 libmnl0
  libnetfilter-conntrack3 libseccomp2 lxc-common lxcfs lxd lxd-client
  squashfs-tools uidmap
0 upgraded, 14 newly installed, 0 to remove and 2 not upgraded.
Need to get 6756 kB of archives.
After this operation, 31.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-backports/main cgroup-lite all 1.11~ubuntu14.04.2 [4084 B]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-backports/main lxc-common amd64 2.0.3-0ubuntu1~ubuntu14.04.1 [28.1 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty-backports/main libseccomp2 amd64 2.2.3-2ubuntu1~ubuntu14.04.1 [38.5 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty-backports/main liblxc1 amd64 2.0.3-0ubuntu1~ubuntu14.04.1 [196 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main liblzo2-2 amd64 2.06-1.2ubuntu1.1 [46.1 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ trusty/main acl amd64 2.2.52-1 [43.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty/main libmnl0 amd64 1.0.3-3ubuntu1 [11.4 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ trusty/main libnetfilter-conntrack3 amd64 1.0.4-1 [45.9 kB]
Get:9 http://archive.ubuntu.com/ubuntu/ trusty-updates/main dnsmasq-base amd64 2.68-1ubuntu0.1 [257 kB]
Get:10 http://archive.ubuntu.com/ubuntu/ trusty-backports/universe lxcfs amd64 2.0.2-0ubuntu1~ubuntu14.04.1 [34.9 kB]
Get:11 http://archive.ubuntu.com/ubuntu/ trusty-updates/main squashfs-tools amd64 1:4.2+20130409-2ubuntu0.14.04.1 [90.8 kB]
Get:12 http://archive.ubuntu.com/ubuntu/ trusty-updates/main uidmap amd64 1:4.1.5.1-1ubuntu9.2 [62.1 kB]
Get:13 http://archive.ubuntu.com/ubuntu/ trusty-backports/universe lxd amd64 2.0.3-0ubuntu2~ubuntu14.04.1 [4058 kB]
Get:14 http://archive.ubuntu.com/ubuntu/ trusty-backports/universe lxd-client amd64 2.0.3-0ubuntu2~ubuntu14.04.1 [1838 kB]
Fetched 6756 kB in 8s (779 kB/s)                                               
Preconfiguring packages ...
Selecting previously unselected package cgroup-lite.
(Reading database ... 25003 files and directories currently installed.)
Preparing to unpack .../cgroup-lite_1.11~ubuntu14.04.2_all.deb ...
Unpacking cgroup-lite (1.11~ubuntu14.04.2) ...
Selecting previously unselected package lxc-common.
Preparing to unpack .../lxc-common_2.0.3-0ubuntu1~ubuntu14.04.1_amd64.deb ...
Unpacking lxc-common (2.0.3-0ubuntu1~ubuntu14.04.1) ...
Selecting previously unselected package libseccomp2:amd64.
Preparing to unpack .../libseccomp2_2.2.3-2ubuntu1~ubuntu14.04.1_amd64.deb ...
Unpacking libseccomp2:amd64 (2.2.3-2ubuntu1~ubuntu14.04.1) ...
Selecting previously unselected package liblxc1.
Preparing to unpack .../liblxc1_2.0.3-0ubuntu1~ubuntu14.04.1_amd64.deb ...
Unpacking liblxc1 (2.0.3-0ubuntu1~ubuntu14.04.1) ...
Selecting previously unselected package liblzo2-2:amd64.
Preparing to unpack .../liblzo2-2_2.06-1.2ubuntu1.1_amd64.deb ...
Unpacking liblzo2-2:amd64 (2.06-1.2ubuntu1.1) ...
Selecting previously unselected package acl.
Preparing to unpack .../acl_2.2.52-1_amd64.deb ...
Unpacking acl (2.2.52-1) ...
Selecting previously unselected package libmnl0:amd64.
Preparing to unpack .../libmnl0_1.0.3-3ubuntu1_amd64.deb ...
Unpacking libmnl0:amd64 (1.0.3-3ubuntu1) ...
Selecting previously unselected package libnetfilter-conntrack3:amd64.
Preparing to unpack .../libnetfilter-conntrack3_1.0.4-1_amd64.deb ...
Unpacking libnetfilter-conntrack3:amd64 (1.0.4-1) ...
Selecting previously unselected package dnsmasq-base.
Preparing to unpack .../dnsmasq-base_2.68-1ubuntu0.1_amd64.deb ...
Unpacking dnsmasq-base (2.68-1ubuntu0.1) ...
Selecting previously unselected package lxcfs.
Preparing to unpack .../lxcfs_2.0.2-0ubuntu1~ubuntu14.04.1_amd64.deb ...
Unpacking lxcfs (2.0.2-0ubuntu1~ubuntu14.04.1) ...
Selecting previously unselected package squashfs-tools.
Preparing to unpack .../squashfs-tools_1%3a4.2+20130409-2ubuntu0.14.04.1_amd64.deb ...
Unpacking squashfs-tools (1:4.2+20130409-2ubuntu0.14.04.1) ...
Selecting previously unselected package uidmap.
Preparing to unpack .../uidmap_1%3a4.1.5.1-1ubuntu9.2_amd64.deb ...
Unpacking uidmap (1:4.1.5.1-1ubuntu9.2) ...
Selecting previously unselected package lxd.
Preparing to unpack .../lxd_2.0.3-0ubuntu2~ubuntu14.04.1_amd64.deb ...
Adding system user `lxd' (UID 106) ...
Adding new user `lxd' (UID 106) with group `nogroup' ...
Creating home directory `/var/lib/lxd/' ...
Adding group `lxd' (GID 111) ...
Done.
Unpacking lxd (2.0.3-0ubuntu2~ubuntu14.04.1) ...
Selecting previously unselected package lxd-client.
Preparing to unpack .../lxd-client_2.0.3-0ubuntu2~ubuntu14.04.1_amd64.deb ...
Unpacking lxd-client (2.0.3-0ubuntu2~ubuntu14.04.1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up cgroup-lite (1.11~ubuntu14.04.2) ...
cgroup-lite start/running
Setting up libseccomp2:amd64 (2.2.3-2ubuntu1~ubuntu14.04.1) ...
Setting up liblzo2-2:amd64 (2.06-1.2ubuntu1.1) ...
Setting up acl (2.2.52-1) ...
Setting up libmnl0:amd64 (1.0.3-3ubuntu1) ...
Setting up libnetfilter-conntrack3:amd64 (1.0.4-1) ...
Setting up dnsmasq-base (2.68-1ubuntu0.1) ...
Setting up lxcfs (2.0.2-0ubuntu1~ubuntu14.04.1) ...
lxcfs stop/pre-start, process 3056
Setting up squashfs-tools (1:4.2+20130409-2ubuntu0.14.04.1) ...
Setting up uidmap (1:4.1.5.1-1ubuntu9.2) ...
Setting up lxd-client (2.0.3-0ubuntu2~ubuntu14.04.1) ...
Setting up lxc-common (2.0.3-0ubuntu1~ubuntu14.04.1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up liblxc1 (2.0.3-0ubuntu1~ubuntu14.04.1) ...
Setting up lxd (2.0.3-0ubuntu2~ubuntu14.04.1) ...
lxd start/running, process 3204

The default LXD bridge, lxdbr0, comes unconfigured by default.
Only limited HTTP connectivity through a PROXY will be available.
To go through the initial LXD configuration, run: lxd init

Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
Processing triggers for ureadahead (0.100.0-16) ...
root@trusty-cloud:~# stat /var/lib/lxd
  File: '/var/lib/lxd'
  Size: 13        	Blocks: 17         IO Block: 131072 directory
Device: 3ch/60d	Inode: 37232       Links: 9
Access: (0755/drwxr-xr-x)  Uid: (  106/     lxd)   Gid: (65534/ nogroup)
Access: 2016-07-10 20:38:47.282228660 +0000
Modify: 2016-07-10 20:38:56.198223911 +0000
Change: 2016-07-10 20:38:56.198223911 +0000
 Birth: -
```

**Comment by stgraber** [comment]
So I have no idea what changed yours to be 700 instead...

**Comment by Schachte** [comment]
@stgraber Strange... Should I `chmod 0711 /var/lib/lxd`

**Comment by stgraber** [comment]
Yeah, it should be 0755 (default) or at least 0711.

**Comment by Schachte** [comment]
@stgraber oh hey, that fixed the errors on this system running **3.13.0-86-generic**... Thanks. 3.16 must really not like something..

**Comment by stgraber** [comment]
Yeah, the 3.16 kernel hasn't been such a success in the past, it ran into quite a few bugs with symptoms very similar to what you reported and it's only minimally maintained right now due to the source Ubuntu release, Ubuntu 14.10 being long past its end of life. So on Ubuntu 14.04, I'd strongly recommend you use the original 3.13 kernel or the backported 4.4 kernel, both of which are known to work with LXD, though the 4.4 kernel will get you a bit more speed and some more features too.

**Comment by Schachte** [comment]
Great. Thanks a lot for the help today. Looks like we can probably close this issue out since it seems to be a kernel problem on 3.16.. I got my image running fine after changing /var/lib/lxd permissions to 0755.
