### ISSUE TITLE
Deleting an image affects the containers that were created from it

### ISSUE THREAD

**Issue by stevenmunro** [lxc/lxd#2197]
* Distribution: Ubuntu:xenial
 * Distribution version: 16.04
 * Kernel version: 4.4.0-28
 * LXC version: 2.02
 * LXD version: 2.02
 * Storage backend in use: ZFS

Launch a new container from an image, delete the image and the container now appears to be 'broken'

$ lxc launch my-image andrew
$ lxc image delete my-image
$ lxc restart andrew

error: Error calling 'lxd forkstart andrew /var/lib/lxd/containers /var/log/lxd/andrew/lxc.conf': err='exit status 1'

Issue appears resolved when ZFS is remounted.

$ lxc stop andrew
$ zfs mount -a
$ lxc start andrew
$ lxc exec andrew /bin/bash

I'm a new user here so, with my limited knowledge my main concern is if containers are indeed linked to their original images and therefore should not be deleted? If someone could tell me that they are actually completely separate and isolated, that would be great.

Cheers Steven

**Comment by stevenmunro** [comment]
Similar issue here.

http://askubuntu.com/questions/774097/lxd-managed-containers-on-zfs-vanish-after-deleting-a-different-one

**Comment by stgraber** [comment]
```
stgraber@castiana:~/data/code/lxc/lxd (lxc/master)$ lxc launch my-image andrew
Creating andrew
Starting andrew
stgraber@castiana:~/data/code/lxc/lxd (lxc/master)$ lxc image delete my-image
stgraber@castiana:~/data/code/lxc/lxd (lxc/master)$ lxc restart andrew
stgraber@castiana:~/data/code/lxc/lxd (lxc/master)$ lxc stop andrew
```

That's on LXD 2.0.4. In 2.0.3 we did add logic to mount the zfs volume if it's unmounted for whatever reason, so that probably fixed this issue.

I'm going to close it based on that and my testing. If you still run into it on 2.0.4, then we'll have to get a more reliable reproducer to look into this.
