### ISSUE TITLE
lxc exec consumes stdin when it  should not

### ISSUE THREAD

**Issue by smoser** [lxc/lxd#2200]
# Issue description
'lxc exec' consumes stdin meaning pasting multiple lines is impossible

# Steps to reproduce

 1. start new container

      lxc launch ubuntu-daily:xenial x1

 2. paste the following something into your terminal
      
      lxc exec --mode=non-interactive x1 /bin/true
      now=$(date -R)
      echo $now
      
 3. expected output is that 'date' would get run on the terminal, and you'd see output like

      Tue, 12 Jul 2016 14:50:37 +0000
     Actual output is that 'date' never gets run as lxc exec swallowed the standard input so it wasn't left for the console.

Note that the above can be 'fixed' by redirecting stdinput to 'lxc exec' </dev/null.  Ie this works:

      lxc exec --mode=non-interactive x1 /bin/true </dev/null
      now=$(date -R)
      echo $now
   
# Required information

 * Distribution: ubuntu
 * Distribution version: xenial
 
```
$ lxc info
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - ppc64le
  certificate: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  certificatefingerprint: 61a161e266c7813050163613d44d2b0b85de62cc52eb4ff8a054008915f715fb
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: ppc64le
  kernelversion: 4.4.0-24-generic
  server: lxd
  serverpid: 31200
  serverversion: 2.0.3
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd-pool
public: false
```

**Comment by tych0** [comment]
This is probably because we're explicitly closing stdin at the end of the exec execution, and when you give it its own stdin, it closes that one instead.

This code is sort of gnarly (right now I think we rely on closing stdin to signal to the websockets that they'll need to close). I tried a cheap hack, but it didn't work:

```
~/packages/go/src/github.com/lxc/lxd master git diff
diff --git a/lxc/exec.go b/lxc/exec.go
index 87427ed..3fd25d5 100644
--- a/lxc/exec.go
+++ b/lxc/exec.go
@@ -145,8 +145,19 @@ func (c *execCmd) run(config *lxd.Config, args []string) error {
                }
        }
 
-       stdout := c.getStdout()
-       ret, err := d.Exec(name, args[1:], env, os.Stdin, stdout, os.Stderr, handler, width, height)
+       stdout, err := c.getStdout()
+       if err != nil {
+               return err
+       }
+       stdin, err := shared.DupFile(os.Stdin)
+       if err != nil {
+               return err
+       }
+       stderr, err := shared.DupFile(os.Stderr)
+       if err != nil {
+               return err
+       }
+       ret, err := d.Exec(name, args[1:], env, stdin, stdout, stderr, handler, width, height)
        if err != nil {
                return err
        }
diff --git a/lxc/exec_unix.go b/lxc/exec_unix.go
index 9b46add..f4f2948 100644
--- a/lxc/exec_unix.go
+++ b/lxc/exec_unix.go
@@ -14,8 +14,8 @@ import (
        "github.com/lxc/lxd/shared"
 )
 
-func (c *execCmd) getStdout() io.WriteCloser {
-       return os.Stdout
+func (c *execCmd) getStdout() (io.WriteCloser, error) {
+       return shared.DupFile(os.Stdout)
 }
 
 func (c *execCmd) controlSocketHandler(d *lxd.Client, control *websocket.Conn) {
diff --git a/lxc/exec_windows.go b/lxc/exec_windows.go
index 5b51c78..3c056fc 100644
--- a/lxc/exec_windows.go
+++ b/lxc/exec_windows.go
@@ -24,8 +24,8 @@ func (wwc *WrappedWriteCloser) Write(p []byte) (int, error) {
        return wwc.wrapper.Write(p)
 }
 
-func (c *execCmd) getStdout() io.WriteCloser {
-       return &WrappedWriteCloser{os.Stdout, colorable.NewColorableStdout()}
+func (c *execCmd) getStdout() (io.WriteCloser, error) {
+       return &WrappedWriteCloser{os.Stdout, colorable.NewColorableStdout()}, nil
 }
 
 func (c *execCmd) controlSocketHandler(d *lxd.Client, control *websocket.Conn) {
diff --git a/shared/util_linux.go b/shared/util_linux.go
index d9e7bc1..6c08948 100644
--- a/shared/util_linux.go
+++ b/shared/util_linux.go
@@ -384,3 +384,12 @@ func SetSize(fd int, width int, height int) (err error) {
        }
        return nil
 }
+
+func DupFile(f *os.File) (*os.File, error) {
+       fd, err := syscall.Dup(int(f.Fd()))
+       if err != nil {
+               return nil, err
+       }
+
+       return os.NewFile(uintptr(fd), f.Name()), nil
+}
```

**Comment by tych0** [comment]
I think we'll probably have to introduce another thing over the control channel which indicates whether or not the command actually closed its stdin, and then propagate that back to the client.

**Comment by tych0** [comment]
So I tried not explicitly closing stdin with: https://github.com/tych0/lxd/commit/334f19998bae8cd6824fd26f3d2e0d457fecc366 but it still didn't work :(

**Comment by brauner** [comment]
So it seems that `ssh` is affected by this issue as well. So if you try:

    seq 1 10 | while read line; do ssh remotehostname "echo x${line}x"; done

you will only see

    x1x

as output. For the rest `ssh` prevents any read from `stdin` because it has allocated the `fd`. The same problem is faced by `lxc exec`:

    seq 1 10 | while read line; do lxc exec c3 echo x${line}x; done

with output

     x1x

Or specifically with the commands you provided:

    ssh -n serv /bin/true now=$(date -R) echo $now
    lxc exec --mode=non-interactive c3 /bin/true now=$(date -R) echo $now

will give you no output. I'm not sure whether there is an easy fix for this or if we should just shrug our shoulders and say "we do what ssh does" which is usually what users expect.

**Comment by smoser** [comment]
I hadn't realized that ssh does in fact have the behavior also.  Your commands above don't show that clearly (possibly just editing/formatting), but essentially pasting this blob:

    ssh localhost /bin/true
    now=$(date -R)
    echo $now

has the same behavior as

    lxc exec --mode=non-interactive c3 /bin/true
    now=$(date -R)
    echo $now

So I think I agree on shrugging shoulders.  Its actually better to have the same behavior to ssh than different behavior.

**Comment by haarts** [comment]
I'm actually having this problem. And while `ssh` might do the same thing this is still that, a problem.
Perhaps you could suggest a workaround?
