### ISSUE TITLE
deleted images never freed in the zfs pool backend

### ISSUE THREAD

**Issue by SFRgithub** [lxc/lxd#2207]
* Distribution: ubuntu desktop
 * Distribution version:16.04
 * The output of "lxc info" or if that fails:

lxc info:
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
  certificatefingerprint: 89548f89d96ff25cc088ed740f4ec49b631f37cfe3c7e7efac6246bcd4572fd5
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-30-generic
  server: lxd
  serverpid: 5865
  serverversion: 2.0.3
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd-zfs-1
public: false

zfs backend uses a file :/var/lib/lxd/zfs.img (10 GO)
 

Description:

I have created lot  of containers and deleted them, created images and deleted them  too. But i finally had to add another file image in the zfs pool since the last created container hadn't enough space to install softwares, which  is estonishing since i was using less thant 7 GO.

 Looking at the zpool space, it looks like deleted images are never really deleted:
lxd-zfs-1/deleted                                                                          2,92G  9,68G    19K  none
lxd-zfs-1/deleted/images                                                                   2,92G  9,68G    19K  none
lxd-zfs-1/deleted/images/28693a1cb78b28e1f5854f72070bf2b1251822348c30bbb042cb6d4fa6a94b4b   416M  9,68G   416M  none
lxd-zfs-1/deleted/images/3e773d734beac9e1ae54b635fab78ab0634ee513ce61abc5cdd4ae8d8165fc2b   455M  9,68G   455M  none
lxd-zfs-1/deleted/images/979b03fb4a8ca384801c9836fed0ae56c045faf3ed7e3d840104bdd099c65e27   373M  9,68G   373M  none
lxd-zfs-1/deleted/images/c9d0dfc89fe2ddc3ead832c71d5acf813f3f7b04e49a55bb92f9810aeb893175   455M  9,68G   455M  none
lxd-zfs-1/deleted/images/f452cda3bccb2903e56d53e402b9d35334b4276783d098a879be5d74b04e62e2   647M  9,68G   647M  none
lxd-zfs-1/deleted/images/fa117e8fba4533655e47d5429e3150f68fd0b03f3d6020d67dad857e7513e35e   641M  9,68G   641M  none

# Steps to reproduce

 1. create images
 2. delete them 
 3. look at zfs pool:  sudo zfs list

Is this a bug ?

Regards.
Gaetan.

**Comment by stgraber** [comment]
Is the above a complete "zfs list" listing or did you filter non-images from it?

If you have a bunch of containers, the above output may be perfectly normal. If you don't, then there may be a bug somewhere.

**Comment by SFRgithub** [comment]
it is a filtered output ( grep deleted) , showing that 2,92 go are still in use in the "deleted" "space". but how could it be normal?

**Comment by stgraber** [comment]
With zfs, the source of a filesystem can't be removed. Which means that LXD can't remove an image from ZFS until the last container using it and any of its decendant had been removed. 

LXD renames the image or container filesystem to deleted/...  and then clears it as soon as it no longer has anything depending on it.

**Comment by SFRgithub** [comment]
ok it is clear. so if i delete all containers the deleted space is free. Thank you for the explanation.

**Comment by stgraber** [comment]
Right. If you delete all the containers and you still have things under deleted/ then we have a problem somewhere in LXD. If you don't, then it's the expected behavior with ZFS, albeit a bit of an annoying one (it's a ZFS limitation, not a LXD one. btrfs for example doesn't have that problem).

**Comment by cryptofuture** [comment]
>  and then clears it as soon as it no longer has anything depending on it. 
Thats a bit confusing, I didn't use containers, I run lxc delete on them and containers still remain in lxd/deleted. How to insure that container will be cleared, or to force it to be cleared?

**Comment by stgraber** [comment]
@cryptofuture and you never copied that container or one of its snapshots into another container?

**Comment by cryptofuture** [comment]
> and you never copied that container or one of its snapshots into another container?

To be clear:  (fake container names here, but order is the same)
I have container5, its a production container
I run `lxc copy  container5 container6`
I tested some new services and practices in container6, was not happy enough with results compared with  production container.
Then I stopped `lxc stop container6`container6 and `lxc delete container6`deleted it.

**Comment by cryptofuture** [comment]
After comparing all containers size with same containers 3 days backups. I figured out size of lxd pool (including lxd/deleted) is the same + data I collected in this last days. Real container size is under `REFER` in `zfs list`and not under `USED.` Looks like lxd/deleted was linked with some containers at some older point, then. And all indeed correct.
I was able to free some extra space with removing lxc image (800Mb free now total). But things not so good, and my pool will be full in like 2-3 days. I found [issue](https://github.com/lxc/lxd/issues/2269) describing pool migration. Is very unfortunate lxd doesn't support multiple pools at this point. Don't like idea switching  from special blocked device I planned from beginning for lxd to zfs loopback. Not sure if I'll be able to make zraid from block device and sparse file with loopback driver.

**Comment by stgraber** [comment]
So long as your sparse loop file is bigger than the existing block device, setting it as a mirror and then degrading it back to a single drive should work fine.

**Comment by rptb1** [comment]
This is a note for anyone else who finds this issue and wants to check whether the `deleted` filesystems are referenced.  You can check by looking at the `origin` property.  For example:
`zfs list -r -o name,origin zp0/lxd/containers`
shows which containers are retaining which “deleted” images for me.

**Comment by stgraber** [comment]
Also worth noting that the same applies to containers themselves when they're copied, so you can have a chain which keeps a whole bunch of containers and the first container's image all alive due to origin.
