### ISSUE TITLE
alpine/3.4/amd64 lxd image has wrong version (3.3) in /etc/os-release

### ISSUE THREAD

**Issue by melato** [lxc/lxd#2209]
To reproduce, with a recent Ubuntu 16.04:
lxc launch images:alpine/3.4/amd64 alpine34
lxc exec alpine34 cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.3.0
PRETTY_NAME="Alpine Linux v3.3"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"

Using lxc image list images:
I find this information about the image:
ALIAS: alpine/3.4/amd64
FINGERPRINT: 88c9d0565328
PUBLIC: yes
DESCRIPTION: Alpine 3.4 (amd64) (20160716_17:50)
ARCH: x86_64
SIZE: 2.63MB
UPLOAD DATE: Jul 16 2016 at 6:00pm (UTC)

I suspect it's a problem with the image generation scripts.
I first entered it here:  http://bugs.alpinelinux.org/issues/5908

**Comment by stgraber** [comment]
https://jenkins.linuxcontainers.org/view/LXC/view/LXC%20Templates/job/lxc-template-alpine/arch=amd64,release=3.4,restrict=lxc-priv,variant=default/190/console shows that we do pass the 3.4 version string to lxc-alpine and it does seem to be downloading a bunch of 3.4 things.

**Comment by stgraber** [comment]
I guess whatever was broken got fixed:
```
stgraber@castiana:~$ lxc launch images:alpine/3.4/amd64 alpine34
Creating alpine34
Retrieving image: 100%
Starting alpine34
stgraber@castiana:~$ lxc exec alpine34 cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.1
PRETTY_NAME="Alpine Linux v3.4"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
stgraber@castiana:~$ 
```

**Comment by melato** [comment]
Indeed, it was fixed in the new template from 20160717_17:50.
