### ISSUE TITLE
Implement container listing using proper API endpoint (/1.0/containers instead of /list)

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#221]
Per title, LXD currently implements container listing using a non-standard "/list" API endpoint when the spec says that this should be "GET /1.0/containers" instead.

LXD and the client should be updated to match the spec.

**Comment by tych0** [comment]
On Mon, Feb 23, 2015 at 08:40:07AM -0800, St�phane Graber wrote:

I'm happy to do this once we get hallyn's branch merged.

**Comment by hallyn** [comment]
On Mon, Feb 23, 2015 at 08:42:41AM -0800, Tycho Andersen wrote:
> On Mon, Feb 23, 2015 at 08:40:07AM -0800, St�phane Graber wrote:
> 
> I'm happy to do this once we get hallyn's branch merged.

Thanks, Tycho.  Also remember we want to return endpoint urls, not
container names :)  (That part is trivial)
