### ISSUE TITLE
lxc copy doesn't change hostname 

### ISSUE THREAD

**Issue by richiela** [lxc/lxd#2212]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-31-generic
  server: lxd
  serverpid: 27876
  serverversion: 2.0.3
  storage: dir
  storageversion: ""
config: {}
public: false

# Issue description
This is exactly as https://github.com/lxc/lxd/issues/2103.  I've copied a container to new one, started the new container, but hostname is still not updated.

# Steps to reproduce

userx@memoir:~$ lxc list
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| base | STOPPED |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+
userx@memoir:~$ lxc copy base brkcoin
userx@memoir:~$ lxc start brkcoin
userx@memoir:~$ lxc exec brkcoin cat /etc/hostname
base

**Comment by stgraber** [comment]
The hostname does change but you have to give it a while as it's cloud-init that's doing that change for the official Ubuntu images during container boot.

**Comment by laerus** [comment]
Hello, this happens on lxc 3.0 as well, i've created a container with the 'download' template and when i `lxc-copy` it the hostname of the new container doesn't change.
