### ISSUE TITLE
lxc image list ubuntu: reports incorrect size for xenial images

### ISSUE THREAD

**Issue by jrwren** [lxc/lxd#2223]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
apicompat: 0
auth: trusted
environment:
  addresses:
  - 107.5.212.189:8443
  - 192.168.15.101:8443
  - '[2601:400:8000:5ab3:21f:d0ff:fe85:d98b]:8443'
  - 10.0.3.1:8443
  - 192.168.122.1:8443
  - 172.17.0.1:8443
  - 10.0.5.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIF2TCCA8GgAwIBAgIQbyqPLPohfuhM05PhCGJSCDANBgkqhkiG9w0BAQsFADA0
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QGRl
    bGF5czAeFw0xNjAzMjQyMzEzMDFaFw0yNjAzMjIyMzEzMDFaMDQxHDAaBgNVBAoT
    E2xpbnV4Y29udGFpbmVycy5vcmcxFDASBgNVBAMMC3Jvb3RAZGVsYXlzMIICIjAN
    BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA2jYPOFz/9VeKW1kBhZA3KFnidrV6
    mYyLE6vcMm8Z7A/eUICQwg3qucRvj845ymBeweBv6v8pK+Dy0fJqGFItearkQHky
    H3/b+cLPssLg6J4ChYpPU3f9NoIivP5YPeIviLIuP6CckKY36/DbrzQr5yooGhet
    Irgzdx5rpKJjtLijPP36o26AEl6E/g6YhX8MyD+AqgLqn699RnSBaRZ9E/RljkdG
    iAcBXfF6VV9qdCEQxdNeqpqf6CrqwMBDQX3wKPMFDM4dmKd8qrLFEmxZHnGUUeUH
    rnnsM4wl2+mmsAsincH1CE4Zbvh3wEKuCMnkFgYRlv58NXoiQmUrGpJiXG+o3xe1
    v0kP8HrNGtUT+buKWNyU2EQ3d5j1WBz7ivQG9DUk+WdeYwSUhdOeQPcj+vkiOHu2
    C5IDqguEBTu1yOLp0s2jDSO6NzDceN1Ve1HzldILEHKdjzxN2fFOl8uQVcLllrad
    +Cyjaiea6/n2zBZV/Fv9aC+9ecOE/l526ID4qtZjg7y7GyhCBzTXUEg+Dc47NW3H
    OcaSgS4gv5/eXCGWjSsMzZihapgVJQA5fIN1WfcPOTSnwYgttQcVyeQWvPgfPJ97
    kMbMw3wNnaAYgq1F5Nz2szdXVn86tojQ7ImASmmG70txT6IiSEtBu/rxon8T/TGy
    P/sTaASXyHzAg88CAwEAAaOB5jCB4zAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAww
    CgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADCBrQYDVR0RBIGlMIGiggZkZWxheXOC
    DjY4LjQwLjU5LjkzLzIxghtmZTgwOjoyYTA6YzlmZjpmZWEwOmMyZmEvNjSCETE5
    Mi4xNjguMTUuMTAxLzI0ghtmZTgwOjoyMGE6Y2RmZjpmZTIxOjNkMDIvNjSCCzEw
    LjAuMy4xLzI0ghxmZTgwOjo3MDY3OjhlZmY6ZmVkNToxOGViLzY0ghAxOTIuMTY4
    LjEyMi4xLzI0MA0GCSqGSIb3DQEBCwUAA4ICAQDHv1tqcrrnQfj/eIXuWN1c1RTM
    ltYif0YOTWdYirWUZSA/5p7YL/5bm8lwPrBS1G5SGBqa6cF8cr0fsRUBLLgZYtf2
    2W2jciY32ZCrBQdu027fhJ0E7j2qKxTitUji0tVwaeBKHpv+V64LnxuW9ncK8pV9
    p9Te5tB9VgVyZreeBZUdmu1EQn7Rz56BSIiOMjg9LAubGPfL33Ddboy/bGbl0ILG
    WudbasghJrcU2gSHOHgJL5IhNoMaWlO1nfdNUftpnOJ5Q8MAmM8qyyP5G70tJc+7
    aUMbW/687JcBj7wfJoMrsiE2Y21UgrsAd3rTVmaEyk7w3OlW62MI6WhjkH7KZksA
    R9ANigEhRRN/9I/Mp19S8T6q0KoGIMF0tER6k81JvtR9ErDXs1CCyJURLvcKpEGu
    QHwFlotyobN/7uc0QVQBn6ZLYskkNzEAZpIqjOLBN4hQ03uWI7cigZn6kYr1QK8n
    cHcLH4QnfVeRJE+G8qHVAa6DJ80bidZKpx0MkBopYioj97IJFryjbZ+fMQEsKAj8
    Yk0LPDtO7Xsyltgz4r0jHTwEcV+lP9uBvWuW60gTfoJNOTJ2sfRw8FdBUuD1iRj9
    I/nRSyaWoEi9EQJpBHE9X0mMuBD3wzWxYLCMF9OZfP1cza2U7Nj8uyC4vFCXm90n
    3GQm47mwFp/JiiLHSQ==
    -----END CERTIFICATE-----
  certificatefingerprint: 479760b89d2bddce769bf051b5000bfeb1890ab3c3516384619a152b36862c2c
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-24-generic
  server: lxd
  serverpid: 24855
  serverversion: 2.0.3
  storage: zfs
  storageversion: "5"
config:
  core.https_address: '[::]'
  storage.zfs_pool_name: lxd
public: false

# Issue description

lxc image list ubuntu: reports incorrect size for xenial images

# Steps to reproduce

 1. lxc image list ubuntu:
 2. Notice how the size column is approximately double what it should be for the xeniall images
 3. Wonder why.

I investigated further and found the reason is that xenial adds squashfs images in addition to the root.tar.xz images. The ToLXD() function in shared/simplestreams.go sums the size of all matching images (L123) even though it only appends a single record for images found from the version.Items (L189,L190)

**Comment by stgraber** [comment]
Oh, good catch. And yeah, the problem is for any image which exists in both squashfs and tar.xz format.
