### ISSUE TITLE
Container can't access internet

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2226]
* Distribution: Ubuntu Studio
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-31-generic
   * LXC version: 2.0.3
   * LXD version: 2.0.3
   * Storage backend in use: dir

# Issue description

Can't ping google.com, 8.8.8.8, etc.

# Steps to reproduce
```
$ lxc launch ubuntu:16.04 u2
$ lxc exec u2 ping google.com
ping: unknown host google.com
$ lxc exec u2 ping 8.8.8.8
connect: Network is unreachable
```

# Information to attach

 - [x] any relevant kernel output (dmesg)
```
$ lxc exec u2 dmesg
...
[ 8381.207701] audit: type=1400 audit(1469179488.925:129): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-u2_</var/lib/lxd>" pid=7297 comm="apparmor_pars
er"
[ 8381.350318] device vethCAK2IE entered promiscuous mode
[ 8381.350528] IPv6: ADDRCONF(NETDEV_UP): vethCAK2IE: link is not ready
[ 8381.482244] eth0: renamed from veth0M0OTR
[ 8381.506822] IPv6: ADDRCONF(NETDEV_CHANGE): vethCAK2IE: link becomes ready
[ 8381.506923] lxdbr0: port 3(vethCAK2IE) entered forwarding state
[ 8381.506952] lxdbr0: port 3(vethCAK2IE) entered forwarding state
[ 8396.512033] lxdbr0: port 3(vethCAK2IE) entered forwarding state
...
```
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
Assuming you never ran "lxd init" and so never configured the LXD bridge with a valid subnet, it's the expected behavior.

**Comment by stgraber** [comment]
Installing packages should work through the use of a minimal proxy that LXD runs for you on an IPv6 link local address, but that's the extent of what can be done until you have configured it with some subnets.

**Comment by techtonik** [comment]
@stgraber it worked previously. Shouldn't `lxd init` be run on LXD install/update automatically? If the behavior have changed, then maybe README.md should be updated?

**Comment by stgraber** [comment]
Bridge configuration is done through distribution packaging so it doesn't make sense to have it in README.md given that the code on github doesn't trigger the network configuration step, only the Ubuntu packaged version does.

In the past, lxd used to use the lxcbr0 bridge from LXC which did come pre-configured (and was causing problems which is why lxdbr0 doesn't).

**Comment by stgraber** [comment]
When I say in the past, that was before LXD 2.0 was released, we wouldn't change such things in a stable release.
