### ISSUE TITLE
Process devices in alphabetical order when generating lxc.conf

### ISSUE THREAD

**Issue by ZeOrion** [lxc/lxd#2233]
Hello,

We are currently working with LXC 1.x tools and we want to use LXD to manage our containers. But after a few tests, it seems some features have been willingly removed. I open this new issue to see if it's still possible to change a few things and use LXD in production. :)

We use a custom (debootstrap-based) container template (converted to image a few days ago).

Our rootfs is minimal (even debootstrap was too "bloated" for us), our goal was to:
 - Start only *mandatory* services
 - Remove as much capabilities as we can (bye bye sys_admin, net_admin and so on)

Our network configuration:

    +--------+------------------------------+
             |           External bridge
             |
     +----------------+
     |       +        |
     | veth0: X.X.X.X |
     |                |
     |     LXC-01     |
     |                |
     | veth1: Y.Y.Y.Y |
     |       +        |
     +----------------+
             |
             |           Internal bridge
    +---------------------------------------+

So here is our problem... We can't set two static IP addresses properly in our containers. This is what happens:
 - If we use the recommended/default method (DHCP), it violates our policy (run only mandatory services)
 - If we configure interfaces inside our container, this won't work because net_admin is dropped. To be honest, DHCP will also fail for the very same reason.
 - If we configure raw.lxc, well... Sometimes our internal veth obtains the external IP address (as explained by Stéphane in one of his commits). Sadly, this is not reliable.

I understand we want to run a custom (and maybe very specific or unusual) distribution. I also understand a "classic" distribution might throw away "pre-init" network configuration (or just go nuts) but our distribution will not do such things.

This worked very well for years with the old LXC versions. **Is it possible to allow setting ipv4/6 and gateway through LXD? I don't really mind if you mark this as a "touch this only if you know what you are doing"-feature.** The auto-generated configuration file will then have `lxc.network.ipv4` not at the end of file (where raw.lxc belongs) but right after each veth declaration.

I guess [this is the right file](https://github.com/lxc/lxd/blob/3ce6bd71afd41f3fb66cc3a48b0662473542fced/lxd/container_lxc.go#L802) for such a patch. I really hope not to have to maintain a fork just for this, I think this could be useful for other sysadmins.

Thanks a lot for your time!

Regards

**Comment by stgraber** [comment]
So when you say you tried with raw.lxc, you had something like:
```
    lxc.network.0.ipv4 = 10.0.1.2/24
    lxc.network.0.ipv4.gateway = 10.0.1.1
    lxc.network.1.ipv4 = 10.0.2.2/24
```

And two network devices directly defined against the container?

If so and you still had random results, then maybe we can make things a bit better by having LXD always read the network interfaces in alphabetical order when compiling the lxc configuration file.

**Comment by ZeOrion** [comment]
Yup, exactly like this for the raw.lxc part. It will be good enough if LXD reads interfaces in alphabetical order.

Here are the different configurations I tried for my container (if the first one can work with alphabetical order definition, then it's really perfect!):
 - Two profiles assigned to container with one interface defined in each (named int in first profile and ext in second).
 - One profile with two interfaces (named int/ext)
 - One profile with two interfaces (named eth0/eth1)

Thank you!
