### ISSUE TITLE
Error while building lxd from source

### ISSUE THREAD

**Issue by DilipRenkila** [lxc/lxd#2235]
$ sudo -E $GOPATH/bin/lxd --group sudo 
errror: exec : "unsquashfs": executable file not found in $PATH.

**Comment by pcdummy** [comment]
LXD depends on squashfs-tools:

    Package: lxd
    Priority: optional
    Section: admin
    Installed-Size: 18057
    Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
    Architecture: amd64
    Version: 2.0.3-0ubuntu1~ubuntu16.04.2
    Depends: acl, adduser, dnsmasq-base, iptables, liblxc1 (>= 1.1.0~), lxcfs, netcat-openbsd, rsync, squashfs-tools, uidmap, xz-utils, debconf (>= 0.5) | debconf-2.0, init-system-helpers (>= 1.18~), lsb-base (>= 4.1+Debian11ubuntu7), libc6 (>= 2.14), libsqlite3-0 (>= 3.7.15)
    Pre-Depends: debconf
    Recommends: lxd-client
    Suggests: criu, lxd-tools
    Filename: pool/main/l/lxd/lxd_2.0.3-0ubuntu1~ubuntu16.04.2_amd64.deb
    Size: 3663800
    MD5sum: b5be73e94fa4bc4fd12491bda4906398
    SHA1: 8a0391e3c5d5a2c474cd1adc8fa8673c6e6f4ac5
    SHA256: 970e3cbd7280a48dfdee1dcf099784290812104098d8c8d2057b72449b06eab1
    Description-en: Container hypervisor based on LXC - daemon
     LXD offers a REST API to remotely manage containers over the network,
     using an image based workflow and with support for live migration.
     .
     This package contains the LXD daemon.

This should be documented in the README ofc.

**Comment by stgraber** [comment]
Yep, feel free to send a branch to add it to README or I'll do it tomorrow
