### ISSUE TITLE
Allow FQDN as container name?

### ISSUE THREAD

**Issue by candlerb** [lxc/lxd#2236]
* Distribution: ubuntu
* Distribution version: 16.04.1

~~~
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: <<snip>>
  certificatefingerprint: <<snip>>
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-31-generic
  server: lxd
  serverpid: 2699
  serverversion: 2.0.3
  storage: dir
  storageversion: ""
config: {}
public: false
~~~

# Issue description

It appears that lxd does not allow container names which are FQDNs.

However it is very desirable to be able to name containers this way, given that an FQDN may already have been allocated - and if it has, it will be globally unique.

FAILS:

~~~
$ lxc launch ubuntu:16.04 netbox.int.example.net
Creating netbox.int.example.net
Retrieving image: 100%
error: Container name isn't a valid hostname.
~~~

Succeeds:

~~~
$ lxc launch ubuntu:16.04 netbox
Creating netbox
Starting netbox
~~~

**Comment by stgraber** [comment]
It's something that folks report every so often but we have no intention of changing. 

The current name restriction is the combination of hostname and DNS record name restrictions on all operating systems that support containers and which we may one day support. 

You can always set the FQDN as a user property to keep track of it. 

    lxc config set NAME user.fqdn FQDN

It will then be visible in "lxc config show"  but more importantly can be used with "lxc list". 

    lxc list user.fqdn=FQDN

or with current git version 

    lxc list -c n4s,user.fqdn:FQDN

**Comment by candlerb** [comment]
> we have no intention of changing

Of course that's your prerogative :-)

But I don't understand your logic. A container is just a subdirectory. I can call a subdirectory "foo_bar", and even though technically that might not be a valid hostname[^1], it's still fine as a container name.

In other words: the space of valid container names is distinct from the space of valid hostnames and valid DNS names, and the rules for the former do not need to comply with the rules for the latter two.

If any future OS applies restrictions on valid container names, then those restrictions can't be predicted today. You are saying that maybe they will reject container names which are not valid hostnames? Sure. But they might also reject container names which contain a hyphen, or which are longer than 8 characters.

You can simply reject such names as invalid at the time of container creation on that OS. Is it important that a container name which is valid on one OS be also valid on every other OS in existence?

[^1]: According to archaic RFC 1123

**Comment by stgraber** [comment]
The container name is used for the kernel uts name, cgroup name, filesystem lv/filesystem name,... 

All of which have their own set of restrictions. 

Our current rules make things work consistently everywhere and allow copying containers between systems without having to think about what kind of restriction may apply. 

As such we have no intention to change behavior.

**Comment by tardich** [comment]
I can understand why you restrict the container name but then, as I have the ability to set the FQDN of a container in a user property, I'd like to be able to show it (the user property) with the lxc list command (or maybe it's already available in latest lxd version. Mine is currently set to 2.0.4

**Comment by tych0** [comment]
On Wed, Oct 05, 2016 at 04:33:40PM -0700, tardich wrote:
> I can understand why you restrict the container name but then, as I have the ability to set the FQDN of a container in a user property, I'd like to be able to show it (the user property) with the lxc list command (or maybe it's already available in latest lxd version. Mine is currently set to 2.0.4

from the output of `lxc help list`:

lxc list -c n,volatile.base_image:"BASE IMAGE":0,s46,volatile.eth0.hwaddr:MAC

so,

lxc list -c n,user.fqdn

**Comment by tardich** [comment]
Not from what I can read. Specifically, lxc help list shows:

Lists the available resources.

lxc list [resource] [filters] [--format table|json] [-c columns] [--fast]

The filters are:
* A single keyword like "web" which will list any container with a name starting by "web".
* A regular expression on the container name. (e.g. .*web.*01$)
* A key/value pair referring to a configuration item. For those, the namespace can be abreviated to the smallest unambiguous identifier:
 * "user.blah=abc" will list all containers with the "blah" user property set to "abc".
 * "u.blah=abc" will do the same
 * "security.privileged=1" will list all privileged containers
 * "s.privileged=1" will do the same
* A regular expression matching a configuration item or its value. (e.g. volatile.eth0.hwaddr=00:16:3e:.*)

Columns for table format are:
* 4 - IPv4 address
* 6 - IPv6 address
* a - architecture
* c - creation date
* n - name
* p - pid of container init process
* P - profiles
* s - state
* S - number of snapshots
* t - type (persistent or ephemeral)

Default column layout: ns46tS
Fast column layout: nsacPt

You can see that columns do not allow anything else than: 4, 6, a, c, n, p, P, s, S, and t

The regular expression matching a config item (for example: volatile.eth0.hwaddr=00:16:3e:.*) allows to filter the output. That's, from what I can see and test, a search filter, not a new field to show. And I'd really like to be able to show those fields with lxc list, not just search them.

**Comment by stgraber** [comment]
It was introduced after LXD 2.0, looks like you're running 2.0.x

**Comment by tardich** [comment]
Yes, running 2.0.4. 

Just got 2.4 from ppa: http://www.ubuntuupdates.org/ppa/lxd

Now getting the user FQDN. Tks for the tip, and keep the good work !

**Comment by tardich** [comment]
One last question. Can I change the default column layout so, by default, it includes user.fqdn ?

**Comment by stgraber** [comment]
The LXC client supports aliases (though we don't have a command to set them up).

You can edit ~/.config/lxc/config.yml and define an alias at the bottom like:
```
aliases:
  list: list -c n,user.fqdn:FQDN,s46tS
```

**Comment by tardich** [comment]
Awesome!  Tks

**Comment by candlerb** [comment]
For reference, there was a previous discussion of FQDNs at #1921
