### ISSUE TITLE
Unable to start containers : Failed to mount proc onto /usr/lib/x86_64-linux-gnu/lxc/proc

### ISSUE THREAD

**Issue by rchincholkar** [lxc/lxd#2238]
Hi,

We are on ubuntu 16.04 (Xen Virtual Machine) and trying LXD with zfs. There is an issue with launching / starting containers. 

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 16.04.01 LTS

 * The output of "lxc info":

> # lxc info 
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
   x86_64
   i686
  certificate: |
  certificatefingerprint: d27cc1c738395f980432643d8418c0945ebb0d89449441409fa03ad184a705c0
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-31-generic
  server: lxd
  serverpid: 4886
  serverversion: 2.0.3
  storage: zfs
  storageversion: 5
config:
  storage.zfs_pool_name: lxd
public: false

# Issue description
Container log:
`$ lxc info --show-log test-1
Name: test-1
Architecture: x86_64
Created: 2016/07/26 07:39 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20160726130909.888 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160726130909.888 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 9
            lxc 20160726130909.889 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /var/lib/lxd/containers test-1
            lxc 20160726130909.890 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 9
            lxc 20160726130909.890 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for reject_force_umount action 0
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for reject_force_umount action 0
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .[all].
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .kexec_load errno 1.
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for kexec_load action 327681
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for kexec_load action 327681
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .open_by_handle_at errno 1.
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for open_by_handle_at action 327681
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for open_by_handle_at action 327681
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .init_module errno 1.
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for init_module action 327681
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for init_module action 327681
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .finit_module errno 1.
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for finit_module action 327681
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for finit_module action 327681
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .delete_module errno 1.
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for delete_module action 327681
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for delete_module action 327681
            lxc 20160726130909.890 INFO     lxc_seccomp - seccomp.c:parse_config_v2:456 - Merging in the compat seccomp ctx into the main one
            lxc 20160726130909.890 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 3 start' for container 'test-1', config section 'lxc'
            lxc 20160726130909.890 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 3
            lxc 20160726130909.891 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 9
            lxc 20160726130909.892 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/d78a9d7e97b4b375//var/lib/lxd/containers
            lxc 20160726130909.995 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160726130909.995 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160726130910.006 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
            lxc 20160726130910.008 DEBUG    lxc_console - console.c:lxc_console_peer_default:469 - no console peer
            lxc 20160726130910.008 INFO     lxc_start - start.c:lxc_init:488 - 'test-1' is initialized
            lxc 20160726130910.009 DEBUG    lxc_start - start.c:__lxc_start:1326 - Not dropping cap_sys_boot or watching utmp
            lxc 20160726130910.009 INFO     lxc_start - start.c:resolve_clone_flags:1013 - Cloning a new user namespace
            lxc 20160726130910.009 DEBUG    lxc_conf - conf.c:instantiate_macvlan:2687 - instantiated macvlan 'mc2KHY4D', index is '6' and mode '4'
            lxc 20160726130910.009 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for test-1
            lxc 20160726130910.152 DEBUG    lxc_conf - conf.c:lxc_assign_network:3048 - move 'eth0' to '5156'
            lxc 20160726130910.152 NOTICE   lxc_start - start.c:do_start:777 - switching to gid/uid 0/0 in new user namespace
            lxc 20160726130910.152 DEBUG    lxc_conf - conf.c:setup_rootfs:1215 - mounted '/var/lib/lxd/containers/test-1/rootfs' on '/usr/lib/x86_64-linux-gnu/lxc'
            lxc 20160726130910.152 INFO     lxc_conf - conf.c:setup_utsname:843 - 'test-1' hostname has been setup
            lxc 20160726130910.247 DEBUG    lxc_conf - conf.c:setup_hw_addr:2145 - mac address '00:16:3e:1e:30:ab' on 'eth0' has been setup
            lxc 20160726130910.248 DEBUG    lxc_conf - conf.c:setup_netdev:2372 - 'eth0' has been setup
            lxc 20160726130910.248 INFO     lxc_conf - conf.c:setup_network:2393 - network has been setup
            lxc 20160726130910.248 INFO     lxc_conf - conf.c:mount_autodev:1072 - Mounting container /dev
            lxc 20160726130910.248 INFO     lxc_conf - conf.c:mount_autodev:1095 - Mounted tmpfs onto /usr/lib/x86_64-linux-gnu/lxc/dev
            lxc 20160726130910.248 INFO     lxc_conf - conf.c:mount_autodev:1113 - Mounted container /dev
            lxc 20160726130910.248 ERROR    lxc_utils - utils.c:safe_mount:1692 - Operation not permitted - Failed to mount proc onto /usr/lib/x86_64-linux-gnu/lxc/proc
            lxc 20160726130910.248 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:743 - Operation not permitted - error mounting proc on /usr/lib/x86_64-linux-gnu/lxc/proc flags 14
            lxc 20160726130910.248 ERROR    lxc_conf - conf.c:lxc_setup:3721 - failed to setup the automatic mounts for 'test-1'
            lxc 20160726130910.248 ERROR    lxc_start - start.c:do_start:833 - failed to setup the container
            lxc 20160726130910.248 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20160726130910.248 WARN     lxc_conf - conf.c:lxc_delete_network:2909 - failed to remove interface 6 'eth0'
            lxc 20160726130910.248 ERROR    lxc_start - start.c:__lxc_start:1353 - failed to spawn 'test-1'
            lxc 20160726130910.295 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'test-1', config section 'lxc'
            lxc 20160726130910.798 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 3 stop' for container 'test-1', config section 'lxc'
            lxc 20160726130910.879 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160726130910.880 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160726130910.882 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160726130910.882 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160726130919.356 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160726130919.356 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160726130919.360 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160726130919.360 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536
`

#Addition Information:
`# uname -r
4.4.0-31-generic
`

Please let me know the way to solve this issue.
Thanks,
Rahul C

**Comment by stgraber** [comment]
Can you pastebin "cat /proc/self/mountinfo" from the host?

My guess is that you have something mounted on top of /proc which the kernel thinks is hiding a directory that contains stuff, it therefore prevents lxc from mounting proc as that'd expose otherwise hidden files.

If that's the case, then mounting a pristine copy of proc somewhere on your host would fix it, say:
```
    mkdir /mnt/proc
    mount -t proc proc /mnt/proc
```

**Comment by stgraber** [comment]
But knowing exactly what the kernel thinks is hiding part of /proc would be useful just to check that it's not wrong (it has been wrong quite a few times).

**Comment by rchincholkar** [comment]
Hi

Please find the information below:

```
root@lxd-zfs:~# cat /proc/self/mountinfo
18 23 0:17 / /sys rw,nosuid,nodev,noexec,relatime shared:7 - sysfs sysfs rw
19 23 0:4 / /proc rw,nosuid,nodev,noexec,relatime shared:12 - proc proc rw
20 23 0:6 / /dev rw,nosuid,relatime shared:2 - devtmpfs udev rw,size=1000080k,nr_inodes=250020,mode=755
21 20 0:14 / /dev/pts rw,nosuid,noexec,relatime shared:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
22 23 0:18 / /run rw,nosuid,noexec,relatime shared:5 - tmpfs tmpfs rw,size=203852k,nr_inodes=254812,mode=755
23 0 202:5 / / rw,relatime shared:1 - ext4 /dev/xvda5 rw,errors=remount-ro,data=ordered
24 18 0:12 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:8 - securityfs securityfs rw
25 20 0:19 / /dev/shm rw,nosuid,nodev shared:4 - tmpfs tmpfs rw,size=1019248k,nr_inodes=254812
26 22 0:20 / /run/lock rw,nosuid,nodev,noexec,relatime shared:6 - tmpfs tmpfs rw,size=5120k,nr_inodes=254812
27 18 0:21 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:9 - tmpfs tmpfs ro,size=1019248k,nr_inodes=254812,mode=755
28 27 0:22 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:10 - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
29 18 0:23 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:11 - pstore pstore rw
30 27 0:24 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,net_cls,net_prio
31 27 0:25 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,hugetlb
32 27 0:26 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,cpu,cpuacct
33 27 0:27 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,devices
34 27 0:28 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,perf_event
35 27 0:29 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,blkio
36 27 0:30 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,freezer
37 27 0:31 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,pids
38 27 0:32 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,memory
39 27 0:33 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,cpuset
40 19 0:34 / /proc/sys/fs/binfmt_misc rw,relatime shared:23 - autofs systemd-1 rw,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct
41 18 0:7 / /sys/kernel/debug rw,relatime shared:24 - debugfs debugfs rw
42 20 0:35 / /dev/hugepages rw,relatime shared:25 - hugetlbfs hugetlbfs rw
43 20 0:16 / /dev/mqueue rw,relatime shared:26 - mqueue mqueue rw
44 18 0:36 / /sys/fs/fuse/connections rw,relatime shared:27 - fusectl fusectl rw
45 23 202:1 / /boot rw,relatime shared:28 - ext4 /dev/xvda1 rw,data=ordered
46 23 0:37 / /var/lib/lxd/containers/test-1.zfs rw,relatime shared:29 - zfs lxd/containers/test-1 rw,xattr,noacl
47 23 0:38 / /var/lib/lxd/images/628c432840e1aedc44006d3c6f7ace79d50753d2267b159289cd2e7490f2348f.zfs ro,relatime shared:30 - zfs lxd/images/628c432840e1aedc44006d3c6f7ace79d50753d2267b159289cd2e7490f2348f ro,xattr,noacl
48 22 0:39 / /run/lxcfs/controllers rw,relatime shared:31 - tmpfs tmpfs rw,size=100k,mode=700
49 48 0:33 / /run/lxcfs/controllers/cpuset rw,relatime shared:32 - cgroup cpuset rw,cpuset
50 48 0:32 / /run/lxcfs/controllers/memory rw,relatime shared:33 - cgroup memory rw,memory
51 48 0:31 / /run/lxcfs/controllers/pids rw,relatime shared:34 - cgroup pids rw,pids
52 48 0:30 / /run/lxcfs/controllers/freezer rw,relatime shared:35 - cgroup freezer rw,freezer
53 48 0:29 / /run/lxcfs/controllers/blkio rw,relatime shared:36 - cgroup blkio rw,blkio
54 48 0:28 / /run/lxcfs/controllers/perf_event rw,relatime shared:37 - cgroup perf_event rw,perf_event
55 48 0:27 / /run/lxcfs/controllers/devices rw,relatime shared:38 - cgroup devices rw,devices
56 48 0:26 / /run/lxcfs/controllers/cpu,cpuacct rw,relatime shared:39 - cgroup cpu,cpuacct rw,cpu,cpuacct
57 48 0:25 / /run/lxcfs/controllers/hugetlb rw,relatime shared:40 - cgroup hugetlb rw,hugetlb
58 48 0:24 / /run/lxcfs/controllers/net_cls,net_prio rw,relatime shared:41 - cgroup net_cls,net_prio rw,net_cls,net_prio
59 48 0:22 / /run/lxcfs/controllers/name=systemd rw,relatime shared:42 - cgroup name=systemd rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
60 23 0:40 / /var/lib/lxcfs rw,nosuid,nodev,relatime shared:43 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
61 19 0:41 / /proc/xen rw,relatime shared:44 - xenfs none rw
62 22 0:42 / /run/user/1000 rw,nosuid,nodev,relatime shared:45 - tmpfs tmpfs rw,size=203952k,mode=700,uid=1000,gid=1000
63 23 202:5 /var/lib/lxd/shmounts /var/lib/lxd/shmounts rw,relatime shared:1 - ext4 /dev/xvda5 rw,errors=remount-ro,data=ordered
```


I have overcome this issue with creating the directory (/usr/lib/x86_64-linux-gnu/lxc/proc) and binding /proc to it (used following command):
`mount --bind /proc /usr/lib/x86_64-linux-gnu/lxc/proc
`
I am not sure, if this is the permanent solution. I need to update fstab for this /proc binding explicitly. 
Please tell me if there is any other solution on this.

Regards,
Rahul C

**Comment by rchincholkar** [comment]
@stgraber 
Yes, you are right, I can see /proc/xen in /proc/self/mountinfo
That is because of xe-guest-utilities which is installed.

I have removed `xe-guest-utilities` (XenServer Tools and Drivers for supported guest operating systems) and able to start containers on the host.

/proc/self/mountinfo after removing xe-guest-utilities:

```
root@lxd-zfs:~# cat /proc/self/mountinfo 
18 23 0:17 / /sys rw,nosuid,nodev,noexec,relatime shared:7 - sysfs sysfs rw
19 23 0:4 / /proc rw,nosuid,nodev,noexec,relatime shared:12 - proc proc rw
20 23 0:6 / /dev rw,nosuid,relatime shared:2 - devtmpfs udev rw,size=1000080k,nr_inodes=250020,mode=755
21 20 0:14 / /dev/pts rw,nosuid,noexec,relatime shared:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
22 23 0:18 / /run rw,nosuid,noexec,relatime shared:5 - tmpfs tmpfs rw,size=203852k,nr_inodes=254812,mode=755
23 0 202:5 / / rw,relatime shared:1 - ext4 /dev/xvda5 rw,errors=remount-ro,data=ordered
24 18 0:12 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:8 - securityfs securityfs rw
25 20 0:19 / /dev/shm rw,nosuid,nodev shared:4 - tmpfs tmpfs rw,size=1019248k,nr_inodes=254812
26 22 0:20 / /run/lock rw,nosuid,nodev,noexec,relatime shared:6 - tmpfs tmpfs rw,size=5120k,nr_inodes=254812
27 18 0:21 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:9 - tmpfs tmpfs ro,size=1019248k,nr_inodes=254812,mode=755
28 27 0:22 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:10 - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
29 18 0:23 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:11 - pstore pstore rw
30 27 0:24 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,pids
31 27 0:25 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,memory
32 27 0:26 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,net_cls,net_prio
33 27 0:27 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,perf_event
34 27 0:28 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,blkio
35 27 0:29 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,cpuset
36 27 0:30 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,hugetlb
37 27 0:31 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,cpu,cpuacct
38 27 0:32 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,devices
39 27 0:33 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,freezer
40 19 0:34 / /proc/sys/fs/binfmt_misc rw,relatime shared:23 - autofs systemd-1 rw,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct
41 18 0:7 / /sys/kernel/debug rw,relatime shared:24 - debugfs debugfs rw
42 20 0:35 / /dev/hugepages rw,relatime shared:25 - hugetlbfs hugetlbfs rw
43 20 0:16 / /dev/mqueue rw,relatime shared:26 - mqueue mqueue rw
44 18 0:36 / /sys/fs/fuse/connections rw,relatime shared:27 - fusectl fusectl rw
45 23 202:1 / /boot rw,relatime shared:28 - ext4 /dev/xvda1 rw,data=ordered
46 23 0:37 / /var/lib/lxd/containers/test-1.zfs rw,relatime shared:29 - zfs lxd/containers/test-1 rw,xattr,noacl
47 23 0:38 / /var/lib/lxd/images/628c432840e1aedc44006d3c6f7ace79d50753d2267b159289cd2e7490f2348f.zfs ro,relatime shared:30 - zfs lxd/images/628c432840e1aedc44006d3c6f7ace79d50753d2267b159289cd2e7490f2348f ro,xattr,noacl
48 22 0:39 / /run/lxcfs/controllers rw,relatime shared:31 - tmpfs tmpfs rw,size=100k,mode=700
49 48 0:33 / /run/lxcfs/controllers/freezer rw,relatime shared:32 - cgroup freezer rw,freezer
50 48 0:32 / /run/lxcfs/controllers/devices rw,relatime shared:33 - cgroup devices rw,devices
51 48 0:31 / /run/lxcfs/controllers/cpu,cpuacct rw,relatime shared:34 - cgroup cpu,cpuacct rw,cpu,cpuacct
52 48 0:30 / /run/lxcfs/controllers/hugetlb rw,relatime shared:35 - cgroup hugetlb rw,hugetlb
53 48 0:29 / /run/lxcfs/controllers/cpuset rw,relatime shared:36 - cgroup cpuset rw,cpuset
54 48 0:28 / /run/lxcfs/controllers/blkio rw,relatime shared:37 - cgroup blkio rw,blkio
55 48 0:27 / /run/lxcfs/controllers/perf_event rw,relatime shared:38 - cgroup perf_event rw,perf_event
56 48 0:26 / /run/lxcfs/controllers/net_cls,net_prio rw,relatime shared:39 - cgroup net_cls,net_prio rw,net_cls,net_prio
57 48 0:25 / /run/lxcfs/controllers/memory rw,relatime shared:40 - cgroup memory rw,memory
58 48 0:24 / /run/lxcfs/controllers/pids rw,relatime shared:41 - cgroup pids rw,pids
59 48 0:22 / /run/lxcfs/controllers/name=systemd rw,relatime shared:42 - cgroup name=systemd rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
60 23 0:40 / /var/lib/lxcfs rw,nosuid,nodev,relatime shared:43 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
61 22 0:41 / /run/user/0 rw,nosuid,nodev,relatime shared:44 - tmpfs tmpfs rw,size=204712k,mode=700
62 23 202:5 /var/lib/lxd/shmounts /var/lib/lxd/shmounts rw,relatime shared:1 - ext4 /dev/xvda5 rw,errors=remount-ro,data=ordered
116 40 0:46 / /proc/sys/fs/binfmt_misc rw,relatime shared:45 - binfmt_misc binfmt_misc rw

```

In this case, what if we want to keep xe-guest-utilities on the system along with LXD running.
Can this thing be available in future releases!

Thanks,
Rahul C.

**Comment by stgraber** [comment]
@sforshee could you take that one?

According to Stefan Bader (our residing xen expert), /proc/xen is empty until it's mounted, so it makes no sense for the kernel over-mounting protection to kick in here.

**Comment by sforshee** [comment]
@rchincholkar I think I have a fix for this problem. Could you test the kernel at http://people.canonical.com/~sforshee/gh2238/ and let me know how it works? Thanks.

**Comment by rchincholkar** [comment]
Thanks for the fix @sforshee 
I tested the kernel and It works great.

Thanks!
Rahul C

**Comment by stgraber** [comment]
Cool. Closing this issue then, I'll let @sforshee take care of the server side of things, get this sent upstream and applied to the Ubuntu stable kernels.

**Comment by sforshee** [comment]
@rchincholkar could you verify the fixed in the proposed kernel for xenial? See http://launchpad.net/bugs/1607374. Let me know if you need any help. Thanks!

**Comment by rchincholkar** [comment]
@sforshee I have verified the proposed kernel for xenial. 
It is working without any problem now.
Thanks!
