### ISSUE TITLE
Contribute a basic french translation to test gettext

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#224]
We have gettext support but it's currently untested as we only have C support. So we should have at least another language in master so we can test things a bit.

**Comment by jggc** [comment]
I'm willing to translate to french. I guess for now you want to translate directly in https://github.com/lxc/lxd/blob/master/po/lxd.pot or create a file like `po/fr/lxd.po` ? However there might be a couple of weeks of delay before I have time to go through all of them.

**Comment by stgraber** [comment]
Hi,

Yeah, we need to create a "fr.po" file under po/ which is a translated copy of lxd.pot.

I'm happy to do a first pass at translating things to French but certainly welcomes any help keeping the translation up to date after that!

Thanks!

**Comment by jggc** [comment]
Oh it's true I had forgotten you speak french. It's as you wish, I'm willing to try even the first pass to spare you that job.

Just tag me somewhere if you need help about translations. I don't think I'm ready yet to get involved in the code but that time will come.
