### ISSUE TITLE
return code missing when executing command with  interactive = False and wait-for-websocket = False

### ISSUE THREAD

**Issue by mixxx911** [lxc/lxd#2243]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Xenial
 * Distribution version: 16.04
apicompat: 0
auth: trusted
environment:
  addresses:
  - 10.60.17.169:8443
  - 10.0.3.254:8443
  - 10.3.0.9:8443
  - 10.4.16.173:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFxjCCA66gAwIBAgIQFWuRZCl8mrBZ20SfnDCY4jANBgkqhkiG9w0BAQsFADA4
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRgwFgYDVQQDDA9yb290QHBp
    cmwtbmRuLTMwHhcNMTYwNzIwMTQ1MTIyWhcNMjYwNzE4MTQ1MTIyWjA4MRwwGgYD
    VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRgwFgYDVQQDDA9yb290QHBpcmwtbmRu
    LTMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCy/RGmxveBxZgUCyH4
    CXXP2a5OK0Gx2g2JEZiNnXLVaXAoFuHnLzmcm7xU8jwuBj4wSFOBIEWpem+UJjs1
    Pf58DZpW8kBB9s76Jbxt4GxN5EyDG2rDqxZSpl4LpxG0pCLLVn6oEqKRVRt0iOBC
    5W2VCrMi9iMADB57aQ9fzoNIWwtfyziqoZ/wW3vn+QTLQDifn6K/5Q+wlmTwGZVN
    cvFxctP+ME3Mb8uUXFMf22OVo3j7mvPY6Yl6/hY5NRT58IQD9r9XPha5ImqRPrAt
    chfbuTosaoGDY8r/9hz41e6pCAaViDxFkuBK2qkODvMhwjIGXSMLQzF+9C8Ob9ch
    8Bf8A0kiLRb2uqSLQz3/bKJSHTaF8G2Lj+pMCOQ0yI0VBJTzE8SkQVVJDeEKrosD
    YgQOgWtgl76zO3dVZeWSuyyJlshLl2ghqvHmUBpOy5art/4QrWDfrjYKuizmBij9
    dbNwB1/hsYghQT9DhevjaRxu6nFx0k2ltq1o0Ouu5sGA6SFZBk6v+lpBFKZgC+L5
    MFuMkspAvaRuy9/ZN7E4xdJGTLt6bi/GohW4SH0Gt6rt7VFn2tKOrAb2G9ftD/C1
    4YM/K4P7MWCRF1WmJ64xyznBv+cp0qFsw/qusSZa8t3GLcKL2gO65er1pmjQ9buN
    pk1DTBn+n9btIeelWG+HfUlK0QIDAQABo4HLMIHIMA4GA1UdDwEB/wQEAwIFoDAT
    BgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMIGSBgNVHREEgYowgYeC
    CnBpcmwtbmRuLTOCDzEwLjYwLjE3LjE2OS8yNIIjMjAwMTo0MjA6NDRmMToxOjIy
    NTpiNWZmOmZlNDI6ZmMvNjSCGWZlODA6OjIyNTpiNWZmOmZlNDI6ZmMvNjSCHGZl
    ODA6OmIwZjU6NDNmZjpmZWRkOjNhYjgvNjSCCmZlODA6OjEvNjQwDQYJKoZIhvcN
    AQELBQADggIBAJ39QBq+LEVY2QVYIsAIrynCTVi8N05ibTPKwwsJATvRJC7tOG51
    yVYXhNyzGTaJFIMtLMm5JTEVQfOhL+XvTfGMCmjshAAd+8/hIti7i/N1OJZVJ2VF
    QZBVcZBf23fiKZzIgGPRLDqJRBsdl7hb6NxGWEoSMMWYpiWcXP1uEYO5PA1jspHS
    ID6j3l0UwLqSdPyiSV3p00/Jx/Wn0O8n0qy0DeqRSb19SEzaleefiKMd0mDwccTt
    wR+NMo0Ke8JqwkobB088vUGee10VgfcOqeU2qfNcocNETg263+OIW9cTZ3QTuhpE
    qfZqwJF3rzgJLo2uLrRuyocTglGw0WZk2JszTQ2LV3F0X57gbqA7Y0VRGywjw4Q3
    MVwcVVNmKAf5di7en+fmh/DDMNViNG/LrGEh3G5BHMVtJ++0Um2b/Zo2gvrLDYfL
    MZPrBZdfRQFvJOs/AE6EHd3KmwlHivjDwzLbVFPggGnrV0BfOjGEcUg1sQlYNxZi
    RnzDCxLU1n76v8Wu7yFn6nSP+jWEadeCOYPHpXXnTp9kyRL3jQ9ZpK9CuNU4byQc
    OsrnEnw6EAh+i5NHrEe6Bde0DnoiZbM/G5jem+w5wZwFnbSNGRs+vW5DzaBvtWqP
    JVZjJxETbXF7BKZmpqdh5Np6oD5D1eg1gGQbgS39bmjztCxUkUYPMJ38
    -----END CERTIFICATE-----
  certificatefingerprint: 2f489a11b69a7918b1439493a59c10e9ab2d88c6ab57c13e0815ff35d6c05319
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-31-generic
  server: lxd
  serverpid: 21783
  serverversion: 2.0.3
  storage: zfs
  storageversion: "5"
config:
  core.https_address: 0.0.0.0:8443
  core.trust_password: true
  storage.zfs_pool_name: lxd-zfs-pool
public: false

# Issue description

The issue is really easy to explain: when I try to execute a remote command with the following configuration:

interactive = False
wait-for-websocket = False

The json string that I receive when the command terminates does not include the
metadata: {return: return-code}
Metadata is null in this case, so I do not know if the command terminated with or without success .

**Comment by tych0** [comment]
If I understand the code correctly, it should always list the return code unless something in the command setup (e.g. PTYs failed to get created or something). Can you post the full operation status? I would expect it to be a failed status, although probably with no real information based on my read of the code :(

**Comment by mixxx911** [comment]
Hey there,

I can list to you the list of operation to replicate the error.

Create a container:

```bash
lxc launch ubuntu:trusty c1
```

launch a command inside this container:

```bash
curl -s --unix-socket /var/lib/lxd/unix.socket -X POST -d '{"command": ["sleep", "15"], "environment": {}, "wait-for-websocket": false, "interactive": false}' a/1.0/containers/c1/exec | jq .
```

response:
```
{
  "type": "async",
  "status": "Operation created",
  "status_code": 100,
  "metadata": {
    "id": "c04ce448-014e-4307-8c7f-d769023e7afe",
    "class": "task",
    "created_at": "2016-08-01T19:28:19.439917463+02:00",
    "updated_at": "2016-08-01T19:28:19.439917463+02:00",
    "status": "Running",
    "status_code": 103,
    "resources": {
      "containers": [
        "/1.0/containers/c1"
      ]
    },
    "metadata": null,
    "may_cancel": false,
    "err": ""
  },
  "operation": "/1.0/operations/c04ce448-014e-4307-8c7f-d769023e7afe"
}
```
Get the response:

curl -s --unix-socket /var/lib/lxd/unix.socket a/1.0/operations/c04ce448-014e-4307-8c7f-d769023e7afe | jq .
```
{
  "type": "sync",
  "status": "Success",
  "status_code": 200,
  "metadata": {
    "id": "c04ce448-014e-4307-8c7f-d769023e7afe",
    "class": "task",
    "created_at": "2016-08-01T19:28:19.439917463+02:00",
    "updated_at": "2016-08-01T19:28:19.439917463+02:00",
    "status": "Success",
    "status_code": 200,
    "resources": {
      "containers": [
        "/1.0/containers/c1"
      ]
    },
    "metadata": null,
    "may_cancel": false,
    "err": ""
  }
}
```
As you can see in the response there is no return code of the sleep.
Right now I cannot try it, but if you put wait-for-websocket=true at the end you get the status code.

**Comment by tych0** [comment]
Cool, thanks. With your example I was able to reproduce, see the above patch.
