### ISSUE TITLE
Option for Access-Control-Allow-Credentials header

### ISSUE THREAD

**Issue by 18augst** [lxc/lxd#2245]
# Required information

 * Distribution: Debian
 * Distribution version: Jessie
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.7.0
   * LXC version: 2.0.0
   * LXD version: 2.0.0
   * Storage backend in use: dir

# Issue description

[Allow web applications to run CORS](https://github.com/dobin/lxd-webgui/issues/5).
Firefox browser fails to make any request to lxd daemon api. It throws a `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at` error. 

# Steps to reproduce

 1. Install lxd on one machine
 2. Install lxd-webgui on the other
 3. Try to open it with Firefox Browser

# Information to attach

Can we have an option for `Access-Control-Allow-Credentials` header?

**Comment by stgraber** [comment]
We already have config options to allow for cross origin connections.

See doc/configuration.md and the core.https_allowed_origin	, core.https_allowed_methods and core.https_allowed_headers keys.

**Comment by 18augst** [comment]
@stgraber then how I should set `Access-Control-Allow-Credentials` header properly? Can't find anything usable in `doc/configuration.md`. Firefox really doesn't work without that header. Chrome works ok.

**Comment by stgraber** [comment]
Hmm, maybe I misunderstand the reason for Access-Control-Allow-Credentials.

The description I read says it's related to being able to forward cookies, but LXD doesn't use cookies at all so why is this relevant?

**Comment by 18augst** [comment]
Let me describe it as it should be done.

In order, to use LXD API we should send credentials(certificate) with each request. So, to use it with JavaScript XHR's we should set "withCredentials=true" to XHR Request. When we do so, Firefox can not finish this request, because there's no `Access-Control-Allow-Credentials: true` header in response (Google Chrome works ok, BlackBerry browser throws security alert, but we can proceed, Safari doesn't work as FF).

**Comment by stgraber** [comment]
Seems odd that they require this for x509 authentication but browsers do tend to be weird and inconsistent...

**Comment by 18augst** [comment]
@stgraber thank you for your advice on the introduction of amendments to the code. Modestly hope that satisfied all requirements.
