### ISSUE TITLE
Profile mistake results in really poor error message

### ISSUE THREAD

**Issue by bigjools** [lxc/lxd#2251]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-31-generic
   * LXC version:
   * LXD version: 2.0.3-0ubuntu1~ubuntu16.04.2
   * Storage backend in use: dir

# Issue description

I set up a profile to mount /dev/kvm in the container, however my host didn't have that present at the time. When trying to launch the container you get:
```
⟫ lxc start mcp1
error: Failed to get device attributes: no such file or directory
Try `lxc info --show-log mcp1` for more info
⟫ lxc info --show-log mcp1
Name: mcp1
Architecture: x86_64
Created: 2016/08/01 05:43 UTC
Status: Stopped
Type: persistent
Profiles: openstack

Log:
```

It took me a while to work out it was a bad mount.

# Steps to reproduce

 1. Create a profile with a mount path that doesn't exist
 2. Launch a container with that profile

**Comment by tych0** [comment]
This behavior has changed in master, 0f708ae6e2e04ff5b1beb399bf41c7b6f9a192b3 should hopefully make it so the error is much more obvious.

**Comment by stgraber** [comment]
Right, one of my fixes should pick this up, either by detecting the missing device and reporting it very clearly or at least by showing you part of the LXC error log which should point out the same.
