### ISSUE TITLE
Grep command

### ISSUE THREAD

**Issue by dakshi5** [lxc/lxd#2254]
While creating containers over LXD, through a script, machine went out of IP addresses. So new containers were getting created but without any assigned IP address. 

`lxc list | grep RUNNING | wc -l `
This works fine.

but
`lxc list | grep -c RUNNING` 

throws an error:

`goroutine 815 [IO wait]:
net.runtime_pollWait(0x7f5b34d14b58, 0x72, 0xc8203f2000)
 /usr/lib/go-1.6/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203259c0, 0x72, 0x0, 0x0)
 /usr/lib/go-1.6/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203259c0, 0x0, 0x0)
 /usr/lib/go-1.6/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820325960, 0xc8203f2000, 0x1000, 0x1000, 0x0, 0x7f5b34d0b028, 0xc8200900a0)
 /usr/lib/go-1.6/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8203081b0, 0xc8203f2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
 /usr/lib/go-1.6/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f5b34d15128, 0xc8203081b0, 0xc8203418c8, 0xc8203f2000, 0x1000, 0x1000, 0x444ea3, 0x0, 0x0)
 /usr/lib/go-1.6/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc8201a8800, 0xc8203f2000, 0x1000, 0x1000, 0xc82058dd1d, 0x0, 0x0)
 <autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8203cd920)
 /usr/lib/go-1.6/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8203cd920, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
 /usr/lib/go-1.6/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820341860)
 /usr/lib/go-1.6/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
 /usr/lib/go-1.6/src/net/http/transport.go:853 +0x10a6
`

**Comment by tych0** [comment]
Hmm. Can you paste the full traceback for all goroutines? This seems like a race, I'm not sure that the `-c` makes any difference.

**Comment by dakshi5** [comment]
Its hard to reproduce.

**Comment by tych0** [comment]
Ok, well if you can reproduce it please post the full backtrace. afcffb844b0f4cbcf558800a636ee17ba51a3772 fixes something like this on master, so it may be fixed if it is the same issue.

**Comment by dakshi5** [comment]
oh! the error looks pretty much same. It was due to concurrent reads too.

**Comment by tych0** [comment]
Ok, I'll close this for now. If you find a different error, feel free to file another bug with the full stack trace. Thanks!
