### ISSUE TITLE
Changing zfs pool, and lxd root path

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#2269]
* Distribution: ubuntu 
 * Distribution version: 16.04
 *  "lxc info" 
apicompat: 0
auth: trusted
environment:
  addresses:
  - :8443
  architectures:
  - x86_64
  - i686
  certificate: |
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-34-generic
  server: lxd
  serverpid: 29045
  serverversion: 2.0.3
  storage: zfs
  storageversion: "5"
config:
  core.https_address: :8443
  core.trust_password: true
  storage.zfs_pool_name: lxd-zfs-1
public: false

I have 2 questions:

1. How to transfert containers/images into another zfs pool and change zfs pool in lxd?

I have a zfs file pool ( lxd-zfs-1) and want to change it. I have lot of containers, images, deleted images inside.

so i have created a new pool on a real disk (zfs-pool-1).

i have done snapshots and do send/receive for each filesystems so now when i do a zfs list i see the same things int the old and new pool.

so i wanted to change storage.zfs_pool_name:
lxc config set storage.zfs_pool_name zfs-pool-1
but it says:
error: Can not change ZFS config. Images or containers are still using the ZFS pool:

# Steps to reproduce

 1. zfs: create a new pool
 2. zfs: for each filesystem X  inside old pool do something like zfs snapshot  "X@snap1" ; zfs send "X@snap1" | zfs receive "zfs-pool-1"/X
 3. try to change lxd config: 
lxc config set storage.zfs_pool_name zfs-pool-1

2. How to change the root path of lxd in zfs pool?

zfs list show that lxd create containers/images directories at the root of the pool: pool/images, pool/containers.
How to tell lxd to have a subdirectory inside?
 pool/ldx/container, pool/lxd/images?

Regards,
Gaetan.

**Comment by stgraber** [comment]
zfs-pool-1/lxd would be a valid value for storage.zfs_pool_name which would create entries under the "lxd" filesystem (which you would have to create manually first with zfs create).

Now as far as moving things between pools, that's simply not supported by LXD at this time.
We may add support for this once we officially support multiple storage pools, but that's at least another 6 months away.

LXD will not let you change the pool name unless there is nothing in LXD using the existing pool, so if you want to do things the clean way, then your only way is to destroy all containers or images or move them to another LXD host temporarily.

If you are sufficiently familiar with ZFS to move all your data using send/receive from the existing pool to the new pool, then you can manually alter the LXD database and restart it:

    systemctl stop lxd
    echo "UPDATE config SET value='zfs-pool-1/lxd' WHERE key='storage.zfs_pool_name';" | sqlite3 /var/lib/lxd/lxd.db
    systemctl start lxd

Note that for this to work, you will need to have properly moved everything from your existing pool to zfs-pool-1/lxd. This is also obviously not a supported action, so make backups before and only do so if you understand what you're doing.

**Comment by gaetanquentin** [comment]
It worked.
i had to create a lxd filesysteme and move containers & others into it (with zfs rename: funny...). I had to rectify mount points too.
Thanks a lot.

**Comment by stgraber** [comment]
Good to hear that this worked for you.

**Comment by gaetanquentin** [comment]
Maybe i was happy too soon: i can start already created containers, i cannot create new ones:

lxc launch Image1 container1  -p profile1:

error: Failed to clone the filesystem: cannot open 'zfs-pool-1/lxd/images/66d961d34f7e193099463eeeab784ea8813e13ce0b2b846baf034b669f873ace@readonly': dataset does not exist

**Comment by gaetanquentin** [comment]
So i had to recreate the @readonly snapshot for each image and i can create container now.

**Comment by stgraber** [comment]
Yep, as I said, if you go down that road, you need to make sure things are absolutely identical :)

**Comment by haasn** [comment]
Old issue, but google still finds it. I wanted to point out that manually copying over every dataset with a `zfs send | zfs recv` is a bad idea, especially as highlighted by the fact that you were missing snapshots which LXD depends on.

The proper way to do this is to use `zfs snapshot -r` (recursive) followed by `zfs send -R` which sends a replication package of the entire tree and all snapshots leading up to that point.

**Comment by gaetanquentin** [comment]
ok. i am using btrfs now and this feature is missing (copying recursively subvolumes with their snaphots) ;-)

**Comment by fmillion** [comment]
The solution of [changing the entry in the database](https://github.com/lxc/lxd/issues/2269#issuecomment-238100571) no longer appears to work.

On my LXD installation (v5.0.2) I don't have `/var/lib/lxd/lxd.db`, but I do have `/var/lib/lxd/database/global/db.bin`. Inside of that database, there's a table named `storage_pools_config` that contains the `zfs.pool_name` entry. However, when I try changing the ZFS pool root there (without lxd running), it gets *reverted back to its original value* when I restart lxd.

This suggests that the pool name is actually being stored somewhere else in the latest versions and is being updated in the global database by something else.

Where can you go now to change the root pool path?
