### ISSUE TITLE
Allow starting a container from a remote image

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#227]
We need to specify how the data transfer between two servers works when starting a container from a remote image.

This should work without having to establish a trust relationship between the two servers and without requiring the client to download/upload the image between servers.

The mechanism will involve the client querying the remote image server, if it's a public image, then the URL is simply fed to the target server, if it's not a public image, a POST should be done to create a unique token for that download.

**Comment by hallyn** [comment]
This was closed by commit c86a4e00c2 - forgot to Close in commit msg.
