### ISSUE TITLE
cannot copy snapshot locally but to remote server ok

### ISSUE THREAD

**Issue by MarkGavalda** [lxc/lxd#2271]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-31-generic
   * LXC version: 2.0.3
   * LXD version: 2.0.3
   * Storage backend in use: ZFS

# Issue description

A simple lxc copy from snapshot into a new container that works on our other hosts fails on this one for all containers and snapshots that we tried (at least 5 random ones out of 250).

However what's interesting is that sending these snapshots to a _remote_ LXD server works perfectly, we also tested the copied container's data consistency and it's fine!

```
root@lxd-us:~# lxc copy PqC-testcontainer/testcontainer-1470606782-autobackup testcontainer-1470606782-autobackup
error: rsync failed: rsync: change_dir "/var/lib/lxd/snapshots/PqC-testcontainer/testcontainer-1470606782-autobackup/rootfs" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
```

**Edit/Update**:
Strange, when adding the server to _itself_ (!) with lxc add remote, the copying works "locally" too...!

**Comment by MarkGavalda** [comment]
Update: on this same machine the following is happening:
```
du -sh /var/lib/lxd/containers --exclude=/var/lib/lxd/containers/*.zfs
22G	/var/lib/lxd/containers
```
That's obviously not right, all other machines report a few KB tops for the same command.

What's going on here?
Thanks!

**Comment by tych0** [comment]
Is the disk full perhaps?

**Comment by stgraber** [comment]
Did you have containers created on that machine before you enabled zfs?

**Comment by MarkGavalda** [comment]
@tych0 nope, it's definitely not.

@stgraber at one time we had to re-import the ZFS pool after rebuilding the server. All containers were stopped prior to the zpool import, and after it all of them have been confirmed to have all the files/folders and general data consistency.

**Comment by stgraber** [comment]
I'm unable to reproduce this here. Also with 2.0.3 on Ubuntu 16.04 with 4.4 kernel and using the ZFS backing storage:

```
stgraber@dakara:~$ lxc launch ubuntu:16.04 PqC-testcontainer
Creating PqC-testcontainer
Starting PqC-testcontainer
stgraber@dakara:~$ lxc snapshot PqC-testcontainer testcontainer-1470606782-autobackup
stgraber@dakara:~$ lxc copy PqC-testcontainer/testcontainer-1470606782-autobackup testcontainer-1470606782-autobackup
```

What am I missing?

**Comment by stgraber** [comment]
Can you provide some more details on this?

**Comment by MarkGavalda** [comment]
No, sorry. It was a one time thing and we can't replicate it. The source of the issue was that we rebuilt the host machine and imported the ZFS pool, maybe LXD wasn't stopped prior to that, ZFS wasn't recognized correctly or something. Let's close this now and I'll get back to you as soon as we bump into this again! Thanks.
