### ISSUE TITLE
LXD client import from URL fails with URLs containing "="

### ISSUE THREAD

**Issue by zenitraM** [lxc/lxd#2272]
Using lxd 2.0.2, as packaged on Ubuntu 16.04.

I'm trying to use S3 as a backend for distribution of some LXD images.
I first discovered that you can not pass a direct URL to the .tar.gz to `lxd import` but rather something that will return the `LXC-Image-URL` and `LXC-Image-Hash` headers, so I made a simple service that will accept two query string parameters (`url` and `hash`) and will just return both headers with their contents, as S3 will not allow custom response headers to be set on an object.

However, while trying to use it from the CLI I found out that the client fails to recognize any URL that has "=" on it:
```
ubuntu@cont02:~$ lxc image import "https://test.com"
error: Missing operation metadata #<-- expected error (there are no headers on the response)
ubuntu@cont02:~$ lxc image import "https://test.com?image=http://s3/foo&hash=bar"
Manipulate container images.
(..help for lxd image import is shown)
error: wrong number of subcommand arguments
```

(A different feature request would be an easier way to be able to import just specifying a image URL and a hash client-side instead of depending on the server, but not sure if it's appropiate to file a ticket for it here)

**Comment by tych0** [comment]
You probably need to urlencode your query parameters,

`https://test.com?image=http%3A%2F%2Fs3%2Ffoo%26hash%3Dbar`

**Comment by zenitraM** [comment]
It still won't work (that URL fails as well), the problem is not the URL encoding of the params but rather the `=` on the querystring that seems to confuse the argument parser.

You can reproduce by trying to import `https://test.com/?foo` and `https://test.com/?foo=bar`

**Comment by tych0** [comment]
Ah ha, sorry, I didn't read very closely. Sounds like gnuflag is probably eating this argument.
