### ISSUE TITLE
Kill `launch`

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2285]
Now that copy is able to get and run images in #2281, maybe it is time to deprecate and remove `launch`?

**Comment by tych0** [comment]
Please no :). Then the command to launch containers would be `lxc copy`, which doesn't make a lot of sense.

**Comment by techtonik** [comment]
Presence of `launch` and `start` does't make a lot of sense too. =)

**Comment by stgraber** [comment]
Copy isn't capable of handling images at all, it only allows copying from existing containers and snapshots, it's very different from launch.

**Comment by techtonik** [comment]
@stgraber why not to extend it to handling images? How images are so different from containers and snapshots? To me image is the same container, just with dynamic part.
