### ISSUE TITLE
Set TERM to "dump" when running the client on Windows

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2288]
This is a documentation request to clarify how `lxc` on client PC interacts with the container on server. How it passes through the barriers until it reaches the application. Without these details I can not complete Windows client.

Let's start with a story. On a fresh new container installed `mc` fails to start when run inside `lxc exec` session:
```
root@far2l:~# mc
The TERM environment variable is unset!
```

So what this `TERM` is? To explain that, it is important to understand how `lxc` (client) is connected to container when running `lxc exec`:

1. `lxc` (client) connects to `lxd` (server) using default port 8443 and speaking over HTTPS protocol
2. inside this HTTPS connection, `lxc` (client) connects its `stdin` to websocket that immediately sends any content to `lxd` side
3. on `lxd` side, it connected websocket to ???

*[ ] is `websocket` created inside initial HTTPS connection or a separate one is created?
*[ ] where `lxd` connects its `stdin` websocket to?

So far, only `stdin` was discussed, but `stdout` is connected in the same way - output received from `lxd` server, which is connected to ???, is received by client and **rendered** locally.

*[ ] where `lxd` gets data for its client's `stdout` websocket?

So, communication with container using `lxc exec` uses only **two wires - stdin and stdout**. Any key you type and files you send go over one wire (that's why you can't upload your files with `lxc exec`), and any output you receive (including text and colors, and other screen operations) go over second wire.

`TERM` variable is an instruction to the program on remote server side about how to treat input that comes from your client and how to prepare output for it. How your keys are encoded, how colors should be send back, etc.

* [ ] who should set TERM variable? `lxc`, `lxd` or I myself (my program)?
* [ ] where it is possible to set TERM - what are the phases of `lxc exec`?
* [ ] why TERM is unset here?

When TERM is unset, we get error from `mc`. Setting it to `dumb` means out `stdin` and `stdout` are dumb and won't understand any advanced features.

* [ ] what are features that are still should be supported by `dumb` TERM? (need to check if my port of `lxc` client to Windows is fully compliant with `dumb` spec)

Setting `dumb` TERM:
```
root@far2l:~# export TERM=dumb
root@far2l:~# mc
Your terminal lacks the ability to clear the screen or position the cursor.
```

Well, what is the next progressive step to implement "clear screen" and "cursor positioning"? Is there a specification that says which TERM values support this feature? Or what value should TERM take when it supports those features?

**Comment by tych0** [comment]
We could probably get away with setting it to whatever the client sets it to, as it should understand the same escape sequences that the host terminal does.

**Comment by techtonik** [comment]
@tych0 but why `lxc` should set it? Where it happens? And when it should be set?

**Comment by tych0** [comment]
`lxc` should set it because it is the one who knows about the host terminal. It should be set for shell sessions, same as ssh. See the commit above for details.

**Comment by tych0** [comment]
Oh, wait. It looks like it should already be there...

**Comment by tych0** [comment]
Yeah, there is a patch that set this long ago, from lxd 0.2 onwards. In my testing it does seem to work; can you show the output of `lxc exec --debug $container /bin/true`?

**Comment by techtonik** [comment]
@tych0 it won't help, because I am running `lxc` client on Windows. =) The reason I am asking is because I want to fill missing details.

```
DBUG[08-17|18:55:37] Posting {"command":["/bin/true"],"environment":{"HOME":"/root","USER":"root"},"height":53,"interactive":true,"wait-for-websocket":true,"width":182}
 to https://192.168.100.6:8443/1.0/containers/$container/exec
DBUG[08-17|18:55:38] Raw response: {"error":"not found","error_code":404,"type":"error"}
```

**Comment by techtonik** [comment]
So I guess it should be set to `dumb` on Windows, but need some prooflinks that show which features are obligatory for `dumb`.

**Comment by tych0** [comment]
Oh, yes, I suspect `dumb` is what you're after. I think most reasonably-close-to-unix-environments on windows (e.g. cygwin, mingw, and the new Ubuntu on Windows) will probably export a TERM if they really support it, but my guess is cmd.exe doesn't support any unix-style escape sequences.

**Comment by techtonik** [comment]
Thanks.

Slipped away from my radar even though I just run into it again. =) Got to squeeze some new data about terminals at that time and lost the track of this issue. https://stackoverflow.com/questions/39001517/features-obligatory-for-term-dumb-terminal
