### ISSUE TITLE
Uploading a file should (optionally) auto-create required directories

### ISSUE THREAD

**Issue by Quicksteve** [lxc/lxd#2290]
Using the command line client or the REST API, there should be an option or it should be standard behaviour that a file upload will create the missing directory structure. Alternatively, a new endpoint should be added to the API to allow creating a directory.

Example: using a fresh container
```
ubuntu@server:~$ lxc file push somefile test-container/tmp/nonexistingdirectory/somefile
error: open: No such file or directory
errno: 2
```

If this is not supported, offline file management is basically impossible as creating directories is a basic  required operation.

**Comment by Quicksteve** [comment]
I would suggest closing this issue in favor of a new issue that describes an addition to the existing API, allowing the creation of directories with custom modes and ownerships.

**Comment by stgraber** [comment]
That's what @tych0 working on, we'll close this and the related issues all at once that's done.

The solution will be support for creating directories, support for listing directories and a flag to create any missing paths along the way in the API. The client side will be done through the -p flag for recursive creation and the -r flag to push and pull to copy a full tree.
