### ISSUE TITLE
Add option for overriding the default compression algorithm when publishing images.

### ISSUE THREAD

**Issue by IshwarKanse** [lxc/lxd#2296]
# Issue description
Sometimes we want to use a different compression algorithm or use no compression at all when publishing containers as images. e.g When publishing a large container of 4 GB, we can use no compression to publish it quickly with the cost of a large image size or use a stronger algorithm like bzip2 or lzma if we are patient enough. An option like --compression can be added to publish.

~~~
lxc publish test --alias=test --compression=none
~~~

**Comment by stgraber** [comment]
So we don't have support to change it at publish time, but you can change it live through the images.compression_algorithm option.

    lxc config set images.compression_algorithm none

**Comment by IshwarKanse** [comment]
We are ok with changing the global option. But instead of changing the global option back and forth will it be feasible to add an option when publishing images ?

**Comment by stgraber** [comment]
Yeah, we can definitely make it overridable at publish time, will be a new feature with an API extension though so won't make it to the 2.0 series.

**Comment by IshwarKanse** [comment]
Great, Thanks ! :)

**Comment by cneira** [comment]
I have this ready, but I needed to change client.go from lxc. Is it really needed to modify 
 ~go/src/github.com/lxc/lxd/client.go ?.
