### ISSUE TITLE
Delete empty parent directory when removing USB devices

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#2306]
When a USB device is removed (through hotplug or by removing the device entry), the parent directory in /dev/bus/usb isn't removed which makes it look a tiny bit different from what you'd see on the host.

LXD should attempt to rmdir the parent directory (/dev/bus/usb/XXX) and ignore failure which would reproduce the behavior we see on the host.

**Comment by tych0** [comment]
Oh, whoops :)

**Comment by stgraber** [comment]
So I really should have tested before merging :)

This isn't working. My guess is because that Remove() call is actually done against the right path, but on the host rather than in the container.

**Comment by tych0** [comment]
Oh, derp. I bet you're exactly right.
