### ISSUE TITLE
Ping missing in Debian Images installed from images.linuxcontainers.com

### ISSUE THREAD

**Issue by rst0git** [lxc/lxd#2309]
Hello, I am not sure if here is the right place to discuss this topic, but I had a problem with setting static ip address on Debian images (sid, stretch...) downloaded from  images.linuxcontainers.org:8443

The problem was after I set the network configuration the gateway server does not know about the new container until I ping it. 
I solve this with all other containers with simply with "ping -c 1 ..." but the Debian images does not have **iputils-ping installed** and I can't just "apt-get install -y iputils-ping" because I don't have network connection yet.

The way I solved it was to manually upload to the container (with file upload) iputils-ping deb package and install it, then ping the gateway server.

However is it possible the packages like "iputils-ping", "resolvconf", "ethtool" to be pre-installed in the Debian templates? 

Thank you :)

**Comment by stgraber** [comment]
You could send a pull request against the lxc project (github.com/lxc/lxc), updating the lxc-debian.in file with what you think should be in there, the folks maintaining that template can then review the proposal.

The images on images.linuxcontainers.org are the unmodified result of running the lxc template so there's something we can do on the LXD side about this.
