### ISSUE TITLE
lxd init questions are non-obvious

### ISSUE THREAD

**Issue by rogpeppe** [lxc/lxd#2310]
lxd 2.0.3

For a relatively naive user, the questions asked by "lxd init" are not obvious.
It would really help if the context and implications of each question were
made more clear.

For example, for someone unfamiliar with Linux filesystems, it's not clear
what the implications are of choosing zfs vs dir, and if zfs is chosen, what
*is* a zfs pool, where would the name be seen and what format is acceptable?

When it says "would you like LXD to be available over the network?", does that
mean from outside the current machine or from within the current machine?

What are the implications of configuring or not configuring the network bridge?
What interface names are acceptable for the bridge?

A sensible default for every question would help a lot.

**Comment by tych0** [comment]
On Wed, Aug 24, 2016 at 03:50:07AM -0700, Roger Peppe wrote:
> lxd 2.0.3
> 
> For a relatively naive user, the questions asked by "lxd init" are not obvious.
> It would really help if the context and implications of each question were
> made more clear.
> 
> For example, for someone unfamiliar with Linux filesystems, it's not clear
> what the implications are of choosing zfs vs dir, and if zfs is chosen, what
> *is* a zfs pool, where would the name be seen and what format is acceptable?
> 
> When it says "would you like LXD to be available over the network?", does that
> mean from outside the current machine or from within the current machine?
> 
> What are the implications of configuring or not configuring the network bridge?
> What interface names are acceptable for the bridge?
> 
> A sensible default for every question would help a lot.

I believe there are sensible defaults in 2.0.4, see
0e2bc7a45db13073f855914dd6b0d33f3e3f24e2

**Comment by stgraber** [comment]
Yep, we have defaults in 2.0.4 and 2.1.
