### ISSUE TITLE
LXD hangs when restart frozen container

### ISSUE THREAD

**Issue by rst0git** [lxc/lxd#2311]
* Distribution: Ubuntu 
 * Distribution version: Ubuntu 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-34-generic
   * LXC version: 2.0.4
   * LXD version: 2.1
   * Storage backend in use:

# Issue description
LXD hangs

# Steps to reproduce

Step one: Create and start new container : 
```
lxc init ubuntu: test
lxc start test
```

 Step two: Suspend the container:
`lxc pause test`

Step three: Restart the container:
`lxc restart test`

**Comment by stgraber** [comment]
Ok, so just in case you're wondering what's the way to have a container resume execution, it's with "start", not with "restart".

But yes, "restart" which sends a SIGINT event to the container indeed will hang until the container is started again which isn't very obvious, so we should have restart fail in the same way as if you were running it against a stopped container.
