### ISSUE TITLE
error: Missing parent 'lxdbr0' for nic 'eth0'

### ISSUE THREAD

**Issue by cneira** [lxc/lxd#2314]
* Distribution: Fedora 
 * Distribution version: 24
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 2.1
   * LXD version: 2.1
   * Storage backend in use: dir

# Issue description
Trying to create a container using version 2.1 from github results in the error 
error: Missing parent 'lxdbr0' for nic 'eth0'

# Steps to reproduce

this command   lxc launch ubuntu: container1
results in the following error :  

error: Missing parent 'lxdbr0' for nic 'eth0'
 

# Information to attach
[cnb@localhost ~]$ lxc info --show-log container1
Name: container1
Architecture: x86_64
Created: 2016/08/24 16:31 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20160824133144.951 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 1000000 range 65536
            lxc 20160824133144.952 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 1000000 range 65536
            lxc 20160824133225.379 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 1000000 range 65536
            lxc 20160824133225.379 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 1000000 range 65536
            lxc 20160824140501.188 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 1000000 range 65536
            lxc 20160824140501.188 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 1000000 range 65536
            lxc 20160824141046.584 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 1000000 range 65536
            lxc 20160824141046.584 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 1000000 range 65536
            lxc 20160824141053.984 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 1000000 range 65536
            lxc 20160824141053.985 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 1000000 range 65536
            lxc 20160824141054.029 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 1000000 range 65536
            lxc 20160824141054.029 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 1000000 range 65536
            lxc 20160824141203.739 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 1000000 range 65536
            lxc 20160824141203.739 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 1000000 range 65536
            lxc 20160824141203.781 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 1000000 range 65536
            lxc 20160824141203.782 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 1000000 range 65536

**Comment by cneira** [comment]
the solution is to start the  lxd-bridge service on the lxd-bridge folder.

**Comment by moon-musick** [comment]
Fails after upgrade on Ubuntu Trusty too. The service is restarted and then some containers are restarted, but without IP address, other won't even start. The message says `error: Missing parent 'lxdbr0' for nic 'eth0'`.
