### ISSUE TITLE
Rename a container 

### ISSUE THREAD

**Issue by rst0git** [lxc/lxd#2320]
Hello, it might be useful to be added an option to **rename** a container through the command line interface of lxd. The easiest way now is with ` lxc move <old name> <new name>` but it might confusing for new users.  https://www.osso.nl/blog/renaming-lxd-managed-lxc-container/ :)

**Comment by stgraber** [comment]
I wouldn't be opposed to shipping a "rename" command as part of our default alias set (so same as "mv" right now). But that won't be visible in the help because that'd absolutely be redundant with move.

Maybe the short help string for move could also be improved a bit to help.
