### ISSUE TITLE
Terminal in web-browser,  no messages are received

### ISSUE THREAD

**Issue by rst0git** [lxc/lxd#2334]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-31-generic
   * LXC version: 2.0.4
   * LXD version: 2.1
   * Storage backend in use: zfs

# Issue description
Hello, I am trying to create terminal on the client side similar to the one from the demo "tryit".

What I have done so far is: 
Django app - web-server which store the trusted certificates (for the LXD host). 

When the user (user authenticated to the web server) request to open a terminal, the web-server send post requst to `https://<ip address>:<port>/1.0/containers/<container name>/exec `
with
 ```
data = {
       "command": ["bash"],
       "environment": {
                "HOME": "/root",
                "USER": "root",
                "TERM": "xterm",
        },
        "wait-for-websocket": True,
        "interactive": True,
        "width": 80,
        "height": 25,
}
```

From the response, extract the **operation id** and the **secret** and send to the client (web browser) url address of the from `wss://<ip address>:<port>/1.0/operations/<operation id>/websocket?secret=<secret>`

Then the web browser opens a web socket to this address as follows:

```
<script src="{% static "js/jquery-3.0.0.min.js" %}"></script>
<script src="{% static "js/term.js" %}"></script>

<script type="text/javascript">
  var height = Math.max(Math.round(window.innerHeight), 20);
  var width  = Math.max(Math.round(window.innerWidth), 80);

  var sock = new WebSocket("{{ws_url}}");
  sock.onopen = function (e) {
    var term = new Terminal({
      cols: width,
      rows: height,
      useStyle: true,
      screenKeys: false,
      cursorBlink: false // To fix copy/paste in term
    });

    term.open(document.getElementById('console'));

    term.on('data', function (data) {
      sock.send(new Blob([data]), { binary: true } );
    });
  }

    sock.onmessage = function (msg) {
      if (msg.data instanceof Blob) {
          let reader = new FileReader();
          reader.addEventListener('loadend', function () {
              term.write(reader.result);
          });
          reader.readAsBinaryString(msg.data);
      } else {
          term.write(msg.data);
      }
    };

    sock.onclose = function (msg) {
      console.log('WebSocket closed');
      term.destroy();
    };

    sock.onerror = function (err) {
      console.error(err);
    };

</script>
```
Result:
   The websocket connection is successful.
   The web browser is sending messages.
   **No messages are received**

Any idea what I am missing?

I found a few other implementations but I just can't see what am I missing:
https://github.com/aarnaud/lxd-webui/blob/732a42a47c3038123c23d2f5dab1b12485297237/src/app/services/container.service.ts

https://gist.github.com/CalebEverett/bed94582b437ffe88f650819d772b682#file-lxd-exec-websock-js

https://github.com/dobin/lxd-webgui/blob/master/modules/terminal/TerminalService.js

**Comment by stgraber** [comment]
The most likely issue is that your web browser isn't authenticated to the LXD server. That is, it's not providing the right SSL client certificate to the LXD server.

It also looks like you're not connecting to the control websocket, which I believe would prevent the exec session from starting.

There are also some minor encoding differences between what the various javascript terminal libraries expect and what LXD itself does. That's why for the try-it server, we have a separate daemon which provides what the web client needs (github.com/lxc/lxd-demo-server).

**Comment by rst0git** [comment]
THANK YOU !!!!!

I found my mistake -> I was providing the control websocket instead of the interacting one. 

I don't send the SSL certificates from the web browser (because I don't want the user to be able to control the LXD instance but to only be able to open a console of the container assign to that user ) but this is OK because the web browser will only open a websocket connection along with a secret that is provided from the web-server (which sends the request along with trusted certificates to the LXD host) and according to the documentation [here](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#10operationsuuidwebsocket) the untrusted request (from the web-browser) will be allowed because correct secret is provided.

I don't connect to the control websocket but thoes not seems prevent the exec session.

And now it works great :) Thank you!

**Comment by stgraber** [comment]
Cool, good to hear it all works now :)
