### ISSUE TITLE
Failed to connect websocket

### ISSUE THREAD

**Issue by NgaNguyenDuy** [lxc/lxd#2336]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.06
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4
   * LXC version: 2.0.3
   * LXD version: 2.0.3
   * Storage backend in use: zfs

# Issue description

I can't connect to /1.0/operations/<uuid>/websocket using [ws](https://github.com/websockets/ws). The error i got is `UNABLE_VERIFY_LEAF_SIGNATURE`

The code i have used:

testsocket.js
```javascript
ocket = require('ws');
var fs = require ('fs');

var opts = {
        key : fs.readFileSync('$HOME/.config/lxc/client.key'),
        cert: fs.readFileSync('$HOME/.config/lxc/client.crt')
}

var wsout = 'wss://127.0.0.1:8443/1.0/operations/4ed54acc-a163-4b9c-a635-bc24241127d7/websocket?secret=eaa763d6d59e3434cba38221eabf1200067fed7aa635050c8788ebfaaa346aff'

var ws = new WebSocket(wsout, opts);
```

Pls help me

**Comment by stgraber** [comment]
Sounds like a TLS error to me. You're providing the client key and cert which is fine, but I suspect your tls library then attempts to validate the server's certificate and fails.

There's likely an option for you to turn off that validation (you don't really need it on localhost) or to provide the server's certificate which will have that validation then pass.

**Comment by NgaNguyenDuy** [comment]
Ah ha, Thank @stefanv I found that option from [here](https://github.com/websockets/ws/blob/master/doc/ws.md). It's `rejectUnauthorized`
