### ISSUE TITLE
How to stop centos7 container correctly?

### ISSUE THREAD

**Issue by vistoyn** [lxc/lxd#2341]
I download and run centos7 container
```bash
lxc image copy images:centos/7/amd64 local: --alias=centos7-image
lxc init local:centos7-image centos7
lxc start centos7
lxc list
+--------------+---------+-----------------------+------+------------+-----------+
|     NAME     |  STATE  |         IPV4          | IPV6 |    TYPE    | SNAPSHOTS |
+--------------+---------+-----------------------+------+------------+-----------+
| centos7      | RUNNING | 10.200.145.224 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-----------------------+------+------------+-----------+
````

Then I stop container.
```bash
lxc stop centos7
```

And the stop command hangs. 
But `lxc stop centos7 --force` works. As I understand `--force` kill container and application inside it.
How to stop centos7 container  correctly?

**Comment by stgraber** [comment]
Can you please include the "lxc info" output as requested as part of the bug report template?

LXD when used with LXC 2.0.4 (liblxc1 at version 2.0.4 or higher) should be able to shutdown centos containers cleanly. I just tried it here and it worked fine.

**Comment by vistoyn** [comment]
I use latest Ubuntu Server 16.04 LTS
```
(ubuntu)[root@ubuntu /]# uname -a
Linux ubuntu 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

(ubuntu)[root@ubuntu /]# lxc info centos7
Name: centos7
Architecture: x86_64
Created: 2016/09/04 07:39 UTC
Status: Stopped
Type: persistent
Profiles: default


(ubuntu)[root@ubuntu /]# lxc version
2.0.3
```

**Comment by stgraber** [comment]
Please update your system, LXC and LXD 2.0.4 have been available as updates for Ubuntu 16.04 for about a week now.

**Comment by lightonflux** [comment]
I have the same problem with debian jessie (amd64) containers. Just plain containers from `images:`, without any changes. I already use 2.0.4 and rebooted so the version in RAM is def .4!

I also have a problem with ubuntu and debian containers regarding apt. I just can't update or install software. Apt does gets the ip via DNS, but then just stalled. Nothing happens just staying at 0%. 

DNS in the containers works, pinging, tracerouting. I can even send text via netcat to the containers (tcp). `0% [Connecting to archive.ubuntu.com (91.189.88.152)] ` . Not sure if related but i thought i mention it.

**Comment by stgraber** [comment]
The jessie problem is unrelated.

```
Sep 06 16:53:05 jessie systemd[1]: Starting Halt...
Sep 06 16:53:05 jessie systemd[1]: Assertion 'sd_id128_randomize(&id) >= 0' failed at ../src/core/dbus.c:688, function bus_on_connection(). Aborting.
Sep 06 16:53:05 jessie systemd[1]: Caught <ABRT>, dumped core as pid 172.
```

So it's basically systemd in jessie just crashing on shutdown. The shutdown sequence itself was triggered properly, so it's down to a systemd bug.

**Comment by lightonflux** [comment]
Thanks for finding the cause. It looks like it is already reported in [DBTS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818978) and [upstream](https://github.com/systemd/systemd/pull/226).

**Comment by vistoyn** [comment]
I'm update Ubuntu by `aptitude upgrade` and centos7 container stoped correctly.
Thanks!
