### ISSUE TITLE
lxdbr0 txqueuelen tweak

### ISSUE THREAD

**Issue by cryptofuture** [lxc/lxd#2342]
This is not an issue, but I want to share this.
What I done:
I changed txqueuelen value to 10000 (not sure about best value for you) for lxdbr0 interface (I prefer set it in /usr/lib/lxd/lxd-bridge start part after iptables rules). Could be set temporary with   `ifconfig lxdbr0 txqueuelen 10000`
And changed txqueuelen for all eth* interfaces in containers to 10000 too.
```bash
# Debian-based container,  change in /etc/network/interfaces to set it permanently 
up ip link set eth0 txqueuelen 10000
```
 I also increased `net.core.netdev_max_backlog` value on host.
I didn't done a lot tests, just played with ipref a bit, but i can see like 3-5% improvement with this settings, for local (host with container, container vs container) and internet connections. 
For the note: I use non default txqueuelen value on my nic too.

**Comment by stgraber** [comment]
Interesting. If you feel like it, you may want to send a branch to add this to doc/production-setup.md.

We should also soon have a better network management API in LXD which could grow support for tweaking the queue lengths and do most of that work for you. That particular bit isn't in our initial design but is something a community member could pretty easily contribute as an extra option once we land the rest.
