### ISSUE TITLE
error: shared's user has no subuids

### ISSUE THREAD

**Issue by src386** [lxc/lxd#235]
Hi, 
I use ubuntu-server 15.04 amd64 and I installed lxd from the PPA.
When I run : 

    $ lxc launch ubuntu
I get : 

    Creating container...error: shared's user has no subuids

Here is my /etc/subuid : 

    xavier:1000000:65536

And my /etc/subgid : 

    xavier:1000000:65536

And, Indeed, xavier is my username.

**Comment by tych0** [comment]
What LXD is complaining about here is having subuid/gids for the user LXD runs as (in this case, root). If you add some subuids/gids for root and restart LXD, it should no longer complain. The next iteration of the packaging will do this for you, but for now you have to do it by hand.

**Comment by src386** [comment]
Should I set root:1000000:65536 in /etc/subuid and /etc/subgid ?
Looks like it doesn't work either.

**Comment by tych0** [comment]
On Tue, Feb 24, 2015 at 07:54:51AM -0800, src386 wrote:
> Should I set root:1000000:65536 in /etc/subuid and /etc/subgid ?
> Looks like it doesn't work either.

Did you restart LXD?

**Comment by src386** [comment]
Now it works, thank you tych0.
I'm eager to try lxd and lxcfs :)

**Comment by tych0** [comment]
On Tue, Feb 24, 2015 at 08:04:20AM -0800, src386 wrote:
> Now it works, thank you tych0.
> I'm eager to try lxd and lxcfs :)

Sure, no problem. We're on freenode at #lxcontainers if you want more
realtime chat.
