### ISSUE TITLE
Force an image update

### ISSUE THREAD

**Issue by panlinux** [lxc/lxd#2358]
Would be useful, I think, to have a way to trigger an image check & update. Maybe just for auto-update images. Something like "lxc image update <image-id|alias>". That would be quicker than waiting for the auto-update to kick in, and also quicker than deleting and re-creating the image.

**Comment by stgraber** [comment]
That's not really needed though, so long as you always start the container with the remote image, say:

    lxc launch ubuntu:x abc

LXD will ALWAYS check if a newer image is available prior to launching the container. The auto-update feature is there only to reduce download time on container startup by already having down the download in the background earlier.

**Comment by panlinux** [comment]
That's not how I usually start the containers. I have images downloaded already, and I just use their aliases.

I also think that's not how juju starts containers, it will just use the ubuntu-<series> alias the documentation tells us to create beforehand.

**Comment by stgraber** [comment]
Ok, well, anyway, we can certainly add some way to force an update over the API. 

For Juju, up until very very recently, they didn't even set the auto-update property at all and so were effectively using months old images. 

I sent them a fix for that which got merge in the last beta and the plan moving forward is for Juju to ask LXD to spawn containers from a specific simplea
streams entry, so effectively the same as I suggested with that lxc launch command.

**Comment by stevenmunro** [comment]
I've had this auto-update happen out of the blue. It was using 100% cpu and referencing /var/log/lxd/lxg.log but nothing was being written to the log apart from the the entry of 

lvl=info msg="Done updating images" t=2017-03-19T09:48:49+0000


seems to go on forever until I do a service lxd restart?

**Comment by stgraber** [comment]
That log entry means that LXD is done running the image update, so that's not what's using your CPU.

**Comment by jmoriau** [comment]
Had the same issue as @stevenmunro today, 200%+ cpu and nothing being written to the log.
![screen shot 2017-03-27 at 17 14 36](https://cloud.githubusercontent.com/assets/13310881/24363836/4778a966-1311-11e7-8bb2-11d4390c93dd.png)

Maybe it needs its own issue? I have no idea what it's doing but it's not the first time I catch it doing this.

**Comment by stgraber** [comment]
@jmoriau what LXD version are you running?

**Comment by jmoriau** [comment]
@stgraber 2.0.9

**Comment by jmoriau** [comment]
@stgraber Just saw that current release is 2.12! I didn't realize my version was so outdated, I installed it using the package manager on ubuntu 16.04. I'll try to update it first.

**Comment by stgraber** [comment]
@jmoriau both 2.0.9 and 2.12 are current release. LXD 2.0.x is the LTS branch which receives 5 years of bugfix and security updates but no new features, it's the recommended for stable production environments. LXD 2.12 is the current feature release, we put out those about once a month and they get new features and other major changes.

**Comment by jmoriau** [comment]
@stgraber Ah I get it. Could you just tell me one thing, I googled a bit, searched through the issues but I can't find this : when I edit a profile (say the default) at the bottom it says used_by : /1.0/containers/container_name
Does it mean that all these containers are using lxc 1.0 ? Even when I create new ones they still appear inside /1.0/, could you point me to where I might find some documentation on this? If indeed they are running using lxc 1.0, is there some documentation on upgrading them to 2.0?

Thanks!

**Comment by stgraber** [comment]
@jmoriau It's normal for you to see /1.0/containers/container_name, it's not related to LXC 1.0 at all, it's just a LXD API URL. LXD's REST API is currently at version 1.0 even though LXD itself is at version 2.x as the API version is only bumped if we make backward incompatible changes to it (and we've never done so).

**Comment by jmoriau** [comment]
@stgraber Ah I understand now, thank you very much for taking the time to answer!

**Comment by stevenmunro** [comment]
I had this happen again yesterday. I waited and waited and eventually it returned to normal.  I only have three containers on this machine so it seems to take a long time for just three. Is this still an issue?

**Comment by stgraber** [comment]
@stevenmunro well, we've had a few reports of this behavior but so far haven't managed to figure out what LXD actually does when that happens as there's nothing obvious in log files and it's nobody managed to come up with a reproducer for the issue which we could use to debug.

I've had a couple of people modify their init scripts to start LXD with --debug passed to it. Hopefully one of those will hit the bug again and the debug log will give us an idea of what's happening.

**Comment by stevenmunro** [comment]
@stgraber great stuff.
