### ISSUE TITLE
Basic output option for lxc list

### ISSUE THREAD

**Issue by ktechmidas** [lxc/lxd#2363]
I think it would be useful to have a basic output option, instead of just fancy (which is useless in scripts) and JSON (which is sometimes overkill)

Just something I can make a quick and dirty one-liner with occasionally, eg:

> for i in `lxc list --format basic | awk {'print $0'}` do lxc delete $i done

**Comment by stgraber** [comment]
A patch adding another sensible --format option would be fine with me. It'd still need to respect the --column option though. It could be a csv kind of output which would act just like a list if there is only a single column.

**Comment by srkunze** [comment]
Let me put another idea into the mix. Maybe, `git's log` command can act as a model for `lxc list`.

**Comment by davidfavor** [comment]
Also be great to add...

1) for csv output, support setting a delimiter so setting a blank character would more easily support using lxc list output in scripts

2) also turn off headers + separator lines for scripting
