### ISSUE TITLE
How to access containers stored in ZFS on a new host?

### ISSUE THREAD

**Issue by wexi79** [lxc/lxd#2365]
Ok, so if we have the following scenario:

- LXD on Ubuntu 16.04 host, let's call it lxd-test1 (Openstack instance)
- storage backend is ZFS on a block device /dev/vdb (Openstack volume)

Let's say that for some reason, lxd-test1 is destroyed. If I create a new instance (lxd-test2) and attach the volume that holds the ZFS pool, the pool is accessible but even if I init LXD on the new host to use an existing ZFS pool, the containers are not listed by LXD.

So what would be the correct procedure to get lxd-test2 to be able to access the containers stored on the volume? If I create lxd-test2 from a Openstack snapshot taken from lxd-test1, the containers are listed and working as expected as the original LXD config is also present on the new host. But I'm looking for a way to get a completely new LXD host to be able to use the containers stored on the volume.

I would assume that what is needed is a way to store the LXD configuration of lxd-test1 somewhere so that it could be imported to lxd-test2, but how would you do that? Or is it possible at all?

**Comment by tych0** [comment]
I think this is basically a dupe of #2286, see the discussion there. Basically, it's not possible currently, but would be possible with patches, although it's not a priority right now.

**Comment by stgraber** [comment]
You'd need to move lxd.db from the old host to the new one at the very least, possibly re-create a bunch of directory structures and stuff under /var/lib/lxd too.

**Comment by wexi79** [comment]
I tried copying lxd.db from the old host but it says:

error: Bad database version: 32

**Comment by wexi79** [comment]
Hmm OK, seems that it got it working. What I did was I edited the SQLite db and changed the db version back to the version that was present on the new host... Where does the LXD daemon keep track of the db version, it would seem that telling LXD the new version of the db would be a better approach than to edit the sqlite db itself?

**Comment by stgraber** [comment]
Your LXD will most likely fail pretty dramatically at some point in the near future if all you did was remove some schema updates from the schema table but not also reverting the actual schema changes (which is very difficult to do).

You should really make sure that your replacement host is running the same or a more recent version of LXD and in no cases, an older version.

**Comment by wexi79** [comment]
I actually reverted the schema changes also but I see your point that it would become far more difficult in the future when there are a lot of changes (snapshots etc). I'm trying a different approach now; I'll actually mount a 1GB volume as a config volume so that /var/lib/lxd is on that volume and also can be attached to the new host with openstack.

**Comment by wexi79** [comment]
Actually, having /var/lib/lxd on a separate volume and also making /etc/default/lxd-bridge symlinked to a file that resides on that volume, worked like a charm. Now I'm able to use all the containers stored in the ZFS pool on a new host in a matter of minutes.

Is this something that should be documented somewhere?

**Comment by wexi79** [comment]
Ok, that seems understandable.
