### ISSUE TITLE
Unable to assign public ips to container created using LXD. Are they any specific bridge network requirements? 

### ISSUE THREAD

**Issue by ksvn24** [lxc/lxd#2366]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

A brief description of what failed or what could be improved.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
LXD only cares about layer 2 networking. If you have a bridge that includes a physical network interface to the outside world, then all your containers will be getting IPs from whatever DHCP server is running on that network.

The default bridge we provide on Ubuntu is merely a convenience that happens to work on all setups (laptops on wifi, servers, ...) but we expect folks in production environment to just setup their own networking.

Be that macvlan on a physical interface, their own custom bridge or whatever SDN they feel like using.

**Comment by ksvn24** [comment]
I created a bridge in my networking (br0) and assigned bridge to lxd using lxd.init which prompts for the bridging network.Later,Inside the container I have asssigned my public ip and made sure that i can ping it from another server.But unfortunately , The containers could get access to the internet.I have assigned statically the ips from dhcp servers.Could you find a solution for this?

**Comment by stgraber** [comment]
Is that inside a virtual machine or some restricted network? Virtual switches (like those from OpenStack and VMWare) as well as some corporate switches have been known to reject multiple MAC addresses behind a single "physical" port.
