### ISSUE TITLE
Unable to run docker engine v1.12.1 in LXC/LXD

### ISSUE THREAD

**Issue by linsun** [lxc/lxd#2367]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
root@linsun5:/var/lib/lxd/containers# lxc info docker1
Name: docker1
Architecture: x86_64
Created: 2016/09/12 19:18 UTC
Status: Running
Type: persistent
Profiles: default, docker
Pid: 11030
Ips:
  eth0:	inet	10.190.111.195	veth6A3HT5
  eth0:	inet6	fe80::216:3eff:fe59:4256	veth6A3HT5
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 26
  Memory usage:
    Memory (current): 16.93MB
    Memory (peak): 39.35MB
  Network usage:
    eth0:
      Bytes received: 3.59kB
      Bytes sent: 1.34kB
      Packets received: 27
      Packets sent: 11
    lo:
      Bytes received: 268 bytes
      Bytes sent: 268 bytes
      Packets received: 4
      Packets sent: 4

   * Kernel version:
root@linsun5:/var/lib/lxd/containers# uname -r
4.4.0-34-generic

   * LXC version:
   * LXD version:

lxd --version
2.0.4

   * Storage backend in use: overlay file system

# Issue description

Following the blog (https://www.stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/#comment-240662) here, I can get older version of Docker running.  But when I attempt to run the latest Docker 1.12.1 engine, it failed to start the docker deamon. Error is like:

Sep 12 20:13:45 docker1 dockerd[294]: time=”2016-09-12T20:13:45.601263368Z” level=info msg=”libcontainerd: new containerd process, pid: 300″
Sep 12 20:13:45 docker1 dockerd[294]: time=”2016-09-12T20:13:45.601446148Z” level=fatal msg=”Failed to connect to containerd. Please make sure containerd is installed in your PATH or you have speci
Sep 12 20:13:45 docker1 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 20:13:45 docker1 systemd[1]: Failed to start Docker Application Container Engine.

If I set the container to be “security.privileged true”, then I can start the docker deamon fine, but I would like to avoid that if possible. Is there a way to make this work? How can I disable appamour & gives all capabilities to the processes in LXC container (e.g. lxc.cap.drop =)?   I tried to disable them myself, but still got same error, see below:

root@linsun5:/var/lib/lxd/containers# lxc config show docker1
name: docker1
profiles:
- default
- docker
config:
  raw.lxc: |
    lxc.aa_profile = unconfined
    lxc.cap.drop =
  security.privileged: "false"
  volatile.base_image: 10b58f7b0082f9b516ecfca44b9b64b8ebc6a6a331217224d9b5baeedd8ada85
  volatile.eth0.hwaddr: 00:16:3e:59:42:56
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  root:
    path: /
    type: disk
ephemeral: false

Many thanks!

# Steps to reproduce

 1. Step one
create a container using ubuntu 16.04 base image.  once container starts, use lxc exec into container and attempt to run docker engine based on instruction here:  https://docs.docker.com/engine/installation/linux/ubuntulinux/
 2. Step two
lxc exec into the container and check if the docker deamon is started by executing  'service docker status'.

Let me know if you need any other info.

**Comment by stgraber** [comment]
Only the Docker build coming from Ubuntu has the needed patches to work inside LXD.

The patches were sent upstream and some were merged, but a clean upstream build as the one you installed will not work right now.

**Comment by stgraber** [comment]
@mwhudson and @tianon should know about the current delta

**Comment by linsun** [comment]
@stgraber thanks for the info!
@mwhudson and @tianon, I appreciate if you could share the delta to make this work like @stgraber described in his comment.  Thanks!

**Comment by mwhudson** [comment]
I think it's just https://github.com/mwhudson/debian-docker/blob/ubuntu/debian/patches/lxd--25672--docker-in-userns.patch and https://github.com/mwhudson/debian-docker/blob/ubuntu/debian/patches/ignore-oom_score_adj-failure.patch (the latter has not been sent upstream yet).

**Comment by linsun** [comment]
Thank you much @mwhudson!

@stgraber, you said "Only the Docker build coming from Ubuntu has the needed patches to work inside LXD."  Can you explain how I can pick up the docker build coming from ubuntu?  I'd be happy to try it out to see if it works.

**Comment by stgraber** [comment]
sudo apt install docker.io

**Comment by stgraber** [comment]
That's what I showed in the blog post you linked to earlier.

**Comment by linsun** [comment]
@stgraber yes, I tried that based on your blog, it did work.  The only thing is that it is an older version of docker (v1.11) that didn't have the new swarm support.  Let me know if there is a Docker v1.12 around that has the fix.

**Comment by tianon** [comment]
Docker 1.12 is currently in yakkety's proposed repository, hopefully making
its way towards xenial soon

**Comment by linsun** [comment]
Thank you @tianon!  Let me know when it is out -- would love to try it!

**Comment by tianon** [comment]
Now that I'm at a computer, it looks like I was mistaken, and Docker 1.12.1 is actually in Yakkety proper (no longer just yakkety-proposed; http://packages.ubuntu.com/yakkety/docker.io). :+1:

**Comment by linsun** [comment]
Great!  Is there instruction on how to point to the Yakkety repo so' apt install docker.io' can pick it up?

**Comment by tomposmiko** [comment]
@tianon 
1.12 can be used from docker's apt repository as well. As far as I can see docker.io is not needed anymore. 

I guess LXC contributed patches have been merged.
@hallyn can you confirm?

**Comment by stgraber** [comment]
@tomposmiko if you read just a few comments above, you'll notice that @mwhudson listed two patches which are in the Ubuntu 1.12 that aren't in the upstream one and which are needed for Docker to work inside LXD.

**Comment by tomposmiko** [comment]
...and @stgraber , not @hallyn , I'm so sorry:/
