### ISSUE TITLE
Profile removes the eth0 interface

### ISSUE THREAD

**Issue by pain15** [lxc/lxd#2369]
I have used your tutorial to succeed in live migration of containers with private IP

As a part of my thesis work I have to use public IPs for connecting it to other servers during migration.
I have configured bridge network on my system and used it to assign a public IP to my container. But live migration isn't working without apply the profile and copying the profile to destination system. But, when I apply migratable profile it simples removes my IP. I tried to do ifup eth0 but it failed to come up.

so, how can i do live migration without losing my public IP

profile used:

name: migratable
config:
  raw.lxc: |
    lxc.console = none
    lxc.cgroup.devices.deny = c 5:1 rwm
    lxc.start.auto =
    lxc.start.auto = proc:mixed sys:mixed
  security.privileged: "true"
devices:
  eth0:
    nictype: bridged
    parent: lxcbr0
    type: nic

**Comment by stgraber** [comment]
The "migratable" profile has long been deprecated and a default container can now be migrated.

When you use the "apply" command, existing profiles are removed, which in your case, most likely means the "default" profile which provides connectivity to your container, is getting removed and replaced by what's in the migratable profile.

I'd suggest, just removing the migratable profile from your hosts as it really shouldn't be needed anymore on an up to date system.

If you absolutely want to use it, then you should use "lxc profile apply <container> default,migratable" to keep the default profile applied and you should also remove the conflicting eth0 device from your migratable profile with "lxc profile device remove migratable eth0".

**Comment by pain15** [comment]
Thanks for the reply,

I have removed all the existing profiles and containers on both the systems. Then I created a new container and tried to migrate it directly without applying any profile. Unfortunately i have faced two new issues in the systems respectively

1) on first server  
error: Error transferring container data: Unable to connect to: 194.47.xxx.xxx:8443

if have already done:

lxc config set core.https_address [::]
lxc config set core.trust_password some-password
lxc remote add lxd 194.47.xxx.xxx:8443
lxc remote add lxd2 194.47.xxx.xxx:8443

But it says unable to the same server on which it is migrated.

2) on second server
error: Get https://cloud-images.ubuntu.com/releases/streams/v1/index.json: lookup cloud-images.ubuntu.com on 10.241.1.10:53: read udp 194.47.xxx.xxx:34719->10.241.1.10:53: i/o timeout

**Comment by pain15** [comment]
Solved the above issue by removing few rules in iptables

coming to live migration without apply profile : DUMPING failed

error: Error transferring container data: migration dump failed
(02.217361) Error (mount.c:1675): mnt: failed to dump fs ./var/lib/lxcfs (fuse): always fail
(02.225704) Error (cr-dump.c:1600): Dumping FAILED.

Before when i got this error i used to apply the profile which would somehow make the container migrate. But now i wanna migrate it without applying profile

i tried "lxc profile apply default migratable" and "lxc profile apply default,migratable"  which resulted in error not found

**Comment by tych0** [comment]
Looks like you have a fuse (lxfs) mount inside the container, which isn't supported right now. Have you started a container inside the container you're trying to migrate?

**Comment by stgraber** [comment]
Closing this as a CRIU issue.

When you have time, can you follow the bug reporting instructions at the bottom of https://www.stgraber.org/2016/04/25/lxd-2-0-live-migration-912/ ?

We track the CRIU bugs on Launchpad against the CRIU package, I'm sure @tych0 will be happy to look into it once we have the needed information there.
