### ISSUE TITLE
LXC copy container cmd issue

### ISSUE THREAD

**Issue by linsun** [lxc/lxd#2371]
# Required information

Distribution: Ubuntu
Distribution version: 16.04
The output of "lxc info" or if that fails:
root@linsun5:~# lxc info docker1
Name: docker1
Architecture: x86_64
Created: 2016/09/12 19:18 UTC
Status: Running
Type: persistent
Profiles: default, docker
Pid: 32195
Ips:
  docker0:	inet	172.17.0.1
  docker0:	inet6	fe80::42:ffff:fe0e:7739
  eth0:	inet	10.190.111.195	vethAWSCTK
  eth0:	inet6	fe80::216:3eff:fe59:4256	vethAWSCTK
  veth22cf825:	inet6	fe80::f0b5:9eff:fe14:b8fa
  vethc829487:	inet6	fe80::d860:93ff:fe47:a10b
  vethe2c9726:	inet6	fe80::287a:b9ff:fe54:7a9
  docker_gwbridge:	inet	172.18.0.1
  lo:	inet	127.0.0.1
  lo:	inet6	::1
  veth272a03a:	inet6	fe80::38ae:edff:febf:e61f
  veth72b63ba:	inet6	fe80::2087:20ff:fe5f:975a
Resources:
  Processes: 137
  Memory usage:
    Memory (current): 119.98MB
    Memory (peak): 153.15MB
  Network usage:
    lo:
      Bytes received: 16.18MB
      Bytes sent: 16.18MB
      Packets received: 109599
      Packets sent: 109599
    veth272a03a:
      Bytes received: 4.62kB
      Bytes sent: 3.38kB
      Packets received: 52
      Packets sent: 45
    veth72b63ba:
      Bytes received: 4.58kB
      Bytes sent: 3.46kB
      Packets received: 51
      Packets sent: 46
    vethe2c9726:
      Bytes received: 4.62kB
      Bytes sent: 3.29kB
      Packets received: 52
      Packets sent: 44
    docker_gwbridge:
      Bytes received: 0 bytes
      Bytes sent: 0 bytes
      Packets received: 0
      Packets sent: 0
    eth0:
      Bytes received: 9.87MB
      Bytes sent: 4.34MB
      Packets received: 33321
      Packets sent: 38495
    veth22cf825:
      Bytes received: 4.62kB
      Bytes sent: 3.29kB
      Packets received: 52
      Packets sent: 44
    vethc829487:
      Bytes received: 4.62kB
      Bytes sent: 4.06kB
      Packets received: 52
      Packets sent: 49
    docker0:
      Bytes received: 503.36kB
      Bytes sent: 18.89kB
      Packets received: 6369
      Packets sent: 295

Kernel version:
root@linsun5:/var/lib/lxd/containers# uname -r
4.4.0-34-generic

LXC version:

LXD version:
lxd --version
2.0.4

Storage backend in use: overlay file system
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

Attempted to copy docker1 container to docker2, however, when exec into docker2 container, still sees docker1 at the prompt on the left side.  It did get assigned a new ip.  Is this as designed?  I would prefer much it says docker2 after exec into it.

# Steps to reproduce

root@linsun5:~# lxc copy docker1 docker2
root@linsun5:~# lxc list
+----------------+---------+--------------------------------+------+------------+-----------+
|      NAME      |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
+----------------+---------+--------------------------------+------+------------+-----------+
| docker1        | RUNNING | 10.190.111.195 (eth0)          |      | PERSISTENT | 0         |
|                |         | 172.17.0.1 (docker0)           |      |            |           |
|                |         | 172.18.0.1 (docker_gwbridge)   |      |            |           |
+----------------+---------+--------------------------------+------+------------+-----------+
| docker2        | STOPPED |                                |      | PERSISTENT | 0         |
+----------------+---------+--------------------------------+------+------------+-----------+
root@linsun5:~# lxc start docker2
root@linsun5:~# lxc exec **docker2** bash
root@**docker1**:~#

**Comment by stgraber** [comment]
Can you re-try after a few seconds?

The container hostname change is performed by cloud-init inside the container. Depending on what else cloud-init is doing, this can take up to 30s.

**Comment by stgraber** [comment]
```
stgraber@dakara:~$ lxc launch ubuntu:16.04 docker1 ; lxc exec docker1 hostname ; sleep 10 ; lxc exec docker1 hostname ; lxc copy docker1 docker2 ; lxc start docker2 ; lxc exec docker2 hostname ; sleep 10 ; lxc exec docker2 hostname
+ lxc launch ubuntu:16.04 docker1
Creating docker1
Starting docker1
+ lxc exec docker1 hostname
ubuntu
+ sleep 10
+ lxc exec docker1 hostname
docker1
+ lxc copy docker1 docker2
+ lxc start docker2
+ lxc exec docker2 hostname
docker1
+ sleep 10
+ lxc exec docker2 hostname
docker2
```

**Comment by linsun** [comment]
Just retried it, still not working:

root@linsun5:~# lxc exec docker2 bash
root@docker1:~#

**Comment by stgraber** [comment]
Hmm, that suggests something went wrong with cloud-init then...

What's the content of "/var/lib/cloud/seed/nocloud-net/meta-data" in docker2?

**Comment by linsun** [comment]
root@linsun5:~# lxc exec docker2 bash
root@docker1:~# cat /var/lib/cloud/seed/nocloud-net/meta-data
#cloud-config
instance-id: docker1
local-hostname: docker1

**Comment by stgraber** [comment]
Can you paste the output of "lxc config show docker1"?

**Comment by linsun** [comment]
root@linsun5:~# lxc config show docker1
name: docker1
profiles:
- default
- docker
config:
  security.privileged: "true"
  volatile.base_image: 10b58f7b0082f9b516ecfca44b9b64b8ebc6a6a331217224d9b5baeedd8ada85
  volatile.eth0.hwaddr: 00:16:3e:59:42:56
  volatile.last_state.idmap: '[]'
devices:
  root:
    path: /
    type: disk
ephemeral: false

**Comment by stgraber** [comment]
Can you paste the content of /var/lib/lxd/containers/docker1/metadata.yaml?

**Comment by linsun** [comment]
root@linsun5:~# cat /var/lib/lxd/containers/docker1/metadata.yaml
architecture: "x86_64"
creation_date: 1473434965
properties:
    architecture: "x86_64"
    description: "Ubuntu 16.04 LTS server (20160909)"
    os: "ubuntu"
    release: "xenial"
templates:
    /var/lib/cloud/seed/nocloud-net/meta-data:
        when:
            - create
            - copy
        template: cloud-init-meta.tpl
    /var/lib/cloud/seed/nocloud-net/network-config:
        when:
            - create
            - copy
        template: cloud-init-network.tpl
    /var/lib/cloud/seed/nocloud-net/user-data:
        when:
            - create
            - copy
        template: cloud-init-user.tpl
        properties:
            default: |
                #cloud-config
                {}
    /var/lib/cloud/seed/nocloud-net/vendor-data:
        when:
            - create
            - copy
        template: cloud-init-vendor.tpl
        properties:
            default: |
                #cloud-config
                {}
    /etc/init/console.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty1.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty2.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty3.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty4.override:
        when:
            - create
        template: upstart-override.tpl

**Comment by stgraber** [comment]
Hmm, weirder and weirder.

Can you do:

   lxc copy docker1 docker3
   lxc config show docker3

(so without ever starting docker3 after the copy)

**Comment by linsun** [comment]
root@linsun5:~# lxc copy docker1 docker3
root@linsun5:~# lxc config show docker3
name: docker3
profiles:
- default
- docker
config:
  security.privileged: "true"
  volatile.apply_template: copy
  volatile.base_image: 10b58f7b0082f9b516ecfca44b9b64b8ebc6a6a331217224d9b5baeedd8ada85
  volatile.eth0.hwaddr: 00:16:3e:00:8a:e0
  volatile.last_state.idmap: '[]'
devices:
  root:
    path: /
    type: disk
ephemeral: false

**Comment by stgraber** [comment]
Hmm, ok, so that's correct, it does list that it will trigger all the templates that are marked as "copy"...

Can you paste /var/lib/lxd/containers/docker3/metadata.yaml and /var/lib/lxd/containers/docker3/templates/cloud-init-meta.tpl ?

**Comment by linsun** [comment]
I don't have the two files.  I tried to start docker3, same result.

root@linsun5:~# cat  /var/lib/lxd/containers/docker3/metadata.yaml 
cat: /var/lib/lxd/containers/docker3/metadata.yaml: No such file or directory
root@linsun5:~# cat /var/lib/lxd/containers/docker3/templates/cloud-init-meta.tpl
cat: /var/lib/lxd/containers/docker3/templates/cloud-init-meta.tpl: No such file or directory
root@linsun5:~# lxc start docker3
root@linsun5:~# cat  /var/lib/lxd/containers/docker3/metadata.yaml 
cat: /var/lib/lxd/containers/docker3/metadata.yaml: No such file or directory
root@linsun5:~# cat /var/lib/lxd/containers/docker3/templates/cloud-init-meta.tpl
cat: /var/lib/lxd/containers/docker3/templates/cloud-init-meta.tpl: No such file or directory

**Comment by linsun** [comment]
one thing I want to mention is i installed docker engine on docker1 LXC container, also enabled security.privileged: "true" on docker1 LXC container.

**Comment by stgraber** [comment]
Ah, so that's the problem then, though I'm not really sure why those files would disappear...

Can you paste "ls -lh /var/lib/lxd/containers/docker3"?

And "lxc info" (no argument) would be useful too.

**Comment by linsun** [comment]
root@linsun5:~# ls -lh /var/lib/lxd/containers/docker3
total 4.0K
drwxr-xr-x 22 root root 4.0K Sep 13 15:51 rootfs
root@linsun5:~# lxc info
apicompat: 0
auth: trusted
environment:
  addresses:
  - 9.42.74.180:8443
  - 10.190.111.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFljCCA36gAwIBAgIQd3MPOx4RSbFxu+FP3ip1aDANBgkqhkiG9w0BAQsFADA1
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRUwEwYDVQQDDAxyb290QGxp
    bnN1bjUwHhcNMTYwOTA5MDI1OTMwWhcNMjYwOTA3MDI1OTMwWjA1MRwwGgYDVQQK
    ExNsaW51eGNvbnRhaW5lcnMub3JnMRUwEwYDVQQDDAxyb290QGxpbnN1bjUwggIi
    MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC3LirVXA3BcCfrG5upn8iSeX01
    Svtkkg2xlLQQrdbfmcYLwWeAA4EinG0E/q7MmiEww7Dq9zLHnJM15bdnE1pXHONF
    5Dv08TFaoI1UAs1lNU4F+RWbyPg0LHulgDLOpyVugfgA8DHa5gSlttv2g4DFHmew
    fwK8cTtWLpd5vtTNErZ9m5OgmgCfaUbZ8vzW9wGtNhFFXf1WDkoDTjCV28LLAJwQ
    kUAUC1YBZ6zfP079TLNLWP5wA4XlwNjyCddK28JxX6i73fVcCXMLwm3VYmq/rFXU
    GNVBUhgOhR55g5gKY9lGLr+sAOP192MdKpNqTVzH4kbuhwpxQWzyy9Ky4pN6Gi6h
    6WCUAt1W2+WyTQqVXe3USOKyFemQm44QuS3pigQbtQwk+ZeY9XaKsMTGg5NBMwvh
    wIG81oBDeBqlIZvkpjLvsfxHP2TD41n0v7g784Su/66OTvs9SFLXxPEzS97uho0i
    FCsjQp6K3DGRHRJ/nDWeKr60BrY4lm2sip9qo4+p6YspJMFehv673/ERiHN0+nYQ
    eMnOl1cVRgoC62sjQSmdrXtiR+NIQmjkfaWSbPx37IX+BPPE9+Mmdo/oEhSQ9cW8
    Q5syy/Pkj9qK8he/bt3Sey6X7kb8rXlubVnlX0cP/Sg1ndptvA8CXH+JyX4Tv5EK
    0u5bCKxJktL1HhixUQIDAQABo4GhMIGeMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUE
    DDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMGkGA1UdEQRiMGCCB2xpbnN1bjWC
    DjkuNDIuNzQuMTgwLzI0ghtmZTgwOjoyNTA6NTZmZjpmZWEwOmNhZTQvNjSCHGZl
    ODA6OjM0MGQ6MjFmZjpmZWI5OjczYTMvNjSCCmZlODA6OjEvNjQwDQYJKoZIhvcN
    AQELBQADggIBAGO/gUw5NObaZBOrBIqPno6oYdMilDfGUjWjw/isiACxzXEtSklA
    QmUDqj8ZY4OMGqVSW4vzhhqb5eDlLsJcL2Nb26ZNMcFzyJIUl+i+v6s7yYc4kEf7
    o23Gh+aNNw9AYMmzuDiKZSt4F0z7cVWLifcQukonO0Fq0G3s1FX9Tcia28wVFSHk
    vcpPKPiU4xhJurxH7k1JNOZ42oAkizja3r+NUAkz6wIoOIMh8dq7NC4aDXv355Ed
    qZv0APQ+ymCMYlYYhd2+62LDgD1Ko6efqJU+VHoSw13Owcsv26aNviWQ6PjwD4Hu
    jK5qd1MRic5V/OeTyOz7d4lk7su1O9ThINamTtzRO+Mniba5KccnokQmw6h0HKLE
    +t4Uv4kirK+CZzdgq9XiWnuX9miPUT1+276zS4mEcog/JZA2vvo0jaKeY/kXw1Az
    vqSMLKicMP4LPefaYAUJJeXBaQaYvRfDR131iR5cI7DaC4UOQEMlmZyR2cqV1DO/
    30eGStQraUTUVDAqnBO2ZMx4O4AF6ZU9e4tXnz8USf2s8yqrHBatRU11Cz7cWI/b
    qG0Ksvuv32JH8y23gjWcL1tucIQ0Qdp6akHNyDrZJgNA866zrk55dfaolZ1GrK4r
    BzEk5s2S40yn9jpS6MeLXfk9DQfuVgrMfrYn17Hiv2W5fYkGSzxYaU+7
    -----END CERTIFICATE-----
  certificatefingerprint: 7ab92f153423b063a8fd0149731361859bfe7d76f9bc3c330af44963264b8a5d
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-34-generic
  server: lxd
  serverpid: 361
  serverversion: 2.0.4
  storage: dir
  storageversion: ""
config:
  core.https_address: 0.0.0.0:8443
  core.trust_password: true
public: false

**Comment by stgraber** [comment]
I wonder if it's a problem with the "dir" storage backend. I was testing on zfs here.

**Comment by stgraber** [comment]
root@xenial:~# ls -lh /var/lib/lxd/containers/alpine1/
total 14K
-rw-r--r--  1 root root 637 Jan  1  1970 metadata.yaml
drwxr-xr-x 18 root root  18 Sep 13 17:53 rootfs
drwxr-xr-x  2 root root   4 Sep 13 20:03 templates

root@xenial:~# lxc copy alpine1 alpine2

root@xenial:~# ls -lh /var/lib/lxd/containers/alpine2/
total 512
drwxr-xr-x 18 root root 18 Sep 13 17:53 rootfs

**Comment by stgraber** [comment]
so that's the issue, the dir backend doesn't seem to be copying everything...

**Comment by stgraber** [comment]
Sent a fix for this issue.

**Comment by linsun** [comment]
I found in your blog on using zfs, I can try that in the meanwhile, thanks for looking into this!

**Comment by stgraber** [comment]
Yeah, using zfs or btrfs will also make a bunch of things much faster, like container creation, container copy, snapshots, ...

**Comment by linsun** [comment]
Confirmed, zfs does work, thank you @stgraber !

**Comment by linsun** [comment]
@stgraber, I have 2 questions.  1) how do I pick up your fix as a user?  2) I'd like to configure LXD to use zfs using automation scripts.  Currently I'm using terraform remote execute provisioner.   I could not find out how to do it.. Is it possible?

**Comment by stgraber** [comment]
1) It will be pushed as part of LXD 2.0.5, hopefully later this week and available through updates for Ubuntu users in a couple of weeks.

2)

    zpool create NAME DEVICE -m none
    lxc config set storage.zfs_pool_name NAME

To just create a 50GB loop device, you can do:

    truncate -s 50G /var/lib/lxd/zfs.img
    chmod 600 /var/lib/lxd/zfs.img
    zpool create lxd /var/lib/lxd/zfs.img -f -m none -O compression=on
    lxc config set storage.zfs_pool_name lxd

**Comment by linsun** [comment]
Thank you @stgraber!  I tried your steps in 2), works well!
