### ISSUE TITLE
LXC/LXD container orchestration 

### ISSUE THREAD

**Issue by hodiapa** [lxc/lxd#2396]
Is there any plans to integrate mesos like container orchestration for LXC containers? Mesos, SHipyard, Docker Swarm, kind of tools are missing for the LXC world which are crucial for wider adoption of the LXC containers. 

Are there any such tools already available for the LXC? If not are there any plans for such tools in future?

**Comment by jamesbeedy** [comment]
@buggtb, @chuckbutler ^

**Comment by buggtb** [comment]
Soooo. yes. Marathon basically `just` hooks into an underlying docker  executable on a host to provide its docker support. So my general opinion  is why not just fork it, provide LXC/LXD support for Marathon and then extend it and juju to use Marathon as a cloud provider..... thats the plan at least, at which point you'd get support from Mesos,  DC/OS and if @chuckbutler isn't lying, K8S as well.

**Comment by ranjib** [comment]
Nomad lxc driver is in pr state. It should be in master by next point
release.

**Comment by fnzv** [comment]
Ansible?

**Comment by stgraber** [comment]
Closing this generic issue as it's not something actionable for us really.
We do have #670 already which is kinda related (though, again, nothing actionable for LXD).

We'll happily fix any bug or missing feature which results from implementing such integration.
