### ISSUE TITLE
Implement push support wherever pull is supported now

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#2402]
This is a fork of #553 for the daemon side of it.

This is to track support for websocket "push" mode wherever we support websocket based "pull" right now, so unless I'm fogetting something, this is just for container migration.

When the client POST to either of those with "push" set, it will be returned a reference to a websocket operation as part of the POST operation metadata.
The client will then have to connect to that websocket (or websockets for migration) and push data.

This is different from the current "pull" mode, where a remote operation URL and secret token is provided to the target daemon, having the daemon itself connect to the source.

The expected use for this work is to have the client tool act as a relay when two LXD servers cannot talk to each other (this part of the work is tracked in #553).

**Comment by brauner** [comment]
So, when would `push` be set? There seem to be two cases mentioned in #553:
1) On transfer failure: What cases does this cover?
 - Remote is not public (as per #1510)?

2) A flag is set in the server config? `websocket_on_push`
