### ISSUE TITLE
create target directory for `pull -r` if does not exist

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2403]
```
$ lxc file pull -r far2l/root/far2l/build/install far2l
error: mkdir far2l/install: not a directory
```
The actual error is that target dir `far2l` does not exist, not `far2l/install`.

**Comment by stgraber** [comment]
Sounds reasonable and in line with "cp"'s own behavior.

**Comment by techtonik** [comment]
I will send a proper PR later.

**Comment by techtonik** [comment]
This should be better.
