### ISSUE TITLE
Does LXD has a init or configure network mode silently?

### ISSUE THREAD

**Issue by linsun** [lxc/lxd#2418]
I'd like to configure LXD (either init or just the network portion) without any prompt, by passing a configure file or params into lxd init or dpkg-reconfigure cmd.  Could you please advise if this is possible?

**Comment by stgraber** [comment]
#2413 will move network configuration from being an Ubuntu packaging thing to being an actual LXD managed object, at which point you'll very easily be able to script all of this through "lxc network".

Until then, you can configure the bridge provided by Ubuntu automatically, either through debconf (which may be a bit painful) or through this possibly easier process:
 - systemctl stop lxd-bridge
 - Edit /etc/default/lxd-bridge (so just write over it with the variables you want)
 - systemctl start lxd-bridge

**Comment by stgraber** [comment]
As far as upstream LXD is concerned, we just merged #2413 so considering this closed as you may now use the "lxc network create" command to do so.

For previous releases, what I described above should get you going.

**Comment by linsun** [comment]
Thank you @stgraber, the workaround works well!
