### ISSUE TITLE
No network configuration

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#242]
Containers created by LXD don't have any network configured.

Until we have the config and profiles implemented, we probably should at least configure the container with a network interface connected to lxcbr0.

**Comment by battlemidget** [comment]
Is this in the latest `0.8.1-0ubuntu1~ubuntu15.04.1~ppa1`?

**Comment by tych0** [comment]
Yes, it should be. There is a profile called "default" that has the
configuration.

Tycho
