### ISSUE TITLE
Networking issue - LXD Bridge Dropping connections

### ISSUE THREAD

**Issue by ktechmidas** [lxc/lxd#2420]
# Required information

 * Distribution: Ubuntu 14.04
 * The output of "lxc info" or if that fails:
driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.13.0-86-generic
  server: lxd
  serverpid: 23103
  serverversion: 2.0.3
  storage: zfs
  storageversion: "5"

# Issue description

I'm currently in China so use something called shadowsocks to bypass the website blocks (Google, Facebook etc) and noticed something strange. I will paint some scenarios (1 and 2 are connecting to the same Shadowsocks container)

1. Me -> UbuntuHost (HK) -> lxdbr0 -> shadowsocks container
2. Me -> JumpHost (Shanghai - Running HaProxy) -> UbuntuHost (HK) -> lxdbr0 -> shadowsocks container
3. Me -> JumpHost (Shanghai - Running HaProxy) -> UbuntuHost (HK)

1 works and is what I've been using for the past year, but slowly yet reliably which is why I'm researching how to "jump" using a server in Shanghai.

2 is what I've been trying to deal with for the past many hours. Essentially I wanted to proxy through a server in Shanghai then onto HK and the container, however this had some interesting results. It would connect most of the time, but occasionally (once or twice on a page full of images) it wouldn't load the image. Next refresh it would be fine. 

I ruled out everything else and found once I ran the shadowsocks process on the host (3) it was okay.

Any ideas why LXD would be dropping packets? The bit that stands out to me about SS and may have a clue is: "ShadowSocks creates a new TCP/UDP connection for each connection that it proxies." so it may be overwhelming the bridge?

https://news.ycombinator.com/item?id=11705623

**Comment by stgraber** [comment]
Symptoms sound like an MTU issue somewhere along the way.

**Comment by stgraber** [comment]
I can't think of any setting that LXD does on the bridge which would cause this, so tentatively closing this issue.

As I stated before, the described behavior sounds like an MTU problem somewhere along your path, which given the use of tunneling seems reasonably likely. You may want to manually decrease the MTU on both ends to see if this solves it. If it does, then find where big packets are being dropped and either fix the issue there or just have your router/firewall clamp the MTU to MSS.
