### ISSUE TITLE
Confused with memory.stat in container

### ISSUE THREAD

**Issue by cryptofuture** [lxc/lxd#2422]
Refering to [this discussion](https://github.com/firehol/netdata/issues/1019), I found that `cat /sys/fs/cgroup/memory/lxc/containername/memory.stat` on host, `cat /sys/fs/cgroup/memory/memory.stat` in container (after `lxc exec containername -- /bin/bash`) and `lxc exec containername -- cat /sys/fs/cgroup/memory/memory.stat` gives totally different output.
And that makes me confused.
 Ubuntu Xenial :
```
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-39-generic
  server: lxd
  serverpid: 2337
  serverversion: 2.0.4
  storage: zfs
  storageversion: "5"
```

```
@host: cat /sys/fs/cgroup/memory/lxc/containername/memory.stat
cache 196608
rss 0
rss_huge 0
mapped_file 126976
dirty 0
writeback 0
pgpgin 13329
pgpgout 13281
pgfault 21176
pgmajfault 6640
inactive_anon 0
active_anon 0
inactive_file 45056
active_file 151552
unevictable 0
hierarchical_memory_limit 9223372036854771712
total_cache 4370432
total_rss 15507456
total_rss_huge 0
total_mapped_file 2215936
total_dirty 0
total_writeback 0
total_pgpgin 1482149
total_pgpgout 1478829
total_pgfault 1879399
total_pgmajfault 1119926
total_inactive_anon 8884224
total_active_anon 7729152
total_inactive_file 1617920
total_active_file 1646592
total_unevictable 0
```

```
@container
cache 925696
rss 581632
rss_huge 0
mapped_file 872448
dirty 0
writeback 0
pgpgin 14506
pgpgout 14138
pgfault 22978
pgmajfault 7313
inactive_anon 258048
active_anon 286720
inactive_file 561152
active_file 311296
unevictable 0
hierarchical_memory_limit 9223372036854771712
total_cache 4235264
total_rss 19251200
total_rss_huge 0
total_mapped_file 2940928
total_dirty 0
total_writeback 0
total_pgpgin 1489468
total_pgpgout 1485267
total_pgfault 1888559
total_pgmajfault 1125768
total_inactive_anon 10407936
total_active_anon 9830400
total_inactive_file 1613824
total_active_file 1544192
total_unevictable 0
```

```
@host: lxc exec containername -- cat /sys/fs/cgroup/memory/memory.stat 
cache 528384
rss 90112
rss_huge 0
mapped_file 475136
dirty 0
writeback 0
pgpgin 14805
pgpgout 14654
pgfault 23373
pgmajfault 7572
inactive_anon 0
active_anon 61440
inactive_file 376832
active_file 73728
unevictable 0
hierarchical_memory_limit 9223372036854771712
total_cache 4698112
total_rss 19542016
total_rss_huge 0
total_mapped_file 3870720
total_dirty 0
total_writeback 0
total_pgpgin 1494030
total_pgpgout 1489645
total_pgfault 1893777
total_pgmajfault 1129612
total_inactive_anon 12091392
total_active_anon 10670080
total_inactive_file 835584
total_active_file 536576
total_unevictable 0
```

**Comment by stgraber** [comment]
@hallyn thoughts?

**Comment by hallyn** [comment]
Dunno - but note that with your setup (if i'm reading it right) that is a straight cgroupfs file, so lxcfs is not involved.

So I"m not quite sure what could be going on here :)  If it behaves differently in different kernels, that could be interesting too.

**Comment by cryptofuture** [comment]
I tested on another machine, where `memory.stat` works right: and I see identical information with
` cat /sys/fs/cgroup/memory/lxc/containername/memory.stat` and  `lxc exec containername -- cat /sys/fs/cgroup/memory/memory.stat` and with `cat /sys/fs/cgroup/memory/memory.stat` in container.
Now even have all the same packages (totally identical lists with `dpkg --get-selections | grep -v deinstall`) installed between two machines (both servers with lxd).
I was also able to break it and fix it back on server where it worked right, but it still didn't work in a right way on first machine.

Thats how I was able to break and fix back on second machine:
```
apt purge plymouth*
apt install mountall:amd64 plymouth-theme-ubuntu-text:amd64 plymouth:amd64 upstart:amd64
```
Interestingly enough mountall unit masked in systemd, plymouth is just boot animation (or not?) and the hell I use systemd instead upstart anyway, but it works this way somehow.
UPD: It worked for some time, and now looks like its broken on second machine too.
I even was able to see this in real time. 
Blank space: reboot time on picture. Total used memory over 200mb, when it worked right and less then ~1mb after reboot, when only nginx takes 12mb in same container.
packages was removed:`mountall:amd64 plymouth-theme-ubuntu-text:amd64 plymouth:amd64 upstart:amd64`
![shoot](https://cloud.githubusercontent.com/assets/6484506/18970261/1b393442-8680-11e6-8262-4dd7769f5976.png)

**Comment by cryptofuture** [comment]
Seems like this is [lxcfs](https://github.com/lxc/lxcfs) issue. And obviously not related to mountall and whatever. Looks like many folks have strange memory stats with it. Is it save to use lxd-git-master ppa in production? I currently use xenial repository version on servers, and lxd-git-master ppa only in localhost. I just think is a good idea to try lxcfs from git, but have no idea is it worth to mix lxcfs from git with lxd from xenial repository.

BTW, I switched to btrfs backend from zfs. Have sweat io performance tests with all possible lxd backends tests and even tried different fs for plain , can I try to publish table with tests in production-setup.md for example? I was quite surprised with results actually.

**Comment by cryptofuture** [comment]
I figured out lxcfs is 6 weeks old in lxd-git-master. I made lxcfs from git (even with pull 147 patch included) package myself, installed it on top of xenial lxd, rebooted machine and memory.stat still incorrect. 
Btw, `lxc info containername` output memory stats are correct. And that means `cat /sys/fs/cgroup/memory/lxc/containername/memory.usage_in_bytes`is correct. (checked container_lxc.go and lxc info values converts right from memory.usage_in_bytes)
for example:
```
lxc info container
Resources:
  Processes: 37
  Memory usage:
    Memory (current): 207.80MB
    Memory (peak): 267.08MB
```
```
cat /sys/fs/cgroup/memory/lxc/containername/memory.usage_in_bytes
217899008
```
But
```
cat /sys/fs/cgroup/memory/lxc/containername/memory.stat
cache 1404928
rss 225280
rss_huge 0
mapped_file 1363968
dirty 0
writeback 0
pgpgin 4605
pgpgout 4207
pgfault 5144
pgmajfault 32
inactive_anon 131072
active_anon 131072
inactive_file 36864
active_file 1331200
unevictable 0
hierarchical_memory_limit 9223372036854771712
total_cache 165269504
total_rss 47849472
total_rss_huge 29360128
total_mapped_file 44699648
total_dirty 172032
total_writeback 0
total_pgpgin 473493
total_pgpgout 432704
total_pgfault 395502
total_pgmajfault 3569
total_inactive_anon 37019648
total_active_anon 95707136
total_inactive_file 34205696
total_active_file 46186496
total_unevictable 0
```

**Comment by hallyn** [comment]
On Thu, Sep 29, 2016 at 05:38:09PM -0700, cryptofuture wrote:
> Seems like this is [lxcfs](https://github.com/lxc/lxcfs) issue.

lxcfs should only be involved if your kernel does not support cgroup
namespaces (which xenial kernel does) because otherwise real cgroupfs
is mounted.  You can verify by looking at

mount | grep cgroup

in the container, to see whehter those show up as 'cgroupfs' or
'fuse.lxcfs' filesystem type.

**Comment by cryptofuture** [comment]
> lxcfs should only be involved if your kernel does not support cgroup namespaces (which xenial kernel does) because otherwise real cgroupfs is mounted
Is this means I can remove lxcfs?
```
tmpfs on /sys/fs/cgroup type tmpfs (rw,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,clone_children)
```
Where I should dig this issue?

**Comment by hallyn** [comment]
Quoting cryptofuture (notifications@github.com):
> > lxcfs should only be involved if your kernel does not support cgroup namespaces (which xenial kernel does) because otherwise real cgroupfs is mounted
> Is this means I can remove lxcfs?
> ```
> tmpfs on /sys/fs/cgroup type tmpfs (rw,mode=755)
> cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
> cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb)
> cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids)
> cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
> cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
> cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
> cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event)
> cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
> cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
> cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
> cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,clone_children)
> ```
> Where I should dig this issue?

lxcfs should be mounted on things like /proc/cpuinfo and /proc/meminfo in the
container.  It's not strictly needed, but it gives things like virtualized
uptime.

**Comment by cryptofuture** [comment]
I still have this think, however since commit  [2776cf0](https://github.com/firehol/netdata/commit/2776cf07577f0527bc8e14d5c3b0cb4fb87dcf16) netdata (use and recommend it for container monitoring) now support alternative memory chart based on `memory.usage_in_bytes`and `memsw_usage_in_bytes. And `memory.usage_in_bytes` always gives right values.

However, I found something fresh regarding possible memory.stat miscalculation:
>CGroup memory swap accounting is disabled, swap limits will be ignored

**Comment by stgraber** [comment]
right, swap isn't accounted by default unless you boot your kernel with swapaccount=1

**Comment by cryptofuture** [comment]
No help with `swapaccount=1` just 6 mb more ram shown, missing like 200mb. Still wrong memory.stat. But, yes since I have alternative per container memory chart now, this issue not bother me.
Maybe yakkety kernel will help, but I need to wait for hwe stack, for production, then.

**Comment by stgraber** [comment]
Ok, well, I'm going to be closing this issue as in any case, it can't be a LXD issue :)

Basically, if you get invalid values from a path under /sys/fs/cgroup, then it's a kernel bug.
If you get invalid values from /proc/meminfo in the container but /sys/fs/cgroup looks good, then it's a lxcfs bug.

For kernel bugs, you should report them at: https://launchpad.net/ubuntu/+source/linux/+filebug
Feel free to subscribe ~ubuntu-lxc so we can keep an eye on it.

For lxcfs bugs, you should report them at: https://github.com/lxc/lxcfs/issues
