### ISSUE TITLE
Stateful snapshot restore failed

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2436]
Ubuntu 16.04 Xenial

lxc 2.0.4
lxd 2.0.2
criu 2.5

$ lxc info cnt1 
Name: cnt1
Architecture: x86_64
Created: 2016/09/29 20:51 UTC
Status: Stopped
Type: persistent
Profiles: default
Snapshots:
  snap0 (taken at 2016/09/29 21:11 UTC) (stateful)

$ lxc restore cnt1 snap0
error: exit status 1

cat /var/log/lxd/cnt1/snapshot_restore

(00.716597) Error (criu/cgroup.c:1209): cg: Failed writing a to devices//lxc/cnt1/devices.deny: Invalid argument
(00.767380) Error (criu/cr-restore.c:1020): 10229 killed by signal 9: Killed
(00.789633) Error (criu/cr-restore.c:1885): Restoring FAILED.

Running a c program in the background, by closing the stdout,stdin, and stderr streams in the program.
Able to exit from the container while executing the program.

Able to take a stateful snapshot, however restore is being failed which in turn fails the live migration.

**Comment by tych0** [comment]
I believe I've fixed this with d52a3522588ebbaebcc944e5a8d894056b0f65c8 in the current criu master tree; unfortunately it didn't go in 2.6, but should be in 2.7.

**Comment by upuvvad1** [comment]
Any tentative date for 2.7 release ?
Or can I patch the commit on 2.5.2 and build it, to make it work ?

**Comment by tych0** [comment]
CRIU releases monthly, https://criu.org/Release_schedule is their release schedule. You should be able to build from their current master tree, though, as that has the patch.

**Comment by upuvvad1** [comment]
Thank you @tych0 .
It worked.

Is there any alternative to run background jobs and do the live migration / stateful snapshot and restore?
I looked at the discussion for the issue #1677.
Is there going to be any patch for that anytime soon ?

**Comment by upuvvad1** [comment]
@tych0 
Now the restore fails with this error 

error: Error transferring container data: restore failed:
(00.367239)      1: Error (criu/files-reg.c:1488): File sys/fs/cgroup/systemd has bad mode 040755 (expect 040775)
(00.437959) Error (criu/cr-restore.c:1023): 35617 killed by signal 9: Killed
(00.450235) Error (criu/cr-restore.c:1889): Restoring FAILED.

This error is being thrown for like 1 out of 10 migrations.
I wonder why it's being succeeded in the other 9 migrations.

**Comment by tych0** [comment]
On Thu, Sep 29, 2016 at 04:55:52PM -0700, upuvvad1 wrote:
> Thank you @tych0 .
> It worked.
> 
> Is there any alternative to run background jobs and do the live migration / stateful snapshot and restore?

You're talking about the fact that you can't dump stuff that's been
backgrounded via `lxc exec`? The only alternative at the moment is to
just run an ssh server.

Implementing support for dumping stuff that's been backgrounded via
`lxc exec` is not impossible, it's just a low priority.

**Comment by tych0** [comment]
On Fri, Sep 30, 2016 at 11:05:53AM -0700, upuvvad1 wrote:
> @tych0 
> Now the restore fails with this error 
> 
> error: Error transferring container data: restore failed:
> (00.367239)      1: Error (criu/files-reg.c:1488): File sys/fs/cgroup/systemd has bad mode 040755 (expect 040775)
> (00.437959) Error (criu/cr-restore.c:1023): 35617 killed by signal 9: Killed
> (00.450235) Error (criu/cr-restore.c:1889): Restoring FAILED.
> 
> This error is being thrown for like 1 out of 10 migrations.
> I wonder why it's being succeeded in the other 9 migrations.

This is fixed with current lxc master and current criu master (via
cb19e69e62433943c8fa2190f9d138666beaa355 and
0ab5703fcff8aafc3512c8b3cb446780b1c6974c respectively). Both of those
will eventually make it into stable releases, but the fixes are only a
few weeks old right now.

Tycho

**Comment by upuvvad1** [comment]
Thanks @tych0
