### ISSUE TITLE
7e13a75b breaks client on Windows

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2438]
7e13a75b breaks build on Windows.

```
.\client.go:1887: undefined: syscall.Stat_t
.\client.go:1888: undefined: syscall.Stat_t
```

```
		mode := fInfo.Mode()
		uid := int(fInfo.Sys().(*syscall.Stat_t).Uid)
		gid := int(fInfo.Sys().(*syscall.Stat_t).Gid)

		return c.PushFile(container, targetPath, gid, uid, fmt.Sprintf("0%o", mode), f)
```

**Comment by techtonik** [comment]
`lxc/file.go` has `getOwner` that can be extended to check `os.FileInfo` structure, but if I understand it right, it is not accessible from `client.go`, so what is the proper way to fix that? Moving `getOwner` to `shared` doesn't seem good, because `lxd` doesn't use it.

**Comment by stgraber** [comment]
Moving it to shared is the way to go for now. We'll reshuffle a bunch of that stuff when we deal with #1926

**Comment by stgraber** [comment]
It's also annoying that travis doesn't support Windows, otherwise we could have it test-build the client the same way we do for MacOS...

**Comment by techtonik** [comment]
I can setup AppVeyor for that.

**Comment by stgraber** [comment]
Added support for it now.
