### ISSUE TITLE
Container Can't start after upgrade

### ISSUE THREAD

**Issue by hooramin** [lxc/lxd#2441]
Hello , 

**# Required information**

> root@MainServer /home # lsb_release -a
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04 LTS
> Release:        16.04
> Codename:       xenial
- The output of "lxc info" on lxc host:

> driver: lxc
> driverversion: 2.0.0
> kernel: Linux
> kernelarchitecture: x86_64
> kernelversion: 4.4.0-22-generic
> server: lxd
> serverpid: 2349
> serverversion: 2.0.0
> storage: zfs
> storageversion: "5"
> config:
> storage.zfs_pool_name: MainMachine1
- The container :  Ubuntu 16.04

**# Issue description**
Container won't start after dist-upgraded and reboot.

**# Steps to reproduce**
1. I  did dist-upgrade inside a container after long time about 3 month.
2. After upgrading finished , i rebooted that container.
3. It didn't boot again .
4. I log in to my lxd host try starting it with lxc start command but i faced with error.

**# Information to attach**

```
root@MainServer /home # lxc start hosting
error: Error calling 'lxd forkstart hosting /var/lib/lxd/containers /var/log/lxd/hosting/lxc.conf': err='exit status 1'
Try `lxc info --show-log hosting` for more info
```

the output of `lxc info --show-log hosting`  was very long , i don't know i should copy that from where ?

_In addition i fear that do dist-upgrade on the host , because all of other container on this host is production vps and if i upgrade lxd and any issue turns the containers down , i will lost my customers for ever !_

**Comment by brauner** [comment]
Can you please provide all the information requested in our issue template https://github.com/lxc/lxd/issues/new?

**Comment by hooramin** [comment]
I updated the first post @brauner .

**Comment by stgraber** [comment]
Can you update your system? You're still running LXD 2.0.0 when LXD 2.0.4 is available through updates.

**Comment by stgraber** [comment]
Your kernel is similarly very out of date (20 updates behind) so this suggest your system was never updated and so is lacking hundreds of bugfixes and security fixes.

**Comment by hooramin** [comment]
@stgraber Thank you for your response.
i will do update and report the result here .

but please answer my 2 questions if possible :
When i do upgrade on my ubuntu , i faced with `no space left on device` error , it's because i made mistake when i was creating zfs pool at first ! I used all of my storage size for zfs pool .
my first question is : **can i decrease size of that pool and make some free space for upgrading kernel?**

Now one of my container can't be started as i said above , and i have so important files on it ,
my second question is : **Can i access the container files while it's stopped ?**

**Comment by stgraber** [comment]
ZFS doesn't support shrinking, so unfortunately you can't shrink it. You'd have to create a new zfs pool and move the content from one to the other and then destroy the original.

If the container is mounted, you should be able to access its files at /var/lib/lxd/containers/NAME/rootfs/

**Comment by stgraber** [comment]
Haven't heard back in more than two months, assuming that upgrading the machine fixed it.
