### ISSUE TITLE
Connecting to REST through browser

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2447]
I am trying to debug the server side of the LXD protocol. Is there any way to make Chrome authenticate with the given `client.crt` file? I am on Windows FWIW.

**Comment by techtonik** [comment]
I was able to convert and import certificate by Windows:

    openssl pkcs12 -clcerts -inkey client.key -in client.crt -export -out client.pfx

But Chrome doesn't propose to select it on authentication. The certificate is imported successfully and present in Personal section of "Certificates" window.

Could the reason be that generated certificate contains `TLS Web Server Authentication` instead of `TLS Web Client Authentication`?
```
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
```
Or maybe I need to sign it additionally?

**Comment by techtonik** [comment]
```
$ openssl.exe x509 -in client.crt -purpose
Certificate purposes:
SSL client : No
SSL client CA : No
SSL server : Yes
SSL server CA : No
Netscape SSL server : Yes
Netscape SSL server CA : No
S/MIME signing : No
S/MIME signing CA : No
S/MIME encryption : No
S/MIME encryption CA : No
CRL signing : No
CRL signing CA : No
Any Purpose : Yes
Any Purpose CA : Yes
OCSP helper : Yes
OCSP helper CA : No
Time Stamp signing : No
Time Stamp signing CA : No
-----BEGIN CERTIFICATE-----
...
```

**Comment by techtonik** [comment]
[GenerateMemCert](https://github.com/lxc/lxd/blob/d9e40ccb1008ea4097735a6721e10dbe90ed63fe/shared/cert.go#L170) should generate different type for `lxc.remote.generateClientCertificate -> shared.FindOrGenCert -> GenCert`.

**Comment by stgraber** [comment]
Hmm, yeah, client generated certificates should definitely have the client type set instead of server... Not a problem when LXD itself validates it, but I can see while a browser wouldn't present it...

**Comment by techtonik** [comment]
New certificate after the fix:
```
$ openssl.exe x509 -in client.crt -purpose
Certificate purposes:
SSL client : Yes
SSL client CA : No
SSL server : No
SSL server CA : No
Netscape SSL server : No
Netscape SSL server CA : No
S/MIME signing : No
S/MIME signing CA : No
S/MIME encryption : No
S/MIME encryption CA : No
CRL signing : No
CRL signing CA : No
Any Purpose : Yes
Any Purpose CA : Yes
OCSP helper : Yes
OCSP helper CA : No
Time Stamp signing : No
Time Stamp signing CA : No
...
```

Generating it in Windows format:
```
$ openssl pkcs12 -clcerts -inkey client.key -in client.crt -export -out client.pfx
```

Then importing by double-clicking on `.pfx`, and trying to access https://192.168.1.5:8443/1.0/containers (local LXD server) gives the correct choice of certificate! =)

**Comment by techtonik** [comment]
Maybe release certificate generation as a standalone tool? Looks very useful.
