### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2449]
`lxd` test failure is expected, because server part can't be run on Windows. `shared` tests would be nice to have and `client` test should probably work too.
```
# github.com/lxc/lxd/shared
.\util_test.go:38: undefined: syscall.Setxattr
.\util_test.go:47: undefined: syscall.Setxattr
.\util_test.go:59: undefined: GetAllXattr
.\util_test.go:79: undefined: GetAllXattr
.\util_test.go:158: undefined: ReadLastNLines
.\util_test.go:177: undefined: ReadLastNLines
FAIL    github.com/lxc/lxd/shared [build failed]

# github.com/lxc/lxd/lxd
.\nsexec.go:26:23: fatal error: sys/mount.h: No such file or directory
compilation terminated.
FAIL    github.com/lxc/lxd/lxd [build failed]

github.com\lxc\lxd>go test
--- FAIL: TestLocalLXDError (0.00s)
        client_test.go:34: GetLocalLXDErr returned the wrong error, EXPECTED: connection refused, ACTUAL: %!s(<nil>)
FAIL
exit status 1
FAIL    github.com/lxc/lxd      0.077s
```

**Comment by stgraber** [comment]
Yeah, there's definitely no way you'll get a clean test run for the lxd directory until someone spends some serious time contributing a windows container backend, but having shared and lxc pass tests on Windows and MacOS would be nice.

Will be easy enough to add a test run to Travis and AppVisor once any issue with those is sorted out.

**Comment by techtonik** [comment]
`GetLocalLXDErr` is `connectViaUnix` fail, which should probably use https://github.com/natefinch/npipe on Windows.

**Comment by stgraber** [comment]
connectViaUnix simply can't work on Windows, no matter how much porting you do since it's only relevant if lxd can be running on the same system as the client, which it can't on Windows.

**Comment by stgraber** [comment]
connectViaUnix should probably be somehow restricted to Linux with all other platforms returning an error if attempted

**Comment by techtonik** [comment]
I mean that Windows' named pipes provides the same mechanism for local communication channel. So maybe it is possible to factor out this interface into some FileSocketConnection?

**Comment by techtonik** [comment]
Well, creating `util_linux_test.go` seems to be the easiest solution.

**Comment by stgraber** [comment]
My point is that making a generic Socket/Pipe connector in LXD doesn't make sense. It'd bring in more dependencies for something which will just never work anyway as this feature is only relevant if the client and daemon run on the same machine.

Much easier to just make this fail on other OS and skip any tests.
