### ISSUE TITLE
Option to load extra dnsmasq option in 2.3 via lxc network 

### ISSUE THREAD

**Issue by anigeo** [lxc/lxd#2452]
As in LXD version on or before 2.2, there use to have `LXD_CONFILE` in `/etc/default/lxd-bridge` to let you load extra dnsmasq options, but after `lxc network` introduced in version 2.3, seems this option has gone, is there any other way to do that now?

**Comment by niko-daniel** [comment]
Did you see [configuration.md](https://github.com/lxc/lxd/blob/master/doc/configuration.md#network-configuration)

**Comment by stgraber** [comment]
That's what raw.dnsmasq is for.
