### ISSUE TITLE
'sudo lxd init' should enable zfs compression by default

### ISSUE THREAD

**Issue by dustinkirkland** [lxc/lxd#2461]
We've just completed some zfs testing, and have determined that, generally, enabling zfs compression reduces disk usage by 20-25%, at a cost of 2-3% CPU overhead, on most systems.  Please enable zfs compression, when the user sets up zfs storage with 'lxd init'.

**Comment by tych0** [comment]
It's been enabled for a while: f75a9136daac62aabfd209f3a6121ef13e23a8d5 and should be enabled in lxd's >= 2.3

**Comment by stgraber** [comment]
Yep, that's all been done already a couple weeks ago :)

**Comment by dustinkirkland** [comment]
;-)  Cool.


:-Dustin
