### ISSUE TITLE
/var/lib/lxcfs provides unexpected behavior

### ISSUE THREAD

**Issue by smoser** [lxc/lxd#2468]
# Required information
 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * LXC version: 2.0.4-0ubuntu1~ubuntu16.04.1
   * LXD version: 2.0.4-0ubuntu1~ubuntu16.04.1
   * Storage backend in use: zfs

# Issue description
`/var/lib/lxcfs` being mounted in the container provides unexpected behavior for users of `/var`.

    root@x1:~# find /var >/dev/null  2>err; echo $?
    1
    root@x1:~# tail -n 5 err 
    find: '/var/lib/lxcfs/cgroup/devices/lxc/x1/system.slice/systemd-update-utmp.service/devices.deny': Permission denied
    find: '/var/lib/lxcfs/cgroup/devices/lxc/x1/system.slice/dev-random.mount/devices.allow': Permission denied
    find: '/var/lib/lxcfs/cgroup/devices/lxc/x1/system.slice/dev-random.mount/devices.deny': Permission denied
    find: '/var/lib/lxcfs/cgroup/devices/lxc/x1/user.slice/devices.allow': Permission denied
    find: '/var/lib/lxcfs/cgroup/devices/lxc/x1/user.slice/devices.deny': Permission denied

    root@x1:~# ls -l /var/lib/lxcfs/cgroup/devices/lxc/x1/user.slice/devices.allow
    ls: cannot access '/var/lib/lxcfs/cgroup/devices/lxc/x1/user.slice/devices.allow': Permission denied
    root@x1:~# ls -l /var/lib/lxcfs/cgroup/devices/lxc/x1/                        
    ls: cannot access '/var/lib/lxcfs/cgroup/devices/lxc/x1/devices.allow': Permission denied
    ls: cannot access '/var/lib/lxcfs/cgroup/devices/lxc/x1/devices.deny': Permission denied
    total 0
    -rw-r--r-- 1 nobody nogroup 0 Oct  6 18:36 cgroup.clone_children
    -rw-rw-r-- 1 nobody root    0 Oct  6 18:36 cgroup.procs
    ?????????? ? ?      ?       ?            ? devices.allow
    ?????????? ? ?      ?       ?            ? devices.deny
    -r--r--r-- 1 nobody nogroup 0 Oct  6 18:36 devices.list
    drwxr-xr-x 2 root   root    0 Oct  6 18:36 init.scope
    -rw-r--r-- 1 nobody nogroup 0 Oct  6 18:36 notify_on_release
    drwxr-xr-x 2 root   root    0 Oct  6 18:36 system.slice
    -rw-rw-r-- 1 nobody root    0 Oct  6 18:36 tasks
    drwxr-xr-x 2 root   root    0 Oct  6 18:36 user.slice

Root generally expects to be able to read things, likely tools or users will find errors here.

# Steps to reproduce
 1. `lxc launch ubuntu-daily:xenial x1`
 2. `lxc exec x1 find /var/`

**Comment by stgraber** [comment]
Closing as this should got to https://github.com/lxc/lxcfs

It's also not a real issue and is far from unusual for fuse filesystems. In fact, for most fuse filesystems, root can't list any attributes at all.

Anyway, @brauner looked at fixing some of those issues in the past, I'm sure we can convince him to take a closer look at what's still going on with 2.0.4 :)

**Comment by pepa65** [comment]
Can't these system-fuse file systems be placed in a separate location?? Even in the very root would be good, like `/fuse`.
