### ISSUE TITLE
Make Container ReadOnly

### ISSUE THREAD

**Issue by mqasim-jahia** [lxc/lxd#2471]
Hi,

Is it possible to change a container state in readonly.

I have one Container running apache in it and after I done the configuration I want to make it readonly so no one can change the configuration on the container.

Thanks

**Comment by stgraber** [comment]
Are you talking about the container configuration in the LXD database or about the service that's inside the container?

For the former, no, we don't support this, nor would it really make any sense to add it until we have some kind of support for identity/tenant. Right now, you should simply not let people you don't trust have access to the LXD API.

For the latter, it's very unlikely that your Linux distribution will boot with a read-only filesystem. You should be able to do it still by setting raw.lxc and using the lxc.root.options key. That being said, there'd be nothing preventing root in the container to then just remount / read-write, so I'm not sure how much protection that'd really give you.

**Comment by mqasim-jahia** [comment]
I am talking about the service inside the container. Basically I have container and inside the I have apache installed and apache is just a proxy (forwarding request to other server).
I have the control of the LXD and it is secure.

Thanks I really appriciate

**Comment by stgraber** [comment]
Ok, so yeah, you can try:

    lxc config set CONTAINER raw.lxc lxc.root.options=ro

But that may not work on some backends and will likely break a bunch of LXD features that assume that the container can be written to in some cases.

You can also just have an init script in the container remonut / read-only at boot, that should be fine and run after LXD is done. That being said, it's still likely to break a whole lot of things in the container itself as Linux distributions don't typically expect them to be read-only.

The more common way to do what you want is simply to run apache as an unprivileged user (which is the case by default with www-data) and just make sure that there is no path that it can write to.

**Comment by mqasim-jahia** [comment]
Thanks a lot
