### ISSUE TITLE
Live migration fails if OSPF is used in the container

### ISSUE THREAD

**Issue by fluboi** [lxc/lxd#2473]
# Required information

 * Distribution: Ubunto 16.04.1
 * Kernel version: 4.4.0-38-generic
 * LXC version: 2.0.5
 * LXD version: 2.4.1
 * Storage backend in use: zfs

# Issue description

Live migration is not possible if OSPF is used in the container. Migration fails with the following messages:

```
error: Error transferring container data: migration dump failed
(00.568350) Warn  (arch/x86/crtools.c:132): Will restore 8668 with interrupted system call
(00.572573) Warn  (arch/x86/crtools.c:132): Will restore 9274 with interrupted system call
(00.631159) Warn  (arch/x86/crtools.c:132): Will restore 8674 with interrupted system call
(00.722985) Warn  (arch/x86/crtools.c:132): Will restore 8680 with interrupted system call
(00.827495) Warn  (arch/x86/crtools.c:132): Will restore 8699 with interrupted system call
(00.870483) Warn  (arch/x86/crtools.c:132): Will restore 8706 with interrupted system call
(00.870872) Warn  (arch/x86/crtools.c:132): Will restore 8710 with interrupted system call
(00.882325) Warn  (arch/x86/crtools.c:132): Will restore 8711 with interrupted system call
(00.932500) Warn  (arch/x86/crtools.c:132): Will restore 8715 with interrupted system call
(00.933495) Warn  (arch/x86/crtools.c:132): Will restore 8717 with interrupted system call
(00.982186) Error (sk-inet.c:105): Unsupported proto 89 for socket e528
(00.982236) Error (cr-dump.c:1303): Dump files (pid: 8917) failed with -1
(00.996372) Error (cr-dump.c:1600): Dumping FAILED.
```

It's problematic because OSPF could be very usefull setting up some dynamic routing scenario... especially when using live migration to have no (or very small) interruption.
Is there something really problematic with OSPF ?

**Comment by brauner** [comment]
As of now, `CRIU` seems to only support `IP`, `TCP`, `UDP`, and `UDPLITE`. A patch to `CRIU` would be required to add support for the `OSPF` `IP` protocol.

**Comment by fluboi** [comment]
Yes, I've seen [that](https://github.com/xemul/criu/blob/master/criu/sk-inet.c#L96). 
But I realize that it's not realated with LXC/LXD but more with CRIU. I close this issue and re-open one [here](https://github.com/xemul/criu/issues/225).
