### ISSUE TITLE
Version info for dev builds

### ISSUE THREAD

**Issue by abitrolly** [lxc/lxd#2475]
My dev client built with:
```
go get -t -v -d ./...
go install -v ./lxc
```
It always reports;
```
>lxc version --verbose
2.0.0
```
And I can't find where it is set in the Makefile.

**Comment by brauner** [comment]
The version for the client is set in `shared/flex.go`. If you're building from current git master this should always be set to the latest release. Please make sure that you're actually executing the client binary you built and not the system binary. It would also be easier to just use `make` in the `LXD` go repo and then test the client you build from the corresponding `bin/` directory in your `GOPATH`.

**Comment by abitrolly** [comment]
You were right. There was another binary lurking in PATH.
