### ISSUE TITLE
CPU usage - Missing from lxc info or /1.0/containers/<name>/state

### ISSUE THREAD

**Issue by givre** [lxc/lxd#2477]
# Required information

 * Distribution: Ubuntu 
  Operating System: Ubuntu 16.04.1 LTS
  Kernel: Linux 4.4.0-28-generic
  Architecture: x86-64

* lxd --version
  2.0.2

# Issue description
From : https://github.com/lxc/lxd/blob/master/doc/rest-api.md
/1.0/containers/<name>/state

This should report CPU usage.  From api-rest or lxc info  
I can't find the cpu usage:
```


lxc info container_name
Name: container_name
Architecture: x86_64
Created: 2016/09/27 13:42 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 32749
Ips:
  eth0:	inet	185.49.22.54	54-eth0
  eth0:	inet6	fe80::fb:e0ff:fe23:3fe5	54-eth0
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 70
  Disk usage:
    root: 17.93GB
  Memory usage:
    Memory (current): 339.23MB
    Memory (peak): 776.73MB
  Network usage:
    eth0:
      Bytes received: 1000.41MB
      Bytes sent: 268.95MB
      Packets received: 10461576
      Packets sent: 395530
    lo:
      Bytes received: 17.07MB
      Bytes sent: 17.07MB
      Packets received: 46080
      Packets sent: 46080

```

# Steps to reproduce

lxc info <container_name>

# Questions

Is that normal ? Where the cpu usage can be found ?
Thanks

**Comment by stgraber** [comment]
Nope, cpu usage reporting isn't part of 2.0.x, it was added much more recently in LXD 2.2 as documented in https://github.com/lxc/lxd/blob/master/doc/api-extensions.md

For 2.0, you're best to look at the documentation for that branch:
https://github.com/lxc/lxd/tree/stable-2.0/doc

**Comment by givre** [comment]
Thanks !
