### ISSUE TITLE
Renaming of running container while migration fails.

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2479]
lxd - 2.4.1
lxc - 2.4.1
Ubuntu 16.04

lxc move cnt49 destn_host:cnt-49

error: Error transferring container data: migration restore failed
(00.018440) Warn  (criu/cr-restore.c:852): Set CLONE_PARENT | CLONE_NEWPID but it might cause restore problem,because not all kernels support such clone flags combinations!
(00.026276) Error (criu/cgroup.c:992): cg: Can't move 5695 into devices//lxc/cnt-49/init.scope/tasks (-1/-1): No such file or directory
(00.026317)      1: Error (criu/cgroup.c:1107): cg: Can't move into devices//lxc/cnt-49/init.scope/tasks (-1/-1): Bad file descriptor
(00.053703) Error (criu/cr-restore.c:1023): 5695 killed by signal 9: Killed
(00.090410) Error (criu/cr-restore.c:1889): Restoring FAILED.

Without renaming, migration succeeds.

**Comment by tych0** [comment]
Yeah, unfortunately this isn't really something we can support right now :(. Once we have https://bugs.launchpad.net/ubuntu/+source/criu/+bug/1580765 fixed, this should be possible.

**Comment by stgraber** [comment]
Going to close this as it's a CRIU bug that's already being tracked by us.
