### ISSUE TITLE
Invalid limits lead to unmodifiable container

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#2483]
Can be reproduced with:

    lxc config set blah limits.memory 512M
    lxc info blah
    lxc config unset limits.memory

Only way to solve it is to manually go and fix the database...

Expected behavior would be for config validation to fail during set and prevent the value from ever hitting the DB.

**Comment by nodoubleg** [comment]
will this fix make its way back to Xenial?

**Comment by stgraber** [comment]
Yes, it will be in 2.0.6
