### ISSUE TITLE
Security Issue: Networking Fails with UFW OUTBOUND DROP ALL as default in /etc/default/ufw

### ISSUE THREAD

**Issue by walkerandco** [lxc/lxd#2506]
* Distribution: Ubuntu
 * Distribution version: 16.04-latest
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 2.0.5
   * LXD version: 2.4.1
   * Storage backend in use: zfs

# Issue description
When outbound communication is denied by default in UFW rules, LXD networking fails to start and containers do not receive a valid IPv4 address and a valid but unroutable IPv6 address.

A brief description of what failed or what could be improved.

Provide information in documentation on ports which need to be allowed for networking to properly start AND/OR advise in documentation to configure ufw outbound drop all to be deleted on shutdown and reenabled on startup with timeout delay so that this happens after lxd starts.

# Steps to reproduce

 1. Step one
Install latest lxd with ubuntu ufw, with ufw enabled.

 2. Step two
Set default outbound rule in /etc/default/ufw to "DROP"

 3. Step three
Reboot. LXC/LXD will not assign IPv4 address or routable IPv6 address until DROP is removed from /etc/default/ufw, then ufw & lxd services restarted. Restarting containers then gives valid ips. Repeat steps and the error will recur. Unlikely to be platform dependant.

No valid information to attach at this stage. Issue easy to replicate across distros and IaaS providers.

**Comment by stgraber** [comment]
That's odd, I was sure I made our code prepend iptables allow rules to allow just that...

**Comment by stgraber** [comment]
I'm setting up a test environment to see what's going on with this.

**Comment by stgraber** [comment]
I'm assuming by DENY, you mean DROP as DENY isn't a valid iptables target.

**Comment by stgraber** [comment]
Reproduced the issue. I think the issue is that the veth device has its traffic dropped by that OUTPUT policy and so doesn't reach the bridge where dnsmasq is running.

**Comment by stgraber** [comment]
Hmm, not only that but also the host contacting the bridge members... Anyway, will work on a fix for this a bit later today.

**Comment by walkerandco** [comment]
Hi Stephane, I corrected the bug report for DROP instead of DENY so that Google indexes the right issue that people might encounter. I thought this would be a dnsmasq problem too because the IPs are not being assigned and I'm assuming dnsmasq is leasing the ips when functioning correctly.

When reinstalling lxdbr0 (as I had originally tried to do thinking it was a more generic error), lxd init throws all sorts of errors and it breaks lxd networking altogether. I found it was very important not to try to reconfigure lxdbr0 without removing the outbound rule on ufw.

On my setup it entered a broken state if the rule wasn't removed and the bridge was reconfigured, even purging with apt-get didn't quite work, so I think that any reconfiguration of the bridge when in this state causes some sort of brctl configuration error. I couldn't get any bridge to work without a full reinstall as the problem was quite deep seated.

**Comment by stgraber** [comment]
Sent a pull request which adds the required OUTPUT rules to make things work.

With that in place, the container will get an IP address and be able to talk to the DNS server that dnsmasq provides.

Note that LXD networks will bypass ufw rules as far as FORWARDING (so reaching out of the host network). If you want to prevent containers from being routed to the outside world, you can set the ipv4.routing=false and ipv6.routing=false properties.

**Comment by ladams00** [comment]
Commenting for posterity: I've hit this issue with the Edge channel of LXD in snap (git-d36b797) which 'lxd --version' shows 2.15.  Revising the ufw rules as suggested (though not ideal) helps greatly as a workaround.
