### ISSUE TITLE
setcap cap_net_raw,cap_net_admin=eip for tcpdump in lxc ?

### ISSUE THREAD

**Issue by juju4** [lxc/lxd#2507]
# Required information

 * Distribution: Ubuntu
 * Distribution version: xenial
 * The output of "lxc info" or if that fails:
```
$ uname -a
Linux dpjenkins 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ lxc info|egrep '(version|storage)'
apiversion: "1.0"
  driverversion: 2.0.4
  kernelversion: 4.4.0-38-generic
  serverversion: 2.0.4
  storage: dir
  storageversion: ""
```

# Issue description

I want to set above capability inside lxc.
goal is to be able to setup cuckoo sandbox inside lxc.

As seen above, I tried to removed to all cap drop without success.
setting container to privileged worked but is too much.

Is it possible? or not like httpd/setfcap on centos?

Thanks

# Steps to reproduce

```
root@default-ubuntu-1604-1476629798:~# setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
Failed to set capabilities on file `/usr/sbin/tcpdump' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
```

**Comment by stgraber** [comment]
It's currently not possible because of the lack of kernel support for unprivileged filesystem capabilities.
You could make your container privileged at which point setcap should work just fine, but this also makes the whole container much more dangerous to the system, so you may prefer sticking with setuid inside an unprivileged container for the time being.

@hallyn is working on a kernel patchset which will add this feature to the kernel, at which point setcap will just start working the way you'd expect.

Closing this issue as there's unfortunately nothing we can do about it in LXD itself.

**Comment by juju4** [comment]
no problem. thanks for the detailed information @stgraber !

**Comment by alex9434** [comment]
Hi @sgraber and @candlerb  , unfortunately I have exactly the same issue with a privileged lxc container. 

```
setcap cap_fowner,cap_mknod,cap_sys_chroot=ep /usr/bin/loolforkit
Failed to set capabilities on file `/usr/bin/loolforkit' (Operation not supported)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
```
I have checked that extended attributes are enabled:
```
cat /proc/fs/ext4/sda6/options | grep xattr
user_xattr
```
Is it OK to add this to the existing issue or should I open a new one?

**Comment by candlerb** [comment]
You did check with `ls -l /usr/bin/loolforkit` that it is not a symlink?

But in any case, it's a different issue.  Firstly, you said it's an lxc container (not an lxd container).  And secondly, you said it occurs in a privileged container - this ticket is about setcap in unprivileged containers.

**Comment by alex9434** [comment]
Thank you, I have opened a new ticket with the additional information:
lxc privileged container: setcap Failed to set capabilities on file #3172

**Comment by candlerb** [comment]
Wrong link, should be to https://github.com/lxc/lxc/issues/3172

**Comment by alex9434** [comment]
thank you, sorry my mistake
