### ISSUE TITLE
LXD containers are unable to reach  network 

### ISSUE THREAD

**Issue by netmoleCBA** [lxc/lxd#2510]
good day ,

i am installed lxd on ubuntu 16.04 with default bridge  can anyone suggest me change to  have containers accessible  on local network ?

**Comment by stgraber** [comment]
To have your containers accessible from other hosts on your network, you can either use macvlan, which is by far the easiest method but comes with the downside that the host and containers won't be able to talk.

To do so, you'll typically just need to do:
    - lxc profile device set default eth0 nictype macvlan
    - lxc profile device set default eth0 parent eth0

Or if you do need communication between your host and containers, then you must bridge the physical network device of the host and then use that bridge with LXD.

Doing that, involves modifying /etc/network/interfaces in your distribution to setup a bridge to replace your current network configuration. Once that's done, run:

    dpkg-reconfigure -p medium lxd

And select the option for an existing bridge and enter its name.

**Comment by netmoleCBA** [comment]
i am make  bridge   
`source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto br0
iface br0 inet static
        bridge_ports ens160
        address 192.168.100.1
        netmask 255.255.255.0
        network 192.168.100.0
        broadcast 192.168.100.255
        gateway 192.168.100.247
        # dns-* options are implemented by the resolvconf package, if installed
        dns-nameservers 192.168.1.1
iface ens160 inet manual
`
it got adress from dhcp but still is unable  to connect outside or ping from network to container 

it is possible to handle container whole  adress and route    as parameter in lxc launch ?

**Comment by stgraber** [comment]
What's your "ifconfig -a" looking like now and "lxc config show --expanded <container name>"

**Comment by netmoleCBA** [comment]
ifconfig 

`br0`       Link encap:Ethernet  HWaddr 00:0c:29:64:78:f8
          inet addr:192.168.100.1  Bcast:192.168.100.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fe64:78f8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:164613 errors:0 dropped:2895 overruns:0 frame:0
          TX packets:53938 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:161071898 (161.0 MB)  TX bytes:3685481 (3.6 MB)

ens160    Link encap:Ethernet  HWaddr 00:0c:29:64:78:f8
          inet6 addr: fe80::20c:29ff:fe64:78f8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:173000 errors:0 dropped:34 overruns:0 frame:0
          TX packets:53993 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:163886706 (163.8 MB)  TX bytes:3689615 (3.6 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:80 errors:0 dropped:0 overruns:0 frame:0
          TX packets:80 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:5920 (5.9 KB)  TX bytes:5920 (5.9 KB)

veth8W2D32 Link encap:Ethernet  HWaddr fe:f2:a8:42:58:02
          inet6 addr: fe80::fcf2:a8ff:fe42:5802/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:47 errors:0 dropped:0 overruns:0 frame:0
          TX packets:43705 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3486 (3.4 KB)  TX bytes:3837001 (3.8 MB)
`
lxc command 

`config:
  storage.zfs_pool_name: lxd`
brctl show 
t-krmela@blade:~$ brctl show
bridge name     bridge id               STP enabled     interfaces
br0             8000.000c296478f8       no              ens160
                                                        veth8W2D32

**Comment by stgraber** [comment]
Oops, github mangled my request, can you get "lxc config show --expanded CONTAINER-NAME"

**Comment by netmoleCBA** [comment]
name: git
profiles:
- default
config:
  volatile.base_image: 6f25adef061c3f2186c6910bff8cacd0c63e1493e3f8b616e52eb84076890bd1
  volatile.eth0.hwaddr: 00:16:3e:59:b8:f5
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    type: disk
ephemeral: false

**Comment by stgraber** [comment]
Ok, that all looks good.

What does "ifconfig -a" and "ip -4 route show" show in the container?

**Comment by netmoleCBA** [comment]
so far i am notice i cant ping to gateway from container  from host i can ping to gateway

**Comment by netmoleCBA** [comment]
how i can force container another ip and route ?

**Comment by stgraber** [comment]
Can you post that "ifconfig -a" and "ip -4 route show" from inside the container?

**Comment by netmoleCBA** [comment]
default via 192.168.2.1 dev eth0
192.168.2.0/24 dev eth0  proto kernel  scope link  src 192.168.2.30
ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:16:3e:59:b8:f5
          inet addr:192.168.2.30  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::216:3eff:fe59:b8f5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:78198 errors:0 dropped:3 overruns:0 frame:0
          TX packets:47 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:6842322 (6.8 MB)  TX bytes:3486 (3.4 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:22 errors:0 dropped:0 overruns:0 frame:0
          TX packets:22 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:2127 (2.1 KB)  TX bytes:2127 (2.1 KB)

**Comment by netmoleCBA** [comment]
in network we had  three nets  192.168.2.x that serves our dhcp server  192.168.1.x static address and 192.168.100.x reserved for  containers   so i had to force them another adress and route i think

**Comment by netmoleCBA** [comment]
btw i am on irc as well

**Comment by stgraber** [comment]
Ok, so yeah, looks like the problem isn't with the bridging but is with your DHCP server and since that's entirely outside of LXD's control, there's no much I can do about that.

You'll probably want to configure your DHCP server to use your .100.x subnet for containers, either based on their MAC address prefix (00:16:3e) or with static assignments in the DHCP server.

**Comment by netmoleCBA** [comment]
well for me will be great if i can handle during launch to give them adress and route to host

**Comment by netmoleCBA** [comment]
when they have route to host then all shall works

**Comment by netmoleCBA** [comment]
if you can tell me how to give container ip adress and route 
best during launch   it shall be great

**Comment by stgraber** [comment]
There's no way to do that during launch. You can use "lxc init" instead of "lxc launch" and then use "lxc file edit" or "lxc file push" to modify /etc/network/interfaces before starting the container, putting static IP configuration in there instead of DHCP.

**Comment by netmoleCBA** [comment]
so i can do it with edit container  /etc/network/interfaces i guess

**Comment by stgraber** [comment]
"lxc file edit container-name/etc/network/interfaces" will work even if the container isn't running yet, so yeah, you can do "lxc init" to create the container, then edit it, then "lxc start" it.

Or if you need to script it, you can generate your interfaces file and push it in place with "lxc file push".

**Comment by netmoleCBA** [comment]
well i am edited interfaces  then did lxc stop git lxc start git and still old adress

**Comment by stgraber** [comment]
chances are you have a file in /etc/network/interfaces.d/ which overrides whatever you put in /etc/network/interfaces

**Comment by netmoleCBA** [comment]
well final trouble i am set route on  host  but i cant stil connect to anything ever in local network

**Comment by netmoleCBA** [comment]
i cant ping on  any servers  in local network

**Comment by stgraber** [comment]
What did you put in your container's /etc/network/interfaces?

**Comment by netmoleCBA** [comment]
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# Source interfaces
# Please check /etc/network/interfaces.d before changing this file
# as interfaces may have been defined in /etc/network/interfaces.d
# See LP: #1262951
#source /etc/network/interfaces.d/*.cfg

auto eth0
iface eth0 inet static
        address 192.168.100.2
        netmask 255.255.255.0
        network 192.168.100.0
        broadcast 192.168.100.255
        gateway 192.168.100.1
        # dns-* options are implemented by the resolvconf package, if installed
        dns-nameservers 192.168.100.1

i run dns on host

**Comment by netmoleCBA** [comment]
host has gw 192.168.100.247 but i cant ping it from container

**Comment by stgraber** [comment]
You're doing all of this inside VMWare aren't you?

**Comment by stgraber** [comment]
VMWare only allows a single MAC address per virtual machine, which effectively prevents bridging and causes the symptoms you're describing.

I believe there's some kind of option somewhere to turn off this particular feature, but I'm not a VMWare user so I can't help much more.

**Comment by stgraber** [comment]
From some googling, it looks like you'd need to turn the vmware network in "promiscuous" mode and possibly also allow "forged transmits" so that vmware allows multiple MAC addresses to be associated to a single VM.

**Comment by netmoleCBA** [comment]
ok  i try look on it i sent out remarks when i am done it

**Comment by stgraber** [comment]
Any update on this?

**Comment by netmoleCBA** [comment]
i am atm close it as incomplete , some actual duty with high priority , when i am have some result i am reopen this
