### ISSUE TITLE
Apparmor prevents dnsmasq / lxd to work in Ubuntu 16.10

### ISSUE THREAD

**Issue by alci63** [lxc/lxd#2511]
* Distribution: Ubuntu
 * Distribution version: 16.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.8.0-22-generic
   * LXC version: 2.0.5
   * LXD version: 2.4.1
   * Storage backend in use: zfs

# Issue description

After upgrading from 16.04 to 16.10, operations of dnsmasq related to LXD fail when apparmor enforces rules.

audit: type=1400 audit(1476709813.572:4291): apparmor="DENIED" operation="truncate" profile="/usr/sbin/dnsmasq" name="/var/lib/lxd/networks/lxdbr0/dnsmasq.leases" pid=13540 comm="dnsmasq" requested_mask="w" denied_mask="w" fsuid=0 ouid=0

**Comment by stgraber** [comment]
This is an optional apparmor profile which isn't shipped by upstream or enabled by default.

I'd recommend you file a bug against apparmor to get this external profile sorted:
https://launchpad.net/ubuntu/+source/apparmor/+filebug

**Comment by alci63** [comment]
Apparmor bug reported https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1634199

**Comment by stgraber** [comment]
Thanks, I subscribed the LXD team to it so we can get notified of progress there.
