### ISSUE TITLE
recursive file push doesn't intermittently fails and/or does not push the files across

### ISSUE THREAD

**Issue by codersquid** [lxc/lxd#2513]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: xenial
 * Distribution version: xenial
 * The output of "lxc info" or if that fails:

Name: cute-narwhal
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2016/10/17 19:24 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 2013
Ips:
  eth0:	inet	10.0.4.239	vethA8SQP4
  eth0:	inet6	fe80::216:3eff:fefa:152e	vethA8SQP4
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 27
  CPU usage:
    CPU usage (in seconds): 5
  Memory usage:
    Memory (current): 17.87MB
    Memory (peak): 140.66MB
  Network usage:
    eth0:
      Bytes received: 10.74kB
      Bytes sent: 1.34kB
      Packets received: 85
      Packets sent: 11
    lo:
      Bytes received: 288 bytes
      Bytes sent: 288 bytes
      Packets received: 4
      Packets sent: 4

   * Kernel version:
   * LXC version:
   * LXD version:

I needed debug output, so the version I am running is a build I made off of
master today with the addition of spew.Dump in a few places in the client.

```
diff --git a/client.go b/client.go
index 4309cb6..a84f4dd 100644
--- a/client.go
+++ b/client.go
@@ -22,6 +22,7 @@ import (
 	"strings"
 	"syscall"
 
+	"github.com/davecgh/go-spew/spew"
 	"github.com/gorilla/websocket"
 
 	"github.com/lxc/lxd/shared"
@@ -1796,8 +1797,11 @@ func (c *Client) PushFile(container string, p string, gid int, uid int, mode str
 		req.Header.Set("X-LXD-gid", strconv.FormatUint(uint64(gid), 10))
 	}
 
+	spew.Dump(req)
+
 	raw, err := c.Http.Do(req)
 	if err != nil {
+		spew.Dump(err)
 		return err
 	}
 
@@ -1870,6 +1874,7 @@ func (c *Client) RecursivePushFile(container string, source string, target strin
 	}
 
 	sourceDir := filepath.Dir(source)
+	spew.Dump(sourceDir)
 
 	sendFile := func(p string, fInfo os.FileInfo, err error) error {
 		if err != nil {
@@ -1883,6 +1888,8 @@ func (c *Client) RecursivePushFile(container string, source string, target strin
 
 		f, err := os.Open(p)
 		if err != nil {
+			spew.Dump(p)
+			spew.Dump(err)
 			return err
 		}
 		defer f.Close()
```

   * Storage backend in use: zfs

# Issue description

This may be a user error, but here goes. I am trying to make a script to run all of my tests
in a container before a merge is done. The idea is to create an ephemeral container, push my
repo file tree to a tmp dir on the container, and then run a script within the container that
sets up my gopath and runs tests for me.

This is how I ran in to the problem with -p for recursive file pushes. Now I seem to have
a different problem. When I tried to push my entire repo tree, it always failed. I've created
a small script to generate failures (and successes) intermitently in two ways. It can run and
will create the requested number of files in a child directory (because I was testing whether
the number of files correlated with failures).

I don't want to have a huge wall of text here so I've added everything to a gist.

As a workaround I'm going to tar up my repo dir and send one file to the container.

# Steps to reproduce

My gist has a debug-launch script that I was running from a directory I made with
files at the toplevel and in a child directory called exampledir.

https://gist.github.com/codersquid/10c978e0f792f0e59290f0a93a11c3df

# Information to attach

I've attached multiple log files to the gist.

* debug10empty.log shows output from a session that ran with 10 files in the subdir and the outcome was a container with no files in /tmp when there should be.
* debug20fail.log shows output from a session that ran with 20 files in the subdir and had an error due to `DBUG[10-17|14:28:31] Raw response: {"error":"open: No such file or directory\nerrno: 2","error_code":500,"type":"error"}`
* debug5success.log shows a successful interaction.
* tmp.0mkJRggfBn.tgz is a tarball of the tmp dir in case it is helpful.
* narwhalinfo is the output of lxc info for one of the containers. --debug was enampled during the calls to push so you'll see the request sending info across the wire as well.

**Comment by codersquid** [comment]
Oh foo. I also forgot to mention that I have set +x in my bash scripts and when I call the lxc push command from the command line it works. vs. calling within the script.

**Comment by stgraber** [comment]
We had other people run into similar issues before, the most likely reason is your use of /tmp

/tmp is cleared by systemd at boot time, so you're going to race with the init script which does that.
I'd strongly recommend you use ANY path but /tmp in the container :)

**Comment by codersquid** [comment]
I think that's it. I just tried without using /tmp and things worked. :) thanks very kindly!
