### ISSUE TITLE
Live Migration doesn't delete the container at source host sometimes.

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2514]
Ubuntu 16.04.1
lxd 2.4.1
lxc 2.4.1

lxc move cnt dest'nhost:
**error: The container is currently running, stop it first or pass --force.**

the container was migrated to the destination host and was online, however the destination at source wasn't deleted and was stopped, throwing an error message as above.

**Comment by stgraber** [comment]
Hmm, I've never seen that behavior... The error suggests that something started the container while it was being moved, that or LXD failed to stop it and didn't return an error...

@tych0 any idea?

**Comment by stgraber** [comment]
We could certainly have the delete step pass --force which would fix that, but it'd probably be best to figure out the underlying issue :)

**Comment by upuvvad1** [comment]
Name: cnt55
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2016/10/13 15:32 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 12975
Ips:
  eth0:	inet	10.222.1.0	cnt55
  eth0:	inet6	fe80::216:3eff:fe9a:f6d2	cnt55
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 86
  Disk usage:
    root: 152.59MB
  CPU usage:
    CPU usage (in seconds): 9098
  Memory usage:
    Memory (current): 458.81MB
    Memory (peak): 4.44GB
  Network usage:
    eth0:
      Bytes received: 2.85GB
      Bytes sent: 3.14MB
      Packets received: 47315723
      Packets sent: 53786
    lo:
      Bytes received: 0 bytes
      Bytes sent: 0 bytes
      Packets received: 0
      Packets sent: 0


name: cnt55
profiles:
- default
config:
  volatile.base_image: 82e95c482635b5a1f8ca21bdf704a5e58708b9b3f9ef0ecec492e7c1460436a2
  volatile.eth0.hwaddr: 00:16:3e:9a:f6:d2
  volatile.eth0.name: eth0
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    host_name: cnt55
    mtu: "9000"
    nictype: bridged
    parent: br0
    type: nic
  mount-ops:
    path: /var/work/www
    source: /var/work/www
    type: disk
  root:
    path: /
    type: disk
ephemeral: false


Is it because of mount entry ?
Mount entry is available on both the source and dest'n host, at the same location on host machine.

**Comment by upuvvad1** [comment]
And also --force option wasn't defined for move command.

lxc move --help
Usage: Move containers within or in between lxd instances.

lxc move [remote:]<source container> [remote:]<destination container>
    Move a container between two hosts, renaming it if destination name differs.

lxc move <old name> <new name>
    Rename a local container.

Options:

    --debug  (= false)
        Enables debug mode.
    --force-local  (= false)
        Force using the local unix socket.
    --no-alias  (= false)
        Ignore aliases when determining what command to run.
    --verbose  (= false)
        Enables verbose mode.

**Comment by stgraber** [comment]
Yeah, that's normal. The error you're seeing is coming from an internal call to "lxc delete" which does accept that --force option.

**Comment by upuvvad1** [comment]
Is there a clean way which can delete the container at source host when migration was successful ?
Doesn't the API pass the force option to lxc delete, when migration was completed ?

**Comment by stgraber** [comment]
The force option is only necessary if the container is running. Since LXD (well CRIU) stops the container during live migration, this shouldn't be necessary at all.

So that's why the fix for this isn't to just change the code to forcefully destroy the source container, but instead to understand why it was still running at that stage.

**Comment by tych0** [comment]
Did you ^C a previous move command? I've had this happen because the move operation is two distinct steps: a copy and then a delete, and if you ^C the lxc command during the move it doesn't cancel the copy, but also exits and doesn't perform the delete.

**Comment by upuvvad1** [comment]
Kindof.
Does this signal cause any flags to be set in the container config ?
If I am trying to migrate the same container from dest't to source it still throws the same error.
However new containers built with the same config doesn't throw this error.

**Comment by tych0** [comment]
Right now ^C does nothing but exit the client. So the container config is not modified, nor is the migration cancelled.

**Comment by upuvvad1** [comment]
Hmm..may be the container or host issue.. will reopen the issue, if I am able to reproduce again with new container.

**Comment by upuvvad1** [comment]
I tried today with the debug option set, and the output is as follows on the source host.

DBUG[10-18|09:59:36] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"architecture":"x86_64","config":{"volatile.apply_template":"copy","volatile.base_image":"82e95c482635b5a1f8ca21bdf704a5e58708b9b3f9ef0ecec492e7c1460436a2","volatile.eth0.hwaddr":"00:16:3e:bc:a8:99","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]"},"created_at":"2016-10-18T13:58:41Z","devices":{"eth0":{"host_name":"cnt49","mtu":"9000","nictype":"bridged","parent":"br0","type":"nic"},"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"volatile.apply_template":"copy","volatile.base_image":"82e95c482635b5a1f8ca21bdf704a5e58708b9b3f9ef0ecec492e7c1460436a2","volatile.eth0.hwaddr":"00:16:3e:bc:a8:99","volatile.eth0.name":"eth0","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]"},"expanded_devices":{"eth0":{"host_name":"cnt49","mtu":"9000","nictype":"bridged","parent":"br0","type":"nic"},"mount-ops":{"path":"/var/work/www","source":"/var/work/www","type":"disk"},"root":{"path":"/","type":"disk"}},"last_used_at":"2016-10-18T13:58:57.710624122Z","name":"cnt49","profiles":["default"],"stateful":false,"status":"Running","status_code":103}}
 
error: The container is currently running, stop it first or pass --force.

According to @stgraber , the container should be stopped before migrating by CRIU.
Doesn't this sound weird ?

**Comment by tych0** [comment]
Can you post all the of the criu related log files from the dump and restore sides, as well as the lxd.log from both hosts?

**Comment by upuvvad1** [comment]
Source:
**lxd.log:**
t=2016-10-18T10:35:52-0400 lvl=info msg="LXD is starting in normal mode" path=/var/lib/lxd
t=2016-10-18T10:35:52-0400 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
t=2016-10-18T10:35:52-0400 lvl=info msg="Default uid/gid map:"
t=2016-10-18T10:35:52-0400 lvl=info msg=" - u 0 100000 65536"
t=2016-10-18T10:35:52-0400 lvl=info msg=" - g 0 100000 65536"
t=2016-10-18T10:35:52-0400 lvl=info msg="Starting /dev/lxd handler"
t=2016-10-18T10:35:52-0400 lvl=info msg="Expiring log files"
t=2016-10-18T10:35:52-0400 lvl=info msg="Done expiring log files"
t=2016-10-18T10:35:52-0400 lvl=info msg="LXD is socket activated"
t=2016-10-18T10:35:52-0400 lvl=info msg="REST API daemon:"
t=2016-10-18T10:35:52-0400 lvl=info msg="Pruning expired images"
t=2016-10-18T10:35:52-0400 lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket
t=2016-10-18T10:35:52-0400 lvl=info msg="Done pruning expired images"
t=2016-10-18T10:35:52-0400 lvl=info msg=" - binding TCP socket" socket=10.16.11.51:8443
t=2016-10-18T10:35:52-0400 lvl=info msg="Updating images"
t=2016-10-18T10:35:52-0400 lvl=info msg="Done updating images"
t=2016-10-18T10:36:14-0400 lvl=info msg="Migrating container" name=cnt49 created=2016-10-18T14:34:58+0000 ephemeral=false used=2016-10-18T14:35:15+0000 statedir=/tmp/lxd_checkpoint_974989473 actionscript=true stop=true
t=2016-10-18T10:36:24-0400 lvl=eror msg="Error collecting checkpoint log file" err="open /tmp/lxd_checkpoint_974989473/dump.log: no such file or directory"
t=2016-10-18T10:36:24-0400 lvl=info msg="Migrated container" name=cnt49 created=2016-10-18T14:34:58+0000 ephemeral=false used=2016-10-18T14:35:15+0000 statedir=/tmp/lxd_checkpoint_974989473 actionscript=true stop=true


Destination:
**lxd.log:



**
t=2016-10-18T10:35:46-0400 lvl=info msg="LXD is starting in normal mode" path=/var/lib/lxd
t=2016-10-18T10:35:46-0400 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
t=2016-10-18T10:35:46-0400 lvl=info msg="Default uid/gid map:"
t=2016-10-18T10:35:46-0400 lvl=info msg=" - u 0 100000 65536"
t=2016-10-18T10:35:46-0400 lvl=info msg=" - g 0 100000 65536"
t=2016-10-18T10:35:46-0400 lvl=info msg="Starting /dev/lxd handler"
t=2016-10-18T10:35:46-0400 lvl=info msg="Expiring log files"
t=2016-10-18T10:35:46-0400 lvl=info msg="Done expiring log files"
t=2016-10-18T10:35:46-0400 lvl=info msg="LXD is socket activated"
t=2016-10-18T10:35:46-0400 lvl=info msg="Pruning expired images"
t=2016-10-18T10:35:46-0400 lvl=info msg="REST API daemon:"
t=2016-10-18T10:35:46-0400 lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket
t=2016-10-18T10:35:46-0400 lvl=info msg=" - binding TCP socket" socket=10.16.11.50:8443
t=2016-10-18T10:35:46-0400 lvl=info msg="Updating images"
t=2016-10-18T10:35:46-0400 lvl=info msg="Done pruning expired images"
t=2016-10-18T10:35:46-0400 lvl=info msg="Done updating images"
t=2016-10-18T10:36:00-0400 lvl=info msg="Deleting container" name=cnt49 created=2016-10-18T14:33:21+0000 ephemeral=false used=2016-10-18T14:33:37+0000
t=2016-10-18T10:36:01-0400 lvl=info msg="Deleted container" name=cnt49 created=2016-10-18T14:33:21+0000 ephemeral=false used=2016-10-18T14:33:37+0000
t=2016-10-18T10:36:22-0400 lvl=info msg="Migrating container" ephemeral=false used=1970-01-01T00:00:00+0000 statedir=/tmp/lxd_restore_082454632 actionscript=false stop=false name=cnt49 created=2016-10-18T14:36:06+0000
t=2016-10-18T10:36:24-0400 lvl=info msg="Migrated container" stop=false name=cnt49 create
t=2016-10-18T10:35:46-0400 lvl=info msg="LXD is starting in normal mode" path=/var/lib/lxd
t=2016-10-18T10:35:46-0400 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
t=2016-10-18T10:35:46-0400 lvl=info msg="Default uid/gid map:"
t=2016-10-18T10:35:46-0400 lvl=info msg=" - u 0 100000 65536"
t=2016-10-18T10:35:46-0400 lvl=info msg=" - g 0 100000 65536"
t=2016-10-18T10:35:46-0400 lvl=info msg="Starting /dev/lxd handler"
t=2016-10-18T10:35:46-0400 lvl=info msg="Expiring log files"
t=2016-10-18T10:35:46-0400 lvl=info msg="Done expiring log files"
t=2016-10-18T10:35:46-0400 lvl=info msg="LXD is socket activated"
t=2016-10-18T10:35:46-0400 lvl=info msg="Pruning expired images"
t=2016-10-18T10:35:46-0400 lvl=info msg="REST API daemon:"
t=2016-10-18T10:35:46-0400 lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket
t=2016-10-18T10:35:46-0400 lvl=info msg=" - binding TCP socket" socket=10.16.11.50:8443
t=2016-10-18T10:35:46-0400 lvl=info msg="Updating images"
t=2016-10-18T10:35:46-0400 lvl=info msg="Done pruning expired images"
t=2016-10-18T10:35:46-0400 lvl=info msg="Done updating images"
t=2016-10-18T10:36:00-0400 lvl=info msg="Deleting container" name=cnt49 created=2016-10-18T14:33:21+0000 ephemeral=false used=2016-10-18T14:33:37+0000
t=2016-10-18T10:36:01-0400 lvl=info msg="Deleted container" name=cnt49 created=2016-10-18T14:33:21+0000 ephemeral=false used=2016-10-18T14:33:37+0000
t=2016-10-18T10:36:22-0400 lvl=info msg="Migrating container" ephemeral=false used=1970-01-01T00:00:00+0000 statedir=/tmp/lxd_restore_082454632 actionscript=false stop=false name=cnt49 created=2016-10-18T14:36:06+0000
t=2016-10-18T10:36:24-0400 lvl=info msg="Migrated container" stop=false name=cnt49 created=2016-10-18T14:36:06+0000 ephemeral=false used=1970-01-01T00:00:00+0000 statedir=/tmp/lxd_restore_082454632 actionscript=false

[DST_migration_restore_2016-10-18T10:36:24-04:00.txt](https://github.com/lxc/lxd/files/536548/DST_migration_restore_2016-10-18T10.36.24-04.00.txt)

d=2016-10-18T14:36:06+0000 ephemeral=false used=1970-01-01T00:00:00+0000 
[SRC_lxc.txt](https://github.com/lxc/lxd/files/536544/SRC_lxc.txt)
[SRC_migration_restore_2016-10-18T10:35:16-04:00.txt](https://github.com/lxc/lxd/files/536543/SRC_migration_restore_2016-10-18T10.35.16-04.00.txt)

statedir=/tmp/lxd_restore_082454632 actionscript=false

**Comment by tych0** [comment]
So you posted restore logs from both, when the source should have a dump log. I think it doesn't because of the race fixed in #2512, but anyway it doesn't look like the dump failed based on your logs, just the log collection failed.

One interesting thing is this in your logs:

```
        lxc 20161018100641.644 INFO     lxc_criu - criu.c:exec_criu:419 - execing: /usr/local/sbin/criu dump --tcp-established --file-locks --link-remap --manage-cgroups=full --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /tmp/lxd_checkpoint_016406657 -o /tmp/lxd_checkpoint_016406657/dump.log -vvvvvv --action-script /tmp/lxd_checkpoint_016406657/action.sh -t 9573 --skip-in-flight --freeze-cgroup /sys/fs/cgroup/freezer///lxc/cnt49 --ext-mount-map /dev/console:console --external tty[8800:e] --ghost-limit 268435456 
        lxc 20161018100650.501 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
        lxc 20161018100650.501 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536
        lxc 20161018100650.504 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
        lxc 20161018100650.504 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
        lxc 20161018100650.504 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'cnt49' is in 'RUNNING' state
        lxc 20161018100651.130 DEBUG    lxc_start - start.c:signal_handler:342 - container init process exited
```

I wonder if there's not some similar race to what happened in #2512 that I'm missing.

**Comment by upuvvad1** [comment]
Any thoughts on why the container is not being deleted at source by looking at the logs ?

**Comment by tych0** [comment]
Yes, see the above comment :)
