### ISSUE TITLE
lxc copy do not change hostname on Debian Jessie

### ISSUE THREAD

**Issue by x86fantini** [lxc/lxd#2518]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu 16.04 LTS 
 * Distribution version: 
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-43-generic
   * LXC version: 2.0.4
   * LXD version: 2.0.4
   * Storage backend in use: ZFS

# Issue description

I have downloaded and imported latest Jessie image with command:
lxc image copy images:47327c631673 local: --alias deb8 --auto-update

i have started a new container named "jessienew"
lxc launch deb8 jessienew

then i have copied this conteiner into jessienew2
lxc copy jessienew jessienew2 

i have echoed the hostname of first jessie container
root@simone-ThinkPad-T440:~# lxc exec jessienew -- hostname
jessienew

i have then started "jessienew2" and echoed the hostname
root@simone-ThinkPad-T440:~# lxc exec jessienew2 -- hostname
jessienew

leaving apart the fact that still i can not stop the Jessie container gracefully (it freee during stop command and only a "-f" stop it..)...this procedure with Ubuntu it's working nice. really do not undertand why there is no love for Debian :(

root@simone-ThinkPad-T440:~# lxc exec ubuntu -- hostname
ubuntu
root@simone-ThinkPad-T440:~# lxc copy ubuntu ubuntu2
root@simone-ThinkPad-T440:~# lxc start ubuntu2
root@simone-ThinkPad-T440:~# lxc exec ubuntu2 -- hostname
ubuntu2

**Comment by stgraber** [comment]
Thanks for the report. I've changed the image build script to fix the embedded template, the Debian image should pick up that change in the next 48 hours. For containers that were created from an older image, you'll need to manually change /etc/hostname and /etc/hosts.

As for the shutdown issue, that's because Debian's systemd is broken and segfaults on shutdown.

```
Oct 18 06:11:45 debian systemd[1]: Assertion 'sd_id128_randomize(&id) >= 0' failed at ../src/core/dbus.c:688, function bus_on_connection(). Aborting.
Oct 18 06:11:46 debian systemd[1]: Caught <ABRT>, dumped core as pid 202.
```

**Comment by x86fantini** [comment]
thank you for the quick update & fix.
regards
S
