### ISSUE TITLE
Snapshot Restore Destroys (?) Data

### ISSUE THREAD

**Issue by roblaus** [lxc/lxd#2520]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info"
    architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-43-generic
  server: lxd
  serverpid: 2461
  serverversion: 2.0.4
  storage: zfs
  storageversion: "5"

# Issue description
I am running a php/js web application on a standard LAMP Stack (php5.6, everything else from the 16.04 repos) as LXD/LXC container. 

I create a stateless snapshot from this running container, make some minimal changes within the application, close the application, restore the snapshot and my application doesn't start anymore with a 500 error.

Further investigation reveals that the config.php which contains the application's database connection parameters as well as other app specific settings is incomplete - there are always roughly 20 bytes cut off at the end which of course causes php to throw an error.  Other damages aren't visible but I will run a diff if required.

I am pretty sure that this is cache related but I have no idea where to look or what to do (I am not a developer). 
Even more so since my whole backup strategy is snapshot / image based and I am not sure which of my backups are ok and which not. I am currently running almost 20 containers some of which hold customer data.

**Comment by tych0** [comment]
Does your application read and then write config.php on every request? I suspect what's happening is that you're somehow snapshotting an incomplete write of config.php which the server since it's running hasn't finished yet.

I think a bug in the underlying snapshot mechanism is unlikely given that you're using ZFS. If you snapshot the container while it's stopped, does it have this problem?

**Comment by roblaus** [comment]
Not sure really about the r/w processes but I have forwarded the question to the authors of the SW since they should know precisely. 
And I do not believe that the snapshot is the culprit since restoring one and the same snapshot once works well, next time it doesn't. It seems that restoring the snapshot somehow interferes with a write process which is delayed due to some caching issues.
And please don't laugh now: I even saw some 'self healing' - I had the above mentioned effect, left the machine for a couple of minutes alone and all of a sudden it worked.
I took snapshots from a stopped container and I didn't notice anything strange. But stopping a container in order to take a snapshot defies the purpose...

**Comment by roblaus** [comment]
I can confirm that it is NOT the snapshot that causes the problem. 
I closed the app, restored the snapshot - config.php damaged
I repaired the file, stopped the container, restored the snapshot - all fine...

And since the there is a label 'incomplete' - what other information do you require?

**Comment by tych0** [comment]
I don't think we need any other information, as I don't think there's really a bug here. Taking a snapshot will snapshot exactly what's on the FS at the time, and it's up to users to make sure what's on the FS is what they want to take a snapshot of.

We have stateful snapshots if your app can't coordinate it's writes, but there's not a lot else LXD can do.
