### ISSUE TITLE
gpu device type

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#2524]
We want users to be able to hotplug a GPU which immediately is made available in the container. The biggest hurdle I currently see with this is how to correctly identify the GPU that is supposed to be
passed through. There are multiple issues.

- Assume that you have two graphics cards both with the same vendor and product
   id.
   - Should we allow users to specify a vendor ID and make all GPUs matching
     that vendor available in the container?
   - Even if the user specifies vendor id and product id it might still match
     multiple GPUs (As can e.g. be seen on our canonical-lxd host.) and we would
     therefore make them all available in the container.
- I couldn't test GPU hotplug directly so far to check what entries netlink
   kobjects will actually give us. But from my research on the internet it's not
   a lot and it's not a vendor or product id.
-  One possibility is to have users give us a slot, that means the first field in
   the output of lspci -nn. This is unique and if I'm right, netlink kobjects
   will actually send this information back in ID_PATH.
   So a user would retrieve:
```
ubuntu@canonical-lxd:~$ lspci -nn | grep -i nvidia
02:06.0 VGA compatible controller [0300]: NVIDIA Corporation GK208 [GeForce GT 730] [10de:1287] (rev a1)
02:07.0 Audio device [0403]: NVIDIA Corporation GK208 HDMI/DP Audio Controller [10de:0e0f] (rev a1)
02:08.0 VGA compatible controller [0300]: NVIDIA Corporation GK208 [GeForce GT 730] [10de:1287] (rev a1)
02:09.0 Audio device [0403]: NVIDIA Corporation GK208 HDMI/DP Audio Controller [10de:0e0f] (rev a1)
```

and decides to give the container
```
02:08.0
```

then netlink would provide us with:
```
ubuntu@canonical-lxd:~$ udevadm info /dev/dri/card1
P: /devices/pci0000:00/0000:00:1e.0/0000:01:01.0/0000:02:08.0/drm/card1
N: dri/card1
E: DEVNAME=/dev/dri/card1
E: DEVPATH=/devices/pci0000:00/0000:00:1e.0/0000:01:01.0/0000:02:08.0/drm/card1
E: DEVTYPE=drm_minor
E: ID_FOR_SEAT=drm-pci-0000_02_08_0
E: ID_PATH=pci-0000:02:08.0
E: ID_PATH_TAG=pci-0000_02_08_0
E: MAJOR=226
E: MINOR=1
E: SUBSYSTEM=drm
E: TAGS=:master-of-seat:seat:uaccess:
E: USEC_INITIALIZED=46084911
```

and we could parse `ID_PATH=-pci-0000:02:08.0`

and check whether Substring(02:08.0, ID_PATH) == true

- Another possibility is that users give us the name of the card directly. So
   they would give us
```
card1
```
   and we would check again Substring(DEVNAME, card1) == true

- An additional thing to think about is whether we want stuff like
```
/dev/dri/controlD64
/dev/dri/renderD128
```
   to be created in the container as well. I think they are running numbers just
   like the cards starting at 64 and 128 respectively. So
```
/dev/dri/controlD64
```
   and
```
/dev/dri/renderD128
```
would belong to
```
/dev/dri/card0
```
   and
```
/dev/dri/controlD65
/dev/dri/renderD129
```
   to
```
/dev/dri/renderD129
```

**Comment by stgraber** [comment]
Ok, so I'd say:
 - Lets ignore PCI hotplug. It's not a common case at all (vs USB where it is). So lets just assume that the GPU is there at the time the container starts or at the time where we add the device to the container. If it's not, we'll just fail.
 - The main target for this feature is CUDA (for NVidia) and OpenCL (for everything else). That's what we should be testing with. So we'll need to pass /dev/nvidiaX for nvidia cards and the relevant /dev/dri entries for OpenCL (and probably for NVidia) too.

For the user experience, I'd say we'd want something like:
 - lxc config device add c1 gpu0 gpu => Pass everything we have
 - lxc config device add c1 gpu0 gpu vendor=nvidia => Pass whatever we have from nvidia
 - lxc config device add c1 gpu0 gpu vendor=nvidia id=1 => Pass the second nvidia GPU
 - lxc config device add c1 gpu0 gpu pci=0000:02:08.0 => Pass whatever GPU is at that PCI address

**Comment by Roszko** [comment]
From looking at this discussion, the gpu device type will be available in lxd version 2.5 / 2.6? When are these scheduled to be released?

Is there a way to do PCIe passthrough in LXD without the gpu device type?

I recognise that cgroups can be used however that requires installing drivers in the host which tends to become messy (as drivers need to also be installed in the container). I assume that PCIe passthrough as used in the gpu device avoids doubling up the drivers as the device is only available in the container?

**Comment by stgraber** [comment]
LXD 2.5 and 2.6 have been released quite a while ago, the next release is 2.7 to be released next Tuesday.

And no, there's no generic PCIe passthrough possible through LXD as even if the kernel would make that possible, it still wouldn't do very much to you since you can't install kernel modules on a per container basis.

A shared kernel with the host is the very definition of what a container is. So all kernel modules must be installed on the host.

**Comment by stgraber** [comment]
And yes, the GPU passthrough assumes the drivers are installed on the host and will just configure cgroups and device nodes entries for whatever card you want to access from the container.

**Comment by dnshs** [comment]
> And no, there's no generic PCIe passthrough possible through LXD as even if the kernel would make that possible, it still wouldn't do very much to you since you can't install kernel modules on a per container basis.


What about network devices using DPDK ?

**Comment by stgraber** [comment]
I've not played with DPDK network devices personally and am unsure what kind of interface is used for userspace to communicate with the DPDK kernel driver.

I seem to remember reading that in one mode at least, this was done through a char device in /dev, which would make it suitable for a unix-char device in LXD, with the network interface itself behaving like a normal interface that can be moved to the container using the "physical" network interface type.
