### ISSUE TITLE
Idea: Simple Data Volume for unprivileged containers

### ISSUE THREAD

**Issue by wtayyeb** [lxc/lxd#2526]
every one knows that currently storage management in LXD for unprivileged container is not clear and in better way needs `setfacl ...`

here my story to handle it in very simple way. may help someone.

NOTE: this recipe is based on default behaviour of lxd that use same uid for all containers on each host. and may break if container moved across hosts.
for resolve this if occure, make sure the uid range for lxd user/group in `/etc/subuid` and `/etc/subgid` are same before creating containers.

1 . create an empty container that will hold the data. name it `c0`
`lxc launch ubuntu c0`
`lxc exec c0 -- mkdir /data-vol/vol1/`
2 . now we assume have `c1` that need a data volume
```
lxc config device add c1 vol1 disk \
    source=/var/lib/lxd/containers/c0/rootfs/data-vol/vol1/ \
    path=/srv/vol1/
```
3 . as the uid in `c0` and `c1` are same, `c1` can write to it without any effort.
`lxc exec c1 -- touch /srv/vol1/hello-from-c1`
4 . and to see the changes
`lxc exec c0 -- ls /data-vol/vol1/`
`> hello-from-c1`

**Comment by wtayyeb** [comment]
it may interested for these issues
#2005 
#2025 
#2242

**Comment by stgraber** [comment]
So I'm a bit confused, this issue doesn't seem to be describing an issue so much as telling people how to share data between containers with current LXD.

Is there an actual problem I'm missing?

And yes, this is all pretty fragile as we will eventually be using different ranges per container which will break this kind of trick. But hopefully by then we'll have an in-kernel mapping filesystem that we can use to bind-mount + remap filesystems without having to alter the source.

**Comment by wtayyeb** [comment]
yes, just tell others.

I have try several ways for this in about two weeks and very tired of clean sharing. finally and temporarily  use this until your great work in in-kernel stuff released, so then migrate to it.

**Comment by stgraber** [comment]
Alright, closing this then. Closed issues are usually pretty well indexed so people should find this pretty easily.
