### ISSUE TITLE
extremely slow memory reclaiming from linux file cache

### ISSUE THREAD

**Issue by davereiner** [lxc/lxd#2530]
As we add more and more containers to the same host machine the memory reclaiming process of Linux gets slower and slower; at around 100 containers (processes in total taking up ~50GB RAM, with 50GB more free) it becomes really hard to work with, if there's a sudden need to allocate memory to new processes system CPU usage shoots through the roof and the whole system hangs for a couple of seconds. This is the case with ZFS and Btrfs too. The VM is a 16 CPU instance on Google Cloud. Tuning parameters like vm.vfs_cache_pressure don't help much.
Any suggestions? Is this an expected behavior?

The below is after clearing file cache with `echo 1 > /proc/sys/vm/drop_caches`

cat /proc/meminfo

```
MemTotal:       107263244 kB
MemFree:        21238804 kB
MemAvailable:   42437400 kB
Buffers:            6320 kB
Cached:         24364556 kB
SwapCached:            0 kB
Active:         59870944 kB
Inactive:       11462216 kB
Active(anon):   48356452 kB
Inactive(anon):  4496536 kB
Active(file):   11514492 kB
Inactive(file):  6965680 kB
Unevictable:        3632 kB
Mlocked:            3648 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:             22124 kB
Writeback:             0 kB
AnonPages:      46966116 kB
Mapped:         14092644 kB
Shmem:           5887628 kB
Slab:           12572612 kB
SReclaimable:    3772920 kB
SUnreclaim:      8799692 kB
KernelStack:      224704 kB
PageTables:       934316 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    53631620 kB
Committed_AS:   392345188 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:  32579584 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:     2074612 kB
DirectMap2M:    99637248 kB
DirectMap1G:     9437184 kB
```

**Comment by stgraber** [comment]
So LXD itself doesn't really have an impact on any of that.

So just to clarify things:
 - Was that /proc/meminfo inside a container or on the host? (to check if lxcfs has a hand in that)
 - What kernel are you running?

So dropping the caches certainly doesn't reset the value to 0, even on a system that's not using containers here, the question is what's the source of those entries and how to clean them up.

**Comment by davidfavor** [comment]
Just checked this on a heavily used machine (3-4 million pageviews/day).

Physical machine w/16 cores running a dozen containers.

Memory reclamation ran in <10 seconds.
```
net10 # cat /proc/meminfo | egrep -e Buffers -e Cached
Buffers:         4087112 kB
Cached:         90519456 kB
SwapCached:       188236 kB

net10 # echo 1 > /proc/sys/vm/drop_caches   <- this took <10 seconds

net10 # cat /proc/meminfo | egrep -e Buffers -e Cached
Buffers:           10480 kB
Cached:          1565364 kB
SwapCached:       188240 kB
```
Maybe this relates to the VM environment where LXC containers are hosted.
