### ISSUE TITLE
lxc remote list not able to pick the config file when application run as systemd service

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2531]
lxd 2.4.1
lxc 2.4.1
Ubuntu 16.04.1
compiled from master branch source code.

When a c application is running as systemd service, which in turn calls lxc remote list, was not able to retrieve the values from service user's home directory (in this case should read from root, since service run as sudo).
Instead, lxc searches for config in the " / " path for config files.

```
#include <unistd.h>
#include <stdio.h>
#include <sys/wait.h>

int main(){
	pid_t pid;
	if((pid = fork()) != -1){
		if(pid == 0)
			execl("/usr/bin/lxc","/usr/bin/lxc","remote","list",(char *) NULL);
		else
			waitpid(pid,NULL,0);
	}
	return 0;
}


```

**Comment by tych0** [comment]
The CLI searches in either `$LXD_CONF` or `$HOME/.config/lxc`; export one of those and it should behave as expected. In your case, you probably want to export `HOME=/root`.

**Comment by upuvvad1** [comment]
I do have that in environment variable list.
If either of these is not found, does lxc list return an error ?
Because it returns basic remotes,
images,local,ubuntu,ubuntu-daily.

and also copying .config from home directory to "/" does work as expected.

**Comment by upuvvad1** [comment]
My bad..
Didn't pass environment variable to service.
