### ISSUE TITLE
 lxd client.go is way too verbose

### ISSUE THREAD

**Issue by anastasiamac** [lxc/lxd#2532]
As per https://bugs.launchpad.net/juju/+bug/1635017, is it possible to lower debug to Trace level?

**Comment by stgraber** [comment]
The logging code we use in LXD itself doesn't have a TRACE level. The fact that you're getting those in Juju seems to indicate that you're registering a log handler in the juju code.

If you don't want LXD debug output to make it to your logs, just don't register a handler for the Debug output.

Looks like the offending part of the juju code is: https://github.com/juju/juju/blob/staging/tools/lxdclient/client.go#L67

Closing this issue as LXD's logging is consistent, it just doesn't match the log levels of Juju and the way to fix this is to change the log handler that Juju registers.

**Comment by stgraber** [comment]
Tried to comment in the Launchpad issue but I can't re-open it and Launchpad times out when commenting, so would be great if you could take care of that.

**Comment by anastasiamac** [comment]
Thanks, Stephane \o/
I'll update Juju issue.
