### ISSUE TITLE
AppVeyor config is missing

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2537]
There is no config for https://ci.appveyor.com/project/lxc/lxd/history in repository, so it is impossible to propose enhancement for CI script,

**Comment by stgraber** [comment]
Until appveyor allows for the config file to be a hidden file, that's how it's going to be. I don't want a visible appveyor.yaml file, .appveyor.yaml would be fine.

**Comment by stgraber** [comment]
```version: '{branch}.{build}'
image: Visual Studio 2015
clone_folder: c:\gopath\src\github.com\lxc\lxd
environment:
  GOPATH: c:\gopath
install:
- cmd: >-
    echo %PATH%

    echo %GOPATH%

    set PATH=%GOPATH%\bin;c:\go\bin;%PATH%

    go version

    go env
build_script:
- cmd: >-
    go get -t -v -d ./...

    go install -v ./lxc
test_script:
- cmd: >-
    cd c:\gopath\src\github.com\lxc\lxd

    go test ./

    go test ./shared

    go test ./lxc
```

Is the current config

**Comment by techtonik** [comment]
@stgraber it allows even to move `appveyor.yml` away - http://help.appveyor.com/discussions/problems/2463-can-a-custom-configuration-yml-file-name-exist-in-a-sub-directory but `appveyor.yml` is only supported for repositories that are linked with GitHub - https://github.com/appveyor/ci/issues/545

**Comment by stgraber** [comment]
Oh, must have missed that setting, so yeah, we can add it to git then.
