### ISSUE TITLE
uid/gid (65534:65534) issue after using security.privileged

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#2539]
After using security.privileged: "true" and removing it, the container has issue, all files are owned to nobody:nogroup:

root@dnxovh-hy002 (node2):~# lxc list
+-------------+---------+-----------------------+------+------------+-----------+
|    NAME     |  STATE  |         IPV4          | IPV6 |    TYPE    | SNAPSHOTS |
+-------------+---------+-----------------------+------+------------+-----------+
| testnico001 | RUNNING | 192.168.10.227 (eth0) |      | PERSISTENT | 0         |
+-------------+---------+-----------------------+------+------------+-----------+
root@dnxovh-hy002 (node2):~# lxc exec testnico001 bash
bash: /root/.bashrc: Permission denied
root@testnico001:/# ls -la
total 35
drwxr-xr-x  22 nobody nogroup  22 Oct 20 13:07 .
drwxr-xr-x  22 nobody nogroup  22 Oct 20 13:07 ..
drwxr-xr-x   2 nobody nogroup 173 Oct 13 16:52 bin
drwxr-xr-x   3 nobody nogroup   3 Oct 13 16:53 boot
drwxr-xr-x   9 root   root    500 Oct 20 16:49 dev
drwxr-xr-x  90 nobody nogroup 179 Oct 20 12:58 etc
drwxr-xr-x   3 nobody nogroup   3 Oct 20 12:58 home
drwxr-xr-x  20 nobody nogroup  23 Oct 13 16:53 lib
drwxr-xr-x   2 nobody nogroup   3 Oct 13 16:49 lib64
drwxr-xr-x   2 nobody nogroup   2 Oct 13 16:49 media
drwxr-xr-x   2 nobody nogroup   2 Oct 13 16:49 mnt
drwxr-xr-x   2 nobody nogroup   2 Oct 13 16:49 opt
dr-xr-xr-x 662 nobody nogroup   0 Oct 20 16:49 proc
drwx------   4 nobody nogroup   7 Oct 20 16:18 root
drwxr-xr-x  18 root   root    660 Oct 20 16:49 run
drwxr-xr-x   2 nobody nogroup 226 Oct 13 16:52 sbin
drwxr-xr-x   2 nobody nogroup   2 Sep 21 17:12 snap
drwxr-xr-x   2 nobody nogroup   2 Oct 13 16:49 srv
dr-xr-xr-x  13 nobody nogroup   0 Oct 20 16:26 sys
drwxrwxrwt   7 root   root      7 Oct 20 16:49 tmp
drwxr-xr-x  10 nobody nogroup  10 Oct 13 16:49 usr
drwxr-xr-x  13 nobody nogroup  15 Oct 13 16:52 var
root@testnico001:/#

INFO:

root@dnxovh-hy002 (node2):~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

root@dnxovh-hy002 (node2):~# lxc info
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
  apistatus: stable
  apiversion: "1.0"
  auth: trusted
  environment:
  addresses:
  - 10.0.0.2:8443
    architectures:
  - x86_64
  - i686
    certificate: |
    [...]
    certificatefingerprint: e3de5a63659185ba9c320bfd9778ec5515649dd5a023c1424b2745b2ffe48d0b
    driver: lxc
    driverversion: 2.0.5
    kernel: Linux
    kernelarchitecture: x86_64
    kernelversion: 4.4.0-43-generic
    server: lxd
    serverpid: 25247
    serverversion: 2.4.1
    storage: zfs
    storageversion: "5"
    config:
    core.https_address: 10.0.0.2:8443
    core.trust_password: true
    storage.zfs_pool_name: zdata/lxd
    public: false

To reproduce:
1. create container with default profile
2. lxc config set testnico001  security.privileged true
3. all good
4. lxc config edit testnico001 and remove the security.privileged line
5. log to container, all are owned to 65534:65534

Any help are welcome.

Thanks

**Comment by stgraber** [comment]
You'll have to be a bit more specific because I can't reproduce this:

```
stgraber@castiana:~$ lxc launch ubuntu:16.04 test
Creating test
Starting test
stgraber@castiana:~$ lxc config show test
name: test
profiles:
- default
config:
  volatile.base_image: 6f25adef061c3f2186c6910bff8cacd0c63e1493e3f8b616e52eb84076890bd1
  volatile.eth0.hwaddr: 00:16:3e:87:78:be
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
ephemeral: false
stgraber@castiana:~$ lxc exec test -- ls -lh /
total 56K
drwxr-xr-x    2 root   root    173 Oct 13 16:52 bin
drwxr-xr-x    3 root   root      3 Oct 13 16:53 boot
drwxr-xr-x    9 root   root    500 Oct 20 17:07 dev
drwxr-xr-x   90 root   root    175 Oct 20 17:07 etc
drwxr-xr-x    2 root   root      2 Apr 12  2016 home
drwxr-xr-x   20 root   root     23 Oct 13 16:53 lib
drwxr-xr-x    2 root   root      3 Oct 13 16:49 lib64
drwxr-xr-x    2 root   root      2 Oct 13 16:49 media
drwxr-xr-x    2 root   root      2 Oct 13 16:49 mnt
drwxr-xr-x    2 root   root      2 Oct 13 16:49 opt
dr-xr-xr-x 1299 nobody nogroup   0 Oct 20 17:07 proc
drwx------    2 root   root      4 Oct 13 16:52 root
drwxr-xr-x   18 root   root    660 Oct 20 17:07 run
drwxr-xr-x    2 root   root    226 Oct 13 16:52 sbin
drwxr-xr-x    2 root   root      2 Sep 21 17:12 snap
drwxr-xr-x    2 root   root      2 Oct 13 16:49 srv
dr-xr-xr-x   13 nobody nogroup   0 Oct 20 17:05 sys
drwxrwxrwt    7 root   root      7 Oct 20 17:07 tmp
drwxr-xr-x   10 root   root     10 Oct 13 16:49 usr
drwxr-xr-x   13 root   root     15 Oct 13 16:52 var
stgraber@castiana:~$

stgraber@castiana:~$ lxc config set test security.privileged true
stgraber@castiana:~$ lxc config show test
name: test
profiles:
- default
config:
  security.privileged: "true"
  volatile.base_image: 6f25adef061c3f2186c6910bff8cacd0c63e1493e3f8b616e52eb84076890bd1
  volatile.eth0.hwaddr: 00:16:3e:87:78:be
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
ephemeral: false
stgraber@castiana:~$ lxc exec test -- ls -lh /
total 56K
drwxr-xr-x    2 root   root    173 Oct 13 16:52 bin
drwxr-xr-x    3 root   root      3 Oct 13 16:53 boot
drwxr-xr-x    9 root   root    500 Oct 20 17:07 dev
drwxr-xr-x   90 root   root    179 Oct 20 17:07 etc
drwxr-xr-x    3 root   root      3 Oct 20 17:07 home
drwxr-xr-x   20 root   root     23 Oct 13 16:53 lib
drwxr-xr-x    2 root   root      3 Oct 13 16:49 lib64
drwxr-xr-x    2 root   root      2 Oct 13 16:49 media
drwxr-xr-x    2 root   root      2 Oct 13 16:49 mnt
drwxr-xr-x    2 root   root      2 Oct 13 16:49 opt
dr-xr-xr-x 1294 nobody nogroup   0 Oct 20 17:07 proc
drwx------    3 root   root      5 Oct 20 17:07 root
drwxr-xr-x   18 root   root    680 Oct 20 17:07 run
drwxr-xr-x    2 root   root    226 Oct 13 16:52 sbin
drwxr-xr-x    2 root   root      2 Sep 21 17:12 snap
drwxr-xr-x    2 root   root      2 Oct 13 16:49 srv
dr-xr-xr-x   13 nobody nogroup   0 Oct 20 17:05 sys
drwxrwxrwt    7 root   root      7 Oct 20 17:07 tmp
drwxr-xr-x   10 root   root     10 Oct 13 16:49 usr
drwxr-xr-x   13 root   root     15 Oct 13 16:52 var
stgraber@castiana:~$


stgraber@castiana:~$ lxc config edit test
stgraber@castiana:~$ lxc config show test
name: test
profiles:
- default
config:
  volatile.base_image: 6f25adef061c3f2186c6910bff8cacd0c63e1493e3f8b616e52eb84076890bd1
  volatile.eth0.hwaddr: 00:16:3e:87:78:be
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
ephemeral: false
stgraber@castiana:~$ lxc exec test -- ls -lh /
total 56K
drwxr-xr-x    2 root   root    173 Oct 13 16:52 bin
drwxr-xr-x    3 root   root      3 Oct 13 16:53 boot
drwxr-xr-x    9 root   root    500 Oct 20 17:07 dev
drwxr-xr-x   90 root   root    179 Oct 20 17:07 etc
drwxr-xr-x    3 root   root      3 Oct 20 17:07 home
drwxr-xr-x   20 root   root     23 Oct 13 16:53 lib
drwxr-xr-x    2 root   root      3 Oct 13 16:49 lib64
drwxr-xr-x    2 root   root      2 Oct 13 16:49 media
drwxr-xr-x    2 root   root      2 Oct 13 16:49 mnt
drwxr-xr-x    2 root   root      2 Oct 13 16:49 opt
dr-xr-xr-x 1293 nobody nogroup   0 Oct 20 17:07 proc
drwx------    3 root   root      5 Oct 20 17:07 root
drwxr-xr-x   18 root   root    680 Oct 20 17:07 run
drwxr-xr-x    2 root   root    226 Oct 13 16:52 sbin
drwxr-xr-x    2 root   root      2 Sep 21 17:12 snap
drwxr-xr-x    2 root   root      2 Oct 13 16:49 srv
dr-xr-xr-x   13 nobody nogroup   0 Oct 20 17:05 sys
drwxrwxrwt    7 root   root      7 Oct 20 17:07 tmp
drwxr-xr-x   10 root   root     10 Oct 13 16:49 usr
drwxr-xr-x   13 root   root     15 Oct 13 16:52 var
stgraber@castiana:~$
```

**Comment by nlienard** [comment]
Strange i 'm trying to reproduce but i can't for now.
in fact, i had this issue during live migration test. it was always failing.
but when i began to add "security.privileged true", it was beginning to work.
But right now, it doesn't anymore; i m totally puzzled.

root@dnxovh-hy001 (node1):~# lxc move test node2:
error: Error transferring container data: migration restore failed
(00.014395) Warn  (cr-restore.c:1159): Set CLONE_PARENT | CLONE_NEWPID but it might cause restore problem,because not all kernels support such clone flags combinations!
(00.030318)      1: Error (image.c:318): Unable to open netns-9.img: Permission denied
(00.046326) Error (cr-restore.c:1352): 25401 killed by signal 9
(00.086636) Error (cr-restore.c:2182): Restoring FAILED.

root@dnxovh-hy001 (node1):~# lxc config show test
name: test
profiles:
- default
config:
  security.privileged: "true"
  volatile.base_image: 6f25adef061c3f2186c6910bff8cacd0c63e1493e3f8b616e52eb84076890bd1
  volatile.eth0.hwaddr: 00:16:3e:60:d9:0e
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
devices:
  root:
    path: /
    type: disk
ephemeral: false

root@dnxovh-hy001 (node1):~# lxc profile show default
name: default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br_lan10
    type: nic
usedby:
- /1.0/containers/inxovh-db001
- /1.0/containers/inxovh-db002
- /1.0/containers/inxovh-db003
- /1.0/containers/inxovh-ws001
- /1.0/containers/inxovh-xmpp001
- /1.0/containers/test


root@dnxovh-hy002 (node2):~# lxc profile show default
name: default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br_lan10
    type: nic
usedby:
- /1.0/containers/testnico001

**Comment by stgraber** [comment]
@tych0

**Comment by tych0** [comment]
Have you rebooted the container to make sure it's actually privileged? It looks to me like you're checkpointing a container that's still unprivileged while LXD thinks it is privileged, which won't work.

**Comment by nlienard** [comment]
I didn't. i did these modification while the container was RUNNING.
So you mean it was a bad idea.

I just stoped it and added back the privileged parameter and now it looks good:

root@dnxovh-hy001 (node1):/srv/local/images# lxc exec testnico001 bash
root@testnico001:~# ls -la
total 9
drwx------  4 root root    7 Oct 20 16:18 .
drwxr-xr-x 22 root root   22 Oct 20 21:58 ..
-rw-------  1 root root   16 Oct 20 20:38 .bash_history
-rw-r--r--  1 root root 3106 Oct 22  2015 .bashrc
drwxr-x---  3 root root    3 Oct 20 16:18 .config
-rw-r--r--  1 root root  148 Aug 17  2015 .profile
drwx------  2 root root    3 Oct 20 12:58 .ssh

**Comment by stgraber** [comment]
@tych0 could it be that criu somehow causes lxd to restart the container on failure? that may have it start with either the wrong uid/gid config or remap the filesystem without the container being unprivileged.

**Comment by nlienard** [comment]
https://gist.github.com/nlienard/446aa56679bbc84bd1826b72de407270

**Comment by tych0** [comment]
@stgraber not likely. the problem is just that the images are owned by root with 600, and they say to create a userns, so when criu spawns the userns it can't open the images. Basically, this just means they didn't get uid shifted but still said to create a user namespace, which means 1. we forgot a shift somewhere, or 2. the security.privileged flag got changed without a reboot.

**Comment by nlienard** [comment]
yes i'm pretty sure that I didn't reboot when i set security.privileged flag.

**Comment by stgraber** [comment]
@tych0 In the steps he gave, he effectively mentioned 2). I guess it's CRIU believing security.privileged rather than checking the volatile entry as we do everywhere else (like in file push/pull).

**Comment by tych0** [comment]
We don't pass CRIU the contents of security.privileged, it just inspects the task and figures it out on its own. The problem is that the container and security.privileged can be in an inconsistent state.

**Comment by stgraber** [comment]
@tych0 so is the some extra data we should be sending during migration? Basically sending the "current" privileged state on top of the "configured" privileged state. Seeing how the two are effectively different as privileged state changes are only done on full container restart (so migration doesn't).

**Comment by tych0** [comment]
Yeah, probably so. I'll have a look.

**Comment by nlienard** [comment]
i guess it can be closed
