### ISSUE TITLE
What is the point of the zfs file pool?

### ISSUE THREAD

**Issue by intdel** [lxc/lxd#2545]
Hello,

Not sure where else I could ask this, but what is the point of the zfs pool that I define in lxd init?
When I do a `df -h` I can see that everything is in /var/lib/lxd, but /lxd itself has "0" used. How does the allocation size of that ZFS pool file affect things?

```
lxd                                        61G     0   61G   0% /lxd
lxd/containers                             61G     0   61G   0% /lxd/containers
lxd/deleted                                61G     0   61G   0% /lxd/deleted
lxd/deleted/images                         61G     0   61G   0% /lxd/deleted/images
lxd/images                                 61G     0   61G   0% /lxd/images
lxd/containers/center                      62G  1.1G   61G   2% /var/lib/lxd/containers/center.zfs

```

Thanks!

**Comment by stgraber** [comment]
Not sure why your pool is mounted on /lxd, "lxd init" is supposed to always setup pools as not mounted.

ZFS pool structure is hierarchical, so we can't create "lxd/containers/center" without "lxd" and "lxd/containers" existing, even if those are effectively unused.

LXD will actively create entries under:
 - lxd/containers/*
 - lxd/images/*
 - lxd/snapshots/* (temporarily during publish)
 - lxd/deleted/* (for anything in the above which is still referenced by a downstream object but has been removed from the LXD DB).

**Comment by intdel** [comment]
Thanks for the quick response!
So even though it looks "empty", it is not? I mean, only that particular layer is empty in this case right (e.g. lxd and lxd container).

So effectively, all the data is stored in that pool file?

**Comment by stgraber** [comment]
You'll probably want to read a bit about how ZFS works in general, but basically you have:

 - Backing devices, which for LXD is a single file (/var/lib/lxd/zfs.img) unless you specified a physical disk partition at init time
 - A pool (lxd) in your case which is made of that backing device (or possibly multiple backing devices for raid)
 - A set of filesystems. Those are what "zfs list" shows you. Everything listed as "lxd/*" will be in the "lxd" pool and so stored in that one backing device.

The filesystems in a pool are stored in a tree, with the pool at the root. Settings applied anywhere in that tree will be inherited by the children. You can only ever destroy a filesystem if it has no children. Similarly you can't create a filesystem if its parent doesn't exist.


Anyway, yes, all of your containers data is stored on ZFS in that one pool that LXD setup for you.

**Comment by intdel** [comment]
Ok awesome thanks.
