### ISSUE TITLE
Question about mounting /tmp in tmpfs inside containers

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#2546]
LXD: 2.4.1
OS: Ubuntu Yakkety (host + container)

Adding this inside container /etc/fstab seems to work.

none            /tmp    tmpfs   rw,noatime,mode=1777,size=1G 0 0

Verify this is the most correct "LXD-esque" way to accomplish this.

Thanks.

**Comment by stgraber** [comment]
Yep, that's what you'd do inside a virtual machine and so that's what we expect you to do inside a LXD container.

**Comment by davidfavor** [comment]
Thanks.
