### ISSUE TITLE
ubuntu15 / slapd and systemd issue inside containers Failed to reset devices.list on /system.slice/

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#2547]
Hi

I'm running SLAPD on 2 containers and they have same issue :

Oct 24 06:25:01 inxovh-ldap002 systemd[1]: Failed to reset devices.list on /system.slice/slapd.service: Operation not permitted
Oct 24 09:24:44 inxovh-ldap002 systemd[1]: Failed to reset devices.list on /system.slice/slapd.service: Operation not permitted
Oct 24 09:24:44 inxovh-ldap002 slapd[279]:  * Starting OpenLDAP slapd
Oct 24 09:24:44 inxovh-ldap002 slapd[313]: @(#) $OpenLDAP: slapd  (Ubuntu) (May 11 2016 16:12:05) $#012#011buildd@lgw01-10:/build/openldap-mF7Kfq/openldap-2.4.42+dfsg/debian/build/servers/slapd
Oct 24 09:24:44 inxovh-ldap002 slapd[279]:    ...done.

The last one is after restarting containers otherwise slapd doesn't start :-(

**Comment by brauner** [comment]
Unprivileged containers are not allowed to change the `devices.list` file or in general modify the devices cgroup. This is enforced by the kernel and unfortunately there is not a lot from the `LXD` side to be done. Using privileged containers it is possible to circumvent this problem but *note well that this will significantly decrease container security* and is not likely what you want.

**Comment by nlienard** [comment]
thanks for your quick answer. 
Firstly i don't understand why systemd tried to modify slapd at 6h25.
but i noticed a memory leak on monitoring, slowly the memory grew up until 100%. so maybe systemd tried to restart it ?

For now, my workaround is very dirty:

*/15 * * * * lxc exec inxovh-ldap001 -- ldapsearch -H ldap://localhost -x -b 'uid=xxxxxxx' '*' > /dev/null || lxc restart inxovh-ldap001

**Comment by stgraber** [comment]
Those systemd error messages aren't fatal, they sure are annoying to see in logs, but they aren't the reason why your daemon isn't starting.

**Comment by stgraber** [comment]
Could it be log rotation that's triggering that slapd restart (and causing the failure)?

6:25am sounds suspiciously like the usual time logrotate triggers at.

**Comment by stgraber** [comment]
6:25am is when /etc/cron.daily/* are called, one of which is logrotate.

**Comment by nlienard** [comment]
this can be closed.

**Comment by drydenp** [comment]
I will ask here if you don't mind.

"Using privileged containers it is possible to circumvent this problem but note well that this will significantly decrease container security and is not likely what you want."

Privileged containers I start with LXC 2 all have this 'problem', but LXC 1 doesn't.

How do I get the behaviour of LXC 1 back?
