### ISSUE TITLE
Add container to a host's vlan

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2551]
Ubuntu 16.04
lxd 2.0.4
lxc 2.0.4

Hi,
I am trying to add the container to a host's VLAN and was unable to configure it properly.
The network configuration is as follows.

Physical interface: eth0
VLAN interface : eth0.172

bridge: br0 with eth0 as the physical interface.
containers running on bridge br0.

I want to run the containers on the VLAN interface.,
I tried the following,
1) add eth0.172 to br0 instead of eth0
2) create br0.172 and adding it to the config of container, (it failed)
3) Tried adding VLAN interface inside the container, and was able to access from container to outside world on VLAN, but not vice versa.

I want to access containers on a VLAN IP from other hosts, along with 10.x.y.z IP.

**Comment by stgraber** [comment]
lxc config device add container-name eth0 nic nictype=macvlan parent=eth0.172 name=eth0

That should work fine so long as you don't need communication between your host and container.

If you do need that kind of communication, then you need to setup a bridge in /etc/network/interfaces of your host, making sure that eht0.172 is bridged inside it, that eth0.172 itself has no IP configuration and that both br0 and eth0.172 are up before starting the container.

**Comment by upuvvad1** [comment]
Yes,
That works, however macvlan interface doesn't support migration. Isn't it ?

**Comment by stgraber** [comment]
Right, @tych0 is working on fixing that in CRIU.

**Comment by upuvvad1** [comment]
Hmm.
Thanks.

**Comment by stgraber** [comment]
So yeah, if you need live migration to work right now, you need to setup a bridge in /etc/network/interfaces on your host, then after confirming that it's all good, just tell LXD to use it.

**Comment by tych0** [comment]
In fact the patchset went in last week, so if you build from source you can try it out!

**Comment by tych0** [comment]
Oh, but you'll need my liblxc patches too. Let me post those.

**Comment by tych0** [comment]
https://github.com/lxc/lxc/pull/1248

**Comment by upuvvad1** [comment]
Thanks @tych0 .
I will give a try.

**Comment by upuvvad1** [comment]
@stgraber 

Do you mean add VLAN interface to the bridge, and specify the bridge to the container ?

Doesn't the container need to know any information about VLAN tag to process the packets ?

**Comment by stgraber** [comment]
@upuvvad1 

If you define a device in /etc/network/interfaces like:

auto br0
iface br0 inet manual
    bridge-ports eth0.172

And then use "br0" as the container's bridge, the container will be bridged onto eth0.172 and so see those packets untagged.

**Comment by upuvvad1** [comment]
@stgraber 
Thanks..It worked.

**Comment by stgraber** [comment]
Good to hear, closing
