### ISSUE TITLE
Busybox location for testing is undocumented

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2563]
I am trying to find out how [test](https://github.com/lxc/lxd/pull/2559/files#diff-af7a8c32dd51a408dc762fcdd12064d1) works. It uses some `testimage` which is imported by https://github.com/lxc/lxd/blob/master/test/deps/import-busybox call in https://github.com/lxc/lxd/blob/master/test/main.sh

But I don't understand where this busybox image is located.

I expected some docs at https://github.com/lxc/lxd/tree/master/test to see what is the contents of this image, is there `/root` dir?

**Comment by stgraber** [comment]
import-busybox generates the image for you from your system's busybox binary.
Just call the script and you'll see the image be imported in your LXD.

**Comment by techtonik** [comment]
@stgraber I'd like to test my local client against remote server. Is there any way to get this image without needing shell access to server machine?

**Comment by techtonik** [comment]
Also, I would rename script from `import-busybox` to `generate-busybox` or `create-busybox`.

**Comment by stgraber** [comment]
Not really, the script doesn't know how to deal with a remote LXD and wouldn't really run on a Windows system anyway.

You could just launch a container on your remote LXD host, then run the script inside the container though and then grab the image and push it to whatever LXD you want.

**Comment by techtonik** [comment]
> You could just launch a container on your remote LXD host, then run the script inside the container though and then grab the image and push it to whatever LXD you want.

Looks like a way to go. Is there any prerequisites I need to be aware of before starting `import-busybox`? I can ask somebody with root access to run necessary commands for me on that box.

**Comment by techtonik** [comment]
Why it is named `import-busybox` if it doesn't import image, but creates it?

**Comment by stgraber** [comment]
It also imports it in LXD. Anyway, it's a hidden away command that's only used in our tests, so its name doesn't matter so much. Running the testsuite will generate and import the image in the various LXDs that are spawned by the testsuite.

**Comment by techtonik** [comment]
I still need ability to run the test suite against remote `busybox`. ) Will look into this later.

**Comment by stgraber** [comment]
You can't do that. The testsuite doesn't run against a remote LXD, it spawns a dozen LXD daemons itself, with varying options and heavily relies on running on the same machine as the daemons it spawns.

**Comment by techtonik** [comment]
https://github.com/lxc/lxd/blob/master/test/suites/filemanip.sh doesn't looks like spawning any local daemons.
