### ISSUE TITLE
lxc move fails with criu error

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2568]
Ubuntu 16.04
lxd 2.4.1
lxc 2.4.1

I am running LAMP stack on lxc container with heavy http requests .
When the container was to busy, the migration fails with the below error.
However, with no or low http connections, the migration succeeds.

04.604713) epoll: Dumping: eventpoll-tfd: id 00000000 tfd 0x000004 events 0x000019 data 0x007fe808b961e8
(04.604724) epoll: Dumping eventpoll: id 0x000093 flags 0x80002
(04.604732) fdinfo: type: 0x7 flags: 02000002/01 pos:        0 fd: 10
(04.604745) 15347 fdinfo 11: pos:                0 flags:          2004002/0x1
(04.604753) 	Searching for socket 22734 (family 10.6)
(04.604758) Error (criu/sk-inet.c:202): Name resolved on unconnected socket
(04.604762) ----------------------------------------
(04.604776) Error (criu/cr-dump.c:1312): Dump files (pid: 15347) failed with -1
(04.604805) Waiting for 15347 to trap
(04.604825) Daemon 15347 exited trapping
(04.604833) Sent msg to daemon 5 0 0
pie: 313: __fetched msg: 5 0 0
pie: 313: 313: new_sp=0x7f5b70315008 ip 0x7f8686d7e53e

**Comment by upuvvad1** [comment]
Some information is available at
https://marc.ttias.be/openvz-criu/2016-07/msg00079.php

**Comment by tych0** [comment]
We should probably close this in favor of https://github.com/xemul/criu/issues/237.
