### ISSUE TITLE
Moving a container to another lxd server fails when snapshots exist

### ISSUE THREAD

**Issue by keestux** [lxc/lxd#2580]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 16.04
 * The output of "lxc info" or if that fails:

(Stripped output of lxc info)

    apiextensions: []
    apistatus: stable
    apiversion: "1.0"
    auth: trusted
    environment:
      architectures:
      - x86_64
      - i686
      driver: lxc
      driverversion: 2.0.4
      kernel: Linux
      kernelarchitecture: x86_64
      kernelversion: 4.4.0-38-generic
      server: lxd
      serverpid: 18454
      serverversion: 2.0.4
      storage: btrfs
      storageversion: "4.4"

# Issue description

The move fails with an error message like this:

    # lxc move test02 host2:test02
    error: subvolume snapshot failed, source=/var/lib/lxd/snapshots/test02/.root, dest=/var/lib/lxd/containers/test02, output=ERROR: cannot access subvolume /var/lib/lxd/snapshots/test02/.root: No such file or directory

lxc list shows the presence of the container on the remote. But only the snapshot is present on the remote. Sometimes the "btrfs send" process is still active, and it has to be killed to be able to delete the ".root" subvolume.

# Workaround

If the snapshots are removed before doing "lxc move" then the command will succeed.

# Steps to reproduce

    lxc launch ubuntu:16.04 test02
    lxc stop test02
    lxc snapshot test02
    lxc list
    lxc list host2:
    lxc move test02 host2:test02

# Information to attach

syslog on host2

    Oct 28 09:49:55 host2 lxd[3832]: t=2016-10-28T09:49:55+0200 lvl=eror msg="subvolume snapshot failed" driver=storage/btrfs source=/var/lib/lxd/snapshots/test02/.root dest=/var/lib/lxd/containers/test02 output="ERROR: cannot access subvolume /var/lib/lxd/snapshots/test02/.root: No such file or directory\n"
    Oct 28 09:49:55 host2 lxd[3832]: t=2016-10-28T09:49:55+0200 lvl=eror msg="problem with btrfs snapshot" err="subvolume snapshot failed, source=/var/lib/lxd/snapshots/test02/.root, dest=/var/lib/lxd/containers/test02, output=ERROR: cannot access subvolume /var/lib/lxd/snapshots/test02/.root: No such file or directory\n"

**Comment by stgraber** [comment]
Can you retry with LXD 2.0.5?

**Comment by keestux** [comment]
Ah, that works. Thanks.
I thought I checked for updates, but I only checked one of the two servers.

**Comment by seanfulton** [comment]
This looks like it has appeared. I am using LXD 3.9 (both ends):
t=2019-01-21T12:58:28-0500 lvl=info msg="Migrating container" actionscript=false created=2019-01-04T13:21:11-0500 ephemeral=false features=1 name=t3 predumpdir= project=default statedir= stop=false used=2019-01-20T20:26:40-0500
t=2019-01-21T12:58:28-0500 lvl=eror msg="Rsync send failed: /var/snap/lxd/common/lxd/snapshots/t3/t3-tableau-clean/: exit status 23: rsync: change_dir \"/var/snap/lxd/common/lxd/snapshots/t3/t3-tableau-clean\" failed: No such file or directory (2)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]\n"
