### ISSUE TITLE
How to connect to container which is behind iptables rule

### ISSUE THREAD

**Issue by wtayyeb** [lxc/lxd#2584]
It is common to access a container from out of host with simple iptable rules which forward a port on host to a port on container with container internal IP in hand

```
-A PREROUTING -d 1.2.3.4/32 -i eth0 -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.0.4.10:80
```

So public IP 1.2.3.4 will routed to the container. with a proper dns record one can point a FQDN (eg: test.example.com) to this container also. and all things is working good til this point.

BUT in the host or in neighbor containers on same host, the FQDN is useless and not routed to that container.

by setting this beside above rule it routes packets from host to that FQDN to container, this work for host only

```
-A OUTPUT -d 1.2.3.4/32 -j DNAT --to-destination 10.0.4.10 -t nat
```

but neighbor containers still cannot use that FQDN.

So I debug iptable rules on host and got this one which blocks the route between containers:

```
-A POSTROUTING -s 10.0.4.0/24 ! -d 10.0.4.0/24 -m comment --comment "generated for LXD network lxdbr0" -j MASQUERADE
```

made a change to it `-d 10.0.4.0/32` and the route works now. the FQDN will routed to correct container.

my question is why this line added to iptables by lxd-network? and is it safe to change it like what I am do?

NOTE: ping is working all the time because it is responded by host. but other packets like tcp/80, ... have above problem.

**Comment by stgraber** [comment]
You may be interested by the "-I" flag from iptables which lets you prepend rules ahead of any other rule in the table.

The rule is generated by LXD to allow containers to talk to machines outside of their bridge as without it, there wouldn't be any NAT in place. Your change effectively makes it so that traffic between containers on the bridge will also be NATed. That may be fine in your case but is usually unexpected for machines that site within the same subnet.

(Note that whether cross-container traffic will be NATed in this case will depend on whether you have the iptables hook for bridges enabled, this defaults to off and usually requires an extra module to be loaded)

**Comment by wtayyeb** [comment]
Ok I understand that NAT is bad things there, but the packets also must not lost. So I revert my change to LXD default and add new rule to iptables to just affect that container only (container static ip is 10.0.4.30).

    -A POSTROUTING -s 10.0.4.0/24 -d 10.0.4.30/32 -j MASQUERADE

Currently it get working everywhere with three rules, but is there is any other way to do this working?

    -A PREROUTING  -d 1.2.3.4/32 -j DNAT --to-destination 10.0.4.30   #1
    -A OUTPUT      -d 1.2.3.4/32 -j DNAT --to-destination 10.0.4.30   #2
    -A POSTROUTING -s 10.0.4.0/24 -d 10.0.4.30/32 -j MASQUERADE       #3

1. outbound to container
1. host to container
1. container to container
 
all rules also have `-p tcp -m multiport --dports 80,443 ...`

I`m not expert in iptables. and all my knowledge is from several hours of try and error with it.

**Comment by davidfavor** [comment]
This ticket seems to talk about a similar problem I was having, where I was attempting to duplicate my LXC way of doing things with LXD.

https://github.com/lxc/lxd/issues/2534 covers a much more elegant way to approach to making LXD containers look like full fledged hosts/IPs where all packet routing just works.

Host to Containers.
Containers to Host.
Containers to Containers.
Containers to Public IPs.

https://github.com/lxc/lxd/issues/2534 resolves many ongoing communication glitches I was having. No all communication... just works...

**Comment by stgraber** [comment]
I'm not seeing anything directly actionable for us as LXD devs to work on. This particular problem can be worked around a rather big set of iptables rules, or as @davidfavor mentioned, by routing an actual public IP to the container and avoid the whole NAT thing entirely.
