### ISSUE TITLE
user.network-config not passed into the container

### ISSUE THREAD

**Issue by lennyby93** [lxc/lxd#2587]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.10
 * The output of "lxc info" or if that fails:
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 127.0.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFZzCCA0+gAwIBAgIRAMeZgktaVRiendqhGAxOxoMwDQYJKoZIhvcNAQELBQAw
    ......
   0223Mb4+cHgh4VUoys6vsZXz64mFDUa/gwmHRfyb9+BThRb7vh/iTnsumA==
    -----END CERTIFICATE-----
  certificatefingerprint: 02cc3f7c235af6ce3ce15d8e364b28d24ace2ce49a916f83c13f5537414c90d2
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.0-26-generic
  server: lxd
  serverpid: 1929
  serverversion: 2.4.1
  storage: btrfs
  storageversion: 4.7.3
config:
  core.https_address: 127.0.0.1
  core.trust_password: true
public: false
# Issue description

I'm trying to setup containers with static IP addressing. I've tried to setup both profiles and individual containers with 'config.network-config':

:~$ lxc profile show bootstrap
name: bootstrap
config:
  user.network-config: |-
    version: 1
    config:
     - type: physical
       name: eth0
       subnets:
        - control: auto
          type: static
          address: 192.168.10.15
          gateway: 192.168.10.1
          netmask: 255.255.255.0
description: used for bootstrapping of containers
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: vlan2
    type: nic

but when I spin up a container using that profile the seed data contains dynamic config:

root@test1:~# cat /var/lib/cloud/seed/nocloud-net/network-config
version: 1
config:
    - type: physical
      name: eth0
      subnets:
          - type: dhcp
            control: auto

# Steps to reproduce

1. Create user.network-config key in a profile
2. Spin up a container using that profile

Is this a feature or is it possible to pass static network config?

**Comment by stgraber** [comment]
What image are you using exactly?

Support for user.network-config was only added to the image building scripts for the cloud images about a week ago, so it may still take a while before all images have support for it.

You can try grabbing an image from "ubuntu-daily" rather than "ubuntu", those should be more likely to have the change.

**Comment by stgraber** [comment]
Looking on my local systems, those appear to be the images that have support for network-config:
```
root@dakara:~# ls -lh /var/lib/lxd/images/*/templates/*network*
-rw-r--r-- 1 root root 208 Oct 20 15:45 /var/lib/lxd/images/1e66f9fa622c0cf03ac395d6fddddcdb0a1ea08bd8753900b0f2a18acf42f2b3.zfs/templates/cloud-init-network.tpl
-rw-r--r-- 1 root root 208 Oct 20 13:57 /var/lib/lxd/images/315bedd32580c3fb79fd2003746245b9fe6a8863fc9dd990c3a2dc90f4930039.zfs/templates/cloud-init-network.tpl
-rw-r--r-- 1 root root 208 Oct 13 14:08 /var/lib/lxd/images/6f25adef061c3f2186c6910bff8cacd0c63e1493e3f8b616e52eb84076890bd1.zfs/templates/cloud-init-network.tpl
```

**Comment by stgraber** [comment]
Oh, right, my check was wrong, you don't just need the template, you need the latest version of it.

**Comment by lennyby93** [comment]
Any idea if there are any ubuntu images that already have that newest version?

**Comment by stgraber** [comment]
```
root@dakara:~# lxc launch ubuntu-daily:16.04 latest
Creating latest
Retrieving image: 100%
Starting latest

root@dakara:~# cat /var/lib/lxd/containers/latest/templates/cloud-init-network.tpl
{% if config_get("user.network-config", "") == "" %}version: 1
config:
    - type: physical
      name: eth0
      subnets:
          - type: {% if config_get("user.network_mode", "") == "link-local" %}manual{% else %}dhcp{% endif %}
            control: auto{% else %}{{ config_get("user.network-config", "") }}{% endif %}
```

So yeah, as I suggested above, using "ubuntu-daily" will get you an image with that feature.

Images in the normal stable stream will get this next time they're updated (I think it's every couple of weeks or whenever there's a big security issue to fix).

**Comment by lennyby93** [comment]
Just looking at that template - there is no way to generate 'static' entry (unless I'm completely blind) like the one I'm after:

version: 1
config:
 - type: physical
   name: eth0
   subnets:
    - control: auto
      type: static
      address: 192.168.10.15
      gateway: 192.168.10.1
      netmask: 255.255.255.0

**Comment by stgraber** [comment]
```
stgraber@dakara:~$ lxc profile create test
Profile test created

stgraber@dakara:~$ lxc profile edit test

stgraber@dakara:~$ lxc profile show test
name: test
config:
  user.network-config: |-
    version: 1
    config:
      - type: physical
        name: eth0
        subnets:
          - control: auto
            type: static
            address: 192.168.10.15
            gateway: 192.168.10.1
            netmask: 255.255.255.0
description: ""
devices: {}
usedby: []

stgraber@dakara:~$ lxc launch ubuntu-daily:16.04 -p default -p test test
Creating test
Starting test

stgraber@dakara:~$ lxc exec test -- ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 00:16:3e:b4:9d:c6
          inet addr:192.168.10.15  Bcast:192.168.10.255  Mask:255.255.255.0
          inet6 addr: fe80::216:3eff:feb4:9dc6/64 Scope:Link
          inet6 addr: fd42:a4f6:6365:4106:216:3eff:feb4:9dc6/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:69 errors:0 dropped:1 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:8933 (8.9 KB)  TX bytes:750 (750.0 B)

stgraber@dakara:~$
```

**Comment by lennyby93** [comment]
Thank you for your help. This is exactly what I was after :-)
