### ISSUE TITLE
Commands required to integrate rsync'ed LXD container from another machine

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#2588]
```
net11 # lsb_release -sc
yakkety

net11 # lxd --version
2.4.1
```

After rsync container from one machine to another, looking for command sequence to update /var/lib/lxd/lxd.db database so LXD becomes aware of new container.

```
mkdir /var/lib/lxd/containers/yakkety
rsync -v -aKH -AX --devices --specials --numeric-ids -e "ssh -i $certfile" root@net12.bizcooker.com:/var/lib/lxd/containers/yakkety/. /var/lib/lxd/containers/yakkety/.
```

Various postings suggest - lxc config set - which fails...

```
lxc config set yakkety security.privileged true
error: not found
```

Someone point me to docs which show best way to accomplish this.

Thanks.

**Comment by stgraber** [comment]
If both hosts are LXD as seems to be the case here, you should just use the "lxc move" or "lxc copy" commands rather than trying to do things yourself in LXD's back.

If migrating between machines that aren't both LXD, the easiest is to create an empty container on the target and just overwrite its filesystem with rsync afterwards. Note that you may need to remap all the uid/gid depending on whether your source was privileged or not.

**Comment by davidfavor** [comment]
I'd prefer a non-easy way then.

Many sites I host can be many Gig in size + being able to rsync files on to many machines, then bring up a copy of site on any machine is essential. Many of these sites have complex ACLs which must transfer correctly.

I'd must rather work with rsync, so lsyncd can also be used.

Likely lxc move/copy would take a very long time to execute + provide no incremental/granular control over the process. 

Please pass along whatever voodoo magic is required to accomplish this.

**Comment by stgraber** [comment]
Ok, so then just do what I described in my second paragraph. Create a dummy container on your target and rsync over it.

**Comment by stgraber** [comment]
If your source and target host don't have matching uid ranges or your source container is privileged and your target isn't, you will also need to change all uid, gid and ACLs of every file in the container after you rsync, but you probably have enough control on your environment to avoid having to do that.

**Comment by davidfavor** [comment]
Yep I can see how I can do this.

Maybe you have a better way of accomplishing what I'm trying to accomplish.

Imagine you have a container on one machine that's 50Gig in size with say 25Gig of many small email messages, so doing an lxc move/copy might take many hours... or days on slow connections.

Currently I'm using LXC + each night at midnight, the following sequence runs for many containers targeting many backup machines.

1) Incrementally rsync the source containers of live/production machines to many other target machines.

2) Then, lxc-stop container on target machine + rsync again (to flush file/database buffers) to bring all files consistent... especially database files...

3) lxc-start container on target machine

This results in many copies of each LXC container on many machines, so if a machine dies... or more likely OVH screws up their networking (happens many times) so machines are unreachable by some Internet network segments...

The production containers can be shutdown + a copy started on some other machine + IP reset +  production site(s) comes back online.

Currently I do this with LXC privileged containers, so all uid/gid numbers are 0 relative.

I'm moving to LXD unprivileged containers, so this becomes more complex.

So the question becomes...

Describe the best way to incrementally clone (usually rsync/lsyncd) live containers to many backup machines + fixup uid/gid numbers on backup machines, handling the case where many source machine LXD containers may have the same uid/gid numbers...

So that all the backup machine containers can be started, ad-hoc, as required + be partitioned from all other LXD containers (no uid/gid duplication).
