### ISSUE TITLE
Troublesome user management

### ISSUE THREAD

**Issue by dann1** [lxc/lxd#2589]
# lxc info output 
* Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
apicompat: 0
auth: trusted
environment:
  addresses:
  - 10.8.9.48:8443
  - 192.168.0.1:8443
  - 192.168.1.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIGGTCCBAGgAwIBAgIQC/EBvoPH0UFWG/Z63rV9xDANBgkqhkiG9w0BAQsFADAx
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMREwDwYDVQQDDAhyb290QGx4
    ZDAeFw0xNjExMDIxNzI2MjVaFw0yNjEwMzExNzI2MjVaMDExHDAaBgNVBAoTE2xp
    bnV4Y29udGFpbmVycy5vcmcxETAPBgNVBAMMCHJvb3RAbHhkMIICIjANBgkqhkiG
    9w0BAQEFAAOCAg8AMIICCgKCAgEA5NFcOPjW+I1HVBt14CRHrd8wbLcYIuTlEPQ4
    VzNU5xmPvF89xZFMPEpH6RYDK7ee29lKY/B+hC8oINTNweIaGD/jbcx1txuQT5jE
    VQ8yNI775eA8RTNV1zUzF0k9wm62vzrLoJHjp6Sr5xILxK+Nx5f33148rF/zX7d0
    GdcLEryGShLW41T5aDzkJPJy2ohFOP1cm3FM5uSwmyWfPGRsvGu/EhWCS68rJ1rz
    rFgxyFCQZJMtamUx8Pef5xSn8PJ1rjlVXf74EZ2W9kOA3rPZLssnE6Hup4QNJCbA
    OSLxYLDOzERImd0Zl3gXL7EmJ/bkNcgFfXDMsvJqnmUH3quVB2lLYmlJclIl+4FA
    7ggR22jQPSfgFAPkSSrlhhHJem0DhMOd8kh2nSWr35sKmijA7CU6vJixMG2/vpj6
    vLj96xdqtW01EAhzNHeBv/ngRqQE/gAQrC5LUxDDhzbYkGx4mIlei0F1iKTvNJm7
    h7tvPAYuPgNlZsEwii1aBYBXSBDmTJZjjbZ1LhGkGtdUy2568oYlqmgLzDE8piBt
    E+kDgSVMPTxUU/SBdSJ74W3E3gBbwXIU4F0JPcX81sBzHshQJmub/Orp6x8b6ot4
    tCkh29AKAOXq2K/ltg7UvznBsLtnFOcP/gU6G+lyWSnjZd8Q+X6YF7SmVXEL/Gsf
    3QhiLs8CAwEAAaOCASswggEnMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMIHxBgNVHREEgekwgeaCA2x4ZIIbZmU4MDo6
    ZTU0OmE1ZmY6ZmU0Njo4ZjAxLzY0ghxmZTgwOjphYzA4OjZmZmY6ZmVlODpjOTk0
    LzY0ggwxMC44LjkuNDgvMjSCHGZlODA6OmFjMDg6NmZmZjpmZWU4OmM5OTQvNjSC
    HGZlODA6OmI0NzU6OGRmZjpmZWY2OmI3NDAvNjSCDjE5Mi4xNjguMC4xLzI0ghxm
    ZTgwOjo4MDRjOmVmZmY6ZmU1NzpkNDM0LzY0gg4xOTIuMTY4LjEuMS8yNIIcZmU4
    MDo6NTRiYzpjZmZmOmZlNWY6ZDczNC82NDANBgkqhkiG9w0BAQsFAAOCAgEAZTSJ
    Ui/CISScV92a756UAzCNG6lmTXNW9aa1saBWKm+xim3D4dAfIIHDUnXuV7DUP96+
    BRtucTXulaEEggEouHif+82+JyVk76Yr8T+mbyHaR0nTZKxrItot1WJKEZowA6pZ
    lHuk7XQffP/SDCf2+E5ycgOuTGk5yK0f8/IujKw/4OTaRY6jFtm2YolaIEGWVppC
    f4JI+BGAbQ4HiDwLvXmUYIjY811L2kFt+PQhoW027C/Daqd+7TAE/Tx01SHNmbqD
    nr0hmtpBT5fVIhXWm9dO3qy2jLOypUIPymoX+OUDSm762rosYjdGl76Wuq/ha80O
    A7ZcaRuPOElnwTCjUm6JcxYp2K/tVzNp6Yts62w1tmUABbHPK+veSs1/eMFcA8E9
    k7y0HOErJYVMJG5fPtJ5zeO8qaPJbyyBt8/US0QqyXunLgwtVtEAo7SqnwT41j3a
    sY7oy8JM34RwVwv375PTJHE7Noxtl7bXVaJzGPRyGAmoLGKWO4/FHhZydBoRgc1C
    qaGqUAliIV28oh21QtVQknGoUvO3UfVgYEEwKm8fQW2QohDZ1jygwURwOCIYbmQf
    ATWWT/OoU2hlcK0l1EowQtX4tVXcKFG4+YA3ucGw/uGWyTZCvaHo7Qcfna+8TAwG
    F/tfpD47PUag5UuWaOqSt2u6aNurBU2koD34iIQ=
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-45-generic
  server: lxd
  serverpid: 6093
  serverversion: 2.0.5
  storage: btrfs
  storageversion: "4.4"
config:
  core.https_address: 0.0.0.0:8443
  core.trust_password: true
public: false
# Issue description

Cannot add  users properly indide a container, when i try to add a user by **adduser** or **useradd** the user is created but I cannot enter the password properly to enter the container using ssh. Pretty much everything related to user management is not OK, **passwd** doesn't work either so, also is there a way to get a login shell in a container like in lxc with **lxc-console** that spawns the login
# Steps to reproduce

For example with passwd
`
lxc exec container bash
passwd
Enter new UNIX password: 
Retype new UNIX password: 
passwd: Authentication token manipulation error
passwd: password unchanged
`

With adduser
`
adduser user1
Adding user user1 ...
Adding new group user1 (1009) ...
Adding new user user1 (1009) with group user1 ...
Creating home directory /home/user1 ...
Copying files from /etc/skel ...
Enter new UNIX password: 
Retype new UNIX password: 
passwd: Authentication token manipulation error
passwd: password unchanged
Try again? [y/N] y
Enter new UNIX password: 
Retype new UNIX password: 
passwd: Authentication token manipulation error
passwd: password unchanged
Try again? [y/N] n
Changing the user information for user1
Enter the new value, or press ENTER for the default
        Full Name []: 
        Room Number []: 
        Work Phone []: 
        Home Phone []: 
        Other []: 
Is the information correct? [Y/n] y
`
With su using the default preexisting ubuntu  user

`
su - ubuntu
setgid: Operation not permitted
`

This is troublesome because some applications create users, for example, when installing OpenNebula, a user and a group named oneadmin are created  with ids 9869:9869 and it results in an incomplete setup.

**Comment by stgraber** [comment]
Not sure what kind of container image you're using, but using a stock Ubuntu 16.04 image here, everything appears to be working just fine:

```
stgraber@castiana:~$ lxc launch ubuntu:16.04 test
Creating test
Starting test

stgraber@castiana:~$ lxc exec test bash
root@test:~# su ubuntu
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@test:/root$ exit

root@test:~# adduser test
Adding user `test' ...
Adding new group `test' (1001) ...
Adding new user `test' (1001) with group `test' ...
Creating home directory `/home/test' ...
Copying files from `/etc/skel' ...
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
Changing the user information for test
Enter the new value, or press ENTER for the default
        Full Name []:
        Room Number []:
        Work Phone []:
        Home Phone []:
        Other []:
Is the information correct? [Y/n] y

root@test:~# su test
test@test:/root$ exit

root@test:~# passwd test
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully

root@test:~# login
test login: test
Password:
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.8.0-26-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

test@test:~$
```

**Comment by stgraber** [comment]
Oh and to match exactly what you ran:

```
root@test:~# su - ubuntu
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@test:~$
```

**Comment by stgraber** [comment]
To get a console login prompt, you can do "lxc exec CONTAINER login"

**Comment by dann1** [comment]
I'm using a xenial image from https://images.linuxcontainers.org, I customized it adding some software like _nano_ and _wget_ , well what is the url for the image to download? Thank you for your quick answer

**Comment by stgraber** [comment]
Ok, re-trying what I did above with the xenial image from images.linuxcontainers.org (images: remote).

```
stgraber@dakara:~$ lxc launch images:ubuntu/xenial test
Creating test
Retrieving image: 100%
Starting test

stgraber@dakara:~$ lxc exec test bash
root@test:~# su ubuntu
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@test:/root$ exit
root@test:~# adduser test
Adding user `test' ...
Adding new group `test' (1001) ...
Adding new user `test' (1001) with group `test' ...
Creating home directory `/home/test' ...
Copying files from `/etc/skel' ...
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
Changing the user information for test
Enter the new value, or press ENTER for the default
        Full Name []:
        Room Number []:
        Work Phone []:
        Home Phone []:
        Other []:
Is the information correct? [Y/n] y

root@test:~# su test
test@test:/root$ exit

root@test:~# passwd test
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully

root@test:~# login
test login: test
Password:
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-45-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

test@test:~$ logout

root@test:~# su - ubuntu
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@test:~$ logout
root@test:~#
```

So seems to be working as expected using that image too.

**Comment by dann1** [comment]
Well then I have no idea, I lxc image import to cache the image:
`
lxc image import image.tar.xz --alias alias 
`
I have to try lxc launch directly from the remote instead of the local imported image

**Comment by stgraber** [comment]
Image import should work perfectly fine, but the kind of problem you're running into is probably because you somehow altered file ownership and/or dropped setuid bits inside your image.

So it's effectively a problem with the content of your modified image that's causing the problems you're running into instead of a LXD bug.

**Comment by stgraber** [comment]
I'd recommend you run "tar Jtvf" against your image and check that the file owners and modes make sense, I suspect that's where you'll find your problem.

**Comment by dann1** [comment]
I tested it with a jessie container and the same happened, thank you I'll try that tar command, is this the url that lxd uses to get the image, I mean there are lots of files in https://cloud-images.ubuntu.com/releases, I'm downloading this one https://cloud-images.ubuntu.com/releases/16.04/release/ubuntu-16.04-server-cloudimg-amd64.tar.gz

**Comment by stgraber** [comment]
It's where it grabs them, along with extra data from the stream data.
I'm still not sure why you're grabbing the tarballs directly though...

You can just run "lxc image export images:ubuntu/xenial" and it will output the image tarballs in your current directory.

You should also read the image-handling document in the doc/ directory to understand how image are structured, especially if you intent to repack them: https://github.com/lxc/lxd/blob/master/doc/image-handling.md

All our official images are in the split format, so they're made of two tarballs, one containing just the metadata and templates, and the other that contains the unshifted rootfs.

**Comment by dann1** [comment]
FINALLY!! It all worked out well I ran the _tar_ you mentioned and the owner was my user, I think I extracted the files some time ago
