### ISSUE TITLE
Request for correct way to bring up lxdbr0 at boot time

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#2591]
```
net11 # lsb_release -sc
yakkety

net11 # lxd --version
2.5
```
After reboot, lxdbr0 seems to only configure when the lxc client runs.

Issuing - lxc list - or any other lxc command brings up lxdbr0.

This creates complexities issuing route commands at boot time to route public IPs to lxdbr0.

My current fix in /etc/rc.local consists of...

1) wait for base interface to come up

2) issue lxc list to bring up lxdbr0

3) wait for lxdbr0 to configure

4) issue appropriate - ip -4 route add IP/MASK dev lxdbr0 - commands for IP ranges on machine.

Likely I'm missing something simple here.

Let me know the correct LXD-esque way to bring up lxdbr0 at boot time.

Thanks.

**Comment by stgraber** [comment]
Hi,

You're absolutely correct. LXD only starts when a client first connects OR if it has auto-started containers OR if it's configured to listen on the network.

An easy trick to have it start at boot would be to set core.https_address to 127.0.0.1. Alternatively you could modify the lxd.service systemd unit to have it always start.

LXD only comes up after the system has configured networking so you'd still need to wait a bit.

I suspect the most reliable way to do what you want is to make a new systemd unit which executes your configuration script and that's configured to start AFTER lxd.service.

**Comment by davidfavor** [comment]
Probably - lxc config get core.https_address - will also work.

Thanks.
