### ISSUE TITLE
lxc exec --mode + STDOUT + STDERR

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#2592]
```
net11 # lsb_release -sc
yakkety

net11 # lxd --version
2.5
```

Looking for a way for - lxc exec - to echo STDOUT + STDERR.

The patch related to adding --mode suggests this allows STDOUT + STDERR to echo. This doesn't seem to be the case.

lxc exec --mode={auto,interactive,non-interactive} name -- flarg

All produce empty STDERR.

I'm trying to debug - lxc exec - command which fail silently where --debug seems to provide no helpful information.

Thanks.

**Comment by stgraber** [comment]
Works fine here:

```
stgraber@castiana:~$ lxc exec test --mode=non-interactive -- sh -c "(echo out > /dev/stdout ; echo err > /dev/stderr)" 2>/dev/null
out

stgraber@castiana:~$ lxc exec test --mode=non-interactive -- sh -c "(echo out > /dev/stdout ; echo err > /dev/stderr)" >/dev/null
err
```

**Comment by davidfavor** [comment]
Oh I see...

So...  lxc exec works differently than lxc-attach...

```
net11 # lxc exec name -- bash -c "flarg"
bash: flarg: command not found
```
So all commands have to be wrapped in a shell to output useful diagnostics.

Thanks.
