### ISSUE TITLE
How to hide lots of veth** network interfaces on the host / user namespaces

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#2596]
* Distribution: ubuntu 
 * Distribution version:16.04.1 LTS
 *lxc info:
apiextensions: []
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 172.16.0.20:8443
  - 172.16.11.1:8443
  - 172.16.12.1:8443
  - 172.16.10.1:8443
  - 192.168.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
     -----END CERTIFICATE-----
  certificatefingerprint: ea854278d6e269bb441c2b59b3407ff2a90459486478cefc439d9750e3b2afd9
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-45-generic
  server: lxd
  serverpid: 5462
  serverversion: 2.0.5
  storage: btrfs
  storageversion: "4.4"
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
public: false

I have 3 bridges for lxd : lxdbr0,1,2.

# Issue description

When we spawn lxd containers, a veth*** network interfaces appears on the host for each network interface in the container.  With 3 interfaces per container and 20 containers, the ifconfig output is full of veth***.

Is there a way to hide them ? 

ip netns list   show nothing: i thought lxc/lxd was using namespaces so how to see them ?

# Steps to reproduce

- creates lxd containers with network interfaces
- ifconfig show veth* network interfaces on the host

**Comment by stgraber** [comment]
There is no way to hide them. If your container uses veth devices, which is basically always the case except for macvlan or physical passthrough. then a host side device must exist and is bridged.

It's just how things work at the kernel level and there's nothing we can do about this. A number of monitoring software and network management tools have been made aware of this and will not list those veth devices, but ifconfig/ip always will.

**Comment by gaetanquentin** [comment]
OK.
 is there a way to rename them? So that veth** associated to container lxdmy-1 could be renames lxdmy-veth-xx?

**Comment by stgraber** [comment]
You can set the host_name property on the nic device to whatever name you want. There is no way to have LXD automatically tied those to your container's name though, so you'll have to do it manually.

The reason we don't make the device name more user friendly is that interface name length is restricted to 15 characters, whereas container names are restricted to 64 characters.
