### ISSUE TITLE
How to hide container pocesses  on the host / user namespaces

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#2597]
Distribution: ubuntu
    Distribution version:16.04.1 LTS
    *lxc info:
    apiextensions: []
    apistatus: stable
    apiversion: "1.0"
    auth: trusted
    environment:
    addresses:

    172.16.0.20:8443
    172.16.11.1:8443
    172.16.12.1:8443
    172.16.10.1:8443
    192.168.0.1:8443
    architectures:
    x86_64
    i686
    certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
    certificatefingerprint: ea854278d6e269bb441c2b59b3407ff2a90459486478cefc439d9750e3b2afd9
    driver: lxc
    driverversion: 2.0.5
    kernel: Linux
    kernelarchitecture: x86_64
    kernelversion: 4.4.0-45-generic
    server: lxd
    serverpid: 5462
    serverversion: 2.0.5
    storage: btrfs
    storageversion: "4.4"
    config:
    core.https_address: '[::]:8443'
    core.trust_password: true
    public: false

Issue description
launching lots of containers results in seeing lots of containers's processes on the host, which is not usefull : is there a way to hide them on the host?

**Comment by stgraber** [comment]
Nope, there is no way to hide them.

Even if you somehow could, that would effectively break LXD and most other container management tools that rely on being able to see the process tree from the host.
