### ISSUE TITLE
Snapshot from inside a container

### ISSUE THREAD

**Issue by Nesta0** [lxc/lxd#2600]
Hello,

Is there any way/trick to perform a container snapshot from inside that same container?

Here's the context: There's an user who have an access to a container on my server.
But I don't want him to have any account on the main server... and he needs to make some snapshots.
I cannot always perform that for him, it's very annoying. Does a solution even exists?
I'm ready to accept some trick, workaround, some UID/GID mapping, I don't know...
Or I also can wait for a future feature ;)

Thanks a lot,
Cheers.

 * Distribution version: Ubuntu 16.04.1 LTS
 * The output of "lxc info":
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-45-generic
  server: lxd
  serverpid: 2616
  serverversion: "2.5"
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd

**Comment by stgraber** [comment]
There's no solution to this that I can think of right now.

Your best bet is probably to allow a restricted SSH shell from the container to the host, allowing it to call "lxc snapshot NAME SNAP-NAME" but nothing else.

**Comment by srkunze** [comment]
Is it even safe to allow this kind of interaction of a container with its host? Couldn't this lead to some sort of mis-use/corruption of the host?

**Comment by stgraber** [comment]
It certainly could lead to DoS if the container is untrusted, so that's why I suggested the SSH trick for those cases where you really do trust the container.

**Comment by srkunze** [comment]
Exactly.

An additional protection could be provided by something like:

- minimum snapshot interval
- minimum command interval
- snapshot rotation à la logrotate.d

Don't know if it's the responsibility of LXD to provide something like that.

**Comment by stgraber** [comment]
Yeah, feels out of scope for LXD, at least in its current form.
