### ISSUE TITLE
Consistent snapshots for dir based containers

### ISSUE THREAD

**Issue by nakatadim** [lxc/lxd#2601]
Hey there,

this is not about a bug- more of an improvement proposition. Currently the snapshots of the running dir based containers doesn't freeze the container so the snapshot could become inconsistent- it does storageRsyncCopy(oldPath, newPath). Wouldn't be more safe to do- 1. initial storageRsyncCopy 2. Freeze() 3. second  storageRsyncCopy- will take up to few seconds because most of it was done in "step 1" 4. Unfreeze()

Cheers

**Comment by stgraber** [comment]
It's probably worth doing, yes.
