### ISSUE TITLE
IO Stats for container ?

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2608]
Hi,
Is there any way we can get the iostats for container running on zfs pool ?

**Comment by stgraber** [comment]
You'd have to grab that from the host. We will probably start surfacing some block I/O stats in the API soon, but surfacing fs specific metrics is unlikely to really scale for us as there are so many metrics and filesystems that we'd have to support.

**Comment by upuvvad1** [comment]
Thank you @stgraber
