### ISSUE TITLE
Snapshot scheduling

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#2610]
Hello

Is it possible to implement some extra snapshot feature (ex:  TTL on snapshot)  in order to have them automatically created and deleted when TTL expired.

For the moment i have to use "zfSnap" in crontab; a tool which add a TTL to snapshot and automatically delete the snapshot when TTL is expired.

     # Snap LXC
     0 * * * * /infra/tools/lxd_snap.sh > /tmp/cron_lxd_snap.log 2>&1

basically, it runs : 
/usr/sbin/zfSnap -s -z -a 24h -r zdata/lxd/containers

another cron at midnight to delete old snap  : /usr/sbin/zfSnap -d -s -S

Results is to have a snap per hour : 

    root@inxovh-hy002 (node2):~# ls -la /var/lib/lxd/containers/inxovh-adm001.zfs/.zfs/snapshot/
    total 0
    dr-xr-xr-x 2 root root 2 Nov 14 11:11 .
    dr-xr-xr-x 1 root root 0 Nov  7 20:50 ..
    dr-xr-xr-x 1 root root 0 Nov 14 11:57 2016-11-14_10.45.00--24h
    dr-xr-xr-x 1 root root 0 Nov 14 11:57 2016-11-14_10.46.00--1w
    dr-xr-xr-x 1 root root 0 Nov 14 11:57 2016-11-14_11.00.00--24h
    dr-xr-xr-x 1 root root 0 Nov 14 11:57 2016-11-14_11.11.00--24h

So, that means, snapshot with 24h TTL will be deleted tomorrow and the one with "1w" will be deleted in 7 days.

Using snapshot is useful *not to restore an entire container* (it almost never happens) but to restaure specific files for any reason (- bad modification, deleted by error; wrong update after a patch etc).

So, would it be possible to add a snapshot feature which integrates:

- a scheduler to plan automatic snapshot for containers
- a TTL for each snapshot
- a scheduler to plan automatic remove of old snapshot according to its TTL
- a way to restore specific files without having to to to .zfs/snapshots/files  : 

lxc snapshot <container_name> <frequency> <TTL>

ex:

    lxc snapshot inxovh-adm001  "0 * * * *" 24h
    => will add scheduler to do an hourly snap with 24h TTL for container named  inxovh-adm001 

    lxc snapshot inxovh-adm001  "0 23 * * 7" 1w
    => will add scheduler to do a snap every sunday at 23h00 for container named inxovh-adm001

Then for restore : 

    lxc restore <container_name>  <path_file_to_restore> [<path_dest>]  [<date_snapshot>]

Usage example:
                    
     lxc restore inxovh-adm001 /etc/hosts
    => it will restore the file /etc/hosts from the LAST snap

     lxc restore inxovh-adm001 /etc/hosts 2016-11-14_11.11.00
    => it will restore the file /etc/hosts from snap at the date 2016-11-14_11.11.00

    lxc restore inxovh-adm001 /etc/network/interfaces /tmp/interfaces  2016-11-12_11.11.00
    => it will restore the file /etc/hosts from snap at the date 2016-11-12_11.11.00 and copy it in /tmp/interfaces instead of original path.

This is just a thought but would add lot of value in our day to day usage of LXD.

Thanks
Regards
nico

**Comment by srkunze** [comment]
Could also solve: #2600

**Comment by davideperozzi** [comment]
Created a simple backup script with python, maybe someone finds it useful.

https://github.com/davideperozzi/lxc-simple-backup

**Comment by stgraber** [comment]
Moved this on our short term todo list.

I think we'll want to do this with three new properties for now:
 - `snapshots.schedule` which takes a cron expression
 - `snapshots.schedule.stopped` to control whether to snapshot stopped containers (defaults to false)
 - `snapshots.pattern` which takes a pongo2 template string and allows for overriding the default naming pattern (which would be considered as `snap%` where `%` represents an increasing integer)

This will get us automatic snapshotting of containers with some amount of flexibility on naming.
`snapshots.pattern` should also be used for manual nameless snapshots (`lxc snapshot c1`).

Doing it through container config options will allow for this to be set through profile for a large range of containers.

I think snapshot expiry may also be interesting to add though it can be done separately from this main piece of work. If there is interest for this part specifically, please file a separate issue about it and we'll schedule it to be implemented after this one.

**Comment by freeekanayaka** [comment]
FWIW it feels that snapshot expiry (as in having a TTL property and have LXD automatically delete snapshots that are past their TTL) is pretty much a must have once we start taking snapshots automatically, because otherwise everyone using the feature would have to implement it on his own to avoid running out of disk space?

**Comment by stgraber** [comment]
Yeah, I expect we'll do expiry shortly after this lands. For my particular use case, I don't actually need expiry but I know my use case is weird and most people will want it :)
