### ISSUE TITLE
lxc stop error

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#2612]
Hello

When stoping an LXC container; i ve regulary same error:

           lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 4
            lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 5
            lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 6
            lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 7
            lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 8
            lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 9
            lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 10
            lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 11
            lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 12
            lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 13
            lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 14
            lxc 20161115014310.586 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 28
            lxc 20161115014310.611 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/d78a9d7e97b4b375//var/lib/lxd/containers
            lxc 20161115014310.611 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
            lxc 20161115014310.611 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'inxovh-mx001' is in 'RUNNING' state
            lxc 20161115014310.611 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
            lxc 20161115014441.213 DEBUG    lxc_start - start.c:signal_handler:342 - container init process exited
            lxc 20161115014441.214 DEBUG    lxc_start - start.c:__lxc_start:1382 - Container halting
            lxc 20161115014441.214 DEBUG    lxc_start - start.c:__lxc_start:1397 - Pushing physical nics back to host namespace
            lxc 20161115014441.214 DEBUG    lxc_start - start.c:__lxc_start:1400 - Tearing down virtual network devices used by container
            lxc 20161115014441.214 WARN     lxc_conf - conf.c:lxc_delete_network:2927 - failed to remove interface 318 'eth0'
            lxc 20161115014441.214 INFO     lxc_error - error.c:lxc_error_set_and_log:55 - child <2003> ended on signal (2)
            lxc 20161115014441.214 WARN     lxc_conf - conf.c:lxc_delete_network:2927 - failed to remove interface 318 'eth0'
            lxc 20161115014441.252 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'inxovh-mx001', config section 'lxc'
            lxc 20161115014441.756 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 13 stop' for container 'inxovh-mx001', config section 'lxc'
            lxc 20161115014441.781 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 20161115014441.781 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 231072 range 65536
            lxc 20161115014442.962 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 20161115014442.962 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 231072 range 65536
            lxc 20161115014446.724 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 20161115014446.724 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 231072 range 65536
            lxc 20161115014446.737 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 20161115014446.737 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 231072 range 65536

root@inxovh-hy001 (node4):~# dpkg -l |grep lxd
ii  lxd                                  2.5-0ubuntu1~ubuntu16.04.1~ppa1     amd64        Container hypervisor based on LXC - daemon
ii  lxd-client                           2.5-0ubuntu1~ubuntu16.04.1~ppa1     amd64        Container hypervisor based on LXC - client
ii  lxd-tools                            2.5-0ubuntu1~ubuntu16.04.1~ppa1     amd64        Container hypervisor based on LXC - extra tools

thanks to help me.

regards
Nico

**Comment by brauner** [comment]
Please provide the information requested in our bug reporting template. Also, I don't see an error in the log output.

**Comment by nlienard** [comment]
Here another fresh example:

     root@inxovh-hy001 (node4):~# lxc list
     +----------------+---------+--------------------------------+------+------------+-----------+
     |      NAME      |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
     +----------------+---------+--------------------------------+------+------------+-----------+
     | cephA-003      | RUNNING | 192.168.10.245 (eth0)          |      | PERSISTENT | 0         |
     +----------------+---------+--------------------------------+------+------------+-----------+
     | inxovh-xy001   | RUNNING | 192.168.10.224 (eth0)          |      | PERSISTENT | 0         |
     +----------------+---------+--------------------------------+------+------------+-----------+

Now, i stop xy001:

     root@inxovh-hy001 (node4):~# lxc stop inxovh-xy001
     error: Container shutdown operation timed out after 30 seconds
     Try `lxc info --show-log inxovh-xy001` for more info

     root@inxovh-hy001 (node4):~# lxc info --show-log inxovh-xy001 | gist-paste
     https://gist.github.com/53fc5292462793b0148022ebadb9719c

Full stack is on   https://gist.github.com/53fc5292462793b0148022ebadb9719c

So each time i got this issue; as said previously i noticed these warning related to nic eth0:

           lxc 20161116231439.349 WARN     lxc_conf - conf.c:lxc_delete_network:2927 - failed to remove interface 338 'eth0'
            lxc 20161116231439.349 INFO     lxc_error - error.c:lxc_error_set_and_log:55 - child <31074> ended on signal (2)
            lxc 20161116231439.349 WARN     lxc_conf - conf.c:lxc_delete_network:2927 - failed to remove interface 338 'eth0'


container conf:

     root@inxovh-hy001 (node4):~# lxc config show inxovh-xy001
     name: inxovh-xy001
     profiles:
     - default
     config:
       volatile.base_image:      315bedd32580c3fb79fd2003746245b9fe6a8863fc9dd990c3a2dc90f4930039
       volatile.eth0.hwaddr: 00:16:3e:e1:ab:b4
       volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":231072,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":231072,"Nsid":0,"Maprange":65
536}]'
       volatile.last_state.power: STOPPED
       volatile.root.hwaddr: 00:16:3e:8e:01:96
       volatile.root.name: eth1
     devices:
       root:
         path: /
         type: disk
     ephemeral: false

Any help would be appreciated.

Thks

**Comment by stgraber** [comment]
Sounds like your container's init system simply isn't reacting to the shutdown signal.

Does using "lxc stop --force" fix this for you? If so, it's a problem with your image/container, not with LXD.

During normal "lxc stop", all that LXD does is signal PID 1 in the container, telling it to shutdown. If PID 1 ignores the signal or doesn't bring down the container, then you get the behavior you described above.

**Comment by nlienard** [comment]
I never use "lxc stop --force".

In fact, at the end, the container is stoped. it hangs a long time during the stop, then give the error message but it is stoped when i do after "lxc list".

The issue is when i do "lxc restart container", it generates the error message and never starts it whereas the container is stoped due to the error during stop.

These containers are very straight forward, there are all Ubuntu 16 like the hypervisor and in 80% of the time, the stop works fine. 

it is sometimes, after a long time running i guess ? Any idea ?

**Comment by stgraber** [comment]
What you're describing would be consistent with the container taking slightly more than 30s to shutdown.

**Comment by stgraber** [comment]
There is a bug in that "lxc stop" without a set timeout, shouldn't timeout after 30s, it should instead just hang there until the container is done shutting down on its own (possibly never, if the container ignores the signal).

**Comment by nlienard** [comment]
Ok so i m reaching a default timeout of 30 sec and then it failed.
but why ? as said, the container was an ubuntu 16 minimal with only ssh service.
Then when i start it again and stop it; it works fine. 
The issue appears randomly after the container is running for a while.

**Comment by srkunze** [comment]
@stgraber systemd again? #1336

Speaking of timeouts, it feels quite natural, that "lxc stop" hungs forever if no timeout is specified.
