### ISSUE TITLE
Question: Update a published image or some other High availability setup

### ISSUE THREAD

**Issue by shadycuz** [lxc/lxd#2613]
Ubuntu 16.04 LTS

driver: lxc
driverversion: 2.0.5
kernel: Linux
kernelarchitecture: x86_64
kernelversion: 4.4.0-45-generic
server: lxd
serverpid: 32040
serverversion: 2.0.5
storage: zfs
storageversion: "5"

I have a couple ubuntu 16.04 servers that I use for LXD. I wan't to create a highly available solution and I'm wondering what the best way to do this is. I had thought I could just publish an image like `lxc publish Nginx/current --alias NginxHA` and then on my other machines run `lxc image copy lxd:NginxHA local: --copy-aliases --auto-update` I have set config's for these machines so they will update the image every hour. Now if I write a script to rerun `lxc publish Nginx/current --alias NginxHA` every hour, will the downstream LXD machines continue to pull that image? Or will the fingerprint change and become an issue?

 I had also just though of creating a snapshot, pushing it to the remote LXD servers as a new container (but not starting it) and then deleting the local snapshot. 

Any thoughts?

Thanks,
Levi

edit: answered my own question `error: The image already exists: c5609842381e2fee2370e527702f2d0f09c59a384f9950cd82366d9b90bfb011`

The funny thing is... it took the time to create the image first, then issued the error. So can we get a feature that would allow you to update an image that would not effect downstream servers that have that image and are set to receive updates from it? Or do we already have this and I'm doing it wrong?

**Comment by stgraber** [comment]
That "image already exists" error, hints that you somehow managed to publish "exactly" the same thing twice, resulting in the same image fingerprint. The image fingerprint is the SHA256 of the compressed image tarball.

The rest of what you described is perfectly fine, if you do "lxc image copy" based on a source alias (as opposed to the fingerprint), the target LXD will record the source alias and update from that. So if you change the alias to point to some other image on the source server, the downstreams server will download the new image.

**Comment by shadycuz** [comment]
Hmm. I did change the image though, but only by a little. I ran touch
test.txt. I then deleted snapshot "current", remade that snapshot. Then ran
the same publish command as before which gave the error.  I then deleted
the published image, and reran the publish command which succeeded, The
root size changed by .3mb when running lxc image info. However my down
stream server didn't pick it up, even though it was subscribed to that same
alias. Oh and they finger prints are different but it still failed with the
image already exists.

Let me run through the process again tonight, document my steps better.
Maybe I did something silly. Thanks for the great blog, it's been my main
resource.

**Comment by stgraber** [comment]
Ah, the already exists may be coming from the alias already existing rather than the fingerprint.

To limit downtime, I'd recommend you do something like:
```
# Record old fingerprint
OLD=$(lxc image info new-image | grep ^Fingerprint | cut -d' ' -f2)

# Publish a new image
lxc publish Nginx/current --alias new-image
NEW=$(lxc image info new-image | grep ^Fingerprint | cut -d' ' -f2)

# Update the alias
lxc image alias delete NginxHA 
lxc image alias create NginxHA $NEW
lxc image alias delete new-image

# Remove the old image
lxc image delete $OLD
```

That's certainly not the most obvious way of doing this. The fact that we don't have a command to re-target an alias atomically should certainly be fixed as we do support that over the API.

I'm also not opposed to adding a flag to API and publish command that'd let you override an existing alias, though you'd still be left with a leftover image in your store you'd need to eventually clean, so not sure how much more convenient that'd be in the end.

**Comment by shadycuz** [comment]
Re-targeting an alias sounds like a winner. The command could be something
like lxc image update NginxHa Niginx/current. Maybe even allow fingerprint
as well or with a switch. I'm basically using it as a backup solution. I
plan on using keepalived to automate bringing up the containers on another
host should one of my lxd machines go down. I hope this becomes a feature.
I'll use the method you describe above for now.

Also when I first tried to publish a container, it complained that it was
running so I made a snapshot, but couldn't it make a  temporary snapshot
for me, then delete it after the image is published? Do it all seamless and
in the background? I'm just being picky though.

Thanks for all your hard work on this. You guys rock.

Levi

**Comment by nlienard** [comment]
personnaly, i always republish the image with the --alias parameter:

     lxc publish template-inx --alias ubuntu-xenial-infranix

it overrides the existing one.

the old one is still there but without any alias and i deleted it with its fingerprint after doing "lxc image list"

i didn't find any better way for now.

**Comment by shadycuz** [comment]
We ever get a better way to do this?

**Comment by xaoc7** [comment]
I believe that there should be other better way to update images. I' currently struggle from issue with updating images... After I publish new version of an image and then delete the old one it disappears from lxd but seems that it is still available as ZFS dataset (under zpool/containers/deleted...) and also all containers that are created from deleted image got its origin pointing to deleted image dataset. So updating an image by removing old one is leading to other issue especially when ZFS is used as a storage backend.

**Comment by stgraber** [comment]
ZFS requires the parent dataset to always exist. So when you delete a LXD image, LXD will remove the tarballs from disk and will either remove it from ZFS completely if nothing depends on it or rename it to deleted/ if something depends on it.

As soon as all containers that depend on the image are gone, so will the deleted/ image.

We don't have a choice there. If we force the deletion in ZFS, all downstream datasets would be destroyed.

So there's nothing wrong with how LXD does things, it does the best that can be done given the limitations of the various filesystems.

**Comment by xaoc7** [comment]
Yep I totally agree with you that LXD operating correctly with ZFS. Just wanted to emphasize that it will be a good idea to implement an LXD image update functionality. Especially with ZFS as a back-end storage this seems to be not so hard task. Each update can be simple snapshot which will save space and effort to manage many images in cases when images are updated regularly. And again this is only a suggestion not a complain about how LXD working :)

**Comment by stgraber** [comment]
Closing as there is nothing clearly actionable on this and workflow discussions are better handled by our forum (https://discuss.linuxcontainers.org).
