### ISSUE TITLE
please have lxd support existing zpools

### ISSUE THREAD

**Issue by dustinkirkland** [lxc/lxd#2614]
I have an existing zpool and I'd like lxd to use it.  (Feedback from the field)

**Comment by stgraber** [comment]
It's absolutely supported today.

**Comment by stgraber** [comment]
The only limitation is that you must give an unused chunk of the zpool to LXD as LXD needs to do its own refcounting without outside interference.

```
zfs create existing/lxd -o mountpoint=none
lxc config set storage.zfs_pool_name existing/lxd
```

Or tell LXD to use "existing/lxd" during "lxd init" (it requires "existing/lxd" to already exist and be empty).
