### ISSUE TITLE
Unable to start docker daemon inside the lxc container

### ISSUE THREAD

**Issue by akshaykarle** [lxc/lxd#2621]
Hello,

I started with a ubuntu 16.04.1 LTS VM, installed lxd 2.5 on it and attempted to create a docker enabled container using lxd. The container starts up fine but is unable to start the docker engine. I launched the container using the command specified in the README: 

``` $ lxc launch ubuntu:xenial my-docker-host -p default -p docker ```

I then installed the docker-engine from the instructions specified on the [docker docs](https://docs.docker.com/engine/installation/linux/ubuntulinux/). This fails and is unable to start the docker daemon. The error I'm seeing from docker is this:
```
root@docker-host:~# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2016-11-16 22:54:01 UTC; 4min 44s ago
     Docs: https://docs.docker.com
  Process: 2155 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 2155 (code=exited, status=1/FAILURE)
    Tasks: 0
   Memory: 0B
      CPU: 13ms
   CGroup: /system.slice/docker.service

Nov 16 22:54:01 docker-host systemd[1]: docker.service: Failed with result 'exit-code'.
Nov 16 22:54:01 docker-host systemd[1]: Starting Docker Application Container Engine...
Nov 16 22:54:01 docker-host dockerd[2155]: time="2016-11-16T22:54:01.216180704Z" level=info msg="libcontainerd: new containerd process, pid: 2158"
Nov 16 22:54:01 docker-host dockerd[2155]: time="2016-11-16T22:54:01.216608328Z" level=fatal msg="Failed to connect to containerd. Please make sure containerd is installed in your PATH or you have specificed the correct address. Got error: write /proc/2158/oom_score_adj: permission denied"
Nov 16 22:54:01 docker-host systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 22:54:01 docker-host systemd[1]: Failed to start Docker Application Container Engine.
Nov 16 22:54:01 docker-host systemd[1]: docker.service: Unit entered failed state.
Nov 16 22:54:01 docker-host systemd[1]: docker.service: Failed with result 'exit-code'.
Nov 16 22:54:01 docker-host systemd[1]: docker.service: Start request repeated too quickly.
Nov 16 22:54:01 docker-host systemd[1]: Failed to start Docker Application Container Engine.
```

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.1 LTS (Xenial Xerus)
 * The output of "lxc info" or if that fails:
```
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 192.168.50.4:8443
  architectures:
  - x86_64
 - i686
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-31-generic
  server: lxd
  serverpid: 1379
  serverversion: "2.5"
  storage: dir
  storageversion: ""
config:
  core.https_address: 192.168.50.4:8443
  core.trust_password: true
public: false
```

Docker version:
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

Now, I don't know if this is a problem in lxc/lxd or docker, I will continue investigating but any help would be appreciated.

**Comment by stgraber** [comment]
Only Docker coming from Ubuntu (docker.io package) works inside LXD containers.

The Docker coming from upstream is missing a number of patches to make it work, leading to the problem you describe above. We've been pushing for those changes to be merged upstream and some were, but we're not yet at a point where the upstream packages work.

**Comment by akshaykarle** [comment]
Understood. Thanks @stgraber. Got it working now. Do you think we should update the README so that others won't run into the same problem as me?

**Comment by stgraber** [comment]
Sure, I'd be fine with that.

**Comment by ayufan** [comment]
@akshaykarle Can you link to these patches?

**Comment by akshaykarle** [comment]
@ayufan https://github.com/akshaykarle/docker/tree/nesting-docker-lxc, but these are highly outdated from docker upstream now. I will see if I can get it patched over latest docker.

**Comment by stgraber** [comment]
Docker 1.13 is reported to run cleanly in LXD without any patches. So the remaining couple of patches we had have been merged upstream.

**Comment by jljouannic** [comment]
In case someone ends here, like I did, and is full of hope after reading [last comment](https://github.com/lxc/lxd/issues/2621#issuecomment-267104728).

It seems to be broken again with last Docker (Docker version 17.03.0-ce, build 3a232c8). Daemon starts, but trying to start a Docker container gives the following:

```bash
$ docker run ubuntu:16.04
Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:252: getting pipe fds for pid 555 caused \"readlink /proc/555/fd/0: permission denied\""
Error: failed to start containers: blissful_mahavira
```

Fortunately, everything is fine when installing docker from `docker.io` package

**Comment by brauner** [comment]
@jljouannic, as soon as Docker vendors a recent enough version of runC that includes a couple of fixes @cyphar has been working on then Docker upstream should be fine as well.

**Comment by jljouannic** [comment]
OK. Thanks. I will stick with the Ubuntu flavour for now :-)

**Comment by Remigius2011** [comment]
I ran on the same error than @jljouannic but I'd like to run a newer docker version than 1.12.6 (in zesty).

Is there a patched ubuntu package for docker 17.03.0-ce or at least for docker 1.13 somewhere? On which ubuntu lxd image does it run?

**Comment by Remigius2011** [comment]
another remark: the following fix mentioned in [https://stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/](url) caused hello-world to run with xenial and 17.03.1-ce, build c6d412e:

    lxc config set docker security.privileged true
    lxc restart docker

**Comment by brauner** [comment]
@Remigius2011 not however, that this will cause Docker to run in a privileged container and so turns of a bunch of security features!

**Comment by Remigius2011** [comment]
@brauner good you mention this (although I was already aware of it - it's mentioned also in the source I have cited). But this does not solve my problem. Do you know either how I can set up a docker >= 1.13 on any ubuntu distro having an lxd image? Can you elaborate on the kind of security problems this rises? Assuming I run "trusted" docker images with some own modifications (web applicateions, databases, build tools) which are not productive?

**Comment by Remigius2011** [comment]
...and is there an ETA or anything (like issue or PR) to follow for the upstream changes?

**Comment by ladams00** [comment]
Commenting to say this thread was helpful.  Thank you for the Docker blurb in the README.md

**Comment by gentunian** [comment]
We came across this issue with `lxc-vpe-2.0` and we found [this](https://www.solaris-cookbook.eu/virtualisation/proxmox/proxmox-lxc-running-docker-inside-container/) a solution to the issue.

**Comment by Remigius2011** [comment]
I don't think disabling apparmor is a good idea (nor that it is really necessary). afaik, privileged mode only (or mainly) preserves UIDs in (nested) containers - could someone please confirm or reject this?

**Comment by remingtonc** [comment]
@stgraber Any chance we can get this clarified/tracked in the [README](https://github.com/lxc/lxd#how-can-i-run-docker-inside-a-lxd-container)? Will docker-ce in its current state supposedly work in an LXD container (did not immediately for me)? Or must specifically utilize docker.io package from Ubuntu?

**Comment by stgraber** [comment]
@remingtonc last I tried (couple of days ago), current stable Docker CE worked fine in LXD containers.

**Comment by stgraber** [comment]
We also have daily testing of Docker from their git branch which has been passing every day for months. When that detects something bad, we usually send a fix or ask Docker upstream to fix whatever they broke.

**Comment by brauner** [comment]
On Tue, Dec 12, 2017 at 04:28:52PM -0800, Remington Campbell wrote:
> @stgraber Any chance we can get this clarified/tracked in the [README](https://github.com/lxc/lxd#how-can-i-run-docker-inside-a-lxd-container)? Will docker-ce in its current state supposedly work in an LXD container (did not immediately for me)? Or must specifically utilize docker.io package from Ubuntu?

Upstream Docker should work fine as @stgraber pointed out. :)

**Comment by remingtonc** [comment]
@stgraber @brauner Thanks for the clarification! I nuked my box and it did work..so something funky was going on. On a side note, in unprivileged containers Docker does not work for many images by default due to an ```overlay2``` storage driver bug with mknod etc. This is being resolved upstream. https://github.com/moby/moby/issues/35245#issuecomment-351607348
Something to watch.
