### ISSUE TITLE
mysql service fails after migration

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2625]
lxd 2.4.1
lxc 2.4.1
ubuntu 16.04

@tych0 
I am running a sysbench/OLTP benchmark on the container and doing a live migration, the mysqld service fails at destination since the sql socket was locked by the criu at the source.

Any quick fixes that can be done to this ?

**Comment by upuvvad1** [comment]
At destination,
inside the container 
cat /var/log/syslog | grep mysql

Nov 17 14:15:51 cnt33 systemd[1]: Failed to reset devices.list on /system.slice/mysql.service: Operation not permitted

**Comment by stgraber** [comment]
Error above is the usual systemd verbosity, that's not the source of the problem. So I guess that means that mysql isn't logging anything useful (at least in syslog).

**Comment by upuvvad1** [comment]
Is it something with the lxd ?

**Comment by stgraber** [comment]
That systemd error comes from the fact that unprivileged containers cannot modify their own device access list, it's a non-fatal error though and you'll see a whole bunch of those in the systemd logs during container start.

**Comment by tych0** [comment]
What do you mean "the mysqld service fails"? Can you post the output of some logs? The restore fails? Or something else happens?

**Comment by upuvvad1** [comment]
My bad,
I didn't provide the necessary information.
I am running a mysql application inside the container, and when I migrate the container, the container migration was successful without any errors either with CRIU or lxd.
However, mysql application fails at the destination machine, I mean, was unable to login to the mysql.
restarting the mysql service works, however, all the existing connections drop if I restart the service which is not we are interested at.

**Source:**

upuvvad1@r520-26:~$ lxc exec cnt26 -- systemctl status mysql
● mysql.service - MySQL Community Server
   Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2016-11-18 13:29:06 EST; 6s ago
  Process: 607 ExecStartPost=/usr/share/mysql/mysql-systemd-start post (code=exited, status=0/SUCCESS)
  Process: 605 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=0/SUCCESS)
 Main PID: 606 (mysqld)
   CGroup: /system.slice/mysql.service
           └─606 /usr/sbin/mysqld
upuvvad1@r520-26:~$ lxc exec cnt26 -- mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.15-0ubuntu0.16.04.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> ^DBye



**Destination:**

upuvvad1@r520-27:~$ lxc list 
+-------+---------+----------------------+------+------------+-----------+
| NAME  |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+-------+---------+----------------------+------+------------+-----------+
| cnt26 | RUNNING | 172.16.180.26 (eth0) |      | PERSISTENT | 0         |
+-------+---------+----------------------+------+------------+-----------+
| cnt27 | RUNNING | 172.16.180.27 (eth0) |      | PERSISTENT | 0         |
+-------+---------+----------------------+------+------------+-----------+
upuvvad1@r520-27:~$ lxc exec cnt26 -- systemctl status mysql
● mysql.service - MySQL Community Server
   Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2016-11-18 13:29:06 EST; 4min 20s ago
  Process: 607 ExecStartPost=/usr/share/mysql/mysql-systemd-start post (code=exited, status=0/SUCCESS
  Process: 605 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=0/SUCCESS)
 Main PID: 606 (mysqld)
   CGroup: /system.slice/mysql.service
           └─606 /usr/sbin/mysqld
upuvvad1@r520-27:~$ lxc exec cnt26 -- mysql -u root -p
Enter password: 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

upuvvad1@r520-27:~$ lxc exec cnt26 -- ls /var/run/mysqld/ -l
total 8
-rw-r----- 1 mysql mysql 4 Nov 18 13:29 mysqld.pid
-rw------- 1 mysql mysql 4 Nov 18 13:29 mysqld.sock.lock

upuvvad1@r520-27:~$ lxc exec cnt27 -- systemctl restart mysql
upuvvad1@r520-27:~$ lxc exec cnt27 -- ls /var/run/mysqld/ -l
total 8
-rw-r----- 1 mysql mysql 4 Nov 18 13:36 mysqld.pid
srwxrwxrwx 1 mysql mysql 0 Nov 18 13:36 mysqld.sock
-rw------- 1 mysql mysql 4 Nov 18 13:36 mysqld.sock.lock

upuvvad1@r520-27:~$ lxc exec cnt26 -- mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 4
Server version: 5.7.15-0ubuntu0.16.04.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>

**Comment by upuvvad1** [comment]
#

**Comment by tych0** [comment]
Sounds like CRIU isn't restoring the unix socket correctly. Unfortunately our management has shelved live migration until we have paying customers for it, so it's unlikely I can debug/fix this.

**Comment by stgraber** [comment]
CRIU bugs should be filed at https://launchpad.net/ubuntu/+source/criu/+filebug

As @tych0 mentioned, we unfortunately can't spend much time on those issues, but having them properly tracked on Launchpad should at least make it easier for outside contributors to look at.

**Comment by adsanz** [comment]
I know this has been close, but for those in the answer for something like this. Reinstalling mysql end up being the solution.
