### ISSUE TITLE
Wording of help texts

### ISSUE THREAD

**Issue by haarts** [lxc/lxd#2627]
At the moment I'm contributing shell completions for LXD to the fish shell project (https://github.com/fish-shell/fish-shell/pull/3554). 
In that PR a reviewer noticed some oddities with the help texts I used there. I took the first line of the `lxc help <cmd>` output as help texts.

An overview (cmd: current -> suggestion):
- delete: 'Delete containers or container snapshots.' -> 'Delete containers or snapshots.'
- finger: 'Fingers the LXD instance to check if it is up and working.' -> 'Check if the LXD instance is up.'
- restore: 'Set the current state of a resource back to a snapshot.' -> Here no suggestion, but a question: what's a resource? I think a container but I'm not sure.

All in all rather trivial I think but great documentation is not to be taken lightly. Are these worthwhile changes?

**Comment by stgraber** [comment]
resource should be replaced by "container" in that context.

And yeah, we'd certainly welcome a branch that improves those.

**Comment by haarts** [comment]
Uhm, you need to help me out a little bit here. I'm not sure what I do with the `po/*.po` files. Do I run `make update-pot`?

**Comment by stgraber** [comment]
"make i18n" will take care of updating what needs to be updated.

**Comment by haarts** [comment]
That was quick. I'll take care of it.

**Comment by haarts** [comment]
Hmmm. That doesn't seem to do anything new. Perhaps `make update-pot` was sufficient?

**Comment by stgraber** [comment]
I can't remember but maybe update-pot depends on i18n and just called it for you.

i18n updates only lxd.pot, update-pot then takes that and update all the .po files. Technically we only care about keeping lxd.pot up to date, the rest will be updated by the translators usually.

**Comment by haarts** [comment]
Everything seems in order then. Enjoy: https://github.com/lxc/lxd/pull/2628
