### ISSUE TITLE
remote copy failed

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#2637]
Same environnement as described in #2540.

I tried to copy a container to another host:

     root@inxovh-hy001 (node4):~# lxc copy inxovh-ldap002 node3:inxovh-ldap003
     error: migration dump failed
     (01.074488) Error (sk-netlink.c:73): The socket has data to read
     (01.074506) Error (cr-dump.c:1303): Dump files (pid: 31326) failed with -1
     (01.082757) Error (cr-dump.c:1600): Dumping FAILED.

When i checked on other node, the container was finally present.

FI, inxovh-ldap002 was running during the copy.

i tried to even start the container on new node3:

     root@inxovh-hy003 (node3):~# lxc list inxovh-ldap003
     +----------------+---------+------+------+------------+-----------+
     |      NAME      |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
     +----------------+---------+------+------+------------+-----------+
     | inxovh-ldap003 | STOPPED |      |      | PERSISTENT | 0         |
     +----------------+---------+------+------+------------+-----------+

the conf : 

     root@inxovh-hy003 (node3):~# lxc config show inxovh-ldap003
     name: inxovh-ldap003
     profiles:
     - default
     config:
       boot.autostart: "1"
       limits.cpu: "1"
       limits.memory: 512MB
       volatile.base_image: 315bedd32580c3fb79fd2003746245b9fe6a8863fc9dd990c3a2dc90f4930039
       volatile.eth0.hwaddr: 00:16:3e:31:5b:e9
       volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
       volatile.last_state.power: RUNNING
       volatile.root.hwaddr: 00:16:3e:2c:09:08
       volatile.root.name: eth1
     devices:
       root:
         path: /
         size: 1GB
         type: disk
     ephemeral: false

here the start:

     root@inxovh-hy003 (node3):~# lxc start inxovh-ldap003
     error: Error calling 'lxd forkstart inxovh-ldap003 /var/lib/lxd/containers /var/log/lxd/inxovh-     ldap003/lxc.conf': err='exit status 1'
       lxc 20161123132652.692 ERROR lxc_conf - conf.c:mount_rootfs:807 - No such file or directory -      failed to get real path for '/var/lib/lxd/containers/inxovh-ldap003/rootfs'
       lxc 20161123132652.692 ERROR lxc_conf - conf.c:setup_rootfs:1221 - failed to mount rootfs
       lxc 20161123132652.692 ERROR lxc_conf - conf.c:do_rootfs_setup:3631 - failed to setup rootfs for 'inxovh-ldap003'
       lxc 20161123132652.692 ERROR lxc_conf - conf.c:lxc_setup:3713 - Error setting up rootfs mount after spawn
       lxc 20161123132652.692 ERROR lxc_start - start.c:do_start:834 - failed to setup the container
       lxc 20161123132652.692 ERROR lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
       lxc 20161123132652.693 ERROR lxc_start - start.c:__lxc_start:1354 - failed to spawn 'inxovh-ldap003'
       lxc 20161123132653.259 ERROR lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
       lxc 20161123132653.259 ERROR lxc_start - start.c:lxc_fini:555 - failed to run post-stop hooks for container 'inxovh-ldap003'.

     Try `lxc info --show-log inxovh-ldap003` for more info

Full stack of show-log is https://gist.github.com/nlienard/9a1d5917164f4b31855a4ce0001206a6

Now i can't delete it on the new node 

     root@inxovh-hy003 (node3):~# lxc delete inxovh-ldap003
     error: Failed to destroy ZFS filesystem: cannot destroy 'zdata/lxd/containers/inxovh-ldap003': dataset already exists

the datavol is there : 

    root@inxovh-hy003 (node3):~# zfs list zdata/lxd/containers/inxovh-ldap003
    NAME                                  USED  AVAIL  REFER  MOUNTPOINT
    zdata/lxd/containers/inxovh-ldap003   933M  91.0M    19K  /var/lib/lxd/containers/inxovh-ldap003.zfs

     root@inxovh-hy003 (node3):~# zfs list -o name,mounted zdata/lxd/containers/inxovh-ldap003
     NAME                                 MOUNTED
     zdata/lxd/containers/inxovh-ldap003       no

what can i do to delete this container and what was wrong there ?

thanks

**Comment by tych0** [comment]
This is: https://bugs.launchpad.net/ubuntu/+source/criu/+bug/1630379

**Comment by nlienard** [comment]
I'm not running 4.8 kernel:

    root@inxovh-hy001 (node4):~# uname -a
    Linux inxovh-hy001 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

More important, i m not able to destroy the container anymore.

**Comment by tych0** [comment]
It's not specific to the 4.8 kernel, that's just where it shows up most often. The core problem is that we can't dump netlink sockets with pending data.

As for your zfs issue, it looks a little strange. Can you paste the full output of `zfs list`?

**Comment by stgraber** [comment]
Check that you don't have leftover "zfs send" or "zfs receive" processes running, that may keep your dataset busy.

**Comment by nlienard** [comment]
there is no zfs process running on these nodes.

here zfs list

root@inxovh-hy003 (node3):~# zfs list
NAME                                                                                        USED  AVAIL  REFER  MOUNTPOINT
zdata                                                                                       526G   282G    19K  /zdata
zdata/backup                                                                                 19K   282G    19K  /srv/local/backup
zdata/g_app                                                                                 539M  19.5G   539M  /srv/gluster/app
zdata/g_infra                                                                              45.2M   211M  45.2M  /srv/gluster/infra
zdata/g_iso                                                                                12.3G   282G  12.3G  /srv/gluster/iso
zdata/g_templates                                                                          2.67G   282G  2.67G  /srv/gluster/templates
zdata/images                                                                               81.3G   282G  81.3G  /srv/local/images
zdata/logs                                                                                   19K  10.0G    19K  /logs
zdata/lxd                                                                                  47.3G   282G    19K  none
zdata/lxd/containers                                                                       38.6G   282G    19K  none
zdata/lxd/containers/alpine                                                                 106K   282G  6.78M  /var/lib/lxd/containers/alpine.zfs
zdata/lxd/containers/cephA-002                                                             1.38G   282G   853M  /var/lib/lxd/containers/cephA-002.zfs
zdata/lxd/containers/inxovh-db002                                                          4.53G   282G  1.99G  /var/lib/lxd/containers/inxovh-db002.zfs
zdata/lxd/containers/inxovh-ldap003                                                          19K  1024M    19K  /var/lib/lxd/containers/inxovh-ldap003.zfs
zdata/lxd/containers/inxovh-log001                                                         3.56G  11.4G  3.36G  /var/lib/lxd/containers/inxovh-log001.zfs
zdata/lxd/containers/inxovh-mx002                                                          3.39G   282G  1.27G  /var/lib/lxd/containers/inxovh-mx002.zfs
zdata/lxd/containers/inxovh-nc001                                                          12.7G   282G  6.34G  /var/lib/lxd/containers/inxovh-nc001.zfs
zdata/lxd/containers/inxovh-nc501                                                          11.4G   282G  8.36G  /var/lib/lxd/containers/inxovh-nc501.zfs
zdata/lxd/containers/inxovh-xmpp002                                                        1.64G   366M   919M  /var/lib/lxd/containers/inxovh-xmpp002.zfs
zdata/lxd/deleted                                                                          2.04G   282G    19K  none
zdata/lxd/deleted/containers                                                                521M   282G    19K  none
zdata/lxd/deleted/containers/b9449ff0-499d-4478-a66b-479a5c25d3cd                           521M  4.49G   916M  none
zdata/lxd/deleted/images                                                                   1.53G   282G    19K  none
zdata/lxd/deleted/images/315bedd32580c3fb79fd2003746245b9fe6a8863fc9dd990c3a2dc90f4930039   667M   282G   667M  none
zdata/lxd/deleted/images/51b44706ae4e5ef0f742d2e962b33b4aef7232f8c03b660429d03419b42bb47a   430M   282G   430M  none
zdata/lxd/deleted/images/7a154406f9a361b7b8d4d0c22a6ac07a5cd4b2de532f698ece689c6e15855ff1   472M   282G   472M  none
zdata/lxd/images                                                                           6.70G   282G    19K  none
zdata/lxd/images/175dddcb03f26fd4047aee8b6bfb7e34af2bd2c84e7575df8c737b8eef999ef5          6.21G   282G  6.21G  /var/lib/lxd/images/175dddcb03f26fd4047aee8b6bfb7e34af2bd2c84e7575df8c737b8eef999ef5.zfs
zdata/lxd/images/b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7           491M   282G   491M  /var/lib/lxd/images/b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7.zfs
zdata/lxd/images/bfd17410a8c7fe6397dba3e353a23001243bc43af87acf25544d6b0ab624f9f8          6.76M   282G  6.76M  /var/lib/lxd/images/bfd17410a8c7fe6397dba3e353a23001243bc43af87acf25544d6b0ab624f9f8.zfs
zdata/mailboxes                                                                            61.7G   282G    19K  /zdata/mailboxes
zdata/mailboxes/inxovh-mx002                                                               61.7G  38.3G  61.7G  /mailboxes/inxovh-mx002
zdata/nextcloud                                                                            5.42G   282G    19K  /zdata/nextcloud
zdata/nextcloud/inxovh-nc001                                                               3.00G   282G  2.99G  /zdata/nextcloud/inxovh-nc001
zdata/nextcloud/inxovh-nc002                                                                 19K   282G    19K  /zdata/nextcloud/inxovh-nc002
zdata/nextcloud/inxovh-nc501                                                               2.42G  2.58G  2.38G  /zdata/nextcloud/inxovh-nc501
zdata/nextcloud/inxovh-nc502                                                                 19K   282G    19K  /zdata/nextcloud/inxovh-nc502
zdata/templates                                                                            5.05G   282G  5.05G  /srv/local/templates
zdata/vms                                                                                   309G   282G    19K  none
zdata/vms/alc                                                                               233G   282G    19K  none
zdata/vms/alc/alcovh-vm02                                                                  32.8G   282G  3.52G  /vms/alc/alcovh-vm02
zdata/vms/alc/alcovh-vm02/data                                                             20.9G   282G  9.95G  /vms/alc/alcovh-vm02/data
zdata/vms/alc/alcovh-vm03                                                                  56.2G   282G  3.16G  /vms/alc/alcovh-vm03
zdata/vms/alc/alcovh-vm03/data                                                             49.9G   282G  39.3G  /vms/alc/alcovh-vm03/data
zdata/vms/alc/alcovh-vm04                                                                   126G   282G  5.37G  /vms/alc/alcovh-vm04
zdata/vms/alc/alcovh-vm04/data                                                              107G   282G  69.4G  /vms/alc/alcovh-vm04/data
zdata/vms/alc/alcovh-vm51                                                                  17.8G   282G  5.75G  /vms/alc/alcovh-vm51
zdata/vms/alc/alcovh-vm51/data                                                             7.72G   282G  5.80G  /vms/alc/alcovh-vm51/data
zdata/vms/inx                                                                              1.95G   282G    19K  none
zdata/vms/inx/star                                                                         1.95G   282G  1.57G  /vms/inx/star
zdata/vms/inx/star/data                                                                     382M   282G   382M  /vms/inx/star/data
zdata/vms/vga                                                                              48.2G   282G    19K  none
zdata/vms/vga/vgaovh-vm50                                                                  48.2G   282G  2.47G  /vms/vga/vgaovh-vm50
zdata/vms/vga/vgaovh-vm50/data                                                             42.0G   282G  39.1G  /vms/vga/vgaovh-vm50/data
zdata/vms/vga/vgaovh-vm50/mysql                                                            1.56G   282G  1011M  /vms/vga/vgaovh-vm50/mysql
zdata/vms/web                                                                              26.2G   282G    19K  none
zdata/vms/web/webovh-vm01                                                                  26.2G   282G  2.81G  /vms/web/webovh-vm01
zdata/vms/web/webovh-vm01/data                                                             20.1G   282G  13.4G  /vms/web/webovh-vm01/data
zosd0                                                                                       325G   659G   325G  /var/lib/ceph/osd/ceph-2
zosd1                                                                                       383G   601G   383G  /var/lib/ceph/osd/ceph-3
root@inxovh-hy003 (node3):~#

**Comment by nlienard** [comment]
today i killed all the "lxd" process (there were a couple running) then it worked:

root@inxovh-hy003 (node3):~# lxc delete inxovh-ldap003
root@inxovh-hy003 (node3):~#
