### ISSUE TITLE
Wrong value on memory resource limit causes broken container

### ISSUE THREAD

**Issue by k-hristov** [lxc/lxd#2641]
* Distribution: Ubuntu
 * Distribution version: 16.04
 * Kernel version: 4.8.0-27-generic
 * LXD version: 2.0.5
 * Storage backend in use: zfs

I found a small bug.
I believe it is easily reproducible.
When I tried to set limit on RAM memory and in the hurry i pressed enter before giving GB and it resulted in a broken container. 

# Steps to reproduce

> lxc init images:ubuntu/xenial mycontainer
> lxc config set mycontainer limits.memory 1
> error: Invalid value: 1
> 
> lxc delete mycontainer
> error: Invalid value: 1
> 
> lxc delete mycontainer --force
> error: Invalid value: 1
> 
> lxc list mycontainer 
> +-------------+-------+------+------+------------+-----------+
> |    NAME     | STATE | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
> +-------------+-------+------+------+------------+-----------+
> | mycontainer | ERROR |      |      | PERSISTENT | 0         |
> +-------------+-------+------+------+------------+-----------+
> 
> lxc info mycontainer --show-log
> error: Invalid value: 1

It will be good if you give information about how to delete broken containers like above.

**Comment by nlienard** [comment]
i believe you have to specify the unit.

lxc config set mycontainer limits.memory 1024MB

**Comment by nlienard** [comment]
try : lxc config edit mycontainer and add the unit.

**Comment by k-hristov** [comment]
Hey, 
Thanks for the idea, but still the same issue
> lxc config edit mycontainer
> error: Invalid value: 1

**Comment by nlienard** [comment]
then go to sqlite:

    $ sqlite3 /var/lib/lxd/lxd.db
    sqlite> select * from containers;

and update the memory

**Comment by k-hristov** [comment]
Well i am trying a different approach that worked
Find container id -> Done
Find all records in containers_config related to  container_id
Get configuration id -> I confirmed it with container_id and key (limits.memory)

Result:
`2518|80|limits.memory|1
`
and finally
`sqlite> UPDATE containers_config SET value='1GB' WHERE id='2535';
`
All fine, but still it will be good if there is any input value validator.

**Comment by brauner** [comment]
This is fixed in in `LXD 2.0.6` where memory limits are properly validated.
