### ISSUE TITLE
container has now same uid/gid as hypervisor

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#2644]
Same environnement as described in #2540.

i've a container installed a while and today, it changed its uid/gid whereas is it not privileged.

    root@inxovh-hy003 (node3):~# lxc config show inxovh-mx002
    name: inxovh-mx002
    profiles:
    - default
    config:
      boot.autostart: "1"
      limits.cpu: "1"
      limits.memory: 900MB
      volatile.base_image: 315bedd32580c3fb79fd2003746245b9fe6a8863fc9dd990c3a2dc90f4930039
      volatile.eth0.hwaddr: 00:16:3e:a5:9b:2f
      volatile.eth1.hwaddr: 00:16:3e:19:ac:39
      volatile.last_state.idmap: '[]'
      volatile.last_state.power: RUNNING
    devices:
      eth1:
        name: eth1
        nictype: bridged
       parent: br_lan6
        type: nic
      opt:
        path: /usr/local/virtual
        source: /mailboxes/inxovh-mx002
        type: disk
      root:
        path: /
        size: 5GB
        type: disk
    ephemeral: false

And here the bug:

    root@inxovh-hy003 (node3):~# ls -la /var/lib/lxd/containers/inxovh-mx002.zfs/rootfs/
    total 50
    drwxr-xr-x  22 root root  22 Nov 24 23:18 .
    drwxr-xr-x   4 root root   5 Oct 25 13:44 ..
    drwxr-xr-x   2 root root 176 Nov 23 10:13 bin
    drwxr-xr-x   3 root root   3 Oct 20 18:40 boot
    drwxr-xr-x   5 root root  91 Oct 20 18:39 dev
    drwxr-xr-x 103 root root 196 Nov 24 00:00 etc
    drwxr-xr-x   8 root root   8 Nov 14 22:28 home
    drwxr-xr-x  20 root root  24 Oct 26 13:51 lib
    drwxr-xr-x   2 root root   3 Oct 26 11:36 lib64
    drwxr-xr-x   2 root root   2 Oct 20 18:36 media
    drwxr-xr-x   2 root root   2 Oct 20 18:36 mnt
    drwxr-xr-x   2 root root   2 Oct 20 18:36 opt
    drwxr-xr-x   2 root root   2 Apr 12  2016 proc
    drwx------   5 root root  11 Nov 22 11:18 root
    drwxr-xr-x   4 root root   4 Oct 20 18:39 run
    drwxr-xr-x   2 root root 226 Oct 26 11:36 sbin
    drwxr-xr-x   2 root root   2 Sep 21 19:12 snap
    drwxr-xr-x   2 root root   2 Oct 20 18:36 srv
    drwxr-xr-x   2 root root   2 Feb  5  2016 sys
    drwxrwxrwt   8 root root  10 Nov 24 23:40 tmp
    drwxr-xr-x  10 root root  10 Oct 20 18:36 usr
    drwxr-xr-x  13 root root  15 Oct 20 18:40 var

=> uid did should be very HIGH.

other container seems ok:

    root@inxovh-hy003 (node3):~# ls -la /var/lib/lxd/containers/inxovh-db002.zfs/rootfs/
    total 41
    drwxr-xr-x 22 165536 100000  22 Oct 24 22:28 .
    drwxr-xr-x  4 165536 100000   5 Oct 18 15:38 ..
    drwxr-xr-x  2 165536 100000 173 Nov 22 18:45 bin
    drwxr-xr-x  3 165536 100000   3 Oct 13 18:53 boot
    drwxr-xr-x  5 165536 100000  91 Oct 13 18:52 dev
    drwxr-xr-x 96 165536 100000 187 Nov 24 18:33 etc
    drwxr-xr-x  8 165536 100000   8 Nov 14 22:27 home
    drwxr-xr-x 20 165536 100000  23 Oct 13 18:53 lib
    drwxr-xr-x  2 165536 100000   3 Oct 13 18:49 lib64
    drwxr-xr-x  2 165536 100000   2 Oct 13 18:49 media
    drwxr-xr-x  2 165536 100000   2 Oct 13 18:49 mnt
    drwxr-xr-x  2 165536 100000   2 Oct 13 18:49 opt
    drwxr-xr-x  2 165536 100000   2 Apr 12  2016 proc
    drwx------  7 165536 100000  19 Nov 24 13:07 root
    drwxr-xr-x  4 165536 100000   4 Oct 13 18:52 run
    drwxr-xr-x  2 165536 100000 226 Oct 13 18:52 sbin
    drwxr-xr-x  2 165536 100000   2 Sep 21 19:12 snap
    drwxr-xr-x  2 165536 100000   2 Oct 13 18:49 srv
    drwxr-xr-x  2 165536 100000   2 Feb  5  2016 sys
    drwxrwxrwt  7 165536 100000   7 Nov 24 23:44 tmp
    drwxr-xr-x 10 165536 100000  10 Oct 13 18:49 usr
    drwxr-xr-x 13 165536 100000  15 Oct 13 18:52 var

On the container itself; all is good:

     root@inxovh-hy003 (node3):~# ssh inxovh-mx002
    Last login: Thu Nov 24 23:40:05 2016 from 192.168.10.3
    root@inxovh-mx002:~# ls -la
    total 35
    drwx------  5 root root    11 Nov 22 11:18 .
    drwxr-xr-x 22 root root    22 Nov 24 23:18 ..
    drwx------  3 root root     3 Nov  5 00:14 .ansible
    -rw-------  1 root root 14008 Nov 24 23:40 .bash_history
    -rw-r--r--  1 root root  3004 Nov 22 11:18 .bashrc
    drwx------  2 root root     3 Oct 25 14:34 .cache
    -rw-------  1 root root   667 Oct 25 21:37 .mysql_history
    -rw-r--r--  1 root root   148 Aug 17  2015 .profile
    drwx------  2 root root     6 Oct 25 22:12 .ssh
    -rw-------  1 root root  7639 Nov 22 10:39 .viminfo
    -rw-r--r--  1 root root    32 Oct 25 14:37 .vimrc

But the external folder  defined here were having bad uid inside container:

      opt:
        path: /usr/local/virtual
        source: /mailboxes/inxovh-mx002
        type: disk

it was the high uid did that i did setup from outside the container in the past to make it good inside the container.

And now; all was not good.

What is happening ? why is the UID /GID similar inside and outside the container ? they should be different as i didn't set privileged parameter.

I restarted the container and it doesn't change anything. same issue.

the only thing done is updating lxd this afternoon.

thanks.

**Comment by stgraber** [comment]
That's pretty concerning.

As a workaround, doing the following should fix things:
 - lxc config set inxovh-mx002 security.privileged true
 - lxc restart inxovh-mx002
 - lxc config unset inxovh-mx002 security.privileged
 - lxc restart inxovh-mx002

**Comment by nlienard** [comment]
Still the same:

    root@inxovh-hy003 (node3):~# lxc config set inxovh-mx002 security.privileged true
    root@inxovh-hy003 (node3):~# lxc restart inxovh-mx002
    Connection to inxovh-mx002 closed by remote host.
    root@inxovh-hy003 (node3):~# lxc config unset inxovh-mx002 security.privileged
    root@inxovh-hy003 (node3):~# lxc restart inxovh-mx002
    root@inxovh-hy003 (node3):~# ssh inxovh-mx002
    root@inxovh-hy003 (node3):~# ls -la /var/lib/lxd/containers/inxovh-mx002.zfs/rootfs/
    total 50
    drwxr-xr-x  22 root root  22 Nov 24 23:53 .
    drwxr-xr-x   4 root root   5 Oct 25 13:44 ..
    drwxr-xr-x   2 root root 176 Nov 23 10:13 bin
    drwxr-xr-x   3 root root   3 Oct 20 18:40 boot
    drwxr-xr-x   5 root root  91 Oct 20 18:39 dev
    drwxr-xr-x 103 root root 196 Nov 24 00:00 etc
    drwxr-xr-x   8 root root   8 Nov 14 22:28 home
    drwxr-xr-x  20 root root  24 Oct 26 13:51 lib
    drwxr-xr-x   2 root root   3 Oct 26 11:36 lib64
    drwxr-xr-x   2 root root   2 Oct 20 18:36 media
    drwxr-xr-x   2 root root   2 Oct 20 18:36 mnt
    drwxr-xr-x   2 root root   2 Oct 20 18:36 opt
    drwxr-xr-x   2 root root   2 Apr 12  2016 proc
    drwx------   6 root root  12 Nov 24 23:47 root
    drwxr-xr-x   4 root root   4 Oct 20 18:39 run
    drwxr-xr-x   2 root root 226 Oct 26 11:36 sbin
    drwxr-xr-x   2 root root   2 Sep 21 19:12 snap
    drwxr-xr-x   2 root root   2 Oct 20 18:36 srv
    drwxr-xr-x   2 root root   2 Feb  5  2016 sys
    drwxrwxrwt   8 root root  10 Nov 24 23:53 tmp
    drwxr-xr-x  10 root root  10 Oct 20 18:36 usr
    drwxr-xr-x  13 root root  15 Oct 20 18:40 var

**Comment by stgraber** [comment]
Reproduced the issue and looking into it now.

**Comment by stgraber** [comment]
Pushed a fix for this at https://github.com/lxc/lxd/pull/2643

Assuming this doesn't regress any of the new idmap stuff, I'll push the fix to Zesty and Xenial.

**Comment by stgraber** [comment]
The fix also has the nice side effect of correcting any accidentally broken containers, so long as the remapping process was never interrupted.

**Comment by stgraber** [comment]
(that is, on restart of the container, it will be remapped to the uid/gid map it should have had from the beginning)

**Comment by stgraber** [comment]
The fix for this has been merged. I'm now running a number of tests between LXD 2.0.5, 2.0.6 and 2.6 to check that it all looks good before releasing new tarballs.

**Comment by nlienard** [comment]
issue is stil present after applying new lxc release with apt

    root@inxovh-hy003 (node3):~# lxc info
    apistatus: stable
    apiversion: "1.0"
    auth: trusted
    environment:
      addresses:
      - 10.0.0.3:8443
      architectures:
      - x86_64
      - i686
      driver: lxc
      driverversion: 2.0.6
      kernel: Linux
      kernelarchitecture: x86_64
      kernelversion: 4.4.0-45-generic
      server: lxd
      serverpid: 28993
      serverversion: "2.6"
      storage: zfs
      storageversion: "5"
    config:
      core.https_address: 10.0.0.3:8443
      core.trust_password: true
     images.auto_update_interval: "0"
      storage.zfs_pool_name: zdata/lxd
    public: false


    root@inxovh-hy003 (node3):~# lxc stop inxovh-mx002
    root@inxovh-hy003 (node3):~# lxc config set inxovh-mx002 security.privileged true
    root@inxovh-hy003 (node3):~# lxc start inxovh-mx002
    root@inxovh-hy003 (node3):~# lxc config unset inxovh-mx002 security.privileged
    root@inxovh-hy003 (node3):~# lxc restart inxovh-mx002
    root@inxovh-hy003 (node3):~# ls -la /var/lib/lxd/containers/inxovh-mx002.zfs/rootfs/
    total 50
    drwxr-xr-x  22 root root  22 Nov 25 09:01 .
    drwxr-xr-x   4 root root   5 Oct 25 13:44 ..
    drwxr-xr-x   2 root root 176 Nov 23 10:13 bin
    drwxr-xr-x   3 root root   3 Oct 20 18:40 boot
    drwxr-xr-x   5 root root  91 Oct 20 18:39 dev
    drwxr-xr-x 103 root root 196 Nov 24 00:00 etc
    drwxr-xr-x   8 root root   8 Nov 14 22:28 home
    drwxr-xr-x  20 root root  24 Oct 26 13:51 lib
    drwxr-xr-x   2 root root   3 Oct 26 11:36 lib64
    drwxr-xr-x   2 root root   2 Oct 20 18:36 media
    drwxr-xr-x   2 root root   2 Oct 20 18:36 mnt
    drwxr-xr-x   2 root root   2 Oct 20 18:36 opt
    drwxr-xr-x   2 root root   2 Apr 12  2016 proc
    drwx------   6 root root  12 Nov 24 23:47 root
    drwxr-xr-x   4 root root   4 Oct 20 18:39 run
    drwxr-xr-x   2 root root 226 Oct 26 11:36 sbin
    drwxr-xr-x   2 root root   2 Sep 21 19:12 snap
    drwxr-xr-x   2 root root   2 Oct 20 18:36 srv
    drwxr-xr-x   2 root root   2 Feb  5  2016 sys
    drwxrwxrwt   8 root root   9 Nov 25 09:01 tmp
    drwxr-xr-x  10 root root  10 Oct 20 18:36 usr
    drwxr-xr-x  13 root root  15 Oct 20 18:40 var

**Comment by stgraber** [comment]
You're still on 2.6. The fix is in 2.6.2.

**Comment by nlienard** [comment]
Oh sorry.
Do you know when would 2.6.2 be release ?
Thanks again/

**Comment by stgraber** [comment]
It has been released, it's in zesty now as well as in the PPAs

**Comment by nlienard** [comment]
thanks; i confirmed it worked on mx002.
