### ISSUE TITLE
Disabling iptables rules injected by lxd networks.

### ISSUE THREAD

**Issue by EggieCode** [lxc/lxd#2647]
* Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-47-generic
   * LXC version: 2.0.5
   * LXD version: 2.5
   * Storage backend in use: btrfs

Can a feature be added to disable the iptables roles injected by LXD networking.
Now I you setup a (ufw) firewall, it will be canceld out by lxd and for example if forwards all IPv6 traffic.

**Comment by simondeziel** [comment]
Having the FORWARD rules inserted on top of the existing ruleset makes it a non-starter for our environment where we want he host to operate as a firewall restricting what containers have access to.

So being able to disable the insertion of those rules would be welcome.

**Comment by stgraber** [comment]
So that'd be just for the normal table rules, not for the nat rules then I guess?

**Comment by simondeziel** [comment]
Yes, the problematic rules for our use case are the ones inserted in the filter table.

**Comment by EggieCode** [comment]
For me, all of them. I nat/route the internet with a ansible script on UFW.
And UFW always append the roles.

**Comment by stgraber** [comment]
Ok, so I think we can add a knob to disable the generation of extra iptables rules but keep the nat ones as you can turn those off already by setting ipv4.nat and ipv6.nat to false.
