### ISSUE TITLE
lxd breaks when given invalid memory limit.

### ISSUE THREAD

**Issue by elektito** [lxc/lxd#2653]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-47-generic
   * LXC version: 2.0.5
   * LXD version: 2.0.5
   * Storage backend in use: dir

# Issue description

When an invalid value is passed for limits.memory, every other command for that container (including delete) keeps giving the same error message from then on.

# Steps to reproduce

 1. lxc launch ubuntu:14.04 foobar
 2. lxc config set foobar limits.memory 2G
     output: error: Invalid value: 2G
 3. lxc config set foobar limits.memory 2GB
     output: error: Invalid value: 2G
 4. lxc info foobar --show-log
     output: error: Invalid value: 2G
 5. lxc delete foobar
     output: error: Invalid value: 2G

**Comment by brauner** [comment]
This is fixed in new versions of `LXD`. Please update.

**Comment by stgraber** [comment]
Note that the new version fixes the check but won't fix your database which is now in an inconsistent state...

You can fix this with:

    sudo sqlite3 /var/lib/lxd/lxd.db 'UPDATE containers_config SET value="2GB" WHERE value="2G";'
