### ISSUE TITLE
disk size config not applied

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#2656]
My env is Ubuntu 16 LTS.

    root@inxovh-hy003 (node3):~# lxc info
      driver: lxc
      driverversion: 2.0.6
      kernel: Linux
      kernelarchitecture: x86_64
      kernelversion: 4.4.0-45-generic
      server: lxd
      serverpid: 26523
      serverversion: 2.6.2
      storage: zfs
      storageversion: "5"
    config:
      core.https_address: 10.0.0.3:8443
      core.trust_password: true
      images.auto_update_interval: "0"
      storage.zfs_pool_name: zdata/lxd
    public: false

I noticed on some containers, the disk size is not applied inside the container.

example:

    root@inxovh-hy003 (node3):~# lxc config show inxovh-mx002
    name: inxovh-mx002
    profiles:
    - default
    config:
      boot.autostart: "1"
      limits.cpu: "1"
      limits.memory: 900MB
      volatile.base_image:     315bedd32580c3fb79fd2003746245b9fe6a8863fc9dd990c3a2dc90f4930039
      volatile.eth0.hwaddr: 00:16:3e:a5:9b:2f
      volatile.eth1.hwaddr: 00:16:3e:19:ac:39
      volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
      volatile.last_state.power: RUNNING
    devices:
      eth1:
        name: eth1
        nictype: bridged
        parent: br_lan6
        type: nic
      opt:
        path: /usr/local/virtual
        source: /mailboxes/inxovh-mx002
        type: disk
      root:
        path: /
        size: 5GB
        type: disk
    ephemeral: false

my understanding is there is a missing zfs parameter for setting the quota to the datavol of the container.

Here zfs  output about quota and as you can see, it is set to "none" instead of 5G quota for mx002.

    root@inxovh-hy003 (node3):~# zfs list -o name,quota |grep containers/
    zdata/lxd/containers/cephA-002                                                              none
    zdata/lxd/containers/inxovh-db002                                                           none
    zdata/lxd/containers/inxovh-log001                                                           15G
    zdata/lxd/containers/inxovh-mx002                                                           none
    zdata/lxd/containers/inxovh-nc001                                                           none
    zdata/lxd/containers/inxovh-nc501                                                           none
    zdata/lxd/containers/inxovh-rdc003                                                            2G
    zdata/lxd/containers/inxovh-xmpp002                                                           2G
    zdata/lxd/deleted/containers/b9449ff0-499d-4478-a66b-479a5c25d3cd                             5G

All these listed containers has a disk size specified.

If i do "lxc config edit <container_name> and set a new value, it is applied; the quota zfs is present.

**Comment by stgraber** [comment]
I don't suppose you have a way to reproduce this?

**Comment by nlienard** [comment]
root@inxovh-hy003 (node3):~# lxc restart inxovh-mx002
    root@inxovh-hy003 (node3):~# lxc exec inxovh-mx002 bash
    root@inxovh-mx002:~# df -h
    Filesystem                         Size  Used Avail Use% Mounted on
    zdata/lxd/containers/inxovh-mx002  250G  3.2G  247G   2% /
    none                               492K     0  492K   0% /dev
    udev                                16G     0   16G   0% /dev/tty
    /dev/md1                            20G  9.3G  8.9G  52% /dev/lxd
    zdata/mailboxes/inxovh-mx002        69G   65G  3.5G  95% /usr/local/virtual
    tmpfs                               16G     0   16G   0% /dev/shm
    tmpfs                               16G  8.2M   16G   1% /run
    tmpfs                              5.0M     0  5.0M   0% /run/lock
    tmpfs                               16G     0   16G   0% /sys/fs/cgroup
    root@inxovh-mx002:~# exit
    root@inxovh-hy003 (node3):~# lxc config show inxovh-mx002
    name: inxovh-mx002
    profiles:
    - default
    config:
      boot.autostart: "1"
      limits.cpu: "1"
      limits.memory: 900MB
      volatile.base_image: 315bedd32580c3fb79fd2003746245b9fe6a8863fc9dd990c3a2dc90f4930039
      volatile.eth0.hwaddr: 00:16:3e:a5:9b:2f
      volatile.eth1.hwaddr: 00:16:3e:19:ac:39
      volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
    devices:
      eth1:
        name: eth1
        nictype: bridged
        parent: br_lan6
        type: nic
      opt:
        path: /usr/local/virtual
        source: /mailboxes/inxovh-mx002
        type: disk
      root:
        path: /
        size: 5GB
        type: disk
    ephemeral: false
    root@inxovh-hy003 (node3):~#

**Comment by stgraber** [comment]
Right, that part is expected, disk quotas are applied when you set them, not at container startup time, so restarting the container won't change anything.

What I'm interested in is a way to reproduce the issue on a clean LXD. So how to create a container that has a disk quota set but not have it actually applied.

**Comment by stgraber** [comment]
Were the affected containers migrated from another host by any chance? I wonder if that's where we may have a bug.

**Comment by nlienard** [comment]
it is possible that i created mx001 then i did "lxc move mx001 node3:mx002" for cloning but i can't be sure; i ve too many containers now but i guess yes.
I can do a test.

**Comment by stgraber** [comment]
Just did some migration tests back and forth here with a clean container on ZFS and couldn't reproduce it.

**Comment by nlienard** [comment]
i just did a lxd config edit  and modified to 7GB

and i got a different value inside:

    root@inxovh-mx002:~# df -h
    Filesystem                         Size  Used Avail Use% Mounted on
    zdata/lxd/containers/inxovh-mx002  4.5G  3.2G  1.4G  71% /
    none                               492K     0  492K   0% /dev
    udev                                16G     0   16G   0% /dev/tty
    /dev/md1                            20G  9.3G  8.9G  52% /dev/lxd
    zdata/mailboxes/inxovh-mx002        69G   65G  3.5G  95% /usr/local/virtual
    tmpfs                               16G     0   16G   0% /dev/shm
    tmpfs                               16G  8.3M   16G   1% /run
    tmpfs                              5.0M     0  5.0M   0% /run/lock
    tmpfs                               16G     0   16G   0% /sys/fs/cgroup
    tmpfs                              3.2G     0  3.2G   0% /run/user/0

**Comment by stgraber** [comment]
what does "zfs get quota zdata/lxd/containers/inxovh-mx002" give you?

**Comment by nlienard** [comment]
root@inxovh-hy003 (node3):/var/lib/lxd# zfs get quota zdata/lxd/containers/inxovh-mx002
    NAME                               PROPERTY  VALUE  SOURCE
    zdata/lxd/containers/inxovh-mx002  quota     7G     local

**Comment by stgraber** [comment]
So looks like LXD did what it was supposed to, not sure what zfs is doing though...

**Comment by nlienard** [comment]
when trying to set 5G back:

   "/tmp/lxd_editor_633982408" 45L, 1164C written
   Config parsing error: Failed to set ZFS config: cannot set property for 'zdata/lxd/containers/inxovh-   mx002': size is less than current used or reserved space

    Press enter to start the editor again

**Comment by stgraber** [comment]
Do you have any snapshots for that container? maybe they're the one using the space difference.

**Comment by nlienard** [comment]
oh yes i ve plenty

root@inxovh-hy003 (node3):/var/lib/lxd# zfs list -t snapshot |grep inxovh-mx002 | wc -l
56

**Comment by nlienard** [comment]
ok so, when the 5GB of quota are not enough for the container, the limit goes away ?

**Comment by nlienard** [comment]
root@inxovh-hy003 (node3):/var/lib/lxd# zfs list -o space zdata/lxd/containers/inxovh-mx002
   NAME                               AVAIL   USED  USEDSNAP  USEDDS  USEDREFRESERV  USEDCHILD
   zdata/lxd/containers/inxovh-mx002  1.34G  5.66G     2.54G   3.12G              0          0

**Comment by stgraber** [comment]
Well, LXD doesn't do any of that, all it does is set quota=7GB in ZFS which it did properly as you saw above.

It's ZFS which is showing you that 4.5G disk space, not LXD. As ZFS snapshots are tied to the dataset, it'd make sense for them to count towards the quota, restricting the effective disk space available to the container.

**Comment by stgraber** [comment]
I think this is the reason why we have the option to use refquota instead of quota for ZFS quotas.
My understanding is that ZFS refquota effectively ignores disk usage by related datasets (snapshots) and only uses direct disk usage by the main dataset towards the quota.

**Comment by stgraber** [comment]
You can change LXD to use refquota instead of quota by:
 - Remove the disk quota from all your containers
 - Confirm with "zfs list -t all -o name,quota" that none of the container still has a quota applied
 - lxc config set storage.zfs_use_refquota true
 - Re-apply all of your disk quotas

Once you do that, the "quota" ZFS property will remain unset (none) but the "refquota" ZFS property will be set instead, which may better match what you want.

**Comment by nlienard** [comment]
lxc config set storage.zfs_use_refquota true <== it is a global parameter ? i mean it will be applied for all containers?

**Comment by nlienard** [comment]
i checked another container, and i do confirm, it is due to snap size, the quota parameter goes away.

**Comment by stgraber** [comment]
Yes, it tells LXD to use "refquota" rather than "quota" for all ZFS operations from that point on. Which is why if you want to switch to it, you need to first unset quotas from all containers to avoid ending up with both quota and refquota being set on some existing containers.

**Comment by nlienard** [comment]
ok i got it. thanks for the explanation. i'll apply this operation tomorrow morning, i need sleep now.
i guess you can close this issue. 
thanks again !
