### ISSUE TITLE
Question: how to migrate lxc containers to lxd

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#2660]
HI,

right now I´m using about 20 containers on Ubuntu 14.04 with just `lxc`
I do want to upgrade my host to xenial and lxd but I dont know how to migrate the containers to lxd?
Sorry if this question was asked before.
Thank you

**Comment by brauner** [comment]
Hi, we have a script in this repository that will help you with that. It's called `lxc-to-lxd` and is located under the `scripts` folder in this repository. It needs to run as root and you can just pass it the names of the `LXC` containers which you'd like to convert to `LXD` managed containers. It also provides the option of converting all your `LXC` container to `LXD ` managed containers. Moving an existing `LXC` container to a `LXD` managed container should be as simple as:

```
chb@conventiont|~/source/go/src/github.com/lxc/lxd/scripts|master $=
> sudo ./lxc-to-lxd yak3
==> Processing container: yak3
Parsing LXC configuration
Checking for existing containers
Validating container name
Validating container mode
Validating container rootfs
Processing network configuration
Processing environment configuration
Processing container boot configuration
Processing container apparmor configuration
Processing container seccomp configuration
Processing container SELinux configuration
Processing container capabilities configuration
Processing container architecture configuration
Creating the container
Container is ready to use

==> Migration summary
yak3: SUCCESS
```
Note though that your container must be stopped to move them from `LXC` to `LXD` managed containers.

**Comment by huegelc** [comment]
Thank you!

**Comment by arthur-e** [comment]
This script no longer seems to be in the `scripts` folder. Has it been deprecated? What is the best way to migrate `lxc` containers to `lxd` today?

**Comment by vrubiolo** [comment]
Finding this ticket as I am looking for information as well.

There seems to be a dedicated binary now in charge of doing this migration: https://github.com/lxc/lxd/tree/master/lxc-to-lxd.

Here is some information on how to build and use it: https://discuss.linuxcontainers.org/t/exporting-from-lxc-and-importing-to-lxd/2823
