### ISSUE TITLE
lxc-to-lxd migration fails

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#2663]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu
 * Distribution version: xenial
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use: dir

apiextensions: []
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 172.16.246.133:666
  - 10.0.3.1:666
  - 10.231.98.1:666
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
xxxxxxxxx
    -----END CERTIFICATE-----
  certificatefingerprint: xxxxxx
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-47-generic
  server: lxd
  serverpid: 4076
  serverversion: 2.0.5
  storage: dir
  storageversion: ""
config:
  core.https_address: '[::]:666'
  core.trust_password: true
public: false

# Issue description

A brief description of what failed or what could be improved.

# Steps to reproduce

 1. Step one
stop running lxc container `lxc-stop -n test`
 2. Step two
start migration script
`/lxc-to-lxd.py`
 3. Step three
Watch the error:
```root@ubuntu:~# ./lxc-to-lxd.py test
==> Processing container: test
Parsing LXC configuration
Checking for existing containers
Validating container name
Validating container mode
Validating container rootfs
Processing network configuration
Processing environment configuration
Processing container boot configuration
Processing container apparmor configuration
Processing container seccomp configuration
Processing container SELinux configuration
Processing container capabilities configuration
Processing container architecture configuration
Creating the container
Traceback (most recent call last):
  File "./lxc-to-lxd.py", line 474, in <module>
    container_name, args)
  File "./lxc-to-lxd.py", line 387, in convert_container
    container_create(lxd_socket, new)
  File "./lxc-to-lxd.py", line 104, in container_create
    raise Exception("Failed to define container: %s" % resp["error"])
Exception: Failed to define container: json: cannot unmarshal number into Go value of type string
```

**Comment by brauner** [comment]
Do you have `LXD` running?

**Comment by huegelc** [comment]
yes
```root@ubuntu:~# service lxd status
● lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: active (running) since Mon 2016-11-28 22:37:45 CET; 36min ago
     Docs: man:lxd(1)
 Main PID: 4076 (lxd)
    Tasks: 11
   Memory: 11.3M
      CPU: 326ms
   CGroup: /system.slice/lxd.service
           ├─4076 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           └─7694 [lxc monitor] /var/lib/lxd/containers alicefrank

Nov 28 22:37:45 ubuntu systemd[1]: Starting LXD - main daemon...
Nov 28 22:37:45 ubuntu lxd[4076]: t=2016-11-28T22:37:45+0100 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
Nov 28 22:37:45 ubuntu systemd[1]: Started LXD - main daemon.
```

**Comment by stgraber** [comment]
Can you run with --debug?

**Comment by stgraber** [comment]
(The lxc-to-lxd script that is)

**Comment by stgraber** [comment]
Looking through the code, I found one codepath that could explain the error above, but only if you had a MTU set on the device entry in your LXC config.

Anyway, running the script with --debug would let me know for sure.

**Comment by stgraber** [comment]
Sent a pull request with the fix I was talking about, marked it as closing this issue, hopefully that's right. If not, we can re-open and fix whatever's the source of your issue.

**Comment by huegelc** [comment]
I´ll provide the `-debug` output this evening.

**Comment by huegelc** [comment]
Interestingly it happens only with flockport (https://www.flockport.com/) lxc´s

**Comment by huegelc** [comment]
You were right: it was the mtu config line
`lxc.network.mtu = 1500`
which caused the issue. I´ve commented out that line and the migration worked.

**Comment by stgraber** [comment]
Cool, or just use the current version with my fix: https://github.com/lxc/lxd/blob/master/scripts/lxc-to-lxd

**Comment by huegelc** [comment]
Great, thank you!
