### ISSUE TITLE
"Bad key: storage.lvm_vg_name"

### ISSUE THREAD

**Issue by Shantira** [lxc/lxd#2666]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-47
   * LXC version: 2.0.5
   * LXD version: 2.0.5
   * Ansible version: 2.2
   * LVM version: 2.02.133
  
# Issue description

Hello I got **"msg": "Bad key: storage.lvm_vg_name"** in Ansible when tried to run lxd container with attached lvm storage. In my playbook I have next parameters: 
```
storage.lvm_thinpool_name: testers
storage.lvm_vg_name: lxd_group
storage.lvm_volume_size: 1G
```
On the server, where it testing result of the command _vgscan_:

> Reading all physical volumes.  This may take a while...
> Found volume group "test4-vg" using metadata type lvm2
> Found volume group "lxd_group" using metadata type lvm2

Partition on which located this vg has 5GB of size, but it`s not a problem, otherwise the error will be different.
What interesting if not pointing  _storage.lvm_ parameters then all works fine, but this is logical.
Also I tried to create LVM thin pool manually, as it presents in your code and all was successfully.

# Steps to reproduce

 1. First need to create vg group with any name, which then paste into playbook`s task.
 2. Next you could use code from my playbook task:
`- name: Install lxd on server
  apt: name=lxd state=present update_cache=yes cache_valid_time=3600
  notify: start lxd
- name: Creating lxd container
  lxd_container:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    architecture: x86_64
    ephemeral: false
    config:
      limits.cpu: "{{ item.cpu_number }}"
      limits.memory: "{{ item.memory_number }}"
      storage.lvm_thinpool_name: testers
      storage.lvm_vg_name: "lxd_group"
      storage.lvm_volume_size: 1G
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: 16.04/amd64
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 30
  with_items: "{{ lxd }}"`

And variables:

`lxd:
  - name: testcontainer
    state: started
    cpu_number: 1
    memory_number: 512MB`

And playbook:

`- hosts: all
  roles:
    - lxd
  become: True`
 3. Try to run this on Ubuntu 16

**Comment by brauner** [comment]
This sounds like you tried to set this key on a single container. However, this is a server configuration key.

**Comment by stgraber** [comment]
Yep, here's a quick test on LXD 2.0.5:

```
stgraber@shell01:~$ lxc config set storage.lvm_vg_name abc
error: LVM volume group 'abc' not found
stgraber@shell01:~$ lxc config set test storage.lvm_vg_name abc
error: Bad key: storage.lvm_vg_name
```

**Comment by stgraber** [comment]
I did that on a machine without LVM support, but it still shows a rather different error and confirms that the error string you're getting is from trying to apply a daemon config option to a container.

This may be an Ansible LXD bug, I'm not sure exactly how you're setting this key. But since it's clearly not a LXD bug, I'm closing this issue.

Feel free to respond with more details anyway, it may be very helpful to other users!

**Comment by Shantira** [comment]
Thanks for the answer, yes, it looks like Ansible bug, cause I've tried to run this parameters not for a container and it's not possible. Only one way to run this:
```
 - lxd_container:
     name: test
     source: some parameters
     config:
       storage.lvm_thinpool_name: testers
       storage.lvm_vg_name: "lxd_group"
       storage.lvm_volume_size: 2G
```
But then this directive will run according to the container with name "test". And as result we will get the error "Bad key".
Could you tell me where I should write about this bug to Ansible developers team?
