### ISSUE TITLE
Question: How can I mount a hosts block device into an LXD container?

### ISSUE THREAD

**Issue by sklosedr** [lxc/lxd#2667]
How can I mount a hosts block device into an LXD container?

I only found examples how to mount Hosts Directory into the container.

The only way I could figure out is to mount a block device ```sdb```  to the Host Server (Mount path ```/mnt/postgres01```) and then add it to the container with:

```
sudo lxc config device add postgres2 sdb disk source=/mnt/postgres01 path=ssd_drive
```

can you please provide an example how to mount the ```sdb``` device into the container directly without a mounting first to the host (or at least suggest a path for the mount dir on the host)

**Comment by stgraber** [comment]
If the source is a block device, lxd will have the kernel mount it for you. So exact same syntax but set source= to point to the block device path.

**Comment by stgraber** [comment]
```
root@castiana:~# truncate -s 10G abc.img

root@castiana:~# mkfs.ext4 abc.img
mke2fs 1.43.3 (04-Sep-2016)
Discarding device blocks: done
Creating filesystem with 2621440 4k blocks and 655360 inodes
Filesystem UUID: ed35c695-f2ba-491a-8307-84b851e4b565
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done
Writing inode tables: done
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done

root@castiana:~# losetup -f abc.img

root@castiana:~# losetup -a
/dev/loop0: [0023]:2535034 (/root/abc.img)

root@castiana:~# lxc config device add abc my-disk disk source=/dev/loop0 path=/mnt/abc
Device my-disk added to abc

root@castiana:~# lxc exec abc -- df -h
Filesystem                Size      Used Available Use% Mounted on
encrypted/lxd/containers/abc
                        167.3G      4.4M    167.3G   0% /
none                    492.0K         0    492.0K   0% /dev
udev                      9.7G         0      9.7G   0% /dev/fuse
udev                      9.7G         0      9.7G   0% /dev/net/tun
df: /sys/kernel/debug/tracing: Permission denied
/dev/nvme0n1p2           25.0G      5.3G     19.4G  21% /dev/lxd
/dev/nvme0n1p2           25.0G      5.3G     19.4G  21% /dev/.lxd-mounts
udev                      9.7G         0      9.7G   0% /dev/null
udev                      9.7G         0      9.7G   0% /dev/zero
udev                      9.7G         0      9.7G   0% /dev/full
udev                      9.7G         0      9.7G   0% /dev/urandom
udev                      9.7G         0      9.7G   0% /dev/random
udev                      9.7G         0      9.7G   0% /dev/tty
tmpfs                     1.9G     52.0K      1.9G   0% /run
/dev/loop0                9.8G     36.0M      9.2G   0% /mnt/abc
```

**Comment by sklosedr** [comment]
Thanks for quick reply.  I run ubuntu on gce an added a disk which I can see as "sdc"

root@gruen-lxd-docker:/var/lib/lxcfs# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
..
sdc      8:32   0   10G  0 disk 

What ist the "source= to point to the block device path"??

**Comment by stgraber** [comment]
source=/dev/sdc

**Comment by sklosedr** [comment]
I created ist as "blank"  Is formatting necessary?

**Comment by stgraber** [comment]
Note that you obviously need to create a filesystem on it first, assuming gce gave you a blank block device.

**Comment by sklosedr** [comment]
I formated the device conforming to google
```https://cloud.google.com/compute/docs/disks/add-persistent-disk```

The it works in a privileged container.
```lxc launch ubuntu:xenial <container name> -c security.privileged=true```


I an unprivileged container (default) I dont have access:
```root@skltest01:/# cd ssd_drive2/
root@skltest01:/ssd_drive2# mkdir test
mkdir: cannot create directory 'test': Permission denied```

Is there a way to use it in an unprivileged container???

Best regards
Stefan

**Comment by pcdummy** [comment]
@sklosedr thats a normal permission problem, mount it on the host then chown it to your needs.

like:

    chown 100000:100000 /mnt/<your-gce-disk-mountpath>/

Then mount it again into the container.

**Comment by stgraber** [comment]
Oh yeah, forgot to show that in my example. You indeed need to either chown the root of the fs so that the container owns it or you need to chmod it so everyone can write to it.

Anyway, sounds like we've covered this question, so closing the issue.

**Comment by butla** [comment]
@pcdummy @stgraber Is there an elegent way of getting the user ID to use with chown? I've used [this stackoverflow answer](https://askubuntu.com/a/742527/238067) to determine that the ID I should use is 165536. And from what I see, all the containers are using the same ID.

**Comment by stgraber** [comment]
@butla containers aren't guaranteed to share the same ID. The "security.idmap.isolated" setting if set will actually make sure that they do not.

One trick that usually works so long as the container filesystem is mounted is to look for the owner of /var/lib/lxd/containers/NAME/rootfs. Otherwise the only really reliable way is to grab the container map using "lxc config show" (volatile.last_state.idmap) but that can get pretty complex.

**Comment by butla** [comment]
@stgraber thanks!
