### ISSUE TITLE
lxc file push seems broken

### ISSUE THREAD

**Issue by mpadge** [lxc/lxd#2668]
This re-opens #2557 from @davidfavor

Issue is Dist independent (see #2557).

# Issue description

Push appears to work according to both client and daemon debug logs--both return Status 200---yet pushed files *do not appear* in the container.

# Steps to reproduce

1. Do a fresh install of entire ubuntu system (16.04)
2. `lxd init` - tried in both `zfs` and `dir` modes
3. `sudo lxc file push <file> my-container/tempdir`

`lxd` daemon debug output:
```
DBUG[11-30|00:05:33] handling                                 method=GET url=/1.0 ip=@
DBUG[11-30|00:05:33]
        {
                "type": "sync",
                "status": "Success",
                "status_code": 200,
                "metadata": {
                        "api_extensions": [],
                        "api_status": "stable",
                        "api_version": "1.0",
                        "auth": "trusted",
                        "config": {
                                "core.trust_password": true,
                                "storage.zfs_pool_name": "lxd"
                        },
                        "environment": {
                                "addresses": [],
                                "architectures": [
                                        "x86_64",
                                        "i686"
                                ],
                                "certificate": "-----BEGIN CERTIFICATE-----(blah blah blah)
-----END CERTIFICATE-----\n",
                                "driver": "lxc",
                                "driver_version": "2.0.5",
                                "kernel": "Linux",
                                "kernel_architecture": "x86_64",
                                "kernel_version": "4.4.0-47-generic",
                                "server": "lxd",
                                "server_pid": 19770,
                                "server_version": "2.0.5",
                                "storage": "zfs",
                                "storage_version": "5"
                        },
                        "public": false
                }
        }
DBUG[11-30|00:05:33] handling                                 method=POST url="/1.0/containers/my-container/files?path=junk" ip=@
DBUG[11-30|00:05:33]
        {
                "type": "sync",
                "status": "Success",
                "status_code": 200,
                "metadata": {}
        }
```
As mentioned, status code with both client and daemon debug is 200, yet files do not appear in container. (`core.trust_password` is `true` because i also tried [this](https://github.com/lxc/lxd#hacking) to no avail.) Any assistance greatly appreciated!

**Comment by tych0** [comment]
Does tempdir exist? It might be that we don't handle the case correctly when you don't specify `-p` but the directory doesn't exist.

**Comment by mpadge** [comment]
Yeah, `tempdir` exists. That's just a flag to avoid thinking the problem might be with pushing to to the root dir (which doesn't work either).

**Comment by stgraber** [comment]
@tych0 this is 2.0.5, no such thing as -p or -r there.

Are you running the file push immediately after the container is started?

We've had people run into such issues where they were pushing to /tmp of a container that was still booting and they didn't know that there is an init script running inside their container which wipes /tmp during boot.

So LXD was doing its job, putting the file in /tmp, just for the init system in the container to then remove it half a second later :)

**Comment by mpadge** [comment]
Nope, I don't think that's it either. I've also made sure I'm pushing to a non-ambiguous dir name (not `/tmp`). Container is running, all is okay, but still no file gets pushed. 

Thanks for the responses, and I hope we can get to the bottom of this

**Comment by stgraber** [comment]
Can you please include:
 - ```lxc info``` (no arguments)
 - ```lxc config show <container name>```
 - The exact "lxc file push" command you're running

**Comment by mpadge** [comment]
Thanks so much for taking this issue seriously - I really appreciate it! I'll get that to you within the hour (am on a different machine right now with currently broken `lxd` -- my fault).

**Comment by mpadge** [comment]
```
~$ sudo lxc info
apiextensions: []
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    (... blah blah blah ...)
    -----END CERTIFICATE-----
  certificatefingerprint: 03b9fc2881207d1801e1cbcfebf1856af18430dfdaf5c6bad429e86f8410599c
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-47-generic
  server: lxd
  serverpid: 2566
  serverversion: 2.0.5
  storage: zfs
  storageversion: "5"
config:
  core.trust_password: true
  storage.zfs_pool_name: lxd
public: false

~$ sudo lxc config show my-container
name: my-container
profiles:
- default
config:
  volatile.base_image: b9cba741ef621f14e6e8c306c7f87637a59d7d09c1a3ec8ef717ab0d6e43430a
  volatile.eth0.hwaddr: 00:16:3e:6e:dc:7c
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
devices:
  root:
    path: /
    type: disk
ephemeral: false
```
Note in regard to `lxc file push` that the container only has one directory, `/tempdir` and both of these commands
```
~$ sudo lxc file push file.dat my-container/tempdir
~$ sudo lxc file push file.dat my-container/otherdir
```
generate the same `lxd debug` output given above - they both return `Status: 200` messages, even though the second one pushes to a non-existent directory and ought not succeed. Every other aspect of the daemon debug output is identical in both cases.

This works as expected:
```
~$ sudo lxc file push file.dat my-container/tempdir/
error: open: Not a directory
errno: 20
```

**Comment by stgraber** [comment]
Ok, so I just setup a similar environment, that is, LXD 2.0.5 on Ubuntu 14.04 with LXC 2.0.5.

```
root@djanet:~# lxc info
apiextensions: []
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFwTCCA6mgAwIBAgIQCyxpTqDyiFNKEh4k0xfXdTANBgkqhkiG9w0BAQsFADA0
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QGRq
    YW5ldDAeFw0xNjEyMDEwMzI5MDBaFw0yNjExMjkwMzI5MDBaMDQxHDAaBgNVBAoT
    E2xpbnV4Y29udGFpbmVycy5vcmcxFDASBgNVBAMMC3Jvb3RAZGphbmV0MIICIjAN
    BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA9/j8z9VsysNRwKCyPGo24vJRX4nV
    r1tEepQ2KlPyJu5tUOO9D6xvjz8i8lVRUgL6BpXZsbGJoKwznJYB6XX1tk7Ecb9C
    BtC/PJtVqw4yj8YqY33QbGNMq4q5NMQFuv1eoTZRZyDo2AqsaNVBRK+3N6YLXsvW
    tqxoVGbI8xRvxvXqRh/oweajO2lMZjyxylTwKwV0QhuLGy5IL3vJ6V6Ui9rU4Dpo
    xvX/MY1uap6Z4PXZnlzNHmzpqy8vH3aC8qncHx6c7xmoXJpbrGFzgEd+VxNwmyfc
    wPLVaO7PYLm8m+ZmmW9/PnH6cQc4nruAuhmQMU1vQvnEV4bil2j7FGlzU6KoR3IO
    m7BY07xOFmitPxHYJbijRelIul172CJiuuy8wqvtnGNpQ683D64Zf44Ek5ERKu9V
    lU2Td5h+XJBGuQOvmqQd6ZOAR3JGJG5lb0UVYpTKzvek8tg8Kn9wn4NVvAGPkTze
    KjT7ta14DSOs0xJFHVEnK1CxqW7h10xx0gczMmmc3LwdTgSBEtDevj2BdqHnkHUc
    Yeo2xgYTtiQgzNDOR0kqsHS5oK1y99VworJulN79+CjsNx1d0ltm8GiodxGRdytZ
    Pw6f5Ol4GbfGQJUIRQd45G069i4LsgVV2mWeY87fEOvS/i2VzRRwHtE5SpR6HWir
    sgDQhCacvtvlQocCAwEAAaOBzjCByzAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAww
    CgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADCBlQYDVR0RBIGNMIGKggZkamFuZXSC
    DjE3Mi4xNy4xNi41LzI0gikyNjA3OmYyYzA6ZjAwZjoyNzE2OjIyMzo4YmZmOmZl
    ZjM6ZDZiNC82NIIbZmU4MDo6MjIzOjhiZmY6ZmVmMzpkNmIyLzY0ghxmZTgwOjo2
    MGRkOjNlZmY6ZmU3MTo0YTA1LzY0ggpmZTgwOjoxLzY0MA0GCSqGSIb3DQEBCwUA
    A4ICAQCpmIf+a7+QnaVriIex2axZZvQSMiylR1iq3jKgPyuRSQtzl2dXX/r6o0Te
    Za+XgktYL2D4HJX8VQykr7MT3SQB+cUxsfNiNh5iC6cwEFf4I01p9Kq7PRKFzwDe
    JLG2hncchfjHX4InAiNzBGuTRh0IaTfl4zAT2sz4VwFbYsQyiSuTLoiFJbCgCfIN
    eNYoB5A+GLImYTHTdCWSH/cnJygAwR32qy5yS9yzoqwEBiUOVpPN79qO8TnCR2d+
    r3IfIEn+TRb+T1A6RxDg9PZpnvvt5wPxbA85WEOBMO++XUOpKFxsbIgtQlRpcM39
    poNkTRwjA2dfSnXkXBVvD3YHfqoGCAWikRZeswW0EB5geKThaJawQTZBvNwYvhp5
    qIrhpv1ziQ/WVECKvmBDl6jBL/hSKhnwWnD9KWcirLErIRNuHQyxGPxP02iziS2Z
    vIVmjDR1GhgJc7J7oGPY53He5a2Abk8Rqegky4TyVsL8PhSHDZnP8a7owo7TISt8
    iA9GLYZNG/Pei4smJUc27BL92KHjRkfvh7QQraAS4y2ULBvCg6lh1lTedxHX2hLE
    8d1xvujj6nWGYAq7ZPnvpqL7MvBbJOCcsBLLzGgwKniXaZj5/gpFGBFubasOBQr4
    miqLNO9wzOBGnTZDADxhOxa6qa3ZBKyx34fkW+Jq9ViikWdUkQ==
    -----END CERTIFICATE-----
  certificatefingerprint: 848bed59702ec0ae2136f6a02fa1aec48a2d5692b6364af6aec4544f50ca1015
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-51-generic
  server: lxd
  serverpid: 17739
  serverversion: 2.0.5
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd
public: false
```

Now, for the most basic file handling:

```
root@djanet:~# lxc launch ubuntu:16.04 my-container
Creating my-container
Starting my-container
root@djanet:~# echo blah > file.dat
root@djanet:~# lxc file push file.dat my-container/tmp/
root@djanet:~# lxc exec my-container -- cat /tmp/file.dat
blah
```

So that works as expected. Now if I push it to a path which doesn't exist:

```
root@djanet:~# lxc file push file.dat my-container/tempdir
root@djanet:~# lxc exec my-container -- cat /tempdir
blah
```

It simply assumes that this is the filename to use, which is similar to what "cp" would do. Unless you force it to assume it's a directory:

```
root@djanet:~# lxc file push file.dat my-container/tempdir1/
error: open: No such file or directory
errno: 2
```

And lastly, if you want to rename the in your target directory:

```
root@djanet:~# lxc file push file.dat my-container/tmp/blah
root@djanet:~# lxc exec my-container -- cat /tmp/blah
blah
```

Now, what's a bit odd and feels like a bug to me is that pushing to "/tmp" (or any other directory which exists), WITHOUT a trailing /, fails with:

```
root@djanet:~# lxc file push file.dat my-container/tmp
error: open: Is a directory
errno: 21
```

That part is inconsistent with what "cp" would do as "cp" would consider this to be equivalent to "/tmp/" and so just create "/tmp/file.dat".


So except for this last case, which does at least provide a clear error message (despite being wrong), everything else appears to behave properly to me.

**Comment by stgraber** [comment]
Ok, so for the discrepancy in behavior with "cp" when pushing a file to "/tmp" (as opposed to "/tmp/"), we unfortunately can't fix this because the LXD daemon doesn't have access to the source filename.

The current logic is that if you push to "/tmp/", the client tool will append the source filename and send "/tmp/file.dat" to the server. If you pass "/tmp" the client doesn't know that this is a directory and so won't append "/file.dat" to the string, causing the path error on the server with no way to recover from it.


So what I'll be sending instead is a fix to return a much improved error:

```
stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc file push file.dat test/tmp
error: Path already exists as a directory

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc file push file.dat test/tmp/
stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$
```

**Comment by tivrfoa** [comment]
Hi. So, the message improved, but I think it could be better, otherwise I would not be here. xD
Maybe: error: Path already exists as a directory. Use a trailing '/', eg: /tmp/

But I got:
Error: Path already exists as a directory: **File too large**
This **File too large** message is really strange Oo
