### ISSUE TITLE
Question: The proper way to backup and restore lxc container

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#2669]
Hi,

I´m looking for a proper way to backup and restore lxc (LXD) containers in case of disaster (hardware failure etc)
Right now my setup consists of two Ubuntu trusty machines with "pure" lxc containers (without LXD) and looks like this:

---[LXC-Host Backup]----(Internet)-----[ISP]-----[LXC-Host Production]----
             <-----------------------rsync------------------|

The backup strategy is to stop the running container and take a backup of /var/lib/lxc/<name> with rsnapshot which then I rsync to my backup host. Now, because rsnapshot/rsync transfers only deltas the downtime of every container is about 5 to 10 secs, which is fine for me. 
On the backup host I have a similar configuration (bridge etc) where I can just start the container right away. So far so good.

Now I want to migrate this LXC containers to LXD (I´ve done a test migration and it works like a charm) . The question is, how the backup strategy is gonna look like? Should I keep the rsnapshot/rsyc way and backup all /var/lib/lxd ? Do snapshots and transfer them via remote copy to the backup host? Or publish images of snapshots? Is there a better/efficient approach?

Thank you

**Comment by stgraber** [comment]
If you're using the directory backend, then yes, just keep /var/lib/lxd in sync the same way you did for LXC.

If you're using btrfs or zfs as the storage backend, then you'll probably want to sync those through their native backup tools (send/receive) and then send what's in /var/lib/lxd separately.

We also just merged some work by @tych0 (to be in LXD 2.7) which will dump a serialized version of the container config to a file in the container storage volume. With this feature you can simply backup the zfs/btrfs storage using send/receive and there will be a new "lxd import" command to load it back into the target LXD.

**Comment by huegelc** [comment]
Thank you for your reply. Yes, I´m using dir as backend.
As I could see, with LXD I can create snapshots without taking the container down. 
Is it safe to backup only the snapshot after one initial backup of the container itself?

**Comment by tomposmiko** [comment]
@stgraber 
> If you're using the directory backend, then yes, just keep /var/lib/lxd in sync the same way you did for LXC.

Also make sure the uid of user 'lxd' is the same on both host machine, am I right?

**Comment by stgraber** [comment]
@tomposmiko the "lxd" user doesn't really matter, but you want to make sure that the uid/gid allocation for the root user is the same, yes.

@huegelc LXD indeed lets you snapshot running containers. We do it atomically when using lvm/btrfs/zfs and for the dir backend, we freeze all tasks temporarily. Note that this doesn't mean that all the processes will have written their data to disk, but it will at least guarantee that nothing changes while the snapshot is being made.

**Comment by huegelc** [comment]
@stgraber great, thank you.
