### ISSUE TITLE
Question: How to convert an privileged container into an privileged one?

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#2671]
Hi,
I´m about to migrate all lxc (privileged) containers to lxd. Thanks to @stgraber this works well.
As I use lxc since the (almost) beginning, all containers created by lxc were privileged as they are after I migrate them to lxd. Is there a way to convert them into unprivileged ones? 
Thank you

**Comment by brauner** [comment]
`lxc config set $CONTAINER_NAME security.privileged false` or maybe just `lxc config unset $CONTAINER_NAME security.privileged`. And then restart the container.

Can you show the output of `lxc config show $CONTAINER_NAME` for one of those imported containers?

**Comment by huegelc** [comment]
@brauner this is great! I changed the config `lxc config set $CONTAINER_NAME security.privileged false` and it worked. All uid/gid of the container are set properly. 
Thank you!

**Comment by brauner** [comment]
Ok, closing this then. :)
