### ISSUE TITLE
Feature: bwlimit option on rsync processes 

### ISSUE THREAD

**Issue by nakatadim** [lxc/lxd#2678]
Hi,

this is more of a proposal for a feature. During snapshots of dir based containers, as expected rsync tries its best to occupy all the IO resources which can be a trouble. Now that snapshots are consistent due to the "initial rsync->freeze->second rsync->unfreeze" i believe rsync can safely run with --bwlimit if set- for example with "lxc config set XXXXX". creating a cgroup for rsync with limited blkio doesn't work smoothly + blkio.weight tend to work only for CFQ io elevator- same is for ionice. So the best place to control this is as a parameter of rsync. What do you think?

Cheers,
Atanas

**Comment by stgraber** [comment]
@nakatadim from the manpage, it says taht bwlimit applies to the socket, which implies it will only ever be used when transferring over a socket (as in, over the network), not when merely copying files on the local disk.

**Comment by nakatadim** [comment]
hey, just made a test with local file copy with rsync- the file is 512M zeroed. Looks like bwlimit works on local fs too:
```
root@atanasdimitrov-ThinkPad-E550:/home/atanasdimitrov# time rsync -av **--bwlimit=10000** testfile testfile2
sending incremental file list
testfile

sent 537,002,103 bytes  received 35 bytes  10,228,612.15 bytes/sec
total size is 536,870,912  speedup is 1.00

**real	0m52.671s**
user	0m2.696s
sys	0m2.812s
root@atanasdimitrov-ThinkPad-E550:/home/atanasdimitrov# rm -f testfile2
root@atanasdimitrov-ThinkPad-E550:/home/atanasdimitrov# sync && echo 3 > /proc/sys/vm/drop_caches
root@atanasdimitrov-ThinkPad-E550:/home/atanasdimitrov# time rsync -av **--bwlimit=50000** testfile testfile2
sending incremental file list
testfile

sent 537,002,103 bytes  received 35 bytes  46,695,838.09 bytes/sec
total size is 536,870,912  speedup is 1.00

**real	0m10.711s**
user	0m2.452s
sys	0m2.692s
```

**Comment by stgraber** [comment]
Interesting. We can probably add a new "storage.dir_rsync_bwlimit" option to use in such cases.

**Comment by nakatadim** [comment]
Sounds nice
