### ISSUE TITLE
Implement projects

### ISSUE THREAD

**Issue by jseguillon** [lxc/lxd#2689]
Hi all, 
I have a genuine question : i'd like to get a bit more fine grained control on people being linked to my lxd daemon.

If i understand well, if someone has a valid authent plus admin password, he can do anything on the daemon (delete anything, create anything, change daemon config, etc..). 

I'd like to find an mechanism to put some limits on some kind of groups (ex : users can snaphsot and copy, only real admins can delete, etc...). I first thought something like a ManInTheMiddle would be an approach but i guess lxc client is protected against those attacks... 

Who could propose a viable option for implementing this ? Maybe a fork of lxd daemon, emptied, and linked to user/role system. Any proxy that could magicaly do the stuff ? 
Or should i PR a feature with some possibility to add plugins to lxd daemon ? 

Thank you.

**Comment by stgraber** [comment]
We don't have immediate plans for multi-tenancy and fine grained API access control in LXD. This may change over the next year or so though as it's not an uncommon request, but it's certainly a tricky one that will require a lot of thinking about.

I think for now, your best option is probably to run a small daemon of your own which exposes the normal LXD API but restricts what any particular client certificate can do.

That'd be a fine approach until we spend the time to spec the details of multi-tenancy and access control in LXD.

**Comment by stgraber** [comment]
Keeping this github issue around as a way to track future work in LXD proper.

**Comment by aarnaud** [comment]
+1 Good things to add this in the future for LXD's API. Thanks @stgraber

**Comment by ajd394** [comment]
+1 I also feel the multi tenancy is would be a great feature!

**Comment by stgraber** [comment]
Renaming this issue to have it focus on a multi-user experience with user groups too.

**Comment by n0guest** [comment]
+1 for this feature request.

**Comment by stgraber** [comment]
So we're ready to start working on this with it hopefully landing in 3.5/3.6.
Here's the current spec I have for this work.

# Introduction
## Current state of things and limitations
Even though LXD supports external authentication, it doesn’t currently have any concept of resource ownership.

Multiple users connecting to a LXD daemon all see the exact same view of containers, images, networks, profiles, storage pools, ...

## Proposal
LXD projects will effectively be a way to get a clean slate on an existing LXD, where you can create containers without having to avoid name conflicts. In the initial implementation, projects will hold containers, images and profiles. Networks and storage may come at some point later but will likely be restricted to software defined network and storage.

### REST API
New API parameter ?project=NAME (similar to ?target=NAME for clusters), relevant for:
 - /1.0
 - /1.0/containers
 - /1.0/images
 - /1.0/profiles

New API at /1.0/projects:

 - GET /1.0/projects: List all project URLs
 - GET /1.0/projects?recursion=1: List all project information
 - POST /1.0/projects: Define a new project
 - GET /1.0/projects/NAME: Get the project information
 - POST /1.0/projects/NAME: Rename the project
 - PUT /1.0/projects/NAME: Update the project
 - PATCH /1.0/projects/NAME: Update the project
 - DELETE /1.0/projects/NAME: Delete the project

Update /1.0
 - Add a project field reporting the current project

Update /1.0/certificates
 - An alternate default project can be set for a given certificate

### Command Line
New “lxc project” subcommand:

 - lxc project create: Create a new project
 - lxc project delete: Delete an existing project
 - lxc project edit: Edit project configuration
 - lxc project list: List all projects (and show the current one)
 - lxc project rename: Rename a project
 - lxc project show: Show project information
 - lxc project switch: Switch the active project

The active project will be stored as part of the remote configuration in the client
For consistency “lxc remote set-default” will be renamed to “lxc remote switch” (with backward compatibility alias for “lxc remote set-default”)

### Default setup
By default a “default” project will be defined and used, keeping the normal LXD workflow absolutely identical to today’s until such point as the user decides to create a new project.

All new installations start with only an empty “default” profile in them.

### Project features
Projects will have features that can be enabled or disabled on a per-project basis so long as the project is empty at the time. Disabling a feature will have the project show the data from the “default” project instead.

All projects will always have their own containers, feature flags will initially be available for:
 - images
 - profiles

New projects will default to having all features enabled.

### Upgrade story
A “default” project will always be defined on all LXD instances and that project will automatically become the owner for any existing objects during the upgrade. CLI and API behavior will remain absolutely identical so long as the user doesn’t use projects, making the upgrade process seamless.

# Implementation details
## Behavior
 - The upgrade from current LXD must not require a series of container restarts.
 - Deleting a project will only be possible if it’s empty.
 - Changing project features also require the project be empty.

## System setup
### AppArmor
Pattern for default project: `lxd-<name>_<LXD path>`
Pattern for other projects: `lxd-<project>_<name>_<LXD path>`

### CGroups
Pattern: `/sys/fs/cgroup/<controller>/lxd/<project>/<name>`

### Storage
Pattern for default project: `storage-pools/<pool>/containers/<name>`
Pattern for other projects: `storage-pools/<pool>/projects/<project>/containers/<name>`

## Database
We’ll need a new “project” table to track the projects and we’ll need to add a project_id column to the containers, images and profiles tables.

## Image handling
Projects will be allowed to hold images and the same image may effectively end up in multiple projects.
The on-disk artifacts will be the same so long as the image fingerprint is the same, so there’s no need to namespace/duplicate those (/var/lib/lxd/images and per-storage-pool volumes).

What will be unique is the DB entries for the images, image aliases and image properties.

We will only get rid of the on-disk artifacts when no projects reference them. Image auto-update will therefore work per-project using the same logic we have today, when the last project gets updated, the refcount will hit 0 for the image artifacts and we’ll flush them from disk.

## Go client API
At the Go API level, we’ll be introducing new symbols for:

 - GetProjectNames() (names []string, err error)
 - GetProjects() (projects []api.Project, err error)
 - GetProject(name string) (project *api.Project, ETag string, err error)
 - CreateProject(name string) (err error)
 - DeleteProject(name string) (err error)
 - RenameProject(name string, project api.ProjectPost) (op Operation, err error)
 - UpdateProject(name string, project api.ProjectPut) (err error)
 - UseProject(name string) (client ContainerServer)

Effectively using a workflow similar to the cluster target one where we can just call UseProject(name) to get a new client instance which targets a different project.

**Comment by stgraber** [comment]
@freeekanayaka My branch at https://github.com/stgraber/lxd/tree/projects has the following implemented:
 - Documentation
 - Database changes
 - LXD project API
 - Go client API
 - CLI support

It's effectively missing:
 - Actual database filtering based on projects
 - Conflict handling (fs level mostly)
 - Integration tests

Assigning this to you so you can pick up the database part of this with the goal to have something we can finalize during the sprint in Brussels (ideally just dealing with fs conflicts at that point).

**Comment by stgraber** [comment]
A few more things we need to consider with this branch:

## storage volumes
At this time, projects don't have a storage component to them, so they don't themselves hold storage pools or storage volumes.

So at this point, the APIs for storage pools and those controlling custom storage volumes will remain global.

The difficulty comes with the "container" and "image" storage volume types as the owner of those volumes may belong to a project.

As a result, when interacting with storage volumes, only the container volumes for the project should be shown and same goes for images when the image feature is enabled on the project.

## logging
As there may now be duplicate containers, images and profiles, log entries which include any of:
 - container name
 - image fingerprint
 - image alias name
 - profile name

Should also have the project name in their logging context.

## events
The `lifecycle` and `operation` type events need to be filtered for the current project to avoid spamming clients with irrelevant messages. That means that the functions emitting those two event types must require a project id be passed and the event handling code need to filter out events based on the recorded project id for the listener.

At this time `logging` events will go unfiltered. We may decide to either filter those too or just turn off logging events for the non-default profile down the line.

## operations
As hinted above wrt events, we need operations to be tie-able to a project.
A number of operations are global, affecting all projects and so shouldn't have the project field set, but operations that are tied to a container, image or profile which is part of a project need to be marked as such so we can properly mark the events and can also filter the list of visible operations to only include the global ones + the project-specific ones.

**Comment by stgraber** [comment]
@freeekanayaka
