### ISSUE TITLE
"name" isn't a valid "source" key

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#269]
Currently lxc and lxd pass around "name" at container creation in the source map.

"name" isn't a valid field there, please use "fingerprint" or "alias".

**Comment by tych0** [comment]
I think the right fix here is to use "name" as in the original spec. The client doesn't know whether we're creating from an image or an alias, it just passes a string to the server which then creates things.

**Comment by stgraber** [comment]
well, the problem is that the server doesn't know either. You could set a sha256 as an alias for another image.

**Comment by stgraber** [comment]
So I tend to prefer the API being explicit and any random guessing happening on the client tool rather than have the server make a guess behind the scene.

**Comment by tych0** [comment]
Sure, except didn't we decide yesterday that delete of a container would delete all its snapshots too? I don't mind having it one way or the other (the server doing guessing or the client), but we should figure out which :)

**Comment by stgraber** [comment]
I'm not sure how the two relate. Snapshots from an API point of view are under /1.0/containers/\<name\>/snapshots so it seems reasonable that a DELETE of /1.0/containers/\<name\> also removes any snapshot as they'd otherwise not be accessible through the API.

Aliases and fingerprints from an API point of view are two completely different things, the first lies in /1.0/images/aliases/ and the later directly in /1.0/images/

The fact that either can be passed for the same argument of the command line (instead of requiring a prefix as I was proposing back in CPT) is a pure client decision which shouldn't be reflected in the API.

**Comment by tych0** [comment]
On Thu, Feb 26, 2015 at 08:47:38AM -0800, St�phane Graber wrote:
> I'm not sure how the two relate. Snapshots from an API point of view are under /1.0/containers/\<name\>/snapshots so it seems reasonable that a DELETE of /1.0/containers/\<name\> also removes any snapshot as they'd otherwise not be accessible through the API.

Seems to me like this is a distinction without a difference. Whatever,
I'll make the change after I'm done with this patch.
