### ISSUE TITLE
Disable Transparent Huge Page Support

### ISSUE THREAD

**Issue by alejosv** [lxc/lxd#2690]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 16.04.1 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-51-generic
   * LXC version: 2.6.2
   * LXD version: 2.6.2
   * Storage backend in use:

# Issue description
I am using a lxc image of Ubuntu 16.04, I installed a mariadb 10.0 server. I am trying to enable the TokuDB engine with instructions from the following site: [https://mariadb.com/kb/en/mariadb/enabling-tokudb/#check-for-transparent-hugepage-support-on-linux](https://mariadb.com/kb/en/mariadb/enabling-tokudb/#check-for-transparent-hugepage-support-on-linux)

For this, I need to disable Transparent HugePage support on the operating system. The commands that need to be executed are with the root user, but the O.S of the container indicates to me "permission denied".

# Steps to reproduce

 1. Step one
     You can check the status of Transparent Hugepages as follows:
     `cat /sys/kernel/mm/transparent_hugepage/enabled`
     If the path does not exist, Transparent Hugepages are not enabled and you may continue.
     Alternatively, the following will be returned:
     `always madvise [never]`
     indicating Transparent Hugepages are not enabled and you may continue. If the following is returned:
     `[always] madvise never`
     Transparent Hugepages are enabled, and you will need to disable them.

 2. Step two
     To disable them, pass "transparent_hugepage=never" to the kernel in your bootloader (grub, lilo, etc.). For example, for SUSE, add `transparent_hugepage=never` to Optional Kernel Command Line Parameter at the end, such as after "showopts", and press OK. The setting will take effect on the next reboot.
     You can also disable with:
     `echo never > /sys/kernel/mm/transparent_hugepage/enabled`
     `echo never > /sys/kernel/mm/transparent_hugepage/enabled`
 3. Step three
     Reboot

# Information to attach

 - [X] any relevant kernel output (dmesg)
     dmesg | grep "huge" 
     [    0.027478] Initializing cgroup subsys hugetlb
 - [X] container log (lxc info NAME --show-log)
     Name: serverdb
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Creation: 2016/12/04 16:55 UTC
State: Running
Type: persistent
Profiles: default
PID: 25927
Ips:
  eth0:	inet	10.129.226.144	vethTQTBV8
  eth0:	inet6	fd42:b490:9b1:f25c:216:3eff:fee2:6c88	vethTQTBV8
  eth0:	inet6	fe80::216:3eff:fee2:6c88	vethTQTBV8
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Procesos: 27
  CPU usage:
    CPU usage (in seconds): 4
  Memory usage:
    Memory (current): 19.79MB
    Memory (peak): 164.39MB
  Network usage:
    eth0:
      Bytes received: 31.94kB
      Bytes sent: 3.31kB
      Packets received: 196
      Packets sent: 35
    lo:
      Bytes received: 0 bytes
      Bytes sent: 0 bytes
      Packets received: 0
      Packets sent: 0

Registry:
            lxc 20161205193551.593 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:265 - Seccomp: failed to resolve syscall: .
            lxc 20161205193551.593 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:266 - This syscall will NOT be blacklisted.
            lxc 20161205193551.593 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:265 - Seccomp: failed to resolve syscall: .
            lxc 20161205193551.593 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:266 - This syscall will NOT be blacklisted.
            lxc 20161205193551.885 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 25921, expected pid 25927.
            lxc 20161205193559.503 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:265 - Seccomp: failed to resolve syscall: .
            lxc 20161205193559.503 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:266 - This syscall will NOT be blacklisted.
            lxc 20161205193559.503 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:265 - Seccomp: failed to resolve syscall: .
            lxc 20161205193559.503 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:266 - This syscall will NOT be blacklisted.
 - [X] main daemon log (/var/log/lxd.log)
     Empty
 - [ ] output of the client with --debug
 - [X] output of the daemon with --debug
     DBUG[12-05|20:32:07] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_extensions":["storage_zfs_remove_snapshots","container_host_shutdown_timeout","container_syscall_filtering","auth_pki","container_last_used_at","etag","patch","usb_devices","https_allowed_credentials","image_compression_algorithm","directory_manipulation","container_cpu_time","storage_zfs_use_refquota","storage_lvm_mount_options","network","profile_usedby","container_push","container_exec_recording","certificate_update","container_exec_signal_handling","gpu_devices","container_image_properties","migration_progress","id_map"],"api_status":"stable","api_version":"1.0","auth":"trusted","config":{},"environment":{"addresses":[],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\nMIIFYjCCA0qgAwIBAgIRAMRg3DuPGxZeCEgJWT5UkpAwDQYJKoZIhvcNAQELBQAw\nPzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEfMB0GA1UEAwwWcm9vdEBh\nbGUtSW5zcGlyb24tMzU1ODAeFw0xNjEyMDIwMDI4MTlaFw0yNjExMzAwMDI4MTla\nMD8xHDAaBgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxHzAdBgNVBAMMFnJvb3RA\nYWxlLUluc3Bpcm9uLTM1NTgwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC\nAQCa/uIPIa98rii39fyyI0WPY+Id9+HMDD2BDfjhZ1+dzMxhpbM2/tjNUnAkSlJd\n0i8ylpif1jltTBVVWNWSOT5NfUNHo298Dtzg8cd7Hr2adkwEp9RqL63cnVh4AvCh\nRzeJXm/6SM9e1PWQovaUN6MekPg6PViN0sXfrVqA89XnZRj8nopsjqpneblV9voI\n+VW34wCm6WKeAcuh3YVbJTgI3xS0zmF5lqywC/IXrFeochTulSFu5Agl9igcMjyw\nm5amruQado3fmOzl6GrMzNgv2bDPQkhcG6Y41/PcwXTdEpRzKZKjFB0cazmKzFL3\nRb5l/NAGCKlS0RRIWpiR+Upzmb5NbMTUTdF2ZVRqed5dZI29O7zskEWtTCNYR+AP\ngAs/hGX/diPIQ6wc9XiB+rRhY9DXSojm6q9pCLFfLTDuw+Oxe4a77Hnz2uaHeBTu\n24B0rKYSVZatbHkWGxuHG0uZjmcxFP6LroQuqctHYwOSA8VTK8TKOB+RiSO82zcr\n/WipL/M2q5LT45dVDjYIfgD5zxsIRj/e7UxMpySoiptoacKMrQufx2Xpk8YChTA2\nO6slNHRQYejo9pVqaNUHhIZCDyJjbaK8LKCxvEvNfUj6NXMQw5jn5yu04en1YVBw\nbzdB1eVfyG2FzhG3cM6/hIYWrdSUIixUmwvkQ3RdbQIVsQIDAQABo1kwVzAOBgNV\nHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAi\nBgNVHREEGzAZghFhbGUtSW5zcGlyb24tMzU1OIcEwKgBjTANBgkqhkiG9w0BAQsF\nAAOCAgEAhdzLMwQhsDh3aCOUD/Y9QCtF9q3PHTg8QpkDbHIjF9k84jUx6xOxRhNI\nUXnUC1Ht+GLUBKtBZL2fZA+ghztNwhbG1ClqV57VapPlKyWobExcFeGhv8jY42jR\nTgCA6gRntFV1KEPTlYqLXrzs0LJLipPTVATD8e+CloS3Cc6fKn2+W4ReMvH4FyKh\naGvYRPAz04RJJp3j+XeSmE3ORHiyB1u6sn78Jp8d/3ApiRr0q0usNPjITj+srBYu\nJ/ujKtVHPM/zZZgHjaEUwo1gsQjEuqJcrvokNIpPRGdvx09Zd2vbF+hGhlZKfHQc\n/NYmgJ5ODzN28BLqKWDKh5OpR+VezQuCkxmquBBUJMuR4SdL63oZTb622kJjCjOH\nnm1GpFLuMihUggV4DG+xToN66vAQUNifC1U0Zd6ewjoh7Wv/HqqfjAqAblhHK6SM\n83QgVx8APLxXj7FIQu30duP/nyrK5MZn3Qqq3Ao6jvz4ZUBnCOVfC9mAolMlbIvV\nff3XXlqlM01f6RyiEeJpZeV2CaFJjB+PEVu4H5zKORaq6MjwQC3suNqjkmdIEWyH\nDdjCOWOkkEelPpHi3TxKHwe8EJYd91RPcjK9WU1msn29zVKcIKwvAeIbTH7dZdcu\ntGzYaMvejdUDnzP+Z/X2tAD4o8yDgDzfp6VwZttwe6fidrlRPQs=\n-----END CERTIFICATE-----\n","driver":"lxc","driver_version":"2.0.6","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.4.0-51-generic","server":"lxd","server_pid":3167,"server_version":"2.6.2","storage":"dir","storage_version":""},"public":false}}
 
DBUG[12-05|20:32:07] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"architecture":"x86_64","config":{"image.architecture":"amd64","image.description":"ubuntu 16.04 LTS amd64 (release) (20161130)","image.label":"release","image.os":"ubuntu","image.release":"xenial","image.serial":"20161130","image.version":"16.04","volatile.base_image":"fc6d723a6e662a5a4fe213eae6b7f4c79ee7dd566c99856d96a5ca677a99b15d","volatile.eth0.hwaddr":"00:16:3e:e2:6c:88","volatile.eth0.name":"eth0","volatile.idmap.base":"0","volatile.idmap.next":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]","volatile.last_state.power":"STOPPED","volatile.root.hwaddr":"00:16:3e:6d:ab:95","volatile.root.name":"eth1"},"created_at":"2016-12-04T16:55:01Z","devices":{"root":{"path":"/","type":"disk"}},"ephemeral":false,"expanded_config":{"image.architecture":"amd64","image.description":"ubuntu 16.04 LTS amd64 (release) (20161130)","image.label":"release","image.os":"ubuntu","image.release":"xenial","image.serial":"20161130","image.version":"16.04","volatile.base_image":"fc6d723a6e662a5a4fe213eae6b7f4c79ee7dd566c99856d96a5ca677a99b15d","volatile.eth0.hwaddr":"00:16:3e:e2:6c:88","volatile.eth0.name":"eth0","volatile.idmap.base":"0","volatile.idmap.next":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]","volatile.last_state.idmap":"[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]","volatile.last_state.power":"STOPPED","volatile.root.hwaddr":"00:16:3e:6d:ab:95","volatile.root.name":"eth1"},"expanded_devices":{"eth0":{"nictype":"bridged","parent":"lxdbr0","type":"nic"},"root":{"path":"/","type":"disk"}},"last_used_at":"2016-12-06T01:35:51.506332909Z","name":"serverdb","profiles":["default"],"stateful":false,"status":"Stopped","status_code":102}}
 
DBUG[12-05|20:32:07] Putting {"action":"start","force":false,"stateful":false,"timeout":0}
 to http://unix.socket/1.0/containers/serverdb/state 
DBUG[12-05|20:32:07] Raw response: {"type":"async","status":"Operation created","status_code":100,"metadata":{"id":"fed17294-538e-4d47-913f-c3176db4e51a","class":"task","created_at":"2016-12-05T20:32:07.144774267-06:00","updated_at":"2016-12-05T20:32:07.144774267-06:00","status":"Running","status_code":103,"resources":{"containers":["/1.0/containers/serverdb"]},"metadata":null,"may_cancel":false,"err":""},"operation":"/1.0/operations/fed17294-538e-4d47-913f-c3176db4e51a"}
 
DBUG[12-05|20:32:07] 1.0/operations/fed17294-538e-4d47-913f-c3176db4e51a/wait 
DBUG[12-05|20:32:07] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"id":"fed17294-538e-4d47-913f-c3176db4e51a","class":"task","created_at":"2016-12-05T20:32:07.144774267-06:00","updated_at":"2016-12-05T20:32:07.144774267-06:00","status":"Success","status_code":200,"resources":{"containers":["/1.0/containers/serverdb"]},"metadata":null,"may_cancel":false,"err":""}}

**Comment by stgraber** [comment]
That's because transparent huge page support is a global kernel knob, so you can't change it from inside a container or for just a container.

You must change it as root on the host and that will affect everything running on the machine.

It doesn't look like the hugetlb cgroup lets you do that per-container either, so this is simply something the Linux kernel doesn't let you do on a per-container/cgroup today.
