### ISSUE TITLE
Unable to perform any actions on containers (start,stop,delete,etc.)

### ISSUE THREAD

**Issue by hmobrienv** [lxc/lxd#2698]
Distribution: Ubuntu
Distribution version: 16.04 LTS
The output of "lxc info" or if that fails:
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  certificatefingerprint: 049610a3a6b846155d45934451f6c1799484362921daef354f76e0cca9e82e55
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-47-generic
  server: lxd
  serverpid: 29746
  serverversion: 2.0.8
  storage: dir
  storageversion: ""
config: {}
public: false

Kernel version: 4.4.0-51-generic
LXC version: 2.0.5
LXD version: 2.0.5
Storage backend in use: zfs

Issue:
Using the REST api, sent a PUT request to /1.0 that was meant to be sent to /1.0/container/<name>/state and overwrote my server's configuration file. All containers are now stuck in error state. Unable to start, delete, stop any of the containers.

New containers are unaffected. 

Any commands on affected containers return "error: ZFS isn't enabled"

**Comment by stgraber** [comment]
Sounds like you managed to unset storage.zfs_pool_name. Setting that one back to the name of your ZFS pool should fix things.

I'm a bit surprised that the daemon let you unset it though... it's supposed to return an error if unsetting the zfs_pool_name key while containers are still using it. Maybe it's got to do with wiping the whole config clean somehow...

**Comment by stgraber** [comment]
so "lxc config set storage.zfs_pool_name NAME" should get you back to a working state. You may also want to restart your daemon after that (systemctl restart lxd) just for good measure.

**Comment by hmobrienv** [comment]
Setting the storage.zfs_pool_name back to its original pool name is now producing "error: provided ZFS pool (or dataset) isn't empty".

**Comment by stgraber** [comment]
Gah, because obviously the check kicks in properly when attempting to set it back, but not when unsetting... wouldn't be fun any other way.

Ok, so DB surgery it is:

    sqlite3 /var/lib/lxd/lxd.db 'INSERT INTO config (key,value) VALUES ("storage.zfs_pool_name", "NAME");'

(obviously replacing NAME for whatever your pool name is)

**Comment by hmobrienv** [comment]
That fixed it. Thank you!

**Comment by stgraber** [comment]
Re-opening to track the fix to the LXD API so that unsetting such a key can't happen in the future.
