### ISSUE TITLE
Make it possible to route additional subnets to LXD managed bridges

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#2701]
This problem has been around ever since I began using LXD. Today I can finally reproduce the problem. This is most certainly an Ubuntu package update problem + need to understand how to fix it. Currently only fix is reboot.

1) Working Ubuntu + LXD running several containers.

2) Do a simple package update. Exact update from this morning...

/usr/bin/aptitude upgrade
The following packages will be upgraded: 
  lxd lxd-client lxd-tools php7.0-cli php7.0-common php7.0-json php7.0-opcache php7.0-readline python3-distupgrade ubuntu-release-upgrader-core

All packages update successfully.

3) At this point systemctl shows both services lxd + lxd-containers both stopped + restarted successfully.

4) lxc info --show-log $container - shows all containers are functional.

5) Problem: private IPs 10.0.119.xxx are pingable + public IPs are all dead.

Inside container both 10.0.119.xxx are pingable + public IPs are pingable.

Outside container (on host) public IPs are all dead (100% packet loss).

This occurred on one machine this morning + I went through the exact same upgrade process on a 2nd machine + all public IPs died on 2nd machine too.

My guess is an LXD networking guru will know exactly how to fix this + maybe how to reconfigure Ubuntu (systemd maybe?) so LXD containers survive simple updates.

Thanks.
________
Setup details.

net12 # lxd --version 
2.6.2

net12 # lsb_release -sc
yakkety

```
net12 # lxc list
+--------------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
|           NAME           |  STATE  |              IPV4              |                     IPV6                      |    TYPE    | SNAPSHOTS |
+--------------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
| ja1-discover-free-ebooks | RUNNING | 10.0.119.202 (eth0)            | fd42:9a2b:d62f:7e98:216:3eff:fe5f:db43 (eth0) | PERSISTENT | 0         |
|                          |         | 144.217.33.225 (eth0)          |                                               |            |           |
+--------------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
| yakkety                  | RUNNING | 10.0.119.85 (eth0)             | fd42:9a2b:d62f:7e98:216:3eff:fe36:18 (eth0)   | PERSISTENT | 0         |
|                          |         | 144.217.33.224 (eth0)          |                                               |            |           |
+--------------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
```

Machine setup per https://github.com/lxc/lxd/issues/2534 previous discussion.

**Comment by davidfavor** [comment]
Additional detail.

Inside container, /etc/init.d/networking stop correctly deassigns/unconfigures IPs, so lxc list shows no IPs assigned. /etc/init.d/networking start correctly brings up both local + public IPs + systemctl status networking shows networking restart was successful.

**Comment by davidfavor** [comment]
More about problem source.

During normal upgrades of lxd, the related service is cycled (stopped/restarted).

It appears Linux networking has enough intelligence now to auto-magically drop broken routes as they become broken... Notice my manual/static route disappears after service cycle.

```
net12 # ip -4 route add 144.217.33.224/27 dev lxdbr0
net12 # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         149.56.27.254   0.0.0.0         UG    0      0        0 eth2
10.0.119.0      0.0.0.0         255.255.255.0   U     0      0        0 lxdbr0
144.217.33.224  0.0.0.0         255.255.255.224 U     0      0        0 lxdbr0
149.56.27.0     0.0.0.0         255.255.255.0   U     0      0        0 eth2
net12 # systemctl restart lxd
net12 # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         149.56.27.254   0.0.0.0         UG    0      0        0 eth2
10.0.119.0      0.0.0.0         255.255.255.0   U     0      0        0 lxdbr0
149.56.27.0     0.0.0.0         255.255.255.0   U     0      0        0 eth2
```

**Comment by stgraber** [comment]
Yeah, so as I said in the other issue, that's because LXD re-applies the network config on startup. It does that in case the system is somehow partly configured or broken due to a bug in a previous LXD release.

So anything that's done outside of LXD will effectively be reset, which includes that extra route.

We should allow for additional routes to be defined through the LXD API so that LXD can track those properly.


Until then, your best bet is to move your custom route from wherever you're setting it now to a local systemd unit which triggers on After=lxd.service, meaning that it will be executed every time the LXD daemon starts/restarts.

**Comment by davidfavor** [comment]
Got it.

If you're doing After=lxd.service processing on your machines, drop me a copy of the systemd file + I'll give it a try.

Thanks.

**Comment by davidfavor** [comment]
If you don't have one, I'll write one + post a copy.

**Comment by stgraber** [comment]
Easiest way I found is:

Run "systemctl edit lxd" and type in:
```
[Service]
ExecStartPost=-/sbin/ip route add 144.217.33.224/27 dev lxdbr0
```

**Comment by stgraber** [comment]
You may need to run "systemctl daemon-reload" after setting this.

**Comment by davidfavor** [comment]
Unfortunately, there's already a ExecStartPost action in the lxd service.

It appears there can only be one ExecStartPost per service + pipelines aren't allowed.

I opted to just create a separate service.

/lib/systemd/system/lxd-lxdbr0-post-up.service containing...

```
[Unit]
Description=Emulate post-up for lxdbr0
After=lxd.service
Requires=lxd.service

[Service]
Type=forking
TimeoutSec=0
RemainAfterExit=yes
ExecStart=/david-favor/tools/lxdbr0-post-up

[Install]
WantedBy=multi-user.target
```

Then to ingest this new service into the systemd abyss...

```
systemctl enable lxd-lxdbr0-post-up
systemctl daemon-reload
```

The ExecStart target (script) can have any commands + do required logging.

Likely good to also end the ExecStart script with exit(0) in case the service unit ever extends to attempt restarting if ExecStart script fails.

**Comment by davidfavor** [comment]
Yes. Adding a facility to do this... cleanly seems far better than hacking systemd...

Thanks for adding this to the 2.7 milestone.

**Comment by stgraber** [comment]
Sent a branch which adds support for ipv4.routes and ipv6.routes.

Once that's in a released LXD, you'll be able to do:

```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ ip -4 route show dev lxdbr0
10.166.57.0/24  proto kernel  scope link  src 10.166.57.1

stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc network set lxdbr0 ipv4.routes 144.217.33.224/27

stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ ip -4 route show dev lxdbr0
10.166.57.0/24  proto kernel  scope link  src 10.166.57.1
144.217.33.224/27  proto static  scope link
```

**Comment by davidfavor** [comment]
Thanks.

I'll check back on this when 2.7 releases + then remove all my systemd hacks.

**Comment by davidfavor** [comment]
So as of LXD-2.7 let me know if the correct way to do this might look like...

lxc config set <container> ipv4.routes 144.217.33.224/27

Also let me know if additional settings are required to be set, like ipv4.firewall or anything else.

Appears only ipv4.routes is required for this to work.

Thanks.

**Comment by stgraber** [comment]
Yep, with 2.7 all you have to do is set ipv4.routes and LXD will make sure you always have that static route set. No more systemd/rc.local trick required.

Everything else works as it used to so you shouldn't need to change anything else.

**Comment by davidfavor** [comment]
Awesome.

I'm looking + missing correct separator character for multiple IP ranges.

Likely this is blank space. Let me know if the following is correct for multiple ranges...

lxc config set container ipv4.routes "144.217.33.224/27 144.217.33.53/27"

Thanks.

**Comment by stgraber** [comment]
Documentation (doc/configuration.md) says "Comma separated list of additional IPv4 CIDR subnets to route to the bridge"

**Comment by davidfavor** [comment]
Thanks.

**Comment by Paprikachu** [comment]
It seems to me that while this works for bridge networks, there is no option to do this with p2p nics, is that correct?
