### ISSUE TITLE
installing nfs-server is not working

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#2703]
Same env as described in #2670 

On a fresh container running ubuntu 16 (like the hypervisor) ; when installing nfs-server

     # apt install -y nfs-server 

Got this error

    Setting up nfs-kernel-server (1:1.2.8-9ubuntu12) ...
    A dependency job for nfs-server.service failed. See 'journalctl -xe' for details.
    nfs-server.service couldn't start.
    A dependency job for nfs-server.service failed. See 'journalctl -xe' for details.
    invoke-rc.d: initscript nfs-kernel-server, action "start" failed.
    dpkg: error processing package nfs-kernel-server (--configure):
    subprocess installed post-installation script returned error exit status 1
    Errors were encountered while processing:
     nfs-kernel-server

Full log is : https://gist.github.com/7fe7dc42bc6019fc79caf1535987d3d2

I set the container with security.privileged to true but it doesn't change anything.

Thanks to help

**Comment by stgraber** [comment]
Looks like the problem is a failure to mount the "rpc_pipefs" filesystem in the container.

Doing:

    lxc config set CONTAINER raw.apparmor "mount fstype=rpc_pipefs,"

Should fix that particular failure.

**Comment by nlienard** [comment]
still got the error 

    root@inxovh-hy001 (node1):~# lxc config show inxovh-nfs001
    name: inxovh-nfs001
    profiles:
    - default
    config:
      raw.apparmor: mount fstype=rpc_pipefs,
      security.privileged: "true"
      volatile.base_image:     b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7
      volatile.eth0.hwaddr: 00:16:3e:32:6b:3b
      volatile.idmap.base: "0"
      volatile.idmap.next: '[]'
      volatile.last_state.idmap: '[]'
      volatile.last_state.power: RUNNING
    devices: {}
    ephemeral: false

    root@inxovh-nfs001:~# dpkg --configure nfs-kernel-server
    Setting up nfs-kernel-server (1:1.2.8-9ubuntu12) ...
    A dependency job for nfs-server.service failed. See 'journalctl -xe' for details.
    nfs-server.service couldn't start.
    A dependency job for nfs-server.service failed. See 'journalctl -xe' for details.
    invoke-rc.d: initscript nfs-kernel-server, action "start" failed.
    dpkg: error processing package nfs-kernel-server (--configure):
     subprocess installed post-installation script returned error exit status 1
    Errors were encountered while processing:
     nfs-kernel-server
    root@inxovh-nfs001:~#


Dec  8 10:30:36 inxovh-nfs001 systemd[1]: Failed to reset devices.list on /system.slice/systemd-remount-fs.service: Operation not permitted
Dec  8 10:30:36 inxovh-nfs001 systemd[1]: Failed to reset devices.list on /system.slice/proc-sysrq\x2dtrigger.mount: Operation not permitted
Dec  8 10:30:36 inxovh-nfs001 systemd[1]: Failed to reset devices.list on /system.slice/systemd-journald.service: Operation not permitted
Dec  8 10:30:36 inxovh-nfs001 systemd[1]: Failed to reset devices.list on /system.slice/console-getty.service: Operation not permitted
Dec  8 10:30:36 inxovh-nfs001 mount[650]: mount: nfsd is write-protected, mounting read-only
Dec  8 10:30:36 inxovh-nfs001 mount[650]: mount: cannot mount nfsd read-only
Dec  8 10:30:36 inxovh-nfs001 systemd[1]: proc-fs-nfsd.mount: Mount process exited, code=exited status=32
Dec  8 10:30:36 inxovh-nfs001 systemd[1]: Failed to mount NFSD configuration filesystem.
Dec  8 10:30:36 inxovh-nfs001 systemd[1]: Dependency failed for NFS Mount Daemon.
Dec  8 10:30:36 inxovh-nfs001 systemd[1]: Dependency failed for NFS server and services.
Dec  8 10:30:36 inxovh-nfs001 systemd[1]: nfs-server.service: Job nfs-server.service/start failed with result 'dependency'.
Dec  8 10:30:36 inxovh-nfs001 systemd[1]: nfs-mountd.service: Job nfs-mountd.service/start failed with result 'dependency'.
Dec  8 10:30:36 inxovh-nfs001 systemd[1]: proc-fs-nfsd.mount: Unit entered failed state.

**Comment by stgraber** [comment]
Looks like you need more filesystems to be allowed :) error above hints at "nfsd".

So you'd need to set raw.apparmor to a multi-line of:

    mount fstype=rpc_pipefs,
    mount fstype=nfsd,

**Comment by nlienard** [comment]
great ! it works ! many thanks

    root@inxovh-nfs001:~# dpkg --configure nfs-kernel-server
    Setting up nfs-kernel-server (1:1.2.8-9ubuntu12) ...
    root@inxovh-nfs001:~#

**Comment by gedOHub** [comment]
How to set multi-lines?

**Comment by juanquy** [comment]
How I set  raw.apparmor to a multi-line in the container config file?
I'm having the same issue installing nfs-server on Ubuntu 16.04

**Comment by lae** [comment]
@juanquy the lines mentioned above don't have to be multi-line pretty sure, they're comma separated.

**Comment by stgraber** [comment]
for multi-line, you can pipe multi-line input to "lxc config set".

printf "line1\nline2" | lxc config set CONTAINER KEY -

**Comment by juanquy** [comment]
Thank just like multi-line in cli

**Comment by bjmuld** [comment]
apparmor_parser is complaining when I use the above (even single line)... ideas?
