### ISSUE TITLE
LxD 2.3+ Networking on CentOS

### ISSUE THREAD

**Issue by bdd4329** [lxc/lxd#2708]
I've been using LxD for some time and am now planning on going full production with LxD 2.3+. I originally compiled LxC + LxD (2.0) on CentOS and have been running it without problems for months. However, on moving to LxD 2.3+, I'm having problems with static addressing via a network bridge. I can only find the simplest of examples for the new 2.3+ networking, so can you please verify that I'm setting up my bridge properly? x.x.x.59 or 60 refers to a real public IP.

> lxc network create lxdbr0 ipv6.address=none ipv4.address=x.x.x.59 ipv4.nat=false ipv4.routing=true
> lxc launch coe-centos7-container test -c security.privileged=true
> lxc config device set test eth0 ipv4.address x.x.x.60
> lxc network attach lxdbr0 coe-centos7-container eth0

All of this succeeds, however the IP address is not set for the container. Instead, I had to set it up with a static IP like any other Centos box. This will configure the IP, but I can't get any packets through. From the container, I can't ping the bridge (59) or anything else. I can ping the bridge (59) from outside of the container, but not the container's IP (60).

**Comment by stgraber** [comment]
The commands above don't seem right to me. First of all, you're listing "x.x.x.59" as the ipv4.address, which isn't in CIDR notation (no mask). Then you appear to be attaching the bridge to your container after it's started. That's unlikely to trigger dhcp in the container, so you either need to restart the container or manually trigger dhcp in the container.

**Comment by bdd4329** [comment]
After changing the command to have the proper CIDR address scheme:
lxc network create lxdbr0 ipv6.address=none ipv4.address=x.x.x.59/24 ipv4.nat=false

and then launching the container like this:
lxc launch coe-centos7-container test -c security.privileged=true -n lxdbr0

and settings this:
lxc config device set test lxdbr0 ipv4.address x.x.x.60

I am now able to properly get a DHCP address. However, I cannot access the network from within the container. I can't ping the bridge address or anything else. Also, from within the host, I cannot ping the bridge address anymore after the container receives a DHCP address. It appears that the bridge just isn't forwarding packets.

**Comment by bdd4329** [comment]
This seems to be a problem using VirtualBox on my Mac. On my dell servers I am properly able to get all of this working. However, I do heavily rely on vagrant for testing (which uses VirtualBox). Any idea what could cause something like this within a VM instance? I have the network interface set to bridge and allow promiscuous traffic.

**Comment by stgraber** [comment]
Not sure why that wouldn't work but I'm not familiar with VirtualBox networking...

Promiscuous mode shouldn't even matter unless you're using bridge.external_interfaces.

Do you have some kind of network overlap/conflict between eth0 and lxdbr0 in that VM?

**Comment by bdd4329** [comment]
No, there isn't any conflict that I can see. I just ran into this issue with a colleague working on LxD deployment with OpenStack. He was also testing with VirtualBox and had the same issue. Sounds completely unrelated to LxD, but this may come up more as people start to understand the value of LxD and start integrating it into their development environments. He is in the process of researching this problem right now.

I'm going to mark this as closed, but I will post the solution here if he finds one.
