### ISSUE TITLE
Ceph RBD map denied in container

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#2709]
Same env as described in #2670

When trying to map a rbd device inside container; it is denied.

    root@inxovh-nfs001:~# rbd --cluster cephA map libvirt-pool/nfs001 --keyring  /    etc/ceph/cephA.client.admin.keyring      
    rbd: sysfs write failed
    In some cases useful info is found in syslog - try "dmesg | tail" or so.
    rbd: map failed: (30) Read-only file system
    root@inxovh-nfs001:~#

Access to ceph is ok:

    root@inxovh-nfs001:~# ceph --cluster cephA -s
        cluster 2c1e0b44-b76b-4283-b0cb-0b002698c0b6
         health HEALTH_OK
         monmap e2: 3 mons at {cephA-001=192.168.10.243:6789/0,cephA-002=192.168.10.244:6789/0,cephA-003=192.168.10.245:6789/0}
                election epoch 346, quorum 0,1,2 cephA-001,cephA-002,cephA-003
         osdmap e260: 6 osds: 6 up, 6 in
                 flags sortbitwise
           pgmap v314792: 400 pgs, 2 pools, 3026 MB data, 764 objects
                 45190 MB used, 1557 GB / 1601 GB avail
                      400 active+clean
       client io 1331 B/s rd, 1 op/s rd, 0 op/s wr

i can access  to rbd and create device:

    root@inxovh-nfs001:~# rbd --cluster cephA create -p libvirt-pool test --size 1G
    root@inxovh-nfs001:~#

    root@inxovh-nfs001:~# rbd --cluster cephA list -p libvirt-pool
    nfs001
    nliovh-vm001
    test

    root@inxovh-nfs001:~# rbd --cluster cephA rm -p libvirt-pool test
    Removing image: 100% complete...done.
    root@inxovh-nfs001:~#

Any clue is welcome.

**Comment by tych0** [comment]
Sounds like you're probably trying to mmap something with PROT_WRITE that's on a read only filesystem. Can you strace the thing that's doing the mmap to figure out what?

**Comment by nlienard** [comment]
strace output: https://gist.github.com/6cac3d3eb852869d817c382480284b6d

**Comment by nlienard** [comment]
should i modify the config of the container ?

**Comment by tych0** [comment]
Oh, sorry, I misread. There is this clue:

```rbd: sysfs write failed```

This seems like something that was likely blocked by apparmor. Can you post the output of dmesg?

**Comment by nlienard** [comment]
dmesg is only showing iptables messages. :(

**Comment by nlienard** [comment]
root@inxovh-nfs001:~# dmesg -c
     root@inxovh-nfs001:~# rbd --cluster cephA map libvirt-pool/nfs001 --keyring       /etc/ceph/cephA.client.admin.keyring
     rbd: sysfs write failed
     In some cases useful info is found in syslog - try "dmesg | tail" or so.
     rbd: map failed: (30) Read-only file system
     root@inxovh-nfs001:~# dmesg
     root@inxovh-nfs001:~#

**Comment by stgraber** [comment]
Setting or adding the following raw.lxc will make /sys and /proc fully writable, that may help:

```
  raw.lxc: |-
    lxc.mount.auto=
    lxc.mount.auto=sys:rw proc:rw cgroup:rw
```

**Comment by nlienard** [comment]
root@inxovh-hy001 (node1):~# lxc config show inxovh-nfs001
name: inxovh-nfs001
profiles:
- default
config:
  raw.apparmor: mount fstype=nfsd,
  raw.lxc: |-
    lxc.mount.auto=
    lxc.mount.auto=sys:rw proc:rw cgroup:rw
  security.privileged: "true"
  volatile.base_image: b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7
  volatile.eth0.hwaddr: 00:16:3e:32:6b:3b
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false


+ restart container


root@inxovh-nfs001:~# rbd --cluster cephA map libvirt-pool/nfs001 --keyring  /etc/ceph/cephA.client.admin.keyring
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail" or so.
rbd: map failed: (13) Permission denied
Bell in window 8  :~#

**Comment by stgraber** [comment]
What's in "dmesg" now?

**Comment by nlienard** [comment]
still nothing :(

**Comment by stgraber** [comment]
The fact that it doesn't say read-only anymore suggests that the lxc.mount.auto trick worked fine. But it seems likely that apparmor is getting in the way now.

Can you try adding "lxc.aa_profile=unconfined" to your raw.lxc?

That will turn apparmor entirely off, at which point the only thing that could still block you is some kernel code that's not namespace aware.

**Comment by nlienard** [comment]
got this now: 

    root@inxovh-nfs001:~# rbd --cluster cephA map libvirt-pool/nfs001 --keyring  /etc/ceph/cephA.client.admin.keyring
    rbd: sysfs write failed
    RBD image feature set mismatch. You can disable features unsupported by the kernel with "rbd feature disable".
    In some cases useful info is found in syslog - try "dmesg | tail" or so.
     rbd: map failed: (6) No such device or address

**Comment by stgraber** [comment]
getting slightly better, can you run it under "strace -fF" so we can see if it's a missing device or something or if it's just the kernel not letting you do this.

**Comment by nlienard** [comment]
strace output: https://gist.github.com/fd8b210fdc206ef867a134558bec40b4

**Comment by nlienard** [comment]
Ok it works now the issue is on rbd side according to 

https://www.mail-archive.com/ceph-users@lists.ceph.com/msg29334.html

here a new test successfullly mapped inside container:

     root@inxovh-nfs001:~# rbd --cluster cephA create -p libvirt-pool test --size 1G  --image-feature layering
    root@inxovh-nfs001:~# rbd --cluster cephA map libvirt-pool/test --keyring  /etc/ceph/cephA.client.admin.keyring
    /dev/rbd0

**Comment by stgraber** [comment]
cool!

So yeah, looks like you can get all of this working, but your container basically doesn't have any security filters applied to it at this point :)

**Comment by nlienard** [comment]
it is strange, i still don't see the rbd0 device:

    root@inxovh-nfs001:~# ls -la /dev/rbd0
    ls: cannot access '/dev/rbd0': No such file or directory

**Comment by stgraber** [comment]
oh, that'd be because /dev is just a tmpfs and rbd probably just assumes the kernel will create those for you in a devtmpfs.

You're going to need to add one or more unix-char devices to your container for those things.

**Comment by stgraber** [comment]
lxc config device add inxovh-nfs001 rbd0 unix-char path=/dev/rbd0

**Comment by stgraber** [comment]
You'll most likely want to set the minor= and major= property on that device too, otherwise the container won't be able to start until the host /dev/rbd0 exists. And by the looks of it, that device won't exist until you run rbd in the container (so chicken and egg problem).

**Comment by nlienard** [comment]
ok but that means if i move the container in another node, i ll lost the rbd0 ?
that means it should be better for me to make a VM in that case.

**Comment by stgraber** [comment]
If you set major= and minor= for the rbd0 device for your container, you should be fine as that will have LXD create the device node regardless of whether it exists on the host or not.

So if you move the container to another host, your container will still show /dev/rbd0 and so should work fine.

Probably best to test it though.

**Comment by nlienard** [comment]
what does that mean minor= and major=  ? what should i do ?

**Comment by nlienard** [comment]
i did:
     # lxc config device add inxovh-nfs001 rbd0 unix-char path=/dev/rbd0

now i got it 


    root@inxovh-nfs001:~# ls -la /dev/rbd0
    crw-rw---- 1 root root 251, 0 Dec  9 14:32 /dev/rbd0

but still can't use it 

    root@inxovh-nfs001:~# mkfs.ext4 /dev/rbd0
    mke2fs 1.42.13 (17-May-2015)
    Could not open /dev/rbd0: Operation not permitted

**Comment by stgraber** [comment]
So what's the state of this?

The errors you're showing above are because you used "unix-char" instead of "unix-block", but I thought we sorted that out on IRC.

Can we close this issue now?

**Comment by nlienard** [comment]
yes it can be closed. thanks !

**Comment by xiaofan-linux** [comment]
> yes it can be closed. thanks !

Hi Hello, I am using kind to deploy rook-ceph storage. pod mounting pvc prompts the following error. Have you encountered this problem? Please answer it. Thank you.

Error message: rbd: map failed: (30) Read-only file system
