### ISSUE TITLE
Add json output for lxc info

### ISSUE THREAD

**Issue by larsemil** [lxc/lxd#2710]
in issue #1789 and the merge request with commit hash cddaada(pr #1876) the --format=json was added for lxc list.

Similar should exist for subcommand: lxc info

**Comment by larsemil** [comment]
ping @cmars who did an awesome job on #1789

**Comment by stgraber** [comment]
Note that #1943 should take care of most of those, quite possibly with less effort.

**Comment by stgraber** [comment]
Going to close this in favor of #1943 which should offer a better general solution to this problem.
