### ISSUE TITLE
container not working anymore

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#2711]
Same env as described in #2670

1. At first , i tried to move the container to another node. it didn't work/
2. i stoped the container; it didn't work; it was hanging forever (30mn and still hanging)
3. i killed the lxc monitor PID.
4. i tried to move it again bug failed.
5. i tried to start it again bug failed/

root@inxovh-hy002 (node2):/var/log/lxd/dpush# lxc move dpush node1:
error: Failed to destroy ZFS filesystem: cannot destroy 'zdata/lxd/containers/dpush': dataset is busy

root@inxovh-hy002 (node2):/var/log/lxd/dpush# zfs list |grep dpush
zdata/lxd/containers/dpush                                                                  147M  4.73G   278M  /var/lib/lxd/containers/dpush.zfs
root@inxovh-hy002 (node2):/var/log/lxd/dpush# zfs umount zdata/lxd/containers/dpush
cannot unmount 'zdata/lxd/containers/dpush': not currently mounted
root@inxovh-hy002 (node2):/var/log/lxd/dpush# zfs start^C
root@inxovh-hy002 (node2):/var/log/lxd/dpush# lxc start dpush
error: Error calling 'lxd forkstart dpush /var/lib/lxd/containers /var/log/lxd/dpush/lxc.conf': err='exit status 1'
  lxc 20161209145033.395 ERROR lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1310 - Path "/sys/fs/cgroup/systemd//lxc/dpush" already existed.
  lxc 20161209145033.395 ERROR lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1367 - No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/dpush: No such file or directory
  lxc 20161209145033.458 ERROR lxc_conf - conf.c:mount_rootfs:807 - No such file or directory - failed to get real path for '/var/lib/lxd/containers/dpush/rootfs'
  lxc 20161209145033.458 ERROR lxc_conf - conf.c:setup_rootfs:1221 - failed to mount rootfs
  lxc 20161209145033.458 ERROR lxc_conf - conf.c:do_rootfs_setup:3671 - failed to setup rootfs for 'dpush'
  lxc 20161209145033.458 ERROR lxc_conf - conf.c:lxc_setup:3753 - Error setting up rootfs mount after spawn
  lxc 20161209145033.458 ERROR lxc_start - start.c:do_start:826 - Failed to setup container "dpush".
  lxc 20161209145033.458 ERROR lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
  lxc 20161209145033.510 ERROR lxc_start - start.c:__lxc_start:1338 - Failed to spawn container "dpush".
  lxc 20161209145034.099 ERROR lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
  lxc 20161209145034.099 ERROR lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "dpush".

Try `lxc info --show-log dpush` for more info
root@inxovh-hy002 (node2):/var/log/lxd/dpush# zfs list -o name,mounted zdata/lxd/containers/dpush
NAME                        MOUNTED
zdata/lxd/containers/dpush       no
root@inxovh-hy002 (node2):/var/log/lxd/dpush# ls -la /sys/fs/cgroup/systemd//lxc/dpush
total 0
drwxrwxr-x  3 root   100000 0 Dec  9 11:26 .
drwxr-xr-x 13 root   root   0 Nov 25 21:39 ..
-rw-r--r--  1 root   root   0 Dec  9 11:26 cgroup.clone_children
-rw-rw-r--  1 root   100000 0 Dec  7 11:50 cgroup.procs
-rw-r--r--  1 root   root   0 Dec  9 11:26 notify_on_release
drwxr-xr-x 14 165536 100000 0 Dec  9 11:26 system.slice
-rw-rw-r--  1 root   100000 0 Dec  2 17:59 tasks
root@inxovh-hy002 (node2):/var/log/lxd/dpush#

how can i fix that ?

thks

**Comment by stgraber** [comment]
Do you have any leftover "zfs" process running on the system?

**Comment by stgraber** [comment]
@nlienard

**Comment by stgraber** [comment]
Any update on this?
