### ISSUE TITLE
what is the recommended way to retrieve the domain name inside the container?

### ISSUE THREAD

**Issue by archf** [lxc/lxd#2713]
# Issue description

When starting a container. The following `/etc/hosts` gets generated.

```bash
[root@mycontainername ~]# cat /etc/hosts
127.0.0.1   localhost
127.0.1.1   <mycontainername>

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
But I kind of expected something like
```bash 
[root@mycontainername ~]# cat /etc/hosts
127.0.0.1   localhost
127.0.1.1   <mycontainername>.<domain> <mycontainername>

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Where this hurts me is that the ansible fact `ansible_domain` can't be retrieve and i'd like to know the realms of my containers...

Is there a rationale behind current behavior?

# Possible solutions

* `domain` defaults to the network `dns.domain` value.
* Maybe it should be a dhcp hook script installed by default inside the images such as [this one here](https://gist.github.com/makuk66/6379642).

Thanks for shedding any light!

**Comment by stgraber** [comment]
/etc/resolv.conf should show the domain the container received over dhcp

**Comment by archf** [comment]
It shows this:

```bash
[root@mycontainername ~]# cat /etc/hosts
; generated by /sbin/dhclient-script
search lxd
nameserver 10.147.76.1
```
You mean we now have to parse the search list? I'm not sure this is reliable if there are multiple entries.

On my `ubuntu 16.04` laptop:

```bash
archf@laptop ~> dnsdomainname 
lan
```
And it's clearly resolved from there:

```bash
archf@laptop ~> cat /etc/hosts                                                                                                              
127.0.0.1       localhost
127.0.1.1       laptop.lan laptop

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

From that perspective i thought `/etc/hosts` was  the ultimate source of truth picked by programs fqdnly speaking... For sure i agree this info should not go in the hostame. I read #1921.

**Comment by stgraber** [comment]
It's not LXD's job to generate files inside your container, we're acting exactly like a VM in that regard.

There is a flag that you can use through cloud-init to have it generate /etc/hosts, but I'm not sure if that includes generating a FQDN record in there.

**Comment by Roszko** [comment]
Further, there are applications which break if the /etc/hosts file is filled like that so LXD definitely took the right approach here.

**Comment by stgraber** [comment]
I'm going to close this issue because LXD does the right thing here, we operate a valid DHCP server and DNS server. We advertise the domain name over DHCP so everything is very much accessible to the container.

As LXD's policy is not to make any assumption about the container's filesystem or workloads, configuring those files is very much up to your container, as it would if it was a VM or physical system.

I suspect the solution for this is to set the right cloud-init config in user.user-data or user.vendor-data.

**Comment by archf** [comment]
Alright! 
Thanks for the clarification. And thank you all for that awesome project. I really like what you guys are doing! Keep it up!

I will probably go down the dhcp hook script route...What's cloud-init config? I never heard of that...
Is user.* information accessible from inside the container? I guess not. Probably only to the cloud-init config your are talking....

**Comment by stgraber** [comment]
cloud-init is a tool which lets you do initial configuration of a system from a provided declarational yaml document. You can read more about it at: https://cloudinit.readthedocs.io/en/latest/

On my desktop, I'm using the following:
```
config:
  user.user-data: |
    #cloud-config
    apt_mirror: http://us.archive.ubuntu.com/ubuntu/
```

As part of the default profile. This bit of cloud-init config changes the archive mirror to use. You can follow that pattern for any of the other keys you find in their documentation.

As for accessing "user.*" keys, you can do so through /dev/lxd in the container.
```
stgraber@castiana:~$ lxc config set xen user.abc def
stgraber@castiana:~$ lxc exec xen bash
root@xen:~# echo $(curl -s --unix-socket /dev/lxd/sock lxd/1.0/config/user.abc)
def
root@xen:~#
```

**Comment by archf** [comment]
Really interesting! Especially for the user and ssh pub key part. I should have know that earlier...
