### ISSUE TITLE
lxc publish error archive tar missed writing bytes

### ISSUE THREAD

**Issue by adriendb** [lxc/lxd#2716]
When running the command:
lxc publish image_name --alias image_name_new
I receive the following error:
error: archive/tar: missed writing X bytes
Which appears to be a golang error

Am I doing something wrong or is this an issue with the tool?

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 LTS
 * The output of "lxc info":
driver: lxc
driverversion: 2.0.0
kernel: Linux
kernelarchitecture: x86_64
kernelversion: 4.4.0-21-generic
server: lxd
serverpid: 1457
serverversion: 2.0.0
storage: btrfs
storageversion: 4.4

**Comment by stgraber** [comment]
Looks like a golang error indeed. Are you anywhere close to running out of disk space on your machine?

Do you have a minimal reproducer for this?

I'd also strongly recommend you upgrade to LXD 2.0.8 as you're still running 2.0.0 which does have a number of bugs related to image publication.

**Comment by adriendb** [comment]
Disk space in the container or the host are not likely the problem. The issue is very consistent and repeatable. I will try on a different host with the same config. Also try upgrade and see what happens. 

Thanks!

Cheers,
Adrien

**Comment by adriendb** [comment]
Hi,

I updated and have the same issue. 

driver: lxc
driverversion: 2.0.5
kernel: Linux
kernelarchitecture: x86_64
kernelversion: 4.4.0-53-generic
server: lxd
serverpid: 1457
serverversion: 2.0.8
storage: btrfs
storageversion: 4.4

Cheers,
Adrien

**Comment by stgraber** [comment]
Is this still a problem? Can you provide the details requested above?
