### ISSUE TITLE
lxc container device mount order

### ISSUE THREAD

**Issue by geodb27** [lxc/lxd#2717]
* Distribution: Ubuntu LTS 16.04
 * Distribution version: lxc-2.0.8
   * Storage backend in use: dir

# Issue description :
When multiple device mappings are configured in a container, the mount order seems randomly made.

A brief description of what failed or what could be improved.
Here is an example container config that I use :
host          | container
/home/X   | /home/X
/home/X/docroot |  /var/www/html
/home/X/NFS      | /var/www/html/some_folder

As you can see, the /var/www/html/some_folder *MUST* be mounted at container startup *AFTER* /var/www/html is mounted. This is not the case every time and leads to problems.

# Steps to reproduce

Each time the container is started, even though it doesn't raise any error (and of course it shouldn't because there is no error at all at the mount point), the mounts are made in random order. This leads to (in my example) to a /var/www/html/some_folder that is sometimes empty, sometime not.
So, what would be great would be to either have an option to specify the numerical order the mounts should be done at container's startup, either to have an option to specify after which, optionnaly, the mount should be done.
To be more specific, either :
lxc config device add lxc-container www-docroot source=/home/X/docroot path=/var/www/html mount-order=1
lxc config device add lxc-container nfs-share disk source=/home/X/NFS path=/var/www/html/some_folder mount-after=www-docroot mount-order=2

lxc config device add lxc-container www-docroot source=/home/X/docroot path=/var/www/html
lxc config device add lxc-container nfs-share disk source=/home/X/NFS path=/var/www/html/some_folder mount-after=www-docroot

In either case, this could be left optionnal, so that if nothing is specified, the startup goes at it already does.

**Comment by brauner** [comment]
Hm, this is caused by the behavior of maps in go which return their members in random order when you retrieve them. So indeed maybe having a mount-after option or similar is a good idea. Let's hear what @stgraber has to say.

**Comment by stgraber** [comment]
I thought @tych0 added code to mount disk devices based on their target path instead of in whatever order we have them in config.

**Comment by tych0** [comment]
I thought I did too. Let me look.

**Comment by tych0** [comment]
https://github.com/lxc/lxd/blob/master/lxd/container_lxc.go#L1664 it doesn't look like we do anything intelligent at all here. I have no idea what happened to this code. Anyway, I'll try to send a patch shortly.
