### ISSUE TITLE
VM inside container

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2718]
Hi,
Is it possible to run KVM inside LXD containers ?

**Comment by stgraber** [comment]
Yes

    lxc config device add CONTAINER kvm unix-char path=/dev/kvm

That will expose /dev/kvm inside the container which you can tell use with kvm/qemu.

**Comment by upuvvad1** [comment]
When trying to build a VM from image inside a container, the process reports an error saying
 [Fri, 06 Jan 2017 10:49:18 virt-install 5222] ERROR (cli:306) Host does not support any virtualization options 
However, the same process works on the bare container.

Do I need to install qemu-kvm inside the container again? I assume it no, since we are attaching the device from the bare hardware to container via 

lxc config device add CONTAINER kvm unix-char path=/dev/kvm

**Comment by stgraber** [comment]
It depends on how the detection is done, if it's done by simply checking if the right commands exist, then installing qemu-kvm may help.

**Comment by ajthemacboy** [comment]
I have added the /dev/kvm device to a privileged LXD container. However, KVM has this error:

`Unable to complete install: 'Unable to write to '/sys/fs/cgroup/devices/machine/qemu-4-generic.libvirt-qemu/devices.allow': Operation not permitted'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 90, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/create.py", line 2277, in _do_async_install
    guest.start_install(meter=meter)
  File "/usr/share/virt-manager/virtinst/guest.py", line 501, in start_install
    noboot)
  File "/usr/share/virt-manager/virtinst/guest.py", line 416, in _create_guest
    dom = self.conn.createLinux(start_xml or final_xml, 0)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 3491, in createLinux
    if ret is None:raise libvirtError('virDomainCreateLinux() failed', conn=self)
libvirtError: Unable to write to '/sys/fs/cgroup/devices/machine/qemu-4-generic.libvirt-qemu/devices.allow': Operation not permitted`

Any ideas?

**Comment by upuvvad1** [comment]
What version of lxd are you running?
I had the same issue with lxd 2.12
Was resolved with lxd 2.13

**Comment by ajthemacboy** [comment]
Before I was running LXD 2.12, but I just updated to 2.13 and I still have the same error.
