### ISSUE TITLE
lxc profile list --help mentions [filters] but doesn't state what filters can be.

### ISSUE THREAD

**Issue by Veebers** [lxc/lxd#2719]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Xenial 16.04.1 LTS
 * The output of "lxc info" or if that fails:
-- snip --
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-31-generic
  server: lxd
  serverversion: 2.0.4
  storage: zfs
  storageversion: "5"

# Issue description

The help text for the command "lxc profile list" mentions that list as an optional argument [filters] but doesn't state what [filters] should or could be (e.g. is it a profile name filter, or a profile attribute to filter on).

The help contents for "lxc profile list" is incomplete regarding [filter].

**Comment by pcdummy** [comment]
After look at the [code](https://github.com/lxc/lxd/blob/master/lxc/profile.go#L416) i think \[filters\] should get renamed to \[remote\]:
