### ISSUE TITLE
rpmlint: E: missing-call-to-setgroups-before-setuid /usr/bin/lxd

### ISSUE THREAD

**Issue by ganto** [lxc/lxd#2724]
I created some community [packages of LXD](https://copr.fedorainfracloud.org/coprs/ganto/lxd/) for Fedora on COPR. When analyzing the resulting RPMs with [rpmlint](https://github.com/rpm-software-management/rpmlint/) (`rpmlint-1.9-3.fc24`) I get the following error:

```
lxd.x86_64: E: missing-call-to-setgroups-before-setuid /usr/bin/lxd
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.
```
As I read it, it complains about [this code in nsexec.go](https://github.com/lxc/lxd/blob/master/lxd/main_nsexec.go#L158) being related to [POS36-C. Observe correct revocation order while relinquishing privileges](https://www.securecoding.cert.org/confluence/display/c/POS36-C.+Observe+correct+revocation+order+while+relinquishing+privileges)

I guess when attaching to a namespace, the related issue might not be valid anymore as you are technically not dropping your privileges but only "move" them. Is my assumption correct?

**Comment by stgraber** [comment]
Right, I didn't put code to do the usual setgroups in there because we don't actually care about the list of groups being right at that point.

That being said, I don't mind adding a call to setgroups either if that makes some linters happier :)
