### ISSUE TITLE
Question: Btrfs not supported anymore? 

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#2733]
Upon `lxd init` I've noticed that you can choose only dir or zfs as storage backend. Isn't Btrfs not supported anymore?

**Comment by stgraber** [comment]
"lxd init" doesn't know about all storage backends. This may change soon with @brauner's work on storage pools.

Right now the way things work, if /var/lib/lxd is on btrfs and you have the btrfs tools installed, LXD will use that without needing any further configuration.

**Comment by huegelc** [comment]
thx
