### ISSUE TITLE
Enhancement Request: lxc exec disable data buffering 

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#2737]
Currently lxc exec seems to buffer data, which means long running command provide no incremental output for feedback about their running.

This means there's no way to tell if a command hangs or is proceeding.

A simple example, create a container + issue...

lxc exec c1 -- apt-get upgrade

Output seems to only occur after command has complete.

Same with...

lxc exec c1 -- bash -c "apt-get upgrade"

If there's a known way to disable buffering for lxc exec, please update this ticket.

Thanks.

**Comment by stgraber** [comment]
Both show progress output just fine here.

**Comment by stgraber** [comment]
To be clear, I'm seeing on my local system, the exact same behavior that we're seeing on say https://linuxcontainers.org/lxd/try-it/

That is, things are behaving exactly as if I was running them locally or over ssh.

**Comment by davidfavor** [comment]
Hum... Something must be different in my environment.

Let me know if you have any clues about how I might debug this.

Thanks.

**Comment by stgraber** [comment]
Not sure, could be something weird with your shell or with your current pty maybe.

**Comment by davidfavor** [comment]
My bad.

I've been rewriting all my management tools, from LXC to LXD + fat fingered some code which runs external programs. Rather than echoing by line, code was buffering entire command output + echoing it.

Apologies for the wild goose chase.
