### ISSUE TITLE
Running Android Container using LXD

### ISSUE THREAD

**Issue by nampnx** [lxc/lxd#2741]
Dear,
I am having a problem with Android Container on LXD.
I am deploying Android Container using LXD. I already deploy successfully Android Container using LXC and now i wanna move to LXD because LXD has Nova-LXD to integrated into OpenStack Platform.
Android Container needs more devices to start Android OS. When I used LXC, all devices from host were automatically mounted in /dev folder of container. However, when I deploy Android Container using LXD, Container cannot start because there was not enough mounted devices in /dev folder, only: cpuctl  fscklogs  pts  socket . Devices were not mounted automatically like LXC.
I would like to ask you how to solve this problem: devices are not automatically mounted in /dev folder?
The following pictures are from LXC and LXD:
LXC:
![lxc](https://cloud.githubusercontent.com/assets/13163073/21340709/ac93c76e-c6cb-11e6-86c7-1445864e0422.png)
LXD:
![lxd](https://cloud.githubusercontent.com/assets/13163073/21340739/e6d3bff6-c6cb-11e6-8d5e-1b97fe529ebe.png)

**Comment by stgraber** [comment]
What was your container's configuration under LXC (/var/lib/lxc/android/config)?

And what's the one generated by LXD? (/var/log/lxd/and1/lxc.conf)?

**Comment by nampnx** [comment]
Hi stgraber,
This is LXC's configuration:
![lxc](https://cloud.githubusercontent.com/assets/13163073/21374454/4050d296-c76a-11e6-8b0a-334dd33cb7b1.png)

And this is LXD's configuration:
![lxd](https://cloud.githubusercontent.com/assets/13163073/21374462/4d063d00-c76a-11e6-8a17-ffcb940d316f.png)

**Comment by stgraber** [comment]
Looks like you should at least set "raw.lxc" to:
```
lxc.cgroup.devices.allow=
lxc.cgroup.devices.allow=a
```

Your pre-start script also won't run with LXD so that may be a problem since that may well be what sets up most of those devices for you.

**Comment by nampnx** [comment]
I already set the configuration like you said however, it also did not start (cannot mounting devices from host to /dev folder of container).
The pre-start scripts in my LXC does not have more configurations, only mount the rootfs for the container.
I already allow all for cgroup devices, unconfined apparmor profile, set permission for seccomp but didnot work well.
Do you think the problem causing by setting permissions in source code LXD?

**Comment by stgraber** [comment]
The other difference in config is that LXD sets "lxc.autodev=1" which has LXC setup a tmpfs on /dev, hiding any device node that may come with your rootfs.

You could try adding "lxc.autodev=0" in raw.lxc to undo that behavior.

**Comment by nampnx** [comment]
I also set "lxc.autodev=0" but I still did  not work, devices were not automatically mounted in LXD container like using LXC.

"lxc.aa_allow_incomplete = 1
lxc.cgroup.devices.allow =
lxc.cgroup.devices.allow = a
lxc.aa_profile = unconfined
lxc.autodev=0"

**Comment by stgraber** [comment]
So to be clear, there is no code in either LXC or LXD that creates those devices.

The devices you saw in your old LXC container were either a part of the rootfs on disk or were created by something inside the container, LXC didn't create them for you.

The LXD configuration you seem to be running with now should make sure that /dev is left alone (lxc.autodev=0) and that you can create whatever devices you want (lxc.cgroup.devices.allow=a).

It could be that your rootfs just doesn't have those device nodes, or whatever usually creates them in the container isn't running somehow or something in the container is over-mounting /dev and hiding the devices.

**Comment by nampnx** [comment]
Basically, LXD written by Go language and based on liblxc to create container. I saw a project from you: go-lxc. Does LXD uses go-lxc to interact with liblxc?

**Comment by stgraber** [comment]
yes it does
