### ISSUE TITLE
Inconsistent permissions with recursive push for files and directories

### ISSUE THREAD

**Issue by vahe** [lxc/lxd#2759]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.1
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-53-generic
   * LXC version: 2.0.6
   * LXD version: 2.6.2
   * Storage backend in use: zfs

# Issue description

All the files and directories being pushed have the same owner outside the container.
When recursively pushing them to a container, files and directories have different owners. Files are owned by uid 1000 inside the container, directories by uid 0. This is true regardless of the permissions of the push target.

Would be nice to have consistent permissions for files and directories.

**Comment by stgraber** [comment]
Definitely sounds like a bug. @tych0 can you take a look when you have a minute?
