### ISSUE TITLE
json/yaml tags in embedded structs

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#2760]
Using an embedded struct (e.g. https://github.com/lxc/lxd/blob/master/shared/api/network.go#L5) with `json` or `yaml` like we do in `lxc network show` will complicate the output. (I face the same issue with the storage stuff.) Currently `lxc network show lxdbr0` will look like:

```

chb@conventiont|~
> lxc network show lxdbr0
networkput:
  config:
    bridge.mtu: "1500"
    ipv4.address: 10.205.204.1/24
    ipv4.nat: "true"
    ipv6.address: fd42:81cf:ad31:c958::1/64
    ipv6.nat: "true"
managed: true
name: lxdbr0
type: bridge
usedby:
- /1.0/containers/alp1
- /1.0/containers/fed241
- /1.0/containers/trust1
- /1.0/containers/vag1
- /1.0/containers/xen1
- /1.0/containers/yak1
- /1.0/containers/zest1
```

So the embedded struct `networkput` needs to get an additional `yaml` tag to show up as e.g. simply `network` but then again, the indentation is still wrong. I'd argue that the `networkput`/`network` label shouldn't exist at all. What I'm currently doing for the storage stuff is:

https://paste.ubuntu.com/23673779/

and it will currently look like:
```
root@conventiont|~/source/go/bin
> ./lxc storage show tank2
pool_name: tank2
used_by: []
config:
  driver: zfs
  size: "61205515468"
  source: /home/chb/mnt/G/lxd/tank2
  zfs.pool_name: tank2
```

**Comment by stgraber** [comment]
Doh, that's kinda annoying, I'll have to look at a way to fix this...

Your approach is wrong tough as the point of Writable() is that it'll give you a struct which you can then PUT/PATCH. This is not true in your case.

I'll take a look at any flag which may exist to have the inherited stuff flattened. If that's not possible then I'll just have to duplicate all the structs and have the various Writable() fill in the right struct...
