### ISSUE TITLE
LXD equivalent to lxc-top request

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#2763]
net11 # lxd --version
2.7

net11 # lsb_release -a     
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

Surely I'm missing this in the docs.

Pass along any discussion about how to duplicate similar functions for CPU + memory + blockio usage.

Thanks.

**Comment by stgraber** [comment]
Same as #822
