### ISSUE TITLE
LXD should treat empty dnsmasq PID files as if the file was missing

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2767]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.10
 * The output of "lxc info" or if that fails:
```
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.0-32-generic
  server: lxd
  serverpid: 10901
  serverversion: "2.7"
  storage: dir
  storageversion: ""
```

# Issue description

Containers lost internet access after LXD upgraded. `dpkg-reconfigure` doesn't propose anything:
```
$ sudo dpkg-reconfigure -p medium lxd
Warning: Stopping lxd.service, but it can still be activated by:
  lxd.socket
$
```
And I don't want to kill my containers yet:
```
$ sudo lxd init
error: You have existing containers or images. lxd init requires an empty LXD.
$
```
Can't ping `google.com` from containers:
```
# ping google.com
ping: google.com: Name or service not known
#
```

What's going on?

**Comment by stgraber** [comment]
lxc network list

**Comment by techtonik** [comment]
```
$ lxc network list node:
+--------+----------+---------+---------+
|  NAME  |   TYPE   | MANAGED | USED BY |
+--------+----------+---------+---------+
| eth0   | physical | NO      | 0       |
+--------+----------+---------+---------+
| lxcbr0 | bridge   | NO      | 0       |
+--------+----------+---------+---------+
| lxdbr0 | bridge   | YES     | 4       |
+--------+----------+---------+---------+
| virbr0 | bridge   | NO      | 0       |
+--------+----------+---------+---------+
```

**Comment by stgraber** [comment]
lxc network show lxdbr0

**Comment by techtonik** [comment]
```
$ lxc network show node:lxdbr0
name: lxdbr0
config:
  dns.mode: dynamic
  ipv4.address: 10.48.250.1/24
  ipv4.dhcp.ranges: 10.48.250.2-10.48.250.254
  ipv4.nat: "true"
  ipv6.address: fd2f:7719:681e:52e1::1/64
  ipv6.nat: "true"
managed: true
type: bridge
usedby:
- /1.0/containers/cpm
- /1.0/containers/far2l
- /1.0/containers/ruby
- /1.0/containers/virtest
```

**Comment by stgraber** [comment]
And I'm assuming those 4 containers are the ones which aren't working right now?
Have you tried restarting the containers?

If you just upgraded from 2.0.x to 2.3 or higher (which seems to be the case here), LXD will translate your existing network configuration for you from the packaging level config over to the native LXD network config.

One potential catch with this though is that this may cause the eth0 device inside the container to be briefly removed and re-added, causing the network configuration inside the container to be lost, unless the container's init system re-configures the network on device hotplug (which doesn't very commonly happen).

Your lxdbr0 configuration looks perfectly fine, so I'd expect containers to be able to reach the network once they configure through DHCP. So if you haven't done so already, restarting the containers should fix things, or possibly even easier, just restarting networking inside the containers should achieve the same.

**Comment by techtonik** [comment]
Restarted all of them. Still can't resolve anything withing the containers. The `ruby` container was created fresh from `ubuntu:16.10`

**Comment by stgraber** [comment]
Does the container get an IP address? Can it ping its gateway? Can it ping 8.8.8.8?

**Comment by techtonik** [comment]
Container gets ipv6 address, but no ipv4. I don't see gateway info for `eth0` there:
```
root@ruby:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
17: eth0@if18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:77:1f:9d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::216:3eff:fe77:1f9d/64 scope link
       valid_lft forever preferred_lft forever
```
And it can not ping 8.8.8.8:
```
root@ruby:~# ping 8.8.8.8
connect: Network is unreachable
```

**Comment by stgraber** [comment]
lxc profile show default

**Comment by techtonik** [comment]
```
$ lxc profile show node:default
name: default
config: {}
description: ""
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
usedby:
- /1.0/containers/cpm
- /1.0/containers/virtest
- /1.0/containers/far2l
- /1.0/containers/ruby
```

**Comment by stgraber** [comment]
What happens if you run "dhclient eth0" in the container?

**Comment by techtonik** [comment]
Nothing. It hangs with no response.

**Comment by stgraber** [comment]
Can you paste a full "ps fauxwww" of the host?

**Comment by techtonik** [comment]
[psfauxwww.txt](https://github.com/lxc/lxd/files/679420/psfauxwww.txt)

**Comment by stgraber** [comment]
I'm not seeing any LXD managed dnsmasq daemons running, so that's probably the problem.

You could try "systemctl restart lxd" which will cause LXD to attempt to spawn it again.
If that doesn't fix it, then you should have an error message in /var/log/lxd/lxd.log at least.

**Comment by techtonik** [comment]
Says it can not read `/proc//exe` or something.
```
lvl=info msg="Received 'terminated signal', exiting." t=2016-12-31T07:58:22+0300
lvl=info msg="Stopping REST API handler:" t=2016-12-31T07:58:22+0300
lvl=info msg=" - closing socket" socket=[::]:8443 t=2016-12-31T07:58:22+0300
lvl=info msg=" - skipping socket-activated socket" socket=/var/lib/lxd/unix.socket t=2016-12-31T07:58:22+0300
lvl=info msg="Closing the database" t=2016-12-31T07:58:22+0300
lvl=info msg="Stopping /dev/lxd handler" t=2016-12-31T07:58:22+0300
lvl=info msg="Stopped /dev/lxd handler" t=2016-12-31T07:58:22+0300
lvl=info msg="Saving simplestreams cache" t=2016-12-31T07:58:22+0300
lvl=info msg="Saved simplestreams cache" t=2016-12-31T07:58:22+0300
lvl=info msg="LXD 2.7 is starting in normal mode" path=/var/lib/lxd t=2016-12-31T07:58:22+0300
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2016-12-31T07:58:22+0300
lvl=info msg="Default uid/gid map:" t=2016-12-31T07:58:22+0300
lvl=info msg=" - u 0 165536 65536" t=2016-12-31T07:58:22+0300
lvl=info msg=" - g 0 165536 65536" t=2016-12-31T07:58:22+0300
err="readlink /proc//exe: no such file or directory" lvl=eror msg="Failed to bring up network" name=lxdbr0 t=2016-12-31T07:58:23+0300
lvl=info msg="Starting /dev/lxd handler" t=2016-12-31T07:58:23+0300
lvl=info msg="LXD is socket activated" t=2016-12-31T07:58:23+0300
lvl=info msg="Expiring log files" t=2016-12-31T07:58:23+0300
lvl=info msg="Pruning expired images" t=2016-12-31T07:58:23+0300
lvl=info msg="Updating images" t=2016-12-31T07:58:23+0300
lvl=info msg="REST API daemon:" t=2016-12-31T07:58:23+0300
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2016-12-31T07:58:23+0300
lvl=info msg=" - binding TCP socket" socket=[::]:8443 t=2016-12-31T07:58:23+0300
lvl=info msg="Done pruning expired images" t=2016-12-31T07:58:23+0300
lvl=info msg="Done expiring log files" t=2016-12-31T07:58:23+0300
lvl=info msg="Done updating images" t=2016-12-31T07:58:25+0300
```

**Comment by techtonik** [comment]
Here - https://github.com/lxc/lxd/blob/8dbee76dff9530c515c2899bb75b1dc53129aaae/lxd/networks_utils.go#L632

**Comment by techtonik** [comment]
Maybe there is conflict between LXD  and LXC started dnsmasq?

**Comment by cryptofuture** [comment]
You should find info in /var/log/lxd/lxd.log (or lxd old logs) if its dnsmasq issue. Also could be you miss  `ipv4.nat: "true"` in container settings. But since yout use default intergace and profile that should be ok. Check [this](https://github.com/lxc/lxd/issues/2688) if this is something with dnsmasq  you could have the same problem. Checking your containername logs is good idea too.

**Comment by techtonik** [comment]
@cryptofuture https://github.com/lxc/lxd/issues/2767#issuecomment-269849685 is the log from `/var/log/lxd/lxd.log` (updated comment to mention that). There is only one string in container log for `ruby`:
```
lxc 20161231043207.434 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 28949, expected pid 28951.
```

**Comment by cryptofuture** [comment]
Why it starts in first place?, try disable it. As I remember even lxd before network api already used lxdbr, and lxcbr was used before already old lxd-bridge unit. Probably you run custom and old [lxc-dns](https://github.com/eazel7/lxc-dns). Also you better delete lxcbr0 interface.
```
lxc-dns+  2705  0.0  0.0  54312   396 ?        S    Dec23   0:00 dnsmasq -u lxc-dnsmasq --strict-order --bind-interfaces --pid-file=/run/lxc/dnsmasq.pid --listen-address 10.0.3.1 --dhcp-range 10.0.3.2,10.0.3.254 --dhcp-lease-max=253 --dhcp-no-override --except-interface=lo --interface=lxcbr0 --dhcp-leasefile=/var/lib/misc/dnsmasq.lxcbr0.leases --dhcp-authoritative
```
You need to play with systemd to find out what starts lxc-dns in first place, mb you even have some rogue packages left. If you have some host to copy containers, it could be even be faster to purge lxc packages and reinstall lxd, then find actual source.

**Comment by techtonik** [comment]
I could not find any trace of `lxc-dns` and I couldn't find who starts dnsmasq. There is `lxc-dnsmasq` user, though.

**Comment by stgraber** [comment]
So, the line:

    err="readlink /proc//exe: no such file or directory" lvl=eror msg="Failed to bring up network" name=lxdbr0 t=2016-12-31T07:58:23+0300

Is the problem here I think. That's causing dnsmasq to fail to start.
I'm not entirely sure why that is, but that's clearly a bug somewhere in our code which we haven't seen until now.

What do you have in /var/lib/lxd/networks/lxdbr0/dnsmasq.pid?

**Comment by techtonik** [comment]
> What do you have in /var/lib/lxd/networks/lxdbr0/dnsmasq.pid?

0 size file created Dec 15 with rw for `root`.

**Comment by stgraber** [comment]
That may be the problem. Can you remove it and restart lxd (systemctl restart lxd)?

That should at least give you a different error in /var/log/lxd/lxd.log

**Comment by techtonik** [comment]
No errors. After restart it didn't work, then I restarted container, then started to look at logs again, and at some point it worked. I guess I had to wait for `dnsmasq` to initialize. So the problem is now solved. Thanks for support. =) And have a nice year ahead!

**Comment by stgraber** [comment]
Thanks. I'll send a change to have LXD treat an empty pid file the same as if it was missing, that should fix this from reoccurring.

**Comment by ackerleytng** [comment]
I have this problem too, removing `/var/lib/lxd/networks/lxdbr0/dnsmasq.pid` also solved my issue.

**Comment by eviweb** [comment]
Hi everybody,
I just ran into the same issue, with just one difference, the `/var/lib/lxd/networks/lxdbr0/dnsmasq.pid` wasn't empty and contained `9258`.
The error log was: `err="readlink /proc/9258/exe: no such file or directory" lvl=eror msg="Failed to bring up network" name=lxdbr0 t=2017-01-23T10:24:44+0100`
Removing `/var/lib/lxd/networks/lxdbr0/dnsmasq.pid`, and then restarting the `LXD` service and each previously running containers solved the issue.
Eric

**Comment by gutschke** [comment]
I somehow got myself into a state where I have the same problem @eviweb encountered. Only, it happens on every reboot of the machine. The PID file doesn't get removed when LXD shuts down, and when rebooting, it fails to start the DNSMasq daemon.

I'll probably eventually figure out what is preventing my system from doing a clean shutdown. But as a defense-in-depth, it would be nice if LXD either deleted stale PID files at system boot, or simply detected that a file was stale and ignored it.

**Comment by knitzsche** [comment]
I had the same issue. Same steps fixed it:
sudo rm /var/lib/lxd/networks/lxdbr0/dnsmasq.pid
sudo systemctl restart lxd
lxc restart mycontainer
now it has an IPv4 address.

lxc: 2.0.8-0ubuntu1~16.04.2
lxd: 2.5-0ubuntu1~ubuntu16.04.1~ppa1
(maybe that ppa version was the issue... it arrived from the ubuntu-sdk-team ppa which I've now killed off:
 *** 2.5-0ubuntu1~ubuntu16.04.1~ppa1 500
        500 http://ppa.launchpad.net/ubuntu-sdk-team/ppa/ubuntu xenial/main amd64 Packages)

**Comment by stgraber** [comment]
@knitzsche yeah, 2.5 is very very much unsupported at this time and indeed never received the bugfix for the dnsmasq pid issue.

On 16.04, you should either run LXD 2.0.10 (xenial-updates) or LXD 2.17 (xenial-backports). The former doesn't have support for LXD managed networking and the latter does contain the fix for this issue.
