### ISSUE TITLE
Relaunch Container

### ISSUE THREAD

**Issue by jkroepke** [lxc/lxd#2768]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4
   * LXC version: 2.0.6
   * LXD version: 2.7
   * Storage backend in use: btrfs

# Issue description

Adding a Command like lxc relaunch or reinstall. The command should be drop the current container volume and replace it with the base image.

Instead lxc delete; lxc launch, this command should not drop the device config (like mac address) or uid/gid range.

**Comment by stgraber** [comment]
Please comment in #2303 with your particular use case. This issue also offers some pointers on what can be done today.
