### ISSUE TITLE
Added device options on lxc launch

### ISSUE THREAD

**Issue by jkroepke** [lxc/lxd#2769]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4
   * LXC version: 2.0.6
   * LXD version: 2.7
   * Storage backend in use: btrfs

# Issue description

Adding a parameter to define device options like mac address to lxc launch, since the mac is the base for the SLAAC ip6 address.

**Comment by stgraber** [comment]
We decided not to add a way to define a full device during launch as it's simply impractical from a command line design point of view.

The API naturally supports it so custom clients are welcome to do so (and some do).

That being said, there is an easy way around your specific issue:

    lxc launch ubuntu:16.04 c1 -c volatile.eth0.hwaddr=00:16:3e:41:9b:12


For all other cases, the recommended way to do it is:

    lxc init ubuntu:16.04 c1
    lxc config device ...
    lxc start c1

**Comment by jkroepke** [comment]
It looks likelxd respect the value for the dhcp leases, if lxd manage the address pool. Thats fine.
