### ISSUE TITLE
Cannot use iptables CLUSTERIP inside container

### ISSUE THREAD

**Issue by Jean-Daniel** [lxc/lxd#2773]
# Required information

 * Ubuntu 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-57-generic
   * LXC version: 2.0.8
   * LXD version: 2.0.8
   * Storage backend in use: ZFS

# Issue description

I'm trying to setup Network load balancing by using the linux built-in CLUSTERIP capabilities in a unprivileged container.
For the record, CLUSTERIP is a way to define the same IP on multiple machines et use MAC multicast to broadcast the packets on each machine. The the kernel use iptables CLUSTERIP rule to filter the packets on each hosts, so each packet is handled by one host only.

Creating the rule work fine:

$ iptables -I INPUT -i eth0 -d 10.0.1.14 -j CLUSTERIP --new --hashmode sourceip --clustermac 01:aa:7b:47:f7:d7 --total-nodes 2 --local-node 1

It creates an entry in the procfs at  /proc/net/ipt_CLUSTERIP/10.0.1.14

My issue is that that file must be readable but it is created with mode  0600 using the host root user, and so is unreadable by the guest root user.

# Steps to reproduce

 1. Step one
Create a CLUSTERIP rule:
$ iptables -I INPUT -i eth0 -d 10.0.1.14 -j CLUSTERIP --new --hashmode sourceip --clustermac 01:aa:7b:47:f7:d7 --total-nodes 2 --local-node 1

 2. Step two
$ cat  /proc/net/ipt_CLUSTERIP/10.0.1.14
cat: /proc/net/ipt_CLUSTERIP/10.0.1.14: Permission denied

**Comment by stgraber** [comment]
Hi,

That's a kernel bug. If the ipt_CLUSTERIP module is in fact properly namespaced (and the fact that you were allowed to use it suggests it is), then it should also allow writing to any file it creates in proc.

You'll need to file this as a kernel bug, possibly against the Ubuntu kernel on Launchpad (https://launchpad.net/ubuntu/+source/linux/+filebug) or contact the author of that netfilter plugin directly to have them look into this (probably best to confirm that this hasn't been fixed already though).

As for LXD itself, I'm closing this issue as there's unfortunately nothing we can do in LXD itself to fix permission issues that the kernel creates.
