### ISSUE TITLE
'lxc exec' returns 0 if containers reboot when command is running

### ISSUE THREAD

**Issue by iainlane** [lxc/lxd#2774]
In one window:
```
 $ lxc exec test sleep infinity
```
In another:
```
 $ lxc exec test reboot
```
In the first again:
```
 $ echo $?
 0
```

I would like to be able to tell if the command stopped because of the container rebooting (or stopping, I guess). It would be nice if this were communicated by the exit code of `lxc exec`.

The actual issue was that we were experiencing a problem with rebooting in Ubuntu's autopkgtest infrastructure when dealing with testbeds that were on lxd containers. There was a timing issue where we were rebooting containers while workloads were running in them (a bug on our side) and falsely reporting that the tests succeeded when in fact they didn't run to completion. Our code wasn't able to catch this happening though, because the `lxc exec` that spawned the workload was returning an exit code of 0 back to us, which made us think that everything was okay.

**Comment by iainlane** [comment]
I suppose there's a problem that it's not possible to differentiate between `lxc exec` erroring and the command itself.

**Comment by brauner** [comment]
Well, we currently explicitly return `0` when the command was killed by signal. We can however change that. I think we left it in this state since the test suite fails, when `lxc exec` gets killed by a signal (See https://github.com/lxc/lxd/blob/master/lxd/container_exec.go#L285). @stgraber , what do you think?

**Comment by stgraber** [comment]
@brauner what does ssh do in such cases? (that's our usual reference for exec)

**Comment by brauner** [comment]
@stgraber, reporting `-1` aka `255` if you do anything else than `SIGTERM`.

**Comment by stgraber** [comment]
@brauner is that something we can easily do too?

**Comment by brauner** [comment]
Yes.
