### ISSUE TITLE
Map host block devices with another name in  containers

### ISSUE THREAD

**Issue by dann1** [lxc/lxd#2776]
# Feature Request
It would be nice if when adding **unix-block devices** to a container they could be mapped inside with a custom name, ex. **/dev/rbd1** as **/dev/hda1**, currently the only similar options to this one, are to mount a host block device or a directory into another directory inside the container, in type **disk** devices; or the case of **unix-block** devices, to allow a host device inside the container.

**Comment by stgraber** [comment]
You can do that today so long as you have the minor= and major= specified. When those two fields are specified, path= can be set to whatever you want the path to be in the container.

**Comment by dann1** [comment]
what should I put in minor= and major= in order to achieve this?

**Comment by brauner** [comment]
@dann1, you should set it to the major and minor device number you would like the device to have in the container. If you want to keep the default device numbers the device has on the host you can just look at the corresponding entry in `/dev`. For example, if you wanted to have `/dev/kvm` inside the container with the same major and minor device number as on the host but with a different name or on a different path, look at:

```
chb@conventiont|~
> ls -al /dev/kvm
crw-rw----+ 1 root kvm 10, 232 Jan  2 10:29 /dev/kvm
```

the major device numver is `10` and the minor device numer is `232`.

**Comment by dann1** [comment]
Thank you all, I wasn't aware this could be done, the first time I read the documentation regarding major and minor I didn't understand it.
