### ISSUE TITLE
Howto easily set static IP for all my containers ?

### ISSUE THREAD

**Issue by pxcluster** [lxc/lxd#2780]
My host has only one IP4 address and I've written a tool which generates all the necessary NAT iptables rules for my containers. Like : 

iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 8001 -j DNAT --to-destination 10.0.3.13:80
iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 8011 -j DNAT --to-destination 10.0.3.15:80
iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 8016 -j DNAT --to-destination 10.0.3.16:80
iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 53 -j DNAT --to-destination 10.0.3.17:53
iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 1194 -j DNAT --to-destination 10.0.3.19:1194
iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 8000 -j DNAT --to-destination 10.0.3.10:8000
iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 8015 -j DNAT --to-destination 10.0.3.20:80
...

This used to be fined with lxc, but lxd is now changing the networking address at each boot/restart. Is there an elegant and simple way to fix this network address once and for all ? 

- Ubuntu 16.10
- LXD 2.4.1

**Comment by karolpiatek** [comment]
Hi.

To assign the static IP for the container, please follow this guide.

https://www.stgraber.org/2016/10/27/network-management-with-lxd-2-3/

I could recommend You create the custom network and create additional profile for Your containers.

**Comment by pxcluster** [comment]
Hi,
>
> To assign the static IP for the container, please follow this guide.
>
> https://www.stgraber.org/2016/10/27/network-management-with-lxd-2-3/
>
> I could recommend You create the custom network and create additional 
> profile for Your containers.
>

Thanks ! I didn't know the command :

lxc network set lxdbr0 ipv4.address 10.3.0.1/24

would permanently remove the random generation of the network address... 
It could be nice to word this as :

"How to permanently replace the random network address of lxdbr0 by a 
user defined static one (need a restart btw)"


Regards
