### ISSUE TITLE
`lxc network edit` gets stuck in edit loop

### ISSUE THREAD

**Issue by OddBloke** [lxc/lxd#2783]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.9.0-11-generic
   * LXC version: 2.0.6-0ubuntu5
   * LXD version: 2.7-0ubuntu2
   * Storage backend in use: dir

# Issue description

When running `lxc network edit <network>` and quitting the editor without changes, I see the following error message:

```
Config parsing error: not implemented
Press enter to open the editor again
```

It's not clear that I can Ctrl-C at this point, so I ended up going through this loop a few times. Not hitting this warning for unmodified configuration would be ideal, but at the very least a clear way of exiting would be good.

**Comment by stgraber** [comment]
@OddBloke that's because your calling "edit" against a LXD server which doesn't implement the network API, which is what that "not implemented" error comes from.

#1926 will include feature checks to better handle this kind of thing, though the error you got seems vaguely appropriate :)
