### ISSUE TITLE
the max UID in lxd container

### ISSUE THREAD

**Issue by raindylong** [lxc/lxd#2784]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-21-generic
   * LXC version: 2.0.8
   * LXD version: 2.0.8
   * Storage backend in use:

# Issue description

============
root@myserver:~# lxc list

+----------------+---------+---------------------+------+------------+-----------+
|      NAME      |  STATE  |        IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+----------------+---------+---------------------+------+------------+-----------+
| GO192-168-2-20 | RUNNING | 192.168.2.20 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+---------------------+------+------------+-----------+
| amazed-hawk    | STOPPED |                     |      | PERSISTENT | 0         |
+----------------+---------+---------------------+------+------------+-----------+]

root@myserver:~# lxc exec GO192-168-2-20 bash
root@GO192-168-2-20:~# cat /etc/issue.net 
Ubuntu 16.04.1 LTS
root@GO192-168-2-20:/var/log# > auth.log 
root@GO192-168-2-20:/var/log# id ejoybox
uid=9000001(ejoybox) gid=1001(ejoybox) groups=1001(ejoybox)
root@GO192-168-2-20:/var/log# su - ejoybox
setuid: Invalid argument
root@GO192-168-2-20:/var/log# cat auth.log 
Jan 11 13:55:51 GO192-168-2-20 su[2001]: Successful su for ejoybox by root
Jan 11 13:55:51 GO192-168-2-20 su[2001]: + ??? root:ejoybox
Jan 11 13:55:51 GO192-168-2-20 su[2001]: pam_unix(su:session): session opened for user ejoybox by (uid=0)
Jan 11 13:55:51 GO192-168-2-20 systemd-logind[234]: Failed to mount per-user tmpfs directory /run/user/9000001: Invalid argument
Jan 11 13:55:51 GO192-168-2-20 su[2001]: pam_systemd(su:session): Failed to create session: Invalid argument
Jan 11 13:55:51 GO192-168-2-20 su[2002]: bad user ID `9000001' for user `ejoybox': Invalid argument
Jan 11 13:55:51 GO192-168-2-20 su[2001]: pam_unix(su:session): session closed for user ejoybox
Jan 11 13:55:51 GO192-168-2-20 systemd-logind[234]: Failed to remove runtime directory /run/user/9000001: No such file or directory

The UID "9000001" is error in lxc container , but ok in the original ubuntu .

**Comment by tych0** [comment]
On Wed, Jan 11, 2017 at 06:01:17AM -0800, Raindy Long wrote:
> The template below is mostly useful for bug reports and support questions.
> Feel free to remove anything which doesn't apply to you and add more information where it makes sense.
> 
> # Required information
> 
>  * Distribution: ubuntu
>  * Distribution version: 16.04
>  * The output of "lxc info" or if that fails:
>    * Kernel version: 4.4.0-21-generic
>    * LXC version: 2.0.8
>    * LXD version: 2.0.8
>    * Storage backend in use:
> 
> # Issue description
> 
> `
> root@myserver:~# lxc list
> +----------------+---------+---------------------+------+------------+-----------+
> |      NAME      |  STATE  |        IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
> +----------------+---------+---------------------+------+------------+-----------+
> | GO192-168-2-20 | RUNNING | 192.168.2.20 (eth0) |      | PERSISTENT | 0         |
> +----------------+---------+---------------------+------+------------+-----------+
> | amazed-hawk    | STOPPED |                     |      | PERSISTENT | 0         |
> +----------------+---------+---------------------+------+------------+-----------+
> root@myserver:~# lxc exec GO192-168-2-20 bash
> root@GO192-168-2-20:~# cat /etc/issue.net 
> Ubuntu 16.04.1 LTS
> root@GO192-168-2-20:/var/log# > auth.log 
> root@GO192-168-2-20:/var/log# id ejoybox
> uid=9000001(ejoybox) gid=1001(ejoybox) groups=1001(ejoybox)
> root@GO192-168-2-20:/var/log# su - ejoybox
> setuid: Invalid argument
> root@GO192-168-2-20:/var/log# cat auth.log 
> Jan 11 13:55:51 GO192-168-2-20 su[2001]: Successful su for ejoybox by root
> Jan 11 13:55:51 GO192-168-2-20 su[2001]: + ??? root:ejoybox
> Jan 11 13:55:51 GO192-168-2-20 su[2001]: pam_unix(su:session): session opened for user ejoybox by (uid=0)
> Jan 11 13:55:51 GO192-168-2-20 systemd-logind[234]: Failed to mount per-user tmpfs directory /run/user/9000001: Invalid argument
> Jan 11 13:55:51 GO192-168-2-20 su[2001]: pam_systemd(su:session): Failed to create session: Invalid argument
> Jan 11 13:55:51 GO192-168-2-20 su[2002]: bad user ID `9000001' for user `ejoybox': Invalid argument
> Jan 11 13:55:51 GO192-168-2-20 su[2001]: pam_unix(su:session): session closed for user ejoybox
> Jan 11 13:55:51 GO192-168-2-20 systemd-logind[234]: Failed to remove runtime directory /run/user/9000001: No such file or directory
> `
> The UID "9000001" is error in lxc container , but ok in the original ubuntu .

What are the contents of your /etc/sub{u|g}id files? My guess is you
don't have uid 9000001 mapped.

**Comment by stgraber** [comment]
Indeed the usual maps in /etc/subuid and /etc/subgid are 65536 ids large. You'll need to bump them to fit your need.

If using security.idmap.isolated you'll also need to bump security.idmap.size to match (but that's unlikely as it's not the default).

**Comment by raindylong** [comment]
Thanks @stgraber & @tych0 .
All the accounts are stored in OpenLdap server , so I think I need to write a script to transfer all the UID to fix my need .

Thanks again .

**Comment by stgraber** [comment]
@raindylong most ldap/ad auth servers will typically use a contiguous offset id range, so contiguous starting at 10000 or something.

On most such systems, I just change the LXD map size from "65536" to "1000000" which will allow containers to use from uid 0 to uid 999999, typically way enough to fix the problem.
