### ISSUE TITLE
Network interface name inside the container

### ISSUE THREAD

**Issue by dann1** [lxc/lxd#2796]
Quick question.
Is it possible to change the name of a network interface inside the container, in a way that it doesn't have the '**@if##**' suffix? The thing is, a 3rd party app runs over the exit of the command *ip link* and the @if is making it misbehave. I have **eth0@*if17*** instead of just **eth0**

**Comment by tych0** [comment]
Not really; this has to do with how iproute2 displays veth pairs whose other end isn't in the current network namespace. You could write a little wrapper that chops this off if you really had to.

**Comment by dann1** [comment]
Well that's what I did, thanks anyway
