### ISSUE TITLE
SSH into container from outside of the network.

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#2802]
Hi @stgraber 

I configured the container to run on a standalone bridge instead of lxdbr0 and was able to communicate to & from outside the network.

I was unable to ssh into the containers from outside the network, returns with an error permission denied from ssh.
upuvvad1@udaya:~$ ssh 172.16.180.1
Permission denied (public key).

I have seen other methods on how to fix this,
  a) Add host's public key to authorization file of container,
  b) Add NAT rule to the lxd host, for port forwarding.

Is there anyway, we can solve without the above the 2 options.
I don't want to give access to the containers without the password.

**Comment by stgraber** [comment]
That error simply means that your container either doesn't have a "upuvvad1" user or that the ssh daemon in the container only authenticates using public keys (as the error states).

This has nothing to do with LXD or your network configuration. It's a simple matter of properly configuring your ssh daemon in the container. In your case, it may be a matter of enabling password authentication in the ssh configuration, or to configure your user in the container to have your public ssh key in its ~/.ssh/authorized_keys.
