### ISSUE TITLE
Triple check that dnsmasq works properly as non-root

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#2804]
As LXD 2.8 will have dnsmasq running as a non-root user. We should be doing some extra upgrade testing to ensure that there will be no problem when switching from root owned to nobody owned dnsmasq.

Area to check are:
 - Change static assignment (causes dnsmasq to be signaled to re-read the files)
 - Change the logic a bit to select "lxd", then "nobody" and finally just run as "root". This should cover all cases including those of confined environments with limited users.

**Comment by stgraber** [comment]
Jan 24 14:52:14 dakara dnsmasq[30048]: cannot read /var/lib/lxd/networks/lxdbr0/dnsmasq.hosts: Permission denied

**Comment by stgraber** [comment]
So the change very much regressed dnsmasq by not letting it re-read its config post-start.

**Comment by stgraber** [comment]
So we need to propagate execute permissions down the networks/ tree to allow traversal and then make sure the dnsmasq files are owned by the same user which runs the daemon.

**Comment by georgebushfourtwenty** [comment]
Have you abandoned this idea?

**Comment by stgraber** [comment]
No, it's been closed as it was implemented. dnsmasq in LXD usually runs as the lxd user.
```
root     1963759  0.4  1.0 2155212 174372 ?      Sl   10:14   0:38  \_ /var/snap/lxd/common/lxd.debug --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group l
xd --debug
lxd      1963913  0.0  0.0   7436  1768 ?        Ss   10:14   0:00      \_ dnsmasq --keep-in-foreground --strict-order --bind-interfaces --except-interface=lo --pid-file= --no-ping --interface=lxdbr0 --dhcp-rapid-commit --listen-address=10.166.11.1 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases --dhcp-hostsfile=/var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts --dhcp-option-force=119,lxd, stgraber.net --dhcp-range 10.166.11.2,10.166.11.254,1h --listen-address=fd42:4c81:5770:1eaf::1 --enable-ra --dhcp-range ::,constructor:lxdbr0,ra-stateless,ra-names -s lxd -S /lxd/ --conf-file=/var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.raw -u lxd -g lxd
```

Recently we also added apparmor confinement on this process for extra security.
