### ISSUE TITLE
Appending text to file inside a container does not create file (lxc exec container -- "echo test > file.sh")

### ISSUE THREAD

**Issue by gregsifr** [lxc/lxd#2807]
The below code does not create a file inside the container.

```
lxc launch ubuntu: test
lxc exec test -- "echo test > /home/ubuntu/file.sh"
lxc exec test -- ls /home/ubuntu
```

**Comment by stgraber** [comment]
That's because there is no command called "echo test > /home/ubuntu/file.sh" in your container.

I suspect you want:

    lxc exec test -- sh -c "echo test > /home/ubuntu/file.sh"
