### ISSUE TITLE
host block devices can be seen inside the container 

### ISSUE THREAD

**Issue by dann1** [lxc/lxd#2810]
# System Info
I have this issue in archlinux and ubuntu.

 * Distribution: ArchLinux/Ubuntu
 * Distribution version: - / 16.04
 * **lxc info:**
#### Archlinux
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 10.8.2.200:8443
  - 192.168.2.1:8443
  - 192.168.162.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificatefingerprint: d8c745cfede9ded4befe182ed924757761d464f20861576dd1e8843a5dc03e6f
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.13-1-ARCH
  server: lxd
  serverpid: 916
  serverversion: "2.7"
  storage: btrfs
  storageversion: "4.9"
config:
  core.https_address: '[::]:8443'
  core.https_allowed_headers: Content-Type
  core.https_allowed_methods: GET, POST, PUT, DELETE, OPTIONS
  core.https_allowed_origin: '*'
public: false

#### Ubuntu
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 10.8.9.48:8443
  - 192.168.1.1:8443
  - 192.168.0.1:8443
  - 192.168.122.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificatefingerprint: e5af923e8761cee98e815442ae22ba4c47dd80c0caa66761a3e6b4f22d20d371
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-59-generic
  server: lxd
  serverpid: 2236
  serverversion: 2.0.8
  storage: btrfs
  storageversion: "4.4"
config:
  core.https_address: 0.0.0.0:8443
  core.trust_password: true
public: false
# Description
If you execute the lsblk command, which displays block devices, inside the container the hosts block devices can be seen. This is no problem for the container execution, */dev/*  directory doesn't have these devices but I think the container is not supposed to be able to see this info.  

**lsblk**

NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 894.3G  0 disk
|-sda4   8:4    0   7.3G  0 part [SWAP]
|-sda2   8:2    0  18.6G  0 part
|-sda3   8:3    0 867.8G  0 part /dev/.lxd-mounts
`-sda1   8:1    0   512M  0 part

**Comment by stgraber** [comment]
That's unfortunately how the kernel works. /sys isn't namespaced so any information available in it will be seen by all containers. They won't be able to do anything with it as the kernel does enforce permissions though.

We've been discussing a fuse overlay for /sys as part of lxcfs, but doing so would be very complex and come with a pretty high performance impact too.


Anyway, closing this LXD issue as it's not something LXD can do anything about. This is either a kernel issue (as part of a new device namespace, which has so far failed to gain any traction) or something that can possibly be papered over by lxcfs in userspace.
