### ISSUE TITLE
support windows container

### ISSUE THREAD

**Issue by sequoiar** [lxc/lxd#2812]
Is LXD possible to support Windows container ?

**Comment by stgraber** [comment]
Hi,

LXD is designed in a way that it could support different container runtimes for different operating systems. So in theory it could be made to use Windows containers on windows, Jails on BSDs, Zones on Solaris, ...

This would however be a massive amount of work for anyone to add any of those and isn't something we plan on doing ourselves any time soon. Should someone be interested in doing the port of the LXD daemon to a new operating system, we'd certainly be happy to give pointers and help reviewing the code.

**Comment by sequoiar** [comment]
@stgraber thanks for clarify.
