### ISSUE TITLE
lxd forkstart fails on ESXi

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#2815]
I'm proxying this bug from Launchpad:
 
https://bugs.launchpad.net/juju/+bug/1637230

This was running on "ESXi VMs", but I don't know the rest of the details.

I looked through the associated log files but didn't see anything that was obvious that we were doing wrong. Is there particular log files that could help you investigate? I don't have personal access.

**Comment by stgraber** [comment]
Marking as Incomplete to match the Launchpad bug's status while we're waiting for various debug information.

**Comment by stgraber** [comment]
Not seen any progress on this on the Launchpad side and nothing actionable for us to do, so closing this upstream issue. If a LXD bug is identified in the Launchpad issue, we'll open a detailed bug report here.
