### ISSUE TITLE
Cached image expiry

### ISSUE THREAD

**Issue by roelrymenants** [lxc/lxd#2816]
# Required information

 * Distribution: **ubuntu**
 * Distribution version: **xenial**
 * The output of "lxc info":
```
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 10.199.28.1:8443
  - 10.0.4.116:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFXzCCA0egAwIBAgIRAJum4s+2uz8HmaJj7E9OQ6IwDQYJKoZIhvcNAQELBQAw
    PjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEeMBwGA1UEAwwVcm9vdEBp
    bnRlZ3JhdGlvbnRlc3RzMB4XDTE3MDExMjE0Mzk0NloXDTI3MDExMDE0Mzk0Nlow
    PjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEeMBwGA1UEAwwVcm9vdEBp
    bnRlZ3JhdGlvbnRlc3RzMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
    5rKCFMzxWpLY1/QAjA0z63T3e3L3pOILyKI95oEi/1sv3QDVyLNQRg5M9Eg6RHs+
    WfZICqXnUGQFqRmtyKO1k5uqeBZr/EMXLSHx1HmrZoxz5HbYeXWF2vimpufMcwy6
    dNQiq1ThJnQ/+TpjiW90puqo2Mv3WFxFEcYr26ZrWX4QHC2ecNS7XoampQNQPGQw
    Rahi0uTw2PD5+IFurgdcZ/E7KsChCb036ONkSI0kuCcGehU4Ny930Nk4530lWNgK
    TlFr89zvmGTHyAFs+zcI4Dx2Z9vwTo5fJqHiq5mKysC0Fn8qokeQV96QSAjCMldt
    GzPg3PqV5+cCiLPheNEAnolyQwpsSYyNwH242s2mGRQ7X/mRVvS3MnFTSQHuilSy
    jvebuJY1mtapIU+6diQUaugYztV8dfuF2MSXis6XxWWD74/T1vOS4zwWACQiENDL
    GNxM8LiNU/7aP/s17R3neALLTRShbG4JXdny0cm15M+IMNCa6ybHN4PuDcqCewZD
    MKOAfosmj9iwejHxDg0NgREWZIC8Rg9rZjNXjbHXqB67yzg4nVqJntM1/PKarGP6
    3OAnUrY9cZ0CnMWDlxDkezF/yTTtvYdD74gLfg2DRDwn2OKW35+uxYYbJY5XdgR1
    41k3uaOdc9xSrVu1IO0PNlSrm1dnB9HMQav4YHgUAxkCAwEAAaNYMFYwDgYDVR0P
    AQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwIQYD
    VR0RBBowGIIQaW50ZWdyYXRpb250ZXN0c4cECgAEdDANBgkqhkiG9w0BAQsFAAOC
    AgEAzwUf2cD44JiHACh1KcOuJtijWNhZ7pbtQcLz0I0lZgqQEGL5ewXzXXgG5zir
    SrrDc1bZTT8pu1dv0PBb/Qnoo4uj0lWYR6ICZa2yOz8IdTh1Tx0Q4gJZ8u3/9LNb
    enNkr8WzCp0myOQis4hnq4C6bB6wLS8NUcvOE0BzY2I5oNqISf1aWG14mmn7NEjQ
    2aWf+I8w84MPvLICYVexhk9BhdZBey9I+mh8zcmXMTbpx2IaH/RjZeOhvMiGAftQ
    0gqW97n2llt7KCphk+2DhNZI0SuSJ38i+6T0bvzt4de8XGBPtBqvjhUXluy1lQ/O
    SkQQVi+/d2GZKzEoEbyAbkCRKLypA+BkhLVrkCiSaokUIeQb0jTk/HQJRZImf/Ux
    cY7OySz32bh8mV+vB+p6AUDqc4za8WDlZCo4x//7kCxxQdV0VpFLpxHDY1QyH24d
    sNZOte3IUN4u7/DEChJRORzZ0Qc7WL2oK4367HGe19p9wQ2Lsz9g8W+kY1ovvNFd
    JUrMoH+xbIATSmUHZiK8ziEesaBeK2s71GWq6KdF3KXrPbsBre9MroFsLejgc/gV
    //HhR0jsdmuLjOO9v0n9cxvzf2DDoJDL4SmOu3sDr4pgQcME890QKj5z/6jnyVNZ
    4QAO/7avQrbR/4Pc6FMx7A4xypgK8ya3njAmXMrRcogp2Iw=
    -----END CERTIFICATE-----
  certificatefingerprint: 5c0dd7c72d0763c255ee0be91e51ae4fb95bdaf4814c86063eeedf6704c2073b
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.0-34-generic
  server: lxd
  serverpid: 4161
  serverversion: 2.0.8
  storage: btrfs
  storageversion: "4.4"
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  images.remote_cache_expiry: "1"
public: false
```
# Issue description

The cached image expiry process is a bit unclear.
- The docs seem to suggest it is based on the last access time, but (as far as I can tell) the code seems to check the creation_date.
- When I create an image by publishing a container, the creation time is always set to 0001/01/01 00:00 UTC. Just like the expiry time. Since that expiry time is long past, I would expect it to get purged immediately, but it doesn't.
- When I launch a container with ubuntu:x, the creation time for the cached image is 2016/12/14 00:00 UTC, the expiry is 2017/07/20 00:00 UTC. However, `images.remote_cache_expiry` is set to 1, so I would expect the expiry to be either tomorrow (based on the last access) or 2016/12/15 (based on creation time).

# Steps to reproduce

 1. `lxc launch ubuntu:x test` --> cached image with a sensible creation time but non-explicable expiry time?
 2. Do something interesting in container test
 3. `lxc publish test --alias test` --> creates a (non-cached) image with creation time 0001/01/01 00:00 UTC
4. On another machine `lxc launch someremote:test newtest` --> cached image with creation time and expiry time set to 0001/01/01 00:00 UTC

**Comment by stgraber** [comment]
The expiry you see in "lxc image info" is the one declared in the image. Your value means it doesn't have one.

This is unrelated from the cache expiry which is X days from image LastUsedAt. The LastUsedAt value isn't reported by the client tool in any released LXD right now, but will in LXD 2.9 and 2.0.9.

```

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc image info ubuntu-core
Fingerprint: 25981220eb90ad0637d7be953d4bac9cfe0ef0f0b99bc60fbbb583ead89351de
Size: 370.85MB
Architecture: x86_64
Public: no
Timestamps:
    Created: 2016/12/09 13:14 UTC
    Uploaded: 2016/12/09 15:01 UTC
    Expires: never
    Last used: 2016/12/09 15:01 UTC
Properties:
    description: Ubuntu Core 16 amd64 (release)
    os: ubuntu core
    release: 16
    architecture: amd64
Aliases:
    - ubuntu-core
Auto update: disabled
```

The Expires above refers to when the image author indicated the image would be invalid. This is typically the end of life of the OS release for the official images (ubuntu:x for example). The cache expiry is an internal value which isn't visible through the API other than by doing the math yourself based on the Last used value.
