### ISSUE TITLE
is it possible to add custom info to ../1.0/containers?

### ISSUE THREAD

**Issue by MicZet** [lxc/lxd#2819]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-59-generic

# Issue description

It's not an issue - rather a question...
Is it possible to add custom information to  ../1.0/containers?

so at the moment there is list of containers with status, name and type... and I'd like to add something new so later I can use it in my automation script

Regards

**Comment by stgraber** [comment]
If you're looking for a way to tag/filter containers, you can use the user.* config keys for that.

    lxc config set c1 user.something somevalue

**Comment by MicZet** [comment]
Thanx for answer... yes I'm aware of that... and this is our plan B... but our reporting tool lists containers based on API call to
https://SERVERIP/1.0/containers
so that's why my question is here...
so i assume we will need to change our reporting tool as it's impossible to add anything there ?!
am i right?

regards,

**Comment by stgraber** [comment]
GET https://SERVERIP/1.0/containers only returns a list of URL, so yeah, nothing you can do here.

You can use "GET https://SERVERIP/1.0/containers?recursion=1" which will get you the config for every container and so let you access the user.* keys.

**Comment by dann1** [comment]
How could I link **user.\*config** with the template hooks, I'd like to set the hostname inside the container with templates, I executed the **hostname** command inside the conatiner but I also need to rename the files

**Comment by stgraber** [comment]
All the container configuration keys are exported to the file templates (see doc/image-handling.md) so you can read those values from inside the templates and write whatever you want to paths inside the container.
If you need to run commands in the container, your best bet is probably to have a template write an init script which is then executed by the container on startup.

**Comment by dann1** [comment]
I edited the *hostname.tpl*, which contains  *{{ container.name }}*, and wrote **container.user.hostname**, a string with the hostname I want, but it didn't work, the file was empty, am I doing something wrong?

**Comment by stgraber** [comment]
@dann1 you want '{{ config_get("user.hostname", "") }}'

**Comment by dann1** [comment]
If I have a container already created and I modify the hook, does this works the next time I start the container? I tried and didn't work, {{ config_get("user.hostname", **""**) }}, also what are the double quotes after user.hostname for?

**Comment by stgraber** [comment]
If the template is marked as running on start in metadata.yaml, then yes, if it's only marked to run on copies or create, then it won't.

The second value passed to config_get is the default value if the configuration key isn't set.

**Comment by dann1** [comment]
Thanks this info is really good, where can I find more about .tpl files, there was a quick overview in your blog series, but this example wasn't.

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/blob/master/doc/image-handling.md

**Comment by dann1** [comment]
Thank you very much I had seen this document before,when getting to know LXD, I didn't know this information was in there.
