### ISSUE TITLE
LXD 2.7 networking issue after upgrading

### ISSUE THREAD

**Issue by MarkGavalda** [lxc/lxd#2820]
After upgrading LXD from 2.6 or previous versions to the latest v2.7 some (and it's important that only a few out of hundreds!) containers lose their ability to use the network. They get the same IP address however they're not accessible from the outside (via networking) nor can they access the internet. The only solution is to remove the default profile, restart, re-add the (supposedly new?) default profile and restart again. They get a new IP address and are able to use the network again.
This also happens if we lxc copy a container from a host machine that runs an older LXD version to a newer one with 2.7.
Any ideas?

**Comment by stgraber** [comment]
Nothing obvious in the 2.6 to 2.7 changelog could explain that.
It'd be great if you could get the following for an affected container:

 - lxc config show --expanded NAME
 - lxc info NAME
 - lxc network list
 - lxc network show NETWORK-NAME
 - Content of all the files in /var/lib/lxd/networks/NETWORK-NAME/
 - brctl show
 - iptables -t nat -L -n -v
 - ip6tables -t nat -L -n -v
 - ebtables -L
 - ps aux | grep dnsmasq
 - ip -4 route show
 - ip -6 route show

That should be enough to track down the whole connection chain for the container and see what may be going on.

**Comment by brauner** [comment]
@stgraber, that should probably be required information for all future network reports. :)

**Comment by MarkGavalda** [comment]
@stgraber found another container doing this, ran all the requested commands, this production server contains a lot of other containers so unnecessary/sensitive data was removed. After removing the default profile and re-adding it, this one started to work again (with a new IP address, of course).

```
root@lxdtest61:~# lxc network list
+--------+----------+---------+---------+
|  NAME  |   TYPE   | MANAGED | USED BY |
+--------+----------+---------+---------+
| ens5   | physical | NO      | 0       |
+--------+----------+---------+---------+
| lxcbr0 | bridge   | NO      | 0       |
+--------+----------+---------+---------+
| lxdbr0 | bridge   | YES     | 238     |
+--------+----------+---------+---------+



root@lxdtest61:~# lxc network show lxdbr0
name: lxdbr0
config:
  ipv4.address: 10.0.0.1/20
  ipv4.nat: "true"
  ipv6.address: none
managed: true
type: bridge
usedby:
- /1.0/containers/VuM-lxdtest61-nonet



root@lxdtest61:~# brctl show
bridge name  bridge id    STP enabled  interfaces
lxcbr0    8000.00163e000000  no    
lxdbr0    8000.fe001921e9e8  no
              vethBHKOLC



root@lxdtest61:~# iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 17879 packets, 1208K bytes)
 pkts bytes target     prot opt in     out     source               destination
   20  1200 DNAT       tcp  --  ens5   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:47487 to:10.0.1.188:80
    7   420 DNAT       tcp  --  ens5   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:48555 to:10.0.1.188:22
 1045 62700 DNAT       tcp  --  ens5   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:59011 to:10.0.1.188:443

Chain INPUT (policy ACCEPT 9419 packets, 700K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 3412 packets, 225K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 97568 packets, 5875K bytes)
 pkts bytes target     prot opt in     out     source               destination         
1274K   77M MASQUERADE  all  --  *      *       10.0.0.0/20         !10.0.0.0/20          /* generated for LXD network lxdbr0 */



root@lxdtest61:~# ebtables -L
Bridge table: filter

Bridge chain: INPUT, entries: 0, policy: ACCEPT

Bridge chain: FORWARD, entries: 0, policy: ACCEPT

Bridge chain: OUTPUT, entries: 0, policy: ACCEPT



root@lxdtest61:~# ps aux | grep dnsmasq
lxc-dns+    3951  0.0  0.0  51588  2768 ?        S    Jan25   0:00 dnsmasq -u lxc-dnsmasq --strict-order --bind-interfaces --pid-file=/run/lxc/dnsmasq.pid --listen-address 10.0.1.1 --dhcp-range 10.0.1.2,10.0.1.254 --dhcp-lease-max=253 --dhcp-no-override --except-interface=lo --interface=lxcbr0 --dhcp-leasefile=/var/lib/misc/dnsmasq.lxcbr0.leases --dhcp-authoritative
root        4501  0.1  0.0  51716  2468 ?        S    Jan25   4:52 dnsmasq -u root --strict-order --bind-interfaces --pid-file=/var/lib/lxd/networks/lxdbr0/dnsmasq.pid --except-interface=lo --interface=lxdbr0 --listen-address=10.0.0.1 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/lib/lxd/networks/lxdbr0/dnsmasq.leases --dhcp-hostsfile=/var/lib/lxd/networks/lxdbr0/dnsmasq.hosts --dhcp-range 10.0.0.2,10.0.15.254 -s lxd -S /lxd/
root     3448737  0.0  0.0  12944  1084 pts/149  S+   20:12   0:00 grep --color=auto dnsmasq



root@lxdtest61:~# ip -4 route show
default via 10.240.0.1 dev ens5 
10.0.0.0/20 dev lxdbr0  proto kernel  scope link  src 10.0.0.1 
10.0.1.0/24 dev lxcbr0  proto kernel  scope link  src 10.0.1.1 linkdown 
10.240.0.1 dev ens5  scope link
```

**Comment by stgraber** [comment]
@MarkGavalda you didn't include a number of the things I asked for.

Based on what you provided, I can't see anything wrong other than your lxdbr0 and lxcbr0 overlapping. lxcbr0 is marked as down but that may still get traffic to 10.1.0/24 to be null routed instead of hitting lxdbr0. You probably want to completely disable lxcbr0 (in /etc/default/lxc-net) rather than just bring that interface down.

If that's not the problem, then please provide the rest of the information I asked for.
