### ISSUE TITLE
lxc exec does open broken shell with input and output problems (umlauts etc)

### ISSUE THREAD

**Issue by lightonflux** [lxc/lxd#2830]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
```

apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificatefingerprint: 359705ec
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-59-generic
  server: lxd                     
  serverpid: 1892
  serverversion: 2.0.8
  storage: btrfs
  storageversion: "4.4"
config: 
  images.remote_cache_expiry: "1"
public: false

```
   * Kernel version: Linux  4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

   * LXC version: 2.0.8
   * LXD version: 2.0.8
   * Storage backend in use: btrfs

# Issue description

When opening a shell (no matter which, tested sh, bash, zsh) with `lxc exec` input and output of umlauts and other non ascii chars does not work. When writing ö,ä,ü they are interpreted as navigation keys or ignored. 

Umlauts in filenames are display as `??`. And many variables are pretty empty:

```
$env
container=lxc
USER=root
PWD=/root
HOME=/root
TERM=screen
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env

```

In some other programs started from that shell, e.g. `cat` (without any parameters) writing umlauts is not a problem. 

Some month ago (same Ubuntu version) it worked as expected. 

# Steps to reproduce

 1. Create 16.04 lxd host 
 2. Set locale: dpkg-recondigure locales, select de_DE.utf8 as default
 3. `lxd init` (dir, over network= no, bridge = yes, no ipv6)
 4. `lxc init ubuntu:16.04` (same result if container is debian)
 5. update host and container
 7. `touch /var/lib/lxd/containers/faithful-rodent/rootfs/root/umlautsäöüß.txt`
 8. `lxc exec faithful-rodent bash`
 9. input ä,ö,ü,ß and other stuff you like
 10. `ls ~`
 11. Be amazed how unusable it is if you want to create or move files.

# Information to attach

 - [ x ] container log (lxc info NAME --show-log)

```
Name: faithful-rodent
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/01/30 15:28 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 20819
Ips:
  eth0:	inet	10.0.0.7	veth54QPQD
  eth0:	inet6	fe80::216:3eff:fe73:5fe6	veth54QPQD
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 26
  Memory usage:
    Memory (current): 27.57MB
    Memory (peak): 148.44MB
  Network usage:
    eth0:
      Bytes received: 1.61kB
      Bytes sent: 1.46kB
      Packets received: 16
      Packets sent: 13
    lo:
      Bytes received: 0 bytes
      Bytes sent: 0 bytes
      Packets received: 0
      Packets sent: 0

Log:

            lxc 20170130153121.713 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 20813, expected pid 20819.


```
 - [ x ] output of the client with --debug
```

lxc exec --debug  faithful-rodent bash
DBUG[01-30|15:36:01] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_extensions":["id_map"],"api_status":"stable","api_version":"1.0","auth":"trusted","config":{},"environment":{"addresses":[],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\nMIIFPjCCAyagAwIBAgIRAI2on/ruqmAlUgZX0XbP4SowDQYJKoZIhvcNAQELBQAw\nMTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzERMA8GA1UEAwwIcm9vdEBs\neGQwHhcNMTcwMTMwMTUyNjAyWhcNMjcwMTI4MTUyNjAyWjAxMRwwGgYDVQQKExNs\naW51eGNvbnRhaW5lcnMub3JnMREwDwYDVQQDDAhyb290QGx4ZDCCAiIwDQYJKoZI\nhvcNAQEBBQADggIPADCCAgoCggIBAMUYe8d866UhjLLLlpXCpjy97hQwCjmyrFnZ\nP8A44zmyipeCTHKYyD1AxlWFI+laZo5nzjovbcnChj1boX4vjiefyi2/yAjBkhGg\n9uS5Na5glBNlEn4VrPIjVIuiRhy5A8xoISh5o7nwHeBgyjBpDsnp54JfKmX/ZkEo\nhL7M7O0Jvg3iwDs13UrjyslD94PZwoRlPeA32VwMqo3Ah0GGwnHVgMoCgD7zKzCk\n1SU5zFrY5uINA14PFgVS2/tUy/5LyfEdUy2GUiYlbGWdLuWmliibmdWuBh385PId\nvIrFWw9oprobvhvwEszFjxcAXcMjcIkfKmKm5qPF75Y49zCUjM6A2f+BDTHifuAK\nxsXjaICNFh16S8uy86L+VUNuPcF+DxhlmPEYBr8COOSjKY+XtCwmiXJHXzSp5FO6\nvthZykH9Iv7UoeGSgWFOKFl8WO+dB//KkLD1Y44K6qd7hzH4YTmnaPRadq7+8AsT\ndHqfkjSogjHD5GpiXx0kkrB2uOmPUeKfXHHMlB1CCwCsn062lS3GcusuR0phNuGI\n58vY8ot9wk6XATQeFYjcYpyrG7HKEiZrObWX1vDSmEinQ7FGcJ3gwYAgRB2ji23e\niLFrlgchRcDM781vob6g4UKwdhnAF+KqJzWzt51etOJ7me2K5jALhxRBfs3atQFW\n5bBQBZ2LAgMBAAGjUTBPMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEF\nBQcDATAMBgNVHRMBAf8EAjAAMBoGA1UdEQQTMBGCA2x4ZIcEizuDNIcEChMABTAN\nBgkqhkiG9w0BAQsFAAOCAgEAEZRMtx7edxqAiu4mOhOM2x6N2d604sCTtWq1DCX2\nI9N/VNe5unhZ82iS1MLJ8/KzY8XiECdNr1VGQeiLMUFkMCqp5QLdgy3mh690KHSk\nER35Ut+cFsf/s6lGNfkS8xqkKhldmoUGgOZmLS/dbjaSHrVJmTlZ+gfdfs+hdSUo\ndLPIIGQ3yF0Pf21IZUrVPEKGA7WmkqPVIylgLyZZ3Cio07Noq+BNfuwoncVXR3oL\nkJxsQgKtCNZDBJXcAQpjkIbORdNrckZ7mSQzTfEvdKDIkEbO1fLk9i9ej5HFsxjr\nTFPsPi9gQLVxT1lASUbT2sx78xJhwYTD8c5agpNGtWbxY/gACELL2sMivGNjYaj2\nGwale9SFD8qHoqjXseE2HN094DltNjtQAicgvG0GqJH/a4hVQx+BB4Z1fCVwp0TU\nvCPoN8FIorUX2zMLylqvhZWGZKELJ3dyPia5hTSri2BEV4+7dzTkrTIM03oL/3Ae\n+iTbuwavY5a3aueurT2Xe3SiARV9GhQyIGF1XmOnNy0Ndd9R2HGkdfPmEWi7yTiM\n3WAiodTrhy7YZjr03J0m3EEXzs1VED3RP0Z5H7ImEQjCs0wT/SjLSpuGkKlCSVWC\n46k7HpGfROz/y7kjiG0mHpmLoQXiXcZFtXXT0ySIKdhyj66OH5EYmXOP/3oqqntk\nuJI=\n-----END CERTIFICATE-----\n","driver":"lxc","driver_version":"2.0.5","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.4.0-57-generic","server":"lxd","server_pid":2694,"server_version":"2.0.8","storage":"dir","storage_version":""},"public":false}}
 
DBUG[01-30|15:36:01] Posting {"command":["bash"],"environment":{"HOME":"/root","TERM":"xterm-256color","USER":"root"},"height":41,"interactive":true,"wait-for-websocket":true,"width":159}
                             to http://unix.socket/1.0/containers/faithful-rodent/exec 
                                                                                       DBUG[01-30|15:36:01] Raw response: {"type":"async","status":"Operation created","status_code":100,"metadata":{"id":"32c7c665-afa9-45c0-9500-7e349d6d306d","class":"websocket","created_at":"2017-01-30T15:36:01.804736741Z","updated_at":"2017-01-30T15:36:01.804736741Z","status":"Running","status_code":103,"resources":{"containers":["/1.0/containers/faithful-rodent"]},"metadata":{"fds":{"0":"843e27aafb46d01639c92373c7eb94584b602ddefd299ee4e93c52aaef1b7588","control":"75af8ed2e7b8f04befe487b792d05f37e41038b8b58496aaf759e4d760aa9111"}},"may_cancel":false,"err":""},"operation":"/1.0/operations/32c7c665-afa9-45c0-9500-7e349d6d306d"}
                                                                                   
                                                                                   root@faithful-rodent:~# 

```

**Comment by lightonflux** [comment]
Just for clarification: Works flawlessly when connecting to container via ssh.

**Comment by stgraber** [comment]
That's most likely because you don't have your locale set in your environment.

Try running:

    lxc exec --env LANG=C.UTF-8 faithful-rodent bash

LXD provides you with a clean environment on login whereas ssh goes through the PAM stack in the container (as the terminal is container initiated rather than host initiated) and so hits pam_env that sets a bunch of extra environment variables for you, including LANG.

**Comment by lightonflux** [comment]
> lxc exec --env LANG=C.UTF-8

Works. Thanks you.

Which part of the stack is responsible to set it so the user does not have to do it manually? Because this can really mess  with some scripts and application. (e.g. unp/unzip extracted files with broken files names because of this).

**Comment by stgraber** [comment]
PAM is what usually does that. For security reason LXD will not read files or exec scripts inside the container from the host, so we can't do that ourselves very easily.

We can however set LANG to C.UTF-8 if the user didn't provide an alternative value through exec or through environment.LANG. That should be safe and should help people avoid that kind of issue.

To set environment variables for all exec sessions to the container, you can do:

    lxc config set faithful-rodent environment.LANG C.UTF-8

**Comment by lightonflux** [comment]
> We can however set LANG to C.UTF-8 if the user didn't provide an alternative value through exec or through environment.LANG. That should be safe and should help people avoid that kind of issue.

That sounds like a good solution. Thanks again.
