### ISSUE TITLE
container path

### ISSUE THREAD

**Issue by anothergituser** [lxc/lxd#2832]
lxd installs everything in /var/lib/lxd and my var partition is not that big, i would like to have my containers installed in a different path, i tried lxd init but there is no option to change this. i also tried to remove /var/lib/lxd/containers and make it a soft link but then i get permissions errors when starting a container so..
Thanks.

EDIT:
My container is c1, this is what happens when i try to start it after i move /var/lib/lxd to another partition with more space and then link it back into /var/lib

lxc start c1
error: Error calling 'lxd forkstart c1 /var/lib/lxd/containers /var/log/lxd/c1/lxc.conf': err='exit status 1'
  lxc 20170201042204.351 ERROR lxc_start - start.c:print_top_failing_dir:103 - Permission denied - Could not access /var/lib/lxd. Please grant it x access, or add an ACL for the container root.
  lxc 20170201042204.351 ERROR lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
  lxc 20170201042204.351 ERROR lxc_start - start.c:__lxc_start:1338 - Failed to spawn container "c1".
  lxc 20170201042204.902 ERROR lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
  lxc 20170201042204.902 ERROR lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "c1".

Try `lxc info --show-log c1` for more info

**Comment by ar45** [comment]
You can either mount another filesystem/partition on top of /var/lib/lxd,
or you can set the LXD_DIR environment variable [1].

[1]
https://github.com/lxc/lxd/blob/2102f23c726025d6d036c26a150a742c8936828b/doc/environment.md#common

**Comment by anothergituser** [comment]
about LXD_DIR env, if i set it and the path is missing, then trying to start lxd will result in an error message, so i guess it does get picked up. I create that patch and start lxd with no errors. Still launching a container fails, first it will download the image but not in the path i specify but still in /var/lib/lxd
And when it tries to start the container i get this
```
lxc start c1
error: Error calling 'lxd forkstart c1 /var/lib/lxd/containers /var/log/lxd/c1/lxc.conf': err='exit status 1'
  lxc 20170201061042.693 ERROR lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
  lxc 20170201061042.693 ERROR lxc_start - start.c:lxc_init:450 - Failed to run lxc.hook.pre-start for container "c1".
  lxc 20170201061042.693 ERROR lxc_start - start.c:__lxc_start:1294 - Failed to initialize container "c1".

Try `lxc info --show-log c1` for more info
```
Also /var/log/lxd/c1/lxc.conf has entries for /var/lib/lxd so i guess setting LXD_DIR env doesn't do much.. (if i edit the file to point those config items to the same path as LXD_DIR doesn't do much, i get the same err).

**Comment by ar45** [comment]
you have to export LXD_DIR for all your invocations of lxc.

**Comment by stgraber** [comment]
It's probably best to bind-mount /var/lib/lxd at this point.

@brauner's work on storage pools will make it possible to define a storage pool at another path in the near future. That's tracked in #2242
