### ISSUE TITLE
Make default leasetime configurable

### ISSUE THREAD

**Issue by jkroepke** [lxc/lxd#2835]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4
   * LXC version: 2.0.7
   * LXD version: 2.8
   * Storage backend in use: btrfs

# Issue description

Reference #2775 

DHCP lease should be configurable, since dnsmasq sets 1h as default lease time, if no dhcp lease time defined.

**Comment by stgraber** [comment]
Should be easy enough to add two new ipv4.dhcp.expiry and ipv6.dhcp.expiry options which will set the lease time field in the dhcp-range entry.

**Comment by jkroepke** [comment]
Yeah, but I do not have any knowledge about go.
