### ISSUE TITLE
How to access to ldx container out side via ssh

### ISSUE THREAD

**Issue by one2Ter** [lxc/lxd#2836]
* Distribution:ubuntu 16.04
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:3.1
   * LXC version:
   * LXD version:2.8

How to access to ldx container out side via ssh ?
iptable can't work to forword port. It says "managed by ldx-bridge"

server has a public ip : 69.11.87.12
container has a private ip : 10.253.210.198

I want to bind  69.11.87.12:2222 and 10.253.210.198:22 together , so that I can get access to the container via ssh by login  69.11.87.12:2222 with username and password.

user->69.11.87.12:2222(server)--->iptable--->10.253.210.198:22(container)

And is there another solution to solve it?

**Comment by stgraber** [comment]
iptables -t nat -A PREROUTING -d 69.11.87.12 -p tcp --dport 2222 -j DNAT --to 10.253.210.198:22

**Comment by stgraber** [comment]
The fact that you already have some auto-generated rules in your table for lxd-bridge isn't a problem.

**Comment by one2Ter** [comment]
There is another problem that you didn't mention in your blog.   What if the server reboots , how can I make sure that the containers can run itself and have static ip address.    Is there a script to solve it or other solution?

**Comment by one2Ter** [comment]
69.11.87.12:2222->  10.253.210.198:22
SSH  69.11.87.12:2222(public ip,server)->10.253.210.198:22(private ip,container)

**Comment by one2Ter** [comment]
I update the my answer ,please change your iptables ,thank you.

**Comment by stgraber** [comment]
The DHCP leases are stored on disk and the default IP assigned by dnsmasq to the container is based off a hash of its MAC, so the chances that the same container will be getting a different IP after reboot is pretty much null. You can of course just configure your container with a static IP through whatever config file is used by the distribution you're using inside the container.

The iptables remains correct. If you need it to survive a reboot, just have it run as part of an init script at boot.

**Comment by one2Ter** [comment]
There is still nothing after "iptables -t nat -A PREROUTING -d 69.11.87.12 -p tcp --dport 2222 -j DNAT --to 10.253.210.198:22"

p@kvm512:~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain /* managed by lxd-bridge */
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain /* managed by lxd-bridge */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps /* managed by lxd-bridge */
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps /* managed by lxd-bridge */

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             /* managed by lxd-bridge */
ACCEPT     all  --  anywhere             anywhere             /* managed by lxd-bridge */

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by stgraber** [comment]
That's because you're not listing the right table:

    iptables -t nat -L

**Comment by one2Ter** [comment]
Do you mean that the container will restart itself after server reboot?

**Comment by vasukolli** [comment]
@one2Ter You can set to autostart container after host system reboot using container config.
Please refer below link:
https://github.com/lxc/lxd/blob/master/doc/configuration.md

**Comment by stgraber** [comment]
This issue really doesn't have anything to do with LXD as it's firewalling and NAT 101, closing.

As for the earlier question, yes, LXD containers will be restored to their previous runtime state on host reboot. The iptables rules however will not be restored for you by the kernel, so that's why you need to put them into some kind of init script so that they're applied on reboot.
