### ISSUE TITLE
live migrtion

### ISSUE THREAD

**Issue by ramy150** [lxc/lxd#2838]
dear all the community 
so i'm actually doing a live migration with lxc/lxd 
but i have a real problem when i use the dump command 

####################################################
root@ubuntu:/home/onos# criu dump -t 2287 --images-dir /root/image/  --leave-stopped 
Error (criu/mount.c:948): mnt: Mount 352 ./dev/console (master_id: 3 shared_id: 0) has unreachable sharing. Try --enable-external-masters.
Error (criu/cr-dump.c:1636): Dumping FAILED.

**Comment by ramy150** [comment]
and this the complete deep view by using -vvv option 
#####################################################

root@ubuntu:/home/onos# criu dump -t 2287 --images-dir /root/image/  --leave-stopped -vvv
(00.000015) Probing sock diag modules
(00.000065) Done probing
(00.002718) ========================================
(00.002748) Dumping processes (pid: 2287)
(00.002751) ========================================
(00.002861) Pagemap is fully functional
(00.002897) Found anon-shmem device at 5
(00.002922) Reset 4738's dirty tracking
(00.002956)  ... done
(00.003008) Dirty track supported on kernel
(00.005459) irmap: Searching irmap cache in work dir
(00.005513) irmap: ... done
(00.005519) irmap: Loading irmap cache
(00.005633) cg-prop: Parsing controller "cpu"
(00.005664) cg-prop: 	Strategy "replace"
(00.005674) cg-prop: 	Property "cpu.shares"
(00.005680) cg-prop: 	Property "cpu.cfs_period_us"
(00.005686) cg-prop: 	Property "cpu.cfs_quota_us"
(00.005692) cg-prop: 	Property "cpu.rt_period_us"
(00.005698) cg-prop: 	Property "cpu.rt_runtime_us"
(00.005705) cg-prop: Parsing controller "memory"
(00.005709) cg-prop: 	Strategy "replace"
(00.005715) cg-prop: 	Property "memory.limit_in_bytes"
(00.005721) cg-prop: 	Property "memory.memsw.limit_in_bytes"
(00.005738) cg-prop: 	Property "memory.swappiness"
(00.005745) cg-prop: 	Property "memory.soft_limit_in_bytes"
(00.005751) cg-prop: 	Property "memory.move_charge_at_immigrate"
(00.005757) cg-prop: 	Property "memory.oom_control"
(00.005763) cg-prop: 	Property "memory.use_hierarchy"
(00.005769) cg-prop: 	Property "memory.kmem.limit_in_bytes"
(00.005775) cg-prop: 	Property "memory.kmem.tcp.limit_in_bytes"
(00.005781) cg-prop: Parsing controller "cpuset"
(00.005784) cg-prop: 	Strategy "replace"
(00.005790) cg-prop: 	Property "cpuset.cpus"
(00.005796) cg-prop: 	Property "cpuset.mems"
(00.005802) cg-prop: 	Property "cpuset.memory_migrate"
(00.005807) cg-prop: 	Property "cpuset.cpu_exclusive"
(00.005813) cg-prop: 	Property "cpuset.mem_exclusive"
(00.005819) cg-prop: 	Property "cpuset.mem_hardwall"
(00.005825) cg-prop: 	Property "cpuset.memory_spread_page"
(00.005831) cg-prop: 	Property "cpuset.memory_spread_slab"
(00.005836) cg-prop: 	Property "cpuset.sched_load_balance"
(00.005842) cg-prop: 	Property "cpuset.sched_relax_domain_level"
(00.005848) cg-prop: Parsing controller "blkio"
(00.005851) cg-prop: 	Strategy "replace"
(00.005857) cg-prop: 	Property "blkio.weight"
(00.005863) cg-prop: Parsing controller "freezer"
(00.005867) cg-prop: 	Strategy "replace"
(00.005873) cg-prop: Parsing controller "perf_event"
(00.005876) cg-prop: 	Strategy "replace"
(00.005882) cg-prop: Parsing controller "net_cls"
(00.005886) cg-prop: 	Strategy "replace"
(00.005891) cg-prop: 	Property "net_cls.classid"
(00.005897) cg-prop: Parsing controller "net_prio"
(00.005901) cg-prop: 	Strategy "replace"
(00.005906) cg-prop: 	Property "net_prio.ifpriomap"
(00.005912) cg-prop: Parsing controller "pids"
(00.005916) cg-prop: 	Strategy "replace"
(00.005921) cg-prop: 	Property "pids.max"
(00.005927) cg-prop: Parsing controller "devices"
(00.005930) cg-prop: 	Strategy "replace"
(00.005936) cg-prop: 	Property "devices.list"
(00.005979) Perparing image inventory (version 1)
(00.005998) Add pid ns 1 pid 4738
(00.006005) Add net ns 2 pid 4738
(00.006011) Add ipc ns 3 pid 4738
(00.006017) Add uts ns 4 pid 4738
(00.006023) Add mnt ns 5 pid 4738
(00.006029) Add user ns 6 pid 4738
(00.006035) Add cgroup ns 7 pid 4738
(00.006039) cg: Dumping cgroups for 4738
(00.006058) cg: Set 1 is criu one
(00.006254) Seized task 2287, state 1
(00.006281) Collected (4 attempts, 0 in_progress)
(00.006303) Seized task 2431, state 0
(00.006356) Collected (4 attempts, 0 in_progress)
(00.006367) Collected (4 attempts, 0 in_progress)
(00.006374) Collected 2431 in 1 state
(00.006377) Seized task 2460, state 0
(00.006565) Collected (4 attempts, 0 in_progress)
(00.006583) Collected (4 attempts, 0 in_progress)
(00.006593) Collected 2460 in 1 state
(00.006597) Seized task 3349, state 0
(00.006820) 	Seizing 3349's 3372 thread
(00.006998) 	Seizing 3349's 3373 thread
(00.007179) Collected (3 attempts, 0 in_progress)
(00.007200) Collected (4 attempts, 0 in_progress)
(00.007209) Collected 3349 in 1 state
(00.007213) Seized task 3353, state 0
(00.007395) Collected (4 attempts, 0 in_progress)
(00.007412) Collected (4 attempts, 0 in_progress)
(00.007419) Collected 3353 in 1 state
(00.007423) Seized task 3356, state 0
(00.007600) 	Seizing 3356's 3454 thread
(00.007774) 	Seizing 3356's 3455 thread
(00.007945) 	Seizing 3356's 3507 thread
(00.008116) 	Seizing 3356's 3508 thread
(00.008287) 	Seizing 3356's 3636 thread
(00.008460) 	Seizing 3356's 3641 thread
(00.008658) 	Seizing 3356's 3642 thread
(00.008703) 	Seizing 3356's 3680 thread
(00.008875) Collected (3 attempts, 0 in_progress)
(00.008906) Collected (4 attempts, 0 in_progress)
(00.008920) Collected 3356 in 1 state
(00.008923) Seized task 3359, state 0
(00.009126) Collected (4 attempts, 0 in_progress)
(00.009142) Collected (4 attempts, 0 in_progress)
(00.009147) Collected 3359 in 1 state
(00.009151) Seized task 3382, state 0
(00.009199) Collected (4 attempts, 0 in_progress)
(00.009208) Collected (4 attempts, 0 in_progress)
(00.009213) Collected 3382 in 1 state
(00.009216) Seized task 3384, state 0
(00.009311) Collected (4 attempts, 0 in_progress)
(00.009323) Collected (4 attempts, 0 in_progress)
(00.009327) Collected 3384 in 1 state
(00.009330) Seized task 3391, state 0
(00.009498) 	Seizing 3391's 3452 thread
(00.009541) 	Seizing 3391's 3515 thread
(00.009758) Collected (3 attempts, 0 in_progress)
(00.009789) Collected (4 attempts, 0 in_progress)
(00.009795) Collected 3391 in 1 state
(00.009799) Seized task 3395, state 0
(00.009849) Collected (4 attempts, 0 in_progress)
(00.009859) Collected (4 attempts, 0 in_progress)
(00.009865) Collected 3395 in 1 state
(00.009868) Seized task 3528, state 0
(00.009974) Collected (4 attempts, 0 in_progress)
(00.009986) Collected (4 attempts, 0 in_progress)
(00.009990) Collected 3528 in 1 state
(00.009994) Seized task 3560, state 0
(00.010061) 	Seizing 3560's 3586 thread
(00.010120) 	Seizing 3560's 3596 thread
(00.010311) Collected (3 attempts, 0 in_progress)
(00.010332) Collected (4 attempts, 0 in_progress)
(00.010341) Collected 3560 in 1 state
(00.010358) Collected (3 attempts, 0 in_progress)
(00.010363) Collected 2287 in 1 state
(00.010375) Will take pid namespace in the image
(00.010379) Add pid ns 8 pid 2287
(00.010385) Will take net namespace in the image
(00.010388) Add net ns 9 pid 2287
(00.010392) Will take ipc namespace in the image
(00.010395) Add ipc ns 10 pid 2287
(00.010400) Will take uts namespace in the image
(00.010403) Add uts ns 11 pid 2287
(00.010408) Will take mnt namespace in the image
(00.010411) Add mnt ns 12 pid 2287
(00.010415) Will take user namespace in the image
(00.010418) Add user ns 13 pid 2287
(00.010427) Will take cgroup namespace in the image
(00.010430) Add cgroup ns 14 pid 2287
(00.010624) Lock network
(00.013013) id_map: 0 165536 65536
(00.013087) id_map: 0 165536 65536
(00.013955) 	type ext4 source /dev/sda1 mnt_id 282 s_dev 0x800001 /var/lib/lxd/containers/cvvv/rootfs @ ./ flags 0x280000 options errors=remount-ro,data=ordered
(00.014036) 	type tmpfs source none mnt_id 319 s_dev 0x2d / @ ./dev flags 0x200004 options size=492k,mode=755,uid=0,gid=0
(00.014047) 	type proc source proc mnt_id 320 s_dev 0x2f / @ ./proc flags 0x20000e options 
(00.014067) 	type sysfs source sysfs mnt_id 321 s_dev 0x30 / @ ./sys flags 0x200004 options 
(00.014076) 	type devtmpfs source udev mnt_id 322 s_dev 0x6 /fuse @ ./dev/fuse flags 0x280002 options size=1994256k,nr_inodes=498564,mode=755
(00.014085) 	type devtmpfs source udev mnt_id 323 s_dev 0x6 /net/tun @ ./dev/net/tun flags 0x280002 options size=1994256k,nr_inodes=498564,mode=755
(00.014100) 	type binfmt_misc source binfmt_misc mnt_id 331 s_dev 0x31 / @ ./proc/sys/fs/binfmt_misc flags 0x280000 options 
(00.014110) 	type fusectl source fusectl mnt_id 332 s_dev 0x27 / @ ./sys/fs/fuse/connections flags 0x280000 options 
(00.014118) 	type pstore source pstore mnt_id 333 s_dev 0x19 / @ ./sys/fs/pstore flags 0x28000e options 
(00.014126) 	type debugfs source debugfs mnt_id 334 s_dev 0x7 / @ ./sys/kernel/debug flags 0x280000 options 
(00.014134) 	type securityfs source securityfs mnt_id 335 s_dev 0xc / @ ./sys/kernel/security flags 0x28000e options 
(00.014226) 	type mqueue source mqueue mnt_id 336 s_dev 0x11 / @ ./dev/mqueue flags 0x280000 options 
(00.014247) 	type ext4 source /dev/sda1 mnt_id 337 s_dev 0x800001 /var/lib/lxd/devlxd @ ./dev/lxd flags 0x280000 options errors=remount-ro,data=ordered
(00.014254) 	type ext4 source /dev/sda1 mnt_id 338 s_dev 0x800001 /var/lib/lxd/shmounts/cvvv @ ./dev/.lxd-mounts flags 0x280000 options errors=remount-ro,data=ordered
(00.014259) 	type fuse source lxcfs mnt_id 339 s_dev 0x29 /proc/cpuinfo @ ./proc/cpuinfo flags 0x280006 options user_id=0,group_id=0,allow_other
(00.014264) 	type fuse source lxcfs mnt_id 340 s_dev 0x29 /proc/diskstats @ ./proc/diskstats flags 0x280006 options user_id=0,group_id=0,allow_other
(00.014290) 	type fuse source lxcfs mnt_id 341 s_dev 0x29 /proc/meminfo @ ./proc/meminfo flags 0x280006 options user_id=0,group_id=0,allow_other
(00.014295) 	type fuse source lxcfs mnt_id 342 s_dev 0x29 /proc/stat @ ./proc/stat flags 0x280006 options user_id=0,group_id=0,allow_other
(00.014300) 	type fuse source lxcfs mnt_id 343 s_dev 0x29 /proc/swaps @ ./proc/swaps flags 0x280006 options user_id=0,group_id=0,allow_other
(00.014318) 	type fuse source lxcfs mnt_id 344 s_dev 0x29 /proc/uptime @ ./proc/uptime flags 0x280006 options user_id=0,group_id=0,allow_other
(00.014361) 	type fuse source lxcfs mnt_id 345 s_dev 0x29 / @ ./var/lib/lxcfs flags 0x280006 options user_id=0,group_id=0,allow_other
(00.014368) 	type devtmpfs source udev mnt_id 346 s_dev 0x6 /null @ ./dev/null flags 0x280002 options size=1994256k,nr_inodes=498564,mode=755
(00.014372) 	type devtmpfs source udev mnt_id 347 s_dev 0x6 /zero @ ./dev/zero flags 0x280002 options size=1994256k,nr_inodes=498564,mode=755
(00.014376) 	type devtmpfs source udev mnt_id 348 s_dev 0x6 /full @ ./dev/full flags 0x280002 options size=1994256k,nr_inodes=498564,mode=755
(00.014392) 	type devtmpfs source udev mnt_id 349 s_dev 0x6 /urandom @ ./dev/urandom flags 0x280002 options size=1994256k,nr_inodes=498564,mode=755
(00.014396) 	type devtmpfs source udev mnt_id 350 s_dev 0x6 /random @ ./dev/random flags 0x280002 options size=1994256k,nr_inodes=498564,mode=755
(00.014400) 	type devtmpfs source udev mnt_id 351 s_dev 0x6 /tty @ ./dev/tty flags 0x280002 options size=1994256k,nr_inodes=498564,mode=755
(00.014405) 	type devpts source devpts mnt_id 352 s_dev 0xe /8 @ ./dev/console flags 0x28000a options gid=-1,mode=620,ptmxmode=000
(00.014458) 	type devpts source devpts mnt_id 284 s_dev 0x32 / @ ./dev/pts flags 0x200000 options gid=5,mode=620,ptmxmode=666
(00.014520) 	type tmpfs source tmpfs mnt_id 285 s_dev 0x33 / @ ./dev/shm flags 0x1000006 options uid=0,gid=0
(00.014526) 	type tmpfs source tmpfs mnt_id 286 s_dev 0x34 / @ ./run flags 0x1000006 options mode=755,uid=0,gid=0
(00.014530) 	type tmpfs source tmpfs mnt_id 287 s_dev 0x35 / @ ./run/lock flags 0x20000e options size=5120k,uid=0,gid=0
(00.014535) 	type tmpfs source tmpfs mnt_id 288 s_dev 0x36 / @ ./sys/fs/cgroup flags 0x100000f options mode=755,uid=0,gid=0
(00.014540) 	type cgroup source cgroup mnt_id 289 s_dev 0x18 /lxc/cvvv @ ./sys/fs/cgroup/systemd flags 0x20000e options xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
(00.014593) 	type cgroup source cgroup mnt_id 290 s_dev 0x20 /lxc/cvvv @ ./sys/fs/cgroup/cpu,cpuacct flags 0x20000e options cpu,cpuacct
(00.014599) 	type cgroup source cgroup mnt_id 291 s_dev 0x1d /lxc/cvvv @ ./sys/fs/cgroup/devices flags 0x20000e options devices
(00.014606) 	type cgroup source cgroup mnt_id 292 s_dev 0x22 /lxc/cvvv @ ./sys/fs/cgroup/cpuset flags 0x20000e options cpuset,clone_children
(00.014626) 	type cgroup source cgroup mnt_id 293 s_dev 0x1e /lxc/cvvv @ ./sys/fs/cgroup/hugetlb flags 0x20000e options hugetlb
(00.014670) 	type cgroup source cgroup mnt_id 294 s_dev 0x1c /lxc/cvvv @ ./sys/fs/cgroup/freezer flags 0x20000e options freezer
(00.014674) 	type cgroup source cgroup mnt_id 295 s_dev 0x1b /lxc/cvvv @ ./sys/fs/cgroup/perf_event flags 0x20000e options perf_event
(00.014678) 	type cgroup source cgroup mnt_id 296 s_dev 0x1f /lxc/cvvv @ ./sys/fs/cgroup/blkio flags 0x20000e options blkio
(00.014682) 	type cgroup source cgroup mnt_id 297 s_dev 0x21 /lxc/cvvv @ ./sys/fs/cgroup/memory flags 0x20000e options memory
(00.014688) 	type cgroup source cgroup mnt_id 298 s_dev 0x1a /lxc/cvvv @ ./sys/fs/cgroup/net_cls,net_prio flags 0x20000e options net_cls,net_prio
(00.014704) 	type cgroup source cgroup mnt_id 299 s_dev 0x23 /lxc/cvvv @ ./sys/fs/cgroup/pids flags 0x20000e options pids
(00.014710) mnt: Building mountpoints tree
(00.014714) mnt: 	Resorting siblings on 282
(00.014721) mnt: 	Resorting siblings on 286
(00.014739) mnt: 	Resorting siblings on 287
(00.014743) mnt: 	Resorting siblings on 345
(00.014749) mnt: 	Resorting siblings on 321
(00.014754) mnt: 	Resorting siblings on 288
(00.014759) mnt: 	Resorting siblings on 299
(00.014764) mnt: 	Resorting siblings on 298
(00.014781) mnt: 	Resorting siblings on 297
(00.014786) mnt: 	Resorting siblings on 296
(00.014791) mnt: 	Resorting siblings on 295
(00.014795) mnt: 	Resorting siblings on 294
(00.014800) mnt: 	Resorting siblings on 293
(00.014805) mnt: 	Resorting siblings on 292
(00.014812) mnt: 	Resorting siblings on 291
(00.014904) mnt: 	Resorting siblings on 290
(00.014911) mnt: 	Resorting siblings on 289
(00.014916) mnt: 	Resorting siblings on 335
(00.014932) mnt: 	Resorting siblings on 334
(00.014937) mnt: 	Resorting siblings on 333
(00.014969) mnt: 	Resorting siblings on 332
(00.014976) mnt: 	Resorting siblings on 320
(00.014981) mnt: 	Resorting siblings on 344
(00.014986) mnt: 	Resorting siblings on 343
(00.014993) mnt: 	Resorting siblings on 342
(00.014998) mnt: 	Resorting siblings on 341
(00.015002) mnt: 	Resorting siblings on 340
(00.015010) mnt: 	Resorting siblings on 339
(00.015015) mnt: 	Resorting siblings on 331
(00.015020) mnt: 	Resorting siblings on 319
(00.015027) mnt: 	Resorting siblings on 285
(00.015032) mnt: 	Resorting siblings on 284
(00.015037) mnt: 	Resorting siblings on 352
(00.015054) mnt: 	Resorting siblings on 351
(00.015059) mnt: 	Resorting siblings on 350
(00.015064) mnt: 	Resorting siblings on 349
(00.015093) mnt: 	Resorting siblings on 348
(00.015098) mnt: 	Resorting siblings on 347
(00.015103) mnt: 	Resorting siblings on 346
(00.015108) mnt: 	Resorting siblings on 338
(00.015117) mnt: 	Resorting siblings on 337
(00.015122) mnt: 	Resorting siblings on 336
(00.015129) mnt: 	Resorting siblings on 323
(00.015144) mnt: 	Resorting siblings on 322
(00.015149) mnt: Done:
(00.015173) mnt: [./](282->283)
(00.015177) mnt:  [./run](286->282)
(00.015180) mnt:   [./run/lock](287->286)
(00.015183) mnt:   <--
(00.015186) mnt:  <--
(00.015189) mnt:  [./dev](319->282)
(00.015192) mnt:   [./dev/shm](285->319)
(00.015193) mnt:   <--
(00.015193) mnt:   [./dev/fuse](322->319)
(00.015194) mnt:   <--
(00.015195) mnt:   [./dev/net/tun](323->319)
(00.015196) mnt:   <--
(00.015197) mnt:   [./dev/mqueue](336->319)
(00.015198) mnt:   <--
(00.015198) mnt:   [./dev/lxd](337->319)
(00.015199) mnt:   <--
(00.015200) mnt:   [./dev/.lxd-mounts](338->319)
(00.015201) mnt:   <--
(00.015202) mnt:   [./dev/null](346->319)
(00.015203) mnt:   <--
(00.015205) mnt:   [./dev/zero](347->319)
(00.015206) mnt:   <--
(00.015206) mnt:   [./dev/full](348->319)
(00.015207) mnt:   <--
(00.015208) mnt:   [./dev/urandom](349->319)
(00.015209) mnt:   <--
(00.015210) mnt:   [./dev/random](350->319)
(00.015211) mnt:   <--
(00.015211) mnt:   [./dev/tty](351->319)
(00.015212) mnt:   <--
(00.015213) mnt:   [./dev/console](352->319)
(00.015214) mnt:   <--
(00.015214) mnt:   [./dev/pts](284->319)
(00.015225) mnt:   <--
(00.015226) mnt:  <--
(00.015227) mnt:  [./proc](320->282)
(00.015227) mnt:   [./proc/uptime](344->320)
(00.015231) mnt:   <--
(00.015244) mnt:   [./proc/sys/fs/binfmt_misc](331->320)
(00.015247) mnt:   <--
(00.015250) mnt:   [./proc/cpuinfo](339->320)
(00.015253) mnt:   <--
(00.015256) mnt:   [./proc/diskstats](340->320)
(00.015259) mnt:   <--
(00.015271) mnt:   [./proc/meminfo](341->320)
(00.015275) mnt:   <--
(00.015301) mnt:   [./proc/stat](342->320)
(00.015307) mnt:   <--
(00.015310) mnt:   [./proc/swaps](343->320)
(00.015313) mnt:   <--
(00.015316) mnt:  <--
(00.015318) mnt:  [./sys](321->282)
(00.015322) mnt:   [./sys/fs/cgroup](288->321)
(00.015326) mnt:    [./sys/fs/cgroup/pids](299->288)
(00.015329) mnt:    <--
(00.015332) mnt:    [./sys/fs/cgroup/systemd](289->288)
(00.015334) mnt:    <--
(00.015335) mnt:    [./sys/fs/cgroup/cpu,cpuacct](290->288)
(00.015338) mnt:    <--
(00.015339) mnt:    [./sys/fs/cgroup/devices](291->288)
(00.015340) mnt:    <--
(00.015342) mnt:    [./sys/fs/cgroup/cpuset](292->288)
(00.015343) mnt:    <--
(00.015344) mnt:    [./sys/fs/cgroup/hugetlb](293->288)
(00.015345) mnt:    <--
(00.015346) mnt:    [./sys/fs/cgroup/freezer](294->288)
(00.015347) mnt:    <--
(00.015347) mnt:    [./sys/fs/cgroup/perf_event](295->288)
(00.015348) mnt:    <--
(00.015349) mnt:    [./sys/fs/cgroup/blkio](296->288)
(00.015350) mnt:    <--
(00.015351) mnt:    [./sys/fs/cgroup/memory](297->288)
(00.015351) mnt:    <--
(00.015352) mnt:    [./sys/fs/cgroup/net_cls,net_prio](298->288)
(00.015353) mnt:    <--
(00.015354) mnt:   <--
(00.015355) mnt:   [./sys/fs/fuse/connections](332->321)
(00.015356) mnt:   <--
(00.015356) mnt:   [./sys/fs/pstore](333->321)
(00.015357) mnt:   <--
(00.015383) mnt:   [./sys/kernel/debug](334->321)
(00.015395) mnt:   <--
(00.015396) mnt:   [./sys/kernel/security](335->321)
(00.015397) mnt:   <--
(00.015398) mnt:  <--
(00.015398) mnt:  [./var/lib/lxcfs](345->282)
(00.015399) mnt:  <--
(00.015400) mnt: <--
(00.015419) Error (criu/mount.c:948): mnt: Mount 352 ./dev/console (master_id: 3 shared_id: 0) has unreachable sharing. Try --enable-external-masters.
(00.015459) Unlock network
(00.017410) Unfreezing tasks into 1
(00.017622) Error (criu/cr-dump.c:1636): Dumping FAILED.

**Comment by stgraber** [comment]
If you're using LXD you should be using "lxc move" instead of calling CRIU directly. The CRIU command line generated by LXD is significantly more complex than what you're using and also includes the use of action scripts to properly deal with the filesystem state.

**Comment by ramy150** [comment]
so the move commande use the CRIU to proceed ?

**Comment by stgraber** [comment]
yes, "lxc move" when the container is running, "lxc snapshot --stateful" and "lxc stop --stateful" all use CRIU.

**Comment by ramy150** [comment]
thank's a lot my friend
