### ISSUE TITLE
LXD container not getting IP Address

### ISSUE THREAD

**Issue by clvx** [lxc/lxd#2839]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04.1 Xenial
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-59-generic
   * LXC version: 2.0.6
   * LXD version: 2.0.8
   * Storage backend in use: dir

# Issue description

Container doesn't get an IP address after creation, even when I reconfigured lxd with `sudo dpkg-reconfigure -p medium lxd`.

----- On Host -----

$ lxc list
+-----------+---------+------+------+------------+-----------+--------------------+
|   NAME    |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+-----------+---------+------+------+------------+-----------+--------------------+
| hardening | RUNNING |      |             | PERSISTENT | 0           |
+-----------+---------+------+------+------------+-----------+--------------------+

$ lxc info hardening
Name: hardening
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/02/02 13:52 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 21667
Ips:
  eth0: inet6   fe80::216:3eff:fe04:f431        vethTX24YI
  lo:   inet    127.0.0.1
  lo:   inet6   ::1

$ip addr show lxdbr0
11: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether fe:0f:65:0f:ff:b9 brd ff:ff:ff:ff:ff:ff
    inet 10.142.0.1/24 scope global lxdbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::8c4b:33ff:fecb:bc9d/64 scope link 
       valid_lft forever preferred_lft forever

$ ps awux | grep dnsmasq | grep lxd
lxd      19814  0.0  0.0  52868  2908 ?        S    08:42   0:00 dnsmasq -s lxd -S /lxd/ -u lxd --strict-order --bind-interfaces --pid-file=/run/lxd-bridge//dnsmasq.pid --dhcp-no-override --except-interface=lo --interface=lxdbr0 --dhcp-leasefile=/var/lib/lxd-bridge//dnsmasq.lxdbr0.leases --dhcp-authoritative --listen-address 10.142.0.1 --dhcp-range 10.142.174.2,10.142.174.254 --dhcp-lease-max=252

$ sudo iptables -t nat -L POSTROUTING | grep lxd
MASQUERADE  all  --  10.142.0.0/24       !10.142.0.0/24        /* managed by lxd-bridge */

---- Inside Container -----
$ lxc exec hardening -- ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
16: eth0@if17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:04:f4:31 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::216:3eff:fe04:f431/64 scope link 
       valid_lft forever preferred_lft forever

$ lxc exec hardening -- cat /etc/resolv.conf 
`#Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)`
`#DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN`
 
$ sudo systemctl status lxd lxd-bridge 
● lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: active (running) since Thu 2017-02-02 09:06:05 PET; 1min 42s ago
     Docs: man:lxd(1)
  Process: 22967 ExecStartPost=/usr/bin/lxd waitready --timeout=600 (code=exited, status=0/SUCCESS)
  Process: 22964 ExecStartPost=/usr/lib/lxd/profile-config (code=exited, status=0/SUCCESS)
  Process: 22926 ExecStartPre=/usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load (code=exited, status=0/SUCCESS)
 Main PID: 22963 (lxd)
    Tasks: 14
   Memory: 24.1M
      CPU: 2.216s
   CGroup: /system.slice/lxd.service
           ├─22963 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           └─23132 [lxc monitor] /var/lib/lxd/containers hardening

Feb 02 09:06:04 xps systemd[1]: Starting LXD - main daemon...
Feb 02 09:06:04 xps lxd[22963]: t=2017-02-02T09:06:04-0500 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
Feb 02 09:06:05 xps systemd[1]: Started LXD - main daemon.

● lxd-bridge.service - LXD - network bridge
   Loaded: loaded (/lib/systemd/system/lxd-bridge.service; static; vendor preset: enabled)
   *Active: active (exited)* since Thu 2017-02-02 09:06:04 PET; 1min 42s ago
     Docs: man:lxd(1)
  Process: 22830 ExecStop=/usr/lib/lxd/lxd-bridge stop (code=exited, status=0/SUCCESS)
  Process: 22882 ExecStart=/usr/lib/lxd/lxd-bridge.start (code=exited, status=0/SUCCESS)
 Main PID: 22882 (code=exited, status=0/SUCCESS)
    Tasks: 1
   Memory: 416.0K
      CPU: 23ms
   CGroup: /system.slice/lxd-bridge.service
           └─22923 dnsmasq -s lxd -S /lxd/ -u lxd --strict-order --bind-interfaces --pid-file=/run/lxd-bridge//dnsmasq.pid --dhcp-no-override --except-interface=lo --interface=l

Feb 02 09:06:04 xps dnsmasq[22923]: read /etc/hosts - 8 addresses
Feb 02 09:06:04 xps systemd[1]: Started LXD - network bridge.
Feb 02 09:06:24 xps dnsmasq-dhcp[22923]: no address range available for DHCP request via lxdbr0
Feb 02 09:06:27 xps dnsmasq-dhcp[22923]: no address range available for DHCP request via lxdbr0
Feb 02 09:06:35 xps dnsmasq-dhcp[22923]: no address range available for DHCP request via lxdbr0
Feb 02 09:06:43 xps dnsmasq-dhcp[22923]: no address range available for DHCP request via lxdbr0
Feb 02 09:06:58 xps dnsmasq-dhcp[22923]: no address range available for DHCP request via lxdbr0
Feb 02 09:07:11 xps dnsmasq-dhcp[22923]: no address range available for DHCP request via lxdbr0
Feb 02 09:07:30 xps dnsmasq-dhcp[22923]: no address range available for DHCP request via lxdbr0
Feb 02 09:07:39 xps dnsmasq-dhcp[22923]: no address range available for DHCP request via lxdbr0

**Comment by stgraber** [comment]
@clvx Sounds like the DHCP address ranges you entered are outside of the subnet assigned to the bridge.

Re-run "dpkg-reconfigure lxd" and pay close attention to the IPs you see for the DHCP range, I bet they're on a different network from what you entered as the bridge network.

Actually, you posted the proof of that :)

```
lxd 19814 0.0 0.0 52868 2908 ? S 08:42 0:00 dnsmasq -s lxd -S /lxd/ -u lxd --strict-order --bind-interfaces --pid-file=/run/lxd-bridge//dnsmasq.pid --dhcp-no-override --except-interface=lo --interface=lxdbr0 --dhcp-leasefile=/var/lib/lxd-bridge//dnsmasq.lxdbr0.leases --dhcp-authoritative --listen-address 10.142.0.1 --dhcp-range 10.142.174.2,10.142.174.254 --dhcp-lease-max=252
```

Your bridge uses 10.142.0.1 but the DHCP range you entered is 10.142.174.2-10.142.174.254. You'll want to change that to 10.142.0.2-10.142.0.254 instead.

(Yes, it'd be better if we could detect that and fail when you fill the form, but we're dealing with a minimal shell script at that point and doing subnet math is rather difficult in shell :))

**Comment by clvx** [comment]
@stgraber, that's odd because I used the default settings recommendations from `dpkg-reconfigure -p medium lxd`. I'll test it again to verify it.
