### ISSUE TITLE
container image support

### ISSUE THREAD

**Issue by one2Ter** [lxc/lxd#2840]
Is lxd only support ubuntu ?
Is there a plan to support debian image ?
I would be happier if lxd support other distributions image ,so we can have debian inside the container.
Could we make the image by ourselves?

**Comment by niko-daniel** [comment]
Do you mean other distributions images ? likes debian, centos, fedora etc.
View images list 
`user@Edge-E440:~$ lxc image list images:`

Example images list
`user@Edge-E440:~$ lxc image list images: |grep fedora`
user@Edge-E440:~$ lxc image list images: |grep fedora
| fedora/22 (3 more)              | 16befef85604 | yes    | Fedora 22 amd64 (20170202_01:27)         | x86_64  | 222.75MB | Feb 2, 2017 at 12:00am (UTC)  |
| fedora/22/i386 (1 more)         | a034a8882d2f | yes    | Fedora 22 i386 (20170202_01:52)          | i686    | 210.31MB | Feb 2, 2017 at 12:00am (UTC)  |
| fedora/23 (3 more)              | 8185d7975889 | yes    | Fedora 23 amd64 (20170202_01:27)         | x86_64  | 241.11MB | Feb 2, 2017 at 12:00am (UTC)  |
| fedora/23/i386 (1 more)         | 44c6806ba6f2 | yes    | Fedora 23 i386 (20170202_01:52)          | i686    | 227.21MB | Feb 2, 2017 at 12:00am (UTC)  |
| fedora/24 (3 more)              | 3ee2afc9a2e1 | yes    | Fedora 24 amd64 (20170202_01:27)         | x86_64  | 235.25MB | Feb 2, 2017 at 12:00am (UTC)  |
| fedora/24/i386 (1 more)         | 67c98510174f | yes    | Fedora 24 i386 (20170202_01:27)          | i686    | 220.38MB | Feb 2, 2017 at 12:00am (UTC)  |


List of local images, Eg my local
`user@Edge-E440:~$ lxc image list` 
+---------+--------------+--------+---------------------------------------+---------+---------+------------------------------+
|  ALIAS  | FINGERPRINT  | PUBLIC |              DESCRIPTION              |  ARCH   |  SIZE   |         UPLOAD DATE          |
+---------+--------------+--------+---------------------------------------+---------+---------+------------------------------+
| alpine  | a62fa8d58d88 | no     | Alpine 3.4 amd64 (20161219_17:50)     | x86_64  | 2.63MB  | Dec 20, 2016 at 1:36pm (UTC) |
+---------+--------------+--------+---------------------------------------+---------+---------+------------------------------+
| jessie  | d8e6748e9024 | no     | Debian jessie arm64 (20170201_22:42)  | aarch64 | 87.72MB | Feb 2, 2017 at 2:24pm (UTC)  |
+---------+--------------+--------+---------------------------------------+---------+---------+------------------------------+
| trusty  | dadb4c498f43 | no     | Ubuntu trusty amd64 (20161220_03:49)  | x86_64  | 77.54MB | Dec 20, 2016 at 2:39pm (UTC) |
+---------+--------------+--------+---------------------------------------+---------+---------+------------------------------+
| xenial  | 6e1db92c30b7 | no     | Ubuntu xenial amd64 (20170109_03:49)  | x86_64  | 81.40MB | Jan 9, 2017 at 3:42pm (UTC)  |
+---------+--------------+--------+---------------------------------------+---------+---------+------------------------------+
| yakkety | 8902f541dea1 | no     | Ubuntu yakkety amd64 (20170119_03:49) | x86_64  | 80.57MB | Jan 20, 2017 at 2:00am (UTC) |
+---------+--------------+--------+---------------------------------------+---------+---------+------------------------------+

and also you can make your own image base on default distributions images and publish it as a custom images.

**Comment by stgraber** [comment]
LXD supports any Linux distribution, we have a bunch of images that are generated daily as @niko-daniel points out. There is even an example of that in the README file that you see when you arrive on Github and image handling is documented in doc/

Closing this issue.
