### ISSUE TITLE
Remove unneeded DB cleanup code

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#2844]
With #2843, we shouldn't need any custom cleanup code like: https://github.com/lxc/lxd/blob/master/lxd/db_images.go#L251

Instead, now that we can actually trust FKs, we should get rid of all this code.

**Comment by stgraber** [comment]
The interest behind doing this is that it will help confirm that our schema is good and that we can rely on CASCADE (as our testsuite will validate that tables are empty). The user visible effect of this should be less DB locks being acquired and so making things a bit speedier in general.
