### ISSUE TITLE
Disabling link-local IPv6 on veth interfaces

### ISSUE THREAD

**Issue by candlerb** [lxc/lxd#2845]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info"

~~~
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: <snip>
  certificatefingerprint: <snip>
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-59-generic
  server: lxd
  serverpid: 5726
  serverversion: 2.0.8
  storage: btrfs
  storageversion: "4.4"
config:
  images.auto_update_cached: "false"
  images.auto_update_interval: "0"
public: false
~~~

# Issue description

When lxd attaches containers to bridges, there is a vethXXXXXX interface on the host side and an ethX interface at the container side.

The vethXXXXXX interfaces all get IPv6 link local addresses (which are different from the link-local addresses of the ethX interfaces inside the containers).

With many containers, the host gains many link-local addresses:

~~~
        "ansible_all_ipv6_addresses": [
            "fe80::fc7d:f7ff:fed7:d4f5",
            "fe80::fc2f:1eff:fe51:1633",
            "fe80::fc69:31ff:fe23:2990",
            "fe80::fcf8:a8ff:fed7:7e7",
            "fe80::fc66:8eff:fe07:e10a",
            "fe80::fca2:26ff:feb6:c370",
            "fe80::fc0c:90ff:fe3c:31ef",
            "fe80::fc03:c9ff:fe2d:fcc1",
... etc
~~~

A veth interface is never a source or target for traffic, so should never have its own IPv4 or IPv6 address.

I'd like to disable these link-local addresses: for cleanliness, and to reduce risk of traffic being able to reach bridges that I don't want it to.

This could probably be done by:

~~~
echo 0 > /proc/sys/net/ipv6/conf/vethXXXXXX/autoconf
~~~

and it definitely can be removed by:

~~~
echo 1 > /proc/sys/net/ipv6/conf/vethXXXXXX/disable_ipv6
~~~

However this depends on the actual assigned name, so has to be done when the interface is created. I don't want to set `net.ipv6.conf.default.autoconf=0` as that would have global effect, only for veth interfaces.

Could this be done in the script which brings up a container interface?

# Steps to reproduce

* Start containers
* 'ifconfig -a' on host
* Look at all those link local addresses.

**Comment by stgraber** [comment]
We can do this in LXD for device hot plug but for the initial devices that needs to be done in LXC instead.

**Comment by stgraber** [comment]
Can you file a bug at https://github.com/lxc/lxc for the LXC side of this?
