### ISSUE TITLE
Please update your article

### ISSUE THREAD

**Issue by one2Ter** [lxc/lxd#2850]
https://www.stgraber.org/2016/10/27/network-management-with-lxd-2-3/

I am trying to create a new network with a random IPv4 and IPv6 subnet and NAT enabled. So I ran the command "lxc network create testbr0".  Then , I got this.

sudo lxc network create testbr0
Usage: lxc [subcommand] [options]
Available commands:
	config     - Manage configuration.
	copy       - Copy containers within or in between lxd instances.
	delete     - Delete containers or snapshots.
	exec       - Execute the specified command in a container.
	file       - Manage files on a container.
	help       - Presents details on how to use LXD.
	image      - Manipulate container images.
	info       - List information on LXD servers and containers.
	launch     - Launch a container from a particular image.
	list       - Lists the available resources.
	move       - Move containers within or in between lxd instances.
	profile    - Manage configuration profiles.
	publish    - Publish containers as images.
	remote     - Manage remote LXD servers.
	restart    - Changes state of one or more containers to restart.
	restore    - Set the current state of a container back to a snapshot.
	snapshot   - Create a read-only snapshot of a container.
	start      - Changes state of one or more containers to start.
	stop       - Changes state of one or more containers to stop.
	version    - Prints the version number of this client tool.

Options:
  --all              Print less common commands.
  --debug            Print debug information.
  --verbose          Print verbose information.
  --version          Show client version.

Environment:
  LXD_CONF           Path to an alternate client configuration directory.
  LXD_DIR            Path to an alternate server directory.

error: unknown command: network

System:ubuntu 16.04     LXD 2.8

It seems you change it but you didn't update your article.

**Comment by one2Ter** [comment]
Please pay more attention on the wiki or it will be easy to make the newcomer to be confused.

**Comment by ar45** [comment]
Your for sure not running LXD 2.8 as *lxc network ..* is absolutely a valid
command.

Can you show the output of *lxc --version* ?


--
Aron Podrigal
718-942-9990 x 221

Software Engineer
MongoTel

**Comment by stgraber** [comment]
Sounds like you're getting confused between 2.0.8 and 2.8, those are two completely different version numbers :)

LXD 2.8 does support "lxc network", the LTS branch of LXD (currently at 2.0.9) does not get feature backports and so, does not include that command.

The article makes it quite clear (it's even in the title) that you need LXD 2.3 or higher.


If you want to use the non-LTS branch of LXD on Ubuntu 16.04 LTS, you can do so by installing LXD from backports:

    apt install -t xenial-backports lxd lxd-client

**Comment by one2Ter** [comment]
apt install -t xenial-backports lxd lxd-client
Reading package lists... Done
E: The value 'xenial-backports' is invalid for APT::Default-Release as such a release is not available in the sources

**Comment by stgraber** [comment]
@one2Ter looks like your particular system doesn't have the "backports' repository enabled. If on a desktop machine, the software sources settings panel will let you turn it on, on a server, you'll need to enable it in /etc/apt/sources.list. In theory all official Ubuntu images should have it enabled by default, users are obviously free to then turn it off.

**Comment by one2Ter** [comment]
Thank yuou for your help
