### ISSUE TITLE
lxc-start error: "unknown capability sys_module"

### ISSUE THREAD

**Issue by Songzhongrang** [lxc/lxd#2856]
I got lxc-2.0.0.tar.gz from https://linuxcontainers.org/lxc/downloads/
I use ubuntu 12.04 precise, following is detail 
> infomation:
szr@szr-VirtualBox:~/software$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
szr@szr-VirtualBox:~/software$ file /bin/ls
/bin/ls: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x83531f308f1fa18221be53eaf399303400c14638, stripped
szr@szr-VirtualBox:~/software$ uname -a
Linux szr-VirtualBox 3.13.0-32-generic #57~precise1-Ubuntu SMP Tue Jul 15 03:50:54 UTC 2014 i686 i686 i386 GNU/Linux
szr@szr-VirtualBox:~/software$ 

I create a container by using 'lxc-create -n u1 -t busybox'
Then I create the bridge named lxcbr0 by 'brctl addbr lxcbr0'
I use following command create mountpoint used by cgroup
> 
mount -t tmpfs cgroup_root /sys/fs/cgroup

mkdir /sys/fs/cgroup/cpu&& 
mount -t cgroup -o cpu cpu /sys/fs/cgroup/cpu/

mkdir /sys/fs/cgroup/cpuset && 
mount -t cgroup cpuset -o cpuset /sys/fs/cgroup/cpuset/

mkdir /sys/fs/cgroup/freezer && 
mount -t cgroup -o freezer freezer /sys/fs/cgroup/freezer/

mkdir /sys/fs/cgroup/memory && 
mount -t cgroup -o memory memory /sys/fs/cgroup/memory/

mkdir /sys/fs/cgroup/systemd && 
mount -t cgroup -o none,name=systemd systemd /sys/fs/cgroup/systemd/

Then I try to start container u1 by execute 'lxc-start -n u1 --logfile log', 
but I got following err msg

> 
  lxc-start 20170207094416.216 ERROR    lxc_conf - conf.c:setup_caps:2051 - unknown capability sys_module
  lxc-start 20170207094416.221 ERROR    lxc_conf - conf.c:lxc_setup:3834 - failed to drop capabilities
  lxc-start 20170207094416.221 ERROR    lxc_start - start.c:do_start:819 - failed to setup the container
  lxc-start 20170207174416.221 ERROR    lxc_sync - sync.c:__sync_wait:52 - An error occurred in another process (expected sequence number 2)
  lxc-start 20170207174416.226 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'u1'
  lxc-start 20170207174421.240 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
  lxc-start 20170207174421.264 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
  lxc-start 20170207174421.264 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

Does any know how to resolve it?

**Comment by stgraber** [comment]
Closing the issue as this isn't a LXD issue but a LXC one.

It looks like you built LXC without libcap support or built it against a libcap which doesn't support sys_module. I'd recommend you look at the summary at the end of the configure run which will tell you if libcap is being used or not.

Alternatively, you could also just use a PPA build of LXC 2.0.x for Ubuntu 12.04 (ppa:ubuntu-lxc/stable) which will save you the trouble of building this yourself.

Also, do note that only the latest bugfix release of a particular LXC version is supported, this means that LXC 2.0.0 isn't supported anymore and that we expect our users to be on 2.0.7.
