### ISSUE TITLE
LXD live migration downtime?

### ISSUE THREAD

**Issue by djixyacine** [lxc/lxd#2858]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 Server
 * The output of "lxc info" or if that fails: /No failure
   * Kernel version: 4.4.0
   * LXC version: 2.8
   * LXD version: 2.8
   * Criu version: 2.9
   * Storage backend in use: ZFS

# Issue description
Hello everyone,
So i have been experimenting with LXD lately, especially with live migration, as it's part of my Master's thesis. After setting up everything, i created a container, installed doom inside it, and tried to migrate it. Here a link to a small demo i made: 

https://drive.google.com/file/d/0BzZL3D4BZUooa3A2WVc5Um40TUZGT0FDMWdhRHpGTDQzQTh3/view

As you may be able to see, Although the migration is successful, there is about 4 or 5 seconds of down time. Is that to be expected? Or something could be wrong with my setup?

# Steps to reproduce

 1. Step one: Create the container
 2. Step two: Launch a ping
 3. Step three: Live migrate using lxc move

# Information to attach
 - [ ] container log right after the migration (lxc info NAME --show-log)
 lxc 20170208081440.079 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 43584, expected pid 43590.

**Comment by tych0** [comment]
Yes, that's to be expected. Right now we don't do iterative migration of the memory state.

**Comment by djixyacine** [comment]
I noticed that making a stateful snapshot using: lxc snapshot <container> --stateful causes downtime, is that to be expected as well? If so, how would one save the memory state while not causing downtime?

**Comment by tych0** [comment]
On Wed, Feb 08, 2017 at 07:18:37AM -0800, djixyacine wrote:
> I noticed that making a stateful snapshot using: lxc snapshot <container> --stateful causes downtime, is that to be expected as well?

Yes, it is.

> If so, how would one save the memory state while not causing downtime?

Iteration, same as above. There will always be some downtime, but it's
possible to make it very small by simply saving the whole memory
state, then the delta during that memory state change, etc. etc.
until the downtime is sufficiently small.

**Comment by djixyacine** [comment]
All right, thank you very much tych0.
One last question if i may, how can I save the memory of a container? (without causing downtime)

**Comment by tych0** [comment]
On Wed, Feb 08, 2017 at 08:32:17AM -0800, djixyacine wrote:
> All right, thank you very much tych0.
> One last question if i may, how can I save the memory of a container? (without causing downtime)

Heh, isn't this the same question as above? CRIU has some memory
tracking features, but they aren't integrated to LXD, so liblxc/LXD
patches would be required to make them work.

**Comment by djixyacine** [comment]
Okay, thank you very much for your help.
