### ISSUE TITLE
Fail to launch container ubuntu 16.04 lxd 2.8 kernel 4.9

### ISSUE THREAD

**Issue by one2Ter** [lxc/lxd#2859]
# Required information

 * Distribution: lxd
 * Distribution version:2.8
 * The output of "lxc info" or if that fails:
   * Kernel version:4.9.8-040908-generic
   * LXC version:2.0.6
   * LXD version:2.8
   * Storage backend in use:

# Issue description
Fail to launch container ubuntu 16.04 lxd 2.8 kernel 4.9

# Steps to reproduce

lxd init
Name of the storage backend to use (dir or zfs) [default=dir]:
Would you like LXD to be available over the network (yes/no) [default=no]?
Would you like stale cached images to be updated automatically (yes/no) [default=yes]?
Would you like to create a new network bridge (yes/no) [default=yes]?
What should the new bridge be called [default=lxdbr0]?
What IPv4 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]?
What IPv6 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]?
error: The network already exists
root@kvm2g:~# dpkg-reconfigure -p medium lxd
Warning: Stopping lxd.service, but it can still be activated by:
  lxd.socket
root@kvm2g:~# lxc launch ubuntu:16.04
Creating decent-giraffe
Starting decent-giraffe
error: Error calling 'lxd forkstart decent-giraffe /var/lib/lxd/containers /var/log/lxd/decent-giraffe/lxc.conf': err='exit status 1'
  lxc 20170208140239.411 ERROR lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:220 - If you really want to start this container, set
  lxc 20170208140239.411 ERROR lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:221 - lxc.aa_allow_incomplete = 1
  lxc 20170208140239.411 ERROR lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:222 - in your container configuration file
  lxc 20170208140239.411 ERROR lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
  lxc 20170208140239.411 ERROR lxc_start - start.c:__lxc_start:1338 - Failedto spawn container "decent-giraffe".
  lxc 20170208140239.942 ERROR lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
  lxc 20170208140239.942 ERROR lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "decent-giraffe".

# Information to attach

dmesg
[13053.330564] lxdbr0: port 1(vethEIBP5W) entered blocking state
[13053.330566] lxdbr0: port 1(vethEIBP5W) entered disabled state
[13053.330644] device vethEIBP5W entered promiscuous mode
[13053.330753] IPv6: ADDRCONF(NETDEV_UP): vethEIBP5W: link is not ready
[13053.373039] eth0: renamed from veth8533XU
[13053.389219] IPv6: ADDRCONF(NETDEV_CHANGE): vethEIBP5W: link becomes ready
[13053.389277] lxdbr0: port 1(vethEIBP5W) entered blocking state
[13053.389279] lxdbr0: port 1(vethEIBP5W) entered forwarding state
[13053.409709] cgroup: new mount options do not match the existing superblock, will be ignored
[13053.512360] lxdbr0: port 1(vethEIBP5W) entered disabled state
[13053.514037] device vethEIBP5W left promiscuous mode
[13053.514042] lxdbr0: port 1(vethEIBP5W) entered disabled state
[13575.783964] audit: type=1400 audit(1486562559.279:48): apparmor="STATUS" operation="profile_load" name="lxd-decent-giraffe_</var/lib/lxd>" pid=12036 comm="apparmor_parser"
[13575.810036] lxdbr0: port 1(veth0KFO4L) entered blocking state
[13575.810038] lxdbr0: port 1(veth0KFO4L) entered disabled state
[13575.810161] device veth0KFO4L entered promiscuous mode
[13575.810333] IPv6: ADDRCONF(NETDEV_UP): veth0KFO4L: link is not ready
[13575.841380] eth0: renamed from vethTY7GXE
[13575.858068] IPv6: ADDRCONF(NETDEV_CHANGE): veth0KFO4L: link becomes ready
[13575.858106] lxdbr0: port 1(veth0KFO4L) entered blocking state
[13575.858107] lxdbr0: port 1(veth0KFO4L) entered forwarding state
[13575.960443] lxdbr0: port 1(veth0KFO4L) entered disabled state
[13575.962267] device veth0KFO4L left promiscuous mode
[13575.962269] lxdbr0: port 1(veth0KFO4L) entered disabled state

lxc info decent-giraffe --show-log
Log:

            lxc 20170208140239.410 WARN     lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:218 - Incomplete AppArmor support in your kernel
            lxc 20170208140239.411 ERROR    lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:220 - If you really want to start this container, set
            lxc 20170208140239.411 ERROR    lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:221 - lxc.aa_allow_incomplete = 1
            lxc 20170208140239.411 ERROR    lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:222 - in your container configuration file
            lxc 20170208140239.411 ERROR    lxc_sync - sync.c:__sync_wait:57- An error occurred in another process (expected sequence number 5)
            lxc 20170208140239.411 ERROR    lxc_start - start.c:__lxc_start:1338 - Failed to spawn container "decent-giraffe".
            lxc 20170208140239.942 ERROR    lxc_conf - conf.c:run_buffer:347- Script exited with status 1
            lxc 20170208140239.942 ERROR    lxc_start - start.c:lxc_fini:546- Failed to run lxc.hook.post-stop for container "decent-giraffe".
            lxc 20170208140239.942 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20170208140239.943 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response

/var/log/lxd.log
bash: /var/log/lxd.log: No such file or directory

**Comment by one2Ter** [comment]
All my operation to a fresh install ubuntu 16.04

1
update to kernel 4.9

`wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9/linux-headers-4.9.0-040900_4.9.0-040900.201612111631_all.deb

wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9/linux-headers-4.9.0-040900-generic_4.9.0-040900.201612111631_amd64.deb

wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9/linux-image-4.9.0-040900-generic_4.9.0-040900.201612111631_amd64.deb

sudo dpkg -i *.deb

sudo update-grub

sudo reboot`


2
enable bbr

`sysctl net.core.default_qdisc=fq
sysctl net.ipv4.tcp_congestion_control=bbr`


enabled backports' repository enabled
`vim /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse
apt-get update
apt-get upgrade
`

3
use the non-LTS branch of LXD on Ubuntu 16.04 LTS
`apt install -t xenial-backports lxd lxd-client
 apt install zfsutils-linux
`


4
lxd init
newgrp lxd 
lxc launch ubuntu:


Then , problem occured.

**Comment by brauner** [comment]
It seems the network bridge `lxdbr0` already existed and so the initial configuration of LXD did not complete successfully. Did you have `LXD` installed and initialized/used before?

The second issue about AppArmor support being incomplete is surprising though. Trying to reproduce this now.

**Comment by one2Ter** [comment]
@brauner after running "lxd init" , I didn't see the interface of setting the network(container's private ip , subnet etc.) 

"AppArmor support being incomplete", I know nothing about this.

**Comment by brauner** [comment]
So what does `ip addr show lxdbr0` say?

**Comment by one2Ter** [comment]
root@kvm2g:~# ip addr show lxdbr0
3: lxdbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.89.253.1/24 scope global lxdbr0
       valid_lft forever preferred_lft forever
    inet6 fd42:e10e:f00a:adb0::1/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::5c9c:c0ff:feac:1633/64 scope link
       valid_lft forever preferred_lft forever

**Comment by brauner** [comment]
Well actually, I don't think you issue is that surprising. You're downloading and installing a mainline vanilla v4.9 kernel. This also means that various (currently) Ubuntu-specific AppArmor patches have not been applied yet and so liblxc's complaint is perfectly sound. There's is nothing we can do about this until the AppArmor patches have made it into mainline. (Which is in progress I think.) Until then you can either try running on a patched v4.9 Ubuntu kernel or set `lxc config set [<remote>:]<container> raw.lxc 'lxc.aa_allow_incomplete = 1'`.

**Comment by one2Ter** [comment]
https://github.com/lxc/lxd/issues/2853

In this issue, somebody say lxd 2.8 runs well on kernel 4.9. 
How can I manage to do it?

**Comment by dann1** [comment]
yes it works, I tested it on archlinux not in, ubuntu
