### ISSUE TITLE
When possible, allow remapping uid/gid of attached disk devices

### ISSUE THREAD

**Issue by lcavassa** [lxc/lxd#2860]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Xenial/16.04.1
   * Kernel version: 4.4.0-62-generic
   * LXD version: 2.8
   * Storage backend in use: dirs

In order to mount a writable/readable USB vfat formatted disk, I have to leverage on the bind-mount in this way:

mount -t vfat /dev/sdc1 /media -o rw,uid=100000,gid=100000
lxc config device add nginx sandisk disk source=/media path=/media

so specifying uid and gid accordingly the LXD/LXC configuration.

It would be really helpful, also in cases of fs without any uid/gid such as the vfat, to directly get a r/w mount inside the container just through the 'lxc config device add ...' command.

**Comment by stgraber** [comment]
Re-titled the issue a bit and milestoned to be implemented soon.

We should try to come up with a generic flag which we can apply today to any "disk" entry that's mounted from a block device and uses a filesystem which supports "uid=, gid=". For everything else, we should fail with an error until "shiftfs" or a similar kernel overlay exists and can be used to implement the same feature for those.
