### ISSUE TITLE
LXD storage api: Implement on-disk storage pool renaming if applicable to driver

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#2864]
Title says it all.

**Comment by brauner** [comment]
## LVM

- [x] implement volume group renaming by setting `lvm.vg_name` (addressed in #2975)

**Comment by brauner** [comment]
## ZFS

This is trickier than LVM:
- Using an actual pool (e.g. `pool2`):
  - This has to be done via `zpool export` followed by `zpool import`. For this to work ZFS will want us to have all datasets unmounted. I vote for only allowing renaming, when the pool is empty (aka no {containers,images,snapshots,storage volumes} otherwise we might run into classic zfs issues like not being able to mount storage volumes again and so on.
- Using a dataset (e.g. `pool2/vol1`):
  - *Might* be easier. ZFS will likely still want all datasets unmounted. Need to investigate.

**Comment by brauner** [comment]
I'm not sure where I currently stand on this. I don't see a nice way to do an on-disk rename of the storage pool in the general case. I think we close this issue for now since all other backends have been taken care of and think about it again once we get a request for it.

**Comment by Lin-Buo-Ren** [comment]
I wan't to rename the `default` dir driver pool but I can't.  I wonder if it's related to this issue?
