### ISSUE TITLE
Implement DELETE for /1.0/files

### ISSUE THREAD

**Issue by SwampFalc** [lxc/lxd#2868]
I've found myself wanting to delete files from a (stopped) container. Unfortunately, that's not an option in the current API...

Concretely, I'm trying to build a solid method of updating my containers, where I start by making a snapshot, copying that snapshot into a new container and then executing the update on that container. If it passes all tests after the update, the exact same update is executed on the production container and then everything gets cleaned up.

The problem is I have a puppet service running by default and I don't want the snapshot container to start that service. So, since after the copy the snapshot isn't running, I'd like to disable that service then and there.

But nowadays with systemd, there's no way I can find to prevent a service from starting that doesn't require deleting a file and that is not something possible through the current API. I could try to overwrite the specific file with an empty one, but who knows what havoc that might wreak...

**Comment by SwampFalc** [comment]
Oh, one more thing: the file that I would like to delete is a symlink to another file. So I'd want to delete the link, not the actual file.

**Comment by stgraber** [comment]
Sounds reasonable for us to implement DELETE in the files API and indeed, we wouldn't follow the symlinks in such case but delete the link itself instead.

Until we have that, I believe you should be able to push an empty file to /etc/systemd/system/UNIT-NAME.service which will take precedence over the original /lib/systemd/system/... file and effectively make the unit disappear as far as systemd is concerned (similar to "systemd mask" which creates a symlink to /dev/null).
