### ISSUE TITLE
Feature request: allow defining aliases on image create

### ISSUE THREAD

**Issue by FransM** [lxc/lxd#2870]
It would be nice if it was possible to define an alias when creating an image through the REST API.
According to the documentation this is not possible. (if it is consider this as a request to update the documentation)

**Comment by stgraber** [comment]
The reason why we didn't add it to the REST API was for the obvious race condition this causes as all image create operations are rather slow, ranging from a few seconds to a few minutes to complete. If something else creates the alias in between, that'd cause a failure for the whole image creation operation, discarding all the work that already happened.

Having it be a separate sync operation that you do once the image is created avoids that problem and is typically trivial to do in clients as the image creation operation gives you its fingerprint on success making it just one trivial API call to then create an alias which points to it.

**Comment by FransM** [comment]
I indeed did this as a sync operation after the image creation was completed.
Rationale for the request was the case were you actually do not want to wait until the image is created but just initiate the action and move on (and use the alias to pick up the alias later on)

**Comment by stgraber** [comment]
```
stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ curl --unix-socket /var/lib/lxd/unix.socket -X POST lxd/1.0/images -d '{"properties": {"foo": "bar"}, "aliases": [{"name": "alpine-edge-i386", "description": "Just a test"}], "source": {"type": "image", "mode": "pull", "server": "https://images.linuxcontainers.org", "protocol": "simplestreams", "alias": "alpine/edge/i386"}}' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   683  100   429  100   254  29514  17475 --:--:-- --:--:-- --:--:-- 30642
{
  "type": "async",
  "status": "Operation created",
  "status_code": 100,
  "operation": "/1.0/operations/60ff4de8-00a3-4bfb-8765-dc62b0f2db0c",
  "error_code": 0,
  "error": "",
  "metadata": {
    "id": "60ff4de8-00a3-4bfb-8765-dc62b0f2db0c",
    "class": "task",
    "created_at": "2017-03-08T01:50:08.868529062-05:00",
    "updated_at": "2017-03-08T01:50:08.868529062-05:00",
    "status": "Running",
    "status_code": 103,
    "resources": null,
    "metadata": null,
    "may_cancel": false,
    "err": ""
  }
}

stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc image info alpine-edge-i386
Fingerprint: 6214b45ef428645fafa2d69a4a11e2f044c72f3c03b0d30d965e50e1dc243343
Size: 2.42MB
Architecture: i686
Public: no
Timestamps:
    Created: 2017/03/07 00:00 UTC
    Uploaded: 2017/03/08 06:50 UTC
    Expires: never
    Last used: never
Properties:
    architecture: i386
    description: Alpine edge i386 (20170307_17:50)
    foo: bar
    os: Alpine
    release: edge
    serial: 20170307_17:50
Aliases:
    - alpine-edge-i386 (Just a test)
Auto update: disabled
Source:
    Server: https://images.linuxcontainers.org
    Protocol: simplestreams
    Alias: alpine/edge/i386
```
