### ISSUE TITLE
Feature request: files: append

### ISSUE THREAD

**Issue by FransM** [lxc/lxd#2871]
The other day I wanted to append something to a file in my container but there does not seem to be an easy way for this. 

The only options I found was: get the file from the container, modify it locally and write it back to the container or start the container and use lxc exec to append my text.
(and the latter was less desirable as this was for a network setting that I wanted to be in the container before I started it).

If files would have some append mechanism that could be useful

**Comment by stgraber** [comment]
That should be reasonably easy to add with an extra http header on POST.
