### ISSUE TITLE
documentation: more info on config and devices

### ISSUE THREAD

**Issue by FransM** [lxc/lxd#2872]
It would be nice to get some more info on config and devices and what works and what not.
I spent a fair amount of time trying to add a device while copying a new container from an existing one, but that did not work. 
Also the information on how to specify a device is quite brief.

(eventually I made it by creating an image from my container, then create a new container from my image adding the extra device; probably it is more efficient to copy the container then add the device, but I did not explore that part yet)

**Comment by stgraber** [comment]
Adding devices during copy should be supported. I'm not sure why it's not working. Will look into that.
