### ISSUE TITLE
Add extra "interface name" argument to "lxc network attach" and "lxc network attach-profile"

### ISSUE THREAD

**Issue by FransM** [lxc/lxd#2873]
Inspired by the lxc network help message I tried this:

lxc network attach enp0s3 mycontainer eth5

I expected the device to be called eth5 but if I do an ifconfig in the container it just uses the first free number (eth2 in my case).

Not sure if this can be fixed easily or if I should have gotten an error message on the attach command telling me that it could not bind to eth5.

**Comment by stgraber** [comment]
You're confusing LXD device names and kernel interface names, those are two different things.

If you do "lxc config show mycontainer --expanded", you'll see that the LXD device indeed got called "eth5".
What you want is the "name" property of the nic device entry which does control the kernel device name.

"lxc config device set mycontainer eth5 name eth5" would do the trick.

I personally use the bridge name as the LXD device name to make things look a bit less confusing :)

We could add an extra argument to "lxc network attach" to let you set the interface name inside the container, which may help a bit with the confusion.

**Comment by FransM** [comment]
Ah ok. My impression was that these are the same. Maybe the difference between device names and kernel interface names could be better explained (but maybe it is just my lousy understanding)
Or maybe device name and kernel interface name should be made identical.

(a bit off-topic: for me after studying the rest api it is still not too clear how to do things like lxc config device etc via the rest api (and my rationale for using the rest api is that I do not want my users having to install lxd locally in order to create containers))

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/blob/master/doc/configuration.md#type-nic shows the "name" property and its meaning.

The LXD device name can't be synced with the interface name as that wouldn't account for conflicts where a container uses multiple profiles each with a bunch of network devices and the user's expectation that the ethX devices be sequential.

"lxc config device ..." is done with PUT or PATCH to /1.0/containers/NAME

Note that you can perfectly install lxd-client for your users which is only the client tool and doesn't include the LXD daemon itself. The client tool can also be built and used directly on Windows or MacOS.

**Comment by FransM** [comment]
Maybe I should create a new ticket for this instead of adding here but as you mentioned it here in a comment:

I tried this:
"lxc config device ..." is done with PUT or PATCH to /1.0/containers/NAME
in various situations with the following observations. Not sure if these are bugs or misunderstandings (in which case maybe the documentation could be improved.

Trying to add devices using PATCH works as expected
I did not find a way to remove devices using PATCH. If I use patch on a container with 3 devices and list only two in the config file, the third one still remains (I expected all of devices to be replaced with the new ones)

Using PUT also works; then I can also remove devices; The documentation could probably explain a bit more that this needs to be a complete config (it mentions it takes the same struc as provided by get; maybe it should suggest more explicitly that it is ofen most convenient to do a get then modify the dict and do a put (assuming patch does not suffice)
(actually it took a bit of time for me to sort this out, initially I tried only sending a config with the changed fields using PUT)

**Comment by stgraber** [comment]
We didn't really feel like we should define standard HTTP methods in the LXD documentation itself.
We're using the standard meaning of GET, POST, PUT, PATCH and DELETE and is consistent with other REST APIs.

 - GET gets an object or an object collection (collection being a list of object URLs)
 - POST causes the creation of a new object (we abuse it a tiny bit by using it for renames and migration
 - PUT replaces an existing object with a new version
 - PATCH replaces only the listed fields of an existing object
 - DELETE removes the object
