### ISSUE TITLE
lxc image copy documentation

### ISSUE THREAD

**Issue by pxcluster** [lxc/lxd#2874]
I've tried hard to find a documentation regarding the command :

lxc image copy...

I'd like to copy an image which is identified by its fingerprint. The documentation talks about the ability to specify a 'version', but... it may represent 30 different images... and don't need all of them.

Where are the real 'manuals' of all the lxc commands ? The current method of 'lxc ... --help' is way not sufficient.

**Comment by stgraber** [comment]
"lxc image copy --help" shows:

```
lxc image copy [<remote>:]<image> <remote>: [--alias=ALIAS...] [--copy-aliases] [--public] [--auto-update]
    Copy an image from one LXD daemon to another over the network.

    The auto-update flag instructs the server to keep this image up to
    date. It requires the source to be an alias and for it to be public.
```

At the top of the same help message, you have:

```
The image unique identifier is the hash (sha-256) of its representation
as a compressed tarball (or for split images, the concatenation of the
metadata and rootfs tarballs).
```

So this means that you can do:

    lxc image copy HASH remote:

So do "lxc image list", get the fingerprint of the image and then pass that to "lxc image copy".
