### ISSUE TITLE
ceph support

### ISSUE THREAD

**Issue by dann1** [lxc/lxd#2875]
Is LXD going to have, in a near future, support for **Ceph** as storage backend? There is a feature request https://github.com/lxc/lxd/issues/1258 about that, but that was submitted in Nov 2015.

**Comment by stgraber** [comment]
It shouldn't be too difficult to add on top of @brauner work, but right now it's not something that we've seen enough demand to implement ourselves, which is why the issue you're referring to is marked as both Maybe and milestoned to "later".

**Comment by jamesbeedy** [comment]
Aweee +100 for Ceph backend here

**Comment by jocado** [comment]
I believe ceph is the most popular storage backend used in openstack, for cinder and glance.
If nova-lxd wants to become a first class citizen in openstack, I would say that ceph support for lxd is a must!
+1 from me :)

**Comment by stgraber** [comment]
@jocado but ceph for LXD would be restricted to what a normal storage backend does for LXD, so it wouldn't let you attach arbitrary volumes defined outside of LXD, making this a bit less useful for nova-lxd.

The nova-lxd team are instead looking at implementing support for the ceph backed openstack volumes at the nova-lxd level instead of through LXD itself.

**Comment by jocado** [comment]
I guess that's true, although direct support in LXD would be good migration between hosts to some extent.

In any case, I'm glad to here that there is a solution being looked at for nova-lxd, as this is my primary interest right now :)

**Comment by mariojmdavid** [comment]
in my opinion if nova-lxd is something more than a playground, then support of ceph volumes should be a must, at least for cinder volume attachments
we have ceph serving cinder and glance
I have recently deployed a compute node with ubuntu (16.04), the rest of our OS infra is centos7, and decided to try nova-lxd, the others are qemu/kvm, and was disappointed when I realized I could not use ceph to attach volumes or to boot from ceph block devices.
I understand that quite a large number of OS deployments is using ceph, so I had guessed that supporting it in all (most) nova-drivers would be high priority
I can't evaluate the best strategy to do that, and I don't want to sound as negative criticism, but help push this to the light of day

**Comment by brauner** [comment]
We recently merged https://github.com/lxc/lxd/issues/3566 and `CEPH` support is available in `LXD 2.16` which was released yesterday.
