### ISSUE TITLE
Feature request: trusted mode

### ISSUE THREAD

**Issue by FransM** [lxc/lxd#2886]
In our environment we use shortlived containers for running some tests. The value of these containers is low and we are running in a safe/trusted environment but containers can be created from a large number of different hosts

As such for us certificates, authentication etc is just overhead and a bit of a nuisance.
We would like to suggest an lxd config option to allow unauthenticated access.
(of course this is insecure but for some cases, like ours, this is not a problem and a convenience)

**Comment by stgraber** [comment]
I don't think it's something we want to support as unfortunately adding such a feature will see some automated tool making use of it without checking if the host is publicly reachable first, leading to LXD hosts exposed on the internet without authentication, giving remote root access to all the affected hosts.

It's something that's hit a number of other projects lately, thanks to internet-wide scanning being very easy nowadays.

Note that if you don't care about potential MITM attacks, you can instruct "lxc remote" to add a remote in a single command:

    lxc remote add my-remote 1.2.3.4 --accept-certificate --password=TRUST-PASSWORD

So assuming you don't change the core.trust_password value, it's a single line that will work on any of your hosts. This will still use individual certificates which will start piling up on the LXD daemon.

If you want to avoid that too, then you may want to use a single client certificate for your machines. Simply add a first machine to LXD, then copy its ~/.config/lxc/client.crt and ~/.config/lxc/client.key (or the whole directory if you want the remote configuration too).

If you really really want unauthenticated access to LXD, then you have one last option which is to run something like nginx on your machine and have it forward the /var/lib/lxd/unix.socket over http. This will effectively do what you want in that there is no authentication on /var/lib/lxd/unix.socket other than file ownership, so all connections will automatically be trusted by LXD.
