### ISSUE TITLE
`lxc list --format json` output changed case

### ISSUE THREAD

**Issue by FauxFaux** [lxc/lxd#2887]
# Issue description

Between lxd `2.0.8-0ubuntu1~ubuntu16.04.2` and `2.0.9-0ubuntu1~16.04.1` (Ubuntu Xenial), the output format of `lxc list --format json` has changed, which breaks our scripts.

Previously, the command emitted lower case JSON key names in all cases. Now, it emits upper/title case names for "State" and "Snapshots":

```
    "status": "Running",
    "status_code": 103,
    "State": {
      "status": "Running",
      "status_code": 103,
      "disk": {},
...
    },
    "Snapshots": []
  },
```

This seems to have been an accident: https://github.com/lxc/lxd/commit/37ddfb27#diff-9420fffec0d592a9827424dc2025c08eL367

I suggest that the old format is restored? It doesn't appear to be documented, however, so maybe this is intentional.

Example script:

```
lxc list --format json \
  | jq -r '.[]|select(.name=="'$1'").state.network.eth0.addresses[]|select(.family=="inet").address'
```

**Comment by stgraber** [comment]
Indeed wasn't intentional and a side effect of switching to the new API code for yaml and json generation. I'll go through the various structs in api/ and make sure we have names defined for both yaml and json for all of them, that should take care of it.
