### ISSUE TITLE
Extracting data

### ISSUE THREAD

**Issue by ktechmidas** [lxc/lxd#2894]
Hi,

Sorry if I'm in the wrong place, I just need some pointers to extract some data from my original LXD host. So my hosting provider deleted my server which is a huge pain for me, all I have left is a backup from January of /var/lib/lxd and a zfs.img in there which I assume holds all my data as it's 95G.

Is there any way to extract my container data from the zfs.img?

**Comment by lagunax** [comment]
i think you can try something from https://groups.google.com/forum/m/#!topic/zfs-fuse/s2njFgkOfhg (look at last post from fajar). At any case, @stgraber or @brauner can describe, how lxc works with images

**Comment by ktechmidas** [comment]
The iscsi stuff is very confusing here... how do I do this part specifically? Do I need to use iscsi to get the image into a readable format?

"setup iscsi
server to export /path/to/your/solaris.img usig tgtadm (part of
scsi-target-utils on RHEL5), and then import the disk back using
iscsiadm (part of iscsi-initiator-utils)."

**Comment by ktechmidas** [comment]
Ah the second link with dd was much easier to understand, was just missing some ZFS knowledge. Let's see if this works.

**Comment by ktechmidas** [comment]
Right... I'm missing something here, I did what they suggested. Created a pool on /dev/vdc and then created a volume: zfs create -V 130gb tank/vol

I copied everything with dd to /dev/zvol/tank/vol

Now how do I mount /dev/zvol/tank/vol? Mount doesn't seem to work:

mount: unknown filesystem type 'zfs_member'
----
So then I try...

zfs set mountpoint=legacy tank/vol

cannot set property for 'tank/vol': 'mountpoint' doesnot apply to datasets of this type
---

Then I find this: https://vox.veritas.com/t5/Discussions/ZFS-pool-volume-does-not-mounting-via-mount-resource/td-p/574644

which tells me "you have zfs volume created using zfs create -V option and now tryng to mount that volume as a zfs file sytem."

Which is what the proxmox link above told me to do... is there another way...?

**Comment by stgraber** [comment]
If you want to restore your full LXD setup, then just restoring those files in /var/lib/lxd of another host (that supports zfs) and rebooting should do the trick.

If you just want to mount your old zpool, you should be able to run "zpool import /path/to/zfs.img lxd" (assuming the pool was called "lxd"). This should then have the pool show up in "zpool list" and in "zfs list -t all".

**Comment by ktechmidas** [comment]
Is there any way to find out what the pool was called?

root@iZ6wefy8r9jd5wk9ee5va8Z:/mnt# zpool import /mnt/zfs.img lxd
cannot import '/mnt/zfs.img': no such pool available

**Comment by ktechmidas** [comment]
>If you want to restore your full LXD setup, then just restoring those files in /var/lib/lxd of another host (that supports zfs) and rebooting should do the trick.

Isn't there some kind of database too?

**Comment by stgraber** [comment]
sqlite3 lxd.db 'SELECT value FROM config WHERE key="storage.zfs_pool_name"'

**Comment by ktechmidas** [comment]
root@iZ6wefy8r9jd5wk9ee5va8Z:/mnt# sqlite3 lxd.db 'SELECT value FROM config WHERE key="storage.zfs_pool_name"'
lxd


So it is lxd, yet the zpool import won't work. Odd right?

**Comment by stgraber** [comment]
You want "zpool import -d /mnt lxd" to to import a pool called "lxd" from files stored in "/mnt"

**Comment by vince06fr** [comment]
Similar issue for me
rsync the entire lxd from damaged server to another server with lxd support should work??

**Comment by stgraber** [comment]
If you can't get the zpool back online, you can't see the containers filesystem so I'm not sure what there would be to copy over to another server.

If you ran "zfs destroy" on some of the containers filesystem, then those containers are gone, there's no way to recover them.

**Comment by vince06fr** [comment]
can i use zfs send/receive and a copy of the lxd directory to recover just the container i need?

**Comment by stgraber** [comment]
send/receive only works if your zpool is online, so far it sounds like it's not, or I misunderstood your current situation.

**Comment by stgraber** [comment]
What does "sudo zpool status" and "sudo zfs list -t all" show?

**Comment by vince06fr** [comment]
ok
I have better to do a new install, there are no sensitive datas on this server.
Thank you for your answer
