### ISSUE TITLE
How to scale LXD daemon ?

### ISSUE THREAD

**Issue by sequoiar** [lxc/lxd#2897]
Seems LXD run single process daemon. Is it possible run LXD in multi-thread or multi-process ?

**Comment by stgraber** [comment]
LXD is written in Go and heavily uses go routines for parallelism so is very heavily multi-threaded.

**Comment by sequoiar** [comment]
@stgraber so, once use systemctrl to assign the dedicated CPU numbers or range to LXD, then LXD daemon will scale to multi-threading automatically  ?

**Comment by stgraber** [comment]
Does "zpool import -d /var/lib/lxd" (directory where the .img file is in) work any better?
