### ISSUE TITLE
Implement the proper "lxc image list" rendering

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#290]
1. lxd-images import lxc ubuntu trusty amd64 --alias ubuntu
2. lxc image list

Output shows some hash, not 'ubuntu'

Output should show the alias if provided.

**Comment by stgraber** [comment]
Note that this is blocked on us having image properties so we can implement the documented behavior for "lxc image list".

**Comment by hallyn** [comment]
Where exactly is the behavior documented? We now have properties but I'm not sure what to show.  Should we just show the shortest alias that exists, followed by a one-line list of the other aliases, followed by properties?  How should properties be shown?  It seems like the output could quickly become unwieldy.

**Comment by raharper** [comment]
I'd suggest something similar to glance image-list or nova image-list which
provides the simple name (alias) and a unique id.
And I'd suggest it would be useful to have a lxc image show <alias|uniq>
and dump the more detailed information (similar to glance image-show).

Ryan

**Comment by hallyn** [comment]
Ah, there's no "image show" but there's "image info", so we can use that for
the properties list.  But for now my question was really about what has been
already spec'ed, if anything.
