### ISSUE TITLE
lxc launch <alias> first errors with container is not defined

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#291]
1. % sudo ~/go/bin/lxd --debug --tcp 127.0.0.1:8443
2. chown unix socket to user
3. % ./scripts/lxd-images import lxc ubuntu vivid amd64 --alias ubuntu-vivid 
(lambic) lxd % ./scripts/lxd-images import lxc ubuntu vivid amd64 --alias ubuntu-vivid 
Downloading the GPG key for https://images.linuxcontainers.org
Downloading the image list for https://images.linuxcontainers.org
Validating the GPG signature of /tmp/tmpvhsoqv9l/index.json.asc
[]
Downloading the image: https://images.linuxcontainers.org/images/ubuntu/vivid/amd64/default/20150227_03:49/rootfs.tar.xz
Validating the GPG signature of /tmp/tmpvhsoqv9l/ubuntu-vivid-amd64-default-20150227_03:49.rootfs.tar.xz.asc
Repacking the image for LXD
Image imported as: 93a579be30e895b4671cc0227be64120997481f83a7675f7758c8a1ff2488926
Setup alias: ubuntu-vivid
(lambic) lxd % lxc image alias list
ubuntu-vivid
4. (lambic) lxd % lxc launch ubuntu-vivid first 
Creating container...done
Starting container...done
error: container is not defined

On the lxd side, I have this output:
2015/02/27 15:37:25 handling GET /1.0
2015/02/27 15:37:25 handling GET /1.0/images/aliases
2015/02/27 15:37:25 responding to images/aliases:get
2015/02/27 15:37:36 handling GET /1.0
2015/02/27 15:37:36 handling GET /1.0/images/aliases/ubuntu-vivid
2015/02/27 15:37:36 handling POST /1.0/containers
2015/02/27 15:37:36 responding to create
2015/02/27 15:37:36 handling GET /1.0/operations/b0617b41-6d27-48bd-a135-b893837d89e2/wait
2015/02/27 15:37:43 handling PUT /1.0/containers/first/state
2015/02/27 15:37:43 handling GET /1.0/operations/ceffb0de-ce28-4411-b1ca-b4aae60d7c7c/wait

(lambic) lxd % lxc list
first: STOPPED
(lambic) lxd % lxc start first 
error: container is not defined

**Comment by stgraber** [comment]
You're building with an old go-lxc, that issue was fixed in go-lxc a week ago.

**Comment by raharper** [comment]
go get -u -v ./... in lxd's dir aft you git pull
