### ISSUE TITLE
btrfs storage driver is pretty broken in LXD 2.9

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#2911]
We use btrfs for the LXD demo server, the things I've noticed that are broken so far:
 - btrfs quota isn't enabled by default (sent a PR for this)
 - Copying/moving/deleting btrfs backed containers that have subvolumes inside them fails with:
```
error: remove /var/lib/lxd/storage-pools/default/containers/tryit-subtle: directory not empty
```
I remember writing logic to avoid that kind of issue, was that accidentally dropped?
 - Snapshot and publish handling is broken. Creating a container, then making a snapshot of it, then restoring that snapshot and finally publishing that same snapshot, fails with:

```
error: The snapshot is already mounted read-write.
```

**Comment by brauner** [comment]
@stgraber about the snapshot-restore-publish problem. Can you give a reproducer? I tried to reproduce but it worked fine:

<a href="https://asciinema.org/a/104074" target="_blank"><img src="https://asciinema.org/a/104074.png" /></a>

**Comment by stgraber** [comment]
@brauner hmm, it was in a nested unprivileged container with host and container both using btrfs as their storage backend.

**Comment by stgraber** [comment]
Not sure why it'd matter though, we don't really have any codepath that's exclusive to nested btrfs...

**Comment by theblazehen** [comment]
@stgraber I had the same issue, unfortunately I already wiped the lxd install and restored containers from config management + backup, so I won't be able to help with reproducing the issue. Had that issue with all containers that I ran docker + btrfs in

**Comment by brauner** [comment]
This has been addressed by @stgraber in https://github.com/lxc/lxd/pull/2922 and should be fixed in newer releases. :)
