### ISSUE TITLE
stateless stop fail

### ISSUE THREAD

**Issue by vince06fr** [lxc/lxd#2913]
# Required information

 * Distribution: Ubuntu
 * Distribution version: xenial
 * $ lxc info
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 192.168.10.163:8443
  - 10.67.68.1:8443
  - '[fd43:8b6:2b81:de3d::1]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    x
x
x
    x
    -----END CERTIFICATE-----
  certificate_fingerprint: 
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-63-generic
  server: lxd
  server_pid: 2157
  server_version: 2.9.1
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu15

# Issue description: fail to do a stateless stop

# Steps to reproduce
```
$ lxc stop --stateful test 
error: snapshot dump failed
(00.557470) Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
(01.195529) Error (criu/parasite-syscall.c:532): Unable to connect a transport socket: Permission denied
(01.195546) Error (criu/parasite-syscall.c:134): Can't block signals for 3894: No such process
(01.195557) Error (criu/cr-dump.c:1244): Can't infect (pid: 3894) with parasite
(01.199548) Error (criu/ptrace.c:54): Unable to detach from 3894: No such process
(01.199810) Error (criu/cr-dump.c:1628): Dumping FAILED.
Try `lxc info --show-log test` for more info
```

```
$ lxc info --show-log test
Name: test
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/02/20 13:30 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 3526
Ips:
  eth0:	inet	10.67.68.36	veth1QKC1X
  eth0:	inet6	fd43:8b6:2b81:de3d:216:3eff:fe66:d57	veth1QKC1X
  eth0:	inet6	fe80::216:3eff:fe66:d57	veth1QKC1X
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 27
  Disk usage:
    root: 6.64MB
  CPU usage:
    CPU usage (in seconds): 4
  Memory usage:
    Memory (current): 76.64MB
    Memory (peak): 198.28MB
  Network usage:
    eth0:
      Bytes received: 3.04kB
      Bytes sent: 1.55kB
      Packets received: 26
      Packets sent: 14
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

            lxc 20160220133105.929 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 3522, expected pid 3526.
            lxc 20160220133133.611 ERROR    lxc_criu - criu.c:do_dump:1124 - dump failed with 1
            lxc 20160220133133.611 ERROR    lxc_criu - criu.c:do_dump:1138 - criu output: Will skip in-flight TCP connections

            lxc 20160220133822.574 ERROR    lxc_criu - criu.c:do_dump:1124 - dump failed with 1
            lxc 20160220133822.574 ERROR    lxc_criu - criu.c:do_dump:1138 - criu output: Will skip in-flight TCP connections

            lxc 20160220134016.791 ERROR    lxc_criu - criu.c:do_dump:1124 - dump failed with 1
            lxc 20160220134016.791 ERROR    lxc_criu - criu.c:do_dump:1138 - criu output: Will skip in-flight TCP connections
```

**Comment by stgraber** [comment]
That'd be a CRIU bug, not a LXD one. Based on the errors, it could just be a race condition in the dump, meaning that a retry may fix it or it could be a confusing way for CRIU to report one of the few usual issues that happen (undumpable socket, apparmor profile dump/restore, ...).

I'm closing this issue as there's nothing wrong in LXD as this is a CRIU issue. You can file a bug report at https://bugs.launchpad.net/ubuntu/+source/criu/+filebug for tracking, though note that Canonical isn't working on CRIU anymore unless we get a paid engagement.

So you may want to try a newer CRIU version to see if upstream fixed it, in which case we'll be happy to update our packages. If that doesn't help, then you can try to fix the issue yourself, pay Canonical to do so or see if someone involved with CRIU upstream knows what's going on and how to fix it.
