### ISSUE TITLE
Upgrade from 2.8 to 2.9.1 results in broken install.

### ISSUE THREAD

**Issue by geodb27** [lxc/lxd#2919]
* Distribution: Ubuntu LTS 
 * Distribution version: 16.04
   * Kernel version: 4.4.0-59-generic
   * LXC version: 2.9.1
   * LXD version: 2.9.1
   * Storage backend in use: dir

Had many containers initiated from version 2.0.x to 2.8, dir backend storage and all went fine. Since update to 2.9.1, lxd refuses to start, with this error message : 

"error: UNIQUE constraint failed: storage_pools.name"

As a matter of fact, I've never defined any storage pool, since this was not supported by earlier versions. Furthermore, since there is none configured, there shouldn't be named duplicates. So, I'm stuck still and cannot run lxd anymore on these hosts.

Steps to reproduce
 1. Step one
Install lxd version prior to 2.9.1, use dir backend and do not define any storage pool.
 2. Step two
Create one or more container.
 3. Step three
Update to 2.9.1

 - [ ] output of the daemon with --debug
lxd --debug
INFO[02-21|10:09:39] LXD 2.9.1 is starting in normal mode     path=/var/lib/lxd
WARN[02-21|10:09:39] CGroup memory swap accounting is disabled, swap limits will be ignored. 
INFO[02-21|10:09:39] Default uid/gid map: 
INFO[02-21|10:09:39]  - u 0 100000 65536 
INFO[02-21|10:09:39]  - g 0 100000 65536 
DBUG[02-21|10:09:39] Initializing and checking storage pool "default". 
DBUG[02-21|10:09:39] StoragePoolInit                          driver=storage/dir
DBUG[02-21|10:09:39] StoragePoolCheck                         driver=storage/dir
DBUG[02-21|10:09:39] Applying patch: storage_api 
error: UNIQUE constraint failed: storage_pools.name

**Comment by brauner** [comment]
We've pushed a new version to the PPAs yesterday night: LXD 2.9.2 which hopefully fixes these issues.

**Comment by stgraber** [comment]
Right, that particular issue is something that 2.9.2 is meant to address. Please update your system, that will get you LXD 2.9.2 which should pick up that broken upgrade and fix it.

If you still run into issues with LXD 2.9.2, please reopen the bug.
