### ISSUE TITLE
LXC migration failing

### ISSUE THREAD

**Issue by ktechmidas** [lxc/lxd#2920]
Hi, I have an issue similar to the one here: https://github.com/lxc/lxd/issues/2019

root@iZ6wefy8r9jd5wk9ee5va8Z:~# lxc move srv-dc-seafile awss:
error: Unable to connect to: 10.138.177.1:8443

However I know it's not a firewall issue and can connect to both ends:

[Local]
root@iZ6wefy8r9jd5wk9ee5va8Z:~# nc -vz 10.138.177.1 8443
Connection to 10.138.177.1 8443 port [tcp/*] succeeded!

[Remote]
root@ip-172-31-14-246:~# nc -vz 47.91.16.178 8443
Connection to 47.91.16.178 8443 port [tcp/*] succeeded!

Any idea what could be happening here?

**Comment by stgraber** [comment]
Is 10.138.177.1 maybe defined on both hosts as a local IP? In which case the target host can indeed connect to that IP, but it's talking to the wrong machine.
