### ISSUE TITLE
snaps can't be installed in lxd  privileged container

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#2927]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.10
 * The output of "lxc info" or if that fails:
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
api_status: stable
api_version: "1.0"
auth: trusted
public: false
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.8.0-39-generic
  server: lxd
  server_pid: 9570
  server_version: 2.9.2
  storage: btrfs
  storage_version: 4.7.3

# Issue description

can't install snaps in privileged lxd container.
Errors:
Feb 22 11:54:19 openstack systemd[1]: snapd.refresh.timer: Adding 5h 26min 17.796383s random time.
Feb 22 11:54:19 openstack systemd[1]: snapd.refresh.timer: Adding 1h 51min 55.488951s random time.
Feb 22 11:54:19 openstack systemd[1]: apt-daily.timer: Adding 2h 27min 38.454833s random time.
Feb 22 11:54:19 openstack systemd[1]: Reloading.
Feb 22 11:54:19 openstack systemd[1]: snapd.refresh.timer: Adding 42min 54.623747s random time.
Feb 22 11:54:19 openstack systemd[1]: snapd.refresh.timer: Adding 5min 38.854538s random time.
Feb 22 11:54:19 openstack systemd[1]: apt-daily.timer: Adding 1h 28min 16.972743s random time.
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /system.slice/snap-core-1264.mount: Operation not permitted
Feb 22 11:54:19 openstack systemd[1]: Mounting Mount unit for core...
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /init.scope: Operation not permitted
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /user.slice: Operation not permitted
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /system.slice/irqbalance.service: Operation not permitted
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /system.slice/resolvconf.service: Operation not permitted
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /system.slice/ssh.service: Operation not permitted
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /system.slice/sys-kernel-debug.mount: Operation not permitted
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /system.slice/apparmor.service: Operation not permitted
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /system.slice/ondemand.service: Operation not permitted
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /system.slice/lvm2-monitor.service: Operation not permitted
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /system.slice/networking.service: Operation not permitted
Feb 22 11:54:19 openstack mount[2399]: mount: /snap/core/1264: mount failed: Unknown error -1
Feb 22 11:54:19 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-journal-flush.service: Operation not permitted

# Steps to reproduce

 1. create a privileged contained : lxc launch ubuntu:16.04 openstack -c security.privileged=true -c security.nesting=true -c "linux.kernel_modules=iptable_nat, ip6table_nat, ebtables, openvswitch" -p public
 2. update container: apt update; apt upgrade
 3. install snapd: apt install snapd
4. install any snap: snap install hello-world

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
That's correct. Snaps require the apparmor namespacing and stacking feature which is tied to user namespaces, making it only work with unprivileged containers.

So it's effectively a kernel restriction that LXD can't do anything about.

That being said. and that's what I do in https://stgraber.org/2017/01/13/kubernetes-inside-lxd/. if you turn off all the containment security of the container and let it load apparmor profiles directly in the host namespace, then you can get things working inside a privileged container. This is obviously a terrible idea from a security point of view because it's trivial to escape such a container and loading profiles in the host namespace can lead to profile conflicts, but it may be good enough for what you want to do.

**Comment by gaetanquentin** [comment]
OK. I have made the container modification  and conjure-up can be installed now as a snap. Thanks.
