### ISSUE TITLE
ERROR: could not insert 'v4l2loopback': Operation not permitted

### ISSUE THREAD

**Issue by voxsoftware** [lxc/lxd#2936]
Ubuntu 16.04 server with xfce-desktop
ERROR: could not insert 'v4l2loopback': Operation not permitted

when i use 

sudo modprobe 'v4l2loopback'

I have privileged container 
Host: Ubuntu 16.04 64 bits
Guest: Ubuntu 16.04 64 bits

**Comment by stgraber** [comment]
Yep, that's normal, containers can't load kernel modules. That's kinda the point of containers, you're sharing your kernel with the host, so you can't have a container load kernel code.

You should do:

    lxc config set CONTAINER-NAME linux.kernel_modules v4l2loopback

Which will have LXD load the kernel module for you at the host level.

**Comment by voxsoftware** [comment]
with your code does't work too

**Comment by stgraber** [comment]
I'm not familiar with v4l2loopback but some googling suggests that it's an out of tree kernel module which you need to build and load yourself. That part needs to be done as root on the host.

Once the module is loaded, it creates /dev/video* devices which you can then pass into the container using for example:

    lxc config device add CONTAINER-NAME video0 unix-char path=/dev/video0
