### ISSUE TITLE
[gentoo] unprivileged systemd based containers do not start

### ISSUE THREAD

**Issue by alexanderhaensch** [lxc/lxd#2937]
# Required information

 * Distribution: Ge ntoo
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.39-gentoo
   * LXC version: 2.0.7
   * LXD version: 2.8
   * Storage backend in use: dir

# Issue description
If i lauch ubuntu 16.04 or centos7 images the container does not init systemd

# Steps to reproduce

```
io ~ # lxc start test1
io ~ # lxc exec test1 bash
[root@test1 ~]# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  8.5  0.0  42480  3668 ?        Ss   07:36   0:01 /sbin/init
root         2  0.0  0.0  11776  2900 ?        Ss   07:37   0:00 bash
root        11  0.0  0.0  47448  3252 ?        R+   07:37   0:00 ps aux
```

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
Name: test1
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/02/22 16:54 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 1403
Ips:
  eth0: inet6   fe80::216:3eff:feca:d376        vethMVGOM4
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 1
  CPU usage:
    CPU usage (in seconds): 0
  Memory usage:
    Memory (current): 8.86MB
    Memory (peak): 9.93MB
  Network usage:
    eth0:
      Bytes received: 51.25kB
      Bytes sent: 648B
      Packets received: 611
      Packets sent: 8
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

            **lxc 20160223073657.567 WARN     lxc_cgmanager - cgroups/cgmanager.c:cgm_get:992 - do_cgm_get exited with error
            lxc 20160223073658.784 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 1397, expected pid 1403.**

 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
That's most likely because /sys/fs/cgroup/systemd isn't mounted on the host. systemd in the container tends to hang/crash when that happens.

**Comment by alexanderhaensch** [comment]
```
io ~ # mount | grep systemd
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)

```

If i set privileged to true then it works.. I am missing the point why the unprivileged container does not work.

**Comment by stgraber** [comment]
Hmm, can you post the content of "/proc/mounts" from inside the container?

**Comment by alexanderhaensch** [comment]
```
/dev/md1 / ext4 rw,noatime,data=ordered 0 0                                                                                                                                                                                                                                               
none /dev tmpfs rw,nodev,relatime,size=492k,mode=755,uid=1000000,gid=1000000 0 0                                                                                                                                                                                                          
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0                                                                                                                                                                                                                                       
sysfs /sys sysfs rw,nodev,relatime 0 0                                                                                                                                                                                                                                                    
udev /dev/fuse devtmpfs rw,nosuid,relatime,size=10240k,nr_inodes=16497112,mode=755 0 0
udev /dev/net/tun devtmpfs rw,nosuid,relatime,size=10240k,nr_inodes=16497112,mode=755 0 0
proc /proc/sys/fs/binfmt_misc proc rw,nosuid,nodev,noexec,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
/dev/md1 /dev/lxd ext4 rw,noatime,data=ordered 0 0
/dev/md1 /dev/.lxd-mounts ext4 rw,noatime,data=ordered 0 0
cgroup /sys/fs/cgroup tmpfs rw,nodev,relatime,size=12k,mode=755,uid=1000000,gid=1000000 0 0
tmpfs /sys/fs/cgroup/cgmanager tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
udev /dev/null devtmpfs rw,nosuid,relatime,size=10240k,nr_inodes=16497112,mode=755 0 0
udev /dev/zero devtmpfs rw,nosuid,relatime,size=10240k,nr_inodes=16497112,mode=755 0 0
udev /dev/full devtmpfs rw,nosuid,relatime,size=10240k,nr_inodes=16497112,mode=755 0 0
udev /dev/urandom devtmpfs rw,nosuid,relatime,size=10240k,nr_inodes=16497112,mode=755 0 0
udev /dev/random devtmpfs rw,nosuid,relatime,size=10240k,nr_inodes=16497112,mode=755 0 0
udev /dev/tty devtmpfs rw,nosuid,relatime,size=10240k,nr_inodes=16497112,mode=755 0 0
devpts /dev/console devpts rw,relatime,gid=5,mode=620,ptmxmode=666 0 0
devpts /dev/pts devpts rw,relatime,gid=1000005,mode=620,ptmxmode=666 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,uid=1000000,gid=1000000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755,uid=1000000,gid=1000000 0 0

```

**Comment by stgraber** [comment]
@alexanderhaensch looks like you don't have lxcfs installed on your system, so the various cgroup paths aren't mounted in the container.

**Comment by stgraber** [comment]
Also note that cgmanager is deprecated so you really shouldn't have it installed nor have LXC be built with cgmanager support anymore.

**Comment by alexanderhaensch** [comment]
Okay that means gentoo ebuilds does not reflect this. Commenting out all cgmanager from the ebuild solves the issue. Thank you very much! @stgraber
