### ISSUE TITLE
lxc list json format state and snapshots used capital S in 2.0.9

### ISSUE THREAD

**Issue by anigeo** [lxc/lxd#2938]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-62-generic
   * LXC version: 2.0.7
   * LXD version: 2.0.9
   * Storage backend in use: dir

# Issue description

The json output of `lxc list --format=json` used .[].**S**tate and .[].**S**napshots in 2.0.9, while it was small **s** in 2.0.8 and also in 2.9.1, as I didn't aware it's on changelog so far, is it an expected change? So I shall update all our script that reading these info.

# Steps to reproduce

 1. Upgrade to LXD 2.0.9
 2. Do `lxc list --format=json`

# Information to attach

`lxc list --format=json` output in 2.0.8:
```
[
  {
    "architecture": "x86_64",
    .
    .
    .
    "stateful": false,
    "status": "Running",
    "status_code": 103,
    "state": {
      "status": "Running",
      "status_code": 103,
      "disk": {}
      .
      .
    },
    "snapshots": []
  }
]
```

`lxc list --format=json` output in 2.0.9:
```
[
  {
    "architecture": "x86_64",
    .
    .
    .
    "stateful": false,
    "status": "Running",
    "status_code": 103,
    "State": {
      "status": "Running",
      "status_code": 103,
      "disk": {}
      .
      .
    },
    "Snapshots": []
  }
]
```

**Comment by brauner** [comment]
I'm pretty sure this wasn't intended. (ping @stgraber)

**Comment by stgraber** [comment]
Yep and it's been fixed in git already

**Comment by stgraber** [comment]
I've been busy with the storage fixes lately but the plan is to push an intermediary SRU to Ubuntu with that fix cherry-picked.

**Comment by stgraber** [comment]
https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1667406
