### ISSUE TITLE
lxd-images got KeyError: 'metadata' in aliases_list

### ISSUE THREAD

**Issue by hnakamur** [lxc/lxd#294]
I tried LXD version 0.2 https://github.com/lxc/lxd/commit/262190ab09ffbb9ebd1f984f9a2b78e768bf81ec
and followed steps in README.

However lxd-images returns a KeyError: 'metadata'.
I modified lxd-images to get more information and tried again.

```
vagrant@ubuntu-1404:~/go/src/github.com/lxc/lxd$ g diff
diff --git a/scripts/lxd-images b/scripts/lxd-images
index 2bed457..fcdb662 100755
--- a/scripts/lxd-images
+++ b/scripts/lxd-images
@@ -86,6 +86,8 @@ class LXD(object):
     def aliases_list(self):
         status, data = self.rest_call("/1.0/images/aliases")

+        print("aliases_list")
+        print(data)
         return [alias.split("/1.0/images/aliases/")[-1]
                 for alias in data['metadata']]
```

With this modification, I got the following error.

```
vagrant@ubuntu-1404:~/go/src/github.com/lxc/lxd$ scripts/lxd-images import lxc ubuntu trusty amd64 --alias ubuntu --alias ubuntu/trusty --alias ubuntu/trusty/amd64
Downloading the GPG key for https://images.linuxcontainers.org
Downloading the image list for https://images.linuxcontainers.org
Validating the GPG signature of /tmp/tmp2886fyp9/index.json.asc
aliases_list
{'error_code': 404, 'error': 'not found', 'type': 'error'}
Traceback (most recent call last):
  File "scripts/lxd-images", line 394, in <module>
    args.func(parser, args)
  File "scripts/lxd-images", line 347, in import_lxc
    print(lxd.aliases_list())
  File "scripts/lxd-images", line 92, in aliases_list
    for alias in data['metadata']]
KeyError: 'metadata'
```

So it seems that https://images.linuxcontainers.org/1.0/images/aliases does not exist.
I opened https://images.linuxcontainers.org/ with my browser, and found only `images` and `meta` exists, and `1.0` does not exist.

Could you tell me how to fix this?
Thanks!

**Comment by stgraber** [comment]
The error you're getting is about your local LXD not having the /1.0/images/aliases endpoint which suggests that your running daemon is pre-0.2.

Can you restart lxd passing --debug and then look for any error in the log output?

I'd also recommend rebuilding lxd to make sure you're actually running 0.2.

**Comment by hnakamur** [comment]
@stgraber You are right. I was running pre-0.2 lxd.

Running `make` at https://github.com/lxc/lxd#building-the-tools, calls `go install -v ./...`
which installs `lxd` to `$GOPATH/bin`.

Running `./lxd/lxd` at https://github.com/lxc/lxd#machine-setup, I was running the old `lxd`.
Maybe we should change `./lxd/lxd` to `$GOPATH/bin/lxd` ?

Now `scripts/lxd-images import lxc ubuntu trusty amd64 --alias ubuntu --alias ubuntu/trusty --alias ubuntu/trusty/amd6` works successfully.
Thanks for your help!

**Comment by stgraber** [comment]
Glad to here it works now. Tycho updated the README to match reality :)

**Comment by hnakamur** [comment]
Thanks for updating README!
I will try again with `sudo -E $GOPATH/bin/lxd --group admin`
