### ISSUE TITLE
Feature request :

### ISSUE THREAD

**Issue by geodb27** [lxc/lxd#2940]
Hi ! 
Unless I did not read my screen and the results given by the REST API correctly when querying the properties of a container, it doesn't report all that is filled in the metadata.yaml file associated to a container.
For example, all I can see when querying a/1.0/containers/container-name is :
"metadata": {
    "architecture": "x86_64"

whilst there are some other informations in the metadata.yaml file that could be interresting : 
properties:
    architecture: "x86_64"
    description: "Ubuntu 16.04 LTS server (20161205)"
    os: "ubuntu"
    release: "xenial"

Could it be possible to add these informations in the dict returned by ?

**Comment by stgraber** [comment]
Right, we don't have an API to read/write metadata.yaml, that's what #2823 is for.
