### ISSUE TITLE
Validate device type for unix-char/unix-block when path is set

### ISSUE THREAD

**Issue by moriczp** [lxc/lxd#2941]
Host and container both Ubuntu 16.04.2 LTS
lxc info:
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-64-generic
  server: lxd
  serverpid: 2319
  serverversion: 2.0.9
  storage: btrfs
  storageversion: "4.4"

# Issue description
dd if=/dev/zero of=/dev/shm/ram_disk bs=1k count=4096
losetup /dev/loop0 /dev/shm/ram_disk
   losetup: /dev/shm/ram_disk: failed to set up loop device: Inappropriate ioctl for device

# Steps to reproduce
lxc launch ubuntu:16.04 u164
lxc stop u164
lxc config device add u164 loop-control unix-char path=/dev/loop-control
lxc config device add u164 loop0 unix-char path=/dev/loop0
lxc config device add u164 loop1 unix-char path=/dev/loop1
lxc config edit u164
  raw.lxc: " lxc.cap.drop = \nlxc.cap.drop = sys_time sys_module mac_admin mac_override \n"
  security.privileged: "true"
lxc start u164
lxc exec u164 -- /bin/bash
dd if=/dev/zero of=/dev/shm/ram_disk bs=1k count=4096
export LOOPDEV_DEBUG=all
losetup /dev/loop0 /dev/shm/ram_disk
723: loopdev:      CXT: [0x7fffffffe390]: initialize context
723: loopdev:      CXT: [0x7fffffffe390]: init: ignore ioctls
723: loopdev:      CXT: [0x7fffffffe390]: init: loop-control detected
723: loopdev:      CXT: [0x7fffffffe390]: /dev/loop0 name assigned
723: loopdev:      CXT: [0x7fffffffe390]: add_device 0
723: loopdev:      CXT: [0x7fffffffe390]: add_device done [rc=-1]
723: loopdev:      CXT: [0x7fffffffe390]: set backing file=/dev/shm/ram_disk
723: loopdev:    SETUP: [0x7fffffffe390]: device setup requested
723: loopdev:    SETUP: [0x7fffffffe390]: backing file open: OK
723: loopdev:      CXT: [0x7fffffffe390]: open /dev/loop0 [rw]: Success
723: loopdev:    SETUP: [0x7fffffffe390]: device open: OK
723: loopdev:    SETUP: [0x7fffffffe390]: LOOP_SET_FD failed: Inappropriate ioctl for device
723: loopdev:    SETUP: [0x7fffffffe390]: failed [rc=-25]
losetup: /dev/shm/ram_disk: failed to set up loop device: Inappropriate ioctl for device
723: loopdev:      CXT: [0x7fffffffe390]: de-initialize
723: loopdev:      CXT: [0x7fffffffe390]: closing old open fd
723: loopdev:     ITER: [0x7fffffffe548]: de-initialize

# Information to attach
I checked the source of losetup and loop device in kernel, but I can not find, where it is give back ENOTTY error code.

[losetup]: util-linux-2.27.1/lib/loopdev.c
	loopcxt_setup_device()
[kernel]: linux-4.4.0/drivers/block/loop.c: 
	lo_ioctl():	
		case LOOP_SET_FD:
			loop_set_fd()

**Comment by stgraber** [comment]
lxc config device add u164 loop0 unix-char path=/dev/loop0
    lxc config device add u164 loop1 unix-char path=/dev/loop1

Those are wrong, you want unix-block for block devices

**Comment by stgraber** [comment]
We probably should add a check in LXD in this case since when path= is set, it can check that the type matches and fail if it doesn't.

**Comment by moriczp** [comment]
Hi Stéphane,

That was my copy-paste fault. With "type: unix-block" all fine.
Thank you.
