### ISSUE TITLE
[feature request] Ability to export/import container configuration

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#2954]
It would be great if a container's configuration can be exported (eg. next to its rootfs directory) and that configuration can be imported.

Why?
It would make backup softwares` job much easier.
Currently (AFAIK) there is no way to restore a container on a different host easily. Data can be transferred (eg. with rsync or zfs/btrfs send) but the configuration at the very most can only be restored manually by analyzing 'lxc info' output.
It also would be great if it covers non-container specific details like the lxd uid:gid and if there is a tool available that can be used to shift uids/gids accordingly at restore time.

In addition it also would be useful in cases when something wrong happened with the configuration, like when an package upgraded is failed and container's configuration has to be recreated from scratch. To be on the safe side.

**Comment by stgraber** [comment]
We have that already. A .yaml file is generated in the container path and can be imported with the "lxd import" command.

**Comment by tomposmiko** [comment]
When is it generated? On every changes? Even if the container's volume is not mounted? I still don't understand, when it is mounted, when not.
Is it backup.yaml?

**Comment by stgraber** [comment]
It's generated on every change when the storage is available or at container start time if not.

**Comment by tomposmiko** [comment]
As for lxc import/export my understanding was that it exports the container as an image (with data content of the container).
So it export/import only the configuration?

**Comment by stgraber** [comment]
Export is automatic. Import is with "lxd import", not "lxc".

**Comment by tomposmiko** [comment]
Right, sorry....it's getting late here.
Thanks.

**Comment by gaetanquentin** [comment]
is there a way to import old containers (without backup.yaml)?

**Comment by stgraber** [comment]
@gaetanquentin if you don't have backup.yaml, your best bet is to create a new container, then replace the created rootfs with your old one.

This will not restore the container configuration though, so you may need to set some of the keys by hand with "lxc edit NAME".

**Comment by gaetanquentin** [comment]
this will get a container with name different from storage name? There is not sqlite method, modifying directly the database?

**Comment by akarelas** [comment]
What is the parameter of lxd import? The help screen of lxd is not very clear or helpful. Should I place my backed-up directory in the storage for lxd import to be able to find it?
