### ISSUE TITLE
lxd warning on creating container (2.9.3)

### ISSUE THREAD

**Issue by FransM** [lxc/lxd#2955]
I noticed this warning  in lxc.log when starting a container 

root@frans-VirtualBox:/var/log/lxd/u1604# cat lxc.log
            lxc 20160225185924.223 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 13230, expected pid 13236.

Not sure why it receivedthat pid, the expected pid is there, the received one isn't

root@frans-VirtualBox:/var/log/lxd/u1604# ps ax | grep init
 2985 ?        Ss     0:00 /sbin/init
 3167 ?        S      0:00 /usr/lib/x86_64-linux-gnu/libexec/kf5/start_kdeinit --kded +kcminit_startup
 3169 ?        Ss     0:00 kdeinit5: Running...
 3248 ?        Sl     0:00 klauncher [kdeinit5] --fd=9
 3295 ?        Sl     0:10 kded5 [kdeinit5]
 4200 ?        Ss     0:00 /sbin/init
13236 ?        Ss     0:00 /sbin/init
13844 ?        S      0:00 /bin/sh /etc/init.d/ondemand background
14110 pts/5    S+     0:00 grep --color=auto init

root@frans-VirtualBox:/var/log/lxd/u1604# lxc --version
2.9.3

host is also 16.04 under virtualbox.

**Comment by brauner** [comment]
Afaict, this is perfectly in order. It's a protection mechanism employed by liblxc to guard against SIGCHLD being sent from a process that is not the container's init during startup.

**Comment by FransM** [comment]
Hm, I think this is confusing. The text WARN combined with invalid pid easily puts people on the wrong foot thinking something might be wrong or misconfigured.

A possible change could be to change WARN into NOTICE or so or maybe eliminate the message altogether.

**Comment by brauner** [comment]
@FransM, yes, we discussed this yesterday. Thanks!

**Comment by brauner** [comment]
Addressed in https://github.com/lxc/lxc/pull/1445.
