### ISSUE TITLE
LXD v2.9.3 won't properly initialize existing ZFS datapool

### ISSUE THREAD

**Issue by audiocricket** [lxc/lxd#2958]
Hi,

seems like the latest LXD v2.9.3 on stock 16.04.2 won't properly initialize ZFS datapool. When doing lxd init and using existing ZFS datapool, we always get this error:

`Would you like to create a new network bridge (yes/no) [default=yes]? no
error: Failed to create ZFS filesystem: mount: mount(2) failed: No such file or directory
cannot mount 'testpool/lxd/containers': No such device or address
filesystem successfully created, but not mounted`

I have workarounded this by manually creating zfs sub-datasets under the testpool/lxd dataset like this (before lxd init):

`for i in deleted containers custom images; do zfs create testpool/lxd/$i -o mountpoint=/var/lib/lxd/$i; done`

Afterwards when I run lxd init and use existing testpool/lxd dataset, this time it will initialize correctly and is ready to run and launching containers seems to work at the moment.

How can I help you fix this? Many thanks!

**Comment by audiocricket** [comment]
I have probably forgot to mention it, but that dedicated datapool is for LXD only and is empty when doing zfs init.

Do you have any clue what could be causing this? This doesn't happen using v2.8 ...

Thanks!

**Comment by brauner** [comment]
Hm, can't really reproduce this problem locally. Can you show me the output of `zfs list -t all`?

**Comment by brauner** [comment]
Also, are you using an existing dataset as pool (e.g. `tank/vol1`) or a whole existing pool (e.g. `tank`)?

**Comment by brauner** [comment]
This is `lxd init` using an existing zpool `pool2`:
[![asciicast](https://asciinema.org/a/104684.png)](https://asciinema.org/a/104684)

This is `lxd init` using an existing dataset `pool2/vol2`:
[![asciicast](https://asciinema.org/a/104685.png)](https://asciinema.org/a/104685)

**Comment by audiocricket** [comment]
It's sub-dataset under a parent dataset **testpool**, which is both shared between Docker (it has testpool/docker dataset) and LXD on the same machine. No problems at all on v2.8, Docker and LXD perfectly coexisted there until upgrade to v2.9.3, so there must be some change causing this. On v2.8, either using dataset **testpool** or **testpool/lxd** it works just fine.

<pre>
root@finaltest-ubuntu:~# zfs list -t all
NAME                                                                                                     USED  AVAIL  REFER  MOUNTPOINT
testpool                                                                                               8.38G  11.8G    40K  /testpool
testpool/docker                                                                                         374M  11.8G  12.0M  /var/lib/docker
testpool/docker/0b54701688f28d024776d5fdfb58aecca7c1c2560e7b119c9522d0a46bf2304c                        137M  11.8G   136M  legacy
testpool/docker/0b54701688f28d024776d5fdfb58aecca7c1c2560e7b119c9522d0a46bf2304c@230988306             1.29M      -   136M  -
testpool/docker/1969eafc5da5a9348407856a7d068045f01f5bbab142ba7f6f721b606b9fd50a                       45.4M  11.8G   179M  legacy
testpool/docker/1969eafc5da5a9348407856a7d068045f01f5bbab142ba7f6f721b606b9fd50a@439515542              166K      -   179M  -
testpool/docker/24ba85380f4953abf48478842b6995aa1c16a70cf26b124670812a79f771f1ef                        552K  11.8G   218M  legacy
testpool/docker/24ba85380f4953abf48478842b6995aa1c16a70cf26b124670812a79f771f1ef@651193083               31K      -   218M  -
testpool/docker/26d43c2e3d0bb785bd867b5bb599d8b6dfbc0432b7e74e311115d962a026bffe                         31K  11.8G   348M  legacy
testpool/docker/30d03c384b6f3d30ab68959a040f8efa2710fbcd2801d69dc2e9229b96493ef0                       31.5K  1024M  4.29M  legacy
testpool/docker/30d03c384b6f3d30ab68959a040f8efa2710fbcd2801d69dc2e9229b96493ef0-init                    28K  1024M  4.29M  legacy
testpool/docker/30d03c384b6f3d30ab68959a040f8efa2710fbcd2801d69dc2e9229b96493ef0-init@473599918            0      -  4.29M  -
testpool/docker/4c9a44e236867b5d9b8699e671fdccc53605e91bbb25d8c12d8d92136d391240                         82K  11.8G   220M  legacy
testpool/docker/4c9a44e236867b5d9b8699e671fdccc53605e91bbb25d8c12d8d92136d391240@822378919               26K      -   220M  -
testpool/docker/5397c3c90f62ed4154b04e350afcf1a5af4da24c4811a76e0319cc274db53e45                       2.70M  11.8G   220M  legacy
testpool/docker/5397c3c90f62ed4154b04e350afcf1a5af4da24c4811a76e0319cc274db53e45@321227897               31K      -   220M  -
testpool/docker/63631ea5a6a2c6368c6e5e2417e487e160bc69ebebfb25c1c3a875eeb333417d                       39.1M  11.8G   218M  legacy
testpool/docker/63631ea5a6a2c6368c6e5e2417e487e160bc69ebebfb25c1c3a875eeb333417d@124367543              588K      -   218M  -
testpool/docker/af66826a8aa157ebc27d637d801da28261f7df7f3822a235567e75da4ccab82a                       4.29M  11.8G  4.29M  legacy
testpool/docker/af66826a8aa157ebc27d637d801da28261f7df7f3822a235567e75da4ccab82a@814462152                 0      -  4.29M  -
testpool/docker/ce6dcf0ec1841c851fdd19dcda5d2cbcc748e8cb57f56fb8b1ff6e4193b994d6                        132M  11.8G   348M  legacy
testpool/docker/ce6dcf0ec1841c851fdd19dcda5d2cbcc748e8cb57f56fb8b1ff6e4193b994d6@926339297             3.05M      -   348M  -
testpool/docker/d307b457bc53fbdfe59cedfe550f3f1015994924c41f1b81e19ed4f9eb361392                        101K  11.8G   348M  legacy
testpool/docker/d307b457bc53fbdfe59cedfe550f3f1015994924c41f1b81e19ed4f9eb361392@192348497               27K      -   348M  -
testpool/docker/e436b176a2c580a891ca6515b83334a0c6bea6e99bf50970f369e46892613987                        178K  11.8G   180M  legacy
testpool/docker/e436b176a2c580a891ca6515b83334a0c6bea6e99bf50970f369e46892613987@218086432               32K      -   180M  -
testpool/docker/e734fc4636e687ac547847397bbfbe9dd4d0abd083435b8a15a5a5d7a7317d74                        556K  11.8G   180M  legacy
testpool/docker/e734fc4636e687ac547847397bbfbe9dd4d0abd083435b8a15a5a5d7a7317d74@749050931               31K      -   180M  -
testpool/lxd                                                                                           7.03G  11.8G    19K  /testpool/lxd
testpool/lxd/containers                                                                                 213M  11.8G    19K  none
testpool/lxd/containers/a15495cb2ed229d6                                                                609K  1023M  8.04M  /var/lib/lxd/storage-pools/default/containers/a15495cb2ed229d6
testpool/lxd/containers/b456c7f862346192                                                               34.6M   989M  1.23G  /var/lib/lxd/storage-pools/default/containers/b456c7f862346192
testpool/lxd/containers/bbb47409882fbae6                                                               1.86M  1022M   374M  /var/lib/lxd/storage-pools/default/containers/bbb47409882fbae6
testpool/lxd/containers/bc8371bf00eb8084                                                               15.7M  1008M   306M  /var/lib/lxd/storage-pools/default/containers/bc8371bf00eb8084
testpool/lxd/containers/cee537a69183dd13                                                               8.27M  1016M   418M  /var/lib/lxd/storage-pools/default/containers/cee537a69183dd13
testpool/lxd/containers/cf9195bd92ca12a7                                                               16.6M  1007M   457M  /var/lib/lxd/storage-pools/default/containers/cf9195bd92ca12a7
testpool/lxd/containers/d8196b861e3ce0ef                                                               8.23M  1016M   673M  /var/lib/lxd/storage-pools/default/containers/d8196b861e3ce0ef
testpool/lxd/containers/e2dc402853874e8b                                                                610K  1023M  8.04M  /var/lib/lxd/storage-pools/default/containers/e2dc402853874e8b
testpool/lxd/containers/e4c5a8a7b5aeb0f5                                                               12.1M  1012M   252M  /var/lib/lxd/storage-pools/default/containers/e4c5a8a7b5aeb0f5
testpool/lxd/containers/f84bcd0fd691403c                                                               1.80M  1022M   390M  /var/lib/lxd/storage-pools/default/containers/f84bcd0fd691403c
testpool/lxd/containers/f9337c7b26e44a0d                                                                112M   912M   613M  /var/lib/lxd/storage-pools/default/containers/f9337c7b26e44a0d
testpool/lxd/custom                                                                                      19K  11.8G    19K  none
testpool/lxd/deleted                                                                                   2.32G  11.8G    19K  none
testpool/lxd/deleted/images                                                                            2.32G  11.8G    19K  none
testpool/lxd/deleted/images/3afd8ae3e68a1af8bdcc67b719533095e1fda4c48437d393985422f069b13484            390M  11.8G   390M  none
testpool/lxd/deleted/images/3afd8ae3e68a1af8bdcc67b719533095e1fda4c48437d393985422f069b13484@readonly      0      -   390M  -
testpool/lxd/deleted/images/44f04a0afed786a88d2a3c4f9a545850237be527ceecf7fd8ed5f163b35fbbd1            373M  11.8G   373M  none
testpool/lxd/deleted/images/44f04a0afed786a88d2a3c4f9a545850237be527ceecf7fd8ed5f163b35fbbd1@readonly      0      -   373M  -
testpool/lxd/deleted/images/559f47f1d5dcf50f6d398d77c100a89077837459deb388f341d3f1464da5350e            420M  11.8G   420M  none
testpool/lxd/deleted/images/559f47f1d5dcf50f6d398d77c100a89077837459deb388f341d3f1464da5350e@readonly      0      -   420M  -
testpool/lxd/deleted/images/967740d48b4bf5abac83394850fe9e49b6559463c909908184f2620e8f478687            442M  11.8G   442M  none
testpool/lxd/deleted/images/967740d48b4bf5abac83394850fe9e49b6559463c909908184f2620e8f478687@readonly      0      -   442M  -
testpool/lxd/deleted/images/9cd6e728f7f8e530f1e20daca863f23b46f4324d1ac8c3a114e0bdaa10d38978            503M  11.8G   503M  none
testpool/lxd/deleted/images/9cd6e728f7f8e530f1e20daca863f23b46f4324d1ac8c3a114e0bdaa10d38978@readonly      0      -   503M  -
testpool/lxd/deleted/images/d056035475f1f876ca4ce227b0b55308770a07c21696db87271804f00424ca09            244M  11.8G   244M  none
testpool/lxd/deleted/images/d056035475f1f876ca4ce227b0b55308770a07c21696db87271804f00424ca09@readonly      0      -   244M  -
testpool/lxd/images                                                                                    4.51G  11.8G    19K  none
testpool/lxd/images/3e4d9bea32dc885755d597ae6d2346ae59910062866b488c6b5291673138a9a7                    292M  11.8G   292M  none
testpool/lxd/images/3e4d9bea32dc885755d597ae6d2346ae59910062866b488c6b5291673138a9a7@readonly              0      -   292M  -
testpool/lxd/images/47defcd671d700576a3b9e93cd072b71a0e008b0aa38ad010ed21be76311a153                    442M  11.8G   442M  none
testpool/lxd/images/47defcd671d700576a3b9e93cd072b71a0e008b0aa38ad010ed21be76311a153@readonly              0      -   442M  -
testpool/lxd/images/6b47cb531e65ba5a182a5842bd18bff94d8f67f923ebc95006c7a8aadc203cdd                    675M  11.8G   675M  none
testpool/lxd/images/6b47cb531e65ba5a182a5842bd18bff94d8f67f923ebc95006c7a8aadc203cdd@readonly              0      -   675M  -
testpool/lxd/images/7445ff338e464f4a359dacef9264146b617df172be652202ec6fbbfb1aa6489b                   7.52M  11.8G  7.52M  none
testpool/lxd/images/7445ff338e464f4a359dacef9264146b617df172be652202ec6fbbfb1aa6489b@readonly              0      -  7.52M  -
testpool/lxd/images/749146bc245146f3d4639dd6a7303654dfc2a8c44f3120ae7a1697773eb3d7ba                   1.23G  11.8G  1.23G  none
testpool/lxd/images/749146bc245146f3d4639dd6a7303654dfc2a8c44f3120ae7a1697773eb3d7ba@readonly              0      -  1.23G  -
testpool/lxd/images/9ec561e79ead1a830381471b4504f325f948b5f752c8d2f5631c7857935d101d                    244M  11.8G   244M  none
testpool/lxd/images/9ec561e79ead1a830381471b4504f325f948b5f752c8d2f5631c7857935d101d@readonly              0      -   244M  -
testpool/lxd/images/c16dcf4e08e3d5740947dae8c5baf6acd3615e333743b0338b4889284b86916c                   7.62M  11.8G  7.62M  none
testpool/lxd/images/c16dcf4e08e3d5740947dae8c5baf6acd3615e333743b0338b4889284b86916c@readonly              0      -  7.62M  -
testpool/lxd/images/cd14831d8d6d7bed4960e77b21ca550e5d7b5c5f2f0fc4724ea2e4230fa80c83                    390M  11.8G   390M  none
testpool/lxd/images/cd14831d8d6d7bed4960e77b21ca550e5d7b5c5f2f0fc4724ea2e4230fa80c83@readonly              0      -   390M  -
testpool/lxd/images/e7e41e747d9d19bae6cfbec0fcdf04721d90bdcc8abcaa0cc9e7612fcd7be486                    373M  11.8G   373M  none
testpool/lxd/images/e7e41e747d9d19bae6cfbec0fcdf04721d90bdcc8abcaa0cc9e7612fcd7be486@readonly              0      -   373M  -
testpool/lxd/images/eccdd40cf2ca2c2311107ef4e19798da1ece96ac798a6561f28326fb6bb8860d                    420M  11.8G   420M  none
testpool/lxd/images/eccdd40cf2ca2c2311107ef4e19798da1ece96ac798a6561f28326fb6bb8860d@readonly              0      -   420M  -
testpool/lxd/images/fcdfa6b9f6a8bcf5d2eeae6725b6e99579b03dc6e239deab7bb6d9994849aabd                    503M  11.8G   503M  none
testpool/lxd/images/fcdfa6b9f6a8bcf5d2eeae6725b6e99579b03dc6e239deab7bb6d9994849aabd@readonly              0      -   503M  -
testpool/lxdvar                                                                                        1001M  11.8G  1001M  /var/lib/lxd
testpool/snapshots                                                                                     2.85M  11.8G  2.85M  /testpool/snapshots
</pre>

**Comment by audiocricket** [comment]
Also, in the /var/lib/lxd/lxd.log there is roughly the same as I've posted in the first comment ...

**Comment by brauner** [comment]
Wait, previously you said

> I have probably forgot to mention it, but that dedicated datapool is for LXD only and is empty when doing lxd init.

but then you showed a fully populated zfs dataset. So what exactly are you saying? Is the zfs dataset `testpool/lxd` empty by the time you run `lxd init` or not? :)

**Comment by audiocricket** [comment]
Aha, okay, we misunderstood a little bit ;) I've written in the first post of this issue that I've workarounded it by manually creating the sub-datasets needed for lxd with respective mountpoints. So actually before that workaround and lxd init (I've pasted after the workaround, sorry), the zfs dataset would be populated only by docker, but I don't see any problem there - this works perfectly fine under v2.8, no matter if the dataset is empty, or use by docker, etc.

**Comment by brauner** [comment]
Ah, thanks. Can you give me the exact commands you used to create the initial zpool and datasets that you have LXD use.

**Comment by brauner** [comment]
The error message you posted is weird, since `testpool/lxd/containers` should never have a mountpoint property set in the first place. So the fact that zfs is trying to mount it seems weird.

Can you also show me the output of:
- `lxc storage show <pool-name>` (The name of your pool as LXD stores it in the db can be gathered from `lxc storage list`.)

**Comment by audiocricket** [comment]
Here you are, nothing strange here:

<pre>
zpool create -f testpool /dev/vda1
zfs set compression=off testpool
zfs set dedup=off testpool
zfs set sync=disabled testpool
zfs set primarycache=none testpool
zfs create testpool/docker -o mountpoint=/var/lib/docker
zfs create testpool/lxdvar -o mountpoint=/var/lib/lxd
zfs create testpool/lxd
</pre>

The is exactly the same as it's working on v2.8.

**Comment by audiocricket** [comment]
<pre>
root@finaltest-ubuntu:~# lxc storage list
+---------+--------+---------------+---------+
|  NAME   | DRIVER |    SOURCE     | USED BY |
+---------+--------+---------------+---------+
| default | zfs    | testpool/lxd  | 22      |
+---------+--------+---------------+---------+

root@finaltest-ubuntu:~# lxc storage show default
config:
  source: testpool/lxd
  zfs.pool_name: testpool/lxd
name: default
driver: zfs
used_by:
- /1.0/containers/a15495cb2ed229d6
- /1.0/containers/b456c7f862346192
- /1.0/containers/bbb47409882fbae6
- /1.0/containers/bc8371bf00eb8084
- /1.0/containers/cee537a69183dd13
- /1.0/containers/cf9195bd92ca12a7
- /1.0/containers/d8196b861e3ce0ef
- /1.0/containers/e2dc402853874e8b
- /1.0/containers/e4c5a8a7b5aeb0f5
- /1.0/containers/f84bcd0fd691403c
- /1.0/containers/f9337c7b26e44a0d
- /1.0/images/3e4d9bea32dc885755d597ae6d2346ae59910062866b488c6b5291673138a9a7
- /1.0/images/47defcd671d700576a3b9e93cd072b71a0e008b0aa38ad010ed21be76311a153
- /1.0/images/6b47cb531e65ba5a182a5842bd18bff94d8f67f923ebc95006c7a8aadc203cdd
- /1.0/images/7445ff338e464f4a359dacef9264146b617df172be652202ec6fbbfb1aa6489b
- /1.0/images/749146bc245146f3d4639dd6a7303654dfc2a8c44f3120ae7a1697773eb3d7ba
- /1.0/images/9ec561e79ead1a830381471b4504f325f948b5f752c8d2f5631c7857935d101d
- /1.0/images/c16dcf4e08e3d5740947dae8c5baf6acd3615e333743b0338b4889284b86916c
- /1.0/images/cd14831d8d6d7bed4960e77b21ca550e5d7b5c5f2f0fc4724ea2e4230fa80c83
- /1.0/images/e7e41e747d9d19bae6cfbec0fcdf04721d90bdcc8abcaa0cc9e7612fcd7be486
- /1.0/images/eccdd40cf2ca2c2311107ef4e19798da1ece96ac798a6561f28326fb6bb8860d
- /1.0/images/fcdfa6b9f6a8bcf5d2eeae6725b6e99579b03dc6e239deab7bb6d9994849aabd
</pre>

**Comment by audiocricket** [comment]
But this is after the workaround, so not sure if you need it.

**Comment by brauner** [comment]
I can't reproduce. Works totally fine here with the commands you gave me on all `LXD 2.9.3` versions.

**Comment by audiocricket** [comment]
Thanks very much, I will try to strace and catch that strange error zfs message. Will report back then.

**Comment by brauner** [comment]
@audiocricket, just so that you know what exactly I did to reproduce this:

[![asciicast](https://asciinema.org/a/104687.png)](https://asciinema.org/a/104687)

**Comment by brauner** [comment]
So one option I can think of is that you unmount the pool or dataset and then when LXD tries to remount the pool/dataset, the `/var/lib/lxd` directory is already populated due to the daemon start and so the pool/dataset will refuse the mount.

**Comment by brauner** [comment]
Any luck in getting this to work or are you still running into this issue?

**Comment by audiocricket** [comment]
Will most probably check this over weekend or past weekend.

**Comment by brauner** [comment]
Cool, no rush. I was just interested. :)

**Comment by audiocricket** [comment]
We can probably close this issue, since it's not happening anymore with latest LXD v2.11 and ZFSonLinux 0.6.5.9. Will reopen/create new issue shall it happen again. Thanks!

**Comment by stgraber** [comment]
Good to hear!
