### ISSUE TITLE
LXD should remove an unused UNIX socket if found

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#296]
Currently LXD binds /var/lib/lxd/unix.socket on startup. If the socket already exists, the bind call fails and LXD fails to start.

That's usually a reasonable behavior, except for the case where LXD crashed. In such a case, it won't get around to removing the socket and so the next startup will fail. Making LXD auto-restart on crash by init systems useless.

What we should implement is:
 - Check if the socket exists
 - If it doesn't, bind as usual
 - If it does, then
   - Attempt to connect to it
   - If that connect succeeds, then fail LXD's start saying that the socket is in use
   - If that connect fails, then remove the socket and continue with binding as usual

**Comment by tych0** [comment]
On Sun, Mar 01, 2015 at 08:47:51PM -0800, St�phane Graber wrote:
> Currently LXD binds /var/lib/lxd/unix.socket on startup. If the socket already exists, the bind call fails and LXD fails to start.
> 
> That's usually a reasonable behavior, except for the case where LXD crashed. In such a case, it won't get around to removing the socket and so the next startup will fail. Making LXD auto-restart on crash by init systems useless.
> 
> What we should implement is:
>  - Check if the socket exists
>  - If it doesn't, bind as usual
>  - If it does, then
>    - Attempt to connect to it
>    - If that connect succeeds, then fail LXD's start saying that the socket is in use
>    - If that connect fails, then remove the socket and continue with binding as usual

+1, I'll do this today since it's annoying :)
