### ISSUE TITLE
symlinks with file push

### ISSUE THREAD

**Issue by sigmonsays** [lxc/lxd#2970]
# Required information

 * Distribution: trusty
 * Distribution version: 14.04.2
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 2.0.0~rc5-0ubuntu1~ubuntu14.04.1~ppa1
   * LXD version: 2.8
   * Storage backend in use: directory

# Issue description

pushing files which are symlinks do not seem behave correct

# Steps to reproduce

1. create this directory structure
```
mkdir junk junk2
date > junk2/test.txt
cd junk
ln -s ../junk2 test
cd $HOME

$ tree junk*
junk
└── test -> ../junk2
junk2
└── test.txt
```

2. run file push
```
$ lxc file push -p -r ./junk pytest/root/
error: Post http://unix.socket/1.0/containers/pytest/files?path=%2Froot%2Fjunk%2Ftest: read junk/test: is a directory
$ cd junk/test
$ ls -l
total 4
-rw-r--r-- 1 sig users 29 Feb 27 15:10 test.txt
```

# Expected Results

I would expect a position on how symlinks are handled. There does not seem to be any documentation in the **lxc file push -h** output talking about special file handling. I'm not aware of any other documentation either.

There are a bunch of different ways to handle this case besides returning an error, simplest being ignoring symlinks. More complicated solutions could be resolving symlinks and copying the regular files or just copying the symlink as is and leave it dangling in the container.

**Comment by stgraber** [comment]
I think we should return an error when doing recursive push and noticing a symlink.
