### ISSUE TITLE
Add a LXD driver to docker-machine 

### ISSUE THREAD

**Issue by gebi** [lxc/lxd#2977]
Hi,

Please provide a docker-machine driver for LXD.

eg. like https://github.com/scaleway/docker-machine-driver-scaleway
or https://github.com/dhiltgen/docker-machine-kvm

It would eg. make it much easier to use lxd for gitlab as a build slave (gitlab-ci-runner).

**Comment by stgraber** [comment]
I don't think anyone on the core LXD team has time or interest in doing this work.
Maybe someone from the community will have some interest in contributing this to the relevant upstream.

**Comment by jgillich** [comment]
@gebi Are you sure you want this? docker-machine still runs actual Docker on the target platform, it's not a generic way to run Docker containers. So you would be running Docker inside LXD..I really don't see the benefit of that.

**Comment by gebi** [comment]
@jgillich yes im sure about that, because it seems like the only possibility currently to build docker container on a machine without compromising the host.

eg. gitlab's ci runner already has support for docker-machine and could then use this backend to let a docker daemon run inside an lxd container which is reset after every build job.

**Comment by BrendanBall** [comment]
I'll add another use case for this. see https://github.com/kubernetes/minikube/issues/946.
To run a local kubernetes cluster for development currently you have to use a VM that is supported by docker-machine. If docker-machine supports LXD then it would supposedly be easy to add support to minikube to use LXD instead of a VM.

**Comment by techtonik** [comment]
I am going to invest some time in this and maybe I even found a sponsor, who is interested in k8s.  =)

**Comment by luisfaceira** [comment]
@techtonik have you had the opportunity to work on this? Have you made any significant progress?

I'm really interested in kubernetes/minikube#946 , after years of developing locally with LXC containers, seems like a step back to go into full VMs with minikube.

**Comment by jfgibbins** [comment]
not sure if this helps for your particular situation, but docker-machine supports lxd containers using the generic driver, example below is what I use for my environment, and only requires a running container, which in my environment is created with terraform.  It even handles installing the current version of docker engine on it.

docker-machine create --driver generic  --generic-ssh-user "user" --generic-ip-address x.x.x.x *container*

**Comment by Remigius2011** [comment]
@jfgibbins This sounds excellent! Could you share the terraform script you use for this? Is the lxd container running in privileged od unprivileged mode?

**Comment by jfgibbins** [comment]
I'm currently rewriting my terraform module for docker at this very moment.  Debating on whether to run as a local exec command that executes the above on each interation, or running an independent script that does all the work, calling terraform to just create the containers for me.  I will probably do the latter, as I want to be able to set env variables to automate the entire process, including the new version of swarm, aka 1.12+.  I'll update this when I work through it.  My docker containers are running unprivileged.  Also FYI, reference #3721.

**Comment by Remigius2011** [comment]
@jfgibbins I am currently working on a combo of terraform and ansible to configure docker clusters on metal and in cloud and a talk on BaselOne in October (all to be published). I don't use docker-machine, though. I'm also interested in newer upstream docker versions (certainly 1.13+, preferrably 2017.x), but they (seem to) require lxd containers in privileged mode, which I'd like to avoid. Unfortunately the information on the future of running docker on lxd in unprivileged mode provided by the creators of lxd is somewhat sparse. ubuntu provides docker.io packages that seem to run in unprivileged mode, but only up to 1.12.x - currently 1.12.6 even for artful. And sorry, I can't find #3721 (yet)

**Comment by jfgibbins** [comment]
@Remigius2011 I'm currently running mine using docker 1.13, with security.nesting = true, security.privileged = false, but in order to use network overlays, I added #3712, sorry, transposed numbers on previous message.  My environment is basically docker-machine and docker on host, create containers with terrraform, and use docker-machine to add the containers and install docker 1.13 using the command "docker-machine create --driver generic --generic-ssh-user "user" --generic-ip-address x.x.x.x container" and then docker swarm to add everything together.  For an existing environment, I would probably put into the terraform local-execs to remove old nodes destroyed, add nodes created, and add as worker to swarm.  My particular use is to recreate an environment from scratch, so debating the order I do things in, ie; terraform builds and handles automation, or automation calls terraform to build the containers I need.

**Comment by jfgibbins** [comment]
@Remigius2011 My only issue I'm stuck on right now, to automate the whole setup is how to get the value of count in terraform.  I want the resource count value, not the index which is all I can find reference to.  I script the writing of my .tf files with excel as my initial source of info.  excel -> csv -> php -> .tf, so I may just set what I need based on count in php to write the .tf file.

**Comment by adomenech73** [comment]
@jfgibbins When I try to use lxd containers with generic drivers I've got this:

```Bash
Sep 14 17:48:29 node-01 systemd-sysctl[37]: Couldn't write '4 4 1 7' to 'kernel/printk', ignoring: Permission denied
Sep 14 17:48:29 node-01 systemd-sysctl[37]: Couldn't write '1' to 'kernel/kptr_restrict', ignoring: Permission denied
Sep 14 17:48:29 node-01 systemd-sysctl[37]: Couldn't write '1' to 'kernel/yama/ptrace_scope', ignoring: Permission denied
Sep 14 17:48:29 node-01 systemd-sysctl[37]: Couldn't write '1' to 'fs/protected_symlinks', ignoring: Permission denied
Sep 14 17:48:29 node-01 systemd-sysctl[37]: Couldn't write '1' to 'fs/protected_hardlinks', ignoring: Permission denied
Sep 14 17:48:29 node-01 systemd-sysctl[37]: Couldn't write '65536' to 'vm/mmap_min_addr', ignoring: Permission denied
Sep 14 17:48:29 node-01 systemd-sysctl[37]: Couldn't write '176' to 'kernel/sysrq', ignoring: Permission denied
Sep 14 17:48:29 node-01 systemd[1]: Started udev Kernel Device Manager.
Sep 14 17:48:29 node-01 systemd[1]: dev-hugepages.mount: Mount process exited, code=exited status=32
Sep 14 17:48:29 node-01 systemd[1]: Failed to mount Huge Pages File System.
Sep 14 17:48:29 node-01 systemd[1]: dev-hugepages.mount: Unit entered failed state.
Sep 14 17:48:29 node-01 systemd-journald[39]: Forwarding to syslog missed 1 messages.
Sep 14 17:48:29 node-01 systemd[1]: systemd-sysctl.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 17:48:29 node-01 systemd[1]: Failed to start Apply Kernel Variables.
Sep 14 17:48:29 node-01 systemd[1]: systemd-sysctl.service: Unit entered failed state.
Sep 14 17:48:29 node-01 systemd[1]: systemd-sysctl.service: Failed with result 'exit-code'.
Sep 14 17:48:29 node-01 systemd[1]: Started Remount Root and Kernel File Systems.
Sep 14 17:48:29 node-01 systemd[1]: Failed to reset devices.list on /system.slice/systemd-random-seed.service: Operation not permitted
Sep 14 17:48:29 node-01 systemd[1]: Starting Load/Save Random Seed...
Sep 14 17:48:29 node-01 systemd[1]: Failed to reset devices.list on /system.slice/systemd-udev-trigger.service: Operation not permitted
Sep 14 17:48:29 node-01 systemd[1]: Starting udev Coldplug all Devices...
Sep 14 17:48:29 node-01 systemd[1]: Reached target Local File Systems (Pre).
Sep 14 17:48:29 node-01 systemd[1]: Reached target Local File Systems.
Sep 14 17:48:29 node-01 systemd[1]: Failed to reset devices.list on /system.slice/system-getty.slice: Operation not permitted
Sep 14 17:48:29 node-01 systemd[1]: Created slice system-getty.slice.
Sep 14 17:48:29 node-01 systemd[1]: Failed to reset devices.list on /system.slice/systemd-journal-flush.service: Operation not permitted
Sep 14 17:48:29 node-01 systemd[1]: Starting Flush Journal to Persistent Storage...
Sep 14 17:48:29 node-01 systemd[1]: Failed to reset devices.list on /system.slice/systemd-remount-fs.service: Operation not permitted
Sep 14 17:48:29 node-01 systemd[1]: Started Nameserver information manager.
Sep 14 17:48:29 node-01 systemd[1]: Started Load/Save Random Seed.
Sep 14 17:48:29 node-01 systemd[1]: Reached target Network (Pre).
Sep 14 17:48:29 node-01 systemd[1]: Failed to reset devices.list on /system.slice/networking.service: Operation not permitted
Sep 14 17:48:29 node-01 systemd[1]: Starting Raise network interfaces...
```
Any clue how can I go out¿

**Comment by jfgibbins** [comment]
@adomenech73 due to a issues with various aspects, my containers include the following:
config:
  security.nesting: "true"
  security.privileged: "true"

 as well as a empty file in the container /.dockerenv
I'm also currently using ubuntu:zesty, but that's because docker 1.13 swarm with overlays has issues with ubuntu xenial, and yakkety apt sources are limited to 17.06

**Comment by adomenech73** [comment]
Just tested!! works perfectly. Thanks a lot @jfgibbins

**Comment by LawfulHacker** [comment]
Just adding more information...

I tried to create a swarm inside LXD but I was unsuccessful.

To create the swarm I create this script: https://gist.github.com/LawfulHacker/1f95ba8e1cfb566bb4167019c37ba5bd

The swarm runs fine but I was unable to create any service which exposes ports. It shows this error:

    "starting container failed: error creating external connectivity network: cannot restrict inter-container communication: please ensure that br_netfilter kernel module is loaded"

I tracked this error down to [docker/libnetwork](https://github.com/docker/libnetwork/blob/19ac3ea7f52bb46e0eb10669756cdae0c441a5b1/drivers/bridge/setup_bridgenetfiltering.go#L161) and I added the `/.dockerenv` file to the containers. It just stopped the error but the service is not exposed at all.

**Comment by jfgibbins** [comment]
The script looks good.  I assume that docker node ls from the master shows all nodes up and running.  In addition running 'lsmod | grep brnet' in the container shows that you have the bridge filter running.  But I don't see your 'docker service create' or a docker stack deploy compose file, so the problem might be in how you're trying to create the service itself.  If you can share that, at the least, I can run it against my swarm, to check if its the problem or not.

**Comment by LawfulHacker** [comment]
Any service on swarm which exposes a port isn't working.

For example, `docker service create --name web --publish 80:80 nginx` isn't accessible and we can't connect to the swarm.

Also portainer which runs on port 9000 doesn't work, so it isn't a matter of privileged ports.

Below is the full command list.

```
# Swarm appears to be working
root@swarm-manager-1:~# docker node list
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
2p55np4fg10y0groovuag60kl     swarm-worker-15     Ready               Active              
a7es1ftp5fvagowwuih5zfcqr     swarm-worker-16     Ready               Active              
g71vyejw9ztldtuvm38nytfba     swarm-worker-13     Ready               Active              
hsvsgwyqzx3o6c4xlwhf9fh9d     swarm-worker-3      Ready               Active              
imk9ofaz5q3e2ixlb75zs5ol2     swarm-worker-6      Ready               Active              
jj46gl86tcarc63o25gtt5g0p     swarm-worker-18     Ready               Active              
llrndv6cz72kswspgbe94244i     swarm-manager-2     Ready               Active              Reachable
lrjrirojeq2moceezy7awp427     swarm-worker-10     Ready               Active              
lt0gc4dq60an2ws89pvol7uet *   swarm-manager-1     Ready               Active              Leader
oh5p9l9qj3gi2o0adwcglo41d     swarm-worker-1      Ready               Active              
ov60b6n1sjgww894kijl6bvgr     swarm-worker-2      Ready               Active              
qqkcugtl39flqds543ykxdhv9     swarm-worker-4      Ready               Active              
s1inqst73xl93a95ysc1p374v     swarm-worker-11     Ready               Active              
s2ituj5c4t1a9454ryh71re93     swarm-worker-17     Ready               Active              
sg0fgf99r3s5eb3qmj9tnkeu9     swarm-worker-14     Ready               Active              
slm4s1atvslautb4xsp95nec2     swarm-worker-12     Ready               Active              
sm1so0cjb5nj7167xuz7jk05o     swarm-worker-19     Ready               Active              
u8e3bsip4va4ori1yzeey4npv     swarm-worker-8      Ready               Active              
uhq0o60fcipt1ctreb95zsaek     swarm-worker-9      Ready               Active              
v78b7f90een09syy8tycixo4s     swarm-worker-7      Ready               Active              
weeraoqpth6s22oydt1cz28cw     swarm-manager-3     Ready               Active              Reachable
yfdhuwka5tsea0ihaeatctbkp     swarm-worker-5      Ready               Active              
```
Create the service:

```
root@swarm-manager-1:~# docker service create --name web --publish 80:80 nginx
a3dtq3f1peh6ehnyxgeutk42a
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.
root@swarm-manager-1:~# docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
a3dtq3f1peh6        web                 replicated          0/1                 nginx:latest        *:80->80/tcp
root@swarm-manager-1:~# docker service ps web
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE           ERROR               PORTS
u8m9srhde54t        web.1               nginx:latest        swarm-worker-15     Running             Running 6 seconds ago                       
root@swarm-manager-1:~# docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
a3dtq3f1peh6        web                 replicated          1/1                 nginx:latest        *:80->80/tcp
root@swarm-manager-1:~# docker service ps web
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE            ERROR               PORTS
u8m9srhde54t        web.1               nginx:latest        swarm-worker-15     Running             Running 14 seconds ago                       
```

It runs but isn't accessible:

```
root@swarm-manager-1:~# curl localhost
curl: (7) Failed to connect to localhost port 80: Connection refused
root@swarm-manager-1:~# 
```

**Comment by niko-daniel** [comment]
@LawfulHacker try to use -p  "docker service create --name $name -p 80:80 $images", I also get same problem when use --publish.

**My setup**
```
user@ThinkPad-E440:~$ lxc ls
+---------+---------+--------------------------------+------+------------+-----------+
|  NAME   |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
+---------+---------+--------------------------------+------+------------+-----------+
| manager | RUNNING | 172.18.0.1 (docker_gwbridge)   |      | PERSISTENT | 0         |
|         |         | 172.17.0.1 (docker0)           |      |            |           |
|         |         | 10.97.244.46 (eth0)            |      |            |           |
+---------+---------+--------------------------------+------+------------+-----------+
| worker  | RUNNING | 172.18.0.1 (docker_gwbridge)   |      | PERSISTENT | 0         |
|         |         | 172.17.0.1 (docker0)           |      |            |           |
|         |         | 10.97.244.160 (eth0)           |      |            |           |
+---------+---------+--------------------------------+------+------------+-----------+
```
**Swarm service**
```
root@manager:~# docker service list
ID                  NAME                MODE                REPLICAS            IMAGE                      PORTS
6u3ed2e1mtpm        web                 replicated          2/2                 tutum/hello-world:latest   *:80->80/tcp

```

**Listen port**

```
root@manager:~# netstat -lnp -t
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::80                   :::*                    LISTEN      219/dockerd     
tcp6       0      0 :::2377                 :::*                    LISTEN      219/dockerd     
tcp6       0      0 :::7946                 :::*                    LISTEN      219/dockerd     
```

**Result**
```
root@manager:~# curl localhost
<html>
<head>
	<title>Hello world!</title>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
	<style>
	body {
		background-color: white;
		text-align: center;
		padding: 50px;
		font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
	}

	#logo {
		margin-bottom: 40px;
	}
	</style>
</head>
<body>
	<img id="logo" src="logo.png" />
	<h1>Hello world!</h1>
	<h3>My hostname is 0933e7e821ba</h3>	</body>
</html>
```

**Comment by LawfulHacker** [comment]
@niko-daniel the [docker engine documentation](https://docs.docker.com/engine/reference/commandline/service_create/#options) states that `-p` and `--publish` are the same option, I tried it and it make no diference on the service. It continues not accepting connections.

What is your configuration? I using the binaries provided by canocial for LXD (apt install lxd lxd-client).

    sergio@halley:~$ uname -a
    Linux halley 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jfgibbins** [comment]
@LawfulHacker l I was just about to ask what version of ubuntu you're running.  I'll take it what you listed is for the host, what about the container itself?  I'm running 17.04 on the host, and generally run LTS as a guest, but the new docker swarm is an epic fail on LTS when using the overlay.  Try running your container as zesty.

**Comment by niko-daniel** [comment]
@LawfulHacker yeah, I know that. thats why I said. so, you need to try that.
host system use xubuntu/xenial 16.04
```
user@ThinkPad-E440:~$ uname -a
Linux ThinkPad-E440 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
user@ThinkPad-E440:~$ lxc --version
2.18

```
container config
```
user@ThinkPad-E440:~$ lxc config show manager --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu xenial amd64 (20170915_03:49)
  image.os: Ubuntu
  image.release: xenial
  image.serial: "20170915_03:49"
  limits.memory: 1GB
  linux.kernel_modules: overlay,nf_nat,ip_tables,br_netfilter,xt_conntrack,nf_conntrack,ip_vs,vxlan
  security.nesting: "true"
  security.privileged: "true"
  volatile.base_image: 6bacf97c51be06574898156c131e38e02901f4317564ec8610670b311b5865a5
  volatile.eth0.hwaddr: 00:16:3e:62:48:54
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

```
container system also use xenial
```
root@manager:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

```
docker 
```
root@manager:~# docker version
Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:42:53 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:43 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Comment by LawfulHacker** [comment]
@niko-daniel thanks for your information, I was able to make my swarm work.

I enabled more modules based on your configuration:

    # Old modules
    lxc profile set docker linux.kernel_modules ip_tables,ip6_tables,netlink_diag,nf_nat,br_netfilter,overlay

    # New Modules
    lxc profile set docker linux.kernel_modules overlay,nf_nat,ip_tables,ip6_tables,netlink_diag,br_netfilter,xt_conntrack,nf_conntrack,ip_vs,vxlan

Probable the `vxlan` missing module was causing the network issues.

**Comment by Remigius2011** [comment]
@LawfulHacker  and @niko-daniel , just out of curiosity: did you encounter this problem: https://stackoverflow.com/questions/45731683/docker-pull-operation-not-permitted ?

**Comment by LawfulHacker** [comment]
@Remigius2011 no.

**Comment by niko-daniel** [comment]
@Remigius2011 looks like permission issue, but I'm not sure. how about your container configurations ?
  security.nesting: "true"
  security.privileged: "true"

@LawfulHacker I don't know exactly which module loaded by docker container. basically overlay network use vxlan based on docker documentations, so I'm just doing some test to make it works and you will see docker_gwbridge and some veth interface on your network config. it's a sign overlay network started working.

**Comment by Remigius2011** [comment]
@niko-daniel : OMG, I was under the assumption that my containers were privileged all the time, because I set `privileged = true` in my terraform script. But only setting security.privileged = true (after doucle-checking the container's config with `lxc config show --expanded`) in the resource's config setction makes them _really_ privileged... now the `docker pull` works. I'll try to strip down all the changes I made to get everything working (including kernel modules. aa_profile etc.)

**Comment by stgraber** [comment]
Closing this issue as there's nothing actionable on the LXD side and not much conversation has happened here in a while (2 years). Discussions are also better hosted on discuss.linuxcontainers.org these days.

I've also found someone who actually did do this work, though I don't know how well this works and whether this is headed upstream any time soon. https://github.com/BrendanBall/docker-machine-driver-lxd

**Comment by BrendanBall** [comment]
@stgraber that work is half done. If I remember correctly I was stuck at getting a usable boot image, but haven't looked at it in a long time.

**Comment by stgraber** [comment]
Thanks for the update, hopefully if someone wants to use it they may complete the work to get it fully functional

**Comment by gattytto** [comment]
https://github.com/eclipse/che-docs/pull/891/files
