### ISSUE TITLE
lxc launch ubuntu fails untar of image with exit status 2

### ISSUE THREAD

**Issue by hnakamur** [lxc/lxd#298]
I'm using LXD 0.2 https://github.com/lxc/lxd/commit/262190ab09ffbb9ebd1f984f9a2b78e768bf81ec
I ran the following command with non-root user `vagrant`.

```
$GOPATH/bin/lxd --debug
```

Then I ran the following command in another terminal. https://github.com/lxc/lxd#first-steps

```
lxc launch ubuntu
```

lxd prints the following error.

```
2015/03/02 13:39:30 handling GET /1.0/operations/e24c6a9a-ca98-4084-991b-36806460b6ea/wait
Untar of image: Output
Error exit status 2
```

I modified lxd/containers.go and tried again.

```
diff --git a/lxd/containers.go b/lxd/containers.go
index 34a8982..78fb6c4 100644
--- a/lxd/containers.go
+++ b/lxd/containers.go
@@ -184,6 +184,7 @@ func extractShiftRootfs(uuid string, name string, d *Daemon) error {
         */
        dpath := shared.VarPath("lxc", name)
        imagefile := shared.VarPath("images", uuid)
+fmt.Printf("dpath=%v, imagefile=%v\n", dpath, imagefile)
        output, err := exec.Command("tar", "-C", dpath, "--numeric-owner", "-Jxf", imagefile, "root
        if err != nil {
                fmt.Printf("Untar of image: Output %s\nError %s\n", output, err)
```

Then I got

```
2015/03/02 13:59:10 handling GET /1.0/operations/c4964f60-7676-4715-b41d-9edf0b7426ff/wait
dpath=/var/lib/lxd/lxc/encephalic-elza, imagefile=/var/lib/lxd/images/f0d7caa414b14ad45a35d94208013c413df3656cc8937d22e94398ccade398b1
Untar of image: Output
Error exit status 2
```

And I tried the tar command by hand.

```
vagrant@ubuntu-1404:~$ tar -C /var/lib/lxd/lxc/porphyritic-leisha --numeric-owner -Jxf /var/lib/lxd/images/f0d7caa414b14ad45a35d94208013c413df3656cc8937d22e94398ccade398b1 rootfs
tar: /var/lib/lxd/lxc/porphyritic-leisha: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```

So I made the destination directory and tried again.
And I got the following errors this time.

```
vagrant@ubuntu-1404:~$ mkdir /var/lib/lxd/lxc/porphyritic-leisha
vagrant@ubuntu-1404:~$ tar -C /var/lib/lxd/lxc/porphyritic-leisha --numeric-owner -Jxf /var/lib/lxd/images/f0d7caa414b14ad45a35d94208013c413df3656cc8937d22e94398ccade398b1 rootfs
tar: rootfs/./dev/agpgart: Cannot mknod: Operation not permitted
tar: rootfs/./dev/audio: Cannot mknod: Operation not permitted
tar: rootfs/./dev/audio1: Cannot mknod: Operation not permitted
tar: rootfs/./dev/audio2: Cannot mknod: Operation not permitted
tar: rootfs/./dev/audio3: Cannot mknod: Operation not permitted
^C
```

How can I avoid these error?
Am I supposed to run `lxd` and `lxc launch` with a non-root user, right?

**Comment by stgraber** [comment]
The LXD daemon must run as root. It will then spawn unprivileged containers using the uids and gids it owns, but the daemon itself must run as root so it can create devices and dump processes for migration.

**Comment by hnakamur** [comment]
Thanks for updating README.
I tried with `sudo -E $GOPATH/bin/lxd --group admin`, but I'm on a ubuntu 14.04 server, and it does not have the `admin` group.

```
vagrant@ubuntu-1404:~$ sudo $GOPATH/bin/lxd --group admin
error: unknown group admin
```

So I used the `sudo` group instead.

```
vagrant@ubuntu-1404:~$ sudo $GOPATH/bin/lxd --group sudo
```

Then I ran `lxc launch ubuntu` and it succeeded!
Thanks for your help!

**Comment by tych0** [comment]
Ah, yeah, it seems half of the machines I play with have 'sudo', and half of them have 'admin'. I'm not sure what the deal is, perhaps @stgraber knows.

**Comment by stgraber** [comment]
sudo is the new name for what was admin. I believe we did the transition around 14.04, so systems that have been upgraded will typically have both.

**Comment by tych0** [comment]
On Mon, Mar 02, 2015 at 08:17:08AM -0800, St�phane Graber wrote:
> sudo is the new name for what was admin. I believe we did the transition around 14.04, so systems that have been upgraded will typically have both.

Ah, perhaps we should switch the recommended group name to sudo? I
can't remember where I was, but one didn't have 'sudo'; this probably
explains why :)

**Comment by hnakamur** [comment]
Thanks for the info about `sudo` and `admin` group.
I found the following page.
[permissions - What is the difference between the 'sudo' and 'admin' group? - Ask Ubuntu](http://askubuntu.com/questions/43317/what-is-the-difference-between-the-sudo-and-admin-group/122500#122500)

**Comment by BarthV** [comment]
@hnakamur : Do you still have this issue ?

I got it few weeks ago, but It seems to work now.
Maybe you can try ```apt-get install acl xzip tar rsync pxz xz-utils python-lzma cgroup-bin libpam-systemd``` :D I think there way more packed that lxd really needs, but try it and tell me if it helps.

**Comment by hnakamur** [comment]
@BarthV No, I don't have this issue.
It is working with the command `sudo $GOPATH/bin/lxd --group sudo` as I wrote at https://github.com/lxc/lxd/issues/298#issuecomment-76741224.
I should've closed this issue.
Thanks for your comment!
