### ISSUE TITLE
"Failed to clone the filesystem" after deleting cached image

### ISSUE THREAD

**Issue by AdamIsrael** [lxc/lxd#2997]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.8.0-34-generic 
   * LXC version: 2.0.7
   * LXD version: 2.10
   * Storage backend in use: zfs

# Issue description

Once a cached image has been deleted, lxc fails when attempting to launch a new container using that image. If I apt remove --purge lxd && apt install lxd, I can re-run lxd init and repeat the steps below to reproduce.

# Steps to reproduce

lxc launch ubuntu:16.04 c1
lxc image delete 96e12fc44b24
lxc launch ubuntu:16.04 c2

# Information to attach

- [lxc-image-delete.txt](https://github.com/lxc/lxd/files/815085/lxc-image-delete.txt)
- [lxc-launch.txt](https://github.com/lxc/lxd/files/815084/lxc-launch.txt)
- [lxd.txt](https://github.com/lxc/lxd/files/815083/lxd.txt)
- [syslog.txt](https://github.com/lxc/lxd/files/815087/syslog.txt)
- [zpool-history.txt](https://github.com/lxc/lxd/files/815088/zpool-history.txt)
- [zpool-list.txt](https://github.com/lxc/lxd/files/815086/zpool-list.txt)

**Comment by brauner** [comment]
Addressed in https://github.com/lxc/lxd/pull/2996.

**Comment by stgraber** [comment]
Doh, looks like we'll need a 2.10.1 for that one...
