### ISSUE TITLE
LXD - split images vs. single images

### ISSUE THREAD

**Issue by audiocricket** [lxc/lxd#2998]
Hi,

why some images can be exported to single tarball (containing both /rootfs/ and /metadata*) and some images are split separately into metadata and rootfs tarballs in output directory?

Does LXD remember when images were imported via single file and when they were imported via separate meta + rootfs tarballs?

It would be nice to have the export functionality behave the same for any kind of image - i.e. an image should be exported either to a single file (with /rootfs/ and /metadata contents) or separate tarballs, because in the end, the outcome (image rootfs and its metadata) is the same, isn't it?

Thanks for clarification!

**Comment by stgraber** [comment]
LXD images are represented by their fingerprints. Combining split images during export or splitting unified images would change that fingerprint and so break on re-import.

LXD's image store never modifies what it records. So if an image was imported as two files, it will be exported as two files. If it was imported as a single file, it will be exported as a single file.

Images LXD generates itself internally when you publish a container are always generated as unified (single file) images.
