### ISSUE TITLE
LXD v2.9.3 - container volatile.base_image attribute inconsistency?

### ISSUE THREAD

**Issue by audiocricket** [lxc/lxd#2999]
Hi,

when we create a container from custom image, the volatile.base_image attribute in `lxc config show <container>` displays SHA hash of the image (image fingerprint).

But when the container is created from "stock" images out of the box (remote images provided by linuxcontainers.org - created using `image:`), the volatile.base_image is not SHA hash anymore, but instead it points to alias of the source image.

The documentation @ https://github.com/lxc/lxd/blob/master/doc/configuration.md says that `volatile.base_image` means `The hash of the image the container was created from, if any.`.

What's more correct then? Documentation or the current state?

Thanks for clarification!

**Comment by stgraber** [comment]
Hmm, base_image is absolutely supposed to be a fingerprint, not an alias...

**Comment by brauner** [comment]
Yeah, this is a regression in comparison to `2.8`.

**Comment by stgraber** [comment]
variable scoping problem, sending a fix
