### ISSUE TITLE
"Read-only" root fs

### ISSUE THREAD

**Issue by tatraian** [lxc/lxd#3003]
First of all, sorry for my English...

I have to create build machines with the same set of libraries and binaries. I planed to create a "golden" image and all build instance should be a clone of it. My first idea was that the "golden" image does not run, just only we have to install/update packages (CentOS7). The cloned images have to use the root filesystem as read only (so accidentally executed yum won't modify /usr).

After reading the documentations, I figured out a solution but with many additional tasks. I can create an image and I can mount its rootfs in read-only mode into other containers and I can mount all part file systems (/home, /var, /run, /tmp), but that means that
* I cannot move this infrastrcture from one machine to an other
* I have to create sub volumes for all machines
* Attaching this profile to images does not look automatic (due to sub volumes paths)

I'm sure that there is an easier solution for this. Could you please help me?

My system:

 * Distribution: Ubuntu 
 * Distribution version: 16.04.2 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-64-generic
   * LXC version: 2.8
   * LXD version: 2.8
   * Storage backend in use: Brtfs

**Comment by stgraber** [comment]
Can you just create that base container, then use that as the base for your build containers (possibly using --ephemeral for them) and in those, run "mount --bind /usr /usr && mount -o remount,rw /usr" to have /usr be read-only and prevent accidental package updates?

**Comment by lagunax** [comment]
@stgraber, is there any way to implement internal block-devices with internal partitioning?

**Comment by stgraber** [comment]
@lagunax you can pass block devices with the unix-block device type. The container can then partition it, but the partitions themselves won't be visible in the container's /dev unless you pass additional unix-block devices for them (once created) and the container won't be able to mount those devices unless it's a privileged container with a custom apparmor rule to allow it.

In short, interacting with block devices in containers is usually a bad idea. That stuff isn't properly namespaced in the kernel and if allowed is full of security issues waiting to happen as it'd allow the user to feed any data it wants to the kernel for parsing by a filesystem driver.

**Comment by tatraian** [comment]
Thanks a lot! This solves my problem! This stuff is cool:)
