### ISSUE TITLE
Improve LXD backup handling

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3005]
LXD recently grew the ability to write a "backup.yaml" file in the container's directory and re-import a container from that file through "lxd import NAME".

I suspect that this got broken with the recent storage work and that even though the file is still being generated in some cases, it fails to be updated in most and can't currently be re-imported cleanly in moderately complex environments.

Our documentation is also very lacking when backup/restore is concerned.

We should:

 - [ ] Simplify the backup feature to dump backup.yaml every time a container starts. This guarantees that the storage will be available at the time. Failure to dump backup.yaml at that time should be considered an error and fail container start. That will prevent unpleasant surprises where someone notices that backup.yaml was outdated at the time of a restore.
 - [x] "lxd import NAME" needs to be updated to look under /var/lib/lxd/storage-pools/*/containers/NAME. If it doesn't find any entry, then it should fail. If it finds more than one entry, then the user's environment is broken and it should fail too.
 - [x] "lxd import" should grow a "--force" flag which (and matching internal API property) which allows importing a container which already exists in the LXD database. In such case, LXD should delete all database information for the container and then perform a normal import.
 - [ ] We need a new doc/backup.md file which explains how the backup/restore mechanism works.
 - [x] We need a Jenkins test which tests the generation of backup.yaml on container startup and attempts a restore from it.

**Comment by stgraber** [comment]
We also should have a serialized version of the storage pools used by the container and any volume it uses from those pools (container type or custom type).

We should require the user to have manually mounted the container path where it belongs (/var/lib/lxd/storage-pools/POOL/containers/NAME), then can get everything we need from there.
We should sanity check things by comparing the pool name from backup.yaml to the pool we found the container in on the filesystem. Define the storage pool in the database if it's not there yet, same for any custom volume the container uses.

**Comment by stgraber** [comment]
We have two main use cases for this feature:

 1) A user has some kind of automated backup for their storage pools. That typically affects ZFS users where plenty of tools to do send/receive based backups exist. But it'd also affect anyone who's physically recovered the disk used to back a LXD storage pool. In this case, we'll be dealing with a blank LXD and need to re-import the container from a storage pool mounted at /var/lib/lxd/storage-pools/NAME

 2) A user is maintaining a backup LXD which has its storage synced with a production system. In this setup, the user will regularly want to do a test import of their backup by issuing "lxd import --force NAME" to replace whatever copy of the container they already have defined on LXD with a freshly imported one from backup.yaml

**Comment by stgraber** [comment]
As for "backup.md". I think we want to point out the following backup strategies:

 1) Full backup: Backup all your storage pools AND /var/lib/lxd. For restore, stop LXD, wipe /var/lib/lxd, restore the /var/lib/lxd snapshot and restore your storage pools.
 2) Secondary LXD: Setup a second LXD server and copy your containers from the first server to the second once a day or so.
 3) Container backup/restore: That's what backup.yaml and "lxd restore" are for. They are mostly meant as an emergency recovery mechanism and allow re-creating container and storage objects from just a backup of the store pool. They also allow testing backups by restoring using --force on a secondary system.

**Comment by pepanillo** [comment]
Hello. In version  prior to 2.10 (Ubuntu 16.04 Server and ZFS) the containers were at /var/ lib/lxd/containers/. Then was easy to make a bakup of one specific container with lxc stop, and tar. Restoring was easy too with lxd import. Now, from 2.10, at /var/lib/lxd/containers/ there are links to /var/lib/lxd/storage-pools/lxd/containers/, where the containers are. But if you stop a container, the content of the container dissapears in /var/lib/lxd/storage-pools/lxd/container/container-name.

Making a copy of a running container is not a good idea. And I can't find documentation that help me.

I need to make a copy of the containers for backup proposities. And subsequently restore the backups.
any idea? Is there any place with actualized documentation?

**Comment by brauner** [comment]
With the new storage work we don't keep containers constantly mounted to not pollute the host mount table. If you want to perform a manual backup you can mount the corresponding `zfs` dataset by using:

```
zfs mount <pool_name>/containers/<container_name>
```

after this it will be mounted at `/var/lib/lxd/storage-pools/<pool_name>/containers/<container_name>`.

**Comment by pepanillo** [comment]
I'll try it. On the other hand, how restore a copy? mount the zfs dataset and overwrite?

**Comment by stgraber** [comment]
If you have a backup of /var/lib/lxd itself (db and such), then yes, restoring the zfs dataset in place will work fine. Note that most people who use LXD with ZFS seem to be using ZFS aware backup tools which will backup the ZFS datasets themselves (using send/receive) rather than their content.

**Comment by pepanillo** [comment]
I've tried zfs mount for making a backup. Ok, works fine. Thanks @brauner.

**Comment by pepanillo** [comment]
And now, the second part. I have a backup of a container (backup.yaml, metadata.yaml, rootfs and templates).  I want to restore it. If the original container no exist (p. ej. a crash and I am restoring the system) what are the steps to follow? I have tried with a copy from version 2.09 and I have failed miserably.

**Comment by stgraber** [comment]
Well, that's what this issue is about, we have a mechanism to do that but it needs some improvements.

In theory you'd do the following:
 - Restore the ZFS dataset
 - Make sure it's mounted at /var/lib/lxd/storage-pools/POOL-NAME/containers/CONTAINER-NAME
 - Run "lxd import CONTAINER-NAME"

"lxd import" would then parse the backup.yaml file from the container and re-create it in the database.

Note that this will only work if restoring to the same or newer LXD version. "backup.yaml" support was added in LXD 2.7.

**Comment by pepanillo** [comment]
Ok, Thanks for your patience @stgraber . I'll try and tell you.

**Comment by pepanillo** [comment]
When I run lxd import sensor (sensor is the container's name) gives the following error
error: readlink /var/lib/lxd/containers/sensor: no such file or directory
Must I create the link in /var/lib/lxd/containers?

**Comment by pepanillo** [comment]
The reason could be that the version of the backup is 2.09?

**Comment by stgraber** [comment]
@pepanillo yeah, that's one of the things that this Github issue is covering, right now "lxd import" assumes that the link exists even though it really shouldn't...

So yeah, you should create a symlink from /var/lib/lxd/containers/NAME to /var/lib/lxd/storage-pools/POOL/containers/NAME

**Comment by stgraber** [comment]
There is no such release as LXD 2.09. There is LXD 2.0.9 (which doesn't have backup.yaml) or LXD 2.9 (which does).

**Comment by pepanillo** [comment]
sorry, 2.9

**Comment by pepanillo** [comment]
And the result is:

# lxd import sensor
error: Failed to mount ZFS filesystem: cannot open 'lxd/containers/sensor': dataset does not exist

**Comment by stgraber** [comment]
can you paste "zfs list -t all"?

**Comment by pepanillo** [comment]
zfs list -t all
NAME                                                                                           USED  AVAIL  REFER  MOUNTPOINT
lxd                                                                                           1,38G  95,0G    19K  none
lxd/containers                                                                                 353M  95,0G    19K  none
lxd/containers/iadforma                                                                        179M  95,0G   482M  /var/lib/lxd/storage-pools/lxd/containers/iadforma
lxd/containers/ws226                                                                           173M  95,0G   471M  /var/lib/lxd/storage-pools/lxd/containers/ws226
lxd/deleted                                                                                    704M  95,0G    19K  none
lxd/deleted/images                                                                             704M  95,0G    19K  none
lxd/deleted/images/87a1f1c305615024124b238c0fcbed99c11193cab4bbc5c340ca2500c99b1b1f            351M  95,0G   351M  none
lxd/deleted/images/87a1f1c305615024124b238c0fcbed99c11193cab4bbc5c340ca2500c99b1b1f@readonly      0      -   351M  -
lxd/deleted/images/fce0f27114d37f3e0827e0c629aefcc32dc1c99af293c5306d43f3d5d50c6f29            352M  95,0G   352M  none
lxd/deleted/images/fce0f27114d37f3e0827e0c629aefcc32dc1c99af293c5306d43f3d5d50c6f29@readonly      0      -   352M  -
lxd/images                                                                                     353M  95,0G    19K  none
lxd/images/2cab90c0c342346ea154bc2e8cacdae752a70747a755ce1f2970c9a9ebb5fe8c                    353M  95,0G   353M  none
lxd/images/2cab90c0c342346ea154bc2e8cacdae752a70747a755ce1f2970c9a9ebb5fe8c@readonly              0      -   353M  -

**Comment by stgraber** [comment]
So the error is right, you don't have a lxd/containers/sensor dataset

**Comment by pepanillo** [comment]
Yes, I want to restore that container.

**Comment by stgraber** [comment]
If you just restored the files in /var/lib/lxd/storage-pools/lxd/containers/sensor, then that's wrong.
You need to restore the zfs dataset before LXD can do anything about it.

So move /var/lib/lxd/storage-pools/lxd/containers/sensor aside, run "zfs create lxd/containers/sensor -o mountpoint=/var/lib/lxd/storage-pools/lxd/containers/sensor" and then restore your files in /var/lib/lxd/storage-pools/lxd/containers/sensor

That way the ZFS dataset will be properly restored which should make "lxd import" happy.

**Comment by pepanillo** [comment]
Ah! Thanks a lot! Trying ...

**Comment by pepanillo** [comment]
lxd import works but ... sensor is not working fine. I have problems with the network on that container.

**Comment by pepanillo** [comment]
I'll try with backup from 2.11 and restore to 2.11.

**Comment by stgraber** [comment]
We didn't change anything in the import logic in 2.11 so it's unlikely to work any better. That's why we have this issue open to look into this and fix it :)

**Comment by stgraber** [comment]
```
lxc config show --expanded sensor
```

That should show any obvious problem with your container.

**Comment by pepanillo** [comment]
Sorry for the delay. `lxc config` showed no errors. But the container is working fine now. I shall document the procedure to backup and make a tarball of a container.
Thanks a lot for the help.

**Comment by brauner** [comment]
@stgraber, about:
> We also should have a serialized version of the storage pools used by the container and any volume it uses from those pools (container type or custom type).

So I agree about a serialized version of the storage pool the container belongs to. But I fail to see the value of having all storage pools the container uses indirectly via volumes or containers on those pools. The information needed to recover this information is either already provided in the local container config via the devices section or via profiles the container belongs to. So what I currently have implemented for now is: https://paste.ubuntu.com/24195329/

**Comment by brauner** [comment]
What we do need however, is to backup the storage volume configuration for the container itself.

**Comment by stgraber** [comment]
Right, was about to point out, we need a serialized version of the storage volume for the container itself, in case there was some weird attributes set on that which need restoring.

**Comment by renky** [comment]
Reopened because lxd import doesn't work porperly on my system...
OS: Debian Stretch, LXD 2.16 (Snap)
Created a new container from scratch (ubuntu 17.04)
made some changes, created 3 Snapshots of the container (with lxc snapshot ....)
here is zft list -t all:
```
zpool1/lxd/containers/test                                                                   5.68M  1.24T   314M  /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/test        
zpool1/lxd/containers/test@snapshot-erster                                                   51.6K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-zweiter                                                  52.4K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-dritter                                                      0      -   314M  -                                                           
...
...
zpool1/lxd/snapshots/test                                                                    25.4K  1.24T  25.4K  none         
```

then I made a zfs-backup:
```
zfs send -R zpool1/lxd/containers/test@snapshot-dritter > /tmp/test
```

important: i didn't save the snapshots-dataset for this container (maybe this was my failure?)

then destroyed the container:

```
lxc stop test
lxc delete test
```

zfs shows no further datasets of the container, ans no snapshots any more

then restored zfs:

```
zfs receive zpool1/lxd/containers/test < /tmp/test
``` 

worked fine, zfs list -t a shows:
```
zpool1/lxd/containers/test                                                                   5.68M  1.24T   314M  /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/test        
zpool1/lxd/containers/test@snapshot-erster                                                   51.6K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-zweiter                                                  52.4K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-dritter                                                      0      -   314M  -                                                                    
```
but it doesn't show the snapshot dataset -> thats right, I didn't backup it...

then import the container
```
lxd import test
```
seems to be successful:
```
lxc list
+------------+---------+---------------------+------+------------+-----------+                                                                                                         
|    NAME    |  STATE  |        IPV4         | IPV6 |    TYPE    | SNAPSHOTS |                                                                                                         
+------------+---------+---------------------+------+------------+-----------+                                                                                                         
| test       | STOPPED |                     |      | PERSISTENT | 0         |                                                                                                         
+------------+---------+---------------------+------+------------+-----------+                                                                                                         
```
but the snapshots are missing - so lxd didn't find the really existing zfs snapshots...
and now the container cannot be startet:
```
> lxc start test
error: Failed to run: /snap/lxd/3346/bin/lxd forkstart test /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/test/lxc.conf:                                           
Try `lxc info --show-log test` for more info                                                                                                                                           

> lxc info --show-log test
Name: test                                                                                                                                                                             
Remote: unix://                                                                                                                                                                        
Architecture: x86_64                                                                                                                                                                   
Created: 2017/08/14 12:03 UTC                                                                                                                                                          
Status: Stopped                                                                                                                                                                        
Type: persistent                                                                                                                                                                       
Profiles: default                                                                                                                                                                      
                                                                                                                                                                                       
Log:                                                                                                                                                                                   
                                                                                                                                                                                       
            lxc 20170814120333.534 ERROR    lxc_conf - conf.c:run_buffer:416 - Script exited with status 1.                                                                            
            lxc 20170814120333.534 ERROR    lxc_start - start.c:lxc_init:450 - Failed to run lxc.hook.pre-start for container "test".                                                  
            lxc 20170814120333.534 ERROR    lxc_start - start.c:__lxc_start:1314 - Failed to initialize container "test".                                                              
            lxc 20170814120333.534 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.                  
```

is this  really because of the missing snapshot-dataset?
or should lxd find all the snapshots and import it too?

**Comment by renky** [comment]
ok, tried it again with also saving zpool1/lxd/snapshots/test and restoring it...
same result: lxc list doesn't show any snapshots, and container doesn't run.
