### ISSUE TITLE
Consistent containers copies

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3006]
Assuming a container "c1" with a bunch of snapshots. Right now we have the following behavior:
 - lxc copy c1 c2 => c2 is created from c1 and has no snapshots
 - lxc copy c1 remote:c2 => remote:c2 is created from c1 and has all its snapshots

This is pretty inconsistent and should be fixed. I think to avoid breaking people, the best is to have the default behavior always copy all snapshots. Then add a flag allowing to the API and "lxc copy" to only copy the current container state.

So we would get:
 - lxc copy c1 c2 => c2 is created from c1 and has all its snapshots
 - lxc copy c1 remote:c2 => remote:c2 is created from c1 and has all its snapshots
 - lxc copy c1 c2 --no-snapshots => c2 is created from c1 and has no snapshots
 - lxc copy c1 remote:c2 --no-snapshots => remote:c2 is created from c1 and has no snapshots

**Comment by brauner** [comment]
This is caused by using `LocalCopy()` which does not handle snapshots. I've got patch in my tree that allows `LocalCopy()` to request the list of snapshots associated with a given container and create them as well.

**Comment by brauner** [comment]
Hm, we should actually only use `LocalCopy()` when the container we're copying has not snapshots. Otherwise we'd need unnecessary complexity in `container_snapshots.go` just for that.

**Comment by stgraber** [comment]
That would only fix our command line tool though, not anyone who's using the REST API for this.

**Comment by stgraber** [comment]
So looks like we'll need:
 - Add a new "ContainerOnly" attribute to ContainerSource to control whether to copy snapshots or not.
 - Add a new --container-only argument to "lxc copy" which sets that flag
 - Add an extra argument to ContainerCopy to indicate that we want to copy all the snapshots too
 - Update containerCreateAsCopy to also take that argument and pass it through to ContainerCopy. Additionally, it should create the various DB entries for the snapshots themselves.
 - Update all the storage drivers to do something sane when asked to copy snapshots. It should be pretty straightforward for dir, btrfs and lvm. Zfs will be the weird one as you can't do a clone including snapshots, so if a copy of a zfs backed container is made and it has snapshots, send/receive will have to be used instead...

**Comment by pgassmann** [comment]
Also remote copy of a running container tries to copy the state. https://github.com/lxc/lxd/issues/3086#issuecomment-287633173

Remote copy of a running container should discard the state. 

A `--stateful` option could make sense in very rare circumstances. E.g inspection of the running state without affecting production by copying the running container to my local machine. But under normal circumstances it is mostly a bad idea to have the exact same machine running twice.

**Comment by brauner** [comment]
@stgraber, so:

> - Add a new "ContainerOnly" attribute to ContainerSource to control whether to copy snapshots or not.

Agreed.

> - Add a new --container-only argument to "lxc copy" which sets that flag

Agreed.

> - Add an extra argument to ContainerCopy to indicate that we want to copy all the snapshots too

I don't think this is necessary and I don't know what we gain from this. See below.

> - Update containerCreateAsCopy to also take that argument and pass it through to ContainerCopy. Additionally, it should create the various DB entries for the snapshots themselves.

So I think all of this can be handled in `createFromCopy()` itself without modifying either `containerCreateAsCopy()` nor `ContainerCopy()` unless some backend will force me too (looking at `zfs` here...).
Essentially, what we can do is to modify the workhorse in `createFromCopy()`:

```
diff --git a/lxd/containers_post.go b/lxd/containers_post.go
index 2db5f179..cbc62d2d 100644
--- a/lxd/containers_post.go
+++ b/lxd/containers_post.go
@@ -471,6 +471,34 @@ func createFromCopy(d *Daemon, req *api.ContainersPost) Response {
 			return err
 		}
 
+		snapshots, err := source.Snapshots()
+		if err != nil {
+			return err
+		}
+
+		if req.Source.ContainerOnly {
+			return nil
+		}
+
+		for _, snap := range snapshots {
+			fields := strings.SplitN(snap.Name(), shared.SnapshotDelimiter, 2)
+			newSnapName := fmt.Sprintf("%s/%s", req.Name, fields[1])
+			snapArgs := containerArgs{
+				Architecture: snap.Architecture(),
+				Config:       snap.LocalConfig(),
+				Ctype:        cTypeSnapshot,
+				Devices:      snap.LocalDevices(),
+				Ephemeral:    snap.IsEphemeral(),
+				Name:         newSnapName,
+				Profiles:     snap.Profiles(),
+			}
+
+			_, err := containerCreateAsCopy(d, snapArgs, snap)
+			if err != nil {
+				return err
+			}
+		}
+
 		return nil
 	}
```

> - Update all the storage drivers to do something sane when asked to copy snapshots. It should be pretty straightforward for dir, btrfs and lvm. Zfs will be the weird one as you can't do a clone including snapshots, so if a copy of a zfs backed container is made and it has snapshots, send/receive will have to be used instead...

Agreed.

**Comment by stgraber** [comment]
That sounds fine, if you can get ZFS to let you transfer snapshots one by one rather than all of them in one chunk as I thought we'd need to do.

**Comment by brauner** [comment]
So, when we currently copy a zfs container (leaving snapshots aside for a minute) what we do is:

`zfs snapshot -r pool/containers/c pool/containers/c@<uuid>`
`zfs clone -p pool/containers/c@<uuid> pool/containers/c-copy`

This will leave `pool/containers/c@<uuid>` behind as long as `pool/containers/c-copy` exists. I wonder if it wouldn't be smarter if we did:
```
zfs snapshot -r pool/containers/c pool/containers/c@<uuid>
zfs send pool/containers/c@<uuid> pool/containers/c-copy
zfs destroy pool/containers/c@<uuid>
zfs destroy pool/containersc-copy<@<uuid>
```
which will only leave us with `pool/containers/c` and `pool/containers/c-copy`.

**Comment by brauner** [comment]
That is, if it isn't too expensive in space.

**Comment by brauner** [comment]
So what I specifically mean is (when creating a copy without snapshots):
1. `lxc copy alp5 alp6` (copying an existing container dataset to a new container):
```
zfs snapshot -r pool3/containers/alp5 pool3/containers/alp5@<uuid>
zfs send pool3/containers/alp5@<uuid> | zfs receive pool3/containers/alp6
zfs rollback pool3/containers/alp6@<uuid>
zfs destroy zfs receive pool3/containers/alp5@<uuid>
zfs destroy zfs receive pool3/containers/alp6@<uuid>
```

2. `lxc copy alp5/snap0 alp6` (copying an existing snapshot to a new container):
```
zfs send pool3/containers/alp5@snapshot-snap3 | zfs receive pool3/containers/alp6
zfs rollback pool3/containers/alp6@snapshot-snap3
zfs destroy pool3/containers/alp6@snapshot-snap3
```

@stgraber, does that make sense or should we use the clone behavior where we keep stuff around in the filesystem?

**Comment by stgraber** [comment]
@brauner Always using send/receive would make the zfs performance and disk space about as good as the dir backend, so not really an option.

**Comment by brauner** [comment]
This would only affect the copy case, but yeah.

**Comment by stgraber** [comment]
So I don't think we have much of a choice when the container has snapshots which is a bit unfortunate but that's a ZFS limitation, but when the container doesn't have any, a clone should be preferred.

**Comment by lagunax** [comment]
what about doin copy from some erly snapshot? something like copy c1:snap5 c2 , where c2 will be copy from snap5 in c1
