### ISSUE TITLE
Feature request: LXD init? add storage backends

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#3012]
long time storage_api makes better. it can use many types of storages. but.
```
#lxd init
...cutted here...
Name of the storage backend to use (dir or zfs) [default=dir]:
```
why does only dir and zfs in this place? :)
whould it be nice to add more backends here? :)

**Comment by brauner** [comment]
We already have an issue tracking this: https://github.com/lxc/lxd/issues/2986.
So closing this one in favor of the other. :)
