### ISSUE TITLE
LXD with LVM (source issue)

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#3013]
I'm not fully understand new technology. tech is good and your work is best, but:
googling in storage backend-working i found it:

>    Create new pool on "/dev/sdX" with the volume group name "my-pool".
> 
> lxc storage create pool1 lvm source=/dev/sdX lvm.vg_name=my-pool
> 

from here: https://github.com/lxc/lxd/blob/master/doc/storage-backends.md

so.  there is a little mistake with some naming and usage LVM. let see:

> lvm.vg_name=my-pool

at first '=my-volume-group'

> source=/dev/sdX

why sdX? my VG consists of a lot of HDDs. then, how can i describe here a lot of sources? i think it needs to remake and use VolumeGroup as source. then it removes needing in 'lvm.vg_name=my-pool'.

**Comment by brauner** [comment]
If I understand you correctly then you want to use an already existing volume group. That is certainly possible. You can use a volume group as source you just specify `source=my-pool` and leave the `lvm.vg_name` property empty.

**Comment by brauner** [comment]
See

> Use the existing volume group "my-pool"
lxc storage create pool1 lvm source=my-pool

**Comment by Laguna-x** [comment]
@brauner oh. thanks. reeded not carefull :). so. question stays with source=a_lotOfHDDs for new pool :)

**Comment by brauner** [comment]
We currently do not support specifying multiple block device sources. This is something which we would need to discuss whether this makes sense design-wise.

**Comment by Laguna-x** [comment]
@brauner i think this mast be looking a little other way. somthing like

> lxc storage create pool1 lvm devices=/dev/sda1,/dev/sdb2 lvm.vg_name=my-pool

then lvm.vg_name will be "source" in storage list. devices in this way will use only for  creating LV

**Comment by stgraber** [comment]
@Laguna-x we don't have plans to support multi-device creation of lvm, btrfs or zfs pools right now.

As @brauner pointed out, for such setups, we'd rather the administrator manually create their LVM VG, ZFS zpool or btrfs filesystem themselves, setup the level of replication they want and tweak whatever other settings they need, and then tell LXD to use it.
