### ISSUE TITLE
Failed to set cgroup memory.limit_in_bytes

### ISSUE THREAD

**Issue by khristovffw** [lxc/lxd#3017]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.02 LTS 
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.8.0-39-generic
   * LXC version: 
   * LXD version: 2.0.9
   * Storage backend in use: zfs

# Issue description
Container was launched with 8GB of RAM memory limit.

I had to import quite some MySQL database on it. After a while i decided to scale it down to 4GB of RAM memory but i got this error:

``
lxc config set db01 limits.memory 4GB
error: Failed to set cgroup memory.limit_in_bytes="4294967296": setting cgroup item for the container failed
``

it was strange. I had another container on the machine and i scaled it normally.

Scaling container db01 was successful with 10GB. After that going back to 8GB also OK. But with 7GB it showed the error above.

I looked into the memory usage inside the container and find out that it was full!

I believe that in these cases when scaling a warning should appear with message that it is impossible to scale because of resource usage. 

# Steps to reproduce
1. Create container
2. Limit RAM memory
3. Fill up RAM memory
4. Scale down RAM memory

**Comment by khristovffw** [comment]
One more thing to add
I have noticed that when scaling was unsuccessful the container was without any memory limit. I could see all the memory of the host machine which is 96GB.

**Comment by stgraber** [comment]
So for the error message, there isn't anything we can do, all we're told by the kernel is "Invalid argument" which can mean just about anything from the actual text value being invalid, not enough physical memory being available, a parent cgroup restriction preventing the write, some weird NUMA restrictions, ...

The fact that the memory limit is cleared before the new value is set is a bit of a problem when setting the limit then fails, I'm looking into fixing that now.
