### ISSUE TITLE
btrfs: improvements

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3020]
The btrfs code is not super nice currently and I've got some fixes coming. What we need are several things:

- loop-backed storage pools independent of the backing fs (fix is in my tree)
- an idea on how to handle (e.g. command-line commands to create) and if we want to better support:
  1. `/var/lib/lxd` or at least `/var/lib/lxd/storage-pools` on an existing btrfs filesystem or subvolume
  2. using an already existing btrfs filesystem or subvolume for storage

For i. we could do `lxc storage create pool1 btrfs source=/var/lib/lxd/storage-pools`.
For ii. we could do `lxc storage create pool1 btrfs source=/some/path`. If `/some/path` is a btrfs *filesystem*  things shouldn't be that difficult in terms of mounting it on `/var/lib/lxd/storage-pools/pool1` since we can detect the `uuid` of the filesystem in `/dev/disk/by-uuid`. However, if we want to also support subvolume re-use then we'd need an additional btrfs pool property `btrfs.fs_uuid` to know what btrfs fileystem the subvolume given to us belongs to. A user would then specify: `lxc storage create pool1 source=/path/to/some/subvolume btrfs.fs_uuid`.

**Comment by brauner** [comment]
- use existing btrfs filesystem:
```
lxc storage create pool1 btrfs source=<{filesystem_name,filesystem_uuid}>
```
This will have LXD create another subvolume called `LXDPool` on the given filesystem. The subvolume `LXDPool` will then be mounted at `/var/lib/lxd/storage-pools/{pool_name}`. The full on-disk layout would then be:

```
LXDPool
LXDPool/containers
LXDPool/images
LXDPool/snapshots
```

**Comment by stgraber** [comment]
```
lxc storage create pool1 btrfs source=/var/lib/lxd/storage-pools
```

That looks invalid to me as it'd mean use "/var/lib/lxd/storage-pools" itself as the pool path. Instead we should have this be valid (and I believe it is right now since that's what I'm using for the demo server).

```
lxc storage create pool1 btrfs source=/var/lib/lxd/storage-pools/pool1
```

Which will just create a subvolume in /var/lib/lxd/storage-pools/ assuming that the underlying dir is btrfs (and that works fine).

For re-use of btrfs from a different location (where /data/pool1 exists):
```
lxc storage create pool1 btrfs source=/data/pool1/lxd
```

I'd just have LXD create "/data/pool1/lxd" if it's not an already existing empty subvolume, then bind-mount it onto "/var/lib/lxd/storage-pools/pool1".


In both cases, LXD will not actually mount a btrfs filesystem (no mount to be done in the first case and just a bind-mount in the second), so it doesn't need to record a uuid, it should behave like the "dir" backend and just record the path as the "source" property.

**Comment by brauner** [comment]
Fair enough, certainly an option. By using uuids/labels we just stay very consistent across {lvm,zfs,btrfs}. Yeah, fwiw, your way is the simplest way and doesn't cause a lot of work as this is exactly what I implemented currently. It just needs more tweaking.

**Comment by stgraber** [comment]
btrfs is a bit special when compared to lvm and zfs, it's got much more in common to the "dir" backend than with those two and I think the above pretty much aligns with what we do in dir.

**Comment by brauner** [comment]
I'm addressing this in #3021:

```
1. lxc storage create pool1 source=/path/to/subvolume
- create /path/to/subvolume if it doesn't already exist and bind-mount onto
  ${LXD_DIR}/storage-pools/pool1

2. lxc storage create pool1 source=${LXD_DIR}/storage-pools/pool1
  - create subvolume if LXD is located on btrfs

3. lxc storage create pool1 source=/path-somewhere-under-${LXD_DIR}-but-not-under-storage-pools-subdir
  - This is considered invalid (As it might mess with LXD's on-disk layout).
    The following error message is given:

	chb@conventiont|~/source/go/src/github.com/lxc/lxd|2017-03-05/btrfs_improvements *$%>
	> lxc storage create pool1 btrfs source=/home/chb/mnt/l1/storage-pools/
	error: BTRFS subvolumes requests in LXD directory "/home/chb/mnt/l1" are only valid under "/home/chb/mnt/l1/storage-pools"
	(e.g. source=/home/chb/mnt/l1/storage-pools/pool1)

    I really wouldn't want to allow users to create subvolumes under say e.g.
    ${LXD_DIR}/containers or the like. This will just cause trouble.
```

@stgraber, I'd like to hear you opinion on the third case. I think that we should only let users create btrfs storage pools inside of LXD's directory if a) it is on a btrfs filesystem (trivial) b) when the path they give use corresponds to `${LXD_DIR}/storage-pools/{pool_name}`. Anything else should probably be invalid. Otherwise users might do stuff like create btrfs storage pools inside `${LXD_DIR}/{containers,snapshots,images}` which might cause all kinds of trouble if we ever need to change the on-disk layout of LXD. Also we currently forbid custom loop file locations so it's not unprecedented.

**Comment by stgraber** [comment]
Agreed
