### ISSUE TITLE
set my container port and bridge to connect via putty

### ISSUE THREAD

**Issue by rsaour** [lxc/lxd#3022]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: 16.04
 * Distribution version: Ubuntu
 * The output of "lxc info" or if that fails:
  Name:           ubuntu_01
State:          RUNNING
PID:            24075
IP:             10.0.3.7
CPU use:        9.32 seconds
BlkIO use:      4.45 MiB
Memory use:     69.41 MiB
KMem use:       0 bytes
Link:           vethQTPB73
 TX bytes:      100.01 KiB
 RX bytes:      567.51 KiB
 Total bytes:   667.53 KiB

# Issue description
installed lxc, default bridge setup as ip 10.0.3.1, I need to setup port for my container and then nat my one public ip to multiple containers. 
port forwarding is enabled.

root@sd-94858:/etc/default# lxc-ls  -f
NAME      STATE   AUTOSTART GROUPS IPV4       IPV6
ubuntu_01 RUNNING 0         -      10.0.3.7   -
ubuntu_02 RUNNING 0         -      10.0.3.235 -
root@sd-94858:/etc/default#
root@sd-94858:/etc/default# cat /etc/network/interfaces
source /etc/network/interfaces.d/*
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto enp0s20f0
iface enp0s20f0 inet dhcp

**Comment by stgraber** [comment]
That's LXC not LXD.

What you're after is a simple NAT rule on the host that you should put in an init script or firewall script if you have one.

Something along the lines of:

    iptables -t nat -A PREROUTING -s 1.2.3.4 -p tcp --dport 2222 -j DNAT --to 10.0.3.7:22

Which will have any traffic hitting 1.2.3.4 on port tcp/2222 hit 10.0.3.7 on port 22.
