### ISSUE TITLE
Difficulties restoring LXD System from backup

### ISSUE THREAD

**Issue by NightDevel** [lxc/lxd#3030]
Hi all - I've recently run into a situation wherein I need to restore a lxd system from backup.

I've got the /var/lib/lxd directory backed up, but on direct copy-and-paste restore - I cannot seem to get a container to start.  I haven't found any documentation detailing on what must be done in this situation.

# Required information

I'm on ubuntu server 16.04.2. 
Output of 'lxc info' - https://hastebin.com/eyemomevun.diff

# Steps to reproduce

1) Backup stopped lxd instances
2) Copy over lxd instances to /var/lib/lxd in new machine
3) attempt to start lxd container

https://hastebin.com/norozaxoye.sql

Not entirely sure what needs to be done at this juncture - I have attempted the lxd import command but to no avail, instead receiving a "error: readlink /var/lib/lxd/containers/$containername: invalid argument" error.

**Comment by stgraber** [comment]
Can you paste the output of "ls -lh /var/lib/lxd/containers/"?

**Comment by NightDevel** [comment]
Yep -

night@c3:~# ls -lh /var/lib/lxd/containers/
total 12K
lrwxrwxrwx 1 root root   55 Mar  6 19:58 atlassian -> /var/lib/lxd/storage-pools/default/containers/atlassian
lrwxrwxrwx 1 root root   52 Mar  6 19:58 haraka -> /var/lib/lxd/storage-pools/default/containers/haraka
-rw-r--r-- 1 root root 8.4K Mar  6 20:10 lxc-monitord.log
lrwxrwxrwx 1 root root   55 Mar  6 19:58 notifiers -> /var/lib/lxd/storage-pools/default/containers/notifiers

**Comment by stgraber** [comment]
What about

    ls -lh /var/lib/lxd/storage-pools/default/containers/

**Comment by NightDevel** [comment]
:~# ls -lh /var/lib/lxd/storage-pools/default/containers/
total 12K
drwxr-xr-x 4 231072 165536 4.0K Mar  6 19:58 atlassian
drwxr-xr-x 4 231072 165536 4.0K Mar  6 19:58 haraka
drwxr-xr-x 4 231072 165536 4.0K Mar  6 19:58 notifiers

**Comment by stgraber** [comment]
What error are you getting when you try to start one of those containers?

**Comment by NightDevel** [comment]
https://hastebin.com/azateqekek.swift

**Comment by stgraber** [comment]
Did you make sure your target server has the exact same /etc/subuid and /etc/subgid as the source one?

**Comment by NightDevel** [comment]
I thought I did - apologies.  Editing the values again gave me this "error"

https://hastebin.com/odoreyeqok.sql

So I guess that means success.  However, this error was not present in the previous host.  Have I missed a detail somewhere?

**Comment by stgraber** [comment]
That typically indicates that you're running a kernel with partial apparmor support rather than an official Ubuntu kernel.

**Comment by stgraber** [comment]
Closing the issue since the restore was succesful.
