### ISSUE TITLE
error: Error calling 'lxd forkstart settling-quagga /var/lib/lxd/containers /var/log/lxd/settling-quagga/lxc.conf': err='exit status 1'

### ISSUE THREAD

**Issue by ljy5490** [lxc/lxd#3031]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

driver: lxc
driverversion: 2.0.7
kernel: Linux
kernelarchitecture: armv7l
kernelversion: 4.4.38-v7+
server: lxd
serverpid: 10745
serverversion: 2.0.9
storage: dir
storageversion: ""

Distributor ID: Ubuntu MATE
Description: Ubuntu MATE 16.04.2 LTS for Raspberry Pi 2 and 3 systems

# Issue description

launch lxd container failed

# Steps to reproduce

 1. sudo apt-get install lxd
 2. sudo lxd init
 3. lxc launch ubuntu:16.04

# Log information
Remote: unix:/var/lib/lxd/unix.socket
Architecture: armv7l
Created: 2017/03/07 10:51 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20170307110828.830 ERROR    lxc_start - start.c:must_drop_cap_sys_boot:641 - Failed to clone (0x30000011): Invalid argument (includes CLONE_NEWUSER).
            lxc 20170307110828.846 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1306 - Path "/sys/fs/cgroup/systemd//lxc/settling-quagga" already existed.
            lxc 20170307110828.846 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1363 - No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/settling-quagga: No such file or directory
            lxc 20170307110828.848 ERROR    lxc_namespace - namespace.c:lxc_clone:67 - Failed to clone (0x3c020000): Invalid argument.
            lxc 20170307110828.848 ERROR    lxc_start - start.c:lxc_spawn:1149 - Invalid argument - Failed to clone a new set of namespaces.
            lxc 20170307110828.959 WARN     lxc_conf - conf.c:lxc_delete_network:3038 - Failed to remove "veth7AC5EN" from host: Invalid argument.
            lxc 20170307110828.960 ERROR    lxc_start - start.c:__lxc_start:1346 - Failed to spawn container "settling-quagga".
            lxc 20170307110829.653 ERROR    lxc_conf - conf.c:run_buffer:405 - Script exited with status 1.
            lxc 20170307110829.653 ERROR    lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "settling-quagga".
            lxc 20170307110829.653 ERROR    lxc_namespace - namespace.c:lxc_clone:67 - Failed to clone (0x10000000): Invalid argument.
            lxc 20170307110829.653 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/systemd//lxc/settling-quagga-1
            lxc 20170307110829.653 ERROR    lxc_namespace - namespace.c:lxc_clone:67 - Failed to clone (0x10000000): Invalid argument.
            lxc 20170307110829.653 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/net_cls//lxc/settling-quagga-1
            lxc 20170307110829.654 ERROR    lxc_namespace - namespace.c:lxc_clone:67 - Failed to clone (0x10000000): Invalid argument.
            lxc 20170307110829.654 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/memory//lxc/settling-quagga-1
            lxc 20170307110829.654 ERROR    lxc_namespace - namespace.c:lxc_clone:67 - Failed to clone (0x10000000): Invalid argument.
            lxc 20170307110829.654 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/cpu//lxc/settling-quagga-1
            lxc 20170307110829.654 ERROR    lxc_namespace - namespace.c:lxc_clone:67 - Failed to clone (0x10000000): Invalid argument.
            lxc 20170307110829.654 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/blkio//lxc/settling-quagga-1
            lxc 20170307110829.654 ERROR    lxc_namespace - namespace.c:lxc_clone:67 - Failed to clone (0x10000000): Invalid argument.
            lxc 20170307110829.654 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/devices//lxc/settling-quagga-1
            lxc 20170307110829.654 ERROR    lxc_namespace - namespace.c:lxc_clone:67 - Failed to clone (0x10000000): Invalid argument.
            lxc 20170307110829.654 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/freezer//lxc/settling-quagga-1
            lxc 20170307110829.657 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - Command get_cgroup failed to receive response: Connection reset by peer.

**Comment by brauner** [comment]
Hm, this looks like your kernel is lacking user namespace support. Can you please try running `sudo unshare -U` and report back?

**Comment by brauner** [comment]
Or the flag value for `CLONE_NEWUSER` is different on arm.

**Comment by ljy5490** [comment]
@brauner Thank you for your help!
When I try `sudo unshare -U`:
`unshare: unshare failed: Invalid argument`

**Comment by brauner** [comment]
Np, can you please show the output of:
```
cat config-$(uname -r) | grep CONFIG_USER_NS
```

**Comment by ljy5490** [comment]
`cat: config-4.4.38-v7+: No such file or directory`

**Comment by ljy5490** [comment]
Does it means that my kernel is lacking user namespace support?

**Comment by brauner** [comment]
The missing config is not an indicator itself. But yeah, `invalid argument` usually means that user namespaces are not supported by your kernel otherwise I'd expect something like `EPERM` to show up.

**Comment by brauner** [comment]
So from the LXD side there is nothing much we can do. The `0x10000000` is the value of the `CLONE_NEWUSER` flag.

**Comment by ljy5490** [comment]
OK, Thanks a lot for your help!
