### ISSUE TITLE
lxd should error out at startup if setfacl is not available

### ISSUE THREAD

**Issue by BarthV** [lxc/lxd#305]
Using latest LXD on Ubuntu 14.04 (commit aead4dd66204de0eb77d09f1191f74ceb1ecfc69) : 
* ubuntu precise 64 image imported with ```lxd-images``` script
* vm1 log : https://gist.github.com/BarthV/1056f07a5ae6799e235f

```bash
> lxc launch ubuntu-precise-64 vm1
Creating container...done
Starting container...done
error: starting the container failed
```

```
  lxc_container 1425374283.454 ERROR    lxc_conf - conf.c:mount_rootfs:866 - Permission denied - failed to get real path for '/var/lib/lxd/lxc/vm1/rootfs'
```
According to https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1277466 it was a unix acl issue
Seems that ```/var/lib/lxd/lxc/vm1``` folder is created with 700 rights.

After a ```chmod +x /var/lib/lxd/lxc/vm1``` , vm1 started well :
```bash
> lxc start vm1
> lxc list
vm1: RUNNING
> lxc exec vm1 hostname
vm1
```

**Comment by hallyn** [comment]
What did getfacl /var/lib/lxd/lxc/vm1 and
getfacl /var/lib/lxd/lxc/vm1/rootfs show?

Were you running lxd as root?

lxd adds an acl for your container root to descend /var/lib/lxd/lxc
and creates /var/lib/lxd/lxc/rootfs owned by the container root,
so the chmod *should* not have been necessary.  We should
figure out what happened.

**Comment by BarthV** [comment]
You just hit me hard ...

```bash
> getfacl /var/lib/lxd/lxc/test1
The program 'getfacl' is currently not installed. You can install it by typing:
apt-get install acl
```

```apt-get install acl``` just fix this ... I didn't see this prerequisite anywhere but now it works perfectly !

Thanks alot.

**Comment by hallyn** [comment]
Hm, maybe lxd should check for it on startup, as it is
apparently quite important :)

**Comment by tych0** [comment]
Can we just use a syscall so we don't need the binary?

**Comment by stgraber** [comment]
Yeah, we should be avoiding shelling out to binaries whenever possible. Not sure how easy it is for filesystem acls though, I expect the interface to be quite complicated (due to how complicated FS ACLs are).
