### ISSUE TITLE
lxc stop waits indefinitely 

### ISSUE THREAD

**Issue by sidxz** [lxc/lxd#3050]
# lxc info
 * Distribution:
 * Distribution version: 2.6.2
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
architectures:
  - x86_64
  - i686
driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.1.12-61.1.18.el7uek.x86_64
  server: lxd
  serverpid: 194945
  serverversion: 2.6.2
  storage: zfs

# Issue description

I have encountered a strange behavior in which lxc stop command waits indefinitely. In another window issuing any lxc command (like lxc info) succeeds and also releases the previous lxc command (which now succeeds).

I have seen this behavior mostly after copying a container to a different host using  'lxc copy'. This happens on the second host during the first start/stop.

Any help?

**Comment by stgraber** [comment]
Any chance you can try to reproduce this with liblxc 2.0.7 (instead of 2.0.6) and LXD 2.11 (instead of 2.6.2)?

liblxc 2.0.7 fixes a number of multi-threading issues that could explain your hangs and LXD has similarly received a great number of fixes since 2.6.2.

**Comment by FransM** [comment]
This could well be the same issue as I had and reported here:
https://github.com/lxc/lxd/issues/2947
At least the symptoms are greatly alike.

sidxz you could try to log into the container after the failing stop command and see with ps what the state is. it is also useful to peek into the container syslog.

I also reported it here: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1668049?comments=all
but unfortunately nothing happened yet.

**Comment by stgraber** [comment]
@FransM what seems different here is that the reporter says that running "lxc info" unsticks the "lxc stop", which would be very inconsistent with systemd failing to stop the container.

**Comment by FransM** [comment]
Hm yes you are right.

**Comment by sidxz** [comment]
Thank you.
Will test this soon.

**Comment by Laguna-x** [comment]
driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-66-generic
  server: lxd
  server_pid: 4833
  server_version: "2.11"

sometimes "lxc stop" freezes. but container is stopped.
cant' reproduce this by any things. tried most of what i did before it happens, but nothing repeats this.
when it happens i'm just pressing ctrl+c and continue normal work processes.

**Comment by stgraber** [comment]
@Laguna-x this is unrelated to this issue and most likely just a problem with the init system in your container not setting up its shutdown handler properly.

This issue is special in that "lxc info" or similar LXD command will unstick it, hinting that it's an actual LXD problem.

**Comment by Laguna-x** [comment]
i catched some one like this:
when container is running i did 'dd if=backeduped_image of=/dev/pool/container'. next lxc stop waits indefinitely. when i pressed ctrl-c - command terminates but container still running.
only 'service lxd stop' unstucked it (when runs lxc stop container) and container finaly stopped. next start|stop was fine.

**Comment by brauner** [comment]
@Laguna-x, is this a `Debian Jessie` container from issue ttps://github.com/lxc/lxd/issues/3178? If so this is completely unrelated and see my comment https://github.com/lxc/lxd/issues/3178#issuecomment-296163319.

**Comment by Laguna-x** [comment]
@brauner yes debian, but it stucked <b>only</b> when i did dd with container. after lxd was restarted - container stops and starts well (with no stuck). may be something goes wrong inside container, but about lxd - stopping works fine now without waitings (checked most times).

**Comment by brauner** [comment]
Whether the systemd signal handler in a Debian Jessie container is correctly setup before systemd completely freezes is pure chance iirc. So you might get lucky, you might not.
