### ISSUE TITLE
Working LXD API but Google Chrome interprets endpoint as 'Not Secure'

### ISSUE THREAD

**Issue by edendekker** [lxc/lxd#3060]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-64-generic
   * LXC version: driverversion: 2.0.7
   * LXD version: serverversion: 2.0.9
   * Storage backend in use: zfs
* The output of "lxc config show"
```
  config:
  core.https_address: 10.0.0.13:8443
  core.https_allowed_headers: Origin, X-Requested-With, Content-Type, Accept
  core.https_allowed_methods: GET, POST, PUT, DELETE, OPTIONS
  core.https_allowed_origin: '*'
  storage.zfs_pool_name: lxd
```
# Issue description
I use my own CA authority. I have generated a root and intermediate CA cert. I have installed these on my browser keychain. Using a different daemon server (nodejs http-server), i configured it to serve requests to my client browser using https. With http-server pointing to server certs generated by my intermediate cert and intermediate key, i get i nice green padlock in google chrome. Command line - http-server -S -a 10.0.0.13 -p 8000 --cert ~/lxd-cert/10.0.0.13.cert.pem --key ~/lxd-cert/10.0.0.13.key.pem

However, when i shutdown http-server, add 10.0.0.13.cert.pem to lxd's trust, restart lxd service, and when i try to access lxd api https://10.0.0.13:8443/1.0 I get a nice json response. LXC-WebGUI is able to read and post to the lxd json api. However, google chrome shows a red 'Not Secure' sign in the address bar when i view lxd api  https://10.0.0.13:8443/1.0 . What this does is cause the entire client side javascript LXC-WebGUI app to change from green padlock to red unsecured padlock. This is because a website with mixed unsecure and secure times is considered not secure.

Since both http-server cert and lxd trust cert are the same, i am expecting the client browser to show green padlocks for both server daemons. Since the lxd api is working fine and encrypting, and it is only chrome invalidating the cert, is this a bug or just an unsupported feature? 

# Steps to reproduce
 1. Create you CA server by following - https://jamielinux.com/docs/openssl-certificate-authority/
 2. You should now have a root CA and intermediate CA cert installed in your browser key chain
 3. Install server cert into lxd and make sure Common Name in cert matches the URL of how you access the api eg. 10.0.0.13
```
sudo lxc config trust add 10.0.0.13.cert.pem
sudo lxc config trust list
sudo service lxd restart
```
4. Access https://10.0.0.13:8443/1.0
5. You get a red 'Not Secure' sign in google chrome with below response - 
'
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{"config":{"core.https_address":"10.0.0.13:8443","core.https_allowed_headers":"Origin, X-Requested-With, Content-Type, Accept","core.https_allowed_methods":"GET, POST, PUT, DELETE, OPTIONS","core.https_allowed_origin":"*","storage.zfs_pool_name":"lxd"},"api_extensions":["id_map"],"api_status":"stable","api_version":"1.0","auth":"trusted","public":false,"environment":{"addresses":["10.0.0.13:8443"],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\nMIIFXDCCA0SgAwIBAgIRAO5KkgWfgo6A0CiA93nzZT8wDQYJKoZIhvcNAQELBQAw\nNzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEXMBUGA1UEAwwOcm9vdEBi\nYXNlc3RhY2swHhcNMTcwMzA1MDgyODA5WhcNMjcwMzAzMDgyODA5WjA3MRwwGgYD\nVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRcwFQYDVQQDDA5yb290QGJhc2VzdGFj\nazCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALf5eyg4fNwRMDq5NyMe\nibfPxQkRb3xk/cJKIpEc9gmFK4sWu6SRB4AJhg6RvUBH5G9cI7UI4OkojFJhHNtp\n0ijtV+yW/qofnPAoMo9IgSharbGlfBGnv6O3ABqBoKGVDesJY7oSetYcK58q9vJF\n/NU011FAcug9V5Pqlj9WGWzgDMYG46eFdns0L/cnCSQRa1urTKBOU3wOamjoV5pY\nJnQz3bAY0afdbOIiqcJ/LECG9v6A39w44Q61ZQMkz6Mc9U+PxZ+cn7UDLnVXykvA\nTIZQBD2S3uXBmbqqG2JYHdC3gfEnoSdGNa3rXQsOkmP5xJrNBCV09yL9WE2UPT2T\nz2sWEqBMeY4csBb1TVmjmKYSxF5mV+zf04v5PYBji10PXnlFaxWdC7bq8aTIlDq3\nOybmf/3nATZMDuT8zsiILa6KP40dJbb8/9Rt6Mgo9wqsHQtNdsSGZ9PBiZ4ueuBn\nsdMvz22Ql9ANxXoNErQlPueHSe1H6+f7gbGIWzBoUjDVclk/ggs0RdATfOsUJIJ3\nn3H5RYY6tfLL5Zd28LWswxOW+abBSak1v+ESfo7bDF8WMmWWVsw3DieI6989x2fM\nAI6kwUduhS796EL3lPInw32B61XUvVtfSrEevZi2NuIeKeQ93GoBjNav857RJWYi\nNlCcT5qfzvvIV9joLDQbhzaRAgMBAAGjYzBhMA4GA1UdDwEB/wQEAwIFoDATBgNV\nHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMCwGA1UdEQQlMCOCCWJhc2Vz\ndGFja4cECgAAP4cQIAGAA2ibNgAKACf//jSjLDANBgkqhkiG9w0BAQsFAAOCAgEA\nQeX9q0OJ8E+wzj1nm0uFWfzI65vhDTOb5mZzeWt1Vi3eBf7lqBre0u6AREV5QqL1\nXw+5e3phnDSvRyd7G3Bzir0gcbNM6htSyWqZvj76ur2YkInEtFs+pp+zRu16Z/ru\n0PRRzaMmsCw/BZJC2qpj5tuOQB3VZAaW183JoPzNQYXzbLjs+oXU8TloVQYOK4eO\ncsMG3Eca+cphUATcI6kobsZ5TEm1+ATi12Z0RL/9wvYK1YzeGUNpbfyD7VdoXkWk\nrITyO8iz3hdGVHmN6lOr+AzINztuHm6GHpljWFMclVTl69/uPgILapxUEOjcJ4+c\neoRjhJqCW9fc/D/k7T24mOzOMkePo82r2rIL6ZpbNFdtvd0a3kbFYqI/ESvJfY7i\nxvTP/4EmibWpZ8ugtgdioZ+cyeM3M/1mFVSvK5OEAnvsM9u23b0AbN5ouwG3GbSb\nRdUPbHw02NiRUTFkwaSNp4A42LSChFJFN8z6+Gy+Zn0YpslNghvgLukOTLVZu26C\niPuFpvJrWkGnxsmOf7cXA+QsEdxv7xeG9ukDj9jqe+Ax849VPSZgYxYfn10WNPNI\nmww5him50AETQqPo9gpjUGTPV4n6/W1YQl40MSuMI4jMVeCR2peg1CG9J42mIN+A\nU43FCOQAVUknCWdrIpAkNFUDxso1tEuxFu8vVIt+R30=\n-----END CERTIFICATE-----\n","certificate_fingerprint":"","driver":"lxc","driver_version":"2.0.7","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.4.0-64-generic","server":"lxd","server_pid":7507,"server_version":"2.0.9","storage":"zfs","storage_version":"5"}}}
'

I have verified the certs and they are valid. the server cert's Common Name matches the accessed url of 10.0.0.13 

# Information to attach
 - [ ] main daemon log (/var/log/lxd.log)
ip=10.0.0.45:52285 lvl=warn msg="rejecting request from untrusted client" t=2017-03-11T16:57:46+1000
ip=10.0.0.45:52314 lvl=warn msg="rejecting request from untrusted client" t=2017-03-11T16:59:26+1000

**Comment by stgraber** [comment]
What's chrome's reason for marking the connection unsafe? You can usually find out by getting into the developer tools (F12) and look at the security tab.

**Comment by stgraber** [comment]
I just did a quick check using a valid commercial certificate here and my local LXD daemon, validation works fine in my chrome browser, so whatever's happening to you is unlikely to be LXD's fault.

![screenshot from 2017-03-11 03-04-49](https://cloud.githubusercontent.com/assets/2230599/23821656/84e568d2-0607-11e7-82fd-abb4928b31a2.png)
