### ISSUE TITLE
Metadata metadata in Exec client

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3061]
I don't understand this
https://github.com/lxc/lxd/blob/689167874f5c7b0ce06b188fbde5c2b5ac20ea7f/client.go#L1541

LXC client sends post to LXD server, which returns Response immediately, because Exec is async. Returned Response contains Metadata, which is turned into Operation object, which in turn also contains Metadata, which for some reason should include "fds" fields with value being another map.

Where is that nested structure explained? Go is a typed language, so I would expect to find some definitions for exchange messages, but I don't see any definition - in Python I would call this monkeypatching style - when there is a container for anything and then magically there is a check for `fds` out of nowhere. I mean I am not against decoupled interfaces, but maybe there is a way to factor out communication protocol / messages into some structures / packets instead of checking for fields here and there ?

**Comment by stgraber** [comment]
The "metadata" field of an operation is defined to be free form, so can be any valid json object. So far for I think we've only ever made it a string list, null or a dict.

Details for what to expect as the metadata reply is documented in:
https://github.com/lxc/lxd/blob/master/doc/rest-api.md#10containersnameexec

We could probably do with unpacking that metadata to a Go struct and it's the approach I've been using so far when working on the new client library which will eventually replace client.go (see #1926)

Once I start working on background operations in the new client code, I will most likely add those standard metadata values as structs to shared/api and then use the json parser to unpack them from the operation data.
