### ISSUE TITLE
lxd 2.11 (32 bits) do not detect btrfs

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#3069]
# Required information

 * Distribution: ubuntu
 * Distribution version yakkety:
 * lxc info:

config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 172.16.99.16:8443
  - 172.17.10.1:8443
  - 172.17.22.1:8443
  - 172.17.11.1:8443
  - 172.17.12.1:8443
  architectures:
  - i686
   certificate_fingerprint: 7e36584daa9cab0e74d86b2e5b359d5c31e3a253db429576b450e0aaba768985
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: i686
  kernel_version: 4.8.0-41-generic
  server: lxd
  server_pid: 10313
  server_version: "2.11"
  storage: dir
  storage_version: "1"

# Issue description
Re-Installed lxd from scratch and btrfs is no more detected.

# Steps to reproduce

 1. apt purge lxd* (was 2.4.XX)
 2. added ppa:ubuntu-lxc/lxd-stable
 3. apt install lxd
 4. lxd init
 5. copied image (yakkety 32 bits): lxc image copy ...: asked me for creating a new storage. Answered 'dir'.
 6. created a container: creation was very slow
 7. btrfs sub list / din't shown anything new
 8. lxc info shown me that i was in 'dir' mode, not btrfs

**Comment by brauner** [comment]
With the new storage api work you need to tell `LXD` explicitly what storage driver you want to use. `LXD` will not just use a btrfs filesystem when it detects one. So if you want to create a btrfs storage pool in the `LXD` dir you would do:

```
lxc storage create pool1 btrfs source=/var/lib/lxd/storage-pools/pool1
```
Then, while you're at it, set the new pool as default storage pool in the default profile by doing:
```
lxc profile device add root disk path=/ pool=pool1
```
and finally launch a container to test.

**Comment by stgraber** [comment]
This will be made easier once #2986 is sorted out. Closing this one.

**Comment by gaetanquentin** [comment]
looks like commands are (for re-creating the default storage):

 lxc profile delete default
 lxc storage delete default
lxc storage create default btrfs source=/var/lib/lxd/storage-pools/default
 lxc profile create default
 lxc profile device add default root disk path=/ pool=default

**Comment by gaetanquentin** [comment]
lxc image copy images:2cfb63aa9b41 local: --copy-aliases
 -> why does this create a simple file rootf into the /var/lib/lxd/images directoriy, not a btrfs subvolume
and this:
lxc launch 4d574fd7ecf8 XXX
 create another copy in /var/lib/lxd/storage-pools/default/images as a btrfs subvolume, before creating the container?

the container creation is longer than before and cost more space

**Comment by brauner** [comment]
Things are similar to before but a couple of things have changed. The most obvious one being that storage volumes for images (e.g. btrfs subvolume) are created opportunistically, meaning only when they are actually needed to create containers. So when you do a `lxc image copy` `LXD` will merely import the tar files into the `/var/lib/lxd/images` directory but will not yet create a storage volume for the image (e.g. a btrfs subvolume). 
When you then do a `lxc launch` `LXD` will first create a storage volume (e.g. btrfs volume) for that image in the storage pool and then use the most efficient method for the given storage driver (Where a "storage driver" is e.g. btrfs, lvm, dir, zfs) to create a storage volume for the container from it. In the case of btrfs the method used is to create a btrfs snapshot from the storage volume for the image that was created in the pool before. So, on-disk you will find:

- tar files in `/var/lib/lxd/images`
- a storage volume (if containers where already created from it) for the image in `/var/lib/lxd/storage-pools/<pool-name>/images/<fingerprint>`
- a storage volume for the container (if one was created) in `/var/lib/lxd/storage-pools/<pool-name>/containers/<container-name>` and a corresponding symlink to this folder in `/var/lib/lxd/container/<container-name>`.
