### ISSUE TITLE
Question: Docker in LXD on ZFS

### ISSUE THREAD

**Issue by k-hristov** [lxc/lxd#3070]
Hi,

According to the storage backends documentation https://github.com/lxc/lxd/blob/master/doc/storage-backends.md
while using ZFS file system nesting is not supported.
LXD in LXD and docker in LXD are both considered as nesting.

Is there a way to run docker in LXD container which is running on ZFS file system?

**Comment by tomposmiko** [comment]
IMHO that information is obsolote.
Docker in LXD works just fine....though aufs driver is required.

**Comment by stgraber** [comment]
The information isn't obsolete, you can't nest ZFS itself.

That is, you can't use "zpool" or "zfs" from inside a container. You can nest containers inside a container that's on zfs, but as far as LXD or Docker is concerned, they'll be using a directory or overlay backend for their filesystem, not zfs.
