### ISSUE TITLE
Cannot remove deprecated storage configuration data

### ISSUE THREAD

**Issue by sbworth** [lxc/lxd#3073]
Ubuntu 16.04LTS
LXD 2.11

My older server had the following configuration entry from pre-storage-API days:

    storage.lvm_volume_size: 40GB

The configuration editor recognizes ``storage.lvm_volume_size`` as a deprecated key and refuses to allow one to add it to a new system, but it ALSO refuses to let one remove it from an older system that has been upgraded to 2.11.

**Comment by stgraber** [comment]
Do you get that when doing "lxc config unset storage.lvm_volume_size" too?

**Comment by stgraber** [comment]
Hmm, so I also have some version of this here:
```
config:
  storage.zfs_pool_name: castiana/lxd
```

@brauner wasn't all of those supposed to be cleared after upgrade?

**Comment by stgraber** [comment]
But at least unset works here:
```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc config unset storage.zfs_pool_name
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc config show
config: {}
```

**Comment by stgraber** [comment]
And "lxc config edit" similarly let me remove that one.

**Comment by brauner** [comment]
Yes, if the `storage_api` patch was run successfully it will call:

	// Unset deprecated storage keys.
	daemonConfig["storage.lvm_fstype"].Set(d, "")
	daemonConfig["storage.lvm_mount_options"].Set(d, "")
	daemonConfig["storage.lvm_thinpool_name"].Set(d, "")
	daemonConfig["storage.lvm_vg_name"].Set(d, "")
	daemonConfig["storage.lvm_volume_size"].Set(d, "")
	daemonConfig["storage.zfs_pool_name"].Set(d, "")
	daemonConfig["storage.zfs_remove_snapshots"].Set(d, "")
	daemonConfig["storage.zfs_use_refquota"].Set(d, "")

if somehow this didn't succeed than you should be able to unset it with the methods you described.

**Comment by stgraber** [comment]
@brauner Should we maybe add another patch in LXD 2.12 which clears them all again for those who ran into upgrade problems before?

**Comment by brauner** [comment]
Sure, can send a patch.

**Comment by stgraber** [comment]
@sbworth Can you show us what "lxc config unset storage.lvm_volume_size" does for you?

I want to make sure we don't have another problem since I can't actually reproduce the error you're getting so long as I'm only unsetting/removing them. Setting them to anything else would indeed trigger the error.

**Comment by sbworth** [comment]
root@sys2:~# lxc config unset storage.lvm_volume_size
    error: Setting the key "storage.lvm_volume_size" is deprecated in favor of storage pool configuration.

**Comment by stgraber** [comment]
Oh, I think I see the problem.
