### ISSUE TITLE
options in rest api for files (e.g. recursive)

### ISSUE THREAD

**Issue by FransM** [lxc/lxd#3075]
Hi,

I want to copy a directory tree to my container.
On the command line I can do that with lxc file push -r localdir container/remotedir
However I want to do this using the REST API.

According to the REST API doc I can only copy a file.
It would be nice also to be able to copy a complete directory tree (and also have an equivalent to the -p option). 

(or if these exist, it would be nice to see this mentioned in the REST API documentation). 

Thanks & keep up the good work!

**Comment by stgraber** [comment]
The client tool uses the REST API, so everything it does can be done with the API.

To implement -p, our client simply causes all directories in the source path to be created on the target by doing a POST for each separate part of the path with X-LXD-type set to "directory".

For recursion, it's a combination of X-LXD-type set to "directory" for the directories leading to the files and "file" for the files themselves. Doing one REST POST for each of those.

Looks like we should document X-LXD-type as valid for POST. I'll send a branch for that.
