### ISSUE TITLE
Use of LXD_DIR to change lxd directory breaks upstart job on Trusty backport

### ISSUE THREAD

**Issue by volkerwestphal** [lxc/lxd#3078]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * Kernel version: 4.4.0-64-generic
 * LXC version:  2.0.7
 * LXD version:  2.0.9
 * Storage backend in use: btrfs

# Issue description

Installed lxd 2.0.9 via trusty-backports on a virtual Ubuntu 14.04 for testing purposes. The mountpoint /var contains is not suitable to hold container images, but a dedicated btrfs subvolume /data/store/container is. Added LXD_DIR=/data/store/container to /etc/environment to point lxd there.

**First issue:** the included upstart job /etc/init/lxd.conf only reads environment variables from /etc/environment in the "script" section, but it does not in the other sections where lxc is called (post-start and pre-stop).  Because of that, a "service lxd start" starts a working instance of the lxd daemon, but waits 30 seconds looking in the wrong directory for the unix socket. More importantly, "service lxd stop" is unable to stop lxd for the same reason. 

**Second issue:** The /etc/environment usually includes environment variables without an explicit export statement in front of the variable's name. Simply sourcing this file does not lead to an exported LXD_DIR. 

I worked around both issues by adding a line 

    env LXD_DIR=/data/store/containers

to the upstart file /etc/init/lxd.conf.

**Comment by stgraber** [comment]
I'll take a look at making the upstart job respect /etc/environment a bit more, though note that the reason we source /etc/environment is to load the proxy servers rather than allow LXD_DIR to be set through there.

In general, people have been getting better results by using a bind-mount over /var/lib/lxd or if using recent versions of LXD, just use the storage API to define your storage pools whichever way you want.

**Comment by stgraber** [comment]
So going to be closing this.

The reason why we source /etc/environment is for the proxy variables, to align the behavior with sysvinit and systemd. It's not meant to set an alternate LXD_DIR.

When using packages, we recommend not setting an alternate LXD_DIR as things like the packaging scripts very much assume that LXD is under /var/lib/lxd.

If you want to have /var/lib/lxd somewhere else, use a bind-mount instead, which is far better supported.

Alternatively, starting with LXD 2.9 (feature branch), you can use the new storage pool API to define storage pools at any location you want on the system.
