### ISSUE TITLE
Add Remote Flow

### ISSUE THREAD

**Issue by jensg-st** [lxc/lxd#308]
I looked at the spec and the following happened, so I'm not sure if that is how it supposed to work:

`lxc remote add demo 127.0.0.1`

Then I get the fingerprint. If I accept and enter a random password, I would assume, that the cert is not getting stored? But if I ran the exact command again, it says the certificate has already been stored. 

I know that it still wouldn't help to get access, because the server didn't store the "client" cert as trusted and would reply with untrusted again. But maybe the remote cert should not be added in the first place, if I can't satisfy the requirements?

I noticed that the client sends a second get request to the server ("/1.0") after accepting the fingerprint. But then the password input comes. Is the second get request required? We can not be a trusted client and the info that we need to provide a password is in the first get request already. 

I can dig through the code to understand it better, but maybe you can shed some light on it.

**Comment by tych0** [comment]
Can you give an example of the output? I'm a little confused by your description. Is it saying that the client already had the server cert, instead of the other way around?

**Comment by jensg-st** [comment]
I'm not grandmaster of explanation maybe :)

Let's say we have host1 and host2 and I want to have host2 trusting host1. So I run the 'remote add' command. Host2 shows the fingerprint and I accept it. Then host2 asks for the password. Let's assume, I don't know it, so I either cancel or enter some bogus password. Then I run the command again and host1 is telling me, the certificate has already been stored. Maybe I misread the spec, but the questions are:

1. If I don't know the password, is it by design that host1 stores the cert under the remote name, despite not knowing host2's password?

2. Did I misread the spec?

```
./lxc remote add helloworld host2:6430
Certificate fingerprint: bb 4c 2a 7a 61 57 b3 ee ae a4 16 12 aa 0e 49 3b 2a e3 48 14 e6 25 3b c3 ef 01 de 82 a6 6d 6f 73
ok (y/n)? y
Admin password for helloworld: 
./lxc remote add helloworld host2:6430
Certificate already stored.
Admin password for helloworld: 
```

**Comment by jensg-st** [comment]
Ok, half of what I said is rubbish after going through the source, so you can close it I guess. It is more a question of opinion rather than a bug. Just an explanation, so I don't look too stupid :)

In remote.go:

```
func addServer(config *lxd.Config, server string) error {
	
	fmt.Println(server)
	remote := config.ParseRemote(server)
	fmt.Println(remote)
	fmt.Println(config)
	c, err := lxd.NewClient(config, remote)
	if err != nil {
		return err
	}

	err = c.UserAuthServerCert()
	if err != nil {
		return err
	}
```

The UserAuthServerCert() call is actually storing the cert in my home folder `/.config/lxc/servercerts`

The I enter the admin password and it gets posted with the cert to the server. If my admin password is wrong, it returns `Forbidden` and the lxc cert is not added to the remote. 

I was just expecting that the certificate in `/.config/lxc/servercerts` would be deleted after the add of the cert failed. But maybe that is what you wanted to check if the certificate has changed and that is, as far as I know, how 'known_hosts' in SSH works. I just did not expect that behaviour.  

So, forget everything, except good morning. :) Issue can be closed.

**Comment by stgraber** [comment]
Right, per specs/lxd-ssl-authentication.md we try to offer an ssh-like experience. The server fingerprint validation is separate from the password validation, so once you say yes to the fingerprint, the certificate is added to the client's trust store, then a second query is done to add the client's certificate to the server's trust store. That's the step which may prompt for a password and where if it fails, a re-try will not ask for the fingerprint again, just the password.

I think our current behavior is correct, however maybe the messaging back to the user in the client is confusing and could be improved somehow?

**Comment by jensg-st** [comment]
I think if you want to be close to ssl, nothing should be printed to stdout if the cert has been stored already. Feels like something is wrong. If there are issues like different fingerprint, ssl usually tells you how to fix it like 'delete xyz from known_hosts'.

**Comment by stgraber** [comment]
Yeah, that sounds reasonable to me.

**Comment by stgraber** [comment]
Will you send a branch for it?

**Comment by jensg-st** [comment]
Yes, will do. Seems like an easy solution.
