### ISSUE TITLE
lxc 1.09: lxc-ls dumps core

### ISSUE THREAD

**Issue by FransM** [lxc/lxd#3080]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.0.05 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.13
   * LXC version: 1.09
   * LXD version: n/a
   * Storage backend in use: aufs

# Issue description

lxc-ls -f dumps core:
tst_lxcls: line 21: 42539 Segmentation fault      (core dumped) lxc-ls -f > /tmp/lxcls

# Steps to reproduce

I had a hunch we had a problem with lxc-ls so I ran a while loop on the host continuously doing
lxc-ls -f on our production machine on which containers are regularly created and destroyed.
After a few hours lxc-ls crashed
# Information to attach

I dont know if this is related but sometimes I see this in syslog:
Mar 16 15:28:46 LXC-Master kernel: [872235.860763] aufs au_plink_put:454:lxc-start[100777]: pseudo-link is not flushed

lxc-monitord only cointains lines like this one:
  lxc-monitord 1489674650.149 NOTICE   lxc_monitord - lxc_monitord.c:main:416 - pid:28162 monitoring lxcpath /var/lib/lxc
   lxc-monitord 1489674686.064 NOTICE   lxc_monitord - lxc_monitord.c:main:421 - no remaining clients, exiting
   lxc-monitord 1489674686.064 NOTICE   lxc_monitord - lxc_monitord.c:main:429 - monitor exiting

apport.log says:
ERROR: apport (pid 42558) Thu Mar 16 15:15:32 2017: called for pid 42539, signal 11, core limit 0
ERROR: apport (pid 42558) Thu Mar 16 15:15:32 2017: script: /usr/bin/lxc-ls, interpreted by /usr/bin/python3.4 (command line "/usr/bin/python3 /usr/bin/lxc-ls -f")
ERROR: apport (pid 42558) Thu Mar 16 15:15:32 2017: is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
ERROR: apport (pid 42558) Thu Mar 16 15:15:32 2017: apport: report /var/crash/_usr_bin_lxc-ls.0.crash already exists and unseen, doing nothing to avoid disk usage DoS

Attached is the crash log
[crash.zip](https://github.com/lxc/lxd/files/848010/crash.zip)

**Comment by stgraber** [comment]
Can you file this at https://github.com/lxc/lxc since that's a LXC bug rather than a LXD one?

**Comment by FransM** [comment]
Of course, sorry about submitting in the wrong tracker
