### ISSUE TITLE
How to set MAC address in macvlan environment?

### ISSUE THREAD

**Issue by jemxpat** [lxc/lxd#3083]
I am running LXD 2.4.1 on Ubuntu 16.10 server. All containers use the default config, with macvlan network connection to the physical interface. All working well.

I would like to be able to set the MAC address for each container. When I try setting volatile.eth0.hwaddr, container startup fails. Presumably, this is a permissions problem somewhere.

error: Error calling 'lxd forkstart bb-192-168-131-001 /var/lib/lxd/containers /var/log/lxd/bb-192-168-131-001/lxc.conf': err='exit status 1'
  lxc 20170317070929.442 ERROR lxc_conf - conf.c:setup_hw_addr:2223 - ioctl failure : Cannot assign requested address
  lxc 20170317070929.442 ERROR lxc_conf - conf.c:setup_netdev:2340 - failed to setup hw address for 'eth0'
  lxc 20170317070929.442 ERROR lxc_conf - conf.c:setup_network:2467 - failed to setup netdev

Am I missing something obvious?

-jem

**Comment by stgraber** [comment]
It's not a permission problem, it's the kernel telling you the MAC isn't valid.

Can you paste "lxc config show --expanded bb-192-168-131-001" and the content of /var/log/lxd/bb-192-168-131-001/lxc.conf?

**Comment by jemxpat** [comment]
The MAC address I tried to use is 11:11:C0:A8:83:01. It seems properly formatted.
-jem

# lxc config show --expanded bb-192-168-131-001
name: bb-192-168-131-001
profiles:
- default
config:
  volatile.base_image: 2cab90c0c342346ea154bc2e8cacdae752a70747a755ce1f2970c9a9ebb5fe8c
  volatile.eth0.hwaddr: 11:11:C0:A8:83:01
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: enp1s0
    type: nic
  root:
    path: /
    type: disk
ephemeral: false

--

# cat lxc.conf
lxc.cap.drop = sys_time sys_module sys_rawio
lxc.mount.auto = proc:rw sys:rw
lxc.autodev = 1
lxc.pts = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/security sys/kernel/security none rbind,create=dir,optional
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional
lxc.include = /usr/share/lxc/config/common.conf.d/
lxc.logfile = /var/log/lxd/bb-192-168-131-001/lxc.log
lxc.loglevel = 0
lxc.arch = linux64
lxc.hook.pre-start = /usr/bin/lxd callhook /var/lib/lxd 943 start
lxc.hook.post-stop = /usr/bin/lxd callhook /var/lib/lxd 943 stop
lxc.tty = 0
lxc.utsname = bb-192-168-131-001
lxc.mount.entry = /var/lib/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.aa_profile = lxd-bb-192-168-131-001_</var/lib/lxd>//&:lxd-bb-192-168-131-001_<var-lib-lxd>:
lxc.seccomp = /var/lib/lxd/security/seccomp/bb-192-168-131-001
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.network.type = macvlan
lxc.network.macvlan.mode = bridge
lxc.network.flags = up
lxc.network.link = enp1s0
lxc.network.hwaddr = 11:11:C0:A8:83:01
lxc.network.name = eth0
lxc.rootfs.backend = dir
lxc.rootfs = /var/lib/lxd/containers/bb-192-168-131-001/rootfs
lxc.mount.entry = /var/lib/lxd/shmounts/bb-192-168-131-001 dev/.lxd-mounts none bind,create=dir 0 0

--

**Comment by jemxpat** [comment]
When I change the first 2 bytes to be 00:00, it works fine. Thanks!

**Comment by stgraber** [comment]
Right, your MAC had an invalid prefix.
