### ISSUE TITLE
lxd  : lxc copy between remotes do not work if remotes are not declared on unix root account

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#3085]
on both sides:

config:
  core.https_address: :8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - :8443
  architectures:
  - x86_64
  - i686
  certificate: |

  certificate_fingerprint: ea854278d6e269bb441c2b59b3407ff2a90459486478cefc439d9750e3b2afd9
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-66-generic
  server: lxd
  server_pid: 4755
  server_version: "2.11"
  storage: btrfs
  storage_version: "4.4"

# Issue description
lxc copy remote:XX remote2:

error: Error transferring container data: lookup : no such host

remotes bust be created on root account, on both sides

# Steps to reproduce

 1. adding remotes:

on both sides:
 from account X on remote1, from account Y on remote2:

 lxc remote add remote1-vpn https://remote1-vpn:8443 -> remote1 is localhost with vpn ip: so no network confusion when copying on vpn network on multi ip machines
 lxc remote add remote2-vpn https://remote2-vpn:8443 (ip of a real remote host on the vpn)

 2. test the remotes:
on both sides:

lxc list remote1-vpn: ->works
lxc list remote2-vpn:  -> works
lxc exec remote2-vpn:container1 bash -> works

 3. copy the container:
lxc copy remote1-vpn:my-container remote2-vpn:

error: Error transferring container data: lookup : no such host

# Information to attach

on remote2 side:
/var/log/lxd.log:
ephemeral=false lvl=info msg="Creating container" name=mycontainer t=2017-03-17T14:05:21+0100
ephemeral=false lvl=info msg="Created container" name=mycontainer t=2017-03-17T14:05:21+0100
lvl=warn msg="Unable to update backup.yaml at this time." name=mycontainer t=2017-03-17T14:05:21+0100
lvl=warn msg="Unable to update backup.yaml at this time." name=mycontainer t=2017-03-17T14:05:21+0100
err="lookup : no such host" lvl=eror msg="Error during migration sink" t=2017-03-17T14:05:21+0100
created=2017-03-17T13:05:21+0000 ephemeral=false lvl=info msg="Deleting container" name=mycontainer t=2017-03-17T14:05:21+0100 used=1970-01-01T00:00:00+0000
created=2017-03-17T13:05:21+0000 ephemeral=false lvl=info msg="Deleted container" name=mycontainer t=2017-03-17T14:05:21+0100 used=1970-01-01T00:00:00+0000

  -> the remote name is not present on the err line.

on remote1 side:
debug output:
DBUG[03-17|13:28:53] Found cert                               k=2
DBUG[03-17|13:28:53] handling                                 ip=10.8.0.6:43698 method=GET url=/1.0/containers/mycontainer
DBUG[03-17|13:28:53] 
	{
		"type": "sync",
		"status": "Success",
		"status_code": 200,
		"operation": "",
		"error_code": 0,
		"error": "",
		"metadata": {
			"architecture": "x86_64",
			"config": {
				"volatile.base_image": "f27ed1c7fad89d5ece8a0f5adfea517cde6ee6e27a259ee0976fdcc6c05941aa",
				"volatile.eth0.hwaddr": "00:16:3e:3a:73:a5",
				"volatile.eth1.hwaddr": "00:16:3e:f1:9c:db",
				"volatile.eth2.hwaddr": "00:16:3e:3d:3f:9f",
				"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":362144,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":362144,\"Nsid\":0,\"Maprange\":65536}]",
				"volatile.last_state.power": "STOPPED",
				"volatile.root.hwaddr": "00:16:3e:84:8e:6f",
				"volatile.root.name": "eth3"
			},
			"devices": {
				"root": {
					"path": "/",
					"pool": "default",
					"type": "disk"
				}
			},
			"ephemeral": false,
			"profiles": [
				"front"
			],
			"created_at": "2016-11-28T15:55:10Z",
			"expanded_config": {
				"volatile.base_image": "f27ed1c7fad89d5ece8a0f5adfea517cde6ee6e27a259ee0976fdcc6c05941aa",
				"volatile.eth0.hwaddr": "00:16:3e:3a:73:a5",
				"volatile.eth1.hwaddr": "00:16:3e:f1:9c:db",
				"volatile.eth2.hwaddr": "00:16:3e:3d:3f:9f",
				"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":362144,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":362144,\"Nsid\":0,\"Maprange\":65536}]",
				"volatile.last_state.power": "STOPPED",
				"volatile.root.hwaddr": "00:16:3e:84:8e:6f",
				"volatile.root.name": "eth3"
			},
			"expanded_devices": {
				"eth0": {
					"name": "eth0",
					"nictype": "bridged",
					"parent": "lxdbr0",
					"type": "nic"
				},
				"eth1": {
					"name": "eth1",
					"nictype": "bridged",
					"parent": "lxdbr1",
					"type": "nic"
				},
				"eth2": {
					"name": "eth2",
					"nictype": "bridged",
					"parent": "lxdbr2",
					"type": "nic"
				},
				"root": {
					"path": "/",
					"pool": "default",
					"type": "disk"
				}
			},
			"name": "mycontainer",
			"stateful": false,
			"status": "Stopped",
			"status_code": 102,
			"last_used_at": "2017-03-08T13:05:03.94286815Z"
		}
	} 
DBUG[03-17|13:28:53] Found cert                               k=2
DBUG[03-17|13:28:53] handling                                 ip=10.8.0.6:43702 method=POST url=/1.0/containers/mycontainer
DBUG[03-17|13:28:53] 
	{
		"migration": true
	} 
DBUG[03-17|13:28:53] New websocket operation: 6cd1ff6d-8363-45b9-b08d-7a1053a667bc 
DBUG[03-17|13:28:53] Started websocket operation: 6cd1ff6d-8363-45b9-b08d-7a1053a667bc 
DBUG[03-17|13:28:53] 
	{
		"type": "async",
		"status": "Operation created",
		"status_code": 100,
		"operation": "/1.0/operations/6cd1ff6d-8363-45b9-b08d-7a1053a667bc",
		"error_code": 0,
		"error": "",
		"metadata": {
			"id": "6cd1ff6d-8363-45b9-b08d-7a1053a667bc",
			"class": "websocket",
			"created_at": "2017-03-17T13:28:53.612280566+01:00",
			"updated_at": "2017-03-17T13:28:53.612280566+01:00",
			"status": "Running",
			"status_code": 103,
			"resources": {
				"containers": [
					"/1.0/containers/mycontainers"
				]
			},
			"metadata": {
				"control": "6f9295d42c6ff04b6397015cd93d924fa6488e218e7ac7021e3912f4d1058f54",
				"fs": "ae0975c0f7afc3324fd86f963df9abefcdaadd3c2ca10424deed7b88fe1b87b0"
			},
			"may_cancel": false,
			"err": ""
		}
	} 
DBUG[03-17|13:28:53] Found cert                               k=2
DBUG[03-17|13:28:53] handling                                 ip=10.8.0.6:43704 method=GET url=/1.0
DBUG[03-17|13:28:53] Found cert                               k=2
DBUG[03-17|13:28:53] Initializing a BTRFS driver. 
DBUG[03-17|13:28:53] 
	{
		"type": "sync",
		"status": "Success",
		"status_code": 200,
		"operation": "",
		"error_code": 0,
		"error": "",
		"metadata": {
			"config": {
				"core.https_address": ":8443",
				"core.trust_password": true
			},
			"api_extensions": [
				"storage_zfs_remove_snapshots",
				"container_host_shutdown_timeout",
				"container_syscall_filtering",
				"auth_pki",
				"container_last_used_at",
				"etag",
				"patch",
				"usb_devices",
				"https_allowed_credentials",
				"image_compression_algorithm",
				"directory_manipulation",
				"container_cpu_time",
				"storage_zfs_use_refquota",
				"storage_lvm_mount_options",
				"network",
				"profile_usedby",
				"container_push",
				"container_exec_recording",
				"certificate_update",
				"container_exec_signal_handling",
				"gpu_devices",
				"container_image_properties",
				"migration_progress",
				"id_map",
				"network_firewall_filtering",
				"network_routes",
				"storage",
				"file_delete",
				"file_append",
				"network_dhcp_expiry",
				"storage_lvm_vg_rename",
				"storage_lvm_thinpool_rename",
				"network_vlan",
				"image_create_aliases"
			],
			"api_status": "stable",
			"api_version": "1.0",
			"auth": "trusted",
			"public": false,
			"environment": {
				"addresses": [
					":8443"
				],
				"architectures": [
					"x86_64",
					"i686"
				],
				"certificate": "-----BEGIN 				"certificate_fingerprint": "",
				"driver": "lxc",
				"driver_version": "2.0.7",
				"kernel": "Linux",
				"kernel_architecture": "x86_64",
				"kernel_version": "4.4.0-66-generic",
				"server": "lxd",
				"server_pid": 4755,
				"server_version": "2.11",
				"storage": "btrfs",
				"storage_version": "4.4"
			}
		}
	}

**Comment by gaetanquentin** [comment]
looks like remote creation are "unix user dependant".

a remote created from unix account X won't be seen from account Y (lxc remote list)
it may be the problem

**Comment by gaetanquentin** [comment]
i had to declare remotes on the root account, on both sides, to make it work: it is normal?

**Comment by stgraber** [comment]
The LXD daemon doesn't have the concept of "remotes", so adding a remote to the root account on the target machine won't do anything.

    lookup : no such host

Suggests that your core.https_address is set to an odd value which the target host can't resolve.
Please show "lxc config show" for both source and target host.

**Comment by gaetanquentin** [comment]
remote 1:

lxc config show
config:
  core.https_address: :8443
  core.trust_password: true


remote 2:
lxc config show
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  images.auto_update_cached: "True"

**Comment by gaetanquentin** [comment]
Why remotes declared from X linux account are not shown in Y account?
"lxc remote list "from account Y won't show remotes created from account X.

As i said, since i declared the remotes on each root account , it works.

**Comment by gaetanquentin** [comment]
just seen that remotes are in .config/lxc/config.yml of each user account, not in sqlite database.

so which user account a remote lxd will use to read remotes list? i think root?

**Comment by stgraber** [comment]
The problem in your case is almost certainly that you're using ":8443" in remote 1 rather than "[::]:8443", that's causing a DNS resolution failure causing the error you're seeing.

So you can copy containers from remote 2 to remote 1 just fine, but the other way around would fail.

As I said before, LXD doesn't use the remotes in ~/.config/lxc at all, those are ONLY used by the command line client, the daemon only ever deals with https addresses sent by the client.

**Comment by gaetanquentin** [comment]
i deleted remotes declaration on remote2:  it works. 
the point is that both remotes but be declared on /etc/hosts or dns on each side.
if i unset /etc/hosts declarations on remote2, it does a "no such host".

**Comment by stgraber** [comment]
Right, that makes sense. Container copies are done by telling the target to connect to the source.

The URL passed is based is based on what the client was provided with fallback to the list of IPs the source server announces.

Closing this issue as the problem was indeed a missing entry in /etc/hosts of the target server, causing a DNS resolution failure which results in that "no such host" error (that's what Go returns for DNS failure).

**Comment by stgraber** [comment]
Note that these days you can also try --mode=push if the source server can talk to the target or --mode=relay to have the client tool relay all traffic. That latter should always work well, but may be slow as the client will relay all traffic.
