### ISSUE TITLE
Can't change network type

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#3092]
lxd 2.11 with openvswitch 2.5.0
```
ovs-vsctl add-br ovsbr0
ovs-vsctl add-port ovsbr0 bond0 trunk=10,11
ovs-vsctl add-port ovsbr0 lxd1 tag=10
lxc network create lxd1
```
all "show" shows that all works normal
but i trying to change type to macvlan in

> lxc network edit lxd1

and next opening lxd1's config shows that type returned to bridge.

does it changes automaticaly? 
ps/ ipv4 and ipv6 and nat changes normaly

**Comment by stgraber** [comment]
The type can't be changed. Only "bridge" type is modifiable in LXD.

If you want a bridge which is backed by OpenVswitch, you need to set the bridge.driver property to openvswitch instead (as documented in doc/configuration.md).

    lxc network set lxd1 bridge.driver openvswitch
