### ISSUE TITLE
Have yaml file examples actually be standard yaml

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#310]
It seems as though both lxd-images and the spec render metadata.yml in images as json. We should either change the file extension in the spec to .json, or actually put yaml in there.

**Comment by stgraber** [comment]
YAML is a superset of JSON. As python3 doesn't contain a native yaml parser/writer, I went with the easy alternative which is to just use the json parser/writer which happens to be compatible (I tested) with a regular YAML parser.

**Comment by tych0** [comment]
On Wed, Mar 04, 2015 at 07:52:52PM -0800, St�phane Graber wrote:
> YAML is a superset of JSON. As python3 doesn't contain a native yaml parser/writer, I went with the easy alternative which is to just use the json parser/writer which happens to be compatible (I tested) with a regular YAML parser.

Ok, can we switch our examples to normal looking yaml, though?

**Comment by stgraber** [comment]
Yep, I'll send an update.
