### ISSUE TITLE
Recreating a bridge that is in the database leads to bad behavior (lxd init)

### ISSUE THREAD

**Issue by larryprice** [lxc/lxd#3100]
# System Info

 * Distribution: zesty
 * Distribution version: latest
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-13-generic
   * LXD version: 2.12-0ubuntu1
   * Storage backend in use: zfs

# Issue description

Initializing lxd, deleting the created bridge on the system, and then reinitializing lxd leads to unexpected behavior. This started happening once the `network` subcommands were introduced.

# Steps to reproduce

 1. Run `lxd init` for the "first time" (or equivalent), accepting all the default options
 2. Delete "lxdbr0" (ip link set lxdbr0 down && brctl delbr lxdbr0)
 3. Run `lxd init`, attempting to accept all the default options

# Expectation

`lxd init` should succeed, recreating the bridge and attaching it to the default profile.

# Reality

lxd does create the bridge (surprise), but *then* complains that the bridge already exists because it's already in the database.

```
$ lxd init
...
What should the new bridge be called [default=lxdbr0]? 
The requested network bridge "lxdbr0" already exists. Please choose another name.
```

This message is misleading, and it seems that the database should synced up with the actual state of the system.

**Comment by brauner** [comment]
For `LXD` itself the bridge is never really deleted from it's db which is fine since you didn't call `lxc network delete lxdbr0` (At least not from what I can see here.). So `LXD` is right when it complains that the bridge exists when it tries to create it. @stgraber

**Comment by stgraber** [comment]
As @brauner said, we don't support people going behind LXD's back and deleting devices. If you want to delete the bridge, use "lxc network delete".

In your case, should you have restarted LXD or altered any property of the bridge through "lxc network edit", you'd have seen LXD re-create the interface. The same is true of libvirt, networkd, ifupdown, NetworkManager, ... we're hardly a unique snowflake here and the error is absolutely correct in that "lxc network list" would have reported the bridge to exist.
