### ISSUE TITLE
Ambiguous error messages when specifying a bad storage pool

### ISSUE THREAD

**Issue by CuriousBadger277** [lxc/lxd#3110]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * driver: lxc
   *  driver_version: 2.0.7
   * kernel: Linux
   * kernel_architecture: x86_64
   * kernel_version: 4.4.0-67-generic
   * server: lxd
   * server_pid: 3246
   * server_version: "2.12"
   * storage: zfs
   * storage_version: 0.6.5.6-0ubuntu15

# Issue description

When using ZFS as a back end and you try to create a container with a profile which specifies a non-existent ZFS pool you get the error message `error: not found`. Given that during automated processes there are a large number of things that could potentially be not found it could save a fair bit of debugging time if this were more specific.

In our case we encountered the bug when a developer accidentally initialized his local LXD instance with a different pool name. I'm still not sure how he managed it but it happened.

Thanks for taking the time to improve this.

# Steps to reproduce

 1. `lxc profile copy default bad-pool`
 2. `lxc profile edit bad-pool` then change the `pool` attribute of the `root` disk to a non-existent pool, like `bad-lxd`.
 3. `lxc launch ubuntu:16.04 foo-container --profile=bad-pool`

    ```
    Creating foo-container
    error: not found
    ```

We did not manage to find any further clues in the logs.

**Comment by brauner** [comment]
Did any storage pool exist on this instance? I'm trying to track down the error path.
