### ISSUE TITLE
How to init a container from a btrfs backup file

### ISSUE THREAD

**Issue by gabdara** [lxc/lxd#3112]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.10
 * The output of "lxc info" :
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
   xxxxxxxxxxxxxxxxx
    -----END CERTIFICATE-----
  certificate_fingerprint: xxxxxxxxxxxxxxxxx
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.8.0-41-generic
  server: lxd
  server_pid: 11574
  server_version: "2.12"
  storage: btrfs
  storage_version: 4.7.3
```

# Issue description

I have a backup file of a container made with `btrfs send `. Now I'm trying to restore it to another machine.

I've managed to do this by creating a container on the destination machine with the same name and architecture as the one in the backup, then replaced container subvolume with the one from `btrfs receive` 

I'm wondering if there's a better way to achieve this. I've found there is [lxd import command that works for zfs](https://github.com/lxc/lxd/commit/189641641f1effe9d53449d3e0a14f08b91bff69) , but couldn't make it to work for btrfs and didn't found any documentation of the command.

Any indications or suggestions are apprecieted.
Thanks!

**Comment by brauner** [comment]
@gabdara so what you can do is to call `lxd import` on the machine you're currently on and do a `lxc copy` or `lxc move` to the remote LXD. This obvs. presupposes that the two LXD instances can talk to each other.

**Comment by brauner** [comment]
Fwiw, the strategy I described above will also emply `btrfs {send,receive}` in case both LXD instances use a btrfs storage pool.

**Comment by gabdara** [comment]
Thank you for your answer!
In this case the two LXD instances can't talk with each other, that's why I want to use the output file of `btrfs send`.

**Comment by brauner** [comment]
Well yeah, in this case LXD itself can't be of much help. So yeah, what you can do is `btrfs {send,receive}` the container via `ssh` or something similar. Then on the host machine LXD should be able to import the container via `lxd import` so you don't need to pre-create the container itself. However, this presupposes that the `backup.yaml` file contains the same `pool` information as the source LXD instance.

**Comment by stgraber** [comment]
Doing a "btrfs send" on the source, transferring the output to the target and doing a "btrfs recv" in the same path as the source (under /var/lib/lxd/storage-pools/...), followed by a call to "lxd import NAME" should work fine.

@brauner what am I missing?

**Comment by brauner** [comment]
@stgraber answered one second before you. :)

**Comment by gabdara** [comment]
Works like a charm guys.
Thanks for the help!

**Comment by stgraber** [comment]
Perfect, closing.
