### ISSUE TITLE
Default pool for images

### ISSUE THREAD

**Issue by Lisio** [lxc/lxd#3115]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 x64
 * Kernel version: 4.4.52
 * LXD version: 2.12
 * Storage backend in use: zfs

# Issue description

Can't find any documentation on how to use pool as default for all images and containers. Please help to find it out.

**Comment by stgraber** [comment]
You can't select a storage pool to hold the images, it's done on-demand.

When an image is downloaded by LXD, the original image files are always stored in /var/lib/lxd/images.

We then have optimizations for the various storage backends that support it (btrfs, zfs, lvm) where on first use of the image, it will be converted to a more optimal format (subvolume, filesystem or lv) and stored in the container's storage pool. The container is then created from that optimized version of the image.

**Comment by Lisio** [comment]
Ok, with images I understood. How about setting default pool for containers?

**Comment by stgraber** [comment]
Just set the "pool" property of the "root" device in the "default" profile to point to whatever pool you want.
That's what "lxd init" does for you.

**Comment by Lisio** [comment]
Thank you. After your explanation I've ended up with the following setup:
```
lxc config device add default root disk path=/ pool=z
lxc network attach-profile lxdbr0 default eth0
lxc launch ubuntu u
lxc network attach lxdbr0 u eth0
lxc config device set u eth0 ipv4.address 10.10.10.10
```
Image moved to zfs as you said during first container creation and container works with statich IP.
