### ISSUE TITLE
when a container starts a script inside that lxc must be executed

### ISSUE THREAD

**Issue by lepidas** [lxc/lxd#3117]
This is more a need than an issue.
I can't figure out how to execute a script when the container(that has this script) will be started.

**Comment by stgraber** [comment]
What would that script do in your case?

With LXD we've been staying away from hooks or similar scripting attach points as they tend to make things very unreliable and near impossible to debug when misused (as we've noticed with LXC and numerous other projects).

Instead, we prefer having first class support for those cases that matter and have the rest be handled either through custom clients that execute those things and interact with LXD (keeping the LXD side effectively untouched) or by listening to LXD's events API and trigger things asynchronously that way.

**Comment by lepidas** [comment]
ah it's nothing very important, just to run a node.js when I start the container that has the node.js after stopping it to take a snapshot. Or I could snapshot a container while it's running?

**Comment by stgraber** [comment]
Snapshots can be done while the container is running, no problem.

**Comment by lepidas** [comment]
thank you so much :)

**Comment by stgraber** [comment]
Cool, closing this then.
