### ISSUE TITLE
how to delete ghost container?

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#3123]
lxd 2.12:

lxc list shows a container named 'mycontainer' but on the filesystem there is no trace of this container. it is a ghost container from a failed copy.

How to delete it in the sqlite database? can i just delete a row in the container table?

**Comment by stgraber** [comment]
What storage backend are you using?

It's usually easier to create a minimal filesystem entry to make "lxc delete" happy than to go cleanup the database by hand.

**Comment by gaetanquentin** [comment]
btrfs

**Comment by stgraber** [comment]
ok, then:

    btrfs subvolume create /var/lib/lxd/storage-pools/default/containers/mycontainer
    ln -s /var/lib/lxd/storage-pools/default/containers/mycontainer /var/lib/lxd/containers/mycontainer

That should create what LXD expects to see on the filesystem.

**Comment by gaetanquentin** [comment]
works! thanks a lot Stéphane.

**Comment by stgraber** [comment]
Good to hear, closing.
