### ISSUE TITLE
Is it possible to automatically restart crashed container? 

### ISSUE THREAD

**Issue by CodeJuan** [lxc/lxd#3129]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 14.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.19.0-37
   * LXC version: 2.0.6
   * LXD version: 2.0.8
   * Storage backend in use: dir

# Issue description
Is it possible to automatically restart crashed container? Like docker run restart=always.

Thank you.

# Steps to reproduce

1. lxc launch b490093ae9e3 a
2. Get the PID of container `a`, then kill it
3. lxc list

**The results  I received:** the state of container `a` is STOPPED
**The results I expected:** Container `a` is restarted automatically

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
It should be possible to add a "boot.respawn" boolean to the configuration where when set to true, containers would always be respawned unless directly stopped with "lxc stop".

I'm not sure that it's necessarily something that makes sense for us to do though. LXD doesn't run application containers, therefore the only case where such a thing would happen is if the container's init system crashes and when that happens, you usually really don't want it auto-respawned but instead want to take a very close look at kernel logs prior to starting the container again.

It would also be a bit awkward in that a user calling "poweroff" or "shutdown" inside the container wouldn't actually stop the container but have LXD respawn it for them.

**Comment by CodeJuan** [comment]
Yes, it would be awkward. 

The container was spawned by nova-lxd, but the container terminaled by command lxc stop(or kill). 
The state of container in nova is running, is it ok to restart the container by nova-lxd?

English is not my native language, sorry for mistakes.

**Comment by stgraber** [comment]
A restart may not work if it's actually sending a restart command to LXD. But I'd expect a shutdown followed by a start to work.

We're not the best to ask about nova-lxd though. It may be best to file a bug against nova-lxd to have them look into what happens when nova-lxd and LXD don't agree on the container's state. I suspect OpenStack has a similar issue with nova and libvirt, so the answer is probably to do the same thing as is done for that case.

**Comment by CodeJuan** [comment]
Yes, I found the similar issue in nova. There is a "resume" boolean in config file, if the value of "resume" is true, nova would keep VM runnging(similar to restart=always).

Thank you for your patience.

**Comment by stgraber** [comment]
Ok, so sounds like it's best to deal with this in nova-lxd/nova rather than in LXD, unless someone comes with a different use case where we'd want to respawn the container when the stop command wasn't sent through LXD.
