### ISSUE TITLE
lxc launch ubuntu: not working anymore

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#3130]
Since today, lxc launch ubuntu: is not working anymore

root@rlabdc1-hyov1001 (node1):~# lxc launch ubuntu: test
Creating test
error: Couldn't find the requested image

Previously, it was fetching ubuntu 16.04 (xenial).

Any help would be appreciated.

thks

**Comment by vasukolli** [comment]
same issue:

vasu@gbcontainer:~$ lxc launch ubuntu testcontainer
The local image 'ubuntu' couldn't be found, trying 'ubuntu:' instead.
Creating testcontainer
error: Couldn't find the requested image
vasu@gbcontainer:~$

**Comment by WTFjustgivemeaname** [comment]
Can confirm, same issue as of today. Server is up to date.

> lxc launch ubuntu: test
> Creating test
> error: Couldn't find the requested image

**Comment by stgraber** [comment]
This was caused by the Canonical Cloud team publishing bad data to cloud-images.ubuntu.com, breaking all cloud images. This has since been resolved.
