### ISSUE TITLE
live migration of container doesn't reopen all closed sockets.

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#3132]
lxd 2.7
lxc 2.7
Ubuntu 16.04

We are running VM inside lxc container, and when we migrate the container to another host, libvirtd-sock necessary for virsh api fails with.

lxc config show cnt13

name: cnt13
profiles:
- default
config:
  boot.autostart: "true"
  volatile.apply_template: copy
  volatile.base_image: f9fe8c92b170405736f9cb06609e95360879f38d6b060e47ebcf148e875758d2
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    host_name: cnt13
    hwaddr: f2:ff:e7:e5:6e:b9
    nictype: bridged
    parent: br0
    type: nic
  kvm:
    path: /dev/kvm
    type: unix-char
    root:
    path: /
    type: disk
 ephemeral: false

error: failed to connect to the hypervisor
error: no valid connection
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

When we reboot the same container, the libvirt-socket will open up, and the virsh api works.
Is it something with CRIU or LXD ?

**Comment by stgraber** [comment]
That would be a CRIU issue, you can file one at https://bugs.launchpad.net/ubuntu/+source/criu/+filebug

The fact that the libvirt socket isn't getting bound properly post-migration is a bit surprising, especially if libvirt itself is properly running. Note however that I don't expect you to be able to move a container that has a running VM inside it anytime soon (as there is no way to dump the /dev/kvm state).

**Comment by upuvvad1** [comment]
Thanks @stgraber 
Thanks for the note.
