### ISSUE TITLE
does a line in a script in host waits the lxc to finish a process before going to next line;

### ISSUE THREAD

**Issue by lepidas** [lxc/lxd#3134]
Line in script in host tells lxc to tar a directory.
The next line in the same script tells host to pull file lxc/tar.gz from the lxc.
The question is if the script is waiting for the lxc to complete the tar before pulling the file.
I now in the same environment should wait before go to the next line but what about this situation. #
lxc exec container -- tar cf dir.tar.gz /home
pull file container/dir.tar.gz

**Comment by stgraber** [comment]
The "lxc exec" won't return until the "tar" command returns, so your example above will be fine.

**Comment by lepidas** [comment]
Thanx so much.
