### ISSUE TITLE
It's possible to ignore disk quota on btrfs storage backend

### ISSUE THREAD

**Issue by soffokl** [lxc/lxd#3135]
If you are setting disk quota for container on btrfs storage backend it's works only for current subvolume. 
But if user creates another subvolume inside container, new subvolume does not inherit parent's limits. 

![image](https://cloud.githubusercontent.com/assets/8612618/24542806/e15955f2-161e-11e7-8422-31a4ae398682.png)

Is there another way to control disk quota for btrfs storage backend?

**Comment by stgraber** [comment]
So hmm, that's a bit upsetting indeed. I just went through a whole bunch of btrfs quota and qgroup documentation and there doesn't appear to be a way to tell btrfs to inherit from the parent subvolume's qgroup when the user creates a new subvolume.

That seems like a rather major flaw in the way quotas are handled, but maybe I'm missing something...

**Comment by stgraber** [comment]
@brauner is that something you could take a quick look at when you have some time? We're certainly not going to go add bits to btrfs in the kernel, but I'd like to make sure I didn't overlook a way of doing this as it seems such an obvious use case...

**Comment by brauner** [comment]
Only snapshots automatically inherit quotas from their parent subvolumes. I'm looking into doing this for subvolumes.

**Comment by stgraber** [comment]
@brauner ok, that confirms what I've seen.. That's pretty annoying then since as long as the user is allowed to create a subvolume from inside the container, they can therefore bypass the quota...

**Comment by brauner** [comment]
Well, the only way is to create a parent qgroup and assign both sub-qgroups as children of the parent qgroup in order to share a common limit. But this is terribly fiddly and according to my local testing this is not working smoothly at all.

**Comment by stgraber** [comment]
@brauner right, but there's nothing which does that automatically at the kernel level and we can't have LXD constantly scanning for new subvolumes to try and redo their qgroup setup.

Not to mention that there would be nothing preventing the user from simply removing the qgroup from the subvolume they just created...

**Comment by brauner** [comment]
@stgraber, yup, yup, and yup.

**Comment by stgraber** [comment]
@brauner can you maybe ping the btrfs upstream mailing-list about how to deal with such a setup?

I'd think it'd be the exact same problem if a system admin was to setup per-user subvolumes in /home to apply user quotas. Anyone of those users would be able to bypass the quotas by running "subvolume create" somewhere in their home directory and dump a bunch of big files in there.

If they say there's no way to do it at all, then we should update doc/storage-backends.md to reflect that and close this issue.

**Comment by brauner** [comment]
I'll ping them.

**Comment by brauner** [comment]
Sent a mail and CCed you (@stgraber).

**Comment by stgraber** [comment]
@brauner thanks for that. So sounds like the conclusion is that btrfs quotas while hierarchical aren't automatically tied to the parent, letting whoever is allowed to create a new subvolume (everyone) to bypass their quota.

Can you send a pull request which updates storage.md to mention that?

**Comment by brauner** [comment]
Will do.

**Comment by soffokl** [comment]
@stgraber @brauner btw, https://linuxcontainers.org/lxd/try-it uses btrfs and allows to anyone bypass quota using this method.

**Comment by brauner** [comment]
That depends on whether @stgraber is actually using btrfs quota on the btrfs {filesystem,subvolume} that the parent `LXD` daemon of the daemon your interacting with runs on. :)

**Comment by michacassola** [comment]
@brauner and @stgraber Was there any response from the btrfs team?

**Comment by brauner** [comment]
@michacassola, not a very helpful one: https://marc.info/?l=linux-btrfs&m=149288068515307&w=2
The solution that they suggest only applies to snapshots taken by `LXD` itself not to snapshots taken by users inside the container. Short answer: it's broken and it looks like it'll stay this way.

**Comment by brauner** [comment]
I could look at this and see how difficult it would be to fix btrfs quotas.

**Comment by stgraber** [comment]
@michacassola that wouldn't prevent a user from directly hitting the system with btrfs ioctls through some alternative binary. I suppose you could use a fancy seccomp filter to try and prevent the specific ioctls but that will also cause any tool that's used to being able to perform those on a btrfs filesystem to then fail miserably (Docker would likely be one of those).

**Comment by brauner** [comment]
When we have the seccomp userspace trap we can rewrite the corresponding argument in the btrfs ioctl() to always pass the option to create quota-based snapshots. :)

**Comment by michacassola** [comment]
@stgraber and @brauner Thanks for explaining but since @stgraber s comment things started to go over my head. I hope you figure it out though!
