### ISSUE TITLE
lxd networking and contradictory documentation

### ISSUE THREAD

**Issue by nhadsall** [lxc/lxd#3138]
I'm using the latest ubuntu & lxd.

Basically, I just need containers created with Juju to use the local dhcp. However, because of a bug with Juju, they also have to use the default bridge,

I'm was thinking of a simple configuration: 
1. Have eth0 use the default bridge (lxdbr0 bridged to eno1 on host)
2. Have a eth1 connect to another bridge (br0 bridged to eno2 on host)

However, after nearly 20 hours of tinkering, I am still just as lost. The lack of details and documentation contradictory documentation is maddening.

I have been trying to piece together something that would work using:
https://insights.ubuntu.com/2016/04/07/lxd-networking-lxdbr0-explained/
https://github.com/lxc/lxd/blob/master/doc/configuration.md#network-configuration
https://insights.ubuntu.com/2017/02/14/network-management-with-lxd-2-3/
http://stackoverflow.com/questions/41826430/how-to-setup-lxd-containers-that-communicate-over-the-lan

I'd appreciate any help. Thanks!

**Comment by stgraber** [comment]
Ok, so there are two parts to this:
 - Defining the two bridges
 - Attaching the containers to them

The first part is where things differ depending on LXD versions, the second remains the same (two is made easier by extra command line options in recent LXD).

On LXD 2.0.x, bridges must be defined OUTSIDE of LXD, typically in /etc/network/interfaces.
This will typically look like:
```
auto br0
iface br0 inet manual
  bridge-ports eno1

auto br1
iface br1 inet manual
  bridge-ports eno2
```

This would effectively ignore the lxdbr0 bridge which you could then completely turn off (with "dpkg-reconfigure -p medium lxd").

On LXD 2.3 or higher, you can instead do:

    lxc network create br0 ipv4.address=none ipv6.address=none bridge.external_interfaces=eno1
    lxc network create br1 ipv4.address=none ipv6.address=none bridge.external_interfaces=eno2

Which will have LXD create and manage the two bridges for you.

At that point, you'll have two bridges defined and need to tell LXD to use them for your containers.
So lets remove the default "eth0" device and add the new "eth0" and "eth1":

    lxc profile device remove default eth0
    lxc profile device add default eth0 nic nictype=bridged parent=br0 name=eth0
    lxc profile device add default eth1 nic nictype=bridged parent=br1 name=eth1

And there you go, any container using the "default" bridge will now get eth0 attached to br0 and eth1 attached to br1.

I'm not particularly familiar with Juju, so the above is simply about the LXD configuration for the setup you want. If Juju has broken tests for a particular bridge name or something similar, you may need to adapt the bridge names above to satisfy such requirements.

**Comment by nhadsall** [comment]
@stgraber Thank you so much! I have tried bits of this, but not all as you laid it out. I will try it now and let you know.

**Comment by nhadsall** [comment]
Okay, this is much closer.

I left the default eth0 (with the default bridge lxdbr0), because this is exactly what juju expects. I did use the following to create the second interface:
```
lxc network create br1 ipv4.address=none ipv6.address=none bridge.external_interfaces=eno2 
lxc profile device add default eth1 nic nictype=bridged parent=br1 name=eth1
```

The interface was created successfully, but the guest will not get a DHCP address for that interface unless I edit the guest's /etc/network/interfaces and run `ifup eth1`.

I see a couple options:
1. Am I missing a setting in xld for the guest to get the dhcp automatically?
2. Can lxd create a bridge in the guest between eth0 and eth2?

Thanks again!

**Comment by stgraber** [comment]
LXD doesn't alter container configuration files, so it's normal that nothing happens on eth1 since the image shipped by Ubuntu only has dhcp configured on eth0.

1) You may be able to have cloud-init set that up for you by passing it network data with user.network-config (though saying that cloud-init's network-config is poorly documented would be an understatement)

2) No, again, that'd be something you'd need to do through cloud-init's network-config.

You can find some information on the network-config syntax here: http://curtin.readthedocs.io/en/latest/topics/networking.html

But note that running DHCP on two different interfaces typically fails as both DHCP servers will be pushing a default gateway which will then conflict, making whichever dhcp client runs first succeed and the others fails.

**Comment by nhadsall** [comment]
Oh, of course the bridge with two DHCP servers wouldn't work...

I'll take a look at cloud-init. I really appreciate the quick response!

**Comment by nhadsall** [comment]
Yeah... cloud-init is a pain

So for, I have:

```
  user.network-config: |
    version: 1
    config:
      - type: physical
        name: eth1
        subnets:
          - type: dhcp
            control: auto
      - type: physical
        name: eth0
        subnets:
          -type: dhcp
          control: auto
```

However, this gets rid of the default dhcp on eth0. I have not found anything on adding multiple interfaces.

**Comment by nhadsall** [comment]
Arg... just a typo in the spaces. Looks like I got it. Thanks!
