### ISSUE TITLE
Storage Documentation Error

### ISSUE THREAD

**Issue by neil-bowers** [lxc/lxd#3140]
There appears to be a mis-match of information in this table in the storage docs [Storage Volume Configuration](https://github.com/lxc/lxd/blob/master/doc/configuration.md#storage-volume-configuration) - the descriptions do not appear to match up with the keys.

Maybe it got out of order during an edit?

**Comment by brauner** [comment]
Right.

**Comment by stgraber** [comment]
@brauner are you sending a fix? I was about to start preparing one.

**Comment by brauner** [comment]
@stgraber, go ahead if you already have one.

**Comment by stgraber** [comment]
@brauner don't have one yet, just noticed this issue and was about to create a branch for it :)

**Comment by brauner** [comment]
Then lemme send one. :)
