### ISSUE TITLE
virtual interface host_name in profile

### ISSUE THREAD

**Issue by kasra73** [lxc/lxd#3143]
# Required information

 * Distribution: kubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails: Config parsing error: Bad key: volatile.eth0.host_name
   * Kernel version: 4.4.0-64-generic
   * LXC version: 2.0.9
   * LXD version: 2.0.9
   * Storage backend in use: ZFS

# Issue description

I was playing with Open vSwitch and p2p nictype and found a problem. Each time I restart my container, p2p virtual interface name in the host (host_name), changes. So I searched for a solution and found that there is a host_name key in the config.

 1. First try:
I try to change it by:
`lxc config edit mycontainer`
and in config section, I added 
`volatile.eth0.host_name: veth123`
and an error occurred. 
 2. Second try:
Almost always we create our virtual interface in profile. maybe it works fine for the first container with a profile like _MySwitch_ if we add 
`lxc profile edit MySwitch`
and write:
```
config: {}
description: ""
devices:
  eth0:
    nictype: p2p
    type: nic
    host_name: veth123
name: MySwitch

```
but for second container, it will raise an error. because a virtual interface with the same name (_veth123_ ) exists in the host machine.

# A Probable Solution
Maybe we can use raw.lxc and change it in the container config. But I prefer to do that in LXD way! :)

# What I think is wrong
In [this](https://github.com/lxc/lxd/blob/master/shared/container.go) file at line about 206 in ConfigKeyChecker function, we should add another **if** for the **host_name**. something like this:

```
if strings.HasPrefix(key, "volatile.") {
	if strings.HasSuffix(key, ".hwaddr") {
		return IsAny, nil
	}

	f strings.HasSuffix(key, ".name") {
		return IsAny, nil
	}

	f strings.HasSuffix(key, ".host_name") {
		return IsAny, nil
	}
}

```

**Comment by stgraber** [comment]
Hi,

Taking a look at this now. Adding a volatile key to allow for the stabilization of the name (if set) seems reasonable to me.
