### ISSUE TITLE
[question] Create a local readonly LXD registry

### ISSUE THREAD

**Issue by shantanugadgil** [lxc/lxd#3144]
I am using stock Ubuntu **16.04.2** on two separate hosts.
I have followed the instructions from:
https://stgraber.org/2016/04/12/lxd-2-0-remote-hosts-and-container-migration-612/

... to allow access to one of the machines (LXD host) from the other (driver node).

This is fine if I make the LXD host download images from "https://images.linuxcontainers.org"

The question is:
Can I setup a local LXD registry in readonly mode?

The above setup will thus change to:
A single "driver" node. (driver)
A single readonly LOCAL registry. (localregistry)
One or more LXD hosts which can be controlled from the driver node. (lxdhost)

Hope my question makes sense.

Thanks and Regards,
Shantanu

**Comment by shantanugadgil** [comment]
_after some searching_

I think this seems to be an often asked feature, solved (currently) as a workaround:
export to tarball -> scp/rsync to lxdhost -> import into lxdhost's image repo

This becomes tricky if I have a large number of lxdhosts to which I have to copy this.

Example:
#1510
#553  

I think my question of setting up a local readonly registry still remains, I guess! 😀 

Regards,
Shantanu

**Comment by stgraber** [comment]
You can just run a normal LXD instance, have the images in its store marked "public" which then allows read-only access from other LXDs.

**Comment by stgraber** [comment]
Clients should add such a LXD image server with "lxc remote add NAME URL --public" so that they're not prompted for the trust password and so only get access to the public images.

**Comment by shantanugadgil** [comment]
Thanks @stgraber. For now I have setup things using the **public** images.

**Comment by stgraber** [comment]
Cool, good to hear that this is working for you!
