### ISSUE TITLE
Wall message on container shutdown

### ISSUE THREAD

**Issue by kirgene** [lxc/lxd#3145]
I wonder how to send wall message like "Doing shutdown" to a container on "lxd shutdown".
Also is there any way to propagate wall message from host machine to all containers?

**Comment by stgraber** [comment]
When "lxd shutdown" is run or when the host is shutdown (which calls "lxd shutdown" too), a shutdown signal is sent to the container's init system which then proceeds to cleanly shutdown the container.

If the init system sends such a wall message, then this is already happening already. If not, you may want to add a init script in your container that will do so as the first thing in the shutdown sequence.
