### ISSUE TITLE
Please help !

### ISSUE THREAD

**Issue by djixyacine** [lxc/lxd#3146]
Hello everyone,

I'm working on LXD, more precisely migration and how LXD works with criu. I'm having some dificulties with the "GO" language, so here is my question: 
    What part of the code that chooses the flags for criu for ex. "criu dump --tcp-established --manage-cgroups ..." while doing the migration or a making stateful snaphost ?

Thank you

**Comment by stgraber** [comment]
That's C code in github.com/lxc/lxc, not LXD code.

**Comment by djixyacine** [comment]
Allright, got it. Thank you very much!

**Comment by djixyacine** [comment]
Okay, so I've made my modifications in lxc, compiled it and installed it. How to make LXD the LXC I built ?

**Comment by djixyacine** [comment]
Any help would be appreciated.

**Comment by stgraber** [comment]
LXD uses liblxc1.so so if you built a modified one and put it in the place of the normal system one, restarting LXD is all that's needed.

**Comment by djixyacine** [comment]
Okay, that's way simpler than what i was trying to do. Thanks
