### ISSUE TITLE
proper reporting of top command inside container ?

### ISSUE THREAD

**Issue by memed81500** [lxc/lxd#3147]
I was wondering if there is a way that the top command in a container, only show the cpu usage of the container  ? Because for now, it seems that even a "dummy" container shows the cpu usage of the cores even if it is an another container that run on that cores. Sorry if my question is not clear.

Thanks in advance.

**Comment by stgraber** [comment]
Nope, there is a lxcfs bug for that here: https://github.com/lxc/lxcfs/issues/13

**Comment by amostech** [comment]
@stgraber Is there any workaround for this in the meantime? I checked https://github.com/lxc/lxcfs/issues/13 and it looks like we won't be seeing a fix or support for this soon in lxcfs or even in lxc. So we're not sure how to proceed with this. To achieve this kind of isolation in reporting are we suppose to migrate to QEMU?
