### ISSUE TITLE
dmesg shows host's log

### ISSUE THREAD

**Issue by lagunax** [lxc/lxd#3148]
in any (in my case - debian) container dmesg shows log of main system. 
is there any plans to implement by-container logs? or how can i configure it?

**Comment by brauner** [comment]
There were a couple of discussions about this on the kernel mailing list but afaik no one made a convincing enough argument for them to implement it. So there's not a lot that LXD can do.

**Comment by stgraber** [comment]
Note that there is a sysctl you can set to prevent non-root users from accessing the kernel log buffer, that will cause containers to get a permission denied error when running "dmesg".
