### ISSUE TITLE
image issue: ifup|ifdown missing file

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#3152]
```
lxc launch debian svn
lxc network create lxdSVN ipv4.address=none ipv6.address=none ipv4.nat=false ipv6.nat=false
lxc network attach lxdSVN svn
lxc file edit svn -- /etc/network/interfaces
 ...<adding ipaddress to interface eth0>...
lxc exec svn -- /bin/bash
#ifdown eth0
ifdown: failed to open lockfile /run/network/.ifstate.lock: No such file or directory

```

if i do "touch /run/network/.ifstate.lock" then all seems ok.

```
lxc image list
|  ALIAS   | FINGERPRINT  | PUBLIC |             DESCRIPTION              |  ARCH  |  SIZE   |         UPLOAD DATE          
| debian   | 0459336f6238 | no     | Debian jessie amd64 (20170317_22:42) | x86_64 | 94.15MB | Mar 18, 2017 at 3:16pm (UTC) |
```

and second question:
is it possible to do configuration of in-container net interface  to configure from internal container/etc/network/interfaces on starting container?
issue:
```
# lxc exec container -- cat /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
        address 192.168.1.119
        netmask 255.255.255.128
        gateway 192.168.1.125
        dns-nameservers 192.168.1.125 8.8.8.8
```

when i do lxc start container - then interfaces do not used. only ifdown-ifup loads configuration

**Comment by lagunax** [comment]
thats ok. on container startup /run folder takes most of time to be mounted.

**Comment by stgraber** [comment]
Looks like the usual jessie systemd issue. That is, the container isn't fully starting so ifdown fails because systemd pretty much crashed on boot...

I confirmed that stretch appears to be fine.
