### ISSUE TITLE
cannot create top level directory with file push --create-dirs

### ISSUE THREAD

**Issue by smoser** [lxc/lxd#3153]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.04
 * kernel / lxc / lxd versions
       $ dpkg-query --show lxc2 lxd
       lxc2	2.12-0ubuntu1
       lxd	2.12-0ubuntu1
       $ uname -r
       4.9.0-15-generic
      
 * Storage backend in use: zfs

# Issue description
`lxc file push --create-dirs` fails if the top level directory in the container does not already exist.

# Steps to reproduce

    $ name=zpushtest
    $ lxc init ubuntu-daily:zesty $name
    Creating zpushtest
    
    #
    # push and pull seem to work fine to existing directories.
    #
    $ lxc file push -p /etc/passwd $name/foo.file
    $ lxc file pull $name/foo.file - | grep 1000
    smoser:x:1000:1000:Scott Moser,,,:/home/smoser:/bin/bash
    
    $ lxc file push -p /etc/passwd $name/etc/passwd.new
    $ lxc file pull $name/etc/passwd.new - | grep 1000
    smoser:x:1000:1000:Scott Moser,,,:/home/smoser:/bin/bash
    
    #
    # but if i want to make a new dir, I get 
    #     error: missing path argument
    #
    
    $ lxc file push -p /etc/passwd $name/foo.d/bar
    error: missing path argument
    
    # if the top level dir exists, then it will still work
    $ p=etc/this/really/deep/a/b/c/d/passwd
    $ lxc file push -p /etc/passwd $name/$p
    $ lxc file pull $name/$p - | grep 1000
    smoser:x:1000:1000:Scott Moser,,,:/home/smoser:/bin/bash

**Comment by brauner** [comment]
@stgraber, looking into this now.
