### ISSUE TITLE
thick lvm instead of thin

### ISSUE THREAD

**Issue by overquota** [lxc/lxd#3160]
Hello!
Is there a possibility to add support for lvm thick backend storage instead of lvm thin?
We are having some perfomance issues with thin backend on random writes which are normal for databases
I've found similiar question in lunixcontainers maillist, but unfortunately there is no answer.. (https://lists.linuxcontainers.org/pipermail/lxc-users/2016-March/011234.html)

**Comment by brauner** [comment]
We could add a key on the storage pool level to switch this behavior off. @stgraber?

**Comment by stgraber** [comment]
Yeah, a lvm. key would be fine with me.

**Comment by OmAsana** [comment]
Are you planning on implementing this feature in the nearest future?
We are thinking about implementing this and then submitting a pull request.
At the same time we think it might take us a long time to implement it.
On the other hand we see that you added this feature to a "later" milestone that has no deadline. 
We need this feature in our production and it would be great if you could give us any time-frame. 

Thank you.

**Comment by brauner** [comment]
@OmAsana, in fact I'm working on this right now. There are some caveats though. Without thin pools LVM has the same problem as zfs namely that you cannot remove the origin logical volume as long as it has dependent snapshots. That's a case I need to handle.

**Comment by brauner** [comment]
So, another thing to think about is that snapshots of snapshots are not allowed for non-thinpool based logical volumes. This means we cannot create a logical volume for the image, then snapshot the image to create a new container from it and then create another snapshot for the container. In short:
```
lxc launch images:ubuntu/xenial xen1
lxc snapshot xen1
```
would not be possible. Afaik, LVM also does not offer the concept of a "clone" similar to zfs.
However, there's an obvious way around this:
- Do not import the image into a non-thinpool storage pool, i.e. do not create a storage volume for the image itself in the pool. Instead, on container creation, create an empty logical volume for the container and rsync the contents of the compressed image files into it. Container snapshots will then work out of the box.
- For creating containers from snapshots (i.e. `lxc copy a/snap0 b`) we'd need the same strategy as for creating containers from images. We create an empty logical volume and rsync the contents of the snapshot over into it.
All of this is of course less space-efficient than thinpools so this should be mentioned in the docs. @stgraber, what do you think?

**Comment by stgraber** [comment]
Sounds good to me.

**Comment by brauner** [comment]
I should have something today or tomorrow. Need to figure out the (non-live) migration story for this one.
