### ISSUE TITLE
Limits not respected in nested containers using docker 

### ISSUE THREAD

**Issue by givre** [lxc/lxd#3161]
# Required information
```

   Virtualization: vmware
   Operating System: Ubuntu 16.04.2 LTS
   Kernel: Linux 4.4.0-72-generic
   Architecture: x86-64
```
```
lxd --version
2.12
```
```
lxc --version
2.12

```

# Issue description
Nesting container / docker does not respect the limits set on first level 
I limit the container (level 0) to 1 CPU
I start docker container inside my container, docker can see 4 CPU

# Steps to reproduce

 1. Create a container
 2. Set limit 1 cpu 
lxc config set benoit-docker limits.cpu 1
 3. Step three
Inside the container : 
```
cat /proc/cpuinfo|grep proc|wc -l
1
```
 4. Step four
install docker.io and launch any image.
 5. Step five
Go into the docker image
`docker exec -it bbd565f477ba /bin/bash`
 6. Look number of CPU
```
cat /proc/cpuinfo|grep proc|wc -l
4
```

I was expecting the limits set on the container would apply in nested configuration. 
Is this specific to docker or would it be the same for LXD into LXD ?

Thanks

**Comment by stgraber** [comment]
Docker doesn't use lxcfs so it shows the host values rather than the cgroup values.

The limits absolutely do apply to nested containers.

**Comment by givre** [comment]
Thanks @stgraber

**Comment by badsmoke** [comment]
how can this problem be solved?

**Comment by paulstelian97** [comment]
> how can this problem be solved?

Probably remount /proc inside the container I guess, to account for the cgroup.
