### ISSUE TITLE
LXD accepts expired certificate in PKI setup.

### ISSUE THREAD

**Issue by jtopjian** [lxc/lxd#3162]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info":

```
config:
  core.https_address: '[::]'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.1.7.83:8443
  - '[3605:fd00:4:1000:f816:3eff:fe88:a0f7]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
  certificate_fingerprint: 91f14f801ee3e2d14881a3cd306f55fd8949c8bb1acf0c59eb38136b54dd2d98
  driver: lxc
  driver_version: 2.0.5
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-57-generic
  server: lxd
  server_pid: 12425
  server_version: "2.12"
  storage: btrfs
  storage_version: "4.4"
```

# Issue description

Client connection is still accepted after client certificate has expired.

# Steps to reproduce

1. Set up a central CA
2. Create an LXD server with the required `server.ca`, `server.crt`, and `server.key` files.
3. Create `client.ca`, `client.key`, and `client.crt` with a short expiration time.
4. Attempt to both perform an initial authentication and subsequent communication. 

# Information to attach

Let me know if you need any further information. 

I've done a good amount of digging into the LXD code to try to find where certificate [verification](https://golang.org/pkg/crypto/x509/#Certificate.Verify) should happen, but it's entirely possible that I have something misconfigured or missed something.

In addition, the docs reference the ability to specify a CRL, but I'm not sure I see where that's happening, either.

**Comment by ZZelle** [comment]
I had the same trouble and i solved it by adding a https proxy between lxd client and lxd server. The proxy ensures the client certificate is valid (not expired, verified by the CA) ... and it's an enabler to perform finer client certificate check.

**Comment by jtopjian** [comment]
@ZZelle Thanks! I was kicking that idea around - glad to hear it's a worthwhile approach. 

I have a few questions, if you don't mind:

Which proxy are you using?

Is the proxy acting as an initial gate for the cert, and if the cert is valid, the connection will proceed as normal? Or is the proxy acting as a terminator and initiating a new SSL on the backend?

I thought about using HAProxy and configuring the backend to communicate with the local unix socket.

**Comment by ZZelle** [comment]
@jtopjian I am using Nginx as proxy but it should work with haproxy or apache2.

You can either use a https->lxc-socket proxy: the lxd client authenticates against the proxy server over https, the proxy interacts with the lxd server using lxc socket (http) ... which implies the lxd proxy is not able to differentiate local requests from proxied requests.

Or use a https->https proxy: the lxd client authenticates against the proxy server over https, the proxy as a lxd client authenticates against the lxd server ... which implies the proxy should have a trusted client cert to interact with lxd server AND from the lxd server, there is a unique client: the proxy.

In both cases, the lxd client authentication is delegated to the proxy. The simplest case is to accept every client certificate accepted by the CA, it's possible to perform finer authentication (at least with Nginx).

I choose the https->socket proxy which is a bit easier to configure.

A simple https->socket configuration:
```
server {
  listen 8443 ssl;
  
  # SSL server config
  ssl_verify_client on;
  ssl_client_certificate  /etc/nginx/server.ca;
  ssl_certificate         /etc/nginx/server.crt;
  ssl_certificate_key     /etc/nginx/server.key;

  location / {
    proxy_set_header Host $http_host;
    # Nginx user (nginx or www-data) should be able to open the socket ... typically by being in lxd group.
    proxy_pass http://unix:/var/lib/lxd/unix.socket;
  }
}
```

A simple https-https configuration:
```
server {
  listen 8443 ssl;
  
  # SSL server config
  ssl_verify_client on;
  #ssl_verify_depth 2;
  ssl_client_certificate  /etc/nginx/server.ca;
  ssl_certificate         /etc/nginx/server.crt;
  ssl_certificate_key     /etc/nginx/server.key;

  location / {
    proxy_set_header Host $http_host;
    proxy_pass https://localhost:18443;
    # SSL client config
    proxy_ssl_certificate /etc/nginx/trusted-by-lxd.crt
    proxy_ssl_certificate_key /etc/nginx/trusted-by-lxd.key
  }
}
```

**Comment by jtopjian** [comment]
@ZZelle Thank you - that's really helpful 😄

**Comment by ZZelle** [comment]
I forgot that some commands (at least lxc exec) use websockets, to support them it requires extra-configuration in Nginx to correctly forward some headers:

```
map $http_upgrade $connection_upgrade {
    default       upgrade;
    ''            close;
}

server {
  listen 8443 ssl;
  ssl_verify_client on;
  ssl_client_certificate  /etc/nginx/server.ca;
  ssl_certificate         /etc/nginx/server.crt;
  ssl_certificate_key     /etc/nginx/server.key;

  location / {
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_pass http://unix:/var/lib/lxd/unix.socket;
  }
}
```

**Comment by stgraber** [comment]
Ok, did some testing:
 - Expired CA invalidates the trust path, so that's fine
 - Expired server cert causes client failure because of expiry, that's fine too
 - Expired client cert makes it to the DB (expected as not authenticated) but remains trusted afterwards and expiry appears to go unchecked by TLS stack. That's certainly wrong. Fix sent.

**Comment by jtopjian** [comment]
@stgraber Thank you!
