### ISSUE TITLE
lxc-to-lxd script interface doesnt point to lxdbr0

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#3164]
Xenial
lxc version 2.0.9

On my host I have a mix of lxc using lxcbr0 (10.0.3.0/24) and lxd containers using lxdbr0 (10.0.4.0/24) I was using the lxc-to-lxd script to migrate all of them to lxd. I´ve noticed that (apart to change the IP of interface of the container) that in the configuration file of the container points to interface lxcbr0 and not lxdbr0 as it should be. Here is a excerpt of the config after migration.
```devices:
  convert_net0:
    hwaddr: 00:16:3e:5f:c0:7c
    nictype: bridged
    parent: lxcbr0
    type: nic
  eth0:
    type: none
  root:
    path: /
    type: disk
```

**Comment by stgraber** [comment]
lxc-to-lxd migrates your container without any change to its configuration, so if it was attached to lxcbr0 in LXC, it will also be attached to lxcbr0 in LXD. It's then up to you to change the config to match your other LXD containers.

**Comment by stgraber** [comment]
There are cases where systems have lxcbr0 but no lxdbr0, there also are cases where both lxcbr0 and lxdbr0 co-exist with widely different configuration. We don't want to do guesswork in this script, we just want to import a container and have it work exactly the same way it did before, but in LXD.

If your goal is to then remove lxc1 and its bridge, then you should update your container configuration to match. Doing so will mean a change of subnet and IP address for your container though.

**Comment by huegelc** [comment]
Hi @stgraber , 

yes, thanks for clarifying this. 
Can you tell me what is the right subcommand of lxc  like `lxc config set "containername" security.privileged false` ? I would like to run a post-script to change the bridge.
Thx

**Comment by stgraber** [comment]
You most likely want to change your container to inherit those things from the default profile again, so this should do:

    lxc config device remove "containername" convert_net0
    lxc config device remove "containername" eth0
    lxc config unset "containername" security.privileged

That will remove the device that was added to the container by the migration script, re-enable inheritance of "eth0" from the profile and also allow inheritance of security.privileged from the profile (which is a bit cleaner than what you did with setting it to false).

**Comment by huegelc** [comment]
Thank you. Much appreciated.
