### ISSUE TITLE
Error running docker inside an lxd container, works fine outside of container

### ISSUE THREAD

**Issue by tpaluch** [lxc/lxd#3166]
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
Kernel: 4.4.0-71-generic

docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

Fresh server, only ubuntu OS , lxd, and docker installed. I followed the installation instructions for docker from their docs page for the CE version: docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository

Running the "Hello-World" app inside the container as root user (sudo user same thing) gives the following error:

docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:252: getting pipe fds for pid 2391 caused \"readlink /proc/2391/fd/0: permission denied\"".

Note: I am using ZFS storage (with proper packages to enable ZFS on linux) for the LXD container, however I have not made any modifications to the docker installation -- just the defaults it installed with.

**Comment by brauner** [comment]
Docket upstream is still missing a patch required to work out of the box in a LXD container. Until it is merged we recommend to use the Ubuntu Docker package.

**Comment by hooramin** [comment]
@brauner Do you mean apt-get install docker.io inside the container ?

**Comment by stgraber** [comment]
This recommendation no longer applies that was from back in April, the change in question is now part of the normal Docker deb packages.

**Comment by hooramin** [comment]
@stgraber but i have exactly the same problem as first post here in ubuntu 14.04 yet!

**Comment by hooramin** [comment]
should i open a new issue ?

**Comment by brauner** [comment]
@hooramin, wait, are you saying that you are on Ubuntu 14.04 if so what is the Docker version you are using. Afaik, the minimal required version for Docker to work out of the box in LXD is `17.06` . (I'm not sure about their current numbering scheme though.) If you install that version you should be fine. The installation instruction can be found in the Docker documentation.

**Comment by hooramin** [comment]
@brauner I'm at ubuntu 16.04 and my container is ubuntu 14.04
i followed the instruction in their document and i got error , also i tried to do as[ lxd docker document ](https://stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/)
in both of them i got a same error as first post 
`root@server:~#  docker run hello-world
FATA[0000] Error response from daemon: Cannot start container ad0ea7fd6ffc14f4c6d48b30f70a13a38542e39f042c9e1fa256bd16852d6d51: [8] System error: write /sys/fs/cgroup/devices/docker/ad0ea7fd6ffc14f4c6d48b30f70a13a38542e39f042c9e1fa256bd16852d6d51/devices.allow: operation not permitted`

**Comment by stgraber** [comment]
Right, you're running a Docker version that's super old and that will not work inside LXD.

The instructions that said that docker.io from Ubuntu would work inside LXD were for Ubuntu 16.04, not 14.04. You either need Ubuntu's version of Docker at version 1.12 or higher, or the upstream Docker build which should be version 17.06 or higher.
