### ISSUE TITLE
lvm: restore containers after system crushed.

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#3181]
(history related to #3178.)

first of all before reinstalling system i copied /var/lib/lxd/ content to other place. as i think - there was some symlinks, that do not copied due to fat32-destination.
So troubles now with restoring all of them.
containers' VGs and LXDThinpool exists in theres' places.

on clean system installing lxd from ppa.
next is service lxd stop, rm -R /var/lib/lxd, and copy backuped varliblxd into /var/lib/lxd
then:
```
root@mSys:/# cp -R /var/backups/var_lib_lxd/lxd /var/lib/
root@mSys:/# service lxd start
root@mSys:/# lxc list
+----------+---------+------+------+------------+-----------+
|   NAME   |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+----------+---------+------+------+------------+-----------+
| cert     | STOPPED |      |      | PERSISTENT | 0         |
+----------+---------+------+------+------------+-----------+
| database | STOPPED |      |      | PERSISTENT | 0         |
+----------+---------+------+------+------------+-----------+
| dns      | STOPPED |      |      | PERSISTENT | 1         |
+----------+---------+------+------+------------+-----------+
| github   | STOPPED |      |      | PERSISTENT | 0         |
+----------+---------+------+------+------------+-----------+
| inet     | STOPPED |      |      | PERSISTENT | 0         |
+----------+---------+------+------+------------+-----------+
| mail     | STOPPED |      |      | PERSISTENT | 0         |
+----------+---------+------+------+------------+-----------+
| ntp      | STOPPED |      |      | PERSISTENT | 0         |
+----------+---------+------+------+------------+-----------+
| openvpn  | STOPPED |      |      | PERSISTENT | 0         |
+----------+---------+------+------+------------+-----------+
| svn      | STOPPED |      |      | PERSISTENT | 1         |
+----------+---------+------+------+------------+-----------+
| test     | STOPPED |      |      | PERSISTENT | 0         |
+----------+---------+------+------+------------+-----------+
| unifi    | STOPPED |      |      | PERSISTENT | 2         |
+----------+---------+------+------+------------+-----------+
root@mSys:/# lxc start inet
error: Failed to run: /usr/bin/lxd forkstart inet /var/lib/lxd/containers /var/log/lxd/inet/lxc.conf:
Try `lxc info --show-log inet` for more info
root@mSys:/# lxc info --show-log inet
Name: inet
Remote: unix:/var/lib/lxd/unix.socket
Архитектура: x86_64
Создано: 2017/04/11 17:37 UTC
Status: Stopped
Type: persistent
Profiles: default

Журнал:

            lxc 20170417110008.122 ERROR    lxc_conf - conf.c:mount_rootfs:865 - No such file or directory - failed to get real path for '/var/lib/lxd/containers/inet/rootfs'
            lxc 20170417110008.122 ERROR    lxc_conf - conf.c:setup_rootfs:1279 - failed to mount rootfs
            lxc 20170417110008.122 ERROR    lxc_conf - conf.c:do_rootfs_setup:3750 - failed to setup rootfs for 'inet'
            lxc 20170417110008.122 ERROR    lxc_conf - conf.c:lxc_setup:3832 - Error setting up rootfs mount after spawn
            lxc 20170417110008.122 ERROR    lxc_start - start.c:do_start:811 - Failed to setup container "inet".
            lxc 20170417110008.122 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20170417110008.215 WARN     lxc_conf - conf.c:lxc_delete_network:3038 - Failed to remove "vethNSGFY2" from host: Invalid argument.
            lxc 20170417110008.215 ERROR    lxc_start - start.c:__lxc_start:1346 - Failed to spawn container "inet".
            lxc 20170417110008.788 ERROR    lxc_conf - conf.c:run_buffer:405 - Script exited with status 1.
            lxc 20170417110008.788 ERROR    lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "inet".
            lxc 20170417110008.788 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - Command get_cgroup failed to receive response: Connection reset by peer.
            lxc 20170417110008.788 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - Command get_cgroup failed to receive response: Connection reset by peer.
```

if we look closer: 

> failed to get real path for '/var/lib/lxd/containers/inet/rootfs'

but i found something like that by this way:

```
root@mSys:/var/lib/lxd/containers/inet# ls -luap
итого 8
drwxrwx--- 2 165536 165536 4096 апр 17 14:00 ./
drwx--x--x 3 root   root   4096 апр 17 13:59 ../
root@mSys:/var/lib/lxd/containers/inet# mount | grep inet
/dev/mapper/Data-containers_inet on /var/lib/lxd/storage-pools/LXCPool/containers/inet type ext4 (rw,relatime,discard,stripe=32,data=ordered)
root@mSys:/var/lib/lxd/containers/inet# ls /var/lib/lxd/storage-pools/LXCPool/containers/inet/
backup.yaml  lost+found  metadata.yaml  rootfs  templates
```

there is we have folder named "rootfs". what's metter with this all? and what i can edit to fully restore containers?

```
root@mSys:/# lxc info
config:
  core.https_address: 192.168.201.2:8888
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 192.168.201.2:8888
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFcjCCA1qgAwIBAgIQfQ3UXjmV+y1UULUDQVhqXTANBgkqhkiG9w0BAQsFADAy
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRIwEAYDVQQDDAlyb290QG1T
    eXMwHhcNMTcwMzE4MTUwMDAyWhcNMjcwMzE2MTUwMDAyWjAyMRwwGgYDVQQKExNs
    aW51eGNvbnRhaW5lcnMub3JnMRIwEAYDVQQDDAlyb290QG1TeXMwggIiMA0GCSqG
    SIb3DQEBAQUAA4ICDwAwggIKAoICAQCrldknemNUd8kYpcvpsqKPZlUwgp5pvbZS
    aRoP7oYV0rphRxf0xp4AtCPrt29mL6AK3C4lNt/8Ac8oES/1AHi9w1xFSt/+0XGf
    LQZRjUD0Ms2sDoCjjZD2AD4bdmt5FQkUW69AsCBnCphbWyRonxoeZN6qNxw+VLWC
    mN4hSwETOgF+Ycnq2xKFy+3aam2rIbtakrZUqd/q1wCTZfIO6d0cmWgLZ5dwdZ9y
    BoEOwsNTPfb1822e70eF4jhqJ50bYLnlFb0tD6z06mPoJ01clTrr+79vEP1dR+pH
    3s/z5Yu5Dtvu4NKie6vIWe2iJwI57bs25v+tsYIzcccGyBuWuHqKK80f/QY+u3ou
    hCNoPM+ITwuI9JPNuok3h+3wn3TIwFxzHSzhEhQrNzE7UDWzB8Mn6Mh0bbDzTxw4
    P8SMQH+FSiGrHm9aYgnCElbNlH695UDy8p8wiwTT8ZePu/qUmgL1lXTmEleSeZ51
    ajMP8t/Ha7Cc3izCbJvohS+IcTjd2jU/Lw/Ye4iftTMd31mRrbQUWiiXtVpcMKS1
    f7l9Bu3PMQGlS5MXpuZTXd4TBrRTT9gDJ2uU2xRIzjiQR1NdZzr95nR3/sg15bIr
    NQhNXuxmQO1ANO6r7csLA362rh37v6ZBdPJinQPHuERGIZQqZJgc3Fr8ND3hMQrS
    BsyEhQ/8iQIDAQABo4GDMIGAMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMEsGA1UdEQREMEKCBG1TeXOHBMCoAdKHBMCo
    AH2HBMCoAX2HBMCoAZ6HBMCoAL6HBMCoAP6HBMCoAvyHBMCoyQKHBMCoygKHBAoA
    AwEwDQYJKoZIhvcNAQELBQADggIBAI5r5brYBwAa65oecFQtm86MBRD7liGKUwYK
    aJt7pFeha54t2V5o6KRZji1VwB/O9H3WNp/Q0eccd5uhogTPhJHHpaeJWSwO/1aP
    K++FriQ05iWxCyADWSp/xrx+HFW7BHtMgu9Bh98gbxaTU+mO7V7rRKGbNQlYZUw0
    ou2FLKQBYW+2fIrkP2Tnq9Y4le/ywSMUhpwBroKeQwJR3Afg+wcGhI1372K3Bmhs
    oC3Zh+sHvOmiDleXeRxgoT2pi+nmeHX1PPpX3wzxYrUTpnmWS9K8ceyllFpRQhFc
    ayWXis5wbSeIJ+idyDbue0l4dCmlTKr2bKYYzNTOlpwr3IvY2iGyYsMyvslI6Sub
    6TshNwB+ryQMwM9D98d+F2/fbaMdtCT0iZpGKJCx6TP/II55l9g3+DCOr6czpWgF
    Y9Ti9iXpB15ZO/fTrEw8gU1GUi7P4FW5rH30FZ5qLoof4LjQtfzqHen+r5Cryc6U
    HfxdRHtdjQ2DubrIr5sp+DvxnvTsyxedJB/8Od21AmG4K5moJc1p5H1jGplkAzLo
    1Bwxmf9RCRS69/XwINYoIzGqt01ODgDWmn3L+28H1V3RraKhkg0age4FN7K/X/Hn
    H+wRpOnWhRrngxrdp6O3ysHbRfwYAjJgWzdi2AtsucW0L8Ka0LvVDADrIFehrycj
    nrGZpoZ4
    -----END CERTIFICATE-----
  certificate_fingerprint: 3affa322fafe80fd43f063577077574eef56b0e4017ac6b5aac002412f766ab3
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.8.0-46-generic
  server: lxd
  server_pid: 15064
  server_version: "2.12"
  storage: dir | lvm
  storage_version: 1 | 2.02.133(2) (2015-10-30) / 1.02.110 (2015-10-30) / 4.35.0


root@mSys:/var/lib/lxd/containers/inet# uname -a
Linux mSys 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Laguna-x** [comment]
tried this:
> root@mSys:/var/lib/lxd/containers# ln -s /var/lib/lxd/storage-pools/LXCPool/containers/database ./database

and got that:```

root@mSys:/var/lib/lxd/containers# lxc start database
error: Failed to run: /usr/bin/lxd forkstart database /var/lib/lxd/containers /var/log/lxd/database/lxc.conf:
Try `lxc info --show-log database` for more info
root@mSys:/var/lib/lxd/containers# lxc info --show-log database
Name: database
Remote: unix:/var/lib/lxd/unix.socket
Архитектура: x86_64
Создано: 2017/04/04 12:39 UTC
Status: Stopped
Type: persistent
Profiles: default

Журнал:

            lxc 20170417114926.315 ERROR    lxc_utils - utils.c:safe_mount:1751 - Operation not permitted - Failed to mount sysfs onto /usr/lib/x86_64-linux-gnu/lxc/sys
            lxc 20170417114926.315 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:801 - Operation not permitted - error mounting sysfs on /usr/lib/x86_64-linux-gnu/lxc/sys flags 0
            lxc 20170417114926.315 ERROR    lxc_conf - conf.c:lxc_setup:3859 - failed to setup the automatic mounts for 'database'
            lxc 20170417114926.315 ERROR    lxc_start - start.c:do_start:811 - Failed to setup container "database".
            lxc 20170417114926.315 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20170417114926.365 ERROR    lxc_start - start.c:__lxc_start:1346 - Failed to spawn container "database".
            lxc 20170417114926.942 ERROR    lxc_conf - conf.c:run_buffer:405 - Script exited with status 1.
            lxc 20170417114926.942 ERROR    lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "database".
            lxc 20170417114926.942 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - Command get_cgroup failed to receive response: Connection reset by peer.
            lxc 20170417114926.942 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - Command get_cgroup failed to receive response: Connection reset by peer.
```

**Comment by brauner** [comment]
So there's some additional info I need:
- Is this a loop backed LVM Pool or a Block-Service backed LVM Pool?
- What exactly resides on Fat32, the backup or the /var/lib/lxd directory?
If indeed the symlinks are broken due to the backup residing on a Fat32 FS you need to manually recreate them.
- Please paste the output of `lxc storage list` and the output of `lxc storage show <pool-name>` for any defined storage pool.
- Please show the output of `ls -al /var/lib/lxd/containers` and the output of `/var/lib/lxd/storage-pools/<pool-name>/containers` for all defined storage pools.
- Was the pool functional before the backup?

**Comment by Laguna-x** [comment]
@brauner ,
- LVM Pool stays as-is from the beginning, like containers' lvs. when system crushed (don't know whats matter was), all of containers was started. then at reboot there was fsck with error-corrections (in asks there was at most /usr's subdirs, that resides on same VG with lxd's pool).
- yes. mount /dev/sde1 /mnt | cp -R /var/lib/lxd /mnt | umount /mnt

```
root@mSys:/var/lib# service lxd stop
root@mSys:/var/lib# rm -R ./lxd
root@mSys:/var/lib# cp -R /var/backups/var_lib_lxd/lxd ./
root@mSys:/var/lib# service lxd start
root@mSys:/var/lib# lxc storage list
+---------+--------+------------------------------------+---------+
|  NAME   | DRIVER |               SOURCE               | USED BY |
+---------+--------+------------------------------------+---------+
| LXCPool | lvm    | Data                               | 18      |
+---------+--------+------------------------------------+---------+
| default | dir    | /var/lib/lxd/storage-pools/default | 0       |
+---------+--------+------------------------------------+---------+
root@mSys:/var/lib# lxc storage show LXCPool
config:
  lvm.thinpool_name: LXDThinpool
  lvm.vg_name: Data
  source: Data
name: LXCPool
driver: lvm
used_by:
- /1.0/containers/cert
- /1.0/containers/database
- /1.0/containers/dns
- /1.0/containers/dns/snapshots/snap0
- /1.0/containers/github
- /1.0/containers/inet
- /1.0/containers/mail
- /1.0/containers/ntp
- /1.0/containers/openvpn
- /1.0/containers/svn
- /1.0/containers/svn/snapshots/svn-snap0
- /1.0/containers/test
- /1.0/containers/unifi
- /1.0/containers/unifi/snapshots/snap0
- /1.0/containers/unifi/snapshots/uni-snap0
- /1.0/images/0459336f62389d73349a078aaca600bb8602fab388aaaadb5c7e2aa4f24c3b05
- /1.0/images/98f8bc4f213436d3c4ae825cb8c13d8e30407b5beb89c0f40d22e98f2560930b
- /1.0/profiles/default
root@mSys:/var/lib# lxc storage show default
config:
  source: /var/lib/lxd/storage-pools/default
name: default
driver: dir
used_by: []
root@mSys:/var/lib# ls -al /var/lib/lxd/containers
итого 284
drwx--x--x  2 root root   4096 апр 17 16:15 .
drwxr-xr-x 12 root root   4096 апр 17 16:15 ..
-rwxr-xr-x  1 root root 280985 апр 17 16:15 lxc-monitord.log
root@mSys:/var/lib# ls -al /var/lib/lxd/storage-pools/
default/ LXCPool/
root@mSys:/var/lib# ls -al /var/lib/lxd/storage-pools/LXCPool/containers/
итого 52
drwx--x--x 13 root root 4096 апр 17 16:15 .
drwx--x--x  5 root root 4096 апр 17 16:15 ..
drwx--x--x  2 root root 4096 апр 17 16:15 cert
drwx--x--x  2 root root 4096 апр 17 16:15 database
drwx--x--x  2 root root 4096 апр 17 16:15 dns
drwx--x--x  2 root root 4096 апр 17 16:15 github
drwx--x--x  2 root root 4096 апр 17 16:15 inet
drwx--x--x  2 root root 4096 апр 17 16:15 mail
drwx--x--x  2 root root 4096 апр 17 16:15 ntp
drwx--x--x  2 root root 4096 апр 17 16:15 openvpn
drwx--x--x  2 root root 4096 апр 17 16:15 svn
drwx--x--x  2 root root 4096 апр 17 16:15 test
drwx--x--x  2 root root 4096 апр 17 16:15 unifi
root@mSys:/var/lib# ls -al /var/lib/lxd/storage-pools/default/containers/
ls: невозможно получить доступ к '/var/lib/lxd/storage-pools/default/containers/': Нет такого файла или каталога
root@mSys:/var/lib# ls -al /var/lib/lxd/storage-pools/
default/ LXCPool/
root@mSys:/var/lib# ls -al /var/lib/lxd/storage-pools/default/
итого 8
drwx--x--x 2 root root 4096 апр 17 16:15 .
drwx--x--x 4 root root 4096 апр 17 16:15 ..
root@mSys:/var/lib#
```

don't remember at what moment i copied /var/lib/lxd, but may be this was when system fails. but as i remember i tried to ls -la -R on this folder and seen most of symlinks, that i don't see now.

**Comment by Laguna-x** [comment]
@brauner , is it possible to safly make this schema:
 on clean system make containers, add networks to them, stop lxd and replace all containers' LVs with old LVs (like dd if=old of=/dev/VG/c*_new)? does container contains any of settings for dirrecories/uuids/or others that can broke this schema?

**Comment by brauner** [comment]
So I'm not sure what questions you answered so I'm reiterating to make sure that we are on the same page. The affected pool is a block device backed pool. I is only the backup that resides in a Fat32 FS.

So, this really seems to be caused by broken symlinks. None of the symlinks for the containers exist. I suspect it's the same for images and snapshots. To recover your containers you can use `lxd import` and import your containers one-by-one. So, to import a container you can use: `lxd import --force <container-name>` . This assumes that the storage volumes for the containers are mounted in their appropriate locations. If they aren't, please mount them manually.

**Comment by Laguna-x** [comment]
@brauner , sorry if i'm hard to understend, 3 days without rest and sleep makes me broken.
yes dst is fat32 fs (usb stick).

about import: huston, i have troubles

```
root@mSys:/var/lib# lxd import ntp --force
error: The container's directory "/var/lib/lxd/storage-pools/LXCPool/containers/ntp" appears to be empty. Please ensure that the container's storage volume is mounted.
root@mSys:/var/lib# lxc start ntp
error: Failed to run: /usr/bin/lxd forkstart ntp /var/lib/lxd/containers /var/log/lxd/ntp/lxc.conf:
Try `lxc info --show-log ntp` for more info
root@mSys:/var/lib# lxd import ntp --force
error: open /var/lib/lxd/containers/ntp/backup.yaml: no such file or directory
```

**Comment by Laguna-x** [comment]
don't know what is metter with them, but tomorrow i'll try to clean system, create new lvm pool with lxc containers and next just mount and copy old to new. i think now it will be fastest way. i'v gon to sleep.

P.S. i think it needs to implement lxd backup | lxd restore feauteres. somthing like:
lxd {backup|restore} <container> - backup/restore full container (to tar or other). or another feautere {stack|unstack} and {import(implemented but needs to be better)|export(i think it must be something with dir-structure and some hardware independed settings, that it can be imported anywere on any storage)}
lxd {backup|restore} config - something with checking all of settings and dirrrectory structure.

**Comment by brauner** [comment]
Also I've mentioned in my previous comment for lxd import to work the containers storage volumes needs to be mounted. If I isn't you need to make sure it is. This should be possible by just doing: `mount /dev/<vg-name>/containers_<container-name> /var/lib/lxd/storage-pools/<pool-name>/containers/<container-name>` . The correct path for the lvm volume group can be gathered by looking at the available lvs under the corresponding vg name in `/dev`.

Note that you really shouldn't try to keep a non-zip backup of a directory that uses symlinks on a non-symlink supporting fs. :)

**Comment by Laguna-x** [comment]
@brauner , is it possible to use existing pool?
and i think, that "lxd import" better looks as "lxc storage import <driver> <pool> [<lv>] [<driver-dst> <other dst optinons>]", so lxc storage <expot|import> can export and import lv and existing pool.
may be it will be feauture.

**Comment by brauner** [comment]
It is currently not possible to import an existing storage pool.

**Comment by brauner** [comment]
Available backup strategies are outlined here: https://github.com/lxc/lxd/blob/master/doc/backup.md .

**Comment by Laguna-x** [comment]
@brauner, don't know how, but:
After one container was restored with
```
lxc launch debian/jessie dns
lxc stop dns
dd if=backedup_LV of=/dev/<VG>/container_dns
lxc start dns
```
container was mounted and worked for some time (with rebooting inclusive).
But at one moment system returned to issue #3178.
One that i does with system between this moments - is configuring networking (bonding-openvswitch-lxd_container)

next restorations leads to same issue :(

**Comment by Laguna-x** [comment]
issue with braking system and mounting errors look at  #3178. all other are working fine.

About restoring:
dd work was fine. containers restored. networks created manualy and attached.
Some brief from me to work with lxd for backup|restore purposes with lvm:
1) make logical volume for /var/lib/lxd and add it to fstab
2) if /usr/lib/x86_64-linux-gnu resides on SSD-like disk make logical volume for /usr/lib/x86_64-linux-gnu/lxc

next time to backup all system you can 'dd' this logical volumes safely or make lv-snapshots.

to restore system from null it needs to do lxc create <container> for every container, or manualy create containers' volumes on lxd's thin-pool and 'dd' backups on them. And 'dd' with '/var/lib/lxd'-backup.

i think this schema or some elements may be used in 'lxd backup'.
