### ISSUE TITLE
Cannot change/set static ipv6 address

### ISSUE THREAD

**Issue by petergloor** [lxc/lxd#3192]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 (Xenial)
 * LXC/LXD 2.12 from xenial-backports
 * The output of "lxc info":
[see attached lxc_info.txt](https://github.com/lxc/lxd/files/936612/lxc_info.txt)

# Issue description

I wanted to give a container static ipv4 and ipv6 addresses from outside the container. While it was easy to change the containers ipv4 address I cannot change its ipv6 address using the same workflow. As I'm new to containers I guess I'm doing something wrong, but it might be a bug.

# Steps to reproduce

I configured lxd with an lxdbr0 bridge with IPv4 and IPv6.
The relevant part in the config looks like this:

    ipv4.address: 10.122.45.1/24
    ipv4.nat: "true"
    ipv6.address: fd42:7146:f400:1::1/64
    ipv6.nat: "true"
  
After I launched a container with Xenial (contxenial) its ifconfig for eth0 looked something like this:

    peter@led:~$ lxc exec contxenial -- ifconfig eth0
    eth0      Link encap:Ethernet  HWaddr 00:16:3e:2e:37:ad
              inet addr:10.122.45.250  Bcast:10.122.45.255  Mask:255.255.255.0
              inet6 addr: fe80::216:3eff:fe2e:37ad/64 Scope:Link
              inet6 addr: fd42:7146:f400:1:216:3eff:fe2e:37ad/64 Scope:Global
             :

Now I wanted to change both, its ipv4 *AND* its ipv6 address to static ip adresses using the following commands:

    peter@led:~$ lxc network attach lxdbr0 contxenial eth0
    peter@led:~$ lxc config device set contxenial eth0 ipv4.address 10.122.45.71
    peter@led:~$ lxc config device set contxenial eth0 ipv6.address fd42:7146:f400:1::71

Finally I restarted my container.

    peter@led:~$ lxc restart contxenial

To my surprise the IPv4 address changed as expected, but the IPv6 address did not!

    peter@led:~$ lxc exec contxenial -- ifconfig eth0
    eth0      Link encap:Ethernet  HWaddr 00:16:3e:2e:37:ad
              inet addr:10.122.45.71  Bcast:10.122.45.255  Mask:255.255.255.0
              inet6 addr: fe80::216:3eff:fe2e:37ad/64 Scope:Link
              inet6 addr: fd42:7146:f400:1:216:3eff:fe2e:37ad/64 Scope:Global
             :

However, dnsmasq.hosts contains both, the changed IPv4 address as well as the changed IPv6 address.
		  
    peter@led:~$ sudo cat /var/lib/lxd/networks/lxdbr0/dnsmasq.hosts
    00:16:3e:2e:37:ad,id:*,10.122.45.71,[fd42:7146:f400:1::71],contxenial

# Information to attach

 - [ ] any relevant kernel output (dmesg)
[dmesg.txt](https://github.com/lxc/lxd/files/936738/dmesg.txt)

 - [ ] container log (lxc info NAME --show-log)
[lxc_info_contxenial.txt](https://github.com/lxc/lxd/files/936747/lxc_info_contxenial.txt)

 - [ ] main daemon log (/var/log/lxd/lxd.log)
[lxd.log.txt](https://github.com/lxc/lxd/files/936749/lxd.log.txt)

 - [ ] lxc log and conf files from /var/log/lxd/contxenial
[lxc.log.txt](https://github.com/lxc/lxd/files/936787/lxc.log.txt)
[lxc.log.old.txt](https://github.com/lxc/lxd/files/936789/lxc.log.old.txt)
[lxc.conf.txt](https://github.com/lxc/lxd/files/936790/lxc.conf.txt)

**Comment by stgraber** [comment]
Static IPv6 assignment can only work in stateful DHCP mode as otherwise SLAAC is used to assign the address.

You can enable stateful DHCP with:
    lxc network set lxdbr0 ipv6.dhcp.stateful true

But note that no Linux distribution does DHCPv6 by default, so you'll also need to update your container's /etc/network/interfaces (or similar based on distribution) to actually do DHCPv6.

**Comment by petergloor** [comment]
Thank you for the clarification.

**Comment by owenson** [comment]
Hi

There doesn't seem to be a way to use a subnet smaller than /64 for ipv6?  Or at least it doesn't seem to work even with stateful set.

Some servers get allocated a /64, and it's useful to run lxd containers onthem.

**Comment by stgraber** [comment]
@owenson I can reproduce that behavior, though I can't tell what we'd be doing wrong on the dnsmasq side...

In my case I tried with 2001:470:b368:4243::1/92 and I see us pass this to dnsmasq:

    --dhcp-range 2001:470:b368:4243::2,2001:470:b368:4243:0:f:ffff:ffff,1h

Which looks like the proper range for the /92. Yet dnsmasq logs this:

    Nov  5 06:23:57 castiana dnsmasq-dhcp[16620]: no address range available for DHCPv6 request via limitedv6

So starting to suspect a dnsmasq bug there...
