### ISSUE TITLE
lxc restart fails while stop/start work fine

### ISSUE THREAD

**Issue by vds** [lxc/lxd#3195]
# Required information

 * Distribution: Ubuntu Server
 * Distribution version: 16.04 Xenial
 * The output of "lxc info":   https://paste.ubuntu.com/24419168/

# Issue description

Using lxc restart fails and return an error, while stopping and then restarting the container works.

# Steps to reproduce

See: https://paste.ubuntu.com/24419156/

**Comment by stgraber** [comment]
Can you paste "lxc config show --expanded xenial-maas"?

**Comment by vds** [comment]
https://paste.ubuntu.com/24446717/

**Comment by stgraber** [comment]
Thanks, that should be enough to try to reproduce this.

**Comment by stgraber** [comment]
I'm unable to reproduce this with 2.13, will try on 2.0.9 and 2.0.10 next.

**Comment by stgraber** [comment]
So I'm also unable to reproduce this on LXD 2.0.9...

**Comment by stgraber** [comment]
Yep, completely unable to reproduce it here, running lxd 2.0.9 with dir backend, the maas profile and a container using it. Ran a dozen "lxc restart xenial-maas", all of which succeeded.

**Comment by stgraber** [comment]
Marking Incomplete and moving out of the 2.14 milestone.
