### ISSUE TITLE
Problem restoring container

### ISSUE THREAD

**Issue by pepanillo** [lxc/lxd#3198]
lxd version 2.12 on ubuntu server 16.04

Trying to restore the backup of a container lxd import <container_name> gives me the following error:
error: open /var/lib/lxd/storage-pools/lxd/snapshots/<container_name>: no such file or directory

To make the backup the steps were:
- lxc stop <container_name>
- cd /var/lib/lxd/storage-pools/lxd/containers
- tar --create --verbose --gzip <container_name> --file /temp/<container_name.tgz>

Then I remove the container with lxc destroy <container_name>

To restore the backup the steps are:
- cd /temp
- tar --extract --verbose --file=/temp/<container_name>.tgz
- zfs create lxd/containers/<container_name> -o mountpoint=/var/lib/lxd/storage-pools/lxd/containers/<container_name>
- ln -s /var/lib/lxd/storage-pools/lxd/containers/<container_name> /var/lib/lxd/containers/<container_name>
- lxd import <container_name>

And I get the error indicated before.

This worked for me with version 2.11.

**Comment by brauner** [comment]
Did the original container have snapshots?

**Comment by pepanillo** [comment]
No.

**Comment by pepanillo** [comment]
Actually no.

**Comment by pepanillo** [comment]
The folder /var/lib/lxd/storage-pools/lxd/snapshots does not exists.

**Comment by pepanillo** [comment]
mkdir /var/lib/lxd/storage-pools/lxd/snapshots will solve the problem?

**Comment by brauner** [comment]
It should. Can you try?

**Comment by pepanillo** [comment]
Yes. I've created /ver/lib/lxd/storage-pools/lxd/snapshots and give permissions 711
The same error after lxd import prueba  (prueba is <container_name>)
error: open /var/lib/lxd/storage-pools/lxd/snapshots/prueba: no such file or directory

**Comment by brauner** [comment]
Yeah, that's right. Can you try with the name of the container added. The patch I sent skips it now if it doesn't exist.

**Comment by pepanillo** [comment]
I have created /var/lib/lxd/storage-pools/lxd/snapshots/prueba and it works.
I shall try the container to see if it works fine.
Thank you so much @brauner

**Comment by brauner** [comment]
Yup, would be nice. :)

**Comment by pepanillo** [comment]
Ok. All is working fine. I shall document the process for automation the process. This patch will apply in the next release?

**Comment by brauner** [comment]
Yup, should be in `2.13`.

**Comment by pepanillo** [comment]
Ok. I'll try. Thank you very much.

**Comment by brauner** [comment]
@pepanillo, sure np. :)
