### ISSUE TITLE
tests: make storage tests less redundant

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3201]
Right now the `test/suites/storage.sh` suite runs all storage pool and volume creation tests for all backends which are supported on a given runner. So if it detects that btrfs, lvm, and zfs tools are available on a given runner it will run all the tests in `storage.sh` for all of them. While this was a good strategy to pound on the new storage api right after my branch landed it causes way too much overhead in the long run. Especially, since some tools are not happy about the heavy pressure we put on them. The obvious candidate for my very subtle slight is lvm. The metadata daemon gets really cranky when dealing with a lot of locking and so on. In any case, the idea is to make running the storage tests dependent on the backend used (`LXD_BACKEND` variable in the script) instead of on the availability of the tools.

**Comment by stgraber** [comment]
@freeekanayaka can you take a stab at this one? @brauner should be able to help you with any question you may have.

**Comment by freeekanayaka** [comment]
@stgraber yes, I'll take it
