### ISSUE TITLE
[query] Can an LXD client run a desktop environment?

### ISSUE THREAD

**Issue by kwill** [lxc/lxd#3202]
The examples given for LXD [[1]](https://www.ubuntu.com/containers/lxd) [[2]](https://linuxcontainers.org/lxd/getting-started-cli/) centre around terminal-based server use-cases. Can an LXD client run a graphical desktop environment in the same way as, for example, GNOME Boxes or VirtualBox?

<https://askubuntu.com/questions/907385/can-an-lxd-client-run-a-desktop-environment>

**Comment by stgraber** [comment]
Short answer is "no". Containers don't have virtual graphic cards so there's nothing for them to render to.

There are some alternatives though:
 - Run Xephyr or similar on the host, then pass the X socket to the container and run things against that
 - Run some kind of VNC/RDP based server in the container and connect to that from the host
 - Give the container full access to your host's devices (GPU and terminal), this would let you have your desktop environment in a container with a mostly blank host
