### ISSUE TITLE
NFS or device for share host dir with containers?

### ISSUE THREAD

**Issue by niksfirefly** [lxc/lxd#3205]
What is the better way - in terms of stability/speed - for share 
host lvm/ext4 or zfs based dir with containers
NFS or lxc device?
I assume in both options that containers must be privileged
but I am in total control of containers

regards

**Comment by stgraber** [comment]
Using an lxc "disk" device comes with 0 overhead since it's just a bind-mount at the kernel level, all other solutions will come with rather significant network overhead, though they do let you mount stuff cross-host which may be interesting.

**Comment by niksfirefly** [comment]
what about using host dir read/write with multiple containers at the same time?

**Comment by stgraber** [comment]
Sure, you can have as many bind-mount of a given host path as you want.
