### ISSUE TITLE
lxc init seems missing from help message + man page

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#3214]
Low priority issue + likely good for this to be eventually fixed.

Unsure if this is an Ubuntu packaging issue or LXD.
```
net10 # lxd --version
2.12

net10 # lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

```

```
net10 # lxc --help | grep launch
  launch           Create and start containers from images
net10 # lxc --help | grep init
```
So no help message showing how to create a container + leave it stopped.

There is help for lxc init, if you already know the init command exists.
```
net10 # lxc init --help
... help message text here ...
```

**Comment by brauner** [comment]
`lxc help --all` should do the trick.

**Comment by stgraber** [comment]
Correct, it's considered a "less common" command and is therefore only listed with --all.
The description of --all is in lxc's help message and running it then will include everything.

It's however a good point that our manpage probably ought to run with --all so we have everything listed.
