### ISSUE TITLE
lxc - unknown remote server when called from systemd service unit

### ISSUE THREAD

**Issue by audiocricket** [lxc/lxd#3222]
Hi there,

seems like there's some issue when we try to init containers from our own remote server and the problem is that it fails exclusively when it's run from our own systemd service unit. `lxc init` reports it can't find our custom remote server.

So I've been stracing `lxc init <remote>:<image>` and when it's run locally from console, it tries to open config.yml from the `/root/.config/lxc` directory and this is the expected behavior:

```
root@tpl-do:~# grep config.yml lxc.init.local
openat(AT_FDCWD, "/root/.config/lxc/config.yml", O_RDONLY|O_CLOEXEC) = 3
```
However, strace shows something different when run from systemd service unit:

```
root@tpl-do:~# grep config.yml lxc.init.systemd
openat(AT_FDCWD, "/.config/lxc/config.yml", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

We can of course work around this by symlinking, but that's not proper fix. This happens on latest Ubuntu 16.04.02 (fully updated) + latest LXD v2.12 from PPA.

Where can be the problem? Maybe this is the problem of our custom systemd service unit or maybe it's problem of lxc client - not sure about this behavior.

Thanks.

**Comment by stgraber** [comment]
@audiocricket that suggests that your systemd unit doesn't have the "HOME" environment variable set.

**Comment by audiocricket** [comment]
Thanks, that helped. Closing.
