### ISSUE TITLE
NAT to Docker running in container

### ISSUE THREAD

**Issue by ajthemacboy** [lxc/lxd#3227]
# Required information

 * Distribution: Host and container are both Ubuntu
 * Distribution version: Host: Ubuntu 17.04, container: Ubuntu 16.04
 * The output of "lxc info": https://gist.githubusercontent.com/ajthemacboy/1e2d2959f4a081431fc672979ce4d117/raw/f64b837f0cebd237a7ecf8e75fa4db4cd72d78b0/gistfile1.txt

# Issue description and steps to reproduce

I have successfully installed Docker in an Ubuntu 16.04 container. I did this using:
- `lxc launch ubuntu:16.04 docker -p default -p docker`
- `apt install docker.io` inside the container

It is easy to setup NAT for a LXC:

First I find the container IP in `lxc list`, here I see the LXC bridge and 2 Docker networks: 
`172.18.0.1 (docker10)`
`172.17.0.1 (docker0)`
`10.51.133.217 (eth0)`

Now I can NAT to the primary interface's IP:
`iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 10.51.133.217`

However, I cannot NAT to the Docker bridge(s), in this case 172.17.0.x or 172.18.0.x. Say my container is running on 172.x.0.5:
`iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 172.17.0.5`
`iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 172.18.0.5`

I also observe that the Docker bridge IPs are nowhere to be found in `ip a` or `ifconfig`. I would expect otherwise because the `10.51.133.1/24` (in my example) network does, but maybe I'm wrong.

I also attempted to NAT to the primary interface, eth0, from the host to the container:
`iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 10.51.133.217`
... and then to NAT from inside the container to the Docker bridge:
`iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 172.18.0.5`
... with no luck either. 

I also tried variations of these commands, replacing `-A PREROUTING` with `-I PREROUTING 1` with no success.

These commands seem to be correct to me. I can only conclude that the Docker bridges, 172.17.0.1 or 172.18.0.1, are supposed to show up on the host, or that there is some networking issue.

**Comment by brauner** [comment]
Network devices that you create inside the container are created in the container's network namespace which is distinct from the host's network namespace. That means you won't be able to see these network devices on the host.

**Comment by ajthemacboy** [comment]
@brauner That explains why my first commands aren't working. But do you know why forwarding from Host > LXC > Docker isn't working? These commands work in a normal Docker environment. I have also tried starting Docker with `--iptables=false`.

**Comment by brauner** [comment]
Is the Docker daemon and the container's it is running able to reach the internet?

**Comment by stgraber** [comment]
@ajthemacboy so what you did at the end looks good. NAT from host to container and the in container NAT from container to docker.

However note that PREROUTING won't be caught for traffic coming from your host, so if you run your web browser on your host, you'll need an extra OUTPUT rule for the host part.

On host:
```
iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 10.51.133.217
iptables -t nat -A OUTPUT -p tcp --dport 8080 -j DNAT --to-destination 10.51.133.217
```

In container:
```
iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 172.18.0.5
iptables -t nat -A OUTPUT -p tcp --dport 8080 -j DNAT --to-destination 172.18.0.5
```

**Comment by ajthemacboy** [comment]
@stgraber Thank you, that works! Sorry for making an issue for a support problem.
