### ISSUE TITLE
"lxc network show <remote>:" (without a network name) fails with a weird error

### ISSUE THREAD

**Issue by rkelleyrtp** [lxc/lxd#3230]
================================
# Required information
================================
 * Distribution: Ubuntu

 * Distribution version: 17.04

 * The output of "lxc info" or if that fails:
--------------------------------------------
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.0.0.130:8443
  - 192.168.122.1:8443
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-20-generic
  server: lxd
  server_pid: 2703
  server_version: "2.12"
  storage: ""
  storage_version: ""
--------------------------------------------

# Issue description
When executing the command, "lxc network show <remote_host>: command, the error message "error: json: cannot unmarshal array into Go value of type" is returned.

# Steps to reproduce

 1. Setup two identical LXD servers
 
2. Enable server 1 to remotely manage server 2:
    lxc config set core.https_address [::]:8443
    lxc config set core.trust_password <my_pass>

 3. Add remote server to server 1
  lxc remote add <remote_server> <remote_IP>

4. run the command, "lxc network show <remote_server>"

I was expecting to get a list of network interfaces attached/configured on the remote server.  However, the error message was returned instead.

**Comment by stgraber** [comment]
Sounds like your server is running LXD 2.0.x which doesn't have the network API and the client code is getting confused as a result :)

**Comment by rkelleyrtp** [comment]
I am running Ubuntu 17.04 with LXD 2.12.  Is there a newer version of LXD?

**Comment by stgraber** [comment]
is that what your remote server is running too?

**Comment by stgraber** [comment]
above very much suggests that your remote server isn't

**Comment by rkelleyrtp** [comment]
Yes, all 5 servers (1 manager and 4 remote) were cloned from a master U17.04 server this morning.

**Comment by stgraber** [comment]
Oh right, I misread, it's a different problem than what I was thinking about.
The problem is that you're running "lxc network show remote-name:" rather than "lxc network show remote-name:network-name"

Our client should do a better job at telling you that you must type in the name of a network though.

**Comment by rkelleyrtp** [comment]
Gotcha.  I should have run the command, “lxc network list <remote>:” instead as I wanted to get a list of configured networks on the remote site.

**Comment by stgraber** [comment]
Yep, lets keep this issue open to make sure we get a better error message for this.
