### ISSUE TITLE
lxd should clear the interface volatile keys as part of Update()

### ISSUE THREAD

**Issue by rkelleyrtp** [lxc/lxd#3231]
# Required information

 * Distribution: Ubuntu

 * Distribution version: 17.04

 * The output of "lxc info" or if that fails:
==========================
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.0.0.134:8443
  - 172.17.238.14:8443
  - 192.168.122.1:8443
  architectures:
  - x86_64
  - i686

  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-20-generic
  server: lxd
  server_pid: 2966
  server_version: "2.12"
  storage: dir
  storage_version: "1"
root@LXD-QA-Server-04:~#
==========================

# Issue description

When removing network interfaces via the "lxc network detach" command, the interface index presented to the container (ie: eth0, eth1, etc) does not get reset.  As a result, the static network configuration for the container is no longer valid, and the container can't get an IP address.

# Steps to reproduce

1. Ensure no network interfaces are configured in the default profile

2. Launch a new Ubuntu container

3. Attach a new network interface via the command "lxc network attach eth0 <container_name>"

4. Run the command, "lxc config show <container_name> - taking note of the devices section.  Example:
-------------------------------------------
devices:
  eth0:
    nictype: macvlan
    parent: eth0
    type: nic
-------------------------------------------

5. Execute a shell inside the container and type "ip a s" - should see one interface at "eth0"

6. Stop the container, detach the interface, and attach a new interface:  
lxc network detach eth0 <container_name>"
lxc network attach eth1 <container_name>"

7. Run the command, "lxc config show <container_name> - taking note of the devices section.  The device list should be correct, but the "volatile" information still shows eth0 and eth1.

8. Start the container again, get a shell, and type "ip a s".  This time, the interface index is eth1 instead of eth0.  Since this is the only interface configured for this device, I would expect to see eth0 only.

The same combination of events can also cause the old interface to retain its original id.  In the case above, if I remove "eth2", add eth3, then add eth2 back, the container retains the old eth2 details.

It seems the code that indexes the interfaces is not cleaning out the old values.  Thus, the container could end up with the wrong interfaces connected.

Real-world example:
-----
* We provision containers on eth0 to perform initial configs on our setup network.
* Once the provisioning is done, we move the container to our production network by detaching the setup network interface and attaching the production network interface (eth0 and eth2 respectively) and applying the necessary IP addresses in the container's network configuration files.
* The above scenario prevents our auto-setup scripts from working as the "eth0" interface is now "eth1".

The only way to fix this issue is to copy the container to a new container ID.  The copying process seems to fix the network index issue.

**Comment by stgraber** [comment]
You have a point that we should try to cleanup the volatile keys better. I believe we do clean them up, but they need a container restart without any change for things to sync up.

But in your case, you really should use:

    lxc network attach eth1 <container name> eth0 eth0

Which will ensure that LXD creates a device named "eth0" and have the interface name set to "eth0" in the container, this way the volatile keys aren't used to assign a non-conflicting name at all and things will be exactly the way you want it.

**Comment by rkelleyrtp** [comment]
Thanks for the info.  I did not know about the "extended" attach command.


Also, is it possible to get the parent interface via the “lxc list” command?  In our use case, we use vxlan IDs; it would be great if we could run “lxc list <some_arg>” to see which parent network interface is used.  The only keys I could find were these:

lxc list -c abclnpst46
+--------------+--------------+----------------------+----------------------+---------+------+---------+------------+--------------------+------+
| ARCHITECTURE | STORAGE POOL |      CREATED AT      |     LAST USED AT     |  NAME   | PID  |  STATE  |    TYPE    |        IPV4        | IPV6 |
+--------------+--------------+----------------------+----------------------+---------+------+---------+------------+--------------------+------+
| x86_64       | local        | 2017/04/26 18:12 UTC | 2017/04/26 20:58 UTC | new-one | 4309 | RUNNING | PERSISTENT | 32.32.32.41 (eth2) |      |
+--------------+--------------+----------------------+----------------------+---------+------+---------+------------+--------------------+———+


Thanks.

**Comment by stgraber** [comment]
@rkelleyrtp I don't think the kernel even tells us that :)

You can see what LXD configured with "lxc config show --expanded new-one" but the user in the container can rename the interface as they see fit and at that point there's not a lot of tracking we can still do.
