### ISSUE TITLE
Unable to 'lxd forkstart' on ARM ThunderX

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#3232]
https://bugs.launchpad.net/juju/+bug/1686420

Its possible that Juju is configuring the containers incorrectly in some fashion, but the errors from LXD aren't particularly informative to help us understand what we are doing wrong. We need a bit of assistance in understanding what we should be changing.

**Comment by brauner** [comment]
As mentioned in the Launchpad issue, we'd need all logs from `/var/log/lxd`, especially the daemon log and the log for the failing container(s).

**Comment by brauner** [comment]
Quoting Sean Feole verbatim from https://bugs.launchpad.net/juju/+bug/1686420:

> Marking bug Invalid as I have identified the cause of this, MAAS has been configuring /dev/USB devices to boot from, in this particular case. I have been trying to reproduce this issue the past day. After further investigation I noticed that the disk devices in some of our MAAS machines are configured to boot from USB. After removing this disk configuration (in MAAS) I was able to successfully launch lxd containers under load within a reasonable amount of time.
>
> The issue appears to be bugged, however configured as a "Wishlist" item.
>
> https://bugs.launchpad.net/maas/+bug/1307614
>
> Users need to take precaution when adding devices to MAAS with USB devices.
