### ISSUE TITLE
LXD PPA missing 2.13

### ISSUE THREAD

**Issue by MarkGavalda** [lxc/lxd#3234]
Even though 2.13 was released a couple of days ago the official PPA hasn't been updated since, can someone look into it, please? Thanks!

**Comment by brauner** [comment]
@MarkGavalda I'm sure @stgraber is already on top of this. Afaik, we had some issues with golang shared libraries that blocked us but they should be resolved soon.

**Comment by stgraber** [comment]
Right, it's the first upload through Ubuntu Artful and it got stuck for a while, I'll do the PPA setup today which should then populate with 2.13.
