### ISSUE TITLE
Error Running LXC-TO-LXD script

### ISSUE THREAD

**Issue by mheroux2** [lxc/lxd#3237]
I have a vanilla Ubuntu 16.04 and I'm trying to run the lxc-to-lxd python script to migrate numerous LXC containers to LXD. With the first container I get the following:

root@seuropa:~# python3 lxc-to-lxd pumelo-test
==> Processing container: pumelo-test
Parsing LXC configuration
Container fstab file doesn't exist, skipping...
Traceback (most recent call last):
  File "lxc-to-lxd", line 613, in <module>
    container_name, args)
  File "lxc-to-lxd", line 228, in convert_container
    found_keys = config_keys(lxc_config)
  File "lxc-to-lxd", line 125, in config_keys
    for line in config:
TypeError: 'bool' object is not iterable

**Comment by stgraber** [comment]
What version of LXD is this?

**Comment by stgraber** [comment]
(Fully up to date 16.04 should be LXD 2.0.9)

**Comment by stgraber** [comment]
Oh though we don't package the script so you've likely downloaded it from github directly right?

**Comment by mheroux2** [comment]
I was wondering if the script was bundled with the latest, for that and other reasons I upgraded:

sudo add-apt-repository ppa:ubuntu-lxc/lxd-git-master && sudo apt-get update
sudo apt-get install lxd

Also wget the script the latest version of the script. Thanks for the quick replies

**Comment by mheroux2** [comment]
root@seuropa:/home/it# lxd --version
2.12

**Comment by stgraber** [comment]
@mheroux2 yup, found a pretty obvious bug in there :)

**Comment by stgraber** [comment]
@mheroux2 can you paste the /var/lib/lxc/NAME/config file for your container?

The problem appears to be that you have a lxc.mount entry in your config which points to a path that doesn't exist, or that our script doesn't understand.

**Comment by stgraber** [comment]
So I fixed the obvious bug in there, but I still want to understand why you have what our script think is a bad lxc.mount entry and if there's something else we should be doing there.

**Comment by mheroux2** [comment]
I corrected the config (previously it was pumelo, when it should have been pumelo-test). Now I'm getting 

root@seuropa:/var/lib/lxc/pumelo-test# python3 ~/lxc-to-lxd pumelo-test
==> Processing container: pumelo-test
Parsing LXC configuration
Checking for unsupported LXC configuration keys
Found at least one unsupported config key lxc.devttydir: 
Not importing this container, skipping...

==> Migration summary
pumelo-test: FAILURE

Here's the config you asked for:

lxc.network.type=veth
lxc.network.link=acad
lxc.network.flags=up

lxc.cgroup.cpu.shares = 512
lxc.cgroup.memory.limit_in_bytes = 512M
lxc.cgroup.memory.memsw.limit_in_bytes = 512M
lxc.network.hwaddr = /*REMOVED*/
lxc.utsname = pumelo

lxc.devttydir = lxc
lxc.tty = 4
lxc.pts = 1024
lxc.mount  = /var/lib/lxc/pumelo-test/fstab
lxc.arch = amd64
lxc.cap.drop = sys_module mac_admin
lxc.pivotdir = lxc_putold

# uncomment the next line to run the container unconfined:
#lxc.aa_profile = unconfined

lxc.cgroup.devices.deny = a
# Allow any mknod (but not using the node)
lxc.cgroup.devices.allow = c *:* m
lxc.cgroup.devices.allow = b *:* m
# /dev/null and zero
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
# consoles
lxc.cgroup.devices.allow = c 5:1 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
#lxc.cgroup.devices.allow = c 4:0 rwm
#lxc.cgroup.devices.allow = c 4:1 rwm
# /dev/{,u}random
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 5:2 rwm
# rtc
lxc.cgroup.devices.allow = c 254:0 rwm
#fuse
lxc.cgroup.devices.allow = c 10:229 rwm
#tun
lxc.cgroup.devices.allow = c 10:200 rwm
#full
lxc.cgroup.devices.allow = c 1:7 rwm
#hpet
lxc.cgroup.devices.allow = c 10:228 rwm
#kvm
lxc.cgroup.devices.allow = c 10:232 rwm
lxc.rootfs = /dev/vg00/pumelo-test

# Added by lxc postinst, migration of autostart flag
lxc.start.auto = 1
~

**Comment by mheroux2** [comment]
Uncommented out some stuff... getting further.

root@seuropa:/var/lib/lxc/pumelo-test# python3 ~/lxc-to-lxd pumelo-test
==> Processing container: pumelo-test
Parsing LXC configuration
Checking for unsupported LXC configuration keys
Checking whether container has already been migrated
Checking for existing containers
Validating container mode
Validating container name
Container name doesn't match lxc.utsname, skipping...

==> Migration summary
pumelo-test: FAILURE
root@europa:/var/lib/lxc/pumelo-test# vim config 
root@europa:/var/lib/lxc/pumelo-test# python3 ~/lxc-to-lxd pumelo-test
==> Processing container: pumelo-test
Parsing LXC configuration
Checking for unsupported LXC configuration keys
Checking whether container has already been migrated
Checking for existing containers
Validating container mode
Validating container name
Validating whether incomplete AppArmor support is enabled
Validating whether mounting a minimal /dev is enabled
Validating that no custom haltsignal is set
Validating that no custom rebootsignal is set
Validating that no custom stopsignal is set
Validating container rootfs
Processing network configuration
Processing environment configuration
Processing container boot configuration
Processing container apparmor configuration
Processing container seccomp configuration
Processing container SELinux configuration
Processing container capabilities configuration
Custom capabilities aren't supported, skipping...

==> Migration summary
pumelo-test: FAILURE

**Comment by mheroux2** [comment]
Original problem was with my config. Not the script. 

I recommend not hard coding LXC toggles and making script smarter. This should be bundled.

Closed
