### ISSUE TITLE
file push broken on windows with 2.13

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3240]
# Required information

   * LXC version: 2.13

# Issue description

Pushing file from Windows results in file with backslashes written to root.

# Steps to reproduce

```
> lxc file push 01install.sh node:remote/01install.sh
> lxc exec remote:cpm -- ls
> lxc exec remote:cpm -- ls /
'C:\01install.sh'  boot  etc ...
```

```
> lxc file push 01install.sh node:remote/root/01install.sh
> lxc exec remote:cpm -- ls /
'C:\root\01install.sh' ...
```

# Information to attach

 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
Doh, that code is so fragile...

@brauner I'm guessing your fix caused this, can you take a look?

**Comment by techtonik** [comment]
`targetPath, err := filepath.Abs(targetPath)` - looks like the problem is here.

**Comment by techtonik** [comment]
I've fixed it locally. Submitting patch right now.
