### ISSUE TITLE
error: The container is currently running, stop it first or pass --force.

### ISSUE THREAD

**Issue by givre** [lxc/lxd#3243]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

  *Operating System: Ubuntu 16.04.2 LTS
   *Kernel: Linux 4.4.0-75-generic

   * LXC version: 2.13
   * LXD version: 2.13
   * Storage backend in use: ZFS

# Issue description
The command : 
`lxc move CT1  remote-node:`
Give this result, after a while :
`error: The container is currently running, stop it first or pass --force.`

A brief description of what failed or what could be improved.
It looks like the container is actually migrated on the other node but the error message appears at the end. 
A  the container is running and `lxc move` is used , I guess it should move it anyways, even if it's running 
Or the error message should be before moving the container :) 

Live migration have to be with --force then ?

**Comment by givre** [comment]
Looks like I can't even use this --force option 

`error: flag provided but not defined: --force`

**Comment by stgraber** [comment]
The error comes from the fact that "lxc move" effectively calls "lxc delete" after it's done copying the container. However the fact that the source container is still running at that point is puzzling.

For you to be able to move a running container, I'm assuming you're running CRIU on both hosts?

**Comment by givre** [comment]
Yes , from the last version you share : 
https://launchpad.net/ubuntu/+source/criu/2.12.1-2ubuntu1/+build/12473819

**Comment by stgraber** [comment]
Ok, can you share /var/log/lxd.log from the source and target servers?

The one case where I see something like this could happen is if the source server didn't stop the container post-dump, which would be a bit of a problem.

**Comment by givre** [comment]
From the source (where the container is running)
`--------------
actionscript=true created=2017-04-26T02:59:25+0000 ephemeral=false lvl=info msg="Migrating container" name=container-name statedir=/tmp/lxd_checkpoint_606511839 stop=true t=2017-04-28T04:53:24+0200 used=2017-04-26T22:49:19+0000
actionscript=true created=2017-04-26T02:59:25+0000 ephemeral=false lvl=info msg="Failed migrating container" name=container-name statedir=/tmp/lxd_checkpoint_606511839 stop=true t=2017-04-28T04:53:32+0200 used=2017-04-26T22:49:19+0000
`

From the destination :
`
--------------
ephemeral=false lvl=info msg="Creating container" name=container-name t=2017-04-28T04:49:16+0200
ephemeral=false lvl=info msg="Created container" name=container-name t=2017-04-28T04:49:16+0200
lvl=warn msg="Unable to update backup.yaml at this time." name=container-name t=2017-04-28T04:49:17+0200
lvl=warn msg="Unable to update backup.yaml at this time." name=container-name t=2017-04-28T04:49:17+0200
err="migration dump failed\n(00.181049) Warn  (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)\n(00.725959) Warn  (criu/arch/x86/crtools.c:138): Will restore 7137 with interrupted system call\n(01.485339) Warn  (criu/arch/x86/crtools.c:138): Will restore 7395 with interrupted system call\n(01.693395) Warn  (criu/arch/x86/crtools.c:138): Will restore 7396 with interrupted system call\n(01.885061) Warn  (criu/arch/x86/crtools.c:138): Will restore 7398 with interrupted system call\n(02.088788) Warn  (criu/arch/x86/crtools.c:138): Will restore 7399 with interrupted system call\n(07.905815) Error (criu/util.c:670): exited, status=1\n(07.905833) Error (criu/action-scripts.c:94): Script /tmp/lxd_checkpoint_606511839/action.sh exited with -1\n(07.905842) Error (criu/action-scripts.c:138): One of more action scripts failed" lvl=eror msg="Error during migration sink" t=2017-04-28T04:53:32+0200
created=2017-04-28T02:49:16+0000 ephemeral=false lvl=info msg="Deleting container" name=container-name t=2017-04-28T04:53:32+0200 used=1970-01-01T00:00:00+0000
lvl=eror msg="Rsync receive failed: /tmp/lxd_restore_308058642/: exit status 12: rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]\nrsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.1]\n" t=2017-04-28T04:53:32+0200
created=2017-04-28T02:49:16+0000 ephemeral=false lvl=info msg="Deleted container" name=container-name t=2017-04-28T04:53:33+0200 used=1970-01-01T00:00:00+0000
`

**Comment by stgraber** [comment]
And you say you ended up with the container on the target anyway, despite the log showing LXD deleting it?

**Comment by stgraber** [comment]
@brauner any idea what's going on here? Kinda looks like lxc/copy is ignoring errors or something along those lines. Both logs show a whole bunch of errors...

**Comment by brauner** [comment]
I can reproduce the error but the container get's deleted on error on the sink.

**Comment by givre** [comment]
No, sorry, I was not what I was saying . 
I this the container is going to the remote node. Transferring all the data (i guess) and at the end , cancel it as the log says.  The container on the remote is deleted and the one on the source is still running

**Comment by givre** [comment]
Thanks for the quick fix
