### ISSUE TITLE
Importing the same image twice (lxc image import) results in an SQL error

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3244]
```
stgraber@castiana:~/data/code/lxc/lxd/a (stgraber/new-client)$ lxc image export 401
Image exported successfully!           

stgraber@castiana:~/data/code/lxc/lxd/a (stgraber/new-client)$ lxc image import meta-401.tar.xz 401.tar.xz 
error: UNIQUE constraint failed: images.fingerprint
```

**Comment by stgraber** [comment]
@albertodonato assigning to you as something you can take a look at when not working on that "description" branch.

**Comment by albertodonato** [comment]
@stgraber what's the expected behavior in this case? just a more meaningful error message like "Image with fingerprint XXX already present"?

**Comment by stgraber** [comment]
@albertodonato right, I'd expect a "Image 'XXX' already exists" which would be consistent with the error we return for containers, profiles, ...
