### ISSUE TITLE
Copied container retains same "internal" name as source container

### ISSUE THREAD

**Issue by stevenmunro** [lxc/lxd#3253]
* Ubuntu 16.04
driver: lxc
driver_version: 2.0.7
kernel: Linux
kernel_architecture: x86_64
kernel_version: 4.4.0-75-generic
server: lxd
server_pid: 2867
server_version: "2.13"
storage: zfs
storage_version: 0.6.5.6-0ubuntu16

`root@ip-172-31-7-137:~# lxc copy wp-source-com wp-destination-com`
`root@ip-172-31-7-137:~# lxc start wp-destination-com`
`root@ip-172-31-7-137:~# lxc exec wp-destination-com /bin/bash`
`root@wp-source-com:~#`

**Comment by stevenmunro** [comment]
Further testing

It doesn't matter what the source name is - if the destination name is a certain 'wp-thintanks-co-nz' it will take the name of the source. If I change the destination name to anything else, it works fine. So what is wrong with this particular name?

**Comment by stevenmunro** [comment]
ok, sorry for the spam here..

This appears to happen if the target container name already exists in the source container in the directory /var/lib/cloud/

**Comment by stgraber** [comment]
That's correct. LXD won't do any renaming itself. Templates in images can however decide to run when a container is created, copied, or started. In the case of the cloud-init one, it is run on copy, but cloud-init itself will not run unless the container name changed compared to what was stored in /var/lib/cloud.

Other images may behave differently as not all include cloud-init.

**Comment by stevenmunro** [comment]
Ahh thanks, it now does make a bit of sense to me. Obviously in my case I have created containers from containers from containers etc. How would I safely 'reset' cloud-init? (or make it clean without stuffing anything)

**Comment by stgraber** [comment]
Wiping /var/lib/cloud/data should do the trick to force cloud-init to re-run.
