### ISSUE TITLE
Treating LXD container as VPS with public IPv4 and IPv6 correctly.

### ISSUE THREAD

**Issue by tererero** [lxc/lxd#3254]
# Required information

 * Distribution: Ubuntu LTS
 * Distribution version: 16.04

# Issue description

Hi. I have Ubuntu 16.04 in a dedicated OVH server. I want to buy 200 IPv4, launch 200 LXD containers, and use one IPv4 for each container, and have IPv6 correctly enabled also (essentially treating LXD containers as VPS). 

I cannot gather the entire procedure by reading the documentation, and the info online seems contradictory, for example, about DHCP, static IPs, and I am having difficulty about the IPv6 implementation on OVH. 

After an ```lxd init```, what steps would be necessary for setting these static public IPv4 and IPv6 for each container and making them permanent?

Should I configure the distribution *in* the container to have a static IP in  /etc/network/interfaces, and then do a

```lxc network attach-profile eth0 default eth0```?

What is the recommendation for treating LXD containers as VPS (using LXD as a sort of hypervisor) assigning them public IPs?

Thanks

**Comment by stgraber** [comment]
OVH does IPv4 and IPv6 weirdly. In both cases they don't route the subnet to you but rather just announce it to the subnet you're connected to.

So there's no nice and easy way to carve a bunch of those IPs to assign to a LXD bridge, especially as IPv6 requires at least a /64 and OVH gives you only a partial /64 so not good enough.

Your only real option if you don't want to play the NAT game, is to have a bridge with no IPv4 and IPv6 on it at all, then on the host add a manual IPv4 and IPv6 route for each one of the IPs you want to use with your containers, then have your containers configured to use that as static assignment with the host's own IPs as the gateway.

**Comment by stgraber** [comment]
In a more normal setup where your provider actually routes subnets to your IP, as my ISP does for example, then all you'd need to do is create a LXD bridge with that routed IPv4 and IPv6 subnet (so long as that one is /64 or bigger) and things would just work automatically.

**Comment by wociscz** [comment]
Just solved it right now on ovh (after trying everything)
Not so nice but works. Follow this howto:
https://hibern8.wordpress.com/2014/03/16/ipv6-in-lxc-at-ovh/

in short:
host:
br0 (pyhisical eth0 in it) - public ipv4 and public ipv6 subnet (with ::1) from ovh, gateway to ovh :ff:ff
lxdbr0 - bridge managed by lxd with private ipv4 only (and with nat)
npd6 daemon configured and started

containers:
eth0: bridged, parent br0 (static ipv6 from ovh subnet ::2 and so on, gateway to ::1 not to :ff:ff... ovh)
eth1: bridged, parent lxdbr0 (dhcp, ipv4 gets from lxd)

So one interface for public ipv6 one for ipv4 nat. Maybe it should be nicer, but works as i want - every container has own public ipv6 (static) and ipv4 dynamic natted... 

Don't know why ovh has this crappy setup for ipv6...

**Comment by tererero** [comment]
Hi Stephan, sorry to bother you again. You said:

> Your only real option if you don't want to play the NAT game, is to have a bridge with no IPv4 and IPv6 on it at all, then on the host add a manual IPv4 and IPv6 route for each one of the IPs you want to use with your containers, then have your containers configured to use that as static assignment with the host's own IPs as the gateway.

There you said "have a bridge with no IPs on it at all". So should I create a br0 in the /etc/network/interfaces of the host without any bridge_ports line?

There you said "then on the host add a manual IPv4 and IPv6 route for each one of the IPs you want to use with your containers". What is the correct way to do that? IP Alias (br0:0 or eth0:0) and then NAT forwarding? The route command? Forwarding all ports of every IP via "iptables -t nat -A PREROUTING  -p tcp -i eth0 -d 1.2.3.5 -j DNAT --to-destination 10.11.1.2" directly to the private IP of the containers?

There you said "then have your containers configured to use that as static assignment with the host's own IPs as the gateway". From this I understand I have to modify the /etc/network/interfaces of each container with the corresponding failover IP with the host IP as the gateway. This I understand. 

Thanks for your work, God bless you.

**Comment by stgraber** [comment]
https://discuss.linuxcontainers.org/t/public-ip-in-the-ct/453 should help
