### ISSUE TITLE
lxd/main_forkexec.go:93: c.RunCommandNoWait undefined

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3258]
* Distribution: Fedora
 * Distribution version: 25
 * LXC version: b01f013

Can't compile current code.
```
go get -t -v -d ./...
go install -v   ./...
github.com/lxc/lxd/lxd
# github.com/lxc/lxd/lxd
lxd/main_forkexec.go:93: c.RunCommandNoWait undefined (type *lxc.Container has no field or method RunCommandNoWait)
Makefile:16: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by brauner** [comment]
Seems you have an old version of https://github.com/lxc/go-lxc installed. Try  `rm ~/go/pkg/linux_amd64/gopkg.in/lxc/go-lxc.v2.a' and then `make`.

**Comment by stgraber** [comment]
Yeah, we added this to go-lxc quite a while ago, make sure your dependencies are up to date.

**Comment by techtonik** [comment]
How to make sure that dependencies are installed? `go get -u github.com/lxc/lxd` didn't help.
