### ISSUE TITLE
Improve launch experience by always using cache if present (and auto-update enabled)

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3262]
It's always a bit annoying when you do "lxc launch ubuntu:16.04" and LXD then notices that a new version of the image is present, starts downloading it, making you wait for it.

To make things better here, we should:
 - Check if image auto-update is enabled. If not, keep things as they are today (look at the source and download if more recent is available).
 - If auto-update is enabled and we can locate an image which matches the requested one in the database (comparing the "source" information), then spawn the container from that

This should make the user experience quite a bit better by not having them wait for the download. If they want a particular version of an image, fingerprint based selection will keep working as it does today.

**Comment by stgraber** [comment]
@dustinkirkland that's a slightly different take on what we discussed earlier today. It achieves the same goal of not having "lxc launch" show you an image download when you have an earlier image available locally. The main change with what we discussed is that this keeps LXD on its normal image update schedule since some users may otherwise be surprised by extra background download outside of the scheduled times.

**Comment by dustinkirkland** [comment]
Right.  Thanks for capturing.

**Comment by stgraber** [comment]
@freeekanayaka assigning to you as this should be a good one to explore some of the LXD code.

**Comment by freeekanayaka** [comment]
@stgraber: Just to make sure I understand correctly, in case auto-update is enabled, this effectively means that "lxc launch ubuntu:16.04" would potentially launch an image version that is not the most recent one available remotely? (it would be the most recent one available locally). Or if it's not the case I might be confused about the current vs. desired behavior.

**Comment by brauner** [comment]
@freeekanayaka, that seems correct.

**Comment by albertodonato** [comment]
The behavior @freeekanayaka described above seems confusing to me too (from a user perspective).

Calling `lxc launch ubuntu:16.04` I would expect to get the image that's latest on that remote.

If the same image is available locally, it could of course be used, but if the one cached locally is not up to date (even if `auto-update` is set) because the deamon hasn't updated it yet, it should not be used.

**Comment by brauner** [comment]
Note, however, that if we implement https://github.com/lxc/lxd/issues/2358 by giving `ImagePut` a new `ForceUdate` field which when set to true for that image in the db will allow users to enforce the old behavior.
