### ISSUE TITLE
Add the ability to specify btrfs mount options during "lxd init" setup

### ISSUE THREAD

**Issue by rkelleyrtp** [lxc/lxd#3268]
Per the discussion thread (https://discuss.linuxcontainers.org/t/storage-pool-default-mount-options/80), please add the ability to specify btrfs mount options during "lxd init" setup.

Adding @brauner as a reference

===
From the discussion thread:
> Installed LXD 2.12 on a Ubuntu 16 server, ran the "lxd init" command, and specified a btrfs back end storage volume. I noticed the default mount parameters for btrfs were:
> 
> rw,relatime,space_cache,user_subvol_rm_allowed,subvolid=5,subvol=/
> How can I add additional options to the default mount options like "compression=lzo, autodefrag"? Right now, I manually mount the volume via /etc/fstab but would like to have lxd mount the volume if possible.
>

**Comment by brauner** [comment]
This is easy to implement but I'm not sure if we shouldn't just require users to do set this option manually via `lxc storage set <pool-name> btrfs.mount_options "rw,strictatime,user_subvol_rm_allowed"`.

**Comment by stgraber** [comment]
Yeah, we're not going to surface such low level options in the interactive "lxd init". You can very easily set it later and the non-interactive version of lxd init will let you set that too once it accepts yaml.
