### ISSUE TITLE
Storage volumes report differently than underlying filesystem

### ISSUE THREAD

**Issue by rkelleyrtp** [lxc/lxd#3271]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.04
 * The output of "lxc info" or if that fails:
`root@LXD-Testing-001:~# lxc info
config:
  core.https_address: 10.30.50.151:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.30.50.151:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
...
    -----END CERTIFICATE-----
  certificate_fingerprint: a44a822a925d13da354f25e8a9ddb9c0ff58654439a1a2e99ec52a44dbdcddba
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-19-generic
  server: lxd
  server_pid: 1479
  server_version: "2.12"
  storage: btrfs | dir
  storage_version: 4.9.1 | 1`

# Issue description

For some reason, the command "lxc storage list" is showing my volumes as btrfs when, in fact, one is a normal directory and the other is a btrfs volume.  In the example below, the "default" volume lives in /var/lib/lxd/storage-pools/default (a normal directory).

```
root@LXD-Testing-003:~# lxc storage list
+---------+--------+--------------------------------------+---------+
|  NAME   | DRIVER |                SOURCE                | USED BY |
+---------+--------+--------------------------------------+---------+
| btrfs   | btrfs  | fb5c03f9-7dc3-42d3-b5f7-c5f1a730b2fd | 0       |
+---------+--------+--------------------------------------+---------+
| default | btrfs  | 91cbb470-ca96-4d2d-8653-8fae12acea62 | 1       |
+---------+--------+--------------------------------------+---------+
```

```
root@LXD-Testing-003:/var/lib/lxd/storage-pools/default# df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        20G  2.9G   16G  16% /


root@LXD-Testing-003:/var/lib/lxd/storage-pools/default# mount |grep sda
/dev/sda1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```

# Steps to reproduce
 1. Start a new Ubuntu 17.04 LXD server (VM on ESXi)
 2. Attach a second HDD to be used for the storage pool
 3. Run "lxd init" and create a new storage volume; specify btrfs and select "no" to use new volume (force the creation of the btrfs filesystem - don't use loopback filesystem)

This issue has happened to a few servers, and I can't pin down exactly what I did to end up in this state.

**Comment by brauner** [comment]
Can you show me the output of:

   lxc storage show default

?

**Comment by rkelleyrtp** [comment]
root@LXD-Testing-003:/var/lib/lxd/storage-pools/default# lxc storage show default
config:
  source: 91cbb470-ca96-4d2d-8653-8fae12acea62
name: default
driver: btrfs
used_by:
- /1.0/profiles/default

**Comment by brauner** [comment]
Can you show me the output of:

    cat /proc/1/mounts

please?

**Comment by rkelleyrtp** [comment]
root@LXD-Testing-003:~# cat /proc/1/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=1999556k,nr_inodes=499889,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=404448k,mode=755 0 0
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14268 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /var/lib/lxd/shmounts tmpfs rw,relatime,size=100k,mode=711 0 0
tmpfs /var/lib/lxd/devlxd tmpfs rw,relatime,size=100k,mode=755 0 0
/dev/sdb /var/lib/lxd/storage-pools/btrfs btrfs rw,relatime,space_cache,user_subvol_rm_allowed,subvolid=5,subvol=/ 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=404444k,mode=700 0 0

**Comment by brauner** [comment]
And `ls -al /dev/disk/by-uuid/`?

**Comment by rkelleyrtp** [comment]
root@LXD-Testing-003:~# ls -la /dev/disk/by-uuid/
total 0
drwxr-xr-x 2 root root 100 May  1 11:05 .
drwxr-xr-x 7 root root 140 Apr 30 18:57 ..
lrwxrwxrwx 1 root root   9 Apr 30 18:57 2017-04-12-03-20-12-00 -> ../../sr0
lrwxrwxrwx 1 root root  10 Apr 30 18:57 b5e59845-4068-419d-b761-83e474bf65cf -> ../../sda1
lrwxrwxrwx 1 root root   9 May  1 11:05 fb5c03f9-7dc3-42d3-b5f7-c5f1a730b2fd -> ../../sdb

**Comment by brauner** [comment]
So just to clarify before I give you a sql-command to fix this: You want the storage pool named `default` to be a storage pool using the `DIR` driver, right?

**Comment by rkelleyrtp** [comment]
Yes, please.

Thanks!

**Comment by brauner** [comment]
Are there currently any containers on the `default` storage pool you care about? If not, please do

    lxc profile device unset default root pool
    lxc storage delete default
    lxc storage create default dir
    lxc profile device set default root pool default

**Comment by rkelleyrtp** [comment]
Thanks Christian!  That fixed the problem.

Let me see if I can reproduce this situation and post my findings.

-Ron

**Comment by brauner** [comment]
> # Steps to reproduce
> 1. Start a new Ubuntu 17.04 LXD server (VM on ESXi)
> 2. Attach a second HDD to be used for the storage pool
> 3. Run "lxd init" and create a new storage volume; specify btrfs and select "no" to use new volume (force the creation of the btrfs filesystem - don't use loopback filesystem)

Ok, now to the misdetection issue. I have a couple of questions :)

1. Why would you specify `btrfs`  as storage driver during `lxd init` but expect `LXD` to give you a `dir` pool? Or am I misunderstanding you?
2. Can you post the exact answers you gave during `lxd init` that caused you to end up in this situation? Ideally you could give reliable reproducer.

> This issue has happened to a few servers, and I can't pin down exactly what I did to end up in this state.

**Comment by rkelleyrtp** [comment]
> 	• Why would you specify btrfs as storage driver during lxd init but expect LXD to give you a dir pool? Or am I misunderstanding you?

I did not expect to use dir as a pool type.  I wanted to use a btrfs partition (/dev/sdb) to hold the data.

Let me come up with the exact steps and get back to you.  I don’t remember them 1:1 right now and don’t want to give you bad information.

**Comment by brauner** [comment]
@rkelleyrtp, thanks. Marking as incomplete for now.

**Comment by stgraber** [comment]
Any update on this?

Un-milestoning for now.
