### ISSUE TITLE
add support for new lxc.limit.[limit name] feature

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3272]
Since @Blub implemented the `lxc.limit.[limit name]` feature in https://github.com/lxc/lxc/pull/1276 we should decide whether we want to support this with a generic `LXD` `limit.[limit name]` configuration key. I'm very much in favor of this to allow setting per-container limits. Since my https://github.com/systemd/systemd/pull/5795 was merged we should be good on all fronts to support this.

**Comment by stgraber** [comment]
Yeah, I think I had something in the original plan for resource limits to cover this somewhat.
Probably something along the lines of:
 - limits.kernel.nofile
 - limits.kernel.fsize
 - ...

 - limits.prlimits.X

Would be more precise but it feels a bit redundant.

**Comment by stgraber** [comment]
We also need to find a way to detect whether LXC supports this or not. I do plan on releasing LXC 2.1 and LXCFS 2.1 around the July/August timeframe but we still need to work on older releases.

**Comment by brauner** [comment]
@stgraber, checking the version should be easy enough:
- if `LXC_DEVEL` is defined we'll assume this feature is there
- if `LXC_VERSION` is < `2.1` we know that this feature isn't available.

For the future I think exposing an API function that allows a caller to query liblxc whether it supports a given configuration item is really useful. I've sent a branch in https://github.com/lxc/lxc/pull/1535 which implements this. I'm tempted to call this a bugfix and backport it to all versions of https://github.com/lxc/lxc we still support. This shouldn't break API.

**Comment by brauner** [comment]
So here's a minimal "spec" for this.

- Implement a generic key `limit.[limit name]` instead of having multiple keys. Resource limit options that we do not want to support can be internally filtered during key validation.
-  I'd argue that `limit.[limit name]` keys should be settable on the `daemon`, `pool`, `profile`, and `container` level. The same `limit.[limit name]` keys on different levels override each other bottom-up (`container` beats `profile` beats `pool` beats `daemon`. For example, if `limit.[limit 1]` is  set in a `container`'s config it will override any `limit.[limit 1]` key set in `profiles` or in the `daemon` config. The reasoning is similar for `profiles` vs `daemon` wide settings. This might seem extreme but I think each has its use-cases. We also have some precedence on overrides in `profiles` vs `containers` and `storage pools` vs `storage volumes` (For example, `zfs.use_refquota` set on a `storage volume` beats `volume.zfs.use_refquota` set on a `storage pool`.).

**Comment by stgraber** [comment]
Hmm, what? prlimits are a container option. We already have the "limits" key space for this stuff, so just add:
 - limits.kernel.[limit name]

And let LXD do the usual profile inheritance as with everything else. So you can set it in a profile or override it in the container.

**Comment by stgraber** [comment]
I don't really see why those make any sense at the storage pool level and would get confusing when a container is attached to more than one of those. Same for the daemon, doesn't make sense to set those there when you can just set them in the default profile.
