### ISSUE TITLE
`lxc file pull` fails on Windows

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3275]
* LXC version: 2.13

```
>lxc file pull lx/etc/php/7.0/apache2/php.ini . --debug
error: chmod php.ini: not supported by windows
```

A workaround is to use:
```
lxc file pull lx/etc/php/7.0/apache2/php.ini - > php.ini
```

Interesting that the command may fail on Linux as well if target filesystem doesn't support setting permissions. https://github.com/lxc/lxd/blob/e0090661fa39692fccfbd6e2338e9ac95b69efec/lxc/file.go#L334

**Comment by brauner** [comment]
@techtonik, care to test the patch I just sent for this issue on Windows and report back whether this fixes it? :)

**Comment by techtonik** [comment]
I am on Linux right now. Maybe in a few hours.

**Comment by techtonik** [comment]
@brauner it works. Yesss! =)
