### ISSUE TITLE
Snapshot of one container make the host freeze/crash

### ISSUE THREAD

**Issue by antitoine** [lxc/lxd#3287]
# Required information

 * Distribution: `Ubuntu`
 * Distribution version: `16.10`
 * Kernel version: `4.8.0-49-generic`
 * LXC version: `2.0.7`
 * LXD version: `2.4.1`
 * Storage backend in use: `dir`

# Issue description

After two tentative, I can't make a snapshot of an Ubuntu 16.04 container (named `freeipa-client-1`). The `rsync` doesn't finish and after 15 minutes host computer completely freeze and crash.

# Steps to reproduce

I don't know if this will reproduce the freezing scenario, but I will describe what I have done (based on my history).

 1. Create a container: `lxc launch images:ubuntu/xenial free-ipa-client-1` then set `security.privileged` to `true`
 2. Make some stuff in the container, then stop it
 3. Make a first snapshot: `lxc snapshot free-ipa-client-1 init`
 4. Start container, make some stuff in the container, then stop it
 5. Make a second snapshot: `lxc snapshot free-ipa-client-1 post-install`
 6. Start container, make some stuff in the container, then stop it
 7. Make a third snapshot: `lxc snapshot free-ipa-client-1 post-configured`
 8. Start container, make some stuff in the container, then stop it
 9. Restore container: `lxc restore free-ipa-client-1 post-configured`
 10. Delete snapshot: `lxc delete free-ipa-client-1/post-configured`
 11. Restore container: `lxc restore free-ipa-client-1 post-install`
 12. Reboot host computer
 13. Start container, make some stuff in the container, then stop it
 14. Make a snapshot: `lxc snapshot free-ipa-client-1 post-client-1-config` => This nether ended

# Information to attach

 - [x] container log (`lxc info freeipa-client-1 --show-log`) [freeipa-client-1.log](https://github.com/lxc/lxd/files/978666/lxc-info-freeipa-client-1.txt)
 - [x] main daemon log (`/var/log/lxd/lxd.log`) [lxd.log](https://github.com/lxc/lxd/files/978675/lxd.txt)

**Comment by brauner** [comment]
@antitoine, can you please upgrade to a new LXD instance and try to reproduce?

**Comment by antitoine** [comment]
@brauner Hi, thanks for the response. I can't with package manager. I make an upgrade and reboot but I have the same version.

**Comment by brauner** [comment]
Hm, what do you mean?

**Comment by antitoine** [comment]
What can I do ?
I already make:
`sudo apt update && sudo apt upgrade && reboot`
And now : `lxc info`
```
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.0-51-generic
  server: lxd
  serverpid: 2179
  serverversion: 2.4.1
  storage: dir
  storageversion: ""
```
And try again to make the snapshot and same issue occur.

**Comment by brauner** [comment]
Please do `apt install -t yakkety-proposed lxd lxd-client`. Note that `16.10` will be EOL in about a month so you should consider upgrading to a newer version of `Ubuntu`.

**Comment by antitoine** [comment]
I solve the issue by clearing a log file.
The following file in the container takes more than 450GB: `/var/log/lastlog` (`/var/lib/lxd/containers/free-ipa-client-1/rootfs/var/log/lastlog`).
That's why the `rsync` never ended and make my computer crashing (no space left).
I don't know why this file was so big.

Thank for the help! (and yes, I will upgrade to Ubuntu 17.04 or downgrade to the 16.04 version for longer support).

**Comment by elupus** [comment]
Note this is a real issue. lastlog is a spare's file. It can be huge on any system (http://www.noah.org/wiki/Lastlog_is_gigantic) so lxd should really handle these types of file.
