### ISSUE TITLE
Minimal Backups, Backup one container more than another? Restore from just a snapshot on vanilla LXD?

### ISSUE THREAD

**Issue by mheroux2** [lxc/lxd#3289]
Is it possible to restore a container from just a snapshot with use of the files generated in /var/lib/lxd/snapshots/{{container}} only; consider the files inside /var/lib/lxd/ to be vanilla? If so how? 

I've read that for a complete backup you should capture all the files in /var/lib/lxd/ and do a SQL dump. But lets say we want to create a remote backup of some containers more frequently than others (without stopping the containers from running/freezing) and have those back ups work on a vanilla installation by themselves -- what's a good method for that? 

We'd rather our backup server not run LXD, and therefore migration/move commands are not applicable. I wrote the following script to take a snapshot of each container, rysync it to a backup server, and delete it. However, I've been unable to restore the snapshots of the container on the backup server on a vanilla LXD installation (no files exist inside /var/lib/lxd/container only files exists inside /var/lib/lxd/snapshots). I've been trying to use LXD import, copy, etc. which may not be designed for this functionality.

Should I just do a backup of /var/lib/lxc/ and then do a backup of particular snapshots more frequently?
```

#!/usr/bin/python
from __future__ import with_statement
import inspect, os, shutil, subprocess, datetime, socket, string, sys, json
__author__ = 'mheroux'

def main():
	# specify the remote directory where the backups are destine
	# these directories must actually exists
	backup_location = 'root@sub.example.com:/backup/' + socket.gethostname() + '/daily/00/'
	snapshot_location = '/var/lib/lxd/snapshots/'

	print 'Backup linux containers on "' + socket.gethostname() + '"'
	# get json list of containers and parse for processing
	containers = json.loads(shell_exec('lxc list -cn --format json'))
	# for each container
	for container in containers:
		print ' Process "' + container['name'] + '"'

		# take a snapshot of the container
		print ' - Take snapshot',
		try:
			shell_exec('lxc snapshot ' + container['name'] + ' auto-backup')
			print '[SUCCESS]'
		except:
			print '[FAILURE]'
			pass
 
		# move the snapshot to backup location
		print ' - Copy to backup location',
		try:
			rsync = 'rsync --archive --stats --delete --progress --rsh="ssh -o StrictHostKeyChecking=no" '
			rsync += snapshot_location + container['name'] + '/auto-backup/ ' + backup_location + container['name']		
			shell_exec(rsync)
			print '[SUCCESS]'
		except Exception, e:
			print '[FAILURE]'
			print ' -  DETAILS:  '
			print '     COMMAND.' + rsync
			print '     ' + str(e)		
			pass

		# remove snapshot the container
		print ' - Delete local snapshot',
		try:
			shell_exec('lxc delete ' + container['name'] + '/auto-backup')
			print '[SUCCESS]'
		except:
			print '[FAILURE]'
			pass
		
# run shell command function as subprocess 
def shell_exec(command):
	proc = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	output, errors = proc.communicate()
	if errors:
		raise Exception("ERROR: " + errors)
	return output

# main 
if __name__ == "__main__":
  main()

```

**Comment by brauner** [comment]
Before I can give you advice on the method you're using right now I'd need to know that version of `LXD` you're using. Depending on whether this is a storage-api LXD instance or not I'd have different advice. :)

**Comment by mheroux2** [comment]
com@seuropa:~$ lxd --version
2.13

**Comment by brauner** [comment]
Your current method can be used but there are some caveats. First of all, storage backends that use the `lvm` or `zfs` driver will not mount the storage volume they create for a snapshot. So if you do

    lxc snapshot <lvm-based-container>

or 

    lxc snapshot <zfs-based-container>

a snapshot will be created but the storage volume will not be mounted at

    /var/lib/lxd/storage-pools/<pool-name>/snapshots/<container-name>/<snapshot-name>

That means the symlink in 

    /var/lib/lxd/snapshots/<container-name>

will point to

    /var/lib/lxd/storage-pools/<pool-name>/snapshots/<container-name>

but none of the contents will be available.

So rsyncing directly in the way you described will only work with the `btrfs` driver and the `dir` driver. (Caveat, the `btrfs` driver would require the storage pool to be mounted. But that should always be the case when the `LXD` daemon is running and no one has manually unmounted it.) For the other two drivers I mentioned above (`lvm` and `zfs`) this becomes more involved. I'm pretty sure `lvm` will simply let you mount the snapshot you want. What you'd need to do is to look under `/dev/<vgname>/snapshots_<snapshot-name>` and mount it, then you can rsync the contents where you want to. For `zfs` this is even more annoying since `zfs` will not let you mount snapshots. So what you could do, is create a new container from the snapshot by using `lxc copy <zfs-container>/<snapshot> <temporary-container>`, mount the storage volume for the new container and then rsync.

Now, assume that all works and you want to recreate the container on another `LXD` instance. If you really only care about the files for the container you backed up you can create an empty container on the new `LXD` instance and simply rsync the contents of your backed up container into its storage volume. I've done this a couple of times before.

So you'd need:
```
curl -s --unix-socket /var/lib/lxd/unix.socket -X POST -d '{"name": "bla", "source": {"type": "none"}}' a/1.0/containers | jq .
```
and get the `<operation-id>` from the return output you see. And wait for it to succeed.

```
curl -s --unix-socket /var/lib/lxd/unix.socket a/1.0/operations/<operation-id> | jq .

```

If necessary mount the storage volume (for `lvm` and `zfs`) and then rsync into:

    /var/lib/lxd/storage-pools/<pool-name>/containers/<container-name>

**Comment by brauner** [comment]
Leaving the container running and performing the backup via rsync manually is not really a good idea since the contents of the container might be inconsistent. The best way would actually be live migration which we support to a limited extent at least.

**Comment by brauner** [comment]
You could also publish the container as an image and import that image into the other LXD instance and start a container from it. I've done that as well. So:

    lxc publish -f <container> --alias <container> # (this will stop the container and restart it)
    lxc image export <container> # will output tarball named with a hashed name
   
then rsync the image tarball(s) to the remote location.

To restore a container from a tarball do:

    lxc image import <tarball> # will import and output a hash for the image
    lxc image import <hash>

**Comment by mheroux2** [comment]
Hi Brauner,

Thank you for the timely response. I am using a DIR pool.

For the publish the container option, that will stop the container and restart it and therefore should not be used regularly (e.g. every 3 hours). I will be considering this for limited nightly backups and therefore appreciate you mentioning this possibility.

As for the method of restoring a rsync of a dir snapshot, i.e. "If you really only care about the files for the container you backed up you can create an empty container on the new LXD instance and simply rsync the contents of your backed up container into its storage volume." I take it some of the container's configurations would be lost? It seems like there is stuff stored outside of a snapshot that keeps it from being a standalone snapshot? And this is not a good solution?

Rsyncing a tarball file, would likely take more resources than rsyncing the whole /var/lib/lxc directory (minus images), because the transfer would not take advantage of preexisting files on the backup server.

I'm probably missing something, but there doesn't seem to be an ideal solution. Snapshots do not appear to be standalone files that can easily be restored, even using dir storage pools? Meaning I should probably do a /var/lib/lxd backup every 24 and a snapshot backup more frequently if needed?

**Comment by imad-abdou** [comment]
hello
any one tried one of this tools with lxd zfs ?
https://github.com/jimsalterjrs/sanoid
https://github.com/oetiker/znapzend

**Comment by brauner** [comment]
Sorry for the delay, the issue was farther down the stack. :) Yes, the latter option for now sounds alright. And no, snapshots can be somewhat seen as backups to be used by `LXD` daemons. If you take the daemon out of the picture restoring from a backup becomes a little problematic.

**Comment by mheroux2** [comment]
Thanks again, I'll dev that.

It would be nifty if snapshots and containers were standalone in the future from ;-). Seems like you could do an SQLite3 dump of the features, and copy necessary portions when a snapshot is generated.

Also, setting static IP4 for containers could be a lot easier. ;-) 

Keep up the great work and thanks, folks!
