### ISSUE TITLE
file push: allow -r for pushing files

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3291]
lxc 2.13

# Issue description
```
>lxc file push 01install.sh node:lxdtox/root/01install.sh

>lxc file push -r 01install.sh node:lxdtox/root/01install.sh
error: open: Not a directory
```

For a command line tool it is very inconvenient to implement branching logic (if dir then `-r` else empty).

**Comment by brauner** [comment]
I think that it is actually smart to print out this warning to ensure that people do not accidentally push a file when they mean to push a directory.

**Comment by techtonik** [comment]
I don't mind against a warning, but this is an error.

**Comment by techtonik** [comment]
`cp -r` doesn't fail when copying file, so I expect `lxc push` to work the same way.

**Comment by brauner** [comment]
I'd rather require the user to be explicit about what {she,he} wants then to just execute this but I'm also not opposed to changing it given that the unix standard tools don't.

**Comment by brauner** [comment]
Yeah, I know that `{mv,cp}` behave that way.

**Comment by brauner** [comment]
@techtonik, are you working on this?

**Comment by techtonik** [comment]
@brauner no. I am not sure it won't break anything.

**Comment by stgraber** [comment]
@albertodonato tells me that this behaves as expected on 2.15.
