### ISSUE TITLE
Format of fingerprint presented by lxc remote add

### ISSUE THREAD

**Issue by Shinzu** [lxc/lxd#3293]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-75
   * LXC version: 2.0.7
   * LXD version: 2.0.9
   * Storage backend in use: zfs

# Issue description

when i do a lxc remote add i get presented following fingerprint:

```62336534346662333130343963333866653538623163616566383437326634663166623262396633303361326137363561393761336337323133663831383433```

what format is this fingerprint?

**Comment by stgraber** [comment]
It's supposed to be the sha256 of the TLS certificate, though it looks like it may be sending out sha512 now instead... We'll need to look into it to make everything consistent again.

**Comment by stgraber** [comment]
Oh wow, found the issue, kinda amazed that nobody noticed before to be honest :)
So what you're getting is the hex representation of the sha256 string rather than the sha256 string.

Sending a fix.

**Comment by Shinzu** [comment]
ok thx, for now i confirm it with

``` 
> echo 62336534346662333130343963333866653538623163616566383437326634663166623262396633303361326137363561393761336337323133663831383433 | xxd -r -p
b3e44fb31049c38fe58b1caef8472f4f1fb2b9f303a2a765a97a3c7213f81843%
```
