### ISSUE TITLE
Why docker profile?

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3299]
[README.md](https://github.com/lxc/lxd#how-can-i-run-docker-inside-a-lxd-container) says to assign `docker` profile to container, but doesn't explain why.

**Comment by brauner** [comment]
And it doesn't need to anymore. If you want, you can remove this section and mention that Docker upstream now runs fine inside a LXD container and that only setting `lxc config set <container> security.nesting true` is required.

**Comment by techtonik** [comment]
That's good to know. I've almost finished messing with `docker` profile. :D

**Comment by techtonik** [comment]
@brauner I added instructions in PR above, but I can't explain what is that and how it works.

**Comment by brauner** [comment]
@techtonik newer kernels come with AppArmor namespacing support. This means programs can load AppArmor profiles inside of a container. Setting `security.nesting` to `true` will allow them to do just that. For example, `Docker` likely wants to load a custom `AppArmor` profile for its containers and/or the daemon.

**Comment by techtonik** [comment]
I don't know what `AppArmor` is and why Docker requires it,

**Comment by brauner** [comment]
@techtonik, without going into to much detail (if you're interested there are various good articles out there in the wild) AppArmor is an additional LSM (Linux Security Module) designed to further harden the kernel against possible attacks. LXD and Docker/Moby both make use of this.
