### ISSUE TITLE
Help and docs for lxd-images script

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#330]
I am trying to figure out where lxd-images imports stuff from. `lxc image import` grabs this from .tar.gz The problem is that this script is not documented and command line output is poor. It would be nice to have some docs like https://github.com/lxc/lxd/blob/master/specs/command-line-user-experience.md for that and some sane command line help. It is not necessary to construct it using argparse.

And it would be nice to see a definition - what this "image" is. For me the image could be dd image, iso, memory image, etc.

**Comment by stgraber** [comment]
lxd-images is basically a temporary helper tool so I don't intend to cover it in the command line specification.

However we should be adding a more comprehensive help as the one generated by argparse can be a bit confusing.

**Comment by techtonik** [comment]
It looks like this functionality belongs to `lxc images import`.

**Comment by stgraber** [comment]
It is indeed where we would move that feature if we were to support it. lxd-images is a temporary thing so that's why we've made it a separate, optional tool.

**Comment by techtonik** [comment]
Why downloading images could be out of scope for user level tool?

**Comment by stgraber** [comment]
Transferring images between LXD hosts and spawning containers based from a remote image is in scope and is covered by the lxc tool spec ("lxc image copy remote:image local-image" and "lxc launch remote:image container name").

What's not covered is supporting any number of different source image formats on remote servers, each likely to change completely outside of our control and requiring an ever growing number of dependencies to support all the image protocols and formats.

For that, we intend for the various distributions to either provide a LXD-compatible image server that you can directly use using the lxc command or provide their own script to convert and feed a compatible image into LXD.

**Comment by techtonik** [comment]
Sounds like LXD needs a plugin system and API for that. Installing plugin package is way easier that messing with custom scripts.

**Comment by BarthV** [comment]
Image provider plugin system would be very powerful.
