### ISSUE TITLE
Change `lxc init` behavior

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#331]
https://github.com/lxc/lxd/blob/master/specs/command-line-user-experience.md#init
From:
```
<image> [container name] [--ephemeral|-e] [--profile|-p <profile>...]
```
To:
```
[container name] [--image|-i <image>] [--ephemeral|-e] [--profile|-p <profile>...]
```

Make the default behaviour of `lxc init` as:
```
$ lxd-images import lxc {{dist}} {{release}} {{arch}} --alias ubuntu
$ lxc init {{dist}} --image {{dist}}
```
This will make it the easiest way to get started.

**Comment by stgraber** [comment]
I'm failing to see how that's making it any easier and it does make it inconsistent with every single other command...

**Comment by techtonik** [comment]
Which commands are inconsistent? These all need container as their first argument:

    lxc delete   (no command line hint though)
    lxc exec
    lxc info
    lxc restart
    lxc start
    lxc stop

**Comment by techtonik** [comment]
Usability stuff is that new user will just `install lxd` and run `lxc init` and will get working container that is a disposable environment specific for his system.

**Comment by stgraber** [comment]
No,

"lxc init" is an advanced option which is hidden by default.

The default user experience is you install lxd and you run "lxc launch <image> [name]".

**Comment by techtonik** [comment]
"lxc launch" is also hidden by default, FWIW.

**Comment by stgraber** [comment]
Oops, that's a bug. Sent a branch to fix that.
