### ISSUE TITLE
copy container between ZFS pools?

### ISSUE THREAD

**Issue by niksfirefly** [lxc/lxd#3312]
Is there a simple way to copy container between ZFS storage pools on the same host ?

regards

**Comment by brauner** [comment]
Not yet, can you open an issue for this and ping me.

**Comment by niksfirefly** [comment]
OK so what is the most elegant way to copy/move container.
1.Create image and launch new container?
2.ZFS send dataset to another and manually modify lxd DB?
other option?

**Comment by brauner** [comment]
Without manually touching the db, I'd go for:

```
lxc publish -f <container> --alias <container> # (this will stop the container and restart it)
lxc launch local:<hash> <container-name> -s <storage-pool-of-choosing>
```

**Comment by brauner** [comment]
You can obviously use a short form for `<hash>` in the second command.

**Comment by brauner** [comment]
@niksfirefly, does that work for you for now?

**Comment by niksfirefly** [comment]
Yes of course it is working :)
We must only remember to launch new container with profiles for old one.

regards
