### ISSUE TITLE
storage: copy containers between storage pools

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3315]

**Comment by LordAro** [comment]
This seems like an odd feature to be missing, given you can quite easily copy between different storage pools on different hosts. Don't suppose there's been any progress?

**Comment by brauner** [comment]
So one other thing that came to my attention when starting to look into this is that we likely made a design mistake when we added the storage api. Right now, when we move containers between LXD instances we try to find a valid pool in the following order:
- look at local devices of container. if we find a root disk device with a pool property check if that pool exists. if it doesn't unset the pool property and move on to looking at the profiles. repeat the same logic. if we didn't find a pool use the default pool iff only a single pool exists on this lxd instance.
This logic gets us into trouble now. I wanted to enable copying/moving containers and allowing users to target a specific storage pool but if users want to target a specific storage pool they likely want to fail if that pool doesn't exist on the target LXD. But right now we can't reasonably fail without regressing use-cases.

**Comment by brauner** [comment]
I'm likely going to split this work into two parts:
1. moving containers between storage pools locally (larger task)
2. moving containers between storage pools remotely (smaller task once design is settled)

I'm scheduling 1. for 3.2.

**Comment by brauner** [comment]
#### Moving containers between storage pools on the same LXD instance
- `lxc copy` and `lxc move` subcommands gain the flag `-s/--storage` similar to `lxc launch` and `lxc init`.
- the `pool` specified via `-s/--storage` gets added to the target container's local devices. Any old pool property in the container's root disk device is overriden

The rest should be internal plumbing on the server side.
