### ISSUE TITLE
New storage backend: shared filesystem

### ISSUE THREAD

**Issue by djgroves** [lxc/lxd#3316]
This is a feature request rather than an issue. 

The idea would be to have a storage backend for a shared filesystem: glusterfs or nfs spring to mind, i'm sure there are others. 

This would enable very fast migration between hosts (no copying, its already there!) and allow a degree of recovery in the event of a host failure (subject to network configuration) as well as enable central backups.

**Comment by brauner** [comment]
We already have an issue to track support for ceph. `nfs` will be almost impossible since the kernel will severely restrict access to it by unprivileged containers and so it's almost unusable for now. https://github.com/lxc/lxd/issues/1258
