### ISSUE TITLE
`lxc image alias` doesn't work in 0.2

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#332]
```
$ lxc image alias create ubuntu 495
$ lxc image list
495f37156ca3f1be30180e4f4b9437a3abb9217f7c8fe205dbf6fe5c707c970c
$ lxc image alias list
$
```
I expected it to add image that starts with 495 or report an error. It is very strange that no feedback is given and alias is not created. If I specify full hash, the alias is created ok.

**Comment by stgraber** [comment]
Indeed, the lack of error is a bug.

We do intend to support matching only part of a hash when referencing an image, but I don't believe that's been done yet, so you'll have to pass the full hash for now.

**Comment by stgraber** [comment]
@hallyn Can you look at why we're not showing an error in this case?
