### ISSUE TITLE
LXD - Failing to copy/move container from v2.08 to v2.12 when using BTRFS

### ISSUE THREAD

**Issue by rkelleyrtp** [lxc/lxd#3323]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04

# Issue description
I have two LXD servers: server(a) is running 2.08 and server(b) is running 2.12.  Both servers have BTRFS filesystems.  I am trying to copy/migrate a container from server(a) to server(b) but can't successfully migrate the container from 2.08 to 2.12:

# Steps to reproduce
Stop the source container and copy it to the target server
`root@WP-Container-Mgmt:~# lxc stop WP-Container-004:wordpress-testsite-com1`  
`root@WP-Container-Mgmt:~# lxc copy WP-Container-004:wordpress-testsite-com1 WP-Container-005:`
(works OK)

On the receiving side, I see a similar directory with a timestamp:
```
root@HJ-WP-Container-005: ls -la /var/lib/lxd/storage-pools/default/containers 
drwxr-xr-x 1 root   root   132 May 15 22:46 .
drwxr-xr-x 1 root   root    62 Apr 28 09:34 ..
drwx------ 1 root   root    10 May 15 22:46 wordpress-testsite-com1845325915
```

…and, inside that site directory I see this:
```
root@HJ-WP-Container-005: ls -la /var/lib/lxd/storage-pools/default/containers/wordpress-testsite-com1845325915/
total 0
drwx------  1 root   root    10 May 15 22:46 .
drwxr-xr-x  1 root   root   132 May 15 22:46 ..
drwxr-xr-x+ 1 100000 100000  12 May 15 22:49 .root

```

Running an “lxc list” on the target server, I see this:
```
root@HJ-WP-Container-005:/var/lib/lxd/storage-pools/default/containers# lxc list
+--------------------------+---------+--------------------------------+------+------------+-----------+
|           NAME           |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
+--------------------------+---------+--------------------------------+------+------------+-----------+
| wordpress-testsite-com1  | STOPPED |                                |      | PERSISTENT | 0         |
+--------------------------+---------+--------------------------------+------+------------+-----------+

```

Trying to start the container on the receiving side:
```
root@HJ-WP-Container-005:/var/lib/lxd/storage-pools/default/containers# lxc start wordpress-testsite-com
error: saving config file for the container failed
Try `lxc info --show-log wordpress-testsite-com` for more info
root@HJ-WP-Container-005:/var/lib/lxd/storage-pools/default/containers# lxc info --show-log wordpress-testsite-com
Name: wordpress-testsite-com
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/05/16 03:30 UTC
Status: Stopped
Type: persistent
Profiles: WP__Default

Log:

```

At this point, LXD is in an inconsistent state.  BTRFS now has a sub volume for this container (under container_name/.root), but LXC won’t allow me to remove it until I do some *hackery*
------------------------------------------------------------
```
root@HJ-WP-Container-005:/var/lib/lxd/storage-pools/default/containers# lxc delete wordpress-testsite-com1
error: Failed to run: btrfs subvolume delete /var/lib/lxd/storage-pools/default/containers/wordpress-testsite-com1: ERROR: cannot access subvolume /var/lib/lxd/storage-pools/default/containers/wordpress-testsite-com1: No such file or directory

btrfs sub list /var/lib/lxd/storage-pools/default/containers
ID 257 gen 1238 top level 5 path containers
ID 258 gen 1176 top level 5 path snapshots
ID 259 gen 229 top level 5 path images
ID 260 gen 12 top level 5 path custom
ID 1087 gen 1245 top level 257 path wordpress-testsite-com1845325915/.root


root@HJ-WP-Container-005:/var/lib/lxd/storage-pools/default/containers# btrfs sub del wordpress-testsite-com1845325915/.root/
Delete subvolume (no-commit): /var/lib/lxd/storage-pools/default/containers/wordpress-testsite-com1845325915/.root

root@HJ-WP-Container-005:/var/lib/lxd/storage-pools/default/containers# rmdir wordpress-testsite-com1845325915/

root@HJ-WP-Container-005:/var/lib/lxd/storage-pools/default/containers# btrfs sub create wordpress-testsite-com1
Create subvolume './wordpress-testsite-com1

root@HJ-WP-Container-005:/var/lib/lxd/storage-pools/default/containers# lxc delete wordpress-testsite-com1
```

Additional information
---------------------------
I have run the copy/clone process a few times and have seen two different outcomes:
(1) "error: Migration failed on target host: Container 'wordpress-testsite-com' already exists”
In this test case, the site actually copied to the target server but failed to start (the "already exists" message is wrong).  You can ignore the message and try to start the container on the target server.

(2) "error: saving config file for the container failed”  This means the copy worked but the BTRFS snapshot did not get properly renamed on the target system (lxd copy uses btrfs snapshots to move sites between servers).  To fix this issue: 
 —> Go to your target server terminal
 —> Navigate to the directory /var/lib/lxd/storage-pools/default/containers, and do a directory list (“ls”).  
 —> You should see a directory with the container name and a snapshot time/date.  Something like wordpress-"testsite-com1845325915”.  
 —> Inside that directory is a “.root” directory used to hold the btrfs snapshot.  
 —> Run the command, “btrfs sub create /var/lib/lxd/storage-pools/default/containers/testsite-com1845325915/.root /var/lib/lxd/storage-pools/default/containers/testsite-com”.  
 —> Try to start the site (it should come up properly now that the btrfs snapshot is pointing to the right location).  
 —> If this works, you can remove the other snapshot like this: btrfs sub delete /var/lib/lxd/storage-pools/default/containers/testsite-com1845325915/.root.

**Comment by brauner** [comment]
Is it possible for you to try and reproduce this with `2.13`?

**Comment by brauner** [comment]
Ok, I managed to reproduce on `2.13` as well.

**Comment by rkelleyrtp** [comment]
Yes, sorry for the delay.  This problem exists in both 2.12 and 2.13.

**Comment by brauner** [comment]
@rkelleyrtp, thanks for reporting the issue. The patch I sent should fix this issue. If you want you can grab it and test whether it fixes it.

**Comment by rkelleyrtp** [comment]
Thanks Christian.  I am not familiar on how to apply the patch.  Can you please give me a quick primer?

**Comment by brauner** [comment]
@rkelleyrtp, if it's too much work for you don't worry about it.
Basically, all you should usually need is `go` and `git` installed and then you can do:

```
go get github.com/lxc/lxd
cd ${GOPATH}/src/github.com/lxc/lxd
wget https://patch-diff.githubusercontent.com/raw/lxc/lxd/pull/3325.patch
git apply 3325.patch
make

sudo systemctl stop lxd.service lxd.socket
sudo ${GOPATH}/bin/lxd --debug --group lxd
```

But as I said don't worry about it if it is too much trouble. I tested locally with and without snapshots and it seems to work fine.

**Comment by rkelleyrtp** [comment]
Thanks again.  Will this show up in 2.14 or something else?

**Comment by brauner** [comment]
@rkelleyrtp, this will be in `2.14`.

**Comment by rkelleyrtp** [comment]
I thought someone mentioned this in a previous topic, but I can’t find the reference.

Is it possible to enable LXD to make incremental copies of a container?  Currently, if you run “lxc copy <container_a> <container_b>”, the first iteration works properly.  But, subsequent commands will fail since the container already exists.  I don’t want hot migration, I just want incremental copies of one container to another.

It would be great if we had an incremental copy whereby the destination gets updated on-the-fly.  This would certainly cut down the time to move containers between hosts.

Thanks.

**Comment by brauner** [comment]
@rkelleyrtp, that's a totally separate issue but ok. :)
So, I guess what you would want is to calculate and then transmit an fs-delta between two containers? Meaning:

    lxc copy a remote:b

and when you do

    lxc copy a remote:b

you only want the delta between the first transmission and the second transmission?

**Comment by rkelleyrtp** [comment]
Correct.  Maybe add an “incremental” option so we can just update the remote site w/out shutting down the primary or powering on the remote.

BTW - this request is not part of the bug ticket.  I just happen to send this email around the same time I filed the bug :-)
