### ISSUE TITLE
Local DNS Name resolving for LXC containers on the host

### ISSUE THREAD

**Issue by despens** [lxc/lxd#3327]
# Required information

<details>
<summary>output of <code>lxc info</code> </summary>

```
$ lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
***
    -----END CERTIFICATE-----
  certificate_fingerprint: e79b6012bfd6356607d9a38b0a4f0d3310a691c3e2f9e26e9b37fd33e1be7013
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.8.0-52-generic
  server: lxd
  server_pid: 2996
  server_version: "2.13"
  storage: zfs
  storage_version: 0.6.5.8-0ubuntu4.2
```

</details>

# Issue description

On *Ubuntu 16.04 server edition*, after launching a container, it can only be referred to by its IP address. Enabling the `.lxc` domain in dnsmasq doesn't seem to help, and tutorials available only seem to work for Ubuntu 14.04. 

Not being able to use DNS names on the host is a major inconvenience.

From blog posts I gather LXD 2.9 solves this problem, but it seems unclear how to install via PPA.

# Steps to reproduce

Following instructions https://gauvain.pocentek.net/name-resolution-lxc-containers.html

1. installed `dnsmasq`
2. uncommented `LXC_DOMAIN="lxc"` in `/etc/default/lxc-net`
3. added `server=/lxc/10.0.3.1` to `/etc/dnsmasq.d/lxc`
4. checked that `/etc/resolv.conf` contains DNS server 10.0.3.1

Querying `dig mycontainer.lxc` leads no results.
Querying `dig @10.0.3.1 mycontainer.lxc` leads no results.
Querying `dig @10.0.3.1 google.com` produces results.

<details>
<summary>result for <code>sudo lsof -i :53</code></summary>

```
$ sudo lsof -i :53
COMMAND  PID        USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
dnsmasq 3199 lxc-dnsmasq    6u  IPv4  19437      0t0  UDP 10.0.3.1:domain 
dnsmasq 3199 lxc-dnsmasq    7u  IPv4  19438      0t0  TCP 10.0.3.1:domain (LISTEN)
dnsmasq 3280         lxd    6u  IPv4  21542      0t0  UDP 10.111.40.1:domain 
dnsmasq 3280         lxd    7u  IPv4  21543      0t0  TCP 10.111.40.1:domain (LISTEN)
dnsmasq 3280         lxd   12u  IPv6  20612      0t0  UDP [fe80::dc47:e5ff:fe49:aac8]:domain 
dnsmasq 3280         lxd   13u  IPv6  20613      0t0  TCP [fe80::dc47:e5ff:fe49:aac8]:domain (LISTEN)
dnsmasq 4741     dnsmasq    4u  IPv4  30236      0t0  UDP lxd-host.c.server-environments.internal:domain 
dnsmasq 4741     dnsmasq    5u  IPv4  30237      0t0  TCP lxd-host.c.server-environments.internal:domain (LISTEN)
dnsmasq 4741     dnsmasq    6u  IPv4  30238      0t0  UDP localhost:domain 
dnsmasq 4741     dnsmasq    7u  IPv4  30239      0t0  TCP localhost:domain (LISTEN)
dnsmasq 4741     dnsmasq    8u  IPv6  30240      0t0  UDP [fe80::fc0d:e8ff:feeb:15ea]:domain 
dnsmasq 4741     dnsmasq    9u  IPv6  30241      0t0  TCP [fe80::fc0d:e8ff:feeb:15ea]:domain (LISTEN)
dnsmasq 4741     dnsmasq   10u  IPv6  30242      0t0  UDP [fe80::4001:aff:fe8e:2]:domain 
dnsmasq 4741     dnsmasq   11u  IPv6  30243      0t0  TCP [fe80::4001:aff:fe8e:2]:domain (LISTEN)
dnsmasq 4741     dnsmasq   12u  IPv6  30244      0t0  UDP ip6-localhost:domain 
dnsmasq 4741     dnsmasq   13u  IPv6  30245      0t0  TCP ip6-localhost:domain (LISTEN)
```

</details>

**Comment by stgraber** [comment]
If you're using LXD, the domain is ".lxd", not ".lxc".

**Comment by stgraber** [comment]
LXD 2.9 and higher makes thing a bit more configurable by letting you define multiple bridges, each running their own dnsmasq instance with configurable DNS domain and resolving behavior, but we still don't automatically register with the OS as it's not really doable in a reliable way (nor necessarily desirable for most users).

So I don't think that upgrading your LXD to 2.13 (current version in xenial-backports) would necessarily help you there.

**Comment by stgraber** [comment]
Closing as the core of the issue above was ".lxc" vs ".lxd".

**Comment by despens** [comment]
Is there a place where I could ask about some details about LXC/LXD? For example, the ppa `ubuntu-lxc/lxd-git-master` does contain LXD and LXD version 2.14, and lots of documentation I found leaves out the version information.

Any recommendation—IRC channel, forum, …—would be greatly appreciated!

**Comment by brauner** [comment]
@despens sure. I think for any non-technical issues the best place nowadays is https://discuss.linuxcontainers.org/ where we maintain a support forum. :)

**Comment by kattunga** [comment]
I have exactly the same problem using Ubuntu 16.04 Server and LXD 2.14.

I'm using a custom lxd domain called lxd-02

Bridge configuration:
```
description: ""
config:
  dns.domain: lxd-20
  ipv4.address: 10.123.20.1/24
  ipv4.nat: "true"
  ipv6.address: none
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/ldap
- /1.0/containers/mongodb
managed: true
```
I instaled dnsmasq on host
added `/etc/dnsmasq.d/lxd-02`
```
server=/lxd-02/10.123.20.1
```

lxc list:
```
+-----------------+---------+----------------------+------+------------+-----------+
|      NAME       |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+-----------------+---------+----------------------+------+------------+-----------+
| ldap            | RUNNING | 10.123.20.253 (eth0) |      | PERSISTENT | 0         |
+-----------------+---------+----------------------+------+------------+-----------+
| mongodb         | RUNNING | 10.123.20.50 (eth0)  |      | PERSISTENT | 0         |
+-----------------+---------+----------------------+------+------------+-----------+
```

/var/lib/lxd/networks/lxdbr0/dnsmasq.hosts
```
00:16:3e:ae:49:0a,id:*,10.123.20.253,ldap
00:16:3e:59:16:96,id:*,10.123.20.50,mongodb
```

/var/lib/lxd/networks/lxdbr0/dnsmasq.leases
```
1498573932 00:16:3e:ae:49:0a 10.123.20.253 ldap *
1498573927 00:16:3e:59:16:96 10.123.20.50 mongodb *
```

Querying `dig ldap.lxd-02` leads no results.
Querying `dig @10.123.20.1 ldap.lxd-02` leads no results.
Querying `dig @10.123.20.1 google.com` ok.

Am I forgetting something?
