### ISSUE TITLE
Detecting when container has completed booting

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#3330]
Hi!

I'd like to know if there is a way to detect when an LXD container has finished booting. My use case is quite simple: I'd like to provision a container and then add some users and databases to MariaDB in a shell script. 

However, I have experienced that after calling lxc start I cannot immediately start interacting with the MySQL daemon as it hasn't started yet.

I've "solved" it for now by putting a sleep command in my shell script, but this is ... Well sub-optimal.

Any hints on how I can wait the appropriate amount of time for my userspace to be ready in the container?

Thanks! And I apologize beforehand if this is a duplicate question.

**Comment by brauner** [comment]
I'm not sure about a good way to detect this. It is kind of similar to call `ssh {some-host-ip}` after you have rebooted it.

**Comment by Kramerican** [comment]
Hi Brauner,

Thank you for your response. Well, there has to be some method out there. I found this using my awesome Google-fu:

[https://superuser.com/questions/918860/how-to-detect-an-lxc-container-system-is-ready](https://superuser.com/questions/918860/how-to-detect-an-lxc-container-system-is-ready)

I have yet to explore the suggestion found here though ...

**Comment by brauner** [comment]
So if that works for you what about using the same approach but instead of using `lxc-attach` as you do for `LXC` you'd use `lxc exec`?

**Comment by Kramerican** [comment]
I was just referencing that post by someone else, and I have not tried this approach yet. I'll dig into it this weekend and report back here if I find a good way of doing this with LXD :)

**Comment by Kramerican** [comment]
Hello

The solution seems to be in that you should decide what it is specifically you are waiting for to be ready. Googling "wait for x ready docker" seems to yield plenty of bash commands and scripts which can be used to wait for various services to be ready in a container, network, mysql, whatever. Namely:

[https://github.com/vishnubob/wait-for-it](https://github.com/vishnubob/wait-for-it)

[https://askubuntu.com/questions/697798/shell-script-how-to-run-script-after-mysql-is-ready](https://askubuntu.com/questions/697798/shell-script-how-to-run-script-after-mysql-is-ready)

[https://gist.github.com/ricog/9e745cd79824bc360df14bdf95bb1f27](https://gist.github.com/ricog/9e745cd79824bc360df14bdf95bb1f27)

And many other approaches. I ended up with doing a one-liner:

lxc exec $name -- /bin/bash -c "while ! (mysqladmin ping); do sleep 1; done"

I guess this can be closed now, as it wasn't really an "issue" to begin with :) I hope this info helps other LXD afficionados!

**Comment by brauner** [comment]
Cool, good that you found a solution.
