### ISSUE TITLE
Deleting LXD containers on zfs sometimes messes up ZFS mount points

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#3331]
Hello,

I'd like to call this issue to your attention, as it is unclear to me (and the others in the posts linked to here) whether this is a ZFS or LXD issue. I run into this regularly. It always happens after having performed a lxc delete on the host.

Vanilla Xenial, latest stable LXD (2.13 I believe)

Read more here:

[https://askubuntu.com/questions/774097/lxd-managed-containers-on-zfs-vanish-after-deleting-a-different-one](https://askubuntu.com/questions/774097/lxd-managed-containers-on-zfs-vanish-after-deleting-a-different-one)

Thank you for your time and attention :)

**Comment by brauner** [comment]
The post you linked seems to show a LXD version prior to 2.9. Are you running into the same problem with 2.13?

**Comment by brauner** [comment]
It sound like a problem we've already reported to `zfs` upstream here https://github.com/zfsonlinux/zfs/issues/5796 .

**Comment by Kramerican** [comment]
Hello brauner,

I have recently upgraded from 2.9 to 2.13, so I am actually not 100% sure this issue still persists. I have a cron'ed script which warns me when mount points have gone funky, but I can't remember if I had fixed the  bad mounts before upgrading to 2.13 (I upgraded like, 2 days ago). 

Anyway, I will fix them now and then keep an eye on things and report back here if I decidedly see this happening in 2.13 as well.

Thank you for your attention. Much respect :+1:

**Comment by brauner** [comment]
Np. :) So I suggest, we close this for now and you ping me in case you see this issue again!

**Comment by Kramerican** [comment]
Hello Brauner

There is still some funkyness here on LXD 2.13 - It doesn't to seem to be as "bad" as before, as I do not have to remove the zfs mount point before remounting. Anyway, symptoms:

1) A stopped container (seemingly randomly) no longer has any data in /var/lib/lxd/containers/containername/
-  I have to detect this, as I use rsync to backup my containers, and it rsyncs that dir

2) If I start the container, the rootfs shows up, vanishes if I stop the container

3) Running zfs mount -a while the container is stopped runs without problems and rootfs shows up

So not as bad as it was before, as it's easily fixed by running zfs mount -a - I have incorporated this command in by backup routine, but it would be nice to know what's going on.

**Comment by brauner** [comment]
@Kramerican, this is totally intentional from LXD's perspective. LXD will mount the container's storage volume on container start and will unmount it on container stop. This is not at all random. The reason for this is to not clutter the host's mount namespace with pointless mounts when a container is not running and thus need not access the storage volume.

**Comment by Kramerican** [comment]
Ahaa I see. That makes total sense.

I am now thinking that maybe I should revisit my decision to back up stopped containers. Not sure if that makes a whole lot of sense in the first place.

Thank you for your excellent input, as usual!

**Comment by Kramerican** [comment]
Hello @brauner 

I am sorry to bother you again, but I think I have a legitimate concern at this point :) 

Ok, so the deal is that I have concluded that I have to back up stopped containers. This is due to the fact that some users might (for some reason or another) not have their containers running all the time, but may start them from time to time and thus create new data which needs to be backed up.

I think the core question here is: Is my method of doing live snapshots a valid approach? Because if there is a "better way" and I'm being a retard about things, then that should be the way to go, instead of fusking around  with trying to figure out what the hell is up with ZFS mount points.

So, what I am doing is inspired by this: [https://github.com/vistoyn/backup-tools](https://github.com/vistoyn/backup-tools)

Essentially what this does is dumping the container config, then doing an rsync > tar.gz of the container(s)

This approach was very attractive to me as I would then get

1. Fully portable copies of containers
2. Not dependent on any "snapshot chain" being in place in order to restore stuff
3. Simpler

The downside is that it takes up more diskspace - but I have been through many a horror-show trying to restore incremental backups in other systems which had gone awfully wrong. So this seemed like a more solid approach.

In any case, I have just today run into ZFS mount point weirdness again, and I am not getting worried I might have gone down the wrong path. Maybe. In any case, what I am seeing:

1. The container is running and alive and is able to access its filesystem
2. Doing 
`ls -lah /var/lib/lxd/containers/NAME`
and 
`ls -lah /var/lib/lxd/storage-pools/lxd/containers/NAME`
Gives me an empty directory, and thus my backup routine cannot back anything up
3. Doing `zfs list` shows the mount and it looks identical to other mounts. Everything seems ok.
4. Doing `zfs mount -a` makes no difference and gives me the error:

> filesystem 'lxd/containers/NAME' is already mounted
> cannot mount 'lxd/containers/NAME': mountpoint or dataset is busy

**Comment by stgraber** [comment]
The error you got is a ZFS bug.

The most common source of this is when the image the container was created from got expired by LXD. When that happens the image is renamed from images/XYZ to deleted/images/XYZ, this causes ZFS to unmount all the filesystems that were created from the image, including running containers.

At that point, you have a running container "NAME" that doesn't have its /var/lib/lxd/storage-pools/lxd/containers/NAME path mounted. But attempting to mount it (as "zfs mount -a") did above in your case, now fails because it's technically still mounted IN the container. Unfortunately ZFS doesn't know what a container is and so refuses to mount it again.

That's all very confusing and we have a number of open ZFS issues upstream to try and get ZFS itself fixed to behave as all other filesystems do.

For your backup system, if you want to grab the content of the container, I'd recommend you do:
 - For RUNNING containers, backup /proc/PID/root/ as that is guaranteed to be around even if ZFS decides to unmount the filesystem from the host. The "PID" is the container's PID1 as reported by "lxc info".
 - For STOPPED containers, running "zfs mount", then backup, then "zfs umount" will be fine. I'd just recommend you run it for the specific container you care about rather than use "zfs mount -a" as that may fail as it did in your case.

**Comment by Kramerican** [comment]
Howdy

Absolutely epic support as always. You are not only a gentleman, but indeed a scholar as well, sir! :+1: 

Anyway, now that _that_ is out of the way - then I am pleased this has a logical explanation and may be fixed. And most importantly that we have workaround(s).

_**But**_ This opens up a new kettle of worms: How to correctly update images?

I haven't gotten this far in my todolist, so I had figured I'd learn how all that stuff is set up in the near future, but now that we touch on the subject then I might as well ask now: My plan was to have a central source server which would have our custom images, and then use LXD to synch those out to other hosts - as I think you have intended, as far as I can see from the docs :)

This would avoid the problem with weird zfs unmounts entirely.

But for now, I have not found any method of updating an image on the local host directly. So I have deleted them and republished them whenever I've done changes (a slight pain, but ok whatever) - which is the cause of the issue it turns out.

I don't like having to delete images, because what if someone wants to provision a container at the moment I am deleting and publishing? This is why I was thinking of having a seperate staging host where I'd manage images and then "client" would pull from there. But I have also had the worrying thought that LXD probably uses the unique fingerprint and not the alias when updating images... 

Hmm, anyway, as you can tell I am unsure of how all this should work (docs are a bit unclear on this - but I had figured I'd learn it by doing, like I've done so far)

Any pointers would be much appreciated - and again: You guys kick ass. I'll buy you beers any time.

**Comment by stgraber** [comment]
The best way to manage images in your case should be:
 - Setup a LXD host just for use as an image source
 - Mark all images that you intend downstream servers to use as public
 - Setup an alias for each of those images. If updating, you'll change the alias to point to the new version.

That's all that's needed on the image server side.
Now on the client side, you'll do:
 - lxc remote add local-images IP-OF-SERVER --public

And lastly, you can now do:
 - lxc launch local-images:ALIAS CONTAINER

And that's going to work exactly like our public image servers, the target LXD will download the image from the source, cache it for you and then automatically update the cached image as needed.

You could also do:
 - lxc image copy local-images:ALIAS local: --auto-update --copy-aliases

Which will then copy the image from your image server to a target LXD host, mark the image as being auto-updated (so it will refresh every 6 hours) and tells LXD to also copy the source aliases.
At that point you can do:
 - lxc launch ALIAS blah

**Comment by Kramerican** [comment]
Parfait! :+1: :+1: 

Pretty much what I thought. I am a bit unclear on

_If updating, you'll change the alias to point to the new version._

Do you mean

`lxc image delete my-alias`
`lxc image publish some-container --alias=my-alias`

Or is it better to

`lxc publish some-container`
`lxc image alias create my-alias <fingerprint from prv. comman>`
`lxc image delete <old fingerprint>`

**Comment by stgraber** [comment]
Both approach work. I usually tend to prefer the latter because it gives you a chance to make sure the image is functional before you change the alias.
