### ISSUE TITLE
lxc network create testbr0 Broken on Gentoo -- Need kernel requirements.

### ISSUE THREAD

**Issue by Conjohnsonjohnson** [lxc/lxd#3334]
# Required information

 * Distribution:Gentoo
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:4.8.17-hardened-r2
   * LXC version:2.0.7
   * LXD version:2.11
   * Storage backend in use:dir

# Issue description

lxc network create testbr0 produces the following:

error: Failed to run: iptables -w -t mangle -I POSTROUTING -o testbr0 -p udp --dport 68 -j CHECKSUM --checksum-fill -m comment --comment generated for LXD network testbr0: iptables: No chain/target/match by that name.

# Steps to reproduce
You're not likely to reproduce this. I'm simply asking for some assistance working through the details of getting lxd working on Gentoo. I've discovered the vast majority of documentation assumes Ubuntu. Apparently there is some default chain/target/match that is built into Ubuntu. My iptables -L shows:

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination 

Following this:
https://stgraber.org/2016/10/27/network-management-with-lxd-2-3/
suggests 
lxc network create testbr0
should be very basic functionality. The only clues I have are the error I posted above and this:
DBUG[05-20|23:09:08] POST {"config":{},"name":"testbr0"}

I can see I need CHECKSUM support built into the kernel.

Is there an exhaustive list of kernel requirements for lxd/lxc?
I've added at least 30 lxd/lxc-specific kernel options and counting and still missing some apparently.
Any help is appreciated.

**Comment by stgraber** [comment]
We don't have exact requirements though from the top of my head, I'd say you at least need:
 - xt_comment
 - xt_CHECKSUM
 - ip_tables
 - ipt_MASQUERADE
 - ip6_tables
 - ip6t_MASQUERADE
 - ebtables

**Comment by stgraber** [comment]
The iptables error itself is pretty vague, you'd think it'd know whether the table or target was missing :)

**Comment by Conjohnsonjohnson** [comment]
Thank you Stéphane. I believe it was missing CHECKSUM in the kernel that caused the iptables error. I have all but ebtables from your list. Do you know if any options under ebtables are required? These are:
1)ebt: broute table support - CONFIG_BRIDGE_EBT_BROUTE
2)ebt: filter table support - CONFIG_BRIDGE_EBT_T_FILTER
3)ebt: nat table support - CONFIG_BRIDGE_EBT_T_NAT
4)ebt: 802.3 filter support - CONFIG_BRIDGE_EBT_802_3
5)ebt: among filter support - CONFIG_BRIDGE_EBT_AMONG
6)ebt: ARP filter support -  CONFIG_BRIDGE_EBT_ARP
7)ebt: IP filter support - CONFIG_BRIDGE_EBT_IP
8)ebt: IP6 filter support - CONFIG_BRIDGE_EBT_IP6
9)ebt: limit match support - CONFIG_BRIDGE_EBT_LIMIT
10)ebt: mark filter support - CONFIG_BRIDGE_EBT_MARK
11)ebt: packet type filter support - CONFIG_BRIDGE_EBT_PKTTYPE
12)ebt: STP filter support - CONFIG_BRIDGE_EBT_STP
13)ebt: 802.1Q VLAN filter support - CONFIG_BRIDGE_EBT_VLAN
14)ebt: arp reply target support - CONFIG_BRIDGE_EBT_ARPREPLY
15)ebt: dnat target support - CONFIG_BRIDGE_EBT_DNAT
16)ebt: mark target support - CONFIG_BRIDGE_EBT_MARK_T
17)ebt: redirect target support - CONFIG_BRIDGE_EBT_REDIRECT
18)ebt: snat target support - CONFIG_BRIDGE_EBT_SNAT
19)ebt: log support - CONFIG_BRIDGE_EBT_LOG
20)ebt: nflog support - CONFIG_BRIDGE_EBT_NFLOG

I'm guessing, if any, 1,2,3,7,8,13 but would like to document the true requirements. Super Thanks for any help. I'll post my list of kernel requirements when I get one together.

**Comment by stgraber** [comment]
I think you only need ebt_t_filter in that list. The rules we set only use the interface names and MAC addresses so don't need any of the protocol ones.

**Comment by stgraber** [comment]
Did you get past this issue with the modules I mentioned?

**Comment by Conjohnsonjohnson** [comment]
Yes Stéphane. Thank You. Specifically I believe it was xt_CHECKSUM. I'm still working on assembling a set of kernel requirements that must be added to a default kernel configuration. I'll publish my findings either here or on the mailing list, or both.

**Comment by klowe0100** [comment]
Hi. Just confirming that CONFIG_NETFILTER_XT_TARGET_CHECKSUM=y was the only missing link for me. Thanks.

**Comment by Conjohnsonjohnson** [comment]
klowe0100 wrote:
> Hi. Just confirming that
> CONFIG_NETFILTER_XT_TARGET_CHECKSUM=y
> was the only missing link for me. Thanks.
>

I believe this is a list of all kernel config requirements. Some may
already be set by default.

CONFIG_GENTOO_LINUX_INIT_SYSTEMD
CONFIG_MEMCG
CONFIG_CGROUP_DEVICE
CONFIG_USER_NS
CONFIG_EXPERT
CONFIG_CHECKPOINT_RESTORE
CONFIG_PACKET_DIAG
CONFIG_UNIX_DIAG
CONFIG_NET_IPIP
CONFIG_NET_IPGRE_DEMUX
CONFIG_NET_IPGRE
CONFIG_INET_DIAG
CONFIG_INET_UDP_DIAG
CONFIG_INET_TCP_DIAG
CONFIG_NETFILTER_ADVANCED
CONFIG_NF_NAT_REDIRECT
CONFIG_NETFILTER_XT_TARGET_CHECKSUM
CONFIG_NETFILTER_XT_MATCH_COMMENT
CONFIG_NF_NAT_IPV4
CONFIG_IP_NF_IPTABLES
CONFIG_IP_NF_FILTER
CONFIG_IP_NF_NAT
CONFIG_IP_NF_TARGET_MASQUERADE
CONFIG_IP_NF_MANGLE
CONFIG_NF_NAT_IPV6
CONFIG_NF_NAT_MASQUERADE_IPV6
CONFIG_IP6_NF_IPTABLES
CONFIG_IP6_NF_FILTER
CONFIG_IP6_NF_MANGLE
CONFIG_IP6_NF_NAT
CONFIG_IP6_NF_TARGET_MASQUERADE
CONFIG_BRIDGE_NF_EBTABLES
CONFIG_BRIDGE_EBT_T_FILTER
CONFIG_BRIDGE
CONFIG_VLAN_8021Q
CONFIG_NET_SCHED
CONFIG_NET_SCH_INGRESS
CONFIG_NET_CLS_U32
CONFIG_NET_ACT_POLICE
CONFIG_OPENVSWITCH is not set
CONFIG_VSOCKETS
CONFIG_NETLINK_DIAG
CONFIG_DUMMY
CONFIG_MACVLAN
CONFIG_VXLAN
CONFIG_TUN
CONFIG_VETH
CONFIG_FUSE_FS
CONFIG_SECURITY_APPARMOR

If you use the menu config (make menuconfig), these instructions should
result in a reasonable kernel:

======================
o lxc/lxd need the following kernel config options

  - Gentoo Linux
        -> Support for init systems, system and service managers
                -> systemd
  - General setup
        -> Control Group support
                -> Memory controller
                -> Device controller
        -> Namespaces support
                -> User namespace
        -> Configure standard kernel features (expert users)
                -> Note: This automatically enables Checkpoint/restore
support
  - Networking support
        -> Networking options
                -> Packet: sockets monitoring interface
                -> UNIX: socket monitoring interface
                -> IP: tunneling
                -> IP: GRE demultiplexer
                -> IP: GRE tunnels over IP
                -> INET: socket monitoring interface
                        -> UDP: socket monitoring interface
                -> Network packet filtering framework (Netfilter)
                        -> Advanced netfilter configuration
                        -> Core Netfilter Configuration
                                -> CHECKSUM target support
                                -> "comment" match support
                        -> IP: Netfilter Configuration
                                -> <*> iptables NAT support
                                -> <*> MASQUERADE target support
                        -> IPv6: Netfilter Configuration
                                -> ip6tables NAT support
                                -> MASQUERADE target support
                        -> Core Netfilter Configuration
                                -> <M> IPv4/IPv6 redirect support (built
as module)
                           (This is placed here because its not visible
without IP, IPv6 NAT)
                        -> Ethernet Bridge tables (ebtables) support
                                -> ebt: filter table support
                -> 802.1d Ethernet Bridging (Enabled)
                -> 802.1Q/802.1ad VLAN Support (Enabled)
                -> QoS and/or fair queueing
                        -> Ingress/classifier-action Qdisc (Enabled)
                        -> Universal 32bit comparisons w/ hashing (U32)
                        -> Traffic Policing
                -> Open vSwitch (DISABLE)
                -> Virtual Socket protocol
                -> NETLINK: socket monitoring interface
  - Device Drivers
        -> Network device support
                -> Dummy net driver support
                -> MAC-VLAN support
                -> Virtual eXtensible Local Area Network (VXLAN)
                -> Universal TUN/TAP device driver support
                -> Virtual ethernet pair device
  - File systems
        -> FUSE (Filesystem in Userspace) support
  - Security options
        -> AppArmor support
======================
