### ISSUE TITLE
Forward SSH key into LXD container

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3339]
I need to commit something to GitHub after testing the code inside container. I find it constraining that when I fix bugs on containers I need to pull all files back (which is slow) and commit from my machine. I'd like to commit from the container, but I want to share my git credentials with it (forward SSH key and username/email) - is that possible?

**Comment by albertodonato** [comment]
You can use `lxc file push` to copy your keys/config to the container.

An alternative would be to bind-mount your home directory in the container (so everything would be shared). See https://insights.ubuntu.com/2016/12/08/mounting-your-home-directory-in-lxd/ for details

**Comment by techtonik** [comment]
I am on Windows, so port forwarding is the only alternative way. I'd rather not copy my private keys around, but use agent forwarding for encryption.

**Comment by stgraber** [comment]
You can just use sshd agent forwarding. So setup your container to have ssh running, then connect to it with "ssh -A" (or whatever the Windows equivalent is).

**Comment by techtonik** [comment]
That doesn't work by default, because default node is behind NAT and is only reachable through LXD.

**Comment by stgraber** [comment]
Yeah, so you're kinda out of options. To get SSH from the container to some other server working you need to do one of:
 - Generate a SSH key in the container, grab the public key and add to your account
 - Push your existing private key to the container
 - SSH into the container and use the SSH agent forward feature

Not much LXD can really do about any of those. The 3rd option is obviously easiest but as you said, requires your ssh client to be able to reach the LXD container, so depends on your network setup.

**Comment by techtonik** [comment]
I need to somehow find the time to finish the patch for port forwarding through LXD client (sigh)..
