### ISSUE TITLE
LXD dockerfile equivalent.

### ISSUE THREAD

**Issue by tuapuikia** [lxc/lxd#3343]
Hi,

Do we have API that support something similar to dockerfile ? If possible, I try to avoid chef or ansible for container creation. 

regards,
Stan Wong

**Comment by stgraber** [comment]
LXD itself doesn't provide a Dockerfile equivalent as Dockerfile is really meant for application containers where you build a somewhat minimal, usually heavily modified image for a single application.

LXD instead behaves like a VM host. Our images are full Linux distributions as you'd get them if you installed them from their installation media. They're meant to be long running and be updated and managed as a VM or real system would.

That being said, if you wanted to automate image customization, that's perfectly doable by invoking the "lxc exec" and "lxc file" on a cleanly created container, then publish the result as a new image with "lxc publish".
That or directly using the REST APIs that those tool use (see doc/rest-api.md).

**Comment by ChristopherLClark** [comment]
> They're meant to be long running and be updated and managed as a VM or real system would.
gross.

**Comment by vazhnov** [comment]
@tuapuikia, there are no direct equivalent of Dockerfile in LXC/LXD, but you can try [mkosi](https://github.com/systemd/mkosi). Here is a list of other tools: https://wiki.debian.org/SystemBuildTools
