### ISSUE TITLE
Automatic security updates for official LXD images

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3344]
Are offical LXD images configured to update themselves with latest security patches? Some of mine are exposed to internet and I am concerned about people breaking into them.

How to check if my existing containers update themselves automatically?

**Comment by stgraber** [comment]
The images themselves will auto-update in the LXD image store, but that won't update your existing containers.

To have your containers auto-install updates you need to configure them to do so. This varies depending on distributions. For Debian and Ubuntu, that's usually done by installing and configuring unattended-upgrades.
