### ISSUE TITLE
docker.io or Docker-CE

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3349]
https://askubuntu.com/questions/906289/docker-ce-or-docker-io-package

Am I right that the only reason why https://packages.ubuntu.com/xenial/docker.io package should be used is its compatibility with LXD?

What is the status of those compatibility patches? Are there upstream links to track?

**Comment by brauner** [comment]
The necessary patches are available from `17.06` onwards if I'm not misremembering. Docker hasn't yet released a new version. When they will things will be fine.

**Comment by stgraber** [comment]
https://jenkins.linuxcontainers.org/job/lxd-test-docker/ is a daily test we run against the latest git build of docker to see how it behaves in LXD.

This confirms that what's in their git repo is currently functional, but as @brauner said, unreleased.

**Comment by techtonik** [comment]
Thanks for the heads up.
