### ISSUE TITLE
LVM storage misbehavior 

### ISSUE THREAD

**Issue by nakatadim** [lxc/lxd#3351]
Dear LXD team,
first the required information
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 x86_64
 * The output of "lxc info" or if that fails:
   * Kernel version:4.4.0-78-generic
   * LXC version:2.0.8
   * LXD version:2.13-0ubuntu3~ubuntu16.04.1~ppa1
   * Storage backend in use: LVM

# Issue description
1. In LVM storage setup- the “lxc launch” command always creates the container’s logical volume in the same LV pool, where the source image resides, without considering which storage pool is set in the container's profile.

2. Deleting of a storage pool via lxc deletes others too.

# Steps to reproduce point. 1

1. Let’s have two lvm thin pools predefined
`vgcreate vg_data /dev/vda7 /dev/vdb7`
2. Create two thin pools
`lvcreate -L 2G --thinpool tp_1 vg_data`
`lvcreate -L 1G --thinpool tp_2 vg_data`
3. Lets now add them both in LXD
`lxc storage create pool1 lvm lvm.thinpool_name='tp_1' lvm.vg_name='vg_data'`
`lxc storage create pool2 lvm lvm.thinpool_name='tp_2' lvm.vg_name='vg_data'`
4. Lets now have pool1 set as “root” disk device for profile "default" and pool2 set as “root” disk device for a new pool called “second”
`lxc profile copy default second`
`lxc profile device add default root disk path=/ pool=pool1`
`lxc profile device add second root disk path=/ pool=pool2`
5. All set- let’s now init a container with “default” profile
`lxc init ubuntu: u1604default`
As expected this creates two volumes in “pool1”- one for the image and one for the container-` lxc storage volume list pool1`
		+-----------+------------------------------------------------------------------+---------+
|   TYPE    |                               NAME                               | USED BY |
+-----------+------------------------------------------------------------------+---------+
| container | u1604default                                                     | 0       |
+-----------+------------------------------------------------------------------+---------+
| image     | 8fa08537ae51c880966626561987153e72d073cbe19dfe5abc062713d929254d | 0       |
+-----------+------------------------------------------------------------------+---------+
6. Let’s now create a container from the same image, using the “second” profile- we expect the container to be created in “pool2”
`lxc init ubuntu: u1604second -p second`
Looks like lxc storage command says it has done it right: “lxc storage volume list pool2” 
	+-----------+-------------+---------+
|   TYPE    |    NAME     | USED BY |
+-----------+-------------+---------+
| container | u1604second | 0       |
+-----------+-------------+---------+

BUT in fact something else has happened:

Running “lvdisplay” says that the “u1604second” is using the “tp_1” volume which is "pool1" for lxd, where we expect this to be in “tp_2”( pool2 from "second" profile"). Feels like it follows the volume location of the image.  

# Steps to reproduce point. 2
There’s another strange behavior causing deletion misbehavior- deleting one of the pools via lxd deletes the whole volume group. Continuing from where we left in point. 1:
1. Lets first delete the container on “pool2”
`lxc delete u1604second`
2. Lets delete the root device from “second” profile so that we can delete “pool2” storage.
`lxc profile device remove second root disk path=/ pool=pool2`
3. Lets now delete “pool2”
`lxc storage delete pool2`
And this causes: lost of “vg_data” volume group, including “pool1” or deleting one of the volume causes lost of all.
Lvs shows just the host’s root lv
```
  LV      VG      Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_root vg_root -wi-ao---- 9.31g           
```       

Thanks,
Atanas

**Comment by brauner** [comment]
Thanks for the detailed description and reproducers!
I've managed to reproduce point `2` and sent a branch that fixes it. I will try to reproduce point `1`.

**Comment by brauner** [comment]
The first issue should be fixed by my branch as well. A couple of short noes: `LXD` will always assume that it has full control of the storage pool. We try to be very explicit about this and mention it in our storage documentation. This means when LXD deletes a storage pool - depending on the exact behavior of the driver - it will tear down everything inside the pool at the time of deletion. This is why each driver checks, when it creates the storage pool, that it is indeed empty and will refuse to create the storage pool if it is not. The `LVM` driver somehow skipped this check so far. My branch will make it so that this behavior is strictly enforced. However, this restriction will be loosened in a follow up commit for thinpool `LVM` pools. In case only the thinpool exists in the pool at the time of creation, `LVM` will create the pool.

**Comment by nakatadim** [comment]
Thanks for the fast response. It's absolutely fare for the LXD to have full control- the thing is that by deleting "pool2" in the example, it deleted its "pool1" as well incl. the whole volume group. The reason why i handle the LV creation with the original lv* tools is the fact that for example i could need lvm raid1 or lvm stripe with custom stripe size etc. so in order for me to do that i can't just give the whole volume group to lxd.

**Comment by brauner** [comment]
@nakatadim, yeah that's a totally valid use-case. The branch I sent will let you re-use already existing lxd thinpools provided they are the only logical volume that exists in the volume group at the time of creation. Is that sufficient for you use-case?

**Comment by nakatadim** [comment]
Yeap, that should do the trick. Thanks!
