### ISSUE TITLE
Improve and make LXD documentation more visible

### ISSUE THREAD

**Issue by nicolas33** [lxc/lxd#3355]
- There are the lxc man pages but there is nothing about lxd.
- There is no clear documentation about how lxd integrates with lxc.
- It is not clear what of lxc is relevant when working with lxd.

Each time I need yet another information I have to search online for someone who wrote something about my own use case or CLI option. Once the correct information is found (and this might be VERY hard sometimes because of the LXC/LXD names being very similar), I pray that this is still working/relevant.

My user experience of lxd tends to be very frustrating and time consuming. The exact opposite of what it's supposed to provide, mostly because configuration files and CLI options are not clear.

Please, do not point me to yet another blog or external documentation. They are all partial when not outdated.

This project should provide everything users might need to know.

**Comment by stgraber** [comment]
LXD does ship with manpages for every one of the LXD commands (auto-generated as the preferred way to access the help is with "lxc COMMAND --help":
```
/usr/share/man/man1/lxd.1.gz
/usr/share/man/man1/lxc.publish.1.gz
/usr/share/man/man1/lxc.restore.1.gz
/usr/share/man/man1/lxc.exec.1.gz
/usr/share/man/man1/lxc.delete.1.gz
/usr/share/man/man1/lxc.info.1.gz
/usr/share/man/man1/lxc.1.gz
/usr/share/man/man1/lxc.init.1.gz
/usr/share/man/man1/lxc.start.1.gz
/usr/share/man/man1/lxc.remote.1.gz
/usr/share/man/man1/lxc.finger.1.gz
/usr/share/man/man1/lxc.storage.1.gz
/usr/share/man/man1/lxc.copy.1.gz
/usr/share/man/man1/lxc.manpage.1.gz
/usr/share/man/man1/lxc.list.1.gz
/usr/share/man/man1/lxc.stop.1.gz
/usr/share/man/man1/lxc.move.1.gz
/usr/share/man/man1/lxc.restart.1.gz
/usr/share/man/man1/lxc.profile.1.gz
/usr/share/man/man1/lxc.version.1.gz
/usr/share/man/man1/lxc.help.1.gz
/usr/share/man/man1/lxc.monitor.1.gz
/usr/share/man/man1/lxc.config.1.gz
/usr/share/man/man1/lxc.pause.1.gz
/usr/share/man/man1/lxc.file.1.gz
/usr/share/man/man1/lxc.network.1.gz
/usr/share/man/man1/lxc.image.1.gz
/usr/share/man/man1/lxc.snapshot.1.gz
/usr/share/man/man1/lxc.launch.1.gz
```

All configuration options as well as more general topic information is included in the source tree and all source tarballs: https://github.com/lxc/lxd/tree/master/doc

There is certainly a lot of confusion between LXC and LXD and the naming is certainly problematic, though that's not something we ever could do much about (management decision).

Basically:
 - "lxc-*" binaries are LXC tools
 - "lxc" is the LXD command line client
 - "lxd" is the LXD daemon

When using LXD, only use the last two. When using LXC, only use the "lxc-*" tools. You can't mix the use of the two as they won't see each other's containers.

We have some work planned to expose the documentation in doc/ to the LXD website and add a number of extra topics. It's just not something that many people are enthusiastic about working on nor is particularly rewarding (unlike the blog posts you mentioned which have been working very well).

So our current approach is to continue to publish good examples as blog posts, keep documenting all configuration options and API in code tree (doc/), extend our existing topic documentation to include more examples and make things more visible by having our website automatically publish what's in the code tree (as doing it manually would just lead to even more outdated documentation.

**Comment by nicolas33** [comment]
Sorry about the man pages. I'll open a bug report to my distrib not packaging them.

Also, related to #477 that is 2 years old. I don't know if contributors are enthusiastic when it comes to documentation but I know for sure that the user experience is poor sometimes.

I'm used to read the --help doc but it's not easy to get the full overview. For example:
- I still do not make clear distinction between the "local" and "public" images;
- It's not clearly defined what --alias is for: some options require an alias, some don't;
- It's not very clear what the `<image>` is all about when working with the CLI options;
- I've never could export an image into a one backup file.

Samples:

### lxc image export

```
lxc image export [<remote>:]<image> [target]
    Export an image from the LXD image store into a distributable tarball.

    The output target is optional and defaults to the working directory.
    The target may be an existing directory, file name, or "-" to specify
    stdout.  The target MUST be a directory when exporting a split image.
    If the target is a directory, the image's name (each part's name for
    split images) as found in the database will be used for the exported
    image.  If the target is a file (not a directory and not stdout), then
    the appropriate extension will be appended to the provided file name
    based on the algorithm used to compress the image.
```
Reading this only leads to more questions:
- WTF is a "split image"?
- What are the supported compression formats?

### lxc image import

```
lxc image import <tarball> [<rootfs tarball>|<URL>] [<remote>:] [--public] [--created-at=ISO-8601] [--expires-at=ISO-8601] [--fingerprint=FINGERPRINT] [--alias=ALIAS...] [prop=value]
    Import an image tarball (or tarballs) into the LXD image store.
```
Now, how to import the exported directory? There is no options to import it. What file should I use? What is a "rootfs tarball"?

### lxc image edit

```
lxc image edit [<remote>:]<image>
    Edit image, either by launching external editor or reading STDIN.
    Example: lxc image edit <image> # launch editor
             cat image.yaml | lxc image edit <image> # read from image.yaml
```
Once read this, what is this f***g `image.yaml` all about? Where are the specs of the YAML image file and what are the available options? Why `lxc image edit <fingerprint>` works? Undocumented feature or the documentation is misleading about what the "image" is? Currently, this documentation is not very helpful.


And I've reported issues only for few basic features and concepts.

BTW, displaying the output of --help to stderr sounds wrong and it's boring to add `2>&1` to pipe this all the time.

**Comment by nicolas33** [comment]
Oh, and thanks for the above quick response. :-)

**Comment by nicolas33** [comment]
Another example: 
```
$ lxc file push
lxc file push [-r|--recursive] [-p|--create-dirs] [--uid=UID] [--gid=GID] [--mode=MODE] <source path> [<source path>...] [<remote>:]<container>
$ lxc file push ~/.ssh/id_ed25519.pub test:
error: Invalid target test
```

So, reading the doc more closely, this says:
```
Examples:
To push /etc/hosts into the container foo:
    lxc file push /etc/hosts foo/etc/hosts
```

Hmm, looks like the lxc push spec should be:
```
lxc file push [-r|--recursive] [-p|--create-dirs] [--uid=UID] [--gid=GID] [--mode=MODE] <source path> [<source path>...] [<remote>:]<container>[/<path>]
```

So, let's fix my command:
```
$ lxc file push ~/.ssh/id_ed25519.pub test:~/.ssh/authorized_keys
error: unknown remote name: test
```

Is it possible to push a file to a local image? The spec says `[<remote>]` (optional remote) while the error seems to require a remote image?

Ok, now I'm really **frustrated**. :-/

**Comment by nicolas33** [comment]
(notice my last command obviously wrong but this doesn't invalidate my point about the "remote" thing).

**Comment by stgraber** [comment]
The current help for "lxc file push" is:

```
lxc file push [-r|--recursive] [-p|--create-dirs] [--uid=UID] [--gid=GID] [--mode=MODE] <source path> [<source path>...] [<remote>:]<container>/<path>
```

Which means:

```
lxc file push ~/.ssh/id_ed25519.pub test/root/.ssh/authorized_keys
```

"~" is dependent on the user and its home directory so can't be expanded by LXD, full paths are required for file operations (since all pushes happen as root I'm assuming you meant "/root/" above).

**Comment by nicolas33** [comment]
Ok, thanks. The lagging version of the distrib does not help either...

**Comment by stgraber** [comment]
We now have control of http://lxd.readthedocs.io/en/latest/

We should improve it to look good and then I'll figure out how to get the embedded code for that stuff going so that it can integrate with our website.

@albertodonato can you take a look through the readthedocs rendering of our docs and send fixes for anything that looks broken/wrong?
