### ISSUE TITLE
lxc list -- IPV4 table element not being populated on Gentoo

### ISSUE THREAD

**Issue by Conjohnsonjohnson** [lxc/lxd#3357]
* Distribution: Gentoo
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: linux-4.8.17-hardened-r2
   * LXC version: 2.0.7
   * LXD version: 2.11
   * Storage backend in use: dir

After creating a network, attaching the network, and starting the container, 'lxc list' shows an entry for IPV6 but not IPV4.

# Steps to reproduce
It seems likely this is a missing kernel or package dependency so perhaps it's not reproducible. Surely I'm the only one seeing this odd behavior. I'm not sure how serious it is.

1. Step one
lxc network create testbr0
lxc network show testbr0 gives this:
config:
  ipv4.address: 10.243.123.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:3147:fac5:eede::1/64
  ipv6.nat: "true"
name: testbr0
type: bridge
used_by: []
managed: true

 2. Step two
lxc network attach testbr0 centos default eth0
lxc start centos

 3. Step three
'lxc list' gives this:

+--------+---------+------+-----------------------------------------------+------------+-----------+
|  NAME  |  STATE  | IPV4 |                     IPV6                      |    TYPE    | SNAPSHOTS |
+--------+---------+------+-----------------------------------------------+------------+-----------+
| centos | RUNNING |      | fd42:3147:fac5:eede:216:3eff:fe2e:6718 (eth0) | PERSISTENT | 0         |
+--------+---------+------+-----------------------------------------------+------------+-----------+

Of course, if I set ipv6.address=none, then both IPVx table elements are empty.

+--------+---------+------+------+------------+-----------+
|  NAME  |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+--------+---------+------+------+------------+-----------+
| centos | RUNNING |      |      | PERSISTENT | 0         |
+--------+---------+------+------+------------+-----------+

Am I doing something wrong? 

Here's a dumb question. If I set ipv4.address=192.168.0.83/24

Should I be able to ping a local interface like so:
[root@centos ~]# ping 192.168.0.80
connect: Network is unreachable

Thanks for any help.

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
Sounds like your container simply never grabbed an IP address...

Can you run:
 - lxc exec centos -- ps fauxww
 - lxc exec cetnos -- ip -4 addr show

What image are you using for that centos container?

**Comment by stgraber** [comment]
(IPv6 will auto-configure through the kernel without the need for any dhcp client or similar user space process, so that explains why it'd be setup when ipv4 isn't).

**Comment by Conjohnsonjohnson** [comment]
Thanks for the help Stéphane,

The result of -- ps fauxww is:
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         16  0.0  0.0 151028  3464 ?        Rs+  01:01   0:00 ps fauxww
root          1  0.0  0.0  42476  3992 ?        Ss   00:58   0:00 /sbin/init

And the result of -- ip -4 addr show is:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever

I'm using this image:  images:centos/7/amd64  from https://images.linuxcontainers.org

At one point lxc told me this:
error: Failed to add interface to bridge: Failed to run: ovs-vsctl add-port eth0 vethcf048ea3:

So it seems openvswitch might be a dependency. I installed openvswitch, started the database and server, but that didn't help.

Could the hardened kernel be a problem? For example, when I built lxc it asked for CONFIG_CHECKPOINT_RESTORE but that wasn't in the hardened kernel. It was in another kernel I checked but not hardened. So far that's the only kernel config option I've ignored.

I'm running out of ideas, but will keep trying.

**Comment by stgraber** [comment]
So looks like systemd in your container is pretty sad. Having just the init process running is the usual sign of systemd having failed to start.

The most common reason for that, at least for Gentoo users, is a missing "name=systemd" cgroup on the host, explained by the fact that Gentoo doesn't use systemd itself.

You should be able to fix this with:
```
mkdir -p /sys/fs/cgroup/systemd
mount -t cgroup cgroup /sys/fs/cgroup/systemd -o name=systemd
```

But you'll then need to make sure this is done on every start of the host or the problem will re-appear.
With this done, restarting the container should get you more processes running, quite possibly including the dhcp client which will then get you an IPv4 address.

**Comment by brauner** [comment]
@stgraber, this should be possible as a mount hook. This somewhat relates to https://github.com/lxc/lxc/pull/1597 where someone wants to mount cgroups prior to systemd start. The trick here would be to have this run **after** the cgroup namespace has been unshared. So we would make it so that `lxc.hook.mount` is executed **after all** namespaces have been created.

**Comment by brauner** [comment]
Obviously, this is only possible as a mount hook in case the hierarchy has been created on the host first. Otherwise the kernel will refuse the mount with `EPERM` since it enforces that hierarchies can only be created in the initial root user namespace.

**Comment by stgraber** [comment]
@brauner hmm, I thought you couldn't mount new controllers as part of a cgroup namespace, otherwise systemd would just mount it itself.

**Comment by brauner** [comment]
@stgraber, yeah, that's what I mentioned in the next comment. :) It's just that it might be convenient to have this setup as a hook but e.g. placed the systemd controller as an fstab entry on the host (or something saner).

**Comment by stgraber** [comment]
@brauner I don't really like having such a systemd special case in LXD's code... I'd prefer that the gentoo init script just mounts /sys/fs/cgroup/systemd before starting LXD, possibly optional as that'd only be needed for those running systemd containers (gentoo on gentoo would be fine).

**Comment by brauner** [comment]
@stgraber, oh sorry, we misunderstood each other. I just meant that the user can just set a `raw.lxc` value for that.

**Comment by stgraber** [comment]
Ah, yeah, they could. I still feel like for this, the user is more likely to just dump the mkdir + mount in /etc/rc.local and call it done :)

**Comment by Conjohnsonjohnson** [comment]
Possibly I'm misunderstanding the mkdir + mount instructions... cuz its giving me this:

mount: wrong fs type, bad option, bad superblock on cgroup,
       missing codepage or helper program, or other error

Possibly the best solution is to abandon the hardened kernel and compile a Gentoo kernel. There is support in the later for systemd:

Gentoo Linux  ---> 
     Support for init systems, system and service managers  --->
          [ ] systemd (NEW)

Note its not selected by default. I'm guessing that will provide what centos containers need.

**Comment by brauner** [comment]
@Conjohnsonjohnson, well I guess Gentoo will soon drop `grsecurity` since they effectively un-open-sourced themselves.

**Comment by Conjohnsonjohnson** [comment]
@brauner Yes, they've dropped the 3.x series already and say "the 4.x series will not be as reliable as the 3.x series was"... so hardened is looking more like softened at this point. I think you're right, it may be dropped altogether some day soon.

**Comment by stgraber** [comment]
Closing this issue as there's nothing for us to fix in LXD that I can see.
Let us know if anything is still misbehaving after you got a working kernel and cgroup configuration.

**Comment by Conjohnsonjohnson** [comment]
The correct mount command is:
mount -t cgroup -o none,name=systemd systemd /sys/fs/cgroup/systemd
