### ISSUE TITLE
No privileges from Windows pushes

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3363]
* The output of "lxc info" or if that fails:
```
  driver_version: 2.0.7
  kernel_architecture: x86_64
  kernel_version: 4.10.0-22-generic
  server: lxd
  server_version: "2.12"
```
```
>lxc version
2.13
```

### Issue description
```
# lxc file push build.sh lx/root/build.sh
# lxc exec lx -- ls -la
...
----------  1 root root    36 May 30 12:17 build.sh
```

The same with recursive uploads. I am thinking if `0o777` should be the default if no more information it given?

**Comment by techtonik** [comment]
Just discovered `--mode` parameter. `lxc file push build.sh --mode 744 lx/root/build.sh` works for me without implicit magic.

**Comment by techtonik** [comment]
`--mode` flag doesn't work with recursive pushes. Reopening.
```
error: can't supply uid/gid/mode in recursive mode
```

**Comment by stgraber** [comment]
The problem with supporting --mode with -r is that you don't want the same mode for files and for directories.

Though maybe we can do something clever with masking there, effectively granting execute access to directories where read would be granted. @brauner

**Comment by techtonik** [comment]
The PR above at least makes uploaded files and dirs
```
-rw-rw-rw-
drwxr-xr-x
```
