### ISSUE TITLE
Globally defined dnsmasq.conf read with lxc network create.

### ISSUE THREAD

**Issue by georghopp** [lxc/lxd#3367]
# Required information

 * Distribution: gentoo but shouldn't make any difference
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.11.1
   * LXC version: 2.0.7
   * LXD version: 2.11
   * Storage backend in use: btrfs 4.10.2

# Issue description

The dnsmasq process spawned by lxd read the global configuration in /etc/dnsmasq.conf
So if you run a dnsmasq process on your host for whatever reason it is quite difficult to manage lxd networks.

# Steps to reproduce

 1. Have a globally running dnsmasq with a configuration in /etc/dnsmasq.conf, explicitly bound to one interface.
 2. lxc network create testbr0

    error: Failed to run: dnsmasq --strict-order --bind-interfaces --pid-file=/var/lib/lxd/networks/testbr0   /dnsmasq.pid --except-interface=lo --interface=testbr0 --listen-address=10.165.92.1 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/lib/lxd/networks/testbr0/dnsmasq.leases --dhcp-hostsfile=/var/lib/lxd/networks/testbr0/dnsmasq.hosts --dhcp-range 10.165.92.2,10.165.92.254,1h --listen-address=fd42:305b:7388:6347::1 --enable-ra --dhcp-range ::,constructor:testbr0,ra-stateless,ra-names -s lxd -S /lxd/ -u nobody: dnsmasq: failed to create listening socket for 10.165.92.1: Address already in use

The problem here is that the dnsmasq instance does not load its own config file but the globally defined. If I run the following:

    lxc network create testbr0 raw.dnsmasq='#'

It works as  the following is added to the start command:

    --conf-file=/var/lib/lxd/networks/testbr0/dnsmasq.raw

# Suggestion

I think it would be a good idea to always create a separate config for dnsmasq and pass the `--conf-file` argument.

But perhaps there is a way to specify a dnsmasq config file that I have missed...

**Comment by stgraber** [comment]
Interesting, kinda surprised we never noticed that :)

**Comment by BobVul** [comment]
Does this now make it impossible to add conf options to lxd's dnsmasq?

I have one server where I have the host going through lxd's dnsmasq - which dnsmasq didn't like (since it was forwarding to itself). The solution was to specify a different resolver list/file via dnsmasq.conf, so the host resolves against dnsmasq and dnsmasq forwards correctly to an external resolver.

This was to make it easier to discover lxd hostnames/addresses from the host. Though maybe I'm missing an obvious/easier method.

**Comment by stgraber** [comment]
You can always add extra statement to LXD"s dnsmasq instance by using the "raw.dnsmasq" configuration key.

**Comment by BobVul** [comment]
Ah... completely missed that config, sorry. I probably should've read the commit more carefully!

**Comment by stgraber** [comment]
It's also listed in the documentation :)
https://github.com/lxc/lxd/blob/master/doc/networks.md

**Comment by BobVul** [comment]
Yea, I must be completely blind today, considering it's even mentioned in the opening comment on this issue.
