### ISSUE TITLE
Cannot restart container after stopping it with open exec

### ISSUE THREAD

**Issue by lutostag** [lxc/lxd#3371]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2 LTS (Xenial Xerus)
 * The output of "lxc info": http://pastebin.ubuntu.com/24727414/
   * Storage backend in use: zfs

# Issue description

After launching a container and connecting to it, stopping the container from another tty will prevent the container from starting again.

# Steps to reproduce
```
lxc launch ubuntu:16.04 testhost
lxc exec testhost bash -- -c "su - ubuntu"
ls
# from another terminal
lxc stop testhost # which will kick us out of our session in the previous terminal
# back to the first terminal
lxc start testhost
error: Monitor is hung
# to a different terminal
lxc start testhost # hangs indefinitely so ctrl-c
```
# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [x] output of the client with --debug
[client-log.txt](https://github.com/lxc/lxd/files/1042094/client-log.txt)
 - [ ] output of the daemon with --debug

I will try running this with --debug on the daemon and see if I get anything more helpful.

**Comment by lutostag** [comment]
`sudo systemctl restart lxd` will allow us to start/stop the container again, so there is a workaround.

**Comment by stgraber** [comment]
Does that reliably happen for you?

The "monitor is hung" error comes from LXC but we've never managed to reliably get it to happen.

@brauner

**Comment by lutostag** [comment]
@stgraber yes, using those exact steps I have replicated it at least 3 times (sometime the "monitor is hung" error shows up and sometimes the `lxc start foo` get hung forever). On two different systems, one amd64 one ppc64el. with the ppa version.

The snap version hits a different error about the zfs filesystem already mounted (but that is a problem I often hit on that machine and think I may have gotten it into a weird state somehow by myself, so ignore that data point).

**Comment by brauner** [comment]
@lutostag, can you try to reproduce with `lxc.loglevel = debug` and provide me the old and the new container log, meaning:

    /var/log/lxd/<container>/lxc.log
    /var/log/lxd/<container>/lxc.log.old

So on the affected container do `lxc config set <container> raw.lxc "lxc.loglevel=debug"`.

**Comment by lutostag** [comment]
Seems like, it happens only when the container is started when it is being stopped in another terminal (or for some time period shortly after -- if you wait too long it doesn't occur). Had to run it a few times to get it to show up.

Please let me know if there is any other logs/debug session I can provide. (I think I can grant y'all access to the machine to poke it actively if you would like as well).

logs (only the old was there):
[lxc.log.old.txt](https://github.com/lxc/lxd/files/1045060/lxc.log.old.txt)

**Comment by brauner** [comment]
I know, I have some theories. :)

**Comment by brauner** [comment]
Tentatively closed by https://github.com/lxc/lxc/pull/1618 .
