### ISSUE TITLE
"lxd network create" fails on a machine in a 10.0.0.0/8 network: Unable to find a free IPv4 subnet

### ISSUE THREAD

**Issue by jordanauge** [lxc/lxd#3376]
Hello,

I am running LXD on a machine in a 10.0.0.0/8 network and noticed some hardcoded network in LXD, in [lxd/network_utils.go](https://github.com/lxc/lxd/blob/master/lxd/networks_utils.go).

The relevant piece of code is the following:

> func networkRandomSubnetV4() (string, error) {
> 	for i := 0; i < 100; i++ {
> 		cidr := fmt.Sprintf("10.%d.%d.1/24", rand.Intn(255), rand.Intn(255))
> [...]
> 		if networkInRoutingTable(subnet) {
> 			continue
> 		}
> [...]
> 		return cidr, nil
> 	}
> 	return "", fmt.Errorf("Unable to find a free IPv4 subnet")
> }

If the host has a route towards 10.0.0.0/8, `lxd network add` with always fail with the error "Unable to find a free IPv4 subnet". Would it be possible to have this as a configuration option ? 

Thanks

**Comment by stgraber** [comment]
This is the intended behavior and there's no real reason to change it.
The random subnet code is pretty conservative and will not let you mask part of an outside network. So the logic appears to be working perfectly fine in this case.

In this case, you simply need to directly tell LXD what you want:
```
lxc network create lxdbr0 ipv4.address=10.0.3.1/24 ipv4.nat=true
```

That will configure the LXD bridge with that subnet and not use the random subnet generator.

**Comment by jordanauge** [comment]
It is impossible to understand why it fails without looking at the source code.
