### ISSUE TITLE
error: Block device doesn't support quotas

### ISSUE THREAD

**Issue by gjedeer** [lxc/lxd#3378]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-78-generic
  server: lxd
  server_pid: 3494
  server_version: "2.13"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu16

```

# Issue description

Block I/O quotas aren't working.

```
# lxc config device set container root limits.read 30MB
error: Block device doesn't support quotas: 259:2
# ls -l /dev | grep 259
brw-rw---- 1 root         disk    259,   2 May 31 10:56 md1p1
```

Possibly having to do with md-backed zfs.

# Steps to reproduce

 1. Follow part 4 of the blog posts
 2. It doesn't work
 3. Cry

# Information to attach

```
# zpool status
  pool: tank
 state: ONLINE
  scan: scrub repaired 0 in 8h19m with 0 errors on Sun May 14 08:43:40 2017
config:

        NAME        STATE     READ WRITE CKSUM
        tank        ONLINE       0     0     0
          md1       ONLINE       0     0     0
        logs
          md2       ONLINE       0     0     0
        cache
          sda6      ONLINE       0     0     0
          sdb6      ONLINE       0     0     0

errors: No known data errors
```

**Comment by stgraber** [comment]
Hmm, right so we don't know how to resolve device mapper devices to backing physical disk.

To be fair, even if we did, it wouldn't really work. ZFS tends to bypass blkio limits (because of ZFS being a ported Solaris kernel module and not using a lot of the Linux VFS infrastructure). The blkio limits are also tied to a physical block device, not a partition and not a virtual device, so to be able to set it, we need to resolve things all the way to the physical disk, which as you can imagine becomes a bit messy when your filesystem is backed by multiple block devices.

I think the best thing we can do here is improve our storage documentation to explain how those limits actually work, including the fact that mixing md devices won't work and that ZFS limits don't work so well.

**Comment by stgraber** [comment]
I pushed a commit to my branch which should give a bunch more details on what works and what doesn't with regard to blkio limits.

**Comment by gjedeer** [comment]
Thank you. 

If I may suggest something, perhaps the discussion of preferred filesystems for LXD should also mention this so other people don't fall into this trap. "ZFS is the best as long as you use raid-z instead of md" or something similar.

**Comment by gjedeer** [comment]
Actually it seems that if I/O limits don't affect ZFS, there's no single recommended file system for LXD? btrfs is unstable and will likely have the same issues, and ext* or LVM have other issues?

> Our recommendation is ZFS as it supports all the features LXD needs to offer the fastest and most reliable container experience.

**Comment by stgraber** [comment]
@gjedeer yeah, unfortunately the answer as to what the best storage backend for LXD is "it depends", as is often the case with those things.

**Comment by gjedeer** [comment]
Thanks you, closing the issue then.
