### ISSUE TITLE
--format=json ignored by lxc image info

### ISSUE THREAD

**Issue by smoser** [lxc/lxd#3380]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-21-generic
   * LXC version: 2.14-0ubuntu1
   * LXD version: 2.14-0ubuntu1
   * Storage backend in use: zfs

# Issue description
`lxc image info` and `show` seem to ignore the `--format=json` argument.  Note that image list (`lxc image --format=json list`) respects it.

# Steps to reproduce
 1. run lxc image show:

        $ lxc image show --format=json ubuntu-daily:xenial
        auto_update: false
        properties:
          architecture: amd64
          description: ubuntu 16.04 LTS amd64 (daily) (20170531)
          label: daily
          os: ubuntu
          release: xenial
          serial: "20170531"
          version: "16.04"
        public: true

 2. verify that is not json output (at least per 'json.tool')

        $ lxc image show --format=json ubuntu-daily:xenial | python3 -m json.tool
        Expecting value: line 1 column 1 (char 0)

**Comment by stgraber** [comment]
"--format=json" is only implemented by "lxc list" and "lxc image list" as shown in the usage.

Our command line parser is a bit annoying in that it doesn't know what sub-commands are, so when you do "lxc image info --help" it shows you the same as "lxc image --help", but the listed usage for "lxc image info" is correct.

**Comment by stgraber** [comment]
The various "lxc * info" commands are also bad candidates for supporting --format as they don't directly map to any API object and so don't really have a good structure for us to serialize.

That's unlike the "lxc * show" commands which output raw yaml and can be easily parse.

**Comment by smoser** [comment]
Well, if i were trying to parse output of lxc command line tools, i'd like to have *some* format that is consistent.
lxc list --format=json will outpt json.
lxc show --format=IGNORED will output yaml

Perhaps if you just added and honored '--format=yaml' to lxc list, then i could at least know that i can always get yaml out.  converting json to yaml should be simple enough as you clearly have a yaml dumper.

**Comment by stgraber** [comment]
Yeah, adding "yaml" as an option to the list commands should be easy enough.
