### ISSUE TITLE
custom sysctl - how to set

### ISSUE THREAD

**Issue by siteshbehera** [lxc/lxd#3382]
I want to add some container specific sysctl configs. I can very well do it inside container as sysctl -w  net.ipv4.conf.vrrp150.rp_filter=0. 

I added it to /etc/sysctl.conf, but when we reboot the container, we dont see the config added. Is there a way to add sysctl confgs via raw.lxc settings ?

I tried adding something like this:
  raw.lxc: |-
    lxc.config.sysctl.net.ipv4.conf.rp_filter: 0

But I got error:
Config parsing error: Invalid raw.lxc line: lxc.config.sysctl.net.ipv4.conf.rp_filter: 0

**Comment by stgraber** [comment]
Nope, doing it through an init script in your container is the way to go.

/etc/sysctl.conf really should work, but I suspect your init system is skipping the application of sysctls for some reason (likely a container check)... You may want to file a bug against your init system for that issue, or if you don't feel like it, just put the sysctl call in your own init script.

**Comment by siteshbehera** [comment]
I am using ubuntu16.04. So you think its a systemd issue? 

I can see sysctl configs added under /etc/sysctl.d/99-salt.conf. I can see none of the sysctls get applied.  So its basically an init / systemd issue ?

**Comment by stgraber** [comment]
Yes, I expect systemd-sysctl is failing because of some sysctl keys which can't be set in containers. Then rather than ignoring those and moving on, it fails immediately and never gets to applying yours.

**Comment by siteshbehera** [comment]
Makes sense, thx. I will do the cleanup. You can close the bug.
