### ISSUE TITLE
Failed to initialize container storage

### ISSUE THREAD

**Issue by iyakimavetc** [lxc/lxd#3386]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info":
`config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - ip:8443
  - 10.8.0.1:8443
  - 10.0.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate_fingerprint: 04bc0dfcce282506419a26a3e21f5483de6e3dfcb0bb530b38e6191605825759
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-77-generic
  server: lxd
  server_pid: 29767
  server_version: "2.14"
  storage: ""
  storage_version: ""
`

# Issue description

After upgrading lxd I can not do anything with containers.

# Steps to reproduce

 1. Install lxd from ubuntu repos (2.0.9)
 2. Init to use zfs, lauch some containers
 3. Add stable ppa and upgrade lxd to 2.14

# Information to attach (at time of upgrading)
journalctl --unit=lxd
systemd[1]: Stopped LXD - main daemon.
systemd[1]: Stopped LXD - main daemon.
systemd[1]: Starting LXD - main daemon...
lxd[29298]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-06-06T09:09:19+0200
lxd[29298]: lvl=warn msg="Failed to unmount ZFS filesystem via zfs unmount. Trying lazy umount (MNT_DETACH)..." t=2017-06-06T09:09:31+0200
lxd[29298]: lvl=eror msg="Error initializing storage pool \"lxd\": no storage driver was provided. Correct functionality of the storage pool cannot be guaranteed." t=2017
systemd[1]: Started LXD - main daemon.
systemd[1]: Stopping LXD - main daemon...
systemd[1]: Stopped LXD - main daemon.
systemd[1]: Starting LXD - main daemon...
lxd[29767]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-06-06T09:09:32+0200
lxd[29767]: lvl=eror msg="Error initializing storage pool \"lxd\": no storage driver was provided. Correct functionality of the storage pool cannot be guaranteed." t=2017
systemd[1]: Started LXD - main daemon.

 - [ ] container log (lxc info NAME --show-log)
If i try to restart container
            lxc 20170606072449.816 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.
            lxc 20170606074219.954 ERROR    lxc_conf - conf.c:run_buffer:416 - Script exited with status 1.
            lxc 20170606074219.954 ERROR    lxc_start - start.c:lxc_init:450 - Failed to run lxc.hook.pre-start for container "testopen".
            lxc 20170606074219.955 ERROR    lxc_start - start.c:__lxc_start:1314 - Failed to initialize container "testopen".
            lxc 20170606074219.955 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.

 - [ ] main daemon log (/var/log/lxd.log)
if i try lauch container
ephemeral=false lvl=eror msg="Failed to initialize container storage" name=test123 t=2017-06-06T09:22:40+0200

 sqlite3 /var/lib/lxd/lxd.db "SELECT name FROM storage_pools"
lxd

zpool list 
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
lxd    168G  7.19G   161G         -    12%     4%  1.00x  ONLINE  -

**Comment by iyakimavetc** [comment]
sqlite3 /var/lib/lxd/lxd.db

sqlite> select * from storage_pools;
1|lxd||zfs

sqlite> select * from patches;
1|invalid_profile_names|1494763860
2|leftover_profile_config|1494763860
3|network_permissions|1496732959
4|storage_api|1496732971
5|storage_api_v1|1496732971
6|storage_api_dir_cleanup|1496732971
7|storage_api_lvm_keys|1496732971
8|storage_api_keys|1496732971
9|storage_api_update_storage_configs|1496732972
10|storage_api_lxd_on_btrfs|1496732972
11|storage_api_lvm_detect_lv_size|1496732972

**Comment by brauner** [comment]
@iyakimavetc, can you run

    lxc storage show lxd

?

**Comment by iyakimavetc** [comment]
@brauner 
ilya# lxc launch ubuntu: test3
Создание test3
error: no storage driver was provided
ilya# lxc storage show lxd
description: zfs
config:
  size: "19193135104"
  source: /var/lib/lxd/disks/lxd.img
name: lxd
driver: ""
used_by:
- /1.0/containers/test
- /1.0/containers/test1
- /1.0/containers/test2
- /1.0/containers/test3
- /1.0/images/8fa08537ae51c880966626561987153e72d073cbe19dfe5abc062713d929254d
- /1.0/profiles/default

**Comment by stgraber** [comment]
```
sudo sqlite3 /var/lib/lxd/lxd.db 'UPDATE storage_pools SET driver="zfs", description="" WHERE id=1;'
```

This will fix your database.

@brauner is working on fixing the upgrade code to deal with this regression.

**Comment by iyakimavetc** [comment]
Thanks, it works

**Comment by stgraber** [comment]
Perfect, re-opening the issue to track the proper bug fix.
