### ISSUE TITLE
Failed to add device

### ISSUE THREAD

**Issue by hooramin** [lxc/lxd#3403]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:

lxc info
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  storage.zfs_pool_name: MainMachine1
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 148.251.155.201:8443
  - '[2a01:4f8:210:54d8::2]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
   driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-79-generic
  server: lxd
  serverpid: 2475
  serverversion: 2.0.9
  storage: zfs
  storageversion: "5"

# Issue description

after i did apt-get upgrade and reboot , i can't mount any new device ( ftp-mounted folder here) to containers ; also exist devices from past inside containers are permission denied now ...

`lxc config device add host1 uploads disk source=/ftpmount/uploads/ path=/home/uploads/
error: Failed to add mount for device: Error calling 'lxd forkmount 25176 /dev/.lxd-mounts/lxdmount_024123295 /home/uploads': err='exit status 1'`

`shell : /ftpmount/profiles # lxc config device add host1 uploads disk source=/ftpmount/uploads/ path=/home/uploads/
error: Failed to setup device: remove /var/lib/lxd/devices/host1/disk.home-uploads-: device or resource busy`

Really i need some helps now , cuz it happened on a produce server unfortunately

**Comment by stgraber** [comment]
Hi,

Does that still happen after you restart the container?

Can you include the output of:
 - lxc config show --expanded host1
 - ls -lah /var/lib/lxd/devices/host1/
 - cat /proc/self/mountinfo
 - lxc exec host1 -- cat /proc/self/mountinfo
