### ISSUE TITLE
Replace all calls to s.zfsPoolVolumeCreate() with zfsPoolVolumeCreate()

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3404]
Currently, we use the `s.zfsPoolVolumeCreate()` method everywhere but the new `zfsPoolVolumeCreate()` function is (imho) a lot cleaner. It's not a huge deal if we keep using the former but if someone from the community is interested then feel free to send a pr. :)

**Comment by dnegreira** [comment]
Hi, I am currently working on this issue, I hope to be able to test and do a PR soon.

**Comment by dnegreira** [comment]
fixed on https://github.com/lxc/lxd/pull/3468
