### ISSUE TITLE
Headless install, init (with ZFS) and config for lxd

### ISSUE THREAD

**Issue by leowmjw** [lxc/lxd#3407]
Tried to find but was unsuccessful to find steps for the above  :(

All the docs are showing users typing the commands and manually menu selections.  Please provide some pointers on if the whole process can be automated end-to-end (configuration file of some sort?).

I'll be happy to do a PR with updated documentation and examples; but just need pointers to get started.  Thanks!

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/blob/master/doc/preseed.md

**Comment by leowmjw** [comment]
@stgraber Thanks; exactly what I was looking for!
