### ISSUE TITLE
Tag Vlan on Veth to Openvswitch bridge

### ISSUE THREAD

**Issue by bodleytunes** [lxc/lxd#3414]
Hi 

Just wondering if its possible to set a tag on a container's veth port, similar how to you would manually do it with ovs-vsctl and end up with something like this. (basically putting it on a access port on vlan 80)

manual command : ovs-vsctl set port vethB8NH5G tag=80

results in ...

Bridge "lxdbr80"
        Port "vethB8NH5G"
            tag: 80
            Interface "vethB8NH5G"
        Port "patch0"
            trunks: [80]
            Interface "patch0"
                type: patch
                options: {peer="patch1"}
     
        Port "lxdbr80"
            Interface "lxdbr80"
                type: internal

Cheers,

Jon.

**Comment by stgraber** [comment]
This isn't possible right now and isn't something that LXD itself could do until such a feature would be added at the liblxc level. If liblxc grows support for openvswitch configuration of tagged and untagged vlan, then LXD can be updated to make use of it.

**Comment by bodleytunes** [comment]
OK That's fair enough.

In that case, is there a way I can get LXD to keep the veth "ID"/code static, so that would mean I can manually go in and tag the veth on the bridge and then after a reboot, if it stays the same, it shouldn't overwrite it or generate a new one which is what seems to be happening?

Cheers,

Jon

**Comment by stgraber** [comment]
@bodleytunes you can set the host_name property on the nic to have it be set to whatever name you want on the host. The device will however still be recreated every time the container starts as the container going down causes the kernel to destroy the device.

**Comment by 2stacks** [comment]
I was able to solve this using OVS "fake-bridges"
ex.
```bash
sudo ovs-vsctl add-br br0
sudo ovs-vsctl add-port br0 eno1
sudo ovs-vsctl add-br vlan100 br0 100

lxc network attach-profile vlan100 default eth0
```
After that any container you launch in the default profile should be have the access vlan tag of 100.  (This assumes that your upstream switch was tagging vlan 100 down to the physical interface eno1 on your server.)

**Comment by bodleytunes** [comment]
Cheers for the info...

I wanted to tag on the internal ovs bridge so I can have multiple vlans on the same bridge.  I didn't want to bridge but route the containers out as I have a peering from container host server to the switch running ospf w/ FRR routing.

I can see you are bridging to a physical nic and switch, in that case, you will get all vlans by default.  what I have done there is I created a trunk with ovs, tagged specific vlans on the ovs side and also on the physical switch side (cisco 3560g) and then you can create a veth between the lxdbridge and the ovs bridge to pipe specific bridged / tagged networks into your container space directly.  You can also use a child bridge (I think its called?)

Example of what I did:

```
## Bonded interfaces


/// physical interface 1
auto enp2s0f0
iface enp2s0f0 inet manual

/// physical interface 2
auto enp2s0f1
iface enp2s0f1 inet manual

/// lacp bond
allow-bridge0 bond0
iface bond0 inet manual
  ovs_bridge bridge0
  ovs_type OVSBond
  ovs_bonds enp2s0f0 enp2s0f1
  ovs_options bond_mode=balance-tcp lacp=active other-config:lacp-time=slow other_config:lacp-fallback-ab=true tag=1 vlan_mode=native-untagged trunks=1,80,88

^tagging 1,80 and 88 (1 is just used to allow stp to pass)

auto bridge0
allow-ovs bridge0
iface bridge0 inet manual
  ovs_type OVSBridge
  ovs_ports bond0 vlan_88
  up /etc/network/if-up.d/vlans

/// Main upstream / switch facing interface which ospf runs over.

allow-bridge0 vlan_88
iface vlan_88 inet static
  ovs_type OVSIntPort
  ovs_bridge bridge0
  ovs_options vlan_mode=access tag=88
  address 10.10.88.10
  netmask 255.255.255.0
  gateway 10.10.88.1
  up ip route add 10.10.0.0/16 via 10.10.88.1

/// Routed only bridge

auto lxdbr99
allow-ovs lxdbr99
iface lxdbr99 inet static
  ovs_type OVSBridge
  address 10.10.99.1
  netmask 255.255.255.0


/// creating the child bridges on boot with if-up.d script
/// basically the lxd bridge (lxdbr80) will be plumbed into vlan 80 which is tagged on the trunk, any containers on this bridge will have L2 directly out to the physical network on vlan 80

root@server01:/home/jon# cat  /etc/network/if-up.d/vlans

ovs-vsctl add-br lxdbr80 bridge0 80
```

**Comment by bodleytunes** [comment]
Also unfortunatly I have to disable Netplan as Netplan is useless for doing anything with openvswitch at the moment! 👎
