### ISSUE TITLE
Bad behavior when UID from the host is in the range mapped into the container

### ISSUE THREAD

**Issue by matlink** [lxc/lxd#3416]
# Required information

 * Distribution: ubuntu 
 * Distribution version: 16.04 LTS
 * The output of "lxc info" or if that fails:
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFcTCCA1mgAwIBAgIRAM9mMth1VvI3AbEmfe+qsqkwDQYJKoZIhvcNAQELBQAw
    RDEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEkMCIGA1UEAwwbcm9vdEBn
    cmVudGguaW5mby51bmljYWVuLmZyMB4XDTE3MDYxMjEzMTkyMFoXDTI3MDYxMDEz
    MTkyMFowRDEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEkMCIGA1UEAwwb
    cm9vdEBncmVudGguaW5mby51bmljYWVuLmZyMIICIjANBgkqhkiG9w0BAQEFAAOC
    Ag8AMIICCgKCAgEA1sUjCDiVObv1xbzx34I4zw3aZjZnM1PVmjb0EuX5KjLEh1WX
    057BPhIPk4dJDtlB8uiFfUXrE6VQAncAWQTDpgzO0Gg7ZeXJF24bEoywxk4TQYGV
    D6CHGpDwFM1gm4pXwNtygc0TxnFdGbg8y7MUw2ANqWJyFuro3Z04lc4WWFk8jmuR
    D9mRX93I2zlpfq3keM7oclohrZbb6/cNyAZ0eLTgBqYi/BUH0r1wTv7c+2JFYWRa
    9MSTf/u6d4pzxZbm4/9r4jRGYi1YVK4nBQsAG8S6aoTeueFT72ec5UYgPPt7l2LG
    WaICfPefgL+230AklvfsyuNU4Ljd2uKlpMk+C/RKLxvabCOwnqW1/SpQKsWR1UeI
    VTvOmBGE4bnySrVI7joakSJM8nc/oZDWdHm1kX7ojc3e20Vb4Uryf65qdRyuEOy9
    4PlcMkR04bc3SDX3RB+ynP/rG1ZucdoiMnb5AzNICpIRhl3k8jE0onMCXcpwA/QX
    cdiVgu0D3pmgzZuJ0Sid1UcB+0iS9h2tisaPjHCqc+huKatGBXxlfIWBFzlkBWlf
    2H5m8BBfguMH5garQDsWlKdlwuiwuAOy8ndHHFQ3NaRNuJWoCuOsy8+xlnVqnvDD
    NbFd1nMIDZS8AWy1xXnA9Vc3FqrFoEwwj2i+fPqq+/Fn2Aqg4jmzhTrF9mkCAwEA
    AaNeMFwwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1Ud
    EwEB/wQCMAAwJwYDVR0RBCAwHoIWZ3JlbnRoLmluZm8udW5pY2Flbi5mcocECtcL
    7zANBgkqhkiG9w0BAQsFAAOCAgEAkUJqfgMWfmPhupaNh4aE9MGW5ObXc23+6aVR
    61BRZ0ABXSEsoPK27Nk/Dz61lc2LoFPfy2oKJfhdHkSIo/uQejKSNt18LB+soSfl
    pr7hiyr+2+nTUwZwsIST7yYUzMXmQeCRneSLOrMSFdeQu0B6k5nAODZqYpT6fDB0
    2Tyvowl1QBVVyvZ+s79/aqt6d1oMBdLB0vv2kzs7VBbkSGQRugu9v88xKRDYnVkI
    c3VlszCfTOo08JpBWyKTZovvqN/YPQLtyVj7xkU4PYlgv2jeO9AkipRGdZJG9E6i
    qVw1K4I3108kAODKbCOixmd6SJ4Mjn6LB5aUMnmpwaiT1huhZRSJmfOprvp0q5SF
    JNCuv7qv6Nx4iog+89mazkUW/ug7pW65hSM6vG6EL1Co8M7EnFBXqYTfh6RWL1DY
    J3C5aWulPgqDuGd+a3v5u1gWEd0zeUTaVxGGV0e1nPvArXX1AHT9GC0Bb8rLHSNE
    RRGtTHtxHVmLHj+5pNsRHxsYI4yXF7TweWOKzmDoFORhw8QY+OZp4f5ZGiTsPh3r
    dyJc2HIqGRg/CBC1mBAdyI7UqUAc91GEXgVlNZg//em1NFo//FZTZuM6CI0O8DBN
    d2B/m1+SasJhccjN72cISdstd8XCRYHGNYbZmSoWUvzjEn0sKyLCdxGemLg1TVqj
    2NSAGWQ=
    -----END CERTIFICATE-----
  certificate_fingerprint: f2befaf411895f024ef6bf31c159f99a4b4c16e4cd656419924d9c06f0eae775
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-79-generic
  server: lxd
  server_pid: 8188
  server_version: "2.14"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu16

# Issue description

I wanted to use GUI apps in my containers, I followed the great howto
here
https://blog.simos.info/how-to-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop/

However, on my system, it happens that my uid is greater than 65535:

    $ id -u $USER
    119373

When using

    lxc config set guiapps raw.idmap "uid $UID 1000"

in the container, the mapped id is 19737(not 119737), like for .Xauthority :

    $ ls -la /home/ubuntu/.Xauthority
    -rw------- 1 19373 ubuntu 67 Jun 14 07:46 /home/ubuntu/.Xauthority

# Steps to reproduce

 1. create an user with UID larger than 65535 (more than 16 bits)
 2. add this user in lxd group
 3. try to map UID in one container

**Comment by matlink** [comment]
The actual issue is that the UID of the user from the host is in the range mapped to the container:

    $ cat /etc/subuid
    lxd:100000:1000000000
    root:100000:1000000000
    lxd:119373:1
    root:119373:1


    $ cat /etc/subgid
    lxd:100000:1000000000
    root:100000:1000000000
    lxd:2001:1
    root:2001:1

    $ lxc config get test raw.idmap
    uid 119373 1000
    gid 2001 1000

This configuration leads to the bad UID in the host (the truncated one, 19373 instead of 119373).
LXD should either handle this kind of configuration or fail with an explicit error avoiding user to bang his head (which sometimes is good when you listen to a certain kind of music).

**Comment by stgraber** [comment]
Going back and forth on this in my head, not sure what the right option is between:
 - Just don't allow this, return a clear error
 - Allow this mapping and resolve the double mapping issue by creating a hole at uid 19373 in the container (which is what used to be mapped to host uid 119373). Leading to:
   - 0 => 100000
   - 1000 => 119373
   - 19372 => 119372
   - 19373 => -1
   - 19374 => 119374
 - Allow this mapping and resolve the double mapping issue by shifting the whole map by one starting at uid 19373. Leading to:
   - 0 => 100000
   - 1000 => 119373
   - 19372 => 119372
   - 19373 => 119374
   - 19374 => 119375

Those options are in order of ease of implementation and risk. Just erroring out is obviously easy to do and almost risk free. The second option similarly wouldn't require extra uid allocation or costly remapping but would cause a hole in the map, making such a container no longer POSIX compliant and would also fail should anything be owned by 119373 prior to the change. The third option would do exactly what the user expects, would still respect POSIX and wouldn't have any failing corner cases. But if combined with isolated mode, it may require a new allocation of 65537 uids be grabbed as it effectively throws away a uid.

@brauner @hallyn @tych0 thoughts?

**Comment by brauner** [comment]
@stgraber, the last two options all have problem that we need to guess what the user wants. Which is never ideal. However, the third option sounds like the best option.

What about a combined option?
- we shift the whole map iff root and lxd have the same single map entry
- we punch a whole if only one of the two has a single map entry

**Comment by stgraber** [comment]
@brauner I don't think we want to do automatic hole punching based on the subuid/sugid data. Our input is raw.idmap. subuid/subgid are only a safety net the the system can have and shouldn't really be considered an input.

**Comment by brauner** [comment]
Ah, so `raw.idmap` is set. That makes sense. Then as I said I think the best solution is option three.

**Comment by stgraber** [comment]
Yeah, it's just going to be pretty painful to implement without breaking anything :)
Good thing we have pretty good tests around that.

**Comment by brauner** [comment]
Yeah, I'm pretty happy about the good testing there too!

**Comment by matlink** [comment]
Well, it's a quite not frequent situation here. Don't bother if you think nobody will profit of this enhancement

**Comment by stgraber** [comment]
Well, I would have benefited from it yesterday :)
I had to change my default range to avoid that very problem when writing my blog post :)

**Comment by brauner** [comment]
@stgraber, I'm not sure if we're currently doing this (haven't looked at the code) but it would be cool if could isolate the id mapping algorithm into a separate package in LXD. Would make it more modular and also easier testable. In my mind, this piece of code has quite some fundamental security impact. But as I said, I might've missed you already making this a package.

**Comment by stgraber** [comment]
@brauner could probably be better split. The idmap range handling, kernel parsing, subuid/subgid parsing, ... is all in shared/idmap. The isolation handling (cutting new sub-maps) is handled in lxd/

**Comment by stgraber** [comment]
Giving this one to you @brauner.
