### ISSUE TITLE
"bad data in /proc/uptime" error messages

### ISSUE THREAD

**Issue by saaby** [lxc/lxd#3423]
Hi,

After the latest lxd update, when inside a container, using "top", I get repeated messages on the console reading "bad data in /proc/uptime", and pid cpu% is reported in rounded hundreds "100%, 200%, 300%, 400%". lxcfs issue?

 * Ubuntu 16.04, both on host and container. lxd version 2.14 on both host and container.

lxc info output:
# lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: 
<SNIP>
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.8.0-54-generic
  server: lxd
  server_pid: 1301
  server_version: "2.14"
  storage: btrfs | dir
  storage_version: 4.4 | 1

**Comment by stgraber** [comment]
Hi,

Yeah, /proc/uptime is a lxcfs file, could you file an issue at https://github.com/lxc/lxcfs/issues and include the version of lxcfs you're running?

Thanks

**Comment by saaby** [comment]
Hi,

tomponline beat me to it: https://github.com/lxc/lxcfs/issues/191

As far as I can see it has already been fixed in master. Will patiently wait for 2.0.8. Thanks!
