### ISSUE TITLE
Make lxd shutdown timeout configuable

### ISSUE THREAD

**Issue by jkroepke** [lxc/lxd#3434]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.8
   * LXC version: 2.0.8
   * LXD version: 2.14
   * Storage backend in use: btrfs

# Issue description

It should be awesome, if the lxd shutdown timeout would be configuable via server configuration.
https://github.com/lxc/lxd/blob/8c2d5c5768a25b445abc89720954e2a5e17b75ad/lxd/main_shutdown.go#L14

Currently its possible to set a custom timeout via parameter. But on host shutdown, the systemd service lxd-containers.service calls lxd shutdown without any timeout options. The reason are that containers will be kill hard on the shutdown sequence.

**Comment by stgraber** [comment]
Isn't that exactly what "boot.host_shutdown_timeout" is for?

**Comment by stgraber** [comment]
(it's a per-container configuration key, you can set it in a profile if you want to apply the same value to a bunch of containers)

**Comment by jkroepke** [comment]
Yeah, I know. It's well documented.

```
root@mars ~ # lxc profile show default | grep boot
  boot.host_shutdown_timeout: "300"
```

But it doesn't help well on a host reboot. 

On a reboot systemd stop the service lxd-containers.servicer which running lxd shutdown.

After 60 seconds the command lxd shutdown will be return a message something like `LXD still running after 60s timeout.` From systemd side the service lxd-containers has been stopped and reboot the host completely. And thats the problem. In some cases some services are not gracefully stopped. 

I hope you understand me.

**Comment by stgraber** [comment]
So given how shutdown works, I "think" it should be safe to just not have any timeout by default for "lxd shutdown", which would then have it wait until LXD is actually done. Ultimately systemd will still have its own timeout that may mess with things, but that's outside of our control as far as LXD itself is concerned.

**Comment by jkroepke** [comment]
>  but that's outside of our control as far as LXD itself is concerned.
And can be simply configured. 
https://www.freedesktop.org/software/systemd/man/systemd.service.html#TimeoutStopSec=

In Ubuntu its by default 90s. Maybe you should be notice somewhere in the documentation.
