### ISSUE TITLE
Issue with ZFS unmounts when LXD is inside a mount namespace (snap)

### ISSUE THREAD

**Issue by renky** [lxc/lxd#3437]
After several tests with the debian strech testing in the last weeks i have now switched over to newest debian stable (complete reinstall). Installed zfs-dkms and lxd (snap).
Difference to my older tests: instead of lxdbr0 I'm using br0 now (set up directly in the host, to reach all vms directly from network) -> that all works fine!! after my last issue (zfs-mountpoint of dataset had to be set to none) also lxc-container setup works well.

Another difference: when I run lxd init, i selected a different name for the storage pool - I didn't select default, I selected a own name. 

And now I get errors when I restart/reboot a container or stop and start it via lxc command. I can init a new container, set it up, start it, work with it, but after stopping it, it doesn't come up again - gives me the following errors. I didn't get this errors on my testing system where I used the name "default" for the storage pool and the lxdbr0...

```
# lxc start c000331975
error: Failed to run: /snap/lxd/2518/bin/lxd forkstart c000331975 /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/c000331975/lxc.conf:
Try `lxc info --show-log c000331975` for more info
```

```
# lxc info --show-log c000331975
Name: c000331975
Remote: unix:/var/snap/lxd/common/lxd/unix.socket
Architecture: x86_64
Created: 2017/06/23 09:19 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20170623094709.412 ERROR    lxc_conf - conf.c:mount_rootfs:798 - No such file or directory - Failed to get real path for "/var/snap/lxd/common/lxd/containers/c000331975/rootfs".
            lxc 20170623094709.412 ERROR    lxc_conf - conf.c:setup_rootfs:1220 - Failed to mount rootfs "/var/snap/lxd/common/lxd/containers/c000331975/rootfs" onto "/var/snap/lxd/common/lxc/" with options "(null)".
            lxc 20170623094709.412 ERROR    lxc_conf - conf.c:do_rootfs_setup:3899 - failed to setup rootfs for 'c000331975'
            lxc 20170623094709.412 ERROR    lxc_conf - conf.c:lxc_setup:3981 - Error setting up rootfs mount after spawn
            lxc 20170623094709.413 ERROR    lxc_start - start.c:do_start:811 - Failed to setup container "c000331975".
            lxc 20170623094709.413 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20170623094709.140 ERROR    lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "c000331975".
            lxc 20170623094709.703 ERROR    lxc_conf - conf.c:run_buffer:416 - Script exited with status 1.
            lxc 20170623094709.703 ERROR    lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "c000331975".
            lxc 20170623094709.703 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.
            lxc 20170623094709.703 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.

```

but If I search for the directory I get the following:

```
# ls -l /var/snap/lxd/common/lxd/containers/c000331975
lrwxrwxrwx 1 root root 67 Jun 23 11:20 /var/snap/lxd/common/lxd/containers/c000331975 -> /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/c000331975
# ls -l /var/snap/lxd/common/lxd/containers/c000331975/
total 8
-r--------  1 root    root    2094 Jun 23 11:42 backup.yaml
-rw-r--r--  1 root    root     691 Jan  1  1970 metadata.yaml
drwxr-xr-x 22 1000000 1000000   22 May  4 05:25 rootfs
drwxr-xr-x  2 root    root       4 Jun 22 14:49 templates
```
so it should be there, shouldn't it?

after that i also cannot delete this conatiner:
```
 # lxc delete c000331975
error: Failed to destroy ZFS filesystem: cannot destroy 'zpool1/lxd/containers/c000331975': dataset is busy
```
But If I do the following:
```
# zfs unmount zpool1/lxd/containers/c000331975
```
then everything works again -> after that i can start the container again.

Maybe lxd doesn't unmount correctly, if the storagepool-name was changed?

 * Distribution: Debian Strech, fresh install
 * The output of "lxc info" or if that fails:
root@alarich ~ # lxc info
config:
  core.https_address: '[::]:8443'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 94.130.8.20:8443
  - '[2a01:4f8:10b:c58::2]:8443'
  - 94.130.8.20:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFjTCCA3WgAwIBAgIQIioZM/371/VPfLX2P2QCODANBgkqhkiG9w0BAQsFADA/
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMR8wHQYDVQQDDBZyb290QGFs
    YXJpY2gucHdob3N0LmRlMB4XDTE3MDYyMjExMzE1OVoXDTI3MDYyMDExMzE1OVow
    PzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEfMB0GA1UEAwwWcm9vdEBh
    bGFyaWNoLnB3aG9zdC5kZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AMNd4aHhrntfa4Af0FeUlfVt2oeshvu3our8EnUcPX4qcGsV7mIPZUtfdixHUCrt
    MDYxwH9qIUtI5Hx9ii6rim3xTSvSvJ/s9QmbDMKfKGc9robBdHcpKemQS/atjBV4
    BCywIh8q0xrzjstzXCixmyqq06RhGrJ9ot3O5OMFVT0JsOQmqA9TVcwMxi2lK3XE
    Ekxwyt3N6oWsEgRKlMZJtfL7My+wDmUcOeMSjNcfGx/0pSwF8Ul4BNyx6rVxiqm8
    IgkxRLy1ZVyPa1s3dP81e75EFYCqkwPUWvZJGca6g3DqZ57VfuqkBbQMpH1LD1v+
    KrvIGWXWkVK9Vy0vkn1c5htP4fCeE2dq7H2X4oxcZneDdxEhdBVWej2C/P6RJdg9
    MIzTw/xQ6cQZl1CZ6IhtnEJCirHEXqyMugQxwFPyvtH5COzHwCPNtTFDMbUtMgyY
    KD5TekHq0B2li+0Rm4cdlPZzJdi7gys47IBDGBsTzDLjqFWs3Kh8PrtK5dz20EKG
    U3rsgHKxGiRA0ZhO4l/1ta0eDNaFz45xuJ8VJNz5F+XhEzTu/79GYj/qw9o6zefD
    Yad2lIIX4D5v2vZp7fQnU+2Zpm5x9Y27uwKaQvhrZ1bNP2ok4QupYe0brsbNmQbF
    w9I0OKj092JI/RwyEpvYGnPIOQ4MZtHfR6d/re9EBiWXAgMBAAGjgYQwgYEwDgYD
    VR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAw
    TAYDVR0RBEUwQ4IRYWxhcmljaC5wd2hvc3QuZGWHBF6CCBSHBF6CB5CHBF6CB5GH
    BF6CB5KHBF6CB5OHECoBBPgBCwxYAAAAAAAAAAIwDQYJKoZIhvcNAQELBQADggIB
    AAduN9y8YklpLLMuAF1E2/GErNGYmIwTTnAqTjkSnHpx5idrC1EZOrBjFKvRHd5W
    i3u/8Z8Z95fdzjSzqASmAy14WD4FJzXIyM1a2sbzegRSDn/x/68i/xRqIfSA5dJC
    Y49dJsiurCOrGO+gqBY7MT+TQw2acnADGQ0uaRtt4riFQQPWlPwNBbZzLHbwx1Xf
    47pI6T7yPmZ3ZBLkL6FPHN9ODh23m4rs6AhZ26vG6fyo+FRTNLDqc0FRgjbLzHaz
    5fjoEAp9dqwvp7mpMdaZAoQHkNmlNqxdMsHmIOCosvR5QloihE8mi23z+5p+N9bv
    SZhIVWPuykQ1h3gz+qE9/6yBTr3teqa64Zzwe1pPDn9k05jRoMqLPKr/g/4oGF5e
    PegAUdZUHIA2QBuv4bvKR8jliRGUpu91DxwKuueff2yCPF62Ee5GCVitrNXAxIOL
    kA3mMQJHzKYxuuWOw9da7WWq2uMedDe1Kf4FJdn6yfQpgDDbyz3cImpiTeXP+O3S
    N1RmL9UbcCTS2kcTYvcyQK4KuQWJc/47Arpw5wiDFpl+j3/0LwLlD1N7ReZpiUXW
    XW3hIqaBsS2221CrC2DmIeHZXmh++tDfimAu5I4TjJjEAvrHhWRzA4Jr8UdYHSSt
    o85kw5XyzmQY1oaaSbCUgkB8+dAK8DsiurGy8RcPU52g
    -----END CERTIFICATE-----
  certificate_fingerprint: f495c2c18106300c031b0f6bceb5d694cb23d0b8b410be017020e11aa3ad71af
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.0-3-amd64
  server: lxd
  server_pid: 2716
  server_version: "2.14"
  storage: zfs
  storage_version: 0.6.5.9-5

**Comment by stgraber** [comment]
Smells to me like a case of zfs being confused by mount namespaces...

Next time this happens, can you post:
 - cat /proc/self/mountinfo
 - cat /proc/$(pidof lxd)/mountinfo
 - ls -lh /var/snap/lxd/common/lxd/containers/c000331975/
 - ls -lh /proc/$(pidof lxd)/root/var/snap/lxd/common/lxd/containers/c000331975/

**Comment by stgraber** [comment]
that should let you compare what the snap sees with what's on the host.

**Comment by AceSlash** [comment]
I have the same issue with a container named "pasiphae", I did your commands so here is the result:
```
# cat /proc/self/mountinfo|grep pasiphae
111 80 0:45 / /var/snap/lxd/common/lxd/storage-pools/default/containers/pasiphae rw,noatime shared:47 - zfs tank/lxd/containers/pasiphae rw,xattr,noacl
# cat /proc/$(pidof lxd)/mountinfo|grep pasiphae
# ls -lh /var/snap/lxd/common/lxd/containers/pasiphae
lrwxrwxrwx 1 root root 66 Jun 12 18:45 /var/snap/lxd/common/lxd/containers/pasiphae -> /var/snap/lxd/common/lxd/storage-pools/default/containers/pasiphae
# ls -lh /proc/$(pidof lxd)/root/var/snap/lxd/common/lxd/containers/pasiphae
lrwxrwxrwx 1 root root 66 Jun 12 18:45 /proc/32735/root/var/snap/lxd/common/lxd/containers/pasiphae -> /var/snap/lxd/common/lxd/storage-pools/default/containers/pasiphae
```
You'll notice that there are no result to the command `cat /proc/$(pidof lxd)/mountinfo|grep pasiphae`.

Also additional info about my env:
```
# lxc info
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.11.5-200.fc25.x86_64
  server: lxd
  server_pid: 32735
  server_version: "2.14"
  storage: zfs
  storage_version: 0.7.0-rc4
# snap list
Name  Version  Rev   Developer  Notes
core  16-2     1689  canonical  -
lxd   2.14     2518  canonical  -
```

And of course the original error:
```
            lxc 20170627103832.584 ERROR    lxc_conf - conf.c:mount_rootfs:798 - No such file or directory - Failed to get real path for "/var/snap/lxd/common/lxd/containers/pasiphae/rootfs".
            lxc 20170627103832.584 ERROR    lxc_conf - conf.c:setup_rootfs:1220 - Failed to mount rootfs "/var/snap/lxd/common/lxd/containers/pasiphae/rootfs" onto "/var/snap/lxd/common/lxc/" with options "(null)".
            lxc 20170627103832.584 ERROR    lxc_conf - conf.c:do_rootfs_setup:3899 - failed to setup rootfs for 'pasiphae'
            lxc 20170627103832.584 ERROR    lxc_conf - conf.c:lxc_setup:3981 - Error setting up rootfs mount after spawn
            lxc 20170627103832.584 ERROR    lxc_start - start.c:do_start:811 - Failed to setup container "pasiphae".
            lxc 20170627103832.584 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20170627103832.615 ERROR    lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "pasiphae".
            lxc 20170627103833.185 ERROR    lxc_conf - conf.c:run_buffer:416 - Script exited with status 1.
            lxc 20170627103833.185 ERROR    lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "pasiphae".
            lxc 20170627103833.185 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.
            lxc 20170627103833.185 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.
```

**Comment by AceSlash** [comment]
Rebooted the host and reran all commands:
```
# cat /proc/self/mountinfo|grep pasiphae
111 78 0:45 / /var/snap/lxd/common/lxd/storage-pools/default/containers/pasiphae rw,noatime shared:47 - zfs tank/lxd/containers/pasiphae rw,xattr,noacl
# cat /proc/$(pidof lxd)/mountinfo|grep pasiphae
333 325 0:45 / /var/lib/snapd/hostfs/var/snap/lxd/common/lxd/storage-pools/default/containers/pasiphae rw,noatime master:47 - zfs tank/lxd/containers/pasiphae rw,xattr,noacl
378 377 0:45 / /var/snap/lxd/common/lxd/storage-pools/default/containers/pasiphae rw,noatime master:47 - zfs tank/lxd/containers/pasiphae rw,xattr,noacl
# ls -lh /var/snap/lxd/common/lxd/containers/pasiphae
lrwxrwxrwx 1 root root 66 Jun 12 18:45 /var/snap/lxd/common/lxd/containers/pasiphae -> /var/snap/lxd/common/lxd/storage-pools/default/containers/pasiphae
ls -lh /proc/$(pidof lxd)/root/var/snap/lxd/common/lxd/containers/pasiphae
lrwxrwxrwx 1 root root 66 Jun 12 18:45 /proc/11813/root/var/snap/lxd/common/lxd/containers/pasiphae -> /var/snap/lxd/common/lxd/storage-pools/default/containers/pasiphae
```
If I try to reboot any container, the issue arise immediately.

In the meantime, do you have any way to get back the correct mount points so we can use a container after its restart? Currently I don't see any solution beside rebooting the host...

**Comment by renky** [comment]
For me the zfs unmount of the containers dataset worked to get it running again...

Am 27. Juni 2017 14:38:23 MESZ schrieb AceSlash <notifications@github.com>:

**Comment by stgraber** [comment]
@AceSlash are you also on Debian?

**Comment by stgraber** [comment]
Ok, so I've been doing a bit of testing on Ubuntu and have so far been unable to reproduce the problem.

My test is:

    snap install lxd --edge   # The channel shouldn't matter but I want to be able to compare to git
    lxd init  # Using all defaults, so ZFS backend using a loop
    lxc launch images:alpine/edge c1
    lxc restart c1
    lxc restart c1 --force
    lxc stop c1
    lxc start c1
    lxc restart c1

All of the above succeeded for me. Could you try the same and see if that fails for you?

I think the following would also be useful:
 - uname -a
 - lsb_release -a
 - cat /proc/cmdline
 - snap list
 - dpkg -l | grep zfs
 - dpkg -l | grep snap
 - cat /sys/module/zfs/version

That should make it easier for me to compare my environment with yours.
As I mentioned I did my testing on current Ubuntu but will repeat the test using our Debian Stretch test VM tomorrow to see if I can get it to misbehave there, then will try to see what the source of the problem may be.

**Comment by AceSlash** [comment]
@stgraber : I had the issue on Fedora 25 (selinux disabled if it matters). I'm gonna update it and retry to see if something changed.

**Comment by AceSlash** [comment]
uname -a
```
Linux lpt-001 4.11.8-200.fc25.x86_64 #1 SMP Thu Jun 29 16:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
lsb_release -a
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 25 (Twenty Five)
Release:        25
Codename:       TwentyFive
```
cat /proc/cmdline
```
BOOT_IMAGE=/vmlinuz-4.11.8-200.fc25.x86_64 root=/dev/mapper/fed-root ro rd.lvm.lv=fed/root rd.luks.uuid=luks-620869b5-88c3-42d7-b7bb-b850d0b6a14d rhgb quiet rd.driver.blacklist=nouveau LANG=en_US.UTF-8
```
snap list
```
Name  Version  Rev   Developer  Notes
core  16-2     2312  canonical  -
lxd   2.15     2720  canonical  -
```
rpm -qa|grep zf (I'm using the testing version from the ZoL project)
```
zfs-0.7.0-rc4.fc25.x86_64
libzfs2-0.7.0-rc4.fc25.x86_64
zfs-release-1-5.fc25.noarch
zfs-dkms-0.7.0-rc4.fc25.noarch
```
rpm -qa|grep snap
```
snap-confine-2.26.3-3.fc25.x86_64
snapd-selinux-2.26.3-3.fc25.noarch
snappy-1.1.3-2.fc24.x86_64
snapd-2.26.3-3.fc25.x86_64
```
cat /sys/module/zfs/version
```
0.7.0-rc4
```
With a new container, I see no error now:
``
lxc launch images:alpine/edge c1
lxc restart c1
lxc restart c1 --force
lxc stop c1
lxc start c1
lxc restart c1
```
Trying with an existing container still fails:
```
# lxc restart pasiphae
error: Failed to run: /var/lib/snapd/snap/lxd/2720/bin/lxd forkstart pasiphae /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/pasiphae/lxc.conf: 
Try `lxc info --show-log pasiphae` for more info
```

From this, I guess there is something lingering somewhere that relate to old containers that were created on a previous lxd snap version.

**Comment by renky** [comment]
Hi there

Maybe, I only used 2.14 for my tests, but no older versions...

Regards


Am 7. Juli 2017 12:54:23 MESZ schrieb AceSlash <notifications@github.com>:

**Comment by AceSlash** [comment]
After my tests, I tried to delete the containers I just created and...
```
# lxc delete c1
error: Failed to destroy ZFS filesystem: cannot destroy 'tank/lxd/containers/c1': dataset is busy
# lxc delete social-skunk --force
error: Failed to destroy ZFS filesystem: cannot destroy 'tank/lxd/containers/social-skunk': dataset is busy
```
But zfs destroy works, and I then can delete the container:
```
zfs destroy tank/lxd/containers/social-skunk
lxc delete social-skunk --force
```
Recap in 3 lines:
```
# lxc delete c1
error: Failed to destroy ZFS filesystem: cannot destroy 'tank/lxd/containers/c1': dataset is busy
# zfs destroy tank/lxd/containers/c1
# lxc delete c1
```
Can you try on Ubuntu if you see the same issue? Do you want a new ticket for this specific issue?

**Comment by stgraber** [comment]
Thanks for the feedback, I'll do some tests on our Fedora and Debian test runners.
Still feels like ZFS getting very confused by mount namespaces but hopefully there's something we can do about it ourselves other than wait for ZFS upstream to look at our bug reports.

**Comment by stgraber** [comment]
Yeah, I can't reproduce the deletion issue on Ubuntu either. Getting zfs on our fedora vm now.

**Comment by stgraber** [comment]
```
[root@snap-fedora-25 ~]# lxd init
Do you want to configure a new storage pool (yes/no) [default=yes]? 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (dir, btrfs, zfs) [default=zfs]: 
Create a new ZFS pool (yes/no) [default=yes]? 
Would you like to use an existing block device (yes/no) [default=no]? 
Size in GB of the new loop device (1GB minimum) [default=15GB]: 
Would you like LXD to be available over the network (yes/no) [default=no]? 
Would you like stale cached images to be updated automatically (yes/no) [default=yes]? 
Would you like to create a new network bridge (yes/no) [default=yes]? 
What should the new bridge be called [default=lxdbr0]? 
What IPv4 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]? 
What IPv6 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]? 
LXD has been successfully configured.
[root@snap-fedora-25 ~]# lxc launch images:alpine/edge c1
Creating c1
Starting c1                                 
[root@snap-fedora-25 ~]# lxc restart c1
[root@snap-fedora-25 ~]# lxc restart c1 --force
[root@snap-fedora-25 ~]# lxc delete c1 --force
```

**Comment by stgraber** [comment]
Going to try rebooting, see what happens if the host can see those zfs filesystems at boot time.

**Comment by stgraber** [comment]
Nope, even after reboot, I can delete any of the containers I created prior to reboot and restart them too...

**Comment by stgraber** [comment]
So in your case you were using a pre-existing zpool with LXD taking a dataset from it, I wonder if that may cause the difference. I'll set that up next.

**Comment by stgraber** [comment]
Ok, so I managed to create a bit of a mess with ZFS on fedora when importing a pool after LXD is started and have it trigger the zfs automount. I'm now testing to see if we could get away with setting canmount=noauto for the LXD datasets.

**Comment by stgraber** [comment]
Right, setting canmount=noauto on the container datasets seems to be helping here.

**Comment by stgraber** [comment]
so I closed this issue with the canmount=noauto pull request. I "think" that was the source of most of the issues with snapd but I guess we'll need to wait until 2.16 to really know if that did the trick for all affected.

**Comment by AceSlash** [comment]
Thank you @stgraber , is there an easy way to get 2.16 before release using a beta channel on snapd or something similar? If so I'll have time to test it tomorrow.

**Comment by stgraber** [comment]
You can use the edge channel, that will get you a new build every time something changes in upstream git. Note that this may be pretty risky at times, so don't run that in production :)
