### ISSUE TITLE
Backup LXD container

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#3443]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Xenial
 * Distribution version:
 * The output of "lxc info" or if that fails:
 
```driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-53-generic
  server: lxd
  serverpid: 31936
  serverversion: 2.0.9
  storage: btrfs
  storageversion: "4.4"
```
   * Storage backend in use:
btrfs
# Issue description

I have two identical LXD servers running (production and stage/backup). What is the proper way to backup the production containers with minimal downtime? Any hints suggestions are appreciated. Thank you

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/blob/master/doc/backup.md
