### ISSUE TITLE
Allow specifying the start of an isolated range (security.isolated.start)

### ISSUE THREAD

**Issue by jfgibbins** [lxc/lxd#3451]
Last time I worked on this issue, was over a year ago, when the documentation wasn't quite as friendly.  Nice job guys on improving it.  It's allowing us to use all those great features you've added.  But one issue I could never get to work nicely, was initial creation of container with different ids.  My first go around, I would use a script, to sed the subuid/gid file to a new initial value, restart lxd service, launch my container with a matching lxc.id_map, sed the values back, restart lxd service again, and move on to the next container.  Works fine for one container at a time, but does not scale well and certainly doesn't work in parallel.  Since then, you have come out with security.isolated and a few other things, but for my use case, I use variations of the following simplified:
  raw.lxc: |
    lxc.id_map =
    lxc.id_map = u 0 100000 200
    lxc.id_map = g 0 100000 200
    lxc.id_map = u 200 200 1800
    lxc.id_map = g 200 200 1800
    lxc.id_map = u 2000 102000 63536
    lxc.id_map = g 2000 102000 63536
With the script, I can vary the first values:
containerX u  100000 200
containerY u 100200 200
containerZ u 100400 200

the idea, being that the first 200 uid, are typically id part of the base image, I create a uid/gid on the host named after the container/service, and can more easily view what is doing what.  While the isolated map provides security, from container to container, it's not predictable for creating the host user/group.  Would it be possible, to expose more of that LXC functionality to allow this type of use case in LXD.  FYI, I've tried a few work arounds, above mentioned script, uidmapshift, etc, but none really work when deploying a whole environment with IAC, aka terraform, etc.  Hopefully, I just didn't miss something obvious that already allows it.  BTW, https://github.com/sl1pm4t/terraform-provider-lxd has done a great job so far of making a provider for terraform to work with your lxd, in case you hadn't seen it yet.

**Comment by stgraber** [comment]
If all you want is LXD to map 1800 uids/gids starting at uid/gid 200, you can do so with:

```
raw.idmap: |-
    both 200-2000 200-2000

Which will setup the kind of hole you're describing above. You may want to read:
 - https://stgraber.org/2017/06/15/custom-user-mappings-in-lxd-containers/
 - https://github.com/lxc/lxd/blob/master/doc/userns-idmap.md

**Comment by jfgibbins** [comment]
Actually quite the opposite.  Creating the holes works no problem.  The above is a bit simplified for the map, but I map all kinds of UIDs between host and guest.  What I want, is when the container is created, for the UIDs, mainly 0-200 in the container, to be created starting with a different definable value, rather than just the number that is listed first under /etc/subuid.  As you know, the container is created with the value as follows:
root:100000:65536
root:200:4000000
 
Two ways I have found so far, are to edit subuid, restart service, create container, change subuid back, restart service, and repeat for each container with a different starting value or, init container, run uidmapshift, start container, repeat
Neither way is compatible with large environments or parallel creation

ie,
container x
lxc.id_map = u 0 100000 200
lxc.id_map = g 0 100000 200
lxc.id_map = u 200 200 1800
lxc.id_map = g 200 200 1800

container y
lxc.id_map = u 0 100200 200
lxc.id_map = g 0 100200 200
lxc.id_map = u 200 200 1800
lxc.id_map = g 200 200 1800

container z
lxc.id_map = u 0 100400 200
lxc.id_map = g 0 100400 200
lxc.id_map = u 200 200 1800
lxc.id_map = g 200 200 1800

**Comment by stgraber** [comment]
Ok, so the above shows you mapping only up to uid/gid 2000, this makes the container POSIX incompatible and the lack of uid/gid 65534 may be a problem.

Anyway, to do what you're doing above but through LXD, you'd set:
```
security.idmap.isolated: true
security.idmap.size: 200
raw.idmap: |-
  both 200-2000 200-2000
```

**Comment by stgraber** [comment]
```
root@vm02:~# lxc launch images:alpine/edge c1 -c security.idmap.isolated=true -c security.idmap.size=200 -c raw.idmap="both 200-1999 200-1999"
Creating c1
Starting c1
root@vm02:~# lxc launch images:alpine/edge c2 -c security.idmap.isolated=true -c security.idmap.size=200 -c raw.idmap="both 200-1999 200-1999"
Creating c2
Starting c2
root@vm02:~# lxc launch images:alpine/edge c3 -c security.idmap.isolated=true -c security.idmap.size=200 -c raw.idmap="both 200-1999 200-1999"
Creating c3
Starting c3

root@vm02:~# grep id_map /var/log/lxd/c1/lxc.conf 
lxc.id_map = u 0 1065536 200
lxc.id_map = g 0 1065536 200
lxc.id_map = u 200 200 1800
lxc.id_map = g 200 200 1800
root@vm02:~# grep id_map /var/log/lxd/c2/lxc.conf 
lxc.id_map = u 0 1065736 200
lxc.id_map = g 0 1065736 200
lxc.id_map = u 200 200 1800
lxc.id_map = g 200 200 1800
root@vm02:~# grep id_map /var/log/lxd/c3/lxc.conf 
lxc.id_map = u 0 1065936 200
lxc.id_map = g 0 1065936 200
lxc.id_map = u 200 200 1800
lxc.id_map = g 200 200 1800
root@vm02:~# 
```

**Comment by jfgibbins** [comment]
I am mapping a whole range of 65536, as shown in the first post, so staying posix compatible.  I'm wanting the feature of isolated, but I want to statically pick the unique values are for each container, rather than just getting the next allocation.  I will probably switch to idmap, as the id_map is a hold over from before idmap existed.

**Comment by jfgibbins** [comment]
FYI, the reason, as you may have seen in the first post, is I create users "container1-root:100000:100000" "container2:100200:100200" etc to match so that I get container and service names showing on the host and can see exactly which container, service, uid, etc is doing without having to track it down.  Hope that makes more sense.

**Comment by stgraber** [comment]
Ah right, so yeah, someone who wants to do the same you do but without the need to pick the specific range, could use security.idmap.size=65536 and the rest of what I showed above.

In your case, it sounds like you're indeed stuck with manually setting up the maps.
That or you could have LXD do it for you, then extract the map from "lxc config get c1 volatile.idmap.base" and update subuid/subgid to match.

Closing this issue as it seems like we're offering the right options for this right now.

**Comment by jfgibbins** [comment]
Not sure how LXD would do it for me.  If I do a lxc init with isolated, it'll pick the next range, and I can pull the config to see what it used, but if I recreate the same container, it'll most likely pick a different range the next time.  Would a security.idmap.start be possible, so that we could set where we want the range to begin in addition to how many ids we want?

**Comment by stgraber** [comment]
It should be possible, yes. Obviously that'd let you stamp over an existing container as that'd bypass the code that checks for non-overlapping ranges.

**Comment by jfgibbins** [comment]
I'm cool with that.  Thanks.
