### ISSUE TITLE
volume group is not empty

### ISSUE THREAD

**Issue by nnovikov** [lxc/lxd#3456]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2 LTS
 * The output of "lxc info" or if that fails:
% lxc info
config:
  core.https_address: '[::]'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.10.55.23:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
<skip />
    -----END CERTIFICATE-----
  certificate_fingerprint: ...
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-81-generic
  server: lxd
  server_pid: 8028
  server_version: "2.14"
  storage: ""
  storage_version: ""

   * Storage backend in use: lvm

After upgrade to 2.14 version, lxd can't create storage pool on lvm:
```
/usr/bin/lxc storage create lxdpool lvm source=vg0
error: volume group "vg0" is not empty
```
Is there any way to make this possible?

**Comment by brauner** [comment]
Can you show `vgdisplay vg0`?

**Comment by nnovikov** [comment]
```
% sudo vgdisplay vg0
  --- Volume group ---
  VG Name               vg0
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  11
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                5
  Open LV               5
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               892,29 GiB
  PE Size               4,00 MiB
  Total PE              228427
  Alloc PE / Size       2196 / 8,58 GiB
  Free  PE / Size       226231 / 883,71 GiB
  VG UUID               Vj1nXQ-y5A0-22Z1-3aPl-CdLc-SjAL-zEHdxX
```
```
% sudo lvs
  LV     VG   Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  home   vg0  -wi-ao---- 976,00m                                                    
  root   vg0  -wi-ao---- 976,00m                                                    
  swap_1 vg0  -wi-ao---- 976,00m                                                    
  usr    vg0  -wi-ao----   1,91g                                                    
  var    vg0  -wi-ao----   3,81g      
```

**Comment by brauner** [comment]
Yeah, so `LXD` will not use any volume groups that have existing logical volumes in them. This is a safety measure. `LXD` will assume it has full control over the pool and it might tear it down when you delete the pool via `LXD`. If you want to use an existing VG you need to give `LXD` an empty one. This should also be documented in the storage documentation in this repo.

**Comment by nnovikov** [comment]
It's bad. Why you don't want use full control of thinpool instead of volume group? For creating new volume group I need additional physical volume. It's very hard to add on already configured server.

**Comment by brauner** [comment]
If you have a volume group that only has a thinpool in it then you can pass the name of the volume group and the name of the thinpool to `LXD` and it will use it. It will however, still refuse it if there's any other logical volume besides the thinpool in the volume group.

**Comment by ice-8** [comment]
I'm agree with nnovikov, I'd like to provide a thinpool to lxd, even in group with other logical volumes, but not the whole volume group.

**Comment by nnovikov** [comment]
This makes lvm backend useless for me. This is very sad.

**Comment by brauner** [comment]
So your exact use-case is an already existing volume group with a pre-existing thinpool and some other logical volumes?

**Comment by brauner** [comment]
I sent a PR that allows you to use an already existing non-empty volume groups iff the requested thinpool does already exist. If it does not exist we'd need to start guessing sizes which is not something we want to do.

**Comment by nnovikov** [comment]
Yes, pre-existing thinpool is a good solution. Guessing sizes is not required. I think in this case you must stop creating storage with error message..

**Comment by sehari24jam** [comment]
What are related lxc command to use existing vg?
LV thinpool has been pre-created.
I try to do with these command, but it fail with confusing message:

```
sudo lvcreate -v -L 200G --thinpool lxdlvm xcont2-vg
sudo lvs
  LV     VG        Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lxdlvm xcont2-vg twi-a-tz-- 200.00g             0.00   0.23                            
  root   xcont2-vg -wi-ao---- 433.70g                                                    
  swap_1 xcont2-vg -wi-ao----  31.96g                                                    
  zfslxd xcont2-vg -wi-ao---- 200.00g

lxc storage create pool2 lvm lvm.thinpool_name=lxdlvm lvm.vg_name=xcont2-vg
error: LXD already uses volume group "xcont2-vg" for pool "pool2"
```

**Comment by stgraber** [comment]
@brauner that error looks a bit confusing? :)

@sehari24jam what does "lxc storage list" show you right now?

**Comment by brauner** [comment]
It looks like the storage driver thinks that LXD already used this volume group so yeah, I'd need to see the output of lxc storage list.

**Comment by sehari24jam** [comment]
Late reply. Here the related output.
```
sudo lvcreate -v -L 200G --thinpool lvmlxd ubuntu-05-vg

sudo lvs
  LV     VG           Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lvmlxd ubuntu-05-vg twi-a-tz-- 200.00g             0.00   0.23                            
  root   ubuntu-05-vg -wi-ao---- 100.00g                                                    
  swap_1 ubuntu-05-vg -wi-ao---- 255.87g                                                    
  zfslxd ubuntu-05-vg -wi-ao---- 200.00g

lxc storage list
+-------+-------------+--------+--------+---------+
| NAME  | DESCRIPTION | DRIVER | SOURCE | USED BY |
+-------+-------------+--------+--------+---------+
| pool1 |             | zfs    | pool1  | 13      |
+-------+-------------+--------+--------+---------+
```

**Comment by brauner** [comment]
@monstermunchkin is looking into this. Can't assign him somehow.

**Comment by monstermunchkin** [comment]
What you're trying to do can be achieved by running `lxc storage create pool2 lvm lvm.thinpool_name=lvmlxd source=ubuntu-05-vg`. Simply use `source` instead of `lvm.vg_name`. This is also in the [storage docs](https://github.com/lxc/lxd/blob/master/doc/storage.md#the-following-commands-can-be-used-to-create-lvm-storage-pools).

**Comment by sehari24jam** [comment]
Thanks.. It works.

```
lxc storage create pool2 lvm source=`hostname`-vg lvm.thinpool_name=lvmlxd
Storage pool pool2 created
```

```
lxc storage list
+-------+-------------+--------+--------------+---------+
| NAME  | DESCRIPTION | DRIVER |    SOURCE    | USED BY |
+-------+-------------+--------+--------------+---------+
| pool1 |             | zfs    | pool1        | 14      |
+-------+-------------+--------+--------------+---------+
| pool2 |             | lvm    | ubuntu-05-vg | 0       |
+-------+-------------+--------+--------------+---------+
```

```
sudo lvs
  LV     VG           Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lvmlxd ubuntu-05-vg twi-a-tz-- 200.00g             0.00   0.23                            
  root   ubuntu-05-vg -wi-ao---- 300.00g                                                    
  swap_1 ubuntu-05-vg -wi-ao---- 255.87g                                                    
  zfslxd ubuntu-05-vg -wi-ao---- 200.00g                                                    
```

**Comment by harridu** [comment]
Is there a similar restriction for using zfs?
