### ISSUE TITLE
Lxc containers won't start after ubuntu upgrade 

### ISSUE THREAD

**Issue by AmirBouzouina** [lxc/lxd#3462]
Hi there , 

I upgraded Ubuntu Gnome to version 17.04 from 16.04 , and since then , i cannot start a very important container 

here is the error message : 

lxc start mysql
error: Bad key: volatile.idmap.base
Try `lxc info --show-log mysql` for more info
------------------------------------------------------------

Here is the lxc info of the container

lxc info mysql
Name: mysql
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/01/29 10:38 UTC
Status: Stopped
Type: persistent
Profiles: default

what did i do wrong ? :(

**Comment by brauner** [comment]
I'll punt on that for now and leave this for @stgraber but he'll very likely ask you the same questions:

- What version of LXD where you running on `16.04`?
- Can you show the output of `lxc info`?

**Comment by AmirBouzouina** [comment]
Thanks for your answer brauner 


Here is the output of lxc info `grow@grow-HP-ENVY-m6-Notebook-PC:~$ lxc info
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 192.168.1.16:8443
  - 172.17.0.1:8443
  - 10.0.3.1:8443
  - 10.181.25.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFpjCCA46gAwIBAgIRAOHyyXyO3aB2KXy2c+gRB6IwDQYJKoZIhvcNAQELBQAw
    STEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEpMCcGA1UEAwwgcm9vdEBn
    cm93LUhQLUVOVlktbTYtTm90ZWJvb2stUEMwHhcNMTcwMTA2MjE0OTU5WhcNMjcw
    MTA0MjE0OTU5WjBJMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMSkwJwYD
    VQQDDCByb290QGdyb3ctSFAtRU5WWS1tNi1Ob3RlYm9vay1QQzCCAiIwDQYJKoZI
    hvcNAQEBBQADggIPADCCAgoCggIBAKzY6gQCj8YDXRwsJrCBoZUNcRCljub5IycN
    S2MCqsGL+UuBxkIBVRwnFDvXukUNN2oG422izLfdr094KUPI6vw8UwyeROXGjPgN
    sISB3bNBlCGL7LWSigsXYtfEy9p3W6Wf7+ttpQX2v03lYkLGq2RRCbr201enG8Qe
    lpUYluBTd2ZW9ZAsvKZAoytykvbByr562LZDQ8uyH7gfNMr63ql8dqL5/eCOKduz
    ZvfEQ3Ud3eF6RlFHL/viTI5ZRrsJ+uY50rKxA7AcDAqaFQDpfwTSXEs7sGDzZyTQ
    eLe5Ccdgkgxde1jWhYHEj6CadZnScy45czlr5LFBDUQRBn/uc86d/bwNJr7x6Azw
    ZLd2o78sRKodqieDymVLq5YpBUjNu5lIPxbMY4f+qUkImg8rNHjTWs1wA2Im9hSj
    dE5nsRQytfgOFBu4oKNxoKpFbjM5cYke+9QS8ZTUT21Zw+xGRLqy1godFp0LUXmI
    VUlB7rXEKF4dlCfVo9bN9QepX8mSUZ+6YC7XyhxAKT6KP/zGRkTtXpb5JLX2u9BP
    n5PGyaKyhKCiGsW1H5pK7e3HApj/FAQfSSHk8b8eZOeeZyGW9gLCcWpUOsgHmk3Z
    7OYQFhvLWj8EnJ2flrkktpmjIEvBZvHa0/Vxe2UEktOuFsfU3vG2q2foowwKeTNw
    2ge0diXNAgMBAAGjgYgwgYUwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsG
    AQUFBwMBMAwGA1UdEwEB/wQCMAAwUAYDVR0RBEkwR4IbZ3Jvdy1IUC1FTlZZLW02
    LU5vdGVib29rLVBDhwTAqAEDhxD9YOcBX+X+AJ2kN866RSGshxD9YOcBX+X+AKnq
    gP4EjqDUMA0GCSqGSIb3DQEBCwUAA4ICAQATK3l2hnaVPV5a5doImkMFiTu+ndgI
    nuRIA6IhU/tIqjb3L2MyfY2RyrDK2VZGkyqy4gVthZOrvndJjHiO0AcrwA6tAgZh
    SQ8aG3+1WZJ+kJkpqfk1ptnaMf9yaK9wy2SJZa4x4yT+NVTbXg+r3hj/VGL4T2UI
    FYgTpj/6JsGnzqtQdxvS/hR8o+ekc0FXV5Kq2TM1Ib0nzYcqTSyC9QTOA4Kd60JE
    SUYwdqoliXFC6V5kfwCUF5XhQwzyWRZKvvrlv835+K72DCedSJy4tF0n2fznJgcv
    zKzda87jUWzmW6qjAnek5NChBhAPN/cR+W+BZPXqx7/hkPzsrY3nCnjclS6bMd3N
    DkYmjgKnbmPcB8W8S6fU2SO8g3XfkdIZLAcIjPPZWI48UOkbjMNDk1kT0CRjPbCE
    E6ANlFMBPaNJTEnRj8VBNBMOoC1Ym2TjUSyminhVcg6zOkn6b5vB1wd6IkQvdyrU
    oQmDMTpO7x+ufJA+HTcxnX2CYU3EXHKppUHOaf/a2xFrxxeNsvYh40rZ42h064Wb
    wRfCIRkfluxIx0gUcWr3qFOyBC+rk0P11DDauXLf+4nnep1xsx35gvts6ySW0j//
    1PJvDrtxkxsNQHxsnCM5vFBN3ZbQK+39kIZ3+E7oqkDFg3lC3xzNgDOXomjYCi4l
    0Rt3g2M4Lq/Xnw==
    -----END CERTIFICATE-----
  certificatefingerprint: f0f747eb4a8ac3f10e78d2c1a386d0698b3b17cb7af736f48b5444667190c315
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.0-56-generic
  server: lxd
  serverpid: 2010
  serverversion: 2.4.1
  storage: dir
  storageversion: ""
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
public: false
`




However i wasn't able to find the version i used (hell i can't even find the version i am using now) , could you please guide me on how i can do that ? i would be greatful !

**Comment by stgraber** [comment]
You have LXD 24.1 on Ubuntu 17.04? that seems a bit weird, 17.04 comes with LXD 2.12 which would support volatile.idmap.base.

Can you make sure you are indeed on Ubuntu 17.04 (and not 16.10) and that your system has all update applied (which should get you LXD 2.12)?

**Comment by stgraber** [comment]
Your kernel version is also consistent with you being on Ubuntu 16.10 rather than Ubuntu 17.04 (you have 4.8 when you should have 4.10).

**Comment by AmirBouzouina** [comment]
Ah Sorry , i just saw that i was on ubuntu  16.10 , what should i do ? update Lxd ?

**Comment by stgraber** [comment]
you should update to Ubuntu 17.04, Ubuntu 16.10 is going to be end of life in a few days.

**Comment by AmirBouzouina** [comment]
Yeah well ... while updating , the setup process was saying that "root can't add packages"  and that i have held broken packages , so now i don't even have lxd installed on my machine , recovering my container is impossible now.

**Comment by stgraber** [comment]
What do you have in /var/lib/lxd/?

**Comment by stgraber** [comment]
Unless the package is purged (and the upgrader isn't supposed to ever do that), then the data is still on disk and installing LXD again should give you back your container.

**Comment by AmirBouzouina** [comment]
Hi , I don't have a /var/lib/lxd anymore :(

**Comment by stgraber** [comment]
I'm puzzled as to how this could have happened since only a purge of the LXD package would remove /var/lib/lxd, simple package removal will keep /var/lib/lxd around specifically to avoid such data loss.

There's unfortunately not much we can do at this point. The original issue was because of an upgrade from LXD 2.0.10 in Ubuntu 16.04 LTS to LXD 2.4.2 on Ubuntu 16.10 (which isn't supported anymore), causing that container startup failure. If you had then successfully upgraded to the supported Ubuntu 17.04 release you would have gotten LXD 2.12 which would have happily run your container.

The problem is that somewhere along the way from Ubuntu 16.10 to Ubuntu 17.04, something caused the LXD package to be removed AND purged which caused /var/lib/lxd, or at least so is my guess from your posts.
