### ISSUE TITLE
Unable to connect to remote images server in 2.15

### ISSUE THREAD

**Issue by parak** [lxc/lxd#3464]
Hi,

It seems that the following commit might have broken something for me with remote images:

https://github.com/lxc/lxd/commit/efdb5b8120484e7d91c935f830bf9538bc5c8b47

I have a remote server that I typically add with the following:

`lxc remote add lxc-images lxc-images.somecorp.com --public`

And it's added as expected:

`| lxc-images      | https://lxc-images.somecorp.com:8443 | lxd           | YES    | NO     |
`
Init command:

`lxc init lxc-images:centos7.3-custom centos-73 -p default -p docker  -c security.privileged=true`

Works fine under 2.14, but under 2.15 results in the error message as per the commit, 'The source server isn't listening on the network'. Is there some sort of new way that remotes need to be set up in 2.15?

Thanks!

**Comment by stgraber** [comment]
Doh, no, I think the new client code is just trying to be a bit too clever with public remotes. I'll send a fix.

**Comment by stgraber** [comment]
I'm also adding a test for this, we somehow don't have one for --public...

**Comment by stgraber** [comment]
Fixed in my bugfix branch and has a teest to make sure it doesn't show up again.

**Comment by parak** [comment]
Thanks for the quick response!

**Comment by parak** [comment]
On a very slightly related note, it's apparently not possible to downgrade via the ubuntu-lxc ppa as apt-cache always only shows the most recent, even though the previous version is available in the pool. I guess I can switch to the lxd-git-master archive as a workaround instead once that gets merged and built.

**Comment by stgraber** [comment]
If you are to downgrade, you'd need to pick up the 2.14 version of lxd-client and only downgrade that. Never downgrade LXD (lxd package) itself unless one of the developers tell you it's safe to do as database and on-disk storage changes somewhat frequently and will not cope with downgrading.

In this instance, as soon as my branch is merged, I'll be uploading cherry-pick of all the fixes to the Ubuntu package, so once automated testing is done (which can easily take 3-4 hours), a new version of the package will be available with the fix.

**Comment by stgraber** [comment]
If you need an immediate fix. You can download https://dl.stgraber.org/lxd-3464 (sha256: ef929bf889eddbc97da615dbc1f6d75fac8e65e767b92348d95e3fe1e839b79d) which is a built of the 2.15 client with my fix applied.
