### ISSUE TITLE
Wrong scheme version after upgrade

### ISSUE THREAD

**Issue by pshemk** [lxc/lxd#3465]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2
 * The output of "lxc info" or if that fails:
   * Kernel version:
4.4.0-81-generic
   * LXC version:
2.0.8
   * LXD version:
2.0.10
   * Storage backend in use:
btrfs

# Issue description
It's been about 2 months since I rebooted my container host (used to run on 4.4.0-71 and on lxd 2.0.9). After a reboot this morning LXD failed to start. Browsing the log revealed this message:

`The database schema is more recent than LXD's schema.`

I've copied the lxd.db onto a different machine and had a look inside:

```
sqlite> select * from schema;
1|34|1477613229
```

I've gradually lowered the version number without changing anything else, and once I got to 31 it worked again. After that operation the table looks like this:

```
sqlite> select * from schema;
1|31|1477613229
2|32|1498686099
```

I'm not sure how I've ended up with version 34 in there in the first instance. After the scheme version was corrected all my containers started without any issues. I can only suspect it had something to do with the upgrade to 2.0.10)

**Comment by stgraber** [comment]
The description above suggests that you have now potentially seriously corrupted your LXD instance.
There's a good reason why this check is in place and it's to prevent LXD downgrades from messing up your data.

**Comment by stgraber** [comment]
The LXD 2.0.x branch is currently at schema V32. Higher version of the schema can only have been obtained if you at some point ran a more recent copy of the LXD daemon.

**Comment by stgraber** [comment]
Your schema would have been upgraded to V34 if you had run LXD 2.3 up until LXD 2.9 (which would have gotten you V35).

**Comment by pshemk** [comment]
As I said - I have not touched the box for over 2 months, so the only plausible reason is that the underlying db somehow got corrupted. I run standard 16.04. there and do not have any additional ppas there.

**Comment by stgraber** [comment]
Can you post "ls -lh /var/lib/lxd" on the affected system?

**Comment by pshemk** [comment]
```
root@totara:~# ls -lh /var/lib/lxd
total 344K
drwx--x--x 1 root root  150 Dec  8  2016 containers
drwx--x--x 1 root root  118 Dec  8  2016 devices
drwxr-xr-x 2 root root   60 Jun 29 09:41 devlxd
drwx------ 1 root root  410 Nov  1  2016 images
-rw-r--r-- 1 root root 168K Jun 29 09:43 lxd.db
-rw-r--r-- 1 root root 168K Jun 29 09:41 lxd.db.bak
drwx------ 1 root root    0 Nov 12  2016 networks
drwx------ 1 root root   30 Oct 28  2016 security
-rw-r--r-- 1 root root 1.9K Oct 28  2016 server.crt
-rw------- 1 root root 3.2K Oct 28  2016 server.key
drwx--x--x 8 root root  160 Jun 29 09:43 shmounts
drwx------ 1 root root    0 Oct 28  2016 snapshots
srw-rw---- 1 root lxd     0 Jun 29 09:32 unix.socket
```

**Comment by stgraber** [comment]
```
drwx------ 1 root root    0 Nov 12  2016 networks
```

This particular entry could only have been created by LXD 2.3 or higher. So looks like your system did run a more recent LXD on the 12th of November 2016.

**Comment by pshemk** [comment]
I still have the original lxd.db if that helps

**Comment by stgraber** [comment]
LXD 2.0.x doesn't have the concept of networks at all and is therefore incapable of having created the "networks" directory. Only LXD 2.3 or higher has such a concept, running such a LXD version would explain the directory being created and the DB schema being updated.

**Comment by stgraber** [comment]
The content of the "patches" table in your database would also confirm that and let us pinpoint exactly what LXD version was run.

**Comment by pshemk** [comment]
ok, so I must have downgraded at some stage then, probably when I was setting the box up. The question is how the 2.0.9 worked in that scenario through a few restarts with no issues. 
In any case that's clearly not a bug.

**Comment by pshemk** [comment]
```
sqlite> select * from patches;
1|invalid_profile_names|1477613329
2|leftover_profile_config|1477613329
```

**Comment by pshemk** [comment]
I think I remember now the sequence of events. I've started on 16.10, created a separate partition for /var/lib/lxd. Then I went back to 16.04, but only recreated the main partitions. I must have left the original /var/lib/lxd and reuse it. 🤦‍♂️

**Comment by stgraber** [comment]
The reason why LXD 2.0.9 worked for you is because that check wasn't present then. We introduced the downgrade safety check in LXD 2.0.10. That's meant to prevent harm to user data in the event that they accidentally downgrade their systems.

**Comment by stgraber** [comment]
So looks like you ran LXD 2.4 then downgraded to LXD 2.0.
The database is going to be fine as the schema changes were only additions that simply won't get used.

The filesystem should be fine too. You have some extra bits like that networks directory, but they'll similarly just not be used.

The problem you will run into though is that you won't be able to upgrade from 2.0.x to a more recent version of LXD without having to revert your change to the schema table. If you don't undo your change (making your schema version V34 again) before proceeding, LXD will crash at startup when trying to apply a DB change that's already present (altering the containers table).

That's not going to be a problem until you upgrade to Ubuntu 18.04 though, so you may be fine for years still. Just something to keep in mind.

**Comment by pshemk** [comment]
Ok, if I  restore the original db, add the lxd-stable ppa and use that version - will the upgrade to 2.15 work for me?

**Comment by stgraber** [comment]
Yes, original DB and recent LXD feature releases will work fine. Note that this is a very big version jump though which introduces the LXD network API and LXD storage API, the upgrade should work fine, but some of LXD's behavior will be slightly different afterwards due to the new features.

Rather than using the PPA, I'd recommend you use xenial-backports instead, which we only update once we've had sufficient evidence that the latest LXD release is solid. It currently contains LXD 2.14 with 2.15 being pushed to it probably early next week.

To upgrade from it, do:
 - systemctl stop lxd
 - restore your DB
 - apt -t xenial-backports install lxd lxd-client

This requires xenial-backports to be enabled in /etc/apt/sources.list if it's not already.

**Comment by stgraber** [comment]
I'd recommend you also make a backup of your current lxd.db before doing that, just in case there were some changes made to your containers between the time you upgraded to LXD 2.0.10 and now.

**Comment by pshemk** [comment]
Thank you for your help here.
