### ISSUE TITLE
Client API deprecation should be visible at http://godoc.org/github.com/lxc/lxd

### ISSUE THREAD

**Issue by hnakamur** [lxc/lxd#3466]
I noticed the following comment

```
// DEPRECATED: This package is now deprecated in favor of github.com/lxc/lxd/client
//
// This package will be entirely removed from the code tree with LXD 2.16
```

at https://github.com/lxc/lxd/blob/lxd-2.15/client.go#L3-L5

However this comment is not visible at http://godoc.org/github.com/lxc/lxd

If both github.com/lxc/lxd/client.go and github.com/lxc/lxd/config.go, the above comment should be placed at the package document position, that is, before `package lxd` line.

Or, if only github.com/lxc/lxd/client.go is deprecated ant github.com/lxc/lxd/config.go is not, the above comment should be placed before the `type Client struct` line so that it appears as the comment for the Client struct.

**Comment by stgraber** [comment]
good catch, pushed a fix to my branch
