### ISSUE TITLE
zfs: make the helper functions sane

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3472]
Currently the `zfs` helper functions are - well - not ideal and for some of the other storage backends as well. For instance,

```
func (s *storageZfs) zfsPoolGetUsers() ([]string, error) {
	poolName := s.getOnDiskPoolName()
	subvols, err := s.zfsPoolListSubvolumes(poolName)
	if err != nil {
		return []string{}, err
	}

	exceptions := []string{
		"containers",
		"images",
		"snapshots",
		"deleted",
		"deleted/containers",
		"deleted/images"}

	users := []string{}
	for _, subvol := range subvols {
		path := strings.Split(subvol, "/")

		// Only care about plausible LXD paths
		if !shared.StringInSlice(path[0], exceptions) {
			continue
		}

		// Ignore empty paths
		if shared.StringInSlice(subvol, exceptions) {
			continue
		}

		users = append(users, subvol)
	}

	return users, nil
}
```

The function should either take a dataset argument and the name of the dataset is constructed outside of the function or it should take a pool, and a dataset argument and the path constructed inside. And it likely shouldn't be a method so that it can be used in other places as well. That's just one example. To illustrate, a better function is found in the lvm code:

    func lvmCreateLv(vgName string, thinPoolName string, lvName string, lvFsType string, lvSize string, volumeType string, makeThinLv bool) error

Not the best either, but reusable and clearer than the zfs one.

**Comment by brauner** [comment]
@monstermunchkin, this is what I was talking about. :)

**Comment by dnegreira** [comment]
@brauner I can pick up this one as well

**Comment by brauner** [comment]
Yup, sure, if you want. :) There's work for two. One can do `btrfs` and one `zfs`. :)

**Comment by dnegreira** [comment]
I will start to work on the zfs part.

**Comment by stgraber** [comment]
Hi @dnegreira, are you still working on this?

**Comment by dnegreira** [comment]
hi @stgraber I am currently not working on it, probably will start in two weeks or so, if there is the need for someone else to work on it, please go ahead.
