### ISSUE TITLE
Make --fast and --columns mutually exclusives

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#3484]
This works as expected...
```
net11 # lxc list --columns=nsp --format=csv
clients,RUNNING,2557
jasites,RUNNING,4114
ubuntu-template-zesty,RUNNING,5017
```
Adding --fast quietly ignores --columns directive.
```
net11 # lxc list --fast --columns=nsp --format=csv
clients,RUNNING,x86_64,2017/06/30 23:05 UTC,default,PERSISTENT
jasites,RUNNING,x86_64,2017/06/25 22:26 UTC,default,PERSISTENT
ubuntu-template-zesty,RUNNING,x86_64,2017/06/25 15:23 UTC,default,PERSISTENT
```
I've scripted around this for now + likely best if --fast + --columns work together or an error is thrown saying, they're mutually exclusive.

**Comment by stgraber** [comment]
Yeah, I guess we should throw an error. The help does say that it's just an alias for "-c nsacPt" already.

**Comment by davidfavor** [comment]
Apologies. I completely missed the alias not.
