### ISSUE TITLE
Request for correlating container pids to host pids

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#3485]
Debugging resource hog processes in containers becomes complex due to pid namespace.

Looking for a /proc way to convert container pids from container pid namespace to host pids.

Best way I've come up with so far is to search host level /proc/*/cmdline looking for "lxd monitor", then scan pid tree of each monitor looking for systemd, then adjust container pids by the difference of host level systemd pid number by container systemd pid == 1.

Surely there must be a better + more robust/correct way to do this.

Let me know if there's a standard approach/solution to doing this.

Many thanks.

**Comment by stgraber** [comment]
There is no concept of container as far as the kernel is concerned, so there's no super easy way to do so.
It's also made more complicated by the fact that the container itself can be using the pid namespace.

Very recent kernels do let you see the PID at every level of the namespace tree, but that's still not very useful as there is no way to say "give me the host pid for pid X in container Y".

You can get the list of all "pid X" but it won't tell you in what container that is:
```
stgraber@castiana:~$ lxc exec ups-monitor ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      5231  0.0  0.0  37764  2092 ?        Rs+  23:55   0:00 ps faux
root      4289  0.0  0.0  21628  2636 ?        Ss   23:40   0:00 bash
root      4299  0.0  0.0   4512  1188 ?        S+   23:40   0:00  \_ sh ups.sh
root      5230  0.0  0.0   7720   592 ?        S+   23:55   0:00      \_ sleep 5
root         1  0.0  0.0  37392  3872 ?        Ss   Jul01   0:00 /sbin/init
root        57  0.0  0.0  41768  1828 ?        Ss   Jul01   0:00 /lib/systemd/systemd-udevd
root        58  0.0  0.0  35280  4852 ?        Ss   Jul01   0:00 /lib/systemd/systemd-journald
root       261  0.0  0.0  16124  1944 ?        Ss   Jul01   0:00 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df 
message+   334  0.0  0.0  42908  2160 ?        Ss   Jul01   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
daemon     340  0.0  0.0  26048  1308 ?        Ss   Jul01   0:00 /usr/sbin/atd -f
syslog     341  0.0  0.0 186904  1780 ?        Ssl  Jul01   0:00 /usr/sbin/rsyslogd -n
root       344  0.0  0.1 370820 16904 ?        Ssl  Jul01   0:10 /usr/lib/snapd/snapd
root       347  0.0  0.0  20104  1700 ?        Ss   Jul01   0:00 /lib/systemd/systemd-logind
root       350  0.0  0.0 274492  3280 ?        Ssl  Jul01   0:02 /usr/lib/accountsservice/accounts-daemon
root       352  0.0  0.0  65524  2832 ?        Ss   Jul01   0:00 /usr/sbin/sshd -D
root       353  0.0  0.0  27732  1564 ?        Ss   Jul01   0:00 /usr/sbin/cron -f
root       388  0.0  0.0 277188  3892 ?        Ssl  Jul01   0:00 /usr/lib/policykit-1/polkitd --no-debug
root       633  0.0  0.0  14480  1160 console  Ss+  Jul01   0:00 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 linux

stgraber@castiana:~$ grep NSpid.*633$ /proc/*/status
/proc/8754/status:NSpid:	8754	633
```

In this example, I got lucky, when looking from the host, it only found a single host process that's mapped as "pid 633" in a container. But that could well have returned dozens of results.

For example, looking for PID 1:
```
stgraber@castiana:~$ grep "NSpid.*      1$" /proc/*/status
/proc/10393/status:NSpid:	10393	5321	1
/proc/11630/status:NSpid:	11630	31521	1
/proc/11654/status:NSpid:	11654	31535	3	1
/proc/12184/status:NSpid:	12184	5786	1
/proc/12188/status:NSpid:	12188	2084	1
/proc/12221/status:NSpid:	12221	2107	1
/proc/12297/status:NSpid:	12297	2150	1
/proc/12401/status:NSpid:	12401	2169	1
/proc/17627/status:NSpid:	17627	32351	1
/proc/17648/status:NSpid:	17648	32368	11	1
/proc/18426/status:NSpid:	18426	7307	1
/proc/1/status:NSpid:	1
/proc/23240/status:NSpid:	23240	8418	1
/proc/24140/status:NSpid:	24140	27491	1
/proc/24949/status:NSpid:	24949	1
/proc/24950/status:NSpid:	24950	2	1
/proc/25114/status:NSpid:	25114	27	1
/proc/25119/status:NSpid:	25119	32	1
/proc/25130/status:NSpid:	25130	43	1
/proc/25138/status:NSpid:	25138	51	1
/proc/25142/status:NSpid:	25142	55	1
/proc/25157/status:NSpid:	25157	70	1
/proc/25174/status:NSpid:	25174	87	1
/proc/25220/status:NSpid:	25220	133	1
/proc/25285/status:NSpid:	25285	194	1
/proc/25465/status:NSpid:	25465	8720	1
/proc/25486/status:NSpid:	25486	8738	1
/proc/25748/status:NSpid:	25748	8865	1
/proc/28404/status:NSpid:	28404	9387	1
/proc/28424/status:NSpid:	28424	9405	1
/proc/29141/status:NSpid:	29141	1
/proc/4960/status:NSpid:	4960	3564	1
/proc/7699/status:NSpid:	7699	1
/proc/8399/status:NSpid:	8399	30263	1
/proc/8759/status:NSpid:	8759	4802	1
```

**Comment by stgraber** [comment]
The best approach for a LXD container is probably a mix of cgroup and proc, something like:
```
stgraber@castiana:~$ cat find-pid.sh 
#!/bin/sh
for i in $(cat /sys/fs/cgroup/freezer/lxc/$1/tasks); do
    grep -q "NSpid.*	${2}$" /proc/${i}/status && echo ${i} && exit 0
done

exit 1
stgraber@castiana:~$ sh find-pid.sh ups-monitor 633
8754
```

**Comment by stgraber** [comment]
That's still not ideal though because if you use nested PID namespaces, that'd still fail.

**Comment by stgraber** [comment]
```
#!/bin/sh
CTN=${1}
PID=${2}

for i in $(cat /sys/fs/cgroup/freezer/lxc/${CTN}/tasks); do
    FIELDS=$(grep "NSpid.*$" /proc/${i}/status)
    set -- ${FIELDS}

    [ "${3}" = "${PID}" ] && echo ${i} && exit 0
done

exit 1
```

That version should be safe as it will only look at the first level of PID namespace.

**Comment by stgraber** [comment]
I personally just tend to use "ps fauxww" which shows me a nice tree of processes under each container monitor process and makes it pretty easy to visually get what you want. But for a scripted approach, the trick above should work fine.

Closing this issue as there's no real LXD bug here :)

**Comment by davidfavor** [comment]
This gives me a starting point.

If I come up with anything useful, I'll post it.

Thanks!

**Comment by davidfavor** [comment]
Here's a quick way to surface out some info.

1) iotop -P -a -d 1

<< to select sort on DISK WRITE

After a few seconds an offender will surface, pid 6105 in my case.

2) cat /proc/6105/cgroup | grep freezer
4:freezer:/lxc/net12-jasites

So if mysqld is the iotop offender in question, this is a quick way to determine container name.

**Comment by davidfavor** [comment]
Got motivated a few minutes ago + figured out a crude way to accomplish this.

Looks like **/proc/$pid/status** contains **NSpid** (pid namespace correlations), so my clunky... hacked together in an hour script, takes a set of host pids + appears to correctly convert them to their container name + container relative pid.
```
net12 # lxd-pid 849450 24668 1714
host=849450 lxd:net12-jasites=253094 command=/usr/sbin/mysqld
host=24668 lxd:net12-clients=996 command=/usr/sbin/mysqld
host=1714 lxd:net12-rmt-lowres=798 command=/usr/sbin/mysqld
```
Code is lipstick on a pig ugly...

[https://davidfavor.com/private/lxd-pid.txt](https://davidfavor.com/private/lxd-pid.txt) is the link.

Since pid namespace lookup is fairly easy, I'll revisit writing an **lxd-top** using PERL's **Proc::ProcessTable** to give some crude information about container resource usage, somewhat similar to what **lxc-top** use to provide.
