### ISSUE TITLE
installing LXD on various distros (e.g. CentOS)

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3489]
We receive a lot of requests on how to install LXD on other distros. We usually point users to snaps but we understand that there is a need for native packages or general install instructions as well. This is of course not necessarily something which upstream itself can leverage on a regular basis. It might make sense to either come up with some sort of wiki for this that is community maintained or a readme page that details installing LXD on other distros. This is something we might want to discuss amongst the maintainers (@stgraber, @hallyn) and with the community.

**Comment by brauner** [comment]
@ApertureSecurity I'm tracking this here.

**Comment by ApertureSecurity** [comment]
I searched this when before I asked. Sorry if I opened a duplicate issue.

Thanks for tracking this.

**Comment by brauner** [comment]
@ApertureSecurity, I just opened this. :)

**Comment by stgraber** [comment]
@brauner those kind of instructions really ought to go on the website.

**Comment by brauner** [comment]
Yeah, whatever works best.

**Comment by ApertureSecurity** [comment]
@brauner, thanks!

@strgaber I think its perfectly fine to have them here too. I mean , if I was looking at this on G.H then I would scroll down to look for instructions.

**Comment by stgraber** [comment]
@ApertureSecurity it's annoying to keep multiple places up to date and in sync. I also don't want README.md to become too long. So having the readme point to the website is probably the best solution.

**Comment by stgraber** [comment]
I reworked https://linuxcontainers.org/lxd/getting-started-cli/ to highlight all distributions that we know have some kind of packages for LXD as well as covering the snap option and the Windows and macOS clients.

That document then points back to README.md for any other case as building from source is pretty much the only option at that point.

For Centos, I know that the Fedora COPR repository can be made to work with a number of tricks, but it's not something I'd feel like adding to the website as it's really just a trick. If someone is to make actual Centos (well, RHEL compatible) packages for LXD, we'll gladly merge a pull request to add that to the website.

It looks like the snapd guys are also actively working on Centos7 support. Once that's added to snapd, we'll be adding automatic CI on our side for it and will then feel confident listing Centos with the LXD snap as something that we test.

**Comment by dann1** [comment]
@stgraber  I think you should  also point lxd on ArchLinux via the AUR in https://linuxcontainers.org/lxd/getting-started-cli/

**Comment by stgraber** [comment]
@dann1 done
