### ISSUE TITLE
client disconnects after few seconds with "got message barrier" error

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3496]
# Required information

 * Distribution: Ubuntu 17.04
 * The output of "lxc info" or if that fails:
```
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-28-generic
  server: lxd
  server_pid: 2209
  server_version: "2.12"
  storage: dir
  storage_version: "1"
```

# Issue description

Latest master version of `lxc` client breaks connection after 5 or so seconds with `←[36mDBUG←[0m[07-05|16:52:09] got message barrier` error.

# Steps to reproduce

 1. `lxc exec c1 --debug -- bash`
 2. press enter few times
 3. see the error

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [x] output of the client with --debug
```
...
←[36mDBUG←[0m[07-05|16:55:20] Connected to the websocket
←[36mDBUG←[0m[07-05|16:55:20] Window size is now: 182x67
←[36mDBUG←[0m[07-05|16:55:20] Connected to the websocket
←[32mINFO←[0m[07-05|16:55:20] Sending request to LXD                   ←[32metag←[0m= ←[32mmethod←[0m=GET ←[32murl←[0m=https://192.1...
# ←[36mDBUG←[0m[07-05|16:55:20] Got response struct from LXD
←[36mDBUG←[0m[07-05|16:55:20]
        {
                "id": "596057f4-83a8-46b0-836d-b8f7d4df50b4",
                "class": "websocket",
                "created_at": "2017-07-05T16:55:25.854034643+03:00",
                "updated_at": "2017-07-05T16:55:25.854034643+03:00",
                "status": "Running",
                "status_code": 103,
                "resources": {
                        "containers": [
                                "/1.0/containers/c1"
                        ]
                },
                "metadata": {
                        "fds": {
                                "0": "e17077569d9fa5f9b0a601fa733602fb0180c636d897ad46e46120d9399d7741",
                                "control": "34e23b4d9dd6f6db09a63aae2a8316522c1a8ea2af6b0124f38c3bed777f8a68"
                        }
                },
                "may_cancel": false,
                "err": ""
        }

# ls -la
total 24
drwx------  3 root root 4096 May 30 10:31 .
drwxr-xr-x 22 root root 4096 Apr 12 09:01 ..
-rw-------  1 root root  264 May 30 11:16 .bash_history
-rw-r--r--  1 root root 3106 Oct 22  2015 .bashrc
-rw-r--r--  1 root root  148 Aug 17  2015 .profile
drwx------  2 root root 4096 May 23 16:05 .ssh
# l←[36mDBUG←[0m[07-05|16:55:25] got message barrier
```
 - [ ] output of the daemon with --debug

**Comment by brauner** [comment]
Can you reproduce with latest LXD (2.15)?

**Comment by techtonik** [comment]
@brauner do you mean with server? I need to find out how to install it first. I guess I am not using any PPA right now.

**Comment by brauner** [comment]
@techtonik, yes with a new server. I'm unable to reproduce this on LXD 2.14 and later.

**Comment by stgraber** [comment]
I'm also unable to reproduce this using the current LXD client (2.15) talking to LXD 2.12 from Ubuntu 17.04.

**Comment by techtonik** [comment]
I can't find official instructions how to install development builds. Should I uninstall `lxd` provided by `apt` and try installing with `snapd`?

**Comment by stgraber** [comment]
You can get LXD 2.14 on Ubuntu 17.04 with:

    apt install -t zesty-backports lxd

LXD 2.15 will be pushed to backports later today so it'll update to 2.15 soon afterwards.

If you actually want the upstream builds (very much not recommended for any kind of stable environments), then you could indeed do a clean install of LXD from the snap as we publish automated builds of the snap for every commit:

    <remove all containers and images by hand (if any)>
    apt remove --purge lxd lxd-client
    snap install lxd --edge

**Comment by techtonik** [comment]
The same problem with LXD 2.15. I am connecting from Windows, so that might be a problem.

**Comment by stgraber** [comment]
ok, going to test from win10 then

**Comment by stgraber** [comment]
there's definitely something weird going on with Windows

**Comment by techtonik** [comment]
@stgraber maybe something related to file descriptors. Like if server side tries to send some signal to it.

**Comment by stgraber** [comment]
Confirmed it's got to do with the port to the new client library, trying to figure out exactly what changed there as the logic is near identical to the old code...

**Comment by stgraber** [comment]
There, figured it out, the disconnection was happening as part of the control socket handler so I fixed it to behave like the UNIX one.

There's no point sending sizing information as part of the handler as that's part of the initial request so we should just wait for interruptions and send a SIGINT in that case.

**Comment by techtonik** [comment]
It would be nice if by reading the code it would be possible to see complete interface of that control socket - I mean all those messages/signals/controlops that it sends/receives. Window resize is possible to add later from client side, but first there should be a terminfo entry for Windows capabilities. I was surprised to discover that there is no such entry.
