### ISSUE TITLE
lxd: bad uptime with ps command

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#3501]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04.2 LTS
 * The output of "lxc info" or if that fails:
 
config:
  core.https_address: 10.170.88.15:8443
  core.proxy_http: http://10.154.8.58:3128
  core.proxy_https: https://10.154.8.58:3128
  core.proxy_ignore_hosts: 10.0.0.0/8
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.170.88.15:8443
  architectures:
  - x86_64
  - i686
  certificate: |
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-79-generic
  server: lxd
  server_pid: 6788
  server_version: "2.14"
  storage: btrfs
  storage_version: "4.4"

# Issue description
ps auxw output says uptime is Aug04   whereas we are July 6 and the container was started a few seconds ago

A brief description of what failed or what could be improved.

# Steps to reproduce

 1. start a container (ubuntu 16.04.2 LTS)
 2. run "ps auxw" inside
 output:
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  37116  5344 ?        Ss   Aug04   0:00 /sbin/init
root        35  0.0  0.0  35280  4968 ?        Ss   Aug04   0:00 /lib/systemd/systemd-journald
root        40  0.0  0.0  41592  3336 ?        Ss   Aug04   0:00 /lib/systemd/systemd-udevd
root       126  0.0  0.0  16128   864 ?        Ss   Aug04   0:00 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclien
syslog     137  0.0  0.0 182668  3148 ?        Ssl  Aug04   0:00 /usr/sbin/rsyslogd -n
root       138  0.0  0.0  20104  1212 ?        Ss   Aug04   0:00 /lib/systemd/systemd-logind

On the host the output is good: ps auxw show real values:
ps auxw| grep journald:

100000    5010  0.0  0.0  35280  4968 ?        Ss   13:18   0:00 /lib/systemd/systemd-journald

**Comment by brauner** [comment]
Yes, this has already been fixed upstream and is a `LXCFS`, not a `LXD` bug. The appropriate new package will show up in the repos soon. :)
