### ISSUE TITLE
Return original error in RunCommand() + TryRunCommand()

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3502]
Currently `RunCommand()` and `TryRunCommand()` do not return the original error but rather a custom error created via `fmt.Errorf()`. While this is nice it also means that we can't expect the original error any further. For example, often I need to see if this a specific `errno` or inspect the exit status.

**Comment by stgraber** [comment]
We may be able to keep the original error but rewrite the error string to be that with RunCommand and TryRunCommand currently gives you.

**Comment by stgraber** [comment]
```
package main

import (
	"fmt"
	"os/exec"
	"syscall"

	"github.com/lxc/lxd/shared"
)

func main() {
	out, err := shared.RunCommand("sh", "-c", "exit 10")

	fmt.Printf("err: %s\n", err)
	fmt.Printf("out: %s\n", out)

	runError, ok := err.(shared.RunError)
	if ok {
		exitError, ok := runError.Err.(*exec.ExitError)
		if ok {
			waitStatus := exitError.Sys().(syscall.WaitStatus)
			fmt.Printf("exit: %d\n", waitStatus.ExitStatus())
		}
	}
}

stgraber@castiana:~/data/code/lxc/lxd/a (stgraber/master)$ ./a
err: Failed to run: sh -c exit 10: 
out: 
exit: 10
```
