### ISSUE TITLE
lxd init first intalation vdevs refer to the same device

### ISSUE THREAD

**Issue by Kriskasz** [lxc/lxd#3516]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Linux Ubuntu
 * Distribution version: 16.10  (Yakkety Yak)
 * The output of "lxc info" or if that fails:
   * Kernel version: #63-Ubuntu SMP Mon Jun 26 17:08:21 UTC 2017 (4.8.0-58-generic)
   * LXC version: 2.4.1
   * LXD version: 2.4.1
   * Storage backend in use: zfs

# Issue description

I have problem with lxd. This is compliantly new installation of Ubuntu 16.10, I try to run lxd init but when I answer: 

 Would you like to use an existing block device (yes/no) [default=no]? yes
 Path to the existing block device: /dev/sda1

I get this error: Failed to create the ZFS pool: cannot open '/dev/sda1': Device or resource busy cannot create 'lxdpool': one or more vdevs refer to the same device, or one of the devices is part of an active md or lvm device

and this is fdisk -l
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xf350b45a

Device     Boot     Start       End   Sectors   Size Id Type
/dev/sda1  *         2048 909619199 909617152 433.8G 83 Linux
/dev/sda2       909621246 976705535  67084290    32G  5 Extended
/dev/sda5       909621248 976705535  67084288    32G 82 Linux swap / Solaris

**Comment by stgraber** [comment]
Looking at what you pasted, you're telling ZFS to wipe the partition that currently holds your entire system. It's a really good thing that it gave you that error and didn't just do what you asked because otherwise you'd be left with a completely broken system.

The block device you provide LXD has to be unused so that it can be formatted for ZFS' use. If you just want to have ZFS use a file on your existing partition, use the default answer of "no" which will then let you setup a loop based ZFS using a file on your existing filesystem.

PS: Ubuntu 16.10 is going to reach its end of life in a week or so, you should really upgrade to 17.04.

**Comment by brauner** [comment]
All of our storage backends will refuse to overwrite existing partitions iff the tools the tools for the relevant storage driver are smart enough to not do this without setting a force option!

**Comment by Kriskasz** [comment]
So what will the best way to set up a loop based ZFS or to add new partition and use ZFS filesystem?
How many space I should assign to this partition? I understand that it is keeping images and containers. So if I want to have only 34 containers in this server and nothing more and I have 500 Gb I should assign for ZFS partition  420Gb and the rest for the system around 80 Gb, yes?
Should I create storage pool and the one big volume?
Thank you for all information.

**Comment by stgraber** [comment]
If you just go with the default values in "lxd init", it will setup a loop based ZFS for you and let you specify how big you want to allow for it to be (it pre-selects a reasonable size based on available space).

You can technically grow it later or move it to physical drives/partitions, but note that a ZFS pool can never shrink, so you'll always have to move to something bigger.
