### ISSUE TITLE
Pre-defined (non-mac based) static IPv6 address ?

### ISSUE THREAD

**Issue by nipil** [lxc/lxd#3519]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04.2
 * The output of "lxc info" (2.15 backports) : [lxc-info.txt](https://github.com/lxc/lxd/files/1137104/lxc-info.txt)

# Issue description

We could not get a static **pre-defined/constant** IPv6 address in container, we are only able to get an auto-configured one (mac based). This is espacially important as our firewalling is done outside the hosts and we need to configure static NATs

# Steps to reproduce

 1. lxc network create dmz2 ipv4.address=10.0.2.254/24 ipv4.nat=false ipv4.firewall=false ipv6.address=fd00:0000:0000:0002::FE/64 ipv6.nat=false ipv6.firewall=false
 2. lxc init ubuntu:16.04 test2
 3. lxc network attach dmz2 test2 eth0
 4. lxc config device set test2 eth0 ipv4.address 10.0.2.5
 5. lxc config device set test2 eth0 ipv6.address fd00:0000:0000:0002::5
 6. lxc start test2
 7. lxc info test2

Actual result: [test2.txt](https://github.com/lxc/lxd/files/1137111/test2.txt)

Expected result : test2 should have fd00:0000:0000:0002::5/64 as IPv6 address

PS: we prefer not to use cloud-image

**Comment by stgraber** [comment]
Static IPv6 addressing can only work if running in DHCPv6 stateful mode or in fully static mode.

To have LXD run dnsmasq in stateful mode, you'll need to set the "ipv6.dhcp.stateful" property on the network to "true". Then you'll need to have your container do stateful DHCPv6 requests. The way to configure this varies based on the distributions. For Ubuntu cloud images, you should be able to configure that through the user.network-config property.

**Comment by stgraber** [comment]
```
stgraber@castiana:~/data/code/lxc/lxd (zfs)$ lxc network create lxd3519 ipv6.dhcp.stateful=true
Network lxd3519 created

stgraber@castiana:~/data/code/lxc/lxd (zfs)$ lxc init images:ubuntu/xenial test
Creating test

stgraber@castiana:~/data/code/lxc/lxd (zfs)$ lxc config device add test eth0 nic nictype=bridged parent=lxd3519 ipv4.address=10.142.175.123 ipv6.address=fd42:a052:472c:b89b::123
Device eth0 added to test

stgraber@castiana:~/data/code/lxc/lxd (zfs)$ lxc start test
stgraber@castiana:~/data/code/lxc/lxd (zfs)$ lxc exec test bash
root@test:~# vim /etc/network/interfaces
root@test:~# reboot

stgraber@castiana:~/data/code/lxc/lxd (zfs)$ lxc list test
+------+---------+-----------------------+---------------------------------+------------+-----------+
| NAME |  STATE  |         IPV4          |              IPV6               |    TYPE    | SNAPSHOTS |
+------+---------+-----------------------+---------------------------------+------------+-----------+
| test | RUNNING | 10.142.175.123 (eth0) | fd42:a052:472c:b89b::123 (eth0) | PERSISTENT | 0         |
+------+---------+-----------------------+---------------------------------+------------+-----------+
```

/etc/network/interfaces in the container:
```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
iface eth0 inet6 dhcp
```

**Comment by nipil** [comment]
Oh righty, thanks mate, we forgot the difference between stateless and stateful dhcp in ipv6 ! (see [this page](https://thenetworkway.wordpress.com/2014/07/02/ipv6-address-assignment-stateless-stateful-dhcp-oh-my/), and search "IPv6 address assignment options" in the page)

We added `iface eth0 inet6 dhcp` to the containers' network config to do explicit statefull dhcp, and the container immediately received its desired address : 

```
+-------+---------+-----------------+-----------------------------------+------------+-----------+
| NAME  |  STATE  |      IPV4       |               IPV6                |    TYPE    | SNAPSHOTS |
+-------+---------+-----------------+-----------------------------------+------------+-----------+
| test2 | RUNNING | 10.0.2.5 (eth0) | fd00::2:216:3eff:fe91:ce7b (eth0) | PERSISTENT | 0         |
|       |         |                 | fd00:0:0:2::5 (eth0)              |            |           |
+-------+---------+-----------------+-----------------------------------+------------+-----------+
```

The container got two ipv6 addresses : 
- the pre-configured one, defined in container's config and provided by stateful dhcp6
- the autoconfigured one, due to host network RA (router advertisements) and container sysctl

By the way, we ensured that the pre-configured was used as source address for outgoing traffic, so we could have left it that way.

But as a side precaution, we configured sysctl in the container so that eth0 does **not** get autoconfigured addresses : 

```
net.ipv6.conf.all.autoconf = 0
net.ipv6.conf.default.autoconf = 0
net.ipv6.conf.eth0.autoconf = 0
```

And here's the final result : 

```
+-------+---------+-----------------+----------------------+------------+-----------+
| NAME  |  STATE  |      IPV4       |         IPV6         |    TYPE    | SNAPSHOTS |
+-------+---------+-----------------+----------------------+------------+-----------+
| test2 | RUNNING | 10.0.2.5 (eth0) | fd00:0:0:2::5 (eth0) | PERSISTENT | 0         |
+-------+---------+-----------------+----------------------+------------+-----------+
```

Thanks for the help ! :+1:
