### ISSUE TITLE
lxc file pull/push doesn't work with wildcards

### ISSUE THREAD

**Issue by AdamIsrael** [lxc/lxd#3523]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2
 * The output of "lxc info":

```
config:
  core.https_address: '[::]'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 172.28.0.169:8443
  - 10.113.209.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE----- 
    ...
    -----END CERTIFICATE-----
  certificate_fingerprint: e7d700f1688a5dff090df4c442aa5cd75ba0b7844d3e6fcbbc8412bc77118bcb
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-26-generic
  server: lxd
  server_pid: 3516
  server_version: "2.15"
  storage: zfs | dir
  storage_version: 0.6.5.9-2 | 1
```

# Issue description

Attempting to pull or files based on a wildcard throws the generic error `error: not found`. The help text of the `lxc file` command implies that multiple files can be pushed at once, but doesn't explicitly mention wildcards.

# Steps to reproduce

```bash
lxc file pull foo/root/*.snap .
lxc file push *.snap bar/snap
```
# Expected behavior

I'd expect all files matching the wildcard to be pulled or pushed from/to the specified container, or a more specific error message indicating that wildcards aren't supported.

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc file push a-* snapcraft/root/
stgraber@castiana:~$ 
```

For pull, that's indeed not supported.

**Comment by stgraber** [comment]
The help is also pretty clear that when dealing with multiple files they need to be space separated:
```
lxc file pull [-r|--recursive] [<remote>:]<container>/<path> [[<remote>:]<container>/<path>...] <target path>
lxc file push [-r|--recursive] [-p|--create-dirs] [--uid=UID] [--gid=GID] [--mode=MODE] <source path> [<source path>...] [<remote>:]<container>/<path>
```

The shell does that for you when using wildcards with push (LXD itself never sees the "*"). For pull, your local shell obviously can't expand the remote paths, neither can LXD, so in such case, your shell passes the string "foo/root/*.snap" to LXD which then attempts to extract exactly that from the container. Since you don't have a file called "*.snap" this fails with a 404.

If you did have a file called "*.snap" this would obviously then work:
```
stgraber@castiana:~$ lxc exec snapcraft touch /root/\*.snap
stgraber@castiana:~$ lxc file pull snapcraft/root/*.snap .
stgraber@castiana:~$ ls -lh | grep snap
-rw-r--r--  1 stgraber domain admins    0 Jul 11 03:41 *.snap
```

**Comment by AdamIsrael** [comment]
Understood re file push behavior. It's correct behavior from a technical perspective, although perhaps not as user-friendly as it could be. 

I don't see the same behavior you do from the push, though:
```
lxc file push *.snap osmr2-snap/root
error: wrong number of subcommand arguments

Usage: lxc file <subcommand> [options]
...
```
Perhaps also an issue with wildcard expansion?

**Comment by stgraber** [comment]
You're missing a trailing slash in your push command.
