### ISSUE TITLE
lxd not allocate IPs to conteiners

### ISSUE THREAD

**Issue by Kriskasz** [lxc/lxd#3525]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.04 (Zesty Zapus)
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-26-generic #30-Ubuntu SMP
   * LXC version: 2.12
   * LXD version: 2.12
   * Storage backend in use: zfs

# Issue description

After launch container IP4 is empty. During the installation I choose configure bridge - no. After that I add my own -> lxc network attach-profile br0 default eth0

**my /etc/network/interface looks like that:**

source /etc/network/interfaces.d/*

The loopback network interface
auto lo
iface lo inet loopback

The primary network interface
auto br0
iface br0 inet static
        address x.x.x.2
        netmask 255.255.252.0
        broadcast x.x.x.x
        network x.x.x.0
        gateway x.x.x.254
        dns-nameservers 8.8.8.8 x.x.x.x x.x.x.x

        bridge_ports eth0
        bridge_stp off
        bridge_fd 0
        bridge_maxwait 0

iface eth0 inet manual

**lxc profile show default**

config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: lxdpool
    type: disk
name: default
used_by:
- /1.0/containers/first
- /1.0/containers/second

**also path is empty**
/var/lib/lxd/storage-pools/lxdpool/containers/first is empty

**and the file doesn’t** exist /etc/default/lxd-bridge

What I should do to add IPs to this address? I would like to add range of addresses?

**Comment by stgraber** [comment]
You defined your own bridge on your system without setting up a DHCP/DNS server to allocate addresses, so LXD is doing exactly what you told it to. It connects your containers to the bridge. They then fail to get an IP.

You can either use LXD managed network which will get you DHCP/DNS managed by LXD or you should run your own DHCP and DNS server for your network.
