### ISSUE TITLE
UTF-8 support for image properties

### ISSUE THREAD

**Issue by jensg-st** [lxc/lxd#353]
I just have a few questions regarding the X-LXD-properties value in the header for image import.

The spec says the format is like ’key=value; key1=value1’ and I have seen in the source that you are splitting at ‘; ‘. 

list := strings.Split(properties, "; ")

My questions in general:

1. Despite that splitting (it might be better to split at ‘;’ and then trim the string (sorry for not commenting it during the pull request, but you are too fast and in a different timezone :)), wouldn’t make a comma more sense, if you want to be close to the HTTP 1.1 spec? Then it would be possible to split the properties over multiple headers, if required. 

2. Http headers support US-ASCII only, so I can not use special characters,  German umlaut or Chinese? Maybe the properties are not meant to be used for this kind of data? If yes, wouldn’t it be better to use URL-encoded UTF-8? A few bugs might be avoided as well, which usually happens with splitting and parsing text. If the X-LXD-Properties header is a URL-encoded string with all the key/values, it would be easier I think.

I know that you are doing the server and client, but if you or other people want to do some integrations, this might cause issues. I'm happy to give it a go, if you agree.

**Comment by stgraber** [comment]
Both are good points so if you want to give it a go, go ahead!

Note that on top of the code change, you'll also have to tweak specs/rest-api.md to match the change (urlencode).

**Comment by stgraber** [comment]
Tentatively targeting for 0.4 if you have the time, otherwise we'll push it to 0.5.

**Comment by jensg-st** [comment]
Will do it in the next few days.
