### ISSUE TITLE
UX of LXD development setup

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3530]
Editing LXD code is a pain for me compared to Python projects and static web sites, where most of the changes could be made directly in a short 3 ops edit-run-check cycle. So I thought that maybe there is some magic pill about development setup that you use to work on LXD that makes the workflow more productive than that set of scripts that I set for myself and what still doesn't save me from the pain of cd into overly long Go directories (because scripts can not do cd for me). I don't think that my shell based setup is productive for Go/LXD development, so I am interested how you do it.

**Comment by stgraber** [comment]
I just have a symlink from "lxd" to "$GOPATH/src/github.com/lxc/lxd" which shortens things considerably.

**Comment by stgraber** [comment]
Also, shell history (ctrl+r) does help a lot when you don't feel like typing long paths that you've already recently typed.

**Comment by stgraber** [comment]
Closing this as there's no actual issue in LXD which needs fixing. It's unfortunately the pain that comes with the way Go wants you to setup your development environment.

I for one also am not a fan of the programming language forcing my hand on where things are supposed to be on my filesystem, but that's the way this work...

**Comment by techtonik** [comment]
So far:
1. [x] `ln "$GOPATH/src/github.com/lxc/lxd" lxd`
2. [x] `ctrl-r` or https://github.com/dvorka/hstr
