### ISSUE TITLE
Integrate with pagure.io to fork and edit inside LXD

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3531]
https://pagure.io is GPLv2 GitHub/GitLab/Forge alternative implemented in Python/pygit2.

It does have feature to "fork and edit files with web interface", but non-trivial operations are still require local clone, keys setup, git config, branching. All these steps are unnecessary manual routine that kills the fun from contribution process. So making an exemplary integration can push LXD beyond simple local usage https://linuxcontainers.org/lxd/try-it/ into more useful network solutions for people.

https://pagure.io/pagure/issue/2419

**Comment by stgraber** [comment]
Not sure that there is anything for us to do at the LXD level here.
If someone does take on that work for pagure and they need any additional functionality or help from LXD, let us know and we'll look into it.

Closing the issue as there's no actual LXD bug to investigate/fix.

**Comment by techtonik** [comment]
`pagure` should be able to pass container config to LXD to get up `try server` for user.
```
sources: https://github.com/lxc/lxd
branch: master   # or pr-123
username: anatoly techtonik <techtonik@gmail.com>
```
LXD should pass pubkey for commit back to `pagure` server:
```
pubkey: ...
```
