### ISSUE TITLE
lxd-lts not available via snap

### ISSUE THREAD

**Issue by dann1** [lxc/lxd#3536]
When I install lxd via snap, it installs the latest release, and I can't find the LTS version. Am I doing something wrong or it's just missing?

**Comment by stgraber** [comment]
LXD 2.0 as a snap (2.0.10) is currently only available for Snappy 15.
I'm actually working on that this week. I've filed an issue on our packaging branch for tracking:
https://github.com/lxc/lxd-pkg-ubuntu/issues/30

**Comment by dann1** [comment]
So what do I have to do to install LXD 2.0, I'm not a connoisseur of snaps. Is snappy 15 is the earlier version of snapd?

**Comment by stgraber** [comment]
Right now, if you want LXD 2.0, don't use the snap package.

You'll hopefully be able to install it through a snap in the next month or so, assuming we don't hit any blockers when doing this work.

Snappy 15 is indeed an old version of Ubuntu Core, so it's a full Linux distribution (Ubuntu based) which uses snaps exclusively but a very old version of what snaps are today. I can't really recommend using that at all :) We'll be discontinuing support for LXD on Snappy 15 as soon as we get LXD 2.0 available as a modern snap.

**Comment by dann1** [comment]
Thanks a lot for the tips

**Comment by dann1** [comment]
So, question again. Does lxd 2.0 snap exists to be handled by snapd, but it's not approved yet by the people managing snapd? If this is the case is it shared to be used somewhere  else ?

**Comment by stgraber** [comment]
Nope, the LXD 2.0 snap only exists on my laptop and doesn't have functioning networking which is why we haven't uploaded it yet to the store.

**Comment by stgraber** [comment]
The LXD snap is also a bit special as far as snaps go as it requires a lot more security access to the system than your average snap, this is done through special signed assertions that you receive from the store and makes it hard to sideload the snap even if I had one I could provide you right now.

**Comment by dann1** [comment]
Sad new, thanks for your time.
