### ISSUE TITLE
Cannot remove storage pool with images

### ISSUE THREAD

**Issue by kaszuba** [lxc/lxd#3539]
I found situation when i cannot remove additional storage pool when some image exists on it.
In general it is ok, but i cannot delete it from this specified storage only, to delete i need to remove it from all storage pools.

Steps:
- create container on "default" storage pool

> lxc init ubuntu:16.04 test1

- create new storage pool and container on it

> vgcreate NEW /dev/nvme0n1p1
> lxc storage create NEW lvm source=NEW
> lxc init ubuntu:16.04 test2 -s NEW

- delete test2 container

> lxc delete test2

At this moment i have only one volume on new storage pool:

> lxc storage volume list NEW
> +-------+------------------------------------------------------------------+-------------+---------+
> | TYPE  |                               NAME                               | DESCRIPTION | USED BY |
> +-------+------------------------------------------------------------------+-------------+---------+
> | image | 7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25 |             | 0       |
> +-------+------------------------------------------------------------------+-------------+---------+

To remove NEW storage pool i need to delete image with standard image delete command, when i trying to delete it by storage api i got:

> error: storage volumes of type "image" cannot be deleted with the storage api

Please add possibility to delete storage pool in such situation, or allow to delete image only from one specified storage pool.

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-83-generic
   * LXC version: 2.0.8
   * LXD version: 2.15
   * Storage backend in use:  lvm

**Comment by stgraber** [comment]
@brauner can you take this one.

The problem is when you have multiple storage pools, have the same image on more than one of them, then empty one of the pools of its containers but you can't remove the image without also removing it from all other pools.

**Comment by brauner** [comment]
I think I'd rather allow to do `lxc storage volume delete <pool-name> image/<hash` then allow to wipe the pool in this case.
