### ISSUE TITLE
storage backend or image datastore 

### ISSUE THREAD

**Issue by dann1** [lxc/lxd#3546]
When we setup lxd with a storage backend, this is the storage backend for the containers. Question, does the image datastore gets benefits from storage backend as well?

**Comment by stgraber** [comment]
Kinda. The native format for LXD images are tarballs or squashfs. Those files will always be stored in /var/lib/lxd/images which is typically on your host's filesystem and so unaffected by any storage pool configuration you may have.

However, LXD also stores an optimized version of the image on a per storage pool basis. For LVM that's a LV of the unpacked image, for ZFS a filesystem of the unpacked image and for btrfs a subvolume of the unpacked image. Those are generated on-demand when you create a container on the specific storage pool and is then used for any further container you create, making it possible to instantly create containers (no more unpacking required).

**Comment by stgraber** [comment]
Closing this as it's really just a question and not an actual LXD issue.

Note that you may want to check out https://discuss.linuxcontainers.org for general questions about LXD behavior and design as those forum threads tend to get better indexing by Google and others than closed Github issues.
