### ISSUE TITLE
disabling ipv6 in containers

### ISSUE THREAD

**Issue by jfgibbins** [lxc/lxd#3547]
Despite a lot of searching, I'm not able to find a way to disable IPv6 in containers, specifically Ubuntu.  The usual method is sysctl settings, but that doesn't work.  Could you please point me to the magical setting for this.  FYI, there are unprivileged containers.  Thanks guys.  Always appreciated.
James

**Comment by stgraber** [comment]
Seems to be working fine here:
```
stgraber@castiana:~$ lxc exec ups-monitor bash
root@ups-monitor:~# ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 00:16:3e:1f:c6:7a  
          inet addr:10.204.119.41  Bcast:10.204.119.255  Mask:255.255.255.0
          inet6 addr: 2001:470:b368:4242:216:3eff:fe1f:c67a/64 Scope:Global
          inet6 addr: fe80::216:3eff:fe1f:c67a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4681 errors:0 dropped:0 overruns:0 frame:0
          TX packets:364 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2354704 (2.3 MB)  TX bytes:41303 (41.3 KB)

root@ups-monitor:~# echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6 
root@ups-monitor:~# ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 00:16:3e:1f:c6:7a  
          inet addr:10.204.119.41  Bcast:10.204.119.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4681 errors:0 dropped:0 overruns:0 frame:0
          TX packets:364 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2354704 (2.3 MB)  TX bytes:41303 (41.3 KB)

root@ups-monitor:~# 
```

**Comment by stgraber** [comment]
It could be that sysctl.d doesn't work though as at least some init systems wrongly assume that those can't be applied in containers or consider some sysctl being denied as a critical error and stop applying any further one.

You may just want to stick this particular sysctl as a network hook or in rc.local for now.

**Comment by jfgibbins** [comment]
I do get the same result on ifconfig, but netstat -plant still shows services binding, even after restarting service and/or container:
tcp6       0      0 :::8301                 :::*                    LISTEN      384/consul
tcp6       0      0 :::8302                 :::*                    LISTEN      384/consul
tcp6       0      0 :::8500                 :::*                    LISTEN      384/consul
tcp6       0      0 :::22                   :::*                    LISTEN      372/sshd
tcp6       0      0 :::8600                 :::*                    LISTEN      384/consul

**Comment by jfgibbins** [comment]
I'll look into using rc.local and stuff, maybe I can figure out something that I can drop in cloud.init

**Comment by stgraber** [comment]
yeah, I think that part is normal though they won't have anything on IPv6 to bind to so will just bind to all IPv4 addresses. 

You could set /proc/sys/net/ipv6/bindv6only to 1 in your container, that should stop that behavior of having things bind to IPv6.

**Comment by stgraber** [comment]
Closing this issue as the sysctls do appear to work and there's really not much that LXD can do about any of this as it's pure kernel and init system behavior. Feel free to ask more questions in the issue though.

**Comment by jfgibbins** [comment]
You beat me to it.  I managed to stop the bindings, but in order to do so, had to disable ipv6 in the host kernel, which breaks far too many other things, and can't really change container kernel as it's shared.  Appreciate the help, but pretty sure the issue is regardless of containers.
