### ISSUE TITLE
LXD 2.15 - storage volumes stopped working - idmaps of container and storage volume are not identical

### ISSUE THREAD

**Issue by niksfirefly** [lxc/lxd#3548]
* Distribution:Ubuntu
 * Distribution version: 16.04
  kernel_architecture: x86_64
  kernel_version: 4.4.0-71-generic
  server_version: "2.15"
  storage: dir | zfs

After upgrade to LXD 2.15 i cannot start containers with custom storage volumes:

error: Failed to initialize storage volume "web-root" of type "custom" on storage pool "zfs-root": idmaps of container and storage volume are not identical

what is going on? cant find any info on this

**Comment by stgraber** [comment]
@brauner

**Comment by stgraber** [comment]
@niksfirefly Can you show "lxc config show --expanded CONTAINER-NAME" and "lxc storage volume show POOL CUSTOM-VOLUME"?

**Comment by stgraber** [comment]
I suspect that the newly introduced custom volume attach code is missing an upgrade step that causes existing containers to work properly, we should be able to provide you with a "lxc storage volume set" command which sets the needed bits for things to keep working as they did.

I'm somewhat surprised that custom volumes were even usable for you prior to LXD 2.15 as for most people the lack of correct filesystem ownership made them unsuable.

**Comment by brauner** [comment]
I'll send a branch tomorrow (given that it makes sense once I've taken a closer look ;))

**Comment by niksfirefly** [comment]
Storage volumes are attached to container through profiles.
I've omitted certain init-cloud and eth data from config for the sake of brevity.

[config.txt](https://github.com/lxc/lxd/files/1147464/config.txt)
[profile-home.txt](https://github.com/lxc/lxd/files/1147465/profile-home.txt)
[profile-logs.txt](https://github.com/lxc/lxd/files/1147467/profile-logs.txt)
[storage-home.txt](https://github.com/lxc/lxd/files/1147468/storage-home.txt)
[storage-logs.txt](https://github.com/lxc/lxd/files/1147466/storage-logs.txt)

Well is there something I can do?
I dont understand what "lxc storage volume set" could change for storage volume.

**Comment by brauner** [comment]
@niksfirefly, do all of the containers attached to those profiles have the same id mappings?

**Comment by niksfirefly** [comment]
sure same mapping and everyone cannot start

**Comment by niksfirefly** [comment]
another strange thing
when i try to run for - old and new - storage volumes
lxc storage volume edit zfs-root web-root
i get endless warning:
Config parsing error: ETag doesn't match: 960e5281b9e51d6be8eb1f34f7d9231942156646baacbb0509473703066a5531 vs c27ff56a01eb9502ba001b14c03e66232f407cafeef997177f06a5b442001698
Press enter to open the editor again

**Comment by brauner** [comment]
Fwiw, you can abort by doing `Ctrl + C`.

**Comment by niksfirefly** [comment]
Well of course
but this is something new
BTW I tried with all my ZFS storage pools

**Comment by brauner** [comment]
I can't really reproduce this unless I e.g. mix privileged and unprivileged containers or containers with different id mappings. Do you remember what LXD version you used to originally attach those volumes?

**Comment by niksfirefly** [comment]
I think LXD 2.13
Are there any special upgrade steps between 2.13 .. 2.15 ?

**Comment by stgraber** [comment]
The ETag issue got fixed a couple of days ago upstream and we added a test for it too. I'll backport it to the 2.15 packages next time I get around to doing that (not sure when since I'm traveling...).

**Comment by niksfirefly** [comment]
I got question - where is stored information about idmaps of storage volumes?

**Comment by brauner** [comment]
You can see the idmap of a storage volume by looking at `lxc storage volume show <pool-name> <volume-name>`. Starting with `LXD 2.15` it should show `volatile.idmap.last` and `volatile.idmap.next`.

**Comment by niksfirefly** [comment]
Should I edit volume storage and copy container:
volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'

How can I do that when this endless warning appears
Config parsing error: ETag doesn't match

**Comment by brauner** [comment]
@niksfirefly, if you can't wait for a new LXD version to come out and this is something you can do I'd recommend to detach the volume from the default profile and attach it again.

**Comment by niksfirefly** [comment]
I got 
error: Failed to initialize storage volume "web-root" of type "custom" on storage pool "zfs-root": idmaps of container and storage volume are not identical
with new and old reattached storage volumes so they are not working anymore
I checked new storage volumes config and there's no idmaps in config

**Comment by brauner** [comment]
Ok, if it's not too much trouble, please show:

    lxc list
    lxc list security.privileged=true
    lxc list security.idmap.isolated=true

**Comment by niksfirefly** [comment]
lxc list
|  NAME  |    STORAGE POOL |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |         PROFILES   
| web163 |  zfs-root     | STOPPED |      |      | PERSISTENT | 11        | web   web-home  web-logs                 

Empty lists for:
lxc list security.privileged=true
lxc list security.idmap.isolated=true

**Comment by brauner** [comment]
@niksfirefly, I'm trying to reproduce now by using a LXD 2.13 instance, creating a custom volume and attaching it to the default profile and then upgrading to LXD 2.15.

**Comment by brauner** [comment]
Ok, reproduced and I think I know what it is. You have multiple containers attaching the same storage volume and even though they all share the same mapping the fact that the volume has never been mapped means that starting one would remap which confuses LXD since it sees that there are other attachers that might potentially have a different mapping. I'll come up with a fix.

**Comment by brauner** [comment]
@niksfirefly, if you want you can grab the commits from my branch https://github.com/lxc/lxd/pull/3568 and test.

**Comment by niksfirefly** [comment]
Ok I try but what about newly created storage volumes - they are not working, no idmaps in their config and no way to edit config due ETAG errors
Is there a way to downgrade from 2.15 to 2.13 ?

**Comment by brauner** [comment]
@niksfirefly, not really. We will do a SRU release very soon than this error will be gone.

**Comment by niksfirefly** [comment]
OK I must only add that even storage volumes NOT attached to multiple containers are not working with same effect.

**Comment by brauner** [comment]
@niksfirefly, were you able to test it with this branch?

**Comment by brauner** [comment]
@niksfirefly, just tested it myself. My branch fixes that particular problem as well.

**Comment by niksfirefly** [comment]
Well I must say that I dont know how to apply your branch so I wait for 25 July and next LXD version
