### ISSUE TITLE
dns-sortlist not recognized in network-config

### ISSUE THREAD

**Issue by jfgibbins** [lxc/lxd#3551]
Hi Stéphane,
I entered this ticket for cloud-init on launchpad.  I'm pretty sure the issue is in their code, but I thought you might be interested as well.

I'm using LXD with Ubuntu images, and cloud-init to do initial setup of container.  I'm not sure, but I believe the issue is in cloud-init, but would appreciate a pointer to the right location if not.  Currently using network-config meta data, cloud-init takes the following config and converts correctly:

version: 1
config:
 - type: physical
   name: eth0
 - type: nameserver
   address: ['xx.xx.xx.xx']
   search: ['example.local', 'example.org']

However including the following line is not recognized:

   sortlist: ['xx.xx.xx.xx', 'xx.xx.xx.xx']

Please add support for this standard nameserver option.

**Comment by stgraber** [comment]
Yeah, LXD"s involvement here is limited to passing a big blob from the user (user.network-config) to cloud-init through a file on the filesystem.

What's valid data is entirely up to cloud-init and related specifications (network stuff may involve nplan too nowadays).

So this should indeed be tracked entirely on Launchpad against cloud-init. If/When this is supported in cloud-init, things will just work without any change being needed on the LXD side.

**Comment by jfgibbins** [comment]
@stgraber @brauner Good morning Stephane and Christian.  I've added this over at launchpad under cloud-init and cloud-init(ubuntu).  They've been up for months.  I can't imagine it's more than a five minute task, and half a dozen lines of code, but it's not even been looked at.  TBH, both groups seem pretty dead.  Any ideas on where else this could be posted that is actually active?

**Comment by stgraber** [comment]
@smoser FYI ^

**Comment by smoser** [comment]
@jfgibbins can you point at a bug you opened ? sorry if we've missed it.

I'm not quite sure theres a lot we can do with 'sortlist' as we're kind of a middle man to the network configuration tool ( ifupdown/resolvconf in 16.04, 16.10 and netplan in 17.10+).

**Comment by jfgibbins** [comment]
#1704402
#1711967
@smoser Hey Scott, now it's been a while since I looked at this, but isn't cloud-init handling the writing of the resolv.conf for nameserver and domain search already?  This one just be adding one more line to the file.  At one point I could have sworn I found where the code was doing that part, but it's been a few months.  If not, please tell me which code is actually handling that, and I can get a bug report posted there.

**Comment by jfgibbins** [comment]
@smoser Well, I'm not following the same path I did before, but if I'm following the code right, cloudinit/distros/debian.py is calling the renderer, in this case cloudinit/net/eni.py which is actually writing the /etc/network/interfaces/50-cloud-init.cfg file.  If that's correct, it should just be adding dns-sortlist under def _iface_add_subnet(iface, subnet):  in eni.py?  As it stands now, the entry never makes it into the cfg for ifup/resolv to even know about.  According to the man resolvconf, dns-sortlist is a valid option to be passed to resolvconf from ifup, which I know works, cause if I manually add the parameter as such it shows up in resolv.conf.
iface lo inet loopback
    dns-nameservers x.x.x.x
    dns-search greywolfe.local greywolfe.org
    dns-sortlist x.x.x.x x.x.x.x
Honestly, I'd attempt a push/pull, whatever it's called on launchpad, but I still screw up my own git, and frankly, not a programmer, and would hate to butcher your code.

**Comment by jfgibbins** [comment]
P.S. and don't worry, not even going to touch the subject of modifying gai.conf for the networking through cloud-init.  Well, unless you get really bored, let me know. ;)
