### ISSUE TITLE
Feature request: Progress bar when copy a container between remotes

### ISSUE THREAD

**Issue by jmdelafe** [lxc/lxd#3554]
Hello,

I'm writing this issue to request the LXD's CLI show a status bar when copying a container from a LXD server to another one. Just the same way when you import an image to the local datastore.

Is it possible? There will be a usability improvement.

Thanks

**Comment by stgraber** [comment]
It's already there in current git master.

**Comment by stgraber** [comment]
ea5a3c12b66a09cd477de4b5089e65d03951456c

**Comment by jmdelafe** [comment]
Awesome!
