### ISSUE TITLE
"lxc image list" accepts characters after "remote:"

### ISSUE THREAD

**Issue by 1koval** [lxc/lxd#3555]
```
lxc image list [<remote>:] [filter] ...
```
command accepts characters after "\<remote\>:"

For example:

> lxc image list image:something 

This “something” is ignored and users may confuse it for an image "filter". 

For example:
```
lxc launch ubuntu:16.04
lxc image info ubuntu:16.04
lxc image list ubuntu:16.04
```
"launch" command starts container, "image info" prints information about the image while "image list" gives full list of all images.

To work it around you have to do it as: 
```
lxc image list ubuntu: 16.04
```
(add space after remote name to convert it to "filter")

This behavior is confusing. It would be nice to have more consistent behavior:
```
lxc image list [<remote>:[image]] [filter] ...
```
Implement "image" argument. 
Or, at least, print error if we get “something” after “remote:” to make it clear that it is not expected.

---
This can be reproduced 
@ https://linuxcontainers.org/lxd/try-it

Distribution:
   * Ubuntu 16.04.2 LTS
   * LXC/LXD version: 2.15

**Comment by stgraber** [comment]
We should make it behave like "lxc list" which treats both syntaxes the same.
