### ISSUE TITLE
lxc list throws errors under stress

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#356]
Running a launch of 100 containers (20 in parallel) and performing lxc list operations shows this stack every now and then:

```
 % lxc list
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a662a]

goroutine 16 [running]:
runtime.panic(0x7ffb80, 0xc28193)
	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
main.listContainers(0xc20803e140, 0xc208010600, 0x11, 0x20, 0x0, 0x0)
	/home/rharper/go/src/github.com/lxc/lxd/lxc/list.go:43 +0xcea
main.(*listCmd).run(0xc3f3c8, 0xc208026ff0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/rharper/go/src/github.com/lxc/lxd/lxc/list.go:104 +0x215
main.run(0x0, 0x0)
	/home/rharper/go/src/github.com/lxc/lxd/lxc/main.go:84 +0x8f8
main.main()
	/home/rharper/go/src/github.com/lxc/lxd/lxc/main.go:16 +0x26

goroutine 19 [finalizer wait]:
runtime.park(0x4bf0d0, 0xc3e978, 0xc2af09)
	/usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xc3e978, 0xc2af09)
	/usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 21 [runnable]:
net/http.(*persistConn).readLoop(0xc208040210)
	/usr/lib/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 22 [select]:
net/http.(*persistConn).writeLoop(0xc208040210)
	/usr/lib/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/pkg/net/http/transport.go:601 +0x957
```

**Comment by raharper** [comment]
And sometimes:

```
% lxc list
error: database is locked
```

**Comment by stgraber** [comment]
So for the second error, there's clearly a race if you're trying to list the containers at the same time one is being added to the DB. We should fix that by catching the locking error and retrying a few times.

**Comment by stgraber** [comment]
Most of the DB locking problem has now been fixed by Serge.

**Comment by hallyn** [comment]
Just noting here that the rest of this will be fixed by the go-sqlite3 db implmeenting retry-on-locked with customizable timeout.

**Comment by raharper** [comment]
in 0.6, when mix lxc list with parallel creation, I get;

lxc list outputs:
error: setting config item for the container failed

and then blocks indefinitely

GET on / and /1.0 block/fail.

**Comment by hallyn** [comment]
I *think* this should be solved with current git HEAD of both lxc and lxd.

**Comment by hallyn** [comment]
So currently I think the 'list' errors are fixed.  There is a bug with 'launch' sometimes not starting, and rharper hits a bug by re-trying start in a loop really fast on the same container, but those are i think different bugs, so i'd say this issue is closed (for 0.8).

**Comment by stgraber** [comment]
@raharper can you re-test this specific issue?

Would kinda like to have it finally closed :)

**Comment by raharper** [comment]
It's probably something else now but with the stress test we fail when we
hit open file limits.

Ryan

**Comment by raharper** [comment]
Testing with git head as of yesterday, the 50 container create and delete operation with 25 in parallel succeeds.  Larger runs with default open file limit (1024) breaks, but that's not directly related to the db issues we've seen.

**Comment by stgraber** [comment]
Very good to hear.
