### ISSUE TITLE
publish image with existing alias results in "error: Alias already exists: foo/bar"

### ISSUE THREAD

**Issue by jlec** [lxc/lxd#3560]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
```
# lxc info
config:
  core.https_address: #############
  core.proxy_http: ##############
  core.proxy_https: ##############
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - ##############
  architectures:
  - x86_64
  - i686
  certificate: |
    ##############
  certificate_fingerprint: ##############
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-79-generic
  server: lxd
  server_pid: 178457
  server_version: "2.15"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu16
```
# Issue description

I am trying to publish an image with an alias. If the alias exists I get an `error: Alias already exists: foo/bar`

# Steps to reproduce

```shell
# lxc init ubuntu:x x
Creating x
# lxc init ubuntu:z z
Creating z
# lxc publish x --alias foo/bar --public
Container published with fingerprint: 364ef9f83df74d3ac5abcf3e807d2e1f94270e15827b30fa731fdd09642d56c2
# lxc publish z --alias foo/bar --public
error: Alias already exists: foo/bar
```

**Comment by jlec** [comment]
Same happens when copying to `local:` from `remote:` with `--copy-aliases` when the alias locally exists

**Comment by stgraber** [comment]
The error seems accurate, what's the problem exactly?

**Comment by stgraber** [comment]
Is that a change from LXD 2.14's behavior?

**Comment by jlec** [comment]
> The error seems accurate, what's the problem exactly?
I am creating custom images for our platform and tag them. The images are prepared using ansible automation with a final step of publishing and tagging. The playbook used to work in the past, but got broken now.

> Is that a change from LXD 2.14's behavior?
Yes, I cannot confirm which version broke it, but in the 2.12/13 era it used to work.

**Comment by stgraber** [comment]
Ok. I think the current behavior is correct at the API level, but we should probably change our client tool so that it behaves as it did before by having it apply the aliases after everything is done and removing any existing alias for you.
