### ISSUE TITLE
Stateful flag not set when moving stateful snapshot

### ISSUE THREAD

**Issue by R3curve** [lxc/lxd#3570]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info":
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.12.1-041201-generic
  server: lxd
  server_pid: 2823
  server_version: "2.14"
  storage: dir
  storage_version: "1"

# Issue description

If I move a stateful snapshot of a container from one LXD host to another via `lxc move c1/snap0 dst:c1`, I cannot restore the container statefully. I had a look at the lxd.db and the problem seems to be that the `stateful` flag in the `containers` table is not set. Setting the flag manually resolves the issue.

# Steps to reproduce

 1. src# lxc snapshot c1 --stateful
 2. src# lxc move c1/snap0 dst:c1
 3. dst# lxc start c1

**Comment by R3curve** [comment]
I am sorry that I was not on the latest version but I updated now and I am still experiencing the same issue.

**Comment by brauner** [comment]
@albertodonato care to chime in?

**Comment by brauner** [comment]
@albertodonato, sorry pinged you a) on the wrong issue and b) closed the wrong issue, sorry.

**Comment by brauner** [comment]
@R3curve, can you show me the output of:

    lxc info c1

please?

**Comment by R3curve** [comment]
Name: c1
Remote: unix://
Architecture: x86_64
Created: 2017/07/19 06:32 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 2872
Ips:
  eth0:	inet	10.0.0.10	veth0
  eth0:	inet6	fe80::24b3:90ff:fe78:835d	veth0
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 58
  CPU usage:
    CPU usage (in seconds): 18
  Memory usage:
    Memory (current): 278.83MB
    Memory (peak): 285.45MB
  Network usage:
    eth0:
      Bytes received: 9.74MB
      Bytes sent: 9.84MB
      Packets received: 210744
      Packets sent: 211568
    lo:
      Bytes received: 198.77kB
      Bytes sent: 198.77kB
      Packets received: 2132
      Packets sent: 2132
Snapshots:
  snap1 (taken at 2017/07/21 05:47 UTC) (stateful)

**Comment by brauner** [comment]
Cheers, I think I narrowed the problem down a bit.

**Comment by brauner** [comment]
@stgraber, did we ever support this?

**Comment by stgraber** [comment]
No idea. But I can't think of a reason why it shouldn't be. So long as the target container has the same name as the source. We don't allow live migration/restore with a name change as that breaks apparmor and a whole lot of other stuff.
