### ISSUE TITLE
Client certificate creation on Windows bootstrapping

### ISSUE THREAD

**Issue by sergiusens** [lxc/lxd#3573]
Downloading the latest lxc client build for Windows and trying to add a remote fails when trying to store the certificate as the path does not exist (it seems to also additionally not be the best location altogether).

```
C:\Users\sergiusens>lxc remote add ubuntu-server 10.155.9.157:8443
Generating a client certificate. This may take a minute...
2017/07/19 12:40:34 failed to open \.config\lxc\client.crt for writing: open \.config\lxc\client.crt: The system cannot find the path specified.

C:\Users\sergiusens>mkdir c:\.config

C:\Users\sergiusens>mkdir c:\.config\lxc

C:\Users\sergiusens>lxc remote add ubuntu-server 10.155.9.157:8443
Generating a client certificate. This may take a minute...
Certificate fingerprint: 64704cee37dc5f59cc96a83399a7e57df9420864ddcff178e6751cad8250b842
ok (y/n)? y
```

**Comment by stgraber** [comment]
I'll take care of this one since I have a Windows system setup for this kind of stuff.

May have to wait until I'm back home though, not sure how usable my win10 system will be over VPN from Europe :)
