### ISSUE TITLE
lxc exec hangs on command that exited inside the container

### ISSUE THREAD

**Issue by cpaelzer** [lxc/lxd#3575]
Hi,
I recently found an issue that seems to occur every few days in our test automation which heavily uses lxd. It spawns commands via ``lxc exec <cmd>`` and from the view inside the container the command is finished (no process anymore), but the host is waiting forever.

I debugged a bit with @brauner but we ended needing more debug logs.
Today the issue triggered again while debug logging was active, therefore filing this issue with all data we have so far.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * lxc info:
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
   [...]
  certificate_fingerprint: 3c80197437b99daad4967475e9feec0f936c1a3d5dec5791a3adbaa9d125ef88
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-83-generic
  server: lxd
  server_pid: 502
  server_version: "2.15"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu16

   * LXC version:
     ii  lxc            2.0.8-0ubuntu3~ubuntu16.04.1~ppa1
   * LXD version:
     ii  lxd            2.15-0ubuntu6~ubuntu16.04.1~ppa1
    Both from http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu

# Issue description

- Issue occurs on different places/commands, so it is impossible to harden/debug a specific command for it
 - on the host lxc exec hangs in futex_wait_queue_me or ep_poll wchan
 - but in the guest view the process is gone

Example of a normal "good" case:
`  $ lxc exec artful-test -- sleep 5m`
```
  host view ps axlf:
  0  1000  6847 15329  20   0  38692 17648 wait   Ss   pts/10     0:00  \_ /bin/bash
  0  1000  7233  6847  20   0 144048 11140 futex_ Sl+  pts/10     0:00  |   \_ lxc exec artful-test -- sleep 5m
```
```
  guest view ps axlf
  4     0 17933     0  20   0   9804   664 hrtime Ss+  ?          0:00 sleep 5m
 # once the guest process exits, lxc exec returns
```
  
But in the error case the host still waits for the container process the same way:
```
  # Host view ps axlf
  0  1001  4243  4138  20   0 340244  3628 futex_ Sl   ?          0:00  |           \_ lxc exec testkvm-trusty-from -- nmap -Pn 192.168.122.0/24
  # guest view shows no trace of the nmap process
```

# Steps to reproduce

- not clear yet, running lxc exec often and a rather highly loaded machine is all we know so far.

# Information to attach

After the initial discussion we enabled --debug, the case that hang again then interstingly did not hang on the same futex, instead it was on `ep_poll` this time.

```
# On the Host this time:
0  1001 22584 32543  20   0 200176  6452 ep_pol Sl   ?          0:00  |       \_ lxc exec testkvm-xenial-from --env DEBIAN_FRONTEND=noninteractive -- apt-get --assume-yes --allow-unauthenticated -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install uvtool uvtool-libvirt openssh-server
# Guest again has no trace of the related process
```

The last timestamp I had before that was "02:38:14".
So I'll be adding the logs from that day (compressing the larger ones)
Logs are:
- lxd.log: daemon log (in debug mode)
- lxc-mon.log: lxc monitor
- lxc.log: per container log from /var/log/<container>/lxc.log
- lxc.conf: per container log from /var/log/<container>/lxc.conf
- trigger.log: output of the automation triggering the case (last command doing lxc exec is the one hanging)
- kern.log: dmesg of that day

**Comment by brauner** [comment]
@cpaelzer, I think you forgot to paste/append the logs. :)

**Comment by cpaelzer** [comment]
Need to find a way for the huge logs, but here the others so far:
[kern.txt](https://github.com/lxc/lxd/files/1162163/kern.txt)
[lxc.conf.txt](https://github.com/lxc/lxd/files/1162164/lxc.conf.txt)
[lxc.txt](https://github.com/lxc/lxd/files/1162165/lxc.txt)
[trigger.txt](https://github.com/lxc/lxd/files/1162166/trigger.txt)

**Comment by cpaelzer** [comment]
Needed to re-compress as zip so GH accepts them:
[lxc-mon.txt.zip](https://github.com/lxc/lxd/files/1162196/lxc-mon.txt.zip)
[lxd.txt.zip](https://github.com/lxc/lxd/files/1162197/lxd.txt.zip)

**Comment by cpaelzer** [comment]
In case you need to filter the huge logs - the guest that hung on the case the lgos are from was "testkvm-xenial-from"

**Comment by brauner** [comment]
@stgraber that sounds like locking that you've implemented in the non-interactive codepath. Did you change anything obvious that could cause this which springs to mind?

**Comment by stgraber** [comment]
@brauner nope, nothing obvious comes to mind. There was a bad lock in there a while back, but I thought that all got fixes in 2.15.

**Comment by stgraber** [comment]
@cpaelzer is this something you're still running into? And if so, can you confirm that you did run into this on either LXD 2.20 or LXD 2.0.11?

Want to check if our recent exec fixes have somehow fixed this.

**Comment by cpaelzer** [comment]
Hi we are on 2.20-0ubuntu4~16.04.1~ppa1 since 2017-11-18.
The logs hold no such case since then, so it either got less common or is fully fixed.
I think we can close the bug for now, I can reopen if I find it again.
