### ISSUE TITLE
C Malloc failed on Alpine Edge

### ISSUE THREAD

**Issue by SIN3R6Y** [lxc/lxd#3581]
# Required information

 * Alpine Linux:
 * Edge:
 * The output of "lxc info" or if that fails: LXD wont start, so it fails
   * Kernel version: 4.9.37 (GRSec)
   * LXC version: 2.15
   * LXD version: 2.15 
   * Storage backend in use: ZFS

# Issue description

This may end up being a go issue? Basically after aswering all questions from lxc-init LXD crashes with the following backtrace.

> localhost:# lxd
WARN[07-23|01:46:52] AppArmor support has been disabled because of lack of kernel support
WARN[07-23|01:46:52] CGroup memory swap accounting is disabled, swap limits will be ignored.
fatal error: runtime: C malloc failed
goroutine 1 [running]:
runtime.throw(0x719f96630ab, 0x18)
        /usr/lib/go/src/runtime/panic.go:596 +0x97 fp=0xc4200e0c40 sp=0xc4200e0c20
github.com/lxc/lxd/shared._cgo_cmalloc(0xffffffffffffffff, 0x0)
        github.com/lxc/lxd/shared/_obj/_cgo_gotypes.go:226 +0x79 fp=0xc4200e0c70 sp=0xc4200e0c40
github.com/lxc/lxd/shared._Cfunc__CMalloc(0xffffffffffffffff, 0xffffffffffffffff)
        github.com/lxc/lxd/shared/_obj/_cgo_gotypes.go:88 +0x2d fp=0xc4200e0c90 sp=0xc4200e0c70
github.com/lxc/lxd/shared.UserId(0x719f9653e85, 0x3, 0x0, 0x0, 0x0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/shared/util_linux.go:295 +0xaf fp=0xc4200e0d38 sp=0xc4200e0c90
main.(*network).Start(0xc420156100, 0xc420154500, 0x6)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/networks.go:1179 +0x27b7 fp=0xc4200e3480 sp=0xc4200e0d38
main.networkStartup(0xc420073440, 0x0, 0x0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/networks.go:413 +0xcd fp=0xc4200e3538 sp=0xc4200e3480
main.(*Daemon).Init(0xc420073440, 0xc420073440, 0x0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:823 +0x345a fp=0xc4200e3d08 sp=0xc4200e3538
main.cmdDaemon(0x0, 0x0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main_daemon.go:57 +0x1dd fp=0xc4200e3e18 sp=0xc4200e3d08
main.run(0xc4200f87e0, 0x0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main.go:248 +0x488 fp=0xc4200e3f18 sp=0xc4200e3e18
main.main()
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main.go:54 +0x28 fp=0xc4200e3f88 sp=0xc4200e3f18
runtime.main()
        /usr/lib/go/src/runtime/proc.go:185 +0x212 fp=0xc4200e3fe0 sp=0xc4200e3f88
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200e3fe8 sp=0xc4200e3fe0
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1
goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go/src/runtime/sigqueue.go:116 +0x106
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x24
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x43
goroutine 6 [chan receive]:
database/sql.(*DB).connectionOpener(0xc4201186e0)
        /usr/lib/go/src/database/sql/sql.go:837 +0x4c
created by database/sql.Open
        /usr/lib/go/src/database/sql/sql.go:582 +0x214

These two lines look strange to me, granted i know very little about Go, but these malloc's do not look right to me.

>github.com/lxc/lxd/shared._cgo_cmalloc(0xffffffffffffffff, 0x0)
        github.com/lxc/lxd/shared/_obj/_cgo_gotypes.go:226 +0x79 fp=0xc4200e0c70 sp=0xc4200e0c40
github.com/lxc/lxd/shared._Cfunc__CMalloc(0xffffffffffffffff, 0xffffffffffffffff)
        github.com/lxc/lxd/shared/_obj/_cgo_gotypes.go:88 +0x2d fp=0xc4200e0c90 sp=0xc4200e0c70

If you skip networking during lxd-init ...

> Would you like to create a new network bridge (yes/no) [default=yes]? no

 lxd will start fine and run containers fine. But you can't lxc exec, that gives errors as well.

> localhost:# lxc launch -c security.privileged=true images:alpine/edge/amd64 test
Creating test
The container you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to a container, use: lxc network attach
Starting test
localhost:# lxc exec test -- /bin/ash
error: EOF
localhost:~#

This is the error that is printed in the LXD daemon log at the same time as the lxc exec

> EROR[07-23|02:05:27] Failed to retrieve PID of executing child process: EOF

I suspect an issue with Go here, but i am not certain.

# Steps to reproduce

 1. Install Alpine Edge && LXD from testing repo
 2. run lxd init
 3. if you skip network creation, run lxc exec against a container

# Information to attach

**When running lxc exec lxc --debug logs appear irrelevant, this is lxd --debug log**

> DBUG[07-23|02:15:54] Connected websocket operation: 97f47a62-57fc-4777-a23f-e70682ea5ad6
DBUG[07-23|02:15:54] Handled websocket operation: 97f47a62-57fc-4777-a23f-e70682ea5ad6
DBUG[07-23|02:15:54] handling                                 ip=@ method=GET url=/1.0/operations/97f47a62-57fc-4777-a23f-e70682ea5ad6
DBUG[07-23|02:15:54]
        {
                "type": "sync",
                "status": "Success",
                "status_code": 200,
                "operation": "",
                "error_code": 0,
                "error": "",
                "metadata": {
                        "id": "97f47a62-57fc-4777-a23f-e70682ea5ad6",
                        "class": "websocket",
                        "created_at": "2017-07-23T02:15:54.041838253-04:00",
                        "updated_at": "2017-07-23T02:15:54.041838253-04:00",
                        "status": "Running",
                        "status_code": 103,
                        "resources": {
                                "containers": [
                                        "/1.0/containers/test"
                                ]
                        },
                        "metadata": {
                                "fds": {
                                        "0": "0f953741efb975a4ed219fc39baf7b34fb8ec4a93b9280dab6db791a605f1fd0",
                                        "1": "ba45121735a004fd68354f83801acdd21584d05a282d7e7a6ed5e7b4a2f4c33c",
                                        "2": "7a8493fee7a4884e0b1d7bde3cc1ac08d19db03aac0e2dd87bb7f571fcb9d200",
                                        "control": "f3645af5791b351c2dae6dcf65693482c599e07684679b88383adec8a27d381d"
                                }
                        },
                        "may_cancel": false,
                        "err": ""
                }
        }
EROR[07-23|02:15:54] Failed to retrieve PID of executing child process: EOF
DBUG[07-23|02:15:54] Failure for websocket operation: 97f47a62-57fc-4777-a23f-e70682ea5ad6: EOF
DBUG[07-23|02:15:54] Got error getting next reader websocket: close 1006 (abnormal closure): unexpected EOF, &{%!s(*os.file=&{14 slave <nil>})}

**When LXD crashes during lxd init with -- debug enabled**

> DBUG[07-23|02:25:51] Scheduler: network: lxdbr0 has been added: updating network priorities
fatal error: runtime: C malloc failed
goroutine 166 [running]:
runtime.throw(0xc6b1bdef0ab, 0x18)
        /usr/lib/go/src/runtime/panic.go:596 +0x97 fp=0xc4201f1060 sp=0xc4201f1040
github.com/lxc/lxd/shared._cgo_cmalloc(0xffffffffffffffff, 0x0)
        github.com/lxc/lxd/shared/_obj/_cgo_gotypes.go:226 +0x79 fp=0xc4201f1090 sp=0xc4201f1060
github.com/lxc/lxd/shared._Cfunc__CMalloc(0xffffffffffffffff, 0xffffffffffffffff)
        github.com/lxc/lxd/shared/_obj/_cgo_gotypes.go:88 +0x2d fp=0xc4201f10b0 sp=0xc4201f1090
github.com/lxc/lxd/shared.UserId(0xc6b1bddfe85, 0x3, 0x0, 0x0, 0x0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/shared/util_linux.go:295 +0xaf fp=0xc4201f1158 sp=0xc4201f10b0
main.(*network).Start(0xc420047f80, 0xc4200f4db0, 0x6)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/networks.go:1179 +0x27b7 fp=0xc4201f38a0 sp=0xc4201f1158
main.networksPost(0xc4200718c0, 0xc42000ac00, 0x6e528d496e40, 0xc420047740)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/networks.go:141 +0x672 fp=0xc4201f3a28 sp=0xc4201f38a0
main.(*Daemon).createCmd.func1(0xc6b1c4bc820, 0xc4200c82a0, 0xc42000ac00)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:260 +0x7d4 fp=0xc4201f3b78 sp=0xc4201f3a28
net/http.HandlerFunc.ServeHTTP(0xc42023ca00, 0xc6b1c4bc820, 0xc4200c82a0, 0xc42000ac00)
        /usr/lib/go/src/net/http/server.go:1942 +0x46 fp=0xc4201f3ba0 sp=0xc4201f3b78
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420207090, 0xc6b1c4bc820, 0xc4200c82a0, 0xc42000ac00)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/gorilla/mux/mux.go:114 +0x10e fp=0xc4201f3ca0 sp=0xc4201f3ba0
main.(*lxdHttpServer).ServeHTTP(0xc42029f1d0, 0xc6b1c4bc820, 0xc4200c82a0, 0xc42000a900)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:1394 +0x239 fp=0xc4201f3d10 sp=0xc4201f3ca0
net/http.serverHandler.ServeHTTP(0xc4202a02c0, 0xc6b1c4bc820, 0xc4200c82a0, 0xc42000a900)
        /usr/lib/go/src/net/http/server.go:2568 +0x94 fp=0xc4201f3d58 sp=0xc4201f3d10
net/http.(*conn).serve(0xc4200b8640, 0xc6b1c4bd120, 0xc420046180)
        /usr/lib/go/src/net/http/server.go:1825 +0x614 fp=0xc4201f3fc8 sp=0xc4201f3d58
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4201f3fd0 sp=0xc4201f3fc8
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2668 +0x2d0
goroutine 1 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc42029e48c)
        /usr/lib/go/src/runtime/sema.go:47 +0x36
sync.(*WaitGroup).Wait(0xc42029e480)
        /usr/lib/go/src/sync/waitgroup.go:131 +0x7c
main.cmdDaemon(0x0, 0x0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main_daemon.go:105 +0x344
main.run(0xc4200f67e0, 0x0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main.go:248 +0x488
main.main()
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main.go:54 +0x28
goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1
goroutine 5 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
        /usr/lib/go/src/runtime/sigqueue.go:116 +0x106
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x24
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x43
goroutine 6 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc42012e640)
        /usr/lib/go/src/database/sql/sql.go:837 +0x4c
created by database/sql.Open
        /usr/lib/go/src/database/sql/sql.go:582 +0x214
goroutine 32 [select, 1 minutes]:
main.(*Daemon).Ready.func2(0xc4200718c0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:1095 +0x20a
created by main.(*Daemon).Ready
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:1108 +0xd9
goroutine 31 [select, 1 minutes]:
main.(*Daemon).Ready.func1(0xc4200718c0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:1067 +0x151
created by main.(*Daemon).Ready
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:1077 +0x81
goroutine 30 [IO wait]:
net.runtime_pollWait(0x6e528d48d2f8, 0x72, 0x0)
        /usr/lib/go/src/runtime/netpoll.go:164 +0x5b
net.(*pollDesc).wait(0xc420296378, 0x72, 0x0, 0xc4200a8b00)
        /usr/lib/go/src/net/fd_poll_runtime.go:75 +0x3a
net.(*pollDesc).waitRead(0xc420296378, 0xffffffffffffffff, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:80 +0x36
net.(*netFD).accept(0xc420296310, 0x0, 0xc6b1c4b76a0, 0xc4200a8b00)
        /usr/lib/go/src/net/fd_unix.go:430 +0x1e7
net.(*UnixListener).accept(0xc42027ea80, 0xc420035e28, 0xc6b1b9b4b50, 0xc6b1b77b660)
        /usr/lib/go/src/net/unixsock_posix.go:162 +0x34
net.(*UnixListener).Accept(0xc42027ea80, 0xc6b1c255980, 0xc4200b8640, 0xc6b1c4bd1e0, 0xc4202ba690)
        /usr/lib/go/src/net/unixsock.go:237 +0x4b
net/http.(*Server).Serve(0xc4202a02c0, 0xc6b1c4bc6a0, 0xc42027ea80, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:2643 +0x22a
net/http.Serve(0xc6b1c4bc6a0, 0xc42027ea80, 0xc6b1c4b6ae0, 0xc42029f1d0, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:2307 +0x7a
main.(*Daemon).Init.func6(0x0, 0xc6b1b75929a)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:1040 +0x9d
gopkg.in/tomb%2ev2.(*Tomb).run(0xc420071938, 0xc42029e110)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/gopkg.in/tomb.v2/tomb.go:163 +0x2d
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/gopkg.in/tomb.v2/tomb.go:159 +0xd4
goroutine 23 [chan receive, 1 minutes]:
main.(*Daemon).Init.func2(0xc4200718c0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:847 +0xf5
created by main.(*Daemon).Init
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:849 +0x1339
goroutine 27 [select]:
main.deviceEventListener(0xc4200718c0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/devices.go:745 +0x6a9
created by main.(*Daemon).Init
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:883 +0x2cb0
goroutine 26 [IO wait, 1 minutes]:
net.runtime_pollWait(0x6e528d48d3b8, 0x72, 0x0)
        /usr/lib/go/src/runtime/netpoll.go:164 +0x5b
net.(*pollDesc).wait(0xc42014eca8, 0x72, 0x0, 0xc4202bc4c0)
        /usr/lib/go/src/net/fd_poll_runtime.go:75 +0x3a
net.(*pollDesc).waitRead(0xc42014eca8, 0xffffffffffffffff, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:80 +0x36
net.(*netFD).accept(0xc42014ec40, 0x0, 0xc6b1c4b76a0, 0xc4202bc4c0)
        /usr/lib/go/src/net/fd_unix.go:430 +0x1e7
net.(*UnixListener).accept(0xc4201fd8c0, 0xc4202ba5a0, 0xc6b1c1ae5c0, 0xc6b1c4a2ee0)
        /usr/lib/go/src/net/unixsock_posix.go:162 +0x34
net.(*UnixListener).Accept(0xc4201fd8c0, 0xc4202ba570, 0xc6b1c1ae5c0, 0xc6b1c4a2ee0, 0xc6b1c200740)
        /usr/lib/go/src/net/unixsock.go:237 +0x4b
net/http.(*Server).Serve(0xc4202a0210, 0xc6b1c4bc6a0, 0xc4201fd8c0, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:2643 +0x22a
main.(*Daemon).Init.func3(0xc6b1c1834e0, 0xc4201d64e0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/daemon.go:878 +0x5c
gopkg.in/tomb%2ev2.(*Tomb).run(0xc420071938, 0xc4202003f0)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/gopkg.in/tomb.v2/tomb.go:163 +0x2d
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/gopkg.in/tomb.v2/tomb.go:159 +0xd4
goroutine 167 [IO wait]:
net.runtime_pollWait(0x6e528d48d178, 0x72, 0x9)
        /usr/lib/go/src/runtime/netpoll.go:164 +0x5b
net.(*pollDesc).wait(0xc420048298, 0x72, 0xc6b1c4b8ea0, 0xc6b1c4b4050)
        /usr/lib/go/src/net/fd_poll_runtime.go:75 +0x3a
net.(*pollDesc).waitRead(0xc420048298, 0xc420046291, 0x1)
        /usr/lib/go/src/net/fd_poll_runtime.go:80 +0x36
net.(*netFD).Read(0xc420048230, 0xc420046291, 0x1, 0x1, 0x0, 0xc6b1c4b8ea0, 0xc6b1c4b4050)
        /usr/lib/go/src/net/fd_unix.go:250 +0x1b9
net.(*conn).Read(0xc42000e058, 0xc420046291, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:181 +0x72
net/http.(*connReader).backgroundRead(0xc420046280)
        /usr/lib/go/src/net/http/server.go:656 +0x5a
created by net/http.(*connReader).startBackgroundRead
        /usr/lib/go/src/net/http/server.go:652 +0xe1
goroutine 37 [chan receive, 1 minutes]:
main.cmdDaemon.func2(0xc4200718c0, 0xc42029e470, 0xc42029e480)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main_daemon.go:72 +0xd2
created by main.cmdDaemon
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main_daemon.go:80 +0x2ca
goroutine 38 [chan receive, 1 minutes]:
main.cmdDaemon.func3(0xc4200718c0, 0xc42029e470, 0xc42029e480)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main_daemon.go:83 +0x4d
created by main.cmdDaemon
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main_daemon.go:91 +0x300
goroutine 39 [chan receive, 1 minutes]:
main.cmdDaemon.func4(0xc42029e470, 0xc4200718c0, 0xc42029e480)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main_daemon.go:98 +0x1ab
created by main.cmdDaemon
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/main_daemon.go:103 +0x336
goroutine 40 [select, 1 minutes, locked to thread]:
runtime.gopark(0xc6b1c255fa0, 0x0, 0xc6b1bde1a7f, 0x6, 0x18, 0x2)
        /usr/lib/go/src/runtime/proc.go:271 +0x140
runtime.selectgoImpl(0xc420033f50, 0x0, 0x18)
        /usr/lib/go/src/runtime/select.go:423 +0x1368
runtime.selectgo(0xc420033f50)
        /usr/lib/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /usr/lib/go/src/runtime/signal_unix.go:434 +0x2e3
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1
goroutine 44 [syscall]:
syscall.Syscall(0x0, 0x7, 0xc4202c4000, 0x1000, 0x9b00000000000002, 0x4, 0x9b7bad576528c10c)
        /usr/lib/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x7, 0xc4202c4000, 0x1000, 0x1000, 0xc6b1c4aa830, 0x2, 0xc420122b40)
        /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:783 +0x57
syscall.Read(0x7, 0xc4202c4000, 0x1000, 0x1000, 0xc420122be8, 0x0, 0x2)
        /usr/lib/go/src/syscall/syscall_unix.go:162 +0x4b
main.deviceNetlinkListener.func1(0x800, 0x7, 0xc42028d440, 0xc42028d4a0, 0xc42028d500)
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/devices.go:339 +0xb0
created by main.deviceNetlinkListener
        /home/buildozer/aports/testing/lxd/src/lxd-2.15/dist/src/github.com/lxc/lxd/lxd/devices.go:452 +0x1e5

**Comment by brauner** [comment]
I'd need to see the signature for cgo_malloc but it looks like somehow the go runtime is convinced it needs to allocate uint64 max bytes.

**Comment by SIN3R6Y** [comment]
@brauner or perhaps this is an underflow?

**Comment by tv42** [comment]
You're passing -1 to `malloc` in lxd.
http://man7.org/linux/man-pages/man3/getpwnam.3.html
https://github.com/lxc/lxd/blob/db01a07f42ffed29abc80ca316aa183122c61315/shared/util_linux.go#L294-L295

**Comment by brauner** [comment]
Who the hell wrote that? :D
