### ISSUE TITLE
Clarification on Image publishing and auto-updating

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#3583]
Hi there,

I have recently been messing around with image publishing and updating, and I cannot quite grasp what is going on. The docs and information I find out there do not seem to align with reality, as far as I can see it - but it is entirely possible I have misunderstood how everything works :)

**Desired behavior:**

1. I should be able to update and publish an image in my image server which
2. Then will get automatically used whenever a remote client provisions a container based on said image

Pretty simple, right? 

**How I update images**

I have set up an image server, where I have a "base" container which I modify and publish as my image. I have been using two different approaches to publish my image - one "safe" approach, and another more direct approach. The "safe" way is:

`lxc stop template-xlamp7; lxc publish template-xlamp7 --alias=temporary-alias --public;`

I now test that I can provision a container from my temporary image and that all is well, then I do:

`lxc image delete xenial-lamp-php7; lxc image alias delete temporary-alias; lxc image alias create xenial-lamp-php7 80374647d105;`

Where the stuff at the end there is my updated image fingerprint.

The other way is where I just publish it "directly":

`lxc stop template-xlamp7; lxc image delete xenial-lamp-php7;  lxc publish template-xlamp7 --alias=xenial-lamp-php7 --public;`

Now if I do an lxc image list on my image server, the new image is listed as the only one with the designated alias, and all seems to be well.

**What happens at the other end**

On my target system, I had initially done 

`lxc image copy krellide:xenial-lamp-php7 local: --copy-aliases --auto-update`

Where krellide is my image server which I've added with 

`lxc remote add krellide somewhere.io --public`

In any case - after having made an update to my image, and published it and then on my target system here provisioned a new container using

`lxd init krellide:xenial-lamp-php7 somename` 

I now see when doing lxc image list

```
+--------------------------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|          ALIAS           | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 |  ARCH  |   SIZE   |          UPLOAD DATE          |
+--------------------------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
| xenial-lamp-php7 | 4cb79028ab7d | no     |                                             | x86_64 | 718.01MB | Jun 20, 2017 at 8:54pm (UTC)  |
+--------------------------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|                          | 07481150a253 | no     | Debian wheezy amd64 (20170505_09:10)        | x86_64 | 86.21MB  | Jun 21, 2017 at 8:41pm (UTC)  |
+--------------------------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|                          | 8fa08537ae51 | no     | ubuntu 16.04 LTS amd64 (release) (20170516) | x86_64 | 153.70MB | May 17, 2017 at 7:56pm (UTC)  |
+--------------------------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|                          | 8220e89e33e6 | no     | ubuntu 16.04 LTS amd64 (release) (20170721) | x86_64 | 153.94MB | Jul 22, 2017 at 1:53pm (UTC)  |
+--------------------------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|                          | 55a10140362c | no     | ubuntu 17.04 amd64 (release) (20170615)     | x86_64 | 158.51MB | Jun 16, 2017 at 7:57pm (UTC)  |
+--------------------------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|                          | 80374647d105 | no     |                                             | x86_64 | 571.18MB | Jul 24, 2017 at 12:01pm (UTC) |
+--------------------------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|                          | cd7815f09be3 | no     |                                             | x86_64 | 571.19MB | Jul 24, 2017 at 12:14pm (UTC) |
+--------------------------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
```

**So what's going on here?**

It seems to me that the originally imported image alias using `lxc image copy krellide:xenial-lamp-php7 local: --copy-aliases --auto-update` is being kept around for some reason. Then later on, as you can see near the bottom with fingerprints 80374647d105 and cd7815f09be3 it seems as if LXD is simply grabbing the updated image and not deleting the old one from the image store.

**Questions**

1. Why isn't LXD deleting the old images from the image store, as per the docs? 
2. How come LXD isn't copying and listing the alias when doing lxd image list after doing lxd init remote:alias ? Is this maybe the reason why I'm seeing this strange behavior? In any case, maybe this is a feature request, as it would be nice if LXD were to copy and list the alias in question (I guess I could just add a description to my images, which would make them easier to identify)
3. Or is it, rather, something I'm doing wrong on the image server side, which is causing this behavior
4. Or is it really nothing to worry about and LXD will clean up these old images from the image store eventually?

It would be great to get a bit of clarity to my confusion, and maybe some hints to best practices here, in case I'm fucking things up :)

**Comment by Kramerican** [comment]
I think I've finally found it. As per this issue:

[https://github.com/lxc/lxd/issues/1366](https://github.com/lxc/lxd/issues/1366)

It seems images expire after 10 days. I'll probably mess with that setting.

And my other worry - not being able to identify easily what images are what when doing lxc image list on target systems - can be solved by adding a description to my images after publishing.

Right? :O)

If so: Thank you for your time and feel free to close this! Haha..

**Comment by brauner** [comment]
Yes :)

**Comment by Kramerican** [comment]
Haha

Loving the short and to-the-point reply. Anyway, I just thought of one final question in connection with this:

Is our "old friend" the problem where ZFS mount points get messed up when images are deleted affected by LXD auto-deletion of old images?

[https://github.com/lxc/lxd/issues/3331#issuecomment-306884039](https://github.com/lxc/lxd/issues/3331#issuecomment-306884039)

Meaning, if I have provisioned a container from a remote alias - later that image is updated and the original image used to provision that container is auto-deleted/expired by LXD ... Would that problem crop up?
