### ISSUE TITLE
What could prevent updating the local LXD image cache with new image from remote image server?

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#3590]
Hello

My adventures in LXD image handling continues. Still on LXD v2.15. 

**What I am seeing**

1. Update an image and publish with new fingerprint on my image server
2. do `lxd init krellide:xenial-lemp-php7 test` on a target host system

LXD log in /var/log/lxd/lxd.log shows

> etag= lvl=info method=GET msg="Sending request to LXD" t=2017-07-25T22:42:38+0200 url=https://krellide.mysite.io:8443/1.0
> etag= lvl=info method=GET msg="Sending request to LXD" t=2017-07-25T22:42:41+0200 url=https://krellide.mysite.io:8443/1.0/images/aliases/xenial-lemp-php71
> etag= lvl=info method=GET msg="Sending request to LXD" t=2017-07-25T22:42:44+0200 url=https://krellide.mysite.io:8443/1.0/images/b5946320809384a25a2b6dc798340e084acf8eb9e67318cb99f17dcc825bc98b
> ephemeral=false lvl=info msg="Creating container" name=test t=2017-07-25T22:42:47+0200

The fingerprint shown - `b5946320809384a25a2b6dc798340e084acf8eb9e67318cb99f17dcc825bc98b` - is the correct fingerprint for the updated image on my image server, **but no updated image is being downloaded**, and `lxc image list` on the target system after provisioning just shows the old image

>|       | 63b7f9e580f6 | no     | Ubuntu LEMP PHP7.1                  | x86_64 | 790.74MB | Jul 25, 2017 at 7:25pm (UTC)  |

**Expected behavior:** From all I have seen and been told, the target system should download the new image. The log indicates it is being returned the correct, new, fingerprint. 

What might be going on? Related to the certicate stuff we looked at briefly?

**Comment by stgraber** [comment]
Can you post:
 - lxc remote list
 - lxc image list krellide:

**Comment by Kramerican** [comment]
Of course :)

```
# lxc remote list
+-----------------+------------------------------------------+---------------+--------+--------+
|      NAME       |                   URL                    |   PROTOCOL    | PUBLIC | STATIC |
+-----------------+------------------------------------------+---------------+--------+--------+
| images          | https://images.linuxcontainers.org       | simplestreams | YES    | NO     |
+-----------------+------------------------------------------+---------------+--------+--------+
| krellide        | https://krellide.webdock.io:8443         | lxd           | YES    | NO     |
+-----------------+------------------------------------------+---------------+--------+--------+
| local (default) | unix://                                  | lxd           | NO     | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
| ubuntu          | https://cloud-images.ubuntu.com/releases | simplestreams | YES    | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
| ubuntu-daily    | https://cloud-images.ubuntu.com/daily    | simplestreams | YES    | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
```

```
 # lxc image list krellide:
+---------------------------+--------------+--------+----------------------------+--------+----------+-------------------------------+
|           ALIAS           | FINGERPRINT  | PUBLIC |        DESCRIPTION         |  ARCH  |   SIZE   |          UPLOAD DATE          |
+---------------------------+--------------+--------+----------------------------+--------+----------+-------------------------------+
| webdock-xenial-lamp-php7  | d9ada5c1e2cc | yes    | Webdock Ubuntu LAMP PHP7   | x86_64 | 571.19MB | Jul 24, 2017 at 12:54pm (UTC) |
+---------------------------+--------------+--------+----------------------------+--------+----------+-------------------------------+
| webdock-xenial-lemp-php71 | b59463208093 | yes    | Webdock Ubuntu LEMP PHP7.1 | x86_64 | 790.01MB | Jul 25, 2017 at 8:34pm (UTC)  |
+---------------------------+--------------+--------+----------------------------+--------+----------+-------------------------------+

```

and lxc image list for good measure:

```
# lxc image list
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 |  ARCH  |   SIZE   |          UPLOAD DATE          |
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|       | 07481150a253 | no     | Debian wheezy amd64 (20170505_09:10)        | x86_64 | 86.21MB  | Jun 21, 2017 at 8:41pm (UTC)  |
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|       | 55a10140362c | no     | ubuntu 17.04 amd64 (release) (20170615)     | x86_64 | 158.51MB | Jun 16, 2017 at 7:57pm (UTC)  |
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|       | 63b7f9e580f6 | no     | Webdock Ubuntu LEMP PHP7.1                  | x86_64 | 790.74MB | Jul 25, 2017 at 7:25pm (UTC)  |
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|       | 80374647d105 | no     |                                             | x86_64 | 571.18MB | Jul 24, 2017 at 12:01pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|       | 8220e89e33e6 | no     | ubuntu 16.04 LTS amd64 (release) (20170721) | x86_64 | 153.94MB | Jul 22, 2017 at 1:53pm (UTC)  |
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|       | 8fa08537ae51 | no     | ubuntu 16.04 LTS amd64 (release) (20170516) | x86_64 | 153.70MB | May 17, 2017 at 7:56pm (UTC)  |
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|       | cd7815f09be3 | no     |                                             | x86_64 | 571.19MB | Jul 24, 2017 at 12:14pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|       | d9ada5c1e2cc | no     |                                             | x86_64 | 571.19MB | Jul 24, 2017 at 12:54pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+

```

**Comment by stgraber** [comment]
was your "init" meant to be with php71?

Because if it was php7, then you already have the right image locally (d9a).

**Comment by Kramerican** [comment]
Ah it would be nice if it was a typo :)

But no, sorry the first command example I gave was quickly typed out - the image alias in question is in fact webdock-xenial-lemp-php71

So I am running `lxc init krellide:webdock-xenial-lemp-php71 test` and getting a container off the old image `63b7f9e580f6` and not the new `b59463208093`

**Comment by Kramerican** [comment]
Any way I can debug what is happening with regards to what happens internally in LXD after it makes the request to the remote image server? The log indicates that the correct new fingerprint is being returned, but the image is not being downloaded. So, something is stopping LXD from fetching the new image. I guess it could be anything from a bug to a network issue but I'm not sure where to start looking.

Odds are I fucked up somewhere :smile:

**Comment by stgraber** [comment]
One thing that would be interesting to know is whether restarting LXD gets the image to update.

**Comment by Kramerican** [comment]
Yep, sure does

```
lvl=info msg="Pruning expired images" t=2017-07-25T23:23:42+0200
lvl=info msg="Updating images" t=2017-07-25T23:23:42+0200
lvl=info msg="Done pruning expired images" t=2017-07-25T23:23:42+0200
lvl=info msg="Connecting to a remote public LXD over HTTPs" t=2017-07-25T23:23:42+0200
etag= lvl=info method=GET msg="Sending request to LXD" t=2017-07-25T23:23:42+0200 url=https://krellide.webdock.io:8443/1.0
lvl=info msg="Done expiring log files" t=2017-07-25T23:23:42+0200
etag= lvl=info method=GET msg="Sending request to LXD" t=2017-07-25T23:23:45+0200 url=https://krellide.webdock.io:8443/1.0/images/aliases/webdock-xenial-lemp-php71
etag= lvl=info method=GET msg="Sending request to LXD" t=2017-07-25T23:23:48+0200 url=https://krellide.webdock.io:8443/1.0/images/b5946320809384a25a2b6dc798340e084acf8eb9e67318cb99f17dc$
alias=webdock-xenial-lemp-php71 lvl=info msg="Downloading image" server=https://krellide.webdock.io:8443 t=2017-07-25T23:23:52+0200
```

**Comment by stgraber** [comment]
We somewhat recently landed logic to have LXD use the existing local image even if a newer one is available, so long as an auto-update interval is set. The reason for this was so that users with slower internet connections or on planes wouldn't get stuck waiting for the new image to download. Instead they'd instantly get a new container and the image would auto-update in the background.

Restarting LXD will force an image update cycle, so if that's the reason why your image didn't update then it will update your image then. You can then decide to go with a much faster update frequency or even turn off the auto-update feature which would then force LXD to always update the image when you ask to launch from it (as it otherwise wouldn't ever update it).

**Comment by Kramerican** [comment]
Aha!

Ok that all makes sense, and nice behavior. Albeit poorly documented? In any case, this of course means that if LXD sees that the remote server image has the same fingerprint as the local one, it obviously wont update it, right? Just making sure as you use the wording _always_

Could you give me a shorthand on how I'd turn off auto updating? I guess I can stop being lazy and dig through the docs :smile: 

In any case, if that's it, then all is well with the world!

**Comment by stgraber** [comment]
Correct, the logic is:
 - Resolve the requested image to its fingerprint, if available locally, use it
 - If not available locally, check if we have a local image for the same source alias, if available, use it
 - If nothing available locally, download now

In the second case, the auto-update logic will kick in at the usual interval (6 hours by default) and update the image.

If you do:

    lxc config set images.auto_update_interval 0

Then LXD won't auto-update the images in the background and instead will download the newer image the next time you try to create a container.

**Comment by Kramerican** [comment]
Excellent! Thanks so much yet again. Keep up the good work :+1: 

PS: Love your blog. A fantastic LXD resource.
