### ISSUE TITLE
lxc image export : permission denied

### ISSUE THREAD

**Issue by jwetalley** [lxc/lxd#3592]
**# Required information**

 * Distribution:  Ubuntu Core 16 (GNU/Linux 4.4.0-2002-caracalla x86_64)
 * Distribution version:
**The output of "lxc info":**
root@GW3000:~# lxc info
config:
  core.https_address: '[::]:8443'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.215.3.226:8443
  - 10.10.248.1:8443
  - '[fd42:5443:d291:9bc9::1]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFQzCCAyugAwIBAgIQKFfU7M8sUmzgcO5o5zU4NzANBgkqhkiG9w0BAQsFADA1
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRUwEwYDVQQDDAxyb290QDlU
    VExCMDIwHhcNMTcwNjE0MjIwNzM5WhcNMjcwNjEyMjIwNzM5WjA1MRwwGgYDVQQK
    ExNsaW51eGNvbnRhaW5lcnMub3JnMRUwEwYDVQQDDAxyb290QDlUVExCMDIwggIi
    MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQD1u8nhMJrn6O83n8AXlb6s6lUD
    sz1HD8XIf4Rg8GM2inxG6ZSwqU5OUTLC2G8uf96RQkUeW6gJQiMwQ1wOr1e8Rd3h
    Tdya95U4ZGUYGxXEznxRV0bycnU4ap0QInl/Oe1CqgExy/FLGCpZ3BSS6JncDdBe
    QYnyH2dE6aq0p27VoQa1wsYmq0wLOXEvAGBwMRmdMsjarsdzbiSBxOgZj4Bb8b4U
    1GSBbkyIUsL7xEbjc9V2G8E+1X1LZeNGyX74Ru+Rzd7YZXFCrD7pxWgRY2kicvdx
    Kr8WIrSlap4zlet9dxgvex3ITrBrF7H9soNMSXEcHqq51WtmLtLWwcrSHH167mPE
    1H95IDBMsJDujuHnWl9CokhFXsorIfiTGcGigM4WHfSwWa3lOd2IHGSMpH7lnTUM
    0bKV+txUqaH91WiLMhdJVBdXAmCJcL7uUFSugfyTUIJgT6LjNXbGcNFE+r8Xpemk
    sc1uK+b+H2dSEQaiFLOK14XAuCrcIfkRtWzZGNOc2QyfmUA9F5svQBC/GGuJT6NL
    09pd1LXRX6o+bGFjmZPv7AKSB6CezWlDN6v+D9EjrbBwnPRnYk4kFZSuNuiO5HWm
    ngI8IzP/j5UGeB7J2vutBzlPt2LtvMjTMe7d2h/JgFBjaX6se+LyErV7SfkKwZ5I
    OPIcLbEqx2bi1JWqvQIDAQABo08wTTAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAww
    CgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAYBgNVHREEETAPggc5VFRMQjAyhwQK
    13DIMA0GCSqGSIb3DQEBCwUAA4ICAQAs1r8owQkkCqrmBulyMJ4RNYT0f3/YyH7/
    51KGB0sHPSbw/2NhoqXf1oo0yrV5cOUDkQgnEdEGgOM0iwrANiV1r5PSB2ZlCfaO
    iZsBY4d2BAPmg33zbRi0X7BlQMLdSat9aeYH8QpPzU7t/nc1fftDePKjmCogkyYO
    7L/xSHK8/5PEvzrxJZznIjTjIQlYfgD4wVYUQZUo0Tfe0AVIgw9/MRuhwdvdQeR5
    ym4/hfcH872FPQXwm5lWMY7+TVT2VLD6sFkrxN/XCMpJEazX7aMCizZMtdg5dAi/
    k9V4Zp1T8nWMOLAHmkjob4uYTpiccufUKyCFFlrKOp5buP2cJSm57lrKZFv3PPm6
    m/qAB3ZSzOyvZY5+I9/C5/QKaxWuIkpOTQuGiiu5Xb7g88hHppJYm8hfDWg4JQ4Y
    rebTtnV6mXByQi4lum5ilC1ckdMioGZj7ONTeIzcgU6jpMTZulEQfxjQuA2c6UZC
    RMR0Bg+GjuBZEX6vDmfqCnu32hI1cLPxeLshaQDkPuxuq9Om5rLpGk0ju8cTWmSA
    NmUubn3cBDwKtLA/0Nlp350hifw+HVGyUd6amk9SY/cEVZ5ZtuabVqqjrhHoQ25p
    TRNfSdorqs94ttujbdsJWU+/N25VHiCfpXB+SVeKRMN6T55uaHE2T+1cBbhUR1qw
    GeiMAbro8w==
    -----END CERTIFICATE-----
  certificate_fingerprint: afff5250f37365cc9ed2ca278b8added137ec4642ec64e36a8ec0104c606c256
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-2002-caracalla
  server: lxd
  server_pid: 1605
  server_version: "2.15"
  storage: dir
  storage_version: "1"

   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

**# Issue description**

I can pretty much manage every thing with containers and images in my lxd environment, but whenever I want to **export image** I get "**permission denied**".  I am pretty much new to the lxd environment.  This is also installed within a Ubuntu Core 16 environment.  So there is no /var/lib/lxd directory as I have seen in other forums. 

**# Steps to reproduce**

1. root@GW3000:~# lxc image list
+--------+--------------+--------+---------------------------------------------+-----
| ALIAS  | FINGERPRINT  | PUBLIC | DESCRIPTION  |  ARCH  |   SIZE   | UPLOAD DATE  |
+--------+--------------+--------+---------------------------------------------+-----
| vaatC2 | 4afdf7b83ae3 | yes    |    | x86_64 | 655.33MB | Jul 24, 2017 at 4:48pm (UTC) |
+--------+--------------+--------+---------------------------------------------+--------
|              | 8a3b6cc4b594 | no     | ubuntu 14.04 LTS amd64 (release) (20170718) | x86_64 | 120.00MB | Jul 19, 2017 at 5:55pm (UTC) |
+--------+--------------+--------+---------------------------------------------+--------
2. root@GW3000:~# lxc image export vaatC2
error: open 4afdf7b83ae329e523d1cf4cf632a8286c075dfd0271faa0eeaaceeb12ec5837: permission denied

3. root@GW3000:~# sudo groupadd lxd
groupadd: cannot lock /etc/group; try again later.

4. root@GW3000:~# newgrp lxd
newgrp: group 'lxd' does not exist

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (`lxc info NAME --show-log`)
 - [ ] main daemon log (`cat /var/log/lxd/lxd.log`)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
So I think what's going on here is that the snap is prevented to write to /root by apparmor.
That'd be a snapd permission issue. The "home" interface that's used to write to one's home directory doesn't apply to the root user...

You can either use another system to talk to LXD over the network which should work fine.
Or if you need to do it locally, you'll need to create the "lxd" group (use the --extra-users flag), then put an unprivileged user into that group, restart LXD and then run the "lxc image export" command again as that unprivileged user.

**Comment by jwetalley** [comment]
Hi @stgraber,

Copying over to another LXD host was exactly what I needed to do and it worked perfectly.  Thanks a lot for your help.   The instructions on your web-site were very clear and worked perfectly.

https://stgraber.org/2016/04/12/lxd-2-0-remote-hosts-and-container-migration-612/

**Comment by stgraber** [comment]
Cool. Closing this issue since it's really an issue with snapd/ubuntu-core file permission handling which LXD can't do a lot about. I did file a bug report about this a few months ago, so there's hope the home interface will eventually cover /root too.
