### ISSUE TITLE
LXD Client API: Validation and Certificate Generation

### ISSUE THREAD

**Issue by jtopjian** [lxc/lxd#3606]
Hello,

I've helped add LXD support into two external applications:

* https://github.com/sl1pm4t/terraform-provider-lxd
* https://github.com/yyyar/gobetween

For both of these, I wanted the applications to be able to add remote LXD servers without the need for the LXC client as this would make the applications more standalone.

I had to make a handful of functions in order to fully do this:

https://github.com/jtopjian/lxdhelpers

These functions are based on private functions I found in the LXD code.

Would it be possible to expose this functionality publicly through the LXD Client API at some point? Perhaps it's already possible and I've simply overlooked it?

Thanks,
Joe

**Comment by stgraber** [comment]
Hi,

I'll take a look into this soon. I suspect we can at the very least expose them in github.com/lxc/lxd/shared but it may also be possible to do a clean job of them and have them be directly in the new client code or the config code.

**Comment by jtopjian** [comment]
Sounds good! Thank you 😄

**Comment by stgraber** [comment]
So I've pushed a branch which exposes:
 - HasClientCertificate() (in lxc/config)
 - GenerateClientCertificate() (in lxc/config)
 - GetRemoteCertificate(address) (in shared)

That should eliminate the need for the first of your two helpers.

I'm not sure that ValidateRemoteConnection really makes that much sense for us to carry as its arguments are likely to change as we add some upcoming features and making it flexible would just turn it into an alias of CreateCertificate.

**Comment by jtopjian** [comment]
@stgraber Thank you so much for doing that!
