### ISSUE TITLE
Filed remote image download

### ISSUE THREAD

**Issue by monkiki** [lxc/lxd#3610]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-28-generic
   * LXC version: 2.0.8
   * LXD version: 2.16
   * Storage backend in use: zfs

# Issue description

Can't copy an image to another LXD server. It worked some weeks ago, but it seem a recent update introduced the issue. 

# Steps to reproduce
Log into **srv01** and try to copy the image to **srv02**.
```
$ lxc image copy imageX srv02: --alias imageX
```
Result:

```
error: Failed remote image download:
 - https://88.198.22.111:8443: not found
 - https://[2a01:4f8:130:3395::2]:8443: Get https://[2a01:4f8:130:3395::2]:8443/1.0: Unable to connect to: [2a01:4f8:130:3395::2]:8443
 - https://10.0.3.1:8443: Get https://10.0.3.1:8443/1.0: x509: certificate is valid for srv02, not srv01
```

**Comment by albertodonato** [comment]
are those the addresses of srv01 or srv02?

**Comment by albertodonato** [comment]
Could you please check that srv01 is also listening on the network (`core.https_address` is set)?

If not, the srv02 can't contact srv01 to get the image.

**Comment by monkiki** [comment]
This is the config:
```core.https_address: '[::]:8443'```
I've changed it to bind only to the IPv4 but the problem is the same:
```
error: Failed remote image download:
 - https://88.198.22.111:8443: not found
```
But I think the problem is related to the certificate because when I try to connect from the other server it says (using Lynx):
```SSL error:host(88.198.22.111)!=cert(CN<root@srv01>)```
It seems that the "not found" error is not the real problem but the certificate is not good.
