### ISSUE TITLE
Docker profile not found.

### ISSUE THREAD

**Issue by juanquy** [lxc/lxd#3615]
# Required information

 * Distribution: Ubuntu Server ( update and upgraded)
 * Distribution version:16.04  x86_64
 * The output of "lxc info" or if that fails:
   * Kernel version:4.4.0-87 
   * LXC version: 2.16
   * LXD version: 2.16
   * Storage backend in use: zfs

# Issue description
Profile docker not found!
$ lxc profile list
name            used by 
default ===== 1

**Comment by stgraber** [comment]
Yes, that's normal. The docker profile was removed as it was effectively no longer needed with recent versions of Docker.

Just use: lxc launch ubuntu:16.04 container-name -c security.nesting=true
Which is the same as any case of container in container and that'll work fine with Docker.

**Comment by stgraber** [comment]
This changed with LXD 2.14 and was mentioned in the release announcement:
https://linuxcontainers.org/lxd/news/#lxd-214-release-announcement-30th-of-may-2017

**Comment by juanquy** [comment]
Ok thanks was worry I mess up doing something lol so docket profile is not
longer need it, only security.nesting = true. Done Cool!
