### ISSUE TITLE
DPDK in LXD Container

### ISSUE THREAD

**Issue by mrb1090** [lxc/lxd#3619]
Looking to run DPDK apps within a Ubuntu 16.04 LXD/LXC container.  Have modified the container's config with the following:
  raw.lxc: |-
    lxc.cgroup.devices.allow = c 242:* rwm
    lxc.mount.entry =  /mnt/huge mnt/huge none bind,create=dir 0 0

After container is running I create the mount points for the nics:
    mknod /dev/uio0 c 242 0
    mknod /dev/uio1 c 242 1

However, when I run my DPDk app I get the following warning/error:
    dpdk.cc:88] EAL: Cannot open /sys/class/uio/uio0/device/config: Read-only file system
    I0801 11:32:29.190531   483 dpdk.cc:88] EAL: Requested device 0000:03:00.0 cannot be used

Curious if anyone has a working config I can use as a starting point?

Thanks,

Mike B.

**Comment by stgraber** [comment]
Looks like DPDK needs a very very privileged container then :)

Try adding this to your raw.lxc:
    lxc.mount.auto=
    lxc.mount.auto=proc:rw sys:rw

**Comment by stgraber** [comment]
That should take care of the /sys permission issue, though you may then hit a capability problem as we typically disallow raw pci access and I suspect this is going to be doing just that.

If that becomes a problem, you can go one step further by adding this too:

    lxc.cap.drop=

Which will have LXD retain all capabilities for the container. Obviously at that point there won't be a whole lot container security left in place :)
