### ISSUE TITLE
Question: reload bridge configuration post 2.3

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#3620]
* Distribution: Ubuntu
 * Distribution version: Xenial
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-53-generic
   * LXC version: 2.15
   * LXD version: 2.15
   * Storage backend in use: btrfs

# Issue description

Prior to 2.3 I was using static IP entries for my containers. This was referenced in the file `/etc/default/lxd-bridge` 
```
# Path to an extra dnsmasq configuration file
LXD_CONFILE="/etc/default/lxd_dnsmasq.conf"
```
and the file itself:
```
dhcp-host=cont1,10.0.4.2
dhcp-host=cont2,10.0.4.3
````

How can I reload the bridge configuration when adding another static entry to that file with lxd > 2.3?

Thx

**Comment by huegelc** [comment]
Hi @stgraber ,

thanks for the hint. But why would this value change if I set it once with `lxc network set lxdbr0 raw.dnsmasq conf-file=/etc/default/lxd_dnsmasq.conf` ?
I guess I´ll stick with you second proposal :)

Speaking of dnsmasq: how does lxd use dnsmasq as I see that the service isn´t started but in the process list I see a dnsmasq instance running?

**Comment by stgraber** [comment]
@huegelc it wouldn't, but you could just move the content of /etc/default/lxd_dnsmasq.conf to the raw.lxc config key itself.

LXD spawns dnsmasq directly, similar to what libvirt and a bunch of other daemons do. That way it doesn't interfere with an existing system daemon. LXD also needs one dnsmasq instance per bridge it manages, which isn't something the normal distro init script supports.

**Comment by huegelc** [comment]
Thanx, got it
