### ISSUE TITLE
LXD Error on Ubuntu 16.04.3: Failed Container Creation: Profile Docker Doesn't Exist

### ISSUE THREAD

**Issue by justinmnoor** [lxc/lxd#3623]
I'm working on a clean install of Ubuntu 16.04.3. This was a completely reformatted disk with nothing on it. After running `sudo apt update` and `sudo apt upgrade` as usual, the first thing I installed was the LXD snap package. I attempted to launch my first container with a Docker profile:

`    lxc launch ubuntu-daily:16.04 mytest -p default -p docker`

I got the following error:

```
    Creating mytest
    error: Failed container creation:
     - https://cloud-images.ubuntu.com/daily: Requested profile 'docker' doesn't exist
```

My LXD installation steps:

```
    sudo apt install lxcfs
    sudo groupadd --system lxd
    sudo usermod -G lxd -a myuser
```

The I restarted my computer

```
    sudo snap install lxd
    sudo lxd init

```
I used all of the default settings for the LXD configuration.

Any thoughts?

**Comment by brauner** [comment]
The docker profile has been removed since it is not required anymore with new versions of docker.
