### ISSUE TITLE
LXD fails to start container on host using isolcpus and hugepages

### ISSUE THREAD

**Issue by dosaboy** [lxc/lxd#3624]
While i am not 100% sure the two are related, I have a host configured to use isolcpus for a subset of cores and also a small number of hugepages allocated and when i stop and start a container it fails and spews a lot of errors - see http://pastebin.ubuntu.com/25226827/

The command line opts im adding are:

isolcpus=4,5,12,13,14,15,16,17 hugepagesz=1G hugepages=8 default_hugepagesz=1G

and my numa cells look like:

\# numactl --hardware
available: 2 nodes (0-1)
node 0 cpus: 0 1 2 3 4 5 12 13 14 15 16 17
node 0 size: 32140 MB
node 0 free: 16550 MB
node 1 cpus: 6 7 8 9 10 11 18 19 20 21 22 23
node 1 size: 32253 MB
node 1 free: 21046 MB
node distances:
node   0   1 
  0:  10  20 
  1:  20  10

This is with lxd 2.0.10-0ubuntu1\~16.04.1 i.e. the version in xenial-updates. I also tried upgrading to 2.15-0ubuntu6~ubuntu16.04.1 from xenial-backports but still see the problem albeit without the tons of errors on stdout. After I upgrade, if i reboot the host it does seem to work.

**Comment by brauner** [comment]
@dosaboy, are you handing any specific cpus to your containers that include isolcpus?

**Comment by dosaboy** [comment]
@brauner actually I'm not specifying anything from a lxd perspective. I'm just setting isolcpus so that I can use it with libvirt from a separate use case but also happen to have lxc containers on the same node.

**Comment by brauner** [comment]
Can you show me

- `cat /sys/fs/cgroup/cpuset/lxc/cpuset.cpus`
- `cat /sys/fs/cgroup/cpuset/cpuset.cpus`
- `cat /sys/fs/cgroup/cpuset/lxc/cgroup.clone_children`
- `cat /sys/fs/cgroup/cpuset/cgroup.clone_children`

please?

**Comment by dosaboy** [comment]
ubuntu@orgen:~⟫ cat /sys/fs/cgroup/cpuset/lxc/cpuset.cpus
0-23
ubuntu@orgen:~⟫ cat /sys/fs/cgroup/cpuset/cpuset.cpus
0-23
ubuntu@orgen:~⟫ cat /sys/fs/cgroup/cpuset/lxc/cgroup.clone_children
1
ubuntu@orgen:~⟫ cat /sys/fs/cgroup/cpuset/cgroup.clone_children
1

**Comment by brauner** [comment]
Also

- `cat /sys/devices/system/cpu/isolated`

please?

**Comment by brauner** [comment]
And the output of `lxc info`.

**Comment by brauner** [comment]
I actually suspect this to be related to your numa setting.

**Comment by brauner** [comment]
Also, if you upgraded `liblxc` from a version that doesn't support isolcpus to a version that does and you have container's running that have been created by a  non-isolcpus `liblxc` any new containers will likely fail to start since you cannot remove cpus from a cpuset that is also in a child of that cpuset.

**Comment by dosaboy** [comment]
@brauner so a few things. Firslty i upgraded from the latest version in xenial-updates to the latest version in xenial-backports, both of which iiuc are fully supported albeit generally with a feature delta. Does the version in xenial-updates (2.0.10-0ubuntu1\~16.04.1) not support isolcpus? Also, when i rebooted, following lxd upgrade and subsequent failure to start some containers, it all works fine and i'm guessing that's because lxd is reconfiguring cpusets based on what is available before starting any containers but i'd have to check. If you want I can redeploy and start the process again to pull data in between each step.

**Comment by dosaboy** [comment]
Sorry i forgot to supply that last piece of info so here it is:

# cat /sys/devices/system/cpu/isolated
4-5,12-17

**Comment by brauner** [comment]
If you happen to be able to redeploy and provide me with info about the liblxc version used before and after the upgrade that would be great. You can just gather this info by running `lxc info`.

**Comment by brauner** [comment]
@dosaboy, thanks! @stgraber and I fixed that bug yesterday. :)
