### ISSUE TITLE
error: Missing TLS client certificate and key

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#3627]
Executing this command on v2.16 on a client server:

`~ # lxc remote add krellide krellide.mysite.io --accept-certificate --public
error: Missing TLS client certificate and key`

I can then verify by running `lxc remote list` that the remote has indeed not been added.

This worked fine in v2.15 - I tried updating the image server to v2.16 but no joy. Not sure if this is a bug, or if I have missed a configuration step somewhere.

**Comment by stgraber** [comment]
I can reproduce this with LXD 2.15 and 2.16, in fact with any LXD version I can get my hands on.

The problem is that you're adding a public remote before you ever connected to a private one, so no TLS certificates are present.

**Comment by Kramerican** [comment]
OK

So is this a bug? I mean, I don't need to connect to any private remote - or is .eg. the default ubuntu: remote considered private so I just need to do a quick init of something and then TLS certs will be generated?

Yeah sorry if I'm being thick here - not sure I get it :)

**Comment by stgraber** [comment]
Can you try: https://dl.stgraber.org/lxc-3627 (sha256: 47b20860001d0906007e65e94fe830774906b50fb8c617179eeeb55ccfcf949a)

**Comment by Kramerican** [comment]
As in `lxc remote add test https://dl.stgraber.org/lxc-3627 --public` - Same result :/

**Comment by stgraber** [comment]
Nope, as in, download the custom "lxc" binary at that URL and run that instead of the one you've got on your system.

**Comment by Kramerican** [comment]
No wait that's a link to an ELF - ah yes you beat me to it, ok I'll try

... Works :)

```
root@jadzia ~/webdock # chmod +x ./lxc-3627 
root@jadzia ~/webdock # ./lxc-3627 remote add krellide krellide.webdock.io --public
Certificate fingerprint: 9fc315e1e6e31b86e98d5772ef5ea24a3a4b5396f0a4965c561956a85d59a9cd
ok (y/n)? y
root@jadzia ~/webdock # lxc remote list
+-----------------+------------------------------------------+---------------+--------+--------+
|      NAME       |                   URL                    |   PROTOCOL    | PUBLIC | STATIC |
+-----------------+------------------------------------------+---------------+--------+--------+
| images          | https://images.linuxcontainers.org       | simplestreams | YES    | NO     |
+-----------------+------------------------------------------+---------------+--------+--------+
| krellide        | https://krellide.webdock.io:8443         | lxd           | YES    | NO     |
+-----------------+------------------------------------------+---------------+--------+--------+
| local (default) | unix://                                  | lxd           | NO     | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
| ubuntu          | https://cloud-images.ubuntu.com/releases | simplestreams | YES    | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
| ubuntu-daily    | https://cloud-images.ubuntu.com/daily    | simplestreams | YES    | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
```
