### ISSUE TITLE
CHANGELOG 0.3

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#363]
I realize that maintaining a changelog is a burden, but it will greatly help to keep interested people monitor this project. =)

**Comment by stgraber** [comment]
We keep a changelog on our website. The 0.3 announcement there with its changelog will be pushed later today.

**Comment by stgraber** [comment]
Website updated.

**Comment by techtonik** [comment]
The changelog is hard to spot with these nested menus. It may worth changing URL in GitHUb project header directly to https://linuxcontainers.org/lxd/news/
