### ISSUE TITLE
Is container unprivileged

### ISSUE THREAD

**Issue by vv0iadyk** [lxc/lxd#3635]
Hi,
I succeeded to run GUI apps in container following [this guide](https://blog.simos.info/how-to-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop/), but I dont know if container I got with this is unprivileged. How do I check if container unprivileged and it found out that privileged how to turn him to unprivileged.? 
_I need it unprivileged for safety browsing._

**Comment by stgraber** [comment]
This guide does describe an unprivileged container but with your normal user's uid and gid mapped into the container. So the container doesn't run as real root (therefore is unprivileged) but does have access to some resources as your user (X11 socket and pulseaudio socket).

So your browser does run in an unprivileged container and can't trivially escape from the container.
However do note that there's a major issue with all of this, X11.

X11 allows any client application to eavesdrop on all the others. So even though your browser runs a container, the fact that it has access to X11 (so it can render its window) allows it to record all keystrokes on your machine, capture your entire screen and interact with any window that's currently displayed.

This isn't a container-related limitation, the same is true whether a container is involved or not, but it's certainly something to keep in mind. Wayland and some other X11 alternatives don't have this design mistake in their protocol, so there's hope for the future.
