### ISSUE TITLE
Following official tutorial leads to error: Invalid device type for device 'gpu' when running lxc config device add c1 gpu gpu

### ISSUE THREAD

**Issue by gregsifr** [lxc/lxd#3637]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- id_map
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 192.168.1.105:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFpDCCA4ygAwIBAgIQBulS6UX+T6a2aMLQCglDxzANBgkqhkiG9w0BAQsFADAz
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRMwEQYDVQQDDApyb290QG5v
    ZGU1MB4XDTE2MTEyMjEzMjgxMloXDTI2MTEyMDEzMjgxMlowMzEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBub2RlNTCCAiIwDQYJ
    KoZIhvcNAQEBBQADggIPADCCAgoCggIBANnt8D7kNw34A1EAEAMNsKJSXQGOp9DX
    xj+L2ZtvkgVCTTNvM28wavyn/ngS2/on3DJWu7mlaT2p5rGQOEtX7xo8nmfROJnj
    jra/moXy1Xv4Zyz0SG2RM+StYUUCfq9h0+y23DTbv6zZp1HQCSB5vihrIPnRFHah
    NMuV5QyRpbCxeB7Gg9r6YamzT/CeuL9M2bFgbUw6rK/xmtHo+41Li/63YMiUeFxE
    C7sPRaXFlTo1G7vuOkK+LWLwYL5//eoM3Zgc+pcS/qJdnnWKx3ncE5LyN5q9/wyg
    jh2baH0ryBagIvnMy41quYBoJRX9wF23tHJBv0FvpQcLnIqlFiolxw6oGxSYgiH/
    6euO5nOAwUn/BswCMF1HyiGqKma/qIqdpjhk2o7TBAyoCvRCyGWUpmChfC5yHfAW
    BL+I5FSsE12wXKT7P5+9F4C2WXi33v5uDsumAQf7lNyJhF0uaGXJ6W2Xn9sqmlrc
    29V7fMAb+JkV4aJkqyKoeqmR4beWUPDDaTTkXYQdOIaN8Gjn0fDZfTM3Db7Wcw/X
    rIsDVxxm4figYtnPQ2fdQ0JJB086x2dTG29awUZIrpOuycrh7VuREGrljcuG0rQm
    QL/LICfOM1Tive+MxGIeW7qLoNwynIdu2rFxq/gsAEpzy3XWabfOof8MrsoevWZk
    /e2Zn9QG+8T7AgMBAAGjgbMwgbAwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoG
    CCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwewYDVR0RBHQwcoIFbm9kZTWCEDE5Mi4x
    NjguMS4xMDUvMjSCEDE5Mi4xNjguMS4xMDUvMjSCG2ZlODA6OmVjNDo3YWZmOmZl
    ZDg6YjgzMC82NIIcZmU4MDo6OGNlYjpkMGZmOmZlY2M6NGJkYS82NIIKZmU4MDo6
    MS82NDANBgkqhkiG9w0BAQsFAAOCAgEAwCmTR1NpuvZE/vsOKmT1m8pp/DsL80oE
    nvdhc94OIWbclVEo+9SpNfGYnHO4WKV5CBHhR86XJEZJ3XRu+xdJvzrS3gprwepl
    veut0t1QK4k51si2UpCdaJC5/nI2UrD4DvPH/b1l2mUznT8Rmca3KFgbupFqRnMM
    IPATRud6Dr9PPolF5SBF9T7f9a0n1rQiI0x36h6OyjtpYqfHVokAYNaq4e9mQ32Z
    CJsismz2mG4AAlVjII3n8wqt5AX04eJEFbsZKuu+hCwW4V7G0j/e2qSdyJq4uUEz
    +ZaEn3hov6hywZiZSJLfxEFArr5aSJ5++n76pc69sxRJE5mJ96b1bA1J0l2F2E//
    Yb5hrBvINfXj/OkuNpMGQRkVZmiulWeK8DXwIEfDp79sk/wz7tTG1vzdP16MxHq0
    iby1EH6y635r48JWX+xrpFu3qQN4mErXzrLq5ADUyg8REpdrX2xJsUgMJWYKg8FN
    DbvcxWhCcrzZEnfrWQluE/yJ4zipAePyS94QxejrFUqXY1/Gy99OMod/6ctIlMs1
    ZUhCIsu+nw5OlcFEt2qWue0vBKxNAlSwMoySR8mb66LDtCKxEXseO8wKQvqCyBWR
    bQIHEeLLpNuOxP0WoZhmMiZH3hxEHX6R8IftLM1G504zxbQz2GxaxlGBK/1qAdDL
    8doVn5i+t4A=
    -----END CERTIFICATE-----
  certificate_fingerprint: 78a91b226234ba4c72bcf5e2ac04a4bda752fcbe736739399024f50f377aadd0
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-89-generic
  server: lxd
  server_pid: 2355
  server_version: 2.0.10
  storage: dir
  storage_version: ""

# Issue description
I was following the official tutorial https://stgraber.org/2017/03/21/cuda-in-lxd/ to install a GPU inside an lxd container. After successfully installing the GPU on the host, I tried to add it using `lxc config device add c1 gpu gpu` and received the following error message: `error: Invalid device type for device 'gpu'`.

# Steps to reproduce

Follow the tutorial.

# Information to attach

**Comment by stgraber** [comment]
This article clearly states: "Note that for this to work, you’ll need LXD 2.5 or higher."
You're running LXD 2.0.10 which doesn't qualify for "higher than 2.5".

**Comment by stgraber** [comment]
LXD 2.0.x is the LTS branch, which is updated with bugfixes and security updates but doesn't get any new features. This is the recommended option for production setups which want stability over feature addition.
The LTS branch gets 5 years of support from upstream.

LXD 2.x (currently at 2.16) is the LXD feature branch which gets monthly releases and is only supported until the next release comes out (so about a month).

The GPU passthrough is one such feature which was added after the LXD 2.0 release and so won't be in a LTS release until LXD 3.0. If you need to use this feature, then you have to opt into using the feature branch.

**Comment by gregsifr** [comment]
Thank you for the detailed answer
