### ISSUE TITLE
Static build

### ISSUE THREAD

**Issue by prologic** [lxc/lxd#364]
Is it (*will it be*) possible to statically build/compile lxd/lcd for smaller embedded systems that don't ship with a libc? Are there any hard host dependencies required?

**Comment by stgraber** [comment]
I don't believe anyone successfully achieved a static build yet or at least made noise about it :)

One problem you'll run into is that we have quite a few binaries so statically compiling all of them will make the result pretty big, but I guess you'd just ship a couple of them then.

The other problem you'll run into is the number of external libraries we use. Though I believe all of them can be turned off with configure flags (at the cost of features like capability handling, selinux support, apparmor support, seccomp support and cgmanager support).

**Comment by stgraber** [comment]
As for LXD itself, it's written in Go and Go typically results in a static binary. However as we use a fair amount of C in there (through cgo), we do end up pulling all the library dependencies of LXC (through go-lxc) and we use libc functions too.

**Comment by therealprologic** [comment]
Thanks for the insight. Maybe we'll give this a try and see what issues we run against :)

**Comment by stgraber** [comment]
Closing this from a LXD point of view as we don't have plans to ship static binaries ourselves. Our code should also be fine for that (because of Go), our dependencies may be a problem though.
