### ISSUE TITLE
LXD checkpoints and LIVE migration

### ISSUE THREAD

**Issue by FEDE9326** [lxc/lxd#3640]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
   * Kernel version: Linux 4.13.0-041300rc4-lowlatency #201708062231 SMP PREEMPT Mon Aug 7 02:38:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 2.16
   * LXD version: 2.16
   * Storage backend in use: dir
   * CRIU Version: 3.3 GitID: v3.3-1-g43ed56e

# Issue description

I'm trying to live migrate lxc containers hosted by Ubuntu VMs. Containers are based on a ffserver running a video on-demand for a certain client. At today I'm not able to live-migrate the container beacuse of some CRIU errors. I know that this is a beta-feature but I'd like to understand whether it's a problem of my implementation. I've tried to change kernel versions, criu and lxc/lxd version, apparmor profile configurations but it has never worked. I'm using the kernel version at this page https://github.com/muhasturk/ukupgrade with all the CRIU flags set. The only way I have to perform a live migration is using the lxc API explained here https://tycho.ws/blog/2014/09/container-migration.html but with some limitations. 

# Steps to reproduce

1) Install lxd and CRIU
    sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable -y;
    sudo apt-get update;
    sudo apt-get install lxd;

    sudo apt-get install cgroup-bin cgroup-lite cgroup-tools cgroupfs-mount           libcgroup1;
    sudo apt-get install bridge-utils;

    sudo apt-get install -y protobuf-c-compiler libprotobuf-c0-dev                    protobuf-compiler libprotobuf-dev:amd64 gcc build-essential bsdmainutils          python git-core asciidoc make htop git curl supervisor cgroup-lite                libapparmor-dev libseccomp-dev libprotobuf-dev libprotobuf-c0-dev                 protobuf-c-compiler protobuf-compiler python-protobuf libnl-3-dev libcap-dev      libaio-dev apparmor;
    sudo apt-get install libnet1-dev;

    git clone  https://github.com/xemul/criu.git criu;
    cd criu;
    make clean;
    make;
    sudo make install;

2) bridge creation for containers

    auto br0
    iface br0 inet static
    address 192.168.5.48
    netmask 255.255.255.0
    gateway 192.168.5.1
    bridge_ports ens3
    bridge_stp off
    bridge_fd 0
    bridge_maxwait 0

    sudo nano /etc/sysctl.conf;  #uncomment #net.ipv4.ip_forward=1
    sudo sysctl -p;

3) sudo lxd init without creating lxdbr0
4) Create a new profile and lxd group
newgrp lxd
lxc profile create bridged 
lxc profile edit bridged

    config:
raw.lxc: lxc.console = none lxc.cgroup.devices.deny = c 5:1 rwm lxc.start.auto =
    lxc.start.auto = proc:mixed sys:mixed
  security.privileged: "true"
description: ""
devices:
  ens3:
    nictype: bridged
    parent: br0
    type: nic
name: bridged
used_by: []

    lxc config set my-ubuntu1 raw.lxc "lxc.aa_allow_incomplete = 1"

5) lxc launch ubuntu:16.04 my-ubuntu1 -p bridged -s default
6) install ffserver inside the container 
7) lxc exec my-ubuntu1 bash
   ffserver -f /etc/ffserver.conf & 
8) lxc snapshot my-ubuntu1 snap0 --stateful

    lxc snapshot my-ubuntu1 snap0 --stateful
error: snapshot dump failed
(00.733768) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4312 with interrupted system call
(01.070699) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4316 with interrupted system call
(01.239493) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4321 with interrupted system call
(01.239630) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4333 with interrupted system call
(01.241915) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4317 with interrupted system call
(01.911284) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4341 with interrupted system call
(01.911522) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4343 with interrupted system call
(01.913048) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4335 with interrupted system call
(02.084034) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4336 with interrupted system call
(02.266562) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4340 with interrupted system call
(02.443482) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4347 with interrupted system call
(02.443628) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4352 with interrupted system call
(02.621748) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 4431 with interrupted system call
(02.622059) Error (criu/files-reg.c:1276): Can't lookup mount=22 for fd=0 path=/dev/pts/2
(02.622069) Error (criu/cr-dump.c:1334): Dump files (pid: 4431) failed with -1
(02.626195) Error (criu/cr-dump.c:1657): Dumping FAILED.

    This error appears also when I try to live migrate with LXD move command.

    Instead of the ffserver I also tried to run a PING command and snapshot it.

    (00.505523) Warn  (criu/arch/x86/crtools.c:133): Will restore 31949 with interrupted system call
(01.064745) Warn  (criu/arch/x86/crtools.c:133): Will restore 31953 with interrupted system call
(01.466128) Warn  (criu/arch/x86/crtools.c:133): Will restore 31959 with interrupted system call
(01.466383) Warn  (criu/arch/x86/crtools.c:133): Will restore 31961 with interrupted system call
(01.470641) Warn  (criu/arch/x86/crtools.c:133): Will restore 31956 with interrupted system call
(01.642034) Warn  (criu/arch/x86/crtools.c:133): Will restore 31974 with interrupted system call
(01.642202) Warn  (criu/arch/x86/crtools.c:133): Will restore 31979 with interrupted system call
(01.845464) Warn  (criu/arch/x86/crtools.c:133): Will restore 31982 with interrupted system call
(02.022141) Warn  (criu/arch/x86/crtools.c:133): Will restore 31983 with interrupted system call
(02.022293) Warn  (criu/arch/x86/crtools.c:133): Will restore 31985 with interrupted system call
(02.371584) Warn  (criu/arch/x86/crtools.c:133): Will restore 32164 with interrupted system call
(02.535338) Warn  (criu/arch/x86/crtools.c:133): Will restore 32165 with interrupted system call
(03.091648) Warn  (criu/arch/x86/crtools.c:133): Will restore 32300 with interrupted system call
(03.092077) Error (criu/sk-inet.c:106): Unsupported proto 1 for socket 2f406
(03.092093) Error (criu/cr-dump.c:1313): Dump files (pid: 32300) failed with -1
(03.096479) Error (criu/cr-dump.c:1628): Dumping FAILED.

I have also noted that if a run commands outside the container using

lxc exec my-ubuntu1 -- ffserver -f /etc/ffserver.conf

I'm able to checkpoint but not restore the container:

lxc restore my-ubuntu1 snap0
error: Failed to run: /usr/bin/lxd forkmigrate my-ubuntu1 /var/lib/lxd/containers /var/log/lxd/my-ubuntu1/lxc.conf /var/lib/lxd/containers/my-ubuntu1/state false:

# Information to attach

lxc info my-ubuntu1 --show-log

Name: my-ubuntu1
Remote: unix://
Architecture: x86_64
Created: 2017/08/08 09:25 UTC
Status: Stopped
Type: persistent
Profiles: bridged
Snapshots:
  snap0 (taken at 2017/08/08 09:47 UTC) (stateful)

Log:

    lxc 20170808094930.921 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
    lxc 20170808094931.114 ERROR    lxc_criu - criu.c:do_restore:916 - criu process exited 1, output:
    Error (criu/image.c:416): Can't open dir /var/lib/lxd/containers/my-ubuntu1/state: No such file or directory
    lxc 20170808094931.115 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
    lxc 20170808094931.115 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
    lxc 20170808094931.115 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - Command get_cgroup failed to receive response: Connection reset by peer.
    lxc 20170808094931.540 ERROR    lxc_criu - criu.c:__criu_restore:1221 - restore process died

 - [ ] main daemon log -> https://github.com/FEDE9326/LXD-DEBUG/blob/master/lxd.log
 - [ ] output of the client with --debug -> https://github.com/FEDE9326/LXD-DEBUG/blob/master/client_debug

**Comment by stgraber** [comment]
Looks like we do have a bug in 2.16 where the state directory is cleared on restore...

**Comment by FEDE9326** [comment]
Thanks for your support. The problem seems solved but when I restore the container the process which was running before (simple PING command) expires. 

# Steps to reproduce
lxc exec my-ubuntu1 -- ping 192.168.x.x

In another terminal:
lxc snapshot my-ubuntu1 snap0 --stateful
lxc stop my-ubuntu1
lxc restore my-ubuntu1 snap0 --stateful

When I restore the container the machine I was pinging stops to receive ICMP packets.
The ping process is not restored.

Here you can find the relative logs of the snap dump and restore:
https://github.com/FEDE9326/LXD-DEBUG/blob/master/snap_dump.log
https://github.com/FEDE9326/LXD-DEBUG/blob/master/snap_restore.log

Thank you

**Comment by stgraber** [comment]
As I said earlier, CRIU doesn't support checkpoint/restore of processes that were launched through "lxc exec" as they're not seen as being part of the container.

If you spawn that ping through an init script in the container (making PID1 its parent) or if you spawn it from an ssh session inside the container, then it should be checkpointed.

**Comment by stgraber** [comment]
Can you try with a 14.04 container? systemd tends to cause a lot of problems with criu, so it'd be interesting to see if switching to upstart helps.
