### ISSUE TITLE
Creating a bridge will create an unreadable dnsmasq.raw config file

### ISSUE THREAD

**Issue by xmj** [lxc/lxd#3652]
# Required information

 * Distribution:
   CentOS
 * Distribution version:
  7.3.1611
 * The output of "lxc info"
 ```
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 3.10.0-514.el7.x86_64
  server: lxd
  server_pid: 1438
  server_version: "2.16"
  storage: dir
  storage_version: "1"
```

# Issue description

Creating a network bridge 
will create a configuration file in `/var/lib/lxd/networks/lxdbr0/dnsmasq.raw` which has mode `0000` and is owned by `root:root`. This makes dnsmasq (running as `nobody`) unable to read said configuration file.

# Steps to reproduce

On a new virtual machine with newly installed `lxc`/`lxd` installations, create a network bridge using

```bash
lxc network create lxdbr0 ipv6.address=none ipv4.address=172.16.16.1/24 ipv4.nat=true 
```

It errors out.
```
[root@localhost ~]# lxc network create lxdbr0 ipv6.address=none ipv4.address=172.16.16.1/24 ipv4.nat=true raw.dnsmasq='#'
error: Failed to run: dnsmasq --strict-order --bind-interfaces --pid-file=/var/lib/lxd/networks/lxdbr0/dnsmasq.pid --except-interface=lo --interface=lxdbr0 --listen-address=172.16.16.1 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/lib/lxd/networks/lxdbr0/dnsmasq.leases --dhcp-hostsfile=/var/lib/lxd/networks/lxdbr0/dnsmasq.hosts --dhcp-range 172.16.16.2,172.16.16.254,1h -s lxd -S /lxd/ --conf-file=/var/lib/lxd/networks/lxdbr0/dnsmasq.raw -u lxd: dnsmasq: cannot read /var/lib/lxd/networks/lxdbr0/dnsmasq.raw: Permission denied
```

**Comment by stgraber** [comment]
Hmm, this isn't a problem on Debian or Ubuntu. I guess centos' version of dnsmasq is different and doesn't drop privileges in the same way.

**Comment by stgraber** [comment]
On Ubuntu/Debian, dnsmasq opens all files prior to dropping privileges, avoiding such issues and letting you keep those files pretty severely restricted.

That being said, there's no reason why we can't make dnsmasq.raw 644 like the others.

**Comment by xmj** [comment]
Dnsmasq not being able to read that file is probably a SELinux feature. I'll dig some more.
