### ISSUE TITLE
lxc exec Error: Failed to fetch / 301 Moved Permanently

### ISSUE THREAD

**Issue by anoxi** [lxc/lxd#3653]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.04
   * Kernel version: 4.10.0-30
   * LXC version: 2.0.8
   * LXD version: 2.16 (zesty-backports)
   * Storage backend in use:

# Issue description
After upgrading to lxd 2.16 i can't exec or start any container:
```
$ lxc exec local://xxx -- /bin/bash
error: Failed to fetch http://unix.socket/1.0/containers///xxx/exec: 301 Moved Permanently
```

**Comment by stgraber** [comment]
I think you want "lxc exec local:xxx -- /bin/bash", the syntax isn't a URI/URL so there's never "//" in the LXD commands themselves.

The "local" remote is also usually your default remote, so "lxc exec xxx -- bash" would be equivalent.

I find it surprising that this ever worked, it sure wasn't meant to :)

(Syntax is "lxc <command> [<remote name>]:<container name>").

**Comment by anoxi** [comment]
Thanks for the response.
I don't know why i got used to the syntax, i think i went into an error once and tried this instead.

The following worked for me: 
$ lxc exec local:xxx -- bash

This did not work:
$ lxc exec xxx -- bash
error: The remote "" doesn't exist

**Comment by anoxi** [comment]
I've just set `default-remote: "local"` in ~/.config/lxc/config.yml and `$ lxc exec xxx -- bash` is now working, great :)
