### ISSUE TITLE
Shared ZFS storage fails while set security.idmap.isolated=true

### ISSUE THREAD

**Issue by monkz** [lxc/lxd#3655]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 16.04.3 LTS
 * The output of "lxc info" or if that fails:
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-91-generic
  server: lxd
  server_pid: 2363
  server_version: "2.16"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu16 

# Issue description

I've created a custom storage backed with ZFS
I've set security.idmap.isolated=true but try to get a storage writable by one container and read only by others, to propagate data and sockets (via world readable in those containers).

My current situation is also that this storage volume does not mount automatically, and container, that depend on this storage, fails to start.

Firstoff: This seems to be in conflict with the solution of issue #3548 
Second: Would it be possible to have one shared uid/gid between the provider container and a consumer container while have set security.idmap.isolated=true and ids not shared between consumers?

# Steps to reproduce

 1. Create at least two containers with security.idmap.isolated=true
 2. Create a storage volume
 3. Attach storage volume as disk device to containers

**Comment by stgraber** [comment]
So current behavior is:
```
stgraber@castiana:~$ lxc launch ubuntu:16.04 c1 -c security.idmap.isolated=true
Creating c1
Starting c1

stgraber@castiana:~$ lxc launch ubuntu:16.04 c2 -c security.idmap.isolated=true
Creating c2
Starting c2

stgraber@castiana:~$ lxc storage volume create default shared
Storage volume shared created

stgraber@castiana:~$ lxc storage volume attach default shared c1 /data

stgraber@castiana:~$ lxc storage volume attach default shared c2 /data
error: Failed to setup device: Failed to initialize storage volume "shared" of type "custom" on storage pool "default": idmaps of container and storage volume are not identical.
```

That's indeed to avoid one of the containers seeing everything as owned by uid/gid -1.

There is a fairly new option of security.idmap.isolated that can be (ab)used to give two containers the same map while still keeping it different from all others.

```
stgraber@castiana:~$ lxc config get c1 volatile.idmap.base
1065536
stgraber@castiana:~$ lxc config set c1 security.idmap.base 1065536
stgraber@castiana:~$ lxc config set c2 security.idmap.base 1065536
stgraber@castiana:~$ lxc restart c2
stgraber@castiana:~$ lxc storage volume attach default shared c2 /data
```

This gets the map of the first container, makes it static for that first container, then configure the second to use the same map, restart the second container to remap it, at which point the storage volume can be attached.

**Comment by stgraber** [comment]
In your case however it does sound like you do want the individual idmap ranges and just rely on world readable and executable paths for the others to access it.

**Comment by stgraber** [comment]
One workaround is to properly attach the custom volume to the first container as shown above.
Then for the others use the old way of doing things by just bind-mounting the host path with:

    lxc config device add c2 shared disk path=/data source=/var/lib/lxd/storage-pools/default/custom/shared

**Comment by stgraber** [comment]
One option to make all of this a first class thing would be to add an attribute to the "disk" device type to specify that no remapping is expected. This would then let you bypass the normal remap check.

Not sure it's worth the extra complexity when the above syntax will effectively do the same and when there's shiftfs somewhere in the horizon which will let us avoid all those mapping issues in the future.

**Comment by monkz** [comment]
Ok, your bind mount in https://github.com/lxc/lxd/issues/3655#issuecomment-321931629 approach works.
Advantage: bindmounts can be set as read-only.
Disadvantage: the producer container has to autostart before all consumers. (but doable with boot.autostart.priority)

P.S.: Related Question: is it possible to create a profile that contains a variable, that is resolved later?
Like:
`lxc profile device add shareprofile sharedevice disk path=/data source=/var/lib/lxd/storage-pools/default/custom/shared/{$containername}`
to configure consumers solely via profiles?
