### ISSUE TITLE
Container stuck freezing and blocks rest of system

### ISSUE THREAD

**Issue by saulcosta18** [lxc/lxd#3658]
# Required information
Distribution:
```
Linux container-west1-plbw 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

lxc info (condensed):
```
core.https_address: '[::]:8443'
core.trust_password: true
images.auto_update_interval: "0"
driver: lxc
driver_version: 2.0.8
kernel: Linux
kernel_architecture: x86_64
kernel_version: 4.10.0-32-generic
server: lxd
server_pid: 3123
server_version: "2.16"
storage: zfs
storage_version: 0.6.5.9-2
```

# Issue description

I've run into an issue during which freezing a container (while in the process of stopping it) gets stuck, which leads to a high load average (I usually notice the first symptoms around 400, but it'll climb to 1000 if the server stays in use).

The process that seems to get stuck the most is an Apache 2 web server.

I've noted the timeout [here](https://github.com/lxc/lxd/commit/c591d8d730841dc53b9214f3c4181452a9681430), and am running LXD version 2.16.

Strangely, I can still interact with the remote API (e.g. checking container states), but cannot interact with LXD locally.

Here is the state of a stuck container:
```
{:architecture=>"x86_64",
 :config=>
  {:"volatile.base_image"=>
    "c8d365c36c1a9f411e65b027e7e72a3e308fcbeb34e2c6a15d94343e08650cf1",
   :"volatile.eth0.hwaddr"=>"00:16:3e:4c:a7:c4",
   :"volatile.eth0.name"=>"eth0",
   :"volatile.idmap.base"=>"0",
   :"volatile.idmap.next"=>
    "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]",
   :"volatile.last_state.idmap"=>
    "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]",
   :"volatile.last_state.power"=>"RUNNING"},
 :devices=>
  {:root=>{:path=>"/", :pool=>"default", :size=>"128MB", :type=>"disk"}},
 :ephemeral=>false,
 :profiles=>["default", "small"],
 :stateful=>false,
 :description=>"",
 :created_at=>2017-08-13 13:31:09 UTC,
 :expanded_config=>
  {:"environment.http_proxy"=>"",
   :"limits.cpu"=>"2-7",
   :"limits.cpu.allowance"=>"25%",
   :"limits.cpu.priority"=>"5",
   :"limits.disk.priority"=>"5",
   :"limits.memory"=>"256MB",
   :"limits.memory.enforce"=>"soft",
   :"limits.processes"=>"100",
   :"user.network_mode"=>"",
   :"volatile.base_image"=>
    "c8d365c36c1a9f411e65b027e7e72a3e308fcbeb34e2c6a15d94343e08650cf1",
   :"volatile.eth0.hwaddr"=>"00:16:3e:4c:a7:c4",
   :"volatile.eth0.name"=>"eth0",
   :"volatile.idmap.base"=>"0",
   :"volatile.idmap.next"=>
    "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]",
   :"volatile.last_state.idmap"=>
    "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]",
   :"volatile.last_state.power"=>"RUNNING"},
 :expanded_devices=>
  {:eth0=>{:nictype=>"bridged", :parent=>"lxdbr0", :type=>"nic"},
   :root=>{:path=>"/", :pool=>"default", :size=>"128MB", :type=>"disk"}},
 :name=>"production-ca1ac5e25d74777d-1502631069738",
 :status=>"Freezing",
 :status_code=>109,
 :last_used_at=>2017-08-13 13:31:19 UTC}
```

# Steps to reproduce
This is different from how I'm using it now (which involves never freezing containers), but previously these steps seemed to exacerbate the issue:

1. Start a lot of containers (~100 on a system with 8 CPUs and 30GB memory)
2. Freeze them all
3. Try to use the system to start other containers

# Information to attach
I lost my SSH shell to my last stuck server and it's not possible to regain it after you lose it, but will follow up with that information when another server dies.

**Comment by stgraber** [comment]
Next time this happens, can you get:
 - dmesg output
 - /var/log/lxd/lxd.log

This would help us see if it's something that LXD did which is causing problems or if you're running into kernel scheduling bugs around the freezing logic (which is unfortunately not that uncommon).

**Comment by saulcosta18** [comment]
Thank you for the fast response.

Not sure if relevant, but all schedulers (e.g. `/sys/block/sda/queue/scheduler`) appear to be set to `none`.

I'll followup with those logs once another server crashes, which seems to be occurring every few days.

**Comment by stgraber** [comment]
Those are I/O schedulers, the scheduler that's relevant here is the process scheduler which on most systems is going to be CFS (completely fair scheduler) and is what the various CPU related cgroups (cpu, cpuset, cpuacct and freezer) all integrate with.

**Comment by saulcosta18** [comment]
I had several servers trigger this issue overnight, [Gist here](https://gist.github.com/saulcosta18/471a4cbb4af543fc5fcfc193ad819562) with debugging info.

It looks like there's a `BUG` log line at `24585.875478` in the `dmesg` output, after which the output changes significantly.

I'll (try to) keep this SSH connection to this server open, in case there's other output that would be useful.

**Comment by stgraber** [comment]
Ouch, yeah, that's quite clearly a kernel bug. Looks like something went wrong while a cgroup was destroyed, causing any further interaction with the cgroup subsystem to deadlock, slowly causing all your processes to hang...

I don't believe there's much we can do for this at the LXD level. I'd strongly recommend filing a kernel bug for this. For the Ubuntu kernel, you can run "ubuntu-bug linux" or file a report directly at https://launchpad.net/ubuntu/+source/linux/+filebug

**Comment by saulcosta18** [comment]
Okay, thank you for the info. I'll file that with them.

In the meantime, any recommendations for ways to alleviate the issue? Maybe trying a different / older kernel or version of LXD?

**Comment by stgraber** [comment]
We've not changed that behavior in LXD in quite a while, so I'm not sure that changing LXD versions would help. Changing kernel versions might.

**Comment by saulcosta18** [comment]
To follow up, I have been running Linux 4.4.0-38 for 24 hours with no sign of an issue (currently running 7 servers, usually 1 would have triggered it by now).

Will report kernel bug to Linux and follow up here if anything changes or when I hear from them. Thanks for the help!
