### ISSUE TITLE
Rync failures on "lxc copy"

### ISSUE THREAD

**Issue by matt4d617474** [lxc/lxd#3663]
* Distribution: SuSE Linux Enterprise
 * Distribution version: 12 SP2
   * Kernel version: 4.4.21-69-default
   * LXC version: 2.5
   * LXD version: 2.5
   * Storage backend in use: directory on destination, btrfs on source

# Issue description

When performing "lxc copy <src> <dst>" on various directory storage-backend containers (so using rsync), we have rsync occasionally giving non-zero return codes.  Specifically, we have seen both error code 10 (...) and 12 (...).  These failure instances seem to be 100% repeatable but only fail on certain images.  It almost feels as though the transferred data in question causes the underlying websocket to fail.  This is *not* the rsync deadlock fixed in (I think) LXD v2.3+ where the "lxd netcat" subcommand performing unbuffered netcatting was added.

# Steps to reproduce

 1. lxc copy <src> <dst>

# Information to attach

Since we're running an older LXD, the rsync cmd/Exec bits only log to debug level.  But if you perform an "lxc monitor" on the destination, you can see the rsync non zero return codes.  I was able to manually rsync the data (with the same sort of helps employed by LXD, e.g., --devices and --numeric et al.).

My next debugging step is to binary search parts of the rootfs to find file (if any) is causing the underlying connection failures.

Note that on the same physical hosts, other copies/moves are proceeding without issue.  It appears to be specific to certain containers (so presuming rootfs contents).

Any help would be most appreciated.  Thanks much!

**Comment by brauner** [comment]
@matt4d617474, I think this is caused by `netcat` receiving `EINTR` which we didn't handle in earlier versions. I pushed a fix for this starting with `LXD 2.13` or `LXD 2.0.10`.

**Comment by matt4d617474** [comment]
Thanks for the heads up. And I assume you meant EAGAIN, right?  Will package up that newer version, try again and report back later today. Thanks again for the quick help.

**Comment by brauner** [comment]
Oh sorry, yes I meant `EAGAIN`; `EINTR` was a `liblxc` patch I was thinking about. :)

**Comment by matt4d617474** [comment]
I confirmed that running the latest version (went with the very latest at the time, v2.16) resolved the issue.  Note that I had to upgrade both sending and receiving side
