### ISSUE TITLE
lxc/lxd is no more go get'able

### ISSUE THREAD

**Issue by illarion** [lxc/lxd#3666]
When I try to get lxd in order to use it as dependency in my project (it worked few months ago), I get the following:

```
# go get github.com/lxc/lxd
package github.com/lxc/lxd: no buildable Go source files in /home/shaman/go/src/github.com/lxc/lxd
```
Am I doing something wrong? Maybe I should use some common library?

**Comment by stgraber** [comment]
LXD 2.15 deprecated github.com/lxc/lxd as a Go client library and its code was removed right after LXD 2.16 was released.

github.com/lxc/lxd/client should be used instead. http://godoc.org/lxc/lxd/client has the documentation for it.
