### ISSUE TITLE
Automated performance testing of LXD

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3670]
One thing we're currently missing right now is performance metrics for LXD so we can catch any change that severely regresses performance.

A good first pass would be:
 - Single container creation
 - Single container startup
 - Single container forceful stop
 - Single container delete
 - Parallel container launch (possibly using lxd-benchmark, spawn 128 containers in batches)
 - Parallel container delete

And do so for every storage backend that we support.

Note that this can't be in the normal testsuite as we'll need to run this on a dedicated test node which will offer us a consistent environment (same CPU, memory, storage and network).

All images used should be pre-fetched so that their download time doesn't affect the results (lxd-benchmark does that by default).

The output should be something that can be interpreted by jenkins as performance metrics so we can have it do the analysis and rendering for us.

**Comment by stgraber** [comment]
@albertodonato the machine we'll be using for this is "lantea" in the LXD MAAS.

**Comment by raginigupta6** [comment]
Hi, can we do stress testing using Apache bench on LXD containers?

**Comment by stgraber** [comment]
They're normal Linux systems so if you're running a web server in a container, sure, you can run ab2 against it.
