### ISSUE TITLE
Ceph storage - mapping issue

### ISSUE THREAD

**Issue by nickmaleao** [lxc/lxd#3674]
With the release of 2.16 version i im trying to do some tests with ceph.

I've build a ceph test lab and im able to map a image and use it with a fs , but i must disable some features on the image "rbd --pool lxd feature disable test exclusive-lock object-map fast-diff deep-flatten"

When lxd tries do create the container , it tries with de default settings "rbd --cluster ceph --pool lxd map container_first", when lxd tries to map the image "container_first" it gives a error

Container creation log:

root@osd2:/home/cephdeploy# lxc launch ubuntu:16.04 first
Creating first
error: Failed container creation:
 - https://cloud-images.ubuntu.com/releases: Failed to run: rbd --cluster ceph --pool lxd map container_first: rbd: sysfs write failed
RBD image feature set mismatch. You can disable features unsupported by the kernel with "rbd feature disable".
In some cases useful info is found in syslog - try "dmesg | tail" or so.
rbd: map failed: (6) No such device or address

Is there any way to pass additional ceph parameters with the container creation.

driver: lxc
driver_version: 2.0.8
kernel: Linux
kernel_architecture: x86_64
kernel_version: 4.11.0-14-generic
server: lxd
server_pid: 1417
server_version: "2.16"
storage: ceph
storage_version: ""

**Comment by stgraber** [comment]
I'm pretty sure this particular issue got fixed already. 4d0416053f8424d67d1e4accc0e6a7e00924aaf6

**Comment by stgraber** [comment]
@brauner can you confirm that this is indeed what you fixed?

**Comment by brauner** [comment]
@stgraber, yup that should be it. Clones can - for whatever reason - have more features than the snapshots they are based on. This commit makes them use the same minimal feature set that we use when creating images.

**Comment by stgraber** [comment]
Thanks for confirming, closing.
