### ISSUE TITLE
LXD fails to start without dnsmasq, even when it is not used

### ISSUE THREAD

**Issue by ntnn** [lxc/lxd#3678]
# Issue

LXD fails to start without dnsmasq, even when dnsmasq is not used to manage networks.

I use bind and dhcpd to manage my networks and hence I don't need dnsmasq. This worked as intended with version 2.8.

The earliest version I found which refuses to start without dnsmasq is 2.14.

# Steps to reproduce

1. Install LXD, e.g. via go get
2. Remove dnsmasq if installed
3. Attempt to start server
4. Get the following output:
```
error: exec: "dnsmasq": executable file not found in $PATH
```

**Comment by ntnn** [comment]
Virgil Drupas, the gentoo maintainer of lxd, found the bit of code preventing lxd to start without dnsmasq:
https://github.com/lxc/lxd/blob/2367206747d1105b9dbd90d2c3f02ffca40d28a7/lxd/main_daemon.go#L36

**Comment by hsoft** [comment]
For completeness: https://bugs.gentoo.org/show_bug.cgi?id=624096
