### ISSUE TITLE
Make default volume size configurable

### ISSUE THREAD

**Issue by jkroepke** [lxc/lxd#3679]
# Required information

 * Distribution: Ubuntu
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux cloud 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 2.0.8
   * LXD version: 2.16
   * Storage backend in use: btrfs

# Issue description

Default volume size should be configurable in storage pool.

Since I have a lot of issues with btrfs quotas ... For example (Disk quota exceeded) issue while we are far away from the limit.., I want to disable quotas completly.

See: https://github.com/lxc/lxd/blob/7f814c43a97dcd43dfc056f5197957c17520aa06/lxd/storage_volumes_config.go#L110

Please add an option to set the default size of storage volumes in the storage pool. Also add a pattern to disable the quota size.

**Comment by stgraber** [comment]
You can set the default volume size using the "volume.size" property on the pool.

**Comment by stgraber** [comment]
@brauner why do we set size=10GB for everything now? I thought this was meant to be only for block based volumes.

Can you fix and add a patch to fix all existing containers and images on upgrade (I confirmed that a new container on ZFS here shows up with size=10GB on the volume and gets enforced by ZFS)?

**Comment by jkroepke** [comment]
> You can set the default volume size using the "volume.size" property on the pool.

Only for lvm or ceph devices.
