### ISSUE TITLE
Don't purge storage pool if mount is root disk

### ISSUE THREAD

**Issue by jkroepke** [lxc/lxd#3680]
# Required information

 * Distribution: Ubuntu
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux cloud 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 2.0.8
   * LXD version: 2.16
   * Storage backend in use: btrfs

# Issue description

Today, I deleted a test storage pool on my new lxd server. There was a mistake on my etc/fstab, so the root disk was wrongly mounted on /var/lib/lxd/storage-pools/<pool name>

After deleting the pool with lxc storage delete <pool name>, my root disk was empty :-(

Can you add a detection on this tasks and if the condition is true add a big interactive warning on the screen. Just for the folks.

# Steps to reproduce

 1. mount root disk under /var/lib/lxd/storage-pools/<pool name>
 2. lxc storage create <pool name> 
 3. lxc storage delete <pool name> 

# Information to attach

all deleted :/

**Comment by stgraber** [comment]
What exactly did you do? The steps above are incorrect syntax so it's kinda hard to know exactly what happened.

**Comment by stgraber** [comment]
```
root@vm04:~# mount --bind / /var/lib/lxd/storage-pools/
root@vm04:~# lxc storage create default btrfs
Storage pool default created
root@vm04:~# lxc storage delete default
Storage pool default deleted
root@vm04:~# ls /
bin  boot  dev  etc  home  initrd.img  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  snap  srv  swap.img  sys  tmp  usr  var  vmlinuz
root@vm04:~# 
```

**Comment by jkroepke** [comment]
```
mkdir /var/lib/lxd/storage-pools/raw/
mount /dev/md3 /var/lib/lxd/storage-pools/raw/
lxc storage create raw dir
lxc storage list
+---------+-------------+--------+------------------------------------+---------+
|  NAME   | DESCRIPTION | DRIVER |               SOURCE               | USED BY |
+---------+-------------+--------+------------------------------------+---------+
| default |             | dir    | /var/lib/lxd/storage-pools/default | 1       |
+---------+-------------+--------+------------------------------------+---------+
| raw     |             | dir    | /var/lib/lxd/storage-pools/raw     | 0       |
+---------+-------------+--------+------------------------------------+---------+

lxc storage delete raw

error: remove /var/lib/lxd/storage-pools/raw/dev: device or resource busy

root@hades ~ # ls
-bash: ls: command not found
```

**Comment by stgraber** [comment]
@brauner can you make it so that all storage backends properly set volatile.pristine on create and then make the wiping conditional on that?

That should improve this kind of situation a bit.

**Comment by jkroepke** [comment]
/dev/md3 is the root device.

**Comment by brauner** [comment]
@stgraber, ha I knew we end up here. Good that we added this property with ceph. :)

**Comment by brauner** [comment]
@stgraber, this wouldn't have helped here at all would it? The pool would've been marked pristine on creation since it was empty on creation and then he would've overmounted it with some directory and we would've deleted it. So for this scenario there's really nothing we can do. If the pool is empty from a db point of view on delete but get's overmounted with something else you're hosed.

**Comment by jkroepke** [comment]
Maybe you purge only files managed by lxd like apt and yum does instead purge everythink

**Comment by stgraber** [comment]
@brauner the reproducing steps from the reporter are:
```
mkdir /var/lib/lxd/storage-pools/raw/
mount /dev/md3 /var/lib/lxd/storage-pools/raw/
lxc storage create raw dir```

So it very much wouldn't have been empty at creation time.

**Comment by brauner** [comment]
Ah, missed that.

**Comment by brauner** [comment]
Well, in that case we will simply refuse to create the pool I'd say. This is a folder under the control of LXD itself.

**Comment by brauner** [comment]
Also, this was one of the reasons why we didn't let users create dir storage pools somewhere on the system.
