### ISSUE TITLE
FEATURE: make ipv6 optional

### ISSUE THREAD

**Issue by asarubbo** [lxc/lxd#3688]
If possibile, would be great make the ipv6 support optional with something like --enable-ipv6 --disable-ipv6 at configure time

**Comment by stgraber** [comment]
If you don't want IPv6, just don't set an IPv6 address on your bridge. Why would we need a global configure flag for this?

**Comment by asarubbo** [comment]
I came from gentoo, where is my habit to always configure as minimal as possible.
The lxd installation on gentoo forced me to enable ipv6 where not needed for other things:
```
RDEPEND="
        daemon? (
                app-arch/xz-utils
                >=app-emulation/lxc-2.0.7[seccomp]
                net-dns/dnsmasq[dhcp,ipv6]
                net-misc/rsync[xattr]
                sys-apps/iproute2[ipv6]
                sys-fs/squashfs-tools
                virtual/acl
        )
"
```
To avoid complain I had to enable ipv6 in the kernel, which was previously disabled.
Also, usually, all software that has ipv6 support has always a ipv6 configure option to enable/disable
So making it optional would say to continue to avoid to pull what I won't use.

**Comment by asarubbo** [comment]
And the absence of ipv6 related things would make "lxd init" to fail as described in #3686

**Comment by stgraber** [comment]
Hmm, so a system that's missing IPv6 should be fine so long as you use "none" for ipv6.address. Looks like that's not quite the case right now, I'll send a fix for that.

Go doesn't really have the concept of configure flags that autotools does, it only does build tags which are a massive pain to make code conditional on, so the right fix here is just to make LXD not blow up when ip6tables is missing.

**Comment by asarubbo** [comment]
> Go doesn't really have the concept of configure flags that autotools does, it only does build tags which are a massive pain to make code conditional on, so the right fix here is just to make LXD not blow up when ip6tables is missing.

I don't remember if I suggested this on another place, but since what you said, how sounds make lxc-checkconfig to check only what related to ipv4 with something like: lxc-checkconfig --without-ipv6
