### ISSUE TITLE
unable to reduce the disk space

### ISSUE THREAD

**Issue by asarubbo** [lxc/lxd#3693]
* Distribution: Gentoo
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.9.34-gentoo
   * LXC version: 2.0.8
   * LXD version: 2.14
   * Storage backend in use: btrfs

I followed the steps reported here to reduce the disk of the container: https://stgraber.org/2016/03/26/lxd-2-0-resource-control-412/

however I don't get the same result:

```
ago@wanheda ~ $ lxc exec centos -- df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop0       45G  437M   43G   1% /

ago@wanheda ~ $ lxc config device set centos root size 20GB

ago@wanheda ~ $ lxc exec centos -- df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop0       45G  437M   43G   1% /
```

**Comment by stgraber** [comment]
btrfs quotas never show up in the df output. It's design limitation of btrfs. zfs, lvm and ceph will all appear in df.

**Comment by asarubbo** [comment]
ok, that's fine..but let me ask another question. When I made the btrfs storage pool, the size was 45GB.
Now I notice that something like **"lxc config device set centos root size 50GB"** works for me without issues.
Can I allocate now 50GB or it is just a virtual limit? In case I can't allocate, can I resize the btrfs pool?

**Comment by stgraber** [comment]
btrfs quotas can be bigger than the size of the filesystem (overcommit). I think the idea is that you'll grow you btrfs filesystem before the quota is reached.

**Comment by stgraber** [comment]
lxd itself doesn't know how to grow your btrfs filesystem, but you can do it directly yourself and things should be fine.

**Comment by asarubbo** [comment]
is documented somewhere if it is possible to do it via lxc client?

**Comment by stgraber** [comment]
It's not, that's why I said that lxd itself doesn't know how to do it

**Comment by stgraber** [comment]
You need to use the normal btrfs tools to do that
