### ISSUE TITLE
Templates and metadata.yaml

### ISSUE THREAD

**Issue by jfgibbins** [lxc/lxd#3695]
Playing around with some of the features I haven't used yet and came across the lxc config template commands.  Is there a way to also edit the corresponding metadata.yaml file in order to be able to use the created templates or is required to create an all new image?

**Comment by stgraber** [comment]
lxc config metadata edit?

**Comment by jfgibbins** [comment]
alright, I seriously need to increase my font size, or maybe the wife will let me get a 60" 4k as a monitor, it was there, just couldn't see it

**Comment by stgraber** [comment]
:)

**Comment by jfgibbins** [comment]
@stgraber  Just noticed, on the current 2.18 version at least, bash completion doesn't show metadata or templates.

**Comment by stgraber** [comment]
oh, yeah, that needs updating again... I'll send a branch.
