### ISSUE TITLE
Launch command completes before ubuntu user is added

### ISSUE THREAD

**Issue by ScottHaney** [lxc/lxd#3700]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-81-generic
   * LXC version: 2.0.8
   * LXD version: 2.15
   * Storage backend in use: zfs

# Issue description

The lxc launch command completes before the ubuntu user is actually added to the container. If a command soon after the lxc launch is looking for the ubuntu user then it won't be found. The issue appears to be timing related as inserting a sleep call after lxc launch fixes the issue for the examples that I have tried.

# Steps to reproduce

 1. Launch a new container and log into it as the ubuntu user using the following shell script

```
lxc launch ubuntu:16.04 test
lxc exec test -- su ubuntu -l
```

The result is "No passwd entry for user 'ubuntu'"

 2. Insert a sleep 10 in the same script so that it is as follows:

```
lxc launch ubuntu:16.04 test
sleep 10
lxc exec test -- su ubuntu -l
```
The script now works as expected.

**Comment by stgraber** [comment]
Hi,

As far as LXD's concerned, the container is launched when the init process in the container has started.
What happens during the container's boot sequence is out of LXD's control.

The "ubuntu" account creation is done through init scripts inside your container (by cloud-init) so LXD has nothing to do with that part of the boot sequence.

When scripting LXD, you can either add a fixed sleep as you did, or you can use a loop to check whether that user now exists. Something like this should work:

```
while :; do
    lxc exec test -- getent passwd ubuntu && break
    sleep 1
done
```
