### ISSUE TITLE
Missing descriptions in the github releases

### ISSUE THREAD

**Issue by akarelas** [lxc/lxd#3709]
You are not writing descriptions in the github releases, and we have no way of seeing "what is new". You can see the releases here: https://github.com/lxc/lxd/releases

This is bad documentation.

**Comment by stgraber** [comment]
https://linuxcontainers.org/lxd/news/

**Comment by stgraber** [comment]
Because Github provides a feature doesn't mean we have to use it, and there's no way of turning off the /releases page unfortunately (which also provides bad tarballs...).

**Comment by stgraber** [comment]
We can however update our README to link to the website.
