### ISSUE TITLE
Short image ids in lxc image list does not work

### ISSUE THREAD

**Issue by jensg-st** [lxc/lxd#371]
After importing an image, it shows up correctly in the image list with a 8 character long id. At this stage the shortened id can not be used as reference for e.g. 'launch'. During import I can not set an alias as well, so the image is not accessible by the client.

A fix could be to enable the client to set aliases during import. Either with something like: "--alias=alias1,alias2" or as a normal property. If there is one ore more "alias" in the property list, it is getting stored as alias for the image.

Setting an alias during an import is nice, but is it planned to support shortened image ids on the server?

Btw, isn't 8 characters maybe a bit too short? The probability of a collision is ~65k, if I'm not wrong.

I'm assuming it is a known issue, but just wanted to raise it. 

Like always, if I raise something, I'm happy to go for the fix/improvement.

**Comment by stgraber** [comment]
Hi,

So the goal was to do like git and use the first 12 chars of the sha256 in most user visible places but obviously still use the full sha256 behind the scene.

The plan is indeed for all commands to support the short hashes too.


As for setting aliases directly at import time, we could indeed add a --alias argument to "lxc image import" as we have in lxd-images. I think I'd prefer that to magically named properties that get converted into aliases. Ideally we'd support passing --alias=ALIAS multiple times as does lxd-images.

**Comment by stgraber** [comment]
I'm moving this to 0.4 and marked it release-critical because as it stands today, unless you happen to know the full hash, you can't really do anything with an image...

**Comment by jensg-st** [comment]
So, u prefer to have an additional '--' param? Or as part of the user params at the end with alias as "reserved" property?

**Comment by stgraber** [comment]
I think we should keep the behavior exactly as it is today but also accept the 12 chars short hash everywhere we accept the full one.

**Comment by stgraber** [comment]
Oh and the hash shown in image list should obviously be bumped to 12 chars as it should have been from the start...
