### ISSUE TITLE
Group issue after updating to 2.16

### ISSUE THREAD

**Issue by parak** [lxc/lxd#3711]
I'm getting a weird problem after updating to 2.16 (previous version worked fine) on Ubuntu 14.04. The upstart command fails with the following in the log:

```
WARN[08-23|19:06:32] CGroup memory swap accounting is disabled, swap limits will be ignored. 
error: unknown group lxd
error: LXD still not running after 600s timeout.
```

Yet the group definitely exists:
```
root@load2:/tmp# touch testfile
root@load2:/tmp# chown nobody:lxd testfile 
root@load2:/tmp# ls -lha testfile 
-rw-r--r-- 1 nobody lxd 0 Aug 23 19:28 testfile
```
Both stop and start fail in a similar manner, and the commands hang.

Weirder still is that this works on some instances just fine, yet fails on others, with the only common pattern being that the ones it fails on are m3.xlarge, and those that work are c3.2xlarge. Kernel (4.4.0-92-generic) and OS versions are the same.

Thanks!

**Comment by stgraber** [comment]
That's pretty weird...
Can you do:
 - sudo initctl stop lxd
 - sudo strace -fF -o debug lxd --debug --group lxd

And then post the "debug" file that strace will generate?

**Comment by parak** [comment]
Seems pretty short, so posting inline:

```
root@load2:~# initctl stop lxd
initctl: Unknown instance: 
root@load2:~# strace -fF -o debug lxd --debug --group lxd
INFO[08-23|19:38:27] LXD 2.16 is starting in setup mode       path=/var/lib/lxd
WARN[08-23|19:38:27] CGroup memory swap accounting is disabled, swap limits will be ignored. 
INFO[08-23|19:38:27] Kernel uid/gid map: 
INFO[08-23|19:38:27]  - u 0 0 4294967295 
INFO[08-23|19:38:27]  - g 0 0 4294967295 
INFO[08-23|19:38:27] Configured LXD uid/gid map: 
INFO[08-23|19:38:27]  - u 0 296608 65536 
INFO[08-23|19:38:27]  - g 0 296608 65536 
DBUG[08-23|19:38:27] No existing storage pools detected. 
INFO[08-23|19:38:27] Expiring log files 
INFO[08-23|19:38:27] Done expiring log files 
INFO[08-23|19:38:27] Starting /dev/lxd handler 
DBUG[08-23|19:38:27] Looking for existing certificates        cert=/var/lib/lxd/server.crt key=/var/lib/lxd/server.key
INFO[08-23|19:38:27] LXD isn't socket activated 
INFO[08-23|19:38:27] Connecting to a local LXD over a Unix socket 
INFO[08-23|19:38:27] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[08-23|19:38:27] Detected stale unix socket, deleting 
error: unknown group lxd
```

**Comment by stgraber** [comment]
What I need is the content of the "debug" file that strace generated.

**Comment by parak** [comment]
Oh, doh, sorry. Here you go.

[debug.zip](https://github.com/lxc/lxd/files/1246801/debug.zip)

**Comment by stgraber** [comment]
Can you attach a zip file with your /etc/nsswitch.conf and /etc/group files?
Looks like there's something weird going on when they're being parsed.

**Comment by parak** [comment]
Group file does contain some non-public information, so I can't quite just attach it.. anything I might be looking for?

**Comment by stgraber** [comment]
Anything that'd make the parser crash on it. It could be a line which is missing some fields, could be a duplicate line (same group name twice), ...

**Comment by stgraber** [comment]
Could also be a bad line-break (dos style instead of unix) or something like that

**Comment by parak** [comment]
I've looked at it with line endings turned on, checked for duplicates, missing fields, compared to a file from a working box, and so far I can't see anything :(

What parser is this using? I've checked that getent works, and the grp module in python works as well for example. Any way for me to just run the parser code itself?

**Comment by stgraber** [comment]
Can you download and run https://dl.stgraber.org/test-group (sha256: 887bfab785317b9b5e5b6359d446182e1c6fcf2b0e55dee47a643eb7b0df482c)

It's an isolated copy of the current group parsing code.
You can run it as an unprivileged user.

**Comment by parak** [comment]
Aha, I think I found it. The affected nodes have a group with more users in it than other nodes. Specifically, they have a group with 81 users in it. With a bit of experimentation, the lxd group works when there are 64 users in the group, but not 65 or higher, producing the 'unknown group lxd' error.

**Comment by stgraber** [comment]
And that's a group other than the lxd group right?

**Comment by parak** [comment]
Correct.

**Comment by stgraber** [comment]
And does the test binary I gave you show the same error?

**Comment by parak** [comment]
Yep.
