### ISSUE TITLE
Docker requirements

### ISSUE THREAD

**Issue by jfgibbins** [lxc/lxd#3712]
Using LXD to test some docker stuff.  Had issues with overlays running in the ver 1.12+ swarm due to modprobe, particularly br_filter.  Modules loaded on the host and the kernel usually solves for most problems, but did not for this particular case.  Found an old reference #2321, referred to adding a file /.dockerenv as the docker code uses it as a marker that it is virtualized and stop default behavior of loading modules already loaded.  Suggestion, add to front page, where I believe @brauner had added that 'security.nesting = true' replaced the need for profile docker.  Hopefully save some others time searching when they try out or upgrade to the new version of swarm.
FYI:  lxc/lxd is better than docker. :)

**Comment by jfgibbins** [comment]
@brauner Way better than my incoherent mess that I wrote. You the man. :)

**Comment by brauner** [comment]
@jfgibbins, well thank you for the compliment but I'm passing it along to @stgraber since I'm just the merger not the mergee. :)

**Comment by techtonik** [comment]
This ticket is about `network overlay`s for Docker, right? Is it some Docker-specific solution or a common Linux mechanism?

**Comment by jfgibbins** [comment]
@techtonik docker looks for a file called /.dockerenv as a marker to if it is running inside a virtual environment.  When the file is detected, docker changes its behavior on certain aspects, such as trying to force load of modules, which of course can't be done inside lxd containers.  The mechanism seems to be applied to any hosted environment.  Hope that answers what you were looking for.

**Comment by techtonik** [comment]
This answers partially. `/.dockerenv` from #2321 is still looks like a hack, but I am not sure if it is a Docker hack or Linux kernel. From what I can understand the problem is either:

1. Docker can't load some `overlay network` module
2. Docker can't detect that `overlay network` module is loaded

So, if I understand correctly, we are dealing with the 2nd problem. Then the question is - why Docker is unable to detect that its kernel modules are loaded?

**Comment by jfgibbins** [comment]
@techtonik From my research, it seems that docker, tries to force load the modules it needs, regardless of whether it is already loaded or not.  .dockerenv was added into the docker code, to allow it to know if it inside a container or not, and if so, don't force the behavior.  This enabled, for example, running docker-in-docker and such.  Trying to find the link where I found the source code inside docker for it.

**Comment by stgraber** [comment]
Can someone contribute a simple check to Docker to look at /sys/modules/NAME prior to attempting a force load of the module?

**Comment by stgraber** [comment]
that should be a pretty trivial and uncontroversial change that would most likely resolve this particular issue

**Comment by jfgibbins** [comment]
@techtonik From docker code, which is how .dockerenv is used, as well as the code that was giving me the issue running overlay

https://github.com/docker/libnetwork/blob/master/drivers/bridge/setup_bridgenetfiltering.go
func isRunningInContainer() bool {
	_, err := os.Stat("/.dockerenv")
	return !os.IsNotExist(err)
}

https://github.com/docker/libnetwork/blob/19ac3ea7f52bb46e0eb10669756cdae0c441a5b1/drivers/bridge/setup_bridgenetfiltering.go

func setupBridgeNetFiltering(config *networkConfiguration, i *bridgeInterface) error {
	err := checkBridgeNetFiltering(config, i)
	if err != nil {
		if ptherr, ok := err.(*os.PathError); ok {
			if errno, ok := ptherr.Err.(syscall.Errno); ok && errno == syscall.ENOENT {
				if isRunningInContainer() {
					logrus.Warnf("running inside docker container, ignoring missing kernel params: %v", err)
					err = nil
				} else {
					err = errors.New("please ensure that br_netfilter kernel module is loaded")
				}
			}
		}
		if err != nil {
			return fmt.Errorf("cannot restrict inter-container communication: %v", err)
		}
	}
	return nil
}

**Comment by jfgibbins** [comment]
@stgraber I believe you mean into docker code to check that, and that would certainly fix the issue for that, but I did see reference to isRunningInContainer throughout the docker code, so wouldn't even want to guess how many things need that check.  I would stay safe with just adding the file, rather than additional code to handle case by case issues as they seem to have already done that in code, ie docker-in-docker.

**Comment by techtonik** [comment]
I see `isRunningInContainer` only in `setup_bridgenetfiltering.go` - everything else are tests - https://github.com/docker/libnetwork/search?utf8=%E2%9C%93&q=isRunningInContainer&type=

https://github.com/moby/moby/search?utf8=%E2%9C%93&q=isRunningInContainer&type=

**Comment by techtonik** [comment]
@jfgibbins I don't see where Docker force loads the module in https://github.com/docker/libnetwork/blob/master/drivers/bridge/setup_bridgenetfiltering.go

It checks file `/proc/sys/net/bridge/bridge-nf-call-iptables` and writes to it, but I see no module manipulation.
