### ISSUE TITLE
lxd 2.12: lxc remote add ask for password even if client certificate is added and core.trust_password unset

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#3714]
# Required information

 * Distribution: ubuntu 
 * Distribution version: 17.04
 * The output of "lxc info" 
side 1:
config:
  core.https_address: :8443
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - :8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
[ ... ]
  certificate_fingerprint: ea854278d6e269bb441c2b59b3407ff2a90459486478cefc439d9750e3b2afd9
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-32-generic
  server: lxd
  server_pid: 3920
  server_version: "2.12"
  storage: btrfs
  storage_version: 4.9.1

 side 2:

config:
  core.https_address: :8443
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - :8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
[ ... ]
    -----END CERTIFICATE-----
  certificate_fingerprint: 914053808c99507cab223a10fbdb36f71f2a760c6fad6215f13bba883f4fe0d4
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-22-generic
  server: lxd
  server_pid: 1864
  server_version: "2.12"
  storage: dir
  storage_version: "1"

# Issue description

We can't add a new remote even if we add client.crt on both side: admin password is asked and even if we unset core.trust_password
 

# Steps to reproduce

 1. lxc config trust add  other-side-client.crt.
 2. lxc config unset core.trust_password (work the same if we let it true)
 3. lxc remote add XXX https://IP:8443 --accept-certificate 

result: aadmin password for XXX:

Regards.

**Comment by gaetanquentin** [comment]
it looks like if this pb occurs only in root account. My colleague created a new user account and regenerate a certificate: it works now.

**Comment by stgraber** [comment]
I wonder if it can be as simple as you running under "sudo -s" which would use your user's home directory rather than root's. In which case uploading /root/.config/lxc/client.crt to the target server won't do you much good as the certificate that's actually used is /home/some-user/.config/lxc/client.crt.

**Comment by stgraber** [comment]
Can you show:
 - "lxc config trust list" on the remote server
 - "openssl x509 -in ~/.config/lxc/client.crt -noout -text -fingerprint -sha256" on the client

**Comment by stgraber** [comment]
Assuming it was the simple sudo issue highlighted above, so closing this issue. Feel free to comment with the information requested above if it's not a simple confusion between /root/.config/lxc and /home/USER/.config/lxc.
