### ISSUE TITLE
Live Migration fails

### ISSUE THREAD

**Issue by R3curve** [lxc/lxd#3715]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2 LTS
 * The output of "lxc info" or if that fails:
  Host 1
      config:
      core.https_address: 192.168.1.100:8443
      core.trust_password: true
    api_extensions:
    - storage_zfs_remove_snapshots
    - container_host_shutdown_timeout
    - container_syscall_filtering
    - auth_pki
    - container_last_used_at
    - etag
    - patch
    - usb_devices
    - https_allowed_credentials
    - image_compression_algorithm
    - directory_manipulation
    - container_cpu_time
    - storage_zfs_use_refquota
    - storage_lvm_mount_options
    - network
    - profile_usedby
    - container_push
    - container_exec_recording
    - certificate_update
    - container_exec_signal_handling
    - gpu_devices
    - container_image_properties
    - migration_progress
    - id_map
    - network_firewall_filtering
    - network_routes
    - storage
    - file_delete
    - file_append
    - network_dhcp_expiry
    - storage_lvm_vg_rename
    - storage_lvm_thinpool_rename
    - network_vlan
    - image_create_aliases
    - container_stateless_copy
    - container_only_migration
    - storage_zfs_clone_copy
    - unix_device_rename
    - storage_lvm_use_thinpool
    - storage_rsync_bwlimit
    - network_vxlan_interface
    - storage_btrfs_mount_options
    - entity_description
    - image_force_refresh
    - storage_lvm_lv_resizing
    - id_map_base
    - file_symlinks
    - container_push_target
    - network_vlan_physical
    - storage_images_delete
    - container_edit_metadata
    - container_snapshot_stateful_migration
    - storage_driver_ceph
    - storage_ceph_user_name
    - resource_limits
    - storage_volatile_initial_source
    api_status: stable
    api_version: "1.0"
    auth: trusted
    public: false
    environment:
      addresses:
      - 192.168.1.100:8443
      architectures:
      - x86_64
      - i686
      certificate: |
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      certificate_fingerprint: ...
    driver: lxc
    driver_version: 2.0.8
    kernel: Linux
    kernel_architecture: x86_64
    kernel_version: 4.12.0-rc7+
    server: lxd
    server_pid: 62725
    server_version: "2.17"
    storage: dir
    storage_version: "1"`

Host 2 (differs only in Kernel version)
kernel_version: 4.12.1-041201-generic

# Issue description

Live migration from Host 1 to Host 2 (Host 2 to Host 1) fails due to a failing action script in criu. If I execute the Command from the ActionScript manually, I get: 'error: malformed ws or wss URL'

# Steps to reproduce

 1. #host1: lxc move adequate-racer host2:

# Information to attach
- Actionscript

```bash
 #!/bin/sh -e
if [ "$CRTOOLS_SCRIPT_ACTION" = "post-dump" ]; then
        /usr/bin/lxd migratedumpsuccess /1.0/operations/13f206a9-40ac-4bfb-aaf3-79879fd6298b 07610509a463d542b55e6a838814a269d917ee7d667354da9f21efc92234f88b
fi
```
 - [x] output of the daemon with --debug

> lvl=info msg="LXD 2.17 is starting in normal mode" path=/var/lib/lxd t=2017-08-24T13:52:09+0200
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-08-24T13:52:09+0200
lvl=info msg="Kernel uid/gid map:" t=2017-08-24T13:52:09+0200
lvl=info msg=" - u 0 0 4294967295" t=2017-08-24T13:52:09+0200
lvl=info msg=" - g 0 0 4294967295" t=2017-08-24T13:52:09+0200
lvl=info msg="Configured LXD uid/gid map:" t=2017-08-24T13:52:09+0200
lvl=info msg=" - u 0 165536 65536" t=2017-08-24T13:52:09+0200
lvl=info msg=" - g 0 165536 65536" t=2017-08-24T13:52:09+0200
lvl=dbug msg="Initializing and checking storage pool "default"." t=2017-08-24T13:52:09+0200
lvl=dbug msg="Initializing a DIR driver." t=2017-08-24T13:52:09+0200
lvl=dbug msg="Checking DIR storage pool "default"." t=2017-08-24T13:52:09+0200
lvl=info msg="Connecting to a remote simplestreams server" t=2017-08-24T13:52:09+0200
lvl=info msg="Expiring log files" t=2017-08-24T13:52:09+0200
lvl=info msg="Done expiring log files" t=2017-08-24T13:52:09+0200
lvl=info msg="Starting /dev/lxd handler" t=2017-08-24T13:52:09+0200
cert=/var/lib/lxd/server.crt key=/var/lib/lxd/server.key lvl=dbug msg="Looking for existing certificates" t=2017-08-24T13:52:09+0200
lvl=info msg="LXD isn't socket activated" t=2017-08-24T13:52:09+0200
lvl=info msg="REST API daemon:" t=2017-08-24T13:52:09+0200
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2017-08-24T13:52:09+0200
lvl=info msg=" - binding TCP socket" socket=192.168.1.100:8443 t=2017-08-24T13:52:09+0200
lvl=info msg="Pruning expired images" t=2017-08-24T13:52:09+0200
lvl=info msg="Updating instance types" t=2017-08-24T13:52:09+0200
lvl=info msg="Updating images" t=2017-08-24T13:52:09+0200
lvl=info msg="Done pruning expired images" t=2017-08-24T13:52:09+0200
alias=default fp=58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08 lvl=dbug msg="Processing image" protocol=simplestreams server=https://cloud-images.ubuntu.com/releases t=2017-08-24T13:52:09+0200
lvl=info msg="Connecting to a remote simplestreams server" t=2017-08-24T13:52:09+0200
image=58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08 lvl=dbug msg="Image already exists in the db" t=2017-08-24T13:52:10+0200
fp=58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08 lvl=dbug msg="Already up to date" t=2017-08-24T13:52:10+0200
lvl=info msg="Done updating images" t=2017-08-24T13:52:10+0200
lvl=info msg="Done updating instance types" t=2017-08-24T13:52:11+0200
ip=@ lvl=dbug method=GET msg=handling t=2017-08-24T13:52:28+0200 url=/1.0
lvl=dbug msg="Initializing a DIR driver." t=2017-08-24T13:52:28+0200
lvl=dbug msg="
	{
		"type": "sync",
		"status": "Success",
		"status_code": 200,
		"operation": "",
		"error_code": 0,
		"error": "",
		"metadata": {
			"config": {
				"core.https_address": "192.168.1.100:8443",
				"core.trust_password": true
			},
			"api_extensions": [
				"storage_zfs_remove_snapshots",
				"container_host_shutdown_timeout",
				"container_syscall_filtering",
				"auth_pki",
				"container_last_used_at",
				"etag",
				"patch",
				"usb_devices",
				"https_allowed_credentials",
				"image_compression_algorithm",
				"directory_manipulation",
				"container_cpu_time",
				"storage_zfs_use_refquota",
				"storage_lvm_mount_options",
				"network",
				"profile_usedby",
				"container_push",
				"container_exec_recording",
				"certificate_update",
				"container_exec_signal_handling",
				"gpu_devices",
				"container_image_properties",
				"migration_progress",
				"id_map",
				"network_firewall_filtering",
				"network_routes",
				"storage",
				"file_delete",
				"file_append",
				"network_dhcp_expiry",
				"storage_lvm_vg_rename",
				"storage_lvm_thinpool_rename",
				"network_vlan",
				"image_create_aliases",
				"container_stateless_copy",
				"container_only_migration",
				"storage_zfs_clone_copy",
				"unix_device_rename",
				"storage_lvm_use_thinpool",
				"storage_rsync_bwlimit",
				"network_vxlan_interface",
				"storage_btrfs_mount_options",
				"entity_description",
				"image_force_refresh",
				"storage_lvm_lv_resizing",
				"id_map_base",
				"file_symlinks",
				"container_push_target",
				"network_vlan_physical",
				"storage_images_delete",
				"container_edit_metadata",
				"container_snapshot_stateful_migration",
				"storage_driver_ceph",
				"storage_ceph_user_name",
				"resource_limits",
				"storage_volatile_initial_source"
			],
			"api_status": "stable",
			"api_version": "1.0",
			"auth": "trusted",
			"public": false,
			"environment": {
				"addresses": [
					"192.168.1.100:8443"
				],
				"architectures": [
					"x86_64",
					"i686"
				],
				"certificate": "-----BEGIN CERTIFICATE-----\\XXX\
",
				"certificate_fingerprint": "XXX",
				"driver": "lxc",
				"driver_version": "2.0.8",
				"kernel": "Linux",
				"kernel_architecture": "x86_64",
				"kernel_version": "4.12.0-rc7+",
				"server": "lxd",
				"server_pid": 28283,
				"server_version": "2.17",
				"storage": "dir",
				"storage_version": "1"
			}
		}
	}" t=2017-08-24T13:52:28+0200
ip=@ lvl=dbug method=GET msg=handling t=2017-08-24T13:52:28+0200 url=/1.0/containers/adequate-racer
lvl=dbug msg="
	{
		"type": "sync",
		"status": "Success",
		"status_code": 200,
		"operation": "",
		"error_code": 0,
		"error": "",
		"metadata": {
			"architecture": "x86_64",
			"config": {
				"image.architecture": "amd64",
				"image.description": "ubuntu 16.04 LTS amd64 (release) (20170815.1)",
				"image.label": "release",
				"image.os": "ubuntu",
				"image.release": "xenial",
				"image.serial": "20170815.1",
				"image.version": "16.04",
				"volatile.base_image": "58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08",
				"volatile.idmap.base": "0",
				"volatile.idmap.next": "[{\\"Isuid\\":true,\\"Isgid\\":false,\\"Hostid\\":165536,\\"Nsid\\":0,\\"Maprange\\":65536},{\\"Isuid\\":false,\\"Isgid\\":true,\\"Hostid\\":165536,\\"Nsid\\":0,\\"Maprange\\":65536}]",
				"volatile.last_state.idmap": "[{\\"Isuid\\":true,\\"Isgid\\":false,\\"Hostid\\":165536,\\"Nsid\\":0,\\"Maprange\\":65536},{\\"Isuid\\":false,\\"Isgid\\":true,\\"Hostid\\":165536,\\"Nsid\\":0,\\"Maprange\\":65536}]",
				"volatile.last_state.power": "RUNNING"
			},
			"devices": {},
			"ephemeral": false,
			"profiles": [
				"migration_no_nic"
			],
			"stateful": false,
			"description": "",
			"created_at": "2017-08-24T11:15:36Z",
			"expanded_config": {
				"image.architecture": "amd64",
				"image.description": "ubuntu 16.04 LTS amd64 (release) (20170815.1)",
				"image.label": "release",
				"image.os": "ubuntu",
				"image.release": "xenial",
				"image.serial": "20170815.1",
				"image.version": "16.04",
				"raw.lxc": "lxc.aa_allow_incomplete = 1",
				"volatile.base_image": "58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08",
				"volatile.idmap.base": "0",
				"volatile.idmap.next": "[{\\"Isuid\\":true,\\"Isgid\\":false,\\"Hostid\\":165536,\\"Nsid\\":0,\\"Maprange\\":65536},{\\"Isuid\\":false,\\"Isgid\\":true,\\"Hostid\\":165536,\\"Nsid\\":0,\\"Maprange\\":65536}]",
				"volatile.last_state.idmap": "[{\\"Isuid\\":true,\\"Isgid\\":false,\\"Hostid\\":165536,\\"Nsid\\":0,\\"Maprange\\":65536},{\\"Isuid\\":false,\\"Isgid\\":true,\\"Hostid\\":165536,\\"Nsid\\":0,\\"Maprange\\":65536}]",
				"volatile.last_state.power": "RUNNING"
			},
			"expanded_devices": {
				"root": {
					"path": "/",
					"pool": "default",
					"type": "disk"
				}
			},
			"name": "adequate-racer",
			"status": "Running",
			"status_code": 103,
			"last_used_at": "2017-08-24T11:46:50.022420399Z"
		}
	}" t=2017-08-24T13:52:28+0200
ip=@ lvl=dbug method=GET msg=handling t=2017-08-24T13:52:28+0200 url=/1.0/events
lvl=dbug msg="New events listener: 48abc2df-4ca3-48e8-b098-eb263f8b9ee8" t=2017-08-24T13:52:28+0200
ip=@ lvl=dbug method=POST msg=handling t=2017-08-24T13:52:28+0200 url=/1.0/containers/adequate-racer
lvl=dbug msg="
	{
		"name": "",
		"migration": true,
		"live": true,
		"container_only": false,
		"target": null
	}" t=2017-08-24T13:52:28+0200
lvl=dbug msg="New websocket operation: f02725a5-cb5c-4445-a6e4-f0f4becb804d" t=2017-08-24T13:52:28+0200
lvl=dbug msg="Started websocket operation: f02725a5-cb5c-4445-a6e4-f0f4becb804d" t=2017-08-24T13:52:28+0200
lvl=dbug msg="
	{
		"type": "async",
		"status": "Operation created",
		"status_code": 100,
		"operation": "/1.0/operations/f02725a5-cb5c-4445-a6e4-f0f4becb804d",
		"error_code": 0,
		"error": "",
		"metadata": {
			"id": "f02725a5-cb5c-4445-a6e4-f0f4becb804d",
			"class": "websocket",
			"created_at": "2017-08-24T13:52:28.25262484+02:00",
			"updated_at": "2017-08-24T13:52:28.25262484+02:00",
			"status": "Running",
			"status_code": 103,
			"resources": {
				"containers": [
					"/1.0/containers/adequate-racer"
				]
			},
			"metadata": {
				"control": "260c2a23cbc34b3c7b6d9d1b2cd89f1b3703830def615633e038af2767ce4680",
				"criu": "110cb95a09c58a5e152775deb0634ebe5a8eacf991d26bddf403f63944a9e54b",
				"fs": "e77d87e8e81b16ac8bb44bb8ea4b098879437b4c94bcdc7c0616d4098c0df517"
			},
			"may_cancel": false,
			"err": ""
		}
	}" t=2017-08-24T13:52:28+0200
ip=192.168.1.200:54168 lvl=dbug msg="allowing untrusted GET" t=2017-08-24T13:52:30+0200 url="/1.0/operations/f02725a5-cb5c-4445-a6e4-f0f4becb804d/websocket?secret=260c2a23cbc34b3c7b6d9d1b2cd89f1b3703830def615633e038af2767ce4680"
lvl=dbug msg="Connected websocket operation: f02725a5-cb5c-4445-a6e4-f0f4becb804d" t=2017-08-24T13:52:30+0200
lvl=dbug msg="Handled websocket operation: f02725a5-cb5c-4445-a6e4-f0f4becb804d" t=2017-08-24T13:52:30+0200
ip=192.168.1.200:54170 lvl=dbug msg="allowing untrusted GET" t=2017-08-24T13:52:30+0200 url="/1.0/operations/f02725a5-cb5c-4445-a6e4-f0f4becb804d/websocket?secret=e77d87e8e81b16ac8bb44bb8ea4b098879437b4c94bcdc7c0616d4098c0df517"
lvl=dbug msg="Connected websocket operation: f02725a5-cb5c-4445-a6e4-f0f4becb804d" t=2017-08-24T13:52:30+0200
lvl=dbug msg="Handled websocket operation: f02725a5-cb5c-4445-a6e4-f0f4becb804d" t=2017-08-24T13:52:30+0200
ip=192.168.1.200:54172 lvl=dbug msg="allowing untrusted GET" t=2017-08-24T13:52:30+0200 url="/1.0/operations/f02725a5-cb5c-4445-a6e4-f0f4becb804d/websocket?secret=110cb95a09c58a5e152775deb0634ebe5a8eacf991d26bddf403f63944a9e54b"
lvl=dbug msg="Connected websocket operation: f02725a5-cb5c-4445-a6e4-f0f4becb804d" t=2017-08-24T13:52:30+0200
lvl=dbug msg="Handled websocket operation: f02725a5-cb5c-4445-a6e4-f0f4becb804d" t=2017-08-24T13:52:30+0200
lvl=dbug msg="Initializing a DIR driver." t=2017-08-24T13:52:30+0200
lvl=dbug msg="Got message barrier, resetting stream" t=2017-08-24T13:52:31+0200
lvl=dbug msg="sending write barrier" t=2017-08-24T13:52:31+0200
lvl=dbug msg="New websocket operation: 13f206a9-40ac-4bfb-aaf3-79879fd6298b" t=2017-08-24T13:52:31+0200
lvl=dbug msg="Started websocket operation: 13f206a9-40ac-4bfb-aaf3-79879fd6298b" t=2017-08-24T13:52:31+0200
actionscript=true created=2017-08-24T11:15:36+0000 ephemeral=false lvl=info msg="Migrating container" name=adequate-racer statedir=/tmp/lxd_checkpoint_823362115 stop=true t=2017-08-24T13:52:31+0200 used=2017-08-24T11:46:50+0000
ip=@ lvl=dbug method=GET msg=handling t=2017-08-24T13:52:34+0200 url=/1.0
lvl=dbug msg="Initializing a DIR driver." t=2017-08-24T13:52:34+0200
lvl=dbug msg="
	{
		"type": "sync",
		"status": "Success",
		"status_code": 200,
		"operation": "",
		"error_code": 0,
		"error": "",
		"metadata": {
			"config": {
				"core.https_address": "192.168.1.100:8443",
				"core.trust_password": true
			},
			"api_extensions": [
				"storage_zfs_remove_snapshots",
				"container_host_shutdown_timeout",
				"container_syscall_filtering",
				"auth_pki",
				"container_last_used_at",
				"etag",
				"patch",
				"usb_devices",
				"https_allowed_credentials",
				"image_compression_algorithm",
				"directory_manipulation",
				"container_cpu_time",
				"storage_zfs_use_refquota",
				"storage_lvm_mount_options",
				"network",
				"profile_usedby",
				"container_push",
				"container_exec_recording",
				"certificate_update",
				"container_exec_signal_handling",
				"gpu_devices",
				"container_image_properties",
				"migration_progress",
				"id_map",
				"network_firewall_filtering",
				"network_routes",
				"storage",
				"file_delete",
				"file_append",
				"network_dhcp_expiry",
				"storage_lvm_vg_rename",
				"storage_lvm_thinpool_rename",
				"network_vlan",
				"image_create_aliases",
				"container_stateless_copy",
				"container_only_migration",
				"storage_zfs_clone_copy",
				"unix_device_rename",
				"storage_lvm_use_thinpool",
				"storage_rsync_bwlimit",
				"network_vxlan_interface",
				"storage_btrfs_mount_options",
				"entity_description",
				"image_force_refresh",
				"storage_lvm_lv_resizing",
				"id_map_base",
				"file_symlinks",
				"container_push_target",
				"network_vlan_physical",
				"storage_images_delete",
				"container_edit_metadata",
				"container_snapshot_stateful_migration",
				"storage_driver_ceph",
				"storage_ceph_user_name",
				"resource_limits",
				"storage_volatile_initial_source"
			],
			"api_status": "stable",
			"api_version": "1.0",
			"auth": "trusted",
			"public": false,
			"environment": {
				"addresses": [
					"192.168.1.100:8443"
				],
				"architectures": [
					"x86_64",
					"i686"
				],
				"certificate": "-----BEGIN CERTIFICATE-----\\XXX\
-----END CERTIFICATE-----\
",
				"certificate_fingerprint": "XXX",
				"driver": "lxc",
				"driver_version": "2.0.8",
				"kernel": "Linux",
				"kernel_architecture": "x86_64",
				"kernel_version": "4.12.0-rc7+",
				"server": "lxd",
				"server_pid": 28283,
				"server_version": "2.17",
				"storage": "dir",
				"storage_version": "1"
			}
		}
	}" t=2017-08-24T13:52:34+0200
actionscript=true created=2017-08-24T11:15:36+0000 ephemeral=false lvl=info msg="Failed migrating container" name=adequate-racer statedir=/tmp/lxd_checkpoint_823362115 stop=true t=2017-08-24T13:52:34+0200 used=2017-08-24T11:46:50+0000
lvl=dbug msg="Failure for websocket operation: f02725a5-cb5c-4445-a6e4-f0f4becb804d: migration dump failed
(01.232064) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 27871 with interrupted system call
(01.524483) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 27877 with interrupted system call
(01.524617) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 27899 with interrupted system call
(02.060648) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 27884 with interrupted system call
(02.061290) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 27900 with interrupted system call
(02.358667) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 27882 with interrupted system call
(02.614446) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 27883 with interrupted system call
(03.135625) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 27914 with interrupted system call
(03.392518) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 27917 with interrupted system call
(03.392721) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 27920 with interrupted system call
(03.916794) Error (criu/util.c:669): exited, status=1
(03.916822) Error (criu/action-scripts.c:94): Script /tmp/lxd_checkpoint_823362115/action.sh exited with -1
(03.916835) Error (criu/action-scripts.c:138): One of more action scripts failed" t=2017-08-24T13:52:34+0200

**Comment by R3curve** [comment]
Thanks for the quick fix! I pulled the current master and build it on both servers. The live migration still fails, it says the action script fails.

> EROR[08-28|09:51:21] dump failed after successful restore?: "migration dump failed
> (01.227562) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 18963 with interrupted system call
> (01.764598) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 18968 with interrupted system call
> (02.001299) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 18973 with interrupted system call
> (02.001582) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 18995 with interrupted system call
> (02.297123) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 18988 with interrupted system call
> (02.297975) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 19014 with interrupted system call
> (02.603021) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 18997 with interrupted system call
> (03.148319) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 19031 with interrupted system call
> (03.445277) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 19040 with interrupted system call
> (03.445502) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 19049 with interrupted system call
> (05.169873) Error (criu/util.c:669): exited, status=1
> (05.169899) Error (criu/action-scripts.c:94): Script /tmp/lxd_checkpoint_871848983/action.sh exited with -1
> (05.169911) Error (criu/action-scripts.c:138): One of more action scripts failed" 
> error: Failed container creation:
>  - https://192.168.1.200:8443: Error transferring container data: migration restore failed
> (00.011246) Error (criu/cgroup.c:1642): cg: 	Can't mount controller dir .criu.cgyard.5qTVot/rdma: No such file or directory

To narrow down the problem I tried a "lightweight" live migration, meaning I did a snapshot of the container moved the container and restored it, leading to the following issue:

> EROR[08-28|14:38:04] stop hook failed container=adequate-racer err="Container is already running a start operation"
> error: snapshot restore failed
> (00.014282) Error (criu/cgroup.c:1642): cg: Can't mount controller dir .criu.cgyard.MKCRE9/rdma: No such file or directory

First, I expected it to be a problem with CRIU but I tested the "lightweight" migration with lxd-2.16 and it worked seamlessly.

I am not sure if this bug is related to this issue or if I should open a new one.

**Comment by brauner** [comment]
The `rdma` cgroup controller is a fairly recent addition in kernels. CRIU tries to restore this mount on a system that doesn't support the `rdma` controller apparently and it fails. It seems CRIU is not handling controller mismatch. This is unrelated to LXD.
