### ISSUE TITLE
creating a container in ceph storage

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#3716]
After updating into lxd 2.16 on my ubuntu 16.04 LTS, wanted to make a try with new lxd storage feature :  ceph storage as i 've a ceph cluster for a while.

Here what i did  : 

     root@inxovh-hy001 (node1):~# lxc storage create lxd-pool ceph
     Storage pool lxd-pool created

     root@inxovh-hy001 (node1):~# ceph osd lspools
     0 data,6 libvirt-pool,7 .rgw.root,9 lxd-pool,

     root@inxovh-hy001 (node1):~# lxc storage list
     +----------+-------------+--------+-----------+---------+
     |   NAME   | DESCRIPTION | DRIVER |  SOURCE   | USED BY |
     +----------+-------------+--------+-----------+---------+
     | default  |             | zfs    | zdata/lxd | 27      |
     +----------+-------------+--------+-----------+---------+
     | lxd-pool |             | ceph   | lxd-pool  | 0       |
     +----------+-------------+--------+-----------+---------+

     root@inxovh-hy001 (node1):~#  lxc launch ubuntu-xenial-infranix inxovh-nli5001 -s lxd-pool
     Creating inxovh-nli5001
     error: Failed to run: rbd --cluster ceph --pool lxd-pool map      image_b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7: rbd: sysfs write      failed
     In some cases useful info is found in syslog - try "dmesg | tail" or so.
     rbd: map failed: (110) Connection timed out

     root@inxovh-hy001 (node1):~# rbd -p lxd-pool ls
     lxd_lxd-pool

In /var/log/syslog,

     Aug 24 19:10:32 inxovh-hy001 kernel: [155075.557163] libceph: mon0 10.0.0.1:6789 feature set mismatch, my 106b84a842a42 < server's 40106b84a842a42, missing 400000000000000
     Aug 24 19:10:42 inxovh-hy001 kernel: [155085.572520] libceph: mon0 10.0.0.1:6789 missing required protocol features
     Aug 24 19:10:52 inxovh-hy001 lxd[10584]: lvl=eror msg="Failed to map RBD storage volume for image \"b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7\" on storage pool \"lxd-pool\": Failed to run: rbd --cluster ceph --pool lxd-pool map image_b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7: rbd: sysfs write failed\nIn some cases useful info is found in syslog - try \"dmesg | tail\" or so.\nrbd: map failed: (110) Connection timed out" t=2017-08-24T19:10:52+0200

any clue about "feature set mismatch, my 106b84a842a42 < server's 40106b84a842a42, missing 400000000000000" ??

Kernel info: 

    root@inxovh-hy001 (node1):~# uname -a
    Linux inxovh-hy001 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Ceph version : 10.2.9-1xenial 

Info 

root@inxovh-hy001 (node1):~# lxc info
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 192.168.10.1:8443
  - 192.168.20.1:8443
  - 192.168.30.1:8443
  - 192.168.40.1:8443
  - 192.168.5.1:8443
  - 192.168.6.1:8443
  - 192.168.25.1:8443
  - 10.0.0.1:8443
  - 151.80.26.210:8443
  - '[2001:41d0:1008:26d2::]:8443'
  - 10.0.1.1:8443
  - 192.168.2.1:8443
  - 192.168.122.1:8443
  - 192.168.1.1:8443
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-92-generic
  server: lxd
  server_pid: 10584
  server_version: "2.16"
  storage: zfs | ceph
  storage_version: '0.6.5.6-0ubuntu16 | '

**Comment by stgraber** [comment]
I think the feature mismatch may be the bug we fixed in LXD 2.17 where the image clones wasn't inheriting the feature set of the image.

**Comment by stgraber** [comment]
If you're using xenial-backports to get your LXD, you should be getting 2.17 early next week which will contain the fix. https://github.com/lxc/lxd/commit/4d0416053f8424d67d1e4accc0e6a7e00924aaf6

**Comment by stgraber** [comment]
If you want to try 2.17 ahead of its release in backports, you can download and manually install those two packages:
 - https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxd-stable/+files/lxd-client_2.17-0ubuntu1~ubuntu16.04.1~ppa1_amd64.deb
 - https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxd-stable/+files/lxd_2.17-0ubuntu1~ubuntu16.04.1~ppa1_amd64.deb

We've not received any negative feedback on LXD 2.17 yet, so that should be pretty safe to do.

**Comment by nlienard** [comment]
I updated to LXD 2.17 


    certificate_fingerprint: d551307dac375c378eccdd6c928464c6681d0b2dd77524a54b714864b23f5cc8
     driver: lxc
     driver_version: 2.0.8
     kernel: Linux
     kernel_architecture: x86_64
     kernel_version: 4.4.0-92-generic
     server: lxd
     server_pid: 26548
     server_version: "2.17"
     storage: zfs | ceph
     storage_version: 0.6.5.6-0ubuntu16 | ceph version 10.2.9 
    (2ee413f77150c0f375ff6f10edd6c8f9c7d060d0)


same  result :

    root@inxovh-hy001 (node1):~# lxc launch ubuntu-xenial-infranix inxovh-nli5001 -s lxd-pool
    Creating inxovh-nli5001
    error: Failed to run: rbd --id admin --cluster ceph --pool lxd-pool map image_b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7: rbd: sysfs write failed
    In some cases useful info is found in syslog - try "dmesg | tail" or so.
    rbd: map failed: (110) Connection timed out
    root@inxovh-hy001 (node1):~#

I guess i ve to follow the instructions on http://ceph.com/geen-categorie/feature-set-mismatch-error-on-ceph-kernel-client/

     mon0 192.168.0.1:6789 feature set mismatch, my XXXXXX < server's XXXXXX, missing 40000000
     —> Upgrade kernel client up to 3.9 or unset hashpspool : ceph osd pool set rbd hashpspool false

**Comment by stgraber** [comment]
@brauner ideas?

**Comment by brauner** [comment]
I guess we can somehow try to parse the ceph feature table but that's going to be costly. I'd rather update the document and state that users are expected to set `rbd default features = 1` in their ceph config. Is that acceptable? @nlienard, can you try if that helps, please?

**Comment by brauner** [comment]
@nlienard, also, please show the relevant `dmesg` output, please.

**Comment by nlienard** [comment]
my dmesg is flooded by bad messages


I found this which is related about your suggestion : https://pve.proxmox.com/pipermail/pve-devel/2016-April/020731.html

So it is safe to add this default parameter in my ceph.conf ?

**Comment by nlienard** [comment]
I added the default in [client] section of my ceph.conf

during lxc create, i got this in log:

    Aug 25 10:25:27 inxovh-hy001 lxcfs[8056]: message repeated 5 times: [ bindings.c: 3865: proc_uptime_read: failed to write to cache]
    Aug 25 10:26:08 inxovh-hy001 kernel: [210006.457342] libceph: mon0 10.0.0.1:6789 missing required protocol features
    Aug 25 10:26:20 inxovh-hy001 lxcfs[8056]: bindings.c: 3865: proc_uptime_read: failed to write to cache
    Aug 25 10:26:28 inxovh-hy001 kernel: [210026.451939] libceph: mon1 10.0.0.2:6789 feature set mismatch, my 106b84a842a42 < server's 40106b84a842a42, missing 400000000000000
    Aug 25 10:26:26 inxovh-hy001 lxcfs[8056]: message repeated 3 times: [ bindings.c: 3865: proc_uptime_read: failed to write to cache]
    Aug 25 10:26:38 inxovh-hy001 lxd[26548]: lvl=eror msg="Failed to map RBD storage volume for image \"b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7\" on storage pool \"lxd-pool\": Failed to run: rbd --id admin --cluster ceph --pool lxd-pool map image_b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7: rbd: sysfs write failed\nIn some cases useful info is found in syslog - try \"dmesg | tail\" or so.\nrbd: map failed: (110) Connection timed out" t=2017-08-25T10:26:38+0200
nf_nat_masquerade_ipv4 iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack ip_tables x_tables zfs(PO) zunicode(PO) zcommon(PO) znvpair(PO) spl(O) zavl(PO) bridge ipmi_ssif intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp crct10dif_pclmul crc32_pclmul ghash_clmulni_intel<4>[210042.119407] CPU: 7 PID: 14330 Comm: vhost-14328 Tainted: P        W  O    4.4.0-92-generic #115-Ubuntu

**Comment by brauner** [comment]
Did you restart ceph (e.g. via systemctl)?

**Comment by nlienard** [comment]
restarting OSD or MON ? or both ?

**Comment by brauner** [comment]
@nlienard, I think OSD should be sufficient. :)

**Comment by nlienard** [comment]
Ok i restarted my OSD on all nodes ( 6 OSD) but same issue 

     root@inxovh-hy001 (node1):~# grep -B 3 default /etc/ceph/ceph.conf  |tail -4
     [client]
     rbd_cache = true
     rbd_cache_max_dirty_age = 5
     rbd default features = 1

     root@inxovh-hy001 (node1):~# ps auxw |grep osd |grep ^ceph
     ceph     19696  2.8  1.0 1369360 345376 ?      Ssl  10:50   0:13 /usr/bin/ceph-osd -f --cluster ceph --id 4 --setuser ceph --setgroup ceph
     ceph     20776  2.5  1.0 1310784 337076 ?      Ssl  10:51   0:10 /usr/bin/ceph-osd -f --cluster ceph --id 5 --setuser ceph --setgroup ceph

     root@inxovh-hy001 (node1):~# lxc launch ubuntu-xenial-infranix inxovh-nli5001 -s lxd-pool
     Creating inxovh-nli5001
     error: Failed to run: rbd --id admin --cluster ceph --pool lxd-pool map      image_b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7: rbd: sysfs write failed
     In some cases useful info is found in syslog - try "dmesg | tail" or so.
     rbd: map failed: (110) Connection timed out


syslog

     Aug 25 10:56:32 inxovh-hy001 lxcfs[8056]: bindings.c: 3865: proc_uptime_read: failed to write to cache
     Aug 25 10:56:39 inxovh-hy001 kernel: [211837.291163] libceph: mon1 10.0.0.2:6789 feature set mismatch, my 106b84a842a42 < server's 40106b84a842a42, missing 400000000000000
     Aug 25 10:56:49 inxovh-hy001 kernel: [211847.305958] libceph: mon2 10.0.0.3:6789 feature set mismatch, my 106b84a842a42 < server's 40106b84a842a42, missing 400000000000000
     Aug 25 10:56:59 inxovh-hy001 kernel: [211857.297709] libceph: mon0 10.0.0.1:6789 missing required protocol features
     Aug 25 10:56:47 inxovh-hy001 lxcfs[8056]: message repeated 3 times: [ bindings.c: 3865: proc_uptime_read: failed to write to cache]
     Aug 25 10:57:01 inxovh-hy001 CRON[4377]: (root) CMD (   test -x /etc/cron.daily/popularity-contest && /etc/cron.daily/popularity-contest --crond)
     Aug 25 10:57:01 inxovh-hy001 CRON[4378]: (root) CMD (/usr/local/rtm/bin/rtm 17 > /dev/null 2> /dev/null)
     Aug 25 10:57:09 inxovh-hy001 kernel: [211867.312542] libceph: mon0 10.0.0.1:6789 missing required protocol features
     Aug 25 10:57:29 inxovh-hy001 lxd[26548]: lvl=eror msg="Failed to map RBD storage volume for image \"b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7\" on storage pool \"lxd-pool\": Failed to run: rbd --id admin --cluster ceph --pool lxd-pool map image_b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7: rbd: sysfs write failed\nIn some cases useful info is found in syslog - try \"dmesg | tail\" or so.\nrbd: map failed: (110) Connection timed out" t=2017-08-25T10:57:29+0200

**Comment by brauner** [comment]
Can you please retry with another image and report back. I suppose that the image has already been created in the pool with the wrong feature set.

**Comment by nlienard** [comment]
how can i cleanup the existing content ?

     root@inxovh-hy001 (node1):~# rbd -p lxd-pool ls
     lxd_lxd-pool


Should i remove it ?

**Comment by brauner** [comment]
Well is there anything in the pool currently?

**Comment by nlienard** [comment]
In the pool (lxd-pool) there is only an object called "lxd_lxd-pool"

     root@inxovh-hy001 (node1):~# rbd -p lxd-pool ls
     lxd_lxd-pool

Here the info about this object:

    root@inxovh-hy001 (node1):~# rbd info lxd-pool/lxd_lxd-pool
    rbd image 'lxd_lxd-pool':
        size 0 bytes in 0 objects
        order 22 (4096 kB objects)
        block_name_prefix: rbd_data.d3a703238e1f29
        format: 2
        features: layering
        flags:

Looks empty :

    root@inxovh-hy001 (node1):~# rbd du lxd-pool/lxd_lxd-pool
    warning: fast-diff map is not enabled for lxd_lxd-pool. operation may be slow.
    NAME         PROVISIONED USED
    lxd_lxd-pool           0    0

Should i remove it ?

**Comment by brauner** [comment]
Oh, didn't see it, sorry. No that should be fine that just there for LXD to track whether the pool hasn't been used by another LXD instance.

**Comment by brauner** [comment]
Can you please show me the output of `lxc info` again?

**Comment by nlienard** [comment]
root@inxovh-hy001 (node1):~# lxc info
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 192.168.10.1:8443
  - 192.168.20.1:8443
  - 192.168.30.1:8443
  - 192.168.40.1:8443
  - 192.168.5.1:8443
  - 192.168.6.1:8443
  - 192.168.25.1:8443
  - 10.0.0.1:8443
  - 151.80.26.210:8443
  - '[2001:41d0:1008:26d2::]:8443'
  - 10.0.1.1:8443
  - 192.168.2.1:8443
  - 192.168.122.1:8443
  - 192.168.1.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
  certificate_fingerprint: d551307dac375c378eccdd6c928464c6681d0b2dd77524a54b714864b23f5cc8
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-92-generic
  server: lxd
  server_pid: 26548
  server_version: "2.17"
  storage: zfs | ceph
  storage_version: 0.6.5.6-0ubuntu16 | ceph version 10.2.9 (2ee413f77150c0f375ff6f10edd6c8f9c7d060d0)
root@inxovh-hy001 (node1):~#

**Comment by brauner** [comment]
Did you send the updated `ceph.conf` file to you other nodes via `ceph-deploy config push`?

**Comment by nlienard** [comment]
nope, i edited manually ceph.conf on my 3 nodes, then restarted OSD one by one.

**Comment by brauner** [comment]
@nlienard, can you do manually:

`rbd map lxd-pool/lxd_lxd-pool`

please?

**Comment by nlienard** [comment]
root@inxovh-hy001 (node1):~# rbd map lxd-pool/lxd_lxd-pool
    rbd: sysfs write failed
    In some cases useful info is found in syslog - try "dmesg | tail" or so.
    rbd: map failed: (110) Connection timed out

in log

    Aug 25 11:43:25 inxovh-hy001 kernel: [214643.017298] libceph: mon2 10.0.0.3:6789 feature set mismatch, my 106b84a842a42 < server's 40106b84a842a42, missing 400000000000000

**Comment by brauner** [comment]
Can you try manually creating an image with not image features enabled and try to map it?

**Comment by brauner** [comment]
@nlienard, wait you don't even need to do that, just disable the `layering` feature on the already existing volume in the pool and try to map again.

**Comment by nlienard** [comment]
root@inxovh-hy001 (node1):~# rbd feature disable lxd-pool/lxd_lxd-pool   layering
     rbd: failed to update image features: (22) Invalid argument2017-08-25 11:55:04.721931 7fe3441e3100 -1 librbd: cannot update immutable features

**Comment by brauner** [comment]
*sigh*
Right, then if you could try my first suggestion that would be great.

**Comment by brauner** [comment]
Thanks btw!

**Comment by nlienard** [comment]
hum how to disable layering ?

with rbd create lxd-pool/test --size 4096, it adds automatically layering :(

And why is layering an issue ? i thought it is used for cloning feature.

**Comment by nlienard** [comment]
in ceph.conf, i got rbd_default_format = 2


rbd_default_features
Description
The default features enabled when creating an block device image. This setting only applies to format 2 images. The settings are:

1: Layering support. Layering enables you to use cloning.

2: Striping v2 support. Striping spreads data across multiple objects. Striping helps with parallelism for sequential read/write workloads.

4: Exclusive locking support. When enabled, it requires a client to get a lock on an object before making a write.

8: Object map support. Block devices are thin provisioned—​meaning, they only store data that actually exists. Object map support helps track which objects actually exist (have data stored on a drive). Enabling object map support speeds up I/O operations for cloning, or importing and exporting a sparsely populated image.

16: Fast-diff support. Fast-diff support depends on object map support and exclusive lock support. It adds another property to the object map, which makes it much faster to generate diffs between snapshots of an image, and the actual data usage of a snapshot much faster.

32: Deep-flatten support. Deep-flatten makes rbd flatten work on all the snapshots of an image, in addition to the image itself. Without it, snapshots of an image will still rely on the parent, so the parent will not be delete-able until the snapshots are deleted. Deep-flatten makes a parent independent of its clones, even if they have snapshots.

The enabled features are the sum of the numeric settings.

**Comment by nlienard** [comment]
ok i managed to create an image without layering  but same issue

    root@inxovh-hy001 (node1):~# rbd create lxd-pool/test --size 4096   --image-format 1
    rbd: image format 1 is deprecated
    root@inxovh-hy001 (node1):~# rbd info lxd-pool/test
    rbd image 'test':
        size 4096 MB in 1024 objects
        order 22 (4096 kB objects)
        block_name_prefix: rb.0.d3d337.2ae8944a
        format: 1
    root@inxovh-hy001 (node1):~# rbd map lxd-pool/test
    rbd: sysfs write failed
    In some cases useful info is found in syslog - try "dmesg | tail" or so.
    rbd: map failed: (110) Connection timed out

Log

    Aug 25 12:47:59 inxovh-hy001 kernel: [218516.671115] libceph: mon2 10.0.0.3:6789 feature set mismatch, my 106b84a842a42 < server's 40106b84a842a42, missing 400000000000000
    Aug 25 12:47:59 inxovh-hy001 kernel: [218516.680463] libceph: mon2 10.0.0.3:6789 missing required protocol features

**Comment by nlienard** [comment]
Should i update kernel from 4.4 to 4.11 ?

http://docs.ceph.com/docs/master/rados/operations/crush-map/?highlight=tunables

WHICH CLIENT VERSIONS SUPPORT CRUSH_TUNABLES5

v10.0.2 (jewel) or later
Linux kernel version v4.5 or later (for the file system and RBD kernel clients)

**Comment by brauner** [comment]
Well, your kernel seems to be exploding all over the place and I have no further explanation for this. Can you try to set 'ceph osd crush tunables legacy`?

**Comment by brauner** [comment]
@nlienard, yeah if you can try updating to a newer kernel.

**Comment by nlienard** [comment]
root@inxovh-hy001 (node1):~# ceph osd crush tunables legacy
adjusted tunables profile to legacy
     root@inxovh-hy001 (node1):~# rbd map lxd-pool/test
/dev/rbd0

**Comment by nlienard** [comment]
Looks good !!

     root@inxovh-hy001 (node1):~# lxc launch ubuntu-xenial-infranix inxovh-nli5001 -s lxd-pool
     Creating inxovh-nli5001

     The container you are starting doesn't have any network attached to it.
       To create a new network, use: lxc network create
       To attach a network to a container, use: lxc network attach

     Starting inxovh-nli5001

**Comment by brauner** [comment]
@nlienard, so this must be an ancient kernel module version. Upgrading to a new kernel might really help.

**Comment by tobozo** [comment]
Problem was probably related to this https://bugs.launchpad.net/ubuntu/+source/ceph/+bug/1578484

**Comment by nlienard** [comment]
trying to move the ceph container to another node (where i created the same ceph storage )

root@inxovh-hy001 (node1):~# lxc move inxovh-nli5001 node2:
error: Failed container creation:
 - https://192.168.10.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists
2017-08-25 15:08:20.449601 7f76b7180100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://192.168.20.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:23.495730 7f6858af9100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://192.168.30.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:23.841534 7f02ecaf4100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://192.168.40.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:24.824642 7f55773e1100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://192.168.5.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:25.185875 7f4884f95100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://192.168.6.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:27.612467 7ff981064100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://192.168.25.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:28.215614 7f2ed03ea100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://10.0.0.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:28.616111 7fdf909ee100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://151.80.26.210:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:29.005040 7fd0500bd100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://[2001:41d0:1008:26d2::]:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:31.518942 7f16e9c24100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://10.0.1.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:31.849493 7f2b332a7100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://192.168.2.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:32.222242 7f3113c99100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://192.168.122.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:32.553286 7f1b9d770100 -1 librbd: rbd image container_inxovh-nli5001 already exists
 - https://192.168.1.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-08-25 15:08:32.982025 7f524ce35100 -1 librbd: rbd image container_inxovh-nli5001 already exists
root@inxovh-hy001 (node1):~#

**Comment by brauner** [comment]
@nlienard, do you have two LXD instances using the same OSD pool in the same cluster?

**Comment by nlienard** [comment]
Hello
What do you mean by 2 LXD instances ?
I've created a storage (lxd-pool) on my 3 hypervizors using same name "lxd-pool":

     root@inxovh-hy002 (node2):~# lxc storage list
     +----------+-------------+--------+-----------+---------+
     |   NAME   | DESCRIPTION | DRIVER |  SOURCE   | USED BY |
     +----------+-------------+--------+-----------+---------+
     | default  |             | zfs    | zdata/lxd | 24      |
     +----------+-------------+--------+-----------+---------+
     | lxd-pool |             | ceph   | lxd-pool  | 0       |
     +----------+-------------+--------+-----------+---------+

I ve same on the 3 nodes.

But at the end, i ve 1 ceph pool:

     root@inxovh-hy001 (node1):~# rbd list -p lxd-pool
     container_inxovh-nli5001
     image_b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7
     lxd_lxd-pool

**Comment by brauner** [comment]
So you have a three separate LXD daemons running on three nodes belonging to the same ceph cluster sharing the same osd pool? If that is the pool then this is very much not supported apart from backup purposes. This is also mentioned in our storage document in this repo. This obviously won't work since the storage volume already exists in the pool. We only support sharing the osd pool among multiple LXD instances for backup purposes in case one node goes down and users want to user a LXD daemon on another node to reimport the storage volumes for the containers.

**Comment by stgraber** [comment]
@brauner should we make "lxc storage create" fail when attempting to add an existing ceph pool and require something like "ceph.force_existing=1" be passed as a config key to force the use of an existing pool?

**Comment by stgraber** [comment]
To be clear, being able to use one shared ceph pool for multiple LXD hosts is absolutely on our roadmap, but we can't do so without also having the LXD hosts talk to each other and share one global view of the existing containers, images and custom storage volumes.

Right now, you'll want a separate osd pool per LXD host.

**Comment by nlienard** [comment]
Right now, i got 3  physicals servers (node1/node2/node3) where i created a ceph cluster with 2 OSD per server. I use it to host VM (KVM). In parallel, i use these same nodes to host LXD containers using ZFS local storage.
I thought with LXD Ceph storage that i would be able to do the same as i do with KVM VM meaning hosting a container on a node using ceph storage throught libvirt and performing live migration quickly.
My understanding is ceph storage on LXD is a bit young and for now, it is not possible to perform live migration with ceph storage but you are saying it is on your road map! So i guess i'll wait for this amazing feature before using LXD with ceph storage :)

This ticket can be closed as it concerned only creating a container on ceph storage. Thanks again for your amazing support and projet :)

**Comment by stgraber** [comment]
Yeah, we're slowly working towards a way of getting multiple LXD daemons to talk to each other which will allow them to share storage pool information when a storage pool is remote (as ceph is). It's going to take us a little while to figure everything out, but we'll get there :)
