### ISSUE TITLE
Live Migration fails

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#3719]
I can't perform live migration :

    root@inxovh-hy001 (node1):~# lxc move inxovh-xmpp002 node3:
    Transferring container: inxovh-xmpp002: 1.48GB (1.91MB/s)
    error: Failed container creation:
      - https://192.168.10.1:8443: Error transferring container data: migration dump failed
     (85.301569) Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
     (85.956130) Warn  (criu/arch/x86/crtools.c:133): Will restore 19223 with interrupted system call
     (86.540839) Warn  (criu/arch/x86/crtools.c:133): Will restore 19235 with interrupted system call
     (87.254299) Warn  (criu/arch/x86/crtools.c:133): Will restore 19284 with interrupted system call
     (87.442363) Warn  (criu/arch/x86/crtools.c:133): Will restore 19405 with interrupted system call
     (87.442470) Warn  (criu/arch/x86/crtools.c:133): Will restore 19440 with interrupted system call
     (88.228351) Warn  (criu/arch/x86/crtools.c:133): Will restore 19544 with interrupted system call
     (88.228479) Warn  (criu/arch/x86/crtools.c:133): Will restore 19546 with interrupted system call
     (88.228600) Warn  (criu/arch/x86/crtools.c:133): Will restore 19547 with interrupted system call
     (88.228721) Warn  (criu/arch/x86/crtools.c:133): Will restore 19548 with interrupted system call
     (88.228842) Warn  (criu/arch/x86/crtools.c:133): Will restore 19549 with interrupted system call
     (88.228962) Warn  (criu/arch/x86/crtools.c:133): Will restore 19551 with interrupted system call
     (88.229125) Warn  (criu/arch/x86/crtools.c:133): Will restore 19552 with interrupted system call
     (91.089422) Warn  (criu/arch/x86/crtools.c:133): Will restore 19457 with interrupted system call
     (91.356426) Warn  (criu/arch/x86/crtools.c:133): Will restore 19472 with interrupted system call
     (91.356725) Warn  (criu/arch/x86/crtools.c:133): Will restore 19478 with interrupted system call
     (91.588449) Warn  (criu/arch/x86/crtools.c:133): Will restore 9338 with interrupted system call
     (92.204878) Error (criu/action-scripts.c:116): One of more action scripts failed
      - https://192.168.20.1:8443: Error transferring container data: Unable to connect to: 192.168.20.1:8443
      - https://192.168.30.1:8443: Error transferring container data: Unable to connect to: 192.168.30.1:8443
      - https://192.168.40.1:8443: Error transferring container data: Unable to connect to: 192.168.40.1:8443
      - https://192.168.5.1:8443: Error transferring container data: websocket: bad handshake
      - https://192.168.6.1:8443: Error transferring container data: websocket: bad handshake
      - https://192.168.25.1:8443: Error transferring container data: Unable to connect to: 192.168.25.1:8443
      - https://10.0.0.1:8443: Error transferring container data: websocket: bad handshake
      - https://151.80.26.210:8443: Error transferring container data: Unable to connect to: 151.80.26.210:8443
      - https://[2001:41d0:1008:26d2::]:8443: Error transferring container data: websocket: bad handshake
      - https://10.0.1.1:8443: Error transferring container data: Unable to connect to: 10.0.1.1:8443
      - https://192.168.2.1:8443: Error transferring container data: Unable to connect to: 192.168.2.1:8443
      - https://192.168.122.1:8443: Error transferring container data: Unable to connect to: 192.168.122.1:8443
      - https://192.168.1.1:8443: Error transferring container data: Unable to connect to: 192.168.1.1:8443

I tried to remove and add the node3 and no problem for adding, it is in the remote list:

     root@inxovh-hy001 (node1):~# lxc remote list node3
     +-----------------+------------------------------------------+---------------+--------+--------+
     |      NAME       |                   URL                    |   PROTOCOL    | PUBLIC | STATIC |
     +-----------------+------------------------------------------+---------------+--------+--------+
     | images          | https://images.linuxcontainers.org       | simplestreams | YES    | NO     |
     +-----------------+------------------------------------------+---------------+--------+--------+
     | local (default) | unix://                                  | lxd           | NO     | YES    |
     +-----------------+------------------------------------------+---------------+--------+--------+
     | node2           | https://10.0.0.2:8443                    | lxd           | NO     | NO     |
     +-----------------+------------------------------------------+---------------+--------+--------+
     | node3           | https://10.0.0.3:8443                    | lxd           | NO     | NO     |
     +-----------------+------------------------------------------+---------------+--------+--------+
     | node4           | https://10.0.0.4:8443                    | lxd           | NO     | NO     |
     +-----------------+------------------------------------------+---------------+--------+--------+
     | ubuntu          | https://cloud-images.ubuntu.com/releases | simplestreams | YES    | YES    |
     +-----------------+------------------------------------------+---------------+--------+--------+
     | ubuntu-daily    | https://cloud-images.ubuntu.com/daily    | simplestreams | YES    | YES    |
     +-----------------+------------------------------------------+---------------+--------+--------+

I can also list the containers of node3 remotely from node1 without any problem, so i guess, the communication works:

     root@inxovh-hy001 (node1):~# lxc list node3:
     +------------------+---------+--------------------------------+------+------------+-----------+
     |       NAME       |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
     +------------------+---------+--------------------------------+------+------------+-----------+
     | cephA-002        | RUNNING | 192.168.10.244 (eth0)          |      | PERSISTENT | 0         |
     +------------------+---------+--------------------------------+------+------------+-----------+
     | d-push           | RUNNING | 192.168.10.232 (eth0)          |      | PERSISTENT | 0         |
     +------------------+---------+--------------------------------+------+------------+-----------+
     | inxovh-db002     | RUNNING | 192.168.6.202 (eth0)           |      | PERSISTENT | 0         |
     |                  |         | 192.168.5.202 (eth1)           |      |            |           |
     +------------------+---------+--------------------------------+------+------------+-----------+
     | inxovh-es003     | RUNNING | 192.168.10.153 (eth0)          |      | PERSISTENT | 0         |
     +------------------+---------+--------------------------------+------+------------+-----------+
     | inxovh-git501    | RUNNING | 192.168.10.44 (eth0)           |      | PERSISTENT | 0         |
     +------------------+---------+--------------------------------+------+------------+-----------+
     | inxovh-mx002     | RUNNING | 192.168.6.237 (eth1)           |      | PERSISTENT | 0         |
     |                  |         | 192.168.10.237 (eth0)          |      |            |           |
     +------------------+---------+--------------------------------+------+------------+-----------+
     | inxovh-nc102     | RUNNING | 192.168.10.172 (eth0)          |      | PERSISTENT | 0         |
     |                  |         | 172.17.0.1 (docker0)           |      |            |           |
     +------------------+---------+--------------------------------+------+------------+-----------+
     | inxovh-rdc003    | RUNNING | 192.168.10.214 (eth0)          |      | PERSISTENT | 0         |
     +------------------+---------+--------------------------------+------+------------+-----------+
     | inxovh-rt501     | RUNNING | 192.168.10.93 (eth0)           |      | PERSISTENT | 0         |
     +------------------+---------+--------------------------------+------+------------+-----------+
     | inxovh-xmpp002KK | RUNNING | 192.168.10.207 (eth0)          |      | PERSISTENT | 0         |
     +------------------+---------+--------------------------------+------+------------+-----------+
     | post-io          | STOPPED |                                |      | PERSISTENT | 0         |
     +------------------+---------+--------------------------------+------+------------+-----------+

Any clue is welcome.

Env is same as latest issue created: lxd 2.17

     root@inxovh-hy001 (node1):~# lxc info
     config:
       core.https_address: '[::]:8443'
       core.trust_password: true
     [...]
     api_status: stable
     api_version: "1.0"
     auth: trusted
     public: false
     environment:
       addresses:
       - 192.168.10.1:8443
       - 192.168.20.1:8443
       - 192.168.30.1:8443
       - 192.168.40.1:8443
       - 192.168.5.1:8443
       - 192.168.6.1:8443
       - 192.168.25.1:8443
       - 10.0.0.1:8443
       - 151.80.26.210:8443
       - '[2001:41d0:1008:26d2::]:8443'
       - 10.0.1.1:8443
       - 192.168.2.1:8443
       - 192.168.122.1:8443
       - 192.168.1.1:8443
       architectures:
       - x86_64
       - i686
     driver: lxc
    driver_version: 2.0.8
    kernel: Linux
    kernel_architecture: x86_64
    kernel_version: 4.4.0-92-generic
    server: lxd
    server_pid: 26548
    server_version: "2.17"
    storage: zfs | ceph
    storage_version: 0.6.5.6-0ubuntu16 | ceph version 10.2.9 
  (2ee413f77150c0f375ff6f10edd6c8f9c7d060d0)

**Comment by stgraber** [comment]
I believe that's what I fixed yesterday: https://github.com/lxc/lxd/commit/f4b6f27e367ace763bcb3508a26c2634e7b82491

What version did you last had this working with? Based on the code I could see, live migration must have been broken since LXD 2.13 or so.

Closing this issue since the fix has already been merged.
