### ISSUE TITLE
wrong ip assigned to container with fixed ip, after container was copied

### ISSUE THREAD

**Issue by pgassmann** [lxc/lxd#3721]
Dnsmasq assigns a random IP to a running container which has a fixed ip address configured with
`lxc config device set www2 eth0 ipv4.address 10.0.3.10`
when a copy of that container was created. 
The stopped copy contains the same fixed ip address configuration and this seems to "confuse" dnsmasq when renewing the ip address lease of the running container.

This happened to my setup this early morning, when no special operation was happening. After multiple days/weeks running with the same config, incl. the stopped copy.

Now when analysing the situation it happened again with a second container when I was not directly making any operations on this container.

# Steps to reproduce

 1. Create a container with network device and fixed ip address
 2. Start container
 3. Create a copy
 4. Wait until renewal of dhcp lease. or provoke it somehow, restart running container, do some other operations.

# Required information

 * Distribution: ubuntu xenial
 * Distribution version:
 * The output of "lxc info" , see below

# Information to attach

```
lxc config show www2
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170307)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170307"
  image.version: "16.04"
  volatile.base_image: 2cab90c0c342346ea154bc2e8cacdae752a70747a755ce1f2970c9a9ebb5fe8c
  volatile.eth0.hwaddr: 00:16:3e:8f:2a:b3
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    ipv4.address: 10.0.3.10
    nictype: bridged
    parent: lxdbr0
    type: nic
ephemeral: false
profiles:
- default
stateful: false
description: ""

```
```
# lxc config show www2-bkp 
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170307)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170307"
  image.version: "16.04"
  volatile.base_image: 2cab90c0c342346ea154bc2e8cacdae752a70747a755ce1f2970c9a9ebb5fe8c
  volatile.eth0.hwaddr: 00:16:3e:e5:cf:2d
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    ipv4.address: 10.0.3.10
    nictype: bridged
    parent: lxdbr0
    type: nic
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

```
# cat /var/lib/lxd/networks/lxdbr0/dnsmasq.leases
1503767752 00:16:3e:8f:2a:b3 10.0.3.200 www2 *
```

```
# lxc info
config:
  core.https_address: asdfasdf
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - asdfasdf
  architectures:
  - x86_64
  - i686
  certificate: |
   asdfasdf 
  certificate_fingerprint: 
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-32-generic
  server: lxd
  server_pid: 22769
  server_version: "2.17"
  storage: zfs
  storage_version: 0.6.5.9-2
```

**Comment by stgraber** [comment]
I'm not sure what we can really do about this. LXD does tell dnsmasq about what you want, that is, two containers with the same static IP.

dnsmasq then apparently considers that to be invalid and ignores both static entries.

There's unfortunately no real API to configure dnsmasq, all that LXD can do is dump a bunch of text files into place and send SIGHUP to dnsmasq to have it reload its configuration. Whether that reload succeeds or fails, we unfortunately have no way of knowing.

**Comment by stgraber** [comment]
The few options we have are unfortunately all bad...

# Prevent you from copying the container in the first place
You'd then need to alter the source container to remove its static IP before you can copy it, which may cause your source container to loose its IP at that point...

# Only apply DHCP static leases when the container is running
There are a few problems with this approach, one is that reconfiguring dnsmasq is pretty expensive, so doing it every time a container state changes will cause significant load on busy systems.

The other problem is that if the static address is part of the dynamic range, it may end up being assigned to another running container, causing a later conflict when the container that has the static IP is started.

# Prevent starting containers any container which has a duplicate static address with another
This should be pretty safe to implement but certainly won't cover all cases as creating a container and not starting it is enough to cause the problem.

**Comment by stgraber** [comment]
So it looks like dnsmasq will let you have multiple MACs get the same address if it's listed on the same dhcp-host line. The issue with this is that we also use the dhcp-host line to set the DNS entry for the container which means we have the container name in there...

**Comment by stgraber** [comment]
I'll have to check whether it's allowed to have multiple dhcp-host lines for the same MAC. If so, then we can have one line which does the MAC to NAME assignment and another which does the MACs to IP part, but I doubt that dnsmasq is going to let us get away with that.

**Comment by stgraber** [comment]
Oh, unless we can also specify multiple names on the same line, then we may be able to keep things working that way. I'll have to experiment.

**Comment by huegelc** [comment]
Somehow related to: https://github.com/lxc/lxd/issues/3694 ?

**Comment by pgassmann** [comment]
A simple solution would be to delete the static address when creating a copy.
Then one could set a new ip. lxd could prevent or warn if an ip is already configured.
As a shortcut lxd could promt for a new ip when creating a copy, respectively allow it to be specified as an option.

PS: Stéphane your response time and dedication is phenomenal. Thank you a lot!

**Comment by stgraber** [comment]
@huegelc I don't think so. dnsmasq would have logged an error if that had been the case, something like:

    Aug 24 00:44:02 castiana dnsmasq[9831]: duplicate dhcp-host IP address 10.204.119.8 at line 1 of /var/lib/lxd/networks/lxdbr0/dnsmasq.hosts/cont8

**Comment by stgraber** [comment]
@pgassmann deleting the static IP would be pretty easy indeed, except for a few things:
 - There is no mechanism in the LXD API for giving a "warning" back to the user. Just errors. That's something we may want to add for such cases.
 - The user may actually want the two containers to have the same IP address. Assuming they never plan for the two of them to be running at the same time.
 - We'd need to special case local copies as cross-host copy would be fine.

Preventing the user from setting an ipv4.address value which is already used would also prevent the case where the user is doing this on purpose and isn't planning on running both containers at the same time. A warning would be appropriate, but a hard error not so much.

The way local container copies work at the API level does make it possible to send an alternative list of devices to LXD which would then override what's on the source container. So it is technically possible to allow overriding the address. We've never added such interactive behavior in the client though and I'm concerned it'd break a bunch of people scripting LXD.

Having some command line language to override a particular field of a particular device would be nice though. Similar to the "-c" parameter we have which lets you override normal config keys (so outside of a device).

**Comment by pgassmann** [comment]
Yes, the user might want that. But only if it does not affect the one running container properly. With the current behaviour it is better not to allow setting two times the same IP than allowing it and risk a totally different IP.

Interactive behaviour can be omitted by throwing an error and prompting to either specify a new ip or set a flag to drop the ip configuration.

Example

```
# lxc copy web1 web1-bkp
=> cannot copy container with fixed ip. Specify --drop-ip or --config-set device eth0 ipv4.address <foo> to copy the container
# lxc copy web1 web1-bkp  --config-set device eth0 ipv4.address 10.0.3.12
=> success
```

**Comment by jfgibbins** [comment]
From a networking standpoint, you never want two machines with the same mac.  Not only will it cause the above problems, but if those MAC addresses hit the network on two different ports, ie, it was copied to another host, you will get MAC flapping which can bring down ports, or even cause issues on the control plane of a switch and bring it down.  I would suggest that the MAC address,  be recreated, or if statically assigned, perhaps allow the copy, but leave the container in a shut state, and provide a notice that a possible conflict can occur.  You will drive the network engineers nuts if you cause flapping, and then probably smack you around a while after they turn off your network ports. :)  At least I always do.

**Comment by stgraber** [comment]
LXD ensures that the MAC isn't the same, unless the user really forces us. So that part is fine. We're only talking about IP here. And yes, two containers running with the same IP but different MAC is not much better as far as the network is concerned as you're going to be hitting one or the other depending on what's in your ARP cache.

But at least it won't trip things like loop detection at the switch level.

**Comment by jfgibbins** [comment]
Ah, I was thinking IP from MAC-reservation, not host-name.  Typically don't allow my server administrators to use anything but static configs.  DHCP is strictly for clients, so never an issue.  But on a clone, doesn't the hostname get set in the meta-data from the container name?  I know cloud-init it doing some work, but thought LXD was as well, since hostname does get set even on the non-cloud enabled images.  If only on the first run, then maybe reset the boot-instance or some other trigger on a copy to do so.

**Comment by stgraber** [comment]
The hostname part that's related to dnsmasq is so that dnsmasq can generate the relevant DNS records (both forward and reverse) for the container's IPv4 and IPv6 addresses.

**Comment by stgraber** [comment]
On a normal LXD, that gets you container-name.lxd to resolve to the container's IPv4 and IPv6 addresses (regardless of whether static DHCP assignment is used or not).

**Comment by pgassmann** [comment]
Thank you! What solution did you implement?

**Comment by stgraber** [comment]
We detect if two containers have the same ipv4.address and ipv6.address, if that's the case, the second container gets its mac address added to the static entry of the first.

So we effectively give you exactly what you asked for. Both containers do get the same addresses as requested.
