### ISSUE TITLE
docker: Error response from daemon: Could not check if docker-default AppArmor profile was loaded: open /sys/kernel/security/apparmor/profiles: permission denied.

### ISSUE THREAD

**Issue by scm20008** [lxc/lxd#3723]
# Required information

 * Distribution: ubuntu 16.04
 * Distribution version: ubuntu 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-21-generic
   * LXC version: 2.0.10
   * LXD version: 2.0.10
   * Storage backend in use: zfs
* Docker version: 17.05.0-ce

# Issue description

in win7, I have a vmware workstation, and in vm I have installed ubuntu16.04 with lxd.
and I have installed docker in lxd successfully, but start docker container failed.

# Steps to reproduce

when I run:
docker run --name container_name image_name ......

just start docker container failed, the following is the error:
docker: Error response from daemon: Could not check if docker-default AppArmor profile was loaded: open /sys/kernel/security/apparmor/profiles: permission denied.

tip:
I have run the commond for the container:
lxc config set <container_name> security.nesting true

How can I run the docker container in lxd successfully?

**Comment by stgraber** [comment]
You are running a Linux 4.4.0-21 kernel when the current kernel for Ubuntu 16.04 is 4.4.0-92.115 so you're about 70 kernel updates behind, including the one that's needed to support running Docker inside a LXD container.

Update your system and reboot, then confirm you're on a 4.4.0-92 kernel and then try again.

**Comment by scm20008** [comment]
@stgraber Thanks very much, when I upgraded the kernel, and  another error appears:

docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:252: getting pipe fds for pid 737 caused \"readlink /proc/737/fd/0: permission denied\"".

root@docker-server:~# uname -a
Linux docker-server 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by scm20008** [comment]
lxc config set <containter_name> security.privileged true

after run the upper command, and the docker container start successfully!
thanks very much again!

@stgraber

**Comment by jelmd** [comment]
Same thing with bionic (4.15.0-43-generic) and
```
lxc.include = /usr/share/lxc/config/nesting.conf
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.apparmor.profile = lxc-container-default-with-nesting
lxc.rootfs.path = dir:/zones/te/rootfs
...
```
