### ISSUE TITLE
LXD Network ovs bridge - Error with interfaces ipv6 link-local address - "Only unconfigured network interfaces can be bridged"

### ISSUE THREAD

**Issue by jadjay** [lxc/lxd#3727]
https://github.com/lxc/lxd/blob/d59a112ff91d8914ca31ef536d6d9eeddbceaffb/lxd/networks.go#L659-L678

The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.4
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-32-generic
   * LXC version: 2.0.8
   * LXD version: 2.12
   * Storage backend in use: lvm

# Issue description

You can't add an interface to a lxd network openvswitch bridge, you get this error : 
"Error : Only unconfigured network interfaces can be bridged"

# Steps to reproduce

 1. Install a fresh ubuntu then lxd
 2. connect a net interface to a switch, as it get "UP" : for example eth0
 3. Create a lxd network with openvswitch
lxc network create zone2 bridge.driver=openvswitch
4. Try to add eth0 to the ovswitch with lxc command
lxc network set zone2  bridge.external_interfaces eth0
5. You get an error : 
"Error : Only unconfigured network interfaces can be bridged"

# Analyze

- This problem comes form [those lines](https://github.com/lxc/lxd/blob/d59a112ff91d8914ca31ef536d6d9eeddbceaffb/lxd/networks.go#L659-L678)
- This code detect an ip address, even if not configured ! Because every interface have at least a link-local address !

# Workaround

- sysctl net.ipv6.conf.eth0.disable_ipv6=1

**Comment by stgraber** [comment]
It's usually a good idea to disable IPv6 on the underlying devices, just to avoid a kernel race condition where it may grab a global IPv6 right before it gets bridged, but yes, the check should be relaxed to allow bridging interfaces that only have an IPv6 link-local device.
