### ISSUE TITLE
Allow exporting/importing containers (for backups)

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3730]
This is a placeholder issue for us to think about and implement a better, simpler backup mechanism for those who want offline backups of their containers.

**Comment by Kramerican** [comment]
I have been doing this with an adapted script from [https://github.com/vistoyn/backup-tools](https://github.com/vistoyn/backup-tools) where you essentially dump the container config and then tar gzip it along with the rootfs, excluding proc sys and tmp.

I've also written a number of CLI tools in order to restore existing containers from such backups, or provision new ones (and fixing up the network config etc.). However this is not very generalize-able.

Call me old-fashioned, but I simply do not trust the snapshot functionality as-is and backup chains in general. I've lived one too many horror stories on that front. So in my mind, a wholesale portable snapshot is the way to go.

It would be neat if this was baked-in, as it's a strong "selling point" that you can do live snapshots of containers in this way, and it would make newcomers more at ease doing this stuff as it takes a bit of research and trial and error to get this working as-is.

So yeah, huzzah!

One thing I see would be improved is that as-is I have to import my tarball as an image, then do lxd init and then I nuke the temporary image again. Which seems a bit ... indirect.

**Comment by huegelc** [comment]
I follow this topic with high interest. I've tried different methods backing up lxd containers described in the lxd backup strategy and for now I'm sticking with doing this on the filesystem level (Btrfs). I know it's not 100% reliable and maybe not the "right way" but in lack of other options my best choice.

**Comment by davidfavor** [comment]
@Kramerican, be great if you can post your cli restore tools, in a zip file.

I'm in the same situation, where I have 100s of LXD containers running across many machines + require a mechanism to restore a container on any machine, any time + have the container work.

This was very easy with LXC + ridiculously difficult with LXD.

I'll take a look at the above link.

Thanks for posting it.

**Comment by Kramerican** [comment]
@davidfavor our tools are very much baked into our management tools, so it would be a bit difficult and time consuming to split out the relevant parts for you. However, feel free to shoot me any specific questions you might have and I'll try to help the best I can.

**Comment by Kramerican** [comment]
I have encountered an issue in connection with this recently, which is a bit of a catch-22 for me.

As mentioned, I want portable off-site backups of containers - that's why I don't use snapshotting.

This has worked fine, untill we had a container with hundreds of thousands of files on an HDD setup. This container would take about ~10 hours to "snapshot" instead of the usual couple of minutes. 

This is clearly not acceptable in our setup - so now I am not investigating alternatives. I have looked at something like [https://zpool.org/zfs-snapshots-and-remote-replication/](https://zpool.org/zfs-snapshots-and-remote-replication/) - but we are unfortunately limited by our remote storage which is a dumb FTP server.

The ultimate scenario would be the ability to create portable snapshots of containers quickly and copy them off-site for storage, like you can with so many other traditional vm solutions.

**Comment by tomposmiko** [comment]
AFAIK you can dump ZFS snapshots and upload them to the ftp server.

**Comment by Kramerican** [comment]
@tomposmiko got anything you can link to on this?

**Comment by stgraber** [comment]
zfs send blah@snapshot > file.img

Then when you want to restore: zfs receive blah < file.img

**Comment by Kramerican** [comment]
@stgraber I have stumbled on this myself these last few days, and have had wonderfully mixed, but always far superior results with zfs send / receive. Mixed in the sense that I have a problem with zfs send fluctuating wildly in speed, but I've reached out to the zfs mailing list to diagnose this.

The remainder here is probably a bit off topic, but I'll leave it here for your comments and if others might find this useful ... :

It is now clear to me that it is crazy to consider descending into the filesystem with tar and making tarballs if your objective is snapshots of running containers. That is simply not the correct tool for the job when you have zfs at your disposal.

I have now updated all my snapshotting and restoration workflows with regards to my portable backups to use zfs send / receive. This is not on production yet however, as I am doing things a bit gung-ho with regards to restoration, let me explain:

Rolling back a running container, I do something like: stop container, destroy original pool (and snaps) and then rename pool to minimize downtime

```
pigz -c -d /backup/testsnap.gz | zfs recv -F lxd/containers/temppool
lxc stop mycontainer
zfs destroy -r lxd/containers/mycontainer
zfs rename lxd/containers/temppool lxd/containers/mycontainer
lxc start mycontainer
```
Provisioning a new container based on a snapshotted dataset: Init "empty" ubuntu container, Destroy old storage dataset, Import new dataset, start the container, update network config and whatever else needs done

```
lxc init ubuntu:xenial testnewcontainer --profile webdock
zfs destroy -r lxd/containers/testnewcontainer
pigz -c -d /backup/testsnap.gz | zfs recv -F lxd/containers/testnewcontainer
lxc start testnewcontainer
... Update network config and whatever else needs doing
```

This approach is something I came up with as a test, just to see if it would work, and for now this seems to work just nicely. I have not seen anybody doing things this way however (not that I could find), which leads me to suspect there is possibly more to this kettle of fish. Is this a crazy way of doing it? i.e. just replacing the dataset wholesale like I do here? I can't think of anything theoretical which would be wrong with this, but then again I'm not well versed in the internals of LXD.

**Comment by stgraber** [comment]
What you're doing should be fine and I in fact intend for us to support something like this natively with #3443. Effectively letting you export a container (and its snapshots) as a tarball which either contains the raw fs tree (good old tarball) or contains the storage backend optimized format (result of zfs send, btrfs send, ...).

What format you'd export as would therefore depend on what you expect to restore your container on.

**Comment by Kramerican** [comment]
@stgraber Thank you for setting my mind at ease, and awesome to hear this will be supported natively so I can clean up my scripts a bit :smiley:

**Comment by davidfavor** [comment]
Regards ZFS... I've had to fall back to using ext4, because ZFS speed fluctuates wildly + the client sites I host in LXD containers are all high traffic sites... so speed fluctuation make ZFS a no-go.

**Comment by davidfavor** [comment]
@Kramerican, when you do the LXD restore, pass along how you handle regenerating /sys + /proc as this seems like the only sticking point in the restore process.

**Comment by Kramerican** [comment]
@davidfavor I am no longer doing the tar'ing of the container. I had no problems with the method you refer to, except for the obvious issues of speed and impracticality vs. zfs

The speed issues you have experienced with zfs: Is that when doing zfs send/receive, or just disk i/o in general?

I had tremendously varied results with zfs send/receive up untill I sparred with the nerds on the zfs mailing list. From that I gathered a bunch of very excellent suggestions for optimizations suitable for LXd containers. I have been meaning to do a writeup of this and post... Somewhere.

In essence: Containers suffer from fragmentation of data. Especially webservers with heavy db access or great deletion/creation of files. Here you can essentially "defrag" the datapool with a couple of simple commands, and mitigate this fragmentation with some zfs settings.

If you are seeing bad disk i/o in general, I do not have any solutions for you. I'd suspect something other than zfs, as I do not think your problem is rooted there, per se

**Comment by stgraber** [comment]
Just a few design notes on this:

= API =
 - New API endpoint at /1.0/containers/NAME/backups
   - POST lets you create backups using a struct with the following option (background operation):
     - name (Unique identifier for the backup)
     - expiry (when to delete the backup automatically)
     - container_only (if True, snapshots aren't included)
     - optimized_storage (if True, btrfs send or zfs send is used for container and snapshots)
   - GET lets you list existing backups for the container (supports recursive=1 to list the structs)
 - New API endpoint at /1.0/containers/NAME/backups/NAME
   - GET lets you retrieve the struct
   - DELETE lets you remove the backup
   - POST lets you rename the backup
 - New API endpoint at /1.0/containers/NAME/backups/NAME/export
   - GET lets you fetch the backup tarball
 - Extend POST /1.0/containers to allow reading a tarball sent during POST and create the container based on its content (including snapshots)

= Database =
 - New table containers_backups with at least those fields:
   - id
   - name
   - creation_date
   - expiry_date
   - container_only
   - optimized_storage

= Client support =
We'll keep client support for this pretty limited at the beginning with just two extra top-level commands:
 - lxc export [<remote>:]<container> [target] [--container-only] [--optimized-storage]
 - lxc import [<remote>:] <backup file>

So export would effectively ask LXD to create a backup, setting a short expiry for it, then retrieve it once made and delete the backup. Import would read a backup file and POST it to LXD to have it restored.


@brauner @monstermunchkin assigning this to the two of you.
@monstermunchkin you can try to do all the API addition bits, structs, API extension, ... and then sync with @brauner for the actual generation and consumption of the tarball.

**Comment by l00mi** [comment]
We are excited to see this feature coming.

The last two years we are using our own scripts running something like this:
`zfs send $zfssrc/$container@snapshot-$id | lz4 > $zfslcl/$container-$id.zfs.lz4`

Also do we use the the `zfs copy` to another lxd daemon as a "stand-by" backup.

For both we would love to see an incremental (https://github.com/lxc/lxd/issues/3326) option, as the backup load on the network is slowly hitting a critical size for us.

**Comment by huegelc** [comment]
Same here: we are using (almost) since the beginning https://github.com/digint/btrbk. Works really good with incremental backups.

**Comment by davidfavor** [comment]
Michael Luggen wrote:
> We are excited to see this feature coming.
> 
> The last two years we are using our own scripts running something like this:
> |zfs send $zfssrc/$container@snapshot-$id | lz4 > 
> $zfslcl/$container-$id.zfs.lz4|
> 
> Also do we use the the |zfs copy| to another lxd daemon as a "stand-by" 
> backup.
> 
> For both we would love to see an incremental (#3326 
> <https://github.com/lxc/lxd/issues/3326>) option, as the backup load on 
> the network is slowly hitting a critical size for us.

The will fail if any database subsystem is running, like MariaDB/MySQL.

Snapshotting disk data fails to capture memory buffers, so when this type of
snapshot is restored, it fails with corrupt database files.

With MariaDB, sometimes this corruption can be recovered + data is still lost.

Many times file corruption cannot be recovered + error messages are emitted
each time MariaDB/MySQL is started.

With MySQL (shudder) rarely can any type of corruption be recovered.

The best way to do this is just to do a...

1) lxc stop container

2) lxc copy container in background

3) restart container

At this point the container copy will run till it finishes.

Then stop mysqld on both servers + do a 2nd rsync /var/lib/mysql from
original container to copied container.

Then restart mysqld on both servers.

**Comment by l00mi** [comment]
@davidfavor 
Ha, good to know: Backup is easy, Restore is hard (-:

Unfortunately we cant stop our machines for the backup. Is there anyway to instruct the Database to save to disk before a backup?

**Comment by davidfavor** [comment]
Michael Luggen wrote:
> @davidfavor <https://github.com/davidfavor>
> Ha, good to know: Backup is easy, Restore is hard (-:
> 
> Unfortunately we cant stop our machines for the backup. Is there anyway 
> to instruct the Database to save to disk before a backup?

Two things to consider.

1) Doing a mysql stop + rsync only produces a few seconds of outage.

    This is the fastest way to create a 100% backup which will work
    when restored.

2) You can use xtrabackup (apt-get -y install percona-xtrabackup-24)
    to clone database to another directory + then move that directory
    to your copied container.

    This allows 100% database uptime + the trade off is time required
    to run xtrabackup.

    If the site has a small database, no problem.

    If you're looking at many Gb or Tb of data, then using the rsync
    trick is the only way to handle this.

The way I do this is to place a friendly maintenance mode message
on site for the 5-10 seconds usually required for this operation.

**Comment by Kramerican** [comment]
@davidfavor We've been doing, on our ZFS backed systems

`/sbin/zfs snapshot lxd/containers/$LXD_NAME@$BACKUP_TYPE`

and then 

`/sbin/zfs send lxd/containers/$LXD_NAME@$BACKUP_TYPE | /usr/bin/mbuffer -q -m 500M | /usr/bin/pigz -c -p 6 | /usr/bin/mbuffer -q -m 500M  > $LXD_BACKUP/$LXD_SNAPSHOT.gz`

For 1 year+ on 300+ containers running MariaDB without noticing a single instance of corrupted database data.

Granted, the vast majority of these sites are not busy websites, so maybe we didn't notice any potential drop of data? At the very least, we have seen no corruption of data or problems arising on the database side.

Maybe we have just consistently been getting lucky? :)

**Comment by davidfavor** [comment]
Kramerican wrote:
> @davidfavor <https://github.com/davidfavor> We've been doing, on our ZFS 
> backed systems
> 
> |/sbin/zfs snapshot lxd/containers/$LXD_NAME@$BACKUP_TYPE|
> 
> and then
> 
> |/sbin/zfs send lxd/containers/$LXD_NAME@$BACKUP_TYPE | /usr/bin/mbuffer 
> -q -m 500M | /usr/bin/pigz -c -p 6 | /usr/bin/mbuffer -q -m 500M > 
> $LXD_BACKUP/$LXD_SNAPSHOT.gz|
> 
> For 1 year+ on 300+ containers running MariaDB without noticing a single 
> instance of corrupted database data.
> 
> Granted, the vast majority of these sites are not busy websites, so 
> maybe we didn't notice any potential drop of data? At the very least, we 
> have seen no corruption of data or problems arising on the database side.
> 
> Maybe we have just consistently been getting lucky? :)

Some of the sites I host run 50K-100K reqs/minute, so tend to corrupt.

The only reason you don't see any corruption is...

1) You're log level is to low to see corruption messages.

2) Database updates are so infrequent flushes occur before backups run.

In general, trying to do a snapshot will create corruption under many
circumstances... so...

If you're running hobby sites, you can ignore corruption.

If you're running money/production sites, best to rsync /var/lib/mysql,
as described previously in this thread.

**Comment by Kramerican** [comment]
@davidfavor Maybe this doesn't need to be that complicated? Looking at this:

https://serverfault.com/questions/805257/backing-up-a-mysql-database-via-zfs-snapshots

There may be some configuration / commands which can be used to make sure memory buffers are flushed when doing the snapshot. I'm going to monkey around with this a bit and see what I find. If you've already been down this path and failed, it would be much appreciated to know :)

**Comment by michacassola** [comment]
So from reading this @stgraber:
Will the new feature of more native backups adress the mentioned database troubles?

**Comment by stgraber** [comment]
@michacassola no, this feature lets you extract the filesystem as it currently is into a tarball. If that filesystem is inconsistent because your database server hasn't been told to write everything, then it will be inconsistent. Database servers should usually be special cased in backups, either by turning them off, by doing a seperate dump of the databases or by syncing remotely with a remote DB server.

For incremental type backups, #3326 is what we'll be looking at.

**Comment by michacassola** [comment]
Thank you @stgraber !

I don't have any large sites right now but its alwazs better to know in case I will.
@davidfavor 
> The best way to do this is just to do a...
> 
> 1) lxc stop container
> 
> 2) lxc copy container in background
> 
> 3) restart container
> 
> At this point the container copy will run till it finishes.
> 
> Then stop mysqld on both servers + do a 2nd rsync /var/lib/mysql from
> original container to copied container.
> 
> Then restart mysqld on both servers.

I dont get it.
Why not stop mysql then stop the container then copy it and restart it again. Would the copy then not be corruption free? And you would save a step? Please enlighten me.

Also why is a mysql dump by mysql itself not possible and one could copy the container and do a mysql dump and for restoring putting the mysql dump back into the restored container?

Thanks in advance! :)

**Comment by michacassola** [comment]
@Kramerican Yes of course I did. But with the many edits I was not sure what was the end result. But thanks for making that clear!
But I will have to set `innodb_flush_log_at_trx_commit` to `1` or `2`.
And I guess @stgraber if the log buffer is continually flushed to disk using the future LXD native backup function will also work as a ZFS snapshot would?

**Comment by dplandigi** [comment]
Excellent, Thank you for fix

On 15-May-2018, at 3:45 PM, Christian Brauner <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #3730<https://github.com/lxc/lxd/issues/3730>.

**Comment by davidfavor** [comment]
@Kramerican - Running ZFS + BTRFS backing stores are incredibly slow, compared to raw EXT4, so EXT4 is really the only option for high IOPs databases.

**Comment by davidfavor** [comment]
This entire problem returns to many existing tickets which have requested.

1) Pre + Post hooks for lxc copy, so database start/stop can be integrated into copy operations.

2) Allow passing rsync exclude lists, to optimize copy operations.

If these two features existed working with large data containers would simplify.

**Comment by brauner** [comment]
Here's an illustration of the new feature:
[![asciicast](https://asciinema.org/a/181906.png)](https://asciinema.org/a/181906)

**Comment by uocxp** [comment]
+1 for incremetal backups
