### ISSUE TITLE
lxd copy slow + appears to run multiple copies of rsync

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#3736]
When lxc copy runs several potential oddities can occur....

1) Sometimes cloned containers fail to start in various ways, for example /var/lib/mysql files are corrupt, so database fails to start.

2) Sometimes lxc copy completes, with no error + new container simply doesn't exist.

3) Looks like three simultaneous rsync commands occur for each lxc copy, which means it's anyone's guess how multiple rsync runs fight amongst themselves + resolve conflicts.

4) lxd copy seems to take far longer than lxc operation use to take.

My guess is fix for all these problems is to ensure only a single copy of rsync runs.

```
# All OS updates applied

net11 # lxd --version
2.17

net11 # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```

```
# first window
net11 # lxc stop net11-dev-kashif
net11 # lxc copy net11-dev-kashif net11-dev-kashif-savepoint-2017-08-29

# second window
net11 # r
psall | grep rsync
root     996438 80.2  0.0  95288 46420 ?        S    07:52   0:06 rsync -a -HAX --sparse --devices --delete --checksum --numeric-ids --bwlimit 0 -q /var/lib/lxd/storage-pools/default/containers/net11-dev-kashif/ /var/lib/lxd/storage-pools/default/containers/net11-dev-kashif-savepoint-2017-08-29
root     996439  7.2  0.0  91660  7104 ?        S    07:52   0:00 rsync -a -HAX --sparse --devices --delete --checksum --numeric-ids --bwlimit 0 -q /var/lib/lxd/storage-pools/default/containers/net11-dev-kashif/ /var/lib/lxd/storage-pools/default/containers/net11-dev-kashif-savepoint-2017-08-29
root     996440 52.5  0.0 136216  6228 ?        R    07:52   0:04 rsync -a -HAX --sparse --devices --delete --checksum --numeric-ids --bwlimit 0 -q /var/lib/lxd/storage-pools/default/containers/net11-dev-kashif/ /var/lib/lxd/storage-pools/default/containers/net11-dev-kashif-savepoint-2017-08-29
```

**Comment by brauner** [comment]
What's the storage backend you're using?

**Comment by davidfavor** [comment]
```
# LXD setup via...
lxd init --auto --storage-backend dir
```

**Comment by stgraber** [comment]
You may also want to keep an eye on /proc/PID/fd/ for each of the rsync PIDs. That would give you a good idea as to what file it's busy transferring, letting you see if any one file is causing problems.

**Comment by davidfavor** [comment]
The problem is multiple copies of rsync running.

There should be only one copy.

Running multiple copies chews up CPU resource + produces unnecessary disk i/o thrash.

Thrash is the biggest problem.

Imagine cloning/copying many containers simultaneously, all of which have many small files.

The process of just building the file list can take a machine down... which is exactly what I'm seeing.

Simple fix... Run only a single rsync.

**Comment by stgraber** [comment]
Can you please provide the information I asked for?

LXD only spawns a single rsync, rsync spawns subprocesses.

**Comment by stgraber** [comment]
I just ran a quick test here and sure enough, the process tree shows that LXD only spawns one rsync command which then forks twice:

```
root     12249 47.5  0.0  37636  8204 pts/4    S+   14:02   0:00  |   |               \_ rsync -a -HAX --sparse --devices --delete --checksum --numeric-ids --bwlimit 0 -vi /var/lib/lxd/storage-pools/dir/containers/test1/ /var/lib/lxd/storage-pools/dir/containers/test2
root     12250  6.0  0.0  35700  2628 pts/4    S+   14:02   0:00  |   |                   \_ rsync -a -HAX --sparse --devices --delete --checksum --numeric-ids --bwlimit 0 -vi /var/lib/lxd/storage-pools/dir/containers/test1/ /var/lib/lxd/storage-pools/dir/containers/test2
root     12251 83.0  0.0  45464  2392 pts/4    R+   14:02   0:01  |   |                       \_ rsync -a -HAX --sparse --devices --delete --checksum --numeric-ids --bwlimit 0 -vi /var/lib/lxd/storage-pools/dir/containers/test1/ /var/lib/lxd/storage-pools/dir/containers/test2
```

So this looks exactly like what you've noticed, except that the tree output makes it clear that it's normal rsync behavior.

**Comment by davidfavor** [comment]
My behavior looks abnormal too.

Running inotifywait on source + target containers show rsync processes fighting with each other, attempting to copy already copied files.

Unsure how to fix this.

**Comment by patrakov** [comment]
Why is rsync used at all? What's wrong with a simple "cp -a"?

**Comment by davidfavor** [comment]
Likely to normalize the process of local + remote copies, as rsync tends to run much faster than cp... at least last time I tested.

**Comment by patrakov** [comment]
My testing on ext4 on rotational media yields the opposite result
