### ISSUE TITLE
x509 certificate error, using rest API (unknown authority...)

### ISSUE THREAD

**Issue by memed81500** [lxc/lxd#3741]
Hi stephan :)

Here a description of my problem:
- Three physicals different servers are involved.

**1st server : Bare Ubuntu/LXD running a website/phpscript**

**2nd server: Bare Ubuntu/LXD hosting container ( like a slave VPS provider )**
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 94.130.48.215:8443
  - 94.130.48.215:8443
  architectures:
  - x86_64
  - i686

certificate_fingerprint: 0278bfdc0f4d9845ca9378f7c75ea8dfbd1bd7b8bbaa2310a55a522f81ce5e66
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-33-generic
  server: lxd
  server_pid: 2610
  server_version: "2.17"
  storage: zfs
  storage_version: 0.6.5.9-2

**3st server : Bare Ubuntu/LXD hosting image of preconfigured container**
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 138.201.124.208:8443
  - '[2a01:4f8:172:280f::2]:8443'
  - 10.25.144.1:8443
  - '[fd42:1af1:77e:37ba::1]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
certificate_fingerprint: 303f204c9c554c4af42174ed73bd2d1025a62ed5f3b887546bacfb6498a663a4
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-33-generic
  server: lxd
  server_pid: 2442
  server_version: "2.17"
  storage: zfs
  storage_version: 0.6.5.9-2

The situation:
The 1st server ask to the second server, via the REST API to create a container , by pulling a private image from the third server. The second server produce this error ( lxc monitor) : 

metadata:
  context: {}
  level: dbug
  message: 'New events listener: a3ffbbc5-c5d5-4087-8543-8de54a713751'
timestamp: 2017-08-30T19:50:48.114495237+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: Responding to container create
timestamp: 2017-08-30T19:50:56.852027906+02:00
type: logging

metadata:
  context:
    ip: 163.172.181.176:56686
    method: POST
    url: /1.0/containers
  level: dbug
  message: handling
timestamp: 2017-08-30T19:50:56.852004061+02:00
type: logging

metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: 2017-08-30T19:50:56.85195003+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: No name provided, creating relative-basilisk
timestamp: 2017-08-30T19:50:56.852358122+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 0cbe228e-a14d-4fb3-8d31-bcc6b8e67ebc'
timestamp: 2017-08-30T19:50:56.852457647+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: 'New task operation: 0cbe228e-a14d-4fb3-8d31-bcc6b8e67ebc'
timestamp: 2017-08-30T19:50:56.852392386+02:00
type: logging

metadata:
  class: task
  created_at: 2017-08-30T19:50:56.85238407+02:00
  err: ""
  id: 0cbe228e-a14d-4fb3-8d31-bcc6b8e67ebc
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/relative-basilisk
  status: Pending
  status_code: 105
  updated_at: 2017-08-30T19:50:56.85238407+02:00
timestamp: 2017-08-30T19:50:56.85241603+02:00
type: operation

metadata:
  class: task
  created_at: 2017-08-30T19:50:56.85238407+02:00
  err: ""
  id: 0cbe228e-a14d-4fb3-8d31-bcc6b8e67ebc
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/relative-basilisk
  status: Running
  status_code: 103
  updated_at: 2017-08-30T19:50:56.85238407+02:00
timestamp: 2017-08-30T19:50:56.852483666+02:00
type: operation

metadata:
  context:
    etag: ""
    method: GET
    url: https://138.201.124.208:8443/1.0
  level: info
  message: Sending request to LXD
timestamp: 2017-08-30T19:50:56.856482286+02:00
type: logging

metadata:
  context: {}
  level: info
  message: Connecting to a remote public LXD over HTTPs
timestamp: 2017-08-30T19:50:56.856363555+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: 'Failure for task operation: 0cbe228e-a14d-4fb3-8d31-bcc6b8e67ebc: Get
    https://138.201.124.208:8443/1.0: x509: certificate signed by unknown authority'
timestamp: 2017-08-30T19:50:56.858174774+02:00
type: logging

**metadata:
  class: task
  created_at: 2017-08-30T19:50:56.85238407+02:00
  err: 'Get https://138.201.124.208:8443/1.0: x509: certificate signed by unknown
    authority'
  id: 0cbe228e-a14d-4fb3-8d31-bcc6b8e67ebc
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/relative-basilisk
  status: Failure
  status_code: 400
  updated_at: 2017-08-30T19:50:56.85238407+02:00
timestamp: 2017-08-30T19:50:56.858209098+02:00
type: operation**
 
**THE THIRD SERVER LOG (lxc monitor)**

metadata:
  context: {}
  level: dbug
  message: 'New events listener: e40e82a9-2f97-4af5-89aa-866fa6304402'
timestamp: 2017-08-30T19:50:32.991893453+02:00
type: logging

metadata:
  context:
    k: "2"
  level: dbug
  message: Found cert
timestamp: 2017-08-30T19:50:56.420251943+02:00
type: logging

metadata:
  context:
    ip: 163.172.181.176:57954
    method: POST
    url: /1.0/images/f71c67216cc53f191d844a92d4d31f2a6ebf37eae22a8dcdb335f3e6048c4bdf/secret
  level: dbug
  message: handling
timestamp: 2017-08-30T19:50:56.420343613+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: 'New token operation: 1a2116bf-f2d6-499e-bd9e-6d26dae9b495'
timestamp: 2017-08-30T19:50:56.421708512+02:00
type: logging

metadata:
  class: token
  created_at: 2017-08-30T19:50:56.421673637+02:00
  err: ""
  id: 1a2116bf-f2d6-499e-bd9e-6d26dae9b495
  may_cancel: true
  metadata:
    secret: 706363b214034a47789a707a78d7302c440ad2afc35f314ff6e19bbb09ea98e1
  resources:
    images:
    - /1.0/images/f71c67216cc53f191d844a92d4d31f2a6ebf37eae22a8dcdb335f3e6048c4bdf
  status: Running
  status_code: 103
  updated_at: 2017-08-30T19:50:56.421673637+02:00
timestamp: 2017-08-30T19:50:56.421872969+02:00
type: operation

metadata:
  class: token
  created_at: 2017-08-30T19:50:56.421673637+02:00
  err: ""
  id: 1a2116bf-f2d6-499e-bd9e-6d26dae9b495
  may_cancel: true
  metadata:
    secret: 706363b214034a47789a707a78d7302c440ad2afc35f314ff6e19bbb09ea98e1
  resources:
    images:
    - /1.0/images/f71c67216cc53f191d844a92d4d31f2a6ebf37eae22a8dcdb335f3e6048c4bdf
  status: Pending
  status_code: 105
  updated_at: 2017-08-30T19:50:56.421673637+02:00
timestamp: 2017-08-30T19:50:56.42177053+02:00
type: operation

metadata:
  context: {}
  level: dbug
  message: 'Started token operation: 1a2116bf-f2d6-499e-bd9e-6d26dae9b495'
timestamp: 2017-08-30T19:50:56.42183317+02:00
type: logging
 
**THE FIRST SERVER COMMAND LINE:**:
**Request from 1st server to the third server (hosting image) To get the secret:**
curl -k -L --cert /var/www/html/pure/lxc/your_client.crt --key /var/www/html/pure/lxc/your_client.key -X POST -d '{}' https://138.201.124.208:8443/1.0/images/f71c67216cc53f191d844a92d4d31f2a6ebf37eae22a8dcdb335f3e6048c4bdf/secret

**The answer:**

Array ( [type] => async [status] => Operation created [status_code] => 100 [operation] => /1.0/operations/1a2116bf-f2d6-499e-bd9e-6d26dae9b495 [error_code] => 0 [error] => [metadata] => Array ( [id] => 1a2116bf-f2d6-499e-bd9e-6d26dae9b495 [class] => token [created_at] => 2017-08-30T19:50:56.421673637+02:00 [updated_at] => 2017-08-30T19:50:56.421673637+02:00 [status] => Running [status_code] => 103 [resources] => Array ( [images] => Array ( [0] => /1.0/images/f71c67216cc53f191d844a92d4d31f2a6ebf37eae22a8dcdb335f3e6048c4bdf ) ) [metadata] => Array ( [secret] => 706363b214034a47789a707a78d7302c440ad2afc35f314ff6e19bbb09ea98e1 ) [may_cancel] => 1 [err] => ) )

***The rest api request (from the first server) to the second server to start a container, pulling from the third server using the secret**

curl -k -L --cert /var/www/html/pure/lxc/your_client.crt --key /var/www/html/pure/lxc/your_client.key -H "Content-Type: application/json" -X POST -d @/var/www/html/pure/tmp/3iIQuey5Mufa.json https://94.130.48.215:8443/1.0/containers

**The answer:**

Array ( [type] => async [status] => Operation created [status_code] => 100 [operation] => /1.0/operations/0cbe228e-a14d-4fb3-8d31-bcc6b8e67ebc [error_code] => 0 [error] => [metadata] => Array ( [id] => 0cbe228e-a14d-4fb3-8d31-bcc6b8e67ebc [class] => task [created_at] => 2017-08-30T19:50:56.85238407+02:00 [updated_at] => 2017-08-30T19:50:56.85238407+02:00 [status] => Running [status_code] => 103 [resources] => Array ( [containers] => Array ( [0] => /1.0/containers/relative-basilisk ) ) [metadata] => [may_cancel] => [err] => ) )

**3iIQuey5Mufa.json content:**
{
    "ephemeral":false,
    "config":{"limits.cpu": "4", "limits.cpu.allowance": "6%","limits.memory": "2GB", "limits.disk.priority": "5" },
     "devices": {
        "root": {
            "path": "/",
            "type": "disk",
            "pool": "default",
            "size": "15GB"
        },
        "vneth": {
				"type": "nic",
				"nictype": "bridged",
				"parent": "br0"        
       }
    },
    "source": {
        "type":"image",
        "mode":"pull",
        "server": "https://138.201.124.208:8443",
		  "secret": "706363b214034a47789a707a78d7302c440ad2afc35f314ff6e19bbb09ea98e1",
        
        "alias": "ubuntu1604"}
}

To resume, i just want a webapp written in php to ask to many slave server, to generate container from a central images server, but i'm stuck with this problem of certificate. I have no problem to make it work using by the command line directly like lxc launch hosting_server_image:ubuntu myubuntu for exemple.

Is it a bug or an error of my part ?

Thank you very much !

**Comment by stgraber** [comment]
Your POST request to create the container needs to have the third server's certificate added to the "source" struct so that the second server knows what certificate to expect and refuse connections if something is attempting a man in the middle attack.

So you'll need to set: req["source"]["certificate"] to be the PEM encoded x509 certificate of the 3rd server.

**Comment by memed81500** [comment]
Thanks i'll try it ! Just amazing how fast you are to answer ! Just as LXD is fast to run container :)

**Comment by stgraber** [comment]
```
	{
		"architecture": "",
		"config": null,
		"devices": {},
		"ephemeral": false,
		"profiles": null,
		"stateful": false,
		"description": "",
		"name": "blah",
		"source": {
			"type": "image",
			"certificate": "-----BEGIN CERTIFICATE-----\nMIIGszCCBJugAwIBAgIQQRmb482B75z3JHVa8ZyHQTANBgkqhkiG9w0BAQsFADAz\nMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRMwEQYDVQQDDApyb290QGF0\naG9zMB4XDTE1MTIyMTE4NDEzOFoXDTI1MTIxODE4NDEzOFowMzEcMBoGA1UEChMT\nbGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBhdGhvczCCAiIwDQYJ\nKoZIhvcNAQEBBQADggIPADCCAgoCggIBAJ+GfWYKxmqleR5nLxmuqW60Ew/ZMjBQ\nL28J6WcXAhescBxNZx7RW2XAyJOfwSLBT8o7F8UM2kxh2F4QGGJqCKf+OChPd/hj\no20zPJC3/IC3oaB6C8JY3TSe7zmlea1aTd+5aUpvS23/bV8IgnULdl1bE0rIb9dl\n7EYWUqX/Pgf4IBpPm2U+Dz0TciCRWhnPCdVhPS43sOU/stPT9ItjKS2Lk84YGQP3\nVcL97h7Gu/njRdBvYCCIOeQDR/ARHCBdVTMarb6nX9juTmoFtHWy9xYlDk7nbsxx\ng1ETVv5rUsRA/u4T5R4aS728uuWSCxYtzRT8mcV6v/rY5QPpxEC252SLfLs8WkPA\n5c4slZU4Wb0PvlOTTyzBk+q3AylMVM1VkzypOs1QK8GaWo4Gzv/ftxDFHLVE9P76\njR2QP/WnaqG5j0FDr5L4vgUiRbMCYk3KdoQksp+GXrAcicCW3HAm7DcDJOmbCInn\nPGCSmfADkST7Uc32Msh8QlSUvtBDiasSaMMBIMkPIO8rNChqkX5t93aLRM/vISCz\nkNNxQx+/nsJX4DsxtrkA/y9MKnTvwUjYE5u5+Uo1LUQee/SRlnz8fiyeSY3tDvEi\nV43WqnkOpWBiaSxcex+oQZQdKYSrDgZth6DBsARWR+xiH4e4hV5LC3JTGW99D9e9\nbQMBoP6J3DVHAgMBAAGjggHBMIIBvTAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAww\nCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADCCAYYGA1UdEQSCAX0wggF5ggVhdGhv\nc4IbZmU4MDo6MjI1OjkwZmY6ZmVlZjpmZjMxLzY0ghtmZTgwOjoyMjU6OTBmZjpm\nZWVmOmZmMzEvNjSCKTI2MDc6ZjJjMDpmMDBmOjI3MjA6MjI1OjkwZmY6ZmVlZjpm\nZjMxLzY0ghtmZTgwOjoyMjU6OTBmZjpmZWVmOmZmMzEvNjSCHGZlODA6OmZjNTE6\nZjBmZjpmZTZlOmUzZmQvNjSCHGZlODA6OmZjMWM6YWVmZjpmZTk0OmNlZDcvNjSC\nHGZlODA6OmZjMWQ6MzhmZjpmZTU4OmJkZDUvNjSCHGZlODA6OmZjMGE6OTdmZjpm\nZWU2OmJmZjcvNjSCHGZlODA6OmZjOGQ6MTBmZjpmZTkyOjYxNDkvNjSCHGZlODA6\nOmZjMjY6YTZmZjpmZTAzOjkzZDIvNjSCHGZlODA6OmZjMDc6ZTJmZjpmZTUxOmI1\nNWQvNjSCHGZlODA6OmZjNGY6NzBmZjpmZWFkOmFkYTYvNjQwDQYJKoZIhvcNAQEL\nBQADggIBAGez+7zZY8BG2Lum4jXkB7QDFwdl53XDcXqLnNe4rAlQcp1znLF6RRhV\n8y85aIN/zj+4dan+hEoipaHuv546Sg+pFWgL8sTW1HzlOMUys9hmiuvwBk13dSOW\npX2qOmxFAmJV/OH+LRXc7n/2laYgkbDELCDm1ULcqSyY0TRdoUOlzqkFAbnTmO8p\n1gKOrVRNI1HyB+BmHihi3jDOHA4uRt8ri25htZERE/PSRhz7j09L7Oc9rMKpMTaL\nGeCg+lihn2afdlZfigg03wOFWlpRJ0BehLIF+Jqyoe921+3+DPjWCLi+Br7PBAig\ngI1AJ5qk/lkb7119U2uNEBUenupRPzhcVBJWlDTQA0UxXs7RYurwVmdNB/PcTsRr\n4bB9pvtwDy3iBBKWBzvqUCKdWA2s1TenyZ2kPFOeH6/uCd8+g1TMZA8+BF8G0EIJ\nWRBs3vhVhJ7keiOhqh5RSOQNYs+7Ih5bwXsXMo0gdvKbztnipCSZW2G5o138mRs/\n0Ru1vzDmhEXxuKwcDtoAfx6eR6xASk2LGYNpvB86SY2dmydJs5fL5OFGGdEy7oUZ\n+wb/a+FxWUafyIreZCsJaZVXiSlcXuUq7YMnkujKeVxp2/tp8T/7klXi9OfypfQL\nFqdPYZtqrPWLTxuTa6C9M6FsCNgGNoO5JYrNT2/e7SQkWX4ckqAP\n-----END CERTIFICATE-----\n",
			"fingerprint": "52c57f8cd8f621b01367676ed0271d7ba7b9c17d343ccad5ce66411e6973d80c",
			"server": "https://athos.srv.mtl:8443",
			"secret": "2da9aa9a8b1d5d9f2d806f7ae61735df45b26907bedc9d5a99832996abeb1ec1",
			"protocol": "lxd",
			"mode": "pull"
		},
		"instance_type": ""
	} 
```

That's an example request as generated by "lxc copy".

**Comment by stgraber** [comment]
Closing this issue as it seems like the expected LXD behavior when not provided a certificate and the system CA can't validate the target.
