### ISSUE TITLE
LXD hangs on startup 

### ISSUE THREAD

**Issue by parak** [lxc/lxd#3742]
Hi again,

This is apparently different to the previous issue with lxd group, but oddly similarly affecting only select group of nodes, even though all of them are running the same kernel and lxd version (2.17-0ubuntu2~ubuntu14.04.1~ppa1).

Essentially the startup hangs on this line:

```
INFO[08-30|18:10:30]  - binding Unix socket                   socket=/var/lib/lxd/unix.socket
```

I've tried actually removing all of the directory contents along with fully removing and reinstalling LXD/LXC, but it just happens again afterwards. Strace attached - not sure if this is something on my end at this point.

Thanks!

[debug.zip](https://github.com/lxc/lxd/files/1264659/debug.zip)

**Comment by stgraber** [comment]
Can you manually start LXD, passing the "--debug" flag?

 - systemctl stop lxd.service lxd.socket
 - lxd --debug --group lxd

**Comment by stgraber** [comment]
Oh, sorry, Ubuntu 14.04...

 - initctl stop lxd
 - lxd --debug --group lxd

**Comment by parak** [comment]
Yep, just hangs after the last line:

```
root@build0:~# lxd --debug --group lxd
INFO[08-30|20:11:44] LXD 2.17 is starting in setup mode       path=/var/lib/lxd
WARN[08-30|20:11:44] CGroup memory swap accounting is disabled, swap limits will be ignored. 
INFO[08-30|20:11:44] Kernel uid/gid map: 
INFO[08-30|20:11:44]  - u 0 0 4294967295 
INFO[08-30|20:11:44]  - g 0 0 4294967295 
INFO[08-30|20:11:44] Configured LXD uid/gid map: 
INFO[08-30|20:11:44]  - u 0 296608 65536 
INFO[08-30|20:11:44]  - g 0 296608 65536 
DBUG[08-30|20:11:44] No existing storage pools detected. 
INFO[08-30|20:11:44] Expiring log files 
INFO[08-30|20:11:44] Done expiring log files 
INFO[08-30|20:11:44] Starting /dev/lxd handler 
DBUG[08-30|20:11:44] Looking for existing certificates        cert=/var/lib/lxd/server.crt key=/var/lib/lxd/server.key
INFO[08-30|20:11:44] LXD isn't socket activated 
INFO[08-30|20:11:44] REST API daemon: 
INFO[08-30|20:11:44]  - binding Unix socket                   socket=/var/lib/lxd/unix.socket
```

**Comment by stgraber** [comment]
Oh, your LXD is stuck in setup mode apparently. Can you try removing /var/lib/lxd/.setup_mode and then start it again?

**Comment by stgraber** [comment]
Setup mode is used so that the distribution packaging can inject LXD configuration before the daemon starts spawning containers and the like.

What's very weird is that setup mode isn't used with the LXD 2.17 package at all, so that'd have come from the original LXD 2.0.x that you had installed. It may have been stuck in setup mode prior to you upgrading to 2.17.

**Comment by stgraber** [comment]
I suspect removing that file from all affected servers will fix your problem.

**Comment by parak** [comment]
Yay, that was it, thanks. Really weird how it stuck around for so long and only caused an issue now, and explains why removing /var/lib/lxd/* didn't help either... rm -rf doesn't delete hidden files with that pattern :(
