### ISSUE TITLE
Ceph container and Live Migration

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#3747]
Hello

I've a LXC container into ceph and i would like to know how to move it (live or not) from a node to another.

For now, got this error

     root@inxovh-hy001 (node1):~# lxc move inxovh-nli5001 node2:                                                                                                                                                       
     error: Failed container creation:                                                                                                                                                                                 
      - https://192.168.10.1:8443: Failed to run: rbd --id admin --image-feature layering, --cluster ceph --     pool lxd-pool --size 10737418240B create container_inxovh-nli5001: rbd: create error: (17) File exists2017-
     08-31 12:14:10.965449 7f7ccf17e100 -1 librbd: rbd image container_inxovh-nli5001 already

lxc info

     driver: lxc
      driver_version: 2.0.8
      kernel: Linux
      kernel_architecture: x86_64
      kernel_version: 4.11.0-14-generic
      server: lxd
      server_pid: 11402
      server_version: "2.17"
      storage: zfs | ceph
      storage_version: 0.6.5.10-1ubuntu2~2 | ceph version 10.2.9     (2ee413f77150c0f375ff6f10edd6c8f9c7d060d0)

    root@inxovh-hy001 (node1):~# lxc storage list
    +----------+-------------+--------+-----------+---------+
    |   NAME   | DESCRIPTION | DRIVER |  SOURCE   | USED BY |
    +----------+-------------+--------+-----------+---------+
    | default  |             | zfs    | zdata/lxd | 26      |
    +----------+-------------+--------+-----------+---------+
    | lxd-pool |             | ceph   | lxd-pool  | 2       |
    +----------+-------------+--------+-----------+---------+

     root@inxovh-hy002 (node2):~# lxc storage list
     +----------+-------------+--------+-----------+---------+
     |   NAME   | DESCRIPTION | DRIVER |  SOURCE   | USED BY |
     +----------+-------------+--------+-----------+---------+
     | default  |             | zfs    | zdata/lxd | 25      |
     +----------+-------------+--------+-----------+---------+
     | lxd-pool |             | ceph   | lxd-pool  | 0       |
     +----------+-------------+--------+-----------+---------+

The ceph storage points to same volume  for all my LXD node : 

     root@inxovh-hy002 (node2):~# ceph osd lspools
     0 data,6 libvirt-pool,7 .rgw.root,9 lxd-pool,

So i have a common CEPH pool  for my LXD nodes (like for my KVM VM)

     root@inxovh-hy002 (node2):~# rbd list -p lxd-pool
     container_inxovh-nli5001
     image_b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7
     lxd_lxd-pool

As ceph is seen on all my nodes, i expect live migration would be easy (just move the memory over tcp and free the lock image on source node to reopen it on target node ?).

What is the correct way to move a container with ceph storage from a node to another ? even with container down.

thanks !

**Comment by brauner** [comment]
This seems to be the same issue that you already had a couple of days back so my comment https://github.com/lxc/lxd/issues/3716#issuecomment-324956166 here still applies. :) Please also see the relevant section https://github.com/lxc/lxd/blob/master/doc/storage.md#ceph . Especially:

> Note that sharing the same osd storage pool between multiple LXD instances is not supported. LXD only allows sharing of an OSD storage pool between multiple LXD instances only for backup purposes of existing containers via lxd import. In line with this, LXD requires the "ceph.osd.force_reuse" property to be set to true. If not set, LXD will refuse to reuse an osd storage pool it detected as being in use by another LXD instance.

**Comment by nlienard** [comment]
i created this specific issue because the previous was not related to live migration but container creation with ceph storage, sorry for the inconvenience.
So if we can't share a ceph pool between multiple LXD instances, what is the benefit to use ceph ?

Is it on roadmap to have live migration support between multiple LXD instances ? :)

thanks again

**Comment by brauner** [comment]
@nlienard, as @stgraber pointed out in the previous issue sharing storage pools between LXD instances is very much on our roadmap. However, there's a lot of plumbing to do to get this to work correctly. :)
