### ISSUE TITLE
How to compute/retrieve the fingerprint of an exported image

### ISSUE THREAD

**Issue by olivier-etienne** [lxc/lxd#3750]
I have generated an image using lxc image export image_name image_archive_name
I can get the fingerprint of an existing image with : lxc image info

But I would like to retrieve the fingerprint of the image_archive before to import it again.

How can I do that ?

Olivier

**Comment by stgraber** [comment]
If you have a single file, do "sha256sum FILE", if it's a split image, you need to "cat META ROOTFS | sha256sum".

**Comment by stgraber** [comment]
In the split image case, the order matters, the first file must be the tiny metadata file and the second one be the large rootfs file.

**Comment by olivier-etienne** [comment]
Thanks !
