### ISSUE TITLE
How to set network a description ?

### ISSUE THREAD

**Issue by jadjay** [lxc/lxd#3751]
# Required information

 * Distribution: all
 * Distribution version: all
   * Kernel version: 4.10
   * LXC version: 2.17
   * LXD version: 2.17

# Issue description

When show network
```
$ lxc network show mynet
config:
  bridge.external_interfaces: eth0
description: ""
name: mynet
type: bridge
used_by: []
managed: true
```

There is a description field which you can't update : 

```
$ lxc network set mynet description "My network"
error : Invalid network configuration key: description
$ lxc network set mynet core.description "My network"
error : Invalid network configuration key: core.description
```

Nor during creation : 
```
$ lxc network create mytest description="My bloody network description"
error : Invalid network configuration key: description
$ lxc network create mytest core.description="My bloody network description"
error : Invalid network configuration key: core.description
```

The only way is to edit 
```
$ lxc network edit mynet 
...
description: "My very hard to describe network"
...
```

It's not really easy to change if you need to define via scripts...

**Comment by stgraber** [comment]
Yeah, "lxc network edit" is the only way to do it as "description" is an attribute of the network object, not a config property. The same is true for a few other properties here and there.

At the API level it's all pretty nice and clean, it's just at the CLI level that this looks a bit awkward.

"lxc network edit" does allow parsing stdin, so you can technically script it.

```
stgraber@castiana:~/data/code/lxc/lxd (lxc/master)$ lxc network show lxdbr0 | sed 's/^description:.*/description: This is a test/' | lxc network edit lxdbr0

stgraber@castiana:~/data/code/lxc/lxd (lxc/master)$ lxc network list 
+--------+----------+---------+----------------+---------+
|  NAME  |   TYPE   | MANAGED |  DESCRIPTION   | USED BY |
+--------+----------+---------+----------------+---------+
| eth0   | physical | NO      |                | 0       |
+--------+----------+---------+----------------+---------+
| lxdbr0 | bridge   | YES     | This is a test | 5       |
+--------+----------+---------+----------------+---------+
| wlan0  | physical | NO      |                | 0       |
+--------+----------+---------+----------------+---------+
stgraber@castiana:~/data/code/lxc/lxd (lxc/master)$ 
```

**Comment by jadjay** [comment]
Ok, it's lame but it works...

Do you think CLI will give solution in future ?

**Comment by stgraber** [comment]
Possibly. We have some general CLI rework on our list for LXD 3.0 (next 6 months or so) which does include surfacing some of those more hidden properties.

**Comment by jadjay** [comment]
If I can make propositions : 

- Enable list dashed/undashed, 
- Enable selection for visible attributes 
- Enable those FOR EVERY OBJECTS (containers, networks, storages, profiles, AND FUTURE STUFF) 
- Why don't you externalize in a dedicated listing module every object will call for listing ?
- Create a per user configuration (.lxdrc/.lxcrc) with default listing 

Hope those propositions will help,
