### ISSUE TITLE
Network isolation

### ISSUE THREAD

**Issue by debdattabasu** [lxc/lxd#3754]
Hi.
I have created two bridge networks using lxc network create. I expect containers on these networks to be isolated from each other. However, containers created on these networks can freely access each other over tcp. What do I need to do to set this up?

Regards
Debdatta Basu

**Comment by stgraber** [comment]
Good old fashion firewalling on your host.

**Comment by stgraber** [comment]
iptables -A FORWARD -i bridge1 -o bridge2 -j REJECT
iptables -A FORWARD -i bridge2 -o bridge1 -j REJECT

Or something more specific depending on exactly what you want to allow/block.

**Comment by debdattabasu** [comment]
Hi, 
This is what I was planning to do, but this is an extra step from an orchestration standpoint. I wanted to  check if lxd had something like this built in. 

Thanks for your quick response. 
Regards,
Debdatta Basu

**Comment by stgraber** [comment]
Hi,

No, we've been staying away from implementing firewalling capabilities in LXD, at least for now.
This would add a lot of code and complexity which wouldn't always be welcome by our users as most tend to have existing firewalling tools and scripts on their servers.
