### ISSUE TITLE
LXD on 17.04 using juju bootstrap does not create container

### ISSUE THREAD

**Issue by jfgibbins** [lxc/lxd#3755]
https://jujucharms.com/docs/2.0/clouds-LXD states that juju only works on Xenial, though I have seen numerous references, of systems running on Yakkety and Zesty.  Is the website just out of date, or is support still iffy?  I attempted to "juju bootstrap lxd test", and while it creates the controller, it does not show up as a container as in @stgraber https://stgraber.org/2016/06/06/lxd-2-0-lxd-and-juju-1012/ example.  I know it has create when I have played with juju in the past when trying out openstack on lxd, but it was quite a while ago, and I may still have been on 16.04 or 16.10 at the time.

**Comment by stgraber** [comment]
My understanding is that the version of Juju in the Ubuntu archive is quite a bit behind and not particularly well supported. Unless you're using the Ubuntu LTS.

They do have a PPA which gets the newer releases and may work better. I believe you'll want Juju 2.2.x or higher.

**Comment by jfgibbins** [comment]
@stgraber Appreciate the help.  So far the 2.2.x version created the container.  I try to stick with the archive versions unless I know of a reason to do otherwise.  Had seen about Xenial only, but hadn't about updated version, and figured you of all people would know.  I'll continue testing, but close this as this particular issue is solved.  BTW, reason I'm trying juju, is from what I've seen so far, it might work for Infrastructure-as-code(IAC).  I had attempted terraform, but it's far too limited and restrictive.  Any suggestions you might know that allow IAC or orchestration, and supports LXD would be appreciated.  Thanks again.
