### ISSUE TITLE
Log showing : bindings.c: 3865: proc_uptime_read: failed to write to cache

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#3756]
Got plenty log saying

Sep  2 20:44:35 inxovh-hy001 lxcfs[9071]: bindings.c: 3865: proc_uptime_read: failed to write to cache
Sep  2 20:45:00 inxovh-hy001 lxcfs[9071]: message repeated 7 times: [ bindings.c: 3865: proc_uptime_read: failed to write to cache]
Sep  2 20:45:13 inxovh-hy001 lxcfs[9071]: bindings.c: 3865: proc_uptime_read: failed to write to cache
Sep  2 20:45:16 inxovh-hy001 lxcfs[9071]: message repeated 3 times: [ bindings.c: 3865: proc_uptime_read: failed to write to cache]
Sep  2 20:45:25 inxovh-hy001 lxcfs[9071]: bindings.c: 3865: proc_uptime_read: failed to write to cache
Sep  2 20:45:59 inxovh-hy001 lxcfs[9071]: message repeated 5 times: [ bindings.c: 3865: proc_uptime_read: failed to write to cache]
Sep  2 20:46:19 inxovh-hy001 lxcfs[9071]: bindings.c: 3865: proc_uptime_read: failed to write to cache
Sep  2 20:46:46 inxovh-hy001 lxcfs[9071]: message repeated 3 times: [ bindings.c: 3865: proc_uptime_read: failed to write to cache]
Sep  2 20:48:11 inxovh-hy001 lxcfs[9071]: bindings.c: 3865: proc_uptime_read: failed to write to cache
Sep  2 20:48:41 inxovh-hy001 lxcfs[9071]: message repeated 3 times: [ bindings.c: 3865: proc_uptime_read: failed to write to cache]
Sep  2 20:49:36 inxovh-hy001 lxcfs[9071]: bindings.c: 3865: proc_uptime_read: failed to write to cache
Sep  2 20:50:01 inxovh-hy001 lxcfs[9071]: message repeated 7 times: [ bindings.c: 3865: proc_uptime_read: failed to write to cache]
Sep  2 20:50:14 inxovh-hy001 lxcfs[9071]: bindings.c: 3865: proc_uptime_read: failed to write to cache

Is there any issue with my containers ?

 driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.11.0-14-generic
  server: lxd
  server_pid: 11402
  server_version: "2.17"
  storage: zfs | ceph
  storage_version: 0.6.5.10-1ubuntu2~2 | ceph version 10.2.9 (2ee413f77150c0f375ff6f10edd6c8f9c7d060d0)

**Comment by stgraber** [comment]
That's coming from lxcfs, can you open an issue at https://github.com/lxc/lxcfs/issues?

**Comment by brauner** [comment]
Which LXCFS version is this. There's a commit for uptime in git master that should fix this. This is the same issue as the "bad data in proc uptime" errors.

**Comment by nlienard** [comment]
root@inxovh-hy001 (node1):~# dpkg -l |grep lxc
ii  liblxc1                              2.0.8-0ubuntu6~ubuntu16.04.1~ppa1          amd64        Linux Containers userspace tools (library)
ii  lxc-common                           2.0.8-0ubuntu6~ubuntu16.04.1~ppa1          amd64        Linux Containers userspace tools (common tools)
ii  lxc-templates                        2.0.8-0ubuntu6~ubuntu16.04.1~ppa1          amd64        Linux Containers userspace tools (templates)
ii  lxc1                                 2.0.8-0ubuntu6~ubuntu16.04.1~ppa1          amd64        Linux Containers userspace tools
ii  lxc2                                 2.17-0ubuntu2~ubuntu16.04.1~ppa1           all          Container hypervisor based on LXC - metapackage
ii  lxcfs                                2.0.7-0ubuntu5~ubuntu16.04.1~ppa1          amd64        FUSE based filesystem for LXC
ii  python3-lxc                          2.0.8-0ubuntu6~ubuntu16.04.1~ppa1          amd64        Linux Containers userspace tools (Python 3.x bindings)

when is the new version coming in http://ppa.launchpad.net/ubuntu-lxc/stable/ubuntu ?

**Comment by nlienard** [comment]
sorry didn't know it was a separate project

**Comment by nlienard** [comment]
looks related to https://github.com/lxc/lxcfs/pull/205

    root@inxovh-hy001 (node1):~# cat /var/lib/lxcfs/proc/uptime
    0.00 0.00

**Comment by stgraber** [comment]
Ah yeah, it could well be that issue, LXCFS 2.0.8 will contain the fix. We still have quite a bit of patch backlog before we're ready to release a bunch more stable releases though. Most optimistic timeline is a couple of weeks.
