### ISSUE TITLE
lxd 2.17 init issues with dnsmasq

### ISSUE THREAD

**Issue by rayxis** [lxc/lxd#3757]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: CentOS
 * Distribution version: 7
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.12.10-1.el7.elrepo.x86_64
   * LXC version: 2.17
   * LXD version: 2.17
   * Storage backend in use: Default

# Issue description
After looking at my other VM, which is running 2.16 and this one, which is 2.17, I realized that the 
difference between the two is the addition of: "--quiet-dhcp --quiet-dhcp6 --quiet-ra". Once I removed those and pasted to the command line, dnsmasq no longer had an issue with it.

# Steps to reproduce
_lxd init_

Do you want to configure a new storage pool (yes/no) [default=yes]? 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (dir, btrfs, lvm) [default=dir]: 
Would you like LXD to be available over the network (yes/no) [default=no]? 
Would you like stale cached images to be updated automatically (yes/no) [default=yes]? 
Would you like to create a new network bridge (yes/no) [default=yes]? 
What should the new bridge be called [default=lxdbr0]? 
What IPv4 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]? 
What IPv6 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]? 
error: Failed to run: dnsmasq --strict-order --bind-interfaces --pid-file=/var/lib/lxd/networks/lxdbr0/dnsmasq.pid --except-interface=lo --interface=lxdbr0 --quiet-dhcp --quiet-dhcp6 --quiet-ra --listen-address=10.195.61.1 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/lib/lxd/networks/lxdbr0/dnsmasq.leases --dhcp-hostsfile=/var/lib/lxd/networks/lxdbr0/dnsmasq.hosts --dhcp-range 10.195.61.2,10.195.61.254,1h --listen-address=fd42:eb7:2b20:965::1 --enable-ra --dhcp-range ::,constructor:lxdbr0,ra-stateless,ra-names -s lxd -S /lxd/ --conf-file=/var/lib/lxd/networks/lxdbr0/dnsmasq.raw -u lxd: dnsmasq: bad command line options: try --help

**Comment by stgraber** [comment]
Hmm, that's going to become annoying if we need to add version checks for dnsmasq now...

**Comment by stgraber** [comment]
A temporary workaround for you is to start LXD with "--debug", this will have it skip that part of the code.

**Comment by stgraber** [comment]
What version of dnsmasq do you have? Apparently this feature has been included in dnsmasq 2.67 back in late 2013.

**Comment by rayxis** [comment]
The version is 2.66. I don't know why none of the centos repos haven't included an update since then.

**Comment by stgraber** [comment]
What does this show you?

    dnsmasq --version | head -1 | awk '{print $3}'

**Comment by stgraber** [comment]
Hopefully that'll print 2.66. We can add a version check but I need to be reasonably sure that dnsmasq's --version output is constant :)

**Comment by rayxis** [comment]
It's saying 2.66. I decided to just download and build a newer copy (2.77). I'm jumping through a ton of hoops everytime I install lxd on centos anyway, so it's not that much more big of a deal. Most of the headache is coming from shadow-utils getting along with libtool, not an lxd issue though. Maybe the repos can add lxd so I don't have to pretend I'm using Slackware again. :) It's doubtful though since they'll have to upgrade the kernel, lxc, lxcfs (not even really sure if this is being used) and shadow-utils.

**Comment by rayxis** [comment]
Boom. The update to 2.77 worked. Thanks!

**Comment by stgraber** [comment]
Ok, cool. I'll send a branch which adds logic to detect the dnsmasq version and skip those flags if on < 2.67, that may help some other users.

**Comment by stgraber** [comment]
@albertodonato can you take care of this one? We'll want a function that lets us compare dnsmasq versions and if it's less than 2.67, not pass the --quiet-* options.
