### ISSUE TITLE
What is the best way to go about resizing rbd based images?

### ISSUE THREAD

**Issue by Mantwon** [lxc/lxd#3760]
What I've done now:

1) stop container
2) rbd resize <image> --size 30G
3) rbd map <image> 
4) xfs_growfs /dev/rbpath
5) rbd unmap <image>
6) start container 

is there an easier way to do this? is this bad to do it this way?

**Comment by brauner** [comment]
I can send a branch to implement this. What you did is fine but your lxd instance will have the wrong size property. You'd need to manually update it in the db iff you know what you're doing. :)

**Comment by Mantwon** [comment]
Branch will be fine, I have a build pipleline setup to cut my own packages (I already cut a package for the previous changes the last while).

**Comment by brauner** [comment]
@Mantwon, I currently cannot access our ceph test server. If you could test and report back any errors that would be +1.

**Comment by stgraber** [comment]
@brauner what's wrong with our test server?

**Comment by brauner** [comment]
@stgraber, as i said on IRC I can't reach canonical-lxd to jump through to the test server.

**Comment by Mantwon** [comment]
I think there was still some math wrong somewhere, I was able to use 100G but it actually made the volume 100T

**Comment by Mantwon** [comment]
hah yeah

I made it 1T and the resulted in 1024T

**Comment by brauner** [comment]
What exactly did you pass to LXD? I'm especially curious about the suffix since we only support "TB" and not "T".

**Comment by Mantwon** [comment]
ah yeah, that was just my lingo... I put TB into the file, but I just meant T.

I compiled it w/ what I thought might fix it and it did - but I don't know if there is a better way.

```
diff --git a/lxd/storage_ceph_utils.go b/lxd/storage_ceph_utils.go
index 1200677..a8bb541 100644
--- a/lxd/storage_ceph_utils.go
+++ b/lxd/storage_ceph_utils.go
@@ -1582,7 +1582,7 @@ func (s *storageCeph) rbdShrink(path string, size int64, fsType string,
                "--id", s.UserName,
                "--cluster", s.ClusterName,
                "--pool", s.OSDPoolName,
-               "--size", fmt.Sprintf("%dM", (size/1024)),
+               "--size", fmt.Sprintf("%dM", (size/1024/1024)),
                fmt.Sprintf("%s_%s", volumeTypeName, volumeName))
        if err != nil {
                logger.Errorf(`Could not shrink RBD storage volume "%s": %s`,
@@ -1637,7 +1637,7 @@ func (s *storageCeph) rbdGrow(path string, size int64, fsType string,
                "--id", s.UserName,
                "--cluster", s.ClusterName,
                "--pool", s.OSDPoolName,
-               "--size", fmt.Sprintf("%dM", (size/1024)),
+               "--size", fmt.Sprintf("%dM", (size/1024/1024)),
                fmt.Sprintf("%s_%s", volumeTypeName, volumeName))
        if err != nil {
                logger.Errorf(`Could not extend RBD storage volume "%s": %s`,
```

**Comment by brauner** [comment]
That patch is correct. We pass in the size converted to bytes so we should divide by 1024 two times to get MB. Can you send a signed-off patch?

**Comment by Mantwon** [comment]
#3794 submitted
