### ISSUE TITLE
Failure to run snaps in juju-launched LXD container with artful host

### ISSUE THREAD

**Issue by devec0** [lxc/lxd#3762]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: Artful Aardvark 17.10
 * Container Distribution version: Xenial Xaurus 16.04
 * The (relevant) output of "lxc info":
```
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.11.0-13-generic
  server: lxd
  server_pid: 22619
  server_version: "2.17"
  storage: dir
  storage_version: "1"
```
# Issue description

When attempting to launch a charm which requires the installation of a snapped package, all attempts to launch snapd fail within the created Xenial LXD container, when launched by Juju. Manually launching a container, and then running `snap install hello-world` results in successful install. When the container is launched with Juju, `snapd ` will not even start, with the following error -
```
snapd.service: Failed at step NICE spawning /usr/lib/snapd/snapd: Permission denied
```

Setting `security.nested=true` on the coantainer does not help, setting `security.privileged=true` however works around the problem, so it appears to be related to user namespace mapping.

lxc.conf snipped from Juju launched container -
```
lxc.cap.drop = sys_time sys_module sys_rawio
lxc.mount.auto = proc:rw sys:rw
lxc.autodev = 1
lxc.pts = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none rbind,create=dir,optional
lxc.mount.entry = /sys/firmware/efi/efivars sys/firmware/efi/efivars none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/security sys/kernel/security none rbind,create=dir,optional
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional
lxc.include = /usr/share/lxc/config/common.conf.d/
lxc.mount.entry = proc dev/.lxc/proc proc create=dir,optional
lxc.mount.entry = sys dev/.lxc/sys sysfs create=dir,optional
lxc.logfile = /var/log/lxd/juju-788b6f-3/lxc.log
lxc.loglevel = warn
lxc.arch = linux64
lxc.hook.pre-start = /usr/bin/lxd callhook /var/lib/lxd 20 start
lxc.hook.post-stop = /usr/bin/lxd callhook /var/lib/lxd 20 stop
lxc.tty = 0
lxc.utsname = juju-788b6f-3
lxc.mount.entry = /var/lib/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.aa_profile = lxd-juju-788b6f-3_</var/lib/lxd>//&:lxd-juju-788b6f-3_<var-lib-lxd>:
lxc.seccomp = /var/lib/lxd/security/seccomp/juju-788b6f-3
lxc.id_map = u 0 165536 65536
lxc.id_map = g 0 165536 65536
lxc.rootfs.backend = dir
lxc.rootfs = /var/lib/lxd/containers/juju-788b6f-3/rootfs
lxc.network.0.type = veth
lxc.network.0.flags = up
lxc.network.0.link = lxdbr0
lxc.network.0.hwaddr = 00:16:3e:c1:14:c7
lxc.network.0.name = eth0
lxc.mount.entry = /var/lib/lxd/shmounts/juju-788b6f-3 dev/.lxd-mounts none bind,create=dir 0 0
```

# Steps to reproduce

 1. On Artful host - `juju deploy cs:ubuntu --series=xenial xenial`
 2. jump into Xenial container `juju ssh xenial/0`
 3. Try to install hello world snap `snap install hello-world`
 4. Observe that snapd is not responding, check logs with `systemctl`, note service failure on boot.
 5. Setting security.privileged=true on the contianer, and restarting it, allows the snap install to succeed.

NB: Anecdotally I did get snapd to start with just security.nesting, if I ran the snapd process interactively from a terminal, but it seemed quite unstable and crashed whilst installing snaps, with no notable output. `security.privileged` was the only workaround which worked reliably in the end, which is why I suspect the user namespace mapping functionality.

# Information to attach

 - [x] any relevant kernel output (`dmesg`)
Nothing notable in dmesg.

 - [x] container log (`lxc info NAME --show-log`)
```
Name: juju-788b6f-3
Remote: unix://
Architecture: x86_64
Created: 2017/09/04 07:49 UTC
Status: Running
Type: persistent
Profiles: default, juju-k8s-flannel
Pid: 9239
Ips:
  lo:	inet	127.0.0.1
  lo:	inet6	::1
  lxdbr0:	inet6	fe80::28b6:66ff:fe1d:6689
  lxdbr0:	inet6	fe80::1
  eth0:	inet	10.118.96.87	vethSOXQ69
  eth0:	inet6	fe80::216:3eff:fec1:14c7	vethSOXQ69
Resources:
  Processes: 67
  CPU usage:
    CPU usage (in seconds): 51
  Memory usage:
    Memory (current): 619.69MB
    Memory (peak): 759.04MB
  Network usage:
    eth0:
      Bytes received: 148.68MB
      Bytes sent: 4.77MB
      Packets received: 94163
      Packets sent: 63378
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    lxdbr0:
      Bytes received: 0B
      Bytes sent: 750B
      Packets received: 0
      Packets sent: 9

Log:

            lxc 20170904074908.139 WARN     lxc_cgfsng - cgroups/cgfsng.c:chown_cgroup_wrapper:1502 - Error chmoding /sys/fs/cgroup/unified//lxc/juju-788b6f-3: No such file or directory
```
 - [x] main daemon log (`cat /var/log/lxd/lxd.log`)
```
action=start created=2017-09-04T07:49:03+0000 ephemeral=false lvl=info msg="Started container" name=juju-788b6f-3 stateful=false t=2017-09-04T17:49:08+1000 used=1970-01-01T00:00:00+0000
```

**Comment by stgraber** [comment]
This is a snapd bug.

**Comment by stgraber** [comment]
https://bugs.launchpad.net/snapd/+bug/1709536

**Comment by devec0** [comment]
Thanks for the pointer Stéphane, my searches did not turn this up. I'll me-too the snapd bug.
