### ISSUE TITLE
Setting lxd.idmap via raw.lxc

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3767]
When users set `lxc.idmap` directly via `raw.lxc` LXD will happily create double mappings. Assume that LXD uses the idmap:

```
lxc.idmap = u 0 1000000 1000000000
lxc.idmap = g 0 1000000 1000000000
```
for the container but a user also sets:

```
raw.lxc: |-
   lxc.idmap = u 0 1000000 1000000000
   lxc.idmap = g 0 1000000 1000000000
```
directly. In this case LXD will create the union of these mappings. While I understand that setting `raw.lxc` is discouraged it is still helpful for users to be able to set `lxc.idmap` via `raw.lxc` directly even if `raw.idmap` is available. It still let's experienced users fine-tune the idmap settings maybe even beyond `raw.idmap`. In any case, I see three options here:
1. In case LXD detects a `raw.lxc` setting with `lxc.idmap` it will simply not look itself for an idmap but rather obey the user.
2. Look for any double idmappings and remove them. Create the union of the remaining idmappings.
3. Ban `lxc.idmap` from being set directly entirely.

Options 1. and 2. are potentially dangerous in the face of `idmap.isolated=true`. A knowledgeable user could potentially trick LXD into using an idmap that intersects with the idmap of a container hat has `idmap.isolated=true`.

@hallyn, @stgraber, thoughts?

**Comment by stgraber** [comment]
I'd say just ignore this case. raw.lxc is appended to the generate config, we shouldn't try to special case things there.

The supported way of modifying id mapping in LXD is raw.idmap, not raw.lxc.

**Comment by brauner** [comment]
@stgraber, meaning don't implement any of the options and just let it fail as is?

**Comment by stgraber** [comment]
Yep. I don't think we need to ban it as it's very useful for us to debug stuff and that'd break users who upgraded from LXD releases that didn't have raw.idmap.

So just keep things as they are now and make sure we never tell anyone to use raw.lxc for idmap stuff.

**Comment by brauner** [comment]
Cool.
