### ISSUE TITLE
error: Failed to delete RBD storage volume for container "test" on storage pool "node001"

### ISSUE THREAD

**Issue by Mantwon** [lxc/lxd#3782]
Greetings,

Would it be possible to add a --force to the delete of an rbd based container? for now this error occurs when you try to delete a container which failed during the image creation step.

```error: Failed to delete RBD storage volume for container "test" on storage pool "node001"```

I've been manually removing data from the lxd.db 

```delete from containers where id=7```
```delete from storage_volumes_config where id=7```

*** the creation failed due to default gateway not being set so it couldn't pull the image, which was my fault.

**Comment by stgraber** [comment]
Looks like a bug in the ceph driver. The database entry shouldn't be created in the first place if the storage fails to create.

@brauner

**Comment by brauner** [comment]
@Mantwon, but no storage volume got created on disk?

**Comment by Mantwon** [comment]
no storage volume existed on disk.

I actually think I remember seeing this in the debug, I think it has to do with the rollback maybe - it removed the rbd image but didn't remove the container.

**Comment by brauner** [comment]
Ah, so this is in the container codepath, thanks!

**Comment by brauner** [comment]
@stgraber, that's not a bug in the ceph driver, that's a bug in `containerCreateInternal()` or `containerCreateFromImage()` iiuc since they creates the db entry before the storage but don't wipe the db entry on error.
