### ISSUE TITLE
libacl dependency is onerous 

### ISSUE THREAD

**Issue by jtopjian** [lxc/lxd#3787]
https://github.com/lxc/lxd/pull/3625 introduced a dependency of libacl. This now requires applications that consume LXD to have `libacl1-dev` (or similar, depending on the distribution), gcc, et al installed when building, which is kind of a pain.

Is libacl required when a Go application is _only_ communicating with LXD via the API? If it's not required, can the libacl stuff be moved out of `shared` so that the LXD client package (and dependencies) be used without having to install these libraries and tools?

**Comment by stgraber** [comment]
We should be able to move all the idmap functions and related code to a separate shared/idmap package which would then only be used from the lxd and fuidshift tools, eliminating that dependency for the client code.

**Comment by stgraber** [comment]
@albertodonato can you look into that?

**Comment by jtopjian** [comment]
That did the trick! Thank you so much for doing this so quickly. You folks rock!
