### ISSUE TITLE
why Ceph RBD can not be used as a LXD storage backend with version 2.17

### ISSUE THREAD

**Issue by mrliaon** [lxc/lxd#3788]
# Required information 
* Distribution: Ubuntu
 * Distribution version: 16.04.2
 * The output of "lxc info" or if that fails:
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-62-generic
  server: lxd
  server_pid: 12154
  server_version: "**2.17**"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu15

# Issue description

when using "lxd init" to add a new storage pool , ceph rbd can not be listed ,it seems like the storage just support "dir, btrfs, lvm, zfs" . i got the news showing that ceph rbd can now be used as a LXD storage backend with version 2.16 , why newest version 2.17 not ? 

# Steps to reproduce

1. running "lxd init"
2.add a new storage pool
3. support filesystem list: "dir, btrfs, lvm, zfs"

**Comment by stgraber** [comment]
Make sure you have ceph-common or whatever package provides the "ceph" and "rbd" commands.

We only list filesystems that are supported by your system.

**Comment by stgraber** [comment]
That's an Ubuntu 16.04 system using the same LXD you're using but on a system which does have the ceph tools installed and configured:

```
root@buildd03:~# lxd init
Do you want to configure a new storage pool (yes/no) [default=yes]? 
Name of the new storage pool [default=default]: blah
Name of the storage backend to use (dir, btrfs, ceph, lvm, zfs) [default=zfs]: 
```

**Comment by mrliaon** [comment]
thank u very much
