### ISSUE TITLE
Feature request: update backup.yaml during snapshot creation

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#3792]
Please correct me if I'm wrong.
Currently if there is snapshot created it can be restored properly only on the same machine.
It is because the container configuration of the snapshot time is saved only in the central lxd database. Am I right?
If it's not copied to the backup server together with the data volume, then the configuration cannot be restored.
Hence it would be desired to update backup.yaml if a snapshot created.

**Comment by stgraber** [comment]
Snapshots do contain a backup.yaml. If you backup only a snapshot and then restore that on a target system in the location where the full container would be expected, "lxd import" should allow you to import.

Did you actually confirm that your snapshot doesn't contain a backup.yaml file?

**Comment by brauner** [comment]
As snapshots are literally snapshot of the original container they very much do contain a `backup.yaml` file. I don't really understand what the issue is here.
