### ISSUE TITLE
RAM usage inside and outside container don't match

### ISSUE THREAD

**Issue by 19wolf** [lxc/lxd#3793]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu 16.04.3
 ``` 
driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-041300-generic
  server: lxd
  server_pid: 1480
  server_version: "2.17"
  storage: btrfs
  storage_version: "4.4"
```

# Issue description

Memory usage inside and outside container don't match.

# Steps to reproduce

```
$ lxc exec container1 -- free -h
              total        used        free      shared  buff/cache   available
Mem:            11G        4.9G        6.8G         41M         14M        6.8G
Swap:            0B          0B          0B
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            11G        3.4G        537M         41M        7.8G        7.8G
Swap:            0B          0B          0B
```

**Comment by stgraber** [comment]
Can you file a bug at https://github.com/lxc/lxcfs including your /proc/meminfo from the host and from inside the container? As well as the content of /sys/fs/cgroup/memory/lxc/container1/memory.stat?

**Comment by stgraber** [comment]
This is a lxcfs bug, which I suspect is related to the way we count the usage of cached/buffered resources.

**Comment by 19wolf** [comment]
#https://github.com/lxc/lxcfs/issues/210

**Comment by 19wolf** [comment]
Should I assume my host's `free -h` is the more accurate?
