### ISSUE TITLE
Monitoring Disk I/O for containers

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#3797]
Ubuntu 16.04
ZFS
LXD 2.17

I'd like to be able to track down which specific containers are using high disk i/o. This is usually the cause of slowness on our servers, but it can be hard to figure out which container is misbehaving when I have 30+ containers on a host.

I have looked at zpool iostat - but that just gives me overall stats for the pool. lxd info doesn't reveal much useful information either.

Any hints or suggestions on how one can monitor disk i/o use in containers?

**Comment by stgraber** [comment]
I'd recommend using "iotop" on your host, that tends to be the easiest way.

The blkio cgroup stats aren't super useful in general, so even if we were to expose that over the API, you'd have to be very lucky for them to make sense :)

**Comment by Kramerican** [comment]
Hmmm ... Well, I tried iotop early on but dismissed it, as all that gives me is an overview of processes using disk i/o at this very second, without me being to discern which container they belong to. 

That is, I have lots of LAMP and LEMP stacks, so I'd typically see quite a few php-fpm processes doing something - but with no clue which container to start poking around in...

Any magic commandline options or shortcuts which will enable me to identify which container is (ab)using disk i/o? I'm not sure iotop is what I'm looking for. Well ... Maybe I could look at the user id as seen from the host perspective, which might be some integer like **100113** and then somehow track which container that user belongs to?

No other way of discerning which zfs mount is more busy than others?

**Comment by stgraber** [comment]
ZFS doesn't do I/O tracking so that's not going to help you.
iotop will show you the PID and you can then track down what container that belongs to in "ps fauxww"

I've also just confirmed that ZFS doesn't hit the blkio counters so it reports 0 bytes read which means cgroups won't help you either.

So iotop/iostat is unfortunately your best bet, as limited as they may be.

**Comment by Kramerican** [comment]
Alrighty  I just played with it a bit, and I've found something somewhat workable:

Execute iotop with `iotop -a -P -o -d 5` - This means: cumulative, processes not threads, only ones actually using i/o, interval 5 seconds

Identidy a PID of something you are interested in, then fire up htop, hit F5 to go to tree view, type in the PID (don't use the search function, just start typing the numerical PID and htop will find it) then scroll up the tree untill you see which container the process belongs to.

A little tedious - but it works!

**Comment by stgraber** [comment]
cat /proc/PID/cgroup may also be a quick way of figuring out the container it belongs to

**Comment by Kramerican** [comment]
I have spent a great deal of time researching this subject and I have found no perfect solution. I have been in discussions with the folks over at the zfs mailing list, and the gist of it is that it is hard to implement monitoring at the zfs level. There are tools available for Solaris, but nothing for us Ubuntu/Debian folks.

There is some hope however, as they said they would review this at the yearly zfs hackathon which happened yesterday. I am waiting to get word from there.

Anyway, in the meantime I have hacked something together myself for us lxd folks. I am unsure if this is a correct approach by any means, but it _seems_ to work as I have used this with success to track down a misbehaving container.

The implementation is a CLI php script - my apologies for sloppy code, but this was done as a quick and dirty solution:

[https://gist.github.com/anonymous/6432dea56e022e65d15984afc15c30c1](https://gist.github.com/anonymous/6432dea56e022e65d15984afc15c30c1)

You may need to run `dos2unix monitor-lxd-io.php` before you can do a `chmod +x monitor-lxd-io.php` - alternatively remove the first line and just run it like `/usr/bin/php monitor-lxd-io.php`

Anyway, this will give you output like:

```
Refreshing every 5 seconds
| Name         | rchar       | +change | wchar      | +change | syscr   | +change | syscw   | +change | read_bytes  | +change | write_bytes | +change |
| mycontainer  | 5745651611  | 0       | 2806271741 | 0       | 2029803 | 0       | 546089  | 0       | 7275048816  | 0       | 2707803220  | 0       |
| test         | 1855628720  | 48 B    | 31453417   | 0       | 8187818 | 6 B     | 1184452 | 0       | 4135410401  | 0       | 89934       | 0       |
| foo          | 5938105265  | 0       | 2983313474 | 0       | 899599  | 0       | 450646  | 0       | 7010390311  | 0       | 2788340752  | 0       |
... stuff omitted for brevity
| Cumulative   |             | 6.88 KB |            | 0 B     |         | 26 B    |         | 0 B     |             | 0 B     |             | 0 B     |
```

There is a link in the script source to a page that explains what the columns mean. I also output the delta +change for each column between refreshes, and at the bottom the total sum of all rows.

The way this works is something I came up through trial and error. I found out that you could watch disk i/o for a PID by running `watch -n 1 cat /proc/PID/io` - now, looking at the process tree for an LXD container, I saw that it would look something like:

```
  [lxc monitor] /var/lib/lxd/containers NAME
  |_ /sbin/init
     |_ etc...
```
Watching the lxc monitor process came up short, BUT if I watched the /sbin/init process, it _looks like_ I get something approaching real disk i/o for all processes in that container.

Run this and combine it with `zpool iostat -v 5` and you get a pretty good idea what's going on.

Anyway, this works for me, no guarantees it will work for you, the code sucks, all the caveats etc. etc.

**Comment by Kramerican** [comment]
I have spent a great deal of time researching this subject and I have found no perfect solution. I have been in discussions with the folks over at the zfs mailing list, and the gist of it is that it is hard to implement monitoring at the zfs level. There are tools available for Solaris, but nothing for us Ubuntu/Debian folks.

There is some hope however, as they said they would review this at the yearly zfs hackathon which happened yesterday. I am waiting to get word from there.

Anyway, in the meantime I have hacked something together myself for us lxd folks. I am unsure if this is a correct approach by any means, but it _seems_ to work as I have used this with success to track down a misbehaving container.

The implementation is a CLI php script - my apologies for sloppy code, but this was done as a quick and dirty solution:

[https://gist.github.com/Kramerican/b2bd470cf43c9b72852b891bd9e14007](https://gist.github.com/Kramerican/b2bd470cf43c9b72852b891bd9e14007)

You may need to run `dos2unix monitor-lxd-io.php` before you can do a `chmod +x monitor-lxd-io.php` - alternatively remove the first line and just run it like `/usr/bin/php monitor-lxd-io.php`

Anyway, this will give you output like:

```
Refreshing every 30 seconds
| Name         | rchar        | +change   | wchar         | +change   | syscr      | +change   | syscw      | +change   | read_bytes   | +change   | write_bytes  | +change   |
| mycontainer  | 12895696134  | 128.05 KB | 7863801308    | 36.23 KB  | 13097305   | 382 B     | 3485960    | 45 B      | 15913154313  | 89.19 KB  | 4238106469   | 6.73 KB   |
| foocontainer | 9607027211   | 830.62 KB | 1987152315    | 108.12 KB | 27337327   | 1.3 KB    | 3967607    | 301 B     | 11345360131  | 707 KB    | 1482422031   | 76.89 KB  |
| test         | 9751236900   | 5.17 KB   | 3805920291    | 0         | 12278839   | 148 B     | 1311120    | 0         | 10986836665  | 0         | 3131067708   | 0         |
... lots more lines omitted for brevity
| Cumulative   |              | 125.86 MB |               | 81.18 MB  |            | 508.59 KB |            | 190.53 KB |              | 123.32 MB |              | 30.54 MB  |
```

There is a link in the script source to a page that explains what the columns mean. I also output the delta +change for each column between refreshes, and at the bottom the total sum of all rows.

The way this works is something I came up through trial and error. I found out that you could watch disk i/o for a PID by running `watch -n 1 cat /proc/PID/io` - now, my - probably idiotic - logic was then to just start with a list of lxc monitor processes, then descend into all children of that process, get disk io stats and add it all together.

This works, but is veeeery slow on a busy system. Takes a good 30 seconds for the script to gather data on 30 containers. There's probably all sorts of ways to optimize this - but it works..!

Run this and combine it with `zpool iostat -v 5` and you get a pretty good idea what's going on with the system.

Anyway, works for me, no guarantees it will work for you, the code sucks, all the caveats etc. etc.
