### ISSUE TITLE
Incremental stateless migration of containers

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3798]
For very big containers which can't be live-migrated, it would be nice if we would support:

    lxc move c1 dest: --stateless

Where if "c1" is running and "--stateless" is passed, we'd hit the exact same codepath as live migration except that we'd never dump/restore state. Instead we'd just do a clean shutdown of the container and then start it again on the target (we'd use the same container shutdown timeout as we do on LXD shutdown).

This should be a first step towards https://github.com/lxc/lxd/issues/1987 and would massively improve the experience for those who aren't lucky enough to have live-migratable containers.

**Comment by brauner** [comment]
Right, I spent **way** too much time thinking about this somehow. What confused me is your request to stop the container first which is not needed I think. The stateless copy path doesn't stop the container either and actually can't. So the patch I'm sending will not stop the container in the move path either. If we really really wanted to - and there's a good argument for it - we can stop it in the command line tool before the copy on a stateless request. However, doing this on the LXD side would require more work since we'd need to be able to discern copy from move requests. Anyway, here's my outline:


    When a container is running users can pass "--stateful" to the lxd command line
    tool "lxc move". This will move the container and restore the state of the
    container on the target.
    My original implementation of this feature only applied to stateless container
    copies but not to requests to move a container. The only thing we need to do is
    pass the stateless argument along in the move codepath for the "lxc move"
    command line tool and then restore state on the receiving side based on the
    container's config. This is trivial since we know the source container's state
    because we preserve volatile keys when moving containers.

**Comment by stgraber** [comment]
@mgariepy reported that there appears to be a missing final sync during migration, so that anything which changed on disk between the beginning of the migration and the time the container is stopped on the source is lost.

**Comment by stgraber** [comment]
@brauner

**Comment by brauner** [comment]
@mgariepy, can you reproduce this with a running copy as well?

**Comment by brauner** [comment]
I mean

    lxc copy bla some-remote: --stateless

where `bla` is running on the source.

**Comment by jflandry** [comment]
# Source: nfs005-lxd-tmp

lxc move stretch lxd-d6-infra-beta:stretch --stateless

zpool history shows:

```
2017-09-22.18:04:29 zfs snapshot -r tank/lxd/containers/stretch@migration-send-a27ea649-4a20-4163-9a94-bc2e08291397
2017-09-22.18:04:33 zfs destroy -r tank/lxd/containers/stretch@migration-send-a27ea649-4a20-4163-9a94-bc2e08291397
2017-09-22.18:04:39 zfs destroy -r tank/lxd/containers/stretch
```

# Dest remote: lxd-d6-infra-beta

zpool history shows:

```
2017-09-22.18:04:22 zfs create -o mountpoint=none -o canmount=noauto -p tank/lxd/containers/stretch
2017-09-22.18:04:23 zfs set mountpoint=/var/lib/lxd/storage-pools/default/containers/stretch tank/lxd/containers/stretch
2017-09-22.18:04:23 zfs set refquota=10737418240 tank/lxd/containers/stretch
2017-09-22.18:04:30 zfs receive -F -u tank/lxd/containers/stretch
2017-09-22.18:04:32 zfs destroy -r tank/lxd/containers/stretch@migration-send-a27ea649-4a20-4163-9a94-bc2e08291397
```

So, zfs send/receive, container stop on the source, container start on the destination.
What would be required is at least one final incremental send/receive after the stop, before restarting on the destination.
