### ISSUE TITLE
cant install redis-server on a debian/buster container

### ISSUE THREAD

**Issue by Kuinox** [lxc/lxd#3799]
# Required information

 * Distribution: Debian 
 * Distribution version: Stretch/Buster
# Issue description
Bug reproduced with a fresh install of debian buster on a VM on another hardware.
lxd installed with snapd.
# Steps to reproduce

 1. lxc launch images:debian/buster test
 2. lxc exec test /bin/bash
 3. apt-get install redis-server

```Job for redis-server.service failed because the control process exited with error code.
See "systemctl  status redis-server.service" and "journalctl  -xe" for details.
invoke-rc.d: initscript redis-server, action "start" failed.
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2017-09-14 00:07:45 UTC; 9ms ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 297 ExecStopPost=/bin/run-parts --verbose /etc/redis/redis-server.post-down.d (code=exited, status=237/KEYRING)
  Process: 296 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=237/KEYRING)
  Process: 295 ExecStartPre=/bin/run-parts --verbose /etc/redis/redis-server.pre-up.d (code=exited, status=237/KEYRING)
```
Same install work fine a debian/stretch using backports.

**Comment by stgraber** [comment]
Looks like it's an issue with systemd's private namespaces as used by the redis-server unit.

**Comment by Kuinox** [comment]
So i should post the issue on redis ? Between, redis work fine on my debian buster, but not in the container.

**Comment by stgraber** [comment]
I've been looking into this a bit but haven't yet pinpointed exactly what part of the systemd unit is failing.
There is a good chance that this is effectively a systemd bug but I need to dig into it some more to see exactly what bit's blocking this (and redis is using just about all systemd feature so that's not helping).

**Comment by kakulukia** [comment]
i think i have the same issue or at least the same error message, been trying o find out the cause, but /var/log/syslog or the suggested "journalctl  -xe" is not printing any clue as to whyits not starting. Starting it manually works tho as well as starting with the redis user like this

    su -c "/usr/local/bin/redis-server /etc/redis/redis.conf" -s /bin/sh redis

So rights should be fine, files are there .. something is wrong with the way its startet, but my linux knowledge doesnt help me any further. :(

**Comment by PierrePaul** [comment]
I've got the same issue on ubuntu16.04. To fix the issue I open up the systemd file `/etc/systemd/system/redis.service` and change :
```
PrivateTmp=no
PrivateDevice=no
ProtectHome=no
```

**Comment by stgraber** [comment]
Ok, so sounds like it's indeed systemd attempting to do things which isn't possible in an unprivileged container. PrivateDevice is the most annoying one as it causes systemd to attempt to create device nodes, which the kernel won't allow. PrivateTmp and ProtectHome I believe mostly rely on the ability to create a new mount namespace which is allowed, but it may then hit issues with specific mount entries.

Overall, it'd be great if systemd could be made a bit more clever and work better inside unprivileged containers in such cases but that's sadly outside of LXD's control :(

**Comment by kakulukia** [comment]
@PierrePaul at which section do i have to add those three settings?
I tried all three (Unit/Service/Install), but none ofthat worked. Do i have to add an additional section?

**Comment by PierrePaul** [comment]
@kakulukia it's in service, for the debian/buster image, it's in the second block. Putting the three of them to `no` will give you another error, 

`Failed at step KEYRING spawning /usr/bin/redis-server: Permission denied` 

Which seems related to https://github.com/systemd/systemd/pull/6876

**Comment by dawncold** [comment]
I masked `redis-server.serivce` (sudo systemd mask redis-server.service) before installing it via apt, and run redis by command line executable instead of `systemd`

**Comment by davidfavor** [comment]
Tried the above systemd changes + they fail to work, at least in LXD-3.2 (machine level) + Ubuntu Bionic running at container level.
