### ISSUE TITLE
file system support for 'volume.block.filesystem'

### ISSUE THREAD

**Issue by Mantwon** [lxc/lxd#3801]
Greetings (again),

I am just wondering if there is any plan to add more file systems for 'lxc storage create lxd ceph volume.block.filesystem' type configurations.

Right now I see ext4/xfs are only supported.

xfs + ceph are not playing nice at the moment, and would like to try a few different file systems for the backends there.

**Comment by stgraber** [comment]
What filesystems are you thinking about?

More can be added but this needs specific code in LXD for the LVM and Ceph code paths.

**Comment by Mantwon** [comment]
Actually, really now that I think about it -- probably just btrfs.

**Comment by stgraber** [comment]
Ok, that should be reasonably straightfoward to add. We just need to check how to re-generate the btrfs fs uuid on copy, assuming that btrfs would be confused by the exact same uuid being present multiple times.

**Comment by stgraber** [comment]
@albertodonato can you send a branch which adds support for mkfs.btrfs where we currently support mkfs.ext4 an mkfs.xfs?

**Comment by stgraber** [comment]
@albertodonato this will need an API extension string.
