### ISSUE TITLE
Extend UserAgent string to include distribution and kernel architecture and version

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3819]
This will make it much easier to figure out what distribution and kernel versions to focus our testing on based on image server access. It will also allow us to filter specific images based on whether the target host is going to be able to run it.

**Comment by albertodonato** [comment]
We want something like the following:

- `LXD 2.18 (Windows; x86_64)`
- `LXD 2.18 (Darwin; x86_64)`
- `LXD 2.18 (Linux; x86_64; 4.4.0-78-generic; Ubuntu 16.04)`

**Comment by stgraber** [comment]
To cover some of the corner cases:

 - Unable to get kernel information: `LXD 2.18 (Linux; x86_64; Ubuntu 16.04)`
 - Unable to get OS information: `LXD 2.18 (Linux; x86_64; 4.4.0-78-generic)`
 - Unable to get either: `LXD 2.18 (Linux; x86_64)`
