### ISSUE TITLE
Feature request: import storage pool

### ISSUE THREAD

**Issue by treba123** [lxc/lxd#3824]
Right now, a storage pool can't be imported (afaik). 
To emulate that, I create a storage pool within an empty (btrfs-)subvolume, replace it with the one I want to import and then import the containers with `lxd import ...`.

It would be great if there was either something like `lxd storage import` or if `lxc storage create` had a flag to allow creation in not-empty source folders. Currently it aborts if the source folder is not empty.

**Comment by stgraber** [comment]
"lxd import" will import the storage pool for you. You just need to mount things in place under /var/lib/lxd/storage-pools/POOL and then run "lxd import" for one of the containers. The storage pool DB entry will then get created based on the storage pool data contained in the backup.yaml of that container.

**Comment by treba123** [comment]
Ah cool! Is that documented somewhere already? Awesome feature.

**Comment by stgraber** [comment]
```This recovery mechanism is mostly meant for emergency recoveries and will try to re-create container and storage database entries from a backup of the storage pool configuration.```

From: https://github.com/lxc/lxd/blob/master/doc/backup.md
