### ISSUE TITLE
Containers and lxdbr0 bridge lost ip after upgrade on 2.18

### ISSUE THREAD

**Issue by ldsbiblibre** [lxc/lxd#3837]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu
 * Distribution version: Ubuntu 16.04.3 LTS 
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-96-generic
   * LXC version:                        
   * LXD version: 2.18
   * Storage backend in use: dir

# Issue description
After xenial ubuntu upgrade lxd switch to  2.18
i reboot and no ip for lxdbr0 and no ip for container
It set manualy ip for lxdbr0 "sudo ip addr add dev lxdbr0 10.215.181.1/24" and launch a container but  always no ip 
Here is syslog entry when i try to start the container

# Steps to reproduce

 1. apt update ; apt upgrade
 2. shutdown -r now
 3. lxc list (no ip for containers ; no ip for lxdbr0)

# Information to attach

 - [ ] syslog output
Sep 22 16:18:07 blabla kernel: [ 3482.496088] lxdbr0: port 1(vethFVYDNI) entered disabled state
Sep 22 16:18:07 blabla kernel: [ 3482.501486] device vethFVYDNI left promiscuous mode
Sep 22 16:18:07 blabla kernel: [ 3482.501490] lxdbr0: port 1(vethFVYDNI) entered disabled state
Sep 22 16:18:08 blabla kernel: [ 3483.329216] audit: type=1400 audit(1506089888.350:166): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-user10-blabla-sandbox_</var/lib/lxd>" pid=77593 comm="apparmor_parser"
Sep 22 16:18:16 blabla kernel: [ 3491.046769] audit: type=1400 audit(1506089896.070:167): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-user10-blabla-sandbox_</var/lib/lxd>" pid=77629 comm="apparmor_parser"
Sep 22 16:18:16 blabla systemd-udevd[77631]: Could not generate persistent MAC address for vethB22DLS: No such file or directory
Sep 22 16:18:16 blabla kernel: [ 3491.057615] device vethCORADG entered promiscuous mode
Sep 22 16:18:16 blabla kernel: [ 3491.057808] IPv6: ADDRCONF(NETDEV_UP): vethCORADG: link is not ready
Sep 22 16:18:16 blabla kernel: [ 3491.146758] eth0: renamed from vethB22DLS
Sep 22 16:18:16 blabla kernel: [ 3491.167857] IPv6: ADDRCONF(NETDEV_CHANGE): vethCORADG: link becomes ready
Sep 22 16:18:16 blabla kernel: [ 3491.167961] lxdbr0: port 1(vethCORADG) entered forwarding state
Sep 22 16:18:16 blabla kernel: [ 3491.167971] lxdbr0: port 1(vethCORADG) entered forwarding state
Sep 22 16:18:31 blabla kernel: [ 3506.214893] lxdbr0: port 1(vethCORADG) entered forwarding state

 - [ ] container log (`lxc info NAME --show-log`)
            lxc 20170922143947.289 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20170922143947.289 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20170922143947.464 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20170922143947.464 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.

 - [ ] main daemon log (`cat /var/log/lxd/lxd.log`)
action=start created=2017-07-10T08:09:57+0000 ephemeral=false lvl=info msg="Starting container" name=user10-blabla-sandbox stateful=false t=2017-09-22T16:39:47+0200 used=2017-09-22T13:44:26+0000
action=start created=2017-07-10T08:09:57+0000 ephemeral=false lvl=info msg="Started container" name=user10-blabla-sandbox stateful=false t=2017-09-22T16:39:47+0200 used=2017-09-22T13:44:26+0000

**Comment by Winael** [comment]
Happy to see that I'm not alone with this weird issue. I totally broke my system try to fixed it. Now after remove and reinstall lxd i have an error on Invalid version format: Dnsmasq.

I saw there is a commit about that topic few days ago: https://github.com/lxc/lxd/pull/3816

Hope it could help

Cheers
Winael

**Comment by BlackDex** [comment]
Hello,
I Have the same issue!
I get messages about nettle, "Invalid version format: `nettle_hashes'".

> lxd[10140]: err="Invalid version format: `nettle_hashes'" lvl=eror msg="Failed to bring up network" name=lxdbr0 t=2017-09-22T12:11:12+0200
> Invalid version format: `nettle_hashes'

libnettle6: Installed: 3.3-1~cloud0 (from http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/ocata/main)

I reverted back to 2.17 and that solved the problem for me.

**Comment by n0guest** [comment]
And this aren't all of problems after upgrading to 2.18 ;)

In my case:

```
lxc init images:alpine/3.3 test
Creating test
error: Failed container creation:
- https://images.linuxcontainers.org: Failed to set LXC config: lxc.pty.max=1024
```

I solved it by upgrading all packages related lxd and lxc-related, then reboot system.

**Comment by stgraber** [comment]
@ldsbiblibre @Winael can you post the output of "dnsmasq --version" please?

**Comment by stgraber** [comment]
@n0guest yes, that's because of the LXC 2.1 migration. You indeed need to get both liblxc1 and lxd upgraded together or things won't work too well (unsure why a tighter dependency didn't get auto-generated as it should have...).

**Comment by n0guest** [comment]
@stgraber, but there is one small detail. Just upgrading lxc-related packages didn't helped at all. Any subcommand of lxd-cli which i tried ended with error. As a quick solution i rebooted system and it finally start working. But i still didn't figured what is the difference between before-reboot-with-new-lxc and after-reboot-with-new-lxc. May be you can clarify this mistery? I guess some libs where changed, when lxd was still running with old one?

**Comment by stgraber** [comment]
@n0guest So the main issue is that LXD got built against the liblxc 2.1 API (through go-lxc) but that library wasn't on your system at the time LXD got upgraded (due to broken dependency handling). When you then upgraded the library, LXD didn't get restarted and so didn't pick it up.

A "systemctl restart lxd" would have gotten you rid of most of the issues, with some warnings then still being present when interacting with containers which were based on the older liblxc version.


Once I figure out the dnsmasq issue above, I'll upload an updated lxd to the Ubuntu development release which will include a manual tighter dependency between lxd and liblxc1 >= 2.1, that should help avoid such issues for other users.

**Comment by stgraber** [comment]
```
Invalid version format: `nettle_hashes'
```

That should be enough for me to figure out what happened.

**Comment by stgraber** [comment]
@BlackDex the cloud archive doesn't seem to contain that libnettle6 package anymore. I wonder if that archive used to contain a broken dnsmasq/libnettle6 combo which you got installed somehow before they noticed and removed it.

Can you post "dpkg -l dnsmasq libnettle6" as well as the full output of "dnsmasq --version"?

**Comment by stgraber** [comment]
Attempting to manually install a 3.3-1 version of nettle, I'm getting the following output from dnsmasq, which would match the parsing error you got, but also indicates that your dnsmasq is likely in a bad shape:

```
root@vm04:~# dnsmasq --version
dnsmasq: Symbol `nettle_hashes' has different size in shared object, consider re-linking
Dnsmasq version 2.75  Copyright (c) 2000-2015 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
```
