### ISSUE TITLE
lxc copy container with snapshots to remote btrfs storage fails

### ISSUE THREAD

**Issue by astrablaster** [lxc/lxd#3843]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information
 * Distribution: Ubuntu 17.10
 * Distribution version: updated as of today 2017-09-25
 * The output of "lxc info" or if that fails:
Sending side (nikita):
root@nikita:/lxd# lxc info
config:
  core.https_address: '[::]:6443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 193.135.252.45:6443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFQTCCAymgAwIBAgIRAK4Xx5GezsnHJ16DCWHHwcIwDQYJKoZIhvcNAQELBQAw
    NDEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEUMBIGA1UEAwwLcm9vdEBu
    aWtpdGEwHhcNMTcwNzE5MDU1MDI2WhcNMjcwNzE3MDU1MDI2WjA0MRwwGgYDVQQK
    ExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QG5pa2l0YTCCAiIw
    DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAPh8tBebo80GLmVaqaUvWIKFLieH
    jUDpUuzpz/VjdOlDPeP3W2iysHZmO7NuE1eWZ6zg3Sgr+OJe4J/u5fu+of6MsXNn
    Y9PxC3WdDzil5e1vmTghMR9yrEcG/nS8q2MEC5Ldqy375jVdMXczwBPPt5L8RJsZ
    9D2K60gqn5lwLDpGqO1uERvISnsvWX2FV8EfyQKcbkSaiSXoKTqBt3q1nF6wlWdW
    VGSpDzQA9jxmhByeN/pvIcNC0GjCUTA4Wu07MjclytM0bVvJ2BIMHGXsNSuSUnUq
    TfWBoqx6utzGfZBXmONOA+Jyro/4EuVc55De6GpM7LczNSCO7j65IXDpJYUEORpP
    NQZTa2ioqCqU++Xxd+Slmw976YktDuIzuAEiLnC2nDUcc8YIaaFYaD3tKfaLAtjM
    ZDX7AXnJRM0fxUQkivee66zyVK+yRBUfA3o1Uqeg4wxxod28cHnMkVZoSGkB+CvV
    KuuW/h9B6Hy5QzbB+mXi+VX/GjuLwg2O9jiIokHLlszCK2I+y3/N157rzMXXbj11
    B4aHryE+dpHY2o4UR07IHByGKn3ux16yPo8LbhbNp/vnxK6yMy4BWtzXSUlnD/Hh
    A/GOe8mJ6Qp1YMiL5q3WWzHGknqTcIOAwJksVMfx7VrKfJ7lVp+1JcBekJp73/JQ
    PBunUu4AMRBKejA7AgMBAAGjTjBMMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK
    BggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMBcGA1UdEQQQMA6CBm5pa2l0YYcEwYf8
    LTANBgkqhkiG9w0BAQsFAAOCAgEAMSmrOpmoSGBs7fbK61LkxhItoT+HFrAxfJ+h
    ASQXwd7biPMVLFK8lBI1r36+hondNAzRQp4mVe6m2VwdcAdhkffAy+rjsMWHxKrf
    LVqqczP5Xh9CLS56Ztzwl8gvVO02KilVi1MDO7YrOqIntSjp1UxIaHU7iCiOl8+J
    6gQVfw4dNXNJajpSieqEp93fV9mYks521RKVUoNMbnD+sMF9FmLWJf7jQBTMIvnR
    eL9wPIwykDatVNc2VsxTVSGyms/d5WDeWmTQgA96jxqWiQXzYwpGpwhnpxrG5cTu
    nIBJHAc4OvsliNtAStNQocJbaQEyO2ZWnWOdOzuy8T2s83gLSMGMtCcLADjAiLLa
    w82Vx+6/97IdvVEj6PS3evvVsqK8KZHzyTNgTE/ox/jwx34UTNmRH5YPf/rYQgbZ
    A+HCz4/LKwidrs9WlTmm/dFxuFd2YjTmsH3GU2J5cS24JzqPjJTzKwdb68xAC4/E
    QcvpKGGzazm6J2JxRd4DsI6LUnCruA8AOGdM2Nrw6d+Ck9b0YcbAgWdcUVXpkB8D
    4m91c1XK1kLT90DCuK2Cgtj+ZRpIPS+ApWJ4UGvt+d+fESj0ZakwAsB6NFkcx9GF
    6yo8EEpdbsaLNe7en37r9NBgcsPz5YK/5by7ErQwMukux2cPoodPiX7YuWZ8S7bv
    BhY6PvI=
    -----END CERTIFICATE-----
  certificate_fingerprint: 9e2b96e3320ad9c2de13cf0984508bac21df73f247cd66c4bb3c4f3be11fa96a
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-11-generic
  server: lxd
  server_pid: 30355
  server_version: "2.18"
  storage: btrfs
  storage_version: "4.12"

   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

Receiving side (selma):
root@selma:/var/lib/lxd# lxc info
config:
  core.https_address: '[::]:6443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 193.247.121.52:6443
  - 193.247.239.116:6443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFQzCCAyugAwIBAgIQLaLrQGe0+7HBaJy/5tDmrzANBgkqhkiG9w0BAQsFADAz
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRMwEQYDVQQDDApyb290QHNl
    bG1hMB4XDTE3MDkwNjEyNDM1MloXDTI3MDkwNDEyNDM1MlowMzEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBzZWxtYTCCAiIwDQYJ
    KoZIhvcNAQEBBQADggIPADCCAgoCggIBALje49SGtlARVI+08VXv9BVGnHGe5TON
    ODTGKAUF4ayqcFOhlhRxWLiMaFlAWfNUvvy2srl0cBUMJPNtrPxCPcmlkVILYEcD
    CDAzRMYPKbWr3cIOpT4IvNUTiR5YFmtJEE9piDhm5nSKc0F8jwi7sO4PQ6uunG17
    KikerjCJXUz9NJQyk5fNvyqqgyIE/dDnK64SfhaWZYj+tUqDlqSjlI92QZfZUgzZ
    Irh2hUJRpfUhqTpEP8g/miEe2IQYWfpqjKmXBVJTfzCgLy3ou9W51Nv0YMxhqL+I
    NGuQc3PnO3f/oFEswdgmzfMzG2Fzb10ZDoPPbNswv0MoJCo8KYdpbwIIPszmbjwO
    /PShtH1RMegnhBUfUWmegpSx6XHkY3sDW/aJNHiQxsYqA5byBCcjLtRdx5dbm1vX
    7TxVQszr4on2QDhw7+TsUb/v0YY6Thocvo/2ji7XGKHJnlKn1B25mtFxGypfHEtM
    S/6etWrJ96b5zJ6gIgPqxac7pjQTaKRbysq1WseL4Z1up7T1DoTl4cBoYSJXziH+
    uHFf6kiSKBPKseFGo/mtbTwIz6qlxy30o7drSRPkenFQCDWKpjUU/Wf+7vF0QJv8
    pek8VD3kglpDxEgq6/EP4ITjAnWFeOzoK4rvSfi1xgMOvxMb3y6bikO8ABUfCrSz
    FS7aRsq3qR3vAgMBAAGjUzBRMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMBwGA1UdEQQVMBOCBXNlbG1hhwTB93k0hwTB
    9+90MA0GCSqGSIb3DQEBCwUAA4ICAQA3pe6uCKW76VdtD7bbJkG87XQs/gy6tQrI
    PWYj3kOmz7JLWwWea1ETyf9RV/TnFn+xFu8r6mZqAUSkn7P+qN+6LzgDk8i2L0fw
    26O7NSGxxtD9923+I/mzz9mXhbc7tsFzp2AzjQfsWFu6FGdrtRbEbpEQE2/sV45d
    RvRtfFvNfEV3LOWk5wvpmYYZJldNEX5fmCxtBfoHPOEwt96Ju7tMlpr8Qc+OLl02
    C87Y+ZLtYU2hT/th6GJDntlU5A9zEFUoll1kzV3M8gzMjb63mPc6AzW6hrFSzwcB
    jlXobbzXt69g9nJJYZGGYf4vFBx4nBDkLNmJOMVhInXlqeJBVJdSpBXqnaHhjWAF
    uyi+zHVmAdfvHpq+1WUEvwCFDQJbEV6wgDy5J0doTA/KMkK0p54isg810oD9Mdkv
    HJcdz9wQNypRiRJ4kiJ05efG3TkbACoKwtBg8UV9ETp3P5++lE57IfOVw/AIM8Yq
    vvjppf6aYmXg6P5kJEEbQu+c4GeNqIiyXTQNCG5fQJyRmuhjSkFQhA8CaRPsBG00
    g21C0lR6cFFq1imVrYR9OfUTP60heIHtyq3H6Zc35qpHmpiYUgcGYkT2fdpEKwq3
    HojFjaWzzmO+p2gzbCZjfGNC5hZbPfLiuj5ZfNVsgFNMXRFlOHAvJeJVGBOleBFQ
    Pg9rtsBEUg==
    -----END CERTIFICATE-----
  certificate_fingerprint: ecfa5b07d75ac80555b6db72e8f32e7d4ad45ef4016dc470d778d4388859d99d
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-11-generic
  server: lxd
  server_pid: 8552
  server_version: "2.18"
  storage: btrfs
  storage_version: "4.12"

# Issue description
lxc copy to remote btrfs storage fails on container with snapshots
lxc copy works OK if the container has no snapshots or if --container-only option is used

# Steps to reproduce

 1. Step one
nikita: lxc init images:26bd068866af alptest
 2. Step two
nikita:# lxc snapshot alptest
 3. Step three
nikita:# lxc copy local:alptest selma_ip:alptest --force-local --mode push --verbose --stateless 
error: Failed container migration:
 - https://193.247.239.116:6443: exit status 1
 - https://193.247.121.52:6443: websocket: bad handshake

# Information to attach
Sending side syslog (nikita):
Sep 25 14:05:25 nikita lxd[30355]: lvl=eror msg="Problem with btrfs send: ERROR: unable to resolve -p\n." t=2017-09-25T14:05:25+0200

Receiving side syslog (selma):
Sep 25 14:05:23 selma lxd[8552]: lvl=warn msg="Unable to update backup.yaml at this time." name=alptest t=2017-09-25T14:05:23+0200
Sep 25 14:05:23 selma lxd[8552]: lvl=warn msg="Unable to update backup.yaml at this time." name=alptest t=2017-09-25T14:05:23+0200
Sep 25 14:05:26 selma lxd[8552]: err="exit status 1" lvl=eror msg="Error during migration sink" t=2017-09-25T14:05:26+0200
Sep 25 14:05:26 selma lxd[8552]: err="Failed to run: btrfs subvolume delete /var/lib/lxd/storage-pools/mybpool1/snapshots/alptest/snap0: ERROR: cannot access subvolume /var/lib/lxd/storage-pools/mybpool1/snapshots/alptest/snap0: No such file or directory" lvl=warn msg="Failed to delete snapshot" name=alptest/snap0 t=2017-09-25T14:05:26+0200
Sep 25 14:05:26 selma lxd[8552]: container=alptest err="Failed to run: btrfs subvolume delete /var/lib/lxd/storage-pools/mybpool1/snapshots/alptest/snap0: ERROR: cannot access subvolume /var/lib/lxd/storage-pools/mybpool1/snapshots/alptest/snap0: No such file or directory" lvl=eror msg="containerDeleteSnapshots: Failed to delete a snapshotcontainer" snapshot=alptest/snap0 t=2017-09-25T14:05:26+0200
Sep 25 14:05:26 selma lxd[8552]: err="remove /var/lib/lxd/storage-pools/mybpool1/snapshots/alptest/alptest868448877/snap0/templates/hosts.tpl: read-only file system" lvl=eror msg="Failed deleting container storage" name=alptest t=2017-09-25T14:05:26+0200
Sep 25 14:05:26 selma lxd[8552]: lvl=eror msg="Failed to delete pre-created BTRFS subvolume: /var/lib/lxd/storage-pools/mybpool1/containers/alptest407079144." t=2017-09-25T14:05:26+0200

(receiving side after the failed copy attempt)
root@selma:/var/lib/lxd/storage-pools/mybpool1# btrfs subvolume list .
ID 257 gen 107 top level 5 path containers
ID 258 gen 107 top level 5 path snapshots
ID 259 gen 13 top level 5 path images
ID 260 gen 10 top level 5 path custom
ID 262 gen 13 top level 259 path images/ed435579a1d13aa7610e4796d1db922fc7f1df402b8b30b4ea0577c091fe6786
ID 287 gen 105 top level 258 path snapshots/alptest/snap0

# my comment
Issue with btrfs subvolume delete command itself?

**Comment by brauner** [comment]
This is not a regression in LXD this is a regression in the btrfs tools. I'll see what I can do. Not the first time that I had to fix the tools upstream.
