### ISSUE TITLE
LXC_image_issue

### ISSUE THREAD

**Issue by Giuscar** [lxc/lxd#3849]
Good morning,

I have a problem when I try to create my LXC image, using the command "lxc image import image.tar.gz --alias myAlias"

This is the error I get: "error: Unable to unpack image, run out of disk space."

Is it possible that I have to create an LXD container enough big to contain the image? If it works in this way, could you tell the procedure to follow, please?

Thank you.

Giuseppe.

**Comment by stgraber** [comment]
What storage backend are you using?

**Comment by stgraber** [comment]
and what LXD version?

We have a Github template for our issues that ask for that kind of information so that we don't need to then ask all those questions again, you may want to fill it next time around :)

**Comment by Giuscar** [comment]
Good morning stgraber,

yes, you are right sorry.
By the way I have been able to create my image. 
I just installed everything from scratch. 

I have a new error now.
I will create a new issue to explain that. 
Sorry again.

Giuseppe.

**Comment by stgraber** [comment]
Ok, good to hear that you have things working again.

This error is most common with LVM or Ceph storage backends where if an unpacked image is larger than the volume.size property of the pool, it will fail to import. Bumping the volume size to something large enough for your image will solve that.

A less likely source of the error is if your root filesystem is full enough that there isn't enough room to put the compressed image (tarballs) into /var/lib/lxd/images. LXD must keep the original image files in there to make it possible to convert to new storage format as you setup new storage pools and to allow you to export the image as a tarball again.

**Comment by Giuscar** [comment]
I got the first issue. 
When I re-configured my LXD I set a bigger pool dimension and everything worked. 

Thank you.
Giuseppe.
