### ISSUE TITLE
Could not connect to display

### ISSUE THREAD

**Issue by Giuscar** [lxc/lxd#3855]
Good morning,

I hope not to be out of topic.

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-35-generic
   * LXC version: 2.17
   * LXD version: 2.17
   * Storage backend in use: ZFS

# Issue description

I want to launch a program from my container. 
Error: Could not connect to display

I suppose that there is a way to connect with a display, because at the moment my container is only
characterized by a cmd. 

I think that the issue is: how can I run GUI Apps in a LXC container?
# Steps to reproduce

 1. root@client:./progrName
 

Thank you.
Giuseppe.

**Comment by simos** [comment]
There are two common ways to run GUI programs in an LXD container and get the output on your desktop.

1. Using X11 forwarding
Set up SSH in the container and connect from your desktop to the container using the command

> ssh -X ubuntu@containerIP

The -X means that if you run a GUI program in the ssh session, the output will appear on your desktop's session.
As an example application, install in the container the package `x11-apps`, then run `xclock` in the SSH session and you get the clock window on your desktop session.
The output is not hardware-accelerated. To get, for example, `firefox`, just install and run in the same way.


2. Follow the tutorial at https://blog.simos.info/how-to-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop/
It describes how to setup the container to get access to the local X11 GUI session. Support GPU acceleration, also audio.

**Comment by stgraber** [comment]
Right, LXD doesn't itself do any kind of X11 passthrough setup. If you want access to the X server, you need to set it up either through SSH or by directly passing the X socket. @simos post will get you covered for that.

**Comment by Giuscar** [comment]
Ok thanks to both.
I will follow this guide.
