### ISSUE TITLE
issue when snapshoting a container

### ISSUE THREAD

**Issue by zoum9** [lxc/lxd#3859]
Hello

I use lxc 2.0.8 on ubuntu.
In order to backup a container, i want to  : 
- snapshot it
- publish it and finally export it.

I met a trouble in snapshot step : 
due to rsync issue ( vanish files), snapshot never ends. It always output errors with vanished files.
In unix, vanished files is not blocking for rsync. 
How can i workaround this issue in order to make snapshot step OK ?

Best regards

**Comment by stgraber** [comment]
Hmm, so you're using LXD but with the "dir" backend then?

First can you make sure you're running an up to date LXD (2.0.10 is what you should be getting on up to date 16.04 LTS), then try to reproduce the issue again. If it still happens, then please provide the content of /var/log/lxd/lxd.log.

**Comment by stgraber** [comment]
Note that snapshots on the directory backend are always going to be unreliable as they're not atomic and so will be inherently inconsistent. But this shouldn't cause hangs. Rsync warnings should be ignored and rsync errors should cause LXD errors. A hang is somewhat surprising and hopefully something which got fixed in more recent bugfix releases.

**Comment by zoum9** [comment]
I try with lxd 2.0.10 on ubtunu 16.04 with same issues : 
lxc snapshot xxxxxxxxxxxx
error: rsync failed: file has vanished: "/var/lib/lxd/containers/************************
file has vanished: "/var/lib/lxd/containers/************************
rsync warning: some files vanished before they could be transferred 

As you said, rsync shouldn't issue due to vanished files. In my case, Rsync output error.
[lxd.log](https://github.com/lxc/lxd/files/1339888/lxd.log)

**Comment by stgraber** [comment]
@zoum9 did that hang or just fail?

If hang, can you look at whether you still have some rsync processes running?

**Comment by zoum9** [comment]
It  's just failed, so no snapshot.
I want Snapshot end, even if it s not reliable.
According to me, Snapshot musn't ouput errors (warning)  and end, even with vanished files

**Comment by zoum9** [comment]
Did you publish an lxd update for this ?
Indeed, i don't see update despite your modifications .

Best regards

**Comment by brauner** [comment]
@zoum9, this commit is in master but not in `2.18`. It will be available in `2.19` though.

**Comment by zoum9** [comment]
Ok , thanks.
On my ubuntu server ( ubuntu 16, xenial, the last release avalaible is 2.0.10)
If i want to test this new release, i must download source code wich is master ?

**Comment by brauner** [comment]
@zoum9, `2.19` was releases yesterday it should be available in the backports soon I guess or through the PPA.

**Comment by zoum9** [comment]
Ok, so to test it, i have to upgrade my os in order to download 2.19 wich is not yet ready, isn't it ?

**Comment by brauner** [comment]
You don't have to upgrade your whole OS, you can just update to `2.19` if that is possible for you. `2.19` is ready and released but it takes some time for the package to be published in the archive.

**Comment by stgraber** [comment]
The snap is going to update to 2.19 today, but I'm not sure that moving from the deb to the snap is necessarily worth it just for this one fix :)
