### ISSUE TITLE
[feature-request] remember the image details inside the container meta somewhere

### ISSUE THREAD

**Issue by zerkms** [lxc/lxd#3865]
At the moment container only remembers the image id it was created from.

Given that lxd periodically downloads the new versions of the images and prunes the old versions, after some time there is no chance to know what image was used to create a container.

What if the whole `lxc image info` structure is saved into the container's metadata?

If this idea is accepted I think I can contribute it.

**Comment by stgraber** [comment]
We do that already.

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc config show xenial | grep image
  image.architecture: amd64
  image.description: Ubuntu xenial amd64 (20170927_03:49)
  image.os: Ubuntu
  image.release: xenial
  image.serial: "20170927_03:49"
  volatile.base_image: 0f7e54b5b8493597ac000512dedabcc2f8e2fe47cc0e74aa789c51799ad90302
```

**Comment by zerkms** [comment]
What lxd version is that? Not in `2.0.10`.

**Comment by stgraber** [comment]
That's correct. LXD 2.0.x only gets security and bugfix updates. New features go in LXD 2.x releases. This particular one made it in LXD 2.6.
