### ISSUE TITLE
Connecting LXD container to Internet

### ISSUE THREAD

**Issue by Giuscar** [lxc/lxd#3871]
Good morning,

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-35-generic
   * LXC version: 2.17
   * LXD version: 2.17
   * Storage backend in use: ZFS

# Issue description
I set my topology to connect my lxd container to the internet.
I have created a bridge connected to my host interface.
Every time I reboot my LXD container the topology I have set is removed.
I think that every modification I make is removed.

How can this problem be solved?

 
Thank you.
Giuseppe.

**Comment by stgraber** [comment]
What exactly is your setup? What did you do through "lxc network", what did you do by hand?

**Comment by stgraber** [comment]
Bridging to the physical network is usually best handled at the distro level, at least when your host itself is also connected to that same network.

In Ubuntu, that'd mean configuring a bridge in /etc/network/interfaces, have that bridge include your physical NIC and have that configured for DHCP auto-config or static IP.

After you confirm that your host itself is fully functional after reboot, you can change the LXD default profile to use that bridge, something like this:

 - lxc profile device remove default eth0
 - lxc profile device add default eth0 nic nictype=bridged parent=br0 name=eth0

The commands above assume you're calling your bridge "br0" in /etc/network/interfaces.

**Comment by stgraber** [comment]
An even easier alternative to this would be using macvlan as it won't require any bridging at all, but it does come with the annoying caveat that the host will not be able to communicate with the containers.

If that's not a problem for you, then, you can just do:

 - lxc profile device remove default eth0
 - lxc profile device add default eth0 nic nictype=macvlan parent=ens3 name=eth0

The commands above assume your host network interface is called "ens3".
