### ISSUE TITLE
Support for ZVOL as storage driver

### ISSUE THREAD

**Issue by kattunga** [lxc/lxd#3873]
At this momment LXD support ZFS as storage driver but only as ZFS filesystem.
It would be great to has support for ZVOL (zfs volumes) as storage driver working as LVM or CEPH.
This let us, for example, to use XFS filesystem for a MongoDB container (XFS is a requirement for MongoDB) and get the beneficts of ZVOL's (snapshots, send/receive).

Regards

**Comment by loxK** [comment]
Standard linux quotas support is also needed to be able to run things like Plesk, ISPmanager, ISPconfig and so on. It cannot be enabled on datasets but could be on zvol

**Comment by stgraber** [comment]
So we've made some progress on this thanks to the VM support.
We have logic to create, snapshot, ... zvols on zfs. However this is currently only available for VM storage and there are no option to have containers use it as a backend with a filesystem setup on top.

This should be far easier to implement now than before though, albeit still not trivial.

**Comment by arren-ru** [comment]
There is also good point to use ZVOL inside an LXC container, it is nested containerization with containerd/rkit for docker or even for K8S.
As a workaround it is possible to use LVM on top of ZVOL created manually on the host, but for dynamic control it is really needed to implement ZVOL support for volumes.

**Comment by knutov** [comment]
What is the current state of this feature? Will support of zvol ever be added?

I suppose it will be possible to use user-level quotas inside lxd container with ext4 on zvol and a lot of users really want this feature.

**Comment by afrojewelz** [comment]
still staring at it , still not see any implementation or is it have some preview? now with k8s shift to containerd as main supported crio, but zfs still not perfectly supported for containerd , is that really necessary might i have to shift my host rootfs from zfs to ext4 or what?

**Comment by stgraber** [comment]
We now have an option on the zfs driver to store volumes on zvols.

**Comment by stgraber** [comment]
@monstermunchkin

**Comment by tomponline** [comment]
@kattunga as this issue is closed, I would hate for your post to get lost/forgotten about, would you mind opening a new issue here https://github.com/lxc/lxd/issues ?

Thanks

**Comment by tomponline** [comment]
> I understand that “existing instances using datasets will not be converted to zvols” when they are copied or moved between zfs storages, but why zfs.block_mode = true can’t be honored when storages use different drivers?

You're right, we should find a way to detect this and apply the ZFS storage pool defaults to new volumes not coming from a ZFS pool.

**Comment by kattunga** [comment]
> @kattunga as this issue is closed, I would hate for your post to get lost/forgotten about, would you mind opening a new issue here https://github.com/lxc/lxd/issues ?
> 
> Thanks

done, thank you.
