### ISSUE TITLE
man lxc, does not mention the CLI options of "lxc list"

### ISSUE THREAD

**Issue by akarelas** [lxc/lxd#3875]
This is on version 2.17. The documentation is lacking. It doesn't mention the CLI options that "lxc list" can take. So I cannot program my autocompletion functions.

**Comment by stgraber** [comment]
```man lxc.list```

**Comment by stgraber** [comment]
Or "lxc list --help". The manpages are auto-generated using help2man as that's the only reasonable way we can have them be up to date. Given the crazy amount of sub-commands we have, having everything show up in "man lxc" would be completely unreadable, which is why we have one man page per action.
