### ISSUE TITLE
Consider Prometheus integration

### ISSUE THREAD

**Issue by shanemhansen** [lxc/lxd#3876]
# Export metrics in prometheus-compatible format

It would be great to have prometheus (https://prometheus.io) metrics exposed in lxd. It currently seems to be the most popular out there, but it's line based format for holding metric names + tags seems like a fairly future-proof choice.

I understand if lxd doesn't want to integrate with a particular piece of software, but if you're going to support monitoring, why not support a popular tool?

If there's interest, I'm happy to submit a PR.

**Comment by shanemhansen** [comment]
For clarification I mean existing metrics from `lxc info $name`

**Comment by stgraber** [comment]
This isn't something LXD can do. The metrics you see in "lxc info" are retrieved from the kernel at the time you make the API call. Those kernel calls are very expensive so doing that on a timer basis would be a very bad idea.

In most cases, what you want is to run something like telegraf inside the container, pushing to your prometheus. It's still not cheap as far as kernel resource consumption, but is already significantly better than asking LXD to attach/detach to containers constantly.

**Comment by brauner** [comment]
This seems out of scope for us and @stgraber has provided a nice alternative. Closing for now. :)
