### ISSUE TITLE
lxc storage delete <name> fails while storage pool is not in used

### ISSUE THREAD

**Issue by mjrider** [lxc/lxd#3877]
# Required information

 * Distribution: ubuntu
 * Distribution version: trusty ( travis build environment )
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4
   * LXC version: 2.18
   * LXD version: 2.18
   * Storage backend in use: DIR

# Issue description
lxc storage delete fails with 
`error: remove /var/lib/lxd/storage-pools/foobar: device or resource busy`

# Steps to reproduce
I cannot get it to reproduce everywhere, but basicly:
1. lxc storage create foobar dir source=/tmp/foobar
2. lxc storage delete foobar

# Information to attach
https://travis-ci.org/mjrider/terraform-provider-lxd/builds/281903307 has a .travis build showing the problem. I've not been able to reproduce this on a local system.
 - [x] main daemon log (`cat /var/log/lxd/lxd.log`)
relevant part of the log is with the debug output, see travis build for full log
 - [X] output of the client with --debug
``` 
DBUG[10-01|12:42:54] Sending request to LXD                   etag= method=DELETE url=http://unix.socket/1.0/storage-pools/foobar
DBUG[10-01|12:42:54] 
	{
		"error": "remove /var/lib/lxd/storage-pools/foobar: device or resource busy",
		"error_code": 500,
		"type": "error"
	} 
```

 - [X] output of the daemon with --debug
```
INFO[10-01|12:51:59] Deleting DIR storage pool "foobar". 
DBUG[10-01|12:51:59] Unmounting DIR storage pool "foobar". 
DBUG[10-01|12:51:59] Unmounted DIR pool "foobar". 
DBUG[10-01|12:51:59] 
	{
		"error": "remove /var/lib/lxd/storage-pools/foobar: device or resource busy",
		"error_code": 500,
		"type": "error"
	} 
```

**Comment by mjrider** [comment]
a better and cleaner reproduction travis config 
https://github.com/mjrider/lxd-setup-test

**Comment by jtopjian** [comment]
@mjrider has been really helpful in debugging this issue. The `lxd-setup-test` he linked to above succinctly reproduces this problem. In a nutshell, there's a bug with the dir storage backend on Ubuntu 14.04:

```shell
$ lxc storage create foobar dir source=/tmp/foobar
$ lxc storage delete foobar
error: remove /var/lib/lxd/storage-pools/foobar: device or resource busy
```

I'm pretty sure this began happening in https://github.com/lxc/lxd/commit/ac851c1f37263ea4497edf028a23747b7879485e which is around the time we started seeing Travis errors in the terraform-provider-lxd repo. Additionally, this problem only happens when the source directory is outside of the lxd root, which creates a bind mount.

If you run `umount /tmp/foobar` and then re-run the `lxc storage delete` command, the command succeeds.

From what I can see, `shared.IsMountPoint` is failing to detect that `/var/lib/lxd/storage-pools/foobar` is a mounted directory. `mountpoint` is failing to report it as such. But , `umount` obviously sees it.

**Comment by stgraber** [comment]
Hmm, looks like "mountpoint" is pretty broken in 14.04 indeed... It doesn't seem to recognize bind-mounts at all...

Not too sure what we can do about it though and it's not the only place that we call shared.IsMountPoint from...

**Comment by stgraber** [comment]
@brauner can you take a look at exactly what the current "mountpoint" command does in util-linux and re-implement this in our IsMountPoint() function so we can drop the dependency on the external binary and fix this?

**Comment by mjrider** [comment]
@stgraber i also made an script for running with snap instead of the ppa, and then it works.
So i'm a bit confused
ppa: https://github.com/mjrider/lxd-setup-test/blob/master/.travis.yml
snap: https://github.com/mjrider/lxd-setup-test/blob/snap/.travis.yml

it looks to me that there is something wrong with the ppa then, so maybe this is the wrong forum for this issue. An previously it worked with the ppa also. i found the old build output, and it was version 2.17 which worked correctly

**Comment by jtopjian** [comment]
On Ubuntu 16.04, `util-linux` version 2.27.1 is installed, which doesn't exhibit this problem.

On Ubuntu 14.04, version 2.20.1 is installed.

That narrows it down to... just a few commits :)

https://github.com/karelzak/util-linux/compare/stable/v2.27...stable/v2.20

This might be a hack, but would it be useful to parse `/proc/self/mountinfo` if `mountpoint` returns "false"?

```shell
$ lxc storage create foobar dir source=/tmp/foobar
$ cat /proc/self/mountpoint
...
44 22 8:1 /tmp/foobar /var/lib/lxd/storage-pools/foobar rw,relatime - ext4 /dev/sda1 rw,data=ordered
$ lxc storage delete foobar
error: remove /var/lib/lxd/storage-pools/foobar: device or resource busy
$ cat /proc/self/mountpoint
...
44 22 8:1 /tmp/foobar//deleted /var/lib/lxd/storage-pools/foobar rw,relatime - ext4 /dev/sda1 rw,data=ordered
```

It looks to me like `mountpoint` is [parsing](https://github.com/karelzak/util-linux/blob/stable/v2.20/sys-utils/mountpoint.c#L45) `/proc/self/mountinfo` anyway... my guess is that the parsing of that file is being done incorrectly in v2.20.

If that's too much of a hack, then mimicking `mountpoint` in LXD most likely is the best way to go, though I would not want to be that person :)

**Comment by stgraber** [comment]
@jtopjian that's expected given the way the snap works. The snap is layered on top of Ubuntu 16.04, regardless of what your system's distribution and version is. So installing the LXD snap on Ubuntu 14.04 will get you the 16.04 version of mountpoint whenever LXD calls it.

**Comment by stgraber** [comment]
@jtopjian I'm frankly not super fond of LXD constantly forking a "mountpoint" subprocess when we already have a bunch of functions that do clever parsing of mountinfo. So it feels like the right solution here is going to be to get IsMountPoint to always be a fully Go function without any subprocess calls. Right now it does have a pure-Go fallback logic but it's incomplete, so we need to get it to parity with mountpoint's logic.

**Comment by jtopjian** [comment]
@stgraber I recall reading something that the snap will become the recommended way of installing LXD in the future -- is that correct? If so, we might consider switching to it to run our tests.

Regarding forking, I agree, especially if there's already partial support for detecting mountpoints natively in LXD.

**Comment by brauner** [comment]
@stgraber, well without looking at the specific code for `mountpoint` I can tell you right away that they definitely must parse `/proc/<pid>/mountinfo`. There's just no other way to detect a bind-mount mountpoint. There's code for that in liblxc which I might just move over/reimplement here.

**Comment by brauner** [comment]
> @stgraber, well without looking at the specific code for `mountpoint` I can tell you right away that they definitely must parse `/proc/<pid>/mountinfo`. There's just no other way to detect a bind-mount mountpoint. 

I should clarify: `s/detect a bind-mount/reliably detect a bind-mount/`

**Comment by jtopjian** [comment]
You folks are the best.
