### ISSUE TITLE
Potential Vulnerability

### ISSUE THREAD

**Issue by thewyzard44** [lxc/lxd#3879]
LXD version 2.17

I just caught something tonight that you may want to take a look at...

On the REST API, calling execute with hyperkit (in ruby):
```ruby
            retval = hk.execute_command(container_name, command, wait_for_websocket: true, interactive: false, sync: false)
```
I'm in the midst of replacing my underlying websockets implementation...  the original vendor did it right, I'm just dropping down one more layer and figuring out how to improve/implement it at a more 'raw' level because they did a couple of things that I don't like.

Well, in that process, I 'think' I opened up connections to the websocket endpoints, and I'm not getting any apparent errors.  However, I've yet to get the connections to 'upgrade' to websockets...  that's where I'm at now, but I'm tired, so tomorrow...

Symptom: I connect and nothing happens - hk.wait_for_operation (maps directly to your `/1.0/operations/<uuid>/wait`) hangs forever - the command doesn't execute - same experience developing my original implementation where I connect fds in this order: 1 then 2 and LXD continued to hang until I connected FD 0 and THEN the command runs (makes sense with 'wait_for_websocket') although I have no stdin to give so I attempted to avoid that connection.  I never connected 'control'.

So that's the background and here's the gotcha:

I have ` hk.wait_for_operation` in a 'retry_forever' loop.  Anytime there's a timeout on the underlying socket I just resubmit.  Long running processes are expected - sometimes with no output.
```ruby
          LXD.with_timeout_and_retries({ timeout: 0 }.merge(options)) do
            begin
              pp 'blocking', command
              retval = hk.wait_for_operation opid
              pp 'unblocked'
              backchannel.exit if backchannel.respond_to? :exit
              return LXDExecuteResult.new command, options, retval[:metadata][:return].to_i
            rescue Faraday::TimeoutError => e
              raise Timeout::Retry.new e # rubocop:disable Style/RaiseArgs
            end
          end
```
evidenced by hitting CTRL-C on my rake task and getting my bash prompt back...  every couple of minutes that `pp 'blocking', command` will still output to my terminal.  The loop works (too well).  I have to still actually kill the ruby task, but if i don't, it just keeps on chugging.

Which leads back to my point that the operation ID is still valid on LXD otherwise it would throw a different exception and escape that loop.  Meanwhile, I have another thread connected to the 3 websockets, in the non-upgraded state, without any errors that I can tell 'yet'.

I wonder how long LXD would sit there in that state wasting resources, and waiting?  Before I got a grip on what was going on, and thought to run ps or top...  by the time that I did there was at least 10 ruby processes in the above state just sitting there happily waiting on sockets.

Potential resource exhaustion issue, here
It is likely that that the websockets timeout eventually and are no longer connected - I don't have them in a retry loop or with good error output.  

That assumption leads me to think you may have a bug with 'execute' and 'wait_for_websocket' on the REST API and that you're waiting too long

original working implementation:
https://github.com/NexusSW/lxd-common/blob/master/lib/nexussw/lxd/transport/rest.rb#L17-L50

new dev: (WIP - exposer of the error)
https://github.com/NexusSW/lxd-common/blob/lxd-execute-bug/lib/nexussw/lxd/transport/rest.rb#L18-L39

I've branched this at this point for your reference, but I'm going to push forward tomorrow on my dev branch

basic reproduction:
`vagrant up; vagrant ssh -c 'cd /vagrant; rake spec'`

If you don't know ruby or have vagrant then we can get into it more tomorrow.  And I'm happy to provide whatever debug output that you need.

**Comment by stgraber** [comment]
As you mentioned, so long as wait_for_websocket is set to true, LXD will wait for all websockets to be connected before it spawns the command. There is no timeout on those operations, so if you create one and don't connect and don't cancel it, then it will stick around until the LXD daemon is restarted next.

In your case, your individual connections have likely timed out and been disconnected at the websocket layer, but LXD won't know about that until the last websocket is connected and the code attempts to use the connections, at which point LXD would get an error and fail, destroying the operation in the process.

I'm not seeing anything problematic here. Only authenticated users can interact with the API. LXD did exactly what you asked it to do (as you set wait_for_websocket) and having a yet to be started operation is extremely cheap so having extra monitoring/timeout around it would likely be more expensive resource wise.

**Comment by thewyzard44** [comment]
aha! authenticated users...  I hadn't thought back that far because that's way up my object hierarchy.  my bad and my apologies.  I was just worried (in my tired mumbles) that someone could sneak in there in a public interface with that front-end api call and cause hangups on the backend.
