### ISSUE TITLE
LXD 2.18 Broken on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by tpouyer** [lxc/lxd#3883]
# Required information

 * Distribution: Ubuntu 16.04.3 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: GNU/Linux 4.4.0-92-generic x86_64
   * LXC version: 2.0.10
   * LXD version: 2.18-0ubuntu3~16.04.1
   * Storage backend in use: lvm

# Issue description

Cannot install lxd on ubuntu 16.04.3 LTS with following error:

The following packages have unmet dependencies:
 lxd : Depends: liblxc1 (>= 2.1.0~) but 2.0.8-0ubuntu1~16.04.2 is to be installed

# Steps to reproduce

 1. sudo apt-get install --yes --quiet --target-release=xenial-backports lxd

**Comment by stgraber** [comment]
Oh crap, fixing.

**Comment by stgraber** [comment]
Fix uploaded to the Ubuntu archive for 16.04 and 17.04, package is building now and should get published to the archive within the hour.

**Comment by stgraber** [comment]
Sorry about that, my text system happened to have the more recent liblxc so I didn't catch the issue...

**Comment by tpouyer** [comment]
thx!
