### ISSUE TITLE
lxd complains of "missing updates: 30 -> 32"

### ISSUE THREAD

**Issue by mew1033** [lxc/lxd#3890]
# Required information

 * Distribution: Ubuntu 16.04.03
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 2.18
   * LXD version: 2.18
   * Storage backend in use: ZFS, but I think it might be broken

# Issue description

lxd is failing to run, and lxc list just hangs

# Steps to reproduce

1. Run lxc list. It just hangs forever
2. Run lxd --debug, the following is output:

    INFO[10-03|22:48:48] LXD 2.18 is starting in normal mode      path=/var/lib/lxd
    WARN[10-03|22:48:48] CGroup memory swap accounting is disabled, swap limits will be ignored.
    INFO[10-03|22:48:48] Kernel uid/gid map:
    INFO[10-03|22:48:48]  - u 0 0 4294967295
    INFO[10-03|22:48:48]  - g 0 0 4294967295
    INFO[10-03|22:48:48] Configured LXD uid/gid map:
    INFO[10-03|22:48:48]  - u 0 100000 65536
    INFO[10-03|22:48:48]  - g 0 100000 65536
    error: missing updates: 30 -> 32

**Comment by stgraber** [comment]
sudo sqlite3 /var/lib/lxd/lxd.db 'INSERT INTO "schema" VALUES(8,31,1476916849);'

This should fix it. This is the second report of such a broken database. I really wonder what may be causing this...

Do you remember ever having to manually update your database to fix an issue, or ran into problems related to the storage pool feature a while back?

**Comment by mew1033** [comment]
That definitely fixed it.... Thanks!
I haven't done anything manual to the database at all. Is there anything I can do to help you diagnose the root issue?
