### ISSUE TITLE
Non-root cannot exec with snap package build 4375

### ISSUE THREAD

**Issue by bk** [lxc/lxd#3892]
We're using LXD on Debian stretch via the snap package system, following the stable channel (currently LXD version 2.18). After automatic upgrade to build 4375, non-root users in the lxd group can no longer run commands on the containers, getting the error

    chroot: cannot change root directory to '/var/lib/snapd/hostfs': Operation not permitted

Unsurprisingly, root does not get this error.

There have sometimes been problems in the past associated with snap package upgrades, but they have always been soluble by restarting the containers and/or the `snap.lxd.daemon` service. Not this time. We had to revert to the previous version: build 4279.

**Comment by stgraber** [comment]
Sorry about that, a fixed snap has been released to the stable channel a few hours ago with a fix for this.
