### ISSUE TITLE
How to export a container to a specific folder?

### ISSUE THREAD

**Issue by demsking** [lxc/lxd#3894]
# Required information

 * Distribution: KDE Neon
 * Distribution version: 5.10.95
 * The output of "lxc info" or if that fails:
    -   driver: lxc
    -   driver_version: 2.0.8
    -   kernel: Linux
    -   kernel_architecture: x86_64
    -   kernel_version: 4.10.0-35-generic
    -   server: lxd
    -   server_pid: 110246
    -   server_version: 2.0.10
    -   storage: dir
    -   storage_version: ""

# Issue description

My machine does not have enough space to run `lxc publish centos`. So I would like to specify the destination of the copy.

Is there any way to do that?

**Comment by stgraber** [comment]
Nope. "lxc publish" creates a new image in the LXD image store, which is always located at /var/lib/lxd/images/.

The image creation may also require additional disk space while generating the tarball of the container.

**Comment by demsking** [comment]
OK. So how to export an image directly to an external partition?

**Comment by stgraber** [comment]
Once the image is in the LXD image store, you can do "lxc image export FINGERPRINT ." from wherever you want and it'll write it to your current directory.

**Comment by demsking** [comment]
It's not works.
```sh
~$ lxc image export a2021cb0fc40 /media/demsking/Workspace/
error: multipart: Part Read: unexpected EOF
```

**Comment by stgraber** [comment]
Can you post the content of /var/log/lxd/lxd.log and the output of "dmesg" right after you get such a failure?
I suspect you're either running out of diskspace when LXD attempts to generate the multipart stream or running out of memory.

**Comment by demsking** [comment]
I just try again and it's works now!
I don't know what happened :/

**Comment by bensig** [comment]
@stgraber I attempted to point my images container to my zpool by pointing a sym link from `/var/lib/lxd/storage-pools/default/images` to `/var/lib/lxd/images` and I ran a publish normally... then cancelled it because it's filling up my root drive, but it has not cancelled and I cannot find the process with `top` or `ps -awx` - any ideas of the proper way to do this?
