### ISSUE TITLE
New LXD Snap failes to exec on Ubuntu 16.04

### ISSUE THREAD

**Issue by ted-gould** [lxc/lxd#3897]
* Distribution:
      * Ubuntu 16.04

 * Snap versions
    * Works: 2.18 (4279)
    * Doesn't: 2.18 (4375)

  * Snapd info
```
$ snap version
snap    2.27.6
snapd   2.27.6
series  16
ubuntu  16.04
kernel  4.10.0-35-generic
```

  * Error message
```
$ lxc exec foo ls
chroot: cannot change root directory to '/var/lib/snapd/hostfs': Operation not permitted
```

**Comment by stgraber** [comment]
4418 (released a few minutes after you opened this issue) should fix this particular problem, or rather workaround the odd chroot behavior.

**Comment by stgraber** [comment]
Would be nice if you could confirm that refreshing to 4418 does solve the problem for you.

**Comment by stgraber** [comment]
I finally managed to reproduce the issue and confirmed that the fix which has been pushed out a few hours ago does fix it.

**Comment by ted-gould** [comment]
4418 works for me.
