### ISSUE TITLE
Is it possible to nest LXD inside LXC running on Proxmox?

### ISSUE THREAD

**Issue by bodleytunes** [lxc/lxd#3900]
Hi All,

I know this seems a bit of a pointless exercise but I was wondering if it was possible to get an LXD container to start inside an LXC container that is actually running on a Proxmox VE host.  

I have tried firing up a 17.04 LXC container with LXD 2.18 but the container fails to start, and it looks like it could be some permissions problems.

I've tried enabling nesting and also making the container privileged.

As proxmox is quite customized, locked down and running on Debian Jessie, I'm thinking this may not be possible.

Cheers,

Jon

# Required information

 * Distribution: Proxmox 4.x Debian Jessie
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.4.79-1-pve
   * LXC version: 2.06
   * LXD version:  2.18
   * Storage backend in use:  DIR

config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.173.34.1:8443
  - '[fd42:7f97:a644:3e9e::1]:8443'
  - 10.55.88.26:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFTTCCAzWgAwIBAgIRAL6OX/RvDa2fRjxA/ODphNswDQYJKoZIhvcNAQELBQAw
    ODEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEYMBYGA1UEAwwPcm9vdEBh
    ZGFtc2tpdnBuMB4XDTE3MTAwNDE5MzU0N1oXDTI3MTAwMjE5MzU0N1owODEcMBoG
    A1UEChMTbGludXhjb250YWluZXJzLm9yZzEYMBYGA1UEAwwPcm9vdEBhZGFtc2tp
    dnBuMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA2fjUNm9ktq4s8S7L
    tD5Yw6kKWFB/s5vhYiOsq6YY4O1qKRy8uUyF3+TZ3cBX4arZWya/dJB/PuCgX/Yc
    wPbkzwdiz4OkFJzVBtZkDfcXBfy/i5Y3TZcVs1epmdKDx+5KH46jw3w4O0WIUQYd
    bEbYTkrKp3UCYrebAYaA25nA7tDc5kLAi3VtDaPrd+UKppeBQD0IrDUqyN9N3T3p
    Kss1pri0VUwlxVshCKIpz91IDxfxzliqpgQdqkesd9a++ChaQnAh98daTbxAiwhi
    4RXQFzWz4b8lUwsx1J/j9F/94i1PbGsESIy4QX5ZO0XNTSwuCEleBevrEcJQPd+8
    5nyBPrl/bw5fmIXxt66GPS2PymDPdmzIAqVY7pIRKG0eiOmCkoMsvIDGuGmc5Csa
    WBWy7OlrF6oLlVNH+tqqapqWvaqd9RVr6w5peec3CX99TqTTHOsahFgl8L0y3OsA
    2o7ZK/vZEjFwFMm5sSP2Djp315/ov40NwHuQCjO15VOI2JHuHIfVlvf6IYk1ehSM
    9VpcAEOr4JBqRsAf6zi/Wv4JWO6wKeUQj2jGgHZ0UD0AoEoWEsan7g3N/+OVFd0s
    FZl3k7gx1vbL2S4NkEkXHMRQc6zT5gNLGBpUB8OsmVb79m+yLkM+dGg3vY5pAdRH
    crjv0IE3eiiFj0MbYSaLfQTriMUCAwEAAaNSMFAwDgYDVR0PAQH/BAQDAgWgMBMG
    A1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwGwYDVR0RBBQwEoIKYWRh
    bXNraXZwbocECjdYGjANBgkqhkiG9w0BAQsFAAOCAgEA1myIUsEqiX9s88PfdSPA
    KSMxDVb5uTk4htaRDpJ8lB3OKTJEzsfjDanCT/dXIp6Qihlk9OORTp7Nk7XXVVXf
    U4uoC0lSsCJgXrINkQaiPyo5cA+4QVZYiWgv7+EXbQedwYxJCVtA8mTu6fB9qTp0
    bKLFJAdo8mpQqZtjFdiG6ixyCvLTnE98cuPv8nMMSMoyftI5+SlF5J/0U7HTgpSG
    HYJlSF+Kpfpt6VZM+IEl2ceQ28sTcOjl8eYOxpyeESwDK80+56x6HJQd5F8ncBJm
    dnno2y3C95wkV+AySagnpzBq0b0ywU7qhzSk2nAiuMdXEFonOBEP4JdUxDaUKpYr
    GrSp02FJZtQnes610I+0cMdVruC5iMGvlEjAIuYWVm9PWFmZbF6vOrBT+RasfUpE
    Kk8m0400Vt5+9NyXqXecsuRqKYKiBra338nk01ssCs+fWQR3E8yOOmtyZT/fVBzH
    vvBmLhqI0GekC29lI2eKCkSDr4VrlUbMCY/jLElBCqu0l7dVO24u0w/aqpolKq6I
    8M03U9gk2fsAY7HJwSlFnjK45N8w0fQ8HTFi8iJk70sWKJVaaUK44MH2HsmDMN4d
    gItpu6+u+J0oJAB010Fb8QVMgf5HzUxE96aGuzX/JXFY6X5m86ljUPSUoksonZf/
    ILK0OI+oLM7yzBinv8SIzvg=
    -----END CERTIFICATE-----
  certificate_fingerprint: 9413800d801187599ea43f3b154ffa244344e5fb2a83875bb35ab5bbc0805345
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.79-1-pve
  server: lxd
  server_pid: 318
  server_version: "2.18"
  storage: dir

# Issue description

Try to launch a container but it fails mounting the rootfs by the looks of it.

# Steps to reproduce

`error: Failed to run: /usr/bin/lxd forkstart test /var/lib/lxd/containers /var/log/lxd/test/lxc.conf: 
Try `lxc info --show-log test` for more info
root@adamskivpn:~# lxc info --show-log test
Name: test
Remote: unix://
Architecture: x86_64
Created: 2017/10/04 20:12 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20171004222255.670 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171004222255.672 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171004222255.379 ERROR    lxc_utils - utils.c:safe_mount:1739 - Operation not permitted - Failed to mount proc onto /usr/lib/x86_64-linux-gnu/lxc/proc
            lxc 20171004222255.379 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:712 - Operation not permitted - error mounting proc on /usr/lib/x86_64-linux-gnu/lxc/proc flags 14
            lxc 20171004222255.379 ERROR    lxc_conf - conf.c:lxc_setup:3176 - failed to setup the automatic mounts for 'test'
            lxc 20171004222255.379 ERROR    lxc_start - start.c:do_start:921 - Failed to setup container "test".
            lxc 20171004222255.380 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
            lxc 20171004222255.431 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:760 - Received container state "ABORTING" instead of "RUNNING"
            lxc 20171004222255.432 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171004222255.432 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171004222255.432 ERROR    lxc_start - start.c:__lxc_start:1451 - Failed to spawn container "test".
            lxc 20171004222255.432 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171004222255.432 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171004222255.510 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171004222255.510 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171004222255.510 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:125 - Command get_cgroup failed to receive response: Connection reset by peer.
`

**Comment by stgraber** [comment]
The error you're getting is because of the kernel overmounting protection code.

Basically, you need to have a view of a clean, not overmounted /proc in your container in order to be allowed to mount additional copies of it. It could also be that apparmor is getting in the way in this case, both would show up with similar symptoms.

I'm not particularly familiar with Proxmox, but in general what you'll need in order to have nesting work is:
 - A LSM (AppArmor) policy which allows it (lxc-container-default-with-nesting for example), if Proxmox is using AppArmor
 - A clean copy of the "proc" and "sysfs" filesystems mounted somewhere inside the container. LXD mounts those under /dev/.lxc/proc and /dev/.lxc/sys when nesting is enabled, but the exact location doesn't matter to the kernel.

Whether the container is privileged or not shouldn't really matter. LXD will detect that it's running inside an unprivileged container and make some configuration recommendation when you run "lxd init".

**Comment by bodleytunes** [comment]
Ok thanks, I'll have an other attempt at it :)

**Comment by stgraber** [comment]
Closing this as there's no LXD bug for us to fix as far as I can tell.
