### ISSUE TITLE
increasing the size of the default map

### ISSUE THREAD

**Issue by jduckett** [lxc/lxd#3901]
I tried following the content at the following link: https://stgraber.org/2017/06/15/custom-user-mappings-in-lxd-containers/

as per Increasing the size of the default map
cat /etc/subuid
lxd:100000:65536
root:100000:65536

cat /etc/subgid
lxd:100000:65536
root:100000:65536

I changed the following files to:
cat /etc/subuid
lxd:100000:1000000000
root:100000:1000000000

cat /etc/subgid
lxd:100000:1000000000
root:100000:1000000000

restart lxd and the changes took effect.  now, try changing the settings back to:
cat /etc/subuid
lxd:100000:65536
root:100000:65536

cat /etc/subgid
lxd:100000:65536
root:100000:65536

restart lxd and try to start and existing container or launch a new one and I get:

LXD doesn't have a uid/gid allocation. In this mode, only privileged containers are supported.

/var/log/lxd/lxd.log
lvl=warn msg="No available uid/gid map could be found" t=2017-10-04T21:02:25-0500
lvl=warn msg="Only privileged containers will be able to run" t=2017-10-04T21:02:25-0500

Seems I can't decrease the size of the default map.  Is there a way to reset lxd?

**Comment by stgraber** [comment]
Hmm, that should have worked fine. Existing containers would likely have refused to start at this point, but the daemon itself should have found its map just fine.

The error sounds like LXD failed to parse the subuid/subgid files. Is there anything odd in there?
The "cat" output above doesn't suggest that there is, but it could be hidden characters, missing final line break or something along those lines.

**Comment by jduckett** [comment]
Well, I did something I rarely have to do.  I rebooted the machine.  I have no idea why, but, things seem to be cool now.

I don't understand why and I'm not going to question it.  I think I'm just going to pretend I dreamed it happened.

strange.

**Comment by stgraber** [comment]
that is very strange indeed
