### ISSUE TITLE
remote_cache_expiry does not work, integration tests are constructed incorrectly

### ISSUE THREAD

**Issue by sanderbrandenburg** [lxc/lxd#3904]
I could not get images.remote_cache_expiry to function correctly. My cached images seem to build up and clog my root filesystem. I tried to debug it myself.

From what I'm seeing, I see last_use_date represented as unix time instead of rfc 3399:
```
sqlite3 /var/lib/lxd/lxd.db 'SELECT fingerprint, creation_date, expiry_date, upload_date, last_use_date FROM images WHERE cached=1'
2a6d95cc689465fbb0fe87c8bf873e096bec1390cb2cadac6dad21d7a0559fd0|0001-01-01 00:00:00+00:00|0001-01-01 00:00:00+00:00|1496996301|2017-06-09 14:49:03.205353548+00:00
16810b9bfa1519ff9a895238d8b8e7dc3b266273e7cba666fc59d0b8d11898b0|0001-01-01 00:00:00+00:00|0001-01-01 00:00:00+00:00|1497539778|2017-06-19 15:52:36.668131347+00:00
```

However, what's worse is that **the integration tests seem to be constructed incorrectly** to verify whether "lxc_remote config set images.remote_cache_expiry 0" expires cached images synchronously:
`  ! lxc_remote image list l2: | grep -q "${fpbrief}"`

Unfortunately, this does not trigger errexit and fail the test when grep -q returns a non-0 exit code, as demonstrated here:
```
# in the next line errexit is not triggered, although the exit code of the statement is non-0!
$ sh -e -c '! echo x | grep -q x; echo exit code: $?'; echo $?
exit code: 1
0
$ sh -e -c 'echo x | grep -q x; echo exit code: $?'; echo $? 
exit code: 0
0
```

This could be a relatively daft-looking workaround:
```
sh -e -c 'echo x | grep -q x && false; echo exit code: $?'; echo $?
1
```
**Unfortunately, this breaks the integration test for image.sh!**

And there are more candidates where this shell construct may be a problem:
```
sander@sander-thuis ~/go/src/github.com/lxc/lxd/test
 % egrep  -r '^\s+\!.*\|' .
./suites/basic.sh:      ! aa-status | grep -q ":${aa_namespace}:"
./suites/basic.sh:      ! aa-status | grep -q "lxd-lxd-apparmor-test_<${LXD_DIR}>"
./suites/basic.sh:  ! lxc image list | grep -q image1
./suites/basic.sh:  ! lxc image list | grep -q image2
./suites/basic.sh:  ! lxc image list | grep -q image3
./suites/basic.sh:  ! lxc list | grep -q foo
./suites/concurrent.sh:  ! lxc list | grep -q concurrent
./suites/config.sh:  ! lxc config show foo | grep -q "raw.lxc"
./suites/config.sh:  ! lxc config show foo | grep -v "volatile.eth0" | grep -q "eth0"
./suites/config.sh:    ! (lxc config template list c | grep -q my.tpl)
./suites/deps.sh:  ! ldd "$(which lxc)" | grep -q liblxc
./suites/idmap.sh:  ! echo "uid $((UID_BASE+1)) 1000" | lxc config set idmap raw.idmap - || false
./suites/idmap.sh:  ! echo "gid $((GID_BASE+1)) 1000" | lxc config set idmap raw.idmap - || false
```
(in the last two lines, the person writing the || false statement, knew this problem!)

**Comment by stgraber** [comment]
Got a commit that fixes the return value masking issue, now looking at the image expiry problem again (fixed 2-3 bugs related to it recently, guess it wasn't quite enough).
