### ISSUE TITLE
Getting Failed to get my hostname When trying to add remote

### ISSUE THREAD

**Issue by zacksiri** [lxc/lxd#3910]
Hey I'm trying to add a remote lxd instance and I'm getting this error

``` shell
2017/10/06 14:08:05 Failed to get my hostname
```

lxc info 

``` shell
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
  certificate_fingerprint: 
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.0-3-amd64
  server: lxd
  server_pid: 2003
  server_version: "2.18"
  storage: zfs
  storage_version: 0.6.5.9-5
```

I'm guessing it's something to do with my hostname config in the OS?

I read through the file that generates the certificate and it seems to be config of how the hostname is config or IP address is resolved?

**Comment by stgraber** [comment]
That doesn't look like a LXD log message, what exactly are you running that's giving you this error?

**Comment by zacksiri** [comment]
``` shell
lxc remote add myremote myremote.address.com
```

it seems to becoming from here https://github.com/lxc/lxd/blob/661965a4c60cd99997e95d23bf22a606b7d224c6/shared/cert.go#L125

**Comment by stgraber** [comment]
Can you download https://dl.stgraber.org/lxc-3910 (sha256: a2bf1307f7b84d34a2b27aa19a2b9dade385b8929f4c1f8ff0f6709dbf57776e)

And try what you did again using this binary client instead?

It should behave the same, but I've removed the use of the log package and instead now return the actual error which should help figure out what's going on on your system.

**Comment by zacksiri** [comment]
@stgraber this is completely odd, but your binary worked, it managed to get the certificate added

``` shell
root@zephyr:~# ./lxc-3910 remote add artellectual images.artellectual.com
Certificate fingerprint: 2b73554f343c57b752ffd9715b55f98efac20dae96963a1cdd370c114e697a29
ok (y/n)? y
Admin password for artellectual:
```

``` shell
root@zephyr:~# lxc remote add artellectual images.artellectual.com
Generating a client certificate. This may take a minute...
2017/10/06 14:37:01 Failed to get my hostname
```

**Comment by zacksiri** [comment]
would you like access to my server? send me your public key I will add you.

**Comment by stgraber** [comment]
Hmm, ok, so the main difference I can think of between my binary and what you have on your system is what Go version was used to build it... I built it with Go 1.8.3 whereas the LXD you have on your system was most likely built with Go 1.6.

**Comment by stgraber** [comment]
Where did you get that LXD from anyway? is that from our PPA?

**Comment by stgraber** [comment]
Oh, I think I'm getting confused with another bug report that was on Ubuntu 14.04 and would therefore be Go 1.6.

In your case you didn't actually mention what distribution you're using or how you installed/built LXD.

**Comment by stgraber** [comment]
And sure, I can poke around a bit and see what may be confusing the golang net code on your system.
SSH key can be found at: https://dl.stgraber.org/ssh.ecdsa

**Comment by zacksiri** [comment]
@stgraber I've added your key, try ssh into zephyr.artellectual.com as root I installed it using Debian 9 using snap

**Comment by stgraber** [comment]
ok, tracked down the problem in the snap wrapper for lxc, going to push a fix soon and test it.

**Comment by zacksiri** [comment]
@stgraber much thx! 👍  will wait for the fix.

**Comment by stgraber** [comment]
updated the snap packaging branches, a new build is running now for both the edge and candidate channels, jenkins should auto-test a few minutes later, once that's done, I'll switch your system to the candidate channel to confirm it works, then release to everyone through the stable channel and switch you back to that.

**Comment by stgraber** [comment]
should all be done within an hour or so

**Comment by stgraber** [comment]
```
root@zephyr:~# lxc remote add artellectual images.artellectual.com
If this is your first time using LXD, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:16.04

Generating a client certificate. This may take a minute...
Certificate fingerprint: 2b73554f343c57b752ffd9715b55f98efac20dae96963a1cdd370c114e697a29
ok (y/n)? n
error: Server certificate NACKed by user
```

So the snap in the candidate channel is fine. Just waiting for jenkins to run against it and the build to complete on two more architectures before pushing to the stable channel.

Reverting your server back to stable for now, will refresh once it's out.

**Comment by stgraber** [comment]
Hmm, jenkins isn't happy about this, taking a closer look.

**Comment by stgraber** [comment]
If you "snap refresh lxd" you should now get the fixed build.
