### ISSUE TITLE
Container lost connection after installing docker

### ISSUE THREAD

**Issue by hooramin** [lxc/lxd#3914]
* Distribution:  root@c:~# uname -a
Linux c 4.10.0-27-generic #30~16.04.2-Ubuntu SMP Thu Jun 29 16:07:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

 * `config: {}
api_extensions:
- id_map
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
removed
    -----END CERTIFICATE-----

  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
 kernel_version: 4.10.0-27-generic
  server: lxd
  server_pid: 11097
  server_version: 2.0.10
  storage: dir
  storage_version: ""
`
Hello there
I have ubuntu 16.04 as host and ubuntu 16.04 as container too
my container uses macvlan network type and it was working correctly before i install docker.
i tried to install docker by steps that they provided in their document 
but after rebooting my container lost 4.2.2.4 ping

-I disabled firewall but nothing changed.

    root@c:~# journalctl -u docker
    -- Logs begin at Sat 2017-10-07 19:58:22 UTC, end at Sat 2017-10-07 21:01:34 UTC. --
    Oct 07 19:58:23 chat systemd[1]: Starting Docker Application Container Engine...
    Oct 07 19:58:23 chat dockerd[320]: time="2017-10-07T19:58:23.211856389Z" level=info msg="libcontainerd: new containerd process, pid: 349"
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.255499446Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has over
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.258181761Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has over
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.272217318Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.272499353Z" level=warning msg="Your kernel does not support swap memory limit"
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.272578581Z" level=warning msg="Your kernel does not support cgroup rt period"
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.272593759Z" level=warning msg="Your kernel does not support cgroup rt runtime"
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.273777073Z" level=info msg="Loading containers: start."
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.275568789Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: could not insert 'br_netfilter
    Oct 07 19:58:24 chat dockerd[320]: insmod /lib/modules/4.10.0-27-generic/kernel/net/bridge/br_netfilter.ko
    Oct 07 19:58:24 chat dockerd[320]: , error: exit status 1"
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.409082387Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to se
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.464543315Z" level=info msg="Loading containers: done."
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.471393661Z" level=info msg="Docker daemon" commit=afdb6d4 graphdriver(s)=vfs version=17.09.0-ce
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.471481274Z" level=info msg="Daemon has completed initialization"
    Oct 07 19:58:24 chat dockerd[320]: time="2017-10-07T19:58:24.481979845Z" level=info msg="API listen on /var/run/docker.sock"
    Oct 07 19:58:24 chat systemd[1]: Started Docker Application Container Engine.

    docker0   Link encap:Ethernet  HWaddr 02:42:e2:70:4b:c4
              inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
              UP BROADCAST MULTICAST  MTU:1500  Metric:1
              RX packets:0 errors:0 dropped:0 overruns:0 frame:0
              TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0
              RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

    eth0      Link encap:Ethernet  HWaddr XX:XX:XX:00:64:22
              inet addr:myrealip  Bcast:mybcast  Mask:255.255.255.192
              inet6 addr: myip6 Scope:Link
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:131 errors:0 dropped:0 overruns:0 frame:0
              TX packets:676 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000
              RX bytes:14353 (14.3 KB)  TX bytes:29716 (29.7 KB)

    lo        Link encap:Local Loopback
              inet addr:127.0.0.1  Mask:255.0.0.0
              inet6 addr: ::1/128 Scope:Host
              UP LOOPBACK RUNNING  MTU:65536  Metric:1
              RX packets:25 errors:0 dropped:0 overruns:0 frame:0
              TX packets:25 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000
              RX bytes:2800 (2.8 KB)  TX bytes:2800 (2.8 KB)
can anyone help me about it ?

**Comment by stgraber** [comment]
Did you install Docker on the host or in the container?

In either case, I've seen Docker mess with your iptables rules, I don't know if their flag to turn off firewalling is quite enough for this.

You'd want to look at the output of "iptables -L -n -v". From what I recall seeing in the past, Docker had the tendency to change the default FORWARD policy from ACCEPT to REJECT or DROP, effectively blocking any network connection other than those they specifically allow.

If that's the issue, then doing "iptables -P FORWARD ACCEPT" should fix things by setting the default forward policy back to accept. Well, until Docker changes it back to reject anyway.

**Comment by stgraber** [comment]
The output above looks like it may all be inside a LXD container, in which case the most obvious potential issue would be that the docker0 subnet is conflicting with your outside subnet, unfortunately since you've hidden that particular IP, I can't tell.

Showing the output of "ip -4 route get 4.2.2.4" would probably shed some light on what's going on.

**Comment by stgraber** [comment]
Oh, I see that you filed this on the forum too, which is definitely the right place for such questions.
Can you respond in the forum thread with the information I requested above?

Closing the github issue in favor of the forum thread.
