### ISSUE TITLE
completely remove lxd ?

### ISSUE THREAD

**Issue by ddag** [lxc/lxd#3922]
I''ve been switching between lxd versions to see if it helped with some issues I've been having. I just installed the latest stable and I'm getting the following error even though I'm part of the lxd group (from OS POV that is), I've tried apt-get remove, but looks like it's not completely deleting everything ?

$ sudo apt-get install lxd lxd-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  criu lxd-tools
The following NEW packages will be installed:
  lxd lxd-client
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/5,274 kB of archives.
After this operation, 25.4 MB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package lxd-client.
(Reading database ... 176168 files and directories currently installed.)
Preparing to unpack .../lxd-client_2.0.10-0ubuntu1~16.04.2_amd64.deb ...
Unpacking lxd-client (2.0.10-0ubuntu1~16.04.2) ...
Selecting previously unselected package lxd.
Preparing to unpack .../lxd_2.0.10-0ubuntu1~16.04.2_amd64.deb ...
Unpacking lxd (2.0.10-0ubuntu1~16.04.2) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-4ubuntu19) ...
Setting up lxd-client (2.0.10-0ubuntu1~16.04.2) ...
Setting up lxd (2.0.10-0ubuntu1~16.04.2) ...
$ lxc list
Permission denied, are you in the lxd group?

**Comment by brauner** [comment]
You may need to logout and login again for the group settings to take effect.

**Comment by ddag** [comment]
Actually, I had to reboot. But, just in case I need to start from scratch at anytime, how do I completely remove lxd ?

**Comment by brauner** [comment]
@ddag, likely `apt purge lxd` should do the job.

**Comment by ddag** [comment]
Got the following from purge below. I assume it did not delete everything ?

Purging configuration files for lxd (2.0.10-0ubuntu1~16.04.2) ...
Failed to stop lxd.service: Unit lxd.service not loaded.
dpkg: warning: while removing lxd, directory '/var/lib/lxd' not empty so not removed

**Comment by brauner** [comment]
That either indicates that another program has stored additional files in there or that the user did manually store files there. If you're sure that's what you want you can forcibly remove `/var/lib/lxd` yourself now.

**Comment by stgraber** [comment]
Yeah, apt is rather conservative with removing stuff, even on purge... Wiping /var/lib/lxd by hand should be fine. I've usually seen this warning when LXD had a storage pool setup and mounted on /var/lib/lxd as that can't be easily removed.

It's usually recommended to delete containers and images and storage pools prior to purging LXD, otherwise some amount of kernel artifacts may stick around (mounts and processes).
