### ISSUE TITLE
LXC network still add an ipv6 to bridge when ipv6.address is set to none

### ISSUE THREAD

**Issue by Nani-o** [lxc/lxd#3927]
Hi,

I'm running :
```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
$ lxd --version
2.18
```

I perhaps miss something, but when running :
```
$ lxc network create testbr0 ipv4.address=1.1.1.1/24 ipv6.address=none
Network testbr0 created
$ lxc network show testbr0
config:
  ipv4.address: 1.1.1.1/24
  ipv6.address: none
description: ""
name: testbr0
type: bridge
used_by: []
managed: true
```

The created bridge still have an ipv6 configured :
```
$ ip addr show testbr0
20: testbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 32:0f:a0:a9:c5:41 brd ff:ff:ff:ff:ff:ff
    inet 1.1.1.1/24 scope global testbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::300f:a0ff:fea9:c541/64 scope link
       valid_lft forever preferred_lft forever
```

How do you totally disable ipv6 ?

**Comment by stgraber** [comment]
That's a link-local IPv6 address, the kernel gives you one of those for any interface that you create regardless of whether the network supports IPv6 or not.

You can turn that off on a per-interface basis through the disable_ipv6 sysctl.

/proc/sys/net/ipv6/conf/NAME/disable_ipv6

**Comment by Nani-o** [comment]
I was pretty sure it was nothing to do with lxd, sorry about that.

**Comment by stgraber** [comment]
No worries, not everyone is used to the "normal" ipv6 behavior yet :)
