### ISSUE TITLE
Live migration fails from one VM to another VM on same host 

### ISSUE THREAD

**Issue by psinha01** [lxc/lxd#3928]
# Required information
About VMs, LXD and CRIU:
 * Distribution: Ubuntu
 * Distribution version: 16.04.3 LTS (VMs); container1 (14.04); container2 (16.04); 
 * The output of "lxc info": ( detailed output at:
   for VM1: https://pastebin.com/UJC9pA0r  ;
   for VM2: https://pastebin.com/ry0Stch9  )
   * Kernel version: 4.4.0-87-generic
   * LXC version: 2.0.10
   * LXD version: 2.0.10
   * Storage backend in use: zfs
   * CRIU Version: 2.6 

About the host:
* Distribution: Ubuntu
* Distribution version: Ubuntu 14.04.5 LTS
* Kernel version: 4.8.0

# Issue description
1. Installed two new VMs (ubuntu 16.04.3 LTS) on same host (ubuntu 14.04.5 LTS).
2. Installed lxd and criu on both VMs
3. Created two containers c1 (ubuntu: 14.04)  and c2 (ubuntu: 16.04), both on VM1
4. Tried to do live migration of c1 (ubuntu: 14.04) from VM1 to VM2. It failed with following errors:

```
error: migration dump failed
(00.283482) Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
(02.146639) Warn  (criu/arch/x86/crtools.c:133): Will restore 20150 with interrupted system call
(02.321503) Warn  (criu/arch/x86/crtools.c:133): Will restore 20154 with interrupted system call
(02.493519) Warn  (criu/arch/x86/crtools.c:133): Will restore 20178 with interrupted system call
(03.168736) Error (criu/action-scripts.c:116): One of more action scripts failed
```

4. Tried to do live migration of c2 (ubuntu: 16.04) from VM1 to VM2. It failed with different errors:
```
error: migration dump failed
(00.216663) Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
(00.786994) Error (criu/parasite-syscall.c:532): Unable to connect a transport socket: Permission denied
(00.787004) Error (criu/parasite-syscall.c:134): Can't block signals for 20822: No such process
(00.787008) Error (criu/cr-dump.c:1244): Can't infect (pid: 20822) with parasite
(00.823925) Error (criu/ptrace.c:54): Unable to detach from 20822: No such process
(00.825758) Error (criu/cr-dump.c:1628): Dumping FAILED.
```

# Steps to reproduce: 
 1. Step one: 
I used standard commands to install lxd and criu (given below):

```
$> sudo apt-get install lxd
$> sudo apt update
$> sudo apt install zfsutils-linux
$> sudo lxd init           //kept all the default values 
Name of the storage backend to use (dir or zfs) [default=zfs]: 
Create a new ZFS pool (yes/no) [default=yes]? 
Name of the new ZFS pool [default=lxd]: 
Would you like to use an existing block device (yes/no) [default=no]? 
Size in GB of the new loop device (1GB minimum) [default=17]: 
Would you like LXD to be available over the network (yes/no) [default=no]? 
Do you want to configure the LXD bridge (yes/no) [default=yes]? 
Warning: Stopping lxd.service, but it can still be activated by:
  lxd.socket
LXD has been successfully configured.

$> sudo apt-get install criu
$> criu --version
Version: 2.6
```
 2. Step two: I added VM2 as remote machine on VM1 and VM1 as remote on VM2.
On VM1 and VM2, both:

```
$> lxc config set core.https_address "[::]"
$> lxc config set core.trust_password common-password
```

On VM1:

`$> lxc remote add foo VM2_IP_ADDRESS`

 3. Step three:
- On VM1, Launched two containers c1 (ubuntu: 14.04)  and c2 (ubuntu: 16.04) 

```
$> lxc launch ubuntu:14.04 c1
$> lxc launch ubuntu:16.04 c2
```

4. Step four: 
- On VM1: ran the command to do live migration of c1:

```
$> lxc move c1 foo:

error: migration dump failed
(00.283482) Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
(02.146639) Warn  (criu/arch/x86/crtools.c:133): Will restore 20150 with interrupted system call
(02.321503) Warn  (criu/arch/x86/crtools.c:133): Will restore 20154 with interrupted system call
(02.493519) Warn  (criu/arch/x86/crtools.c:133): Will restore 20178 with interrupted system call
(03.168736) Error (criu/action-scripts.c:116): One of more action scripts failed
```

This failed.

- On VM1: ran the command to do live migration of c2:

```
$> lxc move c2 foo:

error: migration dump failed
(00.216663) Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
(00.786994) Error (criu/parasite-syscall.c:532): Unable to connect a transport socket: Permission denied
(00.787004) Error (criu/parasite-syscall.c:134): Can't block signals for 20822: No such process
(00.787008) Error (criu/cr-dump.c:1244): Can't infect (pid: 20822) with parasite
(00.823925) Error (criu/ptrace.c:54): Unable to detach from 20822: No such process
(00.825758) Error (criu/cr-dump.c:1628): Dumping FAILED.
```

This failed too.

Any help???? Thanks.

# Information to attach
 - [ ] log files:

lxc info c1 --show-log
https://pastebin.com/pR1ttHmY 

lxc info c2 --show-log
https://pastebin.com/gGpRtdrY 

lxc move c1 foo: --verbose --debug
https://pastebin.com/RuDjEnNH

lxc move c2 foo: --verbose --debug
https://pastebin.com/G94eG1QU

/var/log/lxd/lxd.log
https://pastebin.com/cBDBptEf

/var/log/lxd/c1/lxc.log
https://pastebin.com/BmmhSTEf

/var/log/lxd/c2/lxc.log
https://pastebin.com/anRpZDMB

**Comment by stgraber** [comment]
LXD is doing what it's supposed to do here, which is call out to CRIU to attempt to serialize your container's state. Unfortunately CRIU is hitting something that it can't serialize, causing the failure.

CRIU's job is to serialize an entire container's state down to disk, this is incredibly tricky due to all the various kernel structures that may be in play. In general, the more recent the kernel and the older the CRIU version, the least likely it is to succeed. CRIU can be upgraded independently of LXD so it's reasonably easy to install a newer version and see if that somehow helps.

I'd recommend you try to build and run the latest upstream CRIU release, if that's not helping, then attempt to downgrade to the 4.4 kernel which is what we've seen the best results on. If none of that works, you can file a bug against CRIU upstream and hopefully get a fix for the particular feature that's needed on your system.


On our side, we will look into any bug that's directly related in the LXD to CRIU integration or our storage migration code but as cool a feature as it is, we're short on time to invest into CRIU and the upstream kernel itself to resolve those kind of issues. It's our hope that upstream CRIU and other contributors will make progress there. We may also be able to help with specific issues through contract work, depending on the exact scope of the problem and how likely we think it is we can support a particular use case.

**Comment by psinha01** [comment]
Thanks  for the reply.
Before asking above question, I have found some other people here also asked same and similar problems. The general suggestion was to update the criu to a newer version, which I already have followed before asking above question here, but still no luck in making live migration work.

About the kernel downgrade suggestion:
My kernel is already at 4.4 version. 

Can you please suggest any working combination of exact distribution version, kernel version, criu version and lxd version that allows live migration successfully? Thank you.

**Comment by stgraber** [comment]
Last time I spent some time trying this, Ubuntu 16.04 LTS with LXD 2.0.10 or 2.18 and the latest 4.4 kernel was working fine with containers that don't do anything problematic.

I'd say to try with "images:alpine/edge" as alpine containers are exceedingly simple as far as what they use from the kernel.

**Comment by psinha01** [comment]
Thank you so much for the reply. Can you please suggest about the CRIU version that worked with that setup in your previous reply (as CRIU is the one that causing the main issue)? Thank you.

**Comment by stgraber** [comment]
It was CRIU 2.6 from the Ubuntu archive I believe.

**Comment by psinha01** [comment]
Thank you so much

**Comment by psinha01** [comment]
Hi @stgraber 
Migrating a container from one VM to another VM (both VMs running on same host) takes too much time. So, I have been trying to do migration without migrating the disk image of the container by keeping the disk image accessible over NFS at both source and destination VMs. 

I have been digging through the lxc code for a while. "lxc move" command follows
move.go: run() -> copy.go: copyContainer()  -> lxd_containers.go: CopyContainer() -> tryCreateContainer() -> CreateContainer() -> lxd.go: queryOperation() -> query() -> rawQuery()  -> container_exec.go: Do()

And there it finishes the target operation. I tried to modify the code but no success yet.

Is there any way I can do migration without migrating the disk image? 
Another way around I can think of is to disable migration code on "lxc move" command. Instead, create a new container on destination using the disk image (which is accessible on destination VM using NFS). But this approach will not maintain the live state of the container. I would appreciate any pointers. Thank you.

**Comment by psinha01** [comment]
Hi, is there any way we can enable print to stdout in LXD? Thanks
