### ISSUE TITLE
log_posix.go and not enough arguments in call to log15.Must.SyslogHandler

### ISSUE THREAD

**Issue by jokogr** [lxc/lxd#3932]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.3
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-97-generic
   * LXC version: 2.0.8
   * LXD version: 2.18
   * Storage backend in use: zfs

# Issue description

I am following the instructions on README.md to build lxd on Ubuntu 16.04.3 and I get the following message:

```
% make             
go get -t -v -d ./...
go install -v   ./...
github.com/lxc/lxd/shared/logging
# github.com/lxc/lxd/shared/logging
shared/logging/log_posix.go:16: not enough arguments in call to log15.Must.SyslogHandler
shared/logging/log_posix.go:20: not enough arguments in call to log15.Must.SyslogHandler
Makefile:16: recipe for target 'default' failed
make: *** [default] Error 2
```

# Steps to reproduce

 1. `sudo apt install acl dnsmasq-base git golang liblxc1 lxc-dev libacl1-dev make pkg-config rsync squashfs-tools tar xz-utils`
 2. `sudo apt install curl gettext jq sqlite3 uuid-runtime bzr`
 3. `mkdir -p ~/go`
 4. `export GOPATH=~/go`
 5. `go get github.com/lxc/lxd`
 6. `cd $GOPATH/src/github.com/lxc/lxd`
 7. `make`

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
You need to refresh your go packages, log15 unfortunately broke API recently and we had to land a fix in LXD for it, which is now causing the failure on your system because your log15 is outdated.

    go get -v -x -u all

**Comment by jokogr** [comment]
@stgraber this is something I ran on a vanilla system a couple of hours ago, so the go packages are as fresh as possible.

In any way, I ran the command you provided as well and it still does not work. Any other ideas?

**Comment by stgraber** [comment]
Oh, I guess you used a LXD release tarball then, instead of our git tree directly?

**Comment by stgraber** [comment]
In which case, rather than using the git versions of the dependencies, you may want to move the content of the dist/ directory into your GOPATH, that'll include the older log15 that LXD 2.18 needs.

**Comment by jokogr** [comment]
You got me, I had done a git checkout of lxd-2.18 before running make, I've totally forgotten to include this in the issue, sorry.

LXD is being built correctly on master.

Off-topic: Are there any plans to upload a release download for 2.18? The source code of the tags does not include the `dist` directory.

**Comment by stgraber** [comment]
https://linuxcontainers.org/lxd/downloads/ should have the release tarball

**Comment by stgraber** [comment]
I'm going to sync github again, I wish there was a way to disable that release page....
