### ISSUE TITLE
"rename" commands in the CLI

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3936]
To make things a bit easier on users and to expose API functionality that's so far been missing in the client tool, we should implement the following functions:

 - "lxc rename" (same as move, but local-only, RenameContainer or RenameContainerSnapshot call)
 - "lxc profile rename" (RenameProfile call)
 - "lxc network rename" (RenameNetwork call)
 - "lxc image alias rename" (RenameImageAlias call)

**Comment by albertodonato** [comment]
The `lxc image alias rename` seems a bit unnecessary (and weird) to me.
An alias is not an entity with a name,  it's just a name, so chaging it is basically like creating a new one.
I don't see much value over `lxc image alias delete` + `lxc image alias create`

**Comment by stgraber** [comment]
An alias does have a description.

**Comment by stgraber** [comment]
I agree that renaming an alias is going to be the least used of all of those, but we have the API for it and the client function for it, but it's very cheap to do so we should be exposing it for consistency.

**Comment by albertodonato** [comment]
Fair enough, I also forgot that aliases also have description.

**Comment by albertodonato** [comment]
It seems `lxc rename` is already there
