### ISSUE TITLE
LXD on Ubuntu for Windows 10

### ISSUE THREAD

**Issue by ddag** [lxc/lxd#3939]
First, I had to grab lxd from xenial-backports. This got me to issue the init call, but then I got the error below.

$ sudo lxd init
Do you want to configure a new storage pool (yes/no) [default=yes]?
Name of the new storage pool [default=default]:
Name of the storage backend to use (dir, btrfs, lvm) [default=btrfs]: dir
Would you like LXD to be available over the network (yes/no) [default=no]?
Would you like stale cached images to be updated automatically (yes/no) [default=yes]?
Would you like to create a new network bridge (yes/no) [default=yes]?
What should the new bridge be called [default=lxdbr0]?
What IPv4 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]?
What IPv6 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]? none
**error: Failed to run: ip link add dev lxdbr0 type bridge: RTNETLINK answers: Permission denied**

**Comment by stgraber** [comment]
LXD cannot work on the fake Linux kernel that Windows runs.

**Comment by stgraber** [comment]
Windows's Linux subsystem implements a very limited set of kernel APIs, which in this case means no support for advanced networking, but also no support for cgroups or containers in general in their kernel.

**Comment by ddag** [comment]
Ah, I thought it did based on this article -- https://insights.ubuntu.com/2017/02/27/lxd-client-on-windows-and-macos.

**Comment by stgraber** [comment]
That's about running the LXD client tool against a remote LXD server (running on Linux).
