### ISSUE TITLE
Ceph and one pool for LXD instances

### ISSUE THREAD

**Issue by deponian** [lxc/lxd#3958]
Hello.

I'm very interested in opportunity to use one Ceph pool with multiple LXD instances аnd especially in "smart" migration when container transfers from one host to another without actual copying because of they share one Ceph pool.

Can you say anything about the approximate time of the release of those features?

**Comment by stgraber** [comment]
Not expecting this particularly soon. I'd say 6 months at best. The main issue is that LXD stores a lot of metadata about storage pools and volumes in its database, so simply being able to see the same blocks in two places doesn't make it safe to use.

There are two approaches that may get you there:
 - LXD clustering will get multiple LXD hosts using the same database, which will make it possible for us to move containers between hosts without ever actual moving anything.
 - There has been discussions before in adding a separate Ceph disk device type to LXD which would allow you to directly attach an RBD volume to a container without it having to be coming from a LXD storage pool.

**Comment by deponian** [comment]
Thanks for the answer.
LXD clustering looks interesting.
