### ISSUE TITLE
package github.com/lxc/lxd: no buildable Go source files

### ISSUE THREAD

**Issue by psinha01** [lxc/lxd#3960]
About the VM:

Distribution: ubuntu
Distribution version: ubuntu 17.04 zesty
Kernel version: 4.10.0-19-generic
LXC version (already installed with ubuntu distro): 2.12
LXD version (already installed with ubuntu distro): 2.12
Storage backend in use: zfs

About the host:

Distribution: Ubuntu
Distribution version: Ubuntu 14.04.5 LTS
Kernel version: 4.8.0

# Issue description

On a new VM with ubuntu 17.04, I am trying to build LXD from source code of LXD-2.19. It says:
```
o197@o197:~$ go get github.com/lxc/lxd
package github.com/lxc/lxd: no buildable Go source files in /home/o197/go/src/github.com/lxc/lxd
```

I tried to build from source for LXD version 2.12 too (which is the version of the lxd that comes with ubuntu 17.04 by default), but this also gave the same message.

This is same as issue #3666 and tried to follow the suggestion by using version of LXD higher than 2.15, but still the issue is there. Kindly help. Thanks

# Steps to reproduce

 1. Step one: Installing all the required packages
```
sudo apt update
sudo apt install acl dnsmasq-base git golang liblxc1 lxc-dev libacl1-dev make pkg-config rsync squashfs-tools tar xz-utils

sudo apt install lvm2 thin-provisioning-tools
sudo apt install btrfs-tools

sudo apt install curl gettext jq sqlite3 uuid-runtime bzr
```
 2. Step two: Building the tools
```
mkdir -p ~/go
export GOPATH=~/go
```
 3. Step three: Downloading it
`
go get github.com/lxc/lxd
`
It gives following error:
`
package github.com/lxc/lxd: no buildable Go source files in /home/o197/go/src/github.com/lxc/lxd
`

**Comment by stgraber** [comment]
That's normal, there's no Go code at the source of our tree.

You'll want one of those:

    go get -v -x github.com/lxc/lxd/lxc
    go get -v -x github.com/lxc/lxd/lxd
    go get -v -x github.com/lxc/lxd/lxc-benchmark
    go get -v -x github.com/lxc/lxd/fuidshift

Note that our tree is currently not buildable due to a broken dependency, a pull request has been open to get this resolved soon.

**Comment by psinha01** [comment]
Thank you so much. It was very helpful.

**Comment by xmj** [comment]
@stgraber which dependency is that?

**Comment by stgraber** [comment]
@xmj that was a broken API in bakery.v2 I believe
