### ISSUE TITLE
LXD remote host doesn't show if ssh into server using another user than whom added it.

### ISSUE THREAD

**Issue by HW-Siew** [lxc/lxd#3963]
Hi, I am not really sure whether this is a bug or default behavior. Hope that anyone can give me some guidance here. So this is the case, I used one user (userA) added a remote host and everything works fine if i remain as userA. However, if I ssh into server using another user (userB), the result of 'lxc remote list' doesn't show the remote host added by userA. And, both user are in the same 'lxd' group. 

Os : ubuntu 16.04
lxd version : 2.18

![image](https://user-images.githubusercontent.com/10137637/31861524-3f6d6528-b761-11e7-9826-c454388db4eb.png)

Thanks.

**Comment by stgraber** [comment]
"remotes" are a purely CLI tool concept, so your lists of remote is specific to your client config which is stored per user (~/.config/lxc/).

**Comment by HW-Siew** [comment]
I see. Thank you for the reply.
