### ISSUE TITLE
Rebooting host causes GPU / XAuthority, X passthrough to fail and container to fail to start

### ISSUE THREAD

**Issue by RevoluPowered** [lxc/lxd#3968]
# Required information

 * Distribution: Debian 9 (strech) (installed edge via snapd) 
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.9.0-4
   * LXC version: 2.19
   * LXD version: 2.19 
   * Storage backend in use: zfs

# Issue description

Attempting to make my LXD instance passthrough GUI to the host using the GPU device added recently. I got it working following the guide here: https://blog.simos.info/how-to-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop/

It worked until I rebooted, once the host was rebooted the container was failing to start.

# Steps to reproduce

 1. Install as per guide linked
 2. Once it works, reboot your host
 3. Bug should be visible, container will be in a 'stopped' state and until you remove the .XAuthority and .X mappings in the configuration it won't start up again.
4. Attempted remapping the raw.idset as per the guide didn't work
5. Attempted re-running the configuration didn't work.

Other people are having issues using the GPU device in the same way, you can see similar errors posted on the topic, I think the configuration supplied by the guide is wrong, but how do we correct it when no other guides exist for the gpu device?

# Information to attach
[container.log](https://github.com/lxc/lxd/files/1410483/container.log)
[configlog.log](https://github.com/lxc/lxd/files/1410485/configlog.log)
[lxd.log](https://github.com/lxc/lxd/files/1410486/lxd.log)

**Comment by stgraber** [comment]
I'd recommend responding to one of the forum posts in https://discuss.linuxcontainers.org, Simos is quite active there and should be able to help you (and update his post).

**Comment by RevoluPowered** [comment]
Ah cool thank you

Posting this here for completeness!

**Comment by stgraber** [comment]
Hmm, that looks like code I landed yesterday in the edge channel, I wonder if that somehow broke things...

**Comment by RevoluPowered** [comment]
Thank you for the fix, I will updated once the merge is in.

**Comment by stgraber** [comment]
the edge snap that you're using will auto update once this is merged and jenkins thinks everything is good

**Comment by RevoluPowered** [comment]
Will update now, thanks for your assistance, this project is my favourite Linux tool.
