### ISSUE TITLE
Juju fails to bootstrap LXD on artful

### ISSUE THREAD

**Issue by nskaggs** [lxc/lxd#3970]
Originally reported at:
  https://bugs.launchpad.net/bugs/1726993

2.18-0ubuntu4 bootstraps successfully, but 2.18-0ubuntu5 fails. Upstream carried across a patch (0023-dir-make-sure-pool-is-mounted.patch) for dir pool which breaks juju. 

17:39:40 ERROR juju.cmd.juju.commands bootstrap.go:509 failed to bootstrap model: cannot start bootstrap instance: no such file or directory
17:39:40 DEBUG juju.cmd.juju.commands bootstrap.go:510 (error details: [{github.com/juju/juju/cmd/juju/commands/bootstrap.go:601: failed to bootstrap model} {github.com/juju/juju/provider/common/provider.go:24: } {github.com/juju/juju/provider/common/bootstrap.go:50: } {github.com/juju/juju/provider/common/bootstrap.go:185: cannot start bootstrap instance} {github.com/juju/juju/provider/lxd/environ_broker.go:49: } {github.com/juju/juju/provider/lxd/environ_broker.go:211: } {github.com/juju/juju/tools/lxdclient/client_instance.go:116: } {github.com/juju/juju/tools/lxdclient/client_instance.go:88: } {no such file or directory}])
17:39:40 DEBUG juju.cmd.juju.commands bootstrap.go:1107 cleaning up after failed bootstrap
17:39:40 INFO  juju.provider.common destroy.go:20 destroying model "controller"
17:39:40 INFO  juju.provider.common destroy.go:31 destroying instances
17:39:40 INFO  juju.provider.common destroy.go:55 destroying storage
17:39:40 ERROR juju.cmd.juju.commands bootstrap.go:1109 error cleaning up: destroying LXD filesystems for model: listing volumes in LXD storage pool {{map["source":"/var/lib/lxd/storage-pools/extra/storage-pools/lxd"]} "/extra/storage-pools/lxd" "dir" []}: not found

**Comment by stgraber** [comment]
why are you using ubuntu5 when ubuntu6 contains the fix for this?

**Comment by nskaggs** [comment]
@stgraber I should have mentioned, ubuntu6 still fails in the same way.

**Comment by nskaggs** [comment]
This has been cleared up by reinstalling lxd on the afflicted machines.
