### ISSUE TITLE
Test runner has been running the latest build for over 5 hours.

### ISSUE THREAD

**Issue by RevoluPowered** [lxc/lxd#3971]
The jenkins build is stuck at this:
Configuration lxd-github-pull-test » i386,dir,golang-1.6,lxd-priv is still in the queue: All nodes of label ‘i386&&lxd-priv’ are offline

**Comment by RevoluPowered** [comment]
https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/3409/console

**Comment by RevoluPowered** [comment]
#3969

**Comment by stgraber** [comment]
All the test runners are offline due to a power cut so all pull requests are currently queued pending the test runners coming back online (which should happen very soon now).

**Comment by RevoluPowered** [comment]
Ah cool! Hope everything is OK.

**Comment by stgraber** [comment]
Yeah, everything should be back now. The power outage lasted a few hours so after a bit of time, non-critical services like the jenkins runners were shut down to save the battery for more critical services. Once the power came back, things had to be powered back up again which is now all done.
