### ISSUE TITLE
Assign network to macvlan network 

### ISSUE THREAD

**Issue by jenningsloy318** [lxc/lxd#3972]
Github issues are used for bug reports. For support questions, please use [our forum](https://discuss.linuxcontainers.org).

Please fill the template below as it will greatly help us track down your issue and reproduce it on our side.  
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
```
#lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFVjCCAz6gAwIBAgIRAJZquZDwb/C2J1nhjCvyrRswDQYJKoZIhvcNAQELBQAw
    NzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEXMBUGA1UEAwwOcm9vdEBs
    eGMtaG9zdDEwHhcNMTcxMDE5MDI0NjU0WhcNMjcxMDE3MDI0NjU0WjA3MRwwGgYD
    VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRcwFQYDVQQDDA5yb290QGx4Yy1ob3N0
    MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKzUyY4E+IE4ApH1covk
    LyZpoigTgV31fnybgh/3cpuK3/jniOfbyVdELMaBqfgwMAMl43GRSYDq7l3Ot+bg
    HoTL6uwSVj4F41eJesyMMy8NHU4xhEcRh7BTTKgCP/rA+nxBLuKD5CMQ4txCZysI
    RYG3diYv02v9Yuu7c3b0b4P/ljWmVZB6bngOc2MZCDQ1kFsKyp28luj8IEvdI6cZ
    uXqYrXl8DuPNRzZs6ZL9prdcN/s663PF2F8S/F3/o04MdbpVzfqiOvuD72jC0nTP
    6fEsMZIGCiucbQJcnfnQQO5gRybXz23onraX2behqjCaQOtv1kVLY6iIi1RVFUns
    HYQJXzuXlhvhApkMIjQbzg8LdzNJUkeSeHYSJbvsU4T56/RKuI7oTwzxgc6yhoSj
    sFQRlvpHI0pPxpoVDrf7l63ExDZIiaDcUx1P0VL/M7i4SALcFNDzk276Qs9numFc
    EmRi/miOIjDUgubcwJ2LVv3GTO8wgnJ7eTOAfGZYxoS75QmpxLGQFBOO4AZlYyV+
    EAlaRz2Z4cgHOS8NkyVTWuVZvfTCBMPyxBmvqGxKruWTaghP6Rjp28/vsnjbKNyP
    S9TzYes7nIoGcpvNNVebNVZ4TjP3ZuWcneh6fPB+7SDRCPqeZ66KxjiYPJwPEOoB
    cN3hSvwq94pXHfFGT9z74FpnAgMBAAGjXTBbMA4GA1UdDwEB/wQEAwIFoDATBgNV
    HSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMCYGA1UdEQQfMB2CCWx4Yy1o
    b3N0MYcEwKg7gIcEClgBAYcECgADATANBgkqhkiG9w0BAQsFAAOCAgEApLbelIHO
    WEvuo67K+jbGr3RSdKagUk4Vv7pzmetRbU2WjQr8SZmwW8CkUaXAZTMtRQ3UjpCl
    JtuktS3osgYVklFJMkKvatfvIpLCMrOUadWZLQVIvzyhbLtnQ/ZePgVXebMAeY21
    LOOLCDVaGukgF+MMDRISUC/t/QlFbR5gym6Yh+lr2Y3x8C44512m1Xudd/04lIu1
    ndkPVqei61vmV8bUq9XmlCk66tef1mj79JfF2x2lgCtA9oP8iP77lQ6PYFVcoKmb
    /vXv5aYY03PjaW2qN4NkAH1XID3KaLmQQCt1n84UC2SYfzfHIfsytGtAeIpY42Ae
    4huIpjL63WIr1OG2Z8W1SwaIt05rp7hHnp5i+E0P2P8oWwJWm4d5FGqwwMFIDGuE
    0CJieY44ySPMNFkN5z6qXvLP027jLwNFwKa6qX8sSW1xPM3QsLgDul6lqKbnyhU3
    Ew8EWCU8gJjfFZPNspmolptPERWL0uMRsWetD4wAyOKO/9b8Kksbp6OFi3DU4Ic5
    6aLuUKYJX9cHV4jjHBbTCNFt6CzJTr5gzHJM8X+05N40s9oS1rE0EP881lioC5WJ
    8xXHEJk7pXJU/ACz/PwJJ0W9UW0CiX8ypkzcVx7zHNs+cYECAXAt98jTbUD9KZgG
    MNT9+rB5p6znEgwaSE3bjpQ1bNF54M94jkk=
    -----END CERTIFICATE-----
  certificate_fingerprint: 597f9170453363cb5f3545b16b2f91710fa7acda94f3c74f32030a4ea966c71f
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-37-generic
  server: lxd
  server_pid: 1507
  server_version: "2.18"
  storage: dir
  storage_version: "1"
```
   * Kernel version: 4.10.0-37-generic
   * LXC version: 2.1.0
   * LXD version:2.18
   * Storage backend in use: dir

# Issue description

when using macvlan for contaner network, it is impossible to add a network to the profile

# Steps to reproduce
1. create a macvlan device on top of host nic
```
#ip link add link ens33 macvlan4 type macvlan mode bridge
#ip link set macvlan4  up
```
2. create network 
```
#lxc network create macvlan4-net
#lxc network show macvlan4-net
config:
  ipv4.address: 10.27.27.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:498f:110d:7347::1/64
  ipv6.nat: "true"
description: ""
name: macvlan4-net
type: bridge
used_by:
- /1.0/containers/test-macvlan4
managed: true
```

3. create profile 
```
#lxc profile  create macvlan4-profile
```
4. attach network to profile 

```
 #lxc network attach-profile macvlan4-net  macvlan4-profile eth0
 #lxc profile device set macvlan4-profile eth0 nictype macvlan  parent macvlan4
 #lxc profile device add macvlan4-profile root 2 path=/ pool=default type=disk
```

5 launch an instance
```
#lxc launch ubuntu test-macvlan4 -p macvlan4-profile 
```

6. instance info 
```
# lxc info test-macvlan4
Name: test-macvlan4
Remote: unix://
Architecture: x86_64
Created: 2017/10/25 07:16 UTC
Status: Running
Type: persistent
Profiles: macvlan4-profile
Pid: 5432
Ips:
  eth0: inet6   fe80::216:3eff:fe07:6c69
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 6
  CPU usage:
    CPU usage (in seconds): 1
  Memory usage:
    Memory (current): 51.87MB
    Memory (peak): 72.35MB
  Network usage:
    eth0:
      Bytes received: 0B
      Bytes sent: 1.24kB
      Packets received: 0
      Packets sent: 9
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
```
**This key point of this configuration is to use an already existing macvlan device as parent in the profile.** 

I found the root cause is that the type of the network is bridge, not sure if it is possible to change the type to macvlan? 

I also tried to launch the instance without attaching  a network (also created a profile, just don't have the network attached it) , and the instance will get the IP address in the same lan with the host lan.  when adding the route on host, I can access the container from host. (if the container IP is ip1, we just add `route add -host ip1 dev macvlan4`)

**Comment by stgraber** [comment]
Why would you do that?

Just do:

    lxc network attach-profile ens33 default eth0 eth0

And all containers using the "default" profile will now get their eth0 as a macvlan device on top of your physical ens33 device.

**Comment by stgraber** [comment]
I'm not sure why you think you need to use that pre-existing macvlan device.
LXD is perfectly capable to generate macvlan devices for you so just tell LXD the name of the physical device you want to connect to and you're done.

You can create your macvlan4 device and then setup a bridge with LXD that's using it as its underlay, but that's just adding an extra layer (a bridge) which will do nothing but complicate your setup and slow things down.

**Comment by jenningsloy318** [comment]
@stgraber 

My assumption is to assign ip address to macvlan nic with my pre-configured subnet. not the ouside DHCP assignment. But I don't have any method to configure the network subnet assigned to the macvlan device. 

In the past, I have ever configured lxc using such configuation. not sure why I can't achieve this in LXD.

**Comment by stgraber** [comment]
Ah, yes, we don't support that directly in LXD as we instead would like users to just configure their networking from inside the container, possibly feeding the information through something like cloud-init.

That being said, we don't prevent you from forcing it either. So you can set the "raw.lxc" config key for your container with the normal LXC configuration keys for this.

Something like:

    raw.lxc: |-
      lxc.network.0.ipv4 = 10.0.3.100
      lxc.network.0.ipv4.gateway = 10.0.3.1

**Comment by jenningsloy318** [comment]
@stgraber 
Thanks,  followed your advice, I can configure container in this way.

**Comment by stgraber** [comment]
As I mentioned, LXD doesn't do netns pre-configuration, nor do we plan to do it.
You can use the raw.lxc trick, but you'll indeed need to manually do that for every container.

The way LXD normally allocates container addresses is through DHCP, which you can't really do in your case as even if you bridge your macvlan device and then have LXD run a DHCP server on that, this would effectively run a DHCP server on the physical network attached to the bridge and possibly break things on your network.


There are two main ways to go about with networking in your case:

1) Setup a local LXD bridge which doesn't include any physical NIC. Set that up with the subnet you want your containers to use and LXD will provide DHCP on it for your containers. Then configure the router on your network to route that subnet to your LXD host.

2) Keep bridging directly to your physical network and configure the DHCP server on your network to allocate IPs to your containers in whatever subnet you want. This can be done by matching the MAC address prefix of the containers. If that's not an option, then you're back to setting static config as mentioned above.
