### ISSUE TITLE
lxc info.environment.driver_version (JMESPath Basic Expression)

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3973]
While looking at `lxc info --resources` I thought that maybe it is possible to extend command line API of `info` with dot notation? [JMESPath Basic Expressions](http://jmespath.org/tutorial.html) 

So if I need to get some server_version from script, I run `lxc info.environment.server_version`. Right now I need to do unreliable `lxc info | grep server_version` and split if with cryptic `cut -d: -f2 | tr -d " "`.

Then command line from this:

    lxc info [<remote>:]<container> [--show-log]

Would be this:

    lxc info[.selector] [--server|--container|--log|--resources] [<remote>:]<container>

What do you think?

   * LXD version: 2.18

**Comment by stgraber** [comment]
stgraber@castiana:~$ lxc query /1.0 | jq -r .environment.driver_version
2.1.0 (devel)

**Comment by techtonik** [comment]
This requires `jq`, which is not installed.
