### ISSUE TITLE
LXD failing to start container when using ZFS pool on other hard drive, only after reboot [edge]

### ISSUE THREAD

**Issue by RevoluPowered** [lxc/lxd#3976]
# Required information
 * Distribution: debian 9 strech
 * Kernel version: 4.9.0-4-amd64  
 * LXD version: edge (latest; checked)
 * Storage backend in use: zfs

Using ZFS from sda1. Configured storage on another HDD when using lxd init.

# Issue description

Container failing to start with normal start command.

No custom GPU forwarding or Authority configuration, fresh install using -- edge with snapd.

# Steps to reproduce
1. Configure LXD to use ZFS from other hard drive using lxd init (use existing device -- yes)
2. launch container debian - strech (container works)
3. reboot host
2. launch using lxc start build-bot
3. lxc start build-bot
4. error: 
error: no such file or directory
Try `lxc info --show-log build-bot` for more info

# Information to attach
**Container log**
Name: build-bot
Remote: unix://
Architecture: x86_64
Created: 2017/10/26 01:06 UTC
Status: Stopped
Type: persistent
Profiles: default

**Container configuration**
 - [ ] Container configuration (`lxc config show NAME --expanded`)
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian stretch amd64 (20171025_22:42)
  image.os: Debian
  image.release: stretch
  image.serial: "20171025_22:42"
  volatile.base_image: 21fae0325d00b6077fac9b399ecb9a5b59c88da4f96750ee61da2b9842339d43
  volatile.eth0.hwaddr: 00:16:3e:d4:b2:45
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
**Main daemon log**
lvl=info msg="LXD 2.19 is starting in normal mode" path=/var/snap/lxd/common/lxd t=2017-10-25T22:58:38+0000
lvl=warn msg="AppArmor support has been disabled because of lack of kernel support" t=2017-10-25T22:58:38+0000
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-10-25T22:58:38+0000
lvl=info msg="Kernel uid/gid map:" t=2017-10-25T22:58:38+0000
lvl=info msg=" - u 0 0 4294967295" t=2017-10-25T22:58:38+0000
lvl=info msg=" - g 0 0 4294967295" t=2017-10-25T22:58:38+0000
lvl=info msg="Configured LXD uid/gid map:" t=2017-10-25T22:58:38+0000
lvl=info msg=" - u 0 1000000 1000000000" t=2017-10-25T22:58:38+0000
lvl=info msg=" - g 0 1000000 1000000000" t=2017-10-25T22:58:38+0000
lvl=info msg="Expiring log files" t=2017-10-25T22:58:38+0000
lvl=info msg="Done expiring log files" t=2017-10-25T22:58:38+0000
lvl=info msg="Starting /dev/lxd handler" t=2017-10-25T22:58:38+0000
lvl=info msg="LXD isn't socket activated" t=2017-10-25T22:58:40+0000
lvl=info msg="REST API daemon:" t=2017-10-25T22:58:40+0000
lvl=info msg=" - binding Unix socket" socket=/var/snap/lxd/common/lxd/unix.socket t=2017-10-25T22:58:40+0000
lvl=info msg="Pruning expired images" t=2017-10-25T22:58:40+0000
lvl=info msg="Done pruning expired images" t=2017-10-25T22:58:40+0000
lvl=info msg="Updating images" t=2017-10-25T22:58:40+0000
lvl=info msg="Updating instance types" t=2017-10-25T22:58:40+0000
lvl=info msg="Done updating images" t=2017-10-25T22:58:40+0000
lvl=info msg="Done updating instance types" t=2017-10-25T22:58:49+0000
lvl=info msg="Creating ZFS storage pool \"default\"." t=2017-10-26T00:58:53+0000
lvl=info msg="Created ZFS storage pool \"default\"." t=2017-10-26T00:58:54+0000
alias=debian/stretch image=21fae0325d00b6077fac9b399ecb9a5b59c88da4f96750ee61da2b9842339d43 lvl=info msg="Downloading image" operation=c7761004-fc13-425f-a51e-61493369e0fd server=https://images.linuxcontainers.org t=2017-10-26T01:01:57+0000 trigger=/1.0/operations/c7761004-fc13-425f-a51e-61493369e0fd
alias=debian/stretch image=21fae0325d00b6077fac9b399ecb9a5b59c88da4f96750ee61da2b9842339d43 lvl=info msg="Image downloaded" operation=c7761004-fc13-425f-a51e-61493369e0fd server=https://images.linuxcontainers.org t=2017-10-26T01:06:58+0000 trigger=/1.0/operations/c7761004-fc13-425f-a51e-61493369e0fd
ephemeral=false lvl=info msg="Creating container" name=build-bot t=2017-10-26T01:06:58+0000
ephemeral=false lvl=info msg="Created container" name=build-bot t=2017-10-26T01:06:58+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=build-bot t=2017-10-26T01:07:02+0000
action=start created=2017-10-26T01:06:58+0000 ephemeral=false lvl=info msg="Starting container" name=build-bot stateful=false t=2017-10-26T01:07:02+0000 used=1970-01-01T00:00:00+0000
action=start created=2017-10-26T01:06:58+0000 ephemeral=false lvl=info msg="Started container" name=build-bot stateful=false t=2017-10-26T01:07:02+0000 used=1970-01-01T00:00:00+0000
lvl=info msg="Asked to shutdown by API, shutting down containers." t=2017-10-26T01:34:02+0000
action=shutdown created=2017-10-26T01:06:58+0000 ephemeral=false lvl=info msg="Shutting down container" name=build-bot t=2017-10-26T01:34:02+0000 timeout=30s used=2017-10-26T01:07:02+0000
action=shutdown created=2017-10-26T01:06:58+0000 ephemeral=false lvl=info msg="Shut down container" name=build-bot t=2017-10-26T01:34:04+0000 timeout=30s used=2017-10-26T01:07:02+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=build-bot t=2017-10-26T01:34:04+0000
lvl=info msg="Stopping REST API handler:" t=2017-10-26T01:34:04+0000
lvl=info msg=" - closing socket" socket=[::]:8443 t=2017-10-26T01:34:04+0000
lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/unix.socket t=2017-10-26T01:34:04+0000
lvl=info msg="Stopping /dev/lxd handler" t=2017-10-26T01:34:04+0000
lvl=info msg="Stopped /dev/lxd handler" t=2017-10-26T01:34:04+0000
lvl=info msg="Unmounting temporary filesystems" t=2017-10-26T01:34:04+0000
lvl=info msg="Done unmounting temporary filesystems" t=2017-10-26T01:34:04+0000
lvl=info msg="Closing the database" t=2017-10-26T01:34:04+0000
lvl=info msg="Saving simplestreams cache" t=2017-10-26T01:34:04+0000
lvl=info msg="Saved simplestreams cache" t=2017-10-26T01:34:04+0000
lvl=info msg="LXD 2.19 is starting in normal mode" path=/var/snap/lxd/common/lxd t=2017-10-26T11:11:37+0000
lvl=warn msg="AppArmor support has been disabled because of lack of kernel support" t=2017-10-26T11:11:37+0000
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-10-26T11:11:37+0000
lvl=info msg="Kernel uid/gid map:" t=2017-10-26T11:11:37+0000
lvl=info msg=" - u 0 0 4294967295" t=2017-10-26T11:11:37+0000
lvl=info msg=" - g 0 0 4294967295" t=2017-10-26T11:11:37+0000
lvl=info msg="Configured LXD uid/gid map:" t=2017-10-26T11:11:37+0000
lvl=info msg=" - u 0 1000000 1000000000" t=2017-10-26T11:11:37+0000
lvl=info msg=" - g 0 1000000 1000000000" t=2017-10-26T11:11:37+0000
lvl=info msg="Expiring log files" t=2017-10-26T11:11:37+0000
lvl=info msg="Done expiring log files" t=2017-10-26T11:11:37+0000
lvl=info msg="Starting /dev/lxd handler" t=2017-10-26T11:11:37+0000
lvl=info msg="LXD isn't socket activated" t=2017-10-26T11:11:37+0000
lvl=info msg="REST API daemon:" t=2017-10-26T11:11:37+0000
lvl=info msg=" - binding Unix socket" socket=/var/snap/lxd/common/lxd/unix.socket t=2017-10-26T11:11:37+0000
lvl=info msg=" - binding TCP socket" socket=[::]:8443 t=2017-10-26T11:11:37+0000
lvl=info msg="Pruning expired images" t=2017-10-26T11:11:37+0000
lvl=info msg="Done pruning expired images" t=2017-10-26T11:11:37+0000
lvl=info msg="Updating images" t=2017-10-26T11:11:37+0000
lvl=info msg="Updating instance types" t=2017-10-26T11:11:37+0000
lvl=info msg="Done updating images" t=2017-10-26T11:11:39+0000
lvl=info msg="Done updating instance types" t=2017-10-26T11:11:40+0000
lvl=eror msg="Failed to mount ZFS dataset \"default/containers/build-bot\" onto \"/var/snap/lxd/common/lxd/storage-pools/default/containers/build-bot\"." t=2017-10-26T11:11:47+0000
lvl=eror msg="Failed to mount ZFS dataset \"default/containers/build-bot\" onto \"/var/snap/lxd/common/lxd/storage-pools/default/containers/build-bot\"." t=2017-10-26T11:18:09+0000
lvl=eror msg="Failed to mount ZFS dataset \"default/containers/build-bot\" onto \"/var/snap/lxd/common/lxd/storage-pools/default/containers/build-bot\"." t=2017-10-26T11:22:14+0000

**Comment by RevoluPowered** [comment]
I think ZFS is acting up.

systemctl restart zfs-import-cache
systemctl restart zfs-import-scan
systemctl restart zfs-mount
systemctl restart zfs-share

Lets me start the container.

Source: https://unix.stackexchange.com/questions/383566/install-zfs-on-debian-9-stretch

**Comment by RevoluPowered** [comment]
Is this a bug with LXD or my configuration of ZFS?

**Comment by stgraber** [comment]
That may be an issue with the snap, can you show "lxc storage list" and the output of "lxc storage show" for any entry in that list?

**Comment by RevoluPowered** [comment]
**Here is the output of both commands:**
lxc storage show default
config:
  source: default
  volatile.initial_source: /dev/sda1
  zfs.pool_name: default
description: ""
name: default
driver: zfs
**used_by:**
- /1.0/containers/build-bot
- /1.0/containers/levmp-login
- /1.0/images/21fae0325d00b6077fac9b399ecb9a5b59c88da4f96750ee61da2b9842339d43
- /1.0/profiles/default

**lxc storage list**
|  NAME   | DESCRIPTION | DRIVER | SOURCE  | USED BY |
| default |             zfs    |default  4       

May have been just a glitch from me reinstalling; I reinstalled this computer, might have been on the older snap. Will try rebooting to see if this has already been fixed in edge.


`

**Comment by RevoluPowered** [comment]
Okay, after reboot and double checking I'm on the right version the same issue occurs.

**Comment by stgraber** [comment]
@RevoluPowered just to confirm, if you run "zpool import default" then things work, right?

**Comment by RevoluPowered** [comment]
Yep, confirmed that it does!

Weird.

**Comment by evgkarasev** [comment]
Bumped with the same problem causing CDK cluster breaking. It is related to https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/357.

The workaround is to run "zpool import default" after reboot then CDK cluster starts.

**Comment by RevoluPowered** [comment]
I considered it may be the way I'm making my ZFS pool. I didn't really know what I was doing when relocating it to sda1 so it could potentially be unrelated to your issue.

I'm new to ZFS but been using linux for quite a while now.

**Comment by RevoluPowered** [comment]
@evgkarasev what are you using for your ZFS packages? I'm using spl-dkms zfs-dpks and intramfs-zfs

**Comment by RevoluPowered** [comment]
@stgraber I think your command line fixed mine permanently. 

Both chroot's started properly after a reboot

**Comment by stgraber** [comment]
Yeah, I'd expect running "zpool import NAME" from outside the snap environment would be enough to update the zpool cache file with the information, making it come back online after reboot.

I suspect we'll want LXD to attempt a simple "zpool import NAME" if it can't find the zpool on startup, that should take care of this problem for everyone else.

**Comment by brauner** [comment]
@stgraber, `LXD` already tries an import on startup.

**Comment by brauner** [comment]
We can make it unconditional meaning that it also tries to import pools that are not loop-backed.

**Comment by RevoluPowered** [comment]
Closing this now since the PR is now created. 

Again, thank you @stgraber, @brauner and everyone who contributes, this is my favourite tool which I now use, it's hassle free and normally just works!
