### ISSUE TITLE
Add new device type "infiniband"

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3983]
This is similar to `nictype=sr-iov`. Although infiniband will be a separate device type.

**Comment by stgraber** [comment]
Test system is lantea.maas.mtl.

System comes with a Mellanox ConnectX-3 card with two ports, each capable of running in either IB or ETH mode. Right now, those are configured in IB mode.

SR-IOV on Mellanox card requires firmware configuration. This particular card has been configured with SR-IOV enabled in firmware and each port runs 31 functions, making a total of 64 functions on the card.
We will need some way to track down the port from the parent device and then look for a VF on the same port.

Setup on a clean Ubuntu 16.04 looks like:
 - rmmod mlx4_eth
 - modprobe mlx4_core probe_vf=31 num_vfs=31 port_type_array=1
   This sets up teh maximum 31 functions, tie them all to the host driver and run them all in IB mode.

To get the ibX devices, we need IPoIB to be setup:
 - modprobe ib_ipoib

And then to get the char devices needed for RDMA communication:
 - modprobe ib_uverbs

At which point, you should get 64 ib network devices and 32 uverbs device in /dev/infiniband.

**Comment by stgraber** [comment]
Looks like we also should load "ib_umad".

The current result looks like:
 - One ibX device per function and per port
 - One issmX char device per function and per port
 - One umadX char device per function and per port
 - One uverbsX char device per function

I'm yet to find a reliable way to link an ibX device to a particular port. Finding what function it belongs to is easy though (same as for ethernet).

**Comment by brauner** [comment]
I'm gonna expand on some of the stuff a little bit as this is otherwise quite cryptic:

- `modprobe mlx4_core probe_vf=31 num_vfs=31 port_type_array=1`
   - `num_vfs`
      The number of virtual functions (VF) to set up. In this case we use the maximum of `31`VFs.
   -  `probe_vf`:
       The number of VFs to bind to the core device in `/sys/fs/infiniband/<mlx>_core/`.
       This is a slightly tricky concept. Say you request `31` VFs and you also request `probe_vf` for all `31` VFs. Then you will create `64` devices that will show up when you run `ip addr`. Since the card has two ports each sequentially ordered, non-overlapping tuple `{<0,1>, <2,3>, ..., <63,64>}` of those `64` VFs will be bound to a port in `/sys/class/infiniband/<mlx>_{1, ..., 31}`. A pairing would look like this:
       ```
       mlx4_0 port 1 -> ib0
       mlx4_0 port 2 -> ib1
 
       mlx4_1 port 1 -> ib2
       mlx4_1 port 2 -> ib3
       ```
   - `port_type_array`: The type of port to use. The way this is specified here relies on the IB being the default for that card. It should probably be `port_type_array=1,1`. This instructs that each both ports for each `mlx>_{1, ..., 31}` are set to `IB`.

**Comment by brauner** [comment]
Naming the properties nice and generically will be interesting. Here's a first pass sticking close to the terminology we use for type `nic` devices:

### Type: infiniband

The following properties:

Key         | Type      | Default           | Required  | Description
:--         | :--       | :--               | :--       | :--
parent | string | - | ? | name or PCI address of the PF
vendorid    | string    | -                 | no        | The vendor id of the infiniband device.
productid   | string    | -                 | no        | The product id of the infiniband device.
name | string | - | no | name of the VF inside the container
host_name | string | - | no | name or PCI address of the VF on the host
mac | string | - | no | MAC address to assign to the VF inside the container
mtu | string | - | no | MTU value to assign to VF can only be <= the MTU of the PF

Command line expectations:

- pass through all VFs of all PFs
    ```
    lxc config device add <container-name> <device-name> infiniband
    ```
- pass through all VFs of a specific PF
    ```
    lxc config device add <container-name> <device-name> infiniband parent=<PF>
    ```
- pass through a specific VF of a specific PF
    ```
    lxc config device add <container-name> <device-name> infiniband parent=<PF> host_name=<VF>
    ```
  This should always require both `parent` and `host_name` to be set
- pass through a specific VF of a specific PF with a specific name
  ```
    lxc config device add <container-name> <device-name> infiniband parent=<PF> host_name=<VF> name=<name>
  ```
   This should always require both `parent` and `host_name` to be set

**Comment by stgraber** [comment]
mac should be hwaddr and we'll need a nictype property too

**Comment by stgraber** [comment]
nictype would either be physical (entire device) or sriov (vf)

**Comment by stgraber** [comment]
I don't think using host_name makes sense as a way to specify a vf, at that point the user could just set parent to the vf they want and use nictype=physical

**Comment by stgraber** [comment]
I'm not sure that we need vendorid, productid or pciid at this point. Users can use the parent property to point to the infiniband NIC they want based on interface name.

**Comment by brauner** [comment]
If we remove all of those properties. Wouldn't it make more sense to just have this be an additional nictype.

**Comment by brauner** [comment]
Also, please edit the table and remove/add the properties you don't want/want. :)

**Comment by stgraber** [comment]
No because we do have physical vs sriov and infiniband does more than just pass a nic device, it also passes the /dev/infiniband devices and updates the cgroup limits in the process.

**Comment by brauner** [comment]
Automatically? (the cgroup limits?

**Comment by stgraber** [comment]
table updated

**Comment by stgraber** [comment]
The part that'll be a bit tricky is to find the right port to use.

For example if I say "nictype=sriov parent=ib1 name=ib0" I expect to get a network device called ib0 which is connected to one of the 31 VFs and on the second port (to match the port of ib1).
Then we'll need to also track down the various /dev/infiniband devices that are associated to that VFs (for the ones that aren't port-specific) and to the port (for those that are).

**Comment by brauner** [comment]
Well, if we need it that elaborate then we can't make parsing cheap anyway so I won't worry about this now.

**Comment by stgraber** [comment]
Optional modules leading to more files:

 - ib_umad
 - ib_ucm
 - ib_cm
 - ib_sa

**Comment by brauner** [comment]
Some more thoughts:

#### Adding Network Devices (Hot Plug)

When an infiniband physical (PF) or virtual (VF) function is plugged into the
container LXD will also opportunistically add all device nodes associated with
that infiniband device.
These devices nodes could either be added implicitly, i.e. they would not appear
as separate devices in the container's config or explicitly, i.e. they would
appear as separate devices in the container's config.
The latter approach is more in line with viewing those devices as being somewhat
independent from the {P,V}F itself and is probably nicer when users look at the
config and see all of the devices the container currently has plugged in. But it
might also confuse them when there suddenly are devices they didn't add
explicitly.

#### Removing Network Devices (Hot Removal)

Since LXD when adding an infiniband {P,V}F function into a container will also
opportunistically add all device nodes associated with this {P,V}F we need to
find a reliable way to remove those device nodes when the associated {P,V}F is
removed from the container.
- The only reliable way I can think of right now is to record those devices in a
  volatile keys:
  - `volatile.<name>.devices`
  which would be a simple list with all the devices that were plugged into the
  container.
  On device removal we can check whether any of the other still plugged in
  infiniband devices is using this device node and if not, remove it.

**Comment by stgraber** [comment]
I think we should have this behave the same way we do for GPU, so have it happen implicitly.
The alternative would cause LXD to add a bunch of devices for you automatically in your config which would be a mess to support when factoring in profiles and would also be rather surprising to the user.

For the removal case, we can do the config trick or an alternative would be to start encoding the LXD device name in /var/lib/lxd/devices/CONTAINER/. Probably then making one directory per device name under there and store all devices related to the device in there.

That would allow us to reliably remove all devices from the container for all device types that use this (unix-char, unix-block, usb, gpu and infiniband) and would save us from another volatile key (database is going to become costly to write to soon and users can unset volatile keys by accident).

**Comment by brauner** [comment]
> For the removal case, we can do the config trick or an alternative would be to start encoding the LXD device name in /var/lib/lxd/devices/CONTAINER/. Probably then making one directory per device name under there and store all devices related to the device in there.

I think it's easier if we simply encode the device name into the device path. Having a single device with multiple device nodes is not a very common case.

**Comment by brauner** [comment]
@stgraber, I'm currently reworking the device handling the way I outlined above so a quick ack from your side would be nice. :)

**Comment by stgraber** [comment]
Sure, that's fine. I first though of doing that but then figured that if we were using directories, it'd simplify detection of the old vs new way of storing those devices and so simplify our upgrade logic a bit.

**Comment by brauner** [comment]
> Sure, that's fine. I first though of doing that but then figured that if we were using directories, it'd simplify detection of the old vs new way of storing those devices and so simplify our upgrade logic a bit.

My first pass that this started with a directory but that's more internal churn than just plain `mknod()`ing and `unlink()`ing the device file. I don't know right now you can simply create the old-device style path and call `shared.PathExists()` and then handle and create the new-device style path when creating new ones.
