### ISSUE TITLE
remote {copy,move} custom storage volumes

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#3985]
- remote {copy, move} custom storage volume between LXD instances

**Comment by brauner** [comment]
It looks like we need a moderately big rewrite of the migration code to accommodate not just containers but also volumes? Or did you have something else in mind?

**Comment by stgraber** [comment]
@brauner I'm not sure that we do, the protobuf protocol should actually work pretty well for volumes, especially when you consider that we'll want custom volume snapshots in the future and may also end up with idmap handling for custom volumes once shiftfs becomes a thing.

**Comment by stgraber** [comment]
So the migration protocol with its backend detection logic and data should be fine.

**Comment by stgraber** [comment]
API wise, I expect we'll do the usual two set of APIs:

 - POST /1.0/storage-pools/POOL/volumes/VOLUME => If pull mode, return websockets, if push mode, provide target information
 - POST /1.0/storage-pools/POOL/volumes => If pull mode, provide source information, if push mode, return websockets

So pretty much a repeat of what we have for containers with the same way of defining a remote host (Mode, Operation, Websockets and Certificate).

**Comment by brauner** [comment]
My point about the moderately big rewrite was that currently the whole logic in `migrate.go` is centered around containers and the setup functions are centered around containers.
