### ISSUE TITLE
ZFS pool creation and Addition Breaking on Alpine Linux

### ISSUE THREAD

**Issue by zacksiri** [lxc/lxd#3986]
# Required information

 * Distribution: Alpine Linux
 * Distribution version: edge
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux builder 4.9.58-0-hardened
   * LXC version: 2.1.0
   * LXD version: 2.19
   * Storage backend in use: zfs 0.7.3

# Issue description

When I run `lxd init` I'm getting the error 

```
error: cannot open '-H': dataset does not exist
```

Seems like lxd is issuing command in the wrong order, if I issue the command in the shell manually everything works but when i try the command from here:

https://github.com/lxc/lxd/blob/693df2ceddd3287ff1d5bcefea848259899f8151/lxd/storage_zfs_utils.go

# Steps to reproduce

 1. Setup LXD and ZFS on alpine
 2. run `lxd init`
 3. Go through the interactive shell

**Comment by brauner** [comment]
@zacksiri, what is the exact command?

**Comment by zacksiri** [comment]
When I run lxd init it ask me for the name of the pool I type the name of the pool and at the end of the init I get the above error

**Comment by brauner** [comment]
What's the name of the pool you're giving? And what did you mean by

> f I issue the command in the shell manually everything works but when i try the command from here

**Comment by zacksiri** [comment]
If I do 
```
zpool create -f -o ashift=12 lxd /dev/vdb 
```

Zfs pool created, with the name lxd, I then pass this pool called `lxd` into the init process and I get the error.

If I let lxd create the pool by passing the block device (ie I don’t create the pool I just pass /dev/vdb) i also get an error.

**Comment by brauner** [comment]
Can you try `zpool create lxd /dev/vdb  -f -o ashift=12`

**Comment by zacksiri** [comment]
<img width="423" alt="screen shot 2560-10-31 at 11 25 37" src="https://user-images.githubusercontent.com/134488/32207403-3e23bbda-be2e-11e7-8ac8-00501a66efd5.png">

**Comment by zacksiri** [comment]
@brauner anything I can do to help resolving this one?

**Comment by stgraber** [comment]
I'll take this one.

**Comment by stgraber** [comment]
Looks like only the zpool command is imported, so the fix is pretty simple.
I got a clean test run on a system that I manually upgraded to the latest zfs.
