### ISSUE TITLE
nfs-kernel-server not starting..

### ISSUE THREAD

**Issue by juanquy** [lxc/lxd#3989]
Hi: trying to run nfs-kernel-server and I got this issue
I tried to edit the config file of that container to add this line :
...
raw.apparmor : mount fstype=rpc_pipefs,

but already I have this line 
...
raw.apparmor: mount fstype=nfsd,

how I can edit the config file in order to add that line : raw.apparmor : mount fstype=rpc_pipefs,

regards
JC

# Required information

 * Distribution: Ubuntu Server
 * Distribution version: 16.04 
 * The output of "lxc info" or if that fails:

 * Kernel version:  Linux fog-server 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

 sdsadmin@lxd-server:~$ lxc info
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 192.168.10.220:8443
  - '[2607:6300:96:1:483d:6f22:e88b:1cf7]:8443'
  - '[2607:6300:96:1:5cdd:d1e8:f51a:214a]:8443'
  - '[2607:6300:96:1:55f5:7a78:7d9e:efb5]:8443'
  - '[2607:6300:96:1:226:b9ff:fe38:5295]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
  certificate_fingerprint: d814973b655312f1198d08bc9c626b7370ffc3bc692b818abd9d7036210624a7
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-97-generic
  server: lxd
  server_pid: 2953
  server_version: "2.18"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu16
 
   * LXC version:2.0.10
   * LXD version:2.0.10
   * Storage backend in use:zfs
======================================================
# Issue description
nfs-kernel-server not starting :
.....
journalctl -xe
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nfs-idmapd.service has failed.
-- 
-- The result is dependency.
Oct 30 18:31:56 fog-server systemd[1]: nfs-idmapd.service: Job nfs-idmapd.servic
Oct 30 18:31:56 fog-server systemd[1]: nfs-server.service: Job nfs-server.servic
Oct 30 18:31:56 fog-server systemd[1]: nfs-mountd.service: Job nfs-mountd.servic
Oct 30 18:31:56 fog-server systemd[1]: proc-fs-nfsd.mount: Unit entered failed s
Oct 30 18:31:56 fog-server systemd[1]: Failed to mount RPC Pipe File System.
-- Subject: Unit run-rpc_pipefs.mount has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit run-rpc_pipefs.mount has failed.
-- 
-- The result is failed.
Oct 30 18:31:56 fog-server systemd[1]: Dependency failed for RPC security servic
-- Subject: Unit rpc-svcgssd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit rpc-svcgssd.service has failed.
-- 
-- The result is dependency.
Oct 30 18:31:56 fog-server systemd[1]: rpc-svcgssd.service: Job rpc-svcgssd.serv
Oct 30 18:31:56 fog-server systemd[1]: Dependency failed for RPC security servic
-- Subject: Unit rpc-gssd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit rpc-gssd.service has failed.
-- 
-- The result is dependency.
Oct 30 18:31:56 fog-server systemd[1]: rpc-gssd.service: Job rpc-gssd.service/st
Oct 30 18:31:56 fog-server systemd[1]: run-rpc_pipefs.mount: Unit entered failed

.....
$ systemctl list-dependencies nfs-kernel-server
nfs-kernel-server.service
● ├─auth-rpcgss-module.service
● ├─nfs-config.service
● ├─nfs-idmapd.service
● ├─nfs-mountd.service
● ├─proc-fs-nfsd.mount
● ├─rpc-svcgssd.service
● ├─rpcbind.socket
● ├─system.slice
● └─network.target

**Comment by stgraber** [comment]
Just tested here:

```
lxc launch ubuntu:16.04 nfs -c security.privileged=true -c raw.apparmor="mount fstype=rpc_pipefs, mount fstype=nfsd,"
```

I can tell install nfs-kernel-server just fine and services appear to start properly.

**Comment by juanquy** [comment]
Thank you that work. !!!
