### ISSUE TITLE
ecryptfs: unable to create mount in unprivileged container

### ISSUE THREAD

**Issue by iam-TJ** [lxc/lxd#3990]
On Ubuntu 16.04.3 amd64, with a 17.10  (unprivileged) container, it is not possible to create an ecryptfs mount within the container.

root@sourcecode-u1710:~/overlayfs# mount -t ecryptfs /srv /srv
Exiting. Unable to obtain passwd info

This appears due to ecryptfs-utils as noted in a comment by naisanza in issue #2118 at
https://github.com/lxc/lxd/issues/2118#issuecomment-236418431

**Comment by stgraber** [comment]
I think you're out of luck with unprivileged containers, at least until the ecryptfs upstream does some work to allow it.

I've confirmed that "ecryptfs-mount-private" works properly if:
 - The container is privileged (security.privileged=true)
 - You allow ecryptfs mounts (raw.apparmor="mount fstype=ecryptfs,")

Just allowing ecryptfs mounts in apparmor is enough to get you passed an initial permission denied error with an unprivileged container, but you then hit an operation not permitted error coming straight from the kernel.


I'm closing this issue as there's nothing that LXD can do about this, once the ecryptfs kernel code supports unprivileged mounting and the needed keyring operations can be done unprivileged, things should just start to work.
