### ISSUE TITLE
Add events API to the /dev/lxd interface

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3996]
Right now the /dev/lxd/socket interface as available inside the container only supports a rather limited REST API. This is documented in [doc/dev-lxd.md](https://github.com/lxc/lxd/blob/master/doc/dev-lxd.md)

One addition we've always planned on doing but never quite got around to is to add a /1.0/events endpoint.
This endpoint would have a structure similar to the main API /1.0/events (see [doc/rest-api.md](https://github.com/lxc/lxd/blob/master/doc/rest-api.md).

We'd support two message classes:
 - device (for new devices being passed or removed from the container)
 - config (for any change to a configuration key visible to the container)

This would use the same kind of handler we use for events, so be non-blocking on the LXD side and be a websocket based API.

**Comment by calhorn95** [comment]
I am also looking at this issue for my Virtualization project and have a few specification questions.  

If I am understanding the code correctuly, the rather limited REST API that is already supported is setup in devlxd.go.  I understand that two message classes are wanted for devices and configs, so that the REST API can continuously receive information regarding changes to device and configs. 

Is there a GO file where API for /1.0/events is already implemented? (as a resource)

Also, please let me know if there are any additional specifications that are wanted for this interface.

**Comment by stgraber** [comment]
Right, so the goal is to implement /1.0/events as a websocket endpoint on the devlxd socket.

This is going to use a structure that's very similar to the global /1.0/events so you'll want to look at:

https://github.com/lxc/lxd/blob/master/lxd/events.go

The main difference will be that the listeners will be tracked per-container and initially the expected message format is going to look like:

```yaml
type: config
timestamp: <TIMESTAMP>
key: user.XYZ
value: blah

type: device
action: added
device:
  type: nic
  name: eth0

type: device
action: updated
device:
  type: nic
  name: eth0

type: device
action: removed
device:
  type: unix-char
  path: /dev/kvm
```

As far as setting this up, I suspect the easiest will be to:
 1. Add the new API endpoint and write a small test client
 1. Write wrapper functions to send events for a specific container
 1. Add calls to those functions in container_lxc.go where things matter

I'd suggest starting to integrate the config bits as for those you pretty much have a single spot to integrate with, that's the Update() function in container_lxc.go and I'd say that the right time to send the notification would be right after a successful database update.

https://github.com/lxc/lxd/blob/master/lxd/container_lxc.go#L4166

**Comment by stgraber** [comment]
The hidden `lxc monitor` command in our command line tool is an example of a pretty minimal client for that kind of events API.

**Comment by calhorn95** [comment]
For this, I am looking at  devlxd.go, which seems to be where the devLxdHandler is setup for the different Rest API calls that can be used with the /dev/lxd socket that is created within each container.  Do I need to add to this file to handle the updated Rest API calls that are being added for device and config changes?

**Comment by stgraber** [comment]
Yes, that's correct. devlxd.go is where we do all the handling for the /dev/lxd socket.

You'll want to add a new devLxdHandler for /1.0/events. That handler will then look very similar to eventsSocket (in lxd/events.go), with "config" and "device" being the two initial event types.

**Comment by calhorn95** [comment]
Ok that makes sens and I will also want to create a method similar to eventSend() as well that can be called in the Update() function of container_lxc.go which will send the updates to the devlxd event socket?

**Comment by stgraber** [comment]
Yep, the main difference will be that unlike the existing events API, the devlxd one will be container specific. So you'll need to keep track of listeners on a per-container basis and have the devlxdEventSend function (or whatever it ends up being called) take the container id as an argument.

**Comment by calhorn95** [comment]
Would you recommend writing it such that the eventListeners being create in the eventDevLxdSocket() function are given an id that matches a particular container id and then in the devlxdEventSend() function, which will take container id as an argument, the eventListener that is needed can be found by comparing the container id argument and the id of the listener to find the correct socket to send the eventMessage to?

**Comment by stgraber** [comment]
Yeah, I think devlxdEventListeners should be:

    map[int64][]map[string]*eventListener

Or something along those lines, giving us an easy way to grab all the listeners for a particular container and then iterate over them to send the message (checking whether they're subscribed to that message type at this point).

**Comment by calhorn95** [comment]
I am looking through where the eventSocket() is setup for events and I seem to see that it is being setup  in daemon.go with calls to Render(w).  Would the devlxdEventSocket() be setup once the check for the config security.devlxd key has been checked for true?  I understand that the devlxdEventsSend() will happen in the Update() function in container_lxc.go, but I am confused about when to setup the orignal socket.  Thanks in advance.

**Comment by stgraber** [comment]
You shouldn't have to setup anything, it's a global socket that's passed into every container. We then have logic to figure out what container a particular request came from based on its pid.

**Comment by stgraber** [comment]
I just pushed this commit to my branch which cleans up some bits of devlxd to make your life easier:
https://github.com/lxc/lxd/pull/4079/commits/2976cbde3f3350918becc11edafe39d6551ff639

On top of that, you can then do something like this:
```diff
index b1cb16ea..d54c401a 100644
--- a/lxd/devlxd.go
+++ b/lxd/devlxd.go
@@ -14,6 +14,7 @@ import (
        "unsafe"
 
        "github.com/gorilla/mux"
+       "github.com/pborman/uuid"
 
        "github.com/lxc/lxd/lxd/db"
        "github.com/lxc/lxd/lxd/util"
@@ -82,6 +83,23 @@ var devlxdMetadataGet = devLxdHandler{"/1.0/meta-data", func(c container, w http
        return okResponse(fmt.Sprintf("#cloud-config\ninstance-id: %s\nlocal-hostname: %s\n%s", c.Name(), c.Name(), value), "raw")
 }}
 
+var devlxdEventsGet = devLxdHandler{"/1.0/events", func(c container, w http.ResponseWriter, r *http.Request) *devLxdResponse {
+       typeStr := r.FormValue("type")
+       if typeStr == "" {
+               typeStr = "config,device"
+       }
+
+       _, err := shared.WebsocketUpgrader.Upgrade(w, r, nil)
+       if err != nil {
+               return &devLxdResponse{"internal server error", http.StatusInternalServerError, "raw"}
+       }
+
+       id := uuid.NewRandom().String()
+       logger.Debugf("New events listener for %s: %s", c.Name(), id)
+
+       return &devLxdResponse{"websocket", http.StatusOK, "websocket"}
+}}
+
 var handlers = []devLxdHandler{
        {"/", func(c container, w http.ResponseWriter, r *http.Request) *devLxdResponse {
                return okResponse([]string{"/1.0"}, "json")
@@ -92,6 +110,7 @@ var handlers = []devLxdHandler{
        devlxdConfigGet,
        devlxdConfigKeyGet,
        devlxdMetadataGet,
+       devlxdEventsGet,
 }
 
 func hoistReq(f func(container, http.ResponseWriter, *http.Request) *devLxdResponse, d *Daemon) func(http.ResponseWriter, *http.Request) {
```

**Comment by stgraber** [comment]
This adds /1.0/events to the devlxd API, picks up the type from the URL and upgrades the connection to websocket then log a message.

That's obviously missing all of the connection tracking and message sending code, but that should take care of the plumbing that's needed to let you connect from a container.

**Comment by calhorn95** [comment]
The eventListener initialization should also take place within /1.0/3events as well.  Correct?

**Comment by stgraber** [comment]
yeah, I don't have it in the code above because it was a quick example but yes, you'd setup eventListener in there or possibly a new devlxdEventListener struct if we can't recycle the existing one somehow.

**Comment by calhorn95** [comment]
I am running into some problems on how to test the code that I have written  for this.  I am confused about how to use the devlxd socket when in the container.  Would you mind explaining that briefly to me?

**Comment by stgraber** [comment]
For normal endpoints, you can just do something like this:

    curl --unix-socket /dev/lxd/sock lxd/1.0

**Comment by stgraber** [comment]
For websocket, short of writing a small Go client, you should be able to do it with:
```
curl -H 'Connection: Upgrade' -H 'Upgrade: websocket' -H 'Sec-WebSocket-Version: 13' -H 'Sec-WebSocket-Key: lxd' --no-buffer --output - --unix-socket /dev/lxd/sock lxd/1.0/events
```

But note that the output will be a bit messed up due to websocket being a partly binary protocol.

**Comment by calhorn95** [comment]
Ok.  When I am doing this, I keep seeing "curl: (7) Couldn't connect to server".

**Comment by stgraber** [comment]
You're running this from inside the container with a LXD that supports the /1.0/events endpoint on the devlxd API?

**Comment by calhorn95** [comment]
I figured out my issue for that.  Thank you.

**Comment by stgraber** [comment]
@calhorn95 hey there, have you made some progress on this? Do you still expect to complete this work?

**Comment by calhorn95** [comment]
I have not made much progress on this and am not seeing anytime in the near
future to do some work on this.

**Comment by stgraber** [comment]
Thanks for the update. I'll be taking over this then as we were planning to integrate this by mid-January.

**Comment by stgraber** [comment]
Got the config part of this working:
```
root@snapcraft:~# curl -H 'Connection: Upgrade' -H 'Upgrade: websocket' -H 'Sec-WebSocket-Version: 13' -H 'Sec-WebSocket-Key: lxd' --no-buffer --output - --unix-socket /dev/lxd/sock lxd/1.0/events
�~�{"metadata":{"key":"user.blah","new_value":"foo","old_value":""},"timestamp":"2017-12-21T16:15:49.232696553-05:00","type":"config"}
�~�{"metadata":{"key":"user.blah","new_value":"bar","old_value":"foo"},"timestamp":"2017-12-21T16:15:55.505273421-05:00","type":"config"}
�~�{"metadata":{"key":"user.blah","new_value":"","old_value":"bar"},"timestamp":"2017-12-21T16:16:01.582006995-05:00","type":"config"}
```

**Comment by stgraber** [comment]
Now to hook into the device management code.
