### ISSUE TITLE
Introduce a new security.devlxd key to control visibility of /dev/lxd inside the container

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#3997]
Title says it all, we have environments in which any communication channel between guest and host is unacceptable. For LXD, the only such channel is the /dev/lxd interface, so we should add a configuration knob for it so that users can turn it off.

**Comment by Roosterfish** [comment]
I would definitely appreciate this feature.

**Comment by calhorn95** [comment]
Hello I (Chris Loper) am a part of the Virtualization class that a bunch of other new contributors on here are from.  I am interested in looking into this issue and have a few questions to clarify what this feature entails.

When you are talking about the /dev/lxd interface are you talking about the devlxd.go file?  (I am a little confused what you mean by this interface)

And when you are talking about visibility inside the container, are you talking about the host's visibility of the container or the container's visibility of the host? 

Thank you.

**Comment by stgraber** [comment]
devlxd.go implements a web server serving a very limited REST API that can be accessed from inside the container at /dev/lxd/socket.

The actual setup of that path in the container is done in container_lxc.go.

This configuration option will allow to turn off that file on a per container basis.

**Comment by stgraber** [comment]
I'm on my phone right now, I'll give some code pointers when I'm back on my laptop.

**Comment by calhorn95** [comment]
Sounds good.  Thank you very much.

**Comment by stgraber** [comment]
This is what sets up /dev/lxd/ in the container and what should be skipped if security.devlxd is set to false:
https://github.com/lxc/lxd/blob/master/lxd/container_lxc.go#L1034

When adding such a config key, you'll need to at least do:

 - Update doc/containers.md
 - Update doc/api-extension.md adding a new "restrict_devlxd" extension explaining that this introduces a new config key called security.devlxd
 - Update shared/version/api.go to add that same "restrict_devlxd" extension to the list
 - Update the config validation function in shared/container.go to know about the new config key
 - Update the bash completion script in config/bash/lxd-client for the new key

That's on top of the actual code change which would initially be about just adding a check to the bit of code I pointed to above. Then once that all works, we'll want to also add code to the Update() function in the same file to allow making this change dynamically, but I'll have to look a bit more into this before I can give you pointers for that part.

**Comment by calhorn95** [comment]
Thank you very much for the detailed specification.  That really helps to get us started.

**Comment by calhorn95** [comment]
Should the default value of security.devlxd be set to true so that /dev/lxd/ is setup in the container by default?  Thank you.

**Comment by stgraber** [comment]
Yeah, it should be true by default so that we keep the current behavior by default.

**Comment by calhorn95** [comment]
When I am trying to run lxd from source I am running into a problem when I am trying to launch a container.   I am getting an error after the "starting container" message appears that looks like this: "error: Put http://unix.socket/1.0/containers/immune-sheep/state: EOF".  I am wondering if you have any idea what this could be.  I do not think this problem is related to the testing of the implementation of this issue as i have this problem when I remove all of my changes.  Thank you in advance for any help.

**Comment by stgraber** [comment]
What does the server side show?

Here I usually have one window running "lxd --debug --group lxd" for the server and then another one where I run the client. Most interesting errors/crash are likely to show up on the server side.

**Comment by calhorn95** [comment]
When I run that command, I keep getting an error that says that "error: LXD is already running.".  I am not sure how to stop it.

**Comment by stgraber** [comment]
For anyone running in the same situation, you need to make sure the system wide LXD is off first `systemctl stop lxd.service lxd.socket` should do the trick.

**Comment by calhorn95** [comment]
For this do you just want this security option to be condifured when launching a container like this: "lxc launch ubuntu:16.04 first -c security.devlxd=false"?  Thanks.

**Comment by stgraber** [comment]
Yeah, it's going to be a standard LXD config key, so it can be set through a profile or overriden at launch with the "-c" argument or be set later on through "lxc config set" or "lxc config edit".

**Comment by stgraber** [comment]
This has been done
