### ISSUE TITLE
Tunnel MTU > 1400

### ISSUE THREAD

**Issue by Roosterfish** [lxc/lxd#3999]
Hello,

When creating a new network with LXD, the max allowed value for bridge.mtu is 1400.
How can I circumvent this to be able to set a VXLAN MTU greater than 1400? 

The MTU of the physical NIC is already configured properly. With LXC this isn't a problem at all. 

Might it be possible to extend this check ([View code](https://github.com/lxc/lxd/blob/master/lxd/networks_config.go): Line 179) with a test of the actual MTU of the selected tunnel.$.interface in order to see if the bridge.mtu setting would be valid?
Or did I miss the real intention of this check? 

Cheers

**Comment by stgraber** [comment]
Not sure why I put that check in there as deployments that do have a working jumbo frames setup can indeed exceed that MTU safely. Doing an actual check for the underlying devices would be pretty tricky though, so the easiest may be to just remove the check.
