### ISSUE TITLE
lxcfs restarted on update rather than reloaded

### ISSUE THREAD

**Issue by cryptofuture** [lxc/lxd#4009]
`Cannot open /proc/stat: Transport endpoint is not connected` in some containers, access available after container restart, I couldn't reproduce on another lxd hosts (but thats could be due over 100 days uptime with canonical-livepatch on production hosts), all auto-updated to lxcfs from proposed (2.0.8-0ubuntu1~16.04.1), but using `http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu xenial main`, mb thats the issue.

```
Ubuntu 16.04.x
 driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-16-generic
  server: lxd
  server_pid: 10127
  server_version: "2.18"
  storage: btrfs
  storage_version: "4.4"
```
```
lxc 20171108064943.490 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171108064943.490 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171108064943.983 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171108064943.983 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171108092826.172 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171108092826.230 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171108092826.230 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171108092826.354 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171108092826.354 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
```

**Comment by brauner** [comment]
This is very likely a `lxcfs` problem. Can you show `systemctl status lxcfs` and `lxcfs --version`, please?

**Comment by cryptofuture** [comment]
`2.0.8-0ubuntu1~16.04.1`
`
● lxcfs.service - FUSE filesystem for LXC
   Loaded: loaded (/lib/systemd/system/lxcfs.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-11-08 06:53:18 UTC; 3h 2min ago
     Docs: man:lxcfs(1)
  Process: 10087 ExecStopPost=/bin/fusermount -u /var/lib/lxcfs (code=exited, status=0/SUCCESS)
 Main PID: 10109 (lxcfs)
    Tasks: 5
   Memory: 3.3M
      CPU: 23ms
   CGroup: /system.slice/lxcfs.service
           └─10109 /usr/bin/lxcfs /var/lib/lxcfs/

Nov 08 06:53:18 lxcfs[10109]:   2: fd:   7: freezer
Nov 08 06:53:18 lxcfs[10109]:   3: fd:   8: perf_event
Nov 08 06:53:18 lxcfs[10109]:   4: fd:   9: rdma
Nov 08 06:53:18 lxcfs[10109]:   5: fd:  10: net_cls,net_prio
Nov 08 06:53:18 lxcfs[10109]:   6: fd:  11: pids
Nov 08 06:53:18 lxcfs[10109]:   7: fd:  12: cpu,cpuacct
Nov 08 06:53:18 lxcfs[10109]:   8: fd:  13: hugetlb
Nov 08 06:53:18 lxcfs[10109]:   9: fd:  14: cpuset
Nov 08 06:53:18 lxcfs[10109]:  10: fd:  15: blkio
Nov 08 06:53:18 lxcfs[10109]:  11: fd:  16: name=systemd
`
```
lxcfs --version
2.0.8
```

**Comment by brauner** [comment]
Hm, seems that somehow fuse got unmounted on one of the updates. If you can restart the container this should fix it.

**Comment by cryptofuture** [comment]
Just checked, and actually I have it on production lxd hosts too.
So yes https://launchpad.net/ubuntu/+source/lxcfs/2.0.8-0ubuntu1~16.04.1
This update didn't worked good for me.

**Comment by stgraber** [comment]
Uploaded a fix.
