### ISSUE TITLE
macOS and "LXD installed and running?" error

### ISSUE THREAD

**Issue by hipertracker** [lxc/lxd#4015]
On macOS High Sierra I have installed lxd using `brew install lxc`. I also installed it from source, just for comparison. But there is no difference. Every time I get the same error: "LXD socket not found; is LXD installed and running?"
```
$ lxc config show
LXD socket not found; is LXD installed and running?
```

```
$ lxc list
LXD socket not found; is LXD installed and running?
```

**Comment by stgraber** [comment]
That's perfectly normal. The daemon part of LXD can only run on Linux so installing the client on a mac without pointing it to a remote LXD server will fail.

    lxc remote add some-name https://<IP>
    lxc remote set-default some-name

**Comment by hipertracker** [comment]
So I cannot create a new container on macOS? :(

**Comment by stgraber** [comment]
Nope, you can only use the LXD client to talk to a LXD daemon running on a remote Linux server. That can be some server in the cloud or could be a Linux VM on your mac.

**Comment by stgraber** [comment]
MacOS itself doesn't have the concept of containers in its kernel.

**Comment by hipertracker** [comment]
OK. Thanks for the explanation.
