### ISSUE TITLE
`lxd file push` to print filenames in --verbose mode

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#4018]
```
$ lxc file push sync-*.sh rirror/root/
$ lxc file push sync-*.sh rirror/root/ --verbose
$ ls sync-*.sh
sync-apt.sh  sync-bugs.debian.org.sh  sync-packages.debian.org.sh
```
Was there anything copied?

# Required information

   * LXD version: 2.18

**Comment by stgraber** [comment]
Yeah, we could do that. We don't have much that's hooked to the verbose log level, most of it is in debug, which is probably much to verbose for this.

**Comment by techtonik** [comment]
@brauner thanks!
