### ISSUE TITLE
[MacOS] LXD socket not found; is LXD installed and running?

### ISSUE THREAD

**Issue by Fig-R** [lxc/lxd#4020]
Hello, 

* Distribution: MacOS
 * Distribution version: Hight Sierra 10.13.1

# Issue description

I have installed LXD with brew, then with build from source and when I type `lxc info --debug` I have

> DBUG[11-13|09:48:03] Connecting to a local LXD over a Unix socket
DBUG[11-13|09:48:03] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
LXD socket not found; is LXD installed and running?

I don't find any log file :x

Thanks

**Comment by brauner** [comment]
The `LXD` daemon itself (started by the `lxd` binary) cannot run natively on MacOS, only the client can.

**Comment by stgraber** [comment]
You're going to want to add a remote LXD server using "lxc remote add", then you can use "lxc remote set-default" to have all commands default to that remote server.
