### ISSUE TITLE
cloud-images.ubuntu.com fails to resolve in a fresh container

### ISSUE THREAD

**Issue by vilagithub** [lxc/lxd#4026]
# Required information

 * Distribution: ubuntu 
 * Distribution version: xenial
 * The output of "lxc info" or if that fails:
$ lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
   <snip>
   -----END CERTIFICATE-----
  certificate_fingerprint: <snip>
  driver: lxc
  driver_version: 2.1.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-98-generic
  server: lxd
  server_pid: 15747
  server_version: "2.19"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu16
   * Storage backend in use: zfs

# Issue description

Container creation inside a fresh container fails because the image can't be retrieved (more precisely, cloud-images.ubuntu.com can't be resolved).

Once 'dig cloud-images.ubuntu.com' is issued (returning a valid answer), the issue disappears.

# Steps to reproduce

$ lxc launch ubuntu:xenial/amd64 base
$ lxc stop base
$ lxc copy base test
$ lxc start test
$ lxc shell test
root@test:~# lxc image info ubuntu:xenial/amd64
lxc image info ubuntu:xenial/amd64
Generating a client certificate. This may take a minute...
If this is your first time using LXD, you should also run: sudo lxd init
To start your first container, try: lxc launch ubuntu:16.04

error: Get https://cloud-images.ubuntu.com/releases/streams/v1/index.json: lookup cloud-images.ubuntu.com on 10.242.247.1:53: read udp 10.242.247.225:34730->10.242.247.1:53: i/o timeout
root@test:~# lxc image info ubuntu:xenial/amd64
lxc image info ubuntu:xenial/amd64
error: Get https://cloud-images.ubuntu.com/releases/streams/v1/index.json: lookup cloud-images.ubuntu.com on 10.242.247.1:53: read udp 10.242.247.225:34385->10.242.247.1:53: i/o timeout
root@test:~# dig cloud-images.ubuntu.com
dig cloud-images.ubuntu.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> cloud-images.ubuntu.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37204
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;cloud-images.ubuntu.com.	IN	A

;; ANSWER SECTION:
cloud-images.ubuntu.com. 616	IN	A	91.189.92.141

;; Query time: 0 msec
;; SERVER: 10.242.247.1#53(10.242.247.1)
;; WHEN: Wed Nov 15 13:10:16 UTC 2017
;; MSG SIZE  rcvd: 68

root@test:~# lxc image info ubuntu:xenial/amd64
lxc image info ubuntu:xenial/amd64
Fingerprint: d50f965b8d42c0aa8224ac0355d6898e5c0b3521be3af875644c05b04134019a
Size: 156.19MB
Architecture: x86_64
Public: yes
Timestamps:
    Created: 2017/11/07 00:00 UTC
    Uploaded: 2017/11/07 00:00 UTC
    Expires: 2021/04/21 00:00 UTC
    Last used: never
Properties:
    version: 16.04
    architecture: amd64
    label: release
    serial: 20171107.2
    description: ubuntu 16.04 LTS amd64 (release) (20171107.2)
    os: ubuntu
    release: xenial
Aliases:
    - 16.04
    - 16.04/amd64
    - default
    - default/amd64
    - lts
    - lts/amd64
    - x
    - x/amd64
    - xenial
    - xenial/amd64
Auto update: disabled

**Comment by stgraber** [comment]
Looks like something dodgy on your network is affecting DNS as the same works perfectly fine here.

My guess as to why doing dig fixes it is because it's requesting a slightly different set of DNS records, causing a different packet size on your network which doesn't get dropped because of bad MTU. Once that gets cached by your local dnsmasq, then you're good.

**Comment by vilagithub** [comment]
Just found out the issue, I had a ... dead DNS entry in resolvconf on the host which manifested itself only in this specific case.

Sorry for the noise and thanks for the feedback nevertheless.
