### ISSUE TITLE
Returning image hash after import

### ISSUE THREAD

**Issue by jensg-st** [lxc/lxd#403]
I think the import function should return the image hash. Otherwise it will be hard to find the image in the image list, if you have more than 10 images. In particular if you want to set an alias straight after import.

I still think that the property 'alias' should be used as a 'reserved' property on image import, so I could work with the alias(es) straight after import. I understand that this would merge two logical steps into one kind of transaction, where the second step could fail while the first step, the import, is successful. Nevertheless a "best effort" approach while setting aliases here should be good enough, if you don't want to rollback the image import. Can you please share the idea, why you don't like the alias setting during import?

**Comment by stgraber** [comment]
actually, I believe the command line spec does define that --alias can be passed to both publish and import to set aliases at import time. It's just not been implemented yet.

**Comment by jensg-st** [comment]
Didn't see that, sorry. Will do it over the weekend if it has not been touched by then.

**Comment by jensg-st** [comment]
Looking at the specs, I reckon it is a bit confusing sometimes, so sorry for the questions.

The spec says:

> Aliases are a one to one mapping between a user friendly name and an image. 

But the 'image list' command as well as the implementation allows multiple aliases for an image, which makes sense otherwise it would be just a field in the database I'm assuming. So, multiple aliases for an image is the goal?

Not implemented yet, but the '--alias' arg for publish and import is for one alias only and not comma-separated list?

The spec says as well:

> Aliases may contain any character but colons and slashes.

But in the example it is centos/7 and it works at the moment. Colons I understand because you are using it for remotes. I'm assuming that this is just a thing, which needs to be 'fixed' in the specs.

**Comment by stgraber** [comment]
Sounds like the spec needs fixing :)

It's a many to one mapping (an image can have multiple aliases but a given alias will only ever point to a single image). And indeed slashes are allowed and in fact used. Colons are still illegal though :)

**Comment by stgraber** [comment]
Forgot to close this one. I implemented this yesterday.

Keeping the issue open to also address the spec inaccuracy.
