### ISSUE TITLE
bridge.external_interfaces not accepting vlan interfaces

### ISSUE THREAD

**Issue by Spunge** [lxc/lxd#4042]
## Environment
I'm running Ubuntu 16.04.3 LTS with kernel Linux ubuntu 4.4.0-101-generic with packages from the ppa

 driver: lxc
 driver_version: 2.1.1
 kernel: Linux
 kernel_architecture: x86_64
 kernel_version: 4.4.0-101-generic
 server: lxd
 server_pid: 6429
 server_version: "2.20"
 storage: zfs
 storage_version: 0.6.5.6-0ubuntu16

## Issue description
When i create a unconfigured vlan interface via ```vconfig add ens3 30``` i can't add that to a lxd  bridge by editing the network and adding it to 'bridge.external_interfaces'. I can add normal interfaces though. When adding a vlan interface i get the following error on saving:
```Config parsing error: Invalid interface name 'ens3.30' Press enter to open the editor again```

I can add the virtual interface to the bridge using brctl: ```brctl addif bridge_name ens3.30```, which works fine but is not a persistent solution.

I would expect to be able to add vlan interfaces to lxd managed network bridges.

## Steps to reproduce

 1. Create network bridge
 2. Create vlan interface
 3. Try to add vlan interface to bridge.external_interfaces via ```lxc network edit bridge_name```

**Comment by wociscz** [comment]
Observed similar behavior in lxc network create for tunnel interfaces just while ago :-)
example:
```
# lxc network create vx339 tunnel.vx339.protocol=vxlan tunnel.vx339.group=239.0.1.84 tunnel.vx339.id=339 tunnel.vx339.interface=xgb0.1000
error: Interface name contains invalid characters
```

xgb0.1000 is vlan interface on xgb0

When i change it to non-vlan interface everything is ok, except mtu is set to 1400 and not to mtu of the parent interface (9000 in my case, so right value have to be mtu minus 50 for header)
Should i open another issue?

**Comment by stgraber** [comment]
It's likely the same check so same issue is fine.
