### ISSUE TITLE
how to add recursively 165536 number to owner:group ids of files/directories to turn privileged container into  unprivileged one

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#4047]
General question about to turn privileged container into unprivileged one: 

is there a tool planned to turn filesystem owners/group ids from unprivileged one to privileged one?

exemple: to add 165536 on each file/directory owner id 

 root (0) -> 165536 
 userx (1200) -> 165536  + 1200
etc ...

i made a unprivileged container to hold an old redhat 5 (there is not image of that on remotes images):
 - i have downloaded an existing image of centos 6
 - deleted  everything in rootfs 
 - untar a redhat 5 content.

now i have to turn owners/groups  recursively in rootfs
it would be nice to have a tool to do that.

**Comment by brauner** [comment]
I'm pretty sure that our `fuidshift` tool which ships with `LXD` would allow you to do this.

**Comment by stgraber** [comment]
You filed this issue under LXD, if under LXD, just switching security,privileged from true to false and restarting the container will have LXD remap everything for you.

If you're instead using LXC, then as @brauner mentioned, you could use the "fuidshift" tool that's part of the LXD repository to manually remap your root filesystem.

**Comment by gaetanquentin** [comment]
it is lxd but it was already an unprivileged container, so i can't switch security,privileged from true to false

fuidshift do not work with lxd?

**Comment by gaetanquentin** [comment]
ah yes it is shiped with lxd-tools:

lxd-tools: /usr/bin/fuidshift

**Comment by stgraber** [comment]
ah, if it's an existing container, you could try to have LXD do it for you:

 - lxc stop NAME
 - lxc config set NAME volatile.last_state.idmap "[]"
 - lxc start NAME

That should make LXD think that the container is currently privileged and about to become unprivileged on next start, when starting the container, things should get remapped.

**Comment by gaetanquentin** [comment]
great i will try it tomorrow. 

by the way, on "handy made" container like my old redhat 5, is it normal not to see classic mounts inside container, like lxcfs and even / ? on downloaded images, there are lots of system mounts mounted by lxd/lxcfs.

there are only tmpfs
underlayer filesystem is btrfs.
