### ISSUE TITLE
[query] Can LXD host KVM for Windows or linux GUI?

### ISSUE THREAD

**Issue by nhadsall** [lxc/lxd#4055]
We are using LXD for our internal services. We would like to setup windows and linux with GNOME (over VNC) for some of our users.

We setup KVM inside one of the containers. We were able to install CentOS in that KVM guest. I'm wondering if we would be able to run windows within this KVM as well, or if we would have to run KVM outside a container. 

Also, we tried installing GNOME in a LXC container (ubuntu), but it seemed to have trouble.

Thanks!

**Comment by stgraber** [comment]
There is no real difference between running kvm inside a LXD container or running it on the host so I'd expect a Windows VM to work perfectly fine running on kvm inside a LXD container, that's in fact how I have all my kvm hosts setup.
