### ISSUE TITLE
Makefile test for sqlite3.h is broken

### ISSUE THREAD

**Issue by jynnantonix** [lxc/lxd#4078]
# Issue description

Hello, while porting lxd to run on chrome os I noticed that the test for sqlite3.h in the Makefile is broken.  Instead of checking if /usr/include/sqlite3.h exists, it should instead try to include that header from a .c file and then check to see if that file is compiled successfully.

The background is that chrome os uses dedicated sysroots for all the different devices that we ship.  When compiling code for a particular device our C and C++ compilers take care of automatically using the sysroot for that device.  For example, if I was compiling lxd for a device with the codename 'eve', the sysroot for that device would be `/build/eve` and the compiler invocation would look like `x86_64-cros-linux-gnu-clang -sysroot=/build/eve`.

So the situation we have is:

* /usr/include/sqlite3.h <- exists
* /build/eve/usr/include/sqlite3.h <- does not exist

This causes the Makefile to incorrectly assume that sqlite3.h is available when it isn't and lxd fails to compile because it cannot find sqlite3.h.

The correct way to test for sqlite3.h is to try to include from an actual source file and then try to compile that file.  This mimics the environment in which the code will actually be compiled so the test will accurately reflect whether sqlite3.h exists.

# Steps to reproduce

 1. Install sqlite3
 2. Prepare a separate sysroot without sqlite3
 3. Attempt to build lxd while ensuring that C and C++ compilers are invoked with the `-sysroot=<sysroot_without_sqlite3>` flag.

**Comment by brauner** [comment]
@jynnantonix care to send a patch?

**Comment by stgraber** [comment]
Easy enough, pushed a fix for it in my branch, will send later tonight.

**Comment by jynnantonix** [comment]
Hi again.  While the new patch is definitely an improvement, it's still not ideal because it hardcodes `gcc` as the compiler.  As I mentioned in my initial report, our compilers tend to have long names like `armv7a-cros-linux-gnueabi-clang`.  These are set through the `CC` and `CXX` environment variables and can be referenced in the Makefile as `$(CC)` and `$(CXX)`, respectively.

I'm not sure how this interacts with the shell script that's already in the makefile but hardcoding the compiler is definitely not going to work for us.

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/pull/4087 should take care of that
