### ISSUE TITLE
Implement a --all flag in lxc/action.go

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4083]
This would allow running a particular action against all containers.
Useful to start/stop/restart them all or freeze/unfreeze.

Original request: https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1735718

**Comment by schu** [comment]
Took a stab at this with https://github.com/lxc/lxd/pull/4100 - please take a look :)

**Comment by stgraber** [comment]
will do, thanks @schu
