### ISSUE TITLE
Pool Name option missin in lxd 2.0.11

### ISSUE THREAD

**Issue by qerosi** [lxc/lxd#4086]
Hi everyone, 

i would like to let you know if you don't already know that when i tried to make fresh install of lxd 2.0.11 in Ubuntu 16.04.3 i noticed that the step to create Pool Name in automatic mode with command "lxd init" its not present.
This missing step doesn't let to finish configuration ending with message below : 

error: Failed to create the ZFS pool: cannot create ' ': name must begin with a letter pool name may have been omitted

I've managed to make it work with a previous version of lxd and than upgrading to 2.0.11.

Have a nice day and best of luck for the future projects.

**Comment by stgraber** [comment]
What exact "lxd init" command did you run?

**Comment by qerosi** [comment]
Just lxd init without any flag,  all the questions about storage type, storage device/size, bridge configuration came one after the other but the question for naming the pool didn't.

**Comment by stgraber** [comment]
Thanks, reproduced this here, wondering how this was missed in testing... working on a fix now and will upload it to Ubuntu ASAP.

**Comment by stgraber** [comment]
I've uploaded the fix to the Ubuntu archive and am now waiting for someone to review it.
This will be treated as an emergency update so as soon as it's reviewed, it'll get manually tested and released, waving the normal week of -proposed testing.

**Comment by qerosi** [comment]
I've just tested the latest update and everything looks great, thank you.
