### ISSUE TITLE
`lxc-net` fails if port 53 is unavailable

### ISSUE THREAD

**Issue by kdex** [lxc/lxd#4090]
# Required information

 * Distribution: Arch Linux
 * Distribution version: 4.14.4-1-ARCH
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.14.4-1-ARCH
   * LXC version: community/lxc-1:2.1.1-1
   * LXD version: n/a
   * Storage backend in use: n/a

# Issue description

I'm trying to set up a `veth`-type network using the helper script `lxc-net`. I've set up a custom DNS port for `dnsmasq` (5353), since my `powerdns` instance needs port 53; powerdns being strictly a DNS server, not a DHCP server or anything else that's built into dnsmasq.

However, I have found no way to configure this port in `/etc/default/lxc{,-net}`. A quick glimpse in `/usr/lib/lxc/lxc-net` showed that `dnsmasq` is called with the default port and the `iptables` rules have port 53 hardcoded in them. This makes it impossible for me to run `lxc-net`.
 
# Steps to reproduce

 1. Change `dnsmasq`s port to 5353
 2. Use port 53 with another software
 3. Try to run `lxc-net`.

# Information to attach

`# journalctl -xeu lxc-net`

```
-- Unit lxc-net.service has begun starting up.
Dec 09 04:18:50 pichu lxc-net[3635]: dnsmasq: failed to create listening socket for 10.10.10.1: Address already in use
Dec 09 04:18:50 pichu lxc-net[3635]: Failed to setup lxc-net.
Dec 09 04:18:51 pichu lxc-net[3635]: Failed to setup lxc-net.
Dec 09 04:18:51 pichu systemd[1]: lxc-net.service: Main process exited, code=exited, status=1/FAILURE
Dec 09 04:18:51 pichu systemd[1]: lxc-net.service: Failed with result 'exit-code'.
Dec 09 04:18:51 pichu systemd[1]: Failed to start LXC network bridge setup.
-- Subject: Unit lxc-net.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit lxc-net.service has failed.
-- 
-- The result is RESULT.
```

**Comment by kdex** [comment]
I just realized that these issues are about `lxd`, not `lxc`. Should I take this issue to [`lxc/lxc`](https://github.com/lxc/lxc)?

**Comment by stgraber** [comment]
You could but we're not going to be able to do anything about it.
All Linux distributions expect the DNS server to be on port 53 and you can't provide an alternative port through DHCP or IPv6 RA.

The main issue here is that your powerdns server is binding every single interfaces on port 53. If you were to configure it to only bind the interfaces you actually need it on, it'd all work fine.
