### ISSUE TITLE
LXD Shutdown State Consideration

### ISSUE THREAD

**Issue by Fierykev** [lxc/lxd#4102]
When viewing the code for containerShutdown, it seems there may be a small bug in relation to when the container's state is checked during lxd shutdown.

First the container's state is cached during shutdown:
https://github.com/lxc/lxd/blob/2d9eb5ddbadd87d80ea8131c3d86bdcb54a2416c/lxd/containers.go#L213

However, when the code actually considers whether or not the container should be shutdown, it does not use the cached copy of the state, preferring to request if the container is currently running:
https://github.com/lxc/lxd/blob/2d9eb5ddbadd87d80ea8131c3d86bdcb54a2416c/lxd/containers.go#L224

Ergo, when the container is either shutdown or left alone in the below lines, the data stored to "volatile.last_state.power" would seem to not be the last state considered by the shutdown code as it uses the cached copy of the state stored before checking IsRunning:
https://github.com/lxc/lxd/blob/2d9eb5ddbadd87d80ea8131c3d86bdcb54a2416c/lxd/containers.go#L239
https://github.com/lxc/lxd/blob/2d9eb5ddbadd87d80ea8131c3d86bdcb54a2416c/lxd/containers.go#L244

For reference this is the for loop I am referring to below:
https://github.com/lxc/lxd/blob/2d9eb5ddbadd87d80ea8131c3d86bdcb54a2416c/lxd/containers.go#L209

If this is indeed an issue, a possible fix would be to utilize the cached state variable instead of IsRunning.  Additionally, we could also consider caching state prior to the for loop in order to minimize the time that the code checks state in order to try to make lxd shutdown's behavior more predictable to the user because, if there were to be any long pause between caching the var and checking IsRunning, behavior may not be what is expected when the user issued the lxd shutdown command.

**Comment by stgraber** [comment]
I don't think it's a particularly likely race condition given that this code is hit when the daemon is shutting down, usually as a result of the system itself going down, making it extremely unlikely that we'd get queries at that time.

That being said, it's an easy enough race to fix so I sent a fix :)
