### ISSUE TITLE
Allow copying a container or image from a private LXD to a public one

### ISSUE THREAD

**Issue by alejandro-perez** [lxc/lxd#4108]
Hello,

I have a private (not listening over TCP) LXD daemon on my laptop, which is behind  a NAT, firewall, etc.
Now I want to copy my container to a public LXD server I have running at work, but it won't allow me since:
```
error: The source server isn't listening on the network
```
Is this on purpose? Is there any way by which I can move my container from my local machine to the server without having to create the tar ball myseof, then creating a new container in the server, then replacing the rootfs manually?

Thanks for the great job!

**Comment by stgraber** [comment]
It's on purpose as the the way the LXD API works is that the target server is provided the URL of the source server along with a temporary secret to download the image.

For containers we have push and relay support which allows to get around that particular behavior.
So if using `lxc move` or `lxc copy`, you can pass `--mode=push` to have your source server push to the target or `--mode=relay` to have the client tool download from the source and push to the target.

**Comment by alejandro-perez** [comment]
Thanks @stgraber 
That really made my day. Although I was surprised that rsync was not using the compression flag, but I guess that it is meant to move things from cloud to cloud, rather than from my laptop to the server over the Internet.

Yes, I realized the `lxc publish` & `lxc image import` workaround, although I was suffering from the "socket is not allowed in tar" bug, that is not solved in 2.20.

Thanks!

**Comment by stgraber** [comment]
Ah yeah, the export bug is fixed in master but just missed 2.20 (we cherry-picked it in a bunch of our packages though), 2.21 will have that fix for sure.

**Comment by alejandro-perez** [comment]
Yep. I saw that. I can wait, it is not something I use every day.

**Comment by tomposmiko** [comment]
--mode=push|relay works
But it looks totally useless. It would be easy to determine which mode is intended to use.
Am I wrong somewhere?

**Comment by Strum355** [comment]
> For images, you're out of luck at least right now as only pull mode is supported at the API level.

Is there a roadmap time for when this will become a thing?

**Comment by stgraber** [comment]
Nope, but I'll put it on our roadmap and will create an issue for it soon (at a conference right now)
