### ISSUE TITLE
.config/lxc/config.yml is not created until lxc remote add is callled

### ISSUE THREAD

**Issue by alejandro-perez** [lxc/lxd#4112]
Hi!

I wanted to set up an lxc alias that I was using in my laptop into the server one, and I realized there were not .config/lxc/config.yml. I created it and set up the alias but then apparently it expected to find the remote declarations there, and they are not trivial.

I figure it out a workaround, that that's not pretty:
lxc remote add DELETEME MY_HOST_IP
lxc remote remove DELETEME

That created the configuration file and now I can add aliases.

IMO, this file should be created the first time you use `lxc` with t he default values.

**Comment by stgraber** [comment]
Actually, there is logic that does exactly that, but it checks for "~.config/lxc", in your case it sounds like the directory existed bu the config file didn't.

**Comment by alejandro-perez** [comment]
Yes, it existed. I don't know why, maybe some old configuration from a previous installation?

**Comment by stgraber** [comment]
I have a fix for this logic in my local branch (working on a bigger feature now) will send it through tomorrow, it effectively just changes the check from a dir check to a file check.
