### ISSUE TITLE
Failed migration to snap

### ISSUE THREAD

**Issue by nickmaleao** [lxc/lxd#4123]
Hello

After the last update from the ubuntu repo, as sugested a tried to migrate to snap part of the migration succeed but the storage part failed.

leonarit@lab16916.com@thanos:~$ sudo lxd.migrate
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks

=== Source server
LXD version: 2.21
LXD PID: 13280
Resources:
Containers: 2
Images: 1
Networks: 0
Storage pools: 1

=== Destination server
LXD version: 2.21
LXD PID: 23883
Resources:
Containers: 0
Images: 0
Networks: 0
Storage pools: 0

The migration process will shut down all your containers then move your data to the destination LXD.
Once the data is moved, the destination LXD will start and apply any needed updates.
And finally your containers will be brought back to their previous state, completing the migration.

Are you ready to proceed (yes/no) [default=no]? yes
=> Shutting down the source LXD
=> Stopping the source LXD units
=> Stopping the destination LXD unit
=> Unmounting source LXD paths
=> Unmounting destination LXD paths
=> Wiping destination LXD clean
=> Moving the data
=> Moving the database
=> Backing up the database
=> Opening the database
=> Updating the storage backends
error: Failed to update the storage pools: Failed to run: zfs list -H -t all -o name,mountpoint -r : cannot open '': invalid dataset name`

The settings were migrated to snap and the containers were still functioning, but after i rebooted the server, i started to get the following errors and cant start the container.

[journalctl._lxd.log](https://github.com/lxc/lxd/files/1592232/journalctl._lxd.log)

**Comment by nickmaleao** [comment]
leonarit@lab16916.com@thanos:~$ sudo zfs list
NAME                                                                                  USED  AVAIL  REFER  MOUNTPOINT
lxd                                                                                  9.67G  28.8G    19K  none
lxd/containers                                                                       9.00G  28.8G    19K  none
lxd/containers/nms                                                                   9.00G  28.8G  9.11G  /var/lib/lxd/storage-pools/lxd/containers/nms
lxd/deleted                                                                           346M  28.8G    19K  none
lxd/deleted/images                                                                    346M  28.8G    19K  none
lxd/deleted/images/f4c9feb3e4018ffbd793d4b80d54fb95835bb1461380f2f9b7976c7b10ac48b9   346M  28.8G   346M  none
lxd/images                                                                            300M  28.8G    19K  none
lxd/images/8fa08537ae51c880966626561987153e72d073cbe19dfe5abc062713d929254d           300M  28.8G   300M  none

I''ve found that the  mount point is empty after some research i found this post https://discuss.linuxcontainers.org/t/lxd-zfs-mount-empty/831/2, for testing purposes i deleted the mount point 

sudo rm -fr /var/lib/lxd/storage-pools/lxd/containers/nms 

and after that i was able to start the container.

I've removed every trace of lxd services and targets associated with systemd besides snap-lxd  but that the container still gets created at boot, 

does anyone know what are the files/configs that must be removed?

**Comment by ewarnke** [comment]
I'm in the same boat but no images were moved over leaving me hanging.  Networking seems to have been created but no images.

**Comment by brontide** [comment]
Reboot has left me with no containers as the storage is all messed up.  The snap lxd appears to be pointing to an .img file and my lxd zfs is a partition.

**Comment by stgraber** [comment]
@brontide what does `lxc storage list` and `lxc storage show NAME` for each of them show?

The output of `zpool status -v` and `ls -lh /var/snap/lxd/common/lxd/disks/` would also be useful.

**Comment by brontide** [comment]
I was able to revive the containers only after unsetting the mountpoints `zfs set mountpoint=none lxd/...`


```
root@pod1:~# lxd.lxc storage list
+------+-------------+--------+----------------------------------------+---------+
| NAME | DESCRIPTION | DRIVER |                 SOURCE                 | USED BY |
+------+-------------+--------+----------------------------------------+---------+
| lxd  |             | zfs    | /var/snap/lxd/common/lxd/disks/lxd.img | 31      |
+------+-------------+--------+----------------------------------------+---------+
root@pod1:~# zpool status -v
  pool: lxd
 state: ONLINE
  scan: scrub repaired 0 in 11h39m with 0 errors on Sun Dec 10 12:03:29 2017
config:

        NAME        STATE     READ WRITE CKSUM
        lxd         ONLINE       0     0     0
          sdb       ONLINE       0     0     0

errors: No known data errors
root@pod1:~# ls -lh /var/snap/lxd/common/lxd/disks/
total 15G
-rw------- 1 root root 40G Nov  4  2016 lxd.img
root@pod1:~# lxd.lxc storage show webproxy
error: not found
root@pod1:~# lxd.lxc storage show lxd
config:
  size: "321854111744"
  source: /var/snap/lxd/common/lxd/disks/lxd.img
description: ""
name: lxd
driver: zfs
used_by:
- /1.0/containers/collectd
- /1.0/containers/collectd/snapshots/working1
- /1.0/containers/ganglia
- /1.0/containers/ganglia/snapshots/working
- /1.0/containers/insightiq
- /1.0/containers/insightiq/snapshots/iiq41working
- /1.0/containers/insightiq/snapshots/patchedsecret
- /1.0/containers/insightiq/snapshots/pre-4.1.1
- /1.0/containers/insightiq/snapshots/setup
- /1.0/containers/pod1-mysql
- /1.0/containers/pod1-mysql/snapshots/working
- /1.0/containers/shellinabox
- /1.0/containers/shellinabox/snapshots/201611221442
- /1.0/containers/webproxy
- /1.0/containers/webproxy/snapshots/20161104
- /1.0/containers/webproxy/snapshots/201611070714
- /1.0/containers/webproxy/snapshots/201611102031
- /1.0/containers/webproxy/snapshots/201611181052
- /1.0/containers/webproxy/snapshots/201612061532
- /1.0/containers/webproxy/snapshots/working1
- /1.0/containers/website-trr
- /1.0/containers/website-trr/snapshots/working
- /1.0/containers/website-wiki
- /1.0/containers/website-wiki/snapshots/201611051059
- /1.0/containers/website-wiki/snapshots/201611070714
- /1.0/containers/website-wiki/snapshots/201612032147
- /1.0/containers/website-wiki/snapshots/working
- /1.0/images/4a2528350439cc5cda234fb2e81bd8ce4c0c0e0fb265026e3581f5e9fcd945a8
- /1.0/images/562fbb7febfd72d8984bc6f04f7ee1a4cc13e52c4ed708d7e47f825b6a5f8783
- /1.0/images/c8948ee42ef1de2b8a5258cfe0b668ae47abb16a365eb50f1bc9ef9f3849bd32
- /1.0/profiles/default
root@pod1:~# zfs list
NAME                                                                                  USED  AVAIL  REFER  MOUNTPOINT
lxd                                                                                  58.3G   232G    19K  none
lxd/containers                                                                       56.1G   232G    19K  none
lxd/containers/collectd                                                               532M   232G   517M  /var/lib/lxd/storage-pools/lxd/containers/collectd
lxd/containers/ganglia                                                               2.78G   232G  1.56G  /var/lib/lxd/storage-pools/lxd/containers/ganglia
lxd/containers/insightiq                                                             50.3G   232G  42.1G  /var/lib/lxd/storage-pools/lxd/containers/insightiq
lxd/containers/pod1-mysql                                                             494M   232G   433M  none
lxd/containers/shellinabox                                                            448M   232G   451M  none
lxd/containers/webproxy                                                               664M   232G   410M  none
lxd/containers/website-trr                                                            296M   232G   357M  /var/lib/lxd/storage-pools/lxd/containers/website-trr
lxd/containers/website-wiki                                                           699M   232G   541M  none
lxd/deleted                                                                           895M   232G    19K  none
lxd/deleted/images                                                                    895M   232G    19K  none
lxd/deleted/images/315bedd32580c3fb79fd2003746245b9fe6a8863fc9dd990c3a2dc90f4930039   345M   232G   345M  none
lxd/deleted/images/b517d72e6573ef72f9fd90f25877ef6d9773084b4e5906578ba316ac0627b1ce   204M   232G   204M  none
lxd/deleted/images/b9cba741ef621f14e6e8c306c7f87637a59d7d09c1a3ec8ef717ab0d6e43430a   346M   232G   346M  none
lxd/images                                                                            887M   232G    19K  none
lxd/images/4a2528350439cc5cda234fb2e81bd8ce4c0c0e0fb265026e3581f5e9fcd945a8           203M   232G   203M  none
lxd/images/562fbb7febfd72d8984bc6f04f7ee1a4cc13e52c4ed708d7e47f825b6a5f8783           187M   232G   187M  none
lxd/images/c8948ee42ef1de2b8a5258cfe0b668ae47abb16a365eb50f1bc9ef9f3849bd32           303M   232G   303M  none
lxd/images/d021912b7484ddef67786f71bb8a8359bc6d78ac0ce2b098605476b8825337dc           193M   232G   193M  none
lxd/snapshots                                                                          38K   232G    19K  none
lxd/snapshots/webproxy                                                                 19K   232G    19K  none

```

I'm not sure where the files are actually located at this point since the zfs filesystems are not actually mounted.

**Comment by brontide** [comment]
And the list of currently running containers.

```
root@pod1:/snap# lxd.lxc list
+--------------+---------+--------------------------------+------+------------+-----------+
|     NAME     |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
+--------------+---------+--------------------------------+------+------------+-----------+
| collectd     | STOPPED |                                |      | PERSISTENT | 1         |
+--------------+---------+--------------------------------+------+------------+-----------+
| ganglia      | STOPPED |                                |      | PERSISTENT | 1         |
+--------------+---------+--------------------------------+------+------------+-----------+
| insightiq    | STOPPED |                                |      | PERSISTENT | 4         |
+--------------+---------+--------------------------------+------+------------+-----------+
| pod1-mysql   | RUNNING | 10.62.3.20 (eth0)              |      | PERSISTENT | 1         |
+--------------+---------+--------------------------------+------+------------+-----------+
| shellinabox  | RUNNING | 10.62.3.14 (eth0)              |      | PERSISTENT | 1         |
+--------------+---------+--------------------------------+------+------------+-----------+
| webproxy     | RUNNING | externaliphere (eth0)          |      | PERSISTENT | 6         |
|              |         | 10.62.3.2 (eth1)               |      |            |           |
+--------------+---------+--------------------------------+------+------------+-----------+
| website-trr  | STOPPED |                                |      | PERSISTENT | 1         |
+--------------+---------+--------------------------------+------+------------+-----------+
| website-wiki | RUNNING | 10.62.3.11 (eth0)              |      | PERSISTENT | 4         |
+--------------+---------+--------------------------------+------+------------+-----------+
```

**Comment by nickmaleao** [comment]
@brontide thanks for the tip, removed the mouting point "zfs set mountpoint=none lxd/..." and now when i restart the server the container starts without problems.

Best regards.

**Comment by stgraber** [comment]
@brontide did you change your zpool to be backed by /dev/sdb after you had LXD set it up initially?

I'm trying to understand why you'd have a zpool that's backed by /dev/sdb but have LXD think it's backed by /var/snap/lxd/common/lxd/disks/lxd.img

**Comment by stgraber** [comment]
Having moved the zpool from backed by lxd.img to /dev/sdb but not having removed /var/lib/lxd/lxd.img would explain the state you got in and would likely need a bit more cleanup to get things in the expected state again.

**Comment by brontide** [comment]
Based on memory that sounds like it could be it.  When I outgrew the space in the zpool I replaced the .img file with a block device. I may not have gone back and removed the .img file.

**Comment by stgraber** [comment]
Ok, that'd make sense, then I'd recommend you do:

    sqlite3 /var/snap/lxd/common/lxd/lxd.db "UPDATE storage_pools_config SET value='lxd' WHERE value='/var/snap/lxd/common/lxd/disks/lxd.img';"
    rm /var/snap/lxd/common/lxd/disks/lxd.img

**Comment by stgraber** [comment]
At which point `lxc storage list` should show `lxd` as the source for your storage pool.

**Comment by stgraber** [comment]
@nickmaleao Please show the output of:

 - `lxc storage list`
 - `lxc storage show NAME` for every pool listed above
 - `zpool status -v`
 - `ls -lh /var/snap/lxd/common/lxd/disks/`
 - `zfs list -t all`

That should let me check that everything is okay.

**Comment by stgraber** [comment]
@nickmaleao the main bit of migration code you missed is the one that updates the mountpoint properties of all datasets in your zpool, which explains why you had to do it by hand.

**Comment by nickmaleao** [comment]
@stgraber 

Here's the output as requested.


 - sudo lxc storage list
+------+-------------+--------+----------------------------------------+---------+
| NAME | DESCRIPTION | DRIVER |                 SOURCE                 | USED BY |
+------+-------------+--------+----------------------------------------+---------+
| lxd  |             | zfs    | /var/snap/lxd/common/lxd/disks/lxd.img | 3       |
+------+-------------+--------+----------------------------------------+---------+


 - lxc storage show lxd
config:
  size: "42681237504"
  source: /var/snap/lxd/common/lxd/disks/lxd.img
description: ""
name: lxd
driver: zfs
used_by:
- /1.0/containers/nms
- /1.0/images/8fa08537ae51c880966626561987153e72d073cbe19dfe5abc062713d929254d
- /1.0/profiles/default

 - zpool status -v

 pool: lxd
state: ONLINE
 scan: scrub repaired 0 in 0h17m with 0 errors on Sun Dec 10 00:41:04 2017
onfig:

       NAME                                      STATE     READ WRITE CKSUM
       lxd                                       ONLINE       0     0     0
         /var/snap/lxd/common/lxd/disks/lxd.img  ONLINE       0     0     0

 - ls -lh /var/snap/lxd/common/lxd/disks/

total 40G
-rw------- 1 root root 40G Jan 10 21:20 lxd.img

 - zfs list -t all
NAME                                                                                           USED  AVAIL  REFER  MOUNTPOINT
lxd                                                                                           8.13G  30.4G    19K  none
lxd/containers                                                                                7.47G  30.4G    19K  none
lxd/containers/nms                                                                            7.47G  30.4G  7.58G  none
lxd/deleted                                                                                    346M  30.4G    19K  none
lxd/deleted/images                                                                             346M  30.4G    19K  none
lxd/deleted/images/f4c9feb3e4018ffbd793d4b80d54fb95835bb1461380f2f9b7976c7b10ac48b9            346M  30.4G   346M  none
lxd/deleted/images/f4c9feb3e4018ffbd793d4b80d54fb95835bb1461380f2f9b7976c7b10ac48b9@readonly      0      -   346M  -
lxd/images                                                                                     300M  30.4G    19K  none
lxd/images/8fa08537ae51c880966626561987153e72d073cbe19dfe5abc062713d929254d                    300M  30.4G   300M  none
lxd/images/8fa08537ae51c880966626561987153e72d073cbe19dfe5abc062713d929254d@readonly              0      -   300M  -

**Comment by brontide** [comment]
Yep, @stgraber that corrected the issue here.  I've tested creating and deleting containers as well.

**Comment by stgraber** [comment]
@nickmaleao looks like you're in good shape too.

**Comment by nickmaleao** [comment]
Many thanks! i will close the issue.

Best regards.
