### ISSUE TITLE
Different containers are running after server reboots

### ISSUE THREAD

**Issue by akarelas** [lxc/lxd#4130]
# Required information

 * Distribution: Ubuntu Server and Ubuntu MATE (2 machines), after updating to lxd 2.21
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails: https://gist.github.com/akarelas/c250968f75d4913a2158a434ef3971a1 (this is for the Ubuntnu Server)
 * I am using the backports repository, as suggested by lxd update itself when it reached 2.20

# Issue description

When I reboot and some containers are running, after reboot a different set of containers is running (not necessarilly the same number of containers as originally). Also I think (though not sure) that certain containers I had deleted re-appeared in `lxc list`.

# Steps to reproduce

 1. lxc start some containers
 2. sudo reboot
 3. lxc list, observe which containers are running. They are different EVERY TIME.

# Information to attach

This is the lxc info log of a container that didn't launch, when it should:

```
root@immense ~ # lxc info databases --show-log
Name: databases
Remote: unix://
Architecture: x86_64
Created: 2017/07/01 11:23 UTC
Status: Stopped
Type: persistent
Profiles: default
Snapshots:
  snap0 (taken at 2017/07/02 21:30 UTC) (stateless)
  snap1 (taken at 2017/08/12 09:35 UTC) (stateless)
  snap2 (taken at 2017/09/18 18:18 UTC) (stateless)
  snap3 (taken at 2017/09/23 15:59 UTC) (stateless)

Log:

            lxc 20180102044313.927 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180102044313.927 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180102044314.490 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180102044314.490 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180102045237.137 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180102045237.172 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180102045237.971 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
```

If you need any other information, please ask me and I will provide. Thanks.

**Comment by brauner** [comment]
Only those containers that were running before the reboot would be automatically restarted. If you start some containers and stop others and then reboot LXD will only bring up those that were running before the reboot.

**Comment by akarelas** [comment]
I know it *should*. But it doesn't. On both of my two machines (local laptop running Ubuntu MATE 16.04, and Ubuntu server 16.04) it doesn't happen. @brauner do you run Ubuntu 16.04 with the backports ppa instead of snappy?

**Comment by brauner** [comment]
Are you running the LXD ppa or the snap? Your original report reads like you're running the LXD backports ppa.

**Comment by akarelas** [comment]
I am running the LXD backports ppa.

**Comment by akarelas** [comment]
Can someone please confirm whether they see this problem on their xenial/backports lxd as well?

**Comment by Soswald** [comment]
I see a similar behavior.
If my server restarts, containers that where running are stopped and containers that where stopped are running. This occurred on the current version from the official ubuntu xeniall-backports repo on a 16.04 server.

**Comment by Soswald** [comment]
I stand corrected, 
I haven't migrated that server yet. It is the ppa version. I will check recheck after migration to backports on that server.

**Comment by stgraber** [comment]
Got a fix for this.

**Comment by 19wolf** [comment]
I'm having this issue, but I'm not sure if I'm running the backports or the snap. I was running backports but I intended to switch to using the snap.

It seems newly created containers know their status upon reboot, but older containers remain stopped, even if they were running before a reboot.
```
$ snap list lxd
Name  Version  Rev   Developer  Notes
lxd   2.21     5447  canonical  -
nephele@Nephele:~$ apt list lxd
Listing... Done
lxd/xenial-backports,now 2.21-0ubuntu2~16.04.1 amd64 [installed]
N: There are 3 additional versions. Please use the '-a' switch to see them.
```

**Comment by driscollw** [comment]
I have this same issue on backport 16.04 2.21. Not sure what version will address this. 
Thank you all for the work that you do on this project.

**Comment by stgraber** [comment]
Yeah, we need to do some cherry-picking into the 2.21 package, so far this has been resolved in the snap.
