### ISSUE TITLE
go get path adjustment

### ISSUE THREAD

**Issue by jcalfee** [lxc/lxd#4134]
I had to suffix the go get path with an extra `/lxd`.  This worked:
```bash
go get https://github.com/lxc/lxd/lxd
```

As documented `go get https://github.com/lxc/lxd` returned an error: 
>can't load package: package github.com/lxc/lxd: no Go files in /root/go/src/github.com/lxc/lxd

**Comment by stgraber** [comment]
Ah yeah, we should probably change the README to show "go get -d" instead.
