### ISSUE TITLE
Question (Issue) : Nested containers and Snap support 

### ISSUE THREAD

**Issue by ottacom** [lxc/lxd#4135]
Hi,
I don't know if this is the right place to make a question an I apologize in case.
As we know ppa is not longer supported and I have migrated on snap.

I'm working on Nested containers, so downloading ubuntu Xenial from the official repository I can use the LXD  package and lxc commands from the apt repository and they are currently at version 2.0.11, but as far I have understood snap it doesn't work inside the nested containers.

My questions are:
Is it true that Snap it doesn't work in a nested container? 
If yes, how can upgarde lxd inside a nested container without using Snap? 
If not, can I have some documents in order to use snap inside a nested container?

Many thanks,
Francesco

**Comment by stgraber** [comment]
One level is fine, more than one level is a problem because apparmor doesn't stack that far...

So if you have:
```
host (16.04 deb)
 - c1 (16.04 container running LXD snap)
   - c2 (normal container)
```

Then that should work fine. Where things stop working is if you intend to do:
```
host (16.04 deb)
 - c1 (16.04 container running LXD snap)
   - c2 (container running a snap, be that the lxd snap or anything else)
```

**Comment by stgraber** [comment]
Note that this question would likely have been better suited for the discussion forum.
https://discuss.linuxcontainers.org

**Comment by stgraber** [comment]
Note that LXD can still be found as a deb in backports, so that's also an option.

    apt install -t xenial-backports lxd

**Comment by ottacom** [comment]
Hi Stéphane,
many thanks for your quick and accurate answer.
I will move my further questions there in case.

You are doing a great job, please keep on pushing.

My best.

**Comment by brauner** [comment]
Cool, I think we can close here now. :)
