### ISSUE TITLE
added description to container config lost after stop/start/restart

### ISSUE THREAD

**Issue by skyxx** [lxc/lxd#4143]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.3
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-104-generic
   * LXC version: 2.1.1
   * LXD version: 2.21
   * Storage backend in use: LVM

# Issue description

When modify default value of **description: ""** in container config the description is shown in **lxc list -c d** until restart or stop/start container. Then modification was lost.

# Steps to reproduce

 1. lxc config edit containername
 2. change description: "some string"
 3. restart container (in container) or **lxc restart container** or **lxc stop container** / **lxc start container**

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
audit: type=1400 audit(1515254780.724:92): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-container_</var/snap/lxd/common/lxd>" name="/run/systemd/unit-root/run/lock/" pid=8823 comm="(networkd)" flags="ro, nosuid, nodev, noexec, remount, bind"

 - [ ] Container log (`lxc info NAME --show-log`)
  lxc 20180106160619.673 WARN     lxc_conf - conf.c:lxc_map_ids:2672 - newuidmap binary is missing
            lxc 20180106160619.673 WARN     lxc_conf - conf.c:lxc_map_ids:2678 - newgidmap binary is missing
            lxc 20180106160619.894 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180106160619.894 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.

 - [x] Container configuration (`lxc config show NAME --expanded`)
architecture: x86_64
config:
  environment.http_proxy: ""
  image.architecture: amd64
  image.description: Ubuntu bionic amd64 (20180105)
  image.os: Ubuntu
  image.release: bionic
  image.serial: "20180105_03:49"
  limits.cpu: "2"
  limits.memory: 2GB
  user.network_mode: ""
  volatile.base_image: f5f1de7eee9775174b8c83d1ef6276e38f05a7858c06186d4974c63cc783fea4
  volatile.eth0.hwaddr: 00:16:3e:06:33:32
  volatile.eth0.name: eth0
  volatile.eth1.hwaddr: 00:16:3e:e4:a6:43
  volatile.eth1.name: eth1
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  eth1:
    nictype: bridged
    parent: br1
    type: nic
  root:
    path: /
    pool: vlxd
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
lvl=warn msg="Unable to update backup.yaml at this time." name=container t=2018-01-06T16:06:19+0000

**Comment by stgraber** [comment]
Reproduced and got a fix for this.
