### ISSUE TITLE
ipv4 address not appear

### ISSUE THREAD

**Issue by thyeun** [lxc/lxd#4144]
OS : ubuntu 16.04.3 LTS
lxc : 2.0.11
lxd : 2.0.11

i have created a container, but when i done ```lxc list```, i get an empty ipv4 address, as you can see from the picture below

![selection_001](https://user-images.githubusercontent.com/1939446/34643474-bfc3895c-f35f-11e7-9381-2206f9e6648c.png)

below is my ```ifconfig -a ```

![selection_002](https://user-images.githubusercontent.com/1939446/34643495-f79b81d6-f35f-11e7-8b8f-b13c2f97df69.png)

and below is my ```lxc profile edit default ```

![selection_003](https://user-images.githubusercontent.com/1939446/34643519-5afabcec-f360-11e7-80f0-dc503b7bca40.png)

And below is my network configuration

![selection_004](https://user-images.githubusercontent.com/1939446/34643557-0e3e5674-f361-11e7-8345-a56b87e47b27.png)

**all the previous method i been try it, but still no luck to make ipv4 appear**

**Comment by stgraber** [comment]
Can you post the output of:
```
iptables -L -n -v
```

We've seen cases where Docker's changes to the system firewalls can prevent DHCP requests and other network traffic from making through the bridge.

**Comment by stgraber** [comment]
Oh and can you confirm that you do see a "dhclient" process in that container?

If not, you may want to try creating a new container as depending on when you changed your default profile, that container may have been templated to only do IPv6 link-local networking.

**Comment by thyeun** [comment]
![selection_005](https://user-images.githubusercontent.com/1939446/34660850-8042e008-f480-11e7-8cee-f8b3893bb3c7.png)

how to see the "dhclient" ?

**Comment by stgraber** [comment]
```
lxc exec free-husky -- ps aux
```

**Comment by stgraber** [comment]
You may also want to manually configure an IP in one of your containers, to see if it's just your DHCP server that's somehow misbehaving in this case.

**Comment by thyeun** [comment]
```lxc exec free-husky -- ps aux```

![selection_006](https://user-images.githubusercontent.com/1939446/34661124-6e73b670-f482-11e7-8164-2b0282bc91c8.png)

**Comment by stgraber** [comment]
No DHCP client in there but I can't remember exactly how that stuff works in alpine, whatever they use as DHCP client may have given up already.

**Comment by stgraber** [comment]
You can try:

    lxc exec free-husky -- ip -4 addr add 192.168.1.50/24
    lxc exec free-husky -- ip -4 route add 192.168.1.1
    lxc exec free-husky -- ping -c 4 192.168.1.2
    lxc exec free-husky -- ping -c 4 192.168.1.1
    lxc exec free-husky -- ping -c 4 8.8.8.8

To see if manual configuration works, if so, then something's wrong with the DHCP server on your network.

**Comment by thyeun** [comment]
one question, meaning that each of the container will be have a different configuration?

i been trying out several container "alpine, ubuntu xenial and centos" but all does't appear ipv4 address

if each container will be have a different configuration, than lxc n lxd are not robust at all.

**Comment by thyeun** [comment]
```lxc exec free-husky -- ip -4 addr add 192.168.1.50/24
lxc exec free-husky -- ip -4 route add 192.168.1.1
lxc exec free-husky -- ping -c 4 192.168.1.2
lxc exec free-husky -- ping -c 4 192.168.1.1
lxc exec free-husky -- ping -c 4 8.8.8.8 ```

since like nothing appear

![selection_007](https://user-images.githubusercontent.com/1939446/34661314-d70582ee-f483-11e7-9f17-3919ebd7d037.png)

**Comment by stgraber** [comment]
Oh, oops, the instructions weren't accurate:

```
lxc exec free-husky -- ip -4 addr add 192.168.1.50/24 dev eth0
lxc exec free-husky -- ip -4 route add default via 192.168.1.1
lxc exec free-husky -- ping -c 4 192.168.1.2
lxc exec free-husky -- ping -c 4 192.168.1.1
lxc exec free-husky -- ping -c 4 8.8.8.8
```

**Comment by stgraber** [comment]
Every Linux distribution does network configuration differently, this is no different than when installing on a physical system or in a virtual machine. All LXD images are configured to do DHCP on eth0 out of the box so that things work, but this assumes that you do have a working DHCP server on your network, if you don't, some Linux distributions will attempt to DHCP indefinitely while some others will give up.

**Comment by thyeun** [comment]
ok, understand now, than for me it will be impossible to make it work, since my eth0 are damage, currently using external network adapter (USB kind of external network adapter)

**Comment by stgraber** [comment]
eth0 in the container isn't eth0 outside of it, the described behavior is inside the container

**Comment by thyeun** [comment]
``` lxc exec free-husky -- ip -4 addr add 192.168.1.50/24 dev eth0 ```

i getting this 

``` ip: can't find device 'eth0' ```

**Comment by stgraber** [comment]
Oh, re-reading above, you actually have one thing that's clearly wrong in your profile, looking at pictures rather than text that I can highlight is making this harder than usual :)

The "name" property on your "bridge0" nic type device is "bridge0" when it should be "eth0" there.

**Comment by stgraber** [comment]
```
    lxc profile device set default bridge0 name eth0
    lxc restart free-husky
```

**Comment by stgraber** [comment]
That should fix that particular problem and restart the container, at which point the container will have an `eth0` network interface attached to your `bridge0` bridge on the host.

**Comment by thyeun** [comment]
``` lxc exec free-husky -- ip -4 addr add 192.168.1.50/24 dev eth0 ```

now getting 

``` ip: RTNETLINK answers: File exists ```

**Comment by thyeun** [comment]
``` lxc exec free-husky -- ip -4 addr add 192.168.1.50/24 dev eth0
lxc exec free-husky -- ip -4 route add default via 192.168.1.1
lxc exec free-husky -- ping -c 4 192.168.1.2
lxc exec free-husky -- ping -c 4 192.168.1.1
lxc exec free-husky -- ping -c 4 8.8.8.8 ```

now all have return 

![selection_008](https://user-images.githubusercontent.com/1939446/34661635-f17ce246-f485-11e7-838e-dc20601d05a4.png)

**Comment by stgraber** [comment]
Looks like you have functional networking now.

**Comment by thyeun** [comment]
but still not a single working ipv4 address appear

**Comment by thyeun** [comment]
OMG OMG !!!.....it appear now, that evil ipv4 appear now

thanks you so much, be working it for 3 days

**Comment by thyeun** [comment]
sorry for asking this, i'm creating MAAS inside lxd, but i cant get the web ui appear, will it be my lxd setting having some issue?

![selection_009](https://user-images.githubusercontent.com/1939446/34671106-1aa0c0e2-f4b4-11e7-98cb-ae6007f5f1d6.png)

and my ``` lxc profile edit maas ```

![selection_010](https://user-images.githubusercontent.com/1939446/34671144-4f2cc068-f4b4-11e7-874a-c596a259529b.png)

and my ``` sudo dpkg-reconfigure maas-region-controller ```

![selection_011](https://user-images.githubusercontent.com/1939446/34671191-89d25b92-f4b4-11e7-8c9a-36a2adcc0792.png)

lastly my apache2 are looking good as below 

![selection_012](https://user-images.githubusercontent.com/1939446/34671245-c6b81d08-f4b4-11e7-8272-264bef572f8b.png)

but my MAAS web UI appear like below

![selection_013](https://user-images.githubusercontent.com/1939446/34671258-da8d5da2-f4b4-11e7-954d-91b69bc0f8c9.png)

so, will it be my lxd setting goes wrong? or i missing some extra setting on lxd?

**Comment by stgraber** [comment]
That's a MAAS issue, you should look at the logs for MAAS to see why it's not starting properly.

**Comment by thyeun** [comment]
thanks, just no luck to make MAAS running, but juju are ok!
