### ISSUE TITLE
LXD fails to install using snap on Debian testing (buster)

### ISSUE THREAD

**Issue by bk** [lxc/lxd#4152]
# Required information

 * Distribution: debian
 * Distribution version: buster (testing)
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.14.0
   * LXC version: 2.0.9 (installed through apt - probably not relevant)
   * LXD version: not installable using snap, not available through apt
   * Storage backend in use: N/A

# Issue description

When attempting to install LXD using the snap package system, the installation fails with in the configuring phase with the message

```
error: cannot perform the following tasks:
- Run configure hook of "lxd" snap if present (run hook "configure": 
-----
cannot bind-mount the mount namespace file /proc/28221/ns/mnt -> lxd.mnt: Permission denied
support process for mount namespace capture exited abnormally
-----)
```

This seems to be because of apparmor not granting a `ptrace` permission.

# Steps to reproduce

 1. Install debian testing ("buster").
 2. Install the snap package manager with `apt install snapd`
 3. Try to install LXD with `snap install lxd`

**Comment by stgraber** [comment]
Not a LXD issue, the problem is that snapd in Debian Buster doesn't play well with AppArmor yet.

**Comment by stgraber** [comment]
To clarify, none of the code in the LXD snap gets run until after `snap install lxd` succeeds, so anything before then is sure to be a snapd bug.

**Comment by pcdummy** [comment]
This is no more an issue on Buster with the latest snapd `2.30-5+b1`.

**Comment by stgraber** [comment]
Excellent, that's for the update!
