### ISSUE TITLE
Live Migration Failed

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#4156]
Trying to live migrate a container which has a quota of 2GB, real usage is 1.6G, free 700GB.
But when arriving to destination node, it failed due to zfs quota reached. (trying to add more than 2G ?).

root@inxovh-hy002 (node2):~# lxc version
2.17

root@inxovh-hy002 (node2):~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

root@inxovh-hy002 (node2):~# lxc list |grep adm
| inxovh-adm001  | RUNNING | 192.168.6.246 (eth2)           |                               | PERSISTENT | 0         |
root@inxovh-hy002 (node2):~# zfs list |grep inxovh-adm001
zdata/lxd/containers/inxovh-adm001       1.61G   740M  1.28G  /var/lib/lxd/storage-pools/de

root@inxovh-hy002 (node2):~# lxc move inxovh-adm001 node3:
Transferring container: inxovh-adm001: 2.01GB (3.11MB/s)
Transferring container: inxovh-adm001: 2.02GB (2.18MB/s)^C

root@inxovh-hy003 (node3):~# zfs list |grep adm001
zdata/lxd/containers/inxovh-adm001            2.00G  4.23M    19K  /var/lib/lxd/storage-pools/default/containers/inxovh-adm001

Jan 10 18:05:56 inxovh-hy003 lxd[12136]: lvl=eror msg="problem with zfs recv: cannot receive new filesystem stream: destination zdata/lxd/containers/inxovh-adm001 space quota exceeded\n." t=2018-01-10T18:05:56+0100

**Comment by stgraber** [comment]
Try increasing the quota before moving, ZFS on the target may end up using more room that on the source, depending on compression and on how much of the container's space was shared with the image it was created on.

**Comment by nlienard** [comment]
Ok will try thanks

**Comment by nlienard** [comment]
Ok if i removed the zfs quota, it works.
i guess it is because of COW on the original node. when it is moving, the container is growing place due to the copy of the initial image used to build the container.
thanks !

PS : cold migration was used because live migration failed.

    root@inxscw-hy001:/etc/network/interfaces.d# lxc stop inxscw-mx003
    error: shutting down the container failed
    Try `lxc info --show-log inxscw-mx003` for more info
    error: Failed container creation:
    -  https://10.2.69.143:8443: Error transferring container data: migration dump failed
        (00.190086) Error (criu/ptrace.c:64): suspending seccomp failed: Invalid argument
        (00.190184) Error (criu/ptrace.c:54): Unable to detach from 27831: No such process
        (00.190209) Error (criu/cr-dump.c:1628): Dumping FAILED.

**Comment by stgraber** [comment]
Ok, good, so that matches what I expected. Unfortunately we can't really tell how big it will be on the target so can't really check this ourselves...
