### ISSUE TITLE
dockerfile and docker-compose equivalent

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#4166]
I recently had to work with dockerfile, and docker-compose using multiple dockerfiles.

I have to say I like

1. the declarative nature of both dockerfile and docker-compose
2. the laziness of the dockerfile building (basically creating a snapshot after each executed line in a dockerfile)

From reading other issues, I understand the the proposed solution sofar is to use one or more shell scripts to handle that use-case.

Unfortunately, this approach has the drawback of not providing the same amount of declarative and reusing power that LXD could provide given an dockerfile and/or docker-compose equivalent.

Especially docker-compose could prove useful, when designing complex scenarios, testing them, and rebuilding them over and over again because of minimal changes.

**Comment by stgraber** [comment]
It's not something that we have an interest in adding to the LXD client at this point.
Scripting should let you do all that today and if someone wants to make a tool that uses a more declarative syntax around it, it should be pretty easy to do with our API.

For the specific case of generating custom LXD images, we are busy reworking the LXC image generation scripts to replace them with a new tool that uses declarative input and outputs a LXC or LXD image. This work is done by @monstermunchkin over in LXC (https://github.com/lxc/lxc/issues/2072).

**Comment by stgraber** [comment]
Closing since we don't expect to do that kind of work in LXD but hopefully the "distrobuilder" work that's ongoing will address at least part of this use case. I'd recommend commenting in that other issue about the kind of thing you need as part of image creation.

**Comment by shantanugadgil** [comment]
for anyone reading this due to a "google search" for "docker compose equivalent for lxd" ... 
I know of one project:
https://github.com/lxdock/lxdock

Haven't used it but seems promising.

**Comment by geaaru** [comment]
add this link for users that searching for something similar to Ansible but with less memory
https://mottainaici.github.io/lxd-compose-docs/
WIP but it works.
