### ISSUE TITLE
proxy: support UNIX protocol

### ISSUE THREAD

**Issue by KishanRPatel** [lxc/lxd#4167]
Currently, the proxy device only supports `TCP-TCP` connections from host to containers by switching network namespaces. The proxy device needs to be extended so that `Unix-TCP`, `TCP-Unix` and `Unix-Unix` connections are supported.

**Comment by stgraber** [comment]
@KishanRPatel is that something you're still interested in doing yourself?

**Comment by KishanRPatel** [comment]
I am interested in working on this and have been looking into it the last couple of days. Unfortunately, the next semester starts on Tuesday, and I really will not have much available time to work on it.

**Comment by stgraber** [comment]
Ok, feel free to post a link to your branch here if you have some early work done on it so that someone else can pick things up later.
