### ISSUE TITLE
Verbose switch with lxc copy doesn't affect verbosity.

### ISSUE THREAD

**Issue by astrablaster** [lxc/lxd#4173]
* Distribution: Ubuntu
 * Distribution version: Bionic
 * The output of "lxc info":
root@nina:~# lxc info
config:
  core.https_address: '[::]:6443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.250.2:6443
  - '[2a01:4240:53f0:60b7:ec6e:80ff:fed4:ba75]:6443'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFZzCCA0+gAwIBAgIQHN2JV3jdShJOHYQV7Sbz+DANBgkqhkiG9w0BAQsFADAz
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRMwEQYDVQQDDApyb290QGFt
    aWxhMB4XDTE3MDcwODExNTQ0NFoXDTI3MDcwNjExNTQ0NFowMzEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBhbWlsYTCCAiIwDQYJ
    KoZIhvcNAQEBBQADggIPADCCAgoCggIBAM7uWXI8UYyxeslTNOrEWPyyybQn6awf
    jCifP0RLdP23F3cTrDZ4ZwJAGBca6lGR/wPwUhgAOiuFdSRu7KlrcxRUhNz+y5Ft
    6t0/mZ9VInkUbnilxUtoZOFxfTzuBVbr1CumNEHfF2ZrpTnMMN+QtwoeUEpXn09V
    pKE9KGrMeuN9B+8Fk+50sAN7c/E2toyiJI0zQL1dtvwddq3HH05Q4dOJ89U6bev5
    dU7wak4uuDtx9mMVSX6siYbTD5vTs6s/3/pG6gYeYASkZIIz4QCVCbN2s/yFZXpY
    AKH2NnAQZ/wewTYx/+PGhyQ8NImlCcHAip2QPd8v9zerCPke0p3rhL9A76IKdwrU
    XL1ym8Fsths9S+kp7qbBczEXa0iwZFwgr2MISfRcnYmNEqi/NkBmu3m8Rfpl7PGt
    Heqzsvu2MmprG5V+Hfest9+t8ye7WTpk0RTdYhPUFpTd1JnzIXR97E0EVoNSmuhj
    2ZRc8jTj60ZkMJHuPyI9ThLULd4RRpGzrRB9VH1dSja+mnk5K481U8gog7dPBnE0
    hllXTtTrsJyc1zNabA0oJkE3fY7+ZvFn6WnBJnCP9frBSM3NDOTnN3Uo/FM09yIQ
    t4t7oJjhgF9ZrHwqIqP8+f7eHOqu8fMqSytBXwRDnoeiRic4tYbUIq3/YyCzL01s
    g8E1cLYsYrQjAgMBAAGjdzB1MA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMEAGA1UdEQQ5MDeCBWFtaWxhhwTAqP8ChwTA
    qAQBhwQKAAMBhwTAqHoBhwTAqPoChxAqAUJAU/Bgt5begP/+s1A3MA0GCSqGSIb3
    DQEBCwUAA4ICAQCRgHgiV1XGGSl5R0u/Ruf/TSJUZyVlg7qmDJgsMgJJ1LUxQaaD
    ysths5mIHnVbKLR6AxcaWbOIvZIpGhezJxxgVSPgieQQKbym+suc+z+2riPycnoq
    IK0dwmfpJ21ahXkX2iHs66k6J/NxPKAUoyJZyqKdX1SJpmBG6mTMpDbCA2lnv7t+
    5Atu6WnpQcNRxUGtfjt8ddcPxva/iJPqyEtDdXBbtIxjgaPmlaIrx0U695HUw6Ok
    izwgOqKLj/iA/tiJyBhoURaAXVVvdbW0cnec4DjDxGw/T+QU2W2n7t8bQYEclD/v
    OD6C+aL8C7hgrUJVWT2oAbjI4VZC+FCy91G6itEKwaUrf4WC2xZWQOqvmac9frYa
    HQb76x03XJMpvxSR++mi1upzB3ljmp/rO+GguPqKFw4h8plSbZqN3pXWAJlhxsJX
    X2BOz7pnJiUZPNMUrU9S2dtIkTLQCFPzMI4YYMnDHcELjZ36xIWDzNdbRP0SYA2T
    S5R1qUC1y8sd9tWaG2/jENhvQCroUx86iQn+XOgj86+af5oc3uBFXmV3iBUOlv5X
    OZqj0+ZpJu/02OtUHNwnGvyY88TKVdgPX2PJOb3nEUD0MkSve5+AGbhd1mzgBrnS
    PcACeHVdFu3pcoOB3R9Z/dK/019OQ52dXUYMozOGPhPNfc3aq+zPJzJePA==
    -----END CERTIFICATE-----
  certificate_fingerprint: 47da8046f21edb31763553b3b638990aaa0cb87c2e19ebeb1d26187ef2c138c9
  driver: lxc
  driver_version: 2.1.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.14.0-11-generic
  server: lxd
  server_pid: 25484
  server_version: "2.21"
  storage: zfs | dir
  storage_version: 0.7.3-1ubuntu1 | 1

# Issue description
lxc copy --verbose is no more verbose.
Do copy container with and without --verbose. The output is always non-verbose.
I remember it used to be really verbose in older lxd versions. The --debug is working as expected.

# Steps to reproduce
lxc copy local:alp01 amila: --container-only --verbose

**Comment by stgraber** [comment]
Not a bug, there is no log message in place for that log level in that particular operation.
It could be that in the past --verbose was wrongly mapped to the DEBUG log level, that is not the case anymore.

**Comment by stgraber** [comment]
--verbose gets you INFO, --debug gets you DEBUG, default logging gets you WARN

**Comment by astrablaster** [comment]
It used to be like this:
root@amila:~# lxc copy local:art01 nina:art01a --container-only --verbose       
INFO[06-29|13:58:45] Connecting to a local LXD over a Unix socket 
INFO[06-29|13:58:45] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
INFO[06-29|13:58:45] Connecting to a remote LXD over HTTPs 
INFO[06-29|13:58:45] Sending request to LXD                   etag= method=GET url=https://nina.w-w.cz:6443/1.0
INFO[06-29|13:58:45] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0/containers/art01
INFO[06-29|13:58:45] Sending request to LXD                   etag= method=POST url=http://unix.socket/1.0/containers/art01
INFO[06-29|13:58:45] Sending request to LXD                   etag= method=POST url=https://nina.w-w.cz:6443/1.0/containers
INFO[06-29|13:58:45] Sending request to LXD                   etag= method=GET url=https://nina.w-w.cz:6443/1.0/operations/dd309fc4-5a29-4a0c-8311-a9bb8d7ff4c0
INFO[06-29|13:58:55] Sending request to LXD                   etag= method=POST url=https://nina.w-w.cz:6443/1.0/containers
INFO[06-29|13:58:55] Sending request to LXD                   etag= method=GET url=https://nina.w-w.cz:6443/1.0/operations/d24934d1-bf41-4a2c-b3c1-1bbdb6865b0c
INFO[06-29|13:59:05] Sending request to LXD                   etag= method=POST url=https://nina.w-w.cz:6443/1.0/containers

**Comment by stgraber** [comment]
608a80195eeb4358bc2bbaf0685fdb3ac377fac7 demoted all of those to debug as they were too verbose for our taste.

**Comment by stgraber** [comment]
I think I did that around the same time as we started introducing some more useful verbose-level messages in some commands (`lxc file` for example).
