### ISSUE TITLE
Cannot add PPA: 'ppa:~ubuntu-lxc/ubuntu/lxd-stable'. The team named '~ubuntu-lxc' has no PPA named 'ubuntu/lxd-stable'

### ISSUE THREAD

**Issue by tanieee28** [lxc/lxd#4176]
command typed - add-apt-repository ppa:ubuntu-lxc/lxd-stable

**Comment by stgraber** [comment]
The PPA has been deprecated. Use the official backport packages or use the snap.

A warning message was shown to all existing users for two months and the same message was repeated in all our release announcements and weekly news too.

**Comment by vazir** [comment]
@stgraber cound you please recommend which one specificially can replace the deprecated PPA? Just hit the same issue - i would not like to experiment on the production server, trying different PPAs, and would rather prefer using a recommended one which was tested for 16.04 and be safely upgradable

**Comment by stgraber** [comment]
@vazir per the instructions we've been posting everywhere, for 16.04 users, you want to do:

    apt install -t xenial-backports lxd lxd-client

This message was listed in our PPA deprecation post, in all LXD upgrade messages for the two months prior to the PPAs going away and in all our weekly posts during that period too.

**Comment by vazir** [comment]
@stgraber Thank you for noticing! I understand your annoyance, but you should understand us (users of LXC/LXD) too - We use LXC/LXD to run our business logic, and our focus not to follow what is happening with LXC/LXD, forums, discussions, etc LXD development, but totally different stuff. And we pay attention to that only when something, supposedly 'stable' breaks. 15 minutes google search gives no viable answer to my question, that why I asked, you, the primary source directly :) (Sorry for that, but who else?)

**Comment by stgraber** [comment]
Odd, the 3 first Google results here for LXD PPA deprecation all point to suitable posts with instructions on getting to backports.

**Comment by hmilkovi** [comment]
Nice that you broken LXD v2.21 install on ubuntu 14.04.

**Comment by rptb1** [comment]
Just for info, I got here because https://blog.ubuntu.com/2015/03/20/installing-lxd-and-the-command-line-tool was misleading me about this PPA.

**Comment by aplatypus** [comment]
The most recent stable lcd snap will only run on my Ubuntu 19.04 if i run it as Rooy.  Some problem with xauthorise or selinux it seems, from launchpad.

I just think it is ADVISABLE to transition critical system level and infrastructure things like lxd  and not to drop 'customers' in to an under tested/qualified new method with no  woek around.

I can't believe any one is going to use lxd if it can only work as sudo/root.

If you want a new installer just keep the previous merhod for 3 or 4 releases.  Until all the bugs are wirjed out of snap.

**Comment by GopherJ** [comment]
```
E: The value 'xenial-backports' is invalid for APT::Default-Release as such a release is not available in the sources
```
I still have issue...

it's strange that lxd relies so much snap...we don't like snap at all and we will never switch to it...

**Comment by aplatypus** [comment]
More to the point No Snap-s have ever worked on our set-usp because the home directory is never the root mount.  The 'after' mount bind mount solution doesn't correct/work around the problem.  From this point of view that effectively blocks LXD from use on this site because we aren't going to support building our own PPA.  Not sure why an organisation develops a technology like this only to block its use in the real world.
