### ISSUE TITLE
lxc file push fails for some paths starting with 'dev'

### ISSUE THREAD

**Issue by sanderbrandenburg** [lxc/lxd#4181]
System: Ubuntu 16.04.3 LTS
snap: stable or edge (and w/ and without devmode)

# Issue description

We have a habit of using a /developer directory to store our development stuff into for our workstations. Lately we've migrated from the LXD PPA to LXD snap. Then we experienced a problem with lxc file push and directories starting with 'dev'.

# Steps to reproduce
```
sander@sander-desktop / % lxc list sal-dev2
+----------+---------+------+------+------------+-----------+
|   NAME   |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+----------+---------+------+------+------------+-----------+
| sal-dev2 | STOPPED |      |      | PERSISTENT | 0         |
+----------+---------+------+------+------------+-----------+
sander@sander-desktop / % testpush() {
sudo mkdir -p $1
sudo touch $1/z
lxc file push $1/z sal-dev2/ && echo SUCCESS
}
sander@sander-desktop / % testpush /boot2
SUCCESS <-- OK!
sander@sander-desktop / % testpush dev2
error: open /dev2/z: no such file or directory <-- NOT OK!
sander@sander-desktop / % testpush /dev2
error: open /dev2/z: no such file or directory <-- NOT OK!
sander@sander-desktop / % testpush /dev/test
SUCCESS <-- HUH?
```

# Information to attach
I tried to narrow this down somewhat:
`sudo strace -ff -e trace=file,process,mount lxc file push /dev2/z sal-dev2/`
using '/dev2/z' leads to this call failing somewhere within the internals of snap:
`[pid 29205] openat(AT_FDCWD, "/dev2/z", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)`
But using '/boot2/z' leads to this call:
`[pid 29534] openat(AT_FDCWD, "/var/lib/snapd/hostfs/boot2/z", O_RDONLY|O_CLOEXEC) = 3`

I could not find out where this goes wrong. It felt like some Apparmor problems, but --devmode did not change any behavior as far as I can tell. Also, it's very odd that pushing /dev/test/z is OK, but /dev2/z is not, it smells like some security policy mapping gone wrong.

**Comment by stgraber** [comment]
Oh, I think I know why :)

**Comment by sanderbrandenburg** [comment]
I can confirm it works for me on build edge/git-6e76328.

Thanks!

**Comment by stgraber** [comment]
Cool, I'll cherry-pick this fix and a few others soon so that you don't have to stay on edge for it.
