### ISSUE TITLE
lxd's SNAP check is arguably too broad

### ISSUE THREAD

**Issue by nacc** [lxc/lxd#4183]
Currently, util.go is checking if SNAP is set in the environment to determine if lxd is being run as a snap. However, this may not be true if a classic snap is calling the host's lxd and the host's lxd is not a snap!

I believe this check should be narrowed to both SNAP being set and 'lxd' being in the set value. Thoughts?

https://github.com/lxc/lxd/blob/7a5245c32e15d4db5a19360310e758c58b7de32d/shared/util.go#L117

**Comment by stgraber** [comment]
Checking for SNAP_NAME == lxd should fix this

**Comment by nacc** [comment]
On Jan 20, 2018 11:44, "Stéphane Graber" <notifications@github.com> wrote:

Checking for SNAP_NAME == lxd should fix this


Oh yeah that makes total sense.

Thanks,
Nish

**Comment by kyrofa** [comment]
This is breaking snapcraft cleanbuilds. Any ETA for when this will land in xenial backports?

**Comment by stgraber** [comment]
Probably not another couple of weeks, note that you can workaround this easily enough by simply unsetting the SNAP env variable prior to shelling out to the "lxc" command line tool
