### ISSUE TITLE
Added Proxy Device fails to start

### ISSUE THREAD

**Issue by schkovich** [lxc/lxd#4186]
# Required information
 * Distributor ID:	Ubuntu
 * Description:	Ubuntu 16.04.3 LTS
 * Release:	16.04
 * Codename:	xenial
   * Kernel version: 4.4.0-109-generic x86_64 GNU/Linux
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: ZFS
   * Installation: snap
   * tracking: edge
   * installed: git-8c3633c (5451)
# Issue description

I would like to expose Juju GUI running in a container to the local network. To do that I need to proxy traffic coming to the host interface connected to the local network to the container interface on which Juju GUI is listening. 

I added a proxy device without a problem but nobody is listening.

Proxy log shows missing library.
```
tail: /var/snap/lxd/common/lxd/logs/juju-1caef8-1/proxy.proxy0.log: file truncated
Listening on tcp:192.168.50.196:443 in 24878, forwarding to tcp:10.0.10.147:443 from 12226
Re-executing proxy process
lxd: error while loading shared libraries: liblxc.so.1: cannot open shared object file: No such file or directory
```
# Steps to reproduce

 1. Create a container `lxc launch ubuntu:xenial juju-1caef8-1` 
 2. Add a proxy device `lxc config device add juju-1caef8-1 proxy0 proxy listen=tcp:192.168.50.196:443 connect=tcp:10.0.10.147:443 bind=host`
 3. Check if the device is there
```
lxc config device show juju-1caef8-1
proxy0:
  bind: host
  connect: tcp:10.0.10.147:443
  listen: tcp:192.168.50.196:443
  type: proxy
```
4. Connection fails
```
wget https://192.168.50.196/ --no-check-certificate
--2018-01-20 01:06:38--  https://192.168.50.196/
Connecting to 192.168.50.196... failed: Connection refused.
```
5. See if there is a listner on the port 443
```
sudo netstat -tulp | grep 443
tcp6       0      0 [::]:8443               [::]:*                  LISTEN      24878/lxd
```
# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [x] Output of the client with --debug
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

[lxc-info.log](https://github.com/lxc/lxd/files/1649313/lxc-info.log)
[proxy.log](https://github.com/lxc/lxd/files/1649314/proxy.log)
[dmesg.log](https://github.com/lxc/lxd/files/1649315/dmesg.log)
[monitor.log](https://github.com/lxc/lxd/files/1649316/monitor.log)
[main-daemon.log](https://github.com/lxc/lxd/files/1649317/main-daemon.log)
[config-expanded.log](https://github.com/lxc/lxd/files/1649318/config-expanded.log)
[lxc-info-showlog.log](https://github.com/lxc/lxd/files/1649319/lxc-info-showlog.log)
[command-debug.log](https://github.com/lxc/lxd/files/1649320/command-debug.log)

**Comment by simos** [comment]
I got this replicated. 

I believe the issue is what is shown in the proxy.log,

```
tail: /var/snap/lxd/common/lxd/logs/juju-1caef8-1/proxy.proxy0.log: file truncated
Listening on tcp:192.168.50.196:443 in 24878, forwarding to tcp:10.0.10.147:443 from 12226
Re-executing proxy process
lxd: error while loading shared libraries: liblxc.so.1: cannot open shared object file: No such file or directory

```
When the proxy process is re-executed, it cannot find liblxc.so.1 (which is available in the snap).

**Comment by schkovich** [comment]
exactly @simos 
```
$ locate liblxc.so.1
/snap/lxd/5461/lib/liblxc.so.1
/snap/lxd/5461/lib/liblxc.so.1.3.0
/snap/lxd/5463/lib/liblxc.so.1
/snap/lxd/5463/lib/liblxc.so.1.3.0
```
The question is which environment variables are there for the proxy process when re-executed. [syscall.Exec](https://golang.org/pkg/syscall/#Exec) third argument is an [empty array of strings](https://github.com/lxc/lxd/blob/master/lxd/main_proxy.go#L59) which is logical since the parrent process is self referenced `/proc/self/exe`. However, some magic is [done](https://github.com/lxc/lxd/issues/2504#issuecomment-344442097) in [main_nsexec.go](https://github.com/lxc/lxd/blob/master/lxd/main_nsexec.go) and I am not sure which environmental variables are passed when that is done. If I am following [the idea](https://github.com/lxc/lxd/issues/2504#issuecomment-306252851) correctly the parrent process should be the one that is created on adding a new proxy device.  

I could be completely wrong, of course. I have browsed the code a few days ago for the first time and I am not the Golang native speaker. :smile: Though, I would like to become one. :angel:

**Comment by schkovich** [comment]
It does not sound like a packaging issue. liblxc.so.1 is exposed in the definition of the [lxc component](https://github.com/schkovich/lxd-pkg-snap/blob/latest-edge/snapcraft.yaml#L219) and the libraries that are given in `lxc:prime` are added to `LD_LIBRARY_PATH` in `daemon.start` [wrapper](https://github.com/schkovich/lxd-pkg-snap/blob/d49b5b5c60401b116e35351723cc8acca670e061/snapcraft/wrappers/daemon.start#L16).

**Comment by simos** [comment]
I just compiled LXD from source, set up a container with a web server and added the new proxy device. 
All this in an KVM VM (using multipass, from the snap package).
I then managed to access the container web server from outside the KVM VM, as expected.

**Comment by schkovich** [comment]
I was about to do that. So, packaging, most likely. :smile: 

I will do it the same on metal and revert.

**Comment by schkovich** [comment]
@simos confirmed. I compiled LXD from the source, launched a container,  added tiny nodejs server, added a proxy device and accessed the launched container from outside.

I will take a look at [lxc/lxd-pkg-snap](https://github.com/lxc/lxd-pkg-snap).

**Comment by stgraber** [comment]
I'll take a look, should be easy enough to track down.

**Comment by stgraber** [comment]
And reproduced, now to figure out what's going on... my best guess is that LD_LIBRARY_PATH is being stripped for some reason in the subprocess, but no idea why that would be.

**Comment by stgraber** [comment]
Got it.

**Comment by schkovich** [comment]
Sorry, but f30b697 did not fix the problem.
```
$ lxc config device add xen2 proxy0 proxy listen=tcp:192.168.50.196:8080 connect=tcp:10.0.10.185:8080 bind=host
Device proxy0 added to xen2
$ sudo cat /var/snap/lxd/common/lxd/logs/xen2/proxy.proxy0.log
Listening on tcp:192.168.50.196:8080 in 3792, forwarding to tcp:10.0.10.185:8080 from 19579
Re-executing proxy process
lxd: error while loading shared libraries: liblxc.so.1: cannot open shared object file: No such file or directory
```
There is a new error in `lxc.log`.
```
goran.miskovic@srv-ops1:~$ sudo cat /var/snap/lxd/common/lxd/logs/xen2/lxc.log
            lxc 20180126111107.450 WARN     lxc_conf - conf.c:lxc_map_ids:2757 - newuidmap binary is missing
            lxc 20180126111107.450 WARN     lxc_conf - conf.c:lxc_map_ids:2763 - newgidmap binary is missing
            lxc 20180126111107.476 WARN     lxc_conf - conf.c:lxc_map_ids:2757 - newuidmap binary is missing
            lxc 20180126111107.476 WARN     lxc_conf - conf.c:lxc_map_ids:2763 - newgidmap binary is missing
```
@stgraber let me know if you need more details from logs.

**Comment by simos** [comment]
@schkovich Did you create the snap package yourself? The official snap package for LXD in the `edge` channel is still at the following commit,

```
channels:                           
  stable:        2.21        (5494) 45MB -
  candidate:     2.21        (5494) 45MB -
  beta:          ↑                       
  edge:          git-1fa4ddd (5504) 46MB -

```

and does not include the fix (see https://github.com/lxc/lxd/commits/master)

**Comment by schkovich** [comment]
@simos you are right. I checked if f30b697 is in master and did not go to commit list. Sorry. :disappointed: 

Meanwhile, I snaped lxd and, yes, it's working like a charm. :smile: 
```
