### ISSUE TITLE
lxd init error: Unable to talk to LXD: Get http://unix.socket/1.0: read unix @->/var/lib/lxd/unix.socket: read: connection reset by peer

### ISSUE THREAD

**Issue by kc004** [lxc/lxd#4189]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails: Error : Connection refused; is LXD running?
   * Kernel version: 4.4.0-83-generic
   * LXD version:  2.0.11
   * Storage backend in use:

# Issue description
sudo lxd init shows an error: Unable to talk to LXD: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: connection refused

I configured lxd using dpkg-reconfigure -p medium lxd but it couldn't help.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
[448962.628461] audit: type=1400 audit(1516620018.396:112): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/lxd/lxd-bridge-proxy" pid=62520 comm="apparmor_parser"
[451129.284274] audit: type=1400 audit(1516622185.053:113): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/lxd/lxd-bridge-proxy" pid=26414 comm="apparmor_parser"

 - [ ] Container log (`lxc info NAME --show-log`)
Connection refused; is LXD running?
 - [ ] Container configuration (`lxc config show NAME --expanded`)
Connection refused; is LXD running?
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
lvl=info msg="LXD 2.0.11 is starting in normal mode" path=/var/lib/lxd t=2018-01-22T11:18:03+0100
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-01-22T11:18:03+0100
lvl=info msg="Kernel uid/gid map:" t=2018-01-22T11:18:03+0100
lvl=info msg=" - u 0 0 4294967295" t=2018-01-22T11:18:03+0100
lvl=info msg=" - g 0 0 4294967295" t=2018-01-22T11:18:03+0100
lvl=info msg="Configured LXD uid/gid map:" t=2018-01-22T11:18:03+0100
lvl=info msg=" - u 0 231072 65536" t=2018-01-22T11:18:03+0100
lvl=info msg=" - g 0 231072 65536" t=2018-01-22T11:18:03+0100
lvl=info msg="Expiring log files" t=2018-01-22T11:18:03+0100
lvl=info msg="Done expiring log files" t=2018-01-22T11:18:03+0100
lvl=info msg="Starting /dev/lxd handler" t=2018-01-22T11:18:03+0100
lvl=info msg="LXD is socket activated" t=2018-01-22T11:18:03+0100
lvl=info msg="REST API daemon:" t=2018-01-22T11:18:03+0100
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2018-01-22T11:18:03+0100
lvl=info msg="Pruning expired images" t=2018-01-22T11:18:03+0100
lvl=info msg="Done pruning expired images" t=2018-01-22T11:18:03+0100
lvl=info msg="Updating instance types" t=2018-01-22T11:18:03+0100
lvl=info msg="Updating images" t=2018-01-22T11:18:03+0100
lvl=info msg="Done updating images" t=2018-01-22T11:18:03+0100
lvl=info msg="Done updating instance types" t=2018-01-22T11:18:04+0100
lvl=info msg="Received 'terminated signal', exiting." t=2018-01-22T11:18:29+0100
lvl=info msg="Stopping REST API handler:" t=2018-01-22T11:18:29+0100
lvl=info msg=" - skipping socket-activated socket" socket=/var/lib/lxd/unix.socket t=2018-01-22T11:18:29+0100
lvl=info msg="Stopping /dev/lxd handler" t=2018-01-22T11:18:29+0100
lvl=info msg="Stopped /dev/lxd handler" t=2018-01-22T11:18:29+0100
lvl=info msg="Unmounting temporary filesystems" t=2018-01-22T11:18:29+0100
lvl=info msg="Done unmounting temporary filesystems" t=2018-01-22T11:18:30+0100
lvl=info msg="Closing the database" t=2018-01-22T11:18:30+0100
lvl=info msg="Saving simplestreams cache" t=2018-01-22T11:18:30+0100
lvl=info msg="Saved simplestreams cache" t=2018-01-22T11:18:30+0100

 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

$ systemctl status lxd-bridge

● lxd-bridge.service - LXD - network bridge
   Loaded: loaded (/lib/systemd/system/lxd-bridge.service; static; vendor preset: enabled)
   Active: **failed** (Result: exit-code) since Mon 2018-01-22 13:00:00 CET; 28min ago
     Docs: man:lxd(1)
  Process: 27917 ExecStart=/usr/lib/lxd/lxd-bridge.start (code=exited, status=2)
 Main PID: 27917 (code=exited, status=2)

systemd[1]: Failed to start LXD - network bridge.
systemd[1]: Failed to start LXD - network bridge.
systemd[1]: Failed to start LXD - network bridge.
systemd[1]: Failed to start LXD - network bridge.
systemd[1]: Failed to start LXD - network bridge.
systemd[1]: Failed to start LXD - network bridge.
systemd[1]: Failed to start LXD - network bridge.
systemd[1]: Failed to start LXD - network bridge.
systemd[1]: Failed to start LXD - network bridge.
systemd[1]: Failed to start LXD - network bridge.

**Comment by kc004** [comment]
$ systemctl status lxd-bridge

● lxd-bridge.service - LXD - network bridge
   Loaded: loaded (/lib/systemd/system/lxd-bridge.service; static; vendor preset: enabled)
   Active: **failed** (Result: exit-code) since Mon 2018-01-22 13:00:00 CET; 28min ago
     Docs: man:lxd(1)
  Process: 27917 ExecStart=/usr/lib/lxd/lxd-bridge.start (code=exited, status=2)
 Main PID: 27917 (code=exited, status=2)

Jan 22 13:00:01 druid2 systemd[1]: Failed to start LXD - network bridge.
Jan 22 13:00:01 druid2 systemd[1]: Failed to start LXD - network bridge.
Jan 22 13:00:01 druid2 systemd[1]: Failed to start LXD - network bridge.
Jan 22 13:00:01 druid2 systemd[1]: Failed to start LXD - network bridge.
Jan 22 13:00:01 druid2 systemd[1]: Failed to start LXD - network bridge.
Jan 22 13:00:01 druid2 systemd[1]: Failed to start LXD - network bridge.
Jan 22 13:00:01 druid2 systemd[1]: Failed to start LXD - network bridge.
Jan 22 13:00:01 druid2 systemd[1]: Failed to start LXD - network bridge.
Jan 22 13:00:01 druid2 systemd[1]: Failed to start LXD - network bridge.
Jan 22 13:00:01 druid2 systemd[1]: Failed to start LXD - network bridge.

**Comment by stgraber** [comment]
Can you post the output of `bash -x /usr/lib/lxd/lxd-bridge start`?

**Comment by stgraber** [comment]
Those weird failures tend to be either firewall related or caused by a conflicting DNS server on the system, sadly lxd-bridge doesn't make that very easy to diagnose, newer LXD releases with the network API are quite a bit better at reporting such issues.

**Comment by kc004** [comment]
@stgraber  Sorry for late reply.
Here is my output of `bash -x /usr/lib/lxd/lxd-bridge start`

+ config=/etc/default/lxd-bridge
+ varrun=/run/lxd-bridge/
+ varlib=/var/lib/lxd-bridge/
+ USE_LXD_BRIDGE=true
+ LXD_BRIDGE=lxdbr0
+ LXD_CONFILE=
+ LXD_DOMAIN=
+ LXD_IPV4_ADDR=
+ LXD_IPV4_NETMASK=
+ LXD_IPV4_NETWORK=
+ LXD_IPV4_DHCP_RANGE=
+ LXD_IPV4_DHCP_MAX=
+ LXD_IPV4_NAT=false
+ LXD_IPV4_FIREWALL=true
+ LXD_IPV6_ADDR=
+ LXD_IPV6_MASK=
+ LXD_IPV6_NETWORK=
+ LXD_IPV6_NAT=false
+ LXD_IPV6_FIREWALL=true
+ LXD_IPV6_PROXY=true
+ '[' '!' -f /etc/default/lxd-bridge ']'
+ . /etc/default/lxd-bridge
++ USE_LXD_BRIDGE=true
++ LXD_BRIDGE=lxdbr0
++ UPDATE_PROFILE=true
++ LXD_CONFILE=
++ LXD_DOMAIN=lxd
++ LXD_IPV4_ADDR=10.247.162.1
++ LXD_IPV4_NETMASK=255.255.255.0
++ LXD_IPV4_NETWORK=10.247.162.1/24
++ LXD_IPV4_DHCP_RANGE=10.247.162.2,10.247.162.254
++ LXD_IPV4_DHCP_MAX=252
++ LXD_IPV4_NAT=true
++ LXD_IPV6_ADDR=
++ LXD_IPV6_MASK=
++ LXD_IPV6_NETWORK=
++ LXD_IPV6_NAT=false
++ LXD_IPV6_PROXY=false
+ use_iptables_lock=-w
+ iptables -w -L -n
+ use_iptables_lock=
+ HAS_IPV6=false
+ '[' -e /proc/sys/net/ipv6/conf/default/disable_ipv6 ']'
++ cat /proc/sys/net/ipv6/conf/default/disable_ipv6
+ '[' 0 = 0 ']'
+ HAS_IPV6=true
+ case "${1}" in
+ start
+ '[' xtrue = xtrue ']'
+ '[' '!' -f /run/lxd-bridge//network_up ']'
+ '[' -d /sys/class/net/lxdbr0 ']'
+ FAILED=1
+ trap cleanup EXIT HUP INT TERM
+ set -e
+ '[' '!' -d /sys/class/net/lxdbr0 ']'
+ ip link add dev lxdbr0 type bridge
RTNETLINK answers: Operation not permitted
+ cleanup
+ set +e
+ '[' 1 = 1 ']'
+ echo 'Failed to setup lxd-bridge.'
Failed to setup lxd-bridge.
+ stop force
+ '[' -f /run/lxd-bridge//network_up ']'
+ '[' force = force ']'
+ '[' -d /sys/class/net/lxdbr0 ']'
+ rm -f /run/lxd-bridge//network_up

**Comment by stgraber** [comment]
```
ip link add dev lxdbr0 type bridge
RTNETLINK answers: Operation not permitted
```

That seems to indicate that your kernel isn't capable of creating a bridge.

**Comment by stgraber** [comment]
As you are on a very very outdated version of the Ubuntu 4.4 kernel, I'd strongly recommend you make sure your system is up to date on package updates, then reboot it, which should get you a 4.4.0-112 kernel (rather than -83) which will hopefully include the bridge kernel module that you appear to be missing right now.

**Comment by thalesmaoa** [comment]
Same error here, however my kernel is 4.4.0-134-generic.

**Comment by stgraber** [comment]
@thalesmaoa if the manual `ip link add` also fails, then you're somehow missing the bridging kernel modules. You can try to manually modprobe those and look at dmesg for sign of errors.

**Comment by thalesmaoa** [comment]
@stgraber Thanks! It work! Can you please guide me to find where the problem is?
I found out that there was a lxc previous installation and some libvirt files else where. Manually deleted everything. Tutorial went fine, however during start it troughs unix.socket error. I can manually start and launch.

Have no idea whats going on!
