### ISSUE TITLE
Live addition/removal of network interfaces

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#419]
Update to the container's devices dict should when possible be applied immediately, so leading to new network devices being created and attached and in cases where it's possible, drives too.

**Comment by hallyn** [comment]
For clarity's sake - do we want to do this only with "lxc config device add...", or also with "lxc profile device add" for all containers using said profile?

**Comment by stgraber** [comment]
We should do it for profiles too. Basically the idea is to reduce the amount of changes which require a container reboot to be applied to as close to zero as possible.
