### ISSUE TITLE
Live migration of containers

### ISSUE THREAD

**Issue by upuvvad1** [lxc/lxd#4190]
Hi @stgraber,
From the Linux Plumbers conference last year, I heard that CRIU has pushed a patch for live migration using the process_vmsplice system call.
1) Does the recent version of LXC support live migration with 0 downtimes?
2) If not, is there any roadmap for the same?

Thanks,
Udaya Puvvadi

**Comment by dnegreira** [comment]
Hi @upuvvad1 I believe the following thread answers your question: https://discuss.linuxcontainers.org/t/live-migration-between-2-hosts-fails/1030/10

**Comment by brauner** [comment]
@adrianreber any thoughts on this? :)

**Comment by adrianreber** [comment]
@upuvvad1: there is of course nothing like 0 downtime. I am pretty sure there will never be anything with 0 downtime. Besides that, @brauner and I recently pushed changes to LXD to support pre-copy migration in LXD, which can, depending on the processes in the container, decrease downtime during migration: https://github.com/lxc/lxd/pull/4072

We will also talk about that at FOSDEM in two weeks:

https://fosdem.org/2018/schedule/event/containers_optimized_migration/

To further decrease downtime during migration post-copy (lazy) migration which CRIU supports through userfaultfd could be implemented for LXC/LXD.

**Comment by upuvvad1** [comment]
Hi @adrianreber ,
I see that the commit was pushed to 2.21 tag, and bionic release of ubuntu.
I installed the 2.21 release of LXD, and 3.6 release of CRIU from bionic releases, and have issues with the live migration.

The following is the log on the source host"

`actionscript=false created=2018-01-23T18:10:42+0000 ephemeral=false features=1 lvl=info msg="Migrating container" name=delicate-fawn predumpdir= statedir= stop=false t=2018-01-23T13:23:17-0500 used=2018-01-23T18:22:10+0000
actionscript=false created=2018-01-23T18:10:42+0000 ephemeral=false features=1 lvl=info msg="CRIU feature check failed" name=delicate-fawn predumpdir= statedir= stop=false t=2018-01-23T13:23:17-0500 used=2018-01-23T18:22:10+0000
actionscript=true created=2018-01-23T18:10:42+0000 ephemeral=false features=0 lvl=info msg="Migrating container" name=delicate-fawn predumpdir= statedir=/tmp/lxd_checkpoint_674874618 stop=true t=2018-01-23T13:23:20-0500 used=2018-01-23T18:22:10+0000
actionscript=true created=2018-01-23T18:10:42+0000 ephemeral=false features=0 lvl=info msg="Failed migrating container" name=delicate-fawn predumpdir= statedir=/tmp/lxd_checkpoint_674874618 stop=true t=2018-01-23T13:23:28-0500 used=2018-01-23T18:22:10+0000
lvl=eror msg="dump failed after successful restore?: \"migration dump failed\\n(01.594080) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 26250 with interrupted system call\\n(01.873972) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 26258 with interrupted system call\\n(03.232484) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 26291 with interrupted system call\\n(03.554447) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 26313 with interrupted system call\\n(03.554822) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 26320 with interrupted system call\\n(03.858201) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 26349 with interrupted system call\\n(03.858945) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 26352 with interrupted system call\\n(03.868004) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 26331 with interrupted system call\\n(04.174115) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 26341 with interrupted system call\\n(04.174521) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 26344 with interrupted system call\\n(04.456308) Warn  (compel/arch/x86/src/lib/infect.c:249): Will restore 26480 with interrupted system call\\n(08.200428) Error (criu/util.c:669): exited, status=1\\n(08.200465) Error (criu/action-scripts.c:94): Script /tmp/lxd_checkpoint_674874618/action.sh exited with -1\\n(08.200484) Error (criu/action-scripts.c:138): One of more action scripts failed\"" t=2018-01-23T13:23:28-0500`

The following is the log on the destination host"

`ephemeral=false lvl=info msg="Creating container" name=delicate-fawn t=2018-01-23T13:23:16-0500
ephemeral=false lvl=info msg="Created container" name=delicate-fawn t=2018-01-23T13:23:16-0500
lvl=warn msg="Unable to update backup.yaml at this time." name=delicate-fawn t=2018-01-23T13:23:17-0500
lvl=warn msg="Unable to update backup.yaml at this time." name=delicate-fawn t=2018-01-23T13:23:17-0500
actionscript=false created=2018-01-23T18:23:16+0000 ephemeral=false features=0 lvl=info msg="Migrating container" name=delicate-fawn predumpdir= statedir=/tmp/lxd_restore_310195855 stop=false t=2018-01-23T13:23:26-0500 used=1970-01-01T00:00:00+0000
action=stop created=2018-01-23T18:23:16+0000 ephemeral=false lvl=info msg="Container initiated stop" name=delicate-fawn stateful=false t=2018-01-23T13:23:28-0500 used=2018-01-23T18:23:26+0000
action=stop created=2018-01-23T18:23:16+0000 ephemeral=false lvl=info msg="Container initiated stop" name=delicate-fawn stateful=false t=2018-01-23T13:23:28-0500 used=2018-01-23T18:23:26+0000
err="remove /sys/kernel/security/apparmor/policy/namespaces/lxd-delicate-fawn_<var-lib-lxd>: no such file or directory" lvl=eror msg="error removing apparmor namespace" ns=/sys/kernel/security/apparmor/policy/namespaces/lxd-delicate-fawn_<var-lib-lxd> t=2018-01-23T13:23:28-0500
err="open /tmp/lxd_restore_310195855/final/restore.log: no such file or directory" lvl=eror msg="Error collecting checkpoint log file" t=2018-01-23T13:23:28-0500
err="Failed to run: /usr/bin/lxd forkmigrate delicate-fawn /var/lib/lxd/containers /var/log/lxd/delicate-fawn/lxc.conf /tmp/lxd_restore_310195855/final true: " lvl=eror msg="Error during migration sink" t=2018-01-23T13:23:28-0500
created=2018-01-23T18:23:16+0000 ephemeral=false lvl=info msg="Deleting container" name=delicate-fawn t=2018-01-23T13:23:28-0500 used=1970-01-01T00:00:00+0000
action=R err="Failed to run: apparmor_parser -RWL /var/lib/lxd/security/apparmor/cache /var/lib/lxd/security/apparmor/profiles/lxd-delicate-fawn: apparmor_parser: Unable to remove \"lxd-delicate-fawn_</var/lib/lxd>\".  Profile doesn't exist" lvl=eror msg="Running apparmor" output="apparmor_parser: Unable to remove \"lxd-delicate-fawn_</var/lib/lxd>\".  Profile doesn't exist\n" t=2018-01-23T13:23:28-0500
container=delicate-fawn err="Failed to run: apparmor_parser -RWL /var/lib/lxd/security/apparmor/cache /var/lib/lxd/security/apparmor/profiles/lxd-delicate-fawn: apparmor_parser: Unable to remove \"lxd-delicate-fawn_</var/lib/lxd>\".  Profile doesn't exist" lvl=eror msg="Failed to destroy apparmor namespace" t=2018-01-23T13:23:28-0500
created=2018-01-23T18:23:16+0000 ephemeral=false lvl=info msg="Deleted container" name=delicate-fawn t=2018-01-23T13:23:29-0500 used=1970-01-01T00:00:00+0000
`

Can you please share your insights about this?

**Comment by adrianreber** [comment]
That is hard to read but I see the following:

```
(08.200428) Error (criu/util.c:669): exited, status=1
(08.200465) Error (criu/action-scripts.c:94): Script /tmp/lxd_checkpoint_674874618/action.sh exited with -1
(08.200484) Error (criu/action-scripts.c:138): One of more action scripts failed
```

We have seen problems with the CRIU action-script also during development. The action-script error can also be seen in https://discuss.linuxcontainers.org/t/live-migration-between-2-hosts-fails/1030

It does not happen on my system and it is a bit difficult to debug. @brauner do you remember what we had to change to solve the action-script error we were seeing? Could this be apparmor related? Can it be tested without apparmor?

**Comment by upuvvad1** [comment]
@adrianreber @brauner 
I tried debugging the code, and here are my thoughts

**src/github.com/lxc/lxd/lxd/container_lxc.go:2654, onStop.func1** is being called multiple times from the **api_internals.go:70.**

And the onStop.func1 is calling the **AADestroy function** at **src/github.com/lxc/lxd/lxd/apparmor.go: 480: main.AADestroy**, which tries to remove the /sys/kernel/security/policy/namespaces/lxd-CONTAINERNAME

Please let me know your thoughts on this :)

**Comment by upuvvad1** [comment]
Any update on this? :)
