### ISSUE TITLE
Problem with: sudo snap refresh: "lxd": cannot update snap namespace

### ISSUE THREAD

**Issue by wellington1993** [lxc/lxd#4194]
# Required information

 * Distribution: "Ubuntu Bionic Beaver (development branch)"
 * Distribution version: "18.04 LTS (Bionic Beaver)"
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.14.0-3-generic
   * LXC version: 2.1.1
   * LXD version: 2.21
   * Storage backend in use: dir

# Issue description

When try `sudo snap refresh` this problem is displayed:
```

error: cannot perform the following tasks:
- Setup snap "core" (3887) security profiles (cannot setup mount for snap "lxd": cannot update mount namespace of snap "lxd": cannot update preserved namespace of snap "lxd": cannot update snap namespace: cannot save current mount profile of snap "lxd": open /run/snapd/ns/snap.lxd.fstab.HJVyp1h91L34: no such file or directory)
- Setup snap "core" (3887) security profiles (cannot update mount namespace of snap "lxd": cannot update preserved namespace of snap "lxd": cannot update snap namespace: cannot save current mount profile of snap "lxd": open /run/snapd/ns/snap.lxd.fstab.HJVyp1h91L34: no such file or directory)
- Setup snap "lxd" (5447) security profiles (cannot setup mount for snap "lxd": cannot update mount namespace of snap "lxd": cannot update preserved namespace of snap "lxd": cannot update snap namespace: cannot save current mount profile of snap "lxd": open /run/snapd/ns/snap.lxd.fstab.73nQn8G48r43: no such file or directory)
- Setup snap "lxd" (5447) security profiles (cannot update mount namespace of snap "lxd": cannot update preserved namespace of snap "lxd": cannot update snap namespace: cannot save current mount profile of snap "lxd": open /run/snapd/ns/snap.lxd.fstab.73nQn8G48r43: no such file or directory)

```

# Steps to reproduce

 1. Step one
 sudo snap refresh
 2. Step two
-
 3. Step three
-

# Information to attach

 - [x ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [x ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor
[dmesg.txt](https://github.com/lxc/lxd/files/1659597/dmesg.txt)
[lvm-log.txt](https://github.com/lxc/lxd/files/1659598/lvm-log.txt)

` while reproducing the issue)

**Comment by stgraber** [comment]
I've seen this in the past, unfortunately it's not a lxd bug but a snapd issue. There's nothing that we can do about it ourselves...

A reboot has always made this go away for me, but you may also want to file a bug against snapd so that someone investigates the root cause of that, especially if you can reproduce this on a fresh system.

**Comment by stgraber** [comment]
(to be clear, this isn't a general issue, I just checked 8 systems here, all of which refreshed fine)

**Comment by rzr** [comment]
Is this "snapd issue" reported anywhere ?

For the record, I also observed this when I used "sudo snap set" on a locally installed snap, reboot helped thought.
