### ISSUE TITLE
Are all container mounts supposed to show up in mountinfo?

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#4195]
Apologize beforehand for my ignorance, as this may be more of a zfs issue than an lxd issue.

I have been doing some debugging with the folks over at Netdata trying to track down why Netdata doesn't report disk space utilization for some containers. Please see https://github.com/firehol/netdata/issues/3233

According to them, they use `mountinfo` to detect all the mountpoints on the system - but I have concluded that this does not always turn up all containers. Typically it will be containers which are not seeing much activity (just my initial observation - may be of no consequence)

Anybody here have any insight here, and whether this is related to LXD or, possibly more likely, ZFS?

**Comment by brauner** [comment]
On Wed, Jan 24, 2018 at 9:41 PM, Kramerican <notifications@github.com>
wrote:

> Apologize beforehand for my ignorance, as this may be more of a zfs issue
> than an lxd issue.
>
> I have been doing some debugging with the folks over at Netdata trying to
> track down why Netdata doesn't report disk space utilization for some
> containers. Please see firehol/netdata#3233
> <https://github.com/firehol/netdata/issues/3233>
>
> According to them, they use mountinfo to detect all the mountpoints on
> the system - but I have concluded that this does not always turn up all
> containers. Typically it will be containers which are not seeing much
> activity (just my initial observation - may be of no consequence)
>
> Anybody here have any insight here, and whether this is related to LXD or,
> possibly more likely, ZFS?
>

I responded over there.

**Comment by stgraber** [comment]
So this can get pretty complex pretty quickly :)

In the most standard case, you'll see only running containers be mounted, LXD doing the mount/unmount automatically. That's except for the LXD LTS branch (2.0.x) where this code doesn't exist and where all containers are always mounted.

Now as @brauner mentioned, ZFS will do recursive unmounts in some cases, specifically for our case, if the dataset that was used as the container's dataset parent is renamed. In such cases, the mount will disappear from the host, but will not affect the container's copy of that mount entry. Things then go back to normal when the container is restarted.

Then there's the other case, where LXD is installed through its snap package. In this case, the entirety of the snap is running inside an alternative mount namespace, so none of the mounts are going to be visible on the host system, regardless of whether LXD has them mounted or not.

I hope that this and @brauner's answer over in the other issue answers your question.
