### ISSUE TITLE
Feature request: Add glob support for lxc file pull/push

### ISSUE THREAD

**Issue by alejandro-perez** [lxc/lxd#4197]
The use of lxc file pull/push is great, as it allows accesing files without knowing where the storage for the container is. But not being able to use glob filenames (such as *.deb) is a great inconvenient, as you have either to know the name of the files before hand or do a recursive copy of the whole directory, that might pull/push lots of files.

Would it be possible to implement? I guess "go" has some nice libraries to deal with glob, as Python does.

**Comment by stgraber** [comment]
Wildcard/pattern matching support is something provided by your shell, as a result, it's already perfectly supported for push:

```
stgraber@castiana:~/Desktop$ touch a1 a2 a3 a4
stgraber@castiana:~/Desktop$ lxc file push a* c1/root/ --verbose
INFO[01-25|18:01:23] Pushing a1 to /root/a1 (file) 
INFO[01-25|18:01:23] Pushing a2 to /root/a2 (file) 
INFO[01-25|18:01:23] Pushing a3 to /root/a3 (file) 
INFO[01-25|18:01:23] Pushing a4 to /root/a4 (file) 
stgraber@castiana:~/Desktop$ lxc exec c1 -- ls -lh /root/
total 2.0K
-rw-r--r-- 1 201105 200512 0 Jan 25 23:01 a1
-rw-r--r-- 1 201105 200512 0 Jan 25 23:01 a2
-rw-r--r-- 1 201105 200512 0 Jan 25 23:01 a3
-rw-r--r-- 1 201105 200512 0 Jan 25 23:01 a4
```

For pull, your shell can't know what exists on the target, so a literal "*" is passed.
Unfortunately the LXD daemon doesn't know what's in the directory either as pulling files is done one by one using rather complex kernel interfaces which use an exact path. There'd also not be a way of distinguishing from an actual file called "*" and the glob character (the shell requires escaping for the former, but our API doesn't).

There's also the funny issue that if you were to do:
```
lxc file pull c1/* .
```

And you happened to have a directory called with a number of files in it, your local shell would expand the pattern, causing you to pull potentially completely random files, or more likely getting a 404 from LXD.

So the tl&dr is that for push, it's fine and it does work today. For pull, we can't really do it and it'd lead to potential conflicts with your shell anyway so you're better off transferring full directories.

**Comment by alejandro-perez** [comment]
Ok, fair enough. I guess I would do something like:
```
lxc exec $CONTAINER -- mkdir /tmp/tmpfolder
lxc exec $CONTAINER -- cp /path/to/files* /tmp/folder
lxc file pull -r $CONTAINER/tmp/folder .
```

**Comment by stgraber** [comment]
yeah, that works fine. I've also showed once how to wrap rsync around `lxc exec` which may be an alternative to this.

https://discuss.linuxcontainers.org/t/rsync-files-into-container-from-host/822
