### ISSUE TITLE
Unable to complete "make" to build lxd

### ISSUE THREAD

**Issue by DarthSpock** [lxc/lxd#4204]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails: LXD socket not found; is LXD installed and running?
   * Kernel version:  4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 2.0.11 
   * LXD version:  2.0.11
   * Storage backend in use: N/A

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one: Follow this guidance "Installing LXD from source"
 2. When I get to `make`,  I get the following error: 
go get -t -v -d ./...
package context: unrecognized import path "context" (import path does not begin with hostname)
Makefile:16: recipe for target 'default' failed
make: *** [default] Error 1
 3. Step three: Wonder why this world has to be so cruel.

# Information to attach

I have an `strace` here: 
[Failed LXD Make Strace.txt](https://github.com/lxc/lxd/files/1675717/Failed.LXD.Make.Strace.txt)

If there's any other information you need, let me know.

**Comment by stgraber** [comment]
You need Go 1.6 or higher to build LXD, looks like you're running with 1.6.

**Comment by stgraber** [comment]
There's a backport of 1.9 in xenial-backports
