### ISSUE TITLE
LXD: Non-subcommand flags should be able to appear before subcommand

### ISSUE THREAD

**Issue by simos** [lxc/lxd#4207]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.3
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-112-generic
   * LXC version: 2.21 (master)
   * LXD version: 2.21 (master)
   * Storage backend in use: dir

# Issue description

For the `lxd` executable, non-subcommand flags should be able to appear before subcommands.

For example, in 

`$ sudo lxd --group lxd init`

1. the subcommand is `init`
2. the non-subcommand flag is `--group lxd`

In this example, the `init` subcommand is ignored due to 
https://github.com/lxc/lxd/blob/master/shared/cmd/parser.go#L126

# Steps to reproduce

 1. Run `$ sudo lxd --group lxd init`

What happens: `lxd` uses the default subcommand` daemon instead of the supplied `init` because https://github.com/lxc/lxd/blob/master/lxd/main.go#L32
What should happen: `lxd should run the `init` subcommand instead. 
What not just write `$ sudo lxd init --group lxd`: Because `--group lxd` is set in the code after cmdInit() is run, therefore cmdInit() fails.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

The issue happens too early in the set up of `lxd` and there are no relevant logs.

**Comment by stgraber** [comment]
You realize that --group lxd is meaningless when used with init right?

**Comment by stgraber** [comment]
--group is only relevant when LXD is started in daemon mode (no subcommand)

**Comment by simos** [comment]
In that respect, the discussion moves back to https://discuss.linuxcontainers.org/t/writing-a-tutorial-on-how-to-develop-lxd/1153

**Comment by stgraber** [comment]
Going to close this in favor of #490 as the switch to urfave/cli will come with better handling for ordering (or enforcement of ordering at least).
