### ISSUE TITLE
snap migration of lxd fails if btrfs volume is a mounted one

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#4210]
I tried to migrate lxd 2.21 (ubuntu 17.10, btrfs)  to snap package on 2 systems:
 - one with /var/lix/lxd btrfs subvolume in-place
 - one with btrfs subvolume mounted on  /var/lix/lxd (with mount UUID etc ..)

- the migration on the system with btrfs in-place worked fine
- the migration on the system with btrfs mounted on /var/lib/lxd failed (didn't stopped).

I think the second case is not taken in account in the migration process.

Regards.

**Comment by stgraber** [comment]
How did it fail in the second case?

It's not something we can actually support in the automatic migration but we can make it clearer if the error isn't clear. You'd need to stop LXD, unmount the path, run the migration, then update your fstab to mount it at the new location and mount things again, then restart the snap.

**Comment by gaetanquentin** [comment]
i don't remember  the error message, and i can't replay the migration script.

i think the lxd database is corrupted since i have lost all containers.

**Comment by stgraber** [comment]
Hmm, LXD wouldn't start if your database had been corrupted, so it's more likely it's looking at the wrong database. So we should be able to figure that out easily enough.

Can you paste:

 - cat /proc/self/mountinfo
 - ls -lh /var/snap/lxd/common/lxd
 - ls -lh /var/snap/lxd/current/lxd/

**Comment by gaetanquentin** [comment]
gaetanquentin-perso@gquentin-ssd-t3:~$ cat /proc/self/mountinfo
22 28 0:21 / /sys rw,nosuid,nodev,noexec,relatime shared:7 - sysfs sysfs rw
23 28 0:4 / /proc rw,nosuid,nodev,noexec,relatime shared:13 - proc proc rw
24 28 0:6 / /dev rw,nosuid,relatime shared:2 - devtmpfs udev rw,size=8143368k,nr_inodes=2035842,mode=755
25 24 0:22 / /dev/pts rw,nosuid,noexec,relatime shared:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
26 28 0:23 / /run rw,nosuid,noexec,relatime shared:5 - tmpfs tmpfs rw,size=1634952k,mode=755
28 0 0:25 /@ / rw,noatime shared:1 - btrfs /dev/sdc3 rw,compress=lzo,ssd,space_cache,subvolid=257,subvol=/@
29 22 0:7 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:8 - securityfs securityfs rw
30 24 0:28 / /dev/shm rw,nosuid,nodev shared:4 - tmpfs tmpfs rw
31 26 0:29 / /run/lock rw,nosuid,nodev,noexec,relatime shared:6 - tmpfs tmpfs rw,size=5120k
32 22 0:30 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:9 - tmpfs tmpfs ro,mode=755
33 32 0:31 / /sys/fs/cgroup/unified rw,nosuid,nodev,noexec,relatime shared:10 - cgroup2 cgroup rw
34 32 0:32 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:11 - cgroup cgroup rw,xattr,name=systemd
35 22 0:33 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:12 - pstore pstore rw
36 32 0:34 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,cpu,cpuacct
37 32 0:35 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,perf_event
38 32 0:36 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,hugetlb
39 32 0:37 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,pids
40 32 0:38 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,cpuset,clone_children
41 32 0:39 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,memory
42 32 0:40 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,devices
43 32 0:41 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,net_cls,net_prio
44 32 0:42 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,freezer
45 32 0:43 / /sys/fs/cgroup/rdma rw,nosuid,nodev,noexec,relatime shared:23 - cgroup cgroup rw,rdma
46 32 0:44 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:24 - cgroup cgroup rw,blkio
47 23 0:45 / /proc/sys/fs/binfmt_misc rw,relatime shared:25 - autofs systemd-1 rw,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16562
50 24 0:19 / /dev/mqueue rw,relatime shared:26 - mqueue mqueue rw
49 22 0:8 / /sys/kernel/debug rw,relatime shared:27 - debugfs debugfs rw
48 24 0:46 / /dev/hugepages rw,relatime shared:28 - hugetlbfs hugetlbfs rw,pagesize=2M
80 22 0:20 / /sys/kernel/config rw,relatime shared:29 - configfs configfs rw
82 22 0:47 / /sys/fs/fuse/connections rw,relatime shared:30 - fusectl fusectl rw
84 28 7:0 / /snap/core/3748 ro,nodev,relatime shared:31 - squashfs /dev/loop0 ro
86 28 7:1 / /snap/blender/12 ro,nodev,relatime shared:32 - squashfs /dev/loop1 ro
88 28 7:2 / /snap/core/3887 ro,nodev,relatime shared:33 - squashfs /dev/loop2 ro
90 28 7:3 / /snap/core/3604 ro,nodev,relatime shared:34 - squashfs /dev/loop3 ro
93 28 8:33 / /efi rw,relatime shared:35 - vfat /dev/sdc1 rw,gid=46,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro
92 28 0:25 / /mnt/ROOT rw,noatime shared:36 - btrfs /dev/sdc3 rw,compress=lzo,ssd,space_cache,subvolid=5,subvol=/
100 28 0:25 /@lxd /var/lib/lxd rw,noatime shared:37 - btrfs /dev/sdc3 rw,compress=lzo,ssd,space_cache,subvolid=498,subvol=/@lxd
94 28 0:25 /@cache /cache rw,noatime shared:38 - btrfs /dev/sdc3 rw,compress=lzo,ssd,space_cache,subvolid=451,subvol=/@cache
96 28 0:25 /@home2 /home rw,noatime shared:39 - btrfs /dev/sdc3 rw,compress=lzo,ssd,space_cache,subvolid=500,subvol=/@home2
98 28 0:25 /@appli /appli rw,noatime shared:40 - btrfs /dev/sdc3 rw,compress=lzo,ssd,space_cache,subvolid=463,subvol=/@appli
102 28 0:25 /@data /data rw,noatime shared:41 - btrfs /dev/sdc3 rw,compress=lzo,ssd,space_cache,subvolid=464,subvol=/@data
104 28 0:25 /@opt /opt rw,noatime shared:42 - btrfs /dev/sdc3 rw,compress=lzo,ssd,space_cache,subvolid=440,subvol=/@opt
105 47 0:56 / /proc/sys/fs/binfmt_misc rw,relatime shared:43 - binfmt_misc binfmt_misc rw
388 28 0:59 / /var/lib/lxcfs rw,nosuid,nodev,relatime shared:257 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
127 28 0:49 / /mnt/BACKUP rw,noatime shared:368 - btrfs /dev/sde1 rw,compress=lzo,space_cache,subvolid=5,subvol=/
472 100 0:63 / /var/lib/lxd/shmounts rw,relatime shared:383 - tmpfs tmpfs rw,size=100k,mode=711
480 100 0:64 / /var/lib/lxd/devlxd rw,relatime shared:390 - tmpfs tmpfs rw,size=100k,mode=755
458 26 0:62 / /run/user/130 rw,nosuid,nodev,relatime shared:262 - tmpfs tmpfs rw,size=1634948k,mode=700,uid=130,gid=137
667 26 0:67 / /run/user/1003 rw,nosuid,nodev,relatime shared:573 - tmpfs tmpfs rw,size=1634948k,mode=700,uid=1003,gid=1003
679 96 0:68 / /home/gaetanquentin-perso rw,nosuid,nodev,relatime shared:584 - ecryptfs /home/gaetanquentin-perso/.Private rw,ecryptfs_fnek_sig=1c3d846bedc670f4,ecryptfs_sig=8f85385bf3c6e37b,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs
685 679 0:69 / /home/gaetanquentin-perso/Cache rw,nosuid,nodev,relatime shared:589 - ecryptfs /cache/gaetanquentin-perso rw,ecryptfs_fnek_sig=1c3d846bedc670f4,ecryptfs_sig=8f85385bf3c6e37b,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs
691 667 0:70 / /run/user/1003/gvfs rw,nosuid,nodev,relatime shared:594 - fuse.gvfsd-fuse gvfsd-fuse rw,user_id=1003,group_id=1003

gaetanquentin-perso@gquentin-ssd-t3:~$ ls -lh /var/snap/lxd/common/lxd
ls: impossible d'accéder à '/var/snap/lxd/common/lxd': Aucun fichier ou dossier de ce type
 -> no such file or directory

gaetanquentin-perso@gquentin-ssd-t3:~$ ls -lh /var/snap/lxd/current/lxd/
ls: impossible d'accéder à '/var/snap/lxd/current/lxd/': Aucun fichier ou dossier de ce type

-> no such file or directory

**Comment by stgraber** [comment]
Hmm, did you remove the lxd snap? Looks like it's not installed anymore on that system.

**Comment by gaetanquentin** [comment]
yes i think i removed it. i did  that a few weeks ago so i d'ont remember exactly what happened. I remember only that the migration script never ended. And after that, containers disapperared.


since i have a new system to migrate to snap, and which has a mounted btrfs subvolume too in /var/lib/lxd, how should i do it?

you said a few days ago:

"You'd need to stop LXD, unmount the path, run the migration, then update your fstab to mount it at the new location and mount things again, then restart the snap."

but how can the tool script  migrate things if i unmount the /var/lib/lxd subvolume?  
Content won't be here anymore.

**Comment by stgraber** [comment]
Ok, so one issue that you might have run into is the weird way we store our database, it's something I intend to fix in the next couple of days, so I'd suggest you wait for that fix, then I'll let you know the migration steps at that point.

**Comment by stgraber** [comment]
The database issue has been fixed so everything is now self-contained inside /var/snap/lxd/common/lxd, making it easier to transition such a system. I'll look into how lxd.migrate interacts with this and what can be done to improve.

**Comment by stgraber** [comment]
I've made lxd.migrate aware of this and the new workflow looks like:

```
root@vm08:~# lxd.migrate 
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks

=== Source server
LXD version: 2.0.11
LXD PID: 2695
Resources:
  Containers: 1
  Images: 1

=== Destination server
LXD version: 2.21
LXD PID: 3243
Resources:
  Containers: 0
  Images: 0
  Networks: 0
  Storage pools: 0

The migration process will shut down all your containers then move your data to the destination LXD.
Once the data is moved, the destination LXD will start and apply any needed updates.
And finally your containers will be brought back to their previous state, completing the migration.

WARNING: /var/lib/lxd is a mountpoint. You will need to update your /etc/fstab after the migration.

Are you ready to proceed (yes/no) [default=no]? yes
=> Shutting down the source LXD
=> Stopping the source LXD units
=> Stopping the destination LXD unit
=> Unmounting source LXD paths
=> Unmounting destination LXD paths
=> Wiping destination LXD clean
=> Moving the /var/lib/lxd mountpoint
=> Moving the database
=> Backing up the database
=> Opening the database
=> Updating the storage backends
=> Starting the destination LXD
=> Waiting for LXD to come online
=> Converting the network configuration

=== Destination server
LXD version: 2.21
LXD PID: 3493
Resources:
  Containers: 1
  Images: 1
  Networks: 0
  Storage pools: 1

WARNING: Make sure to update /etc/fstab to mount the right path on top of /var/snap/lxd/common/lxd

The migration is now complete and your containers should be back online.
Do you want to uninstall the old LXD (yes/no) [default=no]? yes

All done. You may need to close your current shell and open a new one to have the "lxc" command work.
```

Note that it may be a couple of days before this new code hits stable (it's currently in edge). I also need to do the same trick for those using a zfs dataset (slightly different variant of the same issue).
