### ISSUE TITLE
Socket owned by root rather than lxd

### ISSUE THREAD

**Issue by kalikiana** [lxc/lxd#4211]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version:4.4.0-109-generic
   * LXC version:2.0.8
   * LXD version:2.2.1
   * Storage backend in use:dir

# Issue description

Since this week I'm seeing an issue where after installation LXD creates a socket owned by root, rather than "lxd".
Even if I apply a work-around, and install a different lxd version, the socket is reset to the wrong owner. Happens with 2.21-0ubuntu2~16.04.1 and 2.0.11-0ubuntu1~16.04.4.

# Steps to reproduce

> sudo apt install lxd
> lxc list
Permission denied, are you in the lxd group?
> ls -l /var/lib/lxd/unix.socket
srw-rw---- 1 root root 0 Feb  1 16:35 /var/lib/lxd/unix.socket

Work-around
> sudo chown lxd:lxd /var/lib/lxd/unix.socket
> sudo chmod lxd:lxd /var/lib/lxd/unix.socket

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Hmm, LXD itself doesn't create that socket, it's systemd which does.

**Comment by stgraber** [comment]
```
root@vm07:~# ls -lh /var/lib/lxd/unix.socket 
srw-rw---- 1 root lxd 0 Feb  1 16:11 /var/lib/lxd/unix.socket
```

On a freshly installed Ubuntu 16.04 with 2.0.11.

**Comment by stgraber** [comment]
```
root@vm07:~# ls -lh /var/lib/lxd/unix.socket 
srw-rw---- 1 root lxd 0 Feb  1 16:11 /var/lib/lxd/unix.socket
```

That's after installing LXD 2.21 from backports.

**Comment by stgraber** [comment]
Removed the packages and user/group and rebooting to see if a clean install causes the problem.

```
root@vm07:~# apt install lxd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  ebtables xdelta3
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  lxd-client
Suggested packages:
  criu lxd-tools
The following NEW packages will be installed:
  lxd lxd-client
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 5,389 kB of archives.
After this operation, 26.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 lxd-client amd64 2.0.11-0ubuntu1~16.04.4 [1,884 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 lxd amd64 2.0.11-0ubuntu1~16.04.4 [3,505 kB]
Fetched 5,389 kB in 0s (9,069 kB/s)
Preconfiguring packages ...
Selecting previously unselected package lxd-client.
(Reading database ... 60171 files and directories currently installed.)
Preparing to unpack .../lxd-client_2.0.11-0ubuntu1~16.04.4_amd64.deb ...
Unpacking lxd-client (2.0.11-0ubuntu1~16.04.4) ...
Selecting previously unselected package lxd.
Preparing to unpack .../lxd_2.0.11-0ubuntu1~16.04.4_amd64.deb ...
Adding system user `lxd' (UID 106) ...
Adding new user `lxd' (UID 106) with group `nogroup' ...
Creating home directory `/var/lib/lxd/' ...
Adding group `lxd' (GID 110) ...
Done.
Unpacking lxd (2.0.11-0ubuntu1~16.04.4) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for systemd (229-4ubuntu21) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up lxd-client (2.0.11-0ubuntu1~16.04.4) ...
Setting up lxd (2.0.11-0ubuntu1~16.04.4) ...

The default LXD bridge, lxdbr0, comes unconfigured by default.
Only limited HTTP connectivity through a PROXY will be available.
To go through the initial LXD configuration, run: lxd init

Processing triggers for systemd (229-4ubuntu21) ...
Processing triggers for ureadahead (0.100.0-19) ...
root@vm07:~# ls -lh /var/lib/lxd
total 0
srw-rw---- 1 root lxd 0 Feb  1 16:18 unix.socket
```

**Comment by stgraber** [comment]
Closing this issue as LXD doesn't actually have any code to set the user/group on the socket, that's handled by systemd on Ubuntu.
