### ISSUE TITLE
after snap migration install of lxd, lxc and lxd.lxc act different

### ISSUE THREAD

**Issue by greenpdx** [lxc/lxd#4221]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04 
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-112-generic
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: disk ext4

# Issue description
I update lxd using snap.  I followed the https://discuss.linuxcontainers.org/t/migrate-from-ppa-to-snap/816.  
When I type lxc I see nothing, but when I type lxd.lxc I see the existing containers.  I  found both lxc and lxd in /snap/lxd/5556/bin 
What is going on?  How do I convert lxd.lxc containers to lxc?

I am sorry that I do not have logs, I found this problem after I did the snap install 

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by greenpdx** [comment]
What was happening was in the PATH /usr/bin is before /snap/bin so the old lxc was being used.
I moved  /usr/bin/lxc to old.lxc ,  opened a new shell and now it works, it is use the /snap/bin/lxc

**Comment by stgraber** [comment]
Right, that's why the lxd.migrate command ends with the removal of the .deb version of lxd and lxd-client so that you don't end up with both installed on the system.
