### ISSUE TITLE
LXD hangs when trying to start containers

### ISSUE THREAD

**Issue by harolds** [lxc/lxd#4223]
# Required information

 * Distribution:
Ubuntu
 * Distribution version:
16.04.3 LTS
 * The output of "lxc info":
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  storage.zfs_pool_name: tank
api_extensions:
- id_map
- id_map_base
- resource_limits
api_status: stable
api_version: "1.0"
auth: trusted
auth_methods: []
public: false
environment:
  addresses:
  - 213.239.210.169:8443
  - '[2a01:4f8:a0:9417::2]:8443'
  - 10.0.4.1:8443
  - '[fde3:f4c2:8bd:ceb9::1]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFejCCA2KgAwIBAgIRANN5k8x0YZtMOvJMiSZmGJMwDQYJKoZIhvcNAQELBQAw...
   -----END CERTIFICATE-----
  certificate_fingerprint: a18304156ee2479d745f83829b6deadff2e8014ee9b6ff7426c2ee38a0d6cf20
  driver: lxc
  driver_version: 2.1.0-devel
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-32-generic
  server: lxd
  server_pid: 10975
  server_version: 2.0.11
  storage: zfs
  storage_version: "5"

# Issue description

I am unable to start containers after copying them from a 'base' container. Even after restarting the server LXD no longer responses to command given via LXC. I have this issue on our development server and on our (new) production server. As long as its this 'unstable' I can not use LXD for our new production setup.

Every time this happens I see some container having multiple processes:

root     15695     1  0 13:20 ?        00:00:00 /usr/bin/lxd forkstart kasdev5 /var/lib/lxd/containers /var/log/lxd/kasdev5/lxc.conf
root     15700 15695  0 13:20 ?        00:00:00 [lxd] <defunct>
root     15701     1  0 13:20 ?        00:00:00 [lxc monitor] /var/lib/lxd/containers kasdev5
root     15720 15701  0 13:20 ?        00:00:00 [lxc monitor] /var/lib/lxd/containers kasdev5

As soon as I kill them all I can list the containers again:

+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
|      NAME       |  STATE  |       IPV4       |                     IPV6                     |    TYPE    | SNAPSHOTS |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| kasact          | RUNNING | 10.0.11.1 (eth0) | fde3:f4c2:8bd:ceb9:216:3eff:fed5:f7cf (eth0) | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| kasact2         | RUNNING | 10.0.11.2 (eth0) | fde3:f4c2:8bd:ceb9:216:3eff:fe0d:b624 (eth0) | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| kasdev          | RUNNING | 10.0.10.1 (eth0) | fde3:f4c2:8bd:ceb9:216:3eff:fe27:7be2 (eth0) | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| kasdev2         | RUNNING | 10.0.10.2 (eth0) | fde3:f4c2:8bd:ceb9:216:3eff:fe33:609f (eth0) | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| kasdev3         | RUNNING | 10.0.10.3 (eth0) | fde3:f4c2:8bd:ceb9:216:3eff:fe38:8282 (eth0) | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| kasdev4         | RUNNING | 10.0.10.4 (eth0) | fde3:f4c2:8bd:ceb9:216:3eff:fe8b:ffb5 (eth0) | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| kasdev5         | STOPPED |                  |                                              | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| kasdev6         | RUNNING | 10.0.10.6 (eth0) | fde3:f4c2:8bd:ceb9:216:3eff:fe3a:854 (eth0)  | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| kasdev7         | RUNNING | 10.0.10.7 (eth0) | fde3:f4c2:8bd:ceb9:216:3eff:fe2e:3cc6 (eth0) | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| kasdev8         | RUNNING | 10.0.10.8 (eth0) | fde3:f4c2:8bd:ceb9:216:3eff:fe39:3365 (eth0) | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| kasedsntest     | STOPPED |                  |                                              | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+
| ubuntu-1204-lts | STOPPED |                  |                                              | PERSISTENT | 0         |
+-----------------+---------+------------------+----------------------------------------------+------------+-----------+

But nothing else seems to work:

root@dev ~ # lxc stop kasdev8
error: Put http://unix.socket/1.0/containers/kasdev8/state: EOF

This is what I see in the lxc.log of one of the containers:

root@dev /var/log/lxd/kasdev5 # cat lxc.log
            lxc 20180205142034.220 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1356 - Path "/sys/fs/cgroup/systemd//lxc/kasdev5" already existed.
            lxc 20180205142034.220 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1430 - Failed to create "/sys/fs/cgroup/systemd//lxc/kasdev5"
            lxc 20180205142034.220 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1356 - Path "/sys/fs/cgroup/systemd//lxc/kasdev5-1" already existed.
            lxc 20180205142034.220 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1430 - Failed to create "/sys/fs/cgroup/systemd//lxc/kasdev5-1"
            lxc 20180205142034.254 ERROR    lxc_network - network.c:lxc_setup_network_in_child_namespaces:3021 - WARNING: using "lxc.network.*" keys to define networks is DEPRECATED, please switch to using "lxc.net.[i].* keys"
            lxc 20180205142256.410 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:130 - Connection reset by peer - Failed to receive response for command "get_cgroup"

# Steps to reproduce

Install stable LXD. lxc launch Ubuntu 12.04 LTS. Create 10 copies. Try to start them.

**Comment by stgraber** [comment]
You appear to be running an experimental version of liblxc on your production server, that's at least causing some of the warnings in that log above.

**Comment by stgraber** [comment]
```
driver: lxc
driver_version: 2.1.0-devel
```

Ubuntu 16.04 should report 2.0.8 instead.

**Comment by harolds** [comment]
Thanks for the help! I had installed the feature version first but that was not stable too. This must be a leftover from that install.

There was still an apt config that needed to be removed:
ubuntu-lxc-ubuntu-daily-xenial.list:deb http://ppa.launchpad.net/ubuntu-lxc/daily/ubuntu xenial main

After uninstalling lxd and lxc completely (dpkg --purge lxd, etc) I could reinstall them and now the driver_version is: 2.0.8

Everything seems to be working now.
