### ISSUE TITLE
Add number codes as aliases for debian images

### ISSUE THREAD

**Issue by alejandro-perez** [lxc/lxd#4226]
Number codes are often used instead of Debian release names. Ej, Debian 8 == Debian Jessie. Since images can have aliases, could you add these number codes to the Debian images in "images:"?

So we can make ```lxc launch images:debian/8``` instead of ```lxc launch images:debian/jessie```

**Comment by stgraber** [comment]
That should be possible, at least for the simplestreams image server, will need to tweak our scripts a bit though.

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc launch images:debian/8 c3
Creating c3
Starting c3                                 
stgraber@castiana:~$ 
```

**Comment by alejandro-perez** [comment]
Awesome! Thanks!
