### ISSUE TITLE
pull recursive fails with error: not found

### ISSUE THREAD

**Issue by mikesi** [lxc/lxd#4227]
* Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-42-generic
   * LXD version: 2.21 from snap
   * Storage backend in use: lvm

lxc file pull -r --verbose CONTAINER/etc  .

Fails with:
error: not found

running in verbose mode i can see the last file successfully transferred before the error is thrown.

snap logs lxd does not show anything relevant.

snap info:
services:
 lxd.daemon:    simple, enabled, active
tracking:        stable
installed:       2.21 (5556) 47MB -
refreshed:       2018-02-02 14:48:02 +0100 CET

# Steps to reproduce

lxc file pull -r somecontainer/etc .

# Information to attach
config of container:
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine 3.7 amd64 (20180122_17:50)
  image.os: Alpine
  image.release: "3.7"
  image.serial: "20180122_17:50"
  limits.cpu: "8"
  limits.memory: 4GB
  volatile.apply_quota: 20GB
  volatile.base_image: a875d39328b61dfbd968651e44e8290ac2d3a1058c44583755b0745e9667a554
  volatile.eth0.hwaddr: 00:16:3e:66:cd:f3
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""

**Comment by stgraber** [comment]
Some things that may be useful:

 - What user were you running "lxc" as?
 - What directory were you in at the time?
 - What was that verbose output showing you?

That should help me reproduce the problem here.

**Comment by stgraber** [comment]
I reproduce the issue here.

**Comment by mikesi** [comment]
sorry i didn't get the notification yesterday.
I see you are able to reproduce it without additional input.

**Comment by stgraber** [comment]
The problem is that recursive pull doesn't support retrieving symlinks right now, I've implemented that now.

**Comment by mikesi** [comment]
very nice :) 
i thought it may have something to do with that or something similar, but the verbose output didn't say what was the item it couldn't copy.
