### ISSUE TITLE
Live migration error LXD 

### ISSUE THREAD

**Issue by ibrahimagha** [lxc/lxd#4228]
hi guys,
I was trying to do live migration between 2 lxd hosts but I was not able to do it when I was launching Ubuntu 16 containers I switched to Ubuntu 14 containers and when it is an empty container I can do live migration after a try or two but when I am installing squid on it because I want it to work as a proxy for my back-end cloud the live migration gives me this error :+1: 
sudo lxc move squid me:
error: Failed container creation:
 - https://192.168.2.233:8443: migration dump failed
(00.889609) Warn  (criu/arch/x86/crtools.c:133): Will restore 8024 with interrupted system call
(00.900984) Warn  (criu/arch/x86/crtools.c:133): Will restore 8025 with interrupted system call
(01.012850) Error (criu/sk-inet.c:106): Unsupported proto 1 for socket 11de2
(01.012860) Error (criu/cr-dump.c:1313): Dump files (pid: 13945) failed with -1
(01.072172) Error (criu/cr-dump.c:1628): Dumping FAILED.
 - https://192.168.56.1:8443: x509: certificate is valid for livetest-VirtualBox, not live-VirtualBox
any ideas ?
live migration works fine when it is a fresh container and nothing is installed on it

**Comment by stgraber** [comment]
```
(01.012850) Error (criu/sk-inet.c:106): Unsupported proto 1 for socket 11de2
```

Is the error, apparently process 13945 had such a socket open and CRIU is simply unable to live migrate it.

You could try manually building and running the latest version of CRIU to see if that helps, if not, then maybe consider filing a bug against CRIU upstream (https://github.com/checkpoint-restore/criu).


I'm closing this issue as LXD's live-migration support is limited to transferring the filesystem and calling out to CRIU, any bug or missing features after that is in CRIU and the Linux kernel.

**Comment by stgraber** [comment]
If you do file an issue against CRIU, feel free to post a link here so that others can find it.

**Comment by ibrahimagha** [comment]
I filed an issue against CRIU, you can follow it from this link https://github.com/checkpoint-restore/criu/issues/442
