### ISSUE TITLE
Make shorter "lxc exec mycontainer -- sudo --user ubuntu --login"

### ISSUE THREAD

**Issue by simos** [lxc/lxd#4233]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-35-generic
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: zfs

# Issue description

When a user wants to get a shell into a container, they need to get _a login shell_ so that /etc/profile.d/apps-bin-path.sh runs, which adds **/snap/bin** to the $PATH.

This issue/report is about _potential usability issues_ in getting a login shell in LXD (long command line, possibly error-prone).

```
$ lxc shell mycontainer
root@mycontainer:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
root@mycontainer:~# sudo --user ubuntu --login
ubuntu@mycontainer:~$ echo $PATH
/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
ubuntu@mycontainer:~$ 

```
When they want to log in as a user, they would
```
$ lxc exec mycontainer -- sudo --user ubuntu --login
ubuntu@mycontainer:~$ echo $PATH
/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
ubuntu@mycontainer:~$ 

```

There should be a similar alias (to `lxc shell mycontainer`) for non-root shells, which should be also built-in. 
Understandably, the non-root shell would be specific to Ubuntu container images as other images may not come with a default non-root user account.

# Information to attach

 - [x] [Snap usability issue if shell is not login shell](https://forum.snapcraft.io/t/sudo-snap-install-or-just-snap-install/3909/10)
 - [x] [multipass shell should be a login shell #115](https://github.com/CanonicalLtd/multipass/issues/115)

**Comment by stgraber** [comment]
This isn't something that we can really do as we don't know what's available for what containers and have a policy not to execute stuff in containers to determine it (which is the only way to query available users through libnss).

It's however something you can do for yourself with an alias if you want.

```
stgraber@castiana:~$ lxc ubuntu snapcraft
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@snapcraft:~$ logout
stgraber@castiana:~$ tail .config/lxc/config.yml -n2
aliases:
  ubuntu: exec @ARGS@ -- sudo --login --user ubuntu
```

**Comment by stgraber** [comment]
And you can do that for whatever user you want, under whatever command name you want as well as use the right mechanism to switch user for the relevant distribution you're using.

**Comment by simos** [comment]
Personally I am OK even with typing the full line. 

My difficulty is in trying to explain this in a LXD guide that others will read.
In technical documentation, it's not nice to demonstrate commands that depend on an alias that you have to set in advance.
It would be ideal to have some sort of build-in alias like `lxc shell` is.
For now, I'll opt for the verbose command as before.

**Comment by stgraber** [comment]
The branch I sent will make it easy to list and modify those aliases so should make it easier to tell people how to define something that works for them without having to manually edit the config.
