### ISSUE TITLE
Unable to run docker-ce inside Ubuntu 14.04 container on an Ubuntu 16.04 host

### ISSUE THREAD

**Issue by dhallam** [lxc/lxd#4238]
I'm trying to run an Ubuntu 14.04 LXD container from an Ubuntu 16.04 host but am getting `docker: Error response from daemon: cgroups: cannot found cgroup mount destination: unknown.` when I try to start a docker-ce container within the 14.04 container.

I've run the same process using `lxc launch ubuntu:x docker -p docker` for a 16.04 LXD container and that works fine.  But I need to be able to run a 14.04 LXD container.

Am I missing something? Or is there something that fundamentally won't work?  Many thanks.

# Various information

Output of `cat /etc/lsb-release` on the host

	DISTRIB_ID=Ubuntu
	DISTRIB_RELEASE=16.04
	DISTRIB_CODENAME=xenial
	DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

Output of `lxc info`

	config:
	  core.https_address: '[::]:8443'
	api_extensions:
	- id_map
	- id_map_base
	- resource_limits
	api_status: stable
	api_version: "1.0"
	auth: trusted
	auth_methods: []
	public: false
	environment:
	  addresses:
	  - 172.31.1.115:8443
	  - 10.0.3.1:8443
	  - 172.17.0.1:8443
	  - 192.168.33.1:8443
	  architectures:
	  - x86_64
	  - i686
	  certificate: |
	    -----BEGIN CERTIFICATE-----
	    ...truncated...
	    -----END CERTIFICATE-----
	  certificate_fingerprint: 44a2832734254814f0d75445eb84314d8fa92094da197192b55533dbcf0e3f3e
	  driver: lxc
	  driver_version: 2.0.8
	  kernel: Linux
	  kernel_architecture: x86_64
	  kernel_version: 4.4.0-1049-aws
	  server: lxd
	  server_pid: 49020
	  server_version: 2.0.11
	  storage: dir
	  storage_version: ""

Output of `lxc profile show docker`

	config:
	  linux.kernel_modules: overlay, nf_nat
	  raw.apparmor: |-
	    mount fstype=nfs,
	    mount fstype=nfs4,
	    mount fstype=nfsd,
	    mount fstype=rpc_pipefs,
	  security.nesting: "true"
	  security.privileged: "true"
	description: Profile supporting docker in containers
	devices:
	  aadisable:
	    path: /sys/module/apparmor/parameters/enabled
	    source: /dev/null
	    type: disk
	  eth0:
	    name: eth0
	    nictype: bridged
	    parent: lxdbr0
	    type: nic
	name: docker
	used_by: []

# Running the container

Container creation

	lxc launch ubuntu:14.04 docker -p docker

Output of `lxc show config docker --expanded`

	architecture: x86_64
	config:
	  linux.kernel_modules: overlay, nf_nat
	  raw.apparmor: |-
	    mount fstype=nfs,
	    mount fstype=nfs4,
	    mount fstype=nfsd,
	    mount fstype=rpc_pipefs,
	  security.nesting: "true"
	  security.privileged: "true"
	  volatile.base_image: 46d0f5634a550071b6495115f7bb87cd25c05d756405d9bc60bf464c04c9d249
	  volatile.eth0.hwaddr: 00:16:3e:10:80:71
	  volatile.idmap.base: "0"
	  volatile.idmap.next: '[]'
	  volatile.last_state.idmap: '[]'
	  volatile.last_state.power: RUNNING
	devices:
	  aadisable:
	    path: /sys/module/apparmor/parameters/enabled
	    source: /dev/null
	    type: disk
	  eth0:
	    name: eth0
	    nictype: bridged
	    parent: lxdbr0
	    type: nic
	  root:
	    path: /
	    type: disk
	ephemeral: false
	profiles:
	- docker
	stateful: false
	description: ""

Shell into container

	lxc exec docker bash

Output of `cat /etc/lsb-release` inside the container

	DISTRIB_ID=Ubuntu
	DISTRIB_RELEASE=14.04
	DISTRIB_CODENAME=trusty
	DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

Installation within the container:

    apt-get remove docker docker-engine docker.io ; \
    apt-get update && \
    apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    apt-key fingerprint 0EBFCD88 && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
   	apt-get update && \
   	apt-get install -y docker-ce

Then trying to run hello-world, I get

   	root@docker:~# docker run hello-world
	Unable to find image 'hello-world:latest' locally
	latest: Pulling from library/hello-world
	ca4f61b1923c: Pull complete 
	Digest: sha256:66ef312bbac49c39a89aa9bcc3cb4f3c9e7de3788c944158df3ee0176d32b751
	Status: Downloaded newer image for hello-world:latest
	docker: Error response from daemon: cgroups: cannot found cgroup mount destination: unknown.
	ERRO[0002] error waiting for container: context canceled 

Output of `docker version` within the container:

	Client:
	 Version:	17.12.0-ce
	 API version:	1.35
	 Go version:	go1.9.2
	 Git commit:	c97c6d6
	 Built:	Wed Dec 27 20:10:36 2017
	 OS/Arch:	linux/amd64

	Server:
	 Engine:
	  Version:	17.12.0-ce
	  API version:	1.35 (minimum version 1.12)
	  Go version:	go1.9.2
	  Git commit:	c97c6d6
	  Built:	Wed Dec 27 20:09:12 2017
	  OS/Arch:	linux/amd64
	  Experimental:	false

# Additional info

On some other threads, people have asked for some other info - so here it is:

On the 14.04 LXD container (where it doesn't work):

	root@docker:~# cat /proc/1/mountinfo | grep cgroup
	189 257 0:70 / /sys/fs/cgroup rw,relatime - tmpfs none rw,size=4k,mode=755
	193 189 0:28 / /sys/fs/cgroup/cpuset rw,relatime - cgroup cgroup rw,cpuset,clone_children
	194 189 0:27 / /sys/fs/cgroup/blkio rw,relatime - cgroup cgroup rw,blkio
	195 189 0:34 / /sys/fs/cgroup/memory rw,relatime - cgroup cgroup rw,memory
	196 189 0:26 / /sys/fs/cgroup/devices rw,relatime - cgroup cgroup rw,devices
	197 189 0:30 / /sys/fs/cgroup/freezer rw,relatime - cgroup cgroup rw,freezer
	198 189 0:33 / /sys/fs/cgroup/perf_event rw,relatime - cgroup cgroup rw,perf_event
	199 189 0:25 / /sys/fs/cgroup/hugetlb rw,relatime - cgroup cgroup rw,hugetlb
	200 189 0:29 / /sys/fs/cgroup/pids rw,relatime - cgroup cgroup rw,pids
	root@docker:~# cat /proc/self/cgroup
	11:memory:/
	10:perf_event:/
	9:net_cls,net_prio:/
	8:cpu,cpuacct:/
	7:freezer:/
	6:pids:/
	5:cpuset:/
	4:blkio:/
	3:devices:/
	2:hugetlb:/
	1:name=systemd:/

On a 16.04 LXD container (where it works):

	root@docker:~# cat /proc/1/mountinfo | grep cgroup
	191 256 0:72 / /sys/fs/cgroup ro,nosuid,nodev,noexec - tmpfs tmpfs ro,mode=755
	192 191 0:23 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
	193 191 0:32 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_cls,net_prio
	194 191 0:30 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer
	195 191 0:29 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,pids
	196 191 0:27 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio
	197 191 0:31 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpu,cpuacct
	198 191 0:33 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,perf_event
	199 191 0:25 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,hugetlb
	200 191 0:34 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory
	201 191 0:28 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset,clone_children
	202 191 0:26 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
	root@docker:~# cat /proc/self/cgroup
	11:memory:/
	10:perf_event:/
	9:net_cls,net_prio:/
	8:cpu,cpuacct:/
	7:freezer:/
	6:pids:/
	5:cpuset:/
	4:blkio:/
	3:devices:/
	2:hugetlb:/
	1:name=systemd:/

Output from `lxc info docker --show-log` on the host

	Name: docker
	Remote: unix://
	Architecture: x86_64
	Created: 2018/02/10 07:00 UTC
	Status: Running
	Type: persistent
	Profiles: docker
	Pid: 103255
	Ips:
	  docker0:	inet	172.17.0.1
	  docker0:	inet6	fe80::42:51ff:febd:cce
	  eth0:	inet	192.168.33.249	vethCQCGNF
	  eth0:	inet6	fe80::216:3eff:fe10:8071	vethCQCGNF
	  lo:	inet	127.0.0.1
	  lo:	inet6	::1
	Resources:
	  Processes: 72
	  Memory usage:
	    Memory (current): 392.04MB
	    Memory (peak): 409.05MB
	  Network usage:
	    docker0:
	      Bytes received: 0B
	      Bytes sent: 168B
	      Packets received: 0
	      Packets sent: 2
	    eth0:
	      Bytes received: 44.21MB
	      Bytes sent: 246.63kB
	      Packets received: 4482
	      Packets sent: 3181
	    lo:
	      Bytes received: 0B
	      Bytes sent: 0B
	      Packets received: 0
	      Packets sent: 0

	Log:

**Comment by stgraber** [comment]
Ubuntu 14.04 containers don't support the right cgroup layout and also don't support apparmor namespacing, both of which are needed to run Docker inside a LXD container.

So short of a lot of manual work on your end to manually put things into place, this isn't going to work.

The cgroup issue you're seeing above is because upstart (through cgroup-lite) and docker don't agree on the cgroup layout, unfortunately the kernel only allows for one layout to be in place (the one of your host), so you'd need to manually go and mangle /sys/fs/cgroup to match the layout you see on your host machine. But after that's solved, you're going to hit the apparmor issue which would likely require you to somehow disable apparmor in docker for that environment.

**Comment by dhallam** [comment]
Many thanks @stgraber
