### ISSUE TITLE
Spec and implement recursive GET

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#424]
Currently "lxc image list images:" against images.linuxcontainers.org returns 117 images. I'm 10ms away from the image server and that command is taking a whole 8 seconds to complete.

The reason for it is that the command in question expands to a total of 119 http queries. One for /1.0, one for /1.0/images and then one for every single image in the store.

There are two ways to optimize that. Either on the client by doing all the GETs in parallel which should cut down the time by a good 90% at the cost of more server usage (really bad thing for a public server).

Or we can implement a recursion flag which will have LXD (or in this case apache2-fake-lxd) replace references to objects by the object itself. So GET /1.0/images?recursion=1 will return a list of dicts representing the images rather than just a list of image URIs.

**Comment by techtonik** [comment]
Or use http://en.wikipedia.org/wiki/HTTP/2
