### ISSUE TITLE
monitoring of container uptime

### ISSUE THREAD

**Issue by skyxx** [lxc/lxd#4244]
# Required information

 * Distribution: Ubuntu Server
 * Distribution version:  16.04.3
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.4.0-104-generic #127-Ubuntu
   * LXC version: 2.1.1
   * LXD version: 2.21
   * Storage backend in use: filesytem

# Issue description

Hi all. Im try monitor container with netdata or prometheus_node_exporter monitoring and
there is a problem with system uptime reporting. Both (netdata and prometheus) report
uptime of the host not a container.

But command uptime and file /proc/uptime in container shows correct value.
How is possible that process running in container like netdata or prometheus cannot read  /proc/uptime of container correctly ?

Thanks.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)

architecture: x86_64
config:
  environment.http_proxy: ""
  image.architecture: amd64
  image.description: Ubuntu bionic amd64 (20180110)
  image.os: Ubuntu
  image.release: bionic
  image.serial: "20180105_03:49"
  user.network_mode: ""
  volatile.base_image: d69e3880e184128553eee52f640eb9fe8b2fad6f887d2ac0e2074fd7998963ec
  volatile.eth0.hwaddr: 00:16:3e:d9:5c:70
  volatile.eth0.name: eth0
  volatile.eth1.hwaddr: 00:16:3e:05:ff:65
  volatile.eth1.name: eth1
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  eth1:
    nictype: bridged
    parent: br1
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
- net-management
stateful: false
description: ""

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
This would be a lxcfs issue as that's where the /proc/uptime overlay lies.

It'd be good if you could check what logic is used by prometheus/netdata to figure out the uptime and then file an issue at https://github.com/lxc/lxcfs/issues so we can see what can be done.

My guess is that they're looking at the timestamp of some file in /proc, if that's the case, then it's pretty unlikely that we'll be able to do something about that, that is, other than recommend prometheus/netdata use another method of gathering the uptime which can properly be faked by lxcfs.
