### ISSUE TITLE
snap lxd.migrate: error: Unable to connect to the destination LXD: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: no such file or directory

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#4245]
ubuntu 17.10 32 bits with btrfs:

lxd source: 2.18
lxd dest: snap 2.21

steps:
--------
- sudo snap install lxd
lxd 2.21 de « canonical » installé

- sudo lxd.migrate 
=> Connecting to source server
=> Connecting to destination server
error: Unable to connect to the destination LXD: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: no such file or directory

sudo ls -la /var/snap/lxd/common/lxd/ :
total 68
drwx--x--x 1 root root   252 févr. 12 09:43 .
drwxr-xr-x 1 root root    62 févr. 12 09:40 ..
drwx------ 1 root root    38 févr. 12 09:43 cache
drwx--x--x 1 root root     0 févr. 12 09:40 containers
drwx--x--x 1 root root     0 févr. 12 09:40 devices
drwxr-xr-x 1 root root     0 févr. 12 09:40 devlxd
drwx------ 1 root root     0 févr. 12 09:40 disks
drwx------ 1 root root     0 févr. 12 09:40 images
drwx------ 1 root root    14 févr. 12 09:40 logs
-rw-r--r-- 1 root root 58368 févr. 12 09:40 lxd.db
drwx--x--x 1 root root     0 févr. 12 09:40 networks
drwx------ 1 root root     0 févr. 12 09:40 security
-rw-r--r-- 1 root root  1956 févr. 12 09:43 server.crt
-rw------- 1 root root  3243 févr. 12 09:43 server.key
drwx--x--x 1 root root     0 févr. 12 09:40 shmounts
drwx------ 1 root root     0 févr. 12 09:40 snapshots
drwx--x--x 1 root root     0 févr. 12 09:40 storage-pools
srw-rw---- 1 root lxd      0 févr. 12 09:43 unix.socket

**Comment by gaetanquentin** [comment]
strange: i launch the script a second time and now it is ok:

sudo lxd.migrate 
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks

**Comment by gaetanquentin** [comment]
the whole output: at the end there is an, error

sudo lxd.migrate 
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks

=== Source server
LXD version: 2.18
LXD PID: 3651
Resources:
  Containers: 3
  Images: 1
  Networks: 0
  Storage pools: 1

=== Destination server
LXD version: 2.21
LXD PID: 26631
Resources:
  Containers: 0
  Images: 0
  Networks: 0
  Storage pools: 0

The migration process will shut down all your containers then move your data to the destination LXD.
Once the data is moved, the destination LXD will start and apply any needed updates.
And finally your containers will be brought back to their previous state, completing the migration.

WARNING: /var/lib/lxd is a mountpoint. You will need to update that mount location after the migration.

Are you ready to proceed (yes/no) [default=no]? yes
=> Shutting down the source LXD
=> Stopping the source LXD units
=> Stopping the destination LXD unit
=> Unmounting source LXD paths
=> Unmounting destination LXD paths
=> Wiping destination LXD clean
=> Moving the /var/lib/lxd mountpoint
error: Failed to move the mountpoint: invalid argument

**Comment by stgraber** [comment]
I suspect you just were too fast the first time around and the snapped LXD wasn't done starting yet.

The mount failure is somewhat puzzling. Can you reboot this system (that should get things back online) and then paste the content of `cat /proc/self/mounts` as well as `btrfs subvol show /var/lib/lxd`?

**Comment by gaetanquentin** [comment]
gquentin@nas:~$ cat /proc/self/mount
mountinfo   mounts      mountstats
gquentin@nas:~$ cat /proc/self/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=1001636k,nr_inodes=206512,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=205120k,mode=755 0 0
/dev/sda1 / btrfs rw,noatime,compress=lzo,space_cache,subvolid=257,subvol=/@ 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14456 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
tmpfs /tmpfs tmpfs rw,relatime,size=921600k 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
/dev/loop0 /snap/core/3886 squashfs ro,nodev,relatime 0 0
/dev/loop1 /snap/core/3602 squashfs ro,nodev,relatime 0 0
/dev/loop4 /snap/core/3749 squashfs ro,nodev,relatime 0 0
/dev/loop2 /snap/lxd/5770 squashfs ro,nodev,relatime 0 0
/dev/loop3 /snap/lxd/5759 squashfs ro,nodev,relatime 0 0
/dev/sda1 /mnt/UUID_5770585f-2ac3-4681-a3ca-93d6287165f5 btrfs rw,noatime,compress=lzo,space_cache,subvolid=5,subvol=/ 0 0
/dev/sda1 /mnt/ROOT btrfs rw,noatime,compress=lzo,space_cache,subvolid=5,subvol=/ 0 0
/dev/sda1 /media/nas/Videos/Movies btrfs rw,noatime,compress=lzo,space_cache,subvolid=701,subvol=/@medias/@Movies 0 0
/dev/sda1 /home btrfs rw,noatime,compress=lzo,space_cache,subvolid=258,subvol=/@home 0 0
/dev/sda1 /media/nas/Videos/Deluge btrfs rw,noatime,compress=lzo,space_cache,subvolid=711,subvol=/@medias/@Deluge 0 0
/dev/sdb /mnt/UUID_e61c534d-fb68-4766-ba74-5305883ec77f btrfs rw,noatime,compress=lzo,space_cache,subvolid=5,subvol=/ 0 0
/dev/sdb /media/nas/Videos/TVShows btrfs rw,noatime,compress=lzo,space_cache,subvolid=993,subvol=/@medias/@Videos/@TVShows 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /run/snapd/ns tmpfs rw,nosuid,noexec,relatime,size=205120k,mode=755 0 0
nsfs /run/snapd/ns/lxd.mnt nsfs rw 0 0
tmpfs /var/lib/lxd/shmounts tmpfs rw,relatime,size=100k,mode=711 0 0
tmpfs /var/lib/lxd/devlxd tmpfs rw,relatime,size=100k,mode=755 0 0
/dev/sda1 /var/lib/lxd/devices/client-torrent/disk.data-Downloads btrfs rw,noatime,compress=lzo,space_cache,subvolid=711,subvol=/@medias/@Deluge 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
/dev/sda1 /var/lib/lxd/devices/showfinders/disk.data-Downloads-Deluge btrfs rw,noatime,compress=lzo,space_cache,subvolid=711,subvol=/@medias/@Deluge 0 0
/dev/sda1 /var/lib/lxd/devices/showfinders/disk.data-Downloads-Movies btrfs rw,noatime,compress=lzo,space_cache,subvolid=701,subvol=/@medias/@Movies 0 0
/dev/sdb /var/lib/lxd/devices/showfinders/disk.data-Downloads-TVShows btrfs rw,noatime,compress=lzo,space_cache,subvolid=993,subvol=/@medias/@Videos/@TVShows 0 0
tmpfs /var/lib/lxd/devices/showfinders/disk.tmpfs tmpfs rw,relatime,size=921600k 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=205116k,mode=700,uid=1000,gid=1000 0 0
/home/gquentin/.Private /home/gquentin ecryptfs rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=a12d5157bec5b371,ecryptfs_sig=8d1b3e4aa733508e,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs 0 0

gquentin@nas:~$ sudo btrfs subvol show /var/lib/lxd
var/lib/lxd
        Name:                   lxd
        UUID:                   a5eb1b8c-cc2d-5241-9c8f-c0f38f2130f7
        Parent UUID:            -
        Received UUID:          -
        Creation time:          2016-12-17 23:32:42 +0100
        Subvolume ID:           439
        Generation:             1057225
        Gen at creation:        12197
        Parent ID:              257
        Top level ID:           257
        Flags:                  -
        Snapshot(s):

**Comment by stgraber** [comment]
Thanks, that should be enough to reproduce the setup.

**Comment by stgraber** [comment]
Fix pushed to the stable snap. `snap refresh` should get you the fix. You'll need to reboot your system to get things mounted the right way before you can try the migration again though.

**Comment by gaetanquentin** [comment]
gquentin@nas:~$ sudo snap refresh lxd
snap "lxd" has no updates available
gquentin@nas:~$ sudo snap list
Nom   Version  Révision  Développeur  Notes
core  16-2.30  3886      canonical    core
lxd   2.21     5783      canonical    -

**Comment by stgraber** [comment]
Looks like you're already on the fixed version. snapd performs daily auto-updates so I guess it somehow did it just at the right time :)

**Comment by gaetanquentin** [comment]
yeah:

Are you ready to proceed (yes/no) [default=no]? yes
=> Shutting down the source LXD
=> Stopping the source LXD units
=> Stopping the destination LXD unit
=> Unmounting source LXD paths
=> Unmounting destination LXD paths
=> Wiping destination LXD clean
=> Moving the /var/lib/lxd mountpoint
=> Moving the database
=> Backing up the database
=> Opening the database
=> Updating the storage backends
=> Starting the destination LXD
=> Waiting for LXD to come online

=== Destination server
LXD version: 2.21
LXD PID: 988
Resources:
  Containers: 3
  Images: 1
  Networks: 0
  Storage pools: 1

WARNING: Make sure to update your system to mount your LXD directory at /var/snap/lxd/common/lxd

The migration is now complete and your containers should be back online.
Do you want to uninstall the old LXD (yes/no) [default=no]? yes

All done. You may need to close your current shell and open a new one to have the "lxc" command work.

**Comment by stgraber** [comment]
Cool, so looked like that worked.
