### ISSUE TITLE
No permission to apply cgroup settings

### ISSUE THREAD

**Issue by asarubbo** [lxc/lxd#4247]
* Distribution: Gentoo
 * Distribution version: Latest
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.9.74
   * LXC version: 2.1.1
   * LXD version: 2.21
   * Storage backend in use: dir on a btrfs partition
   * Udev version: 236

# Issue description
"No permission to apply cgroup settings" when start a init service. There is no systemd here but openrc, however I have a systemd fs mounted as:
systemd on /sys/fs/cgroup/systemd type cgroup (rw,relatime,name=systemd)

# Steps to reproduce

 1. Start whatever service via /etc/init.d/$SERVICE start

**Comment by brauner** [comment]
On Mon, Feb 12, 2018 at 02:32:12AM -0800, Agostino Sarubbo wrote:
>  * Distribution: Gentoo
>  * Distribution version: Latest
>  * The output of "lxc info" or if that fails:
>    * Kernel version: 4.9.74
>    * LXC version: 2.1.1
>    * LXD version: 2.21
>    * Storage backend in use: dir on a btrfs partition
>    * Udev version: 236
> 
> # Issue description
> "No permission to apply cgroup settings" when start a init service. There is no systemd here but openrc, however I have a systemd fs mounted as:
> systemd on /sys/fs/cgroup/systemd type cgroup (rw,relatime,name=systemd)

The systemd mountpoint shouldn't matter as this is just named cgroup
that openrc shouldn't care about. According to the affected openrc init
sscript this indicates that openrc doesn't have write permission for
that cgroup which seems weird given that LXD containers are started as
rroot. Can you show:

- cat /proc/1/cgroup
- cat /proc/1/mountinfo | grep cgroup

from inside the container, please?

**Comment by asarubbo** [comment]
```
template ~ # cat /proc/1/cgroup
9:name=systemd:/
8:freezer:/
7:devices:/
6:memory:/
5:blkio:/
4:cpuacct:/
3:cpu:/
2:cpuset:/
1:name=openrc:/
0::/
```

"cat /proc/1/mountinfo | grep cgroup" is empty

Before open a bug I tried something with cgmanager, but I don't know if there was the right direction

**Comment by brauner** [comment]
Right, so cgroups are not mounted. Can you show `ls -al /sys/fs/cgroup` from inside the container please.

**Comment by asarubbo** [comment]
```
template ~ # ls -al /sys/fs/cgroup/
totale 0
dr-xr-xr-x 2 nobody nobody 0 12 feb 12.59 .
drwxr-xr-x 5 nobody nobody 0 12 feb 12.59 ..
```

Since you said:
"given that LXD containers are started as root."
Am I supposed to start the container from the user root or not? Actually I'm managing the containers from an unprivileged user.

**Comment by brauner** [comment]
@asarubbo, no. It's all good the way you're doing it right now. So the problem simply is that Alpine doesn't mount cgroups by itself - in contrast to systemd - and the check it performs in the init script that you pointed me to is wrong or at least too simple:

```
if [ -d /sys/fs/cgroup -a ! -w /sys/fs/cgroup ]; then
        eerror "No permission to apply cgroup settings"
        break
fi
```

What it should do here is to check whether `/sys/fs/cgroup` is either a `tmpfs` or `cgroup2` mountpoint or even a mountpoint at all and then only check whether it can write to it or not. I can try and send a minimal patch to Alpine. Should only take a few minutes. But the error you're seeing is not fatal or a problem.
In the near future we will also have another option in LXC to mount cgroups for the container at which point you will also not have that problem anymore.

In any case, this is not a LXD issue so closing. I'll post a link to the PR once I've done it.

**Comment by brauner** [comment]
Here's the suggested fix for openrc upstream: https://github.com/OpenRC/openrc/pull/209

**Comment by asarubbo** [comment]
Ok, so it is right that the containers should not have the /sys/fs/cgroup mounted?

**Comment by brauner** [comment]
> Ok, so it is right that the containers should not have the /sys/fs/cgroup mounted?

Yes, Alpine does not mount cgroups on its own. You need to instruct it to do so afaik. This is different from systemd which will always try to mount cgroups.

**Comment by asarubbo** [comment]
Ok, but the real question is, do I need to have the cgroup fs mounted inside the container?

**Comment by brauner** [comment]
> Ok, but the real question is, do I need to have the cgroup fs mounted inside the container?

That depends on whether you need to be able to set cgroup limits from inside of the container. If you don't than you don't need them.

**Comment by asarubbo** [comment]
Ok, thanks for the answers and the help

For the record, the cgroup fs are mounted after the start of the sysfs service so:
```
/etc/init.d/sysfs start
```

In short, the provided gentoo image does not start the sysfs service.
