### ISSUE TITLE
Cannot start ntpd: ntp_adjtime() failed: Operation not permitted

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#4249]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Xenial
 * The output of "lxc info" or if that fails:
```
config: {}
api_extensions:
- id_map
- id_map_base
- resource_limits
api_status: stable
api_version: "1.0"
auth: trusted
auth_methods: []
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
  certificate_fingerprint: 700fa5b2b78bc504efbd6a7628d999b
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-112-generic
  server: lxd
  server_pid: 1602
  server_version: 2.0.11
  storage: dir
  storage_version: ""
```
# Issue description

After launching a centos 7 container, ntpd fails to start: `ntpd: ntp_adjtime() failed: Operation not permitted`

The container is unprivileged already. Is this issue related to the kernel?

Regards,

C.

**Comment by brauner** [comment]
> The ntp_adjtime() function is used	by the NTP daemon to adjust the	system     clock to an externally derived time.

Since we don't have a time namespace in the kernel (looking at you, @adrianreber :)) this is a big no-no. So yes, the kernel won't let you change the system clock since it would mean that an unprivileged container would change the time for the whole system. :)
