### ISSUE TITLE
vpnc in lxd

### ISSUE THREAD

**Issue by ddag** [lxc/lxd#4257]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4
   * LXC version: 2.0.11
   * LXD version: 2.0.11
   * Storage backend in use: dir

# Issue description

Get the following error trying to start vpnc inside of a Ubuntu 16.04 container:

Cannot open "/proc/sys/net/ipv4/route/flush": No such file or directory

# Steps to reproduce

1. create 16.04 container
2. apt-get install vpnc
3. sudo vpnc

**Comment by stgraber** [comment]
vpnc starts asking question when I run it here despite the /proc/sys/net/ipv4/route/flush file not existing.

In any case, those files being missing would be a kernel bug. LXD has no control as to what's visible in /proc and /sys inside the container. I've confirmed that those files are missing even on a very recent 4.15 kernel, so that doesn't appear to have been fixed at all.

I'd suggest you file a kernel bug, possibly at https://launchpad.net/ubuntu/+source/linux/+filebug (or running the `ubuntu-bug linux`) command. Feel free to post the resulting URL here so that others can find it.

**Comment by tyhicks** [comment]
@ddag hey there - did you ever file an Ubuntu kernel bug on Launchpad? I can't find one but I wanted to check with you.

I should be able to make the `/proc/sys/net/ipv4/route/flush` file show up inside of a LXD container (more specifically, within a non-init network namespace) but I don't have a server to test VPNC with. If I built you a test kernel, would you be able to test the fix?

**Comment by tyhicks** [comment]
@ddag are you still using the 4.4 based kernel from Ubuntu 16.04 LTS?

**Comment by ddag** [comment]
Yep:
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
$ uname -r
4.4.0-135-generic

**Comment by ddag** [comment]
I have another test machine on:
$ uname -r
4.15.0-34-generic
Both 16.04.5

**Comment by tyhicks** [comment]
@ddag test build here:

  https://people.canonical.com/~tyhicks/rtflush/v1/

Thanks for offering to test!

**Comment by ddag** [comment]
yay! works. thx! when will this fix be part of official release ?

**Comment by haad** [comment]
how about 18.04 ? I'm running bionic and I can see same problem here 

```vpnc[2789]: Cannot open "/proc/sys/net/ipv4/route/flush": No such file or directory
vpnc[2789]: Cannot open "/proc/sys/net/ipv4/route/flush": No such file or directory
vpnc[2789]: Cannot open "/proc/sys/net/ipv4/route/flush": No such file or directory
vpnc[2789]: Cannot open "/proc/sys/net/ipv4/route/flush": No such file or directory
vpnc[2789]: Cannot open "/proc/sys/net/ipv4/route/flush": No such file or directory
vpnc[2789]: Cannot open "/proc/sys/net/ipv4/route/flush": No such file or directory```

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

# uname -a
Linux lxc-vpn-cra 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by stgraber** [comment]
18.04 will need the same change, no kernels currently have this file present in network namespaces

**Comment by ky-ma** [comment]
Hi! my LXC is on 4.18.0-17-generic, how can i get my container setup to fix this too? thanks!

**Comment by brauner** [comment]
See
https://lore.kernel.org/lkml/20190624132923.16792-1-christian@brauner.io/
