### ISSUE TITLE
"lxd stop" hangs

### ISSUE THREAD

**Issue by jhobbs** [lxc/lxd#4267]
# Required information
 * Distribution: Ubuntu 16.04.3 LTS
 * The output of "lxc info": http://paste.ubuntu.com/p/GR8rHd8GrH/

# Issue description
We use lxc in our CI environment, starting a new container for each test, and then stopping it when the test is done.  Occasionally, "lxc stop" will hang for hours, only recovering when the lxd service is restarted.

I don't have a good way to reproduce this reliably.

# Information to attach

 - [x] Any relevant kernel output (`dmesg`): http://paste.ubuntu.com/p/jsmyYZ475Y/
 - [ ] Container log (`lxc info NAME --show-log`); - don't have this from the time of the failure
 - [x] Container configuration (`lxc config show NAME --expanded`): http://paste.ubuntu.com/p/qn8Fgj8FqB/
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log): http://paste.ubuntu.com/p/5G3rYqVkr6/
 - [ ] Output of the client with --debug: don't have this
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue): don't have this

**Comment by brauner** [comment]
Can you please show the output of `lxc info`?

**Comment by stgraber** [comment]
The `lxc info` was provided :)

**Comment by jhobbs** [comment]
Sorry, my report was a bit cluttered with template stuff; cleaned that up. We've added '--debug' to our CI's invocation of lxc stop, so when we hit this again I'll post that.

**Comment by stgraber** [comment]
Is `lxc stop --force` also affected?
If so, then look for a lxc-monitord process on your system and try killing that, it should unblock things.

If that's the case, then it's a solved bug for which the fix hasn't made it into Ubuntu 16.04 yet.
The LXD snap package would have that fix, if switching to the snap is an option for you.

**Comment by jhobbs** [comment]
I'll add --force also, thanks.

**Comment by stgraber** [comment]
Closing on the assumption that this is either the container misbehaving in which case --force will fix it or that it's the monitord issue. If neither of those work for you, comment here and we'll re-open.
