### ISSUE TITLE
Add "description" field on operations

### ISSUE THREAD

**Issue by dhope0000** [lxc/lxd#4268]
I can see from the docs that currently the operations API will return the [following values](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#get-20) , I would like to add an optional field at the end of the operationCreate method that adds a "human readable" type,

All calls to the method operationCreate appear in specific methods like "containerDelete" which could easily be translated into "Delete Container" so instead of end user applications having to store what type of operation was initiated or is running, it can be fetched along with the other data.

**Comment by stgraber** [comment]
Storing a description would probably be fine.

**Comment by dhope0000** [comment]
Where should I create description constants in the `shared/api/operations` file ?

**Comment by stgraber** [comment]
I'll send a fix for this, we'll want LXD itself to set the description, so we need changes to lxd/operations.go and everywhere we create operations inside the codebase, that field will then be exported through shared/api/operations and be made visible in lxc/operation.go too.
