### ISSUE TITLE
Setting lxc IP address during creation

### ISSUE THREAD

**Issue by emersonbarea** [lxc/lxd#4270]
# Required information

 * Distribution: Ubuntu
 * Distribution version: xenial
 * The output of "lxc info" or if that fails:

# lxc info
config:
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 2.1.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-112-generic
  server: lxd
  server_pid: 2651
  server_version: "2.21"
  storage: zfs

# Issue description

When I create a container and set a IP address in lxc configuration commands nothing hapens. Containers are still without IP address.

# Steps to reproduce

 1. Step one

Create a container and attach a interface

# lxc launch servidor container-1
# lxc network attach switch container-1 eth0

 2. Step two

Set a IP address

# lxc config device set container-1 eth0 ipv4.address 10.100.100.100

 3. Step three

Start container and verify IP address configuration

# lxc exec container-1 -- ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:16:3e:b7:80:88  
          inet6 addr: fe80::216:3eff:feb7:8088/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:143 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:11032 (11.0 KB)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:20 errors:0 dropped:0 overruns:0 frame:0
          TX packets:20 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:1740 (1.7 KB)  TX bytes:1740 (1.7 KB)

lxc exec container-1 -- reboot

# lxc exec container-1 -- ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:16:3e:b7:80:88  
          inet6 addr: fe80::216:3eff:feb7:8088/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:143 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:11032 (11.0 KB)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:20 errors:0 dropped:0 overruns:0 frame:0
          TX packets:20 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:1740 (1.7 KB)  TX bytes:1740 (1.7 KB)

Verifing container IP files configuration:

# cat /etc/network/interfaces.d/50-cloud-init.cfg 
auto lo
iface lo inet loopback
auto eth0
iface eth0 inet dhcp

Verifing container LXC's configuration:

# lxc config show container-1 --expanded
architecture: x86_64
config:
  environment.http_proxy: ""
  user.network_mode: ""
  volatile.base_image: e5e404a60bb454a540c986ba4bff0711b1fd115fbf81184ca910bc7ed90b33f5
  volatile.eth0.hwaddr: 00:16:3e:15:04:71
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    ipv4.address: 10.100.100.100
    nictype: bridged
    parent: switch
    type: nic
  root:
    path: /
    pool: honeynet
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

# lxc info container-1 --show-log
Nome: container-1
Remote: unix://
Arquitetura: x86_64
Criado: 2018/02/21 20:22 UTC
Estado: Running
Tipo: persistente
Perfis: default
Pid: 11402
Ips:
  eth0:	inet6	fe80::216:3eff:fe15:471	vethXLJYE5
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Recursos:
  Processos: 27
  Disk usage:
    root: 43.46MB
  CPU usage:
    CPU usage (in seconds): 2
  Memory usage:
    Memória (atual): 66.13MB
    Memória (máxima): 88.39MB
  Network usage:
    eth0:
      Bytes recebidos: 3.69kB
      Bytes enviados: 648B
      Pacotes recebidos: 60
      Pacotes enviados: 8
    lo:
      Bytes recebidos: 1.70kB
      Bytes enviados: 1.70kB
      Pacotes recebidos: 20
      Pacotes enviados: 20

Registo:

            lxc 20180221202639.415 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180221202639.415 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180221202639.643 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180221202639.643 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [X] Container log (`lxc info NAME --show-log`)
 - [X] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
That's normal, you're starting the container, which then configures itself, after that you remove and replace its eth0 device without ever re-triggering the DHCP client in the container.

Instead you should do:

```
lxc init servidor container-1
lxc network attach switch container-1 eth0 eth0
lxc config device set container-1 eth0 ipv4.address 10.100.100.100
lxc start container-1
```

Note that this assumes that `switch` is a LXD managed bridge that has DHCP enabled on it, otherwise ipv4.address isn't going to do anything for you.

**Comment by davidfavor** [comment]
Doesn't quite work for for me. Likely I've missed a step.

This setup using a freshly installed OVH machine using Ubuntu Artful + snap install LXD + /snap/bin in path.

Here are the steps I followed. Let me know what I missed.


```
# Bootstrap LXD
lxd init --auto --storage-backend=dir
lxc network create lxdbr0
lxc network attach-profile lxdbr0 default eth0

# Route packets for IP range bidirectionally over lxdbr0
ip -4 route add 144.217.34.0/27 dev lxdbr0

# Create a container + associate IP + start container
lxc init ubuntu:artful net11-dns
lxc network attach lxdbr0 net11-dns eth0 eth0
lxc config device set net11-dns eth0 ipv4.address 144.217.34.5
lxc start net11-dns

# Ensure IP shows up in config
lxc config device show net11-dns
eth0:
  ipv4.address: 144.217.34.5
  name: eth0
  nictype: bridged
  parent: lxdbr0
  type: nic
```
Now IP doesn't show up at machine level...
```
net11 # lxc list
+--------------------+---------+---------------------+-----------------------------------------------+------------+-----------+
|        NAME        |  STATE  |        IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+--------------------+---------+---------------------+-----------------------------------------------+------------+-----------+
| net11-dns          | RUNNING | 10.191.76.23 (eth0) | fd42:d831:292e:c725:216:3eff:fe74:402c (eth0) | PERSISTENT | 0         |
+--------------------+---------+---------------------+-----------------------------------------------+------------+-----------+
| net11-dns-original | STOPPED |                     |                                               | PERSISTENT | 0         |
+--------------------+---------+---------------------+-----------------------------------------------+------------+-----------+
```
Inside container /etc/netplan/* is missing entries.

Maybe I've munged **lxc config device set net11-dns eth0 ipv4.address 144.217.34.5** somehow.

Or maybe IP assignment can only occur inside container via a netplan file.

Let me know best approach for setting the container IP.

Thanks.

**Comment by stgraber** [comment]
@davidfavor ipv4.address can only refer to an address that's controlled by the dnsmasq instance that LXD runs. You can't set it to an ipv4 address that you just happen to have routed to that bridge.

In your case, adding the public address to the container on top of whatever private address it gets through DHCP is indeed something to be configured inside the container, which can be done with netplan.

**Comment by emersonbarea** [comment]
Thank you Stéphane. I think that it is my problem (how you said: Note that
this assumes that switch is a LXD managed bridge that has DHCP enabled on
it, otherwise ipv4.address isn't going to do anything for you.). Because
"switch" is a OVS bridge that lxc container is attached. I'm not using lxd
network bridge.

So, I think that I'll need to use something like this:
lxc launch servidor container-1 -n switch --config
volatile.switch.hwaddr=52:54:00:bc:e4:02 (to setup mac-address how I need),
and
lxc exec container-1 -- ifconfig eth0 10.10.10.10/24 up

But I wanted launch my container with all network configuration in only one
command.

Thank you.




2018-02-21 18:58 GMT-03:00 Stéphane Graber <notifications@github.com>:

**Comment by emersonbarea** [comment]
Thank you Stéphane. I think that it is my problem (how you said: Note that this assumes that switch is a LXD managed bridge that has DHCP enabled on it, otherwise ipv4.address isn't going to do anything for you.). Because "switch" is a OVS bridge that lxc container is attached. I'm not using lxd network bridge.

So, I think that I'll need to use something like this:
lxc launch servidor container-1 -n switch --config volatile.switch.hwaddr=52:54:00:bc:e4:02 (to setup mac-address how I need), and
lxc exec container-1 -- ifconfig eth0 10.10.10.10/24 up

But I wanted launch my container with all network configuration in only one command.

Thank you.

**Comment by stgraber** [comment]
@emersonbarea You may also be able to push network configuration into place in the container using "lxc file push" before starting it, or if using an Ubuntu container, you can pass yaml formatted network configuration through cloud-init which will be applied by the container on its first boot.

**Comment by davidfavor** [comment]
Thanks.

So using a /etc/netplan file is the trick. Retested the netplan file from a previous issue + all appear well.

```
# /etc/netplan/60-public-init.yaml
network:
    version: 2
    ethernets:
        eth0:
            addresses:
            - 144.217.34.1/32
```
