### ISSUE TITLE
snap migration: lxd.migrate should copy certificates/key in new location

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#4271]
lxd 2.21,  migration from classic package to snap.
when using lxd.migrate:

new certificates/keys are created when migrating to snap packaging:

after migration, ~/snap/lxd/${id}/.config/lxc contains new client.crt and client.key

old ~/.config/lxc/client.* should be copied in instead.

if not, all already declared remotes do not trust anymore

**Comment by stgraber** [comment]
Oh yeah, that's absolutely right, you should move your ~/.config/lxc/ to snap/lxd/current/.config/lxc/ to keep all your remotes and config. It's not something we can/should be doing from you in the migrate tool, but something we should print a message about for sure.

**Comment by stgraber** [comment]
Fix pushed to our packaging branches.

**Comment by gaetanquentin** [comment]
Eh!

 je ne savais pas que tu parlais en Français ;-)
tu as fait une démo hier dans ma société (Extia), Meetup Ops. 
(https://www.youtube.com/watch?v=ne3l4COcGjw)

Dommage, je n'étais pas là.

**Comment by stgraber** [comment]
:)
