### ISSUE TITLE
Simple lxc copy between physical machines sometimes breaks root uid

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#4279]
After simple container root uid seems munged/broken/incorrect.

Note: This only seems to occur intermittently. Other containers I've copied seemed to be correct.

Unsure exactly how to debug this. Let me know what data is required to work out a permanent fix.

Also, I'm in the middle of migrating many containers between machines to do OS updates on machines... so...

Be great to have a temp fix of how I can somehow reset all uid/gid numbers in copied container.

Thanks.
_______
```
# Commands issued...
net11 # lxc copy net11-dns net12:net11-dns-backup
# At this point, permissions seem correct in net12:net11-dns-backup container
# Do full install of Ubuntu Artful from scratch (obliterating all data) + install LXD via snap
net11 # lxc copy net12:net11-dns-backup net11-dns
# At this point, root's uid seems wrong.
# Container's root's uid looks to be 1100000 at machine level.
# Container's root's uid inside container is 1000000.
```
# local machine (snap)
net11 # snap list
Name  Version    Rev   Developer  Notes
core  16-2.31.1  4110  canonical  core
lxd   2.21       5866  canonical  -
```
```
# remote machine (apt)
net10 # lxd --version
2.12
```
Inside local net11:net11-dns container...
```
# Files should by uid=0, rather than uid=100000
lxd: net11-dns # ll -n
total 40K
drwxr-xr-x  2 100000   0 4.0K Apr 11  2017 apparmor/
drwxr-xr-x  3 100000   0 4.0K Feb 23 09:06 apt/
drwxrwxr-x  2 100000 119 4.0K Feb 22 09:23 bind/
drwxr-xr-x  2 100000   0 4.0K Feb 18 11:28 debconf/
drwx------  2 100000   0 4.0K Feb 23 09:05 ldconfig/
drwx------  2 100000   0 4.0K Jun 24  2017 lxd/
drwxr-xr-x 28      6  12 4.0K Feb 23 09:05 man/
drwxr-xr-x  2 100111   0 4.0K Jun 19  2017 pollinate/
drwxr-xr-x  2 100000   0 4.0K Feb 19 11:34 snapd/
-rw-r--r--  1 100000   0  150 Feb 22 22:10 motd-news
```
At machine level...
```
cd /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns/rootfs/var/cache
net11 # ll -n
total 40K
drwxr-xr-x  2 1100000 1000000 4.0K Apr 11  2017 apparmor/
drwxr-xr-x  3 1100000 1000000 4.0K Feb 23 09:06 apt/
drwxrwxr-x  2 1100000 1000119 4.0K Feb 22 09:23 bind/
drwxr-xr-x  2 1100000 1000000 4.0K Feb 18 11:28 debconf/
drwx------  2 1100000 1000000 4.0K Feb 23 09:05 ldconfig/
drwx------  2 1100000 1000000 4.0K Jun 24  2017 lxd/
drwxr-xr-x 28 1000006 1000012 4.0K Feb 23 09:05 man/
drwxr-xr-x  2 1100111 1000000 4.0K Jun 19  2017 pollinate/
drwxr-xr-x  2 1100000 1000000 4.0K Feb 19 11:34 snapd/
-rw-r--r--  1 1100000 1000000  150 Feb 22 22:10 motd-news
```
Config of local container...
```
net11 # lxc config show net11-dns
architecture: x86_64
config:
  boot.autostart: "1"
  image.architecture: amd64
  image.description: ubuntu 17.04 amd64 (release) (20170619.1)
  image.label: release
  image.os: ubuntu
  image.release: zesty
  image.serial: "20170619.1"
  image.version: "17.04"
  volatile.base_image: f50337be60f7fce4ddd71397285490115e208aeb37565b8d77529cb352cdad05
  volatile.eth0.hwaddr: 00:16:3e:9d:cb:18
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  david-favor:
    path: /david-favor
    source: /david-favor
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
Config of remote container...
```
net12 # lxc config show net11-dns-backup
architecture: x86_64
config:
  boot.autostart: "1"
  image.architecture: amd64
  image.description: ubuntu 17.04 amd64 (release) (20170619.1)
  image.label: release
  image.os: ubuntu
  image.release: zesty
  image.serial: "20170619.1"
  image.version: "17.04"
  volatile.base_image: f50337be60f7fce4ddd71397285490115e208aeb37565b8d77529cb352cdad05
  volatile.eth0.hwaddr: 00:16:3e:2b:42:58
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
devices:
  david-favor:
    path: /david-favor
    source: /david-favor
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

**Comment by stgraber** [comment]
Any chance you can upgrade your remote LXD (net10) to 2.21 too?

**Comment by stgraber** [comment]
Oh and did you try starting the container?

The config you posted above shows that the container will be remapped on startup, so if you never started it, then the on-disk uid/gid would indeed be wrong.

**Comment by stgraber** [comment]
Hmm, ignore that last one, I misread the config dump above, the current and next maps are identical...

**Comment by stgraber** [comment]
So would be nice if you could try with LXD 2.21 on both sides. The migration protocol isn't version specific but it may well be that we fixed a bug in uid/gid handling since 2.12 came out.

**Comment by davidfavor** [comment]
No way to upgrade remote.

The point of what I'm doing is migrating all containers out of old LXD to new LXD, so machine where old LXD is running can be installed from scratch again.

Super weird problem. Some containers come across fine + others have base (root) uid set incorrectly.

I'll check each container with the following...
```
find / -printf "%u %g %p\n" | grep -P "^\d+\s+"
```
And reset all root IDs by hand when required. This might include all uids. I'm unsure.

Containers start, they just fail in odd ways... because... read bits are on for all files, they just can't be written. This causes subtle errors to begin with + likely, container will eventually die.

**Comment by davidfavor** [comment]
The gids settings seem correct.

Let me know the correct way to repair a container's base uid.

Thanks.

**Comment by stgraber** [comment]
Ok, so to fix the issue when you get containers with the wrong map, the easiest is probably to run `lxc config edit` against them.

You'll see two idmap lines:
```
volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
```

`volatile.idmap.next` is the map that should be applied for this container next time it starts. `volatile.last_state.idmap` is what LXD thinks is currently applied and what should be used for the on-disk data.

You can alter `volatile.last_state.idmap` to match what you have on disk, then start the container and LXD will do the needed remapping at that time.

Each of those lines first contains the map for uids (isuid=true) and then the map for gids (isgid=true), they typically are identical.

**Comment by davidfavor** [comment]
Thanks!

I'll give it a try.

**Comment by davidfavor** [comment]
Nope. Doesn't work.

Changing the value of volatile.idmap.next is usurped when container starts.

If I set this value to 1100000, during container start this value changes to 1200000.

Tried several times + value never honored. It's always changed/incremented.

Same result doing the lxc edit on container in running state + stopped state.

Let me know what else to try.

**Comment by davidfavor** [comment]
Arg... Misread your comment + changed the wrong value.

**Comment by davidfavor** [comment]
That fixed uids + now gids are all incorrect.

Let me know how to fix gids now.

Thanks.

**Comment by davidfavor** [comment]
Nothing stands out in **lxc config edit** to change gid numbers.

Example of gid numbering...

```
# Outside container...
net11 # cd /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns/rootfs/var/cache
net11 # ll -n
total 40K
drwxr-xr-x  2 1200000 2400000 4.0K Apr 11  2017 apparmor/
drwxr-xr-x  3 1200000 2400000 4.0K Feb 24 08:00 apt/
drwxrwxr-x  2 1200000 2400119 4.0K Feb 24 07:16 bind/
drwxr-xr-x  2 1200000 2400000 4.0K Feb 18 11:28 debconf/
drwx------  2 1200000 2400000 4.0K Feb 23 09:05 ldconfig/
drwx------  2 1200000 2400000 4.0K Jun 24  2017 lxd/
drwxr-xr-x 28 1200006 1200012 4.0K Feb 23 09:05 man/
drwxr-xr-x  2 1200111 2400000 4.0K Jun 19  2017 pollinate/
drwxr-xr-x  2 1200000 2400000 4.0K Feb 23 09:28 snapd/
-rw-r--r--  1 1200000 2400000  150 Feb 24 07:30 motd-news
```
```
# Inside container...
net11 # lxc exec net11-dns bash
lxd: net11-dns # cd /var/cache
lxd: net11-dns # ll -n
total 40K
drwxr-xr-x  2   0 1200000 4.0K Apr 11  2017 apparmor/
drwxr-xr-x  3   0 1200000 4.0K Feb 24 08:00 apt/
drwxrwxr-x  2   0 1200119 4.0K Feb 24 07:16 bind/
drwxr-xr-x  2   0 1200000 4.0K Feb 18 11:28 debconf/
drwx------  2   0 1200000 4.0K Feb 23 09:05 ldconfig/
drwx------  2   0 1200000 4.0K Jun 24  2017 lxd/
drwxr-xr-x 28   6      12 4.0K Feb 23 09:05 man/
drwxr-xr-x  2 111 1200000 4.0K Jun 19  2017 pollinate/
drwxr-xr-x  2   0 1200000 4.0K Feb 23 09:28 snapd/
-rw-r--r--  1   0 1200000  150 Feb 24 07:30 motd-news
```

**Comment by davidfavor** [comment]
Note: New files created via something like **touch foo** show correct uid/gid.

Only existing files seem effected by this problem.

**Comment by stgraber** [comment]
For the gids, you'd need to modify the second part of the last_state idmap, making the hostid 2400000, though it looks like you have some directories (man above) that already have the right owner so those may end up mangled in the process, though I'm hopeful that our code will just skip anything that would end up with a new negative gid.

**Comment by stgraber** [comment]
Ok, lets try fixing this by hand then:
```
apt install lxd-tools
lxc start net11-dns
fuidshift  /var/snap/lxd/common/mntns/var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns/rootfs -t -r g:0:1200000:100000000
```

This should just output a whole bunch of things but not actually change anything. Based on the output I should be able to figure out what needs manual fixing before we can run the tool and have it fix the rest.

The source of the issue I suspect is that some directories are actually owned by the right gid, causing the shifter to fail when it hits them.

**Comment by davidfavor** [comment]
Did...
```
net11 # fuidshift /var/snap/lxd/common/mntns/var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns/rootfs -t -r g:0:1200000:100000000 > ~/fuidshift.txt
```
[fuidshift.zip](https://github.com/lxc/lxd/files/1756504/fuidshift.zip)

**Comment by davidfavor** [comment]
Container name has changed. The effected container was a DNS instance for 100s of sites, so I created a new container + renamed the broken container.

```
lxc stop net11-dns
lxc move net11-dns net11-dns-broken
# disabled public IP in net11-dns-broken
lxc start net11-dns-broken
fuidshift /var/snap/lxd/common/mntns/var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs -t -r g:0:1200000:100000000 > ~/fuidshift.txt
```
Zip file of output attached.

Thanks for your assistance!
[fuidshift.zip](https://github.com/lxc/lxd/files/1756517/fuidshift.zip)

**Comment by stgraber** [comment]
Please run:
```bash
chgrp -R 1200000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/tmp
chgrp -R 1200000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/backups
chgrp -R 1200012 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/cache/man
chgrp -R 1200000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/cache/snapd
chgrp -R 1200000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/cloud/
chgrp -R 1200033 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/www
chgrp 1200000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/logrotate/status
chgrp 1200112 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/mlocate/mlocate.db
chgrp 1200000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/systemd
chgrp 1200000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/systemd/coredump
chgrp 1200000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/ubuntu-release-upgrader/release-upgrade-available
chgrp 1200000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/update-notifier/updates-available
chgrp 1200108 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/log
chgrp 1200032 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/log/btmp
chgrp 1200004 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/log/cloud-init.log
chgrp 1200043 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/log/lastlog
chgrp 1200043 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/log/wtmp
rm /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/apt/lists/*
```

And then re-run the fuidshift command I gave earlier and give me the updated output, hopefully with those changes it'll look good and then you can go with running it in normal mode rather than test mode.

**Comment by davidfavor** [comment]
Commands run + data attached.

[fuidshift.zip](https://github.com/lxc/lxd/files/1756768/fuidshift.zip)

**Comment by stgraber** [comment]
Doh, I messed up :)

**Comment by stgraber** [comment]
Please run:
```
chgrp -R 2400000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/tmp
chgrp -R 2400000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/backups
chgrp -R 2400012 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/cache/man
chgrp -R 2400000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/cache/snapd
chgrp -R 2400000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/cloud/
chgrp -R 2400033 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/www
chgrp 2400000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/logrotate/status
chgrp 2400112 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/mlocate/mlocate.db
chgrp 2400000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/systemd
chgrp 2400000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/systemd/coredump
chgrp 2400000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/ubuntu-release-upgrader/release-upgrade-available
chgrp 2400000 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/update-notifier/updates-available
chgrp 2400108 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/log
chgrp 2400032 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/log/btmp
chgrp 2400004 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/log/cloud-init.log
chgrp 2400043 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/log/lastlog
chgrp 2400043 /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/log/wtmp
rm /var/snap/lxd/common/lxd/storage-pools/default/containers/net11-dns-broken/rootfs/var/lib/apt/lists/*
```

**Comment by stgraber** [comment]
Then re-run the fuidshift, that time it should finally show all the groups being shifted to 120XXXX

**Comment by stgraber** [comment]
@davidfavor

**Comment by stgraber** [comment]
@davidfavor ping

**Comment by davidfavor** [comment]
This problem requires a fix that works instantly, anytime this problem occurs.

I'll just write a script to scan containers + fix problems found.

**Comment by davidfavor** [comment]
Didn't mean to sound terse.

Just production problems require an instant fix which works first time, with no bouncing back + forth running fuidshift + chgrp commands.

**Comment by davidfavor** [comment]
Thanks for your time on this.
