### ISSUE TITLE
Permission Denied LXD fails to start image

### ISSUE THREAD

**Issue by rayxis** [lxc/lxd#4281]
# Required information

 * Distribution: CentOS
 * Distribution version: 7
 * The output of "lxc info" or if that fails:

   -----END CERTIFICATE-----
  certificate_fingerprint: 00fddc3717df5c0137eea68afb5f1a392d0036fb6d68e7c7aa0221e9047fc750
  driver: lxc
  driver_version: 1.0.11
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.5-1.el7.elrepo.x86_64
  server: lxd
  server_pid: 6885
  server_version: "2.21"
  storage: dir
  storage_version: "1"

   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use: dir (lxcfs never works)

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
[raydev@dev ~]$ sudo lxc start visage
error: Failed to run: /usr/bin/lxd forkstart visage /var/lib/lxd/containers /var/log/lxd/visage/lxc.conf: 
Try `lxc info --show-log visage` for more info
 2. Step two
[raydev@dev ~]$ sudo lxc info --show-log visage
Name: visage
Remote: unix://
Architecture: x86_64
Created: 2018/02/24 04:55 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

  lxc_container 1519448642.367 WARN     lxc_start - start.c:lxc_check_inherited:228 - inherited fd 6
  lxc_container 1519448642.367 WARN     lxc_start - start.c:lxc_check_inherited:228 - inherited fd 6
  lxc_container 1519448642.813 ERROR    lxc_conf - conf.c:mk_devtmpfs:1349 - Permission denied - Unable to create /dev/.lxc for autodev
  lxc_container 1519448642.817 ERROR    lxc_conf - conf.c:setup_autodev:1552 - Operation not permitted - Error creating null
  lxc_container 1519448642.817 ERROR    lxc_conf - conf.c:lxc_setup:4349 - failed to populate /dev in the container
  lxc_container 1519448642.817 ERROR    lxc_start - start.c:do_start:732 - failed to setup the container
  lxc_container 1519448642.817 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
  lxc_container 1519448642.818 WARN     lxc_conf - conf.c:lxc_delete_network:3444 - failed to remove interface 11 'eth0'
  lxc_container 1519448642.818 ERROR    lxc_start - start.c:__lxc_start:1149 - failed to spawn 'visage'
  lxc_container 1519448642.866 ERROR    lxc_conf - conf.c:run_buffer:353 - Script exited with status 1
  lxc_container 1519448642.866 ERROR    lxc_start - start.c:lxc_fini:501 - failed to run post-stop hooks for container 'visage'.
  lxc_container 1519448642.866 WARN     lxc_conf - conf.c:lxc_delete_autodev:1606 - Failed to locate autodev /dev/.lxc and /dev/.lxc/user.
  lxc_container 1519448642.870 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:178 - Command get_cgroup failed to receive response: Connection reset by peer.
  lxc_container 1519448642.870 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:178 - Command get_cgroup failed to receive response: Connection reset by peer.

 3. Step three
When I created /dev/.lxc and chmod 777, the file created is owned by 100000 and continues to generate errors.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
ephemeral=false lvl=info msg="Created container" name=visage t=2018-02-23T23:55:24-0500
action=start created=2018-02-24T04:55:24+0000 ephemeral=false lvl=info msg="Starting container" name=visage stateful=false t=2018-02-23T23:55:42-0500 used=1970-01-01T00:00:00+0000
container=visage lvl=eror msg="Container sent invalid target to OnStop" t=2018-02-23T23:55:42-0500 target=unknown
container=visage err="Invalid stop target: unknown" lvl=eror msg="stop hook failed" t=2018-02-23T23:55:42-0500
action=start created=2018-02-24T04:55:24+0000 ephemeral=false lvl=eror msg="Failed starting container" name=visage stateful=false t=2018-02-23T23:55:47-0500 used=1970-01-01T00:00:00+0000
action=start created=2018-02-24T04:55:24+0000 ephemeral=false lvl=info msg="Starting container" name=visage stateful=false t=2018-02-24T00:04:02-0500 used=2018-02-24T04:55:42+0000
container=visage lvl=eror msg="Container sent invalid target to OnStop" t=2018-02-24T00:04:02-0500 target=unknown
container=visage err="Invalid stop target: unknown" lvl=eror msg="stop hook failed" t=2018-02-24T00:04:02-0500
action=start created=2018-02-24T04:55:24+0000 ephemeral=false lvl=eror msg="Failed starting container" name=visage stateful=false t=2018-02-24T00:04:07-0500 used=2018-02-24T04:55:42+0000

 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
LXD requires liblxc 2.0.0 or higher to function. You're attempting to have it run against liblxc 1.0.11 here which isn't going to work.

You should either update liblxc to 2.0.x (which I believe is available through some repositories), then rebuild go-lxc and lxd against that, or use the possibly simpler solution of running the LXD snap for Centos 7 which comes with all the right bits bundled:

https://discuss.linuxcontainers.org/t/lxd-on-centos-7/1250
