### ISSUE TITLE
container mount points vanish

### ISSUE THREAD

**Issue by spape84** [lxc/lxd#4299]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: LVM (two pools)

lxc info: `config:
  core.https_address: xx.xxx.xx.xx:9000
  core.https_allowed_credentials: "true"
  core.https_allowed_headers: Origin, X-Requested-With, Content-Type, Accept
  core.https_allowed_methods: GET, POST, PUT, DELETE, OPTIONS
  core.https_allowed_origin: https://xx.xxx.xx.xx:8443
  images.auto_update_cached: "false"
  images.auto_update_interval: "24"
  images.remote_cache_expiry: "5"
  storage.lvm_thinpool_name: Thinpool
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - xx.xxx.xx.xx:9000
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
 <xxx>
    -----END CERTIFICATE-----
  certificate_fingerprint: <xxx>
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-116-generic
  server: lxd
  server_pid: 1731
  server_version: "2.21"
  storage: lvm
  storage_version: 2.02.133(2) (2015-10-30) / 1.02.110 (2015-10-30) / 4.34.0`

# Issue description

I have a machine running 10 containers using two LVM storage pools. The first storage pool ist located on a bcache enhanced md RAID and the second is pool is a plain SSD.

The mountpoints of the containers just seem to vanish from "mount" after some time. This happens just sometimes to some containers. The containers keep running after the mountpoints are gone and from within the containers everything looks fine, but the mount points at /var/lib/lxd/containers/ are just gone. I wasn't able to find any logs with something like "un-mount"/"unmount"/"umount" in them.

Restarting the containers makes the mount points appear again.

So far the issue doesn't seem to corrupt anything so it might not be critical. Pls. tell me, which logs you need and I'll send them...

# Steps to reproduce

1. Start a container with LVM backed storage (in my case) lxc start container1
2. Wait some time (a few hours...)

# Information to attach

/var/log/lxd/lxd.log

`action=stop created=2017-02-12T17:20:00+0000 ephemeral=false lvl=info msg="Container initiated stop" name=container1 stateful=false t=2018-03-04T10:27:54+0100 used=2018-03-02T07:45:41+0000
action=shutdown created=2017-02-12T17:20:00+0000 ephemeral=false lvl=info msg="Shut down container" name=container1 t=2018-03-04T10:27:54+0100 timeout=-1s used=2018-03-02T07:45:41+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=container1 t=2018-03-04T10:29:53+0100
action=start created=2017-02-12T17:20:00+0000 ephemeral=false lvl=info msg="Starting container" name=container1 stateful=false t=2018-03-04T10:29:59+0100 used=2018-03-02T07:45:41+0000
action=start created=2017-02-12T17:20:00+0000 ephemeral=false lvl=info msg="Started container" name=container1 stateful=false t=2018-03-04T10:30:00+0100 used=2018-03-02T07:45:41+0000`

**Comment by stgraber** [comment]
The mountpont going away on the host won't affect your container at all, so there's no risk of data loss or other problems because of that. LXD will automatically mount it again if needed.

It's still odd that it'd get unmounted somewhat randomly like this.

Could you run your system passing the "--debug" option to LXD? that would provide a more comprehensive log including all mount/umount run by LXD itself. That'll let us track down if it's LXD itself causing the umount and if it is, why it was performed.

If you're using the LXD deb, you should be able to do so with `systemctl edit lxd`, entering the following:
```
[Service]
ExecStart=
ExecStart=/usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log --debug
```
And then run `systemctl restart lxd` to have it applied.

If using the snap, run `snap set lxd daemon.debug=true` followed by `systemctl reload lxd`.

Then wait until the problem happens again and give us the content of your lxd.log at that point.

**Comment by spape84** [comment]
OK. Thank you. I restarted LXD with the settings applied. I'll get back to you as soon as I notice another unmount!

**Comment by spape84** [comment]
Hi!

As this is a production server I removed some containers from the list, but the findings are as follows:
`
%date; mount | grep container
Mon  5 Mar 10:35:03 CET 2018
/dev/mapper/ssd-containers_sql01 on /var/lib/lxd/storage-pools/ssd/containers/sql01 type ext4 (rw,relatime,discard,stripe=64,data=ordered)
/dev/mapper/0-containers_mailin on /var/lib/lxd/storage-pools/0/containers/mailin type ext4 (rw,relatime,block_validity,discard,delalloc,barrier,user_xattr,acl,stripe=16)
/dev/mapper/0-containers_ssl on /var/lib/lxd/storage-pools/0/containers/ssl type ext4 (rw,relatime,block_validity,discard,delalloc,barrier,user_xattr,acl,stripe=16)
/dev/mapper/0-containers_k00v1 on /var/lib/lxd/storage-pools/0/containers/k00v1 type ext4 (rw,relatime,block_validity,discard,delalloc,barrier,user_xattr,acl,stripe=16)

%date; mount | grep container
Tue  6 Mar 13:55:34 CET 2018

-- nothing found --
`

I didn't touch any of the containers (ssl, mailin, k00v1 or sql01). 

I also wasn't able to find any mounts or unmounts in the LXD logfile. Logfile is attached.
[logfiles-attachment.zip](https://github.com/lxc/lxd/files/1785064/logfiles-attachment.zip)

**Comment by stgraber** [comment]
I see a whole bunch of mount/umount in your logs but none of the containers above and for those that I can  find in the logs they all appear to be as expected, so resulting in a mount when starting the container and no umount after that until the container is shut down.

**Comment by stgraber** [comment]
I've just confirmed that all of our unmounting codepaths would result in a log entry, so it looks like it's something outside of LXD doing this somehow.

Can you run those?

 - journalctl | grep sql01
 - journalctl | grep mailin
 - journalctl | grep ssl
 - journalctl | grep k00v1

I'm hoping that we can see the mount units being added and removed and who knows, maybe see what's causing that.

**Comment by spape84** [comment]
Hi!

Thanks for helping. I attached four log files, but I cant find any mounts or unmounts in the time frame between March 05 and March 06...
[mounts.zip](https://github.com/lxc/lxd/files/1785315/mounts.zip)

**Comment by stgraber** [comment]
Hmm, yeah, nothing relevant in there, I'd have thought systemd would log the mount units showing up and going away, but I guess it doesn't...

Any chance you could do the same test again, so getting containers properly mounted first, then maybe setup a script that checks the mount table every 5min or so?

I'm interested to see if they all vanish at the same time, and when that happens. It may point us towards some cronjob or other scheduled activity on the machine that for some odd reason would cause the umount.
