### ISSUE TITLE
LXD snap fails to bring up lxd network at startup

### ISSUE THREAD

**Issue by eviweb** [lxc/lxd#4310]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04.4 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-116-generic
   * LXC version: 2.21
   * LXD version: 2.21 
   * Storage backend in use: ZFS
   * Snap Package Revision : 5866

# Issue description

At startup, the LXD network fails to start because iptables is not ready.
The command `sudo snap logs lxd` shows the following message :
```
2018-03-08T07:43:42Z lxd.daemon[8818]: err="Failed to run: iptables -w -t filter -I INPUT -i lxdbr0 -p udp --dport 67 -j ACCEPT -m comment --comment generated for LXD network lxdbr0: iptables: Resource temporarily unavailable." lvl=eror msg="Failed to bring up network" name=lxdbr0 t=2018-03-08T07:43:42+0000
```

# Steps to reproduce

As it randomly happens (almost each time on my computer), I don't know how to reproduce this issue.
This problem began with the migration to snap.

**Comment by stgraber** [comment]
Hmm, so that seems to be an iptables race condition, there are numerous report of that same error happening for other people on systems that run a number of iptables/xtables scripts...

Do you have anything else on your server which would be interacting with iptables/xtables?

**Comment by stgraber** [comment]
Sent a pullrequest which makes the most likely problematic iptables calls use our "TryRunCommand" wrapper, which will try a command up to 20 times in a 10s timespan, that should avoid any odd locking problem.

**Comment by eviweb** [comment]
Hi @stgraber,
thanks for your quick feedback.
To answer your previous question, I encounter this issue only on my PC for now but almost at every startup.
Docker is installed and also have its own iptables rules.
But I don't see anything else interacting with iptables, and the problem came only after the migration to snap LXD.
