### ISSUE TITLE
Can't run docker under lxc

### ISSUE THREAD

**Issue by galeenk** [lxc/lxd#4313]
hi again.
i found error again in my docker under lxc when i restart my container. before this my docker is running well.. 
error like this : 
ubuntu@git:~/go/src/gitlab.codigo.id/modin$ sudo docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
docker: Error response from daemon: open /sys/kernel/mm/hugepages: permission denied: unknown.
ERRO[0002] error waiting for container: context canceled 

LXD version 2.21
schema lxd : 
first container (stg-sencillo) : 
under first container (app-manager) - install docker 
under first container (data-service) - install docker 
under first container (git) - install docker

**Comment by stgraber** [comment]
Did you pass "-c security.nesting=true" when you created your container, or set the "security.nesting: true" config after the fact?

**Comment by stgraber** [comment]
I just confirmed that current docker-ce from upstream works fine in an Ubuntu 16.04 container with security.nesting set to true.

**Comment by galeenk** [comment]
yeah.. i did .. 
root@stg-sencillo:~# lxc config show git
architecture: x86_64
config:
  security.nesting: "true"
  security.privileged: "true"
  volatile.base_image: b5f3a547289fabf26d90250605dc3067f1863ee46c802f004aa97954cc852c33
  volatile.eth0.hwaddr: 00:16:3e:7b:62:d9
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
ephemeral: false
profiles:
- default
- docker
stateful: false
description: ""

**Comment by galeenk** [comment]
should i remove the old images from docker? then i docker run again?

**Comment by stgraber** [comment]
Shouldn't really matter, but you should remove the docker profile from that container and in fact delete that profile completely from your LXD host. The docker profile isn't needed anymore and in fact ends up being harmful most of the time.

**Comment by galeenk** [comment]
so then, i should've remove the docker profile in all my lxc ? ok.. i'll try

**Comment by stgraber** [comment]
Yes, remove it from all your containers and then delete the profile with `lxc profile delete docker`

**Comment by galeenk** [comment]
i've delete docker profile ... in host and the all container. but when i run docker run again to build images.. i get error like this
ubuntu@git:~/go/src/gitlab.codigo.id/modin$ sudo docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
Unable to find image 'gogs/gogs:latest' locally
latest: Pulling from gogs/gogs
550fe1bea624: Pull complete 
9db37eaa9a9a: Pull complete 
d05081f0e68d: Pull complete 
ca3093a77336: Pull complete 
f71141ec6f75: Pull complete 
86239bda9d7c: Pull complete 
21124162f12b: Pull complete 
376d3b92d247: Pull complete 
d8e85d675330: Pull complete 
251450f12e59: Pull complete 
9e0d8d956659: Pull complete 
Digest: sha256:a948476fcca8ec910d7720ad1108da25387b6218bec1f003fdaaabae1d1d9826
Status: Downloaded newer image for gogs/gogs:latest
docker: Error response from daemon: Could not check if docker-default AppArmor profile was loaded: open /sys/kernel/security/apparmor/profiles: permission denied.
ERRO[0029] error waiting for container: context canceled

**Comment by stgraber** [comment]
```
ubuntu@docker:~$ sudo docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
Unable to find image 'gogs/gogs:latest' locally
latest: Pulling from gogs/gogs
550fe1bea624: Pull complete 
9db37eaa9a9a: Pull complete 
d05081f0e68d: Pull complete 
ca3093a77336: Pull complete 
f71141ec6f75: Pull complete 
86239bda9d7c: Pull complete 
21124162f12b: Pull complete 
376d3b92d247: Pull complete 
d8e85d675330: Pull complete 
251450f12e59: Pull complete 
9e0d8d956659: Pull complete 
Digest: sha256:a948476fcca8ec910d7720ad1108da25387b6218bec1f003fdaaabae1d1d9826
Status: Downloaded newer image for gogs/gogs:latest
usermod: no changes
Mar  8 17:26:53 syslogd started: BusyBox v1.25.1
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
Mar  8 17:26:54 sshd[35]: Server listening on :: port 22.
Mar  8 17:26:54 sshd[35]: Server listening on 0.0.0.0 port 22.
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
error: exec: "/app/gogs/gogs": stat /app/gogs/gogs: permission denied
^CMar  8 17:27:12 sshd[35]: Received signal 15; terminating.
Mar  8 17:27:12 syslogd exiting
ubuntu@docker:~$ 
```

**Comment by stgraber** [comment]
So seems like it's kinda working here, except for not having the right binary or something.

**Comment by stgraber** [comment]
What kernel are you running?

**Comment by galeenk** [comment]
my host : 
root@stg-sencillo:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by stgraber** [comment]
Oh, so that's docker in a nested container right? stg-sencillo is a container itself I believe.

**Comment by stgraber** [comment]
You can do Docker inside of LXD, you cannot do Docker inside of LXD inside of LXD, AppArmor doesn't support more than one level of nesting, so that explains your error.

**Comment by stgraber** [comment]
It's something the apparmor developers are working on in the upstream kernel, but there's no clear ETA of when that limitation will be gone.

**Comment by galeenk** [comment]
yeah.. that's true.. so my real server run a lot of container .. and stg-sencillo is example .. so in stg-sencillo i create container again with name git .. and under git i run a docker... 

hmmm.. so what should i done?

**Comment by stgraber** [comment]
Running docker directly in stg-sencillo would work, running it inside a container inside of it will not and that will be true until some serious work is done in the Linux kernel, no known workaround.

**Comment by stgraber** [comment]
The issue is apparmor so in theory completely disabling apparmor would work too, but then security wouldn't be too great on your entire host, so that's probably not an option.

**Comment by galeenk** [comment]
that's ok .. i will try .. for my studying.. 

so, what should i do first? :)

**Comment by stgraber** [comment]
To turn apparmor off entirely, you'd need to reboot your physical host passing apparmor=0 on the kernel command line, that will turn it off entirely for everything which should then make those containers work.

But then you'll have the issue that root inside of your container will be able to trivially escape the container and reach the host, so as I said, really not recommended.

Anyway, we can keep chatting (but discuss.linuxcontainers.org would be a better place for that) but there's nothing to actually fix at the LXD level here. As soon as the kernel supports more than one level of AppArmor nesting, things will just start working immediately, so LXD is fine, kernel isn't.

**Comment by extraymond** [comment]
Little offtopic here.

Will docker snap works in lxd?
