### ISSUE TITLE
lxc stop hangs with hung task timeout

### ISSUE THREAD

**Issue by powersj** [lxc/lxd#4314]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Bionic
 * The output of "lxc info" or if that fails: http://paste.ubuntu.com/p/zX7PhSBD59/

# Issue description

After attempting to build libaio in a Bionic daily container I cannot stop or delete the container. dmesg shows a variety of hung tasks

# Steps to reproduce

Use the following script and watch for the the hang. At that point attempt to stop or delete the container.
http://paste.ubuntu.com/p/SxfgbxM8v7/

# Information to attach

 - [x] Any relevant kernel output (`dmesg`): http://paste.ubuntu.com/p/4GTtBtd5s3/
 - [x] Container log (`lxc info NAME --show-log`) http://paste.ubuntu.com/p/kS2K27JjTC/
 - [x] Container configuration (`lxc config show NAME --expanded`) http://paste.ubuntu.com/p/NRdP7sn328/
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log) http://paste.ubuntu.com/p/fbfx4nm8W6/
 - [x] Output of the client with --debug https://paste.ubuntu.com/p/3sX5PdJmVM/
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue) https://paste.ubuntu.com/p/ntKtXZYmph/

**Comment by brauner** [comment]
That's kernel bug. I guess `lxc stop <container-name> --force` doesn't do anything either, right?

**Comment by brauner** [comment]
What kernel  version is that?

**Comment by powersj** [comment]
Correct --force does not help, 4.15.0-10-generic

I'll file against linux-image on Ubuntu, I'll close.

**Comment by powersj** [comment]
FWIW here is my kernel bug: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1754584
