### ISSUE TITLE
Enhancement Request: Add options --rsync + --rsync-opts to all LXD commands, to optimize container copy commands

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#4319]
Both machines using fresh Ubuntu Artful install + LXD-2.21 installed via snap from scratch (no migration).

This container is ridiculously large, weighing in at 65G.

I thought it was just my imagination that local copies seemed to be running very slow in LXD, compared with LXC. They are running very slow, when tested.

In fact, data below shows copy of local containers is far slower than copy over network, which makes no sense, as the network connection runs far slower than local disk i/o.

Let me know if there's any way to speed up a local copy.

Thanks.
```
net11 # time nice -19 lxc copy net11-big-container net11-big-container-migrate

real    90m45.254s
user    0m0.354s
sys     0m0.146s

net10 # time lxc copy net11:net11-big-contaier net10-spare-big-container
    
real    18m56.629s
user    0m1.164s
sys     0m0.220s
```

**Comment by stgraber** [comment]
More details on the storage configuration would be useful. `lxc storage show` of all storage pools involved would be a good start

**Comment by davidfavor** [comment]
No storage pools. LXD init'ed as...
```
lxd init --auto --storage-backend=dir
```

**Comment by davidfavor** [comment]
The following command produces an error. I'm guessing because the backend is dir...
```
lxc storage show
```

**Comment by brauner** [comment]
Why do you run the first command with `-19` that would cause the scheduler to grant that process less time than others.

**Comment by brauner** [comment]
`lxc storage show` expects the name of a storage pool, e.g. `lxc storage show bla`

**Comment by davidfavor** [comment]
nice -19, part of script to eventually run.

Currently machine has no load.

**Comment by brauner** [comment]
Do you have `rsync.bwlimit` value set?

**Comment by davidfavor** [comment]
```
rsync.bwlimit -> not set
```
And if you read the issue carefully, you'll see the problem is rsync is faster than than local disk i/o, which is the problem.

The local copy of a container is what's taking a very long time.

**Comment by brauner** [comment]
`rsync.bwlimit` will locally and remotely limit.

**Comment by brauner** [comment]
`lxc storage show` of the source pool would be helpful. :)

**Comment by davidfavor** [comment]
```
net11 # lxc storage show default                                       
config:
  source: /var/snap/lxd/common/lxd/storage-pools/default
description: ""
name: default
driver: dir
used_by:
... ... ...
- /1.0/profiles/default
```

**Comment by stgraber** [comment]
So I'm actually not surprised that network is faster than local when using a directory backed storage pool. With the directory backend, a copy of a large container involves duplicating every single file on the filesystem, so that's obviously very I/O intensive and slow as everything must be read and written again.

When you do it over the network, the source machine will do the reads and the target machine will do the writes, so you don't have the reads and writes both causing an insane amount of disk seeks and completely destroying your I/O performance.

**Comment by stgraber** [comment]
Any of the storage backends other than dir would give you near instant local copies as they all support making an instant snapshot of an existing container, but there's no such thing for the dir backend, so you're looking at a full copy of every single file in the container, which combined with some amount of fragmentation can cause insane seeking of your drive, causing some rather terrible I/O performance.

Note that here I'm assuming that this is on spinning rust, SSDs won't have the seek issue and should in general behave better with the concurrent reads and writes.

**Comment by davidfavor** [comment]
Just ran another lxc copy without nice...
```
real	82m42.357s
user	0m0.060s
sys	0m0.029s
```
Same result. Local file i/o seems to take far longer than network i/o.

**Comment by davidfavor** [comment]
This is a problem. Every time I've ZFS + BTRFS database i/o is to slow for production machines.

And since CRIU has been abandoned, the only way to run massive i/o LXD containers + migrate them between machines is to do a local **lxc copy container new-container** then **lxc copy new-container remote:remote-container**.

I guess I'll have to deconstruct the **lxc copy new-container remote:remote-container** + modify it to actually do a copy from a live running container to a remote container.

Sigh... Not what I had in mind to do right now...

**Comment by stgraber** [comment]
Hmm, yeah, so if btrfs and zfs aren't an option because of the workloads involved (they both have some tricks you can do to better handle databases though), dir isn't an option because of the amount of data involved and how busy the copy makes the system, then you're left twi two other backends, lvm and ceph.

Ceph is unlikely to be an option here unless you already have a very fast ceph cluster setup somehow.

LVM while definitely not our preferred backend, should still be a nice improvement over the directory backend. As it lets you choose the filesystem (defaults to ext4), you shouldn't see any performance degradation because of the filesystem. And it supports snapshots which would make for an extremely quick "lxc snapshot container" or "lxc copy container new-container". Might be worth a try.

**Comment by davidfavor** [comment]
Actually **lxd snapshot** runs even slower for some reason, with realtime of 126+ minutes.

Maybe the solution is adding the ability to pass options to rsync. So in my case all site files live under /sites + database under /var/lib/mysql, so simple solution is passing --exclude to rsync, which drops container size to <2G in most cases.

Let me know if there's a way to pass rsync options to **lxc copy**.

Nothing shows about this in the man page, so I'd like to suggest a simple LXD enhancement of the options...

1) --rsync=path (path to rsync to use, which could also be a custom script)

2) --rsync-opts (set of options passed through to rsync)

Seems like this is the best work around right now.

I'll change the issue ticket title to an enhancement request.

**Comment by stgraber** [comment]
Wouldn't a cleaner approach for you be to use separate storage volumes for your database and websites?
That way they won't be included in a container snapshot and can be attached to multiple containers if needed.

Though that also means that copying the container to a remote host wouldn't bring those things with it but the same would be true with your suggested rsync options trick (which we're not likely to support as what tool we use for snapshot and transfer should be an internal implementation detail).

**Comment by stgraber** [comment]
It really feels like the problem you're having is because of the "dir" backend being completely non-optimized and so terribly slow.

I'd strongly recommend considering switching to another storage backend, especially if you rely on things like snapshots and copies.

**Comment by davidfavor** [comment]
1) Using separate volumes for database works out poorly, due to added complexity managing containers, especially (as you mention), migrating/managing multiple spare container instances.

2) Same with backups, as backup facilities must run at host level, sequentially for all containers. 

Backups for containers must run at host level. If backups run inside containers + many backups run simultaneously disk i/o thrash can take down machines.

3) The dir backend is the only option for high traffic sites, with custom code which involve database i/o for transactions. ZFS + BTRFS simply can't keep up.

Dirt simple solution seems to be adding these two options, for customized lxc commands.

**Comment by stgraber** [comment]
Why not use the LVM backend?

**Comment by stgraber** [comment]
That does support snapshot and fast copy of containers and uses ext4 or xfs as the actual filesystem.

**Comment by stgraber** [comment]
If you want to stick to your rsync hack, you could put a wrapper script for rsync in /usr/local/bin that does what you want behind LXD's back. I don't really see how that'll help you though. It'd let you skip some directories during snapshot/copy, but that means that restoring the snapshot would then delete all that data or copying the container to another host would lead to that data being missing.

**Comment by stgraber** [comment]
Closing as slow performance on snapshots and copies is something that we've always expected for the directory backend. This issue only confirms it but doesn't raise anything that we'd consider to be a bug in LXD.

Network transfers being faster than local snapshots and copies makes sense given that the reads and writes are then spread between two machines.

There are a number of ways to fix those performance issues by using another storage backend, either btrfs/zfs if an option or if you have to stay on ext4, then using LVM would still fix the snapshot/copy performance problems.

We don't plan on allowing excludes in snapshots/copy as that wouldn't be possible with all transfer mechanisms and as those are negotiated dynamically, having different set of files transferred depending on the transfer mechanism would just be terribly confusing. We'd prefer to have those cases where separating data from container makes sense to be using separate storage volumes instead.
