### ISSUE TITLE
Booleans in configuration stored as string after set operation

### ISSUE THREAD

**Issue by despens** [lxc/lxd#4320]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.13.0-1011
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: zfs

# Issue description

Booleans in configuration stored as string after `set` operation

# Steps to reproduce

```bash
$ sudo lxc config set template-ubuntu-14-04 boot.autostart false
$ sudo lxc config show template-ubuntu-16-04
architecture: x86_64
config:
  boot.autostart: "false"
...
```

The quotes around "false" suggest the value being stored as a string. How can it correctly be stored as a boolean?

**Comment by stgraber** [comment]
All config values are stored as strings, the type is only used to indicate how they'll be used internally and how they'll be validated on update.

**Comment by stgraber** [comment]
The documentation actually states:
"""Note that while a type is defined above as a convenience, all values are stored as strings and should be exported over the REST API as strings (which makes it possible to support any extra values without breaking backward compatibility)."""
