### ISSUE TITLE
lxd 2.21: disk quota ignored and weird disk quota exceeded when starting or setting quota

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#4321]
On ubuntu xenial 16.04.3, lxd 2.21, btrfs:

Info:
------

lxc info
config:
  core.https_address: '[::]:8443'
  core.proxy_http: http://10.154.8.58:3128
  core.proxy_https: https://10.154.8.58:3128
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.150.61.47:8443
  - 10.150.56.252:8443
  - 172.18.10.1:8443
  - 172.18.11.1:8443
  - 172.18.12.1:8443
  - 172.18.13.1:8443
  - 172.17.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
  certificate_fingerprint: 71261d282d756e652c08bb308c5dadf32f85e8807d229690347e0cda0ef1da2e
  driver: lxc
  driver_version: 2.1.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-116-generic
  server: lxd
  server_pid: 3678
  server_version: "2.21"
  storage: btrfs
  storage_version: "4.4"

Problem description
-----------------------------
disk quota ignored. Still see the host disk:

Steps to reproduce:
-------------------------

0. Before actions, to gather infos: 
- In the container:
root@elasticsearch:~# df -m
Filesystem     1M-blocks   Used Available Use% Mounted on
/dev/sdb          307200 147009    156662  49% /
none                   1      0         1   0% /dev
udev              100736      0    100736   0% /dev/tty

-> this is the host disk

root@elasticsearch:/# du -sm .
[ .. ]

54567	.
-> real used size of the container

1. Trying to set quota:
lxc config device set elasticsearch root size 100GB
error: The device doesn't exist

oops, no root disk.

2:  add root disk:
lxc config device add  elasticsearch root disk pool=default path=/ size=100GB
Device root added to elasticsearch

lxc config show elasticsearch

devices:
  root:
    path: /
    pool: default
    size: 100GB
    type: disk

ok

3. Stopping container
lxc stop elasticsearch

4. starting container: 
error: open /var/lib/lxd/containers/elasticsearch/backup.yaml: disk quota exceeded

huh?

5. trying to set quota, again
lxc config device set elasticsearch root size 80 Gb
error: open /var/lib/lxd/containers/elasticsearch/backup.yaml: disk quota exceeded

6. Trying again:
lxc config device set elasticsearch root size 80GB
 -> ok

lxc config show elasticsearch
devices:
  root:
    path: /
    pool: default
    size: 80GB
    type: disk

7. Trying again: lxc config device set elasticsearch root size 100GB
lxc config show elasticsearch
devices:
  root:
    path: /
    pool: default
    size: 100GB
    type: disk

8. Trying again: lxc config device set elasticsearch root size 80GB
ok

9. starting container
lxc start  elasticsearch
->ok

9. Looking inside container:
root@elasticsearch:~# df -m
Filesystem     1M-blocks   Used Available Use% Mounted on
/dev/sdb          307200 147100    156562  49% /
none                   1      0         1   0% /dev
udev              100736      0    100736   0% /dev/tty
tmpfs                  1      0         1   0% /dev/lxd
tmpfs                  1      0         1   0% /dev/.lxd-mounts

-> nothing changed

By the way, what  should  be set in /etc/fstab? Container's one  is empty.

Regards.

**Comment by stgraber** [comment]
Unlike zfs, btrfs doesn't create a mount table entry per subvolume, so while the quota is applied by LXD, it is not visible in the `df` output. That's due to how btrfs works internally and not something LXD can do anything about unfortunately.

To check on your quotas, you need to manually interact with the btrfs quotas using `btrfs qgroup`. Also note that as mentioned in our documentation, btrfs quotas aren't hierarchical and so it is trivial for any user in your container to bypass the quota, simply by creating a subvolume.

As for /etc/fstab, no content is required for your container to function.

**Comment by stgraber** [comment]
Oh and for the quota errors when applying it to the container, this comes straight from btrfs, so btrfs must have though you were running out of disk space within the rootfs of your container. This may have been because you're actually using more space than the quota (or right around the size of the quota) or it could be because of mis-balanced metadata/data at the btrfs layer, in which case you may want to run a `btrfs balance` operation on your storage pool.
