### ISSUE TITLE
Unable to have /dev/shm in the container after upgrade to lxd v2.21

### ISSUE THREAD

**Issue by jorgeventura** [lxc/lxd#4323]
# Required information

 * Distribution: gentoo
 * Distribution version: profile 17.0
  driver: lxc
  driver_version: 2.0.9
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.76-gentoo-r1
  server: lxd
  server_pid: 4398
  server_version: "2.21"
  storage: zfs
  storage_version: 0.7.5-r0-gentoo
 
# Issue description
I was running the lxd version 2.14. After upgrade to version 2.21 the container doesn't start with a problem in the device /dev/shm. I removed the device and the container started.

After that I tried to recreate the device with no success.
lxc config device add containerName /dev/shm disk source=/dev/shm path=/dev/shm

error: Failed to setup device: mkdir /var/lib/lxd/devices/containerName/disk./dev/shm.dev-shm: no such file or directory

Apparently the directory structure for devices changed and I created the directory manually.
mkdir -p /var/lib/lxd/devices/containerName/disk./dev

It works with the container running, the next restart doesn't work.

**Comment by brauner** [comment]
Ah yeah, this was fixed by efa955a4477b94f197cd5f0e6664306adbcb22d2 in master. @stgraber did you release a new tarball with that fix? We might need to do this since we have recently pushed a few guys to upgrade to 2.21?

**Comment by stgraber** [comment]
No, we don't normally issue point releases for feature releases, with the exception of security fixes.

This particular fix was cherry-picked into the Ubuntu and Snap packages at least, so I'd recommend you ask your distribution maintainer (looks like Gentoo in this case) to cherry-pick the fix @brauner mentioned.

**Comment by brauner** [comment]
@stgraber, cool.

**Comment by jorgeventura** [comment]
It was my fault!!!
Never mind.
There is a script /etc/init.d/devfs that was starting with a keyword -lxc. I removed the keyword and everything is working now.
