### ISSUE TITLE
Unable to find the ZFS pool image file.

### ISSUE THREAD

**Issue by HW-Siew** [lxc/lxd#4324]
# Required information

 * Distribution:  ubuntu 16.04
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: linux 4.13.0-1011-gcp
   * LXC version: 2.1.1
   * LXD version: 2.21
   * Storage backend in use: zfs

# Issue description

I installed Lxd via snap in a fresh machine. I am trying to grow my zfs pool using the method stated in doc (listed below). However, I am not able to find any file list under  /var/snap/lxd/common/lxd/disks.  

```
truncate -s +20G /var/snap/lxd/common/lxd/disks/default.img
zpool set autoexpand=on default
zpool online -e default /var/snap/lxd/common/lxd/disks/default.img
zpool set autoexpand=off default
```
'ls -la' shows the result below
```
sudo ls -la  /var/snap/lxd/common/lxd/disks
total 8
drwx------  2 root root 4096 Mar 13 00:24 .
drwx--x--x 14 root root 4096 Mar 13 00:43 ..
```

# Steps to reproduce

 1. sudo snap install lxd
 2. sudo lxd.migrate --yes
 3. sudo lxd init
 4. initial lxd using block device '/dev/sdb'
 5. list any file under  /var/snap/lxd/common/lxd/disks

**Comment by stgraber** [comment]
You're using a real block device, in this case `/dev/sdb`, so those instructions don't apply to you.

If this is a virtual machine, you'd have to grow your attached disk, reboot the VM and then set autoexpand=on on the pool. If this is a physical hard drive, then well, there's not much you can do as you can't physically grow a disk :)
