### ISSUE TITLE
LXD Not Initializing

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#4329]
# Required information

 * Distribution: Kali GNU/Linux Rolling
 * Distribution version: 2018
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 3.0.0.beta3
   * LXD version: 3.0.0.beta3
   * Storage backend in use: n/a

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Installing LXD from source until machine setup "echo "root:1000000:65536" | sudo tee -a /etc/subuid /etc/subgid" 
2. I copied all the contents of "$GOPATH/bin" to "/bin/" directory of the host. In order to run lxd/lxc commands directly. 
3. Run "sudo -E /bin/lxd --group sudo" and get an **error**:

**Error**: "WARN[03-13|23:57:58] CGroup memory swap accounting is disabled, swap limits will be ignored. error: failed to create raft factory: failed to create bolt store for raft logs: timeout" 

Note: I get the same error when i run: "sudo -E $GOPATH/bin/lxd --group sudo". 

Also when i try to run "sudo lxd init". it does nothing and just hangs.  

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
That error usually occurs when you have another copy of LXD running on the system.
What does `ps fauxww` show you?

**Comment by elbrinke** [comment]
Hi, I do see the older version as well which run commands such as: lxc-attach

**Comment by elbrinke** [comment]
Command: ps fauxww | grep lxc

Output:
root      3246  0.0  0.0  12840  1064 pts/0    S+   00:56   0:00          \_ grep lxc

**Comment by elbrinke** [comment]
I want to run the new LXC/LXD as a service at boot. How would i do that?

**Comment by elbrinke** [comment]
It stopped showing that error.... I just now need to run lxd as a service or daemon, so i don't always have to start it manually?

**Comment by stgraber** [comment]
Something like:

 - https://github.com/lxc/lxd-pkg-ubuntu/blob/dpm-bionic/debian/lxd.lxd-containers.service
 - https://github.com/lxc/lxd-pkg-ubuntu/blob/dpm-bionic/debian/lxd.service
 - https://github.com/lxc/lxd-pkg-ubuntu/blob/dpm-bionic/debian/lxd.socket

But those assume quite a few things that are unlikely to be true with an hand built daemon, so you'll need to do something which makes sense for your init system.

If all you want is to run the latest beta, you may be much better off just using the beta snap:
```
apt install snapd
snap install --beta lxd
```

**Comment by stgraber** [comment]
Closing as there doesn't appear to actually be a LXD issue here.

The error was far more confusing than it needed to be but I've pushed a fix for this and it's now in master.

**Comment by elbrinke** [comment]
Hi, when i run the command: snap install --beta lxd
I get: error: cannot communicate with server: Post http://localhost/v2/snaps/lxd: dial unix /run/snapd.socket: connect: no such file or directory

**Comment by stgraber** [comment]
@elbrinke that's odd, it's as if the snapd service wasn't running on your system. What does `systemctl status snapd.service` and `systemctl status snapd.socket` show?
