### ISSUE TITLE
LXD snap does not bring up network on Opensuse

### ISSUE THREAD

**Issue by bzeller** [lxc/lxd#4340]
# Required information

 * Distribution: Opensuse
 * Distribution version: Tumbleweed
 * The output of "lxc info":
```
zbenjamin@linux-gaqj:~> lxd.lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFTTCCAzWgAwIBAgIRAMWbwmB79BO6kYlG61YVI/swDQYJKoZIhvcNAQELBQAw
    ODEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEYMBYGA1UEAwwPcm9vdEBs
    aW51eC1nYXFqMB4XDTE4MDMxOTE0MTEzMloXDTI4MDMxNjE0MTEzMlowODEcMBoG
    A1UEChMTbGludXhjb250YWluZXJzLm9yZzEYMBYGA1UEAwwPcm9vdEBsaW51eC1n
    YXFqMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAzw3VYxxk5mMuSCjQ
    jH1cqSuBeh11eCjDJZihwR5TvCJalo1vOpcu0A8VhFk39xt/FKk48VGIhaBtJVxz
    JOuyQ3jR8gv2s9sa0Bm787sYX9coDZdCaeciNXOGye+k/jDihrqzz/ptcB1kYdEK
    vOlil7Xy6JegjJC7UPYtXXukyAbYaMO0Zmnf6RVgGX1Pui1ubR1X97wKvuY/u+oa
    lZLrugWJoQyAbSy2IACiy5cWin3tdCyyXoVnUq1yJhbfe5kFjBF7z06jRRdZNnjS
    KsMN4fbPLe0e/n4UZpHT55squp3recalUyVfRnMLICRPzGZWNlSwUpwfZiZ3JEm2
    VXQ6BCz6LtpB8QBdAOjrmT/x020MHyX6k/H143LIcFAGD0RzkNqj3zWBfl1A8X1A
    x/8PRTON0FzJl+tiuQfGAIzS4M7f/TjMZQrPeZQJHuAuesYYKOfgza3hdNCWF9QH
    0cSqv6uD1741y9Xx1r6xUUz/pU7H354QeWx+0nJK5g/Rd/bccc6pbaqzfQaB58qW
    u6lEXuAbnVEPR1ubNJ30UomqXni99gHBNSatF854TeKhNQIq9IMpiTPg2WXvQr/u
    VrVqfBuZNKbhPzoQ8GuwrKdalmt/IRH+ikWZdy00ua6RR1AdN/Ob9SNUEuwVHVzZ
    czsVaG7m6PojWLrCqd+kMnzG4H8CAwEAAaNSMFAwDgYDVR0PAQH/BAQDAgWgMBMG
    A1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwGwYDVR0RBBQwEoIKbGlu
    dXgtZ2FxaocECgACDzANBgkqhkiG9w0BAQsFAAOCAgEAr3CPjr+5AWBVC+6pacSV
    sALn6jvn60xah0bJyTKVCx7zHrK7MNj7nMB265ovwauAMSp4/rp7CE1JuZ4ch7zH
    Gpye1SBAzXySORJbEJ30MDqXIPN2ZNnBxa/+5ig95PIculJYO4ohN4g0gFnYU6kI
    /l3VOAHTuG/mPx5hbuvVFEVdd6ucIbyeIKdPx6SzO1UGSxFpfPI2S2KloWnTBqXA
    Mnozho7p0KubIQUVAvM5PyWi4R/X2q2/CkrNcQkKu9aWTRZetRlcIdujw2SgC4qA
    nI453rQw2oLCms1HORjKGuHdKxGgn8JaZHUMOT5X9xClw5yl+RBaGMCFXabR3D5v
    fhUGv1LsQnhdrs8z7of7saLhVp1x0KT0kf3V6PXfsw2jdYbMKkVi7bbC0hErvZTR
    QpmOkWMcyRSgZa5QJEICF7BEn837UH8EsuyMnAAl3Iv4BAcx2MD1uzo6ArCN6bpa
    MLzg4/XDEpOZ9FagJ+OFSPSl00LyrW/OUryrAE3eDS+UyBz6UUxovPd8vI6K9ZhO
    1VI53rlXX0fol2GqUW0y3BubG6uaeR4YspzOWxnsZy1XRQey7q9i3fqWH/swOc8+
    bxcAPG+FfvtjAarfxtfNQ0Ys+lq63PFxJRfw1X5WRUDZxSdPJVxmz0cmM2oDCLew
    2vWT2yZ8Qaykr3Zg4VNbH9s=
    -----END CERTIFICATE-----
  certificate_fingerprint: f75ae81dad8b8241639fe09640f68ff07a833abc84ad3bdb57b25d0f4e770859
  driver: lxc
  driver_version: 2.1.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.9-1-default
  server: lxd
  server_pid: 2005
  server_version: "2.21"
  storage: dir
  storage_version: "1"
```

# Issue description

I was installing LXD from the snap store, creating and starting a container works but network does not come up. This is a fresh install of Tumbleweed.

# Steps to reproduce

 1. Install snapd on Opensuse Tumbleweed
 2. Install lxd via "snap install"
 3. Create a container: lxd.lxd launch ubuntu:z test
 4. Network fails to come up

Apparmor seems to block that , so currently the only workaround is to run all containers unconfined:
# Information to attach
 - [ ] Any relevant kernel output (`dmesg`)
```
type=AVC msg=audit(1521468900.083:152): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4014 comm="dhclient" family="packet" sock_type="raw" protocol=768
type=AVC msg=audit(1521468900.459:153): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4068 comm="ifconfig" family="inet" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468900.459:154): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4068 comm="ifconfig" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468900.459:155): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4068 comm="ifconfig" family="inet" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468900.459:156): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4068 comm="ifconfig" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.219:157): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4096 comm="snapd" family="inet" sock_type="stream" protocol=6
type=AVC msg=audit(1521468901.219:158): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4096 comm="snapd" family="inet6" sock_type="stream" protocol=6
type=AVC msg=audit(1521468901.219:159): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4096 comm="snapd" family="inet6" sock_type="stream" protocol=6
type=AVC msg=audit(1521468901.235:160): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4094 comm="rsyslogd" family="inet" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.235:161): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4104 comm="systemd-resolve" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.239:162): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4104 comm="systemd-resolve" family="inet" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.239:163): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4104 comm="systemd-resolve" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.271:164): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4119 comm="systemd-resolve" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.275:165): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4119 comm="systemd-resolve" family="inet" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.275:166): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4119 comm="systemd-resolve" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.291:167): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4107 comm="lxd" family="inet" sock_type="stream" protocol=6
type=AVC msg=audit(1521468901.291:168): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4107 comm="lxd" family="inet6" sock_type="stream" protocol=6
type=AVC msg=audit(1521468901.291:169): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4107 comm="lxd" family="inet6" sock_type="stream" protocol=6
type=AVC msg=audit(1521468901.303:170): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4126 comm="systemd-resolve" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.303:171): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4126 comm="systemd-resolve" family="inet" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.303:172): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4126 comm="systemd-resolve" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.327:173): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4129 comm="systemd-resolve" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.331:174): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4129 comm="systemd-resolve" family="inet" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.331:175): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4129 comm="systemd-resolve" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.355:176): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4132 comm="systemd-resolve" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.355:177): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4132 comm="systemd-resolve" family="inet" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.355:178): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4132 comm="systemd-resolve" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.383:179): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4135 comm="sshd" family="inet6" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.383:180): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4135 comm="sshd" family="inet" sock_type="dgram" protocol=0
type=AVC msg=audit(1521468901.383:181): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4135 comm="sshd" family="inet6" sock_type="stream" protocol=6
type=AVC msg=audit(1521468901.383:182): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4135 comm="sshd" family="inet" sock_type="stream" protocol=6
type=AVC msg=audit(1521468901.387:183): apparmor="DENIED" operation="create" namespace="root//lxd-crazy_<var-snap-lxd-common-lxd>" profile="unconfined" pid=4139 comm="iscsi-iname" family="inet" sock_type="dgram" protocol=0
```

**Comment by stgraber** [comment]
I'll take a look on our tumbleweed test system, those apparmor failures are likely the source of the problem, but it's weird as the LXD generated profile should allow all of those...

What do you have in /var/snap/lxd/common/lxd/security/apparmor/profiles/lxd-crazy?

**Comment by bzeller** [comment]
`#include <tunables/global>
profile "lxd-crazy_</var/snap/lxd/common/lxd>" flags=(attach_disconnected,mediate_deleted) {
  ### Base profile
  capability,
  dbus,
  file,
  network,
  umount,

  # Allow us to receive signals from anywhere.
  signal (receive),

  # Allow us to send signals to ourselves
  signal peer=@{profile_name},

  # Allow other processes to read our /proc entries, futexes, perf tracing and
  # kcmp for now (they will need 'read' in the first place). Administrators can
  # override with:
  #   deny ptrace (readby) ...
  ptrace (readby),

  # Allow other processes to trace us by default (they will need 'trace' in
  # the first place). Administrators can override with:
  #   deny ptrace (tracedby) ...
  ptrace (tracedby),

  # Allow us to ptrace ourselves
  ptrace peer=@{profile_name},

  # ignore DENIED message on / remount
  deny mount options=(ro, remount) -> /,
  deny mount options=(ro, remount, silent) -> /,

  # allow tmpfs mounts everywhere
  mount fstype=tmpfs,

  # allow hugetlbfs mounts everywhere
  mount fstype=hugetlbfs,

  # allow mqueue mounts everywhere
  mount fstype=mqueue,

  # allow fuse mounts everywhere
  mount fstype=fuse,
  mount fstype=fuse.*,

  # deny access under /proc/bus to avoid e.g. messing with pci devices directly
  deny @{PROC}/bus/** wklx,

  # deny writes in /proc/sys/fs but allow binfmt_misc to be mounted
  mount fstype=binfmt_misc -> /proc/sys/fs/binfmt_misc/,
  deny @{PROC}/sys/fs/** wklx,

  # allow efivars to be mounted, writing to it will be blocked though
  mount fstype=efivarfs -> /sys/firmware/efi/efivars/,

  # block some other dangerous paths
  deny @{PROC}/kcore rwklx,
  deny @{PROC}/sysrq-trigger rwklx,

  # deny writes in /sys except for /sys/fs/cgroup, also allow
  # fusectl, securityfs and debugfs to be mounted there (read-only)
  mount fstype=fusectl -> /sys/fs/fuse/connections/,
  mount fstype=securityfs -> /sys/kernel/security/,
  mount fstype=debugfs -> /sys/kernel/debug/,
  deny mount fstype=debugfs -> /var/lib/ureadahead/debugfs/,
  mount fstype=proc -> /proc/,
  mount fstype=sysfs -> /sys/,
  mount options=(rw, nosuid, nodev, noexec, remount) -> /sys/,
  deny /sys/firmware/efi/efivars/** rwklx,
  # note, /sys/kernel/security/** handled below
  mount options=(move) /sys/fs/cgroup/cgmanager/ -> /sys/fs/cgroup/cgmanager.lower/,
  mount options=(ro, nosuid, nodev, noexec, remount, strictatime) -> /sys/fs/cgroup/,

  # deny reads from debugfs
  deny /sys/kernel/debug/{,**} rwklx,

  # allow paths to be made slave, shared, private or unbindable
  # FIXME: This currently doesn't work due to the apparmor parser treating those as allowing all mounts.
#  mount options=(rw,make-slave) -> **,
#  mount options=(rw,make-rslave) -> **,
#  mount options=(rw,make-shared) -> **,
#  mount options=(rw,make-rshared) -> **,
#  mount options=(rw,make-private) -> **,
#  mount options=(rw,make-rprivate) -> **,
#  mount options=(rw,make-unbindable) -> **,
#  mount options=(rw,make-runbindable) -> **,

  # allow bind-mounts of anything except /proc, /sys and /dev
  mount options=(rw,bind) /[^spd]*{,/**},
  mount options=(rw,bind) /d[^e]*{,/**},
  mount options=(rw,bind) /de[^v]*{,/**},
  mount options=(rw,bind) /dev/.[^l]*{,/**},
  mount options=(rw,bind) /dev/.l[^x]*{,/**},
  mount options=(rw,bind) /dev/.lx[^c]*{,/**},
  mount options=(rw,bind) /dev/.lxc?*{,/**},
  mount options=(rw,bind) /dev/[^.]*{,/**},
  mount options=(rw,bind) /dev?*{,/**},
  mount options=(rw,bind) /p[^r]*{,/**},
  mount options=(rw,bind) /pr[^o]*{,/**},
  mount options=(rw,bind) /pro[^c]*{,/**},
  mount options=(rw,bind) /proc?*{,/**},
  mount options=(rw,bind) /s[^y]*{,/**},
  mount options=(rw,bind) /sy[^s]*{,/**},
  mount options=(rw,bind) /sys?*{,/**},

  # allow moving mounts except for /proc, /sys and /dev
  mount options=(rw,move) /[^spd]*{,/**},
  mount options=(rw,move) /d[^e]*{,/**},
  mount options=(rw,move) /de[^v]*{,/**},
  mount options=(rw,move) /dev/.[^l]*{,/**},
  mount options=(rw,move) /dev/.l[^x]*{,/**},
  mount options=(rw,move) /dev/.lx[^c]*{,/**},
  mount options=(rw,move) /dev/.lxc?*{,/**},
  mount options=(rw,move) /dev/[^.]*{,/**},
  mount options=(rw,move) /dev?*{,/**},
  mount options=(rw,move) /p[^r]*{,/**},
  mount options=(rw,move) /pr[^o]*{,/**},
  mount options=(rw,move) /pro[^c]*{,/**},
  mount options=(rw,move) /proc?*{,/**},
  mount options=(rw,move) /s[^y]*{,/**},
  mount options=(rw,move) /sy[^s]*{,/**},
  mount options=(rw,move) /sys?*{,/**},

  # generated by: lxc-generate-aa-rules.py container-rules.base
  deny /proc/sys/[^kn]*{,/**} wklx,
  deny /proc/sys/k[^e]*{,/**} wklx,
  deny /proc/sys/ke[^r]*{,/**} wklx,
  deny /proc/sys/ker[^n]*{,/**} wklx,
  deny /proc/sys/kern[^e]*{,/**} wklx,
  deny /proc/sys/kerne[^l]*{,/**} wklx,
  deny /proc/sys/kernel/[^smhd]*{,/**} wklx,
  deny /proc/sys/kernel/d[^o]*{,/**} wklx,
  deny /proc/sys/kernel/do[^m]*{,/**} wklx,
  deny /proc/sys/kernel/dom[^a]*{,/**} wklx,
  deny /proc/sys/kernel/doma[^i]*{,/**} wklx,
  deny /proc/sys/kernel/domai[^n]*{,/**} wklx,
  deny /proc/sys/kernel/domain[^n]*{,/**} wklx,
  deny /proc/sys/kernel/domainn[^a]*{,/**} wklx,
  deny /proc/sys/kernel/domainna[^m]*{,/**} wklx,
  deny /proc/sys/kernel/domainnam[^e]*{,/**} wklx,
  deny /proc/sys/kernel/domainname?*{,/**} wklx,
  deny /proc/sys/kernel/h[^o]*{,/**} wklx,
  deny /proc/sys/kernel/ho[^s]*{,/**} wklx,
  deny /proc/sys/kernel/hos[^t]*{,/**} wklx,
  deny /proc/sys/kernel/host[^n]*{,/**} wklx,
  deny /proc/sys/kernel/hostn[^a]*{,/**} wklx,
  deny /proc/sys/kernel/hostna[^m]*{,/**} wklx,
  deny /proc/sys/kernel/hostnam[^e]*{,/**} wklx,
  deny /proc/sys/kernel/hostname?*{,/**} wklx,
  deny /proc/sys/kernel/m[^s]*{,/**} wklx,
  deny /proc/sys/kernel/ms[^g]*{,/**} wklx,
  deny /proc/sys/kernel/msg*/** wklx,
  deny /proc/sys/kernel/s[^he]*{,/**} wklx,
  deny /proc/sys/kernel/se[^m]*{,/**} wklx,
  deny /proc/sys/kernel/sem*/** wklx,
  deny /proc/sys/kernel/sh[^m]*{,/**} wklx,
  deny /proc/sys/kernel/shm*/** wklx,
  deny /proc/sys/kernel?*{,/**} wklx,
  deny /proc/sys/n[^e]*{,/**} wklx,
  deny /proc/sys/ne[^t]*{,/**} wklx,
  deny /proc/sys/net?*{,/**} wklx,
  deny /sys/[^fdck]*{,/**} wklx,
  deny /sys/c[^l]*{,/**} wklx,
  deny /sys/cl[^a]*{,/**} wklx,
  deny /sys/cla[^s]*{,/**} wklx,
  deny /sys/clas[^s]*{,/**} wklx,
  deny /sys/class/[^n]*{,/**} wklx,
  deny /sys/class/n[^e]*{,/**} wklx,
  deny /sys/class/ne[^t]*{,/**} wklx,
  deny /sys/class/net?*{,/**} wklx,
  deny /sys/class?*{,/**} wklx,
  deny /sys/d[^e]*{,/**} wklx,
  deny /sys/de[^v]*{,/**} wklx,
  deny /sys/dev[^i]*{,/**} wklx,
  deny /sys/devi[^c]*{,/**} wklx,
  deny /sys/devic[^e]*{,/**} wklx,
  deny /sys/device[^s]*{,/**} wklx,
  deny /sys/devices/[^v]*{,/**} wklx,
  deny /sys/devices/v[^i]*{,/**} wklx,
  deny /sys/devices/vi[^r]*{,/**} wklx,
  deny /sys/devices/vir[^t]*{,/**} wklx,
  deny /sys/devices/virt[^u]*{,/**} wklx,
  deny /sys/devices/virtu[^a]*{,/**} wklx,
  deny /sys/devices/virtua[^l]*{,/**} wklx,
  deny /sys/devices/virtual/[^n]*{,/**} wklx,
  deny /sys/devices/virtual/n[^e]*{,/**} wklx,
  deny /sys/devices/virtual/ne[^t]*{,/**} wklx,
  deny /sys/devices/virtual/net?*{,/**} wklx,
  deny /sys/devices/virtual?*{,/**} wklx,
  deny /sys/devices?*{,/**} wklx,
  deny /sys/f[^s]*{,/**} wklx,
  deny /sys/fs/[^c]*{,/**} wklx,
  deny /sys/fs/c[^g]*{,/**} wklx,
  deny /sys/fs/cg[^r]*{,/**} wklx,
  deny /sys/fs/cgr[^o]*{,/**} wklx,
  deny /sys/fs/cgro[^u]*{,/**} wklx,
  deny /sys/fs/cgrou[^p]*{,/**} wklx,
  deny /sys/fs/cgroup?*{,/**} wklx,
  deny /sys/fs?*{,/**} wklx,

  ### Feature: unix
  # Allow receive via unix sockets from anywhere
  unix (receive),

  # Allow all unix in the container
  unix peer=(label=@{profile_name}),

  ### Feature: cgroup namespace
  mount fstype=cgroup -> /sys/fs/cgroup/**,

  ### Feature: apparmor stacking
  ### Configuration: apparmor profile loading (in namespace)
  deny /sys/k[^e]*{,/**} wklx,
  deny /sys/ke[^r]*{,/**} wklx,
  deny /sys/ker[^n]*{,/**} wklx,
  deny /sys/kern[^e]*{,/**} wklx,
  deny /sys/kerne[^l]*{,/**} wklx,
  deny /sys/kernel/[^s]*{,/**} wklx,
  deny /sys/kernel/s[^e]*{,/**} wklx,
  deny /sys/kernel/se[^c]*{,/**} wklx,
  deny /sys/kernel/sec[^u]*{,/**} wklx,
  deny /sys/kernel/secu[^r]*{,/**} wklx,
  deny /sys/kernel/secur[^i]*{,/**} wklx,
  deny /sys/kernel/securi[^t]*{,/**} wklx,
  deny /sys/kernel/securit[^y]*{,/**} wklx,
  deny /sys/kernel/security/[^a]*{,/**} wklx,
  deny /sys/kernel/security/a[^p]*{,/**} wklx,
  deny /sys/kernel/security/ap[^p]*{,/**} wklx,
  deny /sys/kernel/security/app[^a]*{,/**} wklx,
  deny /sys/kernel/security/appa[^r]*{,/**} wklx,
  deny /sys/kernel/security/appar[^m]*{,/**} wklx,
  deny /sys/kernel/security/apparm[^o]*{,/**} wklx,
  deny /sys/kernel/security/apparmo[^r]*{,/**} wklx,
  deny /sys/kernel/security/apparmor?*{,/**} wklx,
  deny /sys/kernel/security?*{,/**} wklx,
  deny /sys/kernel?*{,/**} wklx,
  change_profile -> ":lxd-crazy_<var-snap-lxd-common-lxd>:*",
  change_profile -> ":lxd-crazy_<var-snap-lxd-common-lxd>://*",

  ### Configuration: unprivileged containers
  pivot_root,

  mount options=(rw,make-slave) -> **,
  mount options=(rw,make-rslave) -> **,
  mount options=(rw,make-shared) -> **,
  mount options=(rw,make-rshared) -> **,
  mount options=(rw,make-private) -> **,
  mount options=(rw,make-rprivate) -> **,
  mount options=(rw,make-unbindable) -> **,
  mount options=(rw,make-runbindable) -> **,

  mount options=(rw,bind),
  mount options=(rw,rbind),
}
`

**Comment by bzeller** [comment]
What is also intersting is I see exactly the same apparmor errors with a local build of LXD on Tumbleweed and the upcoming Leap15

**Comment by stgraber** [comment]
Yeah, it's almost certainly some weirdness with the in-kernel apparmor support...
Our profile clearly allows all network operations, yet they somehow get blocked, so that'd pretty odd.

**Comment by stgraber** [comment]
I've pinged John Johansen about this issue, hopefully he can tell us if it's our profile needing some new bits for recent kernels or if it's some kind of kernel issue with the OpenSUSE kernel.

**Comment by bzeller** [comment]
What is the minimal kernel that LXD should work with, without extra apparmor patches?

**Comment by stgraber** [comment]
3.13

**Comment by bzeller** [comment]
Oh thats pretty old, that means even the current Leap kernel (Linux version 4.4.114-42-default) should work

**Comment by stgraber** [comment]
Yes, LXD and apparmor have feature detection and will automatically use the features available.
That's why the most likely issue here is a kernel bug.

**Comment by stgraber** [comment]
opensuse 42.3 does get you working networking, at least that's what jenkins tells me

**Comment by stgraber** [comment]
Just check and tumbleweed is the only distro we test which shows this problem.

**Comment by bzeller** [comment]
Interesting, did not try 42.3. However I worked on some rpm packaging for Leap 15 and Tumbleweed and I get the same error on both. I tried to run the Snap version of LXD to test if it was related to packaging and ran into the same apparmor issues. Could that be another installed package thats causing it? 

I will try on Leap 15 at least because I have a VM available

**Comment by bzeller** [comment]
Ok, so the LXD snap on Leap 15 also fails to bring up network.

**Comment by jrjohansen** [comment]
suse has been carrying a few out of tree kernel patches for apparmor, I am checking if there is an issue with these.

Another potential issue is with rule downgrades during policy compile, where eg. unix network rules get downgraded to a generic network rule because the kernel doesn't support fine grained network mediation. There was a recent bug around this as well, I check and make sure suse has the patch for that.

**Comment by stgraber** [comment]
I'm closing the LXD issue for now. Comparing with what we get on Ubuntu 4.15, the generated profile by LXD is identical, so it's not our feature detection code or something misfiring on SUSE, instead it looks like it may be a problem with the SUSE kernel or the apparmor parser which is causing issues with recent kernel implementation of apparmor (though likely distro specific as Ubuntu and Debian don't see that problem).

**Comment by stgraber** [comment]
(The issue being closed doesn't mean that the discussion is, it just means we don't have anything actionable at the LXD level. Feel free to keep commenting, we'll be reading.)

**Comment by bzeller** [comment]
FWIW, i installed a clean Leap 42.3 with updates and I was able to bring up network with the snappy version and my manually rpm packaged version of LXD. But not on Leap15 nor Tumbleweed, so the kernel there might really be the issue.

**Comment by bzeller** [comment]
I created a bug in the openSUSE apparmor bugtracker as well: https://bugzilla.opensuse.org/show_bug.cgi?id=1085996
