### ISSUE TITLE
[Feature request] lxc run

### ISSUE THREAD

**Issue by 19wolf** [lxc/lxd#4346]
I think some command like `lxc run $image $command` would be useful. The idea is that it would be equivalent to `lxc launch $image && lxc exec $command`, where command if unset would default to `bash`.

**Comment by stgraber** [comment]
Hmm, I'm not convinced it's worth the effort, maintenance cost and potential user confusion to introduce a separate command for that. It'd also be very difficult to adequately mix the options of launch and exec in the same tool without eventually getting into argument conflicts.

So I'm going to reject that feature request, though the approach discussed in #3233 would let you do that locally if it truly makes a huge difference for you.
