### ISSUE TITLE
process, cpu and memory information in containers

### ISSUE THREAD

**Issue by Cistoge** [lxc/lxd#4348]
Hello,

I do not know if this is distribution-specific or if I just have to change something in the configuration, but after an OS upgrade from Debian 8 to Debian 9, when I enter an unprivileged  container, ps shows process startup times in the future and /proc/cpuinfo and /proc/meminfo show all CPUs and the whole amount of memory, though I am using lxcfs. Before the OS upgrade, ps showed correct startup times and cpuinfo and meminfo showed only the amount resources that was reserved for that container.

Regards
  Christoph

**Comment by Cistoge** [comment]
I was not precise enough, ps shows incorrect startup times only for processes started at container boot, other processes are shown correctly.

**Comment by stgraber** [comment]
`cat /proc/self/mountinfo` inside the container?

**Comment by stgraber** [comment]
And how was LXD installed? is that the snap?

**Comment by Cistoge** [comment]
mountinfo shows the following:

134 86 0:41 / /dev rw,relatime - tmpfs none rw,size=492k,mode=755,uid=100000,gid=100000
135 86 0:43 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
136 137 0:43 /sys/net /proc/sys/net rw,nosuid,nodev,noexec,relatime - proc proc rw
137 135 0:43 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
138 135 0:43 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
139 86 0:44 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
140 139 0:44 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs rw
141 140 0:44 / /sys/devices/virtual/net rw,relatime - sysfs sysfs rw
142 141 0:44 /devices/virtual/net /sys/devices/virtual/net rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
143 140 0:38 / /sys/fs/fuse/connections rw,relatime master:32 - fusectl fusectl rw
144 134 0:6 /console /dev/console rw,nosuid,relatime master:3 - devtmpfs udev rw,size=8203628k,nr_inodes=2050907,mode=755
145 134 0:6 /full /dev/full rw,nosuid,relatime master:3 - devtmpfs udev rw,size=8203628k,nr_inodes=2050907,mode=755                                                                                                                          
146 134 0:6 /null /dev/null rw,nosuid,relatime master:3 - devtmpfs udev rw,size=8203628k,nr_inodes=2050907,mode=755                                                                                                                          
147 134 0:6 /random /dev/random rw,nosuid,relatime master:3 - devtmpfs udev rw,size=8203628k,nr_inodes=2050907,mode=755                                                                                                                      
148 134 0:6 /tty /dev/tty rw,nosuid,relatime master:3 - devtmpfs udev rw,size=8203628k,nr_inodes=2050907,mode=755                                                                                                                            
149 134 0:6 /urandom /dev/urandom rw,nosuid,relatime master:3 - devtmpfs udev rw,size=8203628k,nr_inodes=2050907,mode=755                                                                                                                    
150 134 0:6 /zero /dev/zero rw,nosuid,relatime master:3 - devtmpfs udev rw,size=8203628k,nr_inodes=2050907,mode=755                                                                                                                          
151 135 0:37 /proc/cpuinfo /proc/cpuinfo rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                           
152 135 0:37 /proc/diskstats /proc/diskstats rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                       
153 135 0:37 /proc/meminfo /proc/meminfo rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                           
154 135 0:37 /proc/stat /proc/stat rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                                 
155 135 0:37 /proc/swaps /proc/swaps rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                               
156 135 0:37 /proc/uptime /proc/uptime rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                             
157 151 0:37 /proc/cpuinfo /proc/cpuinfo rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                           
158 152 0:37 /proc/diskstats /proc/diskstats rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                       
159 153 0:37 /proc/meminfo /proc/meminfo rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                           
160 154 0:37 /proc/stat /proc/stat rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                                 
161 155 0:37 /proc/swaps /proc/swaps rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                               
162 156 0:37 /proc/uptime /proc/uptime rw,nosuid,nodev,relatime master:31 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other                                                                                                             
163 144 0:17 /1 /dev/console rw,nosuid,noexec,relatime master:4 - devpts devpts rw,gid=5,mode=620,ptmxmode=000                                                                                                                               
88 134 0:45 / /dev/pts rw,relatime - devpts devpts rw,gid=100005,mode=620,ptmxmode=666                                                                                                                                                       
89 134 0:45 /0 /dev/tty1 rw,relatime - devpts devpts rw,gid=100005,mode=620,ptmxmode=666                                                                                                                                                     
90 134 0:45 /1 /dev/tty2 rw,relatime - devpts devpts rw,gid=100005,mode=620,ptmxmode=666                                                                                                                                                     
91 134 0:45 /2 /dev/tty3 rw,relatime - devpts devpts rw,gid=100005,mode=620,ptmxmode=666                                                                                                                                                     
92 134 0:45 /3 /dev/tty4 rw,relatime - devpts devpts rw,gid=100005,mode=620,ptmxmode=666                                                                                                                                                     
93 134 0:46 / /dev/shm rw,nosuid,nodev - tmpfs tmpfs rw,uid=100000,gid=100000                                                                                                                                                                
94 86 0:47 / /run rw,nosuid,nodev - tmpfs tmpfs rw,mode=755,uid=100000,gid=100000                                                                                                                                                            
95 94 0:48 / /run/lock rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,size=5120k,uid=100000,gid=100000                                                                                                                                     
96 140 0:49 / /sys/fs/cgroup rw,nosuid,nodev,noexec - tmpfs tmpfs rw,mode=755,uid=100000,gid=100000                                                                                                                                          
97 96 0:22 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd                                                                                   
98 96 0:24 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio                                                                                                                                                   
99 96 0:31 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,perf_event                                                                                                                                         
100 96 0:27 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpu,cpuacct                                                                                                                                      
101 96 0:32 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices                                                                                                                                              
102 96 0:26 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_cls,net_prio                                                                                                                            
103 96 0:28 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory                                                                                                                                                
104 96 0:30 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,pids                                                                                                                                                    
105 96 0:25 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer                                                                                                                                              
106 96 0:29 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset,clone_children                                                                                                                                 
107 134 0:42 / /dev/mqueue rw,relatime - mqueue mqueue rw                                                                                                                                                                                    
108 94 0:50 / /run/user/1000 rw,nosuid,nodev,relatime - tmpfs tmpfs rw,size=1643068k,mode=700,uid=101000,gid=101000

**Comment by Cistoge** [comment]
I do not use LXD, I followed the guide on https://myles.sh/configuring-lxc-unprivileged-containers-in-debian-jessie/ for installation. Since then, I appiied an OS upgrade inside and outside the container.

**Comment by stgraber** [comment]
Ah, then this isn't a LXD issue, you should file against lxcfs instead https://github.com/lxc/lxcfs.

My guess for the ps issue is that it's the old btime bug that was fixed a while back. I'm not sure what the problem is with the resource limits though, that may be a cgroup problem somehow.

So far it feels like you're running lxcfs 2.0.7 which would explain the bugs, make sure you're on 2.0.8.
