### ISSUE TITLE
lxd image import from URL is broken

### ISSUE THREAD

**Issue by skgsergio** [lxc/lxd#4353]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-116-generic
   * LXC version: 2.0.11 (from `xenial` repository) and 2.21 (from `xenial-backports` repository)
   * LXD version: 2.0.11 (from `xenial` repository) and 2.21 (from `xenial-backports` repository)

# Issue description

Importing an image from an URL using `lxc image import` is broken.

This bug was introduced in the commit https://github.com/lxc/lxd/commit/e81aeb37b01d1a48fe2c60dd6eba1163f7218777 since it does `imageFile = shared.HostPath(filepath.Clean(imageFile))` before trying to check if it is an URL some lines below.

This causes an URL like `https://dl.stgraber.org/lxd/` to be transformed into `https:/dl.stgraber.org/lxd/`.

So according to this repo, the bug was introduced in `lxd-2.19` and `lxd-2.0.11`.

# Steps to reproduce

 1. `lxc image import https://dl.stgraber.org/lxd/`
 2. Fails with error: `error: open https:/dl.stgraber.org/lxd: no such file or directory`

**Comment by stgraber** [comment]
Hmm, must have typoed the issue number, this got fixed today.
