### ISSUE TITLE
Adding and then removing a profile has side effects.

### ISSUE THREAD

**Issue by smoser** [lxc/lxd#4356]
# Required information

 * Distribution: Ubuntu
 * Distribution version: bionic
 * The output of "lxc info" or if that fails:

        $ lxc info
        config:
          core.proxy_http: http://10.7.1.130:3128/
          core.proxy_https: http://10.7.1.130:3128/
        api_extensions:
          <snip>
        api_status: stable
        api_version: "1.0"
        auth: trusted
        public: false
        auth_methods:
        - tls
        environment:
          addresses: []
          architectures:
          - x86_64
          - i686
          certificate: |
             <blob>
          certificate_fingerprint: 3af6f8b<snip>51f75cb
          driver: lxc
          driver_version: 3.0.0.beta2
          kernel: Linux
          kernel_architecture: x86_64
          kernel_version: 4.15.0-12-generic
          server: lxd
          server_pid: 29615
          server_version: 3.0.0.beta5
          storage: zfs
          storage_version: 0.7.5-1ubuntu1
          server_clustered: false
          server_name: milhouse

# Issue description
I have a use case where I want to modify a container before booting it.
This is more than just updating files, so 'file push' is  not sufficient.

I have a utility '[lxc-pstart](https://gist.github.com/smoser/49444542158f2e5f88f1/#file-lxc-pstart-md)' (psuedo start) that basically does:

  * create a profile and a network. The profile and network by default are pstart0. The profile puts a device on the network, and changes the init command (raw.lxc: lxc.init.cmd=/sbin/psuedo-init)
  * modify the container's config to add the new profile
  * push a new init command into the container (psuedo-init)
  * start the container
  * [psuedo-init](https://gist.github.com/smoser/49444542158f2e5f88f1/#file-psuedo-init) brings up a network connection with 'ip' picking a somewhat random address on its /24 network.
  * run user provided commands
  * stop container
  * put the config back to old profile

After that, then it is expected that the user can 'lxc start' and get "the real init" again.

****

# Steps to reproduce

 1. `lxc init ubuntu-daily:xenial x1`
 2.  `lxc-pstart --dump-commands x1 -- sh -xc 'ps axw; ip addr show dev eth0'`
 3. `lxc start x1`

# Information to attach
 - [pstart-session.log](https://github.com/lxc/lxd/files/1841969/pstart-session.log) is a log of running the commands above. 'lxc-pstart --dump-commands' shows all of its interaction with lxc cli.

**Comment by smoser** [comment]
Just for info, this utility/work-flow *did* work in the past.

**Comment by stgraber** [comment]
Can you post `lxc config show --expanded c1` prior to running `lxc-pstart` and then again after running it?

**Comment by smoser** [comment]
[pstart-issue-more.txt](https://github.com/lxc/lxd/files/1842035/pstart-issue-more.txt)
attached pstart with more info (--expanded).

here it is after just for ease:

    architecture: x86_64
    config:
      image.architecture: amd64
      image.description: ubuntu 16.04 LTS amd64 (daily) (20180322)
      image.label: daily
      image.os: ubuntu
      image.release: xenial
      image.serial: "20180322"
      image.version: "16.04"
      volatile.base_image: a772fc4fdc93d303a6fab55227ee4a953c1e116cd68a2b227eb9d56eb7e1a63d
      volatile.eth0.hwaddr: 00:16:3e:52:7b:0e
      volatile.eth0.name: eth0
      volatile.idmap.base: "0"
      volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
      volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
      volatile.last_state.power: STOPPED
    devices:
      eth0:
        nictype: bridged
        parent: lxdbr0
        type: nic
      root:
        path: /
        pool: default
        type: disk
    ephemeral: false
    profiles:
    - default
    stateful: false
    description: ""

**Comment by stgraber** [comment]
Can you paste the content of `/var/snap/lxd/common/lxd/logs/x1/lxc.conf` and of `/var/snap/lxd/common/lxd/logs/lxd.log`?

**Comment by stgraber** [comment]
What happens if you do "rm /var/snap/lxd/common/lxd/logs/x1/*" and then try "lxc start x1"?

**Comment by smoser** [comment]
looks fixed.  what does that mean?

    $ sudo sh -c 'rm -v /var/snap/lxd/common/lxd/logs/x1/*'
    removed '/var/snap/lxd/common/lxd/logs/x1/console.log'
    removed '/var/snap/lxd/common/lxd/logs/x1/forkexec.log'
    removed '/var/snap/lxd/common/lxd/logs/x1/forkstart.log'
    removed '/var/snap/lxd/common/lxd/logs/x1/lxc.conf'
    removed '/var/snap/lxd/common/lxd/logs/x1/lxc.log'
    removed '/var/snap/lxd/common/lxd/logs/x1/lxc.log.old'
    
    $ lxc start x1
    $ lxc list x1
    +------+---------+-----------------------+-----------------------------------------------+------------+-----------+
    | NAME |  STATE  |         IPV4          |                     IPV6                      |    TYPE    | SNAPSHOTS |
    +------+---------+-----------------------+-----------------------------------------------+------------+-----------+
    | x1   | RUNNING | 10.145.210.185 (eth0) | fd42:6470:c1cd:249f:216:3eff:fe52:7b0e (eth0) | PERSISTENT | 0         |
    +------+---------+-----------------------+-----------------------------------------------+------------+-----------+
    
    $ lxc exec x1 -- systemctl | head -n 3
      UNIT                         LOAD   ACTIVE SUB       DESCRIPTION
      -.mount                      loaded active mounted   /
      dev-.lxd\x2dmounts.mount     loaded active mounted   /dev/.lxd-mounts

**Comment by stgraber** [comment]
Tracked down a LXC bug which got fixed upstream now. We'll be tagging new betas of LXC and LXD shortly.
