### ISSUE TITLE
Override "Don't assign idmaps to privileged containers"

### ISSUE THREAD

**Issue by nkabir** [lxc/lxd#4358]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:

```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  storage.zfs_pool_name: xtank
api_extensions:
- id_map
- id_map_base
- resource_limits
api_status: stable
api_version: "1.0"
auth: trusted
auth_methods: []
public: false
environment:
  addresses:
  - 10.1.200.100:8443
  - 172.20.0.1:8443
  - 10.0.3.1:8443
  - 172.17.0.1:8443
  - 172.27.0.1:8443
  - 192.168.122.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFYTCCA0mgAwIBAgIQFEDMPvzTythEPALuvQh99TANBgkqhkiG9w0BAQsFADA3
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRcwFQYDVQQDDA5yb290QHJr
    eC1scGMtMDAeFw0xNzExMTcwMDU4MjRaFw0yNzExMTUwMDU4MjRaMDcxHDAaBgNV
    BAoTE2xpbnV4Y29udGFpbmVycy5vcmcxFzAVBgNVBAMMDnJvb3RAcmt4LWxwYy0w
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA4FFoOyVd7aKulu93EJec
    Nk0FHj0kSwml1OQhREvme3KnY9SGrLz2Q0AGp8+W8b8WN191M9YJSobP+rFP/odV
    0fYA1fBsnK5ml8Gy1PAiGXMPZCjqVxoE2QRowPUooWY1EAphG5VvMRiDdi/fFk/b
    4ypZ/qubHr3r+lpgqp753u6tP7xm5pRI4u+8GXGslJ36crrq9ZbHXnSITBJIb/Nv
    WVQqCcAzcnmM05jhnBLHnmcJd+wxjV4SQMRUpVJkQPId3Zt3U155qMyj0FNOuP3a
    QBI9qUZDgA1g0mXpAffTtRTkJD4sFjJkGWvf2Jclh6TLBrPn1aq86QEBy4TV8vCU
    vr791TyzjfxnLz+/cEGOVAMdN7zikwJwry4WxJ6s7mlV7layopbn9BMhk+B0vBWV
    GW0kOnae8SFgRaw+bLv3Xq25Ecflh8CDo+oKjr5GuYYvNFSVGcYMevSM43lHSPer
    S9DuJHeKQgOwcww4WLkdi1U/AMjW9trizckwW274c9ir1c2OkmFIYwaro8WPXWEV
    RlM5Fu2jElyXqBDjHkoBnqScuz81vtooqC8Q0RzoSMFW3kyRVzWgKu2FyJQztxuX
    8DnCyfH0EkUT5EMqBEfhen5D7UdgteWNn02idtH6cOP+TLE4pzqbvRMk3hFqnPfL
    fi4uKxi8B7/3MgQ8QGXIh20CAwEAAaNpMGcwDgYDVR0PAQH/BAQDAgWgMBMGA1Ud
    JQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwMgYDVR0RBCswKYIJcmt4LWxw
    Yy0whwQKAchkhwSsFAABhwSsEQABhwSsEDL+hwSsFAD+MA0GCSqGSIb3DQEBCwUA
    A4ICAQDEh3yr0YHAN4yZUBTAWzqb1QoLiuk/0Lc7q+9P0YzPOcz+UoMAoDXXgXPe
    YWOc/pa+2DV2lK+OPnIDQKXcWYIoHfj6HbbE8qE2+alAtQgdKLSFa+MFaap7dHkE
    lRQyVWkwd+Njrj5gL2k2e6ldDPLepytIkoCVl9SG+qgU40evClMsPRZL/WwQDeCs
    vGotb90apbVSfk5NVZjFTAHatmdboKGE5eNmbfOrc+63n/r5tXeXjcM8FJWOaHmk
    EK7fSawx4zTSJr6Xws8hZqkcsnfAq6PguTz2cTEXZX8qTSlrVHrqm0IYrvBm3Gve
    dxEZ4h+ix/EfcMoY1TvoewtTrKq4i6pg5Wx6oom6Rt+YZZ7mbMwtOdLmK8Jbino2
    /DF+8HWS6BEQUio+C524dJcH6ukUACIGG+YemNORcjGVkzc5cEpBgrLkGs/caL0K
    AuwDH7neO+g7uXcuhjpTFo7+tLq+c2fyC8xVjLv7Ngq0aW7scSaQX6UEzJWjIdlE
    XN7BHpLRu/wI1mDY/X+MNXv8YkKth2JmpKAAdQgd25uuEaHPzo7LcHk7Yr2PvAoG
    EW6rzjKDMI2ZjCZm4wymz/JK6iuOYfebz7U2FK5vK9rB+vNCSoDBkKoc5DN+gcE3
    Vks74Ir50t1wzIrT86kycmzS0ST+ES5ybtYGTOyKBCF4/1b1WA==
    -----END CERTIFICATE-----
  certificate_fingerprint: 6e66e3a0d6e05463e8b998dd5e5cc3d04fa2e0650114b8f13d304c8a9c84d9da
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-116-generic
  server: lxd
  server_pid: 11761
  server_version: 2.0.11
  storage: zfs
  storage_version: "5"
```
# Issue description

I'd like to override the restriction for assigning idmaps in privileged containers. Is this possible? I do not plan to deploy this into production--I just need this feature for testing.

https://lists.linuxcontainers.org/pipermail/lxc-devel/2016-November/015117.html

**Comment by stgraber** [comment]
What are you trying to do exactly?

A privileged container by definition does not have a user namespace and so can't have a uid/gid map.
To be able to set a uid/gid map, you need a user namespace and therefore need an unprivileged container.

What map you use is then up to you, either let LXD share the normal map, or use security.idmap.isolated to have a distinct set of uid/gid for the container or use raw.idmap to directly map some uid/gid.

**Comment by nkabir** [comment]
I am testing kvm code in an lxd container. lxd is wonderful and I now use it everywhere. My unprivileged containers mount my home folder and map ubuntu (default user in container) to my username (on the physical host). I wanted to keep this configuration in a privileged container to enable me to continue editing files in my home folder with the correct physical host identity.

Are you implying that I need to use `security.idmap.isolated` in that context?

**Comment by stgraber** [comment]
A privileged container would have all its uid/gid match that of the host, so you wouldn't need any mapping for your home directory.

**Comment by nkabir** [comment]
Understood. My lxd container uses 'ubuntu' with a home folder mounted from my user e.g. 'asmith'. In an unprivileged container, I can make changes to code from within lxd (as 'ubuntu') and they are written to the mounted folder as 'asmith'.

I lose this when I use a privileged container. The 'asmith' home folder contents no longer appear as 'ubuntu' content from within the privileged container. Any changes I make appear as a different user (not 'asmith') in the 'asmith' home folder on the physical host.

**Comment by stgraber** [comment]
If your /home/blah on the host is owned by 1000:1000, and mapped to /home/blah in the container, then 1000:1000 in the privileged container will write as 1000:1000.

There is no map, so just make sure the user in the container has the same uid and gid as it does on the host.

**Comment by stgraber** [comment]
Closing the issue as there's nothing to be done in LXD about this.
Privileged containers are defined by the fact that they don't have a uid/gid map, so uids and gids in such containers match those outside of the container.

**Comment by nkabir** [comment]
Thank you for the feedback. I found #3393 that is related to my efforts to run kvm tests in an unprivileged lxd container. Is it possible to create a new network in an unprivileged container using `virsh net-create`?

```
# virsh net-create network.xml 
error: Failed to create network from network.xml
error: Unable to set bridge virbrdemo forward_delay: Permission denied

<network>
  <name>demo</name>
  <forward mode='nat'/>
  <bridge name='virbrdemo' stp='on' delay='0'/>
  <ip address='192.168.132.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.132.2' end='192.168.132.254'/>
    </dhcp>
  </ip>
</network>
```
The issue #3393 mentions manual workarounds but I would like to avoid them if possible.
