### ISSUE TITLE
LXD fail to start  

### ISSUE THREAD

**Issue by hahattan** [lxc/lxd#4365]
# Required information

 * Distribution: Ubuntu
 * Distribution version: xenial 16.04
 * The output of "lxc info" or if that fails: 
`error: Get http://unix.socket/1.0: read unix @->/var/lib/lxd/unix.socket: read: connection reset by peer`
   * Kernel version: 4.13.0-37-generic
   * LXC version: 2.0.11
   * LXD version: 2.0.11
   * Storage backend in use: dir

# Issue description

I was following the instructions on the [Getting-Start](https://linuxcontainers.org/lxd/getting-started-cli/) page, after I finished the `lxd init` and reboot my machine, I couldn't get the lxd work normally.  
I've tried `$ lxc list` and it output `Connection refused; is LXD running?`  
 

# Information to attach

I also tried `$ sudo service lxd start` and it said `A dependency job for lxd.service failed. See 'journalctl -xe' for details.` below is the full logs: 
```
Mar 27 16:58:01 scope-B150M-D3H systemd[1]: Failed to start LXD - network bridge.
-- Subject: Unit lxd-bridge.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit lxd-bridge.service has failed.
--
-- The result is failed.
Mar 27 16:58:01 scope-B150M-D3H systemd[1]: Dependency failed for LXD - main daemon.
-- Subject: Unit lxd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit lxd.service has failed.
--
-- The result is dependency.
Mar 27 16:58:01 scope-B150M-D3H systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Mar 27 16:58:01 scope-B150M-D3H systemd[1]: lxd-bridge.service: Unit entered failed state.
Mar 27 16:58:01 scope-B150M-D3H systemd[1]: lxd-bridge.service: Failed with result 'exit-code'.
Mar 27 16:58:01 scope-B150M-D3H sudo[2662]: pam_unix(sudo:session): session closed for user root
Mar 27 16:58:01 scope-B150M-D3H nm-dispatcher[2758]: req:2 'down' [lxdbr0]: start running ordered scripts...
```

**Comment by stgraber** [comment]
The lxd-bridge systemd unit is the problem here. The most common source of failure for it is when you have another DNS server running on your system like bind9/named

**Comment by stgraber** [comment]
Manually running `sudo /usr/lib/lxd/lxd-bridge.start` would likely show the underlying error which would confirm if it's a conflicting DNS server or something else.

**Comment by hahattan** [comment]
I ran `/usr/lib/lxd/lxd-bridge.start` and here's the output:
```
dnsmasq: failed to create listening socket for 10.0.8.1: Address already in use
Failed to setup lxd-bridge.
```
it seemed the ip address I set while doing `lxd init` is already taken
is there any way I can check which application is using that ip address or can I change the ip setting of lxd?

thanks

**Comment by stgraber** [comment]
Ok, so that's the error I'd expect if you already had a DNS server running.

Running `sudo netstat -lnp | grep 53` would let you check what's binding port 53 on your system.

**Comment by hahattan** [comment]
here's the output
```
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN      1518/named
tcp        0      0 172.17.0.1:53           0.0.0.0:*               LISTEN      1518/named
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      1236/dnsmasq
tcp        0      0 140.114.85.220:53       0.0.0.0:*               LISTEN      1236/dnsmasq
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      1518/named
tcp6       0      0 ::1:53                  :::*                    LISTEN      1236/dnsmasq
tcp6       0      0 ::1:953                 :::*                    LISTEN      1518/named
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1000/avahi-daemon:
udp        0      0 192.168.122.1:53        0.0.0.0:*                           3756/dnsmasq
udp        0      0 192.168.122.1:53        0.0.0.0:*                           1518/named
udp        0      0 172.17.0.1:53           0.0.0.0:*                           1518/named
udp        0      0 140.114.85.220:53       0.0.0.0:*                           1518/named
udp        0      0 127.0.0.1:53            0.0.0.0:*                           1518/named
udp        0      0 127.0.0.1:53            0.0.0.0:*                           1236/dnsmasq
udp        0      0 140.114.85.220:53       0.0.0.0:*                           1236/dnsmasq
udp6       0      0 :::53289                :::*                                1000/avahi-daemon:
udp6       0      0 :::5353                 :::*                                1000/avahi-daemon:
udp6       0      0 :::53                   :::*                                1518/named
udp6       0      0 ::1:53                  :::*                                1236/dnsmasq
unix  2      [ ACC ]     STREAM     LISTENING     29755    1517/dockerd        /run/docker/libnetwork/dd22f75434570b13809605a96f15bc9fc50412d862e723a5e537d0a5793273bf.sock
```
do I need to unbind all of them or there's specific one cause the problem ?

thanks

**Comment by stgraber** [comment]
Ok, so as expected the problem is that you have the bind9 package installed (which runs that named service).

If you don't need a full DNS server running on your machine, then just removing the bind9 package will take care of the problem. If you do need that DNS server, then you'll have to configure bind9 to only listen to those interfaces you need it to. I can't remember exactly how that works, but it's some config in /etc/bind9/

**Comment by hahattan** [comment]
so after deleting bind9 everything is working correctly and I can successfully launch my first container, thanks for the help .
