### ISSUE TITLE
Node management with clustering

### ISSUE THREAD

**Issue by Mantwon** [lxc/lxd#4368]
Hello,

I am wondering how to address this problem: 

```
lxc cluster delete node001 --force-local
error: Delete https://172.x.x.x:8443/1.0/storage-pools/default: Unable to connect to: 172.16.x.x:8443
```
```
All existing data is lost when joining a cluster, continue? (yes/no) [default=no] yes
error: failed to request to add node: cluster already has node with name node001
```

There is a node in the cluster that needed to be rebuilt, when I try to delete it -- it won't work, when I try to rejoin, it won't work.. is there a way to force it to be removed?

**Comment by stgraber** [comment]
@freeekanayaka

**Comment by stgraber** [comment]
Oh, did you try passing `--force` to `lxc cluster delete`, that's needed to allow removing nodes that can't be reached anymore.

**Comment by Mantwon** [comment]
derp.

That worked, sorry to waste your time.
