### ISSUE TITLE
image export to stdout not working

### ISSUE THREAD

**Issue by kopfsalat** [lxc/lxd#4370]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.10
 * The output of "lxc info" or if that fails:
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-37-generic
  server: lxd
  server_pid: 3354
  server_version: "2.18"
  storage: zfs
  storage_version: 0.6.5.11-1ubuntu3

# Issue description

I want to export images to stdout to pipe the data through gpg before it's going to be written on an NAS. Help says 'The target may be an existing directory, file name, or "-" to specify stdout.' 
The output I get on stdout is just export progress and success message: 'Image exported successfully!' But I have a file '-' in my local directory which looks suspiciously like the image file. 

# Steps to reproduce

$ lxc image export container_backup
Image exported successfully!
$ sha1sum 0a77db518f0cd00e4cd022fd815b36323dc792571bb6c20d482bf9979233a289.tar.gz 
c940552476a970fb324f3701d6179975c79d9524  0a77db518f0cd00e4cd022fd815b36323dc792571bb6c20d482bf9979233a289.tar.gz

$ lxc image export container_backup - | gpg --encrypt  ...
$ ls -la
[...]
-rw-rw-r-- 1 container container 321240299 Mar 28 14:26 -
$ mv - suspicious # because sha1sum reads from stdin when '-' is the first arg
$ sha1sum suspicious 
c940552476a970fb324f3701d6179975c79d9524  suspicious

**Comment by stgraber** [comment]
I'll update the documentation to remove the mention of the stdout option.

**Comment by stgraber** [comment]
stdout probably hasn't worked ever since split images were introduced a few years ago as we can't tell ahead of time whether an image is going to be made of one or multiple files so we always have to download things as if it's going to be multiple files and then move them appropriately, which effectively prevents any streaming to stdout.

**Comment by kopfsalat** [comment]
> stdout probably hasn't worked ever since split images were introduced a few years ago as we can't tell ahead of time whether an image is going to be made of one or multiple files so we always have to download things as if it's going to be multiple files and then move them appropriately, which effectively prevents any streaming to stdout.

Ok, good to know. I'll look for another way to push encrypted images to the NAS. Maybe I'll save the image locally and encrypt it on disk... at least if the images are small enough to do so. 

>  I'll update the documentation to remove the mention of the stdout option.

And thanks for updating the docs.

Best wishes
