### ISSUE TITLE
Two IP Addresses "lxc list" reports after "/etc/init.d/networking retsart" on the container

### ISSUE THREAD

**Issue by gbonazzoli** [lxc/lxd#4378]
# Required information

 * Distribution: **Ubuntu Server**
 * Distribution version: **17.10**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.13.0-37-generic**
   * LXC version: **2.18**
   * LXD version: **2.18**
   * Storage backend in use: **ZFS 0.6.5.11-1ubuntu3**

# Issue description

If you change a static ip address inside a container (in my case in an ubuntu 16.04.4 container) and then stop and start networking you have a correct networking situation inside the container but the command "lxc list" on the LXD host reports both the old and the new IP Addresses. And Both address are operative on the network.

```
root@kvm01:/kvm# lxc list
+----------------+---------+--------------------------------+------+------------+-----------+
|      NAME      |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
+----------------+---------+--------------------------------+------+------------+-----------+
| kitelabs       | RUNNING | 129.101.101.208 (eth0)         |      | PERSISTENT | 0         |
+----------------+---------+--------------------------------+------+------------+-----------+
| srv-bonaz      | STOPPED |                                |      | PERSISTENT | 0         |
+----------------+---------+--------------------------------+------+------------+-----------+
| srv-debian     | RUNNING | 129.101.110.20 (eth0)          |      | PERSISTENT | 0         |
+----------------+---------+--------------------------------+------+------------+-----------+
| srv-prestashop | RUNNING | 129.101.103.173 (eth0)         |      | PERSISTENT | 0         |
|                |         | 129.101.102.173 (eth0)         |      |            |           |
+----------------+---------+--------------------------------+------+------------+-----------+
| srv-progress   | RUNNING | 129.101.101.1 (eth0)           |      | PERSISTENT | 0         |
+----------------+---------+--------------------------------+------+------------+-----------+
```

# Steps to reproduce

 1. Change container machine IP address by editing **/etc/network/interfaces**
 2. Stop networking inside the container with **/etc/init.d/networking stop**
 3. Start networking inside the container with **/etc/init.d/networking start**
 4. Give **lxc list** command on the LXD host

**Comment by stgraber** [comment]
LXD reports directly what's reported by the kernel, so I'm pretty sure your container is actually misconfigured.

The steps above are wrong. You should always do:
 - networking stop
 - changes to /etc/network/interfaces
 - networking start

Otherwise ifupdown doesn't know what to remove when restarting networking, ending up with the old IP still being present.

This is usually hidden by the fact that "ifconfig" only shows a single IP, but if you were to run "ip -4 addr list" in your container, you'd see the two IPs in there.

**Comment by gbonazzoli** [comment]
Perfect! It works like a charm!
