### ISSUE TITLE
'launch' not listed in 'lxc --help'

### ISSUE THREAD

**Issue by markshuttle** [lxc/lxd#4380]
'lxc --help' does not include 'launch' in the list of commands available, and it certainly should! Might be worth checking that there are not any other commands missing, too.

$ lxc --help
Description:
  Command line client for LXD
[...]
Available Commands:
  alias       Manage command aliases
[...]
  info        Show container or server information
  list        List containers
  move        Move containers within or in between LXD instances
[...]
Use "lxc [command] --help" for more information about a command.

**Comment by stgraber** [comment]
Oops, I think that was a case of bad copy/paste when setting up the new parser last week.

We do hide a bunch of advanced commands by default (requiring the --all flag to show up), but we have a few false positives here that we should certainly have spotted in review...
The ones that we're missing in the main help are launch, restart and stop. Fixing that now.

**Comment by stgraber** [comment]
stop and restart were bad copy/paste from pause...
launch was a bit trickier because it inherits from init and init is hidden, so we missed an override there.

**Comment by stgraber** [comment]
Sent a pull request which addresses this issue. After it's reviewed and merged, the fix will be included in the stable-3.0 branch and be included in the candidate snap as well as in the next batch of cherry-picks for the LXD deb.
