### ISSUE TITLE
Improve database handling

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4390]
Now that we are effectively dealing with two databases (lxd.db and raft), we need to make sure we have some pretty consistent tooling available to deal with those databases.

Off the top of my head, I'd like to at least see:
 - Move all database files under /var/lib/lxd/database/ renaming lxd.db to local.db in the process and `raft` to `global` so that we have consistent naming for the two databases.
 - Add support for `patch.local.sql` and `patch.global.sql` files in /var/lib/lxd/database. If present, they should be read and executed immediately after loading the database driver. On success, the file should be removed from disk to prevent accidental double execution.
 - Fix `lxd sql` causing LXD to panic when fed an empty query
 - Make `lxd sql` support reading from stdin as an alternative to passing the query as an argument
 - Have `lxd sql` support running multiple queries (if not already the case)
 - Make `lxd sql` interact with both databases, offering a consistent way to poke at LXD's databases. I'm happy to just require the first argument be one of `local` or `global` to achieve this.
 - Add support for `.dump` to `lxd sql` as a way to dump the database in SQL format.
 - Update our pre-upgrade logic to backup both local and global databases prior to doing a schema upgrade. Test that we have a clear way to perform a revert in a non-clustered environment (equivalent to `mv lxd.db.bak lxd.db` prior to 3.0)
 - Update doc/database.md to reflect the current database schema, explain the split between the two databases and make it clear what is where.

I expect to cherry-pick all of this to the stable-3.0 branch for LXD 3.0.1.

**Comment by freeekanayaka** [comment]
Yes, perhaps that could be a new command "lxc cluster enable".

**Comment by stgraber** [comment]
Yep. I remember effectively doing that using the REST API but then having some issues with existing objects, but that was pre-release.

**Comment by freeekanayaka** [comment]
As for:

> Update our pre-upgrade logic to backup both local and global databases prior to doing a schema upgrade. Test that we have a clear way to perform a revert in a non-clustered environment (equivalent to mv lxd.db.bak lxd.db prior to 3.0)

I'm not entirely sure what experience you want exactly. The current state of affairs is that:

- Schema upgrades to the local database are run first. Those are transactional, so if they fail you local db will be unchanged, and the lxd daemon exits with an error.

- Schema upgrades to the global database are run next. Those are transactional as well, so if they fail your global db will be unchanged, and the lxd daemon exits with an error.

What we could do is to automatically restore the local database backup if the global database schema update fails.

**Comment by stgraber** [comment]
I like having a backup file of the database be created whenever we perform schema changes, LXD never uses those for automatic revert, but they're used in the unlikely event that we need the user to downgrade LXD. In which case we can have them install the previous version, switch to that backup and depending on the case, revert some filesystem changes.

**Comment by freeekanayaka** [comment]
Or perhaps your a thinking more at failures happening with patches that run after the post-schema updates?

**Comment by stgraber** [comment]
The issue is when LXD itself is busted. It can be a broken patch or just a broken codepath in LXD itself which either causes crashes or just prevents you from performing some kind of action.

If you spot that immediately after upgrading, you can downgrade the package, move the DB backups in place and start again.

I also use the `.bak` pretty often to look into an earlier, cleaner state of a misbehaving system.

**Comment by stgraber** [comment]
Remaining issues now that I've merged those PRs:
 - Add support for patch.local.sql and patch.global.sql files in /var/lib/lxd/database. If present, they should be read and executed immediately after loading the database driver. On success, the file should be removed from disk to prevent accidental double execution.
 - Update our pre-upgrade logic to backup both local and global databases prior to doing a schema upgrade. Test that we have a clear way to perform a revert in a non-clustered environment (equivalent to mv lxd.db.bak lxd.db prior to 3.0)
 - Update doc/database.md to reflect the current database schema, explain the split between the two databases and make it clear what is where.
