### ISSUE TITLE
LXD 3.0 auto-init Broken

### ISSUE THREAD

**Issue by trevorgfrancis** [lxc/lxd#4392]
# Required information

Ubuntu 16.04
Linux f8-c1-n13 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
lxd 3.0 stable

# Issue description

cannot perform auto init using command line

# Steps to reproduce

/snap/bin/lxd init --auto --storage-backend=dir network-address=0.0.0.0 --network-port=8443 --trust-password=blahblah

# Information to attach
panic: assignment to entry in nil map

goroutine 1 [running]:
main.(*cmdInit).RunAuto(0xc420304d20, 0xc42030c780, 0xc420213270, 0x0, 0x5, 0x10e3a40, 0xc4202c7f40, 0xf, 0xf, 0xf)
	/build/lxd-latest-candidate/parts/lxd/go/src/github.com/lxc/lxd/lxd/main_init_auto.go:67 +0x9b4
main.(*cmdInit).Run(0xc420304d20, 0xc42030c780, 0xc420213270, 0x0, 0x5, 0x0, 0x0)
	/build/lxd-latest-candidate/parts/lxd/go/src/github.com/lxc/lxd/lxd/main_init.go:103 +0x252
main.(*cmdInit).Run-fm(0xc42030c780, 0xc420213270, 0x0, 0x5, 0x0, 0x0)
	/build/lxd-latest-candidate/parts/lxd/go/src/github.com/lxc/lxd/lxd/main_init.go:56 +0x52
github.com/spf13/cobra.(*Command).execute(0xc42030c780, 0xc420213220, 0x5, 0x5, 0xc42030c780, 0xc420213220)
	/build/lxd-latest-candidate/parts/lxd/go/src/github.com/spf13/cobra/command.go:762 +0x468
github.com/spf13/cobra.(*Command).ExecuteC(0xc4202cb400, 0x0, 0xc42030d680, 0xc42030d680)
	/build/lxd-latest-candidate/parts/lxd/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc4202cb400, 0xc420303e10, 0x1)
	/build/lxd-latest-candidate/parts/lxd/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/build/lxd-latest-candidate/parts/lxd/go/src/github.com/lxc/lxd/lxd/main.go:155 +0xd4d

**Comment by stgraber** [comment]
That's been fixed in the stable-3.0 branch and in the snap package (if that's what you're using).
A test has also been added to prevent regressions.

**Comment by trevorgfrancis** [comment]
Running latest stable...

root@f8-c1-n12:~# snap refresh lxd
snap "lxd" has no updates available

**Comment by trevorgfrancis** [comment]
So no it hasnt made it out to snap in stable branch.

**Comment by stgraber** [comment]
What revision do you see in `snap list`?

**Comment by trevorgfrancis** [comment]
root@f8-c1-n12:~# snap version
snap    2.31.2
snapd   2.31.2
series  16
ubuntu  16.04
kernel  4.13.0-37-generic


root@f8-c1-n12:~# snap list
Name  Version    Rev   Developer  Notes
core  16-2.31.2  4206  canonical  core
lxd   3.0.0      6418  canonical  -

**Comment by stgraber** [comment]
Confirmed that the snap doesn't have the fix for some reason, despite it being clearly listed as cherry-picked in the manifest... rebuilding the snap now.

**Comment by stgraber** [comment]
Oh, I see the problem, fixing.

**Comment by stgraber** [comment]
Problem fixed in the packaging branch, new candidate snaps will build in the next hour or so.
I need to go get some sleep but I'll be promoting those to stable in the morning.
