### ISSUE TITLE
Snap Refresh of LXD kills all containers on host

### ISSUE THREAD

**Issue by trevorgfrancis** [lxc/lxd#4398]
Ubuntu 16.04
LXD 3.0.0

If Snap is going to auto-refresh the LXD daemon randomly (like it does), then LXD cant restart the containers. This completely defeats the purpose of running VM-like workload inside of containers (the whole purpose of the LXD project).

**Comment by trevorgfrancis** [comment]
Apr  3 14:48:56 f8-c1-n13 systemd[1]: Reloading.
Apr  3 14:48:56 f8-c1-n13 systemd[1]: Starting Daily apt download activities...
Apr  3 14:48:56 f8-c1-n13 systemd[1]: Reloading.
Apr  3 14:48:56 f8-c1-n13 systemd[1]: Mounting Mount unit for lxd...
Apr  3 14:48:56 f8-c1-n13 systemd[1]: Mounted Mount unit for lxd.
Apr  3 14:48:56 f8-c1-n13 systemd[1]: Stopping Service for snap application lxd.daemon...
Apr  3 14:48:56 f8-c1-n13 lxd.daemon[24043]: => Stop reason is: snap refresh
Apr  3 14:48:56 f8-c1-n13 lxd.daemon[24043]: => Stopping LXD
Apr  3 14:48:57 f8-c1-n13 systemd[1]: Started Daily apt download activities.
Apr  3 14:48:57 f8-c1-n13 systemd[1]: Stopped Service for snap application lxd.daemon.
Apr  3 14:48:58 f8-c1-n13 systemd[1]: Reloading.

**Comment by trevorgfrancis** [comment]
This was supposed to be fixed with #4193

**Comment by stgraber** [comment]
Can you show the entire output of `journalctl -u snap.lxd.daemon` please?

That `Stop reason is: snap refresh` message is what's shown specifically when LXD is restarted without respawning containers, so my guess is that you have another restart of the daemon happening before that with a reason of `crashed` or something along those lines.

**Comment by stgraber** [comment]
Looking at the logs you sent me by e-mail now, I can see:
```
Apr 03 15:19:58 f10-c1-n5 lxd.daemon[371]: => Stop reason is: crashed
```

**Comment by stgraber** [comment]
So that would indeed have caused all containers to be bounced. I'll take a look to see if there's something we can do to prevent systemd from resetting the entire cgroup during crashes.

**Comment by stgraber** [comment]
Can you also share `snap changes`? That may give us a bit of a timeline for what revision landed on the system.

**Comment by trevorgfrancis** [comment]
ID   Status  Spawn                 Ready                 Summary
7    Done    2018-04-03T15:09:49Z  2018-04-03T15:09:59Z  Auto-refresh snap "lxd"
8    Error   2018-04-03T20:19:49Z  2018-04-03T20:20:02Z  Auto-refresh snap "lxd"
9    Done    2018-04-04T00:30:12Z  2018-04-04T00:30:30Z  Refresh snaps "lxd", "core"

**Comment by trevorgfrancis** [comment]
part of the issue (potentially) is that the profile for these containers were running unsupported raw.lxc commands prior to auto-refresh

**Comment by stgraber** [comment]
Profile with now unsupported raw.lxc shouldn't cause an upgrade issue, it will cause containers to be marked as ERROR afterwards and most actions against them to fail until the key is updated or removed, but it shouldn't actually cause LXD itself to crash.

Do you have anything relevant in /var/snap/lxd/common/lxd/logs/lxd.log that may explain the crash?

**Comment by stgraber** [comment]
LXD certainly recovered from whatever that crash was, but it'd obviously be best if we could figure out what it was an fix it... I'm still setting up a test system to do some crash testing on the LXD snap and try to find a way to have it keep things going even when it crashes.

**Comment by trevorgfrancis** [comment]
nothing useful in:

/var/snap/lxd/common/lxd/logs/lxd.log

**Comment by stgraber** [comment]
So I pushed one fix for a case where a clean install or possibly some upgrades would hit the crashed state when not needed. I'll poke at it a bit more though as I think there's another case we could better handle.

**Comment by stgraber** [comment]
Spent half an hour stress testing the daemon with the latest fixes, I can't seem to re-trigger the mixed crashed+host-shutdown case that I could before, so hopefully this actually got fixed.

If anyone runs into a similar issue where a LXD daemon upgrade restarts your containers, please post your full `journalctl` output here.
