### ISSUE TITLE
Issues launching new containers

### ISSUE THREAD

**Issue by anthonydillon** [lxc/lxd#4399]
I have started to experiencing issues all of a sudden. I had a working containers for a number of weeks before hand. Today this is what I get:
```
$ lxc version
Client version: 3.0.0
Server version: 3.0.0
```
``` 
$ lxc launch ubuntu:16.04 first
Creating first
Starting first                              
Error: Missing parent 'lxdbr1' for nic 'eth0'
Try `lxc info --show-log local:first` for more info
```
```
$ lxc info --show-log local:first
Name: first
Remote: unix://
Architecture: x86_64
Created: 2018/04/03 22:47 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

```
I deleted the old containers as I couldn't run any commands on them without hitting:
```
Error: Failed container creation: Failed to load raw.lxc
```
Now I can't create anymore.

**Comment by stgraber** [comment]
Hi,

So looks like you have two issues, one is that your containers want to use a bridge called `lxdbr1` which doesn't appear to exist.

The second, which explains why none of your containers are working is that you have some legacy configuration key in `raw.lxc` which isn't supported as of liblxc 3.0.

Can you show:
 - `lxc network list`
 - `lxc profile show default`

That should give us some idea of what's going on and how to make things work again.

**Comment by anthonydillon** [comment]
Strange, I haven't changed anything since it was working so I thought it must be to do with 3.0.0.

```
$ lxc network list
+-----------------+----------+---------+-------------+---------+
|      NAME       |   TYPE   | MANAGED | DESCRIPTION | USED BY |
+-----------------+----------+---------+-------------+---------+
| docker0         | bridge   | NO      |             | 0       |
+-----------------+----------+---------+-------------+---------+
| enp0s31f6       | physical | NO      |             | 0       |
+-----------------+----------+---------+-------------+---------+
| enx000ec6d8e6e7 | physical | NO      |             | 0       |
+-----------------+----------+---------+-------------+---------+
| lxdbr0          | bridge   | YES     |             | 0       |
+-----------------+----------+---------+-------------+---------+
| mpbr0           | bridge   | NO      |             | 0       |
+-----------------+----------+---------+-------------+---------+
| wlp4s0          | physical | NO      |             | 0       |
+-----------------+----------+---------+-------------+---------+
| wwp0s20f0u6i12  | physical | NO      |             | 0       |
+-----------------+----------+---------+-------------+---------+
```
```
$ lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: lxdbr1
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/c1
- /1.0/containers/first
```

**Comment by stgraber** [comment]
@anthonydillon it didn't, but a number of raw.lxc keys have changed names.

https://discuss.linuxcontainers.org/t/lxc-2-1-has-been-released/487 has a table with all the renames. Those were causing warnings in LXC 2.1 and the old ones got removed in LXC 3.0.

**Comment by stgraber** [comment]
The one to change in this case is `lxc.aa_profile` is now `lxc.apparmor.profile`.

**Comment by anthonydillon** [comment]
Great stuff, thank you! Worked, I'll get the documentation updated.

**Comment by anthonydillon** [comment]
Great stuff, thank you! Worked, I'll get the documentation updated.

**Comment by anthonydillon** [comment]
@stgraber I will pass on your message. The bug is here if you wanted to follow:
https://bugs.launchpad.net/maas/+bug/1761212
