### ISSUE TITLE
Cannot latest snap installed LXD wont start

### ISSUE THREAD

**Issue by trevorgfrancis** [lxc/lxd#4403]
Linux f9-c2-n12 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

fresh build of ubuntu

root@f9-c2-n12:~# snap install lxd
lxd 3.0.0 from 'canonical' installed
root@f9-c2-n12:~# snap refresh
All snaps up to date.

root@f9-c1-n13:~# snap list
Name  Version    Rev   Tracking  Developer  Notes
core  16-2.32.1  4327  stable    canonical  core
lxd   3.0.0      6469  stable    canonical  -

root@f9-c2-n12:~# /snap/bin/lxd init --auto --storage-backend=dir --network-address=0.0.0.0 --network-port=8443 --trust-password=XXXXXXX
cat: /proc/self/attr/current: Permission denied
/snap/lxd/6469/commands/lxd: 6: exec: aa-exec: Permission denied

syslog:

Apr  3 21:40:13 f9-c2-n12 kernel: [14333.179046] audit: type=1400 audit(1522809613.356:78): apparmor="DENIED" operation="open" profile="snap.lxd.daemon" name="/proc/6394/attr/current" pid=6394 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Apr  3 21:40:13 f9-c2-n12 kernel: [14333.179270] audit: type=1400 audit(1522809613.356:79): apparmor="DENIED" operation="exec" profile="snap.lxd.daemon" name="/usr/sbin/aa-exec" pid=6380 comm="daemon.start" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Apr  3 21:40:13 f9-c2-n12 lxd.daemon[6396]: cat: /proc/self/attr/current: Permission denied
Apr  3 21:40:13 f9-c2-n12 lxd.daemon[6396]: /snap/lxd/6469/commands/daemon.stop: 6: exec: aa-exec: Permission denied
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Control process exited, code=exited status=126
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Unit entered failed state.
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Service hold-off time over, scheduling restart.
Apr  3 21:40:13 f9-c2-n12 systemd[1]: Stopped Service for snap application lxd.daemon.
Apr  3 21:40:13 f9-c2-n12 systemd[1]: Started Service for snap application lxd.daemon.
Apr  3 21:40:13 f9-c2-n12 lxd.daemon[6414]: cat: /proc/self/attr/current: Permission denied
Apr  3 21:40:13 f9-c2-n12 lxd.daemon[6414]: /snap/lxd/6469/commands/daemon.start: 6: exec: aa-exec: Permission denied
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=126/n/a
Apr  3 21:40:13 f9-c2-n12 lxd.daemon[6430]: cat: /proc/self/attr/current: Permission denied
Apr  3 21:40:13 f9-c2-n12 lxd.daemon[6430]: /snap/lxd/6469/commands/daemon.stop: 6: exec: aa-exec: Permission denied
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Control process exited, code=exited status=126
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Unit entered failed state.
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Service hold-off time over, scheduling restart.
Apr  3 21:40:13 f9-c2-n12 systemd[1]: Stopped Service for snap application lxd.daemon.
Apr  3 21:40:13 f9-c2-n12 systemd[1]: Started Service for snap application lxd.daemon.
Apr  3 21:40:13 f9-c2-n12 lxd.daemon[6447]: cat: /proc/self/attr/current: Permission denied
Apr  3 21:40:13 f9-c2-n12 lxd.daemon[6447]: /snap/lxd/6469/commands/daemon.start: 6: exec: aa-exec: Permission denied
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=126/n/a
Apr  3 21:40:13 f9-c2-n12 lxd.daemon[6463]: cat: /proc/self/attr/current: Permission denied
Apr  3 21:40:13 f9-c2-n12 lxd.daemon[6463]: /snap/lxd/6469/commands/daemon.stop: 6: exec: aa-exec: Permission denied
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Control process exited, code=exited status=126
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Unit entered failed state.
Apr  3 21:40:13 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
Apr  3 21:40:14 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Service hold-off time over, scheduling restart.
Apr  3 21:40:14 f9-c2-n12 systemd[1]: Stopped Service for snap application lxd.daemon.
Apr  3 21:40:14 f9-c2-n12 systemd[1]: snap.lxd.daemon.service: Start request repeated too quickly.
Apr  3 21:40:14 f9-c2-n12 systemd[1]: Failed to start Service for snap application lxd.daemon.

root@f9-c2-n12:/var/lib/snapd/apparmor/profiles# snap list
Name  Version    Rev   Tracking  Developer  Notes
core  16-2.32.1  4327  stable    canonical  core
lxd   3.0.0      6469  stable    canonical  -

root@f9-c2-n12:/var/lib/snapd/apparmor/profiles# apparmor_status
apparmor module is loaded.
22 profiles are loaded.
22 profiles are in enforce mode.
   /sbin/dhclient
   /snap/core/4327/usr/lib/snapd/snap-confine
   /snap/core/4327/usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/NetworkManager/nm-dhcp-helper
   /usr/lib/connman/scripts/dhclient-script
   /usr/lib/snapd/snap-confine
   /usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/lib/snapd/snap-confine//snap_update_ns
   /usr/sbin/ntpd
   /usr/sbin/tcpdump
   snap-update-ns.core
   snap-update-ns.lxd
   snap.core.hook.configure
   snap.lxd.benchmark
   snap.lxd.check-kernel
   snap.lxd.daemon
   snap.lxd.database
   snap.lxd.hook.configure
   snap.lxd.lxc
   snap.lxd.lxd
   snap.lxd.migrate
0 profiles are in complain mode.
2 processes have profiles defined.
2 processes are in enforce mode.
   /sbin/dhclient (1197)
   /usr/sbin/ntpd (1399)
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.

root@f9-c2-n12:/var/lib/snapd/apparmor/profiles# snap interfaces
```
Slot                       Plug
:account-control           -
:accounts-service          -
:alsa                      -
:autopilot-introspection   -
:avahi-control             -
:avahi-observe             -
:bluetooth-control         -
:bluez                     -
:broadcom-asic-control     -
:browser-support           -
:camera                    -
:classic-support           -
:core-support              core:core-support-plug
:cups-control              -
:dcdbas-control            -
:desktop                   -
:desktop-legacy            -
:docker-support            -
:firewall-control          -
:framebuffer               -
:fuse-support              -
:gpg-keys                  -
:gpg-public-keys           -
:gpio-memory-control       -
:greengrass-support        -
:gsettings                 -
:hardware-observe          -
:hardware-random-control   -
:hardware-random-observe   -
:home                      -
:io-ports-control          -
:joystick                  -
:kernel-module-control     -
:kubernetes-support        -
:kvm                       -
:libvirt                   -
:locale-control            -
:log-observe               -
:lxd-support               -
:modem-manager             -
:mount-observe             -
:netlink-audit             -
:netlink-connector         -
:network                   -
:network-bind              -
:network-control           -
:network-manager           -
:network-observe           -
:network-setup-control     -
:network-setup-observe     -
:ofono                     -
:opengl                    -
:openvswitch               -
:openvswitch-support       -
:optical-drive             -
:password-manager-service  -
:physical-memory-control   -
:physical-memory-observe   -
:ppp                       -
:process-control           -
:pulseaudio                -
:raw-usb                   -
:removable-media           -
:screen-inhibit-control    -
:shutdown                  -
:snapd-control             -
:ssh-keys                  -
:ssh-public-keys           -
:system-observe            -
:system-trace              -
:time-control              -
:timeserver-control        -
:timezone-control          -
:tpm                       -
:uhid                      -
:unity7                    -
:upower-observe            -
:wayland                   -
:x11                       -
lxd:lxd                    -
-                          lxd:lxd-support
-                          lxd:network
-                          lxd:system-observe
```

**Comment by trevorgfrancis** [comment]
This is resolved with:

snap connect lxd:lxd-support core:lxd-support
systemctl restart snap.lxd.daemon

**Comment by trevorgfrancis** [comment]
Note: This is a fresh install on a fresh ubuntu install. Nothing should conflict here, so snap appears to have issues with initial installation on the 6469 build.

**Comment by stgraber** [comment]
I did see this behavior on one test system, this is pretty concerning as it's not something we have any control over... auto-connected interfaces are controlled by signed assertions from the store...

**Comment by stgraber** [comment]
That didn't help...

**Comment by stgraber** [comment]
But this does:
```
snap remove lxd
snap install lxd
```

And now all interfaces are connected...

**Comment by stgraber** [comment]
Filed a report at https://forum.snapcraft.io/t/auto-connected-interfaces-missing-on-initial-snap-install/4850
I'l continue to post details over there. Closing this issue on the LXD side as it's not anything we control on our end, this is a snapd or core snap bug.

**Comment by HW-Siew** [comment]
I am having the same issue, but my one is not fresh install. And, the line 
`sudo snap connect lxd:lxd-support core:lxd-support`

give me an error

'error: snap "lxd" has no plug named "lxd-support"'

**Comment by stgraber** [comment]
That'd be a different issue I think. In my case I could manually snap connect things and it certainly only applied to fresh installs.

Assuming you're using the stable channel, one thing that may help unstick things for you is:

    snap refresh lxd --channel=3.0/stable
    snap refresh lxd --channel=stable

That should cause two updates to happen and maybe fix those missing interfaces.

**Comment by HW-Siew** [comment]
Thanks!! The two commands are working! My lxd is back online again 👍 

Thanks again stgraber.
