### ISSUE TITLE
Faulty parsing of /etc/fstab

### ISSUE THREAD

**Issue by bk** [lxc/lxd#4407]
# Required information

 * Distribution: Debian
 * Distribution version: stretch (9.3)
 * System information:
   * Kernel version: 4.9.0-6-amd64
   * LXC version: included in snap package; seemingly 1.4.0
   * LXD version: 3.0.0 (snap build 6469)
   * Storage backend in use: zfs

# Issue description

Certain legitimate entries in `/etc/fstab` cause an error message to be emitted each time the `lxc` command is run. This applies to some fuse file systems, such as unionfs, but may also apply to others. An example of a line in fstab which causes this is:

    unionfs#/mnt/a=RO:/mnt/b=RW /mnt/c fuse cow,allow_other,_netdev 0 0

Apparently, the `#` is taken to start a comment, since the error message is: `2018/04/04 13:11:04.026913 system_key.go:117: cannot determine nfs usage in generateSystemKey: cannot parse /etc/fstab: expected between 3 and 6 fields, found 1`.

For most operations, the message is merely a nuisance, but when such a line is present in fstab it causes problems for `snap refresh` and has in at least one instance caused containers to become inaccessible after a snap package update (from build 6418 to 6469).

# Steps to reproduce

1. Add a line of the above kind to `/etc/fstab`.
2. Run a `lxc` subcommand.
3. Observe the emitted warning.

**Comment by stgraber** [comment]
Just did some grepping in source trees locally, this error is originating from snapd itself, not from LXD.

I'd recommend you open a forum topic about this at https://forum.snapcraft.io as that's currently the recommended way to interact with the snapd developers.

Please post the URL here so that anyone who runs into a similar issue can find it.

**Comment by brauner** [comment]
That error is not from LXD though is it? That looks like it is coming from snapd.

**Comment by stgraber** [comment]
https://github.com/snapcore/snapd/pull/4973

**Comment by bk** [comment]
The PR referenced by @stgraber has already been applied to master, fixing this issue - see snapcore/snapd@187de26821c03f5b024508d11a3ac804614b118e. Sorry for reporting this in the wrong place.
