### ISSUE TITLE
typo in container names exposes sqlite query language

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#441]
When attempting to issue commands that require a container name, if you provide an invalid name, lxc emits output from the search for a machine by that name.

Expected:
Common error message like:  No such container found: <container name used>

Actual:
```
% lxc start undefined-machine
error: sql: no rows in result set
```

**Comment by tych0** [comment]
On Mon, Mar 30, 2015 at 02:26:25PM -0700, raharper wrote:
> When attempting to issue commands that require a container name, if you provide an invalid name, lxc emits output from the search for a machine by that name.
> 
> Expected:
> Common error message like:  No such container found: <container name used>
> 
> Actual:
> ```
> % lxc start undefined-machine
> error: sql: no rows in result set
> ```

I've fixed at least one of these in,
514b55fa20a384b8da2777937c56cf1a94c6f1a5, we probably want to do
something similar everywhere else.
