### ISSUE TITLE
Lxc file pull doesn't pull the correct symlink file in container

### ISSUE THREAD

**Issue by HW-Siew** [lxc/lxd#4411]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-42-generic
   * LXC version: 3.0.0
   * LXD version: 3.0.0
   * Storage backend in use: zfs

# Issue description

I am trying to pull a symlink file in container to local machine. However, lxc file pull doesn't seem to be pulling the correct file from container like previously.  

# Steps to reproduce

 1. lxc launch ubuntu:x test
 2. lxc exec test -- sudo --login --user ubuntu
 3.     echo 'testing 123' | tee dummy.txt
 4.     ln -s dummy.txt ./dummy1.txt
 5.     exit
 6. lxc file pull test/home/ubuntu/dummy1.txt .
 7. cat dummmy1.txt
 8.  cat: dummy1.txt: No such file or directory

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
I'll take a look at this tomorrow morning. LXD 3.0 introduces support for transferring symlinks (as symlins) so I suspect it's something odd going on with that part of the code.

**Comment by stgraber** [comment]
Actually, I think `lxc file pull` is doing exactly what you asked it to do in this case, it's just the error looking a bit confusing:

```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc exec test -- sudo --login --user ubuntu
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@test:~$ echo 'testing 123' | tee dummy.txt
testing 123
ubuntu@test:~$ ln -s dummy.txt ./dummy1.txt
ubuntu@test:~$ ls -lh
total 1.0K
-rw-r--r-- 1 ubuntu ubuntu 12 Apr  5 21:52 dummy.txt
lrwxrwxrwx 1 ubuntu ubuntu  9 Apr  5 21:52 dummy1.txt -> dummy.txt
ubuntu@test:~$ logout
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc file pull test/home/ubuntu/dummy1.txt .
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ ls -lh dummy1.txt 
lrwxrwxrwx 1 stgraber domain admins 9 Apr  5 17:52 dummy1.txt -> dummy.txt
```

So whereas as it would mistakenly follow symlinks before, now it transfers the symlink properly.

**Comment by stgraber** [comment]
I think what we should do is allow for "-r" to mean in such cases that you want to follow the symlink.
So:
 - "lxc file pull test/home/ubuntu/dummy1.txt ." would download the symlink
 - "lxc file pull -r test/home/ubuntu/dummy1.txt ." would attempt to download the target (I say attempt because the symlink could be broken)
