### ISSUE TITLE
lxc commands failing with probable snap containment related error

### ISSUE THREAD

**Issue by stub42** [lxc/lxd#4417]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 3.0.0 (snap stable channel)
   * LXD version: 3.0.0 (snap stable channel)
   * Storage backend in use: zfs

# Issue description

After restarting my machine this morning, I find the lxc commands are failing:

```
$ lxc info
failed to create prefix path: /tmp/snap.rootfs_s5iLEy/var/lib/snapd/lib/vulkan/icd.d: Permission denied
```

I do have other snaps working on the system. Juju is working fine with the local provider, so the backend seems to be working. Its just the cli tool that seems to be having trouble.

I do get a matching containment error in /var/log/syslog:

```
Apr  6 13:22:43 localhost kernel: [ 3008.373824] audit: type=1400 audit(1522984963.706:262): apparmor="DENIED" operation="open" profile="/usr/lib/snapd/snap-confine" name="/tmp/snap.rootfs_NiS3tL/" pid=20444 comm="snap-confine" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

Snapd version info (stable channel):

```
snap    2.32+18.04
snapd   2.32+18.04
series  16
ubuntu  18.04
kernel  4.15.0-13-generic
```

Core snap is 16-2.31.2 (stable channel)

**Comment by stgraber** [comment]
Looks like one of the snapd problems, likely the one which causes all interfaces to be dropped on the floor...

https://forum.snapcraft.io/t/summary-of-core-lxd-refresh-bugs-discovered-on-4th-of-april-2018/4869/6

Ah, no, looking again, you're hitting the gl/vulkan one, see here:

https://forum.snapcraft.io/t/cannot-create-directory-tmp-snap-rootfs-var-lib-snapd-lib-gl32-permission-denied/4868/21

My workaround might help.

(Closing as not LXD's fault, unfortunately...)
