### ISSUE TITLE
lxd 3.0.0: can't add client.crt

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#4418]
## info
version: 3.0.0
package: snap
ubuntu 17.10

config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 62.210.152.13:8443
  - 10.90.123.8:8443
  - 172.20.11.1:8443
  - 172.20.10.1:8443
  - 172.20.12.1:8443
  - 172.17.0.1:8443
  - 10.8.0.1:8443
  - 10.8.0.1:8443
  - 10.99.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    [ .. ]
    -----END CERTIFICATE-----
  certificate_fingerprint: ef3e1e725cf80e73691d182fc5ca6f862eb5789208ba817d8d3a8f49cb7f2109
  driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-32-generic
  server: lxd
  server_pid: 6877
  server_version: 3.0.0
  storage: btrfs
  storage_version: "4.4"
  server_clustered: false
  server_name: sd-57286

# Issue description
Can't add certificate. lxd says it can't find the file:

 /tmp$ lxc config trust add client.crt 
Error: open client.crt: no such file or directory

while the file exists and is readable.

# Steps to reproduce

 1. Step one

verify the crt is readable:

/tmp$ cat client.crt 
-----BEGIN CERTIFICATE-----
[ .. ]
-----END CERTIFICATE-----

 2. Step two
/tmp$ lxc config trust add client.crt 
Error: open client.crt: no such file or directory

# Information to attach

**Comment by gaetanquentin** [comment]
resolved:

client.crt must be in ~/snap/lxd/current/.config

**Comment by stgraber** [comment]
Oh, actually it shouldn't have to be but we'll need to do a tiny tweak to the code to fix that one
