### ISSUE TITLE
Provide commit hashes of vendored dependencies

### ISSUE THREAD

**Issue by ganto** [lxc/lxd#4421]
I'm working on a proper RPM package of LXD that could be added to Fedora ganto/copr-lxd#6. While it became easier to build `lxd` thanks to the vendored dependencies, its still missing a list of which version of which packages were used to generate the distribution tarball. This would be required to properly generate a list of which go packages are bundled with the `lxd` RPM. See https://src.fedoraproject.org/rpms/origin/blob/master/f/origin.spec#_111 for an example.

Would it be possible to add this information to the distribution tarball?

**Comment by stgraber** [comment]
We should be able to have our `dist` target spit out the git rev of all repos.

**Comment by stgraber** [comment]
I have most of a prototype ready for a manifest file, will hopefully finish this later tomorrow (on vacation though).
