### ISSUE TITLE
Alias - "unknown shorthand flag: 'c' in -c"

### ISSUE THREAD

**Issue by 19wolf** [lxc/lxd#4423]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
  * driver: lxc
 * driver_version: 3.0.0
 * kernel: Linux
 * kernel_architecture: x86_64
 * kernel_version: 4.16.0-041600-generic
 * server: lxd
 * server_pid: 18724
 * server_version: 3.0.0
 * storage: btrfs
 * storage_version: "4.4"
 * server_clustered: false

# Issue description
Trying to alias `lxc list` to `lxc list -c ns46S` as given as an example in the `lxc alias add` help does not work

```
$ lxc alias add
Description:
  Add new aliases

Usage:
  lxc alias add <alias> <target> [flags]

Examples:
  **lxc alias add list list -c ns46S**
      Overwrite the "list" command to pass -c ns46S.

Global Flags:
      --debug         Show all debug messages
      --force-local   Force using the local unix socket
  -h, --help          Print help
  -v, --verbose       Show all information messages
      --version       Print version number
$ **lxc alias add list list -c ns46S**
Error: unknown shorthand flag: 'c' in -c
```

Edit: Seems no flags are working as they should 
```
$ lxc alias add delete delete -f
Error: unknown shorthand flag: 'f' in -f
$ lxc alias add del delete -f
Error: unknown shorthand flag: 'f' in -f
```

**Comment by stgraber** [comment]
You need to properly split the arguments.

**Comment by stgraber** [comment]
lxc alias add delete "delete -f"

**Comment by 19wolf** [comment]
Makes sense. I had literally copy-pasted the example line and it hadn't worked, so I assumed a bug.
