### ISSUE TITLE
lxd 3.0.0: config.yml reset and database empty

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#4427]
# problem

every remotes, certificates etc have disappeared, whereas i have done nothing.

# infos

config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificate_fingerprint: deb858c54df6cc8fced5fe565ec87f21824fc9265f47490ba39b642a8c2322b8
  driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-38-generic
  server: lxd
  server_pid: 6305
  server_version: 3.0.0
  storage: ""
  storage_version: ""
  server_clustered: false
  server_name: gquentin-ssd-t3

## steps to reproduce

1.lxc remote list
->empty

2. looking at ~/snap/lxd/current/.config/lxc/config.yml it has been rewritten today, abut why?

**Comment by gaetanquentin** [comment]
they are still in an old config file (february) : ./6492/.config/lxc/config.yml ...

**Comment by gaetanquentin** [comment]
i would say that something happened on 6 april:
lrwxrwxrwx 1 root root 13 avril  6 22:05 /snap/bin/lxd.lxc -> /usr/bin/snap


is there a way to trace snap activity?

**Comment by stgraber** [comment]
`snap changes` might have a record of what happened.

**Comment by gaetanquentin** [comment]
Identifiant  État  Descendance           Prêt                  Résumé
170          Done  2018-04-08T22:32:09Z  2018-04-08T22:32:09Z  Actualiser tous les paquets Snap :pas de mise à jour

not enough info so .

**Comment by stgraber** [comment]
Weird, would be nice to figure out what caused that... Was it a regular user or the root user?

**Comment by gaetanquentin** [comment]
regular, my all days user at work.

**Comment by gaetanquentin** [comment]
i boot my computer every day, each morning

**Comment by stgraber** [comment]
What do you have in `~/snap/lxd`? I believe snapd is supposed to be making some backups when it does something there...

**Comment by gaetanquentin** [comment]
today:
drwxr-xr-x 3 root root 4096 avril  9 09:21 6578
drwxr-xr-x 3 root root 4096 avril  9 09:21 6643
drwxr-xr-x 2 root root 4096 avril  9 09:16 common
lrwxrwxrwx 1 root root    4 avril 10 04:15 current -> 6643

**Comment by gaetanquentin** [comment]
ls -la ~/snap/lxd/
total 0
drwxr-xr-x 1 gaetanquentin-sfr gaetanquentin-sfr 1008 avril  9 09:24 .
drwxr-xr-x 1 gaetanquentin-sfr gaetanquentin-sfr  336 févr. 14 14:06 ..
drwxr-xr-x 1 gaetanquentin-sfr gaetanquentin-sfr  168 févr. 14 14:06 5866
drwxr-xr-x 1 gaetanquentin-sfr gaetanquentin-sfr  168 févr. 14 14:06 6418
drwxr-xr-x 1 gaetanquentin-sfr gaetanquentin-sfr  168 févr. 14 14:06 6492
drwxr-xr-x 1 gaetanquentin-sfr gaetanquentin-sfr  168 avril  9 09:24 6578
drwxr-xr-x 1 gaetanquentin-sfr gaetanquentin-sfr    0 févr. 14 14:06 common
lrwxrwxrwx 1 gaetanquentin-sfr gaetanquentin-sfr    4 avril  9 09:24 current -> 6578

**Comment by gaetanquentin** [comment]
gaetanquentin-sfr@gquentin-ssd-t3:~/snap$ find lxd -ls
  1804416      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr     1008 avril 10 09:23 lxd
  1804418      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr        0 févr. 14 14:06 lxd/common
  1834477      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr      168 févr. 14 14:06 lxd/5866
  1834478      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 févr. 14 14:06 lxd/5866/.config
  1834479      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr     1176 mars 30 10:47 lxd/5866/.config/lxc
  1834480     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr      733 févr. 23 13:29 lxd/5866/.config/lxc/config.yml
  1834481     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr        5 mars 29 11:52 lxd/5866/.config/lxc/cookies
  1834482     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1988 févr. 19 23:51 lxd/5866/.config/lxc/_client.crt
  1834483     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3247 févr. 19 23:51 lxd/5866/.config/lxc/_client.key
  1834484      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      544 févr. 23 13:29 lxd/5866/.config/lxc/servercerts
  1834485     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     2082 févr. 19 23:59 lxd/5866/.config/lxc/servercerts/quentinboxv3-vpn.crt
  1834486     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     2317 févr. 20 00:01 lxd/5866/.config/lxc/servercerts/local-vpn.crt
  1861781     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1915 févr. 23 13:29 lxd/5866/.config/lxc/servercerts/vipteam_lab.crt
  1834487     12 -rw-rw-r--   1 gaetanquentin-sfr gaetanquentin-sfr     2021 juin  2  2016 lxd/5866/.config/lxc/client.crt
  1834488     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3243 juin  2  2016 lxd/5866/.config/lxc/client.key
  2093198      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr      168 févr. 14 14:06 lxd/6492
  2093199      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 févr. 14 14:06 lxd/6492/.config
  2093200      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr     1176 avril  5 17:03 lxd/6492/.config/lxc
  2093201     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr      733 févr. 23 13:29 lxd/6492/.config/lxc/config.yml
  2093202     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr        5 avril  5 11:44 lxd/6492/.config/lxc/cookies
  2093203     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1988 févr. 19 23:51 lxd/6492/.config/lxc/_client.crt
  2093204     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3247 févr. 19 23:51 lxd/6492/.config/lxc/_client.key
  2093205      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      544 févr. 23 13:29 lxd/6492/.config/lxc/servercerts
  2093206     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     2082 févr. 19 23:59 lxd/6492/.config/lxc/servercerts/quentinboxv3-vpn.crt
  2093207     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     2317 févr. 20 00:01 lxd/6492/.config/lxc/servercerts/local-vpn.crt
  2093208     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1915 févr. 23 13:29 lxd/6492/.config/lxc/servercerts/vipteam_lab.crt
  2093209     12 -rw-rw-r--   1 gaetanquentin-sfr gaetanquentin-sfr     2021 juin  2  2016 lxd/6492/.config/lxc/client.crt
  2093210     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3243 juin  2  2016 lxd/6492/.config/lxc/client.key
  2123960      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril  9 09:24 lxd/6578
  2123962      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril  9 09:24 lxd/6578/.config
  2123963      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      840 avril 10 08:57 lxd/6578/.config/lxc
  2124684     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr      518 avril  9 13:37 lxd/6578/.config/lxc/config.yml
  2124686     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr        5 avril 10 08:57 lxd/6578/.config/lxc/cookies
  2125394     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1988 avril  9 13:35 lxd/6578/.config/lxc/client.crt
  2125395     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3247 avril  9 13:35 lxd/6578/.config/lxc/client.key
  2125400      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril  9 13:36 lxd/6578/.config/lxc/servercerts
  2125401     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1915 avril  9 13:36 lxd/6578/.config/lxc/servercerts/vipteam_lab.crt
  2128863      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril  9 09:24 lxd/6643
  2128864      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril  9 09:24 lxd/6643/.config
  2128865      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr     1008 avril 10 14:26 lxd/6643/.config/lxc
  2128866     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr      518 avril  9 13:37 lxd/6643/.config/lxc/config.yml
  2128867     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr        5 avril 10 08:57 lxd/6643/.config/lxc/cookies
  2128868     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1988 avril  9 13:35 lxd/6643/.config/lxc/client.crt
  2128869     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3247 avril  9 13:35 lxd/6643/.config/lxc/client.key
  2128870      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril  9 13:36 lxd/6643/.config/lxc/servercerts
  2128871     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1915 avril  9 13:36 lxd/6643/.config/lxc/servercerts/vipteam_lab.crt
  2129175      0 lrwxrwxrwx   1 gaetanquentin-sfr gaetanquentin-sfr        4 avril 10 09:23 lxd/current -> 6643

**Comment by stgraber** [comment]
Ok, so looks like your config and certificates have been backed up properly in the past, but then didn't get carried forward during a snap update?

I suspect you can probably copy the entire content of one of those older directories into your current one, which would get you back to a working configuration and certificates.

**Comment by gaetanquentin** [comment]
i think it is thee root cause , yes.

have already tried yesterday to copy all: but some remotes was not ok, because their changed their configuration was changed.

it's ok today, all is working back, since i recreated this remote.

**Comment by stgraber** [comment]
Ok. I'll close this issue since it's our of LXD's control, but if you see it happen again somewhere, please comment here and include the `snap changes` output as well as the entire output of `journalctl` at that time. That'll hopefully include enough information to figure out what happened to snapd.

**Comment by gaetanquentin** [comment]
Again:

1: like if it was the first time i use lxc ;-(

gaetanquentin-sfr@gquentin-ssd-t3:~$ lxc start Wine
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:16.04

2. snap did something:
drwxr-xr-x 1 gaetanquentin-sfr gaetanquentin-sfr  168 avril  9 09:24 6643
drwxr-xr-x 1 gaetanquentin-sfr gaetanquentin-sfr  168 avril 19 08:23 6729
drwxr-xr-x 1 gaetanquentin-sfr gaetanquentin-sfr    0 févr. 14 14:06 common
lrwxrwxrwx 1 gaetanquentin-sfr gaetanquentin-sfr    4 avril 19 08:23 current -> 6729

3. My remotes gone away:
lxc remote list
 -> only standard ones

4.~/snap$ find lxd -ls

  1804416      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr     1176 avril 19 08:23 lxd
  1804418      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr        0 févr. 14 14:06 lxd/common
  1834477      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr      168 févr. 14 14:06 lxd/5866
  1834478      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 févr. 14 14:06 lxd/5866/.config
  1834479      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr     1176 mars 30 10:47 lxd/5866/.config/lxc
  1834480     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr      733 févr. 23 13:29 lxd/5866/.config/lxc/config.yml
  1834481     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr        5 mars 29 11:52 lxd/5866/.config/lxc/cookies
  1834482     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1988 févr. 19 23:51 lxd/5866/.config/lxc/_client.crt
  1834483     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3247 févr. 19 23:51 lxd/5866/.config/lxc/_client.key
  1834484      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      544 févr. 23 13:29 lxd/5866/.config/lxc/servercerts
  1834485     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     2082 févr. 19 23:59 lxd/5866/.config/lxc/servercerts/quentinboxv3-vpn.crt
  1834486     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     2317 févr. 20 00:01 lxd/5866/.config/lxc/servercerts/local-vpn.crt
  1861781     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1915 févr. 23 13:29 lxd/5866/.config/lxc/servercerts/vipteam_lab.crt
  1834487     12 -rw-rw-r--   1 gaetanquentin-sfr gaetanquentin-sfr     2021 juin  2  2016 lxd/5866/.config/lxc/client.crt
  1834488     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3243 juin  2  2016 lxd/5866/.config/lxc/client.key
  2093198      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr      168 févr. 14 14:06 lxd/6492
  2093199      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 févr. 14 14:06 lxd/6492/.config
  2093200      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr     1176 avril  5 17:03 lxd/6492/.config/lxc
  2093201     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr      733 févr. 23 13:29 lxd/6492/.config/lxc/config.yml
  2093202     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr        5 avril  5 11:44 lxd/6492/.config/lxc/cookies
  2093203     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1988 févr. 19 23:51 lxd/6492/.config/lxc/_client.crt
  2093204     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3247 févr. 19 23:51 lxd/6492/.config/lxc/_client.key
  2093205      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      544 févr. 23 13:29 lxd/6492/.config/lxc/servercerts
  2093206     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     2082 févr. 19 23:59 lxd/6492/.config/lxc/servercerts/quentinboxv3-vpn.crt
  2093207     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     2317 févr. 20 00:01 lxd/6492/.config/lxc/servercerts/local-vpn.crt
  2093208     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1915 févr. 23 13:29 lxd/6492/.config/lxc/servercerts/vipteam_lab.crt
  2093209     12 -rw-rw-r--   1 gaetanquentin-sfr gaetanquentin-sfr     2021 juin  2  2016 lxd/6492/.config/lxc/client.crt
  2093210     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3243 juin  2  2016 lxd/6492/.config/lxc/client.key
  2123960      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril  9 09:24 lxd/6578
  2123962      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril  9 09:24 lxd/6578/.config
  2123963      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      840 avril 10 08:57 lxd/6578/.config/lxc
  2124684     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr      518 avril  9 13:37 lxd/6578/.config/lxc/config.yml
  2124686     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr        5 avril 10 08:57 lxd/6578/.config/lxc/cookies
  2125394     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1988 avril  9 13:35 lxd/6578/.config/lxc/client.crt
  2125395     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3247 avril  9 13:35 lxd/6578/.config/lxc/client.key
  2125400      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril  9 13:36 lxd/6578/.config/lxc/servercerts
  2125401     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1915 avril  9 13:36 lxd/6578/.config/lxc/servercerts/vipteam_lab.crt
  2128863      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril  9 09:24 lxd/6643
  2128864      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      336 avril 10 17:36 lxd/6643/.config
  2128865      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      840 avril 10 17:32 lxd/6643/.config/lxc-backup
  2128866     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr      518 avril  9 13:37 lxd/6643/.config/lxc-backup/config.yml
  2128867     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr        5 avril 10 17:32 lxd/6643/.config/lxc-backup/cookies
  2128868     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1988 avril  9 13:35 lxd/6643/.config/lxc-backup/client.crt
  2128869     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3247 avril  9 13:35 lxd/6643/.config/lxc-backup/client.key
  2128870      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril  9 13:36 lxd/6643/.config/lxc-backup/servercerts
  2128871     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1915 avril  9 13:36 lxd/6643/.config/lxc-backup/servercerts/vipteam_lab.crt
  2133991      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr     1176 avril 18 10:28 lxd/6643/.config/lxc
  2133992     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr      733 févr. 23 13:29 lxd/6643/.config/lxc/config.yml
  2133993     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr        5 avril 17 16:02 lxd/6643/.config/lxc/cookies
  2133994     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1988 févr. 19 23:51 lxd/6643/.config/lxc/_client.crt
  2133995     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3247 févr. 19 23:51 lxd/6643/.config/lxc/_client.key
  2133996      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      544 févr. 23 13:29 lxd/6643/.config/lxc/servercerts
  2133997     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     2082 févr. 19 23:59 lxd/6643/.config/lxc/servercerts/quentinboxv3-vpn.crt
  2133998     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     2317 févr. 20 00:01 lxd/6643/.config/lxc/servercerts/local-vpn.crt
  2133999     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr     1915 févr. 23 13:29 lxd/6643/.config/lxc/servercerts/vipteam_lab.crt
  2134000     12 -rw-rw-r--   1 gaetanquentin-sfr gaetanquentin-sfr     2021 juin  2  2016 lxd/6643/.config/lxc/client.crt
  2134001     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr     3243 juin  2  2016 lxd/6643/.config/lxc/client.key
  2204468      0 drwxr-xr-x   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril 19 08:23 lxd/6729
  2204470      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      168 avril 19 08:23 lxd/6729/.config
  2204471      0 drwxr-x---   1 gaetanquentin-sfr gaetanquentin-sfr      504 avril 19 08:24 lxd/6729/.config/lxc
  2204472     12 -rw-r--r--   1 gaetanquentin-sfr gaetanquentin-sfr      403 avril 19 08:23 lxd/6729/.config/lxc/config.yml
  2204474     12 -rw-------   1 gaetanquentin-sfr gaetanquentin-sfr        5 avril 19 08:24 lxd/6729/.config/lxc/cookies
  2204469      0 lrwxrwxrwx   1 gaetanquentin-sfr gaetanquentin-sfr        4 avril 19 08:23 lxd/current -> 6729

**Comment by gaetanquentin** [comment]
lxc list
+------+---------+----------------------+------+------------+-----------+
| NAME |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+----------------------+------+------------+-----------+
| Wine | RUNNING | 172.16.10.210 (eth0) |      | PERSISTENT | 0         |
+------+---------+----------------------+------+------------+-----------+

sudo btrfs sub list / | grep Wine
 -> nothing


ls -la /var/snap/lxd/common/lxd/storage-pools/default/
total 0
drwx--x--x 1 root root  0 avril 17 14:47 .
drwx--x--x 1 root root 14 avril 17 14:47 ..


ls -la /var/snap/lxd/common/lxd/containers/
Wine -> /var/snap/lxd/common/lxd/storage-pools/default/containers/Wine

bad link ...

?

**Comment by stgraber** [comment]
`/var/snap/lxd/common/lxd/storage-pools/default/` being empty is expected as it's likely got some zfs, btrfs or other storage backend mounted over it inside the private mount namespace of the LXD snap.

**Comment by stgraber** [comment]
So that shows a clear issue with snapd on your system... it's definitely creating a new empty snap user directory rather than migrating the previous one over as it should have...

I guess running:
```
rm -rf ~/snap/lxd/6729
cp -r ~/snap/lxd/6643 ~/snap/lxd/6729
```

Will fix things for you again....

Would you mind reporting this issue at https://forum.snapcraft.io?

**Comment by gaetanquentin** [comment]
so where are the containers now? since there is no btrfs subvolume?

**Comment by stgraber** [comment]
@gaetanquentin they are there and mounted, you just don't see the mountpoint.

You can probably see them at the rather long: `/var/snap/lxd/common/mntns/var/snap/lxd/common/lxd/storage-pools/default/`

**Comment by stgraber** [comment]
`/var/snap/lxd/common/mntns` is a symlink that points to `/` inside of the LXD snap's mount namespace so you can see how things look like from its point of view.

**Comment by gaetanquentin** [comment]
i don't understand why i can see the container here:
sudo ls -la /var/snap/lxd/common/mntns/var/snap/lxd/common/lxd/storage-pools/default/containers/

but not here:
sudo ls -la /var/snap/lxd/common/lxd/storage-pools/default/containers/
ls: impossible d'accéder à '/var/snap/lxd/common/lxd/storage-pools/default/containers/': Aucun fichier ou dossier de ce type


and why i can't see their btrfs subvol anymore ...
sudo btrfs sub list /:
 -> nothing about lxd


on another lxd 3.0.0/btrfs host , i cat see well btrfs subvolumes l:

btrfs sub list /:

ID 3356 gen 1415953 top level 3332 path var/snap/lxd/common/lxd/storage-pools/default/containers/openshift-origin/rootfs/var/lib/docker/btrfs/subvolumes/3941f611bc496433ea3bfff97702423d3200aa835ddda47610dab591cf260950
ID 3373 gen 1434173 top level 2213 path var/snap/lxd/common/lxd/storage-pools/default/snapshots/Wine/snap0
ID 3378 gen 1443414 top level 2213 path var/snap/lxd/common/lxd/storage-pools/default/containers/test

and there are on the classic path:
/var/snap/lxd/common/lxd/storage-pools/default/containers/

**Comment by gaetanquentin** [comment]
ok. just understood how the new storage system was working. so i badly created a btrfs storage in a single file.

Will wait for https://github.com/lxc/lxd/issues/4444 to migrate locally to a new storage pool.

**Comment by stgraber** [comment]
For your earlier question, that's because everything happens in a mount namespace, your shell isn't in that mount namespace and so can't see the mounted btrfs filesystem. The `/var/snap/lxd/common/mntns` trick lets you peak into that mount namespace but that's still unlikely to be enough for the `btrfs` tool itself to be happy :)

One way to get a shell entirely in the namespace is to run something like `nsenter -t $(pgrep daemon.start) -m` from that sub-shell you'll see `/var/snap/lxd/common/lxd/storage-pools/default` as LXD sees it and I'd expect tools like `btrfs` to also better see subvolumes.

**Comment by stgraber** [comment]
The normal way to delete Wine/snap0 would be `lxc delete Wine/snap0` which assumes that you do have a `Wine` container with a `snap0` snapshot.

If you don't, then something went wrong that caused some leftover DB entry. In which case a bit of DB surgery would be needed to remove it.

**Comment by gaetanquentin** [comment]
Nothing to delete and can't delete storage pool because there is old container volume inside.
Whick database to modify?  /var/snap/lxd/common/lxd/lxd.db looks pretty empty.

**Comment by gaetanquentin** [comment]
if i create a storage pool outside the snap namespace, is it a problem?
Ex:
lxc storage create pool1 btrfs source=/mnt/ROOT/@lxd

**Comment by stgraber** [comment]
What's the full output of `lxc storage volume list` for that pool?
And what do you get when running `lxd sql "SELECT * FROM storage_pools;"` and `lxd sql "SELECT * FROM storage_volumes;"`?

**Comment by gaetanquentin** [comment]
lxc storage volume list default 
+-----------+-------------+-------------+---------+
|   TYPE    |    NAME     | DESCRIPTION | USED BY |
+-----------+-------------+-------------+---------+
| container | Wine2/snap1 |             | 1       |
+-----------+-------------+-------------+---------+

lxd sql "SELECT * FROM storage_pools;"
+------------+---------+--------+-------------+------------+
| id         | name    | driver | description | state      |
+------------+---------+--------+-------------+------------+
| 1          | default | btrfs  |             | 1          |
| 2          | pool1   | btrfs  |             | 1          |
+------------+---------+--------+-------------+------------+

lxd sql "SELECT * FROM storage_volumes;"
+------------+-------------+-----------------+------------+------------+-------------+
| id         | name        | storage_pool_id | node_id    | type       | description |
+------------+-------------+-----------------+------------+------------+-------------+
| 8          | Wine2/snap1 | 1               | 1          | 0          |             |
| 45         | Wine        | 2               | 1          | 0          |             |
+------------+-------------+-----------------+------------+------------+-------------+

**Comment by stgraber** [comment]
Ok, so yeah, it's certainly confused :)

```lxd sql "DELETE FROM storage_volumes WHERE id=8;``` should fix that for you.

**Comment by gaetanquentin** [comment]
ok it works. thanks.
