### ISSUE TITLE
lxd 3.0.0: client.crt / client.key missing. how to force lxc to regenerate it?

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#4428]
client.crt / client.key are missing  in ~/snap/lxd/current/.config/lxc with lxd 3.0.0 since last snap actions (which ones, i don't know)

and lxc is not regenerate them: how to force it to generate it?

**Comment by stgraber** [comment]
Adding a remote with `lxc remote add` would cause the client to regenerate them. It's odd that those files would have been removed without the config.yml also getting removed in the process...

I believe a `snap remove` might wipe ~/snap/lxd entirely, but having it partially emptied would be new.

**Comment by gaetanquentin** [comment]
the config.yml has been reset. all remotes disappeared.

as said in https://github.com/lxc/lxd/issues/4427#issuecomment-379720667 , snap did something thar reseted lxc user configuration.

it said when i logged in  then that 'it was the first time i was using lxc, something like that. so i think it regenerated the config.yml

**Comment by stgraber** [comment]
Ok, anyway, to regenerate a certificate, adding a remote will generate it.

Closing this issue in favor of the other one you filled so we can hopefully figure out why snapd wiped the user config.
