### ISSUE TITLE
lxd service fails to restart, containers can't start

### ISSUE THREAD

**Issue by ubojan** [lxc/lxd#4430]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.4 LTS
 * The output of "lxc info" or if that fails:

config:
  core.https_address: 10.240.0.81
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.240.0.81:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFdDCCA1ygAwIBAgIRAJbuNxryc4lDBLSXo06goFMwDQYJKoZIhvcNAQELBQAw
    RTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzElMCMGA1UEAwwccm9vdEBs
    eGQtYXNpYS1ub3J0aGVhc3QxLTMwMTAeFw0xODAxMTAxNDQ1MjhaFw0yODAxMDgx
    NDQ1MjhaMEUxHDAaBgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxJTAjBgNVBAMM
    HHJvb3RAbHhkLWFzaWEtbm9ydGhlYXN0MS0zMDEwggIiMA0GCSqGSIb3DQEBAQUA
    A4ICDwAwggIKAoICAQDXbGMKd/r0ScHH8gQdEqCXjVJC9opSFUjnXZ76bRUq3qn0
    5lXpffjYqNiRQ/QOt8UnEJuyv8ciRWyjBhSP3muXQZNjdaQCdhG/R2kR5xICQ8eK
    /GF2ZsxgpOMmK2k2kX0+oh5sm7yHGBHWMWbln61xFHIyZIjXO5XY/1BAeCvlSEm7
    RQXLAi7i7lp/nDkjKZtDzMuvX8Gz1935UaYmd1zSZnBVkMZhHuq2WJtLjoQHwvUM
    AOy+I7E5t5vtqVYmlcEtoZGh2CeiK2gMd5L+Vg/dPihzAv2jdeZb6thhP/WBVrIt
    HUN4LbRH9aBBOrxwJ4YCv2HD4Xk8H1pYV1VX+GsB/YGl6/ihZIt2fVsMyvdg73pk
    Y83q7pQ631COz7UPzkacINJhU19TFMvq2/DKMEe0l4SkoCTOvBhKzOqajxehfRH0
    WqhYW///2OAZh88AsmLmACwco8Og90Nh33x42JTjV+kvgDUnf9ngKNMP/gOH3twr
    H+vPLbm+0MLpAOpodh8DNw8g9eEriIYO2+KY4K/XD24ieofcIxgBBS5jzueuUJ5U
    DW7yV6i91D4wwQtHRaFRBtF/n+NZ49jRmmuomhbp8eCPxme8jMPcZ8u2/frkaOIW
    L7p4AyWyzAvcww0mdFmftFFXpCKGsxsP9ke1DKv0NbPoi9jxIXq/y5Ccy7vCzwID
    AQABo18wXTAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYD
    VR0TAQH/BAIwADAoBgNVHREEITAfghdseGQtYXNpYS1ub3J0aGVhc3QxLTMwMYcE
    CvAAUTANBgkqhkiG9w0BAQsFAAOCAgEAtScyVZVkiKl3Rgft3UCymTdgQEKfEykD
    dkC2dsQF2UwNuWCaBF47cmc86cCTUCrGc2KhCkkC1goMcLbTANHyfpQyZq1pbRMC
    FjjxDtLeh3XZAf7la2d6BCOGE2YH5xL0v2WlCuKySn83orR2fFVwtbX0DZfgfCbZ
    mYTnYAieOHXb+1GRGMW1SdXkAnfpCS+M/hTqqv9zYel5Fc24gA1qs2zGdodU1z5/
    JvGnBUZ3jb8U79WbeKQmYxs5OJ4YxvrsOK4kEZr4GWETk8ngZFDPIxnf3ARdyIpw
    1HAsa9mWH73eZ8gGded2Kh0qJ+9Fh4n377u6dGLCeR2aF1HRt3ZFULYgJxDXNCQx
    K7HwFyF80uso/12o4N+ckOf/H1QwIXuKkpHrzRz1jpTgOfQG4O35itB7k1u0YoFd
    3TAi3iK1L5WMDewLe+nlCNYyHfmVNlDazcu+lyg0d4BM8FISt0rPWxxzIvzUyRkh
    2jXZTj9Nut3TOQcPo1syhza6TWBPPsICQ5yBXAihL/iIkxdesC4L/hDredNIqFUY
    HktUDftj7kzBksapn3mL8eGMWSRZpz+Me71Xoro42n9UxqE4e186EwrS2Ums8nM7
    vlN7BVCmeilfQtPJWdaInOA7uAvX3zzqPgyGNjl65QnHqaXTtaZ9UBNR261/Q2lD
    B2j7NBl6MJg=
    -----END CERTIFICATE-----
  certificate_fingerprint: 1286a8f142c85e53e89ccc8fe67eef757f107c32b92f389b8589268944ed7089
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-1006-gcp
  server: lxd
  server_pid: 26002
  server_version: "2.21"
  storage: zfs
  storage_version: 0.7.5-0york1~16.04

   * Kernel version: 4.13.0-1006-gcp (it's Google Cloud compute engine instance)
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: zfs

# Issue description

Container is created successfully, but cannot be started (when I run lxc start on container, command never completes). When I restart lxd service, command never completes as well. lxd service output is at the bottom of report (status: activating). Server reboot is the only way to resolve the issue.

# Steps to reproduce

I am not aware of steps that can reproduce the issue. It just happens randomly.

# Information to attach

 - [x] syslog output

Apr  9 10:43:18 lxd-asia-northeast1-301 systemd[1]: Stopping LXD - main daemon...
Apr  9 10:43:43 lxd-asia-northeast1-301 systemd[1]: Stopped LXD - main daemon.
Apr  9 10:43:43 lxd-asia-northeast1-301 systemd[1]: Starting LXD - main daemon...
Apr  9 10:53:43 lxd-asia-northeast1-301 lxd[112091]: error: LXD still not running after 600s timeout.
Apr  9 10:53:43 lxd-asia-northeast1-301 systemd[1]: lxd.service: Control process exited, code=exited status=1
Apr  9 10:53:43 lxd-asia-northeast1-301 systemd[1]: Failed to start LXD - main daemon.
Apr  9 10:53:43 lxd-asia-northeast1-301 systemd[1]: lxd.service: Unit entered failed state.
Apr  9 10:53:43 lxd-asia-northeast1-301 systemd[1]: lxd.service: Failed with result 'exit-code'.
Apr  9 10:53:43 lxd-asia-northeast1-301 systemd[1]: lxd.service: Service hold-off time over, scheduling restart.
Apr  9 10:53:43 lxd-asia-northeast1-301 systemd[1]: Stopped LXD - main daemon.
Apr  9 10:53:43 lxd-asia-northeast1-301 systemd[1]: Starting LXD - main daemon...
Apr  9 11:03:43 lxd-asia-northeast1-301 lxd[127645]: error: LXD still not running after 600s timeout.
Apr  9 11:03:43 lxd-asia-northeast1-301 systemd[1]: lxd.service: Start-post operation timed out. Stopping.
Apr  9 11:03:43 lxd-asia-northeast1-301 systemd[1]: lxd.service: Control process exited, code=exited status=1
Apr  9 11:03:43 lxd-asia-northeast1-301 systemd[1]: Failed to start LXD - main daemon.
Apr  9 11:03:43 lxd-asia-northeast1-301 systemd[1]: lxd.service: Unit entered failed state.
Apr  9 11:03:43 lxd-asia-northeast1-301 systemd[1]: lxd.service: Failed with result 'exit-code'.
Apr  9 11:03:44 lxd-asia-northeast1-301 systemd[1]: lxd.service: Service hold-off time over, scheduling restart.
Apr  9 11:03:44 lxd-asia-northeast1-301 systemd[1]: Stopped LXD - main daemon.
Apr  9 11:03:44 lxd-asia-northeast1-301 systemd[1]: Starting LXD - main daemon...

 - [x] Container log (`lxc info NAME --show-log`)

~# lxc info zZi-tokyo  --show-log
error: Monitor is hung

 - [x] Container configuration (`lxc config show NAME --expanded`)

~# lxc config show zZi-tokyo  --expanded
error: Monitor is hung

 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

ephemeral=false lvl=info msg="Creating container" name=zZi-tokyo t=2018-04-09T09:44:46+0000
ephemeral=false lvl=info msg="Created container" name=zZi-tokyo t=2018-04-09T09:44:46+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=zZi-tokyo t=2018-04-09T09:44:47+0000
action=start created=2018-04-09T09:44:46+0000 ephemeral=false lvl=info msg="Starting container" name=zZi-tokyo stateful=false t=2018-04-09T09:44:47+0000 used=1970-01-01T00:00:00+0000
lvl=info msg="Received 'terminated signal', exiting." t=2018-04-09T10:43:18+0000
lvl=info msg="Stopping REST API handler:" t=2018-04-09T10:43:18+0000
lvl=info msg=" - closing socket" socket=10.240.0.81:8443 t=2018-04-09T10:43:18+0000
lvl=info msg=" - closing socket" socket=/var/lib/lxd/unix.socket t=2018-04-09T10:43:18+0000
lvl=info msg="Stopping /dev/lxd handler" t=2018-04-09T10:43:18+0000
lvl=info msg=" - closing socket" socket=/var/lib/lxd/devlxd/sock t=2018-04-09T10:43:18+0000
lvl=info msg="Closing the database" t=2018-04-09T10:43:43+0000
lvl=info msg="Saving simplestreams cache" t=2018-04-09T10:43:43+0000
lvl=info msg="Saved simplestreams cache" t=2018-04-09T10:43:43+0000
lvl=info msg="LXD 2.21 is starting in normal mode" path=/var/lib/lxd t=2018-04-09T10:43:43+0000
lvl=info msg="Kernel uid/gid map:" t=2018-04-09T10:43:43+0000
lvl=info msg=" - u 0 0 4294967295" t=2018-04-09T10:43:43+0000
lvl=info msg=" - g 0 0 4294967295" t=2018-04-09T10:43:43+0000
lvl=info msg="Configured LXD uid/gid map:" t=2018-04-09T10:43:43+0000
lvl=info msg=" - u 0 100000 65536" t=2018-04-09T10:43:43+0000
lvl=info msg=" - g 0 100000 65536" t=2018-04-09T10:43:43+0000
lvl=info msg="LXD is socket activated" t=2018-04-09T10:43:44+0000
lvl=info msg="Starting /dev/lxd handler:" t=2018-04-09T10:43:44+0000
lvl=info msg=" - binding devlxd socket" socket=/var/lib/lxd/devlxd/sock t=2018-04-09T10:43:44+0000
lvl=info msg="REST API daemon:" t=2018-04-09T10:43:44+0000
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2018-04-09T10:43:44+0000
lvl=info msg=" - binding TCP socket" socket=10.240.0.81:8443 t=2018-04-09T10:43:44+0000
lvl=info msg="Pruning expired images" t=2018-04-09T10:43:44+0000
lvl=info msg="Done pruning expired images" t=2018-04-09T10:43:44+0000
lvl=info msg="Expiring log files" t=2018-04-09T10:43:44+0000
lvl=info msg="Updating instance types" t=2018-04-09T10:43:44+0000
lvl=info msg="Updating images" t=2018-04-09T10:43:44+0000
lvl=info msg="Done updating images" t=2018-04-09T10:43:44+0000
lvl=info msg="Done expiring log files" t=2018-04-09T10:43:44+0000
lvl=info msg="Done updating instance types" t=2018-04-09T10:43:49+0000
lvl=info msg="LXD 2.21 is starting in normal mode" path=/var/lib/lxd t=2018-04-09T10:53:43+0000
lvl=info msg="Kernel uid/gid map:" t=2018-04-09T10:53:43+0000
lvl=info msg=" - u 0 0 4294967295" t=2018-04-09T10:53:43+0000
lvl=info msg=" - g 0 0 4294967295" t=2018-04-09T10:53:43+0000
lvl=info msg="Configured LXD uid/gid map:" t=2018-04-09T10:53:43+0000
lvl=info msg=" - u 0 100000 65536" t=2018-04-09T10:53:43+0000
lvl=info msg=" - g 0 100000 65536" t=2018-04-09T10:53:43+0000
lvl=info msg="LXD is socket activated" t=2018-04-09T10:53:44+0000
lvl=info msg="Starting /dev/lxd handler:" t=2018-04-09T10:53:44+0000
lvl=info msg=" - binding devlxd socket" socket=/var/lib/lxd/devlxd/sock t=2018-04-09T10:53:44+0000
lvl=info msg="REST API daemon:" t=2018-04-09T10:53:44+0000
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2018-04-09T10:53:44+0000
lvl=info msg=" - binding TCP socket" socket=10.240.0.81:8443 t=2018-04-09T10:53:44+0000
lvl=info msg="Pruning expired images" t=2018-04-09T10:53:44+0000
lvl=info msg="Done pruning expired images" t=2018-04-09T10:53:44+0000
lvl=info msg="Expiring log files" t=2018-04-09T10:53:44+0000
lvl=info msg="Updating instance types" t=2018-04-09T10:53:44+0000
lvl=info msg="Updating images" t=2018-04-09T10:53:44+0000
lvl=info msg="Done updating images" t=2018-04-09T10:53:44+0000
lvl=info msg="Done expiring log files" t=2018-04-09T10:53:44+0000
lvl=info msg="Done updating instance types" t=2018-04-09T10:53:49+0000
lvl=info msg="LXD 2.21 is starting in normal mode" path=/var/lib/lxd t=2018-04-09T11:03:44+0000
lvl=info msg="Kernel uid/gid map:" t=2018-04-09T11:03:44+0000
lvl=info msg=" - u 0 0 4294967295" t=2018-04-09T11:03:44+0000
lvl=info msg=" - g 0 0 4294967295" t=2018-04-09T11:03:44+0000
lvl=info msg="Configured LXD uid/gid map:" t=2018-04-09T11:03:44+0000
lvl=info msg=" - u 0 100000 65536" t=2018-04-09T11:03:44+0000
lvl=info msg=" - g 0 100000 65536" t=2018-04-09T11:03:44+0000
lvl=info msg="LXD is socket activated" t=2018-04-09T11:03:44+0000
lvl=info msg="Starting /dev/lxd handler:" t=2018-04-09T11:03:44+0000
lvl=info msg=" - binding devlxd socket" socket=/var/lib/lxd/devlxd/sock t=2018-04-09T11:03:44+0000
lvl=info msg="REST API daemon:" t=2018-04-09T11:03:44+0000
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2018-04-09T11:03:44+0000
lvl=info msg=" - binding TCP socket" socket=10.240.0.81:8443 t=2018-04-09T11:03:44+0000
lvl=info msg="Pruning expired images" t=2018-04-09T11:03:44+0000
lvl=info msg="Done pruning expired images" t=2018-04-09T11:03:44+0000
lvl=info msg="Expiring log files" t=2018-04-09T11:03:44+0000
lvl=info msg="Updating images" t=2018-04-09T11:03:44+0000
lvl=info msg="Updating instance types" t=2018-04-09T11:03:44+0000
lvl=info msg="Done updating images" t=2018-04-09T11:03:44+0000
lvl=info msg="Done expiring log files" t=2018-04-09T11:03:44+0000
lvl=info msg="Done updating instance types" t=2018-04-09T11:03:50+0000
lvl=warn msg="ZFS returned EBUSY while \"/var/lib/lxd/storage-pools/default/containers/yIr-se\" is actually not a mountpoint." t=2018-04-09T11:04:09+0000

 - [x] Output of lxd service status

~# systemctl status lxd
● lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: activating (start-post) since Mon 2018-04-09 12:53:46 UTC; 1min 41s ago
     Docs: man:lxd(1)
  Process: 55944 ExecStartPre=/usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load (code=exited, status=0/SUCCESS)
 Main PID: 55954 (lxd);         : 55955 (lxd)
    Tasks: 155
   Memory: 310.8M
      CPU: 1.112s
   CGroup: /system.slice/lxd.service
           ├─  1057 [lxc monitor] /var/lib/lxd/containers jHa-aaa
           ├─  3210 [lxc monitor] /var/lib/lxd/containers AVA-aaa
           ├─  3523 [lxc monitor] /var/lib/lxd/containers DmF-aaa
           ├─  4396 [lxc monitor] /var/lib/lxd/containers GRD-aaa
           ├─  4729 [lxc monitor] /var/lib/lxd/containers yYV-aaa
           ├─  4789 [lxc monitor] /var/lib/lxd/containers IdN-aaa
           ├─  5602 [lxc monitor] /var/lib/lxd/containers GVk-aaa
           ├─  6287 [lxc monitor] /var/lib/lxd/containers OCf-aaa
           ├─  7335 [lxc monitor] /var/lib/lxd/containers HJh-aaa
           ├─  7359 [lxc monitor] /var/lib/lxd/containers UWW-aaa

**Comment by stgraber** [comment]
Try killing any leftover lxc-monitord processes. If there's none or if that doesn't help, please include the output of `dmesg`.

**Comment by stgraber** [comment]
Good. It's a known issue that lxc-monitord could get stuck. The latest LXC releaes (2.0.9, 2.1 and 3.0) all have the fix for it but we're yet to get that into Ubuntu 16.04 as a SRU, hopefully we can get that sorted soon.
