### ISSUE TITLE
custom idmaps documentation incorrect

### ISSUE THREAD

**Issue by stub42** [lxc/lxd#4437]
# Issue description

On https://lxd.readthedocs.io/en/latest/userns-idmap/ under custom idmaps:

> LXD also supports customizing bits of the idmap, e.g. to allow users to bind mount parts of the host's filesystem into a container without the need for any uid-shifting filesystem. The per-container configuration key for this is raw.idmap, and looks like:
> 
> both 1000 1000
> uid 50-60 500-510
> gid 10000-110000 10000-20000
> 
> The first line configures both the uid and gid 1000 on the host to map to uid 1000 inside the container (this can be used for example to bind mount a user's home directory into a container).
> 
> The second and third lines map only the uid or gid ranges into the container, respectively. The second entry per line is the source id, i.e. the id on the host, and the third entry is the range inside the container. These ranges must be the same size.
> 
> This property requires a container reboot to take effect.

The second last paragraph claims the second parameter is the id on the host and the third entry the range inside the container, which seems to be the wrong way around when I test.

The second last paragraph states the ranges must be the same size, but the 3rd line of the idmap example has ranges that are not the same size.

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc init ubuntu:16.04 test
Creating test
stgraber@castiana:~$ mkdir /tmp/blah
stgraber@castiana:~$ lxc config device add test blah disk path=/mnt source=/tmp/blah
Device blah added to test
stgraber@castiana:~$ touch /tmp/blah/a
stgraber@castiana:~$ sudo chown 2000 /tmp/blah/a
stgraber@castiana:~$ lxc config set test raw.idmap "uid 2000 123456"
stgraber@castiana:~$ lxc start test

stgraber@castiana:~$ lxc exec test -- stat /mnt/a
  File: '/mnt/a'
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 30h/48d	Inode: 51          Links: 1
Access: (0644/-rw-r--r--)  Uid: (123456/ UNKNOWN)   Gid: (65534/ nogroup)
Access: 2018-04-10 09:43:43.917468253 +0000
Modify: 2018-04-10 09:43:43.917468253 +0000
Change: 2018-04-10 09:45:07.705844943 +0000
 Birth: -
stgraber@castiana:~$ 
```

So the order is correct, the first field is uid/gid/both, the second field is the id on the host, the last field is the id in the container.

The example is wrong though so I'm sending a branch for that.
