### ISSUE TITLE
Add a field to metadata.yaml to specify the number of ttys the container needs

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#444]
lxd builds containers with out /dev/tty[1234]  but the ubuntu images expect them to be present.  When they are absent, init spawns getty process on them but fails with errors in /var/log/auth.log like this:

Mar 31 19:59:14 precise-machine-1 getty[12727]: /dev/tty4: No such file or directory

This affects precise and trusty, but vivid doesn't use the same init and does not spawn getty.
```
(lambic) ~ % lxc exec precise-machine-1 -- /bin/bash -c 'uptime; ls -alh /var/log/auth.log && grep -c getty.*No\ such\ file /var/log/auth.log'
 19:57:51 up 22:40,  0 users,  load average: 0.77, 0.72, 0.76
-rw-r----- 1 syslog adm 2.6M Mar 31 19:57 /var/log/auth.log
31679
(lambic) ~ % lxc exec trusty-machine-1 -- /bin/bash -c 'uptime; ls -alh /var/log/auth.log && grep -c getty.*No\ such\ file /var/log/auth.log'
 19:57:55 up 22:40,  0 users,  load average: 0.87, 0.74, 0.76
-rw-r----- 1 syslog adm 2.4M Mar 31 19:57 /var/log/auth.log
29332
(lambic) ~ % lxc exec vivid-machine-1 -- /bin/bash -c 'uptime; ls -alh /var/log/auth.log && grep -c getty.*No\ such\ file /var/log/auth.log'
 19:57:58 up 22:40,  0 users,  load average: 0.87, 0.74, 0.76
ls: cannot access /var/log/auth.log: No such file or directory
```

**Comment by stgraber** [comment]
Assigning to me for the spec work, implementation may slip to 0.7.

**Comment by stgraber** [comment]
So after thinking about this some more, I think that adding that extra knob is actually the wrong thing to do.

There is genuinely no reason for a LXD container to ever have any console setup so rather than adding a way for LXD to offer useless consoles anyway (and therefore waste pty devices and fds), the right solution here will be for the images to either come with those disabled, parse the init environment to know what consoles to spawn (none under lxd) or use LXD's templating feature to turn off any getty inside the container.

**Comment by stgraber** [comment]
As a result, I'm closing this particular issue. For the specific problem we're seeing with Ubuntu pre-systemd, we'll resolve this by shipping a template that'll write "manual" into /etc/init/tty[1234].override

**Comment by Debianer** [comment]
The current Debian Jessie template from http://images.linuxcontainers.org/ tries to spawn 4 consoles.

**Comment by Debianer** [comment]
I must tested a wily image and console getty respawns here as well. Though not in the initial install. But after I enabled networking it did. Docker did something about it. Here is the bug report in RHEL7.1

https://github.com/lxc/lxd/issues/444

**Comment by stgraber** [comment]
Good, so that was fixed in systemd upstream, now we just need to wait for distros to pick up the fix in their systemd
