### ISSUE TITLE
GPU passthrough fails

### ISSUE THREAD

**Issue by tejeez** [lxc/lxd#4441]
# Required information

 * Distribution: Debian
 * Distribution version: 9 (stretch)
 * The output of "lxc info":
config:
  core.https_address: (removed)
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
(removed)
  architectures:
  - x86_64
  - i686
  certificate: (removed)
  certificate_fingerprint: (removed)
  driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.0-6-amd64
  server: lxd
  server_pid: 30074
  server_version: 3.0.0
  storage: dir
  storage_version: "1"
  server_clustered: false

# Issue description

Adding an NVIDIA Quadro NVS 290 gpu device to a container fails with the message:
`Error: strconv.Atoi: parsing "adro": invalid syntax`

Here's my /proc/driver/nvidia/gpus/0000:01:00.0/information:
<pre>
Model: 		 Quadro NVS 290
IRQ:   		 34
GPU UUID: 	 GPU-dfc2dd57-a451-8c62-8632-e79c9ba415bf
Video BIOS: 	 60.86.70.00.12
Bus Type: 	 PCIe
DMA Size: 	 40 bits
DMA Mask: 	 0xffffffffff
Bus Location: 	 0000:01:00.0
</pre>
I'm not sure but I guess it is a string parsing bug here:
https://github.com/lxc/lxd/blob/625bc66e73e51ed283fa1801f730bb44fb8d9ec7/lxd/devices.go#L229
since the string "adro" could come from the model of the GPU in the information file. Looks like it looks for "Device Minor" line but doesn't properly handle the fact that it is not present in the file.

# Steps to reproduce

 1. Find a machine with a similar GPU
 2. lxc config device add container mygpu gpu

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
nothing relevant
 - [ ] Container log (`lxc info NAME --show-log`)
nothing relevant
 - [ ] Container configuration (`lxc config show NAME --expanded`)
(relevant parts)
devices:
  mygpu:
    type: gpu
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
nothing relevant
 - [ ] Output of the client with --debug
lxc config device add container mygpu gpu --debug
DBUG[04-11|12:42:27] Connecting to a local LXD over a Unix socket 
DBUG[04-11|12:42:27] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[04-11|12:42:27] Got response struct from LXD 
DBUG[04-11|12:42:27] 
	{
		"config": {
			"core.https_address": (removed),
			"core.trust_password": true
		},
		"api_extensions": [
			"storage_zfs_remove_snapshots",
			"container_host_shutdown_timeout",
			"container_stop_priority",
			"container_syscall_filtering",
			"auth_pki",
			"container_last_used_at",
			"etag",
			"patch",
			"usb_devices",
			"https_allowed_credentials",
			"image_compression_algorithm",
			"directory_manipulation",
			"container_cpu_time",
			"storage_zfs_use_refquota",
			"storage_lvm_mount_options",
			"network",
			"profile_usedby",
			"container_push",
			"container_exec_recording",
			"certificate_update",
			"container_exec_signal_handling",
			"gpu_devices",
			"container_image_properties",
			"migration_progress",
			"id_map",
			"network_firewall_filtering",
			"network_routes",
			"storage",
			"file_delete",
			"file_append",
			"network_dhcp_expiry",
			"storage_lvm_vg_rename",
			"storage_lvm_thinpool_rename",
			"network_vlan",
			"image_create_aliases",
			"container_stateless_copy",
			"container_only_migration",
			"storage_zfs_clone_copy",
			"unix_device_rename",
			"storage_lvm_use_thinpool",
			"storage_rsync_bwlimit",
			"network_vxlan_interface",
			"storage_btrfs_mount_options",
			"entity_description",
			"image_force_refresh",
			"storage_lvm_lv_resizing",
			"id_map_base",
			"file_symlinks",
			"container_push_target",
			"network_vlan_physical",
			"storage_images_delete",
			"container_edit_metadata",
			"container_snapshot_stateful_migration",
			"storage_driver_ceph",
			"storage_ceph_user_name",
			"resource_limits",
			"storage_volatile_initial_source",
			"storage_ceph_force_osd_reuse",
			"storage_block_filesystem_btrfs",
			"resources",
			"kernel_limits",
			"storage_api_volume_rename",
			"macaroon_authentication",
			"network_sriov",
			"console",
			"restrict_devlxd",
			"migration_pre_copy",
			"infiniband",
			"maas_network",
			"devlxd_events",
			"proxy",
			"network_dhcp_gateway",
			"file_get_symlink",
			"network_leases",
			"unix_device_hotplug",
			"storage_api_local_volume_handling",
			"operation_description",
			"clustering",
			"event_lifecycle",
			"storage_api_remote_volume_handling",
			"nvidia_runtime"
		],
		"api_status": "stable",
		"api_version": "1.0",
		"auth": "trusted",
		"public": false,
		"auth_methods": [
			"tls"
		],
		"environment": {
			"architectures": [
				"x86_64",
				"i686"
			],
			"driver": "lxc",
			"driver_version": "3.0.0",
			"kernel": "Linux",
			"kernel_architecture": "x86_64",
			"kernel_version": "4.9.0-6-amd64",
			"server": "lxd",
			"server_pid": 30074,
			"server_version": "3.0.0",
			"storage": "dir",
			"storage_version": "1",
			"server_clustered": false,
		}
	} 
DBUG[04-11|12:42:27] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0/containers/container
DBUG[04-11|12:42:27] Got response struct from LXD 
DBUG[04-11|12:42:27] 
	{
		"architecture": "x86_64",
		"config": {
			"image.architecture": "amd64",
			"image.description": "ubuntu 17.04 amd64 (release) (20171121)",
			"image.label": "release",
			"image.os": "ubuntu",
			"image.release": "zesty",
			"image.serial": "20171121",
			"image.version": "17.04",
			"volatile.base_image": "cdc7d8cfe7877dc5186376bcd0bce6db4dab4c276aaf812e096fefb4b5fe991f",
			"volatile.eth0.hwaddr": "00:16:3e:eb:68:72",
			"volatile.eth0.name": "eth0",
			"volatile.idmap.base": "0",
			"volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.last_state.power": "RUNNING"
		},
		"devices": {
			"X0": {
				"path": "/tmp/.X11-unix/X0",
				"source": "/tmp/.X11-unix/X0",
				"type": "disk"
			},
			"Xauthority": {
				"path": "/home/ubuntu/.Xauthority",
				"source": "/home/username/.Xauthority",
				"type": "disk"
			}
		},
		"ephemeral": false,
		"profiles": [
			"default"
		],
		"stateful": false,
		"description": "",
		"created_at": "2018-01-21T18:23:13Z",
		"expanded_config": {
			"image.architecture": "amd64",
			"image.description": "ubuntu 17.04 amd64 (release) (20171121)",
			"image.label": "release",
			"image.os": "ubuntu",
			"image.release": "zesty",
			"image.serial": "20171121",
			"image.version": "17.04",
			"volatile.base_image": "cdc7d8cfe7877dc5186376bcd0bce6db4dab4c276aaf812e096fefb4b5fe991f",
			"volatile.eth0.hwaddr": "00:16:3e:eb:68:72",
			"volatile.eth0.name": "eth0",
			"volatile.idmap.base": "0",
			"volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.last_state.power": "RUNNING"
		},
		"expanded_devices": {
			"X0": {
				"path": "/tmp/.X11-unix/X0",
				"source": "/tmp/.X11-unix/X0",
				"type": "disk"
			},
			"Xauthority": {
				"path": "/home/ubuntu/.Xauthority",
				"source": "/home/username/.Xauthority",
				"type": "disk"
			},
			"eth0": {
				"nictype": "bridged",
				"parent": "lxdbr0",
				"type": "nic"
			},
			"root": {
				"path": "/",
				"pool": "default",
				"type": "disk"
			}
		},
		"name": "container",
		"status": "Running",
		"status_code": 103,
		"last_used_at": "2018-04-11T12:41:49Z",
		"location": ""
	} 
DBUG[04-11|12:42:27] Connected to the websocket 
DBUG[04-11|12:42:27] Sending request to LXD                   etag=34d2dcd3ede1451245ca7d308d253e57f66c74bb4ed835d95d0f6e1b99bd158e method=PUT url=http://unix.socket/1.0/containers/container
DBUG[04-11|12:42:27] 
	{
		"architecture": "x86_64",
		"config": {
			"image.architecture": "amd64",
			"image.description": "ubuntu 17.04 amd64 (release) (20171121)",
			"image.label": "release",
			"image.os": "ubuntu",
			"image.release": "zesty",
			"image.serial": "20171121",
			"image.version": "17.04",
			"volatile.base_image": "cdc7d8cfe7877dc5186376bcd0bce6db4dab4c276aaf812e096fefb4b5fe991f",
			"volatile.eth0.hwaddr": "00:16:3e:eb:68:72",
			"volatile.eth0.name": "eth0",
			"volatile.idmap.base": "0",
			"volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.last_state.power": "RUNNING"
		},
		"devices": {
			"X0": {
				"path": "/tmp/.X11-unix/X0",
				"source": "/tmp/.X11-unix/X0",
				"type": "disk"
			},
			"Xauthority": {
				"path": "/home/ubuntu/.Xauthority",
				"source": "/home/username/.Xauthority",
				"type": "disk"
			},
			"mygpu": {
				"type": "gpu"
			}
		},
		"ephemeral": false,
		"profiles": [
			"default"
		],
		"stateful": false,
		"description": ""
	} 
DBUG[04-11|12:42:27] Got operation from LXD 
DBUG[04-11|12:42:27] 
	{
		"id": "5f9ee44f-9ffb-4711-b913-ba7df7f65a6a",
		"class": "task",
		"description": "Updating container",
		"created_at": "2018-04-11T12:42:27.249310892Z",
		"updated_at": "2018-04-11T12:42:27.249310892Z",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/container"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": ""
	} 
DBUG[04-11|12:42:27] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0/operations/5f9ee44f-9ffb-4711-b913-ba7df7f65a6a
DBUG[04-11|12:42:27] Got response struct from LXD 
DBUG[04-11|12:42:27] 
	{
		"id": "5f9ee44f-9ffb-4711-b913-ba7df7f65a6a",
		"class": "task",
		"description": "Updating container",
		"created_at": "2018-04-11T12:42:27.249310892Z",
		"updated_at": "2018-04-11T12:42:27.249310892Z",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/container"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": ""
	} 
Error: strconv.Atoi: parsing "adro": invalid syntax
`

 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
metadata:
  context: {}
  level: dbug
  message: 'New event listener: 6ef24016-ab77-49eb-b91a-c57424501b50'
timestamp: "2018-04-11T12:42:24.590777843Z"
type: logging

metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2018-04-11T12:42:27.215638617Z"
type: logging

metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container
  level: dbug
  message: handling
timestamp: "2018-04-11T12:42:27.222735409Z"
type: logging

metadata:
  context: {}
  level: dbug
  message: 'New event listener: 2c80ad25-d331-4311-93ef-e6e9c710d348'
timestamp: "2018-04-11T12:42:27.236649708Z"
type: logging

metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/events
  level: dbug
  message: handling
timestamp: "2018-04-11T12:42:27.236520925Z"
type: logging

metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/containers/container
  level: dbug
  message: handling
timestamp: "2018-04-11T12:42:27.238650375Z"
type: logging

metadata:
  class: task
  created_at: "2018-04-11T12:42:27.249310892Z"
  description: Updating container
  err: ""
  id: 5f9ee44f-9ffb-4711-b913-ba7df7f65a6a
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/container
  status: Running
  status_code: 103
  updated_at: "2018-04-11T12:42:27.249310892Z"
timestamp: "2018-04-11T12:42:27.323149387Z"
type: operation

metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 5f9ee44f-9ffb-4711-b913-ba7df7f65a6a'
timestamp: "2018-04-11T12:42:27.323119426Z"
type: logging

metadata:
  class: task
  created_at: "2018-04-11T12:42:27.249310892Z"
  description: Updating container
  err: ""
  id: 5f9ee44f-9ffb-4711-b913-ba7df7f65a6a
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/container
  status: Pending
  status_code: 105
  updated_at: "2018-04-11T12:42:27.249310892Z"
timestamp: "2018-04-11T12:42:27.32306558Z"
type: operation

metadata:
  context: {}
  level: dbug
  message: 'New task operation: 5f9ee44f-9ffb-4711-b913-ba7df7f65a6a'
timestamp: "2018-04-11T12:42:27.323002167Z"
type: logging

metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/operations/5f9ee44f-9ffb-4711-b913-ba7df7f65a6a
  level: dbug
  message: handling
timestamp: "2018-04-11T12:42:27.328567956Z"
type: logging

metadata:
  context: {}
  level: dbug
  message: Initializing a DIR driver.
timestamp: "2018-04-11T12:42:27.341970827Z"
type: logging

metadata:
  class: task
  created_at: "2018-04-11T12:42:27.249310892Z"
  description: Updating container
  err: 'strconv.Atoi: parsing "adro": invalid syntax'
  id: 5f9ee44f-9ffb-4711-b913-ba7df7f65a6a
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/container
  status: Failure
  status_code: 400
  updated_at: "2018-04-11T12:42:27.249310892Z"
timestamp: "2018-04-11T12:42:27.344230665Z"
type: operation

metadata:
  context: {}
  level: dbug
  message: 'Failure for task operation: 5f9ee44f-9ffb-4711-b913-ba7df7f65a6a: strconv.Atoi:
    parsing "adro": invalid syntax'
timestamp: "2018-04-11T12:42:27.344188483Z"
type: logging

metadata:
  context: {}
  level: dbug
  message: 'Scheduler: container container changed: re-balancing'
timestamp: "2018-04-11T12:42:27.344283044Z"
type: logging

**Comment by stgraber** [comment]
@brauner can you send a branch to show a better error in such cases?

**Comment by 3XX0** [comment]
In the long run, libnvidia-container API integration should solve that, but in the meantime you can get the correct device mapping using the CLI:

`nvidia-container-cli list -d <device index in PCI bus order>`
or
`nvidia-container-cli info`

I concede that it's not ideal...

**Comment by stgraber** [comment]
@brauner might be worth doing that when the proc field is missing and nvidia-container-cli is present

**Comment by brauner** [comment]
@3XX0  `<device index in PCI bus order>` meaning first column of `lspci`, e.g. `00:1c.5` or only `1c` or what?

**Comment by 3XX0** [comment]
Meaning the same order as shown in `nvidia-smi`, 0 being the first device if you sort all of them by the full PCI busid.
