### ISSUE TITLE
LVM tools doesn't show logical volumes created by lxd

### ISSUE THREAD

**Issue by hispanico** [lxc/lxd#4445]
# Required information

 * Distribution: Ubunut
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.13.0-37-generic
   * LXC version: 3.0.0
   * LXD version: 3.0.0
   * Storage backend in use: lvm

# Issue description

After switch to lxd snap version, when a container or snapshot have been created/deleted `lvs` or `lvdisplay` doesn't show the correct logical volume info.
After manually run `vgscan --cache` we are able to get the correct info.

# Steps to reproduce

 1. Run `lvs`
 2. Create a new container/snapshot or delete container/snapshot
 3. Run `lvs`
 4. Run `vgscan --cache`
 5. Run `lvs`

**Comment by stgraber** [comment]
Yeah, that's expected behavior unfortunately.

The reason for it is that snaps don't use your system's libraries and daemons, so the LXD snap doesn't interact with your system's LVM metadata daemon (lvmetad) which depending on the LVM config on your host can lead to the LVM tools reporting out of date information.

In theory configuring your host to not use lvmetad and disabling LVM caching should then properly report everything that LXD is doing.

**Comment by stgraber** [comment]
The reason why we can't use the system's LVM metad and libraries/files is that the same snap package is used for all distributions and distribution versions and unfortunately LVM's metad structs and on-disk cache aren't backward/forward compatible, so attempting to use them would at best lead to errors and at worse data corruption.

**Comment by hispanico** [comment]
Basically I'd like to check the disk space used via nagios check.
Do you suggest to disable lvmetad and LVM caching or runing `vgscan --cache` before every check?

**Comment by stgraber** [comment]
I thought there was a lvs --no-cache type command that'd effectively do that for you, am I misremembering?

**Comment by stgraber** [comment]
I think the answer will depend on what's run the most often. If it's the nagios check, then I'd say go for turning off metad and caching. If you have a lot of LVS getting created and deleted all the time or other LVM operations happening very frequently, then running vgscan before the check may give you better performance.
