### ISSUE TITLE
(with fix) default alpine images are "spamming" syslog

### ISSUE THREAD

**Issue by gschintgen** [lxc/lxd#4449]
Hi, whenever I set up an alpine-based container I have to fix/workaround a bug where /var/log/messages is constantly spammed with error messages. This is 100% reproducible for me:

```
$ lxc launch images:alpine/edge test
Creating test
Starting test
$ lxc exec test tail /var/log/messages
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty3: No such file or directory
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty4: No such file or directory
Dec 31 23:59:59 test daemon.info init: process '/sbin/getty 38400 tty1' (pid 973) exited. Scheduling for restart.
Dec 31 23:59:59 test daemon.info init: process '/sbin/getty 38400 tty2' (pid 974) exited. Scheduling for restart.
Dec 31 23:59:59 test daemon.info init: process '/sbin/getty 38400 tty3' (pid 975) exited. Scheduling for restart.
Dec 31 23:59:59 test daemon.info init: process '/sbin/getty 38400 tty4' (pid 976) exited. Scheduling for restart.
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty1: No such file or directory
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty2: No such file or directory
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty3: No such file or directory
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty4: No such file or directory
```

The fix is to comment out the 4 tty lines in /etc/inittab:
```
# Set up a couple of getty's
#tty1::respawn:/sbin/getty 38400 tty1
#tty2::respawn:/sbin/getty 38400 tty2
#tty3::respawn:/sbin/getty 38400 tty3
#tty4::respawn:/sbin/getty 38400 tty4
```

Since it's a rather simple fix I hope this could be changed in the default images provided by the LXD project. After all, logging is one of the most basic aspects of any unix-like system.

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: i686
  kernel_version: 4.13.0-38-generic
  server: lxd
  server_pid: 1513
  server_version: "2.21"
  storage: btrfs
  storage_version: "4.4"

**Comment by stgraber** [comment]
actually it's not a simple fix as the same images are consumed by lxc which does need those tty entries.  
Our new image generation tool, distrobuilder should be able to handle this in the future.

@monstermunchkin

Closing the issue as this isn't a LXD bug but a lxc-templates/distrobuilder one instead. I trust that @monstermunchkin will add this to what's needed in distrobuilder for alpine.
