### ISSUE TITLE
(with workaround) useless timestamp Dec 31 23:59:59 for all entries in alpine's /var/log/messages

### ISSUE THREAD

**Issue by gschintgen** [lxc/lxd#4450]
Hi, whenever I set up an alpine-based container I have to fix/workaround a bug where all entries in /var/log/messages have the same nonsensical timestamp. This is 100% reproducible for me:

```
$ lxc launch images:alpine/edge test
Creating test
Starting test
$ lxc exec test tail /var/log/messages
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty3: No such file or directory
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty4: No such file or directory
Dec 31 23:59:59 test daemon.info init: process '/sbin/getty 38400 tty1' (pid 973) exited. Scheduling for restart.
Dec 31 23:59:59 test daemon.info init: process '/sbin/getty 38400 tty2' (pid 974) exited. Scheduling for restart.
Dec 31 23:59:59 test daemon.info init: process '/sbin/getty 38400 tty3' (pid 975) exited. Scheduling for restart.
Dec 31 23:59:59 test daemon.info init: process '/sbin/getty 38400 tty4' (pid 976) exited. Scheduling for restart.
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty1: No such file or directory
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty2: No such file or directory
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty3: No such file or directory
Dec 31 23:59:59 test daemon.info init: can't open /dev/tty4: No such file or directory
```

The workaround is to comment out the "-Z" line in /etc/conf.d/syslog. (Thanks to Maniaxx who provided me with this workaround: https://discuss.linuxcontainers.org/t/alpine-wrong-timestamp-dec-31-23-59-59-for-all-var-log-messages-entries/1566/3?u=gilles)
Since it's a rather simple fix I hope this could be changed in the default images provided by the LXD project. After all, logging is one of the most basic aspects of any unix-like system.

The drawback to this workaround is that then the timestamps are all in UTC instead of localtime. But that's still far better than having no (useful) timestamps at all.

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: i686
  kernel_version: 4.13.0-38-generic
  server: lxd
  server_pid: 1513
  server_version: "2.21"
  storage: btrfs
  storage_version: "4.4"

**Comment by stgraber** [comment]
I expect it's something we could do by default for Alpine in distrobuilder.
@monstermunchkin please track this one too

Closing like the other as there's nothing actionable here for LXD itself.
