### ISSUE TITLE
LXD 3.0 (from snap) node fails to join cluster

### ISSUE THREAD

**Issue by iatrou** [lxc/lxd#4451]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Xenial
 * Kernel version: 4.4.0-119-generic x86_64
 * LXC version: 
<pre>
$ dpkg -l | egrep 'lxc|lxd'
ii  liblxc1                             2.0.8-0ubuntu1 16.04.2                     amd64        Linux Containers userspace tools (library)
ii  lxc-common                          2.0.8-0ubuntu1 16.04.2                     amd64        Linux Containers userspace tools (common tools)
ii  lxcfs                               2.0.7-0ubuntu1 16.04.2                     amd64        FUSE based filesystem for LXC
</pre>
 * LXD version:
<pre>
snap-id:   J60k4JY0HppjwOjW8dZdYc8obXKxujRu
tracking:  stable
refreshed: 2018-04-09T23:13:08Z
installed:       3.0.0       (6643) 56MB -
</pre>
 * Storage backend in use:
<pre>
  storage: ""
  storage_version: ""
</pre>

# Issue description

A node running lxd 3.0 (installed from snap) cannot join a cluster due to insufficient permissions.

# Steps to reproduce
<pre>
$ lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: yes
What name should be used to identify this node in the cluster? [default=dc1-002]: 
What IP address or DNS name should be used to reach this node? [default=10.0.0.62]: dc1-002.maas
Are you joining an existing cluster? (yes/no) [default=no]: yes
IP address or FQDN of an existing cluster node: dc1-001.maas    
Cluster fingerprint: 7011ed3a460337a4695622509a5a797bdd84d8eac9f4d1d3c32d17fdf72cccae
You can validate this fingerpring by running "lxc info" locally on an existing node.
Is this the correct fingerprint? (yes/no) [default=no]: yes
Cluster trust password: 
All existing data is lost when joining a cluster, continue? (yes/no) [default=no] yes
Error: failed to load TLS certificate: open /var/snap/lxd/common/lxd/server.key: permission denied

$ ll /var/snap/lxd/common/lxd/server.key
-rw------- 1 root root 3247 Apr 16 00:43 /var/snap/lxd/common/lxd/server.key
</pre>

Running instead `sudo lxd init` works as expected.

If this behavior is expected, it would be helpful to have a relevant message during the interactive `lxd init` to indicate that.

**Comment by stgraber** [comment]
Oh, good catch, clustering requires root during init. I'll send a fix that adds a check for it.

**Comment by stgraber** [comment]
Actually looks like we can do away with that requirement by changing a bit of code.

**Comment by stgraber** [comment]
Hmm, I spoke to soon, with the current API we can't...

**Comment by maccumaccu** [comment]
Can anyone help me ? 


root@lxd01:/# lxc cluster list 
+-------+---------------------------+----------+--------+-------------------+
| NAME  |            URL            | DATABASE | STATE  |      MESSAGE      |
+-------+---------------------------+----------+--------+-------------------+
| lxd01 | https://10.242.42.14:8443 | YES      | ONLINE | fully operational |
+-------+---------------------------+----------+--------+-------------------+
| lxd02 | https://10.242.42.15:8443 | YES      | ONLINE | fully operational |
+-------+---------------------------+----------+--------+-------------------+
root@lxd01:/# 



root@lxd03:~# lxc list 
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:18.04

+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
root@lxd03:~# lxd init 
Would you like to use LXD clustering? (yes/no) [default=no]: yes
What name should be used to identify this node in the cluster? [default=lxd03]: 
What IP address or DNS name should be used to reach this node? [default=10.242.42.16]: 
Are you joining an existing cluster? (yes/no) [default=no]: yes
IP address or FQDN of an existing cluster node: 10.242.42.14
Cluster fingerprint: 0d7110d5fec373f032421b0ea6474b66a5cb8a0d292ac8f27f1d51968649cd97
You can validate this fingerprint by running "lxc info" locally on an existing node.
Is this the correct fingerprint? (yes/no) [default=no]: yes
Cluster trust password: 
All existing data is lost when joining a cluster, continue? (yes/no) [default=no] yes
**Error: Failed to retrieve cluster information: not authorized**
root@lxd03:~# which lxd 
/snap/bin/lxd
root@lxd03:~# lxd --version 
3.18
root@lxd03:~# snap list 
Name  Version    Rev    Tracking  Publisher   Notes
core  16-2.39.3  7270   stable    canonical✓  core
lxd   3.18       12100  stable    canonical✓  -
root@lxd03:~# uname -a 
Linux lxd03 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stgraber** [comment]
That normally means that the password you entered is incorrect.

**Comment by maccumaccu** [comment]
> That normally means that the password you entered is incorrect.

I have installed a new lxd cluster with 3 new hosts.
I have tried with  lxd 3.18 and lxd 3.0.4.
I created the first node and added the second node without receiving this error.
When I add the third node I get this error by entering the correct password.

Today:

root@lxd03:~# which lxd 
/snap/bin/lxd
root@lxd03:~# which lxc 
/snap/bin/lxc
root@lxd03:~# snap list 
Name  Version  Rev    Tracking  Publisher   Notes
core  16-2.41  7713   stable    canonical✓  core
lxd   3.0.4    11348  3.0       canonical✓  -
root@lxd03:~# 


root@lxd02:~# lxd init 
Would you like to use LXD clustering? (yes/no) [default=no]: yes
What name should be used to identify this node in the cluster? [default=lxd02]: 
What IP address or DNS name should be used to reach this node? [default=10.242.42.15]: 
Are you joining an existing cluster? (yes/no) [default=no]: yes
IP address or FQDN of an existing cluster node: 10.242.42.14
Cluster fingerprint: 2a35bdfc9a91f7a20aacf8efeaf914f64e943c2fda569ccf45580d2ca95de8d6
You can validate this fingerprint by running "lxc info" locally on an existing node.
Is this the correct fingerprint? (yes/no) [default=no]: yes
Cluster trust password: 
All existing data is lost when joining a cluster, continue? (yes/no) [default=no] yes
Choose the local disk or dataset for storage pool "local" (empty for loop disk): 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: 
root@lxd02:~# lxc cluster list 
To start your first container, try: lxc launch ubuntu:18.04

+-------+---------------------------+----------+--------+-------------------+
| NAME  |            URL            | DATABASE | STATE  |      MESSAGE      |
+-------+---------------------------+----------+--------+-------------------+
| lxd01 | https://10.242.42.14:8443 | YES      | ONLINE | fully operational |
+-------+---------------------------+----------+--------+-------------------+
| lxd02 | https://10.242.42.15:8443 | YES      | ONLINE | fully operational |
+-------+---------------------------+----------+--------+-------------------+
root@lxd02:~# 






root@lxd03:~# lxd init 
Would you like to use LXD clustering? (yes/no) [default=no]: yes
What name should be used to identify this node in the cluster? [default=lxd03]: 
What IP address or DNS name should be used to reach this node? [default=10.242.42.16]: 
Are you joining an existing cluster? (yes/no) [default=no]: yes
IP address or FQDN of an existing cluster node: 10.242.42.14
Cluster fingerprint: 2a35bdfc9a91f7a20aacf8efeaf914f64e943c2fda569ccf45580d2ca95de8d6
You can validate this fingerprint by running "lxc info" locally on an existing node.
Is this the correct fingerprint? (yes/no) [default=no]: yes
Cluster trust password: 
All existing data is lost when joining a cluster, continue? (yes/no) [default=no] yes
Error: Failed to retrieve storage pools from the cluster: not authorized
root@lxd03:~#

**Comment by stgraber** [comment]
Ah, could be that this system has a mix of snap and deb which would certainly lead to a bunch of confusion.
