### ISSUE TITLE
LXD Resource Limitation Issue (SWAP)

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#4454]
# Required information

 * Distribution: **Ubuntu**
 * Distribution version: **16.04.4 LTS**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.4.0-116-generic**
   * LXC version: **2.2.1**
   * LXD version: **2.2.1**
   * Storage backend in use: **zfs**

# Issue description

We are running R inside of a container and are trying to LIMIT the amount of Swap space it can use on the host. Reason: When R runs very heavy loads, it uses up all the available SWAP is causes the R process to fail and slows down the entire system.  

# Steps to reproduce

 1. We tried setting the swap limit variables: 
```
    lxc.cgroup.memory.limit_in_bytes = 2G
    lxc.cgroup.memory.memsw.limit_in_bytes = 4G
```
 2. We then restarted the container but obtained the following errors" 
```
ubuntu@ubuntu:~$ lxc info --show-log R
Name: R
Remote: unix://
Architecture: x86_64
Created: 2018/04/16 08:58 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20180416091211.970 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1971 - Permission denied - Error setting memory.memsw.limit_in_bytes to 4G for R
            lxc 20180416091211.970 ERROR    lxc_start - start.c:lxc_spawn:1205 - Failed to setup cgroup limits for container "R".
            lxc 20180416091211.983 WARN     lxc_conf - conf.c:lxc_delete_network:3103 - Failed to remove "veth7O9B7T" from host: Invalid argument.
            lxc 20180416091211.983 ERROR    lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "R".
            lxc 20180416091212.529 ERROR    lxc_conf - conf.c:run_buffer:416 - Script exited with status 1.
            lxc 20180416091212.529 ERROR    lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "R".
            lxc 20180416091212.529 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.
            lxc 20180416091212.530 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.

```

 3. We followed the instructions from:

`
https://www.safematix.com/system/linux/ubuntu-lxc-memory-swap-limit/
`
But still does not work.... We then found that we need to RESTART the entire server in order for it to apply.. 

**Question: Is there a way to have these variables applied without a server reboot?** 

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [x] Output of the client with --debug
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

[lxc-monitor-debug.log](https://github.com/lxc/lxd/files/1914640/lxc-monitor-debug.log)
[lxd.log](https://github.com/lxc/lxd/files/1914641/lxd.log)
[lxc-config-show-R--expanded.log](https://github.com/lxc/lxd/files/1914645/lxc-config-show-R--expanded.log)
[lxc-info-R--show.log](https://github.com/lxc/lxd/files/1914646/lxc-info-R--show.log)

**Comment by lcherone** [comment]
Did you see this: https://github.com/lxc/lxc/issues/668

**Comment by brauner** [comment]
@lcherone, yes that's a pre-requisite. Once you've made sure that this is enabled you should set:

```
lxc config set <container-name> limits.memory 2GB
lxc config set <container-name> limits.memory.swap true
```

**Comment by elbrinke** [comment]
Hi, 
I have set that before but it did not work. After I set those variables and restarted the container, it did not limit the container to a specific amount of swap space. It caused he container to use up all the swap space on the host, which is what we dont want. 

- The container is set to a memory Limit of **16GB**

_But we dont want that to mean that the container should also use 16GB of SWAP space...._ 

**Question: What is the best way to limit a container's use of host swap space?** 

Thanks for your input.

**Comment by brauner** [comment]
That's not easily doable if I remember correctly. Swap limits are set by `memsw.limit_in_bytes` but that just limits `memory + swap`. If you limit to `16GB` the container might still use all of the swap if it runs out of memory. You can try and set `limits.memory.swap.priority` to `10` to make it very unlikely that the container uses swap.

**Comment by elbrinke** [comment]
Hi, 
Since it's not recommended that I use both "limits.memory.swap..." & "

**Comment by elbrinke** [comment]
Hi @brauner , 

I cannot see @lcherone, reply?

**Comment by brauner** [comment]
Ok, so your `lxd.log` file shows:

    lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-04-16T10:54:01+0200

To fix this you need to append `swapaccount=1` to your kernel command line on your host and reboot the server.
If grub is your default bootloader you can add this option to `/etc/default/grub` to
`GRUB_CMDLINE_LINUX`, that is `GRUB_CMDLINE_LINUX="swapaccount=1" and then update grub with the appropriate command. After this these limits should work.

**Comment by lcherone** [comment]
Sorry I removed my comment as I saw the link `https://www.safematix.com/system/linux/ubuntu-lxc-memory-swap-limit` so presumed you had already set it.

The issue I linked to was https://github.com/lxc/lxc/issues/668

**Comment by elbrinke** [comment]
Hi, 
I have done this and it required a server reboot, not just a container reboot to work. 

Kind Regards

**Comment by brauner** [comment]
@elbrinke, but that's not the point. You have to reboot the server **once** to enable this feature. This has nothing to do with LXD or containers in general. It's just that your kernel that is shared between containers wasn't properly setup to handle swap limits. So you should reboot the server once and then you can do swap limits. Currently no-one on your system can because it's simply not enabled.

**Comment by elbrinke** [comment]
I see, thanks @brauner
