### ISSUE TITLE
Block all local network traffic from container

### ISSUE THREAD

**Issue by erbzz** [lxc/lxd#4470]
* Kernel: Linux
* Kernel architecture: x86_64
* Kernel version: 4.13.0-37-generic
* LXC version: 2.0.8
* LXD version: 2.21
* Storage backend in use: dir, version 1

I am running Ubuntu 16.04 on my machine in which I am trying to completely isolate an LXD container's network. Is there an `iptables` command/rule I could execute that would block all local network traffic from the container?

I am mainly focused on blocking output from the container. The use case for this is if someone were to be inside the container, they should not be able to ping/see any of the other devices on the same network. I tried adding IPtables rules to the host machine but I was still able to sniff machines on the local network from inside the container. Is there a specific LXD network config option or a best practice for this?

I am simply looking for the best way to completely isolate a container’s network from the local network. It shouldn’t have access to any IPs on the LAN. However, it should still be able to access the internet (among other things).

**Comment by stgraber** [comment]
```
iptables -I INPUT -s container-ip -j REJECT
iptables -I FORWARD -s container-ip -d lan-subnet -j REJECT
```

Doing that on the host should do the trick. Just replace container-ip with the container's IP address and lan-subnet by the CIDR of your LAN.

**Comment by erbzz** [comment]
Thank you so much for the quick reply, Stephane.

This command works for the container with specified IP. However, is there a way to make this general? To basically execute this rule for all containers (even ones that will be created in the future)

**Comment by stgraber** [comment]
Yep, in that case, use:
```
iptables -I INPUT -i lxdbr0 -j REJECT
iptables -I FORWARD -i lxdbr0 -d lan-subnet -j REJECT
```

Assuming your bridge is called `lxdbr0`.

Closing as there's no actual LXD issue for us to fix here.

**Comment by richearle** [comment]
Using Stephane commands I've set my ip tables up on the machine that hosts the container, trying to block access to the LAN (192.168.69.*), but from inside the container I can still make an ssh connection to 192.168.69.28.

`service --status-all` tells me ufw & apparmor are enabled.

I've tried everything to block it. The hosting machine is 192.168.69.19 and the container is 192.168.69.58. Both are 22.04 with lxd/lxc at 5.1.

```
systems@Chip-C:~$__ sudo iptables -L -v
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REJECT     all  --  lxdbr0 any     anywhere             anywhere             reject-with icmp-port-unreachable
    0     0 REJECT     all  --  any    any     192.168.69.58        anywhere             reject-with icmp-port-unreachable

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REJECT     all  --  lxdbr0 any     anywhere             192.168.69.28        reject-with icmp-port-unreachable
    0     0 REJECT     all  --  lxdbr0 any     anywhere             192.168.69.0         reject-with icmp-port-unreachable
    0     0 REJECT     all  --  lxdbr0 any     anywhere             192.168.69.0/24      reject-with icmp-port-unreachable
    0     0 REJECT     all  --  lxdbr0 any     anywhere             255.255.255.0        reject-with icmp-port-unreachable
    0     0 REJECT     all  --  any    any     192.168.69.58        192.168.69.0/24      reject-with icmp-port-unreachable

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
systems@Chip-C:~$
```
I flushed out iptables-legacy tables but they are empty anyway. Not sure how to get rid of them, or if I need to.

**Comment by tomponline** [comment]
Hi @richearle please can you post support issues over at https://discuss.linuxcontainers.org/ 
Thanks
