### ISSUE TITLE
LXD (>=2.21) will fail to do a container live migration with liblxc (2.x.x)

### ISSUE THREAD

**Issue by tpppppub** [lxc/lxd#4475]
# Issue description
After version 2.21, LXD will do a checkForPreDumSupport (in the file of "migrate.go" or "migrate_container.go") when live migrating containers. This function then will call lxc.MIGRATE_FEATURE_CHECK to do a check. However, liblxc does not support this feature in version 2.x.x (the relevant code is do_lxcapi_migrate in lxccontainer.c). So using LXD (>=2.21) with liblxc (<3.0.0) do a container live migration will fail. An error like "ERROR lxc_container - lxccontainer.c:do_lxcapi_migrate:4027 - invalid migrate command 3" will be given.

**Comment by tpppppub** [comment]
Hi @brauner , could you please check this issue again?

**Comment by brauner** [comment]
@adrianreber, didn't we think of this when we wrote that code? :)

**Comment by tpppppub** [comment]
Hi @adrianreber , I read the code in go-lxc as below. It does have a version check which only passes features_to_check to liblxc if it is >= 3.0.0. However, there is no version check for cmd. When cmd is MIGRATE_FEATURE_CHECK, liblxc (<3.0.0) doesn't know what it is.
```C
int go_lxc_migrate(struct lxc_container *c, unsigned int cmd, struct migrate_opts *opts, struct extra_migrate_opts *extras) {
#if VERSION_AT_LEAST(3, 0, 0)
	opts->features_to_check = extras->features_to_check;
#endif
#if VERSION_AT_LEAST(2, 0, 4)
	opts->action_script = extras->action_script;
	opts->ghost_limit = extras->ghost_limit;
#endif

#if VERSION_AT_LEAST(2, 0, 1)
	opts->preserves_inodes = extras->preserves_inodes;
#endif

#if VERSION_AT_LEAST(2, 0, 0)
	return c->migrate(c, cmd, opts, sizeof(*opts));
#else
	return -EINVAL;
#endif
}
```

**Comment by stgraber** [comment]
Feels like something LXD should guard against with a runtime LXC version check, not even attempting the Migrate call with the feature check arg when on < 3.0. That'd be more reliable than trying to put that in the go-lxc code as go-lxc does build-time checks instead of runtime check (so a system that's using LXD built against liblxc 3.0 but is actually running liblxc 2.x will incorrectly attempt to use the feature).

**Comment by adrianreber** [comment]
@tpppppub I am pretty sure I tested that. When LXC does not know about MIGRATE_FEATURE_CHECK it returns an error and LXD handles it correctly. I am still not sure I understand the problem you describe correctly.

@stgraber If building against liblxc 3.0 and running against liblxc 2.x is a supported case then yes, there is a problem. I guess I assumed that it is expected to always run with at least the version used during build.

**Comment by tpppppub** [comment]
Sorry, I found the reason causing my container live migration failed was not as I thought initially. 
I tried a container live migration from host1 to host2. Then 'lxc move' stuck after files finished transferring, waiting indefinitely. On host2, I found that the container had been migrated and was running. On host1, I found the container was running too.

Host1 and host2 have the completely same environment as follow:
Distribution: Ubuntu
Distribution version: 16.04.3 LTS
Kernel version: 4.10.0-28-generic
LXC version: 2.0.8
LXD version: 2.21
Storage backend in use: btrfs



# Steps to reproduce

 1. Launch a container (ubuntu:16.04) on host1
 2. Stop the apparmor inside the container
 3. lxc move container host2:

On host1:
```bash
root@ubuntu:~# lxc launch ubuntu:16.04 testCon
Creating testCon
Starting testCon
root@ubuntu:~# lxc exec testCon -- /bin/bash
root@testCon:~# /etc/init.d/apparmor teardown
 * Unloading AppArmor profiles                                           [ OK ] 
root@testCon:~# exit
root@ubuntu:~# lxc move testCon host2:

```
waiting indefinitely after files finished transferring ...

```bash
root@ubuntu:~# lxc list
+---------+---------+------+------+------------+-----------+
|  NAME   |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+---------+---------+------+------+------------+-----------+
| testCon | RUNNING |      |      | PERSISTENT | 0         |
+---------+---------+------+------+------------+-----------+
```

On host2:
```bash
root@ubuntu:~# lxc list
+---------+---------+---------------------+-----------------------------------------------+------------+-----------+
|  NAME   |  STATE  |        IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+---------+---------+---------------------+-----------------------------------------------+------------+-----------+
| testCon | RUNNING | 10.214.23.28 (eth0) | fd42:95ee:d9c3:24f3:216:3eff:fefa:f1dc (eth0) | PERSISTENT | 0         |
+---------+---------+---------------------+-----------------------------------------------+------------+-----------+
```
# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
[host1-container.log](https://github.com/lxc/lxd/files/1932748/host1-container.log)
[host2-container.log](https://github.com/lxc/lxd/files/1932749/host2-container.log)

 - [x] Container configuration (`lxc config show NAME --expanded`)
[host1-container-config.log](https://github.com/lxc/lxd/files/1932751/host1-container-config.log)
[host2-container-config.log](https://github.com/lxc/lxd/files/1932752/host2-container-config.log)


 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 The daemon log is with --debug.
[host1-lxd.log](https://github.com/lxc/lxd/files/1932753/host1-lxd.log)
[host2-lxd.log](https://github.com/lxc/lxd/files/1932754/host2-lxd.log)


 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Should be easy enough to try to reproduce, what's the CRIU version in use here?

**Comment by stgraber** [comment]
Note that your kernel isn't supported anymore, AFAIK on 16.04 you get one of:
 - 4.4 (GA kernel)
 - 4.13 (HWE)
 - 4.15 (HWE edge)

I'll attempt to reproduce your issue with the HWE kernel (4.13) as that's what's closed to what you reported.

**Comment by tpppppub** [comment]
The CRIU version is 3.4.

**Comment by stgraber** [comment]
```
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-38-generic
  server: lxd
  server_pid: 5626
  server_version: "2.21"
  storage: ""
  storage_version: ""
```

That's what I've got running here now with a manually installed CRIU 3.4 to match.

**Comment by stgraber** [comment]
We're hitting some btrfs snapshot errors on the source machine, I guess that's the issue. Going to retry with LXD 3.0 see if things are different there, if not, I'll have @brauner look into this :)

**Comment by stgraber** [comment]
Ah no, nevermind, the btrfs issue was caused by the previous migration failure...

**Comment by stgraber** [comment]
The hang is caused by the call back to criu post-migration hanging. I just tried with an alpine container and things worked fine there.

**Comment by stgraber** [comment]
```
root@vm08:~# lxc launch images:alpine/edge c1
Creating c1
Starting c1
root@vm08:~# lxc list
+------+---------+---------------------+-----------------------------------------------+------------+-----------+
| NAME |  STATE  |        IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+------+---------+---------------------+-----------------------------------------------+------------+-----------+
| c1   | RUNNING | 10.76.64.106 (eth0) | fd42:8607:3df5:2ee0:216:3eff:fe82:af12 (eth0) | PERSISTENT | 0         |
+------+---------+---------------------+-----------------------------------------------+------------+-----------+
root@vm08:~# lxc move c1 vm09:
root@vm08:~# lxc list
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
root@vm08:~# lxc list vm09:
+------+---------+---------------------+-----------------------------------------------+------------+-----------+
| NAME |  STATE  |        IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+------+---------+---------------------+-----------------------------------------------+------------+-----------+
| c1   | RUNNING | 10.76.64.106 (eth0) | fd42:8607:3df5:2ee0:216:3eff:fe82:af12 (eth0) | PERSISTENT | 0         |
|      |         |                     | fd42:80c4:b309:3cb3:216:3eff:fe82:af12 (eth0) |            |           |
+------+---------+---------------------+-----------------------------------------------+------------+-----------+
root@vm08:~# 
```

**Comment by stgraber** [comment]
With 3.0, I'm getting the same hang but this time with a clearer "Failed migrating container" error on the sender and no container created on the target.

As with 2.21, migrating an alpine container works fine.

**Comment by stgraber** [comment]
@brauner can you take a look at this? We at the very least are missing some error handling code. When the source hits "Failed migrating container", `lxc move` should report that error and any created background operation on source and target should go away which I'm not seeing happen here...

**Comment by stgraber** [comment]
@brauner feel free to use vm08 and vm09 for that if useful, if not, release them in MAAS.

**Comment by tpppppub** [comment]
Thx. I'll try an alpine container for my jobs.

**Comment by brauner** [comment]
Trying to reproduce now.

**Comment by brauner** [comment]
```
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-38-generic
  server: lxd
  server_pid: 16534
  server_version: 3.0.0
  storage: btrfs
  storage_version: "4.4"
  server_clustered: false
  server_name: vm08        
```
So I could only reproduce this when `migration.incremental.memory` was not used and it seems that somehow `LXD` isn't receiving the success message from the `migratedumpsuccess` subprocess. The hanging `btrfs send` seems just a side-effect and unrelated. The process tree I see:
```
root     16513  0.0  0.0  55756  3420 pts/4    S+   10:52   0:00  |   \_ sudo -E /home/ubuntu/go/bin/lxd --debug --group lxd --logfile l1.log
root     16514  1.0  0.5 1456324 42232 pts/4   Sl+  10:52   0:15  |       \_ /home/ubuntu/go/bin/lxd --debug --group lxd --logfile l1.log
root     17710  0.0  0.0  19680  3984 pts/4    S+   10:54   0:00  |           \_ /usr/sbin/criu dump --tcp-established --file-locks --link-remap --manage-cgroups=full --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /tmp/lxd_checkpoint_992912836/final -o /tmp/lxd_checkpoint_992912836/final/dump.log --cgroup-root name=systemd /lxc/x2 --cgroup-root pids /lxc/x2 --cgroup-root blkio /lxc/x2 --cgroup-root cpu,cpuacct /lxc/x2 --cgroup-root devices /lxc/x2 --cgroup-root cpuset /lxc/x2 --cgroup-root net_cls,net_prio /lxc/x2 --cgroup-root memory /lxc/x2 --cgroup-root rdma /lxc/x2 --cgroup-root freezer /lxc/x2 --cgroup-root perf_event /lxc/x2 --cgroup-root hugetlb /lxc/x2 -vvvvvv --action-script /tmp/lxd_checkpoint_992912836/action.sh --ext-mount-map /dev/fuse dev/fuse --ext-mount-map /dev/net/tun dev/net/tun --ext-mount-map /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc --ext-mount-map /sys/fs/fuse/connections sys/fs/fuse/connections --ext-mount-map /sys/fs/pstore sys/fs/pstore --ext-mount-map /sys/kernel/debug sys/kernel/debug --ext-mount-map /sys/kernel/security sys/kernel/security --ext-mount-map /dev/mqueue dev/mqueue --ext-mount-map /dev/lxd dev/lxd --ext-mount-map /dev/.lxd-mounts dev/.lxd-mounts -t 16844 --skip-in-flight --freeze-cgroup /sys/fs/cgroup/freezer///lxc/x2 --ext-mount-map /dev/console console --external tty[8807:17] --ghost-limit 268435456
root     17749  0.0  0.0   4504   848 pts/4    S+   10:54   0:00  |           |   \_ /bin/sh -e /tmp/lxd_checkpoint_992912836/action.sh
root     17750  0.0  0.2 188260 19460 pts/4    Sl+  10:54   0:00  |           |       \_ /home/ubuntu/go/bin/lxd migratedumpsuccess /1.0/operations/42352221-e681-4c53-a2ba-87ac36d2289a 1d3ee4c417b3bc2b14617096c8a786c85ba55c93a3f063cefbc48c76399a754e
root     17791  0.0  0.0  23952  1040 pts/4    Sl+  10:54   0:00  |           \_ btrfs send /mnt/l1/storage-pools/default/snapshots/x2/.migration-send/.root
```
