### ISSUE TITLE
lxd 3.0.0: lxc copy stuck, never ends

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#4476]
lxc copy a stopped container is stuck:

lxc copy local-vpn:Wine qboxv3-vpn:
Transferring container: snap0: 4.35GB (26.33MB/s)

waiting indefinitely...

on the dest: there is a snapshot from the copy:

gquentin@sd-57286:/$ sudo du -sm var/snap/lxd/common/lxd/storage-pools/default/snapshots/Wine/snap0
4604	var/snap/lxd/common/lxd/storage-pools/default/snapshots/Wine/snap0

lxc info (source and destination are almost the same):
config:
  core.https_address: '[::]'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.37.169.152:8443
  - 172.16.12.1:8443
  - 172.16.10.1:8443
  - 172.16.11.1:8443
  - 10.8.0.6:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
  certificate_fingerprint: deb858c54df6cc8fced5fe565ec87f21824fc9265f47490ba39b642a8c2322b8
  driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-38-generic
  server: lxd
  server_pid: 9315
  server_version: 3.0.0
  storage: btrfs
  storage_version: "4.4"
  server_clustered: false
  server_name: gquentin-ssd-t3

**Comment by gaetanquentin** [comment]
it looks like the copy is ok on destination.

But the source never ends

**Comment by stgraber** [comment]
I believe that's the same issue as I'm having @brauner look at in #4475.

4475 started as a live-migration/criu problem, but the main issue is btrfs send/receive migration hanging, possibly masking errors. Closing this one, treating as duplicate, please subscribe to #4475.
