### ISSUE TITLE
Immediately return error if cluster DB is unavailable

### ISSUE THREAD

**Issue by morphis** [lxc/lxd#4479]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.10
 * The output of "lxc info":

Using multiple VMs, all with the same configuration and part of the same cluster:

```
config:
  core.https_address: 10.126.59.20:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.126.59.20:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    [...]
  certificate_fingerprint: ...
  driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-119-generic
  server: lxd
  server_pid: 3811
  server_version: 3.0.0
  storage: dir
  storage_version: "1"
  server_clustered: true
  server_name: lxd4
```

# Issue description

I've created an LXD cluster based on five VMs (using multipass and the Ubuntu 16.04 cloud image as base) and configured them all with the same storage pool, network bridge and profile. The cluster is successfully created and can be used to create containers etc.

When I now bring down two of the three database nodes, none of the other nodes in the cluster reacts to any HTTP request anymore. A simple `curl --insecure https://10.126.59.243:8443` hangs until it times out. It is fine that the cluster goes into an not-operational state but I would expect to get at least an error from the remaining nodes about this rather than a timeout.

# Steps to reproduce

 1. Create a set of VMs (I created five)
 2. Setup LXD 3.0 (`snap install --channel=3.0 lxd`) on all of them
 3. Create same bridge, storage pool etc. on all nodes and join them into the cluster
 4. Turn off two of the database nodes (find them via `lxc cluster list`)
 5. Run `curl --insecure https://10.126.59.243:8443`  (where `10.126.59.243` is the address of one of the remaining active nodes) or any `lxc ...` command on one of the remaining nodes against the unix.socket

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

Last messages in the log of one of the remaining active nodes:

```
lvl=warn msg="Failed to get events from node 10.126.59.97:8443: Unable to connect to: 10.126.59.97:8443" t=2018-04-20T10:15:30+0000
lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: gRPC grpcConnection failed: context deadline exceeded" t=2018-04-20T10:15:44+0000
lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: gRPC grpcConnection failed: context deadline exceeded" t=2018-04-20T10:15:57+0000
lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: gRPC grpcConnection failed: context deadline exceeded" t=2018-04-20T10:16:11+0000
lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: gRPC grpcConnection failed: context deadline exceeded" t=2018-04-20T10:16:50+0000
lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: gRPC grpcConnection failed: context deadline exceeded" t=2018-04-20T10:17:03+0000
lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: gRPC grpcConnection failed: context deadline exceeded" t=2018-04-20T10:17:17+0000
```

 - [x] Output of the client with --debug

```
ubuntu@lxd0:~$ lxc --debug ls
DBUG[04-20|10:17:26] Connecting to a local LXD over a Unix socket 
DBUG[04-20|10:17:26] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
```

 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by morphis** [comment]
It looks like each request starts to first talk to the database which then results in a long timeout. A request against the `/internal` API endpoint works though:

```
$ curl --insecure https://10.126.59.243:8443/internal
{"error":"not found","error_code":404,"type":"error"}
```

**Comment by stgraber** [comment]
So I guess the issue will be whether all LXD nodes can easily know that the database isn't online yet.
If they can know that, then it'd indeed be possible to return a top level error for any API query.

Note that at that point in time, LXD won't be able to do anything clever as the lack of database also means it can't validate client certificates and so would have to assume that all clients are untrusted.

**Comment by morphis** [comment]
@stgraber That sounds good to me. Some error will help to detect this a lot better than waiting for a timeout with some heuristics. Thanks!

**Comment by stgraber** [comment]
Moving to 3.2 as @freeekanayaka hasn't started work on this and 3.1 is due out on Tuesday.

**Comment by stgraber** [comment]
Moving to 3.3 for now until we address some DB performance improvements.
It's not quite as trivial as it may sound due to the way the database layer works.

This issue may also become moot as we add support for non-voting database nodes and effectively allow LXD to promote new voting database nodes as some go offline, therefore restricting the blocking API case to when there really can't be any database operations happening due to pretty much the entire cluster being offline.

**Comment by stgraber** [comment]
So the upgrade issues in LXD 3.4 showed us that we'd benefit from:
 - Clear logging (INFO or WARN level) of clusters being stuck due to version mismatches
 - Just having API calls hang until the DB is available isn't a good user experience, waiting for 10s or so is reasonable (and should account for a LXD reloading) but after that, we should return an error clearly stating either that the database isn't currently available (and if we can, how many nodes we're short of) OR that some nodes are currently out of date and the cluster is paused (reporting the target version, how many nodes have made it and how many nodes remain on an older version)

I think that'd fix that user experience issue and make it easier for us to support users.
