### ISSUE TITLE
Clarification on running older Ubuntu versions on a newer kernel

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#4484]
LXC v2.21

I suppose I could figure out the answer to this questions by doing extensive testing, but I am just another guy out here in userland and I figure you geniuses in here probably know this :)

With the impending Bionic Beaver release, I am considering how to handle upgrades for my live webserver containers. I have been aware that it is possible to grab various versions of Ubuntu from the official repository, and in my quick and dirty tests in the past I have gotten both newer and older Ubuntu versions to run on a stock 16.04 kernel (namely Zesty and Trusty)

Inside the container `uname -r` obviously reveals that the container is running on the host system kernel version, but my question here is simple, I suppose:

**Is it safe to run an older Ubuntu distribution on a newer kernel?** 

Specifically I am planning to upgrade my hosts to 18.04 Bionic once it becomes available, but I am unclear on whether I need to do a dist-upgrade immediately in all my containers, or if it is OK that they run on top of the newer kernel and I can do a phased upgrade.

My guess is that the answer will either be

 - This is a bad idea. Your distribution should always match the host distribution due to unknown effects that may crop up

or 

- This is OK due to LXD black magic, or as long as the kernel is up-to-date or newer than what the distribution expects,  and there is nothing to worry about here

or

- We are not sure, it all depends on whether the newer kernel has introduced changes that may or may not break stuff in the container.

or possibly

- You have misunderstood / misattributed the importance of the kernel version in relation to the specific Linux distribution, and your distro will work on whatever kernel you throw at it (as long as it's not too old?)

So which is it? :grinning:

**Comment by stgraber** [comment]
Running Ubuntu 16.04 containers on Ubuntu 18.04 will work perfectly fine. There's absolutely no need to rush container upgrades.

You're a lot more likely to run into problems when running very recent Linux distributions on an older kernel than the other way around. The Linux kernel is extremely backward compatible and the Ubuntu kernel usually has most of those older features enabled.

I know that on Ubuntu 18.04, I've been running Ubuntu 14.04 and 16.04 containers just fine for months and remember trying all the way down to Ubuntu 8.04 for a customer at some point, without it needing much tweaking (just an upstart tweak if I recall correctly).

**Comment by stgraber** [comment]
As for your options above, it's somewhere between 2 and 4 :)

There isn't a very strong userspace/kernelspace relationship on most distros these days, even more so with Ubuntu as Ubuntu itself ships with various kernel releases in a specific Ubuntu release (16.04 currently has 4.4 or 4.13 or 4.15).

Our recommendation is to stick to the latest supported kernel you can get from your distro, that will give you the most compatibility with newer releases in containers and get you any new kernel feature we've been pushing for LXD.
