### ISSUE TITLE
Implement cloud image support in lxd-images

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#449]

**Comment by nmathew** [comment]
what is the requirement here?

**Comment by stgraber** [comment]
We're waiting for the Ubuntu cloud folks to build a lxd compatible image.

**Comment by stgraber** [comment]
And it's finally possible to do "lxd-images import ubuntu".

Currently it only lets you import from the daily stream and default to wily. As other releases are added on the server, we'll change that to defaulting to trusty (or latest LTS).

This also only lets you do one-shot imports. There's the plan to store extra metadata in the store and then support a cronnable "lxd-images sync" but that'll be for later.

For right now, we finally have Ubuntu Cloud images support so closing this issue.
