### ISSUE TITLE
lxc launch fails after fresh install

### ISSUE THREAD

**Issue by grwilson** [lxc/lxd#4498]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 beta amd64
 * The output of "lxc info" or if that fails:

```
Name: u1604
Remote: unix://
Architecture: x86_64
Created: 2018/04/25 15:12 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc 20180425151309.321 ERROR    lxc_lsm - lsm/lsm.c:lsm_process_label_set_at:167
 - No such file or directory - Failed to set AppArmor label "lxc-container-defau
lt-cgns"
lxc 20180425151309.321 ERROR    lxc_apparmor - lsm/apparmor.c:apparmor_process_l
abel_set:243 - No such file or directory - Failed to change apparmor profile to 
lxc-container-default-cgns
lxc 20180425151309.322 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occu
rred in another process (expected sequence number 5)
lxc 20180425151309.361 ERROR    lxc_container - lxccontainer.c:wait_on_daemonize
d_start:824 - Received container state "ABORTING" instead of "RUNNING"
lxc 20180425151309.366 ERROR    lxc_start - start.c:__lxc_start:1866 - Failed to
 spawn container "u1604"
lxc 20180425151309.382 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:130 -
 Connection reset by peer - Failed to receive response for command "get_cgroup"
```

   * Kernel version: 4.15
   * LXC version: 3.0
   * LXD version: 3.0
   * Storage backend in use: ZFS

# Issue description

I'm unable to launch any containers in this configuration. The launch gets pretty far before failing with the errors shown above.

# Steps to reproduce

 1. Configure ZFS root with Ubuntu 18.04
 2. lxd init
 3. lxc launch

# Information to attach

 - [X ] Any relevant kernel output (`dmesg`)
 - [X] Container log (`lxc info NAME --show-log`)
 - [X ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

[dmesg.txt](https://github.com/lxc/lxd/files/1947793/dmesg.txt)
[lxc_config.txt](https://github.com/lxc/lxd/files/1947794/lxc_config.txt)
[lxc_info.txt](https://github.com/lxc/lxd/files/1947795/lxc_info.txt)

**Comment by stgraber** [comment]
Can you show `/var/log/lxd/u1604/lxc.conf`?

**Comment by stgraber** [comment]
For some reason your container is trying to switch to a non-existing apparmor profile rather than the one that's generated by LXD.

**Comment by grwilson** [comment]
Here you go:
```
lxc.log.file = /var/log/lxd/u1604/lxc.log
lxc.log.level = warn
lxc.console.buffer.size = auto
lxc.console.size = auto
lxc.console.logfile = /var/log/lxd/u1604/console.log
lxc.mount.auto = proc:rw sys:rw
lxc.autodev = 1
lxc.pty.max = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/security sys/kernel/security none rbind,create=dir,optional
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional
lxc.include = /usr/share/lxc/config/common.conf.d/
lxc.arch = linux64
lxc.hook.pre-start = /usr/lib/lxd/lxd callhook /var/lib/lxd 1 start
lxc.hook.post-stop = /usr/lib/lxd/lxd callhook /var/lib/lxd 1 stop
lxc.tty.max = 0
lxc.uts.name = u1604
lxc.mount.entry = /var/lib/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.seccomp.profile = /var/lib/lxd/security/seccomp/u1604
lxc.idmap = u 0 165536 65536
lxc.idmap = g 0 165536 65536
lxc.rootfs.path = dir:/var/lib/lxd/containers/u1604/rootfs
lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.link = lxdbr0
lxc.net.0.hwaddr = 00:16:3e:09:56:8e
lxc.net.0.name = eth0
lxc.mount.entry = /var/lib/lxd/shmounts/u1604 dev/.lxd-mounts none bind,create=dir 0 0
```

**Comment by stgraber** [comment]
Looks like LXD thinks apparmor support is missing on your system, but liblxc disagrees... That's pretty unusual.

What does the following show:
 - dpkg -l | grep apparmor
 - which apparmor_parser
 - ls -lh /sys/kernel/security

**Comment by stgraber** [comment]
`apt install apparmor` should fix things for you

**Comment by stgraber** [comment]
Or if this was removed on purpose, then you can tell liblxc about it by setting `raw.lxc` to `lxc.apparmor.profile=unconfined` in your default profile.

**Comment by stgraber** [comment]
I added a recommend to the Ubuntu package in our packaging branch which should help any other user installing LXD by hand on a system without apparmor.

**Comment by grwilson** [comment]
@stgraber thank you for the suggestions. I installed apparmor and tried again and it still fails:

# which apparmor_parser
/sbin/apparmor_parser

# lxc start u1604
Error: Failed to run: /usr/lib/lxd/lxd forkstart u1604 /var/lib/lxd/containers /var/log/lxd/u1604/lxc.conf: 
Try `lxc info --show-log u1604` for more info

# lxc info --show-log u1604
Name: u1604
Remote: unix://
Architecture: x86_64
Created: 2018/04/25 17:29 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc 20180425174228.637 ERROR    lxc_lsm - lsm/lsm.c:lsm_process_label_set_at:167 - No such file or directory - Failed to set AppArmor label "lxc-container-default-cgns"
lxc 20180425174228.638 ERROR    lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:243 - No such file or directory - Failed to change apparmor profile to lxc-container-default-cgns
lxc 20180425174228.638 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
lxc 20180425174228.673 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:824 - Received container state "ABORTING" instead of "RUNNING"
lxc 20180425174228.676 ERROR    lxc_start - start.c:__lxc_start:1866 - Failed to spawn container "u1604"
lxc 20180425174228.690 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:130 - Connection reset by peer - Failed to receive response for command "get_cgroup"

**Comment by grwilson** [comment]
I can confirm that after running `lxc config set u1604 raw.lxc "lxc.apparmor.profile=unconfined"` I was able to start the container.

**Comment by grwilson** [comment]
Not sure why installing apparmor was not enough but I'm happy to provide more info.

**Comment by stgraber** [comment]
@grwilson you'd need to restart LXD too as apparmor support is detected on startup.

To get back to having containers protected by apparmor, the following should work:

 - systemctl restart lxd
 - lxc config unset u1604 raw.lxc
 - lxc restart u1604

That's assuming that apparmor itself doesn't need a system restart to reload all profiles, not too sure about that part.

**Comment by grwilson** [comment]
@stgraber that fixed it! Thank you so much for the quick turnaround.
