### ISSUE TITLE
Add more output format for lxc remote list

### ISSUE THREAD

**Issue by kaneg** [lxc/lxd#4500]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-121-generic
   * LXC version: 3.0.0
   * LXD version: 3.0.0
   * Storage backend in use: btrfs

# Issue description
For now,  **lxc remote** can output a table which is good for human readable but not suitable for program use. I want to get a well format output of **lxc remote** for later used by programs.

Actually, the **lxc list** has a parameter **--format** which can support csv|json|table|yaml is good enough.
Wish **lxc remote** can support the same function.

Besides, **lxc remote** has a subcommand **set-url**, if it has a **get-url** would be even better. For example,
```
$ lxc remote get-url mylxd
https://192.168.1.1:8443
```

**Comment by stgraber** [comment]
Sounds reasonable to add the usual set of --format options to that one too. I wish we had a nice generic way to do it for all of them, but they're all subtly different...
