### ISSUE TITLE
Failed to load raw.lxc when trying lxc.aa_profile=unconfined

### ISSUE THREAD

**Issue by eraserix** [lxc/lxd#4501]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04.5
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-121-generic
   * LXC version: 3.0.0
   * LXD version: 3.0.0 (snap 6729)
   * Storage backend in use: btrfs

# Issue description

I tried to configure a privileged container to also run unconfined. However, this fails on my system.

```
$ lxc init images:debian/8 d8 -c security.privileged=true -c raw.lxc="lxc.aa_profile=unconfined"
Creating d8
Error: Failed container creation: Failed to load raw.lxc
```

**Comment by brauner** [comment]
Right, starting with `LXC 2.1` we have deprecated legacy configuration keys and have removed all support for them starting with `LXC 3.0`. You should simply replace `lxc.aa_profile` with `lxc.apparmor.profile`. A full list of keys can be gathered from the [`LXC 2.1` release announcement](https://discuss.linuxcontainers.org/t/lxc-2-1-has-been-released).
