### ISSUE TITLE
lxd 2.0 change /var/lib/lxd dir

### ISSUE THREAD

**Issue by Fullmetal8ender** [lxc/lxd#4503]
Hi. Is it possible to change  /var/lib/lxd or /var/lib/lxd/containers dir?

**Comment by monstermunchkin** [comment]
Yes, you need to set the [`LXD_DIR`](https://github.com/lxc/lxd/blob/master/doc/environment.md#common) environment variable.

**Comment by Fullmetal8ender** [comment]
Thanks!

**Comment by stgraber** [comment]
That's not always super practical on a standard installation though, in those cases, the easiest tends to be to bind-mount /var/lib/lxd away to where you have more storage space.

In this case, you'd do:
 - Stop all your containers
 - systemctl stop lxd lxd.socket
 - Move /var/lib/lxd where you want it
 - Create an empty /var/lib/lxd
 - Setup a mount entry in /etc/fstab like `/new/location/lxd /var/lib/lxd none bind 0 0`
 - Mount it with `mount /var/lib/lxd`
 - Start LXD again with `systemctl start lxd`
