### ISSUE TITLE
Bionic LTS upgrade breaks LXD due to apparmor missing

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#4504]
Hello

Upgraded today on a test system from Ubuntu 16.04 LTS to 18.04 LTS using the recommended upgrade guide [link](https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes)

LXD version before upgrade: 2.21 after upgrade: 3.0.0

I noticed during the upgrade that it removed apparmor. After succesful system upgrade and a reboot, I cannot start my containers and the log shows:

```
Name: testdukat
Remote: unix://
Architecture: x86_64
Created: 2018/04/26 12:52 UTC
Status: Stopped
Type: persistent
Profiles: webdockssd50

Log:

lxc 20180426170532.366 ERROR    lxc_lsm - lsm/lsm.c:lsm_process_label_set_at:167 - No such file or directory - Failed to set AppArmor label "lxc-container-default-cgns"
lxc 20180426170532.366 ERROR    lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:243 - No such file or directory - Failed to change apparmor profile to lxc-container-default-cgns
lxc 20180426170532.366 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
lxc 20180426170532.437 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:824 - Received container state "ABORTING" instead of "RUNNING"
lxc 20180426170532.437 ERROR    lxc_start - start.c:__lxc_start:1866 - Failed to spawn container "testdukat"
lxc 20180426170532.449 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:130 - Connection reset by peer - Failed to receive response for command "get_cgroup"

```
Is this just a matter of waiting till apparmor releases compatible packages for 18.04 ?

**Comment by stgraber** [comment]
We had a similar report before. I'm not sure why apparmor would get removed from your system on upgrade, this seems like a potential security problem...

I'd recommend you file a bug at https://launchpad.net/ubuntu/+source/apparmor/+filebug to track down why apparmor is getting removed.

As for LXD, the other reporter was able to fix things with:
 - sudo apt install apparmor
 - systemctl restart lxd

The next LXD upload to Ubuntu will add a Recommends of apparmor to the package, hoping this may somehow prevent this from happening until someone figures out why apparmor is getting removed for some users.

**Comment by stgraber** [comment]
Closing as not a LXD issue by itself, apparmor comes with ubuntu-standard, neither of those packages should get removed on upgrade...

**Comment by Kramerican** [comment]
@stgraber Ok yeah that is interesting indeed. Especially since this was a completely vanilla 16.04 install which I made just today to test this upgrade path. As in, completely up to date, and no weird config before upgrading. So this should be easily reproducible.

I can confirm that after reinstalling apparmor and restarting the daemon my containers come up immediately (impressively fast - love it!)

I'll file a report with apparmor :+1:

**Comment by stgraber** [comment]
@Kramerican how did you do the upgrade? Was that with do-release-upgrade?

**Comment by Kramerican** [comment]
@stgraber Yes I did a `do-release-upgrade -d` as indicated on wiki.ubuntu.com

**Comment by stgraber** [comment]
Just did an upgrade test with a clean 16.04 with LXD 2.0.11, resulting upgrade still had apparmor installed.
Repeated this time with LXD 2.21 from backports, same result, apparmor still present post upgrade.

Any extra details on what could have caused a different result for you?

**Comment by Kramerican** [comment]
That is ... Interesting. All I can think of is that the base system is set up using Hetzners (hetzner.de) Ubuntu 16.04 minimal image. They might have messed around with the base image - although my impression was that their image was squeaky-clean.

I really have no explanation for this. Looking at the packages we install post-base system install, I see we are not installing apparmor, so it is already present in the Hetzner image.

In any case, let's hope this issue can help others who might run into the same.

**Comment by stgraber** [comment]
Does that base image come with `ubuntu-standard` installed? If not, I can see how the upgrade script may remove some of those packages.

**Comment by ktechmidas** [comment]
Just run into the same, upgrading from a completely vanilla 16.04.4 to 18.04, I had to do 'do-release-upgrade -d' to get it to actually upgrade though.

Glad this issue is here or I would have been chasing it forever.
