### ISSUE TITLE
lxd appears to cause host to hibernate

### ISSUE THREAD

**Issue by ItStillDoesNotWork** [lxc/lxd#4507]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.10
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 2.18
   * LXD version: 2.18
   * Storage backend in use:

# Issue description

I installed lxd and lxc / lxc2, and created my first container with Ubuntu 16.04. I ran out of time to do what I wanted to do, but of course that container was still there and running.

When I came to use the computer again I found that it would "randomly" go to black. I couldn't tell what was happening at all - sometimes it would take several attempts to get back to a running system. Bear in mind, I was still not using the container at this point, it was just sitting there in the background.

Investigating, I found that in syslog there were incidents like this:

```Apr 21 19:37:38 ash systemd[1]: Starting systemd-resolved-update-resolvconf.service...
Apr 21 19:37:38 ash systemd[1]: Started systemd-resolved-update-resolvconf.service.
Apr 21 19:37:38 ash systemd[1]: Reached target Sleep.
Apr 21 19:37:38 ash systemd[1]: Starting Hibernate...
Apr 21 19:37:38 ash wpa_supplicant[2886]: nl80211: deinit ifname=wlp2s0 disabled_11b_rates=0
Apr 21 19:37:38 ash kernel: [  334.756340] PM: Hibernation mode set to 'platform'
Apr 21 19:37:39 ash systemd-sleep[5396]: Suspending system...
Apr 21 19:37:39 ash kernel: [  335.146847] PM: Syncing filesystems ... 
Apr 21 19:39:45 ash kernel: [  335.386311] PM: done.
```
which more or less, according to memory, matched with the behaviour I described above.

The only thing I'd changed on the system was installing lxc/lxd so I removed that and... haven't had a problem since. Make of that what you will.

The only other thing that was different when I encountered the problems was the network I was using, which was rather unreliable, but the computer didn't black screen every time there was a problem with the network so I'm not sure that was the cause.

**Comment by stgraber** [comment]
Going to close this for now as we've never heard of such symptoms when using LXD 2.0.x on 16.04 nor would LXD have any hook into the system suspend mechanism.

It might be interesting for you to review a longer chunk of the systemd journal to see if all such occurrences of the computer screen going off matches a systemd suspend/hibernate as you showed above. If so, then try to track down what trigger the suspend/hibernation, with a bit of luck there will be clues in the journal too.
