### ISSUE TITLE
Optimized UDP/TCP proxying (NAT)

### ISSUE THREAD

**Issue by esosan** [lxc/lxd#4512]
Hi again,
I was really happy for this new feature, but then I have a sad discover: on the containers the proxied connections comes always from lxdbr0 ip.

It would be nice to expand this feature to nat the incoming connection to the container.

Best regards, Davide

**Comment by stgraber** [comment]
Ok, so to make this vaguely doable, we have to scope it a lot.

We can only do this optimization if the target address in the container isn't set or if it's set to the IPv4 address matching `ipv4.address` for that container. We also need to require the container to be connected to a LXD managed bridge and to have a static `ipv4.address` set for that device.

That way LXD can be vaguely confident that the host is in fact the router for that container, that the service in the container is listening on a usable IP and that this IP is known.

**Comment by esosan** [comment]
Hi Stéphane, that seems to be a standard single machine lxd installation.
Do you think it's possibile to ipv6 too?

**Comment by stgraber** [comment]
Yeah, ipv6 would be fine too with the same restrictions.

It's a standard LXD install with the exception that we'd require ipv4.address or ipv6.address to be set on the nic as otherwise LXD won't know what address to NAT to.

**Comment by stgraber** [comment]
We should be able to do it transparently though, so if all the right bits are set, you get NAT, if you're missing some bits, you get proxy.

**Comment by esosan** [comment]
maybe I don't understand exactly. do you mean something like this for my lxdbr0?  

~$ lxc network show lxdbr0
config:
  ipv4.address: 10.4.43.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:26ae:9c2f:e23::1/64
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/***
managed: true
status: Created
locations:
- none

**Comment by stgraber** [comment]
No, I mean the entry on the container.
You'd do that with:

```
lxc config device override c1 eth0 ipv4.address=10.4.43.42
```

Then that container will have a fixed 10.4.43.42 IP address handed over to it by DHCP which LXD can then rely on.

**Comment by esosan** [comment]
ohh ok, it's sound reasonable! very nice! I start to switch ips...

**Comment by lenucksi** [comment]
Such a feature would be highly appreciated. Current approaches revolve around SNAT/DNAT rule combinations and a scripting around them to properly react to the container lifecycle. Removing the need for these would be very nice.

See also these for reference:
- https://github.com/evanhempel/lxc-portforward 
- https://github.com/sebgrohn/lxd-portforward
- https://github.com/JustinJudd/lxd-port-forward

**Comment by mazerty** [comment]
hello ! thanks for the feature !
can this be backported to 3.0.x please ?

**Comment by stgraber** [comment]
No, this is a new feature and therefore unsuitable for backporting into the LTS branch.
LTS releases only get bugfixes and security fixes, no new features.

**Comment by mazerty** [comment]
alright :) thank you !
