### ISSUE TITLE
Snap Updated my database [lxd 3.0.0]

### ISSUE THREAD

**Issue by ElijahTikus21** [lxc/lxd#4519]
#  Required information
- Distribution: Ubuntu 
 - Distribution version:1 6.04 LTS 
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686

# Issue description
Hi,
After the last reboot today, snap has updated the lxd snap, now containers dispeared the database is empty. How to rebuilt the database ?

Thank you.

# Information to attach
```
lxc list
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+

ls -la /var/snap/lxd/common/
total 32
drwxr-xr-x  5 root root 4096 mai    2 10:38 .
drwxr-xr-x  6 root root 4096 mai    1 22:07 ..
-rw-r--r--  1 root root  173 mai    1 22:07 config
drwxr-xr-x  2 root root 4096 avril  9 09:16 lxc
-rw-------  1 root root    5 mai    2 10:14 lxcfs.pid
drwxr-xr-x 15 root root 4096 mai    2 10:38 lxd
-rw-r--r--  1 root root    5 mai    2 10:38 lxd.pid
lrwxrwxrwx  1 root root   15 mai    2 10:38 mntns -> /proc/4601/root
drwxr-xr-x  3 root root 4096 avril  9 09:16 var

```

**Comment by ElijahTikus21** [comment]
``
/var/snap/lxd/common/lxd# ll
total 68
drwxr-xr-x 15 root root 4096 mai    2 10:38 ./
drwxr-xr-x  5 root root 4096 mai    2 10:38 ../
drwx------  2 root root 4096 mai    2 10:38 cache/
drwx--x--x  2 root root 4096 mai    2 10:14 containers/
drwx------  3 root root 4096 mai    2 10:38 database/
drwx--x--x  2 root root 4096 mai    2 10:14 devices/
drwxr-xr-x  2 root root 4096 mai    2 10:14 devlxd/
drwx------  2 root root 4096 mai    2 10:14 disks/
drwx------  2 root root 4096 mai    2 10:14 images/
drwx------  2 root root 4096 mai    2 10:38 logs/
drwx--x--x  2 root root 4096 mai    2 10:14 networks/
drwx------  2 root root 4096 mai    2 10:14 security/
-rw-r--r--  1 root root 1992 mai    2 10:38 server.crt
-rw-------  1 root root 3243 mai    2 10:38 server.key
drwx--x--x  2 root root 4096 mai    2 10:14 shmounts/
drwx------  2 root root 4096 mai    2 10:14 snapshots/
drwx--x--x  2 root root 4096 mai    2 10:14 storage-pools/
srw-rw----  1 root lxd     0 mai    2 10:38 unix.socket=

var/snap/lxd/common/lxd/database# ls -la
total 52
drwx------  3 root root  4096 mai    2 10:38 .
drwxr-xr-x 15 root root  4096 mai    2 10:38 ..
drwxr-x---  3 root root  4096 mai    2 10:38 global
-rw-r--r--  1 root root 40960 mai    2 10:14 local.db

snap changes
ID   Status  Spawn                 Ready                 Summary
29   Done    2018-05-01T20:06:46Z  2018-05-01T20:07:19Z  Auto-refresh snap "lxd"

**Comment by stgraber** [comment]
Hmm, that's odd, there are no database backups there for any of the databases, new or old... This looks like a completely clean LXD installation...

What's in `/var/snap/lxd/common/lxd/containers` and `/var/snap/lxd/common/lxd/storage-pools/`?

**Comment by stgraber** [comment]
And do you still have some stuff in `/var/lib/lxd` and `/var/lib/lxd/containers` maybe?
I'm wondering if the problem is a partial transition to the snap here.

**Comment by ElijahTikus21** [comment]
/var/snap/lxd/common/lxd/containers# ls -la
total 8
drwx--x--x  2 root root 4096 mai    2 10:14 .
drwxr-xr-x 15 root root 4096 mai    2 10:38 ..

var/snap/lxd/common/lxd/storage-pools# ls -la
total 8
drwx--x--x  2 root root 4096 mai    2 10:14 .
drwxr-xr-x 15 root root 4096 mai    2 10:38 ..

/var/lib/lxd.orig# ls -la
total 164
drwxr-xr-x 12 lxd  nogroup  4096 mai   17  2017 .
drwxr-xr-x 48 root root     4096 avril 10 16:51 ..
drwx--x--x  2 root root     4096 janv. 16  2017 containers
drwx--x--x  2 root root     4096 janv. 16  2017 devices
drwxr-xr-x  2 root root     4096 mai   17  2017 devlxd
drwx------  2 root root     4096 mai   17  2017 disks
drwx------  2 root root     4096 janv. 16  2017 images
-rw-r--r--  1 root root    58368 mai   17  2017 lxd.db
-rw-r--r--  1 root root    41984 mai   17  2017 lxd.db.bak
drwx--x--x  3 root root     4096 mai   17  2017 networks
drwx------  2 root root     4096 janv. 16  2017 security
-rw-r--r--  1 root root     1915 janv. 16  2017 server.crt
-rw-------  1 root root     3243 janv. 16  2017 server.key
drwx--x--x  2 root root     4096 janv. 16  2017 shmounts
drwx------  2 root root     4096 janv. 16  2017 snapshots
drwx--x--x  2 root root     4096 mai   17  2017 storage-pools
srw-rw----  1 root lxd         0 mai   17  2017 unix.socket

/var/lib/lxd.orig/containers# ls -la
total 8
drwx--x--x  2 root root    4096 janv. 16  2017 .
drwxr-xr-x 12 lxd  nogroup 4096 mai   17  2017 ..

**Comment by stgraber** [comment]
Ok, so there's literally no data whatsoever inside the LXD snap storage... so it's not just a database problem there.

Your /var/lib/lxd.orig looks old (May 2017) so that doesn't look like it was used on this system.

Do you have some other storage path that was used to contain the snap data, possibly manually mounted on top of /var/snap/lxd/common/lxd? That'd explain what looks like a full reset of the LXD data here.

It may be useful if you could provide the entire output of `journalctl -u snap.lxd.daemon` too?

**Comment by ElijahTikus21** [comment]
initial btrfs mount point is here:
 ls -la /mnt/ROOT/@lxd/storage-pools/default/containers/



total 0
drwx--x--x  1 root    root    748 avril 25 14:18 .
drwx--x--x  1 root    root     62 mai   17  2017 ..
drwxr-x--x+ 1 1000000 1000000  78 avril 25 14:18 apache-archiva
drwx--x--x+ 1  100000  100000  78 févr. 23 16:40 auth
drwx--x--x+ 1  100000  100000  78 oct.   5  2017 centos6-devel
drwx--x--x+ 1  100000  100000  78 févr. 23 13:34 centos7-devel
drwx--x--x+ 1  100000  100000  78 janv.  3 13:19 CentOS7-MongoDB
drwx--x--x+ 1  100000  100000  78 mars  22 11:39 cplmca-p-v01
drwx------+ 1 root    root     78 mars  23 16:16 cplmca-red-p-v01
drwx--x--x+ 1  100000  100000  78 oct.  18  2017 cplsso-auth-p-v01
drwx--x--x+ 1  100000  100000  78 oct.  18  2017 cplsso-auth-p-v01-2
drwx--x--x+ 1  100000  100000  78 mars  29 11:09 databases
drwx--x--x+ 1  100000  100000  78 févr. 28 16:59 elasticsearch
drwx------+ 1 root    root     78 avril 12 16:40 openshift-origin
drwx--x--x  1  100000  100000  78 oct.  31  2017 pfi-redis-master
drwx--x--x+ 1  100000  100000  78 oct.  31  2017 pfi-saltmaster-2017-7-4
drwx--x--x+ 1  100000  100000  78 oct.  31  2017 pfi-saltmaster-2018-3
drwx------  1 root    root     78 mars  19 14:28 Redhat6
drwx------  1 root    root     78 mars  14 16:12 Redhat7
drwx--x--x+ 1  100000  100000  78 nov.  23 14:50 rh5-11
drwx--x--x+ 1  100000  100000  78 févr. 28 09:29 salt-ubuntu-xenial
drwx--x--x+ 1 root    root     78 oct.  31  2017 services
drwx--x--x+ 1  100000  100000  78 févr. 28 09:47 services-in
drwx--x--x+ 1  100000  100000  78 févr. 28 09:49 telemetrie
drwx------  1 root    root     78 mars  19 14:28 test-RH6-PP
drwx------  1 root    root     78 mars  19 14:28 test-RH6-PROD
drwx------  1 root    root     78 mars  14 16:12 test-RH7-PP
drwx------  1 root    root     78 mars  14 16:12 test-RH7-PROD
drwx--x--x+ 1  100000  100000  78 mars   6 09:48 ubuntu16-devel
drwx--x--x+ 1  100000  100000  78 juil. 31  2017 ubuntu-xenial
drwx--x--x+ 1  100000  100000  78 nov.   8 09:56 xenial-java

snap mounted it elsewhere and it was working until last reboot


journalctl -u snap.lxd.daemon:

- Logs begin at mer. 2018-05-02 10:13:46 CEST, end at mer. 2018-05-02 12:06:19 CEST. --
mai 02 10:14:32 vipteam_lab.jmsp.prod systemd[1]: Started Service for snap application lxd.daemon.
mai 02 10:14:38 vipteam_lab.jmsp.prod lxd.daemon[3503]: => Preparing the system
mai 02 10:14:38 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Loading snap configuration
mai 02 10:14:38 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Setting up mntns symlink
mai 02 10:14:38 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Setting up kmod wrapper
mai 02 10:14:39 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Preparing /boot
mai 02 10:14:39 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Preparing a clean copy of /run
mai 02 10:14:39 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Preparing a clean copy of /etc
mai 02 10:14:42 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Setting up ceph configuration
mai 02 10:14:42 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Setting up LVM configuration
mai 02 10:14:42 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Rotating logs
mai 02 10:14:42 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Setting up ZFS (0.6)
mai 02 10:14:42 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Escaping the systemd cgroups
mai 02 10:14:42 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Escaping the systemd process resource limits
mai 02 10:14:42 vipteam_lab.jmsp.prod lxd.daemon[3503]: ==> Increasing the number of inotify user instances
mai 02 10:14:42 vipteam_lab.jmsp.prod lxd.daemon[3503]: => Starting LXCFS
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]: => Starting LXD
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]: mount namespace: 5
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]: hierarchies:
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]:   0: fd:   6: cpuset
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]:   1: fd:   7: freezer
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]:   2: fd:   8: memory
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]:   3: fd:   9: net_cls,net_prio
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]:   4: fd:  10: pids
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]:   5: fd:  11: blkio
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]:   6: fd:  12: cpu,cpuacct
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]:   7: fd:  13: perf_event
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]:   8: fd:  14: hugetlb
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]:   9: fd:  15: devices
mai 02 10:14:43 vipteam_lab.jmsp.prod lxd.daemon[3503]:  10: fd:  16: name=systemd
mai 02 10:14:46 vipteam_lab.jmsp.prod lxd.daemon[3503]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be i
mai 02 10:14:52 vipteam_lab.jmsp.prod lxd.daemon[3503]: lvl=warn msg="Connecting to LXD daemon (attempt 11)" t=2018-05-02T08:14:52+000
mai 02 10:14:52 vipteam_lab.jmsp.prod lxd.daemon[3503]: lvl=warn msg="Failed connecting to LXD daemon (attempt 11): Get http://unix.so
mai 02 10:15:15 vipteam_lab.jmsp.prod lxd.daemon[3503]: lvl=warn msg="Connecting to LXD daemon (attempt 12)" t=2018-05-02T08:15:15+000
mai 02 10:15:15 vipteam_lab.jmsp.prod lxd.daemon[3503]: lvl=warn msg="Failed connecting to LXD daemon (attempt 12): Get http://unix.so
mai 02 10:38:05 vipteam_lab.jmsp.prod lxd.daemon[3503]: lvl=warn msg="Connecting to LXD daemon (attempt 13)" t=2018-05-02T08:38:05+000
mai 02 10:38:05 vipteam_lab.jmsp.prod lxd.daemon[3503]: lvl=warn msg="Failed connecting to LXD daemon (attempt 13): Get http://unix.so
mai 02 10:38:05 vipteam_lab.jmsp.prod lxd.daemon[3503]: Error: LXD still not running after 600s timeout
mai 02 10:38:05 vipteam_lab.jmsp.prod systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=1/FAILURE
mai 02 10:38:06 vipteam_lab.jmsp.prod lxd.daemon[4268]: => Stop reason is: crashed
mai 02 10:38:06 vipteam_lab.jmsp.prod systemd[1]: snap.lxd.daemon.service: Unit entered failed state.
mai 02 10:38:06 vipteam_lab.jmsp.prod systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
mai 02 10:38:06 vipteam_lab.jmsp.prod systemd[1]: snap.lxd.daemon.service: Service hold-off time over, scheduling restart.
mai 02 10:38:06 vipteam_lab.jmsp.prod systemd[1]: Stopped Service for snap application lxd.daemon.
mai 02 10:38:06 vipteam_lab.jmsp.prod systemd[1]: Started Service for snap application lxd.daemon.
mai 02 10:38:06 vipteam_lab.jmsp.prod lxd.daemon[4601]: => Preparing the system
mai 02 10:38:06 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Loading snap configuration
mai 02 10:38:06 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Setting up mntns symlink
mai 02 10:38:06 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Setting up kmod wrapper
mai 02 10:38:06 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Preparing /boot
mai 02 10:38:06 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Preparing a clean copy of /run
mai 02 10:38:07 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Preparing a clean copy of /etc
mai 02 10:38:07 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Setting up ceph configuration
mai 02 10:38:07 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Setting up LVM configuration
mai 02 10:38:07 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Rotating logs
mai 02 10:38:07 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Setting up ZFS (0.6)
mai 02 10:38:07 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Escaping the systemd cgroups
mai 02 10:38:07 vipteam_lab.jmsp.prod lxd.daemon[4601]: ==> Escaping the systemd process resource limits
mai 02 10:38:07 vipteam_lab.jmsp.prod lxd.daemon[4601]: => Re-using existing LXCFS
mai 02 10:38:07 vipteam_lab.jmsp.prod lxd.daemon[4601]: => Starting LXD
mai 02 10:38:07 vipteam_lab.jmsp.prod lxd.daemon[4601]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be i
mai 02 10:38:07 vipteam_lab.jmsp.prod lxd.daemon[4601]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be i
mai 02 10:38:12 vipteam_lab.jmsp.prod lxd.daemon[4601]: lvl=warn msg="Connecting to LXD daemon (attempt 11)" t=2018-05-02T08:38:12+000
mai 02 10:38:12 vipteam_lab.jmsp.prod lxd.daemon[4601]: lvl=warn msg="Checking if LXD daemon is ready (attempt 11)" t=2018-05-02T08:38
mai 02 10:38:12 vipteam_lab.jmsp.prod lxd.daemon[4601]: => LXD is ready
mai 02 10:38:20 vipteam_lab.jmsp.prod lxd.daemon[3503]: lvl=eror msg="Failed to start the daemon: failed to create raft factory: faile
mai 02 10:38:20 vipteam_lab.jmsp.prod lxd.daemon[3503]: Error: failed to create raft factory: failed to create bolt store for raft log
l

**Comment by stgraber** [comment]
Can you run:

```
find / -name db.bin
```

That's going to take a while but may hopefully find any other location for the old LXD db.

Since you have the containers in /mnt/ROOT/ we should at least be able to reimport those if we can't a copy of the database. What's the filesystem behind that /mnt/ROOT/... stuff?

**Comment by gaetanquentin** [comment]
root@vipteam_lab:~# find / -name db.bin
/mnt/ROOT/@lxd/database/global/db.bin
/var/snap/lxd/common/lxd/database/global/db.bin


 /mnt/ROOT/ is btrfs

**Comment by stgraber** [comment]
Can you post `ls -lh /mnt/ROOT//global/db.bin`?

**Comment by stgraber** [comment]
Actually, "ls -lh /mnt/ROOT/global" would be good too

**Comment by ElijahTikus21** [comment]
This problem has resolved.

Thank you
