### ISSUE TITLE
Image copy between two LXD instances using short hash is failing

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#452]
Can be reproduced with:
     lxc image copy lxd1:c8 lxd2:

**Comment by jensg-st** [comment]
It might be in the imageExport in images.go. In line 602 it is

```path := shared.VarPath("images", hash)```

but it should be

```path := shared.VarPath("images", imgInfo.Fingerprint)```

Don't know if that is the error you have experienced, but even export as a standalone service didn't work for me.

**Comment by stgraber** [comment]
Looks like that did the trick here. Want to send a branch?

**Comment by jensg-st** [comment]
yes, will do
