### ISSUE TITLE
LXD-3.0 Latest uid/gid mapping problem + Temp Fix

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#4522]
I've seen this problem several times + have now isolated how to fix it.

Problem occurs when containers are copied between many machines, where sometimes uid/gid mapping seems to have been lost.

I've been able to recreate this as follows.

1) machine1: Launch a container c1 (create/start)

2) machine1: Stop the container c1

3) machine1: Copy container to machine2 as c1

4) machine1: copy container from machine2 to machine1 as c2

5) machine1: start c2

At this point uid/gid mappings in c2 are lost. All uids/gids are numbers, rather than mapped to /etc/passwd + /etc/group.

6) machine1: destroy c2

7) machine2: stop + start c1 copied over from machine1

8) machine1: copy container from machine2 to machine1 as c2

9) machine1: start c2

At this point uid/gid mappings are correct.

So there's something about a copy between machines with no start on intermediary machines which looses uid/gid mappings.

And fix is just to start/stop container on any intermediary machine.

Hopefully this information suffices to create a fix for this problem.

**Comment by davidfavor** [comment]
Reference [https://github.com/lxc/lxd/issues/4279](https://github.com/lxc/lxd/issues/4279) of previous related bug.

**Comment by davidfavor** [comment]
The scenario mentioned above breaks all uid/gid mappings, not just root.

**Comment by davidfavor** [comment]
Just verified this on 13x containers + temp fix works consistently.

One machine is LXD-2.15 install via APT/deb.

Other machine is Bionic fresh install (no update) with latest LXD-3.0 (including yesterday's patch you published) installed via SNAP.

LXD init sequence on both machines...
```
lxd init --auto --storage-backend=dir
lxc network create lxdbr0
lxc network attach-profile lxdbr0 default eth0
```
So neither ZFS of BTRFS issues come into play.

**Comment by stgraber** [comment]
Ah, ok, so yes, that's likely a bug we fixed quite a while ago in the migration code but that requires the source to be updated to 2.21 (possibly a bit earlier than that would work too).

I'll try to reproduce migrating between 2.21 and 3.0, if I can't, then I'll close this issue as there's unfortunately nothing we can do in 3.0 to make up for the missing migration data.

One alternative workaround would be to mark the source container privileged and restart it prior to moving. So effectively:

    lxc config set source:c1 security.privileged true
    lxc restart source:c1
    lxc stop source:c1
    lxc move source:c1 dest:
    lxc config unset dest:c1 security.privileged
    lxc start dest:c1

Note that the restart+stop is required so that the filesystem is properly unmapped on the source.

**Comment by davidfavor** [comment]
Ah... Your fix is even better. I hadn't thought of toggling privileged on/off.

Thanks.

The old 2.15 machine I'm running will shortly receive a fresh Bionic install, so likely this problem will disappear after the upgrade.

Thanks!
