### ISSUE TITLE
It's not clear where the documentation really is.

### ISSUE THREAD

**Issue by akarelas** [lxc/lxd#4525]
This page https://lxd.readthedocs.io/en/latest/#getting-started-with-lxd says that the documentation is in github.

But this page is called "read the docs". So how can it not be documentation?

Is it or is it not the manual? What should I read? Is there a single source of truth for learning about LXD, or do I just have to read everything, test everything, and see what works?

**Comment by stgraber** [comment]
Read the docs renders the doc from the repository so that's normal, we can't have it say two different things.
