### ISSUE TITLE
Migrate or restore LXD containers

### ISSUE THREAD

**Issue by monkiki** [lxc/lxd#4526]
This is not a question or a issue, simply I wanted to share my experience with LXD container migration. After a little research I've not discovered a proper way of backuping my containers and send to another server. I know you can copy a container to another server but I don't see it's a good way of bakcup because  I need to store several days back and the size may become a problem. Also tried tools like Borg Backup which is pretty nice but has some performance problems with containers which has over a million of files to backup.

This is my way to send and restore containers which can be also used to restore them when using ZFS level backup utilities like ZnapZend. 

## Source server
We can't export a dataset if it's mounted so we can make an snapshot or stop the container:
```
$ lxc stop pruebas
$ zfs send zfs-pool/containers/pruebas | pigz > pruebas.gz
```

## Destination server
Create a new instance to be used in the restoration process. The used image doesn't matter:
```
$ lxc launch ubuntu:x pruebas
```
Stop the new container, delete the dataset and import the other one:
```
$ lxc stop pruebas
$ zfs destroy zfs-pool/containers/pruebas
$ pigz -cd pruebas.gz | zfs receive zfs-pool/containers/pruebas
$ zfs set mountpoint=/var/lib/lxd/storage-pools/lxd-pool/containers/pruebas zfs-pool/containers/pruebas
```

Start the container:
```
$ lxc start pruebas
```

As I said previously, this process can be simplified with:
```
$ lxc copy pruebas dst:pruebas
```

But the point was how to restore a ZFS incremental backup.

**Comment by stgraber** [comment]
Sounds about right for zfs. That combined with lxd. import can work. We're currently busy implementing tarball exports that may help some people too, though the thing that's likely to help the most is support for delta copies of containers.

Closing since there's no bug to be fixed here.

**Comment by monkiki** [comment]
Tarball export is an interesting feature because right now if I need an export I have to publish the container as an image and export it, which take longer than expected. Delta copies was the main goal of my investigation, and the method seems to work.

Thanks!
