### ISSUE TITLE
Nvidia-smi (No devices where found) if not using root in the container

### ISSUE THREAD

**Issue by cyberwillis** [lxc/lxd#4534]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails: 
   * Kernel version: 4.15.0-15-lowlatency
   * LXC version: 3.0.0
   * LXD version: 3.0.0
   * Storage backend in use: N/A

# Issue description

Sorry if its a dumb question but, after creates a container with GPU / Cuda capabilites I cannot run nvidia-smi as user **ubuntu**, but is possible to run as user **root**

# Steps to reproduce

1. Setting up the container
```
lxc launch ubuntu:16.04 my_container
lxc config device add my_container gtx gpu
lxc config set my_container nvidia.runtime true
lxc restart my_container
```

2.Accessing the nvidia GPU as Root : **Here everything works out**
```
lxc exec my_container "nvidia-smi"

or

lxc exec my_container -- su root -c "nvidia-smi"
```

3.Accessing the nvidia GPU as Ubuntu : **No devices were found**
```
lxc exec my_container -- su ubuntu -c "nvidia-smi"
```

**Comment by brauner** [comment]
Could be a PATH issue or simply that `nvidia-smi` requires root to initialize cards. //cc @flx42, @3XX0

**Comment by cyberwillis** [comment]
Hi

If I remove this line from the process
```
lxc config set my_container nvidia.runtime true
```
and install cuda drivers and nvidia-driver inside the container everything works. I was using the earlier method in LXD 2.21, but now in LXD 3.0.0 I tried the new method and did not worked yet.

**Comment by stgraber** [comment]
@cyberwillis My guess is that it's got to do with the permissions on some of the /dev files that the nvidia hook setup for you. What does `ls -lh /dev` look like when nvidia-smi isn't working?

**Comment by cyberwillis** [comment]
Hi 

```
lxc exec c1 -- su ubuntu              
ubuntu@c1:/root$ ls -lh /dev
total 0
crw--w---- 1 root   tty     136,   0 May  4 11:40 console
lrwxrwxrwx 1 root   root          11 May  4 11:40 core -> /proc/kcore
drwxr-xr-x 2 root   root         120 May  4 11:40 dri
lrwxrwxrwx 1 root   root          13 May  4 11:40 fd -> /proc/self/fd
crw-rw-rw- 1 nobody nogroup   1,   7 May  4 05:47 full
crw-rw-rw- 1 nobody nogroup  10, 229 May  4 11:40 fuse
drwxr-xr-x 2 root   root          40 May  4 11:40 hugepages
lrwxrwxrwx 1 root   root          25 May  4 11:40 initctl -> /run/systemd/initctl/fifo
lrwxrwxrwx 1 root   root          28 May  4 11:40 log -> /run/systemd/journal/dev-log
drwxr-xr-x 2 nobody nogroup       60 May  4 05:47 lxd
drwxrwxrwt 2 nobody nogroup       40 May  4 05:46 mqueue
drwxr-xr-x 2 root   root          60 May  4 11:40 net
crw-rw-rw- 1 nobody nogroup   1,   3 May  4 05:47 null
crw-rw---- 1 root   root    195,   0 May  4 11:40 nvidia0
crw-rw---- 1 root   root    195,   1 May  4 11:40 nvidia1
crw-rw-rw- 1 nobody nogroup 195, 255 May  4 05:47 nvidiactl
crw-rw-rw- 1 nobody nogroup 239,   0 May  4 05:47 nvidia-uvm
crw-rw-rw- 1 root   root      5,   2 May  4 11:40 ptmx
drwxr-xr-x 2 root   root           0 May  4 11:40 pts
crw-rw-rw- 1 nobody nogroup   1,   8 May  4 05:47 random
drwxrwxrwt 2 root   root          40 May  4 11:40 shm
lrwxrwxrwx 1 root   root          15 May  4 11:40 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root   root          15 May  4 11:40 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root   root          15 May  4 11:40 stdout -> /proc/self/fd/1
crw-rw-rw- 1 nobody nogroup   5,   0 May  4 05:47 tty
crw-rw-rw- 1 nobody nogroup   1,   9 May  4 05:47 urandom
crw-rw-rw- 1 nobody nogroup   1,   5 May  4 05:47 zero
```

**Comment by cyberwillis** [comment]
Hi again @stgraber 

I patched inside the container by addin permissions :
```
sudo chmod 766 /dev/nvidia0
sudo chmod 766 /dev/nvidia1
```
and it worked as ubuntu user now.

its the correct way to do it ?

Thanks in advance

**Comment by cyberwillis** [comment]
I just detected that after restart the container the problem returns.

Looking forward to see a fix for it.

**Comment by stgraber** [comment]
666 would be a better permission here.

@brauner is that our fault or nvidia's? If it's our fault, can you send a branch?
I think we should have the mode match that of the host for any of those files.

**Comment by 3XX0** [comment]
I suspect it's yours since we don't mount the device nodes in LXD, only in LXC :)

If the device nodes are recreated inside the container, they usually need to match the permissions enforced by the kernel modules:

```
cat /proc/driver/nvidia/params

DeviceFileUID: 0
DeviceFileGID: 0
DeviceFileMode: 438 # 0666 in octal
```

Note that these permissions are from the init userns perspective, udev can also do something different on top of that...

If you look at the device nodes mounted by our hook, they are correct:
```
crw-rw-rw- 1 nobody nogroup 195, 255 May  4 05:47 nvidiactl
crw-rw-rw- 1 nobody nogroup 239,   0 May  4 05:47 nvidia-uvm
```
Same should be done with the `/dev/nvidia[N]`

Obviously your UID/GID remapped inside the container then needs permission to access it.
So you most likely want to configure DeviceFileMode or udev with the right permissions for your containers (see also [How and when are the NVIDIA device files created?](http://us.download.nvidia.com/XFree86/Linux-x86/390.48/README/faq.html)).

**Comment by stgraber** [comment]
Yeah, had a chat with @brauner and he said we're using our default device passthrough code, which unless you're specifying your own mode.

```
        // Get the device mode
        mode := os.FileMode(0660)
        if m["mode"] != "" {
                tmp, err := deviceModeOct(m["mode"])
                if err != nil {
                        return nil, fmt.Errorf("Bad mode %s in device %s", m["mode"], m["path"])
                }
                mode = os.FileMode(tmp)
        }
```

What we should do when passing devices automatically (so for GPU, USB and Infiniband) is replicate the permissions found on the host.

@brauner assigning to you

**Comment by cyberwillis** [comment]
Just detected another issue
I don't know if it's related too
The container I was working on had a folder called /projects mapped inside the container. However because the folder was unprivileged all the gid and uid was as nobody nobody
and trying to make writing to that folder wasn't possible

I tried to convert the container to provileged one by:
```
lxc config set c1 security.privileged true
lxc config set c1 volatile.idmap.next 1000
lxc restart c1

```

However it conflicts with the fact I had used this line before
```
lxc config set c1 nvidia.runtime true
```
Unless I set nvidia.runtime to false I cannot start the container as privileged.
