### ISSUE TITLE
LXD v3 does not allow to reuse the existing thinpool

### ISSUE THREAD

**Issue by zerkms** [lxc/lxd#4541]
# Required information

 * Distribution: ubuntu
 * Distribution version: bionic 18.04
 * The output of "lxc info" or if that fails:
<details>
  <summary>lxc info</summary>

    config: {}
    api_extensions:
    - storage_zfs_remove_snapshots
    - container_host_shutdown_timeout
    - container_stop_priority
    - container_syscall_filtering
    - auth_pki
    - container_last_used_at
    - etag
    - patch
    - usb_devices
    - https_allowed_credentials
    - image_compression_algorithm
    - directory_manipulation
    - container_cpu_time
    - storage_zfs_use_refquota
    - storage_lvm_mount_options
    - network
    - profile_usedby
    - container_push
    - container_exec_recording
    - certificate_update
    - container_exec_signal_handling
    - gpu_devices
    - container_image_properties
    - migration_progress
    - id_map
    - network_firewall_filtering
    - network_routes
    - storage
    - file_delete
    - file_append
    - network_dhcp_expiry
    - storage_lvm_vg_rename
    - storage_lvm_thinpool_rename
    - network_vlan
    - image_create_aliases
    - container_stateless_copy
    - container_only_migration
    - storage_zfs_clone_copy
    - unix_device_rename
    - storage_lvm_use_thinpool
    - storage_rsync_bwlimit
    - network_vxlan_interface
    - storage_btrfs_mount_options
    - entity_description
    - image_force_refresh
    - storage_lvm_lv_resizing
    - id_map_base
    - file_symlinks
    - container_push_target
    - network_vlan_physical
    - storage_images_delete
    - container_edit_metadata
    - container_snapshot_stateful_migration
    - storage_driver_ceph
    - storage_ceph_user_name
    - resource_limits
    - storage_volatile_initial_source
    - storage_ceph_force_osd_reuse
    - storage_block_filesystem_btrfs
    - resources
    - kernel_limits
    - storage_api_volume_rename
    - macaroon_authentication
    - network_sriov
    - console
    - restrict_devlxd
    - migration_pre_copy
    - infiniband
    - maas_network
    - devlxd_events
    - proxy
    - network_dhcp_gateway
    - file_get_symlink
    - network_leases
    - unix_device_hotplug
    - storage_api_local_volume_handling
    - operation_description
    - clustering
    - event_lifecycle
    - storage_api_remote_volume_handling
    - nvidia_runtime
    api_status: stable
    api_version: "1.0"
    auth: trusted
    public: false
    auth_methods:
    - tls
    environment:
      addresses: []
      architectures:
      - x86_64
      - i686
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIIFSjCCAzKgAwIBAgIRAMj0Vo7tQjlGiVCQ6LrzCOMwDQYJKoZIhvcNAQELBQAw
        NzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEXMBUGA1UEAwwOcm9vdEB4
        dHItc3J2MDEwHhcNMTgwNTA4MDAzODM3WhcNMjgwNTA1MDAzODM3WjA3MRwwGgYD
        VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRcwFQYDVQQDDA5yb290QHh0ci1zcnYw
        MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAL/df4HO1hukMHyWyXka
        aNoXvTFuOGq07ZDlYBpyyjBVTtJMEU2c/ENL+ohLQNvwhmeDDdOC612CGf5rI8zN
        mtTN1UYIyzVgzR9CA1/LOIA0dozHdW3DqsrF3STp4vzytufTJdndCfqyDIlzq+yV
        hAwLHxplQDrsulsU38536QgXT24/etJ2WOFiK+unvV1uDhkMpcb1wbOq9r9yzWxk
        XYUN2mvgkCg8H8leNUkSBcwMPoALJ6g3TTojAhRZehJBQGZLnTyy+KMp/UA3hqJV
        jnQhqMPEFtQVrqQLJJrVGn/dZq8L8bYkyG0ZsfWevSNi+KZ0W7wQX9JPKgvx+dEK
        RrgxSrKQRXRPD7pBUeMXIJaZ/MDAmhHcgbJU3lK1lipxPf4GMGFcYQHoZIzGgxbe
        cRvgXgj1PDO/MNnHWaiBC1KbKFoQkWwO8sXANriQgZIgnc2sO2wPgyA+ENlvh+kC
        u16gf6QlWjap7n+nQY5OZanH+sTKq+01pUaNB6GRlewrtnBW+Ip0tc8AzEFZm8b/
        AnYEhtgsphnWKw8Kr0XK4tjMQaRRQ7PnU8dipbxS+dwWeIwgr0vCW4yFgyB+BGOK
        aVQnOr2KvlM7e8Iruireu2Qmk1w8jw+6U7pRMPrjy5ywDip7L3uFRHoDnwAM0jUd
        RoRtuDTuERi5K1oSy84WqnqTAgMBAAGjUTBPMA4GA1UdDwEB/wQEAwIFoDATBgNV
        HSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMBoGA1UdEQQTMBGCCXh0ci1z
        cnYwMYcECh4EATANBgkqhkiG9w0BAQsFAAOCAgEAlkAx3ZDhDVp1uvdul6GfCMhD
        VVnP0bdoGN0oLM2grGGMHGJwaVRYtvpLommyrLNdo+JtQWFNSBvtyHBu6Wn5cXXe
        xSaB4VbB+O7YpruE1+l8jmOKro/krF3lfJFS1aYGBK4KRqVJ7Ws7l9HBQOgMT8et
        QKlk48ureN2ib5VsWzfSesZT3KdapdpCcfxefwfJHLQUeyIiAHt1Qch+iMD+pnUi
        jFN1Ii4Gqsh4bC1YzH33n7RRSlaoE8WOISrbaedyDBLUG0+XX+yDKOTvaQLl47lP
        jgxJ+TB9su4n+gFyWMwmZnnnWpCBgl3GxY50n7MCuRUM5WL7+MujxuRDPiaK5m0B
        E5RK0VA35DBxkS52H5gxd21cl8hAdo3ZV5JFwY5jj9LQvhPP4jdxdri57srohPIo
        gVQYk4PflHX4V0hu9gQHu37whLlCOKj9Lgxw5LxLSk+phXCSm8IK+bznjqI7wZ7C
        qciLvN0b4y53pUrzk8o4NAGWCqNyfHnixoXcfVk6wXg8fMOzqQnORZ0E3r62cEgn
        Biza0HE4AeONy64lLayF2gLSYmASOcmQAMTmGfKTIgpFNM8eCmFv07MC80Qxj0Es
        ifoIYdkaoerggoLMTrB7/AGR/mEw+MJl/Q3eBtuDfkyE3z8QXL6uTMvQMcUlpV7C
        hUGXD29h2Dc68RA99gE=
        -----END CERTIFICATE-----
      certificate_fingerprint: 9eb040c04df623ec6f24d20f4d03e7c1fed6db144ee9e9277c87120eafd164ee
      driver: lxc
      driver_version: 3.0.0
      kernel: Linux
      kernel_architecture: x86_64
      kernel_version: 4.15.0-20-generic
      server: lxd
      server_pid: 9690
      server_version: 3.0.0
      storage: lvm
      storage_version: 2.02.176(2) (2017-11-03) / 1.02.145 (2017-11-03) / 4.37.0 / ./configure
        --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man
        --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules
        --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu
        --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --exec-prefix=
        --bindir=/bin --libdir=/lib/x86_64-linux-gnu --sbindir=/sbin --with-usrlibdir=/usr/lib/x86_64-linux-gnu
        --with-optimisation=-O2 --with-cache=internal --with-clvmd=corosync --with-cluster=internal
        --with-device-uid=0 --with-device-gid=6 --with-device-mode=0660 --with-default-pid-dir=/run
        --with-default-run-dir=/run/lvm --with-default-locking-dir=/run/lock/lvm --with-thin=internal
        --with-thin-check=/usr/sbin/thin_check --with-thin-dump=/usr/sbin/thin_dump --with-thin-repair=/usr/sbin/thin_repair
        --enable-applib --enable-blkid_wiping --enable-cmdlib --enable-cmirrord --enable-dmeventd
        --enable-dbus-service --enable-lvmetad --enable-lvmlockd-dlm --enable-lvmlockd-sanlock
        --enable-lvmpolld --enable-notify-dbus --enable-pkgconfig --enable-readline --enable-udev_rules
        --enable-udev_sync
      server_clustered: false
      server_name: <redacted>

</details>

# Issue description

It's not possible (?) to reuse the existing lvm thinpool in LXD v3 (it was fine in v2). I initially asked this question at https://discuss.linuxcontainers.org/t/how-to-create-a-default-storage-pool-on-lvm/1735 but after exploring code I think it's a bug

# Steps to reproduce

 1. Create lvm thinpool
 2. Install lxd (**do not initialise**)
 3. Create a default storage pool with `lxc storage create default lvm lvm.thinpool_name=<thinpool_name> lvm.vg_name=<vg_name> lvm.use_thinpool=true`

The step 3 would fail with `Error: LXD already uses volume group "vghdd" for pool "default"` which simply is not true

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [x] Output of the client with --debug
This is the relevant part of the output

        method=POST url=http://unix.socket/1.0/storage-pools
        {
            "config": {
                "lvm.thinpool_name": "lvdata",
                "lvm.use_thinpool": "true",
                "lvm.vg_name": "vghdd"
            },
            "description": "",
            "name": "default",
            "driver": "lvm"
        }

 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by brauner** [comment]
What does `lvdisplay` for that volume group show?

**Comment by zerkms** [comment]
There is no problem with lvm: I could manually initialise the storage (inserted the records directly using `lxd sql`).

I will post the requested details tomorrow though anyway when back in the office.

**Comment by brauner** [comment]
> There is no problem with lvm: I could manually initialise the storage (inserted the records directly using lxd sql).

Sure, if you force-feed LXD a pool by messing with db it'll work. What else is it supposed to do. I need to see whether that lvm pool has a specific layout.

**Comment by brauner** [comment]
> lxc storage create default lvm lvm.thinpool_name=<thinpool_name> lvm.vg_name=<vg_name> lvm.use_thinpool=true

That's also not a valid way to re-use an existing volume group and if it was that was a bug. The correct way is to specifiy `source`:

    lxc storage create pool1 lvm source=<vg_name> lvm.thinpool_name=<thinpool_name>

Does that work?

**Comment by brauner** [comment]
See https://github.com/lxc/lxd/blob/master/doc/storage.md#lvm .

**Comment by zerkms** [comment]
Oh, how could I overlook that section in the doc 🤦 thanks for that.

Tomorrow I'll report and likely close this issue.

PS: at least now I'm more familiar with lxd and lxc code and database :-D

**Comment by brauner** [comment]
@zerkms, that's perfectly fine. :) I'm excited to hear whether that fixes your issue. If not, re-open, please! :)

**Comment by brauner** [comment]
```
chb@conventiont|~
> lxc storage create lvm lvm lvm.thinpool_name=aaa lvm.vg_name=bbb lvm.use_thinpool=
true
Storage pool lvm created
chb@conventiont|~
> lxc storage show lvm
config:
  lvm.thinpool_name: aaa
  lvm.use_thinpool: "true"
  lvm.vg_name: bbb
  size: 57GB
  source: /var/lib/lxd/disks/lvm.img
description: ""
name: lvm
driver: lvm
used_by: []
status: Created
locations:
- none
```
works perfectly fine if the pool doesn't exist. :)

**Comment by zerkms** [comment]
```
# lxc storage create lvm lvm lvm.thinpool_name=aaa lvm.vg_name=vghdd lvm.use_thinpool=true
Error: volume group "vghdd" is not empty
```
But I see your point, thanks :-)
