### ISSUE TITLE
SNAP auto refresh problem with LXD

### ISSUE THREAD

**Issue by ottacom** [lxc/lxd#4542]
I'm testing LXD on 6 different server and I have at least 100 LXD containers
Honestly I didn't know that  is not possible to stop the autorefresh "feature" on SNAP and for some strange reason I got a stuck on about 10 containers caused from snap refresh.

Although I have to find the way to stop it  (probably using some firewall rules at this point) can I ask how I can fix this error "Failed to start the daemon: Both legacy and new local database files exists"?

Thanks

 cat /var/snap/lxd/common/lxd/logs/lxd.log

lvl=info msg="LXD 3.0.0 is starting in normal mode" path=/var/snap/lxd/common/lxd t=2018-05-08T08:53:41+0000
lvl=info msg="Kernel uid/gid map:" t=2018-05-08T08:53:41+0000
lvl=info msg=" - u 0 0 4294967295" t=2018-05-08T08:53:41+0000
lvl=info msg=" - g 0 0 4294967295" t=2018-05-08T08:53:41+0000
lvl=info msg="Configured LXD uid/gid map:" t=2018-05-08T08:53:41+0000
lvl=info msg=" - u 0 1000000 1000000000" t=2018-05-08T08:53:41+0000
lvl=info msg=" - g 0 1000000 1000000000" t=2018-05-08T08:53:41+0000
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-05-08T08:53:41+0000
lvl=info msg="Initializing local database" t=2018-05-08T08:53:41+0000
**lvl=eror msg="Failed to start the daemon: Both legacy and new local database files exists" t=2018-05-08T08:53:41+0000**
lvl=info msg="Starting shutdown sequence" t=2018-05-08T08:53:41+0000
lvl=info msg="Saving simplestreams cache" t=2018-05-08T08:53:41+0000
lvl=info msg="Saved simplestreams cache" t=2018-05-08T08:53:41+0000

**Comment by freeekanayaka** [comment]
Hello,

The error you pasted seems to suggest some issue that happened while upgrading a LXD 2.x daemon to 3.0.0. Can you provide more details about the history of this particular daemon?

- Full logs of previous runs. If you migrated from deb to snap, you might still have /var/lib/lxd/lxd.log around, but @stgraber will know more about how to get logs of what happened during the migration. You probably have other rotated log files under /var/snap/lxd/common/logs/.

- Output of journalctl -u snap.lxd.daemon

- An attachment with /var/snap/lxd/common/lxd/lxd.db, and /var/snap/lxd/common/lxd/database/ (tarball). You can also send those privately by email.

As a immediate workaround you could try to:

0. Stop the LXD daemon (I guess it's already stop, but double checking won't hurt: systemctl stop snap.lxd.daemon)
1. Backup your /var/snap/lxd/common/lxd/lxd.db file and /var/snap/lxd/common/lxd/database/ directory
2. Remove /var/snap/lxd/common/lxd/lxd.db
3 Start the daemon again.

Note that the above procedure is a bit a shot in the dark without more details, so it might or might not work depending on the situation. However, in case it fails, restoring the backup will bring you back where you are now.

**Comment by ottacom** [comment]
Hello,
thank you for answering me, I'm not migrating from deb to snap, everything was fine since some days ago and it's currently fine also on all the rest of the containers only 10 are in this strange state after upgrading from 2 to 3.

I also tried the workaround ... nothing.... 

I opened a question to ASK ubuntu because I suppose that SNAP is not for production environment until this "feature" it will be fixed :-(.

Here the log:
[lxd.zip](https://github.com/lxc/lxd/files/1983444/lxd.zip)


journalctl -u snap.lxd.daemon
May 08 10:12:04 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 systemd[1]: Started Service for snap application lxd.daemon.
May 08 10:12:06 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: => Preparing the system
May 08 10:12:06 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: ==> Loading snap configuration
May 08 10:12:06 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: ==> Setting up mntns symlink
May 08 10:12:06 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: ==> Setting up kmod wrapper
May 08 10:12:06 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: ==> Preparing /boot
May 08 10:12:06 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: ==> Preparing a clean copy of /run
May 08 10:12:07 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: ==> Preparing a clean copy of /etc
May 08 10:12:07 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: ==> Setting up ceph configuration
May 08 10:12:07 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: ==> Setting up LVM configuration
May 08 10:12:07 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: ==> Rotating logs
May 08 10:12:07 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: ==> Escaping the systemd cgroups
May 08 10:12:07 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: ==> Escaping the systemd process resource limits
May 08 10:12:07 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: => Starting LXCFS
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: => Starting LXD
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: mount namespace: 5
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: hierarchies:
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]:   0: fd:   6: memory
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]:   1: fd:   7: devices
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]:   2: fd:   8: blkio
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]:   3: fd:   9: net_cls,net_prio
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]:   4: fd:  10: pids
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]:   5: fd:  11: cpuset
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]:   6: fd:  12: perf_event
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]:   7: fd:  13: hugetlb
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]:   8: fd:  14: cpu,cpuacct
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]:   9: fd:  15: freezer
May 08 10:12:08 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]:  10: fd:  16: name=systemd
May 08 10:12:09 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-05-08T10:12:09+0000
May 08 10:12:09 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: lvl=eror msg="Failed to start the daemon: Both legacy and new local database files exists" t=2018-05-08T10:12:09+0000
May 08 10:12:09 uuid-647949d8-d1ab-1037-91ba-51a614e7ebd1 lxd.daemon[371]: Error: Both legacy and new local database files exists

**Comment by ottacom** [comment]
Ok in the meanwhile I got an answer for locking SNAP on a specific version , this probably can helps 

snap refresh lxd --channel 2.0/stable

**Comment by ottacom** [comment]
I'm discovering other issues

snap changes

ID   Status  Spawn                 Ready                 Summary
55   Error   2018-05-01T11:40:13Z  2018-05-08T11:40:59Z  Auto-refresh snaps "core", "lxd"
59   Error   2018-05-08T11:45:59Z  2018-05-08T13:19:16Z  Auto-refresh snaps "core", "lxd"
60   Error   2018-05-08T13:19:32Z  2018-05-08T13:38:59Z  Auto-refresh snaps "lxd", "core"
61   Doing   2018-05-08T13:39:00Z  -                     Refresh "lxd" snap from "3.0/stable" channel

Seem that lxd it never closing the update

**Comment by stgraber** [comment]
So the original error about both legacy and new databases existing is definitely because ` /var/snap/lxd/common/lxd/lxd.db` somehow exists on your system. The fact that snapd seems stuck mid-upgrade may explain why it'd re-appear though...

I'd recommend doing:
 - snap abort 61
 - snap refresh
 - snap list
 - snap changes

What we're aiming for here is for both the core and lxd snaps to be up to date and no snapd operations to be running. Once that's the case, if LXD is still failing, move /var/snap/lxd/common/lxd/lxd.db aside and restart lxd with `systemctl restart snap.lxd.daemon`
