### ISSUE TITLE
Running Docker inside LXD Container - FAIL to run Rancher Agent

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#4544]
# Required information

 * Distribution: **Ubuntu** 
 * Distribution version: **16.04**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.4.0-116-generic**
   * LXC version: **2.21**
   * LXD version: **2.21**
   * Storage backend in use: **zfs**

# Issue description

When i try to run the Rancher 2.0 Agent to setup a LXD conatiner a Cluster, i get the following error:

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:365: setting cgroup config for procHooks process caused \\\"failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/docker/980366a6ceb3076fa62ffefcfaa8a51d0b3d3f76e14af0e9e03e9e2e4af828d5/devices.allow: operation not permitted\\\"\"": unknown.`

# Steps to reproduce

 1. I create a container call DOCKER running Ubuntu 18.04.
 2. I execute the following configuration options for the container:
 
```
- linux.kernel_modules: ip_tables
- raw.lxc: lxc.mount.auto = cgroup
- security.nesting: "true"
- security.privileged: "true"
```
 3. Installed Docker using instructions from docker website, but using the Ubuntu 17.10 repository. Everything up to here works fine. 
 4. I then try and run the Rancher Agent:  

sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.0 --server https://rancher.host --token ############################# --ca-checksum ########################## --worker

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

[lxd.log](https://github.com/lxc/lxd/files/1983613/lxd.log)
[dmesg.log](https://github.com/lxc/lxd/files/1983615/dmesg.log)
[lxc-config-show.log](https://github.com/lxc/lxd/files/1983616/lxc-config-show.log)
[lxc-info-log.log](https://github.com/lxc/lxd/files/1983617/lxc-info-log.log)

**Comment by brauner** [comment]
The devices cgroup can't be changed after it has been written to once afaict.

**Comment by elbrinke** [comment]
Is there anything i can do to fix this?

**Comment by brauner** [comment]
Hm, you could try and tamper with the permissions, i.e. add:

```
raw.lxc:
  lxc.cgroup.devices.allow =
  lxc.cgroup.devices.deny =
```

in the container's config and try. Note however, that the container will have access to all devices then.

**Comment by elbrinke** [comment]
I now get a different issue after applying the above mentioned variables:

`
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "operation not permitted": unknown.`

**Comment by stgraber** [comment]
That one is pretty cryptic. It may be apparmor blocking something or maybe some missing kernel modules.
Look at `dmesg` for any sign of apparmor denials.

**Comment by stgraber** [comment]
Closing the issue as there's nothing particularly wrong with LXD here, it's really about understanding what the Docker container is trying to do and turning off enough security features to make it happy.

Note that because we close an issue doesn't mean we won't be reading and responding to any new comments, just that there's nothing actionable for us to do to LXD here.
