### ISSUE TITLE
Fix same-name container move in cluster

### ISSUE THREAD

**Issue by dfsdevops** [lxc/lxd#4546]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 8.04
 * The output of "lxc info" or if that fails:
```
root@lxd-dev-02:~# lxc info
config:
  core.https_address: 10.1.2.42:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.1.2.42:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFTTCCAzWgAwIBAgIRAIYi9SOBaeGArc8ha+7ZyvIwDQYJKoZIhvcNAQELBQAw
    ODEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEYMBYGA1UEAwwPcm9vdEBs
    eGQtZGV2LTAxMB4XDTE4MDUwODIwNTU1N1oXDTI4MDUwNTIwNTU1N1owODEcMBoG
    A1UEChMTbGludXhjb250YWluZXJzLm9yZzEYMBYGA1UEAwwPcm9vdEBseGQtZGV2
    LTAxMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0JxeMil0dOsHwO/x
    xIHJHXfC7VlNRP0WXNLb9glwUr3qVEExW+NG5XOdzts5uQm0wV1nhDrZoLr3AUwI
    dmrvREWbn7PQEr0Fw7ZHYPG1r+06b5m0fweEWuV6punvzZSCeiIV5M4w6S+93Xna
    C4fryXuIRIpMrXhhVzSclIGWiB4DA95KLN8oR8FfhEstZ6Jz+sYMMrOxDjbhEYLw
    OSV4MYgFhXlA+KGgeyCOrseiz9hycBeM8zniIxDzFIFTSGWd9B3omb4eK2li6zhb
    FNnNqsCdIOY7HsMJyD2bLJCKsuxXYkpN/XVJCNVOEoU13S1arTnIKPVzXvnFBpZx
    BREIbBQRI5fROYqlrbcMvOq/jEoWD9JQobK0OhfvdrTaJpWENF2ttf4QwANPx/zC
    DtSfIUbJ5I7iP0P+IuaShgwM2LG0aqyEwEpP3lPqV/LAPFiLj77QuxudiFVU0yZO
    iaA2UUFOskTNQNiMdZqD87j2Pp74dDrKSvmxTSwlXwJntUxAKoSUzaMBGhiRsuGp
    uc3atWRG+Ne7BMpepuyvEb2+kmFjexiyqH1pAXaAhNPJHithCiTFaOJQjbHx+n1n
    AxWqGnJQoDTyRm/JA1kyBo66NoDGW5X/RjVYIkD3Dc1svkYP6eWOB0Mi1mYj0qaq
    LG8jZ/e71ak9GSgdHDzXXvrLP0kCAwEAAaNSMFAwDgYDVR0PAQH/BAQDAgWgMBMG
    A1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwGwYDVR0RBBQwEoIKbHhk
    LWRldi0wMYcECgECKTANBgkqhkiG9w0BAQsFAAOCAgEAPTKfYKvM4tNuoItiIZ7C
    lKVN+73FriGg+xkl4APuT/FqciP4rXQ4eI+XW81BBc4jx1kK5ngmZbOO8tXROBZk
    lHp/6Vz1gxYLeLSbZA5Pi6dnJE5zJnPGrB3vUQgVxdlIF1zI2jtQ9h1h0wUH97nB
    uoK2f0Wd4S+z10bac6P4wGqrzwtFsfnT+077EIdpgtXeqQOxId1GaIfWEKzUhCRO
    Aj6aYw0bU5bigD0OhROI246nKk363X+4kZyMT7FNpUZMpESrw/ZjCBaCOkZkqOEq
    huCVn4yWhZ1sYIMlg9aitNeKaU70gOZDHajI+Lo8m2eemmiQoWGUqN8vu8Tk0Kzo
    s4bFhjPv/NFd9h2LvuulhBqmclPszgyhk9CrSPJL0K0GgcVUMG3IiuxoHBqVQn9M
    nPOVPlf2cYqb4OFC+kdDT3JqG29K+4am8gvV6rAFl+dCsRd6k45keWAB1MjQfl7N
    8whAL6TEXmiT1sb3pWvgd7E53SeIAXEPP/furs0excMJvu/yfZOGhaD/NTZzoC8g
    5WvNNxuuvuWISMJL0uHrn6NcgZ1rZFeOdMwOYewElyEkVLbFMpTacrGj3vYlIEfK
    MXSIiGOGMundoCvlDRRcLCqkYGbiu2Nlab23wpMWBxpFASsaZGgEXRRIn4ujie3t
    OboWBqb/G5F+82vh6wgV2t0=
    -----END CERTIFICATE-----
  certificate_fingerprint: fcc5ff4aea9e3513c7e2791e865bdae6f81b321c6c007a2fd7498d1d727060d0
  driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-20-generic
  server: lxd
  server_pid: 2728
  server_version: 3.0.0
  storage: zfs
  storage_version: 0.7.5-1ubuntu13
  server_clustered: true
  server_name: lxd-dev-02
```
# Issue description

I created 10 containers on a 3 node LXD cluster with ZFS storage back-end. I want to test migrating one of them from one node in the cluster but I get an error:

```
root@lxd-dev-02:~# lxc move cen5 --target lxd-dev-01
Error: Failed container creation: Container 'cen5' already exists
```

# Steps to reproduce

 1. Create a cluster with 3 nodes (for a proper quorum)
 2. Create a container anywhere in the cluster
 3. Run lxc move, using one of the node names in --target
```
root@lxd-dev-02:~# lxc move cen5 --target lxd-dev-03
Error: Failed container creation: Container 'cen5' already exists
```
other variants I have tried:
```
root@lxd-dev-02:~# lxc move cen5 cen5 --target lxd-dev-01
Error: Failed container creation: Container 'cen5' already exists
root@lxd-dev-02:~# lxc move cen5 lxd-dev-01:cen5
Error: The remote "lxd-dev-01" doesn't exist
root@lxd-dev-02:~# lxc move cen5 local:cen5
Error: already exists
root@lxd-dev-02:~# lxc move cen5 local:cen5 --target lxd-dev-01
Error: Failed container creation: Container 'cen5' already exists
root@lxd-dev-02:~# lxc move local:cen5 --target lxd-dev-01
Error: Failed container creation: Container 'cen5' already exists
```

I did discover that if I actually rename the container to something new it does attempt a migration (but gives me an entirely new error message.). If this is not allowed (migrating without renamaing) in a cluster configuration, then my suggestion is to no accept a single argument while using "--target"

**Comment by stgraber** [comment]
It's meant to work but doesn't right now, should be on @freeekanayaka's radar

**Comment by freeekanayaka** [comment]
At the moment keeping the same name when moving a container is only supported if you use ceph as storage driver. In your case (zfs), the "move" API is effectively a "create" followed by a "delete", that's why you get the "already exists" error.

Please try:

```
lxc move cen5 cen5-tmp --target lxd-dev-03
lxc rename cen5-tmp cen5
```

We'll probably want to improve the error message in this case, and eventually properly support this use case too.

**Comment by stgraber** [comment]
@freeekanayaka we definitely want to support this, it's very unfortunate that this didn't make it to 3.0 but we had bigger issues to deal with then. This is a very common operation for our users to do and needs to be addressed soon.

I suspect the naive implementation internally would be to use an "illegal" container name (bypassing that particular name check), then rename to the original name and clearing any `volatile` key that gets set during a traditional rename (so that we don't accidentally run templates when the name doesn't change).

So internally it'd effectively be:
 - cen5 on source host gets copied to move.cen5 on lxd-dev-03
 - cen5 is deleted on source host
 - move.cen5 is renamed to cen5 on lxd-dev-03
 - volatile.apply_template gets restored to pre-migration value on cen5 (unset if it wasn't set before)

**Comment by stgraber** [comment]
Ah yeah, the workaround didn't mention the fact that you should be stopping the container before moving.
Otherwise you're entering CRIU territory with all the potential issues that come with it.

**Comment by wetpaste** [comment]
I opened a separate issue with the CRIU team. https://github.com/checkpoint-restore/criu/issues/485

**Comment by stgraber** [comment]
Moving this to 3.3 as we'll want to have a single set of API changes to `POST /1.0/containers/NAME` which does two things:
 - Allow moving a container between two cluster members (`POST 1/.0/containers/NAME?target=blah`) with or without the container getting renamed at the same time
 - Allow moving a container between two storage pools (new attribute in POST to set the new pool, similar to moving custom volumes between pools)

The result should be that in a single API call we should be able to do all of these at the same time:
 - Move the container between two nodes
 - Rename it if we want
 - Move it to another storage pool

**Comment by laralar** [comment]
I found out that if I move a container that overrides the default profile where the MAAS networking information is, with its own set of eth0 networking without the MAAS information, the containers moves without a problem

```
ubuntu@node38:~$ lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    **maas.subnet.ipv4: 10.3.4.0/23**
    name: eth0
    nictype: bridged
    parent: br1
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/maas-icts
ubuntu@node38:~$ lxc profile show maas
config:
  raw.lxc: |-
    lxc.cgroup.devices.allow = c 10:237 rwm
    lxc.apparmor.profile=unconfined
    lxc.cgroup.devices.allow = b 7:* rwm
  security.privileged: "true"
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br1
    type: nic
```

Then, in theory, I can remove the MAAS networking configuration of the container in the target node, move the container without any issue, then add the container networking configuration.

Seems awkward but works. and I dont have to invent a MAC address every time I am moving a container

Still I believe this should be handled by LXD somehow at some point.  it is just not user fiendly and even tough **lxd move** command local and remote implementations are different, de behaviour should be the same

**Comment by laralar** [comment]
For moving a container from one node to another node whose LXD are registered with MAAS,  Assuming that you are using default profile created with MAAS integration

The workaround is
1. Disable MAAS integration of the container by overriding eth0 with no MAAS integration (the container will be removed from MAAS DNS)
2. Move the container
3. Enable again the MAAS integration by not overriing the eth0 and using the default MAAS integrated one
