### ISSUE TITLE
Cannot pull file from read only filesystem

### ISSUE THREAD

**Issue by shuhaowu** [lxc/lxd#4552]
# Required information

 * Distribution: Ubuntu
 * Distribution version: xenial
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.13.0-39-generic
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: dir

# Issue description

Trying to pull a file from a readonly file system results in an error. Example: pull any file from the RO mounted / from an ubuntu-core/16 image.

# Steps to reproduce

```
$ lxc launch images:ubuntu-core/16 core-test
$ lxc file pull core-test/usr/lib/os-release
error: open: Read-only file system
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
@brauner if you have a few minutes, should be a pretty easy fix (I expect it's just wrong open flags), otherwise I'll pick this up when I start.
