### ISSUE TITLE
Improve candid/macaroon based authentication

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4556]
Right now LXD has basic support for external authentication through macaroons.
Now that a reference open source server exists for this (candid), we need to do the following:
 - Rename a bunch of mentions of "macaroon" to instead say "candid" since macaroon is just a transport and what we care about is the communication protocol above it
 - Switch our tests to using candid rather than our own minimal test server
 - Add support for selecting candid domains to authenticate against
 - Implement/fix renewal of macaroons in the client library (we should expect short expiry with easy non-interactive renewal)
 - Make sure we support both form-based and URL-based authentication (and allow pre-seeding form-based creds through CLI)

**Comment by stgraber** [comment]
Looks like Candid may not have form based auth at all, if that's the case case we should just remove our form based auth code.

**Comment by monstermunchkin** [comment]
> Add support for selecting candid domains to authenticate against

Should we just drop the `core.macaroon.endpoint` config key, and therefore add the `Endpoint` variable to the struct `Remote`? That way, one could specify an endpoint via

    lxc remote add foo some-url --auth-type candid --endpoint some-endpoint

What do you think?

**Comment by stgraber** [comment]
I don't think we can do that. We do need the LXD daemon to choose what Candid server to send the clients to, if we don't do that, every client would need to know where the authentication server is, which they're pretty unlikely to know themselves.

**Comment by monstermunchkin** [comment]
Current status:

* [x] renaming macaroon -> candid
* [x] select domain to authenticate against
* [x] macaroon expiry can be configured
* [ ] switch tests to Candid

Users can select the domain by using the `--domain` flag. The expiry of the macaroon can be changed by setting the `lxc.candid.expiry` config key. It defaults to 3600 (seconds).
