### ISSUE TITLE
New cluster joining API

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4559]
Right now joining a cluster requires the joining node to get pre-configured to have matching storage pools and networks before being allowed to join the cluster. This process is largely hidden to the user by the code we have in `lxd init`, but this leads to a suboptimal API for any external users. (@morphis)

Instead, what we should have is:
 - GET /1.0/cluster returning a list of node-specific configurations in a format that can be used by `lxd init` or other management tools
 - PUT 1/.0/cluster should accept a filled version of that same node-specific configuration alongside the cluster information

LXD will then pre-configure the joining node and go ahead with joining the cluster. If some change occurred in between, then the join will fail, we'll rollback the configuration on the joining node and the user can try again.

This will effectively get us down to just two API calls to join a cluster, one GET against the existing cluster and one PUT against the joining node.

**Comment by morphis** [comment]
@stgraber Sounds ok for me.

**Comment by stgraber** [comment]
From previous discussions, passing the config override should look kinda like this:
# From GET /1.0/cluster
```json
"member_config": [
    {
        "name": "storage-pools.default.config.source",
        "description": "\"source\" property for storage pool \"default\""
    },
    {
        "name": "networks.lxdbr0.config.bridge.external_interfaces",
        "description": "\"bridge.external_interfaces\" property for network \"lxdbr0\""
    }
]
```

#  In PUT /1.0/cluster
```json
"member_config": [
    {
        "name": "storage-pools.default.config.source",
        "value": ""
    },
    {
        "name": "networks.lxdbr0.config.bridge.external_interfaces",
        "value": "eth0"
    }
]
```
