### ISSUE TITLE
Storage pool not set running lxd init

### ISSUE THREAD

**Issue by wallyworld** [lxc/lxd#4561]
# Required information

 * Distribution:
ubuntu
 * Distribution version:
18.04

$ lxc info
Generating a client certificate. This may take a minute...
config: {}
api_extensions:
- id_map
- id_map_base
- resource_limits
api_status: stable
api_version: "1.0"
auth: trusted
auth_methods:
- tls
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFTDCCAzSgAwIBAgIQJO6DbJOThUzTTV3Qd2K0XDANBgkqhkiG9w0BAQsFADA4
    .....
    -----END CERTIFICATE-----
  certificate_fingerprint: acfb631487534c6a0c92335a93b7dff5c4a88546f59b5bb3386568868a660438
  driver: lxc
  driver_version: 2.0.9
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-20-generic
  server: lxd
  server_pid: 19315
  server_version: 2.0.11
  storage: dir
  storage_version: ""

# Issue description

Running lxd init after installing the 2.x snap on a fresh bionic install gives an error about storage.
WARN[05-15|11:01:07] Did not find profile "default" so no default storage pool will be set. Manual intervention needed.

What manual intervention? It should work out of the box?

# Steps to reproduce

$ sudo snap install lxd --channel 2.0
lxd (2.0/stable) 2.0.11 from 'canonical' installed
$ sudo lxd init
Do you want to configure the LXD bridge (yes/no) [default=yes]? 
What should the new bridge be called [default=lxdbr0]? 
What IPv4 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]? 
What IPv6 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]? none
Do you want to configure a new storage pool (yes/no) [default=yes]? 
Name of the storage backend to use (dir or zfs) [default=zfs]: dir
Would you like LXD to be available over the network (yes/no) [default=no]? 
WARN[05-15|11:01:07] Did not find profile "default" so no default storage pool will be set. Manual intervention needed. 
LXD has been successfully configured.

**Comment by davidfavor** [comment]
This is very odd, as this is the exact way I use to setup LXD 2.x machines.

Maybe LXD 2.X has problems running on Bionic.

Likely best to use LXD 3.X + see if your problem resolve.

**Comment by davidfavor** [comment]
My steps for initializing Bionic + LXD 3.X machines.
```
lxd init --auto --storage-backend=dir
lxc network create lxdbr0
lxc network attach-profile lxdbr0 default eth0
```

**Comment by stgraber** [comment]
The fix has been pushed to the candidate channel.
