### ISSUE TITLE
proxy: support UDP protocol

### ISSUE THREAD

**Issue by killua-eu** [lxc/lxd#4566]
Hi, I was wondering if/when there will be udp proxy devices added to lxd.
Thanks lots, Pavel

**Comment by brauner** [comment]
Yes, it's something we're definitely considering. At least `UDP` to `UDP` but ideally also cross-protocol, i.e. `UDP <-> TCP`. We're also happy to take patches. :)

**Comment by killua-eu** [comment]
Not skilled enough here to actually help. Will gladly help with any testing.

**Comment by killua-eu** [comment]
BTW, as for testing, is lxd current on all ubuntu releases only on snap?

**Comment by brauner** [comment]
He, I already tried to get @infusion to do it but he's more interested in doing other boring stuff. :D (jk)

**Comment by brauner** [comment]
@killua-eu, not on all. But is the preferred way according to @stgraber going forward. All new feature releases will be snap-only. The stable-3.0 branch will still be maintained as a deb though.

**Comment by infusion** [comment]
@brauner You know how to catch me ;P But have to finish on my boring stuff right now :/

**Comment by killua-eu** [comment]
Good to know @brauner. I'm now setting up a new lxd host, so I'll just go with snap right of the start. Basically the only difference from user's perspective is the location of lxd data, right? I have some really good green and black teas as well as beautiful cannulas. You can have both @infusion if you look into udp <-> udp.

**Comment by stgraber** [comment]
So we have a few issues for the proxy that'd be neat to have someone work on:
 - Optimization for cases where NAT is possible (#4512)
 - Support for unix sockets (#4167)
 - Add UDP support (this issue)

**Comment by RevoluPowered** [comment]
Would it be more feasible to come up with a raw solution, instead of caring about the proto?

**Comment by stgraber** [comment]
Not really, no. As soon as you're dealing with port numbers, you've got to care about the protocol.
You could in theory nat a full IP to your container and not have to care about ports, but the proxy device is specifically meant for cases where you do not have a full publicly reachable IP per container.

**Comment by RevoluPowered** [comment]
slightly off topic:
I've got to admit that I've always wanted LXD to automatically NAT a container to an IP, if you enable it in the config. I never had the time to sit and figure out the iptables properly.

**Comment by stgraber** [comment]
If your host has a free IP for use by a container, it tends to be faster and simpler to just route it to the container instead, but that's not a super common setup, most users are in the one shared public IP for many containers case.
