### ISSUE TITLE
[Suggestion] Add changelog to Github releases or at least link to it

### ISSUE THREAD

**Issue by C0rn3j** [lxc/lxd#4568]
I have my RSS reader set to grab github releases, and it'd be great if they also had changelog, even if it'd only be a link to the forum (3.1 - https://discuss.linuxcontainers.org/t/lxd-3-1-has-been-released/1787 )

https://github.com/lxc/lxd/releases/tag/lxd-3.1

It was very confusing to figure out where the changelogs are in the first place.

**Comment by stgraber** [comment]
Did 3.0 and 3.1 and updated our internal doc to try to remember to dump the link in the future.
