### ISSUE TITLE
Publish Command Doesn't work when Container is on different machine (same cluster)

### ISSUE THREAD

**Issue by zacksiri** [lxc/lxd#4569]
# Required information

 * Distribution: 3.0.0
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-20-generic
   * LXC version: 3.0.0
   * LXD version: 3.0.0
   * Storage backend in use: zfs

# Issue description

In a cluster environment when I try to publish a container that is not in the same machine as the cluster calling the publish command I get Error: not found

# Steps to reproduce

 1. create a container
 2. login to a different host in the same cluster 
 3. try to publish said container

**Comment by stgraber** [comment]
@freeekanayaka assigned that one to you too
