### ISSUE TITLE
lxd-p2c: Rsync error handling and arbitrary arguments

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#4571]
There appears to be no --verbose or --debug flag to provide more information.

Be great to have some debugging info.

Thanks.
```
# time lxd-p2c https://158.69.126.175:8443 p2c-test /
Generating a temporary client certificate. This may take a minute...
Certificate fingerprint: 523419338c8557663e0e774dacffbbfc78c66a00823113a5959bdd41157b8d6e
ok (y/n)? y
Admin password for https://158.69.126.175:8443: 
Transferring container: p2c-test: 2.63GB (72.59MB/s)Error: exit status 2

real	0m49.613s
user	0m20.432s
sys	0m5.328s
```

**Comment by stgraber** [comment]
That's likely a rsync error on one of the two sides. Try running `lxc monitor` on the target server as you run lxd-p2c, that may show you a better error.

**Comment by davidfavor** [comment]
Not much additional information. rsync just seems to stop.
```
metadata:
  context: {}
  level: dbug
  message: Got message barrier, resetting stream
timestamp: "2018-05-19T20:44:02.871665319Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Got err writing write tcp 158.69.126.175:8443->142.4.216.83:44250: use
    of closed network connection'
timestamp: "2018-05-19T20:44:02.872073959Z"
type: logging


metadata:
  context:
    err: exit status 2
  level: eror
  message: Error during migration sink
timestamp: "2018-05-19T20:44:02.8723029Z"
type: logging


metadata:
  context:
    container: p2c-test
  level: dbug
  message: containerDeleteSnapshots
timestamp: "2018-05-19T20:44:02.872512146Z"
type: logging


metadata:
  context:
    created: 2018-05-19 20:43:24 +0000 UTC
    ephemeral: "false"
    name: p2c-test
    used: 1970-01-01 00:00:00 +0000 UTC
  level: info
  message: Deleting container
timestamp: "2018-05-19T20:44:02.872445866Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Deleting DIR storage volume for container "p2c-test" on storage pool "default".
timestamp: "2018-05-19T20:44:02.877995679Z"
type: logging


metadata:
  context: {}
  level: eror
  message: |
    Rsync receive failed: /var/snap/lxd/common/lxd/containers/p2c-test/: exit status 10: rsync: [generator] write error: Broken pipe (32)
    rsync error: error in socket IO (code 10) at io.c(820) [generator=3.1.1]
timestamp: "2018-05-19T20:44:02.991350392Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Disconnected event listener: 8ca4b85c-4ab6-491c-878d-da45cfcd0973'
timestamp: "2018-05-19T20:44:02.991747083Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Deleted DIR storage volume for container "p2c-test" on storage pool "default".
timestamp: "2018-05-19T20:44:03.665051298Z"
type: logging


metadata:
  context:
    created: 2018-05-19 20:43:24 +0000 UTC
    ephemeral: "false"
    name: p2c-test
    used: 1970-01-01 00:00:00 +0000 UTC
  level: info
  message: Deleted container
timestamp: "2018-05-19T20:44:04.108998477Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Failure for websocket operation: 0046dca2-251f-479a-b132-586d563301e9:
    Error transferring container data: exit status 2'
timestamp: "2018-05-19T20:44:04.109091754Z"
type: logging


metadata:
  action: container-deleted
  source: /1.0/containers/p2c-test
timestamp: "2018-05-19T20:44:04.109054878Z"
type: lifecycle


metadata:
  class: websocket
  created_at: "2018-05-19T20:43:25.5469951Z"
  description: Creating container
  err: 'Error transferring container data: exit status 2'
  id: 0046dca2-251f-479a-b132-586d563301e9
  may_cancel: false
  metadata:
    control: cb5fcc42bbe3fce5b0ca5cc2ab45bcc1d622943148151420d617c6d3bc8ebc0f
    fs: 7eb649185a0489a78e3e1f9fa0fa92493596874446f1b4f189d56edf90d54581
    fs_progress: 'p2c-test: 2.65GB (74.47MB/s)'
  resources:
    containers:
    - /1.0/containers/p2c-test
  status: Failure
  status_code: 400
  updated_at: "2018-05-19T20:44:02.317484066Z"
timestamp: "2018-05-19T20:44:04.109122598Z"
type: operation
```

**Comment by stgraber** [comment]
Ok, looks like it's a problem on the source side then, we'll have to check why the underlying error isn't getting surfaced.

**Comment by davidfavor** [comment]
Very odd, as I rsync many Gigs of data between the two machines involved, every day.

Likely good to add in some way to pass through arguments to rsync, like --verbose + --dry-run to see if there's maybe a problem file involved.

Let me know when you have an updated version to test + I'll test it + return info about what occurs.

**Comment by davidfavor** [comment]
Got lxd-p2c to sort of work.

1) The system I was attempting to clone was heavy. 3+ Million files. Nearly 6,000 databases. Nearly 400,000 database tables. Roughly 80G of data all told.

The behavior looked a lot like problems just trying to copy normal LXD containers.

2) Allowing rsync flag passage would likely solve all container migration problems.

Since there's no way to do this this, I created tarballs of various parts of system + moved tarballs over to target machine + deleted tar'ed files on source machine.

This reduced system size to 6G + file count to 203K files.

3) At this point lxd-p2c works.

So adding passing rsync flags would simplify using this tool. Also adding rsync flags to normal lxc commands would work around same problem with normal lxc copy operations.

**Comment by davidfavor** [comment]
Thanks for creating this tool.

I had to migrate a badly hacked up Trusty system into LXD, so I can start cloning containers + testing upgrade sequences.

Without lxd-p2c producing a running system would have taken hours to days.

**Comment by stgraber** [comment]
Yeah, I'll do a few changes to lxd-p2c to allow arbitrary rsync arguments to be passed as well as seeing why it's not surfacing rsync errors from the client side.

**Comment by wytcld** [comment]
It would be a good thing if, after rsync errors halt the process, the process could be restarted. As it is lxd-p2c complains that the container already exists. Why not have a "resume" flag to continue populating the container after an earlier halt-on-error?

**Comment by wytcld** [comment]
Can migration be completed with a manual rsync? Or does that leave steps undone? Being dependent on rsync never hitting an error, with large system, is optimistic. At least for the system I was hoping would be a good first-use case for this, it is.

**Comment by stgraber** [comment]
You can't use regular rsync as that doesn't know how to do on the fly remapping of uid/gid, also the target LXD wouldn't have the target filesystem created and mounted, ...

An option which many used prior to lxd-p2c is to create a minimal container on the target and then rsync from the source host into the container. That's a bit more work than lxd-p2c but should work fine. Once done, then restart the container and you should be good to go.

**Comment by wytcld** [comment]
Hi Stéphane,

Appreciate the advice.

After seeing lxd-p2c choke four times in a row on rsync, what might be most
useful is the combination of it specifically showing which file it fails on
(some use of the -vv flag?), along with the capibility to then exclude that
file on the next pass, and restart that pass within the current lxd-p2c
session, so that everything already transferred is still good.

Each of those 4 failures was over an hour into the session. What would it
take for lxd-p2c to be able to continue where it left off? Rsync of course
can recognize files already transferred and leave them out of the subsequent
pass. 

Best,
Whit

**Comment by stgraber** [comment]
Continuing an existing sync isn't something the LXD migration API allows at this point, so that's unlikely to be possible particularly soon.

The change I pushed yesterday does allow specifying arbitrary rsync parameters though and I've confirmed that this does include --exclude.

**Comment by erickeller** [comment]
hi everyone,

I also encounter some wired rsync behaviour on the host I try to transfer to a lxd repository.

```
strace lxd-p2c https://my.repo:8443 foobar /
...
getpeername(8, {sa_family=AF_INET, sin_port=htons(8443), sin_addr=inet_addr("162.1.2.5")}, [16]) = 0
futex(0xc42046c548, FUTEX_WAKE, 1)      = 1
getsockname(8, {sa_family=AF_INET, sin_port=htons(47278), sin_addr=inet_addr("10.1.9.5")}, [16]) = 0
setsockopt(8, SOL_TCP, TCP_NODELAY, [1], 4) = 0
write(8, "\26\3\1\0\215\1\0\0\211\3\3\3777\224b\362\240*!\323\347\352\335\341\341\0248\4\220l,\301"..., 146) = 146
read(8, 0xc420476400, 1024)             = -1 EAGAIN (Resource temporarily unavailable)
futex(0xded3e8, FUTEX_WAIT, 0, NULL)    = 0
read(6, "\27\3\3\0\243\0\0\0\0\0\0\0#0\362\250\256|\276g\322\tx\231!33I\265\3\376x"..., 2048) = 726
read(6, "\27\3\3\0\322\0\0\0\0\0\0\0&rK5\0031|c/\335\270\357\246\1\346r\33#)\235"..., 2048) = 215
read(6, 0xc420408800, 2048)             = -1 EAGAIN (Resource temporarily unavailable)
futex(0xded3e8, FUTEX_WAIT, 0, NULL)    = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
rt_sigreturn()                          = 202
futex(0xded3e8, FUTEX_WAIT, 0, NULL
```

on the system I run the lxd-p2c command rsync stopped and the process is staled as Z a defunct ("zombie") process.

setting SA_RESTART does not help much either.

on the lxd monitor side (my.repo)
```
metadata:
  context: {}
  level: eror
  message: |
    Rsync receive failed: /var/snap/lxd/common/lxd/containers/foobar/: exit status 12: rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
    rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.1]
timestamp: "2018-05-28T16:02:04.031396483Z"
type: logging
```

I there a dependency of a minimum version of rsync?

**Comment by erickeller** [comment]
in an equivalent container env.

```
[root@f78dca9c9799 /]# rsync --version
rsync  version 3.0.6  protocol version 30
Copyright (C) 1996-2009 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
[root@f78dca9c9799 /]# rsync -arvP --devices --numeric-ids --partial --sparse --ignore-missing-args
rsync: --ignore-missing-args: unknown option
rsync error: syntax or usage error (code 1) at main.c(1422) [client=3.0.6]
```

Seems that the ignore-missing-args could be the problem here.

**Comment by stgraber** [comment]
Hmm, indeed, will have to add some version checks then, not sure when that got introduced.

**Comment by erickeller** [comment]
What exactly is the intention of the netcat as a specify the remote shell command for rsync?

https://github.com/lxc/lxd/blob/master/lxd-p2c/transfer.go#L67

**Comment by erickeller** [comment]
https://download.samba.org/pub/rsync/src/rsync-3.1.0-NEWS 

```
 - Added the --delete-missing-args and --ignore-missing-args options to
      either delete or ignore user-specified files on the receiver that are
      missing on the sender (normally the absence of user-specified files
      generates an error).
```

**Comment by erickeller** [comment]
first try of PR https://github.com/lxc/lxd/pull/4600

**Comment by erickeller** [comment]
#4599 fixed it and I was able to migrate it to a lxd container...
