### ISSUE TITLE
LXD 3.1 Candidate: creating a privileged container with a  nvidia runtime passthrough, fail to start container or hangs LXD

### ISSUE THREAD

**Issue by cyberwillis** [lxc/lxd#4574]
# Required information

 * Distribution: **ubuntu**
 * Distribution version: **16.04**
 * The output of "lxc info" or if that fails: 
   * Kernel version: **4.15.0-15-lowlatency**
   * LXC version: **3.1** candidate
   * LXD version: **3.1** candidate
   * Storage backend in use: **zfs**

# Issue description

1.Starting a container with :`security.privileged true` alone , goes ok;
2.Starting a container with :`nvidia.runtime true` alone, also goes ok;
3.But starting a container with both, it hangs on this message: **Remapping container filesystem**
4.Or If I script all steps together I get this other message : 
**Error: Failed to run: /snap/lxd/current/bin/lxd forkstart c1 /var/snap/lxd/common/lxd/containers  /var/snap/lxd/common/lxd/logs/c1/lxc.conf:**

# Steps to reproduce:
1.a **Manually**
```
lxc launch ubuntu:16.04 c1 -c security.privileged=true
lxc config device add c1 gtx gpu
lxc config set c1 nvidia.runtime true
lxc restart c1
```
1.b **Manually [another way]**

```
lxc launch ubuntu:16.04 c1 
lxc config set c1 security.privileged true
lxc config device add c1 gtx gpu
lxc config set c1 nvidia.runtime true
lxc restart c1
```
If you arrive here will see that LXD is hanged and cannot start or stop or restart any container until restart the host.

2. **By Script**
```
export MACHINE_CONTAINER=c1
lxc stop $MACHINE_CONTAINER 
lxc delete $MACHINE_CONTAINER
lxc launch ubuntu:16.04 $MACHINE_CONTAINER -c security.privileged=true
lxc config device add $MACHINE_CONTAINER gtx gpu
lxc config set $MACHINE_CONTAINER nvidia.runtime true
lxc restart $MACHINE_CONTAINER;
```
If you arrive here you will see that the **container cannot be started again** but LXD is free to use another containers. But will get the message :

**Error: Failed to run: /snap/lxd/current/bin/lxd forkstart c1 /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/c1/lxc.conf:**

Here is the log of it when this message shows :

```
Name: c1
Remote: unix://
Architecture: x86_64
Created: 2018/05/21 17:24 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc 20180521172413.543 ERROR    lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
lxc 20180521172413.543 ERROR    lxc_conf - conf.c:lxc_setup:3391 - Failed to run mount hooks
lxc 20180521172413.543 ERROR    lxc_start - start.c:do_start:1198 - Failed to setup container "c1"
lxc 20180521172413.543 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
lxc 20180521172413.565 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:824 - Received container state "ABORTING" instead of "RUNNING"
lxc 20180521172413.565 ERROR    lxc_start - start.c:__lxc_start:1866 - Failed to spawn container "c1"
lxc 20180521172413.566 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:130 - Connection reset by peer - Failed to receive response for command "get_cgroup"
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by brauner** [comment]
The Nvidia runtime hook currently does not work with privileged containers since it requires adding permissions to the devices cgroup when the hook is run.

> If you arrive here will see that LXD is hanged and cannot start or stop or restart any container until restart the host.

That particular problem can be prevented by using `--force` when stopping the container.

**Comment by cyberwillis** [comment]
Hi ..
Any advice in how can I map a folder inside the container **without being a privileged user**, and where I can manipulate that files from that folder without root ?

**Comment by brauner** [comment]
If all the files you care about are owned by a single user - preferably not the root user - then you could punch a hole in the idmap of the container. For example, if you care about a specific folder on the host that contains files for `uid` `1000` you could specify:

    lxc config set <container-name> raw.idmap "both 1000 1000"

restart the container

    lxc restart <container-name>

and attach the folder to the container, e.g.:

    lxc config device add <container-name> my-folder disk source=/opt path=/opt

**Comment by cyberwillis** [comment]
Hi,
This solved all my problems.

Thank you.

**Comment by gvijqb** [comment]
Hi @cyberwillis were you able to access GPU view nvidia.runtime in privileged mode in LXC? I'm still facing this issue. I get a forkstart error on lxc container reboot.

**Comment by cyberwillis** [comment]
Hi...

This problem happened to me a long time ago. Previously I was using LXD 3.0 but now I am using 4.0 and I don't use the following settings anymore:
`security.privileged=true`

**Comment by cyberwillis** [comment]
I remember now .. I used that setting to be able to map a shared folder with Host machine ...  because without that the folder become without owner "nobody" and only root will be able to use this folder.

Right now I use 
```
lxc config set "CONTAINER_NAME" raw.idmap "both ${UID} 1000"
```

In this way I have normal access to my folders mapped in host with my "custom" user inside the container without needing the priviledged that can cause GPU access problems.

**Comment by gvijqb** [comment]
Thanks @cyberwillis for this suggestion. It did enable me to get GPU access inside lxc container. But my issue is that I am trying to run docker with GPU inside my lxc container. So when I do this:

`sudo docker run --rm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all -it nvidia/cuda
`
It displays this error:

`stderr: nvidia-container-cli: mount error: write error: .....  operation not permitted
`

And this is resolved with security privileged mode. But security.privileged mode doesn't work with nvidia runtime. So I'm stuck in a limbo. Unable to run docker with gpu inside lxc that has runtime true and privilege false.

**Comment by gvijqb** [comment]
Hi @cyberwillis were you able to run docker container with GPUs inside LXC container by just providing the nvidia runtime and the idmap settings? I am unable to do so. It still results in operation not permitted error.

**Comment by cyberwillis** [comment]
Nope. Appear is not possible anymore.

**Comment by cyberwillis** [comment]
Hi again @gvijqb ,

Just to let you know that running docker with GPU inside the LXD become possible again in unpriviledged container.

However to do this you need to have the lastest libLXC installed inside the LXD (from SNAP). also using `nvidia.runtime true` not possible.

I just tested here and is working.
