### ISSUE TITLE
LXD in cluster doesn't see containers on another node

### ISSUE THREAD

**Issue by zacksiri** [lxc/lxd#4575]
# Required information

 * Distribution: Bionic 18.04
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-20-generic
   * LXC version: 3.0.0
   * LXD version: 3.0.0
   * Storage backend in use: zfs

# Issue description

When I edit a profile on one machine that applies to multiple container, and some of those container live on a different node, I get an error. 

# Steps to reproduce

 1. create a profile
 2. assign profile to containers on different nodes
 3. edit the profile and save

# Information to attach

```
Config parsing error: The following containers failed to update (profile change still saved):
 - some-container: No such object
```

I suspect that the issue is related to the fact that lxd can't find containers by host name.

**Comment by freeekanayaka** [comment]
I can reproduce the problem, I'm adding this to the list of clustering-related issues I'm working on.

**Comment by zacksiri** [comment]
@freeekanayaka while your at it I think this is the same problem https://github.com/lxc/lxd/issues/4569
