### ISSUE TITLE
lxd.migrate Fails

### ISSUE THREAD

**Issue by Whytey** [lxc/lxd#4583]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 14.04.5 (with xenial kernel)
 * The output of "lxc info":
```
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-127-generic
  server: lxd
  server_pid: 11048
  server_version: 2.0.11
  storage: zfs
  storage_version: "5"
```

# Issue description

Was running the PPA version but moved to LXD 3.1 from snap on my server.  Trying to migrate fails everytime.

```
djwhyte@server1:~$ sudo lxd.migrate 
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks

=== Source server
LXD version: 2.0.11
LXD PID: 10683
Resources:
  Containers: 2
  Images: 1

=== Destination server
LXD version: 3.1
LXD PID: 6122
Resources:
  Containers: 0
  Images: 0
  Networks: 0
  Storage pools: 0

The migration process will shut down all your containers then move your data to the destination LXD.
Once the data is moved, the destination LXD will start and apply any needed updates.
And finally your containers will be brought back to their previous state, completing the migration.

Are you ready to proceed (yes/no) [default=no]? yes
=> Shutting down the source LXD
=> Stopping the source LXD units
error: Failed to stop the source LXD units: Failed to run: initctl stop lxd: initctl: Job failed while stopping
```
And, my path, since it is possibly related.
```
djwhyte@server1:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/var/lib/snapd/snap/bin:/snap/bin:/var/lib/snapd/snap/bin
```

# Steps to reproduce

 1. Make sure original LXD is running
 2. Run sudo lxd.migrate
 3. Failure

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
So the issue here is that `initctl stop lxd` is failing for some reason.
What does `initctl status lxd` show you and is there anything relevant looking in `/var/log/upstart/lxd.log`?

**Comment by Whytey** [comment]
Hi,

That's an obvious question I should have preempted.

Trying to manually stop lxd:
djwhyte@server1:~$ sudo initctl stop lxd
initctl: Job failed while stopping
djwhyte@server1:~$


Upstart log (don't know why the ESC chars are present):
ESC[33mWARNESC[0m[05-24|21:20:26] CGroup memory swap accounting is
disabled, swap limits will be ignored.
ESC[31mERORESC[0m[05-24|21:32:30] Failed shutting down container
ESC[31mactionESC[0m=shutdown ESC[31mcreation
dateESC[0m=2018-05-20T11:16:10+00
0 ESC[31mephemeralESC[0m=false ESC[31mnameESC[0m=hass
ESC[31mtimeoutESC[0m=30s
lxd-bridge isn't running
ESC[33mWARNESC[0m[05-24|21:33:01] CGroup memory swap accounting is
disabled, swap limits will be ignored.
ESC[31mERORESC[0m[05-24|21:33:44] Failed shutting down container
ESC[31mactionESC[0m=shutdown ESC[31mcreation
dateESC[0m=2018-05-20T11:16:10+00
0 ESC[31mephemeralESC[0m=false ESC[31mnameESC[0m=hass
ESC[31mtimeoutESC[0m=30s
lxd-bridge isn't running
ESC[33mWARNESC[0m[05-24|21:34:14] CGroup memory swap accounting is
disabled, swap limits will be ignored.
lxd-bridge isn't running
ESC[33mWARNESC[0m[05-24|21:35:51] CGroup memory swap accounting is
disabled, swap limits will be ignored.
lxd-bridge isn't running
ESC[33mWARNESC[0m[05-24|21:41:31] CGroup memory swap accounting is
disabled, swap limits will be ignored.
lxd-bridge isn't running
ESC[33mWARNESC[0m[05-24|21:47:49] CGroup memory swap accounting is
disabled, swap limits will be ignored.
lxd-bridge isn't running
ESC[33mWARNESC[0m[05-24|21:50:57] CGroup memory swap accounting is
disabled, swap limits will be ignored.
ESC[31mERORESC[0m[05-24|22:07:40] Failed shutting down container
ESC[31mactionESC[0m=shutdown ESC[31mcreation
dateESC[0m=2018-05-20T11:16:10+00
0 ESC[31mephemeralESC[0m=false ESC[31mnameESC[0m=hass
ESC[31mtimeoutESC[0m=30s
lxd-bridge isn't running
ESC[33mWARNESC[0m[05-24|22:08:00] CGroup memory swap accounting is
disabled, swap limits will be ignored.
lxd-bridge isn't running
(END)

I'm not using the lxd-bridge.

Thanks,
Whytey

**Comment by stgraber** [comment]
Ok, so given you're not using lxd-bridge and this is a one-time upgrade, lets just cheat.
```
rm /usr/lib/lxd/lxd-bridge
ln -s /bin/true /usr/lib/lxd/lxd-bridge
```

This should cause any bridge-related errors to go away and hopefully make it so you can `initctl start lxd` and `initctl stop lxd` without errors. At which point, you can make sure it's started and run `lxd.migrate`.

**Comment by Whytey** [comment]
Thanks. Can run initctl perfectly now. Will attempt the migration once I'm home from work tonight. 

Great, responsive support. 👍

**Comment by Whytey** [comment]
OK, got much further, but looks like there is a failure with storage.

```
djwhyte@server1:~$ sudo lxd.migrate 
[sudo] password for djwhyte: 
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks

=== Source server
LXD version: 2.0.11
LXD PID: 29036
Resources:
  Containers: 2
  Images: 1

=== Destination server
LXD version: 3.1
LXD PID: 6122
Resources:
  Containers: 0
  Images: 0
  Networks: 0
  Storage pools: 0

The migration process will shut down all your containers then move your data to the destination LXD.
Once the data is moved, the destination LXD will start and apply any needed updates.
And finally your containers will be brought back to their previous state, completing the migration.

Are you ready to proceed (yes/no) [default=no]? yes
=> Shutting down the source LXD
=> Stopping the source LXD units
=> Stopping the destination LXD unit
=> Unmounting source LXD paths
=> Unmounting destination LXD paths
=> Wiping destination LXD clean
=> Backing up the database
=> Moving the data
=> Updating the storage backends
error: Failed to update the storage pools: Failed to run: zfs set mountpoint=/var/snap/lxd/common/lxd/containers/db1.zfs lxd/containers/db1: umount: /var/lib/lxd/containers/db1.zfs: not found
cannot unmount '/var/lib/lxd/containers/db1.zfs': umount failed
```

Following some clues in #4123 to see if I can rectify.

**Comment by Whytey** [comment]
OK, seems that I needed to:
```
sudo initctl start lxd
```
and
```
sudo systemctl start snap.lxd.daemon
```
and then re-run lxd.migrate.  All seems to be working now.

Do you want to leave this bug open to address the original issue in the initctl script?

**Comment by stgraber** [comment]
Ok, good to hear that this did the trick.

I'm testing a fix in our packaging branch now. Could you give me your `/etc/default/lxd-bridge`, that'd be useful to reproduce the exact same setup.

**Comment by stgraber** [comment]
Fix tested and pushed to the lxd-pkg-ubuntu branch, so the next 14.04 upload will fix this.
