### ISSUE TITLE
lxd-p2c Error: not authorized

### ISSUE THREAD

**Issue by erickeller** [lxc/lxd#4586]
I was playing around with the latest master version of the `lxd-p2c` following 
https://fosdem.org/2018/schedule/event/containers_physical_migration/ 

```
[root@foosystem ~]# lxd-p2c --version
3.1
```

I have an existing central lxd server where the following was configured:

```
lxc --version
3.0.0
lxc config set core.trust_password foobar
lxc config set core.https_address "[::]:8443"
```

I can push and pull lxd images from this host.

Now trying to use the `lxd-p2c` from a running system:

```
[root@foosystem ~]# lxd-p2c https://lxd.test.com:8443 foosystem /
Generating a temporary client certificate. This may take a minute...
Certificate fingerprint: 1bc...
ok (y/n)? y
Admin password for https://lxd.test.com:8443: 
Error: not authorized
```

on the side of my `lxd.test.com:8443` I can see that the client gets trusted with the command:
```
lxc config trust list | grep foosystem
```

refering to https://github.com/lxc/lxd/issues/4453 I think that there is no possibility to really check what went wrong with the authorization --debug would be helpful here...

foosystem host: 
```
[root@foosystem ~]# lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.7 (Final)
Release:	6.7
Codename:	Final
[root@foosystem ~]# uname -a
Linux foosystem 2.6.32-573.7.1.el6.x86_64 #1 SMP Tue Sep 22 22:00:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Is there some restriction about the running system?
How could I get more details about why the authorization failed?

Regards

**Comment by stgraber** [comment]
That error is coming directly from the LXD server, so it's not happy about something with that certificate.
You may want to run `lxc monitor` on the LXD server side to get more details, the output of `lxc config trust list` may also point to the problem.

One reason I can think of is if your CentOS server is somehow running with an invalid clock, causing the client certificate it's generating to be invalid.

**Comment by erickeller** [comment]
Thanks for all these hints will go down this path later today

**Comment by erickeller** [comment]
well you were absolutely right the time drifted some 20 sec.
I definitively learned something with `lxc monitor` 
it was helpful and pointed out some Database error, I do not know if this is relevant or not...

```
metadata:
  context: {}
  level: dbug
  message: 'Database error: &errors.errorString{s:"No such object"}'
timestamp: "2018-05-25T06:51:54.145685901Z"
type: logging
```

Finally the following message was displayed
```
Error: No storage pool found. Please create a new storage pool.
```

I suspect that using the `lxd-p2c` means lxd has to be installed as a prerequisite on the host to migrate...
This would mean that I have to also build lxc from the sources and install it on the host I want to migrate.
Or do you have some other hints?

**Comment by stgraber** [comment]
Nope, LXD doesn't need to be installed on the source host at all.

The error you received is because your target LXD appears to be missing a storage pool or its default profile doesn't have a storage pool in it?

What does `lxc storage list` and `lxc profile show default` get you on that target LXD?

**Comment by stgraber** [comment]
Did you ever run `lxd init` on your target LXD? That should have configured things for you.

**Comment by erickeller** [comment]
And again you were able to feel where the problem comes from... as the message did tell me indeed.
I could argue that the message could be improved a little:

```
Error: No storage pool found on `https://lxd.test.com:8443`. Please create a new storage pool.
```

```
lxc storage list
+------+-------------+--------+--------+---------+
| NAME | DESCRIPTION | DRIVER | SOURCE | USED BY |
+------+-------------+--------+--------+---------+

```

```
lxc profile show default
config: {}
description: Default LXD profile
devices: {}
name: default
used_by: []
```

so I tried it out from an ubuntu VM and it now seems to work :)

```
Transferring container: foosystem: 625.25MB (69.45MB/s)
```

One last question, where could I find some doc or code where you decide what has to be part of a LXD container image when you migrate from physical to container?

I played a bit around with taring the complete / except /tmp/* /var/cache/* /dev/... but would be helpful to understand how to ensure that the files of the service I am hosting on the physical device get preserved but things like /etc/udev/90-network.conf containing specific hardware related rules get discarded...

/etc/fstab also should be discarded since it could contain information about lvm partitions, ...

Any resources?

**Comment by stgraber** [comment]
I'm not aware of anyone having published much about this yet. In general my recommendation would be to transfer everything except what's obviously ephemeral data (/tmp and /var/tmp), then on the remote system, clean things up a bit:
 - Uninstall the kernel and bootloader packages
 - Cleanup /etc/fstab
 - Cleanup the network config
 - Look for any running services that's running and which you don't need anymore and uninstall/disable those too
 - Look through the installed package list for anything that seems obviously unnecessary
 - Do a container restart test, make sure the right network is coming up and that your services are back online

**Comment by erickeller** [comment]
thanks for all your support with this tool and the last comment about the high level process to convert a running system to a container.
