### ISSUE TITLE
API extension via plugin or module

### ISSUE THREAD

**Issue by RevoluPowered** [lxc/lxd#4588]
I want to essentially make a plugin to manage my container's network and also to provide cloud like service discovery.

Does LXD have an API for extending it with plugins, or is it worth a PR?

**Comment by stgraber** [comment]
One thing we've though about in the past and may find acceptable is #3391

**Comment by RevoluPowered** [comment]
"What exactly are you trying to do which can't be done by an API client of our existing API?"

Automatically handle NAT and automatically give IP's for each container started, without modifying iptables manually.

**Comment by stgraber** [comment]
Is there a reason why you can't route your public subnet to the LXD bridge (see ipv4.routes config key) and then feed the containers a static IP through cloud-init data?

That's what most of our users seem to be doing when providing public addresses to their containers (usually on hosting provides like OVH or Hetzner).

**Comment by stgraber** [comment]
In any case, as configuring iptables can happen even after the container has started, it sounds like the lifecycle events we push out right now would be sufficient for such a tool.

**Comment by RevoluPowered** [comment]
Can you provide an example of how to make this work? 

I'm fairly new to LXD.

**Comment by stgraber** [comment]
@RevoluPowered https://github.com/lxc/lxd/blob/master/lxc/monitor.go#L96 has an example of a events API client.

That handler is called everytime a relevant message is sent. You can look at messages by running `lxc monitor`.

With code similar to that above, you can filter for those events you care about (type=lifecycle, action=container-started) like this one:
```
metadata:
  action: container-started
  source: /1.0/containers/centos4
timestamp: "2018-05-30T13:29:03.323275991-04:00"
type: lifecycle
```

And then spawn your `iptables` subcommand, possibly fetching more information about the container through `GetContainer` and `GetContainerState`.

https://godoc.org/github.com/lxc/lxd/client has more details to get you started with our Go API.

If not using Go for this, then you'll need a websocket capable HTTP client to hit /1.0/events on the REST API, you'll then receive one message per event with the same format as shown above.

**Comment by RevoluPowered** [comment]
What I'll do is start throwing something together this weekend and see where I get. 

I'm probably going to put the code in the game server management software, I can use C# with RestSharp to access your HTTP web end point.

Only question left is, how is auth handled, I think I've read it's password protected?

Thanks for your help @stgraber
