### ISSUE TITLE
Enhancement Request: lxc list --format=csv --columns=46 convert newlines to whitespace

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#4593]
Currently --format=csv for ipv4 + ipv6 addresses are returned with embedded newline characters embedded in records.

This means some variable number of lines per container, which makes parsing data fragile, because multiple lines must be gathered together to represent one container.

Be great if --format=csv converted any newlines in any columns to whitespace, to simplify parsing.

Thanks for considering this enhancement request.

**Comment by stgraber** [comment]
Space separation would break the current formatting as the interface name is shown after a space following the IP address.

I just checked our output and our CSV is valid multi-line. That is, any value that's multi-line gets quoted. This matches the CSV spec and should be interpreted properly by all valid CSV parsers.

As changing this would effectively break existing users and our output is spec-compliant, I don't intend to change it.

**Comment by davidfavor** [comment]
Thanks for the info.
