### ISSUE TITLE
lxd-p2c doesn't properly cleanup /etc/fstab and /etc/udev/rules.d/*

### ISSUE THREAD

**Issue by erickeller** [lxc/lxd#4603]
using lxd version 3.0 build from source.

the physical device is a rather old centos 6.7 where the disk is partition as LVM:
```
  LV      VG             Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_home vg_foobar -wi-ao---- 873.29g                                                    
  lv_root vg_foobar -wi-ao----  50.00g                                                    
  lv_swap vg_foobar -wi-ao----   7.73g
```

the /etc/fstab
```
/dev/mapper/vg_foobar-lv_root /                       ext4    defaults        1 1
UUID=...-fa0c-4637-aafd-... /boot                   ext4    defaults        1 2
/dev/mapper/vg_foobar-lv_home /home                   ext4    defaults        1 2
/dev/mapper/vg_foobar-lv_swap swap                    swap    defaults        0 0
tmpfs                   /dev/shm                tmpfs   defaults        0 0
devpts                  /dev/pts                devpts  gid=5,mode=620  0 0
sysfs                   /sys                    sysfs   defaults        0 0
proc                    /proc                   proc    defaults        0 0
```

using `lxd-p2c https://lxd.home:8443 foobar /` result in the foobar container on this remote.

starting the container on the remote with `lxc start foobar` and inspecting it with `lxc exec foobar bash` I discovered that some process try to check the lvm partition...

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  17188  2244 ?        Ss   11:06   0:00 /sbin/init
root        31  0.0  0.0 108532  3372 console  Ss   11:06   0:00 /bin/bash /etc/rc.d/rc.sysinit
root       105  0.0  0.0  10920  1812 ?        Ss   11:06   0:00 /sbin/udevd -d
root       127  0.0  0.0 105216  1968 console  S+   11:06   0:00 fsck -T -t noopts=_netdev -A -a -C
root       128  0.0  0.0 113940  2476 console  S+   11:06   0:00 fsck.ext4 -a -C0 /dev/mapper/vg_foobar-lv_root
root       129  0.0  0.0 108372  2700 ?        Ss   11:06   0:00 bash
root       143  0.0  0.0 110220  1900 ?        R+   11:06   0:00 ps aux
```

overwriting the /etc/fstab with did the trick...
```
/dev/root               /                       rootfs   defaults        0 0
```

Then the container was not able to grab an ip... since there were some left-over from /etc/udev/rules.d/70-persistent-net.rules having some specific MAC address

```
mv /etc/rules.d /etc/rules.d.org && mkdir -p /etc/rules.d && cp -f /etc/rules.d.org/60-raw.rules /etc/rules.d/
```

in the `/etc/sysconfig/network-scripts/` I also had to remove the hardcoded MAC address and finally the container could be restarted and obtained a valid ip and started the same services as on the physical box.

I am wondering if these steps could be automated as part of the lxd-p2c tool? or if an additional rsync parameter with `--exclude-from=/path/to/exclusion-file` would be enough?

would the lxd automatically generate the /etc/fstab if missing?

**Comment by stgraber** [comment]
Hey there,

LXD never modifies any file inside the container nor does `lxd-p2c`, there will indeed be a number of files in /etc and possibly in /var which include hardware-specific details like MAC addresses, storage devices, ... `lxd-p2c` can't know about all of those and attempting to just re-generate those files automatically may be dangerous (not to mention would need logic for every version of every Linux distribution).

Instead, we expect users that use this tool to start the resulting container, fix any of those issues by looking at boot logs and then restart the reconfigured container to confirm everything is good.

**Comment by erickeller** [comment]
Yep I was able to fix the container and start the complete.
As you mentioned in the previous issue #4586 there are some things one could do automatically like:

* /etc/fstab since there is no partitioning in a container and using the `lxd-p2c` on / would mean rsync everything flat.
* network config as the default template can also be guessed depending on the distribution at least for the one interface bridged to the lxdbr0.

but you are right in many case it means one has to really about all the quirks of the specific distribution...
The lxd-p2c did it's job well thanks for it!

final note: using the proxy device like following did the trick to forwarding the traffic from the host the the newly born lxd container way better than static iptables rules since the container ip could change and this still would continue to work.

```
lxc config device add foobar proxy0 proxy listen=tcp:0.0.0.0:80 connect=tcp:127.0.0.1:80 bind=host
```

I think we can close this issue.

**Comment by stgraber** [comment]
Well, the problem is that fstab can be pretty subtle, it'd be perfectly valid to list the host's block device in there with / as the target and extra mount options passed afterwards, that'd have init in the container perform a remount with the extra options.

Similarly, a wide number of virtual filesystems (proc, sys, tmpfs, fuse, nfs, ...) may have been configured and should at least be attempted to be mounted.

In quite a few cases, a boot hang/failure during mounting is much preferable to having the actual data path not be mounted, which could then cause a service to still start but use an empty storage path.


My hope is that users will document what steps they had to take on various distributions, ideally as forum topics on https://discuss.linuxcontainers.org so we'll end up with a bunch of good guides for people converting systems to containers.
