### ISSUE TITLE
Error removing node from a cluster

### ISSUE THREAD

**Issue by vikrantrathore** [lxc/lxd#4615]
# Required information

 * Distribution:
 * Distribution version:
  driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-1008-gcp
  server: lxd
  server_pid: 20395
  server_version: "3.1"
  storage: btrfs
  storage_version: "4.4"
  server_clustered: true
# Issue description
After creating a cluster one node automatically went offline and cannot become part of the cluster. Most likely ran snap refresh lxd which might have updated it to 3.0.1. But when I tried restarting it on the new node snap start fails silently.  Subseqently re-install and try to add it again did not work either.

# Steps to reproduce

 1. lxc list
+-------------+-----------------------+----------+---------+-------------------------------------+
|    NAME     |          URL          | DATABASE |  STATE  |               MESSAGE               |
+-------------+-----------------------+----------+---------+-------------------------------------+
| test1            | https://10.8.8.4:8443 | YES      | ONLINE  | fully operational                   |
+-------------+-----------------------+----------+---------+-------------------------------------+
| test2            | https://10.8.8.2:8443 | YES      | ONLINE  | fully operational                   |
+-------------+-----------------------+----------+---------+-------------------------------------+
| test3            | https://10.8.8.3:8443 | NO       | OFFLINE | no heartbeat since 20m51.090968941s |
+-------------+-----------------------+----------+---------+-------------------------------------+

 2. lxc cluster remove test3
 3. Error:
Error: Delete https://10.8.8.3:8443/1.0/storage-pools/local: Unable to connect to: 10.8.8.3:8443
But the purpose of step2 is to take this node out of the cluster completely.

# Information to attach

Error: Delete https://10.8.8.3:8443/1.0/storage-pools/local: Unable to connect to: 10.8.8.3:8443

**Comment by vikrantrathore** [comment]
Removed forcibly using -f flag.

**Comment by vikrantrathore** [comment]
After removing the node by force from another node. The node itself stops lxd daemon from running. The log in the node which needs to be reset are:

2018-06-01T07:46:39Z lxd.daemon[29724]: lvl=eror msg="Failed to start the daemon: failed to open cluster database: failed to ensure schema: failed to update node version info: updated 0 rows instead of 1" t=2018-06-01T07:46:39+0000
2018-06-01T07:46:39Z lxd.daemon[29724]: Error: failed to open cluster database: failed to ensure schema: failed to update node version info: updated 0 rows instead of 1

**Comment by freeekanayaka** [comment]
If you use --force to delete a node, the online nodes of the cluster do not inform the node being deleted that it has been deleted.

This means the node still thinks it's part of the cluster, and currently you'll need to purge it and start from scratch.

We do know that the refresh process of the LXD snap has some bugs somewhere (either in our snap scripts, in the LXD clustering-related code, or both), but we haven't yet been able to identify or reproduce them. It's on our radar screen tho.

**Comment by stgraber** [comment]
Not sure that it's the snap refresh that caused it though as LXD 3.1 got rolled out 4 days ago and all systems running snapd refresh at least once a day. The `lxc info` output above also reports 3.1 which suggests that the rest of the cluster did upgrade properly to 3.1.

It could be that the faulty node is the one that didn't refresh to 3.1 though, that'd explain why the other nodes refused to talk to it. As mentioned in our documentation, all cluster nodes must be running the same LXD version. That means that when upgrading to the next feature release (3.1 in this case), some nodes will appear offline until they all get on the new version.


In this case, LXD seems to have done what you asked it to do, though why this node went offline in the first place isn't something that can be tracked down after it was forcefully removed. If you or someone else run into the same situation, please file a support request on our forum or respond in this issue BEFORE you remove any nodes from your cluster, that way we can figure out what's going on and most likely let you bring your node back online.

**Comment by vikrantrathore** [comment]
As you mentioned I tried upgrading snap to another node and got following error after refresh:
```
sudo snap refresh lxd
error: cannot perform the following tasks:
- Run configure hook of "lxd" snap if present (run hook "configure": error: cannot communicate with server: Post http://localhost/v2/snapctl: dial unix /run/snapd-snap.socket: connect: no such file or directory)
```

**Comment by stgraber** [comment]
@vikrantrathore hmm, can you try `systemctl reload snap.lxd.daemon && snap refresh lxd` see if that helps somehow?

**Comment by vikrantrathore** [comment]
When I try it works.
```
sudo  systemctl reload snap.lxd.daemon && sudo snap refresh lxd
lxd 3.1 from 'canonical' refreshed
```
