### ISSUE TITLE
clean lxd and reuse existing zfs pool with containers 

### ISSUE THREAD

**Issue by mysiar** [lxc/lxd#4619]
# Required information

 * Distribution: Ubuntu server
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.15.0-22-generic
   * LXC version: 3.0.0
   * LXD version: 3.0.0
   * Storage backend in use: zfs

# Issue description

After system disk failure I had to reinstall system.
I have sperate disk with zfs pool for lxd called lxd.
I can list it
```
zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
lxd   1.81T  60.0G  1.75T         -     0%     3%  1.00x  ONLINE  -

zfs list
NAME                                                                          USED  AVAIL  REFER  MOUNTPOINT
lxd                                                                          60.0G  1.70T    96K  none
lxd/containers                                                               59.6G  1.70T    96K  none
lxd/containers/bitbucket                                                      878M  1.70T  1.24G  /var/lib/lxd/storage-pools/lxd/containers/bitbucket
lxd/containers/entry                                                          123M  1.70T   510M  /var/lib/lxd/storage-pools/lxd/containers/entry
lxd/containers/jira                                                          1.25G  1.70T  1.46G  /var/lib/lxd/storage-pools/lxd/containers/jira
lxd/containers/nextcloud-snap                                                56.9G  1.70T  57.3G  /var/lib/lxd/storage-pools/lxd/containers/nextcloud-snap
lxd/containers/rocket-chat-snap                                               418M  1.70T   807M  /var/lib/lxd/storage-pools/lxd/containers/rocket-chat-snap
lxd/custom                                                                     96K  1.70T    96K  none
lxd/deleted                                                                    96K  1.70T    96K  none
lxd/images                                                                    411M  1.70T    96K  none
lxd/images/9879a79ac2b208c05af769089f0a6c3cbea8529571e056c82e96f1468cd1f610   411M  1.70T   411M  none
lxd/snapshots                                                                 192K  1.70T    96K  none
lxd/snapshots/jira                                                             96K  1.70T    96K  none

```

I can't attach this existing pool to new lxd.
Tried lxd init and storage create and set with no luck

Could anybody enlighten me how to get it done ?

**Comment by stgraber** [comment]
You can't attach a populated zfs dataset as an empty storage pool in LXD.

If you want to import the existing containers into the LXD database, you should use the disaster recovery `lxd import` command (see backup.md). If you want to start clean instead, then wipe your dataset and then add it to LXD.

**Comment by mysiar** [comment]
Ok.
How exactly this scenario looks like?
I have clean lxd.
Understand that I have to create new zfs pool for lxd.
How I can import from other zfs pool all my containers to current running lxd?

**Comment by stgraber** [comment]
As I said, use `lxd import` per the backup.md documentation

**Comment by stgraber** [comment]
http://lxd.readthedocs.io/en/latest/backup/#container-backup-and-restore

**Comment by stgraber** [comment]
Closing as this is a support request and not an actual LXD issue. The LXD forum would have been a better fit for this.

**Comment by RanMaosong** [comment]
Have you solve the problem? Tank you!
