### ISSUE TITLE
lxd-p2c 3.1 protocol incompatibility error

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#4622]
Unsure how to debug this as passing rsync args doesn't seem to echo any useful diagnostics.
```
# lxd-p2c https://net10.bizcooker.com:8443 net10-foo / --rsync-args=-vvv
Generating a temporary client certificate. This may take a minute...
Certificate fingerprint: 523419338c8557663e0e774dacffbbfc78c66a00823113a5959bdd41157b8d6e
ok (y/n)? y
Admin password for https://net10.bizcooker.com:8443:
# Data transfers for roughly 20 seconds... then...
Transferring container: net10-foo: 550.22MB (34.96MB/s)Error: Failed to rsync: exit status 2
Invalid remainder length 117506043 [sender]
rsync error: protocol incompatibility (code 2) at io.c(1923) [sender=3.1.0]
unexpected tag -7 [sender/inc]
```
The net10-foo container log on target machine is empty.

Only info in lxd.log is...
```
ephemeral=false lvl=info msg="Creating container" name=net10-foo t=2018-06-04T14:54:26+0000
ephemeral=false lvl=info msg="Created container" name=net10-foo t=2018-06-04T14:54:27+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=net10-foo t=2018-06-04T14:54:27+0000
err="Failed to rsync: exit status 2\nInvalid remainder length 16777216 [sender]\nrsync error: protocol incompatibility (code 2) at io.c(1923) [sender=3.1.0]\nunexpected tag -103 [sender/inc]\n" lvl=eror msg="Error during migration sink" t=2018-06-04T14:54:45+0000
created=2018-06-04T14:54:26+0000 ephemeral=false lvl=info msg="Deleting container" name=net10-foo t=2018-06-04T14:54:45+0000 used=1970-01-01T00:00:00+0000
lvl=eror msg="Rsync receive failed: /var/snap/lxd/common/lxd/containers/net10-foo/: exit status 2: " t=2018-06-04T14:54:45+0000
created=2018-06-04T14:54:26+0000 ephemeral=false lvl=info msg="Deleting container" name=net10-foo t=2018-06-04T14:54:45+0000 used=1970-01-01T00:00:00+0000
created=2018-06-04T14:54:26+0000 ephemeral=false lvl=info msg="Deleted container" name=net10-foo t=2018-06-04T14:54:49+0000 used=1970-01-01T00:00:00+0000
created=2018-06-04T14:54:26+0000 ephemeral=false lvl=info msg="Deleted container" name=net10-foo t=2018-06-04T14:54:50+0000 used=1970-01-01T00:00:00+0000
```
So I guess first question will be to say where output of rsync -vvv emits.

Another question will be why transfer runs for a while + then dies.

Normally rsync **protocol incompatibility** blocks transfers from starting at all.

In this case source machine is rsync 3.1.0 + target machine is 3.1.2 + manual rsync commands work well, so something seems slightly off with lxd-p2c.

Let me know how to debug this.

Thanks.

**Comment by davidfavor** [comment]
Found another way to migrate entire machines, which allows multiple rsyncs/updates of portions of file tree + provides incremental/instant feedback of any problems.

Here's an example of migrating a very old Trusty machine to a Trusty container on a new machine.

On target LXD machine called net10.
```
# Create 64 bit container to match machine
lxc init ubuntu:trusty/amd64 net10-trusty-machine

# Set privileged, so there's no uid/gid rewrite problems to debug
lxc config set net10-trusty-machine security.privileged true

# Verify new container works
lxc start net10-trusty-machine
lxc exec net10-trusty-machine bash

# Move current rootfs aside + create empty rootfs
lxc stop net10-trusty-machine
cd /var/snap/lxd/common/lxd/storage-pools/default/containers/net10-trusty-machine
mv rootfs rootfs.aside
mkdir rootfs

# Clone files
sync -aAXv -e "ssh -i /root/.ssh/your-key-file.rsa" --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} trusty-machine.foo.com:/. rootfs/.

# Following commands brings database files consistent, if required.
# on source machine - service mysql stop
# on target machine - rsync -aAXv -e "ssh -i /root/.ssh/your-key-file.rsa"  trusty-machine.foo.com:/var/lib/mysql/. rootfs/var/lib/mysql/.
# on source machine - service mysql start

# fix /etc/network/interfaces or whatever file defines public interface
# fix /etc/fstab, to contain - LABEL=cloudimg-rootfs	/	 ext4	defaults	0 0

lxc start net10-trusty-machine
```
Once first rsync above occurs, newly created container can be turned over to developers to test + then after testing is complete, a final lxc top + rsync can be done again to pull entire machine or just database.

At this point security.privileged can be set to false + container restarted, if desired.

**Comment by stgraber** [comment]
Note that the above approach will not work if using zfs, lvm or ceph as with those, the container directory isn't mounted when the container is stopped.

**Comment by davidfavor** [comment]
Be great to have an update with ideas about how to work around the rsync **protocol incompatibility error**.

**Comment by stgraber** [comment]
Can you run the current version with `-vv` to see what it says?

**Comment by davidfavor** [comment]
```
# lxd-p2c https://net10.bizcooker.com:8443 net10-foo-p2c-test / --rsync-args=-vv
Generating a temporary client certificate. This may take a minute...
Certificate fingerprint: 523419338c8557663e0e774dacffbbfc78c66a00823113a5959bdd41157b8d6e
ok (y/n)? y
Admin password for https://net10.bizcooker.com:8443: 
Transferring container: net10-foo-p2c-test: 553.98MB (35.30MB/s)Error: Failed to rsync: exit status 2
Invalid remainder length 117506043 [sender]
rsync error: protocol incompatibility (code 2) at io.c(1923) [sender=3.1.0]
unexpected tag -7 [sender/inc]
```

**Comment by stgraber** [comment]
Can you try with "-vvP"? that may tell us what file it's failing on.

**Comment by davidfavor** [comment]
```
# lxd-p2c https://net10.bizcooker.com:8443 net10-foo-p2c-test / --rsync-args=-vvP
Generating a temporary client certificate. This may take a minute...
Certificate fingerprint: 523419338c8557663e0e774dacffbbfc78c66a00823113a5959bdd41157b8d6e
ok (y/n)? y
Admin password for https://net10.bizcooker.com:8443: 
Transferring container: net10-foo-p2c-test: 549.26MB (42.06MB/s)Error: Failed to rsync: exit status 2
Invalid checksum count -83886080 [sender]
rsync error: protocol incompatibility (code 2) at io.c(1905) [sender=3.1.0]
unexpected tag -7 [sender/inc]
```

**Comment by stgraber** [comment]
Hmm, so it's failing before it even reaches a particular file, that's odd. I don't suppose that you have an easy reproducer for this?

What distro, release, ... is used on the source system?

**Comment by davidfavor** [comment]
```
net2-newswire# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```
All rsync updates installed.

**Comment by davidfavor** [comment]
If you have any ideas about this, let me know + I'll provide you with whatever data seems useful.

**Comment by stgraber** [comment]
I'd also recommend not actually migrating a live system, you're going to run in a lot less potential issues if you stop most services prior to running lxd-p2c. Databases come to mind as far as services that should definitely be stopped.

**Comment by davidfavor** [comment]
Yep. And there will always be system files changing. Simple things like /var/log + cache files will never be quiet, so passing --ignore-errors allows rsync to survive simple system noise.

**Comment by stgraber** [comment]
--ignore-errors will hide much more errors than we'd like though, that's why the current code passes --ignore-missing-args when on rsync 3.1.0 or higher which is supposed to allow for files vanishing.

**Comment by davidfavor** [comment]
So to get this to work on a noisy system, just --exclude=... offending directories + also pass --ignore-errors to avoid oddball files which might change.

xd-p2c https://149.56.26.56:8443 p2c-test / --rsync-args="--ignore-errors --exclude=/var/cache --exclude=/var/log"

Then afterwards I can manually rsync /var/log to create files with correct ownership + permissions.

Let me know if this seems correct to you.

**Comment by stgraber** [comment]
Yeah, that approach should be fine, hopefully it won't be needed for many cases, but when moving a busy system, that's certainly an option.

I'd normally recommend stopping as many of the services that are running on the system, including things like rsyslogd (to avoid the /var/log issue), after which lxd-p2c should be able to run without errors and save you the extra rsync runs.

**Comment by davidfavor** [comment]
Note: Just migrated a super old Ubuntu Saucy machine using lxd-p2c + --ignore-errors which worked like a charm.

This machine was running rsync 3.0.9 so looks like all rsync compatibility issues are fixed now.

Thanks!

**Comment by adityacloud1** [comment]
Respected @davidfavor  , I am also migrating container using `lxd move,` command. But, for the workload that change filesystem,  `Rsync send failed` error occurs each time.

How to resolve this issue using `--ignore-missing-args` parameter.

**Comment by adityacloud1** [comment]
[https://github.com/checkpoint-restore/criu/issues/576#issuecomment-442955756](url)
