### ISSUE TITLE
MAAS Integration with LXD 3.0.0

### ISSUE THREAD

**Issue by laralar** [lxc/lxd#4627]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  maas.api.key: MK4Qp5GKDLjUu2khVh:Fa9bjsD37tsANX3Hpr:YMdnsak5Ete2ypqqK3etvrr3cEA4pXhG
  maas.api.url: http://10.3.4.10:5240/MAAS
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.30.60.14:8443
  - 10.3.4.14:8443
  - 192.168.122.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFTDCCAzSgAwIBAgIQSkN0jYBB/wT0hHA2QbzeDDANBgkqhkiG9w0BAQsFADA0
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QG5v
    ZGUxNDAeFw0xODA2MDcxNDQ1NTRaFw0yODA2MDQxNDQ1NTRaMDQxHDAaBgNVBAoT
    E2xpbnV4Y29udGFpbmVycy5vcmcxFDASBgNVBAMMC3Jvb3RAbm9kZTE0MIICIjAN
    BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEApEg+hGwilADwr4WxMOg++PkqRkZL
    mGvLUEPZH2VvpWP2kcGhu5zlZth3an9hyzAMmKsx9g6/1m1Uwcwe+5FcB/Phc9r/
    lU8h5rK2IL5ABnR4Rck+4dAEFiRWnGAhv5hgPCA9W5BZrxkthcSFh5voO3twIU+i
    qiO2Lu/Y9mC0frZfN0kcScjQ2ZfT57nFG7opxK3ugI8CRdDaBzU4yk6hvBgK5nIs
    RJF+JKX56MTvQWYc1F4wPiZ0HX1MNw413sIWu4q0YHg55U10f24F6TO9ZdyKYPF/
    4uBoiLOniWHT/Vgg7gHKVIZT3/0YNl9s5PJ+nLHbwLn9/xlJ9LEhHBJtfJl2rqAJ
    zIhIjkOQX2C0tG5sXRLEidthiSagJ1rzeFAlSXrCh5R+jHa501d9SUV4bDSQ2YWl
    UKTODWNvjkLqyohsevhNCa54vZeN5t3brsoeFYGcW82pzFspKOrpo4c+GHwu7zpT
    ENrqUTMHBc9o9Il1irTGWqcS9PMV7BZQkBAniHWhOIUCIex0Uc4m08wk+cw36+pu
    BY14aZrwPMGauMVJQxJXGqIHUyQXQBOCV3TvTWaBUCHNrnCd/7v8IvFlNE6Pzm8z
    71a86Vaa01nYZsHsITi7SDfDnlawmaPZkCxgdtZ9wpZMzj6wkaNhdCgtVUe+yvwY
    8bEuAYa+OdIhAakCAwEAAaNaMFgwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoG
    CCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwIwYDVR0RBBwwGoIGbm9kZTE0hwQKHjwO
    hwQKAwQOhwTAqHoBMA0GCSqGSIb3DQEBCwUAA4ICAQAUygRrcbtsmUsvnVkEY6Oh
    ROUNQ86YYtJRYoc5vpl2kYYIAykn80qdXlHImPSP1iXJ1IOz5/KPL/MG909wJ0Vx
    DStyhQrejCEhZwk4yEoT2L/jOqffhG/y+XX1ALGhaaLMR0Y66Kek+mu8o4F5Y7De
    cJuwedgbKGnFYMw7uHJaxf1forfaxa6EHz+C+iTkN4ZiOUD6o18Rs+Uun0EhJ4UV
    F2H5J07ewqOEscczlT9G9ADAckShC2EF1zyDkZL8clnNNnuKBF9a+VkA3YFcFVaB
    tawCVQ/GyymKMmflZgIMaKtF245eA6HnlYjGhFiiJYHXjg4Tq96RyHzLupsFsome
    c5vsBS7BO12EWnavM233sJfcHMeBZi6Pds56SG5nHWW4dFWBYaXyf5aMoN9zqAda
    qhi3gb+yiFF5hoVkdVUigGEgKN1xQ7tEOZNADjVNibtk3p7yjRU/niD0uKn2Z5oU
    njUqjmkvTgt5eg8lcpA1xc1gwyMklXfI3gWiyXXuW75K6B7K3qmgUVcOB08SpFo9
    fYUNN5+7Wu7TsFI7N8PCPbZCtHeGADXpOP3eJgXUy0r5bnFmDToEI+ba/2gRuovS
    nB3BzoDM3GLNwdrwQ4MszaOk7NM+oxbkzzvWkuWhQCDH1VE0/tpHx5uJ/I5UQCiE
    t/T//ph0eyDSmGxVJP7SLw==
    -----END CERTIFICATE-----
  certificate_fingerprint: 2f791d30b593586a6f11a8417d591585601c38f0199761d8d6a6a7931aed0450
  driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-22-generic
  server: lxd
  server_pid: 7254
  server_version: 3.0.0
  storage: btrfs
  storage_version: 4.15.1
  server_clustered: true
  server_name: node14
```
# Issue description

1. lxd init fails
```
config:
  core.https_address: '[::]:8443'
  core.trust_password: *******
  maas.api.key: MK4Qp5GKDLjUu2khVh:Fa9bjsD37tsANX3Hpr:YMdnsak5Ete2ypqqK3etvrr3cEA4pXhG
  maas.api.url: http://10.3.4.10:5240
cluster:
  server_name: node14
  enabled: true
  cluster_address: ""
  cluster_certificate: ""
  cluster_password: ""
networks: []
storage_pools:
- config:
    source: /data/bpool/local
  description: ""
  name: local
  driver: btrfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      maas.subnet.ipv4: 10.30.61.0/24
      name: eth0
      nictype: bridged
      parent: br161
      type: nic
    root:
      path: /
      pool: local
      type: disk
  name: default
```
```
Error: Failed to update server configuration: unsupported version: ServerError: 404 Not Found (
<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>No such child resource.</p>
  </body>
</html>
)
```
This happened after an `apt update` and `apt upgrade` . I reinstalled the server using MAAS, and then didn;t do the apt update and apt upgrade and could register successfully

Later I realized that the MAAS URL was incorrect, when I added **`/MAAS`** it worked fine.  the problem was discovered after I used the yaml file in another server that was already upgradede with apt.

Maybe the request is a meaningful message if the MAAS server can't be contacted, or the URL is incorrect.

2. second error. If I try to move the container to a second node in another cluster, it gives me a MAAS error:
```
root@node14:~# lxc image copy ubuntu:b local: --copy-aliases --auto-update
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:16.04

Image copied successfully!
root@node14:~# lxc launch local:b test-161
Creating test-161
Error: {"hostname": ["Node with this Hostname already exists."]}
root@node14:~#  #### DELETED THE NODE FROM THE MAAS DNS STATIC ASSINGMENT ON ANOTHER LXD HOST.
root@node14:~# lxc launch local:b test-161
Creating test-161
Starting test-161
root@node14:~# lxc list
+----------+---------+------+------+------------+-----------+----------+
|   NAME   |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS | LOCATION |
+----------+---------+------+------+------------+-----------+----------+
| test-161 | RUNNING |      |      | PERSISTENT | 0         | node14   |
+----------+---------+------+------+------------+-----------+----------+
```
I had to manually start the bridge 
https://bugs.launchpad.net/ubuntu/+source/nplan/+bug/1736975

This is how the bridge is automatically created from MAAS deployment on the node, it is indeed an anonymous bridge. I don't want a local IP, since I just want to use it for containers

Can LXD team help, push this bug to be fixed in netplan?  Please!! 👍 

```
        br161:
            interfaces:
            - eno1.161
            parameters:
                forward-delay: 15
                stp: false
```

```
root@node14:~# ip link show br161
6: br161: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 5a:82:fb:8e:ee:82 brd ff:ff:ff:ff:ff:ff
root@node14:~# ip link set up br161
root@node14:~# ip link show br161
6: br161: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 5a:82:fb:8e:ee:82 brd ff:ff:ff:ff:ff:ff
root@node14:~# lxc start test-161
root@node14:~# lxc list
+----------+---------+---------------------+------+------------+-----------+----------+
|   NAME   |  STATE  |        IPV4         | IPV6 |    TYPE    | SNAPSHOTS | LOCATION |
+----------+---------+---------------------+------+------------+-----------+----------+
| test-161 | RUNNING | 10.30.61.242 (eth0) |      | PERSISTENT | 0         | node14   |
+----------+---------+---------------------+------+------------+-----------+----------+
```

Now.. second error, trying to move the container from one cluster to another cluster (each node an independent cluster.

```
root@node14:~# lxc move test-161 node15:
Error: Failed container creation: {"mac_addresses": ["MAC address 00:16:3e:24:68:67 already in use on test-161."], "hostname": ["Node with this Hostname already exists."]}
root@node14:~# lxc move test-161 node15:test-161-15
Error: Failed container creation: {"mac_addresses": ["MAC address 00:16:3e:24:68:67 already in use on test-161."]}
```

# Steps to reproduce

First error (lxd init)
 1. fresh cloud image install of Ubuntu 18.04, 
 2. apt update apt upgrade
 3. lxd init with the given info (do not put the /MAAS in the MAAS URL )

Second error (MAAS integration, moving containers)

1. create two LXD hosts both cluster (I used the preseed of the first on the second one, Both registered on MAAS, but not part of the same cluster.

2. create a new container in node1
3. lxc add remote node2 IP 
4. lxc move CONTAINER node2:

**Comment by stgraber** [comment]
For the first part of the issue, there's no a lot we can do. You entered a bad URL and we showed the error that we're getting from the Go MAAS API client. I agree that those errors aren't pretty but it's not our code so there's not a lot we can do there.

We can't assume that you're missing /MAAS either because there are setups (including our own test MAAS) where the URL is different (when using reverse proxies).

**Comment by stgraber** [comment]
The second issue is also not something we can fix as it's simply MAAS enforcing that there not be duplicate MAC addresses on the network and so refuses to let you copy the container.

You should be able to workaround this by passing `-c volatile.eth0.hwaddr=SOME-OTHER-MAC`, effectively causing the container copy to have a different MAC address which should then make MAAS happy.

After the move is successful and the source container gets deleted, you can then set the MAC back to the original value if you want, which may or may not result in MAAS giving you the same IP again.

**Comment by laralar** [comment]
Correct, it is a MAAS error, but maybe a nicer error, like MAAS server couldnt be reached would be nicer.

the netplan part, there is a workaround but ugly for 25 rack servers + 40 IBM blades with LXD. (Love the scripting for creating containers and executing commands in the containers, using pdsh and some custom scripts)

I experienced some instability with clusters if one went down, so I decided not to give them a try yet. that is why I am using separate clusters (one node each).  I dont have the time now.

But I am moving the container, not copying it.  I guess a copy and then delete would work, that would recreate it with a different MAC address, but I would have to use a different name

```
root@node14:~# lxc move test-161 test-161-2
root@node14:~# lxc move test-161-2 node15:
Error: Failed container creation: {"mac_addresses": ["MAC address 00:16:3e:24:68:67 already in use on test-161-2."], "hostname": ["Node with this Hostname already exists."]}
root@node14:~#
```
As you can see the first move within the same node works fine. and the name is also updated in MAAS

but the second one fails.  it is just unnatural if I want to preserve the name on a different host.  I understand that the copy mechanism is doing a temporary snapshot, copying the snapshot and then delete the information.

Can't the lxc move command do the MAC address trick ?

**Comment by laralar** [comment]
In a way, in the first command you do
1. unregister from MAAS
2. change of name with the same MAC
3. register in MAAS

on the second case you do:
1. snapshot, copy
2. register with the same MAC on MAAS --> Fails
3. delete of the original container in the original node

MAAS resgistration should be after the first container name is unregistered from MAAS as in the first move within the same node, shouldn't it?

**Comment by stgraber** [comment]
Yes, `lxc move` should work fine with `-s`, that's because there is no such thing as a "move" in the API.
The client tool actually does a copy of the container from the first server to the second and then if that worked well, asks the source server to delete the container.

The local `lxc move` is a single API call that tells LXD to rename the container, so when doing that, you never have two containers with the same MAC, MAAS simply gets told that the container changed name.

**Comment by laralar** [comment]
Sorry.. I didn't get the `-s` part .. I don't see that flag in lxc move.

Adding a temp MAC address on the move every time you are moving a container frm one node to another is not usable.  specially in large deployments where you are not using openstack/juju.  how does openstack/juju solution work for moving a container form one node to another?

Thanks for the quick response.

**Comment by stgraber** [comment]
Oops, sorry, meant `-c`, not `-s` and yeah, for some reason it's missing in `lxc move`, we'll fix that as there's no reason for it not to be allowed when moving a container between two servers (it won't work when renaming a container locally though).

**Comment by stgraber** [comment]
For now, you can do `lxc copy -c` followed by `lxc delete` of the source container, which is effectively what `lxc move` does for you internally.

**Comment by laralar** [comment]
thank you.  

I would appreciate if at some point in the long run there is a better alternative since as a feature request.  since for large deployments this is not manageable.  (although sometimes I do it, a copy and then update the MAC in case I want the same address at another node and shutting down the first one)

**Comment by stgraber** [comment]
I'm working on fixing `lxc move` now to let you override configuration that way.

For LXD allowing you to move between two unrelated systems connected to the same MAAS without needing the config trick, I don't expect this to really ever be possible. But in the case where both systems are part of a LXD cluster, it should be possible and #4546 should help with that.

**Comment by laralar** [comment]
I added the following comment on the other issue 

I found out that if I move a container that overrides the default profile where the MAAS networking information is, with its own set of eth0 networking without the MAAS information, the containers moves without a problem

```
ubuntu@node38:~$ lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    **maas.subnet.ipv4: 10.3.4.0/23**
    name: eth0
    nictype: bridged
    parent: br1
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/maas-icts
ubuntu@node38:~$ lxc profile show maas
config:
  raw.lxc: |-
    lxc.cgroup.devices.allow = c 10:237 rwm
    lxc.apparmor.profile=unconfined
    lxc.cgroup.devices.allow = b 7:* rwm
  security.privileged: "true"
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br1
    type: nic
```

Then, in theory, I can remove the MAAS networking configuration of the container in the target node, move the container without any issue, then add the container networking configuration.

Seems awkward but works. and I dont have to invent a MAC address every time I am moving a container

Still I believe this should be handled by LXD somehow at some point.  it is just not user fiendly and even tough **lxd move** command local and remote implementations are different, de behaviour should be the same

**Comment by laralar** [comment]
So not to affect other containers that are not being moved, for moving a container from one node to another node whose LXD are registered with MAAS,  Assuming that you are using default profile created with MAAS integration

The workaround thgat best suited for me is

1. Disable MAAS integration of the container by overriding eth0 with no MAAS integration (the container will be removed from MAAS DNS)
2. Move the container
3. Enable again the MAAS integration by not overriing the eth0 and using the default MAAS integrated one

Although somehow I feel that this should be done automatically and transparent for the user
lxc move c1 c2 and lxc move c1 host:c1 or lxc move c1 host:c2 should all of them have the same behaviour independently of MAAS or clustering
