### ISSUE TITLE
LXD 3.01 - Clustering - Failed container creation: no "source" property found for the storage pool

### ISSUE THREAD

**Issue by rkelleyrtp** [lxc/lxd#4629]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
config:
  core.https_address: 10.30.50.60:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.30.50.60:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFVTCCAz2gAwIBAgIQJoB2Oq2wAO9l2qWCd98wCjANBgkqhkiG9w0BAQsFADA7
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRswGQYDVQQDDBJyb290QExY
    RC0zLU1hbmFnZXIwHhcNMTgwNjA3MTkwOTQyWhcNMjgwNjA0MTkwOTQyWjA7MRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRswGQYDVQQDDBJyb290QExYRC0z
    LU1hbmFnZXIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC235WwKNJj
    Ooe3VNTgnXkRdoYMu9UykaKFfPQ1ZPwwpKTncq4RdC92xMhrpVwYKBzP0p8keNgv
    V7/IoCyxzWlg4Rccpu9/E4lWr89N/ankwsXrJjzKUyouUh++QVQaCEEkBT88PUKN
    mquIb+7JMBjcveCg1g4Yx+SdNlfDmLn5c3FJHgmnbE67uJmU8RVRyC1jeCN4irr4
    UcNaUzb6EKETQ3tzbMrdCpyL6alSJObERK4BM7KGRS9sk7XtbcsWxK7XlrrXTBpr
    hN4AehwLY66EG4wdrVyIvvwGcBnK/W0qyoDS+adPNCz+Y0jMdMlfQM1zJe38X5/7
    /P1q0Ko4mE8hd5PVg/j35IjgvTZz3+7+Hu4fmNJhC6Vuw5NmgujVEXfdS1Uwp+AZ
    IOiitAp79+0QgzIZAnDmnG5pPfXHnpBXfa0QLHuk0w+NhEs0TInlvznbcQcDsuTx
    WlVt9OXDlhTM98VFmtx+oMdMd3D2hLGwfBsSNrpZrj1SzNza3gI9icOQ+flTyfaz
    UXbG4u06w0dNdmnbHJPO+bKPinMSbhBpa9SYY3kEk0vsenJfCO5IOpMBuGmheL8J
    D/j2+HBHaxAvUX9J+fXvICLyC1FiRhqjgkuP/LOOJ42aihf+lCVv6bzvfBB7gGLL
    sJ4xCHRMDIVbvGFBBaD5A2HRwGOn2HyqaQIDAQABo1UwUzAOBgNVHQ8BAf8EBAMC
    BaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAeBgNVHREEFzAV
    gg1MWEQtMy1NYW5hZ2VyhwQKHjI8MA0GCSqGSIb3DQEBCwUAA4ICAQBn8qoEp5N6
    GzkaGHa2nDripIretpfG6qdiL9dhkUDLZ9S7v+z6Zjs74oVrf0GEBHgDprapUV1u
    Yx2wOkdrn2BJmq4JCglUv/GBBi2D5IUi5NK5Svv7KiwrjBX6F8baH6eAKcOnAI0d
    9SE6IOTOODnaddHu8GoXOb9xs1/ke8bS4Vxdi9n0RimEecc3coxF09DZpNY8H18p
    chpGEnmDXiRhpR5FhVhJXhXnD1Zmov/qZ/x4nRbapPeGu6GHpJTIF3EO0iWC/uLf
    zzyOyGMjt/tEdX1t28HwljDgVRrwwa0OXp0LXGOy8eEOQKWh3ZN4qOzst2+PO36G
    7RpSHQpjmAiyYCF5H3X5DsX8I6BfRAMM/NgoyqXQ+/FaTPmE39tMmHK51vQiCBFZ
    qUvxt2exahOtCsgXNpVrPGH6HmH2KLQptwupaxvHXq4BuSPPIUyuHE+uogOged2n
    9tKVOOsgzGT80DIRY5Hkc0auYlAITqCLyN2wEBFNEaj4Z/0xJbwE9NNmDrXxeuHQ
    bB4lLTWW6uc1cvI8y+5gRBIT3HOS/guRqZ54ehOZonhA4NfES7hllJHQpBWfS1r4
    aBzQlDlck8Q4qVe9WaYYmaifvAeBazRz1mqnU2BEhPpA6mGmPjs74ZqxFHGfUpSZ
    PGtGFemMGxwhuuHAeQBDzruM1kWzcWKssg==
    -----END CERTIFICATE-----
  certificate_fingerprint: ba6c919bc7a5b8a249075487790abca2c3c148b5a5a139d2c1848f0b0817a94c
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-22-generic
  server: lxd
  server_pid: 808
  server_version: "3.1"
  storage: dir
  storage_version: "1"
  server_clustered: true
  server_name: LXD-3-Manager

# Issue description
After adding a second node to a cluster using a local "dir" storage pool, the new server fails to properly create the container.  However, the storage pool shows the new container.

```
root@LXD-Server1:/var/snap/lxd/common/lxd/storage-pools/BTRFS# lxc storage volume list BTRFS
+-----------+------+-------------+---------+---------------+
|   TYPE    | NAME | DESCRIPTION | USED BY |   LOCATION    |
+-----------+------+-------------+---------+---------------+
| container | c2   |             | 1       | LXD-Server1   |
+-----------+------+-------------+---------+---------------+
| container | c99  |             | 1       | LXD-3-Manager |
+-----------+------+-------------+---------+---------------+
| container | c99  |             | 1       | LXD-Server1   |
+-----------+------+-------------+---------+---------------+

```

```
root@LXD-Server1:/var/snap/lxd/common/lxd/storage-pools/BTRFS# lxc list
+------+---------+-------------------+------+------------+-----------+---------------+
| NAME |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |   LOCATION    |
+------+---------+-------------------+------+------------+-----------+---------------+
| c99  | RUNNING | 240.60.0.9 (eth0) |      | PERSISTENT | 0         | LXD-3-Manager |
+------+---------+-------------------+------+------------+-----------+---------------+

```

# Steps to reproduce

 * Install U18.04 on a fresh machine with two disks (boot and storage) - call it "Manager"

 * Remove LXD and re-install via latest snap (LXD 3.01)

 * Setup LXD in cluster mode as cluster master - take all defaults

 * Create new BTRFS filesystem on /dev/sdb (second drive)

 * Add a new storage pool via "lxc storage create BTRFS dir" - use /var/snap/lxd/common/lxd/storage-pools/BTRFS as the target directory

 * Mount /dev/sdb to /var/snap/lxd/common/lxd/storage-pools/BTRFS and run "lxd storage list"

```
    root@LXD-3-Manager:~# lxc storage list
    +-------+-------------+--------+---------+---------+
    | NAME  | DESCRIPTION | DRIVER |  STATE  | USED BY |
    +-------+-------------+--------+---------+---------+
    | local |             | dir    | CREATED | 2       |
    +-------+-------------+--------+---------+---------+
    | BTRFS |             | dir    | CREATED | 2       |
    +-------+-------------+--------+---------+---------+

```

  * Edit the default profile and change the pool name from "local" to "BTRFS"

  * Remove the local storage pool so as to have only a single BTRFS storage pool available:  "lxc storage delete local" and list the pool again

```
    root@LXD-3-Manager:~# lxc storage list
    +-------+-------------+--------+---------+---------+
    | NAME  | DESCRIPTION | DRIVER |  STATE  | USED BY |
    +-------+-------------+--------+---------+---------+
    | BTRFS |             | dir    | CREATED | 2       |
    +-------+-------------+--------+---------+---------+

```

  * Spin up an identical U18.04 server (Server1) and add it to the cluster
     --> Create a new BTRFS filesystem on /dev/sdb
     --> During the cluster setup, specify the directory "/var/snap/lxd/common/lxd/storage-pools/BTRFS" for the BTRFS pool id

  * Create a new container on Manager - specify BTRFS storage pool

  * Create a new container on Server1 - specify BTRFS storage pool (lxc launch Ubuntu:18.04 --storage BTRFS --target Server1

    ------------------------------
```
    lxc launch ubuntu:16.04 c2
    Creating c2
    Error: Failed container creation: no "source" property found for the storage pool

```    ------------------------------


# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Can you show `lxc storage show BTRFS` and `lxd sql "SELECT * FROM storage_pools_config;"`?

**Comment by rkelleyrtp** [comment]
```
root@LXD-3-Manager:/var/snap/lxd/common/lxd/storage-pools/BTRFS/containers# lxc storage show BTRFS
config: {}
description: ""
name: BTRFS
driver: dir
used_by:
- /1.0/profiles/default
status: Created
locations:
- LXD-3-Manager
- LXD-Server1
```

Unfortunately, the lxd sql command keeps giving me a syntax error:

```
root@LXD-3-Manager:/var/snap/lxd/common/lxd/storage-pools/BTRFS/containers# lxd sql "SELECT * FROM storage_pools_config;"
Description:
  Execute a SQL query against the LXD local or global database

  The local database is specific to the LXD cluster member you target the
  command to, and contains member-specific data (such as the member network
  address).

  The global database is common to all LXD members in the cluster, and contains
  cluster-specific data (such as profiles, containers, etc).

  If you are running a non-clustered LXD instance, the same applies, as that
  instance is effectively a single-member cluster.

  If <query> is the special value "-", then the query is read from
  standard input.

  If <query> is the special value ".dump", the the command returns a SQL text
  dump of the given database.

  If <query> is the special value ".schema", the the command returns the SQL
  text schema of the given database.

  This internal command is mostly useful for debugging and disaster
  recovery. The LXD team will occasionally provide hotfixes to users as a
  set of database queries to fix some data inconsistency.

  This command targets the global LXD database and works in both local
  and cluster mode.

Usage:
  lxd sql <local|global> <query> [flags]

Global Flags:
  -d, --debug     Show all debug messages
  -h, --help      Print help
      --logfile   Path to the log file
      --trace     Log tracing targets
  -v, --verbose   Show all information messages
      --version   Print version number
Error: Missing required arguments

```

**Comment by stgraber** [comment]
Oops, sorry, `lxd sql global "SELECT * FROM storage_pools_config;"`

**Comment by rkelleyrtp** [comment]
```
root@LXD-3-Manager:/var/snap/lxd/common/lxd/storage-pools/BTRFS/containers# lxd sql global "SELECT * FROM storage_pools_config;"
+----+-----------------+---------+--------+----------------------------------------------+
| id | storage_pool_id | node_id |  key   |                    value                     |
+----+-----------------+---------+--------+----------------------------------------------+
| 3  | 3               | 1       | source | /var/snap/lxd/common/lxd/storage-pools/BTRFS |
+----+-----------------+---------+--------+----------------------------------------------+
```

**Comment by stgraber** [comment]
Ok, so the problem is that for some reason the source is missing for a bunch of your nodes...

`lxd sql global "SELECT * FROM nodes;"`

**Comment by stgraber** [comment]
@freeekanayaka you'll want to take a look at this

**Comment by rkelleyrtp** [comment]
```
root@LXD-3-Manager:/var/snap/lxd/common/lxd/storage-pools/BTRFS/containers# lxd sql global "SELECT * FROM nodes;"
+----+---------------+-------------+------------------+--------+----------------+----------------------+---------+
| id |     name      | description |     address      | schema | api_extensions |      heartbeat       | pending |
+----+---------------+-------------+------------------+--------+----------------+----------------------+---------+
| 1  | LXD-3-Manager |             | 10.30.50.60:8443 | 8      | 83             | 2018-06-07T21:01:17Z | 0       |
| 2  | LXD-Server1   |             | 10.30.50.61:8443 | 8      | 83             | 2018-06-07T21:01:17Z | 0       |
+----+---------------+-------------+------------------+--------+----------------+----------------------+---------+
```

**Comment by stgraber** [comment]
Ok, cool, so your second node is missing the source property, to unblock your setup, you should be able to do:

```
lxd sql global "INSERT INTO storage_pools_config (storage_pool_id, node_id, key, value) VALUES (3, 2, 'source', '/var/snap/lxd/common/lxd/storage-pools/BTRFS');"
```

**Comment by stgraber** [comment]
At which point, that error should go away and things will hopefully work as expected.

**Comment by rkelleyrtp** [comment]
```
root@LXD-3-Manager:/var/snap/lxd/common/lxd/storage-pools/BTRFS/containers# lxd sql global "INSERT INTO storage_pools_config (storage_pool_id, node_id, key, value) VALUES (3, 2, 'source', '/var/snap/lxd/common/lxd/storage-pools/BTRFS');"
Rows affected: 1

```

```
root@LXD-3-Manager:/var/snap/lxd/common/lxd/storage-pools/BTRFS/containers# lxd sql global "SELECT * FROM storage_pools_config;"
+----+-----------------+---------+--------+----------------------------------------------+
| id | storage_pool_id | node_id |  key   |                    value                     |
+----+-----------------+---------+--------+----------------------------------------------+
| 3  | 3               | 1       | source | /var/snap/lxd/common/lxd/storage-pools/BTRFS |
| 4  | 3               | 2       | source | /var/snap/lxd/common/lxd/storage-pools/BTRFS |
+----+-----------------+---------+--------+----------------------------------------------+

```
Thanks.  So the question is, why did this happen?  I suspect it was part of removing the default (local) storage pool and adding a new one.  Seems like this would be a standard test case.

**Comment by stgraber** [comment]
Yeah, would be interesting to repeat your steps but dump the content of `storage_pools_config` every step of the way to confirm that the initial setup was correct and then see when the row gets dropped.

If you have spare systems to do this, that'd be great, otherwise, @freeekanayaka should be able to do that on our end (or may just know what's going on without needing to see it happen).

**Comment by rkelleyrtp** [comment]
I might have found the root cause.  After setting up the primary LXD cluster server and adding the new local dir as a storage pool, I added the second node.  During the "lxd init" command on the second node, I am prompted with "Choose the local disk..." option.  During the first run, I selected "/dev/sdb" thinking LXD would automatically create a new BTRFS filesystem on /dev/sdb and mount it for me.  Unfortunately, that command failed:


```
root@LXD-Server1:~# lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: yes
What name should be used to identify this node in the cluster? [default=LXD-Server1]:
What IP address or DNS name should be used to reach this node? [default=10.30.50.61]:
Are you joining an existing cluster? (yes/no) [default=no]: yes
IP address or FQDN of an existing cluster node: 10.30.50.60
Cluster fingerprint: ba6c919bc7a5b8a249075487790abca2c3c148b5a5a139d2c1848f0b0817a94c
You can validate this fingerpring by running "lxc info" locally on an existing node.
Is this the correct fingerprint? (yes/no) [default=no]: yes
Cluster trust password:
All existing data is lost when joining a cluster, continue? (yes/no) [default=no] yes
Choose the local disk or dataset for storage pool "BTRFS" (empty for loop disk): /dev/sdb
Choose the local disk or dataset for storage pool "local" (empty for loop disk):
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]:
Error: Failed to create storage pool 'BTRFS': readdirent: not a directory
```
Next, I re-ran the command but used the absolute path for the "local disk" for the BTRFS storage pool:
```
root@LXD-Server1:~# lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: yes
What name should be used to identify this node in the cluster? [default=LXD-Server1]:
What IP address or DNS name should be used to reach this node? [default=10.30.50.61]:
Are you joining an existing cluster? (yes/no) [default=no]: yes
IP address or FQDN of an existing cluster node: 10.30.50.60
Cluster fingerprint: ba6c919bc7a5b8a249075487790abca2c3c148b5a5a139d2c1848f0b0817a94c
You can validate this fingerpring by running "lxc info" locally on an existing node.
Is this the correct fingerprint? (yes/no) [default=no]: yes
Cluster trust password:
All existing data is lost when joining a cluster, continue? (yes/no) [default=no] yes
Choose the local disk or dataset for storage pool "BTRFS" (empty for loop disk): /var/snap/lxd/common/lxd/storage-pools/BTRFS
Choose the local disk or dataset for storage pool "local" (empty for loop disk):
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]:
```

This is successful but definitely causes problems later.

A suggestion is to re-word the "Choose the local disk" prompt so it make more sense and avoid this problem.

**Comment by stgraber** [comment]
Well, actually, setting /dev/sdb should have worked fine, I wonder why that one didn't work.

**Comment by stgraber** [comment]
And in any case, it shouldn't then cause a subsequent init to fail weirdly.
