### ISSUE TITLE
LXD integration with MAAS deadlock?

### ISSUE THREAD

**Issue by laralar** [lxc/lxd#4636]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 3.0.0, or 3.1
   * LXD version: 3.0.0 or 3.1
   * Storage backend in use: btrfs/zfs

# Issue description
I'm doing some funny things, I want to install MAAS, and LXD together in the same host. Preferably, I want to install MAAS in a container (snapshots) and register the host with MAAS, so that I can see other containers in the Machine/Containers tab.

Is it possible for LXD to startup in a MAAS-disconnected state and bring up the MAAS registered containers? then, when MAAS container comes online, LXD can connect/register to MAAS and update the changed info.

Is it possible to register a LXD server in MAAS host?  If Install MAAS on a container, and then register the LXD host with MAAS, there is a deadlock on reboot.  LXD tries to init and connect to MAAS, but it can't find the MAAS server, since it is self contained in a container in the same host.  

Ok.. understood the deadlock, none is going to come up, or can maybe LXD come with MAAS connectivity offline, and when it is reachable, update the status?

Now. if instead of installing MAAS on a container, I install it on the parent host, the when I try to register LXD with MAAS, it gives an error, node not found, Of course, the node is not a "Machine" but the rack/region controller itself.

How can I see the containers inside a host if it is the MAAS host? or how can MAAS container and LXD come online without a connection to the MAAS server?

The alternative would be to install MAAS in a non-LXD container/VM environment, e.g. KVM, wait for the VM to come online, the LXD can come online.  I don't want to have a dedicated MAAS host to maximize resources.

# Steps to reproduce

 1. Install MAAS on bare metal
 2. lxd init using the same node as MAAS host.
```
root@node11:~# lxd init
Would you like to use LXD clustering? (yes/no) [default=no]:
Do you want to configure a new storage pool? (yes/no) [default=yes]:
Name of the new storage pool [default=default]:
Name of the storage backend to use (btrfs, ceph, dir, lvm, zfs) [default=zfs]:
Create a new ZFS pool? (yes/no) [default=yes]: no
Name of the existing ZFS pool or dataset: zfs/default
Would you like to connect to a MAAS server? (yes/no) [default=no]: yes
What's the name of this host in MAAS? [default=node11]:
URL of your MAAS server (e.g. http://1.2.3.4:5240/MAAS): http://10.3.4.11:5240/MAAS/
API key for your MAAS server: BFm69fTfdH4WvRrLAT:Yf68Np4TEAxgw8HFV8:Pqkje34ELFjLVWtPah7K2ZEyPXE2EzbH
Would you like to create a new local network bridge? (yes/no) [default=yes]: no
Would you like to configure LXD to use an existing bridge or host interface? (yes/no) [default=no]: yes
Name of the existing bridge or host interface: br1
Is this interface connected to your MAAS server? (yes/no) [default=yes]:
MAAS IPv4 subnet name for this interface (empty for no subnet): 10.3.4.0/23
MAAS IPv6 subnet name for this interface (empty for no subnet):
Would you like LXD to be available over the network? (yes/no) [default=no]: yes
Address to bind LXD to (not including port) [default=all]:
Port to bind LXD to [default=8443]:
Trust password for new clients:
Again:
Would you like stale cached images to be updated automatically? (yes/no) [default=yes]
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: yes
config:
  core.https_address: '[::]:8443'
  core.trust_password: A1BL@dm
  maas.api.key: BFm69fTfdH4WvRrLAT:Yf68Np4TEAxgw8HFV8:Pqkje34ELFjLVWtPah7K2ZEyPXE2EzbH
  maas.api.url: http://10.3.4.11:5240/MAAS/
cluster: null
networks: []
storage_pools:
- config:
    source: zfs/default
  description: ""
  name: default
  driver: zfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      maas.subnet.ipv4: 10.3.4.0/23
      name: eth0
      nictype: bridged
      parent: br1
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default

**Error: Failed to update server configuration: Couldn't find the specified machine: node11**

`### OF COURSE, node11 is the region controller @ MAAS, not a node, and I can't register as a Machine since the MAC ADDRESS is already there error is given in MAAS`

root@node11:~# ip a show br1
13: br1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether d6:d5:30:f2:57:b6 brd ff:ff:ff:ff:ff:ff
    inet 10.3.4.11/23 brd 10.3.5.255 scope global br1
       valid_lft forever preferred_lft forever
    inet6 fe80::d4d5:30ff:fef2:57b6/64 scope link
       valid_lft forever preferred_lft forever
root@node11:~#
```

Second option:
1. Install a plain host HOST1.
2. create a container, install MAAS region controller in the container
3. move the container to another host HOST2
4. reinstall the original host HOST1 using MAAS deployment
5. move back the container from HOST2 to HOST1
6. reboot

**LXD doesn't come up**

```
root@node11:~# lxd init
Would you like to use LXD clustering? (yes/no) [default=no]:
Do you want to configure a new storage pool? (yes/no) [default=yes]:
Name of the new storage pool [default=default]:
Name of the storage backend to use (btrfs, ceph, dir, lvm, zfs) [default=zfs]: ^C
root@node11:~# lxd init
Would you like to use LXD clustering? (yes/no) [default=no]:
Do you want to configure a new storage pool? (yes/no) [default=yes]:
Name of the new storage pool [default=default]:
Name of the storage backend to use (btrfs, ceph, dir, lvm, zfs) [default=zfs]:
Create a new ZFS pool? (yes/no) [default=yes]: no
Name of the existing ZFS pool or dataset: zpool/default
Would you like to connect to a MAAS server? (yes/no) [default=no]:
Would you like to create a new local network bridge? (yes/no) [default=yes]: no
Would you like to configure LXD to use an existing bridge or host interface? (yes/no) [default=no]: yes
Name of the existing bridge or host interface: br1
Would you like LXD to be available over the network? (yes/no) [default=no]: yes
Address to bind LXD to (not including port) [default=all]:
Port to bind LXD to [default=8443]:
Trust password for new clients:
Again:
Would you like stale cached images to be updated automatically? (yes/no) [default=yes]
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: yes
config:
  core.https_address: '[::]:8443'
  core.trust_password: A1BL@dm
cluster: null
networks: []
storage_pools:
- config:
    source: zpool/default
  description: ""
  name: default
  driver: zfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: br1
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default

root@node11:~# lxc image copy ubuntu:b local: --copy-aliases --auto-update
```
```
root@node11:~# lxd init
Would you like to use LXD clustering? (yes/no) [default=no]:
Do you want to configure a new storage pool? (yes/no) [default=yes]:
Name of the new storage pool [default=default]:
Name of the storage backend to use (btrfs, ceph, dir, lvm, zfs) [default=zfs]: ^C
root@node11:~# lxd init
Would you like to use LXD clustering? (yes/no) [default=no]:
Do you want to configure a new storage pool? (yes/no) [default=yes]:
Name of the new storage pool [default=default]:
Name of the storage backend to use (btrfs, ceph, dir, lvm, zfs) [default=zfs]:
Create a new ZFS pool? (yes/no) [default=yes]: no
Name of the existing ZFS pool or dataset: zpool/default
Would you like to connect to a MAAS server? (yes/no) [default=no]:
Would you like to create a new local network bridge? (yes/no) [default=yes]: no
Would you like to configure LXD to use an existing bridge or host interface? (yes/no) [default=no]: yes
Name of the existing bridge or host interface: br1
Would you like LXD to be available over the network? (yes/no) [default=no]: yes
Address to bind LXD to (not including port) [default=all]:
Port to bind LXD to [default=8443]:
Trust password for new clients:
Again:
Would you like stale cached images to be updated automatically? (yes/no) [default=yes]
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: yes
config:
  core.https_address: '[::]:8443'
  core.trust_password: A1BL@dm
cluster: null
networks: []
storage_pools:
- config:
    source: zpool/default
  description: ""
  name: default
  driver: zfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: br1
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default

root@node11:~# lxc remote add node20^C
root@node11:~# lxc image copy ubuntu:b local: --copy-aliases --auto-update
Image copied successfully!
root@node11:~# lxc launch local:b maas
Creating maas
Starting maas
root@node11:~# lxc exec maas^C
root@node11:~# lxc file push /etc/apt/apt.conf.d/90curtin-aptproxy maas/etc/apt/apt.conf
root@node11:~# lxc exec maas apt update
root@node11:~# lxc exec maas -- apt install maas -y
root@node11:~# lxc stop maas
root@node11:~# lxc move maas host2:

### THEN reinstall the host with MAAS deploy, execute lxd init using this MAAS container in host2

root@node11:~# lxc stop host2:maas 
root@node11:~# lxc move host2:maas local:
root@node11:~# lxc config set maas boot.autostart true
root@node11:~# reboot

LXD doesnt come up




```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by laralar** [comment]
This is the error that I am getting if MAAS server is not UP when LXD service is starting.  it is a repetitive error, now with snap lxd 3.1 and the service doesnt start
```
lvl=info msg="Initializing global database" t=2018-06-11T20:08:20+0000
lvl=info msg="Initializing storage pools" t=2018-06-11T20:08:20+0000
lvl=info msg="Initializing networks" t=2018-06-11T20:08:20+0000
lvl=info msg="Loading configuration" t=2018-06-11T20:08:20+0000
lvl=eror msg="Failed to start the daemon: Get http://10.3.4.10:5240/MAAS/api/2.0/version/: dial tcp 10.3.4.10:5240: connect: no route to host" t=2018-06-11T20:08:22+0000
lvl=info msg="Starting shutdown sequence" t=2018-06-11T20:08:22+0000
lvl=info msg="Stopping REST API handler:" t=2018-06-11T20:08:22+0000
lvl=info msg=" - closing socket" socket=[::]:8443 t=2018-06-11T20:08:22+0000
lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/unix.socket t=2018-06-11T20:08:22+0000
lvl=info msg="Stopping /dev/lxd handler" t=2018-06-11T20:08:22+0000
lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/devlxd/sock t=2018-06-11T20:08:22+0000
lvl=info msg="Closing the database" t=2018-06-11T20:08:22+0000

```

**Comment by stgraber** [comment]
Yeah, we need to reshuffle that logic a bit so that LXD can come up without MAAS but will refuse to create or modify any container until MAAS is reachable.

**Comment by laralar** [comment]
Will the containers come up?

Is it worth, does it make any sense to have a MAAS within the same LXD environment?, so that when everything comes up the read-only state is finished?

**Comment by laralar** [comment]
Is it possible to have two LXD instances running on the same host? one with MAAS contaner that will come up with no issues, and a second one that will be registered on MAAS and will wait until that MAAS first instance comes up.

**Comment by stgraber** [comment]
LXD doesn't talk to MAAS when starting up containers, so yes, containers would start just fine once we fix that logic.

You can run two LXD instances on the same machine, but they can't share storage pools or networks and it gets very confusing as to which LXD instance you're talking with the various tools... I wouldn't recommend it :)

**Comment by laralar** [comment]
Fair enough.   Thank you.. I can set the default MAAS connectivity in the default profile, and that can be override in the container itself specifying the eth0 device without MAAS connectivity. so that the MAAS container is not registered with itself. 

There is a MAAS bug that MAAS assigns an (Auto) Static IP address, and if the container doesn't use DHCP, but used a Static IP address itself, it can't be modified in MAAS.  Therefore, 1. You can't assign a static IP to a container in MAAS, and 2. If you do so in the container, MAAS, and the DNS provides a different IP address than the one assigned.  The workaround so far is to override the eth0 device in the container itself so that statically assigned IP addresses containers don't connect with MAAS, and manually create a device in MAAS with the container in question and the respective static IP address.

Where can this issue be filed?

**Comment by stgraber** [comment]
MAAS bugs can be filed at https://launchpad.net/maas

For the static network config case, when combined with LXD, an option is to override `eth0` and set `ipv4.address` and `ipv6.address` to the static address you want. This will have MAAS reserve that address and set DNS for you at least.

**Comment by laralar** [comment]
It worked great. Thanks

**Comment by laralar** [comment]
Is there a way that we can specify alias and multiple ip addresses? e.g. eth0:ALIAS

**Comment by stgraber** [comment]
I don't remember the MAAS device address assignment API allowing us to specify more than one IP for a given MAC address. I know it's doable for machines in MAAS, but containers are treated as different objects.

My recommendation would be to just attach a second device (`eth1`) to the container instead. That should work fine with MAAS (because of the separate MAC) and shouldn't make any performance difference.

**Comment by stgraber** [comment]
Looking into that one now.

**Comment by laralar** [comment]
I submitted the bug @ MAAS
https://bugs.launchpad.net/maas/+bug/1776056

However, it seems that from MAAS perspective editing should be done in LXD/Juju. Fine.  The only drawback that I have right now is that in MAAS, I can't easily find in which LXD Node a container is located, I have to go one by one to see where "c1" is.  Let's say I have 40 LXD nodes, thus making it a bit painful if I dont remember.

**Comment by stgraber** [comment]
When using LXD clustering, the containers will show in MAAS against the node they're currently on.

I agree that having some way to see all containers in MAAS or to search for them would be quite nice.

**Comment by laralar** [comment]
I checked with 3.2 and LXD is coming up and a container within is also coming UP.  now I didn't test with MAAS container being in the same host. e.g. LXD host registering on MAAS container within. but as LXD is coming up and underneath containers are coming up I guess once LXD comes up the MAAS container will come up and LXD will get "online" to perform things such as creating a new container

I can't create a new container if MAAS connectivity is down, which I assume is what we want and the correct intended behavior?

but basically now on 3.2 you can install a MAAS on a container, deploy a new host using MAAS, move MAAS container to that new host, and resintall/deploy the original host using MAAS. which was the intention of this bug.

Thanks

**Comment by stgraber** [comment]
Indeed, the new behavior is that only operations that actually require MAAS will fail until MAAS is back online. When MAAS isn't reachable at startup time, LXD setups a background routine that attempts to connect every minute, so about a minute after your MAAS container is online, the rest of the LXD API should work fine.

**Comment by laralar** [comment]
verified.  maas as a container within the same lxd host starts and after a minute of so operations are working.
