### ISSUE TITLE
Error: The source server isn't listening on the network

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#4638]
# Required information

 * Distribution: **Ubuntu**
 * Distribution version: **18.04**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.15.0-22-generic**
   * LXC version: **3.0**
   * LXD version: **3.0**
   * Storage backend in use: **ZFS**

# Issue description

When i try to publish a container as an image to a remote repository using:

> lxc image  copy container repository:

I get the following output:

> **Error: The source server isn't listening on the network**

The same happens when i try to do an image copy to a remote repository using: 

> lxc image copy container repository: --copy-aliases

I get the same error message. 

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
That's because your source server isn't listening on the network :)

As the target server downloads from the source, you need to have core.listen_address set on the source server and have that address be reachable by the target server.

**Comment by elbrinke** [comment]
The config is currently set as: 

> lxc config set core.https_address "[::]:8443"

**Comment by stgraber** [comment]
What does `lxc info` and `lxc info repository:` show you?

Also, try running the `lxc image copy` with `--debug`

**Comment by elbrinke** [comment]
Changing this to: 

> lxc config set core.https_address "[::]:8443"

worked for `lxc image copy` but not for `lxc publish`.

When i run: `lxc publish container repository: --alias hahahaha` , it does not public it to the remote repo.

**Comment by stgraber** [comment]
What does `lxc publish` say? does it show an error? Can you post its output when run with `--debug`?

**Comment by elbrinke** [comment]
It's trying to publish the container to the local image repo, not the remote one.

**Comment by elbrinke** [comment]
It still shows this: 

> 		"config": {
> 			"core.https_address": "[::]:8443",
> 			"core.trust_password": true
> 		},
>

**Comment by stgraber** [comment]
That part's normal, it should publish to the local image store without setting an alias, then copy the image from the local image store to the remote image store, set the alias there and then remove the image from the local image store.
