### ISSUE TITLE
docker-ce inside lxd error with hortonworks hds sandpit

### ISSUE THREAD

**Issue by jonoinnz** [lxc/lxd#4641]
Hi Guys

# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 LTS
 * The output of "lxc info" or if that fails:
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFiDCCA3CgAwIBAgIQKebdqiIZO3XCo8KKnQHH+TANBgkqhkiG9w0BAQsFADBA
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMSAwHgYDVQQDDBdyb290QGpv
    bmF0aGFuLW9sZGxhcHRvcDAeFw0xODA1MDIyMTUzNTdaFw0yODA0MjkyMTUzNTda
    MEAxHDAaBgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxIDAeBgNVBAMMF3Jvb3RA
    am9uYXRoYW4tb2xkbGFwdG9wMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
    AgEA1dIf8CxoOmtOk1EJLHXyBWZEyT4LEr+kuY+8+yDgLxLK+WbUPlO6F/5N3Mth
    pb8lYpQh/qdz90xo79AlqrGqxslVTHNUEM2wfz33wTdppdcBB7N5a72Utx+mA4c2
    F6bFWXqjBpT7qXz/0dQDQq194IyAYv+y8CZaxwBu4zCd19hwBZvVlB+iFSCa9LHD
    pkT22rgnfwFBqRlow0VMEu4WHHidxYd4zEWSTGjQSEMbpmmfdEjSzpG30DdgcKfA
    9lEzq1ODuYwwV07aJtjCAt5Q0YzJCsgz/Draz4lYYskN6D4bhrCPREtd4jmPGGkU
    Ntc085dhGBaLs42fNbbnA9k8x6R68Kj23HrNGbqqbSTwYG6vzOduRSMvN7e8S+EJ
    FcV7ybeaQJhkC6ykgKpR89mEIxAYbXvc8qFP+4v2ubNgiT2dlppQLY6XoGJLJwaH
    AvPG36hfnZB1n550hG10ohOL3YLEpVSe1MSdQr1c/NH6JSBwNoLaxMXa7U645yrQ
    VzaRRPt1MJS3XpWT5/LZEey/bn2dkIByd/kUUyTgB44nvJ5NrveUSANsYDqgAoHu
    cgyeFS+CxK94NuPi5lYphPPnH1SYYmZkoXp4UPu1hUi7zELIqNOHtuSEDttWdiy+
    Z34kIm40N+/2zaxxQlfCvresaLMzVWPaywj32Qfg5TG+jksCAwEAAaN+MHwwDgYD
    VR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAw
    RwYDVR0RBEAwPoISam9uYXRoYW4tb2xkbGFwdG9whwTAqAF7hxD9+COybvHtAEE4
    /0f0CJaXhxD9+COybvHtADY8awcHqE/RMA0GCSqGSIb3DQEBCwUAA4ICAQCinKDl
    YVevM4Y+maVLGZmwX53A/G+R0vpM4m2kqdvADrd7TEzsrTF8pnJg4V1OPiOYkV42
    z+yDfmzakQgmn7WsE+F3vrK7B1fFjOHf1V9l0CZwwo0iVrgOKiiNmupd5L/RG/Sl
    LgteY+H5+ysBH0YhBN4DQViJMZ8aGrbhkgZYb8DsRPBbGSuFLpedzjrfmHtaoHl8
    XXCn2E9lxHwK8UMxl86buyCUGU+5ByzHYqNRtpnsdwADBEgwHgW1a5LmA5WISMIm
    MFAYW1C7CxH6fR1DJgUquJ5tAmJk3psC2i+19h9Ws16igwzTOp1em5gSV3tcW/w2
    EcZFKGpIhV6b5PVA/c41m/GNbpSE01q0A6DjVnBHG1dLIkHAObgkLh5IQ2l4kOps
    2ov8yX4U9pRh6DKr84QybWIZrhHSgHTsOQZzLfLDmhiUcJ8SWw/2ouZ8ovN1BWgL
    WZXnit0aRC5R52MqDuOgaz2CmZjWOKTebeZmhFbXk8HaqHou1UOZzUzamoXF5MXq
    cCz6+QFJuIqwuEpOCgyoy2CwxJw1JI0kvvPCjfdKt7nq2OHou31k/K7Vj5xkTmP7
    f4Q8iMqAXNix4iuABkCCYYwzmJIh8Qf1xC/V64R7O5pw8ZtsNh0HpEDQRL1wxh52
    2pedbfiT7CRznhcQa06+LC0X8CFUGvMe2vbYdg==
    -----END CERTIFICATE-----
  certificate_fingerprint: 0a6c47bb1288bdfdff9c42c70953f4c87a170830c38766ced037248cdd11fd09
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-22-generic
  server: lxd
  server_pid: 9083
  server_version: "3.1"
  storage: zfs
  storage_version: 0.7.5-1ubuntu13
  server_clustered: false
  server_name: jonathan-oldlaptop

# Issue description

I've been trying to install hortownworks hds inside a machine container, but I've been having issues getting the docker-ce container running inside the machine container:

https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/

lxc launch ubuntu:16.04 mcon-hortondf-01
lxc config set mcon-hortondf-01 security.privileged true
lxc config set mcon-hortondf-01 security.nesting true

# Steps to reproduce

1. Inside the container
lxc exec mcon-hortondf-01 bash
root@mcon-hortondf-01:~#apt-get update
root@mcon-hortondf-01:~#apt-get install     apt-transport-https     ca-certificates     curl     software-properties-common
root@mcon-hortondf-01:~#curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
root@mcon-hortondf-01:~#apt-key fingerprint 0EBFCD88
root@mcon-hortondf-01:~#add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
root@mcon-hortondf-01:~#apt update
root@mcon-hortondf-01:~#apt-get install docker-ce
root@mcon-hortondf-01:~# docker pull hortonworks/sandbox-hdf-standalone:3.1.0
3.1.0: Pulling from hortonworks/sandbox-hdf-standalone
af4b0a2388c6: Pull complete 
675d35f85bb2: Pull complete 
27e31c0c280a: Pull complete 
2448aa388819: Pull complete 
53ec16bab5a7: Pull complete 
8bb8693c9b5a: Pull complete 
bfbf229786bf: Pull complete 
b941e74db329: Pull complete 
2e285084a638: Pull complete 
ebfd4ac2f867: Pull complete 
6b67a9ac83ba: Pull complete 
e32f5618a5d9: Pull complete 
fbb8019806f0: Pull complete 
70ec8613e975: Pull complete 
a65ffb634a1c: Pull complete 
2143633a21e4: Pull complete 
c06d2927711b: Pull complete 
39cdb5c4cd18: Pull complete 
c8d583c9fab3: Pull complete 
8f13285986b3: Pull complete 
44805fa8fb11: Pull complete 
c059064b786c: Pull complete 
Digest: sha256:f80bb739a4c51c7f4709d22e114a677197e7df5ed790e46fdbd8d3ce3cc15327
Status: Downloaded newer image for hortonworks/sandbox-hdf-standalone:3.1.0
root@mcon-hortondf-01:~# docker run --privileged --name sandbox-hdf-standalone -h sandbox-hdf.hortonworks.com -itd -p 1080:1080 -p 2181:2181 -p 4200:4200 -p 4557:4557 -p 6080:6080 -p 6627:6627 -p 6667:6667 -p 7777:7777 -p 7788:7788 -p 8000:8000 -p 8080:8080 -p 8081:8081 -p 8088:8088 -p 8090:8090 -p 8744:8744 -p 8886:8886 -p 9088:9088 -p 9089:9089 -p 9090:9090 -p 9091:9091 -p 9995:9995 -p 16010:16010 -p 19888:19888 -p 50070:50070 -p 61080:61080 -p 61888:61888 -p 15500-15510:15500-15510 -p 2222:22 hortonworks/sandbox-hdf-standalone:3.1.0
0d439937d8d0a364e6df773b14ac83095ebd4b720b1459c778f06724aede03de
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/cb9c1a441da604f7c34c3f71d178d08ef154fc7d0890d7c1d24bd194b65c0079\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
Sat Jun  9 23:44:38 2018] audit: type=1400 audit(1528845498.135:556): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-mcon-hortondf-01_</var/snap/lxd/common/lxd>" pid=8808 comm="apparmor_parser"
[Sat Jun  9 23:45:58 2018] audit: type=1400 audit(1528845578.080:557): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-mcon-hortondf-01_</var/snap/lxd/common/lxd>" pid=9732 comm="apparmor_parser"
[Sat Jun  9 23:45:59 2018] audit: type=1400 audit(1528845578.744:558): apparmor="STATUS" operation="profile_load" label="lxd-mcon-hortondf-01_</var/snap/lxd/common/lxd>//&:lxd-mcon-hortondf-01_<var-snap-lxd-common-lxd>:unconfined" name="/usr/bin/lxc-start" pid=10136 comm="apparmor_parser"
[Sat Jun  9 23:45:59 2018] audit: type=1400 audit(1528845578.748:559): apparmor="STATUS" operation="profile_load" label="lxd-mcon-hortondf-01_</var/snap/lxd/common/lxd>//&:lxd-mcon-hortondf-01_<var-snap-lxd-common-lxd>:unconfined" name="lxc-container-default" pid=10134 comm="apparmor_parser"
[Sat Jun  9 23:45:59 2018] audit: type=1400 audit(1528845578.748:560): apparmor="STATUS" operation="profile_load" label="lxd-mcon-hortondf-01_</var/snap/lxd/common/lxd>//&:lxd-mcon-hortondf-01_<var-snap-lxd-common-lxd>:unconfined" name="lxc-container-default-cgns" pid=10134 comm="apparmor_parser"
[Sat Jun  9 23:45:59 2018] audit: type=1400 audit(1528845578.748:561): apparmor="STATUS" operation="profile_load" label="lxd-mcon-hortondf-01_</var/snap/lxd/common/lxd>//&:lxd-mcon-hortondf-01_<var-snap-lxd-common-lxd>:unconfined" name="lxc-container-default-with-mounting" pid=10134 comm="apparmor_parser"
[Sat Jun  9 23:45:59 2018] audit: type=1400 audit(1528845578.748:562): apparmor="STATUS" operation="profile_load" label="lxd-mcon-hortondf-01_</var/snap/lxd/common/lxd>//&:lxd-mcon-hortondf-01_<var-snap-lxd-common-lxd>:unconfined" name="lxc-container-default-with-nesting" pid=10134 comm="apparmor_parser"
[Sat Jun  9 23:45:59 2018] audit: type=1400 audit(1528845578.752:563): apparmor="STATUS" operation="profile_load" label="lxd-mcon-hortondf-01_</var/snap/lxd/common/lxd>//&:lxd-mcon-hortondf-01_<var-snap-lxd-common-lxd>:unconfined" name="/usr/lib/snapd/snap-confine" pid=10146 comm="apparmor_parser"
[Sat Jun  9 23:45:59 2018] audit: type=1400 audit(1528845578.752:564): apparmor="STATUS" operation="profile_load" label="lxd-mcon-hortondf-01_</var/snap/lxd/common/lxd>//&:lxd-mcon-hortondf-01_<var-snap-lxd-common-lxd>:unconfined" name="/usr/lib/snapd/snap-confine//mount-namespace-capture-helper" pid=10146 comm="apparmor_parser"
[Sat Jun  9 23:45:59 2018] audit: type=1400 audit(1528845578.756:565): apparmor="STATUS" operation="profile_load" label="lxd-mcon-hortondf-01_</var/snap/lxd/common/lxd>//&:lxd-mcon-hortondf-01_<var-snap-lxd-common-lxd>:unconfined" name="/usr/lib/lxd/lxd-bridge-proxy" pid=10137 comm="apparmor_parser"
[Sat Jun  9 23:45:59 2018] audit: type=1400 audit(1528845578.756:566): apparmor="STATUS" operation="profile_load" label="lxd-mcon-hortondf-01_</var/snap/lxd/common/lxd>//&:lxd-mcon-hortondf-01_<var-snap-lxd-common-lxd>:unconfined" name="/usr/sbin/tcpdump" pid=10153 comm="apparmor_parser"

 - [ ] Container log (`lxc info NAME --show-log`)

lxc info mcon-hortondf-01 --show-log
Name: mcon-hortondf-01
Remote: unix://
Architecture: x86_64
Created: 2018/06/12 22:33 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 9790
Ips:
  eth0:	inet	10.24.39.84	vethAO5NA9
  eth0:	inet6	fe80::216:3eff:fe63:c661	vethAO5NA9
  lo:	inet	127.0.0.1
  lo:	inet6	::1
  docker0:	inet	172.17.0.1
Resources:
  Processes: 55
  Disk usage:
    root: 45.08GB
  CPU usage:
    CPU usage (in seconds): 86
  Memory usage:
    Memory (current): 166.83MB
    Memory (peak): 275.79MB
  Network usage:
    eth0:
      Bytes received: 295.71kB
      Bytes sent: 6.73kB
      Packets received: 153
      Packets sent: 74
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    docker0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

 - [ ] Container configuration (`lxc config show NAME --expanded`)

lxc config show mcon-hortondf-01 --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20180612)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20180612"
  image.version: "16.04"
  security.nesting: "true"
  security.privileged: "true"
  volatile.base_image: 9743fc7ecac0ba3fdc04a037b77a62af3472e58755cf2db1feeadad9809e90c5
  volatile.eth0.hwaddr: 00:16:3e:63:c6:61
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: lxd
    type: disk
  tuntap:
    path: /dev/net/tun
    type: unix-char
ephemeral: false
profiles:
- default
stateful: false
description: ""

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

action=stop created=2018-05-04T04:24:17+0000 ephemeral=false lvl=info msg="Container initiated stop" name=sjonathan-personal stateful=false t=2018-06-10T11:00:15+0000 used=2018-06-09T22:28:27+0000
alias=16.04 image=9743fc7ecac0ba3fdc04a037b77a62af3472e58755cf2db1feeadad9809e90c5 lvl=info msg="Downloading image" operation=8957598f-9f2e-4b02-8e08-4ca6a8808427 server=https://cloud-images.ubuntu.com/releases t=2018-06-12T22:32:35+0000 trigger=/1.0/operations/8957598f-9f2e-4b02-8e08-4ca6a8808427
alias=16.04 image=9743fc7ecac0ba3fdc04a037b77a62af3472e58755cf2db1feeadad9809e90c5 lvl=info msg="Image downloaded" operation=8957598f-9f2e-4b02-8e08-4ca6a8808427 server=https://cloud-images.ubuntu.com/releases t=2018-06-12T22:33:22+0000 trigger=/1.0/operations/8957598f-9f2e-4b02-8e08-4ca6a8808427
ephemeral=false lvl=info msg="Creating container" name=mcon-hortondf-01 t=2018-06-12T22:33:23+0000
ephemeral=false lvl=info msg="Created container" name=mcon-hortondf-01 t=2018-06-12T22:33:24+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=mcon-hortondf-01 t=2018-06-12T22:33:36+0000
action=start created=2018-06-12T22:33:22+0000 ephemeral=false lvl=info msg="Starting container" name=mcon-hortondf-01 stateful=false t=2018-06-12T22:33:36+0000 used=1970-01-01T00:00:00+0000
action=start created=2018-06-12T22:33:22+0000 ephemeral=false lvl=info msg="Started container" name=mcon-hortondf-01 stateful=false t=2018-06-12T22:33:36+0000 used=1970-01-01T00:00:00+0000
action=shutdown created=2018-06-12T22:33:22+0000 ephemeral=false lvl=info msg="Shutting down container" name=mcon-hortondf-01 t=2018-06-12T23:02:21+0000 timeout=-1s used=2018-06-12T22:33:36+0000
action=shutdown created=2018-06-12T22:33:22+0000 ephemeral=false lvl=info msg="Shut down container" name=mcon-hortondf-01 t=2018-06-12T23:02:28+0000 timeout=-1s used=2018-06-12T22:33:36+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=mcon-hortondf-01 t=2018-06-12T23:02:39+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=mcon-hortondf-01 t=2018-06-12T23:02:43+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=mcon-hortondf-01 t=2018-06-12T23:03:54+0000
action=start created=2018-06-12T22:33:22+0000 ephemeral=false lvl=info msg="Starting container" name=mcon-hortondf-01 stateful=false t=2018-06-12T23:03:54+0000 used=2018-06-12T22:33:36+0000
action=start created=2018-06-12T22:33:22+0000 ephemeral=false lvl=info msg="Started container" name=mcon-hortondf-01 stateful=false t=2018-06-12T23:03:55+0000 used=2018-06-12T22:33:36+0000
lvl=info msg="Raft: Starting snapshot up to 2887" t=2018-06-12T23:04:52+0000
lvl=info msg="Raft: Compacting logs from 2690 to 2759" t=2018-06-12T23:04:52+0000
lvl=info msg="Raft: Snapshot to 2887 complete" t=2018-06-12T23:04:52+0000
action=stop created=2018-06-12T22:33:22+0000 ephemeral=false lvl=info msg="Container initiated stop" name=mcon-hortondf-01 stateful=false t=2018-06-12T23:18:18+0000 used=2018-06-12T23:03:54+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=mcon-hortondf-01 t=2018-06-12T23:19:29+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=mcon-hortondf-01 t=2018-06-12T23:19:37+0000
action=start created=2018-06-12T22:33:22+0000 ephemeral=false lvl=info msg="Starting container" name=mcon-hortondf-01 stateful=false t=2018-06-12T23:19:38+0000 used=2018-06-12T23:03:54+0000
action=start created=2018-06-12T22:33:22+0000 ephemeral=false lvl=info msg="Started container" name=mcon-hortondf-01 stateful=false t=2018-06-12T23:19:38+0000 used=2018-06-12T23:03:54+0000

-  [ ]

Docker version:

docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.03.1-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-22-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.57GiB
Name: mcon-hortondf-01
ID: 4IUD:MIVX:4IYJ:BTLN:R3PW:N3AA:DD6K:YOFC:FUYO:PHJ6:FZ6L:LUT7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
 - [ ] Output of the client with --debug

 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by brauner** [comment]
Your problem is the ` --privileged` flag that hortonworks passes to docker. If possible, you should remove it or - that's the not so nice option - make your container a privileged container by setting `lxc config set <container-name> security.privileged true` followed by `lxc restart <container-name>`.

**Comment by jonoinnz** [comment]
Hi Christian,

On Wed, 13 Jun 2018, 21:08 Christian Brauner, <notifications@github.com>
wrote:

> Your problem is the --privileged flag that hortonworks passes to docker.
> If possible, you should remove it or - that's the not so nice option - make
> your container a privileged container by setting lxc config set
> <container-name> security.privileged true followed by lxc restart
> <container-name>.
>

Thanks for the reply, this is the problem. I've already made it
security.privileged. Also tried to start without the --privileged flag but
then for some reason hortonworks doesn't work properly.

**Comment by stgraber** [comment]
So the `/proc` error is most likely because you didn't restart the container after setting `security.nesting`.
I'm not getting your error here, but I'm getting CGroup errors instead which have been associated with `--privileged` in the past.

The problem is that Docker CE appears to be skipping the code to make Docker work inside containers when `--privileged` is passed... There's not much we can do about that in LXD so the fix would need to happen in Docker itself and once that's fixed, we can add automatic testing on our side to see if that ever regresses.

I'd say, try rebooting your container, you're likely going to be getting CGroup errors instead, those might be skippable by using `raw.lxc` to override the devices cgroup keys (`lxc.cgroup.devices.allow = a` or something like that). I wouldn't really recommend this for security reasons, but that may at least be enough to figure out what's going on with Docker and what they'd need to fix.

**Comment by jonoinnz** [comment]
Hi Stéphane,

Thanks for the reply, so in short, I should run this inside a VM and not inside lxd?

Regards,
Jonathan

**Comment by stgraber** [comment]
Probably best for now, yes, unless you're ready for a rather funky LXD configuration that will effectively disable all security features to make Docker happy.

**Comment by jonoinnz** [comment]
Thanks very much, and thank you very much for lxc/lxd and everything that goes along with it, you guys are doing an o for awesome job :). (NZ saying, google o for awesome :))
