### ISSUE TITLE
LVM: inconsistent information about logical volumes 

### ISSUE THREAD

**Issue by esosan** [lxc/lxd#4645]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04 ( or 18.04)
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-23-generic
   * LXC version: 3.0.1 (or 3.1)
   * LXD version: 3.1 (or 3.1)
   * Storage backend in use: LVM (without thinpool)

# Issue description

After adding a container all information about LVM are not updated. 

# Steps to reproduce

 1. Check the LVM status
`$ lvs`
`ACTIVE            '/dev/pool00/containers_mysql' [3.00 GiB] inherit`
`ACTIVE            '/dev/pool00/containers_pgadmin' [3.00 GiB] inherit`
`$ vgs`
`pool00      1   2   0 wz--n-  <20.00g  <14.00g`
`$ pvs`
 `/dev/lvm/lxc_pool00 pool00    lvm2 a--   <20.00g  <14.00g`
 2. lxc init ubuntu:12.04  c1 (or lxc start ubuntu:1204 c1)
 3. lxc start c1 and lxc exec c1 bash (just to verify if the container is working)
 4. Check again LVM status: nothing it's changed from the step 1 output.
The new logical volumes is not showed or counted, but it's showed in /dev/pool00/ and the container work correctly.
Only after a full reboot LVM are updated.

Regards, Davide

**Comment by stgraber** [comment]
I'm assuming you're using the snap package?

If so, that's expected due to the snap including its own copy of the LVM tools (it can't use the host ones) which also means it's got its own cache.

We've had reports that running `pvscan` should get things to sync again.

**Comment by esosan** [comment]
Hi, you are right, I'm using the snap package.
I have to remember that Snap packages are something different... 
I thing pvscan alone it's not enough, `--cache` it's needed.

Thank you very much
