### ISSUE TITLE
Dump lxd config to yaml (inverse of `lxd init --preseed`)

### ISSUE THREAD

**Issue by killua-eu** [lxc/lxd#4648]
Hi, it would be very helpful to be able to dump the lxd configuration to a yaml file. Would be someone so kind and look at this? Cheers, Pavel

**Comment by stgraber** [comment]
`lxd init` already offers you too dump the chosen options as a yaml at the end

**Comment by killua-eu** [comment]
Yep, i'm aware, I was suggesting this for the time after `lxd init`.

**Comment by stgraber** [comment]
Let's go `lxd init --dump` for now.
