### ISSUE TITLE
lxd init automatically creates lxdbr0 in 3.0.1

### ISSUE THREAD

**Issue by smoser** [lxc/lxd#4649]
# Required information

 * Distribution: Ubuntu
 * Distribution version: cosmic
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-22-generic
   * LXC version: 3.0.1
   * LXD version: 3.0.1
   * Storage backend in use: dir

# Issue description
We have a cloud-init integration test that is failing in cosmic that passes in bionic.
The test consists of launching a new instance (independent of backend) with user-data
like:

    #cloud-config
    lxd:
      init:
        storage_backend: dir
      bridge:
        mode: new
        name: lxdbr0
        ipv4_address: 10.100.100.1
        ipv4_netmask: 24
        ipv4_dhcp_first: 10.100.100.100
        ipv4_dhcp_last: 10.100.100.200
        ipv4_nat: true
        domain: lxd

That causes cloud-init to do:

    lxd init --auto --storage-backend=dir
    lxc network create lxdbr0 ipv4.address=10.100.100.1/24 \
        ipv4.dhcp.ranges=10.100.100.100-10.100.100.200 \
        ipv6.address=none dns.domain=lxd --force-local

This works in bionic, but in cosmic, the network create command fails with

    Error: The network already exists

The difference between the two is that after 'lxd init' on bionic there is no lxdbr0 network interface, but on cosmic there is.

**Comment by stgraber** [comment]
Right, the lack of network configuration when running `lxd init --auto` was a bug which got fixed.
The fix is in LXD 3.1 and LXD 3.0.1, so bionic will have the same behavior in a week or so when the SRU gets released.

I'd recommend putting the `lxc network create` under a check which checks if `eth0` is listed in `lxc profile device list default`.

**Comment by smoser** [comment]
well, I don't think your suggested check is sufficient.
If the user provided specific network configuration for the bridge ('ipv4_address, ipv4_netmask, ipv6_nat...) then we will need to make sure that they get what they asked for.

We can adjust cloud-init, but you should consider the fact that your change will break existing consumers of lxd. Because of that, it would not fit under standard ubuntu Stable Release Guidelines.

**Comment by smoser** [comment]
filed cloud-init bug to track in https://bugs.launchpad.net/cloud-init/+bug/1776958
