### ISSUE TITLE
Setting nvidia.runtime in LXD 3.10 causes failure from snap hook shell program nvidia

### ISSUE THREAD

**Issue by bakerjalexander** [lxc/lxd#4651]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-127-generic
   * LXC version:
   * LXD version: 3.10
   * Storage backend in use:dir

# Issue description

Setting the nvidia.runtime variable invokes snapd to run a script: /snap/lxd/current/lxc/hooks/nvidia. This fails because it throws an invalid option 'r'  to nvidia-container-cli which causes the container to refuse to start 

Steps to reproduce

 1. Create Ubuntu 16.04 container
 2. Set nvidia.runtime to true
 3. Stop and start container

Here's the relevant debug info:

lxc cuda 20180614091500.789 INFO     lxc_conf - conf.c:run_script_argv:369 - Executing script "/snap/lxd/current/lxcfs/lxc.mount.hook" for container "cuda", config section "lxc"

lxc cuda 20180614091500.112 INFO     lxc_conf - conf.c:run_script_argv:369 - Executing script "/snap/lxd/current/lxc/hooks/nvidia" for container "cuda", config section "lxc"

lxc cuda 20180614091500.145 DEBUG    lxc_conf - conf.c:run_buffer:339 - Script exec /snap/lxd/current/lxc/hooks/nvidia cuda lxc mount with output: + exec nvidia-container-cli --user configure --no-cgroups --ldconfig=@/sbin/ldconfig.real --device=all --compute --compat32 --display --graphics --utility --video /var/snap/lxd/common/lxc/

lxc cuda 20180614091500.150 DEBUG    lxc_conf - conf.c:run_buffer:339 - Script exec /snap/lxd/current/lxc/hooks/nvidia cuda lxc mount with output: /var/lib/snapd/hostfs/usr/bin/nvidia-container-cli: invalid option -- 'r'

lxc cuda 20180614091500.150 DEBUG    lxc_conf - conf.c:run_buffer:339 - Script exec /snap/lxd/current/lxc/hooks/nvidia cuda lxc mount with output: Try `nvidia-container-cli --help' or `nvidia-container-cli --usage' for more

lxc cuda 20180614091500.150 DEBUG    lxc_conf - conf.c:run_buffer:339 - Script exec /snap/lxd/current/lxc/hooks/nvidia cuda lxc mount with output: information.

lxc cuda 20180614091500.150 ERROR    lxc_conf - conf.c:run_buffer:348 - Script exited with status 1
lxc cuda 20180614091500.150 ERROR    lxc_conf - conf.c:lxc_setup:3466 - Failed to run mount hooks

Here's what I added to the profile, doubt if it makes a difference:
 raw.lxc: |-
    ### nvidia
    lxc.log.level = debug
    lxc.cgroup.devices.allow = c 195:* rwm
    lxc.cgroup.devices.allow = c 241:* rwm
    lxc.cgroup.devices.allow = c 226:* rwm
    lxc.cgroup.devices.allow = c 29:0 rwm
    lxc.mount.entry = /dev/nvidia0 dev/nvidia0 none bind,optional,create=file
    lxc.mount.entry = /dev/nvidiactl dev/nvidiactl none bind,optional,create=file
    lxc.mount.entry = /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file
    lxc.mount.entry = /dev/nvidia-modeset dev/nvidia-modeset none bind,optional,create=file
    lxc.mount.entry = /dev/dri/card0 dev/dri/card0 none bind,optional,create=file
    lxc.mount.entry = /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
    lxc.mount.entry = /dev/dri/controlD64 dev/dri/controlD64 none bind,optional,create=file
    lxc.mount.entry = /dev/fb0 dev/fb0 none bind,optional,create=file
    lxc.environment = NVIDIA_VISIBLE_DEVICES=all
    lxc.environment = NVIDIA_DRIVER_CAPABILITIES=all

And here's this:

nvidia-container-cli -V
version: 1.0.0
build date: 2017-10-30T23:47+00:00
build revision: ec15c7233bd2de821ad5127cb0de6b52d9d2083c
build compiler: gcc-5 5.4.0 20160609
:

**Comment by brauner** [comment]
Hm, I wonder whether this is the script messing up.

**Comment by stgraber** [comment]
Hmm, when did NVIDIA remove the `-r` option from nvidia-container-cli? Because that sure used to be a supported argument.

**Comment by brauner** [comment]
//cc @3XX0

**Comment by stgraber** [comment]
Just checked the current code on Github and `-r` is very much still there so this should work fine.

**Comment by bakerjalexander** [comment]
Yes, that did it! Was using an old deb file I guess.  Thanks so much!
