### ISSUE TITLE
Sudo does not work within container

### ISSUE THREAD

**Issue by uahic** [lxc/lxd#4664]
# Required information

➜  ~ lxc info
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 141.21.47.39:8443
  - '[2a02:788:13:20:9c07:4350:e019:ba95]:8443'
...
  - '[2a02:788:13:20:b26e:bfff:fe36:dd]:8443'
  - 192.168.122.1:8443
  - 172.17.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate:  ...
  certificate_fingerprint: ...
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-122-generic
  server: lxd
  server_pid: 29060
  server_version: "3.1"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu20
  server_clustered: false
  server_name: ...

# Issue description

I ssh'ed into a host computer that runs a LXD container and tried to install ROS (wiki.ros.org), so ssh -> lxd-computer -> lxc exec c1 -- <command> 
but when executing this command to grep a GPG Key: 
sudo wget -O - https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
then it waits for a long time and aborts. Even using sudo alone or with other commands seem to fail as well. 
It always aborts with: 'sudo: unable to resolve host c1: Connection timed out'
How could I resolve this issue? I really dont know much how LXD works underneath

Thank you so much

**Comment by stgraber** [comment]
So the problem here is that your shell command is wrong. You're running `wget` inside the container and piping its output into `sudo apt-key` outside of it.

I'd recommend getting an interactive shell inside the container with `lxc exec c1 bash` and then running your command from there. If you must script it, then you'd want:

    lxc exec c1 -- sh -c "wget -O - https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | apt-key add -"

Note that I removed the `sudo` calls as `lxc exec` gets you a root shell, so no need for them anyways.
