### ISSUE TITLE
Add a /1.0/networks/NAME/state API

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4665]
Somewhat similar to what we have for containers, we'd want this to return the current addresses of the interface, MAC address, MTU, packet statistics, ...

**Comment by monstermunchkin** [comment]
Would this information be enough or is there something else we want/need here?
```json
"metadata": {
    "name": "lxdbr0",
    "mtu": 1500,
    "hwaddr": "fe:13:a8:2e:2e:70",
    "addresses": [
      "10.92.180.1/24",
      "fd42:89b2:d00e:9762::1/64",
      "fe80::18c9:2dff:fe7c:1422/64"
    ],
    "stats": {
      "bytes_transmitted": 906388,
      "bytes_received": 31719,
      "packets_transmitted": 3673,
      "packets_received": 384
    }
  }
```

**Comment by stgraber** [comment]
I don't think we need the name in there since the API call already contains it, rest looks good to me.
