### ISSUE TITLE
Build LXD For arm64

### ISSUE THREAD

**Issue by sarayuks** [lxc/lxd#4672]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description
I am trying to build LXD for arm64 from an amd64 host. I got some details from the link 
https://golangcookbook.com/chapters/running/cross-compiling/  but when i try to build the lxd code i am getting the below error.
I am on the latest go version go1.10.1 linux/amd64

root@debian:~/code/lxd/go/src/github.com/lxc/lxd$ make
go get -t -v -d ./...
go build -v   ./...
github.com/lxc/lxd/shared
# github.com/lxc/lxd/shared
shared/archive_linux.go:79:15: undefined: DeviceTotalMemory
shared/network_linux.go:19:9: undefined: ExecReaderToChannel
github.com/gosexy/gettext
go build github.com/gosexy/gettext: build constraints exclude all Go files in /home/sarayu/code/lxd/go/src/github.com/gosexy/gettext
github.com/CanonicalLtd/go-sqlite3
# github.com/CanonicalLtd/go-sqlite3
../../CanonicalLtd/go-sqlite3/sqlite3_go18.go:18:10: undefined: SQLiteConn
Makefile:16: recipe for target 'default' failed
make: *** [default] Error 2

I would instead expect LXD to build successfully.

# Steps to reproduce
 1. Have a yocto setup for arm and generate the required toolchain to be used for gcc and g++ ( For test purpose , i tried to use the gcc and g++ also but i still see the same problem.
 2. Set the below env variables 
	sarayu@debian:~/code/lxd/go/src/github.com/lxc/lxd$ go env
	GOARCH="arm64"
	GOBIN=""
	GOCACHE="/home/sarayu/.cache/go-build"
	GOEXE=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOOS="linux"
	GOPATH="/home/sarayu/code/lxd/go"
	GORACE=""
	GOROOT="/home/sarayu/go/latest/go"
	GOTMPDIR=""
	GOTOOLDIR="/home/sarayu/go/latest/go/pkg/tool/linux_amd64"
	GCCGO="gccgo"
	CC="aarch64-fsl-linux-gcc"
	CXX="aarch64-fsl-linux-g++"
	CGO_ENABLED="0"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="--sysroot=/opt/fsl-qoriq/2.0/sysroots/aarch64-fsl-linux -fPIC -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build925670415=/tmp/go-build -gno-record-gcc-switches"
 3. Run the makefile

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Looks like your Go compiler is lacking cgo support when cross-compiling. All the errors you've listed above come from a lack of cgo.

We don't support cross-compiling LXD, instead just doing native builds on the various architectures instead. That said, there's no technical reason why cross-compiling would be impossible, but you do need to get your Go compiler to properly build and link cgo code before you have any chance of building LXD.

**Comment by sarayuks** [comment]
Hi stgraber ,

Thanks for your quick response. However i have a few more questions since i am relatively new to go and LXD. I had initially tried to build LXD for amd64 ( my debian VM ) and i followed the instructions in the link https://tecadmin.net/install-go-on-debian/ to install the latest go version 1.10 and i was able to successfully compile LXD and execute the same on my debian machine and if i see the go env there i could see that the CGO_ENABLED=1 as shown below, 
	root@debian:~$ go env
	GOARCH="amd64"
	GOBIN=""
	GOEXE=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOOS="linux"
	GOPATH=""
	GORACE=""
	GOROOT="/usr/lib/go-1.7"
	GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_amd64"
	CC="gcc"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build591981653=/tmp/go-build -gno-record-gcc-switches"
	CXX="g++"
	CGO_ENABLED="1"

How ever , in my current setup to cross compile LXD for ARM, when i try to enable the CGO_ENABLED flag i get the below errors, 
	sarayu@debian:~/code/lxd/go/src/github.com/lxc/lxd$ make
	go get -t -v -d ./...
	go install -v   ./...
	runtime/cgo
	net
	# net
	/home/sarayu/go/latest/go/src/net/cgo_linux.go:10:19: fatal error: netdb.h: No such file or directory
	 #include <netdb.h>
	                   ^
	compilation terminated.
	os/user
	# os/user
	/home/sarayu/go/latest/go/src/os/user/cgo_lookup_unix.go:20:20: fatal error: unistd.h: No such file or directory
	 #include <unistd.h>
	                    ^
	compilation terminated.
	github.com/gosexy/gettext
	# github.com/gosexy/gettext
	../../gosexy/gettext/gettext.go:28:21: fatal error: libintl.h: No such file or directory
	 #include <libintl.h>
	                     ^
	compilation terminated.
	github.com/CanonicalLtd/go-sqlite3
	# github.com/CanonicalLtd/go-sqlite3
	../../CanonicalLtd/go-sqlite3/backup.go:14:20: fatal error: stdlib.h: No such file or directory
	 #include <stdlib.h>
	                    ^
	compilation terminated.
	gopkg.in/lxc/go-lxc.v2

Kindly let me knew what i am missing . It would be helpful if you could point me to any references as well.

**Comment by stgraber** [comment]
Looks like you're missing all libraries and headers for your target architecture. I don't know how you specify those paths for Go to use when cross-compiling, but you'll need to figure that part out and make sure that you have all headers and libraries for your target architecture so that the compiler and linker can do their job.

**Comment by sarayuks** [comment]
Thanks for your inputs .. Was able to crosscompile lxd successfully.
