### ISSUE TITLE
udevadm command fails in lxd 3.0 when ceph-osd charm is installed. 

### ISSUE THREAD

**Issue by sfeole** [lxc/lxd#4673]
Bionic
18.04
Linux d05-4 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 17:59:52 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
LXD version 3.0
zfs storage backend in use.

Starting with ceph-osd-262 the addition of a udevadm command during storage.real causes install to fail when performed in a LXD container. 

The return code from udevadm control --reload-rules is '2' when run in a LXD even when set to priviliaged and nesting enabled.

Debug Log showing the error:
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install Traceback (most recent call last):
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install File "/var/lib/juju/agents/unit-ceph-osd-0/charm/hooks/install.real", line 630, in <module>
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install hooks.execute(sys.argv)
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install File "/var/lib/juju/agents/unit-ceph-osd-0/charm/hooks/charmhelpers/core/hookenv.py", line 823, in execute
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install self._hooks[hook_name]()
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install File "/var/lib/juju/agents/unit-ceph-osd-0/charm/hooks/charmhelpers/contrib/hardening/harden.py", line 79, in _harden_inner2
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install return f(*args, **kwargs)
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install File "/var/lib/juju/agents/unit-ceph-osd-0/charm/hooks/install.real", line 242, in install
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install install_udev_rules()
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install File "/var/lib/juju/agents/unit-ceph-osd-0/charm/hooks/install.real", line 231, in install_udev_rules
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install '--reload-rules'])
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install raise CalledProcessError(retcode, cmd)
unit-ceph-osd-0: 16:33:15 DEBUG unit.ceph-osd/0.install subprocess.CalledProcessError: Command '['udevadm', 'control', '--reload-rules']' returned non-zero exit status 2
unit-ceph-osd-0: 16:33:15 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1

1.) Install Bionic 18.04
2.) Using the shipping version of LXD (3.0) configure and bootstrap a juju localhost controller
3.) Deploy openstack-on-lxd ( https://docs.openstack.org/charm-guide/latest/openstack-on-lxd.html )
4.) ceph-osd will fail to complete install.

Workaround:

Install LXD 3.1 from the snap store, --stable.  ceph-osd 262 installs properly

For additional logs, please see:
Please see: https://bugs.launchpad.net/charm-ceph-osd/+bug/1776713

**Comment by stgraber** [comment]
What version of Ubuntu is used inside the container?

There's really no reason for LXD 3.1 to make any difference here so it's likely something else at play.
We had cases (snapd) where udevadm would fail the first time bu succeed the second time so it may just be some kind of race.

It'd be good to know what udevadm is actually doing and failing on.

**Comment by sfeole** [comment]
Hey Stephane,  I'm using Bionic, but after further testing its looking more like this is some sort of race as you had suggested.  I'm able to install and confgure ceph-osd on lxd 3.0 / bionic with no complaints via udevadm.  Will close this out for now, as it would appear to be more of an issue with the charm than lxd. 

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

ubuntu@hotdog:~/openstack-on-lxd$ uname -a
Linux hotdog 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 17:59:52 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

$ lxc --version
3.0.0

Model Controller Cloud/Region Version SLA
default localhost-localhost localhost/localhost 2.3.8 unsupported

App Version Status Scale Charm Store Rev OS Notes
ceilometer 10.0.0 waiting 1 ceilometer jujucharms 253 ubuntu
ceilometer-agent waiting 0 ceilometer-agent jujucharms 244 ubuntu
ceph-mon 12.2.4 active 3 ceph-mon jujucharms 25 ubuntu
ceph-osd 12.2.4 active 3 ceph-osd jujucharms 262 ubuntu
ceph-radosgw 12.2.4 active 1 ceph-radosgw jujucharms 258 ubuntu

Unit Workload Agent Machine Public address Ports Message
ceilometer/0* waiting idle 0 10.111.158.119 Incomplete relations: messaging
ceph-mon/0* active idle 1 10.111.158.183 Unit is ready and clustered
ceph-mon/1 active idle 2 10.111.158.173 Unit is ready and clustered
ceph-mon/2 active idle 3 10.111.158.188 Unit is ready and clustered
ceph-osd/0* active idle 4 10.111.158.134 Unit is ready (1 OSD)
ceph-osd/1 active idle 5 10.111.158.33 Unit is ready (1 OSD)
ceph-osd/2 active idle 6 10.111.158.213 Unit is ready (1 OSD)
ceph-radosgw/0* active idle 7 10.111.158.43 80/tcp Unit is ready

**Comment by schkovich** [comment]
related launchpad [bug report](https://bugs.launchpad.net/charm-ceph-osd/+bug/1776713)

**Comment by schkovich** [comment]
@stgraber It's about this set of rules: https://github.com/openstack/charm-ceph-osd/blob/master/files/udev/95-charm-ceph-osd.rules

LXC 3.1 makes no difference.

**Comment by stgraber** [comment]
@schkovich does emptying the fstab file in the container fix this issue?

**Comment by schkovich** [comment]
No difference @stgraber 
```
$ sudo cp /dev/null /etc/fstab 
$ exit
logout
Connection to 10.x.x.x closed.
$ juju resolved ceph-osd/0
$ juju debug-log --include ceph-osd/0
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install Traceback (most recent call last):
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install   File "/var/lib/juju/agents/unit-ceph-osd-0/charm/hooks/install.real", line 630, in <module>
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install     hooks.execute(sys.argv)
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install   File "/var/lib/juju/agents/unit-ceph-osd-0/charm/hooks/charmhelpers/core/hookenv.py", line 823, in execute
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install     self._hooks[hook_name]()
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install   File "/var/lib/juju/agents/unit-ceph-osd-0/charm/hooks/charmhelpers/contrib/hardening/harden.py", line 79, in _harden_inner2
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install     return f(*args, **kwargs)
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install   File "/var/lib/juju/agents/unit-ceph-osd-0/charm/hooks/install.real", line 242, in install
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install     install_udev_rules()
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install   File "/var/lib/juju/agents/unit-ceph-osd-0/charm/hooks/install.real", line 231, in install_udev_rules
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install     '--reload-rules'])
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install     raise CalledProcessError(retcode, cmd)
unit-ceph-osd-0: 15:15:36 DEBUG unit.ceph-osd/0.install subprocess.CalledProcessError: Command '['udevadm', 'control', '--reload-rules']' returned non-zero exit status 2
unit-ceph-osd-0: 15:15:36 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1
```
```
$ sudo udevadm control --reload-rules
$ echo $?
2
```
Command `sudo mount -o remount /` did not fail after removing `LABEL=cloudimg-rootfs	/	 ext4	defaults	0 0` from /etc/fstab as expected.

**Comment by schkovich** [comment]
James Page is saying that proposed oneliner is [good enough](https://bugs.launchpad.net/charm-ceph-osd/+bug/1776713/comments/7).
