### ISSUE TITLE
config editing issue on Centos with Snap package

### ISSUE THREAD

**Issue by antst** [lxc/lxd#4674]
# Required information

 * Distribution: CentOS 
 * Distribution version: 7.5.1804
 * The output of "lxc info" or if that fails:
 driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 3.10.0-862.3.2.el7.x86_64
  server: lxd
  server_pid: 28025
  server_version: "3.1"
  storage: zfs
  storage_version: 0.7.9-1
  server_clustered: false

# Issue description

I can not edit configs. 

"lxc config show"  works.
"lxc config set" works
"lxc config edit" fails with messages like

_Error: open /tmp/lxd_editor_403151221: no such file or directory_

I tried with --debug and

`# lxc --debug config edit`

DBUG[06-21|10:22:26] Connecting to a local LXD over a Unix socket
DBUG[06-21|10:22:26] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[06-21|10:22:26] Got response struct from LXD
DBUG[06-21|10:22:26]
	{
...config dump here...
}
BUG[06-21|10:22:26] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[06-21|10:22:26] Got response struct from LXD
DBUG[06-21|10:22:26]
{
...yet another config dump here
}
Error: open /tmp/lxd_editor_726257605: no such file or directory

**Comment by stgraber** [comment]
What does `ls -lh /proc/$(pgrep daemon.start)/root/` show you?

**Comment by antst** [comment]
Actually, it shows nothing because `pgrep daemon.start` returns nothing

**Comment by stgraber** [comment]
Hmm, so the snap isn't running then?
Can you post a full `ps fauxww`?
