### ISSUE TITLE
Help ! Container is not longer accessible.

### ISSUE THREAD

**Issue by HW-Siew** [lxc/lxd#4689]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.13.0-1015-gcp
   * LXC version: 3.0.1
   * LXD version: 3.0.1
   * Storage backend in use: zfs

Out of sudden, all of my containers are not longer accessible. It hangs when I do `lxc exec container bash` . However, lxc list is working fine and the status of all containers are running.

I tried other command, for example, `lxc snapshot container name`  it showed an error  
`Error: Failed to create ZFS snapshot: cannot open 'lxd/containers/container': pool I/O is currently suspended`

Your help is very much appreciated. Kindly advise anything i can try.

Thanks!

**Comment by HW-Siew** [comment]
Hi @simos , thanks for your prompt reply.

zfs list shows 'no datasets available' & I get hang when i tried to run the command of zpool list.

**Comment by HW-Siew** [comment]
After i reboot the machine, it is now back to normal. I wonder if anyone know what is the cause and solution for this issue. 

I had posted in the forum too -> https://discuss.linuxcontainers.org/t/error-pool-i-o-is-currently-suspended/2104

Thanks

**Comment by brauner** [comment]
As this is tracked in the forum let's close here.
