### ISSUE TITLE
volume attach fails when ZFS snapshots exists and snapdir=visible

### ISSUE THREAD

**Issue by mjansens** [lxc/lxd#4690]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-23-generic
   * LXC version: 3.0.0
   * LXD version: 3.0.0
   * Storage backend in use: ZFS

# Issue description

I'm trying to attach a  custom volume to a container and it fails with: "Error: Failed to setup device: 

> Failed to initialize storage volume "test-shared-data" of type "custom" on storage pool "default": Failed to change ownership of: /var/lib/lxd/storage-pools/default/custom/test-shared-data/.zfs/snapshot/cvlt."

This happens when I set the ZFS snapdir=visible attribute  which I had to do the allow CommVault backup agent to drill through the snapshot directory to backup a coherent state ( the 'cvlt' snapshot)

# Steps to reproduce

 lxc storage volume create default test-shared-data
 zfs set snapdir=visible zfspool/lxd/custom/test-shared-data
 zfs snapshot zfspool/lxd/custom/test-shared-data@cvlt
 lxc storage volume attach default test-shared-data testcontainer /shared-data

**Comment by stgraber** [comment]
@brauner can you take a look at this one?

It should be acceptable to add code that skips shifting of paths under `<root>/.zfs/snapshot` when on a ZFS filesystem. Bonus point if we can check for the `snapdir=visible` option, but I don't think that this is something the remapping code has access to (and I wouldn't do any major changes to make that accessible).

**Comment by mjansens** [comment]
Great Thanks a lot Christian and Stéphane!
I suppose I won't see that comming in 3.0.x only in 3.3.x?

Michel

**Comment by stgraber** [comment]
That fix will be in 3.0.2

**Comment by mjansens** [comment]
Fantastic Stéphane!

 thanks.

Michel
