### ISSUE TITLE
lxc remote add: automatically agree with fingerprint

### ISSUE THREAD

**Issue by killua-eu** [lxc/lxd#4693]
Hi, for automation it would be very convenient to be able to add

```
lxc remote add c1 https://1.2.3.4:8443 --protocol=lxd --password=mypw"
```

in such a way, that the question

```
Certificate fingerprint: 1a22....
ok (y/n)? y
```

can be skipped (forced as 'yes'). So something like

```
lxc remote add c1 https://1.2.3.4:8443 --protocol=lxd --password=mypw" --accept-fingerprint
```

would really help

**Comment by HW-Siew** [comment]
It is already supported. Check lxc remote add -h. It is --accept-certificate.

**Comment by killua-eu** [comment]
Sorry everyone, I must be really blind not to see the option right on the first spot.
