### ISSUE TITLE
lxc.hook.destroy in raw.lxc does not work

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#4695]
Is this somehow will be supported or are there any work-arounds ?

**Comment by brauner** [comment]
What exactly is the issue you're seeing? Can you provide a log that illustrates the error. What exactly are you setting as the `raw.lxc` value for `lxc.hook.destroy`?

**Comment by s3rj1k** [comment]
I am setting raw.lxc: lxc.hook.destroy = /tmp/test.sh

/tmp/test.sh contains:
```
#!/bin/bash
echo $@ > /tmp/params
```

and I do not see any output in /tmp/params

is should contain hook specific params

**Comment by brauner** [comment]
Oh, the destroy hook might not be triggered since the LXC API is not used directly for that. Instead LXD is destroying it directly.

**Comment by brauner** [comment]
Actually, there's a trick to get this working. We can safely call LXC's destroy method but exclude actual storage destruction from it by unsetting t the `lxc.rootfs.path` argument.

**Comment by s3rj1k** [comment]
I would actually prefer proper hook support from within lxd (blocking and non-blocking)
but if this trick is doable for lxd 3.0 (LTS branch), I am voting for that fix

**Comment by stgraber** [comment]
@brauner I'd be fine having Delete() call out to that as the last thing it does, after rootfs and DB records are gone and ignoring errors coming from it, that should make it safe.

**Comment by brauner** [comment]
I can see how easy this is. No promises. :)

**Comment by brauner** [comment]
This can't be done safely and nicely currently. I think we need some minimal plumbing in LXC first for this to work out.

**Comment by s3rj1k** [comment]
@brauner  any news on hook support?
