### ISSUE TITLE
Add recursion support for /1.0/certficates

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#470]
Similar to /1.0/images, implement support for querying all the certificates at once.

**Comment by pcdummy** [comment]
Can you tell me more about this feature request?

This looks like it already returns all certificates:

		func certificatesGet(d *Daemon, r *http.Request) Response {
			body := []string{}
			for _, cert := range d.clientCerts {
				fingerprint := shared.GenerateFingerprint(&cert)
				body = append(body, fingerprint)
			}

			return SyncResponse(true, body)
		}

**Comment by stgraber** [comment]
So ideally, what I'd like to see is:
 - Switch to concatenated fingerprints (remove the spaces)
 - Have /1.0/certificates list them as it does today
 - Have /1.0/certificates?recursion=1 list the equivalent of /1.0/certificates/\<fingerprint\> for each certificate.

So basically:

    stgraber@dakara:~$ curl -s -k --cert .config/lxc/client.crt --key .config/lxc/client.key https://127.0.0.1:8443/1.0/certificates | jq 
    {
      "metadata": [
            "4962f79bad695d80c65fafb05d2961fac072700a50b6f62e398e7d73ca9853eb"
          ],
         "status_code": 200,
         "status": "Success",
         "type": "sync"
    }

    stgraber@dakara:~$ curl -s -k --cert .config/lxc/client.crt --key .config/lxc/client.key https://127.0.0.1:8443/1.0/certificates/4962f79bad695d80c65fafb05d2961fac072700a50b6f62e398e7d73ca9853eb | jq 
    {
      "metadata": {
            "type": "client",
            "certificate": "pem encoded certificate",
          },
         "status_code": 200,
         "status": "Success",
         "type": "sync"
    }

**Comment by stgraber** [comment]
Ok, I think I'm done editing my comment :)

**Comment by pcdummy** [comment]
This is what this patch gives.

    pcdummy@UbuntuPro:~/.gvm/pkgsets/go1.4.2/global/src/github.com/lxc/lxd$ curl -s -k --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key https://localhost:8443/1.0/certificates | jq .
    {
      "type": "sync",
      "status": "Success",
      "status_code": 200,
      "metadata": [
        "e5cc118418f926436af5990b363911d898f5309731946d2d37c51bc7b2cf24e9"
      ]
    }

    pcdummy@UbuntuPro:~/.gvm/pkgsets/go1.4.2/global/src/github.com/lxc/lxd$ curl -s -k --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key https://localhost:8443/1.0/certificates/309731946d2d37c51bc7b2cf24e9 | jq .
    {
      "type": "sync",
      "status": "Success",
      "status_code": 200,
      "metadata": {
        "certificate": "MIIFEDCCAvqgAwIBAgIRAM1h/dXMbeT//ysM368rqfgwCwYJKoZIhvcNAQELMB0xGzAZBgNVBAoTEmxpbnV4Y29udGFpbmVyLm9yZzAeFw0xNDEyMjcwMjA4MDdaFw0xNTEyMjcwMjA4MDdaMB0xGzAZBgNVBAoTEmxpbnV4Y29udGFpbmVyLm9yZzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALockqDq7qi4+Myo2JdNAl4c1FBsMo27KEFxn5lw+g9ceRlTzCbGv/SPtkjXN+jMlDlwkGAO1N4/yXtUxBQYO2si/IphHEuQlEczYio4UyRs05YO1ZUpcL0B6mbBT7wXLL1E/5IRnASoYj7Kiuk9/PKtJybRdLICcE4JRn1w+JP1uxtBlOyVqkyyt1JmPE3eqdpdaWNERWFkKP/Dbp6Qwa3880evM2OY1swLtslnoC++lsGpL58pb+2sr1yGllYDe5n5VLMjXILenIQkgwWqLAH6QSC97Plv0RLQyhx5ggLZSbjz5RXuHDfzC/dbIOea+9sNMJMqncx1SNcwtM1kO9Wm+f/x5XpeCImeVYj+ScHUiswVOARGEb6FNKar7oWtkOZzO96FgZrwB4VY7XyucYYUTJHJiRHfWtbfkCbtozy+EYibHrt5tI0f22kygdH/jfPCuMzM3XstBUDjvJzD9lzyWUiLj7BqkeZteq4Q4Xh6c98Uz4pucLW2zpT/rYBDkVl9sQu4iUfwnVaMdKte4TGCD7N2cWmIUYbuFeUquVj0drgtGTCW8gVmzZdrRBwV66NBH8qx+ib4TCVsrr17+O/3SFNAsH5/UA0KBcCFimJNiqlFdrg68UhxflPX7gBOyAh2T+7TWmhzi2Td6XIMChXF01pGY2hlra7wnAaW8h8XAgMBAAGjTzBNMA4GA1UdDwEB/wQEAwIAoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMBgGA1UdEQQRMA+CDVRoaW5rUGFkLVQ0MTAwCwYJKoZIhvcNAQELA4ICAQB4d0VhGctTSgarTobu+KAOzC+ujNwdqC/jwcbp5VStLIgDlKRaif+MBUrwvspNXouKsDXBNwffgKcd4EUgevptuM0mx8K3I0F2PhkXJDoJjru61Np8f22AVdvDhjgz0emQUhelhxvUGBG5nd2HOaiQ5LM2pmjqUvBvgbNpEQhQAGnQq7xDLVoNK3RD0Sx+WvqofNubpTyS9yZcW0jd34mLq203w2m5Bxqx1qbGQQa5pnJ1gsWia1mHTWp7zpZveFVSqLjiZwG0LVAS2VkJ8z2j07EdE+UQwCgG25xrXUDwmeK9yTPhntdJh92Ahbtm48nie5NXCkLNlYzP1IPWYF3MBFhIDNy34xRwM2CGpm0LJh6DG5ogf8uanboVryK9ESInWnYlZ+/j9k8819x/UiVzfg4Hn98OF6lnepFJryQo9i5w6xLm/JFK6822u65ZiWN92SUBMk1TpSDokWU+4jEnlbBktFGn6Fi/thaQC/X8ITKu6Z18fybWijSNyENmin+M1hZSdId8NLmSiU4YMlDDn9jkaZCrqliqNZUgcgdpFBZjeQYOP3ecUQ+PrIIVa4HoDLmVBD6+J9SJaD4Ayk3MvBtSgUUjfKz7cae6TcU8QqFey5xlsnx6RfL84CIYvNJo+l4uH+U7MznUGVq5rJxlFMUvyJ0OgzK6fjM22Ixu9w==",
        "fingerprint": "e5cc118418f926436af5990b363911d898f5309731946d2d37c51bc7b2cf24e9",
        "type": "client"
      }
    }

    pcdummy@UbuntuPro:~/.gvm/pkgsets/go1.4.2/global/src/github.com/lxc/lxd$ curl -s -k --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key https://localhost:8443/1.0/certificates?recursion=1 | jq .
    {
      "type": "sync",
      "status": "Success",
      "status_code": 200,
      "metadata": [
        {
          "certificate": "MIIFEDCCAvqgAwIBAgIRAM1h/dXMbeT//ysM368rqfgwCwYJKoZIhvcNAQELMB0xGzAZBgNVBAoTEmxpbnV4Y29udGFpbmVyLm9yZzAeFw0xNDEyMjcwMjA4MDdaFw0xNTEyMjcwMjA4MDdaMB0xGzAZBgNVBAoTEmxpbnV4Y29udGFpbmVyLm9yZzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALockqDq7qi4+Myo2JdNAl4c1FBsMo27KEFxn5lw+g9ceRlTzCbGv/SPtkjXN+jMlDlwkGAO1N4/yXtUxBQYO2si/IphHEuQlEczYio4UyRs05YO1ZUpcL0B6mbBT7wXLL1E/5IRnASoYj7Kiuk9/PKtJybRdLICcE4JRn1w+JP1uxtBlOyVqkyyt1JmPE3eqdpdaWNERWFkKP/Dbp6Qwa3880evM2OY1swLtslnoC++lsGpL58pb+2sr1yGllYDe5n5VLMjXILenIQkgwWqLAH6QSC97Plv0RLQyhx5ggLZSbjz5RXuHDfzC/dbIOea+9sNMJMqncx1SNcwtM1kO9Wm+f/x5XpeCImeVYj+ScHUiswVOARGEb6FNKar7oWtkOZzO96FgZrwB4VY7XyucYYUTJHJiRHfWtbfkCbtozy+EYibHrt5tI0f22kygdH/jfPCuMzM3XstBUDjvJzD9lzyWUiLj7BqkeZteq4Q4Xh6c98Uz4pucLW2zpT/rYBDkVl9sQu4iUfwnVaMdKte4TGCD7N2cWmIUYbuFeUquVj0drgtGTCW8gVmzZdrRBwV66NBH8qx+ib4TCVsrr17+O/3SFNAsH5/UA0KBcCFimJNiqlFdrg68UhxflPX7gBOyAh2T+7TWmhzi2Td6XIMChXF01pGY2hlra7wnAaW8h8XAgMBAAGjTzBNMA4GA1UdDwEB/wQEAwIAoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMBgGA1UdEQQRMA+CDVRoaW5rUGFkLVQ0MTAwCwYJKoZIhvcNAQELA4ICAQB4d0VhGctTSgarTobu+KAOzC+ujNwdqC/jwcbp5VStLIgDlKRaif+MBUrwvspNXouKsDXBNwffgKcd4EUgevptuM0mx8K3I0F2PhkXJDoJjru61Np8f22AVdvDhjgz0emQUhelhxvUGBG5nd2HOaiQ5LM2pmjqUvBvgbNpEQhQAGnQq7xDLVoNK3RD0Sx+WvqofNubpTyS9yZcW0jd34mLq203w2m5Bxqx1qbGQQa5pnJ1gsWia1mHTWp7zpZveFVSqLjiZwG0LVAS2VkJ8z2j07EdE+UQwCgG25xrXUDwmeK9yTPhntdJh92Ahbtm48nie5NXCkLNlYzP1IPWYF3MBFhIDNy34xRwM2CGpm0LJh6DG5ogf8uanboVryK9ESInWnYlZ+/j9k8819x/UiVzfg4Hn98OF6lnepFJryQo9i5w6xLm/JFK6822u65ZiWN92SUBMk1TpSDokWU+4jEnlbBktFGn6Fi/thaQC/X8ITKu6Z18fybWijSNyENmin+M1hZSdId8NLmSiU4YMlDDn9jkaZCrqliqNZUgcgdpFBZjeQYOP3ecUQ+PrIIVa4HoDLmVBD6+J9SJaD4Ayk3MvBtSgUUjfKz7cae6TcU8QqFey5xlsnx6RfL84CIYvNJo+l4uH+U7MznUGVq5rJxlFMUvyJ0OgzK6fjM22Ixu9w==",
          "fingerprint": "e5cc118418f926436af5990b363911d898f5309731946d2d37c51bc7b2cf24e9",
          "type": "client"
        }
      ]
    }

**Comment by pcdummy** [comment]
This has been implemented and can be closed.
