### ISSUE TITLE
Cannot move to another machine with error: Permission denied

### ISSUE THREAD

**Issue by ngovanmao** [lxc/lxd#4701]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.13.0-41-generic 
   * LXC version: 2.0.11
   * LXD version: 2.0.11
   * Storage backend in use:

# Issue description

Live migration for a container first (ubuntu:16.04) from one PC (edge1) to another PC(name: edge2) is failed with the following command
```
lxc move first edge2:firstMoveTo2
```
Error messages (complete log is attached [lxd_migration.log](https://github.com/lxc/lxd/files/2141362/lxd_migration.log)):
```
error: Failed container creation:

 - https://172.18.37.105:8443: migration dump failed
(01.080421) Error (compel/src/lib/infect.c:633): Unable to connect a transport socket: Permission denied
(01.080437) Error (compel/src/lib/infect.c:559): Can't inject syscall blob (pid: 18280)
(01.080439) Error (compel/src/lib/infect.c:1313): munmap for remote map 0x7f5ec3e57000, 110592 returned 11
(01.080440) Error (criu/cr-dump.c:1283): Can't infect (pid: 18280) with parasite
(01.098423) Error (compel/src/lib/infect.c:341): Unable to detach from 18280: No such process
(01.098595) Error (criu/cr-dump.c:1709): Dumping FAILED.
```
The suspected error is CRIU at either the source or the destination node required root to checkpoint/restore a checkpointed container.
I try to run lxc command with sudo, the same fault still occurs.
The CRIU version: 3.8.1 in both nodes.
Please tell me how to fix this issue? 
Thank you.

# Steps to reproduce

 1. Step one: add remote host via lxc remote add 
 2. Step two: create a container at the source node via lxc launch
 3. Step three: migration with command lxc move

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [yes] Container log (`lxc info NAME --show-log`)
[lxc_info.log](https://github.com/lxc/lxd/files/2141378/lxc_info.log)

 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by brauner** [comment]
@adrianreber, if you have a second, ever seen anything like this? You don't need to spend a lot of time. Just in case you've seen this before.

**Comment by stgraber** [comment]
LXD always runs CRIU as root so that's not the problem.

It'd be good to know what PID 18280 is in this case. It guess it could be something like no-new-privs getting in the way or something like that.

Closing the issue as there's nothing actionable for LXD itself, this is a CRIU/kernel issue, but I'm still interested in hearing from @adrianreber about potential causes.

**Comment by adrianreber** [comment]
And another one https://github.com/checkpoint-restore/criu/issues/439

**Comment by stgraber** [comment]
It may be worth trying a newer CRIU just to make reporting issues upstream easier.

The LXD version won't matter, we've not changed the way we interact with CRIU much at all in the past two years, all the dump/restore logic is in CRIU.

**Comment by adrianreber** [comment]
CRIU cannot dump raw sockets and I am pretty sure dhclient opens a raw socket. So please try to disable dhclient in your container.
