### ISSUE TITLE
Unable to Run LXD on Arm64 emulator

### ISSUE THREAD

**Issue by sarayuks** [lxc/lxd#4714]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

I have qemu for arm64 running on my debian VM. I was able to generate the toolchain for arm64 using yocto and cross compile the LXD for my arm64 setup on qemu . I transferred the files and libraries to run lxd on the qemu setup how ever when i execute LXD i am seeing the below error.

root@ls1043ardb:/dev/temp#  ./lxd init
Error: Failed to connect to local LXD: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: no such file or directory
root@ls1043ardb:/dev/temp# 

Kindly let me know if i am missing something ? 
What issue with my setup could cause this problem?
How can i fix/workaround this issue ?

# Steps to reproduce

 1. Download LXD code.
 2. Set all the required go env variable to cross compile LXD.
 3. Transfer generate binary files and library to the guest.
 4. Run lxd init

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
You need to run `lxd` in one terminal which runs the actual daemon, then in another terminal you can run `lxd init` to talk to the daemon and configure it.
