### ISSUE TITLE
Where does LXD store it's profiles?

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#4715]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 3.0.1
   * LXD version: 3.0.1
   * Storage backend in use: ZFS

# Issue description

Hi, 

Could you please direct me as to where LXD stores it's profiles in case you want to recover or backup the profiles you created?

**Comment by simos** [comment]
Profiles are stored in the LXD database.

If you use the snap package, it's in `/var/snap/lxd/common/lxd/database/local.db`

If you use the deb package, it's somewhere inside `/var/lib/lxd/`.

You can view the database file with `sqlitebrowser`.

**Comment by stgraber** [comment]
`lxc profile show` and `lxc profile edit` can be used for backup and restore. Otherwise make sure to backup the database directory so you can restore it in its entirety should that be needed.
