### ISSUE TITLE
GUI Snap apps

### ISSUE THREAD

**Issue by gmistick** [lxc/lxd#4717]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04 (Running LXD 3)
 * The output of "lxc info"

config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFejCCA2KgAwIBAgIRAOSAW2wRuQSy7Zssh5nxcs0wDQYJKoZIhvcNAQELBQAw
    QzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEjMCEGA1UEAwwacm9vdEB5
    ZWNoaWVsLUxhdGl0dWRlLTc0OTAwHhcNMTgwNjEwMDgzNzA0WhcNMjgwNjA3MDgz
    NzA0WjBDMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMSMwIQYDVQQDDBpy
    b290QHllY2hpZWwtTGF0aXR1ZGUtNzQ5MDCCAiIwDQYJKoZIhvcNAQEBBQADggIP
    ADCCAgoCggIBAMAv/7Tt2iDe7BUOrNufrM+JLL6FPh2YLyFdHSBIBYCdXIr1IDtE
    0bnCxbF1vjj1zJdE/5l+LhhH+6qVnLuXo8wLpqZVZ2Sk/p7w/ptgr9lX2vJhCQm2
    fZVzu2Lww6KBMjySynkPRIolgDY0U/6Q2EZpwYB8maV1pz2K2hwEJigb6F3T79ba
    0BYFzNt/kY7PLz3ZgOp0J11URJxM7+RVf0eXG1UODS4h1+FHJTXvrxre4i+xklMA
    dAJ1dUI7wO33z14DkmM+LDeVwe/H4FRz9b3pHchzZvFSsHkQJ69ligQoxeY9Bvkz
    lFFVYrV5Njb9OAVMvvf6PLqtpXoPLe2SIp8rp/xH451K3RNuDqCUORPDA+df8MtL
    dh8kM6dLAen9aTlDoWo9fie0CWN2EUdK8UVQJv2hgBj2obU6xzAhLAyUD6GEI38G
    +QNoCJUluXt3ZM+rJvdMqYGkUGxz9R/pvHS+HtzoG3Ues6cB17kbkRJEXiNA/vAu
    mYiIHdSBARLXbcoZXb1B7wC2KSsr/eLoDJH+tQ0w21vvILWKAj82Y1e5NI83vowL
    R9qzgLdTRz+jxCLdSxMmEG2UnjdSOqSCGvxeIGBUcarVyyoISz+8dFOp7BB3MBZc
    MO9uPhEjHW5HSlDKqu0Gc/TMpmnTBRTaBEcKXzl1IVsyDrNysm0M+7sbAgMBAAGj
    aTBnMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMB
    Af8EAjAAMDIGA1UdEQQrMCmCFXllY2hpZWwtTGF0aXR1ZGUtNzQ5MIcECldyiIcE
    rBEAAYcECggABjANBgkqhkiG9w0BAQsFAAOCAgEAthXhLeYOkO8VJQeIDpcdF6nC
    3R9RtDhPry96u1T3rQdb2rRDFpHaiholLzRqkZFZft/e/l3QjilFPRkfWUhWVxBw
    gVHxcT4VZ6lxFy8Giw/PA11lSN6mYEODwniBPxmnWoF6mskkHE3CyqQD9LKJPztM
    so34JRKDmulF/Cs5/QYpYG6DKxSz6io/uCpmZeIBVQidAy7LcLwKdipSohzRiK1w
    AB4I5tcxD9fh4J+Rl+EZm5u7Xgi+gG+FbvYROKvNHwOjbveJKWnKGio89eUnrZCs
    jw4lDCqx01PixAJ+cUM5ECSsiO+iSXFknAu6phg/j7Y0PDRwDHjfhEGfNmYX6QD8
    mIC0kRakqbfhXpc6jk8uy64J1KOFw27BcCaFA3/Ozdnq1Uw6NYscE2l2SNXyiMbh
    5smTCA9S5ow6EtCj5cuR2EQiNPk2ScVZqGmLOtSkollR0IBdY0PMQsanuv3YjZ0d
    JCLnoiW77BLX3IZi1QRJxE1u64/m0sWO/980LscVKWnya6ZKFsdDJAv4rJllRYxm
    i9BTVY/q+WNqc1NGMokvrSrLqFuYANqXK8PMnh8j1kg2R+8pDRnAQ5jw43UibcLi
    cv9R572bu5hsEiiZUNGtlVQmGIUO7TsLWEqlVlfFjG8UZcz5x4EWZQBKkPY0nKiH
    LPfpYI8f3MMtEfEoC0I=
    -----END CERTIFICATE-----
  certificate_fingerprint: c8374e61a302704bfa3733ae17472b9b0acd404105b78ce203a66bec44806013
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-128-generic
  server: lxd
  server_pid: 17162
  server_version: "3.2"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu20
  server_clustered: false
  server_name: yechiel-Latitude-7490

# Issue description

I'm trying to run Snap apps that require X11.
I added the host /tmp/.X11 as a device, and i can run gui apps within the container, but if i want to run snap gui apps it fails.
in essence, the Abstract X11 socket is unreachable ( 
connect(3, {sa_family=AF_LOCAL, sun_path=@"/tmp/.X11-unix/X0"}, 20) = -1 ECONNREFUSED (Connection refused)
) 

**Related discussion:**
https://discuss.linuxcontainers.org/t/cant-get-snap-gui-apps-notepadqq-and-firefox-to-run-in-lxd-lxc-container/1884/5

# Steps to reproduce

 1. create container
lxc launch ubuntu:16.04 testing
 2. Attach devices
lxc config device add testing X0 disk path=/tmp/.X11-unix/X0 source=/tmp/.X11-unix/X0 permission="0666"
lxc config device add testing Xauthority disk path=/home/ubuntu/.Xauthority source=/home/yechiel/.Xauthority mode="0666"
lxc config device add testing mygpu gpu

 3. exec into container, install snap xbill-xaw and try to run

 lxc exec testing -- sudo --login --user ubuntu /bin/bash
sudo snap install xbill-xaw

snap run --strace="-ffe trace=connect" xbill-xaw

/usr/bin/strace: Process 15260 attached
[pid 15260] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=15260, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
/usr/bin/strace: Process 15261 attached
/usr/bin/strace: Process 15262 attached
/usr/bin/strace: Process 15263 attached
/usr/bin/strace: Process 15264 attached
[pid 15264] +++ exited with 0 +++
[pid 15263] +++ exited with 0 +++
[pid 15262] +++ exited with 0 +++
[pid 15261] +++ exited with 0 +++
connect(3, {sa_family=AF_LOCAL, sun_path=@"/tmp/.X11-unix/X0"}, 20) = -1 ECONNREFUSED (Connection refused)
connect(3, {sa_family=AF_LOCAL, sun_path="/tmp/.X11-unix/X0"}, 110) = -1 ENOENT (No such file or directory)
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
syscall_18446744073709551615(0x10, 0x3, 0, 0, 0x7f9bbee71780, 0x1) = -1 (errno 1)
Error: Can't open display: :0
+++ exited with 1 +++

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by simos** [comment]
Snaps in LXD containers cannot access bind-mounted resources like `/tmp/.X11-unix/X0` because the snaps have a separate `/tmp/` than the containers `/tmp/`. It might work if you put these file in $HOME in the container.

See #4718 for a relevant report. LXD 3.2 (snap) supports Unix sockets using the `proxy` device. It is almost there but I believe it has an issue with permissions.

See also the updated guide for GUI LXD containers, https://blog.simos.info/how-to-easily-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop/
