### ISSUE TITLE
proxy device needs keys for uid/gid/mode (for Unix sockets)

### ISSUE THREAD

**Issue by simos** [lxc/lxd#4718]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails: N/A
   * Kernel version: 4.13
   * LXC version: 3.2
   * LXD version: 3.2
   * Storage backend in use: zfs

# Issue description

The new `proxy` device allows the forwarding of network connections, and until recently, also supports Unix sockets. However, with Unix sockets there is a need to be able to specify the ownership (uid/gid) and mode (as in 0777).

# Steps to reproduce

 1. `lxc launch ubuntu:18.04 proxy`
 2. `lxc config device add proxy X0 proxy connect=unix:/tmp/.X11-unix/X0 listen=unix:/tmp/.X11-unix/X0 bind=container`
 3. `lxc exec proxy -- ls -l /tmp/.X11-unix/`

## What appears

    srwxr-xr-x 1 root root 0 Jul  2 17:38 X0

## What should have appeared

    srwxrwxrwx 1 nobody nogroup 0 Jul  2 14:56 /tmp/.X11-unix/X0

# Information to attach

 - [x] Any relevant output

Here is the error in trying to access `/tmp/.X11-unix/X0`.

```bash
ubuntu@proxy:~$ strace -e trace=connect xclock
connect(3, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X0"}, 20) = -1 ECONNREFUSED (Connection refused)
connect(3, {sa_family=AF_UNIX, sun_path="/tmp/.X11-unix/X0"}, 110) = -1 EACCES (Permission denied)
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(3, {sa_family=AF_INET, sin_port=htons(6000), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 ECONNREFUSED (Connection refused)
Error: Can't open display: :0
+++ exited with 1 +++
ubuntu@proxy:~$ 

```

Here is how it looks when you try from [a `gui` container](https://blog.simos.info/how-to-easily-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop/).

```bash
ubuntu@gui:~$ strace -e trace=connect xclock
connect(3, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X0"}, 20) = -1 ECONNREFUSED (Connection refused)
connect(3, {sa_family=AF_UNIX, sun_path="/tmp/.X11-unix/X0"}, 110) = 0

```

**Comment by brauner** [comment]
Are you writing a patch or should I take it?

**Comment by brauner** [comment]
@stgraber, we need a way to specify independent `uid`, `gid`, and `mode` for `listen` and `connect`. The most obvious way of doing it would be:
```diff
diff --git a/lxd/container.go b/lxd/container.go
index b5ee111a8..df5b044e7 100644
--- a/lxd/container.go
+++ b/lxd/container.go
@@ -229,8 +229,20 @@ func containerValidDeviceConfigKey(t, k string) bool {
                switch k {
                case "listen":
                        return true
+               case "listen.gid":
+                       return true
+               case "listen.uid":
+                       return true
+               case "listen.mode":
+                       return true
                case "connect":
                        return true
+               case "connect.gid":
+                       return true
+               case "connect.uid":
+                       return true
+               case "connect.mode":
+                       return true
                case "bind":
                        return true
                default:
```
That would obviously leave `listen` and `connect` to be in a double role as both a namespace and a property which is not ideal. Would be cleaner if they'd be `listen.address` and `connect.address`. Thought that might need property translation code on newer LXD versions.

**Comment by brauner** [comment]
Or in other words @stgraber, other ideas?

**Comment by simos** [comment]
I had a quick look.

```diff
diff --git a/lxd/container.go b/lxd/container.go
index b5ee111a..f6ae085f 100644
--- a/lxd/container.go
+++ b/lxd/container.go
@@ -233,6 +233,12 @@ func containerValidDeviceConfigKey(t, k string) bool {
                        return true
                case "bind":
                        return true
+               case "uid":
+                       return true
+               case "gid":
+                       return true
+               case "mode":
+                       return true
                default:
                        return false
                }
@@ -458,6 +464,10 @@ func containerValidDevices(db *db.Cluster, devices types.Devices, profile bool,
                        if m["connect"] == "" {
                                return fmt.Errorf("Proxy device entry is missing the required \"connect\" property.")
                        }
+
+                       if m["connect"][0:5] != "unix:" &&  (m["uid"] != "" || m["gid"] != "" || m["mode"] != "") {
+                               return fmt.Errorf("Proxy device entry should not specify uid, gid or mode if the \"connect\" property is not a Unix socket.")
+                       }
                } else if m["type"] == "none" {
                        continue
                } else {
```

**Comment by brauner** [comment]
I was somehow under the impression that we create the connect socket as well.

**Comment by brauner** [comment]
@simos, time to test https://github.com/lxc/lxd/pull/4722 fulfills your use-case?

**Comment by simos** [comment]
I spent a couple of hours trying this branch.

I managed to get GUI LXD containers to work with Unix sockets. Both sockets and named sockets in the container was OK.

What I did not manage, was to get the host to accept the connections from the containers so that the containers do not need to specify a cookie (`.Xauthority` and PulseAudio cookie). This is something for me to investigate further. For others trying as well, you have a cookie issue if you get the error `No protocol specified` in X11 apps.

I did not manage to get GUI snaps to work yet. An important thing missing, was some small snap for tests, one that depends only on Xlib. I published `xclock-simosx` to the Snap Store for my tests.

A small patch, the `mode` should be read as octal, not decimal.

```diff
diff --git a/lxd/main_forkproxy.go b/lxd/main_forkproxy.go
index 42b2a135..eb36798b 100644
--- a/lxd/main_forkproxy.go
+++ b/lxd/main_forkproxy.go
@@ -497,7 +497,7 @@ func (c *cmdForkproxy) Run(cmd *cobra.Command, args []string) error {
 
            var listenAddrMode os.FileMode
            if args[8] != "" {
-               tmp, err := strconv.Atoi(args[8])
+               tmp, err := strconv.ParseUint(args[8], 8, 0)
                if err != nil {
                    return err
                }
```

**Comment by stgraber** [comment]
@simos Did you try `xhost +`? That's a bit excessive as far as permissions but since the average X server doesn't actually listen on a publicly available socket, this should be fine.

**Comment by brauner** [comment]
Would'n bind-mounting `.Xauthority` into the container work?

**Comment by stgraber** [comment]
I'd be fine with adding `security.uid` and `security.gid` type properties to the proxy device to control privilege dropping.

**Comment by brauner** [comment]
@stgraber, please merge the other branch first though.

**Comment by simos** [comment]
@brauner, snap packages that do not have the `classic` confinement, cannot currently access any dot files in the home directory. Here is [a recent discussion about a new interface (in snapcraft)](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1607067) should be made soon so that a snap packager can individually request to access, for example, `~/.gitconfig`. But for ~/.Xauthority and similar files, any configuration should somehow go into the shared [desktop-helpers](https://github.com/ubuntu/snapcraft-desktop-helpers). I do not know whether it is technically possible (give all newly created snaps access to `${REALHOME}/.Xauthority` or whether they (Snapcrafters) will be OK to venture there.
In addition, a snap to access (non hidden) files in $(HOME) it needs to use the `[home]` plug, and it may not have it.
