### ISSUE TITLE
REST API: add support for bulk query for all CT Pids

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#4724]
Add support for bulk querying list of container names with their corresponding init pids.

Current behaviour  forces you to ask this info per container, for 500+ CTs this takes some time.

**Comment by stgraber** [comment]
Unfortunately that particular query isn't as easy and cheap as it sounds as LXD itself doesn't know the PID of those containers and so will internally need to reach to liblxc for every container which is where most of the delay from querying container info comes from.

There is certainly a bit of overhead in doing an API call for every container, but based on previous testing, we're talking in the 5% range here, so not quite as big an improvement as you might be hoping for.

What exactly do you need the PID for in your case?

**Comment by s3rj1k** [comment]
@stgraber I am using this to expose cgroup metrics to gather accounting data, statistics that LXD provides via API sadly are not enough for me.

**Comment by stgraber** [comment]
@s3rj1k ok, then if you're already running scripts outside of LXD on the host you could likely just go fish out the paths under `/sys/fs/cgroup` directly. Either by assuming that the entry will start with the container name (may be followed by -1, -2, ...) or if you want to parse /proc/PID/cgroup to be completely sure to get the right cgroup, a cheap-ish solution is to locate the `[lxc monitor]` process for the container and then find its only child which would be the init process of the container.

That effectively lets you get the PID information for the container without ever having to talk to LXD or liblxc.

**Comment by stgraber** [comment]
A pretty simple approach is:

```
LXCPATH=${1:-}

ps aux | grep '\[lxc monitor\]' | while read line
do
    set -- ${line}

    [ "${LXCPATH:-$13}" != "$13" ] && continue

    NAME="${14}"
    PID="$(pgrep -P ${2})"

    echo "${NAME} -> ${PID}"
done
```

**Comment by stgraber** [comment]
I'm closing this issue as we'll not be adding a new API just to get container to pid mapping.

I'm however open to expanding the /1.0/containers?recursion API to allow the inclusion of the state of all containers in there (recursion=2) which would allow most cases of `lxc list` to work with a single, horribly slow query. That wouldn't really make things faster in this particular case though.

We'd also certainly consider adding more fields to the existing state API, possibly exporting the information you need in there so you don't need to go parse cgroups yourself (though that'll depend on exactly what metric you're extracting).
