### ISSUE TITLE
Can't attach ceph volume to container in clustered lxd setup

### ISSUE THREAD

**Issue by Spunge** [lxc/lxd#4736]
# Required information

Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

driver: lxc
driver_version: 3.0.1
kernel: Linux
kernel_architecture: x86_64
kernel_version: 4.15.0-23-generic
server: lxd
server_pid: 46966
server_version: "3.2"
storage: zfs
storage_version: 0.7.5-1ubuntu15
server_clustered: true

```
$> lxc storage list
+---------+-------------+--------+---------+---------+
|  NAME   | DESCRIPTION | DRIVER |  STATE  | USED BY |
+---------+-------------+--------+---------+---------+
| default |             | zfs    | CREATED | 4       |
+---------+-------------+--------+---------+---------+
| lxd     |             | ceph   | CREATED | 1       |
+---------+-------------+--------+---------+---------+

$> lxc storage volume list lxd
+--------+------+-------------+---------+------------+
|  TYPE  | NAME | DESCRIPTION | USED BY |  LOCATION  |
+--------+------+-------------+---------+------------+
| custom | test |             | 0       | host-0001  |
+--------+------+-------------+---------+------------+
| custom | test |             | 0       | host-0002  |
+--------+------+-------------+---------+------------+
| custom | test |             | 0       | host-0003  |
+--------+------+-------------+---------+------------+
```

# Issue description

When creating a new storage volume on a ceph storage pool (even with --target specified), the ceph storage driver creates a 'volume' on every host in the cluster.

When i try to attach this volume to a host, i get the following error:

```
$> lxc storage volume attach lxd test test test /mnt
Error: more than one node has a volume named test
```

# Steps to reproduce

 1. Setup clustered lxd
 2. Create ceph storage pool 
```
lxc storage create lxd ceph --target host-0001
lxc storage create lxd ceph --target host-0002
lxc storage create lxd ceph --target host-0003
lxc storage create lxd ceph
```
 3. Create storage volume on the ceph pool
```
lxc storage volume create lxd test
```
 4. Try to attach the storage volume to a container (lxc storage volume attach)
```
lxc storage volume attach lxd test container_name disk_name /path
```

Am i missing something obvious?

**Comment by stgraber** [comment]
Reproduced the issue here, will work on a fix.

It's on purpose that more than one node has the volume, it'd be a bug if that wasn't the case, so hopefully easy to fix.
