### ISSUE TITLE
Provide unique product_uuid for container

### ISSUE THREAD

**Issue by magne** [lxc/lxd#4737]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info":
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
...
    -----END CERTIFICATE-----
  certificate_fingerprint: ...
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-23-generic
  server: lxd
  server_pid: 17558
  server_version: 3.0.1
  storage: btrfs
  storage_version: 4.15.1
  server_clustered: false
  server_name: ubnt-srv
```

# Issue description

The UUID available at `/sys/class/dmi/id/product_uuid` (and `/sys/devices/virtual/dmi/id/product_uuid`) is sometimes used to identify the node (most notable by Kubernetes), and is supposed to be unique to each machine (or in this instance, container). In LXD containers, the UUID is the same on all containers on the same host, and seem to be the same as the host's. It is also only available in containers running in privileged mode.
This UUID should be generated at container creation, so that it is unique for each container. Or it could be specified as a container configuration. KVM, for example, has the `--uuid` option that sets this uuid. It should also be available to non-privileged containers.

# Steps to reproduce

 1. Start two containers (tested with ubuntu 18.04)
  - `lxc launch ubuntu:18.04 c1`
  - `lxc launch ubuntu:18.04 c2`
 2. Display product UUID:
  - `lxc exec c1 cat /sys/class/dmi/id/product_uuid`
     will display `cat: /sys/class/dmi/id/product_uuid: Permission denied`
 3. Enable privileged:
  - `lxc config set c1 security.privileged true && lxc restart c1`
  - `lxc config set c2 security.privileged true && lxc restart c2`
 4. Again, display product UUID:
  - `lxc exec c1 cat /sys/class/dmi/id/product_uuid`
  - `lxc exec c2 cat /sys/class/dmi/id/product_uuid`
  - `sudo cat /sys/class/dmi/id/product_uuid`
  All of these will display the same UUID.

**Comment by brauner** [comment]
This is a non-namespaced file meaning it is unique per physical host not per container. Changing this even with a privileged container should be a no-no. Some of this information is very much tied to the bios and actual hardware so I expect any argument that we can make upstream to namespace this to result in a metaphorical slap in the face.

**Comment by brauner** [comment]
For virtual machines this case is different since they can fake devices and also run a different kernel.
