### ISSUE TITLE
LXC&D was just automatically upgraded to v3 from v2, on Ubuntu 16.03

### ISSUE THREAD

**Issue by akarelas** [lxc/lxd#4744]
Was this supposed to happen? All I did was apt update and then apt dist-upgrade.

See here for more information:
https://discuss.linuxcontainers.org/t/lxd-2-0-on-ubuntu-16-04-got-automatically-upgraded-to-lxd-3-0-was-that-supposed-to-happen/2188
and
https://discuss.linuxcontainers.org/t/my-lxd-2-0-stopped-working-today-after-an-apt-update-of-ub-16-04/2187/5

**Comment by akarelas** [comment]
here's my /etc/apt/sources.list.d/ubuntu-lxc-ubuntu-lxd-stable-xenial.list:
```
# deb http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu xenial main
# deb-src http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu xenial main
```
i don't know why it has # signs in front of the lines

**Comment by akarelas** [comment]
Here's: apt policy lxd
```
lxd:
  Installed: 3.0.1-0ubuntu1~16.04.2
  Candidate: 3.0.1-0ubuntu1~16.04.2
  Version table:
 *** 3.0.1-0ubuntu1~16.04.2 100
        100 http://mirror.hetzner.de/ubuntu/packages xenial-backports/main amd64 Packages
        100 http://de.archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.11-0ubuntu1~16.04.4 500
        500 http://mirror.hetzner.de/ubuntu/packages xenial-updates/main amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
     2.0.2-0ubuntu1~16.04.1 500
        500 http://mirror.hetzner.de/ubuntu/security xenial-security/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     2.0.0-0ubuntu4 500
        500 http://mirror.hetzner.de/ubuntu/packages xenial/main amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
```

Have I done something wrong? Is this a bug?

**Comment by stgraber** [comment]
Responded on the forum thread as that's more applicable than here, you were on LXD 2.21, not LXD 2.0.x as the forum title suggests and yes, it's normal for LXD 2.21 users (those who opted into major release backports through xenial-backports) to get upgraded to LXD 3.0.1.
