### ISSUE TITLE
No instructions presented anywhere on how to keep LXD containers working after the auto-upgrade to v3

### ISSUE THREAD

**Issue by akarelas** [lxc/lxd#4745]
I had Ubuntu 16.04 with LXD 2.11, and today LXD got automatically upgraded to v3.

My LXD containers stopped working properly, and I was given no instructions on how to make them work again after the upgrade.

Isn't this a bug?

Thank you.

**Comment by stgraber** [comment]
Let's please keep the discussion in one place.

https://discuss.linuxcontainers.org/t/my-lxd-2-0-stopped-working-today-after-an-apt-update-of-ub-16-04/2187/15
