### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by sh2515** [lxc/lxd#4748]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description
On lxd.readthedocs.io the download the document doesn't work properly. It only downloads 2 pages not the whole version
A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one click on the download as PDF or epub
 2. Step two open downloaded file
 

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
I can't speak for the epub download but pdf does work fine for me, I get this URL:

    http://readthedocs.org/projects/lxd/downloads/pdf/latest/

Note that this is on readthedocs.org so we don't actually control any of that, let me know if the link above breaks as well for you, if so, maybe readthedocs has a bugtracker somewhere.

**Comment by sh2515** [comment]
Hi I tried the link you gave and it gave me 5 pages and a few blank pages. Can you try your download again to see if it is at my 3nd that the fault is happening please?
Thanks
S

On July 6, 2018 1:19:31 PM UTC, "Stéphane Graber" <notifications@github.com> wrote:
>I can't speak for the epub download but pdf does work fine for me, I
>get this URL:
>
>    http://readthedocs.org/projects/lxd/downloads/pdf/latest/
>
>Note that this is on readthedocs.org so we don't actually control any
>of that, let me know if the link above breaks as well for you, if so,
>maybe readthedocs has a bugtracker somewhere.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lxc/lxd/issues/4748#issuecomment-403031857

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stgraber** [comment]
Hmm, yeah, looks like that particular readthedocs feature is broken... I've turned it off entirely now so that you at least don't get an old (October 2016) empty pdf.

**Comment by stgraber** [comment]
Again, this stuff is hosted and provided by readthedocs, we have no control over what's run on their server and so can't fix it ourselves. Disabling the feature until they fix it is the only thing we can do.
