### ISSUE TITLE
cannot "su" to another user in alpine container

### ISSUE THREAD

**Issue by melato** [lxc/lxd#4756]
* Distribution: Ubuntu
 * Distribution version: Ubuntu 18.04 LTS
 * The output of "lxc info":
config:
  core.https_address: '[::]:8399'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.80.10:8399
  - 10.27.76.1:8399
  - '[fd42:582c:d2fc:9f0f::1]:8399'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
	<removed>
    -----END CERTIFICATE-----
  certificate_fingerprint: 75f40dacb33e7956372f890fdf9e5e47a3a73cff820c484cbdbe4bcda6c6e262
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-24-generic
  server: lxd
  server_pid: 2063
  server_version: "3.2"
  storage: zfs
  storage_version: 0.7.5-1ubuntu15
  server_clustered: false
  server_name: kerasi
# Issue description
I setup a new alpine container, created a user and tried to su as that user, but I get an error:
su: can't execute '/bin/sh': Permission denied

This seems to be a problem with the alpine image.  It also happens in a Ubuntu 16.04 system with the deb-based lxd (2.0.11).

# Steps to reproduce
1. lxc launch images:alpine/3.7 a1
2. lxc exec a1 ash
3. adduser u1
4. enter a password for the new user
5. su u1
Result:
su: can't execute '/bin/sh': Permission denied

I also cannot ssh to that container as that user.  In addition to the /bin/sh permission denied, I get a permission denied for cd /home/u1

**Comment by stgraber** [comment]
The issue appears to be a bad umask, `chmod 755 /` should fix this until the images are corrected.

**Comment by stgraber** [comment]
Actually, the issue is that the upstream tarballs for Alpine have that wrong ownership for /...
Going to add a workaround in distrobuilder for it, but it's weird that nobody else ran into that.

**Comment by stgraber** [comment]
Fix pushed and new images building now.

**Comment by stgraber** [comment]
All images rebuilt, should be available on the mirrors within the next 30min or so.

**Comment by melato** [comment]
This also fixes the ssh problem.

**Comment by melato** [comment]
Entered an issue on alpinelinux:  https://bugs.alpinelinux.org/issues/9066
