### ISSUE TITLE
SNAP vs. APT question

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#4757]
As I recall LXD switched from APT to SNAP as of LXD-3.0 and...

Now I'm seeing LXD 3.1 APT packages.

Clarify...

1) Specify the preferred method to install LXD - SNAP or APT.

2) If SNAP is used, verify if it's safe to remove all LXD + LXC APT packages.

LXC packages - lxc-common + lxcfs + liblxc1.

Thanks.

**Comment by stgraber** [comment]
Where did you see LXD 3.1 .deb packages? We certainly didn't make any.

What you can find are LXD 3.0.1 debs (bugfix release of 3.0.0) and those are available in bionic-updates and xenial-backports. LXD 3.1 and 3.2 were only made available as snaps.

You can use apt to install LXD 3.0.x on Ubuntu 18.04 or 16.04 (with backports). For anything else, you need the snap. When installing the snap, run `lxd.migrate` which will move any data that you may have with the deb version and will then remove the packages for you.

If you've never used the deb at all, then it's also safe to just remove those yourself, I usually do:

    apt remove --purge lxd lxd-client liblxc1 lxcfs

To clean everything from the system and only have the snap.

**Comment by davidfavor** [comment]
That's what I thought.

Ugh... Looks like OVH private APT cache nonsense...

I wonder how in the world they generated LXD packages like this... OVH doesn't strike me as having this level of in house expertise...
```
net10 # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

net10 # apt-cache policy lxd
lxd:
  Installed: (none)
  Candidate: 3.0.1-0ubuntu1~18.04.1
  Version table:
     3.0.1-0ubuntu1~18.04.1 500
        500 http://ubuntu.mirrors.ovh.net/ubuntu bionic-updates/main amd64 Packages
     3.0.0-0ubuntu4 500
        500 http://ubuntu.mirrors.ovh.net/ubuntu bionic/main amd64 Packages
```

**Comment by davidfavor** [comment]
Oh... I should have said LXD 3.0.1 rather than 3.1 which still doesn't explain why OVH is packaging 3.x packages.

**Comment by davidfavor** [comment]
Ah... Now I got it...

Thanks!

**Comment by davidfavor** [comment]
Note to those managing many machines running many LXD containers.

Many hosting providers plumb in their own repository (package) proxies, to supposedly optimize bandwidth for package installation. In reality, this will only save a small amount of bandwidth + creates problems when (as this ticket explores) hosting providers incorrectly add backports to their default proxy configurations.

Adding a machine setup step to remove any hosting provider APT/RPM/YUM proxies resolves this problem, by only using pristine repositories.

With this added machine setup step, you'll never have to worry about clashes between SNAP + your native package management system (APT/RPM/YUM) which keeps life simple.

**Comment by bcronje** [comment]
> Where did you see LXD 3.1 .deb packages? We certainly didn't make any.
> 
> What you can find are LXD 3.0.1 debs (bugfix release of 3.0.0) and those are available in bionic-updates and xenial-backports. LXD 3.1 and 3.2 were only made available as snaps.
> 
> You can use apt to install LXD 3.0.x on Ubuntu 18.04 or 16.04 (with backports). For anything else, you need the snap. When installing the snap, run `lxd.migrate` which will move any data that you may have with the deb version and will then remove the packages for you.
> 
> If you've never used the deb at all, then it's also safe to just remove those yourself, I usually do:
> 
> ```
> apt remove --purge lxd lxd-client liblxc1 lxcfs
> ```
> To clean everything from the system and only have the snap.

@stgraber you guys really need to put this info in the documentation. I've just spend a couple of hours trying to figure out how to upgrade from 3.0.1 that gets installed by default in Ubuntu 18.04 to the snap version 3.5. Worst was just uninstalling lxd deb alone and snap install lxd ended up with a broken lxc, which still pointed to 3.0.1.
