### ISSUE TITLE
lxd error while using other fuse filesystem

### ISSUE THREAD

**Issue by drscrewdriver** [lxc/lxd#4758]
# Distribution:
 lxd error while using outer fuse filesystem
# Distribution version: 
lxd 3.0.1 build with aur on manjaro

 driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.16.18-1-MANJARO
  server: lxd
  server_pid: 3696
  server_version: "3.2"
  storage: zfs
  storage_version: 0.7.9-1
  server_clustered: false
  server_name: joshua-server
# Issue description

I just add mount remote rclone filesystem on system . then action cp a file from rclone file system to zfs
share with lxd storage backend ,lxc exec seems work ,but command such as lxc list stuck, can't reboot lxd container with lxc restart . I tried mv from fuse rclone system to independence xfs system on inedepend disk out of  zfs pool but fail again

# Steps to reproduce

 1. confirm lxd is runing,with serveal runing container or not
 2. mount a fuse remote file system with rclone
 3. mv or copy files on fuse remote file system out
4. try' lxc list ' container runing infomation should not list and stuck
5.the runing state of container after lxc (start|stop| resart ) is unknown

**Comment by stgraber** [comment]
This issue is confusing, your kernel doesn't allow for unprivileged fuse mounts inside containers, so I'm assuming that the fuse mounts from rclone were outside of any of the containers?

Can you paste `ps fauxww` when `lxc list` is stuck? I suspect you'll see a number of processes stuck in "D" state waiting for the kernel to move on.

**Comment by drscrewdriver** [comment]
Sure ，you are right ，will try it later asap

**Comment by drscrewdriver** [comment]
sorry，seems not reproduce the bug .
