### ISSUE TITLE
Documentation Enhancement: lxd-p2c stop container /sbin/init spinning

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#4759]
After using lxd-p2c several times on old Ubuntu Trusty machines, the resulting containers /sbin/init would spin at 100% CPU usage.

Studying **strace -p $init-pid**, then looking at a tight loop of **ps fauxww** for several minutes suggested problem related to tty[123456] being continually strobed for some sort of i/o + getty then continually died + respawned.

Fix seems to be editing /etc/init/tty*.conf files + commenting out last two lines of each file...
```
respawn
exec /sbin/getty -8 38400 ttyX
```
This seems to stop /sbin/init spinning at 100% CPU for each migrated container.

Unsure where exactly this might be documented.

Hopefully having this scrape of information will save someone hours of head scratching.

**Comment by stgraber** [comment]
What we suggested in the past is to create a post on https://discuss.linuxcontainers.org documenting what post-migration steps are needed for a particular source distribution. We can then make a single topic that refers to them all for all the different distros.

**Comment by davidfavor** [comment]
Posted to discuss as you suggested.

Thanks for the tip.

BTW, after running this fix for a day 100% CPU spin appears to have stopped permanently.
