### ISSUE TITLE
How to find location of "migration.incremental.memory.iterations"

### ISSUE THREAD

**Issue by adityacloud1** [lxc/lxd#4760]
Respected all,

My experimental setup is successfully running with LXD container migration using LXD, CRIU technique.
Please response for the following queries:

1. How to find number of pages transferred during container migration ?.

2. I want to configure number of pre-copy iterations in  "migration.incremental.memory.iterations," but unable to locate path of this variable in the system configuration files.

**Comment by brauner** [comment]
@adrianreber can likely answer `1.`.
About 2.: This is a per-container setting so:
```
 lxc config set <container-name> migration.incremental.memory.iterations <number>
```

**Comment by adrianreber** [comment]
@adityacloud1 You can either try to find stats-dump (from CRIU's dump directory) and parse it with crit (part of CRIU). Or you can look at the LXD debug log:

```
        logger.Debugf("CRIU pages written %d", written)
        logger.Debugf("CRIU pages skipped %d", skipped_parent)
```

https://github.com/lxc/lxd/blob/master/lxd/migrate_container.go#L265

**Comment by adityacloud1** [comment]
Respected @adrianreber, @brauner, thanks for prompt reply.

@adrianreber, First, I explored stats-dump located at path: /var/lib/lxd/snapshots/c1/checkpoint-2/state# gedit stats-dump . But, output is not readable as in attachment.

Then, I checked LXD log file located at:  /var/log/lxd/lxd.log, but did not get any information for CRIU pages written and skipped. 
Could, you please  elaborate the path location for LXD debug log as suggested in yours reply.
![criu-stats dump](https://user-images.githubusercontent.com/40225508/42446918-a4f1dfe0-8395-11e8-9f49-3e45da895631.png)

**Comment by adrianreber** [comment]
You probably need to start LXD differently to get debug output.

stats-dump cannot be read directly. That is protobuf file. You need, like previously mentioned, crit to read it: https://criu.org/CRIT

**Comment by adityacloud1** [comment]
Thanks sir, I got the desired result by running following command:
crit decode -i stats-dump --pretty

**Comment by adityacloud1** [comment]
@adrianreber Sir, I am performing LXD container 'c1' migration using CRIU when benchmarks (like STREAM, Web-server, Idle case, Cassandra, LMbench) are running at the container.
But, each time value of **pages written is constant** for all  cases. Please suggest for this issue.

**Comment by adityacloud1** [comment]
Yes sir, each time all values are same for the variable **"pages_written: 4883".** I don't have multiple stats-dump files.
Following are all **.img file** from the path  root@server1:/var/lib/lxd/snapshots/c1/checkpoint-2/state# ls
![stats-dump](https://user-images.githubusercontent.com/40225508/42498437-d34fdbe4-8449-11e8-8dfc-a847169a63ba.png)

And, the actual contents from **stats-dump file** are as highlighted in following screen-shot: 
![contents](https://user-images.githubusercontent.com/40225508/42498423-c97b8500-8449-11e8-8262-04817ec20c40.png)

**Comment by adrianreber** [comment]
I had a closer look and normally lxd deletes all checkpoint files including all stats-dump after a restore.

To get the detailed information about the pages written and transferred you really need to start LXD with ```--debug```. Then you will see messages like this:

```
 main.readCriuStatsDump: stats-dump payload size 30 
 main.(*migrationSourceWs).preDumpLoop: CRIU pages written 63 
 main.(*migrationSourceWs).preDumpLoop: CRIU pages skipped 0 
 main.(*migrationSourceWs).preDumpLoop: CRIU pages skipped percentage 0% 
 main.(*migrationSourceWs).preDumpLoop: Sending another header 
 main.(*migrationSourceWs).preDumpLoop: Sending another header done 
 main.(*migrationSourceWs).preDumpLoop: Doing another pre-dump in 001 
 main.(*containerLXC).Migrate: Migrating container actionscript=false created=2018-07-10T08:43:55+0000 ephemeral=false features=0 name=a1 predumpdir=001 statedir=/tmp/lxd_checkpoint_297823647 stop=false used=2018-07-10T08:43:55+0000
 main.(*containerLXC).Migrate: Migrated container actionscript=false created=2018-07-10T08:43:55+0000 ephemeral=false features=0 name=a1 predumpdir=001 statedir=/tmp/lxd_checkpoint_297823647 stop=false used=2018-07-10T08:43:55+0000
 main.readCriuStatsDump: stats-dump payload size 30 
 main.(*migrationSourceWs).preDumpLoop: CRIU pages written 6 
 main.(*migrationSourceWs).preDumpLoop: CRIU pages skipped 57 
 main.(*migrationSourceWs).preDumpLoop: CRIU pages skipped percentage 91% 
 main.(*migrationSourceWs).preDumpLoop: Memory pages skipped (91%) due to pre-copy is larger than threshold (70%) 
 main.(*migrationSourceWs).preDumpLoop: This was the last pre-dump; next dump is the final dump 
 main.(*migrationSourceWs).preDumpLoop: Sending another header 
 main.(*migrationSourceWs).preDumpLoop: Sending another header done 
```

To get more details you have to change the LXD code to extract the necessary information.

**Comment by adityacloud1** [comment]
Thanks Sir

**Comment by adityacloud1** [comment]
@adrianreber Respected Sir, any suggestion please.
