### ISSUE TITLE
Ceph's quotas support

### ISSUE THREAD

**Issue by twelfthdoctor** [lxc/lxd#4761]
I can set size of a storage volume using ZFS and btrfs, but I can't use storage volume quotas with ceph storage(however ceph itself supports disk quotas). Please add storage volume quota support to btrfs storage backend. Please check ceph's docs about quotas:
http://docs.ceph.com/docs/jewel/cephfs/quota/

**Comment by brauner** [comment]
That requires us to support `CephFS`. It won't work directly on `ext4` or `xfs`.

**Comment by stgraber** [comment]
Right, cephfs and ceph-rbd are two very different beasts, LXD uses ceph-rbd with normal filesystems on top, making its feature set equivalent to that of LVM.

**Comment by twelfthdoctor** [comment]
I.e. every container has its own RBD device?

**Comment by stgraber** [comment]
that's correct, yes

**Comment by twelfthdoctor** [comment]
But ceph let you to set size of any RBD device.

**Comment by stgraber** [comment]
Right but a container is a clone of the image it's been created from and therefore inherits the size of that image. You can change the size of newly imported images by setting the volume.size property on the storage pool.

**Comment by twelfthdoctor** [comment]
@stgraber So can I do something like that (using ceph as a storage backend)?
`lxc storage volume create default v1 size=1GB` or `lxc storage volume set default v1 size 1GB`

**Comment by stgraber** [comment]
Quota in that table refers to actual filesystem quotas, which indeed don't work with CEPH or LVM.
But the block size is something that can totally be changed:

```
root@vm01:~# lxc storage list
+--------+-------------+--------+---------+---------+
|  NAME  | DESCRIPTION | DRIVER |  STATE  | USED BY |
+--------+-------------+--------+---------+---------+
| local  |             | zfs    | CREATED | 3       |
+--------+-------------+--------+---------+---------+
| remote |             | ceph   | CREATED | 1       |
+--------+-------------+--------+---------+---------+
root@vm01:~# lxc launch ubuntu:16.04 c3 -s remote
Creating c3
Starting c3
root@vm01:~# lxc exec c3 -- df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd1       9.8G  650M  8.6G   7% /
none            492K     0  492K   0% /dev
udev            3.9G     0  3.9G   0% /dev/tty
tmpfs           100K     0  100K   0% /dev/lxd
tmpfs           100K     0  100K   0% /dev/.lxd-mounts
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  8.2M  3.9G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
root@vm01:~# lxc stop c3
root@vm01:~# lxc config device set c3 root size 20GB
root@vm01:~# lxc start c3
root@vm01:~# lxc exec c3 -- df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd1        20G  655M   18G   4% /
none            492K     0  492K   0% /dev
udev            3.9G     0  3.9G   0% /dev/tty
tmpfs           100K     0  100K   0% /dev/lxd
tmpfs           100K     0  100K   0% /dev/.lxd-mounts
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  8.2M  3.9G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
```

This must happen with the container stopped and is very much subject to failures especially if attempting to shrink the filesystem as this effectively requires the filesystem to move blocks around, possibly running out of space.

As for custom volumes, since those aren't created from an image, you can make them as small as you want and no resize happens at creation time, a resize would happen if you increase/decrease it afterwards with the same limitations as for containers (all containers using it must be stopped and shrinking may fail).

```
root@vm01:~# lxc storage volume create remote v1 size=2GB
Storage volume v1 created
root@vm01:~# lxc storage volume attach remote v1 c3 v1 /mnt/v1
root@vm01:~# lxc exec c3 -- df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd1        20G  655M   18G   4% /
none            492K     0  492K   0% /dev
udev            3.9G     0  3.9G   0% /dev/tty
tmpfs           100K     0  100K   0% /dev/lxd
tmpfs           100K     0  100K   0% /dev/.lxd-mounts
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  8.2M  3.9G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/rbd2       2.0G  3.0M  1.8G   1% /mnt/v1
```
