### ISSUE TITLE
Kernel error "task zfs:pid blocked for more than 120 seconds"

### ISSUE THREAD

**Issue by simos** [lxc/lxd#4763]
This is a ZFS-specific issue on Ubuntu 18.04. It has not been tested whether it is also an issue with upstream ZFS/SPL.

## How to reproduce

Run `lxd-benchmark launch --count 48 --parallel 12`. The issue appeared to be in 2 out of 4 attempts. 
`lxd-benchmark` would stall. After two minutes, there would be kernel errors that ZFS got stuck. 
Full details in the reports below. I understand this is not an issue with LXD but an issue that affects LXD. Feel free to close if needed.

https://github.com/zfsonlinux/zfs/issues/7659
https://github.com/zfsonlinux/zfs/issues/7691

**Comment by brauner** [comment]
Ah, good to know that there is an issue. Let's close this issue on the LXD side but good that users can search for it in the repo history. Thanks for filing against zfs!
