### ISSUE TITLE
Unable to execute LXD on Arm emulator

### ISSUE THREAD

**Issue by sarayuks** [lxc/lxd#4771]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

I have qemu for arm64 running on my debian VM. I was able to generate the toolchain for arm64 using yocto and cross compile the LXD for my arm64 setup on qemu . I transferred the files and libraries to run lxd on the qemu setup in which i have the network connection enabled but when i execute LXD i am seeing the below error.

# Steps to reproduce

 1. Start LXD daemon 
 2. Run LXD init successfully
 3. Launch a container with the below command 
root@ls1043ardb:/dev/temp# ./lxc launch ubuntu:16.04
Creating the container
Error: Failed container creation: Get https://cloud-images.ubuntu.com/releases/streams/v1/index.json: x509: failed to load system roots and no roots provided
root@ls1043ardb:/dev/temp# 

Kindly let me know if i am missing any setup

I googled for this error and found that it could be related to ca-certificate and just for testing purpose i transferred the content from /etc/ssl/* on my debian system to my arm emulator /etc/ssl folder but this did not solve the issue for me. 

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Yep, that's the Go TLS stack failing to validate the certificate, most likely because you don't have the certificates in the location it expects. I'd recommend just running LXD under strace and see where it's looking.

Closing as not a LXD bug.

**Comment by sarayuks** [comment]
Thanks for your quick response.
Can you please provide me the instructions as to how i can run LXD under strace  or point me to any documentation for the same ?

**Comment by stgraber** [comment]
Just run strace -f -p pid-of-lxd

**Comment by sarayuks** [comment]
Hi ,
I was able to run strace and i saw that the below errors are causing my LXD launch to fail. 
newfstatat(AT_FDCWD, "/home/root/.config/lxc/client.crt", 0x4420114938, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/root/.config/lxc/client.key", 0x44201149f8, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/root/.config/lxc/client.ca", 0x4420114ab8, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/root/.config/lxc/servercerts/local.crt", 0x4420114b78, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)

But i am not sure how/when to generate these files ?

Since this is an external dependency to LXD , how can i generate these file explicitly in my arm board so that the launch of LXD doesnt fail.

**Comment by stgraber** [comment]
Those are irrelevant. I told you to strace `lxd`, not `lxc`.
