### ISSUE TITLE
lxc list: split "ip4 (interface)" into separate fields

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#4785]
* LXC version: 3.2
   * LXD version: 3.2

# Issue description

I'd like to get IPv4 address in command line for feeding it to other commands But it doesn't work, because result contains interface name:
```
$ lxc list -c4 --format csv          
10.35.65.71 (eth0)
```
So maybe remove `(eth0)` from output unless `--verbose` is specified?

**Comment by techtonik** [comment]
https://askubuntu.com/questions/921110/how-do-i-get-the-ip-address-of-an-lxc-container-for-automation

**Comment by stgraber** [comment]
The recommended way to do this is by using the json output and jq where you can do any filtering you want, including complex filtering maps. We don't intend to duplicate the filtering features of something like jq in the LXD client itself.

**Comment by stgraber** [comment]
One such example with a template that's not too dissimilar from your suggestion would be:
```
stgraber@castiana:~$ lxc list --format=json snapcraft | jq -r ".[].state.network.eth0.addresses | .[0].address"
10.166.11.120
```

This particular query gets you the first address on the eth0 interface. `jq` effectively lets you see, filter and query the property tree of any JSON document and offers an interface that many are already familiar with so I don't think we need to reinvent the wheel here.

**Comment by techtonik** [comment]
`jq` is not installed by default even in Ubuntu.

**Comment by stgraber** [comment]
Sure but it's very widely available and super light, so not a big deal to install it.

**Comment by techtonik** [comment]
Why not provide identical UX to Kubernetes? https://kubernetes.io/docs/reference/kubectl/jsonpath/

**Comment by techtonik** [comment]
I need this again. LXD is not usable out of the box. It requires external utilities - either `jq` or `cut` to be present.

**Comment by tomponline** [comment]
@techtonik @stgraber could you use:

```
lxc list -c4 --format csv | awk '{print $1}'
```

**Comment by monstermunchkin** [comment]
@techtonik this should work:
```bash
a=( lxc list -c4 --format csv ) echo "${a[0]}"
```
I'm pretty sure `echo` is available on your system.

**Comment by mdraevich** [comment]
There is a solution with basic read:
```shell
container_name=<YOUR-CONTAINER-NAME>
read ip_addr _ <<< $(lxc list -c4 --format csv $container_name)
echo $ip_addr
```
