### ISSUE TITLE
Support the PROXY protocol

### ISSUE THREAD

**Issue by simos** [lxc/lxd#4786]
# Issue description

The `proxy` device in LXD can proxy TCP connections from the Internet to individual containers. In doing so, the services in the containers currently only see as source IP address, the address of the host. Therefore, the services in the containers do not get to see the real source IP address because, through the process of proxying, the real source IP address is replaced by LXD's IP address.

The general solution to this, is to add [`PROXY protocol` support to the proxy](http://www.haproxy.org/download/1.9/doc/proxy-protocol.txt). In this way, the proxy (LXD's `proxy` device) would be able to insert the real source IP address into the TCP connection, and then any `PROXY protocol`-aware service in the container will be able to read and use that real source IP address.

Notable examples of `PROXY protocol`-aware network services are HAProxy (they created the `PROXY protocol`), [nginx](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/), [Apache](https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html).

Examples of `PROXY protocol` implementations in Go, include [`go-proxyproto pires`](https://github.com/pires/go-proxyproto) and [`go-proxyproto armon`](https://github.com/armon/go-proxyproto). Distributed with Apache License 2.0 and MIT License respectively.

# Background
1. [`PROXY protocol`](http://www.haproxy.org/download/1.9/doc/proxy-protocol.txt)
2. [`mmproxy` article by Cloudflare](https://blog.cloudflare.com/mmproxy-creative-way-of-preserving-client-ips-in-spectrum/). Has background on the issue and introduces `mmproxy` that works with `PROXY protocol` proxy implementations to add `PROXY protocol` support to network services that do not support it (like the OpenSSH server).

# Instructions to test `PROXY protocol` support

TODO

**Comment by stgraber** [comment]
I have a very basic, very early version of this which just uses the V1 protocol.
I just need to figure out the right code paths in the proxy where we want this (doesn't make sense if client is unix socket for example).
