### ISSUE TITLE
apparmor issues w/ systemd ProtectHome , ProtectSystem, PrivateTmp

### ISSUE THREAD

**Issue by jkroepke** [lxc/lxd#4787]
Followup: https://github.com/lxc/lxc/issues/2412

# Required information

 * Distribution: Ubuntu 18.04
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-22-generic
   * LXC version: 3.0.1
   * LXD version: 3.0.1
   * Storage backend in use: dir

# Issue description
systemd Units like
```
# systemctl cat phpsessionclean.service
# /lib/systemd/system/phpsessionclean.service
[Unit]
Description=Clean php session files

[Service]
Type=oneshot
ExecStart=/usr/lib/php/sessionclean
ProtectHome=true
ProtectSystem=true
PrivateTmp=true
```

Will emit an apparmor denied:

```
[2643584.790168] audit: type=1400 audit(1531564746.557:20805): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-admin_</var/lib/lxd>" name="/bin/" pid=9933 comm="(ionclean)" flags="ro, remount, bind"
```

# Steps to reproduce

 1. Start a fully unpriv. usernamespaced Container
 2. Install PHP
 3. systemctl start phpsessionclean

Im my opinion, this should allowed to restrict units inside containers.

Also see: https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/#fullyunprivilegedcontainerpayload

**Comment by stgraber** [comment]
Yes, this is an apparmor kernel bug. There's unfortunately nothing we can do in LXD about it until it's resolved.

**Comment by stgraber** [comment]
Your best bet until then is to set raw.lxc=lxc.apparmor.profile=unconfined on affected containers.

**Comment by stgraber** [comment]
ah, actually the particular issue you mentioned here has been fixed in our profile. The next issue you may hit (file_lock over Unix domain) is the kernel bug.

**Comment by stgraber** [comment]
Closing as the readonly bind mount issue has already been fixed in master.

**Comment by jkroepke** [comment]
Its https://github.com/lxc/lxd/pull/4704 ?

**Comment by stgraber** [comment]
yes

**Comment by stgraber** [comment]
until that commit makes it to you, setting security.nesting=true should work as a workaround.

**Comment by jsoref** [comment]
For people curious about what to do about phpsessionclean.service: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869182

**Comment by K-os** [comment]
Sorry for digging this up again.

I am on LXD version 3.7 (installed via snap), so it should include the commit from #4704, but I still see the apparmor log messages about the forbidden bind mount.
Do I need to do anything for the fixed apparmor profile to be used?
