### ISSUE TITLE
lxd publish with LVM backend seems to store images both in /var/lib/lxd/images and in LVM volume

### ISSUE THREAD

**Issue by cquike** [lxc/lxd#4790]
I am using packer to create customized images for lxd and the last step is to do a lxc publish. After that the image is created and appears properly in lxc image list. However it seems that there is a duplication of storage, since a LVM volume with the image is created as well as a file under /var/lib/lxd/images:

```
# ls -lh /var/lib/lxd/images/a2*
-rw-r--r-- 1 root root 1000M Jul 15 19:37 /var/lib/lxd/images/a26fb283efbb49ec3071245d0ac43646e226fdfe6ea48f9d46f30e35973fca2f
# lvs 
...
  images_a26fb283efbb49ec3071245d0ac43646e226fdfe6ea48f9d46f30e35973fca2f virtvg   Vwi-a-tz--  10.00g lxd_thinpool                                                                         29.33  
```

 * Distribution: Ubuntu 
 * Distribution version: 18.04

**Comment by stgraber** [comment]
That's perfectly normal. All LXD images must be stored as tarballs as that's what's used between servers and as the main artifact for hashing. The LVM copy is there to make it possible to create containers instantly from that image and using copy on write to avoid data duplication between containers.

**Comment by stgraber** [comment]
It's possible to delete that LVM volume using `lxc storage volume delete` but it's not possible to get rid of the tarball without completely deleting the image from LXD with `lxc image remove`

**Comment by cquike** [comment]
Thank you very much for the explanation.
Maybe it is worth adding a comment in the documentation under https://lxd.readthedocs.io/en/latest/storage/#storage-backends-and-supported-functions, since I was a bit misled by the "Optimized image storage" feature. Maybe adding that the backend image storage format is additional to the tarball under /var/lib/lxd/images would be useful.
