### ISSUE TITLE
Allow deleting storage pools that only contain image volumes

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4792]
It's a bit annoying having to go and manually delete every optimized image from a storage pool when the user didn't have to do anything to put them there.

So instead, we should just have the storage pool deletion code wipe those for the user as needed, effectively only refusing deletion of the pool if anything else is using it.

**Comment by mazerty** [comment]
can this be backported to 3.0.x please ?

**Comment by stgraber** [comment]
Yes, that feels like a perfectly good candidate for a backport once we have a fix.
