### ISSUE TITLE
Error neighbour: ndisc_cache: neighbor table overflow! (ARP Table is full)

### ISSUE THREAD

**Issue by simos** [lxc/lxd#4799]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-20-generic
   * LXC version: 3.0.1
   * LXD version: 3.0.1
   * Storage backend in use: zfs

# Issue description

When creating 1024 or more containers, the ARP table gets full and reaches the default kernel hard limit of 1024 entries. This causes those last containers not to be able to get their networking configured.

# Steps to reproduce

 1. Setup LXD on a system with 32GB RAM or more
 2. Create 1024 containers with `lxd-benchmark --count=1024 images:alpine/edge`
 3. Towards the creation of the last containers, `dmesg` shows the error
```
[21198.545370] neighbour: ndisc_cache: neighbor table overflow!
[21198.545425] neighbour: ndisc_cache: neighbor table overflow!
[21198.545473] neighbour: ndisc_cache: neighbor table overflow!
[21198.545501] neighbour: ndisc_cache: neighbor table overflow!
[21198.545549] neighbour: ndisc_cache: neighbor table overflow!
[21198.801246] neighbour: ndisc_cache: neighbor table overflow!
```
LXD reports the issue as
```
[Jul 16 21:53:43.450] Failed to launch container 'benchmark-0991': Failed to set LXC config: lxc.incl
ude=/usr/share/lxc/config/common.conf.d/
[Jul 16 21:53:50.548] Failed to launch container 'benchmark-1005': Failed to set LXC config: lxc.log.
file=/var/log/lxd/benchmark-1005/lxc.log
[Jul 16 21:53:55.253] Failed to launch container 'benchmark-0993': Failed to set LXC config: lxc.log.
file=/var/log/lxd/benchmark-0993/lxc.log
[Jul 16 21:53:59.071] Failed to launch container 'benchmark-0989': Failed to set LXC config: lxc.log.
file=/var/log/lxd/benchmark-0989/lxc.log
```

# Source of problem

The default configuration of the Linux kernel in Ubuntu has the following values:

```bash
$ sysctl net.ipv4.neigh.default.gc_thresh1
net.ipv4.neigh.default.gc_thresh1 = 128
$ sysctl net.ipv4.neigh.default.gc_thresh2
net.ipv4.neigh.default.gc_thresh2 = 512
$ sysctl net.ipv4.neigh.default.gc_thresh3
net.ipv4.neigh.default.gc_thresh3 = 1024
```

The last value, 1024, is the hard limit of entries in the ARP table.

# How to deal with this

The https://github.com/lxc/lxd/blob/master/doc/production-setup.md guide should be updated with advice about this issue. 
I am not exactly clear what values to put. My current suggestion would be to suggest 2048, 8192, 16384 respectively for the three thresholds. The reason being, 
1. a 64GB server can easily accommodate 384 `ubuntu:18.04` containers, and probably the double number `ubuntu-minimal:18.04` containers. 
2. when you launch 1024 alpine containers, it takes about 25-30GB RAM.

**Comment by stgraber** [comment]
@simos do you want to send a PR to update the production-setup doc?

**Comment by simos** [comment]
@stgraber I sent a PR. I put the advice to only change `net.ipv[46].neigh.default.gc_thresh3` to 8192, which is the maximum number of entries in the ARP table of the Linux kernel. 

The other two gc_thresh1 and gc_thresh2 do not appear to be necessary to be changed. Specifically, some guides even instruct to set gc_thresh1 to `0` which means that the ARP table should not cache entries at all. That might make sense when containers are created and destroyed in quick succession. 
`gc_thresh2` is the limit of number of ARP table entries, after which any entry older than five minutes gets cleared.

While I stress-test LXD more, I'll try to figure out if there is a practical need to change `gc_thresh1` and `gc_thresh2` as well.
