### ISSUE TITLE
Add support for dynamic resource allocation

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#480]
It should be possible to define resource restrictions like CPU as percentage, which will then adapt depending on the number of containers and number of physical resources (support for hotplug).

**Comment by benaryorg** [comment]
It would be a good start if at least the [TODO](https://github.com/lxc/lxd/blob/c9e53e48156b8206d0faa05e871ee213f3d13602/lxd/container.go#L1327) (line 1327) got fixed.

It is horrible. If 32 containers running on a 32-core machine, only the first core is used by all containers.

Round robin would be okay, as long as a `FIXME` would be there instead, but _please_ implement something. _Anything_ would be better than this.

**Comment by tych0** [comment]
On Mon, Aug 24, 2015 at 05:16:37AM -0700, Katze wrote:
> It would be a good start if at least the [TODO](https://github.com/lxc/lxd/blob/c9e53e48156b8206d0faa05e871ee213f3d13602/lxd/container.go#L1327) (line 1327) got fixed.
> 
> It is horrible. If 32 containers running on a 32-core machine, only the first core is used by all containers.
> 
> Round robin would be okay, as long as a `FIXME` would be there instead, but _please_ implement something. _Anything_ would be better than this.

This sounds like a bug to me. The code you linked to shouldn't have
the effect you described. Can you show how you've set up container
configuration?

**Comment by benaryorg** [comment]
Oh, sorry I forgot to mention that this happens when every container is set up to use only one core.

**Comment by benaryorg** [comment]
The current workaround would be to use `raw.lxc` to set up the parameters for lxc directly instead of using the lxd-builtin feature.

**Comment by tych0** [comment]
On Mon, Aug 24, 2015 at 07:36:42AM -0700, Katze wrote:
> Oh, sorry I forgot to mention that this happens when every container is set up to use only one core.

Ok, looks like the behavior is expected based on the code, then :).
We're working on a full limits spec and we'd appreciate you're input
here:
https://lists.linuxcontainers.org/pipermail/lxc-users/2015-August/009787.html

For now I can send a patch to schedule it on a set of random cores if
that would be useful for you. Doing round robin would be fine too, but
it's not such a quick patch, so if you want to do that we'll be happy
to take it :)

**Comment by benaryorg** [comment]
I would really like to implement that, but that is by far above what I would be able to do within a reasonable time, as I would need to learn Go first.

I'll leave that to the more experienced guys.

**Comment by stgraber** [comment]
This is replaced by #1164
