### ISSUE TITLE
Copying LXC container from one zpool to another

### ISSUE THREAD

**Issue by guillelos** [lxc/lxd#4802]
Hi Guys ! 

I have this : 
driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-24-generic
  server: lxd
  server_pid: 2442
  server_version: 3.0.1
  storage: zfs
  storage_version: 0.7.5-1ubuntu15
  server_clustered: false

and I 'm seeing that my zpool is running low on space : 

root@SRMN01-MIA1:~# zpool list
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
default  71.5G  57.9G  13.6G         -    71%    80%  1.00x  ONLINE  -

and I 'm seeing that the container are adapting to that : 
default/containers/ELK1             66G   55G   12G  83% /var/lib/lxd/storage-pools/default/containers/ELK1
default/containers/MAP1            2.9G  759M  2.2G  27% /var/lib/lxd/storage-pools/default/containers/MAP1
default/containers/NGX1             12G  410M   12G   4% /var/lib/lxd/storage-pools/default/containers/NGX1
default/containers/NS1              12G  408M   12G   4% /var/lib/lxd/storage-pools/default/containers/NS1
default/containers/NTP1             12G  396M   12G   4% /var/lib/lxd/storage-pools/default/containers/NTP1
default/containers/RAD1             12G  393M   12G   4% /var/lib/lxd/storage-pools/default/containers/RAD1
default/containers/RANC1            12G  393M   12G   4% /var/lib/lxd/storage-pools/default/containers/RANC1
default/containers/SMTP1            12G  393M   12G   4% /var/lib/lxd/storage-pools/default/containers/SMTP1
default/containers/SYLG1            12G  394M   12G   4% /var/lib/lxd/storage-pools/default/containers/SYLG1
default/containers/ZBX1             13G  633M   12G   6% /var/lib/lxd/storage-pools/default/containers/ZBX1

My question is can I : 
1) remove the limit of the Zpool or increase it ? if yes , where?
2) create another Zpool and move the bigger container or the snapshots ? could you tel me how ?

Thanks a lot 
Kindly Regards,
Guille

**Comment by stgraber** [comment]
With 3.0.1, you can't move volumes between pools, so your only option if you want to split into two pools would be to copy it to another machine and then copy it back onto the new pool.

But it looks like the easier approach may be to just grow your pool.
Our documentation covers this already (at the bottom): https://lxd.readthedocs.io/en/latest/storage/#notes-and-examples

**Comment by guillelos** [comment]
Thanks Stephane !

**Comment by guillelos** [comment]
your talking about this , right ?
Growing a loop backed ZFS pool
LXD doesn't let you directly grow a loop backed ZFS pool, but you can do so with:

sudo truncate -s +5G /var/lib/lxd/disks/<POOL>.img
sudo zpool set autoexpand=on lxd
sudo zpool online -e lxd /var/lib/lxd/disks/<POOL>.img
sudo zpool set autoexpand=off lxd

**Comment by guillelos** [comment]
Thanks it works perfect ;)
