### ISSUE TITLE
Networks API endpoint incorrect behavior

### ISSUE THREAD

**Issue by Nani-o** [lxc/lxd#4813]
# Required information

I'm running LXD via a snap install on Ubuntu :

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

$ lxd --version
3.2

$ snap info lxd | grep tracking
tracking:     stable
```

# Issue description

The two issues i'm seeing are related to the **/1.0/networks/\<name\>** endpoint, here a recap : 
1. The [PUT](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#put-etag-supported-6) method behave like the PATCH, it updates the config instead of replacing it. 
2. The [PATCH](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#patch-etag-supported-5) method seems to not work, but it stills output success without working. 

# Steps to reproduce

PUT method issue 
---------------- 
 
Let's take as an example this bridge network lxdbr1 : 
 
``` 
$ lxc network show lxdbr1 
config: 
  bridge.driver: native 
  ipv4.address: 192.168.1.1/24 
  ipv6.address: fd26:9b5f:cdb1:7756::1/64 
description: "" 
name: lxdbr1 
type: bridge 
used_by: [] 
managed: true 
status: Created 
locations: 
- none 
``` 
 
I gonna use this payload for interacting with the networks/<name> endpoint :

```
{
    "config": {
        "ipv4.address": "192.168.56.1/24"
    }
}
```
This should replace entirely our config letting us with only ipv4.address value : 
 
``` 
$ curl --unix-socket /var/snap/lxd/common/lxd/unix.socket \ 
    -H "Content-Type: application/json" \ 
    -X PUT \ 
    -d @lxdbr1-config.json \ 
    lxd/1.0/networks/lxdbr1 
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{}} 
 
$ lxc network show lxdbr1 
config: 
  bridge.driver: native 
  ipv4.address: 192.168.56.1/24 
  ipv6.address: fd26:9b5f:cdb1:7756::1/64 
description: ""
name: lxdbr1
type: bridge
used_by: []
managed: true
status: Created
locations:
- none
```

I would have expected to have this as an output :

```
$ lxc network show lxdbr1
config:
  ipv4.address: 192.168.56.1/24
description: ""
name: lxdbr1
type: bridge
used_by: []
managed: true
status: Created
locations:
- none
```

PATCH issue 
----------- 
 
For this issue I will use the same lxdbr1 bridge (resetting ipv4.address to initial value) and payload :

```
curl --unix-socket /var/snap/lxd/common/lxd/unix.socket \
    -H "Content-Type: application/json" \
    -X PATCH \
    -d @lxdbr1-config.json \
    lxd/1.0/networks/lxdbr1
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{}}

$ lxc network show lxdbr1
config:
  bridge.driver: native
  ipv4.address: 192.168.1.1/24
  ipv6.address: fd26:9b5f:cdb1:7756::1/64
description: ""
name: lxdbr1
type: bridge
used_by: []
managed: true
status: Created
locations:
- none
```

We have a success, but our configuration didn't change, I would have expected the output observed on the PUT method.

An another thing I have noticed that lead me to thinks this is broken, is for example using an incorrect CIDR value.

With PUT :

```
$ curl --unix-socket /var/snap/lxd/common/lxd/unix.socket \
    -H "Content-Type: application/json" \
    -X PUT \
    -d @lxdbr1-config.json \
    lxd/1.0/networks/lxdbr1
{"error":"invalid CIDR address: 1.1.1/24","error_code":400,"type":"error"}
```
With PATCH : 

```
$ curl --unix-socket /var/snap/lxd/common/lxd/unix.socket \
    -H "Content-Type: application/json" \
    -X PATCH \
    -d @lxdbr1-config.json \
    lxd/1.0/networks/lxdbr1
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{}} 
```

This throws a correct error with PUT, but PATCH still says everything is ok.

**Comment by stgraber** [comment]
Ouch, yeah, something is pretty wrong here...

**Comment by Nani-o** [comment]
I tried to dig into the lxd/network.go file, but I’m not really familiar with GO.

For the PATCH issue, according to my understanding, the **Update** method do not take requests from the patch endpoint : 
```
func (n *network) Update(newNetwork api.NetworkPut) error {
```

**Comment by stgraber** [comment]
The problem is in the database code, I'm looking at it.

**Comment by stgraber** [comment]
Sent a fix

**Comment by Nani-o** [comment]
Glad you came with a fix.

I just noticed an another bug, when creating a network with « openvswitch » when the package is not installed, it errors out but still creates the network bridge.

But then it’s impossible to delete it.

Do you want me to describe this here or in another issue ? (I thought your fix had maybe fix this problem too).

**Comment by stgraber** [comment]
@Nani-o looking into that one now

**Comment by stgraber** [comment]
@Nani-o I can't seem to reproduce the problem here:
```
stgraber@castiana:~$ lxc network create testbr0 bridge.driver=openvswitch
Error: Failed to run: ovs-vsctl add-br testbr0: 
stgraber@castiana:~$ lxc network list
+--------+----------+---------+-------------+---------+
|  NAME  |   TYPE   | MANAGED | DESCRIPTION | USED BY |
+--------+----------+---------+-------------+---------+
| lxdbr0 | bridge   | YES     |             | 11      |
+--------+----------+---------+-------------+---------+
| wlan0  | physical | NO      |             | 0       |
+--------+----------+---------+-------------+---------+
stgraber@castiana:~$ 
```

What did I miss?

**Comment by Nani-o** [comment]
@stgraber Sorry for not giving more details, I first create a network without `bridge.driver`. The I modify it using the PUT method, specifying `bridger.driver: openvswitch`. It errors out but still add the value.

From there, the only way to delete it for me was to install openvswitch, create a lxdbr1 nic with openvswitch and then ask LXD to delete it.

I can post a step by step reproduction example later if needed.

**Comment by stgraber** [comment]
Perfect, that should be enough to reproduce it then.

**Comment by Nani-o** [comment]
@stgraber I just take the time to do it from my phone. This time i’m able to delete it, don’t know what’s the difference with my yesterday test.

But it stills add the value : 
```
$ lxc network set testbr0 bridge.driver openvswitch
Error: Failed to run: ovs-vsctl add-br testbr0: ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
$ lxc network show testbr0
config:
  bridge.driver: openvswitch
  ipv4.address: 10.171.127.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:2421:e478:b8aa::1/64
  ipv6.nat: "true"
description: ""
name: testbr0
type: bridge
used_by: []
managed: true
status: Created
locations:
- none
$ lxc network delete testbr0
Network testbr0 deleted
```

**Comment by stgraber** [comment]
Reseting the bridge.driver property prior to removal should work fine too but anyway, it's certainly meant to revert the configuration on failure.

**Comment by stgraber** [comment]
Sent a fix for it now.

**Comment by Nani-o** [comment]
Yesterday when trying I was not able to reset the value.

Using PUT leaded to error letting the openvswitch value.
Using lxc network edit to remove the value put me in a « vim loop ».

Anyway, thanks for your time and reactivity as always.
