### ISSUE TITLE
Finer grained server logging

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#482]
Implement the usual multi-level logging most users expect. Ranging from critical to debugging.

**Comment by stgraber** [comment]
As mentioned in #852, this should also include support for external logs like syslog, journald or just a simple logfile path.

**Comment by pcdummy** [comment]
I would like to implement that next, for this i have been locking on logger packages, this is what i found:

[inconshreveable/log15](https://github.com/inconshreveable/log15) - [docs here](https://godoc.org/github.com/inconshreveable/log15)
[Sirupsen/logrus](https://github.com/Sirupsen/logrus) - [docs here](https://godoc.org/github.com/Sirupsen/logrus)
[op/go-logging](https://github.com/op/go-logging) - [docs here](http://godoc.org/github.com/op/go-logging)

I like log15 the most, it gots a stable API.

**Comment by stgraber** [comment]
Seems pretty nice indeed.

**Comment by stgraber** [comment]
We've got that now.
