### ISSUE TITLE
Switch `lxd init` to using the new cluster join API

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4830]
This is primarily so that our users have an example of how to use it.
The UX should be pretty much identical to what we have today, just with less direct calls on storage/network.

**Comment by stgraber** [comment]
Assigning this one to @monstermunchkin as another smaller piece of work that he can take on on the side.
I expect that not all of this will make total sense so you'll want to sync with @freeekanayaka.

The general idea is that the current cluster API now let you get the list of stuff you must ask the user about through `GET /1.0/cluster` and the responses can be included in `PUT /1.0/cluster` eliminating the need for directly creating the needed storage pools and networks when joining a cluster.

**Comment by freeekanayaka** [comment]
It's probably more efficient if I take it. I plan to squash it somewhere next week, but if @monstermunchkin beats me on it, no problem :)

**Comment by freeekanayaka** [comment]
Starting a branch.
