### ISSUE TITLE
Make use of new netns netlink API

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4831]
The goal behind this is to significantly decrease the number of subprocesses spawned when running `lxc list` and decrease the overall runtime of such queries.

@brauner contributed kernel code which should allow us to pull all the needed device information directly through netlink without ever needing to use subprocesses or setns.

The plan I believe is to do:
 - Add daemon startup logic to detect kernel support of the new netlink support
 - Introduce a new function that looks like:
```
func processNetworkState(pid int64) (map[string]api.NetworkState, error)
```
 - This function will call our existing `forknet info` subcommand if the kernel doesn't support the new API, if it does support the new API, then all the information will be retrieved without the use of a subprocess or setns

**Comment by brauner** [comment]
This is blocked on some kernel work.
