### ISSUE TITLE
Confusing and unnecessary "run lxd init" message

### ISSUE THREAD

**Issue by pmatulis** [lxc/lxd#4832]
After having run `sudo lxd init` (on Ubuntu) and then `lxc list` (or any other `lxc` command) the following message is prepended to the invoked command's output:

```If this is your first time running LXD on this machine, you should also run: lxd init```

This is confusing and seemingly unnecessary. Shouldn't the software be able to detect whether `lxd init` was run or not?

**Comment by stgraber** [comment]
`lxd init` and `lxc` may be run as completely different users on completely different systems so there's no easy way to detect whether it's been run or not.

Instead, the client just shows a first-use message to the user and suggests that they may want to run `lxd init` if they've never done so (but it's up to them to know whether they have or haven't).

**Comment by stgraber** [comment]
We may be able to reasonably cheaply check if a storage driver is listed by the server, if it is, there's a good chance that `lxd init` was run.
