### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by leonid-xorcom** [lxc/lxd#4846]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 18.0.4
 * The output of "lxc info":$ lxc info
config:
  core.https_address: 192.168.0.206:8443
  core.trust_password: true
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.0.206:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFOzCCAyOgAwIBAgIRAJLCzCsQRqn2ojy/kD7EMLgwDQYJKoZIhvcNAQELBQAw
    MjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzESMBAGA1UEAwwJcm9vdEB3
    ZXlsMB4XDTE4MDYyNTE0MDMyMFoXDTI4MDYyMjE0MDMyMFowMjEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzESMBAGA1UEAwwJcm9vdEB3ZXlsMIICIjANBgkq
    hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArBqX3Gj9XiTfv48s09GBk8ulAm2tyZyv
    ljb/AR3agelbTYDEJGQ+verJYPe62/CnnXg5zQWaSUHbjAg6Hxyj+QUKtG5zHcCg
    lX2TbQ9bXcj1G6oPwqy6w3h9tWYegZFcNapxHmag9waPzNDSfwa6qlZD3peTVndF
    XnqJMmEpnCK2OddeIxaRsl0hDurXfbjI0dE5nCiDI5HDlAYnWxXYAM0O7axVA+U2
    LHWKEPRwegTzqY7mwa6hTKlxXWu/k9C2SHeCFn+iPH2Rq32eibvf3UFvGQCazB44
    rU8sRW/5xXXwCI4XrTJaA1sA7X6ta6Mbiw5lHCRWnPgmtDAnvKYV2OewCiPNaO1i
    hLLMXNutH4J4zd9aCAD7b6EycXrJLltNSIeyQ2t8ImMNDj4b+0fOHNGrl4Kcpz/Z
    VEBZP0IIImlVQiD9TJlBe2jaBY4j18jLqcVDcFKu323RwFBEwFh6sjcsOmE487P4
    Smgdo7NWuASzpFNOfCi0IRKeadC//YRqVQYSBE2ZcKA4vp+ziXgggrz2Wt9hDhSu
    nke6zMQl3n/PqrTnAF40MQ0UoGYXYHw45TZ/vXH5Zf8MYFA1CyR+tdMjUxaH/FpM
    3NDOTYQ+W+ujQu+/iTyzBq5sBe7jji/5UPya2C6sPPJrc08KGkcd5z8yxZamSgNy
    Q6G/EvEgtbUCAwEAAaNMMEowDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsG
    AQUFBwMBMAwGA1UdEwEB/wQCMAAwFQYDVR0RBA4wDIIEd2V5bIcEwKgAzjANBgkq
    hkiG9w0BAQsFAAOCAgEAbh3C8vetgoSnpTbtilgyOzuiEJS3mQscSWXr09q8hYlQ
    7zN2dIN89ajej4oZZdf9a7fs/9uFimJQfEiMDSgaR5zHLLNRj5wR8KnzQzt/CQX5
    yDobQ4Rw4bE15fth2x3B3v5CsGJLEEI2DnwNg0nuv6oSd3VJXCdD4Bx+RfofCnlt
    j8loxDIdIdsKMuzBJOPto2qcRfoeJG9hBvMAWzTEFdS5xKR09Q8GqpUQJLwgY2wi
    7pNfFL4xZwEili/e/HgezF44OEBr1qzfIH7vtHaPQo0fmb8/H3yxIO+IIHXsnnLp
    3+xY0whGonPescNoXPYN9G2xmpe8ur1EuBB/0/k23zn/5qviSpJDNBHIB+M6BbTC
    ao6wFbjsX7QC3LEH3lTtc/swICfdpbgARCyHzasdYm92as5v4+VMg3dzyFgPP+TH
    SLSnkY1VLC4TU5lD9zSFYo5u1VtvpCJ53U6DgGITQ7fzRq+g5NmyDmbF+pAPT0ez
    wfKbeo6b7gSzlbdEFMUMLBCelpwe+nUq/TG8Kwsez8SehOdlQsoWyrfcZV4m3Xui
    P1uQEQPjMglXbYH7a878QzW0wmSVqM+4MLFnExFtCIW8RDRScLnfeeuCLh1qMGoZ
    JF3hsUmEgvLlu8OOlWHSz/8klVQ4mqKrg/0PFkvfPcl+/MaTxg44O0HHY0ou9I0=
    -----END CERTIFICATE-----
  certificate_fingerprint: 2e3d7a97ab8c4368ff32ccd7349349502b812c9d583aa8a79ca5148bcc389564
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-23-generic
  server: lxd
  server_pid: 24830
  server_version: 3.0.1
  storage: lvm
  storage_version: 2.02.176(2) (2017-11-03) / 1.02.145 (2017-11-03) / 4.37.0 / ./configure
    --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man
    --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules
    --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu
    --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --exec-prefix=
    --bindir=/bin --libdir=/lib/x86_64-linux-gnu --sbindir=/sbin --with-usrlibdir=/usr/lib/x86_64-linux-gnu
    --with-optimisation=-O2 --with-cache=internal --with-clvmd=corosync --with-cluster=internal
    --with-device-uid=0 --with-device-gid=6 --with-device-mode=0660 --with-default-pid-dir=/run
    --with-default-run-dir=/run/lvm --with-default-locking-dir=/run/lock/lvm --with-thin=internal
    --with-thin-check=/usr/sbin/thin_check --with-thin-dump=/usr/sbin/thin_dump --with-thin-repair=/usr/sbin/thin_repair
    --enable-applib --enable-blkid_wiping --enable-cmdlib --enable-cmirrord --enable-dmeventd
    --enable-dbus-service --enable-lvmetad --enable-lvmlockd-dlm --enable-lvmlockd-sanlock
    --enable-lvmpolld --enable-notify-dbus --enable-pkgconfig --enable-readline --enable-udev_rules
    --enable-udev_sync
  server_clustered: true
  server_name: weyl

# Issue description

In the 'top' utility output I see that LXD process memory consumption is growing up with the time. 
Thus, immediately after start:

-----------------------------------------------------------
Mem Type      | After Start     |  In a week      |
-------------------|------------------|---------------------|
Virtual             | 1282568       | 2172968         |
Residential     |  34348          | 790276           |
Shared           |  21052          |  23232            |
-------------------|------------------|---------------------|

# Steps to reproduce
Restart the LXD service and just monitor the memory consumption. 

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [X] Main daemon log (at /var/log/lxd/lxd.log
[lxd.log.tar.gz](https://github.com/lxc/lxd/files/2238589/lxd.log.tar.gz)
 or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
There are two leaks in 3.0.1, one in config parsing and one in the database code. Both were fixed upstream and should hit your distro with 3.0.2.

Getting LXD through the snap package would also get you those fixes today.
