### ISSUE TITLE
Move container volume between different pools on local machine

### ISSUE THREAD

**Issue by msjyoo** [lxc/lxd#4847]
# Required information

 * Distribution: bionic
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-29-generic
   * LXC version: 3.0.1
   * LXD version: 3.0.1
   * Storage backend in use: btrfs

# Issue description

Hello,

I'm trying to resize my lxd container that has run out of disk space that is using the default btrfs backend, but I cannot find a way to do so. I've tried to move the container volume from the default to a newly-created larger volume, but it seems container volumes cannot be moved.

Is this a missing feature (container volumes can't be moved) or am I expected to use another workflow to resize a btrfs container that's out-of-space?

# Steps to reproduce

 1. lxc storage volume move default/seedbox default2/seedbox
 2. 
```
DBUG[07-29|17:56:04] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0/storage-pools/default/volumes/custom/seedbox
Error: not found
```

**Comment by msjyoo** [comment]
I've manually modified the btrfs loopback image using `truncate` and `btrfs filesystem resize`. However, the configuration seems unchanged when I use `lxc storage show default`. Am I correct in guessing that the size value in the config is for creation only, and is purely cosmetic?

**Comment by stgraber** [comment]
Yeah, it's purely cosmetic. We do have support for moving storage volumes between pools in LXD 3.2.
