### ISSUE TITLE
Show download progress everywhere possible

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4852]
Right now the following `lxc` commands show progress information:

 - lxc copy
 - lxc export
 - lxc init
 - lxc launch
 - lxc move
 - lxc image copy
 - lxc image export
 - lxc image import
 - lxc image refresh
 - lxc storage volume copy
 - lxc storage volume move

Looking at all our other subcommands, the following should also be made to report progress information (or download speed when relevant):

 - lxc file pull (unless output is `-`)
 - lxc file push
 - lxc import

`lxc file` and `lxc import` should just be using an IO progress tracker to wrap the Reader they're using, that means that for `lxc file push` and `lxc import` we can show progress in percent as well as transfer speed, for `lxc file pull` we won't know the full size so can just show the speed and amount downloaded.

For both `lxc file pull` and `lxc file push` we need to keep in mind that we may be dealing with a batch of files, so the filename should be shown.

`lxc storage volume copy` and `lxc storage volume move` should just be about attaching a progress handler to the operation in the client and possibly doing a bit of plumbing on the server side if we don't already update the operation with progress information.

**Comment by stgraber** [comment]
@monstermunchkin set it for LXD 3.5 but feel free to start hacking on it on the side, most of those should be pretty easy to do, I only expect the storage part to maybe be a bit more complex.

**Comment by monstermunchkin** [comment]
`lxc storage volume {copy,move}` already have a progress handler attached, or am I missing something?

**Comment by stgraber** [comment]
Nope, I'm the one who missed it, nevermind :)

**Comment by stgraber** [comment]
Updated the issue, so your PR should be all we need, once it doesn't crash gettext-go :)
