### ISSUE TITLE
`lxc storage get` empty on 3.0.1

### ISSUE THREAD

**Issue by kfix** [lxc/lxd#4855]
just like #4797 for `lxc profile get`, `lxc storage get` returns nothing.

if the fix is similar to #4798, then the problem might be [here](https://github.com/stgraber/lxd/blob/cdd374b897db21961d560ac1e402a110f33e71c7/lxc/storage.go#L363)

# Required information

Ubuntu 18.04
lxd 3.0.1
Linux 4.15.0-29-generic

# Issue description

```
$ lxc storage show test
config:
  size: 100GB
  source: /var/lib/lxd/disks/test.img
  zfs.pool_name: default
description: ""
name: test
driver: zfs
used_by:
  ...
status: Created
locations:
- none

$ lxc storage get test source
$
```

**Comment by stgraber** [comment]
Re-tested them all for good measure, found two that weren't behaving and fixed them and added a test, so hopefully we're good this time :)

**Comment by kfix** [comment]
Wow, Thanks!

**Comment by Debianer** [comment]
Ubuntu Server 18.04.1 
LXD Snap Stable 3.9
KVM guest (web hosting company) presumably CentOS7 Host

lxd init, btrfs storage backend, block device, /dev/disk/by-id/[scsi-guest-disk]

commands:

# sudo lxc storage get lxd0 block.mount_options 

\\there is no output to the above

# sudo lxc storage get lxd0 size

\\ there is no output to the above

# sudo lxc storage get lxd0 source
a418c781-3fe7-48d4-be87-9bfe95a71dce

# sudo lxc storage set lxd0 btrfs.mount_options rw
Error: invalid argument

# sudo lxc storage set lxd0 btrfs.mount_options "rw"
Error: invalid argument

# sudo lxc storage set lxd0 btrfs.mount_options "autodefrag"
Error: invalid argument
