### ISSUE TITLE
dnsmasq looses container IP address on snapshot deletion

### ISSUE THREAD

**Issue by janxb** [lxc/lxd#4866]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 18.04
 * LXC version: 3.3
 * LXD version: 3.3
 * Snap release: 8011
 * Storage backend in use: BTRFS

# Issue description

`dnsmasq` looses the container IP address when a snapshot is deleted from this container. A container restart is required for `dnsmasq` to pick up the address again.

# Steps to reproduce

```
lxc launch ubuntu:18.04 c1
lxc snapshot c1 snap0
lxc delete c1/snap0
```

Monitor the DNS results using the following command (change the IP address to match your LXD bridge gateway)

`watch -n1 dig c1.lxd @10.154.181.1`

After deleting the snapshot in the last command, the IP address of the container disappears from the DNS. Only a container restart fixes this.

Maybe this is related to the following log line:
`lvl=dbug msg="Database error: &errors.errorString{s:\"sql: no rows in result set\"}"`

# Additional information
This issue first got discussed in the LXD forum at: https://discuss.linuxcontainers.org/t/lxd-dns-seems-to-cache-negative-results-after-container-restart

**Comment by stgraber** [comment]
already fixed
