### ISSUE TITLE
Make use of uevent injection for USB devices

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4874]
Now that we have some support for injecting uevents inside recent Linux kernels, we should have LXD make use of it, a good first candidate is hotplug of USB devices as we already have a uevent handler for this and so should be able to forward the needed event reasonably easily.

@brauner I know you have more kernel work planned around this but is any of it an actual blocker for us landing uevent forwarding for USB devices?

**Comment by brauner** [comment]
> @brauner I know you have more kernel work planned around this but is any of it an actual blocker for us landing uevent forwarding for USB devices?

Oh, never saw that question. :) No.
