### ISSUE TITLE
Internal way to fetch all local or cluster-wide containers in one shot

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4882]
When looking at cluster performance issues on 2 nodes cluster with about 500 containers, we waste a lot of times fetching all containers both at startup time and then in the background when getting various kernel notifications.

The worst happens when restarting both nodes, at which point they both attempt to get all the container objects twice (once for DHCP leases and once for inotify handles). When the DB is hammered it can take up to a second per container, making LXD in my case take about 15min to startup.

I've sent a branch which cuts in half the container count in many cases and fixes further performance issues with network devices, but that's still making LXD startup much much longer than it should be.

I think the easiest way out of this for now is to come up with two new functions:
 - containersLoadAll()
 - containersLoadLocal()

Those would then in a single function call, fetch all the needed containers from the database and feed them all through containerLXCLoad to return `[]container, error`.

On the database side, we should be able to get all we need by only querying every table once rather than once per container which should limit the DB chatter significantly.

We can then use those functions instead of ListContainers + containerLoadByName everywhere we have that pattern today which should let us cut down on DB queries significantly, both for startup/shutdown/background operations but also for interactive queries like `lxc list`.

**Comment by stgraber** [comment]
@freeekanayaka can you take a look at this when starting today? At least to get a sense of how easy writing those functions would be?

On the DB side, it looked like we'd want a ContainersGet(scope) function (scope being local or global effectively) which would then do a single query per affected table and then setup the args struct from that data.

**Comment by freeekanayaka** [comment]
Sure, this should be pretty straightforward. But I'll wait for you to come up online today to be sure that I understand all the details and that we're on the same page. It'd be also interesting to see more data about the profiling you did. Of course it sounds that doing this db optimization alone could indeed be a nice win, since most of the time for db queries is spent in network roundtrips which at the moment increase linearly with the number of containers.
