### ISSUE TITLE
Get a better argument parser

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#490]
Quite frankly, gnuflag is a disaster. We're abusing it in a few ways and it gives a sub-optimal user experience.

We need to replace it or extend it so that we can properly a hierarchy of command, with arguments sitting anywhere in the hierarchy (similar to argparse) and which renders a usable help message to the user showing the required arguments, optional arguments, ...

That means we can have global arguments like --config and --debug which apply to all commands, we can have arguments that are defined for all "lxc image" commands and then arguments specific to a given command. Arguments can be either optional or mandatory, have default values, may be passed multiple times and can be positional or not.

The above should cover about all our current needs.

**Comment by sigmonsays** [comment]
I have been a fan of https://github.com/codegangsta/cli

**Comment by erikh** [comment]
mow.cli is nice too. I was just looking at this code and was hoping you guys had a ticket like this. Do you want a PR for this?

**Comment by stgraber** [comment]
Both suggestions appear to be a massive improvement over what we have today.

If either of you are willing to work on a partial conversion so we can check that it behaves like we'd want for:
 - General help messages
 - List of main commands (and hidden commands)
 - Sub-commands
 - Error handling

Then that'd help us quite a bit to get started with moving to a better argument parser.

**Comment by stgraber** [comment]
I'd just recommend you don't spend too much time on this since it's not clear yet what we'll be using, so spending some time to show how your preferred parser would work would be great, but spending days migrating everything would probably be a waste of time at this point.

**Comment by erikh** [comment]
Fair enough. I'll try to put together a "taste" of each as time permits.

-Erik

**Comment by ranjib** [comment]
im using mow.cli , its pretty neat, specially if you have to support sub-commands. but the spec (that dictates which of the cli options are mandatory and which are optional) enforces you to pass cli arguments in certain order.

**Comment by erikh** [comment]
So, if it's of any use, I have two small projects that I've been building, one uses `codegangsta/cli` and one now uses `mow.cli`. I wanted to do this anyway, but realized it might be useful data to paste here.

mow.cli: https://github.com/erikh/termproxy/blob/develop/main.go#L20-L35
codegangsta/cli: https://github.com/erikh/s3util/blob/master/main.go (the whole file)

Hopefully this assists with any decisions. If you guys have a chat (slack, irc, etc), I'll try to drop in so we can have a detailed discussion if this is desired.

**Comment by pcdummy** [comment]
Late but they are on Freenode channel #linuxcontainers

**Comment by pcdummy** [comment]
This looks very clean: 
https://github.com/erikh/s3util/blob/master/main.go while this doesn't
https://github.com/erikh/termproxy/blob/master/main.go

So i would choose codegangsta/cli over jawher/mow.cli.

**Comment by stgraber** [comment]
I tend to agree with that assessment from a style point of view.
We'd still need to make sure that we can actually achieve what we want with it though.

The main things I'd like to see from the top of my head are:

Command | Result
--- | ---
lxc | Print list of all top level sub-commands + a footer
lxc --help | Print list of all top level sub-commands + all global arguments + a footer
lxc list | Simple command
lxc list --help | Help for lxc list, listing both global arguments and local arguments
lxc config | Print list of all config sub-commands + a footer
lxc config --help | Print list of all config sub-commands + all global arguments + all config arguments + a footer
lxc config trust | Print list of all trust sub-commands + a footer
lxc config trust --help | Print list of all trust sub-commands + all global arguments + all config arguments + all config trust arguments + a footer
lxc image import | Print error (missing arguments) + command usage
lxc image import --help | Print command help
lxc image import blah | Import unified image blah into local LXD
lxc image import blah dakara: | Import unified image blah into dakara's LXD
lxc image import blah.meta blah.rootfs | Import split image blah into local LXD
lxc image import blah.meta blah.rootfs a=b c=d | Import split image blah into local LXD with properties a and c set to b and d respectively
lxc image import blah.meta blah.rootfs a=b c=d --debug | Import split image blah into local LXD with properties a and c set to b and d respectively and use debug mode (global option)
lxc image import blah.meta blah.rootfs dakara: | Import split image blah into dakara's LXD

I think that roughly covers the weird stuff we've got to do with our parser.

**Comment by erikh** [comment]
codegangsta/cli should be able to accommodate this.

I won’t have time this weekend but will put something in for next weekend to tackle an example.

-Erik

**Comment by stgraber** [comment]
For anyone reading this and who's interested in working on it, codegangsta/cli seems like our best bet. It also happens to be packed in Debian/Ubuntu.

**Comment by pcdummy** [comment]
MAYBE this weekend i get the time to work on this (and with Go again).

**Comment by pcdummy** [comment]
Sry, can't hack this together this weekend, we go for a short trip to germany. Think during the next week/weekend i get the time.

**Comment by pcdummy** [comment]
I hacked a simple example [together](http://paste.ubuntu.com/15174403/).

What do you think about that?

**Comment by pcdummy** [comment]
[This](http://paste.ubuntu.com/15174788/) is what i got together this evening.

**Comment by pcdummy** [comment]
Working on that on this [gist](https://gist.github.com/pcdummy/76fb8060517bb51210ac)

**Comment by pcdummy** [comment]
Development happens now [on my lxccg branch](https://github.com/pcdummy/lxd/tree/lxccg)

**Comment by stgraber** [comment]
So it's time to pick this back up, and looks like we'll be going with cobra rather than urfave/cli due to the former supporting GNU style flag handling, that is, allowing flags to be passed anywhere on the command line whereas urfave is now restricted to having flags be passed before the arguments.
