### ISSUE TITLE
How to convert this old values to new ?

### ISSUE THREAD

**Issue by twelfthdoctor** [lxc/lxd#4900]
Hello. I have something like this in my container's config:
```yaml
config:
  lxc.aa_profile = unconfined
  raw.lxc: |-
    lxc.cgroup.devices.allow = a
    lxc.mount.auto=proc:rw sys:rw
    lxc.cap.drop =
devices:
  ...
```
But unfortunately, when I'm trying to attach this config to a container, it fails because of an error: Failed to get raw.lxc
LXD version: 3.3
What should I change in config's section to make it work?

**Comment by stgraber** [comment]
lxc.aa_profile should be under raw.lxc and be renamed to `lxc.apparmor.profile`.

https://discuss.linuxcontainers.org/t/lxc-2-1-has-been-released/487 has the list of old and new names.

**Comment by twelfthdoctor** [comment]
@stgraber There are no mappings for other keys!
