### ISSUE TITLE
What are the mappings for keys?

### ISSUE THREAD

**Issue by twelfthdoctor** [lxc/lxd#4901]
What are the mappings for such keys as:
lxc.cgroup.devices.allow
lxc.mount.auto
lxc.cap.drop
(from old 2.0 config to new 3.3 config) ?
I didn't find this mappings in issue https://github.com/lxc/lxd/issues/4393#issuecomment-378181793
Should **lxc.mount.auto** be changed to **lxc.mount.fstab.auto** ?
And what to do with cgroups and cap.drop ?

**Comment by stgraber** [comment]
We only changed a few keys and those were highlighted in the 2.1 release notes I linked you to.
The rest remains the same. You can check your `raw.lxc` content against the liblxc documentation:
https://linuxcontainers.org/lxc/manpages//man5/lxc.container.conf.5.html
