### ISSUE TITLE
lxc image delete command doesn't work in cluster mode and leaves stale files behind in /var/snap/lxd/common/lxd/images

### ISSUE THREAD

**Issue by itcrowdsource** [lxc/lxd#4906]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.03
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-131-generic
   * LXC version: 3.0.1
   * LXD version: 3.3
   * Storage backend in use: ZFS

# Issue description

When issuing lxc publish <name> --alias <alias name> (on a random cluster node) an image is being created on the node where the source instance resides (in the folder /var/snap/lxd/common/lxd/images)

lxc image info <alias name> shows that the image has been created correctly.

However running the command lxc image delete <alias name> from another node as where the published image physically resides fails to cleanup the image file in /var/snap/lxd/common/lxd/images

lxc image delete only works properly when you issue this command on the cluster node where the image physically resides.

# Steps to reproduce

 1. run  lxc publish <name of instance on node A> --alias <alias name> on node B
 2. run lxc image info <alias name> to determine the fingerprint ID of the image
 3. run lxc image delete <alias name> on node B
 4. The delete file with <fingerprint ID> still exist in /var/snap/lxd/common/lxd/images on node A

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by freeekanayaka** [comment]
I will look at this on Monday, if nobody steps in or gives an explanation.

**Comment by itcrowdsource** [comment]
@freeekanayaka @stgraber 
Issue seems to be resolved in the latest release, correct? The only thing that I notice is that some files/folders are cumulating on the node where the publish command is being executed on. Not sure if this is by design, but I'd just wanted to let you know:

```
root@SRV:/var/snap/lxd/common/lxd/images# ls -laht
total 84K
drwx------ 19 root root  12K Aug 24 10:14 .
drwx------  2 root root 4.0K Aug 24 10:14 lxd_build_510036058
drwx------  2 root root 4.0K Aug 24 10:08 lxd_build_219469544
drwx------  2 root root 4.0K Aug 24 09:55 lxd_build_644054922
drwx------  2 root root 4.0K Aug 24 09:54 lxd_build_103442072
drwx------  2 root root 4.0K Aug 24 09:43 lxd_build_910756751
drwx------  2 root root 4.0K Aug 24 09:41 lxd_build_517421205
drwx------  2 root root 4.0K Aug 24 09:40 lxd_build_566534443
drwx------  2 root root 4.0K Aug 24 09:39 lxd_build_324740305
drwx------  2 root root 4.0K Aug 24 09:37 lxd_build_926124807
drwx------  2 root root 4.0K Aug 24 09:28 lxd_build_876195661
drwx------  2 root root 4.0K Aug 24 09:19 lxd_build_567033635
drwx------  2 root root 4.0K Aug 24 09:09 lxd_build_462488224
drwx------  2 root root 4.0K Aug 24 09:04 lxd_build_053831870
drwx------  2 root root 4.0K Aug 24 09:00 lxd_build_641246200
drwx------  2 root root 4.0K Aug 24 08:58 lxd_build_045998166
drwx------  2 root root 4.0K Aug 24 08:56 lxd_build_167657604
drwx------  2 root root 4.0K Aug 24 08:54 lxd_build_076086786
drwx--x--x 14 root root 4.0K Aug 20 22:28 ..
```

**Comment by stgraber** [comment]
@itcrowdsource https://github.com/lxc/lxd/pull/4975 should take care of those directories.
