### ISSUE TITLE
Fix "lxc file push <file> <container>/<target>/<filename>"

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#491]
Currently LXD appears to assume that the target filename will always match the source and that the path provided as the target must be a directory (and therefore creates it).

This should be changed to only use the source filename if the specified target is a directory. If it's not, the target should be assumed to be a file in an existing directory. If the directory in question doesn't exist, an error should be returned.

**Comment by nmathew** [comment]
basically, if <target> is not a directory, return an error right?

In containerFilePut() 

replace os.mkDirAll() with os.Stat(), and directory don't exist return an error.
Other remain same?

**Comment by stgraber** [comment]
Note quite.

 - If target is an existing directory, write the file using the source filename
 - If target isn't a directory but dirname(target) exists and is a directory, then the user wants us to write with a different filename
 - If target doesn't exist and dirname(target) doesn't exist either, then return an error.

**Comment by nmathew** [comment]
Thanks, you can assign this to me.

**Comment by stgraber** [comment]
Thanks. I would assign it to you if github would let me... Apparently issues can only be assigned to project members...

**Comment by stgraber** [comment]
The fix has been merged. Thanks!
