### ISSUE TITLE
lxc 3.0.1 image import is failing on "Metadata file is required"

### ISSUE THREAD

**Issue by GavrielNsof** [lxc/lxd#4919]
# Required information
 * Distribution: Ubuntu 16.04.5 LTS
 * Kernel version: 4.15.0-30-generic
 * LXC/LXD version: 3.0.1

# Issue description
When trying to import lxc images from a URL I'm getting this error:
`Error: Metadata file is required`

# Steps to reproduce
`lxc image import https://dl.stgraber.org/lxd`
or any URL (it doesn't get to the request part):
`lxc image import https://aaaaaa`

Is there another way to import images from a webserver or this is a bug?

**Comment by stgraber** [comment]
Oops, clearly not the most used feature if nobody else noticed until now (or they're using the API directly instead of the CLI).

Anyway, sent a fix for this now.
