### ISSUE TITLE
Exec control socket closed too early

### ISSUE THREAD

**Issue by lpgera** [lxc/lxd#4922]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 bionic
 * The output of "lxc info":
  ```
config:
  core.https_address: ...
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - ...
  architectures:
  - x86_64
  - i686
  certificate: ...
  certificate_fingerprint: ...
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-1009-gcp
  server: lxd
  server_pid: 103490
  server_version: "3.3"
  storage: zfs
  storage_version: 0.7.9-3ubuntu2~18.04.york0
  server_clustered: false
  server_name: ...
  ```

# Issue description

I am trying to use the exec REST API endpoint to tail some log files. The content of the file arrives successfully on the websocket, but if the content is long enough (above a few kilobytes), the control socket closes before the last message arrives. This makes it impossible to know when the execution has ended. I cannot rely on the closing of the stdout websocket, because that remains open for too long. The same thing applies to interactive and non-interactive mode too.
I think the expected behaviour would be that the control socket does not close until all the messages have been sent on the stdout socket.

# Steps to reproduce

 1. create a log file with a long content on the container
 2. make a post request to the exec endpoint with this body: 
    ```
    {
      "command": ["tail", "-1000", "pathtologfile"],
      "wait-for-websocket": true,
      "interactive": true,
    }
    ```
 3. connect to the operation's websockets
 4. receive messages

**Comment by stgraber** [comment]
Not sure exactly what your client is doing but the control socket gets closed when the process exit which is what I'd expect to happen. At the same time, the operation is marked as done and its return value is set.

The client is supposed to:
 - Spawn the command and get the operation back
 - Write anything that needs to be written to stdin, then close stdin
 - Start reading both stdout and stderr
 - Wait for the operation to complete
 - Wait for stdout/stderr read to reach EOF
 - Exit

The stdin, stdout and stderr should typically happen in separate threads or goroutine as it's pretty common for software to buffer read stdin, meaning that you won't be able to write all of your stdin data if you're not also reading stdout to empty the output buffer.

Note that if all you care about is your example above, you can make your life much easier by using:
```
{
  "command": ["tail", "-1000", "pathtologfile"],
  "record-output": true,
}
```

And then just grab the output at the URL listed in the response:
```
stgraber@castiana:~/data/code/lxc/lxd (lxc/master)$ lxc query /1.0/containers/snapcraft/exec -X POST -d '{"command": ["tail", "-1000", "/var/log/syslog"], "record-output": true}' --wait
{
	"class": "task",
	"created_at": "2018-08-14T11:51:29.497308-04:00",
	"description": "Executing command",
	"err": "",
	"id": "d1acf1c4-89fe-4a8d-a2d4-75158dd04da0",
	"may_cancel": false,
	"metadata": {
		"output": {
			"1": "/1.0/containers/snapcraft/logs/exec_d1acf1c4-89fe-4a8d-a2d4-75158dd04da0.stdout",
			"2": "/1.0/containers/snapcraft/logs/exec_d1acf1c4-89fe-4a8d-a2d4-75158dd04da0.stderr"
		},
		"return": 0
	},
	"resources": {
		"containers": [
			"/1.0/containers/snapcraft"
		]
	},
	"status": "Success",
	"status_code": 200,
	"updated_at": "2018-08-14T11:51:29.55695991-04:00"
}
```

**Comment by lpgera** [comment]
Thanks for your quick response!
So if I understand correctly, the empty messages from stdout/stderr websockets mean EOF, and I have to wait for them to arrive to be sure to capture every data, and I can not rely on the close event from the control socket.

And maybe the record-output option is enough for this use case anyway, but then it means that I have to:
* make a POST request to `/1.0/containers/[container_name]/exec` with `"record-output": true` option
* make a GET request to the `/1.0/operations/[operation_id]/wait`
* make GET requests to the log urls from the result of the previous request

Could you please make these things clearer in the REST API documentation?
