### ISSUE TITLE
Unable to mount squashfs disk image within container

### ISSUE THREAD

**Issue by thomasf1234** [lxc/lxd#4923]
# Required information

 * Distribution: Ubuntu LTS
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-24-generic
   * LXC version:
   * LXD version: 3.0.1-0ubuntu1~18.04.1
   * Storage backend in use: zfs

# Issue description

Failure to mount disk image as loop device that exists within the container. Can steps necessary please be shared to allow a successful and persistent mount withstanding container restarts? (in a VM I would update /etc/fstab) 

# Steps to reproduce

On Host:
1. `mkdir app`
2. `mksquashfs app app.sqsh`
3. `lxc launch ubuntu:16.04 ub16` 
4. `lxc file push app.sqsh ub16/root/`
5. `lxc exec ub16 -- sudo --login --user ubuntu`
6. `sudo mkdir /root/app`
7. `sudo mount -t squashfs /root/app.sqsh /root/app`

# Information to attach
Error:
mount: /root/app: mount failed: Unknown error -1

**Comment by stgraber** [comment]
Unprivileged containers aren't allowed to mount arbitrary filesystems, that's a kernel enforced restriction.

Easiest way to do what you want is to install and use squashfuse in that container.

**Comment by thomasf1234** [comment]
@stgraber : Thank you. I implemented squashfuse via a custom systemd service which would ensure the disk was mounted.
