### ISSUE TITLE
Iterate /sys/class/drm for GPUs rather than PCI

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#4925]
Not all GPUs are on the PCI bus, one such example would be virtio-gpu which shows up on the platform bus.

We should tweak our logic to iterate through /sys/class/drm to find the devices that have drm nodes, then do our usual filtering through those.

**Comment by brauner** [comment]
Hm? https://patchwork.ozlabs.org/patch/482618/

**Comment by stgraber** [comment]
Well, apparently there are cases where virtio-gpu doesn't show up on the PCI bus, such as described here:
https://chromium-review.googlesource.com/c/chromiumos/platform/tremplin/+/1175419

**Comment by stgraber** [comment]
Got a tentative fix for this, just waiting to hear back about exact layout of virtio-gpu to confirm that this commit will do the trick.
