### ISSUE TITLE
lxd daemon stops after adding new container

### ISSUE THREAD

**Issue by ygversil** [lxc/lxd#4931]
# Required information

 * Distribution: Archlinux
 * Distribution version: latest upgrade
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.17.14-arch1-1-ARCH #1 SMP PREEMPT
   * LXC version: 3.0.1
   * LXD version: 3.3
   * Storage backend in use: BTRFS : /dev/sda4 on /var type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)

# Issue description

Just upgraded to lxd 3.3 (among with other packages upgraded). After host reboot, lxd did not start at first, so I did `systemctl restart lxd.service`, and everything went fine. But then I added a new container (which is up and running), but after that `lxc list` shows a 500 internal server error. Tried again `systemctl restart lxd.service` : this time the service does not restart and remains in failed state.

# Steps to reproduce

Not sure how to reproduce this one.

# Information to attach

 - [ ] output of `systemctl status lxd.service`
* lxd.service - REST API, command line tool and OpenStack integration plugin for LXC.
   Loaded: loaded (/etc/systemd/system/lxd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-08-16 11:08:16 CEST; 1h 9min ago
  Process: 15043 ExecStart=/usr/bin/lxd --group lxd (code=exited, status=1/FAILURE)
 Main PID: 15043 (code=exited, status=1/FAILURE)
    Tasks: 19 (limit: 4915)
   Memory: 543.7M
   CGroup: /system.slice/lxd.service
           |- 5572 [lxc monitor] /var/lib/lxd/containers zabbix
           |- 8163 [lxc monitor] /var/lib/lxd/containers glpi
           |-12680 [lxc monitor] /var/lib/lxd/containers queue
           |-15195 [lxc monitor] /var/lib/lxd/containers im
           |-28232 [lxc monitor] /var/lib/lxd/containers accounts
           |-28352 [lxc monitor] /var/lib/lxd/containers admin
           |-28577 [lxc monitor] /var/lib/lxd/containers booked
           |-28725 [lxc monitor] /var/lib/lxd/containers buildbot
           |-28873 [lxc monitor] /var/lib/lxd/containers ci
           |-29017 [lxc monitor] /var/lib/lxd/containers dbchiro
           |-29175 [lxc monitor] /var/lib/lxd/containers flexfield
           |-29511 [lxc monitor] /var/lib/lxd/containers intranet
           |-29610 [lxc monitor] /var/lib/lxd/containers laevus
           |-29839 [lxc monitor] /var/lib/lxd/containers mapproxy
           |-29961 [lxc monitor] /var/lib/lxd/containers nginx
           |-30317 [lxc monitor] /var/lib/lxd/containers openproject
           |-30617 [lxc monitor] /var/lib/lxd/containers orangehrm
           |-31029 [lxc monitor] /var/lib/lxd/containers ows
           `-31180 [lxc monitor] /var/lib/lxd/containers picinceptor

Aug 16 11:08:12 ygversilhw dnsmasq-dhcp[15113]: read /var/lib/lxd/networks/lxdbr0/dnsmasq.hosts/accounts
Aug 16 11:08:15 ygversilhw lxd[15043]: lvl=warn msg="Failed to rollback transaction after error (failed to query containers config: driver: bad conne>
Aug 16 11:08:15 ygversilhw lxd[15043]: err="failed to begin transaction: unexpected response type 7" lvl=eror msg="Failed to bring up network" name=l>
Aug 16 11:08:15 ygversilhw lxd[15043]: err="failed to begin transaction: unexpected response type 7" lvl=eror msg="Unable to retrieve the list of ima>
Aug 16 11:08:15 ygversilhw lxd[15043]: lvl=eror msg="Failed to start the daemon: failed to begin transaction: unexpected response type 7" t=2018-08-1>
Aug 16 11:08:15 ygversilhw lxd[15043]: lvl=warn msg="Failed to rollback transaction after error (failed to query containers: unexpected response type>
Aug 16 11:08:16 ygversilhw lxd[15043]: lvl=eror msg="Dqlite: aborting (fd=18 state=body msg=response write error: broken pipe (EPIPE))" t=2018-08-16T>
Aug 16 11:08:16 ygversilhw lxd[15043]: Error: failed to begin transaction: unexpected response type 7
Aug 16 11:08:16 ygversilhw systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 11:08:16 ygversilhw systemd[1]: lxd.service: Failed with result 'exit-code'.
 
- [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

INFO[08-16|11:38:06] LXD 3.4 is starting in normal mode       path=/var/lib/lxd
INFO[08-16|11:38:06] Kernel uid/gid map: 
INFO[08-16|11:38:06]  - u 0 0 4294967295 
INFO[08-16|11:38:06]  - g 0 0 4294967295 
INFO[08-16|11:38:06] Configured LXD uid/gid map: 
INFO[08-16|11:38:06]  - u 0 1000000 65536 
INFO[08-16|11:38:06]  - g 0 1000000 65536 
WARN[08-16|11:38:06] AppArmor support has been disabled because of lack of kernel support 
INFO[08-16|11:38:06] Initializing local database 
INFO[08-16|11:38:06] Initializing database gateway 
INFO[08-16|11:38:06] Start database node                      address= id=1
INFO[08-16|11:38:06] Raft: Restored from snapshot 1-31143-1534410165159 
INFO[08-16|11:38:06] Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}] 
INFO[08-16|11:38:06] Raft: Node at 0 [Leader] entering Leader state 
INFO[08-16|11:38:06] Dqlite: starting event loop 
DBUG[08-16|11:38:06] Dqlite: accepting connections 
INFO[08-16|11:38:06] LXD isn't socket activated 
INFO[08-16|11:38:06] Starting /dev/lxd handler: 
INFO[08-16|11:38:06]  - binding devlxd socket                 socket=/var/lib/lxd/devlxd/sock
INFO[08-16|11:38:06] REST API daemon: 
INFO[08-16|11:38:06]  - binding Unix socket                   socket=/var/lib/lxd/unix.socket
INFO[08-16|11:38:06] Initializing global database 
INFO[08-16|11:38:06] Dqlite: handling new connection (fd=18) 
INFO[08-16|11:38:06] Dqlite: connected address=0 attempt=0 
INFO[08-16|11:38:09] Initializing storage pools 
DBUG[08-16|11:38:10] Initializing and checking storage pool "default" 
DBUG[08-16|11:38:12] Checking BTRFS storage pool "default" 
INFO[08-16|11:38:13] Initializing networks 
DBUG[08-16|11:38:24] Connecting to a remote simplestreams server 
INFO[08-16|11:38:24] Pruning leftover image files 
INFO[08-16|11:38:25] Done pruning leftover image files 
INFO[08-16|11:38:25] Loading configuration 
DBUG[08-16|11:38:25] Initialized inotify with file descriptor 17 
INFO[08-16|11:38:32] Connected to MAAS controller 
INFO[08-16|11:38:33] Pruning expired images 
INFO[08-16|11:38:34] Done pruning expired images 
INFO[08-16|11:38:34] Updating instance types 
INFO[08-16|11:38:34] Expiring log files 
INFO[08-16|11:38:35] Done updating instance types 
INFO[08-16|11:38:36] Updating images 
INFO[08-16|11:38:37] Done expiring log files 
DBUG[08-16|11:38:44] Database error: &errors.errorString{s:"sql: no rows in result set"} 
INFO[08-16|11:38:51] Dqlite: closing client 
INFO[08-16|11:38:51] Dqlite: handling new connection (fd=22) 
INFO[08-16|11:38:51] Dqlite: connected address=0 attempt=0 
DBUG[08-16|11:38:54] Database error: &errors.errorString{s:"sql: no rows in result set"} 
INFO[08-16|11:38:54] Done updating images 
WARN[08-16|11:39:27] Failed to rollback transaction after error (Failed to fetch nodes: driver: bad connection): unexpected response type 7 
DBUG[08-16|11:39:27] Database error: Failed to fetch nodes: driver: bad connection 
DBUG[08-16|11:39:27] Retry failed db interaction (Failed to fetch nodes: driver: bad connection) 
WARN[08-16|11:39:28] Failed to rollback transaction after error (Failed to fetch nodes: unexpected response type 6): unexpected response type 7 
DBUG[08-16|11:39:28] Database error: Failed to fetch nodes: unexpected response type 6 
WARN[08-16|11:39:28] Failed to get current cluster nodes: Failed to fetch nodes: unexpected response type 6

**Comment by freeekanayaka** [comment]
You mention that you upgraded to lxd 3.3, but I assume you meant 3.4 (as also shown by the logs).

**Comment by freeekanayaka** [comment]
Does this issue happens consistently every time you try to (re)start the LXD daemon?

Would it be possible for you to make a tarball of /var/lib/lxd/database and send it to me so I can probably reproduce the failure here? my mail is free.ekanayaka at canonical dot com

**Comment by ygversil** [comment]
Indeed, I didn't catch the version mismatch. The Archlinux package manager says (`pacaur -Qs lxd`) `local/lxd 3.3-3` while lxd reports itself as 3.4. I'll report this to the package maintainer.

I've just restarted the lxd service to check again. Now the service state is `active (running)`. But `lxc list` and `lxc info` keeps showing `500 Internal Server Error`. And journalctl is fiiled up with the same error messages ::

    Aug 16 14:25:40 ygversilhw lxd[8541]: lvl=warn msg="Failed to rollback transaction after error (Failed to fetch nodes: unexpected response type 6): cannot start a transaction within a transaction" t=2018-08-16T14:25:40+0200
    Aug 16 14:25:40 ygversilhw lxd[8541]: lvl=warn msg="Failed to get current cluster nodes: Failed to fetch nodes: unexpected response type 6" t=2018-08-16T14:25:40+0200
    Aug 16 14:25:41 ygversilhw lxd[8541]: lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: cannot start a transaction within a transaction" t=2018-08-16T14:25:41+0200
    Aug 16 14:25:42 ygversilhw lxd[8541]: lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: unexpected response type 7" t=2018-08-16T14:25:42+0200

**Comment by ygversil** [comment]
Hum... For the version mismatch, this is quite weird. The tarball that is actually downloaded from Github is lxd-3.3.tar.gz. So I can't figure out for now how `lxd --version` can reports 3.4.

**Comment by freeekanayaka** [comment]
I believe I have a clue of what's going on. It's a bug in dqlite/go-dqlite, I'll prepare a fix.

**Comment by stgraber** [comment]
I don't know how the ArchLinux packaging works, but hopefully a rebuild will pick up the new dqlite and go-dqlite, otherwise you may want to talk to the AUR maintainer about picking those fixes up ^

**Comment by tkedwards** [comment]
You guys work fast! From report to fix in < day.
Do you know how long this'll take to land in the LXD snap?

**Comment by ygversil** [comment]
Thanks for the quick fix!

It's better now, but lxd seems to have an erratic behavior. After a service restart, I have the same error message (`driver: bad connection: unexpected response type 7`). But after another restart, it's working fine (`lxc info` and `lxc list --fast` produce correct outputs). And then, after another restart, the error message is back again.

I'll give more feedback after a clean hardware reboot and I'll try to add/delete another container again to see what happens.

Thank you.

**Comment by freeekanayaka** [comment]
@ygversil : just to double check, can you paste here the git hashes of the dqlite and go-dqlite commits that you used to build libdqlite and lxd? (assuming you did it by yourself, otherwise if you can point to where you got the build from)

**Comment by ygversil** [comment]
@freeekanayaka : I've rebuild dqlite then lxd using pacaur and Archlinux PKGBUILD files. In a few words, a PKGBUILD is like a Makefile that pacaur follows to build a tarball (.pkg.tar.gz) that can then be installed with pacman, the Archlinux package manger. Hopefully, those files are self explanatory.

For dqlite, I've been using this file :

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dqlite-git

I replaced the line starting with `pkgver` with `pkgver=r320.e374516`. This is mostly useless anyway since that, according to the `source` line, pacaur will always clone latest commit from the master branch before going to the `prepare()` and `build()` functions.

For lxd, I've used this file as-is : 

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lxd

I presume that `make` in the `build()` function will clone and build any Go dependency from Github, including go-dqlite.

And indeed, if I `git log` in the source folders the last commit for dqlite is `e374516` and for go-dqlite is `2ef866b`.

**Comment by freeekanayaka** [comment]
So there are only two options, either the bug is still not fixed despite my commits, or somehow you're not linking or building lxd against the correct dqlite version (but it's very unlikely since you'd probably get some other error due to the go-dqlite version being pulled from github being newer than dqlite).

If you can double check the output of "ldd $(which lxd)"?

Assuming that the bug is still there, I'd ask you to either send me a tarball of your /var/lib/lxd/database directory in the hope I can reproduce the issue or perhaps I'll have to send you a patch/branch for getting more debug log.

**Comment by tkedwards** [comment]
Is there any workaround until the fix comes out?

**Comment by stgraber** [comment]
@tkedwards the snap has the fix, for other distros, you either need to rebuild with the changes from @freeekanayaka applied or need to contact the packager to have them included.

**Comment by tkedwards** [comment]
I don't think this is fixed, either that or the brokenness of the current LXD is preventing snap from applying the fixed version (which I assume is in the Edge channel):
```
snap refresh --edge lxd
error: cannot perform the following tasks:
- Start snap "lxd" (8411) services ([start snap.lxd.activate.service] failed with exit status 1: Job for snap.lxd.activate.service failed because the control process exited with error code. See "systemctl status snap.lxd.activate.service" and "journalctl -xe" for details.
)
tim@timserver:~/setup/linux_common/auto/containers$ systemctl status snap.lxd.activate.service
● snap.lxd.activate.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: exit-code) since Sat 2018-08-18 15:00:42 AEST; 37s ago
 Main PID: 4599 (code=exited, status=1/FAILURE)
```

```
Aug 18 15:00:39 timserver. systemd[1]: Starting Service for snap application lxd.activate...
Aug 18 15:00:42 timserver. lxd.activate[4599]: Error: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: no such file or directory
Aug 18 15:00:42 timserver. systemd[1]: snap.lxd.activate.service: Main process exited, code=exited, status=1/FAILURE
Aug 18 15:00:42 timserver. systemd[1]: Failed to start Service for snap application lxd.activate.
Aug 18 15:00:42 timserver. systemd[1]: snap.lxd.activate.service: Unit entered failed state.
Aug 18 15:00:42 timserver. systemd[1]: snap.lxd.activate.service: Failed with result 'exit-code'.
Aug 18 15:00:42 timserver. systemd[1]: Stopped Service for snap application lxd.activate.
tim@timserver:~/setup/linux_common/auto/containers$ less /var/log/syslog

Aug 18 15:00:53 timserver snapd[1412]: 2018/08/18 15:00:53.747785 handlers.go:388: Reported install problem for "lxd" as aea3ae2e-a2a3-11e8-8857-fa163e0ec2f1 OOPSID
Aug 18 15:01:01 timserver CRON[5087]: (tim) CMD (test -e /etc/connected && /usr/local/bin/sync_imap_accts.sh)
Aug 18 15:01:05 timserver dovecot: imap-login: Login: user=<tim>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=5098, secured, session=<ZeBAkK5zdrN/AAAB>
Aug 18 15:01:06 timserver lxd.daemon[4889]: lvl=warn msg="Failed to rollback transaction after error (driver: bad connection): unexpected response type 7" t=2018-08-18T15:01:06+1000
Aug 18 15:01:10 timserver lxd.daemon[4889]: err="failed to begin transaction: unexpected response type 7" lvl=eror msg="Unable to retrieve the list of images" t=2018-08-18T15:01:10+1000
Aug 18 15:01:11 timserver lxd.daemon[4889]: lvl=warn msg="Failed to rollback transaction after error (cannot fetch node config from database: unexpected response type 6): cannot start a transaction within a transaction" t=2018-08-18T15:01:11+1000
Aug 18 15:01:11 timserver lxd.daemon[4889]: lvl=eror msg="Failed to start the daemon: cannot fetch node config from database: unexpected response type 6" t=2018-08-18T15:01:11+1000
Aug 18 15:01:12 timserver lxd.daemon[4889]: lvl=eror msg="Dqlite: aborting (fd=23 state=body msg=response write error: broken pipe (EPIPE))" t=2018-08-18T15:01:12+1000
Aug 18 15:01:12 timserver lxd.daemon[4889]: Error: cannot fetch node config from database: unexpected response type 6
Aug 18 15:01:13 timserver lxd.daemon[4889]: => LXD failed to start
Aug 18 15:01:13 timserver systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=137/n/a
Aug 18 15:01:13 timserver lxd.daemon[5108]: => Stop reason is: crashed
Aug 18 15:01:13 timserver systemd[1]: snap.lxd.daemon.service: Unit entered failed state.
Aug 18 15:01:13 timserver systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
Aug 18 15:01:13 timserver systemd[1]: snap.lxd.daemon.service: Service hold-off time over, scheduling restart.
Aug 18 15:01:13 timserver systemd[1]: Stopped Service for snap application lxd.daemon.
Aug 18 15:01:13 timserver systemd[1]: Started Service for snap application lxd.daemon.
Aug 18 15:01:13 timserver lxd.daemon[5144]: => Preparing the system
Aug 18 15:01:13 timserver lxd.daemon[5144]: ==> Loading snap configuration
Aug 18 15:01:13 timserver lxd.daemon[5144]: ==> Setting up mntns symlink (mnt:[4026532306])
Aug 18 15:01:13 timserver lxd.daemon[5144]: ==> Setting up kmod wrapper
Aug 18 15:01:13 timserver lxd.daemon[5144]: ==> Preparing /boot
Aug 18 15:01:13 timserver lxd.daemon[5144]: ==> Preparing a clean copy of /run
Aug 18 15:01:13 timserver lxd.daemon[5144]: ==> Preparing a clean copy of /etc
Aug 18 15:01:14 timserver lxd.daemon[5144]: ==> Setting up ceph configuration
Aug 18 15:01:14 timserver lxd.daemon[5144]: ==> Setting up LVM configuration
Aug 18 15:01:14 timserver lxd.daemon[5144]: ==> Rotating logs
Aug 18 15:01:14 timserver lxd.daemon[5144]: ==> Setting up ZFS (0.6)
Aug 18 15:01:14 timserver lxd.daemon[5144]: ==> Escaping the systemd cgroups
Aug 18 15:01:14 timserver lxd.daemon[5144]: ==> Escaping the systemd process resource limits
Aug 18 15:01:14 timserver lxd.daemon[5144]: => Re-using existing LXCFS
Aug 18 15:01:14 timserver lxd.daemon[5144]: => Starting LXD
Aug 18 15:01:14 timserver lxd.daemon[5144]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-08-18T15:01:14+1000
do lxd --debug --group lxd
```

**Comment by stgraber** [comment]
@tkedwards what distribution are you running? The error above seems related to the newly added socket activation code in edge rather than LXD 3.4.

**Comment by tkedwards** [comment]
@stgraber I tried using the normal lxd Snap (stable branch, 3.4) but ran into the same database problem as before. I then tried the Edge channel snap but that didn't work either.
I've now switched back to the stable branch Snap and rebooted the host, and LXD at least starts now. But it doesn't see any of my containers, they're all there under /var/snap/lxd/common/lxd/storage-pools/default/containers/ but 'lxc list local:' shows no containers and for storage I have:
$ lxc storage list local:
+------+-------------+--------+--------+---------+
| NAME | DESCRIPTION | DRIVER | SOURCE | USED BY |
+------+-------------+--------+--------+---------+

Is there any way to get it to see the containers again? I'd rather not have to re-create the containers again.

**Comment by freeekanayaka** [comment]
@ygversil Is everything you described deterministic? In other words, does LXD work fine (and keeps working fine for as long as you can see) after every single reboot? And does it immediately error after every single time you restart the lxd process? If that's the case, I think it should be easy to get to the bottom of it.

**Comment by ygversil** [comment]
@freeekanayaka rectification: the error does not occur anymore, no matter how many times I restart the service. So as far as I know: problem solved! :)

Thank you so much for your time and reactivity!
