### ISSUE TITLE
Cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied

### ISSUE THREAD

**Issue by 19wolf** [lxc/lxd#4933]
# Required information

 * Distributor ID:	Ubuntu
* Description:	Ubuntu 18.04.1 LTS
* Release:	18.04
* Codename:	bionic
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.18.0-041800-generic
   * LXC version: Unsure, probably latest?
   * LXD version: 3.4
   * Storage backend in use: Btrfs

# Issue description

```
$ lxc list
cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied
$ lxc info
cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied
```

# Steps to reproduce

 1. Update kernel to 4.18.0
 2. run lxc list
 3. Error
# Information to attach

```
$ dmesg > before; lxc list; sleep 2; dmesg > after; diff before after
cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied
888a889
> [ 3311.345207] audit: type=1400 audit(1534446773.155:76): apparmor="DENIED" operation="ptrace" profile="/snap/core/5145/usr/lib/snapd/snap-confine" pid=5760 comm="snap-confine" requested_mask="read" denied_mask="read" peer="unconfined"
```

**Comment by stgraber** [comment]
That's a snapd bug related to the 4.18 kernel, not a LXD issue.
If possible, stay away from the 4.18 kernel for the next few weeks at least as that gets worked on.

https://forum.snapcraft.io/t/custom-kernel-error-on-readlinkat-in-mount-namespace/6097/34

**Comment by stgraber** [comment]
Apparently updating to the beta channel of the core snap may help?
`snap refresh core --beta`
