### ISSUE TITLE
dnsmasq process dies after starting - containers don't obtain IP addresses

### ISSUE THREAD

**Issue by tokiwinter** [lxc/lxd#4934]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.5 LTS
 * The output of "lxc info" or if that fails:
```
# lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    REDACTED
  certificate_fingerprint: REDACTED
  driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-1063-aws
  server: lxd
  server_pid: 2864
  server_version: 3.0.0
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: node-1
```

# Issue description

We run multiple lxd containers over multiple lxd networks. These are short lived instances. Around 1/8 instances are affected with an issue where the appropriate `dnsmasq` process starts, then fails, and the containers attached to that bridged interface fail to obtain IP addresses.

For example, I can see the `dnsmasq` process starting:

```
Aug 17 00:26:36 node-1 dnsmasq[3351]: started, version 2.75 cachesize 150
Aug 17 00:26:36 node-1 dnsmasq[3351]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntr
ack ipset auth DNSSEC loop-detect inotify
Aug 17 00:26:36 node-1 dnsmasq-dhcp[3351]: DHCP, IP range 10.250.3.2 -- 10.250.3.128, lease time 1h
Aug 17 00:26:36 node-1 dnsmasq-dhcp[3351]: DHCP, sockets bound exclusively to interface pcmkbr0
Aug 17 00:26:36 node-1 dnsmasq[3351]: using local addresses only for domain lxd
Aug 17 00:26:36 node-1 dnsmasq[3351]: reading /etc/resolv.conf
Aug 17 00:26:36 node-1 dnsmasq[3351]: using local addresses only for domain lxd
Aug 17 00:26:36 node-1 dnsmasq[3351]: using nameserver 10.70.0.2#53
Aug 17 00:26:36 node-1 dnsmasq[3351]: read /etc/hosts - 28 addresses
Aug 17 00:26:36 node-1 dnsmasq[3351]: read /etc/hosts - 28 addresses
```

However, that process dies at some point after starting:

```
root@node-1:~# ps -ef | grep dnsmasq | grep 250.3
root@node-1:~#
```

And the containers that use that bridge do not obtain IP addresses:

```
root@node-1:~# lxc list pcmk-[01]
+--------+---------+------+------+------------+-----------+
|  NAME  |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+--------+---------+------+------+------------+-----------+
| pcmk-0 | RUNNING |      |      | PERSISTENT | 0         |
+--------+---------+------+------+------------+-----------+
| pcmk-1 | RUNNING |      |      | PERSISTENT | 0         |
+--------+---------+------+------+------------+-----------+
```
All other containers (around 20 of them, spread across multiple networks) obtain IP addresses fine.

We also run lxd on CentOS and do not experience this issue there.

Please let me know what further information you require.

**Comment by stgraber** [comment]
Please show `dpkg -l | grep dnsmasq`, I wonder if the system somehow has a potentially conflicting system dnsmasq instance.

Also `lxc network list` and `lxc network show` for the LXD managed bridges would be useful as well as showing `ps aux | grep dnsmasq` just after restarting LXD with `systemctl restart lxd` to see how they come up.

My main guess right now is that dnsmasq either crashes immediately or some system process is "restarting" dnsmasq with something naive like a "pkill dnsmasq", killing LXD's dnsmasq processes by mistake...

**Comment by stgraber** [comment]
Also, please make sure your systems are up to date, the versions you reported above suggests that they're not.

**Comment by tokiwinter** [comment]
Should I be installing `3.0.1-0ubuntu1~16.04.4` from `xenial-backports` rather than using snaps now?

**Comment by stgraber** [comment]
Using the snap is fine, but you're not using anything vaguely current as far as the snap goes.
What does `snap list` and `snap info lxd` show you?

**Comment by stgraber** [comment]
If you're on the 3.0 track, you should be on 3.0.1, if you're on the latest track, you should be on 3.4, 3.0.0 isn't currently available in any snap channels.

**Comment by tokiwinter** [comment]
We are using a custom built snap (built from source at 3.0.0).:
```
root@node-1:~# snap list
Name  Version    Rev   Tracking  Publisher  Notes
core  16-2.34.3  5145  stable    canonical  core
lxd   3.0.0      x1    -         -          -
```
I think the first course of action is to get this updated. Thanks for the help so far.

**Comment by stgraber** [comment]
Oh yeah, you'd definitely want to update that :)
Why are you building your own snap rather than running the supported one?

**Comment by tokiwinter** [comment]
Thanks, I've changed to using `--channel=3.0` during our build, and will see how we go with that. I'll re-open should the issue arise again. Thanks for your prompt assistance, it is appreciated.
