### ISSUE TITLE
LXD cluster: all lxc related command hangs on http://unix.socket/1.0

### ISSUE THREAD

**Issue by syswipe** [lxc/lxd#4937]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.5 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.4.0-128-generic
   * LXC version: 3.4
   * LXD version: 3.4
   * Storage backend in use: LVM

# Issue description

I can't interact with my cluster and containers at all. All commands hangs and don't return anythin

# Steps to reproduce

 1. Login to lxd host
 2. run any command, for ex. lxc list

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
in attachment [lxd-logs.zip](https://github.com/lxc/lxd/files/2297157/lxd-logs.zip)

 - [x] Output of the client with --debug 
```
lxc --debug list
DBUG[08-17|14:14:10] Connecting to a local LXD over a Unix socket 
DBUG[08-17|14:14:10] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
```
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by freeekanayaka** [comment]
It seems two nodes were upgraded from 3.3 to 3.4 and another one is still running 3.3. Please make sure all your nodes are at 3.4 and possibly restart them.

**Comment by stgraber** [comment]
@freeekanayaka what's odd though is the hang on /1.0, aren't /1.0, /1.0/cluster/* supposed to keep working in such a situation?

**Comment by stgraber** [comment]
@syswipe any update?

**Comment by stgraber** [comment]
Closing as this lines up with a cluster upgrade and we have #4942 to track the improve user experience.
Let us know if it was something else.

**Comment by skyford** [comment]
Encounter the same problem on a fresh lxd install,  all cmds hanges, except "lxc remote list"

**Comment by stgraber** [comment]
@skyford your symptoms are consistent with LXD failing to start due to socket activation and so has nothing to do with a cluster upgrade scenario.

You should look at `journalctl -u snap.lxd.daemon` if using the snap or `journalctl -u lxd` if using the deb, those should include some more details as to why the daemon would fail to start on your system.

(`lxc remote` works because it doesn't actually talk to the daemon at all)
