### ISSUE TITLE
Container copy fails from lxd 3.4 to lxd 2.1 instance

### ISSUE THREAD

**Issue by ubojan** [lxc/lxd#4938]
# Required information

 * Distribution:
Ubuntu
 * Distribution version:
Ubuntu 18.04 on origin, Ubuntu 16.04 on destination
 * The output of "lxc info"
   * Origin server:
config:
  core.https_address: xxx.xxx.xxx.xxx
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - xxx.xxx.xxx.xxx:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
xxx
    -----END CERTIFICATE-----
  certificate_fingerprint: xxx
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-1009-gcp
  server: lxd
  server_pid: 115875
  server_version: "3.4"
  storage: zfs
  storage_version: 0.7.9-3ubuntu2~18.04.york0
  server_clustered: false
  server_name: server1
   * Destination server
config:
  core.https_address: xxx.xxx.xxx.xxx
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - xxx.xxx.xxx.xxx:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
xxx
    -----END CERTIFICATE-----
  certificate_fingerprint: xxx
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-1014-gcp
  server: lxd
  server_pid: 15167
  server_version: "2.21"
  storage: zfs
  storage_version: 0.7.6-0york2~16.04

# Issue description

root@server1:~# lxc copy server2:rvE-xxx/xxx-1533388874-autodaily testbojan
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/lxc/lxd/client.(*ProtocolLXD).CopyContainerSnapshot(0xc4201083f0, 0xe19b40, 0xc4201081b0, 0xc4201a5a88, 0x6, 0xc420272b40, 0x0, 0xed2f79f4a, 0x0, 0xc420272ba0, ...)
	/build/lxd-C7csRV/lxd-2.21/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/client/lxd_containers.go:913 +0x1499
main.(*copyCmd).copyContainer(0xc42008cb90, 0xc42006c7e0, 0x7ffe0cc97753, 0x35, 0x7ffe0cc97789, 0x9, 0x6f4900, 0x0, 0x1, 0x9819e8, ...)
	/build/lxd-C7csRV/lxd-2.21/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/copy.go:139 +0x6e2
main.(*copyCmd).run(0xc42008cb90, 0xc42006c7e0, 0xc4200f1680, 0x2, 0x2, 0x0, 0x0)
	/build/lxd-C7csRV/lxd-2.21/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/copy.go:262 +0x14a
main.run(0x0, 0x0)
	/build/lxd-C7csRV/lxd-2.21/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:175 +0x851
main.main()
	/build/lxd-C7csRV/lxd-2.21/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:32 +0x6e

# Steps to reproduce

 1. Copy container from server with lxd 3.4 installed to server with lxd 2.1 installed.
 2. You'll see "panic: runtime error: index out of range". Complete error output in Issue Description section.

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
no entries
 - [x] Container log (`lxc info NAME --show-log`)
no entries
 - [x] Container configuration (`lxc config show NAME --expanded`)

architecture: x86_64
config:
  boot.autostart: "true"
  limits.cpu: "12"
  limits.memory: 8GB
  volatile.base_image: f4c4c60a6b752a381288ae72a1689a9da00f8e03b732c8d1b8a8fcd1a8890800
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.lxdbr0.hwaddr: 00:16:3e:2f:55:78
  volatile.lxdbr0.name: eth0
devices:
  lxdbr0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
no new entries
 - [ ] Output of the client with --debug
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
metadata:
  context: {}
  level: dbug
  message: 'New event listener: 91910ea2-5503-4b32-816a-ce1bd5cb41e1'
timestamp: "2018-08-17T13:55:17.683858366Z"
type: logging

metadata:
  context:
    k: "1"
  level: dbug
  message: Found cert
timestamp: "2018-08-17T13:55:20.095356822Z"
type: logging

metadata:
  context:
    ip: 10.240.0.69:59668
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2018-08-17T13:55:20.095403671Z"
type: logging

metadata:
  context:
    k: "1"
  level: dbug
  message: Found cert
timestamp: "2018-08-17T13:55:20.096006381Z"
type: logging

metadata:
  context:
    ip: 10.240.0.69:59670
    method: GET
    url: /1.0/containers/rvE-xxx/snapshots/xxx-1533388874-autodaily
  level: dbug
  message: handling
timestamp: "2018-08-17T13:55:20.142132875Z"
type: logging

metadata:
  context:
    k: "1"
  level: dbug
  message: Found cert
timestamp: "2018-08-17T13:55:20.142102146Z"
type: logging

**Comment by stgraber** [comment]
@ubojan so looks like you're using the 2.21 client to have LXD move a container from 3.4 to 2.21, that client then crashes when trying to parse a container snapshot name.

Could you try doing this using the 3.4 client instead? That one should know about both the broken and fixed container snapshot naming and so be able to perform what you want.

In general when dealing with multiple LXD versions, you always want to use the client from the most recent one to interact with the others.

**Comment by ubojan** [comment]
Thanks for your response. Yup I can confirm that moving works fine in all other cases:
- from 3.4 to 3.4
- from 2.1 to 3.4
- form 2.1 to 2.1
Only issue is moving from 3.4 to 2.1

**Comment by stgraber** [comment]
That does not answer my question though.

Can you please try the following:
 - On the system that's got LXD 3.4, add the system that's got LXD 2.21 as a remote
 - Move your container from LXD 3.4 to 2.21 using that remote and the 3.4 version of the client

**Comment by stgraber** [comment]
So just tested it here, with two servers, one on 3.4 and other on 2.21. For the exact same copy of a snapshot from the 3.4 server over to the 2.21 server, using the 2.21 client crashes, using the 3.4 client doesn't.

So this effectively works as expected. Your transfer will work fine, just have it triggered by the new version of the client tool.
