### ISSUE TITLE
LXD deamon stops working after a while in UBuntu 18.04 Server (Lots of processes)

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#4941]
# Required information

 * Distribution: **Ubuntu**
 * Distribution version: **18.04 LTS**
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: **3.0.1**
   * LXD version: **3.0.1**
   * Storage backend in use: **ZFS**

# Issue description

We are running Ubuntu 18.04 LTS Server on multiple physical servers and are making largely use of LXD containers to run applications and services. We have found that on multiple servers LXD would be running an enormous amount of processes and then overtime will become totally useless and will cause the lxd daemon to become inactive. So when you try to run "**lxc list**" or any other lxc commands, it first becomes much slower to show the results, then it becomes inactive where it does not show you anything. It gets to a point where we need to reboot the server everytime. Something with the LXD daemon starts going wrong as the system us being used.  

What can we do and why does LXD seems to be more unstable since the latest release of 3.0.1?

**Comment by stgraber** [comment]
What do you mean with running an enormous amount of processes?
Do you see a lot of subprocesses directly below LXD in `ps fauxww`?

**Comment by stgraber** [comment]
There is a known memory leak issue in LXD 3.0.1 which would account for the decrease in performance over time, that's fixed in 3.0.2 which we released yesterday, so the fix will be showing up soon (probably 10 days or so...). But that wouldn't explain `enormous amount of processes` though.

**Comment by elbrinke** [comment]
Hi @stgraber, 

We rebooted the server now.. So it seems fine for now. But if keeps happening overtime.. It could be due to the memory leak issue mentioned. 

Re: _enormous amount of processes_, that could be due to the fact that when we try to run lxc commands and its slow or it fails, it seems to still keep the previous lxc command instances and just seems to get worse from there. 

See current ps output of server. 
[ps_output.log](https://github.com/lxc/lxd/files/2297825/ps_output.log)

**Comment by stgraber** [comment]
@elbrinke that `ps` output doesn't show any sub-processes on LXD itself. So I'm assuming you had quite a different output before?

**Comment by stgraber** [comment]
Note that rebooting shouldn't be needed, a simple `systemctl restart lxd` will restart LXD without affecting containers and has been confirmed to reset the memory leak.

**Comment by elbrinke** [comment]
@stgraber , when we do a `systemctl restart lxd` , it would just hang and not restart lxd. That is why we need to so a system reboot, because our first option is always to just restart the service.

**Comment by elbrinke** [comment]
Although the memory leak would as you mentioned: `decrease in performance over time,` what would cause it to become unresponsive? Since our issue is that when we execute lxc commands, we notice that the lxc responses becomes slower and slower to the point where it just hangs. Even trying to restart the lxd service hangs.

**Comment by stgraber** [comment]
The two issues we have in 3.0.1 cause a memory leak and a fd leak, so if you eventually reach the maximum number of files, I'd expect it to completely lockup... It's the first time we've had a report of it going so bad though, other reports were of up to 150MB of leakage per day and it taking multiple minutes to list containers...

Did you try to "kill -9" the LXD process? did that also fail?
If so, you may be running into a kernel issue rather than a LXD issue.

**Comment by elbrinke** [comment]
@stgraber , I will check it out on Monday again and during next week and see how it goes. If it happens again i will let you know. But thanks a lot for responding so quickly. It gives us a lot confidence in the support for LXD. 

From the sounds of it, it sounds like what we experienced as a memory leak and possible fd leak as well. I will keep a close eye on it. It's just that when we for instance ran a **"htop"** and filtered all LXD processes, there was really a lot of processes, which we could not understand. 

I attached a screenshot of the lxd processes at idle. Just a lot of processes for logs. 

![lxd_idle_state](https://user-images.githubusercontent.com/1333256/44277547-5f4e1600-a24b-11e8-834f-af38b4d15c14.png)

**Comment by stgraber** [comment]
Ok, I believe that part is normal, assuming that your `htop` is configured to show threads instead of only processes.

I'll tentatively close this issue as we did track down and fix those leaks. LXD 3.0.2 should then take care of those for you.

Comment here if anything else shows up and we'll look into that.

**Comment by elbrinke** [comment]
Thanks @stgraber , will do :)
