### ISSUE TITLE
Facing issue with Ansible playbook

### ISSUE THREAD

**Issue by enggnehaverma** [lxc/lxd#4953]
I am getting error as attached :- 

![screen shot 2018-08-20 at 11 41 00 pm](https://user-images.githubusercontent.com/41340993/44395986-720a6880-a533-11e8-9c26-d4345c0edbbc.png)

**Comment by stgraber** [comment]
@enggnehaverma please include all the information that's requested when filing a bug, then we'll be able to take a closer look.

That screenshot above just shows apt errors, there's no hint of LXD anywhere in there. It's unclear if you're running this inside a container or not and I don't think any of us have any Ansible experience at all.

Not knowing anything about the environment, LXD versions, configuration, ... makes it impossible for us to do anything with this bug report.

Closing for now.
