### ISSUE TITLE
Please allow updating non-storage parameters (cpu, memory) for running containers with block device as a rootfs (ceph, lvm ..).

### ISSUE THREAD

**Issue by sergeyignatov** [lxc/lxd#4960]
# Required information
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-32-generic
  server: lxd
  server_pid: 285138
  server_version: "3.4"
  storage: ceph
  storage_version: ceph version 10.2.10 (5dc1e4c05cb68dbf62ae6fce3f0700e4654fdbbe)
  server_clustered: true

# Issue description

With zfs we could update resource limits  for running containers, but using ceph we have 
Error: Cannot resize RBD storage volume for container "XXXX" when it is running

# Steps to reproduce

 1. lxc config set test1 limits.memory "8GB"
 Error: Cannot resize RBD storage volume for container "test1" when it is running

**Comment by sergeyignatov** [comment]
lxc config show --expanded test1
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20180814)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20180814"
  image.version: "16.04"
  limits.cpu.allowance: 15%
  volatile.base_image: 9023b2feede581884cf45be29f60207ccc5553d762ea8088e849858a58762f6b
  volatile.eth0.hwaddr: 00:16:3e:0e:31:e0
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: remote
    size: 400GB
    type: disk
ephemeral: false
profiles:
- base
- d400
stateful: false
description: ""

lxc storage volume show remote container/test1
config:
  block.filesystem: ext4
  block.mount_options: discard
  size: 400GB
description: ""
name: test1
type: container
used_by:
- /1.0/containers/test1

**Comment by stgraber** [comment]
@sergeyignatov missing the `lxc storage show remote` output.

**Comment by sergeyignatov** [comment]
lxc storage show remote
config:
  ceph.cluster_name: ceph
  ceph.osd.pg_num: "32"
  ceph.osd.pool_name: lxd
  volatile.pool.pristine: "true"
description: ""
name: remote
driver: ceph
used_by:
- /1.0/containers/test1
- /1.0/containers/c10
- /1.0/containers/c100
- /1.0/containers/c101
.....
- /1.0/images/9023b2feede581884cf45be29f60207ccc5553d762ea8088e849858a58762f6b
- /1.0/images/bbb592c417b69ff8eac82df58ceeace2b4f58c09339e7ffc019a5069928648da
- /1.0/profiles/base
- /1.0/profiles/d400
- /1.0/profiles/default
status: Created
locations:
- lxd1
- lxd2
- lxd3
- lxd4

**Comment by stgraber** [comment]
Thanks, that should be enough to track this down.

**Comment by stgraber** [comment]
Managed to reproduce the issue here.
