### ISSUE TITLE
"lxc copy" failure

### ISSUE THREAD

**Issue by pcouderc12** [lxc/lxd#4962]
# Required information (source computer)

 * Distribution: debian
 * Distribution version: stretch
 * lxc info :

config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
...(standard compilation from git)
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.163.1:8443
  - '[2a01:e34:eeaf:c5f0:ca60:ff:fe54:fd23]:8443'
  architectures:
  - x86_64
  - i686
  certificate:
  ...
  certificate_fingerprint: 0a4e224566eeeb35a20472d35da18e8737193f69ff9bd2caba40f7a291dacc90
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.0-7-amd64
  server: lxd
  server_pid: 564
  server_version: "2.21"
  storage: btrfs
  storage_version: 4.7.3

# Required information (destination computer)

 * Distribution: debian
 * Distribution version: stretch
 * The output of "lxc info" or if that fails:
 config: {}
api_extensions:
...(stardard ompilation)
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate:
  ...
  certificate_fingerprint: 50037fbf06c6c0f676ff7460f13c73e0523026607462e61452f92245ecbbd967
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.0-7-amd64
  server: lxd
  server_pid: 2630
  server_version: "3.3"
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: couderc

# Issue description

root@couderc:~# lxc copy 192.168.163.1:debian
Error: Failed container creation:
 - https://192.168.163.1:8443: Error transferring container data: exit status 12
 - https://[2a01:e34:eeaf:c5f0:ca60:ff:fe54:fd23]:8443: Error transferring container data: websocket: bad handshake
root@couderc:~#

# Steps to reproduce

Easy to reproduce on my computers...

# Information to attach

I add the full "lxd monitor" from the source lxd. If useful, I can reproduce and monitor more :

metadata:
  context: {}
  level: dbug
  message: 'New events listener: 005732f6-0484-4a0e-bb71-83b22a2d6bd5'
timestamp: 2018-08-23T06:20:47.947287451+02:00
type: logging

metadata:
  context:
    k: "3"
  level: dbug
  message: Found cert
timestamp: 2018-08-23T06:21:20.574778506+02:00
type: logging

metadata:
  context:
    k: "3"
  level: dbug
  message: Found cert
timestamp: 2018-08-23T06:21:20.574676645+02:00
type: logging

metadata:
  context:
    ip: 192.168.163.253:53702
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2018-08-23T06:21:20.574741304+02:00
type: logging

metadata:
  context:
    k: "3"
  level: dbug
  message: Found cert
timestamp: 2018-08-23T06:21:20.672239291+02:00
type: logging

metadata:
  context:
    ip: 192.168.163.253:53704
    method: GET
    url: /1.0/containers/debian
  level: dbug
  message: handling
timestamp: 2018-08-23T06:21:20.67230506+02:00
type: logging

metadata:
  context:
    k: "3"
  level: dbug
  message: Found cert
timestamp: 2018-08-23T06:21:20.755910123+02:00
type: logging

metadata:
  context:
    ip: 192.168.163.253:53706
    method: GET
    url: /1.0/events
  level: dbug
  message: handling
timestamp: 2018-08-23T06:21:20.755961864+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: 'New events listener: 393839a3-d741-4352-af49-85f1436d3644'
timestamp: 2018-08-23T06:21:20.756047662+02:00
type: logging

metadata:
  context:
    k: "3"
  level: dbug
  message: Found cert
timestamp: 2018-08-23T06:21:20.830267016+02:00
type: logging

metadata:
  context:
    ip: 192.168.163.253:53708
    method: POST
    url: /1.0/containers/debian
  level: dbug
  message: handling
timestamp: 2018-08-23T06:21:20.830343661+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: 'New websocket operation: 90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427'
timestamp: 2018-08-23T06:21:20.831692278+02:00
type: logging

metadata:
  class: websocket
  created_at: 2018-08-23T06:21:20.83166888+02:00
  err: ""
  id: 90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427
  may_cancel: false
  metadata:
    control: fe331627fb95d660a4b898b3e8b57f52166fe5bd5810bcd8116d60579f9af05b
    fs: c452e824812ce4767bd14239157ec2828a4a2c183a0008790fb8cc3e3a7ecb96
  resources:
    containers:
    - /1.0/containers/debian
  status: Pending
  status_code: 105
  updated_at: 2018-08-23T06:21:20.83166888+02:00
timestamp: 2018-08-23T06:21:20.831735097+02:00
type: operation

metadata:
  context: {}
  level: dbug
  message: 'Started websocket operation: 90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427'
timestamp: 2018-08-23T06:21:20.831783309+02:00
type: logging

metadata:
  class: websocket
  created_at: 2018-08-23T06:21:20.83166888+02:00
  err: ""
  id: 90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427
  may_cancel: false
  metadata:
    control: fe331627fb95d660a4b898b3e8b57f52166fe5bd5810bcd8116d60579f9af05b
    fs: c452e824812ce4767bd14239157ec2828a4a2c183a0008790fb8cc3e3a7ecb96
  resources:
    containers:
    - /1.0/containers/debian
  status: Running
  status_code: 103
  updated_at: 2018-08-23T06:21:20.83166888+02:00
timestamp: 2018-08-23T06:21:20.831837868+02:00
type: operation

metadata:
  context:
    ip: 192.168.163.253:53710
    url: /1.0/operations/90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427/websocket?secret=fe331627fb95d660a4b898b3e8b57f52166fe5bd5810bcd8116d60579f9af05b
  level: dbug
  message: allowing untrusted GET
timestamp: 2018-08-23T06:21:21.315730259+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: 'Handled websocket operation: 90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427'
timestamp: 2018-08-23T06:21:21.315981368+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: 'Connected websocket operation: 90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427'
timestamp: 2018-08-23T06:21:21.315792239+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: 'Connected websocket operation: 90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427'
timestamp: 2018-08-23T06:21:21.355682766+02:00
type: logging

metadata:
  context:
    ip: 192.168.163.253:53712
    url: /1.0/operations/90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427/websocket?secret=c452e824812ce4767bd14239157ec2828a4a2c183a0008790fb8cc3e3a7ecb96
  level: dbug
  message: allowing untrusted GET
timestamp: 2018-08-23T06:21:21.355624024+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: 'Handled websocket operation: 90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427'
timestamp: 2018-08-23T06:21:21.357889913+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: Initializing a BTRFS driver.
timestamp: 2018-08-23T06:21:21.362965503+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage volume for container "debian" on storage pool "default".
timestamp: 2018-08-23T06:21:21.363027464+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage pool "default".
timestamp: 2018-08-23T06:21:21.364004596+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: Mounted BTRFS storage volume for container "debian" on storage pool "default".
timestamp: 2018-08-23T06:21:21.364927527+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: The other side does not support pre-copy
timestamp: 2018-08-23T06:21:21.366272637+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: Got message barrier, resetting stream
timestamp: 2018-08-23T06:21:21.526446217+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: sending write barrier
timestamp: 2018-08-23T06:21:21.526602299+02:00
type: logging

metadata:
  context: {}
  level: eror
  message: |
    Rsync send failed: /var/lib/lxd/containers/debian/: exit status 10: rsync: [sender] write error: Broken pipe (32)
    rsync error: error in socket IO (code 10) at io.c(829) [sender=3.1.2]
timestamp: 2018-08-23T06:21:21.630185065+02:00
type: logging

metadata:
  context: {}
  level: dbug
  message: 'Failure for websocket operation: 90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427:
    exit status 10'
timestamp: 2018-08-23T06:21:21.6309405+02:00
type: logging

metadata:
  class: websocket
  created_at: 2018-08-23T06:21:20.83166888+02:00
  err: exit status 10
  id: 90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427
  may_cancel: false
  metadata:
    control: fe331627fb95d660a4b898b3e8b57f52166fe5bd5810bcd8116d60579f9af05b
    fs: c452e824812ce4767bd14239157ec2828a4a2c183a0008790fb8cc3e3a7ecb96
  resources:
    containers:
    - /1.0/containers/debian
  status: Failure
  status_code: 400
  updated_at: 2018-08-23T06:21:20.83166888+02:00
timestamp: 2018-08-23T06:21:21.630997954+02:00
type: operation

metadata:
  context:
    ip: '[2a01:e34:eeaf:c5f0:80d4:34ff:fee9:46b3]:50102'
    url: /1.0/operations/90a8d5e3-a05d-4bd3-9f22-2fbd8f21e427/websocket?secret=fe331627fb95d660a4b898b3e8b57f52166fe5bd5810bcd8116d60579f9af05b
  level: dbug
  message: allowing untrusted GET
timestamp: 2018-08-23T06:21:22.112737228+02:00
type: logging

^C
root@server:~#

**Comment by stgraber** [comment]
What's the rsync version on both side of this?

**Comment by pcouderc12** [comment]
rsync  version 3.1.2  protocol version 31
on both side (== uptodate stretch)

**Comment by stgraber** [comment]
So looks like it's rsync being picky about features matching on source and target... the recent addition of xattr transport is now causing issues

**Comment by pcouderc12** [comment]
Wow !
