### ISSUE TITLE
Enhancement Request: replace hard-wired calls to "tar" for "lxc import/export" with user-defined command line templates

### ISSUE THREAD

**Issue by m-ueberall** [lxc/lxd#4966]
# Required information

 * LXC version: 3.0.2
 * LXD version: 3.4

# Issue description

Currently, `lxc import/export` will result in hard-wired calls to `tar` in order to read/write (compressed) archives from/to disk.
Especially in cases where forementioned archives are to be stored externally for backup purposes, the current format is "not necessarily" suitable.

Instead of post- (backup) and pre-processing (restore) the resulting archives in their current (`.tar.xz`) form, it would be much better if the above hard-wired calls to `tar` could be replaced/overridden by user-defined commands in order to be able to, e.g., apply better compression (_zstd_), encryption (_gpg_), split large archives into smaller parts (_tar_), and protect the resulting files against bit-rot (_par2/par3_) directly.

**Comment by stgraber** [comment]
We're planning on adding compression algorithm configuration but don't expect to do much more than that.
For more complex options, it's likely best to just download the backups through the API and store them in whatever way you want.

**Comment by davidfavor** [comment]
For additional consideration.

The simple way to allow great ease/flexibility might be to just all specifying the -I option as a pass through to tar.

So any new compression method can be used, as they become available.

For example...
```
lxc export -I"zstd --threads=0 --no-check -19 --long=31" cname cname.tar.zst
```
