### ISSUE TITLE
lxc launch fails with short hash

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#498]
I thought we fixed that one a while back, but apparently not...

**Comment by jensg-st** [comment]
We did, but the 'dbImageGet' call needs to be executed first. Even before we do 'ensureLocalImage'. Instead of ignoring the response from 'dbImageGet", we should replace the variable uuid with the fingerprint value from the returned struct. Thats should do the trick. Will send a pull request later.

**Comment by jensg-st** [comment]
Sorry, ensureLocalImage has to be before dbImageGet.
