### ISSUE TITLE
Numeric aliases for Ubuntu images

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#4986]
This is a feature request to add number aliases for LXD images available from https://images.linuxcontainers.org:8443

Right now it is only possible to run Ubuntu 18.04 by knowing its codename and architecture. Like this:
```
$ lxc launch images:ubuntu/xenial/amd64
Creating the container
...
```
Using shorter name doesn't work.
```
$ lxc launch images:ubuntu/18.04
Creating the container
Error: not found (not a fingerprint, partial fingerprint (first 12 chars) or valid alias)
```

Here is what image list shows for it:
```
$ lxc image list images: -cL
...
+---------------------------------+
| ubuntu/xenial/amd64             |
| ubuntu/xenial/amd64/default     |
+---------------------------------+
...
```
I am not sure what default alias is for.

**Comment by stgraber** [comment]
Hmm, that's already there, but it looks like your client hasn't been switched over to the simplestreams protocol for that image server:
```
| ubuntu/16.04                    |
| ubuntu/16.04/amd64              |
| ubuntu/16.04/default            |
| ubuntu/16.04/default/amd64      |
| ubuntu/xenial                   |
| ubuntu/xenial/amd64             |
| ubuntu/xenial/default           |
| ubuntu/xenial/default/amd64     |
```

```
lxc remote remove images
lxc remote add images https://images.linuxcontainers.org --protocol=simplestreams
```

Will get you using the simplestreams image server which comes with the extra aliases.

**Comment by techtonik** [comment]
It is standard `lxc` from Ubuntu 18.04
```
$ lxc --version
3.0.1
```
Why it doesn't use new `simplestreams` protocol by default?

**Comment by stgraber** [comment]
It does, the problem is when you have an existing config in .config/lxc

**Comment by techtonik** [comment]
If I execute

    lxc remote add images https://images.linuxcontainers.org

it doesn't select `simplestreams`.
