### ISSUE TITLE
Moving containers from dir (v2.16) -> zfs (v3.4) now faiing after recent updates.

### ISSUE THREAD

**Issue by garymol** [lxc/lxd#4987]
# Required information

 * Distribution:
     Server1:  Centos 7.4.1708
     Server2:  Centos 7.5.1804
 * The output of "lxc info" or if that fails:

Server1:

config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - <redacted>:8443
  architectures:
  - x86_64
  - i686
  certificate: |
...
  certificate_fingerprint: ...
  driver: lxc
  driver_version: 2.0.9
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 3.10.0-693.11.6.el7.x86_64
  server: lxd
  server_pid: 825
  server_version: "2.15"
  storage: dir
  storage_version: "1"

Server2:
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - <redacted>:8443
  architectures:
  - x86_64
  - i686
  certificate: |
...
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.17.13-1.el7.elrepo.x86_64
  server: lxd
  server_pid: 6938
  server_version: "3.4"
  storage: zfs
  storage_version: 0.7.9-1
  server_clustered: false
  server_name: XXX

# Issue description

I am tryingo to move stopped containers from an older release to a recently rebuilt container host.  This was done successfully a few weeks ago for another host that was upgraded, but is now failing with the following error (on the old server):

#> lxc move testansible-csd service2:
error: Failed container creation:
 - https://<redacted>:8443: Error transferring container data: exit status 12

On service2, I see the following in the logs:

ephemeral=false lvl=info msg="Creating container" name=testansible-csd t=2018-08-30T15:30:18-0400
ephemeral=false lvl=info msg="Created container" name=testansible-csd t=2018-08-30T15:30:18-0400
lvl=warn msg="Unable to update backup.yaml at this time" name=testansible-csd t=2018-08-30T15:30:19-0400
lvl=warn msg="Unable to update backup.yaml at this time" name=testansible-csd t=2018-08-30T15:30:20-0400
lvl=eror msg="Rsync receive failed: /var/snap/lxd/common/lxd/containers/testansible-csd/: exit status 12: " t=2018-08-30T15:30:20-0400
err="exit status 12" lvl=eror msg="Error during migration sink" t=2018-08-30T15:30:20-0400
created=2018-08-30T15:30:18-0400 ephemeral=false lvl=info msg="Deleting container" name=testansible-csd t=2018-08-30T15:30:20-0400 used=1969-12-31T19:00:00-0500
created=2018-08-30T15:30:18-0400 ephemeral=false lvl=info msg="Deleted container" name=testansible-csd t=2018-08-30T15:30:20-0400 used=1969-12-31T19:00:00-0500

I can move containers to server2 from another host running the same version of LXD, and I can move containers off server1 to other servers running the older version.

This was working 16 days ago, but has stopped working since.  There have been a few snap refreshes on the new distribution in the meantime.

# Information to attach

#> lxc info testansible-csd --show-log
Name: testansible-csd
Remote: unix://
Architecture: x86_64
Created: 2018/08/31 11:44 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

#> lxc config show testansible-csd --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Centos 7 amd64 (20180702_02:16)
  image.os: Centos
  image.release: "7"
  image.serial: "20180702_02:16"
  security.privileged: "true"
  volatile.apply_template: copy
  volatile.base_image: 22abbefe0c68943f264a7139c7a699a0b2adfbcf46fc661d2e89b1232301a5de
  volatile.eth0.hwaddr: 00:16:3e:8a:60:23
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

server1: /var/log/lxd/lxd.log
lvl=info msg="Connecting to a remote simplestreams server" t=2018-08-31T05:18:45-0400
lvl=info msg="Connecting to a remote simplestreams server" t=2018-08-31T05:18:47-0400
lvl=info msg="Done updating images" t=2018-08-31T05:18:48-0400
lvl=eror msg="Rsync send failed: /var/lib/lxd/containers/testansible-csd/: exit status 12: rsync: connection unexpectedly closed (9 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]\n" t=2018-08-31T07:23:46-0400
lvl=eror msg="Rsync send failed: /var/lib/lxd/containers/testansible-csd/: exit status 12: rsync: connection unexpectedly closed (9 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]\n" t=2018-08-31T07:35:16-0400
created=2018-07-03T06:12:51+0000 ephemeral=false lvl=info msg="Deleting container" name=testansible-csd t=2018-08-31T07:38:16-0400 used=2018-07-03T06:12:53+0000
created=2018-07-03T06:12:51+0000 ephemeral=false lvl=info msg="Deleted container" name=testansible-csd t=2018-08-31T07:38:17-0400 used=2018-07-03T06:12:53+0000
ephemeral=false lvl=info msg="Creating container" name=testansible-csd t=2018-08-31T07:44:13-0400
ephemeral=false lvl=info msg="Created container" name=testansible-csd t=2018-08-31T07:44:13-0400
lvl=warn msg="Unable to update backup.yaml at this time." name=testansible-csd t=2018-08-31T07:44:13-0400

server2:# /var/snap/lxd/common/lxd/logs/lxd.log
ephemeral=false lvl=info msg="Creating container" name=testansible-csd t=2018-08-31T07:35:15-0400
ephemeral=false lvl=info msg="Created container" name=testansible-csd t=2018-08-31T07:35:15-0400
lvl=warn msg="Unable to update backup.yaml at this time" name=testansible-csd t=2018-08-31T07:35:16-0400
lvl=warn msg="Unable to update backup.yaml at this time" name=testansible-csd t=2018-08-31T07:35:16-0400
lvl=eror msg="Rsync receive failed: /var/snap/lxd/common/lxd/containers/testansible-csd/: exit status 12: " t=2018-08-31T07:35:16-0400
err="exit status 12" lvl=eror msg="Error during migration sink" t=2018-08-31T07:35:17-0400
created=2018-08-31T07:35:15-0400 ephemeral=false lvl=info msg="Deleting container" name=testansible-csd t=2018-08-31T07:35:17-0400 used=1969-12-31T19:00:00-0500
created=2018-08-31T07:35:15-0400 ephemeral=false lvl=info msg="Deleted container" name=testansible-csd t=2018-08-31T07:35:17-0400 used=1969-12-31T19:00:00-0500

**Comment by garymol** [comment]
In case it helps, relvant rsync versions on each server:
server1:  3.0.9  protocol version 30
server2:  3.1.2  protocol version 31

**Comment by stgraber** [comment]
Already fixed in master, the issue was rsync not liking the different flags passed between releases.
