### ISSUE TITLE
Failed to mount RBD storage volume for container

### ISSUE THREAD

**Issue by bit** [lxc/lxd#4997]
my cluster is in a strange state: all nodes report failures to mount RBD volumes for containers that run on other nodes:

i.e. test container is running on node01, but node02 wants to mount it if i try to run lxc stop test

Sep 03 10:19:54 node02 lxd[2908]: lvl=eror msg="Failed to mount RBD storage volume for container \"test\": no such file or directory" t=2018-09-03T10:19:54+0200
Sep 03 10:19:54 node02 lxd[2908]: lvl=eror msg="Failed to start container 'test': no such file or directory" t=2018-09-03T10:19:54+0200

$ lxc info test
Name: test
Location: node01
Status: Running
Type: persistent

$ lxc stop test
Error: Put https://node01:8443/1.0/containers/test/state: read tcp node02:49588->node01:8443: read: connection reset by peer

After this nodes go wild and i get lots of transaction within a transaction errors:

Sep 03 10:38:43 node01 lxd[2651]: lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: cannot start a transaction within a transaction" t=2018-09-03T10:38:43+0200
Sep 03 10:38:43 node01 lxd[2651]: 2018/09/03 10:38:43 http: multiple response.WriteHeader calls
Sep 03 10:38:44 node01 lxd[2651]: lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: cannot start a transaction within a transaction" t=2018-09-03T10:38:44+0200
Sep 03 10:38:44 node01 lxd[2651]: lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: cannot start a transaction within a transaction" t=2018-09-03T10:38:44+0200

**Comment by stgraber** [comment]
What LXD version is that?

**Comment by bit** [comment]
LXD: 3.0.1
from the ubuntu 18.04 repo

**Comment by stgraber** [comment]
Is that during daemon startup (just after machine reboot or the like)?
If so, I'm pretty sure I fixed that particular bug a while back with fix in 3.0.2 (yet to make it to 18.04 though).

**Comment by stgraber** [comment]
@bit

**Comment by bit** [comment]
the cluster was no longer able to sync, raft errors on all nodes, those errors came after restarting nodes one by one.

**Comment by stgraber** [comment]
Ok, so yeah, those particular errors I've fixed in 3.0.2. LXD prior to that was naively attempting to restart all containers on node startup rather than filter for those containers local to the node.
