### ISSUE TITLE
lxd.migrate don't migrate containers.

### ISSUE THREAD

**Issue by geodb27** [lxc/lxd#5002]
* Distribution: ubuntu
 * Distribution version: LTS 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux ubuntu-lts64 4.4.0-134-generic
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: DIR

# Issue description

The system is up-to-date, and I want to switch to snap version of lxd. There is a disk mounted as /var/lib/lxd/storage-pools/default (100G) which contains 35 containers. To be sure that the migration to the 3.4 version of lxd will have enough room to store all containers, I've also mounted a 100G disk on /var/snap/
"snap install lxd" goes fine. Then after I go with "lxd.migrate" and I have absolutely no error nor warnings. So, according to this program everything goes fine. However, after it ends, /var/snap/lxd/common/lxd/containers is full of broken links that points to /var/snap/lxd/common/lxd/storage-pools/default and this last one is absolutely empty.

**Comment by stgraber** [comment]
That's normal, `/var/snap/lxd/common/lxd/storage-pools/default` is mounted inside of a mount namespace so isn't visible from the host.

You should be able to inspect what's actually mounted through `/var/snap/lxd/common/mntns/var/snap/lxd/common/lxd/storage-pools/default`.

How does LXD behave post-migrate? Is anything actually broken?

**Comment by geodb27** [comment]
Hi stgraber, and thanks a lot for your concern.
After the migration, lxc list shows nothing at all. No container. 
I should have written down that I answered yes to the last question from lxd.migrate, so I guessed (maybe wrongly) that the old 2.21 lxd daemon was indeed stopped before it's removal. As suggested by all I read about how to migrate, I logged out and went back again, so as to use the 3.4 version of lxc command line tool.
Maybe I should have restarted the machine ?
Anyway, what you said about the mount makes me think of one thing : maybe I did things wrong by mounting a separate disk to /var/snap. There is not enough space on the / device to host all the containers (as I wrote, nearly 100G of datas dedicated to the containers). This could be the problem indeed.
I won't be abble to dig further until next monday, since I won't have the opportunity and time to get a shell on to this peculiar machine.
So, I'll comment further on when I have more informations and go with more tests.

**Comment by stgraber** [comment]
You shouldn't have needed to do that mount in the first place as `lxd.migrate` never copies your containers, instead containers and mounts are just moved to the new location.

Introducing mounts outside of LXD's control may actually have been causing the problems you're seeing now.

**Comment by stgraber** [comment]
@geodb27 any update?

**Comment by geodb27** [comment]
@stgraber Unfortunately, I got sick (acute lumbago) and won't be back to work until next tuesday...

**Comment by stgraber** [comment]
Fair enough, get well!

**Comment by geodb27** [comment]
I'm still stuck at home till next monday included :-(
My back is not getting well and I can't drive to my work yet (70 kms to go)...
I'm very sorry not to be abble to give you the informations required yet to get all up-to-date.
I will try to see if I can manage to connect to one of the lxd servers from home, if I can, and see in the meantime if I can give you more informations about what I did when I installed the 2.21 version and what I want to achieve.
Thank you so much for your concern. I'll give answers here as soon as possible.

**Comment by stgraber** [comment]
@geodb27 Hi, any update?

**Comment by geodb27** [comment]
Hi !
I've managed to get connected to one of the machine I want to update. Here are some elements before launching lxd.migrate : 
lxc --version : 2.21
lxc list --format=csv returns many containers, some of which are running :
lxc list --format=csv
lxc-balmember1,STOPPED,,,PERSISTENT,0
lxc-balmember2,STOPPED,,,PERSISTENT,0
lxc-balmember3,STOPPED,,,PERSISTENT,0
lxc-demo,STOPPED,,,PERSISTENT,0
lxc-front,STOPPED,,,PERSISTENT,0
lxc-pg,STOPPED,,,PERSISTENT,0
lxc-pg1,STOPPED,,,PERSISTENT,0
lxc-pg2,STOPPED,,,PERSISTENT,0
lxc-pg3,STOPPED,,,PERSISTENT,0
lxc-pg961,STOPPED,,,PERSISTENT,0
lxc-pg9611,STOPPED,,,PERSISTENT,0
lxc-pg962,STOPPED,,,PERSISTENT,0
lxc-pg963,STOPPED,,,PERSISTENT,0
lxc-pgpool1,STOPPED,,,PERSISTENT,0
lxc-pgpool2,STOPPED,,,PERSISTENT,0
lxc-pgpool961,STOPPED,,,PERSISTENT,0
lxc-pgpool962,STOPPED,,,PERSISTENT,0
lxc-rsyslog1,STOPPED,,,PERSISTENT,0
lxc-rsyslog2,STOPPED,,,PERSISTENT,0
lxc-testb,STOPPED,,,PERSISTENT,0
lxc-testc,STOPPED,,,PERSISTENT,0
lxc-testu,STOPPED,,,PERSISTENT,0
lxc-www1,RUNNING,192.168.220.111 (eth0),,PERSISTENT,0
lxc-www2,RUNNING,192.168.220.112 (eth0),,PERSISTENT,0
lxc-www3,RUNNING,192.168.220.113 (eth0),,PERSISTENT,0
lxd-david,STOPPED,,,PERSISTENT,0
lxd-david1,STOPPED,,,PERSISTENT,0
lxd-david2,STOPPED,,,PERSISTENT,0
lxd-jail1,STOPPED,,,PERSISTENT,0
lxd-jail2,STOPPED,,,PERSISTENT,0
lxd-webui,STOPPED,,,PERSISTENT,0
scenari,STOPPED,,,PERSISTENT,0
scenari2,STOPPED,,,PERSISTENT,0
scenari3,STOPPED,,,PERSISTENT,0

and there is a vmdk mounted as shown here :
/dev/mapper/vgLxc-vg0_lxd on /var/lib/lxd/storage-pools/default type xfs (rw,relatime,attr2,inode64,noquota)

Here is the background.
Launching lxd.migrate now : 
lxd.migrate
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks

=== Source server
LXD version: 2.21
LXD PID: 1764
Resources:
  Containers: 34
  Images: 4
  Networks: 1
  Storage pools: 1

=== Destination server
LXD version: 3.5
LXD PID: 15550
Resources:
  Containers: 0
  Images: 0
  Networks: 0
  Storage pools: 0

I say yes to the asked question, since I want to proceed to the migration.
Are you ready to proceed (yes/no) [default=no]? yes
=> Shutting down the source LXD
=> Stopping the source LXD units
=> Stopping the destination LXD unit
=> Unmounting source LXD paths
=> Unmounting destination LXD paths
=> Wiping destination LXD clean
=> Backing up the database
=> Moving the data
=> Updating the storage backends
=> Starting the destination LXD
=> Waiting for LXD to come online

=== Destination server
LXD version: 3.5
LXD PID: 19378
Resources:
  Containers: 34
  Images: 4
  Networks: 1
  Storage pools: 1

The migration is now complete and your containers should be back online.
Do you want to uninstall the old LXD (yes/no) [default=yes]
I say yes...
I log out and I log in back. 
lxc --version 3.5
lxc list --format=csv
lxc-balmember1,STOPPED,,,PERSISTENT,
lxc-balmember2,STOPPED,,,PERSISTENT,
lxc-balmember3,STOPPED,,,PERSISTENT,
lxc-demo,STOPPED,,,PERSISTENT,
lxc-front,STOPPED,,,PERSISTENT,
lxc-pg,STOPPED,,,PERSISTENT,
lxc-pg1,STOPPED,,,PERSISTENT,
lxc-pg2,STOPPED,,,PERSISTENT,
lxc-pg3,STOPPED,,,PERSISTENT,
lxc-pg961,STOPPED,,,PERSISTENT,
lxc-pg9611,STOPPED,,,PERSISTENT,
lxc-pg962,STOPPED,,,PERSISTENT,
lxc-pg963,STOPPED,,,PERSISTENT,
lxc-pgpool1,STOPPED,,,PERSISTENT,
lxc-pgpool2,STOPPED,,,PERSISTENT,
lxc-pgpool961,STOPPED,,,PERSISTENT,
lxc-pgpool962,STOPPED,,,PERSISTENT,
lxc-rsyslog1,STOPPED,,,PERSISTENT,
lxc-rsyslog2,STOPPED,,,PERSISTENT,
lxc-testb,STOPPED,,,PERSISTENT,
lxc-testc,STOPPED,,,PERSISTENT,
lxc-testu,STOPPED,,,PERSISTENT,
lxc-www1,STOPPED,,,PERSISTENT,
lxc-www2,STOPPED,,,PERSISTENT,
lxc-www3,STOPPED,,,PERSISTENT,
lxd-david,STOPPED,,,PERSISTENT,
lxd-david1,STOPPED,,,PERSISTENT,
lxd-david2,STOPPED,,,PERSISTENT,
lxd-jail1,STOPPED,,,PERSISTENT,
lxd-jail2,STOPPED,,,PERSISTENT,
lxd-webui,STOPPED,,,PERSISTENT,
scenari,STOPPED,,,PERSISTENT,
scenari2,STOPPED,,,PERSISTENT,
scenari3,STOPPED,,,PERSISTENT,

They are all stopped... Hummmm... Strange.
lxc start lxc-www1
Error: saving config file for the container failed
Try `lxc info --show-log lxc-www1` for more info

So, here we go for the required command : 
lxc info --show-log lxc-www1
Name: lxc-www1
Remote: unix://
Architecture: x86_64
Created: 2017/09/08 07:11 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

Nothing more.
If I go for
ls -l /var/snap/lxd/common/lxd/containers
lrwxrwxrwx 1 root root     72 sept. 26 10:25 lxc-balmember1 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-balmember1
lrwxrwxrwx 1 root root     72 sept. 26 10:25 lxc-balmember2 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-balmember2
lrwxrwxrwx 1 root root     72 sept. 26 10:25 lxc-balmember3 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-balmember3
lrwxrwxrwx 1 root root     66 sept. 26 10:25 lxc-demo -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-demo
lrwxrwxrwx 1 root root     67 sept. 26 10:25 lxc-front -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-front
-rw-r--r-- 1 root root 135881 sept.  8  2017 lxc-monitord.log
lrwxrwxrwx 1 root root     64 sept. 26 10:25 lxc-pg -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pg
lrwxrwxrwx 1 root root     65 sept. 26 10:25 lxc-pg1 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pg1
lrwxrwxrwx 1 root root     65 sept. 26 10:25 lxc-pg2 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pg2
lrwxrwxrwx 1 root root     65 sept. 26 10:25 lxc-pg3 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pg3
lrwxrwxrwx 1 root root     67 sept. 26 10:25 lxc-pg961 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pg961
lrwxrwxrwx 1 root root     68 sept. 26 10:25 lxc-pg9611 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pg9611
lrwxrwxrwx 1 root root     67 sept. 26 10:25 lxc-pg962 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pg962
lrwxrwxrwx 1 root root     67 sept. 26 10:25 lxc-pg963 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pg963
lrwxrwxrwx 1 root root     69 sept. 26 10:25 lxc-pgpool1 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pgpool1
lrwxrwxrwx 1 root root     69 sept. 26 10:25 lxc-pgpool2 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pgpool2
lrwxrwxrwx 1 root root     71 sept. 26 10:25 lxc-pgpool961 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pgpool961
lrwxrwxrwx 1 root root     71 sept. 26 10:25 lxc-pgpool962 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-pgpool962
lrwxrwxrwx 1 root root     70 sept. 26 10:25 lxc-rsyslog1 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-rsyslog1
lrwxrwxrwx 1 root root     70 sept. 26 10:25 lxc-rsyslog2 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-rsyslog2
lrwxrwxrwx 1 root root     67 sept. 26 10:25 lxc-testb -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-testb
lrwxrwxrwx 1 root root     67 sept. 26 10:25 lxc-testc -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-testc
lrwxrwxrwx 1 root root     67 sept. 26 10:25 lxc-testu -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-testu
lrwxrwxrwx 1 root root     66 sept. 26 10:25 lxc-www1 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-www1
lrwxrwxrwx 1 root root     66 sept. 26 10:25 lxc-www2 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-www2
lrwxrwxrwx 1 root root     66 sept. 26 10:25 lxc-www3 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxc-www3
lrwxrwxrwx 1 root root     67 sept. 26 10:25 lxd-david -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxd-david
lrwxrwxrwx 1 root root     68 sept. 26 10:25 lxd-david1 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxd-david1
lrwxrwxrwx 1 root root     68 sept. 26 10:25 lxd-david2 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxd-david2
lrwxrwxrwx 1 root root     67 sept. 26 10:25 lxd-jail1 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxd-jail1
lrwxrwxrwx 1 root root     67 sept. 26 10:25 lxd-jail2 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxd-jail2
lrwxrwxrwx 1 root root     67 sept. 26 10:25 lxd-webui -> /var/snap/lxd/common/lxd/storage-pools/default/containers/lxd-webui
lrwxrwxrwx 1 root root     65 sept. 26 10:25 scenari -> /var/snap/lxd/common/lxd/storage-pools/default/containers/scenari
lrwxrwxrwx 1 root root     66 sept. 26 10:25 scenari2 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/scenari2
lrwxrwxrwx 1 root root     66 sept. 26 10:25 scenari3 -> /var/snap/lxd/common/lxd/storage-pools/default/containers/scenari3
 (all broken links)

ls -l /var/snap/lxd/common/lxd/storage-pools/default/containers/
ls: cannot access '/var/snap/lxd/common/lxd/storage-pools/default/containers/': No such file or directory

That's all I get... Don't know how to get lxd up-to-date.
On a previous answer, you told me that containers should be available in /var/snap/lxd/common/mntns/var/snap/lxd/common/lxd/storage-pools/default
So, I went to : 
ls -l /var/snap/lxd/common/mntns/var/snap/lxd/common/lxd/storage-pools/default
total 0


Here are all the informations I can give so far. 
Hope that I gave enough details.
Thanks a lot for your kind help.

**Comment by stgraber** [comment]
Ok, so the issue here is:
```
/dev/mapper/vgLxc-vg0_lxd on /var/lib/lxd/storage-pools/default type xfs (rw,relatime,attr2,inode64,noquota)
```

Which is extremely unsupported in LXD and is definitely causing problems with the migration :)

I'd recommend trying:
 - mount /dev/mapper/vgLxc-vg0_lxd /var/snap/lxd/common/lxd/storage-pools/default
 - systemctl reload snap.lxd.daemon
 - lxc start lxc-www1

See if that solves the issue. If it does, then you'll want to update your fstab with the right path.

Using a dir backend with a manually mounted device on top of it isn't supported by LXD and so isn't something `lxd.migrate` knows anything to do with, hopefully the above will fix things for you.

**Comment by stgraber** [comment]
@geodb27 let me know how that goes

**Comment by geodb27** [comment]
Hi @stgraber :-)
I'm back to work today after a long period being stuck at home. Yet, it is out of the scope of this lxd issue anyway.
The commands you gave me seems to have fixed the problem on the test machine I worked on, which is great. I'll be able to proceed further and go to update the whole machine now (16.04->18.04).
I have other machines to update the same way, and I will have similar issues (on some, I didn't make a separate disk for /var/lib/lxd/storage-pools/default but for the whole /var/lib/lxd. But I guess I'll be able to handle this.

On your previous posts, you wrote : 

> Using a dir backend with a manually mounted device on top of it isn't supported by LXD

This is something I can understand. But, what would I have done ? We don't have a 2T / partition with the space available to have only one disk and one mount point. What would be the best way to handle separate disks for storage pools, if any ?

Thanks a lot for your concern and your kind help.

**Comment by stgraber** [comment]
`/var/lib/lxd` being on a separate partition should be detected by lxd.migrate, the migration should work fine but a warning will be displayed telling you that you'll need to update /etc/fstab so that things work after reboot.

The way to handle your setup would normally have been:
 - Mount your external disk to some /mnt/XYZ path
 - lxc storage create blah dir source=/mnt/XYZ

Which would then instruct LXD to use your external disk where you mounted out without having you mount it under /var/lib/lxd, this setup would have worked properly with `lxd.migrate` without manual intervention being required.

Closing this issue since it sounds like we got to the bottom of it and you have a way out of this problem :)
