### ISSUE TITLE
copy problem...

### ISSUE THREAD

**Issue by picousse** [lxc/lxd#5003]
# Required information

 * Distribution: ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-33-generic
   * LXC version: 3.4
   * LXD version: 3.4
   * Storage backend in use: default

# Issue description
```
lxc copy test galaxy2:test 
```
from local to server (debian snap)

 errors out:
```
Error: Failed container creation:
 - https://10.142.100.1:8443: Error transferring container data: Unable to connect to: 10.142.100.1:8443
 - https://[fd42:c137:74da:69e::1]:8443: Error transferring container data: Unable to connect to: [fd42:c137:74da:69e::1]:8443
 - https://172.19.40.112:8443: Error transferring container data: Unable to connect to: 172.19.40.112:8443
 - https://172.19.48.103:8443: Error transferring container data: Unable to connect to: 172.19.48.103:8443
 - https://192.168.123.1:8443: Error transferring container data: Unable to connect to: 192.168.123.1:8443
 - https://10.0.3.1:8443: Error transferring container data: Unable to connect to: 10.0.3.1:8443
```

```
lxc exec galaxy2:XXX bash 
```
works so I guess remote is set right.

is this because my ip changes (dhcp?)
The goal was to develop the container on my computer/laptop and then transfer it to the server.

# Steps to reproduce

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Most likely you don't have a direct network path (no NAT) between the target server and the source server.
You can use `--mode=push` to reverse the direction of the connections or use `--mode=relay` which will have your command line client relay data between the two servers.
