### ISSUE TITLE
Accept Error: too many open connections

### ISSUE THREAD

**Issue by sidxz** [lxc/lxd#5006]
# Required information

 * Distribution: Oracle Enterprise Linux 7.5
 * Distribution version: 7.5 Kernel 4.1.12-124.18.5.el7uek.x86_64
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.1.12-124.18.5.el7uek.x86_64
   * LXC version: 3.0
   * LXD version: 3.0
   * Storage backend in use: ZFS

# Issue description

After forming a cluster of 3 nodes, response to all lxc commands became slow and now hangs indefinitely.
Although The containers are running.

I fixed the tcp problem via
sysctl net.ipv4.ip_local_port_range="15000 61000"
sysctl net.ipv4.tcp_fin_timeout=30

But it doesn't solve anything. I couldn't get any hint from  LXD --debug 
:: lxd --debug
DBUG[09-06|16:34:40] Connecting to a local LXD over a Unix socket 
DBUG[09-06|16:34:40] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
INFO[09-06|16:34:40] LXD 3.0.0 is starting in normal mode     path=/var/lib/lxd
WARN[09-06|16:34:40] Error reading default uid/gid map        err="User \"root\" has no subuids."
WARN[09-06|16:34:40] Only privileged containers will be able to run 
WARN[09-06|16:34:40] AppArmor support has been disabled because of lack of kernel support 
WARN[09-06|16:34:40] Couldn't find the CGroup pids controller, process limits will be ignored. 
INFO[09-06|16:34:40] Initializing local database 
INFO[09-06|16:34:40] Initializing database gateway 
INFO[09-06|16:34:40] Start database node                      address=128.194.145.24:8443 id=2
INFO[09-06|16:34:40] Raft: Restored from snapshot 566-592776-1536269107760 
INFO[09-06|16:34:40] Raft: Initial configuration (index=418804): [{Suffrage:Voter ID:1 Address:0} {Suffrage:Voter ID:2 Address:128.194.145.24:8443} {Suffrage:Voter ID:3 Address:128.194.145.23:8443}] 
INFO[09-06|16:34:40] Raft: Node at 128.194.145.24:8443 [Follower] entering Follower state (Leader: "") 
INFO[09-06|16:34:40] LXD isn't socket activated 
DBUG[09-06|16:34:40] Connecting to a local LXD over a Unix socket 
DBUG[09-06|16:34:40] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[09-06|16:34:40] Detected stale unix socket, deleting 
DBUG[09-06|16:34:40] Detected stale unix socket, deleting 
INFO[09-06|16:34:40] Starting /dev/lxd handler: 
INFO[09-06|16:34:40]  - binding devlxd socket                 socket=/var/lib/lxd/devlxd/sock
INFO[09-06|16:34:40] REST API daemon: 
INFO[09-06|16:34:40]  - binding Unix socket                   socket=/var/lib/lxd/unix.socket
INFO[09-06|16:34:40]  - binding TCP socket                    socket=128.194.145.24:8443
INFO[09-06|16:34:40] Initializing global database 
DBUG[09-06|16:34:40] Failed to establish gRPC connection with 128.194.145.27:8443: 503 Service Unavailable 
DBUG[09-06|16:34:40] Found cert                               k=0
DBUG[09-06|16:34:40] Failed to establish gRPC connection with 128.194.145.24:8443: 503 Service Unavailable 
DBUG[09-06|16:34:41] Found cert                               k=0
INFO[09-06|16:34:41] Raft-http: Establishing new connection with 128.194.145.23:8443 
DBUG[09-06|16:34:41] Raft-net: 128.194.145.24:8443 accepted connection from: 128.194.145.23:59996 
WARN[09-06|16:34:41] Raft: Skipping application of old log: 592776 
DBUG[09-06|16:34:41] Found cert                               k=0
INFO[09-06|16:34:41] Raft-http: Establishing new connection with 128.194.145.23:8443 
DBUG[09-06|16:34:41] Raft-net: 128.194.145.24:8443 accepted connection from: 128.194.145.23:59997

**Comment by sidxz** [comment]
Some more logs
Sep 06 16:45:42 lxdhost027-primary-infra-snet1166-ilsb.biobio.tamu.edu lxd[23480]: lvl=warn msg="Raft: Election timeout reached, restarting election" t=2018-09-06T16:45:42-0500
Sep 06 16:45:46 lxdhost027-primary-infra-snet1166-ilsb.biobio.tamu.edu lxd[23480]: lvl=warn msg="Raft: Election timeout reached, restarting election" t=2018-09-06T16:45:46-0500

**Comment by stgraber** [comment]
Please show 'lxc info'

**Comment by sidxz** [comment]
It fails to work

**Comment by stgraber** [comment]
Ok, anyway, looking at the logs above, you're running LXD 3.0.0.
Please upgrade to 3.0.2 and try again, there have been a lot of clustering fixes in both LXD 3.0.1 and 3.0.2 that may very well take care of this issue for you.

You may also want to increase NOFILE for your LXD daemon in whatever init script you're using to start it. In the systemd units we ship in Ubuntu, we bump this to 1048576 which we've found sufficient to handle several thousands of containers.

**Comment by stgraber** [comment]
Did you get to try 3.0.2?
