### ISSUE TITLE
BUG from source

### ISSUE THREAD

**Issue by ne-vlezay80** [lxc/lxd#5008]
# Required information

 * Distribution: Debian
 * Distribution version: 9
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.18.4
   * LXC version: 3.4
   * LXD version: 3.4
   * Storage backend in use:

# Issue description
Bug from source

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

====

go get -t -v -d ./...
CC=cc go install -v -tags "libsqlite3"  ./...
github.com/pborman/uuid
github.com/CanonicalLtd/go-dqlite/internal/bindings
github.com/CanonicalLtd/go-dqlite/internal/trace
github.com/armon/go-metrics
# github.com/pborman/uuid
../../pborman/uuid/time.go:15: syntax error: unexpected = in type declaration
github.com/miekg/dns
# github.com/CanonicalLtd/go-dqlite/internal/trace
../../CanonicalLtd/go-dqlite/internal/trace/set.go:112: undefined: sort.Slice
# github.com/armon/go-metrics
../../armon/go-metrics/inmem_endpoint.go:72: undefined: sort.Slice
../../armon/go-metrics/inmem_endpoint.go:86: undefined: sort.Slice
../../armon/go-metrics/inmem_endpoint.go:113: undefined: sort.Slice
# github.com/miekg/dns
../../miekg/dns/msg_helpers.go:144: base32.HexEncoding.WithPadding undefined (type *base32.Encoding has no field or method WithPadding)
../../miekg/dns/msg_helpers.go:144: undefined: base32.NoPadding
# github.com/CanonicalLtd/go-dqlite/internal/bindings
../../CanonicalLtd/go-dqlite/internal/bindings/testing.go:13: t.Helper undefined (type *testing.T has no field or method Helper)
../../CanonicalLtd/go-dqlite/internal/bindings/server.go:26: constant -8786437285571510299 overflows uint64
Makefile:18: ошибка выполнения рецепта для цели «default»
make: *** [default] Ошибка 2

**Comment by stgraber** [comment]
what version of Go are you using?

**Comment by stgraber** [comment]
Looking at the Go changelog, the errors above suggest you're running Go < 1.10 which isn't supported to build LXD.

Please upgrade your Go compiler to 1.10 or higher and try building LXD again.

**Comment by stgraber** [comment]
(hint was that sort.Slice was introduced in 1.8 so the errors above show a compiler earlier than 1.8)
