### ISSUE TITLE
Migration from package to snap on non-Ubuntu systems

### ISSUE THREAD

**Issue by lenucksi** [lxc/lxd#5011]
# Required information

 * Distribution: Arch Linux, current
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux-LTS, i.e. 4.14.68
   * LXC version: 3.0.2
   * LXD version: 
     * Package: 3.4
     * Snap: 3.4 (8415)
   * Storage backend in use: BTRFS

# Issue description
LXD is installed on Arch Linux (likely similar to "from source") using this AUR package: https://github.com/maikelwever/lxd
Package LXD runs fine, snap LXD installs fine too.
However, attempting to use` lxd.migrate` reveals that the migration only is supported on Ubuntu.

Manual migration by starting both daemon on separate ports with separate storage pools is not too successfull. The snap version disables quite a bit of functionality (network, storage config, running, ...) once it sees the non-snap daemon running and just outputs a "use lxd.migrate" error message.
Actually migrating a container using `lxc move` from the package version to the snap version works - other functionality only works if one of the daemons is stopped.

However it would be nice to have a proper "import" function to import on-disk data structures from other or previous installations. Alternatively a proper description of the process that` lxd.migrate` executes such that it can be executed manually.

**Comment by stgraber** [comment]
Shouldn't be too difficult for someone with ArchLinux knowledge to send a pull request against the lxd-pkg-snap repository to add migration logic. The main things that may differ are the systemd unit name and package management commands.

**Comment by stgraber** [comment]
Move to https://github.com/lxc/lxd-pkg-snap/issues/22
