### ISSUE TITLE
lxd import destroyed a container it was unable to import

### ISSUE THREAD

**Issue by vuori** [lxc/lxd#5017]
# Required information

 * Distribution: Xenial
 * Distribution version: 16.04.1
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-134-generic
   * LXC version: 3.0.1
   * LXD version: 3.0.1
   * Storage backend in use: btrfs

# Issue description

While re-importing containers due to inability to start lxd after upgrading to 3.0 (#5015), I attempted to import the container which caused the original problem (viz. a bad `raw.lxc` configuration).

Running `lxd import` produced the message `Error: Failed to load raw.lxc` (relevant bit of log below). lxd then *deleted the container's subvolume*, which was not particularly nice.

# Steps to reproduce

1. Create a container, remove it from lxd's database and add an invalid `raw.lxc` section to `backup.yaml`.
2. Attempt to `lxd import` the container.
3. Note that the entire container subvolume got deleted.

# Information to attach

```
ephemeral=false lvl=info msg="Creating container" name=torska t=2018-09-09T13:12:16+0200
created=2018-03-03T16:48:15+0100 ephemeral=false lvl=info msg="Deleting container" name=torska t=2018-09-09T13:12:16+0200 used=2018-06-03T12:37:52+0200
created=2018-03-03T16:48:15+0100 ephemeral=false lvl=info msg="Deleted container" name=torska t=2018-09-09T13:12:20+0200 used=2018-06-03T12:37:52+0200
ephemeral=false lvl=eror msg="Failed creating container" name=torska t=2018-09-09T13:12:20+0200
```

**Comment by stgraber** [comment]
Reproduced the issue here, it's kinda tricky because during normal container creation, we actually do want to delete everything, the `lxd import` case is the only one where we actually want to keep disk artifacts around so will need to get creative on detecting that particular case.
