### ISSUE TITLE
lxd debugging should include writing api calls with timestamps as they arrive

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#502]
I would like to see a dump of all of the incoming API calls to LXD to aide debugging.

**Comment by tych0** [comment]
On Mon, Apr 13, 2015 at 12:51:57PM -0700, raharper wrote:
> I would like to see a dump of all of the incoming API calls to LXD to aide debugging.

It should print stuff like:

2015/04/13 14:18:23 handling GET /1.0
2015/04/13 14:18:23 handling GET /1.0/containers
2015/04/13 14:18:23 handling GET /1.0/containers/foo
2015/04/13 14:18:23 handling GET /1.0/containers/mig
2015/04/13 14:18:24 handling GET /1.0/containers/nonlive

What else would you like to see? I guess we could print the content of
the body on non-get requests, but we wouldn't necessarily want to do
that all the time (e.g. POST an image or whatever). Would that be
enough?

**Comment by raharper** [comment]
I think that's close enough;  though the data passed (within reason) would be useful too.  I'm mostly looking for a way to capture a sequence of API calls in a period of time so I can have context for when something fails (container doesn't start and throws an error).

**Comment by tych0** [comment]
On Mon, Apr 13, 2015 at 01:44:41PM -0700, raharper wrote:
> I think that's close enough;  though the data passed (within reason) would be useful too.  I'm mostly looking for a way to capture a sequence of API calls in a period of time so I can have context for when something fails (container doesn't start and throws an error).

Ok, I'm working on a patch to emit the json stuff for now at least,
since that's the bulk of the requests. We can generalize it from there
if necessary.
