### ISSUE TITLE
Why is LXD 3.4 not available in Ubuntu Repo?

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#5022]
# Required information

 * Distribution: **Ubuntu** 
 * Distribution version: **18.04**
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: **3.0.1**
   * LXD version: **3.0.1**
   * Storage backend in use:

We have noticed that the LXD version of Ubuntu 18.04.1 is still at 3.0.1, but the LXD version in snapd is 3.4? 

Is there any reason why the Ubuntu 18.04 release doe snot get updated? Since its already a major jump from 3.0.1 to 3.4. 

Do you have a time-frame for the Ubuntu 18.01 update?

**Comment by stgraber** [comment]
Ubuntu stable releases never get newer feature releases of software, they just get bugfix releases.
So for Ubuntu 18.04, you currently have LXD 3.0.1 and will soon be getting LXD 3.0.2.

Newer LXD features releases (like 3.4) are only available as snap packages which can be installed on any Ubuntu releases (as well as many non-Ubuntu distributions).

**Comment by elbrinke** [comment]
hi @stgraber , 

Thanks for your response. What would you say is a better way of running LXD on Ubuntu? Through **snap** or through Ubuntu **repo**?
