### ISSUE TITLE
Container live migration and/or failover available in LXD 3.4?

### ISSUE THREAD

**Issue by ncpe20012003** [lxc/lxd#5027]
Running LXD 3.4 via snap on Ubuntu 16.04. Are there still issues with CRIU?

**Comment by stgraber** [comment]
There are no issues that we're aware of in the LXD integration code, CRIU however will fail to checkpoint/restore most workloads, only very limited, well understood workloads can be made to work.

You may want to check the list of open issues at https://github.com/checkpoint-restore/criu

**Comment by ncpe20012003** [comment]
So does that mean that live migration and/or failover capabilities are not available in 3.4?

**Comment by stgraber** [comment]
That's not at all what I said. LXD does support live migration of containers, so long as the container you're trying to migrate can be serialized by CRIU. Whether that's the case is entirely dependent on what's running in the container, kernel version, ...

**Comment by ncpe20012003** [comment]
When I attempt to take a stateful snapshot of a container, I get "Error: Unable to create a stateful snapshot. CRIU isn't installed". CRIU is installed on all three of my LXD hosts and the container. Is this because LXD is loaded via snap?

**Comment by stgraber** [comment]
For the snap, you need to do:
 - snap set lxd criu.enable=true
 - systemctl reload snap.lxd.daemon

To enable CRIU.

**Comment by ncpe20012003** [comment]
Was able to enable criu in snap, tired to snap container first which is a ubuntu:16.04 image

root@lxd1-a:/home/choyle# lxc list
+--------+---------+---------------------+------+------------+-----------+-------------+
|  NAME  |  STATE  |        IPV4         | IPV6 |    TYPE    | SNAPSHOTS |  LOCATION   |
+--------+---------+---------------------+------+------------+-----------+-------------+
| first  | RUNNING | 240.20.0.42 (eth0)  |      | PERSISTENT |           | lxd1-a.test |
+--------+---------+---------------------+------+------------+-----------+-------------+
| second | RUNNING | 240.21.0.230 (eth0) |      | PERSISTENT |           | lxd2-a.test |
+--------+---------+---------------------+------+------------+-----------+-------------+
| third  | RUNNING | 240.22.0.138 (eth0) |      | PERSISTENT |           | lxd3-a.test |
+--------+---------+---------------------+------+------------+-----------+-------------+
root@lxd1-a:/home/choyle# lxc snapshot first snap0 --stateful
Error: snapshot dump failed
(00.028376) Warn  (criu/image.c:127): Failed to open parent directory(00.028379) ========================================
(00.741805) Error (compel/src/lib/infect.c:636): Unable to connect a transport socket: Permission denied
(00.741814) Error (compel/src/lib/infect.c:559): Can't inject syscall blob (pid: 2920)
(00.741817) Error (compel/src/lib/infect.c:1316): munmap for remote map 0x7fec2ff2d000, 106496 returned 11
(00.741820) Error (criu/cr-dump.c:1275): Can't infect (pid: 2920) with parasite
(00.755415) Error (compel/src/lib/infect.c:341): Unable to detach from 2920: No such process
(00.755604) Error (criu/cr-dump.c:1720): Dumping FAILED.
root@lxd1-a:/home/choyle# 

Looks like a permissions issue.

**Comment by stgraber** [comment]
Probably some socket that CRIU can't serialize, I've never had much success with distros using systemd.
Try images:alpine/edge, that one usually works.

**Comment by ncpe20012003** [comment]
Taking a stateful snapshot does work for the image you mentioned above and for images:debian/stretch, which is good. I created a LXC call fifth from debian/stretch and attempted to do a live move between LXC cluster members:

root@lxd1-a:/home/choyle# lxc move fifth --target lxd3-a.test
Error: Migration API failure: Container is running

Is there a different syntax to make this work?

**Comment by stgraber** [comment]
Live migration between nodes of the same cluster isn't currently supported, partly because the container actually gets temporarily renamed as part of that process which intereferes with the CRIU code.

At this time only live migration between two independent LXD deployments will work (two unclustered nodes or two clusters).
