### ISSUE TITLE
Enhance LXD version details

### ISSUE THREAD

**Issue by quater** [lxc/lxd#5029]
### Status Quo

When LXD (stable) is installed. Only the major and minor version is displayed.
```
$ sudo snap refresh lxd --channel=stable
lxd 3.4 from Canonical✓ refreshed

$ lxd version
3.4
```
During the LXD (edge) installation, the major and minor version is displayed, along with the Git commit Id where the current Git HEAD is.

This I find very useful as it makes it very easy to figure out which patches LXD is running on. Unfortunately, even with LXD (edge), the Git commit Id is omitted  when doing `lxd version`.
```
$ sudo snap refresh lxd --channel=edge
lxd (edge) git-a732506 from Canonical✓ refreshed

$ lxd version
3.5
```
### Desired Enhancement

Show the Git commit Id when doing `lxd version`, regardless of the installation channel. This type of information is particularly useful since the LXD snap automatically updates with the latest patches but the users don't have much visibility unless they consult the LXD Jenkins server .
```
# Suggestion
$ lxd version
3.5 (stable) git-a732506
```

**Comment by stgraber** [comment]
LXD doesn't know what git hash it was built from only the packaging does. You can always look at that version using 'snap list'.
