### ISSUE TITLE
Error: Proxy device doesn't support the connection type: udp

### ISSUE THREAD

**Issue by kaN5300** [lxc/lxd#5030]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.01
 * The output of "lxc info" or if that fails:
config:
  core.https_address: 127.0.0.1:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 127.0.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFTDCCAzSgAwIBAgIQBt85E0uesz6gftHuu+ZD0TANBgkqhkiG9w0BAQsFADA2
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRYwFAYDVQQDDA1yb290QGxp
    dmUtdXNiMB4XDTE4MDkxMTEzNTQzMFoXDTI4MDkwODEzNTQzMFowNjEcMBoGA1UE
    ChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEBsaXZlLXVzYjCC
    AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAN/wSWEsYw7NHxmZpDjCZIds
    Xka5Rb6vzBpVxLPkmBkDWgVP5e8vTL86AC54wlk93+EtVaNeaJPNw+kl7uO1T88I
    y8mTA7YzpuxsKXeyhQkEAuniwKEitdhg5c7Z/i7iB4FSb2/Zv5CbZZHVeLAZMDPG
    X2e/yvIHuFC2lhgGRYSruNzlgrvIiZZoZr5aND70CSU+AgWXDSSh7M0VuDAxo4zn
    d5o01XdBIPOB+vdedEZTgb8kQhks7XwUwXKdRJh9G4W6ozsp6Aywrmqgm1twP4i3
    NQBTQDX0Is74FHj9ZGfiNqvFyrRg3GmI83sQjpTzDo0A44dJyPo+MkUg4nM5FeUV
    me1IJcAVCrACibUWPvr43jwLCeeCeUxOBX/t2ggN9LdttROz99XPa/RD9ZhOKzNR
    ng0KeFZpkEjszWTfNR8HMTQzsXMTqyv5OnKTPtUCOyExjcxiS7G+Wa2uftKu/slg
    x+e+gSRozggc5vptVymB+nVpMT3uoHIUy6ZKJqWmUIdGsCvRR8NuTUDgQlscVHdS
    j3RMJZ8FnkQsQhFYZhbcd/gAOiMIS6x+Wjd5d2DXTLJWPoIz6jkkoRx1dR9rC/mn
    8rUOGLWntuHhL2nzNUPD3d5wjkPa7iDZW60ciP4qU+1MgWOmAK/JqOGYt/CHIMHj
    YK1xsCRw8i8gYwlZQ1ydAgMBAAGjVjBUMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUE
    DDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB8GA1UdEQQYMBaCCGxpdmUtdXNi
    hwTAqP6DhwQKCAAJMA0GCSqGSIb3DQEBCwUAA4ICAQCwOXIJOzBPQ7FkrWFaIBvo
    cnsejiDsz35ANZlNTrEBbUiI4aqPJxTvz55Aoq/ogERD+NlYQm3jAvM6hPp/srd9
    4K91cstvSuX10KnWAdnrAuq0Ug8rIvjMlzW+qVwHn4sIEdNsyNwUKcY1OYsVM8q4
    7z0pI6dS0mEoG0k4f14bbgVbdOWiqeygzPwjPHhoEzskkSuGy5i+OcsvlS3OeZXn
    vnYwkSG2mH/W7A+T1CQJRgi20f3HQ10WWR1FgAZF3BmhZevJV0192O4iQuvATJDr
    u7ftfcNAJsqG/oMdOqwnJUuqiCPfIS+jIytAyhNNdqSR7A9hjatdj2+nH8iCzmzJ
    7FGxBTfzYR3Z87PqCg9Mm2mEYOn2AZonElFSaWYAtpMACouN9KCJZ/cxti8mTek+
    hY+JKrsaanwCo83aYwQhZz89QTwjeQFKSz0osFDdA/ksoq4IGu+ZV9ufIYBXkiZs
    gBb4Fby9vg2H66dpdf//+iSwuNK+swyoqIOFO4cdBGY4xzyQW1OmhQHBxH+yDRbq
    u2JggvDfCcTz88QIsin3YkKQ22PkqmizeUh+YOrysAnQXQMHhR24deOqBXbtK7v6
    HTA1l4mt52epfvkcsEjpFiGBjR6jqPVgGHMoUwy1g/xGLUgngVMOXGY/FQJ0Jf8k
    FOVU++73667Sqx8HTx5KDA==
    -----END CERTIFICATE-----
  certificate_fingerprint: 10a6d23492ea6d1fe3047d21615ba9e16cac6f9d8abfcb21d6ba3fb8c22fb28c
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-33-generic
  server: lxd
  server_pid: 1841
  server_version: 3.0.1
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: live-usb
   * Storage backend in use: 

# Issue description

For some reason it is only possible to add proxy device with type tcp and there is an error for type udp:

kan5300@live-usb ~> sudo lxc config device add integral-woodcock radius_tcp_1812 proxy listen=tcp:192.168.254.131:1812 connect=tcp:10.12.172.127:1812 bind=host
Device radius_tcp_1812 added to integral-woodcock
kan5300@live-usb ~> sudo lxc config device add integral-woodcock radius_udp_1812 proxy listen=udp:192.168.254.131:1812 connect=udp:10.12.172.127:1812 bind=host
Error: Proxy device doesn't support the connection type: udp

**Comment by stgraber** [comment]
You're on LXD 3.0.1 which only had tcp to tcp proxying. The other socket types were added in later feature releases.

**Comment by adamryczkowski** [comment]
I have the same error on Ubuntu 18.04 using `ppa:ubuntu-lxc/daily`. In particular, `lxc info` displays the following versions:
```
  driver: lxc
  driver_version: 3.1.0 (devel)
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-42-generic
  server: lxd
  server_pid: 746
  server_version: 3.0.2
  storage: btrfs
  storage_version: 4.15.1
  server_clustered: false
```

The host is hosted by Linode.

How to download a recent enough version of the LXD, that it supports forwarding udp?

**Comment by stgraber** [comment]
@adamryczkowski for a more recent version of LXD, the way to go is to use the LXD snap.
That will get you all the way up to LXD 3.8.

**Comment by adamryczkowski** [comment]
Thank you. Indeed, I got lxc 3.8, but I cannot run it, because it complains it cannot talk with the LXD service. Does install through snap gets also the LXD service, or should I install it separately? If not, how to install it? This is how I tried to install it.
```
$ sudo snap install lxd
# installation process...
$ lxc info
Connection refused; is LXD running?
$ service lxd status
● lxd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
$ sudo service lxd start
Failed to start lxd.service: Unit lxd.service not found.
```

If you prefer, I can make another thread/issue for it.

**Comment by stgraber** [comment]
Kinda sounds like you have the old `lxd-client` package installed on your system.

**Comment by stgraber** [comment]
The transition from deb to snap should normally be done with just:
 - snap install lxd
 - lxd.migrate

That will install the snap version, move all your data and then remove the deb for you.

Your output above suggests that the deb has already been removed, which, if you had any containers on the system, would be very unfortunate as depending on how the package was removed, they may be hard to recover at this point.

**Comment by adamryczkowski** [comment]
Everything works. Thank you very much!
