### ISSUE TITLE
Import Profiles

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#5037]
I read some where a a while back that because of issues with regards to licenses it perhaps wouldn't work to distribute images with software! 

But using cloud-config within profiles has been an awesome tool to help automate the deployment of services (IMO) so instead of deploying pre-made images could it not be added to import profiles from remote ? 

Instead of having a remote LXD node to sync to, it could work over http to allow for easier deployment / integration with existing services (github, gitlab or any http server) as an lxd profile appears to be just a flat file? 

The profile could be extended to include the base image (ubuntu, alpine, centos etc) the cloud-config (profile including a cloud-config) is intended to be run on. 

There would be problems such as varying network configurations and attached devices, but they should be up for the user to decide!

**Comment by stgraber** [comment]
`lxc profile copy` lets you copy profiles between remotes

**Comment by stgraber** [comment]
Alternatively you can always provide a .yaml file and do:
 - lxc profile create SOME-NAME
 - lxc profile edit SOME-NAME < your-profile.yaml
