### ISSUE TITLE
Issue  to export the paths in  ~/.bashrc file environment

### ISSUE THREAD

**Issue by adityacloud1** [lxc/lxd#5038]
I followed instructions to  build/install LXD from source. When running make deps, I was instructed to export the following paths:
`Please set the following in your environment (possibly ~/.bashrc)
export CGO_CFLAGS="-I/home/server1/go/deps/sqlite/ -I/home/server1/go/deps/dqlite/include/"
export CGO_LDFLAGS="-L/home/server1/go/deps/sqlite/.libs/ -L/home/server1/go/deps/dqlite/.libs/"
export LD_LIBRARY_PATH="/home/server1/go/deps/sqlite/.libs/:/home/server1/go/deps/dqlite/.libs/"
` 
I set the paths in ./bashrc file using
echo export CGO_CFLAGS="-I/home/server1/go/deps/sqlite/ -I/home/server1/go/deps/dqlite/include/">> ~/.bashrc `
and save file by running _**source ~/.profile.**_

But, still the same error is encountered when running **make deps** command

**Comment by stgraber** [comment]
Did you try just starting a new shell by running 'bash'?

**Comment by stgraber** [comment]
You can always run 'env' to see whether your configuration worked.

**Comment by adityacloud1** [comment]
Respected sir,
thanks for yours kind suggestion.
output for env'  is
![s1](https://user-images.githubusercontent.com/40225508/45598681-9572e700-b9fd-11e8-8f3c-8acb5963f33d.png)

**Comment by adityacloud1** [comment]
Paths are highlighted

**Comment by adityacloud1** [comment]
Screenshot for the error is:
![error](https://user-images.githubusercontent.com/40225508/45598988-bdfce000-ba01-11e8-956e-91b017c70174.png)

**Comment by stgraber** [comment]
I'm not seeing an error on this last one

**Comment by stgraber** [comment]
`make deps` always shows you the suggested environment at the end, if `make` then works properly, you've got it all set as needed.

**Comment by stgraber** [comment]
That kind of error happen when you have an unsupported mix of package versions.

Make sure that your LXC library (liblxc and lxc-dev) is at least 3.0.0, you'll then need to wipe any build cache you have for the go-lxc package and then rebuild LXD with that, that should get you a go-lxc which is aware of liblxc 3.0 and lxd doing the same.

I'm closing this issue as this is really a support request rather than an actual bug.

**Comment by adityacloud** [comment]
Thanks sir
