### ISSUE TITLE
lxc delete -f does not free dhcp lease

### ISSUE THREAD

**Issue by eraserix** [lxc/lxd#5053]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.1
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-34-generic
   * LXC version: 3.0.1
   * LXD version: 3.0.1
   * Storage backend in use: btrfs

# Issue description

"lxc delete -f <container>" does not remove the dhcp lease from the dnsmasq leases file. "lxc stop" will properly remove the entry (or rather the guest will on shutdown, as discussed elsewhere).

The faulty behaviour is shown below:
```
$ lxc launch images:debian/8 test
Creating test
Starting test
$ lxc network list-leases lxdbr0
+----------+-------------------+------------+---------+
| HOSTNAME |    MAC ADDRESS    | IP ADDRESS |  TYPE   |
+----------+-------------------+------------+---------+
| test     | 00:16:3e:f6:8f:d0 | 10.0.4.9   | DYNAMIC |
+----------+-------------------+------------+---------+

$ lxc delete -f test
$ lxc network list-leases lxdbr0
+----------+-------------------+------------+---------+
| HOSTNAME |    MAC ADDRESS    | IP ADDRESS |  TYPE   |
+----------+-------------------+------------+---------+
| test     | 00:16:3e:f6:8f:d0 | 10.0.4.9   | DYNAMIC |
+----------+-------------------+------------+---------+
```

As far as I understand this should have been fixed a while back with #2781. Also: 
- How does lxd make sure that concurrent deletes won't overwrite each others changes to the dnsmasq leases file?
- Why does lxd send a SIGKILL to dnsmasq and not just a SIGTERM to allow a proper shutdown? There is no guaranty that no events will arrive between SIGHUP and SIGKILL as far as I can tell.

**Comment by stgraber** [comment]
```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc launch images:debian/8 test
Creating test
Starting test                               
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc network list-leases lxdbr0
+-----------+-------------------+---------------+---------+
| HOSTNAME  |    MAC ADDRESS    |  IP ADDRESS   |  TYPE   |
+-----------+-------------------+---------------+---------+
| snapcraft | 00:16:3e:77:c7:f8 | 10.166.11.213 | DYNAMIC |
+-----------+-------------------+---------------+---------+
| test      | 00:16:3e:99:19:d9 | 10.166.11.10  | DYNAMIC |
+-----------+-------------------+---------------+---------+
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc delete -f test
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc network list-leases lxdbr0
+-----------+-------------------+---------------+---------+
| HOSTNAME  |    MAC ADDRESS    |  IP ADDRESS   |  TYPE   |
+-----------+-------------------+---------------+---------+
| snapcraft | 00:16:3e:77:c7:f8 | 10.166.11.213 | DYNAMIC |
+-----------+-------------------+---------------+---------+
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ 
```

**Comment by stgraber** [comment]
The lease cleanup logic got improved a little while ago and another lease-related bug (when snapshots are in the mix) got fixed a bit later. Those fixes are both in 3.0.2.

As for SIGTERM vs SIGKILL when we need dnsmasq to go away, when in a situation where clients are designed to retry (as is the case with DNS and DHCP) and where there are no persistent data that we care about, we far prefer the speed and atomicity of SIGKILL over deal with SIGTERM + timeout + SIGKILL as this makes things slower and introduces potential races.

Closing since the underlying issue was fixed already (as seen above).

**Comment by eraserix** [comment]
Oh, nice, thanks! I cannot reproduce this on 3.5 snap either. Any idea when 3.0.2 will land in bionic as Debian package?

**Comment by stgraber** [comment]
No idea, I uploaded the package to the bionic-proposed queue over a week ago but nobody has reviewed it yet... once the review happens, it'll take a week for it to go from -proposed to -updates
