### ISSUE TITLE
Suddenly unable to start containers under Ubuntu 18.04

### ISSUE THREAD

**Issue by jlmcgraw** [lxc/lxd#5060]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 18.04
 * The output of "lxc info":  [lxc_info.txt](https://github.com/lxc/lxd/files/2408767/lxc_info.txt)

# Issue description
Suddenly I cannot start containers that had been working.  I am not sure what may have triggered this (host machine reboot, snap update etc)

Here is the error that I'm seeing:

```
jlmcgraw@Latitude-E6500:~$ lxc start firefox

Error: Failed to run: /snap/lxd/current/bin/lxd forkstart firefox /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/firefox/lxc.conf: 
Try `lxc info --show-log firefox` for more info

jlmcgraw@Latitude-E6500:~$ lxc info --show-log firefox

Name: firefox
Remote: unix://
Architecture: x86_64
Created: 2018/06/30 15:41 UTC
Status: Stopped
Type: persistent
Profiles: default, gui

Log:

lxc firefox 20180923134452.612 ERROR    cgfsng - cgroups/cgfsng.c:__do_cgroup_enter:1395 - No space left on device - Failed to enter cgroup "/sys/fs/cgroup/cpuset//lxc.monitor/firefox/cgroup.procs"
lxc firefox 20180923134452.612 ERROR    start - start.c:__lxc_start:1975 - Failed to enter monitor cgroup
lxc firefox 20180923134452.613 WARN     conf - conf.c:lxc_map_ids:2983 - newuidmap binary is missing
lxc firefox 20180923134452.613 WARN     conf - conf.c:lxc_map_ids:2989 - newgidmap binary is missing
lxc firefox 20180923134452.613 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:865 - Received container state "STOPPING" instead of "RUNNING"
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [X ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
[lxd_main_daemon_log.txt](https://github.com/lxc/lxd/files/2408766/lxd_main_daemon_log.txt)

 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by brauner** [comment]
Please as requested show the container's config.

**Comment by brauner** [comment]
Ok, I think I know what's happening.

**Comment by jlmcgraw** [comment]
Thanks for the quick response!

1) Do you still need the container config info?
2) How can I go about testing your changes to see if it resolves this issue?
