### ISSUE TITLE
LXD Container Memory Limitations

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#5070]
# Required information

 * Distribution: **Ubuntu** 
 * Distribution version: **18.04.1 LTS**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.15.0-33-generic**
   * LXC version: **3.0.1**
   * LXD version: **3.0.1**
   * Storage backend in use: **ZFS**

# Issue description

When we are running an LXD container, it for some reason only grabs about 4-5GB of RAM. It does not grab more then that. Even if we run a benchmark for RAM inside the :XD container using sysbench, it shows the results shown below:

```
sysbench 1.0.15 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Running memory speed test with the following options:
  block size: 1KiB
  total size: 102400MiB
  operation: write
  scope: global

Initializing worker threads...

Threads started!

Total operations: 47041590 (4702815.57 per second)

45939.05 MiB transferred (4592.59 MiB/sec)


General statistics:
    total time:                          10.0001s
    total number of events:              47041590

Latency (ms):
         min:                                    0.00
         avg:                                    0.00
         max:                                    0.14
         95th percentile:                        0.00
         sum:                                 4568.15

Threads fairness:
    events (avg/stddev):           47041590.0000/0.00
    execution time (avg/stddev):   4.5682/0.00

```
We are trying to run a very  resource intensive MySQL job and its not allowing enough memory to the container. 

**Are we doing anything wrong here?**

**Comment by cyberwillis** [comment]
Hi @elbrinke , I use lxc / lxd for almost a year and I never saw what you described. I use it day by day I run data science algorithms on it that almost my entire ram if I not limit it. Have you tried to update it Actually I am using ubuntu 16.04 yet.

**Comment by elbrinke** [comment]
@cyberwillis , 

After some deeper troubleshooting and further testing, it seems to be **MySQL** related so far. Will be doing some further testing to make 100% sure.   

I still don't get **3.0.2** on the Ubuntu Repo and am only using **3.0.1**. 

I am running Ubuntu 18.04 LTS on Host.

**Comment by stgraber** [comment]
Going to close this until we have a clearer picture of what's happening with MySQL.

The forum may be a better location for such discussion (https://discuss.linuxcontainers.org), if an actual LXD bug is found as part of this, we'll be sure to open an issue here.

**Comment by cyberwillis** [comment]
Hi @elbrinke , 

Take a look on this.: 
There is a formula to know how much memory the MySQL uses memory 
https://stackoverflow.com/questions/12104185/how-to-set-memory-limit-in-my-cnf-file
