### ISSUE TITLE
Fails to launch first container

### ISSUE THREAD

**Issue by pcouderc12** [lxc/lxd#5074]
# Required information

 * Distribution: debian  
 * Distribution version: buster   with lxd ubuntu debs.
 * The output of "lxc info"

root@server:~# lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  certificate_fingerprint: 3a96400497c02dd802da749ed84c813d84bfb5b5a0632069cc4dfdf9fa6820b6
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.18.0-1-amd64
  server: lxd
  server_pid: 7109
  server_version: 3.0.1
  storage: btrfs
  storage_version: "4.17"
  server_clustered: false
  server_name: server

# Issue description

Fails to launch first container with :

lxc launch  ubuntu:16.04 first
Creating first
Starting first
Error: Failed to run: /usr/lib/lxd/lxd forkstart first /var/lib/lxd/containers /var/log/lxd/first/lxc.conf:
Try `lxc info --show-log local:first` for more info

# Steps to reproduce

 1. Step one
Install fresh debian buster 
apt install rsync...
` dpkg -i liblxc1_3.0.1-0ubuntu1~18.04.2_amd64.deb  liblxc-common_3.0.1-0ubuntu1~18.04.2_amd64.deb`
`dpkg -i lxd_3.0.1-0ubuntu1~18.04.1_amd64.deb  lxd-client_3.0.1-0ubuntu1~18.04.1_amd64.deb`
 2. Step two
`lxd init` with default answers except no network followe by :
`lxc network attach-profile br0 default eth0`
 3. Step three
`lxc launch  ubuntu:16.04 first`

# Information to attach

[lxd.log](https://github.com/lxc/lxd/files/2418719/lxd.log)
[lxc.log](https://github.com/lxc/lxd/files/2418721/lxc.log)

[lxc.conf.txt](https://github.com/lxc/lxd/files/2418735/lxc.conf.txt)

**Comment by simos** [comment]
As far as I know, the Ubuntu deb packages are not officially supported on Debian.
There is an ongoing effort to create a deb package for LXD on Debian,
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=768073
See the current status and follow the discussion there. 

There is already [a snap package for LXD, and it works on Debian](https://snapcraft.io/lxd).
The stats show that the snap package is actively used in Debian 8 and 9.
You can give it a try for Debian 10. 
To install, run `sudo snap install lxd`

For community support questions, please see [the LXC/LXD discussion forum](https://discuss.linuxcontainers.org/).

**Comment by stgraber** [comment]
You're running a 4.18 kernel with liblxc 3.0.1, this won't work due to a change in mknod logic in that kernel.
Either downgrade to pre-4.18 or upgrade liblxc to 3.0.2.

**Comment by pcouderc12** [comment]
Thank you. OK now.
I only needed to install libuv1
