### ISSUE TITLE
lxdbr0 not created on cosmic kvms using deb-installed lxd as a snap

### ISSUE THREAD

**Issue by blackboxsw** [lxc/lxd#5081]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.18.0-7-generic
   * LXC version: 3.5
   * LXD version: 3.5
   * Storage backend in use: dir

multipass@kvm-c3:~$ lxc info
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:18.04

config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFQTCCAymgAwIBAgIRAOTbHJ5IDSUdm6JAOMkjdw0wDQYJKoZIhvcNAQELBQAw
    NDEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEUMBIGA1UEAwwLcm9vdEBr
    dm0tYzMwHhcNMTgwOTI3MjI0OTEyWhcNMjgwOTI0MjI0OTEyWjA0MRwwGgYDVQQK
    ExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QGt2bS1jMzCCAiIw
    DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMQ2p+5ZVBhgaPV0yk6Dfif2tVyr
    bH0toL+LwIUrHO8MyLozOr2BHdC9ssyb0wdkEGMuclU/x1iZIuq/dJRc1kTLAp5B
    Eg/1OZk4rEOzQQ6KarOHOkC5ZbvKM/YsO6X7WPoOtuZH3/HvqO1h1kk8HUsz1cH+
    nXeACYHdHikdJ2vz01pdtaTjNsD0vy/7+jk4zncJ7fuGpC9NJme6LQ95ArjcU4uY
    mAhlHdUbIARFZX+1fghTRwwrlVddPkYUWKffrxzGb0Keehd7svWC7U4bNAQ4iKtQ
    H6/H7Z9YJiPtQjhmuCmpkaZctO5KGwidEepcG5XpwDg+/IvR3cZ/IPxxfM2lD459
    gqrKwHsRpTIlgdei2eRMuBykL2NIK2psmjKfsa9lAfKeAziag/eB54V43ZdBHTCd
    fhK6teTtJPeXgPf7hu6f8ByHO3rr+m6MmOXEUyyNHmZq6Fy3k5TOviT201xUJoYn
    5L5zcTEy11E1d5v0Bjf3b2bpg7N0gXloQNXpgOAIcOcmRfjyxPb1eJmxn43E+qxh
    pzYaPUSUPtTsfwvG0uugwYK/yaDVMph3tXSu63YtNy6QL7pskPEiCt8mg+cGYdvZ
    dGJCYAq15r24ec1mu/lcfyIKN8VNaoknNAIQiN2kJl7O8MZoZGXrEzqiUVqTsHij
    TbQAmVqucFfjVp23AgMBAAGjTjBMMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK
    BggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMBcGA1UdEQQQMA6CBmt2bS1jM4cECkBZ
    eDANBgkqhkiG9w0BAQsFAAOCAgEAZJbSok7+cq6nuAo6FaI3oV4gQl3OdJjpAnat
    X16HCx9n3RI1GRN0aEM2+lCMoh/7KRijvSMI/otvtg8Q5XlajDzNS6gC72HyGXCI
    xBcM6VLiFD9s7igh0K/KZrH4amHHTpbUFAXnY094JCzSY5CAxeynf2SFOFlJ1qIz
    b04dGHBYod3mje21oyybDZxaZtrFjF8/6DETXOyaS/2wA57GwiF25EWKLurfBOSD
    cbF3bTlED1iv1jx4DOFTDN/ijIP1JV+nsRLl8Z5XsC05AGD3bvUwDWOq193tyb8r
    zWIAuFdOHwqFdcTkRCi3sfgh0wiOYlbMjRwZaJ1zcPfuZwJrCR7+3U7+AAs6SLDY
    EpNgBAiCxopGbX5mhwZsja5B0qrNfpfMSCzTpGLbJmnQcfpleDiPrNMnQvXqA2oq
    fD62aOucGzOqeX3ScfZcTPESTpjEJSmZg2xBJVR99ZiBEeQRh0ZLjByrUtaKQm3j
    BO99wNmjBuFEsxsp3AjumNrH4/aysMTyg2pzU2Fiz4QQm1+C67/WYSBWVyizYEmi
    rH/+048kGp49cu0pdat9MPBBZpHt8v/Pnqais18x9jg72nMaghf4pAgwlZka7Geo
    rYUd23fZ5S4wS86FtfkOJyTgbeq9IrHtMQaH3g7D67+Ou4YNdminE3acJNa+SVUA
    9LwjFSc=
    -----END CERTIFICATE-----
  certificate_fingerprint: 395c9f0e263bb98c5c472bb197e3e0afdcaf88dd9f805adba649cbb493a9fc2c
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.18.0-7-generic
  server: lxd
  server_pid: 4922
  server_version: "3.5"
  storage: ""
  storage_version: ""
  server_clustered: false
  server_name: kvm-c3

# Issue description

Cannot run 'lxd init' on kvm cosmic daily cloud-images images  buildno: 20180926. No lxdbr0 bridge is created until lxd.daemon service is manually restarted.  This may be the same issue that is currently blocking cloud-init lxd integration tests on kvm for cosmic only (no bionic/xenial issues). As cloud-init integration tests issue the same commands listed below on a kvm. We see timeouts when the lxd deb is trying to install the lxd snap. It feels a bit like is losing a race on network setup.

# Steps to reproduce

 1. multipass launch daily:cosmic -n kvm-c1
 2. multipass exec kvm-c1 sudo apt-get update
 3. multipass exec kvm-c1 sudo apt-get install lxd (choosing latest or stable)
 4. multipass exec kvm-c1 -- lxd waitready --timeout=300
 5. multipass exec kvm-c1 -- sudo lxd init --auto --storage-backend=dir
   // Errors seen here: Error: Failed to create network 'lxdbr0': Failed to list ipv4 rules for LXD network lxdbr0 (table filter)
 // no lxdbr0 created
6. multipass exec kvm-c1 -- ip addr | grep lxd
// Manual restart of lxd.daemon completes setup of lxdbr0
7. multipass exec kvm-c4 sudo systemctl restart snap.lxd.daemon
// lxdbr0 found
8. multipass exec kvm-c1 -- ip addr | grep lxd
  ...lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000

# Information to attach

 - from journalctl, the relevant information related to the lxd init command seems to shed light on lxdbr0 losing carrier
Sep 27 19:56:23 kvm-c4 sudo[4529]: multipass : TTY=pts/0 ; PWD=/home/multipass ; USER=root ; COMMAND=/usr/bin/lxd init --auto --storage-backend=dir
Sep 27 19:56:23 kvm-c4 sudo[4529]: pam_unix(sudo:session): session opened for user root by multipass(uid=0)
Sep 27 19:56:23 kvm-c4 kernel: spl: loading out-of-tree module taints kernel.
Sep 27 19:56:23 kvm-c4 kernel: SPL: Loaded module v0.7.9-3ubuntu2
Sep 27 19:56:23 kvm-c4 kernel: znvpair: module license 'CDDL' taints kernel.
Sep 27 19:56:23 kvm-c4 kernel: Disabling lock debugging due to kernel taint
Sep 27 19:56:25 kvm-c4 kernel: ZFS: Loaded module v0.7.9-3ubuntu4, ZFS pool version 5000, ZFS filesystem version 5
Sep 27 19:56:26 kvm-c4 kernel: bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
Sep 27 19:56:26 kvm-c4 systemd-udevd[4612]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Sep 27 19:56:26 kvm-c4 systemd-networkd[586]: lxdbr0: Gained carrier
Sep 27 19:56:26 kvm-c4 networkd-dispatcher[793]: WARNING:Unknown index 3 seen, reloading interface list
Sep 27 19:56:26 kvm-c4 systemd-networkd[586]: lxdbr0: Gained IPv6LL
Sep 27 19:56:26 kvm-c4 systemd-udevd[4612]: Could not generate persistent MAC address for lxdbr0: No such file or directory
Sep 27 19:56:37 kvm-c4 systemd-networkd[586]: lxdbr0: Lost carrier
Sep 27 19:56:47 kvm-c4 sudo[4529]: pam_unix(sudo:session): session closed for user root
Sep 27 19:56:47 kvm-c4 sshd[4418]: pam_unix(sshd:session): session closed for user multipass
Sep 27 19:56:47 kvm-c4 systemd-logind[775]: Session 33 logged out. Waiting for processes to exit.
Sep 27 19:56:47 kvm-c4 systemd-logind[775]: Removed session 33.
Sep 27 19:56:47 kvm-c4 systemd[4421]: Stopped target Default.
Sep 27 19:56:47 kvm-c4 systemd[4421]: Stopped target Basic System.
Sep 27 19:56:47 kvm-c4 systemd[4421]: Stopped target Timers.
Sep 27 19:56:47 kvm-c4 systemd[4421]: Stopped target Paths.

**Comment by stgraber** [comment]
Odd, sounds like the iptables kernel modules aren't auto-loading...

**Comment by stgraber** [comment]
Right, so I don't think it's a LXD problem because even outside of LXD, we get this:
```
root@kvm-c1:~# iptables -L -n -v
iptables: No chain/target/match by that name.
```

IPv6 doesn't appear to suffer from this problem somehow.

Installing `linux-generic` which gets you the rest of the Ubuntu kernel modules fixes the issue, so this is an Ubuntu kernel bug, closing.

**Comment by smoser** [comment]
Opened ubuntu bug at 
 https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1795036
