### ISSUE TITLE
Please add --dns-loop-detect option to dnsmasq run by LXD

### ISSUE THREAD

**Issue by rudiservo** [lxc/lxd#5084]
# Issue description

There is an infinite loop on resolving dns names between dnsmasq and resolved when you add dnsmasq as a resolver for container hostnames to resolved.

What happens is that dnsmasq sends a query of IPv6 to resolved and since it get no real response from outside dns servers they keep it on the loop between 127.0.0.1 and 127.0.0.53. Also sends some extra IPv4 query but since they are resolved the issue ends up resolving by itself

Adding --dns-loop-detect on the dnsmasq application start will avoid dnsmasq going on a excessive loop.
Although is not the preferable fix, it will mitigate the issue at the moment and it is a quick fix.
The preferable fix would be according to simos is "to access programmatically systemd-resolved over DBUS and set the configuration there". Possibly make another issue with this.

Discussion about the issue and debugging along with @simos (thanks for helping)
https://discuss.linuxcontainers.org/t/ubuntu-18-04-infinite-loop-dnsmasq-systemd-resolved/2768/9

# Steps to reproduce

 1. Install clean OS Ubuntu Desktop
 2. apt install lxd
 3. follow simos instructions about container hostname resolving on host
https://blog.simos.info/how-to-use-lxd-container-hostnames-on-the-host-in-ubuntu-18-04/
 4. start/stop a container and check for top to see the cpu usage, or wireshark on loopback

 * Distribution: Ubuntu (Xubuntu) Desktop
 * Distribution version: 18.04
# lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
  certificate_fingerprint: ba55d2feb65288b06761fee2244db0883587237815b059dc6c6472180385fa00
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-34-generic
  server: lxd
  server_pid: 22741
  server_version: 3.0.1
  storage: dir
  storage_version: "1"
  server_clustered: fa

**Comment by stgraber** [comment]
Since dnsmasq loops aren't the default setup, it doesn't really make sense to slow down resolving for everyone when you can just pass that option by setting raw.dnsmasq on the bridge

**Comment by rudiservo** [comment]
it doens't work there, I tried!

**Comment by rudiservo** [comment]
OK then how do I solve this?

**Comment by stgraber** [comment]
Set raw.dnsmasq to dns-loop-detect

**Comment by rudiservo** [comment]
@stgraber Got it! thank you

`# lxc network edit lxdbr0`

but if you read the discussion between me and simos he mentioned something about a similar issue that LXD has but it was with libvirt. anyways pasting it bellow and leave it to your consideration.

@simos
> I had a look at those two bug reports on Launchpad. The first references an additional report,
https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1694161 1

> which describes a similar issue that we have with LXD but they get this with libvirt.
> Here’s the text,

> In debugging bug #1694156, I found that ultimately my problem was triggered by a hard-coded /etc/resolvconf/resolv.conf.d/tail I had set once upon a time pointing to my libvirt dnsmasq server. It should not be necessary to manually edit /etc/resolvconf/resolv.conf.d/tail to register dnsmasq; instead, on a system where systemd-resolved is running, libvirt should use the DBUS protocol to register its dnsmasq with systemd-resolved, specifying both SetLinkDNS and SetLinkDomains. This would enable properly-scoped DNS lookups for only the hosts on the libvirt bridge, avoiding any possibility of DNS loops and avoiding the need for manual configuration.

>To do this properly, libvirt does need to declare a link domain (SetLinkDomains) that doesn’t conflict with other public DNS, or other non-authoritative DNS that may be configured on the system. I would suggest using just ‘libvirt.’ as a TLD, by default.

>For example implementation, please see ./src/dns-manager/nm-dns-systemd-resolved.c:send_updates() in the network-manager source.`

>It describes how to do this programmatically, which means that there should be a way to interpret as additional command-line options to the configuration we do for LXD.

**Comment by stgraber** [comment]
To me it'd be more useful if there was a way for users to dump persistent configuration into resolved.

Having LXD or libvirt configure resolved directly only really ever works if you have a single bridge and you know the user wants it integrated with the system's resolver.

Many people don't actually want such integration and there are many cases where you'll end up with multiple bridges that are internally using the same DNS domain, making it impossible to configure the system resolver to redirect for that domain without also knowing exactly which one of the bridges you actually want DNS queries to go to.

So if you could just dump a tiny ini file somewhere in /etc/systemd/network to declare that for domain XYZ you want it forwarded to IP 1.2.3.4 on bridge brX, that'd make things explicit, survive restarts of networkd/resolved and could be used for much more than just lxd/libvirt networking.

**Comment by stgraber** [comment]
For many such system integrations, my main goto reason for push back is that LXD is a networked API, you can trivially drive it from a different machine and many users are actually in environments where their LXD daemon doesn't run on the same machine as their LXD client.

In such an environment, them running `lxc network create` and suddenly having the resolver on the LXD server be altered feels rather wrong (and a similar situation applies for things like hooks, various filesystem operations, ...)

**Comment by rudiservo** [comment]
@stgraber I completely understand and it is a safer decision, even if it was a opt-in configuration it might lead to some unwanted issues.

Going to try and figure out some kind of persistent network configuration, since even if you create a service like in simos blog, if you have no containers running LXD wont put the bridge up so no configuration is made into systemd-resolved and you have to manually set it up again, not really a deal breaker but a annoying.

I am just trying to keep multi project development going fast and annoyance free, resolving api's inside containers locally is easier if you can resolve said container, it's a tool for my team to cut down on time wasted deploying stuff constantly since an image launch is faster then reinstalling stuff, specially with large databases and we break things very fast.

Again, thank you for helping me out!

**Comment by rudiservo** [comment]
For history sake

You can add a file
http://manpages.ubuntu.com/manpages/bionic/man5/resolved.conf.5.html

in my case 
`mkdir /etc/systemd/resolved.conf.d`
`nano /etc/systemd/resolved.conf.d/lxdbr0.conf`

and paste this inside

```
[Resolve]
DNS=10.146.38.1
Domains=lxd
```
