### ISSUE TITLE
Cannot assign static lease to eth0 when in default profile

### ISSUE THREAD

**Issue by p53** [lxc/lxd#5108]
# Required information

 * Distribution: bionic
 * Distribution version: 18.04.1
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-34-generic
   * LXC version:
   * LXD version: 3.0.1-0ubuntu1~18.04.1
   * Storage backend in use: directory

# Issue description

assigning static lease to eth0 when this interface is present in default profile (i didn't try with custom profiles) generates this error
Error: The device doesn't exist

interesting is that lxc config show test1 doesn't show eth0 in devices but with --expanded flag it shows it in devices

# Steps to reproduce

 1. install lxd
 2. lxc launch ubuntu:xenial test1
 3. lxc config device set test1 eth0 ipv4.address 10.116.15.100

```
lxc config device set test1 eth0 ipv4.address 10.116.15.100                 [135/1857]
                                                                                                                
Error: The device doesn't exist  

lxc list
+------+---------+---------------------+-----------------------------------------------+------------+-----------+
| NAME |  STATE  |        IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+------+---------+---------------------+-----------------------------------------------+------------+-----------+
| test1 | RUNNING | 10.116.15.47 (eth0) | fd42:930a:da25:4c7b:216:3eff:fe97:6992 (eth0) | PERSISTENT | 0         |
+------+---------+---------------------+-----------------------------------------------+------------+-----------+

lxc info test1
Name: test1
Remote: unix://
Architecture: x86_64
Created: 2018/10/04 21:58 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 19444
Ips:
  eth0: inet    10.116.15.47    veth4P0II0
  eth0: inet6   fd42:930a:da25:4c7b:216:3eff:fe97:6992  veth4P0II0
  eth0: inet6   fe80::216:3eff:fe97:6992        veth4P0II0
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 9
  CPU usage:
    CPU usage (in seconds): 0
  Memory usage:
    Memory (current): 25.63MB
    Memory (peak): 30.08MB
  Network usage:
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    eth0:
      Bytes received: 4.37kB
      Bytes sent: 2.06kB
      Packets received: 37
      Packets sent: 16

lxc config show test1 --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.build: "20181004_07:42"
  image.description: Ubuntu xenial amd64 (20181004_07:42)
  image.distribution: ubuntu
  image.name: ubuntu-xenial-amd64-default-20181004_07:42
  image.os: ubuntu
  image.release: xenial
  image.serial: "20181004_07:42"
  image.variant: default
  volatile.base_image: 950e32336b6551a7cc619bbc318d97bf64ebc26be4e8daa971539a1b0e616f0d
  volatile.eth0.hwaddr: 00:16:3e:97:69:92
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

```
# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
That's perfectly normal, `lxc config device` interacts with devices on the container, if it's inherited from a profile, it's not in the container's configuration.

To copy a device from the profile into the container specific config and override a config key, you can use `lxc config device override`.

At which point the device will show up in `lxc config show` and the container will have its own distinct version of that device.
