### ISSUE TITLE
lxc launch: Error: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.node_id, storage_volumes.name, storage_volumes.type

### ISSUE THREAD

**Issue by abentley** [lxc/lxd#5109]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
$ lxc-start --version

Command 'lxc-start' not found, but can be installed with:

sudo apt install lxc-utils

abentley@skinny:~/ssimwave/big$ lxc info
config:
  core.https_address: '[::]:8443'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.90.13:8443
  - '[fdf0:3b88:9ce6::50b]:8443'
  - '[2607:f2c0:9366:ea00::50b]:8443'
  - '[fdf0:3b88:9ce6:0:7c35:7426:53d9:89ad]:8443'
  - '[2607:f2c0:9366:ea00:a2fb:125e:3ebd:6a9c]:8443'
  - 192.168.122.1:8443
  - 10.3.198.1:8443
  - 172.19.0.1:8443
  - 172.17.0.1:8443
  - 172.18.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIGyjCCBLKgAwIBAgIRALNZdqvV6bhS/M4lZRcmpiMwDQYJKoZIhvcNAQELBQAw
    NDEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEUMBIGA1UEAwwLcm9vdEBz
    a2lubnkwHhcNMTYwMjExMjIwOTU4WhcNMjYwMjA4MjIwOTU4WjA0MRwwGgYDVQQK
    ExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QHNraW5ueTCCAiIw
    DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALZgID0ev+ifq5r7Jj1mvjDMAY17
    JfuWP0eX5ECnclmYeO5O/m9J5+N97R1q3BqGh7puCqeZsuSPdlrkrioGNhtKJKGY
    YDP4MMArOi5cZ0GBUiuGwQJM22AhI3QjgA/BjSus7Ppqud3nhfn830OGfRNnXPm+
    meS9TMO5cV80ZDhGelqcws9vHhCx+RYs87oUjPQqAXIilxS85mgaXR6w5+JzUGKl
    NIP6u+Yn6+4FIh6ueqh2xeFsgGX79HkWB1smEFfq4+p2F443bcPGpTVxbEDcfAQk
    FQbMap4PXn4AR9RFOl5f2b/Q21SmOf5WOr+X29dRq6WKa5HKBggjwzGSe+IU00/D
    XKguRdYxrrf5TVANGdCiZb7nneySlNAtwznSlVzM6jUB6ptB2fJ5rev03+32s6nh
    DfODiWA5xFuqrNKMtNZsSqovbBRk6Bg3Uu9JBKIwD/FoiemgtS+D4tjqNaiMqXx8
    8fdpgNyl4ZLLKbSytHd8dREHHIllZU0L4hjMOASqLdjPC51IusszHSZu4HDbLRcS
    jBHypaAjg2R9UKcFWIZorRrAov239iCwhzMsT4LJjZXRSLZ+lyIiCePzvQLj+WW/
    u7aK/SqNKXNFaDDHannm0Qo/9ji07KJVMgHyHwoimOzcw4mPWJGzA+1KxtxUpxs2
    9bQaCP0BkIdNUY4ZAgMBAAGjggHVMIIB0TAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0l
    BAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADCCAZoGA1UdEQSCAZEwggGNggZz
    a2lubnmCDzE5Mi4xNjguMS4xMy8yNIInZmRmMDozYjg4OjljZTY6MDpmOWU5OmI2
    ODY6N2RlOTpmYzRhLzY0gidmZGYwOjNiODg6OWNlNjowOjVlNTE6NGZmZjpmZTc1
    OmQ4NTIvNjSCKjI2MDc6ZjJjMDo4MDA4OmRkOWY6ZjllOTpiNjg2OjdkZTk6ZmM0
    YS82NIIqMjYwNzpmMmMwOjgwMDg6ZGQ5Zjo1ZTUxOjRmZmY6ZmU3NTpkODUyLzY0
    ghxmZTgwOjo1ZTUxOjRmZmY6ZmU3NTpkODUyLzY0ghAxOTIuMTY4LjEyMi4xLzI0
    ggsxMC4wLjMuMS8yNIIcZmU4MDo6MWM3MDphZGZmOmZlYmU6ZDhjMi82NIIcZmU4
    MDo6ZmNmMTo2ZWZmOmZlNTU6MmExMS82NIIcZmU4MDo6ZmNlZjphOGZmOmZlOGM6
    Yjk5OS82NIIQMTAuMTcyLjY1LjIzNi8xOIIfMjAwMTo2N2M6MTU2Mjo4MDA3Ojph
    YWM6NDFlYy82NDANBgkqhkiG9w0BAQsFAAOCAgEAL2LyZhwZiC5sAsrUTTbzbFuF
    mIhnJ1D6NJxX9nuamzkFXaMo119bHVfwiz6k72lK3zhGBSwgCmwTjuXPSsItTs+Y
    d8myU7seYzPwF5dvuvra5LNvgJkqfUHcjWYvHD55Gavvh5yvP0HTcS4quUNCzgBS
    2AsOHlBYmXdmAvFn8Y09CC0cXLEyJJ9DWEliSIdJIE0CB7Wdfs/bU0ynTVGo8PVr
    eNrR2ldKp8oVz7zHn0Wpvees4kESNeuq5EzyrCwLUsdq3W8IsZE351qVij5hzjhO
    8QWh2KqpEBHO/g0LIj6w5ZwfsRjRkz/WwyN/Jx0h/LEiZscqqERw7+wH8JCSrQwj
    xsZc26NwGuiUta8NMqZBIVczW7vf/533O+5T6rcqkcxYR9lzF8oqsNK+tDKAB99d
    xIvQzd57WeC/brjG+t7RKR4LgMNSoyMWmG5qqHve9l/KXB2ay93JuFdFQXXc6hAc
    VCZv0YaKGfo0jEmGlYfIy9mhmKeeEeH+o0Y9kdW2ESb4SxvCoE3xmhrl1LTtMkuC
    wwKiiLUpYVK4rhElqOC5/osky/77VC6iVTgJ+LXrEhNcP2lMWi3Km84JvUxTYxf6
    aCSYb+5mslNU3UIYPsnDDWcyx3tjJzEYmQjdhHi8u6nZPyqlKE/tqLuKzRADpuG4
    lt00J0Sq4e2XkK2pCAs=
    -----END CERTIFICATE-----
  certificate_fingerprint: 9cd55966bc788d26dee12d36835024f71e372515c2b121ed9b12b58b8a64e072
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-36-generic
  server: lxd
  server_pid: 2960
  server_version: 3.0.1
  storage: dir | btrfs
  storage_version: 1 | 4.15.1
  server_clustered: false
  server_name: skinny

# Issue description

When I run `lxc launch xavier-img xavier2` I got 
Creating xavier2
Error: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.node_id, storage_volumes.name, storage_volumes.type

When I re-ran the command, it succeeded.

Note: the original source, xavier, was on a different storage pool.  This was the only way I could find to migrate* a container from one store to another.  (It might have been easier to copy it to a remote lxd and then back!)

# Steps to reproduce

 1. lxc publish xavier xavier-img
 2. lxc launch xavier-img xavier2

# Information to attach
None

**Comment by stgraber** [comment]
This was fixed already (last week), basically in some creation failure cases, the volume entry in the database wouldn't be deleted, causing the error your ran into.

Running it twice fixes it because the failure does trigger the right cleanup code and so gets rid of the database entry.

**Comment by tmartinx** [comment]
Hey guys,

I just saw this exactly same error on a fully updated Ubuntu 18.04.

    root@floyd:~# lxc image import bionic-server-cloudimg-amd64-lxd.tar.xz bionic-server-cloudimg-amd64-root.tar.xz --alias bionicloud
    Image imported with fingerprint: 9bd41c19058ad596166680b19f35182b81394c4a856e2054ceb9fbc9cc68f631
    root@floyd:~# lxc image list 
    +------------+--------------+--------+--------------------------------------+--------+----------+------------------------------+
    |   ALIAS    | FINGERPRINT  | PUBLIC |             DESCRIPTION              |  ARCH  |   SIZE   |         UPLOAD DATE          |
    +------------+--------------+--------+--------------------------------------+--------+----------+------------------------------+
    | bionicloud | 9bd41c19058a | no     | Ubuntu 18.04 LTS server (20181212)   | x86_64 | 140.49MB | Dec 13, 2018 at 5:10am (UTC) |
    +------------+--------------+--------+--------------------------------------+--------+----------+------------------------------+
    |            | 0911ad595f05 | no     | Ubuntu bionic amd64 (20181212_07:42) | x86_64 | 120.84MB | Dec 13, 2018 at 3:50am (UTC) |
    +------------+--------------+--------+--------------------------------------+--------+----------+------------------------------+
    root@floyd:~# lxc launch bionicloud nuvem
    Creating nuvem
    Error: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.node_id, storage_volumes.name, storage_volumes.type
    root@floyd:~# lxc launch bionicloud nuvem
    Creating nuvem
    Starting nuvem

Cheers!
