### ISSUE TITLE
publish + launch + ssh = WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!

### ISSUE THREAD

**Issue by abentley** [lxc/lxd#5110]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
config:
  core.https_address: '[::]:8443'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.90.13:8443
  - '[fdf0:3b88:9ce6::50b]:8443'
  - '[2607:f2c0:9366:ea00::50b]:8443'
  - '[fdf0:3b88:9ce6:0:7c35:7426:53d9:89ad]:8443'
  - '[2607:f2c0:9366:ea00:a2fb:125e:3ebd:6a9c]:8443'
  - 192.168.122.1:8443
  - 10.3.198.1:8443
  - 172.19.0.1:8443
  - 172.17.0.1:8443
  - 172.18.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIGyjCCBLKgAwIBAgIRALNZdqvV6bhS/M4lZRcmpiMwDQYJKoZIhvcNAQELBQAw
    NDEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEUMBIGA1UEAwwLcm9vdEBz
    a2lubnkwHhcNMTYwMjExMjIwOTU4WhcNMjYwMjA4MjIwOTU4WjA0MRwwGgYDVQQK
    ExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QHNraW5ueTCCAiIw
    DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALZgID0ev+ifq5r7Jj1mvjDMAY17
    JfuWP0eX5ECnclmYeO5O/m9J5+N97R1q3BqGh7puCqeZsuSPdlrkrioGNhtKJKGY
    YDP4MMArOi5cZ0GBUiuGwQJM22AhI3QjgA/BjSus7Ppqud3nhfn830OGfRNnXPm+
    meS9TMO5cV80ZDhGelqcws9vHhCx+RYs87oUjPQqAXIilxS85mgaXR6w5+JzUGKl
    NIP6u+Yn6+4FIh6ueqh2xeFsgGX79HkWB1smEFfq4+p2F443bcPGpTVxbEDcfAQk
    FQbMap4PXn4AR9RFOl5f2b/Q21SmOf5WOr+X29dRq6WKa5HKBggjwzGSe+IU00/D
    XKguRdYxrrf5TVANGdCiZb7nneySlNAtwznSlVzM6jUB6ptB2fJ5rev03+32s6nh
    DfODiWA5xFuqrNKMtNZsSqovbBRk6Bg3Uu9JBKIwD/FoiemgtS+D4tjqNaiMqXx8
    8fdpgNyl4ZLLKbSytHd8dREHHIllZU0L4hjMOASqLdjPC51IusszHSZu4HDbLRcS
    jBHypaAjg2R9UKcFWIZorRrAov239iCwhzMsT4LJjZXRSLZ+lyIiCePzvQLj+WW/
    u7aK/SqNKXNFaDDHannm0Qo/9ji07KJVMgHyHwoimOzcw4mPWJGzA+1KxtxUpxs2
    9bQaCP0BkIdNUY4ZAgMBAAGjggHVMIIB0TAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0l
    BAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADCCAZoGA1UdEQSCAZEwggGNggZz
    a2lubnmCDzE5Mi4xNjguMS4xMy8yNIInZmRmMDozYjg4OjljZTY6MDpmOWU5OmI2
    ODY6N2RlOTpmYzRhLzY0gidmZGYwOjNiODg6OWNlNjowOjVlNTE6NGZmZjpmZTc1
    OmQ4NTIvNjSCKjI2MDc6ZjJjMDo4MDA4OmRkOWY6ZjllOTpiNjg2OjdkZTk6ZmM0
    YS82NIIqMjYwNzpmMmMwOjgwMDg6ZGQ5Zjo1ZTUxOjRmZmY6ZmU3NTpkODUyLzY0
    ghxmZTgwOjo1ZTUxOjRmZmY6ZmU3NTpkODUyLzY0ghAxOTIuMTY4LjEyMi4xLzI0
    ggsxMC4wLjMuMS8yNIIcZmU4MDo6MWM3MDphZGZmOmZlYmU6ZDhjMi82NIIcZmU4
    MDo6ZmNmMTo2ZWZmOmZlNTU6MmExMS82NIIcZmU4MDo6ZmNlZjphOGZmOmZlOGM6
    Yjk5OS82NIIQMTAuMTcyLjY1LjIzNi8xOIIfMjAwMTo2N2M6MTU2Mjo4MDA3Ojph
    YWM6NDFlYy82NDANBgkqhkiG9w0BAQsFAAOCAgEAL2LyZhwZiC5sAsrUTTbzbFuF
    mIhnJ1D6NJxX9nuamzkFXaMo119bHVfwiz6k72lK3zhGBSwgCmwTjuXPSsItTs+Y
    d8myU7seYzPwF5dvuvra5LNvgJkqfUHcjWYvHD55Gavvh5yvP0HTcS4quUNCzgBS
    2AsOHlBYmXdmAvFn8Y09CC0cXLEyJJ9DWEliSIdJIE0CB7Wdfs/bU0ynTVGo8PVr
    eNrR2ldKp8oVz7zHn0Wpvees4kESNeuq5EzyrCwLUsdq3W8IsZE351qVij5hzjhO
    8QWh2KqpEBHO/g0LIj6w5ZwfsRjRkz/WwyN/Jx0h/LEiZscqqERw7+wH8JCSrQwj
    xsZc26NwGuiUta8NMqZBIVczW7vf/533O+5T6rcqkcxYR9lzF8oqsNK+tDKAB99d
    xIvQzd57WeC/brjG+t7RKR4LgMNSoyMWmG5qqHve9l/KXB2ay93JuFdFQXXc6hAc
    VCZv0YaKGfo0jEmGlYfIy9mhmKeeEeH+o0Y9kdW2ESb4SxvCoE3xmhrl1LTtMkuC
    wwKiiLUpYVK4rhElqOC5/osky/77VC6iVTgJ+LXrEhNcP2lMWi3Km84JvUxTYxf6
    aCSYb+5mslNU3UIYPsnDDWcyx3tjJzEYmQjdhHi8u6nZPyqlKE/tqLuKzRADpuG4
    lt00J0Sq4e2XkK2pCAs=
    -----END CERTIFICATE-----
  certificate_fingerprint: 9cd55966bc788d26dee12d36835024f71e372515c2b121ed9b12b58b8a64e072
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-36-generic
  server: lxd
  server_pid: 2960
  server_version: 3.0.1
  storage: btrfs | dir
  storage_version: 4.15.1 | 1
  server_clustered: false
  server_name: skinny

# Issue description
I published an image from a container, launched a new container based on that image, and it had the same IP address as the original container, but a different SSH host key.

When I tried to SSH into the new container, I got:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:gIMpE5ueJxbr/lfn9oo38h6NzQsH8doPYLvy7WB6zl8.
Please contact your system administrator.
Add correct host key in /home/abentley/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/abentley/.ssh/known_hosts:2212
  remove with:
  ssh-keygen -f "/home/abentley/.ssh/known_hosts" -R "xavier"
ECDSA host key for xavier has changed and you have requested strict checking.
Host key verification failed.

# Steps to reproduce

 1. lxc publish xavier --alias xavier-img
 2. lxc launch xavier-img xavier2
 3. find ip address of xavier2
 4. ssh $IP_ADDRESS_OF_XAVIER2

# Information to attach
Both versions of xavier have the same MAC address: 00:16:3e:ae:de:18
lxc exec xavier ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
21: eth0@if22: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:33:03:ef brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.3.198.243/24 brd 10.3.198.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe33:3ef/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by stgraber** [comment]
Can you show `lxc config show` and `lxc config show --expanded` for both the original and new container?

Also, does your image include cloud-init? If so, that's likely what generated a new SSH key for you.

**Comment by abentley** [comment]
The image includes cloud-init.  It was based on the official Ubuntu 16.04 i386 image.

$ lxc config show xavier
architecture: i686
config:
  boot.autostart: "0"
  image.architecture: i386
  image.description: ubuntu 16.04 LTS i386 (release) (20170516)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170516"
  image.version: "16.04"
  volatile.base_image: 564faf78be032dd1ec4a910f9f7b55f0e1d6c8635ea2bc33365299d3e0413061
  volatile.eth0.hwaddr: 00:16:3e:33:03:ef
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":345536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":345536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":345536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":345536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
devices: {}
ephemeral: false
profiles:
- old-default
stateful: false
description: ""
abentley@skinny:~/ssimwave/big$ lxc config show --expanded xavier
architecture: i686
config:
  boot.autostart: "0"
  image.architecture: i386
  image.description: ubuntu 16.04 LTS i386 (release) (20170516)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170516"
  image.version: "16.04"
  volatile.base_image: 564faf78be032dd1ec4a910f9f7b55f0e1d6c8635ea2bc33365299d3e0413061
  volatile.eth0.hwaddr: 00:16:3e:33:03:ef
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":345536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":345536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":345536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":345536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- old-default
stateful: false
description: ""
abentley@skinny:~/ssimwave/big$ lxc config show xavier2
architecture: i686
config:
  volatile.base_image: b59ce1c39c41c75410a8fb51cb6106c319b1ee751a3fb1ed957c293f2056ec2d
  volatile.eth0.hwaddr: 00:16:3e:ae:de:18
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":345536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":345536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":345536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":345536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
abentley@skinny:~/ssimwave/big$ lxc config show --expanded xavier2
architecture: i686
config:
  volatile.base_image: b59ce1c39c41c75410a8fb51cb6106c319b1ee751a3fb1ed957c293f2056ec2d
  volatile.eth0.hwaddr: 00:16:3e:ae:de:18
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":345536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":345536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":345536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":345536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: btrfs-pool
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

**Comment by abentley** [comment]
Note: github appears to interpret "de" as the german flag.

**Comment by stgraber** [comment]
Ok, so cloud-init would probably explain the keys being re-generated.

Now the MAC thing is odd because the two containers you showed above have different MACs:
 - xavier is `00:16:3e:33:03:ef`
 - xavier2 is `00:16:3e:ae:de18`

You're saying that inside the running two containers, they both show `00:16:3e:ae:de18`?

**Comment by abentley** [comment]
Since it's not based on MAC address, I bet it's based on dhclient requesting that IP address, based on /var/lib/dhcp/dhclient.eth0.leases or similar.

Also, is this still incomplete?  What other information would make it complete?

**Comment by stgraber** [comment]
It could indeed be that dnsmasq is issuing the lease based on client identifier rather than MAC in this case... Does wiping /var/lib/dhcp and restarting the container get you a different address?

**Comment by stgraber** [comment]
`sudo cat /var/lib/lxd/networks/lxdbr0/dnsmasq.leases` prior to that may also be useful.

**Comment by stgraber** [comment]
Note that I tried to reproduce this here, unsuccessfully:
```
stgraber@castiana:~$ lxc launch ubuntu:16.04/i386 test
Creating test
Starting test                                 
stgraber@castiana:~$ lxc stop test
stgraber@castiana:~$ lxc publish test --alias test
Container published with fingerprint: a7145be613c4da367329da5727191a637549689f9e084b6d20c2bb572fbf1530
stgraber@castiana:~$ lxc launch test test1
Creating test1
Starting test1
stgraber@castiana:~$ lxc start test
stgraber@castiana:~$ lxc list
+-------------+---------+----------------------+----------------------------------------------+------------+-----------+
|    NAME     |  STATE  |         IPV4         |                     IPV6                     |    TYPE    | SNAPSHOTS |
+-------------+---------+----------------------+----------------------------------------------+------------+-----------+
| test        | RUNNING | 10.166.11.247 (eth0) | 2001:470:b368:4242:216:3eff:fec5:92de (eth0) | PERSISTENT |           |
+-------------+---------+----------------------+----------------------------------------------+------------+-----------+
| test1       | RUNNING | 10.166.11.246 (eth0) | 2001:470:b368:4242:216:3eff:fe93:11fe (eth0) | PERSISTENT |           |
+-------------+---------+----------------------+----------------------------------------------+------------+-----------+
stgraber@castiana:~$ sudo cat /var/lib/lxd/networks/lxdbr0/dnsmasq.leases
1538754366 00:16:3e:c5:92:de 10.166.11.247 test *
1538754362 00:16:3e:93:11:fe 10.166.11.246 test1 *
duid 00:01:00:01:21:37:4b:7e:66:0e:15:d3:12:42
```

**Comment by abentley** [comment]
Here are steps to reproduce.  At different times, both containers have ip address `10.3.198.221/24`

Your test shows that two machines don't have the same IP address at the same time, but I was never asserting that.  I was saying that, if the old container is stopped, and a new container is launched based on the old container, the new container gets the same IP address that the old one had, and this upsets SSH because of the different host keys.

```
$ lxc launch ubuntu:16.04/i386 test
Creating test
Starting test
$ lxc exec test ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
113: eth0@if114: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:2b:65:c0 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.3.198.221/24 brd 10.3.198.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe2b:65c0/64 scope link 
       valid_lft forever preferred_lft forever
$ lxc stop test
$ lxc publish test --alias test-img
Container published with fingerprint: a53bd48065f1032fb829ed207fd8ac3b0e0463ce2915b5ae3aa08af3084b8825
$ lxc launch test-img test-copy
Creating test-copy
Starting test-copy
$ lxc exec test-copy ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
115: eth0@if116: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:50:85:c6 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.3.198.221/24 brd 10.3.198.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe50:85c6/64 scope link 
       valid_lft forever preferred_lft forever
$ 
```
/var/lib/lxd/networks/lxdbr0/dnsmasq.leases is empty after I stop the containers, so I don't think deleting it would help.  But deleting dhclient.eth0.leases does fix it:
```
lxc stop test-copy
abentley@skinny:~$ sudo -s
[sudo] password for abentley:
# rm /var/lib/lxd/storage-pools/btrfs-pool/containers/test-copy/rootfs/var/lib/dhcp/dhclient.eth0.leases
# exit
$ lxc start test-copy
$ lxc exec test-copy ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
117: eth0@if118: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:50:85:c6 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.3.198.74/24 brd 10.3.198.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe50:85c6/64 scope link 
       valid_lft forever preferred_lft forever
```
I think it makes sense to re-generate the SSH host key, but if cloud-init is going to do that, it should also delete any dhclient leases so that we don't get a new SSH host key with an old IP address.

**Comment by abentley** [comment]
Is there anything further?  If not, please remove the "incomplete" label.

**Comment by stgraber** [comment]
Ok, so looking into this again, it's not a LXD bug, though I do agree with you that maybe cloud-init could flush the lease file.

What's happening is:
 - First container gets IP from DHCP
 - On shutdown, first container sends a DHCPRELEASE message
 - dnsmasq flushes the lease entry (as expected following a DHCPRELEASE), freeing that IP
 - New container starts up and rather than performing a blank DHCP request, attempts to re-obtain its old lease
 - dnsmasq confirms that the IP in that lease isn't already in use and generates a new lease

As far as LXD's concerned, the two containers did get different MAC addresses so that part works properly and dnsmasq did behave the way it's supposed to.

If the original container is left running, then dnsmasq refuses to re-issue that lease and the second container properly gets a different address.
