### ISSUE TITLE
documentation doesn't say how to set description on existing image

### ISSUE THREAD

**Issue by akarelas-pt** [lxc/lxd#5111]
I'm using lxd 3.0.1

I was executing the lxc command with various parameters and with 'help' to discover a way to set the description on an existing image. But this documentation didn't appear anywhere.

Could you please make it appear somewhere?

Thank you.

**Comment by akarelas-pt** [comment]
Maybe it's not necessary... I discovered it with `lxc image edit <image-name>`

**Comment by stgraber** [comment]
Yeah, the description fields are only editable through the `edit` command at this point.
