### ISSUE TITLE
container network occasional problem with bridge network on bonding device

### ISSUE THREAD

**Issue by padoauk** [lxc/lxd#5112]
This is a report of network related problem.

I experienced occasional network problem of containers running on ubuntu server 18.04.1. Containers
can communicate with host IP always and they can communicate sometimes to the other hosts but they are disconnected occasionally. When the problem occurs, the ping from the container to external hosts does not reach at all, but very rarely they recover after, for example, several hours later. Disconnection happens much more easily. Under the problem, containers can communicate to the host and to other containers in the same host. The host can communicate external hosts.

The host network is organized by using netplan in the following topology.

                +-eno1-< <--lan_cable--> >-+
    br0--bond0-+                           +-- Cisco 3650
                +-en02-< <--lan_cable--> >-+

The bonding mode is balance-a1b. I also found that if one of the LAN cables is physically disconnected, this problem has never happened.
This problem happens quite often after the following procedure.

1. connect both of the LAN cables
1. stop all containers  (I am not sure whether “all” is necessary.）
1. start some of the containers
1. the problem occurs on the started container just after or serveral minutes after  the restart

By using iptraf-ng, I watched the bridge device, the following br0, as well as the slave devices.
Even if containers send a ping to the external hosts, no ping packet is detected, when they cannot
communicate. Ping packets are detected by iptraf-ng on these devices when the communication is working.

Here's the detail of the setting.

host's netplan setting

    network:
    version: 2
    renderer: networkd
    ethernets:
     eno1:
       dhcp4: no
     eno2:
       dhcp4: no
    bonds:
     bond0:
       interfaces: [eno1, eno2]
       parameters:
         mode: balanec-a1b
    bridges:
     br0:
       interfaces:
         - bond0
       addresses: [10.1.2.3/24]
       gateway4: 10.1.2.254
       dhcp4: no

host network interface status

    host# ip a s
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
      link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
      inet 127.0.0.1/8 scope host lo
         valid_lft forever preferred_lft forever
      inet6 ::1/128 scope host
         valid_lft forever preferred_lft forever
    2: eno1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP group default qlen 1000
      link/ether 0b:25:b5:f2:e1:34 brd ff:ff:ff:ff:ff:ff
    3: eno2: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc mq master bond0 state UP group default qlen 1000
      link/ether 0b:25:b5:f2:e1:35 brd ff:ff:ff:ff:ff:ff
    4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
      link/ether 0a:1a:6c:85:ff:ed brd ff:ff:ff:ff:ff:ff
      inet 10.1.2.3/24 brd 10.1.2.255 scope global br0
         valid_lft forever preferred_lft forever
      inet6 fe80::81a:6cff:fe85:ffed/64 scope link
         valid_lft forever preferred_lft forever
    5: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UP group default qlen 1000
      link/ether 0a:54:4b:f2:d7:10 brd ff:ff:ff:ff:ff:ff
    7: vethK4HOFU@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UP group default qlen 1000
      link/ether fe:ca:07:3e:2b:2d brd ff:ff:ff:ff:ff:ff link-netnsid 0
      inet6 fe80::fcca:7ff:fe3e:2b2d/64 scope link
     valid_lft forever preferred_lft forever
    9: veth77HJ0V@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UP group default qlen 1000
      link/ether fe:85:f0:ef:78:b2 brd ff:ff:ff:ff:ff:ff link-netnsid 1
      inet6 fe80::fc85:f0ff:feef:78b2/64 scope link
         valid_lft forever preferred_lft forever

container's network interface status

    root@bionic0:~# ip a s
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
      link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
      inet 127.0.0.1/8 scope host lo
         valid_lft forever preferred_lft forever
      inet6 ::1/128 scope host
         valid_lft forever preferred_lft forever
    6: eth0@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
      link/ether 00:16:3e:cb:ef:ce brd ff:ff:ff:ff:ff:ff link-netnsid 0
      inet 10.1.2.20/24 brd 10.1.2.255 scope global eth0
         valid_lft forever preferred_lft forever
      inet6 fe80::216:3eff:fecb:efce/64 scope link
         valid_lft forever preferred_lft forever

lxc profile

    # lxc profile show default
    config: {}
    description: Default LXD profile
    devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: br0
      type: nic
    root:
      path: /
      pool: default
      type: disk
    name: default
    # Required information

Here's summary of environment.

    Linux storkhost01 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=18.04
    DISTRIB_CODENAME=bionic
    DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
    ii  liblxc-common     3.0.1-0ubuntu1~18.04.2            amd64
    ii  liblxc1           3.0.1-0ubuntu1~18.04.2            amd64
    ii  lxcfs             3.0.1-0ubuntu2~18.04.1            amd64
    ii  lxd               3.0.1-0ubuntu1~18.04.1            amd64 
    ii  lxd-client        3.0.1-0ubuntu1~18.04.1            amd64

**Comment by stgraber** [comment]
Closing because that's not going to be a LXD issue, LXD plugs a point to point veth device into your bridge, so if traffic to host is working, then it's job is done.

Some potential things to look into:
 - Make sure you don't have MAC filtering or similar MAC handling enabled on your switch
 - Since you're dealing with a managed switch, why aren't you running in LACP mode? that may also clear out some potential confusion at the switch and kernel level
 - You may want to look at the `dmesg` output, with a bit of luck, the kernel may have logged something about potential network issues
