### ISSUE TITLE
Possible Event Race Condition

### ISSUE THREAD

**Issue by jtopjian** [lxc/lxd#5117]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-81-generic
   * LXC version: master
   * LXD version: 3.5
   * Storage backend in use: btrfs

# Issue description

I've been running the Terraform LXD acceptance test suite with the `-race` flag, trying to resolve some  race conditions, and I think it uncovered one with the core LXD/LXC client code.

Since the error is reporting the issue is in the client code, I'm pretty sure this isn't an LXD server issue nor a Terraform issue, though let me know if I'm wrong.

# Steps to reproduce

1. Clone the Terraform LXD repository on an existing server with the LXD server already running and configured:

```shell
$ go get github.com/sl1pm4t/terraform-provider-lxd
$ cd ~/go/src/github.com/sl1pm4t/terraform-provider-lxd
```

2. Set some environment variables (the `LXD_REMOTE` does not need to match):

```
export LXD_REMOTE=travis
export LXD_ADDR=localhost
export LXD_PORT=8443
export LXD_GENERATE_CLIENT_CERTS=true
export LXD_ACCEPT_SERVER_CERTIFICATE=true
export LXD_SCHEME=https
export LXD_PASSWORD=the-password
```

3. Run:

```shell
$ make testacc TESTARGS="-run=importBasic -race -count=1" 2>&1 | tee ~/lxd.log
```

You should see a DATA RACE error at some point:

https://gist.github.com/jtopjian/4071ab3d4c522d325b2819b597082c2d

The `WARNING: DATA RACE` error will happen at various points during the test. I've determined that they always happen during a `Wait()` call:

* https://github.com/sl1pm4t/terraform-provider-lxd/blob/master/lxd/resource_lxd_container.go#L255
* https://github.com/sl1pm4t/terraform-provider-lxd/blob/master/lxd/resource_lxd_container.go#L315
etc

Applying the following patch fixes the problem:

```diff
diff --git a/client/operations.go b/client/operations.go
index fc015c2..f27df75 100644
--- a/client/operations.go
+++ b/client/operations.go
@@ -152,16 +152,16 @@ func (op *operation) setupListener() error {
        _, err := op.listener.AddHandler([]string{"operation"}, func(data interface{}) {
                <-chReady
 
+               // We don't want concurrency while processing events
+               op.handlerLock.Lock()
+               defer op.handlerLock.Unlock()
+
                // Get an operation struct out of this data
                newOp := op.extractOperation(data)
                if newOp == nil {
                        return
                }
 
-               // We don't want concurrency while processing events
-               op.handlerLock.Lock()
-               defer op.handlerLock.Unlock()
-
                // Check if we're done already (because of another event)
                if op.listener == nil {
                        return
```

**Comment by stgraber** [comment]
Hmm, yeah, I think we were assuming that extractOperation doesn't access the struct itself, but that assumption is wrong as it's accessing op.ID, which makes it a potential race.

I think your fix should be fine, feel free to send it as a pull request or I can do it tomorrow.

**Comment by jtopjian** [comment]
@stgraber Thank you for the quick reply. Happy to open a PR :)

#5118
