### ISSUE TITLE
LXD wont start after hard reboot server

### ISSUE THREAD

**Issue by andrey900** [lxc/lxd#5144]
LXD wont start after hard reboot server

Syslog:
> Oct 11 18:11:54 god /usr/bin/snap[2818]: cmd.go:105: DEBUG: restarting into "/snap/core/current/usr/bin/snap"
Oct 11 18:11:54 god lxd.daemon[2818]: => Preparing the system
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Loading snap configuration
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Setting up mntns symlink (mnt:[4026532194])
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Setting up kmod wrapper
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Preparing /boot
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Preparing a clean copy of /run
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Preparing a clean copy of /etc
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Setting up ceph configuration
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Setting up LVM configuration
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Rotating logs
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Setting up ZFS (0.6)
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Escaping the systemd cgroups
Oct 11 18:11:54 god lxd.daemon[2818]: ==> Escaping the systemd process resource limits
Oct 11 18:11:54 god kernel: [ 1633.113660] cgroup: new mount options do not match the existing superblock, will be ignored
Oct 11 18:11:54 god lxd.daemon[2370]: mount namespace: 8
Oct 11 18:11:54 god lxd.daemon[2370]: hierarchies:
Oct 11 18:11:54 god lxd.daemon[2370]:   0: fd:   9: pids
Oct 11 18:11:54 god lxd.daemon[2370]:   1: fd:  10: freezer
Oct 11 18:11:54 god lxd.daemon[2370]:   2: fd:  11: devices
Oct 11 18:11:54 god lxd.daemon[2370]:   3: fd:  12: perf_event
Oct 11 18:11:54 god lxd.daemon[2370]:   4: fd:  13: net_cls,net_prio
Oct 11 18:11:54 god lxd.daemon[2370]:   5: fd:  14: memory
Oct 11 18:11:54 god lxd.daemon[2370]:   6: fd:  15: cpuset
Oct 11 18:11:54 god lxd.daemon[2370]:   7: fd:  16: cpu,cpuacct
Oct 11 18:11:54 god lxd.daemon[2370]:   8: fd:  17: blkio
Oct 11 18:11:54 god lxd.daemon[2370]:   9: fd:  18: name=systemd
Oct 11 18:11:54 god lxd.daemon[2370]: lxcfs.c: 152: do_reload: lxcfs: reloaded
Oct 11 18:11:54 god lxd.daemon[2818]: => Re-using existing LXCFS
Oct 11 18:11:54 god lxd.daemon[2818]: => Re-using existing LXCFS
Oct 11 18:11:54 god lxd.daemon[2818]: => Starting LXD
Oct 11 18:11:54 god lxd.daemon[2818]: lvl=warn msg="AppArmor support has been disabled because of lack of kernel support" t=2018-10-11T18:11:54+0300
Oct 11 18:11:54 god lxd.daemon[2818]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-10-11T18:11:54+0300
Oct 11 18:11:54 god lxd.daemon[2818]: lxd: src/vfs.c:1409: dqlite__vfs_open: Assertion `filename != NULL' failed.
Oct 11 18:11:54 god lxd.daemon[2818]: SIGABRT: abort
Oct 11 18:11:54 god lxd.daemon[2818]: PC=0x7f15c3e9b428 m=0 sigcode=18446744073709551610
Oct 11 18:11:54 god lxd.daemon[2818]: signal arrived during cgo execution
Oct 11 18:11:54 god lxd.daemon[2818]: goroutine 53 [syscall, locked to thread]:
Oct 11 18:11:54 god lxd.daemon[2818]: runtime.cgocall(0xf25f50, 0xc0003b7f20, 0x0)
Oct 11 18:11:54 god lxd.daemon[2818]: #011/build/lxd/parts/go/build/src/runtime/cgocall.go:128 +0x5e fp=0xc0003b7ef0 sp=0xc0003b7eb8 pc=0x40e7ee
...
Oct 11 18:11:55 god lxd.daemon[2818]: #011/build/lxd/parts/go/build/src/net/http/server.go:672 +0xd2
Oct 11 18:11:55 god lxd.daemon[2818]: rax    0x0
Oct 11 18:11:55 god lxd.daemon[2818]: rbx    0x7f15c524c000
Oct 11 18:11:55 god lxd.daemon[2818]: rcx    0x7f15c3e9b428
Oct 11 18:11:55 god lxd.daemon[2818]: rdx    0x6
Oct 11 18:11:55 god lxd.daemon[2818]: rdi    0xb50
Oct 11 18:11:55 god lxd.daemon[2818]: rsi    0xb50
Oct 11 18:11:55 god lxd.daemon[2818]: rbp    0x7f15c4244ac9
Oct 11 18:11:55 god lxd.daemon[2818]: rsp    0x7ffcb79c23c8
Oct 11 18:11:55 god lxd.daemon[2818]: r8     0x34d5ed0
Oct 11 18:11:55 god lxd.daemon[2818]: r9     0xfefefeff092d6300
Oct 11 18:11:55 god lxd.daemon[2818]: r10    0x8
Oct 11 18:11:55 god lxd.daemon[2818]: r11    0x206
Oct 11 18:11:55 god lxd.daemon[2818]: r12    0x581
Oct 11 18:11:55 god lxd.daemon[2818]: r13    0x7f15c4245470
Oct 11 18:11:55 god lxd.daemon[2818]: r14    0x4
Oct 11 18:11:55 god lxd.daemon[2818]: r15    0x10
Oct 11 18:11:55 god lxd.daemon[2818]: rip    0x7f15c3e9b428
Oct 11 18:11:55 god lxd.daemon[2818]: rflags 0x206
Oct 11 18:11:55 god lxd.daemon[2818]: cs     0x33
Oct 11 18:11:55 god lxd.daemon[2818]: fs     0x0
Oct 11 18:11:55 god lxd.daemon[2818]: gs     0x0
Oct 11 18:11:55 god lxd.daemon[2818]: => LXD failed to start
Oct 11 18:11:55 god systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=137/n/a
Oct 11 18:11:55 god /usr/bin/snap[2923]: cmd.go:105: DEBUG: restarting into "/snap/core/current/usr/bin/snap"
Oct 11 18:11:55 god lxd.daemon[2923]: => Stop reason is: host shutdown
Oct 11 18:11:55 god lxd.daemon[2923]: => Stopping LXD (with container shutdown)

Tell me how to start the service LXD

**Comment by stgraber** [comment]
Seems identical to #5139
