### ISSUE TITLE
lxd only works with "--debug" parameter from cli

### ISSUE THREAD

**Issue by cs-tim-buecher** [lxc/lxd#5175]
# Required information

 * Distribution: CentOS
 * Distribution version: 7.5.1804
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.10.0-862.14.4.el7.x86_64
   * LXC version:  2.0.9
   * LXD version: 3.6
   * Storage backend in use: btrfs 4.9.1

# Issue description

Tried to install LXD on a CentOS machine. Built from source, with Kernel modifications, manually downloaded Go 1.10 and installed all required packages. I used this approach, because I work in an Environment behind a firewall I cannot change thus am not able to use snapd. Everything worked pretty fine after one or two issues regarding missing packages.
The Issue here is: When I try to start the service via `systemctl` it fails with the error message below. But when I start it from the CLI with `lxd --debug` it works almost fine (except for a Database error) and I'm able to start containers. If I don't put the `--debug` in there, it doesn't show up, giving me only the message `AppArmor support has been disabled because of lack of kernel support`.

# Steps to reproduce

 1. Install required packages (f.e. dnsmasq, libuv-devel, libacl-devel, lxc-devel, libvirt, ...)
 2. Install Go Version 1.10 (because CentOS 7 has only 1.9)
 3. Install LXD on a CentOS 7 machine
 4. Create a Systemd-File in /etc/systemd/system/lxd.service
 5. run `lxd init`
 6. run `systemctl start lxd`

# Information to attach

 - Output from `systemctl start lxd`:
``` [root@testHost ~]# systemctl status lxd
● lxd.service - LXD Container Hypervisor
   Loaded: loaded (/etc/systemd/system/lxd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2018-10-16 09:22:40 EDT; 2s ago
  Process: 5083 ExecStart=/usr/bin/lxd --debug --logfile=/var/log/lxd/lxd.log (code=exited, status=127)
 Main PID: 5083 (code=exited, status=127)

Oct 16 09:22:40 emnos-one-05 systemd[1]: Unit lxd.service entered failed state.
Oct 16 09:22:40 emnos-one-05 systemd[1]: lxd.service failed.
Oct 16 09:22:40 emnos-one-05 systemd[1]: lxd.service holdoff time over, scheduling restart.
Oct 16 09:22:40 emnos-one-05 systemd[1]: start request repeated too quickly for lxd.service
Oct 16 09:22:40 emnos-one-05 systemd[1]: Failed to start LXD Container Hypervisor.
Oct 16 09:22:40 emnos-one-05 systemd[1]: Unit lxd.service entered failed state.
Oct 16 09:22:40 emnos-one-05 systemd[1]: lxd.service failed. 
```

- Error message for the database: `Database error: &errors.errorString{s:"sql: no rows in result set"}`

- Output from `lxc-checkconfig`:
```[root@testHost ~]# lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-3.10.0-862.14.4.el7.x86_64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled
Multiple /dev/pts instances: enabled
--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/blkio
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/devices
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/freezer
/sys/fs/cgroup/pids

Cgroup v2 mount points: 


Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loadedCONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled
```

**Comment by stgraber** [comment]
So the lack of `--debug` just makes LXD very quiet, it won't really print anything but should still work just fine. You can also try `--verbose` for a middle ground as far as what it'll log.

**Comment by stgraber** [comment]
My guess about the systemd unit is that your unit at /etc/systemd/system/lxd.service does not set the LD_LIBRARY_PATH environment variable which is needed to have lxd load the right sqlite and dqlite shared libraries.

Your shell has those variables from when you ran `make deps`.

**Comment by cs-tim-buecher** [comment]
Just for adding closing information for anyone facing this issue: @stgraber was totally right. After adding the LD_LIBRARY_PATH to my lxd.service everything worked just fine.
```
[Unit]
Description=LXD Container Hypervisor
Requires=network.service

[Service]
ExecStart=/usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
KillMode=process
TimeoutStopSec=40
KillSignal=SIGPWR
Restart=on-failure
LimitNOFILE=-1
LimitNPROC=-1
Environment=LD_LIBRARY_PATH=/home/testboy/go/deps/sqlite/.libs/:/home/testboy/go/deps/dqlite/.libs/
```
