### ISSUE TITLE
Error: failed to open cluster database: failed to ensure schema: failed to apply update 11: Failed to add project_id column: UNIQUE constraint failed: containers_config.id

### ISSUE THREAD

**Issue by mikesi** [lxc/lxd#5176]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

Name  Version    Rev   Tracking  Publisher   Notes
core  16-2.35.2  5548  stable    canonical✓  core
lxd   3.6        9239  stable    canonical✓  -

After snap refresh to 3.6 i get this:
Error: failed to open cluster database: failed to ensure schema: failed to apply update 11: Failed to add project_id column: UNIQUE constraint failed: containers_config.id

**Comment by freeekanayaka** [comment]
The quickest way for me to debug this issue would be for you to send to me a tarball of your ```/var/snap/lxd/common/lxd/database``` directory. If that's not possible for one reason or another, please pop up on the ```#lxccontainers``` IRC channel on freenode and we'll figure out something. (for the tarbal my mail is free.ekanayaka at canonical dot com)

**Comment by mikesi** [comment]
would be great... my production is dead now, gmail doesnt allow attach..
