### ISSUE TITLE
Slow Image Launch then Failure

### ISSUE THREAD

**Issue by svpn** [lxc/lxd#5180]
Ridiculously slow image download leading to failure from within an EC2 10 Gigabit network.

+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
ubuntu@chaos:~$ lxc launch ubuntu:18.04 test
Creating test
Retrieving image: rootfs: 40% (75.67kB/s)

Followed by:

+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
ubuntu@chaos:~$ lxc launch ubuntu:18.04 test
Creating test
Error: Remote operation canceled by user

What's up with the 1980's network speed and ultimately a failure?

I tested my network and it's fine, LXD currently unusable because of this issue.

**Comment by stgraber** [comment]
Can you try downloading something else from https://cloud-images.ubuntu.com through wget/curl to check?

I suspect it's a bad route or some issue with the cloud-images server rather than something we can do much about on our side.

**Comment by svpn** [comment]
I tried wget from https://cloud-images.ubuntu.com/ a few times, getting a consistent 1.24MB/s from there, haven't had the need to launch from the ubuntu repository again but lxc copy from my other remote LXD servers is fine.

Thanks for the reply, closing it.
