### ISSUE TITLE
Snap package of 3.0.2 causes kernel panic on Centos

### ISSUE THREAD

**Issue by amoe** [lxc/lxd#5196]
# Required information

 * Distribution: CentOS
 * Distribution version: 7

# Issue description

Starting lxd leads to a kernel panic that hangs the system.

# Steps to reproduce

A fresh install of CentOS 7 in a KVM.  Using the [ngompa snap builds](https://copr.fedorainfracloud.org/coprs/ngompa/snapcore-el7/).

Install the snap using the lxd 3.0 stable channel.  `snap install --channel=3.0/stable lxd`.
The system will hang.

This can also be reproduced on non-virtualized hardware that I have.  Just used the VM to ensure a clean environment.

# Information to attach

http://solasistim.net/centos-lxd-hang.png

There isn't any useful information available in the logs.  I can't get to dmesg because of the panic.  I was able to boot in rescue mode and run `lxc info`, the data is shown below.  When I reboot in rescue mode the panic log didn't get recorded to `/var/log/dmesg*`, so I only have the screenshot above to work with.

    config: {}
    api_extensions:
    - storage_zfs_remove_snapshots
    - container_host_shutdown_timeout
    - container_stop_priority
    - container_syscall_filtering
    - auth_pki
    - container_last_used_at
    - etag
    - patch
    - usb_devices
    - https_allowed_credentials
    - image_compression_algorithm
    - directory_manipulation
    - container_cpu_time
    - storage_zfs_use_refquota
    - storage_lvm_mount_options
    - network
    - profile_usedby
    - container_push
    - container_exec_recording
    - certificate_update
    - container_exec_signal_handling
    - gpu_devices
    - container_image_properties
    - migration_progress
    - id_map
    - network_firewall_filtering
    - network_routes
    - storage
    - file_delete
    - file_append
    - network_dhcp_expiry
    - storage_lvm_vg_rename
    - storage_lvm_thinpool_rename
    - network_vlan
    - image_create_aliases
    - container_stateless_copy
    - container_only_migration
    - storage_zfs_clone_copy
    - unix_device_rename
    - storage_lvm_use_thinpool
    - storage_rsync_bwlimit
    - network_vxlan_interface
    - storage_btrfs_mount_options
    - entity_description
    - image_force_refresh
    - storage_lvm_lv_resizing
    - id_map_base
    - file_symlinks
    - container_push_target
    - network_vlan_physical
    - storage_images_delete
    - container_edit_metadata
    - container_snapshot_stateful_migration
    - storage_driver_ceph
    - storage_ceph_user_name
    - resource_limits
    - storage_volatile_initial_source
    - storage_ceph_force_osd_reuse
    - storage_block_filesystem_btrfs
    - resources
    - kernel_limits
    - storage_api_volume_rename
    - macaroon_authentication
    - network_sriov
    - console
    - restrict_devlxd
    - migration_pre_copy
    - infiniband
    - maas_network
    - devlxd_events
    - proxy
    - network_dhcp_gateway
    - file_get_symlink
    - network_leases
    - unix_device_hotplug
    - storage_api_local_volume_handling
    - operation_description
    - clustering
    - event_lifecycle
    - storage_api_remote_volume_handling
    - nvidia_runtime
    - candid_authentication
    - candid_config
    api_status: stable
    api_version: "1.0"
    auth: trusted
    public: false
    auth_methods:
    - tls
    environment:
      addresses: []
      architectures:
      - x86_64
      - i686
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIIFbjCCA1agAwIBAgIRAKJAA1PaqjlNmnXY8v7vxNEwDQYJKoZIhvcNAQELBQAw
        QzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEjMCEGA1UEAwwacm9vdEBs
        b2NhbGhvc3QubG9jYWxkb21haW4wHhcNMTgxMDIyMTEwNTIwWhcNMjgxMDE5MTEw
        NTIwWjBDMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMSMwIQYDVQQDDBpy
        b290QGxvY2FsaG9zdC5sb2NhbGRvbWFpbjCCAiIwDQYJKoZIhvcNAQEBBQADggIP
        ADCCAgoCggIBAL11cYN8xg6WDKDAa+87d6fxbl9VesBtedSkU+3sV2hBvUbLrc1L
        3LpDbjWanrursSIedMUFqnqG8EFgwR53f1S+lvlHQgOGtWuW5Ls8XBY5FMHOXFmX
        Ixs2NbRPGSVmONItz8aEH90V5LM9/vesNGhNO8qKPEvIhqJqHKi0Sb9J2z91MzHp
        F5IxmC+OzN7RN8O90IqEg1p0KbeNdOFDsVDIVLyLtoq2eMA2DsWvRCKE4BV60e0H
        RKBuH9n4LirhsTvBisHsGReuKjAo1vwfvCK/QadwMxTGqDr+b+oIL6qhKaG6pNpQ
        K3boXOPxzkgQxh+AgoOzr1MaV9gRFx1tC6xw9lsxSsvYLr8uDr60nl2F5PNeTNrC
        IB9jvOMI5OeNZx5sYw5QlKlbUFbH0SpG56WFSUh9XfVNXyF3EVRlBhdZKh/lo5nL
        a43Mzi8wN3fvxz7skrHpLS85lF73blvAtgQ/v/WiZfAJju4KHUmWAv6nUuEnVuiu
        8ZsOiEwsEc+WttPmSV9meBHYPWoSfI++G9aTzKOU9dM0CotNe/KwWhKFw+cDMSbQ
        h4nIb1gJemwrT1d+F9D6mgIlj5YzIArqfwdHZPrPjvLLOm3W9FCoXwG6r5SQSXlr
        rfvqskuHSnnp19godaMni9Z5WF+4IQINhUa21vb3HkGfMx88y30kd7vdAgMBAAGj
        XTBbMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMB
        Af8EAjAAMCYGA1UdEQQfMB2CFWxvY2FsaG9zdC5sb2NhbGRvbWFpbocEwKg4ZjAN
        BgkqhkiG9w0BAQsFAAOCAgEAoR9Q8SadeHqNtbNlk+2F59nL1NV3YBD45g8w7/Rz
        AMzAdvInezY+9fzRZztnai+Td1cYhSrCDzMRM4iqowv5rrQYosdaqBzB2z/ZyAhF
        Rr6y55N3hFiRNMbWJ6Ig8jIvGpDnkYVVvwqt0V+tvQooo9YcCMSG82DE/7Lgb3o5
        Fa8n5QhvNw5GK4/rib8wMzNNYVRxwtSmfFDPyX6y6/7w/H17tdr3TQHVpc7bU5O3
        BqCP9Y7SwwM1Z+efCGacqYB7smfB3rPkbQacCAU7EjM77JbDE+BTcJYXPe/G3rXw
        8E+mO4iyCwIptESXmXiR4uy4rAU2ZzzZyv33vDW49i6dQTpcQViphzQkYTOOh7l9
        ig9nVU4X0SCf6Kg8B7e5nLZdFsLARA1QOtP1olPgfbNboxFqan2/KmGUE+r058p9
        +8MR0UkQyCe1+Tzjxdr9FOI3ygxj445vKWxQT3n+ZxEpM6M8Ewnc16ED3k6EXv3e
        MRnn7qZU1TJ1LOtTsNfUBMZurFzNQWXBZSi6a0Lp1ZN1pCJwKBxUDQuRWt2E915h
        EI42u6W6HirojuUQbnMM38vewFra+aiuLYdXuGA7e9Bdm8JK8/IzjrSUB6NRaO8q
        Ol5WezaBna/4m3kS/8Oxn0JkUQr+ulQ83rEfOLIW+7kgkHUhCAMS2ruyXDJh7Eq8
        ddw=
        -----END CERTIFICATE-----
      certificate_fingerprint: 87edb8b1ec4ca980c0cfa8e9628d88c0e9c305ff9c79acf58dc6d25360206e14
      driver: lxc
      driver_version: 3.0.2
      kernel: Linux
      kernel_architecture: x86_64
      kernel_version: 3.10.0-693.el7.x86_64
      server: lxd
      server_pid: 1169
      server_version: 3.0.2
      storage: ""
      storage_version: ""
      server_clustered: false
      server_name: localhost.localdomain

**Comment by stgraber** [comment]
https://discuss.linuxcontainers.org/t/lxd-snap-on-centos-7-causes-kernel-panic/2797 is all I can tell you unfortunately.
