### ISSUE TITLE
unmet dependencies: Can not install LXD

### ISSUE THREAD

**Issue by adityacloud1** [lxc/lxd#5198]
I tried to install LXD from source and details of testbed is:
     Distribution: Ubuntu 16.04.5 LTS
     Kernel-version: 4.15.0-29-generic

After running below command
`sudo apt install acl autoconf dnsmasq-base git golang libacl1-dev libcap-dev liblxc1 liblxc-dev libtool libuv1-dev make pkg-config rsync squashfs-tools tar tcl xz-utils`
I got the following error:
`The following packages have unmet dependencies:
 liblxc-dev : Depends: liblxc1 (= 3.0.1-0ubuntu1~16.04.2) but 2.0.8-0ubuntu1~16.04.2 is to be installed
E: Unable to correct problems, you have held broken packages.
`
Stuck in further implementation please, any help is greatly appreciated

**Comment by stgraber** [comment]
Looks like you have a mix of backported packages and non-backported packages causing this issue.

First run `apt install -t xenial-backports liblxc1 liblxc-dev` to install those packages from backports, then install the rest of them normally with `apt install acl autoconf dnsmasq-base git golang libacl1-dev libcap-dev libtool libuv1-dev make pkg-config rsync squashfs-tools tar tcl xz-utils`

This is because you're on 16.04 which doesn't have liblxc-dev outside of the backports, on 18.04 the command above would work properly.

**Comment by adityacloud1** [comment]
Respected Sir,
LXD is built successfully with two binaries in $GOPATH/bin
I run `sudo -E LD_LIBRARY_PATH=$LD_LIBRARY_PATH $GOPATH/bin/lxd --group sudo`
 it gets stuck with
`WARN[10-24|19:12:58] CGroup memory swap accounting is disabled, swap limits will be ignored. 
`

**Comment by stgraber** [comment]
@adityacloud1 it's not stuck, it's working, that's all it's going to print unless you're passing `--verbose` or `--debug` to make it print more stuff

**Comment by adityacloud1** [comment]
Respected all,
Greeting of the Day !!!. I am trying to live migrate container ‘c1’ between 2 LXD servers, with apparmor security feature disabled and experimental setup is:

Physical machine OS: Ubuntu 16.04
lxc --version 3.0.1 (installed from source using: https://github.com/lxc/lxd)
lxd --version 3.0.1 (installed from source)
criu --version: 3.10 (installed from source)
kernel --version: 4.15.0-29-generic

Container’s snapshot is created successfully with remote LXD server named as ‘adityacloud,’. But when I try to live migrate container ‘c1’ using lxc move command it gives me following error
`
`Error: Failed container creation:

    https://[fd42:b6c9:aaf0:2f4b::1]:8443: Unknown configuration key: image.architecture
    https://172.16.13.120:8443: Unknown configuration key: image.description
    https://10.250.213.1:8443: Unknown configuration key: image.os
    ``
    I will post the required information to troubleshoot this error.

Any help is greatly appreciated.

**Comment by stgraber** [comment]
This suggests you're trying to move your container from a 3.0.x machine over to a 2.0.x machine, that's not going to work, you'd want the target server to be running the same or more recent version of LXD.

**Comment by adityacloud1** [comment]
Respected Sir,
A big thanks for your kind help each time. I will update after performing same LXD implementation using the source code at the target server.

**Comment by adityacloud1** [comment]
Respected sir, @stgraber  as per yours last post target server is also configured with same version of LXD, LXC and CRIU.
I tried to migrate new created container 'c2' to target LXD server named **'adityacloud2'** whose IP  address is**172.16.13.220** and accessible from source using _ping_ cmd.

### Issue: Unable to connect to: 172.16.13.220:8443
![lxd move error](https://user-images.githubusercontent.com/40225508/47603723-c76c6580-da0d-11e8-967e-31008f798c09.png)
I explored solutions like [https://github.com/lxc/lxd/issues/553](url), but not getting the idea for further action. You are requested to guide for this issue.

**Comment by stgraber** [comment]
What does `lxc info adityacloud2:` show?

**Comment by adityacloud1** [comment]
Respected sir,
Greeting of the Day!!!
`lxc info adityacloud2:` shows same erro
`Error: Get https://172.16.13.220:8443/1.0: Unable to connect to: 172.16.13.220:8443
`
![lxc info](https://user-images.githubusercontent.com/40225508/47612255-08f82180-da9d-11e8-9993-a94f86d13523.png)

**Comment by adityacloud1** [comment]
Respected sir,
I will always be grateful to you for your your guidance and useful advice. **_lxc config show_** `
  core.https_address: '[::]:8443'
  core.trust_password: true
` and the problem is solved by disabling _**Apparmor**_ at the remote server.

Furthermore, when I run command to migrate container, in starting seconds data is transferred then it got stuck with `Transferring container: checkpoint-2: 24.53MB (24.53MB/s)  
`.  A screenshot of **_lxd --debug_** is here:
![lxd deubg](https://user-images.githubusercontent.com/40225508/47662236-8ff1ea80-dbc0-11e8-9766-882d2f02f783.png)

**Comment by adityacloud1** [comment]
Problem gets resolved. 
Thanks all for the kind support
