### ISSUE TITLE
lxd-p2c fails on rsync error: protocol incompatibility (code 2) at flist.c(2634) [Receiver=3.1.2]

### ISSUE THREAD

**Issue by johanehnberg** [lxc/lxd#5201]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info":
```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 172.17.0.5:8443
  architectures:
  - x86_64
  - i686
  certificate: |
<snip>
  certificate_fingerprint: <snip>
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-32-generic
  server: lxd
  server_pid: 1651
  server_version: 3.0.1
  storage: zfs
  storage_version: 0.7.5-1ubuntu15
  server_clustered: false
  server_name: bionichost

```
# Issue description
Attempting to create a container from a xenial VM install to a bionic lxd host fails.

# Output:
```
ubuntu@xenialvm:~$ sudo ./lxd-p2c bionichost test / --storage=data
Generating a temporary client certificate. This may take a minute...
Certificate fingerprint: ********************
ok (y/n)? y
Admin password for bionichost: 
Error: Failed to rsync: exit status 2
[Receiver] Invalid dir index: -1 (-101 - -101)
rsync error: protocol incompatibility (code 2) at flist.c(2634) [Receiver=3.1.2]
```
`lxd monitor` shows the same errors

# Steps to reproduce
 1. Install a vm with xenial and update
 2. Install a vm with bionic and update
 3. Install lxd with defaults on bionic vm
 4. Build lxd-p2c on bionic vm `sudo apt install golang-go && go get github.com/lxc/lxd/lxd-p2c` and copy it to xenial vm
 5. Run `sudo ./lxd-p2c bionichost test /` on the xenial vm and observe the output above

# Failed attempts at solving:
- Updating rsync on the xenial vm to 3.1.2 does not help
- Switching from lxd-p2c master (at 3.6) to stable-3.0 (at 3.0.2) does not help

# Workaround:
Build lxd-p2c tagged lxd-3.0.1 instead (i.e. this seems to be a regression or needs to be <= the server release as lxd-3.0.0 also works). To accomplish this, simply do the following after the previous build (the `go get` command above):
```
cd go/src/github.com/lxc/lxd/lxd-p2c/
git checkout lxd-3.0.1
go build
```
and copy the new binary from the current folder to the xenial machine.

**Comment by stgraber** [comment]
Yeah, that's unfortunately the currently expected behavior as LXD prior to 3.0.2 doesn't have a way to negotiate rsync options and most releases of rsync just crash on argument mismatch...

The argument mismatch in your case is the xattr transfer options, newer LXD releases that do have the negotiation code will work fine with whatever source version but newer lxd-p2c will run into the mismatch issue if run against a server which lacks the negotiation code.

Your workaround is perfectly correct, running the lxd-p2c release which matches your target server will always be guaranteed to work and using a more recent version will not actually get you anything useful.

(Closing as we can't really do anything in the new lxd-p2c and have already the new negotiation code in our stable-3.0 branch, we just need to get that release into the various distros which takes time...)

**Comment by johanehnberg** [comment]
Excellent. For future reference, anyone landing here can follow version 3.0.2 going into Ubuntu Bionic Beaver 18.04 LTS here (it is showing up in proposed as of this writing):
https://launchpad.net/ubuntu/+source/lxd
