### ISSUE TITLE
Confusing error when attaching CEPH custom volume on different cluster members

### ISSUE THREAD

**Issue by Spunge** [lxc/lxd#5203]
## Platform information

* Distro: ubuntu 18.04
* [lxc info](https://github.com/lxc/lxd/files/2511822/info.txt)

## Issue description

I unable to attach a custom storage volume on a ceph storage pool to multiple containers that are running on different hosts in a clustered lxd setup. I'm perfectly able to attach the storage volume to multiple containers on the same host in the cluster.

Imagine a container running with a storage volume attached, when i try to attach the storage volume to another container running on another host in the cluster i get the following errors:

When attaching the storage volume to another running container
```Error: Add disk devices: Failed to setup device: no such file or directory```

When starting another container that has the storage volume attached
```Error: Common start logic: no such file or directory```

## Information to attach

* There is no logs about this in the container logs.
* Here's the relevant lines from the daemon log: [lxd_log.txt](https://github.com/lxc/lxd/files/2511884/lxd_log.txt)
* And the output of lxc monitor: [lxc_monitor.txt](https://github.com/lxc/lxd/files/2511857/lxc_monitor.txt)

Please let me know if you need any more information.

**Comment by stgraber** [comment]
The error is bad but it's absolutely normal that it does fail, if it succeeded, your disk would get corrupted.

**Comment by stgraber** [comment]
@freeekanayaka Can you send a small fix to check for this case ahead of time and completely prevent attaching a custom volume to two containers that are on different nodes?

**Comment by Spunge** [comment]
Ah yeah, you are totally right. I think i was expecting the cluster to choose the correct node as i'm passing the disk config on creation of the container. If i understand correctly everything will work fine as long as i pass a target myself?

**Comment by stgraber** [comment]
@Spunge yes, targeting the same node as the other containers would fix that.

We have a plan to add support for cephfs in the near future, using cephfs for custom volumes will effectively avoid that particular problem.

**Comment by Spunge** [comment]
Yeah, i'll keep an eye on that ticket, i'll pass the target for now. Thank you for your help!

**Comment by stgraber** [comment]
Re-opening to keep this to track the error handing, we need a much clearer error here.
