### ISSUE TITLE
LXD 3.6 - Different projects having containers with same name. issue removing one of them

### ISSUE THREAD

**Issue by cyberwillis** [lxc/lxd#5207]
# Required information

 * Distribution: **Ubuntu**
 * Distribution version: **16.04**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.4.0-138-lowlatency**
   * LXC version: **3.0.0**(https://github.com/lxc/lxc/commit/f8f1069a8d7e4a4d3d507a07df591ee9ebeb4737) **built from the source**
   * LXD version: **3.6** (https://github.com/lxc/lxd/commit/975a559f9fdcfc243c6c209e9c7b519d708efaf5) **built from the source**
   * Storage backend in use: **zfs**

# Issue description

Creating a new project , switching to it, and creating a new container on that new project that has the same name of another container in the default project is fine, both can start and stop, but if I remove the container on the new project , when I switch back to the default project and try to start the container that had the same name will thrown a error : 
**Failed to mount ZFS dataset "default/containers/container_name" onto "/var/lib/lxd/storage-pools/default/containers/container_name": no such file or directory**

# Steps to reproduce

1-Create a container on the "default" project, start it, list to see if has a IP, then stop it.
```
lxc launch ubuntu:16.04 c1
sleep 5
lxc ls
sleep 3
lxc stop c1
```
2-Create a new project "experiments", switch to it, add disk and custom network to it
```
lxc project create experiments
lxc project switch experiments
lxc profile device add default root disk path=/ pool=default
lxc profile device add default eth0 nic  name=eth0 nictype=bridged parent=lxdbr0
```
3-Create a new container with the same name as the previous project, start it, list it, stop it, remove it
```
lxc launch ubuntu:16.04 c1
sleep 5
lxc ls
sleep 3
lxc stop c1
lxc rm c1
```
4-Switch back to the default project, try to start the container now. Here it lates too much and wont find anything to start and throw this error: **Error: Common start logic: no such file or directory**
```
lxc project switch default
lxc start c1
```

## Debugger information
At the debugger console I got this information:
**EROR[10-26|02:33:31] Failed to mount ZFS dataset "default/containers/c1" onto "/var/lib/lxd/storage-pools/default/containers/c1": no such file or directory**

Note: Folder (/var/lib/lxd/storage-pools/default/containers/) there is a junkyard of folders from previous containers with the following template name "(**project_name**)_(**container_name**)"

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by freeekanayaka** [comment]
Reproduced with ZFS.
