### ISSUE TITLE
lxd uses sub-optimal rsync settings, sometimes resulting in migration failures

### ISSUE THREAD

**Issue by danielrobbins** [lxc/lxd#5212]
Sometimes when migrating containers using rsync, the migration fails and aborts. After debugging, I found the root cause of this issue in lxc monitor:

`metadata:
  context: {}
  level: eror
  message: |
    Rsync send failed: /var/lib/lxd/containers/f2-us-48g-0x4c-2/: exit status 23: could not make way for new symlink: rootfs/var/lock
    rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
project: ""
timestamp: "2018-10-27T23:22:33.301812292Z"
type: logging
`

It appears that rsync is failing because the rootfs/var/lock directory exists but the rsync is wanting to replace it with a symlink. If this is "OK', it can be done by either passing --force or --delete to rsync. See https://unix.stackexchange.com/questions/230334/rsync-complains-about-symlinks.

When looking at the source container, /var/lock is a symlink to  /run/lock. This is true for all the containers I have migrated but it appears to only cause rsync to fail on specific containers. Maybe it is dependent upon the order that /run and /var are rsync'd over? Not sure. But I think it's fixable.

Best,

Daniel

**Comment by danielrobbins** [comment]
Note that when this does fail, it appears to be consistently reproducible by restarting the migration. It will keep aborting at a certain point.

**Comment by stgraber** [comment]
I'd have to check, but `--delete` is most likely the right fix here, when doing multiple rsync runs of the same thing, you don't want old data to be kept around.

**Comment by danielrobbins** [comment]
What interesting is that when the migrate fails, the target logical volume is destroyed automatically. And then re-created when I try again. So I am not sure if this is due to old data or just some quirk with rsync itself.

**Comment by stgraber** [comment]
Hmm, so that's annoying, we need this negotiated or we'll break transfers from older clients...
