### ISSUE TITLE
lxd corrupts database after large number of containers created

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#522]
ubuntu@maas-1-03:~$ lxc list
error: file is encrypted or is not a database
ubuntu@maas-1-03:~$ file /var/lib/lxd/lxd.db 
/var/lib/lxd/lxd.db: data
ubuntu@maas-1-03:~$ ls -al /var/lib/lxd/lxd.db 
-rw-r--r-- 1 root root 196608 Apr 16 08:52 /var/lib/lxd/lxd.db
ubuntu@maas-1-03:~$ ps aux | grep -c lxd
663

**Comment by stgraber** [comment]
Hmm, sounds more likely to be another thread related race condition or sqlite3 crashing in one of the threads. Do you have any reasonably simple reproducer for that?

**Comment by raharper** [comment]
Unfortunately no;  this was fairly far into a scale run in a cloud.  It's
also 0.6 release so I'll attempt to reproduce on 0.7 now.

**Comment by stgraber** [comment]
@hallyn is that something your big rewrite is likely to have resolved?

**Comment by raharper** [comment]
Updated to the latest, still breaks, this time with lxd dumps:

        /usr/lib/go/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x44f, 0xc208b06000, 0x8000, 0x8000, 0x7f2005cd8000, 0x0, 0x0)
        /usr/lib/go/src/pkg/syscall/zsyscall_linux_amd64.go:838 +0x75
syscall.Read(0x44f, 0xc208b06000, 0x8000, 0x8000, 0x1, 0x0, 0x0)
        /usr/lib/go/src/pkg/syscall/syscall_unix.go:136 +0x5c
os.(*File).read(0xc208aee060, 0xc208b06000, 0x8000, 0x8000, 0x4f7453, 0x0,
0x0)
        /usr/lib/go/src/pkg/os/file_unix.go:190 +0x62
os.(*File).Read(0xc208aee060, 0xc208b06000, 0x8000, 0x8000, 0x8000, 0x0,
0x0)
        /usr/lib/go/src/pkg/os/file.go:95 +0x98
github.com/lxc/lxd/shared.func·004()
<http://github.com/lxc/lxd/shared.func%C2%B7004()>
        /home/rharper/go/src/github.com/lxc/lxd/shared/util.go:220 +0x9f
created by github.com/lxc/lxd/shared.ReaderToChannel
        /home/rharper/go/src/github.com/lxc/lxd/shared/util.go:230 +0xab

goroutine 3626 [syscall]:
syscall.Syscall(0x0, 0x46b, 0xc208b30000, 0x8000, 0x7f20006047d0, 0x0,
0x4f301e)
        /usr/lib/go/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x46b, 0xc208b30000, 0x8000, 0x8000, 0x7f2005cd8000, 0x0, 0x0)
        /usr/lib/go/src/pkg/syscall/zsyscall_linux_amd64.go:838 +0x75
syscall.Read(0x46b, 0xc208b30000, 0x8000, 0x8000, 0x1, 0x0, 0x0)
        /usr/lib/go/src/pkg/syscall/syscall_unix.go:136 +0x5c
os.(*File).read(0xc208aee090, 0xc208b30000, 0x8000, 0x8000, 0x4f7453, 0x0,
0x0)
        /usr/lib/go/src/pkg/os/file_unix.go:190 +0x62
os.(*File).Read(0xc208aee090, 0xc208b30000, 0x8000, 0x8000, 0x8000, 0x0,
0x0)
        /usr/lib/go/src/pkg/os/file.go:95 +0x98
github.com/lxc/lxd/shared.func·004()
<http://github.com/lxc/lxd/shared.func%C2%B7004()>
        /home/rharper/go/src/github.com/lxc/lxd/shared/util.go:220 +0x9f
created by github.com/lxc/lxd/shared.ReaderToChannel
        /home/rharper/go/src/github.com/lxc/lxd/shared/util.go:230 +0xab

rax     0x0
rbx     0x46
rcx     0xffffffffffffffff
rdx     0x6
rdi     0x6f0f
rsi     0x7519
rbp     0x7f1ff37fda50
rsp     0x7f1ff37fd738
r8      0x7f200500d440
r9      0x40bc11
r10     0x8
r11     0x206
r12     0x7f1ff37fd8c8
r13     0x46
r14     0x7f1ff37fd8c8
r15     0x2
rip     0x7f2004ebd267
rflags  0x206
cs      0x33
fs      0x0
gs      0x0

**Comment by tych0** [comment]
Is this the full stack trace?

**Comment by raharper** [comment]
http://people.canonical.com/~rharper/lxd/issues/522/lxd_backtrace.log

**Comment by hallyn** [comment]
This one was due to FD_SET being used with fd > 1024.

This should be solved with current git HEAD of lxc.

**Comment by raharper** [comment]
Still running 0.7, but this time underload with lots of creates and list operations, getting this:

error: database disk image is malformed

**Comment by hallyn** [comment]
Wow.  Could you please open a new issue about that one?  Is that again with a bunch of creates and simultaneous lists, or are you doing something different?

**Comment by raharper** [comment]
nclxd driven vs lxc client.

**Comment by raharper** [comment]
Same stuff (creates and lists) though nclxd exercise slightly different ops (config updates and other queries).  I wedged all 3 compute nodes;  Restarted LXD restored operations, but I ended up in the state where operations  were cleaning up the database, but not actually deleting the running containers (ps -ef showed all of the lxd instances, but lxc list was empty).
