### ISSUE TITLE
Provide a way to determine when a container is actually up and running

### ISSUE THREAD

**Issue by BrunnerLivio** [lxc/lxd#5226]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info":
certificate_fingerprint: 1d35851ee9799622e0199e814e592375ed4be50e7b4d103fe1d65b8e3672cbc5
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-137-generic
  server: lxd
  server_pid: 2616
  server_version: "3.6"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu25

# Issue description

I want a way to determine when a container is actually up and running, therefore a IPV4 is associated with the container

# Steps to reproduce

 When I run the following commands:

```bash
lxc launch lxdhub:lxdhub mylxdhub
lxc info mylxdhub | grep "eth0:.*inet" | head -n1 | awk '{print "$3"}'
```

I expect the IPV4 address of the mylxdhub container. Instead I receive the IPV6 address e.g. `fe80::216:3eff:fe98:d043`. Is there an easy way with the CLI when the container is actually up and running and an IPV4 is associated?

By LXC we had a command called `lxc-wait`. Do you have something similar in LXD?

**Comment by brauner** [comment]
When an IP is assigned has nothing to do with container startup. :) LXC will execute the init and then everthing is up to the container's init process. There might be some devlxd magic that @stgraber can help you out with but I'm not sure. `lxc-wait` would also only tell you when a container was in RUNNING state but not whether an IP was assigned or not.

**Comment by stgraber** [comment]
Yeah, I think it's outside of LXD's scope to try and figure out if a container is done booting or not.
There's no reliable way to know that, waiting for an IPv4 will not work for containers that don't use IPv4 and will still be racy even for those that do as having an IPv4 doesn't mean you have DNS setup or that your services are running.

The same problem is true for virtual machines and the best way to deal with this is by attempting an actual connection from the outside until it succeeds.

If you want to wait for an IPv4, you could likely use `lxc list -c4 --format csv mylxdhub`  which should be quite a bit cleaner and more reliable than what you did above.
