### ISSUE TITLE
Delete ephemeral containers if they are detected on boot?

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#523]
I have the following confusing lxc list output

```
% lxc list
+-------------------+---------+------------+------+-----------+
|       NAME        |  STATE  |    IPV4    | IPV6 | EPHEMERAL |
+-------------------+---------+------------+------+-----------+
| trusty-template   | STOPPED |            |      | NO        |
| test-for-tych0    | STOPPED |            |      | NO        |
| test-0-7          | STOPPED |            |      | NO        |
| test-scripts-07   | STOPPED |            |      | YES       |
| test-scripts-07-2 | STOPPED |            |      | YES       |
| test-scripts-07-3 | STOPPED |            |      | YES       |
| foo               | RUNNING | 10.0.3.166 |      | NO        |
+-------------------+---------+------------+------+-----------+
```

How can a container be both ephemeral and stopped?

**Comment by tych0** [comment]
This bug apparently happened when the container failed to start. Once it fails to start, it can't be deleted either.

**Comment by stgraber** [comment]
Oh, oops. So I think in the failed to start case, having them stay around is probably fine, but delete sure should work. Adding a simple state check in delete should do the trick here.

Another bug I just thought about is the case where we have ephemeral containers running and lxd gets restarted. The watcher goroutines won't be respawned on restart so the ephemeral containers won't be removed.
