### ISSUE TITLE
When aborting zfs move, dataset is left busy

### ISSUE THREAD

**Issue by danielrobbins** [lxc/lxd#5233]
I am using git master although this affects all the versions of lxd I have used.

If you start a migration *from* ZFS to another storage pool or remote system, and then you ^C abort the migration, the ZFS storage pool that is the source is left in a "busy" state until lxd is restarted. Example (temptorsent is in a ZFS storage pool on dreamer):

```
logical /home/drobbins # lxc move dreamer:temptorsent local:
Transferring container: temptorsent: 11.14GB (8.94MB/s)^C
logical /home/drobbins # lxc delete dreamer:temptorsent
Error: Failed to destroy ZFS filesystem: cannot destroy 'storage/containers/temptorsent': dataset is busy

logical /home/drobbins # lxc delete dreamer:temptorsent
Error: Failed to destroy ZFS filesystem: cannot destroy 'storage/containers/temptorsent': dataset is busy
```
This is using ZFS 0.8.0_rc1, though I have seen it with other versions of ZFS too :)

Workaround is to restart the lxd daemon, and then you can use lxc delete successfully.

**Comment by danielrobbins** [comment]
Also note that this appears to affect other storage volumes. For example, the partially-completed migration on logical (stored on LVM thinpool) cannot be deleted:
```
logical /home/drobbins # lxc delete temptorsent
Error: Failed to unmount container path "/var/lib/lxd/storage-pools/default/containers/temptorsent": device or resource busy

```

**Comment by stgraber** [comment]
The `lxc` command line tool is just driving a background REST API, so you killing it isn't going to have the backend server stop the operation. So you effectively detached from getting any progress information but your container was very much still being transferred.

**Comment by stgraber** [comment]
I suspect if you look at `ps fauxww` on the source and/or destination server, you'll see a `zfs send` process running there and you'll also see that background operation in progress in `lxc operation list`.

**Comment by danielrobbins** [comment]
Ah, makes sense. I think it would be good to print a message when ^C'ing a long-running task that the task is still running, and as a bonus maybe add a hint on how to stop it manually if possible. Since it's easy to be duped into thinking of it like a regular Linux command, in which case the behavior is a bit odd.

**Comment by danielrobbins** [comment]
Another good and possibly complementary approach is when the command is executed to immediately print out some text informing the user that the command has been sent to the API, and that it's waiting for it to complete as a convenience, but that it's fine to ^C? Dunno. I think some more verbosity by default would be beneficial. Is there a flag that can be specified to simply tell the API to do something and then return immediately? I am not seeing such an option -- could be useful too. Then you can say something like:
"Container move initiated. Waiting for job completion. Use --async to return immediately after submitting job."
