### ISSUE TITLE
Improve handling of db retries

### ISSUE THREAD

**Issue by smibarber** [lxc/lxd#5234]
Downstream issue: crbug.com/901108

The retry mechanism for db transactions can fail, at least on paths like ImageInsert: https://github.com/lxc/lxd/blob/master/lxd/db/images.go#L799

In our case, dqlite ends up blocking for over 5 (!) seconds due to slow I/O. The INSERT succeeds, but since the dqlite client times out the connection is marked bad and reopened. Then LXD retries with another INSERT, which fails since the original INSERT actually succeeded.

In terms of improvements, I have a few ideas.
- use UPSERT or INSERT OR REPLACE which would allow a retry to succeed
- maybe attempt a rollback before retrying a transaction?
- differentiate between a bad connection (ErrBadConn) and a slow transaction - not sure if this is feasible

**Comment by freeekanayaka** [comment]
@smibarber I believe #5236 should fix your use case, as long as you don't enable clustering in your LXD daemon (which I assume the chromebook doesn't need). Please let me know if that doesn't work.

**Comment by freeekanayaka** [comment]
Since you're using the 3.0.x series, you'll probably need for @stgraber to backport this.

**Comment by smibarber** [comment]
Thanks! We don't use clustering so it sounds like that will work for us. Once that makes it into stable we can drop our very hacky [workaround](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/07b67025af05d61d14acd3927ba08f9e9ac2a683/app-emulation/lxd/files/lxd-3.0.2-dqlite-timeout.patch).

**Comment by stgraber** [comment]
Since chromeos moved to 3.17 and higher, this can get closed i think.
