### ISSUE TITLE
lxd truncates rsync errors on newline?

### ISSUE THREAD

**Issue by danielrobbins** [lxc/lxd#5241]
I am trying to debug an issue related to live migration and am noticing even in debug mode, I am not getting a full rsync error message:

`  message: 'Rsync receive failed: /tmp/lxd_restore_286243175/: exit status 12: '
`

Based on the output, it appears that there may be helpful information from rsync after "exit status 12: " that is being truncated, and possibly appearing on a second or successive line? It would be good to be able to see this for troubleshooting purposes. This message is truncated in lxc monitor as well as lxd.log.

**Comment by stgraber** [comment]
It's not actually truncated, there just isn't anything on stderr for LXD to log.

This error comes from RsyncRecv in rsync.go, the particular log entry is:
```go
logger.Errorf("Rsync receive failed: %s: %s: %s", path, err, string(output))
```

Where `stdout` contains everything that was printed on `stderr`, the log entry above is consistent with rsync exiting with error code 12 without printing anything on stderr.

Note that this is in `RsyncRecv` so the invocation of rsync with `--server` which is usually invisible to rsync users and so would explain why little or anything ever gets logged other than the return code.

The client side rsync (on the source server) is where you may find more details.

Closing issue as there's actually no truncating going on here, the entirety of stderr is capture and returned, it just so happens that it's empty in this case.
