### ISSUE TITLE
Feature request: Detailed network configuration during INIT phase

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#5245]
Copied issue over from: https://github.com/lxc/lxc/issues/2718

Hello there,

I've confirmed myself for number of times to be sure that I'm doing everything right, so I commited my self to post this feature request to possibly propagate a potentinal new feature to be implemented.

Please let me know if there is an interest in this feature to be implemented and also - other users can make this feature request more visible by giving it 👍  - thank you all 👏 

And now there goes what I've already posted on [LXC discuss webapp](https://discuss.linuxcontainers.org/t/detailed-network-configuration-during-init/3139). 

I've spent quite a few hours attempting to properly configure networking of container in "init" phase. (Including googling here and there ... :wink: )
I want to have the configuration as simple as possible, so I do not want to use profiles or configure device after the container is initiated.

I am using lxc & lxd setup on Bionic within OpenStack instance with multiple virtual network interfaces and I want to bind that virtual NICs directly to lxc containers as nictype=physical.
Name of NIC is chosen randomly, therefore, the profile would have to be reconfigured every time.
OpenStack's Neutron gives network configuration upon DHCP request and it is working fine.

Problem is that container initiated by command shown below has correct everything but nictype=macvlan.

> lxc init ubuntu:18.10 c2 --no-profiles --storage default --network ens7

The output of request send to LXD:

```
DBUG[10-31|11:13:39] 
        {
                "architecture": "",
                "devices": {
                        "ens7": {
                                "nictype": "macvlan",
                                "parent": "ens7",
                                "type": "nic"
                        },
                        "root": {
                                "path": "/",
                                "pool": "default",
                                "type": "disk"
                        }
                },
                "ephemeral": false,
                "profiles": [],
                "stateful": false,
                "description": "",
                "name": "c2",
                "source": {
                        "type": "image",
                        "certificate": "",
                        "alias": "18.10",
                        "server": "https://cloud-images.ubuntu.com/releases",
                        "protocol": "simplestreams",
                        "mode": "pull"
                },
                "instance_type": ""
        }
```

I have tried these variants but every single one ended neighter with error or unwanted outcome like nictype still macvlan.

```
lxc init ubuntu:18.10 c2 --no-profiles --storage default --config nictype=physical --network ens7
lxc init ubuntu:18.10 c2 --no-profiles --storage default --config device.nictype=physical --network ens7
lxc init ubuntu:18.10 c2 --no-profiles --storage default --config=nictype=physical --network ens7
lxc init ubuntu:18.10 c2 --no-profiles --storage default --config device.eth0.nictype=physical --network ens7
lxc init ubuntu:18.10 c2 --no-profiles --storage default --config devices.eth0.nictype=physical --network ens7
lxc init ubuntu:18.10 c2 --no-profiles --storage default --config devices.ens7.nictype=physical --network ens7
lxc init ubuntu:18.10 c2 --no-profiles --storage default --config user.network-config.type=physical --network ens7
lxc init ubuntu:18.10 c2 --no-profiles --storage default --config user.network-config.ens7.type=physical --network ens7
lxc init ubuntu:18.10 c2 --no-profiles --storage default --config lxc.net.0.type=physical --network ens7
```

What am I doing wrong or is there no such configuration possibility at all? Therefore I can write an issue on github to request this feature or os ...

Thank you a lot :wink:
 

Environment: :computer:  

```
# lxc --version
3.0.1
# lxd --version
3.0.1
# uname -a
Linux test-lxc1 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by stgraber** [comment]
Because of the way device configuration is structured, it's not very practical for the CLI to let you override this stuff at init time. Instead, it's much easier and fast to just do it as two steps:

```
lxc init ubuntu:18.10 c2 --no-profiles --storage default
lxc config device add c2 eth0 nic nictype=physical parent=ens7 name=eth0
```

**Comment by stgraber** [comment]
The `-n` convenience option will either use `bridged` if the interface that was passed is a bridge or `macvlan` otherwise, we certainly don't want this to ever use physical as that'd be sure to confuse and likely break a good chunk of our users :)

nictype=physical tends to be used for more complex, specialized cases where running multiple commands isn't likely to be an issue or where a custom API client is in use anyway (in which case you can totally do it in a single REST API call).

**Comment by lwqcz** [comment]
@stgraber thank you a lot for your answer. You are 100% correct, these two commands work OK and therefore there is no need for that what I've requested. Thank you.
