### ISSUE TITLE
jenkins: Failed to start the daemon: failed to open cluster database: failed to open database: unable to set WAL mode: disk I/O error (2570) 

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#5250]
```
EROR[11-05|22:41:42] Failed to start the daemon: failed to open cluster database: failed to open database: unable to set WAL mode: �����!: disk I/O error (2570) 
INFO[11-05|22:41:42] Starting shutdown sequence 
INFO[11-05|22:41:42] Stopping REST API handler: 
INFO[11-05|22:41:42]  - closing socket                        socket=/lxc-ci/build/tmp.19vGpSwb7k/go/src/github.com/lxc/lxd/test/tmp.q9K/gwa/unix.socket
INFO[11-05|22:41:42] Stopping /dev/lxd handler: 
INFO[11-05|22:41:42]  - closing socket                        socket=/lxc-ci/build/tmp.19vGpSwb7k/go/src/github.com/lxc/lxd/test/tmp.q9K/gwa/devlxd/sock
INFO[11-05|22:41:42] Saving simplestreams cache 
INFO[11-05|22:41:42] Saved simplestreams cache 
Error: failed to open cluster database: failed to open database: unable to set WAL mode: �����!: disk I/O error (2570)
Error: LXD still not running after 300s timeout (Get http://unix.socket/1.0: dial unix /lxc-ci/build/tmp.19vGpSwb7k/go/src/github.com/lxc/lxd/test/tmp.q9K/gwa/unix.socket: connect: no such file or directory)
```

 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2955/arch=i386,backend=ceph,compiler=golang-tip,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5215/arch=amd64,backend=dir,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5217/arch=amd64,backend=dir,compiler=golang-tip,restrict=lxd-priv/console

**Comment by stgraber** [comment]
https://jenkins.linuxcontainers.org/job/lxd-github-commit/2959/arch=amd64,backend=dir,compiler=golang-1.10,restrict=lxd-priv/console

**Comment by C0rn3j** [comment]
I just ran into this on Arch Linux with LXD from AUR (3.5) after my host repeatedly crashed while files were being written onto a container.

Are my only options waiting for a fix in new LXD or wiping everything?

**Comment by stgraber** [comment]
Try to get to a newer release of LXD, this issue hitting repeatedly is likely due to a overly large log file which LXD 3.7 has logic to handle and shrink.
