### ISSUE TITLE
jenkins: failed to begin transaction: cannot start a transaction within a transaction

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#5251]
```
+ /lxc-ci/build/tmp.kBuyR7O6hB/go/bin/lxc launch --target node1 testimage bar --verbose
Creating bar
WARN[11-05|22:50:36] Failed to get current cluster nodes: cannot commit transaction - SQL statements in progress 
Error: Create container: failed to begin transaction: cannot start a transaction within a transaction
```

 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2955/arch=i386,backend=dir,compiler=golang-tip,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2953/arch=i386,backend=btrfs,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2948/arch=amd64,backend=dir,compiler=golang-1.10,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2953/arch=amd64,backend=dir,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2953/arch=i386,backend=btrfs,compiler=golang-1.10,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2951/arch=i386,backend=btrfs,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2948/arch=i386,backend=lvm,compiler=golang-1.10,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2948/arch=i386,backend=btrfs,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2947/arch=amd64,backend=dir,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2947/arch=amd64,backend=btrfs,compiler=golang-tip,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2947/arch=amd64,backend=lvm,compiler=golang-tip,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5204/arch=amd64,backend=btrfs,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5204/arch=amd64,backend=lvm,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5204/arch=i386,backend=random,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5207/arch=amd64,backend=random,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5210/arch=amd64,backend=zfs,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5210/arch=i386,backend=btrfs,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5212/arch=i386,backend=random,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5215/arch=amd64,backend=lvm,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5223/arch=amd64,backend=dir,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5223/arch=amd64,backend=btrfs,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5225/arch=amd64,backend=zfs,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5225/arch=i386,backend=lvm,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5226/arch=i386,backend=random,compiler=golang-1.11,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5233/arch=i386,backend=dir,compiler=golang-tip,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5233/arch=amd64,backend=ceph,compiler=golang-1.11,restrict=lxd-priv/console

**Comment by freeekanayaka** [comment]
This PR against dqlite should workaround this problem:

https://github.com/CanonicalLtd/dqlite/pull/93

I'm going to merge it, wait for jenkins to rebuild its build cache and then see.

**Comment by stgraber** [comment]
We're still seeing some cases of this:
 - https://jenkins.linuxcontainers.org/job/lxd-github-commit/2961/arch=amd64,backend=dir,compiler=golang-tip,restrict=lxd-priv/console
 - https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5239/arch=amd64,backend=ceph,compiler=golang-1.11,restrict=lxd-priv/consoleFull

**Comment by stgraber** [comment]
https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5242/arch=i386,backend=lvm,compiler=golang-1.11,restrict=lxd-priv/console

**Comment by stgraber** [comment]
tentatively closing this thanks to recent dqlite fix which should have taken care of this
