### ISSUE TITLE
Error: strconv.Atoi: parsing "0\nBlacklisted:\t": invalid syntax

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#5271]
# Required information

 * Distribution:
Ubuntu 
 * Distribution version:
Ubuntu 18.04.1 LTS

 * The output of "lxc info" or if that fails:
   config:
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: | **removed**
  certificate_fingerprint: **removed**
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-38-generic
  server: lxd
  server_pid: 2849
  server_version: 3.0.1
  storage: btrfs
  storage_version: 4.15.1
  server_clustered: false
  server_name: **removed**

# Issue description
Trying to mount a nvidia 1070ti using lxc (installed through snap) and I get the error 

`Error: strconv.Atoi: parsing "0\nBlacklisted:\t": invalid syntax`

I was following the guide in [this guide](https://stgraber.org/2017/03/21/cuda-in-lxd/) and it worked up until actually attaching the device

# Steps to reproduce
1. Install ubuntu
2. Install nvidia drivers (410) + cuda (10.0) 
3. Follow the guide attached in the description

**Comment by stgraber** [comment]
This has been fixed in newer LXD releases. 3.0.2 (currently available in updates) might have the needed fix for this, otherwise 3.0.3 definitely will have.

You could also switch to the LXD snap which would then give you 3.6 (3.7 on Monday) that definitely has the fix too.
