### ISSUE TITLE
lxc export help clarification (3.6)

### ISSUE THREAD

**Issue by TerraTech** [lxc/lxd#5285]
lxd-3.6

In the self help for _lxc export_, it shows it will be exported to a ```.tar.xz```, however the actual exported tarball is ```.tar.gz``` format.

Is there a hidden switch and/or configuration that controls the compressor output engine?

Thanks!

**Comment by stgraber** [comment]
Not really hidden since it's in the documentation, but yes, `backups.compression_algorithm` controls the compression used and does indeed default to gzip.

**Comment by TerraTech** [comment]
Thank you for the clarification and the heads up on the config item.  :)
