### ISSUE TITLE
lxc image import:  cannot read rootfs from some filesystems

### ISSUE THREAD

**Issue by melato** [lxc/lxd#5286]
Client version: 3.7
Server version: 3.7
snap: lxd                   3.7             9550  stable    canonical✓  -

"lxc image import metadata.tar.gz rootfs.tar.gz" cannot read rootfs.tar.gz on some filesystems.
The one-argument version works fine.
I believe this is because lxc/lxd/image.go does not call shared.HostPath on rootfsFile.

Here's how to reproduce:
In a zfs filesystem (that is not / or /home):
```
touch metadata.tar.gz rootfs.tar.gz
lxc image import metadata.tar.gz rootfs.tar.gz

Error: open rootfs.tar.gz: no such file or directory

```
I used empty files for reproducing easily.  At first I ran this with real files.  In any case, the error should not be "no such file or directory", because the file exists.

I repeated this on a subdirectory of /mnt, (/ filesystem):

Error: detectCompression failed, err='EOF', tarfile='/var/snap/lxd/common/lxd/images/lxd_build_000468871/lxd_tar_465355089'

This error was expected, since I did not use actual tar files.

**Comment by melato** [comment]
As already mentioned, I think this is because imageFile and rootfsFile are treated differently in lxd/lxc/image.go.  imageFile is mapped via shared.HostPath().  rootfsFile is not.

**Comment by stgraber** [comment]
Yeah, that sounds right, will send a fix
