### ISSUE TITLE
Snapshots don't appear in lxc list

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#530]
I think we should have the number of snapshots appear in lxc list and also make sure that "lxc list container" lists all the snapshots for "container".

Currently there's no way from the command line tool to see the snapshots.

**Comment by hallyn** [comment]
Note that currently the following works:

Name: u1
Status: STOPPED
Snapshots:
  u1/snap0
  u1/snap1

However I'll update list to show the information.
