### ISSUE TITLE
all block devices of host are visible in /sys/block/

### ISSUE THREAD

**Issue by bit** [lxc/lxd#5306]
* Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0
   * LXC version: 3.0.2
   * LXD version: 3.0.2
   * Storage backend in use: ceph

# Issue description

all block devices, disk, rbd etc of host are visible in /sys/block/
they also show up with tools like lsblk

# Steps to reproduce

 1. setup lxd with ceph backend
 2. start multiple containers
 3. ls /sys/block in one of them and see all rbdX devices

**Comment by stgraber** [comment]
Yeah, /sys isn't namespaced, except for /sys/class/net, so this is expected behavior from the Linux kernel.
