### ISSUE TITLE
Unable to do stateful snapshots

### ISSUE THREAD

**Issue by rowhit** [lxc/lxd#5309]
Error: snapshot dump failed
(00.007478) Error (criu/namespaces.c:408): Can't dump nested net namespace for 67385
(00.007493) Error (criu/namespaces.c:626): Can't make netns id
(00.106487) Error (criu/util.c:714): exited, status=1
(00.189576) Error (criu/util.c:714): exited, status=1
(00.190180) Error (criu/cr-dump.c:1709): Dumping FAILED.

# Required information

 * Distribution: Ubuntu
 * Distribution version: Bionic
 * The output of "lxc info" or if that fails:
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-38-generic
  server: lxd
  server_pid: 39879
  server_version: 3.0.2
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.4
  server_clustered: false

# Issue description
Error: snapshot dump failed
(00.007478) Error (criu/namespaces.c:408): Can't dump nested net namespace for 67385
(00.007493) Error (criu/namespaces.c:626): Can't make netns id
(00.106487) Error (criu/util.c:714): exited, status=1
(00.189576) Error (criu/util.c:714): exited, status=1
(00.190180) Error (criu/cr-dump.c:1709): Dumping FAILED

# Steps to reproduce
```
lxc launch ubuntu:bionic m1
lxc snapshot m1 --stateful
```
# Information to attach
- Log:
lxc ry-criu-test-ub18-20181125 20181126050141.130 WARN     conf - conf.c:lxc_setup_devpts:1620 - Invalid argument - Failed to unmount old devpts instance
lxc 20181126050151.308 ERROR    criu - criu.c:do_dump:1329 - dump failed with 1
lxc 20181126050151.308 ERROR    criu - criu.c:do_dump:1343 - criu output: Will skip in-flight TCP connections

- Config
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20181101)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20181101"
  image.version: "18.04"
  volatile.base_image: 8f9da4cd832ba0235749caa2249c1ecfcee0cee052c4647fb502955fcec70072
  volatile.eth0.hwaddr: 00:16:3e:15:ee:49
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":231072,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":231072,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":231072,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":231072,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

**Comment by stgraber** [comment]
That's a CRIU failure, not a LXD one, closing.

You may find more details in the migration and dump logs present in /var/log/lxd/NAME/

Updating to a newer CRIU may help you, or you may just be trying to dump something from a process which cannot be dumped. Modifying your container to better be dumpable may help, or you may need to talk to CRIU upstream to figure out what's missing.
