### ISSUE TITLE
LXD 3.7 dead and won't start

### ISSUE THREAD

**Issue by garymol** [lxc/lxd#5317]
# Required information

 * Distribution: Centos
 * Distribution version: 7.5
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.18.7-1.el7.elrepo.x86_64
   * LXC version:  3.7        9664 
   * LXD version:  3.7        9664
   * Storage backend in use: zfs

# Issue description

After an automated snap update to 3.7, LXD fails to start.  Containers are still running.  This was noticed when a routine "lxc list" failed. 

# Steps to reproduce
I have 5 LXD based production systems.  All updated to 3.7 but only 1 did so successfully.  Three have running containers without LXD and one seems to have lost all containers. 

# Information to attach
# /var/lib/snapd/snap/bin/lxd --debug
DBUG[11-28|23:34:30] Connecting to a local LXD over a Unix socket
DBUG[11-28|23:34:30] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
INFO[11-28|23:34:30] LXD 3.7 is starting in normal mode       path=/var/snap/lxd/common/lxd
INFO[11-28|23:34:30] Kernel uid/gid map:
INFO[11-28|23:34:30]  - u 0 0 4294967295
INFO[11-28|23:34:30]  - g 0 0 4294967295
INFO[11-28|23:34:30] Configured LXD uid/gid map:
INFO[11-28|23:34:30]  - u 0 1000000 1000000000
INFO[11-28|23:34:30]  - g 0 1000000 1000000000
WARN[11-28|23:34:30] AppArmor support has been disabled because of lack of kernel support
INFO[11-28|23:34:30] Kernel features:
INFO[11-28|23:34:30]  - netnsid-based network retrieval: no
INFO[11-28|23:34:30]  - uevent injection: yes
INFO[11-28|23:34:30]  - unprivileged file capabilities: no
INFO[11-28|23:34:30] Initializing local database
DBUG[11-28|23:34:30] Initializing database gateway
DBUG[11-28|23:34:30] Start database node                      address= id=1
DBUG[11-28|23:34:30] Raft: Restored from snapshot 1-6529-1542258162322
DBUG[11-28|23:34:31] Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}]
DBUG[11-28|23:34:31] Raft: Node at 0 [Leader] entering Leader state
DBUG[11-28|23:34:31] Dqlite: starting event loop
DBUG[11-28|23:34:31] Dqlite: accepting connections
DBUG[11-28|23:34:31] Connecting to a local LXD over a Unix socket
DBUG[11-28|23:34:31] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
DBUG[11-28|23:34:31] Detected stale unix socket, deleting
INFO[11-28|23:34:31] Starting /dev/lxd handler:
INFO[11-28|23:34:31]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[11-28|23:34:31] REST API daemon:
INFO[11-28|23:34:31]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[11-28|23:34:31]  - binding TCP socket                    socket=[::]:8443
INFO[11-28|23:34:31] Initializing global database
DBUG[11-28|23:34:31] Dqlite: handling new connection (fd=20)
DBUG[11-28|23:34:31] Dqlite: connected address=0 attempt=0
INFO[11-28|23:34:31] Updating the LXD global schema. Backup made as "global.bak"
DBUG[11-28|23:34:31] Updating global DB schema from 9 to 10
DBUG[11-28|23:34:31] Updating global DB schema from 10 to 11
DBUG[11-28|23:34:31] Updating global DB schema from 11 to 12
DBUG[11-28|23:34:31] Database error: &errors.errorString{s:"failed to apply update 11: Failed to add project_id column: unable to open database file"}
EROR[11-28|23:34:31] Failed to start the daemon: failed to open cluster database: failed to ensure schema: failed to apply update 11: Failed to add project_id column: unable to open database file
INFO[11-28|23:34:31] Starting shutdown sequence
INFO[11-28|23:34:31] Stopping REST API handler:
INFO[11-28|23:34:31]  - closing socket                        socket=[::]:8443
INFO[11-28|23:34:31]  - closing socket                        socket=/var/snap/lxd/common/lxd/unix.socket
INFO[11-28|23:34:31] Stopping /dev/lxd handler:
INFO[11-28|23:34:31]  - closing socket                        socket=/var/snap/lxd/common/lxd/devlxd/sock
DBUG[11-28|23:34:31] Stop database gateway
DBUG[11-28|23:34:31] Stop raft instance
DBUG[11-28|23:34:31] Dqlite: stopping event loop
EROR[11-28|23:34:31] Dqlite: aborting (fd=20 state=header msg=(null))
DBUG[11-28|23:34:31] Dqlite: event loop stopped
DBUG[11-28|23:34:31] Not unmounting temporary filesystems (containers are still running)
INFO[11-28|23:34:31] Saving simplestreams cache
INFO[11-28|23:34:31] Saved simplestreams cache
Error: failed to open cluster database: failed to ensure schema: failed to apply update 11: Failed to add project_id column: unable to open database file

Any help would be appreciated.  These are production systems and I believe I already lost the containers on one.  I'd like to reduce the damage by trying to restore the other three servers.

**Comment by stgraber** [comment]
The log above suggests you're updating from LXD 3.4 to 3.7, is that what you're doing here or is there something else going on that would have caused your database to go back to that older version?

**Comment by garymol** [comment]
That is possible.  We were running 3.4 for sometime.

**Comment by stgraber** [comment]
Ok, so I suspect it's the database hitting some kind of timeout when processing so many schema updates in a row. We've seen some cases of this here and there and have made changes that should have prevented this issue, but clearly there's still something going on.

On one of the affected systems, please do (as root):
 - systemctl stop snap.lxd.daemon snap.lxd.daemon.unix.socket &
 - pkill -9 -f lxd.*logf
 - lxd --debug --group lxd

And post the output here.

**Comment by garymol** [comment]
# lxd --debug --group lxd
INFO[11-28|23:50:55] LXD 3.7 is starting in normal mode       path=/var/snap/lxd/common/lxd
INFO[11-28|23:50:55] Kernel uid/gid map:
INFO[11-28|23:50:55]  - u 0 0 4294967295
INFO[11-28|23:50:55]  - g 0 0 4294967295
INFO[11-28|23:50:55] Configured LXD uid/gid map:
INFO[11-28|23:50:55]  - u 0 1000000 1000000000
INFO[11-28|23:50:55]  - g 0 1000000 1000000000
WARN[11-28|23:50:55] AppArmor support has been disabled because of lack of kernel support
INFO[11-28|23:50:55] Kernel features:
INFO[11-28|23:50:55]  - netnsid-based network retrieval: no
INFO[11-28|23:50:55]  - uevent injection: yes
INFO[11-28|23:50:55]  - unprivileged file capabilities: no
INFO[11-28|23:50:55] Initializing local database
DBUG[11-28|23:50:55] Initializing database gateway
DBUG[11-28|23:50:55] Start database node                      id=1 address=
DBUG[11-28|23:50:55] Raft: Restored from snapshot 1-6529-1542258162322
DBUG[11-28|23:50:55] Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}]
DBUG[11-28|23:50:55] Raft: Node at 0 [Leader] entering Leader state
DBUG[11-28|23:50:55] Dqlite: starting event loop
DBUG[11-28|23:50:55] Dqlite: accepting connections
INFO[11-28|23:50:55] Starting /dev/lxd handler:
INFO[11-28|23:50:55]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[11-28|23:50:55] REST API daemon:
INFO[11-28|23:50:55]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[11-28|23:50:55]  - binding TCP socket                    socket=[::]:8443
INFO[11-28|23:50:55] Initializing global database
DBUG[11-28|23:50:55] Dqlite: handling new connection (fd=20)
DBUG[11-28|23:50:55] Dqlite: connected address=0 attempt=0
INFO[11-28|23:50:55] Updating the LXD global schema. Backup made as "global.bak"
DBUG[11-28|23:50:55] Updating global DB schema from 9 to 10
DBUG[11-28|23:50:55] Updating global DB schema from 10 to 11
DBUG[11-28|23:50:55] Updating global DB schema from 11 to 12
DBUG[11-28|23:50:55] Database error: &errors.errorString{s:"failed to apply update 11: Failed to add project_id column: unable to open d                                            atabase file"}
EROR[11-28|23:50:55] Failed to start the daemon: failed to open cluster database: failed to ensure schema: failed to apply update 11: Fa                                            iled to add project_id column: unable to open database file
INFO[11-28|23:50:55] Starting shutdown sequence
INFO[11-28|23:50:55] Stopping REST API handler:
INFO[11-28|23:50:55]  - closing socket                        socket=[::]:8443
INFO[11-28|23:50:55]  - closing socket                        socket=/var/snap/lxd/common/lxd/unix.socket
INFO[11-28|23:50:55] Stopping /dev/lxd handler:
INFO[11-28|23:50:55]  - closing socket                        socket=/var/snap/lxd/common/lxd/devlxd/sock
DBUG[11-28|23:50:55] Stop database gateway
DBUG[11-28|23:50:55] Stop raft instance
DBUG[11-28|23:50:55] Dqlite: stopping event loop
EROR[11-28|23:50:55] Dqlite: aborting (fd=20 state=header msg=(null))
DBUG[11-28|23:50:55] Dqlite: event loop stopped
DBUG[11-28|23:50:55] Not unmounting temporary filesystems (containers are still running)
INFO[11-28|23:50:55] Saving simplestreams cache
INFO[11-28|23:50:55] Saved simplestreams cache
Error: failed to open cluster database: failed to ensure schema: failed to apply update 11: Failed to add project_id column: unable to open database file

**Comment by stgraber** [comment]
Well, that's not helping very much and it also excludes the idea that this is timeout related since the whole thing happens in a second...

Can you make a tarball of `/var/snap/lxd/common/lxd/database` and send that to stgraber@ubuntu.com?

That should let me replicate the issue here and track down what's going on with this update, hopefully I can then send you a patched up database until the fix for whatever's going on hits the snap.

**Comment by garymol** [comment]
Certainly. Thank you.

**Comment by stgraber** [comment]
So the issue here appeared to be unrelated to LXD but instead be something very odd going on with the snap's mount namespace apparently showing different mounts than the host, leading to those confusing errors above showing a database update on a system which should have otherwise been up to date.

The short version of the "fix" was to force snapd to create a new namespace with:

  - umount -l /var/snap/lxd/common/ns/shmounts
  - umount -l /var/snap/lxd/common/ns
  - umount -l /run/snapd/ns/lxd.mnt
  - rm /run/snapd/ns/lxd.mnt

I suspect this is something funny going on with this particular mix of recent kernel on Centos 7 with snapd as we'd otherwise have seen many more reports of this, but if someone else runs into this, it'd be useful to get the output of:

 - nsenter --mount=/run/snapd/ns/lxd.mnt cat /proc/self/mountinfo
 - cat /proc/self/mountinfo

Prior to running the commands above. This may show us exactly what happened to that namespace.
