### ISSUE TITLE
delete does not always work

### ISSUE THREAD

**Issue by hallyn** [lxc/lxd#532]
This may be a lxc issue, just filing it here for my own sake.

When running the concurrency test, several containers tend to not have their directories fully deleted.   The actual DELETE call does succeed, and the rootfs is deleted, but the log file sticks around.

**Comment by tych0** [comment]
I'm confused, everything gets deleted but the log file (in `/var/log/lxd/<name>/lxc.log`)? Shouldn't that be ok?

**Comment by stgraber** [comment]
Keeping the entry under /var/log/lxd would indeed be fine (and in fact expected), so long as lxd will wipe the directory clean next time it creates a container of the same name (to avoid mixed logs causing confusion).

My reading of the bug report from Serge was that he had cruft left in /var/lib/lxd/lxc/\<name\> though there really shouldn't be a log file in there to begin with...

**Comment by tych0** [comment]
I wonder if this has to do with the logging patches. Once we reverted to the old style logging, the info wouldn't all go to the same place (? that's my understanding at least), so maybe that's why we ended up with the additional log?

**Comment by hallyn** [comment]
No, I'm using a patch to lxd which puts all container log info into $container_dir/log.
