### ISSUE TITLE
Building lxd-p2c for i386 fails

### ISSUE THREAD

**Issue by danboid** [lxc/lxd#5327]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 amd64
 * go 1.10.4
 * LXD git current as of date

# Issue description

I am trying to containerise an i386 install of 14.04 under 16.04 amd64 (that is possible, right?) hence I need to cross-compile an i386 binary of lxd-p2c but I get the following errors:
```
$ env GOOS=linux GOARCH=386 go get github.com/lxc/lxd/lxd-p2c 
# github.com/lxc/lxd/lxc/utils
../go/src/github.com/lxc/lxd/lxc/utils/progress.go:28:19: undefined: termios.GetSize
../go/src/github.com/lxc/lxd/lxc/utils/progress.go:108:7: undefined: termios.IsTerminal
```
I can successfully build lxd-p2c for linux/amd64 on the same machine.

**Comment by stgraber** [comment]
That's because your cross compiling in a way that turns off cgo support.
lxd-p2c builds perfectly well on i386 directly.

**Comment by danboid** [comment]
The above command now works to cross compile for i386
