### ISSUE TITLE
LXD live migration and proxy device

### ISSUE THREAD

**Issue by asolari** [lxc/lxd#5333]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: Ubuntu 18.04.1 LTS
 # lxc info
config:
  core.https_address: 172.31.14.103:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 172.31.14.103:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICFDCCAZmgAwIBAgIRAMBNph+QQEd23+fv7Xd+7ZIwCgYIKoZIzj0EAwMwPzEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEfMB0GA1UEAwwWcm9vdEBhd3Ns
    eGQtMDAxLmdhZy5pdDAeFw0xODExMjIxNzE1MTZaFw0yODExMTkxNzE1MTZaMD8x
    HDAaBgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxHzAdBgNVBAMMFnJvb3RAYXdz
    bHhkLTAwMS5nYWcuaXQwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQtW8ZBB2rx3Wnb
    UO9ML6rv0SC37oIyO0lQBPrgO+L8OPSDOFhK4EcBL78ZPTWo36gJEr37TyHiGUAV
    tDI5qoVMZuDDZPT/eFcf9gmGqqpqeD7Y9/dQQ0JWBEdYkCB5bnGjWTBXMA4GA1Ud
    DwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMCIG
    A1UdEQQbMBmCEWF3c2x4ZC0wMDEuZ2FnLml0hwSsHw5nMAoGCCqGSM49BAMDA2kA
    MGYCMQCeQgr1wjEvScdvB04dfKydNjCqSSMbdbaMF5vtPWz3OoWe1K3YJnBtHrdU
    sjAUL/sCMQDXjdvv35Ps0eNpIgnvEAdOtSM5cQZrFOXmV4lea9/7cWP1vp3LzZjW
    7IO/kiCJ02w=
    -----END CERTIFICATE-----
  certificate_fingerprint: 3dbd0fc4dd779287fe3dfc80359eeb9446f32952272ddba96dc6ac68359651ef
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-1029-aws
  server: lxd
  server_pid: 2296
  server_version: "3.7"
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.4
  server_clustered: false
  server_name: awslxd-001.gag.it
  project: default

# Issue description

I’m testing live migration of containers between 2 LXD hosts (LXD 3.7).

Both the LXD hosts are configured to use the same internal network (10.10.0.1/24) for the containers, so that each container, after a live migration, will keep the previous IP address.
So far, everything is working as expected.

The port 80 inside the container is exposed to the internet by LXD, through the proxy feature:

   `lxc config device add <container> proxy8081 proxy listen=tcp:0.0.0.0:8081 connect=tcp:<container_ip>:80`
This also works:  I can see the website in the container at the address: http://<lxd_node>:8081

The problem arises when I live migrate the container from a LXD host to the other one.
The migration process completes without errors: the container is moved to the new host, it keeps the IP address and can communicate with the network.
Also the proxy device configuration is synced to the new host, but it doesn't work.
A simple stop/start of the container seems to fix the issue and activate the proxy device.

# Steps to reproduce

 1. Step one
 
 Container running on host 1, nothing ho host 2:
 
root@awslxd-001:~# lxc list
 +---------+---------+--------------------+------+------------+-----------+
 |  NAME   |  STATE  |        IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
 +---------+---------+--------------------+------+------------+-----------+
 | alp37   | RUNNING | 10.10.0.100 (eth0) |      | PERSISTENT |           |
 +---------+---------+--------------------+------+------------+-----------+

 root@awslxd-001:~# lxc config device show alp37 
 proxy8081:
   connect: tcp:10.10.0.100:80
   listen: tcp:0.0.0.0:8081
   type: proxy

 root@awslxd-002:~# lxc list                           
 +------+-------+------+------+------+-----------+
 | NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
 +------+-------+------+------+------+-----------+ 

 
 Website into the container is visible through the proxy device fron the same host and from outside:
 
 root@awslxd-001:~# curl -I http://localhost:8081
 HTTP/1.1 200 OK
 Server: nginx
 Date: Wed, 05 Dec 2018 10:14:35 GMT
 Content-Type: text/html
 Content-Length: 15
 Last-Modified: Tue, 04 Dec 2018 14:32:28 GMT
 Connection: keep-alive
 ETag: "5c068ffc-f"
 Accept-Ranges: bytes

 
 2. Step two
 
 Live migration to the second host:
 
 root@awslxd-001:~# lxc move alp37 awslxd-002:
 
 root@awslxd-001:~# lxc list
 +---------+---------+--------------------+------+------------+-----------+
 |  NAME   |  STATE  |        IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
 +---------+---------+--------------------+------+------------+-----------+
 
 root@awslxd-002:~# lxc list
 +-------+---------+--------------------+------+------------+-----------+
 | NAME  |  STATE  |        IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
 +-------+---------+--------------------+------+------------+-----------+
 | alp37 | RUNNING | 10.10.0.100 (eth0) |      | PERSISTENT |           |
 +-------+---------+--------------------+------+------------+-----------+

Proxy configuration is synced:

 root@awslxd-002:~# lxc config device show alp37 
 proxy8081:
   connect: tcp:10.10.0.100:80
   listen: tcp:0.0.0.0:8081
   type: proxy

 Website into the container is not visible through the proxy device:

 root@awslxd-002:~# curl -I http://localhost:8081
 curl: (7) Failed to connect to localhost port 8081: Connection refused

 3. Step three
  
 Restart of the container fixed the proxy:
 
 root@awslxd-002:~# lxc stop alp37

 root@awslxd-002:~# lxc start alp37

 root@awslxd-002:~# curl -I http://localhost:8081
 HTTP/1.1 200 OK
 Server: nginx
 Date: Wed, 05 Dec 2018 10:21:35 GMT
 Content-Type: text/html
 Content-Length: 15
 Last-Modified: Tue, 04 Dec 2018 14:32:28 GMT
 Connection: keep-alive
 ETag: "5c068ffc-f"
 Accept-Ranges: bytes

# Information to attach

 - [X] Container log (`lxc info NAME --show-log`)
 
 After the restart. Nothing before.
 
 root@awslxd-002:~# lxc info alp37 --show-log 
 [...]
 lxc alp37 20181205102453.480 WARN     conf - conf.c:lxc_map_ids:2917 - newuidmap binary is missing
 lxc alp37 20181205102453.480 WARN     conf - conf.c:lxc_map_ids:2923 - newgidmap binary is missing
 lxc alp37 20181205102453.485 WARN     conf - conf.c:lxc_map_ids:2917 - newuidmap binary is missing
 lxc alp37 20181205102453.485 WARN     conf - conf.c:lxc_map_ids:2923 - newgidmap binary is missing
 lxc alp37 20181205102453.544 WARN     conf - conf.c:lxc_setup_devpts:1616 - Invalid argument - Failed to unmount old devpts instance

 - [X] Container configuration (`lxc config show NAME --expanded`)
 
 architecture: x86_64
 config:
   image.architecture: amd64
   image.description: Alpine 3.7 amd64 (20181127_13:00)
   image.os: Alpine
   image.release: "3.7"
   image.serial: "20181127_13:00"
   volatile.base_image: e55323d2fe4e9fe3adacbfbd9fb0bf3162f1f28f4fd10899bdaf9e74ed412130
   volatile.eth0.hwaddr: 00:16:3e:f9:44:ce
   volatile.idmap.base: "0"
   volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
   volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
   volatile.last_state.power: RUNNING
 devices:
   eth0:
     name: eth0
     nictype: bridged
     parent: lxdbr0
     type: nic
   proxy8081:
     connect: tcp:10.10.0.100:80
     listen: tcp:0.0.0.0:8081
     type: proxy
   root:
     path: /
     pool: lxd
     type: disk
 ephemeral: false
 profiles:
 - default
 stateful: false
 description: ""

 - [X] Main daemon log (/var/snap/lxd/common/lxd/logs/lxd.log)
 
 t=2018-12-05T11:23:50+0100 lvl=info msg="Creating container" ephemeral=false name=alp37 project=default
 t=2018-12-05T11:23:50+0100 lvl=info msg="Created container" ephemeral=false name=alp37 project=default
 t=2018-12-05T11:23:50+0100 lvl=warn msg="Unable to update backup.yaml at this time" name=alp37 rootfs=/var/snap/lxd/common/lxd/containers/alp37/rootfs
 t=2018-12-05T11:23:50+0100 lvl=warn msg="Unable to update backup.yaml at this time" name=alp37 rootfs=/var/snap/lxd/common/lxd/containers/alp37/rootfs
 t=2018-12-05T11:23:56+0100 lvl=info msg="Migrating container" actionscript=false created=2018-12-05T11:23:50+0100 ephemeral=false features=0 name=alp37 predumpdir= project=default statedir=/tmp/lxd_restore_117542902 stop=false used=1970-01-01T01:00:00+0100
 t=2018-12-05T11:23:56+0100 lvl=info msg="Migrated container" actionscript=false created=2018-12-05T11:23:50+0100 ephemeral=false features=0 name=alp37 predumpdir= project=default statedir=/tmp/lxd_restore_117542902 stop=false used=1970-01-01T01:00:00+0100
 t=2018-12-05T11:24:47+0100 lvl=info msg="Shutting down container" action=shutdown created=2018-12-05T11:23:50+0100 ephemeral=false name=alp37 project=default timeout=-1s used=2018-12-05T11:23:56+0100
 t=2018-12-05T11:24:50+0100 lvl=info msg="Shut down container" action=shutdown created=2018-12-05T11:23:50+0100 ephemeral=false name=alp37 project=default timeout=-1s used=2018-12-05T11:23:56+0100
 t=2018-12-05T11:24:53+0100 lvl=warn msg="Unable to update backup.yaml at this time" name=alp37 rootfs=/var/snap/lxd/common/lxd/containers/alp37/rootfs
 t=2018-12-05T11:24:53+0100 lvl=info msg="Starting container" action=start created=2018-12-05T11:23:50+0100 ephemeral=false name=alp37 project=default stateful=false used=2018-12-05T11:23:56+0100
 t=2018-12-05T11:24:53+0100 lvl=info msg="Started container" action=start created=2018-12-05T11:23:50+0100 ephemeral=false name=alp37 project=default stateful=false used=2018-12-05T11:23:56+0100

**Comment by stgraber** [comment]
Reproduced the issue, we've definitely got missing logic for proxy device handling... it doesn't get killed on source and never respawned on target.
