### ISSUE TITLE
Error: Failed to configure cluster: The server is missing the required "clustering_join" API extension

### ISSUE THREAD

**Issue by giosakti** [lxc/lxd#5338]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.1 LTS
 * The output of "lxc info"
```
config:
  core.https_address: <***>
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - <***>
  architectures:
  - x86_64
  - i686
  certificate: <***>
  certificate_fingerprint: <***>
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-1025-gcp
  server: lxd
  server_pid: 6685
  server_version: 3.0.3
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.4
  server_clustered: false
  server_name: <***>
  project: ""
```

# Issue description

I'm attempting to join a node to an existing cluster, and encountering this error message. 

`Error: Failed to configure cluster: The server is missing the required "clustering_join" API extension`

I just realized that all of our existing nodes are auto-upgraded to 3.0.3, I never did upgrade explicitly.

# Steps to reproduce

 1. Create preseed like this:

```
config:
  core.https_address: <***>
  core.trust_password: <***>
networks:
- name: fan-172
  type: bridge
  managed: true
  config:
    bridge.mode: fan
    bridge.mtu: "1400"
    fan.underlay_subnet: <***>
    fan.overlay_subnet: <***>
storage_pools:
- config:
    source: /dev/sdb
  name: local
  driver: zfs
cluster:
  enabled: true
  server_name: <***>
  cluster_address: <***>
  cluster_certificate: <***>
  cluster_password: <***>
  member_config:
  - entity: storage-pool
    name: local
    key: source
    value: /dev/sdb
```

2. do this

```
cat /etc/default/lxd_preseed.yml | sudo lxd init --preseed
```

3. `Error: Failed to configure cluster: The server is missing the required "clustering_join" API extension`

**Comment by giosakti** [comment]
default ubuntu lxd installation is already removed from all of the nodes, we install only using snap

**Comment by freeekanayaka** [comment]
From what you report it sounds like the node you are trying to add has a LXD version greater than the ones in the cluster. Are you sure all nodes in the cluster have the same LXD version *and* the node you want to add has that version too?

**Comment by giosakti** [comment]
@freeekanayaka yeah, both has 3.0.3 but the leader was bootstrapped sometimes ago in `3.0.1` then upgraded along the way.

one of the weird thing is that if we take a look at `api_extensions` returned when doing `lxc info` on both the leader and the joining node, there are no `clustering_join` extension exist.

If I query the global DB and do `SELECT * FROM nodes` every nodes has schema `7` and api_extensions `85`

**Comment by freeekanayaka** [comment]
Okay, I see. So looking closer I believe I understand the problem: the preseed YAML configuration you are using has the new ```member_config``` key which is only supported in later versions of LXD (the 3.x series), but not in 3.0.x.

I assume that you prepared your preseed YAML by looking at the documentation for the 3.x series, but you'll need instead to change it to match the format supported by the 3.0.x series. Please see [here](https://github.com/lxc/lxd/blob/stable-3.0/doc/clustering.md). After changing the preseed YAML, you should be able to join the new node.

**Comment by giosakti** [comment]
Thanks, it's working now.. you're correct I have a wrong preseed that contains `member_config`
