### ISSUE TITLE
storage volume copy does not work for zfs backend

### ISSUE THREAD

**Issue by melato** [lxc/lxd#5339]
Client version: 3.7
Server version: 3.7
snap:  lxd                   3.7             9664  stable    canonical

I have repeatedly tried to copy a zfs storage volume, with no success:

Here's one way to demonstrate the problem, assuming "default" is a storage pool with zfs backend:

> lxc storage volume create default x1
> lxc storage volume copy default/x1 default/x2 --volume-only
> lxc storage volume list default | grep custom
> 
Result:  There is custom x1, but no custom x2
zfs does not list an x2 dataset:  zfs list -rt filesystem {default-pool-dataset}/custom

**Comment by kim0** [comment]
Thanks @brauner and @stgraber .. I thought I was getting lucky and this was fixed a day before I needed it :) However, I'm still hitting the errors below, which I'm guessing is the same as this bug? (Yes, I'm on zfs)

```
$ lxc storage volume copy s/data-6d8a1e8771ad200e1d616b238125830db412fc86 s/foo
Error: exit status 1
kim0@docker01:~$ lxc storage volume list s
+-----------+------------------------------------------------------------------+-------------+---------+
|   TYPE    |                               NAME                               | DESCRIPTION | USED BY |
+-----------+------------------------------------------------------------------+-------------+---------+
| container | container-6d8a1e8771ad200e1d616b238125830db412fc86               |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
| custom    | data-6d8a1e8771ad200e1d616b238125830db412fc86                    |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
| image     | 84a71299044bc3c3563396bef153c0da83d494f6bf3d38fecc55d776b1e19bf9 |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
kim0@docker01:~$
kim0@docker01:~$ lxc storage volume copy s/data-6d8a1e8771ad200e1d616b238125830db412fc86 s/foo
Error: exit status 1
```

**Comment by kim0** [comment]
Forgot to mention I'm using the nightly snap .. so snap info shows the below:
```
snap-id:      J60k4JY0HppjwOjW8dZdYc8obXKxujRu
tracking:     edge
refresh-date: yesterday at 18:26 EET
channels:
  stable:        3.7         (9664) 53MB -
  candidate:     3.7         (9742) 54MB -
  beta:          ↑
  edge:          git-5507ca0 (9750) 54MB - <
  3.0/stable:    3.0.3       (9663) 53MB -
  3.0/candidate: 3.0.3       (9663) 53MB -
  3.0/beta:      ↑
  3.0/edge:      git-18c9b88 (9673) 53MB -
  2.0/stable:    2.0.11      (8023) 28MB -
  2.0/candidate: 2.0.11      (8023) 28MB -
  2.0/beta:      ↑
  2.0/edge:      git-c7c4cc8 (9257) 26MB -
installed:       git-5507ca0 (9750) 54MB -
```

**Comment by stgraber** [comment]
I can't reproduce your issue here using the same snap version:
```
root@nuturo:~# lxc storage volume create default data-6d8a1e8771ad200e1d616b238125830db412fc86
Storage volume data-6d8a1e8771ad200e1d616b238125830db412fc86 created
root@nuturo:~# lxc storage volume copy default/data-6d8a1e8771ad200e1d616b238125830db412fc86 default/foo
Storage volume copied successfully!
```

Can you try running `lxc monitor` while doing that operation again?

Also, is that volume currently attached to any running container?

**Comment by kim0** [comment]
Thanks .. Here's lxc monitor output
https://paste.ubuntu.com/p/vvzXJVGjbW/

Yeah, the volume is attached and I was hoping it would work like that!

**Comment by melato** [comment]
Did you try making a volume snapshot and copying the snapshot?

**Comment by stgraber** [comment]
@kim0 nothing really helpful in that log unfortunately. I've also confirmed that I can copy a volume that's currently attached to a container without a problem here...

Can you reproduce the issue with a new storage volume?

 - lxc storage volume create s blah
 - lxc storage volume copy s/blah s/blah1

If not, then try the same but after attaching it to a container, see if that causes the issue to appear.

If still not, then we'll have to check exactly what's going on with your particular volume.

**Comment by kim0** [comment]
Thanks @stgraber .. mm weird, I could copy the volume in both cases (with/without attaching to container) see below. How can we debug what's wrong with that particular volume ? Does lxd shell-out and run "zfs" commands that we can see?

```
kim0@docker01:~$ lxc storage volume create s blah
Storage volume blah created
kim0@docker01:~$ lxc storage volume copy s/blah s/blah1
Storage volume copied successfully!
kim0@docker01:~$
kim0@docker01:~$ lxc storage volume attach s blah container-6d8a1e8771ad200e1d616b238125830db412fc86 /blah
kim0@docker01:~$ lxc storage volume copy s/blah s/blah2
Storage volume copied successfully!
```

**Comment by kim0** [comment]
HYG .. I remember I have a cronjob that snapshots the whole zpool every few minutes. I hope that does not interfere with lxd! Here are the files requested

https://transfer.sh/mgTH7/zfs_list_all.txt
https://transfer.sh/2zZsM/find_mount.txt
https://transfer.sh/KKa82/lxc_storage_volume_list.txt
https://transfer.sh/tzGPc/mountinfo

**Comment by stgraber** [comment]
The auto-snapshots seem like a good potential candidate for problems here :)
Can you try manually creating such snapshots on the test storage volume you create earlier and see if that reproduces the breakage?

**Comment by kim0** [comment]
mm .. the blah one we created earlier picked up a few snaps, but it was copied .. so not that one it seems

```
$ zfs list -r -t all zdocker/lxd/custom/blah
NAME                                                                USED  AVAIL  REFER  MOUNTPOINT
zdocker/lxd/custom/blah                                             152K  93.4G    96K  /var/snap/lxd/common/lxd/storage-pools/s/custom/blah
zdocker/lxd/custom/blah@copy-ae67bb86-11f9-41b4-a9fa-e60b1621ce07     0B      -    96K  -
zdocker/lxd/custom/blah@2018-12-11_17.10.02--1m                       0B      -    96K  -
zdocker/lxd/custom/blah@2018-12-11_18.10.02--1m                       0B      -    96K  -
zdocker/lxd/custom/blah@2018-12-11_19.10.04--1m                       0B      -    96K  -
kim0@docker01:~$
kim0@docker01:~$ lxc storage volume copy s/blah s/blah2wsnapshot1
Storage volume copied successfully!
```

**Comment by stgraber** [comment]
Ah, the mountinfo shows a potential reason for the error, but I'll have to try to reproduce it here, it's some weird mntns issue related to core snap updates that's leading to some mounts being missing in some namespaces...

**Comment by stgraber** [comment]
@kim0 can you file a new issue for this as we're clearly abusing this one by now? :)

**Comment by kim0** [comment]
Thanks .. Filed https://github.com/lxc/lxd/issues/5348
