### ISSUE TITLE
How to resize lxc/lxd images, if i am using LVM backend?

### ISSUE THREAD

**Issue by Piduna** [lxc/lxd#5352]
I am using LXD few years and i am glad to use this platform in my testing environment. But few days ago, i couldn't install Microsoft Sql server 2017. The reason was, that i used default ZFS backend. Ok, i checked, that if i need ext4. i have to use LVM. No problem, i created "Volume Group" and i marked to use this group in LXD. But ... First problem, that i saw, that LXD creates logical volumes not more, than 10GB.

After this command,

`lxc init ubuntu:16.04 container2`

i received this volume:
``` 
Disk /dev/mapper/mainVG-containers_container2: 10 GiB, 10737418240 bytes, 20971520 sectors Units: sectors of 1 * 512 = 512 bytes Sector size (logical/physical): 512 bytes / 4096 bytes I/O size (minimum/optimal): 65536 bytes / 65536 bytes
``` 
I tried to add size via lvextend
```
lvextend -L +10G /dev/mapper/mainVG-containers_container2, but i received following error: Logical volume containers_container2 not found in volume group mainVG
```
Ok, i tried to create logical volume without LXD.

I made

`lvcreate -n lv_data1 --size 12G mainVG`

And i received
```
Disk /dev/mapper/mainVG-lv_data1: 12 GiB, 12884901888 bytes, 25165824 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
```
And i made
```
lvextend -L +10G /dev/mapper/mainVG-lv_data1
  Size of logical volume mainVG/lv_data1 changed from 12.00 GiB (3072 extents) to 22.00 GiB (5632 extents).
  Logical volume mainVG/lv_data1 successfully resized.
```
How you can see, in this case i can succesfully resize my logical volume.

Maybe i don't know something ? Maybe i have to add something in some security group ? Can you help me please ? If you know other way to resize my Logical Volume, i will glad to hear it from you. Thanks

**Comment by stgraber** [comment]
Support questions should go to https://discuss.linuxcontainers.org

In this case, all you need to do is override the size property for your container with:
 - lxc config device override container2 size 20GB
 - lxc restart container2

You shouldn't go behind LXD's back and directly mess with your storage as it will lead to problems.

**Comment by stgraber** [comment]
You can change the default size for new containers by editing the default profile and setting that same size property to whatever size you'd like.

**Comment by Piduna** [comment]
@stgraber 
let's do it from start
i am formatting new hdd via fdisk
next, i am making `lxd init` via this way:

```
Would you like to use LXD clustering? (yes/no) [default=no]:
Do you want to configure a new storage pool? (yes/no) [default=yes]:
Name of the new storage pool [default=default]: lxd
Name of the storage backend to use (btrfs, ceph, dir, lvm, zfs) [default=zfs]: lvm
Create a new LVM pool? (yes/no) [default=yes]:
Would you like to use an existing block device? (yes/no) [default=no]: yes
Path to the existing block device: /dev/sdb1
Would you like to connect to a MAAS server? (yes/no) [default=no]:
Would you like to create a new local network bridge? (yes/no) [default=yes]:
What should the new bridge be called? [default=lxdbr0]:
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]:
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: none
Would you like LXD to be available over the network? (yes/no) [default=no]: yes
Address to bind LXD to (not including port) [default=all]:
Port to bind LXD to [default=8443]:
Trust password for new clients:
Again:
Would you like stale cached images to be updated automatically? (yes/no) [default=yes]
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]:
```

Next, i am making:
`lxc init ubuntu:16.04 container1`

Is everything right ?

**Comment by Piduna** [comment]
@stgraber 

look please

```
lxc config device override container1 size 20GB
Error: The profile device doesn't exist
```

**Comment by stgraber** [comment]
Oh oops, it's 'lxc config device override container1 root size=20GB'

**Comment by Piduna** [comment]
@stgraber it is enough for me. thanks
