### ISSUE TITLE
Cannot add multiple rows to Config raw.idmap

### ISSUE THREAD

**Issue by jradxl** [lxc/lxd#5355]
* Distribution:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

 * Distribution version:
Linux z390mmate1 4.18.0-12-generic #13-Ubuntu SMP Wed Nov 14 15:17:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

 * The output of "lxc info" -- see below
LXD 3.7, snap installed

# Issue description
If I run this command on a newly created Container:-
$ printf "uid $(id -u) 1001\ngid $(id -g) 1001\nuid $(id -u) 1002\ngid $(id -g) 1002" | lxc config set u4 raw.idmap -
(IE - trying to add 4 lines to raw.idmap)

Then, the container won't restart:-
$lxc restart u4
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart u4 /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/u4/lxc.conf: 

# cat lxc.log
lxc u4 20181212234857.377 WARN     conf - conf.c:lxc_map_ids:2917 - newuidmap binary is missing
lxc u4 20181212234857.377 WARN     conf - conf.c:lxc_map_ids:2923 - newgidmap binary is missing
lxc u4 20181212234857.377 ERROR    conf - conf.c:write_id_mapping:2800 - Invalid argument - Failed to write uid mapping to "/proc/26357/uid_map"
lxc u4 20181212234857.377 ERROR    conf - conf.c:lxc_map_ids:3006 - Failed to write mapping: 0 1065536 1001
1001 1000 1
1002 1000 1
1003 1066539 64533

lxc u4 20181212234857.377 ERROR    start - start.c:lxc_spawn:1708 - Failed to set up id mapping.
lxc u4 20181212234857.436 WARN     network - network.c:lxc_delete_network_priv:2613 - Invalid argument - Failed to remove interface "veth98IXOI" from "lxdbr0"
lxc u4 20181212234857.436 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "ABORTING" instead of "RUNNING"
lxc u4 20181212234857.437 ERROR    start - start.c:__lxc_start:1939 - Failed to spawn container "u4"
lxc u4 20181212234857.437 WARN     conf - conf.c:lxc_map_ids:2917 - newuidmap binary is missing
lxc u4 20181212234857.437 WARN     conf - conf.c:lxc_map_ids:2923 - newgidmap binary is missing
lxc 20181212234857.438 WARN     commands - commands.c:lxc_cmd_rsp_recv:132 - Connection reset by peer - Failed to receive response for command "get_state"

$ lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICAzCCAYmgAwIBAgIQQQkn+oR+BC88GFWNw/S0HDAKBggqhkjOPQQDAzA4MRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRgwFgYDVQQDDA9yb290QHozOTBt
    bWF0ZTEwHhcNMTgxMjA4MTYxMDM2WhcNMjgxMjA1MTYxMDM2WjA4MRwwGgYDVQQK
    ExNsaW51eGNvbnRhaW5lcnMub3JnMRgwFgYDVQQDDA9yb290QHozOTBtbWF0ZTEw
    djAQBgcqhkjOPQIBBgUrgQQAIgNiAAQBUmyVWPHWecAQ9VA9RkKFQEcq10EbIfH8
    hEhOx+QS+ElBzMSU3F4XgySFiq0K5uyu3O1KGINQ+xyoj8x8QDyRF8e/4XkfZEzQ
    D2+IxlUhIJZabcQtnV1Tix/o9Y/L+6ajWDBWMA4GA1UdDwEB/wQEAwIFoDATBgNV
    HSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMCEGA1UdEQQaMBiCCnozOTBt
    bWF0ZTGHBMCoDkuHBKwRAAEwCgYIKoZIzj0EAwMDaAAwZQIwOtvwx8W9enDJ/JNP
    4B9LNWw4marxp28JStNS51NPXUIBKA+JGIXfXZw5UrIxmC7oAjEAhhHa22MlE2uC
    0dwGGG6rBYAEFU18wQ4BYst4soLhrezIvQJMH2wq0C7QdCCD9M9C
    -----END CERTIFICATE-----
  certificate_fingerprint: bf5dbf0ded5097bc349a767d5ba232faa2106fcf5061fce17537284760a01bf0
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.18.0-12-generic
  server: lxd
  server_pid: 2833
  server_version: "3.7"
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: z390mmate1
  project: default

**Comment by stgraber** [comment]
You can't map the same uid or gid multiple times.

**Comment by stgraber** [comment]
(Yes, the fact that the kernel only ever returns EINVAL isn't super useful to figure out that kind of restrictions :))
