### ISSUE TITLE
finding LXD documentation

### ISSUE THREAD

**Issue by akarelas-pt** [lxc/lxd#5358]
When searching for "lxd documentation" on duckduckgo.com, the readthedocs site of LXD is nowhere to be found in the top results. Other sites are top, such as this one (number 1 top result): https://help.ubuntu.com/lts/serverguide/lxd.html

However this page https://help.ubuntu.com/lts/serverguide/lxd.html doesn't contain a link to readthedocs, therefore someone who searches with duckduckgo will never reach readthedocs.

You can fix this, by linking to readthedocs from https://help.ubuntu.com/lts/serverguide/lxd.html . Please fix it, thanks.

**Comment by akarelas** [comment]
@stgraber hi, i followed your advice and went the bugs.launchpad and filed a bug, but the people responsible for maintaining the docs just don't believe me that readthedocs is official documentation. Do you feel like visiting my bug page ( https://bugs.launchpad.net/serverguide/+bug/1808755 ) and showing them where the good documentation of LXD is, riather than giving DDG users a hard time?

Thanks!
