### ISSUE TITLE
Image images:ubuntu-core/16 does not launch, "lzcat: unexpected EOF"

### ISSUE THREAD

**Issue by simos** [lxc/lxd#5367]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-42-generic
   * LXC version: 3.8
   * LXD version: 3.8
   * Storage backend in use: zfs

# Issue description

The container image `images:ubuntu-core/16` does not start or launch.

# Steps to reproduce

 1. Launch a container with `images:ubuntu-core/16`.

        lxc launch images:ubuntu-core/16 mycore

What happens: The container does not start.
What should happen: The container should start.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
- [x] Container's `console.log`:

```
lzcat: unexpected EOF
/sbin/init: .: line 43: can't open '/initrd/scripts/ubuntu-core-rootfs'
```

**Comment by stgraber** [comment]
Fixed the image generation script to handle the modified initrd
