### ISSUE TITLE
Show total data to be transferred when using lxd-p2c

### ISSUE THREAD

**Issue by danboid** [lxc/lxd#5368]
When using lxd-p2c to transfer a machine into a container currently it displays the current data transfer rate and how much has been transferred but it gives no indication of the total amount of data to be transferred. Giving an ETA for completion of the transfer would also be nice.

**Comment by stgraber** [comment]
That's because we don't know how much data needs transferring, if we did, the LXD progress code would show a progress percentage as is done with images.
