### ISSUE TITLE
Container sometimes fails to restart

### ISSUE THREAD

**Issue by vsenko** [lxc/lxd#5383]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)
 * The output of "lxc info" or if that fails:

        config:
          images.auto_update_interval: "0"
        api_extensions:
        - storage_zfs_remove_snapshots
        - container_host_shutdown_timeout
        - container_stop_priority
        - container_syscall_filtering
        - auth_pki
        - container_last_used_at
        - etag
        - patch
        - usb_devices
        - https_allowed_credentials
        - image_compression_algorithm
        - directory_manipulation
        - container_cpu_time
        - storage_zfs_use_refquota
        - storage_lvm_mount_options
        - network
        - profile_usedby
        - container_push
        - container_exec_recording
        - certificate_update
        - container_exec_signal_handling
        - gpu_devices
        - container_image_properties
        - migration_progress
        - id_map
        - network_firewall_filtering
        - network_routes
        - storage
        - file_delete
        - file_append
        - network_dhcp_expiry
        - storage_lvm_vg_rename
        - storage_lvm_thinpool_rename
        - network_vlan
        - image_create_aliases
        - container_stateless_copy
        - container_only_migration
        - storage_zfs_clone_copy
        - unix_device_rename
        - storage_lvm_use_thinpool
        - storage_rsync_bwlimit
        - network_vxlan_interface
        - storage_btrfs_mount_options
        - entity_description
        - image_force_refresh
        - storage_lvm_lv_resizing
        - id_map_base
        - file_symlinks
        - container_push_target
        - network_vlan_physical
        - storage_images_delete
        - container_edit_metadata
        - container_snapshot_stateful_migration
        - storage_driver_ceph
        - storage_ceph_user_name
        - resource_limits
        - storage_volatile_initial_source
        - storage_ceph_force_osd_reuse
        - storage_block_filesystem_btrfs
        - resources
        - kernel_limits
        - storage_api_volume_rename
        - macaroon_authentication
        - network_sriov
        - console
        - restrict_devlxd
        - migration_pre_copy
        - infiniband
        - maas_network
        - devlxd_events
        - proxy
        - network_dhcp_gateway
        - file_get_symlink
        - network_leases
        - unix_device_hotplug
        - storage_api_local_volume_handling
        - operation_description
        - clustering
        - event_lifecycle
        - storage_api_remote_volume_handling
        - nvidia_runtime
        - candid_authentication
        - candid_config
        - candid_config_key
        - usb_optional_vendorid
        api_status: stable
        api_version: "1.0"
        auth: trusted
        public: false
        auth_methods:
        - tls
        environment:
          addresses: []
          architectures:
          - x86_64
          - i686
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIIFRzCCAy+gAwIBAgIRAJEFqnAlWEgz9fU3RUjSw5kwDQYJKoZIhvcNAQELBQAw
            NjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEBs
            eGMtaG9zdDAeFw0xODEyMDUxMDEzMDJaFw0yODEyMDIxMDEzMDJaMDYxHDAaBgNV
            BAoTE2xpbnV4Y29udGFpbmVycy5vcmcxFjAUBgNVBAMMDXJvb3RAbHhjLWhvc3Qw
            ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDYnZf4IF7Je2WXfTr1klG+
            RHCwPT4s2Sf0HooFxyo5F/LEc2lzaYdDaGMjTML6wOzRedbH+/6GzMeFxeYAVSDM
            zKQzrmXkJcoKfDtTdZO8sYoy8koQ8Gj9dubW4Cd4mP7G4RLEYByCNgxNU15heZus
            zSh2z0LlomEG3s4vRfgvTXx8GmA7/VY+3jJH1R/icJyq5eAF09ZyKS+e9mkFrmIO
            AgjPxxW1f3saMUy03se7LR+oA47CCwbfVB6AMvAGM3w0YNTkF9w7Wt3bAWd5PuD+
            UX6FdwEd8ZhJ9PB1hz9h1SelBgYV9LJo5h8TjSqC+PguGUxpyh5ZgjXRCdHyE/Ib
            SpfJ5a+Dsw+mYGVlzfVzZs00KeJbD4uUd+M6tQyj1P8wbyLdbinxrSMoL2V/PNFB
            c/GJa229BcUfSmk4dQUt5iSI+NNZDHsPmsl7ZVgP4HVKIVJOEXBamu07z4sFuj99
            mnW8psI6DmIq09n+Q8oS/KuBP8tGE7xGyJD7EcCU4XpBjzNJv8bdA1AaveaEFIMR
            BPuolKGQvohKKsTF5EY/Owo8CRw0mpB53hN/ZKSGkNp0CGc0kuG9mMS4ilT0ZyLm
            DC1usnWqji/T/98eMv0laAgO+TcD/T1gykNOdcG+GeK3FzFqHQOZZgSUd7lyCj8J
            yAvGjnceT2y66B5frsATbwIDAQABo1AwTjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0l
            BAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAZBgNVHREEEjAQgghseGMtaG9z
            dIcErBABCjANBgkqhkiG9w0BAQsFAAOCAgEAfojhk2ZOhqjFqtm5LymZd7mPDY6p
            /l3NyySgPWPw8jVvrA35u0r0jwCV4EXej6Kv0BW/APbe0znZJo1HjnaOoMP/VUwG
            Yjf/tR0PDsQXDtJTeudZ3F6O3ApbxjAmqRpHGH2mSipUT+uaW3xdQHJMSM8blttT
            nBY25kKkSNLkZLNdZu87DXtv13tf0M2Eih4l5s1jpvh2eInH3EX+aRH7XkmkDi5p
            RiP4bvHc4E5KEWqs2YJbV64TCoxAyYfofMKzoMJkEtzOVAacw136zmOYWG8mjBp+
            mUqRXWXXWWiDO0I5MVYc/+gkYG0EwUFdkXC8fYPT2XI1ALWMy77CABxlsHv5nNAI
            Yx779eiU/Gs/v2lLA9LvrqnHTfjW9sYqJk2PXWnvkvXuyfv3nkAmYesBQ07M3wwJ
            l3+6q00OBdoOiLSmKvxGVR0CK0R0C5cM9ntcKO9CFXxzZ5de4ZI+0ov8K+KtNIrm
            /t/KvavBcWVhxz0S24MQLvDyAi2uriR77qRXI2EDMVhhp5Uj32ZyCZF+/X6SFoNa
            apPGkqQ0tLmaxQ3SxegR2T6+ZepZQ07+nZihM4JhermbfqhCU4KvH7Wv2uKN20D6
            DMNR4z9s9mF8op59IYLNk3idTFHJSVK9fT/r/pXxlVseFlDSD3fDekiDQKPgF59J
            xxCKGP9TSsGkRyE=
            -----END CERTIFICATE-----
          certificate_fingerprint: dc2803a84464ce7962189815c6c7a90c0aaada12bdddaba7d1fe883f6dea85f6
          driver: lxc
          driver_version: 3.0.3
          kernel: Linux
          kernel_architecture: x86_64
          kernel_version: 4.15.0-43-generic
          server: lxd
          server_pid: 1562
          server_version: 3.0.3
          storage: btrfs
          storage_version: 4.15.1
          server_clustered: false
          server_name: lxc-host
          project: ""

# Issue description

I have a lxd host which runs several containers. Periodically I run a script that backups containers:

    for container in $(lxc list --format csv -c n)
    do
        echo "== $container =="
        lxc stop $container
        lxc snapshot $container $snapshotname
        sleep 10
        lxc start $container

        duplicity --full-if-older-than 1M --no-encryption /var/lib/lxd/storage-pools/default/snapshots/$container/$snapshotname file:///backup_disk/containers/$container

        duplicity verify --no-encryption file:///backup_disk/containers/$container /var/lib/lxd/storage-pools/default/snapshots/$container/$snapshotname

        lxc delete $container'/'$snapshotname
        echo ""
        echo ""
    done

Sometimes one particular container fails to start with the following:

        Error: Failed to run: /usr/lib/lxd/lxd forkstart web /var/lib/lxd/containers /var/log/lxd/web/lxc.conf: 
        Try `lxc info --show-log web` for more info

`sleep 10` was added in an attempt to fix this problem and it helped a bit - now container fails to start significantly less often. But it still fails some times.

# Steps to reproduce

It is not trivial to reproduce the problem. That particular container was not the first one created, nor the last one. It does not have any specific differences in config. 

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
    Nothing shows up in `dmesg`.
 - [X] Container log (`lxc info NAME --show-log`)

        Name: web
        Remote: unix://
        Architecture: x86_64
        Created: 2018/12/07 12:16 UTC
        Status: Stopped
        Type: persistent
        Profiles: default

        Log:

        lxc web 20181227221932.865 ERROR    network - network.c:lxc_setup_netdev_in_child_namespaces:2934 - Operation not permitted - Failed to set network device "eth0" up
        lxc web 20181227221932.865 ERROR    network - network.c:lxc_setup_network_in_child_namespaces:3047 - failed to setup netdev
        lxc web 20181227221932.865 ERROR    conf - conf.c:lxc_setup:3516 - Failed to setup network
        lxc web 20181227221932.865 ERROR    start - start.c:do_start:1263 - Failed to setup container "web"
        lxc web 20181227221932.866 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
        lxc web 20181227221932.866 WARN     network - network.c:lxc_delete_network_priv:2589 - Operation not permitted - Failed to remove interface "eth0" with index 55
        lxc web 20181227221932.867 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "ABORTING" instead of "RUNNING"
        lxc web 20181227221932.870 ERROR    start - start.c:__lxc_start:1939 - Failed to spawn container "web"
        lxc 20181227221932.933 WARN     commands - commands.c:lxc_cmd_rsp_recv:132 - Connection reset by peer - Failed to receive response for command "get_state"

 - [X] Container configuration (`lxc config show NAME --expanded`)

        architecture: x86_64
        config:
          boot.autostart: "true"
          image.architecture: amd64
          image.description: Ubuntu bionic amd64 (20181207_07:43)
          image.os: Ubuntu
          image.release: bionic
          image.serial: "20181207_07:43"
          limits.memory: 4GB
          limits.memory.swap: "false"
          volatile.base_image: 8828bdf6ab978d47715a5e8e4f384a4f4dfade1155aa4cbcbcda16e9be34f6a9
          volatile.eth0.hwaddr: 00:16:3e:78:29:55
          volatile.idmap.base: "0"
          volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
          volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
          volatile.last_state.power: RUNNING
        devices:
          eth0:
            name: eth0
            nictype: macvlan
            parent: enp6s0
            type: nic
          root:
            path: /
            pool: default
            type: disk
        ephemeral: false
        profiles:
        - default
        stateful: false
        description: ""

 - [X] Default profile configuration (`lxc profile show default`)

        config:
          boot.autostart: "true"
          limits.memory: 4GB
          limits.memory.swap: "false"
        description: Default LXD profile
        devices:
          eth0:
            name: eth0
            nictype: macvlan
            parent: enp6s0
            type: nic
          root:
            path: /
            pool: default
            type: disk
        name: default
        used_by:
        - /1.0/containers/web

 - [X] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

        t=2018-12-28T04:19:18+0600 lvl=info msg="Shutting down container" action=shutdown created=2018-12-07T18:16:55+0600 ephemeral=false name=web timeout=-1s used=2018-12-27T04:18:21+0600
        t=2018-12-28T04:19:20+0600 lvl=info msg="Shut down container" action=shutdown created=2018-12-07T18:16:55+0600 ephemeral=false name=web timeout=-1s used=2018-12-27T04:18:21+0600
        t=2018-12-28T04:19:20+0600 lvl=info msg="Creating container" ephemeral=false name=web/current
        t=2018-12-28T04:19:20+0600 lvl=info msg="Created container" ephemeral=false name=web/current
        t=2018-12-28T04:19:31+0600 lvl=info msg="Starting container" action=start created=2018-12-07T18:16:55+0600 ephemeral=false name=web stateful=false used=2018-12-27T04:18:21+0600
        t=2018-12-28T04:19:32+0600 lvl=eror msg="Failed starting container" action=start created=2018-12-07T18:16:55+0600 ephemeral=false name=web stateful=false used=2018-12-27T04:18:21+0600

 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Looks like the kernel is failing to create the macvlan device

**Comment by stgraber** [comment]
Switching to a bridge instead would avoid any driver/nic specific issue and likely get you a much more consistent behavior.

**Comment by vsenko** [comment]
Doesn't the bridge configuration imply a separate subnet for containers? 

One of my specific requirements is to place containers directly in the network the host is attached to.

Also the section **bridged or macvlan for connection to physical network** of https://lxd.readthedocs.io/en/latest/containers/ states that `macvlan` 

> usually offers better performance than a bridge

**Comment by stgraber** [comment]
No, it doesn't, you can setup a bridge in your distro's network configuration manager (networkd, network-manager, ifupdown) to bridge your physical interface within a bridge, use that for your internet and then attach containers to it.

So that's typically without using LXD's networks, just making a br0 bridge (or whatever you want it called) which includes your physical nic, then change your nic device to be nictype=bridged and parent=br0.

Closing as the error shown above indicates a kernel/driver/nic issue, typically related to the MAC tracking feature of macvlan and so isn't something we can do much about in LXD itself.
