### ISSUE TITLE
Error using lxd copy

### ISSUE THREAD

**Issue by Fecro** [lxc/lxd#5385]
# Required information
Source Server
 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-36-generic
   * LXC version: 3.0.2
   * LXD version: 3.0.1
   * Storage backend in use: zfs

Target Server - - -
 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-43-generic
   * LXC version: 3.0.3
   * LXD version: 3.0.3
   * Storage backend in use: zfs

# Issue description
I want to make a copy of a container from one server (Soucer server) to another (Target server), I'm using the command:
"lxc copy containerA/snap0 target:containerA --verbose"

And I get the following error: "Error: Failed container creation: Create LXC container: Initialize LXC: no such file or directory"

The Target server is newly installed and uses as storage a device block /dev/sda4

# Note
I have already used the lxc copy command and I did not receive this error.

# Source 
comand lxc storage list
+------+-------------+--------+----------------------------+---------+
| NAME | DESCRIPTION | DRIVER |           SOURCE           | USED BY |
+------+-------------+--------+----------------------------+---------+
| lxd  |             | zfs    | /var/lib/lxd/disks/lxd.img | 25      |
+------+-------------+--------+----------------------------+---------+

# Target
command lxc storage list
+------+-------------+--------+--------+---------+
| NAME | DESCRIPTION | DRIVER | SOURCE | USED BY |
+------+-------------+--------+--------+---------+
| lxd  |             | zfs    | lxd    | 4       |
+------+-------------+--------+--------+---------+

# lxc monitor from the Target Server
metadata:
  context: {}
  level: dbug
  message: 'New event listener: f5ca206a-8514-43c2-ad84-3769782f7b65'
timestamp: "2018-12-29T13:54:14.487895427Z"
type: logging
 
 
metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: "2018-12-29T13:54:22.160725442Z"
type: logging
 
 
metadata:
  context:
    ip: x
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2018-12-29T13:54:22.160806939Z"
type: logging
 
 
metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: "2018-12-29T13:54:22.161695303Z"
type: logging
 
 
metadata:
  context: {}
  level: dbug
  message: 'New event listener: 640c12c6-160b-40a5-8243-8635bd1e99a4'
timestamp: "2018-12-29T13:54:22.473872329Z"
type: logging
 
 
metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: "2018-12-29T13:54:22.473718584Z"
type: logging
 
 
metadata:
  context:
    ip: x
    method: GET
    url: /1.0/events
  level: dbug
  message: handling
timestamp: "2018-12-29T13:54:22.473764255Z"
type: logging
 
 
metadata:
  context: {}
  level: dbug
  message: Responding to container create
timestamp: "2018-12-29T13:54:22.559460908Z"
type: logging
 
 
metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: "2018-12-29T13:54:22.559356146Z"
type: logging
 
 
metadata:
  context:
    ip: x
    method: POST
    url: /1.0/containers
  level: dbug
  message: handling
timestamp: "2018-12-29T13:54:22.559431416Z"
type: logging
 
 
metadata:
  context: {}
  level: dbug
  message: No valid storage pool in the container's local root disk device and profiles
   found
timestamp: "2018-12-29T13:54:22.562457973Z"
type: logging
 
 
metadata:
 context: {}
 level: dbug
 message: 'Database error: &errors.errorString{s:"sql: no rows in result set"}'
timestamp: "2018-12-29T13:54:22.562895801Z"
type: logging
 
 
metadata:
 context: {}
 level: dbug
 message: 'Database error: &errors.errorString{s:"sql: no rows in result set"}'
timestamp: "2018-12-29T13:54:22.56394832Z"
type: logging
 
 
metadata:
 context:
   ephemeral: "false"
   name: containerA
 level: info
 message: Creating container
timestamp: "2018-12-29T13:54:22.572457423Z"
type: logging
 
 
metadata:
 context: {}
 level: dbug
 message: Mounting ZFS storage volume for container "containerA" on storage pool "lxd"
timestamp: "2018-12-29T13:54:22.582283133Z"
type: logging
 
 
metadata:
 context: {}
 level: eror
 message: Failed to mount ZFS dataset "lxd/containers/containerA" onto "/var/lib/lxd/storage-pools/lxd/containers/containerA"
timestamp: "2018-12-29T13:54:32.59276082Z"
type: logging
 
 
metadata:
 context: {}
 level: dbug
 message: Mounting ZFS storage volume for container "containerA" on storage pool "lxd"
timestamp: "2018-12-29T13:54:32.593649161Z"
type: logging
 
 
metadata:
 context: {}
 level: eror
 message: Failed to mount ZFS dataset "lxd/containers/containerA" onto "/var/lib/lxd/storage-pools/lxd/containers/containerA"
timestamp: "2018-12-29T13:54:42.603878924Z"
type: logging
 
 
metadata:
 context: {}
 level: dbug
 message: 'Scheduler: container containerA changed: re-balancing'
timestamp: "2018-12-29T13:54:42.604126046Z"
type: logging
 
 
metadata:
 context:
   created: 2018-12-29 13:54:22 +0000 UTC
   ephemeral: "false"
   name: containerA
   used: 1970-01-01 00:00:00 +0000 UTC
 level: info
 message: Deleting container
timestamp: "2018-12-29T13:54:42.604047988Z"
type: logging
 
 
metadata:
 context: {}
 level: dbug
 message: Deleting ZFS storage volume for container "containerA" on storage pool "lxd"
timestamp: "2018-12-29T13:54:42.613792259Z"
type: logging
 
 
metadata:
 context: {}
 level: dbug
 message: Deleted ZFS storage volume for container "containerA" on storage pool "lxd"
timestamp: "2018-12-29T13:54:42.620999746Z"
type: logging
 
 
metadata:
 action: container-deleted
 source: /1.0/containers/containerA
timestamp: "2018-12-29T13:54:43.275845473Z"
type: lifecycle
 
 
metadata:
 context:
   created: 2018-12-29 13:54:22 +0000 UTC
   ephemeral: "false"
   name: containerA
   used: 1970-01-01 00:00:00 +0000 UTC
 level: info
 message: Deleted container
timestamp: "2018-12-29T13:54:43.275755388Z"
type: logging
 
 
metadata:
 context:
   ephemeral: "false"
   name: containerA
 level: eror
 message: Failed creating container
timestamp: "2018-12-29T13:54:43.275954669Z"
type: logging
 
 
metadata:
 context: {}
 level: dbug
 message: 'Database error: &errors.errorString{s:"sql: no rows in result set"}'
timestamp: "2018-12-29T13:54:43.276358727Z"
type: logging

**Comment by turtle0x1** [comment]
>No valid storage pool in the container's local root disk device and profiles 

looks pretty suspect could it be that the default profile doesn't exist contain profile disk information E.G my profile looks like;

```
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
```

What does yours look like ? Prephaps you could try `lxc copy containerA/snap0 target:containerA -p default --verbose` (notice I added the default profile) 

I'm no expert so thats about all I can suggest

**Comment by Fecro** [comment]
> > No valid storage pool in the container's local root disk device and profiles
> 
> looks pretty suspect could it be that the default profile doesn't exist contain profile disk information E.G my profile looks like;
> 
> ```
> config: {}
> description: Default LXD profile
> devices:
>   eth0:
>     name: eth0
>     nictype: bridged
>     parent: br0
>     type: nic
>   root:
>     path: /
>     pool: default
>     type: disk
> name: default
> ```
> 
> What does yours look like ? Prephaps you could try `lxc copy containerA/snap0 target:containerA -p default --verbose` (notice I added the default profile)
> 
> I'm no expert so thats about all I can suggest

It's the same in the both servers
# Source server
```
lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: lxd
    type: disk
name: default
```

# Target Server
```
lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: lxd
    type: disk
name: default
```

The result for the command ` lxc copy containerA/snap0 target:containerA -p default --verbose` is:
`Error: Failed container creation: Duplicate profile found in request`

**Comment by turtle0x1** [comment]
Hmm then im lost apologies!

**Comment by stgraber** [comment]
```
message: Failed to mount ZFS dataset "lxd/containers/containerA" onto "/var/lib/lxd/storage-pools/lxd/containers/containerA"
```

Does that mount path exist? I wonder if something made it so that this is somehow missing.

**Comment by Fecro** [comment]
> ```
> message: Failed to mount ZFS dataset "lxd/containers/containerA" onto "/var/lib/lxd/storage-pools/lxd/containers/containerA"
> ```
> 
> Does that mount path exist? I wonder if something made it so that this is somehow missing.

Tell me how can I verify this?

**Comment by stgraber** [comment]
Check that `/var/lib/lxd/storage-pools/lxd/containers` exists with `sudo ls -lh /var/lib/lxd/storage-pools/lxd/containers`

**Comment by Fecro** [comment]
The error is caused by the following parameters within the configuration file `lxc config edit containerA`
```
root:
    limits.read: 60iops
    limits.write: 60iops
    path: /
    pool: lxd
    size: 100GB
    type: disk
```
it should not be the correct path. I deleted those parameters and I could start the copy.

**Comment by stgraber** [comment]
@Fecro so the two iops limits were causing this?

That's odd, though maybe could be explained if that makes it so slow that the mount operation ends up failing due to the iops limits?

**Comment by Fecro** [comment]
@stgraber I do not know if it was the iops. I removed all those parameters to be able to make the copy and then I copied them again.
