### ISSUE TITLE
doc: there is no mention of client.crt in doc/security.md

### ISSUE THREAD

**Issue by akarelas** [lxc/lxd#5386]
Here it says you need to enter your password to add a remote. But what if I don't want to enter a password? What if I want to use my client.crt? How will I add the remote then? How will I add client.crt to the remote? So many questions left unanswered...

Please don't tell me to look in other help pages for the infornation I need. I cannot afford to go through 10 pages for the information I want. Is it or is it not security information?

**Comment by turtle0x1** [comment]
You should be able to  copy the cert to the server and then import it using `lxc config trust add` you can view help for most commands for example by type `sudo lxd.lxc config trust add --help`
