### ISSUE TITLE
LXD and ZFS: Containers keeps running out of disk space

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#5390]
# Required information

 * Distribution: **Ubuntu**
 * Distribution version: **18.04 LTS**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.15.0-38-generic**
   * LXC version: **3.0.2**
   * LXD version: **3.0.2**
   * Storage backend in use: **zfs**

# Issue description

It seems like the containers keeps running out of disk space. We have a zfs pool called: services:
Global Zpool: 
```
NAME       SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
services  71.5G  69.3G  2.23G         -    72%    96%  1.00x  ONLINE  -
```
LXD Zpool from ZFS Subvolume:
```
+------------+-------------+--------+--------------+---------+
|    NAME    | DESCRIPTION | DRIVER |    SOURCE    | USED BY |
+------------+-------------+--------+--------------+---------+
| containers |             | zfs    | services/lxd | 196     |
+------------+-------------+--------+--------------+---------+
```
As you can see it shows that the pool is 96% used (69.3GB), however when we check the containers zpool from lxd we see that only 24GB of storage is used by the containers. The /images directory is mounted from a /data backup directory and does not create containers within the images directory. 
```
/var/lib/lxd/storage-pools# du -sh *
24G	containers
```
```
/var/lib/lxd/storage-pools/containers# du -sh *
24G	containers
4.0K	custom
28K	images
724K	snapshots
```

It seems like something is using about **45.27GB** of storage inside this LXD ZFS pool, which we cant find. 
```
lxc storage info containers
info:
  description: ""
  driver: zfs
  name: containers
  space used: 74.33GB
  total space: 0B
```

Can anyone please assist us with this? 

Thanks, E.

**Comment by stgraber** [comment]
What does `zfs list -t all` show you?

**Comment by stgraber** [comment]
Note that only running containers are mounted, so your `du -sh` wouldn't have picked up on any container that's not running, nor any container snapshots.

**Comment by elbrinke** [comment]
hi @stgraber , 

Did you have a loot at the **zfs_list.log** i send through? 

Regards

**Comment by elbrinke** [comment]
Ah i found the problem... snapshots :) eishhh ...
