### ISSUE TITLE
Unexpected failure - lxc profile delete default security.syscalls.blacklist

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#5391]
works: lxc profile set default security.syscalls.blacklist "keyctl errno 38"
works: lxc profile get default security.syscalls.blacklist
fails: lxc profile delete default security.syscalls.blacklist

Docs seem to indicate security.syscalls.blacklist cannot be deleted.

Question: Is the correct way to clear/delete this setting...

lxc profile set default security.syscalls.blacklist ""

Thanks.

**Comment by stgraber** [comment]
unset

**Comment by stgraber** [comment]
delete is used to delete a profile

**Comment by davidfavor** [comment]
Ah! Got it!

Thanks!
