### ISSUE TITLE
How to increase entropy in LXD containers

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#5392]
Use to be this worked - **lxc profile set default security.syscalls.blacklist "keyctl errno 38**" - and reading various writings about this, this setting seems to have simply disabled the error + entropy was never increased.

Several questions. Let me know if...

1) There's a way to get rng-tools to actually work with /dev/urandom inside containers.

2) Let me know if there's a better way to generate large entropy inside LXD containers.

Info about rng-tools failures...

```
lxd: net14-drf-webhook-api # /usr/sbin/rngd -r /dev/urandom
unable to adjust write_wakeup_threshold: Permission denied

lxd: net14-drf-webhook-api # journalctl --no-pager | grep -i rng | grep "Operation not permitted"
Jan 02 10:19:37 net14-drf-webhook-api systemd[1]: rng-tools.service: Failed to reset devices.list: Operation not permitted
Jan 02 10:19:38 net14-drf-webhook-api rngd[616]: RNDADDENTROPY failed: Operation not permitted
```

**Comment by davidfavor** [comment]
This container is unprivileged.

If the only way to fix this is make the container privileged, I can do this.

I'd prefer to keep the container unprivileged, if possible.

Thanks!

**Comment by davidfavor** [comment]
Thinking through this + looking at /dev/urandom setup, maybe the solution is simpler than I thought.

Maybe the answer is to run rng-tools at machine level + this increases entropy in all containers, based on how /dev/urandom is handled.

Let me know if this is might be the simple solution also.

**Comment by stgraber** [comment]
urandom is system wide so just run rngd or haveged on the host

**Comment by davidfavor** [comment]
Aha! So it was easy.

Thanks!

Apologies for the rambling.
