### ISSUE TITLE
It is too easy to delete a volume accidentally instead of deleting its snapshot

### ISSUE THREAD

**Issue by melato** [lxc/lxd#5394]
lxc 3.8 snap rev 9795

I wanted to delete snapshot s1 of volume v1 in pool p1, so I hastily typed this:
`lxc storage volume delete p1 v1 d1`
The result was that volume v1 was deleted.
The correct command is:
`lxc storage volume delete p1 v1/d1`

Since lxc storage volume delete can delete only one volume at a time, I suggest returning an error if I add extra arguments at the end.

There are volume snapshot commands that specify a snapshot as vol/snap and other commands that specify a snapshot as "vol snap".  It is therefore easy to make this mistake.
Commands with /:
lxc storage volume delete p1 v1/s1
lxc storage volume copy p1/v1/s1 p1/v2

Commands with space:
lxc storage volume snapshot p1 v1 s1
lxc storage volume restore p1 v1 s1

zfs seems to consistently use filesystem@snapshot to reference a snapshot.
e.g. "zfs snapshot filesystem@snapname"

This is similar to https://github.com/lxc/lxd/issues/4747 except it can be fixed without breaking existing scripts, because volumes are deleted one at a time.

**Comment by stgraber** [comment]
Oh yeah, that's pretty nasty, passing additional arguments to `lxc storage volume delete` should indeed result in an error, not having it delete the wrong thing.
