### ISSUE TITLE
[Arch|AUR] Memory leakage(?) - unreclaimable slab grows till system dies

### ISSUE THREAD

**Issue by C0rn3j** [lxc/lxd#5405]
# Required information

 * Distribution: Arch Linux
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.20
   * LXC version: 3.1.0
   * LXD version: 3.8
   * Storage backend in use: issue happens on both ext4 and btrfs, following logs/screens are from ext4

# Issue description

I run two LXD instances on two KVM hosts. One uses ext4, other btrfs. I've had this issue happen since I started using LXD I believe and have been working around it by restarting the hosts every now and then.

# Steps to reproduce

 1. Install Arch Linux and AUR/lxd
 2. Run some containers, wait a day or two
 3. Stop containers, stop lxd, stop everything that could be consuming memory
 4. /proc/meminfo has high SUnreclaim despite the hosts doing nothing.

# Information to attach

Some/all containers are running privileged.
```
 /var/log/lxd/ansible/lxc.log
lxc ansible 20190108153350.634 WARN     conf - conf.c:lxc_setup_devpts:1641 - Invalid argument - Failed to unmount old devpts instance
lxc ansible 20190111111820.158 WARN     network - network.c:lxc_delete_network_priv:2589 - Operation not permitted - Failed to remove interface "eth0" with index 4
```

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
file 'lxd.log' does not seem to be present on my system.
---

Small side note - is ebtables a dependency? I couldn't find so and I get this error on shutting down the containers (which shut down succesfully)
```
lxd[380]: t=2019-01-11T12:18:20+0100 lvl=eror msg="Unable to remove network filters" container=ansible err="Failed to run: ebtables -L --Lmac2 --Lx: "
```

[htop + tmpfs list](https://i.imgur.com/KAKeetu.png)

[/proc/meminfo - looks like Slab is taking 1.3GB](https://haste.rys.pw/raw/efuniyageg)

[/proc/slabinfo - am out of my depth here](https://haste.rys.pw/raw/oqiqirutam)

**Comment by stgraber** [comment]
@brauner can you take a look?

**Comment by stgraber** [comment]
I don't suppose you can easily try running the exact same setup on a physical system?
Mostly to check that it's not a KVM memory issue, possibly related to the balloon driver or something like that.

Otherwise it looks like some kind of kernel memory leak. It may be interesting to get some memory details from your container prior to shutting everything down, to see if you can track where that memory was used and so figure out what's not getting freed.

Off the top of my head, one thing that could explain this (but I've personally never seen it) would be if tmpfs mounts inside containers weren't properly getting flushed on shutdown. This would likely mean a mount namespace isn't getting flushed, keeping the data that's in that tmpfs in memory while not being tied to any process on the system.

But normally, the container being shut down causes that namespace to go away, resulting in the tmpfs getting flushed.

**Comment by stgraber** [comment]
I'm closing this issue because it can't be a LXD bug since per what you said, you stopped all containers and stopped LXD itself, so LXD itself isn't holding onto that memory, the kernel is somehow.

That makes it a kernel bug, which is still something we're interested in discussing here, just with the issue marked as closed against LXD.

**Comment by C0rn3j** [comment]
It's an Arch KVM on an Arch host, I can install AUR/lxd on host (now that it doesn't prevent normal shutdown anymore since a month or two ago) and migrate the containers I guess, should be similar enough minus the KVM part.

**Comment by stgraber** [comment]
Ok, that'd be useful to see where the issue lies.

**Comment by C0rn3j** [comment]
So at the moment I am running snap LXD on the host directly, no KVM, on Arch Linux with kernel 5.1.6.

After 3 days of uptime, SUnreclaim was 3GB+

That is after stopping all containers, running `snap stop lxd` and killing my DE and almost all processes I could.

[meminfo_2019_06_06.txt](https://github.com/lxc/lxd/files/3260656/meminfo_2019_06_06.txt)
[slabinfo_2019_06_06.txt](https://github.com/lxc/lxd/files/3260657/slabinfo_2019_06_06.txt)

**Comment by stgraber** [comment]
Would slabtop maybe give you a more readable output for slab info?

@brauner thoughts

Having all containers and processes stopped suggests a memory leak somewhere in the kernel, nothing immediately jumps at me in your slabinfo but it's kinda hard to do the mental math of active objs * size when reading through it

**Comment by brauner** [comment]
I wouldn't blame the kernel so fast. This could also be snapd leaking memory or go not gcing agressively enough. Can you reproduce on a different kernel?

**Comment by brauner** [comment]
Also, what happens if you stop snapd?

**Comment by brauner** [comment]
Also, can you give us the full process list of this system after you stopped lxd and all containers?

**Comment by C0rn3j** [comment]
On the initial post (which used AUR/lxd in KVM) I posted htop screen with all the processes and snapd doesn't appear to be running there.
I believe I didn't stop it for the outputs I posted today.

I've rebooted now, but I'll grab `ps aux` and `slabtop -s c` output in a few days when this reoccurs and after I really trim down the processes like I did in the initial post.

@stgraber I assume I should be sorting by CACHE_SIZE in slabtop for the most relevant info?

**Comment by C0rn3j** [comment]
Kernel: 5.1.7-arch1-1-ARCH 

htop:
![image](https://user-images.githubusercontent.com/1641362/59218885-86524b80-8bc1-11e9-8e1b-ed1b1331faa5.png)

slabtop -s c:
![image](https://user-images.githubusercontent.com/1641362/59218948-aaae2800-8bc1-11e9-9312-df92c206ff7f.png)

ps aux, meminfo and slabinfo coming momentarily in an edit

**Comment by C0rn3j** [comment]
Snap LXD: 3.18
Kernel: 4.18.0-24-generic
OS: Ubuntu 18.04

Caches were dropped `echo 3 > /proc/sys/vm/drop_caches`, `sync` ran too.

[meminfo-2019-11-22.log](https://github.com/lxc/lxd/files/3879700/meminfo-2019-11-22.log)
[ps-aux-2019-11-22.log](https://github.com/lxc/lxd/files/3879701/ps-aux-2019-11-22.log)
[slabinfo-2019-11-22.log](https://github.com/lxc/lxd/files/3879702/slabinfo-2019-11-22.log)
[df-2019-11-22.log](https://github.com/lxc/lxd/files/3879706/df-2019-11-22.log)

htop:
![image](https://user-images.githubusercontent.com/1641362/69429631-4ed0f900-0d34-11ea-9c26-4b343cdb79c5.png)

slabtop -s c:
![image](https://user-images.githubusercontent.com/1641362/69429665-614b3280-0d34-11ea-9862-9eace14b807d.png)

unreclaimable slab has some 20GB and the rest of the 150GB taken are a mystery.

**Comment by brauner** [comment]
Why is LXD not showing in ps auxf?

**Comment by C0rn3j** [comment]
I shut nearly everything unnecessary down to get the stats, it is normally running.

**Comment by brauner** [comment]
> I shut nearly everything unnecessary down to get the stats, it is normally running.

Hm, but if it's the LXD daemon that's causing the issue I wonder what's pinning the memory than if it's gone.

**Comment by C0rn3j** [comment]
@stgraber deduced it's a kernel bug https://github.com/lxc/lxd/issues/5405#issuecomment-454024325

The system will be running in this broken state for the next 2 hours before being nuked, if you're interested in poking around in it I could get you SSH access.
