### ISSUE TITLE
'lxc network ...' needs better documentation

### ISSUE THREAD

**Issue by jelmd** [lxc/lxd#5410]
lxd tries to start a container but fails, because it is using the wrong interface (i.e. `lxc.net.0.link = mb0`).
There seems to be no way to change this setting, at least none is documented.
The `lxc network` "man pages" are obscure, do not explain anything and thus are completely useless.

**Comment by stgraber** [comment]
Assuming you're using LXD (your mention of `lxc.net.0.link` suggests you may be using LXC instead), `lxc config show` will show you the configuration of your container and `lxc profile show` can be used to show the configuration of the profiles applied to it, either can have network interfaces that are attached to your container, modifying that can be done with the matching `edit` command.

The description of all containers and profiles options can be found in our documentation:
https://lxd.readthedocs.io/en/latest/containers/

The `lxc network` commands are used to configure network settings, not container settings, and so is unlikely to be useful in this case as your network doesn't appear to have been created with LXD in the first place.


Closing as this is not strictly a LXD issue, the relevant config keys are tab-completed with help messages showing you the general syntax, and full documentation for all config keys is readily available online at the link above.
