### ISSUE TITLE
Forward port from remote container to LXD client

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#5414]
LXD 3.9

# Issue description

I need to access web application running on a remote LXD host container behind firewall. LXD port :8443 is forwarded, but nothing else. Application is a not protected, so it should be only accessed through secure channel.

I added proxy device, but it made web app accessible only on LXD host, not on LXD client machine: 

    lxc config device add c1 proxy0 listen=tcp:127.0.0.1:80 connect=tcp:127.0.0.1:9090 

Now I need to setup another parallel tunnel to LXD host, either by SSH or by another HTTPS proxy with valid certificates. But LXD already has the secure tunnel. I'd like to reuse that for port forwarding.

Maybe it is possible to reuse `lxc console` command for that, like:

    lxc console c1 --local 80:9090

Which means access to local port :80 will connect to port :9090 inside container.

**Comment by stgraber** [comment]
There's nothing in LXD which would let you do this today. The only tunnel you get with a container is exec or console, but both of those are fd based single connection type communication.

For HTTP to work properly, you'd need multi-threaded communications (multiple simultaneous requests).

The only thing I can think of that may work over the normal exec/console communication would be to run a good old serial modem over it, think ppp/slip type communication, then establish a network connection over that, but it's going to be pretty tricky to do, not to mention slow.

**Comment by stgraber** [comment]
Closing as this isn't something that LXD is meant to do, at least for now.

**Comment by techtonik** [comment]
How does SSH port forwarding works? It uses the same connection for everything, right?

Is there any command in LXD that uses one connection with two streams of data simultaneously?
