### ISSUE TITLE
GPU: Installing a run file of Nvidia driver inside LXC container fails

### ISSUE THREAD

**Issue by siteshbehera** [lxc/lxd#5415]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-141-generic
   * LXC version: 3.9
   * LXD version: 3.9
   * Storage backend in use: zfs

# Issue description

When I try installing the Nvidia driver using run file, I am getting the following error.

ERROR: An NVIDIA kernel module 'nvidia-uvm' appears to already be loaded in your kernel.  This may be because it is in use (for example, by an X       
         server, a CUDA program, or the NVIDIA Persistence Daemon), but this may also happen if your kernel was configured without support for module    
         unloading.  Please be sure to exit any programs that may be using the GPU(s) before attempting to upgrade your driver.  If no GPU-based         
         programs are running, you know that your kernel supports module unloading, and you still receive this message, then an error may have occured   
         that has corrupted an NVIDIA kernel module's usage count, for which the simplest remedy is to reboot your computer.

# Steps to reproduce

Installed Nvidia driver 390.48 using run file in hypervisor. 
Installed cuda 9.0 using run file in hypervisor.

Spawned LXC container, and trying to do the same process, but getting error.

When I try using apt install cuda=9.0.176-1, i can see both driver and api version mismatch, as apt will not allow installing only cuda lib. It will install driver also, which is of different version.

So now, installing separate driver and lib installion doesn't help in LXC container. 

When i checked /proc/driver/nvidia/verions, i can see:

cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  390.48  Thu Mar 22 00:42:57 PDT 2018
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 

So though only cuda lib installation should help as driver is already visible. But after installing cuda lib, i can see no result for nvidia-smi:

~nvidia-smi
nvidia-smi: command not found

Clueless now, please help.

Further question:

How can we have multiple versions of driver & cuda installed across different containers? I believe, today we are forced to have same version in hypervisor, and all lxc containers. Please clarify if I am wrong.

**Comment by stgraber** [comment]
NVIDIA requires you have the same version of the driver packages in the host and in containers.


You can have LXD pass those through for you, avoiding the need for the driver install by setting nvidia.runtime to true and possibly tweaking the other NVIDIA configuration keys.

lxd.readthedocs.io/en/latest/containers
