### ISSUE TITLE
Does not work date and time in LXD container

### ISSUE THREAD

**Issue by Piduna** [lxc/lxd#5417]
Hello, i have LXD 3.9, that was installed from SNAP package. I am using LVM storage driver. Everything is ok, but i can't resolve issue with time. Look please, this is my host system time:

```
root@vm-ubuntu1804-lxd:~# date
Thu Jan 17 10:16:48 EET 2019
```

When, i am trying to connect to container via `exec` command, i see this:

```
root@vm-ubuntu1804-lxd:~# lxc exec my-centos3 -- bash
[root@my-centos3 ~]# date
Thu Jan 17 08:18:07 UTC 2019
[root@my-centos3 ~]#
```

Ok, no problem, i can do it manually

`root@vm-ubuntu1804-lxd:~# lxc config set my-centos3 environment.TZ EET`

And, i have gone to see on result

```
root@vm-ubuntu1804-lxd:~# lxc exec my-centos3 -- bash
[root@my-centos3 ~]# date
Thu Jan 17 10:25:54 EET 2019
```

It look like ok. But, let's go to connect to container via ssh

```
login as: root
root@192.168.14.163's password:
Last login: Thu Jan 17 08:23:53 2019 from 192.168.14.178
[root@my-centos3 ~]# date
Thu Jan 17 08:26:56 UTC 2019
[root@my-centos3 ~]#
```

Why it shows time, what i want via `exec` normally, but via ssh not normal ?

**Comment by stgraber** [comment]
That's normal, the environment variable you set only applies to the init process of the container and anything that LXD itself spawns.

In your case, the init process strips that env variable and so it doesn't affect SSH.

Your best bet here is simply to make sure that /etc/localtime is a symlink to the right file under /usr/share/zoneinfo/ and /etc/timezone also contains your timezone's name.

Some of this can be configured through systems like cloud-init.
