### ISSUE TITLE
CEPH custom volumes cross-host issues

### ISSUE THREAD

**Issue by Spunge** [lxc/lxd#5421]
# information

Ubuntu 18.04.1 LTS
```
config:
  cluster.https_address: 10.254.0.5:8443
  core.https_address: 10.254.0.5:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.254.0.5:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    removed for brevity
    -----END CERTIFICATE-----
  certificate_fingerprint: 2f568344e52fa6cfe94346aa7babbc090c75ca09b05958219e60f9c39ef7c488
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-39-generic
  server: lxd
  server_pid: 76853
  server_version: "3.9"
  storage: ceph | zfs
  storage_version: ceph version 10.2.11 (e4b061b47f07f583c92a050d9e84b1813a35671e)
    | 0.7.5-1ubuntu16.4
  server_clustered: true
  server_name: host-0003
  project: default
```

# Issue description
I get the following error when trying to attach a ceph storage volume to a container that resides on a host in the cluster that differs from the one the storage volume was created on:

```Error: Add disk devices: Failed to setup device: Failed to initialize storage volume "test" of type "custom" on storage pool "ceph": no such file or directory```

When not passing a target cluster member as a target, the cluster will decide what host to put a new container on. When the cluster decides to put a container on another host in the cluster, this error occurs.

I thought this would have to do with the volume being mapped on the host that was used to create it and be the exact same issue as #5422, but after `rbd unmap lxd/custom_test` the problem persisted.

Am i supposed to keep track of cluster hosts myself and always pass a target?

# Steps to reproduce

 1. Create storage volume on ceph pool `lxc storage volume create ceph test`
 2. Create container on different host `lxc launch ubuntu: test --target=other-host`
 3. Attach volume to container `lxc storage volume attach ceph test test /mnt`

# Information to attach

The `lxc info test --show-log` shows the following. Is this related?
```
lxc test 20190118132533.714 WARN     conf - conf.c:lxc_setup_devpts:1641 - Invalid argument - Failed to unmount old devpts instance
```

**Comment by Spunge** [comment]
I was able to mount the volume on other hosts after creating the directory myself:
```
mkdir -m 0711 /var/snap/lxd/common/lxd/storage-pools/ceph/custom/test
```

**Comment by stgraber** [comment]
For custom storage volumes on CEPH, we must make sure that:
 - On creation, we temporarily map, format and unmount the rbd volume
 - On attach, if not already mapped and mounted, we do that, along with creating the needed path on disk
 - On delete, we notify all hosts about it so they can clean things up

We already have a check in place to prevent mapping cross-host so that part should be fine, but we want to make sure we don't have the rbd volume mapped on the host that created it unless it's also used there and we need to make sure we create relevant paths when needed and do cluster-wide cleanup on delete.

**Comment by stgraber** [comment]
I'll try to take a look at this myself since I've got a reproducing environment for this but I'll be travelling tomorrow so it may take a little while before I get to that.
