### ISSUE TITLE
LXD-P2C does not copy the www folder

### ISSUE THREAD

**Issue by Fecro** [lxc/lxd#5424]
The `lxd-p2c` command omits the `/var/www/` folder. To try to avoid this error (I do not know if it is an error) I put the parameter `--rsync-args="--include=/var/www"`, but it had no effect.

Is it a default configuration or is it an error?

**Comment by stgraber** [comment]
Is it on a separate mountpoint? If so, it needs to be passed as a separate argument.

**Comment by Fecro** [comment]
> Is it on a separate mountpoint? If so, it needs to be passed as a separate argument.

Yes, you're right! Thanks, now. How do I copy it to the same container? using lxc-p2c?

**Comment by stgraber** [comment]
```
Usage:
  lxd-p2c <target URL> <container name> <filesystem root> [<filesystem mounts>...] [flags]
```

So you can just pass it: `lxd-p2c URL NAME / /var/www`
