### ISSUE TITLE
libcublas.so.9.0 and other extra libraries missing after nvidia.runtime is set to true

### ISSUE THREAD

**Issue by siteshbehera** [lxc/lxd#5426]
# Required information

 * Distribution:
 * 3.9
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.4.0-141-generic
   * LXC version: 
   * LXD version: 3.9
   * Storage backend in use: zfs

# Issue description

Following are the lxc configs we have set for nvidia:

 nvidia.require.cuda: "true"
 nvidia.require.driver: "true"
 nvidia.runtime: "true"

After installing tensorflow-gpu, when we run a test to verify installation, we get following error:

ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

On container :
root@B005AML7212249:~# ls -l /usr/lib/x86_64-linux-gnu/libc*
-rw-r--r-- 1 root   root     5046072 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libc.a
-rw-r--r-- 1 root   root         298 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libc.so
-rw-r--r-- 1 root   root       21764 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libc_nonshared.a
lrwxrwxrwx 1 root   root          18 Oct 23  2015 /usr/lib/x86_64-linux-gnu/libcap-ng.so.0 -> libcap-ng.so.0.0.0
-rw-r--r-- 1 root   root       18776 Oct 23  2015 /usr/lib/x86_64-linux-gnu/libcap-ng.so.0.0.0
lrwxrwxrwx 1 root   root          15 Aug 27 21:15 /usr/lib/x86_64-linux-gnu/libcc1.so.0 -> libcc1.so.0.0.0
-rw-r--r-- 1 root   root       93040 Aug 27 21:50 /usr/lib/x86_64-linux-gnu/libcc1.so.0.0.0
lrwxrwxrwx 1 root   root          34 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libcidn.so -> /lib/x86_64-linux-gnu/libcidn.so.1
lrwxrwxrwx 1 root   root          19 Aug 27 21:15 /usr/lib/x86_64-linux-gnu/libcilkrts.so.5 -> libcilkrts.so.5.0.0
-rw-r--r-- 1 root   root      114696 Aug 27 21:42 /usr/lib/x86_64-linux-gnu/libcilkrts.so.5.0.0
-rw-r--r-- 1 root   root       60572 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libcrypt.a
lrwxrwxrwx 1 root   root          35 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libcrypt.so -> /lib/x86_64-linux-gnu/libcrypt.so.1
lrwxrwxrwx 1 root   root          12 Jan 18 19:39 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root   root          17 Jan 18 19:39 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.390.48
-rwxr-xr-x 2 nobody nogroup 10033592 Jan 18 18:44 /usr/lib/x86_64-linux-gnu/libcuda.so.390.48
lrwxrwxrwx 1 root   root          19 Oct 29 16:01 /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.3 -> libcurl-gnutls.so.4
lrwxrwxrwx 1 root   root          23 Oct 29 16:01 /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 -> libcurl-gnutls.so.4.4.0
-rw-r--r-- 1 root   root      444800 Oct 29 16:01 /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.4.0
root@B005AML7212249:~# 

On hypervisor:

root@blr1p01-gpu:/home/infra# ls -l /usr/lib/x86_64-linux-gnu/libc*
-rw-r--r-- 1 root root   5046072 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libc.a
lrwxrwxrwx 1 root root        18 Oct 24  2015 /usr/lib/x86_64-linux-gnu/libcap-ng.so.0 -> libcap-ng.so.0.0.0
-rw-r--r-- 1 root root     18776 Oct 24  2015 /usr/lib/x86_64-linux-gnu/libcap-ng.so.0.0.0
lrwxrwxrwx 1 root root        15 Aug 28 02:45 /usr/lib/x86_64-linux-gnu/libcc1.so.0 -> libcc1.so.0.0.0
-rw-r--r-- 1 root root     93040 Aug 28 03:20 /usr/lib/x86_64-linux-gnu/libcc1.so.0.0.0
lrwxrwxrwx 1 root root        34 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libcidn.so -> /lib/x86_64-linux-gnu/libcidn.so.1
lrwxrwxrwx 1 root root        19 Aug 28 02:45 /usr/lib/x86_64-linux-gnu/libcilkrts.so.5 -> libcilkrts.so.5.0.0
-rw-r--r-- 1 root root    114696 Aug 28 03:12 /usr/lib/x86_64-linux-gnu/libcilkrts.so.5.0.0
-rw-r--r-- 1 root root     21764 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libc_nonshared.a
-rw-r--r-- 1 root root     60572 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libcrypt.a
lrwxrwxrwx 1 root root        35 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libcrypt.so -> /lib/x86_64-linux-gnu/libcrypt.so.1
-rw-r--r-- 1 root root       298 Jan 15  2018 /usr/lib/x86_64-linux-gnu/libc.so
lrwxrwxrwx 1 root root        55 Jan 21 15:48 /usr/lib/x86_64-linux-gnu/libcublas.so.9.0 -> /usr/local/cuda-9.0/extras/CUPTI/lib64/libcublas.so.9.0
lrwxrwxrwx 1 root root        12 Jan 19 00:14 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root        17 Jan 19 00:14 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.390.48
-rwxr-xr-x 2 root root  10033592 Jan 19 00:14 /usr/lib/x86_64-linux-gnu/libcuda.so.390.48
lrwxrwxrwx 1 root root        29 Jan 19 00:25 /usr/lib/x86_64-linux-gnu/libcudnn.so -> /etc/alternatives/libcudnn_so
lrwxrwxrwx 1 root root        17 Nov  2 12:25 /usr/lib/x86_64-linux-gnu/libcudnn.so.7 -> libcudnn.so.7.4.1
-rw-r--r-- 1 root root 305352592 Nov  2 12:25 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1
lrwxrwxrwx 1 root root        32 Jan 19 00:25 /usr/lib/x86_64-linux-gnu/libcudnn_static.a -> /etc/alternatives/libcudnn_stlib
-rw-r--r-- 1 root root 316941798 Nov  2 12:25 /usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
lrwxrwxrwx 1 root root        54 Jan 21 15:06 /usr/lib/x86_64-linux-gnu/libcupti.so.9.0 -> /usr/local/cuda-9.0/extras/CUPTI/lib64/libcupti.so.9.0

Please guide how to get extra libraries inside the container.

**Comment by stgraber** [comment]
Closing as what's passed is decided by nvidia-container and not by LXD itself.

You may want to play with the `nvidia.driver.capabilities` configuration key to control what gets exposed to your container, it defaults to `compute,utility` which may be too limiting in your case.

**Comment by stgraber** [comment]
https://github.com/NVIDIA/nvidia-container-runtime#possible-values-1
