### ISSUE TITLE
Filter internal cluster storage keys

### ISSUE THREAD

**Issue by syswipe** [lxc/lxd#5427]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.0.5
 * The output of "lxc info":

> config:
>   cluster.https_address: cl-node-3:8443
>   core.https_address: cl-node-3:8443
> api_extensions:
> - storage_zfs_remove_snapshots
> - container_host_shutdown_timeout
> - container_stop_priority
> - container_syscall_filtering
> - auth_pki
> - container_last_used_at
> - etag
> - patch
> - usb_devices
> - https_allowed_credentials
> - image_compression_algorithm
> - directory_manipulation
> - container_cpu_time
> - storage_zfs_use_refquota
> - storage_lvm_mount_options
> - network
> - profile_usedby
> - container_push
> - container_exec_recording
> - certificate_update
> - container_exec_signal_handling
> - gpu_devices
> - container_image_properties
> - migration_progress
> - id_map
> - network_firewall_filtering
> - network_routes
> - storage
> - file_delete
> - file_append
> - network_dhcp_expiry
> - storage_lvm_vg_rename
> - storage_lvm_thinpool_rename
> - network_vlan
> - image_create_aliases
> - container_stateless_copy
> - container_only_migration
> - storage_zfs_clone_copy
> - unix_device_rename
> - storage_lvm_use_thinpool
> - storage_rsync_bwlimit
> - network_vxlan_interface
> - storage_btrfs_mount_options
> - entity_description
> - image_force_refresh
> - storage_lvm_lv_resizing
> - id_map_base
> - file_symlinks
> - container_push_target
> - network_vlan_physical
> - storage_images_delete
> - container_edit_metadata
> - container_snapshot_stateful_migration
> - storage_driver_ceph
> - storage_ceph_user_name
> - resource_limits
> - storage_volatile_initial_source
> - storage_ceph_force_osd_reuse
> - storage_block_filesystem_btrfs
> - resources
> - kernel_limits
> - storage_api_volume_rename
> - macaroon_authentication
> - network_sriov
> - console
> - restrict_devlxd
> - migration_pre_copy
> - infiniband
> - maas_network
> - devlxd_events
> - proxy
> - network_dhcp_gateway
> - file_get_symlink
> - network_leases
> - unix_device_hotplug
> - storage_api_local_volume_handling
> - operation_description
> - clustering
> - event_lifecycle
> - storage_api_remote_volume_handling
> - nvidia_runtime
> - container_mount_propagation
> - container_backup
> - devlxd_images
> - container_local_cross_pool_handling
> - proxy_unix
> - proxy_udp
> - clustering_join
> - proxy_tcp_udp_multi_port_handling
> - network_state
> - proxy_unix_dac_properties
> - container_protection_delete
> - unix_priv_drop
> - pprof_http
> - proxy_haproxy_protocol
> - network_hwaddr
> - proxy_nat
> - network_nat_order
> - container_full
> - candid_authentication
> - backup_compression
> - candid_config
> - nvidia_runtime_config
> - storage_api_volume_snapshots
> - storage_unmapped
> - projects
> - candid_config_key
> - network_vxlan_ttl
> - container_incremental_copy
> - usb_optional_vendorid
> - snapshot_scheduling
> - container_copy_project
> - clustering_server_address
> - clustering_image_replication
> - container_protection_shift
> api_status: stable
> api_version: "1.0"
> auth: trusted
> public: false
> auth_methods:
> - tls
> environment:
>   addresses:
>   - cl-node-3:8443
>   architectures:
>   - x86_64
>   - i686
>   certificate: |
>     -----BEGIN CERTIFICATE-----
>     MIIB9zCCAX2gAwIBAgIQZugD6yuABQ49uKtrFvHkFzAKBggqhkjOPQQDAzA0MRww
>     GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QG5vZGUt
>     MzAeFw0xOTAxMjExNzAwMThaFw0yOTAxMTgxNzAwMThaMDQxHDAaBgNVBAoTE2xp
>     bnV4Y29udGFpbmVycy5vcmcxFDASBgNVBAMMC3Jvb3RAbm9kZS0zMHYwEAYHKoZI
>     zj0CAQYFK4EEACIDYgAEoDNfBv64pFZmFilJbDe5ZGpIDt7vEMLSR2ChhYZCF4w3
>     VmHn4Y67jnkG0JGH2KSv9CbWG2FkXNgUCYUXZbgUYbSMPk1e3J6CiCVzxhRPb9qh
>     RI87vN8HaTgbHRKfXbVfo1QwUjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYI
>     KwYBBQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHREEFjAUggZub2RlLTOHBFu9fSeH
>     BAoAAB4wCgYIKoZIzj0EAwMDaAAwZQIwAJJChFlnQ3Uuvjnuf+KT8ylBklgzyaOL
>     wk7nnSWCjIi8MNjkuer447Ol8aWfiTzwAjEArUEryYDsfDE/tL4hjByf/S+bDmys
>     u5vhfeuA8r/uE+h6UWdYSmpK5gRRQpEYps75
>     -----END CERTIFICATE-----
>   certificate_fingerprint: 215ab70a67efb26051458198d95f90b8957bcbfc90fcc9bab06e915e1e0098c5
>   driver: lxc
>   driver_version: 3.1.0
>   kernel: Linux
>   kernel_architecture: x86_64
>   kernel_version: 4.4.0-141-generic
>   server: lxd
>   server_pid: 13800
>   server_version: "3.9"
>   storage: ""
>   storage_version: ""
>   server_clustered: false
>   server_name: node-3
>   project: default
> 

# Issue description

I tired to join newly installed node to existing LXD cluster using preseed file from bootstrap node. But LXD can't create storage pool:

> # cat cluster.yaml | lxd init --preseed
> Error: Failed to join cluster: Failed to initialize member: Failed to initialize storage pools and networks: Failed to create storage pool 'local': the requested volume group "local" does not exist

May i create networks or storage pool manually? I think that LXD init has to be create storage pools by himself?

# Steps to reproduce

 1. lxc snap install 
 2. cat cluster.yaml | lxd init --preseed

Cluster.yaml was saved from bootstrap server, i replaced only node names:

> config: {}
> networks: []
> storage_pools: []
> profiles: []
> cluster:
>   server_name: cl-node-3
>   enabled: true
>   member_config:
>   - entity: storage-pool
>     name: local
>     key: volatile.initial_source
>     value: /dev/sdb
>     description: '"volatile.initial_source" property for storage pool "local"'
>   - entity: storage-pool
>     name: local
>     key: lvm.thinpool_name
>     value: LXDThinPool
>     description: '"lvm.thinpool_name" property for storage pool "local"'
>   - entity: storage-pool
>     name: local
>     key: lvm.vg_name
>     value: local
>     description: '"lvm.vg_name" property for storage pool "local"'
>   - entity: storage-pool
>     name: local
>     key: source
>     value: local
>     description: '"source" property for storage pool "local"'
>   cluster_address: 10.0.0.10:8443
>   cluster_certificate: |
>     -----BEGIN CERTIFICATE-----
>     MIIFUzCCAzugAwIBAgIRAKa2GJpBtESWVBUr/5QftiAwDQYJKoZIhvcNAQELBQAw
>     NjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEBq
>     b2JwdWx6MTAeFw0xODA2MjAxNDI4NDlaFw0yODA2MTcxNDI4NDlaMDYxHDAaBgNV
>     BAoTE2xpbnV4Y29udGFpbmVycy5vcmcxFjAUBgNVBAMMDXJvb3RAam9icHVsejEw
>     ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDGH57cSdm2CTCUsoR+N9Y3
>     JNWoXFKmcGa4F4/ZM1IyhzK7ZpWesXNPw1llmKoeUIzt6041XwOR3tk/pU95WDha
>     ZXD2ilNiP8ws/5mHWTgfy/56SNbLZIJe6/WfIl9E7eCZewYjCg5XVWw6l+FMzFJk
>     E11k6cPsbkIiUMBRzi/3OsfgoBTe34YO5yN7cTi9Y/EtSuCiY2Xav8TTRZ0w4jf3
>     FjUyUKNe8+2oQQXgZRypE9o3tjKtP8tAUq3IS3beasin+K0s7fHTrCvHJijFc2gV
>     s9jMU+e4HM+o97jsgxHpIpJTA9LUe5bJNvCgLEOX9MmkReyZjBqE5GVzrj3hE+he
>     ByAoPN+D8x8AOagNFYPWsprXnvlUgVAxYqzBw5mUT2yzo3iQ+ECiyYic+U++KFSt
>     9MRjp0k53uxoB23DqtFc/boM1A4/BerLm/CxiBMP5cYUJc5IC9x1yQXU+j/TgwfN
>     dVejyFAYXgn/rbUO8xKTzvNQ3UcDp+3c0hmzZTursTdjmUJISGChltxmr3HefJqs
>     V6dbi0XBSVbO9wYjj4CUBPqAEZ6zT6uxkb1V9NyXM0i1tsyV3CFBIu/8aHt947yZ
>     XLhZDP5A6BUCP+itt1LTf2ETVBc3dh76XSv7M6jFbb1xfjUJ4RFPuX9yyr1wC2xh
>     RXgD/rNoTwwi3qrUqwp/awIDAQABo1wwWjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0l
>     BAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAlBgNVHREEHjAcgghqb2JwdWx6
>     MYcEW719IocECgAAFIcECgAACjANBgkqhkiG9w0BAQsFAAOCAgEAV3M3/lM88wwf
>     nAoZJfp8y3jJG8lk418aZT6Ki3BL6//I2ldslgkEcXMAPc7ovr+Xy9AhbMvdOc6h
>     oiiDG8njrgaoHBp5LascU5b5F9heQo47BpWM+UOB7jtp1/r4O4E6yichB9wElwrs
>     M2op9AnG2CcnqNKW3XTbdWY7eEuwbml3mjGuUJBKGV29qwT9G8+q2/PB1R+7SnTm
>     f5gISCYkwiPlixGqRQh0kX63djN2SCqNy5lzDJDRQS07qtHULcmrNEHxf/wt7P1Y
>     rtIjBqr1sS2qT04VtQxApsKhlBvouhWYJjhrbj6SaiMv1R5zSUOv73VdICHawnN8
>     wosM7RlL4f8jVFc/daIWe8SIqjObUbYXDF5y74v0xM8bSS7ZbQYN61J8Tr+Sfhxk
>     H4dDHIQEPKNJ0tauGnU4ZCs/8htGjoVpiN8E9T8DTuetfOpJno2np1PIDMGJ1dKs
>     GvWZS398O/dV8bgwh5n4PJaz9TeosqqFmYv9fxu3f73oFDyWvN83QSbACU+H1P4p
>     9g75ktTUq13SMztyxO2x7BTm4MsTmo4m7AAnH93I+VVJU0aMdnM9TBcDra8r8GC+
>     rDwjqPFjso66d/F3iRcXUCgFrK1NEswFcirOT6ts2b6f039gFZ1/Dp6Ync/r6LOJ
>     9rcXw9i4lanGNXaHoOnVdOcSoipsf9E=
>     -----END CERTIFICATE-----
>   server_address: cl-node-3:8443
>   cluster_password: secretpassword

**Comment by freeekanayaka** [comment]
The ```cluster.yaml``` definition you are using might be incorrect.

I'm not very familiar with the LVM backend, but I'd be a bit surprised if you need to specify "private" config keys such as ```volatile.initial_source```. Perhaps @stgraber can help spotting what's wrong.

Alternatively, there might be a bug that prevents correctly handling this configuration.

**Comment by stgraber** [comment]
yeah, would be good to retry without that volatile key

**Comment by syswipe** [comment]
Ok, i removed section with volatile.inital_source:

> root@node-3:~# cat cluster.yaml | lxd init --preseed
> Error: Failed to join cluster: Failed to initialize member: Failed to initialize storage pools and networks: >Failed to create storage pool 'local': the requested volume group "local" does not exist

 well, let's create it

> root@node-3:~# vgcreate local /dev/sdb
>   Physical volume "/dev/sdb" successfully created
>   Volume group "local" successfully created
> root@node-3:~# snap remove lxd
> lxd removed
> root@node-3:~# snap install lxd
> lxd 3.9 from Canonical✓ installed
> root@node-3:~# cat cluster.yaml | lxd init --preseed
> Error: Failed to join cluster: Failed to initialize member: Failed to initialize storage pools and networks: > Failed to create storage pool 'local': LXD already uses volume group "local" for pool "local"
still no success :(

**Comment by stgraber** [comment]
Oh, sounds like your server got partially configured, including creation of that storage pool...

`lxc storage list` would confirm and `lxc storage delete local` should reset things.

**Comment by syswipe** [comment]
i tried this but obtained the next
```
root@node-3:~$ lxc storage list
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:18.04

+------+-------------+--------+--------+---------+
| NAME | DESCRIPTION | DRIVER | SOURCE | USED BY |
+------+-------------+--------+--------+---------+
at@node-3:~$ lxc storage delete local
Error: No such object
```
at the same time if i try to lauch lxd init again, server says:
```
root@node-3:~# cat cluster.yaml | lxd init --preseed
Error: Failed to join cluster: This server is already clustered
```
but lxc info shows:
``  server_clustered: false
``

**Comment by freeekanayaka** [comment]
The very last error that you get (```Error: Failed to join cluster: This server is already clustered```), might be a bug: some state is not properly reverted after a failed attempt to join a cluster. I'll check this. In order to revert the state manually, please run:

```
lxd sql node "DELETE FROM config WHERE key='cluster.https_address'"
```

**Comment by syswipe** [comment]
I can completely remove lxd and reinstall it, but result will be the same:
when VG local is not present - lxd init says 

> "Error: Failed to join cluster: Failed to initialize member: Failed to initialize storage pools and networks: Failed to create storage pool 'local': the requested volume group "local" does not exist"

When i create one, than i obtain:

> Error: Failed to join cluster: Failed to initialize member: Failed to initialize storage pools and networks: > Failed to create storage pool 'local': LXD already uses volume group "local" for pool "local"
```
storage pool section in preseed file now contains only:
storage_pools:
- config:
    lvm.thinpool_name: LXDThinPool
    lvm.vg_name: local
    source: local
  description: ""
  name: local
  driver: lvm

```

**Comment by stgraber** [comment]
What happens if you use this YAML?

```
storage_pools:
- config:
    source: /dev/vdb
  description: ""
  name: local
  driver: lvm
```

That's the input I'd expect to be needed to tell it to create a LVM pool called `local` using `/dev/vdb` as the source device.

**Comment by freeekanayaka** [comment]
Note that if we are talking about joining a node to a cluster (vs configuring a standalone node, or the very first node of a cluster), you'll have to use the ```member_config``` method, not ```storage_pools```.
