### ISSUE TITLE
sudo required for init command

### ISSUE THREAD

**Issue by pmatulis** [lxc/lxd#5428]
* Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-1031-aws
   * LXC version: 3.9
   * LXD version: 3.9
   * Storage backend in use: Dunno

# Issue description

I need to prepend `lxd init` with `sudo` in order for it to run. This wasn't the case in previous versions. 

# Steps to reproduce

```
$ lxd init
Error: Failed to connect to local LXD: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: permission denied
```

Compared to

```
$ sudo lxd init
Would you like to use LXD clustering? (yes/no) [default=no]:
```

**Comment by stgraber** [comment]
You're likely not in the lxd group which would explain the error.

**Comment by stgraber** [comment]
```
ubuntu@lantea:~$ ls -lh /var/snap/lxd/common/lxd/unix.socket
srw-rw---- 1 root lxd 0 Jan 18 16:29 /var/snap/lxd/common/lxd/unix.socket
ubuntu@lantea:~$ groups
ubuntu adm dialout cdrom floppy sudo audio dip video plugdev lxd netdev
ubuntu@lantea:~$ lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: 
Do you want to configure a new storage pool? (yes/no) [default=yes]: ^C
ubuntu@lantea:~$ 
```

This confirms that the socket ownership with the snap is correct and that if your user is part of the group, `lxd init` does work as expected.

**Comment by stgraber** [comment]
Using sudo as a way around the missing group membership is perfectly fine, at the end of the day, you're just talking over a REST API, doesn't matter who you're doing that as.
