### ISSUE TITLE
Lxc import - error: not found

### ISSUE THREAD

**Issue by monstermunchkin** [lxc/lxd#5446]
https://discuss.linuxcontainers.org/t/lxc-import-error-not-found/3927

What we need is:
* Clear error when the storage pool can’t be found during restore
* Option to lxc import to override the storage pool, so one can do -s blah at import time

**Comment by angristan** [comment]
Re-posting my comment here in case people stumble upon this issue:

To import a backup that was made on a different storage pool:

In `backup.tar.gz/index.yml`, modify:
- `backend` _(if the pool type is different)_
- `pool`

In `backup.tar.gz/container/backup.yml`, modify:
- `pool.driver` _(if the pool type is different)_
- `container.expanded_devices.root.pool`
- `pool.config.source`
- `pool.name`

**Comment by angristan** [comment]
#5506 completely fixed this. Thanks @monstermunchkin !
