### ISSUE TITLE
lxd won't start after upgrade

### ISSUE THREAD

**Issue by erdelyijanos** [lxc/lxd#5456]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.18.0-14-generic
   * LXC version: 3.9
   * LXD version: 3.9
   * Storage backend in use:btrfs

# Issue description
After upgrading to lxd 3.9 which is only available as snap the lxd daemon won't start.

# Steps to reproduce

sudo lxd --debug --group lxd

INFO[02-01|20:17:02] LXD 3.9 is starting in normal mode       path=/var/snap/lxd/common/lxd
EROR[02-01|20:17:02] Failed to start the daemon: failed to init dir /var/snap/lxd/common/lxd/backups: mkdir /var/snap/lxd/common/lxd/backups: read-only file system 
INFO[02-01|20:17:02] Starting shutdown sequence 
DBUG[02-01|20:17:02] Not unmounting temporary filesystems (containers are still running) 
INFO[02-01|20:17:02] Saving simplestreams cache 
INFO[02-01|20:17:02] Saved simplestreams cache 
EROR[02-01|20:17:02] Failed to cleanly shutdown daemon: open /var/snap/lxd/common/lxd/cache/simplestreams.yaml: no such file or directory 
Error: failed to init dir /var/snap/lxd/common/lxd/backups: mkdir /var/snap/lxd/common/lxd/backups: read-only file system

**Comment by stgraber** [comment]
Suggests some filesystem problem as it says that `/var/snap/lxd/common/lxd` is read-only on your system.

Can you show `cat /proc/self/mountinfo`?

**Comment by erdelyijanos** [comment]
Hi, thanks for the quick reply

actually that directory in a symlink to another directory (/srv) where the containers are located. It is not read only.

sudo cat /proc/self/mountinfo
22 27 0:21 / /sys rw,nosuid,nodev,noexec,relatime shared:7 - sysfs sysfs rw
23 27 0:4 / /proc rw,nosuid,nodev,noexec,relatime shared:15 - proc proc rw
24 27 0:6 / /dev rw,nosuid,relatime shared:2 - devtmpfs udev rw,size=31980948k,nr_inodes=7995237,mode=755
25 24 0:22 / /dev/pts rw,nosuid,noexec,relatime shared:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
26 27 0:23 / /run rw,nosuid,noexec,relatime shared:5 - tmpfs tmpfs rw,size=6401040k,mode=755
27 0 0:24 /@ / rw,noatime,nodiratime shared:1 - btrfs /dev/sdc2 rw,compress=zlib:3,ssd,space_cache,subvolid=257,subvol=/@
28 22 0:7 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:8 - securityfs securityfs rw
29 24 0:27 / /dev/shm rw,nosuid,nodev shared:4 - tmpfs tmpfs rw
30 26 0:28 / /run/lock rw,nosuid,nodev,noexec,relatime shared:6 - tmpfs tmpfs rw,size=5120k
31 22 0:29 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:9 - tmpfs tmpfs ro,mode=755
32 31 0:30 / /sys/fs/cgroup/unified rw,nosuid,nodev,noexec,relatime shared:10 - cgroup2 cgroup2 rw
33 31 0:31 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:11 - cgroup cgroup rw,xattr,name=systemd
34 22 0:32 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:12 - pstore pstore rw
35 22 0:33 / /sys/firmware/efi/efivars rw,nosuid,nodev,noexec,relatime shared:13 - efivarfs efivarfs rw
36 22 0:34 / /sys/fs/bpf rw,nosuid,nodev,noexec,relatime shared:14 - bpf bpf rw,mode=700
37 31 0:35 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,blkio
38 31 0:36 / /sys/fs/cgroup/rdma rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,rdma
39 31 0:37 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,devices
40 31 0:38 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,cpu,cpuacct
41 31 0:39 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,hugetlb
42 31 0:40 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,net_cls,net_prio
43 31 0:41 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,perf_event
44 31 0:42 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:23 - cgroup cgroup rw,pids
45 31 0:43 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:24 - cgroup cgroup rw,freezer
46 31 0:44 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:25 - cgroup cgroup rw,memory
47 31 0:45 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:26 - cgroup cgroup rw,cpuset
48 23 0:46 / /proc/sys/fs/binfmt_misc rw,relatime shared:27 - autofs systemd-1 rw,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=13874
49 24 0:47 / /dev/hugepages rw,relatime shared:28 - hugetlbfs hugetlbfs rw,pagesize=2M
50 22 0:8 / /sys/kernel/debug rw,relatime shared:29 - debugfs debugfs rw
51 24 0:19 / /dev/mqueue rw,relatime shared:30 - mqueue mqueue rw
52 50 0:11 / /sys/kernel/debug/tracing rw,relatime shared:31 - tracefs tracefs rw
53 22 0:20 / /sys/kernel/config rw,relatime shared:32 - configfs configfs rw
54 22 0:49 / /sys/fs/fuse/connections rw,relatime shared:33 - fusectl fusectl rw
124 27 7:0 / /snap/lxd/9919 ro,nodev,relatime shared:67 - squashfs /dev/loop0 ro
131 27 7:1 / /snap/core/6350 ro,nodev,relatime shared:69 - squashfs /dev/loop1 ro
127 27 0:24 /@home /home rw,noatime,nodiratime shared:71 - btrfs /dev/sdc2 rw,compress=zlib:3,ssd,space_cache,subvolid=258,subvol=/@home
129 27 0:53 / /srv rw,noatime,nodiratime shared:73 - btrfs /dev/sdd1 rw,compress=zlib:3,ssd,space_cache,subvolid=5,subvol=/
134 27 8:33 / /boot/efi rw,relatime shared:75 - vfat /dev/sdc1 rw,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro
122 27 0:52 / /data rw,noatime,nodiratime shared:77 - btrfs /dev/sda rw,compress=zlib:3,space_cache,autodefrag,subvolid=5,subvol=/
339 27 0:63 / /var/lib/lxcfs rw,nosuid,nodev,relatime shared:197 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
328 26 0:23 /snapd/ns /run/snapd/ns rw,nosuid,noexec,relatime - tmpfs tmpfs rw,size=6401040k,mode=755
358 328 0:3 mnt:[4026532312] /run/snapd/ns/lxd.mnt rw - nsfs nsfs rw
359 26 0:141 / /run/user/1000 rw,nosuid,nodev,relatime shared:204 - tmpfs tmpfs rw,size=6401040k,mode=700,uid=1000,gid=1000

**Comment by stgraber** [comment]
Don't do symlinks in there, it's going to seriously mess up snapd and its confinement, causing such errors.
This is not a setup we can support.

Instead an alternative would be to setup a bind-mount of /srv to /var/snap/lxd/common/lxd which while not something we'd officially support and something you may still run into some corner case issues with, should still work much better in general.

For such setups, you'd also usually get a better chance of it working if you have all of /var/snap/lxd/common on that mountpoint rather than just the lxd directory within it, that's because otherwise you may run into cross-mount issues.

Closing as this is an unsupported setup, but hopefully the above gives you enough pointers to get something more robust in place.

**Comment by erdelyijanos** [comment]
Thanks, the bind-mount helped that issue.
Generally the upgrade from lxd version <3.0 to 3.9 caused some other issues as well.
I am still fightig to get all containers running. Some of them are ok, some just won't work anymore.

This issue is the id mapping.
There is one container which would not start. If I look into the "rootfs" of it from the host, all directories and files are with uid/gid from the host (like 0 for root etc.). The rootfs directory itself is uid/gid=1000000 everything below is like the id-s of the host.
I tried to change the id-s of all the files below "rootfs". I wrote a script that adds this offset to the uid/gid of all files.
I set security.idmap.isolated true and the base to 1000000. Once I start the container it changes back all uid/gid to the host's and won't run.
/etc/subuid, /etc/subgid are set correctly but it shouldn't matter after lxd > 3.0 as far as I know...

Now where else can I have a wrong setting that causes this to happen?

**Comment by stgraber** [comment]
The snap doesn't care about /etc/subuid and /etc/subgid, it's possible that in the middle of this, the container config got wrong.

If you have such containers, it's possible to get LXD to remap things properly by manually editing the `volatie.last_state.idmap` and `volatile.idmap.next`, setting the first to the way things are on the filesystem and the latter to the state you'd like things to be in. Upon startup, LXD will remap things for you.

We also have a `fuidshift` binary as part of the LXD code tree which can be used to manually remap whole filesystem trees though the other approach is certainly preferred.
