### ISSUE TITLE
Networking problems On VMware pinging between containers

### ISSUE THREAD

**Issue by gbonazzoli** [lxc/lxd#5464]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.1 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-45-generic
   * LXC version: 4.9 (via snap)
   * LXD version: 3.9 (via snap)
   * Storage backend in use: ZFS

I have a VMWARE 5.5 VM with Ubuntu 18.04.01.
On this VM I run several containers.

```
root@lxd02:~# lxc list
+-------------------+---------+-----------------------+------+------------+-----------+----------+
|       NAME        |  STATE  |         IPV4          | IPV6 |    TYPE    | SNAPSHOTS | LOCATION |
+-------------------+---------+-----------------------+------+------------+-----------+----------+
| srv-gitlab        | RUNNING | 192.168.213.14 (eth0) |      | PERSISTENT |           | lxd02    |
+-------------------+---------+-----------------------+------+------------+-----------+----------+
| srv-intranet      | RUNNING | 192.168.213.16 (eth0) |      | PERSISTENT |           | lxd02    |
+-------------------+---------+-----------------------+------+------------+-----------+----------+
| srv-kanboard      | RUNNING | 192.168.213.13 (eth0) |      | PERSISTENT |           | lxd02    |
+-------------------+---------+-----------------------+------+------------+-----------+----------+
| srv-mediawiki     | RUNNING | 192.168.213.12 (eth0) |      | PERSISTENT |           | lxd02    |
+-------------------+---------+-----------------------+------+------------+-----------+----------+
| srv-mediawiki-old | STOPPED |                       |      | PERSISTENT |           | lxd02    |
+-------------------+---------+-----------------------+------+------------+-----------+----------+
| srv-sql-server    | RUNNING | 192.168.213.11 (eth0) |      | PERSISTENT |           | lxd02    |
+-------------------+---------+-----------------------+------+------------+-----------+----------+
| test              | RUNNING | 192.168.213.17 (eth0) |      | PERSISTENT |           | lxd02    |
+-------------------+---------+-----------------------+------+------------+-----------+----------+
```

If I ping from one container another container running on the same LXD host I loose packets:

```
root@srv-sql-server:~# ping 192.168.213.16 
--- 192.168.213.16 ping statistics ---
82 packets transmitted, 73 received, 10% packet loss, time 82938ms
rtt min/avg/max/mdev = 0.025/0.032/0.050/0.008 ms
```
This is only the most incredible network problem, I have problem also in normal networking between containers and the rest of the world.

**Comment by stgraber** [comment]
Can you show:
 - lxc network list
 - lxc network show NAME (for any network in the list)
 - ifconfig -a
 - lxc config show test --expanded
 - dmesg

**Comment by gbonazzoli** [comment]
Here are the outputs of the commands you asked me.

**lxc network list**
`root@lxd02:~# lxc network list
+--------+----------+---------+-------------+---------+-------+
|  NAME  |   TYPE   | MANAGED | DESCRIPTION | USED BY | STATE |
+--------+----------+---------+-------------+---------+-------+
| br0    | bridge   | NO      |             | 7       |       |
+--------+----------+---------+-------------+---------+-------+
| ens160 | physical | NO      |             | 0       |       |
+--------+----------+---------+-------------+---------+-------+`

**lxc network show NAME (for any network in the list)**

`root@lxd02:~# lxc network show br0
config: {}
description: ""
name: br0
type: bridge
used_by:
- /1.0/containers/srv-gitlab
- /1.0/containers/srv-intranet
- /1.0/containers/srv-kanboard
- /1.0/containers/srv-mediawiki
- /1.0/containers/srv-mediawiki-old
- /1.0/containers/srv-sql-server
- /1.0/containers/test
managed: false
status: ""
locations: []
root@lxd02:~# lxc network show ens160
config: {}
description: ""
name: ens160
type: physical
used_by: []
managed: false
status: ""
locations: []`

**ifconfig -a**

`root@lxd02:~# ifconfig -a
br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.213.2  netmask 255.255.0.0  broadcast 192.168.255.255
        inet6 fe80::287a:9cff:fe00:242c  prefixlen 64  scopeid 0x20<link>
        ether 2a:7a:9c:00:24:2c  txqueuelen 1000  (Ethernet)
        RX packets 17021488  bytes 1010653574 (1.0 GB)
        RX errors 0  dropped 87518  overruns 0  frame 0
        TX packets 1208343  bytes 94198081 (94.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens160: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 00:50:56:ad:2c:fc  txqueuelen 1000  (Ethernet)
        RX packets 877691701  bytes 1159364863987 (1.1 TB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 235768762  bytes 35053960528 (35.0 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 8735697  bytes 885378140 (885.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8735697  bytes 885378140 (885.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth575R7P: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc66:dbff:fec1:1b35  prefixlen 64  scopeid 0x20<link>
        ether fe:66:db:c1:1b:35  txqueuelen 1000  (Ethernet)
        RX packets 570103  bytes 47247843 (47.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16400469  bytes 1242311745 (1.2 GB)
        TX errors 0  dropped 525 overruns 0  carrier 0  collisions 0

vethID2L1D: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc92:fff:feb7:6cc7  prefixlen 64  scopeid 0x20<link>
        ether fe:92:0f:b7:6c:c7  txqueuelen 1000  (Ethernet)
        RX packets 232492250  bytes 34708572279 (34.7 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 251654755  bytes 1116262078771 (1.1 TB)
        TX errors 0  dropped 520 overruns 0  carrier 0  collisions 0

vethIWA2KU: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc27:bcff:feff:ed16  prefixlen 64  scopeid 0x20<link>
        ether fe:27:bc:ff:ed:16  txqueuelen 1000  (Ethernet)
        RX packets 209180  bytes 16811809 (16.8 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16209262  bytes 1724505844 (1.7 GB)
        TX errors 0  dropped 525 overruns 0  carrier 0  collisions 0

vethOKATJP: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc5c:54ff:feca:beae  prefixlen 64  scopeid 0x20<link>
        ether fe:5c:54:ca:be:ae  txqueuelen 1000  (Ethernet)
        RX packets 131  bytes 12839 (12.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 491176  bytes 36799617 (36.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethVLRHMY: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fcf1:f2ff:fe02:e1ad  prefixlen 64  scopeid 0x20<link>
        ether fe:f1:f2:02:e1:ad  txqueuelen 1000  (Ethernet)
        RX packets 8274  bytes 677228 (677.2 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 385791  bytes 29078237 (29.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethYOEWDG: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fcf4:b9ff:feff:ec19  prefixlen 64  scopeid 0x20<link>
        ether fe:f4:b9:ff:ec:19  txqueuelen 1000  (Ethernet)
        RX packets 569378  bytes 45212384 (45.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16404589  bytes 1245849270 (1.2 GB)
        TX errors 0  dropped 525 overruns 0  carrier 0  collisions 0`

**lxc config show srv-intranet --expanded**

`root@lxd02:~# lxc config show srv-intranet --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu bionic amd64 (20190128_07:43)
  image.os: Ubuntu
  image.release: bionic
  image.serial: "20190128_07:43"
  security.privileged: "true"
  volatile.base_image: 06d8508f476470d5c9b47c6a30b25beb11cd357e6ffd3ec308d3dcf6417ef8b9
  volatile.eth0.hwaddr: 00:16:3e:d4:af:c6
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: local
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
`
**ip -4 route show**

`root@lxd02:~# ip -4 route show
default via 192.168.0.254 dev br0 proto static 
192.168.0.0/16 dev br0 proto kernel scope link src 192.168.213.2 `

**dmesg**

[dmesg.txt.gz](https://github.com/lxc/lxd/files/2827253/dmesg.txt.gz)

**Comment by gbonazzoli** [comment]
I think the most important thing are the followings:

During ping problems between container, in dmesg i got:

```
[242981.384312] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242981.459940] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242981.767131] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242983.377006] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242984.024470] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242984.445139] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242985.695942] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242989.579013] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242990.055878] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242990.101440] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242991.327694] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242991.731654] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242993.142536] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242993.299722] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242993.803932] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
[242994.490449] br0: received packet on ens160 with own address as source address (addr:2a:7a:9c:00:24:2c, vlan:0)
```
and at the same time the dropped packets on bridge interface adds up:

`root@lxd02:~# ifconfig -a
br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.213.2  netmask 255.255.0.0  broadcast 192.168.255.255
        inet6 fe80::287a:9cff:fe00:242c  prefixlen 64  scopeid 0x20<link>
        ether 2a:7a:9c:00:24:2c  txqueuelen 1000  (Ethernet)
        RX packets 18546276  bytes 1445332075 (1.4 GB)
        RX errors 0  dropped 89044  overruns 0  frame 0
        TX packets 2258524  bytes 513442858 (513.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.213.2  netmask 255.255.0.0  broadcast 192.168.255.255
        inet6 fe80::287a:9cff:fe00:242c  prefixlen 64  scopeid 0x20<link>
        ether 2a:7a:9c:00:24:2c  txqueuelen 1000  (Ethernet)
        RX packets 18772420  bytes 1498365598 (1.4 GB)
        RX errors 0  dropped 89090  overruns 0  frame 0
        TX packets 2479022  bytes 568782198 (568.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

**Comment by stgraber** [comment]
Okay, that bridge is managed outside of LXD and you're bridging a physical interface in a VMWare environment, this usually doesn't work so well as VMWare assumes a single MAC per NIC.

Can you show `brctl show` to confirm that things are good there, but I suspect they will be.

For bridged networking on top of VMWare, you need to do some reconfiguration on the VMWare side to allow for multiple MACs, I've never done it myself but from what I remember it's something to do with promiscuuous mode or something along those lines on the vswitch. Google should be able to help with that.

Closing as the issue appears to be with VMWare's networking or a MAC conflict external to the host (which the error you're getting would also match).

**Comment by stgraber** [comment]
(Note that because an issue is closed doesn't mean we're not looking at new comments on it, just that we don't believe there's anything actionable for LXD)

**Comment by stgraber** [comment]
https://discuss.linuxcontainers.org/t/bridge-with-netplan-for-lxc-doesnt-work/3964/8?u=stgraber

**Comment by gbonazzoli** [comment]
Ok, that's the output you asked me

`root@lxd02:~# brctl show
bridge name	bridge id		STP enabled	interfaces
br0		8000.2a7a9c00242c	no		ens160
							veth575R7P
							vethI40P22
							vethID2L1D
							vethIWA2KU
							vethVLRHMY
							vethYOEWDG`

**Comment by stgraber** [comment]
Yeah, that looks as expected, so the error can mean that:
 - VMWare's vSwitch is confused by all the MACs it's seeing and is mistakenly bouncing traffic back to your host
 - The host or some containers have the same MAC as another host or container on your network
 - A container somehow has the same MAC as the host (though that wasn't visible in previous output)

**Comment by gbonazzoli** [comment]
We finally found the recipe:

- On vmware side, set the port on the vSwitch in promiscuous mode. 
- On LXD host set the "physical" interface in promiscuous mode

In my installation, ens160 is the "physical" interface so the command to run is:
`
root@lxd02:~# ifconfig ens160 promisc
root@lxd02:~# echo $?
0
`
