### ISSUE TITLE
stream export and import of containers without persisting image

### ISSUE THREAD

**Issue by joelhockey** [lxc/lxd#5472]
Currently when exporting a container, I call CreateImage to create an image from a container, then I call GetImage to download it. Ideally I would like to have a single call that streams the image without ever persisting it. Does something like that already exist? If I was to send a patch, do you have suggestions on the best way for me to do this? Should I modify CreateImage or GetImage to take an arg to specify to stream the image rather than persisting? A new API? And I guess it would be good to have something similar for importing an image to create a container that doesn't persist the image, but just streams the image into a newly created container.

**Comment by brauner** [comment]
Thanks! :)

**Comment by stgraber** [comment]
So as I mentioned in the PR, I think this would be much better achieved using the backup export/import mechanism we already have.

Currently exporting a container is done by backing it up and then downloading the backup with the backup getting deleted afterwards or expiring shortly after. `lxc export` drives this.

For ingesting, we have an API that does exactly what you want under CreateContainer and will suck in a backup and create a container from it without ever storing it as an image. `lxc import` drives this.

It could be that what we have right now is sufficient for you or if you think it's possible to actually stream a backup out of the container without having it ever temporarily stored to disk, then maybe we can add an API for that (though I'm not sure that this is really possible without consuming a ton of RAM, at which point generating a backup and downloading it would actually be better).

**Comment by stgraber** [comment]
Re-labeling incomplete until we know that there's a need that's not covered by the backup API.

**Comment by joelhockey** [comment]
I've looked a little at backup and it looks promising.

For our usecase in crostini, we are currently using lxd 3.0.2 and it might be tricky to upgrade.  I'm quite keen to get a solution for backup/restore of container that doesn't require persisting extra copies since we have a lot of chomebook devices with very limited storage.

It looks like backup was added in 3.1.  Do you have thoughts on whether the backup code is compatible if I want to backport some patches into 3.0.2?  Or given that we are using btrfs, I'm also wondering if maybe I could access btrfs snapshots directly rather than going through lxd APIs.

I don't have much knowledge of either lxd or btrfs, but it looks to me that I could use lxd to take a snapshot of a container, then I could create a tarball directly from btrfs which should be a compatible image.  I'm guessing import/restore might be trickier though.

**Comment by stgraber** [comment]
@joelhockey indeed the backup/restore feature was added post-3.0 and would be annoying to backport in your version as it includes database changes.

With btrfs, you could indeed directly access the container on the filesystem or one of its snapshots, the issue with that approach is that the path will be uid/gid shifted, so you'll need to manually unshift that data before you can put it in an image tarball.

That's why in both the container export and container publish cases, we have to first generate a new snapshot, then alter the filesystem in that snapshot to be properly unshifted (rewrite all uid, gid, ACLs and xattrs) and then can generate a tarball of it as either a backup or image.

**Comment by joelhockey** [comment]
Can I clarify about whether backup does the uid/gid shifting?  The usecase for chromebooks has to support transferring containers from one device to another (e.g. buy a new device and transfer).  I'm guessing that backups might not be the right solution.

**Comment by stgraber** [comment]
Backups aren't uid/gid shifted but contain metadata which includes the container map (`backup.yaml`).
When importing a backup on a machine with a different map, LXD will trigger a shift of the container's filesystem on first startup.

**Comment by stgraber** [comment]
Closing as it seems like backups import/export should do the trick, if there's something we can do to improve those for your needs, let us know.
