### ISSUE TITLE
feature: able to create shorter zfs dataset names

### ISSUE THREAD

**Issue by mailinglists35** [lxc/lxd#5475]
# Required information

 * Distribution: ubuntu
 * Distribution version: 18.04lts
 * The output of "lxc info" or if that fails:
   * Kernel version:4.15.0-45-generic
   * LXC version:3.0.0
   * LXD version:3.0.0-0ubuntu4
   * Storage backend in use:zfs

# Issue description

when a container is created, images downloaded are created with very long names (even longer than uuids) as child datasets under pool/lxd/`images` parent dataset
this is a visual annoyance on 80x25 terminals (and even on larger ones) when inspecting `zfs list` output

**it would be neat to be able to provide an argument for `lxc` command to let user choose dataset name at image download/creation time instead of the long default one**

# Steps to reproduce
````
# lxc init images:b7db1990ad01 ubuntu1804lts or "lxc launch ubuntu:16.04 first"
[...]
# zfs list -rtall mypool/lxd
NAME                                                                                                USED  AVAIL     REFER  MOUNTPOINT
mypool/lxd                                                                                           2.87G  6.04T       96K  none
mypool/lxd/containers                                                                                2.22G  6.04T       96K  none
mypool/lxd/containers/fc29                                                                           1.94G  6.04T     2.15G  /var/lib/lxd/storage-pools/default/containers/fc29
mypool/lxd/containers/hp-tools                                                                        214M  6.04T      303M  /var/lib/lxd/storage-pools/default/containers/hp-tools
mypool/lxd/containers/ubuntu1804lts                                                                  68.5M  6.04T      290M  /var/lib/lxd/storage-pools/default/containers/ubuntu1804lts
mypool/lxd/custom                                                                                      96K  6.04T       96K  none
mypool/lxd/deleted                                                                                    669M  6.04T       96K  none
mypool/lxd/deleted/images                                                                             669M  6.04T       96K  none
mypool/lxd/deleted/images/2269bf3c313355c8557ab2836aa0da2173be62b8cf80c0f0272655ad51bd4007            215M  6.04T      215M  none
mypool/lxd/deleted/images/2269bf3c313355c8557ab2836aa0da2173be62b8cf80c0f0272655ad51bd4007@readonly     0B      -      215M  -
mypool/lxd/deleted/images/b7db1990ad01290088657b0e91e4fb7a586964e8ed63c5484b2b1c57696fd182            233M  6.04T      233M  none
mypool/lxd/deleted/images/b7db1990ad01290088657b0e91e4fb7a586964e8ed63c5484b2b1c57696fd182@readonly     0B      -      233M  -
mypool/lxd/deleted/images/e533f11359fa689abcd37ac0dd6d3b2c62c13dc05b448ecedb998696e1f045c3            221M  6.04T      221M  none
mypool/lxd/deleted/images/e533f11359fa689abcd37ac0dd6d3b2c62c13dc05b448ecedb998696e1f045c3@readonly     0B      -      221M  -
mypool/lxd/images                                                                                      96K  6.04T       96K  none
mypool/lxd/snapshots                                                                                   96K  6.04T       96K  none
````
note that I did not manually delete any image - the image cleanup is done probably automatically by ubuntu or lxd! I've just used `lxc init images` command then straight used the image. no clones no any other operation on it except start/stop. I'm even excluding the parent lxd dataset from automatic snapshotting via third party snapshotting tools so no snapshots or clones are made outside lxd.
 
thank you!

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
We will not be doing that.

All LXD images are identified by their SHA256 both on-disk and in any storage backend that we use. Using anything shorter would force us to track two identifier and would open us up to potential collision.

The images are sticking around on your system because of how ZFS works with clones and parents, the images cannot be fully deleted from your zpool until all containers that used those images are gone.

**Comment by stgraber** [comment]
(We also use `<dataset>/deleted/images/<hash>` as a way to found an existing image should the deleted image ever be re-imported somehow, in which case the image will get moved back to `images/<hash>`. If all we had was a UUID, we wouldn't be able to do this, leading to the same image being loaded up into your zpool multiple times.)
