### ISSUE TITLE
LVM: Container initialization failed (existing filesystem on storage)

### ISSUE THREAD

**Issue by esosan** [lxc/lxd#5482]
# Required information

 * Distribution: ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-43-generic
   * LXD version: 3.9
   * Storage backend in use: lvm (xfs)

# Issue description

Sometimes when I create a new container, generally after deleting another one, the initialization fails with this error:

`Creating the container
Error: Failed container creation: Create container from image: Error making filesystem on image LV: Failed to run: mkfs.xfs /dev/lxd_default_storage/containers_model--airedale: mkfs.xfs: /dev/lxd_default_storage/containers_model--airedale appears to contain an existing filesystem (xfs_external_log).
mkfs.xfs: Use the -f option to force overwrite.`

After this error I have to manually remove the volume from the lvm. To fix it, normally I do a `wipefs -a` on the device.

**Comment by stgraber** [comment]
Is that when deleting and creating a container of the same name?

**Comment by esosan** [comment]
No.

**Comment by stgraber** [comment]
That's very odd then, why would LVM give you a dirty LV when you create one...
Feels like a LVM bug to me but that may be a bit hard to catch...

Do you have a somewhat reliable reproducer for this?

**Comment by esosan** [comment]
Unfortunately I can't. I tried several times to init/launch new containers, delete them without problems. 
However it is a fairly rare...

**Comment by tomponline** [comment]
@esosan @stgraber this feels similar to https://github.com/lxc/lxc/issues/2346#issuecomment-428165907 perhaps you have `wipe_signatures_when_zeroing_new_lvs` or similar disabled?

**Comment by tomponline** [comment]
@esosan @stgraber although the patch we added to LXC effectively re-creates the same behaviour as described here, i.e it fails to create the container.

Seems to most reliable way would be to add ```--wipesignatures y``` to lvcreate commands or `-f` flags to mkfs commands (depending on whether LVM wiping or mkfs forcing is more reliable, as there seems to be a couple of signature detection modes in LVM itself).

Although @brauner wasn't keen on auto wiping existing file systems: https://github.com/lxc/lxc/issues/2346#issuecomment-393854019 , so we just fixed the hang in lxc-create.

**Comment by tomponline** [comment]
`mkfs.xfs` and `mkfs.ext4` have different meanings for `-f` (xfs `-f` is force, and ext4 `-f` is fragment size). So LVM signature wiping would likely be the most consistent way of achieving this.

**Comment by stgraber** [comment]
I'll take a look at adding wipesignatures to our lvcreate calls, just need to make sure that older LVM versions we still care about do support it.

**Comment by stgraber** [comment]
wipesignatures is there from 16.04 upwards for Ubuntu which means it's been there for at least 3 years by now, probably fine to rely on

**Comment by tomponline** [comment]
@stgraber cool, shall I add the same flags to lvcreate commands in LXC too?

**Comment by stgraber** [comment]
Yes but for liblxc we'd want some kind of version check as people tend to run liblxc on much much older versions of the operation system and we can't guarantee that this lvcreate option will be present.

**Comment by tomponline** [comment]
@stgraber OK, how about we execute it with the new flags and detect if the error code is `3` which I've tested on both an old CentOS 5 box (which doesn't have support for it) and a modern distro which does have support for it, and it appears that the exit code `3` is used for when an invalid flag is supplied.

If we get an exit code `3` then we could fallback to using `lvcreate` without those flags?

e.g.

```
[root@localhost ~]# lvcreate -Wy ; echo $?
lvcreate: invalid option -- W
  Error during parsing of command line.
3
```

This would avoid having to do any compile time detection of lvm version, and wouldn't require any additional commands to be executed on modern systems.

**Comment by tomponline** [comment]
@stgraber looks like the return code of 3 was added 16 years ago:

https://github.com/lvmteam/lvm2/blame/0ecf232194986b12c3ae95b3f93e7fdd56158dc1/tools/errors.h#L21

And it was used for invalid command args since 15 years ago:

https://github.com/lvmteam/lvm2/blame/6462e8dffc7ed53973ce796cec18fecc0fb89d77/tools/lvmcmdline.c#L2803

**Comment by stgraber** [comment]
Ah yeah, that seems like a good way to handle that then.
