### ISSUE TITLE
lxc file operations don't work... again?

### ISSUE THREAD

**Issue by rosowiecki** [lxc/lxd#5483]
* Distribution: CentOS
 * Distribution version: 7.5.1804
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.161-1.el7.elrepo.x86_64
   * LXC version: 3.1.0 (driver_version)
   * LXD version: 3.9
   * Storage backend in use: lvm

# Issue description
lxc file operations don't work, complaintin about strange paths.

Steps to reproduce:
lxc-start trusted-pigeon (tested on various containers)

[root@gamma1 ~]# lxc file pull trusted-pigeon/etc/hostname .
Error: open /tmp/lxd_forkgetfile_403299203: no such file or directory
[root@gamma1 ~]# lxc file edit trusted-pigeon/etc/hostname 
Error: Unable to create a temporary file: open /tmp/lxd_file_edit_598091288: no such file or directory
[root@gamma1 ~]# lxc file push config.cfg trusted-pigeon/root/config.cfg
Error: open /tmp/lxd_forkputfile_065913606: no such file or directory

EDIT: There was similar issue: #4050

**Comment by stgraber** [comment]
This isn't a LXD issue. The usual culprit is that something on your system cleaned up your /tmp, removing a directory called snap.0_lxd.XXXXXX, doing so causes /tmp in the snap environment to become invalid and all attempts to write to it results in such "No such file or directory".

Doing a full restart of the LXD snap should fix this (`snap restart lxd`) though note that it will also restart all your containers.

You should make sure that you don't have any tmpfile cleaning service or the like messing with that particular directory on your systems.

**Comment by rosowiecki** [comment]
Thanks @stgraber, you were right. It's very suspicious that I can't find any tmpwach or similar cron job on my system... I suspect this was another developer messing around in /tmp.

For anyone with similar issue: for some reason, any combination of restarting snap (restart, stop+start, stop+killall+start) didn't work, but after full host machine reboot it was OK.
