### ISSUE TITLE
Can't create Ceph storage pool

### ISSUE THREAD

**Issue by buggtb** [lxc/lxd#5485]
* Distribution: Ubuntu
 * Distribution version: Bionic
root@research1:~# /snap/bin/lxc info
config:
  core.https_address: 10.0.0.2:8443
  core.proxy_ignore_hosts: 10.0.0.1,127.0.0.1,145.239.254.77,2001:41d0:800:74d::,::1,localhost
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.0.0.2:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFYjCCA0qgAwIBAgIRAN6QvwI5HJiB5oQ41Ka72/owDQYJKoZIhvcNAQELBQAw
    NzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEXMBUGA1UEAwwOcm9vdEBy
    ZXNlYXJjaDEwHhcNMTgwNjIxMTA1NjIzWhcNMjgwNjE4MTA1NjIzWjA3MRwwGgYD
    VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRcwFQYDVQQDDA5yb290QHJlc2VhcmNo
    MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALp3MTnuEB0C6RaAfvl0
    EDlr1G1cEs1QtHCp84Fx7wQdRCAzaRd+mLSN9ncW9Swzaamh/W7NSMqGjDBfQmDA
    d2bb3AK99wtD1/NHGycyw4/RWCs56LoCKivZP65VO35W5CONe5zni6XYwzyNtY2c
    nJRY8Q23gZzan9vUpWPe8pKLubzmDu/Sf4M9z8jYYq2cFXUHGdy7pKc40iTWbJy/
    jAhT3c7QFEduUWpzT7arVGa239X+YsBwnbRZt4gGsWcEmOpOTMSXVUFGANXfab1C
    YQ5CD+WevDZgm8+e7YGr80iWIhoofQdZmKmjCgjsIICwdf/JpOsAYEsY60Us3RK2
    cBulppcw7+NloDNy3klLR5voASefc1Obq6hC9NQo9XW2g+VK2FXFlvFDXAtX7x/5
    IDvSV8KnefXH4tNDSnT96OdvZC1LwxiOMgy0Nw9t4N1cGldLWec2qJqwYb7D4N+T
    rQohn3EJB1Q8jY1UShAeOoRKxvocaS3kdDVDbaYYuScsjugwWy/+rFDzWVf7fJcj
    oyf5ze6ItUP2F50QLda41inevZsmEh730Bl9zzRlzzWi3cM43XK/wZGFAlaunKlK
    N411JSOW0QxTaHaCjQpp+5Mk038JoEUOyOmajoD+4mEmKRH5Mc0oBnZb7ROp0ABF
    P+o1/ZC8Oc6ac5GvAaAU2ZBXAgMBAAGjaTBnMA4GA1UdDwEB/wQEAwIFoDATBgNV
    HSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMDIGA1UdEQQrMCmCCXJlc2Vh
    cmNoMYcEke/9gocQIAFB0AgABIIAAAAAAAAAAIcECgAAAjANBgkqhkiG9w0BAQsF
    AAOCAgEAn/+Zz7ALPkcLEYP6IWU53YVoWKHZEQnrfEQKqFWwGJK3jFUcLt/zGmGp
    c3QMBv8kaCaM3R4jEFodwBWPRpHdUnwfx7ZH8f3tq6SyqWAXfZWx3WytsYlW3mar
    +VvAjVlODRQS9NzbhMQ5XH0jyCqmy0G/Cc55AqSZFgEPQmpsA43hJjYx0HhJPYq6
    HmRDzVf1NTnToAaWB19kr+k+ZavrcorCts+q8OcLbY26AVNi8fhUCSzolVnnCCNU
    Uz1gCpKgSLGgv6eK4MrUQiisK7B+bZH+eE1qODW6gJleIgw71rOSLwFUg+aJqzIp
    sZ+B5wby7FpG7AYwJHaxetpg2Pmmy//V2+k2V+8WQOkrl1caCUFp8S04h5Q4ttLE
    PdEJlQAlgPoAOsb0UjGK3iz3HE7MjFSErcgAcRyElo6onkXaP/UgEd2EMmOTsJwT
    JreBYKZG3g/OcBLzap8/bdXaYnb4/KM+BBWkSVyQLSauf8s3Jt0HyzjIyVzVfeiF
    hxyybJum9GVT3SNThUYmojftekMcFXZEUkoPWScci8+oU9DZZP1xBGXVwvga/UCO
    8avzL+fCCSTHdnz2oELWrmktWE0q2voheJ+ZiDUCHXQsQh2U0Ud/3biT3LxSQH1m
    VT/0zUGDS3+HlGbxo3tPB42v/sTJgbWzRiX9vB4XTED7sHgVtkc=
    -----END CERTIFICATE-----
  certificate_fingerprint: 576ffd08268d33f35e39f3b5fa31e1c66a5fb249017e7a9f3e304ab7f6111334
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-23-lowlatency
  server: lxd
  server_pid: 5325
  server_version: "3.9"
  storage: dir | zfs
  storage_version: 1 | 0.7.5-1ubuntu15
  server_clustered: false
  server_name: research1
  project: default

This looks like a bug but apologies if its not:

I've got a LXD snap installed and then used the ceph proxy charm to connect to a remove ceph cluster.

The ceph command line tool works, I can access the cluster and create pools.

Any variation on 

`lxc storage create ceph-pool ceph ceph.osd.pg_num=32 ceph.osd.pool_name=container-pool2 source=container-pool2`

`lxc storage create pool1 ceph`

all fail with 

`Error: Failed to run: ceph --name client.admin --cluster ceph osd pool create pool1 32: Error initializing cluster client: Error('error calling conf_read_file: error code 22',)`

But then often if you take the following as an example:

`Error: Failed to run: ceph --name client.admin --cluster ceph osd pool create container-pool2 32: Error initializing cluster client: Error('error calling conf_read_file: error code 22',)
`
If i then copy the output:

```
root@research1:~# ceph --name client.admin --cluster ceph osd pool create container-pool2 32
pool 'container-pool2' created
```

You can see the pool was created.

What am I missing?

**Comment by buggtb** [comment]
The error suggests its failing to find ceph.conf but /etc/ceph/ceph.conf exists

**Comment by stgraber** [comment]
Did you maybe install CEPH after you installed LXD?

If that's the case, then LXD wouldn't have access to your /etc/ceph until it gets restarted with `systemctl reload snap.lxd.daemon`.

That's assuming you're using the LXD snap, you didn't fill our issue template so we can't really tell.

**Comment by buggtb** [comment]
Sorry @stgraber I am using the snap, I didn't restart the snap daemon.. but...

```
root@research1:~# systemctl restart snap.lxd.daemon.service
root@research1:~# /snap/bin/lxc storage create lxd-pool123 ceph
Error: Failed to run: ceph --name client.admin --cluster ceph osd pool create lxd-pool123 32: Error initializing cluster client: Error('error calling conf_read_file: error code 22',)
```

**Comment by stgraber** [comment]
Hmm,

 - journalctl -u snap.lxd.daemon -n 300
 - ls -lh /proc/$(pgrep daemon.start)/root/etc/

**Comment by buggtb** [comment]
```
Feb 12 21:07:18 research1 lxd.daemon[2677]: => LXD exited cleanly
Feb 12 21:07:19 research1 systemd[1]: Stopped Service for snap application lxd.daemon.
Feb 12 21:07:26 research1 systemd[1]: Started Service for snap application lxd.daemon.
Feb 12 21:07:26 research1 lxd.daemon[32143]: => Preparing the system
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Loading snap configuration
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Setting up mntns symlink (mnt:[4026532325])
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Setting up kmod wrapper
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Preparing /boot
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Preparing a clean copy of /run
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Preparing a clean copy of /etc
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Setting up ceph configuration
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Setting up LVM configuration
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Rotating logs
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Setting up ZFS (0.7)
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Escaping the systemd cgroups
Feb 12 21:07:26 research1 lxd.daemon[32143]: ==> Escaping the systemd process resource limits
Feb 12 21:07:26 research1 lxd.daemon[32143]: => Re-using existing LXCFS
Feb 12 21:07:26 research1 lxd.daemon[32143]: => Starting LXD
Feb 12 21:07:26 research1 lxd.daemon[32143]: t=2019-02-12T21:07:26+0000 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
Feb 12 21:07:28 research1 lxd.daemon[32143]: => LXD is ready
Feb 12 21:07:35 research1 lxd.daemon[2677]: mount namespace: 8
Feb 12 21:07:35 research1 lxd.daemon[2677]: hierarchies:
Feb 12 21:07:35 research1 lxd.daemon[2677]:   0: fd:   9: cpuset
Feb 12 21:07:35 research1 lxd.daemon[2677]:   1: fd:  10: rdma
Feb 12 21:07:35 research1 lxd.daemon[2677]:   2: fd:  11: perf_event
Feb 12 21:07:35 research1 lxd.daemon[2677]:   3: fd:  12: devices
Feb 12 21:07:35 research1 lxd.daemon[2677]:   4: fd:  13: hugetlb
Feb 12 21:07:35 research1 lxd.daemon[2677]:   5: fd:  14: pids
Feb 12 21:07:35 research1 lxd.daemon[2677]:   6: fd:  15: blkio
Feb 12 21:07:35 research1 lxd.daemon[2677]:   7: fd:  16: memory
Feb 12 21:07:35 research1 lxd.daemon[2677]:   8: fd:  17: freezer
Feb 12 21:07:35 research1 lxd.daemon[2677]:   9: fd:  18: net_cls,net_prio
Feb 12 21:07:35 research1 lxd.daemon[2677]:  10: fd:  19: cpu,cpuacct
Feb 12 21:07:35 research1 lxd.daemon[2677]:  11: fd:  20: name=systemd
Feb 12 21:07:35 research1 lxd.daemon[2677]: lxcfs.c: 105: do_reload: lxcfs: reloaded
Feb 12 21:13:44 research1 lxd.daemon[32143]: t=2019-02-12T21:13:44+0000 lvl=eror msg="Failed to create CEPH osd storage pool \"container-pool2\" in cluster \"ceph\": Error initializing cluster client: Error('error calling conf_read_file: error code 22',)\n"
Feb 12 21:14:17 research1 lxd.daemon[32143]: t=2019-02-12T21:14:17+0000 lvl=eror msg="Failed to create CEPH osd storage pool \"lxd-pool123\" in cluster \"ceph\": Error initializing cluster client: Error('error calling conf_read_file: error code 22',)\n"
```

**Comment by buggtb** [comment]
```
root@research1:~# ls -lh /proc/$(pgrep daemon.start)/root/etc/
total 20K
lrwxrwxrwx 1 root root  35 Feb 12 21:07 alternatives -> /snap/core/current/etc/alternatives
lrwxrwxrwx 1 root root  31 Feb 12 21:07 apparmor -> /snap/core/current/etc/apparmor
lrwxrwxrwx 1 root root  33 Feb 12 21:07 apparmor.d -> /snap/core/current/etc/apparmor.d
lrwxrwxrwx 1 root root  30 Feb 12 21:07 ceph -> /var/lib/snapd/hostfs/etc/ceph
lrwxrwxrwx 1 root root  31 Feb 12 21:07 group -> /var/lib/snapd/hostfs/etc/group
lrwxrwxrwx 1 root root  34 Feb 12 21:07 hostname -> /var/lib/snapd/hostfs/etc/hostname
lrwxrwxrwx 1 root root  31 Feb 12 21:07 hosts -> /var/lib/snapd/hostfs/etc/hosts
-rw-r--r-- 1 root root 14K Feb 12 21:07 ld.so.cache
lrwxrwxrwx 1 root root  35 Feb 12 21:07 localtime -> /var/lib/snapd/hostfs/etc/localtime
-rw-r--r-- 1 root root  87 Feb 12 21:07 logrotate.status
drwxr-xr-x 2 root root  60 Feb 12 21:07 lvm
lrwxrwxrwx 1 root root  12 Feb 12 21:07 mtab -> /proc/mounts
lrwxrwxrwx 1 root root  39 Feb 12 21:07 nsswitch.conf -> /var/lib/snapd/hostfs/etc/nsswitch.conf
lrwxrwxrwx 1 root root  36 Feb 12 21:07 os-release -> /var/lib/snapd/hostfs/etc/os-release
lrwxrwxrwx 1 root root  32 Feb 12 21:07 passwd -> /var/lib/snapd/hostfs/etc/passwd
lrwxrwxrwx 1 root root  37 Feb 12 21:07 resolv.conf -> /var/lib/snapd/hostfs/etc/resolv.conf
lrwxrwxrwx 1 root root  29 Feb 12 21:07 ssl -> /var/lib/snapd/hostfs/etc/ssl
lrwxrwxrwx 1 root root  34 Feb 12 21:07 timezone -> /var/lib/snapd/hostfs/etc/timezone
lrwxrwxrwx 1 root root  26 Feb 12 21:07 vim -> /snap/core/current/etc/vim
root@research1:~#
```

**Comment by stgraber** [comment]
Okay, so LXD appears to have detected the existence of your CEPH config and setup /etc accordingly in the snap environment. Can you show:

`ls -lh /proc/$(pgrep daemon.start)/root/etc/ceph/`

**Comment by stgraber** [comment]
Actually for this to be more reliable, please instead do:

 - nsenter -t $(pgrep daemon.start) -m -- ls -lh /etc/ceph/

**Comment by buggtb** [comment]
```
root@research1:~# nsenter -t $(pgrep daemon.start) -m -- ls -lh /etc/ceph/
total 8.0K
-rw------- 1 ceph root 63 Feb 12 10:28 ceph.client.admin.keyring
lrwxrwxrwx 1 root root 27 Feb 12 10:23 ceph.conf -> /etc/alternatives/ceph.conf
-rw-r--r-- 1 root root 92 Nov  2 16:44 rbdmap
root@research1:~#
```

**Comment by stgraber** [comment]
Ah, that's the issue, there is no such thing as /etc/alternatives inside of the snap environment.
Where does `/etc/alternatives/ceph.conf` point to?

**Comment by stgraber** [comment]
I can tweak the snap to have /etc/alternatives be visible, but depending on where `ceph.conf` points to, it may not be all that useful.

**Comment by buggtb** [comment]
Ah must be to do with this proxy charm:

lrwxrwxrwx 1 root root 35 Feb 12 10:23 /etc/alternatives/ceph.conf -> /var/lib/charm/ceph-proxy/ceph.conf

**Comment by stgraber** [comment]
Ah yeah, we won't be able to accommodate that. We can fake /etc as we want, but we can't make /var/lib/charm appear in the snap environment.

You best bet is to duplicate your CEPH config inside /var/snap/lxd/common/ceph/ (need to create the dir), then set `snap set lxd ceph.builtin=true` followed by `systemctl reload snap.lxd.daemon`.

This will have LXD use /var/snap/lxd/common/ceph/ for the CEPH config which you can then copy whatever you want in (no symlink please, they're unlikely to resolve).

Closing as issue was tracked down to charm behavior.

**Comment by buggtb** [comment]
Thanks @stgraber !
