### ISSUE TITLE
LXD keeps adding NICs and breaking

### ISSUE THREAD

**Issue by buggtb** [lxc/lxd#5492]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Xenial

config:
  core.https_address: 10.0.0.2:8443
  core.proxy_ignore_hosts: 10.0.0.1,127.0.0.1,145.239.254.77,2001:41d0:800:74d::,::1,localhost
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.0.0.2:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFYjCCA0qgAwIBAgIRAN6QvwI5HJiB5oQ41Ka72/owDQYJKoZIhvcNAQELBQAw
    NzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEXMBUGA1UEAwwOcm9vdEBy
    ZXNlYXJjaDEwHhcNMTgwNjIxMTA1NjIzWhcNMjgwNjE4MTA1NjIzWjA3MRwwGgYD
    VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRcwFQYDVQQDDA5yb290QHJlc2VhcmNo
    MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALp3MTnuEB0C6RaAfvl0
    EDlr1G1cEs1QtHCp84Fx7wQdRCAzaRd+mLSN9ncW9Swzaamh/W7NSMqGjDBfQmDA
    d2bb3AK99wtD1/NHGycyw4/RWCs56LoCKivZP65VO35W5CONe5zni6XYwzyNtY2c
    nJRY8Q23gZzan9vUpWPe8pKLubzmDu/Sf4M9z8jYYq2cFXUHGdy7pKc40iTWbJy/
    jAhT3c7QFEduUWpzT7arVGa239X+YsBwnbRZt4gGsWcEmOpOTMSXVUFGANXfab1C
    YQ5CD+WevDZgm8+e7YGr80iWIhoofQdZmKmjCgjsIICwdf/JpOsAYEsY60Us3RK2
    cBulppcw7+NloDNy3klLR5voASefc1Obq6hC9NQo9XW2g+VK2FXFlvFDXAtX7x/5
    IDvSV8KnefXH4tNDSnT96OdvZC1LwxiOMgy0Nw9t4N1cGldLWec2qJqwYb7D4N+T
    rQohn3EJB1Q8jY1UShAeOoRKxvocaS3kdDVDbaYYuScsjugwWy/+rFDzWVf7fJcj
    oyf5ze6ItUP2F50QLda41inevZsmEh730Bl9zzRlzzWi3cM43XK/wZGFAlaunKlK
    N411JSOW0QxTaHaCjQpp+5Mk038JoEUOyOmajoD+4mEmKRH5Mc0oBnZb7ROp0ABF
    P+o1/ZC8Oc6ac5GvAaAU2ZBXAgMBAAGjaTBnMA4GA1UdDwEB/wQEAwIFoDATBgNV
    HSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMDIGA1UdEQQrMCmCCXJlc2Vh
    cmNoMYcEke/9gocQIAFB0AgABIIAAAAAAAAAAIcECgAAAjANBgkqhkiG9w0BAQsF
    AAOCAgEAn/+Zz7ALPkcLEYP6IWU53YVoWKHZEQnrfEQKqFWwGJK3jFUcLt/zGmGp
    c3QMBv8kaCaM3R4jEFodwBWPRpHdUnwfx7ZH8f3tq6SyqWAXfZWx3WytsYlW3mar
    +VvAjVlODRQS9NzbhMQ5XH0jyCqmy0G/Cc55AqSZFgEPQmpsA43hJjYx0HhJPYq6
    HmRDzVf1NTnToAaWB19kr+k+ZavrcorCts+q8OcLbY26AVNi8fhUCSzolVnnCCNU
    Uz1gCpKgSLGgv6eK4MrUQiisK7B+bZH+eE1qODW6gJleIgw71rOSLwFUg+aJqzIp
    sZ+B5wby7FpG7AYwJHaxetpg2Pmmy//V2+k2V+8WQOkrl1caCUFp8S04h5Q4ttLE
    PdEJlQAlgPoAOsb0UjGK3iz3HE7MjFSErcgAcRyElo6onkXaP/UgEd2EMmOTsJwT
    JreBYKZG3g/OcBLzap8/bdXaYnb4/KM+BBWkSVyQLSauf8s3Jt0HyzjIyVzVfeiF
    hxyybJum9GVT3SNThUYmojftekMcFXZEUkoPWScci8+oU9DZZP1xBGXVwvga/UCO
    8avzL+fCCSTHdnz2oELWrmktWE0q2voheJ+ZiDUCHXQsQh2U0Ud/3biT3LxSQH1m
    VT/0zUGDS3+HlGbxo3tPB42v/sTJgbWzRiX9vB4XTED7sHgVtkc=
    -----END CERTIFICATE-----
  certificate_fingerprint: 576ffd08268d33f35e39f3b5fa31e1c66a5fb249017e7a9f3e304ab7f6111334
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-23-lowlatency
  server: lxd
  server_pid: 1470
  server_version: "3.10"
  storage: dir | zfs | ceph
  storage_version: 1 | 0.7.5-1ubuntu15 | ceph version 10.2.11 (e4b061b47f07f583c92a050d9e84b1813a35671e)
  server_clustered: false
  server_name: research1
  project: default

# Issue description

I have no idea how to reproduce this but for the last couple of days my standalone LXD snap install keeps adding (slowly) 99 nics to the default profile, then everything stops running cause it has no nic space left....

Yesterday a snap refresh stopped it for a while, now its back.

**Comment by stgraber** [comment]
Can you show that default profile?

`lxc profile show default`

**Comment by buggtb** [comment]
I wiped the nics out a few minutes ago so they're currently in the growth phase. But there are no containers running....

```
config:
  environment.http_proxy: ""
  user.network_mode: ""
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth1:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth2:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth3:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth4:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth5:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth6:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth7:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth8:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth9:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth10:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth11:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth12:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth13:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/nexus2
- /1.0/containers/meteoritewww
- /1.0/containers/saikucommunitywww
- /1.0/containers/juju-33b9f4-0-lxd-11
- /1.0/containers/juju-33b9f4-0-lxd-7
- /1.0/containers/juju-33b9f4-0-lxd-8
- /1.0/containers/juju-33b9f4-0-lxd-9
- /1.0/containers/norwichdata
- /1.0/containers/norwichb2b
- /1.0/containers/saiku4
- /1.0/containers/importexport
- /1.0/containers/moodle
- /1.0/containers/iesnextcloud
- /1.0/containers/jupyter
- /1.0/containers/license4jcontainer
- /1.0/containers/spiculedocs
- /1.0/containers/drilltest2
- /1.0/containers/licenseserver
- /1.0/containers/spiculewww
- /1.0/containers/jupyter2
```

**Comment by stgraber** [comment]
Can you run `lxc monitor` and wait until you see the events causing a profile update?

**Comment by stgraber** [comment]
LXD doesn't really do things like that, in general, it's not capable of generating new devices on its own, so I'm pretty sure Juju or another API client is messing with you here. That `lxc monitor` output should confirm it.

**Comment by buggtb** [comment]
Hmm I don't know how to grok this so here's a big dump:

`
metadata:
  action: container-updated
  source: /1.0/containers/jupyter2
timestamp: "2019-02-14T00:45:15.598506458Z"
type: lifecycle


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:15.683505621Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:15.68466765Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:15.685685276Z"
type: logging


metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:15.686664587Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:18.701380448Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:18.706190457Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/profiles/default
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:18.710085764Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/networks/lxdbr0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:18.716863252Z"
type: logging


metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/profiles/default
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:18.733144758Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/nexus2
timestamp: "2019-02-14T00:45:19.003229198Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/meteoritewww
timestamp: "2019-02-14T00:45:19.19287542Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/saikucommunitywww
timestamp: "2019-02-14T00:45:19.442781997Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth6e4d9b95 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:19.586502947Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth2bdbcf9e has been added: updating network priorities'
timestamp: "2019-02-14T00:45:19.660729589Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/juju-33b9f4-0-lxd-11
timestamp: "2019-02-14T00:45:19.689277041Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth9b2ae182 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:19.829002309Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth5c34d6fb has been added: updating network priorities'
timestamp: "2019-02-14T00:45:19.903962761Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/juju-33b9f4-0-lxd-7
timestamp: "2019-02-14T00:45:19.961660502Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth946138a4 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:20.179565634Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth07266ca8 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:20.26474727Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/juju-33b9f4-0-lxd-8
timestamp: "2019-02-14T00:45:20.29200353Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: vethd33b41c8 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:20.43423039Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: vethb9b5ddb6 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:20.515193603Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/juju-33b9f4-0-lxd-9
timestamp: "2019-02-14T00:45:20.569956486Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/norwichdata
timestamp: "2019-02-14T00:45:20.859651418Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/norwichb2b
timestamp: "2019-02-14T00:45:21.042099346Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/saiku4
timestamp: "2019-02-14T00:45:21.223171649Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/importexport
timestamp: "2019-02-14T00:45:21.786723718Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/moodle
timestamp: "2019-02-14T00:45:22.047631461Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/iesnextcloud
timestamp: "2019-02-14T00:45:22.242061098Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/jupyter
timestamp: "2019-02-14T00:45:22.434167782Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/license4jcontainer
timestamp: "2019-02-14T00:45:22.692521199Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: Checking if RBD storage volume for container "spiculedocs" on storage pool
    "lxd-pool1" is ready
timestamp: "2019-02-14T00:45:22.851357699Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: RBD storage volume for container "spiculedocs" on storage pool "lxd-pool1"
    is ready
timestamp: "2019-02-14T00:45:22.906703022Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/spiculedocs
timestamp: "2019-02-14T00:45:22.906864676Z"
type: lifecycle


metadata:
  context:
    name: spiculedocs
    rootfs: /var/snap/lxd/common/lxd/containers/spiculedocs/rootfs
  level: warn
  message: Unable to update backup.yaml at this time
timestamp: "2019-02-14T00:45:22.906840035Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Checking if RBD storage volume for container "drilltest2" on storage pool
    "lxd-pool1" is ready
timestamp: "2019-02-14T00:45:23.126419807Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: RBD storage volume for container "drilltest2" on storage pool "lxd-pool1"
    is ready
timestamp: "2019-02-14T00:45:23.184124606Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/drilltest2
timestamp: "2019-02-14T00:45:23.184308832Z"
type: lifecycle


metadata:
  context:
    name: drilltest2
    rootfs: /var/snap/lxd/common/lxd/containers/drilltest2/rootfs
  level: warn
  message: Unable to update backup.yaml at this time
timestamp: "2019-02-14T00:45:23.184289364Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Checking if RBD storage volume for container "licenseserver" on storage
    pool "lxd-pool1" is ready
timestamp: "2019-02-14T00:45:23.326439099Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:23.379510465Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/profiles/default
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:23.382215362Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/licenseserver
timestamp: "2019-02-14T00:45:23.397211009Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: RBD storage volume for container "licenseserver" on storage pool "lxd-pool1"
    is ready
timestamp: "2019-02-14T00:45:23.397136982Z"
type: logging


metadata:
  context:
    name: licenseserver
    rootfs: /var/snap/lxd/common/lxd/containers/licenseserver/rootfs
  level: warn
  message: Unable to update backup.yaml at this time
timestamp: "2019-02-14T00:45:23.397203696Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Checking if RBD storage volume for container "spiculewww" on storage pool
    "lxd-pool1" is ready
timestamp: "2019-02-14T00:45:23.523692339Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/spiculewww
timestamp: "2019-02-14T00:45:23.583395315Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: RBD storage volume for container "spiculewww" on storage pool "lxd-pool1"
    is ready
timestamp: "2019-02-14T00:45:23.583233033Z"
type: logging


metadata:
  context:
    name: spiculewww
    rootfs: /var/snap/lxd/common/lxd/containers/spiculewww/rootfs
  level: warn
  message: Unable to update backup.yaml at this time
timestamp: "2019-02-14T00:45:23.58337547Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Checking if RBD storage volume for container "jupyter2" on storage pool
    "lxd-pool1" is ready
timestamp: "2019-02-14T00:45:23.727586169Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: RBD storage volume for container "jupyter2" on storage pool "lxd-pool1"
    is ready
timestamp: "2019-02-14T00:45:23.781761336Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/jupyter2
timestamp: "2019-02-14T00:45:23.789495383Z"
type: lifecycle


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:23.875536075Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:23.876735721Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:23.877691544Z"
type: logging


metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:23.878662989Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:26.893459245Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:26.897971249Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/profiles/default
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:26.901842394Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/networks/lxdbr0
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:26.908719529Z"
type: logging


metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/profiles/default
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:26.925162259Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/nexus2
timestamp: "2019-02-14T00:45:27.176160968Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/meteoritewww
timestamp: "2019-02-14T00:45:27.350606048Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/saikucommunitywww
timestamp: "2019-02-14T00:45:27.541954163Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth9c8e4576 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:27.687705896Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth652f7d66 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:27.760522358Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/juju-33b9f4-0-lxd-11
timestamp: "2019-02-14T00:45:27.81779346Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: vethdccfb051 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:27.9521453Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth7cb4b290 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:27.982935711Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/juju-33b9f4-0-lxd-7
timestamp: "2019-02-14T00:45:28.052380964Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth45933786 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:28.186538104Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth88d9d2fc has been added: updating network priorities'
timestamp: "2019-02-14T00:45:28.217195621Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/juju-33b9f4-0-lxd-8
timestamp: "2019-02-14T00:45:28.275396518Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth0947b6a2 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:28.420835876Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth60902674 has been added: updating network priorities'
timestamp: "2019-02-14T00:45:28.493968842Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/juju-33b9f4-0-lxd-9
timestamp: "2019-02-14T00:45:28.52292199Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/norwichdata
timestamp: "2019-02-14T00:45:28.709852177Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/norwichb2b
timestamp: "2019-02-14T00:45:28.951418611Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/saiku4
timestamp: "2019-02-14T00:45:29.173290753Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/importexport
timestamp: "2019-02-14T00:45:29.375418158Z"
type: lifecycle
`

**Comment by stgraber** [comment]
```
metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/profiles/default
  level: dbug
  message: handling
timestamp: "2019-02-14T00:45:26.925162259Z"
type: logging
```

This shows an API query coming over the UNIX socket to update the `default` profile, quickly followed by all your containers getting updated due to a new NIC being added.

So you have something on your system which is asking LXD to do that.

**Comment by buggtb** [comment]
Thats amazing! Literally all this box does is run a few LXD containers, some of which are connected to Juju, some aren't... how bizarre.

**Comment by stgraber** [comment]
Yeah, my money is currently on Juju, I'm grabbing their code to see if they have logic which would create such devices. LXD doesn't have a logic that would cause an increasing ethXX device name so that's clearly something external doing that.

**Comment by stgraber** [comment]
And bingo, those device names match those generated by `generateNICDeviceName` in `./container/lxd/network.go` in the Juju codebase.

Closing as this is a Juju issue, LXD is doing as it's told.

**Comment by buggtb** [comment]
Ah ha... does look juju related:

```
machine-0: 01:09:00 WARNING juju.provisioner not stopping machine agent container watcher due to error: setting up container dependencies on host machine: running lxd init --auto: : exec: "lxd": executable file not found in $PATH
machine-0: 01:09:00 ERROR juju.provisioner starting container provisioner for lxd: setting up container dependencies on host machine: running lxd init --auto: : exec: "lxd": executable file not found in $PATH
machine-0: 01:09:04 INFO juju.provisioner initial container setup with ids: [0/lxd/8 0/lxd/9 0/lxd/11 0/lxd/7]
machine-0: 01:09:04 INFO juju.container.lxd LXD snap is installed; skipping package installation
machine-0: 01:09:09 WARNING juju.provisioner not stopping machine agent container watcher due to error: setting up container dependencies on host machine: running lxd init --auto: : exec: "lxd": executable file not found in $PATH
machine-0: 01:09:09 ERROR juju.provisioner starting container provisioner for lxd: setting up container dependencies on host machine: running lxd init --auto: : exec: "lxd": executable file not found in $PATH
machine-0: 01:08:07 INFO juju.provisioner initial container setup with ids: [0/lxd/8 0/lxd/9 0/lxd/11 0/lxd/7]
machine-0: 01:08:07 INFO juju.container.lxd LXD snap is installed; skipping package installation
```

Yet 

root@research1:~# which lxd
/snap/bin/lxd

anyway major hack:

root@research1:~# ln -s /snap/bin/lxd /usr/bin/ :)

**Comment by stgraber** [comment]
Sounds like Juju is running in an environment where /snap/bin isn't in PATH
