### ISSUE TITLE
allow a custom compressor for "lxd publish" / "lxd image export", like pigz

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#5508]
lxd should allow custom compressors for "lxd publish".

Right now, "lxd publish" uses gzip, which is singlethreaded. The operation may take very long if the image is large.

It would be great if I could use i.e. pigz to compress the image to leverage multiple CPUs in the server.

**Comment by stgraber** [comment]
You can set the compressor already using images.compression_algorithm.

```
stgraber@castiana:~$ lxc init images:alpine/edge test
Creating test
stgraber@castiana:~$ lxc config set images.compression_algorithm pigz
stgraber@castiana:~$ lxc publish test --alias test
Container published with fingerprint: d36facc2c5d1c27e07d72dd81378d3ab08b1596da87e703124de4c2c982f3efb
```

It can be set globally as done above, or be passed as an argument to `lxc publish` or through the API.

**Comment by tchwpkgorg** [comment]
Doesn't seem to work for me:

```# lxc config set images.compression_algorithm pigz
Error: cannot set 'images.compression_algorithm' to 'pigz': exec: "pigz": executable file not found in $PATH

# which pigz
/usr/bin/pigz

# snap list
Name  Version    Rev    Tracking  Publisher   Notes
core  16-2.37.2  6405   stable    canonical✓  core
lxd   3.10       10150  stable    canonical✓  -
```

I understand the snap needs to use its own pigz version - this doesn't exist:
```
# find /var/snap -name pigz
# 
```

**Comment by stgraber** [comment]
@tchwpkgorg Try setting it to /var/lib/snapd/hostfs/usr/bin/pigz maybe that'll work. If it doesn't then we'd indeed need to include it in the snap but it's not something we're very likely to do given that pigz isn't in main, meaning it never got through a strong security audit on the Ubuntu side.

**Comment by tchwpkgorg** [comment]
Doesn't work (though maybe I didn't do it correctly)?
```
# ls  /var/lib/snapd/hostfs/usr/bin/pigz
ls: cannot access '/var/lib/snapd/hostfs/usr/bin/pigz': No such file or directory

# ls  /var/lib/snapd/hostfs/usr/bin/
ls: cannot access '/var/lib/snapd/hostfs/usr/bin/': No such file or directory

# mkdir /var/lib/snapd/hostfs/usr/bin
mkdir: cannot create directory ‘/var/lib/snapd/hostfs/usr/bin’: No such file or directory

# mkdir -p /var/lib/snapd/hostfs/usr/bin

# cp /usr/bin/pigz /var/lib/snapd/hostfs/usr/bin/pigz

# lxc config set images.compression_algorithm pigz
Error: cannot set 'images.compression_algorithm' to 'pigz': exec: "pigz": executable file not found in $PATH
```

If not pigz - how about xz-utils then?

xz can do parallel compression using all CPUs (though it needs a flag passed, i.e. "-T 0" to use all CPUs).

```  -T, --threads=NUM   use at most NUM threads; the default is 1; set to 0
                      to use as many threads as there are processor cores
```

**Comment by stgraber** [comment]
Did you actually try just setting it to the value I gave you?
The fact that you don't see it doesn't mean it's not there from the snap's point of view.

```
root@sateda:~# lxc config set images.compression_algorithm /var/lib/snapd/hos/usr/bin/pigz
root@sateda:~# 
```

**Comment by tchwpkgorg** [comment]
With a full path - yes, it works!

```
lxc config set images.compression_algorithm /var/lib/snapd/hostfs/usr/bin/pigz
```

On a system with a AMD EPYC 7401P 24-Core Processor (48 logical CPUs) - for a container which is 3 GB large - "lxc publish" takes ~30 secs with pigz, versus ~2 mins with gzip.

My actual usage case are large containers (>100 GB), though I'm unable to check this due to the issue #5509 :)
