### ISSUE TITLE
feature request: don't set "expires_at" for manually created snapshots

### ISSUE THREAD

**Issue by gschintgen** [lxc/lxd#5510]
Thanks for adding snapshot scheduling and expiry!
I'd like to propose one minor but very useful addition:
Please add a container configuration key (e.g. snapshots.expire_manual_snapshots) that controls whether the automatic expiry is also applied to manually created snapshots.

Rationale:
I'd say that many users (me included) will use the automatic snapshotting feature to have a set of rotating snapshots in a rather high frequency. But at significant times (first working state, before major upgrade, after major upgrade, etc.) the user will likely create a manual snapshot (and possibly even give it a descriptive name with the intention to keep it around). However with the current lxd-3.10 a configured "expiry" will set an "expires_at" time indiscriminately of the snapshot's creation mode (manual or scheduled). This may well be unexpected or at least unwanted.

I don't particularly care if the default setting would be true or false or if the distinction is actually scheduled vs manual or scheduled vs named snapshot, but some kind of discrimination between both types of snapshots would be quite welcome.

(I do know that it's possible to manually edit the expires_at field, but it feels weird to have to do this kind of "low-level" editing after a snapshot that is of some importance.)

**Comment by stgraber** [comment]
@gschintgen How about a `--no-expiry` option to `lxc snapshot` would that cover your need?

**Comment by gschintgen** [comment]
That'd be fine too. Thanks for the fast reply! :-)
