### ISSUE TITLE
Snap remove lxd fails with error message

### ISSUE THREAD

**Issue by SwitchedToGitlab** [lxc/lxd#5513]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.10
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version: 3.9
   * Storage backend in use: btrfs

# Issue description

Cannot remove LXD using snap. Fails with ```remove /var/snap/lxd/common/lxd/storage-pools/default/images/35f6bff57c250208c6dc73445eefe8c1020853a1bc8571ebd8bfb1fe3a239504/metadata.yaml: read-only file system```

Re-installing LXD shows no storage pools. Removing snap again fails with the same error message as above.

# Steps to reproduce

 1. Install lxd using ```snap install lxd```
 2. Create container
```lxc launch $DISTRO:$DISTRO_VERSION -p default -p $USER $CONTAINER_NAME```
 3. Add storage device
```lxc config device add $CONTAINER_NAME device0 disk source=$VOL_SRC_DIR path=$VOL_DST_DIR```
4. Remove LXD from the system
```sudo snap remove lxd```

Completion of step 4 generates the error message.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

None of the suggested steps for additional information are working at this time, either because it is now disabled, and many of the paths are not applicable to snap installs.

**Comment by stgraber** [comment]
Similar to your other issue, this isn't an issue with LXD itself, therefore I'm closing this issue.

In this case, it looks like you're attempting to remove a package that still has a number of active kernel resources in play, in this case a bunch of btrfs subvolumes which cannot be deleted through normal filesystem operations. I suspect that if you had first deleted all containers and images from your LXD installation, the package removal would have worked.

**Comment by SwitchedToGitlab** [comment]
Doesn't change the fact that the behavior exists, and the user has no idea that this action will be detrimental to their system. Had you chosed a packaging system that didn't have these obvious flaws, such as apt, the user could expect to have those resources purged when the package was removed. 

Blaming this on upstream when you are well aware of the issue is unacceptable, as this bug has been an issue upstream for several years now.

**Comment by SwitchedToGitlab** [comment]
Therefore it's not an upstream issue then...

**Comment by SwitchedToGitlab** [comment]
...seriously, I checked and tested this myself. There's no reason that this can't be done with a script in APT. The only issue here is a poor packaging implementation. Packaging using the debian package manager format would intrinsically resolve this isssue.
