### ISSUE TITLE
New installations require snap, snap experience very bad, not production ready

### ISSUE THREAD

**Issue by SwitchedToGitlab** [lxc/lxd#5514]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.18.0-15-generic
   * LXC version:
   * LXD version: 3.9
   * Storage backend in use: btrfs

# Issue description
Snap installations have poor **very poor** user experience. They complicate administration, require multiple additional troubleshooting steps. It is unacceptable to require end users to use a system that is not ready for "prime time". The use of snaps irreparably denigrates the user experience to the point of not being acceptable for use in a production tool chain.   

- For example, restarting the lxd daemon with a snap is not clear, not obviously documented. 

- There are known failures with deleting LXD from a system that cause serious issues for users. 

- I apparently have to learn all about how snaps work etc to install and use lxd. Given that there are other package managers out there, this already makes for a steep barrier to entry. 

- automatic version updating is an absolute no-go for this. I cannot have my development environment halted because lxd updated in the background and broke a script. 

- isolation changes all the paths for the logs, storage, etc, breaking all your documentation. Again, I have to learn all about snap isolation just to find a log file, like the one requested below

- templates, docs, issue templates all refer to the traditional installation of lxd using apt

# Steps to reproduce

 1. ```snap install lxd ```
 2. Use
 3. Cry

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`) - not relevent with snaps
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log) - not relevent with snaps
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue) -- not possible, documented with snaps

**Comment by stgraber** [comment]
Closing as not a constructive bug report.

This is the upstream LXD project, while we prefer our users use the snap as that simplifies reproducing issues, you don't have to. You're welcome to use a Linux distribution that ships other type of packages for it or build it by hand yourself.

**Comment by SwitchedToGitlab** [comment]
This is the project's choice to use a sub-par packaging method that denigrates the user experience. The issues produced are a direct result of the project's choices, therefore the bug is relevant.
