### ISSUE TITLE
dmesg issue

### ISSUE THREAD

**Issue by jaskolowski** [lxc/lxd#5516]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by jaskolowski** [comment]
i have, now again, to insist on this:
i'm talking about this: https://github.com/lxc/lxd/issues/3148
there is no answer on how to solve the issue
so,(please) give us a clue
don`t treat us as an idiot

**Comment by jaskolowski** [comment]
on you learn... y have to say that 2 YEARS ago... your teem dont solve that issue. And thats is why y end here

**Comment by stgraber** [comment]
Answer hasn't changed, this is a kernel feature request not something LXD can do anything about.

The dmesg restrict systctl works just fine to prevent unprivileged containers access to the kernel log. Anything more complex than that would need serious kernel work which so far nobody has shown interest in doing.
