### ISSUE TITLE
lxc cli: allow multiple filters

### ISSUE THREAD

**Issue by dionysius** [lxc/lxd#5525]
Unsure if this is a bug, since this "feature" isn't explicitly mentioned in the usage.

# Required information

 * The output of "lxc info" or if that fails:
   * LXC version: `branch master`
   * LXD version: `branch master`

# Issue description

When filtering for containers `lxc list "filter..."`, you can't set multiple filters. According to the code currently on master:
- while [correctly assigning all remaining args to filters](https://github.com/lxc/lxd/blob/2fd055ea57adeab29140c56776fff0882765c877/lxc/list.go#L389) and beeing passed through
- [this function, while still looping through the filters](https://github.com/lxc/lxd/blob/2fd055ea57adeab29140c56776fff0882765c877/lxc/list.go#L142), returns the result already when the first filter is processed
- so ignoring further filters

# Steps to reproduce

 1. Step one
- have a centos container without privileged
- have a ubuntu container without privileged
 2. Step two
`lxc list "security.privileged=false" "image.os=ubuntu"` should show only the ubuntu container, but is listing both
or `lxc list "security.privileged=false" "image.os=nonexistent"` should show none

**Comment by dionysius** [comment]
I could do a PR for that, but I'm unsure if this fits your plans with args

**Comment by stgraber** [comment]
Yeah, I think we want the filters to be applied as AND, not OR and we definitely should update the help to clarify the behavior. So a PR would be welcome.
