### ISSUE TITLE
LTS: unable to build with go 1.12

### ISSUE THREAD

**Issue by CameronNemo** [lxc/lxd#5529]
```
# gopkg.in/lxc/go-lxc.v2
../../../gopkg.in/lxc/go-lxc.v2/container.go:843:12: identifier "_Ctype_char" may conflict with identifiers generated by cgo
# github.com/lxc/lxd/shared/idmap
shared/idmap/shift_linux.go:221:40: identifier "_Ctype_acl_type_t" may conflict with identifiers generated by cgo
```

**Comment by stgraber** [comment]
Looks like your code tree is outdated as that line in container.go is a blank line these days and there's a December 5th commit which fixes that very issue.

All LXD commits are tested against Go tip, so we find and fix such breakages months before a Go release.

**Comment by CameronNemo** [comment]
There is no December commit in the 3.0 branch. Do you have the commit id?

**Comment by stgraber** [comment]
e2c90d35f6f8e592969efa52d578b33324dc418a

**Comment by stgraber** [comment]
December 6th in stable-3.0
