### ISSUE TITLE
Implement relay/proxy mode in the lxc client

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#553]
This is about implementing the relay/proxy feature in the client, where either on transfer failure or when a remote flag is set, the client will act as a relay between the two LXDs.

**Comment by tkuhlman** [comment]
+1

**Comment by vskubriev** [comment]
+1, Useful feature.

**Comment by casey-bowman** [comment]
+1, per tkuhlman's reference, to be able to copy image to a remote LXD

**Comment by dobin** [comment]
As i'd like to copy a container from my notebook at home to an external rootserver, +1.

**Comment by stgraber** [comment]
Marking as blocked on #2402 and #1926

**Comment by francoisp** [comment]
This missing feature of copying/pushing a container from behind a NATed machine is quite a downer.  It seems like it could be easily addressed by modifying the NATing firewall to forward 8443 and setting the config of the NATed LXC source, but 
lxc config set core.https_address xx.xx.xx.xx:8443 specifying the address of the firewall's forwarded port does not work:
 error: cannot listen on https socket: listen tcp xx.xx.xx.xx:8443: bind: cannot assign requested address.

Any way to force lxc to think it's listening to this forwarded address/port?

**Comment by stgraber** [comment]
You can't listen on an address that doesn't exist. It's not LXD refusing to do it, it's the kernel.
