### ISSUE TITLE
LXD Feature Request: Allow specifying a different init instead of /sbin/init

### ISSUE THREAD

**Issue by xrobau** [lxc/lxd#5541]
When trying to diagnose issues with systemd failing to start, with the normal 'Failed to mount API filesystems, freezing.' error that signifies it is unhappy with what it can see mounted, I discovered there is no way to convince LXD to start with a different init, to ease debugging.

```
Console log:

Failed to insert module 'autofs4'
Failed to insert module 'unix'
Failed to mount sysfs at /sys: Operation not permitted
Failed to mount proc at /proc: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
```

Normally, from this point, you'd switch init to be /bin/bash and then step through why systemd is annoyed, however, that feature is not available in LXD.

The only way to do this could be to exec into the broken container, mv /sbin/init to /sbin/init.old and then link bash into init, which then - by changing the container - makes repeatability of error diagnosis and unit testing impossible.

Is there any possibility of implementing this feature?

**Comment by brauner** [comment]
You can use:
```
lxc config set <container-name> raw.lxc 'lxc.init.cmd = /bin/bash'
```

**Comment by xrobau** [comment]
Well crap. I didn't find that documented anywhere. Thanks, @brauner

**Comment by brauner** [comment]
Oh that's totally fine. :) We do not make a lot of noise about it but the simple rule is: `raw.lxc` let's you set any key documented in `lxc.container.conf`: `man lxc.container.conf`.

**Comment by xrobau** [comment]
The actual REASON for the error turned out that /sys and /proc were missing from the image I built - I would think that LXD should error out and refuse to start, especially as they're defined as a prerequisite.

I'll be creating a pull request against doc/debugging.md page with some hints as to what can go wrong, and how to diagnose them, if that's OK? Or would you like them somewhere else?

**Comment by stgraber** [comment]
Debugging sounds good, and indeed hinting at reading `lxc console --show-log NAME` for early boot errors seems like a good plan.

LXD doesn't itself rely on /proc or /sys existing so while it's something that should be there for a normal working Linux system, there are weird embedded distros that have it somewhere else and so a hard check for it may turn out problematic.
