### ISSUE TITLE
Unable to start containers after upgrading from Ubuntu 16.04 to 18.04

### ISSUE THREAD

**Issue by riverclimber** [lxc/lxd#5542]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info":
config:
  core.https_address: 0.0.0.0:27131
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.2.1.11:27131
  - 10.0.3.1:27131
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFjDCCA3SgAwIBAgIQAvqhu2DdF4/jLrr7zcmicTANBgkqhkiG9w0BAQsFADAx
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMREwDwYDVQQDDAhyb290QHMw
    MzAeFw0xNjExMTcwNTEwMjFaFw0yNjExMTUwNTEwMjFaMDExHDAaBgNVBAoTE2xp
    bnV4Y29udGFpbmVycy5vcmcxETAPBgNVBAMMCHJvb3RAczAzMIICIjANBgkqhkiG
    9w0BAQEFAAOCAg8AMIICCgKCAgEAw+OhqTkMlgqj10qVOopDlVmFbwObKczD0YOE
    TAuRn7Nr8Qnqs2vi2GFB/Lng6xgCvc/ToGzcdSSdlo8u3z3/nQjm8ywT2gWjIBcg
    Dpi98lP+cj72wpMlrCxKIDJ8rxte/vCv1oBuaKXT4bSrZjcI4LL2y1Bf60JUaU9d
    0ukEYZTGDRtcYBgLByEorti+HMJ8iJos5CxAZ8eNY7EWfNF6Nv22yl6yAehSKdV4
    rSWNwm9WVEI+DyOEBNdoDBMuEcpE+4d7nB2V75Us3xKOMlFvTIP1wXvXOCdeZfp/
    UpOPYkdo7zV/IDD3JV9x5YcFVSR2GsTCBe2wH/f/dFZPSdizbEbG6/Jfy7Bx5N1U
    Bthfj72fxcBL8kAsldwSbmfRShbQElBOFJwa5ZL/jSQ8Gkpg3B7EdjEplRJhpjLg
    85g3QsK323DTdmykJFaE16EoRHpZ54VrHPMKMfFNK94CNA9run5J7dKQYhaDqO7f
    c8a1DMyiOhr+Vg93a2LUja2QkfFrTKvQh9k2yZTxOGtSpwttg3+3Y93hw0Sp9gzD
    DQcsTKm9zKs/juhcuhaHUuc+MkXp3U1sjvO3XJ0fkea7VhjvMZZp+HZYA3sXSyRq
    i5B34BQRAkTTwvm8Q79FZ9HjteWKBGSPVbx747AfWM6P2rBWbDtmse9f1nE6Ik1q
    2oNz1aMCAwEAAaOBnzCBnDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYB
    BQUHAwEwDAYDVR0TAQH/BAIwADBnBgNVHREEYDBeggNzMDOCDzEwLjIzNS4xOTcu
    NC8yNIIcZmU4MDo6ODJlZTo3M2ZmOmZlOTc6NjNmYS82NIIcZmU4MDo6NDQ3NDpi
    MmZmOmZlNWQ6ZGZjNC82NIIKZmU4MDo6MS82NDANBgkqhkiG9w0BAQsFAAOCAgEA
    oZOm7xoWFw7mj6K/lvqsqx3K97MJTcjUCHDBC366AxKOhWONpVbBoOoeFmEDiHzR
    VgN9Fz6bBmphENgyPfCOKcs9NiqlUEDjiAsdbn0e//Kwi+k6JWb9ORS+cGH6A/25
    +uho1Yf9wlTp0nWCdg2cF/dezaXauWy5HoC9PqKDLRCqnAMRSkQ6cnNJuO7YZ202
    T9x6raF5vOAIjeEw/1Gf0Rs6hezlAR3cb0D+fbQoxgZgDFHjyz/OGRognGdMNwD+
    1r73hLsKEmjsxPSqlLnb2XaP1Ll/ZF1OvbaZi+kZM24CyBxbengAVgXzvZ6Nz1VF
    7XKPY2KPMb1Hx5ogtUf6s7HK0tvCq4Th1Hv7ywQEQE4XbkiYtPw8J3Y+Z9gQt2UU
    AORYQlrRSuXljifHEc4Xen/GzvqVITMlE6zS0K1hnP04X4ToDGl2GbcounoHGe3u
    sPLNbbItkWBCWxICCPdjsWAGJgn8FvscU+yeLecE/qHOD4daBohZyCcJ4riRhtEV
    D3mfYeT42isqKZXN5XQZfe1VeA5gXUDNLgiZnZDNgwKCijoDJvsxwCOZeVq+Zs+U
    bXSbUwuKyTx4vb/rbwe//d7rkZNi4n7ieD6xdX8nVvRZ4cfBVY+AREbDAKz3XMjz
    ZMb7kqLM7KHtalrCQOfh7GX0WiwWqYxiGa1IFHB/zJw=
    -----END CERTIFICATE-----
  certificate_fingerprint: d7d914fa70f9db9438579a58e6d9f27be08b8a4e3b5c9c7a67171e467a657b6f
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-45-generic
  server: lxd
  server_pid: 1982
  server_version: 3.0.3
  storage: btrfs
  storage_version: 4.15.1
  server_clustered: false
  server_name: s3
  project: ""

# Issue description

My system was upgraded from Ubuntu 16.04 to 18.04 using do-release-upgrade, and the upgrade failed due to the new storage pool partition having insufficient space (/var/lib/lxd/containers, /var/lib/lxd/snapshots, and /var/lib/lxd/images were on a partition different from /var/lib/lxd).  As a result, these errors were found in syslog after reboot:

Feb 15 21:27:23 s3 lxd[3744]: t=2019-02-15T21:27:23-0500 lvl=eror msg="Failed to rsync: rsync: write failed on \"/var/lib/lxd/storage-pools/default/containers/jslate/rootfs/var/log/wtmp.1\": No space left on device (28)\nrsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]\n: Failed to run: rsync -a -HAX --sparse --devices --delete --checksum --numeric-ids --xattrs --bwlimit 0 -q /var/lib/lxd/containers/jslate/ /var/lib/lxd/storage-pools/default/containers/jslate: rsync: write failed on \"/var/lib/lxd/storage-pools/default/containers/jslate/rootfs/var/log/wtmp.1\": No space left on device (28)\nrsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]"

I wasn't expecting the creation of the new storage pool in the partition of /var/lib/lxd, so the rsync processes simply failed.  I believe rsync failed for snapshots, containers, and images directories.  Now lxd is in a state that none of the existing containers would start.  I tried to create a new container, and it failed as well:

s3: $ lxc launch images:alpine/3.6/i386 test
Creating test
Starting test                               
Error: Common start logic: Missing parent 'lxdbr0' for nic 'eth0'
Try `lxc info --show-log local:test` for more info
s3: $ lxc info --show-log local:test
Name: test
Remote: unix://
Architecture: i686
Created: 2019/03/03 23:41 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

I'd really like to get these containers back up and running.  Can you please guide me to complete the upgrade process?

# Steps to reproduce

 1. Install Ubuntu 16.04
 2. Upgrade to 18.04 with /var/lib/lxd not having enough space to hold all files

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Ok, what you'd need to do to try and get things working again is:
 - Have sufficient storage on /var/lib/lxd/storage-pools/default
 - If needed, that may require you moving things out of there, then bind-mount then moving things back
 - Each entry under /var/lib/lxd/storage-pools/default/containers must be its own subvolume
 - All containers must have a directory under /var/lib/lxd/storage-pools/default/containers/
 - /var/lib/lxd/containers should only contain symlinks, those symlinks point from the container name to the matching directory under /var/lib/lxd/storage-pools/default/containers/

If you can manually move all your data around so that each container has a subvolume in /var/lib/lxd/storage-pools/default/containers/ and a symlink under /var/lib/lxd/containers/ pointing to it, that should fix things.

For images you could do the same, but if you don't have any personal images you care about, it's probably easiest to just wipe both /var/lib/lxd/images and /var/lib/lxd/storage-pools/default/images.
LXD should notice on startup and cleanup its internal state to match that.

**Comment by riverclimber** [comment]
Thanks!  Some questions:

- should I stop any services while copying the files?  should I restart anything after?
- do I need to copy ALL containers/images/snaps for this to work?
- would it OK to store some/all containers on a different partition?  Or do all files have to be saved within the storage pool?
- should I worry about the error "Error: Common start logic: Missing parent 'lxdbr0' for nic 'eth0'" when I tried to launch a brand new container?
- I believe this command used for copying the the containers/images/snaps: rsync -a -HAX --sparse --devices --delete --checksum --numeric-ids --xattrs --bwlimit 0 -q /var/lib/lxd/containers/containerX/ /var/lib/lxd/storage-pools/default/containers/containerX.  Could you please confirm?

**Comment by riverclimber** [comment]
I realized that the migration script needed more space before it was trying to rsync files to a different partition.  In addition, there are a couple of databases (100GB+) with snapshots.  This is probably the reason why all that extra space is needed in the first place.  Would it work if I simply mv /var/lib/lxd/containers/containerX/ /var/lib/lxd/storage-pools/default/containers/containerX if it's the same partition?  Would this mean the old snapshots would also work?  The partition is btrfs.

**Comment by stgraber** [comment]
If moving from/to btrfs, using `btrfs send/receive` is likely better than rsync.
Moving things around, if the same partition should work fine, yes, if not the same partition, then btrfs will be pretty unhappy because of subvolumes.

**Comment by stgraber** [comment]
So if you're indeed on the same partition, then using `mv` is likely your best and by far fastest bet.

**Comment by stgraber** [comment]
The `lxdbr0` error suggests that you don't have a `lxdbr0` bridge anymore, possibly because that part of the migration blew up due to the lack of space too.

It's likely as simple as doing `lxc network create lxdbr0` to fix that one though, if the IP addresses are a concern, this can be tweaked afterwards easily enough.

**Comment by riverclimber** [comment]
I managed to copy containers and snapshots to the storage pool and rebooted the system.  Each container is on a separate subvol as is each snapshot.  I decided to leave the images for now (which I assume would not be an issue for the purpose of finishing the upgrade).

So I re-created lxdbr0 as you had suggested and the test container started.  This is when I discovered `/etc/default/lxd-bridge.upgraded`, which looks to be a valid `/etc/default/lxd-bridge` with the pre-upgrade subnet.  What would you recommend at this point?  Ideally, I'd like to keep the old config if possible.  Do I need to delete the bridge I just created?

**Comment by stgraber** [comment]
`/etc/default/lxd-bridge` isn't a thing anymore with LXD 2.1 and higher.

What's in `/etc/default/lxd-bridge.upgraded` and `/etc/default/lxd-bridge` and what does `lxc network show lxdbr0` get you?

We can make sure the settings are effectively the same, then you can delete the two files from /etc/default

**Comment by riverclimber** [comment]
The new lxdbrg0 interface is:

config:
  ipv4.address: 10.67.59.1/24
  ipv4.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/a
- /1.0/containers/b
- /1.0/containers/c
...
- /1.0/containers/z
managed: true
status: Created
locations:
- none

There's no longer a `/etc/default/lxd-bridge` - only `/etc/default/lxd-bridge.upgraded` exists. Here's its content:

USE_LXD_BRIDGE="true"
LXD_BRIDGE="lxdbr0"
UPDATE_PROFILE="true"
LXD_CONFILE=""
LXD_DOMAIN="lxd"
LXD_IPV4_ADDR="10.203.157.1"
LXD_IPV4_NETMASK="255.255.255.0"
LXD_IPV4_NETWORK="10.203.157.1/24"
LXD_IPV4_DHCP_RANGE="10.203.157.2,10.203.157.199"
LXD_IPV4_DHCP_MAX="198"
LXD_IPV4_NAT="true"
LXD_IPV6_ADDR=""
LXD_IPV6_MASK=""
LXD_IPV6_NETWORK=""
LXD_IPV6_NAT="false"
LXD_IPV6_PROXY="false"

**Comment by stgraber** [comment]
```
lxc network set lxdbr0 ipv6.address none
lxc network set lxdbr0 ipv4.address 10.203.157.1/24
```

That should have your LXD managed bridge behave like your old one.

**Comment by riverclimber** [comment]
Managed to bring the containers back online -- thanks for your help!  Some IPs on the bridge interface changed while others didn't.  Is this expected behaviour?

**Comment by riverclimber** [comment]
Could you please help finish migrating the images too?  The old `images` directory still looks like this:

0b969c724698d2337eba00540128e26b17ff608a761c28fe7f91b9aef14c3a6e
0b969c724698d2337eba00540128e26b17ff608a761c28fe7f91b9aef14c3a6e.rootfs

**Comment by stgraber** [comment]
Empty the `images` directory and restart the daemon, it should notice things being gone and update the database to match.

The IP addresses changing is expected as the leases aren't ported during upgrade.
dnsmasq uses a mostly stable way of generating IPs based off the mac, but that's not going to always work. You could manually set `ipv4.address` on the nic device of the affected containers if you want them to get their old IP back.

**Comment by riverclimber** [comment]
Is there a way of saving the images instead of purging them?

**Comment by stgraber** [comment]
In theory, yes, but you only seem to have a single image in there and that particular image is just a standard Ubuntu 18.04 amd64 image which will be downloaded again the next time you ask lxd to create such a container.

**Comment by riverclimber** [comment]
Impressive that you can tell the image content by hash!  I only included one as an example.  Here's the full directory:

0b969c724698d2337eba00540128e26b17ff608a761c28fe7f91b9aef14c3a6e
0b969c724698d2337eba00540128e26b17ff608a761c28fe7f91b9aef14c3a6e.rootfs
51f3c13772ca5fa6765e61800d516ad630e23c2a095dcc9884e8f53ddfa455c1
51f3c13772ca5fa6765e61800d516ad630e23c2a095dcc9884e8f53ddfa455c1.rootfs
943faaa9d3bda6053812f83bb566ac7b1d18f717462d2dbdab14842126de7ad0
db81e96f4cd956670c017ecd158dc20928b7d689d41d1a61cf582a82cd7c0eca
e9b4cf706cf82ada8a964883257ec8451c8c6e7150bd73640cd021563000f25a
e9b4cf706cf82ada8a964883257ec8451c8c6e7150bd73640cd021563000f25a.rootfs

**Comment by stgraber** [comment]
943faaa9d3bda6053812f83bb566ac7b1d18f717462d2dbdab14842126de7ad0
db81e96f4cd956670c017ecd158dc20928b7d689d41d1a61cf582a82cd7c0eca

Those two I can't find on our public image servers, so move them somewhere out of LXD's storage, /root or something would do.

Then remove the rest from the images directory and restart LXD.
After restart, confirm that `lxc image list` is empty.

Then for the two you moved aside, import them back with `lxc image import /path/to/the/file`

**Comment by stgraber** [comment]
Closing the issue as there's nothing really actionable for LXD here and I think we managed to get things back online. We can still chat about images here if anything is missing.
