### ISSUE TITLE
lxc exec environment does not change user

### ISSUE THREAD

**Issue by Miso-K** [lxc/lxd#5544]
LXD version 3.10
I am trying to open terminal with user without root privileges via rest api:

`lxc query -X POST -d '{"command":["bash"],"environment":{"HOME": "/home/demo", "TERM": "xterm", "USER": "demo"},"interactive":true,"wait-for-websocket":true}' /1.0/containers/nuclio/exec`

But after connection via websocket user is always root.

`wscat -c wss://127.0.0.1:8443/1.0/operations/8f945f67-78e4-4a7c-a022-b1c0036edcb8/websocket?secret=c1131b73c0cfd06646dd8aae8083c2b80d900c1e2477985d6f83bb2a0d6d089a -n`
`connected (press CTRL+C to quit)`
`< root@nuclio:~# `

It does not work even if I use lxc exec command:

`lxc exec --env USER=demo nuclio whoami`
`root`

**Comment by stgraber** [comment]
That's normal, you only changed the environment variable `USER` to `demo`, your shell probably then reset that back to match the user, which is always `root` when using `lxc exec`.

What you likely want to do here is call your shell through `sudo` or `su` instead.

Something like `"command": ["sudo", "-u", "demo", "-i"]` or `"command": ["su", "demo"]`
