### ISSUE TITLE
Error message should tell me *what* is not found

### ISSUE THREAD

**Issue by dhenrich** [lxc/lxd#5548]
LXD 3.10 on Ubuntu 16.04 LTS if you type:

`<dean@courage>:~$ lxc exec bash maas-2`

you get:

`Error: not found`

We should state what exactly is not found. It's not clear whether it's the command, the container, or what isn't found.

**Comment by stgraber** [comment]
Marking for later as @freeekanayaka mentioned, properly fixing this will take a long time.
We've already been fixing some of the infrastructure over the past few years to avoid this but there's still a very very long way before we have enough context in our internal error handling to be able to return something better to the client.

**Comment by stgraber** [comment]
The current `SmartError` wrapper just isn't good enough for this and neither is sending the full error chain (which is the other approach that's been taken recently), both are equally confusing to users in completely opposite ways.
