### ISSUE TITLE
While Accessing the console of an Instance Unable to load console. Please reload page to try again. (Error: Console is currently unavailable.)

### ISSUE THREAD

**Issue by agupta1702** [lxc/lxd#5564]
Hello All 

From The given Reference from https://www.ubuntu.com/openstack/install I installed the Workstation model on Single Server All installation is completed successfully I also assigned the floating IP to the created instances to enable the SSH access for the instance from the Controller end. but while accessing instance from the console getting error:
 Unable to load console. Please reload page to try again.
Error: Console is currently unavailable.  I tried vnc, novnc, spice, serial and xvpvnc console one by one to get instance console configured but still no luck so Far.

Following is the reference of Version i am Using 
Base OS Ubuntu 16.04 LTS
lxd verion 3.11
juju version 2.5.0-xenial-amd64

All 16 container are running and I checked in the juju gui the console is getting configured properly.
![image](https://user-images.githubusercontent.com/47646883/54314939-f07b4480-4602-11e9-8e42-38cf88cb6852.png)

I also Tested with Controller node 
nova get-vnc-console instance_name novnc
nova --debug get-vnc-console instance_name novnc

ERROR (HTTPNotImplemented): The requested functionality is not supported. (HTTP 501) (Request-ID: req-9cdbce94-90a4-40a1-b391-1b0ba0d0f417)

**Comment by stgraber** [comment]
Sorry but this isn't a LXD issue.

I'd suggest you report this against the particular flavor of openstack you've deployed as this error appears to be coming through nova (possibly through the nova-lxd bridge if that's what you're using here).

**Comment by agupta1702** [comment]
@stgraber Thankyou for Responding I installed the Workstation model from this Reference as i am new to the Openstack https://www.ubuntu.com/openstack/install.

**Comment by stgraber** [comment]
@ajkavanagh where is the right place for this bug?

**Comment by agupta1702** [comment]
@ajkavanagh I opened it under this category
https://github.com/conjure-up/conjure-up/issues/1592

**Comment by ajkavanagh** [comment]
This bug should probably be filed under nova-lxd at https://bugs.launchpad.net/nova-lxd - I've raised this one (https://bugs.launchpad.net/nova-lxd/+bug/1820021) that also references https://github.com/conjure-up/conjure-up/issues/1592
