### ISSUE TITLE
lxd export fails with lvm/xfs storage

### ISSUE THREAD

**Issue by esosan** [lxc/lxd#5566]
# Required information

 * Distribution: ubuntu
 * Distribution version: 18.04
 * Kernel version: 4.15.0-46-generic
 * LXC version: 3.11 (snap)
 * LXD version: 3.11 (snap)
 * Storage backend in use: LVM with XFS (without thin provisioning)

# Issue description

lxc export c1 c1.tar.xz fails when the storage is lvm and xfs. I don't use thin provisioning, but I don't think it's relevant.
I also try with --optimized-storage --container-only (just in case)

Error: Create backup: Backup storage: Mount /dev/pool_lxc0/containers_snapshot--55c8df9e--6e85--432e--bec7--ab5d8642d2b2 onto /var/snap/lxd/common/lxd/storage-pools/pool0/containers/snapshot-55c8df9e-6e85-432e-bec7-ab5d8642d2b2: invalid argument

# Information to attach
I have look to the various logs files, the only relevant output i found is on /var/log/syslog:
XFS (dm-19): Filesystem has duplicate UUID c6973371-ce32-4068-b5ef-12d69ff33fb5 - can't mount

Googling this kind of problem I found it's possibile to mount with the option -o nouuid or generate a new uuid with xfs_admin tool.  I don't know if relevant...

BTW, now in /var/snap/lxd/common/lxd/backups I have a lots empty dirs. Can I delete them without problems?

**Comment by stgraber** [comment]
Taking a look at this one.

For your empty dirs, they're safe to remove, they will be re-created when needed.

**Comment by stgraber** [comment]
managed to reproduce the issue. The problem is indeed with the duplicate UUIDs, the snapshot needs to get its UUID rewritten before mount which shouldn't be super hard
