### ISSUE TITLE
Live migration with openvswitch

### ISSUE THREAD

**Issue by haha150** [lxc/lxd#5568]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version: 3.11 from snap
   * Storage backend in use: btrfs

# Issue description

I am trying to use openvswitch instead of the lxdbr0 and i am able to do so but i cannot live migrate a container attached to the openvswitch to another remote. The two machines are exactly the same and both run openvswitch with the same name of the switch etc. So when i do "lxc move c1 remote2:", i get the error that the restore fails because it cannot attach the vethXXXX interface to the openvswitch at the destionation. Am i doing something wrong?

# Steps to reproduce

assume that i have one container and two remotes running alpine/edge container

lxc network create ovs-1 bridge.driver=openvswitch
ovs-vsctl add-port ovs-1 enp0s8
lxc network attach-profile ovs-1 default eth0
lxc launch images:alpine/edge c1
lxc move c1 remote2: <---error

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Full details:
```
root@vm03:~# lxc move vm02:a1 local: --mode=relay
Error: Error transferring container data: migration restore failed
(00.000055) Warn  (criu/log.c:203): The early log isn't empty
(00.009473) Warn  (criu/net.c:2867): Unable to get tun network namespace
(00.116293) Warn  (criu/cr-restore.c:1266): Set CLONE_PARENT | CLONE_NEWPID but it might cause restore problem,because not all kernels support such clone flags combinations!
(00.564266) Error (criu/net.c:2929): Can't add interface veth2D98Q0 to bridge lxdbr0: Operation not supported
(00.644744) Error (criu/cr-restore.c:2294): Restoring FAILED.
root@vm03:~# 
```

**Comment by stgraber** [comment]
This shows that CRIU appears to have detected the network interface as bridged and so attempted to re-add to the target bridge. Unfortunately it doesn't appear to know that openvswitch bridges are special and you can't use the same netlink call to attach a nic to one of those.

All this happens within CRIU outside of LXD or LXC's control, so it's unfortunately not really something we can do much about. You may want to file a bug against https://github.com/checkpoint-restore/criu to either add the missing logic to re-attach to openvswitch or add logic to detect non-standard bridged interfaces during dump and refuse dumping (so you don't end up with a non-restorable container).

**Comment by adrianreber** [comment]
@stgraber Are you able to reproduce this? Can you see in any of the logs the full command-line that is used to run CRIU?

**Comment by stgraber** [comment]
I wiped my test systems after reproducing the issue unfortunately, I'll re-reproduce it and grab our detailed criu output this time around.

**Comment by stgraber** [comment]
dump: https://paste.ubuntu.com/p/MbdJTZpPJW/
restore: https://paste.ubuntu.com/p/4GP2ZCcBdw/

@adrianreber

**Comment by stgraber** [comment]
dump command: /snap/lxd/current/criu/criu dump --tcp-established --file-locks --link-remap --manage-cgroups=full --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /tmp/lxd_checkpoint_150842847/final -o /tmp/lxd_checkpoint_150842847/final/dump.log --cgroup-root  /lxc.payload/c1 --cgroup-root name=systemd /lxc.payload/c1 --cgroup-root blkio /lxc.payload/c1 --cgroup-root cpu,cpuacct /lxc.payload/c1 --cgroup-root hugetlb /lxc.payload/c1 --cgroup-root memory /lxc.payload/c1 --cgroup-root net_cls,net_prio /lxc.payload/c1 --cgroup-root perf_event /lxc.payload/c1 --cgroup-root devices /lxc.payload/c1 --cgroup-root pids /lxc.payload/c1 --cgroup-root freezer /lxc.payload/c1 --cgroup-root cpuset /lxc.payload/c1 --cgroup-root rdma /lxc.payload/c1 -vvvvvv --action-script /tmp/lxd_checkpoint_150842847/action.sh --ext-mount-map /dev/fuse dev/fuse --ext-mount-map /dev/net/tun dev/net/tun --ext-mount-map /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc --ext-mount-map /sys/fs/fuse/connections sys/fs/fuse/connections --ext-mount-map /sys/fs/pstore sys/fs/pstore --ext-mount-map /sys/kernel/debug sys/kernel/debug --ext-mount-map /sys/kernel/security sys/kernel/security --ext-mount-map /dev/mqueue dev/mqueue --ext-mount-map /dev/lxd dev/lxd -t 4610 --skip-in-flight --freeze-cgroup /sys/fs/cgroup/freezer///lxc.payload/c1 --ext-mount-map /dev/console console --external tty[8800:33] --prev-images-dir ../003 --track-mem --force-irmap --ghost-limit 268435456

restore command: /snap/lxd/current/criu/criu restore --tcp-established --file-locks --link-remap --manage-cgroups=full --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /tmp/lxd_restore_154854612/final -o /tmp/lxd_restore_154854612/final/restore.log --cgroup-root  /lxc.payload/c1 --cgroup-root name=systemd /lxc.payload/c1 --cgroup-root hugetlb /lxc.payload/c1 --cgroup-root memory /lxc.payload/c1 --cgroup-root blkio /lxc.payload/c1 --cgroup-root perf_event /lxc.payload/c1 --cgroup-root net_cls,net_prio /lxc.payload/c1 --cgroup-root cpuset /lxc.payload/c1 --cgroup-root freezer /lxc.payload/c1 --cgroup-root devices /lxc.payload/c1 --cgroup-root pids /lxc.payload/c1 --cgroup-root cpu,cpuacct /lxc.payload/c1 --cgroup-root rdma /lxc.payload/c1 -vvvvvv --ext-mount-map dev/fuse /dev/fuse --ext-mount-map dev/net/tun /dev/net/tun --ext-mount-map proc/sys/fs/binfmt_misc /proc/sys/fs/binfmt_misc --ext-mount-map sys/fs/fuse/connections /sys/fs/fuse/connections --ext-mount-map sys/fs/pstore /sys/fs/pstore --ext-mount-map sys/kernel/debug /sys/kernel/debug --ext-mount-map sys/kernel/security /sys/kernel/security --ext-mount-map dev/mqueue /dev/mqueue --ext-mount-map dev/lxd /var/snap/lxd/common/lxd/devlxd --root /var/snap/lxd/common/lxc/ --restore-detached --restore-sibling --inherit-fd fd[6]:tty[8800:33] --ext-mount-map console /dev/pts/0 --lsm-profile apparmor:lxd-c1_</var/snap/lxd/common/lxd>//&:lxd-c1_<var-snap-lxd-common-lxd>: --external veth[eth0]:vethKGTF3A@lxdbr0

**Comment by adrianreber** [comment]
@stgraber That was fast. Thanks! Can you see the command-line LXC creates to call CRIU.

I think the output from this line would be important to know (I hope):

https://github.com/lxc/lxc/blob/master/src/lxc/criu.c#L639

**Comment by adrianreber** [comment]
There it is. Thanks. Too slow on my side :grin:

**Comment by stgraber** [comment]
Looks like we're passing --external for the veth along with the bridge name which is what liblxc knows at that point, unfortunately it's not a normal bridge so the normal attach doesn't work.

**Comment by stgraber** [comment]
lxc.conf and lxc.log on restore side:
```
root@vm03:~# cat /var/snap/lxd/common/lxd/logs/c1/lxc.conf
lxc.log.file = /var/snap/lxd/common/lxd/logs/c1/lxc.log
lxc.log.level = info
lxc.console.buffer.size = auto
lxc.console.size = auto
lxc.console.logfile = /var/snap/lxd/common/lxd/logs/c1/console.log
lxc.mount.auto = proc:rw sys:rw
lxc.autodev = 1
lxc.pty.max = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional 0 0
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional 0 0
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none rbind,create=dir,optional 0 0
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional 0 0
lxc.include = /snap/lxd/current/lxc/config//common.conf.d/
lxc.arch = linux64
lxc.hook.pre-start = /snap/lxd/current/bin/lxd callhook /var/snap/lxd/common/lxd 3 start
lxc.hook.post-stop = /snap/lxd/current/bin/lxd callhook /var/snap/lxd/common/lxd 3 stop
lxc.tty.max = 0
lxc.uts.name = c1
lxc.mount.entry = /var/snap/lxd/common/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.apparmor.profile = lxd-c1_</var/snap/lxd/common/lxd>//&:lxd-c1_<var-snap-lxd-common-lxd>:
lxc.seccomp.profile = /var/snap/lxd/common/lxd/security/seccomp/c1
lxc.idmap = u 0 1000000 1000000000
lxc.idmap = g 0 1000000 1000000000
lxc.rootfs.path = dir:/var/snap/lxd/common/lxd/containers/c1/rootfs
lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.link = lxdbr0
lxc.net.0.hwaddr = 00:16:3e:20:8b:11
lxc.net.0.name = eth0
lxc.mount.auto = shmounts:/var/snap/lxd/common/lxd/shmounts/c1:/dev/.lxd-mounts

root@vm03:~# cat /var/snap/lxd/common/lxd/logs/c1/lxc.log
lxc c1 20190315142154.413 INFO     lsm - lsm/lsm.c:lsm_init:50 - LSM security driver AppArmor
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "reject_force_umount  # comment this to allow umount -f;  not recommended"
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for reject_force_umount action 0(kill)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for reject_force_umount action 0(kill)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for reject_force_umount action 0(kill)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for reject_force_umount action 0(kill)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "[all]"
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "kexec_load errno 38"
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for kexec_load action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for kexec_load action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for kexec_load action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for kexec_load action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "open_by_handle_at errno 38"
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for open_by_handle_at action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for open_by_handle_at action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for open_by_handle_at action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for open_by_handle_at action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "init_module errno 38"
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for init_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for init_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for init_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for init_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "finit_module errno 38"
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for finit_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for finit_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for finit_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for finit_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:759 - Processing "delete_module errno 38"
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for delete_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for delete_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for delete_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for delete_module action 327718(errno)
lxc c1 20190315142154.413 INFO     seccomp - seccomp.c:parse_config_v2:970 - Merging compat seccomp contexts into main context
lxc c1 20190315142154.413 INFO     conf - conf.c:run_script_argv:371 - Executing script "/snap/lxd/current/bin/lxd callhook /var/snap/lxd/common/lxd 3 start" for container "c1", config section "lxc"
lxc c1 20190315142154.664 INFO     start - start.c:lxc_init:902 - Container "c1" is initialized
lxc c1 20190315142154.665 INFO     cgfsng - cgroups/cgfsng.c:cgfsng_payload_create:1453 - The container process uses "lxc.payload/c1" as cgroup
lxc c1 20190315142154.666 INFO     criu - criu.c:exec_criu:639 - execing: /snap/lxd/current/criu/criu restore --tcp-established --file-locks --link-remap --manage-cgroups=full --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /tmp/lxd_restore_154854612/final -o /tmp/lxd_restore_154854612/final/restore.log --cgroup-root :/lxc.payload/c1 --cgroup-root name=systemd:/lxc.payload/c1 --cgroup-root hugetlb:/lxc.payload/c1 --cgroup-root memory:/lxc.payload/c1 --cgroup-root blkio:/lxc.payload/c1 --cgroup-root perf_event:/lxc.payload/c1 --cgroup-root net_cls,net_prio:/lxc.payload/c1 --cgroup-root cpuset:/lxc.payload/c1 --cgroup-root freezer:/lxc.payload/c1 --cgroup-root devices:/lxc.payload/c1 --cgroup-root pids:/lxc.payload/c1 --cgroup-root cpu,cpuacct:/lxc.payload/c1 --cgroup-root rdma:/lxc.payload/c1 -vvvvvv --ext-mount-map dev/fuse:/dev/fuse --ext-mount-map dev/net/tun:/dev/net/tun --ext-mount-map proc/sys/fs/binfmt_misc:/proc/sys/fs/binfmt_misc --ext-mount-map sys/fs/fuse/connections:/sys/fs/fuse/connections --ext-mount-map sys/fs/pstore:/sys/fs/pstore --ext-mount-map sys/kernel/debug:/sys/kernel/debug --ext-mount-map sys/kernel/security:/sys/kernel/security --ext-mount-map dev/mqueue:/dev/mqueue --ext-mount-map dev/lxd:/var/snap/lxd/common/lxd/devlxd --root /var/snap/lxd/common/lxc/ --restore-detached --restore-sibling --inherit-fd fd[6]:tty[8800:33] --ext-mount-map console:/dev/pts/0 --lsm-profile apparmor:lxd-c1_</var/snap/lxd/common/lxd>//&:lxd-c1_<var-snap-lxd-common-lxd>: --external veth[eth0]:vethKGTF3A@lxdbr0 
lxc c1 20190315142155.141 ERROR    criu - criu.c:do_restore:1100 - criu process exited 1, output:

lxc c1 20190315142155.144 INFO     conf - conf.c:run_script_argv:371 - Executing script "/snap/lxd/current/lxcfs/lxc.reboot.hook" for container "c1", config section "lxc"
lxc 20190315142155.144 WARN     commands - commands.c:lxc_cmd_rsp_recv:133 - Connection reset by peer - Failed to receive response for command "get_state"
lxc c1 20190315142155.647 INFO     conf - conf.c:run_script_argv:371 - Executing script "/snap/lxd/current/bin/lxd callhook /var/snap/lxd/common/lxd 3 stop" for container "c1", config section "lxc"
lxc c1 20190315142155.683 ERROR    criu - criu.c:__criu_restore:1432 - restore process died
```

**Comment by stgraber** [comment]
Yeah, getting a reproducing environment is pretty simple, just deployed two Ubuntu 18.04 VMs, then ran:

```
snap install lxd --edge
lxd.migrate -yes
snap set lxd daemon.debug=true criu.enable=true openvswitch.builtin=true
snap restart lxd
lxd init --auto
lxc network set lxdbr0 bridge.driver openvswitch
lxc config set core.https_address :8443
lxc config set core.trust_password test
lxc remote add other-vm vm02.maas.mtl.stgraber.net
lxc move other-vm:container local:
```

**Comment by adrianreber** [comment]
And LXC does https://github.com/lxc/lxc/blob/master/src/lxc/criu.c#L576
```
						ret = snprintf(buf, sizeof(buf),
							       "veth[%s]:%s@%s",
							       eth, veth,
							       n->link);
					else
						ret = snprintf(buf, sizeof(buf),
							       "%s=%s@%s", eth, veth, n->link);
```

and it uses `lxc.net.0.link = lxdbr0`. So LXC needs to use some other information at that point.

**Comment by adrianreber** [comment]
So the bridge is still called `lxdbr0`?

**Comment by stgraber** [comment]
The LXD edge snap uses the current master branch of CRIU too FWIW.

@adrianreber liblxc has lxc_bridge_attach which calls is_ovs_bridge and then jumps to lxc_ovs_attach_bridge for the attach in such cases, I guess we either need an equivalent in CRIU or we need to add logic to criu.c in liblxc to detect that the bridge is openvswitch and not tell CRIU to attach the veth, instead having liblxc do it through lxc_bridge_attach

**Comment by stgraber** [comment]
Yep, bridge is still called lxdbr0, it's just using openvswitch as a backend rather than normal Linux bridging.

So the interface exists but it doesn't have the usual `bridge` directory and API:
```
root@vm03:~# ls /sys/class/net/lxdbr0/ -l
total 0
-r--r--r-- 1 root root 4096 Mar 15 14:16 addr_assign_type
-r--r--r-- 1 root root 4096 Mar 15 14:16 address
-r--r--r-- 1 root root 4096 Mar 15 14:31 addr_len
-r--r--r-- 1 root root 4096 Mar 15 14:31 broadcast
-rw-r--r-- 1 root root 4096 Mar 15 14:31 carrier
-r--r--r-- 1 root root 4096 Mar 15 14:31 carrier_changes
-r--r--r-- 1 root root 4096 Mar 15 14:31 carrier_down_count
-r--r--r-- 1 root root 4096 Mar 15 14:31 carrier_up_count
-r--r--r-- 1 root root 4096 Mar 15 14:31 dev_id
-r--r--r-- 1 root root 4096 Mar 15 14:31 dev_port
-r--r--r-- 1 root root 4096 Mar 15 14:31 dormant
-r--r--r-- 1 root root 4096 Mar 15 14:31 duplex
-rw-r--r-- 1 root root 4096 Mar 15 14:31 flags
-rw-r--r-- 1 root root 4096 Mar 15 14:31 gro_flush_timeout
-rw-r--r-- 1 root root 4096 Mar 15 14:31 ifalias
-r--r--r-- 1 root root 4096 Mar 15 14:16 ifindex
-r--r--r-- 1 root root 4096 Mar 15 14:16 iflink
-r--r--r-- 1 root root 4096 Mar 15 14:31 link_mode
-rw-r--r-- 1 root root 4096 Mar 15 14:31 mtu
-r--r--r-- 1 root root 4096 Mar 15 14:16 name_assign_type
-rw-r--r-- 1 root root 4096 Mar 15 14:31 netdev_group
-r--r--r-- 1 root root 4096 Mar 15 14:31 operstate
-r--r--r-- 1 root root 4096 Mar 15 14:31 phys_port_id
-r--r--r-- 1 root root 4096 Mar 15 14:31 phys_port_name
-r--r--r-- 1 root root 4096 Mar 15 14:31 phys_switch_id
drwxr-xr-x 2 root root    0 Mar 15 14:31 power
-rw-r--r-- 1 root root 4096 Mar 15 14:31 proto_down
drwxr-xr-x 4 root root    0 Mar 15 14:16 queues
-r--r--r-- 1 root root 4096 Mar 15 14:31 speed
drwxr-xr-x 2 root root    0 Mar 15 14:31 statistics
lrwxrwxrwx 1 root root    0 Mar 15 14:16 subsystem -> ../../../../class/net
-rw-r--r-- 1 root root 4096 Mar 15 14:31 tx_queue_len
-r--r--r-- 1 root root 4096 Mar 15 14:16 type
-rw-r--r-- 1 root root 4096 Mar 15 14:16 uevent
```

**Comment by adrianreber** [comment]
Okay, so CRIU does not know how to connect the interface to the bridge. So, from my point of view, the best solution would be that CRIU does not touch the networking at all, but all the network namespace configuration is done by LXC and CRIU only restores the container into that existing namespace.

That sounds like a lot of changes to how LXC uses CRIU.

**Comment by stgraber** [comment]
@adrianreber I wonder, can we just tell CRIU to restore the veth but not connect it?
If we have the name of the host side veth, then it becomes easy for liblxc to call our existing bridge attach function on it post-restore.
