### ISSUE TITLE
Support deleting multiple containers at once (possibly all)

### ISSUE THREAD

**Issue by castrojo** [lxc/lxd#558]
It'd be nice to just clean up all the containers on a machine with something like `lxc delete *` or `lxc delete -a` (or something similar.)

**Comment by marcoceppi** [comment]
I think it'd be better instead to just allow multiple container names in the delete line

`lxc delete host:c1 c2 c5` that way the action is more explicit to avoid accidental deletions.

**Comment by basak** [comment]
FTR, uvt-kvm currently does what Marco says, which also means that `uvt-kvm list|xargs uvt-kvm destroy` works. It doesn't currently support `*` or `-a` but I'm not too opposed to that. I favour `-a` since the `*` would need escaping and `\*` is more awkward than `-a`.

**Comment by stgraber** [comment]
Supporting multiple container names would be fine with me, we may want to consider what other command would benefit from a similar behavior (for consistency).

**Comment by jgriffiths1993** [comment]
I think that this would be best for `delete`, `start`, `stop` and `restart`

**Comment by Nekrose483** [comment]
when issueing the command sudo lxc delete * i just get an "error: not found"

**Comment by Nekrose483** [comment]
though, any name i give it, even if its a legic lxd container, says its not found.

**Comment by tlundin** [comment]
you can write a one liner for it. Replace destroy with any other command. 
lxc-destroy $(lxc-ls|awk 'NR==1{print $1}')

**Comment by miathedev** [comment]
Was there something added like lxc delete all ?
Im a little bit frustrated deleting > 100 containers by hand now - i would prefer to go to bed now if i could...
awk and grep is not available on my host...

**Comment by monstermunchkin** [comment]
@miathedev Nothing like that has been added. You can however delete all container by running `lxc rm -f $(lxc ls -c n --format csv)`. No external tools needed.

**Comment by AliEbrahimpour** [comment]
you can use :
`for i in $(lxc-ls) ; do lxc-stop $i; done`
