### ISSUE TITLE
Command names are inconsistent across different tools

### ISSUE THREAD

**Issue by basak** [lxc/lxd#559]
`uvt-kvm` does `create` and `destroy`, but `lxc` has `launch` and `delete` for what are essentially the same operations. Can we figure out how to keep things more consistent for a better UX for users of multiple tools?

**Comment by stgraber** [comment]
The lxc command line interface went through several rounds of review, including user testing and asking the design team for their opinion.

The actual commands have then been reviewed in recent design meetings to ensure that things are consistent (anything that's created gets deleted, anything that's added gets removed, ...) so I don't see us changing this any time soon.

We did discuss the possibility of supporting aliases and short names for the commands (shorted unique match) and that may address your concerns, but I don't see us making any drastic changes to our current naming.
