### ISSUE TITLE
lxd users $HOME must begin with /home

### ISSUE THREAD

**Issue by geodb27** [lxc/lxd#5590]
* Distribution: ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.18.0-16-generic
   * LXC version: 3.11
   * LXD version: 3.11 (snap)
   * Storage backend in use: DIR

If the home directory of a user don't start by /home, lxc commands are not usable at all.

# Steps to reproduce

 1. Step one
As per the doc says, for a user to be abble to use lxc/lxd, he must belong to the group lxd.
So, I created a user for my needs : 
$ useradd -g users -G lxd root-dns -d /appli/root-dns -m
$ ls -ld /appli/root-dns
drwxr-xr-x  3 root-dns users 4096 mars  20 12:26 root-dns/
$ su - root-dns
root-dns $ lxc list
cannot create user data directory: /appli/root-dns/snap/lxd/10343: Read-only file system

 2. Step two
So, I went to the "old-way" : 
$ usermod -d /home/root-dns root-dns
$ ls -ld /home/root-dns
drwxr-xr-x  3 root-dns users     4096 mars  20 12:25 root-dns
$ su - root-dns
root-dns $ lxc list
Gave the expected result, no error

 3. Step three
I wanted to be sure, so I made this test : 
$ usermod -d /home/root-users root-dns
$ ls -ld /home/root-users
drwxr-xr-x 3 root-dns users 4096 mars  20 17:12 /home/root-users
$ su - root-dns
root-dns $ lxc list
Again this worked fine.

So, my conclusion to this is that the home directory of any lxd user must be in /home, why is that so ? To me, this shouldn't be mandatory and should work wherever the home directory is stored.

**Comment by stgraber** [comment]
Those errors unfortunately aren't coming from LXD but from snapd and I can indeed confirm that users that have a home directory outside of /home are having problems with snaps.

The reason for this is rather complex, but the short version is that snaps don't run with the same root filesystem as your system, they run with a read-only minimal root filesystem which then gets a number of things mounted over from the main filesystem, including your home directory. If your home directory is in a part of the filesystem which does not exist in the minimal filesystem, in your case `/appli`, then the mount cannot happen and the directory cannot be created as the filesystem is read-only...

May I suggest you bring this up here: https://forum.snapcraft.io
And ideally post a link back in this issue so others can find it easily and comment there too?
I know of a couple others that ran into similar problems so hopefully we can have the snapd developers figure out a way around this.

**Comment by geodb27** [comment]
Hi stgraber :-)
I did as you suggested and the report on snapcraft.io can be viewed/read here : https://forum.snapcraft.io/t/lxd-users-home-must-begin-with-home/10553
Once again, thanks again for your kind help !
