### ISSUE TITLE
Please provide Ubuntu .deb packages as an alternative to Snap

### ISSUE THREAD

**Issue by pgauret** [lxc/lxd#5593]
For those of us who do not wish to use Snap on Ubuntu, would it be possible to bring back the good old .deb packages? Maybe this could be done in a PPA.

**Comment by Anachron** [comment]
Why not repackage https://linuxcontainers.org/lxd/downloads/ ?

**Comment by stgraber** [comment]
Maintaining both deb and snap with our release schedule isn't practical and not something that the LXD team itself has time for. The snap also saves us from having to produce packages for another 10+ distros and significantly simplifies support.

If someone wants to make deb packages for LXD and maintain them in a PPA or a separate repository, there's nothing wrong with that, we just won't be doing it ourselves.

Do note that Ubuntu 18.04 LTS does still have deb packages for LXD, but that's limited to the LXD 3.0 LTS release and its bugfix releases.
