### ISSUE TITLE
REST API documentation insufficient for new daemon implementation

### ISSUE THREAD

**Issue by rcj4747** [lxc/lxd#561]
The REST API appears to be written for an audience interested in development using the client API.  There is interest in developing a new daemon to support LXD clients and the documentation would need to provide more clarity before that could be done.

**Comment by stgraber** [comment]
Agreed though we are more likely to make progress on that when asked specific questions or pointed at particular bits being unclear than as a single task to go through the whole thing and attempt to cover everything at once.

**Comment by rcj4747** [comment]
Agreed, more specifics are forthcoming.   I jumped the gun on opening the bug.

**Comment by megastef** [comment]
Does the API exposes performance metrics like the Docker stats interface?

**Comment by stgraber** [comment]
At the moment, very little runtime information is exposed, however we have #295 that I still need to work on (trick is coming up with a few to expose all the cgroup and other runtime information, yet keep thing consistent naming-wise with the way they're set and also not be overly implementation-specific).

**Comment by stgraber** [comment]
I'm closing this issue since we've significantly reworked the rest-api.md document and had a number of people successfully writing language bindings and tooling using that documentation.
