### ISSUE TITLE
Live migration dumping failure

### ISSUE THREAD

**Issue by haha150** [lxc/lxd#5611]
# Required information

 * Distribution: ubuntu 18.04
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 3.11
   * LXD version: 3.11
   * Storage backend in use: btrfs

# Issue description

When i try to live migrate a container, whether it uses macvlan, p2p or nothing as nictype it fails to dump when i do lxc move.

Error: Failed container creation: Error transferring container data: migration dump failed
(00.234161) Warn  (compel/arch/x86/src/lib/infect.c:273): Will restore 17885 with interrupted system call
(00.649175) Warn  (compel/arch/x86/src/lib/infect.c:273): Will restore 18153 with interrupted system call
(00.869486) Warn  (compel/arch/x86/src/lib/infect.c:273): Will restore 18503 with interrupted system call
(00.871263) Error (criu/page-xfer.c:372): No parent image found, though parent directory is set: No such file or directory
(01.070734) Error (criu/page-xfer.c:372): No parent image found, though parent directory is set: No such file or directory
(01.314936) Error (criu/net.c:568): Unsupported link 4 (type 1 kind erspan)
(01.329132) Error (criu/namespaces.c:1090): Namespaces dumping finished with error 65280
(01.338879) Error (criu/cr-dump.c:1732): Dumping FAILED.

# Steps to reproduce
Even if i use the default profile that is given when i do lxd init with or without lxdbr0
 1. lxc launch images:alpine/edge test
 2. lxc move test remote2:
 3. Fail

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
```
(01.314936) Error (criu/net.c:568): Unsupported link 4 (type 1 kind erspan)
```

This shows that your container has an interface of type `erspan` which CRIU doesn't know how to serialize, causing the dump to fail.

Either unload whatever kernel module is causing that device to appear on your system, or reach out to the CRIU folks to find a way to dump such devices.

**Comment by haha150** [comment]
yes thanks, it looks like its true, i had a GRE tunnel running in the host which caused it
