### ISSUE TITLE
Live migration with Ipv6 

### ISSUE THREAD

**Issue by haha150** [lxc/lxd#5612]
# Required information

 * Distribution: Ubuntu 18.04
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 3.11
   * LXD version: 3.11
   * Storage backend in use: btrfs

# Issue description

So i have another issue (sorry), when i try to live migrate a clean container running a iperf server with ipv6 it gives me a issue that it cant bind inet socket back: cannot assign the requested address. But it works when i just run the iperf server with ipv6 but not having any client connected to it, that migrates fine. 

And in some cases when i migrate with having a client connected to the ipv6 iperf server in the container, it migrates but then the iperf server dies after migration.

Error: Failed container creation: Error transferring container data: migration restore failed
(00.001663) Warn  (criu/cr-restore.c:1272): Set CLONE_PARENT | CLONE_NEWPID but it might cause restore problem,because not all kernels support such clone flags combinations!
(00.083251)    788: Error (soccr/soccr.c:497): Can't bind inet socket back: Cannot assign requested address
(00.083270)    788: Error (criu/files.c:1203): Unable to open fd=4 id=0x1a
(00.084801)    787: Error (criu/cr-restore.c:1421): 788 exited, status=1
(00.086583) Error (criu/cr-restore.c:2300): Restoring FAILED.

Edit:
all of this works with ipv4, just not with ipv6

# Steps to reproduce

 1. lxc launch images:alpine/edge test
 2. install iperf in container
 3. set ipv6 addr, global 
 4. lxc move test remote2:

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Closing as this is ultimately a CRIU bug, not a LXD one, LXD/LXC don't directly handle the dump/restore of network configuration and network connections in CRIU. Probably best to look for an existing issue or file one at https://github.com/checkpoint-restore/criu

As this is specific to IPv6, it may be interesting to know if privacy addressing was enabled and if it was, whether one of those addresses was in use. I'd expect the main link-local and global addresses to be restored by CRIU, but I don't know what it's doing with temporary addresses such as those used for privacy extensions.

**Comment by haha150** [comment]
hio again I tested some more and i can successfully migrate a container that runs iperf ipv6 server with 1 client connected to it. However, when the migration runs and is near the finish, the TCP connection from the server sends a FIN to the client and terminates the server and then successfully migrates. This does not happen with ipv4, do you have any idea?

**Comment by haha150** [comment]
Hi,

Is it possible to make lxd installed from snap, use CRIU from git master of CRIU? because based on this issue: https://github.com/checkpoint-restore/criu/issues/662# the CRIU version that you are using in lxd 3.11 does not use the CRIU version that potentially supports ipv6 TCP connection migration

**Comment by stgraber** [comment]
@haha150 the LXD snap uses the latest CRIU release (3.11). If you want the git master of CRIU, the LXD edge snap uses that.
