### ISSUE TITLE
[Feature Request] Support for bridge vlan tagging

### ISSUE THREAD

**Issue by lhorace** [lxc/lxd#5627]
# Required information

 * Distribution: ArchLinux
 * Distribution version: Rolling release
 * The output of "lxc info" or if that fails:
https://gist.github.com/0758e6f063cfd24d7bf93a54dce65d36

# Issue description

Is there any intention to supporting vlan on native Linux bridge ports? The impression was this was lack of support in liblxc, see https://github.com/lxc/lxd/issues/3375#issuecomment-362744762?

**Comment by stgraber** [comment]
As stated in that comment, LXD doesn't handle that part, instead relying on liblxc.

Someone needs to first add an option directly in liblxc (not some external shell script) which extends the network config options and works with both native Linux bridges and OpenvSwitch, then LXD can make use of this.

**Comment by lhorace** [comment]
Great, could you point to where we can put in a request to have someone look at this? That's been a mystery to me figuring out the maintainer of liblxc?

**Comment by stgraber** [comment]
@brauner and I are the maintainers for liblxc too, the existing issue against liblxc is just fine for tracking this. We just haven't seen sufficient demand for this to justify us doing this work ourselves and nobody from the community seem to have had interest in sending a branch that implements it.
