### ISSUE TITLE
LXD Containers inside AWS EC2 Instance Routing Problems

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#5628]
# Required information

 * Distribution: **Ubuntu**
 * Distribution version: **18.04.2 LTS**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.15.0-1021-aws**
   * LXC version: **3.0.3**
   * LXD version: **3.0.3**
   * Storage backend in use: **zfs**

# Issue description

When we setup LXD inside AWS Instances, we find that we keep running into issues where the containers don't seem to have proper internet access. From within the containers we can ping anything on the public internet, but when we try and do `apt update` or `curl google.com -vvvv`, it does to work. Almost as if only ICMP traffic is working but no TCP/UDP traffic. We keep seeing IPv6 addresses trying to resolve - see quotes below:

In our setup we have disabled IPv6 on our lxdbr0 config:

`
lxc network show lxdbr0
config:
  ipv4.address: 10.8.120.1/24
  ipv4.nat: "true"
  ipv6.address: none
  ipv6.nat: "false"
description: ""
name: lxdbr0
type: bridge
`

We don't know what we can do to get this to work. We find it only happens with LXD containers. 

Can it be something to do with the subnets that lxd is using? 

# Information to attach
[apt-update.log](https://github.com/lxc/lxd/files/3033869/apt-update.log)
[curl_request.log](https://github.com/lxc/lxd/files/3033870/curl_request.log)

**Comment by stgraber** [comment]
Looks like you're hitting some odd timeouts, it may be MTU related?

Can you check what's the MTU on the host's main network interface and try to set `bridge.mtu` on the LXD network to match that?

That could explain why ICMP is going through but TCP/UDP isn't, though normally you'd expect PMTU discovery to detect this and automatically reduce the MTU, not sure why the AWS network isn't doing that.
