### ISSUE TITLE
apt update fails to connect but ping works in container

### ISSUE THREAD

**Issue by foveann** [lxc/lxd#5629]
# Required information
 * Distribution: Ubuntu 18.04.02 LTS on Fedora 29 host
 * Distribution version: 18.04.2 LTS
 * The output of "lxc info" or if that fails:
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
**************************************************************
    -----END CERTIFICATE-----
  certificate_fingerprint: *******************************
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 5.0.5-200.fc29.x86_64
  server: lxd
  server_pid: 5939
  server_version: "3.11"
  storage: zfs
  storage_version: 0.7.13-1
  server_clustered: false
  server_name: ********
  project: default

# Issue description

I created a container Ubuntu 18.04 on host Fedora 29 and cannot execute 'apt update' as root. I am able to ping 8.8.8.8 and archive.ubuntu.com without any packet loss. I confirmed 'ip link set dev eth0 up'.

**Error for 'apt update':**

Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease                                                  
  Could not connect to archive.ubuntu.com:80 (91.189.88.161), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.23), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.149), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.162), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.91.26), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out
....
**Info for 'ip a':**

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
7: eth0@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:ee:d3:74 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.230.159.32/24 brd 10.230.159.255 scope global dynamic eth0
       valid_lft 3348sec preferred_lft 3348sec
    inet6 fe80::216:3eff:feee:d374/64 scope link 
       valid_lft forever preferred_lft forever

**Info for 'lxc network list':**
+--------+----------+---------+-------------+---------+
|  NAME  |   TYPE   | MANAGED | DESCRIPTION | USED BY |
+--------+----------+---------+-------------+---------+
| lxdbr0 | bridge   | YES     |             | 1       |
+--------+----------+---------+-------------+---------+
| virbr0 | bridge   | NO      |             | 0       |
+--------+----------+---------+-------------+---------+
| wlp2s0 | physical | NO      |             | 0       |
+--------+----------+---------+-------------+---------+

**Info for 'lxc profile show default':**

config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/robust-orca

# Steps to reproduce

 1. lxc exec robust-orca -- /bin/bash -c 'apt update -y'

**Comment by stgraber** [comment]
Can you show `ip link show` on the host?

This smells like an MTU issue.

I'm assuming you also tried to download from other servers?
The Ubuntu archive mirrors were rather swamped and slow yesterday.

**Comment by foveann** [comment]
Haven't tried other servers yet. Here is the ip link show on the host:

`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: wlp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether 98:5f:d3:e9:d7:83 brd ff:ff:ff:ff:ff:ff
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:3a:3b:a1 brd ff:ff:ff:ff:ff:ff
4: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:3a:3b:a1 brd ff:ff:ff:ff:ff:ff
5: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 100
    link/none 
6: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether fe:cc:24:ae:25:56 brd ff:ff:ff:ff:ff:ff
8: vethPCJF22@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lxdbr0 state UP mode DEFAULT group default qlen 1000
    link/ether fe:cc:24:ae:25:56 brd ff:ff:ff:ff:ff:ff link-netnsid 0
`

**Comment by stgraber** [comment]
Ok, that looks fine.

Internally, I'm seeing this warning: `Active/known issues: archive servers slowness / bandwidth peak | US servers added to archive.u.c` so I'm going to just assume that this is the archive servers being completely swamped which would explain why ping would work but downloads wouldn't.

You may have some luck updating your /etc/apt/sources.list to use another mirror for the time being.

**Comment by foveann** [comment]
I tried a different mirror and got this error message :

`Err:1 http://mirror.cs.pitt.edu/ubuntu/archive bionic InRelease
  Could not connect to mirror.cs.pitt.edu:80 (136.142.23.206), connection timed out
`

**Comment by foveann** [comment]
Thanks for all your help. I'll try again tomorrow.

**Comment by stgraber** [comment]
Hmm, now that's a bit odd, that mirror answers immediately here.
So there can be two things I can think of that would explain this:
 - Some MTU issue on your network
 - A firewalling dropping the traffic.

Can you show `iptables -L -n -v` on your host as well as the output of `tracepath archive.ubuntu.com`?

**Comment by foveann** [comment]
Sure. Here is the iptables info:
'Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  lxdbr0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:53 /* generated for LXD network lxdbr0 */
    0     0 ACCEPT     udp  --  lxdbr0 *       0.0.0.0/0            0.0.0.0/0            udp dpt:53 /* generated for LXD network lxdbr0 */
    0     0 ACCEPT     udp  --  lxdbr0 *       0.0.0.0/0            0.0.0.0/0            udp dpt:67 /* generated for LXD network lxdbr0 */
    0     0 ACCEPT     udp  --  virbr0 *       0.0.0.0/0            0.0.0.0/0            udp dpt:53
    0     0 ACCEPT     tcp  --  virbr0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:53
    0     0 ACCEPT     udp  --  virbr0 *       0.0.0.0/0            0.0.0.0/0            udp dpt:67
    0     0 ACCEPT     tcp  --  virbr0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:67
17148   11M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
   98  6320 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0           
 1209  328K INPUT_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 1209  328K INPUT_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 1209  328K INPUT_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    5   260 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
   39  1204 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  *      lxdbr0  0.0.0.0/0            0.0.0.0/0            /* generated for LXD network lxdbr0 */
    0     0 ACCEPT     all  --  lxdbr0 *       0.0.0.0/0            0.0.0.0/0            /* generated for LXD network lxdbr0 */
    0     0 ACCEPT     all  --  *      virbr0  0.0.0.0/0            192.168.122.0/24     ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  virbr0 *       192.168.122.0/24     0.0.0.0/0           
    0     0 ACCEPT     all  --  virbr0 virbr0  0.0.0.0/0            0.0.0.0/0           
    0     0 REJECT     all  --  *      virbr0  0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable
    0     0 REJECT     all  --  virbr0 *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0           
    0     0 FORWARD_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 FORWARD_IN_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 FORWARD_IN_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 FORWARD_OUT_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 FORWARD_OUT_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
    0     0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT 14614 packets, 1848K bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  *      lxdbr0  0.0.0.0/0            0.0.0.0/0            tcp spt:53 /* generated for LXD network lxdbr0 */
    0     0 ACCEPT     udp  --  *      lxdbr0  0.0.0.0/0            0.0.0.0/0            udp spt:53 /* generated for LXD network lxdbr0 */
    0     0 ACCEPT     udp  --  *      lxdbr0  0.0.0.0/0            0.0.0.0/0            udp spt:67 /* generated for LXD network lxdbr0 */
14729 1858K piavpn.anchors  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     udp  --  *      virbr0  0.0.0.0/0            0.0.0.0/0            udp dpt:68
14798 1863K OUTPUT_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FORWARD_IN_ZONES (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 FWDI_FedoraWorkstation  all  --  wlp2s0 *       0.0.0.0/0            0.0.0.0/0           [goto] 
    0     0 FWDI_FedoraWorkstation  all  --  +      *       0.0.0.0/0            0.0.0.0/0           [goto] 

Chain FORWARD_IN_ZONES_SOURCE (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD_OUT_ZONES (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 FWDO_FedoraWorkstation  all  --  *      wlp2s0  0.0.0.0/0            0.0.0.0/0           [goto] 
    0     0 FWDO_FedoraWorkstation  all  --  *      +       0.0.0.0/0            0.0.0.0/0           [goto] 

Chain FORWARD_OUT_ZONES_SOURCE (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD_direct (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain FWDI_FedoraWorkstation (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 FWDI_FedoraWorkstation_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 FWDI_FedoraWorkstation_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 FWDI_FedoraWorkstation_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FWDI_FedoraWorkstation_allow (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate NEW,UNTRACKED mark match 0x65

Chain FWDI_FedoraWorkstation_deny (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain FWDI_FedoraWorkstation_log (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain FWDO_FedoraWorkstation (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 FWDO_FedoraWorkstation_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 FWDO_FedoraWorkstation_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 FWDO_FedoraWorkstation_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FWDO_FedoraWorkstation_allow (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain FWDO_FedoraWorkstation_deny (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain FWDO_FedoraWorkstation_log (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT_ZONES (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 1139  322K IN_FedoraWorkstation  all  --  wlp2s0 *       0.0.0.0/0            0.0.0.0/0           [goto] 
   70  5876 IN_FedoraWorkstation  all  --  +      *       0.0.0.0/0            0.0.0.0/0           [goto] 

Chain INPUT_ZONES_SOURCE (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT_direct (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain IN_FedoraWorkstation (2 references)
 pkts bytes target     prot opt in     out     source               destination         
 1209  328K IN_FedoraWorkstation_log  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 1209  328K IN_FedoraWorkstation_deny  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 1209  328K IN_FedoraWorkstation_allow  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain IN_FedoraWorkstation_allow (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22 ctstate NEW,UNTRACKED
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:137 ctstate NEW,UNTRACKED
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:138 ctstate NEW,UNTRACKED
  783  235K ACCEPT     udp  --  *      *       0.0.0.0/0            224.0.0.251          udp dpt:5353 ctstate NEW,UNTRACKED
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 ctstate NEW,UNTRACKED
  382 91228 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpts:1025:65535 ctstate NEW,UNTRACKED
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpts:1025:65535 ctstate NEW,UNTRACKED

Chain IN_FedoraWorkstation_deny (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain IN_FedoraWorkstation_log (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT_direct (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain piavpn.000.allowLoopback (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  *      lo+     0.0.0.0/0            0.0.0.0/0           

Chain piavpn.100.blockAll (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable

Chain piavpn.200.allowVPN (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  *      tun+    0.0.0.0/0            0.0.0.0/0           

Chain piavpn.290.allowDHCP (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            255.255.255.255      udp spt:68 dpt:67

Chain piavpn.300.allowLAN (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.0.0.0/8          
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            169.254.0.0/16      
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            172.16.0.0/12       
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            192.168.0.0/16      
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            224.0.0.0/4         
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            255.255.255.255     

Chain piavpn.310.blockDNS (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REJECT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:53 reject-with icmp-port-unreachable
    0     0 REJECT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:53 reject-with icmp-port-unreachable

Chain piavpn.320.allowDNS (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     udp  --  *      tun+    0.0.0.0/0            209.222.18.222       udp dpt:53
    0     0 ACCEPT     tcp  --  *      tun+    0.0.0.0/0            209.222.18.222       tcp dpt:53
    0     0 ACCEPT     udp  --  *      tun+    0.0.0.0/0            209.222.18.218       udp dpt:53
    0     0 ACCEPT     tcp  --  *      tun+    0.0.0.0/0            209.222.18.218       tcp dpt:53

Chain piavpn.400.allowPIA (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner GID match 1001

Chain piavpn.a.000.allowLoopback (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain piavpn.a.100.blockAll (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain piavpn.a.200.allowVPN (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain piavpn.a.290.allowDHCP (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain piavpn.a.300.allowLAN (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain piavpn.a.310.blockDNS (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain piavpn.a.320.allowDNS (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain piavpn.a.400.allowPIA (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain piavpn.anchors (1 references)
 pkts bytes target     prot opt in     out     source               destination         
14729 1858K piavpn.a.000.allowLoopback  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
14729 1858K piavpn.a.400.allowPIA  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
14729 1858K piavpn.a.320.allowDNS  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
14729 1858K piavpn.a.310.blockDNS  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
14729 1858K piavpn.a.300.allowLAN  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
14729 1858K piavpn.a.290.allowDHCP  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
14729 1858K piavpn.a.200.allowVPN  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
14729 1858K piavpn.a.100.blockAll  all  --  *      *       0.0.0.0/0            0.0.0.0/0  '

And the tracepath output:

'1?: [LOCALHOST]                      pmtu 1500
 1:  no reply
 2:  no reply
 3:  no reply
 4:  no reply
 5:  no reply
 6:  no reply'

**Comment by stgraber** [comment]
The iptables output looks odd, it shows no packet having gone through any of the rules in the FORWARD table which doesn't make much sense given that you're sending traffic out of the container...

**Comment by foveann** [comment]
I am very grateful for your time on this issue. Not sure how to troubleshoot further. All I know is that the first time I set up a container I was able to run 'apt update' and even 'apt install nginx'  successfully but after rebooting and restarting my host, this issue started. I tried uninstalling lxd then reinstalling lxd but nothing has changed. During this whole time, I have not made any changes to the iptables rules nor installed anything so I can't think of what it could be.

**Comment by stgraber** [comment]
Can you try doing `lxc network set lxdbr0 bridge.mtu 1280` and then restart your container and try again?

If there's some kind of MTU issue, that should unblock it.

**Comment by foveann** [comment]
I ran that command and it didn't complain but when I checked the tracepath again, the MTU size reverted back to the default 1500. Output same as first tracepath.

**Comment by stgraber** [comment]
What's odd is that ICMP would go through but the rest is blocked...

You could temporarily try (as root on the host):
 - iptables -I INPUT -j ACCEPT
 - iptables -I OUTPUT -j ACCEPT
 - iptables -I FORWARD -j ACCEPT

That should mostly run out firewall problems. To undo that change, run:
 - iptables -D INPUT -j ACCEPT
 - iptables -D OUTPUT -j ACCEPT
 - iptables -D FORWARD -j ACCEPT

**Comment by foveann** [comment]
I tried it but nothing has changed unfortunately.

**Comment by stgraber** [comment]
Ok, I suspect you're at the point now where you'll need to use `tcpdump` to follow the traffic coming out of the container, hitting the bridge then hitting the outside interface to see where things go wrong.

You can find the interface name of the container in `lxc info`, dump that one first, then dump lxdbr0 then finally dump your upstream link with wlan0 and make sure you see all packets in all of them, if they disappear somewhere, that should give you a clue as to what's going on.

**Comment by foveann** [comment]
First time doing the tcpdump on my side. I installed it and can't figure out which interface to run the command on...this is what I have when I run 'nmcli device status' on my host:

' DEVICE      TYPE      STATE      CONNECTION  
wlp2s0      wifi      connected  NETWORKNAME
lxdbr0      bridge    connected  lxdbr0      
virbr0      bridge    connected  virbr0      
tun0        tun       connected  tun0        
lxdbr0-mtu  dummy     unmanaged  --          
vethIVB9H4  ethernet  unmanaged  --          
lo          loopback  unmanaged  --          
virbr0-nic  tun       unmanaged  --  '

I am guessing the lxdbr0 and the wlp2s0 but what am I looking for?

**Comment by stgraber** [comment]
`tcpdump -ni vethIVB9H4 port 80` should show you the http traffic, then repeat on lxdbr0 and then on wlp2s0, that's the path your http traffic should be taking out and back.

**Comment by foveann** [comment]
Thanks a lot! I ran all three and it is the wlp2s0 that yields nothing.

**Comment by stgraber** [comment]
Ok, so suspects there could be that ip_forward is disabled somehow, or firewalling (though that didn't seem to be the case earlier) or maybe there's something odd going on with the nat tables or ebtables.

 - iptables -t nat -L -n -v
 - ebtables -L -v
 - cat /proc/sys/net/ipv4/ip_forward
 - cat /proc/sys/net/ipv4/conf/wlp2s0/forwarding
 - cat /proc/sys/net/ipv4/conf/lxdbr0/forwarding
 - ifconfig -a
 - dmesg

May all be useful to track down what configuration is causing this problem.

**Comment by foveann** [comment]
There seems to be some discussion about port forwarding between host and container but in my case I don't even have 'apt update' so I can't possibly have a web server running. Someone in this [thread](https://github.com/lxc/lxd/issues/591) suggests connecting a web server on port 9090 with this command:
'lxc config device add c1 proxy0 listen=tcp:127.0.0.1:80 connect=tcp:127.0.0.1:9090'
How would I modify this if I don't have a web server running within the container to begin with? Or maybe I misunderstand the problem.

**Comment by stgraber** [comment]
The proxy device is completely unrelated to your issue.

**Comment by U-236** [comment]
try using a cloud image, i have that problem with OpenSUSE Leap 15.4 host and fixed using cloud image like ubuntu/jammy/cloud, LXD installed using snap
