### ISSUE TITLE
How to run app on startup

### ISSUE THREAD

**Issue by haha150** [lxc/lxd#5638]
Hi,

I am just wondering how i can start i.e. iperf server (iperf -s -i 1 &) in a fresh container on startup or on creation? 

Currently i ssh in to the container to start the server but i dont want to keep doing that anymore. I should mention that i need to start it via ssh or startup so that i can live migrate the container.

**Comment by stgraber** [comment]
Just like you would on any physical server or VM, write an init script for it and have the init system start it.

Support questions are best handled here: https://discuss.linuxcontainers.org
