### ISSUE TITLE
New container fails to start after copying from an old one

### ISSUE THREAD

**Issue by kaneg** [lxc/lxd#564]
The old container can be started and works well. After copying it to a new container by using command below:
lxc copy <OLD> <NEW>
It seems the command execution is successful. After the command execution, the new container has been created, but with stopped state, it should be started automatically.

The start the new container manually:
lxc start <NEW>
it reports error: starting the container failed

Finally,  searching by Google, found a difference between the old one and the new one is that their folder flag is different, the new one is lack of '+':
drwxr-x---+ 1 root root   30 Apr 27 00:51 old   
drwx------  1 root root   12 Apr 29 22:19  new  

Then by applying a workaround, the new one can be started:
setfacl -m u:100000:r-x <NEW>

Could you please take a look if it is a general issue or environment specific?
BTW, my env info:
LXC version: 0.7
Ubuntu 14.04.2 LTS \n \l
Linux ubuntu 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tych0** [comment]
Hi,

Thanks for the report.

On Wed, Apr 29, 2015 at 07:30:26AM -0700, kaneg wrote:
> The old container can be started and works well. After copying it to a new container by using command below:
> lxc copy <OLD> <NEW>
> It seems the command execution is successful. After the command execution, the new container has been created, but with stopped state, it should be started automatically.

Why should it be started automatically?

> The start the new container manually:
> lxc start <NEW>
> it reports error: starting the container failed
> 
> Finally,  searching by Google, found a difference between the old one and the new one is that their folder flag is different, the new one is lack of '+':
> drwxr-x---+ 1 root root   30 Apr 27 00:51 old   
> drwx------  1 root root   12 Apr 29 22:19  new  
> 
> Then by applying a workaround, the new one can be started:
> setfacl -m u:100000:r-x <NEW>
> 
> Could you please take a look if it is a general issue or environment specific?

Thanks for the report, this does look like a bug. I looked at the code
path and it /should/ do the setfacl, but apparently it isn't.

Can you paste exactly the command you used, as well as the output of
`lxc remote list`?

**Comment by kaneg** [comment]
Copy command: lxc copy first second
Start command:  lxc start second
output of lxc remote list:
local <unix:///var/lib/lxd/unix.socket>

For automatic starting, I thought it is same with launch. Anyway, it is not important whether to start automatically.

**Comment by stgraber** [comment]
Can you try with 0.8.1? We fixed a bug that sounds extremely similar to that in 0.8.

**Comment by kaneg** [comment]
It works in 0.8.1!
Thanks for your quick response.

**Comment by stgraber** [comment]
Great, good to hear!
