### ISSUE TITLE
lxd 3.12 : cannot open freezer cgroup (/sys/fs/cgroup/freezer): No such file or directory

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#5656]
# Required information

 * Distribution:Ubuntu 18.04.2 LTS

 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-48-generic
   * LXC version: 3.12
   * LXD version: 3.12
   * Storage backend in use: btrfs

# Issue description

Since minor update of Ubuntu 18.04.2 LTS and reboot snap lxd do not start:

journalctl logs:
cannot open freezer cgroup (/sys/fs/cgroup/freezer): No such file or directory
snap.lxd.activate.service: Main process exited, code=exited, status=1/FAILURE

even lxc cli can't be launched

# Steps to reproduce

 1. on Ubuntu 18.04.X LTS:
  - apt update
  - apt upgrade
  - reboot

 2. lxc list:
cannot open freezer cgroup (/sys/fs/cgroup/freezer): No such file or directory

 3. Step three
 tried to downgrade snapd 

 initily was: 2.38+18.04
 installed 2.32.5+18.04 : same problem

before update, kernel was 4.15.0-40-generic

now it is 4.15.0-48-generic

- dmesg logs:
'''dmesg | grep -i denied
[    9.560827] audit: type=1400 audit(1554998387.147:3): avc:  denied  { module_load } for  pid=1 comm="systemd" path="/lib/modules/4.15.0-48-generic/kernel/fs/autofs4/autofs4.ko" dev="sda1" ino=11471 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=system permissive=1
[    9.904464] audit: type=1400 audit(1554998387.491:4): avc:  denied  { associate } for  pid=1 comm="systemd" name="init.scope" scontext=system_u:object_r:init_var_run_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   11.350701] audit: type=1400 audit(1554998388.939:5): avc:  denied  { associate } for  pid=1 comm="systemd" name="user.slice" scontext=system_u:object_r:systemd_passwd_var_run_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   11.379877] audit: type=1400 audit(1554998388.963:6): avc:  denied  { associate } for  pid=1 comm="systemd" name="system-openvpn.slice" scontext=system_u:object_r:lvm_var_run_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   11.387624] audit: type=1400 audit(1554998388.971:7): avc:  denied  { associate } for  pid=1 comm="systemd" name="ufw.service" scontext=system_u:object_r:devlog_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   12.167725] audit: type=1400 audit(1554998389.751:8): avc:  denied  { associate } for  pid=1 comm="systemd" name="dev-hugepages.mount" scontext=system_u:object_r:hugetlbfs_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   12.173664] audit: type=1400 audit(1554998389.759:9): avc:  denied  { associate } for  pid=1 comm="systemd" name="sys-kernel-debug.mount" scontext=system_u:object_r:debugfs_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   12.182961] audit: type=1400 audit(1554998389.767:10): avc:  denied  { audit_read } for  pid=1 comm="systemd" capability=37  scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=capability2 permissive=1
[   12.207916] audit: type=1400 audit(1554998389.791:11): avc:  denied  { associate } for  pid=1 comm="systemd" name="initctl" scontext=system_u:object_r:init_var_run_t:s0 tcontext=system_u:object_r:device_t:s0 tclass=filesystem permissive=1
[   19.465161] audit: type=1107 audit(1554998397.051:16): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:kernel_t:s0 msg='avc:  denied  { start } for auid=n/a uid=0 gid=0 path="/lib/systemd/system/ifup@.service" cmdline="" scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=service permissive=1
[   19.467012] audit: type=1107 audit(1554998397.051:17): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:kernel_t:s0 msg='avc:  denied  { status } for auid=n/a uid=0 gid=0 path="/lib/systemd/system/ifup@.service" cmdline="" scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=service permissive=1
[   20.861356] audit: type=1400 audit(1554998398.451:18): avc:  denied  { associate } for  pid=1 comm="systemd" name="var-lib-docker.mount" scontext=system_u:object_r:var_lib_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   20.894316] audit: type=1400 audit(1554998398.479:19): avc:  denied  { associate } for  pid=1 comm="systemd" name="var-snap-lxd-common-lxd.mount" scontext=system_u:object_r:var_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   20.910903] audit: type=1400 audit(1554998398.495:20): avc:  denied  { associate } for  pid=1 comm="systemd" name="mnt-ROOT.mount" scontext=system_u:object_r:mnt_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   21.921617] audit: type=1400 audit(1554998399.507:21): avc:  denied  { create } for  pid=1434 comm="(resolved)" name="shm" scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:ptmx_t:s0 tclass=dir permissive=1
[   21.921623] audit: type=1400 audit(1554998399.507:22): avc:  denied  { mounton } for  pid=1434 comm="(resolved)" path="/tmp/namespace-dev-qbUPRp/dev/shm" dev="tmpfs" ino=5 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:ptmx_t:s0 tclass=dir permissive=1
[   21.921681] audit: type=1400 audit(1554998399.507:23): avc:  denied  { create } for  pid=1434 comm="(resolved)" name="log" scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:ptmx_t:s0 tclass=lnk_file permissive=1
[   21.922138] audit: type=1400 audit(1554998399.507:24): avc:  denied  { create } for  pid=1434 comm="(resolved)" name="core" scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:devtty_t:s0 tclass=lnk_file permissive=1
[   22.205451] audit: type=1400 audit(1554998399.791:25): avc:  denied  { associate } for  pid=1 comm="systemd" name="selinux.service" scontext=system_u:object_r:uuidd_var_run_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   24.636006] audit: type=1400 audit(1554998402.219:26): avc:  denied  { module_load } for  pid=1633 comm="modprobe" path="/lib/modules/4.15.0-48-generic/kernel/drivers/net/dummy.ko" dev="sda1" ino=7553 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=system permissive=1
[   24.918177] audit: type=1400 audit(1554998402.503:27): avc:  denied  { associate } for  pid=1 comm="systemd" name="ifup@dummy0.10.service" scontext=system_u:object_r:uuidd_var_run_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   30.216288] audit: type=1107 audit(1554998407.803:28): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:kernel_t:s0 msg='avc:  denied  { start } for auid=n/a uid=0 gid=0 path="/run/systemd/transient/user-0.slice" cmdline="/lib/systemd/systemd-logind" scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:systemd_unit_t:s0 tclass=service permissive=1
[   30.216776] audit: type=1400 audit(1554998407.803:29): avc:  denied  { associate } for  pid=1 comm="systemd" name="user-0.slice" scontext=system_u:object_r:systemd_unit_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   30.235661] audit: type=1107 audit(1554998407.819:30): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:kernel_t:s0 msg='avc:  denied  { status } for auid=n/a uid=0 gid=0 path="/run/systemd/transient/session-1.scope" cmdline="/lib/systemd/systemd-logind" scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:systemd_unit_t:s0 tclass=service permissive=1
[   31.391084] audit: type=1400 audit(1554998408.975:31): avc:  denied  { associate } for  pid=1 comm="systemd" name="snapd.seeded.service" scontext=system_u:object_r:systemd_unit_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[   38.347086] audit: type=1400 audit(1554998415.931:32): avc:  denied  { module_load } for  pid=5888 comm="modprobe" path="/lib/modules/4.15.0-48-generic/kernel/net/netfilter/xt_mark.ko" dev="sda1" ino=407287 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=system permissive=1
[   38.501542] audit: type=1400 audit(1554998416.087:33): avc:  denied  { associate } for  pid=1 comm="systemd" name="docker.service" scontext=system_u:object_r:systemd_unit_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
[  289.826946] audit: type=1400 audit(1554998667.826:34): avc:  denied  { transition } for  pid=7973 comm="dpkg" path="/var/lib/dpkg/info/linux-modules-4.15.0-42-generic.postrm" dev="sda1" ino=921724 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:system_r:dpkg_script_t:s0 tclass=process permissive=1
[  289.826991] audit: type=1400 audit(1554998667.826:35): avc:  denied  { entrypoint } for  pid=7973 comm="dpkg" path="/var/lib/dpkg/info/linux-modules-4.15.0-42-generic.postrm" dev="sda1" ino=921724 scontext=system_u:system_r:dpkg_script_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
[  308.318375] audit: type=1400 audit(1554998686.316:36): avc:  denied  { entrypoint } for  pid=8190 comm="dpkg" path="/var/lib/dpkg/info/snapd.prerm" dev="sda1" ino=917882 scontext=system_u:system_r:dpkg_script_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1
[  310.764026] audit: type=1400 audit(1554998688.764:37): avc:  denied  { associate } for  pid=1 comm="systemd" name="systemd-journal-flush.service" scontext=system_u:object_r:init_var_run_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=filesystem permissive=1
'''

**Comment by stgraber** [comment]
This error doesn't come from LXD but from snapd instead.

Can you try to run `snap install hello-world` and then run `hello-world` see if this hits the same issue?

**Comment by stgraber** [comment]
Also, how comes your system is running SELinux? is that intentional?

**Comment by gaetanquentin** [comment]
hello-world
cannot open freezer cgroup (/sys/fs/cgroup/freezer): No such file or directory

selinux: i think it was for openshift, unused now: i have uninstalled it. and now all is working .
strange....

**Comment by gaetanquentin** [comment]
i have this warning now: 
2019/04/12 09:16:11.265251 cmd_run.go:876: WARNING: cannot create user data directory: failed to verify SELinux context of /root/snap: exec: "matchpathcon": executable file not found in $PATH
is this important?

**Comment by gaetanquentin** [comment]
i have installed back selinux-tools.
there is still a warning:
WARNING: cannot create user data directory: failed to verify SELinux context of /root/snap: exit status 1

 looks like it is non-mainline kernel problem .

**Comment by stgraber** [comment]
You may have a boot option to force SELinux in /etc/default/grub, if you do, remove that, run update-grub and reboot
