### ISSUE TITLE
Output GPU name with container devices

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#5663]
It would be great if the GPU name could come with container devices to save more api requests

**Comment by brauner** [comment]
Isn't that already covered by the new resource-api work, @stgraber?

**Comment by turtle0x1** [comment]
(if your talking about a future release ignore me) Just to be clear I mean when you call `/containers/container_name/`, I could call the resources api and work it out, it would be nice to save the api call though

![c_response](https://user-images.githubusercontent.com/12494629/56083275-94caf380-5e1a-11e9-9c73-760fa20bc089.png)

**Comment by stgraber** [comment]
We won't be doing that.

The resources API is an expensive host-specific API endpoint, it causes a bunch of kernel calls, parsing local files and in the case of NVIDIA GPUs, communication with the NVIDIA driver.

The container config API is the most common API call in LXD and has been optimized specifically to avoid any local access, subprocess, ... so you can run it against 10k containers without DoSing your system.

For those who want to know exactly what physical device is tied to their container, doing a single call to the resources end point per host and then querying container details and lining things up based on GPU id or PCI address should be easy enough.
