### ISSUE TITLE
lxc file pull from long file path causes new lines printed when bitrate is updated

### ISSUE THREAD

**Issue by rigred** [lxc/lxd#5668]
# Minor Bug

 * Distribution: Arch Linux
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.0.7
   * LXC version: 3.12
   * LXD version: 3.12
   * Storage backend in use: ZFS

# Issue description

Pulling a file from long file path on a remote instance when the filepath is wider than the terminal causes new lines to be printed in the terminal when the bitrate is updated.

# Steps to reproduce

 1. Create file on a remote with very long name (wider than terminal)
 2. Pull file from the remote
 3. Observe the progress line move ever further down the terminal.

Resizing the terminal to be wider than the path stops the scrolling. I'm not quite sure why this is though.

Example Screenshot attached for illustration.
![image](https://user-images.githubusercontent.com/5716332/56200978-2d8e8880-6040-11e9-82c7-36e795f8e307.png)

**Comment by rigred** [comment]
Just noticed this should have been posted to the LXC repo.
My bad.

**Comment by stgraber** [comment]
Nope, here is right
