### ISSUE TITLE
LXD becomes very, very slow with ~ 1,000 snapshots

### ISSUE THREAD

**Issue by ThomasLeister** [lxc/lxd#5678]
# Required information

 * Distribution: Debian 
 * Distribution version: 9 Stretch
 * The output of "lxc info" or if that fails:
 ```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate
  certificate_fingerprint: 
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "false"
  kernel_version: 4.9.0-8-amd64
  project: default
  server: lxd
  server_clustered: false
  server_name: lxd1
  server_pid: 4172
  server_version: "3.12"
  storage: zfs
  storage_version: 0.6.5.9-5
```

# Issue description

I have 4 LXC instances running and configured them to create auto-snapshots. Now after 2 days I have a little more than 1,000 snapshots that were created during that time. LXD is now very slow and can hardly be used. The containers get up after a while, but lxc commands such as "lxc start mycontainer" or "lxc config edit" or "lxc list" take forever (sometimes more than 10 minutes, sometimes even more).

# Steps to reproduce

 1. Create lots of snapshots
 2. Try to use lxc-commands
 3. You will experience very slow reaction

Two separate LXD servers of mine are affected by this problem, so I guess it can be reproduced.

**Comment by ThomasLeister** [comment]
Note: Also the ```zfs list``` takes a long time. About 2 minutes on my other host.

**Comment by stgraber** [comment]
The fact that `zfs list` itself is slow would indicate a performance issue on the ZFS side rather than LXD with LXD suffering due to itself accessing zfs when performing many operations.

Can you try:
 - time lxc query /1.0
 - time lxd sql global "SELECT COUNT(*) FROM containers;"

That would give us a good idea of whether LXD itself is slow due to that data or if it's effectively getting stuck on storage.

**Comment by ThomasLeister** [comment]
Hi @stgraber ! 

### On my fist host

After I saw the massive amount of snapshots, and bad performance of both LXD and ZFS tools, I tried to solve the issue by deleting all snapshots:

```
zfs destroy -r default/snapshots/[container]
```

After that ZFS performance (```zfs``` tool) was okay again. Just LXD was still not fine: ```lxc list``` takes forever. ```zfs list --fast``` is fast ;-) Also the commands provided by you run in reasonable time:

```
root@lxd1# time lxc query /1.0
real    0m0,133s
user    0m0,060s
sys     0m0,064s

root@lxd1# time lxc query /1.0
real    0m0,289s
user    0m0,068s
sys     0m0,116s
```

```
root@lxd1:~# time lxd sql global "SELECT COUNT(*) FROM containers;"
+----------+
| COUNT(*) |
+----------+
| 3893     |
+----------+

real    0m0,267s
user    0m0,092s
sys     0m0,100s

root@lxd1:~# time lxd sql global "SELECT COUNT(*) FROM containers;"
+----------+
| COUNT(*) |
+----------+
| 3893     |
+----------+

real    0m0,221s
user    0m0,060s
sys     0m0,080s
```

### On my second host 

I did not make any changes/manipulations to this host. Timing differs quite much from run to run. Also the first run of ```lxc query```took more than 2 minutes and timing is worse. (Maybe there are 8,000 DB records ;-) )

```
root@lxd2# time lxc query /1.0
real    2m15,187s
user    0m0,228s
sys     0m0,432s

root@lxd2# time lxc query /1.0
real    0m15,367s
user    0m0,192s
sys     0m0,500s
```


```
root@lxd2:~# time lxd sql global "SELECT COUNT(*) FROM containers;"
+----------+
| COUNT(*) |
+----------+
| 8026     |
+----------+

real    0m46,770s
user    0m0,172s
sys     0m0,420s

root@lxd2:~# time lxd sql global "SELECT COUNT(*) FROM containers;"
+----------+
| COUNT(*) |
+----------+
| 8026     |
+----------+

real    0m15,534s
user    0m0,176s
sys     0m0,404s
```

I'm not really sure what to read from the numbers. ```lxc list```, ```lxc config``` and some more commands are still extremely slow, while the commands you suggested work faster. 

On my first host:
```
root@lxd1# lxc list
real    7m53,313s
user    0m1,236s
sys     0m0,320s
```

On my second host: More than 20 minutes - I couldn't wait so long ;-)

**Comment by ThomasLeister** [comment]
In the meantime I've gotten both instances back to working via:

```
lxd sql global "delete from containers where type = 1 and name like 'mycontainer1%';"
zfs destroy -r default/snapshots/mycontainer1
```

*(replace mycontainer1 by your container names - one after another)*

This deletes all snapshots, so lxc commands will run again :-) Nevertheless, I think there should be some investigation on the performance impact. Maybe some performance gain can be achieved by changing the source code.

**Comment by stgraber** [comment]
That's odd because I've definitely run environments with a very large amount of snapshots before, but it could be that we regressed in some way there, the mention of `default/snapshots` is one red flag as that should normally be empty unless a snapshot is actively being produced or exported.

With the long Easter weekend, I don't expect to have much time to look into this until Tuesday, but it certainly is on our list of issues to attempt to reproduce and then debug.

**Comment by stgraber** [comment]
Reproduced the problem with a few thousand snapshots.

The main issue is how slow the Snapshots() call in containerLXC is due to the very very many database queries being performed. We need to move that to a bulk query similar to what we do to get all containers at once.

Also, we need a separate DB query for just getting all snapshot names for a container so the simple /1.0/containers/NAME/snapshots API call can be made significantly faster.
