### ISSUE TITLE
lxd client: UNIQUE constraint failed: certificates.fingerprint

### ISSUE THREAD

**Issue by gjedeer** [lxc/lxd#5707]
Ubuntu 18.04, lxd-client 3.0.3 (no lxd daemon)

Trying to add a few remote LXD servers. Some worked, one failed:

```
$ lxc remote add lx24 1.1.1.1
Certificate fingerprint: 26.........df
ok (y/n)? y
Admin password for lx24: 
Error: UNIQUE constraint failed: certificates.fingerprint

$ lxc remote add lx24 1.1.1.1
Admin password for lx24: 
Error: Certificate already in trust store

$ lxc list lx24:
Error: The remote "lx24" doesn't exist
```

I saw in https://github.com/lxc/lxd/issues/4976 that 'lxd sql global' could work, but I don't have the lxd command installed. Any way to recover from this?

**Comment by gjedeer** [comment]
What didn't work too:

```
rm ~/.config/lxc/servercerts/lx24.crt
lxc remote add lx24 1.1.1.1
Certificate fingerprint: .......
ok (y/n)? y
Admin password for lx24: 
Error: Certificate already in trust store
```

What worked, but I had to re-add all hosts:
```
rm -rf ~/.config/lxc
```

**Comment by stgraber** [comment]
Can you connect to the server in question and show `lxd sql global "SELECT * FROM certificates;"`?

It'd also have been nice to have the `client.crt` from your client but given you've deleted your config directory, this is now gone. Hopefully we can find something wrong in the DB, if not, we'll have to close this until someone else hits the issue and hasn't deleted their config.

**Comment by gjedeer** [comment]
There are 5 certs on that server, 2 of them for my client's IP address. If there is a way to share the output from that command privately to you, I'd be happy to do it.

**Comment by gjedeer** [comment]
I also happen to have the old client certificate (actually moved it to /tmp/ instead of deleting).

**Comment by gjedeer** [comment]
The certificate in old `client.crt` is the same as the one in 4th row of the table. New client cert is now in row 5.

**Comment by gjedeer** [comment]
Regarding the  "UNIQUE constraint failed":

```
root@lx24:~# lxd sql global "SELECT COUNT(1) FROM certificates;"
+----------+
| COUNT(1) |
+----------+
| 5        |
+----------+
root@lx24:~# lxd sql global "SELECT COUNT(DISTINCT fingerprint) FROM certificates;"
+-----------------------------+
| COUNT(DISTINCT fingerprint) |
+-----------------------------+
| 5                           |
+-----------------------------+
```

I think it was just an error during insert, the database looks okay to me. I don't think it's desired behavior that the client fails if server already has the certificate - is it really a problem? All the client cares about is that its certificate is in server's trust store: if it's already there, we're good, the server is already in desired state.

**Comment by stgraber** [comment]
Right but what's odd is that the certificate already being in the trust store should have allowed your client to connect without needing to send it to the server, so there's some odd disconnect there.

The server telling the client that the certificate is already in the trust store is fine, though it shouldn't tell you this way. And once it is in the trust store, the client should just have gone straight to making requests rather than attempting to add its certificate.

**Comment by gjedeer** [comment]
Hmm, could it be that the first time it failed somewhere between `saveCert()` and `d.clientCerts[shared.CertFingerprint(cert)] = *cert` ?

https://github.com/lxc/lxd/blob/7a9a4e24f0eba557c913e735527999aed841fee7/lxd/certificates.go#L187

There are 3 return statements between saving the cert to the database and saving it in the internal cache. I guess even a network error when notifying other cluster nodes could cause inconsistency between database and the copy in memory.

**Comment by gjedeer** [comment]
Perhaps moving the code around a little bit would fix this problem:

https://github.com/lxc/lxd/compare/master...gjedeer:master

**Comment by stgraber** [comment]
well, that's papering over the issue though, you should have hit the "Already in trust store" case, but somehow the trust list wasn't up to date in your case which is a bit odd.

Are you using clustering?

**Comment by stgraber** [comment]
I can see how in a cluster case we could hit this issue and in that case, effectively if a node was temporarily offline while the cert was added, then came back into the cluster without fully restarting.

I suspect we could indeed avoid this kind of issue by effectively checking if the cert is in the trust store, then if it's not, check if it's in the database already, if it is, re-sync the trust store and return pretending we just added it. This would avoid client confusion and would resolve the problem.

For the case where db/memory are up to date, I do want to keep returning an error if a cert is already trusted.

**Comment by gjedeer** [comment]
No I'm not using clustering. Double-checked my seed file:

```
cluster: null
```

The server in question was under some load when the first `remote add` failed, I'm not sure how this could have affected the problem. Maybe `certSave()` failed with some kind of timeout for the first time, but stored the row eventually, and the next time the `UNIQUE constraint failed` error happened?

> I suspect we could indeed avoid this kind of issue by effectively checking if the cert is in the trust store, then if it's not, check if it's in the database already, if it is, re-sync the trust store and return pretending we just added it. This would avoid client confusion and would resolve the problem.

Hmm, wouldn't this allow some kind of DOS attack? Attacker could spam the server with bogus certificates forcing it to `SELECT * FROM certificates` every time.

Unless somehow this would only happen after verifying the trust password.

**Comment by stgraber** [comment]
We'd want to validate the trust password first I think, yeah

**Comment by gjedeer** [comment]
That was fast. Thank you!
