### ISSUE TITLE
lxc copy --refresh removes uid/gid mappings in backuped container config 

### ISSUE THREAD

**Issue by idef1x** [lxc/lxd#5708]
# Required information

 * Distribution: ubuntu 
 * Distribution version: 18.10 on backup LXD 
[lxd-uid-gids-removal-on-refresh.txt](https://github.com/lxc/lxd/files/3126511/lxd-uid-gids-removal-on-refresh.txt)
host and  18.04 on source lxd host
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version: snap lxd   3.12     10601  stable  
   * Storage backend in use: ZFS

# Issue description

Copying a container from one host to another copies the uid/gid mappings correctly in the container configuration. However refreshing it afterwards, removes these mappings from the configuration and so processes won't start inside the container due to wrong uid/gids

# Steps to reproduce

 1. Step one
create snapshot of container on source host (if running)
 2. Step two
copy snapshot to backup lxd host
verify id mappings on config (lxc config show <container>)

 3. Step three
copy original container with --refresh (lxc copy remote:container local: --refresh)
verify uid/gid mapping in container config on backup host and see they are gone.

See attachment of detailed procedure

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by idef1x** [comment]
Hmmm interesting side effect: now it also copies the running state. So when I refresh a running container it will start it on the backup server, which is not really wanted. In my case the networks are bridged on the backup server with the real host, so ip conflicts occur (and duplicate macs)

**Comment by stgraber** [comment]
Indeed, I sent a fix last night which should correct this problem.

**Comment by idef1x** [comment]
I see the thread is still monitored...forgive me that I created an issue in the mean time. You're fast! :)
