### ISSUE TITLE
Creating a network that has a conflicting address range makes lxd hang

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#5722]
If you make a call through the api to create a network with the ipv4.address = 192.168.0.1/24 and then try to create another one with the same address range it will cause lxd to hang (it wont respond) it seems to recover but you will get the following in syslog;

```
May  5 10:19:42 XXX dnsmasq[24471]: failed to create listening socket for 192.168.0.1: Address already in use
May  5 10:19:42 XXX dnsmasq[24471]: FAILED to start up
```

Version 3.12 on Ubuntu 19.04

**Comment by stgraber** [comment]
Does it hang or just take 10s to do the create for you?

Because if it takes 10s and then fails with an error, that's normal.

**Comment by turtle0x1** [comment]
It didnt responded i left it for 5~ minutes this was done over the api and not the cli

**Comment by stgraber** [comment]
How were you connecting using the API? If over https, what address?

I'm wondering if you were hitting the web server on the address that was setup as a conflict which would explain the issue.

**Comment by turtle0x1** [comment]
connecting using localhost:8443 using php (curl) the ip range i  was creating is not my real ip range

**Comment by stgraber** [comment]
I'm unable to reproduce what you're seeing, here, I'm getting the expected:
```
stgraber@castiana:~$ lxc network create test ipv6.address=none ipv4.address=192.168.1.1/24
Network test created

stgraber@castiana:~$ lxc network create test1 ipv6.address=none ipv4.address=192.168.1.1/24
Error: Failed to run: dnsmasq --strict-order --bind-interfaces --pid-file=/var/lib/lxd/networks/test1/dnsmasq.pid --except-interface=lo --interface=test1 --quiet-dhcp --quiet-dhcp6 --quiet-ra --listen-address=192.168.1.1 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/lib/lxd/networks/test1/dnsmasq.leases --dhcp-hostsfile=/var/lib/lxd/networks/test1/dnsmasq.hosts --dhcp-range 192.168.1.2,192.168.1.254,1h -s lxd -S /lxd/ --conf-file=/var/lib/lxd/networks/test1/dnsmasq.raw -u lxd: dnsmasq: failed to create listening socket for 192.168.1.1: Address already in use
```

The first succeeds within 1s, the second fails after exactly 10s which is our normal re-try timeout.

**Comment by turtle0x1** [comment]
Your right when I do this with curl the problem doesn't persist is must be something to do with either my application or the way the network handles the failure (that curl isn't sensitive too) ill close this off, if I find a way to reproduce ill re-open it
