### ISSUE TITLE
About translating(Weblate)

### ISSUE THREAD

**Issue by ccppoo** [lxc/lxd#5723]
Hi, to talk straight I'm having problem of translating of your scripts #1~8

![image](https://user-images.githubusercontent.com/46418312/57198682-8652a080-6fb0-11e9-9e02-f10219649d9c.png)

This is translation of German, which they translated every words, and there's some other language like Japanese(76.5% done) which left it blank ↓

![image](https://user-images.githubusercontent.com/46418312/57198703-cdd92c80-6fb0-11e9-87f2-785f33cad055.png)

I checked the source and found out it was part of the code, and googled there was no annotation starting with ###

So I'm asking this if this (#1~8) just needs translation like any other ones or leave it in go lang.

**Comment by stgraber** [comment]
This is a translatable string so it should be translated, I'm guessing the japanese translators just didn't get to that one yet or the string changed causing it to get reset.

Obviously the config options themselves shouldn't get translated, but the commands around it can, the German translation above seems good as far as what got translated.
