### ISSUE TITLE
File or directory missing (macro.h)

### ISSUE THREAD

**Issue by kperanovic** [lxc/lxd#5725]
# Required information

 * Distribution: Arch Linux
 * Distribution version:  5.0.12-arch2-1-ARCH 

# Issue description

After pulling the library, and ensuring the deps with ```dep ensure```, running the program will fail.
I manually checked for the missing file, and it was missing.
I tried deleting the library and pulling it again. Issue persists.

```
In file included from ./../shared/netns_getifaddrs.c:22,
                 from vendor/github.com/lxc/lxd/shared/network_linux.go:20:
./../shared/network.c:22:10: fatal error: ../lxd/include/macro.h: No such file or directory
 #include "../lxd/include/macro.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

# Steps to reproduce

 1. go get -u github.com/lxc/lxd/lxd
 2. dep ensure -v
 3. Run any go code that uses library functionalities

**Comment by nyetwurk** [comment]
```
$ go get -u github.com/lxc/lxd/lxd
# github.com/CanonicalLtd/go-dqlite/internal/bindings
../../CanonicalLtd/go-dqlite/internal/bindings/cluster.go:7:10: fatal error: dqlite.h: No such file or directory
 #include <dqlite.h>
          ^~~~~~~~~~
compilation terminated.
```

**Comment by nyetwurk** [comment]
Reverting to lxd-3.10 works.
lxd-3.11 broken
lxd-3.12 broken

**Comment by stgraber** [comment]
@nyetwurk that's unrelated to this issue. In your case you're trying to build the daemon which does require a working dqlite as a build dependency. You can likely fix this by running `make deps` and following the instructions showed once that succeeds, those environment variables are likely what's causing the error.

**Comment by nyetwurk** [comment]
@stgraber Thanks.

**Comment by nyetwurk** [comment]
Thanks for the quick turnaround on this one, @stgraber !
