### ISSUE TITLE
Live migration > ~20 times, slowed down

### ISSUE THREAD

**Issue by haha150** [lxc/lxd#5726]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 3.11
   * LXD version: 3.11
   * Storage backend in use: btrfs

# Issue description

So when i do live migration more than 20 times the migration slows down by 10x fold. The first, say 20 times, it took around 10 seconds to do lxc move, but after that it takes 2 minutes for lxc move to finish. Is there something not cleaned up or something else going on here?

Also, when i do lxc monitor i see that:

```
location: none
metadata:
  context: {}
  level: dbug
  message: About to receive rsync
timestamp: "2019-05-06T12:50:52.63886523Z"
type: logging
```

But i am using btrfs on both sides, why is it rsync?

# Steps to reproduce

1. lxc move c1 target:
2. wait ~30 sec
3. lxc move c1 source:
4. repeat 1-3

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ 
[source-lxd.log](https://github.com/lxc/lxd/files/3148028/source-lxd.log)
[target-lxd.log](https://github.com/lxc/lxd/files/3148029/target-lxd.log)

] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [
[source-lxc-monitor.log](https://github.com/lxc/lxd/files/3148023/source-lxc-monitor.log)
[target-lxc-monitor.log](https://github.com/lxc/lxd/files/3148024/target-lxc-monitor.log)

 ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by haha150** [comment]
is there maybe any way to check or cleanup lxd and btrfs database manually?

**Comment by stgraber** [comment]
And that container is stopped, started and then live migrated every time or do you keep it running in between tries?

Is the on-disk storage of the container growing?

**Comment by haha150** [comment]
Hi,

No i never stop or restart it, its always running between tries.

The disk is not growing i think.

**Comment by stgraber** [comment]
does stopping the container and starting it again fix the migration time?

During a migration all that LXD transfers is less than 1k of config (the REST API query itself) and then the btrfs subvol + rsync of the state, the container is only interrupted during the state sync part.

If the disk isn't growing, there's no reason for the migration time to increase unless it's taking CRIU longer and longer to dump the container due to what's in memory.

**Comment by haha150** [comment]
Hi,

I did not try with restarting the container and migrating again. However, what seemed to be another fix for me was that if i stopped using the TCP service that my container is hosting for around 1 minute, and then started the connection again and then did migration, it seemed to work better.

**Comment by stgraber** [comment]
Ah, okay, then you are definitely in CRIU weirdness territory and not in LXD territory anymore :)

You may want to upgrade CRIU to the latest release (if you'r using the LXD snap, the next update, due on Monday will have CRIU 3.12) and file a bug with upstream at https://github.com/checkpoint-restore/criu

They will most likely need your dump and restore logs which you can find at /var/snap/lxd/common/lxd/logs on both the source and target. (/var/log/lxd/ if not using the snap)
