### ISSUE TITLE
Nice to have: write out config files and read it back in

### ISSUE THREAD

**Issue by chrisglass** [lxc/lxd#573]
It'd be nice to be able to pipe a config file back into LXD.

Exemple:

"lxc config profile edit $profile_name" -> Edit, copy, save

I'd like to be able to pipe: "cat myfile | lxc config profile edit $profile_name" for example

**Comment by stgraber** [comment]
So I think there are two things we want to do here:
 - Have "lxc profile show" use the same syntax as edit
 - Have "lxc profile edit" read from stdin when it's not a tty
