### ISSUE TITLE
SIGSEGV on bad request

### ISSUE THREAD

**Issue by mt-caret** [lxc/lxd#5738]
# Required information

 * Distribution: Ubuntu (inside of a LXD container)
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails: https://gist.github.com/mt-caret/0d6e2dc13b3aaa64839bfa29704d9ef4
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

I was attempting to create a container via the REST API, but I accidentally set the protocol to "simplestream" instead of "simplestreams". This resulted in LXD crashing with SIGSEGV; I expected LXD to handle bad input gracefully and (hopefully) return some sort of error.

# Steps to reproduce

1. create file bad_request.txt (note the protocol is `simplestream` instead of the correct `simplestreams`
```
{
  "architecture": "",
  "config": null,
  "devices": null,
  "ephemeral": false,
  "profiles": null,
  "stateful": false,
  "description": "",
  "name": "test-container7",
  "source": {
    "type": "image",
    "certificate": "",
    "alias": "18.04",
    "server": "https://cloud-images.ubuntu.com/releases",
    "protocol": "simplestream",
    "mode": "pull"
  },
  "instance_type": ""
}
```

2. `curl -X POST -H "Content-Type: application/json" -d @./bad_request.txt --unix-socket /var/lib/lxd/unix.socket http://unix.socket/1.0/containers`

The following is returned, suggesting success.
```
{"type":"async","status":"Operation created","status_code":100,"operation":"/1.0/operations/7f1e1707-6831-4179-836a-fbdd2edb8d6e","error_code":0,"error":"","metadata":{"id":"7f1e1707-6831-4179-836a-fbdd2edb8d6e","class":"task","description":"Creating container","created_at":"2019-05-08T12:37:07.067493131Z","updated_at":"2019-05-08T12:37:07.067493131Z","status":"Running","status_code":103,"resources":{"containers":["/1.0/containers/test-container"]},"metadata":null,"may_cancel":false,"err":""}}
```

3. `journalctl -u lxd` shows crash.

```
May 08 12:37:07 godev lxd[25242]: panic: runtime error: invalid memory address or nil pointer dereference
May 08 12:37:07 godev lxd[25242]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc6792e]
May 08 12:37:07 godev lxd[25242]: goroutine 899 [running]:
May 08 12:37:07 godev lxd[25242]: main.(*Daemon).ImageDownload(0xc4201bb8c0, 0xc420306410, 0xc42018e120, 0x28, 0xc4207f81f0, 0xc, 0x0, 0x0, 0x0, 0x0, ...)
May 08 12:37:07 godev lxd[25242]:         /build/lxd-j7VLB_/lxd-3.0.3/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/daemon_images.go:512 +0x151e
May 08 12:37:07 godev lxd[25242]: main.createFromImage.func1(0xc420306410, 0xc42048fd08, 0x44662c)
May 08 12:37:07 godev lxd[25242]:         /build/lxd-j7VLB_/lxd-3.0.3/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/containers_post.go:106 +0x209
May 08 12:37:07 godev lxd[25242]: main.(*operation).Run.func1(0xc420306410, 0xc420268720)
May 08 12:37:07 godev lxd[25242]:         /build/lxd-j7VLB_/lxd-3.0.3/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/operations.go:140 +0x4a
May 08 12:37:07 godev lxd[25242]: created by main.(*operation).Run
May 08 12:37:07 godev lxd[25242]:         /build/lxd-j7VLB_/lxd-3.0.3/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxd/operations.go:139 +0x397
May 08 12:37:07 godev systemd[1]: lxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 08 12:37:07 godev systemd[1]: lxd.service: Failed with result 'exit-code'.
May 08 12:37:07 godev systemd[1]: lxd.service: Service hold-off time over, scheduling restart.
May 08 12:37:07 godev systemd[1]: lxd.service: Scheduled restart job, restart counter is at 7.
May 08 12:37:07 godev systemd[1]: Stopped LXD - main daemon.
```

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Oh wow! Surprised nobody ran into that before, should be an easy one to sort out at least :)

**Comment by stgraber** [comment]
```Error: Unsupported protocol: simplestream```
That's more like it :)
