### ISSUE TITLE
LXD 3.13 at Disco Server giving error: lxc launch ubuntu:19.04 first If this is your first time running LXD on this machine, you should also run: lxd init To start your first container, try: lxc launch ubuntu:18.04  Error: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: permission denied

### ISSUE THREAD

**Issue by skboseATg2d1** [lxc/lxd#5750]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by skboseATg2d1** [comment]
I have installed LXD 3.13 from the Feature Release, with my Kernel 5.0+ following the first step : Creating and Using your first Container as in https://linuxcontainers.org/lxd/getting-started-cli/ . Please help.

Rgds Shamik

**Comment by skboseATg2d1** [comment]
lxc launch ubuntu:19.04 first -- the command gave the error.

**Comment by skboseATg2d1** [comment]
Linux 5.0.0-13-generic x86_64

**Comment by skboseATg2d1** [comment]
I took the tar file for lxd with a sudo installation. Is that the right way? Pls suggest the steps to be taken from the start . Rgds

**Comment by blinkeye** [comment]
You need to add your user to the lxd group:

```
sudo usermod --append --groups lxd $(whoami)
newgroup lxd
```
then you can:
```
lxc launch ubuntu:19.04
```

assuming you've run `lxd init` once before.
