### ISSUE TITLE
LXC cannot resolve DNS name for containers when configuring a proxy

### ISSUE THREAD

**Issue by jus-x** [lxc/lxd#5754]
# Required information
 * Distribution: ubuntu
 * Distribution version: 16.04.5 LTS

# Issue description
Hello! I'm not sure whether this is the right place for this issue but I've encountered the following bug / issue after upgrading to the newest lxd:
After snap upgraded my lxd to 3.13, I could not configure a proxy device for a container, using the container dns-name as IP. This was possible in version 3.12.

# Steps to reproduce
Running the following leads to an error when using lxd 3.13:
```
$ lxc launch ubuntu:16.04 testcontainer
Creating testcontainer
Starting testcontainer
$ lxc config device add testcontainer proxy0 proxy listen=tcp:0.0.0.0:12345 connect=tcp:testcontainer.lxd:27017
Error: Invalid devices: Not an IP address: testcontainer.lxd
```

In lxd 3.12 there is no issue running these commands:
```
$ lxc launch ubuntu:16.04 testcontainer
Creating testcontainer
Starting testcontainer
$ lxc config device add testcontainer proxy0 proxy listen=tcp:0.0.0.0:12345 connect=tcp:testcontainer.lxd:27017
Device proxy0 added to testcontainer
```

**Comment by stgraber** [comment]
That's normal, the fact that we were resolving was a bug and could have evolved to be a security issue, it was never intended to support DNS names.

In your case, maybe connect=tcp:127.0.0.1:27017 would do the trick?

**Comment by jus-x** [comment]
Yes that did the trick, I used the proxy definition wrong. Thanks for your response anyway!
