### ISSUE TITLE
`limits.kernel.*` not applied to `lxc exec`

### ISSUE THREAD

**Issue by Saviq** [lxc/lxd#5755]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 19.04
 * [The output of "lxc info"](https://github.com/lxc/lxd/files/3178109/lxc.txt)

# Issue description

When setting `limits.kernel.*`, they don't get applied to `lxc exec` into the container.

# Steps to reproduce

 1. `lxc launch --config limits.kernel.core=unlimited ubuntu: limits-test`
 2. `lxc exec limits-test -- bash`
 3. 
```
$ ulimit -c
0
```

# Information to attach

 - [x] [Container configuration (`lxc config show NAME --expanded`)](https://github.com/lxc/lxd/files/3178116/lxc-config.txt)

**Comment by stgraber** [comment]
I suspect the problem is in liblxc's attach rather than in LXD but I'll let @brauner confirm before I move the issue over to lxc.

**Comment by brauner** [comment]
Works fine for me:
```
brauner@wittgenstein|~
> lxc shell b2
mesg: ttyname failed: No such device
root@b2:~# ulimit -c
unlimited
root@b2:~#
```

**Comment by stgraber** [comment]
Doesn't here.

```
stgraber@castiana:~$ lxc launch --config limits.kernel.core=1234 ubuntu:18.04 limits
Creating limits
Starting limits
stgraber@castiana:~$ lxc exec limits bash
root@limits:~# ulimit -c
0
root@limits:~# exit
stgraber@castiana:~$ lxc shell limits
mesg: ttyname failed: No such device
root@limits:~# ulimit -c
1
root@limits:~# logout
stgraber@castiana:~$ lxc exec limits bash
root@limits:~# cat /proc/1/limits | grep -i core
Max core file size        1234                 1234                 bytes     
root@limits:~# 
```

**Comment by brauner** [comment]
```
root@limits-test:~# ulimit -c
unlimited
root@limits-test:~# cat /proc/1/limits  | grep -i core
Max core file size        unlimited            unlimited            bytes
```

**Comment by brauner** [comment]
Also works for shell for me:
```
root@limits-test:~# cat /proc/self/limits | grep -i core
Max core file size        1234                 1234                 bytes
```
