### ISSUE TITLE
auto snapshots stop working after enabling delete protection.

### ISSUE THREAD

**Issue by garymol** [lxc/lxd#5761]
# Required information

 * Distribution:  Centos
 * Distribution version:  7.6.1810
 * The output of "lxc info"
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - <omitted>:8443
  architectures:
  - x86_64
  - i686
  certificate: | 
   <snip>
  certificate_fingerprint: 19deed14b822b86d847ad4a47544c88cd18818277d6c4f7cee8b6c1466f5891d
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "false"
  kernel_version: 4.4.178-1.el7.elrepo.x86_64
  project: default
  server: lxd
  server_clustered: false
  server_name: <omitted>
  server_pid: 20908
  server_version: "3.12"
  storage: zfs
  storage_version: 0.7.12-1

# Issue description
All of my containers are set to auto-snapshot to a fixed name at midnight with a 23hr expire time.   This has worked well daily for about 3-4 weeks without error.

Last week, I set the protection deletion flag on the containers using:
    lxc config set <container> security.protection.delete true

On two separate days since enabling the deletion protection,  three of my LXD based hosts have failed to automatically create their snapshots. 

This is the config of a container that failed to auto-snapshot last night:

# lxc config show etcd01-sci
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Centos 7 amd64 (20181217_02:16)
  image.os: Centos
  image.release: "7"
  image.serial: "20181217_02:16"
  security.protection.delete: "true"
  snapshots.expiry: 23H
  snapshots.pattern: borg_backup
  snapshots.schedule: 0 0 * * *
  snapshots.schedule.stopped: "true"
  volatile.base_image: d372613ec481e2febddcad91c6cf579b02f7e989958c059d54474a0011d973d2
  volatile.eth0.hwaddr: 00:16:3e:e3:b0:71
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""

Logs over the time period showing a successful snapshot and then the absence:

t=2019-05-13T17:13:48-0400 lvl=info msg="Updating images" 
t=2019-05-13T17:13:48-0400 lvl=info msg="Done updating images" 
t=2019-05-13T17:14:27-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-13T17:14:27-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-13T18:14:27-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-13T18:14:27-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-13T19:14:27-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-13T19:14:27-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-13T20:14:28-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-13T20:14:28-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-13T21:14:28-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-13T21:14:28-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-13T22:14:28-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-13T22:14:28-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-13T23:00:59-0400 lvl=info msg="Pruning expired container snapshots" 
t=2019-05-13T23:00:59-0400 lvl=info msg="Deleting container" created=2019-05-13T00:00:51-0400 ephemeral=false name=etcd01-sci/borg_backup project=default used=1969-12-31T19:00:00-0500
t=2019-05-13T23:00:59-0400 lvl=info msg="Done pruning expired container snapshots" 
t=2019-05-13T23:00:59-0400 lvl=info msg="Deleted container" created=2019-05-13T00:00:51-0400 ephemeral=false name=etcd01-sci/borg_backup project=default used=1969-12-31T19:00:00-0500
t=2019-05-13T23:13:48-0400 lvl=info msg="Updating images" 
t=2019-05-13T23:13:48-0400 lvl=info msg="Done updating images" 
t=2019-05-13T23:14:28-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-13T23:14:28-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T00:00:55-0400 lvl=info msg="Creating scheduled container snapshots" 
t=2019-05-14T00:00:55-0400 lvl=info msg="Done creating scheduled container snapshots" 
t=2019-05-14T00:00:55-0400 lvl=info msg="Creating container" ephemeral=false name=etcd01-sci/borg_backup project=default
t=2019-05-14T00:00:55-0400 lvl=info msg="Created container" ephemeral=false name=etcd01-sci/borg_backup project=default
t=2019-05-14T00:14:28-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T00:14:28-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T01:14:28-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T01:14:28-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T02:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T02:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T03:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T03:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-15T03:14:32-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-15T03:14:32-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-15T04:14:32-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-15T04:14:32-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-15T05:13:48-0400 lvl=info msg="Updating images" 
t=2019-05-15T05:13:48-0400 lvl=info msg="Done updating images"

**Comment by tomponline** [comment]
@garymol Hi, I noticed in your config above you have this line:

```
snapshots.schedule.stopped: "true"
```

Can you confirm whether you have set this or whether it has become set without you doing it?

Thanks

**Comment by garymol** [comment]
I intentionally set this option when I enabled autosnapshots.  In the event the container is stopped, we still want the snapshots to exist.

Gary.

**Comment by tomponline** [comment]
thanks @garymol I will continue to try and re-produce issue.

**Comment by tomponline** [comment]
@garymol so just to confirm I am interpreting your longs correctly, there was nothing in the output for 24 hours between these 2 lines?

```
t=2019-05-14T03:14:29-0400 lvl=info msg="Done pruning expired container backups"
t=2019-05-15T03:14:32-0400 lvl=info msg="Pruning expired container backups"
```

**Comment by garymol** [comment]
Sorry, my mistake.  Here are all the logs for those 24 hours:

t=2019-05-14T03:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T03:14:29-0400 lvl=info msg="Done pruning expired container backups" 
[root@service3 lxd]# zcat lxd.log-20190515.gz
t=2019-05-14T04:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T04:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T05:13:48-0400 lvl=info msg="Updating images" 
t=2019-05-14T05:13:48-0400 lvl=info msg="Done updating images" 
t=2019-05-14T05:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T05:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T06:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T06:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T07:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T07:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T08:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T08:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T09:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T09:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T10:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T10:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T11:13:42-0400 lvl=info msg="Pruning expired images" 
t=2019-05-14T11:13:42-0400 lvl=info msg="Done pruning expired images" 
t=2019-05-14T11:13:43-0400 lvl=info msg="Updating instance types" 
t=2019-05-14T11:13:43-0400 lvl=info msg="Expiring log files" 
t=2019-05-14T11:13:43-0400 lvl=info msg="Done updating instance types" 
t=2019-05-14T11:13:43-0400 lvl=info msg="Done expiring log files" 
t=2019-05-14T11:13:48-0400 lvl=info msg="Updating images" 
t=2019-05-14T11:13:48-0400 lvl=info msg="Done updating images" 
t=2019-05-14T11:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T11:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T12:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T12:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T13:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T13:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T14:14:29-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T14:14:29-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T15:14:30-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T15:14:30-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T16:14:30-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T16:14:30-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T17:13:48-0400 lvl=info msg="Updating images" 
t=2019-05-14T17:13:48-0400 lvl=info msg="Done updating images" 
t=2019-05-14T17:14:30-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T17:14:30-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T18:14:30-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T18:14:30-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T19:14:30-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T19:14:30-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T20:14:30-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T20:14:30-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T21:14:30-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T21:14:30-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T22:14:30-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T22:14:30-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-14T23:01:06-0400 lvl=info msg="Pruning expired container snapshots" 
t=2019-05-14T23:01:06-0400 lvl=info msg="Deleting container" created=2019-05-14T00:00:55-0400 ephemeral=false name=etcd01-sci/borg_backup project=default used=1969-12-31T19:00:00-0500
t=2019-05-14T23:01:06-0400 lvl=info msg="Done pruning expired container snapshots" 
t=2019-05-14T23:01:07-0400 lvl=info msg="Deleted container" created=2019-05-14T00:00:55-0400 ephemeral=false name=etcd01-sci/borg_backup project=default used=1969-12-31T19:00:00-0500
t=2019-05-14T23:13:48-0400 lvl=info msg="Updating images" 
t=2019-05-14T23:13:48-0400 lvl=info msg="Done updating images" 
t=2019-05-14T23:14:30-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-14T23:14:30-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-15T00:14:31-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-15T00:14:31-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-15T01:14:31-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-15T01:14:31-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-15T02:14:31-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-15T02:14:31-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-15T03:14:32-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-15T03:14:32-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-15T04:14:32-0400 lvl=info msg="Pruning expired container backups" 
t=2019-05-15T04:14:32-0400 lvl=info msg="Done pruning expired container backups" 
t=2019-05-15T05:13:48-0400 lvl=info msg="Updating images" 
t=2019-05-15T05:13:48-0400 lvl=info msg="Done updating images"

**Comment by tomponline** [comment]
@stgraber I haven't been able to re-create this, however after looking at the scheduling code, I am not entirely comfortable that there aren't some edge cases in there that may cause this.

I've been focusing on reasoning why this line is missing from the logs:

https://github.com/lxc/lxd/blob/8137ef0d5f79f2c64a7157bd92d2ad29aee40757/lxd/container.go#L1670

```Creating scheduled container snapshots```

This is most likely caused by not having any snapshots matched for scheduling.

Looking at this chunk of code:

https://github.com/lxc/lxd/blob/8137ef0d5f79f2c64a7157bd92d2ad29aee40757/lxd/container.go#L1636-L1646

It seems potentially brittle in the use of the exact match of `Equal` (https://github.com/lxc/lxd/blob/8137ef0d5f79f2c64a7157bd92d2ad29aee40757/lxd/container.go#L1644) even though the times have been truncated to minute granularity.

Because the schedules are reset after each task run using an independent timer from the time the last task finished, the schedules are prone to drift:

https://github.com/lxc/lxd/blob/master/lxd/task/task.go#L53

If the schedule drifted to running at "x:59" in the minute, then when passed to the `next := sched.Next(now)` this would add 1s and trip over to the next minute, which would then not match the `time.Equal()` check.

Potentially move the `now = now.Truncate(time.Minute)` line to above the `next := sched.Next(now)` would avoid this.

**Comment by tomponline** [comment]
@garymol are you able to restart LXD service to see if resetting the timers results in the snapshots being taken again?

**Comment by garymol** [comment]
I can restart LXD as needed.   I should point out that the container snapshot did create successfully on the next run.  (ie this morning):

> lxc info etcd01-sci
Name: etcd01-sci
Location: none
Remote: unix://
Architecture: x86_64
Created: 2018/12/18 04:00 UTC
Status: Running
Type: persistent
...
Snapshots:
  borg_backup (taken at 2019/05/16 04:00 UTC) (expires at 2019/05/17 03:00 UTC) (stateless)

**Comment by tomponline** [comment]
@garymol interesting, so its not a permanent problem with the config, so it could be an edge case time comparison bug rather than a config problem.

**Comment by garymol** [comment]
Because its a random failure, I didn't suspect a config issue.

In the three cases where this happened so far, each LXD successfully created the snapshots the next day.  On each failed instance, all of the containers configured to auto-snapshot on that server failed at the same time.

**Comment by tomponline** [comment]
Thanks @garymol that would make sense as the snapshot scheduler applies to all containers on that host.

I was referencing the part in the case title about "after enabling delete protection" that I thought it may be related to your config. But I think that could not be the case. From looking at the code, it could in theory at least happen with or without delete protection being enabled. There doesn't appear to be any relationship between those 2 features.

**Comment by garymol** [comment]
Understood.

**Comment by tomponline** [comment]
@stgraber @garymol I've proved that at least in principle you can end up missing a cycle if the check is run at "xx:xx:59".

I added a single error log entry showing when the checks are run, and then artificially slept for 1s each cycle thus drifting the next cycle by 1s and left it to run.

You can see there is a check at 18:43:59 and then nothing at 18:45:00 except my log line, thus missing a minute of snapshots.

```
EROR[05-16|18:43:59] tomp: 2019-05-16 18:43:59.883807118 +0100 BST m=+2684.723551616 
DBUG[05-16|18:43:59] New task operation: 8c60930c-c403-4376-b876-70ee4fe3b28f 
INFO[05-16|18:43:59] Creating scheduled container snapshots 
DBUG[05-16|18:43:59] Started task operation: 8c60930c-c403-4376-b876-70ee4fe3b28f 
INFO[05-16|18:43:59] Done creating scheduled container snapshots 
INFO[05-16|18:43:59] Creating container                       project=default name=test1/borg_backup-39 ephemeral=false
INFO[05-16|18:43:59] Created container                        ephemeral=false project=default name=test1/borg_backup-39
DBUG[05-16|18:43:59] Creating DIR storage volume for snapshot "test1" on storage pool "default" 
DBUG[05-16|18:44:03] Created DIR storage volume for snapshot "test1" on storage pool "default" 
DBUG[05-16|18:44:03] Success for task operation: 8c60930c-c403-4376-b876-70ee4fe3b28f 
DBUG[05-16|18:44:16] New task operation: 3fc560f5-e0ac-42c8-861f-e507a3de21f3 
INFO[05-16|18:44:16] Pruning expired container snapshots 
DBUG[05-16|18:44:16] Started task operation: 3fc560f5-e0ac-42c8-861f-e507a3de21f3 
INFO[05-16|18:44:16] Deleting container                       created=2019-05-16T18:42:58+0100 ephemeral=false used=1970-01-01T01:00:00+0100 project=default name=test1/borg_backup-38
INFO[05-16|18:44:16] Done pruning expired container snapshots 
DBUG[05-16|18:44:16] Deleting DIR storage volume for snapshot "test1/borg_backup-38" on storage pool "default" 
DBUG[05-16|18:44:16] Deleted DIR storage volume for snapshot "test1/borg_backup-38" on storage pool "default" 
INFO[05-16|18:44:16] Deleted container                        used=1970-01-01T01:00:00+0100 project=default name=test1/borg_backup-38 created=2019-05-16T18:42:58+0100 ephemeral=false
DBUG[05-16|18:44:16] Success for task operation: 3fc560f5-e0ac-42c8-861f-e507a3de21f3 
EROR[05-16|18:45:00] tomp: 2019-05-16 18:45:00.894207438 +0100 BST m=+2745.733951928 
DBUG[05-16|18:45:14] Handling                                 method=GET url=/1.0 ip=@ user=
DBUG[05-16|18:45:14] Handling                                 method=GET url=/1.0/containers/test1 ip=@ user=
DBUG[05-16|18:45:14] Handling                                 method=GET url=/1.0/containers/test1/state ip=@ user=
DBUG[05-16|18:45:14] Handling                                 method=GET url="/1.0/containers/test1/snapshots?recursion=1" ip=@ user=
DBUG[05-16|18:45:16] New task operation: 84800de1-5ea9-4993-b4cd-557a5fd14c6a 
INFO[05-16|18:45:16] Pruning expired container snapshots 
DBUG[05-16|18:45:16] Started task operation: 84800de1-5ea9-4993-b4cd-557a5fd14c6a 
INFO[05-16|18:45:16] Deleting container                       project=default name=test1/borg_backup-39 created=2019-05-16T18:43:59+0100 ephemeral=false used=1970-01-01T01:00:00+0100
INFO[05-16|18:45:16] Done pruning expired container snapshots 
DBUG[05-16|18:45:16] Deleting DIR storage volume for snapshot "test1/borg_backup-39" on storage pool "default" 
DBUG[05-16|18:45:16] Deleted DIR storage volume for snapshot "test1/borg_backup-39" on storage pool "default" 
INFO[05-16|18:45:16] Deleted container                        name=test1/borg_backup-39 created=2019-05-16T18:43:59+0100 ephemeral=false used=1970-01-01T01:00:00+0100 project=default
DBUG[05-16|18:45:16] Success for task operation: 84800de1-5ea9-4993-b4cd-557a5fd14c6a 
EROR[05-16|18:46:01] tomp: 2019-05-16 18:46:01.896067485 +0100 BST m=+2806.735811950 
DBUG[05-16|18:46:01] New task operation: cf410620-e7c6-42e9-a202-7665e1c23fda 
INFO[05-16|18:46:01] Creating scheduled container snapshots 
DBUG[05-16|18:46:01] Started task operation: cf410620-e7c6-42e9-a202-7665e1c23fda 
INFO[05-16|18:46:01] Done creating scheduled container snapshots 

```
