### ISSUE TITLE
Publishing image from container lxd.CreateImage failing on ShiftOwner

### ISSUE THREAD

**Issue by joelhockey** [lxc/lxd#5763]
# Required information

  * LXD version: 3.0.2 with chromeos patches
  * Storage backend in use: btrfs

# Issue description

ChromeOS crostini users performing a backup of their container (lxd.CreateImage) are getting failures from lxd when it calls ShiftOwner as part of UnshiftRootfs during container Export.

"Failed to change ownership of: /mnt/stateful/lxd/storage-pools/default/snapshots/penguin/rootfs-backup/rootfs"

https://bugs.chromium.org/p/chromium/issues/detail?id=944758#c6

https://chromium.googlesource.com/chromiumos/platform/tremplin/+/b766733ee23098959e241e7afecba99bf7da12e8/src/chromiumos/tremplin/tremplin.go#1055

https://github.com/lxc/lxd/blob/7a9a4e24f0eba557c913e735527999aed841fee7/lxd/images.go#L267

https://github.com/lxc/lxd/blob/8137ef0d5f79f2c64a7157bd92d2ad29aee40757/lxd/container_lxc.go#L5305

https://github.com/lxc/lxd/blob/6e81c4b916b6013085590e01ba3b719381d35e3b/shared/idmap/shift_linux.go#L164

# Steps to reproduce

I'm not able to reliably reproduce the issue.  I have experienced this issue, but only a non-devmode chromebook where it isn't possible to do much debugging.

Please share if you have any thoughts about the underlying cause of the shiftowners failure, or ways to fix the issue.  The current code in tremplin.go is creating an image from a container-snapshot whilst the container is still running.  Is this supported for the container to still be running?

**Comment by stgraber** [comment]
@brauner want to take a quick look through the codepath for potential spots where things may fail?

Sounds like we at least could improve error reporting there to know exactly what part failed.

**Comment by stgraber** [comment]
@joelhockey did you guys start looking at shiftfs and whether this would be suitable for your kernel? That would eliminate all of that shifting logic which has been a pain point for you.

The main limitation there right now is missing support for overlayfs on top of btrfs, @brauner is working on that part, but the rest should be working fine now, including btrfs ioctls.

**Comment by joelhockey** [comment]
@smibarber I've heard you mention using shiftfs

**Comment by smibarber** [comment]
We've not been able to look at shiftfs yet, but it's definitely on our roadmap. That seems to be the most frequent issue we're hitting with backups, although we also don't handle the disk full case very well either. But I think the full disk and shift backup failures are distinct.

**Comment by stgraber** [comment]
@brauner ping again

**Comment by brauner** [comment]
Oh, sorry, I only ever saw the part about shiftfs not about the issue, sorry.

**Comment by brauner** [comment]
Hm, can you reproduce this with broken symlinks in the rootfs maybe @smibarber?

**Comment by stgraber** [comment]
@brauner would be nice to at least improve our logging around those failures, so we know exactly what operation failed on what file.

I'm also wondering whether we even want a failure on an individual file considering there's little we can do to revert a partial shift...

**Comment by joelhockey** [comment]
To add more info, I have been able to replicate the issue by rebooting the device whilst in the middle of backup.  It is the chmod call that is failing.

lxd output: Failed chown: Read-only file system

[pid  1866] openat(AT_FDCWD, "/mnt/stateful/lxd/storage-pools/default/snapshots/penguin/rootfs-backup/rootfs", O_RDONLY|O_NOFOLLOW|O_PATH) = 23
[pid  1866] readlink("/proc/self/fd/23", "/mnt/stateful/lxd/storage-pools/"..., 4096) = 78
[pid  1866] fchownat(23, "", 0, 0, AT_SYMLINK_NOFOLLOW|AT_EMPTY_PATH) = -1 EROFS (Read-only file system)

And I get the same error if I call chown from cmdline:

strace chown 0:0 /mnt/stateful/lxd/storage-pools/default/snapshots/penguin/rootfs-backup/r
ootfs
                               = 0
newfstatat(AT_FDCWD, "/mnt/stateful/lxd/storage-pools/default/snapshots/penguin/rootfs-backup/rootfs", {st_mode=S_IFDIR|0777, st_size=148, ...}, AT_SYMLINK_NOFOLLOW) = 0
chown("/mnt/stateful/lxd/storage-pools/default/snapshots/penguin/rootfs-backup/rootfs", 0, 0) = -1 EROFS (Read-only file system)

The directory is owned by 1000000

 ls -ld /mnt/stateful/lxd/storage-pools/default/snapshots/penguin/rootfs-backup/rootfs
drwxrwxrwx 1 1000000 1000000 148 Oct  5  2018 /mnt/stateful/lxd/storage-pools/default/snapshots/penguin/rootfs-backup/rootfs

I see some reports that btrfs can go readonly when it has corruption.  I wonder if that has happened?

**Comment by brauner** [comment]
That's the vfs itself - I think - that remounts an fs ro on corruption, so yes. That can totally happen. :)

**Comment by stgraber** [comment]
Could also be a btrfs snapshot that's stuck in read-only mode in this case.

**Comment by brauner** [comment]
I'll see if we can log nicer and/or remove error handling completely.

**Comment by stgraber** [comment]
I know we have logic in the btrfs code to make snapshots read/write or read-only as needed. I wonder if there's a case where we may get interrupted in between making the snapshot and marking it read-write which would then explain the failure to shift.

**Comment by stgraber** [comment]
There's a general issue in our shifting logic when it hits a read-only btrfs subvolume as it will fail shifting there. I think we need to add logic to the shifter for this, so it can mark the subvolume read-write, keep shifting and put a deferred function which will mark the subvolume read-only again once done shifting.

@brauner can you look into that too? Should be pretty trivial to reproduce this case inside a LXD container by using `btrfs subvol snapshot -r`.

**Comment by joelhockey** [comment]
The chromeos backup logic creates a snapshot which is always named 'penguin/rootfs-backup'.  When backup starts, it deletes any existing snapshot with name 'rootfs-backup' and then creates a new one with that name.

If I create a different named snapshot (lxc snapshot penguin), then I have no problem doing 'lxc publish penguin/snap0'.

I see that even after deleting the 'rootfs-backup' snapshot, I still have a directory named /mnt/stateful/lxd/storage-pools/default/snapshots/penguin/rootfs-backup.ro.  I suspect that since this dir stays around, then any newly created snapshot with name 'rootfs-backup' is going to be considered ro.

I suspect that if I delete the rootfs-backup.ro dir, then things will start working OK, but I want to keep trying some things first.

Q: When deleting a snapshot, should lxd check for the <snapshot>.ro dir and also make sure it gets deleted?

**Comment by joelhockey** [comment]
I think I see what is happening at the code at https://github.com/lxc/lxd/blob/ab71a90c0d244de0074efcfd557b3bb92df745df/lxd/storage_btrfs.go#L1493

Should this code delete any existing *.ro snapshot subvolume (I'm using words I don't really understand here) rather than reusing it?

**Comment by brauner** [comment]
> There's a general issue in our shifting logic when it hits a read-only btrfs subvolume as it will fail shifting there. I think we need to add logic to the shifter for this, so it can mark the subvolume read-write, keep shifting and put a deferred function which will mark the subvolume read-only again once done shifting.

I'm not sure I understand. Why would that happen from LXD itself. This is something the user must have set, no? It sounds odd to mount rw, shift, and then make ro again. If there's no proper reason for the volume to be ro I'm not sure we should just mess with things like that?

**Comment by brauner** [comment]
> I think I see what is happening at the code at
> 
> https://github.com/lxc/lxd/blob/ab71a90c0d244de0074efcfd557b3bb92df745df/lxd/storage_btrfs.go#L1493
> 
> Should this code delete any existing *.ro snapshot subvolume (I'm using words I don't really understand here) rather than reusing it?

I'm not completely sure why we've done it this way.
We can certainly try and see if this messes with anything and if not make it so.
if it causes problems we can try and check whether the existing snapshot is ro and if so remount rw.

**Comment by stgraber** [comment]
@brauner The user in the container can create subvolumes, then make those read-only. When this happens, our shifting logic fails with "filesystem read-only". This leaves us with a half shifted filesystem...

The only way to shift a read-only subvolume is to unset the read-only property, shift and set it back to read-only.

Skipping over those read-only subvolumes isn't an option as doing so would allow any user in the container to keep files owned as an unmapped user. Combine this with some setuid/setgid files and we may have a bit of a problem on our hands. At best we end up with undeletable and unaccessible files in the container and at worst a security issue.

**Comment by joelhockey** [comment]
I'm pretty sure this fixes my usecase, so I'm happy to close this issue, but I see there is other discussion about some other possible changes, so I will leave this up to you.
