### ISSUE TITLE
Extend SRIOV network device to support setting anti-spoofing and vlan ID

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#5765]
We should allow the `vlan` property for SRIOV network device (setting the vid on the NIC) and `security.mac_filtering` which sets the anti-spoofing property.

**Comment by stgraber** [comment]
@tomponline let me know if you have any questions. I do have access to hardware that will work with this, but I don't think on any throw away system at this point, so I'd have to test the result myself.

**Comment by tomponline** [comment]
@stgraber I haven't used SRIOV before, is this something I can simulate locally? Thanks

**Comment by stgraber** [comment]
@tomponline I don't know about that, I'm testing on lantea now to see if the ConectX3 card in there can be made to behave in ethernet mode.
