### ISSUE TITLE
Lxc Import

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#5767]
Could there be away to initiate an import of a backup.tar.gz through the LXD rest API ? 

## Why ?

**not suggesting LXD team implements any of this**

It would be useful in an instance where you dont want to use a LXD server as a backup, 

For example a backup server could use the following process:

### Backing up (can be done)

1. Create backup through LXD api 
2. listen for backup successful operation emit 
3. backup server downloads tar ball 

### Recovering (can't be done only through LXD API)

1. backup server receives a request to restore container 
2. backup is either sent as a data stream or path to file

**Comment by stgraber** [comment]
Everything that `lxc` does is done over the REST API and can be done remotely.

So your backup server can absolutely use our existing API to create a snapshot, then download it when ready and to restore, can either restore it from the server or anywhere that can reach the LXD target.

**Comment by turtle0x1** [comment]
So your saying the steps to backup & recovery could be; 

## Backup 

1. Snapshot container
2. Create image from snapshot 
3. Download image

## Recovery
1. LXD requests image from backup server (over http / simple streams)
2. Creates container 
3. Remove the backup image

**Comment by lhorace** [comment]
@stgraber Why you close this ticket this early

**Comment by lhorace** [comment]
@stgraber Can you put you a shit a side and not close ticket automatically

**Comment by turtle0x1** [comment]
Chill dude

**Comment by lhorace** [comment]
I like them to do better, I've been since LXC before LXD Ubuntu pick it up

**Comment by lhorace** [comment]
They finally introduced IPVLAN, that's great, they are not total assholes.

**Comment by lhorace** [comment]
@turtle0x1 Same way I complain, there is not difference, I will treat you the same

**Comment by stgraber** [comment]
@lhorace we close bugs that aren't bugs, that doesn't mean we don't still engage in comments, it just means there's no issue for us to fix.

**Comment by stgraber** [comment]
@turtle0x1 no, we have an actual backup API.
That's what `lxc export` and `lxc import` drive behind the scenes.

https://github.com/lxc/lxd/blob/master/doc/rest-api.md#10containersnamebackups

**Comment by stgraber** [comment]
Restoring the backup is done by doing a POST with the backup as data to `/1.0/containers` effectively creating the container from the backup.

**Comment by turtle0x1** [comment]
great thanks alot :)
