### ISSUE TITLE
lxc restore fails on zfs backend when using projects (searches for wrong snapshot)

### ISSUE THREAD

**Issue by idef1x** [lxc/lxd#5773]
# Required information

 * Distribution: ubuntu
 * Distribution version: 18.10
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version: snap 3.13 10756
   * Storage backend in use: ZFS

# Issue description
When using projects, restoring from a snapshot (created with lxc) will fail due to lxc looking for the wrong snapshot to restore.

# Steps to reproduce

 1. Step one
- create project (lxc project create test)
- switch to project: lxc project switch test
- edit default profile to have at least a disk device
- create container: lxc launch images:alpine/edge test

 2. Step two
- create snapshot of container: lxc snapshot test torestore
 3. Step three
- stop container : lxc stop test 
- restore snapshot: lxc restore test torestore
Error: Failed to restore ZFS snapshot: cannot open 'data/asterix/lxd/containers/test@snapshot-torestore': dataset does not exist

Actual zfs snapshot: zfs list -t snapshot | grep torestore
data/asterix/lxd/containers/test_test@snapshot-torestore

So snapshot is created with project name, but restore wants it without the project name

**Comment by stgraber** [comment]
Thanks, sent a fix

**Comment by idef1x** [comment]
Quick as always :) Thanks!
