### ISSUE TITLE
rtorrent error in container

### ISSUE THREAD

**Issue by Nesta0** [lxc/lxd#5777]
* Distribution:  Ubuntu
 * Distribution version: 18.04
   * LXD version: 3.0.2
   * Storage backend in use: ZFS

# Issue description

Hello, 

I have a problem when i try to create a seedbox in a container using rtorrent+rutorrent.
This error is new. I was before  on ubuntu 16.04 with lxd 2.0 and i had  no problem at all to create a seedbox using the same procedure.

It seems to be a cgroup problem. When i try to start rtorrent i have those error message in the syslog:

`user-1000.slice: Failed to set invocation ID on control group /user.slice/user-1000.slice, ignoring: Operation not permitted
Created slice User Slice of nesta.
user-1000.slice: Failed to set invocation ID on control group /user.slice/user-1000.slice, ignoring: Operation not permitted
user@1000.service: Failed to set invocation ID on control group /user.slice/user-1000.slice/user@1000.service, ignoring: Operation not permitted
 Starting User Manager for UID 1000...
session-c5.scope: Failed to set invocation ID on control group /user.slice/user-1000.slice/session-c5.scope, ignoring: Operation not permitted
May 17 17:41:28 nestaseed systemd[1]: Started Session c5 of user nesta.
M`

Thank you in advance

**Comment by stgraber** [comment]
Those are normally all fine, it's just systemd being pretty verbose.

What's failing exactly? Is it a systemd unit or what?

**Comment by Nesta0** [comment]
I really don't know what is the problem rtorrent is deamonize with screen. And i'm using an init script to launch it. But when i try start the daemon, nothing happened. And i have nothing in the log. The only thing i have is the systemd user-1000.slice each time i try to launch rtorrent. 
The procedure is working on a physical machine but not in a container.

**Comment by Nesta0** [comment]
Find out what was the problem. Sorry, nothing to do with lxd.
