### ISSUE TITLE
Proxy Device fails to start

### ISSUE THREAD

**Issue by ckeschnat** [lxc/lxd#5778]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 18.04.2 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 4.15.0-50-generic
   * LXD version: 3.13 (snap)
   * Storage backend in use: zfs

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

Everything was working fine until after a reboot.
Now lxc doesn't open any ports and trying to modify results in an error:
`$  lxc config device remove haproxy myport443
Error: Invalid devices: Not an IP address: localhost`

# Steps to reproduce

 1. Add a proxy device
`lxc config device add haproxy myport443 proxy listen=tcp:0.0.0.0:443 connect=tcp:localhost:443`
 2. Unsure. Worked fine for some time.
 3. `$  cat /var/snap/lxd/common/lxd/logs/haproxy/proxy.myport443.log
Error: Not an IP address: localhost
Error: Not an IP address: localhost`

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

[lxc_info.txt](https://github.com/lxc/lxd/files/3192649/lxc_info.txt)
[container_configuration.txt](https://github.com/lxc/lxd/files/3192650/container_configuration.txt)
[container_log.txt](https://github.com/lxc/lxd/files/3192651/container_log.txt)
[daemon_debug.txt](https://github.com/lxc/lxd/files/3192652/daemon_debug.txt)
[daemon_log.txt](https://github.com/lxc/lxd/files/3192653/daemon_log.txt)
[ltc.txt](https://github.com/lxc/lxd/files/3192654/ltc.txt)

**Comment by stgraber** [comment]
Use `lxc config edit` to fix all errors in one shot?

**Comment by ckeschnat** [comment]
@stgraber Thanks, so simple. I change all occurences of `localhost` to `127.0.0.1`. Seems to work in a first test. Going to change the rest.
I tried to change it with `lxc config device set haproxy myport443 connect tcp:127.0.0.1:443`  before which threw the same error.

Thanks for the fast help. Awesome.

**Comment by stgraber** [comment]
Yeah, you had an invalid value that happened to work thanks to a bug in the proxy code, we fixed that bug and added the check. Changing a single line in the config causes it all to be re-validated which is why a simple add/remove would fail. `edit` lets you modify it all in one shot, making it pass validation.

Glad it worked and you're back to working order!
