### ISSUE TITLE
Issue Updating and Bulding from Source

### ISSUE THREAD

**Issue by cyberwillis** [lxc/lxd#5779]
# Required information

 * Distribution: **Ubuntu**
 * Distribution version: **16.04**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.4.0-148-lowlatency**
   * LXC version: **3.1.0**
   * LXD version: **3.13**
   * Storage backend in use: **zfs**

# Issue description
Building from source it shows this information
```
➜  lxd git:(master) make
go get -t -v -d ./...
CC=cc go install -v -tags "libsqlite3"  ./...
github.com/CanonicalLtd/raft-test/internal/network
# github.com/CanonicalLtd/raft-test/internal/network
/media/willismar/Dados/go/src/github.com/CanonicalLtd/raft-test/internal/network/network.go:53:2: cannot use transport (type *eventTransport) as type raft.Transport in return argument:
	*eventTransport does not implement raft.Transport (missing TimeoutNow method)
Makefile:18: recipe for target 'default' failed
make: *** [default] Error 2
```
I tried to reach the URL bellow but it states as 'Not Found ':
`https://github.com/CanonicalLtd/raft-test/internal/network/network.go`

But it can be found at:
`https://github.com/CanonicalLtd/raft-test/blob/master/internal/network/network.go`

# Steps to reproduce

 1. make update
 2. make deps
 3. make

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Run `git pull` in your `go/src/github.com/CanonicalLtd/raft-test` directory and that will pull in the fix needed for this.

It's something we fixed a couple weeks back when raft upstream changed their API.

**Comment by tomponline** [comment]
@stgraber I'm afraid they may have broken it again, I'm seeing the same error on a freshly built system

```
ubuntu@lantea:~/go/src/github.com/CanonicalLtd/raft-test$ go get github.com/CanonicalLtd/raft-test
# github.com/CanonicalLtd/raft-test/internal/network
internal/network/network.go:53:2: cannot use transport (type *eventTransport) as type raft.Transport in return argument:
	*eventTransport does not implement raft.Transport (missing TimeoutNow method)
```

Also https://github.com/hashicorp/raft/commit/eba83432bf24fbc71177da3718314fe166633ad0#diff-7a3d2ecae642058c45b6a1f699ee053dR175

**Comment by tomponline** [comment]
@cyberwillis until we fix the `raft-test` library to comply with the change in interface that the raft folks have made, you can build LXD by reverting the raft library to the previous version:

```
cd $GOAPTH/src/github.com/hashicorp/raft
git checkout 2c551690b5c0eb05ef7f4ad72ed01f7f6ce3fcb6
```

Then resume the original build instructions:

```
cd $GOPATH/src/github.com/lxc/lxd
make
```

**Comment by freeekanayaka** [comment]
Fixed here https://github.com/CanonicalLtd/raft-test/commit/ecdf110973a40c4c94fa1423b6fb6e37df90f2c5.
