### ISSUE TITLE
Copies of snapshots have the same IP address

### ISSUE THREAD

**Issue by chrisglass** [lxc/lxd#578]
LXD assigns the same IP address to containers in the following sequence of events:

lxc launch trusty something #"trusty" is 73500357e4d4
lxc snapshot something whatever
lxc copy something/whatever clone1
lxc copy something/whatever clone2
lxc start clone1
lxc start clone2
lxc list

What happens:
clone1 and clone2 report having the same (ipv4) address.

What should happen:
clone1 and clone2 have different (ipv4) addresses.

**Comment by stgraber** [comment]
This is caused by a missing reset of the volatile keys on copy.
