### ISSUE TITLE
lxd-p2c: "Failed to mark / private: Permission denied"

### ISSUE THREAD

**Issue by despens** [lxc/lxd#5781]
# Issue description

I was trying to run `lxd-p2c` in a lxc version 1.0.7 container, to transfer it to a new lxc host running  version 3.0.3 on Ubuntu 18.04.

The `lxd-p2c` binary was created on Ubuntu 18.04 using `go get github.com/lxc/lxd/lxd-p2c`.

When going into the container, I cannot run the binary, it fails with "Failed to mark / private: Permission denied" even when no parameters are passed.

```console
# lxc-attach -n apache-basic
root@apache-basic:~# ./lxd-p2c-amd64 
Failed to mark / private: Permission denied
```

**Comment by stgraber** [comment]
Your container doesn't allow the needed mount operation that `lxd-p2c` needs to perform, this isn't a lxd-p2c bug, it's an issue with the apparmor profile you're using on your source machine.
