### ISSUE TITLE
Lxc move fails with: Migration API failure: not found

### ISSUE THREAD

**Issue by YosuCadilla** [lxc/lxd#5800]
# Required information

LXD version 3.13 with 3 node cluster
OS Ubuntu 18.04
FS: ZFS
Network: FAN

# Issue description
Lxc move fails with: Migration API failure: not found
There are 3 nodes in the cluster named host1, host2, host3
Tested in all 3 nodes, always the same result.
 
# Steps to reproduce
lxc move old old2 --target host1 (the container currently lives in host2)

**Comment by stgraber** [comment]
Can you show the `lxc move` with `--debug` passed to it?

**Comment by stgraber** [comment]
@YosuCadilla
