### ISSUE TITLE
Automatically resize (shrink) BTRFS image file

### ISSUE THREAD

**Issue by heptathlon** [lxc/lxd#5801]
LXD doesn't automatically shrink the BTRFS image when a file inside a container or the container altogether is removed (although [BTRFS supports shrinking](https://gparted.sourceforge.io/features.php)).
Please automatically resize the BTRFS image file (partition and filesystem) from time to time and on certain events from LXD such as container deletion. In addition please also provide a command (eg, "lxd storage resize") to trigger resizing manually.

Rationale: I run LXD on SBCs with limited storage and the image file grows until it fills all available space without a way to shrink it in an elegant and automated way.

If supported by their respective driver this issue applies to all available storage formats.

refs
https://github.com/lxc/lxd/issues/5690

**Comment by stgraber** [comment]
Filesystems using a loop device that's a sparse file will normally allocate more space as needed but will never re-sparsify the underlying file as kernel interfaces to do this are still very new and rarely used.

The rationale for this is usually that such loop files are meant for testing and for environments where no dedicated disks or partitions exist but isn't meant for long time production uses and the complexity in allowing the filesystem to move its allocation around to re-sparsify tends to not be worth the effort.

As you mentioned, you can shrink a btrfs filesystem but this online operation typically involves relocating all blocks to free up space at the end of the block device, letting you put another partition afterwards.

In a loop environment, such a call will not actually shrink your file, it will just tell btrfs not to use the end of it.

```
root@castiana:~# mount blah.img /mnt/
root@castiana:~# ls -lh blah.img 
-rw-r--r-- 1 root root 4.0G May 31 14:37 blah.img
root@castiana:~# btrfs fi resize -1G /mnt/
Resize '/mnt/' of '-1G'
root@castiana:~# ls -lh blah.img 
-rw-r--r-- 1 root root 4.0G May 31 14:38 blah.img
root@castiana:~# 
```

There are tricks you can do to do it anyway, effectively manually creating a second loop file, adding it to btrfs as a mirror device, then removing the original, but this is slow and very much a manual process that we have no intention to automate in LXD.

LXD will happily generate loop files for our user's convenience but such low level modification of the filesystem is better done with the appropriate tools.
