### ISSUE TITLE
Error: Get http://unix.socket/1.0: EOF

### ISSUE THREAD

**Issue by Axel-AMGHAR** [lxc/lxd#5802]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:3.0.3
   * Storage backend in use:

# Issue description

Hello,
 when i change my internet network, my lxd stop working
Every time i use lsc or lxd commands, i have the same error :
Error: Get http://unix.socket/1.0: EOF

when i checked my lxd.log i have:

"Cannot listen on https socket, skipping..." err="listen tcp 192.168.1.15:8443: bind: cannot assign requested address"
 "Failed connecting to global database: failed to create dqlite connection: no available dqlite leader server found"

with :journalctl -u lxd.service
I have 

lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
even if my config is 
BOOT_IMAGE=/vmlinuz-4.18.0-20-generic root=/dev/mapper/xubuntu--vg-root ro quiet splash swapaccount=1 vt.handoff=1

and i have also
lvl=eror msg="Dqlite: aborting (fd=21 state=header msg=(null))"
lvl=warn msg="Raft: Heartbeat timeout from \"\" reached, starting election"

someone would know where the issue could be?

**Comment by stgraber** [comment]
This suggests that your system currently doesn't have the IP address that you configured for your LXD daemon.

LXD on your system is configured to listen on 192.168.1.15 and the error suggests that your system currently doesn't have it. Configure that address and try starting LXD again.

**Comment by stgraber** [comment]
If your system is on dynamic addresses, a better value for core.https_address is `:8443` so that it listens on whatever address is available and won't fail if your system doesn't have the expected address.

**Comment by Axel-AMGHAR** [comment]
Hello,
thanks for the answer
i try : lxc config set core.https_address '[::]:8443'
but i don"t have any access to lxd or lxc commands
do you know an an other way to change the address

ps: it's my first time wuth lxd :)

**Comment by stgraber** [comment]
You'll need to add that IP to your system so that LXD will start again:
 - ip addr add 192.168.1.15/32 dev lo
 - systemctl restart lxd
 - lxc config set core.https_address :8443
 - ip addr del 192.168.1.15/32 dev lo

**Comment by Axel-AMGHAR** [comment]
T'y for help

**Comment by pavel1337** [comment]
> If your system is on dynamic addresses, a better value for core.https_address is `:8443` so that it listens on whatever address is available and won't fail if your system doesn't have the expected address.

Hi, I believe it's the same issue Im having here: 

The lxd network config is this: 
```
$ lxc network show lxdbr0
config:
  ipv4.address: 10.1.37.1/24
  ipv4.dhcp.ranges: 10.1.37.2-10.1.37.254
  ipv4.nat: "false"
  ipv6.address: none
```

Core http address is set to the same IP lxd should care about.
```
$ lxc config show
config:
  core.https_address: 10.1.37.1:8443
```
But after reboot we have this issue

`Mar 19 04:11:57 server lxd[903]: t=2020-03-19T04:11:57+0100 lvl=eror msg="Cannot listen on https socket, skipping..." err="listen tcp 10.1.37.1:8443: bind: cannot assign requested address"`

Is there a way to maybe wait until lxdbr0 is up and then bind to its address? Maybe via systemd somehow?

**Comment by stgraber** [comment]
there's no waiting possible as LXD itself creates that bridge so if LXD can't start, the IP will never show up

**Comment by pavel1337** [comment]
> there's no waiting possible as LXD itself creates that bridge so if LXD can't start, the IP will never show up

That is the thing, LXD starts normally, IP is up, but LXD cannot assign "core.https_address" to this address 10.1.37.1. And to make it work I have to first "lxc config unset core.https_address" and then set it again. 

Should I create a separate issue though?
