### ISSUE TITLE
Support executing as a specified user id

### ISSUE THREAD

**Issue by cyphar** [lxc/lxd#5807]
# Issue description

At the moment, `lxc exec` only supports running a command as root within the container. This is less than ideal if you want to run a command as a non-root user, since you have to install `sudo` in order to get this feature (which isn't installed by default in most container images). Docker has `docker exec -u` -- is there are particular reason that `lxc exec -u` doesn't exist? Is the concern related to parsing `/etc/passwd` to figure out usernames?

**Comment by stgraber** [comment]
Correct. We could add support for passing what UID to execute a command as, but we will not be allowing passing a name as that'd require interactions with the NSS stack in the container which opens a huge can of worms as far as security issues, dealing with non-standard Linux (Android, OpenWRT), ...

If you think that a --uid=1000 option would be useful to you, we probably can do that reasonably cheaply, but passing a username isn't something we're likely to do.

**Comment by cyphar** [comment]
I reckon that just having a `--uid 1000` option (and avoiding the fun world of usernames) would be reasonable. It might require some more hardcoding than would be ideal for admins, but at the very least you don't need to put `sudo` (or `su`) in your container to achieve the same thing -- and you could always use `getent` if you really want to use usernames.

I can cook up a patch for this.

**Comment by stgraber** [comment]
@cyphar that'd be great, thanks

**Comment by stgraber** [comment]
@cyphar had a chance to take a look at this?

**Comment by stgraber** [comment]
I'll take a quick stab at it, hopefully will be pretty straightforward

**Comment by brauner** [comment]
Closed in https://github.com/lxc/lxd/pull/5930.

**Comment by cyphar** [comment]
Thanks! Sorry for not getting around to this, I've was too busy working on https://github.com/openSUSE/libpathrs.
