### ISSUE TITLE
LXC fails to bring up networking on vivid guests

### ISSUE THREAD

**Issue by chrisglass** [lxc/lxd#581]
Launching a vivid LXC container on vivid fails to bring up networking (the container is started but the interface has no ip address).

Steps to reproduce (on a fresh vivid machine):
- apt-get install lxd lxd-client
- (apt-cache policy lxd -> Installed: 0.7-0ubuntu1)
- lxd-images import lxc ubuntu vivid amd64 --alias vivid
- lxc launch vivid vivid-image-test

What happens:
The "lxc list" command shows the container as running, but no ipv4(or ipv6) address is ever assigned to the running container.
Running a shell in the container with lxc exec shows a host name of "LXC_NAME" which looks fishy, but there is a corresponding entry in /etc/hosts so it should work (AFAICT).

What should happen:
The running container gets an IP address and can communicate on the network.

**Comment by stgraber** [comment]
The issue has been tracked down to a change in systemd-journald which uses the new multicast audit reporting capability of recent Linux kernel. Connecting to that multicast bus is restricted to real root, which is causing the journal to fail to start and in turn a bunch more units, including networking.

The issue has been reported to Martin Pitt (systemd maintainer in Ubuntu) and somebody else reported it upstream a little while ago. Hopefully this will be resolved in upstream systemd soon.

Marking the issue as blocked as a result and pushing it to a later milestone.

**Comment by stgraber** [comment]
This has been fixed in Ubuntu's systemd package and pushed as stable update to vivid.
