### ISSUE TITLE
Design and transition to new device interfaces

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#5819]
As part of cleaning up the `containerLXC` struct and converting our existing `container` interface into a cleaner `instance` interface, we need to cleanup the heap of code that is our device handling code.

For this, we should take a close look at what we need each device type to do and design a Go interface around that, this Go interface should then go into a new `devices` package with one sub-package per device type.

Due to circular import issues, we can't have those packages use the `container` interface or `containerLXC` struct making things a bit trickier, though we can work around that by passing callback functions for specific actions we need.

I suspect we'll at least want functions for:
 - Hotplug to running container
 - Hotremove from running container
 - Get container configuration snippet
 - Hook into lifecycle events (get called by LXD prior to start, from OnStart, from OnStop, ...)

We also need to keep future LXD work in mind with the `instance` rework that's coming up soon.

**Comment by stgraber** [comment]
@tomponline is drafting such an interface something you'd be interested to take a stab at?

**Comment by tomponline** [comment]
@stgraber sounds good.
