### ISSUE TITLE
Error: Unable to find quota group

### ISSUE THREAD

**Issue by ykazakov** [lxc/lxd#5842]
# Required information

 * Distribution: ubuntu
 * Distribution version: 18.04 server (fully updated)
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-51-generic
   * LXC version: 3.1.0
   * LXD version: 3.13 (snap)
   * Storage backend in use: btrfs (partition)

# Issue description

I am trying to control disk limits using a profile. When I add the profile with a quota to a container, remove it, and try to add it again, I get: `Error: Unable to find quota group`
I am trying to follow the method described here:
https://stgraber.org/2016/03/26/lxd-2-0-resource-control-412/

# Steps to reproduce

```
$ lxc profile copy default restricted
$ lxc profile device set restricted root size 20GB
$ lxc profile show restricted
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    size: 20GB
    type: disk
name: restricted
used_by: []
$ lxc launch images:alpine/3.8 c1
Creating c1
Starting c1 
$ lxc profile add c1 restricted
Profile restricted added to c1
$ lxc profile remove c1 restricted
Profile restricted removed from c1
$ lxc profile add c1 restricted
Error: Unable to find quota group
```
# Further considerations:

Setting the disk limit directly for the container as described [here](https://stgraber.org/2016/03/26/lxd-2-0-resource-control-412/), does not seem to work:

```
$ lxc launch images:alpine/3.8 c2
Creating c2
Starting c2
$ lxc config device set c2 root size 20GB
Error: The device doesn't exist
```

Further, I am not sure if the profile really sets the limit:

```
$ lxc profile add c2 restricted
Profile restricted added to c2
$ lxc exec c2 -- df -h /
Filesystem                Size      Used Available Use% Mounted on
/dev/sda2               912.4G    416.6G    493.6G  46% /
```

The manually created btrfs partition on /dev/sda2 was mounted as described in https://github.com/lxc/lxd-pkg-ubuntu/issues/28#issuecomment-309293335

**Comment by stgraber** [comment]
You're using btrfs so you won't see the limit applied in `df -h`, and it's normal that `lxc config device set` doesn't work on 3.0 and higher, use `lxc config device override c2 root size=10GB` instead.

The profile part does look like an issue and we'll need to look into that.

**Comment by stgraber** [comment]
reproduced the issue
