### ISSUE TITLE
erro in live migration on debian buster with brtfs backend 

### ISSUE THREAD

**Issue by changuoqiang** [lxc/lxd#5850]
try live migrate container from local host to remote host，two hosts have same environment

the error list below:

Error: Failed container creation:                           
 - https://[fd42:843a:d513:7bea::1]:8443: Error transferring container data: Unable to connect to: [fd42:843a:d513:7bea::1]:8443
 - https://192.168.0.16:8443: Error transferring container data: migration pre-dump failed
(00.121208) Warn  (criu/image.c:134): Failed to open parent directory
(01.206736) Error (criu/mount.c:1089): mnt: The file system 0x35 0x35 (0x60) btrfs ./var/tmp is inaccessible
(01.206745) Error (criu/fsnotify.c:215): fsnotify: Can't open mount for s_dev 35, continue
(01.206756) Error (criu/mount.c:1089): mnt: The file system 0x35 0x35 (0x60) btrfs ./tmp is inaccessible
(01.206762) Error (criu/fsnotify.c:215): fsnotify: Can't open mount for s_dev 35, continue
(01.206775) Error (criu/mount.c:1089): mnt: The file system 0x35 0x35 (0x60) btrfs ./ is inaccessible
(01.206781) Error (criu/fsnotify.c:215): fsnotify: Can't open mount for s_dev 35, continue
(01.206815) Error (criu/mount.c:1089): mnt: The file system 0x35 0x35 (0x60) btrfs ./ is inaccessible
(01.206821) Error (criu/fsnotify.c:215): fsnotify: Can't open mount for s_dev 35, continue
(01.206851) Error (criu/mount.c:1089): mnt: The file system 0x35 0x35 (0x60) btrfs ./ is inaccessible
(01.206858) Error (criu/fsnotify.c:215): fsnotify: Can't open mount for s_dev 35, continue
(01.206870) Warn  (criu/fsnotify.c:289): fsnotify: 	Handle 0x35:0xcbf cannot be opened
(01.212962) Error (criu/irmap.c:86): irmap: Can't stat /no-such-path: No such file or directory
(01.212968) Error (criu/fsnotify.c:292): fsnotify: 	Can't dump that handle
(01.212972) Error (criu/irmap.c:360): irmap: Failed to resolve 35:cbf
(01.213043) Error (criu/cr-dump.c:1543): Pre-dumping FAILED.
 - https://10.109.74.1:8443: Failed to run: btrfs subvolume create /var/snap/lxd/common/lxd/storage-pools/default/containers/pridns-backup: ERROR: target path already exists: /var/snap/lxd/common/lxd/storage-pools/default/containers/pridns-backup

apparmor enabled, what's wrong?

best regard
[migration_pre-dump_2019-06-16T20:09:50+08:00.zip](https://github.com/lxc/lxd/files/3294095/migration_pre-dump_2019-06-16T20.09.50%2B08.00.zip)

# Required information

 * Distribution: debian 
 * Distribution version: buster 
 * The output of "lxc info" or if that fails:
   * Kernel version:4.19.0-5-amd64 #1 SMP Debian 4.19.37-3
   * LXC version: 3.0.3
   * LXD version: 3.0.3
   * Storage backend in use: btrfs

**Comment by stgraber** [comment]
CRIU failed to track down some mounts during the dump stage causing the live migration to fail.
I'd recommend trying the latest CRIU version (3.12) to see if it helps, if it doesn't look for a matching issue or file a new one at https://github.com/checkpoint-restore/criu

Closing this issue as the problem appears to originate on the CRIU side.
