### ISSUE TITLE
LXD corrupted state

### ISSUE THREAD

**Issue by aovestdipaperino** [lxc/lxd#5870]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.2
 * The output of "lxc info" or if that fails:
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICFTCCAZugAwIBAgIQObcofHFzRPH/ilXqXOamQDAKBggqhkjOPQQDAzA0MRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QHNlcnZl
    cjAeFw0xOTA2MjMwMDMzMDZaFw0yOTA2MjAwMDMzMDZaMDQxHDAaBgNVBAoTE2xp
    bnV4Y29udGFpbmVycy5vcmcxFDASBgNVBAMMC3Jvb3RAc2VydmVyMHYwEAYHKoZI
    zj0CAQYFK4EEACIDYgAEcZgOF9bE98p2zI2OAawyBMD8tQuJfFYJ5uV+09rBcRXp
    3gMc5r7jdctEoxS8tb+EoPJpsxPyHWYVaOzeP9nLCaFzCuwXDTtCcSSR1eusDQ4S
    Z9vbKOKAJdq/R29DQvu7o3IwcDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYI
    KwYBBQUHAwEwDAYDVR0TAQH/BAIwADA7BgNVHREENDAyggZzZXJ2ZXKHBMCoAgKH
    BMCoAgOHBMCoAgSHBMCoAgWHBMCoAgaHBMCoAgeHBMCoAggwCgYIKoZIzj0EAwMD
    aAAwZQIwYlpJRHjJAZCts/PMgl5+mvatMkzIAtDSpLkVNkQVR13sbLMe09+BmSMK
    DPjODFwKAjEAgVNV7ZywFuUYLs3lhW8WKW/ErdhzMrvwSdLQHfZSrFt1h5msrSJX
    +rLTpo9o/Rpr
    -----END CERTIFICATE-----
  certificate_fingerprint: 63202c040c1bdc10a7b20cd7e814600f5781f1696c1a2583a6a7545bdf8b86e0
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.15.0-52-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "false"
    network_ipvlan: "false"
    network_l2proxy: "false"
    network_phys_macvlan_mtu: "false"
    seccomp_notify: "false"
  project: default
  server: lxd
  server_clustered: false
  server_name: server
  server_pid: 28838
  server_version: "3.14"
  storage: ""
  storage_version: ""

# Issue description

LXD/LXC is in a corrupt state. If remove (via apt/snap) and reinstall:

root@server:~# lxd list --debug --verbose
DBUG[06-22|19:04:10] Connecting to a local LXD over a Unix socket
DBUG[06-22|19:04:10] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
DBUG[06-22|19:04:10] Got response struct from LXD
DBUG[06-22|19:04:10]
        {
            // removed 
        }
EROR[06-22|19:04:10] Failed to start the daemon: LXD is already running
INFO[06-22|19:04:10] Starting shutdown sequence
DBUG[06-22|19:04:10] Not unmounting temporary filesystems (containers are still running)
Error: LXD is already running
If I stop the service, the command hangs:

root@server:~# service lxd stop
root@server:~# /usr/bin/lxd list --debug --verbose
DBUG[06-22|19:08:51] Connecting to a local LXD over a Unix socket
DBUG[06-22|19:08:51] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
INFO[06-22|19:08:51] LXD 3.0.3 is starting in normal mode     path=/var/lib/lxd
INFO[06-22|19:08:51] Kernel uid/gid map:
INFO[06-22|19:08:51]  - u 0 0 4294967295
INFO[06-22|19:08:51]  - g 0 0 4294967295
INFO[06-22|19:08:51] Configured LXD uid/gid map:
INFO[06-22|19:08:51]  - u 0 100000 65536
INFO[06-22|19:08:51]  - g 0 100000 65536
INFO[06-22|19:08:51] Kernel features:
INFO[06-22|19:08:51]  - netnsid-based network retrieval: no
INFO[06-22|19:08:51]  - unprivileged file capabilities: yes
INFO[06-22|19:08:51] Initializing local database
DBUG[06-22|19:08:51] Initializing database gateway
DBUG[06-22|19:08:51] Start database node                      id=1 address=
DBUG[06-22|19:08:51] Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}]
DBUG[06-22|19:08:51] Raft: Node at 0 [Leader] entering Leader state
DBUG[06-22|19:08:51] Dqlite: starting event loop
DBUG[06-22|19:08:51] Dqlite: accepting connections
DBUG[06-22|19:08:51] Connecting to a local LXD over a Unix socket
DBUG[06-22|19:08:51] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
DBUG[06-22|19:08:51] Detected stale unix socket, deleting
INFO[06-22|19:08:51] Starting /dev/lxd handler:
INFO[06-22|19:08:51]  - binding devlxd socket                 socket=/var/lib/lxd/devlxd/sock
INFO[06-22|19:08:51] REST API daemon:
INFO[06-22|19:08:51]  - binding Unix socket                   socket=/var/lib/lxd/unix.socket
INFO[06-22|19:08:51] Initializing global database
DBUG[06-22|19:08:51] Dqlite: handling new connection (fd=18)
DBUG[06-22|19:08:51] Dqlite: connected address=0 attempt=0
INFO[06-22|19:08:51] Initializing storage pools
DBUG[06-22|19:08:51] No existing storage pools detected
INFO[06-22|19:08:51] Initializing networks
DBUG[06-22|19:08:51] New task operation: babdbd98-d8b1-4e83-a526-9215e0e86329
INFO[06-22|19:08:51] Pruning leftover image files
DBUG[06-22|19:08:51] Started task operation: babdbd98-d8b1-4e83-a526-9215e0e86329
INFO[06-22|19:08:51] Done pruning leftover image files
INFO[06-22|19:08:51] Loading daemon configuration
DBUG[06-22|19:08:51] Success for task operation: babdbd98-d8b1-4e83-a526-9215e0e86329
DBUG[06-22|19:08:51] Initialized inotify with file descriptor 16
DBUG[06-22|19:08:51] New task operation: f447a57b-f4ae-4b65-8a06-47f2ba1133d2
INFO[06-22|19:08:51] Pruning expired images
DBUG[06-22|19:08:51] Started task operation: f447a57b-f4ae-4b65-8a06-47f2ba1133d2
INFO[06-22|19:08:51] Done pruning expired images
DBUG[06-22|19:08:51] Success for task operation: f447a57b-f4ae-4b65-8a06-47f2ba1133d2
DBUG[06-22|19:08:51] New task operation: 7e81e4a1-3132-42a0-b4d7-72babebbf00f
INFO[06-22|19:08:51] Updating images
DBUG[06-22|19:08:51] Started task operation: 7e81e4a1-3132-42a0-b4d7-72babebbf00f
INFO[06-22|19:08:51] Done updating images
DBUG[06-22|19:08:51] New task operation: 19a911f8-c668-4c32-8002-6aef011f49b1
INFO[06-22|19:08:51] Updating instance types
DBUG[06-22|19:08:51] Started task operation: 19a911f8-c668-4c32-8002-6aef011f49b1
INFO[06-22|19:08:51] Done updating instance types
DBUG[06-22|19:08:51] New task operation: 6419f1ea-ffe3-4bd7-846b-c8053aca906d
INFO[06-22|19:08:51] Expiring log files
DBUG[06-22|19:08:51] Started task operation: 6419f1ea-ffe3-4bd7-846b-c8053aca906d
INFO[06-22|19:08:51] Done expiring log files
DBUG[06-22|19:08:51] Success for task operation: 7e81e4a1-3132-42a0-b4d7-72babebbf00f
DBUG[06-22|19:08:51] Success for task operation: 6419f1ea-ffe3-4bd7-846b-c8053aca906d
DBUG[06-22|19:08:54] Success for task operation: 19a911f8-c668-4c32-8002-6aef011f49b1

# Steps to reproduce

I have no idea how I got into this state. The last successful operation was to delete a running container with delete --force

# Information to attach

LOG:
root@server:~# cat /var/log/lxd/lxd.log
t=2019-06-22T19:07:50-0700 lvl=info msg="LXD 3.0.3 is starting in normal mode" path=/var/lib/lxd
t=2019-06-22T19:07:50-0700 lvl=info msg="Kernel uid/gid map:"
t=2019-06-22T19:07:50-0700 lvl=info msg=" - u 0 0 4294967295"
t=2019-06-22T19:07:50-0700 lvl=info msg=" - g 0 0 4294967295"
t=2019-06-22T19:07:50-0700 lvl=info msg="Configured LXD uid/gid map:"
t=2019-06-22T19:07:50-0700 lvl=info msg=" - u 0 100000 65536"
t=2019-06-22T19:07:50-0700 lvl=info msg=" - g 0 100000 65536"
t=2019-06-22T19:07:50-0700 lvl=info msg="Kernel features:"
t=2019-06-22T19:07:50-0700 lvl=info msg=" - netnsid-based network retrieval: no"
t=2019-06-22T19:07:50-0700 lvl=info msg=" - unprivileged file capabilities: yes"
t=2019-06-22T19:07:50-0700 lvl=info msg="Initializing local database"
t=2019-06-22T19:07:53-0700 lvl=info msg="Starting /dev/lxd handler:"
t=2019-06-22T19:07:53-0700 lvl=info msg=" - binding devlxd socket" socket=/var/lib/lxd/devlxd/sock
t=2019-06-22T19:07:53-0700 lvl=info msg="REST API daemon:"
t=2019-06-22T19:07:53-0700 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/lib/lxd/unix.socket
t=2019-06-22T19:07:53-0700 lvl=info msg="Initializing global database"
t=2019-06-22T19:07:53-0700 lvl=info msg="Initializing storage pools"
t=2019-06-22T19:07:53-0700 lvl=info msg="Initializing networks"
t=2019-06-22T19:07:53-0700 lvl=info msg="Pruning leftover image files"
t=2019-06-22T19:07:53-0700 lvl=info msg="Done pruning leftover image files"
t=2019-06-22T19:07:53-0700 lvl=info msg="Loading daemon configuration"
t=2019-06-22T19:07:53-0700 lvl=info msg="Pruning expired images"
t=2019-06-22T19:07:53-0700 lvl=info msg="Done pruning expired images"
t=2019-06-22T19:07:53-0700 lvl=info msg="Updating images"
t=2019-06-22T19:07:53-0700 lvl=info msg="Done updating images"
t=2019-06-22T19:07:53-0700 lvl=info msg="Updating instance types"
t=2019-06-22T19:07:53-0700 lvl=info msg="Done updating instance types"
t=2019-06-22T19:07:53-0700 lvl=info msg="Expiring log files"
t=2019-06-22T19:07:53-0700 lvl=info msg="Done expiring log files"
t=2019-06-22T19:08:29-0700 lvl=info msg="Asked to shutdown by API, shutting down containers"
t=2019-06-22T19:08:29-0700 lvl=info msg="Starting shutdown sequence"
t=2019-06-22T19:08:29-0700 lvl=info msg="Stopping REST API handler:"
t=2019-06-22T19:08:29-0700 lvl=info msg=" - closing socket" socket=/var/lib/lxd/unix.socket
t=2019-06-22T19:08:29-0700 lvl=info msg="Stopping /dev/lxd handler"
t=2019-06-22T19:08:29-0700 lvl=info msg=" - closing socket" socket=/var/lib/lxd/devlxd/sock
t=2019-06-22T19:08:29-0700 lvl=info msg="Closing the database"
t=2019-06-22T19:08:29-0700 lvl=info msg="Stopping REST API handler:"
t=2019-06-22T19:08:29-0700 lvl=info msg="Stopping /dev/lxd handler"
t=2019-06-22T19:08:29-0700 lvl=info msg="Stopping REST API handler:"
t=2019-06-22T19:08:29-0700 lvl=info msg="Stopping /dev/lxd handler"
t=2019-06-22T19:08:29-0700 lvl=info msg="Unmounting temporary filesystems"
t=2019-06-22T19:08:29-0700 lvl=info msg="Done unmounting temporary filesystems"
t=2019-06-22T19:08:29-0700 lvl=info msg="Saving simplestreams cache"
t=2019-06-22T19:08:29-0700 lvl=info msg="Saved simplestreams cache"
t=2019-06-22T19:08:36-0700 lvl=info msg="LXD 3.0.3 is starting in normal mode" path=/var/lib/lxd
t=2019-06-22T19:08:36-0700 lvl=info msg="Kernel uid/gid map:"
t=2019-06-22T19:08:36-0700 lvl=info msg=" - u 0 0 4294967295"
t=2019-06-22T19:08:36-0700 lvl=info msg=" - g 0 0 4294967295"
t=2019-06-22T19:08:36-0700 lvl=info msg="Configured LXD uid/gid map:"
t=2019-06-22T19:08:36-0700 lvl=info msg=" - u 0 100000 65536"
t=2019-06-22T19:08:36-0700 lvl=info msg=" - g 0 100000 65536"
t=2019-06-22T19:08:36-0700 lvl=info msg="Kernel features:"
t=2019-06-22T19:08:36-0700 lvl=info msg=" - netnsid-based network retrieval: no"
t=2019-06-22T19:08:36-0700 lvl=info msg=" - unprivileged file capabilities: yes"
t=2019-06-22T19:08:36-0700 lvl=info msg="Initializing local database"
t=2019-06-22T19:08:36-0700 lvl=info msg="Starting /dev/lxd handler:"
t=2019-06-22T19:08:36-0700 lvl=info msg=" - binding devlxd socket" socket=/var/lib/lxd/devlxd/sock
t=2019-06-22T19:08:36-0700 lvl=info msg="REST API daemon:"
t=2019-06-22T19:08:36-0700 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/lib/lxd/unix.socket
t=2019-06-22T19:08:36-0700 lvl=info msg="Initializing global database"
t=2019-06-22T19:08:36-0700 lvl=info msg="Initializing storage pools"
t=2019-06-22T19:08:36-0700 lvl=info msg="Initializing networks"
t=2019-06-22T19:08:36-0700 lvl=info msg="Pruning leftover image files"
t=2019-06-22T19:08:36-0700 lvl=info msg="Done pruning leftover image files"
t=2019-06-22T19:08:36-0700 lvl=info msg="Loading daemon configuration"
t=2019-06-22T19:08:36-0700 lvl=info msg="Pruning expired images"
t=2019-06-22T19:08:36-0700 lvl=info msg="Done pruning expired images"
t=2019-06-22T19:08:36-0700 lvl=info msg="Updating instance types"
t=2019-06-22T19:08:36-0700 lvl=info msg="Done updating instance types"
t=2019-06-22T19:08:36-0700 lvl=info msg="Updating images"
t=2019-06-22T19:08:36-0700 lvl=info msg="Done updating images"
t=2019-06-22T19:08:36-0700 lvl=info msg="Expiring log files"
t=2019-06-22T19:08:36-0700 lvl=info msg="Done expiring log files"
t=2019-06-22T19:08:49-0700 lvl=info msg="Asked to shutdown by API, shutting down containers"
t=2019-06-22T19:08:49-0700 lvl=info msg="Starting shutdown sequence"
t=2019-06-22T19:08:49-0700 lvl=info msg="Stopping REST API handler:"
t=2019-06-22T19:08:49-0700 lvl=info msg=" - closing socket" socket=/var/lib/lxd/unix.socket
t=2019-06-22T19:08:49-0700 lvl=info msg="Stopping /dev/lxd handler"
t=2019-06-22T19:08:49-0700 lvl=info msg=" - closing socket" socket=/var/lib/lxd/devlxd/sock
t=2019-06-22T19:08:49-0700 lvl=info msg="Closing the database"
t=2019-06-22T19:08:49-0700 lvl=info msg="Stopping REST API handler:"
t=2019-06-22T19:08:49-0700 lvl=info msg="Stopping /dev/lxd handler"
t=2019-06-22T19:08:49-0700 lvl=info msg="Stopping REST API handler:"
t=2019-06-22T19:08:49-0700 lvl=info msg="Stopping /dev/lxd handler"
t=2019-06-22T19:08:49-0700 lvl=info msg="Unmounting temporary filesystems"
t=2019-06-22T19:08:49-0700 lvl=info msg="Done unmounting temporary filesystems"
t=2019-06-22T19:08:49-0700 lvl=info msg="Saving simplestreams cache"
t=2019-06-22T19:08:49-0700 lvl=info msg="Saved simplestreams cache"

**Comment by stgraber** [comment]
Pretty sure you want to run `lxc list`, not `lxd list`.

`lxd list` causes the snap to attempt to start a second instance of the daemon which then fails as there's one running already.

**Comment by aovestdipaperino** [comment]
Ah. Thanks. 
The root problem is that it seems I am unable to create a new container. 
If I stop the service (I guess this should be the state right?) and I try it still hangs:

root@server:~/bfts# lxd launch Ubuntu:16.04 newcontainer --debug --verbose
INFO[06-23|11:30:19] LXD 3.0.3 is starting in normal mode     path=/var/lib/lxd
INFO[06-23|11:30:19] Kernel uid/gid map: 
INFO[06-23|11:30:19]  - u 0 0 4294967295 
INFO[06-23|11:30:19]  - g 0 0 4294967295 
INFO[06-23|11:30:19] Configured LXD uid/gid map: 
INFO[06-23|11:30:19]  - u 0 100000 65536 
INFO[06-23|11:30:19]  - g 0 100000 65536 
INFO[06-23|11:30:19] Kernel features: 
INFO[06-23|11:30:19]  - netnsid-based network retrieval: no 
INFO[06-23|11:30:19]  - unprivileged file capabilities: yes 
INFO[06-23|11:30:19] Initializing local database 
DBUG[06-23|11:30:19] Initializing database gateway 
DBUG[06-23|11:30:19] Start database node                      id=1 address=
DBUG[06-23|11:30:19] Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}] 
DBUG[06-23|11:30:19] Raft: Node at 0 [Leader] entering Leader state 
DBUG[06-23|11:30:19] Dqlite: starting event loop 
DBUG[06-23|11:30:19] Dqlite: accepting connections 
INFO[06-23|11:30:19] Starting /dev/lxd handler: 
INFO[06-23|11:30:19]  - binding devlxd socket                 socket=/var/lib/lxd/devlxd/sock
INFO[06-23|11:30:19] REST API daemon: 
INFO[06-23|11:30:19]  - binding Unix socket                   socket=/var/lib/lxd/unix.socket
INFO[06-23|11:30:19] Initializing global database 
DBUG[06-23|11:30:19] Dqlite: handling new connection (fd=18) 
DBUG[06-23|11:30:19] Dqlite: connected address=0 attempt=0 
INFO[06-23|11:30:19] Initializing storage pools 
DBUG[06-23|11:30:19] No existing storage pools detected 
INFO[06-23|11:30:19] Initializing networks 
DBUG[06-23|11:30:19] New task operation: c2185da7-e466-4373-9aa1-2c6fa05bb214 
INFO[06-23|11:30:19] Pruning leftover image files 
DBUG[06-23|11:30:19] Started task operation: c2185da7-e466-4373-9aa1-2c6fa05bb214 
INFO[06-23|11:30:19] Done pruning leftover image files 
INFO[06-23|11:30:19] Loading daemon configuration 
DBUG[06-23|11:30:19] Success for task operation: c2185da7-e466-4373-9aa1-2c6fa05bb214 
DBUG[06-23|11:30:19] Initialized inotify with file descriptor 17 
DBUG[06-23|11:30:19] New task operation: 9804a8c6-6b7e-4951-8696-d9d8d3a83a75 
INFO[06-23|11:30:19] Pruning expired images 
DBUG[06-23|11:30:19] Started task operation: 9804a8c6-6b7e-4951-8696-d9d8d3a83a75 
INFO[06-23|11:30:19] Done pruning expired images 
DBUG[06-23|11:30:19] Success for task operation: 9804a8c6-6b7e-4951-8696-d9d8d3a83a75 
DBUG[06-23|11:30:19] New task operation: 15d5d2fc-2e0f-4197-b7e8-dff12abfea8b 
INFO[06-23|11:30:19] Updating images 
DBUG[06-23|11:30:19] Started task operation: 15d5d2fc-2e0f-4197-b7e8-dff12abfea8b 
INFO[06-23|11:30:19] Done updating images 
DBUG[06-23|11:30:19] New task operation: 8b74dad2-31b1-460d-a806-0c872738312f 
INFO[06-23|11:30:19] Expiring log files 
DBUG[06-23|11:30:19] Started task operation: 8b74dad2-31b1-460d-a806-0c872738312f 
INFO[06-23|11:30:19] Done expiring log files 
DBUG[06-23|11:30:19] Success for task operation: 15d5d2fc-2e0f-4197-b7e8-dff12abfea8b 
DBUG[06-23|11:30:19] New task operation: a5a17322-69e4-4dcb-9b35-629183e6d5db 
INFO[06-23|11:30:19] Updating instance types 
DBUG[06-23|11:30:19] Started task operation: a5a17322-69e4-4dcb-9b35-629183e6d5db 
INFO[06-23|11:30:19] Done updating instance types 
DBUG[06-23|11:30:19] Success for task operation: 8b74dad2-31b1-460d-a806-0c872738312f 
DBUG[06-23|11:30:23] Success for task operation: a5a17322-69e4-4dcb-9b35-629183e6d5db

**Comment by aovestdipaperino** [comment]
If I try to create the new container while LXD service is running, it fails because "LXD is already running"
I am still puzzled to what should be the normal state of the LXD service, as "lxd init" won't run if the service is stopped.

**Comment by stgraber** [comment]
Same issue, it's 'lxc launch' not 'lxd launch'.

**Comment by aovestdipaperino** [comment]
*facepalm*

**Comment by aovestdipaperino** [comment]
I was thinking a bit, but I see that lxd list or launch should cause an error instead of launching the daemon.
This would be an actionable task. What do you think? I can open a separate issue to track it.

**Comment by stgraber** [comment]
Yeah, that should be returning an error. We can use this issue for that.

**Comment by aovestdipaperino** [comment]
I opened a new, more relevant one:
https://github.com/lxc/lxd/issues/5876
