### ISSUE TITLE
LXD 3.14 : Package requirements (raft) were not met

### ISSUE THREAD

**Issue by cyberwillis** [lxc/lxd#5875]
# Required information

 * Distribution: Ubuntu
 * Distribution version: **16.04 LTS**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.4.0-151-lowlatency**
   * LXC version: **3.1.0 (devel)**
   * LXD version: **3.14**
   * Storage backend in use: **zfs**

# Issue description

during the make deps procedure the following message bellow appear, I am not familiar how can I solve this raft problem, I need to build raft or if I need to move some folders arround:

```
...
checking for RAFT... no
configure: error: Package requirements (raft) were not met:

No package 'raft' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables RAFT_CFLAGS
and RAFT_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Makefile:35: recipe for target 'deps' failed
make: *** [deps] Error 1
```

# Steps to reproduce

 1. make update
 2. make deps

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by freeekanayaka** [comment]
This should get fixed for master once #5872 is merged. For 3.14 you have to use dqlite v0.3.0. Probably we'll want to release a bug fix against the make deps target of 3.14 that pulls v0.3.0 instead of master. @stgraber thoughts?

**Comment by stgraber** [comment]
@freeekanayaka our release tarballs include the old dqlite/sqlite trees inside dist/, building those rather than the new code that's downloaded by `make deps` should work fine.

**Comment by stgraber** [comment]
But yeah, if not building using `dist/`, then modifying Makefile to grab `v0.3.0` should do.

@cyberwillis locally applying this should work to build 3.14 without using the code trees from dist/.

```diff
diff --git a/Makefile b/Makefile
index 99f2aa6ba..4563af44f 100644
--- a/Makefile
+++ b/Makefile
@@ -55,6 +55,7 @@ deps:
        fi
 
        cd "$(GOPATH)/deps/dqlite" && \
+               git checkout v0.3.0 && \
                autoreconf -i && \
                PKG_CONFIG_PATH="$(GOPATH)/deps/sqlite/" ./configure && \
                make CFLAGS="-I$(GOPATH)/deps/sqlite/" LDFLAGS="-L$(GOPATH)/deps/sqlite/.libs/"
```

**Comment by cyberwillis** [comment]
thank you all, it worked nice

**Comment by fcolista** [comment]
LXD 3.15 seems to be still affected with this problem:
```
checking for RAFT... no
configure: error: Package requirements (raft) were not met:

Package 'raft', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables RAFT_CFLAGS
and RAFT_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
And I've patched the Makefile as follows:

```
diff --git a/Makefile b/Makefile
index 45d6749..17b4113 100644
--- a/Makefile
+++ b/Makefile
@@ -77,6 +77,7 @@ deps:
 	fi
 
 	cd "$(GOPATH)/deps/dqlite" && \
+		git checkout v0.3.0 && \
 		autoreconf -i && \
 		PKG_CONFIG_PATH="$(GOPATH)/deps/sqlite/:$(GOPATH)/deps/libco/:$(GOPATH)/deps/raft/" ./configure && \
 		make CFLAGS="-I$(GOPATH)/deps/sqlite/ -I$(GOPATH)/deps/libco/ -I$(GOPATH)/deps/raft/include/" LDFLAGS="-L$(GOPATH)/deps/sqlite/.libs/ -L$(GOPATH)/deps/libco/ -L$(GOPATH)/deps/raft/.libs/"
```
This happens on Alpine Linux as well as Arch Linux.
With and without this patch, LXD does not build.

**Comment by freeekanayaka** [comment]
See https://github.com/lxc/lxd/issues/5964#issuecomment-511714953.
