### ISSUE TITLE
Properly tie nic devices to LXD networks

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#5890]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: N/A
   * LXC version: N/A
   * LXD version: b7ac0c8e07dac4e998e38de696f613596f56b60c
   * Storage backend in use: N/A

# Issue description

Currently you can set a NIC device's `ipv6.address` property even when a container is connected to a managed network that is in SLAAC mode. This means that the static IP will never take effect as it requires `ipv6.dhcp.stateful` to be enabled.

Perhaps we should reject this or issue a warning?

**Comment by stgraber** [comment]
So I wouldn't do it with the current state of things.

I think what we need down the line is something similar to `pool` for storage, probably a `network` key on `nic` devices which then refers to a LXD managed network (bridge or OVN overlay), when that nic and network are tied together, then we can do smarter checks based on the features used on either side.

That would also make it easier to restrict some users to only using LXD managed networks (effectively banning the `parent` key) and avoid us breaking users by introducing new validation around some of those keys.

**Comment by stgraber** [comment]
I suspect this will all end up getting tied to #3440 and putting networks inside projects next cycle.
