### ISSUE TITLE
DHCPv6 can end up with multiple IPs allocated to same container

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#5891]
Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: N/A
   * LXC version: N/A
   * LXD version: b7ac0c8e07dac4e998e38de696f613596f56b60c
   * Storage backend in use: N/A

# Issue description

When changing the `ipv6.address` property on a container's NIC when connected to a managed bridged network, the old value is removed from the host config file `/var/lib/lxd/networks/<network name>/dnsmasq.hosts/<container name>` however if the container is running there is also an active lease for the old IP in `/var/lib/lxd/networks/<network name>/dnsmasq.leases` which is not removed.

This can result in multiple active IPs assigned to the container whilst the old leases are active. Is this desired behaviour?

# Steps to reproduce

 1. Step one
Ensure network DHCPv6 stateful mode enabled:
`lxc network set lxdbr0 ipv6.dhcp.stateful true`
 2. Step two
Create a container with initial staitc IP:
```
lxc init ubuntu:18.04 c1
lxc config device add c1 eth0 nic nictype=bridged parent=lxdbr0 name=eth0 ipv6.address=fd42:817e:4173:7aa3::2
lxc start c1
```
 3. Step three
Change IP
```
lxc config device set c1 eth0 ipv6.address fd42:817e:4173:7aa3::3
```
4. Step four
Two leases active:
```
sudo cat /var/lib/lxd/networks/<network name>/dnsmasq.leases
```

**Comment by stgraber** [comment]
Hopefully not a very hard one to fix, though we'll still have that annoyance that we can't very reliably tie a lease to a container mac for IPv6.

**Comment by tomponline** [comment]
@stgraber I figured I would use the outgoing static IP configured and search for that in leases and then generate a release packet for that based on the details, which sidesteps that dnsmasq IPv6 issue (at least for a static IP changing to another static IP) - the issue still exists potentially for when a stateful lease changes to a static allocation, in which case could just search by container name. Not particularly reliable, as you say though.
