### ISSUE TITLE
Invalid tty ownership leads to Operation not permitted on ioctl

### ISSUE THREAD

**Issue by kenokabe** [lxc/lxd#590]
The host is Ubuntu14.04

```
sudo apt install lxd
newgrp lxd
lxc remote add images images.linuxcontainers.org
lxc launch images:ubuntu/trusty/amd64 ubuntu

lxc exec ubuntu /bin/bash

root@ubuntu:~# adduser ken
.........
gpasswd -a ken sudo

root@ubuntu:~# login ken
Password: 
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-36-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

Unable to change owner or mode of tty stdin: Operation not permitted
```
 
>Unable to change owner or mode of tty stdin: Operation not permitted

Can anyone tell what I miss?

**Comment by sl1pm4t** [comment]
I can reproduce this problem, but I don't know what the fix is.
As a workaround try the following instead, which works for me:
```
root@ubuntu:~# su - ken
ken@ubuntu:~$ 
```

**Comment by kenokabe** [comment]
Thanks a lot!

**Comment by tych0** [comment]
On Tue, May 05, 2015 at 06:08:54PM -0700, Ken OKABE wrote:
> The host is Ubuntu14.04
> 
> ```
> sudo apt install lxd
> newgrp lxd
> lxc remote add images images.linuxcontainers.org
> lxc launch images:ubuntu/trusty/amd64 ubuntu
> 
> lxc exec ubuntu /bin/bash
> 
> root@ubuntu:~# adduser ken
> .........
> root@ubuntu:~# login ken
> Password: 
> Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-36-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com/
> 
> The programs included with the Ubuntu system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
> applicable law.
> 
> Unable to change owner or mode of tty stdin: Operation not permitted
> ```
>  
> >Unable to change owner or mode of tty stdin: Operation not permitted
> 
> Can anyone tell what I miss?

I assume this has to do with the fact that the tty is set up by lxd
(root) and the process is running as a user. The pty/tty code is
fairly gory but lives in /shared/util.go, if you're interested in
looking into a patch. It may be that all it needs is a few well placed
grantpt(3) calls (perhaps in liblxc?)

**Comment by hallyn** [comment]
Yup, the EPERM comes from an attempt to fchown stdin which is a devpts from the host, and owned by a uid (presumably root) not valid in the container's namespace.  It needs to be chowned to container root.
