### ISSUE TITLE
Wrong memory usage in monit with latest versions of monit (and lxd)

### ISSUE THREAD

**Issue by harolds** [lxc/lxd#5905]
We are running monit to monitor all our servers and services. On some virtual hosts monit reports wrong memory usage:

Monit 5.25.2 uptime: 16h 6m

System 'kwp-php5-01'
  status                       OK
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  load average                 [1.24] [1.02] [0.66]
  cpu                          12.2%us 1.4%sy 0.0%wa
  memory usage                 **16 EB [115292151808.0%]**
  swap usage                   88.8 MB [2.2%]
  uptime                       43d 18h 27m
  boot time                    Sun, 19 May 2019 14:49:52
  data collected               Tue, 02 Jul 2019 09:15:42

I checked with the latest version (monit 5.25.3) and that still has the same issue.

But when I use an older version of monit everything is correct:

The Monit daemon 5.16 uptime: 0m

System 'localhost'
  status                            Running
  monitoring status                 Monitored
  load average                      [0.53] [0.55] [0.63]
  cpu                               0.0%us 0.0%sy 0.0%wa
  memory usage                      909.8 MB [6.0%]
  swap usage                        88.2 MB [2.2%]
  data collected                    Tue, 02 Jul 2019 09:27:35

Versions of all involved services:
Ubuntu: 17.10
LXD: 3.14

So for me this not urgent as I can still use the 5.16 version. If this is an issue that the monit team should fix I like to here it too so I can inform them about it.

**Comment by lhorace** [comment]
Hello there,

Shouldn't this be reported again monit? Is LXD misreporting memory usage? How is monit greping for that information, via web API or command line tools? If it's API, perhaps this is the proper place, if it's the latter, than verify the memory usage with command line tools.

Cheers

**Comment by stgraber** [comment]
This feels like either a monit issue or possibly more likely a lxcfs issue, but we'd need to know exactly what monit accesses to know what may be wrong.

Can you paste your `/proc/meminfo` from inside the container?
With a bit of luck there's something obviously wrong there which can be fixed in lxcfs.

Closing the issue on the LXD side as unless monitor is talking to our API (and it's not as far as I know) then this isn't an issue with any of the LXD code but more likely with lxcfs, kernel or monit itself.

**Comment by stgraber** [comment]
(The issue being closed doesn't mean we won't respond to it, just that there isn't anything actionable for us to fix in LXD, we're still interested in tracking this down)

**Comment by harolds** [comment]
Here the meminfo:

MemTotal:       15625000 kB
MemFree:        15078248 kB
MemAvailable:   15249160 kB
Buffers:               0 kB
Cached:           170912 kB
SwapCached:            0 kB
Active:           406480 kB
Inactive:          67396 kB
Active(anon):     303624 kB
Inactive(anon):    26432 kB
Active(file):     102856 kB
Inactive(file):    40964 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      20967416 kB
SwapFree:       20967416 kB
Dirty:               212 kB
Writeback:             0 kB
AnonPages:      13309148 kB
Mapped:          1403232 kB
Shmem:             27092 kB
Slab:               0 kB
SReclaimable:          0 kB
SUnreclaim:            0 kB
KernelStack:       46048 kB
PageTables:       271412 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    86924292 kB
Committed_AS:   33012260 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:      4096 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:     2451924 kB
DirectMap2M:    26791936 kB
DirectMap1G:    106954752 kB

**Comment by lhorace** [comment]
And how Monit is grepiing? Have you made an effort to figure that out?

**Comment by harolds** [comment]
I'm not going to try to figure out how monit works. I don't think that the source code is open.

**Comment by harolds** [comment]
I will create an issue with them too

**Comment by stgraber** [comment]
I'm not seeing anything obviously wrong in your meminfo. The behavior could have made sense if one of the top 5 fields were reporting very odd values (negative or memfree being bigger than memtotal) but that's not the case.

**Comment by lhorace** [comment]
> I will create an issue with them too
I want to follow the ticket, can please update this issue with the ticket number

**Comment by loxK** [comment]
Here is what monit developer says: https://bitbucket.org/tildeslash/monit/issues/385/used-memory-size-detection#comment-28251649

I have a container with: `limits.memory: 2GB`

Here is the output **from the container**:
```
# cat /proc/meminfo
MemTotal:        1953124 kB
MemFree:         1549084 kB
MemAvailable:    1633564 kB
Buffers:               0 kB
Cached:            84480 kB
SwapCached:            0 kB
Active:           197852 kB
Inactive:         149944 kB
Active(anon):     139984 kB
Inactive(anon):   131192 kB
Active(file):      57868 kB
Inactive(file):    18752 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       4194300 kB
SwapFree:        3981564 kB
Dirty:                72 kB
Writeback:            44 kB
AnonPages:       8275716 kB
Mapped:           315932 kB
Shmem:              7860 kB
Slab:               0 kB
SReclaimable:          0 kB
SUnreclaim:            0 kB
KernelStack:       13744 kB
PageTables:        52548 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    12244568 kB
Committed_AS:   13302360 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:    540672 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:     7393556 kB
DirectMap2M:     9056256 kB
DirectMap1G:     2097152 kB
```
