### ISSUE TITLE
How to port-forwarding for such as web-server?

### ISSUE THREAD

**Issue by kenokabe** [lxc/lxd#591]
I'd like to build some web-server within a lxd container.
Obviously, I need to forward the port 80 to 80.

How could we achieve this? Thanks.

PS.

I have the following with one lxd container running:

$ ifconfig

lxcbr0 Link encap:Ethernet HWaddr fe:f5:31:0c:4e:5d
inet addr:10.0.3.1 Bcast:0.0.0.0 Mask:255.255.255.0 inet6 addr: fe80::f44f:9bff:fe8a:c309/64 Scope:Link UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1 RX packets:23 errors:0 dropped:0 overruns:0 frame:0 TX packets:64 errors:0 dropped:0 overruns:0 carrier:0 collisions:0 txqueuelen:0 RX bytes:1768 (1.7 KB) TX bytes:9789 (9.7 KB)

veth2V2GC2 Link encap:Ethernet HWaddr fe:f5:31:0c:4e:5d
inet6 addr: fe80::fcf5:31ff:fe0c:4e5d/64 Scope:Link UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1 RX packets:23 errors:0 dropped:0 overruns:0 frame:0 TX packets:34 errors:0 dropped:0 overruns:0 carrier:0 collisions:0 txqueuelen:1000 RX bytes:2090 (2.0 KB) TX bytes:5251 (5.2 KB)

// and others

I suppose I need to bind lxcbr0: this should be lxd network bridge hub- 10.0.3.1 and veth2V2GC2 : the container network interface.

Am I correct and can anyone show me the way? Thanks.

**Comment by kenokabe** [comment]
I will use nginx.

**Comment by hallyn** [comment]
This has been closed, but to give a clear answer: lxd (at least as
currently intended) will not do host networking.  So in general
you would port-forward to a web-server in a lxd container the same
way you would do with lxc - you can pass in a nic from the host
into the container and have your local router provide it its own
address;  or use route-based networking to container veths;  or
use iptables forwarding to forward host traffic into the container
(which is what I usually do).

See https://help.ubuntu.com/lts/serverguide/lxc.html#lxc-network
for more information.

**Comment by techtonik** [comment]
@hallyn it would be nice if LXD exposed some user level control over port forwarding instead of leaving users with messing with their network settings without any means of control.

```
 iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 587 -j DNAT \
 	--to-destination 10.0.3.100:587
 ```
This helps, but it is kind of cryptic, and there is no guarantee that this rule will be purged once container is removed.

**Comment by tomposmiko** [comment]
+1 for a functionality, that is similar to docker-proxy

**Comment by techtonik** [comment]
Let's see if LXD can be patched to provide such functionality. I borrow forward setting from Vagrant, which is:

    config.vm.network "forwarded_port", guest: 80, host: 8080

Now I need to see where is the place for it in [LXD config](https://github.com/lxc/lxd/blob/master/specs/configuration.md#keyvalue-configuration-1). Looks like LXD config doesn't support arrays, so this looks impossible:

```
config:
  network.forwarded_port:
    guest: 80
    host: 8080
  network.forwarded_port:
    guest: 22
    host: 2222
```

Now we need to see where in LXD where is a place that can:

* [ ] add iptables route when
  * [ ] container with that config is started
  * [ ] container config is updated
  * [ ] dependent variable (ip address) is changed
* [ ] remove iptables route when
  * [ ] container is stopped
  * [ ] container config is updated
  * [ ] dependent variable (ip address) is changed

It will also be nice if LXD could somehow detect its own `iptables` routes and purges them (with obligatory warning) in case somebody decides to manually add/remove containers.

**Comment by tomposmiko** [comment]
There is a case that need to be handled. What happens if a container is migrated and the port on the destination is in use?

**Comment by techtonik** [comment]
* [ ] fail // disable // propose alternative // autoincrement port if
  * [ ] container is going to be created and the port is in use

This will require additional `network.forwarded_port.strategy` variable to choose desired behavior. Maybe even `network.forward_strategy` for the start.

**Comment by JustinJudd** [comment]
I wrote a tool that can monitor LXD and make changes to IPTable rules as containers come up or down. [https://github.com/JustinJudd/lxd-port-forward](https://github.com/JustinJudd/lxd-port-forward)

I really love the `lxd teleport` idea to be able to make these changes on lxd remotes and not having to ssh over. In the meantime, I have added daemon and systemd support so it should be really easy to just throw onto an LXD host and add a configuration file and let it go.

**Comment by zipizap** [comment]
Just in case anyone comes here, there is now a feature in LXD to manage port-forwarding between host and containers (added this year, a few months ago - device proxy)

**Comment by techtonik** [comment]
Yes, to access web app running on port 9090 inside of container you can do:

    lxc config device add c1 proxy0 listen=tcp:127.0.0.1:80 connect=tcp:127.0.0.1:9090

Then http://127.0.0.1 will open it. But that will only work when working on a host itself.
