### ISSUE TITLE
LXD master: can't compile because raft.h missing

### ISSUE THREAD

**Issue by hujiko** [lxc/lxd#5915]
# Required information

 * Distribution: Arch Linux
 * Distribution version: 5.1.15-arch1-1-ARCH
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.1.15-arch1-1-ARCH
   * LXC version:
   * LXD version: latest master: 60a99fb4bbdd6799d1088661effdbbe555f8ac92
   * Storage backend in use: ZFS

# Issue description

Installation of latest master branch does not succeed because of

```
Parsing meta tags from https://gopkg.in/juju/environschema.v1?go-get=1 (status code 200)
get "gopkg.in/juju/environschema.v1": found meta tag get.metaImport{Prefix:"gopkg.in/juju/environschema.v1", VCS:"git", RepoRoot:"https://gopkg.in/juju/environschema.v1"} at https://gopkg.in/juju/environschema.v1?go-get=1
github.com/gosexy/gettext (download)
github.com/mpvl/subtest (download)
github.com/juju/httprequest (download)
CC=cc go install -v -tags "libsqlite3"  ./...
github.com/CanonicalLtd/go-dqlite/internal/bindings
# github.com/CanonicalLtd/go-dqlite/internal/bindings
../../CanonicalLtd/go-dqlite/internal/bindings/server.go:9:10: fatal error: raft.h: No such file or directory
    9 | #include <raft.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:19: default] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: lxd
```

# Steps to reproduce

 1. Start the installation of lxd `yay -S lxd ----editmenu`
 2. If asked to edit PKGFILE say yes
 3. In Line 61 change `git checkout lxd-${pkgver}` to `git checkout master` (To include the bugfix from #5875 )

# Information to attach

I figured out, that `/home/myuser/.cache/yay/lxd/src/go/deps/raft/include/raft.h` actually exists.
That path also is present in `CGO_CFLAGS`

```
echo $CGO_CFLAGS
-I/home/myuser/.cache/yay/lxd/src/go/deps/sqlite/ -I/home/myuser/.cache/yay/lxd/src/go/deps/libco/ -I/home/myuser/.cache/yay/lxd/src/go/deps/raft/include/ -I/home/myuser/.cache/yay/lxd/src/go/deps/dqlite/include/
```

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
You need to wipe your go/deps directory and run 'make deps' and follow the instructions at the end of it.

This will pull the needed dependencies including libraft
