### ISSUE TITLE
/var/lib/lxd/unix.socket: permission denied

### ISSUE THREAD

**Issue by brunetto** [lxc/lxd#593]
Hi!
I'm trying LXD following [this](https://linuxcontainers.org/lxd/getting-started-cli/).

Unfortunately 

```
lxd-images import lxc ubuntu trusty amd64 --alias ubuntu
```

returns 

```
$ lxd-images import lxc ubuntu trusty amd64 --alias ubuntu
Downloading the GPG key for https://images.linuxcontainers.org
Downloading the image list for https://images.linuxcontainers.org
Validating the GPG signature of /tmp/tmpuaa_p3pi/index.json.asc
Downloading the image: https://images.linuxcontainers.org/images/ubuntu/trusty/amd64/default/20150506_03:49/lxd.tar.xz
Validating the GPG signature of /tmp/tmpuaa_p3pi/ubuntu-trusty-amd64-default-20150506_03:49.tar.xz.asc
Traceback (most recent call last):
  File "/usr/bin/lxd-images", line 410, in <module>
    args.func(parser, args)
  File "/usr/bin/lxd-images", line 361, in import_lxc
    if fingerprint in lxd.images_list():
  File "/usr/bin/lxd-images", line 99, in images_list
    status, data = self.rest_call("/1.0/images")
  File "/usr/bin/lxd-images", line 70, in rest_call
    self.lxd.request(method, path, data)
  File "/usr/lib/python3.4/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 841, in send
    self.connect()
  File "/usr/bin/lxd-images", line 55, in connect
    sock.connect(self.path)
PermissionError: [Errno 13] Permission denied
```

I tried also 

```
$ lxd
error: remove /var/lib/lxd/unix.socket: permission denied
```

and 

```
$ lxc list
error: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: permission denied
```

found here in the other issues (but not in the lxc command help?).

It seems, however, running:

```
$ sudo service lxd status
lxd start/running, process 24969
```

I also have Docker and LXC (following [this](https://www.stgraber.org/2013/12/20/lxc-1-0-your-first-ubuntu-container/)) installed for comparison, maybe they conflict?

**Comment by tych0** [comment]
Hello,

On Wed, May 06, 2015 at 07:16:01AM -0700, brunetto wrote:
> Hi!
> I'm trying LXD following [this](https://linuxcontainers.org/lxd/getting-started-cli/).
>
> Unfortunately 
> 
> ```
> lxd-images import lxc ubuntu trusty amd64 --alias ubuntu
> ```
> 
> returns 
> 
> ```
> $ lxd-images import lxc ubuntu trusty amd64 --alias ubuntu
> Downloading the GPG key for https://images.linuxcontainers.org
> Downloading the image list for https://images.linuxcontainers.org
> Validating the GPG signature of /tmp/tmpuaa_p3pi/index.json.asc
> Downloading the image: https://images.linuxcontainers.org/images/ubuntu/trusty/amd64/default/20150506_03:49/lxd.tar.xz
> Validating the GPG signature of /tmp/tmpuaa_p3pi/ubuntu-trusty-amd64-default-20150506_03:49.tar.xz.asc
> Traceback (most recent call last):
>   File "/usr/bin/lxd-images", line 410, in <module>
>     args.func(parser, args)
>   File "/usr/bin/lxd-images", line 361, in import_lxc
>     if fingerprint in lxd.images_list():
>   File "/usr/bin/lxd-images", line 99, in images_list
>     status, data = self.rest_call("/1.0/images")
>   File "/usr/bin/lxd-images", line 70, in rest_call
>     self.lxd.request(method, path, data)
>   File "/usr/lib/python3.4/http/client.py", line 1065, in request
>     self._send_request(method, url, body, headers)
>   File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
>     self.endheaders(body)
>   File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.4/http/client.py", line 841, in send
>     self.connect()
>   File "/usr/bin/lxd-images", line 55, in connect
>     sock.connect(self.path)
> PermissionError: [Errno 13] Permission denied
> ```

Did you re-open a session or do 'newgrp'?

**Comment by brunetto** [comment]
No, the only things I did (for LXD) are :+1: 
```
$ sudo add-apt-repository ppa:ubuntu-lxc/lxd-git-master
$ sudo  apt-get update
$ sudo apt-get install lxd
$ lxd-images import lxc ubuntu trusty amd64 --alias ubuntu
```

**Comment by tych0** [comment]
On Wed, May 06, 2015 at 07:25:00AM -0700, brunetto wrote:
> No, the only things I did (for LXD) are :+1: 
> ```
> $ sudo add-apt-repository ppa:ubuntu-lxc/lxd-git-master
> $ sudo  apt-get update
> $ sudo apt-get install lxd
> $ lxd-images import lxc ubuntu trusty amd64 --alias ubuntu
> ```

Right. As the guide points out, you need to run 'newgrp' or relogin to
get membership in the new lxd group so that you can access the socket.

**Comment by brunetto** [comment]
Oh.. ooops.. sorry... in fact, now it works!! thanks!!!

**Comment by devekko** [comment]
hi, in fact, the docs suggest you are ok to skip this step

After you've got LXD installed, you can take your first steps.

https://github.com/lxc/lxd#first-steps

First Steps is after the permissions thing...

**Comment by tych0** [comment]
On Thu, Feb 04, 2016 at 05:59:15PM -0800, Nicholas Roberts wrote:
> hi, in fact, the docs suggest you are ok to skip this step
> 
> After you've got LXD installed, you can take your first steps.
> 
> https://github.com/lxc/lxd#first-steps
> 
> First Steps is after the permissions thing... 

Indeed it does, I've submitted: https://github.com/lxc/lxd/pull/1573

Thanks!

**Comment by devekko** [comment]
there seems to be some differences between the linuxcontainers site docs and the readme

also, I am using Xenial as a host now, and there is no master ppa

**Comment by stgraber** [comment]
The PPAs are generated from what's in xenial, that's why we don't have xenial in our PPAs.

**Comment by dankegel** [comment]
On Ubuntu 15.10, doing 'apt-get install lxd; newgrp lxd' was not sufficient to get rid of the error; I still get 
```
WARN[03-14|15:19:51] Per-container AppArmor profiles are disabled because mac_admin capability is missing. 
error: remove /var/lib/lxd/devlxd/sock: permission denied
```

**Comment by stgraber** [comment]
@dankegel the client tool is "lxc" not "lxd".

**Comment by dankegel** [comment]
thanks.  bet i'm not the last person to make this mistake.  maybe I'll submit a one-line patch for the README to make it slightly clearer.
