### ISSUE TITLE
Feature Request: API Returning Supported Storage Drivers

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#5955]
When writing a client application you have to keep up to do date with the available storage drivers, but it would be nice if instead we could query LXD for the supported ones 

An example:

To create a new storage pool a user is asked what storage driver to use, but  I have to hard code a list like:

```html
<option value="zfs">ZFS</option>
<option value="Btrfs">BTRFS</option>
<option value="LVM">LVM</option>
<option value="CEPH">CEPH</option>
<option value="dir">DIR</option>
```

which isn't ideal really, but not the end of the world!

**Comment by stgraber** [comment]
This isn't something we plan on adding at this point. We may at some point make the API self-describing which would end up covering this, but that'd be a huge project and not one that we see happening for quite a while.

For the time being, your best bet is to rely on API extensions.
As follow:
 - storage => initial storage API, indicates support for dir, zfs, btrfs and lvm
 - storage_driver_ceph => Support for Ceph
 - storage_cephfs => Support for Ceph FS

Sorry for the lack of consistency on those two, I forgot to look for the previously used pattern when I introduced cephfs... (and sadly renaming them isn't really a thing we can do).

**Comment by turtle0x1** [comment]
Thanks @stgraber
