### ISSUE TITLE
Storage pool on an NFS share strange user mapping

### ISSUE THREAD

**Issue by matthewcooper** [lxc/lxd#5962]
# Required information

 * Distribution:Ubuntu
 * Distribution version: 18.04 LTS
 * The output of "lxc info" or if that fails:
   config:
  core.https_address: 10.0.4.1:8443
  core.trust_password: true
  maas.api.key: ****
  maas.api.url: http://*****:5240/MAAS
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.0.4.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificate_fingerprint:
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-54-generic
  server: lxd
  server_pid: 30277
  server_version: 3.0.3
  storage: dir
  storage_version: "1"
  server_clustered: true
  server_name: m-node-01
  project: ""

# UID mapping incorrect when creating a file.

When touching or creating a file with vim (or any other method) is created with the UID on nobody (65534) but other files are all correct the startup. The correct UID can be set by chown of the file

# Steps to reproduce

1. Create container (lxc launch -s nfs ubuntu:18.04)
2. Access container ( lxc exec modest-ladybug -- sudo /bin/bash )
3. touch file (touch test)
4. list dir (ls -la)
```
root@modest-ladybug:~# ls -la
total 50
drwx------  3 root   root    6 Jul 15 21:18 .
drwxr-xr-x 22 root   root   22 Jun 27 16:28 ..
-rw-r--r--  1 root   root 3106 Apr  9  2018 .bashrc
-rw-r--r--  1 root   root  148 Aug 17  2015 .profile
drwx------  2 root   root    3 Jul 15 21:17 .ssh
-rw-r--r--  1 nobody root    0 Jul 15 21:18 test
```
5. Change own (chown root:root test)
```
root@modest-ladybug:~# ls -la
total 50
drwx------  3 root root    6 Jul 15 21:18 .
drwxr-xr-x 22 root root   22 Jun 27 16:28 ..
-rw-r--r--  1 root root 3106 Apr  9  2018 .bashrc
-rw-r--r--  1 root root  148 Aug 17  2015 .profile
drwx------  2 root root    3 Jul 15 21:17 .ssh
-rw-r--r--  1 root root    0 Jul 15 21:18 test
```
# Information to attach
 - [ ] Container log (`lxc info NAME --show-log`)
Name: modest-ladybug
Location: m-node-02
Remote: unix://
Architecture: x86_64
Created: 2019/07/15 21:15 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 24080
Ips:
  eth0:	inet	10.1.128.8	veth68YBCW
  eth0:	inet6	fe80::216:3eff:fee4:bcc0	veth68YBCW
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 24
  CPU usage:
    CPU usage (in seconds): 9
  Memory usage:
    Memory (current): 220.18MB
    Memory (peak): 279.36MB
  Network usage:
    eth0:
      Bytes received: 832.51kB
      Bytes sent: 14.13kB
      Packets received: 5312
      Packets sent: 176
    lo:
      Bytes received: 1.42kB
      Bytes sent: 1.42kB
      Packets received: 16
      Packets sent: 16

Log:

lxc modest-ladybug 20190715211703.342 WARN     conf - conf.c:lxc_setup_devpts:1616 - Invalid argument - Failed to unmount old devpts instance

 - [ ] Container configuration (`lxc config show NAME --expanded`)
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20190627.1)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20190627.1"
  image.version: "18.04"
  volatile.base_image: 6ae1c6e92017402f1aee655fa8d785ee9d2337a3369d76115cecad5e7a303e07
  volatile.eth0.hwaddr: 00:16:3e:e4:bc:c0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    maas.subnet.ipv4: system-subnet
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: nfs
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
t=2019-07-15T08:50:07+0000 lvl=info msg="Updating images" 
t=2019-07-15T08:50:07+0000 lvl=info msg="Done updating images" 
t=2019-07-15T14:50:07+0000 lvl=info msg="Pruning expired images" 
t=2019-07-15T14:50:07+0000 lvl=info msg="Done pruning expired images" 
t=2019-07-15T14:50:07+0000 lvl=info msg="Expiring log files" 
t=2019-07-15T14:50:07+0000 lvl=info msg="Done expiring log files" 
t=2019-07-15T14:50:07+0000 lvl=info msg="Updating instance types" 
t=2019-07-15T14:50:07+0000 lvl=info msg="Done updating instance types" 
t=2019-07-15T14:50:07+0000 lvl=info msg="Updating images" 
t=2019-07-15T14:50:07+0000 lvl=info msg="Done updating images" 
t=2019-07-15T17:42:57+0000 lvl=warn msg="Detected poll(POLLNVAL) event." 
t=2019-07-15T18:01:57+0000 lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: failed to receive response: failed to receive header: failed to receive header: EOF" 
t=2019-07-15T18:01:58+0000 lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: failed to receive response: failed to receive header: failed to receive header: EOF" 
t=2019-07-15T18:02:42+0000 lvl=warn msg="Failed to get events from node 10.0.4.2:8443: Unable to connect to: 10.0.4.2:8443" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Received 'terminated signal', exiting" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Starting shutdown sequence" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Stopping REST API handler:" 
t=2019-07-15T18:05:15+0000 lvl=info msg=" - closing socket" socket=10.0.4.1:8443
t=2019-07-15T18:05:15+0000 lvl=info msg=" - closing socket" socket=/var/lib/lxd/unix.socket
t=2019-07-15T18:05:15+0000 lvl=info msg="Stopping /dev/lxd handler" 
t=2019-07-15T18:05:15+0000 lvl=info msg=" - closing socket" socket=/var/lib/lxd/devlxd/sock
t=2019-07-15T18:05:15+0000 lvl=info msg="Closing the database" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Stopping REST API handler:" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Stopping /dev/lxd handler" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Stopping REST API handler:" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Stopping /dev/lxd handler" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Saving simplestreams cache" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Saved simplestreams cache" 
t=2019-07-15T18:05:15+0000 lvl=info msg="LXD 3.0.3 is starting in normal mode" path=/var/lib/lxd
t=2019-07-15T18:05:15+0000 lvl=info msg="Kernel uid/gid map:" 
t=2019-07-15T18:05:15+0000 lvl=info msg=" - u 0 0 4294967295" 
t=2019-07-15T18:05:15+0000 lvl=info msg=" - g 0 0 4294967295" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Configured LXD uid/gid map:" 
t=2019-07-15T18:05:15+0000 lvl=info msg=" - u 0 100000 1000000000" 
t=2019-07-15T18:05:15+0000 lvl=info msg=" - g 0 100000 1000000000" 
t=2019-07-15T18:05:15+0000 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." 
t=2019-07-15T18:05:15+0000 lvl=info msg="Kernel features:" 
t=2019-07-15T18:05:15+0000 lvl=info msg=" - netnsid-based network retrieval: no" 
t=2019-07-15T18:05:15+0000 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Initializing local database" 
t=2019-07-15T18:05:15+0000 lvl=info msg="Starting /dev/lxd handler:" 
t=2019-07-15T18:05:15+0000 lvl=info msg=" - binding devlxd socket" socket=/var/lib/lxd/devlxd/sock
t=2019-07-15T18:05:15+0000 lvl=info msg="REST API daemon:" 
t=2019-07-15T18:05:15+0000 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/lib/lxd/unix.socket
t=2019-07-15T18:05:15+0000 lvl=info msg=" - binding TCP socket" socket=10.0.4.1:8443
t=2019-07-15T18:05:15+0000 lvl=info msg="Initializing global database" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Initializing storage pools" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Initializing networks" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Pruning leftover image files" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Done pruning leftover image files" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Loading daemon configuration" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Pruning expired images" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Done pruning expired images" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Expiring log files" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Done expiring log files" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Updating instance types" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Done updating instance types" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Updating images" 
t=2019-07-15T18:05:16+0000 lvl=info msg="Done updating images" 
t=2019-07-15T18:05:17+0000 lvl=info msg="Connected to MAAS controller" url=http://****:5240/MAAS
t=2019-07-15T18:09:35+0000 lvl=info msg="Stopping container" action=stop created=2019-07-14T21:04:31+0000 ephemeral=false name=juju-594876-10 stateful=false used=2019-07-14T21:04:39+0000
t=2019-07-15T18:09:36+0000 lvl=info msg="Stopped container" action=stop created=2019-07-14T21:04:31+0000 ephemeral=false name=juju-594876-10 stateful=false used=2019-07-14T21:04:39+0000
t=2019-07-15T18:09:36+0000 lvl=info msg="Deleting container" created=2019-07-14T21:04:31+0000 ephemeral=false name=juju-594876-10 used=2019-07-14T21:04:39+0000
t=2019-07-15T18:09:40+0000 lvl=info msg="Deleted container" created=2019-07-14T21:04:31+0000 ephemeral=false name=juju-594876-10 used=2019-07-14T21:04:39+0000

**Comment by stgraber** [comment]
Can you show `cat /proc/self/mountinfo` in the container?

In all cases, this isn't going to be a LXD bug but a kernel one, though that output may help figure out where in the kernel the issue would be from.

**Comment by matthewcooper** [comment]
# cat /proc/self/mountinfo

`root@modest-ladybug:~# cat /proc/self/mountinfo
410 50 0:52 / / rw,relatime master:171 - nfs4 nas.whitecrane.io:/mnt/Tank1/lxd/m-node-02/containers/modest-ladybug/rootfs rw,vers=4.1,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.0.4.2,local_lock=none,addr=10.0.3.32
411 410 0:56 / /dev rw,relatime - tmpfs none rw,size=492k,mode=755,uid=100000,gid=100000
412 410 0:55 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
413 410 0:57 / /sys rw,relatime - sysfs sysfs rw
414 412 0:50 /proc/cpuinfo /proc/cpuinfo rw,nosuid,nodev,relatime master:175 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
415 412 0:50 /proc/diskstats /proc/diskstats rw,nosuid,nodev,relatime master:175 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
416 412 0:50 /proc/meminfo /proc/meminfo rw,nosuid,nodev,relatime master:175 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
417 412 0:50 /proc/stat /proc/stat rw,nosuid,nodev,relatime master:175 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
418 412 0:50 /proc/swaps /proc/swaps rw,nosuid,nodev,relatime master:175 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
419 412 0:50 /proc/uptime /proc/uptime rw,nosuid,nodev,relatime master:175 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
420 410 0:50 / /var/lib/lxcfs rw,nosuid,nodev,relatime master:175 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
421 411 0:6 /full /dev/full rw,nosuid,relatime master:2 - devtmpfs udev rw,size=24689400k,nr_inodes=6172350,mode=755
422 411 0:6 /null /dev/null rw,nosuid,relatime master:2 - devtmpfs udev rw,size=24689400k,nr_inodes=6172350,mode=755
423 411 0:6 /random /dev/random rw,nosuid,relatime master:2 - devtmpfs udev rw,size=24689400k,nr_inodes=6172350,mode=755
424 411 0:6 /tty /dev/tty rw,nosuid,relatime master:2 - devtmpfs udev rw,size=24689400k,nr_inodes=6172350,mode=755
425 411 0:6 /urandom /dev/urandom rw,nosuid,relatime master:2 - devtmpfs udev rw,size=24689400k,nr_inodes=6172350,mode=755
426 411 0:6 /zero /dev/zero rw,nosuid,relatime master:2 - devtmpfs udev rw,size=24689400k,nr_inodes=6172350,mode=755
427 411 0:6 /fuse /dev/fuse rw,nosuid,relatime master:2 - devtmpfs udev rw,size=24689400k,nr_inodes=6172350,mode=755
428 411 0:6 /net/tun /dev/net/tun rw,nosuid,relatime master:2 - devtmpfs udev rw,size=24689400k,nr_inodes=6172350,mode=755
429 412 0:58 / /proc/sys/fs/binfmt_misc rw,relatime master:190 - binfmt_misc binfmt_misc rw
430 413 0:45 / /sys/fs/fuse/connections rw,relatime master:33 - fusectl fusectl rw
431 413 0:30 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime master:12 - pstore pstore rw
432 413 0:8 / /sys/kernel/debug rw,relatime master:30 - debugfs debugfs rw
433 413 0:7 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime master:8 - securityfs securityfs rw
434 411 0:19 / /dev/mqueue rw,relatime master:26 - mqueue mqueue rw
435 411 0:53 / /dev/lxd rw,relatime master:183 - tmpfs tmpfs rw,size=100k,mode=755
436 411 0:51 /modest-ladybug /dev/.lxd-mounts rw,relatime master:179 - tmpfs tmpfs rw,size=100k,mode=711
437 411 0:22 /0 /dev/console rw,nosuid,noexec,relatime master:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
51 411 0:59 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=100005,mode=620,ptmxmode=666,max=1024
88 411 0:59 /ptmx /dev/ptmx rw,nosuid,noexec,relatime - devpts devpts rw,gid=100005,mode=620,ptmxmode=666,max=1024
89 411 0:60 / /dev/shm rw,nosuid,nodev - tmpfs tmpfs rw,uid=100000,gid=100000
122 410 0:61 / /run rw,nosuid,nodev - tmpfs tmpfs rw,mode=755,uid=100000,gid=100000
123 122 0:62 / /run/lock rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,size=5120k,uid=100000,gid=100000
156 413 0:63 / /sys/fs/cgroup ro,nosuid,nodev,noexec - tmpfs tmpfs ro,mode=755,uid=100000,gid=100000
157 156 0:28 / /sys/fs/cgroup/unified rw,nosuid,nodev,noexec,relatime - cgroup2 cgroup rw
189 156 0:29 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,xattr,name=systemd
190 156 0:31 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,hugetlb
239 156 0:34 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_cls,net_prio
240 156 0:33 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpu,cpuacct
278 156 0:36 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,pids
279 156 0:32 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset
311 156 0:39 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,perf_event
312 156 0:38 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory
370 156 0:37 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
371 156 0:41 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio
388 156 0:40 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer
389 156 0:35 / /sys/fs/cgroup/rdma rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,rdma
`

**Comment by stgraber** [comment]
Ok, thanks, I just wanted to check if shiftfs was involved and it's not, you also don't have any other kind of overlay type mounts in there so it's really just nfs4 getting confused by the user namespace.

@brauner is that something you want to take a short look at? Maybe something obvious they messed up?

**Comment by stgraber** [comment]
(Closing as not a LXD bug, this is a kernel bug you're hitting when creating files from a user namespace different than that used for the original mount)

**Comment by matthewcooper** [comment]
Hi, @stgraber Thank you for the help.

I have posted the bug https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1836707 

Any chance of getting this push high?

Thank you gain.

**Comment by stgraber** [comment]
I highly doubt that the Ubuntu kernel team has the needed NFS kernel knowledge or time to sort this one out. I think your best bet is to have this resolved upstream in the mainline kernel, at which point that Launchpad bug will become the tracking bug for the fix getting backported to all suitable kernels.

If you can, please reproduce the issue on the latest mainline snapshot at https://kernel.ubuntu.com/~kernel-ppa/mainline/ and indicate that you've done so in the Launchpad bug. If the current mainline build doesn't have the bug, then all that the kernel team would need to do is track down when this got fixed and cherry-pick the fix to the Ubuntu kernels.

If the issue still happens with the current mainline, then going to the upstream maintainers of the NFS code is likely the best option.
