### ISSUE TITLE
/dev/shm missing in guest

### ISSUE THREAD

**Issue by hadmut** [lxc/lxd#5967]
Hi, 

I just ran into the problem of a missing /dev/shm in the guest file system. 

Setup:

host: Ubuntu 18.04.2 LTS, with lxd 3.0.3-0ubuntu1~18.04.1

guest: Alpine 3.10, started with
lxc launch images:alpine/3.10 proxy

the guest was supposed to run just a squid proxy (apk add squid), but that does not start since /dev/shm is missing in the guest. 

Usually in Alpine /etc/init.d/devfs takes care to create the /dev filesystems and mounts tmpfs as /dev/shm if needed. But for some reason lxd starts the container in a way that /etc/init.d/devfs can't create /dev/shm. 

creating and mounting /dev/shm manually makes the daemon run, but it need to be done after every reboot. So why does lxd start the guest in a way that it does not create /dev/shm?

# Required information

 * Distribution:
host: ubuntu 18.04  guest: Alpine 3.10
  
 * The output of "lxc info" or if that fails:
 # lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFZzCCA0+gAwIBAgIQOSiDDEGR4LfgpSvDUt4UhTANBgkqhkiG9w0BAQsFADAz
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRMwEQYDVQQDDApyb290QG1p
    bmkzMB4XDTE4MTAxMDE5MzY1NFoXDTI4MTAwNzE5MzY1NFowMzEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBtaW5pMzCCAiIwDQYJ
    KoZIhvcNAQEBBQADggIPADCCAgoCggIBAN4Ak1jAOkDGbJxXhpeEfjUis9AzaGVu
    cyH9fD6i3AypDVlACWJYqZpe4vWlWMw6nLtFud43Nw7yVGvoD5ab9BQTyTkWVzxd
    FQjvJ5NIPZ7HTJmcFb5KG6yrhgUNE2TYPMsj25H7QdweIl9cnP/+opoMz4sprn9W
    TW8wQ8iHsT6iVZiQdlc8drmAoebBdyWcggHc6LLnGUKw0A8rEVIWPGxm6VHorf68
    Q6oZ2EA6WsjwW4Wp0K6YIDRJwE7GR6fhMesfdT0VddiGcw1c5NkR/szeb56cOiS+
    AAUy8nXwyQR/oH1wCd3HGL+VIYddLXMxtv+Neu6iMV+UuH+jhO3T+xDXEv/o7SRl
    Xp+WyAKfXEgOAVWmQrFw8bbXtMv2Wo6qq3ppp/HErz4MeEEcvLaNNJW3FYjidJxA
    0ncTFOVWbtuspgG1JYGl+lucHOU+pPC/L0XWhnnomODJiea0iqCnmwxqaS/iu5s8
    eGUBFePzckM5bRxO6CG+k5J0fg6Nv+dSpMYF6QuVU9BLXsaCK1xtfArDxYDTnzV6
    eDffJDuGzShU23UMC9EmzeUOGVlVm0LH1GVdIvd9vZUt2gqX2Xtpv364nF4SbRsJ
    ByznHP9S3itbxvJz5ZzQVQrYN8wnkCwoRmJdS2UO3EbxWUmLL08deGkMAd96sVoc
    t+SomS76cStNAgMBAAGjdzB1MA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMEAGA1UdEQQ5MDeCBW1pbmkzhwTAqKSchxD9
    /I4AJGQAAQIBwP/+ITQAhxAqAoEJmIAtwAIBwP/+ITQAhwSsEQABMA0GCSqGSIb3
    DQEBCwUAA4ICAQBfsbxwgqrr9GfaPkfy2B/9pm2wgkYQfHo5gSGo7qSZzC6qabWU
    awF2ItM5s22NVZjuRDQm5MA+MlIPfpptdaUHk76xcu+QprmHvKu0Lw/aGXNt1Pnp
    hoSIgYv0zxc4MS2z4x2xUrdFNeGd2xTlggLHvKd8JbfPo+GyRxkoHz89iwIWv2R+
    VefccAyjRiKiPv/FykHI/18VsEtE27LC3UWrHRIWzv2E6sxKZMy60+fLgCnst8Tz
    gXz1rjVqzDFTOq8UL+d/bTbP3c2L4BFnItBetGA5K/vOlvF6kWXCSNHdtAT4rsxD
    rwZCtwHLSsxlWg+3cWv3UwKha4rZW4c3Gzi7mpChSIrWb0UL3QGPUWhAjZnv/lMe
    WygR5YDvN5A+wm2RY5GdYhQB8kQUEBOcxr2VV4Jh32X8y/Pj0Ug6DQfmXi/GCWCg
    6vfiBTlnmMky/9h6ZnUavwGzHumBA640WjzduIBR+6beZW9xxttjItaBb1g/Fi+/
    TFAZ5x+w2BWP3JHky8pCrLBqy0svlrgeTS5JJmMW/dC3NC+HYvpwxv4l7DbQz8Gy
    U1hjE1F5dQnXuFR7YGIxY8nbQ/9gGgThZsg3Xp0dyaFnvA916mZ6LJwlznFNbDnK
    dWZbDrZgBdLAitbSBP2CuiW3KI3/qXQ2batrKLT/Xh2+2Z3EIaxz1UCUkw==
    -----END CERTIFICATE-----
  certificate_fingerprint: bb54e104142bb7254715d373ebc1f77ef072284070f19fbff7f438faf69f48d5
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-54-generic
  server: lxd
  server_pid: 1553
  server_version: 3.0.3
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: mini3
  project: ""
root@mini3 ~ # 
root@mini3 ~ # lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFZzCCA0+gAwIBAgIQOSiDDEGR4LfgpSvDUt4UhTANBgkqhkiG9w0BAQsFADAz
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRMwEQYDVQQDDApyb290QG1p
    bmkzMB4XDTE4MTAxMDE5MzY1NFoXDTI4MTAwNzE5MzY1NFowMzEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBtaW5pMzCCAiIwDQYJ
    KoZIhvcNAQEBBQADggIPADCCAgoCggIBAN4Ak1jAOkDGbJxXhpeEfjUis9AzaGVu
    cyH9fD6i3AypDVlACWJYqZpe4vWlWMw6nLtFud43Nw7yVGvoD5ab9BQTyTkWVzxd
    FQjvJ5NIPZ7HTJmcFb5KG6yrhgUNE2TYPMsj25H7QdweIl9cnP/+opoMz4sprn9W
    TW8wQ8iHsT6iVZiQdlc8drmAoebBdyWcggHc6LLnGUKw0A8rEVIWPGxm6VHorf68
    Q6oZ2EA6WsjwW4Wp0K6YIDRJwE7GR6fhMesfdT0VddiGcw1c5NkR/szeb56cOiS+
    AAUy8nXwyQR/oH1wCd3HGL+VIYddLXMxtv+Neu6iMV+UuH+jhO3T+xDXEv/o7SRl
    Xp+WyAKfXEgOAVWmQrFw8bbXtMv2Wo6qq3ppp/HErz4MeEEcvLaNNJW3FYjidJxA
    0ncTFOVWbtuspgG1JYGl+lucHOU+pPC/L0XWhnnomODJiea0iqCnmwxqaS/iu5s8
    eGUBFePzckM5bRxO6CG+k5J0fg6Nv+dSpMYF6QuVU9BLXsaCK1xtfArDxYDTnzV6
    eDffJDuGzShU23UMC9EmzeUOGVlVm0LH1GVdIvd9vZUt2gqX2Xtpv364nF4SbRsJ
    ByznHP9S3itbxvJz5ZzQVQrYN8wnkCwoRmJdS2UO3EbxWUmLL08deGkMAd96sVoc
    t+SomS76cStNAgMBAAGjdzB1MA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMEAGA1UdEQQ5MDeCBW1pbmkzhwTAqKSchxD9
    /I4AJGQAAQIBwP/+ITQAhxAqAoEJmIAtwAIBwP/+ITQAhwSsEQABMA0GCSqGSIb3
    DQEBCwUAA4ICAQBfsbxwgqrr9GfaPkfy2B/9pm2wgkYQfHo5gSGo7qSZzC6qabWU
    awF2ItM5s22NVZjuRDQm5MA+MlIPfpptdaUHk76xcu+QprmHvKu0Lw/aGXNt1Pnp
    hoSIgYv0zxc4MS2z4x2xUrdFNeGd2xTlggLHvKd8JbfPo+GyRxkoHz89iwIWv2R+
    VefccAyjRiKiPv/FykHI/18VsEtE27LC3UWrHRIWzv2E6sxKZMy60+fLgCnst8Tz
    gXz1rjVqzDFTOq8UL+d/bTbP3c2L4BFnItBetGA5K/vOlvF6kWXCSNHdtAT4rsxD
    rwZCtwHLSsxlWg+3cWv3UwKha4rZW4c3Gzi7mpChSIrWb0UL3QGPUWhAjZnv/lMe
    WygR5YDvN5A+wm2RY5GdYhQB8kQUEBOcxr2VV4Jh32X8y/Pj0Ug6DQfmXi/GCWCg
    6vfiBTlnmMky/9h6ZnUavwGzHumBA640WjzduIBR+6beZW9xxttjItaBb1g/Fi+/
    TFAZ5x+w2BWP3JHky8pCrLBqy0svlrgeTS5JJmMW/dC3NC+HYvpwxv4l7DbQz8Gy
    U1hjE1F5dQnXuFR7YGIxY8nbQ/9gGgThZsg3Xp0dyaFnvA916mZ6LJwlznFNbDnK
    dWZbDrZgBdLAitbSBP2CuiW3KI3/qXQ2batrKLT/Xh2+2Z3EIaxz1UCUkw==
    -----END CERTIFICATE-----
  certificate_fingerprint: bb54e104142bb7254715d373ebc1f77ef072284070f19fbff7f438faf69f48d5
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-54-generic
  server: lxd
  server_pid: 1553
  server_version: 3.0.3
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: mini3
  project: ""

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
That's an Alpine Linux bug, not a LXD one.

The /etc/init.d/devfs script they ship specifically includes `-lxc` at the top which has it never run inside LXC/LXD containers.

If you modify /etc/init.d/devfs to remove that `-lxc` and then run `rc-update add devfs boot`, that script should then get run on startup and you'll end up with /dev/shm.

I'd recommend you file a bug with Alpine Linux to make them aware of that. They should either run that entire script on LXC too, or split out the SHM handling to a separate boot script and have that one run everywhere.

**Comment by ogelpre** [comment]
I have opened a ticket on upstream OpenRC project: https://bugs.gentoo.org/761918
