### ISSUE TITLE
When a transfer source is a local LXD (unix socket), the main public IP should be used (exported through API)

### ISSUE THREAD

**Issue by kenokabe** [lxc/lxd#598]
I try to copy a container from local to remote.

Say,
```
lxc remote add azurehost https://my-instance.cloudapp.net:8443
```
and it is registered succesufly from the local.

Trying to copy a container:

```
$ lxc copy ubuntu azurehost:ubuntu
error: non-http remotes are not supported for migration right now
```

Ok,
so, I try as follows:

```
$ lxc config set password some-password
$ lxc remote add localhost http://localhost:8443
$ lxc copy localhost:ubuntu azurehost:ubuntu
error: websocket: bad handshake
```

Is there any workarounds?

Or, currently, is it possible to copy a container from local to remote by lxd?

Thanks.

**Comment by stgraber** [comment]
It's correct that you need to copy from a remote lxd (not unix socket) to a remote lxd, so your latter try is right.

The handshake error is typically because of a version mismatch between source and target as we've unfortunately had to change the protocol recently. Making sure they both run the same version would fix that.

**Comment by tych0** [comment]
On Wed, May 06, 2015 at 05:17:06PM -0700, Ken OKABE wrote:
> I try to copy a container from local to remote.
> 
> Say,
> ```
> lxc remote add azurehost https://my-instance.cloudapp.net:8443
> ```
> and it is registered succesufly from the local.
> 
> Trying to copy a container:
> 
> ```
> $ lxc copy ubuntu azurehost:ubuntu
> error: non-http remotes are not supported for migration right now
> ```
> 
> Ok,
> so, I try as follows:
> 
> ```
> $ lxc remote add localhost http://localhost:8443
> $ lxc copy localhost:ubuntu azurehost:ubuntu
> error: websocket: bad handshake
> ```
> 
> Is there any workarounds?

Yes, you can't use "localhost" here. The way the `lxc` client works
right now is it just looks at its remote URL (in your case,
http://localhost:8443) and supplies that to the remote host as the
address to copy the container from. azurehost then tries to connect to
http://localhost:8443 and fails.

So, if you use the public ip of your local remote as the remote
address, it should work (barring any version mismatches as stgraber
points out).

**Comment by stgraber** [comment]
We should still try to be a bit more clever here, possibly exposing an interface to get the main public IP of the source over the API and then try to use that for transfers.

I'll re-cycle this issue for that.

**Comment by kenokabe** [comment]
Thanks a lot gentlemen the core developer here.

The lxd version is the latest 8.1 on the both client and remote site.

>So, if you use the public ip of your local remote as the remote
address, it should work 

Thanks for the tip.
In fact, I've read the article:
https://insights.ubuntu.com/2015/05/06/live-migration-in-lxd/
 no localhost for the public IP. I understand.

>supplies that to the remote host as the
address to copy the container from. azurehost then tries to connect to
http://localhost:8443 and fails.

I do websocket programming a lot in node(js), unfortunately not in C like this project,
and I think we can definitely make it possible (more like easily) to implement to transfer file via TCP port between localhost and remote IP.

What I don't get is, in fact, I could trander 'profile' from localhost to remote.

**Comment by ovidiucp** [comment]
The copy operation seems to be working, sort of. This is how I run it:

```
lxc remote add  m1b https://m1b:3000
lxc copy local:p1 remotemachine:p1
```

If I run `lxc list` on `m1b` while the image is copying, I can see the p1 container being listed:

```
ovidiu@m1b:~$ lxc list
+------+---------+------------+------+-----------+-----------+
| NAME |  STATE  |    IPV4    | IPV6 | EPHEMERAL | SNAPSHOTS |
+------+---------+------------+------+-----------+-----------+
| p1   | STOPPED |            |      | NO        | 0         |
+------+---------+------------+------+-----------+-----------+
```

However the lxc copy command finishes with the error below:

```
error: dial tcp: lookup unix.socket: no such host
```

The copied `p1` container on `m1b` is then deleted.

**Comment by ovidiucp** [comment]
I started lxd with the `--debug` flag, and this is what it reports at the end of the copy operation:

```
2015/05/14 17:30:56 operation %!s(func() shared.OperationResult=0x4cd320) finished: { dial tcp: lookup unix.socket: no such host}
2015/05/14 17:30:56 
	{
		"type": "sync",
		"status": "Success",
		"status_code": 200,
		"metadata": {
			"created_at": "2015-05-14T17:30:36.004119368-07:00",
			"updated_at": "2015-05-14T17:30:56.428702722-07:00",
			"status": "Failure",
			"status_code": 400,
			"resources": {
				"containers": [
					"/1.0/containers/p1"
				]
			},
			"metadata": "dial tcp: lookup unix.socket: no such host",
			"may_cancel": false
		}
	}
```

**Comment by ovidiucp** [comment]
Um, I re-read the thread and now I see what the problem is. The copy operation was not really working. On the destination machine (`m1b`) a destination container was setup, and the copy was attempted using the following request:

```
2015/05/14 17:38:05 handling POST /1.0/containers
2015/05/14 17:38:05 
	{
		"config": null,
		"name": "p1",
		"profiles": null,
		"source": {
			"base-image": "a4066a730e6b3d8021dcc7d0c59f2c37624ffdb60d10f1e09c336e4e1631915c",
			"mode": "pull",
			"operation": "ws://unix.socket/1.0/operations/4ff8104e-3696-4bdb-999e-d1fbb5c6a532/websocket",
			"secrets": {
				"control": "00cc009f301752a525b5d70f59bdd192c78ea1e2a57210ee647bcede5f07d15c",
				"fs": "fd80089ca067b1900202d84813fa21b506de11e9ea5fbff68ec280e5b79c7f9d"
			},
			"type": "migration"
		}
	}
```

However the attempt to resolve `unix.socket` as a DNS name fails, and so the whole operation failed.

The workaround was to add the source machine  (`m1a`) as a remote on itself, and then perform the copy operation:

```
lxc remote add  m1a https://m1a:3000
lxc copy m1a:p1 m1b:p1
```
