### ISSUE TITLE
Some thoughts about projects and few ideas to improve them all.

### ISSUE THREAD

**Issue by geodb27** [lxc/lxd#5987]
* Distribution: Ubuntu 
 * Distribution version: 18.04 server LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-51-generic #55-Ubuntu SMP
   * LXC version: 3.14 
   * LXD version: 3.14
   * Storage backend in use: ceph

For now, if a user wants to interact with the lxd daemon and thus containers, he has to be member of group lxd.
This gives rights to do anything on any container.
It would be great if one could have some kind of "subgroup" of the lxd group tied to projects.
Thus, a user belonging to such a group could only interact with containers in the defined project for the purpose.
Of course, such a user should only be allowed to and be bound to his project when attempting to interact with the containers lxd monitors.
Furthermore, it would be great to be abble to "move" or re-assing containers to the right project.
If I'm not mistaken, for now, there is no way to assign an already existing container to another project than the one it was created for.
Could be that more ideas will come after that, but these two steps would greatly enhance the experience.
Thanks for reading.

**Comment by stgraber** [comment]
`lxc move blah --project SOURCE --target-project TARGET` should work just fine.

We did think of allowing user/group to be tied to specific projects but it's rather hard to do in a way where we're confident about the security aspect of it.

Our focus in that area has been around remote connections where we do support user, groups and access restrictions when authenticating against Candid and a Canonical RBAC server.  This is obviously more of a enterprise solution though as that uses external authentication and an external service for access control so specific permissions can be applied to individual users/groups and projects.

It's not impossible that we will one day feel like we've done enough to secure our unix socket that we can open it up and then do a bunch of ucred magic to get the user's uid/gid and its groups to filter based on that, but it would be quite a lot of work and would only be useful to local users, requiring a completely different solution for the remote usage case.
