### ISSUE TITLE
/proc problem in containers

### ISSUE THREAD

**Issue by melato** [lxc/lxd#6002]
lxc 3.15, lxd 3.15
storage backend: ZFS

# Issue description

When I run "uptime" in a container, I get:

> Error: /proc must be mounted
>   To mount /proc at boot you need an /etc/fstab line like:
>       proc   /proc   proc    defaults
>   In the meantime, run "mount proc /proc -t proc"
> 

cat /proc/cpuinfo

> cat: /proc/cpuinfo: Transport endpoint is not connected

I saw this on two different servers.  I rebooted one of them and it was fixed.

**Comment by stgraber** [comment]
That's https://github.com/lxc/lxcfs/issues/295
