### ISSUE TITLE
Fail to start: (probe I/O capabilities: Unknown system error 95)

### ISSUE THREAD

**Issue by Zzorz** [lxc/lxd#6005]
* Distribution:    Archlinux
 * Distribution version:    rolling
 * The output of "lxc info" or if that fails:     `fails`
   * Kernel version:     `5.2.2-arch1-1-ARCH`
   * LXC version:    `3.1.0`
   * LXD version:    `3.15`
   * Storage backend in use:    `zfs-0.8.0`

# Issue description

Can not start lxd daemon
`sudo lxd --debug` with:
```
INFO[07-24|13:05:46] LXD 3.15 is starting in normal mode      path=/var/lib/lxd
INFO[07-24|13:05:46] Kernel uid/gid map: 
INFO[07-24|13:05:46]  - u 0 0 4294967295 
INFO[07-24|13:05:46]  - g 0 0 4294967295 
INFO[07-24|13:05:46] Configured LXD uid/gid map: 
INFO[07-24|13:05:46]  - u 0 1000000 65536 
INFO[07-24|13:05:46]  - g 0 1000000 65536 
WARN[07-24|13:05:46] AppArmor support has been disabled because of lack of kernel support 
INFO[07-24|13:05:46] Kernel features: 
INFO[07-24|13:05:46]  - netnsid-based network retrieval: yes 
INFO[07-24|13:05:46]  - uevent injection: yes 
INFO[07-24|13:05:46]  - seccomp listener: yes 
INFO[07-24|13:05:46]  - unprivileged file capabilities: yes 
INFO[07-24|13:05:46]  - shiftfs support: no 
INFO[07-24|13:05:46] Initializing local database 
DBUG[07-24|13:05:46] Initializing database gateway 
DBUG[07-24|13:05:46] Start database node                      address= id=1
[ERROR]: probe I/O capabilities: Unknown system error 95
EROR[07-24|13:05:46] Failed to start the daemon: Failed to create dqlite server: failed to create server object 
INFO[07-24|13:05:46] Starting shutdown sequence 
DBUG[07-24|13:05:46] Not unmounting temporary filesystems (containers are still running) 
Error: Failed to create dqlite server: failed to create server object
```

**Comment by freeekanayaka** [comment]
Is your ```/var/lib/lxd``` on ZFS 0.8? There was a known bug that we have now fixed. Since I assume you're building from source, please update the [raft](https://github.com/CanonicalLtd/raft) C library to [v0.9.3](https://github.com/CanonicalLtd/raft/releases/tag/v0.9.3).

**Comment by Zzorz** [comment]
> Is your `/var/lib/lxd` on ZFS 0.8? There was a known bug that we have now fixed. Since I assume you're building from source, please update the [raft](https://github.com/CanonicalLtd/raft) C library to [v0.9.3](https://github.com/CanonicalLtd/raft/releases/tag/v0.9.3).

Exactly, my entire root dir is on zfs. Replacing `libraft.so` with newer version solved my problem.
