### ISSUE TITLE
lxd cannot reach socket

### ISSUE THREAD

**Issue by spirritus** [lxc/lxd#6016]
lxd has worked fine.
Then I switched the hosts networking from eno1 to a bridge on that adapter eno1br1.
Since then lxd cannot be reached - lxc info reports "Error: Get http://unix.socket/1.0: EOF"

However the ip has stayed the same.
Rebooting did not remedy the situation. Any ideas?

Debian Buster
LXD 3.15
storage backend: zfs

# cat /proc/version
Linux version 4.19.0-5-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19)

# lxd --debug --group lxd
DBUG[07-26|14:57:46] Connecting to a local LXD over a Unix socket
DBUG[07-26|14:57:46] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
INFO[07-26|14:57:46] LXD 3.15 is starting in normal mode      path=/var/snap/lxd/common/lxd
INFO[07-26|14:57:46] Kernel uid/gid map:
INFO[07-26|14:57:46]  - u 0 0 4294967295
INFO[07-26|14:57:46]  - g 0 0 4294967295
INFO[07-26|14:57:46] Configured LXD uid/gid map:
INFO[07-26|14:57:46]  - u 0 1000000 1000000000
INFO[07-26|14:57:46]  - g 0 1000000 1000000000
WARN[07-26|14:57:46] CGroup memory swap accounting is disabled, swap limits will be ignored.
INFO[07-26|14:57:46] Kernel features:
INFO[07-26|14:57:46]  - netnsid-based network retrieval: no
INFO[07-26|14:57:46]  - uevent injection: yes
INFO[07-26|14:57:46]  - seccomp listener: no
INFO[07-26|14:57:46]  - unprivileged file capabilities: yes
INFO[07-26|14:57:46]  - shiftfs support: no
INFO[07-26|14:57:46] Initializing local database
DBUG[07-26|14:57:46] Initializing database gateway
DBUG[07-26|14:57:46] Start database node                      id=1 address=192.168.1.15:8443
DBUG[07-26|14:57:46] Connecting to a local LXD over a Unix socket
DBUG[07-26|14:57:46] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
DBUG[07-26|14:57:46] Detected stale unix socket, deleting
DBUG[07-26|14:57:46] Detected stale unix socket, deleting
INFO[07-26|14:57:46] Starting /dev/lxd handler:
INFO[07-26|14:57:46]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[07-26|14:57:46] REST API daemon:
INFO[07-26|14:57:46]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[07-26|14:57:46]  - binding TCP socket                    socket=192.168.1.15:8443
INFO[07-26|14:57:46] Initializing global database
DBUG[07-26|14:57:46] Found cert                               name=0
DBUG[07-26|14:57:46] Found cert                               name=0
DBUG[07-26|14:57:46] Dqlite: connected address=192.168.1.15:8443 attempt=0
DBUG[07-26|14:57:47] Found cert                               name=0
DBUG[07-26|14:57:47] Found cert                               name=0
DBUG[07-26|14:57:51] Dqlite: closing client
DBUG[07-26|14:57:51] Database error: &errors.errorString{s:"driver: bad connection"}
DBUG[07-26|14:57:51] Retry failed db interaction (driver: bad connection)
DBUG[07-26|14:57:51] Found cert                               name=0
DBUG[07-26|14:57:51] Found cert                               name=0
DBUG[07-26|14:57:51] Dqlite: connected address=192.168.1.15:8443 attempt=0
DBUG[07-26|14:57:51] Database error: failed to update node version info: database is locked
DBUG[07-26|14:57:51] Retry failed db interaction (failed to update node version info: database is locked)
DBUG[07-26|14:57:52] Database error: failed to update node version info: database is locked
DBUG[07-26|14:57:52] Retry failed db interaction (failed to update node version info: database is locked)
DBUG[07-26|14:57:52] Database error: failed to update node version info: database is locked
DBUG[07-26|14:57:52] Retry failed db interaction (failed to update node version info: database is locked)
DBUG[07-26|14:57:52] Database error: failed to update node version info: database is locked
DBUG[07-26|14:57:52] Retry failed db interaction (failed to update node version info: database is locked)
EROR[07-26|14:57:52] Failed to start the daemon: failed to open cluster database: failed to ensure schema: failed to update node version info: database is locked
INFO[07-26|14:57:52] Starting shutdown sequence
INFO[07-26|14:57:52] Stopping REST API handler:
INFO[07-26|14:57:52]  - closing socket                        socket=192.168.1.15:8443
INFO[07-26|14:57:52]  - closing socket                        socket=/var/snap/lxd/common/lxd/unix.socket
INFO[07-26|14:57:52] Stopping /dev/lxd handler:
INFO[07-26|14:57:52]  - closing socket                        socket=/var/snap/lxd/common/lxd/devlxd/sock
DBUG[07-26|14:57:52] Stop database gateway
DBUG[07-26|14:57:52] Not unmounting temporary filesystems (containers are still running)
Error: failed to open cluster database: failed to ensure schema: failed to update node version info: database is locked

**Comment by stgraber** [comment]
Can you show the `ip link show` and `ip addr show` output?

**Comment by stgraber** [comment]
and `netstat -lnp` too

**Comment by rigred** [comment]
Likely the same problem has occurred to me as well along with the 3.15 auto-refresh issue.
https://github.com/lxc/lxcfs/issues/295

```
Jul 28 13:09:31 hetz-hel1 systemd[1]: Started Service for snap application lxd.daemon.
Jul 28 13:09:31 hetz-hel1 lxd.daemon[16153]: => Preparing the system
Jul 28 13:09:31 hetz-hel1 lxd.daemon[16153]: ==> Loading snap configuration
Jul 28 13:09:31 hetz-hel1 lxd.daemon[16153]: ==> Setting up mntns symlink (mnt:[4026532239])
Jul 28 13:09:32 hetz-hel1 lxd.daemon[16153]: ==> Setting up kmod wrapper
Jul 28 13:09:32 hetz-hel1 lxd.daemon[16153]: ==> Preparing /boot
Jul 28 13:09:32 hetz-hel1 lxd.daemon[16153]: ==> Preparing a clean copy of /run
Jul 28 13:09:33 hetz-hel1 lxd.daemon[16153]: ==> Preparing a clean copy of /etc
Jul 28 13:09:35 hetz-hel1 lxd.daemon[16153]: ==> Setting up ceph configuration
Jul 28 13:09:35 hetz-hel1 lxd.daemon[16153]: ==> Setting up LVM configuration
Jul 28 13:09:35 hetz-hel1 lxd.daemon[16153]: ==> Rotating logs
Jul 28 13:09:35 hetz-hel1 lxd.daemon[16153]: ==> Setting up ZFS (0.7)
Jul 28 13:09:35 hetz-hel1 lxd.daemon[16153]: ==> Escaping the systemd cgroups
Jul 28 13:09:35 hetz-hel1 lxd.daemon[16153]: ==> Escaping the systemd process resource limits
Jul 28 13:09:35 hetz-hel1 lxd.daemon[16153]: ==> Enabling CRIU
Jul 28 13:09:35 hetz-hel1 lxd.daemon[16153]: ==> Disabling shiftfs on this kernel (auto)
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]: mount namespace: 7
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]: hierarchies:
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:   0: fd:   8: memory
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:   1: fd:   9: perf_event
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:   2: fd:  10: cpu,cpuacct
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:   3: fd:  11: cpuset
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:   4: fd:  12: rdma
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:   5: fd:  13: blkio
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:   6: fd:  14: devices
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:   7: fd:  15: hugetlb
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:   8: fd:  16: freezer
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:   9: fd:  17: pids
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:  10: fd:  18: net_cls,net_prio
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:  11: fd:  19: name=systemd
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]:  12: fd:  20: unified
Jul 28 13:09:35 hetz-hel1 lxd.daemon[27387]: lxcfs.c: 152: do_reload: lxcfs: reloaded
Jul 28 13:09:35 hetz-hel1 lxd.daemon[16153]: => Re-using existing LXCFS
Jul 28 13:09:35 hetz-hel1 lxd.daemon[16153]: => Starting LXD
Jul 28 13:09:42 hetz-hel1 lxd.daemon[16153]: t=2019-07-28T13:09:42+0000 lvl=eror msg="Failed to start the daemon: failed to open cluster database: failed to ensure schema: failed to update node version info: database is locked"
Jul 28 13:09:42 hetz-hel1 lxd.daemon[16153]: Error: failed to open cluster database: failed to ensure schema: failed to update node version info: database is locked
Jul 28 13:09:42 hetz-hel1 lxd.daemon[16153]: => LXD failed to start
```

I can't connect to lxd with lxc, but containers are actually running since my services are online. The snap is also 'pretending' to fail and attempting to restart in a loop, to no avail. 
Doing a `snap restart lxd ` does nothing useful. Changing versions does nothing useful. 
Attached is output of `lxd --debug --group lxd`

[lxd-debug_1.tar.gz](https://github.com/lxc/lxd/files/3439204/lxd-debug_1.tar.gz)

**Comment by rigred** [comment]
Actually I managed to just get further. I did a daemon-reload on systemd and the `snap.lxd.daemon.unix.socket` came back again and could be started. 

```
sudo systemctl status snap.lxd.daemon.unix.socket
**Failed to dump process list, ignoring: No such file or directory**
● snap.lxd.daemon.unix.socket - Socket unix for snap application lxd.daemon
   Loaded: loaded (/etc/systemd/system/snap.lxd.daemon.unix.socket; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-07-27 23:31:04 UTC; 14h ago
   Listen: /var/snap/lxd/common/lxd/unix.socket (Stream)
   CGroup: /system.slice/snap.lxd.daemon.unix.socket

Jul 27 23:31:04 hetz-hel1 systemd[1]: Listening on Socket unix for snap application lxd.daemon.
```

Now the debug gives
```
t=2019-07-28T13:33:21+0000 lvl=dbug msg="Connecting to a local LXD over a Unix socket" 
t=2019-07-28T13:33:21+0000 lvl=dbug msg="Sending request to LXD" etag= method=GET url=http://unix.socket/1.0
t=2019-07-28T13:33:21+0000 lvl=info msg="LXD 3.15 is starting in normal mode" path=/var/snap/lxd/common/lxd
t=2019-07-28T13:33:21+0000 lvl=info msg="Kernel uid/gid map:" 
t=2019-07-28T13:33:21+0000 lvl=info msg=" - u 0 0 4294967295" 
t=2019-07-28T13:33:21+0000 lvl=info msg=" - g 0 0 4294967295" 
t=2019-07-28T13:33:21+0000 lvl=info msg="Configured LXD uid/gid map:" 
t=2019-07-28T13:33:21+0000 lvl=info msg=" - u 0 1000000 1000000000" 
t=2019-07-28T13:33:21+0000 lvl=info msg=" - g 0 1000000 1000000000" 
t=2019-07-28T13:33:21+0000 lvl=info msg="Kernel features:" 
t=2019-07-28T13:33:21+0000 lvl=info msg=" - netnsid-based network retrieval: no" 
t=2019-07-28T13:33:21+0000 lvl=info msg=" - uevent injection: no" 
t=2019-07-28T13:33:21+0000 lvl=info msg=" - seccomp listener: no" 
t=2019-07-28T13:33:21+0000 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2019-07-28T13:33:21+0000 lvl=info msg=" - shiftfs support: no" 
t=2019-07-28T13:33:21+0000 lvl=info msg="Initializing local database" 
t=2019-07-28T13:33:21+0000 lvl=dbug msg="Initializing database gateway" 
t=2019-07-28T13:33:21+0000 lvl=dbug msg="Start database node" address=W.X.Y.Z:8443 id=1
t=2019-07-28T13:33:21+0000 lvl=dbug msg="Connecting to a local LXD over a Unix socket" 
t=2019-07-28T13:33:21+0000 lvl=dbug msg="Sending request to LXD" etag= method=GET url=http://unix.socket/1.0
t=2019-07-28T13:33:21+0000 lvl=dbug msg="Detected stale unix socket, deleting" 
t=2019-07-28T13:33:21+0000 lvl=dbug msg="Detected stale unix socket, deleting" 
t=2019-07-28T13:33:21+0000 lvl=info msg="Starting /dev/lxd handler:" 
t=2019-07-28T13:33:21+0000 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2019-07-28T13:33:21+0000 lvl=info msg="REST API daemon:" 
t=2019-07-28T13:33:21+0000 lvl=info msg=" - binding Unix socket" socket=/var/snap/lxd/common/lxd/unix.socket
t=2019-07-28T13:33:21+0000 lvl=info msg=" - binding TCP socket" socket=W.X.Y.Z:8443
t=2019-07-28T13:33:21+0000 lvl=info msg="Initializing global database" 
t=2019-07-28T13:33:21+0000 lvl=dbug msg="Found cert" name=0
t=2019-07-28T13:33:21+0000 lvl=dbug msg="Found cert" name=0
t=2019-07-28T13:33:21+0000 lvl=dbug msg="Dqlite: connected address=W.X.Y.Z:8443 attempt=0" 
t=2019-07-28T13:33:22+0000 lvl=dbug msg="Found cert" name=0
t=2019-07-28T13:33:22+0000 lvl=dbug msg="Found cert" name=0
t=2019-07-28T13:33:26+0000 lvl=dbug msg="Dqlite: closing client" 
t=2019-07-28T13:33:26+0000 lvl=dbug msg="Database error: &errors.errorString{s:\"driver: bad connection\"}" 
t=2019-07-28T13:33:26+0000 lvl=dbug msg="Retry failed db interaction (driver: bad connection)" 
t=2019-07-28T13:33:26+0000 lvl=dbug msg="Found cert" name=0
t=2019-07-28T13:33:26+0000 lvl=dbug msg="Found cert" name=0
t=2019-07-28T13:33:26+0000 lvl=dbug msg="Dqlite: connected address=W.X.Y.Z:8443 attempt=0" 
t=2019-07-28T13:33:26+0000 lvl=dbug msg="Database error: failed to update node version info: database is locked" 
t=2019-07-28T13:33:26+0000 lvl=dbug msg="Retry failed db interaction (failed to update node version info: database is locked)" 
t=2019-07-28T13:33:27+0000 lvl=dbug msg="Database error: failed to update node version info: database is locked" 
t=2019-07-28T13:33:27+0000 lvl=dbug msg="Retry failed db interaction (failed to update node version info: database is locked)" 
t=2019-07-28T13:33:27+0000 lvl=dbug msg="Database error: failed to update node version info: database is locked" 
t=2019-07-28T13:33:27+0000 lvl=dbug msg="Retry failed db interaction (failed to update node version info: database is locked)" 
t=2019-07-28T13:33:27+0000 lvl=dbug msg="Database error: failed to update node version info: database is locked" 
t=2019-07-28T13:33:27+0000 lvl=dbug msg="Retry failed db interaction (failed to update node version info: database is locked)" 
t=2019-07-28T13:33:27+0000 lvl=eror msg="Failed to start the daemon: failed to open cluster database: failed to ensure schema: failed to update node version info: database is locked" 
t=2019-07-28T13:33:27+0000 lvl=info msg="Starting shutdown sequence" 
t=2019-07-28T13:33:27+0000 lvl=info msg="Stopping REST API handler:" 
t=2019-07-28T13:33:27+0000 lvl=info msg=" - closing socket" socket=W.X.Y.Z:8443
t=2019-07-28T13:33:27+0000 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/unix.socket
t=2019-07-28T13:33:27+0000 lvl=info msg="Stopping /dev/lxd handler:" 
t=2019-07-28T13:33:27+0000 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2019-07-28T13:33:27+0000 lvl=dbug msg="Stop database gateway" 
t=2019-07-28T13:33:27+0000 lvl=dbug msg="Not unmounting temporary filesystems (containers are still running)" 
Error: failed to open cluster database: failed to ensure schema: failed to update node version info: database is locked
```

Any idea what's going on?

**Comment by rigred** [comment]
Ran another `snap restart lxd` and then ran `sudo lxd --debug --group lxd 2>&1 | tee lxd_debug_4.log` While this is running I can access lxc commands again, albeit responses are very slowl (I presume due to the debug output)
[lxd_debug_4.tar.gz](https://github.com/lxc/lxd/files/3439221/lxd_debug_4.tar.gz)

**Comment by spirritus** [comment]
#ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master eno1br1 state UP mode DEFAULT group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
4: eno3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
5: eno4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
6: eno1br1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
8: vnet1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master eno1br1 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
13: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master eno1br1 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff


#ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master eno1br1 state UP group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
    inet 192.168.43.15/24 brd 192.168.43.255 scope global eno2
       valid_lft forever preferred_lft forever
4: eno3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
    inet 192.168.90.15/24 brd 192.168.90.255 scope global eno3
       valid_lft forever preferred_lft forever
5: eno4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
6: eno1br1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.15/24 brd 192.168.1.255 scope global eno1br1
       valid_lft forever preferred_lft forever
8: vnet1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master eno1br1 state UNKNOWN group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff
13: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master eno1br1 state UNKNOWN group default qlen 1000
    link/ether zz:zz:zz:zz:zz:zz brd ff:ff:ff:ff:ff:ff


#netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2676/sshd
tcp        0      0 0.0.0.0:4505            0.0.0.0:*               LISTEN      3794/python2
tcp        0      0 0.0.0.0:4506            0.0.0.0:*               LISTEN      3802/python2
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      2945/apache2
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      3142/smbd
tcp        0      0 0.0.0.0:42813           0.0.0.0:*               LISTEN      2321/rpc.mountd
tcp        0      0 0.0.0.0:36669           0.0.0.0:*               LISTEN      2321/rpc.mountd
tcp        0      0 0.0.0.0:53215           0.0.0.0:*               LISTEN      2321/rpc.mountd
tcp        0      0 0.0.0.0:2049            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3142            0.0.0.0:*               LISTEN      2306/apt-cacher-ng
tcp        0      0 0.0.0.0:9418            0.0.0.0:*               LISTEN      2675/git-daemon
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      3142/smbd
tcp        0      0 127.0.0.1:5900          0.0.0.0:*               LISTEN      29590/qemu-system-x
tcp        0      0 127.0.0.1:5901          0.0.0.0:*               LISTEN      20939/qemu-system-x
tcp        0      0 0.0.0.0:43023           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/init
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2945/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      2676/sshd
tcp6       0      0 :::39771                :::*                    LISTEN      2321/rpc.mountd
tcp6       0      0 :::445                  :::*                    LISTEN      3142/smbd
tcp6       0      0 :::2049                 :::*                    LISTEN      -
tcp6       0      0 :::43333                :::*                    LISTEN      -
tcp6       0      0 :::3142                 :::*                    LISTEN      2306/apt-cacher-ng
tcp6       0      0 :::54665                :::*                    LISTEN      2321/rpc.mountd
tcp6       0      0 :::46697                :::*                    LISTEN      2321/rpc.mountd
tcp6       0      0 :::9418                 :::*                    LISTEN      2675/git-daemon
tcp6       0      0 :::139                  :::*                    LISTEN      3142/smbd
tcp6       0      0 :::111                  :::*                    LISTEN      1/init
udp        0      0 0.0.0.0:47071           0.0.0.0:*                           2321/rpc.mountd
udp        0      0 0.0.0.0:56339           0.0.0.0:*                           2321/rpc.mountd
udp        0      0 0.0.0.0:67              0.0.0.0:*                           2695/dhcpd
udp        0      0 0.0.0.0:69              0.0.0.0:*                           2644/in.tftpd
udp        0      0 0.0.0.0:111             0.0.0.0:*                           1/init
udp        0      0 192.168.90.15:123       0.0.0.0:*                           2648/ntpd
udp        0      0 192.168.1.15:123        0.0.0.0:*                           2648/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           2648/ntpd
udp        0      0 192.168.1.255:137       0.0.0.0:*                           2328/nmbd
udp        0      0 192.168.1.15:137        0.0.0.0:*                           2328/nmbd
udp        0      0 192.168.43.255:137      0.0.0.0:*                           2328/nmbd
udp        0      0 192.168.43.15:137       0.0.0.0:*                           2328/nmbd
udp        0      0 192.168.90.255:137      0.0.0.0:*                           2328/nmbd
udp        0      0 192.168.90.15:137       0.0.0.0:*                           2328/nmbd
udp        0      0 0.0.0.0:137             0.0.0.0:*                           2328/nmbd
udp        0      0 192.168.1.255:138       0.0.0.0:*                           2328/nmbd
udp        0      0 192.168.1.15:138        0.0.0.0:*                           2328/nmbd
udp        0      0 192.168.43.255:138      0.0.0.0:*                           2328/nmbd
udp        0      0 192.168.43.15:138       0.0.0.0:*                           2328/nmbd
udp        0      0 192.168.90.255:138      0.0.0.0:*                           2328/nmbd
udp        0      0 192.168.90.15:138       0.0.0.0:*                           2328/nmbd
udp        0      0 0.0.0.0:138             0.0.0.0:*                           2328/nmbd
udp        0      0 0.0.0.0:58089           0.0.0.0:*                           2321/rpc.mountd
udp        0      0 0.0.0.0:58858           0.0.0.0:*                           -
udp        0      0 0.0.0.0:2049            0.0.0.0:*                           -
udp6       0      0 :::38811                :::*                                -
udp6       0      0 :::48991                :::*                                2321/rpc.mountd
udp6       0      0 :::111                  :::*                                1/init
udp6       0      0 :::33770                :::*                                2321/rpc.mountd
udp6       0      0 :::42064                :::*                                2321/rpc.mountd
udp6       0      0 :::2049                 :::*                                -
raw        0      0 0.0.0.0:1               0.0.0.0:*               7           2695/dhcpd
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     17719    2306/apt-cacher-ng   /run/apt-cacher-ng/socket
unix  2      [ ACC ]     STREAM     LISTENING     356635   20939/qemu-system-x  /var/lib/libvirt/qemu/domain-2-data2/monitor.sock
unix  2      [ ACC ]     STREAM     LISTENING     356646   20939/qemu-system-x  /var/lib/libvirt/qemu/channel/target/domain-2-data2/org.qemu.guest_agent.0
unix  2      [ ACC ]     STREAM     LISTENING     60536    21898/systemd        /run/user/0/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     60542    21898/systemd        /run/user/0/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     894      1/init               /var/run/libvirt/virtlockd-admin-sock
unix  2      [ ACC ]     STREAM     LISTENING     60545    21898/systemd        /run/user/0/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     STREAM     LISTENING     898      1/init               /run/snapd.socket

**Comment by stgraber** [comment]
@spirritus is yours also a multi-node cluster or is it a single node that happens to have cluster enabled?

**Comment by spirritus** [comment]
That would be a single node that happens to have cluster enabled.

**Comment by spirritus** [comment]
My coworker "fixed" it by deleting snap and reinstalling lxd.

**Comment by stgraber** [comment]
Do you mean your coworker had the same issue on another system or was working on the same system you were and reinstalled it?

Just wondering if you still have access to the broken system as a tarball of /var/snap/lxd/common/lxd/database would have been useful for us to debug this further.

**Comment by spirritus** [comment]
He was working on the same system. So we do not have the broken system anymore. Should this error resurface I am sure to post the db here :-)

But realy, all I idid was move the network from eno1 to eno1br1 and lxd was not reachable anymore.

**Comment by stgraber** [comment]
Yeah, that's an odd one because LXD doesn't care about interfaces, it only cares about the IP, so I suspect your change is actually unrelated to the failure.

Since we don't have access to logs, database or a broken system, there's little we can do at this point. I'm closing this, but should it happen again to you or anyone else, please comment here and we will re-open it.
