### ISSUE TITLE
Inconsistent support of CLI flag --format

### ISSUE THREAD

**Issue by AdamIsrael** [lxc/lxd#6034]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 19.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.0.0-21-generic
   * LXC version: 3.15
   * LXD version: 3.15
   * Storage backend in use: zfs

# Issue description

LXD inconsistently offers the `--format` flag amongst its CLI commands. It's convenient to use the flag to use when checking lxc programatically (without using the API directly). 

The commands that support `--format`
- lxc list
- lxc image list
- lxc network list
- lxc profile list
- lxc remote list

The commands that don't support `--format`
- lxc alias list
- lxc cluster list
- lxc project list
- lxc snapshot list
- lxc storage list

# Steps to reproduce

```
$ lxc storage list --format json
Error: unknown flag: --format
```

**Comment by stgraber** [comment]
Yep, it's something I've been meaning to sort out for a while, ideally we'd move them all to a shared set of functions to handle the various outputs.

I may take a look at it next week, see if we can't sort that out in time for 3.16.

**Comment by lucrus73** [comment]
I'm on LXD 4.2 installed from snap and I still see this issue. Is it normal?

**Comment by stgraber** [comment]
I've just checked and all our `list` commands with the exception of `config device list` (which doesn't have a list structure to dump in the first place) all support --format.

**Comment by lucrus73** [comment]
sorry, my fault, you can safely ignore my previous comment.
