### ISSUE TITLE
Error: Failed to start dqlite server: run failed with 13

### ISSUE THREAD

**Issue by julian-klode** [lxc/lxd#6038]
# Required information

 * Distribution:Ubuntu
 * Distribution version:eoan
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.2.0-9-generic
   * LXC version: 3.15
   * LXD version: 3.15 (11437)
   * Storage backend in use: btrfs

# Issue description

Yesterday's upgrade to 3.15 (11437) broke stuff, lxd does not start

```
Aug 01 19:26:31 jak-t480s lxd.daemon[15691]: t=2019-08-01T19:26:31+0200 lvl=eror msg="Failed to start the daemon: Failed to start dqlite server: run failed with 13"
Aug 01 19:26:31 jak-t480s lxd.daemon[15691]: Error: Failed to start dqlite server: run failed with 13
Aug 01 19:26:31 jak-t480s lxd.daemon[15691]: => LXD failed to start
Aug 01 19:26:32 jak-t480s systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=1/FAILURE
Aug 01 19:26:32 jak-t480s systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
Aug 01 19:26:32 jak-t480s systemd[1]: snap.lxd.daemon.service: Service RestartSec=100ms expired, scheduling restart.
Aug 01 19:26:32 jak-t480s systemd[1]: snap.lxd.daemon.service: Scheduled restart job, restart counter is at 2.
```

# Steps to reproduce

Run lxc

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log
[lxd.log](https://github.com/lxc/lxd/files/3460759/lxd.log)
 - [ ] Output of the client with --debug 
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue) [lxd-debug.log](https://github.com/lxc/lxd/files/3460760/lxd-debug.log)

**Comment by julian-klode** [comment]
Reverting to the previous version did not help, though.

**Comment by julian-klode** [comment]
Rebooting did not help either.

**Comment by adamryczkowski** [comment]
I have the same error. Also from yesterday.

```
$ sudo lxd --debug --group lxd
DBUG[08-02|15:16:15] Connecting to a local LXD over a Unix socket 
DBUG[08-02|15:16:15] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
INFO[08-02|15:16:15] LXD 3.15 is starting in normal mode      path=/var/snap/lxd/common/lxd
INFO[08-02|15:16:15] Kernel uid/gid map: 
INFO[08-02|15:16:15]  - u 0 0 4294967295 
INFO[08-02|15:16:15]  - g 0 0 4294967295 
INFO[08-02|15:16:15] Configured LXD uid/gid map: 
INFO[08-02|15:16:15]  - u 0 1000000 1000000000 
INFO[08-02|15:16:15]  - g 0 1000000 1000000000 
WARN[08-02|15:16:15] CGroup memory swap accounting is disabled, swap limits will be ignored. 
INFO[08-02|15:16:15] Kernel features: 
INFO[08-02|15:16:15]  - netnsid-based network retrieval: no 
INFO[08-02|15:16:15]  - uevent injection: no 
INFO[08-02|15:16:15]  - seccomp listener: no 
INFO[08-02|15:16:15]  - unprivileged file capabilities: yes 
INFO[08-02|15:16:15]  - shiftfs support: no 
INFO[08-02|15:16:15] Initializing local database 
DBUG[08-02|15:16:15] Initializing database gateway 
DBUG[08-02|15:16:15] Start database node                      id=1 address=
EROR[08-02|15:16:15] Failed to start the daemon: Failed to start dqlite server: run failed with 13 
INFO[08-02|15:16:15] Starting shutdown sequence 
DBUG[08-02|15:16:15] Not unmounting temporary filesystems (containers are still running) 
```

**Comment by freeekanayaka** [comment]
It would be helpful to know for sure if the problem happened after an upgrade from 3.14 to 3.15, or post 3.15.

**Comment by freeekanayaka** [comment]
From inspecting the database, it seems that some files containing committed entries are missing.

**Comment by adamryczkowski** [comment]
@freeekanayaka If the fix is difficult, perhaps you can tell me, how can I salvage the containers?

**Comment by freeekanayaka** [comment]
@adamryczkowski a fix might prevent this from happening again in the future, but unfortunately it won't solve your situation. Your best bet is to remove all files named ```MMM-NNN``` and leave only the ones named ```metadata*```, ```db.bin*``` and ```snapshot*```. Hopefully those snapshots still have the data about your containers.

**Comment by adamryczkowski** [comment]
Thanks. Everything works now.

**Comment by stgraber** [comment]
Moved to https://github.com/canonical/raft/issues/57
