### ISSUE TITLE
Signing DCO on GitHub is outraging

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#609]
Because it appears more that once, let me just say here why I am not sending patches. The rationale is described https://www.joyent.com/blog/broadening-node-js-contributions The reason that "Lots of projects" use CLA and DCO is not an argument for me. Every community should defend its interests. I don't want to deal with lawyers and ask permission from my slave drivers when I wish to contribute stuff to the open source projects on the Internet. I reviewed the guidelines that say that you don't accept the work of other people and still submitted a PR, and that should be enough. If my company decides to sue you, I will be guilty with DCO and CLA, or without it. It is me, who will pay in any case, so please, don't make it worse.

**Comment by stgraber** [comment]
We've had a few similar discussions in various places (LXD, LXC, Linux kernel, ...) but it's not something we're willing to negotiate so unfortunately it's a case of either you follow the DCO or your contribution won't be included.

For anyone else following this issue, note that the DCO isn't a CLA, that is, it doesn't cause you to re-license your code, attribute your copyright to another entity or interfere with any patent you may be related to in any way.

The only thing the DCO does is make you confirm that you are the author of the code you are contributing to the project and that you are allowed to contribute this code under the project's license. The first part is for simple cases of copy/paste. The latter is to cover the case of contributions during work time, where your employer is typically the copyright holder of any contribution you do during work time.

So in practice the DCO shouldn't make any difference for a contributor who's contributing his own work and if during work time, is allowed to do so by his employer. It however does make a difference in tracking down who contributed what and confirming that as far as the project is concerned, all our contributions were legal.

**Comment by tych0** [comment]
On Fri, May 08, 2015 at 08:34:50AM -0700, anatoly techtonik wrote:
> Because it appears more that once, let me just say here why I am not sending patches. The rationale is described https://www.joyent.com/blog/broadening-node-js-contributions 

This link mentions nothing about DCO.

I'll say again: the DCO (developer certificate of origin) is not a CLA
(contributor license agreement), and it is worth understanding the
difference before you refuse to contribute to the project. The DCO is
essentially a no-op in terms of copyright assignment, where as most
CLAs are very much not.

> The reason that "Lots of projects" use CLA and DCO is not an argument for me. Every community should defend its interests. I don't want to deal with lawyers and ask permission from my slave drivers when I wish to contribute stuff to the open source projects on the Internet. I reviewed the guidelines that say that you don't accept the work of other people and still submitted a PR, and that should be enough. If my company decides to sue you, I will be guilty with DCO and CLA, or without it. It is me, who will pay in any case, so please, don't make it worse.

This argument makes common sense, but unfortunately lawyers have
determined that it may not make legal sense, which is why the DCO was
created (and indeed, integrated as a feature into git via git commit
-s).

The project is not going to change its policies, so I'll go ahead and
close this issue. Feel free to mail me offline if you'd like more
discussion on what the difference between DCO and CLA is.

**Comment by techtonik** [comment]
> This argument makes common sense, but unfortunately lawyers have
determined that it may not make legal sense

Because lawyers need to keep their jobs?

I agree that from copyright law, the CLA and DCO are different. But the issue is that you don't trust people and treat them as corporate slaves, who are dumb enough to skip reading project guidelines before investing time in studying and patching the code.

P.S. Didn't know `git commit -s`. Might be useful.

**Comment by techtonik** [comment]
I mean it is enough to you just say  "Please, don't send us code that is not yours, because other corporations [might sue us](http://en.wikipedia.org/wiki/Oracle_America,_Inc._v._Google,_Inc.)".

**Comment by tych0** [comment]
On May 10, 2015 3:05 AM, "anatoly techtonik" <notifications@github.com>
wrote:
>
> I mean it is enough to you just say "Please, don't send us code that is
not yours, because other corporations might sue us".

No, the point is that it's not. That's the reason the DCO was created. In a
perfect world perhaps, but not in this one :-)

**Comment by techtonik** [comment]
> No, the point is that it's not. That's the reason the DCO was created. In a perfect world perhaps, but not in this one :-)

Before becoming perfect, that world had open ticket about the issue. And in this world people are closing all such tickets. It has no chance.
