### ISSUE TITLE
LXD config non-maintainable when daemon wontstart 

### ISSUE THREAD

**Issue by maelstrom256** [lxc/lxd#6096]
# Required information

 * Distribution: Ubuntu bionic
 * Distribution version: 18.04.3 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.0.0-23-lowlatency
   * LXC version: 
   * LXD version: 3.0.3
   * Storage backend in use: ZFS

# Issue description

When daemon encounters a storage error it try to be smart, but gone completely unconfigurable.
History:
* Host installed as Root-on-ZFS, with separate `hostname-zroot\lxd` dataset for LXD only.
* Initially LXD configured to use this dataset, inside host zpool
* Host migrated from two zpools (`hostname-zroot` and `hostname-srv`) to one, named `hostname`
* Then, LXD daemon wont nor start nor configure

E.g.: another etc'less tool I use is `targetcli`. It has issues too after pool moving, but it start and keep himself configurable. More then, it support export and import config, so issue fixed remotely with simple `sed`

# Steps to reproduce

 1. Create any storage pool
 2. Stop LXD
 3. Rename or move pool by any manner, keeping data safe and accessible
 4. Start LXD

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
> t=2019-08-17T21:34:58+0300 lvl=info msg="Initializing storage pools"
> t=2019-08-17T21:34:58+0300 lvl=eror msg="Failed to start the daemon: ZFS storage pool \"hostname-zroot/lxd\" could not be imported: cannot import 'hostname-zroot': no such pool available\n"
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
The normal way to do what you did with LXD would have been:
 - Setup your new zpool
 - Add it as a new storage pool to LXD
 - Move the containers from the old to the new pool with `lxc move --storage`
 - Once empty, delete the old pool from LXD

Manually reshuffling things behind LXD's back, while possible if done very carefully, isn't something we support.

It is possible to have LXD update its database records on startup, to fix such issues.
Documentation for that is available at https://linuxcontainers.org/lxd/docs/master/database

In your case, you'll want a `patch.global.sql` and need something like:
 - "UPDATE storage_pools_config SET value='hostname/lxd' WHERE value='hostname-zroot/lxd';"

Restarting LXD will then have it update the database prior to bringing up the pool, which should then work properly. This does assume you've properly move the data, including all ZFS properties, that the mount points weren't altered, ...

**Comment by maelstrom256** [comment]
Thanks for quick reply! It helps, now daemon and all containers run correctly.

But, when you suddenly need to migrate, there no time to learn every package manuals. Therefore, manuals usually do not describe caveats.
And more, no one can expect from high quality software that it can just struck, leave you alone with nothing just some kind of non-editable config.

It just dark pattern of app desing, and it matter of the issue. App may use any kind of configuration storage, but it must be always configurable. When app uses text-like config it may struck freely. When app have external editor for config, it may struck also. But when app must be only full-throttle-run to be able to config - it leads every unusual condition to become disaster.

Another thing: your link to database contains key enumeration. I found these tables every time searching ways to restore, but they intended to use `lxc`, which expect `lxd` up and running. And without any clues about SQL-patches or `sqlite3`. So they completely useless in my case. Theremore, without editable db -- it impossible to perform some investigation by my own. So one and only way LXD-team leave to user -- just to pray for a patch.

Thanks a lot again, for your assistance.
