### ISSUE TITLE
Export/Import messes around with my uids?

### ISSUE THREAD

**Issue by m4ntic0r** [lxc/lxd#6097]
I have a really frustrating problem..

I have a debian 9 host, with lxd v. 3.16 and some containers with debian 10 buster. Storage is dir format. All containers are set to "lxc config set name security.privileged true"

I backup my containers with
/snap/bin/lxc export name1 /backup/container/name1-$datum.tar.gz --container-only
/snap/bin/lxc export name2 /backup/container/name2-$datum.tar.gz --container-only

Now i have a new host, debian 10, lxd 3.16 and want to restore my backups. I used lxc import /path/to/tar.gz and imported the containers, but if i start them, a lot of services are not running. It seems that the file permissions in /var/snap/lxd/common/lxd/container.. **are totally fucked up**.

e.g.:
on debian 9 host in /var/snap/lxd/common/lxd/containers/proxy/rootfs/var/spool/postfix
https://chevereto.mm-vault.de/images/2019/08/18/before.jpg

after import on debian 10 host
https://chevereto.mm-vault.de/images/2019/08/18/after.jpg

now within the container postfix cannot start, because of the uid 100 the files and folders are owned by a totally different user..

**Comment by stgraber** [comment]
Sent a fix, though this will sadly only fix newer backups, it won't fix unpacking old ones.

One workaround you may be able to use as a one off way of loading your backups is to temporarily alter /etc/passwd and /etc/group on the target system to match the source server, this will then cause tar to unpack with the right uid/gid.

**Comment by stgraber** [comment]
Worth noting that backups done using --optimized-storage will not be impacted by this issue.
