### ISSUE TITLE
snap lxd refresh stuck on 'Copy snap "lxd" data'

### ISSUE THREAD

**Issue by kevinkk525** [lxc/lxd#6098]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 19.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.0.0-23-generic
   * LXC version:
   * LXD version: 3.16
   * Storage backend in use: zfs

# Issue description

snap tried to refresh lxd to the latest version and is stuck during the process of 'Copy snap "lxd" data' since soon 12 hours:
```
>>>snap change 8
Status  Spawn                Ready                Summary
Done    today at 06:40 CEST  today at 06:40 CEST  Ensure prerequisites for "lxd" are available
Done    today at 06:40 CEST  today at 06:40 CEST  Download snap "lxd" (11672) from channel "stable/ubuntu-19.04"
Done    today at 06:40 CEST  today at 06:40 CEST  Fetch and check assertions for snap "lxd" (11672)
Done    today at 06:40 CEST  today at 06:40 CEST  Mount snap "lxd" (11672)
Done    today at 06:40 CEST  today at 06:40 CEST  Run pre-refresh hook of "lxd" snap if present
Done    today at 06:40 CEST  today at 07:10 CEST  Stop snap "lxd" services
Done    today at 06:40 CEST  today at 07:10 CEST  Remove aliases for snap "lxd"
Done    today at 06:40 CEST  today at 07:10 CEST  Make current revision for snap "lxd" unavailable
Doing   today at 06:40 CEST  -                    Copy snap "lxd" data
Do      today at 06:40 CEST  -                    Setup snap "lxd" (11672) security profiles
Do      today at 06:40 CEST  -                    Make snap "lxd" (11672) available to the system
Do      today at 06:40 CEST  -                    Automatically connect eligible plugs and slots of snap "lxd"
Do      today at 06:40 CEST  -                    Set automatic aliases for snap "lxd"
Do      today at 06:40 CEST  -                    Setup snap "lxd" aliases
Do      today at 06:40 CEST  -                    Run post-refresh hook of "lxd" snap if present
Do      today at 06:40 CEST  -                    Start snap "lxd" (11672) services
Do      today at 06:40 CEST  -                    Remove data for snap "lxd" (11633)
Do      today at 06:40 CEST  -                    Remove snap "lxd" (11633) from the system
Do      today at 06:40 CEST  -                    Clean up "lxd" (11672) install
Do      today at 06:40 CEST  -                    Run configure hook of "lxd" snap if present
Doing   today at 06:40 CEST  -                    Consider re-refresh of "lxd"
```

I have several lxd containers running which all still run although I can't access them anymore directly as no lxd or lxc package is installed anymore until this process finishes.
The server load is inscredibly high (29 on 8 cores) but the IO is low and the server still reacts fast (except for commands like htop and iotop that won't even open after 10 minutes).
My containers are not big so moving any data wouldn't take long.

I have no idea how to resolve this, the data available online is not helpful and I don't want to break my setup. Had I known that snap is that unreliable, I'd have never chosen this installation method.

EDIT: The high load was due to a faulty HDD that I had to kill. Now everything is back to normal but snapd is still stuck there. I can see it using the CPU but that's all..

# Steps to reproduce

 1. Nothing, just snap deciding to update lxd

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 t=2019-08-18T06:40:27+0200 lvl=info msg="Received 'terminated signal', exiting" 
t=2019-08-18T06:40:27+0200 lvl=info msg="Starting shutdown sequence" 
t=2019-08-18T06:40:27+0200 lvl=info msg="Stopping REST API handler:" 
t=2019-08-18T06:40:27+0200 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/unix.socket
t=2019-08-18T06:40:27+0200 lvl=info msg="Stopping /dev/lxd handler:" 
t=2019-08-18T06:40:27+0200 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2019-08-18T06:40:27+0200 lvl=info msg="Closing the database"
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by kevinkk525** [comment]
Oddly enough after killing the non responding external hdd (that wasn't even connected to any lxd container in any way) the process continued but now has a different error:

Status  Spawn                Ready                Summary
Done    today at 06:40 CEST  today at 20:07 CEST  Ensure prerequisites for "lxd" are available
Undone  today at 06:40 CEST  today at 20:07 CEST  Download snap "lxd" (11672) from channel "stable/ubuntu-19.04"
Done    today at 06:40 CEST  today at 20:07 CEST  Fetch and check assertions for snap "lxd" (11672)
Undone  today at 06:40 CEST  today at 20:07 CEST  Mount snap "lxd" (11672)
Undone  today at 06:40 CEST  today at 20:07 CEST  Run pre-refresh hook of "lxd" snap if present
Undone  today at 06:40 CEST  today at 20:07 CEST  Stop snap "lxd" services
Undone  today at 06:40 CEST  today at 20:07 CEST  Remove aliases for snap "lxd"
Undone  today at 06:40 CEST  today at 20:07 CEST  Make current revision for snap "lxd" unavailable
Error   today at 06:40 CEST  today at 20:07 CEST  Copy snap "lxd" data
Hold    today at 06:40 CEST  today at 20:07 CEST  Setup snap "lxd" (11672) security profiles
Hold    today at 06:40 CEST  today at 20:07 CEST  Make snap "lxd" (11672) available to the system
Hold    today at 06:40 CEST  today at 20:07 CEST  Automatically connect eligible plugs and slots of snap "lxd"
Hold    today at 06:40 CEST  today at 20:07 CEST  Set automatic aliases for snap "lxd"
Hold    today at 06:40 CEST  today at 20:07 CEST  Setup snap "lxd" aliases
Hold    today at 06:40 CEST  today at 20:07 CEST  Run post-refresh hook of "lxd" snap if present
Hold    today at 06:40 CEST  today at 20:07 CEST  Start snap "lxd" (11672) services
Hold    today at 06:40 CEST  today at 20:07 CEST  Remove data for snap "lxd" (11633)
Hold    today at 06:40 CEST  today at 20:07 CEST  Remove snap "lxd" (11633) from the system
Hold    today at 06:40 CEST  today at 20:07 CEST  Clean up "lxd" (11672) install
Hold    today at 06:40 CEST  today at 20:07 CEST  Run configure hook of "lxd" snap if present
Done    today at 06:40 CEST  today at 20:07 CEST  Consider re-refresh of "lxd"

......................................................................
Copy snap "lxd" data

2019-08-18T20:07:14+02:00 ERROR cannot copy "/home/kevin/snap/lxd/11643" to "/home/kevin/snap/lxd/11672": failed to sync: "" (-1)

But manually doing the refresh solved the problem.

**Comment by Ferdinanddb** [comment]
I'm having a similar issue on a 3 nodes cluster.. Only 1 node out of 3 managed to do the auto-refresh. 
The auto-refresh on each node was done on 3 different dates and the 2 nodes that failed have this similar  `snap change ID` output :
```
Status  Spawn                     Ready                     Summary
Done    5 days ago, at 22:46 UTC  5 days ago, at 22:46 UTC  Ensure prerequisites for "lxd" are available
Done    5 days ago, at 22:46 UTC  5 days ago, at 22:46 UTC  Download snap "lxd" (11643) from channel "stable/ubuntu-18.10"
Done    5 days ago, at 22:46 UTC  5 days ago, at 22:46 UTC  Fetch and check assertions for snap "lxd" (11643)
Done    5 days ago, at 22:46 UTC  5 days ago, at 22:46 UTC  Mount snap "lxd" (11643)
Done    5 days ago, at 22:46 UTC  5 days ago, at 22:46 UTC  Run pre-refresh hook of "lxd" snap if present
Done    5 days ago, at 22:46 UTC  5 days ago, at 22:46 UTC  Stop snap "lxd" services
Done    5 days ago, at 22:46 UTC  5 days ago, at 22:46 UTC  Remove aliases for snap "lxd"
Done    5 days ago, at 22:46 UTC  5 days ago, at 22:46 UTC  Make current revision for snap "lxd" unavailable
Doing   5 days ago, at 22:46 UTC  -                         Copy snap "lxd" data
Do      5 days ago, at 22:46 UTC  -                         Setup snap "lxd" (11643) security profiles
Do      5 days ago, at 22:46 UTC  -                         Make snap "lxd" (11643) available to the system
Do      5 days ago, at 22:46 UTC  -                         Automatically connect eligible plugs and slots of snap "lxd"
Do      5 days ago, at 22:46 UTC  -                         Set automatic aliases for snap "lxd"
Do      5 days ago, at 22:46 UTC  -                         Setup snap "lxd" aliases
Do      5 days ago, at 22:46 UTC  -                         Run post-refresh hook of "lxd" snap if present
Do      5 days ago, at 22:46 UTC  -                         Start snap "lxd" (11643) services
Do      5 days ago, at 22:46 UTC  -                         Remove data for snap "lxd" (11595)
Do      5 days ago, at 22:46 UTC  -                         Remove snap "lxd" (11595) from the system
Do      5 days ago, at 22:46 UTC  -                         Clean up "lxd" (11643) install
Do      5 days ago, at 22:46 UTC  -                         Run configure hook of "lxd" snap if present
Doing   5 days ago, at 22:46 UTC  -                         Consider re-refresh of "lxd"
```
Also, I use ZFS and it seems that there are a lot of writes on the disk using `top` command (might be linked to the `Copy snap "lxd" data` ?)

I can't do the `snap refresh lxd --stable` since it's disabled and I can't enable it, output is : `error: cannot refresh "lxd": refreshing disabled snap "lxd" not supported` 

I can't neither do snap restart lxd.daemon, output is : `error: snap "lxd" has "auto-refresh" change in progress`

Do you know how could I get off this loop?

**Comment by stgraber** [comment]
You'll want to do `snap changes` then for anything that's stuck, do `snap abort`, give snapd some time to give up on it, then attempt a refresh again.

**Comment by Ferdinanddb** [comment]
Thank you for your answer. How much times would it takes for snapd to give up? Because nothing changed since 20 minutes. 
```
$ sudo snap enable lxd 
error: snap "lxd" has "auto-refresh" change in progress
$ sudo snap refresh lxd --stable
error: cannot refresh "lxd": refreshing disabled snap "lxd" not supported
```

I can provide some other logs if you want : 
from `top` : 
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                   
32508 root      20   0       0      0      0 R 100.0   0.0   0:44.00 kworker/u112:10+flush-zfs-94                                                                                                                                              
16584 root      20   0       0      0      0 R 100.0   0.0  33279:12 kworker/u112:13+flush-zfs-20                                                                                                                                              
39147 1000000   20   0 1879600  59036   7256 S  27.2   0.0   2082:18 python                                                                                                                                                                    
36623 1000000   20   0 2007632  75552   7012 S  10.5   0.0 879:16.55 python                                                                                                                                                                    
15243 1000000   20   0 2022456  71560   7216 S   9.8   0.0   1118:59 python                                                                                                                                                                    
32890 root      20   0 3048936 144004  35404 S   8.5   0.1   2592:34 kubelet                                                                                                                                                                   
 8242 root      20   0 3736108 729276    920 S   7.9   0.4   2135:16 lxcfs                                                                                                                                                                     
14573 root      20   0 2419612 106284  25964 S   4.6   0.1   1196:14 dockerd                                                                                                                                                                   
10833 1000000   20   0 1806900  67272   7348 S   4.3   0.0 465:06.23 python                                                                                                                                                                    
52262 root      20   0  227848  11068   6236 S   4.3   0.0 837:22.35 systemd                                                                                                                                                                   
18801 1000000   20   0 2316720  86192   7444 S   3.9   0.0   1177:42 python                                                                                                                                                                    
15157 1000000   20   0  221320  16956   5884 R   2.6   0.0   0:00.08 python                                                                                                                                                                    
56345 syslog    20   0   62828   4040   2940 S   2.3   0.0 487:24.31 dbus-daemon    
```

from `iostat` I can see that the two disks using ZFS are writing a lot.. 
```
Linux 4.18.0-21-generic (n3) 	08/21/19 	_x86_64_	(56 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           6.45    0.00    4.60    0.09    0.00   88.86

sda             726.54       135.40     17871.18  795645897 105014833656
sdb             729.33       134.98     17871.18  793156865 105014833656
```

**Comment by stgraber** [comment]
Well, that's odd. I'd say, try to abort any running task, give it a minute, then restart snapd itself (`systemctl restart snapd`), hopefully that will unstick things.

**Comment by Ferdinanddb** [comment]
Thanks for your quick answers. We decided to reboot all the nodes which failed the auto-refresh and everything is fine now, the LXD auto-refresh has been successful this time..!

**Comment by stgraber** [comment]
Okay, so bouncing snapd would likely have achieved the same.

If you have a bit of time, can you report this behavior on the snapcraft forum (forum.snapcraft.io).

**Comment by Ferdinanddb** [comment]
Just did the report on forum.snapcraft.io since now the problem is on the node that was working when the 2 other nodes were stuck... I will try what you said about restarting snapd.

**Comment by Ferdinanddb** [comment]
Just did what you mentionned about `systemctl restart snapd` after aborting running tasks and it worked. I also reported the issue on [snapcraft](https://forum.snapcraft.io/t/snap-auto-refresh-lxd-is-stuck-in-doing-status-since-2-days/13300). 

Could you please provide me some tips about using LXC with snap in a production environment? Cause it seems that the auto-refresh function of snap is mandatory but can be modified to happen one time per month for example.. If you have any tips about those aspects I am very interested..!

**Comment by stgraber** [comment]
You can configure a weekly maintenance window for normal refreshes:
  https://snapcraft.io/docs/system-options

For LXD, we've also introduced temporary tracks for our feature releases, so you could do:
 - snap refresh lxd --channel=3.17

Which will then keep the system on 3.17 indefinitely. To upgrade to 3.18, you'll then need to manually do `snap refresh lxd --channel=3.18`. This may be a good option for production environments.

Though you do need to keep in mind that we will not update/fix older LXD feature releases, so you should plan on upgrading to the next one shortly after it's available.

**Comment by lathiat** [comment]
For reference if others find this issue while research, I hit the same issue (stuck in phase: copy snap "lxd" data), filed a bug against snapd with the details:
https://bugs.launchpad.net/snappy/+bug/1943419

Also found a report of the same behaviour on the core snap:
https://bugs.launchpad.net/snappy/+bug/1843589
