### ISSUE TITLE
container fail to start, when /sys/class/net/bonding_masters exist

### ISSUE THREAD

**Issue by n3k2t1** [lxc/lxd#6106]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.2
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-50-generic
   * LXC version: 3.116
   * LXD version: 3.16
   * Storage backend in use: zfs

# Issue description
When exist bonding_masters file(not directory) under /sys/class/net, fail to read infiniband device information.

# Steps to reproduce

 1. Step one
 start container.
 lxc  start _container-name_

 2. Step two
 return error message.
 Error: Common start logic: open /sys/class/net/bonding_masters/device/resource: not a directory

 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
@n3k2t1 please can you provide the output to ```lxc config show NAME --expanded```

**Comment by stgraber** [comment]
Right, it's the weird sysfs behavior, you don't get no such file or directory so the existing check doesn't work.

**Comment by stgraber** [comment]
Sent a PR to sort this one out. I suspect the upcoming infiniband changes would also fix this by relying on the resources API that already has the suitable check, but fixing this first will let me cherry-pick the fix.

**Comment by tomponline** [comment]
Thanks @stgraber
