### ISSUE TITLE
Fscrypt path errors when mounted into container

### ISSUE THREAD

**Issue by chris-sanders** [lxc/lxd#6107]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 19.04
 * The output of "lxc info" or if that fails:

> To start your first container, try: lxc launch ubuntu:18.04
> 
> config: {}
> api_extensions:
> - storage_zfs_remove_snapshots
> - container_host_shutdown_timeout
> - container_stop_priority
> - container_syscall_filtering
> - auth_pki
> - container_last_used_at
> - etag
> - patch
> - usb_devices
> - https_allowed_credentials
> - image_compression_algorithm
> - directory_manipulation
> - container_cpu_time
> - storage_zfs_use_refquota
> - storage_lvm_mount_options
> - network
> - profile_usedby
> - container_push
> - container_exec_recording
> - certificate_update
> - container_exec_signal_handling
> - gpu_devices
> - container_image_properties
> - migration_progress
> - id_map
> - network_firewall_filtering
> - network_routes
> - storage
> - file_delete
> - file_append
> - network_dhcp_expiry
> - storage_lvm_vg_rename
> - storage_lvm_thinpool_rename
> - network_vlan
> - image_create_aliases
> - container_stateless_copy
> - container_only_migration
> - storage_zfs_clone_copy
> - unix_device_rename
> - storage_lvm_use_thinpool
> - storage_rsync_bwlimit
> - network_vxlan_interface
> - storage_btrfs_mount_options
> - entity_description
> - image_force_refresh
> - storage_lvm_lv_resizing
> - id_map_base
> - file_symlinks
> - container_push_target
> - network_vlan_physical
> - storage_images_delete
> - container_edit_metadata
> - container_snapshot_stateful_migration
> - storage_driver_ceph
> - storage_ceph_user_name
> - resource_limits
> - storage_volatile_initial_source
> - storage_ceph_force_osd_reuse
> - storage_block_filesystem_btrfs
> - resources
> - kernel_limits
> - storage_api_volume_rename
> - macaroon_authentication
> - network_sriov
> - console
> - restrict_devlxd
> - migration_pre_copy
> - infiniband
> - maas_network
> - devlxd_events
> - proxy
> - network_dhcp_gateway
> - file_get_symlink
> - network_leases
> - unix_device_hotplug
> - storage_api_local_volume_handling
> - operation_description
> - clustering
> - event_lifecycle
> - storage_api_remote_volume_handling
> - nvidia_runtime
> - container_mount_propagation
> - container_backup
> - devlxd_images
> - container_local_cross_pool_handling
> - proxy_unix
> - proxy_udp
> - clustering_join
> - proxy_tcp_udp_multi_port_handling
> - network_state
> - proxy_unix_dac_properties
> - container_protection_delete
> - unix_priv_drop
> - pprof_http
> - proxy_haproxy_protocol
> - network_hwaddr
> - proxy_nat
> - network_nat_order
> - container_full
> - candid_authentication
> - backup_compression
> - candid_config
> - nvidia_runtime_config
> - storage_api_volume_snapshots
> - storage_unmapped
> - projects
> - candid_config_key
> - network_vxlan_ttl
> - container_incremental_copy
> - usb_optional_vendorid
> - snapshot_scheduling
> - container_copy_project
> - clustering_server_address
> - clustering_image_replication
> - container_protection_shift
> - snapshot_expiry
> - container_backup_override_pool
> - snapshot_expiry_creation
> - network_leases_location
> - resources_cpu_socket
> - resources_gpu
> - resources_numa
> - kernel_features
> - id_map_current
> - event_location
> - storage_api_remote_volume_snapshots
> - network_nat_address
> - container_nic_routes
> - rbac
> - cluster_internal_copy
> - seccomp_notify
> - lxc_features
> - container_nic_ipvlan
> - network_vlan_sriov
> - storage_cephfs
> - container_nic_ipfilter
> - resources_v2
> - container_exec_user_group_cwd
> - container_syscall_intercept
> - container_disk_shift
> - storage_shifted
> - resources_infiniband
> api_status: stable
> api_version: "1.0"
> auth: trusted
> public: false
> auth_methods:
> - tls
> environment:
>   addresses: []
>   architectures:
>   - x86_64
>   - i686
>   certificate: |
>     -----BEGIN CERTIFICATE-----
>     MIICEDCCAZagAwIBAgIRAM8QdpXEA5IuhdZkbQfdpmowCgYIKoZIzj0EAwMwPDEc
>     MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEcMBoGA1UEAwwTcm9vdEBjaHJp
>     cy10aGlua3BhZDAeFw0xOTA4MTYxNTU2MjNaFw0yOTA4MTMxNTU2MjNaMDwxHDAa
>     BgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxHDAaBgNVBAMME3Jvb3RAY2hyaXMt
>     dGhpbmtwYWQwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQassOBAnuhaxjV0RNaNdbg
>     p7ydt4imlfPvQ2V7FNE7+aZXw9Hr+sg5VMh8m35MWVypKbuqbNaqAmeUdxmZwI8H
>     N+uegoJ26fBe1jDSTd8epFdw2Uq1U2YsSoGeqjARE3CjXDBaMA4GA1UdDwEB/wQE
>     AwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMCUGA1UdEQQe
>     MByCDmNocmlzLXRoaW5rcGFkhwTAqAHYhwTAqAHGMAoGCCqGSM49BAMDA2gAMGUC
>     MDIWKN44D3o8IkF71KhVPb82ymeMfb9fHLZrvQ6heO822NGcKlw4zO7CUrNegKd4
>     yAIxAPVrF9UbGO5kdmwLiyyWNWczoIsYz3aHbQZad1GJwD1sMXcrU6EH8e7jTvyY
>     j/BMCA==
>     -----END CERTIFICATE-----
>   certificate_fingerprint: 2a248a048af24566429c74ecdc6a78ea35e17b9e34680df99e6435b55e858386
>   driver: lxc
>   driver_version: 3.2.1
>   kernel: Linux
>   kernel_architecture: x86_64
>   kernel_features:
>     netnsid_getifaddrs: "true"
>     seccomp_listener: "true"
>     shiftfs: "false"
>     uevent_injection: "true"
>     unpriv_fscaps: "true"
>   kernel_version: 5.0.0-25-generic
>   lxc_features:
>     mount_injection_file: "true"
>     network_gateway_device_route: "true"
>     network_ipvlan: "true"
>     network_l2proxy: "true"
>     network_phys_macvlan_mtu: "true"
>     seccomp_notify: "true"
>   project: default
>   server: lxd
>   server_clustered: false
>   server_name: chris-thinkpad
>   server_pid: 1426
>   server_version: "3.16"
>   storage: btrfs
>   storage_version: "4.4"

# Issue description

Mounting a filesystem that is protected with fscrypt into a container is causing the error "Required key not available" for some, but not all, operations. For example, mounting a folder into a container I can edit files with vim. However, trying to cat the same file produces the "Required key not available" message.

I've tried this with both zfs and btrfs backed lxd storage as I wasn't initially aware this was realated to fscrypt. The example below is now running on btrfs and includes 2 mounts, one where the srcpath is from my home the other from outside my home. Only the folder mounted from outside my home works as expected.

# Steps to reproduce

 1. Enable fscrypt on a filesystem, in this case my home directory
 2. Launch a container: "lxc launch ubuntu:xenial test -c security.privileged=true"
 3. Mount a folder into the container: "lxc config device add test testsrc disk source=/home/csanders/my-folder path=/home/ubuntu/my-folder"
 4. Cat a file: 'lxc exec test -- sudo su - ubuntu; cat ./my-folder/some-file'

# Information to attach

 - There is no kernel output. The command simply returns an error as shown below
> cat Dockerfile.app 
> cat: Dockerfile.app: Required key not available

 - [x] Container log (`lxc info NAME --show-log`)

> Name: portal
> Location: none
> Remote: unix://
> Architecture: x86_64
> Created: 2019/08/16 16:54 UTC
> Status: Running
> Type: persistent
> Profiles: default
> Pid: 9507
> Ips:
>   eth0:	inet	10.52.244.131	veth0c777d04
>   eth0:	inet6	fd42:f35b:94d9:109d:216:3eff:feba:2cab	veth0c777d04
>   eth0:	inet6	fe80::216:3eff:feba:2cab	veth0c777d04
>   lo:	inet	127.0.0.1
>   lo:	inet6	::1
> Resources:
>   Processes: 34
>   CPU usage:
>     CPU usage (in seconds): 3
>   Memory usage:
>     Memory (current): 90.85MB
>     Memory (peak): 114.52MB
>   Network usage:
>     eth0:
>       Bytes received: 7.57kB
>       Bytes sent: 2.22kB
>       Packets received: 60
>       Packets sent: 23
>     lo:
>       Bytes received: 41.73kB
>       Bytes sent: 41.73kB
>       Packets received: 99
>       Packets sent: 99
> 
> Log:

 - [x] Container configuration (`lxc config show NAME --expanded`)

> architecture: x86_64
> config:
>   boot.autostart: "false"
>   image.architecture: amd64
>   image.description: ubuntu 16.04 LTS amd64 (release) (20190814)
>   image.label: release
>   image.os: ubuntu
>   image.release: xenial
>   image.serial: "20190814"
>   image.version: "16.04"
>   security.privileged: "true"
>   volatile.base_image: 69ccc7f2e0ff3e2a7b9056fb4d2300aaa5cd5ee9c1a6c9c31eb68f325fb84ab1
>   volatile.eth0.host_name: veth0c777d04
>   volatile.eth0.hwaddr: 00:16:3e:ba:2c:ab
>   volatile.idmap.base: "0"
>   volatile.idmap.current: '[]'
>   volatile.idmap.next: '[]'
>   volatile.last_state.idmap: '[]'
>   volatile.last_state.power: RUNNING
> devices:
>   eth0:
>     name: eth0
>     nictype: bridged
>     parent: lxdbr0
>     type: nic
>   portalsrc:
>     path: /home/ubuntu/tasta
>     source: /mnt/btrfs/src/canonical-is-portal/git/
>     type: disk
>   root:
>     path: /
>     pool: default
>     type: disk
>   tst:
>     path: /home/ubuntu/encfs-folder
>     source: /home/chris/src/canonical-is-portal/git
>     type: disk
> ephemeral: false
> profiles:
> - default
> stateful: false
> description: ""

 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

> t=2019-08-20T12:26:36-0500 lvl=info msg="Starting container" action=start created=2019-08-16T11:54:47-0500 ephemeral=false name=portal project=default stateful=false used=2019-08-20T07:54:57-0500
> t=2019-08-20T12:26:36-0500 lvl=info msg="Started container" action=start created=2019-08-16T11:54:47-0500 ephemeral=false name=portal project=default stateful=false used=2019-08-20T07:54:57-0500
> 

 - [x] Output of the client with --debug
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

lxc monitor doesn't produce anything when the error is created.

**Comment by stgraber** [comment]
How did you setup fscrypt on the source path?

I'd like to reproduce that environment to take a look at it.
This looks like a kernel error so it seems unlikely we'll be able to do something about it, but I'd still like to understand exactly what's going on.

**Comment by chris-sanders** [comment]
I suspect you are right and it's a kernel issue. I setup encryption for my home directory following http://tlbdk.github.io/ubuntu/2018/10/22/fscrypt.html although I suspect you could setup fscrypt on any folder and not mess with unlocking at log-in to recreate.

**Comment by stgraber** [comment]
Ok, been playing with this stuff for an hour or so.
It's pretty tricky and relies on the kernel keyring being setup properly.

I couldn't easily reproduce this issue at first because my keyring setup didn't seem to prevent other users from using my keys, so the container was able to get hold of the ext4 key and so read/write content just fine.

Then I started missing with keyring permissions and managed to break myself in a way similar to yours.

So I suspect in your case you'll want to read about `keyctl`, then look at your user keyrings with `keyctl show`, run `keyctl describe` on the individual keys and possibly tweak access permissions with `keyctl setperm`. You can just open your key up for use by everyone on the system which I suspect would work fine but may not be very safe.

An alternative would be to duplicate the key and chown it to your container's user as seen on the host.

So there isn't really a LXD bug here, the failure is coming from the design of filesystem encryption which relies on per-user keyring entries to allow access to encrypted data. Given a suitable keyring, access will succeed from inside the container.

(Sorry I can't produce immediate steps to fix your setup, the keyring permissions in your case are likely a result of the PAM integration which I don't have here and `setperm` is a very weird and confusing tool to use...)
