### ISSUE TITLE
failed to create dqlite connection: no available dqlite leader server found

### ISSUE THREAD

**Issue by alizowghi** [lxc/lxd#6119]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.3 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-58-generic
   * LXC version: 3.16
   * LXD version: 3.16
   * Storage backend in use: zfs

# Issue description
I have a three nodes cluster and after 2 weeks lxc list stopped working for me.
lvl=warn msg="Failed connecting to global database (attempt 40): failed to create dqlite connection: no available dqlite leader server found"

# Steps to reproduce
I don't know why this happened

# Information to attach
dmesg
[dmesg.txt](https://github.com/lxc/lxd/files/3537246/dmesg.txt)

/var/snap/lxd/common/lxd/logs/lxd.log
[lxd.log](https://github.com/lxc/lxd/files/3537245/lxd.log)

**Comment by freeekanayaka** [comment]
You attached the log of one of the LXD daemons. Can you please attach the logs of the other two daemons as well? Are all daemons running? A cluster of 3 nodes can tolerate at most one down node, so you need to have at least 2 nodes running.

**Comment by alizowghi** [comment]
node2:
[lxd-node2.log](https://github.com/lxc/lxd/files/3537285/lxd-node2.log)

node3:
[lxd-node3.log](https://github.com/lxc/lxd/files/3537286/lxd-node3.log)

Yes all of them are running

**Comment by freeekanayaka** [comment]
Can you make sure that:

1) You can reach all nodes from one another, network-wise.
2) All nodes are running the same lxd version (run ```snap refresh lxd```)

?

**Comment by alizowghi** [comment]
1. I checked this with telnet and all nodes are reachable 
2. Yes all hosts have the same version

My cluster is via public ip address, may this cause problem?

**Comment by freeekanayaka** [comment]
@alizowghi oh yes, public IPs can definitely be a problem, since all cluster nodes are expected to run locally and have a low latency connection. What is the average TCP roundtrip time across those nodes?

**Comment by alizowghi** [comment]
ping average under 1 ms
rtt min/avg/max/mdev = 0.475/0.775/1.269/0.287 ms
