### ISSUE TITLE
$USER is not set inside of container

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#613]
I am not sure where to report that, but $USER variable is not set in container for root. My bootstrap scripts fail, because they rely on it.

```
$ lxc launch ubuntu rtcheck
Creating container...done
Starting container...done
$ lxc exec rtcheck -- bash
root@rtcheck:~# echo $USER

root@rtcheck:~# 
```
On host machine, the $USER shows `root` for admin.

**Comment by techtonik** [comment]
:+1: Nice to see it is *that* simple.

**Comment by techtonik** [comment]
I doesn't seem that I can patch LXC in place until 0.9 is released.
```
$ locate exec.go
/usr/lib/i386-linux-gnu/go/4.9/os/exec.gox
```

**Comment by stgraber** [comment]
correct, Go is a compiled language, the resulting binary is /usr/bin/lxc.

So either you recompile it locally or you wait for us to do it for you, which will be 0.9 on Tuesday.

**Comment by techtonik** [comment]
I guess I can just hardcode the variable until Tuesday. With snapshots it should be much easier.
