### ISSUE TITLE
lxc launch creates LVM volume too small to hold image

### ISSUE THREAD

**Issue by twhite-work** [lxc/lxd#6134]
# Required information
 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    :
    -----END CERTIFICATE-----
  certificate_fingerprint: 5b283d562bd7dea9d339f371826d771ca631928eeefc8c5347b4868f8bbb5148
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-55-generic
  server: lxd
  server_pid: 15148
  server_version: 3.0.3
  storage: zfs | dir | lvm
  storage_version: 0.7.5-1ubuntu16.6 | 1 | 2.02.176(2) (2017-11-03) / 1.02.145 (2017-11-03)
    / 4.37.0 / ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include
    --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc
    --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu
    --libexecdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode
    --disable-dependency-tracking --exec-prefix= --bindir=/bin --libdir=/lib/x86_64-linux-gnu
    --sbindir=/sbin --with-usrlibdir=/usr/lib/x86_64-linux-gnu --with-optimisation=-O2
    --with-cache=internal --with-clvmd=corosync --with-cluster=internal --with-device-uid=0
    --with-device-gid=6 --with-device-mode=0660 --with-default-pid-dir=/run --with-default-run-dir=/run/lvm
    --with-default-locking-dir=/run/lock/lvm --with-thin=internal --with-thin-check=/usr/sbin/thin_check
    --with-thin-dump=/usr/sbin/thin_dump --with-thin-repair=/usr/sbin/thin_repair
    --enable-applib --enable-blkid_wiping --enable-cmdlib --enable-cmirrord --enable-dmeventd
    --enable-dbus-service --enable-lvmetad --enable-lvmlockd-dlm --enable-lvmlockd-sanlock
    --enable-lvmpolld --enable-notify-dbus --enable-pkgconfig --enable-readline --enable-udev_rules
    --enable-udev_sync
  server_clustered: false
  server_name: host
  project: ""

# Issue description
Recommendation:
When launching a new image, the size of the LVM container is set to 10GB (by default) and is set by the definition of the Storage pool and not the size of the image it is launched from.  

When the container is launched, it fails with the following error:
> root@host:/# lxc launch f1d66d6c02d4 containLvm -p default -p defaultlvm
> Creating containLvm
> Error: Unable to unpack image, run out of disk space (consider increasing your pool's volume.size)

I understand the error message now, but it took me a lot of time and research to figure out what exactly was meant by "pool's volume.size".    This is mostly because I am unfamiliar with configuring LVM based containers.   This setting is not required for ZFS based containers or directory based containers.

It seems like either the size of the container should be determined from the originating image, or this should be documented more clearly in the "Storage" documentation:
   https://lxd.readthedocs.io/en/latest/storage/#storage-volume-configuration
I did not see anywhere in the docs where it talked about a default of 10GB containers for LVM storage pools (perhaps I missed it).

# Steps to reproduce
Just a recommendation'

# Information to attach
N/A

**Comment by twhite-work** [comment]
Also in the documentation for Storage pools, there is no differentiation between the "size" and "volume.size" properties, and both say they default to "0".  The "size" property did not work (I got a bunch of TAR error messages) and clearly the volume.size is defaulting to 10GB (at least for LVM's).

**Comment by stgraber** [comment]
We can't easily know how large an image will be once uncompressed. For filesystems that's not a problem as the image itself doesn't have a quota, the quota is applied to the container only. For block based backends like LVM and CEPH, a block device must be created and formatted before the image can be unpacked.

**Comment by twhite-work** [comment]
Thank you for the quick response...

I did not know if the size could be captured when the image is created and stored as meta data inside the image.  Regardless, I think something should be added to the documentation to address the default value and the difference between the two "size" attributes.

**Comment by stgraber** [comment]
Not really because the actual size on disk will vary based on filesystem and could vary based on mount options, both of which are user configurable...

I haven't gotten to the doc yet (on vacation) but will keep this issue around so we can take a look.

 - `size` on a storage pool is the size of the loop device created to back the pool (read-only after pool creation).
 - `volume.size` on a storage pool is the default size for any newly created volumes on that pool.
 - `size` on a storage volume is the size of that volume, if not passed at create time, this gets set to  `volume.size` from the pool. It can normally be changed after the fact, either directly or through the `disk` device on the container.
