### ISSUE TITLE
Cannot build previous version of lxd due to API changes

### ISSUE THREAD

**Issue by nightuser** [lxc/lxd#6137]
# Required information

 * Distribution: ArchLinux, but it's a distribution-agnostic problem
 * Distribution version: 3.16
 * The output of "lxc info" or if that fails: a problem with building the package

# Issue description

It's impossible to build a release-version of lxd due to API changes in dqlite. On of the latest commits to master fixes this issue upstream. `make update` downloads the latest versions of dqlite, sqlite, and other relevant packages (there is simply git clone in the Makefile. It possibly should include the release version of the packages as well, so that build process will be reproducible and provide the same result.

# Steps to reproduce

 1. switch to lxd-3.16
 2. make update and then build as usual

# Information to attach

**Comment by stgraber** [comment]
All release tarballs include a copy of the library sources needed to build them, so you'll want to use the release tarball instead of the git tag and make sure you use the included Go packages and C libraries.
