### ISSUE TITLE
Still no way to "hide" the host load average in an LXD container?

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#6140]
LXD 3.16 from Snap on Ubuntu Bionic

I have been looking into this issue lately, and it seems to be an old one, but I am confused as to whether this is still "pending" upstream updates, or what is going on. It looks to me this open issue is what's being worked on, on the lxc side:

https://github.com/lxc/lxcfs/pull/278

But it is unclear to me where we are at, at the moment. Is it impossible to "hide" the global host load average in an LXD container - e..g from htop? Do you expect this to be solved sometime in the future, or is there some showstopper here?

Thanks :)

**Comment by stgraber** [comment]
https://github.com/lxc/lxd-pkg-snap/issues/38

**Comment by Kramerican** [comment]
@stgraber Thanks Stéphane, much appreciated 👍 I will excitedly await that update :)
