### ISSUE TITLE
lxcfs not stopped after snap update

### ISSUE THREAD

**Issue by geodb27** [lxc/lxd#6142]
# Required information

 * Distribution: ubuntu-server
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-45-generic
   * LXC version: 3.16
   * LXD version: 3.16
   * Storage backend in use: ceph

I had problems with my ubuntu servers machines running lxd : the /var partition was reported as full by df while du showed only half the space used. So I dug the problem and found out that since these machines are servers, they are not rebooted very often. On one of the machine having the /var reported as full, I found out that there was one lxcfs process running per snap's version of lxd. My guess is that the old processes should have been shut down. Indeed, killing the unnecessary lxcfs's processes freed up the space marked as "deleted" reported by "lsof | grep var | grep deleted" and the /var filesystem is not marked full anymore.

 1. Step one : wait for a snap's lxd update
 2. Step two : let the update be done without rebooting the machine
 3. Step three : ps auxf | grep lxfs shows at least two processes while only one (the one that comes with the last installed version of lxd) should be running.

**Comment by stgraber** [comment]
Closing as this isn't a LXD bug (would be more suitable for lxd-pkg-snap).

Anyway, the logic is specifically to NEVER stop lxcfs as doing so would break all existing containers.
However the logic detects the existing lxcfs and tell it to reload itself using the newer library.

So you should only ever have a single lxcfs process that was spawned from whatever revision of the snap was present on initial startup and was then reloaded (not respawned) every time an update happened.

I've looked at the about 20 or so servers I have access to and none of them show multiple lxcfs processes despite having been refreshed quite frequently, so it's not as easy to reproduce as you describe.

I've also checked our test system which tracks all revisions of all the snap channels, that one runs nested LXD with 5 containers per track/container combo, so if something was going generally wrong, I would have expected to see it run a LOT of lxcfs processes, but I'm just seeing one per LXD instance, started when the start system initially booted as I would expect.
