### ISSUE TITLE
Enhancement: 'Error: not found': please be more specific in error message.

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#6143]
# Required information

* Distribution: ubuntu 18.04
* snap lxd 3.16

# Issue description

Lot of lxc commands returns 'Error: not found': it may be not sufficiant to know what it is speaking about.

Examples:

1. lxc file push XXFile remote-cont/opt/Installs/
=> Error: not found

what is not found? the remote? the file? The target path?

2. lxc image  alias rename remote-cont:'alias name' 'new alias'
=> Error: not found
what is not found? the remote? the alias?

**Comment by stgraber** [comment]
We already have an issue that covers this.

#5548
