### ISSUE TITLE
[Docs] Provide more examples with XFS project quota

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#6146]
Current storage quota documentation is lacking for XFS project quota setup.
Would be nice to have more detailed example for this setup.

**Comment by stgraber** [comment]
LXD will use project quotas when the underlying filesystem has been configured for it.
How to achieve that varies between Linux distributions and kernel versions so it's best handled by distribution documentation than it is ours.

**Comment by s3rj1k** [comment]
@stgraber this does not answer a question on how to specify quota size in lxd config.

**Comment by stgraber** [comment]
Same as with all storage backends, you set the `size` property on the `disk` device which backs the / of your container. That's typically the device called `root`.

**Comment by s3rj1k** [comment]
@stgraber thanks
