### ISSUE TITLE
sql error on start of new lxd

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#616]
2015/05/08 14:17:26 DbQuery: query "SELECT max(version) FROM schema" error "sql: Scan error on column index 0: converting string \"<nil>\" to a int: strconv.ParseInt: parsing \"<nil>\": invalid syntax"

**Comment by tych0** [comment]
Note that this doesn't seem to cause any problems, it just looks ugly :)

**Comment by chrisglass** [comment]
Well, that's only a Debug output (Debugf()), I'm not sure it needs any action.

We specifically swallow errors like this there (https://github.com/lxc/lxd/blob/master/shared/db.go#L169), and the upper-layer code relies on this behaviour already (since we return nil, err).

**Comment by stgraber** [comment]
Fair enough. I'll close this and hope that #482 will improve things a bit.
