### ISSUE TITLE
Memory limit is not effective free command for docker in lxd.

### ISSUE THREAD

**Issue by penM000** [lxc/lxd#6166]
# Required information

 * Distribution:debian
 * Distribution version:10
 * The output of "lxc info" or if that fails:
   * Kernel version:Debian 4.19.37-5+deb10u2
   * LXC version:3.16
   * LXD version:3.16
   * Storage backend in use:btrfs

# Issue description

In the case of lxc container, the memory limit was applied by "lxc config set debian10-lxc1 limits.memory 4000MB", but the memory limit is a container (ubuntu18.04) running with docker in the container (debian10-lxc1) Is not applicable.
However, this is a display issue.

# Steps to reproduce

 1. Step one
Check the memory limit.
debian10-lxc1 8000Mb limit
```
user@debian10-lxc1:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:          7.5Gi       178Mi       7.0Gi       7.0Mi       256Mi       7.3Gi
Swap:          20Gi       306Mi        19Gi
```
debian10-lxc1 4000Mb limit
```
user@debian10-lxc1:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:          3.7Gi       179Mi       3.3Gi       7.0Mi       256Mi       3.5Gi
Swap:          20Gi       306Mi        19Gi
```

 2. Step two
Install docker in lxd container and start ubuntu image.
And check free -h 
```
user@debian10-lxc1:~$ sudo docker run -it -d --name ubuntu1804  ubuntu:18.04
ceab41d670e842642b2bcaf0943ef0009caddde97a5f0d64b1e79b4d3efc39db
user@debian10-lxc1:~$ sudo docker exec -it ubuntu1804 /bin/bash
root@ceab41d670e8:/# free -h
              total        used        free      shared  buff/cache   available
Mem:            31G         10G        495M        320M         20G         20G
Swap:           20G        306M         19G

```
The memory acquired by the Docker container is the same as the host.
```
user@server1:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:           31Gi        10Gi       493Mi       320Mi        20Gi        20Gi
Swap:          20Gi       306Mi        19Gi
```
Container nesting is enabled in container profiles.
```
user@server1:~$ lxc profile show default 
config:
  security.nesting: "true"
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/first
- /1.0/containers/debian10-lxc1
- /1.0/containers/ubuntu18
```
To check if this is a display issue, load the memory of the Docker container.

Docker Container stress test
```
root@ceab41d670e8:/# stress --vm 2 --vm-bytes 4G --timeout 2m
stress: info: [321] dispatching hogs: 0 cpu, 0 io, 2 vm, 0 hdd
```

Docker Container free Before after
```
root@ceab41d670e8:/# free -h
              total        used        free      shared  buff/cache   available
Mem:            31G         10G        3.9G        306M         16G         20G
Swap:           20G        526M         19G

root@ceab41d670e8:/# free -h
              total        used        free      shared  buff/cache   available
Mem:            31G         14G        325M        306M         16G         16G
Swap:           20G        5.0G         15G
```
You can see that the memory is increasing. 
lxd free Before after
```
user@debian10-lxc1:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:          3.7Gi        78Mi       3.6Gi       0.0Ki        37Mi       3.6Gi
Swap:          20Gi       523Mi        19Gi

user@debian10-lxc1:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:          3.7Gi       3.7Gi       0.0Ki          0B        10Mi        10Mi
Swap:          20Gi       4.0Gi        15Gi

```

From the above, it can be seen that the memory limit is also effective in the docker container, but the notified memory is not limited.

**Comment by stgraber** [comment]
That's simply because Docker doesn't know about or use lxcfs, so /proc/meminfo in the Docker container doesn't show the cgroup limits but instead shows the system-wide memory information.

In LXD containers, /proc/meminfo is setup as a bind-mount of the lxcfs meminfo file which is what provides you with per-container data in `free` and other tools.

**Comment by penM000** [comment]
Thank you for answering this.
I learned about lxcfs for the first time.
The free command continued correctly by mounting / var / lib / lxcfs / proc / meminfo on / proc / meminfo.
Now you can use lxc like vm.
