### ISSUE TITLE
Restrictions for projects

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#6170]
Somewhat similar to #6169, another big part of delegating access to LXD to users is being able to restrict them to operations that will not allow attacks to the host system.

For this we should introduce a new `restrict` key namespace that's used to block access to a variety of features, an initial set would be:

 - restricted (boolean, if enabled, all restrictions apply)
 - restricted.containers.privilege (one of `allow`, `unprivileged`, `isolated`, default `unprivileged`)
 - restricted.containers.nesting (one of `allow` or `block`, default `block`)
 - restricted.containers.lowlevel (one of `allow` or `block`, default `block`)
 - restricted.devices.disk (one of `allow`, `managed`, `block`, default `managed`)
 - restricted.devices.gpu (one of `allow` or `block`, default `block`)
 - restricted.devices.usb (one of `allow` or `block`, default `block`)
 - restricted.devices.nic (one of `allow`, `managed` or `block`, default `managed`)
 - restricted.devices.infiniband (one of `allow` or `block`, default `block`)
 - restricted.devices.unix-char (one of `allow` or `block`, default `block`)
 - restricted.devices.unix-block (one of `allow` or `block`, default `block`)
 - restricted.devices.unix-hotplug (one of `allow` or `block`, default `block`)
 - restricted.virtual-machines.lowlevel (one of `allow` or `block`, default `block`)

The idea is that if a project has `restricted` set to `true`, all restrictions apply such that if we are to add new restrictions to LXD, things default closed rather than default open.

The `restricted.containers.privilege` key controls `security.privileged` and `security.idmap.isolated`.
When set to`allow`, all keys can be set to whatever value. When set to `unprivileged`, `security.privileged` can only be set to false. When set to `isolated`, `security.privileged` can only be set to false and `security.idmap.isolated` can only be set to true.

The `restricted.containers.nesting` key controls `security.nesting`.

The devices keys allow/block the use of a device type of the same name.

For `restricted.devices.nic` a value of `managed` means it's allowed so long as the `network=` key is used.

For `restricted.devices.disk` a value of `managed` means it's allowed so long as a the `pool=` key is used. Additionally, the default disk must be allowed even if the key is set to `block`. The default disk is one using `path=/` and with `pool=` set.

The `restricted.containers.lowlevel` option above should control (for containers):

 - boot.host_shutdown_timeout
 - linux.kernel_modules
 - raw.apparmor
 - raw.idmap
 - raw.lxc
 - raw.seccomp
 - security.devlxd.images
 - security.idmap.base
 - security.idmap.size
 - security.syscalls.*
 - volatile.*

The `restricted.virtual-machines.lowlevel` option above should control (for VMs):

 - limits.memory.hugepages
 - raw.qemu
 - volatile.*

**Comment by sz17** [comment]
Hi @stgraber we are students from the University of Texas at Austin Computer Science Department and we are interested in taking this issue would you please provide us with more information? Thank you!

**Comment by stgraber** [comment]
Hi @sz17, this issue mostly touches projects and would include:
 - New API extension for the feature
 - Adding all the config keys listed in the issue description to the projects codebase, including value validation for each of them
 - Updating bash completion profile to match
 - Updating documentation to cover them
 - Add wrapper functions to make it easy to check whether a particular Instance can use a particular feature
 - Update the container validation logic to check against those project restrictions
 - Add some tests to validate that everything works as expected

**Comment by sz17** [comment]
@stgraber after discussing with our professor, we were wondering if it would be possible to split up this large project into multiple PRs with the hopes of merging each PR individually? I think it would help us complete the issue better as well as allow someone else to pick up our work if we are unable to complete the entire project.

**Comment by stgraber** [comment]
@sz17 The main thing that could be done to reduce the scope of this is by implementing less of the restrictions. I'm not sure exactly how much work that would save though. When we did some similar access control work for our RBAC feature, the difficult part tends to be to figure out the right helper functions and getting the first path covered, after that, doing the other ones is pretty mechanical and usually quick.

**Comment by sz17** [comment]
@stgraber Our group will take this project, will you please assign it to us? Thank you!
