### ISSUE TITLE
Storage volumes in projects

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#6171]
Right now storage volumes are a global resource, they show up in every single project and can be used by containers of any projects. This may be the desired behavior for some users that have containers in multiple projects and wish to share access to storage volumes but it would be much nicer to have the option to keep those volumes tied to projects.

To do that, we need to:
 - Introduce `features.storage.volumes` which when enabled will cause only custom volumes belonging to the project to show up
 - Use a variant of our good old friend projectPrefix and rename all existing storage volume paths internally to match. Note that unlike containers, underscores are valid in custom volume names, so we need to prefix everything, including those in the default project.
 -  Update the volume attach logic to look at only the project's volumes if the feature is enabled

**Comment by sz17** [comment]
Hi @stgraber , we are students from the University of Texas at Austin in the Computer Science Department's Virtualization class and we were wondering if you could give us more information about the skills required to complete this project? Thank you!

**Comment by stgraber** [comment]
@sz17 this one is currently still on our list of things we're hoping we may get done ourselves over the next two weeks, if that changes and we end up postponing it until the next round (end of January deadline), then this would become an option for you.

**Comment by sz17** [comment]
@stgraber our project is due around the beginning of December, so we will look at other projects. Good luck with the issue!
