### ISSUE TITLE
Direct attach of ceph rbd/fs to containers

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#6174]
We've had a number of users who reached out wanting to connect an existing CEPH RBD or FS directly to a LXD container, without those coming from a LXD managed pool.

This should be doable by extending our current `disk` device, adding options to specify the backend (rbd/fs), the pool name, volume name and other CEPH related options.

**Comment by ribsthakkar** [comment]
Hi @stgraber, my team with @abbykrish, @anusha-paul, and myself will work on this issue

**Comment by stgraber** [comment]
@ribsthakkar assigned it to you for now, I'll need to have the other two comment so Github lets me assign it to them too.

**Comment by stgraber** [comment]
Excellent, for this one, I'd expect roughly the following commits:
 - api: Add `container_disk_ceph` API extension
   - Add that string to `shared/version/api.go`
   - Add a matching entry to `doc/api-extensions.md`
 - lxd: Add support for CEPH RBD backed disks
   - Add the new options to `lxd/device/disk.go`
   - Follow and extend the logic currently used to handle block device mounts and combine that with the functions in `storage_ceph.go` and `storage_ceph_utils.go` to map and mount the needed RBD volume as needed.
 - lxd: Add support for CEPH FS backed disks
   - Add the new options to `lxd/device/disk.go`
   - Follow and extend the logic currently used to handle bind mounts and combine that with the functions in `storage_cephfs.go` to mount the needed FS volume as needed.
 - doc: Add support for CEPH backed disks
   - Split the `disk` device type similarly to what was done for `nic`
   - Put a clear explanation under `local` disktype that `local` also covers those CEPH RBD/FS volumes which are managed by LXD itself (stored on a LXD managed pool)
   - Add the new types and their accepted options
 - tests: Add test for CEPH backed disks
   - Extend `test/suites/container_devices_disk.sh` to test the new configuration options. You'll want to make this conditional on `LXD_CEPH_CLUSTER`. If a cluster is set, then directly allocate a small 10MB RBD volume and pass it to a container.
   - Same goes for CEPH fs but this time checking `LXD_CEPH_CEPHFS` and creating a directory on that CEPH fs instance.
   - The test should validate that this works both on at boot time and when hot plugging the device into the container.

I suspect we'd want the options to look like:
 - `disktype` (default to `local`, can also be `ceph` or `cephfs`)
 - `ceph.user_name` (default to `admin`)
 - `ceph.cluster_name` (default to `ceph`)
 - `source` be used to point to the `<pool>/<volume>` (RBD) or `<pool>/<path>` (FS)

@tomponline and myself should be good contacts for this one.

**Comment by stgraber** [comment]
@tomponline how does that sound to you? I'm not super fond of having to split `disk` through `disktype` but it'd be consistent with `nic` and it feels to me like adding two more device types for this would be even more confusing.

In theory we could do some clever parsing of `source` to avoid needing a `disktype` entirely, but distinguishing between ceph-rbd and ceph-fs then becomes a bit tricky.

**Comment by tomponline** [comment]
@stgraber could we do something similar to LXC where we prefix a protocol to the source, e.g. `ceph:<pool>/<volume>` and `cephfs:<pool>/<volume>`? With nictype, many of the options available are different from others, but with disk would the majority of options still be available?

**Comment by anusha-paul** [comment]
Hi, could you add me to this issue.

**Comment by stgraber** [comment]
Done

**Comment by abbykrish** [comment]
Hi Stephane, we're starting to work on the project and I realized I was never added to this issue. Could you quickly add me?

**Comment by stgraber** [comment]
done!

**Comment by ribsthakkar** [comment]
I am having issues actually ensuring that our changes are being detected. Even when I follow the instructions to make and compile the binaries for lxc and lxd on the readme of the page, I don't think our changes are reflected in the binary itself. For example when running the command 
`lxc config device add first fs disk source=cephfs:$LXD_CEPH_CEPHFS/ ceph.user_name=admin ceph.cluster_name=ceph path=/cephfs` 
I know I don't have anything defined and I expect a faliure to be thrown later in the call stack. However, I get a validation error:
`Error: Invalid devices: Invalid device option: ceph.cluster_name` although I added exceptions in /lxd/device/config/devices.go to allow for those options when the source begins with ceph.

I tried to put a printf statement and even `return nil` at the top of the function and recompiled. However, it still output the same error message. That is why I am suspecting our changes are not being reflected in the binary once it is compiled.

**Comment by stgraber** [comment]
And you built both the lxc and lxd binaries and made sure that the lxd binary you're running is the new one?

**Comment by ribsthakkar** [comment]
yup, I deleted all of the binaries and redid the process again. Still yielded the same result

**Comment by ribsthakkar** [comment]
Do I need to rename the references to other lxd dependency packages if we forked the repository?

**Comment by stgraber** [comment]
Ah, that's likely the problem, yeah. So you'd want your code to be located at `~/go/src/github.com/lxc/lxd`, if it's somewhere else, than imports will still import the upstream code, skipping your changes.

Easiest is to just remove `~/go/src/github.com/lxc/lxd` and replace it with your own tree, then build again.

**Comment by ribsthakkar** [comment]
Yup that was it. thanks!
