### ISSUE TITLE
"Found snapshot with no associated instance" preventing schema upgrade

### ISSUE THREAD

**Issue by zrav** [lxc/lxd#6177]
# Required information

 * Distribution: Ubuntu
 * Distribution version:  18.04 LTS / snap
 * The output of "lxc info":
```
config:
  core.https_address: x.x.x.x:8443
  core.trust_password: true
api_extensions:
...
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - x.x.x.x:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    xxx
  certificate_fingerprint: xxx
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.0.0-27-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: atlas
  server_pid: 122639
  server_version: "3.16"
  storage: zfs
  storage_version: 0.7.12-1ubuntu5
```
# Issue description

Upgrading to 3.17 failed because the DB consistency check failed: "Found snapshot mytest/snap0 with no associated instance". This references a deleted container/snapshot. I don't remember any unusual circumstance when deleting this container.

How can this be worked around? Is there a way to clean up or rebuild the DB?

**Comment by stgraber** [comment]
Write a patch.global.sql file in /var/snap/lxd/common/lxd/database containing:

DELETE FROM containers WHERE name="mytest/snap0";

LXD should then run that on startup before trying the upgrade again.

**Comment by stgraber** [comment]
@zrav did that work?

**Comment by zrav** [comment]
@stgraber yes, that seems to have done the trick. Thanks you.

**Comment by dkruyt** [comment]
Got the same issue but then after a lxd.migratie from version 3.0.3 to 3.17

INFO[10-03|16:38:41] Initializing global database
DBUG[10-03|16:38:41] Dqlite: connected address=1 attempt=0
INFO[10-03|16:38:41] Updating the LXD global schema. Backup made as "global.bak"
DBUG[10-03|16:38:41] Running pre-update queries from file for global DB schema
DBUG[10-03|16:38:41] Updating global DB schema from 7 to 8
DBUG[10-03|16:38:41] Updating global DB schema from 8 to 9
DBUG[10-03|16:38:41] Updating global DB schema from 9 to 10
DBUG[10-03|16:38:41] Updating global DB schema from 10 to 11
DBUG[10-03|16:38:41] Updating global DB schema from 11 to 12
DBUG[10-03|16:38:41] Updating global DB schema from 12 to 13
DBUG[10-03|16:38:41] Updating global DB schema from 13 to 14
DBUG[10-03|16:38:41] Updating global DB schema from 14 to 15
DBUG[10-03|16:38:41] Updating global DB schema from 15 to 16
DBUG[10-03|16:38:41] Database error: &errors.errorString{s:"failed to apply update 15: Found snapshot ghostblog1804/11-10-18-01-57 with no associated instance"}
EROR[10-03|16:38:41] Failed to start the daemon: failed to open cluster database: failed to ensure schema: failed to apply update 15: Found snapshot ghostblog1804/11-10-18-01-57 with no associated instance

lxc list don't show any snapshots.
 
tried the patch.global.sql file in /var/snap/lxd/common/lxd/database but this doesn't seem to work.
Now I downgraded the snap package to 3.16 and the containers are running again.
Inspecting the sql global dump.

INSERT INTO "containers" VALUES(1127,1,'ghostblog1804/11-10-18-01-57',2,1,0,1541815025,0,0,'',1,-62135596800);
INSERT INTO "containers" VALUES(1204,1,'ghostblog1804/11-17-18-01-57',2,1,0,1542419856,0,0,'',1,-62135596800);
INSERT INTO "containers" VALUES(1292,1,'ghostblog1804/11-25-18-01-58',2,1,0,1543111087,0,0,'',1,-62135596800);
INSERT INTO "containers" VALUES(1604,1,'ghostblog1804/12-23-18-01-56',2,1,0,1545530167,0,0,'',1,-62135596800);
INSERT INTO "storage_volumes" VALUES(1133,'ghostblog1804/11-10-18-01-57',1,1,0,'',0,1);
INSERT INTO "storage_volumes" VALUES(1210,'ghostblog1804/11-17-18-01-57',1,1,0,'',0,1);
INSERT INTO "storage_volumes" VALUES(1298,'ghostblog1804/11-25-18-01-58',1,1,0,'',0,1);
INSERT INTO "storage_volumes" VALUES(1610,'ghostblog1804/12-23-18-01-56',1,1,0,'',0,1);

What is the best wat to delete those database objects?

Also seems to have some leftover on the zfs volume.

lxd/snapshots/bionic-minimal/08-25-18-01-26                                          5.71M  33.2G   651M  /var/snap/lxd/common/lxd/storage-pools/lxd/snapshots/bionic-minimal/08-25-18-01-26
lxd/snapshots/ghostblog/07-24-18-21-28                                               91.5M  33.2G  1.95G  /var/snap/lxd/common/lxd/storage-pools/lxd/snapshots/ghostblog/07-24-18-21-28
lxd/snapshots/ghostblog/11-18-18-01-30                                                 15K  33.2G    25K  /var/snap/lxd/common/lxd/storage-pools/lxd/snapshots/ghostblog/11-18-18-01-30
lxd/snapshots/ghostblog/11-22-18-01-30                                                 15K  33.2G    25K  /var/snap/lxd/common/lxd/storage-pools/lxd/snapshots/ghostblog/11-22-18-01-30
lxd/snapshots/ghostblog/11-29-18-01-28                                                 15K  33.2G    25K  /var/snap/lxd/common/lxd/storage-pools/lxd/snapshots/ghostblog/11-29-18-01-28
lxd/snapshots/ghostblog/12-10-18-01-28                                                 15K  33.2G    25K  /var/snap/lxd/common/lxd/storage-pools/lxd/snapshots/ghostblog/12-10-18-01-28
lxd/snapshots/ghostblog/12-15-18-01-28                                                 15K  33.2G    25K  /var/snap/lxd/common/lxd/storage-pools/lxd/snapshots/ghostblog/12-15-18-01-28
lxd/snapshots/mailserver/11-30-18-02-25                                                16K  33.2G    26K  /var/snap/lxd/common/lxd/storage-pools/lxd/snapshots/mailserver/11-30-18-02-25
lxd/snapshots/wordpress/11-13-18-02-48                                                 15K  33.2G    25K  /var/snap/lxd/common/lxd/storage-pools/lxd/snapshots/wordpress/11-13-18-02-48

**Comment by stgraber** [comment]
- lxd sql global "DELETE FROM containers WHERE id in (1127,1204,1292,1604);"
 - lxd sql global "DELETE FROM storage_volumes WHERE id in (1133,1210,1298,1610);"
 - zfs destroy -R lxd/snapshots
 - zfs create lxd/snapshots -o mountpoint=none

All of that as root should take care of everything you showed above, then try switching to stable (3.17) again.

**Comment by dkruyt** [comment]
> * lxd sql global "DELETE FROM containers WHERE id in (1127,1204,1292,1604);"
> * lxd sql global "DELETE FROM storage_volumes WHERE id in (1133,1210,1298,1610);"
> * zfs destroy -R lxd/snapshots
> * zfs create lxd/snapshots -o mountpoint=none
> 
> All of that as root should take care of everything you showed above, then try switching to stable (3.17) again.

Thanks, that worked...
