### ISSUE TITLE
dial unix /var/snap/lxd/common/lxd/unix.socket: connect: no such file or directory

### ISSUE THREAD

**Issue by truelai** [lxc/lxd#6179]
```
sudo lxd --debug --group lxd
INFO[09-09|13:33:32] LXD 3.17 is starting in normal mode      path=/var/snap/lxd/common/lxd
INFO[09-09|13:33:32] Kernel uid/gid map: 
INFO[09-09|13:33:32]  - u 0 0 4294967295 
INFO[09-09|13:33:32]  - g 0 0 4294967295 
INFO[09-09|13:33:32] Configured LXD uid/gid map: 
INFO[09-09|13:33:32]  - u 0 1000000 1000000000 
INFO[09-09|13:33:32]  - g 0 1000000 1000000000 
INFO[09-09|13:33:32] Kernel features: 
INFO[09-09|13:33:32]  - netnsid-based network retrieval: no 
INFO[09-09|13:33:32]  - uevent injection: no 
INFO[09-09|13:33:32]  - seccomp listener: no 
INFO[09-09|13:33:32]  - unprivileged file capabilities: yes 
INFO[09-09|13:33:32]  - shiftfs support: no 
INFO[09-09|13:33:32] Initializing local database 
DBUG[09-09|13:33:32] Initializing database gateway 
DBUG[09-09|13:33:32] Start database node                      id=1 address=
INFO[09-09|13:33:32] Starting /dev/lxd handler: 
INFO[09-09|13:33:32]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[09-09|13:33:32] REST API daemon: 
INFO[09-09|13:33:32]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[09-09|13:33:32]  - binding TCP socket                    socket=[::]:8443
INFO[09-09|13:33:32] Initializing global database 
DBUG[09-09|13:33:32] Dqlite: connected address=1 attempt=0 
INFO[09-09|13:33:32] Updating the LXD global schema. Backup made as "global.bak" 
DBUG[09-09|13:33:32] Updating global DB schema from 14 to 15 
DBUG[09-09|13:33:32] Updating global DB schema from 15 to 16 
DBUG[09-09|13:33:32] Database error: &errors.errorString{s:"failed to apply update 15: Found snapshot nextcloud-node3/nextcloud-node3-2018-07-30 with no associated instance"} 
EROR[09-09|13:33:32] Failed to start the daemon: failed to open cluster database: failed to ensure schema: failed to apply update 15: Found snapshot nextcloud-node3/nextcloud-node3-2018-07-30 with no associated instance 
INFO[09-09|13:33:32] Starting shutdown sequence 
INFO[09-09|13:33:32] Stopping REST API handler: 
INFO[09-09|13:33:32]  - closing socket                        socket=[::]:8443
INFO[09-09|13:33:32]  - closing socket                        socket=/var/snap/lxd/common/lxd/unix.socket
INFO[09-09|13:33:32] Stopping /dev/lxd handler: 
INFO[09-09|13:33:32]  - closing socket                        socket=/var/snap/lxd/common/lxd/devlxd/sock
DBUG[09-09|13:33:32] Stop database gateway 
DBUG[09-09|13:33:33] Not unmounting temporary filesystems (containers are still running) 
Error: failed to open cluster database: failed to ensure schema: failed to apply update 15: Found snapshot nextcloud-node3/nextcloud-node3-2018-07-30 with no associated instance
```
Can I manually delete this snapshot and then restart?

**Comment by stgraber** [comment]
Yes, this is similar to #6177 and the fix would be the same.
Create a file at /var/snap/lxd/common/lxd/database/patch.global.sql containing:

```
DELETE FROM containers WHERE name='nextcloud-node3/nextcloud-node3-2018-07-30';
```

On startup, that entry will then get deleted and the upgrade attempted again. It may or may not fail on another one, if it does, then you'll need to repeat that step with the different name.

**Comment by truelai** [comment]
OMG. I think I messed up big time. 

I created a patch like this and rebooted server: 

DELETE FROM nodes;
INSERT INTO nodes(id, name, address, schema, api_extensions, pending) VALUES(1, 'none', '0.0.0.0', 1, 1, 0);

Looks like I lost everything??

**Comment by stgraber** [comment]
Why did you do that?

But yes, that would likely be a very bad idea as there are foreign key references to the nodes table from pretty much everything else in the database. That delete likely cascaded and effectively deleted everything except the most global settings.

Look for a `global.bak` directory in /var/snap/lxd/common/lxd/database, if it's there and the timestamp looks reasonable, then get rid of `global` and restore `global.bak` as your new `global`.

**Comment by truelai** [comment]
root@R610-LXD2-LAN:~# ll /var/snap/lxd/common/lxd/database/global.bak/
total 64164
drwx------ 1 root root    1824 Sep  9 13:42 ./
drwx------ 1 root root      72 Sep  9 13:42 ../
-rw-r--r-- 1 root root 7343448 Sep  9 13:42 1115610-1116313
-rw-r--r-- 1 root root 1285440 Sep  9 13:42 1116314-1116440
-rw-r--r-- 1 root root  785280 Sep  9 13:42 1116441-1116517
-rw-r--r-- 1 root root 1653168 Sep  9 13:42 1116518-1116678
-rw-r--r-- 1 root root  557976 Sep  9 13:42 1116679-1116733
-rw-r--r-- 1 root root 2475456 Sep  9 13:42 1116734-1116972
-rw-r--r-- 1 root root  949296 Sep  9 13:42 1116973-1117047
-rw-r--r-- 1 root root 1085160 Sep  9 13:42 1117048-1117128
-rw-r--r-- 1 root root  644136 Sep  9 13:42 1117129-1117183
-rw-r--r-- 1 root root  549120 Sep  9 13:42 1117184-1117229
-rw-r--r-- 1 root root  243768 Sep  9 13:42 1117230-1117252
-rw-r--r-- 1 root root  776424 Sep  9 13:42 1117253-1117320
-rw-r--r-- 1 root root 1069320 Sep  9 13:42 1117321-1117409
-rw-r--r-- 1 root root  668568 Sep  9 13:42 1117410-1117461
-rw-r--r-- 1 root root  350904 Sep  9 13:42 1117462-1117490
-rw-r--r-- 1 root root  697920 Sep  9 13:42 1117491-1117551
-rw-r--r-- 1 root root  375960 Sep  9 13:42 1117552-1117586
-rw-r--r-- 1 root root 8380656 Sep  9 13:42 1117587-1118389
-rw-r--r-- 1 root root 3306296 Sep  9 13:42 1118390-1118710
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118711-1118711
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118712-1118712
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118713-1118713
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118714-1118714
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118715-1118715
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118716-1118716
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118717-1118717
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118718-1118718
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118719-1118719
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118720-1118720
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118721-1118721
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118722-1118722
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118723-1118723
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118724-1118724
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118725-1118725
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118726-1118726
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118727-1118727
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118728-1118728
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118729-1118729
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118730-1118730
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118731-1118731
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118732-1118732
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118733-1118733
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118734-1118734
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118735-1118735
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118736-1118736
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118737-1118737
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118738-1118738
-rw-r--r-- 1 root root      48 Sep  9 13:42 1118739-1118739
-rw-r--r-- 1 root root  503808 Sep  9 13:42 db.bin
-rw-r--r-- 1 root root   32768 Sep  9 13:42 db.bin-shm
-rw-r--r-- 1 root root  193672 Sep  9 13:42 db.bin-wal
-rw-r--r-- 1 root root      32 Sep  9 13:42 metadata1
-rw-r--r-- 1 root root      32 Sep  9 13:42 metadata2
-rw-r--r-- 1 root root 8388608 Sep  9 13:42 open-1
-rw-r--r-- 1 root root 8388608 Sep  9 13:42 open-2
-rw-r--r-- 1 root root 8388608 Sep  9 13:42 open-3
-rw-r--r-- 1 root root 3532080 Sep  9 13:42 snapshot-12-1116696-11558177041
-rw-r--r-- 1 root root      56 Sep  9 13:42 snapshot-12-1116696-11558177041.meta
-rw-r--r-- 1 root root 2893480 Sep  9 13:42 snapshot-25-1117720-147841759
-rw-r--r-- 1 root root      56 Sep  9 13:42 snapshot-25-1117720-147841759.meta

**Comment by truelai** [comment]
What can I do?? Looks like everything here is new?

**Comment by truelai** [comment]
I just wiped everything out, didn't i?

**Comment by stgraber** [comment]
It may not be that new, it's a copy, so all those files got copied recently.
Try:
 - mv backup backup.broken
 - cp -r backup.bak backup

Start and see what happens.

**Comment by truelai** [comment]
so:

mv /var/snap/lxd/common/lxd/database/global /var/snap/lxd/common/lxd/database/global.broken
and
mv /var/snap/lxd/common/lxd/database/global.bak /var/snap/lxd/common/lxd/database/global   

correct?

**Comment by truelai** [comment]
I did that and then:

root@R610-LXD2-LAN:~# service snap.lxd.daemon restart
root@R610-LXD2-LAN:~# lxc list 

No output. Just hanging.

**Comment by truelai** [comment]
Rebooted the server. I'm still getting no output when I _lxc list_

**Comment by truelai** [comment]
root@R610-LXD2-LAN:~# lxd --debug --group lxd
DBUG[09-09|14:12:31] Connecting to a local LXD over a Unix socket 
DBUG[09-09|14:12:31] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=

**Comment by truelai** [comment]
Is this a hint? 

root@R610-LXD2-LAN:~# /bin/sh /snap/lxd/11824/commands/daemon.stop
/snap/lxd/11824/commands/daemon.stop: 9: /snap/lxd/11824/commands/daemon.stop: SNAP_COMMON: parameter not set

**Comment by truelai** [comment]
Ok. Got it to stop and start and looks loaded:

```
 root@R610-LXD2-LAN:~# service snap.lxd.daemon status
● snap.lxd.daemon.service - Service for snap application lxd.daemon
   Loaded: loaded (/etc/systemd/system/snap.lxd.daemon.service; static; vendor preset: enabled)
   Active: active (running) since Mon 2019-09-09 14:29:15 EDT; 15s ago
  Process: 5976 ExecStop=/usr/bin/snap run --command=stop lxd.daemon (code=killed, signal=TERM)
 Main PID: 7210 (daemon.start)
    Tasks: 0
   Memory: 3.1M
      CPU: 119ms
   CGroup: /system.slice/snap.lxd.daemon.service
           ‣ 7210 /bin/sh /snap/lxd/11824/commands/daemon.start

Sep 09 14:29:15 R610-LXD2-LAN lxd.daemon[7210]: ==> Rotating logs
Sep 09 14:29:18 R610-LXD2-LAN lxd.daemon[7210]: ==> Setting up ZFS (0.6)
Sep 09 14:29:18 R610-LXD2-LAN lxd.daemon[7210]: ==> Escaping the systemd cgroups
Sep 09 14:29:18 R610-LXD2-LAN lxd.daemon[7210]: ====> Detected cgroup V1
Sep 09 14:29:18 R610-LXD2-LAN lxd.daemon[7210]: ==> Escaping the systemd process resource limits
Sep 09 14:29:18 R610-LXD2-LAN lxd.daemon[7210]: ==> Disabling shiftfs on this kernel (auto)
Sep 09 14:29:18 R610-LXD2-LAN lxd.daemon[7210]: => Re-using existing LXCFS
Sep 09 14:29:18 R610-LXD2-LAN lxd.daemon[7210]: => Killing conflicting LXD (pid=4574)
Sep 09 14:29:18 R610-LXD2-LAN lxd.daemon[7210]: => Starting LXD
Sep 09 14:29:19 R610-LXD2-LAN systemd[1]: Started Service for snap application lxd.daemon.
```

But list is still hanging.

**Comment by truelai** [comment]
I see it says:

Setting up ZFS 

But I'm not running ZFS

**Comment by stgraber** [comment]
This has been sorted offline by reverting the last transaction and applying the db patch from above.
