### ISSUE TITLE
Error: failed to begin transaction: not an error

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#6201]
# Required information

 * Distribution: ubuntu
 * Distribution version: 19.04

# Issue description

I setup a cluster and its been working for a couple of hours

Been making api requests to `/1.0/clusters` and `/1.0/resources` and all kinds of other endpoints no problem,

Then I tried to hit `https://MY_IP:8443/1.0/images?project=default` and I got the response 

```
failed to begin transaction: not an error
```

Then i looked in `/var/log/syslog` and I now have lots of 

```
lvl=warn msg="Failed to get current cluster nodes: failed to begin transaction: not an error"
```
If i go back to the CLI and type any command E.G `lxc info` I get 

```
Error: failed to begin transaction: not an error
```

# Information to attach
I dont know at this point!

**Comment by stgraber** [comment]
Can you try running 'systemctl reload lxd.snap.daemon' on all cluster nodes, see if that makes it recover?

**Comment by turtle0x1** [comment]
```
Failed to reload lxd.snap.daemon.service: Unit lxd.snap.daemon.service not found.
```

Its installed through snap

**Comment by stgraber** [comment]
Ah, sorry, should have been `systemctl reload snap.lxd.daemon`

**Comment by turtle0x1** [comment]
That didn't fix the issue at this point I need to purge and re-install LXD

Usefull debugging information is probably lost as I have had t restart, also I was running a two node cluster (this is a temporary dev thing not a "production" cluster) and LXD now can't connect as a dqlite leader is missing

**Comment by suprasoil** [comment]
I'm running into this issue every once in a while.

1 host in the 3 member cluster will still be responding and telling me all hosts in the cluster are fine, but it will report "state=ERROR" for all containers not on the responding host.

The other 2 hosts will respond with "Error: failed to begin transaction: not an error" for every lxc command and LXD will be a defunct process.

Restarting lxd on the responding node usually solves the problem.

What could be causing this?

**Comment by wmchris** [comment]
i have this problem as well, but all nodes are reporting the same error.
/var/snap/lxd/common/lxd/logs/lxd.log is spammed with
"Failed to get current cluster nodes: failed to begin transaction: not an error"

i cant get any useful information from any log.
using lxd 3.23

**Comment by freeekanayaka** [comment]
Probably a duplicate of #7371
