### ISSUE TITLE
Mounting lxc path from one container to others via profile

### ISSUE THREAD

**Issue by tokiwinter** [lxc/lxd#6214]
Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux node-1 4.4.0-1087-aws #98-Ubuntu SMP Wed Jun 26 05:50:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 3.14
   * LXD version: 3.14
   * Storage backend in use: dir

I'd like to mount a directory among multiple containers. The directory to share is in a container itself.

Could I use a profile to mount this shared directory from one container to the others at boot time?

**Comment by stgraber** [comment]
With the directory backend, you can but it's certainly not something we'd recommend.

Something like: `lxc config device add NAME shared disk path=/shared source=/var/snap/lxd/common/lxd/storage-pools/default/containers/OTHER-NAME/rootfs/PATH` should do the trick

In general we'd recommend you make a custom storage volume with `lxc storage volume create` and then attach it to all containers, that way you don't need to go play behind LXD's back.

Closing as this was a support question.

**Comment by tokiwinter** [comment]
Thanks - I didn't even think about `storage volume`. Awesome.
