### ISSUE TITLE
Allow modification of image expiration field

### ISSUE THREAD

**Issue by Cynerd** [lxc/lxd#6220]
The expiration field for images currently is read-only. The possibility to allow modification of it might allow automatic removal of old images created locally.

Forum post: https://discuss.linuxcontainers.org/t/automatic-local-image-expiration-how-to-set-expires-at/5761

**Comment by stgraber** [comment]
This issue would be a good candidate for a new contributor to tackle.

What needs to happen is effectively:
 - Add an API extension in doc/api-extensions.md
 - Add the matching string in shared/version/api.go
 - Update shared/api/images.go to move ExpiryDate from Image to ImagePut
 - Update lxd/db/images.go to have it accept updating that database field
 - Update lxd/images.go to have ImagePut pass the updated field to the database function (if set)

No changes should be needed to the client, the update to shared/api should be enough to have the field show up in `lxc image edit`.

**Comment by keyallis** [comment]
Myself and my partner from the UT Virtualization class would like to take this issue as part of our class project

**Comment by stgraber** [comment]
Thanks, assigned it to you. Hopefully the instructions I pasted in the previous comment will help you figure out what needs to happen.

I would expect a pull request made of 3 commits for this one:
 - api: Add images_expiry API extension
 - shared/api: Make image ExpiryDate modifiable
 - lxd: Make image ExpiryDate modifiable

This should all be pretty easy to do and a good start to see how to contribute to LXD.

**Comment by piluke** [comment]
Hi, I'm the partner, could I also be assigned?

**Comment by stgraber** [comment]
Done
