### ISSUE TITLE
wrong usage for lxc exec --cwd

### ISSUE THREAD

**Issue by melato** [lxc/lxd#6221]
Client version: 3.17
Server version: 3.17

run:
`lxc exec -h`

result:
In the Flags section, there is a line:

>       --cwd                    Group ID to run the command as (default /root)

This seems to be accidentally copied from the --group flag
I expected something like:

>       --cwd                    Directory to run the command in (default /root)

**Comment by stgraber** [comment]
Sent a PR to fix this
