### ISSUE TITLE
Mount options for disk device mounts

### ISSUE THREAD

**Issue by KsaRedFx** [lxc/lxd#6225]
Currently you can mount a device into a container by adding it as disk to your containers configuration using: `lxc config device add <container> <name> disk source=/dev/<device> path=<relativepath>`

While this works great for basic filesystems like ext4, this makes using specific mount options difficult for anything more complex like btrfs. 

I'm trying to specifically mount a btrfs subvol inside of a container, and while I can always mount it on the host manually, or just include it in the fstab pointing into `/var/snap/lxd/common/lxd/containers/<container>/rootfs/<mountpoint>` with my mount options, it seems like a messy solution especially when you get into multiple mount points, and possibly migrating containers.

Unless I've missed already implemented somewhere, or I should be approaching this differently, I believe this would be a useful feature to add.

**Comment by stgraber** [comment]
So I'm still not fond of the idea (this has been suggested before) but as we don't really have a better answer to it, I suspect a `raw.mount.options` config option on the disk device would probably be okay.

Once we start implementing project restrictions (#6170) this would then get restricted in the same way a `raw.lxc` config option would be.

**Comment by splett2** [comment]
Hi, Lily and I would like to claim this issue for our group.

**Comment by stgraber** [comment]
Excellent, for this one, I expect roughly the following commits:
 - api: Add `container_raw_mount` API extension
   - Add that string to `shared/version/api.go`
   - Add a matching entry to `doc/api-extensions.md`
 - lxd: Add support for `raw.mount.options:
   - Add the new option to `lxd/device/disk.go`
   - Make the logic in `disk.go` add the mount options to the returned RunConfig
   - Add matching logic to pass the flags through to `forkmount` for hotplug
 - tests: Add test for `raw.mount.options`
   - Extend `test/suites/container_devices_disk.sh` to test the new configuration option. One idea to test it would be to use a tiny vfat filesystem on a loop device, add it to the container with some mount options (I'd suggest using uid= and gid=) and confirm that this is properly used in the container.
   - For loop device handling, you'll want to use `truncate` to create a small (10MB should do) file, then use `mkfs.vfat` on top of that file, lastly map it to a loop using our `configure_loop_device` helper, cleaning things up after the test with `deconfigure_loop_device`.
   - The test should validate that this works both on at boot time and when hot plugging the device into the container.

@tomponline should be able to help you with any question you may have regarding this issue.

**Comment by tomponline** [comment]
@splett2 Yep let me know if you have any questions.

**Comment by splett2** [comment]
@tomponline 

I'm guessing most of the logic we're implementing for lxd: Add support for `raw.mount.options:
would be in the Start() function, and I see that there are already a number of mount options. If a user decides to pass in options via raw mount options, should we ignore any other potential mount parameters?

**Comment by stgraber** [comment]
I think raw.mount.options should get appended to anything we already came up with internally

**Comment by splett2** [comment]
Hi, sorry for the radio silence, we ended up busy with projects and other deadlines, we're going to start working on this now.

**Comment by stgraber** [comment]
@splett2 no worries, let us know if you have any questions

**Comment by Lilyjjo** [comment]
Hello, I'm working with David on this project

We saw two places to add logic for the mount options stemming from Start() in disk.go:
1.) Start() calls createDevice() which calls device_utils_disk.go’s DiskMount() which performs a unix.Mount(). We’re thinking of adding the raw.mount.options to this unix call, do you think that is needed? It looks to be creating the device on the host which is unmounted later. 
2.) We see that we’re to add the options to the RunConfig, to handle this added logic, is changing insertMountLCX() and insertMountLXD() in the right direction?

**Comment by stgraber** [comment]
@Lilyjjo Indeed the main spot to pass the extra mount options is the first `unix.Mount` call in `DiskMount`. I'd suggest adding an extra argument to `DiskMount` allowing for arbitrary mount options to be passed through, passing those to `unix.Mount`.

I don't think you actually need to do anything about RunConfig as that part of the mount handling is only about telling liblxc to bind-mount the device mount into the container. We don't really care about the mount options on that bind-mount, what matters is the mount options on the original mount which is what `createDevice` and `DiskMount` do.

**Comment by stgraber** [comment]
(I realize I'm the one who mentioned RunConfig/forkmount, as it turns out, we only use those two approaches to inject a bind-mount into the container, so don't actually need to touch those at all so long as the initial mount of the device is correct)

**Comment by Lilyjjo** [comment]
Hi,

David and I are a little stuck. We’ve changed the device config and passed the raw.mount.options to the unix.Mount() commands inside of DiskMount() but we’re not seeing the changes reflected in the container.

Here’s how we’re setting up the loop device on the host:
Make a new file file.txt, truncate it to 10M
run: sudo losetup —show -f file.txt (This creates dev/loop9)
run: sudo mkfs.vfat /dev/loop9
(That’s all we did to set up the loop device)

Then we’re running these commands for lxc:
lxc config device add first vfat1 disk source=/dev/loop9 path=/mnt/test raw.mount.options=gid=123,uid=456
And then run:
lxc exec first — stat /mnt/test 
We’re not seeing the gid/uid changes being made. We’re not sure why this is the case. 

We’re not sure if we need to mount the loop device on the host or modify any fstabs. We’re wondering if you see anything wrong with what we’re doing. 

Thanks

**Comment by stgraber** [comment]
@Lilyjjo What does `grep loop9 /proc/mounts` show on the host? Do you see uid/gid being set there?

Does everything show up as nobody/nogroup in the container?
If so, you need to test with a privileged container to make this easier.
`lxc config set first security.privileged true && lxc restart first` should take care of that.

**Comment by Lilyjjo** [comment]
@stgraber 
Hi, we were able to test with the privileged container and verified that the raw mount options are getting passed in correctly. We also wrote an integration test, and we're trying to run the bash scripts for integration testing, but we're getting an error:

==> Checking for dependencies
==> Available storage backends: dir btrfs lvm
==> Using storage backend dir
==> Setting up directory backend in /home/lily/go/src/github.com/lxc/lxd/test/tmp.RiI/VlR
==> Spawning lxd in /home/lily/go/src/github.com/lxc/lxd/test/tmp.RiI/VlR
==> Spawned LXD (PID is 7132)
==> Confirming lxd is responsive
lxd: error while loading shared libraries: libdqlite.so.0: cannot open shared object file: No such file or directory
lxd: error while loading shared libraries: libdqlite.so.0: cannot open shared object file: No such file or directory
==> Cleaning up
cat: /home/lily/go/src/github.com/lxc/lxd/test/tmp.RiI/macaroon-identity.pid: No such file or directory
./main.sh: 28: kill: Illegal number: 
==> Killing LXD at /home/lily/go/src/github.com/lxc/lxd/test/tmp.RiI/VlR
==> Tearing down directory backend in /home/lily/go/src/github.com/lxc/lxd/test/tmp.RiI/VlR

We aren't sure why this is happening considering we're able to run LXD without issue manually, but it fails to load when running the test script.

**Comment by stgraber** [comment]
@Lilyjjo hmm, not sure what's causing that one. Could be that some of the `export` are missing, especially the `LD_LIBRARY_PATH` one?

You can probably sort out your commits and open a pull request, then I can have a look at the tests and if all looks fine, have jenkins run them.

**Comment by Lilyjjo** [comment]
@stgraber we've made the pull request for this issue, it's named raw_mount_options https://github.com/lxc/lxd/pull/6429
