### ISSUE TITLE
lxd/lxc hwaddr only accepts lower case letters

### ISSUE THREAD

**Issue by captainwasabi** [lxc/lxd#6232]
If a containers hwaddr contains any upper case letters the container will fail to start.

# Steps to reproduce

 1.Set the container to have uppercase letters in it's mac address
 2. Try to start the container
 3. See error message

MAC addresses should definitely be allowed to have upper case letters in their mac addresses, unless something has changed recently the usage of uppercase would be considered "more standard" than lower-case.  If you look at the Wikipedia page on MAC addresses ALL the examples are upper-case.

**Comment by stgraber** [comment]
So this isn't the first time someone gets annoyed by the stricter validation from 3.16 and higher so we should allow both cases and just bring everything to lower before using it.
