### ISSUE TITLE
Implement initial LXD VM agent

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#6234]
As part of the work to get LXD virtual machine support (#6205), some features will need the assistance of an agent in the VM.

# API
The agent will listen over a vsock, running an HTTPS server with a REST API similar to what LXD itself does. The address should be ANY and port should be 8443.

For the initial implementation, we're looking at getting the following API endpoints implemented:
 - /1.0 (basic agent information, similar to /1.0 on LXD API)
   - api_extensions
   - api_status
   - api_version
   - environment (excluding storage, clustering, project, features, driver and addresses)
 - /1.0/exec (same as /1.0/instances/NAME/exec)
 - /1.0/file (same as /1.0/instances/NAME/file)
 - /1.0/operations (used to support /1.0/exec)
 - /1.0/state (same as /1.0/instances/NAME/state)

# Security
The agent will need the following to start up:
 - Public certificate of the LXD host (`server.crt`)
 - Its own key pair, generated by LXD during initial VM startup

All incoming connections from LXD will be checked against the public certificate and LXD will similarly be checking the public key of the agent to match the one it has on disk.

This will prevent anyone else on the host or VM to spoof LXD or the LXD agent.

# Communication from LXD
LXD will directly connect to the agent when some data is needed.
To avoid long delays in `lxc list` we will run a goroutine in charge of keeping a list of VMs that have a running agent. When a VM is started, it gets marked as having its agent offline. Every 10s the go-routine attempts to connect to the VMs marked as offline, if reachable, they get marked online. When we fail to send an agent request, we flip the VM back to offline, leaving it up to the goroutine to ping it regularly until it's back up.

Eventually we will want something more clever using a second host side vsock and having the agents directly contact LXD, but this is quite a bit trickier, especially when considering multiple instances of the LXD daemon running on the same kernel. So we'll be tackling this aspect when we actually have to.

# Notes
Whenever possible, code duplication should be avoided by moving the relevant logic into its own separate package, used by both core LXD and the LXD agent codebase.

Agent codebase should be in a separate top-level `lxd-agent` directory.

**Comment by turtle0x1** [comment]
Please scrape CPU load avgs this should be a non-issue compared to using lxcfs right ?

**Comment by mdlayher** [comment]
Hello! I was linked here by a friend. You may be interested in my vsock package for Go: https://github.com/mdlayher/vsock. Hope this helps your efforts.

**Comment by stgraber** [comment]
@mdlayher We've been using your package for a quick prototype we wrote last week. One issue we have though is that a rather significant part of our user base is on Go 1.10, so we'll either need to find a way to get this working on 1.10 or deal with the issues that would come with raising our own minimal Go version to 1.11.

**Comment by mdlayher** [comment]
Unfortunately you are going to have to deal with a lot of headaches unless you're using at least Go 1.11 and possibly Go 1.12. The hooks that allow the package to efficiently work with the go runtime and enable the use of timeouts simply do not exist before Go 1.11.

That said, I am willing to accept patches if you can get some reasonable subset of functionality working on Go 1.10.
