### ISSUE TITLE
Support device keys as `lxc list` columns

### ISSUE THREAD

**Issue by itisnotdone** [lxc/lxd#6275]
It would be great if we can add custom columns for devices when using multiple virtual networks for multiple Envs.
For example, `lxc list --columns devices.eth0.parent`

I wasn't able to find any docs or use cases that explains it so I assume this could be a new feature.

**Comment by stgraber** [comment]
That particular syntax would be a potential problem as we may one day introduce a `devices` namespace for config keys, which would then cause a conflict.

I think we'll want to switch the format to support both:
 - [config:]key[:name][:maxWidth}
 - devices:key[:name][:maxWidth}

So in your case, you'd be using: lxc list -c devices:eth0.parent

**Comment by stgraber** [comment]
This should be a pretty easy issue, especially as we already have testing in place for `lxc list`'s current behavior. I expect someone interested in implementing this would need to:
 - Modify `parseColumns` in `lxc/list.go` to allow for the `config:KEY:NAME:WIDTH:` syntax
 - Add extra tests in `lxc/list_test.go` to test the `config:KEY:NAME:WIDTH` syntax and confirm nothing regressed
 - Add support for `devices:KEY:NAME:WIDTH` to `parseColumns` in `lxc/list.go`
 - Add more tests to `lxc/list_test.go` to validate support for `devices:KEY:NAME:WIDTH`

**Comment by srados** [comment]
I could try to fix this one

**Comment by stgraber** [comment]
Sure! Assigning it to you.
