### ISSUE TITLE
Failed to start the daemon: Failed to start dqlite server: failed to start task

### ISSUE THREAD

**Issue by Buri** [lxc/lxd#6298]
# Required information

 * Distribution: OpenSUSE Tumbleweed
 * Distribution version: 20191007
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.3.2-1-default
   * LXD version: 3.18
   * Storage backend in use: btrfs

# Issue description

Daemon fails to start. Happened with upgrade to 3.18. Reproducible always. Installed via native package (no modifications by distro)

# Steps to reproduce

 1. systemctl start lxd

# Information to attach

 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
the issue)
```
t=2019-10-09T14:53:52+0200 lvl=info msg="LXD 3.18 is starting in normal mode" path=/var/lib/lxd
t=2019-10-09T14:53:52+0200 lvl=info msg="Kernel uid/gid map:" 
t=2019-10-09T14:53:52+0200 lvl=info msg=" - u 0 0 4294967295" 
t=2019-10-09T14:53:52+0200 lvl=info msg=" - g 0 0 4294967295" 
t=2019-10-09T14:53:52+0200 lvl=info msg="Configured LXD uid/gid map:" 
t=2019-10-09T14:53:52+0200 lvl=info msg=" - u 0 400000000 500000001" 
t=2019-10-09T14:53:52+0200 lvl=info msg=" - g 0 400000000 500000001" 
t=2019-10-09T14:53:52+0200 lvl=warn msg="Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored." 
t=2019-10-09T14:53:52+0200 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." 
t=2019-10-09T14:53:52+0200 lvl=info msg="Kernel features:" 
t=2019-10-09T14:53:52+0200 lvl=info msg=" - netnsid-based network retrieval: yes" 
t=2019-10-09T14:53:52+0200 lvl=info msg=" - uevent injection: yes" 
t=2019-10-09T14:53:52+0200 lvl=info msg=" - seccomp listener: yes" 
t=2019-10-09T14:53:52+0200 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2019-10-09T14:53:52+0200 lvl=info msg=" - shiftfs support: no" 
t=2019-10-09T14:53:52+0200 lvl=info msg="Initializing local database" 
t=2019-10-09T14:53:52+0200 lvl=dbug msg="Initializing database gateway" 
t=2019-10-09T14:53:52+0200 lvl=dbug msg="Start database node" address= id=1
t=2019-10-09T14:53:52+0200 lvl=eror msg="Failed to start the daemon: Failed to start dqlite server: failed to start task" 
t=2019-10-09T14:53:52+0200 lvl=info msg="Starting shutdown sequence" 
t=2019-10-09T14:53:52+0200 lvl=dbug msg="Not unmounting temporary filesystems (containers are still running)" 
```

**Comment by freeekanayaka** [comment]
Please can you try to start the daemon from the console and paste the output? This command line below should work:

```
LXD_DIR=/var/snap/lxd/common/lxd LD_LIBRARY_PATH=/snap/lxd/current/lib/ /snap/lxd/current/bin/lxd --verbose --debug
```

**Comment by stgraber** [comment]
Did your system recently run out of disk space?

That's the most common source of such issues.

Can you show a directory listing of the `database/global` directory?

**Comment by Buri** [comment]
```
hydra:/var/lib/lxd # ls -la database/global/
celkem 9628
drwxr-x--- 1 root root     104  9. říj 16.28 .
drwx------ 1 root root      52  8. říj 21.36 ..
-rw------- 1 root root  339968  8. říj 21.16 db.bin
-rw------- 1 root root  618032  8. říj 21.16 db.bin-wal
-rw------- 1 root root      32  9. říj 16.28 metadata1
-rw------- 1 root root      32  9. říj 16.28 metadata2
-rw------- 1 root root      64  7. říj 20.45 1-1
-rw------- 1 root root  882480  7. říj 21.23 16-74
-rw------- 1 root root  501680  7. říj 20.45 2-15
-rw------- 1 root root 7495704  8. říj 21.16 75-784
```

No space related issues as far as i know. 

```
hydra:/var/lib/lxd # btrfs fi usage /
Overall:
    Device size:                  21.83TiB
    Device allocated:              6.41TiB
    Device unallocated:           15.42TiB
    Device missing:                  0.00B
    Used:                          6.40TiB
    Free (estimated):              7.71TiB      (min: 7.71TiB)
    Data ratio:                       2.00
    Metadata ratio:                   2.00
    Global reserve:              512.00MiB      (used: 0.00B)
```

**Comment by Buri** [comment]
Would it be possible that if snapshot was taken at the moment when lxd was writing to the database and then the snapshot was restored that it would result in corrupted database?

**Comment by stgraber** [comment]
Assuming said snapshot included the LXD database directory, then yeah, LXD would certainly not appreciate database transaction files getting reverted or just disappearing.

Based on the output you've given above, your database was never cleanly stopped as a clean stop would have generated a snapshot file. Instead you only have a few segment files from the database's first startup until now.

Moving aside the last one (`75-784`) will most likely let you bring the database back online, but it will be at the same state it was at 21:23 on the 7th, missing potentially a lot of transactions.

There is however a good chance that any lost data could be manually recovered from the `db.bin` file, assuming that it wasn't also corrupted.

So I'd recommend you do:
 - cp -r database database.bak
 - rm database/global/75-784
 - lxd --debug ---group lxd

See what the state of things is like. If you somehow get all your containers and images, then you're lucky and can just keep things as they are.

If those steps result in many missing container/images, then send me a tarball of your `database` directory to stgraber at ubuntu dot com and I'll see if I can recover the rest of the data from the `db.bin` file somehow.

**Comment by Buri** [comment]
Thanks for the offer. The server has no critical data on it, so just bringing daemon online is good enough. My question however would be if it is for scope lxd to have some way of journaling in a similar fashion like Mysql/Postgres, which can recover from unclean shutdown/filesystem snapshot?

If not, we can close this issue. Thanks for the help. :)

**Comment by stgraber** [comment]
The LXD database uses Raft to handle its transactions, sqlite transactions get added to the raft log which gets written to disk as part of segment files. We then have automated snapshots that occur whenever enough segments have been written or during clean shutdown. On startup, the latest snapshot is used, then the subsequent transactions applied from the segment files.

In the event that the last segment file got corrupted, as is the case for you, we can get back to a consistent state by removing the segment, this does however cause data loss as your database goes back in time.

We don't feel that it's usually a good idea to discard the last segment automatically as some other database may do, especially when you also have to consider the clustered LXD case where the segments need to match on at least two systems.

So we're certainly looking at ways to limit the potential data loss in such cases but automatically recovering seems too risky and effectively impossible in clustered cases.

We do have an issue open for LXD to add more tooling so that one can get more details on such issues, including getting some information on the segments and have LXD itself delete the last segment and attempt to show you any data that may need to be manually re-added (attempting to read `db.bin` and comparing that to the replayed raft state).

This is tracked in #5550
