### ISSUE TITLE
Add ability to pass password as an argument

### ISSUE THREAD

**Issue by benbooth493** [lxc/lxd#630]
When issuing lxc remote add the user is prompted to enter the admin password of the remote host.
The make automation easier it would be helpful if -p could be added to pass the password as an argument.

**Comment by stgraber** [comment]
--password is actually something that's defined in the specification (specs/command-line-user-experience.md) but hasn't been implemented.

Feel free to send a pull request for it.

**Comment by benbooth493** [comment]
I'll look into it

**Comment by benbooth493** [comment]
Submitted pull request https://github.com/lxc/lxd/pull/643

**Comment by stgraber** [comment]
This has now been merged (branch didn't include a Closes reference so this didn't get auto-closed on merge).
