### ISSUE TITLE
[FEATURE] fanotify support inside container

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#6303]
It there any possible way of using fanotify inside LXD container?

**Comment by brauner** [comment]
On Thu, Oct 10, 2019, 15:57 s3rj1k <notifications@github.com> wrote:

> It there any possible way of using fanotify inside LXD container?
>

A lot of it is guarded by CAP_SYS_ADMIN in the initial user namespace so
very unlikely.

I've once talked to the maintainers and they were open to removing this
check. So far nothing happened and I don't remember whether or not this
required work or not...
