### ISSUE TITLE
CGroup abstraction and parity between V1/V2

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#6305]
So far for LXD, we've done some very minimal work to have it work on CGroupV2, but that work does not currently include support for any of the limits we support on CGroupV1.

Low level `liblxc` has support for setting up CgroupV2 controllers, so the bulk of this is to provide it suitable configuration and to update the logic we have driving Cgroups after startup to also work with CGroupV2.

To do so, I believe we'll want to introduce an abstraction layer, effectively a single struct likely in our new `cgroup` package which we can call from wherever we need cgroup changes done, it would then support detecting if a particular controller is handled by v1 or v2 and give us the key/value we need to feed to liblxc, either through configuration or through the cgroupset API.

**Comment by Namit-Agrawal** [comment]
I would like to work on this.

**Comment by stgraber** [comment]
Per our e-mail discussion, I suspect the main steps for this will be:
 - Build up a list of all the CGroupV1 files that we interact with today
 - Figure out the equivalent for each of those in the CGroupV2 world
 - Create a set of functions in the "cgroup" package which covers our current use of cgroups and switch over to using them
 - Add functions to detect whether a particular controller is present on the system and if so whether it's using cgroupv1 or cgroupv2
 - Using those functions, update the functions in the cgroup package to detect and handle cgroupv2 resource controllers

To find all the current uses, you can look around for `lxc.cgroup` (liblxc config file) or `CGroupGet` and `CGroupSet` which are the functions used to do live changes.

For testing, your best bet is a recent Ubuntu system, at least 18.04, quite possible 19.10 at this point. This will default to a hybrid v1/v2 setup where all controllers are v1 but a v2 hierarchy exists.

To switch to cgroupv2 only, you can boot the system with `systemd.unified_cgroup_hierarchy=true` on the kernel command line which should result in only a cgroupv2 hierarchy in /sys/fs/cgroup.

Good contacts for this work are @brauner (who did liblxc cgroupv2), @tomponline (who has quite a bit of experience with those kind of refactoring) and myself for the rest of the LXD knowledge.

**Comment by shreyassood** [comment]
@stgraber I would like to contribute as well -- could you please assign me to the issue as well?

**Comment by lucindan** [comment]
Hi Stéphane,
we're having trouble trying to set up LXD. When we do the Machine Setup
part, we run into a segfault.
[image: image.png]
This is our output when we tried running it with GDB
[image: image.png]
Do you have ideas on what we could do to fix this?
Thanks,
Lucinda

**Comment by stgraber** [comment]
Hi @lucindan the screenshot didn't make it to github I'm afraid so it's a bit hard to help :)

The mention of a segfault makes me think of a broken dqlite setup, did you make sure that the terminal you're running `lxd` from has those `export` variables that `make deps` gave you?

If not, it'd be missing the correct `LD_LIBRARY_PATH` which usually results in a segfault during DB initialization.

**Comment by aadi123** [comment]
Here is some output that might be helpful

```
aaditya@pop-os:~$ sudo -E LD_LIBRARY_PATH=$LD_LIBRARY_PATH $GOPATH/bin/lxd --group sudo
WARN[10-29|21:14:19] Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored. 
WARN[10-29|21:14:19] CGroup memory swap accounting is disabled, swap limits will be ignored. 
Segmentation fault
aaditya@pop-os:~$ echo $LD_LIBRARY_PATH
/home/aaditya/go/deps/sqlite/.libs/:/home/aaditya/go/deps/dqlite/.libs/:/home/aaditya/go/deps/raft/.libs:/home/aaditya/go/deps/libco/:
aaditya@pop-os:~$ echo $CGO_CFLAGS
-I/home/aaditya/go/deps/sqlite/ -I/home/aaditya/go/deps/dqlite/include/ -I/home/aaditya/go/deps/raft/include/ -I/home/aaditya/go/deps/libco/
aaditya@pop-os:~$ echo $CGO_LDFLAGS
-L/home/aaditya/go/deps/sqlite/.libs/ -L/home/aaditya/go/deps/dqlite/.libs/ -L/home/aaditya/go/deps/raft/.libs -L/home/aaditya/go/deps/libco/
aaditya@pop-os:~$ 
```

**Comment by stgraber** [comment]
@aadi123 that's pretty odd. Can you run with `--debug`.

Also, @freeekanayaka has been doing some fixes around the database logic so maybe you got unlucky and built at a time things were inconsistent, you could run `make deps` again to update those bits and see if that helps.

**Comment by stgraber** [comment]
@aadi123 @freeekanayaka and I have now reproduced that failure on our systems too, looking into it.

**Comment by stgraber** [comment]
looks like building libraft with --enable-debug fixes it :)

**Comment by stgraber** [comment]
@aadi123 this has now been resolved, running `make deps` should refresh your copy of libraft and let LXD run.

**Comment by aadi123** [comment]
@stgraber I am also part of the group from UT Austin working on this issue. Could I be assigned? Thanks.

**Comment by stgraber** [comment]
Done

**Comment by lucindan** [comment]
@brauner  ,we're having trouble creating the struct that will capture the c group hierarchy at startup, Would this be the same as the struct hierarchy that is in lxc  (at https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgroup.h ) ?  Or would it be struct that has  a list of controllers that we would set to 0,1,2 depending on their c group version (0= not enabled, 1 = c group v1, 2= c group v2)

**Comment by brauner** [comment]
> @brauner, we're having trouble creating the struct that will capture the c group hierarchy at startup, Would this be the same as the struct hierarchy that is in lxc (at https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgroup.h ) ? Or would it be struct that has  a list of controllers that we would set to 0,1,2 depending on their c group version (0=not enabled, 1=c group v1, 2=c group v2)

What struct do you want to recreate and why exactly?
LXD would likely only need to:
- find out whether the host is a pure unified layout, e.g. by doing:
```c
static int cg_is_pure_unified(void)
{

	int ret;
	struct statfs fs;

	ret = statfs(DEFAULT_CGROUP_MOUNTPOINT, &fs);
	if (ret < 0)
		return -ENOMEDIUM;

	if (is_fs_type(&fs, CGROUP2_SUPER_MAGIC))
		return CGROUP2_SUPER_MAGIC;

	return 0;
}
```
(just in go)
- check for various controllers and record them similar to what we do now for the various v1 controllers. controllers are files in v2, e.g. to detect memory controller support you'd check for `memory.stat` or another file, for `io` you could stat `io.max` etc. pp.

**Comment by lucindan** [comment]
Hi @brauner 
we're having some issues for the memory controller, particularly the memory.memsw. 
For v1, `memory.memsw.limit_in_bytes`	  set/show limit of memory+Swap usage
For v2, `memory.swap.max`                           set/show  Swap usage hard limit. 

Currently, our abstraction layer is designed so that container_lxc.go will called `PidsCurrent()` and we return the correct key depending on the controller version. 

But for memory, would `CgroupGet("memory.memsw.usage_in_bytes")` , should we call `CgroupGet("memory.current")` + `CgroupGet("memory.swap.current")`
 to get the same result? For the other specific files that have no equivalences in v2 world, we will just throw an error if it's a v2 controller. 

Could you offer feedback for our design?

**Comment by brauner** [comment]
> Hi @brauner
> we're having some issues for the memory controller, particularly the memory.memsw.
> For v1, `memory.memsw.limit_in_bytes` set/show limit of memory+Swap usage
> For v2, `memory.swap.max` set/show Swap usage hard limit.
> 
> Currently, our abstraction layer is designed so that container_lxc.go will called `PidsCurrent()` and we return the correct key depending on the controller version.

The relevant controllers are detected once at startup, I assume.

> 
> But for memory, would `CgroupGet("memory.memsw.usage_in_bytes")` , should we call `CgroupGet("memory.current")` + `CgroupGet("memory.swap.current")`
> to get the same result? For the other specific

Yes, that makes sense.

files that have no equivalences in v2 world, we will just throw an error if it's a v2 controller.

Yeah, that's fine.

**Comment by brauner** [comment]
Note that you should test your changes with a liblxc version from master. Not sure how you development environment looks like. Do you use the edge snap a d sideload `lxd.debug` or do you compile and run directly? In the latter case you would have to use the lxc-git-master ppa assuming you're on Ubuntu.

**Comment by shreyassood** [comment]
Hi @brauner @stgraber, we ran it with the lxc ppa and created the first PR: https://github.com/lxc/lxd/pull/6575

We're planning on adding other controllers and utilizing our `SetConfigMap` method for setting the `lxcSetConfigItem` items in another PR along with adding functionality to detect the current controller version. Would appreciate your feedback!

**Comment by shreyassood** [comment]
Hi @stgraber @brauner, we added some code to use the modified abstraction in https://github.com/lxc/lxd/pull/6600 and would love your feedback -- thank you!
