### ISSUE TITLE
member_config null

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#6312]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 19.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version: 3.18
   * Storage backend in use: dir

# Issue description
When asking for cluster info E.G `curl --unix-socket /var/lib/lxd/unix.socket s/1.0/cluster` I get the response 

>{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{"server_name":"cluster-node1","enabled":true,"member_config":null}}

"member_config" should not be null right?

**Comment by stgraber** [comment]
It could be if you don't have any member specific config keys for your network or storage, though I'd probably expect it to be an empty list instead.

**Comment by turtle0x1** [comment]
When i try to join a server to the cluster with empty config it says it doesnt match

**Comment by stgraber** [comment]
Just checked and I do get an empty member_config on a system which doesn't need configuration, so the fact that it's null for you suggests something failed but didn't result in an error being returned...

Can you run `lxc monitor` at the same time as you run your curl to see if anything useful is logged?

**Comment by turtle0x1** [comment]
metadata:
  context: {}
  level: dbug
  message: Successful heartbeat for 10.233.30.73:8443
node: 2
timestamp: "2019-10-13T20:26:08.298532484Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Completed heartbeat round
node: 2
timestamp: "2019-10-13T20:26:08.306967516Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Skipping heartbeat since we're not leader
timestamp: "2019-10-13T20:26:09.132775055Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Starting heartbeat round
timestamp: "2019-10-13T20:26:09.132692207Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/cluster
  level: dbug
  message: handling
timestamp: "2019-10-13T20:26:11.327927251Z"
type: logging

Anything ?

**Comment by stgraber** [comment]
Nope

**Comment by stgraber** [comment]
Can you show:
 - lxc network list
 - lxc storage list

And "lxc network show" for any managed network and "lxc storage show" for all storage pools?

**Comment by turtle0x1** [comment]
+---------+--------+---------+-------------+---------+---------+
|  NAME   |  TYPE  | MANAGED | DESCRIPTION | USED BY |  STATE  |
+---------+--------+---------+-------------+---------+---------+
| lxdfan0 | bridge | YES     |             | 4       | CREATED |
+---------+--------+---------+-------------+---------+---------+


+-------+-------------+--------+---------+---------+
| NAME  | DESCRIPTION | DRIVER |  STATE  | USED BY |
+-------+-------------+--------+---------+---------+
| local |             | dir    | CREATED | 3       |
+-------+-------------+--------+---------+---------+

**Comment by stgraber** [comment]
Do you get the same result running that command on both nodes?

**Comment by turtle0x1** [comment]
Yeah

**Comment by stgraber** [comment]
Weird, is that on x86_64?

If so, I can give you a test binary to side load to try to figure out what's going on.

**Comment by turtle0x1** [comment]
Yeah sure

**Comment by stgraber** [comment]
- sudo curl https://dl.stgraber.org/lxd-6312 -o /var/snap/lxd/common/lxd.debug
 - sudo chmod +x /var/snap/lxd/common/lxd.debug
 - systemctl reload snap.lxd.daemon
 - lxc query /1.0/cluster
 - grep stgraber /var/snap/lxd/common/lxd/logs/lxd.log

Sha256 of the file should be 4b01a9d1dcecbadb01ce6e34dc345377b5146b0bf23c548e4fb1473a2ae6fcd8

**Comment by turtle0x1** [comment]
Hmm when i run `sudo systemctl reload snap.lxd.daemon`

I get 

```
snap.lxd.daemon.service is not active, cannot reload.
```

**Comment by stgraber** [comment]
That's, hmm, unexpected. What does `systemctl -a | grep lxd` show you?

**Comment by turtle0x1** [comment]
Im sorry, i didn't realize this is 3.0.3 I assumed the ubuntu image wouldn't come with LXD installed so I did `snap install lxd` and have assumed that its 3.18 :disappointed:

**Comment by stgraber** [comment]
Ah, that'd explain it too, cluster_config isn't supported on 3.0.x so would show up as nil in the json output.

And indeed if you're mixing 3.18 and 3.0.3 in the same cluster, I'd expect that join failure.

**Comment by stgraber** [comment]
@turtle0x1 can you confirm that running everything on 3.18 behaves as expected?

**Comment by turtle0x1** [comment]
Yeah I need to sleep, Ill close this out and re-open when i can check tomorrow evening!
