### ISSUE TITLE
Switch to per-container idmap

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#632]
Currently our code uses d.idMap pretty much everywhere. That refers to the default idMap as read from /etc/subuid and /etc/subgid when lxd is started.

However we have privileged containers where the idmap of the container should be the same as lxd's own idmap (typically the whole range of uid and gid).

To reduce confusion, we should have a idMap tied to the container struct which will always be right. So for unprivileged containers, contain the expected idMap, for privileged containers, contain the whole range of uid/git.

**Comment by tych0** [comment]
+1, then we could avoid having privileged checks everywhere.
