### ISSUE TITLE
LXD image import metadata.yaml not found

### ISSUE THREAD

**Issue by fulcrum29** [lxc/lxd#6329]
I am trying to import image tarball created out of untared exported image.
When i run `lxc image import prbf2-reserves-backu.tar.gz --alias prbf2-reserves-backup`
the error occurs
`Error: Could not extract image metadata.yaml from tar: Failed to run: tar -O -zxf /var/lib/lxd/images/lxd_build_953046405/lxd_post_144107296 metadata.yaml: tar: metadata.yaml: Not found in archive
tar: Exiting with failure status due to previous errors (tar: metadata.yaml: Not found in archive)`
Despite the fact that metdata.yaml is in the tarball
 `tar tf prbf2-reserves-backup.tar.gz | grep metadata.yaml
prbf2-reserves-backup/metadata.yaml`

 1. lxc snapshot 
 2. lxc publish
 3. lxc image export 
 4. tar -xvzf exported-image.tar.gz -C exported-image/
 5. tar -cvzf exported-image.tar.gz exported-image/
 6. lxc image import exported-image.tar.gz

Distro: Ubuntu 18.04
Storage backend: Directory
driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-64-generic
  server: lxd
  server_version: 3.0.3

**Comment by stgraber** [comment]
Does the original tarball as returned by `lxc image export` import properly back into LXD?

If so, then there's something wrong in your repack stage which causes the metadata.yaml to either be moved inside a directory or some prefix added to its path (we've see `./metadata.yaml` for example in the past).

**Comment by stgraber** [comment]
Indeed, this image repacking process is incorrect:

```
root@edfu:~# lxc launch images:alpine/edge a1
Creating a1
Starting a1
root@edfu:~# lxc snapshot a1
root@edfu:~# lxc publish a1/snap0
Container published with fingerprint: bf8ca4958f9fd826f0bb55534184b9fddb2383648fbc07890502c352ca57bd0c
root@edfu:~# lxc image export bf8ca4958f9fd826f0bb55534184b9fddb2383648fbc07890502c352ca57bd0c
Image exported successfully!          
root@edfu:~# tar tzvf bf8ca4958f9fd826f0bb55534184b9fddb2383648fbc07890502c352ca57bd0c.tar.gz | grep metadata
-rw-r--r-- root/root       660 2019-10-21 13:00 metadata.yaml
root@edfu:~# mkdir exported-image
root@edfu:~# tar -xzf bf8ca4958f9fd826f0bb55534184b9fddb2383648fbc07890502c352ca57bd0c.tar.gz -C exported-image/
root@edfu:~# tar -czf exported-image.tar.gz exported-image/
root@edfu:~# tar tzvf exported-image.tar.gz | grep metadata
-rw-r--r-- root/root       660 2019-10-21 13:00 exported-image/metadata.yaml
root@edfu:~# 
```
