### ISSUE TITLE
Dir Quota on XFS, broken?

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#6330]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 18.04.3
 * Kernel version: 4.15.0-66-generic
 * LXC version: 3.2.1
 * LXD version: 3.17, 3.18 (Snap)
 * Storage backend in use: dir
 * Mounts:
```
/dev/md1 on / type xfs (rw,relatime,attr2,inode64,prjquota)
/var/lib/snapd/snaps/core_7917.snap on /snap/core/7917 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/lxd_11985.snap on /snap/lxd/11985 type squashfs (ro,nodev,relatime,x-gdu.hide)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,noexec,relatime,size=204180k,mode=755)
nsfs on /run/snapd/ns/lxd.mnt type nsfs (rw)
tmpfs on /var/snap/lxd/common/ns type tmpfs (rw,relatime,size=1024k,mode=700)
nsfs on /var/snap/lxd/common/ns/shmounts type nsfs (rw)
nsfs on /var/snap/lxd/common/ns/mntns type nsfs (rw)
```
 * Kernel cmdline: ```BOOT_IMAGE=/vmlinuz-4.15.0-66-generic root=UUID=d0e1e3ef-78e4-4f45-98ce-e5df55a05b37 ro quiet splash rootflags=prjquota```
 * Quota configured inside CT:
```
root:
  path: /
  pool: default
  size: 8GB
  type: disk
```

Issue with ```quota enforcing```, ```disk usage counting```.

 - Inside CT I can see with ```df``` that quota is enabled. 
 - Then I try to create large file using ```dd if=/dev/urandom of=big.img bs=1 count=0 seek=10G``` I expect to see failed command with disk full error.
 - Command does not fail and creates 10G file.
 - Checking disk usage with ```df``` also does not show that counters go up.

**Comment by stgraber** [comment]
Ok, so modifying the `size` property directly causes `df -h` in the container to update to the correct value?

If so, then we've properly updated the xfs project quota, any issue after that would most likely be a filesystem bug.

**Comment by s3rj1k** [comment]
@stgraber, yes ```size``` updates ```df -h``` output.
XFS quota works then I use cli tools directly to setup project quota (```xfs_quota```)

**Comment by stgraber** [comment]
Yeah, the problem there is that there are two kernel APIs, there is the old xfs-specific one (which xfs_quota uses) and the new generic one which LXD uses to configure both ext4 and xfs.

So it's possible that xfs either needs extra initialization to support the standard one or that there is some kind of kernel bug getting in your way here.

**Comment by stgraber** [comment]
What does `repquota -avugP` get you?

**Comment by s3rj1k** [comment]
```
*** Report for project quotas on device /dev/md1
Block grace time: 7days; Inode grace time: 7days
                        Block limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
#0        -- 4299828       0       0          98858     0     0       
#10001    --  699388       0 7812500          35843     0     0       

*** Status for project quotas on device /dev/md1
Accounting: ON; Enforcement: ON
Inode: #4279069 (2 blocks, 2 extents)
```

**Comment by stgraber** [comment]
Ok, so that does show a hard 8GB limit applied for containerid 1 with about 10% of the allocation used... Does that match up with what `df` show you?

**Comment by s3rj1k** [comment]
```
root@test:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/md1        7.5G  683M  6.8G   9% /
none            492K  4.0K  488K   1% /dev
udev            976M     0  976M   0% /dev/tty
tmpfs           100K     0  100K   0% /dev/lxd
tmpfs           100K     0  100K   0% /dev/.lxd-mounts
tmpfs           997M     0  997M   0% /dev/shm
tmpfs           997M  140K  997M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           997M     0  997M   0% /sys/fs/cgroup
```

**Comment by s3rj1k** [comment]
look correct

**Comment by stgraber** [comment]
Ok, so matches with what the kernel projquota API reports perfectly.

**Comment by s3rj1k** [comment]
Hmm, works as expected on 5.0.x kernel, I'll test with ext4 and newer kernel. Will open new issue if problem recurs.
Thanks.
