### ISSUE TITLE
Rename/Move using a shell script fails reliably - PATH issue?

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#6331]
LXD 3.18 from Snap on Ubuntu Bionic

Issuing a `/snap/bin/lxc rename somename newname` or `/snap/bin/lxc move somename newname` invoked by a script always results in the message:

> Error: rename /var/snap/lxd/common/lxd/storage-pools/lxd/containers/somename /var/snap/lxd/common/lxd/storage-pools/lxd/containers/newname: file exists

If run manually from a terminal, the command succeeds. The script is being run as root. The LXD log doesn't reveal much - here are log lines showing the script failing to rename and a manual run afterwards which works:

> t=2019-10-21T21:10:48+0200 lvl=info msg="Renaming container" created=2018-04-24T21:25:23+0200 ephemeral=false name=byggeboks newname=byggebokssoftdelete25 project=default used=2019-02-11T22:47:37+0100
> t=2019-10-21T21:10:48+0200 lvl=eror msg="Failed renaming container" created=2018-04-24T21:25:23+0200 ephemeral=false name=byggeboks newname=byggebokssoftdelete25 project=default used=2019-02-11T22:47:37+0100
> t=2019-10-21T21:14:00+0200 lvl=info msg="Renaming container" created=2018-04-24T21:25:23+0200 ephemeral=false name=byggeboks newname=byggebokssoftdelete18 project=default used=2019-02-11T22:47:37+0100
> t=2019-10-21T21:14:01+0200 lvl=info msg="Renamed container" created=2018-04-24T21:25:23+0200 ephemeral=false name=byggeboks newname=byggebokssoftdelete18 project=default used=2019-02-11T22:47:37+0100

**Comment by stgraber** [comment]
what's running the script won't change the REST query. `lxc` itself doesn't do the work, the `lxd` server is, so it's unaffected by the PATH or other variables.

What storage pool driver are you using for this?

**Comment by Kramerican** [comment]
Ah yes of course I hadn't thought that far - that makes this mysterious indeed. It's a zfs backed system.

**Comment by Kramerican** [comment]
Anything I can do to give you more detailed information here? :) To be fair, it is a non-critical issue as I can just rename those containers manually, but it is slowing some processes down on my end.

**Comment by stgraber** [comment]
What's the simplest reproducer you have that I can run on a clean LXD host using zfs?

**Comment by stgraber** [comment]
@Kramerican

**Comment by Kramerican** [comment]
@stgraber Sorry Stéphane - I'll get back to this soon-ish - I just found a workaoround which consists of doing a retry after a 5sec sleep and as that worked I've been forging ahead with out workflows. It's quite strange really, it _seems_ as if it's required that the container has been running for some time and then consistently the first rename will fail while the second always succeeds.

Anyway, I'll get back to this once I'm back from vacation in about a week, and I'll see if I can cook up a reproducer (but as mentioned, a fresh container does not exhibit this issue... Maybe this is due to the system having been upgraded from previous versions of LXD?) - Anyway, sorry about the delay

**Comment by stgraber** [comment]
So we did some changes to the way mounts are handled in the snap to avoid other issues around container deletion, my guess is that's what's getting in your way, especially with systems that would have been started with the older broken logic.

Any chance you can see if this behavior shows up after a system reboot?

If not, then we can probably ignore the issue as a side effect of the fix we did and something that will self-resolved as machines get rebooted for kernel updates.

**Comment by Kramerican** [comment]
Yes I've been thinking that as well, as I've been following that thread as well, in that I started that one :) I can conceivably - maybe - do that test for you, but I need to think about it for a little bit. I suspect you are right. In any case, I'll try and do that test soon and get back to you - so let's keep this open for a little while longer if that's ok.

Thanks again Stéphane

**Comment by stgraber** [comment]
Yep, I'll nag you at some point next week :)

**Comment by stgraber** [comment]
@Kramerican ping :)

**Comment by Kramerican** [comment]
Fine timing @stgraber - I will be doing the reboot test later today - will report back here :)

**Comment by stgraber** [comment]
Excellent, thanks!

**Comment by Kramerican** [comment]
Hey @stgraber 

Alright, after a reboot, I issued the command and got:

root@rom ~ # lxc rename grabandgonyf grabandgonyfsoftdelete
Error: rename /var/snap/lxd/common/lxd/storage-pools/lxd/containers/grabandgonyf /var/snap/lxd/common/lxd/storage-pools/lxd/containers/grabandgonyfsoftdelete: file exists

This particular system is running v3.11 - so yeah, not sure if this exists in later versions. Anyway, I'm out of systems to test with at this point, so I'm not sure if I can help here any further. And yeah it just dawned on me my initial report was flawed: all the systems I have been seeing this on have been on older versions of LXD, not v3.18 

So I think it's safe to close this now, as this is probably just legacy crap. Sorry for having wasted your time here :)

**Comment by stgraber** [comment]
Oh, 3.11, that's rather old, I don't even remember what kind of storage changes we've done since but it's a lot :)

So I'd indeed strongly recommend getting at least one of those over to 3.18 and see if you're still running into issues then.
