### ISSUE TITLE
[Feature Request] Container ID in REST API

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#6343]
Would be nice to have Container ID from ```lxd sql global "SELECT id, name FROM instances;"``` exposed in REST API call ```/1.0/containers/<name>```

**Comment by stgraber** [comment]
Hmm, no, we don't intend to ever export database internals over the REST API.

Those can change at any time and we don't want to end up being tied to the API backward compatibility guarantees on any of this. (Those ids specifically, did all change recently when we split snapshots to their own tables, this would be an API break if it had been exposed).
