### ISSUE TITLE
Incorrect disk usage report when using Dir quota

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#6345]
Setup is the same like in https://github.com/lxc/lxd/issues/6333#issue-510584054

When using Dir storage backend and ext4 project quota enabled, disk usage reports are incorrect.

No related output in ```lxc info NAME``` and in direct API query.

![67396230-dc8fbc00-f5af-11e9-8031-1e2dba56d4c0](https://user-images.githubusercontent.com/11349489/67401276-99394b80-f5b7-11e9-92dd-357ba2ce8c84.png)

![67399727-55dddd80-f5b5-11e9-8bbc-41b4b0a3427e](https://user-images.githubusercontent.com/11349489/67401290-9cccd280-f5b7-11e9-8725-03e1ef8d0e9d.png)

**Comment by s3rj1k** [comment]
@stgraber done
![изображение](https://user-images.githubusercontent.com/11349489/67404794-8b39f980-f5bc-11e9-9549-11a61101e5cb.png)

**Comment by stgraber** [comment]
@s3rj1k not having any luck reproducing this issue so far, I always get the disk usage data returned here.

**Comment by s3rj1k** [comment]
@stgraber do you use ext4 quota on mdadm raid? I think this can be related to enabled quota on a partition.

**Comment by stgraber** [comment]
I do have quotas enabled but on a ext4 loop device.

**Comment by stgraber** [comment]
Can you run: https://dl.stgraber.org/lxd-6345

That binary will output debug data on failure to fetch the disk usage.

**Comment by s3rj1k** [comment]
I can check on a snap version of LXD if needed

**Comment by stgraber** [comment]
that container isn't running, you need the container to be running

**Comment by s3rj1k** [comment]
@stgraber did not noticed that it was stopped, sorry

```
root@vm1:/home/user# lxc query -X GET --wait /1.0/containers/test/state
{
	"cpu": {
		"usage": 3831762011
	},
	"disk": {},
	"memory": {
		"swap_usage": 0,
		"swap_usage_peak": 0,
		"usage": 162144256,
		"usage_peak": 202768384
	},
	"network": {
		"lo": {
			"addresses": [
				{
					"address": "127.0.0.1",
					"family": "inet",
					"netmask": "8",
					"scope": "local"
				},
				{
					"address": "::1",
					"family": "inet6",
					"netmask": "128",
					"scope": "local"
				}
			],
			"counters": {
				"bytes_received": 3792,
				"bytes_sent": 3792,
				"packets_received": 52,
				"packets_sent": 52
			},
			"host_name": "",
			"hwaddr": "",
			"mtu": 65536,
			"state": "up",
			"type": "loopback"
		}
	},
	"pid": 981,
	"processes": 24,
	"status": "Running",
	"status_code": 103
}
```

```
./lxd-6345 -d --group lxd

DBUG[10-23|20:03:39] Handling                                 method=GET url=/1.0 ip=@ user=
DBUG[10-23|20:03:39] Handling                                 method=GET url=/1.0/containers/test/state ip=@ user=
EROR[10-23|20:03:39] stgraber: ContainerGetUsage failed, err=Failed to get project consumption for id '10001' on '/var/lib/lxd/storage-pools/default/containers/test'
```

```
lxc info | grep shiftfs
    shiftfs: "false"
```

Was able to replicate this with your binary then ```shiftfs``` is disabled (deleted kernel module)

**Comment by s3rj1k** [comment]
@stgraber on a side note, can we have ```quota project id``` to ```config:volatile.*``` struct?
Should not break any API promises and will make life a bit easier for me at least :)

**Comment by s3rj1k** [comment]
I think it should look for quota on ```/var/lib/lxd/storage-pools/default``` instead of ```/var/lib/lxd/storage-pools/default/containers/test```

**Comment by stgraber** [comment]
@s3rj1k what's `repquota -avugP` getting you now?

**Comment by s3rj1k** [comment]
```
*** Report for project quotas on device /dev/md1
Block grace time: 7days; Inode grace time: 7days
                        Block limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
#0        --       8       0       0              2     0     0       
#10001    -- 7812500       0 7812500          35842     0     0  
```

also everything is fine inside CT using `df`

**Comment by stgraber** [comment]
I've updated https://dl.stgraber.org/lxd-6345 can you give the updated binary a go?

The path that was logged wasn't the actual path being queried, so I changed the logging to report the right one.

**Comment by s3rj1k** [comment]
![изображение](https://user-images.githubusercontent.com/11349489/67417646-ecb89300-f5d1-11e9-892d-699f38cbfcf9.png)

**Comment by s3rj1k** [comment]
@stgraber yep, just a moment

**Comment by s3rj1k** [comment]
@stgraber 
```
EROR[10-23|20:18:18] stgraber: ContainerGetUsage failed, err=Failed to get project consumption for id '10001' on '/dev/md1'
```

**Comment by s3rj1k** [comment]
Same output, dmesg is empty
```
DBUG[10-23|20:26:50] Handling                                 method=GET url=/1.0 ip=@ user=
DBUG[10-23|20:26:50] Disconnected event listener: dff69b73-bd23-46c2-b1e4-f1109601bf53 
DBUG[10-23|20:26:50] Handling                                 ip=@ user= method=GET url=/1.0/containers/test/state
EROR[10-23|20:26:50] stgraber: ContainerGetUsage failed, err=Failed to get project consumption for id '10001' on '/dev/md1'
```

```
md5sum lxd-6345 
715e4c3f5f6871defcdb4693d1bdb7b3  lxd-6345
```

**Comment by stgraber** [comment]
stgraber@castiana:~/data/code/lxc/lxd (lxc/master)$ curl https://dl.stgraber.org/lxd-6345 -s | md5sum
4db9e3aba4e9ce8fc87ef6c44f519a88  -

^ that's the md5 you should have

**Comment by s3rj1k** [comment]
@stgraber forgot that I was doing ```patchelf --set-rpath "/usr/lib/lxd" ./lxd-6345``` to load shared libraries

re-downloaded, checked md5, patched rpath, same thing
```
EROR[10-23|20:36:50] stgraber: ContainerGetUsage failed, err=Failed to get project consumption for id '10001' on '/dev/md1'
```

**Comment by s3rj1k** [comment]
On a side note, while using ```shiftfs``` disk usage returns correct, while quota is broken as before (no kernel patch applied, the one from other issue)

**Comment by s3rj1k** [comment]
@s3rj1k I am running from bash console directly, I can try to redirect stderr to a file, one moment

**Comment by s3rj1k** [comment]
@stgraber 

```
./lxd-6345 -d --group lxd 2> error

t=2019-10-23T20:43:44+0300 lvl=dbug msg=Handling ip=@ method=GET url=/1.0/containers/test/state user=
t=2019-10-23T20:43:44+0300 lvl=eror msg="stgraber: ContainerGetUsage failed, err=Failed to get project consumption for id '10001' on '/dev/md1'" 
```

**Comment by stgraber** [comment]
So those two lines is what you're getting in the `error` file?

If so, then we'll want to try with more debugging, can you run it as:
`strace -fF -o trace -s999 ./lxd-6345 --group lxd`

Then do the `lxc info` call, kill lxd and push the `trace` file somewhere.

**Comment by s3rj1k** [comment]
@stgraber done
https://drive.google.com/file/d/1qS82wLzPIjo9ZYcW-YimM8J-v-40_yg-

**Comment by stgraber** [comment]
```
4825  quotactl(QCMD(Q_GETQUOTA, PRJQUOTA), "/dev/md1", 10001, {dqb_bhardlimit=7812500, dqb_bsoftlimit=0, dqb_curspace=8000000000, dqb_ihardlimit=0, dqb_isoftlimit=0, dqb_curinodes=35839, ...}) = 0
4825  write(2, "\33[31mEROR\33[0m[10-23|20:48:42] stgraber: ContainerGetUsage failed, err=Failed to get project consumption for id '10001' on '/dev/md1' \n", 134) = 134
```

That's weird, it shows success and the right data, then prints the error anyway :)

**Comment by s3rj1k** [comment]
@stgraber well, quota works correctly, only reporting broken, maybe something in go, error type casting?

**Comment by stgraber** [comment]
Updated the binary with an extra logging line to see if we're getting a negative value for some odd reason.

**Comment by s3rj1k** [comment]
@stgraber Lol, good guess, negative indeed

```
EROR[10-23|21:00:33] stgraber: size=-589934592 
EROR[10-23|21:00:33] stgraber: ContainerGetUsage failed, err=Failed to get project consumption for id '10001' on '/dev/md1'
```

**Comment by stgraber** [comment]
New binary, try that one. I'm forcing the type to int64_t which hopefully will avoid that issue :)

**Comment by s3rj1k** [comment]
Works correctly, YAY

```
EROR[10-23|21:05:35] stgraber: size=3958411264 
EROR[10-23|21:05:35] stgraber: dev={Name:root Config:map[path:/ pool:default size:8GB type:disk]} usage=3958411264
```

So more questions, when will be fixes released approximately?
and about that ```quota project id to config:volatile.*```
https://github.com/lxc/lxd/issues/6345#issuecomment-545543902

**Comment by stgraber** [comment]
Not too sure about the volatile idea, it's reasonably expensive for us to set those keys and they do get in the way of migration as source and destination servers must support them (and would also need to update them). We're also trying to deliberately not have any DB knowledge or access from the low level storage driver where the quotas reside.

That doesn't really feel any cleaner to me than you running `lxd sql global "SELECT id FROM instances WHERE name='blah';"` and the raw DB query is actually less work intensive for LXD :)

**Comment by stgraber** [comment]
I've updated the binary again now with the debugging removed and more typing fixes for quotas, can you confirm this still works for you?

**Comment by s3rj1k** [comment]
@stgraber I would just like to avoid running those SQLs ;)
Yep, moment

**Comment by s3rj1k** [comment]
@stgraber Confirming, works as expected

**Comment by stgraber** [comment]
@s3rj1k added another change to my branch exposing the `disk` struct in /state even when the container is stopped

**Comment by s3rj1k** [comment]
Stopped CT:
```
root@vm1:~# lxc query -X GET --wait /1.0/containers/test/state
{
	"cpu": {
		"usage": 0
	},
	"disk": null,
	"memory": {
		"swap_usage": 0,
		"swap_usage_peak": 0,
		"usage": 0,
		"usage_peak": 0
	},
	"network": null,
	"pid": 0,
	"processes": 0,
	"status": "Stopped",
	"status_code": 102
}
```
Started CT:
```
root@vm1:~# lxc query -X GET --wait /1.0/containers/test/state
{
	"cpu": {
		"usage": 1918843786
	},
	"disk": {
		"root": {
			"usage": 8000000000
		}
	},
	"memory": {
		"swap_usage": 0,
		"swap_usage_peak": 0,
		"usage": 85614592,
		"usage_peak": 85745664
	},
	"network": {
		"lo": {
			"addresses": [
				{
					"address": "127.0.0.1",
					"family": "inet",
					"netmask": "8",
					"scope": "local"
				},
				{
					"address": "::1",
					"family": "inet6",
					"netmask": "128",
					"scope": "local"
				}
			],
			"counters": {
				"bytes_received": 3424,
				"bytes_sent": 3424,
				"packets_received": 40,
				"packets_sent": 40
			},
			"host_name": "",
			"hwaddr": "",
			"mtu": 65536,
			"state": "up",
			"type": "loopback"
		}
	},
	"pid": 7077,
	"processes": 36,
	"status": "Running",
	"status_code": 103
}

```

disk usage of 8GB is ok, was testing 100% usage of quota

**Comment by stgraber** [comment]
Updated the binary now with the code for stopped containers.

**Comment by s3rj1k** [comment]
@stgraber That's really handy

```
root@vm1:~# lxc query -X GET --wait /1.0/containers/test/state
{
	"cpu": {
		"usage": 0
	},
	"disk": {
		"root": {
			"usage": 8000000000
		}
	},
	"memory": {
		"swap_usage": 0,
		"swap_usage_peak": 0,
		"usage": 0,
		"usage_peak": 0
	},
	"network": null,
	"pid": 0,
	"processes": 0,
	"status": "Stopped",
	"status_code": 102
}
```
