### ISSUE TITLE
[BUG] Stripping lxd binary effectively breaks it

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#6353]
Is there a way of removing debug info from lxd daemon without breaking it?

**Comment by stgraber** [comment]
We've been stripping both lxc and lxd in the LXD snap for months now and haven't seen a problem doing that:

```
root@sateda:~# file /snap/lxd/current/bin/lxd
/snap/lxd/current/bin/lxd: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=115284b458780ae9c8e3053cbe6e205f3ca935bc, stripped
root@sateda:~# file /snap/lxd/current/bin/lxc
/snap/lxd/current/bin/lxc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=9c955a8bc98923c9999ec9b178a90bd53551a131, stripped
```

**Comment by stgraber** [comment]
We run a simple `strip -s` on them.

**Comment by stgraber** [comment]
Older versions of the Go compiler had issues with stripping, but we've not seen any of those in years and I believe started stripping our binaries around the time we switched to Go 1.10.

(Closing as even if this wasn't working, any issue would be with the Go compiler, not something we can influence ourselves.)

**Comment by s3rj1k** [comment]
ok, issue actually was because of ```patchelf```
