### ISSUE TITLE
enhancement request: using btrfs subvolume/snapshot instead of tar.gz for images

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#6357]
lxd image management uses tar.gz to build and store images.

And when you create a container:
- it is slow because it unzip the archive and do a full copy
- it is a waste of resource since creating containers create a full copy each time: 3 containers = 3 full copies

btrfs and its cow system would be usefull instead: 
- a subvolume would be created like for containers
- when creating a container a cow rw snapshot would be created from image, instantly

it would be fast and there wont be waste of resources.

**Comment by stgraber** [comment]
This isn't quite accurate. The only case where we unpack the image every time is if you're using a `dir` storage backend.

For all the others, we unpack the image (which is usually squashfs, not tar) during the first container creation, the image is then turned into a btrfs subvolume or zfs dataset or lvm lv, ... and the container is then created as a copy on write clone of that.

We cannot have the image artifact itself be a btrfs subvolume as that would make it impossible to use on anything but btrfs, including preventing moving the image artifact between servers.

**Comment by gaetanquentin** [comment]
ok. it has always been like that?
