### ISSUE TITLE
LXD commissioning data differs when run in a container vs metal

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#6378]
MAAS 2.7 uses the LXD commissioning data. During testing we have noticed that this information differs between when commissioning data is gather with LXD on bare metal vs in an LXD container. The information isn't just different it is sometimes wrong which is causing issues with MAAS

1. Blocksize is being detected as 0([LP:1848822](https://bugs.launchpad.net/maas/+bug/1848822)). We worked around this by assuming 0 means 512 but we really should be getting the correct data
2. CDROM is being detected as a read/write SCSI device([LP:1850671](https://bugs.launchpad.net/maas/+bug/1850671)). This results in MAAS thinking the CDROM is available for use as a normal drive. Another weird thing about this is LXD is saying the size is 1073741312 when there is no CD/DVD in the drive.
3. The firmware version of block devices and interfaces is missing.
4. The serial of block devices is missing
5. The ports field on interfaces is missing when run in an LXD container. This means MAAS can't gather whether a an interface is connect nor the interface or link speed it is connected at.

[container.txt](https://github.com/lxc/lxd/files/3795191/container.txt)
[metal.txt](https://github.com/lxc/lxd/files/3795192/metal.txt)

**Comment by stgraber** [comment]
Unfortunately nothing we can do about that. Containers don't have access to the raw block devices, so this data cannot be retrieved making it all unset.

**Comment by stgraber** [comment]
The size thing needs fixing, will look into that one. Sounds like we're not properly handling a -1 or something.

**Comment by ltrager** [comment]
Could this information be added to the [socket in the container at /dev/lxd/sock](https://lxd.readthedocs.io/en/stable-2.0/dev-lxd/)? This way the information would be gathered on hardware and we wouldn't see any differences.

**Comment by stgraber** [comment]
No, this would be information leakage across privilege boundary

**Comment by stgraber** [comment]
(Our work on containers is actually towards the other way around, we'd like to have /sys not show those devices at all unless they've been passed through by the user, but filtering /sys to that extent has been so far too costly and so hasn't been done)
