### ISSUE TITLE
Live migration is not working

### ISSUE THREAD

**Issue by ne-vlezay80** [lxc/lxd#6433]
# Required information

 * Distribution: Arch Linux
 * Distribution version: Upsteram
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.2.9-arch1-1-ARCH
   * LXC version: 3.18
   * LXD version: 3.18
   * Storage backend in use: btrfs

# Issue description

Live migration is not working.

# Steps to reproduce

 1. Livong migration container with debian 10 node

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ *] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

```
Name: proxy
Location: none
Remote: unix://
Architecture: x86_64
Created: 2019/11/02 21:30 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 1604
Ips:
  eth0: inet    172.17.100.19   vethc582a2eb
  eth0: inet    <Public IP Deleted>     vethc582a2eb
  eth0: inet6   <Public IP Deleted>       vethc582a2eb
  eth0: inet6   <Public IP Deleted>   vethc582a2eb
  eth0: inet6   fe80::216:3eff:fe38:d1d1        vethc582a2eb
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 19
  CPU usage:
    CPU usage (in seconds): 3
  Memory usage:
    Memory (current): 83.45MB
    Memory (peak): 133.32MB
  Network usage:
    eth0:
      Bytes received: 219.63kB
      Bytes sent: 30.00kB
      Packets received: 2454
      Packets sent: 375
    lo:
      Bytes received: 78B
      Bytes sent: 78B
      Packets received: 2
      Packets sent: 2

Log:

lxc proxy 20191110204019.665 WARN     cgfsng - cgroups/cgfsng.c:chowmod:1525 - No such file or directory - Failed to chown(/sys/fs/cgroup/unified//lxc.payload/proxy/memory.oom.group, 1000000000, 0)
lxc 20191110210223.731 ERROR    criu - criu.c:do_dump:1325 - dump failed with 1
lxc 20191110210223.731 ERROR    criu - criu.c:do_dump:1339 - criu output: 
lxc 20191110211643.301 ERROR    criu - criu.c:do_dump:1325 - dump failed with 1
lxc 20191110211643.301 ERROR    criu - criu.c:do_dump:1339 - criu output: 

```
# Peer information

 * Distribution: Debian Linux
 * Distribution version: 10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.19.0-6-amd64
   * LXC version: 3.18
   * LXD version: 3.18
   * Storage backend in use: btrfs

**Comment by stgraber** [comment]
What happens if you run `criu check`? Looks like even the most basic criu operations don't work on your system. This can be due to lack of kernel support or criu itself failing for some reason.

You'll find detailed CRIU logs in `/var/log/lxd/NAME/` assuming that criu even started.

Log above suggests that criu was called, so this issue is most likely not a LXD issue, it's either a system configuration problem or a criu bug, so tentatively closing, feel free to provide more details as you track this down.

**Comment by stgraber** [comment]
Ah and a good first start is to do `lxc snapshot name --stateful` on both nodes to make sure that basic criu works before attempting live migration.

**Comment by stgraber** [comment]
It's also worth noting that live migrating across such big kernel version difference may lead to issues, especially if migrating from the more recent kernel to the older one, programs may have detected kernel features which will then no longer be available, leading to crashes.
