### ISSUE TITLE
ps aux complains of no btime in /proc/stat with 160 cpu host

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#644]
On the p8 box, if I leave SMT=8 on, the host has 160 cpus.  When I run ps aux in a container, it complains that there is no btime in /proc/stat output.  If I disable SMT and have 20 cores, then btime shows up in the guest /proc/stat.

**Comment by stgraber** [comment]
Can you paste /var/liblxcfs/proc/stat in both scenarios?

**Comment by stgraber** [comment]
Oh, also, would you mind re-opening that bug against lxcfs instead? I'll close it against lxd.
