### ISSUE TITLE
lxc is missing an "unapply" command for profiles

### ISSUE THREAD

**Issue by chrisglass** [lxc/lxd#646]
The "lxc profile apply <container name> <profile name>" is missing a removal counterpart, something like "lxc profile unapply <container name> <profile name>" (or "remove")

**Comment by stgraber** [comment]
So actually you're supposed to always use "lxc profile apply". Calling with with "default" would reset the profile list to just the default profile, calling it with "default,blah" will set those two profiles for the container.

Removing all profiles can be done with passing "".

The reason for this is that the order in which profiles are set is important, so if we were requiring multiple calls to apply/unapply, it'd get pretty annoying to re-order them.

So my guess is that the main problem here is the command line help which doesn't make that clear at all. The argument name may also be confusing, but I can't think of anything better...

**Comment by chrisglass** [comment]
Ok, I'll give it a try and see if I can formulate it slightly more explicitely.

**Comment by chrisglass** [comment]
https://github.com/lxc/lxd/pull/652 is an attempt at changing the inline documentation.

**Comment by stgraber** [comment]
Merged. Can we close this issue or do you think there are more places that needs clarifying?

**Comment by chrisglass** [comment]
I think we can go ahead and close it for now
