### ISSUE TITLE
RFC: Add support for tunnel GRE with tun mode (Layer3)

### ISSUE THREAD

**Issue by geaaru** [lxc/lxd#6467]
Currently, tunnel GRE support of network API support only tunnels GRE with Protocol Type Ethernet (0x6558) that use gettap.

An example of the command used with iproute tools is:
```bash
$# ip link add tun0 type gretap remote 10.10.10.1 local 10.10.10.2 dev eth0
```
gretap works at Layer2.

An alternative to this is to create a tunnel with Protocol Type 0x0800 at Layer 3.
```bash
$# ip link add tun1 mode grep remote 10.10.10.1 local 10.10.10.2 dev eth0
```

I think that this could be useful with the new feature about veth route mode but I'm not sure that could be easy to integrate inside normal logic with bridging between host and containers.

FWIK normally with Cisco devices is used Layer 3 and not Ethernet Type tunnel GRE.

My cent.

**Comment by stgraber** [comment]
LXD network tunnels expect L2 so you can connect containers on a LXD server to those on another, only having one of them operate as DHCP/DNS/router for the network.

I don't think we can really fit a L3 tunnel into the current tunnel model.

L3 is likely better handled by having the host setup the tunnel, whether that's GRE or some kind of encrypted L3 VPN, then typically ensuring a subnet is routed to the endpoint of that tunnel and finally handing out that subnet to a LXD bridge or by using the routed network feature.

We do have plans to bring more complex cross-node networking in the future, with our current plan being full support of OVN to handle distributed virtual networks and firewalling. As we start working on this in the next year or so, we may find ourselves reconsidering the place of L3 tunnels, but for now, I expect they make more sense outside of LXD and just having the containers access them through normal host routing.
