### ISSUE TITLE
VM Power state not maintained

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#6469]
VM support currently does not update the `volatile.last_state.power` key on start and stop.

Whilst setting this on start should be trivially added to the `Start()` function in vm_qemu.go, making the equivalent of containerLXC's `OnStop()` hook function will require us to have a fork process that waits until the qemu process has ended and then calls back to LXD.

Currently VM's rely on qemu's own forking feature, but we should stop using that and wrap it in our own forking process.

**Comment by stgraber** [comment]
Yeah, we'll need something similar to `forkstart` so we can handle this and also support properly cleaning devices on the host on shutdown.
