### ISSUE TITLE
lxc config profile device show is missing

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#649]
Could we get a device show ?  I typo'ed my lxc config profile device add <foo>  and without running edit, I can't see that I missed setting the parent value correctly.

$ lxc config profile device list scaling-3
eth0: nic

$ lxc config profile edit scaling-3
name: scaling-3
config: {}
devices:
  eth0:
    nictype: bridged
    parent: ''
    type: nic

**Comment by butikofer** [comment]
This should be closed out, as I failed to properly reference this issue in the above PR.
