### ISSUE TITLE
How does LXD use the existing zfs pool.

### ISSUE THREAD

**Issue by RanMaosong** [lxc/lxd#6507]
I have created some containers. One day, I accidentally uninstall the LXD, then, the all containers disappear. I reinstall LXD, it still doesn't work.  So how do i restore the previous containers. Thanks!

**Comment by stgraber** [comment]
https://linuxcontainers.org/lxd/docs/master/backup#disaster-recovery

But that's assuming that your storage pool was separate from the LXD daemon storage, if it was some kind of loop mounted file backing your pool, then you're out of luck.

**Comment by RanMaosong** [comment]
Would you give me more detailed instructions, please?

Stéphane Graber <notifications@github.com> 于2019年11月26日周二 下午2:44写道：

**Comment by RanMaosong** [comment]
Would you give me more detailed instructions, please?

**Comment by stgraber** [comment]
Support questions are better handled in https://discuss.linuxcontainers.org where more community member are around to answer your questions.
