### ISSUE TITLE
Console Error: Failed running forkconsole: "attaching to the container failed"

### ISSUE THREAD

**Issue by cyberwillis** [lxc/lxd#6512]
# Required information

 * Distribution: **ubuntu**
 * Distribution version: **16.04**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.4.0**
   * LXC version: **3.2.x  (https://github.com/lxc/lxc/commit/f177506f59ec142718413c3accffcf9cc3dd0746)**
   * LXD version: **3.18 (https://github.com/lxc/lxd/commit/5759c4be9fd85ab949544c440d5ac0545bcad86e)**
   * Storage backend in use: **zfs**

# Issue description

Trying to reconnect to console without previous logout give a error message:
```
To detach from the console, press: <ctrl>+a q
Error: Failed running forkconsole: "attaching to the container failed" 
```
# Steps to reproduce

 1. Launch a new container
```
lxc launch ubuntu:16.04 u16
```
 2. Create a password for user root 
```
lxc exec u16 -- bash -c 'passwd'
```
3. Login to the console
```
lxc console u16
```
 4. exit from console without logout
```
<CRTL>+a q
``` 
5. Try to access the console again

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
I think I've got a fix for this one.

**Comment by cyberwillis** [comment]
Yeah ... It works. Thank you
