### ISSUE TITLE
Nested Docker container can "spy" on the host system

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#6533]
Ubuntu Bionic
LXD 3.18 from Snap

Create an LXD container with -c security.nesting=true - set some cpu / ram limits - and then initialize a docker container:

```
apt update
apt upgrade
apt install docker.io
mkdir -p /mnt/sysdisk
docker run -d --name Cloud9 --restart always -v /mnt/sysdisk/Cloud9:/workspace --net host sapk/cloud9 --auth admin:testcloud9
```

Enter the container and install / execute htop:

```
docker exec -it Cloud9 /bin/bash
apt update; apt install htop -y; htop;
```
 
You will now notice you can see all host system resources - total number of threads, total CPU use, total amount of memory and overall host system load, despite LXD being configured with `snap set lxd lxcfs.loadavg=true`

Somehow Docker circumvents all of this. 

Running `stress` reveals system cpu and memory limits are still enforced, fortunately - in addition, the container can only see processes running under the LXD container. So my impression is this is a non-critical issue. Just a bit confusing to customers who see something they do not expect :)

**Comment by stgraber** [comment]
That's not spying, lxcfs is setup in LXD containers for convenience but someone can absolutely unmount it our mount a new instance of proc and see the real values from the system.

As Docker doesn't know how to setup lxcfs, Docker containers see the host resources directly, this is normal.

**Comment by Kramerican** [comment]
Thought as much - thanks for confirming, @stgraber :)

**Comment by badsmoke** [comment]
how can this problem be solved?
