### ISSUE TITLE
iSCSI inside a container fail to login

### ISSUE THREAD

**Issue by davidp1404** [lxc/lxd#6536]
Hello, I'm trying to run a container that mounts a iscsi target but it doesn't work.
I've also applied privileged mode without success.
The syslog reports:
Dec 02 15:07:54 nfs10A systemd[1]: iscsid.service: Failed to reset devices.list: Operation not permitted
Dec 02 15:07:54 nfs10A systemd[1]: Starting iSCSI initiator daemon (iscsid)...
Dec 02 15:07:54 nfs10A iscsid[1804]: iSCSI logger with pid=1805 started!
Dec 02 15:07:54 nfs10A systemd[1]: iscsid.service: Failed to parse PID from file /run/iscsid.pid: Invalid argument
Dec 02 15:07:54 nfs10A iscsid[1805]: iSCSI daemon with pid=1806 started!
Dec 02 15:07:54 nfs10A systemd[1]: Started iSCSI initiator daemon (iscsid).
Dec 02 15:07:54 nfs10A systemd[1]: iscsid.service: Main process exited, code=exited, status=255/n/a
Dec 02 15:07:54 nfs10A iscsid[1805]: sendmsg: bug? ctrl_fd 6
Dec 02 15:07:54 nfs10A iscsid[1807]: semop down failed 22
Dec 02 15:07:54 nfs10A systemd[1]: iscsid.service: Failed with result 'exit-code'.

The VM hosting the container is Linux lxd01 4.15.0-70-generic and I verified that can use the iscsi target without problems.

ubuntu@lxd01:~$ lxc info nfs10A --show-log
Name: nfs10A
Location: lxd02
Remote: unix://
Architecture: x86_64
Created: 2019/11/30 19:06 UTC
Status: Running
Type: persistent
Profiles: nfs10
Pid: 3199
Ips:
  eth0: inet    192.168.122.177
  eth0: inet6   fe80::216:3eff:fe7c:f30
  eth1: inet    192.168.10.1
  eth1: inet6   fe80::216:3eff:fe7f:bac7
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 26
  CPU usage:
    CPU usage (in seconds): 94
  Memory usage:
    Memory (current): 71.73MB
    Memory (peak): 423.60MB
  Network usage:
    lo:
      Bytes received: 3.25kB
      Bytes sent: 3.25kB
      Packets received: 30
      Packets sent: 30
    eth0:
      Bytes received: 9.66MB
      Bytes sent: 210.38kB
      Packets received: 4887
      Packets sent: 2693
    eth1:
      Bytes received: 16.97kB
      Bytes sent: 1.26kB
      Packets received: 308
      Packets sent: 16

Log:

lxc nfs10A 20191202145846.900 WARN     conf - conf.c:lxc_setup_devpts:1616 - Invalid argument - Failed to unmount old devpts instance

---
ubuntu@lxd01:~$ lxc config show nfs10A --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20191114)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20191114"
  image.version: "18.04"
  security.privileged: "yes"
  volatile.base_image: 028d045b1cfcfc8a69cc68674557bd86e015c0ba4bb5c3d6851043f785963728
  volatile.eth0.hwaddr: 00:16:3e:7c:0f:30
  volatile.eth1.hwaddr: 00:16:3e:7f:ba:c7
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: ens3
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: br10
    type: nic
  root:
    path: /
    pool: local
    type: disk
ephemeral: false
profiles:
- nfs10
stateful: false
description: ""
--

**Comment by stgraber** [comment]
Closing as it's not a LXD issue by itself, in that, there's nothing we can really do at the LXD level to make this just work.

Now what would be interesting to get is an `strace -f` output of the daemon and whatever other iscsi process you may have. I suspect we'll see an attempt at either creating device nodes directly in /dev or trying to access some specific iscsi device nodes or device mapper nodes which are missing inside the container.

With that trace, it may be possible to pre-create enough of that stuff through LXD devices attached to the container to have it behave.
