### ISSUE TITLE
Hangs at shutdown

### ISSUE THREAD

**Issue by hadmut** [lxc/lxd#6538]
Hi, 
I just installed a fresh Lubuntu 19.10 on an notebook machine. Since 19.10 does not provide a regular LXD package and asks to install a snap, I did that, but not yet configured LXD. 

„A stop job is running for Service for snap application lxd.daemon

 * Distribution: Lubuntu 19.10
 * Distribution version: 19.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.3.0-24-generic
   * LXC version: 3.2.1
   * LXD version: snap 3.18
   * Storage backend in use: not configured yet

# Issue description

did not yet do anything with LXD on that machine, just installed the snap. Since then, the machine hangs forever (or at least for a long time) during shutdown, and does not finish the shutdown. After disabling the Lubuntu Splash I saw that it hangs at
„A stop job is running for Service for snap application lxd.daemon”

**The problem is gone once lxd init is run.** 

However, since this is not always the case and not obvious, an unitialized snap should not block the shutdown.

**Comment by stgraber** [comment]
Should have been fixed by the snap revision we pushed out about 15min ago.
Run `snap refresh lxd`, make sure you're on revision 12631 or newer and hopefully that problem will be gone.
