### ISSUE TITLE
shiftfs doesn't work if built in

### ISSUE THREAD

**Issue by dgreid** [lxc/lxd#6545]
When running on a kernel that doesn't support modules, shiftfs is always disabled because the check for shiftfs depends on it being compiled as a module.
This check:
https://github.com/lxc/lxd/blob/a75e207459a047835e43245f95ee50ada8854cee/lxd/daemon.go#L623
uses this code
https://github.com/lxc/lxd/blob/fbff4896fa3d1a83530ffa8351fd82d1795a0230/lxd/util/kernel.go#L12
which checks /sys/module/shifts, however that directory doesn't exist because the shiftfs module doesn't expose any paramenters.

This code must currently be working by falling through to the modprobe case and succeeding.

Is there an easy way to check /proc/filesystems instead?

**Comment by stgraber** [comment]
Ah yeah, for this one we should certainly be looking at `/proc/filesystems` too.
