### ISSUE TITLE
lxc copy command does *something* which causes a 2 minute delay in container startup

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#6549]
Ubuntu Bionic
LXD 3.18

Interesting issue I encountered today. Reliably reproducible:

```
# lxc init ubuntu:bionic flipasaurus
# lxc exec flipasaurus bash
~# netstat -tapn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      176/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      222/sshd   
tcp6       0      0 :::22                   :::*                    LISTEN      222/sshd   
~# exit
```

Container starts up fine as usual and you can see the ssh daemon running. Now let's make a copy and see what happens:

```
# lxc stop flipasaurus; lxc copy flipasaurus testingsystemd; lxc start testingsystemd;
# lxc exec testingsystemd bash
# netstat -tapn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      188/systemd-resolve
```

ssh daemon does not come up. Watching the syslog then always after about 2 minutes services will come up. This seems like the system is waiting for something and then times out and then continues startup. I noticed this first on a container with a full LEMP stack which made this immediately noticeable.

My thinking here is that something has changed and that the copy is not a straight up clone of the original container, which is causing the system to hang. Would a change in the MAC address be responsible here? Networking seems to come up immediately, so it's not because the system is waiting for that target... I think..

**Comment by tomponline** [comment]
@Kramerican does it take a 'normal' time to boot up on subsequent stop and then starts of the copy?

**Comment by Kramerican** [comment]
@tomponline I'm not sure what you mean - the container copy starts and stops immediately as they usually do. However the 2 minute delay in bringing up services is consistent on each startup.

**Comment by tomponline** [comment]
@Kramerican yep thats what I meant (wanted to ensure it wasn't LXD doing the initial uid shift). What does your syslog/journctl show you for the ssh daemon?

**Comment by stgraber** [comment]
A copy operation re-triggers cloud-init, this is most likely what you're seeing here.

**Comment by stgraber** [comment]
(To be more specific, cloud-init will re-trigger after a copy if the name of the container has changed in the process, so won't kick in on remote copies usually)

**Comment by Kramerican** [comment]
@stgraber How would re-trigger of cloud-init consistently leave boot hanging for 2 minutes ?... Or well, I'm not sure if I care about the specifics really, rather: how to fix/avoid the situation? :)

**Comment by stgraber** [comment]
Look at your systemd journal, you may be able to see what's going on in there.

**Comment by stgraber** [comment]
Note that following your steps, I'm unable to reproduce such a long delay, second container has sshd come up just as fast as the first.

**Comment by Kramerican** [comment]
@stgraber That is interesting as I was certain this was not host/network specific as I am seeing the same thing on two seperate hosts in seperate locations with differing network environments. One host is an upgraded Xenial->Bionic host whilst the other is a relatively fresh Bionic host.

In any case, this is what the logs reveal around the time of a reboot/startup of a copy:

syslog:
```
Dec  4 17:04:13 flipasaurus systemd[1]: Stopped Execute cloud user/final scripts.
Dec  4 17:04:13 flipasaurus systemd[1]: Stopped Apply the settings specified in cloud-config.
Dec  4 17:04:13 flipasaurus systemd[1]: Stopped target Network is Online.
Dec  4 17:04:13 flipasaurus systemd[1]: Stopped target Cloud-config availability.
Dec  4 17:04:13 flipasaurus systemd[1]: Stopped target Multi-User System.
Dec  4 17:04:13 flipasaurus systemd[1]: Stopping Deferred execution scheduler...
Dec  4 17:04:13 flipasaurus systemd[1]: Stopping Regular background program processing daemon...
Dec  4 17:04:13 flipasaurus systemd[1]: Stopping OpenBSD Secure Shell server...
Dec  4 17:04:13 flipasaurus systemd[1]: Stopping Unattended Upgrades Shutdown...
Dec  4 17:04:13 flipasaurus systemd[1]: Stopping Dispatcher daemon for systemd-networkd...
Dec  4 17:04:13 flipasaurus systemd[1]: Stopping System Logging Service...

--> At this point the container is UP and networking works <--

Dec  4 17:06:23 systemdtest systemd-modules-load[60]: could not open moddep file '/lib/modules/4.15.0-65-generic/modules.dep.bin'
Dec  4 17:06:23 systemdtest systemd-modules-load[60]: Failed to lookup alias 'iscsi_tcp': Function not implemented
Dec  4 17:06:23 systemdtest systemd-modules-load[60]: could not open moddep file '/lib/modules/4.15.0-65-generic/modules.dep.bin'
Dec  4 17:06:23 systemdtest keyboard-setup.sh[61]: Couldn't get a file descriptor referring to the console
Dec  4 17:06:23 systemdtest systemd-modules-load[60]: Failed to lookup alias 'ib_iser': Function not implemented
Dec  4 17:06:23 systemdtest keyboard-setup.sh[61]: Couldn't get a file descriptor referring to the console
Dec  4 17:06:23 systemdtest systemd-sysctl[78]: Couldn't write '4 4 1 7' to 'kernel/printk', ignoring: Permission denied
Dec  4 17:06:23 systemdtest keyboard-setup.sh[61]: setupcon: We are not on the console, the console is left unconfigured.
Dec  4 17:06:23 systemdtest systemd-sysctl[78]: Couldn't write '1' to 'kernel/kptr_restrict', ignoring: Permission denied
Dec  4 17:06:23 systemdtest systemd-sysctl[78]: Couldn't write '1' to 'fs/protected_hardlinks', ignoring: Permission denied
Dec  4 17:06:23 systemdtest systemd-sysctl[78]: Couldn't write '1' to 'fs/protected_symlinks', ignoring: Permission denied
Dec  4 17:06:23 systemdtest rsyslogd: imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.  [v8.32.0]
Dec  4 17:06:23 systemdtest systemd[1]: Started System Logging Service.
Dec  4 17:06:23 systemdtest rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Permission denied.
Dec  4 17:06:23 systemdtest rsyslogd: activation of module imklog failed [v8.32.0 try http://www.rsyslog.com/e/2145 ]
Dec  4 17:06:23 systemdtest rsyslogd: rsyslogd's groupid changed to 106
Dec  4 17:06:23 systemdtest rsyslogd: rsyslogd's userid changed to 102
Dec  4 17:06:23 systemdtest rsyslogd:  [origin software="rsyslogd" swVersion="8.32.0" x-pid="247" x-info="http://www.rsyslog.com"] start
Dec  4 17:06:23 systemdtest systemd[1]: Started LSB: automatic crash report generation.
Dec  4 17:06:23 systemdtest systemd[1]: Started OpenBSD Secure Shell server
```

The journal is more useful:
```
Dec 04 17:04:22 systemdtest systemd[1]: Started Network Name Resolution.
Dec 04 17:04:22 systemdtest systemd[1]: Reached target Host and Network Name Lookups.
Dec 04 17:04:22 systemdtest systemd[1]: Reached target Network.
Dec 04 17:06:21 systemdtest systemd-networkd-wait-online[199]: Event loop failed: Connection timed out
Dec 04 17:06:21 systemdtest systemd-journald[67]: Forwarding to syslog missed 57 messages.
Dec 04 17:06:21 systemdtest systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
```

So it indeed seems to be a networking issue ? I'm still a bit lost as to what I could have done in our environment to cause this.

Anyway, we don't use lxc copy in production - so no big deal for me - but it would be interesting to find out what is happening here.

**Comment by tomponline** [comment]
@Kramerican would also be worth checking that both containers dont have the same MAC address and are racing each other on the network.

**Comment by Kramerican** [comment]
I would also like to note that my reproduction steps were incomplete in my original post, as I omitted that I wrote a network config yaml file, in order to get things working in our environment. My apologies as that would have given you an immediate hint as to what I was doing "wrong"

**Comment by Kramerican** [comment]
@tomponline They seem to have differing MAC addresses - See my edit above, I think I got this figured out :)

Not sure if this is 100% good vanilla behavior - but it was easily explainable at the very least :)

**Comment by stgraber** [comment]
Sounds like we have this one tracked down then :)
