### ISSUE TITLE
error: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: no such file or directory

### ISSUE THREAD

**Issue by johnsamuelwrites** [lxc/lxd#655]
While running 
$ sudo lxc list
error: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: no such file or directory

$ lxc version
0.7

$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

**Comment by sl1pm4t** [comment]
What OS? Ubuntu 15.04 ?

Is lxd daemon running?
```
ps -ef | grep lxd
```

If not, try start it:
`sudo service lxd start` or `sudo systemctl start lxd`

**Comment by johnsamuelwrites** [comment]
Thanks, starting the lxd worked
$ sudo service lxd start

$ sudo lxc list
+------+-------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | EPHEMERAL |
+------+-------+------+------+-----------+
+------+-------+------+------+-----------+

**Comment by johnsamuelwrites** [comment]
I think, it will be useful to have an error message like
https://github.com/lxc/lxd/blob/40d11870c866e0ac84deedb4b20666a8e38f7dba/scripts/lxd-images#L323
...
        print(_("LXD isn't running."))
        sys.exit(1)
...

**Comment by chrisglass** [comment]
It's a little more complicated since the client and server could very well be running on different machines, but it's still a valuable UX improvement in my opinion.

**Comment by tych0** [comment]
I poked around at this just now, and there doesn't seem like a nice way to do it besides pattern matching on the error result. The error that we get back from doing the http request has an underlying type:

```
2015/05/14 23:14:49 &url.Error{Op:"Get", URL:"http://unix.socket/1.0", Err:(*net.OpError)(0xc208056080)}
```

which we can't inspect nicely. I suppose another option would be some sort of downcasting. Anyway, it's not going to be pretty whatever it is, unless someone can shed some light :)

**Comment by chrisglass** [comment]
I looked a bit as well, I suspect we could prevent the downcasting further
down the stack, so that we can switch on the error type...

I'll do a bit more of poking today.

**Comment by chrisglass** [comment]
I "solved" it in a semi-ugly way for unix sockets in https://github.com/lxc/lxd/pull/666

It exits as soon as it detects the exact conditions, but does so in client.go instead of in main.go (the error type gets lost along the way, I couldn't find where exactly).

**Comment by chrisglass** [comment]
I took another stab at the problem in #686 

It *might* display "is the server running?" in cases where it is actually running, but in this case better debug output is added.

**Comment by stgraber** [comment]
Closing this after merging @chrisglass's branch
