### ISSUE TITLE
lxc copy to another storage does not change hostname

### ISSUE THREAD

**Issue by rudiservo** [lxc/lxd#6551]
* Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.0
   * LXC version: 3.18
   * LXD version: 3.18
   * Storage backend in use: btrfs

# Issue description
copy one container into another storage does not change it's hostname.
This happens when you change to another storage inside the same storage it does not happen.
Have not tried with different profiles that have different storages.

# Steps to reproduce

 1. Step one
lxc launch ubuntu:18.04 test

 2. Step two
lxc copy test test-copy -s burnout

**Comment by stgraber** [comment]
Ah, interesting, I'm guessing we're not setting the proper trigger in such case, should be easy enough to fix.

**Comment by rudiservo** [comment]
Thanks for fixing it :+1: 
just confirmed that
lxc copy test test-1 -p devprofile
also does not change the hostname, hopefully it uses the same storage function so you only have to fix one :smile:

**Comment by stgraber** [comment]
Does devprofile contain a different root device too, so effectively causing the same issue?

**Comment by stgraber** [comment]
Ah, so good news is that the new storage interface does not have this issue, only the old drivers do.

**Comment by stgraber** [comment]
Got a fix for the old storage drivers. They'll go away in 3.19 so it's a bit pointless, but we can still cherry-pick that fix to the snap in the mean time.

**Comment by rudiservo** [comment]
Thanks, sorry for the late answer but yes the devprofile has a diferent root device.
thanks for the notice, I'll be waiting on 3.19 then.
