### ISSUE TITLE
adj_systime: Operation not permitted

### ISSUE THREAD

**Issue by chrissly90** [lxc/lxd#6566]
Hi,

I want to notice that the Option:
```lxc.kmsg=0```
is no longer available in LXC like to be seen here:

https://github.com/lxc/lxd/issues/4393#issuecomment-378181793

Sadly, that makes the following solving of this Issue Impossible:
https://github.com/lxc/lxd/issues/2004

> This line is wrong. It needs to be:
> 
> ```
> raw.lxc: |-
>   lxc.aa_profile=unconfined
>   lxc.cgroup.devices.allow=a
>   lxc.mount.auto=proc:rw sys:ro cgroup:ro
>   lxc.kmsg=0
>   lxc.autodev=1
> ```
> 
> Also, please note that `lxc.kmsg` is deprecated as of liblxc 2.1 and `lxc.autodev` shouldn't need to be set as this is the default anyway. Additionally, `cgroup:ro` will currently only be respected if cgroup namespaces are **not** supported by the running kernel. If they are this statement has no effect since the isolation due to cgroup namespaces should be sufficient. However, we might enable this option in future liblxc versions.

I have the same problem under LXC right now, that I get the error 
```adj_systime: Operation not permitted ```

```local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted```
```ntp_adjtime(TAI) failed: Operation not permitted```
```ntp_loopfilter.c line 848: ntp_adjtime: Operation not permitted```

I am using Proxmox with LXC, my lxc config looks like this:

/etc/pve/lxc/110.conf:
```
arch: amd64
features: fuse=1,keyctl=1,nesting=1
hostname: box
memory: 1024
nameserver: 79.143.183.251 79.143.183.252 2620:119:35::35                                                         
net0: name=eth0,bridge=vmbr2,firewall=1,gw=10.10.20.254,hwaddr<MAC>,ip=<ipv4>/24,type=veth      
net1: name=net1,bridge=vmbr1,firewall=1,hwaddr<MAC>,ip6=<ipv6>/64,type=veth
ostype: ubuntu
rootfs: local:110/vm-110-disk-0.raw,size=8G
searchdomain: christian-nitschke.tech
swap: 500
unprivileged: 1
lxc.apparmor.profile: unconfined
lxc.cgroup.devices.allow: a
lxc.mount.auto: proc:rw sys:ro cgroup:ro
lxc.autodev: 1
```
my /var/lib/lxc/110/config:
```
lxc.arch = amd64
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.include = /usr/share/lxc/config/ubuntu.userns.conf
lxc.apparmor.raw = mount fstype=fuse,
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file 0 0
lxc.monitor.unshare = 1
lxc.idmap = u idmap
lxc.idmap = g idmap
lxc.tty.max = 2
lxc.environment = TERM=linux
lxc.uts.name = box
lxc.cgroup.memory.limit_in_bytes = 1073741824
lxc.cgroup.memory.memsw.limit_in_bytes = 1598029824
lxc.cgroup.cpu.shares = 1024
lxc.rootfs.path = /var/lib/lxc/110/rootfs
lxc.net.0.type = veth
lxc.net.0.veth.pair = veth110i0
lxc.net.0.hwaddr = <MAC>
lxc.net.0.name = eth0
lxc.net.1.type = veth
lxc.net.1.veth.pair = veth110i1
lxc.net.1.hwaddr = <MAC>
lxc.net.1.name = net1
lxc.apparmor.profile = unconfined
lxc.cgroup.devices.allow = a
lxc.mount.auto = proc:rw sys:ro cgroup:ro
lxc.autodev = 1
```

I am giving this much permission because I want to fit MailInabox inside an LXC Container.
Would be great, if you could help me too, since ```lxc.kmsg``` seems to be removed from LXC. Would be great if there's a solution

- chrissly90

**Comment by stgraber** [comment]
This is the LXD project, not LXC, you're using proxmox, therefore you're not using LXD.

Your container is attempting to modify global system time which isn't allowed for unprivileged containers and would be a bad idea (and normally blocked) even in privileged containers.
