### ISSUE TITLE
/sbin/init fails in a container on a host booted with systemd.unified_cgroup_hierarchy

### ISSUE THREAD

**Issue by emojifreak** [lxc/lxd#6587]
Host: Ubuntu Eoan booted with `systemd.unified_cgroup_hierarchy`
LXD version: github master branch retrieved and compiled today
LXC version:

```shell-session
$ dpkg-query -W | grep lxc
liblxc-common	3.2.1+master~20191210-1504-0ubuntu1~eoan
liblxc-dev	3.2.1+master~20191210-1504-0ubuntu1~eoan
liblxc1	3.2.1+master~20191210-1504-0ubuntu1~eoan
lxc	3.2.1+master~20191210-1504-0ubuntu1~eoan
lxc-utils	3.2.1+master~20191210-1504-0ubuntu1~eoan
lxcfs	3.0.4-2
```

Container's Guest: Ubuntu Eoan made by `lxc launch ubuntu:19.10`

When host Linux is booted with `systemd.unified_cgroup_hierarchy`, and the guest Linux is relatively new, e.g. Ubuntu 18.04 or 19.10, we need `lxc.mount.auto = cgroup:rw:force` as told at https://github.com/lxc/lxc/issues/3183#issuecomment-560163709

On the other hand, LXD hard-codes `lxc.mount.auto` as
https://github.com/lxc/lxd/blob/9522abd2e090d4f3b4c7a2a0f1fd4e4564eba4fb/lxd/container_lxc.go#L784-L788

The above hard-coded `lxc.mount.auto` prevents Ubuntu 19.10 from starting as an LXD guest. When Ubuntu 18.04 is started as a guest, only `/sbin/init` (=systemd) is running and there is no other process in the container, which is very abnormal.

After I applied the following changes and rebuilt LXD, everything works fine on my host Ubuntu 19.10 booted with systemd.unified_cgroup_hierarchy:

```diff
--- lxc/lxd/lxd/container_lxc.go-org	2019-12-11 19:57:42.487136537 +0900
+++ lxc/lxd/lxd/container_lxc.go	2019-12-11 20:11:00.732855626 +0900
@@ -783,6 +783,8 @@
 
 	if !shared.PathExists("/proc/self/ns/cgroup") {
 		mounts = append(mounts, "cgroup:mixed")
+	} else {
+		mounts = append(mounts, "cgroup:rw:force")
 	}
 
 	err = lxcSetConfigItem(cc, "lxc.mount.auto", strings.Join(mounts, " "))
```

**Comment by emojifreak** [comment]
Thank you for your hard work!

**Comment by emojifreak** [comment]
@brauner @stgraber The problem persists after rebuilding LXD having #6588 
The source code was retrieved three hours ago. Could you see if `lxc.mount.auto = cgroup:rw:force` takes effect on Linux host with systemd.unified_cgroup_hierarchy?

The host has following `/proc/mounts` 

```text
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=8122092k,nr_inodes=2030523,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=1636580k,mode=755 0 0
/dev/sdb7 / btrfs rw,noatime,ssd,space_cache,subvolid=256,subvol=/@ 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=26,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16482 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/sdb7 /home btrfs rw,noatime,ssd,space_cache,subvolid=258,subvol=/@home 0 0
/dev/sdb1 /boot/efi vfat rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /run/user/110 tmpfs rw,nosuid,nodev,relatime,size=1636576k,mode=700,uid=110,gid=119 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=1636576k,mode=700 0 0
tmpfs /var/lib/lxd/shmounts tmpfs rw,relatime,size=100k,mode=711 0 0
tmpfs /var/lib/lxd/devlxd tmpfs rw,relatime,size=100k,mode=755 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
```

and the guest (Ubuntu Eoan with /sbin/init replaced by `while true; do sleep 1; wait; done`) has the following `/proc/mounts`

```text
/var/lib/lxd/storage-pools/default/containers/eoan/rootfs / shiftfs rw,relatime,passthrough=3 0 0
none /dev tmpfs rw,relatime,size=492k,mode=755,uid=1000000,gid=1000000 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs rw,relatime 0 0
udev /dev/fuse devtmpfs rw,nosuid,relatime,size=8122092k,nr_inodes=2030523,mode=755 0 0
udev /dev/net/tun devtmpfs rw,nosuid,relatime,size=8122092k,nr_inodes=2030523,mode=755 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/lxd tmpfs rw,relatime,size=100k,mode=755 0 0
tmpfs /dev/.lxd-mounts tmpfs rw,relatime,size=100k,mode=711 0 0
lxcfs /proc/cpuinfo fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/diskstats fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/meminfo fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/stat fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/swaps fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/uptime fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
udev /dev/full devtmpfs rw,nosuid,relatime,size=8122092k,nr_inodes=2030523,mode=755 0 0
udev /dev/null devtmpfs rw,nosuid,relatime,size=8122092k,nr_inodes=2030523,mode=755 0 0
udev /dev/random devtmpfs rw,nosuid,relatime,size=8122092k,nr_inodes=2030523,mode=755 0 0
udev /dev/tty devtmpfs rw,nosuid,relatime,size=8122092k,nr_inodes=2030523,mode=755 0 0
udev /dev/urandom devtmpfs rw,nosuid,relatime,size=8122092k,nr_inodes=2030523,mode=755 0 0
udev /dev/zero devtmpfs rw,nosuid,relatime,size=8122092k,nr_inodes=2030523,mode=755 0 0
devpts /dev/console devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
none /proc/sys/kernel/random/boot_id tmpfs ro,nosuid,nodev,noexec,relatime,size=492k,mode=755,uid=1000000,gid=1000000 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=1000005,mode=620,ptmxmode=666,max=1024 0 0
devpts /dev/ptmx devpts rw,nosuid,noexec,relatime,gid=1000005,mode=620,ptmxmode=666,max=1024 0 0
```

The below is `lxc info --show-log` is attached below.
[eoan-log.txt](https://github.com/lxc/lxd/files/3954410/eoan-log.txt)

**Comment by brauner** [comment]
I've just retested this on a cgroup2-only host on 5.4 kernel which has both cgroup namespaces and cgroup2 support.
Did you ensure you recompiled and then restarted the daemon and the containers using the correct binary? I've just tested this with the edge lxd snap too.
What is your host os and what is you host kernel version?

Can you also show:
```
lxc info
```
and the `lxc.conf` file. If you're using the snap the log can be found under
```
/var/snap/lxd/common/lxd/logs/<ct>/lxc.conf
```
and on-non snap
```
/var/lib/lxd/logs/<ct>/lxc.conf
```

**Comment by brauner** [comment]
Please also show:
```
cat /proc/1/cgroups
```
and
```
cat /proc/self/cgroups
```
on the _host_.

**Comment by emojifreak** [comment]
@brauner Thank you for your response and paying attention to this (closed) issue. I debugged it to some extent.

Firstly, we cannot use `logger.something` function in `init()` of `cgroup/init.go`. The reason is that the order of execution of init() functions in multiple packages is undefined. So, we **MUST NOT** assume that logger.init() is called before cgoup.init(). This is unrelated to this issue, though.

```shell-session
root@newlaptop:/usr/local/lxdgo/src/github.com# cat /proc/1/cgroup /proc/self/cgroup
0::/init.scope
0::/user.slice/user-0.slice/session-2.scope
root@newlaptop:/usr/local/lxdgo/src/github.com# uname -a
Linux newlaptop 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I added the debugging print as shown in the diff at the bottom of this reply, and now I believe that

https://github.com/lxc/lxd/blob/f9f0a091da2d9967d9ec767936a0cfa99e556ee2/lxd/cgroup/init.go#L118-L122

`err` is `nil` in the above, but the `cgroup.init()` function returns despite of `err == nil`. If my guess of the cause of the problem is correct, I deeply wonder what was meant by

> I've just retested this on a cgroup2-only host on 5.4 kernel which has both cgroup namespaces and cgroup2 support.

Did you boot your Linux with `systemd.unifed_cgroup_hierarchy=1`? If the answer is no, please test the code with `systemd.unifed_cgroup_hierarchy=1` *before* making the claim that LXD (and LXC) supports unified CGroup hierarchy (or please stop the claim of CGroup2 support because CGroup V2 controllers are very limited under systemd hybrid cgroup hierarchy). I found too many issues in LXC and LXD combined under `systemd.unifed_cgroup_hierarchy=1` in a very short period of time. I was surprised at my bug hunting ability, but truth may be that really **NOBODY** has tested the code under `systemd.unifed_cgroup_hierarchy=1`. I mean nobody (incl. @stgraber ), not *few*. I am aware that this paragraph is impolite and offensive, but frankly I am deeply disappointed that there were too many issues under `systemd.unifed_cgroup_hierarchy=1` in the presence of the claim of CGroup V2 support. In addition cgroup-v2.txt in the kernel documentation discourages us not to mix V1 and V2 controllers as

> While useful for development and manual configurations, moving
> controllers dynamically between the v2 and other hierarchies is
> strongly discouraged for production use.  It is recommended to decide
> the hierarchies and controller associations before starting using the
> controllers after system boot.

By the debug print at the bottom of this reply, I got the following. It strongly suggests that `hasV2` has not been set correctly despite `dedicatedPath` exists and is readable.

```shell-session
root@newlaptop:/usr/local/lxdgo/src/github.com# /usr/local/lxdgo/bin/lxd --verbose --logfile=/var/tmp/lxd4.log
init() called
error of os.Open(/proc/self/cgroup): %#v <nil>
line: %#v 0::/user.slice/user-0.slice/session-2.scope
path: %#v /user.slice/user-0.slice/session-2.scope
dedicatedPath: %#v /sys/fs/cgroup/user.slice/user-0.slice/session-2.scope/cgroup.controllers
err of os.Open(hybridPath): %+v open /sys/fs/cgroup/unified/user.slice/user-0.slice/session-2.scope/cgroup.controllers: no such file or directory
err of os.Open(dedicatedPath): %+v <nil>
Unable to load unified cgroup.controllers
but err of os.Open(dedicatedPath): %+v can be nil!! <nil>
```

The below is diff of debug prints:

```diff
--- lxc/lxd/lxd/cgroup/init.go-org	2019-12-13 02:47:11.535576605 +0900
+++ lxc/lxd/lxd/cgroup/init.go	2019-12-13 03:53:37.012781661 +0900
@@ -5,6 +5,7 @@
 	"os"
 	"path/filepath"
 	"strings"
+	"fmt"
 
 	"github.com/lxc/lxd/shared/logger"
 )
@@ -44,6 +45,7 @@
 	info := Info{}
 	info.Namespacing = cgNamespace
 	info.Layout = cgLayout
+	logger.Errorf("GetInfo called")
 
 	return info
 }
@@ -53,9 +55,11 @@
 	if err == nil {
 		cgNamespace = true
 	}
+	fmt.Println("init() called")
 
 	// Go through the list of resource controllers for LXD.
 	selfCg, err := os.Open("/proc/self/cgroup")
+	fmt.Println("error of os.Open(/proc/self/cgroup): %#v", err)
 	if err != nil {
 		if os.IsNotExist(err) {
 			logger.Warnf("System doesn't appear to support CGroups")
@@ -74,6 +78,7 @@
 	scanSelfCg := bufio.NewScanner(selfCg)
 	for scanSelfCg.Scan() {
 		line := strings.TrimSpace(scanSelfCg.Text())
+		fmt.Println("line: %#v", line)
 		fields := strings.SplitN(line, ":", 3)
 
 		// Deal with the V1 controllers.
@@ -89,19 +94,26 @@
 
 		// Parse V2 controllers.
 		path := fields[2]
+		fmt.Println("path: %#v", path)
 		hybridPath := filepath.Join(cgPath, "unified", path, "cgroup.controllers")
 		dedicatedPath := filepath.Join(cgPath, path, "cgroup.controllers")
+		fmt.Println("dedicatedPath: %#v", dedicatedPath)
 
 		controllers, err := os.Open(hybridPath)
+		fmt.Println("err of os.Open(hybridPath): %+v", err)
 		if err != nil {
 			if !os.IsNotExist(err) {
-				logger.Errorf("Unable to load cgroup.controllers")
+				fmt.Println("Unable to load hybrid cgroup.controllers")
 				return
 			}
 
 			controllers, err = os.Open(dedicatedPath)
+			fmt.Println("err of os.Open(dedicatedPath): %+v", err)
 			if !os.IsNotExist(err) {
-				logger.Errorf("Unable to load cgroup.controllers")
+				fmt.Println("Unable to load unified cgroup.controllers")
+				if err == nil {
+					fmt.Println("but err of os.Open(dedicatedPath): %+v can be nil!!", err)
+				}				
 				return
 			}
 		}
@@ -118,6 +130,8 @@
 			hasV2 = true
 		}
 	}
+	fmt.Println("hasV1: %#v", hasV1)
+	fmt.Println("hasV2: %#v", hasV2)
 
 	if hasV1 && hasV2 {
 		cgLayout = CgroupsHybrid
```

**Comment by stgraber** [comment]
@emojifreak there is no claim that LXD limits function under cgroup2-only systems, we actively do not support this scenario currently, that's why we have ongoing cgroupv2 work.

**Comment by stgraber** [comment]
That logc in the cgroup package is days old, has never been in an actual release and is actively being worked on by multiple people. I'd suggest you wait until LXD 3.19 is out.

**Comment by emojifreak** [comment]
@stgraber Thank you for your kind reply to my too offensive comment. I am sorry for that. As you saw, systemd.unified_cgroup_hierarchy=1 being the new Ubuntu default is considered/examined at https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1850667
Did you mean that for a while LXD will block the transition of Ubuntu to systemd.unified_cgroup_hierarchy=1 ?

**Comment by stgraber** [comment]
@emojifreak I am on the Ubuntu release team and Ubuntu technical board, switching to cgroupv2 only has been a topic we've discussed and subsequently dismissed for Ubuntu 20.04.

We will be doing work to prepare for it, work we need for projects like LXD to work on cgroupv2-only systems anyway, but have currently no plan to have Ubuntu 20.04 ship with such a configuration by default.

**Comment by stgraber** [comment]
It would be nice of users could opt into cgroupv2-only on 20.04 if they would like to benefit from some of the enhancements coming from those controllers and I do expect that we will consider fixes for cgroupv2 regressions to qualify for post-release fixes (SRUs), but I do not expect us to consider any such fixes as being release blockers.

**Comment by emojifreak** [comment]
@stgraber Thanks again for your comment.
I agree. Very few people (if any?) seem to expect Ubuntu 20.04 to have systemd.unified_cgroup_hierarchy. Ubuntu LTS should provide a production-quality OS. I thought that systemd.unified_cgroup_hierarchy being default will be from 20.10 at the earliest.

On the other hand, LXD being able to start a newer Ubuntu container under systemd.unified_cgroup_hierarchy seems necessary for contributors to work on https://github.com/lxc/lxd/issues/6305 . Currently LXD cannot start  a newer Ubuntu (e.g. eoan) container under host's systemd.unified_cgroup_hierarchy...

**Comment by emojifreak** [comment]
@stgraber There seems more reason to use the unified cgroup hierarchy than the hybrid one for testing V2 resource controls to work on #6305 , because it makes more sense to use the unified hierarchy when one uses V2 resource control and because the unified one is likely to be the new default in a near future.
