### ISSUE TITLE
lxd installed in multiple KVM VM's all use same 10.x.x.x subnet - is this intentional?

### ISSUE THREAD

**Issue by bmullan** [lxc/lxd#6589]
# Required information

 * Distribution:  Ubuntu 18.04
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.0.0-37-generic
   * LXC version: 3.1.8
   * LXD version: 3.1.8
   * Storage backend in use: dir

# Issue description
I created 2 KVM VM's, both Ubuntu 18.04 and installed SNAP LXD in both.   Did lxd init in both.

Then I create an ubuntu 18.04 container in both VMs and I noticed that in bother VM's the containers were given the exact same 10.x.x.x IP Subnet and Host address:

VM1 - CN1 ip address:   10.230.208.118

VM2 - CN2 ip address:   10.230.208.118

Is this intentional?   Just curious if so... why? 

I thought that on different hosts the LXD containers used to be given different/random Subnet's.

Reason I am asking is that I'm testing various Mesh VPNs and having identical IP addresses for LXD containers in multiple VMs/Hosts becomes a problem which requires creating a configuration profile for each host to force using different IP Subnets on each Host for that Host's LXD containers.

thanks...

Brian

**Comment by stgraber** [comment]
Hmm, how did you create the lxdbr0 network?
What's the network config and container config?

The subnet for `lxdbr0` unless specified is randomly allocated, container MAC addresses are similarly randomly allocated and the IP addresses are tied to a hash of the MAC, so getting exactly the same subnet and address should be almost impossible.

That's unless you have very crappy random number generators in those VMs that throw the same data to both VMs.

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ ifconfig test
test: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.177.97.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::7c8a:69ff:feee:1311  prefixlen 64  scopeid 0x20<link>
        inet6 fd42:2918:eddd:25e7::1  prefixlen 64  scopeid 0x0<global>
        ether 7e:8a:69:ee:13:11  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 1500 (1.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

stgraber@castiana:~$ lxc network delete test
Network test deleted
stgraber@castiana:~$ lxc network create test
Network test created
stgraber@castiana:~$ ifconfig test
test: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.201.20.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fd42:18de:aa3a:ac54::1  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::1c32:45ff:fe2e:b665  prefixlen 64  scopeid 0x20<link>
        ether 1e:32:45:2e:b6:65  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10  bytes 1260 (1.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

stgraber@castiana:~$ 
```

**Comment by stgraber** [comment]
I've looked at our automatic tests here: https://jenkins.linuxcontainers.org/job/lxd-test-snap-latest-stable/263/

And it looks like the addresses shown in `lxc list` are random between test machines.

**Comment by bmullan** [comment]
I am using SNAP LXD
Installed LXD on both vm's

$ sudo snap install lxd
$ sudo lxd init

just accept defaults for everything for "lxd init" on both VMs

create a container on both VMs

$ lxc launch ubuntu:b cn1   # on vm1
$ lxc launch ubuntu:b cn2   # on vm2

I also just checked on both VMs:

$ lxc network show lxdbr0

and the IP subnets are identical?

**Comment by stgraber** [comment]
ok, so yeah, that'd suggest amazingly crappy randomness

**Comment by stgraber** [comment]
I'll repeat the same test here with two 18.04 VMs but I expect them to behave much like our jenkins VMs.

**Comment by bmullan** [comment]
I can delete the VMs and recreate them again but I've been seeing this for a while now.

Also, just fyi...
This is not LXD related ... but creating VMs using Virt-Manager to CLONE one VM to create another there is some bug (in my opinion) where in each VM keeps the same  **/etc/machine-id**
which then causes both VM's to get the same IP address.

The fix for that is a script I found which uses VIRSH to clone an existing VM to another VM and then performs:

**
> $ sudo virt-sysprep --enable machine-id -d $new_vm --hostname $new_vm
**

to force a new **/etc/machine-id** on the new VM and a new Hostname

**Comment by bmullan** [comment]
Come to think of it Stephane... 

perhaps the difference between what your Test does and what I've done is that initially I use Virt-Manager to create a BASE VM.

Then I use Virt-Manager to "Clone" that Base VM to more VMs 

Your testing might be creating 2 VMs from scratch ... re Not Cloned like I am doing?  
What happens if you Clone 2 VMs from an original?   Do they get the same IP Subnet on Both the Clones?

**Comment by stgraber** [comment]
using a clone does increase the chance that your number generator will throw the exact same thing, especially if no virtualized rng is passed in

**Comment by stgraber** [comment]
and yeah, cloning systems in general is a bad idea as you do get a variety of files storing "unique" values which aren't so unique anymore. machine-id is one of them, your SSH keys is another, ...

**Comment by bmullan** [comment]
I know but it saves so much time using a newly installed Ubuntu KVM VM as a Base image to just clone further working VMs from rather than doing a full install each time you want a new VM

**Comment by stgraber** [comment]
Yeah and a lot of people hit those kind of issues :)
For LXD containers and cloud-instances, cloud-init can be used to reset all of those. It also has support for injecting more entropy at boot time to avoid issues with VMs having unreliable random number generation.

I've now confirmed that I'm not seeing this issue here at all using VMs.

One thing you can probably try to do with virt-manager is add a virtio-random device to your VMs, this should give you better random number generation, probably fixing this particular issue.

**Comment by bmullan** [comment]
@stgraber 
Okay... I'm now puzzled about your suggestion of adding **virtio-random**.

According to...
https://www.exoscale.com/syslog/random-numbers-generation-in-virtual-machines/

Their recommendation in the section titled:

**Linux /dev/random versus /dev/urandom**

> The Linux kernel provides two devices which can be used (read) to obtain random numbers:
> 
>     /dev/random: very high quality of randomness, extracted directly from the entropy pool (itself fed mostly by peripherals interrupts timings and block devices seek times); it will block if you request more bits than available in the entropy pool (as reported by cat /proc/sys/kernel/random/entropy_avail)
> 
>     /dev/urandom: lesser — but still high — quality of randomness, generated by an intermediate Cryptographically (Secure) Random Number Generator (CRNG); it will block until it is properly seeded from the entropy pool (at boot time) but not afterwards (albeit with decreasing randomness quality if you read too many data, too fast, before it gets re-seeded)
> 
> The following rules and facts should thus be kept in mind:
> 
>     Given its entropy-greedy and blocking nature, never use /dev/random! (unless you’re a cryptographer and know for sure you need it)
> 
>     Always use /dev/urandom for common cryptography purposes (such as generating SSL certificates, SSH key pairs, Diffie-Hellmann parameters, etc.)

So they seem to be saying to normally use  /dev/urandom  not /dev/random generally?

In my Virt-Manager for the KVM VM's it is creating from the CLONE process the setting is:

![urandom vm](https://user-images.githubusercontent.com/1682855/70668488-c0b8a600-1c41-11ea-93b5-67d81b5cbf5e.png)

So **my Cloned VMs are using /dev/urandom**...

It just _seems like a bug in virt-manager or ubuntu that /dev/urandom ends up generating a number that generates the same IP subnet for all the VMs_ ?
 
brian

**Comment by stgraber** [comment]
That's all pretty weird indeed, with the VM pulling randomness from urandom on the host, you wouldn't expect it to get the exact same random state and therefore not get the exact same subnet.

What happens if you do:
 - lxc network delete lxdbr0
 - lxc network create lxdbr0

Does it pick the same subnet once again?

**Comment by bmullan** [comment]
@stgraber 

Stephane... 

    lxc network delete lxdbr0
    lxc network create lxdbr0

that worked now the LXD containers on VM1 and VM2 are on different subnets like I'd expect.

Any idea what causes the initial state?

SNAP LXD is v3.1.8 in both VMs
