### ISSUE TITLE
Danger of data loss when using snap version on existing thin pool

### ISSUE THREAD

**Issue by lukaszczerpak** [lxc/lxd#6623]
One of example use cases is to reuse existing LVM's thin pool as storage backend. This is detailed on the following page: https://lxd.readthedocs.io/en/latest/storage/
Such setup will (sooner or later) result in serious LVM errors and eventually potential data loss.

# Required information

 * Distribution: Ubuntu
 * Distribution version: snap based
 * The output of "lxc info" or if that fails:
   * Kernel version: n/a
   * LXC version: n/a
   * LXD version: n/a
   * Storage backend in use: LVM

# Issue description

The following conditions must be met:
- LXD is used as Snap (so it has its own LVM's metadata cache)
- LXD shares LVM's thin pool with the host (or any other process/system outside of the LXD snap)
Since LXD caches LVM metadata inside snap and doesn't synchronise with the host, it gets out of sync with what the host knows about. As a result any operation on LVM (snapshot, new pool, etc...) throws an error like as follows:

`Thin pool vg1-thinpool1-tpool (253:2) transaction_id is 574, while expected 572.`

I discussed this specific issue here: https://www.redhat.com/archives/linux-lvm/2019-December/msg00018.html
Thanks to clarifications from Zdenek, I was able to identify the root cause quickly and fix it w/o losing data (upgraded kernel to 5.x and migrated to btrfs for now). However it's not always so straightforward: https://discuss.linuxcontainers.org/t/is-it-safe-to-create-an-lvm-backed-storage-pool-that-can-be-shared-with-other-logical-volumes/5658/5

One of past issues (https://github.com/lxc/lxd/issues/4445) explains the whole situation clearly, the context is a bit different only.

What I'd like to achieve is better document this specific use case and warn people about it, or find a workaround that would be thoroughly tested.

# Steps to reproduce

n/a

# Information to attach

n/a

**Comment by stgraber** [comment]
This isn't a LXD issue but a packaging one, specifically one we have with the snap having its own copy of the LVM tools and cache.

https://github.com/lxc/lxd-pkg-snap/issues/41 is already opened to track resolving this.
