### ISSUE TITLE
Is there a way to convert an openRC container to systemd-nspawn ?

### ISSUE THREAD

**Issue by jorgeventura** [lxc/lxd#6629]
I would like to convert the gentoo openRC based container to systemd-nspawn based container. Is there any way to do that?

**Comment by stgraber** [comment]
If you're looking at replacing openrc with systemd as an init system in your container, you're likely best looking at Gentoo docs.

If you want to use systemd-nspawn to manage the container, then this has nothing to do with LXD and you should probably talk the the people who maintain that container manager instead :)

**Comment by jorgeventura** [comment]
Thank you Stephane! I figured out a way to do what I need.
