### ISSUE TITLE
uid/gid incorrect after using custom init via lxc file push

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#6632]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Bionic (18.04)
 * The output of "lxc info" or if that fails:
```
$ lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIB/jCCAYOgAwIBAgIQWvyD6ehXSyrNlIzhz3DESDAKBggqhkjOPQQDAzA4MRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRgwFgYDVQQDDA9yb290QHJoYXJw
    ZXItYjIwHhcNMTkxMjE2MjIzMzM2WhcNMjkxMjEzMjIzMzM2WjA4MRwwGgYDVQQK
    ExNsaW51eGNvbnRhaW5lcnMub3JnMRgwFgYDVQQDDA9yb290QHJoYXJwZXItYjIw
    djAQBgcqhkjOPQIBBgUrgQQAIgNiAAR3cVaR74JmHjFow6bdw5yga1LelDosWD9j
    sLWoVG4BSakE/nMq/T7WzjQDiMjnL36FUXy6ZVwTVwmvMPxtgQSxxzzz6brgPq1T
    ccIC/GY2VBVyhN6L09gKoKBRuTcwRdCjUjBQMA4GA1UdDwEB/wQEAwIFoDATBgNV
    HSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMBsGA1UdEQQUMBKCCnJoYXJw
    ZXItYjKHBMCoehYwCgYIKoZIzj0EAwMDaQAwZgIxAMNjK7uLgXaPzjqI5n0WuXpY
    0l7Vzr61kF0FyGpW+CP+bJXOsQURLw52W3PL/qb5/AIxANjfhYQkjemAH/vBqoOL
    8vweEVow1u5ZLfDoXK8ezXKF3jOv8zQL8i6+HKSulVziRA==
    -----END CERTIFICATE-----
  certificate_fingerprint: ecb6309fd8272dd31348463cb61a0a3e06561e69a7d44615d63d297470a5d932
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.15.0-72-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: rharper-b2
  server_pid: 1565
  server_version: "3.17"
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.6
```
  
# Issue description

We use a custom init to inject files into "pristine" images.  On lxd 3.17/3.18, the file permissions inside the container are no longer correctly mapped if we use a custom init.  This same process does not fail on lxd 3.0 (what's currently installed in bionic by default).

# Steps to reproduce

 1. Launch an ubuntu 18.04 VM, ssh into VM
 2. wget https://raw.githubusercontent.com/smoser/qa-scripts/mini-issue/scripts/lxc-pstart
 3. chmod +x lxc-pstart
 4. lxd init  # take all defaults
 5. lxc init ubuntu-daily:eoan e1
 6. ./lxc-pstart --start e1 /bin/true
 7. lxc start e1
 8. lxc exec e1 -- ls -al /

The output from 8 will show root.root ownership on lxd 3.0 and on 3.17/3.18, the ownership is 1000000 1000000.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Can you provide reproduction steps which rely on LXD commands rather than that long external python script?

**Comment by smoser** [comment]
lxc-pstart has a `--dump-commands` option just for this scenario.
Below is an interaction with lxc.  the `$` prompt is my typing,
the `pstart% ` prompt is pstart running commands. You should
be able to copy and paste into your shell if you'd like.

As a summary, though:

  * create new container
  * create a profile `pstart1` if it does not exist.
     The profile does nothing except change the init command via `lxc.init.cmd` to `/sbin/psuedo-init`
  * edit the container's config to include the `pstart1` profile.
  * push a shell script into the container at `/sbin/psuedo-init` (0755 root:root)
  * Start the container.
  * lxc execute `psuedo-init wait` . lxc execute `ls -al /`.
  * Stop the container
  * remove the `pstart1` profile from the container's profile list.
  * Start the container
  * lxc execute `ls -al /`


The full session:
    
    $ lxc init ubuntu-daily:eoan e1
    Creating e1
    $ ./scripts/lxc-pstart --dump-commands --start e1 /bin/true
    pstart% lxc config show e1
    <stdout>
    architecture: x86_64
    config:
      image.architecture: amd64
      image.description: ubuntu 19.10 amd64 (daily) (20191213)
      image.label: daily
      image.os: ubuntu
      image.release: eoan
      image.serial: "20191213"
      image.type: squashfs
      image.version: "19.10"
      volatile.apply_template: create
      volatile.base_image: c33f22f166a644953829995923c8f8eec8084756befb22fb9f7f3f7a302ec429
      volatile.eth0.hwaddr: 00:16:3e:18:f3:2b
      volatile.idmap.base: "0"
      volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
      volatile.last_state.idmap: '[]'
    devices: {}
    ephemeral: false
    profiles:
    - default
    stateful: false
    description: ""
    
    pstart% lxc profile show pstart1
    <stderr>
    Error: Fetch profile: No such object
    
    pstart% lxc profile create pstart1
    <stdout>
    Profile pstart1 created
    
    pstart% lxc profile edit pstart1 <<"PSTART_EOF"
    config: {raw.lxc: lxc.init.cmd=/sbin/psuedo-init}
    description: Profile for psuedo-start.
    
    PSTART_EOF
    pstart% lxc config edit e1 <<"PSTART_EOF"
    architecture: x86_64
    config: {image.architecture: amd64, image.description: ubuntu 19.10 amd64 (daily)
        (20191213), image.label: daily, image.os: ubuntu, image.release: eoan, image.serial: '20191213',
      image.type: squashfs, image.version: '19.10', volatile.apply_template: create, volatile.base_image: c33f22f166a644953829995923c8f8eec8084756befb22fb9f7f3f7a302ec429,
      volatile.eth0.hwaddr: '00:16:3e:18:f3:2b', volatile.idmap.base: '0', volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]',
      volatile.last_state.idmap: '[]'}
    description: ''
    devices: {}
    ephemeral: false
    profiles: [default, pstart1]
    stateful: false
    
    PSTART_EOF
    pstart% lxc file push --mode=0755 --uid=0 --gid=0 - e1/sbin/psuedo-init <<"PSTART_EOF"
    #!/bin/sh
    KID=""
    do_exit() {
        [ -z "$KID" ] || kill $KID
        echo "good bye."
    }
    main() {
        [ "$1" = "wait" ] && { return 0; }
        trap "echo got SIGPWR; exit 0;" PWR
        trap "echo got SIGQUIT; exit 0;" QUIT
        trap do_exit EXIT
        sleep 1d &
        KID=$!
        echo "init up. sleeping kid is pid $KID"
        wait
        ret=$?
        echo "$KID finished $ret"
        KID=""
        exit $ret
    }
    main "$@"
    
    PSTART_EOF
    pstart% lxc start e1
    pstart% lxc exec e1 -- /sbin/psuedo-init wait
    pstart% lxc exec e1 -- /bin/true
    pstart% lxc stop e1
    pstart% lxc config edit e1 <<"PSTART_EOF"
    architecture: x86_64
    config: {image.architecture: amd64, image.description: ubuntu 19.10 amd64 (daily)
        (20191213), image.label: daily, image.os: ubuntu, image.release: eoan, image.serial: '20191213',
      image.type: squashfs, image.version: '19.10', volatile.apply_template: create, volatile.base_image: c33f22f166a644953829995923c8f8eec8084756befb22fb9f7f3f7a302ec429,
      volatile.eth0.hwaddr: '00:16:3e:18:f3:2b', volatile.idmap.base: '0', volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]',
      volatile.last_state.idmap: '[]'}
    description: ''
    devices: {}
    ephemeral: false
    profiles: [default]
    stateful: false
    
    PSTART_EOF
    $ 
    $ 
    $ lxc start e1; sleep 5; lxc exec e1 -- ls -al /
    total 20
    drwxr-xr-x  18 1000000 1000000  24 Dec 13 07:57 .
    drwxr-xr-x  18 1000000 1000000  24 Dec 13 07:57 ..
    lrwxrwxrwx   1 1000000 1000000   7 Dec 13 07:51 bin -> usr/bin
    drwxr-xr-x   2 1000000 1000000   2 Dec 13 07:57 boot
    drwxr-xr-x   8 root    root    500 Dec 17 02:09 dev
    drwxr-xr-x  89 1000000 1000000 178 Dec 17 02:09 etc
    drwxr-xr-x   3 1000000 1000000   3 Dec 17 02:09 home
    lrwxrwxrwx   1 1000000 1000000   7 Dec 13 07:51 lib -> usr/lib
    lrwxrwxrwx   1 1000000 1000000   9 Dec 13 07:51 lib32 -> usr/lib32
    lrwxrwxrwx   1 1000000 1000000   9 Dec 13 07:51 lib64 -> usr/lib64
    lrwxrwxrwx   1 1000000 1000000  10 Dec 13 07:51 libx32 -> usr/libx32
    drwxr-xr-x   2 1000000 1000000   2 Dec 13 07:52 media
    drwxr-xr-x   2 1000000 1000000   2 Dec 13 07:52 mnt
    drwxr-xr-x   2 1000000 1000000   2 Dec 13 07:52 opt
    dr-xr-xr-x 574 nobody  nogroup   0 Dec 17 02:09 proc
    drwx------   3 1000000 1000000   5 Dec 17 02:09 root
    drwxr-xr-x  14 root    root    480 Dec 17 02:09 run
    lrwxrwxrwx   1 1000000 1000000   8 Dec 13 07:51 sbin -> usr/sbin
    drwxr-xr-x   2 1000000 1000000   3 Dec 17 02:09 snap
    drwxr-xr-x   2 1000000 1000000   2 Dec 13 07:52 srv
    dr-xr-xr-x  13 nobody  nogroup   0 Dec 16 16:30 sys
    drwxrwxrwt   6 root    root      6 Dec 17 02:10 tmp
    drwxr-xr-x  14 1000000 1000000  14 Dec 13 07:53 usr
    drwxr-xr-x  13 1000000 1000000  15 Dec 13 07:54 var
    $ 
    $ lxc delete --force e1
    $ lxc profile delete pstart1
    Profile pstart1 deleted

**Comment by stgraber** [comment]
Thanks, this output indicates that your script is the problem.

Your last `lxc config edit` is modifying the idmap values, causing LXD to shift the container again on startup, creating this problem.

**Comment by stgraber** [comment]
Specifically the `volatile.last_state.idmap` key at least will have changed value by the time you issue that last `lxc config edit` so you're accidentally modifying it back to a value indicating the filesystem state isn't shifted. When the container is then started, LXD shiftfs everything again, causing what you're seeing.

**Comment by raharper** [comment]
But why does it break in newer than 3.0.3?

**Comment by raharper** [comment]
And as a follow up, what can we do to not break on modern lxd vs older lxd?  Our tool may run on Xenial/Bionic but also on newer releases.

**Comment by stgraber** [comment]
You should do `lxc config show`, then edit, then `lxc config edit`.
If you do that, you'll be fine. Above you're doing a `lxc config show` then edit, then starting, then edit again, so any config key that LXD wrote while the container was started gets reset/deleted.

The only reason why you don't get hit by this on 3.0.3 is a bug in our shifting logic there which I believe will likely be fixed in 3.0.5. Basically the shifting logic hits during create rather than first startup, so you're not seeing this issue, instead seeing a lot more I/O during create time. We've been moving that logic to startup as a way to better spread I/O when creating a batch of container at the same time.

**Comment by stgraber** [comment]
Worth noting that if you were using the Go client for our API, this mistake wouldn't be possible as LXD gives you an ETag value when retrieving the configuration which you should supply when subsequently editing the configuration. If anything changes in between, LXD will refuse the config change, avoiding such issues.

If going straight to the REST API, you could also use `PATCH` rather than `PUT` to only submit the one key you want to modify rather than overwriting the whole thing.

Similarly even with the CLI as you're doing it, you could rely on `lxc config set` and `lxc config device` to similarly avoid races.

**Comment by smoser** [comment]
fwiw, `lxc config set` doesn't seem to be able to modify or read the 'profiles'.

**Comment by stgraber** [comment]
Indeed, you'd want to use `lxc profile add`, `lxc profile assign` or `lxc profile remove` for this instead.
