### ISSUE TITLE
500 internal server error on file upload

### ISSUE THREAD

**Issue by suprasoil** [lxc/lxd#6644]
### Problem

I'm getting sporadic internal server errors on uploading plaintext files to the LXD api.

### Software

```
root@alpha-0001:/# snap list
Name  Version    Rev    Tracking  Publisher   Notes
core  16-2.42.5  8268   stable    canonical✓  core
lxd   3.18       12631  3.18      canonical✓  -
```
```
root@alpha-0001:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

### Logs

Info about request:
```
StatusCodeError: 500 - "{\"error\":\"file does not exist\",\"error_code\":500,\"type\":\"error\"}\n\n"                              
// removed for brevity                                       
  name: 'StatusCodeError',                                                                                                          
  statusCode: 500,                                                                                                                  
  message: '500 - "{\\"error\\":\\"file does not exist\\",\\"error_code\\":500,\\"type\\":\\"error\\"}\\n\\n"',                     
  error: '{"error":"file does not exist","error_code":500,"type":"error"}\n\n',                                                     
  options: {                                                                                                                        
// removed for brevity  
    },                                                                    
    ecdhCurve: 'secp384r1',                          
    json: false,                                                  
    method: 'POST',                                         
    url: 'https://10.254.0.4:8443/1.0/containers/tree-9a763b55-51a2-47e5-aa35-af7238a90290/files',
    qs: { path: '/etc/environment' },   
    headers: { 'X-LXD-type': 'file', 'Content-Type': 'plain/text' },
    body: '\n' +                   
      'ENVIRONMENT_VARIABLE=value\n' +                                                    
      '\n' +                                                
```                          

I can't find anything in the lxd daemon logs.

Also, i haven't reported this for quite some time as i'd found this: https://github.com/lxc/lxd/issues/5240 which seems like the same problem to me as i did not set the `Content-Type` header manually. Now i'm passing the header since a few days though and i'm still encountering this bug.

Also, a lot of containers get set up, but this problem occurs only sporadically.

**Comment by stgraber** [comment]
So the error is in fact `file does not exist` which is returned by Go.

This could be a few different things:
 - Something wiping your temporary directory during a transfer (causing the source file to go away)
 - The target file being handled by something else in parallel (/etc/environment in this case)
 - The parent directory ('/etc') not existing for some reason
 - In theory the container getting shutdown at that exact time could lead to a similar error

We're going to need a more reliable reproducer to be able to figure out what's going on.

**Comment by suprasoil** [comment]
> Something wiping your temporary directory during a transfer (causing the source file to go away)

There is no source file, i'm passing the body directly

> The target file being handled by something else in parallel (/etc/environment in this case)

I'm getting these with other files as well, not only `/etc/environment`

> The parent directory ('/etc') not existing for some reason

Could you elaborate? How would this be the case in some instances and not in others when the same image is used?

> In theory the container getting shutdown at that exact time could lead to a similar error

Maybe somethings up on my side that's causing this, will investigate

Thanks for the fast response as always

**Comment by stgraber** [comment]
@suprasoil LXD stores it as a temporary file before it's copied over. If that temporary file is deleted by a cronjob cleaning up /tmp or something, this could cause that kind of error.

**Comment by suprasoil** [comment]
Well, after some investigation i think these are *not* the case:
> * Something wiping your temporary directory during a transfer (causing the source file to go away)

There's a lot of old files in /tmp when this problem occurs

> * The parent directory ('/etc') not existing for some reason

When deploying the same image containing an /etc multiple times, sometimes this problem occurs, most of the times it does not.
> * In theory the container getting shutdown at that exact time could lead to a similar error

The container will still be alive & working after this problem has occurred

As for this:
> The target file being handled by something else in parallel (/etc/environment in this case)

Could it be that a slow disk is causing the temporary file created by LXD to not exist when LXD is trying to read from it?

**Comment by stgraber** [comment]
No, LXD writes the file when processing the request data, then calls the function which enters the container and writes the file inside it. It's that function which is returning the `file does not exist` error.

When this happens, does an immediate retry succeed? If so, this is going to be a bit of a pain to reproduce and debug :)

**Comment by stgraber** [comment]
@suprasoil

**Comment by Spunge** [comment]
I will add a direct retry and report back.

**Comment by stgraber** [comment]
thanks

**Comment by stgraber** [comment]
Ok, so in that case the list of what's failing may be a bit different.
Do you have multiple of those file transfers against the same container in parallel?

As the container is offline, LXD effectively needs to:
 - Receive the file in a temporary path
 - Mount the container
 - Run forkfile which will chroot in the container and write the file
 - Unmount the container

We normally have logic preventing conflicts around mounts so that one action doesn't unmount something still needed by another but there may be a missing check somewhere, if parallel transfer or parallel actions needing a mounted/unmounted container are going on.

What's your storage driver (not sure if mentioned before)?

**Comment by suprasoil** [comment]
Ah yeah, that could very well be it. I checked (only one case of this problem after adding the retry loop) and there is 2 files being uploaded in parallel, i've now changed this to be sequential.

Storage driver is ZFS.

**Comment by stgraber** [comment]
Okay, if that fixes it for you, it will give us a good idea of where the problem may be.
It's also plausible that LXD 3.19 fixes it as we've completely rewritten the storage layer and so may be doing a better job at dealing with such parallel actions.

**Comment by stgraber** [comment]
@suprasoil if you're running 3.19 or 3.20 now, any chance you can report whether you can still reproduce that race when doing parallel transfers? If so, I'll go and track it down.

**Comment by suprasoil** [comment]
I will be keeping an eye on the logs and let you know.

**Comment by stgraber** [comment]
@suprasoil all good?

**Comment by suprasoil** [comment]
Haven't seen this since, so let's close this issue.
