### ISSUE TITLE
Implement /1.0/meta-data over the /dev/lxd interface

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#665]
We vaguely mention it in the spec (in examnple output of `GET /1.0/containers/<name>`, but we should flush this out. I assume right now this is just another post parameter, but we also need to figure out what to do about where to stuff it into the rootfs since we don't have `/dev/lxd` yet.

**Comment by stgraber** [comment]
I have some notes on that from our meeting with Scott in Malta, I'll try to do the required spec work next week.

Basically the concept is:
 - A bunch of user.* config keys
 - Templating support in images
 - /dev/lxd protocol to access the config keys + get container info

**Comment by howbazaar** [comment]
We want to make sure that we can also pass userdata to the clone calls.

**Comment by stgraber** [comment]
A clone is a copy operation. From an API point of view, a copy is a container creation using an existing container as the source. As the API for container creation does support setting configuration keys, this is therefore already covered and supported today (minus the fact that we do not use those config keys).

**Comment by stgraber** [comment]
The /dev/lxd interface has now been defined, it provides the following things to cloud-init:
 - meta-data (generated by LXD itself and exposed through /dev/lxd)
 - user-data, defined as a regular config key in the user config namespace, so "lxc config set user.user-data blah"
 - vendor-data, defined as a regular config key in the user config namespace, so "lxc config set user.vendor-data blah"

The next step here is to implement the templating engine for the images, then we can ship a template which generates the user-data file within the container every time it's started.

**Comment by stgraber** [comment]
Pushing this one to the next milestone and instead moving the templating issue to this milestone.

**Comment by stgraber** [comment]
We now have both templating and /dev/lxd, so seeding cloud-init is just a matter of having the images either ship a cloud-init version that's aware of /dev/lxd (none at present) or ship a template for /var/lib/cloud-init/... that takes the value from user.user-data and dumps it into the seed file.

**Comment by stgraber** [comment]
@tych0 pointed out that this isn't quite fully implemented. We do have the mechanism required for user-data and vendor-data through read access to the container user config namespace, but we do not have a renderer for meta-data (/1.0/meta-data).

So updating the bug title and description to match that and re-targeting to next milestone.
