### ISSUE TITLE
Unique constraint failed on images_profiles when updating to edge

### ISSUE THREAD

**Issue by gabriel-samfira** [lxc/lxd#6657]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info": https://paste.ubuntu.com/p/XJg9Fcsfzt/

# Issue description

After switching from the stable channel to the edge channel, lxd failed to start with the following error:

```bash
root@rossak:/var/snap/lxd/common/lxd/database# /snap/bin/lxd --debug --group lxd
DBUG[12-23|13:18:45] Connecting to a local LXD over a Unix socket 
DBUG[12-23|13:18:45] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
INFO[12-23|13:18:45] LXD 3.18 is starting in normal mode      path=/var/snap/lxd/common/lxd
INFO[12-23|13:18:45] Kernel uid/gid map: 
INFO[12-23|13:18:45]  - u 0 0 4294967295 
INFO[12-23|13:18:45]  - g 0 0 4294967295 
INFO[12-23|13:18:45] Configured LXD uid/gid map: 
INFO[12-23|13:18:45]  - u 0 1000000 1000000000 
INFO[12-23|13:18:45]  - g 0 1000000 1000000000 
INFO[12-23|13:18:45] Kernel features: 
INFO[12-23|13:18:45]  - netnsid-based network retrieval: yes 
INFO[12-23|13:18:45]  - uevent injection: yes 
INFO[12-23|13:18:45]  - seccomp listener: yes 
INFO[12-23|13:18:45]  - seccomp listener continue syscalls: yes 
INFO[12-23|13:18:45]  - unprivileged file capabilities: yes 
INFO[12-23|13:18:45]  - cgroup layout: hybrid 
WARN[12-23|13:18:45]  - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored 
WARN[12-23|13:18:45]  - Couldn't find the CGroup memory swap accounting, swap limits will be ignored 
INFO[12-23|13:18:45]  - shiftfs support: yes 
INFO[12-23|13:18:45] Initializing local database 
DBUG[12-23|13:18:45] Initializing database gateway 
DBUG[12-23|13:18:45] Start database node                      id=1 address=
DBUG[12-23|13:18:46] Connecting to a local LXD over a Unix socket 
DBUG[12-23|13:18:46] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
DBUG[12-23|13:18:46] Detected stale unix socket, deleting 
INFO[12-23|13:18:46] Starting /dev/lxd handler: 
INFO[12-23|13:18:46]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[12-23|13:18:46] REST API daemon: 
INFO[12-23|13:18:46]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[12-23|13:18:46] Initializing global database 
DBUG[12-23|13:18:46] Dqlite: connected address=1 id=1 attempt=0 
INFO[12-23|13:18:46] Updating the LXD global schema. Backup made as "global.bak" 
DBUG[12-23|13:18:46] Updating global DB schema from 21 to 22 
DBUG[12-23|13:18:46] Database error: &errors.errorString{s:"failed to apply update 21: UNIQUE constraint failed: images_profiles.image_id, images_profiles.profile_id"} 
EROR[12-23|13:18:46] Failed to start the daemon: failed to open cluster database: failed to ensure schema: failed to apply update 21: UNIQUE constraint failed: images_profiles.image_id, images_profiles.profile_id 
INFO[12-23|13:18:46] Starting shutdown sequence 
INFO[12-23|13:18:46] Stopping REST API handler: 
INFO[12-23|13:18:46]  - closing socket                        socket=/var/snap/lxd/common/lxd/unix.socket
INFO[12-23|13:18:46] Stopping /dev/lxd handler: 
INFO[12-23|13:18:46]  - closing socket                        socket=/var/snap/lxd/common/lxd/devlxd/sock
DBUG[12-23|13:18:46] Stop database gateway 
DBUG[12-23|13:18:46] Not unmounting temporary filesystems (containers are still running) 
Error: failed to open cluster database: failed to ensure schema: failed to apply update 21: UNIQUE constraint failed: images_profiles.image_id, images_profiles.profile_id
```

Looking at the global database, in ```/var/snap/lxd/common/lxd/database/global/db.bin``` this is what I found:

```sql
sqlite> .headers on
sqlite> select * from images_profiles;
image_id|profile_id
62|1
79|1
79|1
79|1
79|1
80|1
80|1
sqlite> select * from images;
id|fingerprint|filename|size|public|architecture|creation_date|expiry_date|upload_date|cached|last_use_date|auto_update|project_id|type
62|f75468c572cc50eca7f76391182e6fdaf58431f84c3d35a2c92e83814e701698|ubuntu-18.04-server-cloudimg-amd64-lxd.tar.xz|187306768|0|2|2019-12-05 00:00:00+00:00|2023-04-26 00:00:00+00:00|2019-12-06 04:11:06.610926172+00:00|0|2019-11-28 15:33:22.095286913+02:00|1|1|0
79|68bfd7ad97e383a5279f1903f14bd2f9f71b44b7ce6a081a582300dc284ad29b|lxd.tar.xz|87134912|0|2|2019-12-13 00:00:00+00:00|1970-01-01 00:00:00+00:00|2019-12-13 10:16:54.915457559+00:00|0|0001-01-01 01:44:48+01:44|1|1|0
80|5d99b0db423410643bda5017b96b9cb48501a7c670ac4b0d468b026db0043054|ubuntu-18.04-server-cloudimg-amd64-lxd.tar.xz|344458004|0|2|2019-11-14 00:00:00+00:00|2023-04-26 00:00:00+00:00|2019-12-13 11:46:57.760653883+00:00|0|0001-01-01 00:00:00+00:00|1|1|1
```
To work around this, I had to create a file:

/var/snap/lxd/common/lxd/database/patch.global.sql

with the following contents:

```sql
# delete all current image_profiles
delete from images_profiles;
# insert image_profiles, without duplicates
insert into images_profiles values (62, 1);
insert into images_profiles values (79, 1);
insert into images_profiles values (80, 1);
```

After which lxd finally started normally. I am not sure if this is an actual bug, or if there was something on my system, but this is how I got passed it, in case someone else runs into this particular issue.

Thanks for having that ```patch.global.sql``` custom hook thing :).

**Comment by stgraber** [comment]
Does that happen on a clean install of stable followed by an upgrade to edge?
When did you perform the switch to edge?

We did have an issue in edge a little while back where that people got created but was mis-populated, leading to duplicates. We've then fixed the schema to avoid this, altering the schema on upgrade as needed. This would however cause upgrade issues for anyone who had the bad database entries.

**Comment by gabriel-samfira** [comment]
I think I attempted to upgrade ~2 weeks ago. I tried a clean install in a VM and upgraded to edge, which worked. I think an upgrade script that checks for duplicates before attempting to create a unique constraint should fix this for users that have had their DB mis-populated. 

In any case, I was aware that this was probably an edge case that not many people ran into, so I created this issue in the hopes it might provide a workaround for those few that ran into this, and might want to avoid reinstalling :).

Thanks for the great project!

P.S. feel free to close this issue if you feel it has been addressed already.

**Comment by stgraber** [comment]
Yeah, there was a window of a few days where depending on image operations you could have gotten your db into a non-upgradable case. I was actually hit by such duplicates which is what prompted me to fix the schema. Initially the fix was to just add the unique constraint in the db update path, leaving existing edge users without it. We've then gone back on that and added the logic to fix the schema for everyone including those edge users.

It would probably have been a good idea to tweak that logic to also filter out duplicates, though as that change was pushed almost two weeks ago now and edge refreshes daily, anyone who would have gotten broken would be broken by this point, so doing further changes is unlikely to help as they already need the manual operation to get back online and get further updates.

Thanks for the report, that did show that I'm not the only one who ran into this and in the future we will try to remember to also de-duplicate the data during such an upgrade to avoid this hitting edge users.
