### ISSUE TITLE
bfq scheduler and cgroup blkio.weight

### ISSUE THREAD

**Issue by iRbouh** [lxc/lxd#6658]
Hi,

If you use the `bfq` scheduler the weight filename would be `blkio.bfq.weight`!  and the follwing warning will show up `Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored.`

https://github.com/lxc/lxd/blob/9cf72363bb886f313176e50446b965ad5e85a409/lxd/cgroup/init.go#L371

**Comment by stgraber** [comment]
@brauner want to take this one?

**Comment by brauner** [comment]
> @brauner want to take this one?

Yeah, already have a patch. Just reviewing kernel patches rn.
