### ISSUE TITLE
Inconsistent user-agent sent from LXD

### ISSUE THREAD

**Issue by joewholden** [lxc/lxd#6662]
Hi guys,

I've noticed that the user-agent sent from LXD when talking to another LXD remote isn't consistent.
Sometimes it sends 'Go-http-client/1.1' and other times 'LXD ' - I'm not that familiar with Go so i'm not entirely sure where to look, but is there any chance this could be made consistent (or ideally, send other headers to identify LXD)?

'Go-http-client/1.1' sometimes appears in the first request for /, but not so far in the request for /1.0

I'm currently testing on Arch (recently updated), LXC 3.2.1, LXD 3.18 (modified aur pkgbuild) on x86_64 although I don't expect it to behave any differently on other platforms.

Thanks!

**Comment by stgraber** [comment]
Do you have some specific examples of when this happens?

I'm not seeing any obvious code paths where the `lxc` CLI tool would ever instantiate an http client that lacks the user agent string. But it is certainly possible for other cases within LXD itself to be missing that logic.

**Comment by joewholden** [comment]
It seems to be during a fresh 'lxc remote add'

**Comment by joewholden** [comment]
Awesome, thanks!
