### ISSUE TITLE
sys-kernel-config.mount fails to load in unprivileged container

### ISSUE THREAD

**Issue by jdstrand** [lxc/lxd#6676]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 18.04 LTS
 * The output of "lxc info" or if that fails:
```
$ lxc info # via snap
config:
  images.auto_update_cached: "false"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
- id_map_current
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    ...
  certificate_fingerprint: ...
  driver: lxc
  driver_version: 3.0.4
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features: {}
  kernel_version: 4.15.0-72-generic
  lxc_features: {}
  project: ""
  server: lxd
  server_clustered: false
  server_name: ...
  server_pid: 1256
  server_version: 3.0.4
  storage: dir
  storage_version: "1"
```

# Issue description

I saw https://github.com/lxc/lxc/issues/436 but it was quite old. I apologize if this is a duplicate or known issue.

On a bionic host, in a bionic unprivileged container, the container almost, but not quite, comes up clean. The only issue is:

```
$ sudo systemctl --failed --all
  UNIT                    LOAD   ACTIVE SUB    DESCRIPTION                     
● sys-kernel-config.mount loaded failed failed Kernel Configuration File System

$ sudo systemctl status sys-kernel-config.mount
● sys-kernel-config.mount - Kernel Configuration File System
   Loaded: loaded (/lib/systemd/system/sys-kernel-config.mount; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-01-07 09:40:22 CST; 24min ago
    Where: /sys/kernel/config
     What: configfs
     Docs: https://www.kernel.org/doc/Documentation/filesystems/configfs/configfs.txt
           https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
  Process: 61 ExecMount=/bin/mount configfs /sys/kernel/config -t configfs (code=exited, status=32)

Jan 07 09:40:23 test mount[61]: mount: /sys/kernel/config: permission denied.
```

It is my understanding that this is desirable behavior and that /sys/kernel/config is intentionally not loaded in the container and services in the container seem to run fine so I just assume not add the access. 

I'm currently using `sudo systemctl mask sys-kernel-config.mount` which 'works', but I'm not sure it is the right approach. Are unprivileged containers expected to come up clean by default? If not, what is the recommended way of handling this?

**Comment by brauner** [comment]
Unprivileged containers will have some services failing. configfs failing is fine imho. Usually services that fail but are not detrimental can just be ignored. One option to not have them fail is to mask them via systemctl mask.

**Comment by stgraber** [comment]
I don't believe it is safe to have this mounted in unprivileged containers which is why the kernel refuses the mount (even outside of apparmor rules).

I suspect the right fix for this would be a change to the systemd unit to not mount when inside a container.

**Comment by stgraber** [comment]
Closing as not a LXD bug and not something we'd actually ever want to allow.

I'd strongly recommend opening a bug against systemd and/or sending a PR which adds a container restriction on this unit so that it doesn't show up as failed on startup.

**Comment by aadnehovda** [comment]
Ran into this on Proxmox and I resolved it by adding `lxc.cap.drop: sys_rawio` to my config and this is the result, no more error. What may I be missing by dropping that cap in an unprivileged container? 

```
root@erling:~# systemctl status sys-kernel-config.mount
* sys-kernel-config.mount - Kernel Configuration File System
     Loaded: loaded (/lib/systemd/system/sys-kernel-config.mount; static)
     Active: inactive (dead)
  Condition: start condition failed at Tue 2021-11-09 11:21:58 UTC; 3min 47s ago
             `- ConditionCapability=CAP_SYS_RAWIO was not met
      Where: /sys/kernel/config
       What: configfs
       Docs: https://www.kernel.org/doc/Documentation/filesystems/configfs/configfs.txt
             https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
```

This was also an interesting read, don't know if it's relevant: https://systemd.io/CONTAINER_INTERFACE/

**Comment by stgraber** [comment]
I don't think you're likely to miss anything by dropping `sys_rawio` inside of an unprivileged container as I'd expect just about every kernel codepath requiring this capability to check it against the host namespace. We in theory could add mediated raw PCI access or something down the line through syscall interception which would then make use of that capability in the container, but it's not something we've seen any need for yet.

**Comment by Ikomaz** [comment]
![fix](https://user-images.githubusercontent.com/131301327/233181886-03aac690-ffad-4891-a07f-731caf9bbd81.jpg)
how i can fix this, help plaese! its a nextcloud server 25.0.1 in debian 11
