### ISSUE TITLE
lxc import ignores volume.size on LVM storage pool

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#6687]
* Distribution: Ubuntu
 * Distribution version: 20.04
 * # lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICHjCCAaWgAwIBAgIRAJSBBgWxsPNQBBO9LVPZOzowCgYIKoZIzj0EAwMwQTEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEhMB8GA1UEAwwYcm9vdEBsdHJh
    Z2VyLXgxLWV4dHJlbWUyMB4XDTE5MTIyOTE4Mjk1NFoXDTI5MTIyNjE4Mjk1NFow
    QTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEhMB8GA1UEAwwYcm9vdEBs
    dHJhZ2VyLXgxLWV4dHJlbWUyMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEP+xgxyvL
    QnMsrrM4ONfo+Wau5Dscz+egDQOTpIhesIL+wm8M63L2C9YG+YtWHlSKDXZuMQB9
    +4mMsi6se2NgyW3Leg9gsySgrrCAsI2MaKz2rCKpOVq0/LJNwZq2w2fPo2EwXzAO
    BgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIw
    ADAqBgNVHREEIzAhghNsdHJhZ2VyLXgxLWV4dHJlbWUyhwTAqAG5hwTAqHoBMAoG
    CCqGSM49BAMDA2cAMGQCMB9F1pQ9bDqBepT/4G5nA4Fqz9oy98KISk7yT6prETGf
    45ss1lGsXUgyEu8DVOUBmgIwZC3cO5poNfEllB99lLoeZf37DFn0hIY9flKi2Nfd
    bZv7lhEyEJMnlUDVQjzIPdPe
    -----END CERTIFICATE-----
  certificate_fingerprint: e968afca753e8f5e68af9d6e25cb818f9ae848b22ca60bf6e236c33a9613a45b
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-9-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: ltrager-x1-extreme2
  server_pid: 2378
  server_version: "3.18"
  storage: dir | lvm
  storage_version: 1 | 2.02.133(2) (2015-10-30) / 1.02.110 (2015-10-30) / 4.41.0

# lxc storage show intel-ssd
`config:
  lvm.thinpool_name: LXDThinPool
  lvm.vg_name: intel-ssd
  source: intel-ssd
  volatile.initial_source: intel-ssd
  volume.size: 20GB
description: ""
name: intel-ssd
driver: lvm
used_by:
- /1.0/profiles/default
- /1.0/profiles/maas
status: Created
locations:
- none`

# lvdisplay
`--- Logical volume ---
  LV Name                LXDThinPool
  VG Name                intel-ssd
  LV UUID                1j8E0S-pd8g-T4eB-sed9-XStX-Hmva-dTHMJ6
  LV Write Access        read/write
  LV Creation host, time ltrager-x1-extreme2, 2020-01-08 14:31:58 -0800
  LV Pool metadata       LXDThinPool_tmeta
  LV Pool data           LXDThinPool_tdata
  LV Status              available
  # open                 2
  LV Size                <236.46 GiB
  Allocated pool data    4.21%
  Allocated metadata     2.14%
  Current LE             60533
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:6
   
  --- Logical volume ---
  LV Path                /dev/intel-ssd/containers_maas--dev--bionic
  LV Name                containers_maas--dev--bionic
  VG Name                intel-ssd
  LV UUID                fBKr9S-AYuB-noPT-oLmk-i5Iq-U700-JRRGPf
  LV Write Access        read/write
  LV Creation host, time ltrager-x1-extreme2, 2020-01-09 17:43:42 -0800
  LV Pool name           LXDThinPool
  LV Status              available
  # open                 1
  LV Size                10.00 GiB
  Mapped size            99.65%
  Current LE             2560
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:8`

# Issue description
I recently bought a new laptop and I am trying to migration my containers over using the lxc import command. My container is 9.8GB on my old laptop using a dir driver backed storage pool. The import fails as the volume runs out of space. As suggested in #6134 I set volume.size in the storage profile to 20GB, manually deleted the previously created LV and tried to import again. LXC is still creating a 10GB LV despite my config change.

# Steps to reproduce
1. Export a container using the lxc export command
2. Configure an LVM backed storage pool
3. Set volume.size to 20GB
4. Import the container
5. See that the imported LV is only 10GB.

**Comment by stgraber** [comment]
@tomponline can you test to make sure the new lvm implementation does not suffer from this bug?

**Comment by tomponline** [comment]
@stgraber looks like it doesn't:

```
lxc storage create dir dir
lxc init ubuntu:18.04 c1 -s dir
lxc export c1 /home/user/backup.tar.gz

lxc storage create lvm lvm
lxc storage set lvm volume.size 20GB
lxc import /home/user/backup.tar.gz -s lvm

 sudo lvs --units G lvm
  LV                                                                      VG  Attr       LSize  Pool        Origin Data%  Meta%  Move Log Cpy%Sync Convert
  LXDThinPool                                                             lvm twi-aotz-- 40.85G                    5.22   1.68                            
  containers_test_c1                                                      lvm Vwi-a-tz-- 20.00G LXDThinPool        5.89                                   
  images_979ff60086ca9fb1c93d3131f8eca291820a524f0bd0b7d621a3c2f5f41ef185 lvm Vwi-a-tz-- 10.00G LXDThinPool        9.53               
```

Note I've used the `--units G` flag on `lvs` to instruct the report to shows sizes using SI gigabytes which is what `lxc storage set lvm volume.size 20GB` specifies rather than GiB.

**Comment by tomponline** [comment]
@stgraber however I noticed another bug, if the exported instance has a `size` property as part of its rootfs config, because the instance DB row has not been created at the time the imported volume is created, this does not get applied.

I've fixed that in my new LVM branch now so that the `backendLXD` inspects the `size` property on the rootfs as part of the post-hook and if its non-empty then runs `b.driver.SetVolumeQuota(vol, rootDiskConf["size"], op)` after the driver's own post hook.

```
lxc init ubuntu:18.04 c1 -s dir
lxc config device set c1 root size=15GB
lxc export c1 /home/user/backup.tar.gz
lxc delete c1

lxc import /home/user/backup.tar.gz -s lvm
sudo lvs --units G lvm
  LV                                                                      VG  Attr       LSize  Pool        Origin Data%  Meta%  Move Log Cpy%Sync Convert
  LXDThinPool                                                             lvm twi-aotz-- 40.85G                    5.69   1.69                            
  containers_test_c1                                                      lvm Vwi-a-tz-- 15.00G LXDThinPool        9.13                                   
  images_979ff60086ca9fb1c93d3131f8eca291820a524f0bd0b7d621a3c2f5f41ef185 lvm Vwi-a-tz-- 10.00G LXDThinPool        9.53 
```

**Comment by ltrager** [comment]
Since this is fixed in the new, unreleased LVM driver I have figured out a work around in the meantime.

1. Import the container into the default, dir driver backed, storage pool
    lxc import /home/user/backup.tar.gz -s default
2. Configure the LVM container for the correct size
    lxc storage set lvm volume.size 20GB
3. Move the container between storage pools, note you have to rename the container since its already on your system
    lxc move backup backup-lvm -s lvm
4. Rename the container back to the original name
    lxc moreve backup-lvm backup
