### ISSUE TITLE
Can not start a container after 3.19 upgrade : no mountpoint set

### ISSUE THREAD

**Issue by gbonazzoli** [lxc/lxd#6765]
After 3.19 snap upgrade I get the following error when I try to start a container created before 3.19 release.

```
root@lxd01:~# lxc start bionic

Error: Common start logic: Failed to run: zfs mount vgraid/lxd/containers/bionic: cannot mount vgraid/lxd/containers/bionic: no mountpoint set
Try  lxc info --show-log bionic for more info

```

I found also the following work around:

```
root@lxd01:~# zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/default/containers/bionic vgraid/lxd/containers/bionic

root@lxd01:~# zfs umount vgraid/lxd/containers/bionic

root@lxd01:~# lxc start disco

```
Hoping that it will not have side effects in other parts of the system

**Comment by stgraber** [comment]
Nope, that's a correct fix. Actually a slightly more correct fix would be:
 - zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/default/containers/bionic vgraid/lxd/containers/bionic canmount=noauto

Do you remember what LXD version you were running at the time you created that container?
Or do you remember if that container was maybe created as a copy of a local or remote container?

If we can figure out a pattern, we'll put a patch in place to correct any such issue on upgrade, otherwise we may just end up closing this and see if anyone else hits this and can track down what source version may have the issue.

**Comment by gbonazzoli** [comment]
Lxc/Lxd is constantly and automaticly updated by the snap system.So the
container was created with version that was
The container was created on:  2019/08/07 is saying the lxc info command:

root@lxd01:~# lxc info --show-log bionic
Name: bionic
Location: none
Remote: unix://
Architecture: x86_64
Created: 2019/08/07 16:30 UTC
Status: Stopped
Type: container
Profiles: default

For sure it may have been subjected to zfs send | zfs receive between lxc
hosts.

I usually do these sequence of command to quickly evacuate a physical host:

new host>: lxc init ubuntu:18.04 bionic
new host>: lxc config set bionic security.privileged true
new host>: lxc start bionic
new host>: lxc stop bionic
new host>: zfs destroy vgraid/lxd/containers/bionic

old host>: zfs send  vgraid/lxd/containers/bionic@last_snapshot | ssh
root@new_host "zfs receive  vgraid/lxd/containers/bionic"

**Comment by asolari** [comment]
The same happened here after 3.19 upgrade by snap.

```
root@host1:~# lxc start systest1
Error: Common start logic: Failed to run: zfs mount lxd-3/containers/systest1: cannot mount 'lxd-3/containers/systest1': no mountpoint set
Try 'lxc info --show-log systest1' for more info

```
```
root@host1:~# zfs list | grep systest1
lxd-3/containers/systest1                                       594M  99.3G   594M  none
```

```root@host1:~# zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/lxd/containers/systest1 canmount=noauto lxd-3/containers/systest1
```
```
root@host1:~# zfs list | grep systest1
lxd-3/containers/systest1                                       594M  99.3G   594M  /var/snap/lxd/common/lxd/storage-pools/lxd/containers/systest1

```
```
root@host1:~# lxc start systest1
root@host1:~# lxc list systest1
+----------+---------+-------------------+------+-----------+-----------+
|   NAME   |  STATE  |       IPV4        | IPV6 |   TYPE    | SNAPSHOTS |
+----------+---------+-------------------+------+-----------+-----------+
| systest1 | RUNNING | 10.10.0.63 (eth0) |      | CONTAINER | 0         |
+----------+---------+-------------------+------+-----------+-----------+
```

**Comment by stgraber** [comment]
I wrote a fix which will reset all mountpoint/canmount properties in one shot.

**Comment by astrablaster** [comment]
> Nope, that's a correct fix. Actually a slightly more correct fix would be:
> 
>     * zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/default/containers/bionic canmount=noauto vgraid/lxd/containers/bionic
> 
> 
> Do you remember what LXD version you were running at the time you created that container?
> Or do you remember if that container was maybe created as a copy of a local or remote container?
> 
> If we can figure out a pattern, we'll put a patch in place to correct any such issue on upgrade, otherwise we may just end up closing this and see if anyone else hits this and can track down what source version may have the issue.

canmount=noauto must precede filesystem specification:
zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/default/containers/bionic canmount=noauto vgraid/lxd/containers/bionic

**Comment by gbonazzoli** [comment]
Great !

It will be pushed also to my server, or only to new lxd 3.19 installations ?

Regards

**Comment by stgraber** [comment]
To all 3.19 installations.

**Comment by stgraber** [comment]
Pushed to candidate branch, building a snap now, will release to stable later (if still awake) or otherwise early tomorrow
