### ISSUE TITLE
 Invalid device option "path" when adding a device to a VM

### ISSUE THREAD

**Issue by leopaul36** [lxc/lxd#6767]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 19.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.0.0-38-generic
   * LXC version: 3.19
   * LXD version: 3.19
   * Storage backend in use: ZFS

# Issue description

When attaching a device to a VM, I would like to choose the path according to this [documentation](https://lxd.readthedocs.io/en/latest/instances/#type-disk), but I get the following error:

`Error: Invalid devices: Device validation failed "sdj": Invalid device option "path"`

It works without the `path` option but then it makes it harder to automate things as I am not sure under which /dev/sdX my mounted device will show up. I have had cases in which it was /dev/sdb, other thimes /dev/sdc.

Thanks for your help.

# Steps to reproduce

 1. lxc init ubuntu:19.04 testvm --vm --profile vm --storage virtpoo
 2. lxc config device add testvm sdj disk source=/dev/sdj1 path=/dev/sdj
 3. Error: Invalid devices: Device validation failed "sdj": Invalid device option "path"

**Comment by tomponline** [comment]
@leopaul36 this is a limitation of our VM implementation, the disk devices are added to the VM so they show up under /dev but we cannot control how and where they are mounted in the VM, hence the `path` property is not supported for VMs.

**Comment by tomponline** [comment]
We could do with clarifying this in the documentation though.

**Comment by tomponline** [comment]
The devices should as the same each boot, do you have an example where they change each boot?

**Comment by leopaul36** [comment]
@tomponline thanks, makes sense then.

About the change of the device path, I did encounter this behaviour with a VM let me try to reproduce it.

**Comment by stgraber** [comment]
I believe we get our devices in alphabetical order and assign them to the bus in that order so it should be constant (assuming we do indeed get the devices in a consistent order).

**Comment by leopaul36** [comment]
I have not been able to reproduce this yet. I will make sure to create an issue if encounter this problem again.

Thank you both for your help.

**Comment by broizter** [comment]
Sorry to piggyback on this issue, but how do you passthrough a folder? Since you can't specify a path, it gives me this error when I start the vm.

qemu-system-x86_64:/var/snap/lxd/common/lxd/logs/webserver/qemu.conf:165: A regular file was expected by the 'file' driver, but something else was given

```
lxc config device add webserver test disk source=/mnt/pool/storage/test
```
