### ISSUE TITLE
lxd init issue after installation

### ISSUE THREAD

**Issue by RangaArni** [lxc/lxd#6775]
# Required information

 * Distribution: BOSS GNU/Linux 7 (drishti)
 * Distribution version: 7.0
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.9.0-6-amd64
   * LXC version: 2.0.11
   * LXD version: 2.0.11
   * Storage backend in use:

# Issue description

I face issue post installation step(s) while "lxd init". Trying to initialize lxd init or lxc list. Got error: "Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: connection refused"
 
# Steps to reproduce

 1. apt lxd
 2. lxd init
 3. lxc list

# Information to attach

 - [*] Any relevant kernel output (`journalctl -xe`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
[journalctl-log.txt](https://github.com/lxc/lxd/files/4112578/journalctl-log.txt)

Thank you!

**Comment by stgraber** [comment]
Are you running the commands as root or as a member of the lxd group?
I'm also not aware of that distro, can you show `systemctl status lxd` and `systemctl status lxd.socket` for good measure?

**Comment by RangaArni** [comment]
distro is based on ubuntu... 
the user id is part of lxd group 
and i tried to issue sudo lxd init as well
status of lxd and lxd.socket were down as shown in the attachment.
tried to start lxd.socket it came up successfully.
but when starting lxd it is not and it brought down lxd.socket with apparmor error in the journalctl log in the attachment.
No /vr/log/lxd log file(s) yet.

**Comment by stgraber** [comment]
Right, so it's the packaging script run at `/usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load` which fails on your distribution.

```
-- The process /usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load could not be executed and failed.
```

This is a pre-requisite for the LXD unit so it failing prevents the entire thing from starting.

Looking at the error, the thing is just plain missing on your system?
This is normally provided by the `liblxc-common` package on Ubuntu systems.

Closing as this appears to be either a packaging error or some conflicting package setup in this Ubuntu derivative, tracking down and re-instating the missing file should avoid this.
