### ISSUE TITLE
LXD 3.19 trying to mount bookmarks

### ISSUE THREAD

**Issue by kevinkk525** [lxc/lxd#6777]
# Required information

 * Distribution: ubuntu
 * Distribution version: 19.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.0.0-38-generic
   * LXC version: 3.2.1
   * LXD version: 3.19
   * Storage backend in use: zfs 0.7.12-1ubuntu5

# Issue description

The new version tries to mount zfs bookmarks and therefore fails with the attached error message. Couldn't restart lxd until I removed all bookmarks.
These bookmarks are used for zfs replication.
The developer of zrepl seems to have found the cause of this: https://github.com/lxc/lxd/pull/6766/files#r370989009

# Steps to reproduce

 1. Create a bookmark (containing "#") of a container or image, or use software zrepl for replication
 2. Restart lxd
 3. lxd won't start

# Logs
```
Jan 26 09:35:04 localhost lxd.daemon[14278]: t=2020-01-26T09:35:04+0100 lvl=eror msg="Failed to start the daemon: Failed to run: zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/zfs_lxd/containers/broadcast#zrepl_CURSOR_G_fe5d6a56365cebc2_J_pull_source canmount=noauto rpool/lxd/containers/broadcast#zrepl_CURSOR_G_fe5d6a56365cebc2_J_pull_source: cannot open 'rpool/lxd/containers/broadcast#zrepl_CURSOR_G_fe5d6a56365cebc2_J_pull_source': bookmark delimiter '#' is not expected here"
Jan 26 09:35:04 localhost lxd.daemon[14278]: Error: Failed to run: zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/zfs_lxd/containers/broadcast#zrepl_CURSOR_G_fe5d6a56365cebc2_J_pull_source canmount=noauto rpool/lxd/containers/broadcast#zrepl_CURSOR_G_fe5d6a56365cebc2_J_pull_source: cannot open 'rpool/lxd/containers/broadcast#zrepl_CURSOR_G_fe5d6a56365cebc2_J_pull_source': bookmark delimiter '#' is not expected here
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Wrote a fix which skips those bookmarks in the zfs driver. Will cherry-pick to candidate and stable snap once CI is happy and it's been reviewed.
