### ISSUE TITLE
LXD isn't running

### ISSUE THREAD

**Issue by jdupl** [lxc/lxd#678]
On a 15.04 box, I installed LXD via the main repo.

I enabled and started LXD with systemctl, but it kept saying 'LXD isn't running.'.
LXD was running, but LXC was not started.

Perhaps the message could be changed for easier debugging.

**Comment by tych0** [comment]
On Tue, May 19, 2015 at 10:54:51AM -0700, Justin Duplessis wrote:
> On a 15.04 box, I installed LXD via the main repo.
> 
> I enabled and started LXD with systemctl, but it kept saying 'LXD isn't running.'.
> LXD was running, but LXC was not started.

There are some known problems with the systemd init scripts that I
think are fixed in the packaging. However, I'm confused by the last
sentence here, what do you mean by "LXC was not started"?

**Comment by jdupl** [comment]
I started LXD with systemctl, but I still had the same message. I ran to start LXC by itself too with `systemctl start lxc`.

**Comment by walkerandco** [comment]
@tych0 Let me be clear on behalf of @jdupl . The error message "LXD isn't running" is a typo which should read "LXC is not running", in other words the LXC subsystem is not running as a service. Personally, I think @jdupl was perfectly clear about the error and so your query seems somewhat obstructive (which is extremely annoying).

I can confirm the same bug. Do you want me to fix it or can you manage by yourself?

**Comment by jdupl** [comment]
This message might be displayed if lxd or lxc is not running.

Le 2015-05-25 9:32 AM, "walkerandco" <notifications@github.com> a écrit :
>
> @tych0 Let me be clear on behalf of @jdupl . The error message "LXD isn't
running" is a typo which should read "LXC is not running", in other words
the LXC subsystem is not running as a service. Personally, I think @jdupl
was perfectly clear about the error and so your query seems somewhat
obstructive (which is extremely annoying).
>
> I can confirm the same bug. Do you want me to fix it or can you manage by
yourself?

**Comment by walkerandco** [comment]
Quite likely, it could be an ambiguous error message. Or, it could be (and perhaps more likely is) a typo for a contextual error message specific to lxc.

**Comment by tych0** [comment]
On Mon, May 25, 2015 at 06:32:19AM -0700, walkerandco wrote:
> @tych0 Let me be clear on behalf of @jdupl . The error message "LXD isn't running" is a typo which should read "LXC is not running", in other words the LXC subsystem is not running as a service. Personally, I think @jdupl was perfectly clear about the error and so your query seems somewhat obstructive (which is extremely annoying).
> 
> I can confirm the same bug. Do you want me to fix it or can you manage by yourself?

Sure, patches are more than welcome. Thanks!

**Comment by stgraber** [comment]
I believe we've now had the command line reworked a bit to offer a clearer error. Closing this.
