### ISSUE TITLE
Error 404 on POST /1.0/instances 

### ISSUE THREAD

**Issue by NateKomodo** [lxc/lxd#6785]
#6 Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu Xenial
 * The output of "lxc info":
driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-74-generic
  server: lxd
  server_pid: 1581
  server_version: 3.0.3
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.6
  server_clustered: false

# Issue description

Sending a post request to /1.0/instances is resulting in a 404.

# Steps to reproduce
Setup LXD and run this code:
```
RestClient client;
        public API()
        {
            client = new RestClient("https://127.0.0.1:40/");

            ServicePointManager.Expect100Continue = false;
            ServicePointManager.DefaultConnectionLimit = 9999;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3;
            ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;

            var certFile = "lxd.pfx";
            X509Certificate2 cert = new X509Certificate2(certFile, "(password)");
            client.ClientCertificates = new X509CertificateCollection() { cert };
            client.Proxy = new WebProxy();
        }

        public bool CreateContainer(string name)
        {
            var restrequest = new RestRequest("1.0/instances", Method.POST);
            string req = RequestsTemplates.ContainerCreateRequest(name);
            Logging.Log("Sending" + req, "API", LogLevel.INFO);
            restrequest.AddJsonBody(req);
            IRestResponse response = client.Execute(restrequest);
            Logging.Log(response.StatusCode + " " + response.Content, "API", LogLevel.INFO);
            return response.StatusCode == HttpStatusCode.Continue;
        }
```
Note other trusted endpoints work with this configuration

The code returns ` NotFound {"error":"not found","error_code":404,"type":"error"}`

**Comment by NateKomodo** [comment]
Solved, the endpoint is /1.0/containers, not /1.0/instances. rest-api.md is out of date.

**Comment by tomponline** [comment]
@NateKomodo the `/1.0/instances` route was added after 3.0.3 and is the preferred route on newer versions of LXD, but you can see the 3.0.3 docs here https://github.com/lxc/lxd/blob/lxd-3.0.3/doc/rest-api.md

**Comment by NateKomodo** [comment]
@tomponline so the version from apt-get is nt the latest?

**Comment by tomponline** [comment]
@tomponline that is correct, the apt version is a long-term-support (LTS) track, whereas the latest versions are packaged as a snap for ubuntu and other distributions.

See https://linuxcontainers.org/lxd/getting-started-cli/

Also see further info about this on the latest release post: https://discuss.linuxcontainers.org/t/lxd-3-19-has-been-released/6529/18?u=tomp
