### ISSUE TITLE
Add ability to push images

### ISSUE THREAD

**Issue by randombenj** [lxc/lxd#6805]
When hosting something like [lxdhub](https://github.com/Roche/lxdhub) or any other generic lxd remote where images could be consumed from, it would be nice to be able to push images directly from your host.

There is currently `lxc image copy local:IMAGE remote:` however, if you are not in the same network this fails because the remote can't access my local machine:

```
 Error: Failed remote image download:
 - https://XXX:8443: Get https://XXX:8443/1.0: Unable to connect to: MY_HOST:8443
```

This is because lxd sends a `pull` request to my local machine:

```
DBUG[01-29|13:50:50] Sending request to LXD                   method=POST url=https://XXX:8443/1.0/images etag=
DBUG[01-29|13:50:50] 
	{
		"auto_update": false,
		"properties": null,
		"public": false,
		"filename": "",
		"source": {
			"alias": "",
			"certificate": "...",
			"protocol": "lxd",
			"server": "https://MY_HOST:8443",
			"mode": "pull",
			"type": "image",
			"url": "",
			"name": "",
			"fingerprint": "...",
			"secret": "..."
		},
		"compression_algorithm": "",
		"aliases": null
	}
```

There is one workaround for this, you can export and import the image to the remote because this uses the [images post api](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#10images):

```sh
lxc image export IMAGE imgage.tar.xz
lxc image import image.tar.xz remote:
```

So what would be nice is something like which internally just uses the [images post api](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#10images) and really pushes the image instead of pulling from the remote:

```sh
lxc image push IMAGE remote:
```

If you think this idea would be usefull I would be happy to participate when time allows it, but maybe some help is needed :)

**Comment by stgraber** [comment]
Yeah, I've been meaning to do this for a while.
The CLI would still be `lxc image copy` but similar to `lxc copy` would support a `--mode=push` option.

As for APIs, if you are to implement this, I suspect you'd need:
 - Change to POST /1.0/images to obtain a receive token (token operation). This is needed as the source server will not have credentials to connect to the target, so a one time token needs to be generated by the CLI and provided to the source server.
 - Changes to POST /1.0/images to accept the receive token during image import (extra http header).
 - Addition of POST /1.0/images/FINGERPRINT/export which would take a JSON struct similar to what we have in instance migration, this would include the target URL, certificate and the token.

The CLI would then hit /1.0/images of the target to get the token, then hit the source at /1.0/images/FINGERPRINT/export giving it the target url, certificate and token. The source server would then post to /1.0/images of the target server using the image data + the token. The target server will import the image and invalidate the token. Lastly the CLI can fixup things like aliases and properties.

**Comment by randombenj** [comment]
Thanks for the fast answer! Will see what I can do :smiley:

**Comment by randombenj** [comment]
One additional question, after looking at the sourcecode, why do you want this to be part of the api (with the push mode)? Isn't this functionality already given by the api with the `POST /1.0/images`.
Wouldn't pushing to the remote `POST /1.0/images` from the CLI be enought to achieve this or am I missing something here?

**Comment by stgraber** [comment]
Having the CLI do it is certainly something we should allow. That's what we call relay mode.

The difference between push and relay mode is that in the case of relay mode all traffic must go through the client.

If you're managing remote servers, you may not like that very much.
