### ISSUE TITLE
Backups response doesn't use instances

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#6824]
When calling the endpoint `/instances/`  the returned names are like `/1.0/instances/INSTANCE_NAME` when calling `/instances/INSTANCE_NAME/backups/` the returned names are like `/1.0/containers/INSTANCE_NAME/backups/test` instead of `/1.0/instances/INSTANCE_NAME/backups/test`

**Comment by stgraber** [comment]
I believe I fixed this yesterday:

https://github.com/lxc/lxd/commit/4e34b0870004466260ba4abecdf3ed75f27e8932

**Comment by stgraber** [comment]
This will be in the snap package that we'll promote to stable tomorrow.

**Comment by turtle0x1** [comment]
Awesome ty 😊
