### ISSUE TITLE
lxd 3.20 fails to start with zfs storage - Alpine Linux

### ISSUE THREAD

**Issue by atersurs** [lxc/lxd#6830]
# Required information
 * Distribution: Alpine Linux
 * Distribution version: 3.11 / lxd packages from edge-testing
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.12-1-lts
   * LXC version: 3.20
   * LXD version: 3.20
   * Storage backend in use: zfs

# Issue description
Containers on zfs fail to start due to errors enumerating zfs.

# Steps to reproduce

 1. setup containers on zfs in a previous version before storage driver changes
 2. upgrade to 3.20
 3. start service - containers fail to start

# log output

EROR[02-03|03:23:22] Failed to start the daemon: Failed to run: zfs get name -o name -H -r lxd: cannot open '-o': dataset does not exist
cannot open 'name': dataset does not exist
cannot open '-H': dataset does not exist
cannot open '-r': dataset does not exist

# fix is to re-order arguments to zfs:
```go
--- a/lxd/storage/drivers/driver_zfs_utils.go
+++ b/lxd/storage/drivers/driver_zfs_utils.go
@@ -82,7 +82,7 @@
 }

 func (d *zfs) getClones(dataset string) ([]string, error) {
-       out, err := shared.RunCommand("zfs", "get", "-H", "-p", "-o", "value", "-r", "clones", dataset)
+       out, err := shared.RunCommand("zfs", "get", "-H", "-p", "-r", "-o", "value", "clones", dataset)
        if err != nil {
                return nil, err
        }
@@ -102,7 +102,7 @@
 }

 func (d *zfs) getDatasets(dataset string) ([]string, error) {
-       out, err := shared.RunCommand("zfs", "get", "name", "-o", "name", "-H", "-r", dataset)
+       out, err := shared.RunCommand("zfs", "get", "-H", "-r", "-o", "name", "name", dataset)
        if err != nil {
                return nil, err
        }
```

**Comment by stgraber** [comment]
Thanks, sent a branch with your fix.
