### ISSUE TITLE
How do I change default mount options for '/'?

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#6847]
How do I change default mount options for '/'?

Can't seem to get raw.lxc working.

**Comment by stgraber** [comment]
Setting `lxc.rootfs.options` through `raw.lxc` will work but note that the container root mount is effectively just a bind-mount, so the amount of options that the kernel will accept are extremely limited and everything else will get discarded.

Things that should work are `ro`, propagation options (`private`, `slave`, `shared`, ...), `noexec`, `nosuid`, `bind`, `rbind`, ...
But anything that's a superblock option will be discarded by the kernel.

**Comment by s3rj1k** [comment]
@stgraber What about `noacl`, `noxattr`?

Should I use those on parent mount instead of per-container config?

Are there any security implications (Apparmor ?) for disabling acl and xattr in container?

**Comment by stgraber** [comment]
Those are superblock options indeed and also may not be present on all filesystems.
So yes, you'd need to set them on the parent mount and they will apply to all containers.

We don't rely on those for security in any way, so you won't get in trouble with apparmor or the like.

**Comment by s3rj1k** [comment]
@stgraber Thanks.
