### ISSUE TITLE
Failed to add second ipvlan interface with IP.

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxd#6852]
* Distribution: Ubuntu
 * Distribution version: 19.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.3.0-29-generic
   * LXC version: 3.20
   * LXD version: 3.20
   * Storage backend in use: dir

# Issue description

Adding second ipvlan nic device with setting IP adress causing conteiner start error.
It seems, that lxc trying to add second default gateway.

If add ipvlan nic device without setting IP - container starts normally.

# Steps to reproduce
```
lxc init ubuntu:18.04 test
sysctl -w net.ipv4.conf.ens160.forwarding=1
sysctl -w net.ipv4.conf.ens192.forwarding=1
lxc config device add test eth0 nic name=eth0 nictype=ipvlan parent=ens160 ipv4.address="192.168.0.2"
lxc config device add test eth1 nic name=eth1 nictype=ipvlan parent=ens192 ipv4.address="192.168.0.3"
lxc start test
```
# Information to attach

`lxc info --show-log test` output:
 
Name: test
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/02/07 15:49 UTC
Status: Stopped
Type: container
Profiles: default

Log:

lxc test 20200207155001.952 WARN     cgfsng - cgroups/cgfsng.c:chowmod:1525 - No such file or directory - Failed to chown(/sys/fs/cgroup/unified//lxc.payload/test/memory.oom.group, 1000000000, 0)
lxc test 20200207155002.258 ERROR    network - network.c:lxc_setup_netdev_in_child_namespaces:3789 - File exists - Failed to setup ipv4 gateway to network device "eth1"
lxc test 20200207155002.258 ERROR    network - network.c:lxc_setup_network_in_child_namespaces:3892 - Failed to setup netdev
lxc test 20200207155002.258 ERROR    conf - conf.c:lxc_setup:3570 - Failed to setup network
lxc test 20200207155002.258 ERROR    start - start.c:do_start:1321 - Failed to setup container "test"
lxc test 20200207155002.264 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
lxc test 20200207155002.327 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:873 - Received container state "ABORTING" instead of "RUNNING"
lxc test 20200207155002.336 ERROR    start - start.c:lxc_abort:1122 - Function not implemented - Failed to send SIGKILL to 3561
lxc test 20200207155002.336 ERROR    start - start.c:__lxc_start:2039 - Failed to spawn container "test"
lxc 20200207155002.999 WARN     commands - commands.c:lxc_cmd_rsp_recv:135 - Connection reset by peer - Failed to receive response for command "get_state"

**Comment by tomponline** [comment]
@kautMaks this is because `ipvlan` type NICs add a default device route to the container pointing to the device's interface, so adding two will try and add 2 default gateways to different interfaces.

What is the use case you are trying to achieve here? Are you trying to connect the container to two different physical networks, would one of these need to be the default gateway only?

**Comment by tomponline** [comment]
@kautMaks I notice in your example that the 2 IPs also appear to be in the same subnet but will be connected to different parent interfaces, is this intentional?

**Comment by kautMaks** [comment]
@tomponline Those IP's are only example. Problem reproduces with any IP's/networks. I will use IP's from different networks (parent interfaces are vlans).

I am trying to use different networks inside container with advanced policy routing.
It is necessary to add the ability not to create a default gateway for some interfaces, or to make sure that it does not break container start.

**Comment by tomponline** [comment]
@kautMaks yes indeed, @stgraber do you have any comment on naming for such an option in the NIC device config, perhaps `gateway=none` with the default being `gateway=dev`?

I imagine this is something that may also be relevant to the `routed` device type, which similarly adds default gateways.

**Comment by kautMaks** [comment]
@tomponline  sounds good, thank you :)

**Comment by stgraber** [comment]
@tomponline `ipv4.gateway` and `ipv6.gateway` supporting `none` or `auto` (default)?

**Comment by tomponline** [comment]
@stgraber yep that would work, then `auto` will map to the correct type of gateway being added for `ipvlan` and `router` NICs in liblxc (the former having gateway `dev` and the latter having link-local addresses set).

For `none` both types will just have no gateways set and its up to the container's internal config to define one as needed.

**Comment by tomponline** [comment]
@kautMaks btw, did you know you can add multiple addresses to a single `ipvlan` NIC?

i.e

```
lxc config device add test eth0 nic name=eth0 nictype=ipvlan parent=ens160 ipv4.address="192.168.0.2, 192.168.0.3"
```
