### ISSUE TITLE
Disable O_DIRECT?

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#6855]
Is there any possible way of blacklisting `O_DIRECT` flag when backing file-system is `ext4` and storage driver is `Dir`.

Use case would be to force processes inside container to always use kernel file cache (thinking `bcache` here), without the ability to bypass it.

**Comment by stgraber** [comment]
Maybe there's an ext4 mount option to turn this off?
Otherwise you'd probably need a custom seccomp filter or something.

**Comment by s3rj1k** [comment]
@s3rj1k Did not find any mount option to disable `O_DIRECT` :(.

Can I change seccomp filter without recompiling LXD?

**Comment by stgraber** [comment]
Yes, we have `raw.seccomp` that could be used to add a complex seccomp filter.

**Comment by s3rj1k** [comment]
Hmm, as per `https://www.kernel.org/doc/Documentation/filesystems/ext4.txt`
you can disable `O_DIRECT` by forcing `data=journal `

**Comment by stgraber** [comment]
Closing as you seem to have found a way to do it and this is all rather outside of LXD's control anyway.
