### ISSUE TITLE
We could allow connecting to unix sockets on macOS

### ISSUE THREAD

**Issue by XeCycle** [lxc/lxd#6858]
# Required information

 * Distribution: homebrew package on macOS Catalina
 * Distribution version: 3.20
 * The output of "lxc info" or if that fails:
```
# some ssh command...
~ $ export LXD_SOCKET=$HOME/lxd.socket
~ $ lxc info
This client hasn't been configured to use a remote LXD server yet.
As your platform can't run native Linux instances, you must connect to a remote LXD server.

If you already added a remote server, make it the default with "lxc remote switch NAME".
To easily setup a local LXD server in a virtual machine, consider using: https://multipass.run
1 ~ $ lxc --force-local info
This client hasn't been configured to use a remote LXD server yet.
As your platform can't run native Linux instances, you must connect to a remote LXD server.

If you already added a remote server, make it the default with "lxc remote switch NAME".
To easily setup a local LXD server in a virtual machine, consider using: https://multipass.run
```

# Issue description

SSH can be used to forward unix sockets over network, and connecting via forwarded unix sockets already works when `lxc` is running on Linux.  Apparently macOS can do the same; do we want to relax this requirement?

**Comment by stgraber** [comment]
Well, even with that, you don't have an actual local LXD.

Does:
    lxc remote add blah unix:///path/to/socket
    lxc remote switch blah

Work on macOS?

**Comment by stgraber** [comment]
If it does, then I believe our behavior is correct and does support one using a redirected unix socket.

**Comment by XeCycle** [comment]
Thanks, that works.  So is there something special with `local:`?  IMHO that's a bit confusing, we'd better add some docs/hints on this use case.

**Comment by stgraber** [comment]
`local` is a static remote, same as `ubuntu` or `ubuntu-daily`.
That means it is guaranteed to be present on all LXD installations and cannot be altered by the user.
Its address is `unix://` which uses the default socket path considering things like the LXD_DIR and LXD_SOCKET environment variables.

So this can never be altered even if the local system doesn't run LXD. What can be altered is the default remote, which is what the LXD client uses as its target server. Out of the box this is set to `local` but `lxc remote switch` lets you change this to point to whatever you want.
On systems that don't run LXD locally, you usually want to use that to point to your remote LXD server.


Closing as behavior matches what we expect and adding a unix remote works fine.
