### ISSUE TITLE
Stopping vivid guest fails

### ISSUE THREAD

**Issue by rsommer** [lxc/lxd#687]
Stopping an ubuntu vivid guest running with lxc-1.1.2/lxd-0.9 fails. The host system is ubuntu 14.04.2.

Steps to reproduce:
```
lxd-images import lxc ubuntu vivid amd64 --alias ubuntu/vivid
lxc launch ubuntu/vivid test
lxc stop test
```
-> hangs

This seems to be connected to the switch to systemd. If i do
```
apt-get install upstart-sysv
```
inside the container, kill it manually and restart it, i can use `lxc stop test` without a problem.

**Comment by stgraber** [comment]
Yep, it's a known issue and a systemd bug in Ubuntu (systemd ignores SIGPWR).

**Comment by stgraber** [comment]
Marking blocked as it's not a LXD bug but something we want to track.

**Comment by stgraber** [comment]
This was fixed in a SRU.
