### ISSUE TITLE
GET /1.0/instances should return instance type end points

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#6903]
LXD 3.21

GET /1.0/containers and GET /1.0/virtual-machines returns the containers or virtual-machines at their instance type end points. GET /1.0/instances returns all instance types on the /1.0/instances end point. The caller has no way of knowing the instance type without pulling all instance information. If GET /1.0/instances would return all instances on their instance type end point the caller would know the type without having to make additional calls.

This would allow PYLXD to return the correct object type when calling client.instances.all()

**Comment by stgraber** [comment]
`/1.0/containers` and `/1.0/virtual-machines` are backward compatibility URLs and should in general not be exposed to any user from the new endpoint (`/instances`), so I don't see us changing that.

What you should be doing in your case is use `/1.0/instances?recursion=1` which will then get you most of the details you care about for all instances (without being as intrusive as `recursion=2`) which includes the type of every entry.

**Comment by stgraber** [comment]
Ah and node that we also have API level filtering which you can use for this.

Passing "?filter=type eq virtual-machine" will filter the list for you to only include virtual-machines.

```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ curl -G --unix-socket "/var/lib/lxd/unix.socket" "lxd/1.0/instances" --data-urlencode "filter=type eq virtual-machine" | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   150  100   150    0     0  15000      0 --:--:-- --:--:-- --:--:-- 15000
{
  "type": "sync",
  "status": "Success",
  "status_code": 200,
  "operation": "",
  "error_code": 0,
  "error": "",
  "metadata": [
    "/1.0/instances/win10",
    "/1.0/instances/v1"
  ]
}
```

https://linuxcontainers.org/lxd/docs/master/rest-api#recursion has both recursion and filtering mentioned.

**Comment by ltrager** [comment]
The use case I'm thinking of is for pylxd. [I just added support for both the instances and virtual-machines endpoints.](https://github.com/lxc/pylxd/pull/387) When client.instances.all() is called both containers and virtual-machines are returned but the [data isn't loaded until needed](https://github.com/lxc/pylxd/blob/master/pylxd/models/container.py#L243). If the containers or virtual-machines end-points are given instead of instances pylxd can return Container or VirtualMachine objects instead of Instance objects.

**Comment by stgraber** [comment]
Why does pylxd have Container and VirtualMachine objects?

In the Go client, we have a single struct type, Instance which has a Type field associated to it if you want to know if you're dealing with a container or VM.

As the API for both of them is identical, duplicating the types seems odd.
