### ISSUE TITLE
"Error: EOF" when using "lxc exec ...."

### ISSUE THREAD

**Issue by 66hades** [lxc/lxd#6910]
# Issue description

Hello, github newbie here!

 I'm getting the same behavior as issue [#5188](https://github.com/lxc/lxd/issues/5188). It occurs some time after the container has been running (after several hours?).

I am using projects, the container in question is not in the default project.

Running 
`lxc exec <container> -- /bin/bash
`
returns 
'Error: EOF

This also occurs when using --project flag to execute in the non-current project.

For this container's use case, I would prefer not to restart the instance to do exec commands, so the restart container fix does not work for me. Restarting the container does fix the error temporarily, it does come back after some time though.

# Steps to reproduce

 1. Create lxd project <project>
 2. Create container <container> inside that project
 3. Wait some amount of time (<=8 hours, tried at night, worked, tried in morning, errored).
 4. execute 'lxc exec <container> -- /bin/bash 
(other lxc exec commands also fail)

# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
`uname -a
' : Linux borderbound3 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

 * The output of "lxc info" or if that fails:
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.0.140:8443
  - 10.177.89.1:8443
  - 192.168.122.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICFjCCAZygAwIBAgIRALm5CN9+hyWR6rny6B3ZhLkwCgYIKoZIzj0EAwMwOjEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEaMBgGA1UEAwwRcm9vdEBib3Jk
    ZXJib3VuZDMwHhcNMjAwMjA2MjE1MjQ1WhcNMzAwMjAzMjE1MjQ1WjA6MRwwGgYD
    VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRowGAYDVQQDDBFyb290QGJvcmRlcmJv
    dW5kMzB2MBAGByqGSM49AgEGBSuBBAAiA2IABHbtkzLoxV9GrxlkeqrGSn7pvQHC
    OoGe2X+y3+a7arli8HvgY2iskSKZGv2d7Yc2pydYs67TzLwBo6A1Yf2+lq5t0Cd8
    8KST+3KUdy+uSQCXYdsdWSXHRwnb8UZ9yxRwXqNmMGQwDgYDVR0PAQH/BAQDAgWg
    MBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwLwYDVR0RBCgwJoIM
    Ym9yZGVyYm91bmQzhwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMD
    A2gAMGUCMCBn6vvsEbJvvD5MLQv8O2v+sNufj8MGVgQb6pEFpoxcMBGGY6iMz34W
    6rs2BP0LigIxAJMCORmlveSWWHGtdzjNOsO2JwopnLv+cpbUs8nUyCfRqHkMW1xv
    0Q0ZO5iuJVHnoQ==
    -----END CERTIFICATE-----
  certificate_fingerprint: caba0295930e718cabc54f2a8751ec98325af8e849c561ccc8015e7cbcebd03e
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.0.0-37-generic
  lxc_features:
    cgroup2: "false"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  project: client-minecraft
  server: lxd
  server_clustered: false
  server_name: borderbound3
  server_pid: 11576
  server_version: "3.21"
  storage: zfs
  storage_version: 0.7.12-1ubuntu5

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
(log is empty)
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/02/16 03:22 UTC
Status: Running
Type: container
Profiles: default
Pid: 22572
Ips:
  eth0: inet    10.177.89.108   veth358d0327
  eth0: inet6   fe80::216:3eff:feaa:abd2        veth358d0327
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 100
  Disk usage:
    root: 332.97MB
  CPU usage:
    CPU usage (in seconds): 40805
  Memory usage:
    Memory (current): 3.22GB
  Network usage:
    lo:
      Bytes received: 73.66MB
      Bytes sent: 73.66MB
      Packets received: 543277
      Packets sent: 543277
    eth0:
      Bytes received: 81.45MB
      Bytes sent: 1.56MB
      Packets received: 37081
      Packets sent: 21979

 - [ ] Container configuration (`lxc config show NAME --expanded`)

architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20200129.1)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20200129.1"
  image.type: squashfs
  image.version: "18.04"
  volatile.base_image: 9e7158fc0683d41f7f692ce8b17598716d7eee925c6a593432df59488bf4131f
  volatile.eth0.host_name: veth358d0327
  volatile.eth0.hwaddr: 00:16:3e:aa:ab:d2
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  myport13579:
    connect: tcp:127.0.0.1:13579
    listen: tcp:192.168.0.140:13579
    type: proxy
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

(I'm a little new to this, I think this is the relevant part of the log?)
t=2020-02-20T10:52:53-0500 lvl=warn msg="Detected poll(POLLNVAL) event."
t=2020-02-20T11:11:23-0500 lvl=eror msg="Failed to retrieve PID of executing child process: EOF"
t=2020-02-20T11:11:47-0500 lvl=eror msg="Failed to retrieve PID of executing child process: EOF"
t=2020-02-20T11:14:00-0500 lvl=warn msg="Detected poll(POLLNVAL) event: exiting."
t=2020-02-20T11:14:59-0500 lvl=info msg="Pruning expired container backups"
t=2020-02-20T11:14:59-0500 lvl=info msg="Done pruning expired container backups"
t=2020-02-20T11:15:15-0500 lvl=eror msg="Failed to retrieve PID of executing child process: EOF"
t=2020-02-20T11:19:01-0500 lvl=eror msg="Failed to retrieve PID of executing child process: EOF"
t=2020-02-20T11:33:42-0500 lvl=warn msg="Detected poll(POLLNVAL) event."
t=2020-02-20T11:35:12-0500 lvl=warn msg="Detected poll(POLLNVAL) event."
t=2020-02-20T11:36:51-0500 lvl=eror msg="Failed to retrieve PID of executing child process: EOF"
t=2020-02-20T11:36:54-0500 lvl=warn msg="Detected poll(POLLNVAL) event: exiting."
t=2020-02-20T11:42:26-0500 lvl=eror msg="Failed to retrieve PID of executing child process: EOF"
t=2020-02-20T11:42:33-0500 lvl=warn msg="Detected poll(POLLNVAL) event: exiting."

 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
@66hades does restarting LXD itself help (`systemctl reload snap.lxd.daemon`)?

If not, can you show:
 - /var/snap/lxd/common/lxd/logs/PROJECT_CONTAINER/lxc.conf
 - /var/snap/lxd/common/lxd/logs/PROJECT_CONTAINER/lxc.log

And do you have that same container name in multiple projects?

**Comment by 66hades** [comment]
Restarting LXD did not fix the issue.
`gardener6@borderbound3:/var/snap/lxd/common/lxd/containers$ systemctl reload snap.lxd.daemon
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to reload 'snap.lxd.daemon.service'.
Multiple identities can be used for authentication:
 1.  gardener6,,, (gardener6)
 2.  Michael Lohrer,,, (mflohrer)
Choose identity to authenticate as (1-2): 1
Password:
==== AUTHENTICATION COMPLETE ===
gardener6@borderbound3:/var/snap/lxd/common/lxd/containers$ lxc exec mc-server-1dot15 -- /bin/bash
Error: EOF
`

All project and container names are unique.

`root@borderbound3:/var/snap/lxd/common/lxd/logs/client-minecraft_mc-server-1dot15# ll
total 16
drwxr-xr-x 2 root root 4096 Feb 20 14:24 ./
drwx------ 5 root root 4096 Feb 20 14:09 ../
-rw-r--r-- 1 root root   89 Feb 20 14:18 forkexec.log
-rw-r----- 1 root root  511 Feb 20 14:24 lxc.log
`

lxc.log file was empty
lxc.conf file did not exist
there was a file "forkexec.log" but opening it will less results in 
`Error: Error opening startup config file: "loading config file for the container failed"
`

**Comment by stgraber** [comment]
Ok, so the missing `lxc.conf` is the issue, though the question is why is this missing :)

**Comment by 66hades** [comment]
Does it have to do with how projects react with pruning expired container backups or updating images? These are the entries from the log between when it worked and when it didn't work. It updated images only once, but pruned backups several times.

`t=2020-02-20T05:14:59-0500 lvl=info msg="Pruning expired container backups"`
`t=2020-02-20T05:14:59-0500 lvl=info msg="Done pruning expired container backups"`
`t=2020-02-20T06:14:59-0500 lvl=info msg="Updating images"`
`t=2020-02-20T06:14:59-0500 lvl=info msg="Done updating images"`

**Comment by 66hades** [comment]
The container that was restarted, and lxc exec command works on has this folder structure. Both containers have proxy devices.

`root@borderbound3:/var/snap/lxd/common/lxd/logs/client-rumblepack_OBS-rumblepack# ll`
`total 84`
`drwxr-xr-x 2 root root  4096 Feb 20 10:44 ./`
`drwx------ 5 root root  4096 Feb 20 15:11 ../`
`-rw------- 1 root root 51357 Feb 20 10:46 console.log`
`-rw-r--r-- 1 root root    89 Feb 20 01:15 forkexec.log`
`-rw-r--r-- 1 root root     0 Feb 20 10:44 forkstart.log`
`-rw-r----- 1 root root  2219 Feb 20 10:44 lxc.conf`
`-rw-r----- 1 root root   252 Feb 20 10:44 lxc.log`
`-rw-r----- 1 root root   252 Feb 20 10:42 lxc.log.old`
`-rw------- 1 root root   800 Feb 20 02:04 proxy.proxyport13578.log`
`-rw------- 1 root root   206 Feb 20 10:44 proxy.proxyport22.log`

**Comment by stgraber** [comment]
Ok, can you try copying the `lxc.conf` from the working one to the non-working one and just replace all mention of the name in there by the correct one?

That should get you back online.

**Comment by 66hades** [comment]
> Ok, can you try copying the `lxc.conf` from the working one to the non-working one and just replace all mention of the name in there by the correct one?
> 
> That should get you back online.

@stgraber I've got some profiles set up, and browsing through the .conf file it appears that there are some references to them. Would copying the lxc.conf file from one container to another that has different profiles set up cause conflicts?

**Comment by stgraber** [comment]
For `exec` purpose, relatively little of that file is likely to be used, so it not being perfect should be fine.

**Comment by 66hades** [comment]
> For `exec` purpose, relatively little of that file is likely to be used, so it not being perfect should be fine.

Understood, thanks!
