### ISSUE TITLE
adding LVM storage... no matter what..."Error: Volume group "extravg" is not empty"

### ISSUE THREAD

**Issue by tazmo** [lxc/lxd#6916]
Hi-

I am trying to add lvm storage to lxd using an existing VG but am not able to.

Running Ubuntu 18.04.4... lxd from snap -version 3.21. According to this[1], I should be able to but no matter what, it does not work.

I have read all four ""Error: Volume group "extravg" is not empty" threads found when posting this.

root@dozer:~# vgs
  VG         #PV #LV #SN Attr   VSize   VFree 
  extravg      1   3   0 wz--n-  <1.82t  1.33t
  kubuntu-vg   1   2   0 wz--n- 237.97g 24.00m 

root@dozer:~# lvs
  LV          VG         Attr       LSize    Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  LXDThinPool extravg    twi-a-tz--  100.00g             0.00   10.43                           
  homes       extravg    -wi-ao----  200.00g                                                    
  vms         extravg    -wi-ao----  200.00g                                                    
  root        kubuntu-vg -wi-ao---- <237.00g                                                    
  swap_1      kubuntu-vg -wi-ao----  976.00m    

root@dozer:~# lxc storage list
+------+-------------+--------+--------+---------+
| NAME | DESCRIPTION | DRIVER | SOURCE | USED BY |
+------+-------------+--------+--------+---------+

Commands and results tried:

root@dozer:~#  lxc storage create default lvm lvm.thinpool_name=LXDThinPool source=extravg
Error: Volume group "extravg" is not empty

root@dozer:~# lxc storage create default lvm source=extravg lvm.thinpool_name=LXDThinPool 
Error: Volume group "extravg" is not empty

From the docs:
root@dozer:~#  lxc storage create default lvm source=extravg
Error: Volume group "extravg" is not empty

I then did a:
root@dozer:~# lvremove extravg/LXDThinPool 
Do you really want to remove and DISCARD active logical volume extravg/LXDThinPool? [y/n]: y
  Logical volume "LXDThinPool" successfully removed

And repeated the three above -> same results.

It baffles me why this is so complicated but I must be missing something.

Attached is -debug version of one of the above.

[lxc-create-lvm-debug.txt](https://github.com/lxc/lxd/files/4238421/lxc-create-lvm-debug.txt)

Was this feature removed? Can we no longer add existing VGs? I know that VG is not empty... I am trying to add it!

Please help me with the obvious...

Bob
 
[1] Ref: https://github.com/lxc/lxd/issues/3456

**Comment by stgraber** [comment]
Correct, LXD 3.21 properly enforces our storage rules to not allow using a storage pool that's got a single namespace and where items already exist. The same protection is present for ZFS and Ceph, LVM just had a bug that made it unenforced up until 3.20 or so.

@tomponline Added a new config option to bypass that test, the result of which is in current git master and will be in LXD 3.22.

If you don't mind living on the edge for a while, refreshing the snap with `snap refresh lxd --edge` will get you access to that new `lvm.vg.force_reuse` config key. Using this key effectively records in LXD that the VG wasn't empty when we first started using it and will make it easier for us to handle any bugreport related to conflicting LVs or the like in the future by knowing that it's such a system.

**Comment by tazmo** [comment]
Thank you for the response and (temporary) workaround. 

The reason I ask the question is the docs [here](https://lxd.readthedocs.io/en/latest/storage/#notes-and-examples) state :

" Use the existing LVM Volume Group called "my-pool" "

Unless I am miss-understanding the above, "existing" seems to infer already there....I see no other suppositions or assumptions about where the VG came from in that doc. If it's an assumption that it was a previous VG made from say lxc init, it seems misleading.

Can someone please change the docs?

Thanks,
Bob

**Comment by tomponline** [comment]
@tazmo the volume group can be there already (hence "existing" wording), but should not contain any existing volumes, it should be empty.

**Comment by tazmo** [comment]
but I tried that in my examples above with nothing in the new VG:

> I then did a:
root@dozer:~# lvremove extravg/LXDThinPool
Do you really want to remove and DISCARD active logical volume extravg/LXDThinPool? [y/n]: y
Logical volume "LXDThinPool" successfully removed

> And repeated the three above -> same results.

And it still didn't work.

So to be clear you are saying under THAT condition it should work?

**Comment by tazmo** [comment]
never mind... I did have other stuff in there.... sorry...

**Comment by tazmo** [comment]
btw - that doesn't seem very clear from the docs @tomponline
