### ISSUE TITLE
Debian rules file

### ISSUE THREAD

**Issue by Funeoz** [lxc/lxd#6940]
I'm currently trying to build a .deb package from the source code. Can the debian/rules file that can be found here (http://archive.ubuntu.com/ubuntu/pool/main/l/lxd/lxd_3.0.3-0ubuntu1~18.04.1.debian.tar.xz) be applied to the newer versions of lxd without any modifications ?

**Comment by stgraber** [comment]
It's possible, you should try it. If it doesn't then it probably wouldn't take too many changes for it to work for you.

Closing as this isn't a packaging repository and we are not publishing new LXD releases as debs (though others are obviously free to package it if they wish).
