### ISSUE TITLE
lxc remote add fails saving servercert if remote name not specified

### ISSUE THREAD

**Issue by albertodonato** [lxc/lxd#6951]
# Required information

 * Distribution: ubuntu
 * Distribution version: 19:10
 * LXD versions:
```
$ lxc version
Client version: 3.21
Server version: 3.21
```

# Issue description

When adding a remote, if a name is not specified the command continues, but then fails to save the server certificate, as the filename contains slashes:

```
$ lxc remote add https://localhost:8443
Certificate fingerprint: 10dde3acccc3f17c698ab6a89b58d90bd74af8200c8dcdd1653fedca40a18a66
ok (y/n)? y
Error: open /home/ack/snap/lxd/13522/.config/lxc/servercerts/https://localhost:8443.crt: no such file or directory
```

**Comment by stgraber** [comment]
Ah yeah, looks like we need to do some encoding around that, fun.
