### ISSUE TITLE
Ceph RBD disk usage not implemented

### ISSUE THREAD

**Issue by maran** [lxc/lxd#6953]
I noticed that Ceph RBD disk usage was [not implemented yet](https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_ceph_volumes.go#L603). Is this a case of "there was no time to implement this yet" or is there a structural reason this can't be implemented? 

I would be interested in contributing support for it if there is no reason for not having it.

**Comment by stgraber** [comment]
I can't think of a fundamental reason why it wouldn't work. Using the same pattern we're using for LVM should work just fine.

If you want to give it a shot, you need to populate `GetVolumeUsage` in `lxd/storage/drivers/driver_ceph_volumes.go` and I'd recommend basing this on the same function from `lxd/storage/drivers/driver_lvm_volumes.go`.

**Comment by maran** [comment]
Thanks for the tips. This should work fine when the system is mounted however what would we do when it's not? Also how do you normally deal with things like snapshots when calculating the size of an image. We could use `rbd du` but that would also include the size of the derived snapshots.

```
~# rbd du --pool cluster custom_bcc-maran-5002
warning: fast-diff map is not enabled for custom_bcc-maran-5002. operation may be slow.
NAME                                        PROVISIONED USED
custom_bcc-maran-5002@snapshot_snappyshotty     9.3 GiB 1.3 GiB
custom_bcc-maran-5002                           9.3 GiB  16 MiB
<TOTAL>                                         9.3 GiB 1.3 GiB
```

How do you handle this for other storage drivers?

**Comment by stgraber** [comment]
Using `rbd du` when not mounted should be fine. That's effectively what we do with LVM where we try to get it from the filesystem and if we can't, we go look at the thinpool usage.

We'd usually prefer to ignore the snapshots, though it always depends on how `used` is calculated.
If in your example above, `used` is only 16MB because of the previous snapshot owning the vast majority of the actual used space (so used is just delta since last snapshot), then we'd prefer to use the total I think.

**Comment by maran** [comment]
Just to be clear though: this would mean that getting the volume size while the system is not mounted would result in a much larger volume than when it is mounted, especially if you have tons of snapshots. This won't be too much of an issue?

**Comment by stgraber** [comment]
Correct, that's what we do for lvm so shouldn't be too much of a surprise

**Comment by maran** [comment]
Just a small follow-up question while I try to make this work;

I'm trying to figure out where in the lxc tooling the size is suppose to show up. Is it correct it should show up automatically on `lxc storage volume show ceph-dev custom/test-rbd` if it is properly implemented? The REST API docs seems to suggest as much.

**Comment by stgraber** [comment]
I believe so, yes, though only for custom volumes.

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc storage volume create default blah size=5GB
Storage volume blah created
stgraber@castiana:~$ lxc storage volume show default blah
config:
  size: 5GB
description: ""
name: blah
type: custom
used_by: []
location: none
```

**Comment by maran** [comment]
Ah but that's the configured size, not the actual current usage I want to add support for. How do I get the actual usage (GetVolumeUsage())?

**Comment by stgraber** [comment]
GetVolumeUsage right now is only used for instances. So doing `lxc info NAME` on an instance.

**Comment by maran** [comment]
```
$ lxc info 
...
Resources:
  Processes: 24
  Disk usage:
    root: 774.84MB
```

So the code does seem to show it for the root disk now, however the custom disks that I attached are not showing up. Is that suppose to show up there?

**Comment by stgraber** [comment]
nope

**Comment by maran** [comment]
Just to confirm: There is no way currently to get the usage of custom storage volumes out of the system?

**Comment by stgraber** [comment]
That's correct, yes. Other than attaching to a container and using `df -h` or something through exec :)

**Comment by maran** [comment]
Yeah that's my current solution which is fine. 

I do notice that when I stop the container it won't try to get the size of the root disk. So the code that's now in my else statement where it tries to get the usage from `rbd du` will never be ran. Is there some other way to see if that code is working ok?

**Comment by stgraber** [comment]
`lxc query /1.0/instances/NAME/state | jq .disk.root.usage`

It's just the CLI not fetching the value, but the API exposes it.

**Comment by maran** [comment]
Interestingly enough it seems to work but the usage when stopped is smaller then when it's running. 

I guess this is because there is a parent image being used for the root disk and it's showing me the usage offset against the original image when the container is not running?

**Comment by maran** [comment]
```
        "disk": {
                "root": {
                        "usage": 117440512
                }
        },
```
Which matches

```
NAME                      PROVISIONED USED
container_honest-seasnail     9.3 GiB 112 MiB
```

But when the container is running it's showing quite a bit more. 

```
/var/lib/lxd/storage-pools/ceph-dev/containers/honest-seasnail/rootfs  9.2G  737M  8.0G   9% /`

**Comment by stgraber** [comment]
Yeah, I think that's correct. The 112MB is the delta between the image it was created from and its current state. The 737MB is the used space in the container which includes the bits shared with the image.

**Comment by maran** [comment]
Ok great, I think everything is working then. Will look at the code again with fresh eyes tomorrow and send a PR.

**Comment by stgraber** [comment]
thanks!
