### ISSUE TITLE
Add 2nd routed NIC support

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#6965]
See https://github.com/lxc/lxd/issues/6852 for more info.

**Comment by s3rj1k** [comment]
@tomponline Shouldn't this be solved in `C` liblxc ?

**Comment by tomponline** [comment]
So the issue is that in LXD the gateway is automatically configured for each device by default.

This is not the case in liblxc, as the config options for defining the gateway are optional and by default none are setup:

https://github.com/lxc/lxd/blob/master/lxd/device/nic_routed.go#L218

So the proposal for this is described here: https://github.com/lxc/lxd/issues/6852#issuecomment-583507562

**Comment by s3rj1k** [comment]
@tomponline I can test patches for this feature, just in case you need confirmation.
Would be nice to see this sooner. Thanks.

**Comment by tomponline** [comment]
Also relevant to this: https://github.com/lxc/lxd/pull/7094
