### ISSUE TITLE
Can't create container on encrypted zfs

### ISSUE THREAD

**Issue by eksapetm** [lxc/lxd#6968]
Hi,

I'm installing a new Ubuntu 19.10 server which comes with zfs 0.8.1. I then installed lxd 3.0.4.

My plan was to create two storage pools: an unencrypted pool and an encrypted pool. It currently looks like this:

```
+-----------+--------------------------+--------+-----------------+---------+
|   NAME    |       DESCRIPTION        | DRIVER |     SOURCE      | USED BY |
+-----------+--------------------------+--------+-----------------+---------+
| lxd-crypt | Encrypted ZFS filesystem | zfs    | zpool/crypt/lxd | 2       |
+-----------+--------------------------+--------+-----------------+---------+
| lxd-plain | Plain ZFS filesystem     | zfs    | zpool/plain/lxd | 8       |
+-----------+--------------------------+--------+-----------------+---------+

root@newhost:~# zfs get encryption,encryptionroot zpool/crypt
NAME         PROPERTY        VALUE        SOURCE
zpool/crypt  encryption      aes-256-gcm  -
zpool/crypt  encryptionroot  zpool/crypt  -
root@newhost:~# zfs get encryption,encryptionroot zpool/plain
NAME         PROPERTY        VALUE        SOURCE
zpool/plain  encryption      off          default
zpool/plain  encryptionroot  -            -
```
I can create containers on the "plain" filesystem alright, but creating a container on the "crypt" filesystem fails:

`ubuntu@newhost:~$ lxc launch ubuntu:16.04 exim4 --profile public-crypt
Creating exim4
Error: Failed container creation: Failed to run: zfs create -o mountpoint=none -p zpool/crypt/lxd/images/996fb4df6092705d7eb91ba9ba92302ad522273d09574d24c0791f4584559bc4: cannot create 'zpool/crypt/lxd/images/996fb4df6092705d7eb91ba9ba92302ad522273d09574d24c0791f4584559bc4': encryption root's key is not loaded or provided

It seems to me I should be able to tell lxc how to create the zfs filesystem (ie. supply the encryption type, keyformat and keylocation) but I'm not sure whether this is possible.

Thanks,

Thanks,

eksa

**Comment by stgraber** [comment]
LXD itself doesn't know about ZFS encryption, proper support is discussed in #2118 

I would still expect things to behave so long as the parent dataset is properly loaded.
Does manually running `zfs key zpool/crypt/lxd` unstick things?

Alternatively, using a file data source should avoid the need for prompting for the secret.

**Comment by eksapetm** [comment]
Thank you for your quick response, Stéphane. I now realize my mistake, the key for zpool/crypt/lxd was not properly loaded:

```
root@newhost:~# zfs load-key zpool/crypt/lxd
Enter passphrase for 'zpool/crypt/lxd': 
root@newhost:~# logout
ubuntu@newhost:~$ lxc launch ubuntu:16.04 exim4 --profile public-crypt
Creating exim4
Starting exim4
```

Since I had already mounted other filesystems under zpool/crypt/lxd I was under the impression that the key was already loaded.

I apologize for opening this issue for something that was clearly my own fault.

Best,

eksa
