### ISSUE TITLE
lxd crashes when attaching a HID device

### ISSUE THREAD

**Issue by mpuzio** [lxc/lxd#6972]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 18.04.4 LTS
 * The output of "lxc info" - please see below.
Note: This is an install with lxd and lxc compiled from source tarball (https://linuxcontainers.org/downloads/lxd/lxd-3.21.tar.gz), following instructions on https://github.com/lxc/lxd/.
   * Kernel version: 5.3.0-40-generic #32~18.04.1-Ubuntu SMP
   * LXC version: 3.21
   * LXD version: 3.21
   * Storage backend in use: zfs

# Issue description
lxd daemon crashes when a HID device (e.g. a mouse) is attached to the machine, either directly or by using a KVM switch. The deamon is restarted by systemd. Containers continue running unaffected.

Report of a very similar issue, likely the same bug, against lxd 3.20 in Funtoo:
https://bugs.funtoo.org/browse/FL-6991
User comment about this bug in lxd 3.21:
https://bugs.funtoo.org/browse/FL-6991#comment-44583

# Steps to reproduce
Reproducible: always

 1. Start lxd: systemctl start lxd
 2. Plug a USB mouse into the machine
 3. Look at /var/log/syslog (see below for a log excerpt)

# Information to attach

## /var/log/syslog

Mar  3 15:55:42 bear kernel: [372215.593162] usb 1-10: new low-speed USB device number 16 using xhci_hcd
Mar  3 15:55:42 bear kernel: [372215.745467] usb 1-10: New USB device found, idVendor=046d, idProduct=c077, bcdDevice=72.00
Mar  3 15:55:42 bear kernel: [372215.745472] usb 1-10: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Mar  3 15:55:42 bear kernel: [372215.745475] usb 1-10: Product: USB Optical Mouse
Mar  3 15:55:42 bear kernel: [372215.745478] usb 1-10: Manufacturer: Logitech
Mar  3 15:55:42 bear kernel: [372215.751226] input: Logitech USB Optical Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10:1.0/0003:046D:C077.000F/input/input17
Mar  3 15:55:42 bear kernel: [372215.751363] hid-generic 0003:046D:C077.000F: input,hidraw2: USB HID v1.11 Mouse [Logitech USB Optical Mouse] on usb-0000:00:14.0-10/input0
Mar  3 15:55:42 bear lxd[15027]: panic: strings: negative Repeat count
Mar  3 15:55:42 bear lxd[15027]: goroutine 103 [running]:
Mar  3 15:55:42 bear lxd[15027]: strings.Repeat(0x134d7d7, 0x1, 0xffffffffffffffff, 0xc42045e01c, 0x4)
Mar  3 15:55:42 bear lxd[15027]: #011/usr/lib/go-1.10/src/strings/strings.go:538 +0x1c7
Mar  3 15:55:42 bear lxd[15027]: main.deviceNetlinkListener.func1.2(0xc42045e032, 0x5, 0x4, 0xc42045e01c, 0x4)
Mar  3 15:55:42 bear lxd[15027]: #011/home/maciej/lxd/lxd-3.21/_dist/src/github.com/lxc/lxd/lxd/devices.go:256 +0x4c
Mar  3 15:55:42 bear lxd[15027]: main.deviceNetlinkListener.func1(0x800, 0x1b, 0xc4201e8960, 0xc4201dc540, 0xc4201dc5a0, 0xc4201dc600)
Mar  3 15:55:42 bear lxd[15027]: #011/home/maciej/lxd/lxd-3.21/_dist/src/github.com/lxc/lxd/lxd/devices.go:266 +0x844
Mar  3 15:55:42 bear lxd[15027]: created by main.deviceNetlinkListener
Mar  3 15:55:42 bear lxd[15027]: #011/home/maciej/lxd/lxd-3.21/_dist/src/github.com/lxc/lxd/lxd/devices.go:96 +0x226
Mar  3 15:55:42 bear systemd[1]: lxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar  3 15:55:42 bear systemd[1]: lxd.service: Failed with result 'exit-code'.
Mar  3 15:55:43 bear systemd[1]: lxd.service: Service hold-off time over, scheduling restart.
Mar  3 15:55:43 bear systemd[1]: lxd.service: Scheduled restart job, restart counter is at 8.
Mar  3 15:55:43 bear systemd[1]: Stopped LXD - main daemon.
Mar  3 15:55:43 bear systemd[1]: lxd.service: Found left-over process 23654 (lxd) in control group while starting unit. Ignoring.
Mar  3 15:55:43 bear systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Mar  3 15:55:43 bear systemd[1]: Starting LXD - main daemon...
Mar  3 15:55:43 bear systemd[1]: lxd.service: Found left-over process 23654 (lxd) in control group while starting unit. Ignoring.
Mar  3 15:55:43 bear systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Mar  3 15:55:43 bear lxd[24959]: t=2020-03-03T15:55:43-0600 lvl=warn msg=" - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored"
Mar  3 15:55:43 bear systemd[1]: Started LXD - main daemon.

## /var/log/lxd/lxd.log
Nothing interesting, these messages are from the restart after the crash. No messages from the crash itself.

t=2020-03-03T15:55:43-0600 lvl=info msg="LXD 3.21 is starting in normal mode" path=/var/lib/lxd
t=2020-03-03T15:55:43-0600 lvl=info msg="Kernel uid/gid map:" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - u 0 0 4294967295" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - g 0 0 4294967295" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Configured LXD uid/gid map:" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - u 0 231072 65536" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - g 0 231072 65536" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Kernel features:" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - netnsid-based network retrieval: yes" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - uevent injection: yes" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - seccomp listener: yes" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - seccomp listener continue syscalls: yes" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - cgroup layout: hybrid" 
t=2020-03-03T15:55:43-0600 lvl=warn msg=" - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - shiftfs support: yes" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Initializing local database" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Starting /dev/lxd handler:" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - binding devlxd socket" socket=/var/lib/lxd/devlxd/sock
t=2020-03-03T15:55:43-0600 lvl=info msg="REST API daemon:" 
t=2020-03-03T15:55:43-0600 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/lib/lxd/unix.socket
t=2020-03-03T15:55:43-0600 lvl=info msg="Initializing global database" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Initializing storage pools" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Initializing networks" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Pruning leftover image files" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Done pruning leftover image files" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Loading daemon configuration" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Started seccomp handler" path=/var/lib/lxd/seccomp.socket
t=2020-03-03T15:55:43-0600 lvl=info msg="Pruning expired images" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Done pruning expired images" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Pruning expired container backups" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Done pruning expired container backups" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Updating instance types" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Done updating instance types" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Expiring log files" 
t=2020-03-03T15:55:43-0600 lvl=info msg="Done expiring log files" 

## Output of lxc info

config:
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
[redacted]
    -----END CERTIFICATE-----
  certificate_fingerprint: [redacted]
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.3.0-40-generic
  lxc_features:
    cgroup2: "false"
    mount_injection_file: "false"
    network_gateway_device_route: "false"
    network_ipvlan: "false"
    network_l2proxy: "false"
    network_phys_macvlan_mtu: "false"
    network_veth_router: "false"
    seccomp_notify: "false"
  project: default
  server: lxd
  server_clustered: false
  server_name: bear
  server_pid: 24959
  server_version: "3.21"
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.8

**Comment by stgraber** [comment]
@brauner
