### ISSUE TITLE
proxy device crashes when forwarding web traffic

### ISSUE THREAD

**Issue by neilbags** [lxc/lxd#6973]
I've got a production webserver in an lxd container with ports 80 and 443 forwarded through an lxc proxy device.

About once a month or so the proxy device seems to go down. Since its in production i've just been rebooting the host os right away, and don't have any logging data.

I don't know how to reproduce this - I assume its script kiddies sending malformed packets. Is anyone else experiencing these types of issues? I'm considering just using iptables instead, but thought i'd ask because i can't be the only one.

$ uname -a
Linux z 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lxc --version
3.0.3

Sorry, i know this is a terribly vague bug report.

**Comment by stgraber** [comment]
Any chance you can test this on a recent LXD release (LXD 3.21 ideally)?

We've fixed a lot of issues in the proxy since, some of those are already in 3.0.4 too (but that version isn't packaged in Ubuntu yet).

**Comment by neilbags** [comment]
Ok i'm on 3.21 now. Let's see how it goes

**Comment by stgraber** [comment]
@neilbags how's that been going?

**Comment by neilbags** [comment]
May be too early to tell, but so far no issues

**Comment by stgraber** [comment]
Okay, let's call it good and we can re-open if it's not.
