### ISSUE TITLE
Failed to migrate to dqlite 1.0: No database dump found

### ISSUE THREAD

**Issue by feileacan** [lxc/lxd#6980]
# Required information

 * Distribution: Chrome OS
 * Distribution version: 3.17
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.19.106-08245-g9eef371ee83e
   * LXC version: 3.03
   * LXD version: 3.17
   * Storage backend in use: btrfs (5.3.1)

# Issue description

Missing global/db.bin blocks lxd from starting - https://bugs.chromium.org/p/chromium/issues/detail?id=1057869

```
>ls -R
.:
global  global.bak  local.db  local.db.bak

./global:
logs.db  snapshots

./global/snapshots:

./global.bak:
logs.db  snapshots

./global.bak/snapshots:
```

We've seen a few cases where 1: somehow a user's database dump disappears then 2: this missing dump blocks lxd from even launching, since it tries to migrate, fails, then shuts back down:
```
2020-02-13 00:57:07.084 6 VM(3)[4662]:   lxd[135]: t=2020-02-13T00:57:02+0000 lvl=info msg="Initializing local database"#012
2020-02-13 00:57:07.084 3 VM(3)[4662]:   lxd[135]: t=2020-02-13T00:57:02+0000 lvl=eror msg="Failed to start the daemon: Failed to migrate to dqlite 1.0: No database dump found"#012
2020-02-13 00:57:07.084 6 VM(3)[4662]:   lxd[135]: t=2020-02-13T00:57:02+0000 lvl=info msg="Starting shutdown sequence"#012
```

I have a repro case that's in this bad state if there's any more information you need, but haven't been able to turn a working install into this state.

Expected behaviour - 1: the database doesn't disappear, 2: lxd is still able to launch so we or our users can recover their containers e.g. lxd import.

Thanks

**Comment by freeekanayaka** [comment]
So just to be clear, these are users that have been upgrading from some previous LXD version right?

What might have happened is that the last time the **previous** LXD version was run it did not shutdown cleanly and didn't have chance to dump that ```db.bin``` file. If the upgrade was done right at this point, it might produce this error.

The easiest way to fix this would be to 1: restore the ```global.bak``` and ```local.db.bak``` files to get back to the pre-upgrade state 2: restart the **previous** LXD binary and shut it down gracefully. 3: retry the upgrade.

As for a broader fix, we might be able to automatically recover from a situation where ```db.bin``` is missing by re-generating it, but it could be non-trivial to do.

**Comment by feileacan** [comment]
Probably upgrading from a previous version, haven't confirmed.

Launching the previous LXD binary would be tricky since Chrome OS doesn't support downgrading OS without wiping the machine. Would restoring the previous global.bak and local.db.bak then relaunching current LXD to try the upgrade again not work?

That said, in the one case I got a disk image of there's no db.bin in global.bak either so can't recover that way.
Could something be saving the global db again (e,g, prior to upgrade or if you retry launching) and overwriting global.bak as well?

**Comment by freeekanayaka** [comment]
> Probably upgrading from a previous version, haven't confirmed.
> 
> Launching the previous LXD binary would be tricky since Chrome OS doesn't support downgrading OS without wiping the machine. Would restoring the previous global.bak and local.db.bak then relaunching current LXD to try the upgrade again not work?

No, it would fail in the same way, since the new binary of LXD would start off from the same state (with a missing db.bin).

> 
> That said, in the one case I got a disk image of there's no db.bin in global.bak either so can't recover that way.
> Could something be saving the global db again (e,g, prior to upgrade or if you retry launching) and overwriting global.bak as well?

I don't understand this question.

**Comment by stgraber** [comment]
To be clear, `db.bin` isn't required by LXD at all. In fact, this file isn't read by LXD.
`db.bin` is a saved view of the database as assembled from Raft. It's useful for debugging purposes but it is not where the data is stored.

What you do need is at least one snapshoft or a set of segments to replay the raft transactions to your current state.

This is LXD 3.17 on ChromeOS. Can you comment on the versions of libraft and libdqlite used in your setup? We did have a bug a few months ago where out of disk space situations could lead to missing files and a broken database, though not quite to the extent displayed here.

It may be worth checking with @freeekanayaka on good versions of those two dependencies to match the LXD version you ship.

**Comment by stgraber** [comment]
Seeing that both the main directory and the backup directory are near empty, I wonder if it wasn't a bad shutdown leading to un-flushed btrfs transactions. LXD would have copied `global` over to `global.bak`, then opened the database from `global` and run the update.

This would have lead to most files being freshly written, so if filesystem writes weren't properly flushed, a filesystem view such as the one you posted in this issue is possible.

**Comment by feileacan** [comment]
Ah, that sounds plausible.

* @stgraber I've found that deleting the entire database folder allows lxd to start, then I can `lxd import` the existing containers. If we're only running containers on the same host is there anything we'd lose when we `lxd import` the container?
* @stgraber Do you have a link to the issue where out-of-disk leads to broken database? A quick github search didn't find it for me. We've seen issues when running out of space e.g. http://crbug/930602 and am curious if it's the same.
* @freeekanayaka What versions of raft and dqlite should we be running with lxd 3.17? We use whichever versions are bundled with lxd in in the download at https://linuxcontainers.org/downloads/lxd/lxd-3.17.tar.gz . The timestamp is September 2019.

Thanks,

**Comment by stgraber** [comment]
@feileacan you will loose any daemon configuration, network configuration, profiles, projects and storage volumes. Depending on the use case, that may not be a problem though.

@freeekanayaka may have a link to the out of disk issue we fixed a while back.

**Comment by freeekanayaka** [comment]
@feileacan the out of disk issue is very likely not relevant, since it affected the dqlite 1.x series (for reference here's the top-level [PR](https://github.com/canonical/dqlite/pull/189) where the issue was fixed).

Now, the lxd 3.17 tarball **does** sport dqlite 1.x (didn't check what version exactly, but it doesn't matter), **however** as far as I can tell the issue has happened because of an unclean shutdown of lxd 3.14 or earlier (which is the last version sporting dqlite 0.x) immediately followed by an upgrade to 3.15 or later (presumably 3.17 in your case).

Unfortunately this is an edge case we don't have a good fix for at the moment, so if you want to restore your state completely the only option would be to restore the state as it was before the upgrade (e.g. with the .bak directories), start 3.14 again (or whatever version you were running before the upgrade), shut it down cleanly and then re-try the upgrade.

**Comment by stgraber** [comment]
@freeekanayaka anything more to do here?

**Comment by freeekanayaka** [comment]
@stgraber I don't think there's anything with a reasonable cost/benefit ratio to do here. The suggested approach is either restart from scratch and use `lxd import` to restore your containers, or revert to 3.14 restoring the `.bak` dir and try to shutdown it gracefully then re-do the upgrade.

**Comment by stgraber** [comment]
Ok, since we haven't any more cases of this and 3.14 was quite a while back, let's close this.
