### ISSUE TITLE
Document itemization problem

### ISSUE THREAD

**Issue by tenforward** [lxc/lxd#6982]
# Issue description

In the official documentation, some itemization are not converted correctly. For example,

* "Additional libraries" section in [Requirements page](https://linuxcontainers.org/lxd/docs/master/requirements)
* "Commit structure" section in [Contributing page](https://linuxcontainers.org/lxd/docs/master/contributing)

On github, these are correctly itemized.

In readthedocs, line breaks may be required between paragraphs and itemization. However, line breaks did not solve the problem in the official documentation ([this patch](https://github.com/lxc/lxd/commit/18b4df801a55d4089c10e989410fe7efe5e8eb5c)).

I don't know how to convert the official document, so I just report it.

**Comment by stgraber** [comment]
I think it may just be the official documentation being out of data, let me go kick it.

**Comment by stgraber** [comment]
@tenforward yep, that was it, the fix was correct, it was just the online doc being out of date, fixed now.

**Comment by tenforward** [comment]
Thanks!! :smiley: 
I will send a patch for other non-itemized parts. (ex. Requirements page)

**Comment by tenforward** [comment]
I Sent #6984

**Comment by stgraber** [comment]
Thanks!

**Comment by stgraber** [comment]
And website updating now.
