### ISSUE TITLE
running jailkit command jk_init in lxd instance is sometimes very slow

### ISSUE THREAD

**Issue by dhpowrhost** [lxc/lxd#6985]
# Required information

 * Distribution: 
Debian
 * Distribution version: 
buster 10.2
 * The output of "lxc info" or if that fails:

`config:
  core.https_address: 10.10.1.49:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.10.1.49:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
 
    -----END CERTIFICATE-----
  certificate_fingerprint: 
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-0.bpo.2-amd64
  lxc_features:
    cgroup2: "false"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: lxd07
  server_pid: 37133
  server_version: "3.21"
  storage: zfs
  storage_version: 0.8.3-1~bpo10+1
`

# Issue description

We have used jailkit to let customers use ssh on our servers giving them access only to their own little chrooted environment. On bare metal and VPS this works perfectly, however sometimes - and only sometimes we see that when we create a jail it takes more than 30 times longer to run jk_init. Seems to be related to the container. One container with same profile on the same host is slow - another container with same specs have no issues.

See attached strace of the process. It seems to be the close(3) syscall that is taking up the time.
[strace-jailkit-lxd-close(3).txt](https://github.com/lxc/lxd/files/4291949/strace-jailkit-lxd-close.3.txt)
cpu usage is not high. There is no iowait on the host.

# Steps to reproduce

 1. Create debian 10 container
 2. Install jailkit
 3. And then sometimes - only sometimes it takes forever to run jk_init -v -j /home/jails/jail 

# Information to attach

**Comment by stgraber** [comment]
I've been playing around with jailkit on a debian 10 container for maybe half an hour without much success in reproducing a hang. Any chance you can share a clear reproducer in a freshly created container?

**Comment by stgraber** [comment]
```
root@debian10:~# for i in $(seq 100); do time (mkdir -p /home/jail ; jk_init -j /home/jail basicshell >/dev/null ; rm -rf /home/jail) | grep real; done 2>&1 | grep real
real	0m0.156s
real	0m0.451s
real	0m0.410s
real	0m0.425s
real	0m0.407s
real	0m0.410s
real	0m0.412s
real	0m0.412s
real	0m0.433s
real	0m0.415s
real	0m0.427s
real	0m0.448s
real	0m0.416s
real	0m0.471s
real	0m0.420s
real	0m0.425s
real	0m0.412s
real	0m0.416s
real	0m0.419s
real	0m0.426s
real	0m0.426s
real	0m0.427s
real	0m0.452s
real	0m0.415s
real	0m0.422s
real	0m0.421s
real	0m0.449s
real	0m0.446s
real	0m0.413s
real	0m0.420s
real	0m0.431s
real	0m0.432s
real	0m0.419s
real	0m0.450s
real	0m0.456s
real	0m0.422s
real	0m0.419s
real	0m0.417s
real	0m0.425s
real	0m0.423s
real	0m0.418s
real	0m0.419s
real	0m0.426s
real	0m0.423s
real	0m0.460s
real	0m0.434s
real	0m0.417s
real	0m0.431s
real	0m0.428s
real	0m0.418s
real	0m0.430s
real	0m0.421s
real	0m0.431s
real	0m0.417s
real	0m0.424s
real	0m0.484s
real	0m0.416s
real	0m0.435s
real	0m0.415s
real	0m0.540s
real	0m0.419s
real	0m0.437s
real	0m0.428s
real	0m0.425s
real	0m0.422s
real	0m0.425s
real	0m0.488s
real	0m0.417s
real	0m0.426s
real	0m0.422s
real	0m0.431s
real	0m0.429s
real	0m0.425s
real	0m0.429s
real	0m0.452s
real	0m0.448s
real	0m0.449s
real	0m0.441s
real	0m0.440s
real	0m0.420s
real	0m0.433s
real	0m0.419s
real	0m0.427s
real	0m0.424s
real	0m0.449s
real	0m0.485s
real	0m0.463s
real	0m0.442s
real	0m0.427s
real	0m0.424s
real	0m0.445s
real	0m0.425s
real	0m0.453s
real	0m0.429s
real	0m0.420s
real	0m0.422s
real	0m0.433s
real	0m0.463s
real	0m0.440s
real	0m0.438s
```
