### ISSUE TITLE
Add USB and PCI devices to resources API

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#6991]
The LXD resources endpoint doesn't currently show all PCI and USB devices. This information can be used to know what hardware is available for pass through. Ideally LXD would be able to tag hardware that is currently in use and unable to be redirected.

**Comment by stgraber** [comment]
For both type of items, I suspect we'll want:

 - driver
 - driver_version
 - numa_node
 - pci_address
 - product
 - product_id
 - vendor
 - vendor_id

Note that some cards will not have a driver loaded, that's fine and should just be kept empty.

We'll want those under separate rootfs, `pci` and `usb`. Those will be somewhat redundant with what we already have under network/storage so I don't expect we'll want to show any of that directly in `lxc info`.

**Comment by stgraber** [comment]
For USB, PCI address isn't really applicable, instead it should be BusAddress and DeviceAddress I believe (looking at `lsusb`).

Note that we need to fill all of this only by looking at the filesystem (`/sys`).
