### ISSUE TITLE
lxd operation show not very useful

### ISSUE THREAD

**Issue by ort163** [lxc/lxd#6995]
# Required information

ubuntu bionic

```
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.18.0-25-generic
  server: lxd
  server_pid: 4137
  server_version: 3.0.3
  storage: zfs
  storage_version: 0.8.1-3~18.04.york0
  server_clustered: false

```
# Issue description

lxc operation show is not very useful

LXD status codes `created_at updated_at` identical even after several hours. May be better if the updated_at is recent.

# Steps to reproduce

 1. make a copy some huge containers (containing AOSP code)
 2. wait for it to run
 3. After few hours still the updated_at is so old.
 4.  Would be nice if status or  updated_at is refreshed regularly (say every few minutes)

# Information to attach

```

~ $ lxc operation  show dffggfd18-278a-4f19-b3e4-11ece89bd208
id: d9d6fd18-278a-4f19-b3e4-11ece89bd208
class: task
description: Creating container
created_at: 2020-03-08T10:25:06.712379023+01:00
updated_at: 2020-03-08T10:25:06.712379023+01:00
status: Running
status_code: 103
resources:
  containers:
  - /1.0/containers/xenial-quack-aosp
  - /1.0/containers/xenial-los-rename
metadata: {}
may_cancel: false
err: ""

~ $ date
Sun Mar  8 13:22:19 CET 2020

```

**Comment by stgraber** [comment]
That would just needlessly require running a go routine and burning cpu without actually saying anything about whether something is happening.

Operations where progress information is available will show that under metadata.
