### ISSUE TITLE
IP addresses allocated with DHCP for unmanaged bridge device

### ISSUE THREAD

**Issue by eagerm** [lxc/lxd#6996]
# Required information

 * Distribution:  CentOS 
 * Distribution version: 8
 * The output of "lxc info" or if that fails: 
[lxc-info.txt](https://github.com/lxc/lxd/files/4303830/lxc-info.txt)
   * Kernel version: 4.18.0
   * LXC version: 3.2.1
   * LXD version: 3.20
   * Storage backend in use:  dir

# Issue description

A container using an unmanaged bridge is getting an IP address from DHCP (from the LAN) in addition to the static IP which is configured in the container.   The container does not issue DHCP request.  This should not happen.

# Steps to reproduce
 1. Create a container, configure with a static IP  (e.g., 192.168.20.42)
 2. Attach unmanaged bridge device to container
 3. Start container, list status.
The container will have an IP address (e.g., 192.168.20.175) obtained from the DHCP server on the LAN.  When the container starts (or occasionally some time after), the static IP will be allocated.  Running "ifup eth0" in container will remove IP obtained by DHCP.

$ lxc network show br0
config: {}
description: ""
name: br0
type: bridge
used_by:
- /1.0/instances/fedora31
managed: false
status: ""
$ lxc profile show bridge
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: lxdraid
    type: disk
name: bridge
used_by:
- /1.0/instances/fedora31
$ lxc start fedora31
$ lxc list fedora31
+----------+---------+-----------------------+------+-----------+-----------+
| fedora31 | RUNNING | 192.168.20.42 (eth0)  |      | CONTAINER | 0         |
|          |         | 192.168.20.175 (eth0) |      |           |           |
+----------+---------+-----------------------+------+-----------+-----------+
$ lxc exec fedora31 -- ifup eth0
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/2)
$ lxc list fedora31
+----------+---------+----------------------+------+-----------+-----------+
| fedora31 | RUNNING | 192.168.20.42 (eth0) |      | CONTAINER | 0         |
+----------+---------+----------------------+------+-----------+-----------+
 
 - [ ] Container log (`lxc info NAME --show-log`)
[lxc-log.txt](https://github.com/lxc/lxd/files/4303843/lxc-log.txt)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
[lxc-config.txt](https://github.com/lxc/lxd/files/4303845/lxc-config.txt)
 - [ ] Output of the client with --debug
[lxc-monitor.txt](https://github.com/lxc/lxd/files/4303838/lxc-monitor.txt)

**Comment by stgraber** [comment]
There is no way for LXD or liblxc to perform DHCP. The only way this can happen is if your container does it.

Take a close look at NetworkManager and networkd, one of the two is likely still doing this.

**Comment by eagerm** [comment]
Thanks for the info.  

I found that both systemd-networkd and NetworkManager were running in the container.  NetworkManager was configuring the static IP while systemd-networkd was getting an IP using DHCP.  I disabled NetworkManager and configured systemd-networkd with a static IP.
