### ISSUE TITLE
lxd daemon power usage (powertop)

### ISSUE THREAD

**Issue by token47** [lxc/lxd#7000]
* Distribution: ubuntu
  * Distribution version: Eoan
  * The output of "lxc info" or if that fails: nothing fails
   * Kernel version: 5.3.0-29-generic
   * LXC version: 3.22
   * LXD version: 3.22
   * Storage backend in use: ZFS

I've been tracking down what are the processes consuming most power in my laptop (to optimize for battery life) and noticed that lxd daemon is frequently on the top of the list (on powertop).

Here is a sample:

Summary: 905,5 wakeups/second,  0,0 GPU ops/seconds, 0,0 VFS ops/sec and 17,0% CPU use

                Usage       Events/s    Category       Description
              3,2 ms/s     225,7        Timer          tick_sched_timer
              3,7 ms/s      73,2        Timer          hrtimer_wakeup
             74,7 ms/s      42,7        Process        [PID 10547] /opt/google/chrome/chrome --type=renderer --disable-webrtc-apm-in-audio-service --field-trial-handle=90661688012137
              3,9 ms/s      61,2        Process        [PID 30636] /opt/Telegram/Telegram -noupdate
              2,5 ms/s      53,3        Process        [PID 28781] /opt/google/chrome/chrome
              0,7 ms/s      44,5        Process        [PID 24395] lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
              1,6 ms/s      43,4        Process        [PID 674] [irq/135-iwlwifi]

Also, on "top", it keeps around 1% of cpu usage constantly.

While those two things don't seem much at first, I wonder why it's doing that if there's nothing running. No containers or VMs are running (in fact I have only one stopped container).

At some moments it was on the top of the list (still doing nothing), but I cannot reproduce it now.

I expected to see chrome high on that list but not lxd when doing nothing. Maybe a too aggressive timer for some internal loop?

**Comment by stgraber** [comment]
Can you install `health-check` and then run:

`health-check -f -c -p $(cat /var/snap/lxd/common/lxd.pid) -d 30`

This should show some more details on wakeups coming from LXD.

**Comment by token47** [comment]
Thank you for the response.

https://pastebin.ubuntu.com/p/2TrkSr572t/

Doesn't seem too bad now. No containers running and not executing any operations.

I'll keep an eye on it and run the health-check again if I see it happening.

If you don't think there's anything of note on this report, you can go ahead and close this for new.

Thanks!

**Comment by stgraber** [comment]
LXD seems quite fine in your case. dnsmasq looks a lot busier than usual though, not sure what's going on with it.

On the LXD side, I didn't see anything obviously wrong. Last time we had such a report, we had a goroutine firing every second which was causing around 400 ctx/s, but here on a fairly non-busy LXD, I'm somewhere between 40 and 100 ctx/s which isn't too bad.

Closing for now, if someone hits similar issues, please run that `health-check` command so we can figure out what's going on.
