### ISSUE TITLE
systemd taking 100% CPU

### ISSUE THREAD

**Issue by Sujai85** [lxc/lxd#7009]
Hello,

I could see that systemd process taking 100% CPU on lxd containers. Can you please help me with this issue? 
<img width="374" alt="systemdlxd" src="https://user-images.githubusercontent.com/57617793/76510284-5cdb8e80-6477-11ea-87c2-3ce47ff82b4f.png">

Thank you
Sujai

**Comment by stgraber** [comment]
what version of LXD, what image, what version of systemd, ...

Your report is a bit light on details.
