### ISSUE TITLE
limits.kernel.nofile and systemd init / PID 1 limit

### ISSUE THREAD

**Issue by hloeung** [lxc/lxd#7017]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-9-generic
   * LXC version: 3.2.1
   * LXD version: 3.22
   * Storage backend in use: dir

# Issue description

LXC/LXD documentation mentions using limits.kernel.nofile to increase max. open files for containers but that doesn't allow you to get past 1048576 with container failing to start:

lxc cactuar 20200312035049.930 ERROR    conf - conf.c:setup_resource_limits:2597 - Operation not permitted - Failed to set limit nofile
lxc cactuar 20200312035049.930 ERROR    start - start.c:lxc_spawn:1792 - Failed to setup resource limits
lxc cactuar 20200312035049.930 WARN     network - network.c:lxc_delete_network_priv:2589 - Operation not permitted - Failed to remove interface "eth0" with index 12
lxc cactuar 20200312035049.930 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "ABORTING" instead of "RUNNING"
lxc cactuar 20200312035049.931 ERROR    start - start.c:__lxc_start:1939 - Failed to spawn container "cactuar"
lxc 20200312035049.942 WARN     commands - commands.c:lxc_cmd_rsp_recv:132 - Connection reset by peer - Failed to receive response for command "get_state"

Not even with fs.nr_open set to something higher than 1048576.

It seems this is due to the systemd limit as per commit https://github.com/systemd/systemd/commit/6385cb31ef443be3e0d6da5ea62a267a49174688 and also:

$ grep open /proc/1/limits
Max open files            1048576              1048576              files

The fix here is to call prlimit to increase PID 1's limits. Maybe LXD should do this if/when limits.kernel.nofile is configured?

$ sudo prlimit --pid 1 --nofile=7424000

# Steps to reproduce

 1. Spin up a new container.
 2. sudo sysctl fs.nr_open 7424000
 3. sudo lxc config set $container$ limits.kernel.nofile 7424000
 4. Stop and start container.
 5. Fails to start.
 6. sudo prlimit --pid 1 --nofile=7424000
 7. Start container.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Deployed a clean Ubuntu 20.04 system and did the following per your instructions:

```
root@vm02:~# lxc launch images:alpine/edge a1
Creating a1
Starting a1                                 
root@vm02:~# cat /proc/sys/fs/nr_open 
1048576
root@vm02:~# echo 7424000 > /proc/sys/fs/nr_open
root@vm02:~# cat /proc/sys/fs/nr_open 
7424000
root@vm02:~# lxc config set a1 limits.kernel.nofile 7424000
root@vm02:~# lxc stop a1
root@vm02:~# lxc start a1
root@vm02:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Focal Fossa (development branch)
Release:	20.04
Codename:	focal
root@vm02:~# lxc exec a1 sh
~ # cat /proc/self/limits | grep "open files"
Max open files            7424000              7424000              files     
~ # root@vm02:~# 
```

**Comment by stgraber** [comment]
anything else I'm missing to have this issue happen?

**Comment by hloeung** [comment]
Ah, the steps I used to reproduce this is Bionic and LXD 3.03.

https://pastebin.ubuntu.com/p/Jx8vjZ8YtS/

**Comment by hloeung** [comment]
I'll just close this off for now as we'll just rework our application reducing the max. fds required.
