### ISSUE TITLE
qemu: Invalid parameter 'obsolete'

### ISSUE THREAD

**Issue by Ne02ptzero** [lxc/lxd#7023]
I'm running into the following issue with a `lxc start` on a virtual-machine:
```
$> lxc start LF3eb234f5-66ff-4592-9436-4ff0c772c250
Error: Failed to run: /usr/bin/lxd forklimits limit=memlock:unlimited:unlimited -- /usr/bin/qemu-system-x86_64 -S -name LF3eb234f5-66ff-4592-9436-4ff0c772c250 -uuid 9cb93712-2808-41f3-8687-8d62caef7b77 -daemonize -cpu host -nographic -serial chardev:console -nodefaults -no-reboot -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=deny,resourcecontrol=deny -readconfig /var/log/lxd/LF3eb234f5-66ff-4592-9436-4ff0c772c250/qemu.conf -pidfile /var/log/lxd/LF3eb234f5-66ff-4592-9436-4ff0c772c250/qemu.pid -D /var/log/lxd/LF3eb234f5-66ff-4592-9436-4ff0c772c250/qemu.log -chroot /var/lib/lxd/virtual-machines/LF3eb234f5-66ff-4592-9436-4ff0c772c250 -runas nobody: qemu-system-x86_64: -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=deny,resourcecontrol=deny: Invalid parameter 'obsolete': exit status 1
Try `lxc info --show-log LF3eb234f5-66ff-4592-9436-4ff0c772c250` for more info
```
(`lxd/instance/drivers/driver_qemu.go`)

The server is on debian 9 (so debian oldstable), and the distro-packaged qemu with the following version:
```
$> qemu-system-x86_64 --version
QEMU emulator version 2.8.1(Debian 1:2.8+dfsg-6+deb9u9)
Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers
```

I can't find in which version the parameters to `sandbox` where introduced in QEMU, but in the packaged version, it only accepts `on` or `off`.

There's no real solution for this, besides:
1) Make a more intelligent code that works with the qemu version (Might be useful in the future too)
2) Removing the sandbox arguments in order to comply with older systems
3) Not supporting virtual-machines without at least a XX.XX qemu version.

Any of these will work for me.

**Comment by stgraber** [comment]
We should put out a statement in documentation about the version of qemu we support and test on.

The version we actively develop/test on and ship with the snap is Qemu 4.2 but we also have systems running on 2.11 so we're unlikely to completely break 2.11. Versions prior to that should be considered unsupported.

I don't think we'd reject a pull request to do version detection to handle older versions, but we're realistically not going to be testing on old versions to make sure we don't break things again later.
