### ISSUE TITLE
sshguard in lxc container blocks everything

### ISSUE THREAD

**Issue by clauded** [lxc/lxd#7050]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version: 3.22
   * Storage backend in use: ZFS

# Issue description

We've installed sshguard inside a lxc container and defined a lxc proxy:

  proxy-ssh:
    bind: host
    connect: tcp:10.10.10.10:22
    listen: tcp:x.x.x.x:5000
    type: proxy

When sshguard detects an 'attack' it blocks the ip but the ip blocked is the proxy ip (10.10.10.10) so all communication is blocked with the container. Is there a way to have the container receive the real adresses?

**Comment by tomponline** [comment]
This is expected, as the proxy opens a new connection from the host. If you use the `nat=true` on the proxy device config it will use DNAT instead which should then pass the source address through.
