### ISSUE TITLE
sys-kernel-tracing.mount fails to in non-privileged container

### ISSUE THREAD

**Issue by rbalint** [lxc/lxd#7059]
Systemd 245 introduces a new mount for tracefs:

https://github.com/systemd/systemd/pull/14916

I fails in lxc, as observed in armhf autopkgtest results:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-focal-ci-train-ppa-service-3801/focal/armhf/s/systemd/20200318_193832_448e9@/log.gz

Please treat it the same way as `sys-kernel-debug.mount`, and bind-mount `/sys/kernel/tracing`, too.

**Comment by stgraber** [comment]
Note that us adding it will not do you any good unless the host also has it mounted.
So while it's fine for us to add it similarly to debugfs and others, it won't actually fix your issue.
