### ISSUE TITLE
Upgrade to lxc 3.2.1 fails

### ISSUE THREAD

**Issue by falves1** [lxc/lxd#7064]
I was using Ubuntu 18.04 with stock lxc, not lxd. Now I need ipvlan support so I erased all packages with the word "lxc" in the name. Then I downloaded https://linuxcontainers.org/downloads/lxc/lxc-3.2.1.tar.gz. I did the usual make,install, etc. lxc-start --version shows the correct version. But lxc-ls shows no containers exist, when in fact I do have 20 containers in the box. The tar ball does not really install LXC. Can somebody fix the tar ball so it does what it needs to do? I also did a lxc-update-config on one of my containers, and it worked, but still lxc-ls shows nothing.

**Comment by stgraber** [comment]
Filled against the wrong project. What you're describing would be consistent with a manually built LXC without the appropriate paths being passed to configure.

In that case it would likely look for containers in /usr/local/var/lib/lxc or something.

**Comment by falves1** [comment]
is there any documentation on how to pass the right parameters to the ./configure ?

**Comment by falves1** [comment]
parse.c: lxc_file_for_each_line_mmap: 142 Failed to parse config file "/usr/local/var/lib/lxc/xxx-20/config" at line "lxc.net.1.ipvlan.flags=bridge"

**Comment by falves1** [comment]
lxc.net.1.type=ipvlan
lxc.net.1.ipvlan.mode=l3
#lxc.net.1.ipvlan.flags=bridge
lxc.net.1.link=eth0
lxc.net.1.name = eth1
lxc.net.1.flags=up
lxc.net.1.ipv4.address = 0.0.0.0/24
The network type ipvlan does no work. It creates an interface with the same mac address as the linked interface from the host, and that is what I need, but there is no communication through. 
if I try this:
arping -I eth1 xx.x.x.1
ARPING xx.x.x.1
arping: libnet_write(): libnet_write_link(): only -1 bytes written (No buffer space available)
