### ISSUE TITLE
Importance of disk I/O performance for the host system

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#7067]
This is more of a general question as to how LXD containers depend on the host kernel and the underlying hardware the host system is installed on.

As we all know Linux Containers share the host system kernel - I am in the process of researching various hardware configurations for our next iteration of bare-metal servers and a fundamental question came to mind: How important is disk i/o performance to the host kernel?

Should one go balls-out and raid a bunch of NVMe drives for your host OS install (in addition to having multiple NVMe drive ZFS backed storage for your containers) for optimum performance on current generation hardware?

My feeling is, without knowing the specifics of how the Ubuntu/Linux kernel is loaded and utilized by LXD containers, that the kernel is mostly living in RAM and rarely hits the disk. I conclude this from "gut feeling" experience dealing with a range of hardware combinations and LXD containers through these past few years. As an example, with just a few test containers a year back I saw no performance hit using a slow-as-balls SAS HDD drive for the host OS (untill a container needed to swap, that is, then things took a turn for the worse)

The picture becomes a bit more unclear however when considering a very high density compute host with up to hundreds of containers doing their thing ... Even if the kernel doesn't use much i/o, the denser you want to go the more i/o horsepower you should probably give your host kernel?

Is the sane approach to use sturdy enterprise grade SSD SATA or SAS (reasonably priced obviosuly) drives for your OS - and then spend your money on optimizing your container storage with fast-as-flip NVMe for best all-round performance pr. $?

I would love to hear some theory and/or wisdom from somebody "in the know" on this topic :)

**Comment by stgraber** [comment]
Yeah, no need for NVME for the root filesystem unless you're dealing with a very busy cluster where database commit times start to matter.

The other things that LXD write to the root disk are things like backups and images but there are now config options to control that too.

As for the kernel, no, it doesn't care about disk I/O so your host system can be running from super slow storage without impacting the running containers.

**Comment by stgraber** [comment]
Closing as not really an issue, happy to keep chatting though. In the future such questions are often better handled on the forum where other users of large LXD deployments can share their experiences.

**Comment by Kramerican** [comment]
Thank you so much for this information @stgraber - I will make sure to post general questions like this in the forum in the future
