### ISSUE TITLE
Implement the publish command

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#707]
Looks like this one fell through the cracks and didn't get an issue filed.

**Comment by hallyn** [comment]
@stgraber a question.  Currently things like LXC_NAME in /etc/hosts are not being expanded.  I assume lxd/template.go will end up doing that.  I suppose I should just ignore this for now, but I assume we'll want to reverse such changes on image publish?  I'm not sure how we can do so robustly though, unless we just always re-place the full original file, which can also go wrong if parts of it were properly updated in the snapshot being published.

**Comment by stgraber** [comment]
@hallyn The way we'll deal with those variables is by having images.linuxcontainers.org include templates in the lxd image for those files. So long as you keep those templates in the image on publish, the template will be used again on the next container creation and everything will be fine.

**Comment by hallyn** [comment]
But say i lxc launch ubuntu u1;  make changes to /etc/hosts;  lxc snapshot u1;  and now lxc publish u1/snap0.  what's the right thing to do?  LXC_NAME is no longer in /etc/hosts, so we don't know how to un-template it;  putting the original templated file back in may be wrong depending on circumstances.

**Comment by stgraber** [comment]
@hallyn the templates in LXD aren't like those in LXC. We don't sed a string, we generate the whole file. So yes, if you make modifications to a templated file, it will be overwritten the next time the template is triggered.

In such cases, we'd expect the user to adjust the template rather than change the file directly.

**Comment by stgraber** [comment]
This has been done by @hallyn.
