### ISSUE TITLE
Beginning with v3.19, messing around with zfs volumes directly prevents container startup

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#7079]
Ubuntu Bionic

I have always enjoyed the flexibility of LXD in conjunction with the ZFS filesystem and how I was able to monkey around with ZFS volumes pretty much ad-hoc and I could in this fashion do a bunch of non-standard but useful workflows when testing this and that.

Beginning with v3.19 however, if I try to do something like:

`lxc init ubuntu:bionic mytestcontainer`

And then I decide, no you know what, that container should have some other rootfs:

```
/sbin/zfs destroy -r lxd/containers/mytestcontainer
-> now execute something that creates a volume in lxd/containers/mytestcontainer like a zfs send/receive for example or just rename an existing volume
lxc start
```

Then I get:

```
Error: Common start logic: Failed to run: zfs mount lxd/containers/mytestcontainer: cannot mount 'lxd/containers/mytestcontainer': no mountpoint set
Try `lxc info --show-log mytestcontainer` for more info
```

What has changed? This smells like all I need to do is tell zfs what the mount point should be ... But yeah, how and why now?

Would this new behavior potentially break backup schemes where people snapshot / reload their entire ZFS pool?

I realize this is all "non standard" - but I expect maybe others might run into problems with their existing toolchains if they rely on this flexibility (as I have done in some scenarios)

**Comment by stgraber** [comment]
Our new storage logic is indeed a lot stricter than the previous one.
If something is missing that should be there, we error out immediately rather than go on and potentially hit issues later.

It shouldn't really impact what you've been doing, but you just need to make sure you do things the way LXD expects it.

In this case, the things to make sure of are:
 - mountpoint must be set properly
 - canmount must be set to noauto
 - the dataset should not be mounted if the container isn't running

If the above is all good, LXD should happily use the dataset.

The new storage driver is also a bit smarter about snapshot usage, LXD causes less snapshot pollution and also knows that users may have made snapshots outside of LXD. Those snapshots will be automatically ignored during migrations but will be considered blockers if for example, you're trying to delete a container that you've made out-of-lxd snapshots on.

**Comment by Kramerican** [comment]
Awesome - now, while I applaud that filesystem/snapshot stuff is becoming more robust, I am having a bit of trouble here...

- mountpoint must be set properly

I tried looking at an existing container with zfs list and from that setting it to  
`zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/lxd/containers/mycoontainer lxd/containers/mycontainer`
 
And stuff blew up ... Hints? :)

- canmount must be set to noauto

Where do I check/set this?

- the dataset should not be mounted if the container isn't running

Ah this is maybe where I went wrong as the zfs command auto-mounted the dataset, and the config option you mention above needed to be run first I'm guessing? :)

I'll try and figure that out tomorrow if I don't hear back from you and report back here ...

**Comment by stgraber** [comment]
`zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/lxd/containers/mycoontainer lxd/containers/mycontainer canmount=noauto DATASET` will usually do it if not already mounted.
If already mounted, then you'll need to unmount it to avoid confusing LXD.

**Comment by Kramerican** [comment]
Awesome - I got this all working with your help. What I do, exactly, for prosperity:

```
# zfs set canmount=noauto lxd/containers/mycontainer
# zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/lxd/containers/mycoontainer lxd/containers/mycontainer
# zfs unmount lxd/containers/mycontainer
# lxc start mycontainer
```

That final unmount is probably not required as the canmount=noauto should prevent any auto mounting, but I play it safe. **This works!**

**Comment by Kramerican** [comment]
Hello

This no longer works in v4.14 - it still worked on v4.8

Now when doing the above, I get:

```
root@asclepius:/home/master# zfs get canmount lxd/containers/mclaren
NAME                    PROPERTY  VALUE     SOURCE
lxd/containers/mclaren  canmount  noauto    local
root@asclepius:/home/master# zfs get mountpoint /lxd/containers/mclaren
/lxd/containers/mclaren: No such file or directory
root@asclepius:/home/master# zfs unmount lxd/containers/mclaren
cannot unmount 'lxd/containers/mclaren': not currently mounted
root@asclepius:/home/master# lxc start mclaren
Error: Failed preparing container for start: Failed to run: zfs mount lxd/containers/mclaren: cannot mount 'lxd/containers/mclaren': filesystem already mounted
Try `lxc info --show-log mclaren` for more info
root@asclepius:/home/master# zfs unmount lxd/containers/mclaren
cannot unmount 'lxd/containers/mclaren': not currently mounted
```

Hmm ok so already mounted somehow, let's check procinfo 


```
# grep lxd/containers/mclaren /proc/*/mountinfo
/proc/105335/mountinfo:10174 347 0:534 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren rw,noatime shared:4091 - zfs lxd/containers/mclaren rw,xattr,posixacl
/proc/1282434/mountinfo:10174 347 0:534 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren rw,noatime shared:4091 - zfs lxd/containers/mclaren rw,xattr,posixacl
/proc/1356439/mountinfo:10174 347 0:534 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren rw,noatime shared:4091 - zfs lxd/containers/mclaren rw,xattr,posixacl
/proc/1402589/mountinfo:10174 347 0:534 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren rw,noatime shared:4091 - zfs lxd/containers/mclaren rw,xattr,posixacl
/proc/1418030/mountinfo:10174 347 0:534 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren rw,noatime shared:4091 - zfs lxd/containers/mclaren rw,xattr,posixacl
/proc/1701823/mountinfo:10174 347 0:534 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren rw,noatime shared:4091 - zfs lxd/containers/mclaren rw,xattr,posixacl
/proc/1714544/mountinfo:10174 347 0:534 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren rw,noatime shared:4091 - zfs lxd/containers/mclaren rw,xattr,posixacl
/proc/1775410/mountinfo:10174 347 0:534 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren rw,noatime shared:4091 - zfs lxd/containers/mclaren rw,xattr,posixacl
/proc/2220508/mountinfo:10174 347 0:534 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren rw,noatime shared:4091 - zfs lxd/containers/mclaren rw,xattr,posixacl
/proc/2419807/mountinfo:10174 347 0:534 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren rw,noatime shared:4091 - zfs lxd/containers/mclaren rw,xattr,posixacl
/proc/2580827/mountinfo:10174 347 0:534 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren rw,noatime shared:4091 - zfs lxd/containers/mclaren rw,xattr,posixacl

... And many more lines
```

Ok let's make sure we are unmounted

```
# nsenter -t 98526 -m umount /var/snap/lxd/common/lxd/storage-pools/lxd/containers/mclaren
root@asclepius:/home/master# grep lxd/containers/mclaren /proc/*/mountinfo
root@asclepius:/home/master# zfs unmount lxd/containers/mclaren
cannot unmount 'lxd/containers/mclaren': not currently mounted
```

But ...

```
# lxc start mclaren
Error: Failed preparing container for start: Failed to run: zfs mount lxd/containers/mclaren: cannot mount 'lxd/containers/mclaren': filesystem already mounted
Try `lxc info --show-log mclaren` for more info
```

What's changed in latest versions that's confusing LXD vis-a-vis mountpoints now? :)

**Comment by stgraber** [comment]
Most likely some kind of in-kernel reference. Probably worth retrying after a while to see if it resolved, if not, the fact that it's not present in your mount table at all suggests a zfs bug so a reboot is pretty much the only way out of that.

Looking at a diff from LXD 4.8 to 4.14 I'm not seeing any real change to our mount logic. We still call `zfs mount` and `zfs unmount`. There have been some changes but they're around rounding disk quotas and VM volume map/unmap which doesn't affect containers.

**Comment by Kramerican** [comment]
Hmm ok that's unfortunate. One thing to note is that immediately after issuing the `lxc start`  after having killed the mounts with nsenter I again see mounts in proc

So it's as if LXD is getting partway - or maybe all the way - but then thinking there's a mount hanging anyway, if that makes sense.

I'll keep an eye on this, reboot when able, do more tests etc. and report back here what I find.

**Comment by stgraber** [comment]
Maybe some of this rings a bell with @tomponline but in general, ZFS just doesn't really do well with namespaces, so I wouldn't put it past the zfs tool from setting up the mounts and then freaking out with an error ;)

**Comment by tomponline** [comment]
@Kramerican yeah if you can get a reproducer after a fresh reboot that would be interesting. 

Also first thing to check is if the mount is removed after doing `lxc stop` from snap's mount namespace, before starting to recreate the ZFS volume.

**Comment by tomponline** [comment]
@Kramerican sorry, to be clear, I meant check the mount is removed from the snap's mount namespace after initiating a `lxc stop` from the normal namespace.

**Comment by Kramerican** [comment]
@tomponline Oh I see, yes that makes sense.

I cannot do this at the moment, but the first maintenance window I can justify sneaking in there I'll be trying that as well as rebooting the host in question and do further tests. I have no clue when exactly that will be possible so feel free to close this issue in the meantime if you want.

Thanks :)
