### ISSUE TITLE
Change default container configuration with "security.nesting=true"

### ISSUE THREAD

**Issue by AceSlash** [lxc/lxd#7085]
This is a follow-up of #7065 .

The thing is that currently I have random services that do not start anymore after an upgrade because they implement `ProtectSystem=` in their systemd service file.

Typical example are redis, mariadb and powerdns.

There are 2 ways to fix this:
1. add an override system file for all those services that deactivate `ProtectSystem=` but this is not scalable, and the main issue is when a software is updated and add this option, meaning that it could work first and then break at any time (even minor security update can add this setting)
2. `lxc config set container security.nesting true` from the host, which doesn't seem to have any downside, that's why I think that it should be the default

I have changed my own script that create containers to add this so it doesn't change anything for me, but I think that it is critical for the LXD project to help people have a seamless experience, which is not the case when common services simply don't work.

How many people would understand and fix something like that:
```
 # systemctl status redis
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-03-26 12:47:40 CET; 15s ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 10236 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=226/NAMESPACE)
```
Let's just eliminate the issue and make `security.nesting=true` the default.

**Comment by stgraber** [comment]
We're not going to do that. `security.nesting=true` is indeed mostly harmless for unprivileged containers, though there are system administrators that do not want their users to be able to using namespacing features in containers.

It would also make then setting `security.privileged=true` on a container get both privileged AND nesting which is then extremely unsafe.

We'll keep monitoring what happens with systemd and specific units and workaround things when we can in the default apparmor profile but switching the default to true isn't going to happen.

**Comment by K-PANIK** [comment]
Can you give us the last workarourd report ? Or an up to date link?
Without nested true, debian bullseye container systemd-networkd service still fails to init ipv4 for bridged ethernet interfaces... IPv6 probably works (ipv4 iproute settings workas an alternate configuration).

**Comment by stgraber** [comment]
```
stgraber@dakara:~$ lxc launch images:debian/bullseye d1
Creating d1
Starting d1
stgraber@dakara:~$ lxc list d1
+------+---------+----------------------+-------------------------------------------+-----------+-----------+
| NAME |  STATE  |         IPV4         |                   IPV6                    |   TYPE    | SNAPSHOTS |
+------+---------+----------------------+-------------------------------------------+-----------+-----------+
| d1   | RUNNING | 172.17.250.84 (eth0) | 2602:fc62:c:250:216:3eff:fe9d:1e0c (eth0) | CONTAINER | 0         |
+------+---------+----------------------+-------------------------------------------+-----------+-----------+
stgraber@dakara:~$ lxc config show --expanded d1
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian bullseye amd64 (20230531_05:24)
  image.os: Debian
  image.release: bullseye
  image.serial: "20230531_05:24"
  image.type: squashfs
  image.variant: default
  volatile.base_image: 9d10e8b9e175cdc5d8a331a439963f002c6855d35ce52b27d3cdb9c68d76c4c4
  volatile.cloud-init.instance-id: 55f6ec49-24de-4c47-bd8f-e8839b82cf02
  volatile.eth0.host_name: veth26e0db50
  volatile.eth0.hwaddr: 00:16:3e:9d:1e:0c
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 02ab308f-25a7-4828-8e2f-0cb47059eec3
  volatile.uuid.generation: 02ab308f-25a7-4828-8e2f-0cb47059eec3
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
stgraber@dakara:~$ lxc exec d1 bash
root@d1:~# systemctl --failed
  UNIT LOAD ACTIVE SUB DESCRIPTION
0 loaded units listed.
root@d1:~# 
```

**Comment by K-PANIK** [comment]
Ok but is networkd service umasked?
