### ISSUE TITLE
LXD resources is not providing model names consistent with lsblk

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#7096]
MAAS 2.7 uses LXD to gather commissioning information. [In LP:1869116 a user has reported that hardware testing is failing.](https://bugs.launchpad.net/maas/+bug/1869116) This is due to LXD reporting disk models with a space while lsblk uses an underscore.

lsblk model name: PERC_6/i
LXD model name: PERC 6/i

MAAS still uses lsblk for hardware testing and Curtin still uses lsblk when mapping disks to block devices. Naming must be consistent between lsblk and LXD.

**Comment by stgraber** [comment]
The model as reported by LXD is what's read from sysfs in the `model` file.
We don't do any processing on it.

**Comment by stgraber** [comment]
How exactly do you call `lsblk`? Running it here has it report the same names with spaces as LXD does and tracing it, it's getting it from the same place too.

**Comment by stgraber** [comment]
Closing as LXD isn't going to start mangling strings from the kernel to have them line up with another reporting tool, but I'd still be interested to know how it is that your version of lsblk seems to replace spaces when mine doesn't.

**Comment by ltrager** [comment]
MAAS:
https://git.launchpad.net/maas/tree/src/metadataserver/user_data/templates/snippets/maas_run_remote_scripts.py#n590

Curtin:
https://git.launchpad.net/curtin/tree/curtin/block/__init__.py#n222

I agree we shouldn't be changing strings from the kernel. I tested the command MAAS uses on my system and spaces aren't being replaces

`
$ lsblk --exclude 1,2,7 -d -P -o NAME,MODEL,SERIAL

NAME="nvme0n1" MODEL="INTEL SSDPEKKF256G8L" SERIAL="BTHP94351UPV256B"

NAME="nvme1n1" MODEL="Samsung SSD 970 EVO Plus 1TB" SERIAL="S4P4NF0M611513E"
`

The reporter is using a RAID controller which may have something to do with it.
