### ISSUE TITLE
Unable to rejoin cluster after leaving

### ISSUE THREAD

**Issue by nniehoff** [lxc/lxd#7100]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04 Focal
 * The output of "lxc info":  https://paste.ubuntu.com/p/ms9Qmwpgnc/
   * Kernel version:  5.4.0-14-generic
   * LXC version:  
   * LXD version:  3.23 (snap 14066)
   * Storage backend in use:  zfs with existing root zfs pool

# Issue description

I had a 3 node cluster (recently built after installing focal), each node has a zfs root filesystem on the rpool zfs pool.  I have created rpool/lxd for lxd's use.  I then realized one machine did not have the correct disk layout and since I deploy with maas I decided to fix it.  I did an lxc cluster remove on that machine no problems it left the cluster leaving me with 2 nodes.  I then rebuilt the 3rd machine but it will not rejoin the cluster, lxd init hangs.  I then tried with another focal machine and I also have problems with it joining, but thought it might be because I had lxd previously configured on that box not in a cluster.  So I tried adding a random VM to the cluster, it joined just fine and I removed it to continue testing on the 2 nodes that I actually want as cluster members.

# Steps to reproduce

I have tried to reproduce this on bionic with no such luck.  I am going to spin VMs and try focal shortly I will post the results.

# Information to attach

Status before join attempt:  https://pastebin.canonical.com/p/HBJYNtCXRZ/
lxd init --debug output:  https://pastebin.canonical.com/p/p3mTQmFg8D/
lxd debug log from machine attempting to join cluster:  https://pastebin.canonical.com/p/bxGX9CXNpZ/
lxd log from node1 (for appropriate time frame):  https://pastebin.canonical.com/p/gpfcdNMJhr/
lxd log from node2 (for appropriate time frame):  https://pastebin.canonical.com/p/F4B79GJt75/
lxc monitor from node1 (for appropriate time frame): https://pastebin.canonical.com/p/gxm4S8jKFD/
lxc monitor from node2 (for appropriate time frame): https://pastebin.canonical.com/p/WMT2DzsR8v/
status post join attempt: https://pastebin.canonical.com/p/DrFGnDByhF/

I think this is very similar to 
https://github.com/lxc/lxd/issues/5896

But the failed to join cluster message from my logs is:
t=2020-03-28T16:37:01-0600 lvl=dbug msg="Failure for task operation: ad6c2061-9881-49dd-82db-cfa286bae2a9: Failed to join cluster: server ID already in use (1)" 

hence the new issue.  I'd appreciate any help

**Comment by stgraber** [comment]
@freeekanayaka ideas?

**Comment by nniehoff** [comment]
FYI I can't reproduce this with VMs.  I've tried to break it and can't.  I'm thinking the failed operation that failed with "Failed to join cluster: server ID already in use (1)" is coming from dqlite but I'm not sure that's where I need some advice on where to look next.

**Comment by nniehoff** [comment]
I tried a hail marry attempt and joined the 10.12.48.40 node to the cluster I stood up in VMs, it joined right away.  I then left the cluster removed the snap and all lxd related folders, reinstalled, and it joined the real cluster right away.  Unfortunately the 10.12.48.31 node is stuck in the same place the trick didn't work for it.

**Comment by freeekanayaka** [comment]
> I tried a hail marry attempt and joined the 10.12.48.40 node to the cluster I stood up in VMs, it joined right away. I then left the cluster removed the snap and all lxd related folders, reinstalled, and it joined the real cluster right away.

This is the behavior I'd indeed expect to see for `10.12.48.40`, given that `10.12.48.4`0 is **not** showing up in the `raft_nodes` table of node2, as you report in https://pastebin.canonical.com/p/HBJYNtCXRZ/.

If I understand correctly (from https://pastebin.canonical.com/p/p3mTQmFg8D/ and https://pastebin.canonical.com/p/p3mTQmFg8D/) you made also at least another attempt to join `10.12.48.40` and it failed with `server ID already in use (1)`. Is that correct? That would be quite surprising, and I wouldn't have an explanation for it, even more so if it actually worked at a second attempt.

> Unfortunately the 10.12.48.31 node is stuck in the same place the trick didn't work for it.

This one failure is expected, since `10.12.48.31` does show up in the `raft_nodes` table of node2, meaning that it's currently already part of the raft configuration.

The question here is how did you and up with `10.12.48.31` being in the raft configuration but **not** in the global `nodes` table. That might be due to some issue that occurred the very first time you removed `10.12.38.31`, do you recall noticing anything like that?

I seem to remember that there were a few issues reported when using LXD clustering with MAAS, because nodes might end up being added and/or removed concurrently and that's probably not something we handle quite well at the moment.

Unfortunately I don't think there's an easy way to recover from this specific situation, the best you could do is to shutdown all the nodes currently part of the cluster, pick one of them, then follow the steps [here](https://github.com/lxc/lxd/blob/master/doc/clustering.md#disaster-recovery), and finally force-remove and re-join the remaining nodes.

**Comment by nniehoff** [comment]
@freeekanayaka thanks for the help.  This solution sounds drastic to me especially since I have containers running on this cluster, and if I had say 100 nodes in my cluster instead of 3 I would basically have to rebuild the cluster? 

> That might be due to some issue that occurred the very first time you removed 10.12.38.31, do you recall noticing anything like that?

No, I don't, it seemed pretty straight forward.  Although it is possible in all of my testing/troubleshooting of this I made things worse.

> I seem to remember that there were a few issues reported when using LXD clustering with MAAS, because nodes might end up being added and/or removed concurrently and that's probably not something we handle quite well at the moment.

Good to know.  I'm using MAAS only to deploy the machines.  Currently, I am clustering lxd by hand so I likely to them serially, although again I've been doing a lot of troubleshooting, it's possible I was building the .40 system and coincidentally ended up doing them concurrently but I'll keep this in mind.

It sounds like the best course of action is to essentially follow the disaster recovery procedures and rebuild my cluster.  My question is if I have running containers across the nodes, how will those be impacted.  If I remove all of the nodes from the cluster and re-add them AIUI the containers that were on that node will no longer exist.  Is that correct?  Would something like LXD import help me here?  Would I be better off to stop the running containers, move them all to say node2, run the recover from quorum lost on that node, then remove and re-add the other nodes, migrating containers back as I add them?  @stgraber thoughts?

**Comment by freeekanayaka** [comment]
> @freeekanayaka thanks for the help. This solution sounds drastic to me especially since I have containers running on this cluster, and if I had say 100 nodes in my cluster instead of 3 I would basically have to rebuild the cluster?

This disaster recovery sequence was not meant for this particular situation. But yes, I agree we might need to improve it so it can handle also situations like this more easily.

I'd say the first thing though would be to understand how the problem occurred. Probably we'd need to run more serious QA around clustering+MAAS, since afaik it's a scenario we don't exercise much or hear much about from users.

**Comment by nniehoff** [comment]
> I'd say the first thing though would be to understand how the problem occurred. Probably we'd need to run more serious QA around clustering+MAAS, since afaik it's a scenario we don't exercise much or hear much about from users.

I would say the most likely scenario here is I accidentally tried to add .31 and .40 at the same time.  I can't say for sure as I've been doing a lot of troubleshooting, luckily this is my lab and it's been a good lxd troubleshooting learning experience for me.  I would say I doubt this has anything to do with MAAS as I am using MAAS only to deploy the OS then by hand I'm installing lxd and clustering.  Although I can see how this would be an issue if it were part of my automation.  Which I will have to figure out something in my automation to handle the concurrent joins, but I'll figure something out.

**Comment by freeekanayaka** [comment]
> I would say the most likely scenario here is I accidentally tried to add .31 and .40 at the same time.

If you have time to test concurrent joins and check if you can confirm the issue can be in fact triggered that way, we might try to see if there's something reasonable we can do on our side to fix this.

**Comment by nniehoff** [comment]
Ok I moved all of the containers to node2.  I then stopped lxd, and verified it was down with ps | grep lx nothing returned.  When I try to run recover-from-quorum-loss I get:

```
root@node2:~# lxd cluster recover-from-quorum-loss
Error: The LXD daemon is running, please stop it first.
```

Debug output: https://pastebin.canonical.com/p/ZxKCTbkhPb/
Logs: https://pastebin.canonical.com/p/VttzTrhrGC/

**Comment by stgraber** [comment]
@freeekanayaka ah yeah, concurrent joins is something we should definitely test and if broken, fix.
I didn't see this failing much in the past when creating a 50 nodes cluster with all nodes installing around the same time, but it may just have been luck.

**Comment by freeekanayaka** [comment]
> Ok I moved all of the containers to node2. I then stopped lxd, and verified it was down with ps | grep lx nothing returned. When I try to run recover-from-quorum-loss I get:
> 
> ```
> root@node2:~# lxd cluster recover-from-quorum-loss
> Error: The LXD daemon is running, please stop it first.
> ```
> 
> Debug output: https://pastebin.canonical.com/p/ZxKCTbkhPb/

This debug output shows that `lxd cluster recover-from-quorum-loss` is able to connect to the LXD daemon process via Unix socket and the process sends back a reply.

You probably still have socket activation via systemd turned on, so even if the process is not running when you launch the command, it will be started as soon as you connect to the Unix socket.

Please try:

```
sudo systemctl stop snap.lxd.daemon.service
sudo systemctl stop snap.lxd.daemon.unix.socket
```

**Comment by nniehoff** [comment]
@freeekanayaka thanks I didn't see the socket.  The recover-from-quorum-loss procedure worked.  I think we are good to close this issue thanks for your help.
