### ISSUE TITLE
lxd crashes and no longer starts when disk out of space

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#7101]
My disk got full after trying to create an image of a large container:

- root filesystem is 20 GB in size
- lxd storage is several terabytes in size, in /data/lxd
- an attempt to create an image of a large container created a huge image file in /var/snap/lxd/common/lxd/images/lxd_build_205173754, which filled the root filesystem 100%

After this, lxc command fails:

# lxc list
Error: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused

lxd log:

t=2020-03-29T01:37:36+0000 lvl=info msg="Initializing local database" 
t=2020-03-29T01:37:36+0000 lvl=eror msg="Failed to start the daemon: Failed to start dqlite server: raft_start(): " 
t=2020-03-29T01:37:36+0000 lvl=info msg="Starting shutdown sequence" 

After releasing some space on the rootfs, lxd no longer starts.

**Comment by stgraber** [comment]
Can you try `sudo lxd --debug --group lxd`?

**Comment by tchwpkgorg** [comment]
```
# lxd --debug --group lxd
DBUG[03-29|05:27:47] Connecting to a local LXD over a Unix socket 
DBUG[03-29|05:27:47] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
INFO[03-29|05:27:47] LXD 3.23 is starting in normal mode      path=/var/snap/lxd/common/lxd
INFO[03-29|05:27:47] Kernel uid/gid map: 
INFO[03-29|05:27:47]  - u 0 0 4294967295 
INFO[03-29|05:27:47]  - g 0 0 4294967295 
INFO[03-29|05:27:47] Configured LXD uid/gid map: 
INFO[03-29|05:27:47]  - u 0 1000000 1000000000 
INFO[03-29|05:27:47]  - g 0 1000000 1000000000 
INFO[03-29|05:27:47] Kernel features: 
INFO[03-29|05:27:47]  - netnsid-based network retrieval: yes 
INFO[03-29|05:27:47]  - uevent injection: yes 
INFO[03-29|05:27:47]  - seccomp listener: yes 
INFO[03-29|05:27:47]  - seccomp listener continue syscalls: yes 
INFO[03-29|05:27:47]  - unprivileged file capabilities: yes 
INFO[03-29|05:27:47]  - cgroup layout: hybrid 
WARN[03-29|05:27:47]  - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored 
WARN[03-29|05:27:47]  - Couldn't find the CGroup memory swap accounting, swap limits will be ignored 
INFO[03-29|05:27:47]  - shiftfs support: no 
INFO[03-29|05:27:47] Initializing local database 
DBUG[03-29|05:27:47] Initializing database gateway 
DBUG[03-29|05:27:47] Start database node                      id=1 address= role=voter
EROR[03-29|05:27:48] Failed to start the daemon: Failed to start dqlite server: raft_start():  
INFO[03-29|05:27:48] Starting shutdown sequence 
DBUG[03-29|05:27:48] Not unmounting temporary filesystems (containers are still running) 
Error: Failed to start dqlite server: raft_start(): 
```

**Comment by stgraber** [comment]
Can you list the content of /var/snap/lxd/common/lxd/database/global/ ?

**Comment by tchwpkgorg** [comment]
I did the following to fix:

```
mv /var/snap/lxd/common/lxd/database/global /var/snap/lxd/common/lxd/database/global.corrupt
mv /var/snap/lxd/common/lxd/database/global.bak /var/snap/lxd/common/lxd/database/global
```

"global.bak" had quite an old timestamp (a week or two), but it worked after that.

For the record:

```
# ls /var/snap/lxd/common/lxd/database/global.corrupt/ -l
total 120872
-rw------- 1 root root 8388176 Mar 27 12:50 0000000004058544-0000000004059336
-rw------- 1 root root 8376656 Mar 27 13:52 0000000004059337-0000000004060140
-rw------- 1 root root 8383976 Mar 27 14:54 0000000004060141-0000000004060932
-rw------- 1 root root 8381408 Mar 27 15:56 0000000004060933-0000000004061745
-rw------- 1 root root 8385584 Mar 27 17:56 0000000004061746-0000000004062559
-rw------- 1 root root 8381408 Mar 27 18:58 0000000004062560-0000000004063372
-rw------- 1 root root 8377304 Mar 27 20:00 0000000004063373-0000000004064185
-rw------- 1 root root 8381408 Mar 27 21:02 0000000004064186-0000000004064998
-rw------- 1 root root 8377304 Mar 27 22:04 0000000004064999-0000000004065811
-rw------- 1 root root 8381408 Mar 28 00:04 0000000004065812-0000000004066624
-rw------- 1 root root 8377304 Mar 28 01:06 0000000004066625-0000000004067437
-rw------- 1 root root 8380976 Mar 28 02:08 0000000004067438-0000000004068244
-rw------- 1 root root 8381408 Mar 28 03:10 0000000004068245-0000000004069057
-rw------- 1 root root 8377304 Mar 28 03:15 0000000004069058-0000000004069870
-rw------- 1 root root  786432 Mar 29 01:34 db.bin
-rw------- 1 root root   32768 Aug 16  2018 db.bin-shm
-rw------- 1 root root 1326672 Mar 29 01:34 db.bin-wal
-rw------- 1 root root      32 Dec  2 23:04 metadata1
-rw------- 1 root root      32 Dec  2 23:04 metadata2
-rw------- 1 root root  971904 Mar 27 23:04 snapshot-24-4066156-43822238
-rw------- 1 root root      56 Mar 27 23:04 snapshot-24-4066156-43822238.meta
-rw------- 1 root root 3258504 Mar 28 00:07 snapshot-24-4067180-47621154
-rw------- 1 root root      56 Mar 28 00:07 snapshot-24-4067180-47621154.meta
-rw------- 1 root root       0 Mar 28 02:08 snapshot-24-4068245-54885408
-rw------- 1 root root      56 Mar 28 02:08 snapshot-24-4068245-54885408.meta
```

Still, the bug report is more on "LXD should have some mechanism preventing database corruption on disk full", rather than "how do I recover from this situation".

**Comment by stgraber** [comment]
You didn't quite need that, removing the last segment should have been sufficient (`0000000004069058-0000000004069870`).

We actually do have testing specifically for running out of disk space, so you must have hit a particular corner case of this.

Maybe @freeekanayaka can look into this.

Any chance you can e-mail the `global.corrupt` directory as a tarball to stgraber at ubuntu dot com?

**Comment by tchwpkgorg** [comment]
Mailed.

As for this issue:

> an attempt to create an image of a large container created a huge image file in /var/snap
> /lxd/common/lxd/images/lxd_build_205173754, which filled the root filesystem 100%

Is there any storage setting for it? Or one still needs to play with bind mounts?

**Comment by stgraber** [comment]
There is a setting for it, you can move images and backups onto storage volumes now. Look at the server settings in the documentation.
I think it's something like 'storage.images_volume"

**Comment by freeekanayaka** [comment]
@tchwpkgorg thanks for sending the database.

After inspection it turns out that it's indeed a corner case that we don't quite handle, as @stgraber hinted.

The last snapshot was empty (presumably because an attempt to take it was performed when the disk was full).

In this specific case, removing the last snapshot:

```
rm ./database/global/snapshot-24-4068245-54885408
rm ./database/global/snapshot-24-4068245-54885408.meta
```

(instead of removing the last segment) fully recovers the database with no data loss.

I'll look at how to fix this in the C raft library.

**Comment by stgraber** [comment]
@freeekanayaka did any fix for this made it in raft?

**Comment by stgraber** [comment]
Opened a bug over at raft, closing the LXD side of it.
