### ISSUE TITLE
"lxc info <container>" output is almost completely yaml format, but not quite.

### ISSUE THREAD

**Issue by craigphicks** [lxc/lxd#7103]
# Required information

 * Distribution: 
ubuntu
 * Distribution version:
18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

config:
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
  <omitted>
  certificate_fingerprint: 36112b175655b6c64de6b327faa5e4ce9dc9f565518a183b12cb02cb1d41cd3d
  driver: lxc
  driver_version: 4.0.0
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 4.18.0-18-generic
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: ub18
  server_pid: 1996
  server_version: "3.23"
  storage: dir
  storage_version: "1"

# Issue description

The CLI command

```
lxc info [name of container instance] 
```

outputs nearly *yaml* but not quite *yaml* format information.  It would be really useful to have it in *yaml* format.

One case example:

```
 $ lxc info ub18-1
Name: ub18-1
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/03/28 22:32 UTC
Status: Running
Type: container
Profiles: default
Pid: 2270
Ips:
  eth0:	inet	10.64.64.239	veth48620580
  eth0:	inet6	fe80::216:3eff:fe07:7670	veth48620580
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 24
  CPU usage:
    CPU usage (in seconds): 21
  Memory usage:
    Memory (current): 418.61MB
  Network usage:
    eth0:
      Bytes received: 29.48MB
      Bytes sent: 245.17kB
      Packets received: 5449
      Packets sent: 3403
    lo:
      Bytes received: 3.62kB
      Bytes sent: 3.62kB
      Packets received: 40
      Packets sent: 40
```
 
The only non-*yaml* is in the following  lines:
```
  eth0:	inet	10.64.64.239	veth48620580
  eth0:	inet6	fe80::216:3eff:fe07:7670	veth48620580
  lo:	inet	127.0.0.1
  lo:	inet6	::1
```
which contain tabs on each line (tabs not allowed in *yaml*) and which use the same keyd *eth0* and *lo* twice, causing most parsers to overwrite the info for the first line containing the ip4 address into, perhaps the most useful information of all, after the name.

**Comment by stgraber** [comment]
Yeah, it's not meant to be YAML, I actually have planned changes to make it significantly less YAML-like.

Use `lxc list NAME --format=yaml` if you want the same raw data in actual stable YAML format.

**Comment by craigphicks** [comment]
Thanks @stgraber !
