### ISSUE TITLE
Restrict valid container/server config keys

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#712]
Instead of allowing everything, let's store the list of valid config keys and validate.

The only user defined keys care against containers in the "user" namespace, everything else should be restricted to the keys we know and use.

**Comment by tych0** [comment]
On Tue, May 26, 2015 at 04:10:29PM -0700, Stéphane Graber wrote:
> Instead of allowing everything, let's store the list of valid config keys and validate.
> 
> The only user defined keys care against containers in the "user" namespace, everything else should be restricted to the keys we know and use.

Don't we do this in ValidContainerConfigKey? Perhaps it's just not
getting called somewhere?

**Comment by stgraber** [comment]
At least in the server case it's not since the testsuite sets an invalid key.

**Comment by tych0** [comment]
On Tue, May 26, 2015 at 04:27:38PM -0700, Stéphane Graber wrote:
> At least in the server case it's not since the testsuite sets an invalid key.

Ah, ok. I think it should work (i.e. fail) in the container case, but
I haven't looked at the new server code.

**Comment by stgraber** [comment]
Done
