### ISSUE TITLE
IPVLAN with (multple/single) tagged VLAN(s) issue

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#7123]
* Distribution: Ubuntu
 * Distribution version: 19.10
 * Kernel version: 5.3.0-40-generic
 * LXC version: 3.2.1
 * LXD version: 3.23
 * Storage backend in use: Dir

Not sure that this is actual issue with LXD or LXC itself, betting on LXC.

So what works as expected:
 - network at hypervisor node has single VLAN what is configured as `Untagged`: `eno1` interface
 - `eno1` is parent NIC for container `test1` in `ipvlan` mode
 - container `test1` has IP of `IP1`
 - **after container `test1` starts we can see that `IP1/32` route is created at `lo` interface**
 - container `test1` has internet connectivity 

Things go wrong at this point:
 - adding new VLAN in tagged mode, `trunk` port config on HW switch port
 - creating `Untagged` interface using linux with `eno1` as parent: `vlan101@eno1`
 - `vlan101` is parent NIC for container `test2` in `ipvlan` mode
 - container `test2` has IP of `IP2`
 - **after container `test1` starts we can see that `IP1/32` route is created at `lo` interface**
 - container `test2` has **NO** internet connectivity 
 - **running this command fixes internet connectivity** for container `test2`: `ip route add local IP2/32 dev vlan101`

Adding this route above tells kernel to enable ProxyARP for this specific IP for container.

Ok, so at this point I was thinking that somehow this tagged/untagged setup confused kernel.
So I decided to create two VLAN interfaces with tagged VLANS: `vlan100@eno1`, `vlan101@eno1`.
Did a similar setup, cleared ARP cache at gateway router, no network on both containers.

**Adding local route** for both `IP1` and `IP2` instantaneously **fixes ProxyARP** and network connectivity.

P.S. Please do not try to enable `proxy_arp_pvlan`, this sysctl tunable does not respect routes as regular `proxy_arp`, it will do ProxyARP for **all** IPs.

@tomponline Can you please look at this, in the initial implementation of ipvlan patch for LXD https://github.com/lxc/lxd/pull/5182, routes where added to local routing table, VLAN(s) setup was working then.

**Comment by tomponline** [comment]
@s3rj1k thanks for your detailed report.

So the `ipvlan` nic type should add a static route on the host for the container's IPs, but rather than using a `local` route it instead points it to the `lo` device on the host.

Example:

```
lxc init ubuntu:18.04 c1
lxc config device add c1 eth0 none # Skips netplan configured for DHCP eth0
lxc config device add c1 eth1 nic nictype=ipvlan name=eth1 parent=enp3s0 ipv4.address=192.168.1.201
lxc start c1
```

```
ip r
192.168.1.201 dev lo scope link 
```

Can you advise whether you are seeing static routes created for your container's IPs pointing at the `lo` interface?

The reason I went with this approach, rather than `local` routes is that with `local` routes if the container is stopped for some reason and the route on the host is left behind, then it has the undesired behaviour of making the host respond to those IPs (potentially exposing the host's services to the wider network on another potentially unfirewalled IP). With routing to the `lo` interface, it was sufficient to trigger the kernel's proxy arp, and when the container is running the `ipvlan` layer takes the traffic before it hits the host's routing table (with the effect of not using the static route), and if the container is stopped and for some reason the static route is left, then routing to the `lo` interface with a non-bounded IP will just cause the host to reject the packets.

**Comment by s3rj1k** [comment]
@tomponline Yes I am seeing routes for container IPs on `lo` interface.
Why not to delete those routes when container stops and re-add them on start?

**Comment by tomponline** [comment]
@s3rj1k they are deleted normally, it was a safety feature in case they are left around for some unexpected reason.

With the container started, please can you provide output of on host:

```
ip a
ip r
ip neigh show proxy
```

Thanks

**Comment by s3rj1k** [comment]
@tomponline Sorry, had to revert changes, I did a setup on production server.

`ip neigh` contained all relevant container IPs.

also I did policy routing for 2 VLANs, the one that `ip rule show` has, I can provide example configs for systemd-networked for this setup.

Please not that `netplan` config would not work for this setup, it lacks 2 major options in advanced routing.

**Comment by s3rj1k** [comment]
@tomponline I am curious, is `nictype: routed` has similar issue?

**Comment by tomponline** [comment]
@s3rj1k im not sure, although because with `routed` there is a 'proper' veth interface on the host side, we do add a static route to the container's IP via the container's host-side veth interface. So in that respect it is not a 'trick' to activate proxy ARP/NDP, but in fact a required static route to direct traffic.

**Comment by s3rj1k** [comment]
@tomponline So if routed is added to veth interface this shouldn't be a problem for `routed` type.

Where you able to replicated the issue with `ipvlan`?

**Comment by s3rj1k** [comment]
Similar issue with `nictype: routed` https://github.com/lxc/lxd/issues/7152

**Comment by tomponline** [comment]
@s3rj1k not yet, I need to spend some time trying to replicate it by first setting up a trunked VLAN setup locally, as I do not have one running normally.

**Comment by tomponline** [comment]
Tested two containers running with an IPVLAN interface each, connected to two different VLANs over same trunk port.

LXD host trunk port and 2 VLAN interfaces (100 and 101):

```
10: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 6c:b3:11:1c:09:52 brd ff:ff:ff:ff:ff:ff
19: enp4s0f0.100@enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 6c:b3:11:1c:09:52 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.2/24 scope global enp4s0f0.100
       valid_lft forever preferred_lft forever
    inet6 fe80::6eb3:11ff:fe1c:952/64 scope link 
       valid_lft forever preferred_lft forever
20: enp4s0f0.101@enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 6c:b3:11:1c:09:52 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.2/24 scope global enp4s0f0.101
       valid_lft forever preferred_lft forever
    inet6 fe80::6eb3:11ff:fe1c:952/64 scope link 
       valid_lft forever preferred_lft forever
```

Two containers:

```
lxc init ubuntu:18.04 c1 # Disable netplan for eth0
lxc init ubuntu:18.04 c2 # Disable netplan for eth0
lxc config device add c1 eth0 nic nictype=ipvlan name=eth0 parent=enp4s0f0 vlan=100 ipv4.address=10.0.0.3
lxc config device add c2 eth0 nic nictype=ipvlan name=eth0 parent=enp4s0f0 vlan=101 ipv4.address=10.0.1.3
lxc start c1 c2
lxc ls 
+------+---------+-----------------+------+-----------+-----------+
| NAME |  STATE  |      IPV4       | IPV6 |   TYPE    | SNAPSHOTS |
+------+---------+-----------------+------+-----------+-----------+
| c1   | RUNNING | 10.0.0.3 (eth0) |      | CONTAINER | 0         |
+------+---------+-----------------+------+-----------+-----------+
| c2   | RUNNING | 10.0.1.3 (eth1) |      | CONTAINER | 0         |
+------+---------+-----------------+------+-----------+-----------+
```

```
ip neigh show proxy
10.0.1.3 dev enp4s0f0.101  proxy
10.0.0.3 dev enp4s0f0.100  proxy
```

```
ip r
10.0.0.3 dev lo scope link 
10.0.1.3 dev lo scope link 
10.0.0.0/24 dev enp4s0f0.100 proto kernel scope link src 10.0.0.2 
10.0.1.0/24 dev enp4s0f0.101 proto kernel scope link src 10.0.1.2 
```

On another host on the connect with a trunk port:

```
3: eth0.100@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 28:92:4a:32:0c:e2 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.1/24 scope global eth0.100
       valid_lft forever preferred_lft forever
    inet6 fe80::2a92:4aff:fe32:ce2/64 scope link 
       valid_lft forever preferred_lft forever
4: eth0.101@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 28:92:4a:32:0c:e2 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.1/24 scope global eth0.101
       valid_lft forever preferred_lft forever
    inet6 fe80::2a92:4aff:fe32:ce2/64 scope link 
       valid_lft forever preferred_lft forever
```

```
ip r
10.0.0.0/24 dev eth0.100 scope link  src 10.0.0.1 
10.0.1.0/24 dev eth0.101 scope link  src 10.0.1.1 
```

Tests from remote host:

```
ping 10.0.0.3 -c 3
PING 10.0.0.3 (10.0.0.3): 56 data bytes
64 bytes from 10.0.0.3: seq=0 ttl=63 time=0.374 ms
64 bytes from 10.0.0.3: seq=1 ttl=63 time=0.281 ms
64 bytes from 10.0.0.3: seq=2 ttl=63 time=0.341 ms

--- 10.0.0.3 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.281/0.332/0.374 ms
```

```
ping 10.0.1.3 -c 3
PING 10.0.1.3 (10.0.1.3): 56 data bytes
64 bytes from 10.0.1.3: seq=0 ttl=63 time=0.361 ms
64 bytes from 10.0.1.3: seq=1 ttl=63 time=0.283 ms
64 bytes from 10.0.1.3: seq=2 ttl=63 time=0.339 ms

--- 10.0.1.3 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.283/0.327/0.361 ms
```

Seems to work OK without local routes (just the static routes to lo interface to trigger ARP proxy).

**Comment by s3rj1k** [comment]
@tomponline Same issue as with ticked about routed setup, please do test with public IPs.

I've prepared a lab for this, you can check it out and see what I am talking about.

**Comment by s3rj1k** [comment]
Also you do not have policy routing set, refer to other issue, I tried to explain why it is needed as best as I can.

**Comment by s3rj1k** [comment]
I would hope for native fix for this issue, after all this effort to bring `ipvlan` support I would hate to fix this route problem by write custom lxc hook, thanks.

**Comment by tomponline** [comment]
@s3rj1k ok so to summarise, proxy arp is not working when using policy routing?

**Comment by s3rj1k** [comment]
@tomponline I actually did not check without policy routing, as this setup is incorrect, I can check this now and report in few minutes.

**Comment by tomponline** [comment]
@s3rj1k also are you able to test whether adding static routes to the gateway back to the container IPs (down the correct vlan interface) works with policy routing in place. This would effectively bypass the need for proxy ARP and just deliver the packets directly to the interface.

**Comment by s3rj1k** [comment]
@tomponline As expected, without policy routing same effect, network does not work for CTs that have none default network.

Did you mean adding static ARP record?

**Comment by tomponline** [comment]
@s3rj1k im still a bit confused, I expect the cross-subnet pinging to not work, but normal same-subnet pinging works here in my local setup. Is that what you tested (lets discount cross-subnet pinging for now). Can you clarify what you tested when it doesn't work? Thanks

Regarding the static routes, I meant add a static route on the gateway for the container's IP destined for the IP of the host in the VLAN interface. This way packets should flow towards the host's VLAN interface without needing proxy ARP. It would be interesting to see if then ipvlan device picks them up and delivers them to the container (which it should).

**Comment by s3rj1k** [comment]
@tomponline I was testing network connectivity, pinging CT from some remote host and pinging 1.1.1.1 from CT.

Adding static ARP records on GW enables network connectivity, bypasses proxy_arp, but this is obviously not a solution. :)

**Comment by s3rj1k** [comment]
@tomponline 

adding static route from border gateway (hardware box) to VLAN interface on LXD node as expected creates network connectivity for CTs in question, but this solution can not be used in production environment.

manually adding static routes on border gateway for a fleet of LXD servers is like using /etc/hosts as a DNS resolver

**Comment by tomponline** [comment]
@s3rj1k out of interest, have you tried adding a static route to the lo interface for the container's IP in the additional routing tables,

e.g.

```
ip r list table 4220
10.0.1.3 dev lo scope link (Im not sure what the container's IP is, but you get my idea).
default via 192.168.127.65 dev vlan220
```

In case the proxy arp logic is looking at a different routing table based on the inbound rules.

**Comment by s3rj1k** [comment]
@tomponline 
```
$ ip r list table 4220
default via 192.168.127.65 dev vlan220
192.168.127.75 dev lo scope link
```

Just tried that, appears to also work.

**Comment by tomponline** [comment]
Excellent, thats our way forward then. Potentially a config key like vlan, that assigns the containers nic to a routing table id

**Comment by s3rj1k** [comment]
@tomponline I am all for it as long as it will work with preconfigured VLAN interface and policy routing rules.

I can test this changes locally, I assume that this will be done in LXD only?

**Comment by s3rj1k** [comment]
@tomponline Any updates on this?

**Comment by tomponline** [comment]
@s3rj1k no change since last week as have been on Easter break. Will pick this up in due course.

**Comment by tomponline** [comment]
I've re-created this issue and have added PR to fix it. Interestingly the static route to the `lo` device was only needed to be added to the custom routing table to trigger proxy ARP for IPv4. IPv6 addresses seemed to trigger proxy NDP without needing it. However what apparently happens is that proxy NDP sees the wider /64 route I added manually as sufficient to activate the proxy NDP response. 

For `routed` NIC types the static IPv6 route is absolutely necessary, even though it is not needed to trigger proxy NDP, as it is still needed to allow the the traffic to route to the veth interface.

However for `ipvlan` NIC types I've still added static routes to the `lo` interface, even for ipv6 addresses, as it will allow proxy NDP to be activated in cases where the custom routing table doesn't contain a wider route for the local subnet, and it means the ipv4 and ipv6 behaviour is consistent.

**Comment by s3rj1k** [comment]
@tomponline Waiting this in master to confirm
