### ISSUE TITLE
Problem with mount of a loopback device during LXD startup

### ISSUE THREAD

**Issue by TheCoder4eu** [lxc/lxd#7125]
Good evening,
unfortunately my server has problems starting LXD, I am unsure if it is a side effect of an upgrade to 4.0.0 but it seems unable to mount a dev/loop8 at some point (the BTRFS filesistem is ok).

This are the relevant informations, I suppose this might be a bug since a invalid argument is mentioned: 

root@LXDH03 ~ # lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

root@LXDH03 ~ # lxd version
4.0.0
root@LXDH03 ~ # lxd --debug -v --group lxd
INFO[04-03|00:36:53] LXD 4.0.0 is starting in normal mode     path=/var/snap/lxd/common/lxd
INFO[04-03|00:36:53] Kernel uid/gid map: 
INFO[04-03|00:36:53]  - u 0 0 4294967295 
INFO[04-03|00:36:53]  - g 0 0 4294967295 
INFO[04-03|00:36:53] Configured LXD uid/gid map: 
INFO[04-03|00:36:53]  - u 0 1000000 1000000000 
INFO[04-03|00:36:53]  - g 0 1000000 1000000000 
INFO[04-03|00:36:53] Kernel features: 
INFO[04-03|00:36:53]  - netnsid-based network retrieval: yes 
INFO[04-03|00:36:53]  - uevent injection: yes 
INFO[04-03|00:36:53]  - seccomp listener: yes 
INFO[04-03|00:36:53]  - seccomp listener continue syscalls: yes 
INFO[04-03|00:36:53]  - unprivileged file capabilities: yes 
INFO[04-03|00:36:53]  - cgroup layout: hybrid 
WARN[04-03|00:36:53]  - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored 
WARN[04-03|00:36:53]  - Couldn't find the CGroup memory swap accounting, swap limits will be ignored 
INFO[04-03|00:36:53]  - shiftfs support: yes 
INFO[04-03|00:36:53] Initializing local database 
DBUG[04-03|00:36:53] Initializing database gateway 
DBUG[04-03|00:36:53] Start database node                      id=1 address= role=voter
DBUG[04-03|00:36:53] Detected stale unix socket, deleting 
INFO[04-03|00:36:53] Starting /dev/lxd handler: 
INFO[04-03|00:36:53]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[04-03|00:36:53] REST API daemon: 
INFO[04-03|00:36:53]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[04-03|00:36:53] Initializing global database 
DBUG[04-03|00:36:53] Dqlite: connected address=1 attempt=0 
DBUG[04-03|00:36:53] Firewall xtables detected iptables is in use 
INFO[04-03|00:36:53] Firewall loaded driver "xtables" 
INFO[04-03|00:36:53] Initializing storage pools 
DBUG[04-03|00:36:53] Initializing and checking storage pool "lxdpool" 
DBUG[04-03|00:36:53] Mount started                            driver=btrfs pool=lxdpool
DBUG[04-03|00:37:04] Mount finished                           driver=btrfs pool=lxdpool
EROR[04-03|00:37:04] Failed to start the daemon: Failed initializing storage pool "lxdpool": Failed to mount '/dev/loop8' on '/var/snap/lxd/common/lxd/storage-pools/lxdpool': invalid argument 
INFO[04-03|00:37:04] Starting shutdown sequence 
INFO[04-03|00:37:04] Stopping REST API handler: 
INFO[04-03|00:37:04]  - closing socket                        socket=/var/snap/lxd/common/lxd/unix.socket
INFO[04-03|00:37:04] Stopping /dev/lxd handler: 
INFO[04-03|00:37:04]  - closing socket                        socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[04-03|00:37:04] Closing the database 
DBUG[04-03|00:37:04] Stop database gateway 
INFO[04-03|00:37:05] Unmounting temporary filesystems 
INFO[04-03|00:37:05] Done unmounting temporary filesystems 
Error: Failed initializing storage pool "lxdpool": Failed to mount '/dev/loop8' on '/var/snap/lxd/common/lxd/storage-pools/lxdpool': invalid argument

root@LXDH03 ~ # ls -al /var/snap/lxd/common/lxd/storage-pools/lxdpool
total 0
drwx--x--x 1 root root  0 Jun 16  2018 .
drwx--x--x 1 root root 32 Jun 16  2018 ..

Hope this information is sufficient to help me.
Thank you in advance for your support!

**Comment by stgraber** [comment]
Can you show `ls -lh /var/snap/lxd/common/lxd/disks/`?

**Comment by TheCoder4eu** [comment]
Hi Stéphane,
i get this:
root@LXDH03 ~ # ls -lh /var/snap/lxd/common/lxd/disks/
total 1009M
-rw------- 1 root root 1.0G Jun 19  2019 lxdpool.img

**Comment by stgraber** [comment]
Ok,  what happens if you do `mount -o loop /var/snap/lxd/common/disks/lxdpool.img /mnt` ?

**Comment by TheCoder4eu** [comment]
I get:
root@LXDH03 ~ # mount -v -o loop /var/snap/lxd/common/disks/lxdpool.img /mnt
mount: /mnt: failed to setup loop device for /var/snap/lxd/common/disks/lxdpool.img.

**Comment by TheCoder4eu** [comment]
Also:
root@LXDH03 ~ # losetup
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                        DIO LOG-SEC
/dev/loop1         0      0         1  1 /var/lib/snapd/snaps/core_8935.snap                0     512
/dev/loop6         0      0         1  1 /var/lib/snapd/snaps/lxd_14194.snap                0     512
/dev/loop4         0      0         1  1 /var/lib/snapd/snaps/core18_1668.snap              0     512
/dev/loop2         0      0         1  1 /var/lib/snapd/snaps/core_8689.snap                0     512
/dev/loop0         0      0         1  1 /var/lib/snapd/snaps/core18_1705.snap              0     512
/dev/loop7         0      0         1  1 /var/lib/snapd/snaps/canonical-livepatch_94.snap   0     512
/dev/loop5         0      0         1  1 /var/lib/snapd/snaps/lxd_14133.snap                0     512
/dev/loop3         0      0         1  1 /var/lib/snapd/snaps/canonical-livepatch_95.snap   0     512

**Comment by stgraber** [comment]
Okay, so you're on a system with the old limit of 8 loop devices and they're currently all in use, causing this issue.

You could probably `mknod` a few more to get out of this.

**Comment by stgraber** [comment]
It's a bit odd though as 18.04 should have a working loop-control allowing for more of them to get created on demand...

**Comment by stgraber** [comment]
Closing as a plain mount call is failing too, so unrelated to LXD.
Is that a stock kernel?

**Comment by TheCoder4eu** [comment]
Thank you very much Stéphane,

> Okay, so you're on a system with the old limit of 8 loop devices and they're currently all in use, causing this issue.


strange since I see:
root@LXDH03 ~ # ls -al /dev/loop*
brw-rw---- 1 root disk  7,   0 Apr  3 00:21 /dev/loop0
brw-rw---- 1 root disk  7,   1 Apr  3 00:21 /dev/loop1
brw-rw---- 1 root disk  7,   2 Apr  3 00:21 /dev/loop2
brw-rw---- 1 root disk  7,   3 Apr  3 00:21 /dev/loop3
brw-rw---- 1 root disk  7,   4 Apr  3 00:21 /dev/loop4
brw-rw---- 1 root disk  7,   5 Apr  3 00:21 /dev/loop5
brw-rw---- 1 root disk  7,   6 Apr  3 00:21 /dev/loop6
brw-rw---- 1 root disk  7,   7 Apr  3 00:21 /dev/loop7
brw-rw---- 1 root disk  7,   8 Apr  3 08:27 /dev/loop8
crw-rw---- 1 root disk 10, 237 Apr  3 00:21 /dev/loop-control

so there should be a /dev/loop8 free to use but failing to mount but in LXD log we see:
Failed initializing storage pool "lxdpool": Failed to mount '/dev/loop8' on
The Kernel is HWE:
Linux LXDH03 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
yesterday I updated it and rebooted and I use Livepatch.

So you suggest I figure out how to mount manually the image on /dev/loop8 with losetup ?
I don't think it is possible the lxdpool image got corrupted, isn't it?

**Comment by TheCoder4eu** [comment]
I had two storage pools, can I get rid or avoid to load this problematic one and use only the second pool to be able to start LXD ?

**Comment by stgraber** [comment]
Not particularly easily. Can you look at `dmesg` after a startup failure?

**Comment by stgraber** [comment]
It may still be a corruption issue after all, if it is, hopefully that will show it.

**Comment by stgraber** [comment]
If it's corruption, then `btrfs check /var/snap/lxd/common/lxd/disks/lxdpool.img` could help figure out what's going on.
