### ISSUE TITLE
(Feature request) local repos for lxd

### ISSUE THREAD

**Issue by toby63** [lxc/lxd#7127]
**Problem:**
I am using many different containers on the same computers/servers/local network and most of them run the same OS (Debian in my case).
Now when I update them, each container connects to the internet and downloads the same packages.
I think that is unnecessary traffic and a waste of resources (because obviously the internet consumes a lot of energy).

**Solution:**
LXD could include an option for local repos from which all containers could download their updates from.
A concept could look like this:
1. Download package updates to local repo (could be a folder or a seperate container; maybe on a set schedule (like daily))
2. automatically add the local repo to a container (as a disk device or something else (like anetwork related solution))
3. Containers download updates

One more thought about the local repo:
It could be a copy of the complete repo of a distro, but that could be to big, so the alternative would be a program/script looking into the containers, which packages are installed, to only download and include those.

**Alternatives:**
- While some might say that there are other ways to achieve that, I would prefer a solution in lxd itself
- I am aware of the image auto update function ([image handling docs](https://lxd.readthedocs.io/en/latest/image-handling/)), but thats not the same, because the containers can be different from the (official) images and updating each image (that could be created from containers) would lead to the same problem.

**Comment by stgraber** [comment]
Not something that really makes sense to do at the LXD layer.

You should create a container that either runs some kind of proxy (look at squid-deb-proxy for example) or even has a full archive mirror of your distro, then configure your other containers to pull from that.

That's not really any different than what organizations do with their physical systems/VMs.
