### ISSUE TITLE
Image retrieval is too slow

### ISSUE THREAD

**Issue by smahi** [lxc/lxd#7136]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-21-generic
   * LXC version: 4.0.0
   * LXD version: 4.0.0
   * Storage backend in use: dir

# Issue description

Image retrieval is too slow even though the connection is good on my part.

# Steps to reproduce

 1. `$ lxc launch ubuntu:bionic`

```
Creating the instance
Retrieving image: rootfs: 3% (8.06kB/s) 
```

Is there an other way to download the image, for example using a download manager like `aria2` then import the downloaded image using `lxc` command.

**Comment by stgraber** [comment]
Does 'images:ubuntu/bionic/cloud' download faster?

**Comment by stgraber** [comment]
You can go and download the two files by hand and import with lxc image import as an alternative indeed.

**Comment by smahi** [comment]
@stgraber thank you for the reply
Where can i go to get these files and what are their names ?

**Comment by smahi** [comment]
@stgraber 
Yes `images:ubuntu/bionic/cloud` is faster

**Comment by stgraber** [comment]
You need a .squashfs and the matching .tar.xz for it.

You can manually find them at https://cloud-images.ubuntu.com

**Comment by stgraber** [comment]
Make sure to import as `lxc image import /path/to/lxd.tar.xz /path/to/img.squashfs` (tar.xz first)

**Comment by stgraber** [comment]
Closing as bad performance/rounting on cloud-images.ubuntu.com is sadly out of our control.

**Comment by smahi** [comment]
@stgraber thank you so much

**Comment by alialinx** [comment]
.
