### ISSUE TITLE
Error: Invalid devices: Invalid device configuration key for proxy: proxy_protocol

### ISSUE THREAD

**Issue by smahi** [lxc/lxd#7145]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04 
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.15.0-91-generic
   * LXC version: 3.0.3
   * LXD version: 3.0.3
   * Storage backend in use: btrfs

# Issue description

Can not set `proxy` device key `proxy_protocol` to true, i am getting the following error

`Error: Invalid devices: Invalid device configuration key for proxy: proxy_protocol`

# Steps to reproduce

 1. `lxc config device add  lrs proxy80 proxy listen=tcp:0.0.0.0:80 connect=tcp:127.0.0.1:80 proxy_protocol=true`

**Comment by stgraber** [comment]
You're on 3.0.3, this is a feature which was introduced in later releases.

**Comment by smahi** [comment]
@stgraber sorry i did not know.
Thank you for your help.
