### ISSUE TITLE
Nested VM can't start due to vhost-vsock issue

### ISSUE THREAD

**Issue by rafaeldtinoco** [lxc/lxd#7148]
# Required information

 * Distribution: Ubuntu Focal
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-18-generic
   * LXC version: latest
   * LXD version: 4.0.0 (rev: 14270)
   * Storage backend in use: ZFS

# Issue description

I'm creating a nested LXD environment to run virtual machines. It looks good until I tried to launch the VM - in the nested KVM guest - and received:

rafaeldtinoco@lxdexample:~$ lxc start focalvm
Error: Failed to run: modprobe vhost_vsock: modprobe: ERROR: could not insert 'vhost_vsock': Device or resource busy
Try `lxc info --show-log focalvm` for more info

rafaeldtinoco@lxdexample:~$ sudo modprobe vhost_vsock
modprobe: ERROR: could not insert 'vhost_vsock': Device or resource busy

# Steps to reproduce

 1. lxc init ubuntu-daily:focal lxdexample --vm
 2. Set cpu, memory and add a config disk
 3. Install LXD inside it and try to run a nested VM

# Information to attach

I believe vsock is broken in nested LXD VMs. I know VM feature is recent and being developed, don't want to rush things, just wanted to document.

**Comment by tomponline** [comment]
@rafaeldtinoco can you show the output of `lsmod | grep vsock` please, it may be there is a conflicting vsock module loaded already.

**Comment by stgraber** [comment]
So I'm not sure that we can actually nest vsock properly.

**Comment by brauner** [comment]
> So I'm not sure that we can actually nest vsock properly.

You likely want what's been merged in November:

```
commit 24df31f8d5be1b09f9e6c6d07ddfa96cbef1782b
Merge: 798a496bf425 ed8640a9612c
Author: David S. Miller <davem@davemloft.net>
Date:   Thu Nov 14 18:12:19 2019 -0800

    This series adds the multi-transports support to vsock, following
    this proposal: https://www.spinics.net/lists/netdev/msg575792.html

    With the multi-transports support, we can use VSOCK with nested VMs
    (using also different hypervisors) loading both guest->host and
    host->guest transports at the same time.
    Before this series, vmci_transport supported this behavior but only
    using VMware hypervisor on L0, L1, etc.
```

**Comment by stgraber** [comment]
Ah yeah, we'd indeed need that for nesting ^

@brauner is that a reasonably sized patch which we could convince @sforshee to include in the Ubuntu kernel?

**Comment by stgraber** [comment]
Closing because it's a kernel limitation.

**Comment by brauner** [comment]
> Ah yeah, we'd indeed need that for nesting ^
> 
> @brauner is that a reasonably sized patch which we could convince @sforshee to include in the Ubuntu kernel?

That's a pretty huge patch tbh.
