### ISSUE TITLE
Offer a way to sort "lxc list" numerically

### ISSUE THREAD

**Issue by zyga** [lxc/lxd#7149]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-91-generic
   * LXC version: 3.0.3
   * LXD version: 3.0.3
   * Storage backend in use: directory

# Issue description

I have a number of containers with a common prefix and a number, e.g. foo-42. I would love if `lxc list` sorted the list numerically, so that `foo-9` comes before `foo-10`

# Steps to reproduce
```
lxc launch ubuntu:18.04 foo-1
lxc launch ubuntu:18.04 foo-2
lxc launch ubuntu:18.04 foo-10
```
Running `lxc list` should show `foo-1`, `foo-2` and then `foo-10`. Currently it shows `foo-1`, `foo-10` and then `foo-2`.

# Information to attach
N/A

**Comment by stgraber** [comment]
@zyga do you know of a Go sorter which does that?

**Comment by zyga** [comment]
I do not. I think coreutils `sort` has `-n` with similar semantics though.

**Comment by stgraber** [comment]
https://stackoverflow.com/questions/18355338/alphanumeric-sorting-in-go looks like a good starting point. I'll play with integrating this with SortByName which we use for those columns already.

**Comment by stgraber** [comment]
```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc list foo
+--------+---------+------+------+-----------+-----------+
|  NAME  |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+--------+---------+------+------+-----------+-----------+
| foo-1  | STOPPED |      |      | CONTAINER | 0         |
+--------+---------+------+------+-----------+-----------+
| foo-2  | STOPPED |      |      | CONTAINER | 0         |
+--------+---------+------+------+-----------+-----------+
| foo-10 | STOPPED |      |      | CONTAINER | 0         |
+--------+---------+------+------+-----------+-----------+
```
