### ISSUE TITLE
off-line container creation fails with "Error: Configure instance: Failed to render instance metadata: Get container stated: allocating the container failed"

### ISSUE THREAD

**Issue by amd3963** [lxc/lxd#7161]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by amd3963** [comment]
Running on CentOS 7.7 (CentOS Linux release 7.7.1908 (Core))
The output of "lxc info"
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIB/zCCAYagAwIBAgIQMu/6Mxqmr4DILIaAScrx1jAKBggqhkjOPQQDAzAzMRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRMwEQYDVQQDDApyb290QHIxc3Yy
    MB4XDTIwMDQwNzIwNDg1OVoXDTMwMDQwNTIwNDg1OVowMzEcMBoGA1UEChMTbGlu
    dXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEByMXN2MjB2MBAGByqGSM49
    AgEGBSuBBAAiA2IABG3KHEbbwYvljdHFBzQu9cifW+g4SmIF7zK0LdolepTnsYiI
    b+fLwmlpozCWtUHtdEtzGRauWIyIbAW9xCRnil1eUTxmp8s79//oH9Icy0wOELjs
    oLboDXiovXiSvMNguqNfMF0wDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsG
    AQUFBwMBMAwGA1UdEwEB/wQCMAAwKAYDVR0RBCEwH4IFcjFzdjKHBH8AAAGHEAAA
    AAAAAAAAAAAAAAAAAAEwCgYIKoZIzj0EAwMDZwAwZAIwNYY5uTCOeUVdHDGj0nlt
    xqwxyECvXcdrfpo9vdKfxFA8eell1XvYedwwDNwnxbAwAjB0h9JgzYuvUWTs662x
    9EGdf4zwZyfFZPC1Gq10aCgFzswEodyjPvjb74ItRatTd70=
    -----END CERTIFICATE-----
  certificate_fingerprint: c5a8eaf39314bd88d2347dcca5a052745f88933a3818a565a570b7f717285460
  driver: lxc
  driver_version: 4.0.0
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 3.10.0-1062.18.1.el7.x86_64
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: r1sv2
  server_pid: 3581
  server_version: 4.0.0
  storage: btrfs
  storage_version: "4.4"
==================================================
We created our image with:   lxc image import --alias my-image3 /data/lxc/meta.tar.xz /data/lxc/rootfs.tar.xz
My metadata.yaml contents:
architecture: x86_64
creation_date: 1585812008
Image gets created, but container creation fails, command we run to create container:  lxc launch --verbose --debug my-image3 alextest2
WE ARE IN AN AIRGAPPED ENVIRONMENT, NO ACCESS TO THE INTERNET

**Comment by stgraber** [comment]
Error is coming from low level LXC, not from LXD.
Can you try: `lxc init test --empty` see if that also fails?

Where did LXD come from? snap, external RPM or hand built?

**Comment by amd3963** [comment]
# lxc init test --empty
Creating test
LXD came from using snap, we installed it using the following:

On a machine with internet access:
# snap download core
# snap download lxd

On off-line server:
# snap ack /data/lxd/core_8935.assert
# snap install /data/lxd/core_8935.snap
# snap ack /data/lxd/lxd_14270.assert
# snap install /data/lxd/lxd_14270.snap

**Comment by stgraber** [comment]
Ok and where did your image come from?

The fact that `lxc init --empty` succeeds when your image doesn't is a bit suspicious.

**Comment by stgraber** [comment]
Also check if you got lucky enough to get a `/var/snap/lxd/common/lxd/logs/alextest2/lxc.log` file.

**Comment by amd3963** [comment]
Sorry about the giant font earlier. :)
Got image from:  https://us.images.linuxcontainers.org/images/centos/7/amd64/default/20200402_07:08/
It did not have a metadata.yaml, so I created one with just 2 lines in it and re-created the tar.

We do not have the exact log file you listed above, we do have:
# pwd
/var/snap/lxd/common/lxd/logs
# ll
total 28
-rw-r--r-- 1 root root 5528 Apr  8 21:21 lxd.log
-rw-r--r-- 1 root root 9995 Apr  8 20:57 lxd.log.1
-rw-r--r-- 1 root root 1429 Apr  8 16:51 lxd.log.2.gz
drwxr-xr-x 2 root root 4096 Apr  8 21:00 test

**Comment by stgraber** [comment]
ah, that's probably the issue.

You want:
 - https://us.images.linuxcontainers.org/images/centos/7/amd64/default/20200402_07:08/lxd.tar.xz
 - https://us.images.linuxcontainers.org/images/centos/7/amd64/default/20200402_07:08/rootfs.squashfs

Download those two and then pass them as `lxc image import lxd.tar.xz rootfs.squashfs --alias blah`

You can also use the tar.xz for the rootfs if you prefer, both work, but squashfs tends to be faster to import.

**Comment by amd3963** [comment]
THANK YOU SO MUCH!!  That did it.
On a second note can you direct us to instructions to customize container disk size and memory and cpu?  If you prefer, I would gladly start a new issue thread.

Thanks again, you are my hero.

**Comment by stgraber** [comment]
For support questions https://discuss.linuxcontainers.org is usually a better spot.

For resource limits, your best bet is a custom profile that you can select at creation time or apply later, set `limits.cpu`, `limits.memory`, ...
