### ISSUE TITLE
Renaming an instance with a backup breaks backup API

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#7176]
If you do the following on LXD 4.0.0;

 - Create a container
 - Create a backup 
 - Rename container
 - Get `/instances/NEW_CONTAINER_NAME/backups`
    - This works fine shows the backups
 -  Get `/instances/NEW_CONTAINER_NAME/backups/BACKUP_NAME` 
     - Not found 

You have to rename the container back to its original name to access the backup info (just changing instance name in the URL doesn't work)

_Didnt test VM's_

**Comment by stgraber** [comment]
@monstermunchkin Can you fix this please?
