### ISSUE TITLE
No id remapping when changing idmap config on privileged containers

### ISSUE THREAD

**Issue by MemoWalk** [lxc/lxd#7179]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 LTS
 * The output of "lxc info"
   * Kernel version: 4.15.0-1079-oem
   * LXC version: lxc 3.0.3
   * LXD version: lxd 3.0.3 (lxd --version)
   * Storage backend in use: dir / storage_version "1"
   * config: {}

# Issue description

Not sure if this is an issue or intended. 

Intention: create shared device disk with read write between guest and host.
Issue: If I create a privileged container and then add the host user (!= root) via id remap, the container is /not/ remapping and in my case the folders I wanted to access are not remapped to my local user.

# Steps to reproduce

## 1) Create container > privileged=true > add id_remap > "fails"

All code is supposed to be run on host with user !=  root. These are the steps to reproduce to what I would refer to as an issue without further knowledge.

```
cd ~
mkdir ~/test/shared/ -p
touch ~/test/a-file.txt
echo "some info" >> ~/test/a-file.txt
id
: uid=1001(me) gid=1001(me) Gruppen(groups)=1001(me),...,129(lxd)
 ```

Create as privileged

```
lxc launch ubuntu:x test-1 -c security.privileged=true
lxc config show test-1 | grep privileged
:   security.privileged: "true"
```

add device

```
lxc config device add test-1 testdisk disk source=~/test/shared path=/home/ubuntu/new
: Gerät testdisk wurde zu test-1 hinzugefügt
: [[own translation] device testdisk has been added to test-1]
lxc exec test-1 -- sudo -iu ubuntu ls -l
: drwxr-xr-x 2 1001 1001 4096 Apr 13 06:08 new
```

This is obviously not writable from within lxc as the user ubuntu.

Setting options in subgid and subuid (I have already set this way before writing this post, so lxc restarts with these options have happened a number of times.)

```
cat /etc/subuid | grep lxd
: lxd:231072:65536
: lxd:1001:1
```

```
cat /etc/subgid | grep lxd
: lxd:231072:65536
: lxd:1001:1
```
remap

```
lxc config set test-1 raw.idmap "both 1001 1000"
lxc restart test-1
```

which yields no output. (my guess is, the bug seems to be hidden here)

```
lxc config show test-1 | grep raw.idmap
:  raw.idmap: both 1001 1000
```
but still:

```
lxc exec test-1 -- sudo -iu ubuntu ls -l
: drwxr-xr-x 2 1001 1001 4096 Apr 13 06:08 new
```
and I cannot write. See attachment test-1-log.log:

```
lxc info test-1 --show-log > test-1-log.log
lxc config show test-1 --expanded  > test-1-config.log
```

## 2) Create container > add id_remap > "works"

This one works as expected. Assume host settings as before.

```
lxc launch ubuntu:x test-2
lxc config device add test-2 testdisk disk source=~/test/shared path=/home/ubuntu/new
: Gerät testdisk wurde zu test-2 hinzugefügt
: [device testdisk has been added to test-2]
lxc exec test-2 -- sudo -iu ubuntu ls -l
: drwxr-xr-x 2 nobody nogroup 4096 Apr 13 06:08 new
lxc config set test-2 raw.idmap "both 1001 1000"
lxc restart test-2
: outputs something about remapping devices
lxc exec test-2 -- sudo -iu ubuntu ls -l
: drwxr-xr-x 2 ubuntu ubuntu 4096 Apr 13 06:08 new
```
and this works.

```
lxc info test-2 --show-log > test-2-log.log
lxc config show test-2 --expanded  > test-2-config.log
```
# Information to attach

- [test-1-log.log](https://github.com/lxc/lxd/files/4468292/test-1-log.log)
- [test-1-config.log](https://github.com/lxc/lxd/files/4468298/test-1-config.log)
- [test-2-log.log](https://github.com/lxc/lxd/files/4468318/test-2-log.log)
- [test-2-config.log](https://github.com/lxc/lxd/files/4468319/test-2-config.log)

**Comment by stgraber** [comment]
Privileged containers do not use the user namespace so cannot have uid/gid remapped.

**Comment by stgraber** [comment]
I think the only real action here is to update the documentation to make it clear than this only applies to unprivileged containers.
