### ISSUE TITLE
Provide virtuality on the host_info endpoint.

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#7188]
MAAS currently collects whether or not a machine is running in a container or is a virtual machine using systemd-detect-virt during commissioning. If this information is made available via the LXD API MAAS will be able to display this information for LXD Pods.

Note: Running systemd-detect-virt shows lxc whenever running in a Snap. LXD should only show true if the host operating system is running in a container or virtual machine.

**Comment by stgraber** [comment]
I'm not really sure why you care. For pods you already know their types through the LXD API.
So I guess it's about saving you one command during commissioning which I guess is ok. 

I think we'll fold that into #7189 though.
