### ISSUE TITLE
Resources endpoint does not provide mainboard and system information

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#7189]
[MAAS is still relying on lshw to gather mainboard information.](https://git.launchpad.net/maas/tree/src/metadataserver/builtin_scripts/hooks.py#n364) The following items are missing:

* System UUID
* System vendor
* System product
* System version
* System serial
* Mainboard vendor
* Mainboard product
* Mainboard version(BIOS/UEFI firmware version)
* Mainboard date(BIOS/UEFI firmware release date)

**Comment by ltrager** [comment]
What I mean by virtuality is whether or not the machine running LXD is a virtual machine/container. This would allow MAAS to know if composed machines are actually nested virtual machines or not.

So lets say I setup LXD in a VMware virtual machine. I then add that LXD to MAAS as a new Pod. virtuality would be True.

**Comment by stgraber** [comment]
Adding a new `system` section in the resources API seems reasonable for this.

```go
type ResourcesSystem struct {
    UUID string `json:"uuid" yaml:"uuid"` // /sys/class/dmi/id/product_uuid
    Vendor string `json:"vendor" yaml:"vendor"` // /sys/class/dmi/id/sys_vendor
    Product string `json:"product" yaml:"product"` // /sys/class/dmi/id/product_name
    Family string `json:"family" yaml:"family"` // /sys/class/dmi/id/product_family
    Version string `json:"version" `yaml:"version"` // /sys/class/dmi/id/product_version
    Sku string `json:"serial" yaml:"serial"` // /sys/class/dmi/id/product_sku
    Serial string `json:"serial" yaml:"serial"` // /sys/class/dmi/id/product_serial

    Firmware *ResourceSystemFirmware `json:"firmware" yaml:"firmware"`
    Motherboard *ResourceSystemMotherboard `json:"motherboard" yaml:"motherboard"`
}

type ResourcesSystemFirmware struct {
    Vendor string `json:"vendor" yaml:"vendor"` // /sys/class/dmi/id/bios_vendor
    Date string `json:"date" yaml:"date"` // /sys/class/dmi/id/bios_date
    Version string `json:"version" `yaml:"version"` // /sys/class/dmi/id/bios_version
}

type ResourcesSystemChassis struct {
    Vendor string `json:"vendor" yaml:"vendor"` // /sys/class/dmi/id/chassis_vendor
    Type string `json:"type" yaml:"type"` // /sys/class/dmi/id/chassis_type (convert to string with https://morecomputerstuff.net/2017/06/27/smbios-chassis-type-table/)
    Serial string `json:"serial" yaml:"serial"` // /sys/class/dmi/id/chassis_serial
    Version string `json:"version" `yaml:"version"` // /sys/class/dmi/id/chassis_version
}

type ResourcesSystemMortherboard struct {
    Vendor string `json:"vendor" yaml:"vendor"` // /sys/class/dmi/id/board_vendor
    Product string `json:"product" yaml:"product"` // /sys/class/dmi/id/board_name
    Serial string `json:"serial" yaml:"serial"` // /sys/class/dmi/id/board_serial
    Version string `json:"version" `yaml:"version"` // /sys/class/dmi/id/board_version
}
```

**Comment by stgraber** [comment]
Note that we need to be resilient to:
 - Any of those files being missing (return empty)
 - /sys/class/dmi itself being missing (will be the case on any non-x86/non-arm64 effectively)
 - systemd-detect-virt not existing or failing

We also need to cache the result of systemd-detect-virt. The rest of the files are cheap to read so we can just parse again (will avoid issues if SMBIOS is temporarily unreadable) but we should only ever run `systemd-detect-virt` once, store the result in a global variable and never run it again.

**Comment by stgraber** [comment]
@monstermunchkin can you start with this tomorrow please?

**Comment by stgraber** [comment]
@ltrager does that cover everything you need? ^

**Comment by stgraber** [comment]
@monstermunchkin let's use `resources_system` for the API extension.

**Comment by ltrager** [comment]
Looks great! Thanks for adding this!
