### ISSUE TITLE
Split up lxd/containers.go

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#719]
lxd/containers.go is a big unreadable mess. We should split it into one file per command (exec, file, state changes, config, ...).

**Comment by boynux** [comment]
I read contribution guide and would like to contribute to this project. How can I choose this issue to work?

**Comment by stgraber** [comment]
Just comment here that you're working on it and others will leave it alone.

**Comment by techtonik** [comment]
Are you sure the right issue is fixed by the commit above?

**Comment by stgraber** [comment]
Nope :)

**Comment by stgraber** [comment]
messed up my bug numbers apparently, thanks for noticing.

**Comment by Ramzec** [comment]
Could you please take a look at my attempt to resolve this issue.
Thanks.
