### ISSUE TITLE
Ubuntu 20.04(beta):  LXD 4.0 on ZFS dataset does not start after first reboot following the installation

### ISSUE THREAD

**Issue by mhansi12** [lxc/lxd#7199]
# Environment:

Distributor ID: Ubuntu
Description:    Ubuntu Focal Fossa (development branch)
Release:        20.04
Codename:       focal
 * The output of "lxc info" fails:  
   * Kernel version: 5.4.0-21
   * LXC version:4.0.0
   * LXD version: Build 14594
   * Storage backend in use:  ZFS
installed snap :
snap    2.44.3+20.04
snapd   2.44.3+20.04
series  16

~# apt policy lxd
lxd:
  Installed: 1:0.8
  Candidate: 1:0.8
  Version table:
 *** 1:0.8 500
        500 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status

# Issue description
After Install LXD on Ubuntu 20.04 everything was fine 
(lxd init worked without problems,  I was able to launch an ubuntu image,too )
Until I rebooted the first time following the installation:
I got:

~#> lxc info
**internal error, please report: running "lxd.lxc" failed: cannot find installed snap "lxd" at revision 14594: missing file /snap/lxd/14594/meta/snap.yaml**

LXD service does not come up again:

~#> snap services 
Service       Startup  Current   Notes
lxd.activate  enabled  inactive  -
lxd.daemon    enabled  inactive  -

it seams that the snap service is not fully up again ( compared , before I reboot):
~# ps -ef |grep snap 
root        7748       1  1 22:26 ?        00:00:00 /usr/lib/snapd/snapd
root        7970    2603  0 22:27 pts/0    00:00:00 grep --color=auto snap

 "mount |grep snap" does not show any loopback mount

# Steps to reproduce

1.) Install Ubuntu 20.04 (server live), with minimum of packages, no desktop, with two ZFS pools a
 "bpool" and "rpool"  ( same as with Ubuntu Desktop with ZFS)
Installation steps taken from:
https://github.com/openzfs/zfs/wiki/Ubuntu-18.04-Root-on-ZFS

2.) apt install  lxd
--> choose Version 4.0/stable

3.) lxd init:

Would you like to use LXD clustering? (yes/no) [default=no]: 
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: svc-pool
**Name of the storage backend to use (btrfs, dir, lvm, zfs, ceph) [default=zfs]: zfs**
**Create a new ZFS pool? (yes/no) [default=yes]: no**
**Name of the existing ZFS pool or dataset: rpool/LXD**
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to create a new local network bridge? (yes/no) [default=yes]: 
What should the new bridge be called? [default=lxdbr0]: lxbr0
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]:           
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
Would you like LXD to be available over the network? (yes/no) [default=no]: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes] 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: 

4) launch  first container or not does not make any difference
5) reboot
6) lxc info --> error

# zfs layout
root@labc~# zfs list
>NAME                                    USED  AVAIL     REFER  MOUNTPOINT
rpool                                  10.6G  6.87G       96K  /
rpool/LXD                               960K  6.87G       96K  none
rpool/LXD/containers                     96K  6.87G       96K  none
rpool/LXD/custom                         96K  6.87G       96K  none
rpool/LXD/deleted                       480K  6.87G       96K  none
rpool/LXD/deleted/containers             96K  6.87G       96K  none
rpool/LXD/deleted/custom                 96K  6.87G       96K  none
rpool/LXD/deleted/images                 96K  6.87G       96K  none
rpool/LXD/deleted/virtual-machines       96K  6.87G       96K  none
rpool/LXD/images                         96K  6.87G       96K  none
rpool/LXD/virtual-machines               96K  6.87G       96K  none
rpool/ROOT                             2.01G  6.87G       96K  none
rpool/ROOT/ubuntu_23wahm               2.01G  6.87G      984M  /
rpool/ROOT/ubuntu_23wahm/var            949M  6.87G      264K  /var
rpool/ROOT/ubuntu_23wahm/var/cache      436M  6.87G      103M  /var/cache
rpool/ROOT/ubuntu_23wahm/var/lib        507M  6.87G      162M  /var/lib
rpool/ROOT/ubuntu_23wahm/var/lib/apt   67.6M  6.87G     33.6M  /var/lib/apt
rpool/ROOT/ubuntu_23wahm/var/lib/dpkg  17.3M  6.87G     9.83M  /var/lib/dpkg
rpool/ROOT/ubuntu_23wahm/var/log       3.86M  6.87G     1.87M  /var/log
rpool/ROOT/ubuntu_23wahm/var/spool      104K  6.87G      104K  /var/spool
rpool/ROOT/ubuntu_23wahm/var/tmp        400K  6.87G      120K  /var/tmp
rpool/SWAP                             8.50G  15.4G       56K  -
rpool/USERDATA                         44.4M  6.87G       96K  none
rpool/USERDATA/root_x0uelt             44.3M  6.87G     41.7M  /root

**Comment by stgraber** [comment]
```
 internal error, please report: running "lxd.lxc" failed: cannot find installed snap "lxd" at revision 14594: missing file /snap/lxd/14594/meta/snap.yaml
```

This is a snapd error, not a LXD one.

**Comment by mhansi12** [comment]
thank you for your fast response, 
OK, where should I look next ? Any ideas ?

**Comment by stgraber** [comment]
https://launchpad.net/ubuntu/+source/snapd/+filebug
https://forum.snapcraft.io

Would be the two best spots to report this. The issue appears to be that the snap isn't mounted on your system.

`systemctl --failed` may be useful, assuming there are some failures in there.
The `journalctl -b0` output may help them too.

**Comment by mhansi12** [comment]
In the meantime  I have installed  a test with Ubuntu 20.04 Desktop with ZFS and same settings during LXD init. lxd works there also after reboot.
I will compare - you can close the issue.

from failing system:  journalctl -b0
(what blockdev ?)
..
Apr 15 22:49:37 loidi kernel: /var/lib/snapd/snaps/core18_1705.snap: Can't open blockdev
Apr 15 22:49:37 loidi systemd[1]: Mounting Mount unit for lxd, revision 14594...
Apr 15 22:49:37 loidi kernel: /var/lib/snapd/snaps/core_8935.snap: Can't open blockdev
Apr 15 22:49:37 loidi kernel: /var/lib/snapd/snaps/lxd_14594.snap: Can't open blockdev
Apr 15 22:49:37 loidi systemd[1]: Mounting Mount unit for snapd, revision 6953...
Apr 15 22:49:37 loidi systemd[1]: snap-core-8935.mount: Mount process exited, code=exited, status=32/n/a
Apr 15 22:49:37 loidi systemd[1]: snap-core-8935.mount: Failed with result 'exit-code'.
Apr 15 22:49:37 loidi systemd[1]: Failed to mount Mount unit for core, revision 8935.
Apr 15 22:49:37 loidi systemd[1]: snap-core18-1705.mount: Mount process exited, code=exited, status=32/n/a
Apr 15 22:49:37 loidi systemd[1]: snap-core18-1705.mount: Failed with result 'exit-code'.
Apr 15 22:49:37 loidi systemd[1]: Failed to mount Mount unit for core18, revision 1705.
Apr 15 22:49:37 loidi kernel: /var/lib/snapd/snaps/snapd_6953.snap: Can't open blockdev
Apr 15 22:49:37 loidi systemd[1]: snap-lxd-14594.mount: Mount process exited, code=exited, status=32/n/a
Apr 15 22:49:37 loidi systemd[1]: snap-lxd-14594.mount: Failed with result 'exit-code'.
Apr 15 22:49:37 loidi systemd[1]: Failed to mount Mount unit for lxd, revision 14594.
Apr 15 22:49:37 loidi systemd[1]: Dependency failed for Service for snap application lxd.activate.
Apr 15 22:49:37 loidi systemd[1]: snap.lxd.activate.service: Job snap.lxd.activate.service/start failed with result 'dependency'.
Apr 15 22:49:37 loidi systemd[1]: Dependency failed for Socket unix for snap application lxd.daemon.
Apr 15 22:49:37 loidi systemd[1]: snap.lxd.daemon.unix.socket: Job snap.lxd.daemon.unix.socket/start failed with result 'dependency'.
Apr 15 22:49:37 loidi systemd[1]: snap-snapd-6953.mount: Mount process exited, code=exited, status=32/n/a
Apr 15 22:49:37 loidi systemd[1]: snap-snapd-6953.mount: Failed with result 'exit-code'.
Apr 15 22:49:37 loidi systemd[1]: Failed to mount Mount unit for snapd, revision 6953.

**Comment by stgraber** [comment]
Sounds like something wrong going on with loop devices maybe?

Are the files at `/var/lib/snapd/snaps` accessible?

**Comment by mhansi12** [comment]
I made progress !

when restarting  manually (  "snap-core-8935.mount".  "snap-core18-1705.mount" and "snap-lxd-14594.mount"  and then "snap restart lxd" ) eveything works again:

So it seams that the order of avaibility of the involved zfs filsystems/datasets are relevant, 
I am confident to solve it soon. I see difference to the desktop version, too

THank you for your help
