### ISSUE TITLE
No network on CentOS8 if raw.lxc: lxc.mount.auto=sys:rw && security.privileged: "true"

### ISSUE THREAD

**Issue by jsalatiel** [lxc/lxd#7200]
# Required information

 * Distribution: Linux Mint
 * Distribution version: 19.3 ( Ubuntu 18.04 base )
 lxc/lxd version: 3.0.3
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
```
# Issue description
If I set the following two lines at my profile,  CentOS8 container will have no network. 
**_raw.lxc: lxc.mount.auto=sys:rw
security.privileged: "true"_**
I need those two parameters to be able to run kubernetes on lxd and they work just fine with CentOS7.

Actually the full raw.lxc line required by K8s is:
raw.lxc: "lxc.apparmor.profile=unconfined\nlxc.cap.drop= \nlxc.cgroup.devices.allow=a\nlxc.mount.auto=proc:rw sys:rw cgroup:rw"

But I was able to reduce the scope to 
**_raw.lxc: lxc.mount.auto=sys:rw
security.privileged: "true"_**
# Steps to reproduce

 1. Edit your default profile and add inside the config session
**_raw.lxc: lxc.mount.auto=sys:rw
security.privileged: "true"_**
 2. lxc launch images:centos/8 mycontainer
 3. lxc ls mycontainer

There will be no network ipv4 or ipv6 assigned to eth0.

**Comment by stgraber** [comment]
Looks like setting /sys to fully writable causes NetworkManager to get confused.
As this is an unsupported configuration, you're going to have to find a way around it.

Some options would be to switch to `systemd-networkd` or manually put something that does:
 - ip link set dev eth0 up
 - nmcli conn up "System eth0"

Which seems to be enough to make NM happy here.

**Comment by jsalatiel** [comment]
Thanks.
I will leave here a systemd unit that run those command in case someone else faces this problem:

``` 
[Unit]
Description=Workaround for lxd privileged/sys=rw CentOS8 network
After=NetworkManager.service

[Service]
ExecStartPre=/usr/sbin/ip link set dev eth0 up
ExecStart=/usr/bin/nmcli conn up "System eth0"
RemainAfterExit=true
type=oneshot

[Install]
WantedBy=network.target
```
