### ISSUE TITLE
Validate that the listen address is available

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7202]
During `lxd init` we should validate that the selected address for `core.https_address` is available.
The easiest would be to attempt to listen on it, if that fails, consider validation failed and require the user to try another one.

This would have saved me some confusing errors when setting up clusters :)

**Comment by stgraber** [comment]
@freeekanayaka want to take a stab at this one? Should be a quick one. We'd want this for both standalone and cluster listen address.

**Comment by freeekanayaka** [comment]
Sure.
