### ISSUE TITLE
Nested LXD fails with error when asking for available resources

### ISSUE THREAD

**Issue by morphis** [lxc/lxd#7203]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:5.3.0-28-generic #30~18.04.1-Ubuntu SMP
   * LXC version: 4.0.0
   * LXD version: 4.0.0
   * Storage backend in use: zfs

# Issue description

A nested LXD within an unprivileged fails to determine available resources when calling the `/1.0/resources` API endpoint

# Steps to reproduce

 1. Create a LXD container `lxc launch ubuntu:b c0`
 2. Install LXD snap within that container `lxc exec c0 -- snap install lxd`
 3. Try to fetch resources from LXD
```
$ curl --unix /var/snap/lxd/common/lxd/unix.socket s/1.0/resources
{"error":"Failed to retrieve system information: Failed to read \"/sys/class/dmi/id/product_uuid\": open /sys/class/dmi/id/product_uuid: permission denied","error_code":500,"type":"error"
```

**Comment by stgraber** [comment]
Yep, I sent a PR to fix that already, we'll cherry-pick it ASAP.

**Comment by morphis** [comment]
Nice, thanks @stgraber

**Comment by stgraber** [comment]
Also added a test for it and validate on all architectures for good measure.
