### ISSUE TITLE
Cephfs: Parsing ceph configuration file is too rigid.

### ISSUE THREAD

**Issue by amcduffee** [lxc/lxd#7208]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-66-generic
   * LXC version: 4.0.0
   * LXD version: 4.0.0
   * Storage backend in use: ceph

# Issue description

The direct attach of cephfs through a disk device is too rigid in how it parses and interprets the cluster conf file under /etc/ceph

# Steps to reproduce

 1. Add a 'mon host' entry under [global] in the default cluster /etc/ceph/ceph.conf, for example:
> mon host = [fc00::12:3],[fc00::12:4],[fc00::13:1]

 2. Try to direct attach the cephfs:
> $ lxc config device add test-cephfs cephfs disk source=cephfs:/ path=/cephfs
> Error: Failed to start device "cephfs": Couldn't find a CPEH mon

I see two cases for the above error:
1) func (d *cephfs) getConfig( ... ) in lxd/storage/drivers/driver_cephfs_utils.go
2) func cephFsConfig( ... ) in lxd/device/device_utils_disk.go

Refer to the 'OPTION NAMES' section at https://docs.ceph.com/docs/master/rados/configuration/ceph-conf/ for the following line:
> When option names appear in configuration files, spaces can also be used in place of underscore or dash.

Another issue with the two functions above is that they assume a nomenclature for ceph keyring filenames:

> cephKeyring, err := os.Open(fmt.Sprintf("/etc/ceph/%v.client.%v.keyring", clusterName, userName))

While this is probably acceptable as a default behavior it is problematic that there isn't an optional configuration value for overriding the default.  As is, I can't get this layer to see my mount secret because I use a slightly different nomenclature:
> /etc/ceph/\<cluster_name\>.mnt.\<username\>.secret

I also use this variation because the file doesn't actually store a ceph keyring, instead it contains only the secret as specified by the 'mount.ceph' manpage for the 'secretfile' option:
>        secretfile
>               path to file containing the secret key to use with cephx

**Comment by stgraber** [comment]
Hmm so tweaking the parser to accept spaces is fine, we'll do that.

I don't think we'll be adding support for secret files or alternative location for the keyring, supporting the common setup is fine and the LXD snap allows you to have a completely separate ceph config directory if you want to keep your system one the way it is now.

**Comment by amcduffee** [comment]
Ok, don't forget hyphens in addition to spaces and underscores.

It is unfortunate that you won't consider supporting secret files because it is documented and official behavior based on 'man mount.ceph'.  Sure, I could use the separate ceph config directory only for the snap, but that means managing two sets of configurations needlessly when I am already creating and using 'secretfile' mount options at the host level for other mounts.

Irrespective of what the nomenclature is for the secretfile filenames, it would be ideal to not have to manage essentially two copies of the same thing.  Considering that the parsing logic is already opening the keyring file and searching for the 'secret=...' line it seems natural that an optional 'secretfile' configuration value for the device could instead point to a file that could be opened and consumed in its entirety.  As indicated in the manpage, and learned from my own experience, a 'secretfile' explicitly should contain only the value portion of the 'secret=...' line from a keyring file, so no parsing would be required.

I figured I would recommend it for improved usability.

**Comment by stgraber** [comment]
It's worth noting that LXD directly calls the Mount syscall and so doesn't use `mount.ceph` at all, so `secretfile` isn't an option we can actually use. We can only use what the kernel driver supports directly, everything else we need to manually parse and process. So we're sticking with the most common setup as it's something we can more reliably test, adding more options means more config options, more validation, more potential conflicts and more potential bugs.

Given this isn't something you're expected to have to change outside of initial setup, it should be fine.

**Comment by amcduffee** [comment]
I understand what you are saying.  That is fine.

I wasn't asking for it to be supported as a mount command option.  Rather simply, if an optional 'secretfile' configuration value was offered then it could define a path to a file containing only the secret itself.  LXD could just read the contents of the file as opposed to parsing a keyring file for the 'secret=...' line.

Considering such files already have to exist in such a format to be compatible with the 'secretfile' option in /etc/fstab entries I just thought it would be a nice usability addition to effectively allow me to tell LXD "hey, go read the secret from this file because it is already there for other fstab entries."
