### ISSUE TITLE
lxc-checkconfig gives wrong result for "Cgroup memory controller" test on Linux >= 4.0

### ISSUE THREAD

**Issue by LeeTibbert** [lxc/lxd#721]
I am not sure if I should be reporting this issue here or in an lxc repository. Sorry
if I have the wrong place. I probably have the right people. 

Short story:
I believe an edit is needed in lxc-checkconfig in order for it to give proper
results in linux >= 4.0.

Replace line:

if [ $KVER_MAJOR -ge 3 -a $KVER_MINOR -ge 6 ]; then

with line:
if [ $KVER_MAJOR -ge 4 ] || [ $KVER_MAJOR -ge 3 -a $KVER_MINOR -ge 6 ]; then

Thank you.

Longer story:

First & foremost, thank you for lxc-checkconfig. I encountered it after many
hours of debugging why the simple instructions for launching a container
were not working on my system.  I was about to give up on lxd when
it saved my bacon.  Problem was a mixture of custom kernel &, I believe,
a bug in the linux 4.0.4 version I am using.  I am now up and running
on an earlier linux version.  I _strongly_ recommend that lxc-checkconfig
be mentioned _prominently_ in any getting started description. Who
would ever run a custom kernel?

The blog post: https://www.stgraber.org/2015/04/21/lxd-getting-started/
was essential to my getting started with lxd. Thank you Stephane.

This issue report is an effort to make a small contribution back, not
a complaint.

I've never done a pull request before & this edit is simple, so I suspect
that the developer time taken to walk me through the steps would
not be repaid.  If I am wrong, please advise.

Lee

**Comment by stgraber** [comment]
Hi Lee,

lxc-checkconfig belongs to the lxc repository, so the issue should have been filed at github.com/lxc/lxc/

As for the actual report, this issue has already been fixed a little while ago in git, though not included in any release yet.

The condition we currently have in git is:

    ([ $KVER_MAJOR -ge 3 ] && [ $KVER_MINOR -ge 6 ]) || ([ $KVER_MAJOR -gt 3 ])

As such, I believe this issue has already been resolved and so will close it, thanks!
