### ISSUE TITLE
VM restart fails writing agent config

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7223]
root@contest06:~# lxc restart ctf18
Error: Failed writing agent mounts file: open /var/snap/lxd/common/lxd/virtual-machines/ctf18/config/agent-mounts.json: no such file or directory
Try `lxc info --show-log ctf18` for more info

A start immediately after that works fine.

**Comment by tomponline** [comment]
@stgraber I'll take a look at this if ur ok?

**Comment by stgraber** [comment]
Yep, thanks!

**Comment by tomponline** [comment]
On 18.04 ZFS I'm also seeing:

```
qemu-system-x86_64:/var/log/lxd/test_v1/qemu.conf:81: char device redirected to /dev/pts/5 (label console)
qemu-system-x86_64:/var/log/lxd/test_v1/qemu.conf:104: Could not open '/var/lib/lxd/virtual-machines/test_v1/qemu.nvram': No such file or directory
```

**Comment by stgraber** [comment]
Yeah, the problematic file has been changing. I suspect the issue is OnStop finishing cleanup when Start() has already been called.
