### ISSUE TITLE
LXD VM: ubuntu-daily images kernels = error: kernel doesn't support EFI handover.

### ISSUE THREAD

**Issue by rafaeldtinoco** [lxc/lxd#7224]
# Required information

  driver: lxc
  driver_version: 4.0.1
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-24-generic
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: workstation
  server_pid: 1122044
  server_version: 4.0.0
  storage: dir | zfs
  storage_version: 1 | 0.8.3-1ubuntu12

# Issue description

Can't get eoan or focal images to work as VMs because during initial boot I get:

BdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)
error: kernel doesn't support EFI handover.
error: you need to load the kernel first.

Press any key to continue...!!!! X64 Exception Type - 0D(#GP - General Protection)  CPU Apic ID - 00000000 !!!!
ExceptionData - 0000000000000000
RIP  - 000000003FAF3405, CS  - 0000000000000038, RFLAGS - 0000000000210012
RAX  - 000000003E657018, RCX - AFAFAFAFAFAFAFAF, RDX - 000000003FAF3520
RBX  - 0000000000000080, RSP - 000000003FFA4B80, RBP - 0000000000000000
RSI  - 000000003FAF3520, RDI - 000000003FFBA130
R8   - 000000003E97F082, R9  - 0000000000000000, R10 - 0000000000000000
R11  - 000000003E9C664C, R12 - 0000000000000010, R13 - 000000003E97F082
R14  - 000000003FFBCEE0, R15 - 000000003E761B18
DS   - 0000000000000030, ES  - 0000000000000030, FS  - 0000000000000030
GS   - 0000000000000030, SS  - 0000000000000030
CR0  - 0000000080010033, CR2 - 0000000000000000, CR3 - 000000003FC01000
CR4  - 0000000000000668, CR8 - 0000000000000000
DR0  - 0000000000000000, DR1 - 0000000000000000, DR2 - 0000000000000000
DR3  - 0000000000000000, DR6 - 00000000FFFF0FF0, DR7 - 0000000000000400
GDTR - 000000003FBEE698 0000000000000047, LDTR - 0000000000000000
IDTR - 000000003F2D8018 0000000000000FFF,   TR - 0000000000000000
FXSAVE_STATE - 000000003FFA47E0
!!!! Find image based on IP(0x3FAF3405) /build/edk2-dQLD17/edk2-0~20191122.bd85bf54/Build/OvmfX64/RELEASE_GCC5/X64/NetworkPkg/DpcDxe/DpcDxe/DEBUG/DpcDxe.dll (ImageBase=000000003FAF3000, EntryPoint=000000003FAF3484) !!!!

# Steps to reproduce

lxc init ubuntu-daily:focal testando --vm

# Information to attach

Removing the -kvm kernel that comes with it and installing latest -generic (5.4.0-25) fixed the issue.

**Comment by stgraber** [comment]
Hmm, the KVM images are supposed to be booting better than the non-kvm...

Speaking of, this made me notice https://github.com/lxc/lxd/pull/7225

**Comment by stgraber** [comment]
```
BdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)
error: can't find command `hwmatch'.
error: /boot/vmlinuz-5.4.0-1008-kvm has invalid signature.

Press any key to continue...

  Failed to boot both default and fallback entries.

Press any key to continue...
```

**Comment by stgraber** [comment]
With secureboot disabled, I'm now getting the same error you're getting.

**Comment by stgraber** [comment]
https://bugs.launchpad.net/cloud-images/+bug/1873809 with more details and reproduction step with simple qemu.

Closing this issue as there's no LXD bugs there, the images appear to be the issue.
