### ISSUE TITLE
Add lxd-agent option to apply name, mtu to nic devices

### ISSUE THREAD

**Issue by rafaeldtinoco** [lxc/lxd#7233]
# Required information

  driver: lxc
  driver_version: 4.0.1
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-24-generic
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: workstation
  server_pid: 1122044
  server_version: 4.0.0
  storage: dir | zfs
  storage_version: 1 | 0.8.3-1ubuntu12

# Issue description

When adding nics to a VM it is hard to tell which nic is connected to which network. It would be good if a 1:1 nic <-> naming could be achieved like in regular containers.

Perhaps udev rules renaming interfaces could be placed inside VM image through cloud-init or lxd-agent so the interfaces are named like the yaml file from either profile or vm itself.

# Steps to reproduce

Nowadays, for example, I have to:

$ lxc network list --format=csv
enp8s0,physical,NO,,0
lxdbr0,bridge,YES,,3
lxdint01,bridge,YES,,2
lxdint02,bridge,YES,,2
lxdiscsi01,bridge,YES,,2
lxdiscsi02,bridge,YES,,2
lxdpub01,bridge,YES,,2
lxdpub02,bridge,YES,,2

then edit the profile:

  lxdbr0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  lxdint01:
    nictype: bridged
    parent: lxdint01
    type: nic
  lxdint02:
    nictype: bridged
    parent: lxdint02
    type: nic
  lxdiscsi01:
    nictype: bridged
    parent: lxdiscsi01
    type: nic
  lxdiscsi02:
    nictype: bridged
    parent: lxdiscsi02
    type: nic
  lxdpub01:
    nictype: bridged
    parent: lxdpub01
    type: nic
  lxdpub02:
    nictype: bridged
    parent: lxdpub02
    type: nic

then show the VM config:

  volatile.lxdbr0.host_name: tapbc7fbbba
  volatile.lxdbr0.hwaddr: 00:16:3e:21:10:70
  volatile.lxdint01.host_name: tapf7a264de
  volatile.lxdint01.hwaddr: 00:16:3e:65:f5:00
  volatile.lxdint02.host_name: tap7921f0f8
  volatile.lxdint02.hwaddr: 00:16:3e:6d:68:84
  volatile.lxdiscsi01.host_name: tap9a14182f
  volatile.lxdiscsi01.hwaddr: 00:16:3e:00:63:c3
  volatile.lxdiscsi02.host_name: tap95eb4757
  volatile.lxdiscsi02.hwaddr: 00:16:3e:bd:c3:15
  volatile.lxdpub01.host_name: tapf89fbefc
  volatile.lxdpub01.hwaddr: 00:16:3e:b3:7a:28
  volatile.lxdpub02.host_name: tapfd1a02c2
  volatile.lxdpub02.hwaddr: 00:16:3e:73:60:c8

to configure netplan:

network:
    ethernets:
        enp5s0:
            dhcp4: true
            match:
                macaddress: 00:16:3e:21:10:70
            set-name: enp5s0
        enp6s0:
            match:
                macaddress: 00:16:3e:65:f5:00
            addresses: [10.250.96.98/24]
            set-name: lxdint01
        enp7s0:
            match:
                macaddress: 00:16:3e:6d:68:84
            addresses: [10.250.95.98/24]
            set-name: lxdint02
        enp8s0:
            match:
                macaddress: 00:16:3e:00:63:c3
            addresses: [10.250.94.98/24]
            set-name: lxdiscsi01
        enp9s0:
            match:
                macaddress: 00:16:3e:bd:c3:15
            addresses: [10.250.93.98/24]
            set-name: lxdiscsi02
        enp10s0:
            match:
                macaddress: 00:16:3e:b3:7a:28
            addresses: [10.250.92.98/24]
            set-name: lxdpub01
        enp11s0:
            match:
                macaddress: 00:16:3e:73:60:c8
            addresses: [10.250.91.98/24]
            set-name: lxdpub02
    version: 2

# Information to attach

This is likely a whishlist and not a bug.

**Comment by stgraber** [comment]
Yeah, it's something we considered and that's somewhat doable with the agent, though we wouldn't want it done by default as we need to ship default network configs in the images and so can't have varying interface names in there (just like we assume eth0 for containers).

**Comment by stgraber** [comment]
I suspect what we would do for those devices where the user opts for us to rename it is write down a file for the agent to handle which contains the expected PCI address for the NIC and the name, mtu, IP, ... whatever else makes sense that it should have.

It would still be somewhat racy with networkd or whatever else the user may use, so they may need to order their boot such that lxd-agent starts first.

**Comment by stgraber** [comment]
So I think what we'd do here is:

 - Introduce a new `agent.rename_interfaces` instance config option (default=false)
 - When set to true, we'd calculate the PCI address of the NICs and write down a file containing a map of those PCI addresses to the expected name and mtu
 - `lxd-agent` on startup would consume that data and perform the needed renames and apply the configured MTU

The user would have to opt into this by setting the flag to true and will then be responsible for dealing with any boot ordering and network config issues that may result from this.

**Comment by rafaeldtinoco** [comment]
I like that approach! Cloning a VM and rebooting it would make all the previously named interface to be renamed again with the new MACs <- this is my real need for cloning cluster nodes. Thank you for considering this!

**Comment by archevan** [comment]
My group for a virtualization class at UT Austin can take a look at getting this added as part of our final project! Is there any way you could assign this issue to me so we have a record of the issues we're working on?

**Comment by stgraber** [comment]
Done!

**Comment by stgraber** [comment]
@archevan hello, just wanted to check if you still intend to work on this or if we should unassign it so someone else can take a crack at it?

**Comment by archevan** [comment]
@stgraber I haven't been able to take a look yet. I'll unassign and let someone else take a look!
