### ISSUE TITLE
lxc export of running container breaks when file is missing

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxd#7242]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 19.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.3.0-46-generic
   * LXC version: 4.0.1
   * LXD version: 4.0.0
   * Storage backend in use: dir

# Issue description
Export of running container breaks if file disappears (for ex. from .../roundcube/temp/).

# Steps to reproduce
Tested on actively used roundcube CT.
It is problem to stop it during export.

It would be nice if in this case the export would give a warning, but not break

# Information to attach
lxc export roundcube roundcube.tar.gz

Error: Create backup: Backup create: lstat /var/lib/lxd/storage-pools/default/containers/roundcube/rootfs/.../roundcube/temp/rcmAttmntdDYrtL: no such file or directory

**Comment by stgraber** [comment]
@tomponline another tweak to the tarball writer?

**Comment by tomponline** [comment]
@stgraber yep will take
