### ISSUE TITLE
Container network

### ISSUE THREAD

**Issue by hlyj1995** [lxc/lxd#7253]
hi，
  I meet a problem this week, my container network doesn't work. I didn't  change any configs. Is it due to I installed docker engine on the host machine? Look forward your help.
 ylh

### This is my lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: br1
    type: nic
  root:
    path: /
    pool: my-zfs
    type: disk
name: default
used_by:
- /1.0/containers/jxb
- /1.0/containers/ylhh
### This is my host interface
auto lo
iface lo inet loopback

auto br1
iface br1 inet dhcp
  bridge_ports enp5s0

iface enp5s0  inet manual

### This is my container interface 
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

### This is lxc list，you can see only having IPV6
 NAME  |  STATE  |         IPV4         |                    IPV6                     |    TYPE    | SNAPSHOTS |
+-------+---------+----------------------+---------------------------------------------+------------+-----------+
| ylhh  | RUNNING | 172.17.0.1 (docker0) | 2001:da8:216:251d:216:3eff:fee2:d9ec (eth0) | PERSISTENT | 1         |

### this is ifcong                        
br1       Link encap:以太网  硬件地址 2c:4d:54:45:01:66  
          inet 地址:172.25.29.50  广播:172.25.29.255  掩码:255.255.255.0
          inet6 地址: fe80::2e4d:54ff:fe45:166/64 Scope:Link
          inet6 地址: 2001:da8:216:251d:e9eb:38e6:9e3a:32b4/64 Scope:Global
          inet6 地址: 2001:da8:216:251d:2e4d:54ff:fe45:166/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  跃点数:1
          接收数据包:620465 错误:0 丢弃:0 过载:0 帧数:0
          发送数据包:20556 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:1000 
          接收字节:53168078 (53.1 MB)  发送字节:1751389 (1.7 MB)

docker0   Link encap:以太网  硬件地址 02:42:c8:fd:e0:dd  
          inet 地址:172.17.0.1  广播:172.17.255.255  掩码:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  跃点数:1
          接收数据包:0 错误:0 丢弃:0 过载:0 帧数:0
          发送数据包:0 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:0 
          接收字节:0 (0.0 B)  发送字节:0 (0.0 B)

eno1      Link encap:以太网  硬件地址 2c:4d:54:45:01:65  
          UP BROADCAST MULTICAST  MTU:1500  跃点数:1
          接收数据包:0 错误:0 丢弃:0 过载:0 帧数:0
          发送数据包:0 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:1000 
          接收字节:0 (0.0 B)  发送字节:0 (0.0 B)
          中断:20 Memory:fb100000-fb120000 

enp5s0    Link encap:以太网  硬件地址 2c:4d:54:45:01:66  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  跃点数:1
          接收数据包:623814 错误:0 丢弃:0 过载:0 帧数:0
          发送数据包:20862 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:1000 
          接收字节:62747924 (62.7 MB)  发送字节:1778237 (1.7 MB)
          Memory:fb700000-fb77ffff 

lo        Link encap:本地环回  
          inet 地址:127.0.0.1  掩码:255.0.0.0
          inet6 地址: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  跃点数:1
          接收数据包:296 错误:0 丢弃:0 过载:0 帧数:0
          发送数据包:296 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:1000 
          接收字节:23468 (23.4 KB)  发送字节:23468 (23.4 KB)

### this is contain ifconfig，the eth0 only has ipv6
docker0   Link encap:Ethernet  HWaddr 02:42:a5:ca:57:10  
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 00:16:3e:e2:d9:ec  
          inet6 addr: 2001:da8:216:251d:216:3eff:fee2:d9ec/64 Scope:Global
          inet6 addr: fe80::216:3eff:fee2:d9ec/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:26968 errors:0 dropped:124 overruns:0 frame:0
          TX packets:337 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2504457 (2.5 MB)  TX bytes:35498 (35.4 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:168 errors:0 dropped:0 overruns:0 frame:0
          TX packets:168 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:14112 (14.1 KB)  TX bytes:14112 (14.1 KB)

**Comment by stgraber** [comment]
Please show 'iptables -L' and 'ip6tables -L' to confirm its docker messing with your firewall

**Comment by hlyj1995** [comment]
@stgraber 
This is my result.Is there anything wrong with it ？
root@ylhh:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
root@ylhh:~# ip6tables -L
libkmod: ERROR ../libkmod/libkmod-config.c:635 kmod_config_parse: /etc/modprobe.d/blacklist-nouveau.conf line 1: ignoring bad line starting with 'cklist'
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.15.0-96-generic/modules.dep.bin'
modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/4.15.0-96-generic
ip6tables v1.6.0: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.

**Comment by tomponline** [comment]
Do you have a DHCP server on the `br1` network?

If you launch another container connected to the `br1` network without installing docker inside it, does the network work OK?

What container image are you using and can you show me the network config used inside the container?

**Comment by stgraber** [comment]
@hlyj1995 I need those `iptables` and ip6tables` commands run on the host, not in the container.

**Comment by hlyj1995** [comment]
@stgraber 
ok.this is my host result.
sudo iptables -L
[sudo] sipl  password： 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
sipl@sipl-1201:~$ ip6tables -L
modprobe: ERROR: could not insert 'ip6_tables': Operation not permitted
ip6tables v1.6.0: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
sipl@sipl-1201:~$ sudo ip6tables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by hlyj1995** [comment]
@tomponline 
I don't know how to judge  if there have a DHCP server on the br1 network. But as I wrote above, I wrote it into my host interface file.And you can see ifconfig ，br1 has its inet and inet6.
This problem occurred after I installed docker on my host, before that I had docker in every container.
I use Ubuntu 16.04 LTS server，and this is my container network config.
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

docker0 Link encap:Ethernet HWaddr 02:42:a5:ca:57:10
inet addr:172.17.0.1 Bcast:172.17.255.255 Mask:255.255.0.0
UP BROADCAST MULTICAST MTU:1500 Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)

eth0 Link encap:Ethernet HWaddr 00:16:3e:e2:d9:ec
inet6 addr: 2001:da8:216:251d:216:3eff:fee2:d9ec/64 Scope:Global
inet6 addr: fe80::216:3eff:fee2:d9ec/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:26968 errors:0 dropped:124 overruns:0 frame:0
TX packets:337 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:2504457 (2.5 MB) TX bytes:35498 (35.4 KB)

lo Link encap:Local Loopback
inet addr:127.0.0.1 Mask:255.0.0.0
inet6 addr: ::1/128 Scope:Host
UP LOOPBACK RUNNING MTU:65536 Metric:1
RX packets:168 errors:0 dropped:0 overruns:0 frame:0
TX packets:168 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:14112 (14.1 KB) TX bytes:14112 (14.1 KB)

**Comment by stgraber** [comment]
Can you also show `grep "" /proc/sys/net/bridge/*`?

Docker has put its usual firewall rules which have a tendency to conflict with LXD.
If br_netfilter is enabled on your system, then those rules would block most traffic through your bridge, including DHCP.

**Comment by hlyj1995** [comment]
@stgraber 
hi，this is my result.If docker does put its usual firewall rules,what should I do？
grep "" /proc/sys/net/bridge/*
/proc/sys/net/bridge/bridge-nf-call-arptables:1
/proc/sys/net/bridge/bridge-nf-call-ip6tables:1
/proc/sys/net/bridge/bridge-nf-call-iptables:1
/proc/sys/net/bridge/bridge-nf-filter-pppoe-tagged:0
/proc/sys/net/bridge/bridge-nf-filter-vlan-tagged:0
/proc/sys/net/bridge/bridge-nf-pass-vlan-input-dev:0

**Comment by stgraber** [comment]
Right, so Docker is the one blocking your network.

Manually configuring your firewall to not DROP all traffic would be one way out.
Another since you're bridging straight to the outside would be to set all the files under `/proc/sys/net/bridge` to 0.

Closing as this isn't a LXD bug but other software on the system interfering with networking.
