### ISSUE TITLE
Installing LXD on debian 10 from snap does fail

### ISSUE THREAD

**Issue by xhess** [lxc/lxd#7260]
# Required information

 * Distribution: debian
 * Distribution version: 10
 * Snapd version: 2.37.4-1
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.19.0-8-amd64
   * LXC version: snap-14804
   * LXD version: snap-14804
   * Storage backend in use: zfs

# Issue description

I don't know if it is really of your concern, but since a few days installing lxd on debian 10 using the snap installer does't work. It says:

> Mount snap "lxd" (14804) (snap "lxd" assumes unsupported features: snapd2.39 (try to update snapd and refresh the core snap))

It maybe has something to do with the release of the new ubuntu focal?!

**Comment by stgraber** [comment]
Try running:
 - snap install core18
 - snap install snapd
 - snap version
 - snap install lxd

This should get snapd to the version you need.

**Comment by mikkel1156** [comment]
I had the same issue, core18 was already installed but couldn't install snapd either.
However, I then installed hello-world (which worked) and after that I could install snapd and then lxd.

**Comment by stgraber** [comment]
Ah right, snapd may be old enough that you actually want `snap install core`, which then gets you the new snapd, at which point you can install lxd and that will grab core18 for you...

The error actually used to be a lot worse, but we've added metadata in LXD now which causes that version error to show up instead, at least trying to nudge some folks into the right direction when this happens.
