### ISSUE TITLE
LXD reports i686 support but fails to start i686 VM

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#7263]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-96-generic
   * LXC version: 4.0.2
   * LXD version: 4.0.1
   * Storage backend in use: dir

# Issue description

MAAS allows users to create VMs based on what architectures LXD reports it supports. LXD reports it supports both x86_64 and i686 virtual machines. LXD allows you to create an i686 VM however when you try to start it LXD reports the architecture isn't supported.

# Steps to reproduce

 1. List LXD supported architectures

$ sudo curl -G --unix-socket "/var/snap/lxd/common/lxd/unix.socket" "lxd/1.0" | jq .metadata.environment.architectures
[
  "x86_64",
  "i686"
]

 2. Create an i686 VM

$ lxc init i686-vm --empty --vm
$ lxc config edit i686-vm
change architecture:x86_64 to architecture:i686

 3. Start VM and see failure
 lxc start i686-vm
Error: Architecture isn't supported for virtual machines
Try `lxc info --show-log i686-vm` for more info

$ lxc info --show-log i686-vm
Name: i686-vm
Location: none
Remote: unix://
Architecture: i686
Created: 2020/04/27 18:12 UTC
Status: Stopped
Type: virtual-machine
Profiles: default
Error: open /var/snap/lxd/common/lxd/logs/i686-vm/qemu.log: no such file or directory

**Comment by stgraber** [comment]
Not really a bug in that we've always been pretty clear that LXD VM support would start with x86_64, then add aarch64, ppc64el and s390x and that's the order we've been adding architectures into.

i386 & armhf have not seen any request until now so it's not even on our ideas list at this stage.

Also worth noting that very very few Linux distributions support i386 EFI boot, so I'm not convinced that it'd be of much use to you were we to implement it.

**Comment by stgraber** [comment]
@ltrager would i386 UEFI with secureboot actually be something useful to you?

**Comment by stgraber** [comment]
(The info in /1.0 is the list of architectures supported by the host CPU, it doesn't say anything about what can be used for VMs, though it will normally line up with what can work for containers since the kernel is shared)

**Comment by stgraber** [comment]
To be clear, adding qemu-system-i386 with IA32 edk2 firmware should be reasonably straightforward so we could do that pretty cheaply. Whether there's anything you can run on top of that is another question though :)

**Comment by ltrager** [comment]
Ok I had assumed the architectures list in /1.0 was the list of architectures that LXD supports. I'm fine with LXD not supporting i686 and was just testing out MAAS/LXD integration when I came across this.

Is there some way to query what architectures LXD supports for VMs? I'm trying to avoid hard coding the list of LXD virtual-machine architectures in MAAS.

**Comment by stgraber** [comment]
No, there isn't. It primarily depends on what qemu binaries are shipped on the system which is more of a packaging thing. With the snap we only ship the native architecture at this time.

**Comment by ltrager** [comment]
Ok will update MAAS, no need for LXD changes :)
