### ISSUE TITLE
lxc.rootfs.path not recognized once starting container

### ISSUE THREAD

**Issue by naimols** [lxc/lxd#7268]
# Required information

lxc.rootfs.path not recognized once starting container

 * Distribution: RHEL
 * Distribution version: 7
 * The output of "lxc info" or if that fails:
lxc c1 20200427232917.707 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_create:1157 - File exists - The /sys/fs/cgroup/cpuset//lxc.monitor.c1 cgroup already existed
lxc c1 20200427232917.707 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1264 - Failed to create cgroup "(null)"
lxc c1 20200427232917.707 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_create:1157 - File exists - The /sys/fs/cgroup/cpuset//lxc.monitor.c1-1 cgroup already existed
lxc c1 20200427232917.707 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1264 - Failed to create cgroup "(null)"
lxc c1 20200427232917.707 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_create:1157 - File exists - The /sys/fs/cgroup/cpuset//lxc.monitor.c1-2 cgroup already existed
lxc c1 20200427232917.707 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1264 - Failed to create cgroup "(null)"
lxc c1 20200427232917.707 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_create:1157 - File exists - The /sys/fs/cgroup/cpuset//lxc.monitor.c1-3 cgroup already existed
lxc c1 20200427232917.707 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1264 - Failed to create cgroup "(null)"
lxc c1 20200427232917.708 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_create:1157 - File exists - The /sys/fs/cgroup/cpuset//lxc.monitor.c1-4 cgroup already existed
lxc c1 20200427232917.708 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1264 - Failed to create cgroup "(null)"
lxc c1 20200427232917.708 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_create:1157 - File exists - The /sys/fs/cgroup/cpuset//lxc.monitor.c1-5 cgroup already existed
lxc c1 20200427232917.708 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1264 - Failed to create cgroup "(null)"
lxc c1 20200427232917.708 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_create:1157 - File exists - The /sys/fs/cgroup/cpuset//lxc.monitor.c1-6 cgroup already existed
lxc c1 20200427232917.708 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1264 - Failed to create cgroup "(null)"
lxc c1 20200427232917.708 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1143 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.c1-7"
lxc c1 20200427232917.709 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1143 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.c1"
lxc c1 20200427232917.711 ERROR    utils - utils.c:lxc_can_use_pidfd:1834 - Kernel does not support pidfds
lxc c1 20200427232917.713 ERROR    dir - storage/dir.c:dir_mount:152 - No such file or directory - Failed to mount "/var/lib/lxd/containers/c1/rootfs" on "/usr/lib64/lxc/rootfs"
lxc c1 20200427232917.713 ERROR    conf - conf.c:lxc_mount_rootfs:1256 - Failed to mount rootfs "/var/lib/lxd/containers/c1/rootfs" onto "/usr/lib64/lxc/rootfs" with options "(null)"
lxc c1 20200427232917.713 ERROR    conf - conf.c:lxc_setup_rootfs_prepare_root:3187 - Failed to setup rootfs for
lxc c1 20200427232917.713 ERROR    conf - conf.c:lxc_setup:3286 - Failed to setup rootfs
lxc c1 20200427232917.713 ERROR    start - start.c:do_start:1232 - Failed to setup container "c1"
lxc c1 20200427232917.713 ERROR    sync - sync.c:__sync_wait:41 - An error occurred in another process (expected sequence number 5)
lxc c1 20200427232917.713 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:852 - Received container state "ABORTING" instead of "RUNNING"
lxc c1 20200427232917.714 ERROR    start - start.c:__lxc_start:1953 - Failed to spawn container "c1"
lxc c1 20200427232917.714 WARN     start - start.c:lxc_abort:1030 - No such process - Failed to send SIGKILL to 7052
lxc c1 20200427232917.771 WARN     cgfsng - cgroups/cgfsng.c:cgfsng_monitor_destroy:1110 - No space left on device - Failed to move monitor 6999 to "/sys/fs/cgroup/cpuset//lxc.pivot"
lxc 20200427232917.772 WARN     commands - commands.c:lxc_cmd_rsp_recv:122 - Connection reset by peer - Failed to receive response for command "get_state"
   * Kernel version: 4.9.98
   * LXC version: 4.0.0
   * LXD version: 4.0.0
   * Storage backend in use: dir

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

1. Create rootfs @ /containers/c1/rootfs
 2. lxc init c1 --empty
 3. Add lxc.rootfs.path=/containers/c1/rootfs to the raw.lxc entry in "lxc config edit c1"
4. lxc start c1

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
architecture: x86_64
config:
  raw.lxc: |-
    lxc.rootfs.path=/containers/c1/rootfs
  security.privileged: "true"
  volatile.idmap.base: "0"
  volatile.idmap.current: '[]'
  volatile.idmap.next: '[]'
  volatile.last_state.power: STOPPED
devices:
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

**Comment by stgraber** [comment]
This isn't a setup that we can support.

**Comment by stgraber** [comment]
(To be clear, the issue is custom rootfs that's not managed by LXD and is passed through raw.lxc, the LXD generated config conflicts with the manual one and even if this was somehow successful, this would break very large parts of what LXD expects from a container)

**Comment by naimols** [comment]
Ok. Understood, I just noticed that once the I try to start the containers (2) lxc.rootfs.path entries are in: /var/log/lxd/c1/lxc.conf while the last entry is the default storage pool, if I remove the last entry and start the container with the forkstart everything works OK.

Reason for this is I'm using LXD in a offline setup where access to images (or the internet doesnt exist), so I manually overlayfs mount rootfs'es for my containers; this method worked in previous LXD releases. Do you have a recommendation on how to attack that scenario? Or should I migrate all of my processing back to LXC.

**Comment by stgraber** [comment]
If you want normal LXD but offline, you can just run `lxc image export` on a connected system, then bring in the files to your server and import them with `lxc image import`, the rest will then work as normal.

Now if you need your custom overlayfs setup in an alternate path, then that may be better handled with just LXC.
