### ISSUE TITLE
Proper support for moving between pools

### ISSUE THREAD

**Issue by toby63** [lxc/lxd#7274]
### Required information:
 * Distribution: Debian
 * Distribution version: Testing
   * Kernel version: 5.5.0-1-amd64
   * LXC version: 4.0.2
   * LXD version: 4.0.1
   * Storage backend in use: btrfs and dir

### Issue description:
When I tried to move a container to a another storage pool (on the same host), I got an error message:
> lxc move debian1 debian1 -s pool2 --instance-only
Error: Add instance info to the database: This instance already exists

More information:
I tried to move from a btrfs pool to a dir pool.

I had to rename the destination container name for the command to be sucessful.
> lxc move debian1 debian1a -s pool2 --instance-only

### Expected behaviour:
Being able to move container without renaming.

### Disclaimer: 
Maybe I missunderstand the command, but then see this as a feature request, to also be able to use my command :wink:.
Thanks in advance.

**Comment by stgraber** [comment]
So there's currently no API to just move an instance between storage pools.
Instead what we do is copy it, which requires a new unique name, and then delete the source.

We have some minimal support for server side move, but that's only supported for transfers within a cluster at this time and in that case, still doesn't let you move across pool.


So I think the right solution here is for a new `MoveInstance` function in our storage API which does the migration, update the DB record and we'd then follow that with either updating the existing root device for the container or by copying it up from its expanded config and changing the pool to the new location.

This would then allow for proper move between pools without having to do copy+delete.

**Comment by stgraber** [comment]
@tomponline thoughts on the approach? Seems reasonably easy with the logic we have in place now.

**Comment by tomponline** [comment]
@stgraber this sounds fine. I expect we would also need a MoveCustomVolume too, although that would likely need to check if it is in use by any instances.

**Comment by tomponline** [comment]
Added to ideas tracker.

**Comment by stgraber** [comment]
So I wouldn't automatically move any custom volume along with the instance, but yeah, we'd want the same API to be able to move custom volumes and update any reference to them assuming nothing has them mounted at the time.

**Comment by vvolas** [comment]
I dont know if it related, but I have same problem when trying to move from 1 cluster member to another and change storage pool from **ssd** to **hdd**. It leaves machine on same **ssd** pool.

```
root@universe-linux:/var/snap/lxd/common/lxd# lxc move --storage **hdd** salt-user --target cluster-linux
root@universe-linux:/var/snap/lxd/common/lxd# lxc list salt-user
+-----------+---------+------+--------------+----------+-----------+-----------+---------------+
|   NAME    |  STATE  | IPV4 | STORAGE POOL | PROFILES |   TYPE    | SNAPSHOTS |   LOCATION    |
+-----------+---------+------+--------------+----------+-----------+-----------+---------------+
| salt-user | STOPPED |      | ssd          | default  | CONTAINER | 0         | cluster-linux |
```
I looked at the lxd.log on both machines but didint saw anything interesting.

Could this be related to profile? Since default profile is   
```
root:
    path: /
    pool: ssd
    type: disk
```

**Comment by vpranav5** [comment]
Hi, Can I be tentatively assigned this issue?

**Comment by stgraber** [comment]
Done!

**Comment by WilliamGrossKC** [comment]
Hi, Im working with vpranav5 on this issue. We have a few questions if that is ok. We want to know what files we are modifying  to create the Move Instance method and the MoveCustomVolume method and want to know if we should create a whole new branch for development locally. Unfortunately, whenever we try to follow the Adding Your Fork Remote instruction we get a permission denied error. Thanks! @stgraber

**Comment by stgraber** [comment]
You should hit the fork button on Github and then use `git clone ssh://git@github.com/WilliamGrossKC/lxd` to get a local clone that you can push to.

I think the plan for this one is:
 - Add a new `MoveInstance` to the `lxd/storage` package with a signature like this:
```go
MoveInstance(inst instance.Instance, target Pool, op *operations.Operation) error
```
 - Have this function use `MigrateInstance` and `CreateInstanceFromMigration` to move the data across, update the DB record as needed and finally delete the source from its storage pool.
 - Extend api.InstancePost to add a `Pool string` entry that the client would use to trigger such a server-side move
 - Update `lxc/move.go` to use `MigrateContainer` in the client codebase combined with that new `Pool` field to trigger it
 - Update `lxd/instance_post.go` on the server side to detect that `Pool` field and trigger the new `MoveInstance` logic.

@tomponline how does that sound to you?

**Comment by tomponline** [comment]
@stgraber sounds viable, however some careful consideration is going to be needed to get the `CreateInstanceFromMigration` to create it on the correct pool.

@WilliamGrossKC take a look at the `CreateInstanceFromCopy` function as this new function will share much of the same makeup.

For consistency with `CreateInstanceFromCopy` and `RefreshInstance`, the pool represented by the `b` variable (i.e the instantiated backendLXD struct) should be the target pool (so there shouldn't need to be a `target` argument in the function).

Instead there should just be a `src instance.Instance` argument that contains the source instance to be moved (which will then be inspected internally using `GetPoolByInstance(b.state, src)` to provide the `srcPool` used with `MigrateInstance`.

The target pool therefore is provided by the pool of the instantiated backendLXD struct that `MoveInstance` is being run on.

**Comment by vpranav5** [comment]
@stgraber Apologies for the late response and thanks for your help! What specifically should we update in lxc/move.go? We're a little confused on how to use the Pool field with MigrateContainer since we are adding the Pool field in api.InstancePost and not in api.ContainerPost. Also, in lxd/instance_post.go, should we be making our call to our new MoveInstance function within the containerPostClusteringMigrate function?
