### ISSUE TITLE
File share from lxd-client on Mac onto the lxd container running on a VM 

### ISSUE THREAD

**Issue by rgupta1993** [lxc/lxd#7275]
# Required information

 * Distribution: snap lxd
 * Distribution version:
Client version: 4.0.0
Server version: 3.21
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.10.0-1062.18.1.el7.x86_64
   * LXC version: 3.2.1
   * LXD version: 3.21
   * Storage backend in use:
  storage: zfs
  storage_version: 0.8.3-1
# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
Currently, I have a Virtualbox CentOS 7 VM managed by Vagrant running LXD server.
On this VM, currently have a CentOS 6 container running.
I have a MAC host OS running lxd-client. I can run lxc commands on my mac to access the container.
I want to mount the folders from my mac onto the container. Is this possible?
I could do that from my VM to the container using the command:
`lxc config device add <container-name> <name> disk source=<path on my vm> path=<path on my container>.
But when I try to do the same command from my MAC, looks like it cannot find the path on my host MAC and points only to the VM.

How can I achieve the use case of mounting the folders on my mac to the container?

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by rgupta1993** [comment]
I get the following error: Error: Invalid devices: Device validation failed "<device name>": Missing source <source path> for disk <device name>

**Comment by stgraber** [comment]
All LXD path configuration is relative to the LXD host, not to the client.

That means that if you do:

    lxc config device add NAME blah disk source=/home/blah path=/home/blah

You need /home/blah in your VM to be what you want to expose as /home/blah in your container.

Having this magically happen through the LXD client tool would be problematic on quite a few level. First, we'd need to build a cross-platform file sharing solution which isn't really something we have any expertise in. Then you'd have the problem of having to always connect the client to LXD before you can start the container, if the client disconnects for any reason, you'd lose the mount. This isn't really possible and if it were, we'd still be unlikely to do it :)

In your case, what you need to do is use the built-in file sharing in your VM technology (VirtualBox), assuming it has one. Use that to map a directory from your host into the VM, at which point you can tell LXD to map that into the container.
