### ISSUE TITLE
Tuning tmpfs in LXD containers

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#7279]
LXD 4.0.1
Ubuntu Bionic

So I should probably have picked up on this long ago, but today it was brought to my attention that LXD containers by default "inherit" the size allocation of tmpfs mounts from the host system. As we have lots of RAM all our unprivileged containers have access to about 189GB of memory directly in /dev/shm, /run and /sys/fs/cgroup

This is no good, as while containers can only exhaust the amount of RAM afforded to them by their profile - they can spill over into swap space and fill up the swap partition with junk, if they wanted to.

Besides 189GB is probably completely overkill - wouldn't 1GB be plenty?

I have been searching around and there are hints out there that this can be tuned in LXD config for my containers but I am unclear how I should achieve this exactly.

I have tried just scaling /dev/shm for starters using an fstab entry on the host, and while it works on the host level it does not take effect inside the container. Besides, this does not seem like the right approach whether inside the container or on the host level.

What is the deal here? Thanks!

**Comment by stgraber** [comment]
`tmpfs` is indeed constrained by the cgroup limits, so while the user can allocate far more memory than they have, they can't run you out of memory through it.

Looking around, there is no way that I can find to change the default size of a tmpfs for the entire system. It always uses its documented default of half of the size memory.

The container can certainly specify a `size=` for their various mounts which then makes things look less ridiculous in `df` and others.

I personally would quite welcome a kernel sysctl to override the default size of tmpfs-es given we're dealing with machines taking TB of RAM these days, but I don't know how this would be received upstream.

@brauner what do you think? Think we should whip up a simple patch to make this configurable through sysctl? I don't see us needing to namespace this at all, for cases like @Kramerican, just having a way to say that all tmpfs mounts default to say 2GB would be good enough.

**Comment by stgraber** [comment]
Closing as not a LXD bug, but if @brauner thinks it's worth a kernel patch and it's not particularly hard to write, we'll put it on our list of kernel work to do to make things better.

**Comment by Kramerican** [comment]
Much appreciated @stgraber and @brauner - while they cannot run you out of memory as you say, they could run you out of swap space and create a lot of i/o noise on whatever device holds the swap (usually your OS disk). So it's not a critical issue per-se from my POV, but worrying nonetheless.

In the meantime, could you drop me a hint as to how I would go about modifying `size=` for container "system mounts" in my config? I gave it a shot trying to figure it out this morning, but Google is not being kind to me today (or the various suggestions and docs I can find are quite unclear on this)

Thank you yet again for the excellent support and tremendous work you guys are doing 👍

**Comment by stgraber** [comment]
I would expect that putting /etc/fstab entries would work, assuming systemd doesn't hardcode those things internally.

**Comment by Kramerican** [comment]
Ah I see - well yes that does indeed work (already tried it), but is easily changed by anyone with access to the container, so this would only be cosmetic. I was under the impression you could do config updates on the host level, e.g. adding this to a profile or something like that - but I guess not?

**Comment by stgraber** [comment]
Nope, there's no way to override such things from the host in a way that can't similarly be undone by the user.

**Comment by Kramerican** [comment]
Alright I see - I guess we'll just have to hope @brauner thinks this can be patched in for all of us with lots and lots of RAM :D

**Comment by Kramerican** [comment]
Decided to try and implement something here today, but turns out modifying /etc/fstab doesn't survive container reboots. If I add something like `none /dev/shm tmpfs defaults,nodev,nosuid,noexec,size=1G 0 0` and remount it takes effect, but is ignored on restart.

@brauner Is there anywhere I can "officially" request the aforementioned kernel patch, so this doesn't just vanish at the bottom of a "nice to have" list scribbled on a post-it note somewhere? :O)

I get that this is an absolutely non-critical issue, and I can live with it - but it would be nice to get some control here (mostly due to the theoretical "kill all swap space for everybody" attack contained herein). Thanks.!
