### ISSUE TITLE
Features Querys

### ISSUE THREAD

**Issue by mairajsmamji** [lxc/lxd#7284]
Hi,
I have some query about lxd.
Is there any option to pull VM image from REST API?
Have u any plan to add drbd as storage type? 
is there any option with current raft based cluster to replicate rootfs? for 0 downtime migration.

**Comment by stgraber** [comment]
Questions are usually better suited for https://discuss.linuxcontainers.org

1) Everything the CLI does is done over the REST API, you can always pass `--debug` to see exactly what calls. You can download local images from REST API through /1.0/images/FINGERPRINT/export
2) Kinda, we're unlikely to add it as its own backend but have been considering it as a way to improve migration of block based storage by allowing for background block transfer. For HA storage, our favored option currently is Ceph.
3) Ceph can be used for HA, it's not 0 downtime however. For containers we have CRIU which can do stateful live migration but it's extremely workload dependents and so rarely works. For VMs we don't have live migration support at this time, it's on our roadmap but will likely take a year or so before we have it sorted.
