### ISSUE TITLE
unix-block device dd Permission denied

### ISSUE THREAD

**Issue by ltwell** [lxc/lxd#7291]
# Required information

 * Distribution: ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-28-generic
   * LXC version:4.0.1
   * LXD version:4.0.1
   * Storage backend in use:zfs

# Issue description
i want to use dd to test the raw device but get  Permission denied error

# Steps to reproduce

qemu-img create -f raw test1.img 10g
sudo losetup $(sudo losetup -f) /data/volume/chb/test1.img
lxc config device add chb test1 unix-block source=/dev/loop5 path=/dev/sdb

[root@chb ~]# dd if=/dev/sdb of=/tmp/aa bs=1k count=1
dd: failed to open ‘/dev/sdb’: Permission denied
[root@chb ~]# ll /dev/sdb
brw-rw---- 1 root root 7, 5 May  2 11:59 /dev/sdb
# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
What are the permissions on the /dev/loop5 device on the host?

Shouldn't really matter though...

**Comment by ltwell** [comment]
the permission of /dev/loop5 is 
brw-rw---- 1 root disk 7, 5 May  2 11:55 /dev/loop5 

lxc config show chb --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Oracle 7 amd64 (20200315_07:46)
  image.os: Oracle
  image.release: "7"
  image.serial: "20200315_07:46"
  image.type: squashfs
  raw.lxc: |-
    lxc.cgroup.devices.allow = a
    lxc.cgroup.devices.allow = b 7:5 rwm
  security.privileged: "true"
  volatile.base_image: 3cc8d51bc2f5f436fd822d265c8571df659581ce0b243fff6a384976fedd7924
  volatile.eth0.host_name: veth84b04a67
  volatile.eth0.hwaddr: 00:16:3e:c9:67:2a
  volatile.eth1.host_name: veth382cea4a
  volatile.eth1.hwaddr: 00:16:3e:a5:39:4e
  volatile.idmap.base: "0"
  volatile.idmap.current: '[]'
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  app:
    path: /app
    source: /app
    type: disk
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: virbr1
    type: nic
  root:
    path: /
    pool: default
    type: disk
  test1:
    path: /dev/sdb
    source: /dev/loop5
    type: unix-block
ephemeral: false
profiles:
- default
stateful: false
description: ""

**Comment by stgraber** [comment]
Ok, just for curiosity's sake, does `chmod 777 /dev/loop5` fix the issue somehow?

It really shouldn't, but who knows...

**Comment by ltwell** [comment]
no,the same result
dell@dell-pc:~$ sudo chmod 777 /dev/loop5
dell@dell-pc:~$ ll /dev/loop5
brwxrwxrwx 1 root disk 7, 5 May  3 22:01 /dev/loop5

[root@chb ~]# dd if=/dev/sdb of=/tmp/aa bs=1k count=1
dd: failed to open ‘/dev/sdb’: Permission denied

**Comment by stgraber** [comment]
Ok, can you show `ls -lh /var/snap/lxd/common/lxd/devices/chb/`?

**Comment by stgraber** [comment]
Oh and `cat /proc/self/mountinfo` in the container may be useful too.

**Comment by ltwell** [comment]
ls -lh /var/snap/lxd/common/lxd/devices/chb/

crw-rw---- 1 root root 10, 236 May  3 22:05 unix.mapper--control.dev-mapper-control
brw-rw---- 1 root root  7,   6 May  3 22:05 unix.test1.dev-sdb


[root@chb ~]# cat /proc/self/mountinfo
2818 2169 0:113 /rootfs / rw,relatime master:955 - zfs datapool/default/containers/chb rw,xattr,posixacl
2819 2818 0:125 / /dev rw,relatime - tmpfs none rw,size=492k,mode=755
2820 2818 0:119 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
2821 2822 0:119 /sys/net /proc/sys/net rw,nosuid,nodev,noexec,relatime - proc proc rw
2822 2820 0:119 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
2823 2820 0:119 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
2824 2818 0:126 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
2825 2824 0:126 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs rw
2826 2825 0:126 / /sys/devices/virtual/net rw,relatime - sysfs sysfs rw
2827 2826 0:126 /devices/virtual/net /sys/devices/virtual/net rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
2828 2819 0:114 / /dev/mqueue rw,relatime - mqueue mqueue rw
2829 2819 0:6 /fuse /dev/fuse rw,nosuid,noexec,relatime master:2 - devtmpfs udev rw,size=16293340k,nr_inodes=4073335,mode=755
2830 2819 0:6 /net/tun /dev/net/tun rw,nosuid,noexec,relatime master:2 - devtmpfs udev rw,size=16293340k,nr_inodes=4073335,mode=755
2831 2822 0:95 / /proc/sys/fs/binfmt_misc rw,nosuid,nodev,noexec,relatime master:171 - binfmt_misc binfmt_misc rw
2832 2825 0:34 / /sys/firmware/efi/efivars rw,nosuid,nodev,noexec,relatime master:13 - efivarfs efivarfs rw
2833 2825 0:50 / /sys/fs/fuse/connections rw,nosuid,nodev,noexec,relatime master:33 - fusectl fusectl rw
2834 2825 0:33 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime master:12 - pstore pstore rw
2835 2825 0:21 / /sys/kernel/config rw,nosuid,nodev,noexec,relatime master:34 - configfs configfs rw
2836 2825 0:8 / /sys/kernel/debug rw,nosuid,nodev,noexec,relatime master:30 - debugfs debugfs rw
2837 2825 0:7 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime master:8 - securityfs securityfs rw
2838 2825 0:12 / /sys/kernel/tracing rw,nosuid,nodev,noexec,relatime master:31 - tracefs tracefs rw
2839 2819 0:112 / /dev/lxd rw,relatime - tmpfs tmpfs rw,size=100k,mode=755
2843 2819 0:51 /snap/lxd/common/lxd/devices/chb/unix.test1.dev-sdb /dev/sdb rw,nodev,relatime master:931 - zfs rpool/var rw,xattr,posixacl
2844 2819 0:51 /snap/lxd/common/lxd/devices/chb/unix.mapper--control.dev-mapper-control /dev/mapper/control rw,nodev,relatime master:931 - zfs rpool/var rw,xattr,posixacl
2845 2819 0:111 /chb /dev/.lxd-mounts rw,relatime master:933 - tmpfs tmpfs rw,size=100k,mode=711
2846 2820 0:110 /proc/cpuinfo /proc/cpuinfo rw,nosuid,nodev,relatime master:932 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
2847 2820 0:110 /proc/diskstats /proc/diskstats rw,nosuid,nodev,relatime master:932 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
2848 2820 0:110 /proc/loadavg /proc/loadavg rw,nosuid,nodev,relatime master:932 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
2849 2820 0:110 /proc/meminfo /proc/meminfo rw,nosuid,nodev,relatime master:932 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
2850 2820 0:110 /proc/stat /proc/stat rw,nosuid,nodev,relatime master:932 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
2851 2820 0:110 /proc/swaps /proc/swaps rw,nosuid,nodev,relatime master:932 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
2852 2820 0:110 /proc/uptime /proc/uptime rw,nosuid,nodev,relatime master:932 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
2853 2825 0:110 /sys/devices/system/cpu/online /sys/devices/system/cpu/online rw,nosuid,nodev,relatime master:932 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
2854 2819 0:102 /0 /dev/console rw,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666
2170 2822 0:125 /.lxc-boot-id /proc/sys/kernel/random/boot_id ro,nosuid,nodev,noexec,relatime - tmpfs none rw,size=492k,mode=755
2176 2819 0:131 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666,max=1024
2177 2819 0:131 /ptmx /dev/ptmx rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666,max=1024
1724 2819 0:132 / /dev/shm rw,nosuid,nodev - tmpfs tmpfs rw
1743 2818 0:149 / /run rw,nosuid,nodev - tmpfs tmpfs rw,mode=755
1747 2825 0:151 / /sys/fs/cgroup ro,nosuid,nodev,noexec - tmpfs tmpfs ro,mode=755
1775 1747 0:32 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,xattr,name=systemd
1776 1747 0:38 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpu,cpuacct
1777 1747 0:42 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer
1778 1747 0:40 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,pids
1781 1747 0:39 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_cls,net_prio
1782 1747 0:43 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio
1783 1747 0:45 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset,clone_children
1784 1747 0:44 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
1785 1747 0:46 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory
1786 1747 0:36 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,hugetlb
1787 1747 0:37 / /sys/fs/cgroup/rdma rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,rdma
1788 1747 0:41 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,perf_event
1789 2819 0:152 / /dev/hugepages rw,relatime - hugetlbfs hugetlbfs rw,pagesize=2M
1790 1743 0:153 / /run/user/0 rw,nosuid,nodev,relatime - tmpfs tmpfs rw,size=3269488k,mode=700

**Comment by stgraber** [comment]
Ok, that shows the problem. The filesystem on which LXD resides on your host is mounted with nodev

**Comment by stgraber** [comment]
You need to make sure that the filesystem used to store /var/snap/lxd allows for the creation of device nodes or you won't be able to pass those into containers.

**Comment by stgraber** [comment]
@brauner is there a cheap check we can do to see if the filesystem is nodev at the time we create a device node?

**Comment by brauner** [comment]
> @brauner is there a cheap check we can do to see if the filesystem is nodev at the time we create a device node?

Hotplugged through lxd?

**Comment by brauner** [comment]
The thing is that mknod works just fine with `nodev` so it seems weird to fail just because of `nodev`. `nodev` just let's you fail the open, essentially.

**Comment by stgraber** [comment]
@brauner if someone adds a `unix-block` or `unix-char` device, we should fail if `/var/lib/lxd/devices` is mounted nodev.
I'm looking for a cheap way to determine if `/var/lib/lxd/devices` is nodev.

**Comment by stgraber** [comment]
Well, technically, same thing with usb, gpu, ... anything that has us use `/var/lib/lxd/devices` to store a device node.

**Comment by brauner** [comment]
> @brauner if someone adds a `unix-block` or `unix-char` device, we should fail if `/var/lib/lxd/devices` is mounted nodev.
> I'm looking for a cheap way to determine if `/var/lib/lxd/devices` is nodev.

Oh, I get it.

**Comment by brauner** [comment]
> @brauner if someone adds a `unix-block` or `unix-char` device, we should fail if `/var/lib/lxd/devices` is mounted nodev.
> I'm looking for a cheap way to determine if `/var/lib/lxd/devices` is nodev.

When LXD starts, create a dummy device node on /var/lib/lxd/devices and then try to open at when you inject a device.

**Comment by brauner** [comment]
> > @brauner if someone adds a `unix-block` or `unix-char` device, we should fail if `/var/lib/lxd/devices` is mounted nodev.
> > I'm looking for a cheap way to determine if `/var/lib/lxd/devices` is nodev.
> 
> When LXD starts, create a dummy device node on /var/lib/lxd/devices and then try to open at when you inject a device.

You could e.g. use `c 5 0` which is `/dev/tty`.

**Comment by stgraber** [comment]
Yeah, I guess we could just do the test on startup and then record the result in the state struct, then check that and fail when creating device nodes.

**Comment by stgraber** [comment]
I'll send a branch that does that, will make debugging such issues much easier.

**Comment by ltwell** [comment]
OK I got it , in my /etc/fstab the /var is mounted as  rpool/var /var zfs nodev,relatime 0 0
I can use dd to read/write sdb after remove the nodev option
[root@chb dev]# dd if=/dev/sdb of=/tmp/aa bs=1k count=1
1+0 records in
1+0 records out
1024 bytes (1.0 kB) copied, 0.0202347 s, 50.6 kB/s
[root@chb dev]# dd if=/dev/zero of=/dev/sdb bs=1k count=1
1+0 records in
1+0 records out
1024 bytes (1.0 kB) copied, 0.0238254 s, 43.0 kB/s

**Comment by stgraber** [comment]
Keeping open as we want to add a better error for this.
