### ISSUE TITLE
VM: user.network-config is not copied to config.iso

### ISSUE THREAD

**Issue by vitfri** [lxc/lxd#7292]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux XYZ 4.15.0-39-generic #42~16.04.1 SMP Mon Jan 28 12:24:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: Client version: 4.0.0
   * LXD version: Server version: 4.0.0
   * Storage backend in use: dir
   * snap info lxd: installed: git-428b34b

# Issue description
When creating a VM, custom network-config file, generated with help of user.network-config, is created, but not added to config.iso

# Steps to reproduce
 1. lxc init  ubuntu:20.04 c2-master --vm  --type c2-m1 --profile vm
 2. cat v1.nw.cfg.yaml | lxc config set --debug c2-master user.network-config -
 3. lxc start c2-master

# Information to attach
### v1.nw.cfg.yaml:
```
version: 1
config:
  - type: physical
    name: enp5s0
      subnets:
      - type: static
        ipv4: true
        control: auto
        address: 10.68.80.106/24
        gateway: 10.68.80.1
```
### vm profile:
```
name: vm-base
description: VM base profile
config:
  boot.autostart: "true"
  environment.http_proxy: ""
  security.nesting: "true"
  security.privileged: "true"
devices:
  enp5s0:
    name: enp5s0
    nictype: macvlan
    parent: eno1
    type: nic
  root:
    path: /
    pool: local
    type: disk
  config:
    source: cloud-init:config
    type: disk
```
### cloud-init files:
```
sudo ls -l /var/snap/lxd/common/lxd/storage-pools/local/virtual-machines/c2-master/config/cloud-init/
total 16
-r-------- 1 lxd root  50 maj  2 09:16 meta-data
-r-------- 1 lxd root 270 maj  2 09:16 network-config
-r-------- 1 lxd root 752 maj  2 09:16 user-data
-r-------- 1 lxd root  14 maj  2 09:16 vendor-data

sudo mount /var/snap/lxd/common/lxd/virtual-machines/c2-master/config.iso /mnt/x/
sudo ls -la /mnt/x
total 8
d--x------ 2 root root 2048 maj  2 09:16 .
drwxr-xr-x 6 root root 4096 maj  2 09:21 ..
-r-------- 1 root root   50 maj  2 09:16 meta-data
-r-------- 1 root root  752 maj  2 09:16 user-data
-r-------- 1 root root   13 maj  2 09:16 vendor-data
```

**Comment by stgraber** [comment]
That's normal, cloud-init config drives do not support network config data.

**Comment by vitfri** [comment]
Ubuntu 20.04 tries to read network-config, actually.
You can see it in the /var/log/cloud-init.log of the new instance.

How to inject network settings into VM?

**Comment by stgraber** [comment]
Your best bet right now is to use `images:ubuntu/focal/cloud` which is Ubuntu 20.04 with cloud-init and includes `lxd-agent` which takes care of passing all the data (including network-config) to cloud-init.

When using those images, make sure you don't have a `cloud-init:config` device as that would take precedence and still not get you network-config.

**Comment by vitfri** [comment]
I have tested `images:ubuntu/focal/cloud` that you recommended.
I could inject desired `network-config`, though `openssh-server` and `curl` were missing in this image, but these are standard in `ubuntu:20.04`. So the images are different.

Beside that, following log shows that even `ubuntu:20.04` tries to access `network-config`
```
2020-05-02 07:15:43,983 - util.py[DEBUG]: Running command ['mount', '-o', 'ro', '-t', 'auto', '/dev/sdb', '/run/cloud-init/tmp/tmpzv36jssd'] with allowed return codes [0] (shell=False, capture=True)
2020-05-02 07:15:43,993 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpzv36jssd//user-data (quiet=False)
2020-05-02 07:15:43,993 - util.py[DEBUG]: Read 752 bytes from /run/cloud-init/tmp/tmpzv36jssd//user-data
2020-05-02 07:15:43,993 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpzv36jssd//meta-data (quiet=False)
2020-05-02 07:15:43,993 - util.py[DEBUG]: Read 50 bytes from /run/cloud-init/tmp/tmpzv36jssd//meta-data
2020-05-02 07:15:43,994 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpzv36jssd//vendor-data (quiet=False)
2020-05-02 07:15:43,994 - util.py[DEBUG]: Read 13 bytes from /run/cloud-init/tmp/tmpzv36jssd//vendor-data
2020-05-02 07:15:43,994 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpzv36jssd//network-config (quiet=False)
2020-05-02 07:15:43,994 - util.py[DEBUG]: Running command ['umount', '/run/cloud-init/tmp/tmpzv36jssd'] with allowed return codes [0] (shell=False, capture=True)
2020-05-02 07:15:43,998 - util.py[DEBUG]: Attempting to load yaml from string of length 50 with allowed root types (<class 'dict'>,)
2020-05-02 07:15:43,999 - DataSourceNoCloud.py[DEBUG]: Using data from /dev/sdb
```

Wouldn't following addition solve this issue?
```
diff --git a/lxd/device/disk.go b/lxd/device/disk.go
index 39a4ec940..8c7dfb85d 100644
--- a/lxd/device/disk.go
+++ b/lxd/device/disk.go
@@ -1530,6 +1530,14 @@ func (d *disk) generateVMConfigDrive() (string, error) {

        instanceConfig := d.inst.ExpandedConfig()

+       networkConfig := instanceConfig["user.network-config"]
+       if networkConfig != "" {
+               err = ioutil.WriteFile(filepath.Join(scratchDir, "network-config"), []byte(networkConfig), 0400)
+               if err != nil {
+                       return "", err
+               }
+       }
+
        // Use an empty user-data file if no custom vendor-data supplied.
        vendorData := instanceConfig["user.vendor-data"]
        if vendorData == "" {

```

**Comment by stgraber** [comment]
https://github.com/canonical/cloud-init/blob/master/cloudinit/sources/DataSourceConfigDrive.py#L135

You'll see the it states that `network-config` is to be ENI formatted. So yes, it does look for a file of that name, but it is not a network-config as you would normally use, nor would it work with anything using netplan.

The alternative JSON that's allowed in there is similarly a custom OpenStack format which also doesn't line up with the generic network-config format used by LXD.

**Comment by stgraber** [comment]
Currently your options are:
 - ubuntu:20.04 => cloud-init won't run without the config drive, config drive cannot have network config
 - images:ubuntu/20.04/cloud => More minimal build but has a fully working agent and full cloud-init support

We have a bug at https://bugs.launchpad.net/cloud-images/+bug/1873809 which once fixed will eventually allow `ubuntu:20.04` to work without the config drive in the same way as `images:ubuntu/20.04/cloud`. Once ubuntu:20.04 is confirmed to fully behave the way we want, we'll look at pushing the logic back to ubuntu:18.04 and ubuntu:16.04. Until then, the community images (images:ubuntu/18.04/cloud and images:ubuntu/16.04/cloud) are your best bet for those as well.

There is also work on the cloud-init roadmap to have them treat LXD as a first class cloud so we don't need to rely on any of those config drives and NoCloud datasources.

**Comment by OddBloke** [comment]
@stgraber I believe (and have confirmed with a few launches locally) that LXD uses the `NoCloud` DS, not the `ConfigDrive` DS. That _does_ have support for cloud-init's networking format: https://github.com/canonical/cloud-init/blob/master/cloudinit/sources/DataSourceNoCloud.py#L187-L188, https://github.com/canonical/cloud-init/blob/master/cloudinit/sources/DataSourceNoCloud.py#L227-L232

Could we reopen this and have a look at fixing it? (We're currently integrating LXD VMs into cloud-init's integration testing framework, and this is tripping us up; we can work around it, but it'd be nice to not have to.)

**Comment by stgraber** [comment]
When the LXD agent is used, NoCloud is used in the exact same way as in the containers which does include rendering the network config file too.

The only case where network config is ignored is when the user attaches a config drive to the instance.

**Comment by OddBloke** [comment]
NoCloud is used for containers, for VMs with lxd-agent _and_ for VMs without the LXD agent. Using:

```
% lxc profile show cloud-init-config
config: {}
description: Default LXD profile for bionic VMs
devices:
  config:
    source: cloud-init:config
    type: disk
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: cloud-init-config
```

If I launch a bionic instance (without the LXD agent, so `password.yaml` is backdooring it for SSH access):

```
$ lxc launch ubuntu:b --vm --profile cloud-init-config -c user.user-data="$(cat user-data/password.yaml)"
Creating the instance
Instance name is: bold-pelican            
Starting bold-pelican
```

Then we can see that NoCloud is used, but there is not a seed directory:

```
% ssh ubuntu@10.236.135.119 -- cloud-id
ubuntu@10.236.135.119's password: 
nocloud
% ssh ubuntu@10.236.135.119 -- ls /var/lib/cloud/seed/
ubuntu@10.236.135.119's password: 
```

ConfigDrive is only used when an OpenStack platform is detected. NoCloud also handles configuration ISOs, and is generally what people are using when they specify a "config drive" to cloud-init.

**Comment by stgraber** [comment]
Yeah, I don't remember the internal details of cloud-init, but basically, if you don't have the lxd-agent, then your config comes from the config drive you've attached and cloud-init does not support reading a YAML network v2 from that.

So if you have a lxd-agent, then the data for user/vendor/network is copied into /var/lib/cloud/seed and the instance rebooted.

**Comment by OddBloke** [comment]
> your config comes from the config drive you've attached and cloud-init does not support reading a YAML network v2 from that.

Right, I think this understanding is mistaken. LXD mounts a `cidata` drive:

```
$ ls /dev/disk/by-label/cidata -lah
lrwxrwxrwx 1 root root 9 Nov 24 15:09 /dev/disk/by-label/cidata -> ../../sdb
```

and that's what cloud-init is using:

```
$ cloud-init status --long
status: done
time: Tue, 24 Nov 2020 15:09:25 +0000
detail:
DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
```

The lines of code which do this are https://github.com/canonical/cloud-init/blob/master/cloudinit/sources/DataSourceNoCloud.py#L113-L137; this mounts the ISO and then reads it as a regular seed directory: compare those lines to the seed directory path: https://github.com/canonical/cloud-init/blob/master/cloudinit/sources/DataSourceNoCloud.py#L87-L95. Both call `util.pathprefix2dict` to generate a dict of `{filename: content}` and then pass it to `_merge_new_seed`.

If there's a `network-config` file in the ISO, it should be treated the same as a `network-config` file in the seed directory.

(I don't have a setup to build LXD locally and VMs don't support arbitrary disks yet, so I don't think there's an easy way for me to demonstrate this working, unfortunately.)

**Comment by stgraber** [comment]
`cidata` is only present if you have added the `cloud-init:config` drive which is only used for legacy images that do not have the agent. Raw disks can easily be attached to LXD VMs, this has always been supported, so it'd be easy for you to test :)

I remember reading some cloud-init code which specifically didn't support the full network-config case, though that may have been in an older version or just the wrong code path.

So when the agent is present, you get:

```
stgraber@castiana:~$ lxc init images:ubuntu/20.04/cloud u2 --vm
Creating u2
stgraber@castiana:~$ lxc config set u2 user.user-data foo
stgraber@castiana:~$ lxc config set u2 user.vendor-data bar
stgraber@castiana:~$ lxc config set u2 user.network-config baz
stgraber@castiana:~$ lxc start u2
stgraber@castiana:~$ lxc exec u2 bash
root@u2:~# ls -lh /var/lib/cloud/seed/nocloud-net/
total 16K
-rw-r--r-- 1 root root 36 Nov 24 17:55 meta-data
-rw-r--r-- 1 root root  4 Nov 24 17:55 network-config
-rw-r--r-- 1 root root  4 Nov 24 17:55 user-data
-rw-r--r-- 1 root root  4 Nov 24 17:55 vendor-data
root@u2:~# cat /var/lib/cloud/seed/nocloud-net/meta-data 
instance-id: u2
local-hostname: u2

root@u2:~# cat /var/lib/cloud/seed/nocloud-net/user-data 
foo
root@u2:~# cat /var/lib/cloud/seed/nocloud-net/vendor-data 
bar
root@u2:~# cat /var/lib/cloud/seed/nocloud-net/network-config 
baz
root@u2:~# exit
```

When the config drive is used, you indeed don't have a `network-config` file. We'll push a change that adds it and hope that this doesn't break anything on older distros :)

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/pull/8182
