### ISSUE TITLE
LXD 4.0.1 on Fedora 32 - No IPv4 address assigned to container with or without cgroup v2

### ISSUE THREAD

**Issue by chrispatrik** [lxc/lxd#7294]
* Distribution: Fedora
 * Distribution version: 32

# Issue description
With a Fedora 32 host, containers do not get an IPv4 address
so networking does not work in the container. This happens if cgroup v2 is enabled
or not on the host. I tried various Fedora containers and Ubuntu and they all had the same
problem.

# Steps to reproduce

 1. Create a container. e.g. **lxc launch images:fedora/32/amd64 fedora32**
 2. **lxc list** shows an IPv6 address, but no IPv4 address. Disabling cgroup v2 has no effect.

See attached files for output of various commands and lxd.log

[client-debug.txt](https://github.com/lxc/lxd/files/4569371/client-debug.txt)
[lxc-config-expanded.txt](https://github.com/lxc/lxd/files/4569372/lxc-config-expanded.txt)
[lxc-monitor.txt](https://github.com/lxc/lxd/files/4569373/lxc-monitor.txt)
[lxd.log.txt](https://github.com/lxc/lxd/files/4569374/lxd.log.txt)

**Comment by chrispatrik** [comment]
[lxc-info.txt](https://github.com/lxc/lxd/files/4569379/lxc-info.txt)

**Comment by stgraber** [comment]
@chrispatrik this is most likely firewalld making a mess on your system, see our networking doc on how to have it play ball.

**Comment by chrispatrik** [comment]
@stgraber - thanks for the quick response. This command fixed it after rebooting:

`sudo firewall-cmd --zone=trusted --change-interface=lxdbr0 --permanent`

I don't remember doing that for previous releases but I may have. Thanks again.
