### ISSUE TITLE
Ambiguous error message from lxc config 

### ISSUE THREAD

**Issue by jtroup** [lxc/lxd#7295]
Using lxd 4.0.1 on Ubuntu 20.04:

```
🙂 james@malefic:~$ lxc config device add instance-name device-name disk source=/some/path path=/some/path
Error: not found
🙂 james@malefic:~$ 
```

It turns out (in my particular case) that I had typo-d 'instance-name', but it'd be easier if the error message was explicit about what wasn't found.

**Comment by stgraber** [comment]
Duplicate of https://github.com/lxc/lxd/issues/5548
