### ISSUE TITLE
Have zfs driver retry for a while on EBUSY

### ISSUE THREAD

**Issue by xsoalokinx** [lxc/lxd#7296]
# Required information

 * Distribution: Gentoo/Linux
 * The output of "lxc info" or if that fails:

config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.0.2.15:8443
  - '[fec0::4faa:458f:611e:fb4c]:8443'
  - 10.100.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
  certificate_fingerprint: 
  driver: lxc
  driver_version: 3.0.3
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "false"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.28-gentoo
  lxc_features:
    cgroup2: "false"
    mount_injection_file: "false"
    network_gateway_device_route: "false"
    network_ipvlan: "false"
    network_l2proxy: "false"
    network_phys_macvlan_mtu: "false"
    network_veth_router: "false"
    seccomp_notify: "false"
  project: default
  server: lxd
  server_clustered: false
  server_name: neo
  server_pid: 5239
  server_version: "3.23"
  storage: zfs
  storage_version: 0.8.3-1

# Issue description

When stopping a container with `lxc stop c1` it fails to unmount the containers filesystem. Manually unmounting it with 'zfs unmount neo-root/data/lxd-storage/containers/c1' does work after the container was stopped. I can confirm that deleting a container, is also properly destroying the filesystem. Also, upon viewing lxc info, it appears the lxc features are all disabled.

# Steps to reproduce

 1. lxc launch ubuntu:18.04 c1
 2. lxc stop c1

# Information to attach

Here is some output from daemon log.

`May  3 22:01:17 neo lxd[5239]: t=2020-05-03T22:01:17-0400 lvl=info msg="Shutting down container" action=shutdown created=2020-05-03T22:00:50-0400 ephemeral=false name=c1 project=default timeout=-1s used=2020-05-03T22:00:55-0400

May  3 22:01:38 neo lxd[5239]: t=2020-05-03T22:01:38-0400 lvl=eror msg="The stop hook failed" container=c1 err="Failed to run: zfs unmount neo-root/data/lxd-storage/containers/c1: umount: /var/lib/lxd/storage-pools/default/containers/c1: target is busy.\ncannot unmount '/var/lib/lxd/storage-pools/default/containers/c1': umount failed"

May  3 22:01:38 neo lxd[5239]: t=2020-05-03T22:01:38-0400 lvl=info msg="Shut down container" action=shutdown created=2020-05-03T22:00:50-0400 ephemeral=false name=c1 project=default timeout=-1s used=2020-05-03T22:00:55-0400`

**Comment by stgraber** [comment]
Does 'lxc stop --force' hit the same issue?

**Comment by xsoalokinx** [comment]
> Does 'lxc stop --force' hit the same issue?

Yes, it does.

**Comment by stgraber** [comment]
Ah, that's somewhat unusual. We've had some cases where clean shutdown cause some processes to somehow create kernel references to files on zfs, preventing the unmount for a while until the kernel is done expiring things. But force usually doesn't hit the same issue.

In any case, we used to have retry logic for unmount when it hits EBUSY, we should probably re-introduce that and see if that helps. Ultimately this is either a legitimate issue on your system (an active process having an open file from that dataset) or more likely a kernel bug keeping such a reference.

**Comment by xsoalokinx** [comment]
> Ah, that's somewhat unusual. We've had some cases where clean shutdown cause some processes to somehow create kernel references to files on zfs, preventing the unmount for a while until the kernel is done expiring things. But force usually doesn't hit the same issue.
> 
> In any case, we used to have retry logic for unmount when it hits EBUSY, we should probably re-introduce that and see if that helps. Ultimately this is either a legitimate issue on your system (an active process having an open file from that dataset) or more likely a kernel bug keeping such a reference.

Thank you for your time on this issue, could you refer me to some patch to add this retry logic back? Will test further. Thank you!
