### ISSUE TITLE
Issue using nfs on lxd containers

### ISSUE THREAD

**Issue by rgupta1993** [lxc/lxd#7306]
# Required information

 * Distribution: snap lxd
 * Distribution version:
      Client version: 4.0.0
      Server version: 3.21
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.10.0-1062.18.1.el7.x86_64
   * LXC version: 3.2.1
   * LXD version: 3.21
   * Storage backend in use:
         storage: zfs
         storage_version: 0.8.3-1

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one:
I a using NFS mounting to mount the folder on my mac to the LXD container running inside the VM on my mac. I have a NFS server running on my host mac. When I try to run nfs mount command from container client, I reciever errors:
mount.nfs: Connection reset by peer 
and
mount.nfs: Broken pipe

Is there anything specific about lxd config that should be done in order to use nfs? 
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
NFS cannot be used inside unprivileged containers, it can sometimes be used with some apparmor workarounds inside a privileged container but that tends to still be pretty tricky.

The errors you're reporting suggest network issues, can your container properly reach the host, is your host running some kind of firewall? You may also want to look at sshfs for something that works in unprivileged containers and tends to be a fair bit easier to debug :)

(Closing as not a LXD issue but likely environment issue or kernel security restrictions, such questions are usually better handled at https://discuss.linuxcontainers.org)
