### ISSUE TITLE
Tweak to `lxc info`

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7319]
`lxc info` could do with some cleanup. It currently looks YAML-ish even though it's not but then does a pretty bad job at showing some of the information we have available.

Some ideas:
 - Only show location if clustered
 - Don't bother showing the remote
 - Show last used date
 - Render snapshots as a table (with more details)
 - Merge the Ips section into the resources net section
 - Show backups if present

**Comment by grant-he** [comment]
My group would also like to tentatively claim this issue. Thank you!

**Comment by stgraber** [comment]
Thanks, assigned to you.

This is one of the more subjective one as it's really about making it more user friendly, so best will be to play with editing `lxc/info.go` a bit (for the instance aspect of it as that's what that issue is about) and propose some alternative ways for it to render the same information as well as extend what it displays a bit to cover more of what we know about instances.

Turning the snapshot list into a table is probably a good start as that will also make it easier to show more details on those snapshots. Then looking at how to better present the devices and their usage and then finish off by cleaning up the other fields.

**Comment by stgraber** [comment]
@grant-he Do you still intend to work on this or should we un-assign so someone else can have a go at it?

**Comment by grant-he** [comment]
Let's have someone else have a go at it.

**Comment by marsblkm** [comment]
@stgraber Would you mind if I give this one a go?

**Comment by stgraber** [comment]
@marsblkm that'd be great! assigned it to you

**Comment by marsblkm** [comment]
I went through the codebase again and realised that there is an exisiting method called `RenderTable` that potentially can be used in this case. 

I will try to re-work on the pr, using the same exisiting method for the above scenarios.

**Comment by marsblkm** [comment]
To test what I have changed, I simply launch an instance and snapshot it. Below is what I got by running ```lxc info ubuntuone```

I believe this ticks some of the boxes mentioned in this ticket. Thoughts? @stgraber 

```
marsblkm@localhost:~/go/src/github.com/lxc/lxd$ lxc info ubuntuone
Name: ubuntuone
Location: test_lxd_cluster
Architecture: x86_64
Created: 2021/07/27 13:54 UTC
Last Used: 2021/07/28 10:52 UTC
Status: Running
Type: container
Profiles: default
Pid: 9505
Resources:
  Processes: 36
  CPU usage:
    CPU usage (in seconds): 9
  Memory usage:
    Memory (current): 300.88MB
    Memory (peak): 451.83MB
  Network usage:
    eth0:
      Bytes received: 19.45MB
      Bytes sent: 107.91kB
      Packets received: 1719
      Packets sent: 1373
      Ips:
        inet	240.126.0.132	veth33f96c58
        inet6	fe80::216:3eff:fefa:3373	veth33f96c58
    lo:
      Bytes received: 3.40kB
      Bytes sent: 3.40kB
      Packets received: 36
      Packets sent: 36
      Ips:
        inet	127.0.0.1
        inet6	::1
Snapshots:
+-----------------+----------------------+------------+----------+
|      NAME       |       TAKEN AT       | EXPIRES AT | STATEFUL |
+-----------------+----------------------+------------+----------+
| bakcupubuntuone | 2021/07/27 13:56 UTC |            | False    |
+-----------------+----------------------+------------+----------+
```

**Comment by stgraber** [comment]
This looks pretty good to me!
I'd replace the `False` with a YES/NO instead.

I'd also add a blank line before the `Resources` and `Snapshots` lines.

For the top section, it may look better to go with:
```
Name: ubuntuone
Status: RUNNING
Type: container
Architecture: x86_64
Location: test_lxd_cluster
PID: 9505
Created: 2021/07/27 13:54 UTC
Last Used: 2021/07/28 10:52 UTC
```

The main changes here are the removal of `Profiles`, some re-ordering, capitalization of PID and capitalization of the status string.

**Comment by marsblkm** [comment]
Updated!
PR here: https://github.com/lxc/lxd/pull/9019
Here is what does it look like:
```
marsblkm@localhost:~$ lxc info ubuntuone
Name: ubuntuone
Status: RUNNING
Type: container
Architecture: x86_64
Location: test_lxd_cluster
Pid: 9505
Created: 2021/07/27 13:54 UTC
Last Used: 2021/07/28 10:52 UTC

Resources:
  Processes: 36
  CPU usage:
    CPU usage (in seconds): 65
  Memory usage:
    Memory (current): 325.85MB
    Memory (peak): 649.14MB
  Network usage:
    eth0:
      Bytes received: 31.96MB
      Bytes sent: 529.34kB
      Packets received: 6739
      Packets sent: 5590
      Ips:
        inet	240.126.0.132	veth33f96c58
        inet6	fe80::216:3eff:fefa:3373	veth33f96c58
    lo:
      Bytes received: 20.29kB
      Bytes sent: 20.29kB
      Packets received: 216
      Packets sent: 216
      Ips:
        inet	127.0.0.1
        inet6	::1

Snapshots:
+-----------------+----------------------+------------+----------+
|      NAME       |       TAKEN AT       | EXPIRES AT | STATEFUL |
+-----------------+----------------------+------------+----------+
| bakcupubuntuone | 2021/07/27 13:56 UTC |            | NO       |
+-----------------+----------------------+------------+----------+
```

**Comment by stgraber** [comment]
I'd replace `Ips` with `IP addresses` too.

**Comment by marsblkm** [comment]
> I'd replace `Ips` with `IP addresses` too.
Got that solved!
