### ISSUE TITLE
Forkproxy logfile size is unbounded

### ISSUE THREAD

**Issue by benaryorg** [lxc/lxd#7332]
# Required information

 * Distribution: Gentoo
 * Distribution version: n/a
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.9
   * LXC version: 3.1.0
   * LXD version: 4.0.0
   * Storage backend in use: btrfs

# Issue description

Proxy devices write logfiles, that's all well and okay unless you have a daemon which does decline connections on purpose when there are too many open connections (currently running IPFS which due to the p2p nature has several thousand connections open at a time).
In that case the forkproxy starts logging lots of error messages like these:

```
Warning: Error while reading data: write udp [::1]:59370->[::1]:4001: write: connection refused
```

Which is all good and well until that file reaches the 1.5T mark and you run out of diskspace ;-)
I haven't found a way to turn off logging (or raise the minumum loglevel  for proxy devices).

Ideally I'd have an option to disable logging for specific devices entirely or set the minimum loglevel needed to log to message.

# Steps to reproduce

 1. use proxy device
 2. get failed connections
 3. diskspace full

# Notes

This is more of a feature request than a bug report so I left out most of the details, if you do need any further information though give me a heads-up and I'll add it.

**Comment by stgraber** [comment]
Yeah, feels like we should move all user-generated log entries to debug, we don't want user action to be able to result in log entries. We'd probably want the `--debug` option of LXD to similarly run the proxy in debug mode though.

**Comment by stgraber** [comment]
@benaryorg as a temporary workaround, you can probably symlink the log file to /dev/null :)

**Comment by stgraber** [comment]
That's assuming we don't delete/create it every time on proxy startup.

**Comment by benaryorg** [comment]
> you can probably symlink the log file to /dev/null :)

Had the same thought.

> That's assuming we don't delete/create it every time on proxy startup.

And the same concern ;-)

However it's actually worse than that if I do use a symlink:

```
Error: Error occurred when starting proxy device, please look in /var/log/lxd/[instance name]/[logfile]
Try `lxc info --show-log [instance name]` for more info
```
