### ISSUE TITLE
expose a way to use -kernel -initrd -append for virtual machines

### ISSUE THREAD

**Issue by raharper** [lxc/lxd#7334]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

When using raw.qemu we can pass -kernel, -initrd,  however due to the -chroot parameter
the filesystem of the host is not easily populated with files that the qemu binary can read.
The current process that works is:

```
lxc init ubuntu-daily:groovy g-vm2
sudo zfs mount rpool/lxd/virtual-machines/g-vm2
cd /var/snap/lxd/common/lxd/virtual-machines/g-vm2
wget https://cloud-images.ubuntu.com/daily/server/server/groovy/current/unpacked/groovy-server-cloudimg-amd64-initrd-generic -O initrd.img
wget https://cloud-images.ubuntu.com/daily/server/server/groovy/current/unpacked/groovy-server-cloudimg-amd64-vmlinuz-generic -O vmlinuz
cp /usr/share/seabios/linuxboot_dma.bin .
cd
sudo zfs unmount rpool/lxd/virtual-machines/g-vm2
lxc config edit g-vm2  # add the following raw.qemu
 raw.qemu: |
   -kernel /var/snap/lxd/common/lxd/virtual-machines/g-vm2/vmlinuz -initrd /var/snap/lxd/common/lxd/virtual-machines/g-vm2/initrd.img -append "console=ttyS0" -bios /var/snap/lxd/common/lxd/virtual-machines/g-vm2/linuxboot_dma.bin
```

This will boot up (you can see in lxc console) but stops in initramfs since
we're missing a root= parameter.  I filed an issue on -append handling; if
that gets fixed then it should work just fine.

Interested in your thoughts on how to get kernel/initrd from host into the
filesystem chroot,  I think the bios bits could be added automatically

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
So short answer is that LXD virtual machines are by design opinionated and many low level options just won't really be possible. Similar to containers where someone who wants something very custom is better off with pure LXC, someone who wants something particularly custom with VMs is going to be better off with pure QEMU.

So we're not going to be putting any effort in exposing this in a more user friendly manner than `raw.qemu` and can't guarantee that `raw.qemu` itself won't be broken as we change some properties of our VMs in the future.

I'm not actually getting any issue with `-chroot` here, as far as I can tell, qemu does open every path you pass it before it chroots. What you need to keep in mind though is that you're in a snap environment, so any path you want to access from outside of the snap environment needs to be prefixed with /var/lib/snapd/hostfs/.

**Comment by raharper** [comment]
ok, I didn't know about the hostfs path.  I'll check that.  

I'd really like to migrate away from rolling our own qemu command tool.  Multipass doesn't expose enough; the raw.qemu is fairly close.  

The other things that would allow us to construct vms "of our design" would be to allow us to supply a qemu conf, instead of the autogenerated one.  Would that be a reasonable alternative?

raw.qemu.conf ? 

In our vmtest scenario, we need to control the disk device drivers (virtio, virtio-scsi, virtio-s390, nvme);  we pass device option parameter (to control disk logical block size, simulate 4k vs 512b sectors; we construct specific disk serial,wwn values, we run both bios and uefi modes
we capture the serial console output to file, for nics, mostly specify the mac address.

I think all of those can be controlled via the conf file, so that would make this low-level control fairly simple and with no real work other than let the user define a conf file.  Thoughts?

**Comment by stgraber** [comment]
You should be able to pass -readconfig through raw.qemu, no?

**Comment by raharper** [comment]
Yes, will it override the existing -readconfig already passed?  (I'll check).  At this time raw.qemu only appends to the command line you're generating so, we'd have to rely upon qemu's cli parsing behavior to "clobber" previous values.

**Comment by stgraber** [comment]
I'm not sure, I'm hoping it does as that would offer an easy way out for you without us adding an option that users may mistake for something they may want to use :)

**Comment by stgraber** [comment]
(We're having enough problems with users incorrectly using `raw.lxc` that we don't want to make it too easy for the same mis-use to happen with qemu)
