### ISSUE TITLE
LXD container loses internet connection after an arbitrary amount of time

### ISSUE THREAD

**Issue by Keraldi** [lxc/lxd#7339]
# Required information

 * Distribution: OpenSUSE Tumbleweed x86_64
 * Distribution version: - (rolling), snapshot of 2020-05-09
 * The output of "lxc info":
   https://gist.github.com/Keraldi/5aaaafafe675a5adfea9ddbdbdb28503#file-lxc-info-log

# Issue description

Container loses internet connection after some time with a bridged connection. I tried to switch to macvlan to test if it occurs there, too but so far failed to change the network type as per found instructions.

Rebooting host fixes this issue for an arbitrary amount of time again.

LAN connections still work, the container can reach host and host can reach the container.
Containername is `docker` (because I made it to hold docker containers).

# Steps to reproduce

 1. `lxd init` with default values on btrfs
 2. `lxc launch ubuntu:20.04 docker`
 3. Confirm internet connection is working in container, i.e. `ping 8.8.8.8`
 4. Wait ~1-2 hours
 5. Confirm internet connection does not work in container, i.e. `ping 8.8.8.8`
 6. Reboot host
 7. Confirm internet connection works again in contaienr, i.e. `lxc exec docker ping 8.8.8.8`

# Information to attach

https://gist.github.com/Keraldi/5aaaafafe675a5adfea9ddbdbdb28503

**Comment by stgraber** [comment]
When things break, can you show `iptables -L -n -v` on the host and in the container?

Both `docker` and `firewalld` have the annoying tendency of messing with the firewall rules in ways that blocks all network traffic for containers going out of the host.

I don't know why this wouldn't affect you right from the start, but if you've got Docker installed on the host too rather than just inside a container, this would be a good place to start :)

In any case, that iptables output should help.

**Comment by Keraldi** [comment]
Docker is only installed in the lxc-container.  
 
iptables with no internet connection in container (has been running for a long time):  
https://gist.github.com/Keraldi/b4e6ba50d7cb80ffdae94ff9004bb798

iptables with internet connection in container (fresh restart):

https://gist.github.com/Keraldi/0d2c7430114e025d844b2500e452fdea

**Comment by stgraber** [comment]
Hmm, if the host doesn't have Docker installed, then why are firewall tables for DOCKER showing up in the host output when no internet is available in the container while they don't when the container has working internet?

**Comment by stgraber** [comment]
Or did `iptables-host` get mixed up with container output somehow in your pastes?

**Comment by Keraldi** [comment]
I did have docker installed temporarily when I was looking for a different error (I wasn't sure if an error was caused by not having an internet connection in the LXC container or missing to create a different firewall rule) and had since uninstalled docker again.
But I think that I hadn't rebooted, so I'll do another go with iptables, I'm sorry, that was an unnecessary confusion. The problem had existed before that and still persists after docker had been uninstalled on the host (and rebooted).

iptables with no internet connection in container:
https://gist.github.com/Keraldi/4f8b8cc379bee5feabd6bd328b0219b5

iptables with internet connection in container
https://gist.github.com/Keraldi/c713cdb280bd88bc476c427cac71ff0d

I'll try to find the exact point when it loses internet connection.

**Comment by Keraldi** [comment]
After monitoring it for 2.5 hours, the connection didn't drop, I'll check back tomorrow, maybe it only happens if it's idle?

**Comment by Keraldi** [comment]
Internet connection has been active without interruption for the past 12 hours now, the following events have occurred:

- BIOS update
- short power outage

As I haven't figured out what triggered it (the dmesg I provided at the beginning has a lot of recurring events around line 1000+ but those include docker0), I suggest closing the issue as I cannot replicate it and it most likely was a user error.  
Though I am fairly certain that docker was not active on the host when then container lost internet connection at least a couple times, I have no logs for those situations (anymore) and I might have mis-remembered the chain of events or docker might have been installed on the host at some point while setting up or installing LXD even if I had removed it afterwards.  
I have but two questions:  
What should be done if the problem occurs again and what should be done to ensure a working internet connection in the container if docker is used on the host?

**Comment by stgraber** [comment]
If Docker is used on the host, you should find some way to configure Docker to not completely mess with iptables :)
Alternatively, you can go after it and fix the policies so traffic isn't all getting blocked.

If this happens again, you should dump `iptables -L -n`, `ps fauxww` and `netstat -lnp` so we can see if dnsmasq should be reachable or if something is getting in the way.
