### ISSUE TITLE
Order the devices list

### ISSUE THREAD

**Issue by hallyn** [lxc/lxd#734]
Currently devices are applied in the order in which ranging over the keys happens.  Currently that is the same as the order in which they were added to the lxdcontainer.devices map.  And that is profiles first, then container.  This means we are depending on a golang implementation detail, which is not good.  Add ordering to the devices list.

This is a low priority item compared to many others, but will become higher priority as people begin to use more complicated setups.

**Comment by stgraber** [comment]
When iterating over the map, we should simply sort by the key name. That should be pretty easy to do.

**Comment by stgraber** [comment]
Re-opening as the branch that was merged, while useful as it's sorting containers in the client, doesn't actually deal with this issue.
