### ISSUE TITLE
[4.1] Stop hook fails with zfs storage backend.

### ISSUE THREAD

**Issue by fling-** [lxc/lxd#7340]
# Required information

 * Distribution: gentoo
 * Distribution version: 17.1
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.39-gentoo-gnu-zfs-0.8.3
   * LXC version: 3.1.0
   * LXD version: 4.1
   * Storage backend in use: zfs

# Issue description

msg="The stop hook failed" container=test err="Failed to unmount '/var/lib/lxd/storage-pools/default/containers/test_test': device or resource busy"

# Steps to reproduce

lxc stop test

**Comment by stgraber** [comment]
Usually a sign of a kernel bug. We've added retry logic to allow for up to 10 attempts now, if you're still getting it, you likely have some kind of fd leak going on in the kernel (we don't hit it in our CI environment).
