### ISSUE TITLE
Copy/move custom volumes between projects

### ISSUE THREAD

**Issue by fling-** [lxc/lxd#7341]
`lxc storage volume` subcommands are missing --target-project option.
It is possible to move containers between projects but custom volumes are being left behind.

**Comment by stgraber** [comment]
Yeah, this isn't currently possible but is something we should eventually add.

**Comment by presztak** [comment]
@stgraber this issue looks interesting but I think this is duplicate of  #8236. Am i right?

**Comment by stgraber** [comment]
Indeed, let me close this one and clear the other as the assignee isn't responding.
