### ISSUE TITLE
Inefficient storage space usage.

### ISSUE THREAD

**Issue by fling-** [lxc/lxd#7342]
Moving containers between projects causes filesystem clones to be created.
Original filesystems are being moved to `storage-filesystem/deleted/containers`.
It is not possible to delete these filesystems because of the clones not being promoted.
Filesystem list grows with each container move.
Storage backend space usage grows with snapshots taking more space when old data is being overwritten.

**Comment by stgraber** [comment]
What storage backend (sounds like ZFS)?

What commands did you run and how does `zfs list -t all -o name,origin` look before and after?
