### ISSUE TITLE
You can create image alias you can't delete

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#7344]
Using the API by mistake I create an image alias with the name "https://localhost:8443" when you try to remove this with the API its not found & if you try to remove with LXC you get `the remote "https" doesn't exist` (which is expected), but the API should probably validate the names

**Comment by stgraber** [comment]
Hmm, should be deletable through API if properly URL encoded.

Using the CLI, did you try 'lxc image alias delete local:https://localhost: 8443'?

**Comment by turtle0x1** [comment]
`lxc image alias delete local:https://localhost: 8443` (including the space between : and 8443)

you get the help menu 

`lxc image alias delete local:https://localhost:8443` without the space 

> Error: not found

**Comment by stgraber** [comment]
I'll take a look at this one.
