### ISSUE TITLE
lxd does not create a subvolume on btrfs

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#735]
/var/lib/lxd/ is a symbolic link to /srv/lxd, placed on a btrfs filesystem:

# ls -l /var/lib/lxd
lrwxrwxrwx 1 root root 8 Jun  5 10:15 /var/lib/lxd -> /srv/lxd

# mount|grep /srv
/dev/sda4 on /srv type btrfs 
(rw,noatime,device=/dev/sda4,device=/dev/sdb4,compress=zlib)

# lxc launch images:ubuntu/trusty/amd64 test-image
Creating container...done
Starting container...done
error: exit status 1

Note that it errored when trying to start the container - I have to add 
"lxc.aa_allow_incomplete = 1"; otherwise, it won't start (is there some 
/etc/lxc/default.conf equivalent for lxd, where this could be set?).

However, the container is already created in a directory, so I don't 
think the above error matters:

# btrfs sub list /srv|grep lxd
# btrfs sub list /srv|grep test-image
#

For reference, see this thread:

https://lists.linuxcontainers.org/pipermail/lxc-users/2015-June/009440.html

**Comment by stgraber** [comment]
What version of lxd is that?

**Comment by tchwpkgorg** [comment]
# dpkg -l|grep lxd
ii  lxd                                      0.9-0ubuntu2~ubuntu14.04.1~ppa1      amd64        Container hypervisor based on LXC - daemon
ii  lxd-client                               0.9-0ubuntu2~ubuntu14.04.1~ppa1      amd64        Container hypervisor based on LXC - client

**Comment by stgraber** [comment]
Can you paste the output of:

     curl -s -k --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key https://127.0.0.1:8443/1.0

**Comment by tchwpkgorg** [comment]
{"type":"sync","status":"Success","status_code":200,"metadata":{"api_compat":1,"auth":"untrusted"}}

**Comment by stgraber** [comment]
Oh, oops, looks like you never accessed your local lxd over https, should have thought of that :)

Can you do:

    lxc config trust add ~/.config/lxc/client.crt

Then do the curl line again, that should return more stuff that time.

**Comment by tchwpkgorg** [comment]
{"type":"sync","status":"Success","status_code":200,"metadata":{"api_compat":1,"auth":"trusted","config":{"trust-password":false},"environment":{"backing_fs":"btrfs","driver":"lxc","kernel_version":"4.0.5-040005-generic","lxc_version":"1.1.2"}}}

**Comment by stgraber** [comment]
hmm, so it did detect btrfs

**Comment by stgraber** [comment]
I'm unable to reproduce the issue here, things seem to work fine with /var/lib/lxd symlinked to /srv/lxd.

One thing I don't see in your report though is confirmation that you imported the container image after switching to btrfs.

Basically, LXD will only make a subvolume for your container if the image itself is a subvolume. It will unpack images into a new subvolume only if it detects btrfs (which seems to be the case for you) and only since version 0.8.

So if you imported your image before moving to btrfs or if you imported it with a version of LXD pre-dating 0.8, then that could explain what you're seeing.

To confirm you may want to do:

    lxd-images import busybox --alias test
    lxc launch test blah

And see if you do end up with the expected subvolumes.

    root@castiana:~# /home/stgraber/data/code/lxc/lxd/scripts/lxd-images import busybox --alias test
    Image imported as: c567f881452e799c7bced37dd7383dc0f37264656268384dae63c06fb628f838
    Setup alias: test
    
    root@castiana:~# lxc launch test blah
    Creating container...done
    Starting container...done
    
    root@castiana:~# btrfs subvolume list / | grep srv/lxd
    ID 386 gen 28207 top level 5 path srv/lxd/images/ebe9d8522a6d610c1d57f2b4414de13a33c4460f2a154e1dce10122ab0bab9e7.btrfs
    ID 1674 gen 46629 top level 5 path srv/lxd/lxc/prebranchial-lennie
    ID 1676 gen 46665 top level 5 path srv/lxd/images/c567f881452e799c7bced37dd7383dc0f37264656268384dae63c06fb628f838.btrfs
    ID 1677 gen 46665 top level 5 path srv/lxd/lxc/blah

**Comment by tchwpkgorg** [comment]
Indeed, that was the case - the original image was not created on btrfs.
