### ISSUE TITLE
Old contributing guidelines link

### ISSUE THREAD

**Issue by BryanQuigley** [lxc/lxd#7355]
On page https://github.com/lxc/lxd/pulls
It shows this message:
First time contributing to lxc/lxd?

If you know how to fix an issue, consider opening a pull request for it.

You can read this repository’s *contributing guidelines* to learn how to open a good pull request.

*contributing guidelines* is what has the broken link.

I believe this may only show to first time contributors..

Links to:https://github.com/lxc/lxd/blob/master/contributing.md
Should be: https://github.com/lxc/lxd/blob/master/doc/contributing.md

**Comment by stgraber** [comment]
We can't change that path unfortunately and GitHub has a bug where it doesn't always follow those symlinks...

**Comment by BryanQuigley** [comment]
I think if you delete contributing.md in the root, it may switch to in docs/

https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by stgraber** [comment]
No, what that says is that putting it in only docs/ would only have it show up for contributions started from the docs directory.
