### ISSUE TITLE
github.com/mdlayher/eui64 broken dependency

### ISSUE THREAD

**Issue by AdrienR** [lxc/lxd#7357]
# Required information

 * Distribution: Debian
 * Distribution version: Buster (10)
 * LXD version: HEAD of master

# Issue description

Trying to compile LXD from source, it fails because one of its dependency repositories has been archived.

```
$ make                                                                                                                   
go get -t -v -d ./...
github.com/mdlayher/eui64 (download)
package github.com/mdlayher/eui64: no Go files in /home/adrien/go/src/github.com/mdlayher/eui64
```
This  repository is used here :
```
grep -r eui64 *                                                                                                       
lxd/device/nic_bridged.go:	"github.com/mdlayher/eui64"
lxd/device/nic_bridged.go:		IP, err := eui64.ParseMAC(subnet.IP, MAC)
```
I'm not in Go, so i dunno how this issue should be fixed, properly.

# Steps to reproduce

 1. git clone https://github.com/lxc/lxd && cd lxd
 2. make deps
 3. make

# Information to attach
https://github.com/mdlayher/eui64 has been archived and its content moved to another repository.

**Comment by tomponline** [comment]
I'm looking at this now. Thanks
