### ISSUE TITLE
[Feature Request] show message when cloud-init is finished

### ISSUE THREAD

**Issue by toby63** [lxc/lxd#7364]
**Problem:**
When using cloud-init it is hard to know when cloud-init is finished setting everything up.

**Solution:**
If you could implement some way to show a message in the console, this would be more convenient.

Options implemented in cloud-init are:
* [cloud-init status](https://cloudinit.readthedocs.io/en/latest/topics/cli.html)
* [call-a-url-when-finished](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#call-a-url-when-finished)
* [completion message](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#alter-the-completion-message)

**For Reference:**
As far as I remember Docker for example only starts the container when the Dockerfile has finished.

**Alternatives/Enhancements:**
* only show container as ready when cloud-init is finished
* A progress bar would be even more convenient, though probably (very) difficult to implement (and also out of scope of this project)
* Console/log of cloud-init (the idea is to show it in the host console)

**Comment by marbetschar** [comment]
IMHO it would be great to report the container's status as `106 Starting` while cloud-init is running, so its more obvious when the container is 100% ready.

**Comment by stgraber** [comment]
That's out of scope for LXD. LXD works quite hard not to care about anything that's running in the container.
Doing something like this would require LXD poke all containers, monitor files, ... which is all quite expensive, extremely distro-specific and even release specific at times.

It could also be used as an attack vector by having the container provide bogus output to LXD.


There are cloud-init commands you can run for yourself which will wait until cloud-init is complete. I'd recommend using those.

**Comment by toby63** [comment]
Ok, but just to mention it, you provide images which explicitely provide cloud-init, so cloud-init might be seen as a "core"-feature.

Maybe a more generic way of passing a message from the container to LXD could be implemented, that can only activate specific messages and would be encrypted/signed (or protected in some other way), so only specific applications can use it (like cloud-init).
All of this could also be optional, so the message is only shown if the user chooses it in LXD (per container start).

That said I understand and respect your decision, just wanted to mention it :slightly_smiling_face: .
