### ISSUE TITLE
Issues resizing Ceph volumes on 4.1 cluster

### ISSUE THREAD

**Issue by maran** [lxc/lxd#7369]
I'm having some issues resizing volumes via the HTTP API, not sure this is a user error or a bug so bear with me.

If I resize a volume via the CLI everything works and I can see the reflected new storage on my container right away.

If I do this via the HTTP API though it seems to try to mount the, already mounted, rbd image on the communication server. At least that's what I make of it. This obviously does not work as the image is already mounted.

Server 1
```
root@dream:~# rbd showmapped | grep disk-test-5041
6  rbd               custom_default_bcc-disk-test-5041 -    /dev/rbd6
```

Server 2 at the same time

```
t=2020-05-15T17:11:08+0100 lvl=dbug msg="UpdateCustomVolume started" driver=ceph newConfig="map[block.filesystem:ext4 block.mount_options:discard size:180GB volatile.idmap.last:[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}] volatile.idmap.next:[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]]" newDesc= pool=test-pool project=default volName=bcc-disk-test-5041
t=2020-05-15T17:11:08+0100 lvl=dbug msg="Mounted RBD volume" dev=/dev/rbd2 driver=ceph options=discard path=/var/snap/lxd/common/lxd/storage-pools/test-pool/custom/default_bcc-disk-test-5041 pool=test-pool
t=2020-05-15T17:11:09+0100 lvl=dbug msg="Unmounted RBD volume" driver=ceph path=/var/snap/lxd/common/lxd/storage-pools/test-pool/custom/default_bcc-disk-test-5041 pool=test-pool
t=2020-05-15T17:11:09+0100 lvl=dbug msg="UpdateCustomVolume finished" driver=ceph newConfig="map[block.filesystem:ext4 block.mount_options:discard size:180GB volatile.idmap.last:[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}] volatile.idmap.next:[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]]" newDesc= pool=test-pool project=default volName=bcc-disk-test-5041
```

Is this something I am doing wrong? Can I somehow specify the node it should do this operation on or is this a bug of some sort?

**Comment by tomponline** [comment]
which filesystem are you using on the ceph volumes, some filesystems require the volume to be mounted to resize.

**Comment by tomponline** [comment]
and which node are you targeting with your API request?

**Comment by maran** [comment]
> which filesystem are you using on the ceph volumes, some filesystems require the volume to be mounted to resize.

Just normal ext4

> and which node are you targeting with your API request?

Non specifically like you could with container creation (`target: 'server-name'`), is this an option for volume operations? I only have the API enabled on one of the nodes so that's the node I use as endpoint.

**Comment by tomponline** [comment]
And is that the node that is trying to mount? And its mounted already on another node?

**Comment by maran** [comment]
> And is that the node that is trying to mount?

Yeah the 'communication node' is trying to mount it even though it's not where the container lives that has the disk attached to it at the moment and while the volume is mounted in said container.

**Comment by stgraber** [comment]
Ah yeah, we definitely should have this processed only by the node on which it's being used.

**Comment by stgraber** [comment]
@tomponline want to take that one?

**Comment by tomponline** [comment]
@stgraber yep, I'll see what the lxc cli does differently to the API.

**Comment by tomponline** [comment]
@maran are you able to post a set of instructions you use to make the API requests so I can re-create and fix? I'd be interested to see what URL and payload you are sending.

**Comment by tomponline** [comment]
@maran @stgraber I took a look at the `method=PUT url=/1.0/instances/` and as far as I can see the forwarding of requests from the local node to the remote node where the instance is actually 'hosted' seems to be working (as you say, this is the route that the lxc cli uses).

https://github.com/lxc/lxd/blob/master/lxd/instance_put.go#L39-L45

But if you let me know which specific API request and payload you are using I may be able to re-create it.

**Comment by maran** [comment]
I've upgraded the whole test cluster to 4.7 and tried it again but I can't get it to work.

Some more info.

**Communication node**
```
t=2020-10-21T11:01:22+0100 lvl=dbug msg=Handling ip=62.251.114.227:52258 method=GET url=/1.0/containers/vieze-freddy user=8791165c10e3dd13a822436b7d9f8332baaf3e9eef6c0f6532d5e677ef11dd8d
t=2020-10-21T11:01:22+0100 lvl=dbug msg="Connecting to a remote LXD over HTTPs"
t=2020-10-21T11:01:22+0100 lvl=dbug msg="Found cert" name=8791165c10e3dd13a822436b7d9f8332baaf3e9eef6c0f6532d5e677ef11dd8d
t=2020-10-21T11:01:22+0100 lvl=dbug msg=Handling ip=62.251.114.227:52259 method=GET url=/1.0/storage-pools/remote/volumes/custom/resize-test user=8791165c10e3dd13a822436b7d9f8332baaf3e9eef6c0f6532d5e677ef11dd8d
t=2020-10-21T11:01:22+0100 lvl=dbug msg="Database error: &errors.errorString{s:\"No such object\"}"
t=2020-10-21T11:01:23+0100 lvl=dbug msg="Found cert" name=8791165c10e3dd13a822436b7d9f8332baaf3e9eef6c0f6532d5e677ef11dd8d
t=2020-10-21T11:01:23+0100 lvl=dbug msg=Handling ip=62.251.114.227:52260 method=PUT url=/1.0/storage-pools/remote/volumes/custom/resize-test user=8791165c10e3dd13a822436b7d9f8332baaf3e9eef6c0f6532d5e677ef11dd8d
t=2020-10-21T11:01:23+0100 lvl=dbug msg="\n\t{\n\t\t\"config\": {\n\t\t\t\"block.filesystem\": \"ext4\",\n\t\t\t\"block.mount_options\": \"discard\",\n\t\t\t\"size\": \"15GB\",\n\t\t\t\"volatile.idmap.last\": \"[{\\\"Isuid\\\":true,\\\"Isgid\\\":false,\\\"Hostid\\\":1000000,\\\"Nsid\\\":0,\\\"Maprange\\\":1000000000},{\\\"Isuid\\\":false,\\\"Isgid\\\":true,\\\"Hostid\\\":1000000,\\\"Nsid\\\":0,\\\"Maprange\\\":1000000000}]\",\n\t\t\t\"volatile.idmap.next\": \"[{\\\"Isuid\\\":true,\\\"Isgid\\\":false,\\\"Hostid\\\":1000000,\\\"Nsid\\\":0,\\\"Maprange\\\":1000000000},{\\\"Isuid\\\":false,\\\"Isgid\\\":true,\\\"Hostid\\\":1000000,\\\"Nsid\\\":0,\\\"Maprange\\\":1000000000}]\"\n\t\t},\n\t\t\"description\": \"\",\n\t\t\"name\": \"resize-test\",\n\t\t\"type\": \"custom\",\n\t\t\"used_by\": [\n\t\t\t\"/1.0/instances/vieze-freddy\"\n\t\t],\n\t\t\"location\": \"\",\n\t\t\"content_type\": \"filesystem\"\n\t"
t=2020-10-21T11:01:23+0100 lvl=dbug msg="Database error: &errors.errorString{s:\"No such object\"}"
t=2020-10-21T11:01:23+0100 lvl=dbug msg="UpdateCustomVolume started" driver=ceph newConfig="map[block.filesystem:ext4 block.mount_options:discard size:15GB volatile.idmap.last:[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}] volatile.idmap.next:[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]]" newDesc= pool=remote project=default volName=resize-test
t=2020-10-21T11:01:23+0100 lvl=dbug msg="UpdateCustomVolume finished" driver=ceph newConfig="map[block.filesystem:ext4 block.mount_options:discard size:15GB volatile.idmap.last:[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}] volatile.idmap.next:[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]]" newDesc= pool=remote project=default volName=resize-test
```

**Node that is running the container**
Basically nothing.

```
t=2020-10-21T12:01:22+0200 lvl=dbug msg="Found cert" name=0
t=2020-10-21T12:01:22+0200 lvl=dbug msg=Handling ip=185.162.185.25:51480 method=GET url=/1.0/containers/vieze-freddy user=
t=2020-10-21T12:01:28+0200 lvl=dbug msg="Found cert" name=0
t=2020-10-21T12:01:28+0200 lvl=dbug msg="Replace current raft nodes with [{ID:2 Address:185.162.185.25:8443 Role:voter} {ID:3 Address:185.162.185.3:8443 Role:voter} {ID:1 Address:185.162.185.31:8443 Role:voter}]"
```

**Comment by tomponline** [comment]
@maran are you able to post a set of instructions you use to make the API requests so I can re-create?

**Comment by tomponline** [comment]
@maran also does it work when the container isnt running?

**Comment by maran** [comment]
This is tightly integrated in a Ruby on Rails project using Hyperkit so it's a bit hard to replicate directly via the API. 

If I stop the container it does something but gives an error. This might be related because of corruption that happened earlier so I will try it on a fresh disk in a bit.

```
root@olaris-swarm:~# lxc storage volume set remote custom/resize-test size=23GB
Error: Could not extend underlying ext4 filesystem for "/dev/rbd4": Filesystem at /dev/rbd4 is mounted on /var/snap/lxd/common/lxd/storage-pools/remote/custom/default_resize-test; on-line resizing required
old_desc_blocks = 2, new_desc_blocks = 3
```

**Comment by tomponline** [comment]
@maran you could try recreating using `lxc query` perhaps?

**Comment by maran** [comment]
```
lxc query -X POST --data '{"config": {"size": "10GB"}, "name": "lxd-query-resize-test"}' --wait /1.0/storage-pools/remote/volumes/custom

lxc storage volume attach remote custom/lxd-query-resize-test c1 /mnt/test # I can't easily replicate this over lxc query as it requires the entire container config to work

lxc query -X PUT --data '{"config": {"size": "33GB"}}' --wait /1.0/storage-pools/remote/volumes/custom/lxd-query-resize-test
```

This replicates the behaviour and wants to mount the already mounted RBD instance on the communication node.

**Comment by tomponline** [comment]
@maran thanks thats great, I'll try to reproduce here and look to fix it.

**Comment by tomponline** [comment]
@maran and what error do you get when using your reproducer above?

**Comment by maran** [comment]
Various things go wrong. The most obvious is that the disk does not get properly resized and it will stay the same size in the container. After reboot the "used space" column in `df -h` will often go into the negative. It might actually corrupt the filesystem, I should probably test this.

**Comment by tomponline** [comment]
@maran please can you confirm whether you see the issues if the container is stopped before executing each resize request.

The reason I ask is that I've seen some issues with resizing custom ceph volumes when they are attached to running instances (even when the resize request is initiated on the same node as the running instance where the ceph volume is mounted).

It seems like the root issue is that we need to better detect when a custom volume is in use and restrict resizing.

**Comment by tomponline** [comment]
@stgraber so just to check I've got my understanding right here:

1. ceph rbd volumes should not be mounted on more than one node at a time?
2. This means that we should not allow a ceph volume to be attached to multiple instances (this is currently blocked).
3. Also, ceph driver indicates that it doesn't not support online resize (which makes sense given it provides block devices) which means we should not allow custom volumes to be resized if they are attached to a running instance (this is currently allowed and causes issues if a volume is resized).
4. So more generally, we should detect if a custom volume is attached and then forward the request to the node that hosts the instance using the volume. Then we need to update the custom volume resize code to query the running state of the instance it is attached too, and if it is running, reject the resize.

**Comment by stgraber** [comment]
1) Correct, that would cause data corruption
2) That's correct, that's why we instead recommend ceph-fs for such cases
3) Indeed we should check for running instances and refuse resizing if the volume is in active use
4) That's correct with the exception of cephfs where multiple nodes can attach the same volume and where a resize can be performed from any of them.

**Comment by tomponline** [comment]
@stgraber thanks

Also, did ceph/cephfs volumes have multiple nodes defined at some point in the past, as currently I observe that ceph volumes have a nil node ID in the DB, however these lines suggest that previously it was normal for a ceph volume to be defined with multiple node addresses:

https://github.com/lxc/lxd/blob/4bb48ec45df1e7debf7402f83d1a7574f69179ab/lxd/cluster/connect.go#L135-L148

**Comment by stgraber** [comment]
@tomponline yeah, that's right. We used to duplicate the volume record for every single node, which cause a variety of problems.
These days we just mark it as NULL to indicate that location is irrelevant for such volumes.
