### ISSUE TITLE
LXD Cluster completly broken after restarting one node (failed to begin transaction: not an error /  cannot fetch node config from database: driver: bad connection)

### ISSUE THREAD

**Issue by wmchris** [lxc/lxd#7371]
Setup: LXD Clustered on 21 machines using lxd 3.23 on debian / 10 installed via snap
Linux cluster01-00 5.5.0-0.bpo.2-amd64 #1 SMP Debian 5.5.17-1~bpo10+1 (2020-04-23) x86_64 GNU/Linux

Problem started after one machine (id 10) had to be rebootet. All LXD Cluster Nodes got unresponsive. Databases are on id 3,4,6. Immediately all lxc related commands got unresponsive. 

Already tried rebooting the whole cluster and restarting the daemon.

/var/snap/lxd/common/lxd/logs/lxd.log is spammed with
"Failed to get current cluster nodes: failed to begin transaction: not an error"
or
"Error: cannot fetch node config from database: driver: bad connection"

i cant get any useful information from any log.

even when running a node on its own, they're completly unresponsive. 

any chance to recover this system?

**Comment by freeekanayaka** [comment]
I might know the cause of this issue. Please try the following:

1. Use "sqlite3 /var/snap/lxd/common/lxd/database/local.db "SELECT * FROM raft_nodes" to double check what your database nodes are (they should have `0` in the role column)
2. Stop the lxd daemon on **all** nodes
3. Move away the `/var/snap/lxd/common/lxd/database/global` directory on all nodes that are **not** database nodes (e.g. `/var/snap/lxd/common/lxd/database/global /my/backup/dir`)
4. Restart all nodes

**Comment by wmchris** [comment]
i tried it - database nodes are 3,4,6. after restart the nodes 0-2,5,7-20 are responsive, but lxc cluster list displays every node as offline. node 3-4,6 are completly unresponsive.

**Comment by wmchris** [comment]
ok, it required a system reboot, a simple lxd restart was not enough, now its starting to get back online again.

any more detail what happened here?

**Comment by freeekanayaka** [comment]
The fact that you needed a system reboot is probably a red herring.

I discovered today an issue when a database node is first shutdown and then restarted, and the cluster has more than 3 nodes. It doesn't happen all the times, but I think it can be frequent.

I'll work on a fix in the next days.

**Comment by wmchris** [comment]
the restarted node was not a database node.
if you find sth please provide a fix for the v3, too. i cannot run v4 at the moment :-(

**Comment by freeekanayaka** [comment]
> the rebooted node was not a database node.

It was not when it came back (because we transfer the database role at daemon shutdown), but it likely was when it went down, or at some point in time before that.

> also if you find sth please provide a fix for lxd v3, too.

I don't think this fix will be backported to the 3.X series, since that's the development version. Fixes are usually backported to stable series, currently 3.0.X and 4.0.X. @stgraber might be able to comment on that tho.

**Comment by wmchris** [comment]
must've been a while ago. it was not a database node on this day, not even a standby node.

this would be sad, as i cannot run 4.0.X (unless the new snapd is now available for debian) and 3.0.X is missing a lot of features.

**Comment by stgraber** [comment]
3.0 is security fix only at this stage, though we will be pushing a few dqlite tweaks in the next release just to keep it building.

**Comment by stgraber** [comment]
@freeekanayaka so is that the WIP dqlite bug then?

If so, should we close this in favor of the dqlite bug?

**Comment by freeekanayaka** [comment]
> @freeekanayaka so is that the WIP dqlite bug then?
> 
> If so, should we close this in favor of the dqlite bug?

Which bug are you referring to?

I plan to fix this bug with #7373, however it will require a non-trivial change in raft as well.

Note also that although I've identified an issue when restarting servers, I've not been hitting "not an error" specifically, but a normal "leadership lost". So I can kinda reproduce the problem, but not with the exact same error. Nevertheless it's possible that the root cause is the same.

**Comment by stgraber** [comment]
Indeed, thanks for the link to the PR

**Comment by stgraber** [comment]
PR was merged and cherry-picked.
