### ISSUE TITLE
Documentation bug: LVM pool creation

### ISSUE THREAD

**Issue by vic-t** [lxc/lxd#7374]
I may have found a small issue in the storage documentation. Under the title Notes and Examples in the section for LVM, there is an example how to create a LXD pool from an existing LVM thin volume: 

> Use the existing LVM Thinpool called "my-pool" in Volume Group "my-vg".
> 
> `lxc storage create pool1 lvm source=my-vg lvm.thinpool_name=my-pool`

If I do this on my system (Ubuntu 18.04.4 with LXD 4.1), I get the error message "Error: Volume group "my-vg" is not empty". 

When referring to an existing thin volume, the correct command seems to be

`lxc storage create pool1 lvm lvm.thinpool_name=my-pool`

The original command seems to allow the creation of a named thinpool using lxc. So it's absolutely valid to have it in the documentation but it just needs to be described differently.

**Comment by stgraber** [comment]
@tomponline why wouldn't it work to set both the VG (through source) + thinpool name?

Anyway, we need to sort out the code or sort out the doc here :)

**Comment by tomponline** [comment]
Confirmed creating thinpool storage pool on existing empty VG works:

```
dd if=/dev/zero of=~/mylvm.img bs=1 count=0 seek=5G
sudo losetup -fP ~/mylvm.im
sudo losetup  | grep mylvm.img
sudo pvcreate /dev/loop16
sudo vgcreate myvg /dev/loop16
lxc storage create mylvm lvm source=myvg
sudo lvs myvg
 LV          VG   Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  LXDThinPool myvg twi-a-tz-- <3.00g             0.00   1.57  
```

Confirmed creating storage pool ontop of existing thinpool is also working:

```
dd if=/dev/zero of=~/mylvm.img bs=1 count=0 seek=5G
sudo losetup -fP ~/mylvm.im
sudo losetup  | grep mylvm.img
sudo pvcreate /dev/loop16
sudo vgcreate myvg /dev/loop16
sudo lvcreate --thinpool mythinpool  --extents 100%FREE myvg
sudo lvs myvg
  LV         VG   Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  mythinpool myvg twi-a-tz-- 4.98g             0.00   10.60         

lxc storage create mylvm lvm source=myvg lvm.thinpool_name=mythinpool
lxc storage show mylvm
config:
  lvm.thinpool_name: mythinpool
  lvm.vg_name: myvg
  source: myvg
  volatile.initial_source: myvg
description: ""
name: mylvm
driver: lvm
used_by: []
status: Created
locations:
- none

lxc init ubuntu:18.04 c1 -s mylvm
sudo lvs myvg
  LV                                                                      VG   Attr       LSize  Pool       Origin                                                                  Data%  Meta%  Move Log Cpy%Sync Convert
  containers_c1                                                           myvg Vwi---tz-k <9.32g mythinpool images_93b9eeb85479af2029203b4a56a2f1fdca6a0e1bf23cdc26b567790bf0f3f3bd                                        
  images_93b9eeb85479af2029203b4a56a2f1fdca6a0e1bf23cdc26b567790bf0f3f3bd myvg Vwi---tz-k <9.32g mythinpool                                                                                                                
  mythinpool                                                              myvg twi-aotz--  4.98g                                                                                    17.92  15.92                           
```

Confirmed creating storage pool on exiting vg & thinpool when vg is non-empty fails as expected:

```
sudo vgcreate myvg /dev/loop16
sudo lvcreate --thinpool mythinpool  --extents 50%FREE myvg
sudo lvcreate -n test1 -L 500M myvg
sudo lvcreate -n test2 --thin --virtualsize 2G myvg/mythinpool
lxc storage create mylvm lvm source=myvg lvm.thinpool_name=mythinpool
Error: Volume group "myvg" is not empty
lxc storage create mylvm lvm source=myvg lvm.thinpool_name=mythinpool lvm.vg.force_reuse=true
Storage pool mylvm created
```

So as far as I can tell this is working correctly.

**Comment by avsdev-cw** [comment]
Rather than open a new issue about this (I think @vic-t is right, this is a documentation issue) I'm going to tie in #6916 and request/suggest:

It would be useful if the documentation explained the ramifications of using an existing volume group or pool and what happens to the existing logical volumes in the life-cycle of lxd.  Some further clarification on the docs that are already there would be useful too. There is a lot of clarification between btrfs, zfs and dir storage backends, but lvm seems somewhat ignored at points.

For example, I have a vg with some lv's containing project specific data (some ~1G others 50GB+). I've been around the bush a number of times on how to give unpriv containers access to them (mount them on the host and use a bind mount into the container is a common solution but requires giving the containers a host account for write access through idmap). Recently I went through the `lxc storage volume` commands and thought "I could just attach them to the container... if only they were in an lxc storage pool...". Now I'm left wondering:
- What happens to the existing lv if I delete the container it is attached to? Does it also get deleted? Does it just get detached?
- What happens if I delete an existing lv using lxd (by accident)? I would assume that lxd would allow it (but this is not clear!)
- What happens if I delete the storage pool in lxd, do the existing lv's all get deleted along with the lxd created ones?
- What happens if I create a new lv outside of lxd, will it be accepted/detected?
- How do ACL's work and will I need to id.map the users in? (this is only in write cases, nearly all my use cases are read-only)

**Comment by stgraber** [comment]
1) Deleting an instance that has an attached custom storage volume does not delete the custom storage volume.
2) You can only delete custom storage volumes which are not in use.
3) Deleting a storage pool in LXD only works if no LXD resources are left on it. If the VG existed, LXD should have set a property on that storage pool indicating as much, in which case it will delete the thinpool it created but leave the rest alone. If LXD was the one creating the VG, it will delete the VG. That's in line with what's done for ZFS. We allow using a subset of an existing pool, in this case a thinpool in an existing VG but whatever LXD creates it feels free to delete and you should never create stuff manually in a LXD managed pool (in this case a custom LV in the thinpool or if LXD created the VG, any LV in that VG).
4) This is kinda answered by 3). If you specified an existing VG to LXD, you can create more LVs outside of the thinpool used by LXD, but creating anything on a VG that LXD created or anything in the thinpool that LXD uses is unsupported, can lead to runtime issues and will be deleted on pool removal.
5) The custom storage volume is mapped to the same map as the instance it's attached to. Attaching to multiple instances with differing maps (like security.idmap.isolated) doesn't work (LXD will refuse to do it with an error) unless you also use shiftfs.

**Comment by tomponline** [comment]
@avsdev-cw in addition to what @stgraber I would like to clarify that we will not remove a volume group or thinpool if it is non-empty (even if `lvm.vg.force_reuse=true` wasn't specify when the storage pool was created). Although creating volumes in a volume group or thinpool used by LXD may still expose you to naming conflicts (as @stgraber mentioned above).

The `lvm.vg.force_reuse` setting was added to allow you to force LXD to re-use a non-empty volume group/thinpool (whereas normally LXD would refuse to do so) and record the fact that this decision had been made to aid support cases where naming conflicts could occur.

The logic for deleting is here, with comments:
https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_lvm.go#L335-L391

**Comment by avsdev-cw** [comment]
Thanks to both of you for the clarifications.  From an integrity point of view it's pretty important to understand what lxd is doing and that has cleared things up greatly and given piece of mind!

**Comment by lathiat** [comment]
I hit this problem today. I expected to be able to use an LVM thinpool from a VG that was not empty and also used for the Root FS.

With an empty thinpool, but a VG that has other LVs, this fails:

```
root@skc:~# lxc storage create lvm lvm source=ubuntu-vg lvm.thinpool_name=lxd
Error: Volume group "ubuntu-vg" is not empty
```

This works (as noted in the issue opener) however it doesn't actually do what we expect. It creates a new loopback LVM VG and creates another thinpool on that.

```
root@skc:~# lxc storage create lvm lvm lvm.thinpool_name=lxd 
Storage pool lvm created
```

So for anyone discovering this issue wanting to do it, the correct solution appears to be to use lvm.vg.force_reuse.

**Comment by tomponline** [comment]
Yes using `lvm.vg.force_reuse=true` is what is needed to reuse a non-empty volume group. The `lvm.thinpool_name` controls the thinpool volume created on the volume group, but if not specified by `source=` then a loop file volume group is created.
