### ISSUE TITLE
LVM - Thin volume creation not working with snap version of LXD 4.1

### ISSUE THREAD

**Issue by vic-t** [lxc/lxd#7376]
Yesterday, on a freshly installed Ubuntu 18.04 LTS server, on physical hardware, I installed the snap package for LXD. I then went on to manually create a LVM thinpool that I added as a storage device in LXD and referenced it in the default profile. 

I think I lost 3 hours on this but there was simply no way I managed to get LXD to create a new thin volume. LXD always created a LVM loopback device when launching a new container.

I uninstalled the snap version, installed LXD via apt (in version 3, of course), didn't touch the existing thinpool at all, and ran the exact same configuration. LXD would create new volumes now without issues. 

I'm not sure if this is an issue with version 4.1 or the snap version in general but at any rate, I couldn't get thin volume creation to work.

**Comment by tomponline** [comment]
Please can you show us the commands you ran and the error you got. Thanks

**Comment by vic-t** [comment]
Hi Tom, thanks for getting back to me so quickly. 

```
# lxd init (defaults, without configuring storage)
# lvcreate -L 200G --thinpool lxdthin vg0
# lxc storage create lvmthin1 lvm source=vg0 lvm.use_thinpool=true lvm.vg.force_reuse=true lvm.thinpool_name=lxdthin
# lxc profile device add default root disk path=/ pool=lvmthin1
# lxc launch ubuntu:18.04 c1
```

Works with the apt version, does not work with 4.1 snap.

**Comment by tomponline** [comment]
Ok thanks. So what indicates to you there is a problem?

**Comment by vic-t** [comment]
As described, no thin volume is created, just a loopback device. 

This is how I'm expecting it to look after creating container c1: 

```
root@sb32 ~ # lvs
  LV                                                                      VG  Attr       LSize   Pool     Origin                                                                  Data%  Meta%  Move Log Cpy%Sync Convert
  containers_c1                                                           vg0 Vwi-aotz--  10.00g lxdthin  images_235aa7210a0821ff12ebf376dd119388a7aa1cdff4fc40752d7d8cbf3507b417 33.49                                  
  images_235aa7210a0821ff12ebf376dd119388a7aa1cdff4fc40752d7d8cbf3507b417 vg0 Vwi-a-tz--  10.00g lxdthin                                                                          5.84                
  lxdthin                                                                 vg0 twi-aotz-- 200.00g                                                                                  1.75   11.32   
```

The thin volumes are never created, though. This example is taken from the same machine with the apt version of LXD 3 installed.

**Comment by tomponline** [comment]
Ok so the container fails to start presumably?

**Comment by vic-t** [comment]
No, the container starts fine. As mentioned, there are no errors whatsoever, everything works. It just doesn't use the storage backend it's supposed to.

**Comment by stgraber** [comment]
It's almost certainly doing the right thing, you just don't see it because the snap has its own LVM which does not share cache with the host one.

**Comment by stgraber** [comment]
Can you run `pvscan` and `pvscan --cache` on the host, then look at `lvs` again see if maybe things are showing up now?

**Comment by vic-t** [comment]
Hi Stéphane, I guess that's possible and it would explain why I didn't see any errors. I can't check now since I already moved on to the apt version of LXD. How complicated is it to update to the snap version again, is this a seamless process, would my containers just keep working as is? The machine is now in production so I wouldn't want to risk more than 15 minutes of downtime.

**Comment by stgraber** [comment]
The process is pretty straightforward with 'snap install lxd --channel=4.0 && lxd.migrate' but it will shut down all containers and perform a major upgrade from 3.0 to 4.0 on top of the deb to snap data migration.

So it's fast but with a lot of moving pieces.

**Comment by stgraber** [comment]
I'll close this issue as we have an open packaging issue about the out of sync cache behavior on the packaging side.

If you decide to go with the migration, let us know if everything behaves as expected.
