### ISSUE TITLE
After upgrade to Fossa containers have problems and processes hang

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#7385]
LXD 4.1
Focal Fosssa (Upgraded from Bionic)

We upgraded lots of systems yesterday as all our initial tests it looked as if we had it nailed down and things would run smoothly. The upgrade went fine but today we started getting reports of users not being able to log in with SSH to their containers. We did a debug session on both the server and client and we saw this:

Server:
```
# /usr/sbin/sshd -d -D -p 222
 .. output cropped
Postponed publickey for admin from 2.110.243.147 port 61874 ssh2 [preauth]
debug1: userauth-request for user admin service ssh-connection method publickey [preauth]
debug1: attempt 2 failures 0 [preauth]
debug1: temporarily_use_uid: 1001/27 (e=0/0)
debug1: trying public key file /home/admin/.ssh/authorized_keys
debug1: fd 4 clearing O_NONBLOCK
debug1: matching key found: file /home/admin/.ssh/authorized_keys, line 1 RSA SHA256:plvv+n6kLeQP5SEes64kDnVFN0X5GUo7ZR9OsOAnQ5A
debug1: restore_uid: 0/0
debug1: do_pam_account: called
Accepted publickey for admin from 2.110.243.147 port 61874 ssh2: RSA SHA256:plvv+n6kLeQP5SEes64kDnVFN0X5GUo7ZR9OsOAnQ5A
debug1: monitor_child_preauth: admin has been authenticated by privileged process
debug1: Enabling compression at level 6. [preauth]
debug1: monitor_read_log: child log fd closed
debug1: PAM: establishing credentials
```
It hangs indefinitely on the PAM line. Disabling PAM in sshd config "fixes" the issue, but we also noticed that running stuff like `ps aux` or `htop` incurr noticeable delays. Also container startup is a lot slower than usual - it can take several minutes for all processes to come up.

Note: This is happening across 10+ host servers and in all containers we have checked so far (lots). So it's an endemic issue and not just a one off.

Doing an strace on sshd in order to try and see where it hangs - output stops here:

```
... output cropped
sendmsg(5, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1p\0\0\0\2\0\0\0\230\0\0\0\1\1o\0\27\0\0\0/org/fre"..., iov_len=168}, {iov_base="\351\3\0\0\326\n\0\0\4\0\0\0sshd\0\0\0\0\3\0\0\0tty\0\4\0\0\0"..., iov_len=112}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 280
recvmsg(5, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1\n\0\0\0\2\0\0\0\215\0\0\0\1\1o\0\25\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24
recvmsg(5, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="/org/freedesktop/DBus\0\0\0\2\1s\0\24\0\0\0"..., iov_len=146}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 146
recvmsg(5, {msg_namelen=0}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
ppoll([{fd=5, events=POLLIN}], 1, {tv_sec=24, tv_nsec=999806000}, NULL, 8) = 1 ([{fd=5, revents=POLLIN}], left {tv_sec=24, tv_nsec=997098328})
recvmsg(5, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\2\1\1d\0\0\0E\0\0\0=\0\0\0\5\1u\0\2\0\0\0", iov_len=24}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, cmsg_data=[6]}], msg_controllen=24, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24
recvmsg(5, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\6\1s\0\5\0\0\0:1.17\0\0\0\10\1g\0\10soshusub\0\0\0"..., iov_len=156}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 156
access("/run/user/1001/bus", F_OK)      = -1 ENOENT (No such file or directory)
fcntl(6, F_DUPFD_CLOEXEC, 3)            = 7
close(5)                                = 0
close(6)                                = 0
stat("/etc/update-motd.d", {st_mode=S_IFDIR|0755, st_size=15, ...}) = 0
umask(022)                              = 022
rt_sigaction(SIGINT, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fdd89a91f20}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fdd89a91f20}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
clone(child_stack=NULL, flags=CLONE_PARENT_SETTID|SIGCHLD, parent_tidptr=0x7ffd2b55da5c) = 2874
wait4(2874,
```

So it's hanging while trying to spawn a child process? 

Any ideas what might be causing these issues? I'll keep updating here as we investigate further - maybe some new stuff in the Focal kernel or limits/security parameters are not playing nice with our containers? We can grant you access to these systems if you want for further inspection :)

**Comment by Kramerican** [comment]
The issue with slow container startup has been traced to the "old" cloud-init issue we hit before - see #6549 - so that's no big deal. We are however still seeing this PAM subsystem hang as described above.

**Comment by Kramerican** [comment]
Some more information here:

Creating an Ubuntu Xenial container and then trying to SSH in completes succesfully. Output in that case around where it hangs in a Bionic container is:

```
... output cropped
debug1: PAM: establishing credentials
User child is on pid 919
debug1: SELinux support disabled
debug1: PAM: establishing credentials
debug1: permanently_set_uid: 1001/27
... continues and all is well
```

I have tried a focal container as well, and there I see the same behavior as in a Bionic container. I am now starting to think this might be networking related as Bionic/Focal use Netplan and Xenial does not - but sshd hanging on that PAM line spawning a child process (seemingly) doesn't really rhyme with that.

The investigation continues ...

**Comment by stgraber** [comment]
Could be DNS related? Were you running strace with -f to catch forks?

**Comment by Kramerican** [comment]
Networking really seems to be working just fine from the container point of view. 

I ran strace with the -f option (sheesh why did I not think of that) and I get this repeating endlessly when sshd hangs:

```
0} ---
[pid  1496] getpid()                    = 1496
[pid  1496] write(8, "\21", 1)          = 1
[pid  1496] rt_sigreturn({mask=[]})     = 0
[pid  1496] read(10, "255.10 238.44\n", 8192) = 14
[pid  1496] read(10, "", 8178)          = 0
[pid  1496] openat(AT_FDCWD, "/proc/1886/stat", O_RDONLY|O_CLOEXEC) = 11
[pid  1496] fstat(11, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
[pid  1496] ioctl(11, TCGETS, 0x7ffd837c91e0) = -1 ENOTTY (Inappropriate ioctl for device)
[pid  1496] lseek(11, 0, SEEK_CUR)      = 0
[pid  1496] ioctl(11, TCGETS, 0x7ffd837c91b0) = -1 ENOTTY (Inappropriate ioctl for device)
[pid  1496] lseek(11, 0, SEEK_CUR)      = 0
[pid  1496] lseek(11, 0, SEEK_CUR)      = 0
[pid  1496] fstat(11, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
[pid  1496] read(11, "1886 (landscape-sysin) Z 1496 12"..., 8192) = 187
[pid  1496] read(11, "", 8005)          = 0
[pid  1496] close(11)                   = 0
[pid  1496] wait4(1886, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 1886
[pid  1496] lseek(9, 0, SEEK_SET)       = 0
[pid  1496] lseek(10, 0, SEEK_SET)      = 0
[pid  1496] lseek(9, 0, SEEK_CUR)       = 0
[pid  1496] fstat(9, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
[pid  1496] read(9, "256.31 239.64\n", 8192) = 14
[pid  1496] read(9, "", 8178)           = 0
[pid  1496] clone(strace: Process 1900 attached
child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fe522bf9a10) = 1900
[pid  1900] set_robust_list(0x7fe522bf9a20, 24) = 0
[pid  1496] lseek(10, 0, SEEK_CUR)      = 0
[pid  1496] fstat(10,  <unfinished ...>
[pid  1900] getpid()                    = 1900
[pid  1900] exit_group(0)               = ?
[pid  1496] <... fstat resumed> {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
[pid  1496] read(10,  <unfinished ...>
[pid  1900] +++ exited with 0 +++
[pid  1496] <... read resumed> "257.83 241.15\n", 8192) = 14
[pid  1496] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1900, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
```

I am not sure how to interpret this output? Can you spot anything significant here @stgraber ?

**Comment by Kramerican** [comment]
Tried another thing to get nearer whether this is a networking related issue: I tried disabling Netplan and switched to ifupdown in a Bionic container which was failing (on a system where a Xenial container works) under the assumption that it might be Netplan gunking up the works.

Unfortunately the issue persists - networking and name resolution confirmed as working in the container with ifupdown. So it really seems to be something happening at a deeper level than that.

**Comment by Kramerican** [comment]
After many hours of debugging we have identified the core issue being that we load the br_netfilter kernel module in order to facilitate anti cross-container IP spoofing.

Removing this module and rebooting the host solves the issue. 

Unfortunately it seems we need to reboot all our hosts in order to fix this - but such is life. Consider this issue closed.

**Comment by stgraber** [comment]
You may get away with just reconfiguring the module through /proc/sys/net maybe?

**Comment by Kramerican** [comment]
I ended up doing:

`modprobe -r br_netfilter; sleep 2; netplan apply; sleep 2; snap restart lxd;`

That got everything working again :)

**Comment by Kramerican** [comment]
As an aside here if somebody stumles on this issue in the future: The issue here turned out not to be br_netfilter at all - the issue creeps in over time so we erroneously thought we had solved it, while it was just the restart of containers that did the trick temporarily. It turns out to be that we have set `snap set lxd lxcfs.loadavg=true` in order to get nice load avg. on a per container basis - this is the core cause and you can follow the (hopefully) ultimate resolution in https://github.com/lxc/lxcfs/issues/407
