### ISSUE TITLE
Permission denied for different user

### ISSUE THREAD

**Issue by johnmaher443** [lxc/lxd#7387]
# Required information

 * Distribution:  Ubuntu Server
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-29-generic
   * LXC version:
   * LXD version: 4.1
   * Storage backend in use: btrfs

# Issue description

After pursuing on discuss.linuxcontainers.org I was asked to submit here. I just configured LXD (sudo lxd init) on a fresh install of Ubuntu Server 20.04. After configuring successfully with my initial user, I added another user to the lxd group (that user is authenticated via LDAP), logged on as that user, and get the following when I type any lxc command (like lxc list):

cannot create user data directory: /home/user2/snap/lxd/15067: Permission denied

The inital user (user1) continues to work fine.

# Steps to reproduce

 1. Install Ubuntu Server 20.04, using btrfs as file system
 2. Configure to authenticate to external system (LDAP)
 3. sudo lxd init
 4. Use defaults in configuration
 5. Type `lxc list`
 6. Log in as user2 using the LDAP authentication
 7. Edit /etc/group to include user2 as member of lxd group
 8. As user2, run `lxc list`
 9. Output is: `cannot create user data directory: /home/user2/snap/lxd/15067: Permission denied`
10. Initial user continues to work fine.

# Information to attach

Output from /var/log/syslog when user2 runs `lxc list`:
`May 18 12:47:18 [myhost] kernel: [263369.012491] audit: type=1400 audit(1589820438.818:50): apparmor="DENIED" operation="open" profile="/usr/lib/snapd/snap-confine" name="/home/user2/" pid=8173 comm="snap-confine" requested_mask="r" denied_mask="r" fsuid=50224 ouid=50224`

**Comment by stgraber** [comment]
Hmm, can you show, this isn't going to be a LXD issue as it's failing before you reach LXD.
So closing the issue as there won't be anything for us to fix.

That being said, we can still figure out what's happening :)

Can you show `stat /home/user2`?

**Comment by johnmaher443** [comment]
Thank you for helping with my issue. Please let me know if I should not continue here and should continue the discussion at discuss.linuxcontainers.org.

```
$ stat /home/user2/
  File: /home/user2/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 901h/2305d	Inode: 3932200     Links: 5
Access: (0700/drwx------)  Uid: (50224/   user2)   Gid: (10001/usergroup)
Access: 2020-05-18 13:07:31.308624597 -0400
Modify: 2020-05-18 12:46:52.014764563 -0400
Change: 2020-05-18 12:46:52.014764563 -0400
 Birth: -
```

**Comment by stgraber** [comment]
Not seeing anything obvious that would tickle snapd the wrong way.

Can you try `snap install hello-world` and run `hello-world` as that user?

**Comment by johnmaher443** [comment]
There certainly is a pattern:

```
$ hello-world
cannot create user data directory: /home/user2/snap/hello-world/29: Permission denied
```
This seems to be related to snap and possibly to LDAP, but I really only have hunches.

**Comment by stgraber** [comment]
Yeah, so you're probably better off showing this at https://forum.snapcraft.io mentioning the `hello-world` case as that's a lot simpler and straightfoward than LXD :)

**Comment by johnmaher443** [comment]
Ok, thanks very much for giving this some attention.  By the way, I just created a local (non-LDAP) user and it was able to run `hello-world` just fine.

**Comment by stgraber** [comment]
I don't see why the uid/gid of an LDAP account would matter, if the user home directory was coming from the network, that'd be a bit different though.

**Comment by stgraber** [comment]
FWIW, all my systems are effectively using LDAP login (through sssd + samba4) and I've never run into this.

**Comment by johnmaher443** [comment]
Definitely helps. Thank you.

**Comment by johnmaher443** [comment]
This has been solved. The issue is that our LDAP users have home directories in the form of /home/primarygroup/username, but snap requires user's home directories to be in /home.  The solution was pointed  out to me (in the [Snapcraft Forum](https://forum.snapcraft.io/)) and is explained [here](https://forum.snapcraft.io/t/how-can-i-use-snap-when-i-dont-use-home-user/3352).
