### ISSUE TITLE
haproxy.service: Failed to reset devices.list: Operation not permitted

### ISSUE THREAD

**Issue by rayj00** [lxc/lxd#7388]
I have HAproxy installed in an LXD 3.0 container.   While monitoring syslog and restarting haproxy, I am seeing this in syslog.  Should I be concerned?

May 19 15:06:31 haproxy systemd[1]: Stopping HAProxy Load Balancer...
May 19 15:06:31 haproxy systemd[1]: Stopped HAProxy Load Balancer.
**May 19 15:06:31 haproxy systemd[1]: haproxy.service: Failed to reset devices.list: Operation not permitted**
May 19 15:06:31 haproxy systemd[1]: Starting HAProxy Load Balancer...
May 19 15:06:31 haproxy systemd[1]: Started HAProxy Load Balancer.

**Comment by rayj00** [comment]
And here's the haproxy status:
root@HAProxy:~# service haproxy status
● haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/lib/systemd/system/haproxy.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-05-19 15:06:31 UTC; 7min ago
     Docs: man:haproxy(1)
           file:/usr/share/doc/haproxy/configuration.txt.gz
  Process: 2217 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS (code=exited, status=0/S
 Main PID: 2218 (haproxy)
    Tasks: 2 (limit: 4659)
   CGroup: /system.slice/haproxy.service
           ├─2218 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
           └─2219 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid

May 19 15:06:31 HAProxy systemd[1]: Starting HAProxy Load Balancer...
May 19 15:06:31 HAProxy systemd[1]: Started HAProxy Load Balancer.

**Comment by stgraber** [comment]
No, that's normal, systemd always logs those when run in a container, it's been this way for years and is harmless.
