### ISSUE TITLE
4.0.1 - After a while SQL logic errors start cropping up

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#7393]
Focal Fossa
LXD 4.0.1

Today a few hosts have started kicking up this error when restarting, starting or stopping containers:

`Error: failed to add Operation 7a7302e8-62ac-4062-905a-a12925239a46 to database: SQL logic error`

I found a thread describing the exact same symptoms here: 

https://discuss.linuxcontainers.org/t/sql-logic-error/6839/15

But no resolution suggested despite a few other users chiming in with the same problem.

`snap restart lxd` "fixes" the problem. I am worried this will only be a temporary fix however looking at the forum discussions - as we can't keep restarting LXD as that brings down containers (albeit briefly)

Update: Seems `snap restart lxd` can clear up the issue for some containers, not others.
Update to the update: On one host a wholesale snap restart cleared up the SQL error for one container, but not another. I tried then just doing a `systemctl reload snap.lxd.daemon` and this cleared it up for the other container as well. This is all very odd :)

I now suspect this may possibly be related to my other issue from yesterday #7385 - The user in question in the forums mentions problems with ports and things being dropped "over time". We thought we had found the culprit yesterday in a Kernel module, but in fact it was just the reboot of LXD which temporarily fixed the problem.

That issue very much persists today unfortunately :(

What we are seeing is that something seems to be happening with the i/o subsystem which creeps in over time. Also this sql error seems to creep in over time - it gets worse quicker the more busy a host is.

One hunch I am working with - based on the mention that lxcfs may be at fault in the forum thread - is that we do `snap set lxd lxcfs.loadavg=true` in order to get nice load averages - this is the only place we mess with lxcfs at all - so I have just now tried disabling that on a couple of hosts and restarted LXD which I will be watching throughout the day to see how that works out.

I am very motivated to provide any information you need and/or access to affectes systems. Thank you for your time and attention as always.

**Comment by Kramerican** [comment]
On a single host we see the `systemctl reload snap.lxd.daemon` fix working but it reverts back into an erroneous state very quickly. We have simply had to resort to the - slightly crazy imo - mitigation of adding this command as a cron job run every minute in order to try and prevent our clients from hitting this error repeatedly.

**Comment by freeekanayaka** [comment]
Is it the error always `failed to add Operation` or are there other different messages too?

**Comment by Kramerican** [comment]
@freeekanayaka It's always that same error message

**Comment by freeekanayaka** [comment]
@Kramerican how comfortable would you be to build LXD from source and run it? I might need to add some more debugging messages to narrow down what the problem is.

**Comment by Kramerican** [comment]
@freeekanayaka well ... My problem with that is that where this is happening consistently is on a production system where we have already had multiple restarts and reboots in the last 48 hours so I would like not to aggravate clients more than is absolute needed. 

I have just checked our staging hosts which are identically configured and there the issue is not showing itself at the moment.

So... Sure I could rebuild from source on our staging system, but that would not get us closer to what the issue is unless I get lucky and the problem crops up there as well ..

**Comment by Kramerican** [comment]
@freeekanayaka I am willing to grant you access to the affected system so you can dig into it there directly - how does that sound?

**Comment by freeekanayaka** [comment]
@Kramerican ah that'd be great of course. This is my public SSH key:

https://launchpad.net/%7Efree.ekanayaka/+sshkeys

**Comment by Kramerican** [comment]
@freeekanayaka Awesome! I just shot you a mail with access details :)

**Comment by freeekanayaka** [comment]
It seems that the system was hitting its `/proc/sys/fs/aio-max-nr` limit of AIO events. Bumping that makes the issue go away.

I'll prepare a branch so we report a better error in this cases.

**Comment by stgraber** [comment]
@freeekanayaka can you send a PR to update production-setup.md with a suitable bump for that sysctl?

**Comment by stgraber** [comment]
doc updated and better errors added so this should catch it in the future.
