### ISSUE TITLE
DNSMASQ leases are not deleted on container deletion in some cases

### ISSUE THREAD

**Issue by johanehnberg** [lxc/lxd#7397]
LXD 4.1 snapd on Ubuntu 20.04

```
$ lxc network show lxdbr0 
config:
  dns.domain: lxd
  ipv4.address: 10.10.1.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:27ac:904c:833a::1/64
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/instances/test
managed: true
status: Created
locations:
- none
```

# Issue description
Consider the case of rapidly re-deploying containers to the same IP, using overrides. In contrast to actual static configurations, the overrides produce a DHCP lease that blocks the use of that IP even after the container is destroyed.

# Steps to reproduce
```
lxc init images:ubuntu/focal/cloud test
lxc config device override test eth0 ipv4.address=10.10.1.5
lxc start test
sleep 20
lxc list # observe correct IP
lxc stop test
lxc delete test
lxc init images:ubuntu/focal/cloud test
lxc config device override test eth0 ipv4.address=10.10.1.5
lxc start test
lxc list # observe incorrect IP (will correct itself after lease runs out)
```

# Expected behaviour
Override works, here are a few approaches:
- Override triggers a removal of any matching lease
- Deleting a container removes associated leases
- Overrides are created as static leases (if DNSMASQ supports it and it takes priority)

**Comment by tomponline** [comment]
Leases should already be released when container is deleted. Please can you send the contents of `/var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases` after the `lxc-delete test` highlighting the lease that still references the old container's IP?

Thanks

**Comment by johanehnberg** [comment]
.5 is first lease
.226 is from rerun
command run after both test containers were deleted, it seems the host name is just replaced with an asterisk.
```
$ cat /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases
1589986620 00:16:3e:fd:0e:d6 10.10.1.226 * ff:03:6a:58:6f:00:02:00:00:ab:11:63:27:20:a2:37:ce:a5:fa
1589986257 00:16:3e:59:16:f0 10.10.1.5 * ff:fc:33:6e:ab:00:02:00:00:ab:11:9c:56:9e:4f:0a:1b:a5:5f
1589988301 00:16:3e:91:ce:62 10.10.1.29 c3 ff:57:77:6f:a9:00:02:00:00:ab:11:4c:d1:33:96:9a:55:59:1d
1589987538 00:16:3e:0d:27:1e 10.10.1.11 c2 ff:af:4a:33:a5:00:02:00:00:ab:11:26:9f:ec:22:88:02:cd:09
1589988126 00:16:3e:c1:81:c9 10.10.1.10 c1 ff:ab:4b:43:0c:00:02:00:00:ab:11:96:36:cc:1c:e7:1a:c2:f8
duid 00:01:00:01:26:51:b6:47:0c:c4:7a:c2:f3:d4
```

**Comment by johanehnberg** [comment]
I guess this is no longer incomplete?

**Comment by tomponline** [comment]
Ill try to recreate this locally and if not will ask for more info. Interesting the hostnames have gone, suggesting lease was indeed released somewhat.

**Comment by johanehnberg** [comment]
Here's a workaround:
sudo killall dnsmasq
sudo sed -i "/${IP}/d" /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases
lxc network set ${TARGET}:lxdbr0 dns.domain lxd # causes lxd to start dnsmasq

**Comment by tomponline** [comment]
I've just tried to re-create this on ubuntu 20.04 and have not succeeded:

```
sudo cat /var/lib/lxd/networks/lxdbr0/dnsmasq.leases
duid 00:01:00:01:26:50:2e:e5:44:8a:5b:25:54:d8

lxc init images:ubuntu/focal/cloud c
lxc config device override c1 eth0 ipv4.address=10.109.89.2
lxc start c1

sudo cat /var/lib/lxd/networks/lxdbr0/dnsmasq.leases
1590592763 00:16:3e:aa:9b:dc 10.109.89.2 c1 ff:2e:26:b3:72:00:02:00:00:ab:11:24:37:70:d1:af:8c:5a:e0
duid 00:01:00:01:26:50:2e:e5:44:8a:5b:25:54:d8

lxc stop c1
lxc delete c1

sudo cat /var/lib/lxd/networks/lxdbr0/dnsmasq.leases
duid 00:01:00:01:26:50:2e:e5:44:8a:5b:25:54:d8

lxc init images:ubuntu/focal/cloud c1
lxc config device override c1 eth0 ipv4.address=10.109.89.2
lxc start c1

sudo cat /var/lib/lxd/networks/lxdbr0/dnsmasq.leases
1590592889 00:16:3e:67:64:78 10.109.89.2 c1 ff:8c:4a:13:d2:00:02:00:00:ab:11:45:08:90:69:85:b8:6a:b0
duid 00:01:00:01:26:50:2e:e5:44:8a:5b:25:54:d8
```

This is using a non-snap build though, so I'll try to re-create this using the snap package.

**Comment by tomponline** [comment]
Tried this on stable snap too and same behaviour, I cannot re-create the issue you are experiencing.

**Comment by johanehnberg** [comment]
I am bisecting to see if it relates to some setting that I am using.

**Comment by johanehnberg** [comment]
I can confirm it does not happen in a virtual machine installing with defaults. I am checking if it may relate to other networks running on the same server.

**Comment by johanehnberg** [comment]
I noticed that after deleting the first container, the lease changes to * only after starting the replacement container:

```
<...>
lxc delete c1
lxc init images:ubuntu/focal/cloud c1
lxc config device override c1 eth0 ipv4.address=10.10.7.201
cat /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases
1590596266 00:16:3e:1a:60:63 10.10.7.201 c1 ff:6e:0c:4d:df:00:02:00:00:ab:11:eb:bd:7f:5d:5d:69:a3:34
<...>
lxc start c1
cat /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.leases
1590596337 00:16:3e:42:6c:ef 10.10.7.243 c1 ff:3e:32:8f:cd:00:02:00:00:ab:11:a6:20:37:eb:7e:2a:ca:55
1590596266 00:16:3e:1a:60:63 10.10.7.201 * ff:6e:0c:4d:df:00:02:00:00:ab:11:eb:bd:7f:5d:5d:69:a3:34
<...>
```

**Comment by johanehnberg** [comment]
First round of bisecting done. Very interesting. I found that the behaviour is consistent across all tested systems. What I know is:
- Rebooting the server removes the problem at least temporarily
- Restarting LXD also removes the problem (sudo snap restart lxd)
- This is occurs even on quite fresh installs (one was 3 days old)
- No kernel upgrades in between (i.e. not running on older kernel before reboot)

Non-exhaustive list of possible triggers:
- The issue may come up only some time after startup
- The issue may be related to other packages that were upgraded on Ubuntu 20.04 this week
- The issue may be related to updates or updating procedure on LXD snap

**Comment by stgraber** [comment]
Did you find anything more on this?

**Comment by johanehnberg** [comment]
I found that sudo snap restart lxd does not always fix the issue, but a reboot still does. I am unsure where to look next.

There does not seem to be a way for me to check snap releases during those days and connect them with commits in the codebase. Most likely I installed with lxd 15272 and error occured on 15359. My gut feeling is there is some difference between the dnsmasq versions included, and maybe the dnsmasq is not restarted on snap refresh, causing the problem.

One approach is also to consider this something that is already fixed, since it does not manifest on new installs. Feel free to close if you share this view. We can return to this if re-emerges.

**Comment by stgraber** [comment]
`dnsmasq` is indeed restarted on LXD status which would happen during a refresh, dnsmasq version hasn't changed in a while though.

The snap imports dnsmasq from Ubuntu 18.04 and the last time it changed was 2018-04-02.

**Comment by stgraber** [comment]
Since we don't really have a good way to pinpoint it or reproduce it, let's close for now, leave a comment in here if it resurfaces and we can try looking into it again.

**Comment by bstivers** [comment]
I am pretty sure I narrowed my issue down to dnsmasq being installed system wide. Removed dnsmasq via apt, rebooted, and back to normal. Not sure why that was even installed. (Probably because metal life started out as a server and was turned into a desktop.)

**Comment by johanehnberg** [comment]
Update on the workaround: as dnsmasq is no longer restarted unless there is a change, changing it twice does the trick:

`lxc network set lxdbr0 dns.domain lxdd; lxc network set lxdbr0 dns.domain lxd # restart dnsmasq`
