### ISSUE TITLE
auto renamed custom storage volume after upgrading to 4.1 ?

### ISSUE THREAD

**Issue by VeryGames** [lxc/lxd#7415]
Hello,

After upgrading to 4.1, all the custom volume names where renamed (probably after the CT restart)

Example:
default/custom/default_vm708521
was renamed to 
default/custom/vm708521

Anyone saw this already ? 
This is a big problem here on upgrade deployment.

Thank you !

 * Distribution: debian
 * Distribution version: buster
 * The output of "lxc info" :
# lxc info
config:
  core.https_address: '[::]:8448'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - x.x.x.x:8448
  - '[::]:8448'
  - 10.71.229.1:8448
  - '[fd42:4a5b:2370:f5f2::1]:8448'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificate_fingerprint: ce1920eafa8db1d70889a349b80b1aa4818a551ae5209f140ae4652fd2f2567b
  driver: lxc
  driver_version: 3.0.3
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 4.19.0-8-amd64
  lxc_features:
    cgroup2: "false"
    mount_injection_file: "false"
    network_gateway_device_route: "false"
    network_ipvlan: "false"
    network_l2proxy: "false"
    network_phys_macvlan_mtu: "false"
    network_veth_router: "false"
    seccomp_notify: "false"
  os_name: Debian GNU/Linux
  os_version: "10"
  project: default
  server: lxd
  server_clustered: false
  server_name: cpu-5219
  server_pid: 1443
  server_version: "4.1"
  storage: zfs
  storage_version: 0.7.12-2+deb10u1

**Comment by stgraber** [comment]
What's the problem exactly?

This isn't a new behavior in 4.1, it dates back to 4.0 or a bit earlier when custom storage volumes were made to be part of projects. This change is only at the driver and filesystem layer, not in anything that's exposed to instances or the user.

If you rely on the specific dataset names or where they're mounted, you're going to have issues as LXD makes no guarantees on either of those and we have already renamed and moved things around quite extensively in the past.

**Comment by stgraber** [comment]
Hmm, your issue says they got renamed from default_XYZ to just XYZ?
That part is odd, as the renaming should be the other way around, adding the default_ prefix...

**Comment by VeryGames** [comment]
We upgraded fro 3.21 to 4.1.

t=2020-05-22T13:22:00+0000 lvl=info msg="Applying patch \"storage_zfs_volmode\""
t=2020-05-22T13:22:00+0000 lvl=info msg="Applying patch \"storage_rename_custom_volume_add_project\""
t=2020-05-22T13:22:00+0000 lvl=info msg="Lazy unmount custom volume \"references\" in pool \"default\""
t=2020-05-22T13:22:00+0000 lvl=info msg="Renaming custom volume \"references\" in pool \"default\" to \"default_references\""
t=2020-05-22T13:22:00+0000 lvl=info msg="Mount custom volume \"default_references\" in pool \"default\""
t=2020-05-22T13:22:00+0000 lvl=info msg="Lazy unmount custom volume \"vm620789\" in pool \"default\""
t=2020-05-22T13:22:00+0000 lvl=info msg="Renaming custom volume \"vm620789\" in pool \"default\" to \"default_vm620789\""
t=2020-05-22T13:22:00+0000 lvl=info msg="Mount custom volume \"default_vm620789\" in pool \"default\""

This is the problem, "storage_rename_custom_volume_add_project" .

**Comment by stgraber** [comment]
Ok, so that patch would have added the default_ prefix to all existing volumes, that's normal.

**Comment by VeryGames** [comment]
Hmm ok, thank you for the fast feedback.
We have to deal with it then.

We are using /var/lib/lxd/storage-pools/default/custom/ mounts from host to access volumes data.
So the path changed and it breaks things our side :x
