### ISSUE TITLE
lxc export - dont copy backup data twice

### ISSUE THREAD

**Issue by curupira** [lxc/lxd#7418]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.15.0-102-generic
   * LXC version: 4.1
   * LXD version: 4.1
   * Storage backend in use:lvm

# Issue description

Please dont copy backup data twice.

# Steps to reproduce

I have several large container in respect to amount of files > 4M an space >1TB. Because lxc export just creates a tar-file, I dont understand, why this cant be created right in the target-place, which I point out in the option, but have to be created in the snap-backup-dir and copy to target afterwards instead. Unfortunately I dont have the luxury of time and space to copy backup-images twice. They have to land in their final place right at the first copy process.

Additionally I would be nice to use pigz instead of gzip. At the moment its faster to backup uncompressed and use pigz afterwards. But this again requires much more diskspace and copy time of uncompressed data than actually nescessary, if the backup would be more optimized.

Thanks

**Comment by stgraber** [comment]
You can set pigz as your compressor, either globally with `backups.compression_algorithm` or through `lxc export`.

LXD is a client/server system, `lxc export` asks the server to make a backup, then fetches that backup.
As as result, the server doesn't know where the client would write it, nor should it. So the best we can do is create one directly compressed tarball on the server side, then stream that to the client. It used to be quite worse (up to 3 copies on the server side) but now we're about as optimized as it can get.

**Comment by curupira** [comment]
Hello, didnt know, that I can use pigz in lxc export. Will try it out. Anyway I wrote a bash script inbetween, which does single copy backups in my configuration, with resulting same backup-files as in lxc export.
Thanks for advise.
