### ISSUE TITLE
`lxc restart` hangs when run immediately after `lxc launch`

### ISSUE THREAD

**Issue by pstch** [lxc/lxd#7419]
# Required information

 * Distribution: NixOS
 * Distribution version: Unstable
 * LXD  version: 4.1 (but happens also on 3.18)
 * The output of `lxc info` : [lxd-info.txt](https://github.com/lxc/lxd/files/4673128/lxd-info.txt)

# Issue description

`lxc restart` hangs when run just after `lxc launch`.

This should be a low-priority issue as it can be worked around easily (but finding the right delay on a loaded machine can be tricky). However, it may not manifest itself each time depending on the latency between the client and the server, so it can make automation scripts hang in a non-deterministic way.

Restarting just after launch is required in some cases where the inner system only applies some of its configuration at boot, since there is no way to launch a stopped container.

# Steps to reproduce

 1. `lxc launch images:debian/10 test && sleep 1 && lxc restart test` => **OK**
 2. `lxc launch images:debian/10 test && lxc restart test` => **Hang**

# Information to attach

 - [ ] Any relevant kernel output : **no relevant output**
 - [X] Container log : [lxd-container-log.txt](https://github.com/lxc/lxd/files/4673131/lxd-container-log.txt)

 - [X] Container configuration : [lxd-container-config.txt](https://github.com/lxc/lxd/files/4673132/lxd-container-config.txt)

 - [ ] Main daemon log
 - [X] Output of the client with --debug : [lxd-client-debug.log](https://github.com/lxc/lxd/files/4673135/lxd-client-debug.log)

 - [X] Output of the daemon with --debug : [lxd-server-debug.log](https://github.com/lxc/lxd/files/4673136/lxd-server-debug.log)

**Comment by stgraber** [comment]
That's normal. `lxc restart` sends a signal to the init system in the container, similar to ctrl-alt-del on a physical system.
If the init system hasn't yet setup its logic to detect and respond to that event, nothing will happen.

`lxc restart --force` should always work as that one doesn't send an event, instead having LXD directly kill everything (causing potential data loss).
