### ISSUE TITLE
Add more flags or filters to `lxc list`

### ISSUE THREAD

**Issue by toby63** [lxc/lxd#7423]
**Context:**
See request in Forum by SeventhSon: https://discuss.linuxcontainers.org/t/list-running-containers/7049

**Description:**
Edit: Take a look at this https://github.com/lxc/lxd/issues/7423#issuecomment-694531799 for an updated concept for this.

---

**Original idea:**
More flags for the `lxc list` command would be useful, to list more details or filter the list.
For example:

container status | flag |
------------------- | ----- |
running | -r |
stopped | -s |
freezed | -f |

container type | flag |
------------------- | ----- |
container | -con |
virtual machine | -vm |

Further ideas (don't seem to be implemented in list yet):

value | flag |
------------------- | ----- |
size/disk-usage of container/vm | -size |
show image the instance is based on | -img |
date of creation | -date
sort by creation date | -age |
network devices | -net |

**Comment by stgraber** [comment]
Don't quite agree with proposed naming, but proposed functionality is fine.

**Comment by chang-andrew** [comment]
Hi there, my name is Andrew and I'm a CS student at UT Austin. Would it be okay if I worked on this issue as part of a learning requirement for a Virtualization class I am taking right now?

**Comment by stgraber** [comment]
@chang-andrew certainly, that sounds good. I'll assign it to you.

As mentioned, we agree with the general need to add more filtering options to `lxc list` though don't really agree with the proposed options above and will need to think about this a bit more to come up with a set of options that should cover most needs, is easily extensible and doesn't end up consuming too many command line flags.

**Comment by stgraber** [comment]
@chang-andrew btw, not sure how many more in that class are looking for good first contributions but I've just gone through some of our backlog and created suitable issues on the LXD project. They can also all be found (for all our projects) at https://discuss.linuxcontainers.org/t/easy-issues-for-new-contributors/7454

Feel free to circulate that link to anyone else interested. We've had great contributions in the past from that class so hoping that this year will be no different :)

**Comment by chang-andrew** [comment]
@stgraber that is amazing and very helpful, thanks so much! I will be sure to share that with the class 😃

**Comment by toby63** [comment]
@chang-andrew @stgraber Could you post the resulting propositions for the flags?
Maybe some people would like to comment :slightly_smiling_face: .

**Comment by stgraber** [comment]
@toby63 my current hope is that we can do away with flags completely and extend the filter syntax instead to match based on API fields. This may be slightly longer to type but would never need updating as it would just automatically evolve as we add more properties in the API.

`lxc list type=virtual-machine location=node03 status=RUNNING user.foo=bar abc -c n46`

This would list anything which:

 - Is a virtual machine
 - Is running on cluster node node03
 - Is running
 - Has a name which starts with abc
 - Has user.abc config key set to foo
 - Print columns name, ipv4 and ipv6

Which is a combination of what we have and what we could add to filters without introducing a bunch of new flags.

**Comment by toby63** [comment]
> my current hope is that we can do away with flags completely and extend the filter syntax instead to match based on API fields.

:thinking: While I understand the benefits of this approach, it seems a bit too long and complicated for me.
I thought about something like this:
For example typing `lxc list r` or (at least) `lxc list running` would list all running containers.

While one could maybe add something like this with `lxc alias` (I suppose it's possible?), this is not very convenient, because it would need many entries and need to be setup for every server that someone might uses.

Potential Alternatives:
1. Shorter version of your idea, for example:

| key: | alternative: |
| --- | --- |
| type=virtual-machine | type=vm |

2. (Assuming it's possible) Add lxc aliases by default, this way `lxc list r` or `lxc list running` could work, but behind the scenes it's the longer command.

**Comment by stgraber** [comment]
`lxc list r` is already a valid syntax listing all containers starting with the letter `r`.

And yeah, we can make the existing API filtering code in LXD understand `vm` to be `virtual-machine` to keep that one short.

Ideally this feature should be built on the filtering API that the UTexas students implemented last year as it allows just passing those filters (in much the same syntax I listed above) directly to LXD and have the server filter the data returned to the client, making the whole process a lot less heavy weight.

**Comment by toby63** [comment]
But is it possible to shorten it with `lxc alias` then?

**Comment by stgraber** [comment]
Yeah, you can still alias things, just don't alias a valid command to something else or you'll get surprised.

Setting an alias from `lxc lsvmr` to `lxc list state=RUNNING type=virtual-machine` for example would be fine, not that we would ship with any of those by default though.

**Comment by ghomem** [comment]
One thing I am missing is an option to list the instances (containers and VMs) with the limits (CPUs, memory, disk,....) to get an overview of resources allocated for the physical system. Would it make sense to add this to the lxc list command? Or is there a separate command for that purpose?

thanks in advance!

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc list -c ns46,limits.memory:MEM,limits.cpu:CPU,devices:root.size:DISK nsd
+-------+---------+-----------------------+--------------------------------------------+------+-----+------+
| NAME  |  STATE  |         IPV4          |                    IPV6                    | MEM  | CPU | DISK |
+-------+---------+-----------------------+--------------------------------------------+------+-----+------+
| nsd01 | RUNNING | 170.39.196.165 (eth0) | 2602:fd23:8:1::5 (eth0)                    | 1GiB | 2   | 5GiB |
|       |         |                       | 2602:fd23:8:1001:216:3eff:feef:a5a3 (eth0) |      |     |      |
+-------+---------+-----------------------+--------------------------------------------+------+-----+------+
| nsd02 | RUNNING | 170.39.196.165 (eth0) | 2602:fd23:8:1::5 (eth0)                    | 1GiB | 2   | 5GiB |
|       |         |                       | 2602:fd23:8:1002:216:3eff:fe3a:8549 (eth0) |      |     |      |
+-------+---------+-----------------------+--------------------------------------------+------+-----+------+
| nsd03 | RUNNING | 170.39.196.165 (eth0) | 2602:fd23:8:1::5 (eth0)                    | 1GiB | 2   | 5GiB |
|       |         |                       | 2602:fd23:8:1003:216:3eff:feca:5a90 (eth0) |      |     |      |
+-------+---------+-----------------------+--------------------------------------------+------+-----+------+
```

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc alias add reslist "list -c ns46,limits.memory:MEM,limits.cpu:CPU,devices:root.size:DISK"
stgraber@castiana:~$ lxc reslist nsd
+-------+---------+-----------------------+--------------------------------------------+------+-----+------+
| NAME  |  STATE  |         IPV4          |                    IPV6                    | MEM  | CPU | DISK |
+-------+---------+-----------------------+--------------------------------------------+------+-----+------+
| nsd01 | RUNNING | 170.39.196.165 (eth0) | 2602:fd23:8:1::5 (eth0)                    | 1GiB | 2   | 5GiB |
|       |         |                       | 2602:fd23:8:1001:216:3eff:feef:a5a3 (eth0) |      |     |      |
+-------+---------+-----------------------+--------------------------------------------+------+-----+------+
| nsd02 | RUNNING | 170.39.196.165 (eth0) | 2602:fd23:8:1::5 (eth0)                    | 1GiB | 2   | 5GiB |
|       |         |                       | 2602:fd23:8:1002:216:3eff:fe3a:8549 (eth0) |      |     |      |
+-------+---------+-----------------------+--------------------------------------------+------+-----+------+
| nsd03 | RUNNING | 170.39.196.165 (eth0) | 2602:fd23:8:1::5 (eth0)                    | 1GiB | 2   | 5GiB |
|       |         |                       | 2602:fd23:8:1003:216:3eff:feca:5a90 (eth0) |      |     |      |
+-------+---------+-----------------------+--------------------------------------------+------+-----+------+
```

**Comment by ghomem** [comment]
@stgraber awesome! Somehow we didn't find it. Thank you :-) :+1:

**Comment by ghomem** [comment]
@stgraber here is a script that prints that list and sums the rows to obtain the totals:

https://bitbucket.org/asolidodev/ironman/src/master/puppet/is_lxd/files/lxd-used-resources.sh

Would be better if LXD could sum the summable fields directly but for now this script is a must for us.

![Screenshot_20210115_150935](https://user-images.githubusercontent.com/3352900/104743525-b2da2c00-5743-11eb-8061-a8614ffe7a00.png)

**Comment by stgraber** [comment]
@chang-andrew Do you still intend to work on this or should we un-assign so someone else can have a go at it?

**Comment by chang-andrew** [comment]
Apologies, yes would you mind unsigning me? I have not been able to make much progress on this.

**Comment by my5t3ry** [comment]
Hello,

first of all, i did not realize that adding the issue url in commit messages will spam this thread with my commit references. sry for that :/

i found the issue at https://discuss.linuxcontainers.org/t/easy-issues-for-new-contributors/7454. 
i think i implemented what was requested. I never wrote something in golang before, so i'm pretty shure the code is crap. Maybe it's possible that somebody could take a look if what i did and give some feedback.
That would be nice, thx :)

this is what i ended up with ->
https://github.com/my5t3ry/lxd/commit/4e776001d9d932300253da41b72278ce2f55060b

**Comment by toby63** [comment]
@my5t3ry Thx for the approach, but could you open a pull request for this?
Also please follow the [contributing guidelines](https://github.com/lxc/lxd/blob/master/doc/contributing.md).

**Comment by my5t3ry** [comment]
@toby63 i created a pull request -> 
https://github.com/lxc/lxd/pull/8562

i tried to fix all commits according the contribution guidelines. i'm not expecting to get it merged, but would be happy to get feedback how to work it into the right direction. 

thx :)

**Comment by my5t3ry** [comment]
@toby63 i created a pull request ->
https://github.com/lxc/lxd/pull/8562

i tried to fix all commits according the contribution guidelines. i'm not expecting to get it merged, but would be happy to get feedback how to work it into the right direction.

thx :)

**Comment by toby63** [comment]
@my5t3ry Thx for your effort, it is up to the LXD team to review and potentially merge it, just wait some time, I am sure someone will comment.
I will take a look at it too; I am no programmer though :wink:.

**Comment by ingobaab** [comment]
I do not understand this "(1 more)" srtring and the list:

`| alpine/edge/cloud (1 more)   | x86_64       | CONTAINER       | 21.43MB  | CONTAINER       | 040f5977adf1 | 040f5977adf1f910db5f44c754c6c1a976de76fb6eeed4e64e74c78dd04cd67b |
+------------------------------+--------------+-----------------+----------+-----------------+--------------+------------------------------------------------------------------+
| alpine/edge/cloud (1 more)   | x86_64       | VIRTUAL-MACHINE | 121.69MB | VIRTUAL-MACHINE | ca93784bc0b1 | ca93784bc0b1f641fcd1f24a0fda4602506422d484fc5b5e7570ee9c24c23b78 |
+------------------------------+--------------+-----------------+----------+-----------------+--------------+------------------------------------------------------------------+
`
the command works:
`ingo@elitebook ~ $ lxc image show images:beea71b48edf
auto_update: false
properties:
  architecture: amd64
  description: Alpine 3.16 amd64 (20220708_13:01)
  os: Alpine
  release: "3.16"
  requirements.secureboot: "false"
  serial: "20220708_13:01"
  type: squashfs
  variant: default
public: true
expires_at: 1970-01-01T00:00:00Z
profiles: []
`
