### ISSUE TITLE
[Feature Request] lxc config show -a 

### ISSUE THREAD

**Issue by toby63** [lxc/lxd#7424]
**Description:**
I imagine a flag `-a` for `lxc config show`, that will show all configuration information, including the configuration applied by profiles.

This would save one (or even multiple) steps, when someone wants to see all configuration of a container or vm.

**Comment by stgraber** [comment]
That's what `lxc config show --expanded` does.

**Comment by toby63** [comment]
Thank you.

But its a bit bulky, is there a shorter one?
If not, could that be implemented?

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/pull/7425
