### ISSUE TITLE
Failed applying patch "storage_lvm_skipactivation"

### ISSUE THREAD

**Issue by fendrychl** [lxc/lxd#7427]
# Required information

 * Distribution: Debian
 * Distribution version: 10 (snap)
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.19.0-8-amd64
   * LXC version: 4.0.2
   * LXD version: 4.0.1
   * Storage backend in use: lvm

# Issue description

Hello, I received update through snap today and LXD fails to apply storage_lvm_skipactivation patch.

> Failed to start the daemon: Failed applying patch \"storage_lvm_skipactivation\": Error getting LVM logical volume list for storage pool \"default\": Failed to run: lvs --noheadings -o lv_name,lv_attr default: Volume group \"default\" not found\n  Cannot process volume group default

The problem is here I think: https://github.com/lxc/lxd/blob/9cd9eac4cf1e78bb78592551947720e7bb776f0b/lxd/storage/drivers/driver_lvm_patches.go#L15

I have different volume group name, so "d.name" should be "d.config["lvm.vg_name"]"?

Thank you.

**Comment by stgraber** [comment]
Oops, indeed, looks like both @tomponline and I missed this :)

Patch sent, we'll cherry-pick into the snap as soon as CI says it's good.

**Comment by stgraber** [comment]
A temporary workaround would be to write `/var/snap/lxd/common/database/patch.local.sql` containing:
 - `INSERT INTO patches (name, applied_at) VALUES ('storage_lvm_skipactivation',1590073806);`

And then manually do what the patch does so your LVs are not auto-activated.

**Comment by fendrychl** [comment]
Wow! Thanks for the lightning fast response. For me it's ok right now, I can wait for the new version.

**Comment by stgraber** [comment]
For anyone else hitting this. I've cherry-picked the fix into the candidate branch of both 4.1 and 4.0 snap.
It's now building and should be available in the next two hours. If you're stuck on this, refresh to the matching candidate channel and that should unblock you.

It's unfortunately a bit too late here to wait for it to build on all 6 architectures and goes through automated QA so I'll be releasing to stable first thing tomorrow instead (~11 hours from now).

**Comment by tomponline** [comment]
thanks @stgraber
