### ISSUE TITLE
Abillity to hot plug network devices would be cool

### ISSUE THREAD

**Issue by zulcss** [lxc/lxd#743]
Nova needs to hotplug interfaces to the container. Entering the name space to configure the IP address is quite easy to do, keeping track of things is a different matter.

**Comment by hallyn** [comment]
@zulcss,

Hi Chuck,

Can you describe exactl how you would want to do it?  I assume you want to plug a nic which you create into the container;  is it veth?

The current support will allow you to ask lxd to create a veth pair, plugging one end into a bridge you specify, and the other end in the container.  I don't think that's good enough for you.

**Comment by zulcss** [comment]
Yeah thats good enough

**Comment by hallyn** [comment]
Oh, cool, then I'll close this issue.  Thanks.
