### ISSUE TITLE
lxd v0.7-0 + ubuntu server 15.04 = ulimit doesn't work

### ISSUE THREAD

**Issue by geekon75** [lxc/lxd#745]
Hello,

I make some tests with lxd, and I found (In my opinion) big problem
On Lxd ( 0.7-0ubuntu1 , run on Ubunru server 15.04 ( amd64 ))
I cannot use ulimit command. I tried run this, on Linux Debian 7
container. Example:

# ulimit -n 65000
bash: ulimit: open files: cannot modify limit: Operation not permitted

ulimit with read only parameter ( ulimit -n ) works great ( ;) )
on lxc, ulimit works great.

Regard

GK

PS I checked "ulimit problem" on lxd 0.10, and problem exists in new version :/

**Comment by stgraber** [comment]
Hi,

That's not related to LXD at all but to user namespaces.

You'll notice the exact same when using unprivileged containers under LXC.

Basically what's going on there is that even though it looks like you're root in the container, you're actually uid 165536 (or similar) outside the container, which doesn't have the right to increase user limits, only reduce them.

Today it's not possible to workaround this but it's probably worth considering adding some ulimits to the ever growing list of security knobs in LXD so that the default ulimit for the container can be increased at startup time, therefore letting the user deal with larger values (they'd still not be able to increase them, they'd just start at a higher value).

**Comment by geekon75** [comment]
Thank you for the quick reply.

Can you tell me, how can I  turn off unprivileged mode
and use ulimit command  on my containers.
I use Ubuntu server v15.04 and LXD v0.10

Regards

GK

**Comment by stgraber** [comment]
# Create a new unprivileged container profile
lxc profile create privileged
lxc profile set security.privileged true

# Start a new container from "image" using the privileged profile
lxc launch image blah --profile default,privileged

**Comment by geekon75** [comment]
Thank you very much for answer, but I hava still problem...
Actually I use file system containers and I run them by lxc start <CT-NAME>
Is there solution for my sytuation / environment ???

Regards

GK

**Comment by geekon75** [comment]
When I do changes in profile configuration, by use command: "lxc profile set security.privileged true", should I see any changes, when I use command: "lxc profile show privileged" ?.
I see only standard output:

# lxc profile show privileged
name: privileged
config: {}
devices: {}

Regards

GK

**Comment by tych0** [comment]
On Tue, Jun 09, 2015 at 08:04:50AM -0700, geekon75 wrote:
> When I do changes in profile configuration, by use command: "lxc profile set security.privileged true", should I see any changes, when I use command: "lxc profile show privileged" ?.

You need to set the profile name (the fact that this command doesn't
error out is a bug that is fixed in later releases, apologies):

`lxc profile set privileged security.privileged true`

**Comment by geekon75** [comment]
Oh yes. I was close :) After changes,  container works excelent
Wery, wery thank for solution !
This information was very important and necessary.

Where can I see all possible configuration options for container ?

Regards

GK

**Comment by tych0** [comment]
On Tue, Jun 09, 2015 at 08:20:07AM -0700, geekon75 wrote:
> Oh yes. I was close :) After changes,  container works excelent
> Wery, wery thank for solution !
> This information was very important and necessary.
> 
> Where can I see all possible configuration options for container ?

https://github.com/lxc/lxd/blob/master/specs/configuration.md

**Comment by geekon75** [comment]
Tkank you, thank you. It's very important link, for me even critical.
It's strange, that I can't saw this document...

Regard

GK

**Comment by linuxtim** [comment]
Until full ulimit support is added, it might be nice to add:

`LimitNOFILE=65536`

to the [service] section of `/lib/systemd/system/lxd.service`

in the vivid packages?

The number chosen is a little arbitrary of course, but hopefully strikes a balance between resource exhaustion (which seems pretty likely with default 1024:4096 setting which systemd applies by default on vivid), and host resource exhaustion/DoS?

**Comment by stgraber** [comment]
Sounds like a good idea indeed.
