### ISSUE TITLE
Add easier `set`ting of image properties (e.g. description)

### ISSUE THREAD

**Issue by dionysius** [lxc/lxd#7450]
# Required information

   * LXC version: 4.1
   * LXD version: 4.1

# Issue description

Currently it is difficult to set image properties in automated fashion. The `lxc image` command group has no `set` (and `get`, `unset`) commands to set the image properties in contrary to the `network`, `storage`, `config`, `profile` counterparts . You can only set them via `edit` manually or by piping a full yaml.

# Information to attach

```bash
# lxc image --help
Description:
  ...

Usage:
  lxc image [command]

Available Commands:
  alias       Manage image aliases
  copy        Copy images between servers
  delete      Delete images
  edit        Edit image properties
  export      Export and download images
  import      Import images into the image store
  info        Show useful information about images
  list        List images
  refresh     Refresh images
  show        Show image properties

Global Flags:
  ...
```
```bash
# lxc image edit --help
Description:
  ...

Usage:
  lxc image edit [<remote>:]<image> [flags]

Examples:
  lxc image edit <image>
      Launch a text editor to edit the properties

  lxc image edit <image> < image.yaml
      Load the image properties from a YAML file

Global Flags:
  ...
```
```bash
# lxc network --help
Description:
  ...

Usage:
  lxc network [command]

Available Commands:
  ...
  get            Get values for network configuration keys
  ...
  set            Set network configuration keys
  ...
  unset          Unset network configuration keys

Global Flags:
  ...
```

**Comment by stgraber** [comment]
We normally reserve `get/set/unset` to modify config keys.
Images do not currently have config keys which is why they don't have those commands.

We could introduce `{get,set,unset}-property` in this case though.

**Comment by dionysius** [comment]
I could also see a 'properies' subcommand before set, get, unset. The chain is then longer, but the commands itself shorter.

**Comment by dionysius** [comment]
Or/And allow a `--description` property in `lxc publish`

**Comment by stgraber** [comment]
For `lxc publish` you can alter all of that through `lxc config metadata` on the instance prior to publishing.

**Comment by tbobo** [comment]
Hi! I would like to work on this issue along with some colleagues (@ej-castillo and @dramos20) as a part of a course on Virtualization at The University of Texas at Austin. Would it be alright if we were assigned this? Thanks in advance.

**Comment by stgraber** [comment]
Assigned. Same deal as the other two, I'll assign @ej-castillo and @dramos20 once they comment in the issue.

**Comment by dramos20** [comment]
Hi, I will be working on this with @tbobo . Can I be assigned to this? Thank you!

**Comment by stgraber** [comment]
Done!

**Comment by ej-castillo** [comment]
Commenting to be assigned to issue.
