### ISSUE TITLE
Exporting image writes wrong image description

### ISSUE THREAD

**Issue by dionysius** [lxc/lxd#7451]
# Required information

   * LXC version: 4.1
   * LXD version: 4.1

# Issue description

When exporting an image using `lxc image export`, I expected that the metadata.yaml in the archive contains the description of the image property description. Instead, it (re-)uses the image that was based on.

# Steps to reproduce

```bash
# lxc image alias list ci/test
+---------+--------------+-----------+-------------+
|  ALIAS  | FINGERPRINT  |   TYPE    | DESCRIPTION |
+---------+--------------+-----------+-------------+
| ci/test | bdab3a6ba9c2 | CONTAINER |             |
+---------+--------------+-----------+-------------+

# lxc image list ci/test
+---------+--------------+--------+-------------+--------------+-----------+----------+-------------------------------+
|  ALIAS  | FINGERPRINT  | PUBLIC | DESCRIPTION | ARCHITECTURE |   TYPE    |   SIZE   |          UPLOAD DATE          |
+---------+--------------+--------+-------------+--------------+-----------+----------+-------------------------------+
| ci/test | bdab3a6ba9c2 | no     | foo         | x86_64       | CONTAINER | 613.12MB | May 27, 2020 at 12:32pm (UTC) |
+---------+--------------+--------+-------------+--------------+-----------+----------+-------------------------------+

# lxc image show ci/test
auto_update: false
properties:
  description: foo
public: false
expires_at: 0001-01-01T00:00:00Z
profiles:
- default

# lxc image export ci/test test
Image exported successfully!

# tar zxf test.tar.gz

# grep -C2 description metadata.yaml 
properties:
    architecture: "x86_64"
    description: "Ubuntu 16.04 LTS server (20200522)"
    os: "ubuntu"
    release: "xenial"
```

**Comment by stgraber** [comment]
That's unfortunately not possible.

LXD images are identified by their SHA256, that SHA256 is made of the combination of their metadata and root tarballs.
Any alteration to the metadata tarball would break the hash.

When an image is imported/exported using a tarball, you only get the pristine metadata that came from that image.
That's different than when you copy an image as that part happens through the API and so the image creation request gets a copy of the properties from the source.

**Comment by stgraber** [comment]
One option for you is to do `lxc image show HASH > HASH.yaml` and then re-apply that on the target.

**Comment by dionysius** [comment]
`lxc image show HASH > HASH.yaml` sounds promising enough. Thank you!
