### ISSUE TITLE
Document available export/image compression methods

### ISSUE THREAD

**Issue by johanehnberg** [lxc/lxd#7456]
LXD 4.1 snap on Ubuntu 20.04

Please document available compression algorithms and requirements. It seems they are not built in nor delivered with the snaps but have to be installed separately, for example using apt.

Here is what I gather:
- Documentation mentions **bz2, gz, xz, lzma, tar** 
- https://github.com/lxc/lxd/issues/6284 mentions **none**
- https://github.com/lxc/lxd/commit/309c8d8c8c9c4160330e7938080142adafb61307 mentions **pigz**

Out of these, pigz is the only multithreaded as-is, making it quite valuable to mention.

**Comment by johanehnberg** [comment]
As a related thought, if compression actually just forwards the responsibility to the plaform, the parameter could be a freeform string, allowing admins to select something like "zstd -T0".

**Comment by stgraber** [comment]
There is no validation on the LXD side, any command that's available to LXD can be used as a compressor.
This is why there is no documentation on the valid values.
