### ISSUE TITLE
Invalid limits (NPROC) set after switching to the user "root" using sudo inside the container (pam_limits.so in sudo session)

### ISSUE THREAD

**Issue by percoz** [lxc/lxd#7461]
# Required information

 * Distribution: Ubuntu Server
 * Distribution version:16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-169-generic
   * LXD version: 3.0.3-0ubuntu1~16.04.1
   * Storage backend in use: LVM

# Issue description

In a non-privileged container, when switching to the "root" user using sudo from a user logged in via SSH, limits (e.g. NPROC) are not set correctly despite pam_limits.so enabled in /etc/pam.d/sudo.

Current behavior:
Limits are set only within the allowed limits for a regular user from which switching to the "root" account has been made.

Expected behavior:
limits for the "root" user should be set according to the entries in the /etc/security/limits.conf file

Additional informations:
After logging in directly to the root account using SSH, the limits are set correctly:
```
root@ap-test-debian9:~# ulimit -u
9000
root@ap-test-debian9:~# ulimit -Hu
10000
```

# Steps to reproduce

The test was performed on the debian 9 system inside the container.

1. Enable pam_limits.so in /etc/pam.d/sudo
```
#%PAM-1.0
session    required   pam_limits.so

@include common-auth
@include common-account
@include common-session-noninteractive
```
2. Set limits in the /etc/security/limits.conf file are as follows:
```
* soft nproc 2000
* hard nproc 3000
test soft nproc 5000
test hard nproc 7000
root soft nproc 9000
root hard nproc 10000
```

3. Login to a standard user via SSH
4. Check the limits of a regular user ("test") logged in using SSH:
```
test@ap-test-debian9:~$ ulimit -u
5000
test@ap-test-debian9:~$ ulimit -Hu
7000
```

5. Switch to the "root" user using sudo and check the limits:
```
test@ap-test-debian9:~$ sudo su
root@ap-test-debian9:/home/test/test# ulimit -u
5000
root@ap-test-debian9:/home/test/test# ulimit -Hu
7000
```

**Comment by stgraber** [comment]
Nothing LXD can do about this. Unprivileged containers are as their name implies, unprivileged.
So root in the container doesn't have any more rights to raise ulimit than a random user on the system.

**Comment by stgraber** [comment]
Limits for non-real-root can only be lowered, never be raised, that's what's hitting you there.

**Comment by percoz** [comment]
thank you for the quick reply.
---
When logging in directly with SSH to the "root" account, the limits are set correctly.

If I understand You correctly, the problem is not in setting limits for the "root" account (as it happens when logging in directly to this account), but in raising / changing them using pam_limit.so in sudo when switching from different user?

**Comment by stgraber** [comment]
Correct, sshd itself likely has a high limit so logging in as root either causes no changes or a lowering.
Your user session running sudo is on a low value and needs to be raised, which isn't possible.
