### ISSUE TITLE
LXD removes LVM block devices on container stop

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#7466]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-33-generic
   * LXC version: 4.0.2
   * LXD version: 4.1
   * Storage backend in use: dir | lvm

# Issue description

I created a container using an LVM storage pool. I need to increase the size of the container. I can stop the container and resize it with lvresize however LXD is removing the block device so I can't run resize2fs. lvchange -a y <vg>/<lv> does not bring back the block device.

I have libvirt configured to use the same storage pool and block devices are always available whether the virtual machine is on or off.

# Steps to reproduce

 1. Create an LVM storage pool
 2. Launch a container which uses the LVM storage pool
 3. Stop the container
 4. Block device is no longer available.

**Comment by stgraber** [comment]
Yes, that's a deliberate change in LXD, we just don't want to keep block devices around as we have systems with thousands of them which then causes all kind of interesting side effects.

As you want to resize your container, just override its size and LXD will do the resizing for you.
`lxc config device override NAME root size=50GB` or if your container already has its own `root` device, then use `lxc config device set NAME root size 50GB`.

If you really must play with the block device directly, running `lvchange --activate y --ignoreactivationskip NAME` should do it.
