### ISSUE TITLE
Snap has non-configurable lvm.conf . Server settings does not apply to snap.

### ISSUE THREAD

**Issue by olaor** [lxc/lxd#7483]
# Required information

 * Distribution: Ubuntu Server
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:

# Issue description

I have a rather custom configuration for filter = and global_filter in my /etc/lvm/lvm.conf file. Since lxd is installed via a snap I am unable to make those settings available for lxd at runtime, which makes lxd init fail since it can see a physical volume two times. No issues detected when running the same lvm commands on the non-snap command line. 

# Steps to reproduce

1. change the filter or global_filter variables in /etc/lvm/lvm.conf
2. Run lxd init and watch the warnings still be there
3. run lvm commands as normal and watch them succeed.

**Comment by stgraber** [comment]
Dup of https://github.com/lxc/lxd-pkg-snap/issues/41

**Comment by stgraber** [comment]
(well, not failing for the same reason, but same root of the issue)

**Comment by olaor** [comment]
Yes, the root of the issue is that you think like developers and create unmanageable containerized software. Pretty normal stuff. If you absolutely NEED to not package the software so it integrates properly with the OS it runs on you should at least have a very good plan on how to customize that container package in a way that survives updates.

How can I change the settings in the lvm.conf file that is included in the snap in a way that survives the next update without the user having to figure out how to manually unpack and repack the entire snap every time?

**Comment by olaor** [comment]
Please pardon the snarkyness. I really love LXD, but then I wish nobody would distribute their programs in their completely own ecosystem. It's often a nightmare for sysadmins.

Sorry. And thanks for making such great software.
