### ISSUE TITLE
Cannot set volatile.eth0.host_name

### ISSUE THREAD

**Issue by qiet72** [lxc/lxd#7490]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.3.0-51-generic
   * LXC version: 4.1
   * LXD version: 4.1
   * Storage backend in use: btrfs

# Issue description

When I try to set the config option volatile.eth0.host_name either through "lxc config edit" or "lxc config set", it is ignored and goes back to vethXXXXX.  Editing the config option when the instance is stopped or not does not make a difference.  In LXD 3.0.3 this was possible.

# Steps to reproduce
lxc init ubuntu:18.04 ubuntu-1804
lxc config set ubuntu-1804 volatile.eth0.host_name test
lxc start ubuntu-1804
lxc info ubuntu-1804 --show-log

# Information to attach

Name: cnmaestro
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/06/05 16:59 UTC
Status: Running
Type: container
Profiles: default
Pid: 9974
Ips:
  eth0:	inet	10.0.0.112	vethdfe77f8c
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 1020
  CPU usage:
    CPU usage (in seconds): 437
  Memory usage:
    Memory (current): 3.57GB
    Memory (peak): 3.60GB
  Network usage:
    eth0:
      Bytes received: 387.91kB
      Bytes sent: 17.02kB
      Packets received: 4155
      Packets sent: 201
    lo:
      Bytes received: 7.49MB
      Bytes sent: 7.49MB
      Packets received: 67579
      Packets sent: 67579

Log:

lxc cnmaestro 20200605180050.899 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.cnmaestro"
lxc cnmaestro 20200605180050.900 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.cnmaestro"
lxc cnmaestro 20200605180050.900 ERROR    utils - utils.c:lxc_can_use_pidfd:1855 - Invalid argument - Kernel does not support waiting on processes through pidfds
lxc cnmaestro 20200605180050.902 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1572 - No such file or directory - Failed to fchownat(17, memory.oom.group, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )

**Comment by tomponline** [comment]
You shouldnt edit volatile keys. These are internal only and liable to change without warning.

Please set the 'host_name' property on the device instead as that is a documented key.
