### ISSUE TITLE
Error message incorrect

### ISSUE THREAD

**Issue by jamielsharief** [lxc/lxd#7497]
When trying to create a volume with the size `64MB`, I get the following error. I also tried `65MB` and got the same error.

```bash
Failed to run: zpool create -f -m none -O compression=on foo /var/snap/lxd/common/lxd/disks/foo.img: cannot create 'foo': one or more devices is less than the minimum size (64M)
```

**Comment by jamielsharief** [comment]
Note. I made a mistake and posted to `/storage_pools` so the error was when creating a storage pool not a volume. Still when increased size to 1GB it let me. So I think the error message is still wrong.

**Comment by stgraber** [comment]
We don't control that error, it's straight from ZFS.

I suspect it's a MB vs MiB thing though, try giving it 65MiB see if it's happy then.
