### ISSUE TITLE
If you add another network device lxc list IPV6 output order is wrong.

### ISSUE THREAD

**Issue by cemzafer** [lxc/lxd#7499]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-33
   * LXC version: 4.2
   * LXD version: 4.2 
   * Storage backend in use: zfs

# Issue description

If you add another ethernet device lxc list output order is wrong in IPV6 column. 

# Steps to reproduce

 1. Add another network device to container
 2. lxc list
 3. The output looks like that.
```
+-----------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| alpine    | RUNNING | 192.168.1.98 (eth0)   | fd42:4be4:539a:702a:216:3eff:fee9:9635 (eth1) | CONTAINER | 0         |
|           |         | 192.168.1.142 (eth1)  | fd42:4be4:539a:702a:216:3eff:fe9a:c139 (eth0) |           |           |
+-----------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
```
# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Not exactly wrong, it's sorted in both cases, just happens to be sorted by IP rather than by interface and then by IP :)

**Comment by stgraber** [comment]
Ok, so looked at it some more, the sorting is indeed by address and not by interface and looks like it's deliberate and may break people if we somehow change it, so I don't think we will.
