### ISSUE TITLE
No way to un-set server config values

### ISSUE THREAD

**Issue by mikemccracken** [lxc/lxd#751]
The CLUI spec doesn't explain how to un-set config values.
The most obvious way would be to support `lxc config unset core.keyname`

**Comment by stgraber** [comment]
"config unset", "profile unset" and "image unset" are all commands specified in the command-line-user-experience.md.

**Comment by mikemccracken** [comment]
On a second look, the spec does indeed show `config unset [resource] key`.
I probably misinterpreted the [resource] part.

However, the code expects the resource name to be there, so I've implemented two-arg `config unset key` for server config values. Will push a PR shortly, once it passes tests
