### ISSUE TITLE
Storage info returns images from wrong? project

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#7518]
Version 4.2

In the project `default` with a zfs pool created by lxd called `default`, run the command `lxc storage info default` returns a list of containers & images and the images are from the wrong project

**Comment by stgraber** [comment]
Hmm, can you show:
 - lxc query /1.0/projects?recursion=1
 - lxc query /1.0/storage-pools/default

**Comment by turtle0x1** [comment]
```
lxc query /1.0/projects?recursion=1
[
	{
		"config": {
			"features.images": "true",
			"features.profiles": "true"
		},
		"description": "Default LXD project",
		"name": "default",
		"used_by": [
			"/1.0/images/229220dae6164a63ce6d00b4b1ba51e0ee533ef823e36cc56de7a53ae3884d83",
			"/1.0/images/3fddda7e68f96ee1422371ab15043d2f0fe2758602f4079fe4955ef3be18121e",
			"/1.0/images/ecca2cbe9df8630f00c6853c8692d581b4ae279e7c0c5744c3bd9af1b8bdd8ed",
			"/1.0/instances/c0-node0?project=default",
			"/1.0/instances/c0-node1?project=default",
			"/1.0/instances/c1-node0?project=default",
			"/1.0/instances/c1-node1?project=default",
			"/1.0/instances/lxdMosaic?project=default",
			"/1.0/instances/lxdmosaic-build-new?project=default",
			"/1.0/instances/lxdmosaic-build?project=default",
			"/1.0/instances/music?project=default",
			"/1.0/profiles/4bnwfHSnGeiU?project=default",
			"/1.0/profiles/default-vm-profile?project=default",
			"/1.0/profiles/default?project=default",
			"/1.0/profiles/test?project=default"
		]
	},
	{
		"config": {
			"features.images": "true",
			"features.profiles": "true",
			"features.storage.volumes": "true"
		},
		"description": "tes",
		"name": "was",
		"used_by": [
			"/1.0/images/5b72cf46f628b3d60f5d99af48633539b2916993c80fc5a2323d7d841f66afbe",
			"/1.0/profiles/OqU4eldc4joa?project=was",
			"/1.0/profiles/default?project=was",
			"/1.0/profiles/was-profile?project=was"
		]
	}
]

```

```
lxc query /1.0/storage-pools/default
{
	"config": {
		"size": "43GB",
		"source": "/var/snap/lxd/common/lxd/disks/default.img",
		"zfs.pool_name": "default"
	},
	"description": "",
	"driver": "zfs",
	"locations": [
		"none"
	],
	"name": "default",
	"status": "Created",
	"used_by": [
		"/1.0/containers/music",
		"/1.0/containers/c0-node0",
		"/1.0/containers/c0-node1",
		"/1.0/containers/c1-node0",
		"/1.0/containers/c1-node1",
		"/1.0/containers/lxdMosaic",
		"/1.0/containers/lxdmosaic-build",
		"/1.0/containers/c0-node0/snapshots/rea",
		"/1.0/containers/lxdmosaic-build-new",
		"/1.0/containers/c0-node1/snapshots/test",
		"/1.0/images/5b72cf46f628b3d60f5d99af48633539b2916993c80fc5a2323d7d841f66afbe",
		"/1.0/images/229220dae6164a63ce6d00b4b1ba51e0ee533ef823e36cc56de7a53ae3884d83",
		"/1.0/profiles/default"
	]
}

```

**Comment by stgraber** [comment]
Ok, I don't think it's necessarily wrong for used_by to reference the things that are using the pool even across project since they are indeed using that shared object and deleting the pool could only be done once all those references are gone.

But the URLs should use the same format as for projects where the project is indicated in the URL.

Can you show `lxc query/1.0/networks/lxdbr0` see if that one looks correct?

**Comment by turtle0x1** [comment]
My problem comes from the fact you can't reach the image with fingerprint without the project, so it would solve my problems if the project was included in everywhere you can (or you can reach a fingerprint without a project but that would be inconsistent I guess)

(I guess this should show project info as-well)
```
lxc query /1.0/networks/lxdbr0
{
	"config": {
		"ipv4.address": "10.83.58.1/24",
		"ipv4.nat": "true",
		"ipv6.address": "fd42:2040:4413:1b4d::1/64",
		"ipv6.nat": "true"
	},
	"description": "",
	"locations": [
		"none"
	],
	"managed": true,
	"name": "lxdbr0",
	"status": "Created",
	"type": "bridge",
	"used_by": [
		"/1.0/instances/c0-node0",
		"/1.0/instances/c0-node1",
		"/1.0/instances/c1-node0",
		"/1.0/instances/c1-node1",
		"/1.0/instances/lxdMosaic",
		"/1.0/instances/lxdmosaic-build",
		"/1.0/instances/lxdmosaic-build-new",
		"/1.0/instances/music"
	]
}
```

**Comment by turtle0x1** [comment]
Also `lxc query /1.0/storage-pools/default` is missing 3 images

**Comment by stgraber** [comment]
This would suggest that `3fddda7e68f96ee1422371ab15043d2f0fe2758602f4079fe4955ef3be18121e` and `ecca2cbe9df8630f00c6853c8692d581b4ae279e7c0c5744c3bd9af1b8bdd8ed` exist in the `images` directory as tarballs but have not been loaded up as datasets in that particular ZFS pool.

**Comment by stgraber** [comment]
Do you have any instances in that project? All the output so far points to you not having any instances in there, which would make the `/1.0/networks/lxdbr0` output correct.

**Comment by stgraber** [comment]
Here, I see:

```

```stgraber@castiana:~$ lxc query /1.0/networks/lxdbr0
{
	"config": {
		"dns.search": "lxd, stgraber.net",
		"ipv4.address": "10.166.11.1/24",
		"ipv4.nat": "true",
		"ipv6.address": "fd42:4c81:5770:1eaf::1/64",
		"ipv6.nat": "true"
	},
	"description": "",
	"locations": [
		"none"
	],
	"managed": true,
	"name": "lxdbr0",
	"status": "Created",
	"type": "bridge",
	"used_by": [
		"/1.0/instances/v1?project=camp",
		"/1.0/instances/b1",
		"/1.0/instances/bionic",
		"/1.0/instances/c1",
		"/1.0/instances/centos3",
		"/1.0/instances/centos4",
		"/1.0/instances/f1",
		"/1.0/instances/keybase",
		"/1.0/instances/npm",
		"/1.0/instances/snapcraft",
		"/1.0/instances/steam",
		"/1.0/instances/ubuntu-core18",
		"/1.0/instances/ubuntu1804",
		"/1.0/instances/ubuntu2004",
		"/1.0/instances/ups-monitor",
		"/1.0/instances/win10",
		"/1.0/instances/zerotier"
	]
}

**Comment by stgraber** [comment]
Based on this, it looks like the issues we're seeing above are:
 - `/1.0/projects` shouldn't generate URLs that contain `?project=default` as that's just noise
 - `/1.0/storage-pools` doesn't generate project-aware URLs

**Comment by turtle0x1** [comment]
> exist in the images directory as tarballs 

I had a couple of failed migrations & tarball restores so these images may have come from that, which I guess makes some sense they dont appear in the storage pool (I mean what happens if you get a lot of these images ? Surely the eat up storage somewhere)

>Do you have any instances in that project ?

Nope - so I guess the output right

> /1.0/projects shouldn't generate URLs that contain ?project=default as that's just noise

IMO this is wrong because they should be consistent - I shouldn't get `?project` 90% of the time and program special cases for the rest (theoretically I suppose if your using `/1.0/projects?recursion=2` you can always "calculate" the project you don't need any `?project` strings and if your using `/1.0/project/X` then you also obviously know the project - so all project strings should be dropped from `/1.0/projects` entirely (which would be inconsistent) or keep the `?project=default` string)

I.E you have to do things like this

```
used_by_entity = "container"

if(string_contains(used_by_entity, "?project="){
        project = extractProject(used_by_entity);
}else{
       project = "default"
}
``` 

> /1.0/storage-pools doesn't generate project-aware URLs
IMO all `used_by` should generate project aware URL's (only because I assume the long term plan is  to support all entity's existing as children of projects)

**Comment by stgraber** [comment]
No, the URL logic should be that for anything that's part of the default project (and so doesn't require ?project=default), the URLs should NOT include it, otherwise older API clients that aren't project-aware may break when parsing.

For anything that's NOT in the default project, all URLs to that need to include the ?project=NAME so that the URL is valid, for those a project-aware client is obviously needed.

**Comment by turtle0x1** [comment]
TBH dunno why im arguing, sorry! 

Project info on storage resolves my issue!

**Comment by stgraber** [comment]
For consistency, lets check them all:

- [x] /1.0/profiles/PROFILE
- [x] /1.0/networks/NETWORK
- [ ] /1.0/projects/PROJECT
- [ ] /1.0/storage-pools/POOL
- [ ] /1.0/storage-pools/POOL/volumes/VOLUME

**Comment by stgraber** [comment]
I've got a fix for the generated DB bits that handle profiles & projects, that actually lets us remove a bit of hardcoded logic.
Storage is however full of hardcoded logic so we need to update:
 - storagePoolUsedByGet
 - storagePoolVolumeUsedByGet

So that they return something which makes sense.

**Comment by stgraber** [comment]
I think I have /1.0/storage-pools/POOL pretty much sorted though I'll rebase a bunch of that code when I complete the /volumes work.

One thing that also got overlooked is that custom volumes and images availability vary based on server in a cluster.

For images, that's not a huge deal as removing the image will get rid of it everywhere, so my current fix to report all projects that an image is a part of will do the trick just fine. But for custom storage volumes, you can have volumes with different content on different nodes sharing the same name, so those should show up with a ?target=NAME in the URL.

**Comment by stgraber** [comment]
Ok, so just writing down some thoughts so I remember later :)

For /1.0/storage-pools/NAME, we want:
 - Any profile which stores its instances on the pool (with ?project= if non-default)
 - Any instance currently stored on the pool (with ?project= if non-default)
 - Any image currently stored on the pool and for any project it's a part of (with ?project= if non-default)
 - Any custom volume stored on the pool and for any target it exists on (with ?project= if non-default and always ?target= if on cluster)
 - If the pool contains volumes that are used to back either images or backups for the whole daemon, add a ref to /1.0

For /1.0/storage-pools/NAME/volumes/TYPE/VOL, we want:
 - image:
  - Link back to the image
 - instance
  - Link back to the instance
 - custom volumes:
  - /1.0 if the volume is used to store either backups or images for the whole daemon
  - Any profile which attaches the volume (with ?project= if non-default)
  - Any instance currently attached to the volume (with ?project= if non-default)

**Comment by stgraber** [comment]
My local branch currently is missing the ?target= bits for custom volumes and the /1.0 ref for backups/images storage in the storage-pool case.

I'm yet to do the needed work around storage-volume.

Once all the above is done, we should be able to completely rely on this UsedBy data to decide whether a pool is removable or not, letting us deprecate more code.

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/pull/7546 should take care of everything for storage pools.

**Comment by turtle0x1** [comment]
Should `?target` apply in the `used_by` section of the `/1.0/profiles` as well (its come up in the context of clusters, otherwise you have to go an hit `/1.0/containers/` to find the host its actually on)

**Comment by stgraber** [comment]
We should only have ?target= in the URL when it's actually required to disambiguate between two different objects with the same name on different machines. This is only a problem for custom volumes so I've only added it there.

?target= is expensive as that tells whatever LXD server answers your request to stop what it's doing and perform an internal request to the server you've indicated. So we only want to have to do this when strictly required. For most objects even if they're stored on another server, no direct communication is needed as the data required is present in the database.
