### ISSUE TITLE
Add support for dxgkrnl on WSL 2

### ISSUE THREAD

**Issue by sirredbeard** [lxc/lxd#7545]
This is a wishlist request to support GPU compute on WSL 2, in particular CUDA.

Basically I would like support for this https://stgraber.org/2017/03/21/cuda-in-lxd/ with CUDA on WSL 2 with the systemd workarounds to get LXD running https://blog.simos.info/how-to-run-lxd-containers-in-wsl2/ and https://wsl.dev/wsl2-lxd-funtoo/.

I am particularly interested in combining GPU support with the new VM and SPICE features coming in LXD.

CUDA on WSL 2 doesn't use Nvidia drivers on Linux, tools need to detect dxgkrnl for pass-through GPU https://devblogs.nvidia.com/announcing-cuda-on-windows-subsystem-for-linux-2/.

More info on dxgkrnl https://devblogs.microsoft.com/directx/directx-heart-linux/ and https://lore.kernel.org/lkml/CAPM=9tx4wh-Lk6Dffsdh-7mYvXx+GX2AxhrGqFgyN8-AWJvP6A@mail.gmail.com/T/

What can I do to help?

**Comment by stgraber** [comment]
LXD doesn't really do much there. You need to have the GPU show up in /sys/class/drm, if it does, things should just work already. If not, then you need a better kernel :)

For the rest of the story about passing through the libraries and the rest, that's all done through nvidia-container, so if something's broken there, then you'd need to file a bug against that project. Though the logic should be pretty similar in nvidia-docker, so assuming this works, there's a good chance that it would work here too.

**Comment by stgraber** [comment]
lxc query /1.0/resources

And 'find /dev' would be useful

**Comment by stgraber** [comment]
Looking at the kernel doc, this isn't a true GPU so won't work with our normal GPU support or with the Nvidia integration bits nor can it really be made to work with any if it as there is no hardware data showing up.

**Comment by stgraber** [comment]
lxc config device add NAME dxg  unix-char path=/dev/dxg

This should work fine assuming the kernel doc is correct.

**Comment by stgraber** [comment]
Closing as there doesn't appear to be an actual issue for us to fix.

If this does work with /dev/dxg, a tutorial for it would be great to see though. Feel free to post any such content on our forum at https://discuss.linuxcontainers.org

**Comment by sirredbeard** [comment]
Thank you for looking into this.

I am going to do more research.

Here are the log files previously requested.
[find_dev.txt](https://github.com/lxc/lxd/files/4802356/find_dev.txt)
[lxd_query_resources.txt](https://github.com/lxc/lxd/files/4802357/lxd_query_resources.txt)

**Comment by stgraber** [comment]
Interesting, so unix-char for /dev/dxg should definitely work fine for what you're trying to do.
What's interesting is that there's also some kind of GPU visible on the PCI bus though without any usable DRI/DRM entries associated with it and it doesn't appear that /dev/dxg is clearly tied to it either otherwise we could do some more magic in the `gpu` device type to make it work without unix-char.
