### ISSUE TITLE
Not Found fedora and centos image metadata

### ISSUE THREAD

**Issue by hidaruma** [lxc/lxd#755]
In https://images.linuxcontainers.org/meta/1.0/ , valid image metadata about fedora and centos are not found. But in image dir, there are the images.

```
% lxd-images import lxc fedora 20 amd64 --alias fedora20   
Downloading the GPG key for https://images.linuxcontainers.org
Downloading the image list for https://images.linuxcontainers.org
Validating the GPG signature of /tmp/tmprhakngwf/index.json.asc
Requested image doesn't exist.

```

**Comment by stgraber** [comment]
fedora isn't supported in unprivileged containers at this time.

The images are only present in the system index which isn't what lxd-images uses as it's running unprivileged containers and so uses the user index.
