### ISSUE TITLE
Ability to retrieve instances for all projects through API

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#7559]
Recursion 2 is cool, what about a `?recursion=3` that returns all whatever entities grouped by projects ?

**Comment by stgraber** [comment]
It's certainly possible though this would also be extremely slow in large deployments I would expect.

**Comment by tbobo** [comment]
Hi! I would like to work on this issue along with some colleagues (@ej-castillo and @dramos20) as a part of a course on Virtualization at The University of Texas at Austin. Would it be alright if we were assigned this? Thanks in advance.

**Comment by stgraber** [comment]
Done! Similar to the other one, I can only assign people who have commented in an issue so will assign the other two when they comment.

**Comment by dramos20** [comment]
Hi, I will be working on this with @tbobo . Can I be assigned to this? Thank you!

**Comment by stgraber** [comment]
Done!

**Comment by ej-castillo** [comment]
Commenting to be assigned to issue.

**Comment by stgraber** [comment]
@ej-castillo @dramos20 @tbobo Do you still intend to work on this or should we un-assign so someone else can have a go at it?

**Comment by tbobo** [comment]
Sorry about the delay, we intend to follow up on this soon.

**Comment by stgraber** [comment]
@tbobo hey there, are you still looking at implementing this?

**Comment by tbobo** [comment]
Many apologies. Personal circumstances have kept me away and occupied. I'll implement this as soon as possible and open a PR in the coming weeks, if that's okay.

**Comment by stgraber** [comment]
Un-assigning for inactivity and so others can take a stab at it.

**Comment by presztak** [comment]
@stgraber, if you didn't mind i would like to take a look at this one.

**Comment by stgraber** [comment]
Sure!

**Comment by pmarini-nc** [comment]
Will this feature allow to list all the containers in all the projects with a `lxc ls`, thus returning the project in an additional column?
Thanks in advance!

**Comment by stgraber** [comment]
Yes, it will.

**Comment by turtle0x1** [comment]
Is it going to group or leave it as flat array? I.E

```
// As a group
[default] => [
   [
      "name"=>"c1",
   ] 
]
// Or as a flat
[
  [ 
     "name"=>"c1",
     "project"=>"default"
  ]
]
```

**Comment by stgraber** [comment]
I expect it will be a map as that wouldn't require changes to the API struct of an instance
