### ISSUE TITLE
Update all LXD images on images.linuxcontainers.org to use templates

### ISSUE THREAD

**Issue by LenzGr** [lxc/lxd#756]
When launching a container based on the CentOS 6 image available from images.linuxcontainers.org, the container's name does not resolve via the local dnsmasq service:

```
% lxd-images import lxc centos 6 amd64 --alias centos6
Downloading the GPG key for https://images.linuxcontainers.org
Downloading the image list for https://images.linuxcontainers.org
Validating the GPG signature of /tmp/tmpsdubx7ai/index.json.asc
Downloading the image: https://images.linuxcontainers.org/images/centos/6/amd64/default/20150604_02:16/lxd.tar.xz
Validating the GPG signature of /tmp/tmpsdubx7ai/centos-6-amd64-default-20150604_02:16.tar.xz.asc
Image imported as: cf90adbf650b89c0530402546fda9a0f465e6719802abafba4c126e4f1a99fdf
Setup alias: centos6
Creating container...done
Starting container...done
% lxc list noname
+--------+---------+------------+------+-----------+-----------+
|  NAME  |  STATE  |    IPV4    | IPV6 | EPHEMERAL | SNAPSHOTS |
+--------+---------+------------+------+-----------+-----------+
| noname | RUNNING | 10.0.3.236 |      | NO        | 0         |
+--------+---------+------------+------+-----------+-----------+
% dig noname @10.0.3.1

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> noname @10.0.3.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 11403
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;noname.				IN	A

;; Query time: 0 msec
;; SERVER: 10.0.3.1#53(10.0.3.1)
;; WHEN: Thu Jun 11 16:34:18 CEST 2015
;; MSG SIZE  rcvd: 24
```
There actually is an entry in the dhcp.leases file, but it shows the incorrect host name:

```
% grep 10.0.3.236 /var/lib/misc/dnsmasq.lxcbr0.leases
1434036769 00:16:3e:d5:2b:50 10.0.3.236 LXC_NAME *
```

This is likely due to `DHCP_HOSTNAME` being set to `LXC_NAME` in `/etc/sysconfig/network-scripts/ifcfg-eth0`:

```
% lxc exec noname /bin/bash                          
[root@noname ~]# grep LXC_NAME /etc/sysconfig/network-scripts/ifcfg-eth0 
DHCP_HOSTNAME=LXC_NAME
```

Setting `DHCP_HOSTNAME` to `noname` here and restarting the network fixes the issue and the local DNS server returns the correct IP address. However, this is cumbersome and requires some post-processing of an image when creating a container.

This problem does not exist in Ubuntu containers, because they set `send host-name = gethostname();` in `/etc/dhcp/dhclient.conf`.

While researching this issue I stumbled over [this thread](http://centos.1050465.n5.nabble.com/CentOS-DHCP-HOSTNAME-in-ifcfg-eth0-td5032421.html), which recommends to set `DHCP_HOSTNAME` as follows:

```
DHCP_HOSTNAME=`hostname`
```

I can confirm that this resolves the problem in my case. It might make sense to update the CentOS 6 image accordingly. Not sure if this applies to CentOS 7, too.

**Comment by stgraber** [comment]
currently container hostname is set to LXC_NAME for all containers, that's a known issue and something we couldn't resolve until a couple of days ago when we landed templating support.

**Comment by stgraber** [comment]
As for changing the value in the config file, I'm not opposed to it, but that'd have to be done in the lxc-fedora, lxc-centos and lxc-oracle templates in LXC. A pull request against lxc git would be appreciated.

**Comment by LenzGr** [comment]
OK, I'll take a look at this, even though I'm not sure how to properly test this locally. By the way, the host name defined in `HOSTNAME` in `/etc/sysconfig/network` is empty, not sure if that's intended?

**Comment by LenzGr** [comment]
OK, I created https://github.com/lxc/lxc/pull/568 - let me know what you think. Thanks!

**Comment by LenzGr** [comment]
Next try - I hope this one looks better. Thanks!

**Comment by stgraber** [comment]
Re-opening since we still need to update the public images to properly template config files.

**Comment by stgraber** [comment]
script updated so that new images contain templates.

**Comment by stgraber** [comment]
Script updated
