### ISSUE TITLE
Headers sent when `lxc image import` on URL seems wrong.

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#7563]
* Distribution: Ubuntu
 * Distribution version: 20.04
 * Kernel version: 5.4.0-33-generic
 * LXC version: 4.2
 * LXD version: 4.2
 * Storage backend in use: DIR

I am checking headers with (using putsreq.com):

```
lxc -v --debug image import https://putsreq.com/RANDOM_HASH --alias myproject
```

And getting this headers:
```
{
  "VERSION": "HTTP/1.1",
  "CONNECTION": "close",
  "ACCEPT-ENCODING": "gzip",
  "USER-AGENT": "LXD 4.2 (Linux; x86_64; 5.4.0; Ubuntu; 20.04) (dir 1)",
  "LXD-SERVER-ARCHITECTURES": "2, 1",
  "LXD-SERVER-VERSION": "4.2",
  "CDN-LOOP": "cloudflare"
}
```

Should  `LXD-SERVER-ARCHITECTURES` header be equal to `x86_64, i686` and not `2, 1` ?

How exactly I can know from this information what exact `arch` image server supposed to give back for a specified URL?

I mean, how can I know for a fact that request was for `i686` and not for `x86_64`?

**Comment by stgraber** [comment]
Ah yeah, that looks like a bug, we should definitely be passing the names instead of the integer values.

**Comment by stgraber** [comment]
Sent a fix for the naming issue.

As for what architecture you should actually serve, architectures in LXD are sorted starting with the native architecture, so in this case, you'd want to prefer x86_64.
