### ISSUE TITLE
Disabling ad-hoc LXC clustering

### ISSUE THREAD

**Issue by gbrener** [lxc/lxd#7566]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails: N/A
   * Kernel version: N/A
   * LXC version: 3.0.3
   * LXD version: 3.0.3 
   * Storage backend in use: N/A

# Issue description

LXD installed via `apt`, was initialized without clustering enabled, and my goal was to enable clustering in an ad-hoc manner. The existing value for `core.https_address` was empty, so I followed some lines in the documentation and main README, typing `lxc config set core.https_address <ip-address>`. Following that, I typed `lxc cluster enable`, but this failed with:
```
Error: Failed to configure cluster: failed to re-initialize gRPC SQL gateway: Failed to create raft factory: invalid node address: address <ip-address>: missing port in address
```

I attempted to use the CLI to fix the config and add a port, but each command I typed would hang. The LXD log showed:
```
t=2020-06-21T08:01:16-0500 lvl=info msg="Updating images"
t=2020-06-21T08:01:16-0500 lvl=info msg="Done updating images"
t=2020-06-21T13:42:06-0500 lvl=info msg="Update network address"
t=2020-06-21T13:42:06-0500 lvl=info msg=" - binding TCP socket" socket=<ip-address>:8443
t=2020-06-21T13:42:15-0500 lvl=eror msg="Dqlite: aborting (fd=20 state=header msg=(null))"
```

I began following the troubleshooting steps to revert the configuration back and disable clustering. I attempted to fix the database values for `config` and `raft_nodes` rows, typing `systemctl stop lxd lxd.socket`, then edited `patch.local.sql` and `patch.global.sql` files in the appropriate locations (so the relevant rows had empty values in both `nodes` and `raft_nodes` tables), then `systemctl start lxd`... To no avail. The CLI commands still hanged, and although the error messages would change with each attempt, I did not capture logs at the time. I also tried to add port number (8443, as the docs showed) into the `value` column of the local and global `config` table. This got LXD to attempt to do leader election, but it ended up failing because nothing was listening on HTTPS port 443.

Is there a recommended way to disable LXC clustering? Perhaps there is something additional I can try.

# Steps to reproduce

 1. Install LXD without clustering enabled
 2. `lxc config set core.https_address <ip-address>` # No port
 3. `lxc cluster enable`

**Comment by stgraber** [comment]
Let me make sure we haven't fixed that already in more recent versions of LXD.

**Comment by stgraber** [comment]
Yes, this has already been fixed.

```
root@c1:~# lxc cluster enable c1
Error: Failed to configure cluster: no cluster.https_address config is set on this node
root@c1:~# lxc config set core.https_address 127.0.0.1
root@c1:~# lxc cluster enable c1
Error: Failed to configure cluster: Copy core.https_address to cluster.https_address: cannot set 'cluster.https_address' to '127.0.0.1': Address not in form of <HOST>:<PORT>: address 127.0.0.1: missing port in address
root@c1:~# lxc list
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
root@c1:~# lxc config set core.https_address 127.0.0.1:8443
root@c1:~# lxc list
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
root@c1:~# lxc cluster enable c1
Clustering enabled
root@c1:~# lxc list
+------+-------+------+------+------+-----------+----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS | LOCATION |
+------+-------+------+------+------+-----------+----------+
root@c1:~# lxc cluster list
+------+------------------------+----------+--------+-------------------+--------------+
| NAME |          URL           | DATABASE | STATE  |      MESSAGE      | ARCHITECTURE |
+------+------------------------+----------+--------+-------------------+--------------+
| c1   | https://127.0.0.1:8443 | YES      | ONLINE | fully operational | x86_64       |
+------+------------------------+----------+--------+-------------------+--------------+
root@c1:~# 
```

**Comment by gbrener** [comment]
Thanks for looking into it.
