### ISSUE TITLE
publish image require space on /tmp

### ISSUE THREAD

**Issue by vot4anto** [lxc/lxd#7577]
follow operation of publish a new image on local installation:

lxc -v --debug publish win2016std  --alias windows2016
DBUG[06-23|08:36:36] Connecting to a local LXD over a Unix socket 
DBUG[06-23|08:36:36] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
DBUG[06-23|08:36:36] Got response struct from LXD 
DBUG[06-23|08:36:36] 
	{
		"config": {},
		"api_extensions": [
			"storage_zfs_remove_snapshots",
			"container_host_shutdown_timeout",
			"container_stop_priority",
			"container_syscall_filtering",
			"auth_pki",
			"container_last_used_at",
			"etag",
			"patch",
			"usb_devices",
			"https_allowed_credentials",
			"image_compression_algorithm",
			"directory_manipulation",
			"container_cpu_time",
			"storage_zfs_use_refquota",
			"storage_lvm_mount_options",
			"network",
			"profile_usedby",
			"container_push",
			"container_exec_recording",
			"certificate_update",
			"container_exec_signal_handling",
			"gpu_devices",
			"container_image_properties",
			"migration_progress",
			"id_map",
			"network_firewall_filtering",
			"network_routes",
			"storage",
			"file_delete",
			"file_append",
			"network_dhcp_expiry",
			"storage_lvm_vg_rename",
			"storage_lvm_thinpool_rename",
			"network_vlan",
			"image_create_aliases",
			"container_stateless_copy",
			"container_only_migration",
			"storage_zfs_clone_copy",
			"unix_device_rename",
			"storage_lvm_use_thinpool",
			"storage_rsync_bwlimit",
			"network_vxlan_interface",
			"storage_btrfs_mount_options",
			"entity_description",
			"image_force_refresh",
			"storage_lvm_lv_resizing",
			"id_map_base",
			"file_symlinks",
			"container_push_target",
			"network_vlan_physical",
			"storage_images_delete",
			"container_edit_metadata",
			"container_snapshot_stateful_migration",
			"storage_driver_ceph",
			"storage_ceph_user_name",
			"resource_limits",
			"storage_volatile_initial_source",
			"storage_ceph_force_osd_reuse",
			"storage_block_filesystem_btrfs",
			"resources",
			"kernel_limits",
			"storage_api_volume_rename",
			"macaroon_authentication",
			"network_sriov",
			"console",
			"restrict_devlxd",
			"migration_pre_copy",
			"infiniband",
			"maas_network",
			"devlxd_events",
			"proxy",
			"network_dhcp_gateway",
			"file_get_symlink",
			"network_leases",
			"unix_device_hotplug",
			"storage_api_local_volume_handling",
			"operation_description",
			"clustering",
			"event_lifecycle",
			"storage_api_remote_volume_handling",
			"nvidia_runtime",
			"container_mount_propagation",
			"container_backup",
			"devlxd_images",
			"container_local_cross_pool_handling",
			"proxy_unix",
			"proxy_udp",
			"clustering_join",
			"proxy_tcp_udp_multi_port_handling",
			"network_state",
			"proxy_unix_dac_properties",
			"container_protection_delete",
			"unix_priv_drop",
			"pprof_http",
			"proxy_haproxy_protocol",
			"network_hwaddr",
			"proxy_nat",
			"network_nat_order",
			"container_full",
			"candid_authentication",
			"backup_compression",
			"candid_config",
			"nvidia_runtime_config",
			"storage_api_volume_snapshots",
			"storage_unmapped",
			"projects",
			"candid_config_key",
			"network_vxlan_ttl",
			"container_incremental_copy",
			"usb_optional_vendorid",
			"snapshot_scheduling",
			"container_copy_project",
			"clustering_server_address",
			"clustering_image_replication",
			"container_protection_shift",
			"snapshot_expiry",
			"container_backup_override_pool",
			"snapshot_expiry_creation",
			"network_leases_location",
			"resources_cpu_socket",
			"resources_gpu",
			"resources_numa",
			"kernel_features",
			"id_map_current",
			"event_location",
			"storage_api_remote_volume_snapshots",
			"network_nat_address",
			"container_nic_routes",
			"rbac",
			"cluster_internal_copy",
			"seccomp_notify",
			"lxc_features",
			"container_nic_ipvlan",
			"network_vlan_sriov",
			"storage_cephfs",
			"container_nic_ipfilter",
			"resources_v2",
			"container_exec_user_group_cwd",
			"container_syscall_intercept",
			"container_disk_shift",
			"storage_shifted",
			"resources_infiniband",
			"daemon_storage",
			"instances",
			"image_types",
			"resources_disk_sata",
			"clustering_roles",
			"images_expiry",
			"resources_network_firmware",
			"backup_compression_algorithm",
			"ceph_data_pool_name",
			"container_syscall_intercept_mount",
			"compression_squashfs",
			"container_raw_mount",
			"container_nic_routed",
			"container_syscall_intercept_mount_fuse",
			"container_disk_ceph",
			"virtual-machines",
			"image_profiles",
			"clustering_architecture",
			"resources_disk_id",
			"storage_lvm_stripes",
			"vm_boot_priority",
			"unix_hotplug_devices",
			"api_filtering",
			"instance_nic_network",
			"clustering_sizing",
			"firewall_driver",
			"projects_limits",
			"container_syscall_intercept_hugetlbfs",
			"limits_hugepages",
			"container_nic_routed_gateway",
			"projects_restrictions",
			"custom_volume_snapshot_expiry",
			"volume_snapshot_scheduling",
			"trust_ca_certificates",
			"snapshot_disk_usage",
			"clustering_edit_roles",
			"container_nic_routed_host_address",
			"container_nic_ipvlan_gateway",
			"resources_usb_pci",
			"resources_cpu_threads_numa",
			"resources_cpu_core_die",
			"api_os",
			"resources_system",
			"usedby_consistency"
		],
		"api_status": "stable",
		"api_version": "1.0",
		"auth": "trusted",
		"public": false,
		"auth_methods": [
			"tls"
		],
		"environment": {
			"addresses": [],
			"architectures": [
				"x86_64",
				"i686"
			],
			"certificate": "-----BEGIN CERTIFICATE-----\nMIICCDCCAY2gAwIBAgIRAI2KjCQAFXKr7ppzo/SfZCowCgYIKoZIzj0EAwMwNTEc\nMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEVMBMGA1UEAwwMcm9vdEBjaGFy\nbGVzMB4XDTIwMDYyMjIwNDQxMloXDTMwMDYyMDIwNDQxMlowNTEcMBoGA1UEChMT\nbGludXhjb250YWluZXJzLm9yZzEVMBMGA1UEAwwMcm9vdEBjaGFybGVzMHYwEAYH\nKoZIzj0CAQYFK4EEACIDYgAErGzUrOGXIyb+rzdGiHP7blGAMOQqDhXeGM7TN9B1\nidUdznAFiAIvH/KlDvBGxfeKMUAQkLkf7YfxdcIeFoJAK2sJ8BQtFy0kT3J02w/k\ncwycsGDQu051Z6+94supTUFoo2EwXzAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAww\nCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAqBgNVHREEIzAhggdjaGFybGVzhwR/\nAAABhxAAAAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMDA2kAMGYCMQDrjZgUTJFJ\nlNHIqDgoUdqXwMjW0MAYzChDJsqP4TO5shZq/cDoFGQ1c2mphyKtoZwCMQDpV0OT\nqKF7o3HMbWx8gBU0wRXEgKnpQMENGOecudPn3VPR1d+3q43rr8GQkUpfIgw=\n-----END CERTIFICATE-----\n",
			"certificate_fingerprint": "e092a817f3102097b1027e4eb009134daeb9e8a6e3f0f99b056a9b4b35561740",
			"driver": "lxc",
			"driver_version": "4.0.2",
			"firewall": "xtables",
			"kernel": "Linux",
			"kernel_architecture": "x86_64",
			"kernel_features": {
				"netnsid_getifaddrs": "false",
				"seccomp_listener": "false",
				"seccomp_listener_continue": "false",
				"shiftfs": "false",
				"uevent_injection": "false",
				"unpriv_fscaps": "true"
			},
			"kernel_version": "4.15.0-106-generic",
			"lxc_features": {
				"cgroup2": "true",
				"mount_injection_file": "true",
				"network_gateway_device_route": "true",
				"network_ipvlan": "true",
				"network_l2proxy": "true",
				"network_phys_macvlan_mtu": "true",
				"network_veth_router": "true",
				"pidfd": "true",
				"seccomp_notify": "true"
			},
			"os_name": "Ubuntu",
			"os_version": "18.04",
			"project": "default",
			"server": "lxd",
			"server_clustered": false,
			"server_name": "charles",
			"server_pid": 7455,
			"server_version": "4.0.1",
			"storage": "lvm",
			"storage_version": "2.02.176(2) (2017-11-03) / 1.02.145 (2017-11-03) / 4.37.0"
		}
	} 
DBUG[06-23|08:36:36] Sending request to LXD                   method=GET url=http://unix.socket/1.0/instances/win2016std etag=
DBUG[06-23|08:36:36] Got response struct from LXD 
DBUG[06-23|08:36:36] 
	{
		"architecture": "x86_64",
		"config": {
			"limits.cpu": "4",
			"limits.memory": "8GB",
			"raw.qemu": "-device virtio-vga -vnc :1 -drive file=/var/tmp/virtio.iso,index=0,media=cdrom,if=ide -drive file=/var/tmp/win2016.iso,index=1,media=cdrom,if=ide ",
			"security.secureboot": "false",
			"volatile.eth0.hwaddr": "00:16:3e:d3:5a:6b",
			"volatile.last_state.power": "STOPPED",
			"volatile.vm.uuid": "43e972f0-ff6c-4b13-a5e8-018af753539f"
		},
		"devices": {
			"root": {
				"path": "/",
				"pool": "default",
				"size": "80GB",
				"type": "disk"
			}
		},
		"ephemeral": false,
		"profiles": [
			"default"
		],
		"stateful": false,
		"description": "",
		"created_at": "2020-06-22T08:39:40.955609063Z",
		"expanded_config": {
			"limits.cpu": "4",
			"limits.memory": "8GB",
			"raw.qemu": "-device virtio-vga -vnc :1 -drive file=/var/tmp/virtio.iso,index=0,media=cdrom,if=ide -drive file=/var/tmp/win2016.iso,index=1,media=cdrom,if=ide ",
			"security.secureboot": "false",
			"volatile.eth0.hwaddr": "00:16:3e:d3:5a:6b",
			"volatile.last_state.power": "STOPPED",
			"volatile.vm.uuid": "43e972f0-ff6c-4b13-a5e8-018af753539f"
		},
		"expanded_devices": {
			"eth0": {
				"name": "eth0",
				"nictype": "bridged",
				"parent": "br0",
				"type": "nic"
			},
			"root": {
				"path": "/",
				"pool": "default",
				"size": "80GB",
				"type": "disk"
			}
		},
		"name": "win2016std",
		"status": "Stopped",
		"status_code": 102,
		"last_used_at": "2020-06-23T08:35:13.23144908Z",
		"location": "none",
		"type": "virtual-machine"
	} 
DBUG[06-23|08:36:36] Connected to the websocket: ws://unix.socket/1.0/events 
DBUG[06-23|08:36:36] Sending request to LXD                   method=POST url=http://unix.socket/1.0/images etag=
DBUG[06-23|08:36:36] 
	{
		"auto_update": false,
		"properties": null,
		"public": false,
		"expires_at": "0001-01-01T00:00:00Z",
		"profiles": null,
		"filename": "",
		"source": {
			"alias": "",
			"certificate": "",
			"protocol": "",
			"server": "",
			"image_type": "",
			"mode": "",
			"type": "instance",
			"url": "",
			"name": "win2016std",
			"fingerprint": "",
			"secret": ""
		},
		"compression_algorithm": "",
		"aliases": null
	} 
DBUG[06-23|08:36:36] Got operation from LXD 
DBUG[06-23|08:36:36] 
	{
		"id": "df7a0668-b593-4912-8f85-46e4c7cb51e6",
		"class": "task",
		"description": "Downloading image",
		"created_at": "2020-06-23T08:36:36.642271294Z",
		"updated_at": "2020-06-23T08:36:36.642271294Z",
		"status": "Running",
		"status_code": 103,
		"resources": null,
		"metadata": null,
		"may_cancel": false,
		"err": "",
		"location": "none"
	} 
DBUG[06-23|08:36:36] Sending request to LXD                   method=GET url=http://unix.socket/1.0/operations/df7a0668-b593-4912-8f85-46e4c7cb51e6 etag=
DBUG[06-23|08:36:36] Got response struct from LXD 
DBUG[06-23|08:36:36] 
	{
		"id": "df7a0668-b593-4912-8f85-46e4c7cb51e6",
		"class": "task",
		"description": "Downloading image",
		"created_at": "2020-06-23T08:36:36.642271294Z",
		"updated_at": "2020-06-23T08:36:36.642271294Z",
		"status": "Running",
		"status_code": 103,
		"resources": null,
		"metadata": null,
		"may_cancel": false,
		"err": "",
		"location": "none"
	} 
DBUG[06-23|08:58:56] Sending request to LXD                   method=GET url="http://unix.socket/1.0/images/aliases?recursion=1" etag=
DBUG[06-23|08:58:56] Got response struct from LXD 
DBUG[06-23|08:58:56] 
	[] 
DBUG[06-23|08:58:56] Sending request to LXD                   method=POST url=http://unix.socket/1.0/images/aliases etag=
DBUG[06-23|08:58:56] 
	{
		"description": "",
		"target": "c211633b09bba1232368b0f7827b4e1d52d108399ecdb1b66c079c4caba63d12",
		"name": "windows2016",
		"type": ""
	} 
Instance published with fingerprint: c211633b09bba1232368b0f7827b4e1d52d108399ecdb1b66c079c4caba63d12
# lxc image list
+-------------+--------------+--------+-------------+--------------+-----------------+-----------+------------------------------+
|    ALIAS    | FINGERPRINT  | PUBLIC | DESCRIPTION | ARCHITECTURE |      TYPE       |   SIZE    |         UPLOAD DATE          |
+-------------+--------------+--------+-------------+--------------+-----------------+-----------+------------------------------+
| windows2016 | c211633b09bb | no     |             | x86_64       | VIRTUAL-MACHINE | 4736.56MB | Jun 23, 2020 at 8:58am (UTC) |
+-------------+--------------+--------+-------------+--------------+-----------------+-----------+------------------------------+

required the same space on /tmp, as you can see from the follow listing during the operation:
/tmp/snap.lxd/tmp/lxd_export_716836975# ls -lrt
total 4853132
-rw-r--r-- 1 root root 4990168440 Jun 23 08:52 rootfs.img

at the end of operation the space is not more used:
:/tmp/snap.lxd/tmp# ls -lrt
total 0

: # snap list
Name    Version   Rev    Tracking       Publisher   Notes
core    16-2.45   9289   latest/stable  canonical✓  core
core18  20200427  1754   latest/stable  canonical✓  base
lxd     4.0.1     15682  4.0/stable     canonical✓  -
snapd   2.45.1    8140   latest/stable  canonical✓  snapd

**Comment by stgraber** [comment]
I think I have a suitable grep pattern that found all cases where we don't specify a path for temp files/dirs, I'll get all of those that make sense updated to use one of `backups` or `images`.
