### ISSUE TITLE
Failed to create storage pool - bad file descriptor

### ISSUE THREAD

**Issue by DobleV55** [lxc/lxd#7586]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
  lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFXDCCA0SgAwIBAgIRAM4M9rvm4a1tzgH1J3/ViIkwDQYJKoZIhvcNAQELBQAw
    PTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEdMBsGA1UEAwwUcm9vdEBE
    RVNLVE9QLUVOTE1WTEUwHhcNMjAwNjI2MDEwNDIzWhcNMzAwNjI0MDEwNDIzWjA9
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMR0wGwYDVQQDDBRyb290QERF
    U0tUT1AtRU5MTVZMRTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALV7
    CvHrvercbjXid0voWG1dLgBVjqp/H2HTFcjyXevSrfpGKbRMgnTuY2D67g3Q2nKb
    DCfcm9VCU+zkOgxRoUfrP94pkaZyFGcmJBbAWhgus9KBRaYnZcOSxvynu+fpVAkL
    cplIRucvSRfFzomSOxu9J459fcGXsdu8Vl09vSDHS0ZBKF7AoQ/nHv7r6tQeeuGm
    VwJ0ggipqVA2DmMwHpfPg1SsdU/noI06WWbFQIE/EVhE5B5tNNrOJ7Qm+5YJtH/m
    1yYz5k3qT5J5gy51ZHHgzcEGtxf7g03L8zi8cwYEL8RtxZArTLNVyLoDQJjE2gKb
    RngtGrPg0r7LKR8siSSgD3EGCHl0mdWccvK711Oqb3hzxw9S/9vKvOGfAmeW/TFe
    oxB1Y0wjMCncjMAJTX2YYJ/tWKIQrwbNme8GhICHSVDNz0B3NqN3oeDcprPn90jl
    BQNUotJnamPv9z7vKYTofsYXyuXeiHa7fazMOJxtrTijNY3maCYFVrtpzY92yKNR
    34eOVR96wGU5xC4XGYrvGulNWft68Euxk+9TZdHYbeBhnEEhKJeOp3wssvk/v8iY
    TvZwzUeZxbN33umzl9+2CrBi3ao7SrPIAC1hZyEUIReymVxI857MVthu3QTYQ3xX
    6eSWNKai4cXSJWekdq9DvVR7VShoIvxeX15Cs/N9AgMBAAGjVzBVMA4GA1UdDwEB
    /wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMCAGA1Ud
    EQQZMBeCD0RFU0tUT1AtRU5MTVZMRYcEwKgAbTANBgkqhkiG9w0BAQsFAAOCAgEA
    I8KZiuKJvrnOw+87150QDtEgEEph/NFbXWzXHzq8RtDn3xsLJ7fsVfa2VJ66yZlk
    RP8HMNF2sWxV98lFbeYpxEWDzF+Y3ov1l7bCKAZRYQ+SMck8bmxqug8t+4w7THG2
    1cBldru2Ouq4TTHcWYKseRlQ709JA5AEMqBCAlT3IT/GwHY14e5W44OO0yxWo6xU
    Ng/lXOd7hInNTli27Awv8FBJK2cjEJukLe2TcoVUXdTQHRhDHzhauWYf9PS2/3tP
    qAommfIDPm7klFbrVs5RXRaLFBRU1kc64dqhmm4LTewuineNR3gREyFuSIzXaIH9
    RuYMW0/9HvrjT2wdTMAFMCovGOzpCPKBkzfMiE/CxlishpAWvEgPeMSe0+Q+7vyv
    0aGV8XQpN+J+N8P4nT7IK/g0Sk7dQbWTVy03pRW3mWjUBk6V+QmX4foYsoe7xYjp
    k9Xo8H9PejZhYbA/X16AU201ORm68pQ8xituVwmePDlhV8wkXGbqa5Tojt2okYkI
    f1gc74w2iMeqCmEBYZhqDWfJpp6ORRWwq7GDsL7YD9uICwtm+GYOlDp45P/+9PMW
    E5eKJWLLJzPOxPG4rv+sC8MQ3whz+xiGD6oWLv+NQyaR0Mqa2d7jos6vo02Gz43A
    tAEOpHVt6+wHU/bnyzhBYU23lVQSgroYkQAlLd7PlZU=
    -----END CERTIFICATE-----
  certificate_fingerprint: 257bfade7dae84964d66c340ad2b18cb4c81d3eb61bba45c0f9757461beaf3f6
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-18362-Microsoft
  server: lxd
  server_pid: 1120
  server_version: 3.0.3
  storage: ""
  storage_version: ""
  server_clustered: false
  server_name: DESKTOP-ENLMVLE
  project: ""

# Issue description
[...]
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: 
Error: Failed to create storage pool 'default': Failed to prepare loop device for "/var/lib/lxd/disks/default.img": bad file descriptor

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce
$sudo lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: 
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (btrfs, dir, lvm) [default=btrfs]: 
Create a new BTRFS pool? (yes/no) [default=yes]: 
Would you like to use an existing block device? (yes/no) [default=no]: 
Size in GB of the new loop device (1GB minimum) [default=44GB]: 20
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to create a new local network bridge? (yes/no) [default=yes]: no
Would you like to configure LXD to use an existing bridge or host interface? (yes/no) [default=no]: yes
Name of the existing bridge or host interface: wifi0
Would you like LXD to be available over the network? (yes/no) [default=no]: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes] 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: 

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
LXD cannot work on WSL1.
