### ISSUE TITLE
[Feature Request] Make remote server options more specific

### ISSUE THREAD

**Issue by toby63** [lxc/lxd#7591]
Right now the options regarding the remote servers are rather confusing (especially for new users).
https://linuxcontainers.org/lxd/docs/master/server mentions many options and "mixes" non-remote and remote options, so it is not clearly visible what options apply in which case.

I see two potencial solutions (they should both be applied imo):
1. Add two (or more) more specific configuration keys:
I imagine something like this:
    - `remote-server.activated: true`
Other option: `false`

   - `remote-server.type: tls`   
   Other options:`candid`, `candid-rbac`

2. Clearly seperate the server configuration keys (at least between `regular server options` and `remote server options`) in the documentation and explain their exact meaning and how they can be combined or not.

**Comment by stgraber** [comment]
I'm sorry, I don't understand what you mean.

Everything listed at https://linuxcontainers.org/lxd/docs/master/server are server options, I don't see what you mean by remote and non-remote, they are all settings that are stored by the server in the database.

**Comment by stgraber** [comment]
Configuring the `rbac` keys conflicts with the `candid` keys as one is a superset of the other (you'll get an error if you attempt it), if either `candid` or `rbac` is configured, LXD starts advertising support for the `candid` auth-type.

`tls` is always advertised and supported by LXD.

**Comment by stgraber** [comment]
Adding a section in `server.md` which covers exposing LXD to the network and authentication probably makes sense, without going in depth about what to set the keys too as the values themselves come from candid/RBAC and if you have those services in place you should also know what the values are.

**Comment by toby63** [comment]
> I'm sorry, I don't understand what you mean.
Everything listed at https://linuxcontainers.org/lxd/docs/master/server are server options, I don't see what you mean by remote and non-remote, they are all settings that are stored by the server in the database.

I don't see what is unclear, my request even states examples.
1. Instead of having only potencially confusing configuration keys like `core.https_address` where people don't know what they mean exactly, the situation and functionality could be clarified with general configuration keys for remote server settings, like I mentioned above.

2. It would also be good to seperate the list of configuration keys in the server documentation into two sections.
First section: General Server configuration
Second Section: Remote configuration

Both points would make the situation much clearer.
