### ISSUE TITLE
[Feature request] Provide profile config parameter for hugetlbfs mountpoint

### ISSUE THREAD

**Issue by PikkuJose** [lxc/lxd#7593]
* Distribution: Gentoo
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.6.15-x86_64
   * LXC version: 4.0.2-r2
   * LXD version: 4.0.1
   * Storage backend in use: lvm

Gentoo doesn't populate folder /dev/hugepages for hugetlbfs, instead user
generates any mountpoint and loads it through fstab, for example, /mnt/hugepages.
As devtmpfs is going to be populated on boot, there would be need to find
out if there is udev rules to populate it, or any other userspace tool that
can populate it for you. It will ease quite a lot if it could be just passed in
the profile as a string, and let lxd consume it.

 - [ x ] Container log (`lxc info NAME --show-log`)

$ lxc info --show-log vm-test
Name: vm-test
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/06/27 19:41 UTC
Status: Stopped
Type: virtual-machine
Profiles: vm-1

Log:

qemu-system-x86_64: can't open backing store /dev/hugepages/ for guest RAM: Is a directory
 - [ ] Container configuration (`lxc config show NAME --expanded`)

$ lxc config show vm-test --expanded
architecture: x86_64
config:
  boot.autostart: "0"
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20200626)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20200626"
  image.type: disk1.img
  image.version: "18.04"
  limits.cpu: "4"
  limits.memory: 16GB
  limits.memory.hugepages: "true"
    volatile.base_image: 238450c866b2a735cb6e134b25094897b58565123d8f5d6725f3273dcc468b3a
  volatile.eth0.hwaddr: 00:16:3e:1a:7c:64
  volatile.eth1.hwaddr: 00:16:3e:29:8f:c3
  volatile.eth2.hwaddr: 00:16:3e:54:4b:40
  volatile.last_state.power: STOPPED
  volatile.vm.uuid: e109c7a6-01d0-4775-bd52-aa532013d8ee
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: virbr1
    type: nic
  eth2:
    name: eth2
    nictype: bridged
    parent: virbr2
    type: nic
  root:
    path: /
    pool: LXDPool
    size: 50GB
    type: disk
ephemeral: false
profiles:
- vm-1
stateful: false
description: ""

**Comment by stgraber** [comment]
Added logic to locate a hugetlbfs instance. This will work so long as you either only have a single hugetlbfs instance or have multiple ones with one of those being at /dev/hugepages.

**Comment by PikkuJose** [comment]
Excellent, works out of the box! Thanks Stéphane!
