### ISSUE TITLE
API semantics for /1.0/cluster/members?recursion=1 changed with 4.0.2 and 4.2

### ISSUE THREAD

**Issue by morphis** [lxc/lxd#7602]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 (but doesn't matter)
 * The output of "lxc info" or if that fails:
   * Kernel version: n/a
   * LXC version: see below
   * LXD version: see below
   * Storage backend in use: n/a

# Issue description

API semantics for an unintialized LXD installation for the `/1.0/cluster/members` API endpoint have changed with 4.2 and 4.0.2 so that now an error is returned instead of a success response. This breaks existing API users.

# Steps to reproduce

In a fresh Ubuntu 18.04 LXD container, run the following commands:

```
$ snap install --channel=4.0/stable lxd
lxd (4.0/stable) 4.0.2 from Canonical✓ installed
$ lxd waitready
$ curl --unix-socket /var/snap/lxd/common/lxd/unix.socket s/1.0/cluster/members?recursion=1
{"error":"not found","error_code":404,"type":"error"}
$ snap remove lxd

$ snap install --channel=stable lxd
lxd 4.2 from Canonical✓ installed
$ lxd waitready
$ curl --unix-socket /var/snap/lxd/common/lxd/unix.socket s/1.0/cluster/members?recursion=1
{"error":"not found","error_code":404,"type":"error"}
$ snap remove lxd

$ snap install --channel=4.1/stable lxd
lxd (4.1/stable) 4.1 from Canonical✓ installed
$ lxd waitready
$ curl --unix-socket /var/snap/lxd/common/lxd/unix.socket s/1.0/cluster/members?recursion=1
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":[{"roles":null,"architecture":"x86_64","server_name":"none","url":"https://0.0.0.0","database":false,"status":"Online","message":"fully operational"}]}
``` 

# Information to attach

 - [ n/a] Any relevant kernel output (`dmesg`)
 - [ n/a] Container log (`lxc info NAME --show-log`)
 - [ n/a] Container configuration (`lxc config show NAME --expanded`)
 - [ n/a] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ n/a] Output of the client with --debug
 - [ n/a] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by freeekanayaka** [comment]
I can reproduce the issue with the 4.0.2 snap from the 4.0/stable channel.

However, trying to build 4.0.2 from the tarball we released, using the dependencies and the Go packages shipped in `_dist`, does not seem to reproduce that. Also, looking at the code of the `lxd-4.0.2` git tag I don't find any way where `not found` could be returned. The diff between `lxd-4.0.1` and `lxd-4.0.2` also doesn't seem to sport any relevant change in that code path.

This is going to be interesting..

**Comment by freeekanayaka** [comment]
Dropping the LXD binary that I built by hand using the `lxd-4.0.2.tar.gz` tarball into the snap (`/var/snap/lxd/common/lxd.debug`) seems to fix the issue, hinting that indeed the source code behind the binary in the `4.0/stable` channel is not quite the same as the `lxd-4.0.2.tar.gz` tarball.

**Comment by freeekanayaka** [comment]
Running `lxd init` against the pristine 4.0.2 snap, and enabling clustering, still leads to the same error when running `curl --unix-socket /var/snap/lxd/common/lxd/unix.socket s/1.0/cluster/members?recursion=1`.

However, `lxc cluster list` (which hits the same URL), does work.. hm

**Comment by freeekanayaka** [comment]
Ok, turns out that the snap binary was built from the `stable-4.0` branch which is a few revisions ahead of the `lxd-4.0.2` tag. One of those revisions contains the regression.
