### ISSUE TITLE
`lxd image export <image> [target]` stopped supporting directories as the target 

### ISSUE THREAD

**Issue by paride** [lxc/lxd#7617]
Up to some time ago (for sure up to LXD < 4.0, sorry for not being more precise) it was possible to run
```
lxc image export <image> <target directory>
```
and LXD dumped the image files to `<target directory>` with predictable naming. Apparently this is not possible anymore: the target, if specified, is expected to be a filename. If target is `/path/to/somefile` then the image is dumped as the two files `somefile` (metadata) and `somefile.root` (squashfs root fs). This is not optimal as the format (`.tar.xz`) of `somefile` is not immediately visible. If `/path/to/somefile.tar.xz` is used then the root filesystem is saved as `somefile.tar.xz.root`, which is wrong.

# Required information

 * Distribution: Ubuntu
 * Distribution version: Groovy
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-26-generic
   * LXC version: 4.3
   * LXD version: 4.3
   * Storage backend in use: ZFS

**Comment by stgraber** [comment]
You're just missing a trailing slash.

```
stgraber@castiana:~/a$ lxc image export images:alpine/edge
Image exported successfully!                   
stgraber@castiana:~/a$ ls -l
total 4241
-rw-r--r-- 1 stgraber domain admins     864 Jul  3 15:08 lxd.tar.xz
-rw-r--r-- 1 stgraber domain admins 4329472 Jul  3 15:08 rootfs.squashfs
stgraber@castiana:~/a$ rm *

stgraber@castiana:~/a$ lxc image export images:alpine/edge /home/stgraber/a/
Image exported successfully!                   
stgraber@castiana:~/a$ ls -l
total 4241
-rw-r--r-- 1 stgraber domain admins     864 Jul  3 15:09 lxd.tar.xz
-rw-r--r-- 1 stgraber domain admins 4329472 Jul  3 15:09 rootfs.squashfs
stgraber@castiana:~/a$ rm *

stgraber@castiana:~/a$ lxc image export images:alpine/edge /home/stgraber/a/a
Image exported successfully!                   
stgraber@castiana:~/a$ ls -l
total 1
-rw-r--r-- 1 stgraber domain admins     864 Jul  3 15:09 a
-rw-r--r-- 1 stgraber domain admins 4329472 Jul  3 15:09 a.root
stgraber@castiana:~/a$ 
```
