### ISSUE TITLE
LVM-backed pool gives error message when backing up container with snapshots

### ISSUE THREAD

**Issue by Wnthr** [lxc/lxd#7636]
# Required information

 * Distribution: Gentoo
 * The output of "lxc info"
  driver: lxc
  driver_version: 4.0.2
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.38-gentoo
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  os_name: Gentoo
  os_version: ""
  project: default
  server: lxd
  server_clustered: false
  server_name: zerus
  server_pid: 2556
  server_version: 4.0.1
  storage: lvm
  storage_version: 2.02.187(2) (2020-03-24) / 1.02.170 (2020-03-24) / 4.41.0

# Issue description

When backing up a container with snapshots, lxc export fails with error message: Error: Create backup: Backup create: Failed to mount LVM snapshot volume: Failed to mount '/dev/vg_fast/containers_foo---controller' on '/var/lib/lxd/storage-pools/pool2/containers-snapshots/foo/-controller': no such file or directory

# Steps to reproduce

 1. Create snapshot of container
 2. lxc export foo foo-backup.tar.gz
 
# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
None.
 - [x] Container log (`lxc info NAME --show-log`)
Name: foo
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/07/08 22:31 UTC
Status: Running
Type: container
Profiles: bridged
Pid: 62875
Ips:
  eth0: inet    172.16.1.11     vethead0fa50
  eth0: inet6   fe80::216:3eff:fe72:46ce        vethead0fa50
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 12
  Disk usage:
    root: 1.67GB
  Network usage:
    eth0:
      Bytes received: 146.37MB
      Bytes sent: 6.63MB
      Packets received: 45623
      Packets sent: 26575
    lo:
      Bytes received: 6.33MB
      Bytes sent: 6.33MB
      Packets received: 15113
      Packets sent: 15113
    sit0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
Snapshots:
  after_install (taken at 2020/07/09 15:06 UTC) (stateless)
  after_restore (taken at 2020/07/09 15:23 UTC) (stateless)

Log:

 - [x] Container configuration (`lxc config show NAME --expanded`)
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian stretch amd64 (20200708_05:25)
  image.os: Debian
  image.release: stretch
  image.serial: "20200708_05:25"
  image.type: squashfs
  volatile.base_image: 703d3340f246c9fb8d98cae44524fffa022b9cb573706b67fc4803f751a1aff2
  volatile.eth0.host_name: vethead0fa50
  volatile.eth0.hwaddr: 00:16:3e:72:46:ce
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: pool2
    type: disk
ephemeral: false
profiles:
- bridged
stateful: false
description: ""

**Comment by stgraber** [comment]
Pretty sure we fixed that issue a while back. Can you please upgrade to 4.0.2?

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/pull/7348

**Comment by stgraber** [comment]
Tentatively closing as this looks like an issue we've fixed in 4.0.2.
If you do get this problem on either 4.0.2 or 4.3, let us know and we'll re-open it.
