### ISSUE TITLE
VMs launched from published images do not have image information

### ISSUE THREAD

**Issue by lucasmoura** [lxc/lxd#7648]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-40-generic
   * LXC version: 4.3
   * LXD version: 4.3
   * Storage backend in use: zfs

# Issue description

When creating a lxd vm, we can perfectly see that the image information cab be found on the vm instance configuration. However, if we publish that same image and create another lxd vm from it, we loose this information from the configuration.

# Steps to reproduce

 1. Launch an ubuntu lxd vm
```sh
lxc launch ubuntu-daily:focal focal-vm --vm
```
 2. Verify that the `image` information are in the configuration, such as `image.release`
```sh
lxc config edit focal-vm
```
 3. Publish the vm image
```sh
lxc stop focal-vm
lxc publish focal-vm
```
4. Launch a new vm image from the published image
```sh
lxc launch test-focal new-test-focal --vm
```
5. Verify that the image information is not found:
```sh
lxc config edit new-test-focal
```

**Comment by stgraber** [comment]
The `image.*` keys are set based on what the properties are on the image.
So if `lxc image show focal-vm` doesn't have properties set to describe it, then it's normal that new-test-focal won't either.

**Comment by stgraber** [comment]
So there was a bug that the properties set through `lxc config metadata` would land in the image files but not in the DB during publish, I've pushed a fix for that now.
