### ISSUE TITLE
Panic while creating a certificate via the API

### ISSUE THREAD

**Issue by zulcss** [lxc/lxd#765]
0.11 on wiley

2015/06/15 09:56:50 handling POST /1.0/certificates
2015/06/15 09:56:50 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 16 [running]:
net/http.func·011()
	/usr/lib/go/src/net/http/server.go:1130 +0xbb
main.certificatesPost(0xc208034ea0, 0xc208035380, 0x0, 0x0)
	/build/buildd/lxd-0.11/dist/src/github.com/lxc/lxd/lxd/certificates.go:150 +0x7c1
main.func·021(0x7f9708719f10, 0xc2080c4dc0, 0xc208035380)
	/build/buildd/lxd-0.11/dist/src/github.com/lxc/lxd/lxd/daemon.go:229 +0x5f0
net/http.HandlerFunc.ServeHTTP(0xc2080ca0c0, 0x7f9708719f10, 0xc2080c4dc0, 0xc208035380)
	/usr/lib/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208052640, 0x7f9708719f10, 0xc2080c4dc0, 0xc208035380)
	/build/buildd/lxd-0.11/dist/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc20800a4e0, 0x7f9708719f10, 0xc2080c4dc0, 0xc208035380)
	/usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2080c4d20)
	/usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e

**Comment by tych0** [comment]
On Mon, Jun 15, 2015 at 07:01:28AM -0700, zulcss wrote:
> 0.11 on wiley

I guess this is over the unix socket and not TCP?

**Comment by zulcss** [comment]
Yes

**Comment by tych0** [comment]
On Mon, Jun 15, 2015 at 07:18:26AM -0700, zulcss wrote:
> Yes

Ok, I think the API call you're making is malformed (although we still
shouldn't crash if it is, I'll send a patch in a second).

You can either tell LXD "add the cert that I'm telling you via json"
or "use the cert for the current connection"; when you connect over
the unix socket you don't have to use https/TLS, and therefore you
don't have a current cert, so you have to provide a certificate.
