### ISSUE TITLE
CentOS 8 and Fedora 31/32 Cloud Images Ignore Network Configuration Files

### ISSUE THREAD

**Issue by shawnweeks** [lxc/lxd#7674]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

config:
  cluster.https_address: 10.0.2.20:8443
  core.https_address: 10.0.2.20:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.0.2.20:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICODCCAb+gAwIBAgIQYcYTiR+fnnzFdXzMyC3EYzAKBggqhkjOPQQDAzBGMRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMSYwJAYDVQQDDB1yb290QGNsb3Vk
    Ny5jbG91ZGJyb2NrdGVjLmNvbTAeFw0yMDA1MjQxNjU1MjFaFw0zMDA1MjIxNjU1
    MjFaMEYxHDAaBgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxJjAkBgNVBAMMHXJv
    b3RAY2xvdWQ3LmNsb3VkYnJvY2t0ZWMuY29tMHYwEAYHKoZIzj0CAQYFK4EEACID
    YgAEyYXxdQTDltvWDJHdfDZgNBDEtV58mWH0NIK6VdDwxMpeagS2WenPz7F4wBHH
    RVw33wltFY74jgOFhDpYDvGd/MXNkmNpwIXP+pifqzB8N26MNEAN1D3LW+sYuF7T
    4/nYo3IwcDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYD
    VR0TAQH/BAIwADA7BgNVHREENDAyghhjbG91ZDcuY2xvdWRicm9ja3RlYy5jb22H
    BH8AAAGHEAAAAAAAAAAAAAAAAAAAAAEwCgYIKoZIzj0EAwMDZwAwZAIwEfEycl0i
    tmpHUSzK5nFCBAW1+rMP3zaNKsN8nMwnmtmrWGX1Yl1r4yQcnrTx3hQgAjAyp9bU
    qVYY00N5Mb2yxX1Nj0v8X+R1UbSa+ZZmyoN4CGK3hHysWBr2tu3fZOfEv2o=
    -----END CERTIFICATE-----
  certificate_fingerprint: f5977db2c09dc64907f4b1911bc8f4bfca571ecd77ca1db2e5936b0fcd42ac7f
  driver: lxc
  driver_version: 4.0.3
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-40-generic
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_notify: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: true
  server_name: cloud10
  server_pid: 2293
  server_version: "4.3"
  storage: zfs
  storage_version: 0.8.3-1ubuntu12

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

1. Start with a bare bones Ubuntu 20.04 system and the latest LXD Snap
2. Create an LXC Profile called "vlan13" with a macvlan nictype and a cloud init static ip
3. Create a CentOS 8 or Fedora 32 Container Instance using that profile
```lxc launch images:centos/8/cloud -p default -p vlan13 ipa1```
4. Note that /etc/sysconfig/network-scripts/ifcfg-eth0 is populated with your static IP
5. Note that "ip addr" doesn't show eth0 as being up or your ip as being applied.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
That would be a bug in NetworkManager or other distro scripts in CentOS/Fedora, not something that we have any control over in LXD.

**Comment by shawnweeks** [comment]
So where do I file the bug request at?

**Comment by stgraber** [comment]
LXD takes the config you provide and feeds it to cloud-init, the job of generating the config is cloud-init's job, the job of applying that config to your interfaces is NetworkManager's.

Note that if your interface isn't named `eth0`, you may need to duplicate one workaround we've put in place in the images.
If that's the case for you, look at and adapt `/etc/systemd/system/network-device-down.service` which is a workaround for a NetworkManager bug where it doesn't properly handle interfaces that are already up.

**Comment by stgraber** [comment]
Most likely, against NetworkManager, either upstream or in the distro's bugtracker.
