### ISSUE TITLE
Go related: Can we have a dummy go file for folders containing c code?

### ISSUE THREAD

**Issue by dionysius** [lxc/lxd#7677]
# Required information

Affects LXD source code on branch stable-4.0

# Issue description

When using lxd as go module for a project, combined with go vendoring, the project can't be compiled:

```
# github.com/lxc/lxd/shared
vendor/github.com/lxc/lxd/shared/util_linux_cgo.go:34:42: fatal error: ../lxd/include/process_utils.h: No such file or directory
 #include "../lxd/include/process_utils.h"
                                          ^
compilation terminated.
```

The reason is go vendoring doesn't check out non-go-packages and this way the header files are missing. There is no distinct solution from the golang devs (https://github.com/golang/go/issues/26366) and the way go vendoring behaves is by design.

I'm asking what are you willing to do to allow other projects to depend on lxd source code. One possibility, and the easiest,  is placing a dummy .go file into that folder `/lxd/include/` so vendoring detects this folder as a package and can be vendored this way - this is why I raised this issue.

# Steps to reproduce

 1. go get github.com/lxc/lxd@stable-4.0
 2. Use this module in your project
 3. go mod vendor
 4. go build ./...

**Comment by stgraber** [comment]
Hmm, would that actually work when we never import from that path, so if go mod just follows imports to decide what directory to include, this will not help.

**Comment by dionysius** [comment]
I forgot also a little disclaimer: This happens only when vendoring modules. When using modules normally you have access to all files. But vendoring is important for reproducible builds.

My suggestion is based on this comment https://github.com/golang/go/issues/26366#issuecomment-606404010 to trick vendoring that this folder is a go package. I've prepared a scenario with https://github.com/dionysius/issue-lxd-7677-lib representing LXD and https://github.com/dionysius/issue-lxd-7677-consumer representing a project wanting to use LXD.

You don't need to clone the `lib` repo, but let me explain the structure:
- `lxd/` is just a folder and go package, like https://github.com/lxc/lxd/tree/master/lxd is - just for the structure
- `lxd/include1` is a folder without any go file and thus is no go package, like currently https://github.com/lxc/lxd/tree/master/lxd/include is
- `lxd/include2` is a folder with a simple go file and thus a normal go package (even without "real" content)
- `lxd/include3` is a folder with a go file with a special build flag, still a normal go package
  - Adding a build flags allows you to steer which files are included at building, with this we can exclude that dummy file and thus shouldn't have any impact on building lxd
- `lxd/include4` is the same as include3 (beside the name), but it is _blind_ imported from package `implementation`
- `lxd/implementation` is a folder which uses the include4 files and thus makes a _blind_ import to that, that's what i suggest for https://github.com/lxc/lxd/blob/master/shared/util_linux_cgo.go and other files including c code
  - you would need to to this only once per package, but why not just "document" this releation in all affected files? You decide

Now "my" project is the `consumer` repo:
```
$ git clone https://github.com/dionysius/issue-lxd-7677-consumer.git
Cloning into 'issue-lxd-7677-consumer'...
...
$ go mod vendor; tree vendor
vendor/
├── github.com
│   └── dionysius
│       └── issue-lxd-7677-lib
│           └── lxd
│               ├── implementation
│               │   └── implementation.go
│               ├── include4
│               │   ├── 4.txt
│               │   └── dummy.go
│               └── package.go
└── modules.txt

6 directories, 5 files
```
You can play around with the imports in https://github.com/dionysius/issue-lxd-7677-consumer/blob/master/main.go#L7 and you'll see different results in `vendor/`

You have the following options:
- For me option `lxd/implementation` combined with `lxd/include4` would be best, as I won't need to do anything and the required folder is vendored implicitly
- I would need at minimum variant `include2` so I can steer the vendoring from my side explicitly
- Or you can also choose not to and I would need to manually copy the files into the vendor folder at the right places

**Comment by stgraber** [comment]
@brauner can you take care of this?

I think we should go with:
 - Add `dummy.go` file (`package include`) in `lxd/include`
 - Add a dummy blind import `_ github.com/lxc/lxd/lxd/include` anywhere we have a matching `#include`

**Comment by brauner** [comment]
> @brauner can you take care of this?
> 
> I think we should go with:
> 
> * Add `dummy.go` file (`package include`) in `lxd/include`
> * Add a dummy blind import `_ github.com/lxc/lxd/lxd/include` anywhere we have a matching `#include`

Why not calling it `include.go`?
