### ISSUE TITLE
lxc export fills up root filesystem and doesn't release space when file is deleted

### ISSUE THREAD

**Issue by Wnthr** [lxc/lxd#7685]
#7666 Required information

config: {} 
api_extensions: 
- storage_zfs_remove_snapshots 
- container_host_shutdown_timeout 
- container_stop_priority 
- container_syscall_filtering 
- auth_pki 
- container_last_used_at 
- etag 
- patch 
- usb_devices 
- https_allowed_credentials 
- image_compression_algorithm 
- directory_manipulation 
- container_cpu_time 
- storage_zfs_use_refquota 
- storage_lvm_mount_options 
- network 
- profile_usedby 
- container_push 
- container_exec_recording 
- certificate_update 
- container_exec_signal_handling 
- gpu_devices 
- container_image_properties 
- migration_progress 
- id_map 
- network_firewall_filtering 
- network_routes 
- storage 
- file_delete 
- file_append 
- network_dhcp_expiry 
- storage_lvm_vg_rename 
- storage_lvm_thinpool_rename 
- network_vlan 
- image_create_aliases 
- container_stateless_copy 
- container_only_migration 
- storage_zfs_clone_copy 
- unix_device_rename 
- storage_lvm_use_thinpool 
- storage_rsync_bwlimit 
- network_vxlan_interface 
- storage_btrfs_mount_options 
- entity_description 
- image_force_refresh 
- storage_lvm_lv_resizing 
- id_map_base 
- file_symlinks 
- container_push_target 
- network_vlan_physical 
- storage_images_delete 
- container_edit_metadata 
- container_snapshot_stateful_migration 
- storage_driver_ceph 
- storage_ceph_user_name 
- resource_limits 
- storage_volatile_initial_source 
- storage_ceph_force_osd_reuse 
- storage_block_filesystem_btrfs 
- resources 
- kernel_limits 
- storage_api_volume_rename 
- macaroon_authentication 
- network_sriov 
- console 
- restrict_devlxd 
- migration_pre_copy 
- infiniband 
- maas_network 
- devlxd_events 
- proxy 
- network_dhcp_gateway 
- file_get_symlink 
- network_leases 
- unix_device_hotplug 
- storage_api_local_volume_handling 
- operation_description 
- clustering 
- event_lifecycle 
- storage_api_remote_volume_handling 
- nvidia_runtime 
- container_mount_propagation 
- container_backup 
- devlxd_images 
- container_local_cross_pool_handling 
- proxy_unix 
- proxy_udp 
- clustering_join 
- proxy_tcp_udp_multi_port_handling 
- network_state 
- proxy_unix_dac_properties 
- container_protection_delete 
- unix_priv_drop 
- pprof_http 
- proxy_haproxy_protocol 
- network_hwaddr 
- proxy_nat 
- network_nat_order 
- container_full 
- candid_authentication 
- backup_compression 
- candid_config 
- nvidia_runtime_config 
- storage_api_volume_snapshots 
- storage_unmapped 
- projects 
- candid_config_key 
- network_vxlan_ttl 
- container_incremental_copy 
- usb_optional_vendorid 
- snapshot_scheduling 
- container_copy_project 
- clustering_server_address 
- clustering_image_replication 
- container_protection_shift 
- snapshot_expiry 
- container_backup_override_pool 
- snapshot_expiry_creation 
- network_leases_location 
- resources_cpu_socket 
- resources_gpu 
- resources_numa 
- kernel_features 
- id_map_current 
- event_location 
- storage_api_remote_volume_snapshots 
- network_nat_address 
- container_nic_routes 
- rbac 
- cluster_internal_copy 
- seccomp_notify 
- lxc_features 
- container_nic_ipvlan 
- network_vlan_sriov 
- storage_cephfs 
- container_nic_ipfilter 
- resources_v2 
- container_exec_user_group_cwd 
- container_syscall_intercept 
- container_disk_shift 
- storage_shifted 
- resources_infiniband 
- daemon_storage 
- instances 
- image_types 
- resources_disk_sata 
- clustering_roles 
- images_expiry 
- resources_network_firmware 
- backup_compression_algorithm 
- ceph_data_pool_name 
- container_syscall_intercept_mount 
- compression_squashfs 
- container_raw_mount 
- container_nic_routed 
- container_syscall_intercept_mount_fuse 
- container_disk_ceph 
- virtual-machines 
- image_profiles 
- clustering_architecture 
- resources_disk_id 
- storage_lvm_stripes 
- vm_boot_priority 
- unix_hotplug_devices 
- api_filtering 
- instance_nic_network 
- clustering_sizing 
- firewall_driver 
- projects_limits 
- container_syscall_intercept_hugetlbfs 
- limits_hugepages 
- container_nic_routed_gateway 
- projects_restrictions 
- custom_volume_snapshot_expiry 
- volume_snapshot_scheduling 
- trust_ca_certificates 
- snapshot_disk_usage 
- clustering_edit_roles 
- container_nic_routed_host_address 
- container_nic_ipvlan_gateway 
- resources_usb_pci 
- resources_cpu_threads_numa 
- resources_cpu_core_die 
- api_os 
- resources_system 
- usedby_consistency 
api_status: stable 
api_version: "1.0" 
auth: trusted 
public: false 
auth_methods: 
- tls 
environment: 
 addresses: [] 
 architectures: 
 - x86_64 
 - i686 
 driver: lxc 
 driver_version: 4.0.2 
 firewall: xtables 
 kernel: Linux 
 kernel_architecture: x86_64 
 kernel_features: 
netnsid_getifaddrs: "true" 
seccomp_listener: "true" 
seccomp_listener_continue: "false" 
shiftfs: "false" 
uevent_injection: "true" 
unpriv_fscaps: "true" 
 kernel_version: 5.4.48-gentoo-x86_64-mw 
 lxc_features: 
cgroup2: "true" 
mount_injection_file: "true" 
network_gateway_device_route: "true" 
network_ipvlan: "true" 
network_l2proxy: "true" 
network_phys_macvlan_mtu: "true" 
network_veth_router: "true" 
pidfd: "false" 
seccomp_notify: "true" 
 os_name: Gentoo 
 os_version: "" 
 project: default 
 server: lxd 
 server_clustered: false 
 server_pid: 9555 
 server_version: 4.0.2 
 storage: lvm 
 storage_version: 2.02.187(2) (2020-03-24) / 1.02.170 (2020-03-24) / 4.41.0

# Issue description

When backing up my container, my root filesystem filled up. After ctrl-c on the backup job and deleting the file in /var/lib/lxd/backups that ate all the space, none of the space was reclaimed. Restarting lxd solved the problem, I'm guessing because the backup file was still open in the process.

# Steps to reproduce

 1. lxc export --compression=none mycontainer /disk/mycontainer.tar
 2. watch disk space disappear
 3. rm -rf /var/lib/lxd/backups/*

# Information to attach

 It would be good to have the ability to backup a container that is larger than the available space in /. In this case, using the destination directory for temporary creation of the backup image would have been the expected behavior. Also, if cancelling a backup job, it's probably a good idea to cleanup so that the created file at least isn't still open.

Also, after mounting a bigger temporary file system to workaround the problem, the backups directory still took up some 256M after finishing up the backup (down from 13G for a 12G sized backup file at destination). I suspect there might be files still open even when not hitting ctrl-c, since the directory itself is empty.

**Comment by stgraber** [comment]
ctrl+c in the client isn't going to do much in this case as the server is what's making the backup.

The required bug template above is truncated so we don't have the two critical pieces of information needed to look into this, namely LXD version and storage backend used.

**Comment by stgraber** [comment]
Note that the preferred way to allocate more space is to use storage.backups_volume and a volume coming from one of the storage pools.

**Comment by Wnthr** [comment]
Hopefully the repaste is more complete, thanks for letting me know.

Not sure what is considered client vs server in this case, but the ctrl-c was an attempt to stop the backup from the command line of the lxd host. If the command itself doesn't control the backup process, it seems like the prompt should be returned immediately instead. Either way, the server process should be able to detect a full file system and either cancel the job and delete the files, or at the very least return the used temp space.

When making a backup without specifying a destination, I would assume a backups volume configuration would be used to pick the destination for me. However, if I specifically specify backing up a container on pool2 located on disk A, and delivering the result to a specific disk B, there seems to be no good reason that the system would use an additional area on disk C as intermediate storage for the entire backup, and then move that backup to B?

**Comment by stgraber** [comment]
Ok, so LVM would use `genericVFSBackupVolume` to generate the tarball, I went through that logic and we only manually open files in very limited case and always with a suitable `defer Close` on them.

Anyway, what happens when you do `lxc export` is:
 - CLI tells LXD's backup API to generate a new backup (`/1.0/instances/NAME/backups`)
 - LXD creates a compressed tarball writer and adds every file of your container & snapshots to it one by one + add metadata
 - That tarball is stored in the backups path at /var/snap/lxd/common/lxd/backups (or /var/lib/lxd/backups if non-snap)
 - The backup is marked to auto-expire after a day in case the client doesn't fetch it by then
 - CLI waits for that backup to be fully generated, then downloads it to the target path and asks LXD to delete the backup

Doing (ctrl+c) only disconnects the client, the backup is still generated by the server (as can be seen in `lxc operation list`), only now it will never be downloaded and deleted, so it will take its timeout to have it go away releasing the space.

**Comment by stgraber** [comment]
`lxc export` was incorrectly missing the logic that normally prints a warning on `ctrl+c` for uninterruptible operations, I'm pushing a branch fixing this.
