### ISSUE TITLE
Using LXD client without GCC

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#769]
In https://github.com/lxc/lxd/issues/762#issuecomment-112463214 LXD fails to install without GCC. From https://github.com/mattn/go-sqlite3/issues/212:

> if you install go-sqlite3 with go install github.com/mattn/go-sqlite, you don't need gcc

Will that work for LXD?

**Comment by stgraber** [comment]
his comment is very unclear. He first says that go-sqlite3 uses cgo and so requires gcc to build, then says that github.com/mattn/go-sqlite doesn't, but that repository doesn't exist at all.

Anyway, for LXD, the answer is still no.

**Comment by stgraber** [comment]
There will never be a way for you to build the whole of LXD without using cgo, for the simple reason that the container runner itself is a C library (liblxc), so even if we were to somehow use pure Go versions of everything else, we'd still need cgo for go-lxc.

**Comment by tych0** [comment]
On Wed, Jun 17, 2015 at 08:17:34AM -0700, Stéphane Graber wrote:
> his comment is very unclear. He first says that go-sqlite3 uses cgo and so requires gcc to build, then says that github.com/mattn/go-sqlite doesn't, but that repository doesn't exist at all.

You can go install go-sqlite3 and it will put the .a somewhere and use
that. I'm not sure how go invokes the linker, so you still may need
gcc even if LXD didn't have embedded C.

**Comment by stgraber** [comment]
I guess we may be able to make the client (github.com/lxc/lxd/lxc) buildable without cgo, but since you're mentioning go-sqlite3, you're apparently trying to build the server and that's simply not possible.

**Comment by stgraber** [comment]
@tych0 how does it build the .a for the binding itself (the cgo stuff) without using gcc to build it?

**Comment by tych0** [comment]
On Wed, Jun 17, 2015 at 08:22:18AM -0700, Stéphane Graber wrote:
> @tych0 how does it build the .a for the binding itself (the cgo stuff) without using gcc to build it?

It doesn't. Once the .a is installed, it will use that instead of
trying to build it again.

**Comment by techtonik** [comment]
> I guess we may be able to make the client (github.com/lxc/lxd/lxc) buildable without cgo

Yes, that's the point.

**Comment by stgraber** [comment]
Ah right, which is fine for something that can be statically built like that, well, so long as you don't expect the .a to be usable on another architecture or OS.

**Comment by stgraber** [comment]
That's still not going to help you with go-lxc since that one is dynamically linked and depends on a dozen of libs including the C library (as does the C code we have in utils.go).

**Comment by techtonik** [comment]
This becomes complicated. It is hard to get "who installs and builds/complies when and what" after coming from Python.

**Comment by stgraber** [comment]
So I believe with my recent changes you can now build the client tool without gcc. It's been confirmed to work on Mac OS and Linux. Support for other OSes may vary depending on what the syscall module supports on that platform.

**Comment by techtonik** [comment]
Nice. I will try it next time I get back to Windows,

**Comment by stgraber** [comment]
@techtonik Windows won't work, see #825 

The problem is all the various syscalls we use which are UNIX-specific, quite a bit more work would be needed to come up with generic functions for those to work with Windows. It's obviously not a priority for us, but if someone is willing to give it a shot, it should all be doable.
