### ISSUE TITLE
Config commands should output a status message

### ISSUE THREAD

**Issue by mhitza** [lxc/lxd#7706]
# Required information

 * Distribution: Ubuntu
 * Distribution version:  19.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.3.0-62-generic
   * LXC version: 4.0.3
   * LXD version: 4.3
   * Storage backend in use: dir

# Issue description

When running commands like `lxc config set VM autostart.boot.priority 1` there is no confirmation message if anything was changed or if it stayed the same.

It would be helpful in terms of automation to print a confirmation message, I have no particular preference for the message, but at least it should confirm that something has changed, or that nothing had changed.

Currently, in the Ansible automation I'm writing, I have to rely on the --debug flag and pipe stderr to stdout to be able to grep the HTTP response JSON to know if there were any changes made.

**Comment by stgraber** [comment]
I'm confused, why can't you just check the return code?

If things work, LXD will always exit with 0, if not it will exit with 1.

Parsing output strings is super bad practice in general as those are meant for humans and so get translated and/or can change at any time for any reason.

**Comment by mhitza** [comment]
When writing an Ansible playbook you want to know if a command applied has changed the state of the system (to ensure idempotency of the configuration written). If it just returns 0 because it did not fail there's no way of knowing if a change took place.

**Comment by stgraber** [comment]
Ok, so same as #2283 then.

**Comment by stgraber** [comment]
Worth noting that something like Ansible really ought to be using the API rather than wrapping the human focused CLI.

Using the REST API, figuring out whether a key is already set is quite a bit easier.

**Comment by mhitza** [comment]
I agree that it would be nice if there was an Ansible module that integrated more deeply with LXD and it's REST API.

While the linked issue relates to operation idempotency. The level of idempotency at which Ansible operates is different. From an Ansible playbook writer perspective, I'm interested to have an idempotent playbook, which doesn't necessarily require the underlying operation involved to be idempotent.

For example, let's say I try to manage directly dnf upgrade calls[1]. If there are packages that need to be upgraded changes will be applied to the system. However, because dnf reports if there's anything to upgrade or not, I can inspect the output and tag the execution state myself as idempotent.

```yaml
- name: Ensure everything is up to date
  shell: dnf upgrade -y
  register: dnf_upgrade
  changed_when: 'Nothing to do.' not in dnf_upgrade.stdout
```

Anyway, that's my rationale for opening this issue.

[1] it's a bad example considering that ansible has a dnf wrapper out of the box, but it's the tool that came to mind in regards to the confirmation messages
