### ISSUE TITLE
Failed to start gpu device: Can't create device as devices path is mounted nodev

### ISSUE THREAD

**Issue by nahall** [lxc/lxd#7710]
# Required information

 * Distribution: Debian
 * Distribution version: 10.4
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.5.0-0.bpo.2-amd64
   * LXC version: 4.3
   * LXD version: 4.3 (running within a snap)
   * Storage backend in use: zfs

# Issue description

I'm trying to add a gpu device "mygpu" to a container via a profile and I'm getting the error:

`Error: Common start logic: Failed to start device "mygpu": Can't create device as devices path is mounted nodev`

# Steps to reproduce

 1. lxc profile copy default mytestprofile
 2. lxc profile edit mytestprofile
 3. Add the following in the devices section:
>   mygpu:
>     type: gpu
> 

 4. lxc launch ubuntu:18.04 --profile mytestprofile
Fails with `Error: Common start logic: Failed to start device "mygpu": Can't create device as devices path is mounted nodev`

lxc profile show mytestprofile:

> config:
>   environment.TZ: America/Chicago
> description: Default LXD profile
> devices:
>   eth0:
>     name: eth0
>     network: lxdbr0
>     type: nic
>   mygpu:
>     type: gpu
>   root:
>     path: /
>     pool: default
>     type: disk
> name: mytestprofile
> used_by:
> - /1.0/instances/loyal-goshawk
> 
>

**Comment by stgraber** [comment]
This suggests that /var/snap/lxd is on a filesystem mounted nodev, if that's the case, you need to fix that.

Please show `cat /proc/self/mountinfo` to confirm.

**Comment by nahall** [comment]
You are right, this system is running in ZFS and the root pool had the ZFS property set "devices=off" which causes the mountpoint to be nodev, and rpool/lxd inherited this property from rpool so it also had nodev set. Setting devices=on allowed lxd to start the container. Thanks.
