### ISSUE TITLE
consider means of waiting for container init

### ISSUE THREAD

**Issue by jetpackdanger** [lxc/lxd#7711]
It'd be useful if there were a built-in way to wait for a container to finish initializing.

(One of the problems this solves is running `apt update` too soon in the container, before the user's custom apt mirror has been configured.)

Currently we poll `cloud-init status` until we get `status: done` (or time out).

Depending on the container image the definition of "ready" may vary, so perhaps waiting for cloud-init should just be a default, overridable by the image supplying a hook script of some sort.

**Comment by jetpackdanger** [comment]
For the curious, or those who have a similar problem:

```bash
function lxc_wait_for_cloud_init_done {
    lxc=$1
    echo -n "Polling ${lxc} for cloud-init completion..."
    for x in {1..20} ; do
	status=$(lxc exec $lxc cloud-init status)
	case "$status" in
	    "status: done")
		echo " done."
		return 0	# exit status, not boolean
		;;
	    *)
		echo -n .
		;;
	esac
	sleep 3
    done

    return 1			# again, exit status
}
```

**Comment by stgraber** [comment]
Having LXD run arbitrary commands inside all starting containers to try to figure out if they're running or not isn't going to happen. This would cause potentially massive load on systems running a lot of containers and would also require awareness from LXD as to what the containers are running which isn't something we've ever wanted to have to deal with.

There's also the general issue of the definition of "ready" varying very widely based on user preference.
For some, this means that network is functional, though whether that means routable or routable+DNS can also be debated.
For others, this means having their main service started and responding appropriately.
Or in some cases, waiting for all services to be started.

In practice, it tends to be far better for whoever interacts with the containers/VMs to check what actually matters to them, whether it be cloud-init being done, network being initialized, some service running or whatever may fit their use case.
