### ISSUE TITLE
centos/8 Virtual Machine does'nt boot On LXD 4.3

### ISSUE THREAD

**Issue by gbonazzoli** [lxc/lxd#7716]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version:  5.4.0-42-generic
   * LXD version: snap 4.3
   * Storage backend in use: ZFS 0.8.3-1ubuntu12.1

# Issue description

If you initialize a Centos VM with the following command:

`lxc init images:centos/8 srv-oracle --vm`

the machine doesn't boot and entering in console (with lxc console srv-oracle) it displays:

`../../grub-core/loader/i386/efi/linux.c:215:/boot/vmlinuz-4.18.0-193.6.3.el8_2.centos.plus.x86_64 has invalid signature.` 

I tried other images centos/8/xxxxx, but the result is still the same.

**Comment by stgraber** [comment]
I suspect that's a temporary glitch in the Centos side following the grub vulnerabilities that got disclosed this past week.

I expect Centos will publish new signed kernels fixing this soon.

Until then setting security.secureboot=false on the instance should get you past this.

**Comment by gbonazzoli** [comment]
**security.secureboot=false** works like a charm!!! Thanks a lot.

I only want to add that on centos8 the boot get an error on the lxd-agent.

I was obliged to create the following profile in order to enter the machine as root

```config:
  user.user-data: |
    #cloud-config
    ssh_pwauth: yes
    users:
      - name: ubuntu
        passwd: "$6$W2ZyG34q$CQG1MkN0aqzWGKkZwpg4WuQo1Z3YRx4487jGpXtbabGARliNRyVofS.RcbgIvmFBiVzeGCllU2c66XFcY.2GA/"
        lock_passwd: false
        groups: lxd
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
    runcmd:
     - timedatectl set-timezone Europe/Rome
     - echo "pippo" | passwd root --stdin
description: VM specific configuration
devices:
  config:
    source: cloud-init:config
    type: disk
name: vm-centos8
used_by:
- /1.0/instances/srv-oracle
```

**Comment by stgraber** [comment]
Yeah, the Centos 8 kernel recently dropped the required 9p driver... Until they undo that change, there's no way for the agent to run on there...
