### ISSUE TITLE
Failed to start containers after upgrade LXD 4.3 to 4.4

### ISSUE THREAD

**Issue by arren-ru** [lxc/lxd#7719]
# Required info

Distribution: Archlinux
Lxc info: https://gist.github.com/arren-ru/95200a9617104774223a7a0675cad6b4

# Issue description

After upgrading LXD containers are failed to start even newly created with messages in journald log
```text
Aug 03 15:26:23 helios lxd[1335]: t=2020-08-03T15:26:23+0700 lvl=eror msg="Failed to stop device 'eth0': Failed to list network interfaces: container is not running: \"test\""
Aug 03 15:26:23 helios lxd[1335]: t=2020-08-03T15:26:23+0700 lvl=eror msg="Failed starting container" action=start created=2020-08-03T15:25:51+0700 ephemeral=false name=test project=default stateful=false used=1970-01-01T07:00:00+0700
```

Also each container after try to start fails with status = ERROR and leave undeleted macvlan network device, so each failed container left bunch of devices.
Containers are configured to use macvlan with `hp1` as parent with config:
```yaml
devices:
  eth0:
    hwaddr: 00:20:3e:46:86:0a
    nictype: macvlan
    parent: hp1
    type: nic
```

`ip a` prints:
```text
⋮
3: hp1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:23:7d:fc:32:58 brd ff:ff:ff:ff:ff:ff
⋮
6: mac9c7f7112@hp1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:16:3e:1e:5d:39 brd ff:ff:ff:ff:ff:ff
7: mace73eced1@hp1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:20:3e:46:86:0a brd ff:ff:ff:ff:ff:ff
⋮
13: mac95594de1@hp1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:16:3e:1e:5d:39 brd ff:ff:ff:ff:ff:ff
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
    https://gist.github.com/arren-ru/b96909bdf413a97b6725388ac2400b28
 - [x] Container configuration (`lxc config show NAME --expanded`)
    https://gist.github.com/arren-ru/abdc1b0e2f316cfbe585289f7078f5fa
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
    https://gist.github.com/arren-ru/ecfda3bd5e98dcb4865393c6162b5013
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by arren-ru** [comment]
Suddenly I found the problem by traversing the logs: lxd can't detect apparmor version because of:
```text
msg="The start hook failed" container=test err="Failed to run: apparmor_parser --version: "
```
Not sure if this ok, but I had to install apparmor to successfully start containers.

**Comment by tomponline** [comment]
There are lots of apparmor errors in your main daemon log, so this looks like it could be related to https://discuss.linuxcontainers.org/t/lxd-4-4-container-doesnt-start-unless-apparmor-is-installed/8580/3

**Comment by arren-ru** [comment]
> There are lots of apparmor errors in your main daemon log, so this looks like it could be related to https://discuss.linuxcontainers.org/t/lxd-4-4-container-doesnt-start-unless-apparmor-is-installed/8580/3

Yep just found problem locally, will checkout the link you gave me, thanks.

**Comment by stgraber** [comment]
Yeah, definitely sounds like the bug we fixed yesterday. Would strongly recommend that Arch cherrypicks that fix.

As a quick alternative you can try to just install the apparmor tools.
