### ISSUE TITLE
'nvme list' does NOT show up exported drives inside the container

### ISSUE THREAD

**Issue by ssampath** [lxc/lxd#7723]
# Required information

  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 5.4.0-42-generic
  server: lxd
  server_pid: 12066
  server_version: 3.0.3
  storage: zfs
  storage_version: 0.8.3-1ubuntu12.1
  server_clustered: false
  server_name: SudheFMdev01
  project: ""

# Issue description

'nvme list' on the container does not list any devices exported from the host.

# Steps to reproduce

**On the host:**

 1. lxc config device add spdk nvme0n1 unix-block path=/dev/nvme0n1
 2. lxc config device add spdk nvme0 unix-char path=/dev/nvme0

**Inside the container:**

root@SudheFMdev01:/var/lib# lxc exec spdk bash
root@spdk:~# nvme list
root@spdk:~# ls -l /dev/nvme*
crw-rw---- 1 root root 242, 0 Aug  5 00:45 /dev/nvme0
brw-rw---- 1 root root 259, 0 Aug  5 00:45 /dev/nvme0n1
root@spdk:~# lsmod | grep nvme
nvme                   45056  2
nvme_core             102400  4 nvme
root@spdk:~#

# Information to attach

root@SudheFMdev01:/mnt/work# lxc config show spdk --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20200729)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20200729"
  image.version: "18.04"
  raw.idmap: |-
    uid 1000 1000
    gid 1000 1000
  volatile.base_image: 0041760acce68c101aecc63372309733df5bb94bf180eb3d9a21ae26c304f536
  volatile.eth0.hwaddr: 00:16:3e:db:c3:29
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":101001,"Nsid":1001,"Maprange":64535},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":false,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":101001,"Nsid":1001,"Maprange":64535}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":101001,"Nsid":1001,"Maprange":64535},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":false,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":101001,"Nsid":1001,"Maprange":64535}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  gpu:
    type: gpu
  nvme0:
    path: /dev/nvme0
    type: unix-char
  nvme0n1:
    path: /dev/nvme0n1
    type: unix-block
  root:
    path: /
    pool: data
    type: disk
  work:
    path: /mnt/work
    source: /mnt/work
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
root@SudheFMdev01:/mnt/work#

**Comment by stgraber** [comment]
You could have saved me from trying to reproduce this if you had showed the error from `nvme list` :)

```
root@u20:~# nvme list
/dev/nvme0n1: failed to obtain nvme info: Operation not permitted
```

Running under strace you can see:

```
openat(AT_FDCWD, "/dev/nvme0n1", O_RDONLY) = 3
ioctl(3, NVME_IOCTL_ADMIN_CMD, 0x7fffd9142080) = -1 EACCES (Permission denied)
```

So it's the kernel not allowing you to perform that ioctl even though you have write access on the char device.
There's nothing that LXD can do about this. The only way to sort this would be to convince the NVME maintainers in the kernel that an unprivileged user who's been granted write access to the nvme node device should also be allowed to perform the associated ioctls.

**Comment by stgraber** [comment]
I've also confirmed that making the container privileged does make this work, though with all the usual security concerns that this would bring.

**Comment by stgraber** [comment]
@brauner want to take a quick look at why NVME ioctls are more restricted than matching whoever is allowed to write to the device in the first place? I know having the two linked would also help @morphis with unrelated work, though there may have been some good reason for this.

**Comment by ssampath** [comment]
Thank you.

One thing: In my setup, when I run 'nvme list' I don't see the error message "/dev/nvme0n1: failed to obtain nvme info: Operation not permitted".

However, the exit code is still 255 and running it under strace gives me the same 'Permission denied' issue that you are seeing.

**Comment by ssampath** [comment]
> I've also confirmed that making the container privileged does make this work, though with all the usual security concerns that this would bring.

Confirmed that making it privileged works in my case as well.

One question:  Making the container privileged should be welcoming.  

However, I am curious to know the flip-side and it's implications.

**Comment by stgraber** [comment]
Root in a privileged container is real system root. That's why `nvme` then works properly, but it also means that there are now many ways for processes in that container to escape or perform denial of service attacks on the host.

The only time where privileged containers are fine to use is if whoever or whatever uses/runs in that container can also be trusted with root access to the entire physical system.

**Comment by ssampath** [comment]
That makes sense.  Thank you for the explanation.
