### ISSUE TITLE
Cockpit integration

### ISSUE THREAD

**Issue by polygonalenippel** [lxc/lxd#7742]
https://github.com/cockpit-project/cockpit/issues/8215#issuecomment-549780737

Cockpit is a neat interactive dashboard/admin interface, which also ships with Fedora Server. It is possible to manage systemd-nspawn and docker instances, but, as the comment I linked above states, Cockpit integration is lacking.

My request is: is there any developer who understands the underlying API well enough willing to write an integration?

This would build upon the ease of use of LXD and allow for easier management of linux containers.

**Comment by stgraber** [comment]
Maybe bring it up on https://discuss.linuxcontainers.org where you'll find far more LXD users than here.

The LXD development team itself doesn't have time to integrate LXD in 3rd party projects, so it's not something that we'd do ourselves, though we'd certainly be happy to give pointers and prioritize bugs/missing features for anyone who would.
