### ISSUE TITLE
Can't add a proxy device - error says bind: address already in use but container has none assigned ?

### ISSUE THREAD

**Issue by bmullan** [lxc/lxd#7749]
* Distribution: Ubuntu
 * Distribution version: 20.04.1
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-42-generic
   * LXC version: 4.4
   * LXD version: 4.4
   * Storage backend in use: dir

**# Issue description**

I have one LXD container, host and container are ubuntu 20.04

**Added several proxy devices to cn_name**
**lxd config device add cn_name  myproxyXXX proxy ... etc**

_All was okay at that point._

**Later removed **all of the proxy devices** I had added using** 
lxc config device remove to remove all proxy devices

**I confirmed there are No Proxy devices now install against my cn_name**

$ lxc config device show cn_name
{}

**But now attempting to add a proxy device again to cn_name I get an error:**

lxc config device add cn_name myport443 proxy listen=tcp:0.0.0.0:443 connect=tcp:127.0.0.1:443
Error: Failed to start device "myport443": Error occurred when starting proxy device: Error: Failed to listen on 0.0.0.0:443: listen tcp 0.0.0.0:443: bind: address already in use

**Again, checked that there were NO Proxy Devices configured for cn_name:**

$ lxc config device show cn_name
{}

**_Reloaded snap.lxd and still same problem?_**

**$ lxc info cn_name --show-log**
Name: cn_name
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/08/08 15:51 UTC
Status: Running
Type: container
Profiles: default
Pid: 61788
Ips:
  eth0:	inet	10.107.254.201	vethaf4121b7
  eth0:	inet6	fd42:5daf:90cc:97a6:216:3eff:fe0e:ef83	vethaf4121b7
  eth0:	inet6	fe80::216:3eff:fe0e:ef83	vethaf4121b7
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 509
  Disk usage:
    root: 315.08MB
  CPU usage:
    CPU usage (in seconds): 69
  Memory usage:
    Memory (current): 917.86MB
    Memory (peak): 918.13MB
  Network usage:
    eth0:
      Bytes received: 161.94MB
      Bytes sent: 662.38kB
      Packets received: 11707
      Packets sent: 9642
    lo:
      Bytes received: 5.18MB
      Bytes sent: 5.18MB
      Packets received: 5467
      Packets sent: 5467

Log:

lxc cn_name 20200808155748.804 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1153 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.jitsi"
lxc cn_name 20200808155748.805 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1153 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.jitsi"
lxc cn_name 20200808155748.811 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1573 - No such file or directory - Failed to fchownat(17, memory.oom.group, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )

**$ lxc config show cn_name --expanded**
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20200729)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20200729"
  image.type: squashfs
  image.version: "20.04"
  volatile.base_image: b1900a3455dd9ce8d2a7e77f755d72974803f2d7dd0f06a27724a1aa847a9a24
  volatile.eth0.host_name: vethaf4121b7
  volatile.eth0.hwaddr: 00:16:3e:0e:ef:83
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

**Comment by stgraber** [comment]
This suggests that port 443 on your host is already in use.

Remember that `bind` defaults to `host`, so what you're requesting LXD to do here is listen on port 443 of the host and forward any connections to that onto port 443 of 127.0.0.1 in the container.

**Comment by bmullan** [comment]
@stgraber 
I'll double chk again but as I indicated above I had thse same Device Proxys installed once ok

Removed them

Later tried to reinstall again and got the error

Netstat on the host didn't show any process using the Port and I had no other Containers active at the time.

But I'll double chk everything

Thanks Stephane
