### ISSUE TITLE
Error: Error occurred when starting proxy device: Error: Failed to listen on 0.0.0.0:80: listen tcp 0.0.0.0:80: bind: address already in use

### ISSUE THREAD

**Issue by iPabro** [lxc/lxd#7751]
Hi, I've encountered on this message when stopped my containers (to copy on another server) and tried to launch one of them again.
Full message: Error: Error occurred when starting proxy device: Error: Failed to listen on 0.0.0.0:80: listen tcp 0.0.0.0:80: bind: address already in use
Try `lxc info --show-log nginx` for more info

`lxc info --show-log nginx`
Name: nginx
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/07/18 13:32 UTC
Status: Stopped
Type: container
Profiles: default
Snapshots:
  nginxsnapshot (taken at 2020/08/08 11:03 UTC) (stateless)

Log:

lxc nginx 20200809080001.899 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1153 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.nginx"
lxc nginx 20200809080001.900 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1153 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.nginx"
lxc nginx 20200809080001.901 ERROR    utils - utils.c:lxc_can_use_pidfd:1834 - Kernel does not support pidfds
lxc nginx 20200809080001.905 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1573 - No such file or directory - Failed to fchownat(17, memory.oom.group, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc nginx 20200809080008.111 WARN     network - network.c:lxc_delete_network_priv:3203 - Failed to rename interface with index 2 from "eth0" to its initial name "vethda1b6b95"

`lxc config device show nginx`
http:
  connect: tcp:127.0.0.1:80
  listen: tcp:0.0.0.0:80
  proxy_protocol: "true"
  type: proxy
ssh:
  connect: tcp:127.0.0.1:22
  listen: tcp:0.0.0.0:2576
  type: proxy

`lxc list`

+---------+---------+------+------+-----------+-----------+
|  NAME   |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+---------+---------+------+------+-----------+-----------+
| apache  | STOPPED |      |      | CONTAINER | 1         |
+---------+---------+------+------+-----------+-----------+
| map-map | STOPPED |      |      | CONTAINER | 1         |
+---------+---------+------+------+-----------+-----------+
| mariadb | STOPPED |      |      | CONTAINER | 1         |
+---------+---------+------+------+-----------+-----------+
| nginx   | STOPPED |      |      | CONTAINER | 1         |
+---------+---------+------+------+-----------+-----------+
`netstat -tulpn | grep :80`
tcp6       0      0 :::80                   :::*                    LISTEN      1454/lxd

# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
(cut-off here)
environment:
  addresses:
  - 95.142.44.112:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICKzCCAbGgAwIBAgIRAI9wSCBw9/hKRB3dAaOAsfcwCgYIKoZIzj0EAwMwQTEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEhMB8GA1UEAwwYcm9vdEB2bTM5
    NDYzNi5ldXJvZGlyLnJ1MB4XDTIwMDcxNzE3NTYyN1oXDTMwMDcxNTE3NTYyN1ow
    QTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEhMB8GA1UEAwwYcm9vdEB2
    bTM5NDYzNi5ldXJvZGlyLnJ1MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE/mpeISLA
    d9CAsaNbt5XpFiKHH64rs2oIoJdNb2AwX0zoC28f3jIsJ6YpBheLtuBIFyPvb1Ea
    lO2SwOFdKfmaGGVWXvyFxQRTyPeW7a0fbgXroOHFgEYlkyY5sh4E/pi1o20wazAO
    BgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIw
    ADA2BgNVHREELzAtghN2bTM5NDYzNi5ldXJvZGlyLnJ1hwR/AAABhxAAAAAAAAAA
    AAAAAAAAAAABMAoGCCqGSM49BAMDA2gAMGUCMQCAfJVrhqUQGTg0TnUK+X8mpPsk
    djlVJunS+Jtz2J43VU2RzIkCnmu2kgM9xYJv9d8CMAzUijHKsjLTpELcmMshikPl
    On3WlRhGVte2FOC4kQniyjeoaFA0vrkVvEVK9xEW8Q==
    -----END CERTIFICATE-----
  certificate_fingerprint: bd558115ead17e8f6c220f766d7dc1b7b477ed1f789659f96366414fb1ad10ed
  driver: lxc
  driver_version: 4.0.3
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 4.19.0-9-amd64
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "false"
    seccomp_notify: "true"
  os_name: Debian GNU/Linux
  os_version: "10"
  project: default
  server: lxd
  server_clustered: false
  server_name: vm394636.eurodir.ru
  server_pid: 680
  server_version: "4.4"
  storage: btrfs
  storage_version: 4.15.1

Containers without proxy devices launching successfully

**Comment by stgraber** [comment]
Can you look for any leftover forkproxy processes?

**Comment by iPabro** [comment]
![forkproxy](https://user-images.githubusercontent.com/53886209/89734736-9afcce80-da66-11ea-9a4f-21d5644bb50e.png)
yes, in htop i see forkproxy processes

**Comment by stgraber** [comment]
Okay, so that's a problem...

forkproxy processes are supposed to get my killed when the container is stopped or restarted.

**Comment by stgraber** [comment]
How did you stop the containers?

Using `lxc stop` or `lxc stop --force` or using shutdown/halt/poweroff from within the container?

**Comment by iPabro** [comment]
as I remember, using `lxc stop`.. By the way, when the error appeared, I rebooted server, but no effect.

**Comment by stgraber** [comment]
And your two running forkproxy processes are they for one of the containers you're trying to start now?

**Comment by iPabro** [comment]
yes, and just those two have proxies devices
right side of htop:
![htop-right](https://user-images.githubusercontent.com/53886209/89737703-bb835380-da7b-11ea-9963-f2cc24cde5fd.jpg)


that's bunch of commands I did (maybe something useful):

> lxc list
> lxc stop
> lxc stop apache map-map mariadb nginx
> lxc list
> lxc snapshot
> lxc snapshot apache apachesnapshot
> lxc snapshot map-map map-mapsnapshot
> lxc snapshot mariadb mariadbsnapshot
> lxc snapshot nginx nginxsnapshot
> lxc info nginx
> df
> df -h
> lxc config set
> lxc config set core.https_address 95.142.44.[..cut-off..]
> lxc config set core.trust_password [..cut-off..]
> lxc copy
> lxc profile show default
> lxc move
> lxc
> lxc profile
> lxc profile copy
> lxc profile show
> lxc profile list
> lxc profile
> lxc profile copy
> lxc remote add newvps [..cut-off..]
> lxc copy apache/apachesnapshot newvps:apache
> lxc copy apache/apachesnapsho newvps:apache
> lxc copy apache/apachesnapshot newvps:apache
> lxc device show map-map
> lxc
> lxc profile
> lxc profile list
> lxc profile device
> lxc profile device list
> lxc profile device list apache
> lxc profile device list default
> lxc profile device list apache
> lxc copy apache/apachesnapshot newvps:apache
> lxc profile show apache
> lxc 
> lxc publish
> lxc publish apache
> lxc image list
> lxc image delete 8f51
> lxc image delete
> lxc image delete fbc4c1988f51
> lxc image list
> lxc publish apache/apachesnapshot --alias apache-img
> lxc image list
> lxc image export apache-img
> lxc
> lxc export
> lxc 
> rsync fbc4c1988f51d464e71a0209c9977dd637e8889ab374e177516eacf80b08c676.tar.gz root@62.171.[..cut-off..]:
> scp fbc4c1988f51d464e71a0209c9977dd637e8889ab374e177516eacf80b08c676.tar.gz root@62.171.[..cut-off..]:
> lxc publish map-map --alias map-map-img
> rm -rf fbc4c1988f51d464e71a0209c9977dd637e8889ab374e177516eacf80b08c676.tar.gz 
> lxc image list
> lxc image delete apache-img
> lxc copy map-map newvps:map-map
> lxc copy nginx newvps:nginx
> lxc copy nginx newvps:mariadb
> lxc profile device list default
> lxc profile device list nginx
> lxc profile device list apache
> lxc profile device list mariadb
> lxc profile device list map-map
> lxc profile device show
> lxc profile device show map-map
> lxc config device show nginx
> lxc config device show apache
> lxc storage volume move mypool/map-map newvps:default/map-map
> lxc storage list
> lxc storage volume
> lxc storage volume move
> lxc storage volume copy
> lxc storage volume 
> lxc storage volume list
> lxc storage volume list mypool
> lxc storage volume move default/map-map newvps:default/map-map
> lxc list
> lxc storage volume show default/map-map
> lxc storage volume list default
> lxc storage volume 
> lxc storage volume show
> lxc storage volume show default map-map
> lxc storage volume list default
> lxc storage volume 
> lxc storage volume get
> lxc storage volume get default map-map
> lxc storage volume copy default/map-map newvps:default/map-map
> lxc list
> lxc storage volume copy default/apache newvps:default/apache
> lxc copy apache newvps:apache
> lxc copy map-map newvps:map-map
> sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
> dd if=tempfile of=/dev/null bs=1M count=1024
> /sbin/sysctl -w vm.drop_caches=3
> dd if=tempfile of=/dev/null bs=1M count=1024
> sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
> lxc exec map-map bash
> lxc start map-map
> lxc info --show-log map-map
> rm tempfile 
> rm -rf tempfile 
> lxc start map-map
> lxc info --show-log map-map
> lxc start nginx
> netstat -tulpn | grep :80
> netstat -tulpn
> lxc start nginx
> systemctl status lxd
> systemctl status lxc
> systemctl status snapd
> systemctl restart snapd
> lxc start nginx
> lxc list
> systemctl status snapd
> lxc list
> netstat -tulpn
> lxc start nginx
> lxc info --show-log nginx
> lxc config show --expanded nginx
> lxc start nginx
> netstat -tulpn | grep :80
> sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
> cat /sys/block/sda/queue/rotational
> lxc list
> lxc start apache
> lxc list
> lxc start map-map
> lxc start mariadb
> lxc start nginx
> lxc list
> restart
> reboot
> lxc list
> lxc start nginx
> netstat -tulpn
> lxc start nginx
> lxc start map-map
> lxc list
> lxc stop --all
> lxc start nginx
> lxc config device show mariadb
> lxc copy mariadb newvps:mariadb
> lxc config device show map-map
> lxc stop --all
> lxc start nginx
> lxc list
> lxc info --show-log nginx
> uname -r
> lxc start nginx
> lxc config device show nginx
> lxc list
> netstat -tulpn
> netstat -tulpn | grep 80
> netstat -tulpn | grep :80
> lxd --version
> lxc --version
> uname -r
> lxc info
> lxc info --show-log nginx
> lxc start map-map
> netstat -tulpn | grep :2575
> htop
> pwd
> ls -l
> rm -rf tempfile 
> ls -la
> cat .bash_history

**Comment by stgraber** [comment]
Can you show `cat /var/snap/lxd/common/lxd/logs/lxd.log`?
I wonder if it's maybe a startup failure that left those around?

Can you also confirm that killing those processes and start the container again works?

**Comment by iPabro** [comment]
No, it's not working after killing processes forkproxy. As I understand, these processes launched even after fail attempts to start containers. 
`Error: Error occurred when starting proxy device, please look in /var/snap/lxd/common/lxd/logs/nginx/proxy.http.log
Try `lxc info --show-log nginx` for more info
`
`cat /var/snap/lxd/common/lxd/logs/lxd.log`
> t=2020-08-09T09:34:01+0300 lvl=info msg="LXD 4.4 is starting in normal mode" path=/var/snap/lxd/common/lxd
> t=2020-08-09T09:34:01+0300 lvl=info msg="Kernel uid/gid map:"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - u 0 0 4294967295"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - g 0 0 4294967295"
> t=2020-08-09T09:34:01+0300 lvl=info msg="Configured LXD uid/gid map:"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - u 0 1000000 1000000000"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - g 0 1000000 1000000000"
> t=2020-08-09T09:34:01+0300 lvl=info msg="Kernel features:"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - netnsid-based network retrieval: no"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - pidfds: no"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - uevent injection: yes"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - seccomp listener: no"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - seccomp listener continue syscalls: no"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - unprivileged file capabilities: yes"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - cgroup layout: hybrid"
> t=2020-08-09T09:34:01+0300 lvl=warn msg=" - Couldn't find the CGroup hugetlb controller, hugepage limits will be ignored"
> t=2020-08-09T09:34:01+0300 lvl=warn msg=" - Couldn't find the CGroup memory swap accounting, swap limits will be ignored"
> t=2020-08-09T09:34:01+0300 lvl=info msg=" - shiftfs support: disabled"
> t=2020-08-09T09:34:01+0300 lvl=info msg="Initializing local database"
> t=2020-08-09T09:34:02+0300 lvl=info msg="Starting /dev/lxd handler:"
> t=2020-08-09T09:34:02+0300 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
> t=2020-08-09T09:34:02+0300 lvl=info msg="REST API daemon:"
> t=2020-08-09T09:34:02+0300 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/snap/lxd/common/lxd/unix.socket
> t=2020-08-09T09:34:02+0300 lvl=info msg=" - binding TCP socket" socket=95.142.44.112:8443
> t=2020-08-09T09:34:02+0300 lvl=info msg="Initializing global database"
> t=2020-08-09T09:34:02+0300 lvl=info msg="Firewall loaded driver \"xtables\""
> t=2020-08-09T09:34:02+0300 lvl=info msg="Initializing storage pools"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Initializing daemon storage mounts"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Initializing networks"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Generated temporary MAC for bridge interface" driver=bridge hwaddr=00:16:3e:48:d6:33 network=lxdbr0
> t=2020-08-09T09:34:03+0300 lvl=info msg="Pruning leftover image files"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Done pruning leftover image files"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Loading daemon configuration"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Pruning expired images"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Done pruning expired images"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Done pruning expired instance backups"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Updating instance types"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Done updating instance types"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Updating images"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Done updating images"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Expiring log files"
> t=2020-08-09T09:34:03+0300 lvl=info msg="Done expiring log files"
> t=2020-08-09T09:34:04+0300 lvl=info msg="Starting container" action=start created=2020-07-18T16:33:01+0300 ephemeral=false name=apache project=default stateful=false used=2020-08-09T09:30:47+0300
> t=2020-08-09T09:34:04+0300 lvl=info msg="Started container" action=start created=2020-07-18T16:33:01+0300 ephemeral=false name=apache project=default stateful=false used=2020-08-09T09:30:47+0300
> t=2020-08-09T09:34:04+0300 lvl=info msg="Starting container" action=start created=2020-07-18T16:33:23+0300 ephemeral=false name=mariadb project=default stateful=false used=2020-08-09T09:31:24+0300
> t=2020-08-09T09:34:05+0300 lvl=info msg="Started container" action=start created=2020-07-18T16:33:23+0300 ephemeral=false name=mariadb project=default stateful=false used=2020-08-09T09:31:24+0300
> t=2020-08-09T09:34:19+0300 lvl=info msg="Starting container" action=start created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:31:30+0300
> t=2020-08-09T09:34:29+0300 lvl=info msg="Stopping container" action=stop created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:31:30+0300
> t=2020-08-09T09:34:30+0300 lvl=info msg="Stopped container" action=stop created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:31:30+0300
> t=2020-08-09T09:35:12+0300 lvl=info msg="Starting container" action=start created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:34:19+0300
> t=2020-08-09T09:35:18+0300 lvl=info msg="Stopping container" action=stop created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:34:19+0300
> t=2020-08-09T09:35:19+0300 lvl=info msg="Stopped container" action=stop created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:34:19+0300
> t=2020-08-09T09:35:27+0300 lvl=info msg="Starting container" action=start created=2020-08-06T07:11:59+0300 ephemeral=false name=map-map project=default stateful=false used=2020-08-09T09:31:11+0300
> t=2020-08-09T09:35:37+0300 lvl=info msg="Stopping container" action=stop created=2020-08-06T07:11:59+0300 ephemeral=false name=map-map project=default stateful=false used=2020-08-09T09:31:11+0300
> t=2020-08-09T09:35:38+0300 lvl=info msg="Stopped container" action=stop created=2020-08-06T07:11:59+0300 ephemeral=false name=map-map project=default stateful=false used=2020-08-09T09:31:11+0300
> t=2020-08-09T09:43:40+0300 lvl=info msg="Shutting down container" action=shutdown created=2020-07-18T16:33:01+0300 ephemeral=false name=apache project=default timeout=-1s used=2020-08-09T09:34:04+0300
> t=2020-08-09T09:43:40+0300 lvl=info msg="Shutting down container" action=shutdown created=2020-07-18T16:33:23+0300 ephemeral=false name=mariadb project=default timeout=-1s used=2020-08-09T09:34:04+0300
> t=2020-08-09T09:43:42+0300 lvl=info msg="Shut down container" action=shutdown created=2020-07-18T16:33:01+0300 ephemeral=false name=apache project=default timeout=-1s used=2020-08-09T09:34:04+0300
> t=2020-08-09T09:43:44+0300 lvl=info msg="Shut down container" action=shutdown created=2020-07-18T16:33:23+0300 ephemeral=false name=mariadb project=default timeout=-1s used=2020-08-09T09:34:04+0300
> t=2020-08-09T09:43:52+0300 lvl=info msg="Starting container" action=start created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:35:12+0300
> t=2020-08-09T09:43:58+0300 lvl=info msg="Stopping container" action=stop created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:35:12+0300
> t=2020-08-09T09:43:59+0300 lvl=info msg="Stopped container" action=stop created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:35:12+0300
> t=2020-08-09T10:09:56+0300 lvl=info msg="Starting container" action=start created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:43:52+0300
> t=2020-08-09T10:10:02+0300 lvl=info msg="Stopping container" action=stop created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:43:52+0300
> t=2020-08-09T10:10:03+0300 lvl=info msg="Stopped container" action=stop created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T09:43:52+0300
> t=2020-08-09T10:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T10:34:03+0300 lvl=info msg="Done pruning expired instance backups"
> t=2020-08-09T11:00:01+0300 lvl=info msg="Starting container" action=start created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T10:09:56+0300
> t=2020-08-09T11:00:08+0300 lvl=info msg="Stopping container" action=stop created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T10:09:56+0300
> t=2020-08-09T11:00:08+0300 lvl=info msg="Stopped container" action=stop created=2020-07-18T16:32:15+0300 ephemeral=false name=nginx project=default stateful=false used=2020-08-09T10:09:56+0300
> t=2020-08-09T11:16:43+0300 lvl=info msg="Sending top level 404" url=/currentsetting.htm
> t=2020-08-09T11:17:30+0300 lvl=info msg="Starting container" action=start created=2020-08-06T07:11:59+0300 ephemeral=false name=map-map project=default stateful=false used=2020-08-09T09:35:27+0300
> t=2020-08-09T11:17:37+0300 lvl=info msg="Stopping container" action=stop created=2020-08-06T07:11:59+0300 ephemeral=false name=map-map project=default stateful=false used=2020-08-09T09:35:27+0300
> t=2020-08-09T11:17:37+0300 lvl=info msg="Stopped container" action=stop created=2020-08-06T07:11:59+0300 ephemeral=false name=map-map project=default stateful=false used=2020-08-09T09:35:27+0300
> t=2020-08-09T11:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T11:34:03+0300 lvl=info msg="Done pruning expired instance backups"
> t=2020-08-09T12:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T12:34:03+0300 lvl=info msg="Done pruning expired instance backups"
> t=2020-08-09T13:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T13:34:03+0300 lvl=info msg="Done pruning expired instance backups"
> t=2020-08-09T14:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T14:34:03+0300 lvl=info msg="Done pruning expired instance backups"
> t=2020-08-09T15:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T15:34:03+0300 lvl=info msg="Updating images"
> t=2020-08-09T15:34:03+0300 lvl=info msg="Done pruning expired instance backups"
> t=2020-08-09T15:34:03+0300 lvl=info msg="Done updating images"
> t=2020-08-09T15:34:06+0300 lvl=info msg="Downloading image" alias=ubuntu/bionic/amd64 server=https://images.linuxcontainers.org
> t=2020-08-09T15:34:14+0300 lvl=info msg="Image downloaded" alias=ubuntu/bionic/amd64 server=https://images.linuxcontainers.org
> t=2020-08-09T16:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T16:34:03+0300 lvl=info msg="Done pruning expired instance backups"
> t=2020-08-09T17:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T17:34:03+0300 lvl=info msg="Done pruning expired instance backups"
> t=2020-08-09T18:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T18:34:03+0300 lvl=info msg="Done pruning expired instance backups"
> t=2020-08-09T19:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T19:34:03+0300 lvl=info msg="Done pruning expired instance backups"
> t=2020-08-09T20:34:03+0300 lvl=info msg="Pruning expired instance backups"
> t=2020-08-09T20:34:03+0300 lvl=info msg="Done pruning expired instance backups"

**Comment by iPabro** [comment]
If you want I can give you credentials to the server

**Comment by stgraber** [comment]
Sure, that'd be fastest to figure it out.

https://github.com/stgraber.keys

**Comment by iPabro** [comment]
hope, I did it right: `root@95.142.44.112` default port

**Comment by stgraber** [comment]
Taking a look now, access works and I do see the bad behavior, not sure I'll figure it out tonight though, may have to try again tomorrow morning.

**Comment by stgraber** [comment]
```
/dev/sda1       119G  116G     0 100% /
```

This may be causing some issues.

**Comment by stgraber** [comment]
I've used a bit of trickery to shrink those the two storage pools on your system, freeing up a lot of disk space.

**Comment by stgraber** [comment]
Then after killing the leftover forkproxy processes, things behave properly:

```
root@vm394636:~# lxc start map-map nginx
root@vm394636:~# 
```

So long story short, the issue was your system running out of disk space.
You have two pools, one with a 20GB limit, another one with a 100GB limit. The total capacity of your server's harddisk is 125GB.

This really doesn't give you much room for system files and when your disk got completely full, it was preventing the forkproxy log files from being written, making them stay empty and causing the startup failures.

One thing we should do however is kill forkproxy instances when they fail that way rather than leave them behind.

**Comment by stgraber** [comment]
Oh, I see, we would normally have done a PID file and then used that to track the process, but we can't because there's no space for a PID file :)

**Comment by iPabro** [comment]
Yes, there was a problem with free space, but I thougth a little of free space should be enough. Thank you for your help, now all lxc's launching successfully!)
