### ISSUE TITLE
Documetation usability bug - 

### ISSUE THREAD

**Issue by tim-seoss** [lxc/lxd#7760]
The online docs e.g. https://lxd.readthedocs.io/en/stable-4.0/instances/#keyvalue-configuration currently have some formatting issues which makes the instance key/value configuration section very difficult to read.

The key value information is presented as a large table, and the full width of it cannot be viewed horizontally (a horizontal scroll-bar appears at the bottom of the table) zooming out to reduce the text size in an effort to increase the visibility, just squashes the table onto the left side of the web page rather than making more of it visible (tested with Firefox 79 and Chrome 84 on a 16:9 15" 4k display).

**Comment by stgraber** [comment]
Yeah, the bad style is one of the reason why we've moved away from readthedocs.io.

https://linuxcontainers.org/lxd/docs/master/instances renders a fair bit better here and is where we've moved the documentation for the main branch and will soon follow with the stable branches (I'll add 4.0 now as it has the needed metadata).

Horizontal scrolling is likely to be a necessary evil though as wrapping makes it even harder to read and the alternative would be a paragraph per key which makes it almost impossible to search.

**Comment by tim-seoss** [comment]
OK, that's better thanks.

At least I can fit it all on screen by zooming out (although that's not viable for lower resolution displays).  If there were some way to optionally/temporarily hide the left and right contents bars, that would make this sort of wide table more usable for more people.

It's a tricky problem, but in the case of this particular table, the layout forces a lot of white-space in the centre of the table.

If it is possible to wrap only certain columns (or limit the max height of each row), then the columns that usually contain a single word, but might contain two words (e.g. the "Default"  "Live Update" "Condition" columns), could shrink horizontally, and claw back a lot of dead whitespace (a key thing for many users would be to simultaneously be able to read the "description" and "key" text visible at the same time.

If that's not possible currently, please let me know and I'll suggest it at https://github.com/canonical-web-and-design/vanilla-framework to see what they think.

**Comment by stgraber** [comment]
We'd need the various columns to have a specific class so we can then change the behavior in our custom CSS, currently that's not the case and may be more of a limitation of python-markdown

**Comment by stgraber** [comment]
https://linuxcontainers.org/lxd/docs/stable-4.0/ has stable-4.0 now
