### ISSUE TITLE
Github popup when opening first new issue: [contributing guidelines] link doen't follow symlink

### ISSUE THREAD

**Issue by ackalker** [lxc/lxd#7771]
(deliberately not following the template as I believe this is a meta-issue.)
When I tried to create a new issue for this project on Github, I was greeted with a popup whose text starts with:
```
It looks like this is your first time opening an issue in this project!

Be sure to review the [contributing guidelines](https://github.com/lxc/lxd/blob/master/contributing.md) and [code of conduct](https://github.com/lxc/lxd/blob/master/.github/CODE_OF_CONDUCT.md).
```
(links in Markdown syntax)

When I follow the link [contributing guidelines], I end up on a page which among other things states that the object is a "symbolic link" followed by a single line of text: "doc/contributing.md".
My tentative conclusion is that Github's "first contribution" popup doesn't handle symlinks correctly.

**Comment by ackalker** [comment]
The commit which moved the CONTRIBUTING.md document: f4dcf512073811bef6fa7eea30fb02e9d8bc179b

**Comment by stgraber** [comment]
Yeah, we have reported this mis-behavior to Github before and there is an issue about it in the private OSS maintainers project with Github.

It's certainly a bit annoying but moving it to the root would then break our online documentation which to us matters more than Github's behavior.

**Comment by stgraber** [comment]
(Annoyingly Github also follows symlinks, sometimes... so it's not a very consistent experience)
