### ISSUE TITLE
lxc-0.9.0 ipv6 interface details is not shown using ifconfig

### ISSUE THREAD

**Issue by vikikumar** [lxc/lxd#7780]
Hi,

I am using lxc-0.9.0 and configured a bridged ipv6 interface in my lxc configuration as below

lxc.network.type  = veth
lxc.network.link  = br_external
lxc.network.name  = eth2
lxc.network.flags = up
lxc.network.hwaddr = 4a:49:43:49:79:bf
lxc.network.ipv6 = 2003:db8:1:0:214:1234:fe0b:3597
lxc.network.ipv6.gateway = fe80::210:20ff:fe30:4050

The container is not throwing error if I used the above ip configuration during initialzation(As when given addresses in wrong format, it throwed me error and the container failed to launch). 
But when trying to list using ifconfig(ifconfig -a) inside the container, it is not showing the eth2 interface

I am not sure if I am missing something?

Please need advise. Thank you.

**Comment by stgraber** [comment]
This is the wrong project, you're not using LXD.

LXC 0.9 is over 7 years old and very much unsupported at this point.
The most likely issue you're running into though is that your container is simply resetting its network config on boot.

When using such preconfigured networking, you must make sure that nothing you run in your container will attempt to configure networking on boot.
