### ISSUE TITLE
Unable to build LXD master branche

### ISSUE THREAD

**Issue by aagt-prog** [lxc/lxd#7784]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 18.04

# Issue description

On build operation we have an error:
package vbom.ml/util/sortorder: unrecognized import path "vbom.ml/util/sortorder": reading https://vbom.ml/util/sortorder?go-get=1: 503 Service Unavailable
make: *** [Makefile:19: default] Error 1

I think it's a dependency error and web site vbom.ml realy say 503 status code. Web site look's as down (as a last week). How can i fix this issue?

# Steps to reproduce

root@anton-notebook:/opt/go/src/github.com/lxc/lxd# export CGO_CFLAGS="-I/opt/go/deps/sqlite/ -I/opt/go/deps/libco/ -I/opt/go/deps/raft/include/ -I/opt/go/deps/dqlite/include/"
root@anton-notebook:/opt/go/src/github.com/lxc/lxd# export CGO_LDFLAGS="-L/opt/go/deps/sqlite/.libs/ -L/opt/go/deps/libco/ -L/opt/go/deps/raft/.libs -L/opt/go/deps/dqlite/.libs/"
root@anton-notebook:/opt/go/src/github.com/lxc/lxd# export LD_LIBRARY_PATH="/opt/go/deps/sqlite/.libs/:/opt/go/deps/libco/:/opt/go/deps/raft/.libs/:/opt/go/deps/dqlite/.libs/"
root@anton-notebook:/opt/go/src/github.com/lxc/lxd# export CGO_LDFLAGS_ALLOW="-Wl,-wrap,pthread_create"
root@anton-notebook:/opt/go/src/github.com/lxc/lxd# make
go get -t -v -d ./...
package vbom.ml/util/sortorder: unrecognized import path "vbom.ml/util/sortorder": reading https://vbom.ml/util/sortorder?go-get=1: 503 Service Unavailable
make: *** [Makefile:19: default] Error 1

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
I checked just now and this is working OK, so it suggests the 503 you received was just a temporary network issue, can you retry and let us know if it works.

**Comment by aagt-prog** [comment]
When i'm try to open url in browser. I see message:
Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.

Try to get url by curl:
# curl -I https://vbom.ml/util/sortorder?go-get=1
HTTP/2 503 
date: Tue, 18 Aug 2020 08:47:05 GMT
content-type: text/html
set-cookie: __cfduid=db8b3b7f56ead4945b939d938f55f7f2b1597740425; expires=Thu, 17-Sep-20 08:47:05 GMT; path=/; domain=.vbom.ml; HttpOnly; SameSite=Lax
cf-cache-status: BYPASS
cf-request-id: 04a259395800007b738ca3f200000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5c4a5e3bc9f97b73-DME

On clean ubuntu just now i'm take same error:
# make
go get -t -v -d ./...
package vbom.ml/util/sortorder: unrecognized import path "vbom.ml/util/sortorder": reading https://vbom.ml/util/sortorder?go-get=1: 503 Service Unavailable
make: *** [Makefile:19: default] Error 1

**Comment by aagt-prog** [comment]
> I checked just now and this is working OK, so it suggests the 503 you received was just a temporary network issue, can you retry and let us know if it works.

Maybe this package is cached by you? On clean ubuntu i have this error now.

**Comment by tomponline** [comment]
@aagt-prog what version of go are you using? LXD requires go >= 1.13

**Comment by aagt-prog** [comment]
> @aagt-prog what version of go are you using? LXD requires go >= 1.13 (https://linuxcontainers.org/lxd/docs/master/requirements)

go version 1.15

**Comment by tomponline** [comment]
@aagt-prog I've reproduced it in empty container, although earlier running `go get -u vbom.ml/util/sortorder` worked OK, deleting it entirely and re-running produces the issue.

The package itself is still available here https://github.com/fvbommel/util but I suspect we'll need to vendor it or switch to another package.

**Comment by tomponline** [comment]
@stgraber how would you like to proceed?

**Comment by tomponline** [comment]
@aagt-prog in the meantime you can resolve this by doing:

```bash
cd $GOPATH/src
mkdir vbom.ml
cd vbom.ml
git clone https://github.com/fvbommel/util.git
```

**Comment by fvbommel** [comment]
The package previously named `vbom.ml/util/sortorder` is now available again as `github.com/fvbommel/sortorder`, see fvbommel/util#7.

My apologies for the inconvenience.
