### ISSUE TITLE
Volume resize: false positive failure

### ISSUE THREAD

**Issue by mkhon** [lxc/lxd#7788]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.03
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-23-generic
   * LXC version: 4.0.4
   * LXD version: 4.0.4
   * Storage backend in use: lvm

# Issue description

Seems there is a false positive failure when container volume is downsized:
```
root@hn3:~# lxc config device set jenkins root size=1000GB                
Error: Failed to update device "root": Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity                                           
/lost+found not found.  Create? yes                                        
                                                                  
Pass 4: Checking reference counts                                                      
Pass 5: Checking group summary information                       
                                                                                               
/dev/lxd/containers_jenkins: ***** FILE SYSTEM WAS MODIFIED *****
/dev/lxd/containers_jenkins: 3179294/121361888 files (0.1%!n(MISSING)on-contiguous), 121575693/488282112 block
s: Failed to run: e2fsck -f -y /dev/lxd/containers_jenkins: e2fsck 1.44.1 (24-Mar-2018)
root@hn3:~# lxc start jenkins                                                                       
root@hn3:~#
```

# Steps to reproduce

 1. Downsize container root disk: the operation will fail with the error message above and the container will remain stopped
 2. Start the container - it starts properly

**Comment by stgraber** [comment]
@tomponline can you take a look at this one?

**Comment by tomponline** [comment]
@stgraber will do, looks like fsck (which is a requirement to be run before shrinking a filesystem) has modified the system and is returning a non-zero error code. I will see if that error code is different from a genuine error, although given the risks with automatically fixing filesystems, I may be tempted to see if there is a flag we can pass to just bail out and don't modify the filesystem at all, leaving that as a task for the admin to do.

**Comment by tomponline** [comment]
OK so according to manpage of e2fsck the exit codes are:

```
       The exit code returned by e2fsck is the sum of the following conditions:
            0    - No errors
            1    - File system errors corrected
            2    - File system errors corrected, system should
                   be rebooted
            4    - File system errors left uncorrected
            8    - Operational error
            16   - Usage or syntax error
            32   - E2fsck canceled by user request
            128  - Shared library error
```

So if we check for 0 and 1 then that should be fine.

**Comment by tomponline** [comment]
Reproduced the issue:

```
lxc launch images:ubuntu/focal c1 -s lvm
rm -Rvf /var/lib/lxd/storage-pools/lvm/containers/c1/lost+found/
lxc stop c1
lxc config device set c1 root size=8GB
Error: Failed to update device "root": Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
/lost+found not found.  Create? yes

Pass 4: Checking reference counts
Pass 5: Checking group summary information

/dev/lvm/containers_c1: ***** FILESYSTEM WAS MODIFIED *****
/dev/lvm/containers_c1: 18014/610800 files (0.1%!n(MISSING)on-contiguous), 177149/2442240 blocks: Failed to run: e2fsck -f -y /dev/lvm/containers_c1: e2fsck 1.45.5 (07-Jan-2020)
```

**Comment by tomponline** [comment]
@mkhon by the way, if you try to shrink the disk again it should succeed the 2nd time as e2fsck has fixed the missing `lost+found` directory.

**Comment by mkhon** [comment]
1) Just doing "lxc start" helps.

2) Do you think exit code 2 is also legitimate?

**Comment by tomponline** [comment]
@mkhon mmm perhaps.

**Comment by tomponline** [comment]
Actually I think I won't add that now as we unmount the volume first before running e2fsck and that exit code shouldn't occur unless its mounted.
