### ISSUE TITLE
[Feature Request] Prompt before remapping

### ISSUE THREAD

**Issue by toby63** [lxc/lxd#7810]
When LXD does not find the kernel module shiftfs it automatically disables the shiftfs option and during container start, starts remapping the container.

I would like to see two things:

1. Warn if shiftfs gets disabled and why (kernel module not found).
2. Ask before remapping the container.

**Comment by stgraber** [comment]
1) Is advertised in `lxc info`. We don't know why but we do report if the system supports it or not.
2) Can't be done. There is no way for the server to interactively ask the client. This also wouldn't work for any case where the server itself is starting/stopping instances.

For 2), we do have a config key which prevents remapping though, setting it to true would prevent the instance from ever starting in such a scenario.

**Comment by stgraber** [comment]
`security.protection.shift` would be the key in question.

**Comment by toby63** [comment]
>     1. Is advertised in `lxc info`. We don't know why but we do report if the system supports it or not.

I saw no message anywhere, it is also not very useful if it's just in the logs.
Logs are imo for investigations after something happened and prevent nothing.

>     2. Can't be done. There is no way for the server to interactively ask the client. This also wouldn't work for any case where the server itself is starting/stopping instances.

Well maybe there should be such an option, there are many cases in which user interaction might be helpful, for example whenever certain devices, networks etc. are not available.

And in case of automation, the interaction could be disabled.

> For 2), we do have a config key which prevents remapping though, setting it to true would prevent the instance from ever starting in such a scenario.

It reads: 

`security.protection.shift - Prevents the instance's filesystem from being uid/gid shifted on startup`
So the container is prevented from using shiftfs? Or is it now protected against a change of uids (aka "remapping")?

**Comment by stgraber** [comment]
It won't log a warning or anything, not having shiftfs isn't a bug, it's a feature which is used opportunistically.
LXD itself doesn't even know if a container was using shiftfs before. It can't distinguish a privileged container being turned unprivileged from a container which used shiftfs being started on a non-shiftfs system.

`lxc info` as I mentioned does report whether the system is capable of using shiftfs (as it does all other relevant kernel features).

`security.protection.shift` as mentioned prevents shifting on startup. That means that when the container is started, if a shift needs to happen and this is set to true, then the startup will fail.

**Comment by toby63** [comment]
> It won't log a warning or anything, not having shiftfs isn't a bug, it's a feature which is used opportunistically.

Ok, but the remapping is still annoying without any warning and prompt.
But I read your oppinion as `wontfix`.

> security.protection.shift as mentioned prevents shifting on startup. That means that when the container is started, if a shift needs to happen and this is set to true, then the startup will fail.

Confusing explanation, but from your first comment:
> For 2), we do have a config key which prevents remapping though

I assume my second option is correct:
`[it is] now protected against a change of uids (aka "remapping")`

You still could edit the explanation in the docs, so everyone can understand what it means exactly.
`Prevents the instance's filesystem from being uid/gid shifted on startup`
Because imo this can be missunderstood as disabling shifting, or shiftfs functionality etc.
