### ISSUE TITLE
GPU information with nvidia.runtime

### ISSUE THREAD

**Issue by nehz** [lxc/lxd#7840]
* Distribution: Debian 10 Buster
 * Kernel version: 5.7.0-0.bpo.2-amd64
 * LXD version: 4.4 (via snap)
 * Storage backend in use: ZFS

# Issue description

Using `nvidia.runtime="true"` does not seem to mount the `gpus` in `/proc/driver/nvidia/gpus` which contains information about the GPUs

# Steps to reproduce

 1. Use `ubuntu:focal image`
 2. Add gpu device
 3. Use `nvidia.runtime="true"` and `nvidia.driver.capabilities: all`

**Comment by stgraber** [comment]
I'll take a look at this one. This is almost certainly kernel behavior that we can't really do anything about (especially given the nvidia driver is proprietary) but I'd like to see it for myself :)

**Comment by stgraber** [comment]
Hmm, so this appears to be deliberate and done by the nvidia-container tools.

```
root@u1:~# grep /proc/driver /proc/mounts 
tmpfs /proc/driver/nvidia tmpfs rw,nosuid,nodev,noexec,relatime,mode=555,uid=1000000,gid=1000000 0 0
```

You can restore the normal entries with `umount -l /proc/driver/nvidia`

I'm not sure exactly why nvidia made the container logic do this, but it appears to be somehow deliberate?

**Comment by stgraber** [comment]
If you want to file an issue about this behavior, https://github.com/NVIDIA/libnvidia-container should be a good place for it.
I've checked that we have no code that would cause this, so it's the call to `nvidia-container-cli configure` which is triggering this behavior.

**Comment by nehz** [comment]
Awesome thanks for looking into it
