### ISSUE TITLE
Proxy for nginx php xml content shift

### ISSUE THREAD

**Issue by Tampa** [lxc/lxd#7845]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 kts
 * The output of "lxc info" or if that fails:
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 167.114.211.140:8443
  - '[2607:5300:60:7a8c::]:8443'
  - 10.195.62.1:8443
  - '[fd42:2a46:1e57:d16::1]:8443'
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.19-ovh-xxxx-std-ipv6-64
  server: lxd
  server_pid: 27391
  server_version: 3.0.3
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: ns516468
  project: ""

# Issue description

Setup lxd container to run nginx serving xml data via php. Proxy port 80 through to the WAN, but output is shifted.
Instead of providing proper xml output the result is shifted with a newline before content and the last char is cut off.
Same exact code running on the host works perfectly fine using the same nginx and php setup.

# Steps to reproduce

- Create lxd container
- add device to proxy port 80
- Install nginx with php in container
- Create php script to serve xml data with proper headers

# Information to attach

XML Parsing Error: XML or text declaration not at start of entity
Location: http://example.com/xml.php
Line Number 2, Column 1:
<?xml version="1.0" encoding="utf-8"?>
^

**Comment by stgraber** [comment]
Looks like you're using LXD 3.0.3 which had a very limited and somewhat buggy implementation of the proxy logic.
Any chance you could upgrade to LXD 4.0 as there is a good chance this will fix the problem.

**Comment by Tampa** [comment]
Annoyingly the provider only offers Bionic so I can't install from snap as snap itself won't install due to kernel missing patch. I have a test environment on Focal, am about to test it there to see if it still does it. If there is a ppa for Bionic with version 4 I'd happily test it there as well.

I somewhat suspect it really is just this version causing the issue, but I couldn't find concrete info on this either so I kept trying for hours until I had exhausted all other variables. Guess this serves as resource for others in the same boat :)

Will update when I get the Focal environment setup.

**Comment by stgraber** [comment]
That's odd, what kernel is your provider running on bionic?

bionic should be on 4.15 at minimum and I know snapd happily works at least as far back as 4.4 so a bit confused as to why this isn't a viable option for you.

**Comment by Tampa** [comment]
snap install lxd --channel=4.0/stable
error: system does not fully support snapd: cannot mount squashfs image using "squashfs": mount:
       /tmp/sanity-mountpoint-998328098: unknown filesystem type 'squashfs'.

Haven't found conclusive results as to what causes this other than the kernel not being up to the task to run snap properly, but it is 4.15.

**Comment by Tampa** [comment]
I just finished setup on Focal and installed everything just like I did on bionic and I see no shifted output and the basic return is also not cutoff in the end either. So this really must be the outdated LXD version.

Installed on Focal via snap LXD 4.4 and the container config being the same, I also tried ppa for php and nginx to get the latest version there, but no matter which php or nginx I install the output remains working as it should. The variable is LXD and distro version and as both systems natively run the code with proper code that leaves LXD as the culprit.

**Comment by stgraber** [comment]
Ok, that's good to know. We'll be closing this issue as LXD 3.0.x is in security-only mode at this point. It's worth noting that we do have a few proxy fixes in the stable-3.0 branch which will be included in an upcoming 3.0.5 release, so this may still be fixed there.

As for running 4.0 on bionic, this should definitely work fine. I suspect you're getting this `squashfs` error because you're running an out of date kernel, have installed the latest update but not rebooted on it. When this happens, it's possible that you have already removed the package containing the kernel modules for your running kernel and so are unable to load the module.

If that's an option, make sure you have all update applied and reboot your system on the latest 4.15 kernel, this should sort it out.

**Comment by Tampa** [comment]
Think the reason for this is the provider being OVH, which haven't even bothered to update their mirrors to focal at this point and it seems their custom kernel is missing some parts, which means my best option is to bother them to get their act together.

I don't really want to spend the effort to compile a kernel for this potentially breaking other hardware compatibility so I will just wait and see. I suppose this ticket now serves as a resource for anyone that comes across this issue as I could not find anything in my search.

**Comment by stgraber** [comment]
Hmm, I wonder if you could just switch to the official Ubuntu repositories and get the regular 4.15.

I've also been using OVH extensively for my servers (in fact linuxcontainers.org and some of our image servers run there), but never used their image of Ubuntu, instead getting the server into rescue mode or using IPMI KVM (when available) and then performing a clean stock Ubuntu Server install from there.

**Comment by Tampa** [comment]
I switched the server into prod so can't do that at the moment, but if OVH continues to lack behind on updating to focal I may have to switch to mainline. Fact I couldn't go up to focal still bothers me greatly with ubuntu not really backporting anything bionic is a minefield of outdated software that does not make it fun to setup and use. Good to know that this is an option though, you never know what custom kernels are built for, if it is just to slap their own brand on it or to ensure hardware compat.
