### ISSUE TITLE
lxc config device add:  wrong usage

### ISSUE THREAD

**Issue by melato** [lxc/lxd#7851]
snap version:  lxd     4.4          16926  latest/stable  canonical

# Issue description

The usage for "lxc config device add" incorrectly mentions that it can add a device to an instance or a profile.
The way to add a device to a profile is with another command:  lxc profile device add

Steps to reproduce:
lxc config device add -h

Result:  The help mentions:

```
Description:
  Add devices to instances or profiles
 
Usage:
  lxc config device add [<remote>:]<instance|profile> <device> <type> [key=value...] [flags]


```
This couldn't work because what if I have an instance and a profile with the same name?  Which would it choose?
I tried it with an existing profile, and it gave me a "not found" error.
-----------------

The help should show:

```
Description:
  Add devices to instances
 
Usage:
  lxc config device add [<remote>:]<instance> <device> <type> [key=value...] [flags]

```

**Comment by stgraber** [comment]
Yeah, this is because we use the same functions to process instance and profile devices, though I may have figured out a way to still have the help differ somehow, giving that a go now.
