### ISSUE TITLE
zfs error:  cannot receive: local origin for clone does not exist

### ISSUE THREAD

**Issue by melato** [lxc/lxd#7854]
I cannot use zfs send/receive to copy the LXD ZFS dataset in certain cases after copying and deleting containers.

This must be a ZFS bug, but I can only reproduce it with LXD.  Could you please find out the equivalent zfs commands that reproduce this problem, so we can pass it on to ZFS.

# Version information

Distribution:  Debian 10.5, with backports, snapd, and ZFS installed, as per:
https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/index.html

I also verified it with Ubuntu 20.04 and Ubuntu 18.04.

```
uname -vrmo
4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

zfs version
zfs-0.8.4-2~bpo10+1
zfs-kmod-0.8.4-2~bpo10+1


snap list         
Name    Version      Rev    Tracking       Publisher   Notes
core    16-2.45.3.1  9804   latest/stable  canonical✓  core
core18  20200724     1885   latest/stable  canonical✓  base
lxd     4.4          16926  latest/stable  canonical✓  -
```

# Steps to reproduce:
Assume LXD is installed with ZFS dataset z/lxd:

lxc launch images:alpine/3.12 a1
lxc snapshot a1 packages
lxc copy a1/packages a2
lxc stop a1
lxc delete a1
zfs snapshot -r z/lxd@copy

on another system (I tried Debian and Ubuntu 18.04), with ssh access to the first system as host "pin", and an empty ZFS dataset z/test, run the following:
ssh pin sudo zfs send -R z/lxd@copy | sudo zfs receive -F z/test/lxd

Result:  I get an error:
cannot receive: local origin for clone z/test/lxd/containers/a2@copy does not exist

Expected Result:
I should be able to backup the LXD zfs dataset using ZFS tools.

**Comment by melato** [comment]
A similar issue was reported here:  https://github.com/openzfs/zfs/issues/10135

**Comment by melato** [comment]
I edited the description and removed the second "lxc snapshot", which is not needed.

**Comment by stgraber** [comment]
Definitely smells like a ZFS bug...
Can you show `zfs list -t all -o name,origin,clones`? Maybe this will show some oddity?

I'm closing the issue as this really feels like a ZFS bug. I subscribed myself to the openzfs issue so will get notified if upstream asks for something that's related to LXD.
