### ISSUE TITLE
Commands missing from lxc help text

### ISSUE THREAD

**Issue by jgriffiths1993** [lxc/lxd#786]
There doesn't appear to be anything the `lxc help` output for `finger` or `init`; they're not in the man page either.

**Comment by tych0** [comment]
On Tue, Jun 23, 2015 at 02:13:12PM -0700, Joshua Griffiths wrote:
> There doesn't appear to be anything the `lxc help` output for `finger` or `init`; they're not in the man page either.

I think finger is dead, and init missing from the help output is
intentional, as ideally people would just use launch (but some more
advanced folks will want init).

**Comment by stgraber** [comment]
They appear when passing \-\-all to help.

The argument is documented when passing \-\-help to help, but that's maybe a bit odd.

**Comment by jgriffiths1993** [comment]
Ah I see!
It is a bit odd (I wouldn't usually pass -h to help to find the --all option).
I'd expect the help output to show all the options available (including init)

**Comment by stgraber** [comment]
Yeah, we probably ought to at least mention \-\-all in the help output.

**Comment by jgriffiths1993** [comment]
Most definitely

It's really down to how many more things are going to be added to the `--all` category. At the moment it's just `finger` (which sounds like it may be deprecated) and `init` which I expect most people will require at some point.

Unless lots of new options are to be added soon, it might be better to put all of the options in the standard `--help` text until it becomes excessive

**Comment by pcdummy** [comment]
Maybe do this with Issue #490?

**Comment by stgraber** [comment]
Yeah, that's definitely the right fix for this, though I'll probably still add a mention of \-\-all to the current help message for the next release.
