### ISSUE TITLE
lxc commands mixed german and english

### ISSUE THREAD

**Issue by rusher97** [lxc/lxd#7864]
Distribution: Ubuntu
Distribution version: 18.04.5 LTS
Kernel version: GNU/Linux 4.15.0-117-generic x86_64
LXC version: 3.0.3
LXD version: 3.0.3
Storage backend in use: zfs

Hi, 

the first nine lxc commands are upper case and german, i think its since the last update. Last time i changed container configuration i just used "lxc config", now its called "lxc Konfiguration", see my "lxc help" below. I think even if the os is configured to german, all commands should be lower case and english, a german description would be ok. But half german and half english commands are very annoying.

Best regards

# Steps to reproduce

lxc --help

Beschreibung:
  Command line client for LXD

  All of LXD's features can be driven through the various commands below.
  For help with any of those, simply call them with --help.

Usage:
  lxc [command]

Available Commands:
  Abbild        Abbilder verwalten
  Alias         Befehlsaliase verwalten
  Datei         Dateien in Containern verwalten
  Konfiguration Container- und Serverkonfigurationsoptionen verwalten
  Netzwerk      Container verwalten und zu Netzwerken hinzufügen
  Operation     Hintergrundoperationen auflisten, zeigen und löschen
  Profil        Profile verwalten
  Speicher      Speicherpools und Speicherdatenträger verwalten
  Version       Show local and remote versions
  cluster       Cluster-Mitglieder verwalten
  console       Herunterfahren des Containers erzwingen
  copy          Copy containers within or in between LXD instances
  delete        Container und Snapshots löschen
  exec          Befehle in Containern ausführen
  help          Help about any command
  info          Container- oder Serverinformationen anzeigen
  launch        Container vom Abbild erstellen und starten
  list          Container auflisten
  move          Verschiebe Container innerhalb oder zwischen LXD-Instanzen
  publish       Container als Bilder veröffentlichen
  remote        Die Liste der Remoteserver verwalten
  rename        Container und Snapshots umbenennen
  restart       Container neustarten
  restore       Restore containers from snapshots
  snapshot      Create container snapshots
  start         Container starten
  stop          Container stoppen

Flags:
      --all           Weniger gewöhnliche Befehle anzeigen
      --debug         Alle Debug-Nachrichten anzeigen
      --force-local   Force using the local unix socket
  -h, --help          Hilfe ausgeben
  -v, --verbose       Alle Informationsnachrichten anzeigen
      --version       Versionsnummer ausgebe

**Comment by stgraber** [comment]
That's unfortunately a common pattern with partly translated software which we can't really control.
Official LXD translations can be found and fixed at https://hosted.weblate.org/projects/linux-containers/lxd/

Though in the case of Ubuntu, there's also Launchpad which may have differing distro-specific translations impacting this.
One thing I noticed is that a few of our commands are incorrectly marking some strings as translatable. I'll fix this and close this issue with that fix.

**Comment by typomedia** [comment]
Workaround: `sudo mv /usr/share/locale-langpack/de/LC_MESSAGES/lxd.mo /usr/share/locale-langpack/de/LC_MESSAGES/lxd.mo.bak`
