### ISSUE TITLE
`proxy` device support for VMs (NAT-only)

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7868]
We should add support for `proxy` devices on virtual machines but restricting them to NAT mode for now as implementing the full range of proxy device options through the agent would be a lot of work.

Just doing the NAT piece should be very straightforward, re-using what we have in place for containers.

**Comment by grant-he** [comment]
My group would also like to tentatively claim this issue. Thank you!

**Comment by stgraber** [comment]
Thanks, assigned to you
