### ISSUE TITLE
Report `qemu` driver with version in `/1.0`

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7869]
Similar to how we're reporting `lxc` and its version in `driver` and `driver_version`, we should include `qemu` and its version in there when available.

I suspect this should be done by:
 - Adding an `Info()` function in the `instance` interface, similar to what we're doing for storage
 - Having a function in the `instance` package which lets you query the `Info` for all drivers
 - Updating the `/1.0` API endpoint to use that data (and cache it), reporting with a syntax similar to storage

**Comment by wester162** [comment]
Hi, I'm also a student at UT with @nzubair76 and @mattdombrowski21. Sorry for the sudden deluge of issue claims, but we'd like to tentatively claim this one as well to work on. Thanks!

**Comment by stgraber** [comment]
Sounds good, assigned to you.

@tomponline should be able to give you more details instructions on what would need changing for this.
It should be pretty straightforward, effectively introducing an Info struct in the instances package and implementing it in both lxc and qemu, then having the logic in `lxd/api_1.0.go` use that data and render it in the `driver` and `driver_version` fields the same way we do `storage` and `storage_version`.

Caching will be critically important here as `/1.0` is hit extremely often, so we can't go poking at `go-lxc` or `qemu` directly every time, also those versions aren't going to change without LXD getting restarted, so no reason not to cache.

`lxc.Version()` gets you the LXC version, for qemu, you'll need to run and parse `qemuBinary --version`  (where qemuBinary is the one returned from `qemuArchConfig()` in `driver_qemu.go`).

**Comment by tomponline** [comment]
@wester162 let me know when you are getting started on this and I'll flesh out the instructions.

**Comment by wester162** [comment]
@tomponline Sorry about the long delay on this, we had another project to do before we started on this one, but we're looking to get started working on this now.

I've taken a peek into ``api_1.0.go`` and see the existing ``Driver`` and ``DriverVersion`` fields for lxc, as well as having looked into ``driver_qemu.go`` and found the origins of the ``qemuBinary`` variable that stgraber was talking about, but I wouldn't mind having a bit more specific instructions on where to get started.

**Comment by tomponline** [comment]
Hi @wester162 I've been looking into this today.

@stgraber can you confirm you are thinking of modifying the `api.ServerEnvironment` struct to make it so that multiple drivers (and their associated versions) can be returned in the output of `lxc info`? 

Perhaps introducing a new `InstanceDrivers` field to  `api.ServerEnvironment`  of new type `[]api.InstanceDriver` (containing `Name` and `Version` fields).

Presumably for API compatibility we'd need to keep the old `Driver` and `DriverVersion` fields for LXC?

E.g.

```
lxc info
...
  driver: lxc
  driver_version: 4.0.0 (devel)
  instance_drivers:
      - name: lxc
        version: 4.0.0 (devel)
     - name: qemu
       version: 4.2.1
```

**Comment by stgraber** [comment]
@tomponline no, I was planning on doing the same we do for storage. That keeps the exact same key and uses a separator to list multiple values.

That avoids any API breakage.

**Comment by tomponline** [comment]
@stgraber ah OK I see what you mean now.


@wester162 the current `lxc info` command outputs the storage drivers and their associated versions in the following format:

```
lxc info
...
  storage: zfs | btrfs | dir | lvm
  storage_version: 0.8.3-1ubuntu12.4 | 5.4.1 | 1 | 2.03.07(2) (2019-11-30) / 1.02.167 (2019-11-30) / 4.41.0
...
```

So we should update the `driver` and `driver_version` fields to do the same, e.g.

```
lxc info
...
  driver: lxc | qemu
  driver_version: 4.0.0 (devel) | 4.2.1
...
```

**Comment by tomponline** [comment]
@wester162 so have a look at how we use `storagePoolDriversCacheUpdate()` and `readStoragePoolDriversCache()` and then create a similar set of functions for instance driver cache.

**Comment by wester162** [comment]
@tomponline Got it. I'll let you guys know if I have any further questions.

**Comment by wester162** [comment]
@tomponline I've implemented most of the functionality necessary to make this work [here](https://github.com/wester162/lxd/blob/wester162/lxd/instance.go), but I've run into something of a snag trying to grab the ``qemuBinary`` value from ``driver_qemu.go``. This is probably just because I'm not super familiar with Go and its way of handling packages/scope, but if I try and pass the ``qemuBinary`` value via a setter function (``SetQemuPath()`` in ``instance.go``) it tells me the function is undefined, even though I think I'm setting the function as exported and ``driver_qemu.go`` has ``.../lxd/instance`` in its import.

Am I on the right track with that line of thinking, and just messing up something with scope, or is that a fundamentally flawed way of trying to find the qemu executable path?

**Comment by stgraber** [comment]
I took a quick look at your current approach. The cache mechanism & locking looks fine, but you really shouldn't have any logic specific to qemu or lxc be directly in that file.

Instead I would expect a new `Info() Info{}` function be added to the `Instance` interface and implemented in both `driver_qemu.go` and `driver_lxc.go`.

This `Info` struct would then include both `Name` and `Version` properties. Each of the driver would implement it and return suitable values. All you need to do then in the `instance.go` file is call `Info()` on all drivers and cache that result so `api_1.0.go` can use it.

**Comment by tomponline** [comment]
Thanks @wester162 please could you open a draft pull-request against LXD project and then we can review and add specific comments.

For example of what @stgraber is suggesting with regards to an `Info` struct, take a look at something very similar we have used in the storage subsystem:

https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/interface.go#L25-L27
https://github.com/lxc/lxd/blob/ba5ba36b81c1c01d716e9dd2b8b8cfd13109edd3/lxd/network/driver_common.go#L23-L27
https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_lvm.go#L87-L101
https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_lvm.go#L57-L83

So for instances, you should add a `SupportedDrivers` function to the `instances/drivers` package, that loads each supported instance driver similar to:

https://github.com/lxc/lxd/blob/f12f03a4ba4645892ef6cc167c24da49d1217b02/lxd/storage/drivers/load.go#L49-L64

However unlike the storage package, there isn't currently an equivalent `Load` function you can call with all nil arguments. So instead I would suggest creating the equivalent of https://github.com/lxc/lxd/blob/f12f03a4ba4645892ef6cc167c24da49d1217b02/lxd/storage/drivers/load.go#L8-L15 such that it returns a function that returns the instance type you need, which then allows you to call its `Info()` function.

You could even go further than that in making the instance package more like the storage package, but updating the `load` and `create` functions to remove the if/else statement on instance type and use the new instance type map instead. Then the associated `lxcLoad`, `qemuLoad`, `lxcCreate` and `qemuCreate` functions could be moved to be attached to the associated driver types as just `load` and `create`.
