### ISSUE TITLE
Allow `user.*` keys everywhere we store configuration

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7870]
The `user.*` key namespace is meant to allow users to store any additional data they see fit.
This is allowed in a few places right now, most notably in instance/profile config, but we should make sure it's also valid in:
 - networks
 - projects
 - server
 - storage pools
 - storage volumes

**Comment by grant-he** [comment]
My group is interested in working on this. Could you please elaborate on the tasks needed to close the issue? Thank you!

**Comment by stgraber** [comment]
Thanks, assigned to you.
