### ISSUE TITLE
Move all iproute (`ip` command) calls to a separate package

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7871]
Our long term plan is to switch from calling `ip` as a subprocess and instead hit netlink directly from Go.

But as a first step, we need to refactor our calls to `ip` and move everything into a new package, providing a first abstraction layer that we can then use as the basis for the switch to netlink.

So for this issue, we'll want to locate all calls to `ip`, figure out what they do, from that determine what level of abstraction can be done by the new package, then implement the new functions and port over all existing `ip` calls.

**Comment by grant-he** [comment]
Hi, I'm a CS student at UT Austin and looking to contribute to this project. My group would like to tentatively claim this issue. Thank you!

**Comment by stgraber** [comment]
Thanks, assigned to you.

**Comment by stgraber** [comment]
@grant-he Do you still intend to work on this or should we un-assign so someone else can have a go at it?

**Comment by grant-he** [comment]
Let's have someone else have a go at it.

**Comment by presztak** [comment]
@stgraber Can I work on this?

**Comment by stgraber** [comment]
Yep!

**Comment by stgraber** [comment]
@presztak how's this going? need any pointers?

**Comment by presztak** [comment]
@stgraber I already have most of the implementation. PR should be ready in next week. Is it ok for you?

**Comment by stgraber** [comment]
yep, that's great, thanks!
