### ISSUE TITLE
New `pci` device type for virtual machines

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7872]
This is a new device type exclusively available to virtual machines and which relies on the existing VFIO logic we have for `nic` and `gpu` passthrough.

The expectation is that a user would provide either a `pci` address or `vendorid` and `productid` (similar options to `gpu` type).
From that we locate the PCI device and pass it in with VFIO to the VM.

The main benefit of this is to allow passing through PCI devices which aren't GPU or NIC devices, things like NVME disks or random accelerator cards or FPGAs.

**Comment by kevtheappdev** [comment]
Hi! I'm interested in working on this along with some colleagues of mine as part of a course on Virtualiztion at UT Austin. Can we work on this issue? Thanks!

**Comment by stgraber** [comment]
Yep, assigned it to you.

I expect this will end up with a set of commits like:

 - api: pci_devices extension
 - doc: Add PCI devices
 - lxd/devices/pci: Add new PCI device type

This will only apply to virtual machines so will need to be marked as such.
The only properties this should allow is:
 - pci
 - productid
 - vendorid

@tomponline should be able to help you with any questions regarding our device packages.

**Comment by stgraber** [comment]
@kevtheappdev Do you still intend to work on this or should we un-assign so someone else can have a go at it?

**Comment by stgraber** [comment]
I'll take this one over.
