### ISSUE TITLE
Support refreshing custom storage volume copies

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7873]
This is the same idea as `lxc copy --refresh` which allows updating an existing copy, both locally and remotely.
But this time, we want to do it for storage volumes, so at the `lxc storage volume copy` level.

The infrastructure should be identical and so require little to no changes at the storage package layer.
As the same migration structs are used for both instances and storage, that layer should also already be able to handle it.

So this is primarily an API, CLI and tiny bit of plumbing to get it to work (+ some tests).

**Comment by grant-he** [comment]
My group would also like to tentatively claim this issue. Thank you!

**Comment by stgraber** [comment]
Assigned it to you, thanks!

As mentioned, everything needed for this should already be there already so it's mostly a matter of connecting the dots.

This will need an API extension and CLI change, so I expect the final list of commits to look something like:

 - api: Add custom_volume_refresh extension
 - shared/api: Add Refresh to StorageVolumeSource
 - client: Add Refresh to StoragePoolVolumeCopyArgs
 - lxc/storage: Add `--refresh` to `lxc storage volume copy`
 - lxd/migration: Add Refresh support for custom volumes

@tomponline should be able to answer any additional question on what to modify, how to test, ...

**Comment by stgraber** [comment]
@grant-he Do you still intend to work on this or should we un-assign so someone else can have a go at it?

**Comment by grant-he** [comment]
Let's have someone else have a go at it.

**Comment by avr1** [comment]
Hi @stgraber, I'd like to take a look at this for my first issue if that's ok. I might need a bit of help, but I'm looking forward to learning a lot!

**Comment by stgraber** [comment]
Absolutely, assigning it to you and we'll be happy to give you some pointers!

**Comment by avr1** [comment]
Hi @stgraber, newbie question incoming: In the first bullet point in one of your previous comments on this thread, you mention that I should plan on adding a custom_volume_refresh extension to the api. I'm having trouble locating the folder or file where the rest of this api is housed. Could you point me in the right direction?

**Comment by stgraber** [comment]
You need to add a new section to `doc/api-extensions.md` and add the same named entry to `shared/version/api.go`.

**Comment by stgraber** [comment]
@avr1 still planning on implementing this one?

**Comment by zakufish** [comment]
Hi @stgraber, I am interested in involving myself more in the lxd project. I noticed that this one is currently unassigned, do you mind letting me have a stab at it?

**Comment by zakufish** [comment]
Hi @stgraber I am interested in getting more involved in the development of the LXD project. Do you mind letting me have a stab at this one as it is currently unassigned?

**Comment by stgraber** [comment]
Assigned it to you!

**Comment by zakufish** [comment]
Thanks @stgraber
