### ISSUE TITLE
Make `lvm.thinpool_name` node-specific

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7875]
Originally from https://discuss.linuxcontainers.org/t/failed-to-join-cluster-due-to-missing-config-part-in-lxc-profile-show/8538/26,

In July 2018 the `lvm.thinpool` key was made node-specific (https://github.com/lxc/lxd/commit/1b67e1cc9a9f4851695c898fbb16bc31b444dfe3), however it was likely a typo as this key has apparently never actually been in use.

Instead it should have been `lvm.thinpool_name`.

We should correct this typo and then make a DB patch that converts existing non-node-specific `lvm.thinpool_name` keys in the database to node-specific ones.

**Comment by AndrewElvisDeng** [comment]
Hi! I'm a student from UT and my group would like to claim this issue. Thanks!

**Comment by stgraber** [comment]
Thanks, assigned it to you.

@tomponline should be able to help you with this one.

Fixing the typo wherever it's present should be pretty straightforward, then we need a one time patch to fix any deployment where it's incorrect. We should have some examples of this somewhat readily available in `lxd/patches.go`.

Worth noting that while a DB schema update would be more suitable for such changes, unfortunately those cannot be backported to stable releases whereas this fix definitely should be. So that's why we'll instead need to use a `lxd/patches.go` entry which is a bit awkward (patches apply on every system, schema updates apply once per cluster).

**Comment by AndrewElvisDeng** [comment]
We've fixed the typo and are working on the patch

**Comment by stgraber** [comment]
Cool!

**Comment by tomponline** [comment]
@AndrewElvisDeng please let me know if you get stuck on anything and need help. Thanks
