### ISSUE TITLE
Cryptic "The requested image couldn't be found" even though it's listed in `lxc image list`

### ISSUE THREAD

**Issue by Saviq** [lxc/lxd#7877]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04.1
 * [The output of "lxc info"](https://github.com/lxc/lxd/files/5233048/lxc.txt)

# Issue description

I'm getting an "image not found" without any detail when working with a prototype streams:

```plain
 lxc image list buildd-test:0e6b24b6a420332ac3fd1c84c77bcf7434524d3fd214a1580a87eba5af3e12b0
+-------------+--------------+--------+----------------------------------------------------+--------------+-----------------+----------+-------------------------------+
|    ALIAS    | FINGERPRINT  | PUBLIC |                    DESCRIPTION                     | ARCHITECTURE |      TYPE       |   SIZE   |          UPLOAD DATE          |
+-------------+--------------+--------+----------------------------------------------------+--------------+-----------------+----------+-------------------------------+
| f (11 more) | 0e6b24b6a420 | yes    | ubuntu 20.04 LTS amd64 (buildd release) (20200825) | x86_64       | VIRTUAL-MACHINE | 295.56MB | Aug 25, 2020 at 12:00am (UTC) |
+-------------+--------------+--------+----------------------------------------------------+--------------+-----------------+----------+-------------------------------+
 lxc image copy buildd-test:0e6b24b6a420332ac3fd1c84c77bcf7434524d3fd214a1580a87eba5af3e12b0 local:
Error: Failed remote image download: The requested image couldn't be found
```

While it's obviously a problem with my streams, the error could say more? Maybe the URL it was trying?

# Steps to reproduce

1. `lxc remote add --protocol simplestreams buildd-test https://people.canonical.com/~msawicz/buildd/`
2. `lxc image copy buildd-test:0e6b24b6a420332ac3fd1c84c77bcf7434524d3fd214a1580a87eba5af3e12b0 local:`

# Information to attach

 - [x] [Output of the client with --debug](https://github.com/lxc/lxd/files/5233059/lxc.txt)
 - [x] [Output of `lxc monitor` while reproducing the issue](https://github.com/lxc/lxd/files/5233063/lxc.txt)

**Comment by stgraber** [comment]
That tends to be hidden away a bit by the LXD API a bit since in this case the actual download will be initiated by your local server.

Debugging streams tends to be easier when only relying on the client code, so in this case, try:
 - lxc image list buildd-test:
 - lxc image show buildd-test:0e6b24b6a420
 - lxc image export buildd-test:0e6b24b6a420

And that last one tells you what's going on:
```
Error: Unable to fetch https://people.canonical.com/~msawicz/buildd/focal/release-20200825/focal-server-cloudimg-amd64-lxd.tar.gz: 404 Not Found
```

**Comment by stgraber** [comment]
it's a `.tar.gz` vs `.tar.xz` thing in this case.

**Comment by stgraber** [comment]
Oh, actually, in my case I'm actually getting the right error:
```
stgraber@castiana:~$ lxc image copy buildd-test:0e6b24b6a420332ac3fd1c84c77bcf7434524d3fd214a1580a87eba5af3e12b0 local:
Error: Failed remote image download: Unable to fetch https://people.canonical.com/~msawicz/buildd/focal/release-20200825/focal-server-cloudimg-amd64-lxd.tar.gz: 404 Not Found
```

I think what you're hitting in your case is the simplestreams cache. LXD downloaded your stream the first time you tried a copy, probably when the index wasn't working (explaining your error), you've then fixed that issue but the cache hasn't expired yet and so you're still getting the error.

So get things working with `lxc image export` and when they do, go and manually wipe the LXD cache (`/var/snap/lxd/common/lxd/cache/` and reload LXD before re-trying).

Alternatively wait an hour for the cache to expire.

**Comment by Saviq** [comment]
> it's a `.tar.gz` vs `.tar.xz` thing in this case.

> I think what you're hitting in your case is the simplestreams cache.

Yeah I realized that in the mean time… Sorry for the noise, then. It was still weird to see the image in the list, but have it 404 when trying to use it…
