### ISSUE TITLE
lxc exec randomly crash

### ISSUE THREAD

**Issue by vince06fr** [lxc/lxd#788]
When I do 
```lxc exec ubuntu -- /bin/bash```
sometimes it is working and sometimes i can do nothing except close the terminal (even ctrl+z or ctrl+c don't work)

here my log

```
  lxc_container 1435212136.848 INFO     lxc_confile - confile.c:config_idmap:1376 - read uid map: type u nsid 0 hostid 100000 range 65536
  lxc_container 1435212136.848 INFO     lxc_confile - confile.c:config_idmap:1376 - read uid map: type g nsid 0 hostid 100000 range 65536
  lxc_container 1435212136.851 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:574 - 'ubuntu' is in 'RUNNING' state
  lxc_container 1435212136.858 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:574 - 'ubuntu' is in 'RUNNING' state
  lxc_container 1435212136.859 WARN     lxc_log - log.c:lxc_log_init:316 - lxc_log_init called with log already initialized
  lxc_container 1435212136.859 WARN     lxc_attach - attach.c:lxc_attach:651 - Failed to get seccomp policy
  lxc_container 1435212136.862 INFO     lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:187 - changed apparmor profile to lxc-container-default
```
More about the bug

first time running the lxc exec command working perfectly
do exit 
running the lxc exec command again don't work
restart the lxd daemon
the lxc exec command work again

**Comment by zacbri** [comment]
Same behaviour here.
Here is the debug output on the client :

2015/06/25 11:27:24 fingering the daemon
2015/06/25 11:27:25 raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_compat":1,"auth":"trusted","config":{"core.trust_password":true},"environment":{"backing_fs":"ext4","driver":"lxc","kernel_version":"3.13.0-55-generic","lxc_version":"1.1.2","lxd_version":"0.11"}}}
2015/06/25 11:27:25 pong received
2015/06/25 11:27:25 posting {"command":["ps"],"environment":{"HOME":"/root","TERM":"xterm","USER":"root"},"interactive":true,"wait-for-websocket":true}
 to https://REDACTED:8443/1.0/containers/corp-pg1/exec
2015/06/25 11:27:25 raw response: {"type":"async","status":"OK","status_code":100,"operation":"/1.0/operations/d7a9c526-ef59-49db-9fc3-22b6acdfb59e","resources":null,"metadata":{"fds":{"0":"7be7475d42f70bbf95a2d783ef94dc978b0df3d788d5b520447f696d63591309","1":"8c222f5a75f6f0b26f00faf482936c875fd7edbfa2dcb8a512520274ef4817ef","control":"0b6da7dd8d3b4b1fedb1f46946a49783043abdaad9c60a8d934a59d1b3066c00"}}}

And it gets stuck here.
I get the same random lock-ups whether I'm running the exec command locally or remotely.

Funny thing is when I use exec to run a script previously pushed with "lxc file", I would get no output back and it would get stuck, but the script execution actually completes in the container.

I'm using :
* lxc 1.1.2-0ubuntu3~ubuntu14.04.1~ppa1
* lxd 0.11-0ubuntu1~ubuntu14.04.1~ppa1

**Comment by tych0** [comment]
Would either of you guys mind trying with the current git trunk? I think we've had several exec releated fixes go in since 0.11.

**Comment by zacbri** [comment]
Will do asap. Just need to get familiar with building LXD.
By the way, any ETA on 0.12 landing in the PPA ?

**Comment by vince06fr** [comment]
I have make a  try to install the current trunk but I have failed
installing from lxc-daily : I get a dpkg: dependency problems with lxd depend of lxc
not configured lxc
Building from source i am  blocked on 
```sudo -E $GOPATH/bin/lxd --group sudo```
the processus freeze and I must do ctrl+c
then
```
$GOPATH/src/github.com/lxc/lxd/scripts/lxd-imageimport lxc ubuntu trusty amd64 --alias
LXD isn't running.
```
so
```
$GOPATH/bin/lxd 
error: open /var/lib/lxd/server.key: permission denied
```
:/

**Comment by tych0** [comment]
On Fri, Jun 26, 2015 at 08:57:07AM -0700, vince06fr wrote:
> I have make a  try to install the current trunk but I have failed
> installing from lxc-daily : I get a dpkg: dependency problems with lxd depend of lxc
> not configured lxc
> Building from source i am  blocked on 
> ```sudo -E $GOPATH/bin/lxd --group sudo```
> the processus freeze and I must do ctrl+c

What do you mean by freeze? LXD is a daemon, it just waits for input.

**Comment by jgriffiths1993** [comment]
You'll need to be part of the given group (`sudo`). Try starting lxd with `--debug=true`

**Comment by vince06fr** [comment]
> What do you mean by freeze? LXD is a daemon, it just waits for input.

Just when I have try to make the daemon in the background with & and run  the lxc command, the lxd daeamon was stopped . Just I make another try today and it is working. I think i have make a typo error of something like this yesterday..
