### ISSUE TITLE
Feature request, user/group quota support for dir ext4 storage backend

### ISSUE THREAD

**Issue by WebsliceNL** [lxc/lxd#7886]
# Required information

 * Distribution: Centos8 or latest Ubuntu
  * Storage backend in use: dir ext4

# Issue description

Already tried to get the status clear on the forum.
With the lack of feedback, I will assume it's not supported yet.

https://discuss.linuxcontainers.org/t/is-regular-user-and-group-quota-supported-inside-a-container-using-ext4-dir-backend/8502

Can we have full user/group quota support within a container with a dir ext4 storage backend, similar to how OpenVZ and simfs are providing. Don't want to use ZFS of BTRFS.
I don't mind if dedicated ext4 attached volumes/disks/partitions are needed.

**Comment by stgraber** [comment]
The reason why nobody's giving a clear answer is that it's really not something we can control at the LXD level.

Those are seldom used filesystem-specific features. LXD does give you control on mount flags when using something like LVM with ext4 per-container, but then I highly doubt that the kernel would allow any of the quota related ioctls when coming from inside an unprivileged container.

**Comment by stgraber** [comment]
So I would expect user/group quotas to function inside a privileged container running on a dedicated ext4 filesystem as you'd get from using the LVM backend when combining that with the appropriate mount options.

For unprivileged containers, I don't see how the kernel could allow that without at the same time allowing any normal user on your system to bypass the quota.

**Comment by stgraber** [comment]
@brauner any idea how user/group quotas work? What's the actual API used for this, is it something we could syscall intercept in theory?

**Comment by WebsliceNL** [comment]
> So I would expect user/group quotas to function inside a privileged container running on a dedicated ext4 filesystem as you'd get from using the LVM backend when combining that with the appropriate mount options.

Tried that now, but lvm device does not seem to be available from the container

lxc storage create lvm-container1 lvm source=/dev/nvme1n1 lvm.vg_name=lvm-container1
lxc launch -s lvm-container1 images:centos/8 lvm-container1

lxc set lvm-container1 security.privileged true

lxc storage volume set lvm-container1 container/lvm-container1 block.mount_options=discard,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0

lxc restart lvm-container1

lxc exec lvm-container1 -- /bin/mount |grep quota
/dev/lvm-container1/containers_lvm--container1 on / type ext4 (rw,relatime,discard,stripe=16,data=ordered,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)

lxc exec lvm-container1 -- /sbin/quotacheck -cmug /
quotacheck: Cannot stat() mounted device /dev/lvm-container1/containers_lvm--container1: No such file or directory
quotacheck: Mountpoint (or device) / not found or has no quota enabled.
quotacheck: Cannot find filesystem to check or filesystem not mounted with quota option.

**Comment by stgraber** [comment]
Interesting, so yeah, that means there's no chance of quotas being a thing unless some serious kernel work happens.

The error above suggests that the quota code requires direct access to the backing block device. This device is never exposed to containers as access to it would let you attack the kernel in a rather trivial way, not only escaping the container but even corrupting the kernel on the entire machine.

**Comment by stgraber** [comment]
There is the possibility that accessing the backing device directly is just a convenience/shortcut that the authors of the quota tools took and that the kernel API itself may not require that, instead using ioctls on the root path or something, in which case it would be possible for someone to make those tools smarter.

But we'd need someone to go dig in the kernel code to understand exactly how those quotas get configured from a syscall/ioctl point of view and exactly what must be passed to the kernel to do it.

**Comment by WebsliceNL** [comment]
This seems to work;

lxc config device add lvm-container1 lvm-container1/containers_lvm--container1 unix-block path=/dev/lvm-container1/containers_lvm--container1

useradd quotauser

quotacheck -cmug /
quotaon /

repquota -a
*** Report for user quotas on device /dev/lvm-container1/containers_lvm--container1
Block grace time: 7days; Inode grace time: 7days
                        Block limits                File limits
User            used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
root      --  704328       0       0          19082     0     0       
tss       --      12       0       0              2     0     0       
quotauser --       4       0       0              5     0     0       

setquota -u quotauser 209715 209715 100000 100000 /

repquota -a
*** Report for user quotas on device /dev/lvm-container1/containers_lvm--container1
Block grace time: 7days; Inode grace time: 7days
                        Block limits                File limits
User            used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
root      --  704328       0       0          19082     0     0       
tss       --      12       0       0              2     0     0       
quotauser --       4  209715  209715              5 100000 100000       

su - quotauser
fallocate -l 100M test.img
logout

repquota -a
*** Report for user quotas on device /dev/lvm-container1/containers_lvm--container1
Block grace time: 7days; Inode grace time: 7days
                        Block limits                File limits
User            used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
root      --  704324       0       0          19082     0     0       
tss       --      12       0       0              2     0     0       
quotauser --  102404  209715  209715              7 100000 100000

**Comment by stgraber** [comment]
Right, that will work, but now your container can directly write to its backing block device, attacking the kernel and crashing it or worse injecting arbitrary kernel code that can affect your entire machine.

**Comment by WebsliceNL** [comment]
So, for ZVOL it is implemented differently?
I understood it's very simular to the LVM mount inside the container.
So the regular quota tools inside de container seem to be able to access the raw device, but than securely in that case?

**Comment by stgraber** [comment]
For an actual zvol, it would be identical as zvol is also a block device and so would be identical as far as the kernel is concerned.

user/group quotas on top of a dataset may be different though, not sure how those work.
