### ISSUE TITLE
Add IOMMU group information to resources API

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7894]
When dealing with device passthrough, it's quite useful to know the IOMMU group for a particular device.
We should add this to our PCI entries in the resources API.

**Comment by nzubair76** [comment]
Hi, also a student at UT Austin and looking to contribute to this project. My group would like to tentatively claim this issue. Thank you!

**Comment by stgraber** [comment]
Sounds good, assigned it to you for now.

This should be a pretty simple one to resolve, with changes needed in:
 - doc/api-extensions.md (introduce a new API extension)
 - shared/version/api.go (add the API extension to the list)
 - shared/api/resource.go (add the new field to `ResourcesPCIDevice`)
 - lxd/resources/pci.go (fill the newly introduced field)

I'd expect this to result in 3 commits:
 - api: resources_pci_iommu extension (includes the doc/ and shared/version/api.go changes)
 - shared/api: Add IOMMUGroup field to `ResourcesPCIDevice` (includes the shared/api changes)
 - lxd/resources: Add IOMMU group value to PCI devices (includes the lxd/resources changes)

As for figuring out the IOMMU group, you can do this by using the symlink present at `/sys/bus/pci/devices/ADDR/iommu_group`, resolve the symlink with ReadLink and then get the filename (basename) from the resulting path, this looks like this in shell:

```
root@athos:~# basename $(readlink /sys/bus/pci/devices/0000\:82\:00.0/iommu_group)
80
```

We should be able to make this a uint and use 0 if no `iommu_group` file can be found (as will be the case on any system which does not have iommu enabled).

To enable iommu grouping, you'll need to boot your system with `iommu=pt intel_iommu=on` on the kernel command line, assuming an Intel system. Though you can also implement the code purely based on the description above and I can easily test it for you on some servers that have IOMMU enabled and a bunch of groups.
