### ISSUE TITLE
Smarter handling of `volatile` keys in restricted projects

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7896]
Right now, `restricted` projects that do not have `restricted.containers.lowlevel` and/or `restricted.virtual-machines.lowlevel` will prevent the user from setting/altering `volatile.*` config keys.

This is a good thing in general and avoids a lot of potential attacks against the host, however this also breaks quite a lot of things, including instance copies:

```
stgraber@castiana:~/data/code/lxc/lxd (lxc/master)$ lxc copy stgraber-ctn1 stgraber-ctn2
Error: Setting "volatile.base_image" on container "stgraber-ctn2" in project "warthogs" is forbidden
```

I suspect at a minimum we need to:
 - Maintain a list of `safe` volatile keys which we actually do allow to set in a restricted project, this should include:
   - volatile.apply_template
   - volatile.base_image
   - volatile.last_state.power
   - volatile.DEVNAME.apply_quota
   - volatile.DEVNAME.hwaddr
 - Allow those `safe` volatile keys to be set even when in a restricted project
 - On creation (which would include copies), silently strip any non-allowed volatile key from the config rather than fail the copy.

**Comment by jtajonera** [comment]
Hi I am a student at UT Austin and am currently taking a Virtualization course. Is it possible for me to tentatively claim this issue?

**Comment by stgraber** [comment]
Yep, assigned to you now.
