### ISSUE TITLE
Restrict a client certificate to a particular project

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7898]
Currently anyone who's in the LXD trust store has global access to LXD unless they're using external authentication through candid and access policies through RBAC.

This is all fine for production servers and clusters where that additional machinery is expected, but we have now seen cases we'd want to tie a single user (certificate) to a particular project and prevent that user from escaping the project or having LXD-wide admin access.

This issue is to track:
 - Adding a new column and matching API field to the `certificates` table storing a list of projects that the user can access
 - Updating our permission checking code to treat this method as equivalent to RBAC where such a user would have the `operator` equivalent role on the listed projects.
 - `operator` is currently defined as having project-specific permissions:
   - view
   - manage-containers
   - manage-images
   - manage-networks
   - manage-profiles
   - manage-storage-volumes
   - operate-containers
 - Matching tests

The result here should be the ability to:
 - Create a new project, enable limits and restrictions on it
 - Add or edit a trust store entry for a user certificate and tie it to that project
 - Validate that this user can now only see listed projects, cannot modify global settings and is limited to interacting with what's inside the project so long as they stay within the limits/restrictions applied on it

NOTE: We have no intention of building something like RBAC into LXD. An external service is a far better fit for this. As a result, we're only interested here in giving that general `operator` type access to a specific certificate. We're not interested in giving finer grained access or allowing things like groups, those should be done in the external RBAC service.

**Comment by Jdogtherock** [comment]
Hello, I am a UT Austin student, can I be assigned to this issue?

**Comment by stgraber** [comment]
Done!

**Comment by stgraber** [comment]
Un-assigned as requested in #7900

**Comment by turtle0x1** [comment]
@stgraber how will the user be limited on the wider API? 

I.E If I limit a user to a project will they still be able to hit `/1.0/resources` and get information about the system?

**Comment by stgraber** [comment]
In general a protect restricted user can see just about everything so long as it's not owned by another project.

There are a few restrictions though, currently off the top of my head:
 - The logging part of the events API is blocked
 - The server configuration is always returned as empty

The resources API is available and we don't expect to block it as it is useful to choose targets and also does not leak information about other projects.

**Comment by stgraber** [comment]
Going to look into this one next.

**Comment by stgraber** [comment]
Just a quick note for myself, I think on the DB front, I'll be adding a `restricted` boolean column to `certificates` and then a separate `certificates_projects` table to assign certificates to projects.

This will support proper assignment through IDs and the extra column will allow to distinguish a restricted certificate with no project from an unrestricted certificate. This addresses a concern I had where a restricted certificate would become unrestricted once its projects got deleted. With the table + column setup, this can't happen, the certificate will remain restricted and not be allowed access to anything.
