### ISSUE TITLE
meaning of 'format' in lxc list 

### ISSUE THREAD

**Issue by arges** [lxc/lxd#790]
I see format mentioned in the specs/command-line-user-experience.md:                                                             
    [resource] [filters] [format]  

Yet lxc/list.go shows
    [resource] [filters]

I think a format field would be useful in order to minimize having to pipe things through awk/head/etc in order to get usable output for scripts.

How exactly should the 'format' field be set up? Is it another flag? How does it control output? Ideally it would be great to have a way to just print all names (for scripts) or perhaps names + IPs for others.

Either way it would be good to have consistency here.

**Comment by stgraber** [comment]
This has been resolved a while back.
