### ISSUE TITLE
Add `images.*` and `backups.*` server config keys to per-project

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7900]
Title pretty much says it all. We currently have the following configuration keys:

 - backups.compression_algorithm
 - images.auto_update_cached
 - images.auto_update_interval
 - images.compression_algorithm
 - images.remote_cache_expiry

Which are all related to objects that can be stored in profiles these days and so those keys now make a lot more sense being per-project rather than global.

The global keys can stay for backward compatibility reasons and as a way to set a system-wide default, but all those keys should be added to project configuration and when set there should take precedence over the global value.

**Comment by Jdogtherock** [comment]
Hello. I am a UT student in Virtualization, and I was wondering if I could work on this issue rather than the one I stated earlier?

**Comment by stgraber** [comment]
Sure, updated!

**Comment by Jdogtherock** [comment]
Hello, I am currently working on this issue and I was wondering if I could have some help. What are configuration keys, profiles, and projects?

**Comment by stgraber** [comment]
https://linuxcontainers.org/lxd/docs/master/ may help with some of the general concepts.

I'd say to start with `backups.compression_algorithm` and `images.compression_algorithm` as those are pretty easy ones.
Right now when we need that value we first look at a user provided override and if not set, look at the global config, if there's nothing there, then we use a default value.
This needs to be changed to also look at the current project for the request, check if a value was set on the project and if it is, use that over the global value.

Effectively lookup order becomes:
 - CompressionAlgorithm set on the request
 - `backups.compression_algorithm` set on the current project
 - `backups.compression_algorithm` set in the server config
 - default value

I'd say to start with those two as they work nearly identically, send a PR for it and after that look at the more complex ones.

**Comment by Jdogtherock** [comment]
So, I have found the keys and they are apart of server configuration. The goal is to effectively transfer them to project configuration, and have them be set in precedence over the server configuration values?

**Comment by Jdogtherock** [comment]
Also, would these keys be set in the lxc or lxd file? I've been trying to peruse through the code but I can't seem to find the answer.

**Comment by stgraber** [comment]
Someone should be able to do:
`lxc project set default backups.compression_algorithm gzip`

This would hit `lxd/api_project.go`, needs to be stored in configuration and retrieved from there where they're consumed in `lxd/images.go` and `lxd/backup.go` at least.

**Comment by stgraber** [comment]
The code should already have logic to look for a compression algorithm directly in the user's request, then fallback to the server value which then falls back to the hardcoded default.

So you just need to add an intermediate between what's in the user's request and hitting to the server value.

**Comment by stgraber** [comment]
@Jdogtherock Do you still intend to work on this or should we un-assign so someone else can have a go at it?

**Comment by Jdogtherock** [comment]
Hello, may I be unassigned?

**Comment by presztak** [comment]
Hello, can I work on this issue?

**Comment by stgraber** [comment]
Certainly, assigned it to you!

**Comment by presztak** [comment]
@stgraber  two questions:

1. I have used validateCompression function from lxd/cluster/config.go and moved it to shared/validate/validate.go because now it's used in lxd/api_project.go to validate project config keys. Is it a good place for this function or it should be placed somewhere else?

2. Key images.auto_update_interval is a little bit tricky. We have task function (autoUpdateImagesTask) where it should be checked. Interval in this functions is dependant from server config value right now but we can have many projects (many interval values) and we have one task function. What will be the best aproach? Should we fixed interval value for this task (e.g. for 1 hour) and inside task function check for every project (of course if project key is set) which images should be updated? Simillar scenario is with images.remote_cache_expiry key.

**Comment by stgraber** [comment]
1) That sounds like an appropriate place for it. The `validate` package was somewhat recently introduced by @tomponline and has been growing quickly, it certainly makes sense to move other validation function over.

2) I'd recommend to do a PR with the easy ones first so we can have that in place. But for those more complex ones, I think the approach of running the task every hour and then checking the config is the best one. Managing multiple tasks gets a bit tricky when you put clustering and folks creating/delete projects into the mix.

**Comment by stgraber** [comment]
Closing as we've now got all of those.
