### ISSUE TITLE
Option to configure the ZFS block size on volumes

### ISSUE THREAD

**Issue by InsanePrawn** [lxc/lxd#7901]
Custom volumes on ZFS (both filesystems and zvols) should expose control of their `recordsize` or `volblocksize` properties respectively.
This is commonly used to "tune" (read: fix) performance of applications like databases on ZFS, where it can have a huge impact due to its COW nature.

**Comment by stgraber** [comment]
Yeah, should be easy enough to add a new ZFS-specific volume property.

`volume.zfs.blocksize` when configured on a POOL, `zfs.blocksize` when configured directly on a volume.

**Comment by TimRots** [comment]
> `volume.zfs.blocksize` when configured on a POOL, `zfs.blocksize` when configured directly on a volume.
Isn't this the other way around?

**Comment by stgraber** [comment]
no

**Comment by stgraber** [comment]
On a pool, the config keys that will impact volumes are all prefixed with `volume.` whereas no such prefixing is needed on volume keys since they can only affect volumes :)

**Comment by TimRots** [comment]
Thank you for clearing this up @stgraber.
Would like to give this one a shot to implement.

Do you have some tips/guidance on this? I'm still getting familiar with the code base.

**Comment by stgraber** [comment]
The easiest is likely to based it off another option we have and look for that in the codebase.
In this case, I'd look for `volume.zfs.use_refquota` which is mentioned in:
 - doc/storage.md
 - lxd/storage_pools_config.go
 - lxd/storage/utils.go
 - lxd/storage/drivers/driver_zfs_volumes.go
 - lxd/storage/drivers/driver_zfs.go
 - scripts/bash/lxd-client

It's a bit different in that this one will take a size instead of a boolean and it doesn't apply during quotas but instead just at volume creation and update time, so should be a smaller delta than refquota.

@tomponline how difficult to you reckon it would be to get rid of those entries in `lxd/storage_pools_config.go` and `lxd/storage/utils.go`, only relying on the drivers to expose their pool and volume configs?

The current way we have things feels like a bit of layering violation, resulting from us having never fully completed the migration over to the new storage packages.

**Comment by tomponline** [comment]
@stgraber shouldnt be difficult, as we've already made provision for taking that out at some point.

I think this section is dead code now that all storage drivers are ported over: https://github.com/lxc/lxd/blob/master/lxd/storage/utils.go#L307-L344

Which means we could then get rid of https://github.com/lxc/lxd/blob/master/lxd/storage/utils.go#L296 entirely as its only called from one place anyway.

The `storagePoolValidateConfig` and `storagePoolValidate` are a bit more involved, they may need a generic `storage.Validate()` function being added that loads the driver internally and calls its `.Validate()` function before the DB record is created.

Shall I add a task in trello for this?

**Comment by tomponline** [comment]
@stgraber one thing I was a bit caution around was the use of `storagePoolValidateConfig` in the old patches for storage pool, as didn't want to interfere with the historical conversion process.

**Comment by stgraber** [comment]
Yeah, seems worth adding a card to clean things up when we have some time.

For things being used from patches, we can move what we must keep to patches_utils.go

**Comment by stgraber** [comment]
@TimRots are you still looking into this?

**Comment by TimRots** [comment]
> @TimRots are you still looking into this?

Yes. I would like to pick this up again over the upcoming weekend.

**Comment by stgraber** [comment]
Excellent!

**Comment by stgraber** [comment]
@TimRots hey, any progress on this?

**Comment by stgraber** [comment]
@TimRots

**Comment by zakufish** [comment]
Hi @stgraber as I have recently worked on another volume related issue, do you mind if I give this one a shot?

**Comment by stgraber** [comment]
Sure!

**Comment by stgraber** [comment]
Un-assigning due to inactivity, we're starting to run low on easy issues so putting this one back in the pool.

**Comment by andrewli6504** [comment]
Hello, I am a student at UT Austin taking Virtualization - Could me and @BlakeRomero I try tackling this issue?

**Comment by stgraber** [comment]
done!

**Comment by BlakeRomero** [comment]
Could I get assigned as well since we will be working together on this?

**Comment by zakufish** [comment]
@stgraber I was preparing for job interviews and didn't really have time to work on this. Sorry about ghosting and the inconvenience I've caused.

**Comment by stgraber** [comment]
@zakufish no worries!

**Comment by BlakeRomero** [comment]
I've been able to add zfs.blocksize and volume.zfs.blocksize as config options, but I am a bit confused on how I can actually provide the desired functionality to these config options. 
Do you have any tips on where in the code I should be looking?

So far, I have found that in lxd/storage/drivers/driver_zfs_volumes.go, CreateVolume references a defaultBlockSize, and GetVolumeUsage references a stat.Bsize. I am unsure of whether these two pieces of code should be changed, and if they should be changed, how I should go about altering them to get the desired behavior.

**Comment by stgraber** [comment]
So the code paths that would need to be covered for this are the volume creation ones:
 - CreateVolume
 - CreateVolumeFromBackup
 - CreateVolumeFromCopy
 - CreateVolumeFromMigration

And because I "think" those properties can be changed later on, probably also add support for blocksize to:
 - UpdateVolume

I suspect the easiest here would be to add a `setBlocksize(vol Volume)` function to the `zfs` struct in `driver_zfs_utils.go`.
That function would apply the value from `zfs.blocksize` to the volume, if the volume is of type Filesystem, then it would be applied as recordsize, if the volume is of type Block, then apply as volblocksize.

**Comment by stgraber** [comment]
Ah, so I just played with them a bit. `recordsize` (for filesystem volumes) can be set to any value that's a power of 2 between 512B and 1M, it can be changed at any time.

`volblocksize` can only be set at creation time (`zfs create`), it cannot be modified at any other point.


So for `recordsize`, what I said above will work just fine, but for `volblocksize`, it will only be possible to do it from `CreateVolume`, in all other cases, it should be skipped.

**Comment by BlakeRomero** [comment]
Thanks for the tips! I was able to add the necessary code for each of the places you mentioned, and I have written a `setBlocksize` function as well. I do have a couple more questions:

First, I think it would make sense to include some logic for a default value for this property, but I am unsure of what that default value should be and how I would go about including this logic. Do you have any pointers towards relevant code or information about this?

Second, I am having trouble finding references in the code to the `recordsize` and `volblocksize` properties that you have mentioned. Where can I find more information on these?

Thank you again for your help!

**Comment by InsanePrawn** [comment]
Please note that users can use a tunable to be able to go above 1M for recordsizes.

**Comment by stgraber** [comment]
Default should be not to set either of those properties.

`recordsize` and `volblocksize` are ZFS properties which you pass to `zfs create` or to `zfs set`

**Comment by stgraber** [comment]
@andrewli6504 @BlakeRomero hello, just wanted to check if you still intend to work on this or if we should unassign it so someone else can take a crack at it?

**Comment by BlakeRomero** [comment]
Yes, I plan to hopefully finish this up soon.

**Comment by stgraber** [comment]
Sounds good, thanks!

**Comment by presztak** [comment]
@stgraber I can work on this if you don't mind.

**Comment by stgraber** [comment]
Absolutely!

**Comment by presztak** [comment]
@stgraber,

I think that I'm very close to finish this one but I encountered one problem. We try to use one property (blocksize) to control two others: `recordsize` for volumes of type Filesystem and `volblocksize` for volumes of type Block. It wouldn't be a problem if not the fact that this two properties can have different range of values. `volblocksize` can have value from 512 to 128k, power of 2. And `recordsize` can have values from 512 to 1M, power of 2. So if we set 1M on the pool and then try to create volume of type Block, it would be a problem with creation.
What do you think? What will be the best approach to solve this?

**Comment by stgraber** [comment]
So I think what we can do is:
 - Allow `recordsize` to be anything in the 512 to 1M range (I'm assuming `M` here is `MiB`)
 - When setting `volblocksize`, we cap it to 128K so any value larger than it will just cause us to set 128K instead.

**Comment by presztak** [comment]
@stgraber I've just open PR. Should we allow for 16 MiB and allow to zfs throw the error if value is too big?

**Comment by stgraber** [comment]
Yeah, that's fine.
