### ISSUE TITLE
Add contextual logger to Instances

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#7903]
Currently the logging done in the instances drivers for LXC (https://github.com/lxc/lxd/blob/master/lxd/instance/drivers/driver_lxc.go) and Qemu (https://github.com/lxc/lxd/blob/master/lxd/instance/drivers/driver_qemu.go) are all done using the global logger, e.g. `logger.Info()`.

We have been updating other subsystems of LXD (such as device, storage and network) to use a per-struct local logger that is preloaded with contextual info about the struct. It would be great to update the instance drivers to have a local contextual logger as well.

An example from the network subsystem:

1. The `common` driver contains a `logger` variable (https://github.com/lxc/lxd/blob/master/lxd/network/driver_common.go#L29-L30).
2. This is then initialised with useful contextual information when the specific device driver is loaded (https://github.com/lxc/lxd/blob/master/lxd/network/driver_common.go#L42-L43).
3. Any logging calls then use the local logger in the per-driver code (https://github.com/lxc/lxd/blob/master/lxd/network/driver_bridge.go#L472).

This task is to:

1. Add a local logger to the common instance driver (https://github.com/lxc/lxd/blob/master/lxd/instance/drivers/driver_common.go#L12).
2. Initialise it with useful contextual information (at a minimum the instance name and instance type) https://github.com/lxc/lxd/blob/e1fa47b273fe971d54c0a627fd40886a31ed4388/lxd/instance/drivers/driver_lxc.go#L371 and https://github.com/lxc/lxd/blob/e1fa47b273fe971d54c0a627fd40886a31ed4388/lxd/instance/drivers/driver_qemu.go#L78.
3. Update calls to `logger.X` in the LXC and Qemu drivers to use the local logger (adding additional function local context variables in place of embedded arguments where relevant).

**Comment by kevtheappdev** [comment]
Hi! Could my team and I work on this? Thanks!

**Comment by stgraber** [comment]
Sure, assigned!

**Comment by kevtheappdev** [comment]
Hi! My team and I have an implementation for this issue, but we have been unable to get tests up and running on our machine. Running `sudo -E make check` in the root directory gives us the following error: `can't load package: package github.com/golang/lint/golint: code in directory /home/kturnt/go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"`. 
Do you have any suggestions for how to fix this? We would of course like to test our implementations before making a PR. Also, is there a good medium to reach you for questions? My team and I are working through our set of issues and are all newbies at Go/Linux containers?

**Comment by stgraber** [comment]
Try `go get -v golang.org/x/lint/golint` looks like it got moved.
