### ISSUE TITLE
'BPF_PROG_TYPE_CGROUP_DEVICE' undeclared 

### ISSUE THREAD

**Issue by tczaude** [lxc/lxd#7909]
# Required information

 * Distribution: Funtoo
 * Distribution version: 1.4
 * The output of "lxc info" or if that fails:
   * Kernel version:  Linux-5.7.10_p1-debian-sources-x86_64-Intel-R-_Core-TM-_i7-4810MQ_CPU_@_2.80GHz-with-gentoo-1.4
   * LXC version: --
   * LXD version: 4.6
   * Storage backend in use:

# Issue description

compiling lxd i recive this

```
github.com/lxc/lxd/lxd-agent
github.com/lxc/lxd/lxd/storage/drivers
github.com/lxc/lxd/lxc-to-lxd
github.com/lxc/lxd/lxd-p2c
# github.com/lxc/lxd/lxd/seccomp
lxd/seccomp/seccomp.go: In function 'handle_bpf_syscall':
lxd/seccomp/seccomp.go:335:25: error: 'BPF_PROG_TYPE_CGROUP_DEVICE' undeclared (first use in this function); did you mean 'BPF_PROG_TYPE_CGROUP_SOCK'?
  335 |   if (attr.prog_type != BPF_PROG_TYPE_CGROUP_DEVICE)
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         BPF_PROG_TYPE_CGROUP_SOCK
lxd/seccomp/seccomp.go:335:25: note: each undeclared identifier is reported only once for each function it appears in
lxd/seccomp/seccomp.go:389:27: error: 'BPF_CGROUP_DEVICE' undeclared (first use in this function)
  389 |   if (attr.attach_type != BPF_CGROUP_DEVICE)
      |                           ^~~~~~~~~~~~~~~~~
make: *** [Makefile:20: default] Error 2
 * ERROR: app-emulation/lxd-4.6::Funtoo-servers failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/lxd-4.6::Funtoo-servers'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/lxd-4.6::Funtoo-servers'`.
 * The complete build log is located at '/var/tmp/portage/app-emulation/lxd-4.6/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-emulation/lxd-4.6/temp/environment'.
 * Working directory: '/var/tmp/portage/app-emulation/lxd-4.6/work/go/src/github.com/lxc/lxd'
 * S: '/var/tmp/portage/app-emulation/lxd-4.6/work/go/src/github.com/lxc/lxd'

 * Messages for package app-emulation/lxd-4.6:

 * ERROR: app-emulation/lxd-4.6::Funtoo-servers failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/lxd-4.6::Funtoo-servers'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/lxd-4.6::Funtoo-servers'`.
 * The complete build log is located at '/var/tmp/portage/app-emulation/lxd-4.6/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-emulation/lxd-4.6/temp/environment'.
 * Working directory: '/var/tmp/portage/app-emulation/lxd-4.6/work/go/src/github.com/lxc/lxd'
 * S: '/var/tmp/portage/app-emulation/lxd-4.6/work/go/src/github.com/lxc/lxd'


```

**Comment by stgraber** [comment]
@brauner more bpf fixing fun for you?

**Comment by tczaude** [comment]
@tomponline thanks i start testing :)

**Comment by tczaude** [comment]
this patch no resolve above problem

**Comment by stgraber** [comment]
@tczaude sorry, confused by your message, do you still have the issue with the patch applied?

**Comment by tczaude** [comment]
Yes i apply patch from above commit and i have this same error

**Comment by stgraber** [comment]
@brauner back to you :)

@tczaude can you show the output again in case something changed a bit in it?

**Comment by tczaude** [comment]
[build.log](https://github.com/lxc/lxd/files/5263695/build.log)

[environment.log](https://github.com/lxc/lxd/files/5263700/environment.log)

I add build.log and env maybe give more info

**Comment by s4uliu5** [comment]
The root cause of this issue is that currently Funtoo has headers of 4.14 kernel.
`BPF_PROG_TYPE_CGROUP_DEVICE` and  `BPF_CGROUP_DEVICE` appeared in 4.15.

**Comment by brauner** [comment]
Well, yes we know that. The problem is that enums and structs can't be detected from cgo so we can't detect at build-time what kernel headers are supported. The solution is usually to (ab)use a define that can be detected when including the header via `#define` of some constant that was introduced around the same time as the feature. But for the one we used to use bpf has moved it into an enum in newer kernels and this one right here doesn't seem to work either. So my guess is that we need to start "vendoring" bpf types similar to what we do with the seccomp types.
