### ISSUE TITLE
Add a new `limits.instances` key in project

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7925]
This key will count containers+virtual-machines and so act as an overall limit on top of the existing container/virtual-machines limits.

**Comment by kevtheappdev** [comment]
My team and I would love to work on this! Can you elaborate what is meant by `limits.instances` key.

**Comment by stgraber** [comment]
Yeah, you'll find that we currently have both `limits.containers` and `limits.virtual-machines` implemented.

If I set `limits.containers=10` and `limits.virtual-machines=10`, I'm allowed 10 of each but there are environment where you'd want something like `limits.containers=20`, `limits.virtual-machines=10` and `limits.instances=20``, meaning that a user can have a maximum of 20 instances, all 20 can be containers but up to 10 may be virtual-machines.

More realistically, there are also users which will not care about the distinction between containers and virtual machines and just want to cap the maximum number of instances, regardless of type by just setting `limits.instances`.

**Comment by kevtheappdev** [comment]
Hi! My team and I have a solution for this, and it passes local runs of build/integration tests. How can we best test this addition locally before publishing our PR?

**Comment by tomponline** [comment]
@kevtheappdev have you followed the build instructions at https://github.com/lxc/lxd#installing-lxd-from-source and got a running LXD?
