### ISSUE TITLE
Add a new `restricted.cluster.target` project config key

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7926]
This key should default to `block`, effectively preventing the user from using `--target` to specify what cluster member to place a workload on or the ability to move a workload between members.

If configured to `allow`, the user will be allowed to place/move workloads on specific cluster members.

This may later be expanded to restricting targeting and placement to a specific set of cluster members, but for now let's just keep it simple.

**Comment by kevtheappdev** [comment]
My team would love to work on this one!

**Comment by stgraber** [comment]
Assigned to you!

**Comment by stgraber** [comment]
@kevtheappdev Do you still intend to work on this or should we un-assign so someone else can have a go at it?

**Comment by kevtheappdev** [comment]
Sorry for the late reply, been on winter break. You can go ahead and un-assign!

**Comment by presztak** [comment]
@stgraber Can I take this one as my second issue?

**Comment by stgraber** [comment]
Certainly, assigning to you!

**Comment by presztak** [comment]
@stgraber what in situation when we copy workload between projects e.g.:

`lxc cp c1 c2 --target n1 --target-project p1`

or copy workload to other remote

`lxc cp c1 r1:c2 --target n1 --target-project p1`

should we check config key for source or destination project?

**Comment by stgraber** [comment]
The destination is all we care about, the key is there to control where something can be created.
So when going across project, the target project is what matters.

**Comment by presztak** [comment]
@stgraber  I've idea to implement this in `checkRestriction` function from `lxd/project/permissions.go` so in this same place where other project restrictions are checked. What do you think about it? But other project restrictions  are dependant from `restricted` config key also. Should `restricted.cluster.target` be also dependant from this setting?

In another approach we can implement this directly in lxc commands but I think is not so DRY and consistent solution as first one.

**Comment by stgraber** [comment]
Yeah, `checkRestriction` sounds good and indeed this config key will be dependent on `restricted` being `true`.

We definitely cannot do this in the client alone, the keys under `restricted.*` must be enforced by the server and we consider any ways to bypass them to be security issues.
