### ISSUE TITLE
Add config option to disable rsync compression during migration

### ISSUE THREAD

**Issue by diegomontoya** [lxc/lxd#7936]
Rsync compression can cause up to 11x lxc copy degration over fast localprivate networks. 

Lxc copy which may use rsync which enables compression=2 causes two local servers (amd 3900x with nvme/raid0) with 10g nics to communicate at only 300Mbps with 100% cpu usage on a single cpu core. Disabling compression in source enabled lxc copy to reach 3500Mbps at 80% cpu usage on the same cpu core.

https://discuss.linuxcontainers.org/t/how-to-disable-rsync-compression-for-lxc-copy-100-cpu-and-slow-for-local-network-transfer/9028

**Comment by stgraber** [comment]
We'd do that by introducing a new pool property called `rsync.compression` which would default to true. When set to false, the migration logic would report compression as unsupported during transfer.

**Comment by drs-11** [comment]
Looks fun to me. Do I need to be assigned to work on this?

**Comment by stgraber** [comment]
Sure, assigning it to you!

**Comment by drs-11** [comment]
Hey so I dived into the code and wanted to ask if I'm going in the right direction.

Here is what I think is supposed to be done:
1) Add `rsync.compression` entry in `storagePoolConfigKeys`(in storage_pool_config.go) to validate entry
2) Add logic to `storagePoolFillDefault`(in storage_pool_config.go) to set the default bool value of `rsync.compression` as `True`
3) Provide the `rsync.compression` value from Config() to `rsync.Send` and `rsync.Recv` functions wherever they are located
4) Modify `rsyncFeatureArgs`(in rsync.go) to remove appending compression argument if `rsync.Compression` is set to True

Thoughts?

**Comment by stgraber** [comment]
Right, I'd expect you to have to:
 - Add to `storagePoolConfigKeys` as `validate.Optional(validate.isBool)`
 - Add the key to `doc/storage.md`
 - Add an API extension to `shared/api/version.go` and `doc/api-extensions.md`, call it `storage_rsync_compress` or something along those lines
 - Modify each of the storage drivers under `lxd/storage/drivers/` to strip `compress` from `rsyncFeatures` if the config key is set and its value isn't true

In theory that should do it. You don't need to actually modify the rsync calls or modify the FillDefault functions. Rsync will determine the right set of arguments based on the features negotiated during migration and FillDefault is only used for cases where we want the value to always be present in storage pool config. In this particular case, we'll know that an empty value means true, so something like this should do `if d.Config()["rsync.compression"] != "" && !shared.IsTrue(d.Config()["rsync.compresion"]) { drop the compress flag }`

**Comment by drs-11** [comment]
Alright yeah that is a better way and makes more sense. Thanks!
Will a unit-test be required with the PR?
