### ISSUE TITLE
`lxc config trust add` broken in snap

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#7937]
Is there a way to install LXD on Ubuntu in traditional 'apt install lxd' way?
LXD by itself has a sharp learning curve. Now add another forced complexity to it with snap.
Snapd adds 130-150 MB by itself, creates a core of 400 MB+ put itself everywhere:
/snap
/home/user/snap
/var/snap
keeps at least two versions of each app
and obfuscate the app, changes paths, complicate the privileges, containers are hidden and not mounted plain on zfs, so makes a direct access impossible without manually zfs mounting.
Why do we need to containerize the Container Management (LXD)?

Below an error caused by snap:
$ lxc config trust add /st1/tools/fc-templ/L/config/servercerts/FC-Center.crt
Error: open /var/lib/snapd/hostfs/st1/tools/fc-templ/L/config/servercerts/FC-Center.crt: no such file or directory

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXD version: 4.6

**Comment by stgraber** [comment]
The only package that we directly provide ourselves as upstream is the snap as that's the one requiring the least amount of effort from us to cover the most users at once.

We're quite supportive of packagers making other packages available for various distributions but so far nobody has stepped up to make native deb packages for Debian or Ubuntu.

**Comment by stgraber** [comment]
The error you're showing above is a trivial bug in that `lxc` command. I'll send a fix for it shortly.

**Comment by stgraber** [comment]
@kamzar1 are there symlinks somewhere in that path you provided?

**Comment by kamzar1** [comment]
Indeed there symlinks.
I try to do same, using hard links.
Thanks very much for the hint.
