### ISSUE TITLE
Candid executable file not found in $PATH

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#7938]
lxc config set candid.api.url http://10.0.6.32:8081
lxc config set candid.api.key OotnGM3FTgF8WysLpZZ46i0J0hx5pC2ItBdYgMWRGkg=
lxc config set core.https_address :8443
lxc remote add localhost https://localhost:8443 --auth-type=candid

Opening an authorization web page in your browser.
If it does not open, please open this URL:
http://10.0.6.32:8081/login?did=681a4139e0c0ed60fc3e4d039266fdbb117bc35f7eeac3068b3c05a7b70c77d3
user-open error: exec: "dbus-launch": executable file not found in $PATH
Certificate fingerprint: 15a638fba4279da0810b76c8cdea47d6941856e9535da5666c017d68012155fd
ok (y/n)? y
Opening an authorization web page in your browser.
If it does not open, please open this URL:
http://10.0.6.32:8081/login?did=2501ab59324753c76daf99e97e93ff18e6ee9968becf7ad6a8e835c5ecd072dc
user-open error: exec: "dbus-launch": executable file not found in $PATH
Error: cannot get discharge from "http://10.0.6.32:8081": cannot acquire discharge token: cannot wait: cannot wait: rendezvous wait timed out

**Comment by stgraber** [comment]
Sounds like you didn't open that second link fast enough and candid expired your authentication token somehow.

**Comment by stgraber** [comment]
Closing as support questions are better handled at https://discuss.linuxcontainers.org
