### ISSUE TITLE
lxc ls

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#7939]
lxc list --columns 
works only with --format csv and --table 
--format yaml and --format json do not honor the --columns choice and spit the whole config file.
Sure, it is called --columns which are naturally only in csv and tables given.
But it would be nice getting the keys/values of --columns in yaml and json as well without piping the lxc config show into third party 'yq' or 'jq' or 'grep' etc. to get a yaml result of:
cont-1
  status: RUNNING
cont-2
  status: STOPPED

`$lxc ls candid -c ns --format csv`
candid,RUNNING

`$ls candid -c ns --format yaml`

- architecture: x86_64
  config:
    image.architecture: amd64
    image.description: Ubuntu focal amd64 (20200915_os)
    image.os: Ubuntu
    image.release: focal
    image.serial: 20200915_os
    image.type: squashfs
    volatile.base_image: e7458c23f371475336bde98aab35766b2d46959b662473c0341bdc705039e963
    volatile.eth0.host_name: vethd5851c98
    volatile.eth0.hwaddr: 00:16:3e:fb:eb:5e
    volatile.eth1.host_name: veth32ed3ac2
    volatile.eth1.hwaddr: 00:16:3e:0b:dd:85
    volatile.idmap.base: "0"
    volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
....
a lot

**Comment by stgraber** [comment]
The JSON and YAML outputs aren't in the same format as our list outputs and can't easily be filtered especially since some fields come from deeply nested entries.

This complex filtering job is far better handled by a tool like jq or yq and so we don't expect to be changing this behavior.
