### ISSUE TITLE
Add concept of default architecture (global and per-project)

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7947]
Right now in a mixed architecture cluster, spawning an image like `ubuntu:18.04` will go to the least busy node, regardless of its architecture. This means that you may do one `lxc launch` and get x86_64, then do it again and get aarch64.

While technically fine since you didn't tell LXD what you want, it can still be a bit surprising.

We should add a `images.default_architecture` global config key and matching per-project key which lets the user tell LXD what architecture to go with when no specific one is specified as part of the image request.

**Comment by rctravers** [comment]
Hello, I'm a student at UT. Could I be assigned this Issue?

**Comment by stgraber** [comment]
Done!

**Comment by rctravers** [comment]
Working on these now. Do you have recommendations for where to start, or specifics about how you want them implemented?

**Comment by stgraber** [comment]
@rctravers Do you still intend to work on this or should we un-assign so someone else can have a go at it?

**Comment by presztak** [comment]
Can I work on this one?

**Comment by stgraber** [comment]
Absolutely!

**Comment by presztak** [comment]
@stgraber just to clarify, if `images.default_architecture` config is set (e.g. x86_64) and we launch instance we should pick least busy node but with x86_64 architecture. Am I right? Any other case/command which should also respect this config key?

**Comment by stgraber** [comment]
Yeah, that's right, when launching an image which isn't tied to a particular architecture, then we should restrict the nodes we consider to those of offering the default architecture. So in a mixed cluster with x86_64 and aarch64 nodes where the default_architecture is set to x86_64 either globally or in my project, I'd expect:

 - lxc launch images:ubuntu/20.04/arm64 => least busy aarch64 cluster member
 - lxc launch images:ubuntu/20.04 => least busy x86_64 cluster member

Whereas right now the latter one of those two would just pick the least busy overall, so unless you pass /amd64, you may end up with an arm64 instance.

**Comment by presztak** [comment]
@stgraber this issue is already done, pull request was not correctly linked to it.
