### ISSUE TITLE
Add support for port isolation

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7949]
It's been suggested that we should add a new security feature to LXD managed bridges.

This should be a new `security.port_isolation` boolean defaulting to false and where when set to true will turn on the `isolated` port feature for all ports.

There should be an exception for external interfaces and for tunnel devices when the system itself isn't a router (so where the tunnel will be used as an uplink).

**Comment by matthewa150** [comment]
I'd like to try and implement this if it's still available.

**Comment by stgraber** [comment]
Yep, definitely still available. Assigned it to you.

@tomponline should be able to give you more details on what's needed here.

**Comment by tomponline** [comment]
I believe the original suggestion came from here:

https://discuss.linuxcontainers.org/t/support-for-port-isolation-on-bridge-interfaces/9036

It has examples and explanation of what is trying to be achieved and why.

Looking at this file is the place to start: https://github.com/lxc/lxd/blob/master/lxd/device/nic_bridged.go

It contains the bridge NIC driver implementation, and is where the veth/tap pair is created to connect the container/VM to the bridge. 

- Validation for the config keys is done here: https://github.com/lxc/lxd/blob/master/lxd/device/nic_bridged.go#L43-L203
- And the actual setup of the port is done here: https://github.com/lxc/lxd/blob/master/lxd/device/nic_bridged.go#L236-L346

If you can add support initially for native bridging using the examples in the forum post, then we can explore adding OVS support after that.

**Comment by matthewa150** [comment]
I've been mulling over the code now for some time. I believe I have gotten the validation part down, but I'm a little lost as to how to use the `bridge` commands (from the [linked post](https://discuss.linuxcontainers.org/t/support-for-port-isolation-on-bridge-interfaces/9036)) in the `Start()` function. Any advice would be greatly appreciated!

**Comment by tomponline** [comment]
@matthewa150 please can you put up a draft PR of what you have so far so we can see it. With regard to the bridge commands I believe there was an example in the first reference https://discuss.linuxcontainers.org/t/support-for-port-isolation-on-bridge-interfaces/9036?u=tomp

I would suggest setting up a normal bridge using `lxc network create <net name>` and then manually trying those commands and checking they do indeed achieve the isolation desired.

**Comment by matthewa150** [comment]
Sorry for delay, I've made a preliminary pull request ( #8234 )
