### ISSUE TITLE
Prevent internal cluster migration of instances with backups

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#7959]
Backups cannot be moved, so if an instance has an existing backup, we need to have the user delete those backups prior to moving the instance.

**Comment by DDEFISHER** [comment]
I am going to look into fixing this.

**Comment by stgraber** [comment]
Okay, assigned to you.

I suspect the best spot for the check would be in `containerPost` in `lxd/instance_post.go`, the condition you care about for this is the `targetNode != ""` one which handles internal cluster instance move.

**Comment by DDEFISHER** [comment]
Hey I have a decent understanding of this at this point however I am not seeing the condition `targetNode != ""` be met even on a successful `lxc move ip-172-31-2-179:hello4 ip-172-31-11-25:hello2`. 

The container will be migrated fine however if I place a debug statement in that `if` block it will never get printed (it will get printed if I place it before or after that if block).

I am assuming I might be testing this wrong but not 100% sure. Any insight?  Example below... that debug statement is right before `if targetNode != ""` no targetNode is ever passed AFAICT.

```
ubuntu@ip-172-31-2-179:~/go/src/github.com/lxc/lxd$ lxc list
+--------+---------+------+------+-----------+-----------+-----------------+
|  NAME  |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |    LOCATION     |
+--------+---------+------+------+-----------+-----------+-----------------+
| hello4 | RUNNING |      |      | CONTAINER | 2         | ip-172-31-2-179 |
+--------+---------+------+------+-----------+-----------+-----------------+
```
```
ubuntu@ip-172-31-2-179:~/go/src/github.com/lxc/lxd$ lxc move ip-172-31-2-179:hello4 ip-172-31-11-25:hello2
WARN[10-05|18:18:21] target node:
```
```
ubuntu@ip-172-31-2-179:~/go/src/github.com/lxc/lxd$ lxc list
+--------+---------+------+------+-----------+-----------+-----------------+
|  NAME  |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |    LOCATION     |
+--------+---------+------+------+-----------+-----------+-----------------+
| hello2 | RUNNING |      |      | CONTAINER | 2         | ip-172-31-11-25 |
+--------+---------+------+------+-----------+-----------+-----------------+
```

**Comment by stgraber** [comment]
That's because you're not using a cluster, you're just dealing with two LXD servers transferring instances between each other.

https://linuxcontainers.org/lxd/docs/master/clustering
https://discuss.linuxcontainers.org/t/lxd-cluster-on-raspberry-pi-4/9076

You can likely reset your two systems and cluster them together, at which point you should hit the issue when doing:
 - lxc move hello --target node02

Assuming you name your servers node01 and node02 and the instance is currently on node01.

**Comment by DDEFISHER** [comment]
Just to be clear I thought I was using a cluster. 

```
ubuntu@ip-172-31-2-179:~/go/src/github.com/lxc/lxd$ lxc cluster list
+-----------------+---------------------------+----------+--------+-------------------+--------------+----------------+
|      NAME       |            URL            | DATABASE | STATE  |      MESSAGE      | ARCHITECTURE | FAILURE DOMAIN |
+-----------------+---------------------------+----------+--------+-------------------+--------------+----------------+
| ip-172-31-2-179 | https://172.31.2.179:8443 | NO       | ONLINE | fully operational | x86_64       | default        |
+-----------------+---------------------------+----------+--------+-------------------+--------------+----------------+
| ip-172-31-11-25 | https://172.31.11.25:8443 | YES      | ONLINE | fully operational | x86_64       | default        |
+-----------------+---------------------------+----------+--------+-------------------+--------------+----------------+
```

**Comment by DDEFISHER** [comment]
ah okay the secret sauce I was missing was the wrong command.

**Comment by DDEFISHER** [comment]
`lxc move hello4 --target ip-172-31-2-179` vs `lxc move ip-172-31-2-179:hello4 ip-172-31-11-25:hello2`

**Comment by DDEFISHER** [comment]
Thanks for the help I can move forward now

**Comment by stgraber** [comment]
Haha, that explains it :)
