### ISSUE TITLE
Make it possible to turn a remote container into an image

### ISSUE THREAD

**Issue by hallyn** [lxc/lxd#796]
Currently (in my PR) 'lxc publish' only works when publishing a container to an image on the same host.

To publish to a container to a remote image, it has been suggested that we would get a websocket from the source server and pass that on to the image server, so that the source can copy the generated imagefile over the websocket.

However, there is no rest call like /1.0/containers/export to request this websocket from the source server.

Should we add /1.0/containers/<container>/export to the rest api spec?

**Comment by hallyn** [comment]
Make that /1.0/containers/<name>/export of course.

**Comment by stgraber** [comment]
so my thought was actually to do a POST to /1.0/images on the source server but with a keyword telling it not to record the image in the image store, but instead provide the image over websocket. The target server can then connect to the source to fetch the image, then publish it in its image store.
