### ISSUE TITLE
Orphan qemu process on VM start / KVM failure

### ISSUE THREAD

**Issue by Saviq** [lxc/lxd#7962]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04.1
 * The output of "lxc info": [lxc-info.txt](https://github.com/lxc/lxd/files/5307469/lxc-info.txt)

# Issue description

I'm in a weird state where a VM doesn't start, as far as LXD is concerned, but qemu is left orphaned.

# Steps to reproduce

 1. `lxc start instance`
 1. observe that it doesn't start
 1. `lxc start instance`
 1. error:
  ```
  lxc --project multipass start snapcraft-egmde-confined-desktop
  Error: Failed to run: forklimits limit=memlock:unlimited:unlimited -- /snap/lxd/17320/bin/qemu-system-x86_64 -S -name snapcraft-egmde-confined-desktop -uuid 598bce0e-ff89-4d7a-860e-df4b2f66298b -daemonize -cpu host -nographic -serial chardev:console -nodefaults -no-reboot -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=deny,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/multipass_snapcraft-egmde-confined-desktop/qemu.conf -pidfile /var/snap/lxd/common/lxd/logs/multipass_snapcraft-egmde-confined-desktop/qemu.pid -D /var/snap/lxd/common/lxd/logs/multipass_snapcraft-egmde-confined-desktop/qemu.log -chroot /var/snap/lxd/common/lxd/virtual-machines/multipass_snapcraft-egmde-confined-desktop -smbios type=2,manufacturer=Canonical Ltd.,product=LXD -runas lxd: qemu-system-x86_64: cannot create PID file: Cannot lock pid file: Resource temporarily unavailable
  : Process exited with a non-zero value
  Try `lxc info --show-log snapcraft-egmde-confined-desktop` for more info
  ```

# Information to attach

 - [x] Container log (`lxc info NAME --show-log`): [lxc-info.txt](https://github.com/lxc/lxd/files/5307521/lxc-info.txt)
 - [x] Container configuration (`lxc config show NAME --expanded`): [lxc-config.txt](https://github.com/lxc/lxd/files/5307527/lxc-config.txt)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log): [lxd-log.txt](https://github.com/lxc/lxd/files/5307532/lxd-log.txt)
 - [x] Output of the client with --debug: [lxc-start-debug.txt](https://github.com/lxc/lxd/files/5307545/lxc-start-debug.txt)
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue): [lxc-monitor.txt](https://github.com/lxc/lxd/files/5307549/lxc-monitor.txt)

**Comment by stgraber** [comment]
I've seen this before and killing the previous qemu does usually resolve it.
However I'm not sure what's the right way to get the system into such a situation or why that previous qemu just won't die on its own :)

Is this something you can make repeatedly happen somehow?

@tomponline any ideas?

**Comment by Saviq** [comment]
> I've seen this before and killing the previous qemu does usually resolve it.
> However I'm not sure what's the right way to get the system into such a situation or why that previous qemu just won't die on its own :)
> 
> Is this something you can make repeatedly happen somehow?

Right now, yes. This wasn't a one off, I can do kill the qemu, and start and go into the same situation again.

**Comment by Saviq** [comment]
I wonder if running a VirtualBox VM at the time when you start a LXD one would go there. KVM and VBox don't like each other, so may well be a way to reproduce?

**Comment by tomponline** [comment]
@Saviq I'd be interested in getting more info about the state of the qemu process at stage 2 of your original post, can you show the output of `lxc info NAME --show-log` after the initial failure to launch? Also can you advise what you mean by "observe it doesn't start" is there no qemu process at all?

**Comment by Saviq** [comment]
@tomponline,

> @Saviq I'd be interested in getting more info about the state of the qemu process at stage 2 of your original post, can you show the output of `lxc info NAME --show-log` after the initial failure to launch?

It's this initially:
```
 lxc info --project multipass --show-log snapcraft-egmde-confined-desktop
Name: snapcraft-egmde-confined-desktop
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/09/30 16:23 UTC
Status: Running
Type: virtual-machine
Profiles: default
Pid: 3547556
Resources:
  Processes: -1
  Disk usage:
    root: 159.74kB

Log:
```

And a few seconds after:
```
 lxc info --project multipass --show-log snapcraft-egmde-confined-desktop
Name: snapcraft-egmde-confined-desktop
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/09/30 16:23 UTC
Status: Stopped
Type: virtual-machine
Profiles: default
Pid: 3547556
Resources:
  Processes: 0

Log:

KVM internal error. Suberror: 3
extra data[0]: 800000ec
extra data[1]: 31
extra data[2]: 83
extra data[3]: 38fc0
RAX=0000000000000000 RBX=0000000000000001 RCX=0000000000000001 RDX=0000000000000182
RSI=ffff9eacfdb1cb48 RDI=0000000000000001 RBP=ffffa9fe00077e90 RSP=ffffa9fe00077e78
R8 =000000000c189381 R9 =0000000000000000 R10=0000000000002400 R11=0000000000002400
R12=0000000000000001 R13=ffff9eac80196e00 R14=0000000000000000 R15=0000000000000000
RIP=ffffffffb97530ae RFL=00000246 [---Z-P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 0000000000000000 ffffffff 00c00000
CS =0010 0000000000000000 ffffffff 00a09b00 DPL=0 CS64 [-RA]
SS =0000 0000000000000000 ffffffff 00c00000
DS =0000 0000000000000000 ffffffff 00c00000
FS =0000 0000000000000000 ffffffff 00c00000
GS =0000 ffff9eacfdb00000 ffffffff 00c00000
LDT=0000 0000000000000000 ffffffff 00c00000
TR =0040 fffffe0000036000 0000206f 00008b00 DPL=0 TSS64-busy
GDT=     fffffe0000034000 0000007f
IDT=     fffffe0000000000 00000fff
CR0=80050033 CR2=00000000ffffffff CR3=000000005600a001 CR4=001606a0
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000d01
Code=30 8b 05 3f 4f 8d 00 85 c0 7e 07 0f 00 2d 16 dd 4b 00 fb f4 <8b> 05 d4 a4 78 00 65 44 8b 25 74 d0 8b 46 85 c0 0f 8f 85 00 00 00 5b 41 5c 41 5d 5d c3 65
```

> Also can you advise what you mean by "observe it doesn't start" is there no qemu process at all?

No, qemu is running:
```
 ps aux | grep qemu
lxd      3547556 21.8  2.4 2984608 196904 ?      Sl   22:48   0:15 /snap/lxd/17320/bin/qemu-system-x86_64 -S -name snapcraft-egmde-confined-desktop -uuid 598bce0e-ff89-4d7a-860e-df4b2f66298b -daemonize -cpu host -nographic -serial chardev:console -nodefaults -no-reboot -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=deny,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/multipass_snapcraft-egmde-confined-desktop/qemu.conf -pidfile /var/snap/lxd/common/lxd/logs/multipass_snapcraft-egmde-confined-desktop/qemu.pid -D /var/snap/lxd/common/lxd/logs/multipass_snapcraft-egmde-confined-desktop/qemu.log -chroot /var/snap/lxd/common/lxd/virtual-machines/multipass_snapcraft-egmde-confined-desktop -smbios type=2,manufacturer=Canonical Ltd.,product=LXD -runas lxd
```

But LXD doesn't think it is:
```
 lxc ls --project multipass
+----------------------------------+---------+------+------+-----------------+-----------+
|               NAME               |  STATE  | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+----------------------------------+---------+------+------+-----------------+-----------+
| snapcraft-egmde-confined-desktop | STOPPED |      |      | VIRTUAL-MACHINE | 0         |
+----------------------------------+---------+------+------+-----------------+-----------+
```

**Comment by Saviq** [comment]
Just as a data point, this one instance has this issue (corrupted image¿?), I can launch new VMs fine. That doesn't change the fact that LXD should realize the original error :)
