### ISSUE TITLE
Unable to refresh snap: Failed to get unit file state for snap.lxd.activate.service: No such file or directory

### ISSUE THREAD

**Issue by itcrowdsource** [lxc/lxd#7964]
# Required information

 * Distribution: Ubuntu
Distribution version: 18.04 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-118-generic
   * LXC version: 4.0.4
   * LXD version: 4.6
   * Storage backend in use: zfs

# Issue description

LXD stopped working suddenly. Unable to launch lxc command. Snap refresh fails:
root@VM1:~# snap refresh lxd
error: cannot perform the following tasks:
- Stop snap "lxd" services ([--root / is-enabled snap.lxd.daemon.service] failed with exit status 1: Failed to get unit file state for snap.lxd.daemon.service: No such file or directory
)

Also unable to remove LXD
root@VM1:~# snap remove lxd
error: cannot perform the following tasks:
- Stop snap "lxd" services ([--root / is-enabled snap.lxd.daemon.service] failed with exit status 1: Failed to get unit file state for snap.lxd.daemon.service: No such file or directory
)

# Steps to reproduce

 1. snap refresh lxd
 2. Error message being showed

# Information to attach
Important note: This server is one of the nodes of a three node LXD cluster.

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
This would be a snapd bug unfortunately...

I've seen some variants of this popping up every now and then so it looks like something is racy.

Could you report this at https://forum.snapcraft.io and post a link here so I can go comment?

(Closing the issue as it's external to us but will definitely follow it over there and help you get back online)

**Comment by itcrowdsource** [comment]
@stgraber here's the link to the forum post:

https://forum.snapcraft.io/t/unable-to-refresh-snap-failed-to-get-unit-file-state-for-snap-lxd-activate-service-no-such-file-or-directory/20311
