### ISSUE TITLE
Super jumbo frame support

### ISSUE THREAD

**Issue by ne-vlezay80** [lxc/lxd#7972]
# Required information

 * Distribution: Arch Linux
 * Distribution version: stream
 * The output of "lxc info" or if that fails: 
   * Kernel version:  5.4.24-rt15-2-rt
   * LXC version: 4.0.4
   * LXD version: 4.6
   * Storage backend in use: 5.7

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Create and set mtu for interface >9202

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

------
#> lxc config device add frr-test eth0 nic nictype=p2p host_name=cnt-frr-test.0 name=eth0 mtu=9216
Error: Invalid devices: Device validation failed for "eth0": Invalid value for device option "mtu": Out of MTU range (1280-9202) "9216"

Please add support super jumbo frame support, as with old versions.

**Comment by tomponline** [comment]
This seems like a fine change to make, but I'd like to understand more about what your application is here, as this setting will set the MTU of the veth interfaces at the network layer, rather than setting the MTU at the link layer (where link layer MTUs of 9216 are commonly seen when the network layer's MTU is 9000).

Are you tunnelling another protocol over the veth that needs MTU of 9000? 

Thanks

**Comment by ne-vlezay80** [comment]
You using mtu = 16384 in internal lxd container server between virtal
machines. External network inside hypervisor using mtu = 16384 bytes.

> Are you tunnelling another protocol over the veth that needs MTU of 9000?

**Comment by tomponline** [comment]
So what is the maximum mtu you're looking to set, the original post suggested you were trying to set an MTU of 9216, but are you trying to set something higher than that (16384?). Thanks

**Comment by ne-vlezay80** [comment]
> So what is the maximum mtu you're looking to set, the original post suggested you were trying to set an MTU of 9216, but are you trying to set something higher than that (16384?). Thanks

I used mtu = 16384 for local lxd cluster. mtu = 9216 i instelled in test lxd server.
