### ISSUE TITLE
Kill hung qemu processes when doing lxc stop on errored VM

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#7995]
Following on from https://github.com/lxc/lxd/pull/7966, we should investigate allowing an `lxc stop` of an errored/hung qemu process that no longer has the monitor socket responding, but killing the remaining qemu process.

**Comment by rctravers** [comment]
Hello, I'm a student at UT. Could I be assigned this Issue?

**Comment by stgraber** [comment]
Done!

**Comment by rctravers** [comment]
Working on these now. Do you have recommendations for where to start, or specifics about how you want them implemented?

**Comment by tomponline** [comment]
There was a brief discussion about how to approach this on https://github.com/lxc/lxd/pull/7966 (see https://github.com/lxc/lxd/pull/7966#issuecomment-702205356 and https://github.com/lxc/lxd/pull/7966#issuecomment-702241991).

I wonder if in order to avoid killing an unrelated process, we should try and inspect the running process's command line to check that its qemu and has a matching uuid argument for the VM we expect.

**Comment by tomponline** [comment]
@rctravers so after chatting with @stgraber yesterday, although the ideal approach would be to use a pidfd wrapper, for now we think a reasonably safe approach would be to detect when `statusCode` returns `api.Error` and then inspect the command running for the recorded pid. If the command running includes the word `qemu` and has an argument `-uuid` followed by a UUID value that matches the VM's `volatile.uuid` config key. If so then we can kill the process and be confident we aren't killing an unrelated process that happens to have jumped in and used the same PID.

**Comment by stgraber** [comment]
@rctravers Do you still intend to work on this or should we un-assign so someone else can have a go at it?
