### ISSUE TITLE
Introduce new `virtual-machine-restarted` and `container-restarted` events

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8010]
Right now when an instance self-restarts (reboot inside the instance), all we get is a `container-started` type event.

Instead, we should add logic so that instance initiated reboots only log a single `container-restarted` event.
Similarly, running `lxc restart blah` should also only log a single `container-restarted` event rather than the current `container-stopped` + `container-started` combination.

**Comment by dlemel8** [comment]
Hey @stgraber  , I want to do this.
Can you guide me a bit?
Thanks.

**Comment by stgraber** [comment]
Assigned it to you.

You can see what events are emitted today with `lxc monitor --type=lifecycle` and then restart a container/virtual-machine both from inside (`lxc exec NAME reboot`) or outside (`lxc restart NAME`).

The current logic can be found in `lxd/instance/drivers/driver_lxc.go` and `lxd/instance/drivers/driver_qemu.go`.

I suspect I would do changes in this order:

 - Add the new event to the reboot section of `onStop` in both lxc and qemu
 - Introduce a new `Restart(timeout time.Duration) error` function in both lxc and qemu (base logic off of what's in `lxd/instance_state.go`)
 - Add that function to the interface in `lxd/instance/instance_interface.go`
 - Change the current restart logic to use that function in `lxd/instance_state.go`
 - Introduce a new operationlock for `restart` and use checks for that to avoid emitting needless stop/start events when in a restart

With all that done, running either `lxc exec NAME reboot` or `lxc restart NAME` against either a container or virtual-machine should yield just a single `container-restarted` or `virtual-machine-restarted` event.

**Comment by stgraber** [comment]
Let me know if you have more specific questions when looking at the various bits.

Also feel free to send PRs as you go through this. Pretty much ever bullet-point above should be an improvement on its own and so could be submitted and be merged progressively.
