### ISSUE TITLE
Record requestor as part of `lifecycle` events

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8011]
`lifecycle` events would be quite useful for auditing if they would also record who asked for a given action.

To do this, I suspect we'll want to:
 - Refactor the current SendLifecycle calls to be done through a common function on instance driver
 - Have that function take care of adding context like instance name, instance project, resources, ...
 - Add some way to store the requestor onto the struct too and seed that from the `user` field on requests (when available)
 - Then add that context to the lifecycle events.

**Comment by my5t3ry** [comment]
I start working on this issue : )
