### ISSUE TITLE
Support ceph msgr2 address config 

### ISSUE THREAD

**Issue by brettmilford** [lxc/lxd#8018]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-48-generic
   * LXC version: 4.6
   * LXD version: 4.6
   * Storage backend in use:

# Issue description
When creating a lxd ceph storage pool for a Ceph Octopus cluster I encountered the following error:
```
~$ lxc storage create lxd-ceph-test ceph
Error: Failed to run: ceph --name client.admin --cluster ceph osd pool create lxd-ceph-test 32: unable to parse addrs in '[v2:192.168.1.156:3300,v1:192.168.1.156:6789]'
[errno 22] error connecting to the cluster
```
This is the address format for msgr v2 and is supported by all the recent ceph tools [0], i.e. running `ceph --name client.admin --cluster ceph osd pool create lxd-ceph-test 32` directly creates the pool (but doesn't register it with lxd). 

[0] https://docs.ceph.com/en/latest/rados/configuration/msgr2

**Comment by brettmilford** [comment]
This might be a limitation of the luminous client packaged with lxd snap.
```
~$ snap run --shell lxd --login
bash-4.4$ ceph --version
ceph version 12.2.13 (584a20eb0237c657dc0567da126be145106aa47e) luminous (stable)
```

**Comment by stgraber** [comment]
It's not a LXD thing, it's a snap thing. The snap ships with Ceph 12 which does not understand the new addresses.
We'll be rebasing the snap on Ubuntu 20.04 in the near feature which will give us Ceph 15.

Until then, you can configure the snap to use the client from the host system with:
 - snap set lxd ceph.external=true
 - systemctl reload snap.lxd.daemon

Which will take care of this.
