### ISSUE TITLE
Restarting a container doesn't pick up configuration changes

### ISSUE THREAD

**Issue by jgriffiths1993** [lxc/lxd#802]
I've noticed that `lxc restart <name>` does not pick up configuration changes, whilst `lxc stop <name> && lxc start <name>` does.

Specifically, I've seen this when changing NIC configuration.

**Comment by stgraber** [comment]
so there are two things that can happen on restart:
 - A restart signal is sent to the container, the restart is then entirely done inside the container and there's nothing lxd can do (so no config change).
 - The container doesn't handle the signal and lxd ends up doing stop+start, in which case we can apply config changes.

Maybe we can get lxd to figure out that the config changed and so do a clean shutdown+start in the event that the config changed?

**Comment by jgriffiths1993** [comment]
Good shout; I'll try and get to work on that soon

**Comment by stgraber** [comment]
I've implemented restart as stop+start now, so this should be solved.
