### ISSUE TITLE
Question: How can I set noatime mount option if I use lvm as storage backend?

### ISSUE THREAD

**Issue by catsem** [lxc/lxd#8027]
Hello,

for performance reasons I'd like to set the noatime mount flag for a single container (I/O consuming application).
I'm using lvm as storage backend.
Already tried to set the volume.block.mount_options=atime at my storage pool which did not have the desired effect.

How can it be done?

OS: Ubuntu 18.04
LXD 3.0.3

Thanks and best regards.

**Comment by tomponline** [comment]
@catsem I tried this and can confirm that `atime` specifically doesn't take effect, however using `noatime` does.

I've also confirmed that this is behaviour of the `mount` command too, which suggests that `atime` is considered a default, or at least equivalent to the default `relatime` option which is used instead.

See https://ubuntuforums.org/showthread.php?t=1530291

**Comment by catsem** [comment]
Sorry to bother you again.
You are right I had a typo in my original question it supposed to mean volume.block.mount_options=**noatime**. Shame on me. I edited my question in order to fix it. 

But still I couldn't get it to work.

```
~$ lxc storage show pool1
config:
  lvm.thinpool_name: LXDPool
  lvm.vg_name: vg00
  source: vg00
  volatile.initial_source: vg00
  volume.block.mount_options: noatime
description: ""
name: pool1
driver: lvm
used_by:
- /1.0/containers/repo
- /1.0/profiles/default
status: Created
locations:
- none
```

When I start my container "repo" with this config it leads to the following mount options (output of mount command):
`/dev/mapper/vg00-containers_repo on /var/lib/lxd/storage-pools/pool1/containers/repo type ext4 (rw,relatime,discard,stripe=64,data=ordered)`

**Comment by tomponline** [comment]
@catsem that setting only applies to new volumes, and the value of that setting is copied into each volume as the `block.mount_options` setting.

You can see the current volume config using:

```
lxc storage volume show <storage pool> container/<container name>`
```

**Comment by catsem** [comment]
@tomponline 
Thanks for pointing me the right direction.
It's also possible to change the mount options of an existing container (that answers my question). 
e.g.
`lxc storage volume set <storage pool> container/<container name> block.mount_options discard,noatime`
