### ISSUE TITLE
Issue with last snap refresh for latest/beta

### ISSUE THREAD

**Issue by stephenjamieson** [lxc/lxd#8051]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-51-generic 
   * LXC version: 
   * LXD version: 4.7, latest/beta
   * Storage backend in use: BTRFS

# Issue description

Starting LXD unix socket failing

# Steps to reproduce

 1. Try to start lxd socket

# Information to attach

Issue is here when running with debug

```
INFO[10-19|00:47:07] Applying patch "network_ovn_enable_nat" 
DBUG[10-19|00:47:07] Database error: &errors.errorString{s:"sql: Scan error on column index 3, name \"description\": converting NULL to string is unsupported"} 
EROR[10-19|00:47:07] Failed to start the daemon: Failed applying patch "network_ovn_enable_nat": sql: Scan error on column index 3, name "description": converting NULL to string is unsupported 
INFO[10-19|00:47:07] Starting shutdown sequence 
```

**Comment by stgraber** [comment]
Not sure what's causing this error but it's triggered because of a recent patch that @tomponline added.

Could you make a tarball of `/var/snap/lxd/common/lxd/database` and send it to me at: stgraber at ubuntu dot com

That will let me try a quick fix for your case and let us reproduce the issue to introduce a proper fix tomorrow.

**Comment by stephenjamieson** [comment]
Sent

**Comment by stgraber** [comment]
Thanks, I'll look at it shortly.

Until then, I suspect that putting this in `/var/snap/lxd/common/lxd/database/patch.global.sql` will do the trick:
```
UPDATE networks  SET description="" WHERE description IS NULL;
```

Then try starting LXD.

**Comment by stephenjamieson** [comment]
That worked, thank you @stgraber

**Comment by stgraber** [comment]
Managed to get your DB loaded and have the issue show up, going to test a proper fix now.

**Comment by stgraber** [comment]
Sent a fix which worked with your database here.
