### ISSUE TITLE
Nonsenical answers to ZFS pool creation question during lxd init

### ISSUE THREAD

**Issue by mtausig** [lxc/lxd#8060]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-47-generic
   * LXC version:  (contained with snap)
   * LXD version: 4.7
   * Storage backend in use: ZFS

# Issue description

After installing LXD via snap and during the run of lxd init, one of the questions contains nonsensical answers:

```bash
$ sudo lxd init

Would you like to use LXD clustering? (yes/no) [default=no]:    
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (ceph, btrfs, dir, lvm, zfs) [default=zfs]: 
Create a new ZFS pool? (yes/no) [default=yes]: 
Would you like to use an existing empty disk or partition? (yes/no) [default=no]:
...
```

The last question cannot be answered by `yes` or `no`, but that's the only possible answers presented to the user. 
The answers should be replaced by `empty disk` and `partition`.

# Steps to reproduce

 1. Install lxd with `snap install lxd`
 2. Run `sudo lxd init`

**Comment by stgraber** [comment]
We don't care if it's an empty disk or an empty partition, we're asking if you have one of those.

**Comment by tomponline** [comment]
We will clarify the question to avoid confusion.
