### ISSUE TITLE
`virtfs-proxy-helper` not in `$PATH`

### ISSUE THREAD

**Issue by Foxboron** [lxc/lxd#8065]
# Required information

 * Distribution: Arch Linux
 * Distribution version: rolling
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 4.0.4
   * LXD version: 4.7
   * Storage backend in use: VM(?)

# Issue description

Currently the code assumes `virtfs-proxy-helper` is always somewhere in `$PATH` when executed, and it doesn't seem like there is any attempts verifying it's in path or look in alternative paths. 

https://github.com/lxc/lxd/blob/f64cdea54fcbcb1d434bf2ce1bc3961e54d26529/lxd/device/disk.go#L509

In Arch the binary is under `/usr/lib/qemu/` which is not included in `$PATH`. I'm unsure if Arch is the only distro that keeps this outside of `$PATH`, or if this is a bug waiting to be discovered.

# Steps to reproduce

Ensure `virtfs-proxy-helper` is not in `$PATH`
```
# lxc config device add arch-vm pkgs disk source=/home path=/mnt
# lxc start arch-vm
Error: Failed to start device "pkgs": Failed to start virtfs-proxy-helper for device "pkgs": Unable to start process: exec: "virtfs-proxy-helper": executable file not found in $PATH
```

For the sake of having this behave nicely with Arch I'm probably just going to apply the following patch:

```diff
diff --git a/lxd/device/disk.go b/lxd/device/disk.go
index 4f728007e..c0bc8c370 100644
--- a/lxd/device/disk.go
+++ b/lxd/device/disk.go
@@ -506,7 +506,7 @@ func (d *disk) startVM() (*deviceConfig.RunConfig, error) {
                                        // Start the virtfs-proxy-helper process in non-daemon mode and as root so that
                                        // when the VM process is started as an unprivileged user, we can still share
                                        // directories that process cannot access.
-                                       proc, err := subprocess.NewProcess("virtfs-proxy-helper", []string{"-n", "-u", "0", "-g", "0", "-s", sockPath, "-p", srcPath}, "", "")
+                                       proc, err := subprocess.NewProcess("/usr/lib/qemu/virtfs-proxy-helper", []string{"-n", "-u", "0", "-g", "0", "-s", sockPath, "-p", srcPath}, "", "")
                                        if err != nil {
                                                return nil, err
                                        }
```

**Comment by stgraber** [comment]
On Debian/Ubuntu, virtfs-proxy-helper is in PATH at least.

**Comment by stgraber** [comment]
We can easily enough add logic to check for it in both PATH and /usr/lib/qemu though

**Comment by snhardin** [comment]
Happy Hacktoberfest! I'd like to work on this, please. 🙂

**Comment by stgraber** [comment]
Hey there, assigned it to you!

In this case, you most likely want to poke `exec.LookPath` to see if `virtfs-proxy-helper` can be found. If so, then keep passing `virtfs-proxy-helper` to subprocess. If not, use `shared.PathExists` on `/usr/lib/qemu/virtfs-proxy-helper`, if that exists, then pass that path to subprocess.
