### ISSUE TITLE
`lxc rename` then `lxc import` without running container in between results in a broken container

### ISSUE THREAD

**Issue by feileacan** [lxc/lxd#8071]
# Required information

Trimmed `lxc info` output
```
config: {}
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  project: default
  server: lxd
  server_clustered: false
  server_name: localhost
  server_version: "3.17"
  storage: ""
  storage_version: ""
```

# Issue description

`lxc rename` then `lxc import` without running container in between results in a broken container.

# Steps to reproduce

1. Create container "penguin"
2. `lxc rename penguin foo`
3. Shut down LXD and delete the database (so we can import the container)
4. Restart LXD
5. `lxd import foo`

You now end up with a container called penguin but in a folder called foo. `lxc start foo` reports no container called foo, and `lxc start penguin` gives "Error: Common start logic: Expand symlinks: lstat /mnt/stateful/lxd/containers/penguin: no such file or directory". You also get errors for trying to rename the container, and probably other operations.

The cause is that the name of the container in backup.yaml isn't updated upon lxc rename, only after running the container is the new name written out. To recover you have to rename the folder on the filesystem.

**Comment by tomponline** [comment]
@feileacan so I can try and re-create, which storage pool driver are you using? Thanks

**Comment by stgraber** [comment]
@tomponline based on LXD version and container name, this is on a Chromebook, so storage is btrfs.

It will be interesting to see if our recent work on backups has somehow fixed this already.

**Comment by tomponline** [comment]
@stgraber ok thanks

**Comment by feileacan** [comment]
Yup, it is indeed btrfs on Chromebook.

**Comment by tomponline** [comment]
@feileacan thanks I will get onto this one next.

**Comment by tomponline** [comment]
@stgraber have confirmed using `dir` backend that a similar issue still exists in main branch.

```
lxdarg import foo
Error: Instance name in request "c2" doesn't match instance name in backup config "foo"
```

Will work on a fix (re-writing backup.yaml when renaming).
