### ISSUE TITLE
Wrong path shown in lxc rename error message

### ISSUE THREAD

**Issue by diegomontoya** [lxc/lxd#8084]
Ubuntu 20.04/Snap LXD 4.7

```
#db is on storage default1
lxc rename db-fast db
Error: Rename instance: Failed to rename '/var/snap/lxd/common/lxd/storage-pools/default2/containers/db-fast' to '/var/snap/lxd/common/lxd/storage-pools/default2/containers/db': rename /var/snap/lxd/common/lxd/storage-pools/default2/containers/db-fast /var/snap/lxd/common/lxd/storage-pools/default2/containers/db: file exists
```

The issue is not about the error but the paths shown in the error which doesn't exist. 

I have two storage enabled for lxd, ```default1``` and ```default2```. Both are simple ext4 dirfs mounted to two different hard drives.

```
+----------+-------------+--------+-------------------+---------+
|   NAME   | DESCRIPTION | DRIVER |      SOURCE       | USED BY |
+----------+-------------+--------+-------------------+---------+
| default1 |             | dir    | /raid0/lxd-data-1 | 12      |
+----------+-------------+--------+-------------------+---------+
| default2 |             | dir    | /raid0/lxd-data-2 | 4       |
+----------+-------------+--------+-------------------+---------+
```

The error is that the ```default2``` storage somehow contains a "db" container which doesn't exists. I have confirmed the empty directory exists in ```/raid0/lxd-data-2/containers/db``` but the path shown in the error message is not the real path for the file conflict.

**Comment by stgraber** [comment]
The path in the error is absolutely correct from LXD's point of view.
You can take a peak at what LXD sees through `/var/snap/lxd/common/mntns`.

**Comment by stgraber** [comment]
In short, LXD runs in a mount namespace, letting it mount things as it pleases without messing up what you see on your host system. With your configuration, LXD will have bind-mounted /raid0/lxd-data1 onto /var/snap/lxd/common/lxd/storage-pools/default and same for default2 and it then operates under those bind-mounts.

This allows for LXD to never actually do anything outside of /var/snap/lxd/common/lxd regardless of where the storage actually came from. That's far easier to audit and test on our end.

**Comment by diegomontoya** [comment]
@stgraber Thanks for the detailed explanation. Now everything is clear. The path shown in errors are not host paths but paths within the roofs used by LXD with is by design an isolation feature from external OS/host.
