### ISSUE TITLE
github.com/CanonicalLtd/candidclient is archived and no longer maintained - please switch to github.com/canonical/candid

### ISSUE THREAD

**Issue by nodens** [lxc/lxd#8085]
# Required information

 * Distribution: Debian
 * Distribution version: unstable
   * LXD version: 4.0.x

# Issue description
I recently resumed working on the packaging of LXD stable in Debian. That's now possible because the libco/dqlite issue (local fork needing patch) is now solved, thanks for that :)

The first step is to package the many Go library that aren't yet in Debian.

Among them, github.com/CanonicalLtd/candidclient is a problem: I'm not going to package an unmaintained library in Debian.
According to the readme, the mapping to packages of github.com/canonical/candid are as follow:

```
gopkg.in/CanonicalLtd/candidclient.v1               -> github.com/canonical/candid/candidclient
gopkg.in/CanonicalLtd/candidclient.v1/candidtest    -> github.com/canonical/candid/candidtest
gopkg.in/CanonicalLtd/candidclient.v1/params        -> github.com/canonical/candid/params
gopkg.in/CanonicalLtd/candidclient.v1/redirect      -> github.com/canonical/candid/candidclient/redirect
gopkg.in/CanonicalLtd/candidclient.v1/ussodischarge -> github.com/canonical/candid/candidclient/ussodischarge
gopkg.in/CanonicalLtd/candidclient.v1/ussologin     -> github.com/canonical/candid/candidclient/ussologin
```

If I'm not mistaken, that's a couple lines patch in lxd/daemon.go, right ?

I guess I could patch the Debian package, but it would be much better to do that upstream, and since I'm not a candid (or macaroon) user, I'm a bit uncomfortable with providing a PR myself since I have no way to test it properly.

Thanks!

**Comment by nodens** [comment]
PS: I'd really appreciate if such a change was pushed to the stable-4.0 branch, as that's the on I intend to package ;)

**Comment by stgraber** [comment]
Ah yeah, I didn't notice that they moved it over, we'll definitely update that and it will make it to stable-4.0.

**Comment by nodens** [comment]
Thanks!
