### ISSUE TITLE
Add a core.default_compression key

### ISSUE THREAD

**Issue by hallyn** [lxc/lxd#810]
This is for the compression algorithm to use when publishing images.  By default it should be gzip, but xz would be at least one other alternative.  We also may want to add a compression-level key (or built it in, i.e. "xz9" vs "gz1").

**Comment by hallyn** [comment]
Then again maybe we shouldn't - it's the kind of thing that'll complicate the code for little actual benefit, with likelyhood for little-used options to silently regress.

**Comment by stgraber** [comment]
well, we already have to support them all for unpack, so supporting them for compression should be easy enough. Compression level would also be pretty simple assuming we can agree on the language to represent that (maybe default_compression_level or something to avoid confusion over the name of the algorithm?).

**Comment by stgraber** [comment]
Should be images.default_compression
