### ISSUE TITLE
mistake in dir storage pool creation can easily corrupt the LXD global database 

### ISSUE THREAD

**Issue by waldekkot** [lxc/lxd#8111]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.10
 * The output of "lxc info" or if that fails:
config:
  cluster.https_address: 192.168.100.131:8443
  core.https_address: 192.168.100.131:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.100.131:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICFDCCAZmgAwIBAgIRAI5AM5uTzznAZfWivq1V2bkwCgYIKoZIzj0EAwMwOTEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEZMBcGA1UEAwwQcm9vdEBseGQt
    aG9zdC0wMTAeFw0yMDExMDIxNzIzNDBaFw0zMDEwMzExNzIzNDBaMDkxHDAaBgNV
    BAoTE2xpbnV4Y29udGFpbmVycy5vcmcxGTAXBgNVBAMMEHJvb3RAbHhkLWhvc3Qt
    MDEwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAS8jTKvsufhaZLPrl28dPoeBcmRiSp+
    jHPdZ/E+pjOSTkj19t/nuoqEWbMDHC4cQm3+6YoV40fTPPkWYPV0wXHfWBQwXv5s
    kTNVr9mxIPFvdpY1Z8fk5iR7An+TzBPBjL6jZTBjMA4GA1UdDwEB/wQEAwIFoDAT
    BgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMC4GA1UdEQQnMCWCC2x4
    ZC1ob3N0LTAxhwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMDA2kA
    MGYCMQCbqScv5GPQbYsmLNVoapN9q1iCSQ+Y+L7ULr9PHzK16NYMp3i6YKVrZeoJ
    FffK1c0CMQDZmWpswqIo4r9W0NvrJDMZ+daSWeHInGnMCNcQYcfStcBpDaSue+pP
    AyaDlagSrdg=
    -----END CERTIFICATE-----
  certificate_fingerprint: b164bab6343eb9f253b9585072ee10a1c4f35f48ff2a4e1c21821e4d27bf4234
  driver: lxc
  driver_version: 4.0.5
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.8.0-26-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.10"
  project: default
  server: lxd
  server_clustered: true
  server_name: lxd-host-01
  server_pid: 1627
  server_version: "4.7"
  storage: zfs
  storage_version: 0.8.4-1ubuntu11

# Issue description

I have been playing with "lxc create storage" and it seems it is (way too) easy to make a stupid mistake, which ultimately leads to LXD global database corruption, which affects all nodes in the LXD cluster. There should be some kind of protection against this stupid mistake, esp. that after making this mistake and restarting all nodes in the LXD cluster, LXD will be completely inaccessible and troubleshooting methods like "lxd sql global .dump" or "lxd sql global [query]" no longer work...

The stupid mistake is to simply forget to create the source directory for the "dir" storage pool (even on a single lxd node in the cluster) BEFORE performing the "lxc create storage ... --target ..." command. The missing directory on the LXD node is ultimately detected by "lxc storage create X dir" command, but even after creating the missing directory on the node, the storage pool creation fails, yet leaving the LXD global database in a state, which prevents LXD to restart. And the ERRORED storage pool cannot be deleted using "lxd storage delete" either. Deleting using "lxc sql global [query]" does work (as long as the LXD cluster is not restarted, otherwise sqlite3 must be used to correct the problem).

# Steps to reproduce

 1. create LXD cluster (say: 3 nodes: lxd-host-01, lxd-host-02, lxd-host-03, with IPs: 192.168.100.131, .132 and .133 resp.)
 2. forget to do "mkdir /home/waldek/myshared" on any - EVEN ONE - of the nodes (say, I will forget to do it on: lxd-host-03)
 3. doing: lxc storage create ms dir source=/home/waldek/myshared --target lxd-host-01
     gives: "Storage pool ms pending on member lxd-host-01"
 4. doing: lxc storage create ms dir source=/home/waldek/myshared --target lxd-host-02
     gives: "Storage pool ms pending on member lxd-host-02"
 5. doing: lxc storage create ms dir source=/home/waldek/myshared --target lxd-host-03
     gives: "Storage pool ms pending on member lxd-host-03"
 6. doing: lxc storage create ms dir
     gives: "Error: failed to notify peer 192.168.100.133:8443: Source path '/var/lib/snapd/hostfs/home/waldek/myshared' doesn't exist"
 7. doing: mkdir /home/waldek/myshared on lxd-host-03 and repeating step 6
     gives: "Error: Pool not defined on nodes: lxd-host-01, lxd-host-02, lxd-host-03"
 8. doing: lxc storage list, gives:
+-------+-------------+--------+---------+---------+
| NAME  | DESCRIPTION | DRIVER |  STATE  | USED BY |
+-------+-------------+--------+---------+---------+
| local |             | zfs    | CREATED | 11      |
+-------+-------------+--------+---------+---------+
| ms    |             | dir    | ERRORED | 0       |
+-------+-------------+--------+---------+---------+
 9. doing: lxc storage delete ms
    gives: "Error: Error loading pool "ms": No such object"
10. at this stage doing: lxd sql global .dump | grep storage_pool to get the id of the problematic storage pool still works, so doing: lxd sql global "DELETE FROM storage_pool WHERE id = 2" still works 
11. but, stopping LXD on any node in the cluster (or even worse stopping all the nodes in the cluster) and trying to restart them fails
12. doing: sudo lxd --debug --group lxd, reveals:
INFO[11-03|01:02:25] LXD 4.7 is starting in normal mode       path=/var/snap/lxd/common/lxd
INFO[11-03|01:02:25] Kernel uid/gid map:
INFO[11-03|01:02:25]  - u 0 0 4294967295
INFO[11-03|01:02:25]  - g 0 0 4294967295
INFO[11-03|01:02:25] Configured LXD uid/gid map:
INFO[11-03|01:02:25]  - u 0 1000000 1000000000
INFO[11-03|01:02:25]  - g 0 1000000 1000000000
INFO[11-03|01:02:25] Kernel features:
INFO[11-03|01:02:25]  - closing multiple file descriptors efficiently: no
INFO[11-03|01:02:25]  - netnsid-based network retrieval: yes
INFO[11-03|01:02:25]  - pidfds: yes
INFO[11-03|01:02:25]  - uevent injection: yes
INFO[11-03|01:02:25]  - seccomp listener: yes
INFO[11-03|01:02:25]  - seccomp listener continue syscalls: yes
INFO[11-03|01:02:25]  - seccomp listener add file descriptors: no
INFO[11-03|01:02:25]  - attach to namespaces via pidfds: yes
INFO[11-03|01:02:25]  - safe native terminal allocation : yes
INFO[11-03|01:02:25]  - unprivileged file capabilities: yes
INFO[11-03|01:02:25]  - cgroup layout: hybrid
WARN[11-03|01:02:25]  - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored
INFO[11-03|01:02:25]  - shiftfs support: yes
INFO[11-03|01:02:25] Initializing local database
DBUG[11-03|01:02:25] Initializing database gateway
DBUG[11-03|01:02:25] Start database node                      id=3 address=192.168.100.133:8443 role=voter
INFO[11-03|01:02:26] Starting cluster handler:
INFO[11-03|01:02:26] Starting /dev/lxd handler:
INFO[11-03|01:02:26]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[11-03|01:02:26] REST API daemon:
INFO[11-03|01:02:26]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[11-03|01:02:26]  - binding TCP socket                    socket=192.168.100.133:8443
INFO[11-03|01:02:26] Initializing global database
DBUG[11-03|01:02:26] Dqlite: attempt 0: server 192.168.100.131:8443: connect to reported leader 192.168.100.132:8443
DBUG[11-03|01:02:26] Dqlite: attempt 0: server 192.168.100.131:8443: connected
INFO[11-03|01:02:26] Firewall loaded driver "nftables"
DBUG[11-03|01:02:26] Notify node 192.168.100.131:8443 of state changes
DBUG[11-03|01:02:26] Notify node 192.168.100.132:8443 of state changes
DBUG[11-03|01:02:26] Connecting to a remote LXD over HTTPs
DBUG[11-03|01:02:26] Connecting to a remote LXD over HTTPs
INFO[11-03|01:02:26] Initializing storage pools
DBUG[11-03|01:02:26] Initializing and checking storage pool "local"
DBUG[11-03|01:02:26] Mount started                            driver=zfs pool=local
DBUG[11-03|01:02:26] Mount finished                           driver=zfs pool=local
DBUG[11-03|01:02:26] Initializing and checking storage pool "ms"
EROR[11-03|01:02:26] Failed to start the daemon: Failed initializing storage pool "ms": No such object
INFO[11-03|01:02:26] Starting shutdown sequence
INFO[11-03|01:02:26] Closing the database
INFO[11-03|01:02:26] Stop database gateway
INFO[11-03|01:02:26] Stopping REST API handler:
INFO[11-03|01:02:26]  - closing socket                        socket=192.168.100.133:8443
INFO[11-03|01:02:26]  - closing socket                        socket=/var/snap/lxd/common/lxd/unix.socket
INFO[11-03|01:02:26] Stopping /dev/lxd handler:
INFO[11-03|01:02:26]  - closing socket                        socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[11-03|01:02:26] Unmounting temporary filesystems
INFO[11-03|01:02:26] Done unmounting temporary filesystems
Error: Failed initializing storage pool "ms": No such object

13. of course, doing:
    cd /var/snap/lxd/common/lxd/database/
    touch patch.global.sql
    echo "DELETE FROM storage_pools WHERE id=9" > patch.global.sql
    
    will work. However, in case that none of the LXD nodes in the cluster works anymore, it requires resorting to "lower level" sqllite CLI to get the errored storage pool id (like: sqlite3 /var/snap/lxd/common/lxd/database/global/db.bin
and then: select * from storage_pools;). Maybe there could be some way to let LXD bypass the errored storage pool, so at least lxd sql would work ?

14. also, this method requires manual cleaning of directories (on all cluster nodes !), otherwise trying to create a new pool named with the same name as the errored one, makes "lxc storage create" fail again:
Error: Storage pool directory "/var/snap/lxd/common/lxd/storage-pools/ms" already exists
and:
Error: Source path '/var/lib/snapd/hostfs/home/waldek/myshared' isn't empty

15. BTW: manually removing/emptying the directories in step 14 and doing "lxc storage create ms dir" again, causes the same  "storage pool already exists" problem and requires repeating the whole procedure again

I know it is a stupid mistake to forget to create the source directory for the dir storage, but it could happen and it should not be possible to so easily break LXD just using the standard lxc CLI... Esp. LXD newbies might have a hard time to troubleshoot the issue...

Cheers,
Waldemar :-)

**Comment by stgraber** [comment]
@tomponline assigning to you, let's try to fix this soon.
I think the cleanest way to fix this would be to track the state on a per-node basis by adding a state column to both:
 - storage_pools_nodes
 - networks_nodes

Then when a node is notified to create the pool or network, it would attempt to do it, if it fails, it returns an error.
If it succeeds, it updates its state in the database from pending to ready.

Then whatever node received the initial create request will ensure that all nodes are reporting the ready state and only then flip the pool or network to ready in the main table.

When in that partially ready state, the user can always delete the storage pool or network which will cause all nodes that have it marked as ready to have it deleted from them.

Does that make sense?

**Comment by waldekkot** [comment]
BTW: the same (original) issue also happens with ZFS storage pools, i.e. not just "dir" ones

**Comment by tomponline** [comment]
@stgraber making a start on this now.

**Comment by tomponline** [comment]
@stgraber I started working on the network side of this task first as I've recently worked on the clustering for networks and it is more familiar to me.

I've added the `state` column to the `networks_nodes` table and chased it through the code base so its correctly set in all the various scenarios.

I've then updated the network drivers to allow being started when the network itself is still pending (as the network is started on each node as part of the create process) and subsequently mark each node as "created" once it has been created and started cleanly.

Once all nodes are successfully marked as "created", the network itself is marked as "created".

So now the process of creating a new network in a cluster is as follows:

- A pending network DB record (and associated pending network node record) is created for each cluster member (either manually or automatically if network driver doesn't support per-member settings).
- The network is then setup and started on the local node where the command is initiated.
- If local member setup & start is successful then the local member node record is marked as "created".
- Then each other member is notified and asked to create and start the network, each one marks its own network node record as "created" if it succeeds and responds to the initiator member.
- The initiator member waits for all other members to succeed, and if this occurs then it marks the network record itself as "created".
- If one of the other members fail, then the process ends and the network and any failed members are left in "pending" state.

I've got some questions/points:

1. Should I restore the existing behaviour of marking the network state as "errored" if one or more of the members fail to create successfully? This should then prevent any further modification of the network leaving the only next step being to delete the network and try again?
2. Or should I leave it in pending state, and then allow subsequent `lxc network create <name>` requests, but update it to only send notification create requests to nodes that are marked as "pending" and not "created"?
3. Currently it is possible to modify a pending network using `lxc network set`, should this be prevented (as this would seem to allow network config to change whilst nodes are being joined)?
4. However depending on the response to Q2, it would seem that modifying network config (at either the global or node level) would be required in order to correct any config issues that lead to one or more of the members not being able to create & start.
5. In which case config updates would need to be stored in the DB for all relevant nodes, but only applied to "created" nodes and not "pending" nodes (until the next `lxc network create <name>` at which point the current config would then be used against each pending node).

I suppose in a nutshell I'm asking whether a `lxc network create <name>` request should be a one-shot type scenario, where it either succeeds 100% or fails fully or partially, and in the latter scenario should the only course of action be to delete it and try again from the start?

In that case, do we really need the new columns, and wouldn't it be just the same to fix the storage pool issue directly which is that `cluster.GetNonPendingStoragePoolNames()`is returning storage pools with a state of `errored` which then fail to load blocking LXD start up, and allow storage pools in state `errored` to be deleted (like we do for networks).

The difference with networks is that `networkStartup()` skips over networks that fail to start so doesn't block LXD start, this means that `s.Cluster.GetNonPendingNetworks()` returning networks in an `errored` state isn't a problem. And that errored networks can currently be deleted.

Sorry for the rambling post, just been trying to get this straight in my head.

**Comment by stgraber** [comment]
I think we want 2).

Indeed, I'd expect the user to create the network on each node, making them go to pending.
Then do the global create which will then fail on one or more node. Those that succeeded should go to ready while those that failed should remain in pending state. The global network entry should only go into ready when all nodes are ready.

When in a situation where some of the nodes are ready and some others aren't, those which are still pending should allow for node specific config changes, letting you fix something like a bad `bridge.external_interfaces` for example. But those nodes which are ready already should not allow config changes nor should the global entry allow config changes.

Those that match your plan?

**Comment by tomponline** [comment]
@stgraber thanks, yes that makes sense. And if there is a scenario where the global config is causing problems with one or more nodes (I can't think of an actual real-world example for that at the moment though) then one can just delete the network entirely and all 'created' nodes will be cleaned up fully and pending nodes will just have their records removed.

**Comment by stgraber** [comment]
Yep!
