### ISSUE TITLE
Requested image's type 'virtual-machine' doesn't match instance type 'container'

### ISSUE THREAD

**Issue by mullumaus** [lxc/lxd#8117]
# Required information

 * Distribution: ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICADCCAYegAwIBAgIRAJY/Om1FMKn+PVgq2twn41YwCgYIKoZIzj0EAwMwMzEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBub2Rl
    MzAeFw0yMDExMDMwODA1MTRaFw0zMDExMDEwODA1MTRaMDMxHDAaBgNVBAoTE2xp
    bnV4Y29udGFpbmVycy5vcmcxEzARBgNVBAMMCnJvb3RAbm9kZTMwdjAQBgcqhkjO
    PQIBBgUrgQQAIgNiAAQ33SDFRxU9XrrlUZBZy56bWBnebUjLuWSqJNKaYiBdQqYJ
    NSlf623/7tRFaJJhW9W/mdFL5bCuvYxIdv2Uqwm+gYf/dce6OGXzfFgiIEszYVRk
    W6CZYUwt1RfaO6i5+6+jXzBdMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMCgGA1UdEQQhMB+CBW5vZGUzhwR/AAABhxAA
    AAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMDA2cAMGQCMAp9Ev+JY7hwKOB0eYE8
    Z8PW4TrjRnpdceq8Ov2vWXgQzygP0pF231g2CHgoPQ5huwIwfucjcC7RomcN3150
    OsRNOpE7mkTGmishf+6mbkJMyiGGdBkblTRGaC0kULXuKINc
    -----END CERTIFICATE-----
  certificate_fingerprint: b4d341664a3cf634d0d2a183fe72a45897e100105cd5bcc4c241f7eec92f1701
  driver: lxc
  driver_version: 4.0.5
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-52-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: node3
  server_pid: 1621
  server_version: "4.7"
  storage: dir
  storage_version: "1"
ubuntu@node3:~$ sudo lxc info |grep kernel
- kernel_limits
- kernel_features
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
  kernel_version: 5.4.0-52-generic
ubuntu@node3:~$ sudo lxc info |grep version
api_version: "1.0"
  driver_version: 4.0.5
  kernel_version: 5.4.0-52-generic
  os_version: "20.04"
  server_version: "4.7"
  storage_version: "1"

   * Kernel version: 5.4.0-52-generic
   * LXC version: 4.7
   * LXD version: 4.7
   * Storage backend in use:

# Issue description
Deploying ceph-base bundle on a virutal MaaS running on KVMs. 'juju status' shows error :Requested image's type 'virtual-machine' doesn't match instance type 'container'

Node summary:
Five KVMs running on baremetal node-flyer in Ruxton lab:
1 KVMs to install MaaS and juju client
1 KVM for juju controller (2 CPUs, 8G RAM, 1 NIC, 1 disk)
3 KVMs to deploy ceph-base/openstack-base (each node 2 CPUs, 8G RAM, 2 NICs, 3 disks)

buntu@ruxton-maas:~$ juju status
Model      Controller       Cloud/Region    Version  SLA          Timestamp
openstack  maas-controller  mymaas/default  2.8.6    unsupported  02:05:01-05:00

App       Version  Status   Scale  Charm     Store       Rev  OS      Notes
ceph-mon           waiting    0/3  ceph-mon  jujucharms   49  ubuntu  
ceph-osd  15.2.3   waiting      3  ceph-osd  jujucharms  304  ubuntu  

Unit         Workload  Agent       Machine  Public address  Ports  Message
ceph-mon/0   waiting   allocating  0/lxd/0                         waiting for machine
ceph-mon/1   waiting   allocating  1/lxd/0                         waiting for machine
ceph-mon/2   waiting   allocating  2/lxd/0                         waiting for machine
ceph-osd/0*  waiting   idle        0        10.17.17.212           Incomplete relation: monitor
ceph-osd/1   waiting   idle        1        10.17.17.213           Incomplete relation: monitor
ceph-osd/2   waiting   idle        2        10.17.17.214           Incomplete relation: monitor

Machine  State    DNS           Inst id  Series  AZ       Message
0        started  10.17.17.212  node2    focal   default  Deployed
0/lxd/0  down                   pending  focal            Requested image's type 'virtual-machine' doesn't match instance type 'container'
1        started  10.17.17.213  node3    focal   default  Deployed
1/lxd/0  down                   pending  focal            Requested image's type 'virtual-machine' doesn't match instance type 'container'
2        started  10.17.17.214  node4    focal   default  Deployed
2/lxd/0  down                   pending  focal            Requested image's type 'virtual-machine' doesn't match instance type 'container'

==================bundle file
ubuntu@ruxton-maas:~$ cat ceph-base-bundle.yaml 
machines:
  '0':
    series: focal
  '1':
    series: focal
  '2':
    series: focal
relations:
- - ceph-osd:mon
  - ceph-mon:osd
series: focal
services:
  ceph-mon:
    annotations:
      gui-x: '750'
      gui-y: '500'
    charm: cs:ceph-mon-49
    num_units: 3
    options:
      expected-osd-count: 3
      source: distro
    to:
    - lxd:0
    - lxd:1
    - lxd:2
  ceph-osd:
    annotations:
      gui-x: '1000'
      gui-y: '500'
    charm: cs:ceph-osd-304
    num_units: 3
    options:
      osd-devices: /dev/vdb
      source: distro
    to:
    - '0'
    - '1'
    - '2'

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

https://pastebin.canonical.com/p/wyHqmWG5H8/

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Can you do:
 - snap set lxd daemon.debug=true
 - systemctl reload snap.lxd.daemon

Then repeat what you were doing and after you hit the error, send us `/var/snap/lxd/common/lxd/logs/lxd.log`?
This should get us the full REST call done by Juju so we can see exactly what was requested.

**Comment by mullumaus** [comment]
thanks, I have set the config for lxd. The issue happens occasionally, I will upload the log when I see it again.

**Comment by stgraber** [comment]
@mullumaus any luck getting this to happen again?

**Comment by mullumaus** [comment]
No, I ran the test many times over these weeks but it didn't happpen again.

**Comment by stgraber** [comment]
Ok. There was bad image ordering logic in LXD which we fixed a little while back. This shouldn't have affected your LXD daemon because it was recent enough to get the fix in theory, however Juju uses the LXD library and so may have been using an older version internally.

Let's hope that this was the issue and call it good. If this shows up again, hopefully your system will still have the debugging enabled to catch it :)

**Comment by aydintd** [comment]
Hello, 

I think I am having a similar issue on a similar environment mentioned in the first comment, let me quickly summarize and give some information about my test environment : 

I am trying to deploy the openstack-base bundle in an environment with MAAS v2.9.1 (9153-g.66318f531) provisioned juju v2.8.7-focal-amd64, I have 3 compute VM nodes (Ubuntu 20.04) and 1 juju controller (Ubuntu 18.04) all being hosted on a 16GB RAM 8vCPU qemu-kvm virtualized Ubuntu 20.04 droplet.

So after issuing the juju deploy command, I observe the same error message in juju status output on 2 of my compute nodes when juju is trying to create some lxd containers as they are some parts of the openstack deployment like neutron-api or rabbitmq-server etc. containers so deployment fails.

The error message I get against the containers  :

"Requested image's type 'virtual-machine' doesn't match instance type 'container'"

I enabled the lxd debug logs on one of my compute hosts which is having the issue as you advised so here's the repeated error log : https://paste.ubuntu.com/p/dq4Jh3Dmhw/

Please let me know in case of you want me to upload the whole lxd.log file or a sosreport from one of the failed nodes many thanks!

**Comment by stgraber** [comment]
@aydintd I believe this is a Juju issue actually.

As your log shows, Juju directly interacts with LXD by using an image fingerprint, it doesn't request LXD do the simplestreams image lookup, this is done by Juju itself.

So I suspect it's broken/missing logic in Juju itself that should filter out VM images when looking up a suitable Ubuntu image from simplestreams.
