### ISSUE TITLE
Loop-backed ZFS storage pool creation fails with error about minimum size (64M)

### ISSUE THREAD

**Issue by waldekkot** [lxc/lxd#8119]
# Issue description

Hi,
This looks like a small bug, but I am not 100% sure and might have overlooked something. 

Using LXD 4.7 on Ubuntu 20.10, I am trying to create a new loop-based ZFS storage pool, but I am getting error about "the minimum size (64M)" of ZFS pool, which I guess should not happen...Seems like the default minimum for the ZFS pool size in LXD is set too low. Have not verified it, but could also be LXD cluster specific...

# Steps to reproduce

1. created LXD cluster (say: 3 nodes: lxd-host-01, lxd-host-02, lxd-host-03, with IPs: 192.168.100.131, .132 and .133 resp.)
2. the storage pool from lxd init on /dev/sdb works fine: 

> lxc storage list
> +-------+-------------+--------+---------+---------+
> | NAME  | DESCRIPTION | DRIVER |  STATE  | USED BY |
> +-------+-------------+--------+---------+---------+
> | local |             | zfs    | CREATED | 15      |
> +-------+-------------+--------+---------+---------+

3. 
> lxc storage create myzfspool zfs --target lxd-host-01
> Storage pool myzfspool pending on member lxd-host-01

4. 
> lxc storage create myzfspool zfs --target lxd-host-02
> Storage pool myzfspool pending on member lxd-host-02

5. 
> lxc storage create myzfspool zfs --target lxd-host-03
> Storage pool myzfspool pending on member lxd-host-03
 

6.
> lxc storage create myzfspool zfs
> Error: Failed to run: zpool create -f -m none -O compression=on myzfspool /var/snap/lxd/common/lxd/disks/myzfspool.img: 
> cannot create 'myzfspool': one or more devices is less than the minimum size (64M)

However, manually creating the loop-backed ZFS pool first and sourcing it to LXD, works fine:
1. same cluster as above
2. doing the following **on each of the 3 nodes**:
> sudo truncate -s 2G /tmp/myloopfile.img
> 
> sudo zpool create myzfslooppool /tmp/myloopfile.img
> 
> zpool list
> NAME            SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
> local           254G  6.84G   247G        -         -     0%     2%  1.00x    ONLINE  -
> myzfslooppool  1.88G   117K  1.87G        -         -     0%     0%  1.00x    ONLINE  -
> 
3. 
> lxc storage create myzfslooppool zfs source=myzfslooppool  --target lxd-host-01
> Storage pool myzfslooppool pending on member lxd-host-01
> 
> lxc storage create myzfslooppool zfs source=myzfslooppool  --target lxd-host-02
> Storage pool myzfslooppool pending on member lxd-host-02
> 
> lxc storage create myzfslooppool zfs source=myzfslooppool  --target lxd-host-03
> Storage pool myzfslooppool pending on member lxd-host-03
> 
4. 
> lxc storage create myzfslooppool zfs
> Storage pool myzfslooppool created
> 
5. 

> lxc storage ls
> +---------------+-------------+--------+---------+---------+
> |     NAME      | DESCRIPTION | DRIVER |  STATE  | USED BY |
> +---------------+-------------+--------+---------+---------+
> | local         |             | zfs    | CREATED | 15      |
> +---------------+-------------+--------+---------+---------+
> | myzfslooppool |             | zfs    | CREATED | 0       |
> +---------------+-------------+--------+---------+---------+
> | myzfspool     |             | zfs    | PENDING | 0       |
> +---------------+-------------+--------+---------+---------+
> 

# Required information
$ lxc info
config:
  cluster.https_address: 192.168.100.131:8443
  core.https_address: 192.168.100.131:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.100.131:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICFDCCAZmgAwIBAgIRAI5AM5uTzznAZfWivq1V2bkwCgYIKoZIzj0EAwMwOTEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEZMBcGA1UEAwwQcm9vdEBseGQt
    aG9zdC0wMTAeFw0yMDExMDIxNzIzNDBaFw0zMDEwMzExNzIzNDBaMDkxHDAaBgNV
    BAoTE2xpbnV4Y29udGFpbmVycy5vcmcxGTAXBgNVBAMMEHJvb3RAbHhkLWhvc3Qt
    MDEwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAS8jTKvsufhaZLPrl28dPoeBcmRiSp+
    jHPdZ/E+pjOSTkj19t/nuoqEWbMDHC4cQm3+6YoV40fTPPkWYPV0wXHfWBQwXv5s
    kTNVr9mxIPFvdpY1Z8fk5iR7An+TzBPBjL6jZTBjMA4GA1UdDwEB/wQEAwIFoDAT
    BgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMC4GA1UdEQQnMCWCC2x4
    ZC1ob3N0LTAxhwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMDA2kA
    MGYCMQCbqScv5GPQbYsmLNVoapN9q1iCSQ+Y+L7ULr9PHzK16NYMp3i6YKVrZeoJ
    FffK1c0CMQDZmWpswqIo4r9W0NvrJDMZ+daSWeHInGnMCNcQYcfStcBpDaSue+pP
    AyaDlagSrdg=
    -----END CERTIFICATE-----
  certificate_fingerprint: b164bab6343eb9f253b9585072ee10a1c4f35f48ff2a4e1c21821e4d27bf4234
  driver: lxc
  driver_version: 4.0.5
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.8.0-26-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.10"
  project: default
  server: lxd
  server_clustered: true
  server_name: lxd-host-01
  server_pid: 138963
  server_version: "4.7"
  storage: zfs
  storage_version: 0.8.4-1ubuntu11

**Comment by stgraber** [comment]
This suggests that one of your systems may have been low on disk space. Resulting in a default size lower than 64MB.

**Comment by waldekkot** [comment]
That was my initial thinking too, but checked and df shows a ~5 GB available. Also, in the scenario above I was able to create the temp 2GB file for ZFS pool with truncate without any problems. Just to be 100% on the safe side, I also checked if this works: dd if=/dev/urandom of=test.bin bs=500MB count=1 **on each node** and seems to be fine...

> 0+1 records in
> 0+1 records out
> 33554431 bytes (34 MB, 32 MiB) copied, 0.283378 s, 118 MB/s
> 

waldek@lxd-host-03:~$ ls -l
total 32780
drwxrwxr-x 2 waldek waldek     4096 Nov  4 20:55 my2ndshare
drwxrwxr-x 2 waldek waldek     4096 Nov  5 12:38 myshare
drwxr-xr-x 3 waldek waldek     4096 Oct 31 16:40 snap
-rw-rw-r-- 1 waldek waldek 33554431 Nov  5 13:54 test.bin

**Comment by waldekkot** [comment]
That was my initial thinking too, but checked and df shows ~5GB avail. Also, in the scenario above, I was able to create the temp file of 2 GB with truncate. Also, no problem with dd-ing a large file on every node as below (my LXD nodes are actually VMs on a laptop, so double checked if the host and guests have free disk space too, but it all seems to be fine...):

> df -h
> Filesystem      Size  Used Avail Use% Mounted on
> tmpfs           391M  1.6M  389M   1% /run
> /dev/sda2        16G   11G  4.0G  74% /
> tmpfs           2.0G     0  2.0G   0% /dev/shm
> tmpfs           5.0M     0  5.0M   0% /run/lock
> tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
> tmpfs           391M  4.0K  391M   1% /run/user/1000
> myzfslooppool   1.8G  128K  1.8G   1% /myzfslooppool
> waldek@lxd-host-01:~$ dd if=/dev/urandom of=test2.bin bs=1000000 count=1000
> 1000+0 records in
> 1000+0 records out
> 1000000000 bytes (1.0 GB, 954 MiB) copied, 7.09075 s, 141 MB/s
> waldek@lxd-host-01:~$ df -h
> Filesystem      Size  Used Avail Use% Mounted on
> tmpfs           391M  1.6M  389M   1% /run
> /dev/sda2        16G   12G  3.1G  80% /
> tmpfs           2.0G     0  2.0G   0% /dev/shm
> tmpfs           5.0M     0  5.0M   0% /run/lock
> tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
> tmpfs           391M  4.0K  391M   1% /run/user/1000
> myzfslooppool   1.8G  128K  1.8G   1% /myzfslooppool
>

**Comment by waldekkot** [comment]
I have just done another quick test. Created a fresh new cluster (like before, 3 nodes) and a 4th LXD node, which is **not** part of any cluster. The error about the minimum size appears only when doing "lxc storage create X zfs" on the LXD cluster. For the standalone node the pool creation works fine. 

Could the default be set differently for cluster and non-cluster nodes ?

**Comment by stgraber** [comment]
I'll take a look at this one. Normally the `size` property which is node-specific should be calculated in `storagePoolFillDefault` by looking at the free space in /var/snap/lxd/common/lxd/disks but this should have a 5GB lower size, in your case it suggests something is effectively passing 0 through.

**Comment by stgraber** [comment]
Can you try manually passing size=15GB or whatever size to each of the targeted creates?

**Comment by waldekkot** [comment]
Yes, passing the size attribute works fine for the cluster.
And confirming that the size of the img file in /var/snap/lxd/common/lxd/disks/myzfspool.img is indeed 0 if the size attribute is not passed.

**Comment by waldekkot** [comment]
I confirm the issue has been resolved in LXD 4.8. Thanks guys :-)
