### ISSUE TITLE
lxc list should return 'project' as one of the pre-defined columns

### ISSUE THREAD

**Issue by waldekkot** [lxc/lxd#8128]
# Issue description

There seems to be a small usability issue with lxc list... I started playing with LXD projects and just wanted to list all currently running instances in my LXD cluster and see to which project they have been assigned. I can see instances per project (using the lxc list's global flag: _--project_, but I need to specify the exact project name to get back the instances' info. I think something similar to `lxc list -c n "c.."` should exist but for getting the **project** name of the instance...

I know a kind of workaround would be to do something similar to the one below, but, well, it is too much typing ;-) and not consistent with handling of the other instance data with the -c option:

`lxc project list --format json | jq '.[].name' | xargs -I % sh -c 'echo %; lxc list --project %'
`

Cheers,
Waldemar

# Required information

LXD 4.7

**Comment by stgraber** [comment]
We already have an issue to add a way to list instances from all projects.

**Comment by waldekkot** [comment]
Thanks ! Issue #7559 - I should have checked that before. I have not been referring to just listing of instances from all projects, but in general that the `lxc list -c` should allow specifying "project" as a column (so, in a sense would be consistent with other options, esp. lxc list -c L), but hope #7559 solves this too :-)

**Comment by stgraber** [comment]
Well, `lxc list` only shows things from your current project, so right now such a column would be pointless.
Once we add an API to query across projects, then the column will make sense.
