### ISSUE TITLE
Add something like lxc.start.auto = 1

### ISSUE THREAD

**Issue by pcdummy** [lxc/lxd#814]
I'm not using Openstack but i have my management stuff which will be my openstack replacement inside a lxd container, which means i need lxd to autostart at least the management containers with lxd.

Also i want to start them in a particular order so i need something like `lxc.start.order` and `lxc.start.delay`.

I'm sure i'm not the only one needing something like that, others also asking for it [here](http://askubuntu.com/questions/618577/cannot-auto-start-lxc-containers-created-with-lxd)

**Comment by stgraber** [comment]
Ok, so I think there are a few things we want to do here:
 - Remove the power\_state column from the containers table
 - Introduce a new volatile.last\_state config key which is used as an equivalent to power\_state. On clean shutdown, set to whatever state the container is in. On next startup, bring things back up and clear the key.
 - Introduce a new boot.autostart key that can be set to 1 to always cause the container to start on LXD startup.
 - Introduce a new boot.autostart.delay key that can be set to a number of seconds to wait after the container has been started before attempting to start the next one.
 - Introduce a new boot.autostart.order key that can be set to an integer used to sort the containers to start in the right order.

For now that's pretty much equivalent to what we have in LXC. At some point later we may be able to introduce an alternative to the delay option which would instead use some kind of signal over the /dev/lxd socket.

**Comment by stgraber** [comment]
Changed above comment from volatile.last\_state to volatile.last\_state.power as we'll need a volatile.last\_state.idmap for #787

**Comment by stgraber** [comment]
@pcdummy any interest in working on this?

**Comment by stgraber** [comment]
I may take a stab at this one on my flight to Seattle.
