### ISSUE TITLE
lxc copy error can result in invalid container on dst due to security.protection.delete flag

### ISSUE THREAD

**Issue by diegomontoya** [lxc/lxd#8141]
Ubuntu 20.04, snap lxd 4.7

Server A and Server B are identical in terms of hardware, os and software. 

1) Containers storage are using DIRFS
2) Src container profile and dst profile have ```security.protection.delete``` set to true.
3) ServerB: ```lxc copy ServerAIp:c1 c1```
4) after a few seconds of copy over tcp, rsync fails for whatever reason
5) ServerB now attempts cleanup due to failed lxc copy. (partial success)
6) ServerB is able to remove all the partial copied container files from storage/containers folder (success)
7) ServerB is unable to delete the container registry in lxd db due to ```security.protection.delete``` true flag. (fail)
8) ServerB now has an empty shell c1 container that is unusable. There are no files for c1 in any storage as they were correctly cleaned/deleted in step 6. 

I am not including logs here since the steps are very straightforward. 

```security.protection.delete``` flag should be ignored if lxc is performing delete operation due to a failed migration cleanup.

**Comment by stgraber** [comment]
I remember observing that before and it unfortunately not being trivial to resolve but I'll take another look :)
