### ISSUE TITLE
API memory doesn't match "free"

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#8143]
Im not sure if this is an LXD issue or me miss understanding the API but;

LXD Version: 4.7 snap

if you run 
```
root@root lxc query /1.0/instances/c1/state
{
        ....
	"memory": {
		"swap_usage": 0,
		"swap_usage_peak": 0,
		"usage": 188903424,
		"usage_peak": 433291264
	},
       ...
}
```

or 

```
lxc info c1

...
  Memory usage:
    Memory (current): 188.88MB
    Memory (peak): 433.29MB
...

```

then you do

```
lxc exec c1 bash
free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi       130Mi        15Gi          0B        50Mi        15Gi
```

You can see the values dont match

**Comment by stgraber** [comment]
LXD reports the raw cgroup memory usage (`memory.usage_in_bytes` on V1 or `memory.current` on V2).

`free` reports used memory as being used-buffer. In your output above, if you add up the 50MB of buffers with your 130MB of used space, you do get to the cgroup memory consumption of 180MB with the only part left in the difference being MB vs MiB.

LXCFS has a bunch of logic to generate a full `meminfo` which is what you get inside the container when using `free`, LXD instead goes the very fast route and just pulls the cgroup memory consumption reported by the kernel.
