### ISSUE TITLE
Running LXC client on OSX

### ISSUE THREAD

**Issue by rrva** [lxc/lxd#815]
Running (not even building LXC client) on OSX is not possible, multiple problems. It would be useful to manipulate a remote LXD instance via some lxc commandline tool on OSX.

I tried building in the lxc folder and got

```
 go build
# github.com/gosexy/gettext
../../../gosexy/gettext/gettext.go:28:10: fatal error: 'libintl.h' file not found
#include <libintl.h>
         ^
1 error generated.
# github.com/lxc/lxd/shared
../shared/container.go:23: undefined: lxc.State
dejsi:lxc rrj$ pwd
/Users/rrj/go/src/github.com/lxc/lxd/lxc
```

**Comment by stgraber** [comment]
hmm, you seem to be building an older version of LXD. Current LXD git doesn't use gosexy's gettext anymore, specifically for this reason.

**Comment by stgraber** [comment]
oh, nevermind actually, looks like somebody reintroduced it...

**Comment by stgraber** [comment]
I'll let @pcdummy submit his fix for inclusion so I can pull it myself and don't have to wait for another committer to do the review :)

**Comment by pcdummy** [comment]
This should be fixed now. Thanks for reporting @rrva and thanks for your help @stgraber.
