### ISSUE TITLE
LXD trying to set MAC to 00:00:00:00:00:00 when using SR-IOV

### ISSUE THREAD

**Issue by scubashan** [lxc/lxd#8162]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:# lxc info
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- resources_system
- usedby_consistency
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- storage_rsync_compression
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.1.239:8443
  - '[fdef:c3f5:dcab::b80]:8443'
  - '[fdef:c3f5:dcab:0:ba2a:72ff:fee1:c1d7]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
  certificate_fingerprint:
  driver: lxc
  driver_version: 4.0.5
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-54-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: b1-lxd
  server_pid: 2222
  server_version: 4.0.4
  storage: zfs
  storage_version: 0.8.3-1ubuntu12.4

# Issue description

Trying to add SR-IOV device to a container and it fails with : 

# lxc launch ubuntu: test
Creating test

The instance you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to an instance, use: lxc network attach

Starting test
# lxc config device add test eth0 nic nictype=sriov parent=eno1 hwaddr=00:00:00:00:00:01 mtu=2000
Error: Failed to start device "eth0": Failed to run: ip link set dev eno1 vf 0 mac 00:00:00:00:00:00: RTNETLINK answers: Invalid argument

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)

[  688.245349] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  688.749241] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  689.252941] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  689.756847] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  690.260765] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  690.764664] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  691.268406] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  691.772215] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  692.275800] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  692.779699] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  693.283089] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  693.786765] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  694.290492] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  694.794248] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  695.297603] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  695.801575] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  696.305926] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  696.809373] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  697.312694] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  697.816331] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[  698.318081] bnx2x 0000:01:01.0: msix capability found
[  698.318127] bnx2x 0000:01:01.0: enabling device (0000 -> 0002)
[  698.422914] bnx2x 0000:01:01.0: 32.000 Gb/s available PCIe bandwidth (5 GT/s x8 link)
[  698.429712] bnx2x 0000:01:01.0 eno1v0: renamed from eth0

 - [ ] Container log (`lxc info NAME --show-log`)

# lxc info test --show-log
Name: test
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/11/16 21:52 UTC
Status: Running
Type: container
Profiles: default
Pid: 5072
Ips:
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 62
  Disk usage:
    root: 19.50MB
  CPU usage:
    CPU usage (in seconds): 21
  Memory usage:
    Memory (current): 229.35MB
    Memory (peak): 365.58MB
  Network usage:
    lo:
      Bytes received: 7.30kB
      Bytes sent: 7.30kB
      Packets received: 100
      Packets sent: 100

Log:

lxc test 20201116215244.720 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.test"
lxc test 20201116215244.722 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.test"
lxc test 20201116215244.730 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1573 - No such file or directory - Failed to fchownat(17, memory.oom.group, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )

 - [ ] Container configuration (`lxc config show NAME --expanded`)

# lxc config show test --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20201111)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20201111"
  image.type: squashfs
  image.version: "20.04"
  volatile.base_image: 1503148c44359a349c17ce7cd4e0e36dae9ff3a44a7777cc1cee993491a73adf
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

Any ideas?

**Comment by scubashan** [comment]
Same result after upgrading from 4.0/stable/ubuntu-20.04 to 4.8/stable

**Comment by stgraber** [comment]
That's the normal way to clear any MAC restriction on the VF.

```
root@athos:~# ip link set dev eth0 vf 0 mac 00:00:00:00:00:00
root@athos:~# 
```

How do you clear the MAC restriction on your card so that all MACs can once again be used without hardware filtering?

**Comment by scubashan** [comment]
Unsure... 

# ip link set dev eno1 vf 0 mac 00:00:00:00:00:00
RTNETLINK answers: Invalid argument
# ip link set dev eno1 vf 0 mac 00:00:00:00:00:01
# 

Its the bnx2x driver.

**Comment by stgraber** [comment]
@tomponline

**Comment by tomponline** [comment]
@stgraber I suppose we could try and reset it and if it fails ignore the error, that way problematic devices like this one can still work.

As we only go onto set it to the static or volatile MAC after that anyway, its just that IIRC some devices required it be reset first before setting a new one.

**Comment by scubashan** [comment]
This is still failing in 4.0.11 on bnx2x , looks like it gets a bit further then fails?

# lxc network attach internet test eth1
Error: Failed to start device "eth1": Failed to bring up the interface: Failed to run: ip link set dev eno1v1 up: RTNETLINK answers: Cannot assign requested address

 dmesg |grep bnx |tail 
[ 6874.359565] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[ 6874.862640] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[ 6875.366094] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[ 6875.869865] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[ 6876.373813] [bnx2x_set_vf_mac:2704(eno1)]mac address invalid
[ 6876.878091] bnx2x 0000:01:01.1: msix capability found
[ 6876.878136] bnx2x 0000:01:01.1: enabling device (0000 -> 0002)
[ 6876.986130] bnx2x 0000:01:01.1: 32.000 Gb/s available PCIe bandwidth (5 GT/s x8 link)
[ 6876.994338] bnx2x 0000:01:01.1 eno1v1: renamed from eth0
[ 6877.038468] bnx2x: [bnx2x_validate_addr:12950(eno1v1)]Non-valid Ethernet address

# ip link set dev eno1 vf 1 mac 00:00:00:00:00:69
# lxc network attach internet test eth1
#


What can I provide to help?

**Comment by scubashan** [comment]
post-up echo 16 > /sys/class/net/eno1/device/sriov_numvfs
  post-up for vf in $(ip link show eno1 | awk '/vf / {printf $2" "}'); do ip link set eno1 vf $vf mac b8:2a:71:be:ef:${vf}; done

I added the above to the interfaces file to manually set the mac addresses on boot which is successful as a workaround. 
Let me know if theres anything I can do to help diagnose the issue.

**Comment by tomponline** [comment]
@scubashan In your original post your were trying to add a device with a MAC of `00:00:00:00:00:01` using `lxc config device add test eth0 nic nictype=sriov parent=eno1 hwaddr=00:00:00:00:00:01 mtu=2000`.

However in your latest manual example your using `b8:2a:71:be:ef:${vf}`. Please can you confirm that the equivalent static MAC is also causing the original issue reported with LXD?

Also, can you try adding a VF without a specific MAC address using:

```
lxc config device add test eth0 nic nictype=sriov parent=eno1
```

**Comment by scubashan** [comment]
@tomponline 
Oops! Apologies, its been a few weeks and I'd started using LXC to manage SRIOV networks.

Using: 
c# lxc config device add test eth0 nic nictype=sriov parent=eno1 hwaddr=00:00:00:00:00:01 mtu=2000
works fine. 

Using: 
c# lxc config device add test eth0 nic nictype=sriov parent=eno1 mtu=2000
Error: Failed to start device "eth0": Failed to bring up the interface: Failed to run: ip link set dev eno1v1 up: RTNETLINK answers: Cannot assign requested address

Ditto using:
c# lxc network create internet  parent=eno1 --type=sriov vlan=21 
c# lxc network attach internet test eth0 
Error: Failed to start device "eth0": Failed to bring up the interface: Failed to run: ip link set dev eno1v1 up: RTNETLINK answers: Cannot assign requested address
 
Let me know if anything else you need.

**Comment by tomponline** [comment]
Is it possible to get access to the server remotely?

**Comment by scubashan** [comment]
Not easily :/

**Comment by tomponline** [comment]
So checking I understand correctly? The original issue is now fixed `lxc config device add test eth0 nic nictype=sriov parent=eno1 hwaddr=00:00:00:00:00:01 mtu=2000` works whereas it didnt before?

But not specifying a MAC does not work?

**Comment by scubashan** [comment]
Correct. And all 3 methods work if I set the MACs on boot. Is that expected behaviour or should LXD create the MACs?

**Comment by tomponline** [comment]
It seems that each SRIOV chipset seem to have subtly different behaviour/characteristics. So LXD has to adapt to accommodate them. On the Mellanox and Intel chipsets we have access to if we do not set a MAC address, then when we bring the VF up it uses its own MAC address, but perhaps your chipset requires us to set a (random one) if not specified by user.

**Comment by tomponline** [comment]
when you first boot the machine before setting up any VF config, what is the output of `sudo ip link` showing the VF states?

**Comment by scubashan** [comment]
There is none, LXD is creating the VFs

**Comment by tomponline** [comment]
Ah, ok, what about after doing `echo 16 > /sys/class/net/eno1/device/sriov_numvfs`?

**Comment by stgraber** [comment]
@tomponline so we may need to do a bit of a dance, try to bring it up, if that fails and we don't have an hwaddr set by the user, then generate a random one and use that? That should allow for cards that generate their own to keep doing that and to handle cards which don't?

**Comment by scubashan** [comment]
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether b8:2a:72:e1:9a:d7 brd ff:ff:ff:ff:ff:ff
    vf 0     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 1     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 2     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 3     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 4     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 5     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 6     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 7     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 8     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 9     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 10     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 11     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 12     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 13     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 14     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 15     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto




6: eno1v0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
7: eno1v1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
8: eno1v2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
9: eno1v3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
10: eno1v4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
11: eno1v5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
12: eno1v6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
13: eno1v7: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
14: eno1v8: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
15: eno1v9: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
16: eno1v10: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
17: eno1v11: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
18: eno1v12: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
19: eno1v13: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
20: eno1v14: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
21: eno1v15: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff

**Comment by scubashan** [comment]
FYI - I thought I'd try bring one of those up 

# ip link set eno1v0 up 
RTNETLINK answers: Cannot assign requested address

**Comment by tomponline** [comment]
thanks @scubashan, so we can see your card is behaving differently than the others. Here's an example on my Intel card on a fresh boot (I'm using the PF here), but you can see that although the VFs have no MAC assigned, the interfaces associated to them do, and can be brought up without specifying a MAC, whereas yours do not.

```
ip l
10: enp1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 6c:b3:11:1c:09:52 brd ff:ff:ff:ff:ff:ff
    vf 0     link/ether ae:91:f5:91:c3:7c brd ff:ff:ff:ff:ff:ff, spoof checking off, link-state auto, trust off
    vf 1     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, spoof checking on, link-state auto, trust off
    vf 2     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, spoof checking on, link-state auto, trust off
    vf 3     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, spoof checking on, link-state auto, trust off
    vf 4     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, spoof checking on, link-state auto, trust off
    vf 5     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, spoof checking on, link-state auto, trust off
    vf 6     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, spoof checking on, link-state auto, trust off
4: enp1s0f0v1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ae:82:49:78:01:76 brd ff:ff:ff:ff:ff:ff
5: enp1s0f0v2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 66:2f:77:de:15:b7 brd ff:ff:ff:ff:ff:ff
6: enp1s0f0v3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 7a:f5:1c:ac:ae:02 brd ff:ff:ff:ff:ff:ff
7: enp1s0f0v4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 2a:01:da:84:db:5a brd ff:ff:ff:ff:ff:ff
8: enp1s0f0v5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 9e:7e:18:cb:15:47 brd ff:ff:ff:ff:ff:ff
9: enp1s0f0v6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ba:58:d7:4d:07:40 brd ff:ff:ff:ff:ff:ff
10: enp1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
```

@stgraber yes that would seem to be the way forward.

**Comment by stgraber** [comment]
I really wish the kernel would enforce a common behavior on this stuff...

**Comment by scubashan** [comment]
Great, let me know if you need anything else.

**Comment by tomponline** [comment]
@scubashan do you have to set a MAC to the VF on the PF or can you just set it on the VF interface itself and bring it up?

**Comment by scubashan** [comment]
c# ip link set eno1v0 address  00:00:00:00:00:69 
c# ip link set eno1v0 up 
c# 

Looks like you can set the VF directly.

**Comment by tomponline** [comment]
And what does `ip link` on the PF show for the VF setting after that (so I can get a full picture)?

**Comment by scubashan** [comment]
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether b8:2a:72:e1:9a:d7 brd ff:ff:ff:ff:ff:ff
    vf 0     link/ether 00:00:00:00:00:69 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 1     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 2     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto


6: eno1v0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:69 brd ff:ff:ff:ff:ff:ff
7: eno1v1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
8: eno1v2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff

**Comment by tomponline** [comment]
@scubashan ok thanks, this makes more sense. Thanks
