### ISSUE TITLE
Allow listing device keys in `lxc list`

### ISSUE THREAD

**Issue by visit1985** [lxc/lxd#8171]
# Issue description

Follow-up to: Support device keys as lxc list columns #6275

Could we maybe extend the custom columns format `[config:|devices:]key[:name][:maxWidth]` to allow listing the device keys?
For example: `lxc list <container> -c devices: --format=csv`

This would be nice for iterating in shell scripts.

**Comment by stgraber** [comment]
I don't understand what you want to do. The current syntax lets you add columns for any device config key you want.

**Comment by visit1985** [comment]
Given:
```
$ lxc config device show somecontainer
backup:
  path: /backup
  source: /srv/backup
  type: disk
data:
  path: /srv
  source: /srv/data
  type: disk
```
I would like to do:
```
$ lxc list somecontainer -c devices: --format=csv
backup
data
```

**Comment by stgraber** [comment]
Don't we have a 'lxc config device list' for that?

**Comment by visit1985** [comment]
Yes, you are right. :man_facepalming: Thanks!
