### ISSUE TITLE
If restoring state container from criu, with host_name, tring creating two network interfaces

### ISSUE THREAD

**Issue by ne-vlezay80** [lxc/lxd#8189]
# Required information

 * Distribution: Void Linux
 * Distribution version: 
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.7.10_1
   * LXC version: 4.0.4
   * LXD version: 4.8
   * Storage backend in use: 5.6.1

# Issue description
If a saving stateful from the container, and start, exist's the bug.

# Steps to reproduce

 1. lxc start container -stateful
 2. lxc start container

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

https://ibb.co/wcKcnsL

**Comment by stgraber** [comment]
I don't see how this bug is possible in the first place given that current LXD with CRIU does not let you have network interfaces.
