### ISSUE TITLE
Invalid storage volume content type name

### ISSUE THREAD

**Issue by jamielsharief** [lxc/lxd#8203]
Previously I could create a volume on a storage pool via the API by posting the following data to `/storage-pools/default/volumes`, however now I am getting the error `Invalid storage volume content type name` 

```
Array
(
    [name] => volume-58da
    [type] => custom
    [config] => Array
        (
            [size] => 5GB
        )

    [driver] => zfs
)
```

Note: the same error occurs if using the example from the REST docs

```
{
    "config": {},
    "name": "vol1",
    "type": "custom"
}
```

**Comment by stgraber** [comment]
@tomponline can you take a quick look? Feels like we're failing to default to fs content type when not specified?

**Comment by tomponline** [comment]
@stgraber yep will do

**Comment by tomponline** [comment]
@jamielsharief can you give me an example of the HTTP request you're sending, are you POSTing to that URL?

**Comment by tomponline** [comment]
@jamielsharief also what version of LXD please

**Comment by tomponline** [comment]
I think ive found the issue

**Comment by tomponline** [comment]
@jamielsharief by the way in the interim you can also complete the request by providing the `content_type` field set to "filesystem" (which will be the default if empty) of "block" for block volumes.

**Comment by jamielsharief** [comment]
Sorry for the delay

- LXD version 4.8

note. The manual says set to `custom` but I had tried `filesystem` earlier but it said I don't have permissions. I am trying to look into now, just LXD is giving EOF errors on everything. I will let you know shortly.

**Comment by tomponline** [comment]
volume type (custom) and content type are different concepts.

**Comment by tomponline** [comment]
@jamielsharief do you have a reproducer using `lxc query` command?

**Comment by jamielsharief** [comment]
The EOF error was caused because of change I made before i left earlier, ignore that comment.

I have added the `content_type` and it now works again, my PHPUnit tests from 2-3 months ago stopped working as well, so I presume this is something to do with a recent update?
