### ISSUE TITLE
Feature: Add the usage of SIGPWR to the init scripts on shutdown.

### ISSUE THREAD

**Issue by pcdummy** [lxc/lxd#821]
@stgraber implemented a feature to restore the power state of a container on reboot in issue #512.

I think we should add an **option to /etc/default/lxd** to **enable/disable this behavior** and if enabled use SIGPWR on `service lxd stop` or on a simple `poweroff`|`reboot`

**Comment by stgraber** [comment]
Not sure why you'd want to disable this behavior. My plan was to just always do it, as is the case for libvirt for example. The trick is to do it right though. For upstart it should be pretty simple, just change the kill signal, systemd is likely to be as simple, sysvinit will need a bit more scripting though.

**Comment by stgraber** [comment]
New default for upstart and systemd is SIGPWR and a 40s timeout (lxd itself has a 30s timeout).
