### ISSUE TITLE
No way to map between USB device and storage/network resource

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#8215]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.8.0-29-generic
   * LXC version: 4.0.5
   * LXD version: 4.8
   * Storage backend in use: LVM

# Issue description

MAAS 2.10 will model all PCIE and USB devices using LXD output. MAAS will also create associations between existing storage and network models with PCIE and USB models. MAAS can use the device_path of network and storage devices to map them to the pci_address of network and storage devices. For USB devices LXD does not give MAAS enough information to determine which network/storage device maps to which USB device.

Below is the storage and USB output for a USB disk. The only way I can determine the association is by name which won't work when the system has more than one of the same device.

```
{
          "id": "sda",
          "device": "8:0",
          "model": "U3 Cruzer Micro",
          "type": "usb",
          "read_only": false,
          "size": 4110227968,
          "removable": true,
          "numa_node": 0,
          "device_path": "pci-0000:00:14.0-usb-0:2:1.0-scsi-0:0:0:0",
          "block_size": 512,
          "firmware_version": "4.05",
          "rpm": 0,
          "serial": "000018626575A3E7",
          "device_id": "usb-SanDisk_U3_Cruzer_Micro_000018626575A3E7-0:0",
          "partitions": [
            {
              "id": "sda1",
              "device": "8:1",
              "read_only": false,
              "size": 2601910272,
              "partition": 1
            },
            {
              "id": "sda2",
              "device": "8:2",
              "read_only": false,
              "size": 4063232,
              "partition": 2
            },
            {
              "id": "sda3",
              "device": "8:3",
              "read_only": false,
              "size": 1507662336,
              "partition": 3
            }
          ]
        }
```

```
{
          "bus_address": 1,
          "device_address": 30,
          "interfaces": [
            {
              "class": "Mass Storage",
              "class_id": 8,
              "driver": "usb-storage",
              "driver_version": "5.8.0-29-generic",
              "number": 0,
              "subclass": "SCSI",
              "subclass_id": 6
            }
          ],
          "product": "U3 Cruzer Micro",
          "product_id": "5406",
          "speed": 480,
          "vendor": "SanDisk Corp.",
          "vendor_id": "0781"
        },
```

**Comment by stgraber** [comment]
Hmm and you had that information before through some other tool?

Because looking around at sysfs and the udev database, neither seem to record a link from a particular instance of a usb-storage or usb-net stack and its underlying port...

**Comment by stgraber** [comment]
I think I found a way to get the information we need, no idea if it's reliable though.

**Comment by ltrager** [comment]
Thanks for the fix! Verified I can now map USB storage and network devices to their USB entry. I think this should be good enough for now, I'm just starting to model all hardware for 2.10, we'll be doing more advanced config in the future :)
