### ISSUE TITLE
Importing backup using API

### ISSUE THREAD

**Issue by jamielsharief** [lxc/lxd#8219]
LXD 4.04
Ubuntu 20.04.01

I am trying to restore a backup using the API, I am not sure if I am understanding the manually correctly, but I am posting the backup file in RAW to `1.0/instances/c1`, however I get an error back

```
curl -X POST -k -H "Content-Type: application/octet-stream" --data-binary @tmp.gz --cert /var/www/config/certs/certificate --key /var/www/config/certs/privateKey https://192.168.1.160:8443/1.0/instances/c1
```
Which returns

 `{"error":"invalid character '\\x1f' looking for beginning of value","error_code":400,"type":"error"}`

The manual says this

![image](https://user-images.githubusercontent.com/20553479/101371110-ad6b0580-38aa-11eb-8473-f6bb63bdd7e6.png)

Any ideas what I am doing wrong?

**Comment by stgraber** [comment]
You need to push this to `/1.0/instances` not `/1.0/instances/NAME`, the endpoint you're pushing to right now is meant for renames/migration of an existing instance and is expecting JSON input.

The name is included in the backup usually but can be overriden with the `X-LXD-name` HTTP header.
