### ISSUE TITLE
Expose DNS to host

### ISSUE THREAD

**Issue by aguytech** [lxc/lxd#8230]
# Required information

 * Distribution:

> Manjaro Lysia

   * Kernel version:

> Linux 970a 5.9.11-3-MANJARO #1 SMP PREEMPT Sat Nov 28 09:08:57 UTC 2020 x86_64 GNU/Linux

   * LXC version:

> 4.8

   * LXD version:

> 4.8

   * Storage backend in use:
`btrfs`

# Issue description
with following documentation at [](https://linuxcontainers.org/lxd/docs/master/networks):
Unable to expose lxd DNS (dnsmasq) to host
`resolve call failed: DNSSEC validation failed: no-signature`

`resolvectl status`

> Link 18 (lxdbr0)
> Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
> DefaultRoute setting: no
> LLMNR setting: yes
> MulticastDNS setting: no
> DNSOverTLS setting: no
> DNSSEC setting: allow-downgrade
> DNSSEC supported: no
> Current DNS Server: 10.0.0.1
> DNS Servers: 10.0.0.1
> DNS Domain: ~lxd
> 

# Solution
May be precise in documentation to disable dnssec, (not only allow-downgrade), two ways:
- in global configuration '/etc/systemd/resolved.conf', modify to 

    > DNSSEC=no

  and restart service
  `systemctl restart systemd-resolved.service`

- just for lxd interface 'lxdbr0'
  `resolvectl --interface lxdbr0 dnssec set no && systemctl restart systemd-resolved.service`
  or
  `systemd-resolve --interface lxdbr0 --set-dnssec no && systemctl restart systemd-resolved.service`

# Question
I've tried to expose lxd DNS via the addon dnsmasq from networkmanager. Is there a way to expose dnsmasq configuration or is it "hard coded" in launching of dnsmaq daemon ?
Thank you ?

**Comment by stgraber** [comment]
I believe network manager's dnsmasq instance reads additional config files from `/etc/NetworkManager/dnsmasq.d/` at least it looks like it would here.

**Comment by aguytech** [comment]
May be a important thing to add to documentation to have a SIMPLE persistent dns resolving for host:
**No need to use interactive resolvectl to that**

Just create the  folder
`/etc/systemd/resolved.conf.d/`
and the file
`/etc/systemd/resolved.conf.d/lxd.conf`
with content
```
[Resolve]                                                                                                                                                                                                                   
DNS=10.0.0.1                                                                                                                                                                                                                
Domains=lxd                                                                                                                                                                                                                 
DNSSEC=no                                                                                                                                                                                                                   
```
`systemctl restart systemd.resolved.service`
it's done !

`resolvectl status`
show nothing, but the configuration file is well parsed and
`resolvectl query my_ct.lxd`
works fine !

**Tested with restarting systemd-resolved.service, reboot OS and on Unbuntu & manjaro ;o)**

**Comment by stgraber** [comment]
This approach doesn't tie it to a particular interface so if you somehow have that subnet on multiple interfaces, resolved will get confused, same if the interface goes away, you'd now be leaking DNS queries to the internet.

**Comment by aguytech** [comment]
> This approach doesn't tie it to a particular interface so if you somehow have that subnet on multiple interfaces, resolved will get confused, same if the interface goes away, you'd now be leaking DNS queries to the internet.

Good point, I'm waiting you're implement this responsive dns solution in lxc ;o)

Actually I don't see a natural solution to dynamically bind a container to a proxy ?
Either I use a dynamical command that I need to reuse at each Host restarting ( so it doesn't follow the life cycle of network between...)
So I put configuration in a file, that I need to modify when network changes...

I'm going to try to use a dhcp reservation in lxc and then use IP addresses in the proxy, may be more efficient ?

The life is no so easy ;o)

**Comment by stgraber** [comment]
Yeah, using `ipv4.address` may be the easiest way there :)

We do have a vague plan to add a built-in DNS server to LXD that would expose networks with public DNS zones, it wouldn't let you have two networks that are exported with the same dns.domain (obviously) but for anything non-overlapping that should work and we'd also allow for zone transfers so you can front it with a proper dns server too.

**Comment by aguytech** [comment]
It's look good. Good works ;o)
