### ISSUE TITLE
Copy incremental with storage volume

### ISSUE THREAD

**Issue by olivier-lz** [lxc/lxd#8232]
It's not a bug, but a feature asking, don't know if it's the best place to ask ?

# Required information

 * Distribution: **Debian**
 * Distributions versions: **10.7** => **10.7**
 * Debian 10.7 (**source**) :
   * Kernel version: **5.8.10-1~bpo10+1**
   * LXC version: **4.8**
   * LXD version: **4.8**
   * Storage backend in use: **btrfs**
 * Debian 10.7 (**destination**) :
   * Kernel version: **5.9.6-1~bpo10+1**
   * LXC version: **4.8**
   * LXD version: **4.8**
   * Storage backend in use: **btrfs**

# Feature description

After copying a custom volume, with success
```
destination:~# lxc storage volume copy source:default/backup default/backup
Storage volume copied successfully!
```

I want to copy an incremental, without success
```
destination:~# lxc storage volume copy olddoc:default/backup default/backup
Error: Failed storage volume creation: Volume by that name already exists
```

I try with `--refresh` option, like it works with `lxc copy`
```
destination:~# lxc storage volume copy olddoc:default/backup default/backup --refresh
Error: unknown flag: --refresh
```

# Workaround

I can mount the subvolume, and copie de diff with `rsync`, so this is not required feature, but I think it's more logical if `lxc` can do it.

Thanks in advance.

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/issues/7873

**Comment by olivier-lz** [comment]
Oh sorry, I search, but not find in existing issue :(
I will follow this ticket.
