### ISSUE TITLE
Allow moving storage volumes between projects

### ISSUE THREAD

**Issue by avsdev-cw** [lxc/lxd#8236]
# Required information

 * Distribution: Debian
 * Distribution version: Buster (10) (with backports)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.8.0-0.bpo.2-amd64
   * LXC version: 4.8
   * LXD version: 4.8 (snap rev 18546)
   * Storage backend in use: LVM
   * Storage version in use: 2.02.176(2) (2017-11-03) / 1.02.145 (2017-11-03) / 4.42.0

# Feature Request

I noticed whilst playing around with `lxc storage` and `lxc storage volume` that there appears to be no way to transfer volumes or storage pools between projects. You can however transfer containers between projects using the `--target-project` switch.  Could something similar be implemented please?

**Comment by matthewa150** [comment]
I'd like to try and tackle this.

**Comment by tomponline** [comment]
Thanks! Assigned to you.

**Comment by stgraber** [comment]
@matthewa150 are you still looking into this?

**Comment by matthewa150** [comment]
Yes, sorry for delay. End of year/new year got pretty busy for me, should have something soonish though.

**Comment by stgraber** [comment]
Excellent, looking forward to it!

**Comment by matthewa150** [comment]
I thought I was close to a solution, but as I've worked, I've run into an issue: I'm having trouble seeing the association between pools/volumes and projects. For containers, I can see the project association when looking at the container (for example, when looking at it in a pool, it is shown with `used_by: /1.0/instances/c1?project=foo`); however, I'm having trouble finding where that association is stored for pools/volumes. I might just be missing something simple though.

**Comment by stgraber** [comment]
The `storage_volumes` database table has a `project_id` column for each volume, indicating in what project it's stored.
Though changing that isn't quite sufficient as the on-disk naming for the volume also includes the project name.

So basically you'd need to:
 - Check that the volume isn't currently in use by any instance or profile
 - Check that no custom volume of that name already exist in the target project
 - Cause a volume rename to the new project name
 - Update the database record to put the volume in the target porject

**Comment by stgraber** [comment]
@matthewa150 hey there, are you still interested in fixing this one?

**Comment by stgraber** [comment]
@matthewa150

**Comment by stgraber** [comment]
@presztak all yours if you want it :)

**Comment by stgraber** [comment]
We should do both `lxc storage move` and `lxc storage copy` for this one.

**Comment by presztak** [comment]
@stgraber I would be happy to take this.

**Comment by stgraber** [comment]
Excellent, assigned!

**Comment by stgraber** [comment]
For this I suspect you'll need to add a `Project` field to `StorageVolumeSource` and add server-side handling for it so you can have it copy across projects. Then hook it up to `lxc storage volume copy` and when that works, the initial implementation of `lxc storage volume move` should just be a copy+delete.

We could do a one step move on the server side (like we do for instances) but I don't think it's strictly required now and can add it later as an optimization.
