### ISSUE TITLE
Make it possible to build the client on Windows

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#825]
Currently the client can be built on Linux and MacOS, possibly on some other unix systems too.

However it won't build on Windows due to a bunch of remaining unix-isms which would have to be re-implemented using the Windows equivalent.

Specifically, there are a bunch of file related functions in shared/ which use Unix system calls to retrieve their information, those should be moved to a util_unix.go file and an equivalent be implemented for Windows.

Same goes with a few client features like signal handling for SIGWINCH and stdin/stdout/stderr mode handling in exec. Those would have to be changed to use a generic interface which can then be backed by a unix and a windows backend.

**Comment by techtonik** [comment]
This is 0.18 list of problems when just trying to get the source.
```
> go get github.com/lxc/lxd
# github.com/lxc/lxd/shared
go\src\github.com\lxc\lxd\shared\log.go:28: log15.Must.SyslogHandler undefined (type log15.muster has no field or method SyslogHandler)
go\src\github.com\lxc\lxd\shared\log.go:32: log15.Must.SyslogHandler undefined (type log15.muster has no field or method SyslogHandler)
go\src\github.com\lxc\lxd\shared\util.go:30: undefined: syscall.Stat_t
go\src\github.com\lxc\lxd\shared\util.go:31: undefined: syscall.Lstat
go\src\github.com\lxc\lxd\shared\util.go:106: undefined: syscall.Stat_t
go\src\github.com\lxc\lxd\shared\util.go:336: undefined: syscall.Mmap
go\src\github.com\lxc\lxd\shared\util.go:336: undefined: syscall.PROT_READ
go\src\github.com\lxc\lxd\shared\util.go:336: undefined: syscall.MAP_SHARED
go\src\github.com\lxc\lxd\shared\util.go:340: undefined: syscall.Munmap
go\src\github.com\lxc\lxd\shared\util.go:340: too many errors
```

**Comment by techtonik** [comment]
How do you include util_linux.go dynamically at run-time?

**Comment by techtonik** [comment]
With PR above ready to review, this leaves client with just a few errors:
```
> go install -v ./lxc
github.com/lxc/lxd/shared
# github.com/lxc/lxd/shared
shared\log.go:28: log15.Must.SyslogHandler undefined (type log15.muster has no field or method SyslogHandler)
shared\log.go:32: log15.Must.SyslogHandler undefined (type log15.muster has no field or method SyslogHandler)
shared\util.go:29: undefined: syscall.Stat_t
shared\util.go:30: undefined: syscall.Lstat
shared\util.go:321: undefined: syscall.Mmap
shared\util.go:321: undefined: syscall.PROT_READ
shared\util.go:321: undefined: syscall.MAP_SHARED
shared\util.go:325: undefined: syscall.Munmap
```

Not `too many` as before. =)

**Comment by stgraber** [comment]
Thanks. I guess the log15 one shouldn't be too hard to fix by moving part of that code into a _linux and _windows files.

The bunch of syscall stuff will be a bit trickier I expect :)

**Comment by techtonik** [comment]
With merged #1107 this leaves it to just:
```
> go install -v ./lxc
github.com/lxc/lxd/shared
# github.com/lxc/lxd/shared
shared\log.go:28: log15.Must.SyslogHandler undefined (type log15.muster has no field or method SyslogHandler)
shared\log.go:32: log15.Must.SyslogHandler undefined (type log15.muster has no field or method SyslogHandler)
shared\util.go:29: undefined: syscall.Stat_t
shared\util.go:30: undefined: syscall.Lstat
```

I tried to understand how the logging subsystem works, but couldn't. Not enough experience to Go. I though that this might be a conditional, configurable code. But it looks like it will have to live in separate files anyway.

The last two lines are indeed tricky, because it is `func GetFileStat(p string) (uid int, gid int, major int, minor int,` which is used in `lxd/container.go` and `shared/idmapset,go --> GetOwner --> func (set *IdmapSet) doUidshiftIntoContainer(dir string, testmode bool, how string) error --> ...`. Looks like client doesn't use them.. Hmm..

**Comment by techtonik** [comment]
* [ ] create `shared/log_linux.go` to move syslog handling there
* [ ] move GetFileStat into `shared/util_linux.go` because it doesn't seem to be used by client

**Comment by techtonik** [comment]
This needs to be reopened until #1225 is merged.
