### ISSUE TITLE
Change the editor for "lxc profile edit abc123" to nano in the snap version

### ISSUE THREAD

**Issue by Lyamc** [lxc/lxd#8258]
Version Info
```
lxd     4.8
lxc     4.8
snap    2.48.1
snapd   2.48.1
series  16
ubuntu  20.04
kernel  5.4.0-58-generic
$ which lxc
/snap/bin/lxc
$ which lxc
/snap/bin/lxd
```

Fresh Ubuntu install & apt update
Run `sudo snap install lxd`
When I type `lxc profile edit default` I get vi which is jarring. I'm assuming that the snap doesn't have access to nano or at least has different defaults?

**Comment by stgraber** [comment]
The snap respects `EDITOR`, make sure it's set to `EDITOR=nano` in your bashrc and you'll be good to go.

**Comment by stgraber** [comment]
(Support questions are usually better handled in https://discuss.linuxcontainers.org)

**Comment by Lyamc** [comment]
That doesn't work

![2020-12-15 17-35-41](https://user-images.githubusercontent.com/10787681/102295494-4976bb80-3f00-11eb-8d07-a3fe0d7339f2.png)

**Comment by stgraber** [comment]
```
export EDITOR=nano
lxc profile edit default
```

That works just fine here.

**Comment by stgraber** [comment]
In your case it seems like you may have set `EDITOR` but not exported it?

**Comment by Lyamc** [comment]
Ah, yes you're right. It works now.

**Comment by gschintgen** [comment]
Hm, I've just wanted to post the *opposite* bug as a (minor) regression: `lxd` has started using `nano` (sometime between 4.15 and 4.23) even though I always specify `vim` as my default editor. More to the point: while `lxc` may respect `$EDITOR`, it doesn't use the editor I specifically set using `update-alternatives --config editor` which is, as far as I can tell, the recommended way on Debian/Ubuntu systems.

**Comment by stgraber** [comment]
Yeah, that's unfortunately to be expected as snaps are purposefully isolated from their host system and are distro-agnostic.
