### ISSUE TITLE
lxc copy <ct>/<snapshot> --target-project <proj> <new-ct> causes odd behavior

### ISSUE THREAD

**Issue by avsdev-cw** [lxc/lxd#8273]
# Required information

 * Distribution: Debian
 * Distribution version: Buster (10) (with backports)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.8.0-0.bpo.2-amd64
   * LXC version: 4.8
   * LXD version: 4.8 (snap rev 18546)
   * Storage backend in use: LVM
   * Storage version in use: 2.02.176(2) (2017-11-03) / 1.02.145 (2017-11-03) / 4.42.0

# Issue description
Copying a container snapshot to a new project causes un-expected behaviour. It appears the transfer looks in the target project rather than the source project for the snapshot to copy (even with an explicit `--project default`).

# Steps to reproduce
```
lxc launch images:debian/buster/amd64 ct1
lxc project create backup -c features.images=false -c features.profiles=false -c features.storage.volumes=false
lxc snapshot ct1 backup-20201218
lxc copy ct1/backup-20201218 --target-project backup ct1-backup-20201218
Error: Load source instance from database: Failed to fetch snapshot "backup-20201218" of instance "ct1" in project "backup": No such object
```

NOTE: in this instance I have called the target of the copy "ct1-backup-20201218" but ideally it would be the same name as the original container "ct1".

**Comment by stgraber** [comment]
@tomponline can you take a look?

**Comment by tomponline** [comment]
@stgraber yep looking now

**Comment by avsdev-cw** [comment]
Thank you very much for the quick fix!
