### ISSUE TITLE
Why lxc cp accross cluster take so much time?

### ISSUE THREAD

**Issue by stastnypremysl** [lxc/lxd#8279]
Hello.

I have run `lxc cp blank mail1 --target alpha` across two cluster nodes and it take several hours to be done. I think, there is no real reason to the operation be so much slow. Is there any way, how to optimize it?

The cp takes the longer the more snapshots I have (around 5000), but the snapshot copy on btrfs is itself much faster on my network and takes only few minutes on such small data.

Thanks in advance.

**Comment by stgraber** [comment]
Issue is missing the required data from the issue template.
