### ISSUE TITLE
Events / operations still say "container" when using a VM

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#8281]
When you start a VM you will get an event with the message "starting container"

Would it be possible to say "starting container" or "starting virtual machine" or if easier just the agnostic "starting instance"

**Comment by stgraber** [comment]
Yeah, I've been planning on renaming all the operations to say instance instead. I've already done that to the lifecycle events in 4.9

**Comment by turtle0x1** [comment]
Great thanks!
