### ISSUE TITLE
Incorrect usage amount after creating from custom image

### ISSUE THREAD

**Issue by jamielsharief** [lxc/lxd#8289]
Ubuntu 20.04.1 LTS
LXD version: 4.0.4
zfs-0.8.3-1ubuntu12.5
zfs-kmod-0.8.3-1ubuntu12.5

I created an ubuntu instance, and ran `apt install apache2 mysql-server php`, and then created an image of this using the API by sending a post request to `/images`. 

When I create a new instance using this image, the usage amount is reported as 38MB. If I create an instance and manually install usage is shown as 701.03MB.

![image](https://user-images.githubusercontent.com/20553479/103437164-5e538e80-4c24-11eb-844d-71d4bf847f7f.png)
![image](https://user-images.githubusercontent.com/20553479/103437176-804d1100-4c24-11eb-92fe-526d6532e85f.png)

**Comment by stgraber** [comment]
That's perfectly normal. When crating from a clone, ZFS only tracks the divergence from the base image as disk usage.

If you want to consider the entire size of the dataset, you can switch the `zfs.use_refquota` option.
