### ISSUE TITLE
Post hook: Failed to run: zfs set quota=1000000000 lxdpool/containers/ubuntu: cannot set property for 'lxdpool/containers/ubuntu': size is less than current used or reserved space

### ISSUE THREAD

**Issue by jamielsharief** [lxc/lxd#8291]
Ubuntu 20.04.1 LTS
LXD version: 4.0.4

When testing backing up and restoring I came across the following error, I am noticing this because I am using 1GB limit, but it might apply to any instance on ZFS that goes into the extra 300MB.

```
Post hook: Failed to run: zfs set quota=1000000000 lxdpool/containers/ubuntu: cannot set property for 'lxdpool/containers/ubuntu': size is less than current used or reserved space
```

Here is the info

![config-device-show](https://user-images.githubusercontent.com/20553479/103437374-4f221000-4c27-11eb-8e0b-2b52c0931d25.png)

This is disk usage after creating container

![ubuntu-console-after-install](https://user-images.githubusercontent.com/20553479/103437375-50533d00-4c27-11eb-8011-93251a9c64d8.png)

This is disk usage after installing `apache2 mysql-server php`, it seems to have gone over the limit that I had set.

![ubuntu-console-after-lamp](https://user-images.githubusercontent.com/20553479/103437376-50ebd380-4c27-11eb-8da7-034c6683f29b.png)

Issue #8237 shows the ZFS quota works, but in the container I went over and now run into problems later on.

**Comment by tomponline** [comment]
@jamielsharief I think you are hitting issues related the shared concept of ZFS quotas.

By default LXD creates ZFS instance volumes from snapshots of the base image volume. In this way the quota used related to the differences between the base image and the instance's snapshot volume.

If you want to have dedicated quota for each volume then enable the the following storage pool setting `volume.zfs.use_refquota=true` and then recreate the instance.

**Comment by jamielsharief** [comment]
So If I am not using ZFS and set the root disk size, then what?

**Comment by tomponline** [comment]
Then the quota system of the non zfs pool will be used. I'm not quite following the question though, your report was talking about zfs quotas?

**Comment by jamielsharief** [comment]
Yes my report was about that, but I am trying to understand properly. 

On my installation I am testing ZFS, and I thought if i set the root disk size, then that is the size of the disk.But if I understand you correctly, you are saying that depending upon driver it could mean totally different things.

E.g I create a container and set the root disk size, on ZFS, disk size means difference between snapshot, but other drivers, it could be totally different things.

**Comment by tomponline** [comment]
The disk 'size' property sets the disk quota for the volume on the pool. Depending on the pool driver this is implemented differently based on the functionality provided by the storage system. For example btrfs uses a filesystem level quota and lvm uses a logical volume of the specified size.  Zfs for containers uses a zfs quota and this takes into account actual space used by the snapshot not cumulative size. However the ref counter mode on the zfs driver allows you to make the quota behave more like an lvm volume with a dedicated size.
