### ISSUE TITLE
Lxc config device add unix-block mounts host root device into container

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#8297]
* Distribution: Ubuntu
 * Distribution version: 18.04.5
   * Kernel version: 4.15.0-128-generic x86-64
   * LXC version: 4.9
   * LXD version: 4.9
   * Storage backend in use: zfs
   * Container: Alpine edge (3.12)

`sudo zfs create -s -V 1G zp2/pl2/1001/vd2`
`sudo chown -R 1000000.1000000 /zp2/pl2/1001/vd2`

`ls -lh /dev/zp2/pl2/1001/vd2`
lrwxrwxrwx 1 1000000 1000000 13 Jan  4 09:10 /dev/zp2/pl2/1001/vd2 -> ../../../zd16

`lxc config device add X2 vd2 unix-block uid=1000000 gid=1000000 mode=0660 source=/dev/zp2/pl2/1001/vd2 path=/dev/vd2`
Device vd2 added to X2
`lxc exec X2 ash`
`df -h`
Filesystem                Size      Used Available Use% Mounted on
/dev/mapper/srv9--vg-root    3.9G      1.7G      1.9G  47% /dev/vd2

but expected shall be:
**/dev/zp2/pl2/1001/vd2 1G 1G 0G /dev/vd2**

**Comment by stgraber** [comment]
This is perfectly normal, you're passing `/dev/vd2` in the container, the underlying block device on the host for it is stored on `vg-root` so the bind-mount of that block device file shows up properly.

It's just how bind-mounting special files works on Linux.
