### ISSUE TITLE
Packaging for Fedora

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#830]
I was able to build `lxd` and `lxc` with:
```
sudo dnf install go lxc-devel
cd ~
mkdir -p go
export GOPATH=$PWD/go
go get -v -u github.com/lxc/lxd
cd $GOPATH/src/github.com/lxc/lxd
make
```

But now I can not create container after running `lxd` under root:
```
$ ~/go/bin/lxc init -v --debug ubuntu gpi
2015/07/10 12:53:33 fingering the daemon
2015/07/10 12:53:33 url.Error caught in main(). Op: Get, URL: http://unix.socket/1.0, Err: dial unix /var/lib/lxd/unix.socket: permission denied
2015/07/10 12:53:33 Inner error type is a net.OpError: Op: dial Net: unix Addr: /var/lib/lxd/unix.socket Err: syscall.Errno
Cannot connect to unix socket at /var/lib/lxd/unix.socket Is the server running?
[anatolix@localhost lxd]$ ls -la /var/lib/lxd
total 68
drwxr-xr-x.  4 root root  4096 Jul 10 12:51 .
drwxr-xr-x. 63 root root  4096 Jul 10 12:51 ..
drwxr-xr-x.  2 root root  4096 Jul 10 12:51 devlxd
drwxr-xr-x.  2 root root  4096 Jul 10 12:51 lxc
-rw-r--r--.  1 root root 38912 Jul 10 12:51 lxd.db
-rw-r--r--.  1 root root  1939 Jul 10 12:51 server.crt
-rw-------.  1 root root  3243 Jul 10 12:51 server.key
srw-rw----.  1 root root     0 Jul 10 12:51 unix.socket
```

Do I need to start `lxd` in some special way on Fedora?

**Comment by tych0** [comment]
Try --group $usergroup

**Comment by techtonik** [comment]
Thanks for the hint. Will try when I get there.

**Comment by techtonik** [comment]
@tych0 ehh, where should I add it?
```
$ ~/p/go/go/bin/lxc init -v --debug --group $usergroup ubuntu gpi
error: flag provided but not defined: --group
```

**Comment by stgraber** [comment]
it's a parameter to lxd, not lxc.

**Comment by techtonik** [comment]
Tracing further:
```
$ sudo -E $GOPATH/bin/lxd --group wheel
INFO[08-20|22:27:02] LXD is starting                          path=/var/lib/lxd
WARN[08-20|22:27:02] error reading idmap                      err="user: Current not implemented on linux/amd64"
WARN[08-20|22:27:02] operations requiring idmap will not be available 
INFO[08-20|22:27:02] Init                                     driver=storage/dir
INFO[08-20|22:27:02] Looking for existing certificates:       cert=/var/lib/lxd/server.crt key=/var/lib/lxd/server.key
INFO[08-20|22:27:03] LXD isn't socket activated 
INFO[08-20|22:27:03] REST API daemon: 
INFO[08-20|22:27:03]  - binding socket                        socket=/var/lib/lxd/unix.socket
```
What does it mean?

**Comment by techtonik** [comment]
```
$ lxc init -v ubuntu gpi
Creating gpi error: shared's user has no subuids
```
Forgot to add those subids.

**Comment by stgraber** [comment]
WARN[08-20|22:27:02] error reading idmap                      err="user: Current not implemented on linux/amd64"

is the problem

**Comment by stgraber** [comment]
that error means that your version of Go somehow doesn't implement user.Current() which is required for us to do uid/gid lookup throughout LXD.

Both golang-gc and gccgo implement that function just fine at least starting with Go 1.3, so I'm not sure what's going on with your Go version.

**Comment by techtonik** [comment]
Looks like this Fedora bug https://bugzilla.redhat.com/show_bug.cgi?id=1135152 which fails to natively build some Go components. And also https://github.com/golang/go/issues/6376

**Comment by techtonik** [comment]
With #830 the error changes to:
```
$GOPATH/bin/lxc init --verbose ubuntu gpix
Creating gpix error.
error: setting config item for the container failed
```

**Comment by stgraber** [comment]
That error has mostly been seen when a liblxc ABI change happened without LXD being recompiled from scratch (including rebuilding go-lxc).

Basically upstream LXC had to fix an ABI regression in LXC 1.1, which happened with LXC 1.1.3, so if you had built go-lxc against LXC 1.1.0, 1.1.1 or 1.1.2, then updated to LXC 1.1.3, you'd hit the ABI mismatch which makes LXD hit the wrong liblxc symbol, causing that error message.

I'd recommend wiping your go cache and rebuilding LXD, if that doesn't do the trick, then there may actually be something wrong with the generate LXC configuration.

**Comment by techtonik** [comment]
@stgraber thanks for the insight. I reticketed the issue to summarize the things and let interested parties skip the stuff that is already fixed.

**Comment by techtonik** [comment]
@stgraber killed the cache and still getting the error - see #1156.
