### ISSUE TITLE
Cant call alias command in container .bashrc!

### ISSUE THREAD

**Issue by muslu** [lxc/lxd#8304]
# Required information

 * Distribution: Ubuntu 18.04
   * Kernel version: 5.4.0-59-generic
   * LXC version: 4.9
   * LXD version: 4.9
   * Storage backend in use: zfs

Hi All;

If i create any alias command in container’s .bashrc and call alias than i get error.

For example:

I added alias `netp=’clear; netstat -pulten’`  to **.bashrc** in container (u18base) and `source .bashrc`

When I call `lxc exec u18base — bash -c "netp"`, I get this error `bash: netp: command not found`

If I call `lxc exec u18base — netp` , there is no error/warning on terminal.

Have you any experience?

**Comment by stgraber** [comment]
Closing as such support/usage questions are better handled at https://discuss.linuxcontainers.org

I suspect that non-interactive `bash -c` may not be sourcing the `.bashrc` file, but I've never looked into it.
You may want to look at the bash manpage for that.

`lxc exec u18base -- netp` does not go through a shell at all, so it makes sense that this would not respect .bashrc and would just exit with a non-zero return code.
