### ISSUE TITLE
RFE: lxc restart --console <instance>

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#8313]
I find myself often wanting to use `lxc restart --console --force <instance>` to not lose any console input when restarting an instance. I could of course do `lxc stop --force <instance>` and then `lxc start --console <instance>` but it would be nicer if I could do this with the single restart command. What do you think?

**Comment by stgraber** [comment]
It's already supported :)

**Comment by brauner** [comment]
Hahaha :)
