### ISSUE TITLE
websocket: bad handshake for lxc exec command

### ISSUE THREAD

**Issue by larrycai** [lxc/lxd#832]
new to LXD, try to establish environment, and met problem when I run `lxc exec` command

Ubuntu 15.04 version

    add-apt-repository ppa:ubuntu-lxc/lxd-git-master 
    apt-get update
    apt-get install lxd
    lxd-images import lxc ubuntu trusty amd64 --alias ubuntu
    lxc launch ubuntu ub
    lxc exec ub /bin/bash

While in the last command, it returns error like below

    root@lxd:~# lxc exec ub /bin/bash
    error: websocket: bad handshake

What's wrong with the procedure ?

**Comment by stgraber** [comment]
so that typically hints that your client and server aren't running the same version somehow.

Can you paste:

    which lxc
    which lxd
    lxc --version
    lxd --version
    /usr/bin/lxc --version
    /usr/bin/lxd --version

**Comment by larrycai** [comment]
@stgraber thx.

lxc is just 0.7 version. 

    root@lxd:~# lxc --version
    0.7

I thought it will be auto-updated by `apt-get install lxd`, and after I found the real package name `lxd-client` (not package `lxc`) and install the latest version for `lxc`, it works fine

    root@lxd:~# dpkg -S /usr/bin/lxc
    lxd-client: /usr/bin/lxc
    root@lxd:~# apt-get install lxd-client
    ...

Now I have same version for `lxc`/`lxd`

    root@lxd:~# lxc --version
    0.13
    root@lxd:~# lxd --version
    0.13
