### ISSUE TITLE
lxd import breaks lxc exec CT

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxd#8320]
* Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-58-generic
   * LXC version: 4.0.5
   * LXD version: 4.10
   * Storage backend in use: dir

# Issue description

lxd import breaks lxc exec CT

# Steps to reproduce

 1. `lxc launch ubuntu:20.04 test`
 2. `lxd import test --force`
 3. Output of `lxc exec test -- bash`:
 ```
 Error: Failed to retrieve PID of executing child process
 ```

`lxc restart test` fix this.
Maybe, you should not allow lxd import of running CT.

**Comment by stgraber** [comment]
That should be fixable, this error usually happens as a result of not having an up to date `lxc.conf` for the container.

**Comment by stgraber** [comment]
@tomponline can you look at a quick fix for this?

**Comment by tomponline** [comment]
@stgraber there is already an exported `SaveConfigFile()` function on the `Instance` interface so can use that. However it is currently returning `ErrNotImplemented` for VMs. Is it expected that `lxd import` work for VMs at this time? If not I'll add a check to fail on non-container instances for now.

**Comment by stgraber** [comment]
@tomponline not sure about VMs, if it works, it's likely by accident :)
As I mentioned earlier, qemu does not need its configuration after startup, so I think having the function return nil for VMs should be fine.
