### ISSUE TITLE
lxc rename VM on ceph fails to rename both ceph images  lxd 4.0.4 

### ISSUE THREAD

**Issue by vvolas** [lxc/lxd#8328]
```
andriusjurkus@blazar-linux:~$ lxc rename w10-management w10-managements
Error: Failed to run: rbd --id lxd --cluster ceph --pool ceph-hdd map virtual-machine_w10-managements: rbd: sysfs write failed
rbd: map failed: (2) No such file or directory
```
It leaves like this 
virtual-machine_w10-management
virtual-machine_w10-management**s**.block

I have to manually rename on ceph virtual-machine_w10-management -> virtual-machine_w10-management**s**

**Comment by tomponline** [comment]
Confirmed, looking into this now.
