### ISSUE TITLE
add status of downloading in lxd-images import

### ISSUE THREAD

**Issue by larrycai** [lxc/lxd#833]
running the command `lxd-images import lxc ubuntu trusty amd64 --alias ubuntu --alias ubuntu/trusty`, due to the network problem, the download may last an hour, it will be good to show the progress for the downloading.

For new user, it looks it hangs there.

    Downloading the image: https://images.linuxcontainers.org/images/ubuntu/trusty/amd64/default/20150619_19:15/lxd.tar.xz

It is even better if we can support progressive download

**Comment by tobegit3hub** [comment]
Have the same problem and stuck there.
