### ISSUE TITLE
no lxd iptables rules after installation

### ISSUE THREAD

**Issue by lds-lds** [lxc/lxd#8335]
# Required information

 * Distribution: ubuntu bionic
 * Distribution version: snap 4.0.4
 * The output of "lxc info" 

config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- resources_system
- usedby_consistency
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- storage_rsync_compression
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.96.10.101:8443
  - 10.235.165.1:8443
  - '[fd42:2939:f72d:51d::1]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    -----END CERTIFICATE-----
  certificate_fingerprint: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  driver: lxc
  driver_version: 4.0.5
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-60-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "18.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: xxxx
  server_pid: 11327
  server_version: 4.0.4
  storage: dir
  storage_version: "1"

# Issue description

today i install lxd on a laptop in very restrictive local network

```
snap install lxd --channel=4.0/stable
lxd init
```

I look at the iptables rules, I see that no lxd rule appears

```
# Generated by iptables-save v1.6.1 on Thu Jan 14 15:25:37 2021
*raw
:PREROUTING ACCEPT [123089:165838107]
:OUTPUT ACCEPT [96172:6536304]
COMMIT
# Completed on Thu Jan 14 15:25:37 2021
# Generated by iptables-save v1.6.1 on Thu Jan 14 15:25:37 2021
*mangle
:PREROUTING ACCEPT [123089:165838107]
:INPUT ACCEPT [123084:165837687]
:FORWARD ACCEPT [5:420]
:OUTPUT ACCEPT [96172:6536304]
:POSTROUTING ACCEPT [96269:6547259]
COMMIT
# Completed on Thu Jan 14 15:25:37 2021
# Generated by iptables-save v1.6.1 on Thu Jan 14 15:25:37 2021
*nat
:PREROUTING ACCEPT [5082:298051]
:INPUT ACCEPT [5081:297967]
:OUTPUT ACCEPT [207:16232]
:POSTROUTING ACCEPT [186:14728]
COMMIT
# Completed on Thu Jan 14 15:25:37 2021
# Generated by iptables-save v1.6.1 on Thu Jan 14 15:25:37 2021
*filter
:INPUT ACCEPT [123088:165837895]
:FORWARD ACCEPT [5:420]
:OUTPUT ACCEPT [96178:6536824]
COMMIT
# Completed on Thu Jan 14 15:25:37 2021

```

Here is the lxd log /var/snap/lxd/common/lxd/logs/lxd.log

t=2021-01-14T14:46:38+0100 lvl=info msg="LXD 4.0.4 is starting in normal mode" path=/var/snap/lxd/common/lxd
t=2021-01-14T14:46:38+0100 lvl=info msg="Kernel uid/gid map:" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - u 0 0 4294967295" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - g 0 0 4294967295" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Configured LXD uid/gid map:" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - u 0 1000000 1000000000" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - g 0 1000000 1000000000" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Kernel features:" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - closing multiple file descriptors efficiently: no" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - netnsid-based network retrieval: yes" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - pidfds: yes" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - uevent injection: yes" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - seccomp listener: yes" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - seccomp listener continue syscalls: yes" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - seccomp listener add file descriptors: no" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - attach to namespaces via pidfds: no" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - safe native terminal allocation : yes" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - cgroup layout: hybrid" 
t=2021-01-14T14:46:38+0100 lvl=warn msg=" - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored" 
t=2021-01-14T14:46:38+0100 lvl=warn msg=" - Couldn't find the CGroup memory swap accounting, swap limits will be ignored" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - shiftfs support: disabled" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Initializing local database" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Starting /dev/lxd handler:" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2021-01-14T14:46:38+0100 lvl=info msg="REST API daemon:" 
t=2021-01-14T14:46:38+0100 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/snap/lxd/common/lxd/unix.socket
t=2021-01-14T14:46:38+0100 lvl=info msg=" - binding TCP socket" socket=[::]:8443
t=2021-01-14T14:46:38+0100 lvl=info msg="Initializing global database" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Firewall loaded driver \"nftables\"" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Initializing storage pools" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Initializing daemon storage mounts" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Initializing networks" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Pruning leftover image files" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Done pruning leftover image files" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Loading daemon configuration" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Started seccomp handler" path=/var/snap/lxd/common/lxd/seccomp.socket
t=2021-01-14T14:46:38+0100 lvl=info msg="Pruning expired images" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Done pruning expired images" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Pruning expired instance backups" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Done pruning expired instance backups" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Expiring log files" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Updating instance types" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Done expiring log files" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Done updating instance types" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Updating images" 
t=2021-01-14T14:46:38+0100 lvl=info msg="Done updating images" 
t=2021-01-14T14:46:38+0100 lvl=warn msg="Failed to update instance types: Get \"https://images.linuxcontainers.org/meta/instance-types/.yaml\": read tcp 10.96.10.101:36918->91.189.91.21:443: read: connection reset by peer"

**Comment by tomponline** [comment]
LXD is using the nftables firewall:

```
t=2021-01-14T14:46:38+0100 lvl=info msg="Firewall loaded driver "nftables""
```

So take a look at the nft rules:

```
sudo nft list ruleset
```
