### ISSUE TITLE
LXD's cleanup of /run upon start breaks network namespaces

### ISSUE THREAD

**Issue by axinojolais** [lxc/lxd#8336]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-62-generic
   * LXC version: ?
   * LXD version: snap 18150 (4.0/stable right now)
   * Storage backend in use: N/A

# Issue description

I have some custom systemd scripts creating network namespaces before network.target (a tweaked version of https://cloudnull.io/2019/04/running-services-in-network-name-spaces-with-systemd/)
It would appear that when LXD starts, it "cleans up" /run and this very probably breaks my namespaces.

journalctl show me :

```
Jan 14 16:07:19 x systemd[1]: Starting Named network namespace frr...
Jan 14 16:07:19 x systemd[1]: run-netns-frr.mount: Succeeded.
Jan 14 16:07:19 x systemd[1]: Finished Named network namespace frr.
```
this is my custom service creating the netns. A bit later :
```
Jan 14 16:07:24 x lxd.daemon[3340]: ==> Preparing a clean copy of /run
Jan 14 16:07:24 x systemd[1]: run-netns-frr.mount: Succeeded.
Jan 14 16:07:24 x lxd.daemon[3340]: ==> Preparing /run/bin
```
(my netns is named "frr"), after what I get the following :
```
$ sudo ip netns
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
frr
```
because the mount holding the netns has been removed (there are still processes in the netns, so it's still there)

After removing the LXD snap, I don't have this problem.

What does "Preparing a clean copy of /run" do exactly ? Could it break my netns ? If yes, could it please stop doing that ? :)

Thanks

**Comment by stgraber** [comment]
Everything the LXD snap does is done in a separate mount namespace and so cannot impact the entries on the host.
You can easily see the two different /run copies with (as root):
 - ls -lh /run
 - ls -lh /proc/$(cat /var/snap/lxd/common/lxd.pid)/root/run/

I wonder if you're maybe dealing with a systemd bug there where a mount in a separate mount namespace is somehow re-triggering your mount unit.

You can try that hypothesis by manually running `unshare -m` as root and then in that sub-shell run `mount -t tmpfs tmpfs /run`.
This will similarly not impact any process outside of that unshare instance, but may similarly confuse systemd.
If that's the issue, then systemd itself may need some fixing.

(Tentatively closing as I strongly suspect this isn't a LXD issue).

**Comment by axinojolais** [comment]
Related : https://github.com/lxc/lxd-pkg-snap/commit/a58e72e819f37495cd6bb174b551a2ba928e1efc

Thanks @stgraber :)
