### ISSUE TITLE
Feature request: Allow multiple mntdir devices.

### ISSUE THREAD

**Issue by pcdummy** [lxc/lxd#834]
I tried to add two mntdir devices to a lxd container, but the second overwrites the first.

    lxc config device add srv01:files2 mntdir disk source=/media/MEDIEN path=media/MEDIEN
    lxc config device add srv01:files2 mntdir disk source=/cdata path=cdata

It should be possible to add multiple dirs i think.

**Comment by stgraber** [comment]
that's because you're using the same device name for both, "mntdir". So the second redefines the "mntdir" device entry, overriding it.

Instead:

    lxc config device add srv01:files2 mntdir-media disk source=/media/MEDIEN path=media/MEDIEN
    lxc config device add srv01:files2 mntdir-cdata disk source=/cdata path=cdata

Should work fine.

**Comment by pcdummy** [comment]
That works, thanks a lot!
