### ISSUE TITLE
Delete port from ovs when stopping container

### ISSUE THREAD

**Issue by reversecipher** [lxc/lxd#835]
LXD adds container veth automatically to ovs-bridge when specified as parent in container config, but when container is stopped veth doesn't get removed from ovs-bridge.

Steps to reproduce:

Create bridge and add it to container config:
```
ovs-vsctl add-br br-int
lxc config device add test eth0 nic parent=br-int nictype=bridged
```

Start container and check that veth gets added to bridge:
```
lxc start test

lxc list
+------+---------+------+------+-----------+-----------+
| NAME |  STATE  | IPV4 | IPV6 | EPHEMERAL | SNAPSHOTS |
+------+---------+------+------+-----------+-----------+
| test | RUNNING |      |      | NO        | 0         |
+------+---------+------+------+-----------+-----------+

ovs-vsctl show
849c8cb9-1dcd-477f-931c-beeadb4ceb3b
    Bridge br-int
        Port "vethSL5GF4"
            Interface "vethSL5GF4"
        Port br-int
            Interface br-int
                type: internal
    ovs_version: "2.0.2"
```

Stop container and check ovs-bridge:
```
lxc stop test

lxc list
+------+---------+------+------+-----------+-----------+
| NAME |  STATE  | IPV4 | IPV6 | EPHEMERAL | SNAPSHOTS |
+------+---------+------+------+-----------+-----------+
| test | STOPPED |      |      | NO        | 0         |
+------+---------+------+------+-----------+-----------+

ovs-vsctl show
849c8cb9-1dcd-477f-931c-beeadb4ceb3b
    Bridge br-int
        Port "vethSL5GF4"
            Interface "vethSL5GF4"
        Port br-int
            Interface br-int
                type: internal
    ovs_version: "2.0.2"
```

Workaround is to add `raw.lxc: lxc.network.0.script.down` to container config and create script that removes the container veth from bridge.

It would be nice to have LXD remove the veth automatically when container is stopped.

**Comment by stgraber** [comment]
That'd actually be a LXC issue, not a LXD one. LXD itself has no knowledge of openvswitch.

Could you file a bug at github.com/lxc/lxc instead?

What I found odd is that openvswitch doesn't automatically destroy the port when the interface disappears (as should be the case when the container exits).

**Comment by stgraber** [comment]
Closing this one, tracking in LXC instead.
