### ISSUE TITLE
Configuration of VM isn't updated when adding new disks

### ISSUE THREAD

**Issue by grebennikov** [lxc/lxd#8358]
Focal
LXD 4.10
Storage backend - file

Created a VM with one additional volume, VM runs, volume is working.
Shutdown the VM, add 2 more volumes, "lxc config" reflects that.
However looking into the qemu config for the VM still see that only one volume is attached.

$ lxc storage volume list default|grep osd
| custom          | osd1         |             | block        | 1       |
| custom          | osd2         |             | block        | 1       |
| custom          | osd3         |             | block        | 1       |

$ lxc config show ceph-osd3|grep osd
  osd1:
    source: osd1
  osd2:
    source: osd2
  osd3:
    source: osd3

$ sudo cat /var/snap/lxd/common/lxd/logs/ceph-osd3/qemu.conf|grep osd
addr = "/var/snap/lxd/common/lxd/logs/ceph-osd3/qemu.spice"
file = "/var/snap/lxd/common/lxd/virtual-machines/ceph-osd3/qemu.nvram"
path = "/var/snap/lxd/common/lxd/logs/ceph-osd3/qemu.monitor"
path = "/var/snap/lxd/common/lxd/virtual-machines/ceph-osd3/config"
path = "/var/snap/lxd/common/lxd/logs/ceph-osd3/virtio-fs.config.sock"
# osd1 drive
[drive "lxd_osd1"]
file = "/var/snap/lxd/common/lxd/storage-pools/default/custom/default_osd1/root.img"
[device "dev-lxd_osd1"]
drive = "lxd_osd1"
# osd2 drive
[drive "lxd_osd2"]
file = "/var/snap/lxd/common/lxd/storage-pools/default/custom/default_osd2/root.img"
[device "dev-lxd_osd2"]
drive = "lxd_osd2"
file = "/var/snap/lxd/common/lxd/storage-pools/default/virtual-machines/ceph-osd3/root.img"

**Comment by tomponline** [comment]
VM's config file is only updated at next start. Are you able to post a full-reproducer showing the commands you run to add the drives, and the lack of devices being represented in the VM at next start?

**Comment by grebennikov** [comment]
@tomponline 
I'm so sorry folks, I don't have access to the environment anymore to re-test it.
One part of the problem was that when creating the device without specifying the size was a cloze-to-zero size that just confused the VM.
