### ISSUE TITLE
Improve rendering and user experience of "lxc config trust"

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#836]
Currently the user is presented with very long fingerprints which must be copy/pasted in their entirety.

Partial match should probably be allowed and the rendering should be done as a tidier table.

**Comment by pcdummy** [comment]
Hey @stgraber what do you mean with "tidier table" ?

This is what it looks like with Pull #848 

    $ lxc config trust list
    e5cc118418f926436af5990b363911d898f5309731946d2d37c51bc7b2cf24e9

I want it to look like in issue #849

**Comment by stgraber** [comment]
Basically we should render it as a table just like we do for containers and images.

As for printing an identifier, we don't need to extend the API for that. A recursive query against /1.0/containers will get you the fingerprint and PEM representation of all certificates.

The client can then easily parse the PEM blob and extract the commonName from it, as well as things like issue date, expiry, ...

**Comment by pcdummy** [comment]
Ok, will implement that soon.

**Comment by pcdummy** [comment]
Hmm we don't have much informations in that cert.

    # openssl x509 -in ~/.config/lxc/client.crt -text
    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number:
                36:70:ab:2d:0f:b3:2a:bf:fe:ea:48:1c:3f:69:2a:bc
        Signature Algorithm: sha256WithRSAEncryption
            Issuer: O=linuxcontainers.org
            Validity
                Not Before: Jun 29 11:19:29 2015 GMT
                Not After : Jun 26 11:19:29 2025 GMT
            Subject: O=linuxcontainers.org
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (4096 bit)
                    Modulus:
                        00:ad:37:16:af:e2:98:f8:1b:cf:a7:26:78:4c:03:
                        e2:d9:c1:a7:fa:7e:bc:f9:cc:15:75:48:ce:21:6f:
                        8b:7a:03:76:f3:71:cc:fa:52:71:53:f8:dc:34:7a:
                        30:9e:e2:b6:76:0a:3b:aa:7b:db:6a:1b:db:88:98:
                        9c:c7:ad:8e:d1:e7:e6:ca:f3:fc:49:da:ab:ad:07:
                        3b:e2:07:e3:66:5a:b3:6d:6e:3f:36:4b:83:cd:54:
                        ae:f6:2b:65:96:8d:2d:ed:6b:60:e2:08:20:89:9b:
                        91:24:07:b6:78:93:84:0b:e9:b5:56:79:9f:90:8b:
                        74:46:4d:47:2f:ce:29:6a:26:04:85:7c:ac:0c:51:
                        7a:26:0a:57:55:29:f9:fe:e3:1b:20:bf:2f:71:7e:
                        f6:bb:7e:c7:1b:08:53:a3:28:b6:28:e6:30:ca:90:
                        38:0a:14:d0:cd:ac:9a:2b:8b:d1:46:b1:80:1e:69:
                        a8:d4:97:6b:ab:8c:30:c7:4e:61:9c:7f:05:22:1f:
                        96:a4:24:cf:fb:68:b0:8b:d4:81:f1:58:71:97:2e:
                        bd:c3:85:0d:fa:28:be:7f:00:19:6c:bf:11:ba:f2:
                        03:a8:e5:c9:d5:c3:3c:8c:24:54:f2:51:1b:b1:11:
                        de:c1:bc:e1:d7:09:d0:e9:7f:91:64:fe:c1:3c:ac:
                        53:3b:4c:38:6a:00:00:97:a5:a3:50:06:fe:89:af:
                        17:ad:a1:95:c1:96:b1:40:f5:ce:2e:67:c8:ce:37:
                        ee:1e:88:64:a0:b6:1a:3c:1a:3f:1e:64:65:f9:93:
                        00:56:99:f8:03:69:5e:a3:b9:0b:a2:95:98:01:45:
                        2b:14:b7:61:f4:79:65:fd:ee:18:91:92:e1:2e:37:
                        f0:15:4b:62:7e:36:1f:94:bb:ef:7c:87:ee:e9:f6:
                        a0:47:4c:50:76:48:01:cc:7a:f0:b1:51:3f:d4:44:
                        42:fd:99:ae:8d:a1:ef:38:67:8f:ca:fd:9d:d7:cd:
             73:0f:22:7f:ec:44:1a:a8:ed:2a:21:15:4b:f8:9e:f8:e7:a0:
             f2:13:68:c2:24:0a:5a:53:79:2d:d2:86:1e:83:73:df:33:5e:
             99:d2:f6:dc:27:86:85:11:73:04:25:d5:0f:05:f4:d2:d0:70:
             a2:67:e8:e3:f3:c4:8f:b0:cd:61:3e:81:97:83:6c:9c:85:01:
             b0:7a:2e:4c:d3:8e:30:3b:3f:64:9d:47:60:e6:72:80:ab:1c:
             eb:f8:56:6e:7f:c5:63:10:20:23:44:b1:2c:18:b0:cd:cb:41:
             22:ac:ed:70:a9:e5:9a:2a:d5:cf:fb:7b:95:cf:81:cf:f6:9b:
             fb:71:d1:8d:9d:c2:ff:d5:ae:5b:c6:1b:e1:e7:86:13:5c:b9:
             51:16:14:fe:63:7e:33:e7:85:94:31:9e:2e:93:0d:15:68:ee:
             6b:9e:7b:0e:cd:f8:dd:0e:74:76:4d:6d:b8:1a:a0:33:98:03:
             28:75:2b:ba:5c:e6:7b:47:68:6c:4e:3d:40:69:de:6f:7d:4a:
             a4:b7:98:64:c4:db:24:c3:19:47:36:26:1b:91:ef:40:a0:65:
             58:76:c2:f6:8b:40:50:7e:a9:78:83:11:89:40:e2:a0:eb:ef:
             ff:cd:12:da:2c:df:1f:e4:b1:98:ba:f1:1c:0e:db:89:db:c1:
             b9:fe:ec:74:49:2b:c2:c6:b7:c6:24:e6:0f:11:30:ff:4e:f3:
             8c:1c:9d:e0:1b:95:90:48:ce:46:9f:4e:af:b1:d0:40:af:65:
             ab:de:d5:86:8b:9a:3f:b3:38:ac:cf:e5:b5:58:d9:85:86:ba:
             50:13:34:5a:9d:7b:4b:c8:e2:82:8b:99:90:9f:50:10:e0:9b:
             65:fe:cd:55:23:8b:98:d3:26:05:0b:d6:48:c1:d9:f1:78:f0:
             c9:41:35:33:18:4b:d2:b1
    -----BEGIN CERTIFICATE-----
    MIIFCTCCAvOgAwIBAgIQNnCrLQ+zKr/+6kgcP2kqvDALBgkqhkiG9w0BAQswHjEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzAeFw0xNTA2MjkxMTE5MjlaFw0y
    NTA2MjYxMTE5MjlaMB4xHDAaBgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcwggIi
    MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCtNxav4pj4G8+nJnhMA+LZwaf6
    frz5zBV1SM4hb4t6A3bzccz6UnFT+Nw0ejCe4rZ2Cjuqe9tqG9uImJzHrY7R5+bK
    8/xJ2qutBzviB+NmWrNtbj82S4PNVK72K2WWjS3ta2DiCCCJm5EkB7Z4k4QL6bVW
    eZ+Qi3RGTUcvzilqJgSFfKwMUXomCldVKfn+4xsgvy9xfva7fscbCFOjKLYo5jDK
    kDgKFNDNrJori9FGsYAeaajUl2urjDDHTmGcfwUiH5akJM/7aLCL1IHxWHGXLr3D
    hQ36KL5/ABlsvxG68gOo5cnVwzyMJFTyURuxEd7BvOHXCdDpf5Fk/sE8rFM7TDhq
    AACXpaNQBv6JrxetoZXBlrFA9c4uZ8jON+4eiGSgtho8Gj8eZGX5kwBWmfgDaV6j
    uQuilZgBRSsUt2H0eWX97hiRkuEuN/AVS2J+Nh+Uu+98h+7p9qBHTFB2SAHMevCx
    UT/UREL9ma6Noe84Z4/K/Z3XzV2lD2z2B4vcEmQ2pfGUE1vI6x6iOOQ9At6njkIK
    pkt+sc2l29lgmz9/YHzDolv2nQ3v4IYOSUxFwGb8f8DCoPf9jZyCmEFTXoomQqPi
    NLqFAmR/AifkI/3GIwYAkNK7WhMIUv3bdhUK9S9wPsSDa2DlTVCK0T6mtM/7KBwF
    8jKhr56Gpy31p8nFnQIDAQABo0cwRTAOBgNVHQ8BAf8EBAMCAKAwEwYDVR0lBAww
    CgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAQBgNVHREECTAHggVzcnYwMTALBgkq
    hkiG9w0BAQsDggIBAFio6RVopbLGlYCFglcxJYBzd8yy/3ZVa3JLdBG1V8rlQyNn
    TuNw4yXQ5c2lqJv0IZ0IpH+nnLdmyO/OZ/pb/QjQB6G8G/udbnUODjQyYpeLTIKt
    C15/+mB+E2Kym/q3tTNQtbfCNIwknH7vNnWrEyA97zFSrN45Wn9ylZhxIjxIfxT7
    4aV1CNbdJR5HJ4Tfb6HzGzqBDiQdi9LCF3criP/OjHMPIn/sRBqo7SohFUv4nvjn
    oPITaMIkClpTeS3Shh6Dc98zXpnS9twnhoURcwQl1Q8F9NLQcKJn6OPzxI+wzWE+
    gZeDbJyFAbB6LkzTjjA7P2SdR2DmcoCrHOv4Vm5/xWMQICNEsSwYsM3LQSKs7XCp
    5Zoq1c/7e5XPgc/2m/tx0Y2dwv/VrlvGG+HnhhNcuVEWFP5jfjPnhZQxni6TDRVo
    7mueew7N+N0OdHZNbbgaoDOYAyh1K7pc5ntHaGxOPUBp3m99SqS3mGTE2yTDGUc2
    JhuR70CgZVh2wvaLQFB+qXiDEYlA4qDr7//NEtos3x/ksZi68RwO24nbwbn+7HRJ
    K8LGt8Yk5g8RMP9O84wcneAblZBIzkafTq+x0ECvZave1YaLmj+zOKzP5bVY2YWG
    ulATNFqde0vI4oKLmZCfUBDgm2X+zVUji5jTJgUL1kjB2fF48MlBNTMYS9Kx
    -----END CERTIFICATE-----

**Comment by stgraber** [comment]
Mine here has a X509v3 DNS alt field which contains the hostname of the machine which generated the certificate.

But we probably should set the Subject field to USER@HOSTNAME or something along those lines.

**Comment by pcdummy** [comment]
I would resolve the clients ip on the lxd host and save that in the db (+ the original ip).

**Comment by stgraber** [comment]
Hmm, I'm concerned it'd be more confusing than anything. On an IPv6 network, you're going to just end up with a bunch of privacy extension temporary IPv6 addresses which won't have a PTR record, so effectively storing a bunch of meaningless numbers that won't even respond if you try to contact them (as those expire rather quickly).

**Comment by stgraber** [comment]
I think setting better values for the X509 fields and displaying those on the client when listing the certificates is a better approach which doesn't require any DB or API change and better shows exactly what the server trusts.
