### ISSUE TITLE
devices: disk: EPERM on fchmod() and utimensat() calls

### ISSUE THREAD

**Issue by iam-TJ** [lxc/lxd#8372]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.11-0-rc3
   * LXC version: 4.10
   * LXD version: 4.10
   * Storage backend in use: dir

# Issue description

EPERM returned by calls to utimensat() with a host directory mounted inside a container.

I use containers for building software, with source editing on the host-side and building inside containers to contain the build-
dependencies and out-of-archive tool versioning (especially with nodejs ecosystem!).

```
$ lxc profile show builder
config:
  raw.idmap: |
    uid 1000 1000
    gid 1000 1000
  user.vendor-data: |
    users:
     - name: ubuntu
       groups: sudo
       shell: /bin/bash
       sudo: ['ALL=(ALL) NOPASSWD:ALL']
    packages:
     - bash
description: Include source-code directory to allow building software in confined
  container
devices:
  sourcecode:
    path: /media/ubuntu/SourceCode
    source: /media/tj/SourceCode
    type: disk
name: builder
used_by:
- /1.0/instances/u2004
- /1.0/instances/fomantic-builder
```

As seen above "fomantic-builder" (for nodejs based build system of Fomantic-UI/Fomantic-UI-Docs) is an Ubuntu 20.04 image.

Permissions on `/media/tj/SourceCode/fomantic/` and all files and sub-dirs are 0666/0777 (ugo=rw/ugo=rwx) to allow the container user IDs write permissions and that works correctly most of the time..

```
$ ls -l /media/tj/SourceCode/fomantic
total 36
drwxrwxrwx  8 tj      tj      4096 Jan 15 08:20 create-fomantic-icons
lrwxrwxrwx  1 1000000 1000000   16 Jan 21 13:55 docs -> Fomantic-UI-Docs
drwxrwxrwx  3 tj      tj      4096 Jan 18 11:05 docs2
-rw-rw-r--  1 tj      tj       662 Jan 22 05:00 docs-docsearch-remove.patch
-rw-rw-r--  1 tj      tj      1801 Jan 22 04:42 docs-offline.patch
drwxrwxrwx 11 tj      tj      4096 Jan 21 13:57 Fomantic-UI
drwxrwxrwx  5 tj      tj      4096 Jan 15 08:18 Fomantic-UI-CSS
drwxrwxrwx  6 tj      tj      4096 Jan 21 13:30 Fomantic-UI-Docs
drwxrwxrwx  9 tj      tj      4096 Jan 15 06:32 Fomantic-UI-SASS
drwxrwxrwx  5 tj      tj      4096 Jan 21 13:55 httrack
lrwxrwxrwx  1 1000000 1000000   11 Jan 21 13:36 ui -> Fomantic-UI

root@fomantic-builder:~/fomantic/ui# ls -l /media/ubuntu/SourceCode/fomantic/
total 36
drwxrwxrwx 11 nobody nogroup 4096 Jan 21 13:57 Fomantic-UI
drwxrwxrwx  5 nobody nogroup 4096 Jan 15 08:18 Fomantic-UI-CSS
drwxrwxrwx  6 nobody nogroup 4096 Jan 21 13:30 Fomantic-UI-Docs
drwxrwxrwx  9 nobody nogroup 4096 Jan 15 06:32 Fomantic-UI-SASS
drwxrwxrwx  8 nobody nogroup 4096 Jan 15 08:20 create-fomantic-icons
lrwxrwxrwx  1 root   root      16 Jan 21 13:55 docs -> Fomantic-UI-Docs
-rw-rw-r--  1 nobody nogroup  662 Jan 22 05:00 docs-docsearch-remove.patch
-rw-rw-r--  1 nobody nogroup 1801 Jan 22 04:42 docs-offline.patch
drwxrwxrwx  3 nobody nogroup 4096 Jan 18 11:05 docs2
drwxrwxrwx  5 nobody nogroup 4096 Jan 21 13:55 httrack
lrwxrwxrwx  1 root   root      11 Jan 21 13:36 ui -> Fomantic-UI

```
In container, when running the command `gulp build-docs` it hits an error "Permission Denied" which, after some digging, strace revealed to be caused by:

```
root@fomantic-builder:~/fomantic/ui# grep -n fchmod /tmp/gulp.strace 
149103:16719 fchmod(23, 0100777 <unfinished ...>
149106:16719 <... fchmod resumed>)             = -1 EPERM (Operation not permitted)
149203:16720 fchmod(21, 0100777)               = -1 EPERM (Operation not permitted)

```
Here's a contextual extract from the strace:

```
16720 openat(AT_FDCWD, "/media/ubuntu/SourceCode/fomantic/Fomantic-UI/dist/components/reset.css", O_WRONLY|O_CREAT|O_TRUNC
|O_CLOEXEC, 0100777 <unfinished ...>
...
16720 <... openat resumed>)             = 21
...
16720 fchmod(21, 0100777)               = -1 EPERM (Operation not permitted)
...
16718 utimensat(21, NULL, [{tv_sec=1611237513, tv_nsec=68000000} /* 2021-01-21T13:58:33.068000000+0000 */, {tv_sec=1610692
810, tv_nsec=605000000} /* 2021-01-15T06:40:10.605000000+0000 */], 0 <unfinished ...>
...
16718 <... utimensat resumed>)          = -1 EPERM (Operation not permitted)
```
It looks as if the issue is with the mode flag:

`S_ISVTX  (01000)  sticky bit `

# Information to attach

Attached:  - [ ] Container configuration (`lxc config show NAME --expanded`) 
[lxc-config-show-expanded.txt](https://github.com/lxc/lxd/files/5855740/lxc-config-show-expanded.txt)

**Comment by stgraber** [comment]
@brauner ideas?

**Comment by brauner** [comment]
You're not privileged over the inode which is required to change ownership. Simply put that "nobody:nogroup" indicates that you don't have an idmapping for the uid and gid in question and so the kernel will not allow you to change the owner or mode. It looks like some of your files aren't writable for the other group. Thta's why utimensat files. If you change that utimensat should work.

**Comment by stgraber** [comment]
Oh yeah, oops, I missed that the entry you were trying to change was outside of the container's uid/gid range, so indeed the error makes sense then.
