### ISSUE TITLE
Live migrate VMs

### ISSUE THREAD

**Issue by vosdev** [lxc/lxd#8386]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04.1
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux node1 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version:
   * LXD version: 4.10
   * Storage backend in use: Ceph

# Issue description

I was trying to move a running VM to a second node and unfortunately that is a feature that does not exist (yet?)

The error states that the `container is running` . That should say instance.
```
~
root @ node1 # lxc ls --fast flying-leech
+--------------+---------+--------------+----------------------+----------+-----------------+
|     NAME     |  STATE  | ARCHITECTURE |      CREATED AT      | PROFILES |      TYPE       |
+--------------+---------+--------------+----------------------+----------+-----------------+
| flying-leech | RUNNING | x86_64       | 2020/09/28 09:28 UTC | default  | VIRTUAL-MACHINE |
+--------------+---------+--------------+----------------------+----------+-----------------+

~
root @ node1 # lxc move flying-leech --target node2
Error: Migration API failure: Container is running
```

Is the ability to live-migrate a VM in a cluster something on the wish list for the LXD project? And if not, I would like to request it :-)

Related to live migration; I have criu enabled in the snap but I understand from earlier github issues (~2018) that live migration of containers is a nono in a cluster but possible when not clustered. The project has improved immensely in the past few years . Is this limitation still necessary ?

**Comment by stgraber** [comment]
VM live migration is on the roadmap but it will take time for us to get there.
We have some initial work scheduled for this cycle to attempt to get stateful stop and snapshots working with VMs.

On the CRIU side, CRIU is currently pretty broken with LXD. We have @brauner working on a couple of critical issues there, once that's sorted we should be able to resume automated testing of live migration in the non-cluster case and maybe eventually allow for it in the cluster case too.

The main difficulty with the cluster case is the temporary rename of the instance as it's being migrated (instance is copied using a UIUD then source is deleted and lastly instance is renamed), it should be doable to get CRIU to behave there too once we sort out the other issues.

**Comment by tomponline** [comment]
I fixed the error message that mentioned container and changed it to instance. https://github.com/lxc/lxd/pull/8387
