### ISSUE TITLE
lxc image copy <source>:<image> <target> fails with metadata.yaml error

### ISSUE THREAD

**Issue by pcdummy** [lxc/lxd#839]
I tried to do the following, it fails with a metadata.yaml error.

    $ lxc image copy srv01:ubuntu/trusty/amd64 srv02: --debug
    2015/07/14 10:07:52 fingering the daemon
    2015/07/14 10:07:53 raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_compat":1,"auth":"trusted","config":{"core.trust_password":true},"environment":{"backing_fs":"btrfs","driver":"lxc","kernel_version":"3.19.0-21-generic","lxc_version":"1.1.2","lxd_version":"0.13"}}}
    2015/07/14 10:07:53 pong received
    2015/07/14 10:07:53 fingering the daemon
    2015/07/14 10:07:54 raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_compat":1,"auth":"trusted","config":{"core.trust_password":true},"environment":{"backing_fs":"btrfs","driver":"lxc","kernel_version":"3.19.0-22-generic","lxc_version":"1.1.2","lxd_version":"0.13"}}}
    2015/07/14 10:07:54 pong received
    2015/07/14 10:07:54 raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"target":"451c1b479aa516a5d9106353cf9dd9fc6ed9220a5684da0a192950315caf00bb","description":"ubuntu/trusty/amd64"}}
    2015/07/14 10:07:54 raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"aliases":[{"target":"ubuntu/trusty","description":"ubuntu/trusty"},{"target":"ubuntu/trusty/amd64","description":"ubuntu/trusty/amd64"}],"architecture":0,"fingerprint":"451c1b479aa516a5d9106353cf9dd9fc6ed9220a5684da0a192950315caf00bb","filename":"","properties":{},"public":0,"size":137758073,"created_at":0,"expires_at":0,"uploaded_at":1436618208}}
    2015/07/14 10:08:07 raw response: {"error":"Could not extract image metadata metadata.yaml from tar: exit status 2 (tar: metadata.yaml: Nicht im Archiv gefunden.)","error_code":500,"type":"error"}

    2015/07/14 10:08:07 Error caught in main: *errors.errorString
    error: Could not extract image metadata metadata.yaml from tar: exit status 2 (tar: metadata.yaml: Nicht im Archiv gefunden.)

lxc and both lxd are on latest master.

**Comment by pcdummy** [comment]
Same with lxc image import, **image.tar contains a metadata.yaml**

    pcdummy@UbuntuPro:~/Downloads$ lxc image import image.tar srv02: --debug
    2015/07/14 10:22:33 fingering the daemon
    2015/07/14 10:22:34 raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_compat":1,"auth":"trusted","config":{"core.trust_password":true},"environment":{"backing_fs":"btrfs","driver":"lxc","kernel_version":"3.19.0-22-generic","lxc_version":"1.1.2","lxd_version":"0.13"}}}
    2015/07/14 10:22:34 pong received
    2015/07/14 10:22:43 raw response: {"error":"Could not extract image metadata metadata.yaml from tar: exit status 2 (tar: metadata.yaml: Nicht im Archiv gefunden.)","error_code":500,"type":"error"}

    2015/07/14 10:22:43 Error caught in main: *errors.errorString
    error: Could not extract image metadata metadata.yaml from tar: exit status 2 (tar: metadata.yaml: Nicht im Archiv gefunden.)

**Comment by pcdummy** [comment]
This fixes that error:

    diff --git a/lxd/images.go b/lxd/images.go
    index 2169683..6000be7 100644
    --- a/lxd/images.go
    +++ b/lxd/images.go
    @@ -572,7 +572,7 @@ func xzReader(r io.Reader) io.ReadCloser {
     }
     
     func getImageMetadata(fname string) (*imageMetadata, error) {
    -       metadataName := "metadata.yaml"
    +       metadataName := "/metadata.yaml"
     
            compression, _, err := detectCompression(fname)

But **metadata.yaml** is **json** not **yaml** ?

**Comment by pcdummy** [comment]
Yeah **scripts/lxd-image**

        # Add the metadata file
        metadata_yaml = json.dumps(metadata, sort_keys=True,
                                   indent=4, separators=(',', ': '),
                                   ensure_ascii=False).encode('utf-8') + b"\n"

        metadata_file = tarfile.TarInfo()
        metadata_file.size = len(metadata_yaml)
        metadata_file.name = "metadata.yaml"
        target_tarball.addfile(metadata_file,
                               io.BytesIO(metadata_yaml))

**Comment by stgraber** [comment]
json is conveniently a subset of yaml so a json document will be successfully parsed by a yaml parser.
As python doesn't come with a yaml parser by default and I didn't want to depend on external module, I've simply been using the json parser/writer instead.

Anyway, with that branch merged, I think we can close this issue now.

Thanks for the fix!
