### ISSUE TITLE
lxd 4.0.4 ceph cluster cant move vm if one member is not reachable 

### ISSUE THREAD

**Issue by vvolas** [lxc/lxd#8394]
This is on ceph so there shouldnt be anything holding to do so?

I had one cluster member locked up and  tried move my vm to other cluster member.

lxc move  something --target aa 
"Error: Migration API failure: Missing event connection with target cluster member"

**Comment by stgraber** [comment]
LXD doesn't need all servers to be online for such an operation and I've frequently done it on cluster with some dead machines.

The error you're getting means that the server your CLI client is configured to talk to and the target server of that move operation aren't talking to each other properly.

**Comment by vvolas** [comment]
OK maybe I m doing something wrong.

**Comment by GuanglinDu** [comment]
This "Missing event connection with target cluster member" started bothering me today after I replaced the faulty HDD of one cluster member. Before the replacement, that HDD had been warning me for months.

- Bad sectors detected (`sudo badblocks -v /dev/sda > badsectors.txt`).
- More malfunction appeared frequently in recent days when running lxc commands.

I thought the replacement would fix both the warning and the cluster malfunction on this node. I cannot find out what type of RAID existed on this server, but there is some RAID as the replacement is successful. Unfortunately, only the HDD warning disappeared. 

When I run `sudo lxd cluster list-database` on the other members (a 4-member cluster), this node is not among the returned IP address list. It seems that the LXD db has lost this record. Can I manually modify the LXD db to recover this member?  Or is there some way to notify LXD to re-join this member? Thanks. @stgraber

**Comment by GuanglinDu** [comment]
@stgraber Sorry, the bad sectors remain and are the same sector IDs in spite of the replacement. I have to continue to trouble-shoot the problem. It appears it's not the fault of LXD.
