### ISSUE TITLE
LXC binary

### ISSUE THREAD

**Issue by killua-eu** [lxc/lxd#8418]
Hi all,

I'm trying to move our ansible-based management to awx/tower and am hitting a major issue. We extensively use the lxd_connection plugin, which per https://github.com/ansible-collections/community.general/blob/9c648c8e3acedf0881c9fbeb08b353230457c945/plugins/connection/lxd.py#L64 requires the lxc binary (https://github.com/ansible/awx/issues/9184). I hoped that installing the lxc package would do, but after building lxc from source I found out, that only lxc-something gets compiled - it seems that `lxc` might be a binary belonging to the lxd package. Since awx is installed as docker images, I won't have systemd running. Without systemd, snapd won't work hence no lxc binary. 

Is the lxc only part of lxd? Why? Any suggestions how to work around / build just lxc?

**Comment by stgraber** [comment]
Just build the `lxc` binary from this repo. `go get -v -x github.com/lxc/lxd/lxc`.

**Comment by stgraber** [comment]
You can also find static binaries for it (untested) from the `Actions` page in this repository.
