### ISSUE TITLE
LXD remote added by one user is not seen by other users

### ISSUE THREAD

**Issue by cquike** [lxc/lxd#8426]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-126-generic
   * LXC version: 3.0.3
   * LXD version: 3.0.3
   * Storage backend in use: lvm

# Issue description

An LXD server has several users which has permission to execute LXD commands since they all belong to the lxd group. If a user adds a remote with "lxd remote add" the other users cannot see the new configured remote.

 This doesn't work with my current Ubuntu 18.04 which is 3.0.3. I have tried with the demo server at https://linuxcontainers.org/lxd/try-it/ and the results are the same.

 I am not sure whether this is a bug or a feature. Per-user remote configuration looks interesting, but certain is that it is currently not possible to add a remote in a system wide fashion, so that different operators can see the same configuration. There should be at least an option to add the remote to the global configuration.

# Steps to reproduce

 1. Add  two users to the lxd group which have permission to execute LXD commands
 2. As user1: "lxc remote add image_again https://images.linuxcontainers.org"
 3. As user1: "lxc remote list". The new image_again remote is shown
 3. As user2: "lxc remote list". The new image_again added by the user is not shown

**Comment by stgraber** [comment]
Remotes are a client side concept.

**Comment by stgraber** [comment]
We have another existing issue tracking a way to have system wide configuration for the client.

**Comment by cquike** [comment]
Hi,
thank you for the prompt answer.
In this case the LXD client is the same and indeed the rest of the LXD configuration is the same, only that this LXD is managed by different operators. 

Could you point to the issue with the system wide configuration?

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/issues/7322
