### ISSUE TITLE
LV-backed container that failed to completely start leaves mounted LV hanging

### ISSUE THREAD

**Issue by mikemccracken** [lxc/lxd#844]
If a container fails to start after it has mounted its LV, the LV will remain mounted, which will break delete.

Error handling code in container creation should have a hook to allow storage backends to deactivate storage.

**Comment by mikemccracken** [comment]
I'm planning to work on this this week sometime.

**Comment by pcdummy** [comment]
This will be fixed in the upcoming containers branch.
