### ISSUE TITLE
API Error Messages Suggestion

### ISSUE THREAD

**Issue by jamielsharief** [lxc/lxd#8455]
Currently the error messages in the API are hard to use in other software unless you just throw out the exact error response that comes back.

For example

```
Error occurred when starting proxy device: Error: Failed to receive fd from listener process
```
and
```
Error occurred when starting proxy device: Error: Failed to listen on 0.0.0.0:80: listen tcp 0.0.0.0:80: bind: address already in us
```

In order to use this API and give better responses to users, i would have to attempt to parse the error message string to find out what is going on.

I am wondering if the API can return a category error, and then a system error message if available, e.g `ZFS cannot destroy data set because its busy`, to make the API more friendly.

```
 {
    "type": "sync",
    "status": "Success",
    "status_code": 200,
    "operation": "",
    "error_code": 0,
    "error": "",
    "metadata": {
        "id": "4400cf9c-06a6-4202-8d07-b227540dc76a",
        "class": "task",
        "description": "Starting instance",
        "created_at": "2021-02-12T15:08:51.542477114Z",
        "updated_at": "2021-02-12T15:08:51.542477114Z",
        "status": "Failure",
        "status_code": 400,
        "resources": {
            "instances": [
                "/1.0/instances/ubuntu-apache"
            ]
        },
        "metadata": null,
        "may_cancel": false,
        "err": "Error occurred when starting proxy device: Error: Failed to listen on 0.0.0.0:80: listen tcp 0.0.0.0:80: bind: address already in use",
        "reason": "proxy-device-start-error",
        "message": "Failed to listen on 0.0.0.0:80: listen tcp 0.0.0.0:80: bind: address already in use"
        "location": "none"
    }
} 
```

**Comment by stgraber** [comment]
Initially marked as `Maybe` but unfortunately the answer really is a no in this case...

Most LXD functions just return a Go `error` which doesn't let you split the message and indicate categories like you'd want here.
This then gets turned into an ErrorResponse in the API handler.

So we could add context to tell you what API endpoint returned the error, but not much else.
In your example above, all we could tell you is `/1.0/instances/NAME/state` was the thing which failed, but you already know that based on the operation description.

What we do to make things easier to debug is extend the error struct every time it passes through as function, that's what caused `Error occurred when starting proxy device` to be prepended in this case, but that's just a string prefix, not something we can really turn into anything more structured.
