### ISSUE TITLE
lxd init says invalid input for fan underlay

### ISSUE THREAD

**Issue by cjohnston1158** [lxc/lxd#8456]
# Required information

 * Distribution: Ubutun
 * Distribution version: 20.04 
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-65-generic
   * LXC version: 4.0.3?
   * LXD version: 4.0.2
   * Storage backend in use: dir

# Issue description

When trying to initialize lxd on a new VM with a Fan overlay network, the question What subnet should be used as the Fan underlay? [default=auto] complains about invalid input if left default.

# Steps to reproduce
/snap/bin/lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: yes
What name should be used to identify this node in the cluster? [default=lxdk8s-01]: 
What IP address or DNS name should be used to reach this node? [default=10.10.22.164]: 
Are you joining an existing cluster? (yes/no) [default=no]: 
Setup password authentication on the cluster? (yes/no) [default=yes]: 
Trust password for new clients: 
Again: 
Do you want to configure a new local storage pool? (yes/no) [default=yes]: 
Name of the storage backend to use (dir, lvm, btrfs) [default=btrfs]: dir
Do you want to configure a new remote storage pool? (yes/no) [default=no]:  
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to configure LXD to use an existing bridge or host interface? (yes/no) [default=no]: 
Would you like to create a new Fan overlay network? (yes/no) [default=yes]:   
What subnet should be used as the Fan underlay? [default=auto]: 
Invalid input: The underlay subnet must be a /16 or a /24

What subnet should be used as the Fan underlay? [default=auto]:

**Comment by stgraber** [comment]
Yeah, that suggests that your underlay network isn't a /16 or /24 and so you'll need to manually configure it.

**Comment by stgraber** [comment]
This happens in environment where your default interface is on an unusual subnet size. There's nothing we can really do to figure out the right value, so it's up to you to specify it.
