### ISSUE TITLE
Enhancement: Backup and restore configurations

### ISSUE THREAD

**Issue by jetojedno** [lxc/lxd#8460]
# Required information
All distributions & backends.

# Issue description

The aim is to backup the LXD setup so it can be restored on a fresh build, without any storage contents.

First step would be documentation on how to do this - what to backup and how to restore (e.g. lxd did / guid changes).

This is related to Issue [#5782](https://github.com/lxc/lxd/issues/5782) 

# Steps to reproduce

 1. Backup LXD configuration
 2. Clean install of (new release of) OS
 3. Install LXD
 3. Restore LXD config from backup
 4. LXD is as it was ...

# Information to attach
LXD uid / guid may change between installs
? what else is likely to change

**Comment by stgraber** [comment]
https://linuxcontainers.org/lxd/docs/master/backup#full-backup covers most of it, though it didn't mention subuid/subgid for the cases where this matters (doesn't for snaps).

I'm sending a PR which adds a mention of those two files.
