### ISSUE TITLE
enhancement: move delete -i confirmation request after error checking

### ISSUE THREAD

**Issue by jetojedno** [lxc/lxd#8466]
# Required information

 * Distribution: openSUSE
 * Distribution version: Leap 15.2
 * lxd --version
4.10

# Issue description

The `lxc delete -i <some_name>` command requests confirmation before any error checking, so `lxc delete -i I_DONT_EXIST` prompts for confirmation, as well as many other "normal" errors, such as trying to delete a running container.

# Steps to reproduce

 1. lxc delete -i I_DONT_EXIST
 - confirmation
 - error

or

 1. lxc launch images:ubuntu/bionic fred
 2. lxc delete fred
 - confirmation
 - error 

both of these should error before asking for confirmation.

**Comment by stgraber** [comment]
That's not possible, we can't show you a server-side error coming from the requested deletion operation before we send that deletion operation through. All the checks are done on the server side as part of the delete operation, the confirmation prompt is done in the client ahead of that.
