### ISSUE TITLE
enhancement: facility within container to pause (similar to hibernate)

### ISSUE THREAD

**Issue by jetojedno** [lxc/lxd#8474]
This will add the ability for a container to "pause" itself.

A container can be stopped from the inside by running `systemctl shutdown` (or equivalent).

It would be useful for a container to be able to run `systemctl hibernate` (or equivalent) to pause its operation.

**Comment by stgraber** [comment]
You won't be able to do that from within the container as those commands directly interact with the kernel.
But from outside the container, LXD also supports it:
 - lxc pause NAME => freezes all processes until you `lxc start` it back. Memory remains used though.
 - lxc stop NAME --stateful => saves all running state to disk, all memory is released, very rarely works though (depends on ability for CRIU to serialize kernel state of everything in the container).

Closing as LXD already supports this, it just can't be container initiated.
