### ISSUE TITLE
Move/migrate instances within cluster in projects other than default

### ISSUE THREAD

**Issue by matthewalanpenning** [lxc/lxd#8484]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info":
config:
  cluster.https_address: 10.180.188.164:8443
  core.https_address: 10.180.188.164:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.180.188.164:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIB+DCCAX6gAwIBAgIRAO+xFKN1B14A/xFLwIwCSHgwCgYIKoZIzj0EAwMwMDEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEQMA4GA1UEAwwHcm9vdEBjMTAe
    Fw0yMTAyMDkxNDAxMzBaFw0zMTAyMDcxNDAxMzBaMDAxHDAaBgNVBAoTE2xpbnV4
    Y29udGFpbmVycy5vcmcxEDAOBgNVBAMMB3Jvb3RAYzEwdjAQBgcqhkjOPQIBBgUr
    gQQAIgNiAAQShcqiJYd/BaCb/fS0pC5rQ9k/WmeX0jzdJdoldC6XOglEZoqUFyMK
    /S8gof3kIkbQItUIFDpmflYtXiP574qPcETiXZ0Bs8R60AhQxv5IuU8XMiCcE27m
    p6enXyUAwcajXDBaMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcD
    ATAMBgNVHRMBAf8EAjAAMCUGA1UdEQQeMByCAmMxhwR/AAABhxAAAAAAAAAAAAAA
    AAAAAAABMAoGCCqGSM49BAMDA2gAMGUCMA7h0ydd9H4AX3gIantzJjwCp9c5VOFc
    ghQg9LVhVjI2HtIdrnxZYsrg+MyTAC4QWgIxAJjC9RRqRbWcVGUzMSWNHo8SsQWY
    UcIGDzjxHOWfJdLW0pMxQoKti1/Ib/3El+9QOw==
    -----END CERTIFICATE-----
  certificate_fingerprint: b66b21986f9f7be457278b7c44439d5aeb4ca6ab4637d9d4b4e309217013d207
  driver: qemu | lxc
  driver_version: 5.2.0 | 4.0.6
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-1032-kvm
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: true
  server_name: c1
  server_pid: 709
  server_version: "4.11"
  storage: zfs
  storage_version: 0.8.3-1ubuntu12.5

# Issue description
I have three Ubuntu 20.04 LXD servers in a cluster (c1, c2, c3), using the snap lxd 4.11 version from latest/stable channel and zfs for storage pool. When using the move command with --target the instance migrates between the cluster members just fine, but if the instance is in a project other than default I am getting a "Failed to get instance info: not found" error. 

# Steps to reproduce
lxc project create test
lxc profile device add default root disk path=/ pool=local --project test
lxc init images:ubuntu/20.04 instance1 --project test
lxc move instance1 --target c2 --project test

# Information to attach (debug message)
lxc move instance1 --target c2 --project test --debug

DBUG[02-18|18:02:21] Connecting to a local LXD over a Unix socket 
DBUG[02-18|18:02:21] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
DBUG[02-18|18:02:21] Got response struct from LXD 
DBUG[02-18|18:02:21] 
	{
		"config": {
			"cluster.https_address": "10.180.188.164:8443",
			"core.https_address": "10.180.188.164:8443",
			"core.trust_password": true
		},
		"api_extensions": [
			"storage_zfs_remove_snapshots",
			"container_host_shutdown_timeout",
			"container_stop_priority",
			"container_syscall_filtering",
			"auth_pki",
			"container_last_used_at",
			"etag",
			"patch",
			"usb_devices",
			"https_allowed_credentials",
			"image_compression_algorithm",
			"directory_manipulation",
			"container_cpu_time",
			"storage_zfs_use_refquota",
			"storage_lvm_mount_options",
			"network",
			"profile_usedby",
			"container_push",
			"container_exec_recording",
			"certificate_update",
			"container_exec_signal_handling",
			"gpu_devices",
			"container_image_properties",
			"migration_progress",
			"id_map",
			"network_firewall_filtering",
			"network_routes",
			"storage",
			"file_delete",
			"file_append",
			"network_dhcp_expiry",
			"storage_lvm_vg_rename",
			"storage_lvm_thinpool_rename",
			"network_vlan",
			"image_create_aliases",
			"container_stateless_copy",
			"container_only_migration",
			"storage_zfs_clone_copy",
			"unix_device_rename",
			"storage_lvm_use_thinpool",
			"storage_rsync_bwlimit",
			"network_vxlan_interface",
			"storage_btrfs_mount_options",
			"entity_description",
			"image_force_refresh",
			"storage_lvm_lv_resizing",
			"id_map_base",
			"file_symlinks",
			"container_push_target",
			"network_vlan_physical",
			"storage_images_delete",
			"container_edit_metadata",
			"container_snapshot_stateful_migration",
			"storage_driver_ceph",
			"storage_ceph_user_name",
			"resource_limits",
			"storage_volatile_initial_source",
			"storage_ceph_force_osd_reuse",
			"storage_block_filesystem_btrfs",
			"resources",
			"kernel_limits",
			"storage_api_volume_rename",
			"macaroon_authentication",
			"network_sriov",
			"console",
			"restrict_devlxd",
			"migration_pre_copy",
			"infiniband",
			"maas_network",
			"devlxd_events",
			"proxy",
			"network_dhcp_gateway",
			"file_get_symlink",
			"network_leases",
			"unix_device_hotplug",
			"storage_api_local_volume_handling",
			"operation_description",
			"clustering",
			"event_lifecycle",
			"storage_api_remote_volume_handling",
			"nvidia_runtime",
			"container_mount_propagation",
			"container_backup",
			"devlxd_images",
			"container_local_cross_pool_handling",
			"proxy_unix",
			"proxy_udp",
			"clustering_join",
			"proxy_tcp_udp_multi_port_handling",
			"network_state",
			"proxy_unix_dac_properties",
			"container_protection_delete",
			"unix_priv_drop",
			"pprof_http",
			"proxy_haproxy_protocol",
			"network_hwaddr",
			"proxy_nat",
			"network_nat_order",
			"container_full",
			"candid_authentication",
			"backup_compression",
			"candid_config",
			"nvidia_runtime_config",
			"storage_api_volume_snapshots",
			"storage_unmapped",
			"projects",
			"candid_config_key",
			"network_vxlan_ttl",
			"container_incremental_copy",
			"usb_optional_vendorid",
			"snapshot_scheduling",
			"container_copy_project",
			"clustering_server_address",
			"clustering_image_replication",
			"container_protection_shift",
			"snapshot_expiry",
			"container_backup_override_pool",
			"snapshot_expiry_creation",
			"network_leases_location",
			"resources_cpu_socket",
			"resources_gpu",
			"resources_numa",
			"kernel_features",
			"id_map_current",
			"event_location",
			"storage_api_remote_volume_snapshots",
			"network_nat_address",
			"container_nic_routes",
			"rbac",
			"cluster_internal_copy",
			"seccomp_notify",
			"lxc_features",
			"container_nic_ipvlan",
			"network_vlan_sriov",
			"storage_cephfs",
			"container_nic_ipfilter",
			"resources_v2",
			"container_exec_user_group_cwd",
			"container_syscall_intercept",
			"container_disk_shift",
			"storage_shifted",
			"resources_infiniband",
			"daemon_storage",
			"instances",
			"image_types",
			"resources_disk_sata",
			"clustering_roles",
			"images_expiry",
			"resources_network_firmware",
			"backup_compression_algorithm",
			"ceph_data_pool_name",
			"container_syscall_intercept_mount",
			"compression_squashfs",
			"container_raw_mount",
			"container_nic_routed",
			"container_syscall_intercept_mount_fuse",
			"container_disk_ceph",
			"virtual-machines",
			"image_profiles",
			"clustering_architecture",
			"resources_disk_id",
			"storage_lvm_stripes",
			"vm_boot_priority",
			"unix_hotplug_devices",
			"api_filtering",
			"instance_nic_network",
			"clustering_sizing",
			"firewall_driver",
			"projects_limits",
			"container_syscall_intercept_hugetlbfs",
			"limits_hugepages",
			"container_nic_routed_gateway",
			"projects_restrictions",
			"custom_volume_snapshot_expiry",
			"volume_snapshot_scheduling",
			"trust_ca_certificates",
			"snapshot_disk_usage",
			"clustering_edit_roles",
			"container_nic_routed_host_address",
			"container_nic_ipvlan_gateway",
			"resources_usb_pci",
			"resources_cpu_threads_numa",
			"resources_cpu_core_die",
			"api_os",
			"container_nic_routed_host_table",
			"container_nic_ipvlan_host_table",
			"container_nic_ipvlan_mode",
			"resources_system",
			"images_push_relay",
			"network_dns_search",
			"container_nic_routed_limits",
			"instance_nic_bridged_vlan",
			"network_state_bond_bridge",
			"usedby_consistency",
			"custom_block_volumes",
			"clustering_failure_domains",
			"resources_gpu_mdev",
			"console_vga_type",
			"projects_limits_disk",
			"network_type_macvlan",
			"network_type_sriov",
			"container_syscall_intercept_bpf_devices",
			"network_type_ovn",
			"projects_networks",
			"projects_networks_restricted_uplinks",
			"custom_volume_backup",
			"backup_override_name",
			"storage_rsync_compression",
			"network_type_physical",
			"network_ovn_external_subnets",
			"network_ovn_nat",
			"network_ovn_external_routes_remove",
			"tpm_device_type",
			"storage_zfs_clone_copy_rebase",
			"gpu_mdev",
			"resources_pci_iommu",
			"resources_network_usb",
			"resources_disk_address",
			"network_physical_ovn_ingress_mode",
			"network_ovn_dhcp",
			"network_physical_routes_anycast",
			"projects_limits_instances",
			"network_state_vlan",
			"instance_nic_bridged_port_isolation",
			"instance_bulk_state_change",
			"network_gvrp",
			"instance_pool_move",
			"gpu_sriov",
			"pci_device_type",
			"storage_volume_state"
		],
		"api_status": "stable",
		"api_version": "1.0",
		"auth": "trusted",
		"public": false,
		"auth_methods": [
			"tls"
		],
		"environment": {
			"addresses": [
				"10.180.188.164:8443"
			],
			"architectures": [
				"x86_64",
				"i686"
			],
			"certificate": "-----BEGIN CERTIFICATE-----\nMIIB+DCCAX6gAwIBAgIRAO+xFKN1B14A/xFLwIwCSHgwCgYIKoZIzj0EAwMwMDEc\nMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEQMA4GA1UEAwwHcm9vdEBjMTAe\nFw0yMTAyMDkxNDAxMzBaFw0zMTAyMDcxNDAxMzBaMDAxHDAaBgNVBAoTE2xpbnV4\nY29udGFpbmVycy5vcmcxEDAOBgNVBAMMB3Jvb3RAYzEwdjAQBgcqhkjOPQIBBgUr\ngQQAIgNiAAQShcqiJYd/BaCb/fS0pC5rQ9k/WmeX0jzdJdoldC6XOglEZoqUFyMK\n/S8gof3kIkbQItUIFDpmflYtXiP574qPcETiXZ0Bs8R60AhQxv5IuU8XMiCcE27m\np6enXyUAwcajXDBaMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcD\nATAMBgNVHRMBAf8EAjAAMCUGA1UdEQQeMByCAmMxhwR/AAABhxAAAAAAAAAAAAAA\nAAAAAAABMAoGCCqGSM49BAMDA2gAMGUCMA7h0ydd9H4AX3gIantzJjwCp9c5VOFc\nghQg9LVhVjI2HtIdrnxZYsrg+MyTAC4QWgIxAJjC9RRqRbWcVGUzMSWNHo8SsQWY\nUcIGDzjxHOWfJdLW0pMxQoKti1/Ib/3El+9QOw==\n-----END CERTIFICATE-----\n",
			"certificate_fingerprint": "b66b21986f9f7be457278b7c44439d5aeb4ca6ab4637d9d4b4e309217013d207",
			"driver": "qemu | lxc",
			"driver_version": "5.2.0 | 4.0.6",
			"firewall": "nftables",
			"kernel": "Linux",
			"kernel_architecture": "x86_64",
			"kernel_features": {
				"netnsid_getifaddrs": "true",
				"seccomp_listener": "true",
				"seccomp_listener_continue": "true",
				"shiftfs": "false",
				"uevent_injection": "true",
				"unpriv_fscaps": "true"
			},
			"kernel_version": "5.4.0-1032-kvm",
			"lxc_features": {
				"cgroup2": "true",
				"devpts_fd": "true",
				"mount_injection_file": "true",
				"network_gateway_device_route": "true",
				"network_ipvlan": "true",
				"network_l2proxy": "true",
				"network_phys_macvlan_mtu": "true",
				"network_veth_router": "true",
				"pidfd": "true",
				"seccomp_allow_deny_syntax": "true",
				"seccomp_notify": "true",
				"seccomp_proxy_send_notify_fd": "true"
			},
			"os_name": "Ubuntu",
			"os_version": "20.04",
			"project": "default",
			"server": "lxd",
			"server_clustered": true,
			"server_name": "c1",
			"server_pid": 709,
			"server_version": "4.11",
			"storage": "zfs",
			"storage_version": "0.8.3-1ubuntu12.5"
		}
	} 
DBUG[02-18|18:02:21] Connected to the websocket: ws://unix.socket/1.0/events?project=test&target=c2 
DBUG[02-18|18:02:21] Sending request to LXD                   method=POST url="http://unix.socket/1.0/instances/instance1?project=test&target=c2" etag=
DBUG[02-18|18:02:21] 
	{
		"name": "instance1",
		"migration": true,
		"live": false,
		"instance_only": false,
		"container_only": false,
		"target": null,
		"pool": ""
	} 
DBUG[02-18|18:02:21] Got operation from LXD 
DBUG[02-18|18:02:21] 
	{
		"id": "30d7c86f-bab9-49c5-84e8-402f77984b05",
		"class": "task",
		"description": "Migrating instance",
		"created_at": "2021-02-18T18:02:21.262691584Z",
		"updated_at": "2021-02-18T18:02:21.262691584Z",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/instance1"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": "",
		"location": "c1"
	} 
DBUG[02-18|18:02:21] Sending request to LXD                   method=GET url="http://unix.socket/1.0/operations/30d7c86f-bab9-49c5-84e8-402f77984b05?project=test&target=c2" etag=
DBUG[02-18|18:02:21] Got response struct from LXD 
DBUG[02-18|18:02:21] 
	{
		"id": "30d7c86f-bab9-49c5-84e8-402f77984b05",
		"class": "task",
		"description": "Migrating instance",
		"created_at": "2021-02-18T18:02:21.262691584Z",
		"updated_at": "2021-02-18T18:02:21.262691584Z",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/instance1"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": "",
		"location": "c1"
	} 
Error: Migration operation failure: Failed to get instance info: not found

**Comment by stgraber** [comment]
Should be a pretty straightforward bug, chances are we missed a `.UseTarget()` somewhere when calling the source server.

**Comment by tomponline** [comment]
@stgraber I'll take a look tomorrow if ok.

**Comment by tomponline** [comment]
Have reproduced the issue

**Comment by tomponline** [comment]
@matthewalanpenning thanks for the reproducer, have sent a PR that fixes it.

**Comment by matthewalanpenning** [comment]
@tomponline great work!
