### ISSUE TITLE
LXC upgrade attempt gets stuck at "Connecting to source server" - connecting forever

### ISSUE THREAD

**Issue by olokos** [lxc/lxd#8506]
# Required information

 * Distribution:  Ubuntu 
 * Distribution version: 18.04 to 20.04 update
 * The output of "lxc info":
[Link to pastebin](https://pastebin.com/kTjqkdSA)
# Issue description

I'm updating ubuntu 18.04 LTS to 20.04 LTS and lxc is attempting to upgrade from deb to snap, but it gets into infinite loop of connecting to source server, which never ends.

# Steps to reproduce

 1. Use ubuntu 18.04 LTS with all latest packages, latest kernel
 2. Use `sudo do-release-upgrade` 
 3. After a very long get stuck at lxc Connecting to source server
 4. Do `sudo reboot`
 5. Do `sudo dkpkg --configure -a`
 6. Do sudo apt --fix-broken install`
 7. End up in lxc attempting to upgrade from deb to snap "Connecting to source server" which would last forever

# Information to attach

 - [5.10.15-051015-generic] Kernel version
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 I'm not using any containers within lxc, so i cannot provide above 2 info
- [https://pastebin.com/KLi4rf1a] Main daemon log (at /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
I'm not entirely sure how to provide the last two info

Any ideas? I've been trying to update since around a year now, but this has always been stopping everything.

**Comment by olokos** [comment]
![Screenshot of the moment at which point it's stuck](https://image.prntscr.com/image/u2hioTUYQkSNB6AZCalZ_Q.png)

**Comment by stgraber** [comment]
What does `journalctl -u lxd -n 300` show you?

**Comment by olokos** [comment]
@stgraber 

It says this:
[Link](https://pastebin.com/6aPRhZtT)

I'm currently in the state as in the screenshot, using another SSH session to enter new commands.

Noticing the error I've done `sudo mkdir /var/log/lxd/` but it didn't seem to progress the `Connecting to source server` situation.
It's been like this since yesterday :D

**Comment by olokos** [comment]
Okay, seeems like it did progress after 10 minutes of me creating that directory!
![image](https://user-images.githubusercontent.com/1755581/109423375-6a1ebf80-79df-11eb-8fd0-6702e20673be.png)

**Comment by stgraber** [comment]
Closing this as the /var/log/lxd path isn't created by LXD but instead handled by distro specific packaging. So there is no change to this repository which can prevent this from happening.

**Comment by olokos** [comment]
Good job! I'm not that familiar with lxc/lxd so that's why I started the issue here.
