### ISSUE TITLE
Project list csv adds "(current)"

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#8508]
Compared with `json` & `yaml`, `lxc project list --format csv` will output the project name with `(current)` attached I.E

```
default (current),YES,YES,YES,YES,56
```

If you wanted to get a list of project names using a command like the following it would fail without extra code

`lxc project list --format csv | cut -d, -f1`

**Comment by stgraber** [comment]
Yeah, we have the same behavior in `lxc remote list`. I noticed it before but I'm not sure that we can really do anything about it.
Basically the output formats which use structs are fed the raw data (yaml/json) whereas table and csv use processed data from the client, in this case, adding in what the current project is.

Removing it wouldn't be too hard but this would break anyone who's currently assuming that CSV does give them the same output as the list view, just in CSV format.

In this case, I think your two options are:
 - `lxc project list --format csv | cut -d, -f1 | cut -d' ' -f1`
 - `lxc project list --format json | jq -r .[].name`

**Comment by turtle0x1** [comment]
`lxc project list --format csv | cut -d, -f1 | cut -d' ' -f1` would do it, thanks :smile:
