### ISSUE TITLE
lxc init/launch with multiple profiles fails

### ISSUE THREAD

**Issue by pcdummy** [lxc/lxd#851]
Think these outputs says everything, i'm running the latest master lxd and lxc on all machines.

**Init:**

    # lxc init ubuntu/trusty/amd64 mongo1 -p default,privileged
    error: NOT NULL constraint failed: containers_profiles.profile_id

**Launch:**

    # lxc launch ubuntu/trusty/amd64 mongo1 -p default,privileged
    Creating container...error: NOT NULL constraint failed: containers_profiles.profile_id

**Profile default:**

    # lxc profile show default
    name: default
    config: {}
    devices:
      eth0:
        nictype: bridged
        parent: p4mbrext
        type: nic
      eth1:
        nictype: bridged
        parent: p4mbrint
        type: nic

**Profile privileged:**

    # lxc profile show privileged
    name: privileged
    config:
      security.privileged: "true"
    devices: {}

**Comment by pcdummy** [comment]
I'll try to fix that.

**Comment by pcdummy** [comment]
May fault, have been using the commands from issue #745 

The correct **init** cmd is:

    lxc init ubuntu/trusty/amd64 test123 -p default -p privileged

As you see not with a comma but with two **-p**

**Comment by stgraber** [comment]
Oops, the error message should probably be improved a bit at least :)
