### ISSUE TITLE
Bug: lxc copy isn't using IPv6 first and leaves a half container on the target

### ISSUE THREAD

**Issue by pcdummy** [lxc/lxd#854]
I tried to move a container i made to production but it fails as i don't have IPv4 routes to it.
Normaly everything uses IPv6 first but not in this case.
    
    $ lxc copy srv01:mongoexpress containers.chost.lan:
    error: dial tcp 10.167.160.14:8443: connection refused

Also this command leaves a container on the target which only exists in the DB and theres **no chance** to remove it with *lxc delete containers.chost.lan:monogexpress*

**Comment by pcdummy** [comment]
This bug is very hard to debug as i don't know what wants to dial.

**Comment by stgraber** [comment]
So in this case, containers.chost.lan will be connecting to srv01 directly, I suspect that's where we have a non-ipv6 aware dial...

**Comment by pcdummy** [comment]
Your right its the IP of srv01, where does containers.chost.lan get it from?

**Comment by stgraber** [comment]
Can you try http://paste.ubuntu.com/11883189/ ?

**Comment by pcdummy** [comment]
Looks better but now i get:

    $ lxc copy srv01:mongoexpress containers.chost.lan:
    error: checkpoint failed

**Comment by stgraber** [comment]
Is it a running container?

**Comment by pcdummy** [comment]
It was, yes. Stopping it first works!

Still that "checkpoint" error message isn't very helpfull and it leaves a container you cannot delete.
Maybe force delete a container without a rootfs on "lxc delete" ?

**Comment by pcdummy** [comment]
Hmm this way it doesn't create a btrfs subvolume on the receiver site, want to do this with btrfs send/receive or just create one and rsync into it?

**Comment by stgraber** [comment]
Well, there must be a bug in the create from migration code, that's certainly supposed to destroy the container on failure...

As for container transfer, if both sides are btrfs, it'd be nice to use send/receive, though for now just creating the subvolume and rsyncing would be fine I guess.
