### ISSUE TITLE
Ceph RBD map denied in container

### ISSUE THREAD

**Issue by borgez** [lxc/lxd#8540]
I have same problem like #2709, when i provision device from rook in k8s it say ok and no error.
On hypervisor side /dev/rbdX created but in container not.

Any way to auto mount it to right container?

**Comment by stgraber** [comment]
Nope, /dev isn't really namespaced so containers can't have their own version of `devtmpfs` where device nodes show up automatically (which `rbd map` relies on).

Your best way around this would be to setup custom udev hooks on the host to react to those rbd devices showing up and then automatically passing them into the container but that's pretty custom and will possibly still fail if `rbd` or any other tool in the container expect to receive the kernel uevent too.

(Closing as this is a kernel limitation)
