### ISSUE TITLE
Importing Existing BTRFS Storage Pool [Block Storage] after Server Rebuild

### ISSUE THREAD

**Issue by eelbrink** [lxc/lxd#8556]
# Required information

 * Distribution: **Debian** 
 * Distribution version: **10**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.19.0-14-amd64**
   * LXC version: **4.12**
   * LXD version: **4.12**
   * Storage backend in use: **BTRFS**

# Issue description

Hi, I did a rebuild of the server I was using to run LXD containers on. The LXD storage pool is a BTRFS pool from block storage, which is essentially just an LVM volume with a BTRFS filesystem on it. I rebuild the root filesystem and want to use the existing LXD storage pool still available. 

The storage pool name: **containers**
The storage pool logical volume location: **/services/lxd**

How do use an existing BTRFS storage pool which is a logical volume or block device? 

Your assistance would be greatly appreciated. 

Kind Regards
E.

**Comment by stgraber** [comment]
Please ask support questions at https://discuss.linuxcontainers.org
