### ISSUE TITLE
doc: Add a Table of Content to README

### ISSUE THREAD

**Issue by toby63** [lxc/lxd#8559]
The Readme.md is quite long, so I think a TOC could help users to find information easier and faster.

I can make it, but I would like to hear your oppinion first :slightly_smiling_face:.

@stgraber

**Comment by stgraber** [comment]
Certainly worth a try, probably don't want it right at the top but a bit further down and we'll want to make sure that the anchors work on both Github and the doc site.

**Comment by toby63** [comment]
Ok.

> and we'll want to make sure that the anchors work on both Github and the doc site.

A Problem there is, that the documentation site already has a TOC :thinking:.
OT: It's a bit buggy though, for example on the [instances page](https://linuxcontainers.org/lxd/docs/master/instances) some links don't work.

What do you think of adding a seperate page for the documentation instead?
I think it would be good to have a bit more description and introduction to the documentation in it anyway.

**Comment by stgraber** [comment]
I don't think having it show up both on the side and in-line will be a big problem for now.
Maybe we eventually want a different page but we already have a hard time keeping the README up to date, so I'm not super keen on adding more ;)
