### ISSUE TITLE
REST API file push doesn't upload file properly

### ISSUE THREAD

**Issue by reversecipher** [lxc/lxd#856]
File push returns success and file gets created on container, but is empty.

```
$ cat test
This is a test

$ curl -s -k -X POST -H "X-LXD-uid: 0" -H "X-LXD-gid: 0" -H "X-LXD-mode: 0700" -d "@test" --cert client.crt --key client.key https://192.168.10.155:8443/1.0/containers/test/files?path=/tmp/test

2015/07/15 23:09:46 handling POST /1.0/containers/test/files?path=/tmp/test
2015/07/15 23:09:46 
	{
		"type": "sync",
		"status": "Success",
		"status_code": 200,
		"metadata": {}
	}

# lxc exec test -- ls -la /tmp/test
-rwx------ 1 root root 0 Jul 15 20:09 /tmp/test

# lxc exec test -- cat /tmp/test
#
```

**Comment by stgraber** [comment]
Hi,

Oddly, this isn't a bug. curl by default sets the Content-Type to application/x-www-form or some such, which makes the LXD web server attempt to parse the data into a key/value map.
In most cases it succeeds and so the raw body is actually empty, leading to the empty file.

To fix the issue, simply pass -H "Content-Type: application/octet-stream" and things will work just fine.

**Comment by stgraber** [comment]
Actually, it may be a curl bug that when you pass a data blob which obviously isn't an http form that it still pretends it's a form rather than say it's a blob (which application/octet-stream says).

**Comment by reversecipher** [comment]
Ok, thanks. Had the problem both with curl and python-requests, but setting the content-type resolved it.
