### ISSUE TITLE
Issues growing ext4 partitions

### ISSUE THREAD

**Issue by maran** [lxc/lxd#8569]
# Required information

 * Distribution: Ubuntu 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-66-generic
   * LXC version: driver_version: 4.0.6 | 5.2.0
   * LXD version: 4.12
   * Storage backend in use: ceph version 15.2.1

# Issue description

It appears that sometimes growing (RBD) ext4 filesystems does not work, correctly. 

# Steps to reproduce

 1. Update LXC config to increase size from X to Y. 
 2. The underlying RBD will be correctly grown. 
 3. The filesystem does not always grow correctly.

From my own tests when manually growing the filesystem using `resize2fs` it always gives me the message to run a `fsck` first. I checked the LXD code and it does not appear to be doing any filesystem checks before growing (only shrinking), should this be added, and could this explain the issue?

It would also be nice to get a bit more debug messages when it's growing as I don't think any log statements show up currently.

The weird thing though is that is not constantly happening sometimes it does resize, although not enough to fill the full partition, not sure this is related though. For instance.

LXC config is correct.
```
  root:
    limits.max: 150iops
    path: /
    pool: ceph-erasure
    size: 750GB
```

Parted information on the host is correct.
```
parted /dev/rbd56 print
Model: Unknown (unknown)
Disk /dev/rbd56: 750GB
Sector size (logical/physical): 512B/512B
Partition Table: loop
Disk Flags: 

Number  Start  End    Size   File system  Flags
 1      0.00B  750GB  750GB  ext4
```

Inside the container however it appears 11GB of storage is missing.
```
:~# df -H
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd56      739G  653G   86G  89% /
```

**Comment by tomponline** [comment]
@maran so just to be clear, you're not getting any errors, its just that you don't think the filesystem is resized to the correct size?

Please could you also give an example of the output of parted and df when the resize does work, so we can see the difference?

**Comment by maran** [comment]
Sorry I was not super specific. There are no errors indeed. It just sometimes does not work.

There are two errors, I think the first one might be a LXD issue, the second one is probably more me not understanding how growing ext4 filesystems work exactly.

1. Sometimes the filesystem simply won't be grown, but the partition will be. This is I think related to not doing a filesystem check before the resize2fs.
2. Sometimes it does work but it won't grow it fully. This seems not to be related to LXD though since it won't even work when I manually resize it.

What I tried now with a volume that wouldn't resize ithe filesystem the following:

1. Stop container (just to rule out it would try a live resize)
2. Manually map the RBD device with `rbd map`
3. `fsck -f` the device
4. `rbd unmap` the device again
5. `lxc config edit` and grow the filesystem to 70GB.
6. Start the container. It was now successfully grown (although to 69GB and not the full 70GB)

Although this is just one instance it seems to imply that not running fsck might be the problem

T

**Comment by tomponline** [comment]
@maran please can you provide an example of what you run to resize the instance disk (without using manual rbd tools or fsck) and then showing the before and after output of commands you used to ascertain that the rbd device was resized but the filesystem was not. So a full reproducer that I can use to recreate the issue. Thanks

**Comment by maran** [comment]
Took me a bit of time to translate our layers on top of LXD to CLI commands but it seems that with a fresh container using the CLI only I could **not** replicated the issue. Which seems to imply there is something with the way we use the API that might be triggering this. If I can figure out a way to successfully replicated this via CLI only I will update this post.

**Comment by tomponline** [comment]
@maran ah interesting, thanks for digging into it further. Let us know how you get on.

**Comment by stgraber** [comment]
@maran did you figure out what's going on?

**Comment by maran** [comment]
Sadly no. I'm guessing it might have been a race condition in our own code somehow. I don't think it happened anymore in the last two months or so but I will ask around and make sure.

**Comment by stgraber** [comment]
Okay, tentatively closing for now but comment here if it happens again so we can reopen.
