### ISSUE TITLE
Unable to add second node in lxd cluster

### ISSUE THREAD

**Issue by Kumar6295** [lxc/lxd#8595]
Hi,
Created lxd master and working fine,Try to create slave in another machine.
**commands**
sudo zpool create  disk2_pool /dev/sdb
sudo zfs create disk2_pool/clusterData
While adding second node cluster,getting error..

lxd init

Would you like to use LXD clustering? (yes/no) [default=no]: yes
What name should be used to identify this node in the cluster? [default=ps]:
What IP address or DNS name should be used to reach this node? [default=slave_ip]:
Are you joining an existing cluster? (yes/no) [default=no]: yes
IP address or FQDN of an existing cluster node: master_ip
Cluster fingerprint: 4c67c80c1bb8d6fda4583927b088
You can validate this fingerprint by running "lxc info" locally on an existing node.
Is this the correct fingerprint? (yes/no) [default=no]: yes
Cluster trust password:
All existing data is lost when joining a cluster, continue? (yes/no) [default=no] yes
Choose "source" property for storage pool "local": disk2_pool/clusterData
Choose "zfs.pool_name" property for storage pool "local": disk2_pool
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]:
Error: Failed to join cluster: Failed to initialize member: Failed to initialize storage pools and networks: Failed to create storage pool 'local': The source must match zfs.pool_name if specified

**Comment by monstermunchkin** [comment]
> Error: Failed to join cluster: Failed to initialize member: Failed to initialize storage pools and networks: Failed to create storage pool 'local': The source must match zfs.pool_name if specified

You are using `disk2_pool/clusterData` as the source, and `disk2_pool` for `zfs.pool_name`. You need to use `disk2_pool` for both.

```
$ zpool list
NAME   SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
lxd    896M   524K   895M        -         -     0%     0%  1.00x    ONLINE  -

$ lxc storage create zfs zfs source=lxd zfs.pool_name=lxd
Storage pool zfs created
```

**Comment by Kumar6295** [comment]
Thank you so much,Now it is working
