### ISSUE TITLE
How to stop tmpfs consumption in container (LXD)

### ISSUE THREAD

**Issue by Kumar6295** [lxc/lxd#8596]
Hi,
Created multiple container, every container tmpfs is taking 79 GB and 16 GB etc..
Can we able stop/restrict consumption..
If we done it, is have any effects of containers??

Filesystem                    Size  Used Avail Use% Mounted on
disk/containers/test  2.9T  6.6G  2.9T   1% /
none                          492K  4.0K  488K   1% /dev
udev                           79G     0   79G   0% /dev/tty
tmpfs                         100K     0  100K   0% /dev/lxd
tmpfs                         100K     0  100K   0% /dev/.lxd-mounts
tmpfs                          79G     0   79G   0% /dev/shm
tmpfs                          16G  200K   16G   1% /run
tmpfs                          5.0M     0  5.0M   0% /run/lock
tmpfs                          79G     0   79G   0% /sys/fs/cgroup

**Comment by monstermunchkin** [comment]
I believe you're reading the output incorrectly. ` tmpfs 79G 0 79G 0% /dev/shm` means that 79G are still available, and ` tmpfs 16G 200K 16G 1% /run` means that 200K have been taken.

**Comment by monstermunchkin** [comment]
>  Can we able stop/restrict consumption..

Yes, that's possible. [Here](https://lxd.readthedocs.io/en/latest/instances/) you can see how to configure an instance. If you wanted to limit memory usage to 500MB, you could for example call `lxc config set <instance-name> limits.memory 500MB`.

**Comment by stgraber** [comment]
Indeed tmpfs consumption is governed by the general instance memory limit. The default tmpfs size will still defaut to 50% of the total system RAM or whatever the kernel picks, but the consumption will be limited by the instance memory limit.

It'd certainly be nicer if the kernel would consider the cgroup limit of the mounter process and do 50% of that, but interactions between cgroups and unrelated logic like that in the kernel is very rare and usually frowned upon.

(Closing as not a LXD bug, this is an odd kernel behavior but one that's ultimately correct as limits are respected)

**Comment by Kumar6295** [comment]
79 Gb is not consumed but in every container it is showing 79 GB that means every container taking 79 GB memory right? How to stop it ?

**Comment by Kumar6295** [comment]
Container data will store in disk/containers/test  ..Then why we need tmpfs??

**Comment by monstermunchkin** [comment]
> 79 Gb is not consumed but in every container it is showing 79 GB that means every container taking 79 GB memory right?

That's incorrect. Containers will take as much memory as they want/need from your system's available memory. Unlike VMs, containers share the resources.

Example:

Your system has 16 GB, and is using 6 GB for itself (Browser, etc.). That leaves you with 10 GB.
If you're running 2 containers, each of them will still see 16 GB, but they will only be able to use 10 GB at this time.

> How to stop it ?

That was already answered here. You can limit the memory per container.

> Container data will store in disk/containers/test ..Then why we need tmpfs??

Container data is persistent, tmpfs not. They are two different concepts.
