### ISSUE TITLE
After reboot server,Lxc is not working

### ISSUE THREAD

**Issue by Kumar6295** [lxc/lxd#8599]
hi,
After reboot server master node of lxc ,Lxc is not working. it is showing below error

**Error: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused**
while executing zfs  list command , it is giving result.

none of the lxc commands are not working,Every command giving above error only.

ps002,ps003(slave nodes) giving below details
 lxc cluster list
+-------+----------------------------+----------+---------+--------------------------------------+--------------+----------------+
| NAME  |            URL    | DATABASE |  STATE  |               MESSAGE                | ARCHITECTURE | FAILURE DOMAIN |
+-------+----------------------------+----------+---------+--------------------------------------+--------------+----------------+
| ps001 | https://ip-1:8443 | YES      | OFFLINE | no heartbeat for 21h48m46.532442827s | x86_64       | default        |
+-------+----------------------------+----------+---------+--------------------------------------+--------------+----------------+
| ps002 | https://ip-2:8443 | YES      | ONLINE  | fully operational                    | x86_64       | default        |
+-------+----------------------------+----------+---------+--------------------------------------+--------------+----------------+
| ps003 | https://ip-3:8443 | YES      | ONLINE  | fully operational                    | x86_64       | default        |
+-------+----------------------------+----------+---------+--------------------------------------+--------------+----------------+

ps001 is master node of lxc every container is created in maser.ps001 has no heartbeat.

ps002,ps003(slave nodes) giving below details
sudo lxc list
+-------------------------+-------+------+------+-----------+-----------+----------+
|          NAME           | STATE | IPV4 | IPV6 |   TYPE    | SNAPSHOTS | LOCATION |
+-------------------------+-------+------+------+-----------+-----------+----------+
| Test-Storage            | ERROR |      |      | CONTAINER | 0         | ps001    |

**Comment by Kumar6295** [comment]
Systemctl services was failed to restart but it is failling.

 sudo systemctl status  snap.lxd.daemon
● snap.lxd.daemon.service - Service for snap application lxd.daemon
     Loaded: loaded (/etc/systemd/system/snap.lxd.daemon.service; static; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-03-24 11:20:44 IST; 11min ago
TriggeredBy: ● snap.lxd.daemon.unix.socket
    Process: 6916 ExecStart=/usr/bin/snap run lxd.daemon (code=exited, status=1/FAILURE)
   Main PID: 6916 (code=exited, status=1/FAILURE)

Mar 24 11:20:44 ps001 systemd[1]: snap.lxd.daemon.service: Scheduled restart job, restart counter is at 5.
Mar 24 11:20:44 ps001 systemd[1]: Stopped Service for snap application lxd.daemon.
Mar 24 11:20:44 ps001 systemd[1]: snap.lxd.daemon.service: Start request repeated too quickly.
Mar 24 11:20:44 ps001 systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
Mar 24 11:20:44 ps001 systemd[1]: Failed to start Service for snap application lxd.daemon.

**Comment by monstermunchkin** [comment]
Could you run `snap set lxd daemon.debug=true`, and provide us with the logs from `snap logs lxd`? That will likely display the error.

**Comment by Kumar6295** [comment]
ok , i wil do it

**Comment by Kumar6295** [comment]
after executing debug lxd command, it is working,Thank you

**Comment by monstermunchkin** [comment]
> after executing debug lxd command, it is working,Thank you

That's great. The `daemon.debug=true` setting was only to get more information in the logs. You can safely turn it off again using `snap unset lxd daemon.debug`.
