### ISSUE TITLE
How to Adjusting root size while creating container

### ISSUE THREAD

**Issue by Kumar6295** [lxc/lxd#8600]
using below commands we are able create containers and after creating container we are able override root storage but while launching new container how to give/override root size for the container

sudo lxc launch ubuntu:20.04 test
sudo lxc config device override test root size=20GB
->sudo lxc exec test bash 
root@test:~# df -h
Filesystem                       Size  Used Avail Use% Mounted on
disk/containers/test    20G 1011M   19G   6% /
none                             492K  4.0K  488K   1% /dev
udev                              63G     0   63G   0% /dev/tty
tmpfs                            100K     0  100K   0% /dev/lxd
tmpfs                            100K     0  100K   0% /dev/.lxd-mounts
tmpfs                             63G     0   63G   0% /dev/shm
tmpfs                             13G  184K   13G   1% /run
tmpfs                            5.0M     0  5.0M   0% /run/lock
tmpfs                             63G     0   63G   0% /sys/fs/cgroup

**Comment by monstermunchkin** [comment]
>  how to give/override root size for the container

What do you mean by root size? If you are trying to change the output of `df -h` to not show `63G` for tmpfs, it won't work for containers because they share the system's resources.

Perhaps VMs are better suited for what you are trying to achieve.

**Comment by Kumar6295** [comment]
Actually we are using zfs pool to one of hard disk (3.0 TB)..
We are creating container using launch command.

in every container it is showing 2.9T.

root@Test-Storage:~# df -h
Filesystem                          Size  Used Avail Use% Mounted on
**disk/containers/Test-Storage  2.9T   29G  2.9T   1% /**
none                                492K  4.0K  488K   1% /dev
udev                                 79G     0   79G   0% /dev/tty
tmpfs                               100K     0  100K   0% /dev/lxd
tmpfs                               100K     0  100K   0% /dev/.lxd-mounts
tmpfs                                79G     0   79G   0% /dev/shm
tmpfs                                16G  196K   16G   1% /run
tmpfs                               5.0M     0  5.0M   0% /run/lock
tmpfs                                79G     0   79G   0% /sys/fs/cgroup


We want to assign storage size for each container differently.. For that used override like sudo lxc config device override test root size=20GB.At that time it showing like below
df -h
**disk/containers/test 20G 1011M 19G 6% /**

we want to assign storage size of container when we are launching new container.is their any command

**Comment by monstermunchkin** [comment]
> we want to assign storage size of container when we are launching new container.is their any command

You cannot assign the storage size for each container individually using `lxc launch`. You have to do the following for each containers:

```bash
lxc init ubuntu:20.04 test
lxc config device override test root size=20GB # or: lxc config device set test root size=20GB
lxc start test
```

**Comment by Kumar6295** [comment]
Thank you..

**Comment by tomponline** [comment]
@Kumar6295 for non-bug issues please can you post over at https://discuss.linuxcontainers.org/ thanks :)
