### ISSUE TITLE
unable attach storage volume to container

### ISSUE THREAD

**Issue by Kumar6295** [lxc/lxd#8602]
i am able to attach Storage volume to container.
**commands**
sudo lxc launch ubuntu:20.04 etcd-2 

sudo lxc storage volume create local  etcd-storage-1 size=200GB

sudo lxc storage volume attach local etcd-storage-1 etcd-2 etcd-1 /dev/etcd

**ERROR:**

**Error: Failed to add device "etcd-1": Failed loading custom volume: No such object**

**Comment by tomponline** [comment]
Hi @Kumar6295 please could you post this over at https://discuss.linuxcontainers.org/

**Comment by Kumar6295** [comment]
Ok,Thank you
