### ISSUE TITLE
lxd 4.12 Container Disk Usage Information Not Present On btrfs (in ZFS is OK) 

### ISSUE THREAD

**Issue by gbonazzoli** [lxc/lxd#8611]
# Required information

 * Distribution: (Oracle Linux 8 & Ubuntu 20.04)
 * Distribution version: 4.12 snap
 * The output of "lxc info" or if that fails:
  os_name: Oracle Linux Server
  kernel_version: 5.4.17-2036.101.2.el8uek.x86_64
  os_version: "8.3"
  project: default
  server: lxd
  server_clustered: false
  server_name: ora02.ps.it
  server_pid: 187575
  server_version: "4.12"
  storage: btrfs
  storage_version: 4.15.1

# Issue description

With ZFS as storage backend "lxc info" 4.12 displays the disk usage of the container.

```
root@empire:~# lxc info srv-intranet 
Name: srv-intranet
....
  Disk usage:
    root: 16.71GB
```

The same snap version with a btrfs backend does not.

**Comment by stgraber** [comment]
Did you set a disk limit on your instance?

For ZFS the kernel always tracks disk usage, for btrfs this is only true if a quota has been set.

**Comment by gbonazzoli** [comment]
No I didn't set any limit on btrfs.

btrfs is much more immature and unstable than ZFS. So I tend to use it
without activating any features on it.
I have to use a machine with Oracle Linux on which ZFS is not a first
citizen....

Any way. It is one missed thing among a lot of others. :-(

**Comment by stgraber** [comment]
Yeah, to be fair, event when limits are set, the disk usage reporting isn't 100% accurate as users can pretty easily bypass their qgroup and so get unaccounted and unlimited disk usage...

Closing as AFAICT, there's no real LXD issue here, we're reporting whatever we can from the backend.
