### ISSUE TITLE
This operation can't be cancelled

### ISSUE THREAD

**Issue by qian-fei** [lxc/lxd#8622]
op, err := c.ExecContainer("some-ubuntu", req, &args)
if err != nil {
fmt.Println(err)
}
op.Cancel() // err: This operation can't be cancelled

**Comment by stgraber** [comment]
That's correct, LXD cannot cancel an exec operation.

**Comment by stgraber** [comment]
Not all operations are cancel-able. In general operation that are handling HTTP transfers can be canceled, the rest cannot.

For exec, you may be able to interrupt the process in the container by either running another command to kill the first or if still attached to the initial command by using its control socket to send a kill signal to the process.
