### ISSUE TITLE
network create type flag unknown

### ISSUE THREAD

**Issue by SLusenti** [lxc/lxd#8625]
hi all,
I'm trying to create some new network bridge configuration on my updated LXD cluster hosted on bionic servers.
But  currently it seems that won't recognize type flag anymore. 
please, see the example below
```
ubuntu@maas1:/var/lib/lxd/containers$ lxc network create br-internal --type=bridge 
Error: Invalid network configuration key: type
ubuntu@maas1:/var/lib/lxd/containers$ lxc network create br-internal -t bridge
Error: unknown shorthand flag: 't' in -t
```

I saw that the handling of this flag still exist on the source-code:
https://github.com/lxc/lxd/blob/134fda606b87ed5d5145249269674347b55f179e/lxc/network.go#L274

There's some workaround for this?

thanks.

**Comment by stgraber** [comment]
You're using an older release which does not have that flag.

Bridges are the default so not passing it will do what you want.
