### ISSUE TITLE
The source code for loop is invalid

### ISSUE THREAD

**Issue by qian-fei** [lxc/lxd#8634]
/ GetInstanceLogfiles returns a list of logfiles for the instance.
func (r *ProtocolLXD) GetInstanceLogfiles(name string) ([]string, error) {
	path, _, err := r.instanceTypeToPath(api.InstanceTypeAny)
	if err != nil {
		return nil, err
	}

	urls := []string{}

	// Fetch the raw value
	_, err = r.queryStruct("GET", fmt.Sprintf("%s/%s/logs", path, url.PathEscape(name)), nil, "", &urls)
	if err != nil {
		return nil, err
	}

	// Parse it     ↓↓ ↓↓ ↓↓ ↓↓ ↓↓ ↓↓ ↓↓
	logfiles := []string{}
	for _, uri := range logfiles {
		fields := strings.Split(uri, fmt.Sprintf("%s/%s/logs/", path, url.PathEscape(name)))
		logfiles = append(logfiles, fields[len(fields)-1])
	}

	return logfiles, nil
}

**Comment by tomponline** [comment]
Thanks I'll look into this.
