### ISSUE TITLE
Fix cluster image replication logic

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8641]
As mentioned in https://github.com/lxc/lxd/pull/8640 our current cluster image replication logic isn't exactly ideal.
With that code removed, there are still a few issues to sort out to get the level of reliability we need for this feature:

 - autoSyncImagesTask should run hourly instead of daily
 - autoSyncImages should iterate over all images, not just the locally available ones
 - imageSyncBetweenNodes should be updated to use our image handling API, get a client for the first address in `syncNodeAddresses` and use that as the source of `CopyImage` to copy to the target. This way the leader which runs this scheduled task will be able to replicate images that it doesn't itself locally own
 - autoSyncImages should be run from clusterPutJoin and clusterNodeDelete to ensure we replicate things as we grow/shrink
 - autoSyncImages should also be called from doApi10UpdateTriggers so a change in `cluster.images_minimal_replica` also triggers a new run

With that done, joining a 4th node to a 3 nodes cluster with a cached and a locally published image should cause no replication (cached image should be stored on 1 node, published one on all 3). Increasing the setting to 4 should lead to immediate replication. Reducing that to two and remove/re-add node 3 and 4 should have them join without any image replicated. Removing node 2 should cause the published image to be replicated on either node 3 or 4. The cached image should never be replicated.

**Comment by stgraber** [comment]
@monstermunchkin oh and make sure that the calls to autoSyncImages from the clusterNodeDelete function is a blocking call.
We shouldn't continue with the cluster node removal process if we didn't manage to replicate the images it held as that could lead to data loss.

**Comment by monstermunchkin** [comment]
> autoSyncImages should be run from clusterPutJoin and clusterNodeDelete to ensure we replicate things as we grow/shrink

@stgraber It's already run in `clusterPutJoin` when the function calls `d.startClusterTasks()`. Should we just do the same in `clusterNodeDelete` or only perform `autoSyncImages`?

**Comment by monstermunchkin** [comment]
@stgraber Nevermind, as you mentioned in your other comment it should be a blocking call, and `d.startClusterTasks()` won't block.

**Comment by monstermunchkin** [comment]
> We shouldn't continue with the cluster node removal process if we didn't manage to replicate the images it held as that could lead to data loss.

@stgraber What if `force` is set to 1? Blocking seems like a bad idea in that case.

**Comment by stgraber** [comment]
It's probably fine to ignore errors when forcing the removal as indeed we may not have another source for the image.

**Comment by stgraber** [comment]
What I mostly want to avoid is it being spun off in a goroutine and possibly having more nodes removed before it's done running, causing some images to go unreplicated and missing from the cluster.
