### ISSUE TITLE
Importing VMs previously exported w/ --optimized storage flag ended w/ error

### ISSUE THREAD

**Issue by rvalo** [lxc/lxd#8649]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04.2 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux pila 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 4.12
   * LXD version: 4.12
   * Storage backend in use: ZFS

# Issue description

I have two identical machines, with identical HW, OS version and patches, LXD versions & storage backends. When trying to backup stopped VM from one machine via
lxc export ubuvm /path/to/backup/ubuvm.tar.gz --optimized storage

and restore it on another machine via
lxc import /path/to/backup/ubuvm.tar.gz ubuvm-backup

import ended by the following error message:
Error: Post hook: In use

This is working perfectly with containers. For VMs, it is working just without --optimized-storage flag.

**Comment by tomponline** [comment]
I've recreated this and am looking into it.
