### ISSUE TITLE
VM snapshots copying not working correctly

### ISSUE THREAD

**Issue by rvalo** [lxc/lxd#8651]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04.2 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux pila 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 4.12
   * LXD version: 4.12
   * Storage backend in use: ZFS

# Issue description

When trying to run copied VM snapshot on remote LXD server, error message is given:

```
Error: Failed preparing container for start: No such file or directory: "/var/snap/lxd/common/lxd/storage-pools/default/containers/ubuvm-snapcopy/rootfs"
Try `lxc info --show-log ubuvm-snapcopy` for more info
```

# Steps to reproduce

1. There is existing Ubuntu 20.04 VM (called ubuvm) newly created on source LXD server (freza):

```
rvalo@freza:~$ lxc list
+---------+---------+------+------+-----------------+-----------+
|  NAME   |  STATE  | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+---------+---------+------+------+-----------------+-----------+
| ubucont | STOPPED |      |      | CONTAINER       | 0         |
+---------+---------+------+------+-----------------+-----------+
| ubuvm   | STOPPED |      |      | VIRTUAL-MACHINE | 0         |
+---------+---------+------+------+-----------------+-----------+
| windows | STOPPED |      |      | VIRTUAL-MACHINE | 0         |
+---------+---------+------+------+-----------------+-----------+
```

2. Creating new snapshot of ubuvm:

```
rvalo@freza:~$ lxc snapshot ubuvm
rvalo@freza:~$ lxc info ubuvm
Name: ubuvm
Location: none
Remote: unix://
Architecture: x86_64
Created: 2021/04/08 13:11 UTC
Status: Stopped
Type: virtual-machine
Profiles: default
Snapshots:
  snap0 (taken at 2021/04/09 07:24 UTC) (stateless)
```

3. Copying newly created snapshot to remote LXD server (pila), ended successfully without any error indication:
```
rvalo@freza:~$ lxc copy ubuvm/snap0 pila:ubuvm-snapcopy
rvalo@freza:~$
```

4. Checking the copied snapshot on remote LXD server:
```
rvalo@pila:~$ lxc list
+----------------+---------+------+------+-----------------+-----------+
|      NAME      |  STATE  | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+----------------+---------+------+------+-----------------+-----------+
| ubucont-backup | STOPPED |      |      | CONTAINER       | 0         |
+----------------+---------+------+------+-----------------+-----------+
| ubuvm-snapcopy | STOPPED |      |      | CONTAINER       | 0         |
+----------------+---------+------+------+-----------------+-----------+
| windows-copy   | STOPPED |      |      | VIRTUAL-MACHINE | 0         |
+----------------+---------+------+------+-----------------+-----------+
```
Note the type of copied snapshot - it's CONTAINER, not VIRTUAL-MACHINE as it would be expected.

5. Attempt to start the copied snapshot - above mentioned error message is given:
```
rvalo@pila:~$ lxc start ubuvm-snapcopy
Error: Failed preparing container for start: No such file or directory: "/var/snap/lxd/common/lxd/storage-pools/default/containers/ubuvm-snapcopy/rootfs"
Try `lxc info --show-log ubuvm-snapcopy` for more info
```

The container log is empty however:
```
rvalo@pila:~$ lxc info --show-log ubuvm-snapcopy
Name: ubuvm-snapcopy
Location: none
Remote: unix://
Architecture: x86_64
Created: 2021/04/09 07:28 UTC
Status: Stopped
Type: container
Profiles: default

Log:


rvalo@pila:~$
```
6. On source LXD server (freza), attempt to delete ubuvm/snap0 ended w/ error:
```
rvalo@freza:~$ lxc delete ubuvm/snap0
Error: Failed to run: zfs destroy default/virtual-machines/ubuvm.block@snapshot-snap0: cannot destroy snapshot default/virtual-machines/ubuvm.block@snapshot-snap0: dataset is busy
```
Looking to running processes, the underlying zfs copy command didn't finished correctly, which seems to be the core of the issue:
```
rvalo@freza:~$ ps -ef | grep zfs
root     2483729 1812484  0 09:28 ?        00:00:00 zfs send -c -L default/virtual-machines/ubuvm.block@snapshot-snap0
```
After killing this process manually, deletion of ubuvm/snap0 finished successfully.
7. I was trying the same steps with both stateless and stateful snapshots of VMs, both with the same issue.

**Comment by tomponline** [comment]
Thanks I'll look into this now.

**Comment by tomponline** [comment]
Recreated. Only affects copying snapshots as new VMs.

**Comment by tomponline** [comment]
Seems to work OK when using the migration system between pools on the same node.

However when doing cross-node transfers it is failing even when doing a non-optimised transfer (ZFS -> LVM for example) with an error:

```
 - https://192.168.1.106:8443: Error transferring instance data: No matching migration types found. Offered types: [RSYNC RSYNC], our types: [ZFS BLOCK_AND_RSYNC]
```

**Comment by tomponline** [comment]
This actually looks like a client bug, the `CopyInstanceSnapshot` function is not populating the instance type field in the POST request:

https://github.com/lxc/lxd/blob/0ef7797a64667a4c372119685607ffeb977f303c/client/lxd_instances.go#L1194

Compared to:

https://github.com/lxc/lxd/blob/0ef7797a64667a4c372119685607ffeb977f303c/client/lxd_instances.go#L387

**Comment by tomponline** [comment]
@stgraber confirmed, hardcoding the `Type` field in that POST request fixes it.

But I am unsure how best to proceed here with a fix.

My first thought was to add a `Type` field to the `api.InstanceSnapshot` struct type, this would then allow us to populate the source type in https://github.com/lxc/lxd/blob/a7ece9de1d21fe591dcf2a725aa6d3393dc587de/lxc/copy.go#L167 and then use it when we call https://github.com/lxc/lxd/blob/a7ece9de1d21fe591dcf2a725aa6d3393dc587de/lxc/copy.go#L240 passing in the entry.

But I was concerned that this would add an additional API field, and as well, introduce the concept that the `api.InstanceSnapshot` struct has a type, which would need careful consideration as it is used in many places internally to LXD as well, where it would potentially also need populating/using to ensure consistency (presumably at the moment those places have access to the parent instance and so can derive the correct instance type that way).

For an alternative to that, I considered extending the `InstanceSnapshotCopyArgs` struct with a `Type` field and then in `copyInstance` also make a call to `GetInstance` for the parent to get its type, and then copy the type into the `InstanceSnapshotCopyArgs.Type` field for use in `CopyInstanceSnapshot`. This would still introduce a new field, but wouldn't be an API struct change nor a conceptual change.

**Comment by stgraber** [comment]
@tomponline can't we have `CopyInstanceSnapshot` effectively do:
 - Check if server supports VMs, if not, take the easy path
 - Do `source.GetInstance(instanceName)` to figure out the type
 - Set the type in `InstancesPost` to match the one retrieved

**Comment by tomponline** [comment]
@stgraber yep we can, thats basically the same as my 2nd proposal, but just doing it inside the `CopyInstanceSnapshot` function rather than modifying `InstanceSnapshotCopyArgs` - I wasn't sure if that was OK as seemed a bit inconsistent with how other copy functions are done (i.e gathering configuration outside).

**Comment by stgraber** [comment]
Well, the issue with it being in args is that it's not really an option, you can copy a VM as a container or the other way around.

**Comment by tomponline** [comment]
@stgraber I dont really understand what you mean, we'd only pass in the correct type to the argument InstanceType, but don't worry about it, as this way is nicer as it doesn't modify any structs.
