### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by janmuennich** [lxc/lxd#8653]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
[lxc info.txt](https://github.com/lxc/lxd/files/6285533/lxc.info.txt)

# Issue description

Since our migration from LXD 3 via .deb to LXD 4.0.5 via Snap, we are observing a memory leak in LXD. This happens in two independent clusters with each ca. 10 hosts.

Every day, memory LXD usage goes up by about 64 MB on hosts that don't handle many `lxc` commands and by about 320 MB on the host in each cluster that does issue a lot of `lxc` commands (hourly snapshot creation and deletion for all containers and VMs).

So my guess is that the memory leak is either connected the snapshots or to the `lxc` commands themselves.

For now, we restart LXD every couple of days with `systemctl reload snap.lxd.daemon`.

# Information to attach

As requested in: https://github.com/lxc/lxd/issues/6362#issuecomment-730024517

> curl http://localhost:8444/debug/pprof/goroutine?debug=2

[goroutine.txt.gz](https://github.com/lxc/lxd/files/6285626/goroutine.txt.gz)

> go tool pprof -top http://localhost:8444/debug/pprof/heap

[pprof.heap.output.txt](https://github.com/lxc/lxd/files/6285629/pprof.heap.output.txt)
[pprof.lxd.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/lxc/lxd/files/6285631/pprof.lxd.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)

> go tool pprof -top http://localhost:8444/debug/pprof/allocs

[pprof.allocs.output.txt](https://github.com/lxc/lxd/files/6285632/pprof.allocs.output.txt)
[pprof.lxd.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz](https://github.com/lxc/lxd/files/6285633/pprof.lxd.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz)

> You should also run lxc query /internal/gc to force a garbage collection + return to OS run.
> This will log some statistics in lxd.log which you should also include.

[lxc.log garbage collection.txt](https://github.com/lxc/lxd/files/6285640/lxc.log.garbage.collection.txt)

**Comment by stgraber** [comment]
Holy crap, that's a lot more goroutines than you should have :)
You have 29513 of them when a normal server often has less than 20!

**Comment by stgraber** [comment]
You appear to have an insane amount of WebsocketProxy goroutines and handlers for GetEvents (may be related as GetEvents is a websocket API).

I suspect the memory usage is likely all coming from what's held by those goroutines.

**Comment by stgraber** [comment]
I looked at my production cluster which also has automated snapshots (daily, delete after 7) on all instances and volumes but I'm not seeing any suspicious goroutine in my case. Mind you, it's running LXD 4.13 not 4.0.5 so maybe it's something we fixed somehow...

Can you confirm that your snapshot creation and deletion is handled through LXD's snapshot scheduling and snapshot expiry and not through an external system?

Could you show `lxc operation list` too to see if any of those goroutines are tied to operations?

**Comment by janmuennich** [comment]
Thanks for looking at the issue!

The snapshots are not managed by LXD snapshot scheduling. A backup script creates the snapshot with `lxc snapshot` and transfers it directly with ZFS to a backup storage. Next time the backup script runs, the old snapshot is deleted with `lxc delete`. So there is never an excessive amount of snapshots on the servers, maximum 2 per instance. On another cluster that runs with Ceph, the snapshots are actually not managed by LXD at all but instead directly with `rbd`.

I always thought that LXD would just pass on the snapshot actions to the underlying file system and also keep a record of snapshot in the database. Is there anything else going on that would be different when using snapshot scheduling?

`lxc operation list` does not show anything. I actually monitored that for a while but there was nothing suspicious going on apart from normal operations that finish correctly.

**Comment by stgraber** [comment]
Sorry for the delay on this one...
How many machines do you have in that cluster? And roughly how many instances? Also how many projects (if you use them)?

This may help us reproduce a similar environment here. The goroutine output certainly showed you having far more GetEvents goroutines than anyone should ever have, but it's still a bit unclear whether that's triggered by the snapshot API calls or by something else.

**Comment by stgraber** [comment]
Also worth noting that 4.0.6 is currently in 4.0/candidate and we're expecting it to be pushed to users in stable tomorrow.
I'd be surprised if that took care of things though as I went through our commit history and there's nothing really changing in that area.

**Comment by janmuennich** [comment]
Cluster 1: 60 instances on 10 machines
Cluster 2: 70 instances on 7 machines

On cluster 1 a snapshot is created and deleted via `lxc` hourly. On cluster 2 snapshots are created directly on the storage backend without involving `lxc` commands. So I guess snapshots are not related to the issue, although I don't understand the LXD procedures in detail.

Additionally, for every instance once per hour, a monitoring server fetches health details, e.g. diskspace with a single `lxc exec` command.

I'm quite sure though that the issue is related to cluster operations. We also have single node LXD servers that execute the same snapshot and monitoring commands. These servers don't suffer from the memory leak.

Let me know what I can do to further debug this!

**Comment by stgraber** [comment]
Ah, good to know, so yeah, it's not going to be snapshots that are causing that goroutine leak then.
LXD 4.0.6 has now made it to the `stable` channel. It'd be great if you could refresh one of the clusters and confirm that the issue is still happening.

If it is, then we'll likely want to capture `lxc monitor --type=logging --pretty` for a reasonable amount of time while also getting a frequent count of the number of goroutines so hopefully we can correlate LXD actions with the leakage.

**Comment by janmuennich** [comment]
`Connecting to a remote LXD over HTTPs` happens for every `lxc` request as it is sent to the cluster member where the instance lives. So in this cluster for all monitoring and snapshot commands three times per hour for every instance. In total 180 requests per hour on this machine.

Would this be be problem? I thought it is one of the features of clustering that you don't have to issue commands locally on the machine where the instance is running.

**Comment by stgraber** [comment]
No, you're right, it's perfectly fine for LXD to forward requests internally and indeed your output looks correct for an exec operation.
The accumulation of goroutines kinda looks like something isn't getting cleaned up though.

You said you're seeing the same behavior on machines that do not rely on the LXD API for snapshotting, do those systems still use your monitoring tooling to run exec sessions? If so, that'd point more towards an issue with exec not clearing an event listener or something along those lines.

**Comment by stgraber** [comment]
I've managed to reproduce it on a cluster running 4.14. It definitely seems to be related to `exec` operations across the cluster.

**Comment by stgraber** [comment]
```
root@infra01:~# curl -s "http://127.0.0.1:8444/debug/pprof/goroutine?debug=2" | grep created.*GetEvent | wc -l
14
root@infra01:~# curl -s "http://127.0.0.1:8444/debug/pprof/goroutine?debug=2" | grep created.*GetEvent | wc -l
94
root@infra01:~# curl -s "http://127.0.0.1:8444/debug/pprof/goroutine?debug=2" | grep created.*GetEvent | wc -l
104
root@infra01:~# curl -s "http://127.0.0.1:8444/debug/pprof/goroutine?debug=2" | grep created.*GetEvent | wc -l
256
root@infra01:~# curl -s "http://127.0.0.1:8444/debug/pprof/goroutine?debug=2" | grep created.*GetEvent | wc -l
256
root@infra01:~# curl -s "http://127.0.0.1:8444/debug/pprof/goroutine?debug=2" | grep created.*GetEvent | wc -l
266
root@infra01:~# curl -s "http://127.0.0.1:8444/debug/pprof/goroutine?debug=2" | grep created.*GetEvent | wc -l
270
```

Over just a few seconds while spamming the server with exec sessions.

The initial 14 is normal (2x the number of other nodes in the cluster is expected), but more than that shouldn't happen unless there are active exec sessions (which there isn't in my case).

**Comment by janmuennich** [comment]
That's great. Thanks for the update!

**Comment by stgraber** [comment]
The bulk of the leak was fixed but I'm still seeing a websocketproxy leak for each exec session, looking into that now.

**Comment by stgraber** [comment]
Got a fix where I'm now not getting a single leftover goroutine after running 10000 exec sessions.

**Comment by janmuennich** [comment]
Sorry to bother you again! Any chance that you could release 4.0.7 with this fix?

**Comment by stgraber** [comment]
We'll be releasing new stable releases this week.
