### ISSUE TITLE
Add options for automated host selection in cluster

### ISSUE THREAD

**Issue by jetojedno** [lxc/lxd#8657]
# Feature description

Add options to control the automated selection of host for new instances:
- host-enabled: **true** / false (for each host)
- algorithm: **number** / load (for cluster)
- algorithm.load-period: **30** minutes

If host-enabled is false, don't auto-select that host for new instances; if true, always consider
If algorithm is number, select host with lowest number of instances (the current algorithm). If load, select the host with the lowest average load (measured by CPU utilisation) over the past load-period minutes.

_Note_: it's possible to elaborate this by specifying or auto-determining the cluster's limiting resource and using that instead of CPU utilisation.

_Note_: it's possible to elaborate this by adding requirement tags to the start / launch request which must all match the tags of the host chosen.  No tags = all enabled are eligible.

# Justification / Utility:
I have an unbalanced cluster where the various hosts have different characteristics, and one is a low-powered control & ingress / egress host where no new instances should be created.  At present I have to manually specify the target host for each instance, which is un-sustainable medium term.

# Required information
Ubuntu focal / 20.04
LXD 4.12
Linux 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stgraber** [comment]
We've been pretty resistant on changing that algorithm or introducing options for it as we'd very very quickly find ourselves in a rabbit hole, having to deal with a whole lot of hardware behavior differently. The load average isn't a particularly great metric nor one that LXD track. We also have been using a general policy of never storing temporary state in our database so not too keen on having to change that.

What we're considering though is configuration on the cluster node allowing for specific nodes never to be auto-selected, instead those would require direct targeting. This may solve the issue for some common cases of unbalanced clusters.

**Comment by jetojedno** [comment]
Thanks.  Blocking auto-allocation on the control servers would solve half my issue with this.

The counting instances approach depends on the assumption that there are a large number of instances so the differences between instance resource consumption averages out to more-or-less equal.  My use case is different with a very unbalanced mix of instances having small number of high CPU & memory demanding instances and a small number of high disk use instances.

I'll build some resource tracking outwith LXD and create a script for container creation in place of `lxc init | start` which uses that info.  That would have other benefits as it would allow me to create and manage work queues.

**Comment by stgraber** [comment]
Yeah, we suspect that in many cases more complex scheduling will often be better handled externally. Load based scheduling is one approach but I think you'll quickly want to also consider the size of the instance you're deploying, whether it needs special hardware, what other instances already exist on given nodes, ...

For now a completely external scheduler that tells you what target to select is the easiest though we have plans to start adding webhook support to LXD and a scheduling hook would certainly make sense. With that you could give LXD a URL to hit whenever a cluster node needs to be selected and LXD would call it with some context about the new instance and give a chance to that hook to override the default target.

We're looking at building up that infrastructure in LXD over the next 6 months and then slowly start adding more hooks as we find the need for them.
