### ISSUE TITLE
Any way to resolve container ip addresses from host ?

### ISSUE THREAD

**Issue by clarkwinkelmann** [lxc/lxd#866]
I'm experimenting with LXD. I have created many containers and now I'd like to access them trough certain ports. I adapted some iptables rules found [here](http://stackoverflow.com/questions/18580637/iptables-redirect-from-external-interface-to-loopbacks-port):

    iptables -t nat -A PREROUTING -p tcp -i eth0 -m tcp --dport 80 -j DNAT --to-destination 10.0.3.30:80

Where `10.0.3.30` is the dynamically allocated ip for the `srv-web1` container.

It works well, but I had to hard-code the dynamic ip (found with `ifconfig`). I think there's a great risk that the thing break if I restart the host or move containers around.

I could use static ips, but I didn't found any documentation to do that, and I'd prefer to keep DHCP and manage containers by name and not mess with a lot of ips. Is there a way to query the hostnames from the host machine, like `dig lxd.srv-web1` or a bash command / environment variable that stores this data ?

Edit: I've found I can do `dig @10.0.3.1 mycontainer`. If I use that can I be sure that the NAT router/dns will always be found at this address ?

**Comment by stgraber** [comment]
The dig trick is probably about as reliable as it gets without poking the LXD API.

If you want to know for sure what the container's IP address is, using "lxc info container_name" or the REST API would be the way to go.

**Comment by stgraber** [comment]
Using the REST API and a trusted certificate, you can do something like (admittedly not a super simple filter).

    stgraber@castiana:~$ curl -k -s --cert .config/lxc/client.crt --key .config/lxc/client.key https://localhost:8443/1.0/containers/abc | jq '.metadata.status.ips | map(select(.interface=="eth0")) | map(select(.protocol=="IPV4")) | .[0].address'
    "10.0.3.249"

**Comment by stgraber** [comment]
Closing since this was a question which I believe has been answered. Feel free to let us know if you think there's a bug somewhere in LXD or some way to make it easier for your use case.

**Comment by ak2766** [comment]
Is this broken?
```
lxc remote list | grep lxc
| lxc             | https://my-lxd-server.my-domain.com:10443               | lxd           | NO     | NO     |

$ lxc list lxc: | grep dummy
| dummy               | RUNNING | 10.2.20.43 (eth0)              |      | PERSISTENT | 0         |
```
When I attempt to get the IP via API, I get:

```
$ curl -s -k --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key https://my-lxd-server.my-domain.com:10443/1.0/containers/dummy | jq '.metadata.status.ips | map(select(.interface=="eth0")) | map(select(.protocol=="IPV4")) | .[0].address'
jq: error (at <stdin>:1): Cannot index string with string "ips"
```
Here's evidence that the machine really exists:
```
curl -s -k --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key https://my-lxd-server.my-domain.com:10443/1.0/containers/dummy | jq .metadata.config
{
  "image.architecture": "amd64",
  "image.description": "ubuntu 16.04 LTS amd64 (release) (20170307)",
  "image.label": "release",
  "image.os": "ubuntu",
  "image.release": "xenial",
  "image.serial": "20170307",
  "image.version": "16.04",
  "volatile.base_image": "x",
  "volatile.eth0.hwaddr": "00:16:3e:e4:b3:2a",
  "volatile.idmap.base": "0",
  "volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]",
  "volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]",
  "volatile.last_state.power": "RUNNING"
}

**Comment by ak2766** [comment]
Found it - [Rest API](https://github.com/lxc/lxd/blob/master/doc/rest-api.md):
```
$ curl -s -k --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key https://my-lxd-server.my-domain.com:10443/1.0/containers/dummy/state | jq .{
  "type": "sync",
  "status": "Success",
  "status_code": 200,
  "operation": "",
  "error_code": 0,
  "error": "",
  "metadata": {
    "status": "Running",
    "status_code": 103,
    "disk": {},
    "memory": {
      "usage": 143683584,
      "usage_peak": 769069056,
      "swap_usage": 0,
      "swap_usage_peak": 0
    },
    "network": {
      "eth0": {
        "addresses": [
          {
            "family": "inet",
            "address": "10.2.20.43",
            "netmask": "24",
            "scope": "global"
          },
      ...
```
