### ISSUE TITLE
Error: Failed instance creation: invalid character '\x00' after top-level value

### ISSUE THREAD

**Issue by janpekar** [lxc/lxd#8668]
Hi all,

I have problem creating new lxc container.
I get `Error: Failed instance creation: invalid character '\x00' after top-level value
`
I run 
```lxc launch images:debian test01```

Last debug messages are
```
DBUG[04-14|10:50:41] Sending request to LXD                   method=POST url=http://unix.socket/1.0/instances etag=
DBUG[04-14|10:50:41]
        {
                "architecture": "",
                "config": {},
                "devices": {},
                "ephemeral": false,
                "profiles": null,
                "stateful": false,
                "description": "",
                "name": "test01",
                "source": {
                        "type": "image",
                        "certificate": "",
                        "alias": "debian",
                        "server": "https://images.linuxcontainers.org",
                        "protocol": "simplestreams",
                        "mode": "pull"
                },
                "instance_type": "",
                "type": "container"
        }
Error: Failed instance creation: invalid character '\x00' after top-level value
```

The same I see in ```lxc monitor```, no other error messages. 
The log in `/var/snap/lxd/common/lxd/logs/lxd.log` shows no errors, the same syslog o kern.log

How can I debug it more? From my side it looks that lxd returns empty response?

Stopping and starting already created containers is ok. I only cannot create new one.

Some additional info below.

Thank you for help.

```
  kernel_version: 5.4.0-52-generic
  os_name: Ubuntu
  os_version: "20.04"
  server_version: 4.0.5
  storage: dir | ceph

```

**Comment by tomponline** [comment]
Please see https://discuss.linuxcontainers.org/t/linuxcontainers-org-image-server-appears-to-be-broken/10768
