### ISSUE TITLE
DeferTemplateApply triggers don't stack

### ISSUE THREAD

**Issue by fergus-dall** [lxc/lxd#8674]
# Required information

 * Distribution: Chrome OS
 * Distribution version: 4.0.5
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.110
   * LXC version: 4.0.6
   * LXD version: 4.0.5
   * Storage backend in use: btrfs

# Issue description

When LXD image template triggers are queued with DeferTemplateApply, only the last trigger applies. Concretely, if you create a container and rename it before the first time it runs, only the "rename" triggers will run.

# Steps to reproduce

 1. lxc init images:debian/buster test1234
 2. lxc config get test1234 volatile.apply_template    # "create"
 3. lxc rename test1234 test5678
 4. lxc config get test5678 volatile.apply_template    # "rename"
 5. lxc start test5678
 6. lxc exec test5678 -- cat /etc/hostname   # hostname.tpl should have set this to the container name
 7. lxc exec test5678 -- cat /etc/hosts          # hosts.tpl should have added the container name to this file

Arguably these templates should also be set to run on rename too

**Comment by stgraber** [comment]
The easiest fix there would be not to update the volatile key if it's already set, that way copy/create would not get overridden by rename.
