### ISSUE TITLE
Volume snapshots should only be done on one node

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8680]
`cephfs` volume snapshots appear to be done by all of my servers causing in this case 3x as many snapshots as I should have...

**Comment by Fl4v** [comment]
Hello again @stgraber , if you point me in the right direction, I am happy to take this on.

**Comment by stgraber** [comment]
@Fl4v thanks!

I'll have to dig into the code a bit, basically I'd track down where the scheduled snapshots are handled for volumes and then in that function we're going to have to check if the storage pool is remote and if it's remote add logic so that we use a stable random to determine what cluster member will preform the actual snapshot.

I thought we had put logic in place to do that already but based on the snapshots I'm seeing, it doesn't appear to be the case ;)

**Comment by stgraber** [comment]
`autoCreateCustomVolumeSnapshots` in `storage_volumes_snapshot.go` is what creates the volume snapshots.

**Comment by stgraber** [comment]
I found the regression, it's simply code we removed by accident... I'll send a trivial PR to revert that change.

**Comment by stgraber** [comment]
@Fl4v if you'd like another similar issue to look into, https://github.com/lxc/lxd/issues/8670 should be a good one!

**Comment by stgraber** [comment]
@Fl4v or https://github.com/lxc/lxd/issues/8674 would be another easy one to fix

**Comment by Fl4v** [comment]
> 
> 
> @Fl4v if you'd like another similar issue to look into, #8670 should be a good one!

Hi @stgraber, sure thing, I will give it a try.
