### ISSUE TITLE
Failed to start the daemon: Failed to start dqlite server

### ISSUE THREAD

**Issue by genet022** [lxc/lxd#8688]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Focal
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-72-generic
   * LXC version: lxc (1:4.0.2-0ubuntu1) [universe]
   (*Comes from stable Focal Cloudinit image which pulls from Universe*)
   * LXD version: lxd (1:0.9) [universe]
   (*Comes from stable Focal Cloudinit image which pulls from Universe*)
   * Storage backend in use: zfs

# Issue description

Solutions-qa hit this on a run over the weekend during an Openstack deploy. So the lxd/lxc Snaps come from the stable Focal Cloudinit image we are using. I would be willing to bet we hit a database transaction corruption due to unclean system shutdown or something similar. I came across canonical/raft#57 and noticed you could not figure out exactly what happened so I figured I'd throw a bug together in case we have any valuable info for you in our logging.

Our logging is linked below. The environment has unfortunately since been cleaned up. If you have any questions let me know!

Feel free to move this to Raft if that is a more appropriate location.

Here's the usual failure snippet from syslog:
```
Apr 18 16:28:25 spearow systemd[1]: Started Service for snap application lxd.daemon.
Apr 18 16:28:25 spearow lxd.daemon[5506]: => Preparing the system (20037)
Apr 18 16:28:25 spearow lxd.daemon[5506]: ==> Loading snap configuration
Apr 18 16:28:25 spearow lxd.daemon[5506]: ==> Setting up mntns symlink (mnt:[4026533887])
Apr 18 16:28:25 spearow lxd.daemon[5506]: ==> Setting up kmod wrapper
Apr 18 16:28:25 spearow lxd.daemon[5506]: ==> Preparing /boot
Apr 18 16:28:25 spearow lxd.daemon[5506]: ==> Preparing a clean copy of /run
Apr 18 16:28:25 spearow lxd.daemon[5506]: ==> Preparing /run/bin
Apr 18 16:28:25 spearow lxd.daemon[5506]: ==> Preparing a clean copy of /etc
Apr 18 16:28:26 spearow lxd.daemon[5506]: ==> Preparing a clean copy of /usr/share/misc
Apr 18 16:28:26 spearow lxd.daemon[5506]: ==> Setting up ceph configuration
Apr 18 16:28:26 spearow lxd.daemon[5506]: ==> Setting up LVM configuration
Apr 18 16:28:26 spearow lxd.daemon[5506]: ==> Rotating logs
Apr 18 16:28:26 spearow lxd.daemon[5506]: ==> Setting up ZFS (0.8)
Apr 18 16:28:26 spearow lxd.daemon[5506]: ==> Escaping the systemd cgroups
Apr 18 16:28:26 spearow lxd.daemon[5506]: ====> Detected cgroup V1
Apr 18 16:28:26 spearow lxd.daemon[5506]: ==> Escaping the systemd process resource limits
Apr 18 16:28:26 spearow lxd.daemon[5506]: ==> Disabling shiftfs on this kernel (auto)
Apr 18 16:28:26 spearow lxd.daemon[5506]: => Re-using existing LXCFS
Apr 18 16:28:26 spearow lxd.daemon[5506]: => Starting LXD
Apr 18 16:28:26 spearow lxd.daemon[5643]: t=2021-04-18T16:28:26+0000 lvl=warn msg=" - Couldn't find the CGroup blkio.weight, disk priority will be ignored"
Apr 18 16:28:26 spearow lxd.daemon[5643]: t=2021-04-18T16:28:26+0000 lvl=warn msg=" - Couldn't find the CGroup memory swap accounting, swap limits will be ignored"
Apr 18 16:28:26 spearow lxd.daemon[5643]: t=2021-04-18T16:28:26+0000 lvl=eror msg="Failed to start the daemon: Failed to start dqlite server: raft_start(): io: load closed segment 0000000000000001-0000000000000001: file is empty"
Apr 18 16:28:26 spearow lxd.daemon[5643]: Error: Failed to start dqlite server: raft_start(): io: load closed segment 0000000000000001-0000000000000001: file is empty
Apr 18 16:28:27 spearow lxd.daemon[5506]: => LXD failed to start
Apr 18 16:28:27 spearow systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=1/FAILURE
Apr 18 16:28:27 spearow systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
Apr 18 16:28:27 spearow systemd[1]: snap.lxd.daemon.service: Scheduled restart job, restart counter is at 1.
```

# Information to attach

**Test run on our dashboard:**
https://solutions.qa.canonical.com/testruns/testRun/8d916282-adc3-4a2b-b977-d77aeb6b642c

**Full Artifacts/Logs/Bundles:**
https://oil-jenkins.canonical.com/artifacts/8d916282-adc3-4a2b-b977-d77aeb6b642c/index.html

**Juju model crashdump (syslogs/etc from Machine 3 that encountered this issue)**
https://oil-jenkins.canonical.com/artifacts/8d916282-adc3-4a2b-b977-d77aeb6b642c/generated/generated/openstack/juju-crashdump-openstack-2021-04-18-20.17.41.tar.gz

**Comment by genet022** [comment]
Looks like we don't collect `/var/snap/lxd`. And since the environment has been cleaned and redeployed I can't get to it.
I'll add that to crashdump collection for the future though.

**Comment by stgraber** [comment]
Thanks, without it, there's really nothing else we can do, especially since we've fixed a number of bugs in that area over the past weeks so this may have been resolved already.
