### ISSUE TITLE
Add new project restrictions for snapshots and backups

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8703]
Snapshots and backups can be expensive both to produce and store them, so it would make sense to make them a restricted feature.

We should add:
 - restricted.backups (allow/deny)
 - restricted.snapshots (allow/deny)

Which will restrict the creation of any instance backups/snapshots or volume backups/snapshots.

**Comment by presztak** [comment]
@stgraber Can I work on this one?

**Comment by stgraber** [comment]
Certainly!
