### ISSUE TITLE
enhancment: allow ipv4.address on macvlan networks

### ISSUE THREAD

**Issue by jetojedno** [lxc/lxd#8709]
# Required information

Ubuntu focal 20.04
LXD 4.13

# Issue description

I have an LXD MACVLAN network on a switch without DHCP server, so the instances don't acquire an IP Address.

`lxc network lxdmvl0 assign XXXX eth0 eth0` (lxdmvl0 is the macvlan network) followed by
`lxc config device set XXXX eth0 ipv4.address aa.bb.cc.dd` doesn't work - it seems to have no effect.

The way I found to give it an IP address was `ip link set up dev eth0` then `ip a add aa.bb.cc.dd dev eth0` then 'ip r add default aa.bb.cc.dd` in the instance.
I haven't tested if this is enough for the container to communicate as I decided to switch to OVN at this point.  I suspect not as I couldn't see the IP Address listed on the host device.

It would be much less error prone if `config device set ... ipv4.address ...` worked for macvlan networks.

**Comment by stgraber** [comment]
Supporting `ipv4.address` wouldn't do you any good without a way to configure a gateway, DNS, ...
You can do all that through `user.network-config` with cloud-init instead which is likely a better fit in this case.
