### ISSUE TITLE
DHCP stopped to work with LXD 4.13

### ISSUE THREAD

**Issue by arren-ru** [lxc/lxd#8710]
# Required information

 * Distribution: archlinux
   * Kernel version: 5.11.15
   * LXC version: 4.0.6
   * LXD version: 4.13
   * Storage backend in use: lvm | zfs

# Issue description

Simply after upgrading from 4.12 to 4.13 network stopped to work in terms of no IP addresses was assigned via external DHCP while no configuration was changed.

# Information to attach

- [Several configurations](https://gist.github.com/arren-ru/e1bcdcbde77f60dd85cc7719068fa51a)

Downgrading LXD to 4.12 also fixes problem

**Comment by tomponline** [comment]
Can you try setting ipv4.firewall and ipv6.firewall to false on your network. I think it could be related to https://github.com/lxc/lxd/pull/8706

**Comment by arren-ru** [comment]
> Can you try setting ipv4.firewall and ipv6.firewall to false on your network. I think it could be related to #8706

Yes it works, but why it is enforced? Anyway thanks for the answer.
I would like to recommend to leave this issue opened for those people who will face such kind of problem until it is resolved in #8706.

**Comment by tomponline** [comment]
It was an issue that has been fixed in #8706 that has already been merged and will be in 4.14 or cherry picked into 4.13. Will close this now, but is still searchable.
