### ISSUE TITLE
Implement a way to hot-plug mounts into container

### ISSUE THREAD

**Issue by hallyn** [lxc/lxd#872]
It is not possible to insert mounts into another namespace.  We can however implement a roundabout way to achieve this.  We cannot make it bullet-proof - meaning that the container root will be able to prevent such mounts from working in the future.  That's its own problem.

The simplest way to do this would be to create a /dev/.lxc_mounts directory, which is MS_SHARED with the host.  When we 'lxc config device add hostmnt type=disk source=/mnt path=/mnt", lxd can bind-mount /mnt to /var/lib/lxd/lxc/sharedmounts/mnt, then attach to the container's mntns and move-mount /dev/lxc/mnt to /mnt.  Alternatively it could ask for this to happen using a /dev/lxd callback, but that seems more fragile and depends on running dev-lxd-watcher in the container.

**Comment by stgraber** [comment]
The MS_SHARED hack is fine for now. I'd still like to dig into the kernel and understand why there's this check in place which prevents us from bind-mounting cross mntns as that'd be a cleaner solution (open dirfd outside the container, setns to the mntns, bind-mount /proc/self/fd/X to path, done).

**Comment by techtonik** [comment]
Is there a user level doc how to use this feature?

**Comment by stgraber** [comment]
Works the exact same way as adding mounts before, except you don't have to restart the container anymore.

**Comment by techtonik** [comment]
Meaning you still need to give rw access to everybody to your mounted folder?

**Comment by stgraber** [comment]
Not everybody, the container's user which you can do using POSIX ACLs, but yeah, we still have no plan to alter host filesystem permissions automatically from LXD.

**Comment by techtonik** [comment]
But that user doesn't on host system, doesn't it?

**Comment by stgraber** [comment]
The uid sure does.

If you have a map of lxd:100000:65536, then uid 1000 in the container will be uid 101000 on the host, so just use uid 101000 with setfacl and it'll work fine.

**Comment by techtonik** [comment]
I see. Is there a programmatic way to get UID from container, so that the operation can be scripted?

**Comment by stgraber** [comment]
Easiest would be to look at the owner of a file under /var/lib/lxd/containers/...

**Comment by techtonik** [comment]
Interesting that if container is created, the owner is root, but after container is started, the owner is uid 100000. Also it seems that all containers share the same uid 100000. Is that intentional?
```
$ ls -la /var/lib/lxd/containers
total 36
drwxr-xr-x  6 root   root    4096 Aug 16 19:59 .
drwxr-xr-x  7 root   root    4096 Aug 16 19:59 ..
drwxr-x---+ 3 100000 100000  4096 May 27 00:29 gp
drwxr-x---+ 3 100000 100000  4096 Aug 12 08:36 gpinside
drwxr-x---+ 3 100000 100000  4096 May 26 12:37 lp
-rw-r--r--  1 root   root   10843 Aug 16 20:00 lxc-monitord.log
drwxr-xr-x+ 3 100000 100000  4096 Aug 16 19:58 u1
$ lxc list
+----------+---------+------------+------+-----------+-----------+
|   NAME   |  STATE  |    IPV4    | IPV6 | EPHEMERAL | SNAPSHOTS |
+----------+---------+------------+------+-----------+-----------+
| gp       | RUNNING | 10.0.3.100 |      | NO        | 0         |
| gpinside | STOPPED |            |      | NO        | 1         |
| lp       | STOPPED |            |      | NO        | 0         |
| u1       | RUNNING | 10.0.3.169 |      | NO        | 0         |
+----------+---------+------------+------+-----------+-----------+
```

**Comment by stgraber** [comment]
That's intentional, currently all containers share the same uid/gid map.

**Comment by techtonik** [comment]
So, let me sum up the steps. Given project directory $PDIR and container $NAME.

* [ ] run container $NAME
* [ ] lookup uid in /var/lib/lxd/containers/$NAME as $UID
* [ ] setfacl -R -m u:$UID:rwX $PDIR
* [ ] lxc config device add shareddir type=disk source=$PDIR path=~

And then $PDIR from host will be available on guest at /root/$PDIR. Is that correct? (unfortunately, there are no separate docs for `lxc config device add -h` with examples).

**Comment by stgraber** [comment]
yep, that sounds right
