### ISSUE TITLE
LXD detects rotary disks with RPM=0, this causes issues with MaaS 2.9.2 (possibly newer) as drives are mis-represented, causing tag matching failures and potential for data loss.

### ISSUE THREAD

**Issue by dandruczyk** [lxc/lxd#8721]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
 * ~# lxc info
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first instance, try: lxc launch ubuntu:18.04

config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -<REDACTED>
  certificate_fingerprint: <REDACTED>
  driver: lxc | qemu
  driver_version: 4.0.0 (devel) | 5.2.0
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-26-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: <redacted>
  server_pid: 3991722
  server_version: "4.13"
  storage: ""
  storage_version: ""

 
# Issue description
LXD is leveraged by canonical maas for it's hardware inventory portion, and LXD/LXC is failing to detect rotary disks properly,  They are reported as "RPM:0" which MaaS interprets as an SSD when it in fact is not, thuis causes downstream problems with tools that leverage maas drive tags (ssds and rotary are tagged differently) which nearly resulted in the lost of 433TB of data due to the rotary drives identified as SSD's when they in fact are not.

# Steps to reproduce
snap refresh --channel=latest/edge lxd
curl -G --unix-socket "/var/snap/lxd/common/lxd/unix.socket" "lxd/1.0/resources" 2>/dev/null | jq >/tmp/t
Investigate /tmp/t for disks and note that spinning disks have RPM: 0 instead of 5400, 7200, 10000, 15000, etc

# snippet of above commands' output

NOTE: sda is a REAL SSD,  sdaa and following drives ARE ROTATIONAL however lxd fails to gather their RPM
"storage": {
      "disks": [
        {
          "id": "sda",
          "device": "8:0",
          "model": "KINGSTON SUV5002",
          "type": "scsi",
          "read_only": false,
          "size": 240057409536,
          "removable": false,
          "numa_node": 0,
          "device_path": "pci-0000:00:1f.2-ata-1",
          "block_size": 4096,
          "firmware_version": "56RI",
          "rpm": 0,
          "serial": "50026B7682608962",
          "device_id": "wwn-0x50026b7682608962",
          "partitions": [
            {
              "id": "sda1",
              "device": "8:1",
              "read_only": false,
              "size": 1048576,
              "partition": 1
            },
            {
              "id": "sda2",
              "device": "8:2",
              "read_only": false,
              "size": 240048406528,
              "partition": 2
            }
          ]
        },
        {
          "id": "sdaa",
          "device": "65:160",
          "model": "HGST HUH721212AL",
          "type": "scsi",
          "read_only": false,
          "size": 12000138625024,
          "removable": false,
          "numa_node": 0,
          "device_path": "pci-0000:01:00.0-sas-exp0x5003048017f7ae7f-phy28-lun-0",
          "block_size": 4096,
          "firmware_version": "T3M0",
         "rpm": 0,
          "serial": "5000cca278d542e3",
          "device_id": "wwn-0x5000cca278d542e3",
          "partitions": []
        },
        {
          "id": "sdab",
          "device": "65:176",
          "model": "HGST HUH721212AL",
          "type": "scsi",
          "read_only": false,
          "size": 12000138625024,
          "removable": false,
          "numa_node": 0,
          "device_path": "pci-0000:01:00.0-sas-exp0x5003048017f7ae7f-phy29-lun-0",
          "block_size": 4096,
          "firmware_version": "T3M0",
          "rpm": 0,
          "serial": "5000cca278d55a2f",
          "device_id": "wwn-0x5000cca278d55a2f",
          "partitions": []
        },
        {
          "id": "sdac",
          "device": "65:192",
          "model": "HGST HUH721212AL",
          "type": "scsi",
          "read_only": false,
          "size": 12000138625024,
          "removable": false,
          "numa_node": 0,
          "device_path": "pci-0000:01:00.0-sas-exp0x5003048017f7ae7f-phy30-lun-0",
          "block_size": 4096,
          "firmware_version": "T3M0",
          "rpm": 0,
          "serial": "5000cca278d54aa1",
          "device_id": "wwn-0x5000cca278d54aa1",
          "partitions": []
        },
....

**Comment by stgraber** [comment]
Was already reported a few hours ago. Please do a Github issue search before filling a new issue :)
