### ISSUE TITLE
Apparmor profile for VMs uses hardcoded ovmf path

### ISSUE THREAD

**Issue by lukts30** [lxc/lxd#8722]
# Required information

 * Distribution: Arch Linux
 * The output of "lxc info": [info.txt](https://github.com/lxc/lxd/files/6393880/info.txt)
   * Storage backend in use: btrfs

# Issue description

On Arch Linux ovmf is installed under `/usr/share/edk2-ovmf/`.

The arch provided lxd.service sets `Environment=LXD_OVMF_PATH=/usr/share/ovmf/x64` and without Apparmor everything works as expected. 
But with Apparmor enabled the vm profile denies access to `/usr/share/edk2-ovmf/x64/OVMF_CODE.fd`:
```
[  205.872540] audit: type=1400 audit(1619628908.123:296): apparmor="DENIED" operation="file_lock" profile="lxd-vm-ubuntu-pod4_</var/lib/lxd>" name="/usr/share/edk2-ovmf/x64/OVMF_CODE.fd" pid=3723 comm="qemu-system-x86" requested_mask="k" denied_mask="k" fsuid=0 ouid=0
```
 
Setting `lxc config set VM1 raw.apparmor "/usr/share/edk2-ovmf/x64/OVMF_CODE.fd kr,"` or `lxc launch ubuntu:20.04 vm-tmp7 --vm -c "raw.apparmor=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd kr,"` works around but IMHO lxd should just create
an Apparmor profile that honours the **LXD_OVMF_PATH** environment variable.

https://github.com/lxc/lxd/blob/ee6eda246a08f754cc914faa7cf05dfb204dabc4/lxd/apparmor/instance_qemu.go#L39

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (` NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by lukts30** [comment]
I just tested the new release and actually I still get an access denied with an up to date Arch installation with Apparmor enabled.

Most likely an symlink & LSM issue:
`/usr/share/ovmf` is a symlink to `/usr/share/edk2-ovmf`.
The LXD_OVMF_PATH env is set to `/usr/share/ovmf/x64`.
LXD creates a profile with `/usr/share/ovmf/x64/OVMF_CODE.fd`. 
But AppArmor resolves (realpath) the symlink and treats:
`/usr/share/ovmf/x64/OVMF_CODE.fd != /usr/share/edk2-ovmf/x64/OVMF_CODE.fd`.

In my initial report I just set the raw.apparmor to the resolved symlink from apparmor denied massage and that worked.
```
[lukas@ lxd]$ ls -lah /usr/share/ovmf/x64/OVMF_CODE.fd
-rw-r--r-- 1 root root 1,9M 11. Mär 20:34 /usr/share/ovmf/x64/OVMF_CODE.fd
[lukas@ lxd]$ ls -lah /usr/share/edk2-ovmf/x64/OVMF_CODE.fd
-rw-r--r-- 1 root root 1,9M 11. Mär 20:34 /usr/share/edk2-ovmf/x64/OVMF_CODE.fd
[lukas@ lxd]$ realpath /usr/share/ovmf/x64/OVMF_CODE.fd
/usr/share/edk2-ovmf/x64/OVMF_CODE.fd
```
```
[  631.344174] audit: type=1400 audit(1620937052.590:295): apparmor="DENIED" operation="file_lock" profile="lxd-t1_</var/lib/lxd>" name="/usr/share/edk2-ovmf/x64/OVMF_CODE.fd" pid=3953 comm="qemu-system-x86" requested_mask="k" denied_mask="k" fsuid=0 ouid=0

#include <tunables/global>
profile "lxd-t1_</var/lib/lxd>" flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/base>
  #include <abstractions/consoles>
  #include <abstractions/nameservice>

  capability dac_override,
  capability dac_read_search,
  capability ipc_lock,
  capability setgid,
  capability setuid,
  capability sys_chroot,
  capability sys_resource,

  # Needed by qemu
  /dev/hugepages/**                         rw,
  /dev/kvm                                  rw,
  /dev/net/tun                              rw,
  /dev/ptmx                                 rw,
  /dev/vfio/**                              rw,
  /dev/vhost-net                            rw,
  /dev/vhost-vsock                          rw,
  /etc/ceph/**                              r,
  /run/udev/data/*                          r,
  /sys/bus/                                 r,
  /sys/bus/nd/devices/                      r,
  /sys/bus/usb/devices/                     r,
  /sys/bus/usb/devices/**                   r,
  /sys/class/                               r,
  /sys/devices/**                           r,
  /sys/module/vhost/**                      r,
  /{,usr/}bin/qemu*                         mrix,
  /usr/share/ovmf/x64/OVMF_CODE.fd              kr,
  /usr/share/qemu/**                        kr,
  /usr/share/seabios/**                     kr,
  owner @{PROC}/@{pid}/task/@{tid}/comm     rw,
  /etc/nsswitch.conf         r,
  /etc/passwd                r,
  /etc/group                 r,
  @{PROC}/version                           r,

  # Instance specific paths
  /var/log/lxd/t1/** rwk,
  /var/lib/lxd/storage-pools/main/virtual-machines/t1/** rwk,

  /var/lib/lxd/storage-pools/main/virtual-machines/t1/root.img rwk,

  # Needed for lxd fork commands
  /usr/bin/lxd mr,
  @{PROC}/@{pid}/cmdline r,
  /{etc,lib,usr/lib}/os-release r,

  # Things that we definitely don't need
  deny @{PROC}/@{pid}/cgroup r,
  deny /sys/module/apparmor/parameters/enabled r,
  deny /sys/kernel/mm/transparent_hugepage/hpage_pmd_size r,

# Entries from LD_LIBRARY_PATH

  /** mr,
}
```

**Comment by stgraber** [comment]
Doh, indeed, apparmor is rather annoying with symlinks, we need to deref the path in this case.

**Comment by stgraber** [comment]
Setting LXD_OVMF_PATH to `/usr/share/edk2-ovmf/x64/` in your case should work.

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/pull/8776
