### ISSUE TITLE
/etc/systemd/system/service.d/lxc.conf generates a lot of logs "Unknown key name 'ProtectProc' in section 'Service', ignoring."

### ISSUE THREAD

**Issue by AceSlash** [lxc/lxd#8729]
# Required information

 * Distribution: ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails: (I don't think the full lxc info is necessary here)
   * Kernel version: 5.4.0-72-generic
   * LXC version: from snap : 4.0.5
   * LXD version: lxd from snap version 4.0.5
   * Storage backend in use: ZFS

# Issue description

A new file is now added at this location {{/etc/systemd/system/service.d/lxc.conf}}. This file contains the following lines:
```
[Service]
ProtectProc=default
ProtectControlGroups=no
ProtectKernelTunables=no
```
This make other services log this:
```
Apr 30 20:25:19 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:25:19 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:25:20 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:25:20 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:25:20 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:25:20 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:25:20 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:25:20 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:25:20 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:26:11 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:26:11 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:26:12 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:26:12 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:26:12 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:26:12 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Apr 30 20:26:12 example-20 systemd[1]: /etc/systemd/system/service.d/lxc.conf:2: Unknown key name 'ProtectProc' in section 'Service', ignoring.
```
I would like to avoid to manage this file to remove this line, since for some service, this generate a lot of useless noise.

The container is running ubuntu 20.04, this is recent since other containers I created last week don't have this file.
# Steps to reproduce

 1. lxc init with ubuntu 20.04
 2. run a systemd service

**Comment by stgraber** [comment]
Tracked here https://github.com/lxc/distrobuilder/issues/427

**Comment by AceSlash** [comment]
Ok thanks, does the settings in this file make sense even with security.nesting set to true?
Currently the file content is:
```
[Service]
ProtectProc=default
ProtectControlGroups=no
ProtectKernelTunables=no
```
From https://www.freedesktop.org/software/systemd/man/systemd.exec.html , it looks like since `ProtectSystem` is available with security.nesting and it implies `ProtectControlGroups` and `ProtectKernelTunables`, this file should be removed from any container that is started with `security.nesting`.

Can you confirm?

**Comment by stgraber** [comment]
security.nesting for unprivileged containers let's you get around most of those but it can vary a bit based on the host distro/kernel and guest.

**Comment by stgraber** [comment]
As we're working to move to a systemd generator, we may eventually be able to attempt using some of those features and relax the override where needed, though initially the focus will be to avoid using unsupported systemd features.

**Comment by AceSlash** [comment]
OK, I see that this dependent on the systemd version but if I understand correctly, for an _unprivileged Ubuntu 20.04 container with security.nesting_, I'm better of removing this file, right?

**Comment by stgraber** [comment]
Yep, it's safe to remove in your case.

**Comment by AceSlash** [comment]
Thanks for the confirmation.
