### ISSUE TITLE
Support for starting LXD with degraded storage or network

### ISSUE THREAD

**Issue by yahbluez** [lxc/lxd#8730]
# Required information

 * Distribution: manjaro
 * Distribution version: 2021 05 01
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.11.16-2-MANJARO #1 SMP PREEMPT Thu Apr 22 09:53:11 UTC 2021 x86_64 
   * LXC version: 4.13
   * LXD version: 4.13
   * Storage backend in use: dir

# Issue description

lxd did not start up if a dir storage pool of a single container is missing.

I did: 
  Rebooting a system with a temporary in memory storage pool.

What happend: 
  lxd did not start and did not start any container
  lxd did not even start containers with existing storage pools.

Expected: 
   That the lxd service start.
   That lxd start every container with existing storage.
   That lxd error messages the missing storage pool. 

# Steps to reproduce

 1. lxc storage create tmp dir source=/dev/shm/tmp
 2. lxc launch images:debian/10  deb  -s tmp 
 3. reboot

# Information to attach

Nothing relevant the three steps to reproduce the bug tell you everything.

**Comment by stgraber** [comment]
It's far more complex than you make it out to be as storage pools store far more than just instances. We'd have to block any storage related startup patches, prevent starting up any instance with a storage volumes coming from that pool, prevent image updates for images that have an optimized copy in that pool, ...

That said, it's something we intend to do for both storage pools and networks, effectively tracking their state, logging a persistent warning and only preventing startup if a storage related migration patch must be applied.

But based on complexity and other things on our roadmap, this will most likely not make it until early 2022.

**Comment by yahbluez** [comment]
Thank you for your fast response. 
The typically way to use in memory storage pools is to create one, use it with an container and delete it after terminating the container. That's done by a singel script.
This time a reboot was done while the temporary  container was still running.
So i came to this issue with an not starting lxd.
I reported it because it's an issue wich could stop a whole lxd system from working because of one "little" problem.
