### ISSUE TITLE
warnings "bugs"

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#8736]
Couple of trivial things with warnings

`lxc warning show` (without a UUID) causes a `panic: runtime error: index out of range [0] with length 0`

Also should the following help message read `warning attributes` instead of `image attributes`

https://github.com/lxc/lxd/blob/4e4590ee598edd58aaa4af80385b36264101bd2e/lxc/warning.go#L71

**Comment by tomponline** [comment]
Thanks, will get these fixed.

**Comment by stgraber** [comment]
@tomponline are you doing this now? Otherwise I was planning to send a PR in a few minutes, should be very trivial.

**Comment by tomponline** [comment]
@stgraber I was going to take first thing tomoz, if you can do now that would be great thanks.
