### ISSUE TITLE
Upgrade ceph libraries in snap, ceph warning  mons are allowing insecure global_id reclaim

### ISSUE THREAD

**Issue by vvolas** [lxc/lxd#8739]
lxd 4.05
ceph:v15.2.11

with recent ceph upgrade, ceph started giving warnings:
```
andriusjurkus@universe-linux:~$ sudo ceph --status
  cluster:
    id:     4e01640b-951b-4f75-8dca-0bad4faf1b11
    health: HEALTH_WARN
            mons are allowing insecure global_id reclaim
```

After I "fixed" this and disabled insecure global reclaim in ceph cluster certain lxd operations stops working. Like lxc info, lxc list, lxc snapshot (whole container locked up) if something has snapshots. 

I think it should be enough to upgrade ceph libraries.

**Comment by stgraber** [comment]
Not a snapd issue but a snap one and there is already a config key to let you handle that.
`snap set lxd ceph.external=true` followed by `systemctl reload snap.lxd.daemon`

We're also moving to core20 (edge channels done already) which will bring in a more recent bundled ceph client.
