### ISSUE TITLE
Add `core.shutdown_timeout` as a way to override the default 5min timeout

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8755]
When LXD shuts down for an update and there are running operations, it will wait for up to 5min for those to complete before moving on. This is implemented to be nice to `lxc exec` users but it being hardcoded to 5min can sometimes be too long or too short depending on environments.

Let's add a `core.shutdown_timeout` global config option and use that to override the default 5min timeout.

**Comment by presztak** [comment]
@stgraber I can work on this as next one.
