### ISSUE TITLE
Expose database stand-by role on cluster members

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8756]
Currently cluster members that are voting members in dqlite will report `database: true` and have `database` in their roles list.
But the other 2 members which are receiving the database stream but don't get to vote are not exposed in any way.

Instead we should change so that `database: true` is also set for standby members and those should show a `database-standby` role so it's easy to keep track of what server's doing that.

This is all data we should have by peeking into the local database or in-memory hearbeat data so should be easy to incorporate in our response.

**Comment by presztak** [comment]
@stgraber Can I be assign to this one?

**Comment by stgraber** [comment]
Done!
