### ISSUE TITLE
Support HAProxy protocol header on HTTPS listener

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8757]
When LXD is being run behind a HAProxy server (common with clusters), it'd be quite useful for LXD to still capture the requestor's IP address. For that, the easiest is to add an option to specify upstream haproxy servers and if a connection comes from those, then expect the proxy header and replace the client's address with it.

As this is for `core.https_address`, we'd probably want `core.https_trusted_proxy` which takes a comma separated list of IP addresses of servers that we trust to provide the client's address through the proxy connection header.

Then in the REST API endpoint, if the connection is coming from one of those addresses, we'll read the first line of data, parse the proxy header and replace the address in the request with the extracted one (there's likely a Go package doing that already, I remember implementing this in https://github.com/nsec/askgod a while back).

**Comment by presztak** [comment]
@stgraber, Can I be assign to this one?

**Comment by stgraber** [comment]
you got it!
