### ISSUE TITLE
Add location field to /1.0 in devlxd API

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8758]
When accessing the guest API (/dev/lxd), we should add a `location` field in /1.0 to expose the name of the host the instance is running on when clustered ("none" if not clustered).

This will be particularly useful for the guests to be able to pass that to further clusters (like kubernetes) to avoid putting all of the control services on the same physical host potentially leading to broken high availability.

(For security concerns about this, devlxd can be disabled already through `security.devlxd`)

**Comment by presztak** [comment]
@stgraber Can I be assigned to this issue?

**Comment by stgraber** [comment]
Yep, done!

**Comment by presztak** [comment]
@stgraber Should we implement this for both containers and virtual machines? Because as I can see there are separate implementation of `devlxd API` for them.

**Comment by stgraber** [comment]
Yeah, we should have it for both, the logic should be near identical in both cases. The main difference is that for the VM, it's reading the data from a json file instead of being answered by the LXD daemon itself.

**Comment by presztak** [comment]
@stgraber

while testing devlxd api I was confused about one thing. `instance-data` file on vm is created when `security.devlxd` flag is set to `true` but in documentation we can find that this flag is `true` by default. Unfortunately when I run this command:

`lxc launch images:ubuntu/focal/cloud testvm --vm`

`instance-data` file is not created. I need to run this command:

`lxc launch images:ubuntu/focal/cloud testvm --vm -c security.devlxd=true`

so if security.devlxd is `true` by default shouldn't `instance-data` file be created after run first command?

**Comment by stgraber** [comment]
Yeah, that looks like a bug, I'd expect instance-data to be there by default and only be missing if the feature is specifically set to false...
