### ISSUE TITLE
make copyfile kick fewer kittens

### ISSUE THREAD

**Issue by hallyn** [lxc/lxd#877]
currently copyfile is implemented using cgo code marked with a constructor attribute, to make sure that there are no other threads yet so we can do a setns(mnt).

This is working, but we are not certain that it is guaranteed to work.

Gustavo suggested creating a new dependency for main, which itself has no dependencies, and which defines an init which does our work.  This should be guaranteed to run before any other go code.

**Comment by hallyn** [comment]
Assigned to Tycho for now, but I may do it myself (will change the assignee if i start).

**Comment by stgraber** [comment]
Let's close this. We've been running millions of tests by now and have never run into an issue with forkgetfile/forkputfile.
