### ISSUE TITLE
Windows vm doesn't start

### ISSUE THREAD

**Issue by rostalor** [lxc/lxd#8783]
kernel_version: 5.4.0-72-generic
os_name: Ubuntu
os_version: "20.04"

root@lxd1:~# lxc start win100 --console=vga
Unable to init server: Could not connect: Connection refused

(remote-viewer:4000394): Gtk-WARNING **: 10:16:48.693: cannot open display:

what can I do?

**Comment by stgraber** [comment]
Closing as it's not a LXD bug but instead related to your X11 setup and virt-viewer.

Just running `lxc start win100` should work fine. You can then try `lxc console win100 --type=vga` separately which will likely fail with the same error. This error suggests you may be using X redirection over SSH which confuses the snap setup.

If that's what you're doing, please instead remotely connect to LXD itself by running `lxc` on your local PC and adding your remote LXD server as a remote (`lxc remote add`).

**Comment by rostalor** [comment]
![image](https://user-images.githubusercontent.com/82805479/118446455-7c241a80-b711-11eb-9cef-a4a8afa12efe.png)
I didn't understand this **"If that's what you're doing, please instead remotely connect to LXD itself by running lxc on your local PC and adding your remote LXD server as a remote (lxc remote add)."**

I have connected my lxd server by mobaxterm
