### ISSUE TITLE
how do i configure lxd to use xtables instead of nftable?

### ISSUE THREAD

**Issue by lds-lds** [lxc/lxd#8792]
# Required information

 * Distribution: ubuntu
 * Distribution version: bionic
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-140-generic
   * LXC version: 4.14
   * LXD version: 4.14
   * Storage backend in use: dir

# Issue description

Hello
How to set lxd to use xtable ?

Il try ``lxc config set core.firewall: xtables``` or ```lxc config set firewall: xtables``` but this is not the correct syntax
Can someone explain to me how to do this?

**Comment by tomponline** [comment]
LXD will detect which firewall driver to use based on what is available and whether one of them is already in use by either an earlier LXD process or another application on the system.

As such you can influence which driver LXD uses by ensuring that you have iptables rules present when LXD starts *and* ensuring that there are no nftables rules present (as in mixed environments LXD will prefer to use nftables).

So you need to inspect iptables and nftables and ensure you're only using one of them:

```
sudo apt install nftables -y
sudo nft list ruleset
sudo nft flush ruleset # Only if you're happy with the removing the rules from the previous command.
sudo iptables-save # Check if you have any existing rules
sudo iptables -A INPUT # If not add a dummy rule that will be sufficient to trigger LXD's detection to consider that iptables is in use.
sudo systemctl reload snap.lxd.daemon # Reload LXD to trigger detection
```

For future reference support related questions are better suited to https://discuss.linuxcontainers.org/. Thanks

**Comment by lds-lds** [comment]
ok thanks :)
