### ISSUE TITLE
ipv4/6.address: detect if address already is used

### ISSUE THREAD

**Issue by mkg20001** [lxc/lxd#8799]
# Required information

 * Distribution: nixOS
 * Distribution version: 21.05pre-git
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version: 4.14
   * Storage backend in use:

# Issue description

When setting ipv4/6.address for a container I expect that an address already assigned to an interface cannot be used on another interface

# Steps to reproduce

```
# create test container
lxc launch images:alpine/3.13 cont1
# assign address
lxc config device add cont1 eth0 nic name=etho nictype=bridged parent=lxdbr1 ipv4.address=10.148.228.20
# create other
lxc launch images:alpine/3.13 cont2
# assign same address
lxc config device add cont2 eth0 nic name=etho nictype=bridged parent=lxdbr1 ipv4.address=10.148.228.20
```

Re-using the address leads to unpredictable behaviour that is sometimes very non-obvious, for example I had a shutdown container with the same address assigned and DHCP would sometimes not give it to the other container during renew..

I expect an error message instead of undefined behaviour

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Well, this gets complicated because if you're in a cluster, two instances with the same ipv4.address may be on different servers and so not actually conflict. The other tricky case is when copying an instance as a simple check like this would prevent any copy.

We could possibly put a startup time check to prevent two instances from running with the same configured address. I'm just not sure of the overhead needed to perform the proper check.

@tomponline what do you think?

**Comment by tomponline** [comment]
@stgraber I'm going to throw another couple of complexity issues into the mix here too:

1. We will need to differentiate between `bridged` NICs connected to managed and unmanaged networks, and really it would be preferable to not allow setting `ipv{n}.address` settings at all when connecting to unmanaged networks. This has come up a few times in the forum where people have connected to an external network and then set a static IP setting and wondered why it didn't take effect.
2. However a static IP setting is required when using `bridged` NIC's `security.ipv{n}_filtering` setting, and there is a planned feature to allow this to work when connecting to unmanaged external networks (https://github.com/lxc/lxd/issues/7477) (which then means the restriction in 1. would need to be relaxed to allow setting static IPs on unmanaged networks).

@stgraber is correct that when not using a distributed network mode (such as `bridge.mode=fan` or OVN network type) there is no such limitation on having multiple instances same the same IP defined. It may even be desirable. For example a scenario I can think of is where you have a single LXD network in a cluster that manifests itself as multiple local bridges (one on each cluster member), you could then want to expose a network service from a container onto each of the local bridges using the same IP. This would then require that you setup a container on each cluster member and assign it the *same* static IP.

Although a start time check would make sense to avoid the issues with copying that @stgraber described, its a shame to have to incur that additional cost every time the instance is started, although hopefully we can minimise that with a specialised query that only looks at instances on the local cluster member, and directly looks for the matching NIC config key.

We could potentially look at parsing the dnsmasq config files, although that isn't guaranteed to be quicker, and would be specific to that particular application.

**Comment by mkg20001** [comment]
In my particular instance the other host was shutdown, only the dnsmasq host file was written (but no active lease in dnsmasq.leases)

dnsmasq would sometimes randomly during renew give that host a new, random address. Sometimes it would work for some time again.

I'm not sure if the dnsmasq host files are written on startup or creation/modify, but this could be another place where a check might make sense.
