### ISSUE TITLE
LXD "routed" nictype containers need to be restarted after host network disconnect/reconnect

### ISSUE THREAD

**Issue by timlee81** [lxc/lxd#8805]
# Required information

 * Distribution: Ubuntu Server
 * Distribution version: 20.04.2
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-73-generic
   * LXC version:
   * LXD version: 4.14
   * Storage backend in use: zfs

# Issue description

When the host loses/regains it's network connection (unplug, replug cable), 'routed' containers can't be pinged (respond) until restarted.

# Steps to reproduce

 1. Configure a routed container
 2. Start container
 3. Disconnect / re-Connect cable
 4. Try to ping routed container IP
 5. No ping response

# Information to attach
[config_show.txt](https://github.com/lxc/lxd/files/6529605/config_show.txt)
[info_show_log.txt](https://github.com/lxc/lxd/files/6529606/info_show_log.txt)
[routed_profile.txt](https://github.com/lxc/lxd/files/6529607/routed_profile.txt)

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Yeah, that's most likely to be expected if the network management tool in use on your system flushes all routes from the device (which is a fairly common behavior).

I don't know that there is a particularly good way for LXD to handle another tool removing what it configured though...

**Comment by tomponline** [comment]
OpenVZ's `venet` NIC type (which `routed` is similar to) had the same issue. Without some process/thread/go routine continuously monitoring for changes to the routing and arp proxy tables (or for events that could trigger routing/arp table wipes) and then re-adding the static routes and arp proxy entries, there's not a lot that can be done.

**Comment by stgraber** [comment]
Yeah, going to close this one as that level of system monitoring would get very closely and also likely to never perfectly handle everything.

**Comment by timlee81** [comment]
Simple enough workaround: I added a networkd-dispatcher routable script to stop and start each routed container.
