### ISSUE TITLE
Allow setting image expiration from `lxc publish`

### ISSUE THREAD

**Issue by InsanePrawn** [lxc/lxd#8808]
Tested with LXD 4.14

While #6220/#6266 allowed the interactive `lxc image edit` to modify `expires_at`, there's currently no good way to set it from cli, especially during `lxc publish` (unless I overlooked it?)

`lxc image show ... | sed ... | lxc image edit ...` is not really a good solution for this imo :)

**Comment by stgraber** [comment]
That should be reasonably easy to do. It will need an extension on what we accept through `POST /1.0/images` but should otherwise be a pretty small change.

**Comment by stgraber** [comment]
To implement this, I suspect you'll need to:
 - Add an API extension string in shared/version/api.go and doc/api-extensions.md
 - Add a new field to the API for `ImagesPost` in shared/api/
 - Update doc/rest-api.yaml (`make update-api`)
 - Add a CLI argument in lxc/publish.go
 - Update the i18n templates for the new string (`make i18n`)
 - Add handling for this field in lxd/images.go (`imgPostInstanceInfo`)

Each of those points should be a separate commit, something like:
 - api: Add image_publish_expiry
 - shared/api: Add ExpiresAt to ImagesPost
 - doc/rest-api: Refresh swagger YAML
 - lxc/publish: Add  --expiration
 - i18n: Update translation templates
 - lxd/images: Add image expiration for instance publish

**Comment by stgraber** [comment]
From IRC:
```
18:35:07 | &lt;+stgraber&gt; | masnax: so when you publish an instance as an image, LXD calls Export() on the instance to generate the tarball. That tarball contains a metadata.yaml which includes the creation date and expiry date. So we'll need to feed the expiry to Export() so it can write the right one.
18:36:10 | &lt;+stgraber&gt; | masnax: where things get a bit trickier is that this metadata.yaml can be edited ahead of time through `lxc config metadata`. So instead of passing --expire DATE to `lxc publish`, someone may just do `lxc config metadata edit` and then `lxc publish` and expect the expiry to be set properly.
```

So the extra things we need to sort out here:
 - Pass req.ExpiresAt over to the Export() function call
 - If provided to Export(), override any existing expiry from metadata.yaml with the provided one
 - If not provided, use the one from metadata.yaml (if present), if not present default to no expiry
 - Export() will then return the correct expiry as part of its returned metadata and this can be used to feed the DB record
