### ISSUE TITLE
`publish`ing an ephemeral instance with `--force` throws etag error, then works

### ISSUE THREAD

**Issue by InsanePrawn** [lxc/lxd#8816]
# Required information

 * Distribution: Debian
 * Distribution version: 10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.19.0-14-amd64
   * LXD version: 4.14 (snap)
   * Storage backend in use: zfs (0.8.6)

# Issue description

When creating images from ephemeral instances for CI usage, the first call to `lxc publish --force` will always fail for me like so:
`Error: ETag doesn't match: c380fb1279400ae8f34c484260a143efc5fe6d840c6f88003c8af5f510624055 vs d013f6543f3120c37640d29ba3a3a03b8b3c10cf428ba52b3c03a3a6ff2fd055`
The machine will remain in shutdown state.
Repeating the command will work fine!

# Steps to reproduce

 1. Create ephemeral instance: `lxc launch -e images:debian/buster/cloud publishtestinstance`
 2. try to publish an image of it: `lxc publish publishtestinstance --force` -> fails
 3. retry: `lxc publish publishtestinstance --force` -> works

**Comment by stgraber** [comment]
Ah yeah, this is an interesting case as normally shutting down an ephemeral instance would destroy it but we obviously don't want it to happen in this case ;)

I'll take a look, it's probably a simple mistake in the CLI code.
