### ISSUE TITLE
Is there any chance to install lxd from .deb?

### ISSUE THREAD

**Issue by aTanW** [lxc/lxd#8820]
I have farm, where host OSes have no internet connection, so there is no sense to  install snap.

Currently containers are pretty static and runs under systemd-nspawn, but we deside to change schemas and now I need containers migration function.

I see, it is possible to complete that job with scripts, but why reinvent the wheel...

**Comment by StyXman** [comment]
Debian has no `lxd` package and Ubuntu's say:

```
lxd/hirsute,hirsute 1:0.9 all
  Transitional package - lxd -> snap (lxd)
```

So currently the answer is no. Maybe you can try and find the latest properly packaged `.deb` (if there ever was one; given the pkg is not in Debian points to 'never') and use its `debian` directory and pray for the best.

**Comment by stgraber** [comment]
It's possible to install snaps in offline environments using 'snap download' on an online system and transferring the resulting files to the offline system.

As for debs, for Ubuntu the last packaged version was 3.0. You can find the packaging used for that version in the lxd-pkg-ubuntu repository.

A few people have mentioned they would look at building debs in a PPA, at least for the LTS releases but so far we've not seen it actually be done. If someone does it and keeps it up to date, we'd be happy to add it to the getting started guide on the website as we have for other distros.


Closing this issue as LXD itself doesn't contain any packaging, it's just the upstream code which we release as git tag and tarballs. Packaging is always handled externally by the various distributions and packaging teams.

**Comment by tomponline** [comment]
@stgraber there is this, but I don't know how complete it is https://github.com/el-eks-di/lxd-deb

**Comment by aTanW** [comment]
Thanx for all, I'll try to build .deb(-s)

But, that looks strange - written by Ubuntu developer, software for Ubuntu cant be run in Ubuntu. 8-)
