### ISSUE TITLE
Small improvement to cluster join

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#8825]
When joining new members to a cluster, the `lxd init` process asks `Do you have a join token? (yes/no) [default=no]:` it would be nice if it could also accept the the token in addition to `yes/no`.

This is inspired by how SSH proposes adding fingerprints to ~/.ssh/known_hosts:

```
The authenticity of host 'cloud-vm04.maas.mtl.stgraber.net (<no hostip for proxy command>)' can't be established.
ECDSA key fingerprint is SHA256:UNKZfO4GZEZk+rmDnctE2l191QfVpfX1DDrxmxYneOE.
No matching host key fingerprint found in DNS.
Are you sure you want to continue connecting (yes/no/[fingerprint])? SHA256:UNKZfO4GZEZk+rmDnctE2l191QfVpfX1DDrxmxYneOE
```

So for lxd, it'd be nice to have the question shown as `Do you have a join token? (yes/no/[token]) [default=no]:`. If a token is provided, the next question (`Please provide join token:`) could be skipped.

**Comment by stgraber** [comment]
It's a bit different from SSH where SSH uses it as a way to quickly confirm that it's the same string.

The places that would be equivalent to SSH though would be:
 - lxc remote add
 - lxd init's fingerprint prompt

**Comment by simondeziel** [comment]
I agree the init question isn't about authentication as in the SSH case but it's where I got the idea from. I like your proposal for the `lxc remote add`!
