### ISSUE TITLE
lxc launch remote: does not work

### ISSUE THREAD

**Issue by rrva** [lxc/lxd#883]
launch remote: does not work.

```
$ lxc launch wily:ubuntu
Creating container...Cannot connect to unix socket at /var/lib/lxd/unix.socket Is the server running?
```

But the remote does work

```
$ lxc list wily:
+--------------------------+---------+-----------+------+-----------+-----------+
|           NAME           |  STATE  |   IPV4    | IPV6 | EPHEMERAL | SNAPSHOTS |
+--------------------------+---------+-----------+------+-----------+-----------+
| antihierarchical-tabatha | RUNNING | 10.3.0.60 |      | NO        | 0         |
+--------------------------+---------+-----------+------+-----------+-----------+

$ lxc remote list
local <unix:///var/lib/lxd/unix.socket>
wily <https://10.3.0.10:8443>
```

lxc was running on OSX, lxd on ubuntu

**Comment by stgraber** [comment]
"lxc launch wily:ubuntu" means "start the ubuntu image on the default remote", if your default remote is "local", as appears to be the case here, then you get that error.

You either need "lxc launch wily:ubuntu wily:" or use "lxc remote set-default wily" and then do "lxc launch ubuntu".

**Comment by rrva** [comment]
The help text was misleading me a bit:

```
lxc launch [remote:]<image> [remote:][<name>] [--ephemeral|-e] [--profile|-p <profile>...]
```

It looks like I should be able to use the syntax 

lxc launch remote:<image>

**Comment by stgraber** [comment]
You can, if you want to run a remote image on your local LXD as I do with our remote image server.

lxc remote add images images.linuxcontainers.org
lxc launch images:ubuntu/trusty/amd64 blah

That uses the remote image ubuntu/trusty/amd64 on my default remote which is local.
