### ISSUE TITLE
LXD 4.14 - lxc info hangs - no response on snapshot request

### ISSUE THREAD

**Issue by ninjuan11** [lxc/lxd#8835]
After upgrading to 4.14 i've encountered an error, which i cannot identify.
More details are in #8834 

System: ceph as storage backend
octopus on 15.2.13
using lxd snap 4.14 with internal ceph.

requesting informations about snapshots takes indefinitely long
`time lxc query /1.0/instances/con-00/snapshots/running --verbose --debug`
```DBUG[06-01|23:02:40] Sending request to LXD                   method=GET url=http://unix.socket/1.0/instances/con-00/snapshots/running etag=
^C

real	6m35.007s
user	0m0.028s
sys	0m0.026s
```

it is not a performance problem on the ceph side.
```
time rbd du --format json --id lxd --cluster ceph --pool ceph container_con-00@snapshot_running
warning: fast-diff map is not enabled for container_con-00. operation may be slow.
{"images":[{"name":"container_con-00","id":"175f026b8b4567","snapshot":"snapshot_initial","snapshot_id":329,"provisioned_size":100000000000,"used_size":692060160},{"name":"container_con-00","id":"175f026b8b4567","snapshot":"snapshot_running","snapshot_id":333,"provisioned_size":100000000000,"used_size":12113149952}]}

real	0m2.264s
user	0m1.566s
sys	0m1.014s
```

**Comment by ninjuan11** [comment]
update: everything regarding snapshots is completly unusable.
creating a new snapshot will permanently freeze the container, nothing will happen.

**Comment by ninjuan11** [comment]
update: problem solved.
internal ceph from the snap package is extremly outdated.

`sudo snap set lxd ceph.external=true && sudo systemctl reload snap.lxd.daemon`
fixes the issue

**Comment by tomponline** [comment]
reopening this as the original problem isnt fixed. Will close the other one with the fix.
