### ISSUE TITLE
lxc launch does not return container id

### ISSUE THREAD

**Issue by rrva** [lxc/lxd#884]
lxc launch should return the created container id, much like docker run -d does

```
lxc launch ubuntu
Creating container...done
Starting container...done
```

**Comment by rrva** [comment]
using an API like https://github.com/lxc/pylxd resolves a lot of my issues, but still the lxc command needs to become more unixy, composable so you can use it in scripts etc.

**Comment by stgraber** [comment]
I guess most people usually pass a container name, but yeah, printing the name would be fine.
