### ISSUE TITLE
Move remaining iproute calls to ip package

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8857]
A new `ip` package was introduced a little while ago to centralize all `ip` calls, but iproute also ships a few more tools like `bridge`, `tc`, `ss`, `devlink`, ... which we also ought to have the package cover.

Looking around we have:
 - `lxd/device/nic_sriov.go` that uses `ip` directly and should be using the package instead
 - `lxd/device/nic_bridged.go` that uses `bridge` directly
 - `lxd/device/proxy.go` that uses `bridge` directly
 - `lxd/device/device_utils_network.go` that uses `tc` directly

Each of those should be looked at and suitable functions added to the `ip` package before replacing the existing call sites to use the new functions.

**Comment by presztak** [comment]
@stgraber Can I take also this?

**Comment by stgraber** [comment]
Of course, done!
