### ISSUE TITLE
Retry failed instance startup when auto-started

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8858]
We've seen a few times where LXD fails to autostart some instances because of network/storage type issues.
It'd be good to retry startup up to 3 times waiting 5s or so in between tries.

If things still fail, then a persistent warning should be added using our new warnings API so the user can easily see what happened.

**Comment by zakufish** [comment]
Hi @stgraber , may I take this one?

**Comment by stgraber** [comment]
That'd be great! Assigned it to you!

**Comment by zakufish** [comment]
HI @stgraber , I've made a pull request. However, I am new to this repo, and I am having some confusions regarding using the newest warning API to raise warnings.

Is there an existing sample that I could reference from?
