### ISSUE TITLE
Improve `lxd init` ordering for cluster token

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#8860]
When running `lxd init` to join a cluster, we're currently asking for both the local address and local server hostname before asking for the token. But when joining with a token, the joining node doesn't get to chose its name so this question is redundant in that case.

We should probably change the flow to ask for the token first when joining a cluster, then if provided, the hostname question should be skipped and the hostname inside the token be used instead.

**Comment by marsblkm** [comment]
Hi @stgraber can I take this?

**Comment by stgraber** [comment]
Done!

**Comment by tomponline** [comment]
Ah originally when adding cluster token feature we discussed using the hostname in the token to validate that it was being used for the right host so I thought we would still need to ask the user what their intended hostname was. Although making the join process easier makes sense too.

**Comment by stgraber** [comment]
Yeah, the shorter process should be nicer.

**Comment by marsblkm** [comment]
> Ah originally when adding cluster token feature we discussed using the hostname in the token to validate that it was being used for the right host so I thought we would still need to ask the user what their intended hostname was. Although making the join process easier makes sense too.

Just want to double check if I understand this correctly:
Do we still want to ask user what their intended hostname is for validation purpose even though user is trying to join with a token?

**Comment by stgraber** [comment]
No, if they have provided a token, we should only ask for the listen address and skip the rest.

**Comment by stgraber** [comment]
Currently we have:
 - Would you like clustering
 - What name
 - What IP address
 - Are you joining
 - Do you have a token
 - Alternative joining method

I think the main change we want here is to move the "What name" question to happen only if no token was provided, so moving it to just before "IP address or FQDN of an existing cluster node".

**Comment by marsblkm** [comment]
> Currently we have:
> 
> * Would you like clustering
> * What name
> * What IP address
> * Are you joining
> * Do you have a token
> * Alternative joining method
> 
> I think the main change we want here is to move the "What name" question to happen only if no token was provided, so moving it to just before "IP address or FQDN of an existing cluster node".

Got it. Thanks for clarifying! Will raise the pr soon

**Comment by stgraber** [comment]
Thanks!
