### ISSUE TITLE
IP address not being assigned to containers

### ISSUE THREAD

**Issue by trombonebuster** [lxc/lxd#8878]
Lxd isn't assigning IPv4 or IPv6 to my containers. When I look at lxd.log, I get the following error - `Failed enabling VLAN filtering on bridge \"lxdbr0\": open /sys/class/net/lxdbr0/bridge/vlan_filtering: permission denied`
![Screenshot from 2021-06-09 14-03-39](https://user-images.githubusercontent.com/69058128/121414533-5a8f0b00-c92c-11eb-932a-41212d7c1c00.png)

**Comment by stgraber** [comment]
What LXD version is that, on what distribution, with what kernel?

We normally like issues to follow the template that Github shows you so we don't need to ask all of those questions ;)

**Comment by trombonebuster** [comment]
# Required information

 * Distribution: 
 * Distribution version:
 * The output of "lxc info" or if that fails:
   root@B020121-fc102f4:~# lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - aarch64
  - armv7l
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICHzCCAaWgAwIBAgIRAI0Widh1TSJRqYfcK75M6gAwCgYIKoZIzj0EAwMwPTEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEdMBsGA1UEAwwUcm9vdEBCMDIw
    MTIxLWZjMTAyZjQwHhcNMjEwNjA5MjAwNDI4WhcNMzEwNjA3MjAwNDI4WjA9MRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMR0wGwYDVQQDDBRyb290QEIwMjAx
    MjEtZmMxMDJmNDB2MBAGByqGSM49AgEGBSuBBAAiA2IABC7Zlyf4cmMbinxlFnmp
    sCSrBNbBX/LHVkab6mZ2duVhY6ws01oEyhFKOklPUEQFTTs9lgIVjMhiaNPGQcuw
    MRKCTWlZiccMReJadBrILkiIThDhh44mxr/JsYt4j/fuLaNpMGcwDgYDVR0PAQH/
    BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwMgYDVR0R
    BCswKYIPQjAyMDEyMS1mYzEwMmY0hwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMAoG
    CCqGSM49BAMDA2gAMGUCMB3loNMSAGv37iyUF4EtAp6lbtiFGcoGc5sJigENA/J8
    fzazH7QbpmMiT8PnoSbmnAIxANoT7tZMFMWmF6ZChT1sIBNa/fhHetEmLcnqsvI2
    foGS+r6Ar9M8SHIPQpE8WsORpA==
    -----END CERTIFICATE-----
  certificate_fingerprint: 6a8e4ad6b64c757a45b9d9860e230e037ed88a6c572bb6fa86486600f825bfb4
  driver: lxc | qemu
  driver_version: 4.0.9 | 5.2.0
  firewall: xtables
  kernel: Linux
  kernel_architecture: aarch64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "false"
  kernel_version: 4.4.154
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "false"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "18.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: B020121-fc102f4
  server_pid: 27094
  server_version: "4.15"
  storage: dir
  storage_version: "1"


# Issue description

IP addresses are not being assigned to containers.

# Steps to reproduce

 1. lxd init --auto  (creates bridge lxdbr0)
 2. lxc list

**Comment by trombonebuster** [comment]
I'm able to get an ipv4 address temporarily if I run `lxc config device add test  eth0 nic name=eth0 nictype=bridged parent=lxbr0`, but if the container is restarted, i lose the ipv4

**Comment by stgraber** [comment]
What Linux distribution and release is this?

Your kernel is showing as 4.4.154 and the reported distro is Ubuntu 18.04, but that seems quite unlikely as this isn't a kernel that ever shipped with Ubuntu 18.04 so that reported distro may just be the snap not knowing any better.

**Comment by trombonebuster** [comment]
I actually just solved the problem. I forgot to restart after setting security.privileged true. I'm having a whole new issue now and that's that the docker service won't run inside the container even with security.nesting set to true.

**Comment by stgraber** [comment]
@trombonebuster any more details on what's causing docker to fail?

We actually have daily tests for docker in LXD containers so AFAICT there's nothing obviously broken:
https://jenkins.linuxcontainers.org/job/lxd-test-docker/

**Comment by trombonebuster** [comment]
Sorry for taking so long to get back to you. I found a fix shortly after talking to you last. I had to do the following to get docker running in the container:
`               apt-get install -y cgroupfs-mount
                service docker stop
		service containerd stop
		cgroupfs-umount
		cgroupfs-mount
		service containerd start
		service docker start`

We suspect our issues with lxd have been due to using a very old kernel, which is due to a compatibility issue with the boards we are using. I could only get internet to the containers by setting security.privilidged true.

**Comment by stgraber** [comment]
What are you running in that container as far as distro?
Normally anything that's systemd based will not need cgroupfs-mount but maybe you're using something different?

**Comment by trombonebuster** [comment]
We are running ubuntu:18.04 . The issue we are having now is that our download speeds are 30mbps inside of the container with the host downolad speed being 900-1000 mbps. Any idea what might be causing this? Thanks for any insight!

**Comment by stgraber** [comment]
Hmm, this shouldn't really be a thing unless you've configured a bandwidth limit. I commonly run containers on 10Gb/s link and they can easily saturate that. We even recently tested containers on 100Gb/s links and while those struggle a bit, they could still do 85Gb/s or so.

If I were you, I'd probably start eliminating variables and run a bunch of iperf3 tests between your container and its host, then between two containers on the same machine, ... to see exactly where the issue appears.

**Comment by trombonebuster** [comment]
Thanks for the response. Yea our team is running iperf3 tests now actually to try and find the culprit.

**Comment by drscrewdriver** [comment]
![image](https://user-images.githubusercontent.com/19632018/123236696-9bcc1100-d50f-11eb-9f0e-eefeb92707dc.png)
Things go wired after update Linux kernels too. My cgoup fs is partly mounted.  lxd service is bootup while couldn't find some cgroup settings, and ipv4 dhcpclient doesn't work in containers. After lxd downgrade to 4.12 the virtual net port show with patten like veth0bbc0d57@if43 instead of eth*@*.
I'm using manjaro a kind of archlinux , so cgroupfs-mount is available in the same name but I do get cgroupfs-mount command in my roblematic system . maybe try it out later, or build a ubuntu virtsystem to find the difference.

**Comment by stgraber** [comment]
Going to close this issue as it's looking like a weird pile up of different issues with no actual sign of a LXD bug so far :)
We prefer to have one issue per actual LXD problem so we can track them down and fix them.

For discussions and user support, https://discuss.linuxcontainers.org tends to be a better place for it.

@drscrewdriver for your issue, my guess is that because you're running on a very modern distro, LXD is using nft for firewalling, nft does not support udp checksum filling and so dhclient will fail. Most other DHCP clients properly handle UDP checksums and will work fine. As you're running on a modern systemd based system, you definitely should not install or run cgroupfs-mount. cgroupfs-mount is meant for systems that are not running systemd and so lack a cgroup mounting mechanism.

Your cgroup tree isn't partly mounted, it's simply that you're running on a very modern distribution which has done away with cgroup1 and is using cgroup2 now. This can come with quite a few changes in behavior for the software running on your system.
