### ISSUE TITLE
QEMU dependency check for creating VMs

### ISSUE THREAD

**Issue by jamielsharief** [lxc/lxd#8899]
I was trying to check to see if a host supports virtual machines or not using the HOST API call, on the host in a parallels VM it still reports QEMU and virtual-machine despite it not going to work. Can we added some validation here and some way to identify properly if this is supported.

```
jsharief@ubuntu-zfs:~$ lxc launch images:ubuntu/focal test --vm
Creating test
Starting test                                 
Error: Failed to run: forklimits limit=memlock:unlimited:unlimited -- /snap/lxd/20330/bin/qemu-system-aarch64 -S -name test -uuid 73537b0e-e93d-4a37-9988-3e3d022da6c4 -daemonize -cpu host -nographic -serial chardev:console -nodefaults -no-reboot -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=deny,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/test/qemu.conf -spice unix=on,disable-ticketing=on,addr=/var/snap/lxd/common/lxd/logs/test/qemu.spice -pidfile /var/snap/lxd/common/lxd/logs/test/qemu.pid -D /var/snap/lxd/common/lxd/logs/test/qemu.log -chroot /var/snap/lxd/common/lxd/virtual-machines/test -smbios type=2,manufacturer=Canonical Ltd.,product=LXD -runas lxd: char device redirected to /dev/pts/8 (label console)
: Process exited with a non-zero value
Try `lxc info --show-log local:test` for more info
jsharief@ubuntu-zfs:~$ lxc info --show-log local:test
Name: test
Location: none
Remote: unix://
Architecture: aarch64
Created: 2021/06/16 14:46 UTC
Status: Stopped
Type: virtual-machine
Profiles: default

Log:

Could not access KVM kernel module: No such file or directory
qemu-system-aarch64: failed to initialize kvm: No such file or directory
````

**Comment by stgraber** [comment]
Yeah, we can probably look for /dev/kvm which is pretty much what qemu seems to hit.

**Comment by stgraber** [comment]
@tomponline want to take care of this one? We probably want the driver info check to validate /dev/kvm and make sure we don't allow using VMs if we don't have a functional qemu (we may already have that check in place).

**Comment by tomponline** [comment]
@stgraber will do

**Comment by jamielsharief** [comment]
On the subject of validation, one thing would be really great, when copying instances to different servers or restoring a backup from a tar.gz (if i remember correctly), a quick check of the free space available prior to carrying out the operation, the amount of times things gone horribly wrong because the free space available was less than needed despite having more than sufficient storage.

**Comment by tomponline** [comment]
> On the subject of validation, one thing would be really great, when copying instances to different servers or restoring a backup from a tar.gz (if i remember correctly), a quick check of the free space available prior to carrying out the operation, the amount of times things gone horribly wrong because the free space available was less than needed despite having more than sufficient storage.

Its best not to conflate issues as when this one gets closed so will the discussion. Please can you open a new issue or forum post at https://discuss.linuxcontainers.org/. Thanks

**Comment by jamielsharief** [comment]
Sorry

**Comment by tomponline** [comment]
> Sorry

No worries :)

**Comment by tomponline** [comment]
> in a parallels VM it still reports QEMU and virtual-machine

@jamielsharief what did you mean by this btw, what is "it" in this context?

**Comment by jamielsharief** [comment]
If i create a VM in Parallels desktop, I can't create virtual machines in this VM, but the info shows those drivers (I thought since it does not support then it should not show).

**Comment by tomponline** [comment]
> Sorry what i was trying to say is in VMs created by Parallels, i cant create virtual machines with LXD. But the info was showing this driver was available - if that is what is it is for.

Great thanks, I suspected it was that, but wanted to make sure.

**Comment by jamielsharief** [comment]
Can information wether the host supports KVM added to the endpoint "", this is important when migrating VMs between hosts, if the other host does not support it, then it will not run the other end, and if they did a move, then the original would have been deleted.

**Comment by tomponline** [comment]
> endpoint ""

what is "endpoint """?

**Comment by jamielsharief** [comment]
![image](https://user-images.githubusercontent.com/20553479/122556657-12629d80-d03c-11eb-9ad1-202f1c5f2105.png)

**Comment by tomponline** [comment]
@jamielsharief Ah that is endpoint `/1.0` yes, it is being addressed in PR https://github.com/lxc/lxd/pull/8919

**Comment by jamielsharief** [comment]
My bad, i saw you were making a commit, and i only saw error handling. Sorry.

**Comment by tomponline** [comment]
@jamielsharief to confirm, inside your VM you don't have a `/dev/kvm` path present right?

**Comment by jamielsharief** [comment]
> /dev/kvm

Sorry for the late reply, i did not see this. Probably too late now. 

![image](https://user-images.githubusercontent.com/20553479/122595642-0e994000-d069-11eb-8704-d2ba935ce8db.png)

**Comment by tomponline** [comment]
> > /dev/kvm
> 
> Sorry for the late reply, i did not see this. Probably too late now.
> 
> ![image](https://user-images.githubusercontent.com/20553479/122595642-0e994000-d069-11eb-8704-d2ba935ce8db.png)

Thats good to hear, just wanted to check our assumptions about what we would need to detect for lack of KVM support.

**Comment by jamielsharief** [comment]
@stgraber Will this and related features (ie. querying host to see if this feature is available) get back ported to stable branch? If so what sort of timeline should I expect this this to show, just asking as i am not familiar with the LXD release cycle etc.

**Comment by stgraber** [comment]
That will get backported to 4.0, next release should be in 2-3 weeks I think.
