### ISSUE TITLE
Duplicate warnings

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#8902]
Ive some how ended up in the spot where I have duplicate warnings, this might be a problem if continues to grow in the background

version 4.15

```
lxc warning list
+--------------------------------------+-------------------------------------------------+--------+----------+-------+---------+----------+------------------------------+
|                 UUID                 |                      TYPE                       | STATUS | SEVERITY | COUNT | PROJECT | LOCATION |          LAST SEEN           |
+--------------------------------------+-------------------------------------------------+--------+----------+-------+---------+----------+------------------------------+
| 1f630b3d-f958-4981-a278-d114ac607049 | Couldn't find the CGroup memory swap accounting | NEW    | LOW      | 21    |         | none     | Jun 16, 2021 at 9:50am (UTC) |
+--------------------------------------+-------------------------------------------------+--------+----------+-------+---------+----------+------------------------------+
| 11e90354-47cd-409d-8668-0b35ebd4201f | Couldn't find the CGroup memory swap accounting | NEW    | LOW      | 15    |         |          | Jun 2, 2021 at 5:32pm (UTC)  |
+--------------------------------------+-------------------------------------------------+--------+----------+-------+---------+----------+------------------------------+
| 74677b01-7612-46b3-924e-3c077ade0b78 | Couldn't find the CGroup blkio.weight           | NEW    | LOW      | 21    |         | none     | Jun 16, 2021 at 9:50am (UTC) |
+--------------------------------------+-------------------------------------------------+--------+----------+-------+---------+----------+------------------------------+
| da9782bd-d7a8-4f96-a673-c2ad7479af2d | Couldn't find the CGroup blkio.weight           | NEW    | LOW      | 15    |         |          | Jun 2, 2021 at 5:32pm (UTC)  |
+--------------------------------------+-------------------------------------------------+--------+----------+-------+---------+----------+------------------------------+
```

**Comment by monstermunchkin** [comment]
Is this a clustered environment?

**Comment by turtle0x1** [comment]
Nope

**Comment by monstermunchkin** [comment]
There was a code change around June 2nd which resulted in "none" being displayed instead of an empty string. This is a bug, as it needs to display an empty string in non-clustered environments.

**Comment by tomponline** [comment]
@monstermunchkin I'm on my phone so haven't been able to review this in detail, but are you proposing rolling back that change? I'd be keen not to so we don't start storing node name inconsistently between different tables in the db. Perhaps a patch to fix historical problem rows might be a solution?

**Comment by monstermunchkin** [comment]
@tomponline No, the change will not be reverted. I've just looked at the `lxc ls` command which only displays the location in a clustered environment. We should do the same for `lxc warnings`. Also, having `none` as the location in non-clustered environments is fine.

What we could do is write a patch which removes all entries which have an empty location.

Also, is there any reason we don't clear all warnings on shutdown?

**Comment by stgraber** [comment]
We don't clear all warnings on shutdown because some things keep running (networks, instances, ...) even though LXD itself is being shutdown for restart.

**Comment by tomponline** [comment]
@monstermunchkin ok thanks for the clarification.

So are we thinking that @turtle0x1 has an old warning from before we started populating the non-clustered node name with "none", which means the system now has both the old and current duplicate warnings.

Don't we delete warnings on start up, in that case, won't a reload of lxd clear the warnings and only the current warnings will get recreated?

**Comment by tomponline** [comment]
>  I've just looked at the `lxc ls` command which only displays the location in a clustered environment

Makes sense, but does that just "paper over" the issue of the duplicate warnings?

**Comment by monstermunchkin** [comment]
> So are we thinking that @turtle0x1 has an old warning from before we started populating the non-clustered node name with "none", which means the system now has both the old and current duplicate warnings.

Exactly.

> Don't we delete warnings on start up, in that case, won't a reload of lxd clear the warnings and only the current warnings will get recreated?

Apparently not. I guess we should clear some warnings though, e.g. the cgroup warnings.

**Comment by tomponline** [comment]
Right got you.

It feels like this part https://github.com/lxc/lxd/blob/master/lxd/daemon.go#L1273-L1294 is not clearing the duplicates because it does a comparison on warning type code (and the warning with the none node name is then allowing the warning with the empty node name to remain because their type codes match).

**Comment by tomponline** [comment]
@monstermunchkin probably a manual `lxd sql` command to remove the dupes in this case would suffice, as it shouldn't happen again in the future.

**Comment by monstermunchkin** [comment]
The manual command would be:

`lxd sql global 'delete from warnings where node_id is null'`

We probably should write a patch for that as most users will have duplicate warnings.
