### ISSUE TITLE
Validate instance config on a per-instance-type basis

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#8912]
Currently both container and VM config is validated via `instance.ValidConfig()` which doesn't apply instance type specific validation.

As such it is possible to set container-only config keys on a VM, e.g. `lxc config set v1 security.nesting=true`.

**Comment by stgraber** [comment]
Ah yeah, we should fix that. The only case where we need this to still succeed is when it comes from a profile as profiles can be shared.

**Comment by my5t3ry** [comment]
Can i try  to solve this one?

**Comment by tomponline** [comment]
@my5t3ry Thanks!
