### ISSUE TITLE
assigned IP changed after creation copy of container

### ISSUE THREAD

**Issue by skyxx** [lxc/lxd#8921]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
  driver: qemu | lxc
  driver_version: 5.2.0 | 4.0.9
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-73-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: server1
  server_pid: 1398
  server_version: 4.0.6
  storage: btrfs
  storage_version: 4.15.1

# Issue description

After creating new container2 as copy from running container1 snapshot the running container IP is changed, not immediately but after 1hour.
New created container2 is created as STOPPED , both have configured same IP but it shouldnt change IP of running container.

I try fix it by edit config IP new and original container but it is not work well as original contaner is not able get/set old IP. 
Maybe restart of dnsmaq or LXD will help i dont try it.

# Steps to reproduce

 1. lxc config device add contaner1 eth0 nic name=etho nictype=bridged parent=lxdbr0 ipv4.address=10.1.1.20
 2. lxc snapshot contaner1 forcopy
 3. lxc copy contaner1/forcopy container2

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
@tomponline thoughts on this one?

We obviously must make the copy succeed as a snapshot is immutable but we also don't want to confuse dnsmasq too much.
dnsmasq doesn't seem to tolerate two machines with the same static lease and then goes on to give a dynamic one which the container can then renew later on, causing the described issue.

I can think of a couple of ways out of this:
 - When using a managed network, don't allow two instances to have the same static lease on the same node. This would force the use of `lxc copy -d` to override the `ipv4.address` field when copying from a snapshot.
 - Move static lease handling to instance startup, updating dnsmasq then and ensuring that we never have two running instances with the same address.

In theory the second sounds better as it still allows for easy copy of instances and instance snapshots, but it may also end up being a bit racy and odd to implement.

**Comment by tomponline** [comment]
@stgraber this functionality is currently provided by the `bridged` NIC driver's `Add()` function:

https://github.com/lxc/lxd/blob/master/lxd/device/nic_bridged.go#L232-L240

So we would need to ensure that we don't generate the static lease file at add time, and instead at start time (and important remove it at stop time).

This is unfortunately pretty inefficient as it would require reloading dnsmasq when adding/removing lease files, which would impact on the speed we can launch containers, as well as potentially impacting on the service provided by dnsmasq.

For those reasons I would prefer the first option of validating and preventing duplicate IPs being used in LXD's config.

**Comment by stgraber** [comment]
@tomponline yeah, I guess we should setup validation then.

**Comment by tomponline** [comment]
This issue is pretty similar to #8799

**Comment by stgraber** [comment]
Indeed

**Comment by stgraber** [comment]
Probably ought to also validate that we don't have duplicate hwaddr while we're at it :)

**Comment by tomponline** [comment]
> Probably ought to also validate that we don't have duplicate hwaddr while we're at it :)

Good idea. I'm also working on enforcing the same checks we have when using `network=<managed bridged>` to `parent=<bridge>` where the bridge name matches a managed bridge.
