### ISSUE TITLE
"lxc network get lxdbr0 dns.domain"  returns nothing if default value is not changed

### ISSUE THREAD

**Issue by yahbluez** [lxc/lxd#8922]
# Required information

 * Distribution: manjaro  x86_64, ubuntu 20.04.02  LTS aarch64
 
   * Kernel version: 5.11.22 + 5.4.0
   * LXC version: 4.15 + 4.0.6
   * LXD version: 4.15 + 4.0.6
   * Storage backend in use: dir btrfs

# Issue description

The cmd: 

**lxc network get lxbr0 dns.domain**

returns not the default dns domain: "lxd"

If i set the dns.domain to some other value the command above returns the value.

Expected:

To get the correct value for the key "dns.domain"

# Steps to reproduce

 1. install lxd with everything default
 2. run the cmd
 3. see the bug

# remarks

It would be very nice and use full to be able to get all <keys> or the whole <key>=<value> store / dictionary / json of a command.

something like

lxd network keys lxdbr0 

which gives all keys from the object "lxdbr0"

best regards
fridolin

**Comment by stgraber** [comment]
This isn't a bug but is just part of how the LXD API works. The API shows you the configuration keys that you have set, not those that you've not set and are therefore using the default value.

This is a pretty common pattern in such REST API based services and not something we intend to change.

All config keys as well as their default values are included in our documentation.
https://linuxcontainers.org/lxd/docs/master/
