### ISSUE TITLE
`lxc config sets core.trust_password bar` should not return 0

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#8927]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * lxd: 4.15  (snap 20806)

# Issue description

`lxc config sets core.trust_password bar` returns 0 and with a help message:

```
$ lxc config sets core.trust_password bar
Description:
  Manage instance and server configuration options

Usage:
  lxc config [command]
...
$ echo $?
0
```

The action `config sets` is not a valid one, it should have been `config set` (no `s`). On such error, `lxc` should return an error code != 0.

**Comment by masnax** [comment]
This actually exists with every non-top-level command! Seems to be a bug/oversight with cobra itself, as mentioned [here.](https://github.com/spf13/cobra/issues/706)

Workarounds are pretty hacky, and accessing the underlying error overwrites the default usage function, so we would have to write one from scratch ourselves....

**Comment by stgraber** [comment]
I've commented on the upstream issue to try and make them look into it again as well as to have me be notified of any changes.
For now, while I don't like the usage being wrong, this feels better than having invalid command succeed.

So can you work on applying this pattern to all commands that have sub-commands?

```patch
diff --git a/lxc/config.go b/lxc/config.go
index 9e154e88e..f70ffe485 100644
--- a/lxc/config.go
+++ b/lxc/config.go
@@ -29,6 +29,8 @@ func (c *cmdConfig) Command() *cobra.Command {
        cmd.Short = i18n.G("Manage instance and server configuration options")
        cmd.Long = cli.FormatSection(i18n.G("Description"), i18n.G(
                `Manage instance and server configuration options`))
+       cmd.Args = cobra.NoArgs
+       cmd.Run = subcommandRun
 
        // Device
        configDeviceCmd := cmdConfigDevice{global: c.global, config: c}
diff --git a/lxc/main.go b/lxc/main.go
index bf8571176..1248c4155 100644
--- a/lxc/main.go
+++ b/lxc/main.go
@@ -261,6 +261,10 @@ To easily setup a local LXD server in a virtual machine, consider using: https:/
        }
 }
 
+func subcommandRun(cmd *cobra.Command, args []string) {
+       cmd.Usage()
+}
+
 func (c *cmdGlobal) PreRun(cmd *cobra.Command, args []string) error {
        var err error
 
```

It appears to conserve the expected behavior for say `lxc config` (minus the broken usage) and fixes `lxc config blah`.
