### ISSUE TITLE
LXC overzealous localization: fails on `profile` command, wants `Profil` instead

### ISSUE THREAD

**Issue by c-lipka** [lxc/lxd#8934]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 LTE (WSL, German localization)
 * The output of "lxc info": [lxc-info.txt](https://github.com/lxc/lxd/files/6696345/lxc-info.txt)

# Issue description

Running `do-release-upgrade` to upgrade WSL from Ubuntu 16.04 to 18.04. While installing `lxd`, got a message saying something like this:
~~~
Old bridge configuration detected in /etc/default/lxd-bridge, upgrading
Unsetting deprecated profile options
Error: unknown command "profile" for "lxc"

Did you mean this?
        Profil

Run 'lxc --help' for usage.
~~~

Given that I'm running a German installation of Windows, and WSL is also partially localized, and knowing that `Profil` is the German word for `profile`, at this point I'm already suspecting that some overzealous git localized lxc's commands.

Indeed, running `lxc --help` reveals the extent of the catastrophe: About a third of lxc's commands are indeed localized (with the description of one of them oddly enough being among the few command descriptions that haven't been localized), breaking the upgrade process and presumably plenty of other stuff left and right:

~~~
Beschreibung:
  Command line client for LXD

  All of LXD's features can be driven through the various commands below.
  For help with any of those, simply call them with --help.

Usage:
  lxc [command]

Available Commands:
  Abbild        Abbilder verwalten
  Alias         Befehlsaliase verwalten
  Datei         Dateien in Containern verwalten
  Konfiguration Container- und Serverkonfigurationsoptionen verwalten
  Netzwerk      Container verwalten und zu Netzwerken hinzufügen
  Operation     Hintergrundoperationen auflisten, zeigen und löschen
  Profil        Profile verwalten
  Speicher      Speicherpools und Speicherdatenträger verwalten
  Version       Show local and remote versions
  cluster       Cluster-Mitglieder verwalten
  console       Herunterfahren des Containers erzwingen
  copy          Copy containers within or in between LXD instances
  delete        Container und Snapshots löschen
  exec          Befehle in Containern ausführen
  help          Help about any command
  info          Container- oder Serverinformationen anzeigen
  launch        Container vom Abbild erstellen und starten
  list          Container auflisten
  move          Verschiebe Container innerhalb oder zwischen LXD-Instanzen
  publish       Container als Bilder veröffentlichen
  remote        Die Liste der Remoteserver verwalten
  rename        Container und Snapshots umbenennen
  restart       Container neustarten
  restore       Restore containers from snapshots
  snapshot      Create container snapshots
  start         Container starten
  stop          Container stoppen

Flags:
      --all           Weniger gewöhnliche Befehle anzeigen
      --debug         Alle Debug-Nachrichten anzeigen
      --force-local   Force using the local unix socket
  -h, --help          Hilfe ausgeben
  -v, --verbose       Alle Informationsnachrichten anzeigen
      --version       Versionsnummer ausgeben

Use "lxc [command] --help" for more information about a command.
~~~

# Steps to reproduce

 1. (??? - probably get your hands on any Ubuntu 18.04 set to German language - ???)
 2. try running `lxc profile` with whatever parameter that may expect

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Hi,

We fixed this issue quite a while ago actually :)
You're still hitting this because you're using Ubuntu 18.04 with the old LXD 3.0.x which is now in the security-fix only part of its support life.

LXD 4.0 and higher do not suffer from this issue.
