### ISSUE TITLE
Storage pool / volume storage space warning

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#8946]
Could we have a warning when a storage pool ( / volume) runs low on space? Or are warnings more for "low level" issues?

**Comment by stgraber** [comment]
Currently they're mostly for things that LXD itself is aware of. LXD doesn't monitor disk usage itself so introducing a warning for this would require us to have a scheduled task checking each storage pool.

Then we'd likely get similar requests for cpu, memory, i/o, ...

Currently I think this kind of thing is better handled through dedicated monitoring and alerting tools such as node-exporter or telegraf with monitoring and alerts done in something like grafana.

We actually have more work on this kind of integration planned in the near future where we'll be adding metric targets to LXD directly which can then be scraped by prometheus.

**Comment by turtle0x1** [comment]
I assumed that might be the case, feel free to close!

My only thoughts with storage is that you throw what I assume is handle-able exception when there is no storage space so it could trigger a warning. I suppose the warning couldn't clear itself so probably just annoying.

**Comment by stgraber** [comment]
Yeah, we'd still need built-in monitoring logic to clear the warning. Issuing the warning when we hit an out of space error may also be tricky as we use a lot of tools which all of their own custom return codes or errors for this...
