### ISSUE TITLE
Cant copy lxd container in ceph due to fs mishap

### ISSUE THREAD

**Issue by vvolas** [lxc/lxd#8952]
* Distribution: ubuntu 18
   * LXD version: 4.0.6
   * Storage backend in use: ceph

This is not with all containers just few, it seems that container have stored fs type somewhere wrongly. Container might have been converted by copying from one pool to another from ext4 to xfs because fstab did have ext4( somehow still booted).

lxc copy unimall-dev/snap0 unimall-devcopy --target neutron-star
Error: Create instance from copy: Failed to mount "/dev/rbd3" on "/var/snap/lxd/common/lxd/storage-pools/ceph-lxd/containers/unimall-devcopy" using "ext4": invalid argument

` lxc storage volume show ceph-lxd container/unimall-dev
config:
  block.filesystem: xfs
  block.mount_options: discard
  size: 35GB
description: ""
name: unimall-dev
type: container
used_by:
- /1.0/instances/unimall-dev
location: ""
content_type: filesystem
`

`lxc copy unimall-dev unimall-devcopy --target neutron-star
t=2021-06-28T05:29:08+0000 lvl=dbug msg="New event listener: 60a54907-79ca-4401-ac65-cd6c15f98976"
t=2021-06-28T05:29:08+0000 lvl=dbug msg=Handling ip=@ method=POST protocol=unix url="/1.0/instances?target=neutron-star" username=uni058
t=2021-06-28T05:29:08+0000 lvl=dbug msg="\n\t{\n\t\t\"architecture\": \"x86_64\",\n\t\t\"config\": {\n\t\t\t\"boot.autostart\": \"false\",\n\t\t\t\"image.architecture\": \"amd64\",\n\t\t\t\"image.description\": \"ubuntu 18.04 LTS amd64 (release) (20200519.1)\",\n\t\t\t\"image.label\": \"release\",\n\t\t\t\"image.os\": \"ubuntu\",\n\t\t\t\"image.release\": \"bionic\",\n\t\t\t\"image.serial\": \"20200519.1\",\n\t\t\t\"image.version\": \"18.04\",\n\t\t\t\"volatile.base_image\": \"70d3dcaabcffb1aa1644d0ce866efcb141742179e94ad72aefb8d3502338a71f\"\n\t\t},\n\t\t\"devices\": {\n\t\t\t\"root\": {\n\t\t\t\t\"path\": \"/\",\n\t\t\t\t\"pool\": \"ceph-lxd\",\n\t\t\t\t\"size\": \"36GB\",\n\t\t\t\t\"type\": \"disk\"\n\t\t\t}\n\t\t},\n\t\t\"ephemeral\": false,\n\t\t\"profiles\": [\n\t\t\t\"ceph-ssd\"\n\t\t],\n\t\t\"stateful\": false,\n\t\t\"description\": \"\",\n\t\t\"name\": \"unimall-devcopy\",\n\t\t\"source\": {\n\t\t\t\"type\": \"copy\",\n\t\t\t\"certificate\": \"\",\n\t\t\t\"base-image\": \"70d3dcaabcffb1aa1644d0ce866efcb141742179e94ad72aefb8d3502338a71f\",\n\t\t\t\"source\": \"unimall-dev\"\n\t\t},\n\t\t\"instance_type\": \"\",\n\t\t\"type\": \"container\"\n\t}"
t=2021-06-28T05:29:08+0000 lvl=dbug msg="Responding to instance create"
t=2021-06-28T05:29:08+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.last_state.power project=default sourceInstance=unimall-dev sourceProject=default
t=2021-06-28T05:29:08+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.eth0.hwaddr project=default sourceInstance=unimall-dev sourceProject=default
t=2021-06-28T05:29:08+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.idmap.current project=default sourceInstance=unimall-dev sourceProject=default
t=2021-06-28T05:29:08+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.idmap.base project=default sourceInstance=unimall-dev sourceProject=default
t=2021-06-28T05:29:08+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.uuid project=default sourceInstance=unimall-dev sourceProject=default
t=2021-06-28T05:29:08+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.idmap.next project=default sourceInstance=unimall-dev sourceProject=default
t=2021-06-28T05:29:08+0000 lvl=dbug msg="New task Operation: bbef4c47-4847-43a2-8dfa-1aa68b103390"
t=2021-06-28T05:29:08+0000 lvl=dbug msg="Started task operation: bbef4c47-4847-43a2-8dfa-1aa68b103390"
t=2021-06-28T05:29:08+0000 lvl=dbug msg="\n\t{\n\t\t\"type\": \"async\",\n\t\t\"status\": \"Operation created\",\n\t\t\"status_code\": 100,\n\t\t\"operation\": \"/1.0/operations/bbef4c47-4847-43a2-8dfa-1aa68b103390\",\n\t\t\"error_code\": 0,\n\t\t\"error\": \"\",\n\t\t\"metadata\": {\n\t\t\t\"id\": \"bbef4c47-4847-43a2-8dfa-1aa68b103390\",\n\t\t\t\"class\": \"task\",\n\t\t\t\"description\": \"Creating instance\",\n\t\t\t\"created_at\": \"2021-06-28T05:29:08.450697507Z\",\n\t\t\t\"updated_at\": \"2021-06-28T05:29:08.450697507Z\",\n\t\t\t\"status\": \"Running\",\n\t\t\t\"status_code\": 103,\n\t\t\t\"resources\": {\n\t\t\t\t\"containers\": [\n\t\t\t\t\t\"/1.0/containers/unimall-devcopy\",\n\t\t\t\t\t\"/1.0/containers/unimall-dev\"\n\t\t\t\t],\n\t\t\t\t\"instances\": [\n\t\t\t\t\t\"/1.0/instances/unimall-devcopy\",\n\t\t\t\t\t\"/1.0/instances/unimall-dev\"\n\t\t\t\t]\n\t\t\t},\n\t\t\t\"metadata\": null,\n\t\t\t\"may_cancel\": false,\n\t\t\t\"err\": \"\",\n\t\t\t\"location\": \"neutron-star\"\n\t\t}\n\t}"
t=2021-06-28T05:29:08+0000 lvl=dbug msg=Handling ip=@ method=GET protocol=unix url="/1.0/operations/bbef4c47-4847-43a2-8dfa-1aa68b103390?target=neutron-star" username=uni058
t=2021-06-28T05:29:08+0000 lvl=info msg="Creating container" ephemeral=false instance=unimall-devcopy instanceType=container project=default
t=2021-06-28T05:29:08+0000 lvl=dbug msg="FillInstanceConfig started" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default
t=2021-06-28T05:29:08+0000 lvl=dbug msg="FillInstanceConfig finished" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default
t=2021-06-28T05:29:08+0000 lvl=info msg="Created container" ephemeral=false instance=unimall-devcopy instanceType=container project=default
t=2021-06-28T05:29:08+0000 lvl=dbug msg="CreateInstanceFromCopy started" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default snapshots=true src=unimall-dev
t=2021-06-28T05:29:08+0000 lvl=dbug msg="CreateInstanceFromCopy same-pool mode detected" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default snapshots=true src=unimall-dev
t=2021-06-28T05:29:09+0000 lvl=dbug msg="Found cert" name=0
t=2021-06-28T05:29:09+0000 lvl=dbug msg="Replace current raft nodes with [{ID:8 Address:10.0.199.210:8443 Role:voter} {ID:9 Address:10.0.199.230:8443 Role:stand-by} {ID:10 Address:10.0.199.250:8443 Role:stand-by} {ID:11 Address:10.0.199.190:8443 Role:voter} {ID:6 Address:10.0.199.220:8443 Role:voter}]"
t=2021-06-28T05:29:09+0000 lvl=dbug msg="DeleteInstance started" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default
t=2021-06-28T05:29:09+0000 lvl=dbug msg="Deleting instance volume" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default volName=unimall-devcopy
t=2021-06-28T05:29:09+0000 lvl=dbug msg="DeleteInstance finished" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default
t=2021-06-28T05:29:09+0000 lvl=dbug msg="CreateInstanceFromCopy finished" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default snapshots=true src=unimall-dev
t=2021-06-28T05:29:09+0000 lvl=info msg="Deleting container" created=2021-06-28T05:29:08+0000 ephemeral=false instance=unimall-devcopy instanceType=container project=default used=1970-01-01T00:00:00+0000
t=2021-06-28T05:29:09+0000 lvl=dbug msg="Database error: &errors.errorString{s:\"No such object\"}"
t=2021-06-28T05:29:09+0000 lvl=info msg="Deleted container" created=2021-06-28T05:29:08+0000 ephemeral=false instance=unimall-devcopy instanceType=container project=default used=1970-01-01T00:00:00+0000
t=2021-06-28T05:29:09+0000 lvl=dbug msg="Failure for task operation: bbef4c47-4847-43a2-8dfa-1aa68b103390: Create instance from copy: exit status 2"
t=2021-06-28T05:29:09+0000 lvl=dbug msg="Event listener finished: 60a54907-79ca-4401-ac65-cd6c15f98976"
t=2021-06-28T05:29:09+0000 lvl=dbug msg="Disconnected event listener: 60a54907-79ca-4401-ac65-cd6c15f98976"`

lxc copy unimall-dev/snap0 unimall-devcopy --target neutron-star

**dmesg EXT4-fs (rbd3): VFS: Can't find ext4 filesystem**

```
t=2021-06-28T05:34:22+0000 lvl=dbug msg=Handling ip=@ method=POST protocol=unix url="/1.0/instances?target=neutron-star" username=uni058
t=2021-06-28T05:34:22+0000 lvl=dbug msg="\n\t{\n\t\t\"architecture\": \"x86_64\",\n\t\t\"config\": {\n\t\t\t\"boot.autostart\": \"false\",\n\t\t\t\"image.architecture\": \"amd64\",\n\t\t\t\"image.description\": \"ubuntu 18.04 LTS amd64 (release) (20200519.1)\",\n\t\t\t\"image.label\": \"release\",\n\t\t\t\"image.os\": \"ubuntu\",\n\t\t\t\"image.release\": \"bionic\",\n\t\t\t\"image.serial\": \"20200519.1\",\n\t\t\t\"image.version\": \"18.04\",\n\t\t\t\"volatile.base_image\": \"70d3dcaabcffb1aa1644d0ce866efcb141742179e94ad72aefb8d3502338a71f\"\n\t\t},\n\t\t\"devices\": {\n\t\t\t\"root\": {\n\t\t\t\t\"path\": \"/\",\n\t\t\t\t\"pool\": \"ceph-lxd\",\n\t\t\t\t\"size\": \"36GB\",\n\t\t\t\t\"type\": \"disk\"\n\t\t\t}\n\t\t},\n\t\t\"ephemeral\": false,\n\t\t\"profiles\": [\n\t\t\t\"ceph-ssd\"\n\t\t],\n\t\t\"stateful\": false,\n\t\t\"description\": \"\",\n\t\t\"name\": \"unimall-devcopy\",\n\t\t\"source\": {\n\t\t\t\"type\": \"copy\",\n\t\t\t\"certificate\": \"\",\n\t\t\t\"base-image\": \"70d3dcaabcffb1aa1644d0ce866efcb141742179e94ad72aefb8d3502338a71f\",\n\t\t\t\"source\": \"unimall-dev/snap0\"\n\t\t},\n\t\t\"instance_type\":
\"\",\n\t\t\"type\": \"\"\n\t}"
t=2021-06-28T05:34:22+0000 lvl=dbug msg="Responding to instance create"
t=2021-06-28T05:34:22+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.idmap.next project=default sourceInstance=unimall-dev/snap0 sourceProject=default
t=2021-06-28T05:34:22+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.eth0.hwaddr project=default sourceInstance=unimall-dev/snap0 sourceProject=default
t=2021-06-28T05:34:22+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.uuid project=default sourceInstance=unimall-dev/snap0 sourceProject=default
t=2021-06-28T05:34:22+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.idmap.base project=default sourceInstance=unimall-dev/snap0 sourceProject=default
t=2021-06-28T05:34:22+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.idmap.current project=default sourceInstance=unimall-dev/snap0 sourceProject=default
t=2021-06-28T05:34:22+0000 lvl=dbug msg="Skipping key from copy source" instance=unimall-devcopy key=volatile.last_state.power project=default sourceInstance=unimall-dev/snap0 sourceProject=default
t=2021-06-28T05:34:22+0000 lvl=dbug msg="New task Operation: 00786f4c-6741-4a70-855b-8f3bf6a29f1c"
t=2021-06-28T05:34:22+0000 lvl=dbug msg="Started task operation: 00786f4c-6741-4a70-855b-8f3bf6a29f1c"
t=2021-06-28T05:34:22+0000 lvl=dbug msg="\n\t{\n\t\t\"type\": \"async\",\n\t\t\"status\": \"Operation created\",\n\t\t\"status_code\": 100,\n\t\t\"operation\": \"/1.0/operations/00786f4c-6741-4a70-855b-8f3bf6a29f1c\",\n\t\t\"error_code\": 0,\n\t\t\"error\": \"\",\n\t\t\"metadata\": {\n\t\t\t\"id\": \"00786f4c-6741-4a70-855b-8f3bf6a29f1c\",\n\t\t\t\"class\": \"task\",\n\t\t\t\"description\": \"Creating instance\",\n\t\t\t\"created_at\": \"2021-06-28T05:34:22.508386577Z\",\n\t\t\t\"updated_at\": \"2021-06-28T05:34:22.508386577Z\",\n\t\t\t\"status\": \"Running\",\n\t\t\t\"status_code\": 103,\n\t\t\t\"resources\": {\n\t\t\t\t\"containers\": [\n\t\t\t\t\t\"/1.0/containers/unimall-devcopy\",\n\t\t\t\t\t\"/1.0/containers/unimall-dev/snap0\"\n\t\t\t\t],\n\t\t\t\t\"instances\": [\n\t\t\t\t\t\"/1.0/instances/unimall-devcopy\",\n\t\t\t\t\t\"/1.0/instances/unimall-dev/snap0\"\n\t\t\t\t]\n\t\t\t},\n\t\t\t\"metadata\": null,\n\t\t\t\"may_cancel\": false,\n\t\t\t\"err\": \"\",\n\t\t\t\"location\": \"neutron-star\"\n\t\t}\n\t}"
t=2021-06-28T05:34:22+0000 lvl=dbug msg=Handling ip=@ method=GET protocol=unix url="/1.0/operations/00786f4c-6741-4a70-855b-8f3bf6a29f1c?target=neutron-star" username=uni058
t=2021-06-28T05:34:22+0000 lvl=info msg="Creating container" ephemeral=false instance=unimall-devcopy instanceType=container project=default
t=2021-06-28T05:34:22+0000 lvl=dbug msg="FillInstanceConfig started" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default
t=2021-06-28T05:34:22+0000 lvl=dbug msg="FillInstanceConfig finished" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default
t=2021-06-28T05:34:22+0000 lvl=info msg="Created container" ephemeral=false instance=unimall-devcopy instanceType=container project=default
t=2021-06-28T05:34:22+0000 lvl=dbug msg="CreateInstanceFromCopy started" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default snapshots=true src=unimall-dev/snap0
t=2021-06-28T05:34:22+0000 lvl=dbug msg="CreateInstanceFromCopy same-pool mode detected" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default snapshots=true src=unimall-dev/snap0
t=2021-06-28T05:34:23+0000 lvl=dbug msg="Activated RBD volume" dev=/dev/rbd3 driver=ceph pool=ceph-lxd vol=container_unimall-devcopy
t=2021-06-28T05:34:30+0000 lvl=dbug msg="Found cert" name=0
t=2021-06-28T05:34:30+0000 lvl=dbug msg="Replace current raft nodes with [{ID:10 Address:10.0.199.250:8443 Role:stand-by} {ID:11 Address:10.0.199.190:8443 Role:voter} {ID:6 Address:10.0.199.220:8443 Role:voter} {ID:8 Address:10.0.199.210:8443 Role:voter} {ID:9 Address:10.0.199.230:8443 Role:stand-by}]"
t=2021-06-28T05:34:34+0000 lvl=dbug msg="Deactivated RBD volume" driver=ceph pool=ceph-lxd vol=container_unimall-devcopy
t=2021-06-28T05:34:42+0000 lvl=dbug msg="Found cert" name=0
t=2021-06-28T05:34:42+0000 lvl=dbug msg="Replace current raft nodes with [{ID:6 Address:10.0.199.220:8443 Role:voter} {ID:8 Address:10.0.199.210:8443 Role:voter} {ID:9 Address:10.0.199.230:8443 Role:stand-by} {ID:10 Address:10.0.199.250:8443 Role:stand-by} {ID:11 Address:10.0.199.190:8443 Role:voter}]"
t=2021-06-28T05:34:45+0000 lvl=dbug msg="DeleteInstance started" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default
t=2021-06-28T05:34:45+0000 lvl=dbug msg="Deleting instance volume" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default volName=unimall-devcopy
t=2021-06-28T05:34:45+0000 lvl=dbug msg="DeleteInstance finished" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default
t=2021-06-28T05:34:45+0000 lvl=dbug msg="CreateInstanceFromCopy finished" driver=ceph instance=unimall-devcopy pool=ceph-lxd project=default snapshots=true src=unimall-dev/snap0
t=2021-06-28T05:34:45+0000 lvl=info msg="Deleting container" created=2021-06-28T05:34:22+0000 ephemeral=false instance=unimall-devcopy instanceType=container project=default used=1970-01-01T00:00:00+0000
t=2021-06-28T05:34:45+0000 lvl=dbug msg="Database error: &errors.errorString{s:\"No such object\"}"
t=2021-06-28T05:34:45+0000 lvl=info msg="Deleted container" created=2021-06-28T05:34:22+0000 ephemeral=false instance=unimall-devcopy instanceType=container project=default used=1970-01-01T00:00:00+0000
t=2021-06-28T05:34:45+0000 lvl=dbug msg="Failure for task operation: 00786f4c-6741-4a70-855b-8f3bf6a29f1c: Create instance from copy: Failed to mount \"/dev/rbd3\" on \"/var/snap/lxd/common/lxd/storage-pools/ceph-lxd/containers/unimall-devcopy\" using \"ext4\": invalid argument"
t=2021-06-28T05:34:45+0000 lvl=dbug msg="Event listener finished: 0dba4df1-59c8-4319-9f98-b51db862d1cb"
t=2021-06-28T05:34:45+0000 lvl=dbug msg="Disconnected event listener: 0dba4df1-59c8-4319-9f98-b51db862d1cb"
```

**Comment by stgraber** [comment]
Okay, so some kind of filesystem mismatch. Reading this is a bit confusing though, to clarify, could you show:
 - lxc storage show ceph-lxd
 - lxc volume show ceph-lxd container/unimall-dev
 - lxc volume show ceph-lxd container/unimall-dev/snap0

**Comment by vvolas** [comment]
Sorry for confusion this is old installation and at some point I have changed block_filesystem (not manually) and few container may be converted via copy from ceph-hdd to ceph-ssd. Probably thats why this container in fstab still had ext4 in fstab.

```
lxc storage show ceph-lxd
config:
  ceph.cluster_name: ceph
  ceph.osd.pg_num: "128"
  ceph.osd.pool_name: ceph-lxd
  ceph.user.name: lxd
  volatile.pool.pristine: "true"
  volume.size: 35GB
description: ""
name: ceph-lxd
driver: ceph
used_by:

lxc storage volume show ceph-lxd container/unimall-dev
config:
  block.filesystem: xfs
  block.mount_options: discard
  size: 35GB
description: ""
name: unimall-dev
type: container
used_by:
- /1.0/instances/unimall-dev
location: ""
content_type: filesystem

lxc storage volume show ceph-lxd container/unimall-dev/snap0
description: ""
expires_at: 0001-01-01T01:41:16+01:41
name: snap0
config:
  block.filesystem: xfs
  block.mount_options: discard
  size: 35GB
content_type: ""

```

**Comment by stgraber** [comment]
Thanks, that should be enough for us to reproduce it. Looks like LXD is not considering the volume config in this case which is wrong.

**Comment by tomponline** [comment]
This sounds very similar to https://github.com/lxc/lxd/issues/8301

**Comment by stgraber** [comment]
Got it reproduced here:
```
root@vm01:~# lxc storage set ceph volume.block.filesystem=xfs volume.block.mount_options=discard
root@vm01:~# lxc launch images:alpine/edge a1
Starting a1
root@vm01:~# lxc snapshot a1
root@vm01:~# lxc storage unset ceph volume.block.filesystem
root@vm01:~# lxc storage unset ceph volume.block.mount_options
root@vm01:~# lxc storage show ceph
config:
  ceph.cluster_name: ceph
  ceph.osd.pg_num: "32"
  ceph.osd.pool_name: persist-vm01
  ceph.user.name: admin
  source: persist-vm01
  volatile.initial_source: persist-vm01
  volatile.pool.pristine: "true"
description: ""
name: ceph
driver: ceph
used_by:
- /1.0/images/3cc5f40527ea7055beccefcedd8a89b7b8b488037a288078e7681e815543b576
- /1.0/instances/a1
- /1.0/profiles/default
status: Created
locations:
- none
root@vm01:~# lxc storage volume show ceph container/a1
config:
  block.filesystem: xfs
  block.mount_options: discard
description: ""
name: a1
type: container
used_by:
- /1.0/instances/a1
location: ""
content_type: filesystem
root@vm01:~# lxc storage volume show ceph container/a1/snap0
description: ""
expires_at: 0001-01-01T00:00:00Z
name: snap0
config:
  block.filesystem: xfs
  block.mount_options: discard
content_type: filesystem
root@vm01:~# lxc stop a1
root@vm01:~# lxc copy a1/snap0 a2
Error: Create instance from copy: Failed to mount "/dev/rbd0" on "/var/snap/lxd/common/lxd/storage-pools/ceph/containers/a2" using "ext4": invalid argument
root@vm01:~# 
```

**Comment by stgraber** [comment]
@tomponline so if I'm reading things right, the issue is that we're just passing a `rootDiskConf` as the config of the volume rather than pulling the current volume's config and using rootDiskConf as an override to apply on top.

As a result, config options like `volume.*` which the source may have, end up being discarded.

**Comment by stgraber** [comment]
@tomponline sent a fix for it. Basically the issue is that the instance code which creates the DB entries has no idea it's dealing with a copy and has no access to the original volume config.

As a result, it creates a new volume or volume snapshot with a blank config and moves on. This then gets passed to the storage driver which fails when trying to actually mount the thing.

I don't think we've found the right spot for the storage volume DB logic quite yet. It's definitely quite awkward to have the instance driver handle the DB record creation in this case. Ideally, having the storage backend handle the DB bits would be great and would make such things easier (as we'd deal with volumes, have source and target and could sync up the configs) but short of that, maybe moving that logic over to instance.go would already make things a bit simpler.

In any case, to solve this bug, I've added logic which will now update the volume config immediately after its creation by the instance driver, syncing it up with the source so long as they reside on the same storage pool (as cross pool will most likely involve rsync which can handle with a change of volume config). This is done prior to snapshots being handled so new snapshots just inherit this copied config and all is well.

I've confirmed that both `lxc copy a1/snap0 a2` and `lxc copy a1 a2` works properly. Resulting volumes are all properly configured to use xfs while any new instance will use ext4 as expected.

**Comment by tomponline** [comment]
@stgraber 
> I don't think we've found the right spot for the storage volume DB logic quite yet. It's definitely quite awkward to have the instance driver handle the DB record creation in this case. Ideally, having the storage backend handle the DB bits would be great and would make such things easier (as we'd deal with volumes, have source and target and could sync up the configs) but short of that, maybe moving that logic over to instance.go would already make things a bit simpler.

I would whole heartedly support moving the instance storage volume DB record creation/update/deletion into the storage layer, this is the logical place to do it, and also brings it inline with what we do for custom volumes.

I didn't do this at the time of the storage package creation because the instance DB record creation logic was already quite interwoven with the instance storage DB record creation, and as it was already a large change, I didn't feel confident tackling that at the time. However now the storage package is well bedded in and I am a lot more familiar now with the instance/instance storage volume relationship, especially as recently making the revert logging more nuanced, I think this would be a good idea to tackle. Shall I add to the ideas board?

**Comment by stgraber** [comment]
Yep, that'd be good.
