### ISSUE TITLE
cannot set link-layer device addresses

### ISSUE THREAD

**Issue by mullumaus** [lxc/lxd#8962]
# Required information

 * Distribution:
 * Distribution version:
   Operating System: Ubuntu 18.04.5 LTS
            Kernel: Linux 4.15.0-147-generic
      Architecture: x86-64

 * The output of "lxc info" or if that fails:
   driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-112-generic
  server: lxd
  server_pid: 73670
  server_version: 3.0.3
  storage: ""
  storage_version: ""
  server_clustered: false

# Issue description

I am getting this error when I try to deploy LXD on a  machine, I tried to remove the machine and re-deploy it but didn't help

juju add-unit prometheus-openstack-exporter  -n 1 --to lxd:44

44/lxd/1  down                    pending         bionic         cannot record provisioning info for "juju-2a61ce-44-lxd-1": cannot set link-layer device addresses of machine "44/lxd/1": invalid address "10.X.X.X/24": DeviceName "eth0" on machine "44/lxd/1" not found

# Steps to reproduce

 1. juju add-machine $name  (get the machine ID 44)
 2. juju add-unit prometheus-openstack-exporter  -n 1 --to lxd:44

We've confirmed that creating LXDs manually on the machine works fine (with "sudo lxc launch juju/bionic/amd64"), but when trying to create a LXD through Juju, we get the same error about not finding the eth0 interface (tried with "juju deploy ubuntu --to lxd:44" and "juju add-machine lxd:44").

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
This is an error coming from Juju, not from LXD and we're not familiar enough with how Juju configures LXD to help track this down.

I'd strongly recommend filling a bug against Juju so the devs over there can look into it.

The error message itself is confusing too. It suggests that the eth0 device couldn't be found (presumably in the instance state struct) but then in the same line, also complains about an IP address which would suggest that it did in fact find the entry...
