### ISSUE TITLE
dns entry for lxd host

### ISSUE THREAD

**Issue by hadmut** [lxc/lxd#8976]
# Required information

 * Distribution: Lubuntu 
 * Distribution version: 20.04

# Issue description

That's not a bug, that's a feature request. 

When running multiple lxd guest machines, they can find each other on dns in the lxd. domain with their names. 

But I didn't find a trivial way (other than routing tables or replacing the own ip with .1) to query the IP of the host machine, e.g. when using lxd to run a test client for a server. I didn't find a hint in the man pages or help texts about how to manually configure additional dns entries. 

Would be nice if the host with its lxd network address appeared in DNS with both a canonical and its regular hostname (or some configurable one) 

regards

**Comment by stgraber** [comment]
At least for containers using systemd with resolved, you can use `_gateway` to resolve to whatever the gateway is.

**Comment by tomponline** [comment]
You can also use the `raw.dnsmasq` setting on your managed network to add a custom DNS entry returned by dnsmasq.

Option 1:

Use the `interface-name` dnsmasq option to create DNS records for the IP addresses on the interface of your managed bridge, e.g:
```
lxc network set lxdbr0 raw.dnsmasq='interface-name=gateway.lxd,lxdbr0'
```

Then inside the instance:

```
dig any gateway.lxd

; <<>> DiG 9.16.1-Ubuntu <<>> any gateway.lxd
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13060
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;gateway.lxd.			IN	ANY

;; ANSWER SECTION:
gateway.lxd.		0	IN	A	10.98.30.1
gateway.lxd.		0	IN	AAAA	fd42:f402:8623:5b6b::1

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mon Jul 05 08:21:28 UTC 2021
;; MSG SIZE  rcvd: 84
```

Or you can add manual DNS records using:

```
lxc network set lxdbr0 raw.dnsmasq='address=/gateway.lxd/10.98.30.1'
```

Then inside the instance:

```
dig any gateway.lxd

; <<>> DiG 9.16.1-Ubuntu <<>> any gateway.lxd
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17215
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;gateway.lxd.			IN	ANY

;; ANSWER SECTION:
gateway.lxd.		0	IN	A	10.98.30.1

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mon Jul 05 08:22:58 UTC 2021
;; MSG SIZE  rcvd: 56
```

@stgraber perhaps we could add an option in LXD to use the `interface-name` option without using `raw.dnsmasq`?


@hadmut then for resolving `.lxd` domains from the host, see this guide: https://linuxcontainers.org/lxd/docs/master/networks#integration-with-systemd-resolved

**Comment by hadmut** [comment]
There is, btw., a problem with the _gateway hostname offered by systemd-resolved as mentioned above. Since this is not an RFC2396 compliant hostname, it cannot be used as part of a URI. E.g. the ruby runtime does not accept it as a hostname.

**Comment by stgraber** [comment]
I suspect that was somewhat intentional to avoid clashing with normal legitimate entries and is also why we used it for LXD as you can't call a container _gateway
