### ISSUE TITLE
dhcp error on 20.04.2 snap lxd

### ISSUE THREAD

**Issue by drscrewdriver** [lxc/lxd#8983]
# Required information

 * Distribution:Ubuntu 
 * Distribution version:20.04.2 tls
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux wnadminserver 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 4.0.5
   * LXD version: 4.0.5
   * Storage backend in use: dir

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce
dhcient not work

 1. cgroupfs-mount  (installed)
 2. snap restart lxd (init finsh )
 3. root@wnadminserver:/home/wnadmin# lxc list
+----------+---------+------+------+-----------+-----------+
|   NAME   |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+----------+---------+------+------+-----------+-----------+
| net-test | RUNNING |      |      | CONTAINER | 0         |
+----------+---------+------+------+-----------+-----------+

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 
![image](https://user-images.githubusercontent.com/19632018/124577435-d888f800-de7f-11eb-8563-57b64ffccff1.png)

 - [ ] Container log (`lxc info NAME --show-log`)
 root@wnadminserver:/home/wnadmin# lxc info --show-log net-test
Name: net-test
Location: none
Remote: unix://
Architecture: x86_64
Created: 2021/07/06 08:34 UTC
Status: Running
Type: container
Profiles: default
Pid: 3500
Ips:
  eth0:	inet6	fe80::216:3eff:fee2:d5ed	veth307481f8
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 10
  CPU usage:
    CPU usage (in seconds): 1
  Memory usage:
    Memory (current): 19.43MB
    Memory (peak): 21.40MB
  Network usage:
    eth0:
      Bytes received: 51.78kB
      Bytes sent: 1.71kB
      Packets received: 478
      Packets sent: 11
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

lxc net-test 20210706090037.260 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1126 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.net-test"
lxc net-test 20210706090037.262 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1126 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.net-test"
lxc net-test 20210706090037.272 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1547 - No such file or directory - Failed to fchownat(17, memory.oom.group, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc net-test 20210706090037.304 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 30(dev)
lxc net-test 20210706090037.370 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(full)
lxc net-test 20210706090037.371 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(null)
lxc net-test 20210706090037.371 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(random)
lxc net-test 20210706090037.371 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(tty)
lxc net-test 20210706090037.371 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(urandom)
lxc net-test 20210706090037.371 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(zero)

run dhclient in container exec shell dosen't work ether

static IP seems working
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 root@wnadminserver:/home/wnadmin# lxc config show net-test --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Centos 7 amd64 (20210705_19:52)
  image.os: Centos
  image.release: "7"
  image.serial: "20210705_19:52"
  image.type: squashfs
  image.variant: default
  volatile.base_image: 3db812dce97facea012e88c4299d166074f9d5c1782400c1c053699bb8b52d67
  volatile.eth0.host_name: veth307481f8
  volatile.eth0.hwaddr: 00:16:3e:e2:d5:ed
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: ced9103c-cc4b-4f4a-8121-2071b9e4f443
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
root@wnadminserver:/home/wnadmin# 

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 root@wnadminserver:/home/wnadmin# lxc config show net-test --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Centos 7 amd64 (20210705_19:52)
  image.os: Centos
  image.release: "7"
  image.serial: "20210705_19:52"
  image.type: squashfs
  image.variant: default
  volatile.base_image: 3db812dce97facea012e88c4299d166074f9d5c1782400c1c053699bb8b52d67
  volatile.eth0.host_name: veth307481f8
  volatile.eth0.hwaddr: 00:16:3e:e2:d5:ed
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: ced9103c-cc4b-4f4a-8121-2071b9e4f443
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
root@wnadminserver:/home/wnadmin# tail -5000 /var/snap/lxd/common/lxd/logs/lxd.log
t=2021-07-06T09:00:36+0000 lvl=info msg="LXD 4.0.5 is starting in normal mode" path=/var/snap/lxd/common/lxd
t=2021-07-06T09:00:36+0000 lvl=info msg="Kernel uid/gid map:" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - u 0 0 4294967295" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - g 0 0 4294967295" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Configured LXD uid/gid map:" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - u 0 1000000 1000000000" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - g 0 1000000 1000000000" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Kernel features:" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - closing multiple file descriptors efficiently: no" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - netnsid-based network retrieval: yes" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - pidfds: yes" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - uevent injection: yes" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - seccomp listener: yes" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - seccomp listener continue syscalls: yes" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - seccomp listener add file descriptors: no" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - attach to namespaces via pidfds: no" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - safe native terminal allocation : yes" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - cgroup layout: hybrid" 
t=2021-07-06T09:00:36+0000 lvl=warn msg=" - Couldn't find the CGroup blkio.weight, disk priority will be ignored" 
t=2021-07-06T09:00:36+0000 lvl=warn msg=" - Couldn't find the CGroup memory swap accounting, swap limits will be ignored" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - shiftfs support: disabled" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Initializing local database" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Starting /dev/lxd handler:" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2021-07-06T09:00:36+0000 lvl=info msg="REST API daemon:" 
t=2021-07-06T09:00:36+0000 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/snap/lxd/common/lxd/unix.socket
t=2021-07-06T09:00:36+0000 lvl=info msg="Initializing global database" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Firewall loaded driver \"xtables\"" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Initializing storage pools" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Initializing daemon storage mounts" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Initializing networks" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Pruning leftover image files" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Done pruning leftover image files" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Loading daemon configuration" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Started seccomp handler" path=/var/snap/lxd/common/lxd/seccomp.socket
t=2021-07-06T09:00:36+0000 lvl=info msg="Pruning expired images" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Done pruning expired images" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Pruning expired instance backups" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Done pruning expired instance backups" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Expiring log files" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Updating instance types" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Done updating instance types" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Done expiring log files" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Updating images" 
t=2021-07-06T09:00:36+0000 lvl=info msg="Done updating images" 
t=2021-07-06T09:00:37+0000 lvl=info msg="Starting container" action=start created=2021-07-06T08:34:31+0000 ephemeral=false instance=net-test instanceType=container project=default stateful=false used=2021-07-06T08:56:05+0000
t=2021-07-06T09:00:37+0000 lvl=info msg="Started container" action=start created=2021-07-06T08:34:31+0000 ephemeral=false instance=net-test instanceType=container project=default stateful=false used=2021-07-06T08:56:05+0000
t=2021-07-06T09:10:36+0000 lvl=warn msg="Detected poll(POLLNVAL) event."

**Comment by tomponline** [comment]
Please confirm you are saying that your instances are not getting IPs from LXD's DHCP server?

**Comment by drscrewdriver** [comment]
Test container can‘t get ip from dhcp server in normal network while virt eth port attached on the net bridge br0 which work fine on Host system.

**Comment by drscrewdriver** [comment]
It is similar to the situation on my personal server running manjaro ，the system of upload example host-system is a nest system virt by a qemu-kvm program running on the real host system kernel info: Linux wnadmin-poweredger620-252 5.4.118-1-MANJARO #1 SMP PREEMPT Tue May 11 17:46:18 UTC 2021 x86_64 GNU/Linux.

**Comment by tomponline** [comment]
Can you confirm dnsmasq is running on the host and is listening:

```
sudo ss -ulpn
```

**Comment by drscrewdriver** [comment]
DHCP service fail to assign container eth is supply by a hardware router ，which has assign ip for qemu-kvm host server ubuntu successfully。

**Comment by tomponline** [comment]
Do you see DHCP packets arriving from the container to the bridge using `tcpdump`, and also leaving the host's external interface to the upstream DHCP server?

**Comment by drscrewdriver** [comment]
![image](https://user-images.githubusercontent.com/19632018/124625424-5b29ab80-deb0-11eb-8f1c-edace9a23fdc.png)

**Comment by drscrewdriver** [comment]
![image](https://user-images.githubusercontent.com/19632018/124627010-c45dee80-deb1-11eb-9d35-c1a4984a1a36.png)
![image](https://user-images.githubusercontent.com/19632018/124627025-c922a280-deb1-11eb-81fb-6c54830c88ab.png)
Network-scripts work fine but the real issue is it doesn't work on 5.4+ manjaro with lxd 4.12 or lxd 4.15. Forget the issue if you can‘t repeat it in similar env.

**Comment by crzfst** [comment]
Are you by any chance running firewall on your LXD Host? Something changed in one of the latest LXD versions and I had the same problem with containers not getting IP from LXD bridge until I added firewall rules to allow DHCP ports (67 & 68).

I'm running Ubuntu 20.4.2 LTS with LXD 4.16

**Comment by tomponline** [comment]
> Are you by any chance running firewall on your LXD Host? Something changed in one of the latest LXD versions and I had the same problem with containers not getting IP from LXD bridge until I added firewall rules to allow DHCP ports (67 & 68).
> 
> I'm running Ubuntu 20.4.2 LTS with LXD 4.16

Its likely an interaction with an existing firewall meaning that the rules LXD adds don't get applied.

See https://discuss.linuxcontainers.org/t/lxd-bridge-doesnt-work-with-ipv4-and-ufw-with-nftables/10034/14?u=tomp for discussion and work around the changes in behaviour when using nftables vs xtables backends.

**Comment by stgraber** [comment]
@drscrewdriver any update?
