### ISSUE TITLE
LXC Doesn't Handle Arguments in VISUAL

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#899]
I have VISUAL="/usr/bin/emacs -nw" set in my bashrc so that while using the command line I always get emacs in a terminal window instead of the full GTK GUI. If I use an LXC command which invokes VISUAL I get the following error

$ lxc config edit trusty
error: fork/exec /usr/bin/emacs -nw: no such file or directory

If I set VISUAL="/usr/bin/emacs" the error goes away.

**Comment by ranjib** [comment]
hmm.. does this fixes your issue: https://github.com/lxc/lxd/pull/900

**Comment by stgraber** [comment]
I believe this has been fixed.
