### ISSUE TITLE
Growing number of snap.rootfs directories

### ISSUE THREAD

**Issue by dansimpson** [lxc/lxd#9029]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04 
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.8.0-1041-aws 43~20.04.1-Ubuntu
   * LXC version: 4.0.4
   * LXD version: 4.0.4
   * Storage backend in use: disk?

# Issue description
When running 'lxc info' or any other lxc command, there is an error presented:
`cannot perform operation: mount --rbind /var/log /tmp/snap.rootfs_MoGMHN//var/log: Permission denied`

Now, this is likely due to an odd setup where /var/log is symbolically linked to /mnt/blah/log, but the problem is: Directories and mounts are created such as `snap.rootfs_MoGMHN` but are never cleaned up.

As a result, over time, thousands of these folders/mounts are created and systemd oriented services start having issues starting due to timeouts and CPU usage spikes for systemd related services.

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Symbolically link var log to another directory: `ln -sf /mnt/target /var/log`
 2. Run `lxc list`
 3. Run `find /tmp/snap.rootfs*`
 4. Repeat 2 through 3 10,000 times.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Thanks for this report, unfortunately this is showing a bug or design issue with snapd which will affect every snap, not just LXD.
It's also not something which we can workaround at the LXD level.

Could you report this behavior over at https://forum.snapcraft.io?

As an alternative/workaround, replacing your symlink with a bind-mount (`mount -o bind /mnt/target /var/log`) would probably avoid this issue and quite a number of others (security system apparmor applies all path checks on the resolved symlink, so a profile allowing /var/log/XYZ will no longer apply on your system...).

**Comment by dansimpson** [comment]
@stgraber thanks, I will report it there. I have tested the mount version with success and will proceed with that workaround.
