### ISSUE TITLE
LXD unable to find udev device id

### ISSUE THREAD

**Issue by jardon** [lxc/lxd#9035]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 20.04

<details>
  <summary>The output of "lxc info"</summary>

      config: {}
      api_extensions:
      - storage_zfs_remove_snapshots
      - container_host_shutdown_timeout
      - container_stop_priority
      - container_syscall_filtering
      - auth_pki
      - container_last_used_at
      - etag
      - patch
      - usb_devices
      - https_allowed_credentials
      - image_compression_algorithm
      - directory_manipulation
      - container_cpu_time
      - storage_zfs_use_refquota
      - storage_lvm_mount_options
      - network
      - profile_usedby
      - container_push
      - container_exec_recording
      - certificate_update
      - container_exec_signal_handling
      - gpu_devices
      - container_image_properties
      - migration_progress
      - id_map
      - network_firewall_filtering
      - network_routes
      - storage
      - file_delete
      - file_append
      - network_dhcp_expiry
      - storage_lvm_vg_rename
      - storage_lvm_thinpool_rename
      - network_vlan
      - image_create_aliases
      - container_stateless_copy
      - container_only_migration
      - storage_zfs_clone_copy
      - unix_device_rename
      - storage_lvm_use_thinpool
      - storage_rsync_bwlimit
      - network_vxlan_interface
      - storage_btrfs_mount_options
      - entity_description
      - image_force_refresh
      - storage_lvm_lv_resizing
      - id_map_base
      - file_symlinks
      - container_push_target
      - network_vlan_physical
      - storage_images_delete
      - container_edit_metadata
      - container_snapshot_stateful_migration
      - storage_driver_ceph
      - storage_ceph_user_name
      - resource_limits
      - storage_volatile_initial_source
      - storage_ceph_force_osd_reuse
      - storage_block_filesystem_btrfs
      - resources
      - kernel_limits
      - storage_api_volume_rename
      - macaroon_authentication
      - network_sriov
      - console
      - restrict_devlxd
      - migration_pre_copy
      - infiniband
      - maas_network
      - devlxd_events
      - proxy
      - network_dhcp_gateway
      - file_get_symlink
      - network_leases
      - unix_device_hotplug
      - storage_api_local_volume_handling
      - operation_description
      - clustering
      - event_lifecycle
      - storage_api_remote_volume_handling
      - nvidia_runtime
      - container_mount_propagation
      - container_backup
      - devlxd_images
      - container_local_cross_pool_handling
      - proxy_unix
      - proxy_udp
      - clustering_join
      - proxy_tcp_udp_multi_port_handling
      - network_state
      - proxy_unix_dac_properties
      - container_protection_delete
      - unix_priv_drop
      - pprof_http
      - proxy_haproxy_protocol
      - network_hwaddr
      - proxy_nat
      - network_nat_order
      - container_full
      - candid_authentication
      - backup_compression
      - candid_config
      - nvidia_runtime_config
      - storage_api_volume_snapshots
      - storage_unmapped
      - projects
      - candid_config_key
      - network_vxlan_ttl
      - container_incremental_copy
      - usb_optional_vendorid
      - snapshot_scheduling
      - snapshot_schedule_aliases
      - container_copy_project
      - clustering_server_address
      - clustering_image_replication
      - container_protection_shift
      - snapshot_expiry
      - container_backup_override_pool
      - snapshot_expiry_creation
      - network_leases_location
      - resources_cpu_socket
      - resources_gpu
      - resources_numa
      - kernel_features
      - id_map_current
      - event_location
      - storage_api_remote_volume_snapshots
      - network_nat_address
      - container_nic_routes
      - rbac
      - cluster_internal_copy
      - seccomp_notify
      - lxc_features
      - container_nic_ipvlan
      - network_vlan_sriov
      - storage_cephfs
      - container_nic_ipfilter
      - resources_v2
      - container_exec_user_group_cwd
      - container_syscall_intercept
      - container_disk_shift
      - storage_shifted
      - resources_infiniband
      - daemon_storage
      - instances
      - image_types
      - resources_disk_sata
      - clustering_roles
      - images_expiry
      - resources_network_firmware
      - backup_compression_algorithm
      - ceph_data_pool_name
      - container_syscall_intercept_mount
      - compression_squashfs
      - container_raw_mount
      - container_nic_routed
      - container_syscall_intercept_mount_fuse
      - container_disk_ceph
      - virtual-machines
      - image_profiles
      - clustering_architecture
      - resources_disk_id
      - storage_lvm_stripes
      - vm_boot_priority
      - unix_hotplug_devices
      - api_filtering
      - instance_nic_network
      - clustering_sizing
      - firewall_driver
      - projects_limits
      - container_syscall_intercept_hugetlbfs
      - limits_hugepages
      - container_nic_routed_gateway
      - projects_restrictions
      - custom_volume_snapshot_expiry
      - volume_snapshot_scheduling
      - trust_ca_certificates
      - snapshot_disk_usage
      - clustering_edit_roles
      - container_nic_routed_host_address
      - container_nic_ipvlan_gateway
      - resources_usb_pci
      - resources_cpu_threads_numa
      - resources_cpu_core_die
      - api_os
      - resources_system
      - usedby_consistency
      - resources_gpu_mdev
      - console_vga_type
      - projects_limits_disk
      - storage_rsync_compression
      - gpu_mdev
      - resources_pci_iommu
      - resources_network_usb
      - resources_disk_address
      - network_state_vlan
      - gpu_sriov
      - migration_stateful
      - disk_state_quota
      - storage_ceph_features
      - gpu_mig
      - clustering_join_token
      - clustering_description
      - server_trusted_proxy
      - clustering_update_cert
      - storage_api_project
      - server_instance_driver_operational
      - server_supported_storage_drivers
      - event_lifecycle_requestor_address
      api_status: stable
      api_version: "1.0"
      auth: trusted
      public: false
      auth_methods:
      - tls
      environment:
        addresses: []
        architectures:
        - x86_64
        - i686
        certificate: |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAaSgAwIBAgIQCR64ipp41WoXwWsMot+r2TAKBggqhkjOPQQDAzA9MRww
          GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMR0wGwYDVQQDDBRyb290QG54cHJk
          YXBjejFtZ3QwMTAeFw0yMTA3MTMxNzQxMDFaFw0zMTA3MTExNzQxMDFaMD0xHDAa
          BgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxHTAbBgNVBAMMFHJvb3RAbnhwcmRh
          cGN6MW1ndDAxMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEltrB9PgKwtMHQuLuF1oU
          jju5Pgj+RA41h0M970kf5CieM0lXO+73EC0llwLLUVGHuraZzQnjDYUqyu4rSH0D
          Z3jeXwO2yqkwFlFldNJQlrjqs2x8DxXAWXyDe/QefTtyo2kwZzAOBgNVHQ8BAf8E
          BAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAyBgNVHREE
          KzApgg9ueHByZGFwY3oxbWd0MDGHBH8AAAGHEAAAAAAAAAAAAAAAAAAAAAEwCgYI
          KoZIzj0EAwMDaAAwZQIxAOgJDEwXdziFG1IoB1uo5lXMz4O5Oah0LgBqmbqeu+MQ
          Ae+gnksG/HvjRkgUuMoA7QIwM1owUz+qr2kNTDefbzf/zWblLO5KI1g+k/eKjKt9
          IYKRvJPQnReV42ipumZbs/xe
          -----END CERTIFICATE-----
        certificate_fingerprint: 42d9447158ffe4412277c6bf1e0574c78623c4ca22afe89dc623ab69f610974f
        driver: lxc | qemu
        driver_version: 4.0.10 | 5.2.0
        firewall: nftables
        kernel: Linux
        kernel_architecture: x86_64
        kernel_features:
          netnsid_getifaddrs: "true"
          seccomp_listener: "true"
          seccomp_listener_continue: "true"
          shiftfs: "false"
          uevent_injection: "true"
          unpriv_fscaps: "true"
        kernel_version: 5.4.0-77-generic
        lxc_features:
          cgroup2: "true"
          devpts_fd: "true"
          idmapped_mounts_v2: "true"
          mount_injection_file: "true"
          network_gateway_device_route: "true"
          network_ipvlan: "true"
          network_l2proxy: "true"
          network_phys_macvlan_mtu: "true"
          network_veth_router: "true"
          pidfd: "true"
          seccomp_allow_deny_syntax: "true"
          seccomp_notify: "true"
          seccomp_proxy_send_notify_fd: "true"
        os_name: Ubuntu
        os_version: "20.04"
        project: default
        server: lxd
        server_clustered: false
        server_name: nxprdapcz1mgt01
        server_pid: 1764232
        server_version: 4.0.7
        storage: btrfs
        storage_version: 4.15.1
        storage_supported_drivers:
        - name: btrfs
          version: 4.15.1
          remote: false
        - name: cephfs
          version: 12.2.13
          remote: true
        - name: dir
          version: "1"
          remote: false
        - name: lvm
          version: 2.02.176(2) (2017-11-03) / 1.02.145 (2017-11-03) / 4.41.0
          remote: false
        - name: zfs
          version: 0.8.3-1ubuntu12.9
          remote: false
        - name: ceph
          version: 12.2.13
          remote: true

</details>

# Issue description

This bug relates to https://bugs.launchpad.net/maas/+bug/1937310 

MAAS is failing to provide ID_PATHS for FC storage arrays provided by UCS.  LXD is failing to identify the disk under `/dev/disk/by-id/`  

# Steps to reproduce

 1. Install and configure MAAS for use with UCSM 
 2. Add and commission an UCS server
 3. Run `maas root node-results read system_id=<server-id>`

# Information to attach

Looks like the relevant code is here: https://github.com/lxc/lxd/blob/master/lxd/resources/storage.go#L335

**Comment by stgraber** [comment]
The logic to populate `DeviceID` is pretty straightforward. We take the block device name (should be `sda` in your case), then we list `/dev/disk/by-id/` and look at the target of those symlinks, looking for anything that points to `/dev/sda`. The lack of value in your case suggests that nothing matches.

Can you show `ls -lh /dev /dev/disk/by-id/`?

**Comment by stgraber** [comment]
@jardon can you provide the requested information please?
