### ISSUE TITLE
lxc storage volume {copy,move} ignore --target flag

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9041]
LXD 4.16:

```
lxc cluster ls
+------+-------------------------+----------+--------------+----------------+-------------+--------+-------------------+
| NAME |           URL           | DATABASE | ARCHITECTURE | FAILURE DOMAIN | DESCRIPTION | STATE  |      MESSAGE      |
+------+-------------------------+----------+--------------+----------------+-------------+--------+-------------------+
| v1   | https://10.98.30.2:8443 | YES      | x86_64       | default        |             | ONLINE | Fully operational |
+------+-------------------------+----------+--------------+----------------+-------------+--------+-------------------+
| v2   | https://10.98.30.8:8443 | YES      | x86_64       | default        |             | ONLINE | Fully operational |
+------+-------------------------+----------+--------------+----------------+-------------+--------+-------------------+

lxc storage ls
+-------+--------+-------------+---------+---------+
| NAME  | DRIVER | DESCRIPTION | USED BY |  STATE  |
+-------+--------+-------------+---------+---------+
| local | dir    |             | 3       | CREATED |
+-------+--------+-------------+---------+---------+

lxc storage volume create local vol1

lxc storage volume ls local
+--------+------+-------------+--------------+---------+----------+
|  TYPE  | NAME | DESCRIPTION | CONTENT-TYPE | USED BY | LOCATION |
+--------+------+-------------+--------------+---------+----------+
| custom | vol1 |             | filesystem   | 0       | v1       |
+--------+------+-------------+--------------+---------+----------+

lxc storage volume copy local/vol1 local/vol2 --target v2
Storage volume copied successfully!

# But copied to wrong server.
lxc storage volume ls local
+--------+------+-------------+--------------+---------+----------+
|  TYPE  | NAME | DESCRIPTION | CONTENT-TYPE | USED BY | LOCATION |
+--------+------+-------------+--------------+---------+----------+
| custom | vol1 |             | filesystem   | 0       | v1       |
+--------+------+-------------+--------------+---------+----------+
| custom | vol2 |             | filesystem   | 0       | v1       |
+--------+------+-------------+--------------+---------+----------+

# But it gets worse, move fails with an error, and...
lxc storage volume move local/vol1 local/vol3 --target v2
Error: not found

# Its renamed the original volume name!
lxc storage volume ls local
+--------+------+-------------+--------------+---------+----------+
|  TYPE  | NAME | DESCRIPTION | CONTENT-TYPE | USED BY | LOCATION |
+--------+------+-------------+--------------+---------+----------+
| custom | vol2 |             | filesystem   | 0       | v1       |
+--------+------+-------------+--------------+---------+----------+
| custom | vol3 |             | filesystem   | 0       | v1       |
+--------+------+-------------+--------------+---------+----------+
```

Reported from: https://discuss.linuxcontainers.org/t/remove-or-copy-storage-volume-between-nodes-in-a-cluster/11677

**Comment by tomponline** [comment]
Looks like the command doesn't handle `--target` at all. Although copy/move works for remotes, so should be reasonably straight forward to hook it up to use `--target`.

**Comment by stgraber** [comment]
@tomponline So I think we'll have to think this through a bit. Unlike instances, storage volumes can have the same name on multiple servers. In the context of storage volumes, `--target` is used to select what server and therefore what volume you're dealing with.

So in this case, it feels like we need a `--target` and `--destination-target` or something to both select the volume we want to move and its new location.

**Comment by aivanise** [comment]
I have tried referecing cluster members directly as separate remotes and that kinda works, but only partially, looks like --target is taken into account in some cases, but in others not
`
1 > lxc storage volume create lxd12:ee testvol
Storage volume testvol created
0 > lxc storage volume copy lxd12:ee/testvol lxd13:ee/testvol
Storage volume copied successfully!

Works, nice ;)

0 > lxc storage volume copy lxd12:ee/testvol lxd13:ee/testvol
Error: More than one cluster member has a volume named "testvol". Please target a specific member

I am, but OK ;) 

1 > lxc storage volume copy lxd12:ee/testvol lxd13:ee/testvol2 --target lxd12
Error: More than one cluster member has a volume named "testvol". Please target a specific member
1 > lxc storage volume copy ee/testvol lxd13:ee/testvol2 --target lxd12
Error: More than one cluster member has a volume named "testvol". Please target a specific member

1 > lxc storage volume delete lxd12:ee testvol
Error: More than one cluster member has a volume named "testvol". Please target a specific member
Again, I am ;)

1 > lxc storage volume delete ee testvol --target lxd12
Storage volume testvol deleted
0 > lxc storage volume delete ee testvol --target lxd13
Storage volume testvol deleted

finally ;)

`

please can you make this work, especially copy --refresh, that would be a life saver in active/passive clusters where the standby node can keep a (read-only) copy of the storage of the active member. Yes, I know about ceph, but I also know how unreliable it is ;)

**Comment by TheNeroNex** [comment]
Hello! @RKBethke and I would love to try and tackle this issue and would appreciate guidance/mentoring in how to approach a solution. After a preliminary look, we're thinking we'd start trying to implement a `--destination-target` flag as mentioned previously.

**Comment by RKBethke** [comment]
Leaving comment for assignment.  Looking forward to tackling this one!

**Comment by RKBethke** [comment]
We made a few simple changes in an attempt to solve the issue.  It looks like both `storage volume {copy, move}` were not set up to use the target command line flag, and as @stgraber mentioned, this use case would also require a `--destination-target` flag.  
Here is our branch with these current changes: https://github.com/RKBethke/lxd/tree/iss9041-lxc-storage-volume-ignore-target

Unfortunately, we are having a hard time setting up a cluster to test these changes.  The multiple-VM's on one machine approach proved to be quite CPU intensive.  What would be the best way to go about testing this branch? Would the testing infrastructure be out of scope for a non-server-equipped pair of college students?

Any advice for the path forward would be greatly appreciated.  Thanks!

**Comment by aivanise** [comment]
you can try building in nested containers instead of VMs, I've been doing that while testing and successfuly hosted a 3 member cluster in 8G of memory, probably even less

have a look at this gist: https://gist.github.com/aivanise/e6efcbdf18ca998a9dcaa808feba952f

**Comment by stgraber** [comment]
Right, running LXD inside of LXD containers works pretty well to limit usage.

For VMs, you also don't need a lot of resources, my test VMs are commonly one vCPU and 1GB of RAM running a simple Ubuntu Server image. Most laptops have at least 4GB of RAM so should be able to run a couple of those at least.

**Comment by RKBethke** [comment]
Thanks for the suggestions.  We were able to get a small cluster working to test our changes.

After adding a `--destination-target` flag to specify where the copy request would be sent to, we realized that the api copy requests lack any field to specify _where_ the volume to be copied is located.  This results in the `destination-target` searching for the source volume in itself, rather than from the `--target` cluster member.

```
lxc storage volume copy local/vol1 local/vol2 --target ubuntu-vm --destination-target ubuntu-vm2 --verbose --debug
```
```
DBUG[11-12|13:13:42] Connected to the websocket: ws://unix.socket/1.0/events?target=ubuntu-vm2 
DBUG[11-12|13:13:42] Sending request to LXD                   method=POST url="http://unix.socket/1.0/storage-pools/local/volumes/custom?target=ubuntu-vm2" etag=
DBUG[11-12|13:13:42] 
	{
		"config": {},
		"description": "",
		"name": "vol2",
		"type": "custom",
		"source": {
			"name": "vol1",
			"type": "copy",
			"pool": "local",
			"certificate": "",
			"volume_only": false,
			"refresh": false
		},
		"content_type": "filesystem"
	} 
...
    "err": "Source volume doesn't exist",
    "location": "ubuntu-vm2"
```
We know copying can be done via two separate remotes, so is there a mechanism to do this transfer without changing the "source" (`api.StorageVolumeSource`) structure?  If not, perhaps we could add a field to the underlying structure and update the backend copy method to use it.  
Any insight would be greatly appreciated.

**Comment by stgraber** [comment]
Ah yeah, this will make things a tiny bit more interesting to hook everything up right...
So you're absolutely correct that you'll need to add a field (I'd call it `Location`) to `api.StorageVolumeSource`.

That way when LXD gets the volume creation request it can tell that it needs to copy it and from where.

Where things will get interesting is that LXD will then need to deal with an internal volume migration request if Location doesn't match the local machine. We have a bunch of migration logic for storage volumes already but this will need a bit of plumbing to effectively turn this copy request into an internal cluster migration request.

We'll also need to make sure we have remote filesystems (ceph/cephfs) handled properly as for those volumes are always available on every system and Location is therefore meaningless, but that's something to worry about later.
