### ISSUE TITLE
Containers with gpu device fail to start when connected to docking station

### ISSUE THREAD

**Issue by bigcat2014** [lxc/lxd#9047]
* Distribution: Ubuntu Linux
 * Distribution version: 20.04
 * lxc info: https://pastebin.ubuntu.com/p/VNv2NWPRWM/
 
# Issue description

When starting a container with a gpu device while plugged into my docking station, the container fails to start with the following error message:

> Error: Failed preparing container for start: Failed to start device "gpu": Failed to add device information for "/sys/class/drm/card0/device": Failed to read "/sys/class/drm/card0/device/device": read /sys/class/drm/card0/device/device: is a directory
Try `lxc info --show-log test` for more info

nvidia driver version: 465.31

gpu section of profile:
```
  gpu:
    pci: "0000:01:00.0"
    type: gpu
```

When not connected to the dock:
* `ls /dev/dri` on host: `by-path  card0  card1  card2  card3  card4  card5  renderD128  renderD129`
* `ls /dev/dri` in working container: `card5  renderD129`
* `ls /sys/class/drm/card0/device`: `driver  driver_override  drm  modalias  power  subsystem  uevent`

Once connected to the dock:
* `ls /dev/dri` on host: `by-path  card0  card1  card2  card3  card4  card5  renderD128  renderD129`
* `ls /dev/dri` in working container: `card5  renderD129`
* `ls /sys/class/drm/card0/device`: `device driver  driver_override  drm  modalias  power  subsystem  uevent`
* `ls /sys/class/drm/card0/device/device`:
```
2-1.1:1.0  2-1.1:1.4   avoid_reset_quirk    bDeviceProtocol  bMaxPower           configuration  devpath    idVendor      port     removable  speed      urbnum
2-1.1:1.1  2-1.1:1.5   bcdDevice            bDeviceSubClass  bNumConfigurations  descriptors    driver     ltm_capable   power    remove     subsystem  version
2-1.1:1.2  2-1.1:1.6   bConfigurationValue  bmAttributes     bNumInterfaces      dev            ep_00      manufacturer  product  rx_lanes   tx_lanes
2-1.1:1.3  authorized  bDeviceClass         bMaxPacketSize0  busnum              devnum         idProduct  maxchild      quirks   serial     uevent
```

Once connected to the dock, this nested device path is created, however, it is a folder instead of a file.

I've tried specifying the gpu device in my profile in the following ways:
* Device type only
* Device type and pci: "0000:01:00.0"
* Device type and id: 5
* Device type, vendorid: 10de, productid: 1f99

But no matter how I specify, it always tries card0 and fails on the device folder.
Based on the discussion [here](https://discuss.linuxcontainers.org/t/gpu-id-from-1-not-0/5841/7) I was under the impression that specifying id specifies the card number to use in /dev/dri, which seems to be card 5 in my working containers, but it still checks card0 when id is specified as 5

Another thing that I've tried, which didn't seem to change anything, is creating the unix-char device on my own instead of relying on lxd to create it for me by adding the following to my profile:
```
  card5:
    path: /dev/dri/card5
    gid: 44
    type: unix-char
```
This was found in [this](https://blog.simos.info/how-to-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop/#post-1808) blog post in the Configuring graphics and graphics acceleration section.

One last thing that I thought was odd was the device minor in the output of `cat /proc/driver/nvidia/gpus/0000\:01\:00.0/information`:
```
Model: 		 NVIDIA GeForce GTX 1650
IRQ:   		 158
GPU UUID: 	 GPU-efd152f1-bc0a-f859-ddce-7bca3be61ad6
Video BIOS: 	 90.17.4c.00.26
Bus Type: 	 PCIe
DMA Size: 	 47 bits
DMA Mask: 	 0x7fffffffffff
Bus Location: 	 0000:01:00.0
Device Minor: 	 0
GPU Excluded:	 No
```
Which based on [this](https://github.com/lxc/lxd/issues/3950#issuecomment-337540166) comment I am led to believe is how lxd figures out which card number to use. Maybe this is why it keeps trying to use card0 instead of 5, even with id specified?

**Comment by stgraber** [comment]
Can you show:
 - ls -lh /sys/class/drm/
 - ls -lh /sys/class/drm/card0/
 - ls -lh /sys/class/drm/card0/device/
 - ls -lh /sys/class/drm/card0/device/device

/sys is always quite messy so just knowing the content of the directory without seeing all symlinks involved makes it difficult to debug.

**Comment by bigcat2014** [comment]
Here is the output from those commands
ls -lh /sys/clas/drm/
```
total 0
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card0 -> ../../devices/platform/evdi.0/drm/card0
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card0-DVI-I-1 -> ../../devices/platform/evdi.0/drm/card0/card0-DVI-I-1
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card1 -> ../../devices/platform/evdi.1/drm/card1
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card1-DVI-I-2 -> ../../devices/platform/evdi.1/drm/card1/card1-DVI-I-2
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card2 -> ../../devices/platform/evdi.2/drm/card2
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card2-DVI-I-3 -> ../../devices/platform/evdi.2/drm/card2/card2-DVI-I-3
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card3 -> ../../devices/platform/evdi.3/drm/card3
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card3-DVI-I-4 -> ../../devices/platform/evdi.3/drm/card3/card3-DVI-I-4
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card4 -> ../../devices/pci0000:00/0000:00:02.0/drm/card4
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card4-eDP-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card4/card4-eDP-1
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card4-HDMI-A-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card4/card4-HDMI-A-1
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card5 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card5
lrwxrwxrwx 1 root root    0 Jul 26 13:51 card5-DP-1 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card5/card5-DP-1
lrwxrwxrwx 1 root root    0 Jul 26 13:51 renderD128 -> ../../devices/pci0000:00/0000:00:02.0/drm/renderD128
lrwxrwxrwx 1 root root    0 Jul 26 13:51 renderD129 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/renderD129
-r--r--r-- 1 root root 4.0K Jul 26 13:51 version
```

ls -lh /sys/class/drm/card0/
```
total 0
drwxr-xr-x 3 root root    0 Jul 26 13:51 card0-DVI-I-1
-r--r--r-- 1 root root 4.0K Jul 26 13:51 dev
lrwxrwxrwx 1 root root    0 Jul 26 13:51 device -> ../../../evdi.0
drwxr-xr-x 2 root root    0 Jul 26 15:39 power
lrwxrwxrwx 1 root root    0 Jul 26 13:51 subsystem -> ../../../../../class/drm
-rw-r--r-- 1 root root 4.0K Jul 26 13:51 uevent
```

ls -lh /sys/class/drm/card0/device
```
total 0
lrwxrwxrwx 1 root root    0 Jul 26 13:53 device -> ../../pci0000:00/0000:00:14.0/usb2/2-1/2-1.1
lrwxrwxrwx 1 root root    0 Jul 26 13:51 driver -> ../../../bus/platform/drivers/evdi
-rw-r--r-- 1 root root 4.0K Jul 26 13:52 driver_override
drwxr-xr-x 3 root root    0 Jul 26 13:51 drm
drwxr-xr-x 4 root root    0 Jul 26 13:53 i2c-9
-r--r--r-- 1 root root 4.0K Jul 26 13:52 modalias
drwxr-xr-x 2 root root    0 Jul 26 13:52 power
lrwxrwxrwx 1 root root    0 Jul 26 13:51 subsystem -> ../../../bus/platform
-rw-r--r-- 1 root root 4.0K Jul 26 13:51 uevent
```

ls -lh /sys/class/drm/card0/device/device
```
total 0
drwxr-xr-x 5 root root    0 Jul 26 13:53 2-1.1:1.0
drwxr-xr-x 3 root root    0 Jul 26 13:53 2-1.1:1.1
drwxr-xr-x 5 root root    0 Jul 26 13:53 2-1.1:1.2
drwxr-xr-x 3 root root    0 Jul 26 13:53 2-1.1:1.3
drwxr-xr-x 3 root root    0 Jul 26 13:53 2-1.1:1.4
drwxr-xr-x 5 root root    0 Jul 26 13:53 2-1.1:1.5
drwxr-xr-x 5 root root    0 Jul 26 13:53 2-1.1:1.6
-rw-r--r-- 1 root root 4.0K Jul 26 13:53 authorized
-rw-r--r-- 1 root root 4.0K Jul 26 13:53 avoid_reset_quirk
-r--r--r-- 1 root root 4.0K Jul 26 13:53 bcdDevice
-rw-r--r-- 1 root root 4.0K Jul 26 13:53 bConfigurationValue
-r--r--r-- 1 root root 4.0K Jul 26 13:53 bDeviceClass
-r--r--r-- 1 root root 4.0K Jul 26 13:53 bDeviceProtocol
-r--r--r-- 1 root root 4.0K Jul 26 13:53 bDeviceSubClass
-r--r--r-- 1 root root 4.0K Jul 26 13:53 bmAttributes
-r--r--r-- 1 root root 4.0K Jul 26 13:53 bMaxPacketSize0
-r--r--r-- 1 root root 4.0K Jul 26 13:53 bMaxPower
-r--r--r-- 1 root root 4.0K Jul 26 13:53 bNumConfigurations
-r--r--r-- 1 root root 4.0K Jul 26 13:53 bNumInterfaces
-r--r--r-- 1 root root 4.0K Jul 26 13:53 busnum
-r--r--r-- 1 root root 4.0K Jul 26 13:53 configuration
-r--r--r-- 1 root root  65K Jul 26 13:53 descriptors
-r--r--r-- 1 root root 4.0K Jul 26 13:53 dev
-r--r--r-- 1 root root 4.0K Jul 26 13:53 devnum
-r--r--r-- 1 root root 4.0K Jul 26 13:53 devpath
lrwxrwxrwx 1 root root    0 Jul 26 13:53 driver -> ../../../../../../bus/usb/drivers/usb
drwxr-xr-x 3 root root    0 Jul 26 13:53 ep_00
-r--r--r-- 1 root root 4.0K Jul 26 13:53 idProduct
-r--r--r-- 1 root root 4.0K Jul 26 13:53 idVendor
-r--r--r-- 1 root root 4.0K Jul 26 13:53 ltm_capable
-r--r--r-- 1 root root 4.0K Jul 26 13:53 manufacturer
-r--r--r-- 1 root root 4.0K Jul 26 13:53 maxchild
lrwxrwxrwx 1 root root    0 Jul 26 13:53 port -> ../2-1:1.0/2-1-port1
drwxr-xr-x 2 root root    0 Jul 26 13:53 power
-r--r--r-- 1 root root 4.0K Jul 26 13:53 product
-r--r--r-- 1 root root 4.0K Jul 26 13:53 quirks
-r--r--r-- 1 root root 4.0K Jul 26 13:53 removable
--w------- 1 root root 4.0K Jul 26 13:53 remove
-r--r--r-- 1 root root 4.0K Jul 26 13:53 rx_lanes
-r--r--r-- 1 root root 4.0K Jul 26 13:53 serial
-r--r--r-- 1 root root 4.0K Jul 26 13:53 speed
lrwxrwxrwx 1 root root    0 Jul 26 13:53 subsystem -> ../../../../../../bus/usb
-r--r--r-- 1 root root 4.0K Jul 26 13:53 tx_lanes
-rw-r--r-- 1 root root 4.0K Jul 26 13:53 uevent
-r--r--r-- 1 root root 4.0K Jul 26 13:53 urbnum
-r--r--r-- 1 root root 4.0K Jul 26 13:53 version
```

**Comment by stgraber** [comment]
Ah, looks like your dock may have a displaylink type graphics card. I don't think we have any of those in our test hardware and so never had to deal with a graphics card on USB before.

**Comment by stgraber** [comment]
I'm poking at the logic a bit and will send you a small static test binary to run so we can check that we're properly detecting those in the future.

**Comment by bigcat2014** [comment]
Yes, correct. For completeness, the dock is a ThinkPad USB 3.0 ultra dock, model # DK1523 and my PC is a System76 Gazelle, gaze15. Using the DisplayLink 5.4 driver

**Comment by bigcat2014** [comment]
Yes, here's the output after running
https://pastebin.ubuntu.com/p/P4QVzThMSn/

**Comment by stgraber** [comment]
Hmm, okay, so it doesn't crash but it's also not properly recording the USB address... Let's see what's up with that.

**Comment by stgraber** [comment]
@bigcat2014 I've updated the binary at that URL, can you run the new version?

**Comment by bigcat2014** [comment]
Yes, here's the new output
https://pastebin.ubuntu.com/p/jxxhKdjVJC/

**Comment by stgraber** [comment]
`usb_address: "2:6"`

Can you show `lsusb -tv` just to confirm this is correct?

**Comment by bigcat2014** [comment]
This is the output when running `lsusb -tv`
```
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/8p, 10000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 5000M
        ID 17ef:1014 Lenovo 
        |__ Port 1: Dev 6, If 0, Class=Vendor Specific Class, Driver=usbfs, 5000M
            ID 17e9:4340 DisplayLink 
        |__ Port 1: Dev 6, If 1, Class=Application Specific Interface, Driver=usbfs, 5000M
            ID 17e9:4340 DisplayLink 
        |__ Port 1: Dev 6, If 2, Class=Audio, Driver=snd-usb-audio, 5000M
            ID 17e9:4340 DisplayLink 
        |__ Port 1: Dev 6, If 3, Class=Audio, Driver=snd-usb-audio, 5000M
            ID 17e9:4340 DisplayLink 
        |__ Port 1: Dev 6, If 4, Class=Audio, Driver=snd-usb-audio, 5000M
            ID 17e9:4340 DisplayLink 
        |__ Port 1: Dev 6, If 5, Class=Communications, Driver=cdc_ncm, 5000M
            ID 17e9:4340 DisplayLink 
        |__ Port 1: Dev 6, If 6, Class=CDC Data, Driver=cdc_ncm, 5000M
            ID 17e9:4340 DisplayLink 
        |__ Port 4: Dev 3, If 0, Class=Hub, Driver=hub/4p, 5000M
            ID 17ef:1015 Lenovo 
            |__ Port 1: Dev 5, If 0, Class=Hub, Driver=hub/2p, 5000M
                ID 0bda:0409 Realtek Semiconductor Corp. 
            |__ Port 4: Dev 4, If 0, Class=Hub, Driver=hub/2p, 5000M
                ID 0bda:0409 Realtek Semiconductor Corp. 
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/16p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    |__ Port 1: Dev 4, If 0, Class=Hub, Driver=hub/4p, 480M
        ID 17ef:1014 Lenovo 
        |__ Port 4: Dev 5, If 0, Class=Hub, Driver=hub/4p, 480M
            ID 17ef:1015 Lenovo 
            |__ Port 4: Dev 8, If 0, Class=Hub, Driver=hub/4p, 480M
                ID 0bda:5409 Realtek Semiconductor Corp. 
            |__ Port 2: Dev 6, If 0, Class=Human Interface Device, Driver=usbhid, 12M
                ID 0c45:5004 Microdia 
            |__ Port 2: Dev 6, If 1, Class=Human Interface Device, Driver=usbhid, 12M
                ID 0c45:5004 Microdia 
            |__ Port 3: Dev 7, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
                ID 1bcf:0053 Sunplus Innovation Technology Inc. 
            |__ Port 1: Dev 9, If 0, Class=Hub, Driver=hub/4p, 480M
                ID 0bda:5409 Realtek Semiconductor Corp. 
        |__ Port 2: Dev 10, If 0, Class=Chip/SmartCard, Driver=usbfs, 480M
            ID 0bda:0165 Realtek Semiconductor Corp. 
    |__ Port 8: Dev 2, If 1, Class=Video, Driver=uvcvideo, 480M
        ID 04f2:b685 Chicony Electronics Co., Ltd 
    |__ Port 8: Dev 2, If 0, Class=Video, Driver=uvcvideo, 480M
        ID 04f2:b685 Chicony Electronics Co., Ltd 
    |__ Port 14: Dev 3, If 0, Class=Wireless, Driver=btusb, 12M
        ID 8087:0aaa Intel Corp. 
    |__ Port 14: Dev 3, If 1, Class=Wireless, Driver=btusb, 12M
        ID 8087:0aaa Intel Corp.
```

**Comment by stgraber** [comment]
All good, bus 2 device 6 is indeed the DisplayLink controller.

**Comment by bigcat2014** [comment]
Based on your commit message "Add support for USB GPU" I just want to make sure the correct issue is solved in your fix.
My GPU is internal to the laptop, not running over USB from the docking station.
I don't know the details of how the GPU is being referenced or used for the gpu devices in lxd, but I would think you would want to point the lxc gpu device to the GPU itself, right, not the DisplayLink controller? Unless I'm misunderstanding how this is working

**Comment by stgraber** [comment]
Yeah, basically when dealing with GPUs, LXD uses our resources API to fetch a list of all GPUs and then filters it down based on your criteria, in your case, a PCI address.

Because it was failing on USB GPUs, it never managed to pull a full device list and so failed even though you're not trying to use a USB GPU.

Now with this change, it'd in theory be possible for someone to directly use a USB GPU, though, that's not a very likely scenario given those are usually just offering basic compressed VGA output and don't offer any compute or acceleration.

**Comment by bigcat2014** [comment]
Ah, ok. That makes more sense. Thanks!
