### ISSUE TITLE
Support mounting additional block devices into containers

### ISSUE THREAD

**Issue by hallyn** [lxc/lxd#906]
I *think* we want to implement a way in lxd to do this for lxc.mount.entry = /dev/vda2 [...].  lxd would have to insert the mounts or add lxc.mount.entries for shared entries which it sets up before starting the container.

On the other hand, we might simply want to wait for the kernel support for safe block device mounting in unprivileged containers.

**Comment by kapilt** [comment]
workaround here is usability helps adoptions (another on that note, double
plus if lxc config keys/values are documented/api discoverable), kernel
wait is always unknown delay + distro ship delay + lxd/c expose delay, from
a time perspective. ie. doing it in lxc hook space before namespaced pid 1
sounds like a win.

**Comment by stgraber** [comment]
Adding support for this through the existing shmounts facility should be pretty simple, so yeah, I think we should do it.
