### ISSUE TITLE
Can't delete container with btrfs subvolumes

### ISSUE THREAD

**Issue by xose** [lxc/lxd#907]
It is currently not possible to delete a container when the rootfs has btrfs subvolumes (lxc/lxc#210 ?)

But the default Ubuntu Vivid and Wily images for LXD automatically create one such subvolume on boot, making it impossible to delete a container without manually removing the subvolume first.

The error message is also not helpful, doesn't give any clue as to what may have gone wrong:

```
$ lxd-images import ubuntu vivid --alias ubuntu
$ lxc launch ubuntu test
Creating container...done
Starting container...done
[ Wait for the container to boot... ]
$ lxc delete test
error: exit status 1
```

The subvolume, and manually deleting it to destroy the container:

```
$ sudo btrfs subvolume list /
ID 257 gen 1623 top level 5 path @
ID 258 gen 1617 top level 5 path @home
ID 270 gen 1620 top level 257 path var/lib/lxd/images/06ec182c32946bb8f990068ac3da1d60eb65b062ee4a162f7e1eb60d3a3fb5da.btrfs
ID 273 gen 1623 top level 257 path var/lib/lxd/lxc/test
ID 274 gen 1621 top level 257 path var/lib/lxd/lxc/test/rootfs/var/lib/machines

$ sudo btrfs subvolume delete /var/lib/lxd/lxc/test/rootfs/var/lib/machines
$ lxc delete test
$
```

**Comment by pcdummy** [comment]
Why and how do they get created?

We could detect if $rootfs/var/lib/machines is a btrfs subvolume and delete it in the btrfs storage driver.

What do you think @stgraber

**Comment by kapilt** [comment]
underlying lxc will do this, however if lxd if running as non root,  it
needs a mount option to btrfs to support user self owned subvolume deletion.

**Comment by xose** [comment]
They are created by systemd 219+. From their release notes:

```
        * tmpfiles gained support for a new "v" line type for creating
          btrfs subvolumes. If the underlying file system is a legacy
          file system, this automatically degrades to creating a
          normal directory. Among others /var/lib/machines is now
          created like this at boot, should it be missing.
```

I have just tried adding the mount option "user_subvol_rm_allowed" to fstab and rebooted, but it doesn't seem to be working either:

```
$ mount | grep btrfs
/dev/sda2 on / type btrfs (rw,subvol=@,user_subvol_rm_allowed)
/dev/sda2 on /home type btrfs (rw,subvol=@home,user_subvol_rm_allowed)
$ lxc delete test
error: exit status 1
```

**Comment by stgraber** [comment]
We should add some logic to the LXD btrfs driver to do recursive subvolume deletion when removing the container (or when restoring it to a previous state).

**Comment by pcdummy** [comment]
@xose i implement the logic to handle subvolumes in a container, but i can't replicate your error as my vivid container doesn't create /var/lib/machines (i even don't know how it does that).

Can you give me more informations about your installation?

**Comment by stgraber** [comment]
It does here when I'm on btrfs. systemd creates that subvolume at some point on first container boot.

**Comment by stgraber** [comment]
@pcdummy did you make any progress on this? if you don't have the time, do you have a partial branch I could take over?

**Comment by pcdummy** [comment]
Sorry, i don't have the time to complete this. :-1: 

This is what i was working on:
https://github.com/lxc/lxd/commit/6473377deaef95fbaee0e6d45943232db23f2640

The important part is **getSubVolumes** there, it uses `btrfs subvolume list -o path` as you told me.

**Comment by stgraber** [comment]
thanks, I'll pick it up from there.
