### ISSUE TITLE
Proxy device with NAT enabled has a single firewall rule per port

### ISSUE THREAD

**Issue by morphis** [lxc/lxd#9073]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: `5.8.0-1037-oracle #38~20.04.1-Ubuntu`
   * LXC version: 
   * LXD version: 4.0.7
   * Storage backend in use: zfs

# Issue description

Adding the following proxy device to a container causes one iptables rule in the nat table to be generated per port:

```
  turn:
    connect: udp:240.39.0.109:60000-60100
    listen: udp:10.0.0.39:60000-60100
    nat: "true"
    type: proxy
```

```
$ sudo iptables -S -t nat
...
-A POSTROUTING -s 240.39.0.109/32 -d 240.39.0.109/32 -p udp -m udp --dport 60100 -m comment --comment "generated for LXD container juju-111acc-1 (turn)" -j MASQUERADE
....
-A POSTROUTING -s 240.39.0.109/32 -d 240.39.0.109/32 -p udp -m udp --dport 60000 -m comment --comment "generated for LXD container juju-111acc-1 (turn)" -j MASQUERADE
```

# Steps to reproduce

See above

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
I believe we could add an optimisation to add a single rule per proxy range, e.g.

```
sudo iptables -t nat -A POSTROUTING -s 10.128.213.2 -d 10.128.213.2 -p tcp --dport 80:81 -j MASQUERADE
```

However as the proxy config allows for multiple ranges, we would need to restructure how the proxy device parses config, as right now it is expanding each range into a separate connect address/port, which is why when it gets to the firewall driver it adds them as individual rules.

**Comment by stgraber** [comment]
Ah yeah, that must be a case where when we use forkproxy we need to split them but for the firewall case we could deal with the ranges, so expanding should be made to append later I guess.

**Comment by tomponline** [comment]
@markylaing let me know if you need any intro/help on this issue.

**Comment by simondeziel** [comment]
> However testing iptables behaviour with DNAT destination port ranges, they are treated more like "pools" of destinations and are picked (seemingly) randomly as an endpoint for an incoming connection on any of the listen ports.

This port load-balancing behaviour seems to only occur when the `--to` includes a port range. If the `--to` argument simply points to an IP, the port won't be altered.

```
# no port load-balancing
iptables -t nat -D PREROUTING -i wg-admin -d 172.24.20.1 -p tcp --dport 90:91 -j DNAT --to 172.24.22.80

# port load-balancing
iptables -t nat -D PREROUTING -i wg-admin -d 172.24.20.1 -p tcp --dport 90:91 -j DNAT --to 172.24.22.80:90-91
```

**Comment by tomponline** [comment]
Yep thats another optimisation we can/could do. But wouldn't help with this particular issue.

**Comment by simondeziel** [comment]
> Yep thats another optimisation we can/could do. But wouldn't help with this particular issue (as the OP is using a connect port range).

I am assuming the listen and connect port ranges are identical most of the time which would allow to not have them repeated in the `DNAT` target and run into the undesired load-balancing behaviour.

**Comment by tomponline** [comment]
Oh I see what you mean, remove the destination port entirely (I'd read the .80 as a single target port 80) if its the same as the listen port ranges. Yes that could be a helpful optimisation, assuming it is guaranteed not to have the load balancing behaviour (is that documented anywhere?)

**Comment by simondeziel** [comment]
man 8 iptables-extensions:

> DNAT
>        ...
>        --to-destination [ipaddr[-ipaddr]][:port[-port]]
>               which can specify a single new destination IP address, an inclusive range of IP addresses. Optionally a port range, if the rule also specifies one of the following protocols: tcp, udp, dccp or sctp.  **If no port range is  specified,  then  the  destination 
>               port  will never be modified.** ...

**Comment by tomponline** [comment]
Perfect! Lets add that optimisation as well as the MASQUERADE one @markylaing 

We can also do the same optimisation if there's only one connect port per listen range too. 

Thanks @simondeziel

**Comment by tomponline** [comment]
> Are we now accepting these values because each corresponding range is valid on it's own?

No lets ignore the optimisation for `5000-5005 -> 5000` as its not allowed in the current config validation, and so is outside of the scope of this change. Thanks for checking.

**Comment by tomponline** [comment]
We could still add the optimisation for a proxy device with a single connect port, then a user could always add another `proxy` device with just `5000-5005 -> 5000` if they needed that configuration.
