### ISSUE TITLE
add group to lxd

### ISSUE THREAD

**Issue by vince06fr** [lxc/lxd#908]
it could be a great feature if we can select a group of containers for running the same command on all containers of this group

exemple of implementation :
add containers to a group
`lxc groupadd <group's name> <container's name>, <...>`

Now, we can execute command on all containers of the group
example:
stop all container of the group
`lxc stop <group's name>`
execute an upgrade on all the containers of the group : 
`lxc exec <group's name> -- apt-get upgrade`
etc..

the lxc list command should show the containers list sorted by group

**Comment by srkunze** [comment]
This really would come in handy when scaling out.

I am currently working on LXD containers for an super-easy setup of a so-called PostgreSQL BDR group. http://bdr-project.org/docs/next/quickstart-enabling.html describes how to setup each node which is quite cumbersome.

With proper templating support though, LXD groups could make scaling out extremely easy.

Just add a new BDR instance to a LXD group, and the container finds its peers automatically.

**Comment by stgraber** [comment]
I expect that for some users, the new concept of projects (name not final) will work fine for this.
You'll effectively be able to create a new project, create your containers in there and if you want something to apply to them all, just use `lxc start --all` or `lxc stop --all` while looking at this project.

Closing in favor of #2689

**Comment by nanjj** [comment]
```
lxc group create ubuntu:18.04 mysql \
  --policy anti-affinity \
  --profile mysql
lxc group up mysql 3 # make member number to 3
lxc group up mysql +1 # add 1 member
lxc group up mysql -1 # remove 1 member
lxc stop mysql # stop group and its members
lxc delete mysql # delete group and it's members
```
here policy can be `affinity`, `anti-affinity`, or `none`, by default it's `none`.
