### ISSUE TITLE
Multiple problems faced in 0.7 (default version one gets from ubuntu repository)

### ISSUE THREAD

**Issue by ranadeep47** [lxc/lxd#909]
I have just started using `lxd` and this is my first experience with containers. I have faced the following problems yesterday
* lxc-tools - `lxc` cmd tool works, but all the `lxc-*` tools wont, they dont recognise running containers, wont attach to containers and `lxc-ls --fancy`doesnt show any containers. How can i make `lxc-*` work, i really want to experiment with `lxc-clone` and `lxc-snapshot`.
* im using ubuntu 15.04 and i have installed lxd using `apt-get install lxd` and i have `lxd 0.7` now, but the latest version seems to be `0.12` ,is there any way i can update than removing the current version and building the latest version from scratch
* I have used `lxd snapshot <source> <snap name> ` (mind the tool's version is 0.7) and i have a new folder called `snapshot` in the container's folder. But im not sure if it used btrfs or overlayfs. Also when i `du -sh` it shows me the snapshot is the size of the container's rootfs, its like its copied rather than just a reference, is it the du tool here or the snapshot really is a copy ? . Also using `--stateful` crashes the snapshot process with an error.
* Also i couldn't stop the containers using `lxc stop <container>` , it hangs there indefinitely. Right now im killing the init pid.

**Comment by tych0** [comment]
Hello,

On Tue, Jul 28, 2015 at 09:22:12PM -0700, Ranadeep wrote:
> I have just started using `lxd` and this is my first experience with containers. I have faced the following problems yesterday
> * lxc-tools - `lxc` cmd tool works, but all the `lxc-*` tools wont, they dont recognise running containers, wont attach to containers and `lxc-ls --fancy`doesnt show any containers. How can i make `lxc-*` work, i really want to experiment with `lxc-clone` and `lxc-snapshot`.

The lxc-* tools don't work with lxd; you should just use the `lxc`
equivalents (`lxc snapshot` and `lxc copy`).

> * im using ubuntu 15.04 and i have installed lxd using `apt-get install lxd` and i have `lxd 0.7` now, but the latest version seems to be `0.12` ,is there any way i can update than removing the current version and building the latest version from scratch

https://github.com/lxc/lxd#getting-started-with-lxd

> * I have used `lxd snapshot <source> <snap name> ` (mind the tool's version is 0.7) and i have a new folder called `snapshot` in the container's folder. But im not sure if it used btrfs or overlayfs. Also when i `du -sh` it shows me the snapshot is the size of the container's rootfs, its like its copied rather than just a reference, is it the du tool here or the snapshot really is a copy ? . Also using `--stateful` crashes the snapshot process with an error.

If you had /var/lib/lxd mounted as a btrfs subvolume, it should be
btrfs. We don't have any overlayfs specific backend right now, so for
that (and everything else) it would just be a copy.

> * Also i couldn't stop the containers using `lxc stop <container>` , it hangs there indefinitely. Right now im killing the init pid.

This is a bug fixed in upstream systemd:
https://github.com/lxc/lxd/issues/687

**Comment by stgraber** [comment]
Note that btrfs support requires a version newer than 0.7 (0.9 I believe).

**Comment by ranadeep47** [comment]
@tych0 Thanks, dont kow how i missed it, i did apt-get upgrade lxd and now its 0.13.
`/var/lib/lxd# lxc snapshot source snap --stateful` gives me `error: checkpoint failed` . But without stateful it makes a snapshot.

Also i request any one of you to mention in the documentation about mounting the /var/lib/lxd as btrfs subvolume to get the benefit of snapshot. A small guide if time permits.

Also as now im using `lxc stop container --force` to stop it.

**Comment by tych0** [comment]
On Wed, Jul 29, 2015 at 01:26:58AM -0700, Ranadeep wrote:
> @tych0 Thanks, dont kow how i missed it, i did apt-get upgrade lxd and now its 0.13.
> `/var/lib/lxd# lxc snapshot source snap --stateful` gives me `error: checkpoint failed` . But without stateful it makes a snapshot.

Yes, a stateful snapshot involves the memory state, which requires you
to `apt-get install criu`; a non --stateful snapshot is just a
snapshot of the disk.

**Comment by fninja** [comment]
@stgraber @tych0 it would be wonderful if lxc / lxd could inform me why `--stateful` is failing, if criu is not installed!
Right now, `--stateful` will just fail with `error: checkpoint failed`, which is not so helpful.

**Comment by tych0** [comment]
On Mon, May 09, 2016 at 03:02:56AM -0700, fninja wrote:
> @stgraber @tych0 it would be wonderful if lxc / lxd could inform me why `--stateful` is failing, if criu is not installed!
> Right now, `--stateful` will just fail with `error: checkpoint failed`, which is not so helpful.

Yes, it seems we do a special check for migration, but not for
stateful snapshots/start stop. I'll send a patch for a check shortly,
thanks!
