### ISSUE TITLE
Setting ENV vars for server via lxc.environment?

### ISSUE THREAD

**Issue by emilebosch** [lxc/lxd#910]
Is there currently a way to set env vars for the server? Unfortuneately i can't see a way to set an ENV variable to be set when booting a server. If i understand correctly its trivial to add it it via `config.set lxc.environment=RAILS_ENV=production` but why isn't there are simple config env call ?

**Comment by stgraber** [comment]
So I do have a branch which adds support to set environment variables for LXD. Those variables will be set for pid1 (lxc.environment) and on any exec command.

However note that init systems typically strip the environment they receive, so don't expect the environment to survive for things that are spawned by the init system of the container.

**Comment by emilebosch** [comment]
Thanks for your quick response! I also want to thank you for building this simple tool. Especially after trying to port existing solutions such as my rails environments to this and the least amount of pain compared to docker/rocket/insert something here.

I'd love to check that branch if possible. Also i am wondering even though im feeding raw lxc settings why doesn't it show up? Is it because init strips the ENV settings like you explain? I've used this:

```
lxc config set my-container raw.lxc 'lxc.environment = RAILS_ENV=production'
```
?

**Comment by stgraber** [comment]
Hi,

Yes, you're hitting the case where init ignores its own environment and doesn't propagate to the child processes.

My branch will make it possible to do "lxc config set my-container environment.RAILS_ENV production" which will expand to lxc.environment as you're currently doing as well as set the environment variable for you in any exec call.

I've been working on that mostly to have http_proxy and https_proxy set properly for the user. The fact that init systems don't propagate their environment to their children makes the feature not nearly as useful as it could be for other cases (like yours).

**Comment by emilebosch** [comment]
True, but having the env available in both init (even if its ignored) and in the exec calls really makes it a lot easier to come to a simple painless solution. Since we're migrating from heroku (which uses LXC and env variables for setting configuration in their apps, it brings us closed to a painless experience migrating.  We have about 20 env vars for a typical rails app. 

I think however other uses might want to be able to kill the default env vars in `lxc exec` calls just to start clean maybe.

I would love a workflow like this:

1. lxc config container set environment.RAILS_ENV=production (repeat until done)
2. lxc exec  container rake (passes the env varibales)

and optionally uses `lxc exec container -strip-env` in order to start clean exec not passing the default variables.

Where can i checkout the branch?
