### ISSUE TITLE
Keep lxd able to bind when network changes

### ISSUE THREAD

**Issue by dcore94** [lxc/lxd#9102]
# Required information

 * Distribution: ubuntu 20.04
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * LXD version: 4.16
   
# Issue description

I noticed that when working out of office with mobile hotspot, I'm unable to run lxc/lxd. `lxc list` just hanges as any other command.
I run my lxd in cluster mode and it looks like lxd is unable to start because it doesn't find the bind address to be correct because of the network change. Getting back home on the usual network everything works again.
I infer this hypothesis from the log:
```
ago 09 12:33:35 ontheroad-work lxd.daemon[25973]: t=2021-08-09T12:33:35+0200 lvl=eror msg="Failed to start the daemon: Bind network address: listen tcp 192.168.1.90:8443: bind: cannot assign requested a>
ago 09 12:33:35 ontheroad-work lxd.daemon[25973]: Error: Bind network address: listen tcp 192.168.1.90:8443: bind: cannot assign requested address
ago 09 12:33:36 ontheroad-work lxd.daemon[25829]: => LXD failed to start
ago 09 12:33:36 ontheroad-work systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=1/FAILURE
ago 09 12:33:36 ontheroad-work systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
```

Is there a quick solution for this? Maybe writing directly to the sqlite3 DB? I don't think I'll be able to control the hotspost delivered IP address and network settings....
Thanks a lot.

**Comment by tomponline** [comment]
Is the IP address on your LAN changing? The cluster address of a member shouldn't change, so that might be the issue.

**Comment by dcore94** [comment]
Yes, that's exactly the issue ... maybe I haven't expressed myself clearly enough. I'd like to know if there is a workaround for this to fix it whenever I'm away from my original LAN ... thanks.

**Comment by tomponline** [comment]
The LXD cluster requires that each member's address doesn't change (although I believe you can use a DNS name for each member's address too although that doesn't sound like it would help in this situation).

I'd like to understand more about your setup. You say you're using a cluster, but also that you want to use LXD whilst you're not connected directly to your LAN. How are you connecting to the other members of the cluster when you are out? As aside from the listen address problem, even if LXD were able to bind to that address (which could be achieved by using either https://sysctl-explorer.net/net/ipv4/ip_nonlocal_bind/) or just adding that as an IP alias to your local machine, if LXD cannot communicate with the other cluster members it won't be operational.

**Comment by dcore94** [comment]
Legitimate curiosity :-) I actually use a cluster in order to keep the same structure, deployment as our production deployment. This helps when experimenting cluster specific functionality. But most of the time (for example when testing new software) I still use only one physical node thus actually falling back to a standard usage.
So, maybe trying to restate the question: what I'am actually looking for is the possibility to be rigid as a cluster or not depending on external conditions.
I'll give a try to "just adding that as an IP alias to your local machine" .... and let you know

**Comment by dcore94** [comment]
Yes, it worked creating an alias interface with something like:

`sudo ifconfig wlp0,,,f3:0 192.168.1.90 up`

and it defintely looks like the temporary fix I was looking for! Thank you @tomponline for the right pointer!
