### ISSUE TITLE
Add ipv{n}.routes setting for routed NIC type.

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9128]
Add `ipv{n}.routes` for `routed` NIC type to support routing additional subnets from the host to the instance NIC (without L2 ARP/NDP proxy).

See https://discuss.linuxcontainers.org/t/nictype-routed-ipv6-prefix-range/11870/7?u=tomp

**Comment by jeff2814** [comment]
Hi, @hQavi and I are students from University of Texas taking a virtualization class. One of our assignments is to contribute to an open source project and we thought lxd was pretty exciting! Would it be ok if we tried to tackle this issue?

**Comment by tomponline** [comment]
Thanks, have assigned to you.
