### ISSUE TITLE
VM memory reporting as 0

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#9139]
The API seems to be reporting 0 memory used in `4.17`.

VM in question is a ubuntu 18.04 image.

```
lxc info gui-vm --debug
...
"status": "Running",
"status_code": 103,
"disk": {
	"root": {
		"usage": 2483215872
	}
},
"memory": {
	"usage": 0,
	"usage_peak": 0,
	"swap_usage": 0,
	"swap_usage_peak": 0
},
...

```

**Comment by stgraber** [comment]
Reports it correctly here.

**Comment by stgraber** [comment]
Can you provide the usual bug report details?

**Comment by stgraber** [comment]
This may suggest you're running on a kernel without a memory cgroup (like is the case on the raspberry pi).

**Comment by turtle0x1** [comment]
Stock ubuntu 20.04, I was on the edge snap and then went back to 4.17.

Is there particular debug information you want? Ill try a new VM maybe its a one off type thing, had this one around a while.

**Comment by turtle0x1** [comment]
Nope same issue with a alpine 3.11 vm

**Comment by stgraber** [comment]
Oh, I somehow missed the fact that it's a VM, let me see what that looks like here.

**Comment by stgraber** [comment]
```
		"memory": {
			"usage": 144973824,
			"usage_peak": 170278912,
			"swap_usage": 0,
			"swap_usage_peak": 0
		},
```

**Comment by stgraber** [comment]
Is your VM's lxd agent working? Can you use `lxc exec` against it?
