### ISSUE TITLE
don't let a misconfigured container be unfixable

### ISSUE THREAD

**Issue by hallyn** [lxc/lxd#914]
If there is a container configuration error, 'lxc list', 'lxc config edit', and 'lxc destroy' should never fail as a result.

**Comment by hallyn** [comment]
Hm, I thought that there were more ways to do this, but right now I can only reproduce with the original example, that is 'lxc init image a/b'.  That is not really handlable since 'a/b' messes with both the urls and the filesystem paths, and it's properly fixed at init time.

So maybe this should be marked as fixed by pull#916.  Not 1005 sure yet...

**Comment by stgraber** [comment]
So "lxc init image a/b" isn't valid syntax as the / in container name is a reserved char for snapshots. We should make sure never to allow slashes in container names.

**Comment by mikemccracken** [comment]
fixed by #916
