### ISSUE TITLE
"Stand Alone" containers

### ISSUE THREAD

**Issue by Annakan** [lxc/lxd#915]
I am trying to build containers that sit on the network like "regular machines", looking at /usr/lib/x86_64-linux-gnu/lxc/lxc-net there always seems to be some nat magic involved but I am not sure this script is used to build new containers.

To achieve my goal I created a new bridge (`/etc/network/interface` dump below) and assignated it to a container with
 `lxc config set containerName raw.lxc 'lxc.network.link = br0'` 
the container starts but can't seem to get an address from the dnsmaq dhcp server :
the dnsmasq log output shows a DHCPDISCOVER(br0) but the DHCPOFFER(br0) is never received by the container.

Am I on the wrong path and are iptable rules always needed ?

Some context :
The goal would be to create containers with a network configuration that put them as first class citizen of the network they are in while assigning their IP in a reserved range with dnsmaq to also get name resolution from dnsmasq.

Bridge configuration : 
```
# The primary network interface
auto eth0
iface eth0 inet manual

auto br0
iface br0 inet static
        address 172.20.4.227
        netmask 255.255.255.0
        network 172.20.4.0
        broadcast 172.20.4.255
        gateway 172.20.4.253
        # dns-* options are implemented by the resolvconf package, if installed
        dns-nameservers 10.255.255.254
        dns-search mondomaine.com
        bridge_ports eth0
        bridge_stp off
```

Thanks a lot for your time

**Comment by pcdummy** [comment]
Join us on [IRC Freenode #linuxcontainers](https://webchat.freenode.net/?channels=linuxcontainers) for support.

**Comment by pcdummy** [comment]
But to answer your question, use "lxc config edit <container>"
And paste something like [that](http://paste.ubuntu.com/11962004/)

**Comment by Annakan** [comment]
Thanks a lot for you answer, I went to theIRC  channel before posting but nobody was available to answer at that time, I'll do my homework with your clues and come back to the IRC after that.
I did not know the `nictype : bridged` since I based my knowledge of the various type of connection on the otherwise excellent blog post http://containerops.org/2013/11/19/lxc-networking/ that did not mention it ;)

**Comment by stgraber** [comment]
You can't really configure LXD by following LXC documentation :)

For LXD, what @pcdummy told you is right, you want to edit the device definition of the container or of the default profile.

Obviously if you're creating your own bridge, then there won't be a DHCP daemon running on it unless you manually set on up.

Closing this as there's no evidence of an actual LXD issue there.
