### ISSUE TITLE
Undecorated Table Format Option

### ISSUE THREAD

**Issue by markmcb** [lxc/lxd#9162]
The default table formatting makes output hard to read, especially on smaller terminals. Vertically is reduces what's visible by 50%, and horizontally makes for a very hard read if the lines wrap.

Current output for something like lxc list (17 lines):

```
lxc list --columns "ns4t"

+----------+---------+-----------------------------+-----------+
|   NAME   |  STATE  |            IPV4             |   TYPE    |
+----------+---------+-----------------------------+-----------+
| A-ubuntu | RUNNING | 10.105.207.91 (wg-mullvad)  | CONTAINER |
|          |         | 10.0.1.214 (eth0)           |           |
+----------+---------+-----------------------------+-----------+
| B-void   | RUNNING | 10.0.1.211 (eth0)           | CONTAINER |
+----------+---------+-----------------------------+-----------+
| C-void   | RUNNING | 10.0.1.212 (eth0)           | CONTAINER |
+----------+---------+-----------------------------+-----------+
| D-ubuntu | RUNNING | 10.0.1.215 (eth0)           | CONTAINER |
+----------+---------+-----------------------------+-----------+
| E-ubuntu | RUNNING | 10.0.1.210 (eth0)           | CONTAINER |
+----------+---------+-----------------------------+-----------+
| F-ubuntu | RUNNING | 10.109.131.212 (wg-mullvad) | CONTAINER |
|          |         | 10.0.1.213 (eth0)           |           |
+----------+---------+-----------------------------+-----------+
```

Suggested alternative (no decoration text, 3-space delimiters, only 9 lines):

```
NAME       STATE     IPV4                          TYPE        
A-ubuntu   RUNNING   10.105.207.91 (wg-mullvad)    CONTAINER   
                     10.0.1.214 (eth0)                         
B-void     RUNNING   10.0.1.211 (eth0)             CONTAINER   
C-void     RUNNING   10.0.1.212 (eth0)             CONTAINER   
D-ubuntu   RUNNING   10.0.1.215 (eth0)             CONTAINER   
E-ubuntu   RUNNING   10.0.1.210 (eth0)             CONTAINER   
F-ubuntu   RUNNING   10.109.131.212 (wg-mullvad)   CONTAINER   
                     10.0.1.213 (eth0)                      
```
I feel like that should be the default, and if there's a use case for the table decorations it can be achieved via --format option.

I currently run `lxc list --columns "ns4t" | sed -E 's/\| +\|/|-   |/g' | sed -E 's/\| +\|/|-   |/g' | tr '|' ' ' | sed 's/^+.*//' | sed '/^$/d' | sed -E 's/^ *//g' | sed -E 's/   */,/g' | column -t -s ',' -o '   ' | sed 's/- /  /g'` to achieve that format.

Running LXC 4.15 on Void Linux.

**Comment by 745150400** [comment]
@stgraber May I work on this? I would like to have a first try

**Comment by stgraber** [comment]
Assigned it to you!

I think what we'd want to do is introduce a different `--format` for this. We currently have `table`, so maybe we'd want a `compact` value which configures the `tablewriter` to be much more compact.

This should then be added to every list command that supports `--format`.

**Comment by 745150400** [comment]
> 分配给你了！
> 
> 我认为我们想要做的是为此引入不同`--format`的方法。我们目前有`table`，所以也许我们想要一个`compact`将 配置为`tablewriter`更紧凑的值。
> 
> 然后应该将它添加到每个支持`--format`.

ok, I get it
