### ISSUE TITLE
Certificate error: `lxc image ls images:` not working, `lxc launch images:xyz container` working

### ISSUE THREAD

**Issue by christoph-conrads** [lxc/lxd#9175]
# Required information

* Distribution: Ubuntu
* Distribution version: 18.04.5, 20.04.3
* The output of "lxc info": [lxc-info-ubuntu-18.04.5.txt](https://github.com/lxc/lxd/files/7091376/lxc-info-ubuntu-18.04.5.txt) [lxc-info-ubuntu-20.04.5.txt](https://github.com/lxc/lxd/files/7091469/lxc-info-ubuntu-20.04.5.txt)

# Issue description

`lxc image ls 'images:'` is not working but `lxc launch 'images:something' container'` is, see the console output below for the error message.

# Steps to reproduce

```console
christoph@dell-christoph:~$ lxc image ls 'images:'
Error: Get https://uk.images.linuxcontainers.org/streams/v1/index.json: x509: certificate has expired or is not yet valid
christoph@dell-christoph:~$ lxc --debug image ls  'images:'
DBUG[09-01|15:32:51] Connecting to a remote simplestreams server 
Error: Get https://uk.images.linuxcontainers.org/streams/v1/index.json: x509: certificate has expired or is not yet valid
christoph@dell-christoph:~$ lxc image rm ad0536 # current image hash of devuan/beowulf
christoph@dell-christoph:~$ lxc launch 'images:devuan/beowulf' dummy
Creating dummy
Starting dummy
```

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
  * none present
 - [ ] ~~Container log (`lxc info NAME --show-log`)~~ the issue is not related to containers
 - [ ] ~~Container configuration (`lxc config show NAME --expanded`)~~ there is no container
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
   * [lxd.log](https://github.com/lxc/lxd/files/7091430/lxd.log)
 - [x] Output of the client with --debug
  * (see console output above)
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
  * `lxc monitor` does not show any output while executing `lxc image ls`

**Comment by tomponline** [comment]
This is likely due to an ongoing network issue, please follow IRC channel #lxc for updates.

**Comment by stgraber** [comment]
Our infrastructure is in the middle of a DDoS attack, things may be a bit bumpy for a bit.

**Comment by tomponline** [comment]
We are investigating the certificate expiry of https://us.images.linuxcontainers.org/ and https://uk.images.linuxcontainers.org/

**Comment by stgraber** [comment]
This should have been sorted now.
