### ISSUE TITLE
Build problem: cannot find package "github.com/hashicorp/hcl/hcl/printer"

### ISSUE THREAD

**Issue by christoph-conrads** [lxc/lxd#9176]
# Required information

 * Distribution: Debian 11
 * The output of "lxc info" or if that fails:
   * LXD version: 4.17

# Issue description

LXD 4.17 does not build on Debian 11. `make` fails with the error shown in the console output below.

# Steps to reproduce

```console
john@db:/tmp $ wget -- 'https://github.com/lxc/lxd/releases/download/lxd-4.17/lxd-4.17.tar.gz'
john@db:/tmp $ tar -zxf ~/Downloads/lxd-4.17.tar.gz
john@db:/tmp $ cd lxd-4.17
john@db:/tmp/lxd-4.17$ make deps
[...]
john@d11:/tmp/lxd-4.17$ cat >../lxd-setup-env.sh
export CGO_CFLAGS="-I/home/john/go/deps/raft/include/ -I/home/john/go/deps/dqlite/include/"
export CGO_LDFLAGS="-L/home/john/go/deps/raft/.libs -L/home/john/go/deps/dqlite/.libs/"
export LD_LIBRARY_PATH="/home/john/go/deps/raft/.libs/:/home/john/go/deps/dqlite/.libs/"
export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"
john@d11:/tmp/lxd-4.17$ source ../lxd-setup-env.sh 
john@db:/tmp/lxd-4.17$ make
go get -t -v -d ./...
[...]
github.com/hashicorp/hcl (download)
package github.com/hashicorp/hcl/hcl/printer: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
	/usr/lib/go-1.11/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
	/home/john/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)
john@d11:/tmp/lxd-4.17$ go version
go version go1.15.9 linux/amd64
```

This seems to be hashicorp/hcl#449.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
The instructions you see have been updated ahead of 4.18 which now uses gomod.
As you're building 4.17, you should look at the README that's included in that tarball instead.

The online version is at: https://github.com/lxc/lxd/tree/lxd-4.17#from-source-building-a-release

This should have the instructions on setting GOPATH such that the build can work.

**Comment by christoph-conrads** [comment]
Thank you, it is building now.
