### ISSUE TITLE
Duplicate join token

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#9183]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04.3
```
$ snap list lxd
Name  Version      Rev    Tracking  Publisher   Notes
lxd   git-1e32d45  21373  4.0/edge  canonical✓  -
```
# Issue description

On a cluster, adding a join token results in two identical tokens being created.

# Steps to reproduce

 1. Setup a cluster (a single node will do)
 2. Issue a join token for
 
```
for i in 1 2 3; do   lxc cluster add foo; done
```
 3. Confirm 2 identical tokens are available
```
lxc cluster list-tokens | grep foo | sort | uniq -c
```

There should only be one token for the node named 'foo', not two.

**Comment by simondeziel** [comment]
FYI, this is no longer reproducible on edge snap rev 21455.

**Comment by tomponline** [comment]
This was fixed by https://github.com/lxc/lxd/commit/75bb51b22e31ec18d10c23d71f45325c0062c89b
