### ISSUE TITLE
500 error getting network info from API: Network interface "tap4eb1e6f0" not found

### ISSUE THREAD

**Issue by bjornt** [lxc/lxd#9191]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 21.04
 * The output of "lxc info" or if that fails: https://paste.ubuntu.com/p/KcYN5X4P9m/

# Issue description

In MAAS, we have code like this, using pylxd:

  `networks = [net.state() for net in client.networks.all()]`

If that runs while a VM is stopped, a 500 error is returned from the LXD API:
  
    Network interface "tap4eb1e6f0" not found

While it's understandable that network interface can go away, shouldn't it return a 404 instead of a general 500 error? I couldn't find anything, except looking at the error message, to determine that the error is that the interface doesn't exist. I would at least expect something in the response to be able to see that it's not found, apart from having to search the error message, which is a bit fragile.

# Steps to reproduce

 1. Request /1.0/networks/foo/state, where foo doesn't exist.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Yeah, we'll likely need to make our SmartError wrapper or something turn this into a Missing error instead of InternalError.

**Comment by tomponline** [comment]
@stgraber @masnax now that we have `api.StatusError()` and `response.SmartError()` is already configured to recognise it by type, you can use `api.StatusErrorf()` to return an `api.StatusError()` with a particular HTTP status code and custom message that will then be returned to the requester with the correct HTTP status code.

E.g.
https://github.com/lxc/lxd/blob/f9ce1c2d3191b4c88973dc2141841c2685498e68/lxd/db/network_forwards.go#L124

**Comment by tomponline** [comment]
This should be a small change to https://github.com/lxc/lxd/blob/fc743968e05d941e796643b7558a991a2f62d1f6/lxd/resources/network.go#L437 to replace:

```
return nil, fmt.Errorf("Network interface %q not found", name)
```

with

```
return api.StatusErrorf(http.StatusNotFound, "Network interface %q not found", name) 
```
