### ISSUE TITLE
pprof listener bind to TCP/8443 if no port is specified

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#9193]
# Required information

```
# snap list lxd
Name  Version      Rev    Tracking     Publisher   Notes
lxd   git-2dea139  21455  latest/edge  canonical✓  -
```
# Issue description

If one set `core.debug_address` without specifying a port to bind to, the listener will be on TCP/8443 which risks conflicting with `core.https_address` and `cluster.https_address`. Also, TCP/8443 usually comes with the expectation of HTTPS whereas is plain HTTP.

# Steps to reproduce

 1. Install LXD
```
snap install lxd --edge
```
 2. Enable the pprof listener
```
lxc config set core.debug_address ::
```
3. Check which port was bounded
```
ss -nltp | grep lxd
```

The listener should not be on TCP/8443 but it is.

**Comment by tomponline** [comment]
And worse, if you reload LXD after setting the core.debug_address to that LXD fails to start with:

```
Error: listen tcp: address ::: too many colons in address
```

**Comment by tomponline** [comment]
A port should always be required, so either in the format `:<port>` or `<ip>:<port>`.
Also needs to handle wildcard formats for IPs `0.0.0.0` and `::`, as well as validating that IPv6 addresses can be differentiated from the port specified.

**Comment by tomponline** [comment]
I think `validate.IsListenAddress()` will likely be useful here.
