### ISSUE TITLE
Warnings not directly created in init() are resolved on LXD start (even if triggered during startup)

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9194]
Warnings that are triggered during LXD start (such as network failures) are immediately marked as resolved as LXD finishes starting up due to https://github.com/lxc/lxd/blob/0754c9fe9d35e7b76a618263e0cc15682525be3b/lxd/daemon.go#L1322-L1342

This means that these warnings that are triggered during LXD start but are not directly created by the `init()` function are never visible to the user.

Perhaps we should switch to resolving any warning with a date that is older than the LXD daemon start up time, allowing ones created after the start time to remain.

**Comment by monstermunchkin** [comment]
> Perhaps we should switch to resolving any warning with a date that is older than the LXD daemon start up time, allowing ones created after the start time to remain.

@tomponline That won't work because `startTime` is set at the end of `init` (in the `Ready` function) which would cause all warnings to be resolved.

**Comment by tomponline** [comment]
Could we not set it earlier or take another reading earlier?

**Comment by monstermunchkin** [comment]
> Could we not set it earlier or take another reading earlier for use with resolving older warnings?

We could set it earlier, e.g. in `Init()` (which calls `init()`). Looks like `startTime` is only used for image updates.
