### ISSUE TITLE
Limits as bytes

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#9204]
Should the API returning `limits` as bytes? Clients have to approximate this by converting string to bytes.

Are you internally converting "10GB" to bytes?

This is fine as long as it matches the internal behaviour.

**Comment by stgraber** [comment]
LXD always returns current usage in bytes as that's how we get it from the kernel and allows for the client to choose whatever precision they see fit.

As for what the client can use to set limits, they can give us a straight amount of bytes or use any suffix they want (both SI and IEC notations are supported).

**Comment by stgraber** [comment]
Closing as this sounded like a question on behavior rather than a bug.
