### ISSUE TITLE
mounting sys:rw with custom exported image forces logout

### ISSUE THREAD

**Issue by da-moon** [lxc/lxd#9206]
# Issue description

I am using [kubedee](https://github.com/schu/kubedee) to quickly bootstrap a K8s cluster.

after reading Kubedee scripts, it looks like the process has two main phases :

- create a custom LXD image based on `ubuntu:20.04`. Some tools are installed and then the image is published
- create nodes based on the custom image.

When Kubedee is creating nodes based on custom image, it tries to mount `sys:rw` which is what causes the system to crash.mounting as `ro` does not cause any problems.

# Steps to reproduce

## with kubedee

```bash
KUBEDEE_DEBUG=1 kubedee up test --kubernetes-version v1.22.1
```

## without kubedee

- assuming `kubedee up` has ran once and custom image `kubedee-container-image-v0-7-0-66-g34ea3c3-dirty` is available
- launch a container

```bash
lxc launch \
  --profile default \
  --config security.privileged=true \
  --config security.nesting=true \
  --config linux.kernel_modules=ip_tables,ip6_tables,netlink_diag,nf_nat,overlay \
   kubedee-container-image-v0-7-0-66-g34ea3c3-dirty c1
```

- set container config

```bash
lxc config set c1 raw.lxc  'lxc.console.path=none
lxc.apparmor.profile=unconfined
lxc.apparmor.allow_nesting=1
lxc.apparmor.allow_incomplete=1
lxc.mount.auto=proc:rw sys:ro cgroup:rw:force
lxc.cgroup.devices.allow=a
lxc.cap.drop='
``` 

- restart container 

```bash
lxc restart c1
```

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
 
[kernel-output.txt](https://github.com/lxc/lxd/files/7125564/kernel-output.txt)

 - [x] Container log (`lxc info NAME --show-log`)

 [container-log.txt](https://github.com/lxc/lxd/files/7125565/container-log.txt)

- [x] Container configuration (`lxc config show NAME --expanded`)

[container-config.txt](https://github.com/lxc/lxd/files/7125568/container-config.txt)

- [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

[main-daemon-log.txt](https://github.com/lxc/lxd/files/7125569/main-daemon-log.txt)

# Required information

 * Distribution: Arch Linux
 * Kernel : `5.13.13-arch1-1`
 * The output of "lxc info" 

[lxc-info.txt](https://github.com/lxc/lxd/files/7125571/lxc-info.txt)

**Comment by stgraber** [comment]
Closing as anything coming from `raw.lxc` is unsupported. The config described here completely disables all security on a privileged container. Such a container is able to do anything it wants to the host system, access any data it wants and reconfigure any device which is likely what's causing issues here.

**Comment by stgraber** [comment]
Basically:

 - lxc.console.path=none (exposes the host's /dev/console to the container, potentially allowing things like tty reconfigs)
 - lxc.apparmor.profile=unconfined (disables all apparmor profiles and namespaces, causes host apparmor profiles to apply to procsses inside the container)
 - lxc.apparmor.allow_nesting=1 (meaningless given the above)
 - lxc.apparmor.allow_incomplete=1 (meaningless given the above)
 - lxc.mount.auto=proc:rw sys:ro cgroup:rw:force (allows full write access to /proc, too little access to /sys (missing /sys/class/net as read-write) and forces /sys/fs/cgroup to be pre-setup conflicting with systemd's own setup)
 - lxc.cgroup.devices.allow=a (allows all devices to be created, makes it possible to intentionally or accidentally access or corrupt all system drives and attached devices)
 - lxc.cap.drop= (disables all dropped capabilities, causing the container to get the ability to reconfigure the Linux Security Modules as well as reconfigure system time and load kernel modules)

**Comment by da-moon** [comment]
@stgraber thanks you so much for your detailed feedback; this makes things much more clear.

**Comment by da-moon** [comment]
@stgraber one thing that stood out to me was that these steps worked with `ubuntu:20.04` image

- launch a container

```bash
lxc launch \
  --profile default \
  --config security.privileged=true \
  --config security.nesting=true \
  --config linux.kernel_modules=ip_tables,ip6_tables,netlink_diag,nf_nat,overlay \
   ubuntu:20.04 c1
```

- set container config

```bash
lxc config set c1 raw.lxc  'lxc.console.path=none
lxc.apparmor.profile=unconfined
lxc.apparmor.allow_nesting=1
lxc.apparmor.allow_incomplete=1
lxc.mount.auto=proc:rw sys:ro cgroup:rw:force
lxc.cgroup.devices.allow=a
lxc.cap.drop='
``` 

- restart container 

```bash
lxc restart c1
```

this makes me wonder if taking snapshot and using the exported snapshot is what might be causing a problem.
essentially, `kubedee-container-image-v0-7-0-66-g34ea3c3-dirty`is created by running the following:

```bash
lxc launch \
  --storage kubedee \
  --network "${network_id}" \
  --config raw.lxc="lxc.apparmor.allow_incomplete=1" \
  "ubuntu:20.04" "kubedee-container-image-setup"

cat <<'EOF' | lxc exec "kubedee-container-image-setup" bash
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
apt-get update
# crio requires libgpgme11
# helm requires socat
apt-get install -y libgpgme11 socat
rm -rf /var/cache/apt
EOF
lxc snapshot "kubedee-container-image-setup" snap
lxc publish "kubedee-container-image-setup/snap" --alias "kubedee-container-image-v0-7-0-66-g34ea3c3-dirty"
lxc delete -f "kubedee-container-image-setup"
```

Do you have any Idea why this happens only when I am using the exported image ?

**Comment by zer0def** [comment]
Just to expand on this - this used to be the case on OpenSUSE Tumbleweed images as well, and stems from systemd's udev being a little too grabby (I used to have a link to the specific systemd commit, where Lennart outright states that `sys:rw` in containers is an unsupported case) - if you can neuter (through masking, maybe?) udev during the image's build without compromising on Kubedee's goal, it might get you closer to solving your issue.

**Comment by da-moon** [comment]
@zer0def I looked into it a bit more, so these were my findings:
- I could not replicate the problem on another machine that was provisioned with the exact same scripts; the only difference was the on the machine without the problem, I am using refind as bootloader and on the faulty system I am using grub.
- it looks like it's not a kernel panic; it seems like X server is crashing. I modified boot parameters set RunLevel to `3`; and tried to create a K8S cluster with Kubedee, it worked without a problem then. It seems like there is a service in graphical.target that might be the culprit or it might be an issue with faulty X server config.

**Comment by zer0def** [comment]
Definitely not a kernel panic, I would lean towards the container, under the assumption that it's the sole init on that boot (there are no additional checks being made after `/sys` is found as `rw`), invasively poking somewhere between TTYs, DRI and the framebuffer, potentially yanking out the GPU from underneath your host's Xorg session.

**Comment by da-moon** [comment]
@zer0def do you think it may have something to do with the fact that the faulty system has an Nvidia GPU ? there might be something wrong with the nvidia GPU driver I have installed. That system is running a Ryzen 9 with AMD integrated graphics and an Nvidia GPU.

**Comment by stgraber** [comment]
That's possible. When running a full writable /sys, udev in the container will trigger new uevents for every device on your system. Depending on how udev on the host then behaves, it could re-initialize some hardware and cause this kind of issues.

**Comment by zer0def** [comment]
I would start by investigating Xorg.log and dmesg as soon as you are crashed out to get a better picture. I don't have a good post-mortem from when I was encountering this issue, but it did "automagically solve itself" over the course of updating container image bases and the host system, which is utterly unhelpful as aid and guidance.

**Comment by da-moon** [comment]
@stgraber @zer0def your help has been invaluable. thank you. I will update this thread if I find a surefire way to fix this as others may encounter the same issue.

**Comment by da-moon** [comment]
It looks like it was the GPU setup. The faulty laptop is a Lenovo Legion Slim 7 ( gen 6 ). In the bios, it has two graphic card settings: [Discrete Graphics and Dynamic Graphics](https://www.lenovo.com/ca/en/faqs/gaming/gaming-graphic-cards). By default, it was using Dynamic Graphics mode. I switched to Discrete graphics and the error went away.

**Comment by zer0def** [comment]
Glad you managed to sort it out - considering my host is Arch as well and that I had this occurrence sometime during the spring this year with Tumbleweed, you may want to try changing the base image, for example, to `ubuntu:21.04` or a different distribution base entirely - it would narrow down the source of the issue, though time-wise it leans towards being an unfortunately buggy version of systemd in the container image.

**Comment by da-moon** [comment]
@zer0def I tried multiple ubuntu images ( I couldn't do it with Kubedee, so I manually made a profile with `sys:rw` and launched different images ); it was the same thing. 
Basically, it turns out that by using [`optimus-manager`](https://github.com/Askannz/optimus-manager), I can avoid this problem. This problem only happens when the profile is in the `hybrid` mode;  setting the profile to `integrated` or `nvidia` would resolve the problem; keep in mind that in the bios setting, you have to choose `Dynamic Graphics` as `Discrete Graphic` option makes X freeze.

To test the theory on systemd, maybe I will try launching an image based on Alpine ( since it doesn't use systemd ) and see if it crashes X or not; 

There is another problem that occurs when switching profiles through optimus-manger, after the logout, I am seeing this error

```console
❯ lxc ls
cannot change profile for the next exec call: No such file or directory
snap-update-ns failed with code 1
```

I think this is something that might affect all Snap packages. I need to do more research.

**Comment by da-moon** [comment]
@zer0def It looks like you are correct. I created a profile called `kubernetes`:
```console
❯ lxc profile show kubernetes
config:
  linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
  raw.lxc: |-
    lxc.apparmor.allow_incomplete=1
    lxc.apparmor.profile=unconfined
    lxc.cgroup.devices.allow=a
    lxc.mount.auto=proc:rw sys:rw cgroup:rw
    lxc.cap.drop=
  security.nesting: "true"
  security.privileged: "true"
description: LXD container for Kubernetes
devices:
  aadisable:
    path: /sys/module/nf_conntrack/parameters/hashsize
    source: /dev/null
    type: disk
  aadisable1:
    path: /sys/module/apparmor/parameters/enabled
    source: /dev/null
    type: disk
  mem:
    path: /dev/mem
    type: unix-char
name: kubernetes
used_by:
- /1.0/instances/c1
```

applying this profile to my alpine container did not cause X to crash.

**Comment by zer0def** [comment]
I've decided to take a look at udev's source between Ubuntu's 20.04 and 21.04 releases (systemd v245 and v247, respectively) and, barring distro-specific patches, bumped into these two commits that may be of relevance:
- https://github.com/systemd/systemd/commit/5abee64ed40039404d68414f0189245988635e6c (shipped with v246, which also happens to be the major version packaged with `ubuntu:20.10`, image is still available)
- https://github.com/systemd/systemd/commit/b8380cc67a738cb7ec68ac03bb128b90d542d53a (less likely, since it relates to block devices, shipped with v247)

along with removal of `dev_setup()` in `udevd.c`'s main function and a bunch of additions.
