### ISSUE TITLE
FEATURE REQUEST - LXD "client only" binary

### ISSUE THREAD

**Issue by jadjay** [lxc/lxd#9227]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
   * Kernel version:
   * LXC version: 
   * LXD version: stable/latest

# Issue description

Is there a way to get only LXD as a client application ? e.g. via remote links ? with no local LXD daemon ?

The best would be to have a "lxd_lxc binary" to download, which is only able to access to remote LXD servers (the killer feature would be a builtin ssh-connect feature (via unix socket or localhost connection).

Thanks for your attention,

Regards,

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/actions builds a `Linux` artifact with every build which includes a static version of the LXD client (`lxc`) that can be used for this.

**Comment by jadjay** [comment]
Thanks a lot,

It's what we need, but, is there a way to catch the "release url" via api or else ?

Regards,

**Comment by stgraber** [comment]
Though the Github API, probably, not that I've ever done so. I'd love it if there was a unique URL to get the actions result for a particular tag but I'm yet to find one...
