### ISSUE TITLE
A Centos 7 container running on Debian 11 is unable to mount cgroup

### ISSUE THREAD

**Issue by cquike** [lxc/lxd#9228]
# Required information

 * Distribution: Debian
 * Distribution version: 11

# Issue description

I have installed lxd in Debian 11 using the snap package but I fail to have a running Centos 7 on it. lxc init and lxc start seem to work fine, but the container doesn't get an IP address and only /sbin/init process seems to be running.
The log seems to indicate that systemd is unable to mount cgroup:
```
# lxc console centos7con --show-log
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement

Console log:

Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization lxc.
Detected architecture x86-64.

Welcome to CentOS Linux 7 (Core)!

Cannot determine cgroup we are running in: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object, freezing.
```
 The "WARNING: cgroup v2..." message appears with every lxc command that I issue, but I am not sure whether that's causing the problem or not. 

# Steps to reproduce

 1. Install lxd from snap in Debian 11
 2. lxc launch images:centos/7 centos7con
 3. lxc ls  centos7con   # No IPV4 is shown
 4. lxc console centos7con --show-log

It is worth mentioning that other images work fine. In particular I have tried images:centos/8, images:debian/bullseye and ubuntu:18.04 without an issue.
[lxc_config_out.txt](https://github.com/lxc/lxd/files/7173331/lxc_config_out.txt)
[lxc_info_out.txt](https://github.com/lxc/lxd/files/7173334/lxc_info_out.txt)

**Comment by stgraber** [comment]
Yes, that's normal. Systemd in centos7 does not support cgroup2. You're running on a cgroup2-only system and so such containers will fail to start.

If you can't move your containers to an OS which supports cgroup2, then you will need to configure your host to use cgroup1 instead.

**Comment by cquike** [comment]
I need to use Centos 7 as the container image. Is there actually a way to use cgroup1 in Debian 11?

**Comment by stgraber** [comment]
Yeah, you need to update your grub config to pass `systemd.unified_cgroup_hierarchy=false` to the kernel, then run `update-grub` and reboot.

**Comment by cquike** [comment]
That indeed works!
Thank you very much for your support.

**Comment by stgraber** [comment]
np, glad it worked!
