### ISSUE TITLE
Add tab completion for snapshot names in `lxc restore`

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#9231]
It would be nice if `lxc restore foo <tab>` would offer the list of snapshots for the instance.

Should be retrievable with something like:
```
lxc query /1.0/instances/win11/snapshots | grep /1.0/instances | sed -e "s/.*\/snapshots\///g" -e "s/\"$//g"
```

Note that this will unfortunately be a bit flaky as it's going to be a bit hard to handle specific remotes and projects.
That's probably fine as it'd still be an improvement for the standard local case though.

**Comment by ulziibuyan** [comment]
Hi @stgraber, I'll grab this
