### ISSUE TITLE
Report OVN network state in /1.0/networks/NAME/state

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#9232]
Currently trying to fetch the network state for an OVN network returns:
```
stgraber@dakara:~$ lxc query s-dcmtl-cluster:/1.0/networks/default/state?project=core
Error: Network interface "default" not found
```

Compare to what we get for a traditional bridge:
```
stgraber@dakara:~$ lxc query /1.0/networks/lxdbr0/state
{
	"addresses": [
		{
			"address": "172.17.250.1",
			"family": "inet",
			"netmask": "24",
			"scope": "global"
		},
		{
			"address": "2602:fc62:b:250::1",
			"family": "inet6",
			"netmask": "64",
			"scope": "global"
		},
		{
			"address": "fe80::216:3eff:fe36:1f28",
			"family": "inet6",
			"netmask": "64",
			"scope": "link"
		}
	],
	"bond": null,
	"bridge": {
		"forward_delay": 1500,
		"id": "8000.00163e361f28",
		"stp": false,
		"upper_devices": [
			"tapf59a5d19",
			"tapfb01853f",
			"veth2cd1b8fd",
			"veth5ef8d6a3",
			"veth6063b243"
		],
		"vlan_default": 1,
		"vlan_filtering": true
	},
	"counters": {
		"bytes_received": 12396298233,
		"bytes_sent": 114815830037,
		"packets_received": 28723462,
		"packets_sent": 43057416
	},
	"hwaddr": "00:16:3e:36:1f:28",
	"mtu": 1500,
	"state": "up",
	"type": "broadcast",
	"vlan": null
}
```

OVN networks are a bit special but we should still be able to:
 - Compute the addresses section from the known virtual router addresses
 - Maybe fill in the counters? (@tomponline is there such a thing on an OVN router?)
 - Fill in the hwaddr, mtu, state and type
 - Add a new `ovn` section which should then expose what server is currently handling the router traffic for the network (@tomponline do you have details on how to fetch that?)

**Comment by stgraber** [comment]
@tomponline anything else worth adding?

**Comment by tomponline** [comment]
@stgraber I've assigned this to myself for now as I'll need to spend some time researching to answer those questions.

**Comment by stgraber** [comment]
@tomponline unassigned you so this shows up as available for someone to tackle, at which point we'll provide mentoring/guidance as usual.

**Comment by andrewli6504** [comment]
Hello, I am a student at UT Austin taking Virtualization - Could me and @BlakeRomero I try tackling this issue?

**Comment by tomponline** [comment]
> @tomponline unassigned you so this shows up as available for someone to tackle, at which point we'll provide mentoring/guidance as usual.

Sounds good.

**Comment by andrewli6504** [comment]
Hello, I'm having a bit of trouble starting on this - where would most of the relevant code be located? Also, what steps do I need to perform before I can replicate the issue?

**Comment by stgraber** [comment]
For basic setup of OVN, the standalone LXD OVN setup section at https://linuxcontainers.org/lxd/docs/master/networks#network-ovn should help you get such a network online.

Once you do, you should be able to reproduce the issue with the `lxc query` command I used above.

As for what will need to be done here, I suspect we'll want to:
 - Change `networkStateGet` in networks.go to instead:
   - Attempt to load the network using `network.LoadByName` (see `networkStateGet` for an example)
   - If not found, use the current logic (`resources.GetNetworkState`) so we don't break querying non-LXD interfaces
   - If found, then call `n.State()` which will be a new function you'll introduce to `lxc/network/`
   - That `State` function will by default just call `resources.GetNetworkState` (should be done through `driver_common.go`)
   - Then the `driver_ovn` implementation of it is what will need to actually hit OVN and pull in some relevant network details.

That last step is where this chunk of the initial issue comes into play:
```
    Compute the addresses section from the known virtual router addresses
    Maybe fill in the counters? (@tomponline is there such a thing on an OVN router?)
    Fill in the hwaddr, mtu, state and type
    Add a new ovn section which should then expose what server is currently handling the router traffic for the network (@tomponline do you have details on how to fetch that?)
```

So you'd start by grabbing the OVN network information to fill in the addresses, possibly counters, hwaddr, MTU, state and type part of the struct. Then you'd extend `api.NetworkState` a bit (shared/api/network.go) to add a `OVN` member (`NetworkStateOVN`) which will include additional OVN-specific informations. For now I'd just start by tracking what server is acting as the gateway for that network.

I don't have exact details for how to fetch and fill the OVN specific part, hopefully @tomponline can give you some pointers for that, though you have quite a bit of reshuffling to do before you can really get to that part and you can always start by hardcoding some values to make sure you have the rest of the logic correct.

**Comment by tomponline** [comment]
@stgraber @andrewli6504 let me know when you get onto the OVN specific parts if I've not had chance before that to back to you on these as I don't have any answers right now so would need to spend some time digging into it.

**Comment by andrewli6504** [comment]
Have you had time to look more into the OVN parts yet @tomponline ?

**Comment by stgraber** [comment]
> So you'd start by grabbing the OVN network information to fill in the addresses, possibly counters, hwaddr, MTU, state and type part of the struct. Then you'd extend api.NetworkState a bit (shared/api/network.go) to add a OVN member (NetworkStateOVN) which will include additional OVN-specific informations. For now I'd just start by tracking what server is acting as the gateway for that network.

 - hwaddr: "mac" field from lr-lrp-ext (Logical_Router_Port)
 - mtu: maybe "mtu" field from ipv6_ra_configs  on lr-lrp-int
 - state: up
 - type: broadcast
 - ovn
   - chassis: map lr-lrp-ext in Logical_Router_Port table of SB database to name field in Chassis table

@tomponline I haven't found a way to figure out the chassis from NB alone so looks like we need to poke SB which I don't think we've done before? Can you think of a way around that?

@andrewli6504 as mentioned before, you should already be able to put a lot of things into place even before hitting any of that OVN stuff, have you done all of that already? If so, the above should get you some information on how to fill hwaddr, mtu, state and type while we wait for @tomponline to look into the chassis bit.

**Comment by tomponline** [comment]
I've spent a few hours this morning on this and so far the only way I've figured out how to detect the active gateway chassis is as follows:

Assuming you have an OVN central server (called `ovndb`) and 3 OVN host servers (called: `ovn1`, `ovn2`, and `ovn3`) in an OVN setup (their chassis IDs can be got via `ovs-vsctl get open_vswitch . external_ids:system-id` on each server).

```
ovn1: OVS: d7ddbc15-52b4-466e-b6da-c1762b3dcef2
ovn2: OVS: 038fcc8a-8293-4a96-bebf-cc8a454706c0
ovn3: OVS: cd58feaa-4510-405c-b2fd-f3ab99d326c2
```

On the `ovndb` server we can see these in the logical northbound database along with their northbound DB _uuid and priorities as follows:

```
ovn-nbctl list ha_chassis
_uuid               : 69935c8d-87c3-4af4-bddc-4614f7411bce
chassis_name        : "cd58feaa-4510-405c-b2fd-f3ab99d326c2"
external_ids        : {}
priority            : 6437

_uuid               : ab770942-e6d6-4b6e-a8bf-4b915b550cea
chassis_name        : "038fcc8a-8293-4a96-bebf-cc8a454706c0"
external_ids        : {}
priority            : 8742

_uuid               : 3a37625f-fb76-4122-b87b-be0641d78aec
chassis_name        : "d7ddbc15-52b4-466e-b6da-c1762b3dcef2"
external_ids        : {}
priority            : 11503
```

Additionally, as we can have multiple OVN networks each with their own chassis, we need to ensure we are only looking at the chassis for our network. To do this, get find the chassis group for the network:

```
ovn-nbctl list ha_chassis_group
_uuid               : 299462ef-4fe3-40cc-b6b4-72e36d6f3b5b
external_ids        : {}
ha_chassis          : [3a37625f-fb76-4122-b87b-be0641d78aec, 69935c8d-87c3-4af4-bddc-4614f7411bce, ab770942-e6d6-4b6e-a8bf-4b915b550cea]
name                : lxd-net4
```

This is a mapping of network name to ovn northbound chassis _uuid values from the previous table.

So now we have the following mappings for `lxd-net4` chassis:

```
ovn1: OVS: d7ddbc15-52b4-466e-b6da-c1762b3dcef2 -> OVN-NB: 3a37625f-fb76-4122-b87b-be0641d78aec
ovn2: OVS: 038fcc8a-8293-4a96-bebf-cc8a454706c0 -> OVN-NB: ab770942-e6d6-4b6e-a8bf-4b915b550cea
ovn3: OVS: cd58feaa-4510-405c-b2fd-f3ab99d326c2 -> OVN-NB: 69935c8d-87c3-4af4-bddc-4614f7411bce
```

Next we need to look at the ovn southbound database to see the active chassis for the gateway. 
For this I've found that the `port_binding` table (https://manpages.ubuntu.com/manpages/focal/man5/ovn-sb.5.html#port_binding%20table) contains a `type` field and that for the active gateway's external logical router port has it set to `chassisredirect`, along with the `ha_chassis_group` and `chassis` values set indicating the chassis group and chassis.

This seems to change, even if I forcefully kill one of the OVN members rather than cleanly shutting it down.

But, just to make things even more complicated, the OVN southbound database doesn't use the same `_uuid` values for the chassis IDs as the northbound database, so we would have to go through another level of indirection using the southbound `ha_chassis` table (https://manpages.ubuntu.com/manpages/focal/man5/ovn-sb.5.html#ha_chassis%20table).

```
ovn-sbctl list ha_chassis
_uuid               : fb7038aa-f114-45df-886c-2f3c4a42da24
chassis             : 578d33be-bb2d-449e-b4d2-02ba2df926b5
external_ids        : {chassis-name="cd58feaa-4510-405c-b2fd-f3ab99d326c2"}
priority            : 6437

_uuid               : bf63e7d2-d88a-4312-900c-5d31b016686f
chassis             : b71e94b7-125f-4575-b644-3b80eb95b8b0
external_ids        : {chassis-name="d7ddbc15-52b4-466e-b6da-c1762b3dcef2"}
priority            : 11503

_uuid               : ff7623a2-c37e-4912-9a70-00cec5cbe00d
chassis             : e9fd1be4-2265-4e89-8efb-e1a2c50ee5f3
external_ids        : {chassis-name="038fcc8a-8293-4a96-bebf-cc8a454706c0"}
priority            : 8742
```

So we then have the following mappings:

```
ovn1: OVS: d7ddbc15-52b4-466e-b6da-c1762b3dcef2 -> OVN-NB: 3a37625f-fb76-4122-b87b-be0641d78aec -> OVN-SB:  bf63e7d2-d88a-4312-900c-5d31b016686f
ovn2: OVS: 038fcc8a-8293-4a96-bebf-cc8a454706c0 -> OVN-NB: ab770942-e6d6-4b6e-a8bf-4b915b550cea -> OVN-SB: ff7623a2-c37e-4912-9a70-00cec5cbe00d
ovn3: OVS: cd58feaa-4510-405c-b2fd-f3ab99d326c2 -> OVN-NB: 69935c8d-87c3-4af4-bddc-4614f7411bce -> OVN-SB: fb7038aa-f114-45df-886c-2f3c4a42da24 
```

Although we may be table to take a shortcut, as the original OVS chassis name is stored in the `external_ids` in the OVN-SB `external_ids` fields.

**Comment by tomponline** [comment]
In order to do this LXD will need to access the OVN southbound database, which as @stgraber rightly says we've not needed to do before. However OVN does require that each OVN server has the southbound connection details stored in the OVS database on each server, and as a LXD OVN network must exist on each cluster member, we should be able to get access to the OVS connection string by using the `ovs-vsctl get open_vswitch . external_ids:ovn-remote` return value. We would need to explore what this value can contain in cluster setups too, to support the variety of OVN setups that can occur.

**Comment by tomponline** [comment]
Have emailed @fnordahl about this too.

**Comment by stgraber** [comment]
@tomponline what was I missing in my approach to find the chassis?

> chassis: map lr-lrp-ext in Logical_Router_Port table of SB database to name field in Chassis table

This was using only the SB database to trace the logical router port for a network to its chassis and then getting the name of the system from the SB chassis table.

**Comment by tomponline** [comment]
Sorry I missed that bit of your post (was flitting about between several topics at the same time and must've not clocked you were proposing a solution, thought you were just asking how to achieve it).

I'm not quite following your proposal though, do you have a step by step? Also from what I could see there is a difference between cleanly shutting down a server (where the chassis entries are removed) and uncleanly shutting down a server (where the chassis entries are left).

**Comment by stgraber** [comment]
I don't have an OVN system to poke at right now (on my phone) but from what I remember I was just looking at two tables in the SB database.

In Logical_Router_Port, you locate by name the entry for your network's external router port (netX-lr-lrp-ext). Then from that entry you get the chassis id field and then line that up with the matching entry in the Chassis table, finally you get the name of the server from that Chassis entry.

**Comment by stgraber** [comment]
So the steps seem to be:
 - Get SB connection string with `ovs-vsctl get open_vswitch . external_ids:ovn-remote`
 - From the SB database, pull Port_Binding, in there, locate `cr-lxd-net<ID>-lr-lrp-ext`
 - Pull the Chassis table from the SB database, find the record matching the `chassis` field in the Port_Binding table and extract the `hostname` field from that `Chassis` record

**Comment by tomponline** [comment]
You can load the specific port using `ovn-sbctl find port_binding logical_port=cr-lxd-net<ID>-lr-lrp-ext`

**Comment by tomponline** [comment]
@stgraber yep that seems to work great, even with forcefully killing a server. :)

**Comment by stgraber** [comment]
@andrewli6504 @BlakeRomero hello, just wanted to check if you still intend to work on this or if we should unassign it so someone else can take a crack at it?

**Comment by stgraber** [comment]
@markylaing going to give you that one as getting some familiarity with OVN would be nice :)
