### ISSUE TITLE
Support for moving instances and custom volumes between projects

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#9235]
We currently have server-side support for moving instances or custom volumes between storage pools.
But we don't currently have support for moving between projects. Instead the client handles it as copy+delete.

We should expand the `POST` operation on both instances and custom volumes to support moving between projects and have LXD itself handle the copy+delete.

One thing to be careful about here is project access. We'll need to call the access checker to ensure that the requestor is allowed access to the target project.

**Comment by presztak** [comment]
@stgraber Can I be assign to this one?

**Comment by stgraber** [comment]
Yep!

**Comment by presztak** [comment]
@stgraber, PR almost done but still I'm not sure what do you mean by "access checker". Which mechanism is it?

**Comment by stgraber** [comment]
You can call `rbac.UserHasPermission(r, targetProject, "manage-containers")` which will return true if the user is allowed instance creation on the target project. For custom volumes, you'd want the same but using "manage-storage-volumes" instead.
