### ISSUE TITLE
Quiesce HTTP errors caused by HAProxy connectivity checks

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#9237]
When HAProxy is run in front of LXD, it performs TCP connectivity checks which then trigger errors as the connection is terminated early. This looks like:
```
Sep 17 04:58:30 abydos lxd.daemon[21884]: 2021/09/17 04:58:30 http: TLS handshake error from [2602:fd23:8:1003:216:3eff:fefa:7670]:44918: write tcp [2602:fd23:8:101::100]:8443->[2602:fd23:8:1003:216:3eff:fefa:7670]:44918: write: connection reset by peer
Sep 17 04:58:31 abydos lxd.daemon[21884]: 2021/09/17 04:58:31 http: TLS handshake error from [2602:fd23:8:1001:216:3eff:fecb:58f1]:37238: write tcp [2602:fd23:8:101::100]:8443->[2602:fd23:8:1001:216:3eff:fecb:58f1]:37238: write: connection reset by peer
Sep 17 04:58:32 abydos lxd.daemon[21884]: 2021/09/17 04:58:32 http: TLS handshake error from [2602:fd23:8:1003:216:3eff:fefa:7670]:44994: write tcp [2602:fd23:8:101::100]:8443->[2602:fd23:8:1003:216:3eff:fefa:7670]:44994: write: connection reset by peer
Sep 17 04:58:33 abydos lxd.daemon[21884]: 2021/09/17 04:58:33 http: TLS handshake error from [2602:fd23:8:1002:216:3eff:fe13:6bb1]:55672: write tcp [2602:fd23:8:101::100]:8443->[2602:fd23:8:1002:216:3eff:fe13:6bb1]:55672: write: connection reset by peer
```

This is caused by HAProxy never going through a full TLS handshake and terminating the session early.
We should find a way to quiesce those errors, at least when LXD is configured for HAProxy.

**Comment by kaustubnvd** [comment]
Hello, I'm a student from UT Austin taking the Virtualization class, and I would love to take a look at this issue.

**Comment by stgraber** [comment]
Done!

**Comment by Gautham-Raju** [comment]
Hey, I have a couple of follow up questions:
1. When you say quiesce the HTTP errors, should the HAProxy be shut down after the failed checks or should we simply remove the errors from showing up and continue the session?
2. Should the logs only be silent until the TCP connection checks are over and then they should display errors as usual? 
3. Does HAProxy use one of the configurations to run on top of lxd (Network Configuration)?
4. From what I gather, HAProxy logging can be configured to be silent with a keyword but that option is set within HAProxy. Assuming the errors should be removed in lxd itself and not by modifying configurations in HAProxy, is there any way lxd can force the HAProxy config to make these logs silent? Alternatively, if HAProxy does use network configuration would the security logging properties be of any use or should other possibilities be explored? Any additional information about how HAProxy is able to run on lxd would be greatly appreciated. Thanks!

**Comment by stgraber** [comment]
1) We just want to silence them, we still need HAProxy to connect or it would mark the server as broken
2) If that's reasonably easy to do, that'd be great, yes. When dealing with a legitimate request from a HAProxy server, it'd be good to have logging working normally
3) This issue is about an external HAProxy forwarding requests to LXD's HTTPS listener
4) The logging issue is on LXD's side, HAProxy is just doing frequent TCP connections to check for service availability and as it terminates the connection before doing anything useful with it, it's causing LXD's http listener to complain about it

Ideally we should:
 - Check if the connection is coming from a trusted proxy (`core.https_trusted_proxy` which becomes `l.trustedProxy` in the endpoints package)
 - If it is, then skip logging any TCP error, if possible restore TCP error logging after initial full connection

**Comment by stgraber** [comment]
Did a bit of digging and it looks like there is a `ErrorLog` attribute on http.Server which can be pointed to a `log.Logger` implementation. In this case, I suspect we could define a custom logger which will:
 - Parse the log entry in search of `http: TLS handshake error from` and if found, check if the address in the message matches one of the proxy servers, if it does, then the message should be discarded
 - All other messages should be forwarded to our normal logger (`logger.Warn`)

**Comment by stgraber** [comment]
@kaustubnvd @Gautham-Raju hello, just wanted to check if you still intend to work on this or if we should unassign it so someone else can take a crack at it?

**Comment by kaustubnvd** [comment]
@stgraber Apologies for the delayed response, we made some progress, but currently we no longer intend to work on the issue, so you can go ahead and let someone else take a crack at it.

**Comment by markylaing** [comment]
@stgraber it looks like the simple solution would be to set the value of `ErrorLog` on the `http.Server` returned [here](https://github.com/lxc/lxd/blob/master/lxd/api.go#L96) to be `log.New(ioutil.Discard, "", 0)`. However that will discard all logs from that `http.Server` which are otherwise written by the `log` packages standard logger.
