### ISSUE TITLE
Split the storage documentation into per-driver tables

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#9239]
Following the pattern in `instances` and `networks`. The `storage` documentation should be modified to have each storage driver have its own section with its configuration keys.

**Comment by jeff2814** [comment]
Hi, @hQavi and I are students from University of Texas taking a virtualization class. One of our assignments is to contribute to an open source project and we thought lxd was pretty exciting! Would it be ok if we tried to tackle this issue?

**Comment by stgraber** [comment]
Sure, I've assigned it to you. I'll need @hQavi to comment in here so I can assign them too.

**Comment by hQavi** [comment]
Thanks, commenting to get assigned.

**Comment by stgraber** [comment]
Done!
