### ISSUE TITLE
"Unable to find quota group" when getting volume size

### ISSUE THREAD

**Issue by OhSoGood** [lxc/lxd#9241]
Hi All

I'm on Debian 10, kernel 5.10, LXD 4.18 with btrfs storage (btrfs 5.4.1).
The command  `lxc storage volume list local:default -ctnU` returns the message `Error: Unable to find quota group` because of the 'U' option (I got that command from https://github.com/lxc/lxd/issues/7708 ). Unless I forgot, I'v never set any quota anywhere. Do I miss something or is that a bug? Thanks for your help!

PS: I found another issue with the same message (https://github.com/lxc/lxd/issues/5842) but I am not sure it is related.

**Comment by stgraber** [comment]
Hmm, qgroup should be setup the first time you set a `size` limit on a root device of one of your containers on btrfs.
Did you do that already?

If so, then we need to figure out what could have unconfigured it. If you haven't, then we should look into why we're not detecting this and just returning 0 for everything.

**Comment by OhSoGood** [comment]
Hi Stephen.
My containers are small ones on huge SSDs, so I have never felt the need to set size limits. So in my case the relevant action would be "we should look into why we're not detecting this and just returning 0 for everything."
Thank you

**Comment by stgraber** [comment]
Ok, cool. Can you try to set a size limit on one of them? Just doing that should initialize the qgroup, you can then unset the limit.

**Comment by OhSoGood** [comment]
When I set "size: 100GB" in the profile used by the container and close it, I get this message: `Project: default, Instance: cloud-alpine: Failed to update device "root": Failed to get subvol information: Failed to run: btrfs subvolume show /var/snap/lxd/common/lxd/storage-pools/default/containers/cloud-alpine: ERROR: quota query failed: Success`

If I manually run `btrfs subvolume show /var/snap/lxd/common/lxd/storage-pools/default/containers/cloud-alpine`, I get the CT specs and the snapshot list but at the end there is the message `ERROR: quota query failed: No such file or directory`.

Am i doing something wrong?

**Comment by stgraber** [comment]
Sorry for the delay. Your own `btrfs subvolume show` isn't running in the correct namespace.

You'd need something like `nsenter --mount=/run/snapd/ns/lxd.mnt /snap/lxd/current/bin/btrfs subvol show /var/snap/lxd/common/lxd/storage-pools/default/containers/cloud-alpine`

**Comment by tomponline** [comment]
@OhSoGood do you have an update for this? Thanks

**Comment by OhSoGood** [comment]
Thank you Tom for your feedback. The issue is an old one now (we are on Debian 11 with LXD 5.6). I cannot pitifully remember when and how it was solved.
