### ISSUE TITLE
Setting `core.https_address` to `0.0.0.0` listens on IPv6 too

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#9248]
# Required information

```
# snap info lxd | grep installed
installed:          4.18                   (21468) 75MB -
```

# Steps to reproduce

1. Tell LXD to listen on all IPv4 addresses
```
# lxc config set core.https_address 0.0.0.0
```
 2. Check which IP/port is bounded
```
# ss -nltp | grep lxd
LISTEN    0         0                        *:8443                   *:*        users:(("lxd",pid=2533,fd=19))
```
 3. Confirm IPv6 connectivity
```
# nc -zv ::1 8443
Connection to ::1 8443 port [tcp/*] succeeded!
```

Connecting to IPv6 should *not* work.

**Comment by simondeziel** [comment]
@tomponline, I don't know what are the implications of using `tcp`, `tcp4` or `tcp6` but I'd expect the following behavior:

`[::]`: listen on all available IPs (assuming `net.ipv6.bindv6only` is left at its default value of 0, all IPv6s otherwise)
`0.0.0.0`: listen on all IPv4s
`192.0.2.1`: listen on just 192.0.2.1
`2001:db8::1`: listen on just 2001:db8::1
`ipv4only.example.com`: listen on the IPv4 corresponding to the A record
`ipv6only.example.com`: listen on the IPv6 corresponding to the AAAA record
`ipany.example.com`: listen on the IPv4 and IPv6 corresponding to the A/AAAA records

For the hostname cases, I don't know how LXD handles those. Are the lookups done once at configuration time and the A/AAAA results are saved in the config? Or is the hostname saved in the config and re-resolved on each startup/config change?

**Comment by tomponline** [comment]
> `ipany.example.com`: listen on the IPv4 and IPv6 corresponding to the A/AAAA records

According to Go doc, it will only listen on a single IP at most.

**Comment by tomponline** [comment]
https://pkg.go.dev/net#Listen

**Comment by tomponline** [comment]
> `0.0.0.0`: listen on all IPv4s

Thanks, that should be sufficient for this particular issue then.

**Comment by tomponline** [comment]
Its a known golang issue https://go-review.googlesource.com/c/go/+/45771/4/src/net/dial.go

https://go-review.googlesource.com/c/go/+/45771/

**Comment by simondeziel** [comment]
> > `ipany.example.com`: listen on the IPv4 and IPv6 corresponding to the A/AAAA records
> 
> According to Go doc, it will only listen on a single IP at most.

That makes sense as otherwise it would need to deal with two (or more) sockets. Thanks.
