### ISSUE TITLE
Update the instancesOnDisk function to handle VMs

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9265]
The `instancesOnDisk` is called by the `instancesShutdown` function during LXD daemon shutdown when the cluster database isn't available (perhaps the cluster has lost quorum). It attempts to scan the local storage to find instances to shutdown.

However currently it only supports detecting containers, and it should be updated to detect VMs too.

**Comment by stgraber** [comment]
Ah yeah, that's quite critical when shutting down an entire cluster as the last two servers will not have quorum and so will rely on this.
