### ISSUE TITLE
Getting undocumented status code 112 (Error)

### ISSUE THREAD

**Issue by ricab** [lxc/lxd#9271]
# Issue description

Another API documentation issue. I just reported that we were not handling the Error state on our side: https://github.com/canonical/multipass/issues/2250. But then I realized why that was: it is not documented, at least not in https://linuxcontainers.org/lxd/docs/master/rest-api#status-codes

**Comment by stgraber** [comment]
Ah yeah, looks like we need to resync that with shared/api/status_code.go
