### ISSUE TITLE
cpu usage reported as "-1" on Debian 11 (seems related to cgroup v2)

### ISSUE THREAD

**Issue by AceSlash** [lxc/lxd#9273]
# Required information

 * Distribution: Debian
 * Distribution version: 11
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.10.0-8-amd64
   * LXC version: 4.0.7
   * LXD version:4.0.7
   * Storage backend in use: zfs

# Issue description

The CPU usage reported via the unix-socket is stuck at `-1`:
```
curl --silent --unix-socket /var/snap/lxd/common/lxd/unix.socket a/1.0/containers/container/state| jq .metadata.cpu
{
  "usage": -1
}
```
# Steps to reproduce

 1. Run a container with an host on Debian 11
 2. Check CPU usage

**Comment by stgraber** [comment]
@monstermunchkin looks like this one isn't properly implemented in `lxd/cgroup`, can you fill it in?

**Comment by monstermunchkin** [comment]
@AceSlash in case you run into problems with this, make sure the resources are delegated. You'll need to create a unit overload for your user by running `systemctl edit user@1000.service` (if your user ID is 1000). Here's what you need to add:
```systemd
[Service]
Delegate=yes
```

Source: https://wiki.archlinux.org/title/cgroups#As_unprivileged_user

**Comment by AceSlash** [comment]
@monstermunchkin : I'm not sure I understand... I have the result via the unix-socket with curl, how does the user matters in this case?

Anyhow, I'm running it as root.

Currently I changed our monitoring system to get the CPU usage via `cat /sys/fs/cgroup/lxc.payload.$1/cpu.stat |grep usage_usec| cut -d' ' -f2`. It gives the same value as LXD except that it is in microseconds while yours is in nanoseconds.

**Comment by monstermunchkin** [comment]
@AceSlash When I tested this PR without the unit overload, LXD reported missing `cpu` and `io` controllers. Once the unit overload was in place, it returned the cpu usage correctly.

**Comment by stgraber** [comment]
Hopefully this won't be a problem with the snap package, if it is, we can look at ways to tweak the snap to do the right thing on startup for cgroup2 systems.

**Comment by monstermunchkin** [comment]
> Hopefully this won't be a problem with the snap package, if it is, we can look at ways to tweak the snap to do the right thing on startup for cgroup2 systems.

It won't be a problem in the snap, I just checked. Both `/etc/systemd/system/snap.lxd.daemon.service` and `/etc/systemd/system/snap.lxd.activate.service` set `Delegate=true`.
