### ISSUE TITLE
missing LV VG causes daemon to refuse to start

### ISSUE THREAD

**Issue by mikemccracken** [lxc/lxd#931]
If you wiped your LVM VGs and restarted LXD without clearing the config, the daemon won't start

It gives a nice error message, so that's good. But how do we support allowing the user to fix it? 

Should it:
 1. should it fall back to plain dirs?
 2. go into a degraded mode so it can still respond to config set/unset and be fixed without db tweaking
 3. or we could add a new admin tool like 'lxd-config' that lets you edit the config without starting the daemon...

**Comment by pcdummy** [comment]
Would say fall back to dirs and refuse to start a container if LXD_DIR/containers/&lt;container&gt; doesn't exists with an error.

**Comment by mikemccracken** [comment]
@stgraber this was fixed by #952
