### ISSUE TITLE
Metrics returning empty

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#9323]
When I run `lxc query /1.0/metrics` I get an empty string (on the edge snap)

**Comment by turtle0x1** [comment]
Forgot to include the syslog entry

```
lxd.daemon[4060]: t=2021-10-02T21:40:50+0100 lvl=warn msg=“Failed to get instance metrics” err=“Failed to get swap usage: strconv.ParseInt: parsing “”: invalid syntax” instance=zabbix project=default
```

**Comment by monstermunchkin** [comment]
You're getting this because swap accounting is disabled on your machine. You can enable it by setting `swapaccount=1` in your kernel cmdline.
