### ISSUE TITLE
cpuprofiling test has intermittent failures

### ISSUE THREAD

**Issue by mikemccracken** [lxc/lxd#941]
recently I had a case where the cpuprofiling test would panic repeatedly even though the same command outside the test suite ran fine. This happened repeatably until I checked out a different branch then never repeated.
@pcdummy has reported the same issue, so I am filing it as a bug to track. I don't have any clues.

**Comment by pcdummy** [comment]
This is what i get:

+ go tool pprof /root/go/bin/lxd /root/go/src/github.com/lxc/lxd/test/tmp.OobNUMcBjv/cpu.out
Entering interactive mode (type "help" for commands)
(pprof) panic: runtime error: index out of range

goroutine 1 [running]:
cmd/pprof/internal/driver.sampleFormat(0xc2080901c0, 0xc20809c300, 0xc2080c6ba0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/cmd/pprof/internal/driver/driver.go:975 +0x21c
cmd/pprof/internal/driver.generate(0xc208090101, 0xc2080901c0, 0x7fa084649d50, 0xc20802afe0, 0x7fa084649d08, 0xc208038060, 0xc20809c300, 0x0, 0x0)
	/usr/lib/go/src/cmd/pprof/internal/driver/driver.go:1012 +0x11f
cmd/pprof/internal/driver.generateReport(0xc2080900e0, 0xc20801ef80, 0x2, 0x2, 0x7fa084649d50, 0xc20802afe0, 0x7fa084649d08, 0xc208038060, 0xc20809c000, 0x0, ...)
	/usr/lib/go/src/cmd/pprof/internal/driver/interactive.go:133 +0x11e
cmd/pprof/internal/driver.interactive(0xc2080900e0, 0x7fa084649d50, 0xc20802afe0, 0x7fa084649d08, 0xc208038060, 0xc20809c000, 0x0, 0x0)
	/usr/lib/go/src/cmd/pprof/internal/driver/interactive.go:99 +0x586
cmd/pprof/internal/driver.PProf(0x7fa084649d90, 0xae8fe8, 0x971768, 0x971d30, 0x7fa084649d50, 0xc20802afe0, 0x7fa084649d08, 0xc208038060, 0x0, 0x0, ...)
	/usr/lib/go/src/cmd/pprof/internal/driver/driver.go:112 +0xc24
main.main()
	/usr/lib/go/src/cmd/pprof/pprof.go:28 +0x129
+ cleanup
+ set +x
==> Test result: failure
failed test: test_cpu_profiling
==> Cleaning up

**Comment by mikemccracken** [comment]
I haven't been able to reproduce this recently. @stgraber, have you seen it at all? maybe we should de-milestone it?

**Comment by stgraber** [comment]
I've never seen it myself. I'm happy to close this for now and reconsider if this happens again.
