### ISSUE TITLE
Remove use of sql.NullString and ensure all description fields are not nullable

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9414]
Historically some database tables have allowed NULL description fields.
However there is no need for this as an empty string aligns more closely with Go's default string value and can indicate "no description" without needing the field to be NULLable.

Right now we use a mixture of Go's `sql.NullString{}` to handle parsing NULLs from the database results or handle it at the databse layer using `IFNULL()` in the query.

Requiring these approaches is error prone when refactoring code (see https://github.com/lxc/lxd/issues/9385), because new records are created with descriptions that are an empty string (if not specified) and so the automated tests do not account for older records that have a NULL description.

We should:

- Patch the DB to make the description fields not NULLable.
- Remove the NULL handling in the code for `description` fields.

**Comment by markylaing** [comment]
@tomponline should we also set a default value? 

e.g. 
```sql
ALTER TABLE networks
ALTER COLUMN description NOT NULL DEFAULT '';
```

**Comment by tomponline** [comment]
I think it will be defaulting to empty string anyway so I'd leave it off (make it like the `networks_zones` table for example)
