### ISSUE TITLE
Cannot run Docker in Debian Bullseye container created with LXD

### ISSUE THREAD

**Issue by lephilousophe** [lxc/lxd#9421]
# Required information

 * Distribution: Gentoo | Ubuntu
 * Distribution version: rolling release | 21.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.14.11-gentoo | 5.11.0-31-generic
   * LXC version: 4.0.10 | snap version 4.19 21750
   * LXD version: 4.19 | snap version 4.19 21750
   * Storage backend in use: dir

# Issue description

A Debian container is running on both hosts with official package docker.io installed.
Settings set:
  security.syscalls.intercept.bpf: "true"
  security.syscalls.intercept.bpf.devices: "true"
After migrating the container from Buster to Bullseye, docker got upgraded to 20.10.5 and stopped working with the following error:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: can't load program: operation not permitted: unknown.
ERRO[0002] error waiting for container: context canceled
```
I suspect this error to be related to upstream bug opencontainers/runc#2792 which got fixed in recent version not available in Debian.
Anyway, I understand that LXD BPF syscall interception should have avoided this bug.

LXD debug log says:
```
t=2021-10-23T17:30:47+0200 lvl=dbug msg="Handling bpf syscall" audit_architecture=3221225534 bpf_attach_type=-22 bpf_cmd=5 bpf_prog_type=15 container=buildbot-host project=default seccomp_notify_fd=45 seccomp_notify_flags=0 seccomp_notify_id=5556265980763106451 seccomp_notify_mem_fd=44 seccomp_notify_pid=7320 syscall_continue=true syscall_handler_error="invalid argument - Failed to handle bpf syscall" syscall_number=321
```

stracing lxd reports the following error:
```
[pid  6659] pread64(44, "\17\0\0\0c\0\0\0\0`/\0\300\0\0\0\320\30(\0\300\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 120, 824636385280) = 120
[pid  6659] pidfd_open(7320, 0)         = -1 EINVAL (Argument invalide)
[pid  6659] write(3, "t=2021-10-23T17:30:47+0200 lvl=dbug msg=\"Handling bpf syscall\" audit_architecture=3221225534 bpf_attach_type=-22 bpf_cmd=5 bpf_prog_type=15 container=buildbot-host project=default seccomp_notify_fd=45 seccomp_notify_flags=0 seccomp_notify_id=5556265980763106450 seccomp_notify_mem_fd=44 seccomp_notify_pid=7320 syscall_continue=true syscall_handler_error=\"invalid argument - Failed to handle bpf syscall\" syscall_number=321\n", 424) = 424
```
By reading kernel code of `pidfd_open` we can conclude that `EINVAL` is returned when given PID is not a thread group leader.
This is coherent with seccomp notify passing the thread PID in `seccomp_notif` structure and not the thread group leader PID.

LXD should determine the TGID and use it on pidfd_open instead of the thread PID

**Comment by sargun** [comment]
@stgraber An aside, rather than parsing /proc/<pid>/stat(us), I have a little kernel module for introspection here: https://github.com/Netflix/taskintrospection

**Comment by stgraber** [comment]
Looks like a nice and simple netlink API indeed. I believe Andrey Vagin and possibly other CRIU folks have been looking at replacing much of /proc with something more programmatically accessible (I think they were also leaning towards netlink?) as parsing ever changing text files can be very error prone...
