### ISSUE TITLE
Disk, memory and transfer units are not consistently using IEC units

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#9433]
# Required information

```
$ snap list lxd
Name  Version  Rev    Tracking       Publisher   Notes
lxd   4.19     21750  latest/stable  canonical✓  -
```
 # Issue description

Disk and memory should be expressed with IEC units but that is not consistently done everywhere.

# Steps to reproduce

```
$ lxc list -cnm xeon:squid
+-------+--------------+
| NAME  | MEMORY USAGE |
+-------+--------------+
| squid | 146.79MB     |
+-------+--------------+
```

The above should report something like 142MiB.

`git grep -F 'GetByteSizeString('` should be looked at to fix all those related to memory, disk and transfer/IO progress.

**Comment by RKBethke** [comment]
Hello! @TheNeroNex and I would be happy to tackle this one to get more familiar with the code base.  

When would IEC units be preferable to SI units?  We noticed SI is almost exclusively used throughout the repository as of now.

**Comment by TheNeroNex** [comment]
Dropping comment for assignment :)

**Comment by stgraber** [comment]
Done!
