### ISSUE TITLE
lxc import read from stdin

### ISSUE THREAD

**Issue by catsem** [lxc/lxd#9435]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-89-generic
   * LXC version: 
   * LXD version: 4.19
   * Storage backend in use: lvm

# Issue description

Would it be possible to add the functionality that lxc import could read from stdin?

My use case is, that I pipe the backup directly to the archive, e.g.:
`lxc export --compression none --instance-only foo - | borg backup create myArchive::{now} -`

That is already working fine, as the export class already had the “write to stdout” functionality. But the import class is missing the opposite “read from stdin” function.
(see https://github.com/lxc/lxd/blob/e86e1f8f7837ada83402bcc891ace8f5f8cfcd18/lxc/export.go#L129)

Currently to restore that backup I have to first write it to a file and then execute `lxc import myFile.tar` which is a superfluous step.

# Steps to reproduce

lxc export --compression none --instance-only foo - | lxc import - foo-new

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by presztak** [comment]
@stgraber Can I work on this?

**Comment by stgraber** [comment]
Absolutely!
