### ISSUE TITLE
Add doc section on pongo2 syntax for snapshots (timestamp example)

### ISSUE THREAD

**Issue by danboid** [lxc/lxd#9439]
Currently, if the user configures LXD snapshots and doesn't know about snapshots.pattern or how to configure it using Pongo2 syntax (who does?), the user gets snapshots named something like

snapshot-snap0

I think a much more sensible default is

snapshot-$DATEANDTIME

Which a user can configure by running a command such as:

$ lxc config set hermes snapshots.pattern "{{ creation_date|date:'2006-01-02_15-04-05' }}"

Hence I am requesting that either

{{ creation_date|date:'2006-01-02_15-04-05' }}

becomes the new default for snapshot.pattern or this config gets added to the docs at https://linuxcontainers.org/lxd/docs/master/instances to spare users having to search the web or learn Pongo2 to get useful, sensibly named snapshots.

**Comment by TheNeroNex** [comment]
Hey! Me and my partner @RKBethke are students from UT Austin's fall 2021 Virtualization class, and we'd like to make some contributions on issues for the repo. We were thinking of starting with this pretty simple one while we get familiar with the codebase, could I be assigned?

**Comment by RKBethke** [comment]
Excited to begin contributing to this repo! Commenting here to also be assigned.

**Comment by stgraber** [comment]
Done!

**Comment by danboid** [comment]
What I didn't know about LXD when I opened this ticket was that the `lxc info` command shows the time and date each snapshot was made it. However, I presume this depends upon you having made the snapshot with LXD and you having its db intact. I will still be inserting the time and date into my snapshots so that they are logically named outside of LXD.
