### ISSUE TITLE
Snapd nested lxd tests fails in 21.04

### ISSUE THREAD

**Issue by mvo5** [lxc/lxd#9447]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 21.04
 * The output of "lxc info": attached

# Issue description

Snapd in nested lxd stopped working in the edge channel for 21.04 (but seems to be okay for older versions of Ubuntu). 

# Steps to reproduce

This is what we are doing: https://github.com/snapcore/snapd/blob/master/tests/main/lxd/task.yaml#L72

The error happens inside:
```
lxd.lxc exec my-nesting-ubuntu -- \
        lxd.lxc exec my-inner-ubuntu -- \
            /root/prep-snapd-in-lxd.sh
```
when "systemctl restart snapd.service" is called in the my-inner-ubuntu.

There is also the following error inside the nested container:
```
# journalctl -u snapd.service
-- Journal begins at Fri 2021-10-29 15:11:26 UTC, ends at Fri 2021-10-29 16:18:3
7 UTC. --
Oct 29 15:11:52 my-inner-ubuntu systemd[1]: Starting Snap Daemon...
Oct 29 15:11:52 my-inner-ubuntu snapd[1655]: AppArmor status: apparmor is enable
d and all features are available
Oct 29 15:11:52 my-inner-ubuntu snapd[1655]: daemon.go:246: started snapd/1337.2
.53.1 (series 16; classic; testing) ubuntu/21.04 (amd64) linux/5.11.0-38-generic
.
Oct 29 15:11:52 my-inner-ubuntu snapd[1655]: main.go:129: system does not fully 
support snapd: apparmor detected but insufficient permissions to use it
Oct 29 15:11:52 my-inner-ubuntu snapd[1655]: daemon.go:339: adjusting startup ti
meout by 30s (pessimistic estimate of 30s plus 5s per snap)
Oct 29 15:11:52 my-inner-ubuntu snapd[1655]: cannot run daemon: state startup er
rors: [cannot reload snap-confine apparmor profile: cannot load apparmor profile
s: exit status 243
Oct 29 15:11:52 my-inner-ubuntu snapd[1655]: apparmor_parser output:
Oct 29 15:11:52 my-inner-ubuntu snapd[1655]: apparmor_parser: Unable to replace 
"mount-namespace-capture-helper".  Permission denied; attempted to load a profil
e while confined?
Oct 29 15:11:52 my-inner-ubuntu snapd[1655]: apparmor_parser: Unable to replace 
"/usr/lib/snapd/snap-confine".  Permission denied; attempted to load a profile w
hile confined?
Oct 29 15:11:52 my-inner-ubuntu snapd[1655]: ]
Oct 29 15:11:52 my-inner-ubuntu systemd[1]: snapd.service: Main process exited, 
code=exited, status=1/FAILURE
Oct 29 15:11:52 my-inner-ubuntu systemd[1]: snapd.service: Failed with result 'e
xit-code'.
Oct 29 15:11:52 my-inner-ubuntu systemd[1]: Failed to start Snap Daemon.
```

And the apparmor denails visible in the outside
```
[  901.601355] audit: type=1400 audit(1635520197.309:186): apparmor="STATUS" operation="profile_load" label="lxd-my-nesting-ubuntu_</var/snap/lxd/common/lxd>//&:lxd-my-nesting-ubuntu_<var-snap-lxd-common-lxd>:unconfined" name="lxd_dnsmasq-lxdbr0_</var/snap/lxd/common/lxd>" pid=39714 comm="apparmor_parser"
[  901.620299] audit: type=1400 audit(1635520197.325:187): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-my-nesting-ubuntu_<var-snap-lxd-common-lxd>" profile="lxd_dnsmasq-lxdbr0_</var/snap/lxd/common/lxd>" name="/var/snap/lxd/common/lxd/logs/dnsmasq.lxdbr0.log" pid=39715 comm="dnsmasq" requested_mask="wr" denied_mask="wr" fsuid=1000000 ouid=1000000
[  987.975772] lxdbr0: port 1(veth1f8d0d5f) entered blocking state
[  987.975776] lxdbr0: port 1(veth1f8d0d5f) entered disabled state
[  987.975976] device veth1f8d0d5f entered promiscuous mode
[  988.901561] audit: type=1400 audit(1635520284.606:188): apparmor="STATUS" operation="profile_load" label="lxd-my-nesting-ubuntu_</var/snap/lxd/common/lxd>//&:lxd-my-nesting-ubuntu_<var-snap-lxd-common-lxd>:unconfined" name="lxd-my-inner-ubuntu_</var/snap/lxd/common/lxd>" pid=39826 comm="apparmor_parser"
[  988.934985] physAsor5V: renamed from veth576f9d15
[  988.936475] eth0: renamed from physAsor5V
[  988.936905] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  988.936942] lxdbr0: port 1(veth1f8d0d5f) entered blocking state
[  988.936944] lxdbr0: port 1(veth1f8d0d5f) entered forwarding state
[  988.936964] IPv6: ADDRCONF(NETDEV_CHANGE): lxdbr0: link becomes ready
[  997.733748] audit: type=1400 audit(1635520293.438:189): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 namespace="root//lxd-my-nesting-ubuntu_<var-snap-lxd-common-lxd>" profile="lxd-my-inner-ubuntu_</var/snap/lxd/common/lxd>" name="/run/systemd/unit-root/proc/" pid=40553 comm="(networkd)" fstype="proc" srcname="proc" flags="rw, nosuid, nodev, noexec"
[  997.814697] audit: type=1400 audit(1635520293.518:190): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 namespace="root//lxd-my-nesting-ubuntu_<var-snap-lxd-common-lxd>" profile="lxd-my-inner-ubuntu_</var/snap/lxd/common/lxd>" name="/run/systemd/unit-root/proc/" pid=40564 comm="(resolved)" fstype="proc" srcname="proc" flags="rw, nosuid, nodev, noexec"
[ 1000.584445] audit: type=1400 audit(1635520296.290:191): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 namespace="root//lxd-my-nesting-ubuntu_<var-snap-lxd-common-lxd>" profile="lxd-my-inner-ubuntu_</var/snap/lxd/common/lxd>" name="/run/systemd/unit-root/proc/" pid=41040 comm="(d-logind)" fstype="proc" srcname="proc" flags="rw, nosuid, nodev, noexec"
```

# Information to attach

 - [x ] Any relevant kernel output (`dmesg`): see above
 - [x] Container log (`lxc info NAME --show-log`): see attachments
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

[lxd-info.txt](https://github.com/lxc/lxd/files/7443354/lxd-info.txt)
[lxd-my-ubuntu.txt](https://github.com/lxc/lxd/files/7443356/lxd-my-ubuntu.txt)
[lxd-my-inner-ubuntu.txt](https://github.com/lxc/lxd/files/7443357/lxd-my-inner-ubuntu.txt)
[lxc-config-show-my-ubuntu.txt](https://github.com/lxc/lxd/files/7443380/lxc-config-show-my-ubuntu.txt)
[lxc-config-show-my-inner-ubuntu.txt](https://github.com/lxc/lxd/files/7443381/lxc-config-show-my-inner-ubuntu.txt)

**Comment by mvo5** [comment]
Thanks @stgraber ! The host is also 21.04 (or 21.10, same failure there). 

We try to run snaps inside the nested container. This test used to work on 18.04/20.04 but if the nested use-case is not really supported and we were just lucky I think we can just remove this test and not test that snaps work inside nested lxd containers - if you are okay with this I will push a PR that removes this part of the test from our tree (it's a bit of a unusual use-case anyway I suppose).

**Comment by stgraber** [comment]
Ah, okay, so I'm quite confused as to how any of this used to work ;)

If snapd attempts to load apparmor profiles at installation time as the log suggests, then this should never have worked as nested containers don't have an apparmor namespace to load them into and also lack cap_mac_admin and cap_mac_overide which would be needed to perform that action.

It could be that the apparmor shell functions somehow behave differently on that Ubuntu version and so used to silently skip loading profiles rather than fail?

In any case, not seeing anything wrong with LXD here and sounds like this got fixed on the snapd side by not testing this unsupported scenario :)
