### ISSUE TITLE
lxc start fails

### ISSUE THREAD

**Issue by gulfpearl** [lxc/lxd#946]
This is on a wily host.

I receive the error:
```
error: Error calling 'lxd forkstart': exit status 1
```
and in the logs:
```
lxc_container 1438562920.444 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:808 - Operation not permitted - error mounting proc on /usr/lib/x86_64-linux-gnu/lxc/proc flags 14
```

**Comment by valmar** [comment]
I confirm this!. Same error. Version 0.14 on Vivid

**Comment by tych0** [comment]
On Sun, Aug 02, 2015 at 05:54:39PM -0700, Shidan Gouran wrote:
> This is on a wily host.
> 
> I receive the error:
> ```
> error: Error calling 'lxd forkstart': exit status 1
> ```
> and in the logs:
> ```
> lxc_container 1438562920.444 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:808 - Operation not permitted - error mounting proc on /usr/lib/x86_64-linux-gnu/lxc/proc flags 14
> ```

What user is LXD running as?

**Comment by gulfpearl** [comment]
root, also I downgraded to vivid and did the the exact same setup and at it
works fine now (for that problem).

**Comment by valmar** [comment]
Mine is still not solved. Same error. Here is the debugging output:

lxc start --debug centos6-amd64-psana
DBUG[08-11|16:59:27] fingering the daemon 
DBUG[08-11|16:59:27] raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_compat":1,"auth":"trusted","config":{},"environment":{"architectures":[2,1],"backing_fs":"btrfs","driver":"lxc","driver_version":"1.1.2","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.0.0-040000-generic","version":"0.15"}}}
 
DBUG[08-11|16:59:27] pong received 
DBUG[08-11|16:59:27] putting {"action":"start","force":false,"timeout":-1}
 to http://unix.socket/1.0/containers/centos6-amd64-psana/state 
DBUG[08-11|16:59:27] raw response: {"type":"async","status":"OK","status_code":100,"operation":"/1.0/operations/656d2ec8-5832-4719-8551-961ae17c836a","resources":null,"metadata":null}
 
DBUG[08-11|16:59:27] 1.0/operations/656d2ec8-5832-4719-8551-961ae17c836a/wait 
DBUG[08-11|16:59:33] raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"created_at":"2015-08-11T16:59:27.840130051+02:00","updated_at":"2015-08-11T16:59:33.003040243+02:00","status":"Failure","status_code":400,"resources":null,"metadata":"Error calling 'lxd forkstart centos6-amd64-psana /var/lib/lxd/containers /var/log/lxd/centos6-amd64-psana/lxc.conf': err='exit status 1'","may_cancel":false}}
 
error Error calling 'lxd forkstart centos6-amd64-psana /var/lib/lxd/containers /var/log/lxd/centos6-amd64-psana/lxc.conf': err='exit status 1'

**Comment by valmar** [comment]
Aaargh! Sorry, my fault! I was running a custom kernel. If I boot in the default one, everything works as expected.

**Comment by unaszplodrmann** [comment]
I received the same error with 3.19.0-26-generic on Vivid using unprivileged containers. Rebooted with 3.19.0-25-generic the containers started up.

**Comment by Cheddoleum** [comment]
Just a note to people having this or similar problems starting unprivileged containers with the Vivid kernel.  Consider adding the ubuntu-lxc/stable PPA version of lxc.   I encountered this problem when using the LTS kernel enablement stack (in a nutshell, allows you to use the vivid kernel in trusty).    

Corrected by updating lxc to the ubuntu-lxc/stable PPA version.

**Comment by christophlehmann** [comment]
Any news on that? Same here with unprivileged container under Linux 3.19.0-26-generic #28~14.04.1-Ubuntu SMP

**Comment by tych0** [comment]
Yes, it seems the current vivid kernel is still broken. I just spoke with the kernel team, and there will be an SRU version released next week that will fix it. The workaround now is just to downgrade to -25-generic as described above.

**Comment by Cheddoleum** [comment]
Thanks. Is there a bug # for this?   I'd like to observe the changeset in order to understand why it's happening.  It's involved in some peculiar, irreproducible trap-door effects on two of my systems.

**Comment by gulfpearl** [comment]
This also happens with 4.2.0-7-generic.

**Comment by tych0** [comment]
Hmm. Can you confirm that it is the same bug via lxc info --show-log $container?

**Comment by gulfpearl** [comment]
It looks the same to me, mounting related, it happens from 4.2.0-8-generic down to 3.19.0-26-generic :
```
            lxc 20150427012246.607 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:819 - Operation not permitted - error mounting proc on /usr/lib/x86_64-linux-gnu/lxc/proc flags 14
            lxc 20150427012246.607 ERROR    lxc_conf - conf.c:lxc_setup:3738 - failed to setup the automatic mounts for 'test'
            lxc 20150427012246.607 ERROR    lxc_start - start.c:do_start:712 - failed to setup the container
            lxc 20150427012246.607 ERROR    lxc_sync - sync.c:__sync_wait:51 - invalid sequence number 1. expected 2
            lxc 20150427012246.607 WARN     lxc_conf - conf.c:lxc_delete_network:2936 - failed to remove interface '(null)'
            lxc 20150427012246.624 ERROR    lxc_start - start.c:__lxc_start:1182 - failed to spawn 'test'
```

**Comment by gulfpearl** [comment]
If I mount /usr/lib/x86_64-linux-gnu/lxc/proc manually before running lxc start test it works.

**Comment by Cheddoleum** [comment]
Also, curiously, an init script that starts a certain user's (call him bob) autostarted unprivileged containers at startup with 

    exec su -l bob -c "/usr/bin/lxc-autostart"

works just fine under the affected kernels, like 2.19.0-26-generic.  This works for all such containers on two different systems.  However, user bob cannot start these or any other unprivileged containers himself without getting the above error, nor does the above invocation as root work at that point.

**Comment by fgggid** [comment]
Just FYI

My environment is:
Ubuntu Vivid with kernel 3.19.0-26-generic;
lxd 0.18 & lxc 1.1.3 which are from Wily repo;

Today I also meet this problem after "sudo apt-get install nfs-kernel-server" with its dependencies "rpcbind libnfsidmap2 libtirpc1 nfs-common keyutils", because I want to share some folder in my host to containers. :(

After I remove these new installed, and reboot, I can start container again. :)

**Comment by pcdummy** [comment]
You can mount ordinary directories into your container's by using

    lxc config device add <see the help>

You need to use setfacl if you want them to be useable by host and container users.

**Comment by w39hh** [comment]
This continues to be an issue with kernel 3.19.0-30-generic
Upgraded today from 3.19.0-25-generic to 3.19.0-30-generic, hit this issues and found this thread
Downgraded back to 3.19.0-25-generic and issue disappeared.

Ubuntu 15.04
lxc 1.1.3-0ubuntu1~ubuntu15.0
lxd 0.19-0ubuntu4~ubuntu15.04
nfs-server-kernel 1:1.2.8-9ubuntu8.1

**Comment by yoniy0** [comment]
Pardon, @gulfpearl, I realize this might not be the proper place to ask for directions (but, unfortunately, I'm not sure what is), but I can't seem to launch a container by manually mounting `/usr/lib/x86_64-linux-gnu/lxc/proc` first. At least not by mounting it with `lxc config device add <container> proc disk source=/usr/lib/x86_64-linux-gnu/lxc/proc path=proc`. Am I doing it wrong?

**Comment by gulfpearl** [comment]
mount --bind /proc /usr/lib/x86_64-linux-gnu/lxc/proc

but you would probably want to mount it using fstab.

**Comment by yoniy0** [comment]
@gulfpearl thank you, and I see where `fstab` would help with an auto-started container. But is that mount desirable for an unprivileged container? Is that something `lxc` would do on its own without this bug?

**Comment by gulfpearl** [comment]
Not sure, I think it should be only visible by the processes in the
container, but that's how I have done it for now. Hopefully someone else
will chime in with the way to do it with proper namespace isolation...
Overall LXD is pretty raw still, I think canonical were way too eager to
include it in so early and its really alpha software at this point.

**Comment by Atbara** [comment]
I'm dealing with the same problem. I was using kernel 4.0.18 and downgraded to -4.0.0 but with no luck.
I still receive this error whenever I try to create a container:

{error: Error calling 'lxd forkstart "name of my container" "container path/lxc.conf"': err='exit status 1'}

**Comment by hallyn** [comment]
@Atbara 
please open a new issue and show the result of lxc info --show-log container-name
