### ISSUE TITLE
`lxc cluster remove` fails with EOF

### ISSUE THREAD

**Issue by morphis** [lxc/lxd#9464]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4
   * LXC version: 4.0.11
   * LXD version: 4.0.8
   * Storage backend in use: zfs

# Issue description

In a cluster of 8 nodes removing one of the nodes when running `lxc cluster remove <name>` on the node to be removed causes the following error: `Error: Delete "http://unix.socket/1.0/cluster/members/lxd6": EOF`

The node is afterwards correctly removed from the cluster. 

Attempting to stop the LXD daemon afterwards (in our case via `snap disable lxd`) causes the command to hang. The `lxd.log` shows

```
t=2021-11-02T19:49:26+0000 lvl=info msg="Disabling clustering" serverName=
t=2021-11-02T19:49:26+0000 lvl=info msg="Stop database gateway" 
t=2021-11-02T19:49:26+0000 lvl=info msg="Dqlite proxy stopped" local=172.31.2.195:8443 name=runDqliteProxy remote=172.31.30.112:55418
t=2021-11-02T19:49:26+0000 lvl=info msg="Dqlite proxy stopped" local=172.31.2.195:42074 name=raftDial remote=172.31.30.112:8443
t=2021-11-02T19:49:26+0000 lvl=info msg="Starting database node" address=1 id=1 role=voter
t=2021-11-02T19:49:26+0000 lvl=info msg="Restarting LXD daemon following removal from cluster" 
```

Process list has

```
root           1  0.0  0.0 168436 10668 ?        Ss   16:13   0:11 /sbin/init
root         212  0.0  0.0  53132 14176 ?        S<s  16:13   0:00 /lib/systemd/systemd-journald
root         245  0.0  0.0  21200  5112 ?        Ss   16:13   0:00 /lib/systemd/systemd-udevd
root         376  0.0  0.1 279916 16288 ?        SLsl 16:13   0:00 /sbin/multipathd -d -s
systemd+     417  0.0  0.0  89564  6004 ?        Ssl  16:13   0:00 /lib/systemd/systemd-timesyncd
systemd+     496  0.0  0.0  26284  6652 ?        Ss   16:13   0:00 /lib/systemd/systemd-networkd
systemd+     499  0.0  0.0  23884 10744 ?        Ss   16:13   0:00 /lib/systemd/systemd-resolved
root         592  0.0  0.0 240716  8160 ?        Ssl  16:13   0:00 /usr/lib/accountsservice/accounts-daemon
root         595  0.0  0.0   8328  2580 ?        Ss   16:13   0:00 /usr/sbin/cron -f
message+     596  0.0  0.0   8488  4392 ?        Ss   16:13   0:01 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root         603  0.0  0.0  80924  2948 ?        Ssl  16:13   0:00 /usr/sbin/irqbalance --foreground
root         605  0.0  0.1  29064 16852 ?        Ss   16:13   0:00 /usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers
syslog       609  0.0  0.0 221176  3932 ?        Ssl  16:13   0:00 /usr/sbin/rsyslogd -n -iNONE
root         610  0.0  0.2 1301648 36680 ?       Ssl  16:13   0:11 /usr/lib/snapd/snapd
root       61280  0.0  0.0  10448  1384 ?        S    19:49   0:00  \_ systemctl stop snap.lxd.daemon.service
root         612  0.0  0.0  16260  6716 ?        Ss   16:13   0:00 /lib/systemd/systemd-logind
root         615  0.0  0.0 393692 12356 ?        Ssl  16:13   0:00 /usr/lib/udisks2/udisksd
daemon       616  0.0  0.0   3584  1760 ?        Ss   16:13   0:00 /usr/sbin/atd -f
root         632  0.0  0.0   6832  1864 ttyS0    Ss+  16:13   0:00 /sbin/agetty -o -p -- \u --keep-baud 115200,38400,9600 ttyS0 vt220
root         650  0.0  0.0   5308  1456 tty1     Ss+  16:13   0:00 /sbin/agetty -o -p -- \u --noclear tty1 linux
root         673  0.0  0.1 107824 19240 ?        Ssl  16:13   0:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
root         689  0.0  0.0 236132  8072 ?        Ssl  16:13   0:00 /usr/lib/policykit-1/polkitd --no-debug
root         801  0.0  0.0  12200  6472 ?        Ss   16:13   0:00 sshd: /usr/sbin/sshd -D -o AuthorizedKeysCommand /usr/share/ec2-instance-connect/eic_run_authorized_keys %u %f -o AuthorizedKeysCommandUser ec2-instance-connect [listener] 0 of 10-100 startups
root       61502  0.0  0.0  15456  7716 ?        Ss   19:51   0:00  \_ sshd: ubuntu [priv]
ubuntu     61609  0.0  0.0  15592  4384 ?        S    19:51   0:00      \_ sshd: ubuntu@pts/0
ubuntu     61611  0.0  0.0   9768  4732 pts/0    Ss   19:51   0:00          \_ -bash
ubuntu     61890  0.0  0.0  10524  3120 pts/0    R+   19:54   0:00              \_ ps fauxww
root        1289  0.0  0.1 1455540 17572 ?       Ssl  16:13   0:00 /snap/amazon-ssm-agent/4047/amazon-ssm-agent
root        1332  0.0  0.1 1466904 29248 ?       Sl   16:13   0:00  \_ /snap/amazon-ssm-agent/4047/ssm-agent-worker
root        2882  0.0  0.0   8324  2988 ?        Ss   16:13   0:00 bash /etc/systemd/system/jujud-machine-8-exec-start.sh
root        2887  0.0  0.6 854172 96160 ?        Sl   16:13   0:12  \_ /var/lib/juju/tools/machine-8/jujud machine --data-dir /var/lib/juju --machine-id 8 --debug
root       60853  0.2  0.2  46664 38244 ?        S    19:49   0:00      \_ /var/lib/juju/agents/unit-lxd-7/.venv/bin/python /var/lib/juju/agents/unit-lxd-7/charm/hooks/pool-storage-detaching
root       61263  0.3  0.1 840032 21708 ?        Sl   19:49   0:01          \_ snap disable lxd
dnsmasq     3368  0.0  0.0  11720   340 ?        S    16:13   0:00 dnsmasq -u dnsmasq --strict-order --bind-interfaces --pid-file=/run/ubuntu-fan/dnsmasq-fan-252.pid --conf-file= --listen-address 252.2.195.1 --dhcp-range 252.2.195.2,252.2.195.254 --dhcp-no-override --except-interface=lo --interface=fan-252 --dhcp-leasefile=/var/lib/misc/dnsmasq.fan-252.leases --dhcp-authoritative
root       18210  0.0  0.0 163232  4092 ?        Ssl  16:14   0:00 /usr/sbin/zed -F
root       23428  0.0  0.0   2060  1368 ?        Ss   16:15   0:00 /bin/sh /snap/lxd/21804/commands/daemon.start
root       23611  0.5  0.1 1266832 29312 ?       Sl   16:15   1:13  \_ lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root       23600  0.0  0.0  85308  1500 ?        Sl   16:15   0:00 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid
root       61281  0.0  0.0   2060  1340 ?        Ss   19:49   0:00 /bin/sh /snap/lxd/21804/commands/daemon.stop
root       61889  0.0  0.0   3700   448 ?        S    19:54   0:00  \_ sleep 1
ubuntu     61505  0.0  0.0  17952  8500 ?        Ss   19:51   0:00 /lib/systemd/systemd --user
ubuntu     61506  0.0  0.0 170236  3752 ?        S    19:51   0:00  \_ (sd-pam)

```

Systemd will timeout the stop command after a while and take the daemon down

# Steps to reproduce

 1. Create a cluster with 8 nodes
 2. On a non-database node run `lxc cluster remove <name of the node>`

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Based on previous chats, it looks like two behavior may occur in this scenario:
 - Cluster member is successfully removed but EOF is returned as LXD is restarted prior to the request completing
 - Cluster member removal straight up fails with `Error: Unable to inspect leader: No such object`

**Comment by stgraber** [comment]
We should add a test to cover this particular scenario as part of one of the existing clustering testsuites and then sort out whatever is causing this issue.

**Comment by tomponline** [comment]
We can probably use the ManualResponse type to send the response before restarting

https://github.com/lxc/lxd/blob/3ff91aa566d32f84b463d1aa9dfd23281bb5fc04/lxd/api_cluster.go#L760

**Comment by morphis** [comment]
As I was scaling the cluster node by node further down I now ran into 

```
unit-lxd-1: 21:25:14 INFO unit.lxd/1.juju-log Error executing `/snap/bin/lxc cluster remove lxd1`: 1 - Error: failed to begin transaction: failed to create dqlite connection: no available dqlite leader server found
```
Look at the cluster (from the same node the remove command was execute on by the charm):

```
ubuntu@ip-172-31-31-238:~$ sudo lxd cluster list-database
+--------------------+
|      ADDRESS       |
+--------------------+
| 172.31.12.192:8443 |
+--------------------+
| 172.31.21.247:8443 |
+--------------------+
| 172.31.10.229:8443 |
+--------------------+
ubuntu@ip-172-31-31-238:~$ lxc cluster ls
+------+----------------------------+----------+--------+-------------------+--------------+
| NAME |            URL             | DATABASE | STATE  |      MESSAGE      | ARCHITECTURE |
+------+----------------------------+----------+--------+-------------------+--------------+
| lxd1 | https://172.31.31.238:8443 | YES      | ONLINE | Fully operational | aarch64      |
+------+----------------------------+----------+--------+-------------------+--------------+
| lxd2 | https://172.31.12.192:8443 | YES      | ONLINE | Fully operational | aarch64      |
+------+----------------------------+----------+--------+-------------------+--------------+
| lxd3 | https://172.31.10.229:8443 | YES      | ONLINE | Fully operational | aarch64      |
+------+----------------------------+----------+--------+-------------------+--------------+
| lxd4 | https://172.31.21.247:8443 | YES      | ONLINE | Fully operational | aarch64      |
+------+----------------------------+----------+--------+-------------------+--------------+
```

After a few more retries of the failed Juju hook the `lxc cluster remove` command finally went through and the node was dropped from the cluster. Running `lxc cluster ls` from the remaining nodes shows a healthy cluster.

**Comment by masnax** [comment]
> Based on previous chats, it looks like two behavior may occur in this scenario:
> 
>     * Cluster member is successfully removed but EOF is returned as LXD is restarted prior to the request completing
This seems to be because using `http.Flusher.Flush()` to get a response before restarting takes a tad too long. Trying to figure out why it's slow, but just adding as much as a 100ms sleep seems to fix this as a bandaid.
>     * Cluster member removal straight up fails with `Error: Unable to inspect leader: No such object`
This one's really weird. The only way this can happen is if for some reason the leader address we get from the gateway is not actually in the nodes database. As yet I haven't been able to reproduce this one.

**Comment by tomponline** [comment]
I wonder if waiting until r.Context() is done before restarting would be a better way of ensuring the client has got the response before restarting.

**Comment by morphis** [comment]
I got the `Error: Unable to inspect leader: No such object` error reproduced. Basically adding and removing nodes over and over again and at some point the problem shows up. 

https://private-fileshare.canonical.com/~morphis/lxc-unable-to-inspect-leader.log has the log of the lxd node which our charm tries to remove with executing `lxc cluster remove <name>` from the node itself. 

The juju log shows that the `Error: Unable to inspect leader: No such object` error is just a symptom of another thing going wrong. The very first time `lxc cluster remove` is executed the error is `Error: failed to begin transaction: failed to create dqlite connection: no available dqlite leader` and any subsequent calls get  `Error: Unable to inspect leader: No such object`

**Comment by stgraber** [comment]
@morphis when you get one of the weird ones (so not the EOF), can you check if LXD crashed/restarted on any of the servers?

**Comment by morphis** [comment]
@stgraber No, haven't seen any crash on the other nodes. Uploaded their logs at https://private-fileshare.canonical.com/~morphis/node-logs/
