### ISSUE TITLE
GetNonPendingNetworkIDs function is not project aware

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9466]
The `GetNonPendingNetworkIDs` function is not project aware, and yet returns a map of network names to IDs.
This means its possible for the same network to exist in different projects and for one to be overwritten with the other in the output.

This function is currently used during cluster member join.
This function either needs to be removed, and the cluster member join process reworked or this function needs to be updated to take into accounts projects (similar to `GetCreatedNetworks`).

https://github.com/lxc/lxd/blob/master/lxd/db/networks.go#L44-L71

**Comment by archevan** [comment]
I've left some comments on a couple of other issues but this seems like something my group could tackle as part of a final virtualization project at UT Austin. Could you assign this one to me as well?

**Comment by stgraber** [comment]
Done!
