### ISSUE TITLE
LXC command not found

### ISSUE THREAD

**Issue by emilebosch** [lxc/lxd#950]
After clean install of Ubuntu 15.04 i can't get the lxc command to work,it says not found. Any ideas?

````
root@vps-deploy:~# lxd
error: cannot listen on unix socket: listen unix /var/lib/lxd/unix.socket: bind: address already in use
root@vps-deploy:~# 
````

```
apt-get -y update && apt-get -y upgrade
apt-get install -y nginx software-properties-common
add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
apt-get -y update
apt-get -y install lxd
```

When excuting `lxc` -> command not found.

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
```

```
 lxd --version
```

```
0.14
```

**Comment by tych0** [comment]
On Mon, Aug 03, 2015 at 08:47:19AM -0700, Emile Bosch wrote:
> After clean install of Ubuntu 15.04 i can't get the lxc command to work,it says not found. Any ideas?
> 
> ````
> root@vps-deploy:~# lxd
> error: cannot listen on unix socket: listen unix /var/lib/lxd/unix.socket: bind: address already in use
> root@vps-deploy:~# 
> ````
> 
> ```
> apt-get -y update && apt-get -y upgrade
> apt-get install -y nginx software-properties-common
> add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
> apt-get -y update
> apt-get -y install lxd
> ```
> 
> When excuting `lxc` -> command not found.

You need to install lxd-client.

**Comment by TimJSwan89** [comment]
Can you explain what the package that allows `lxc-info` to run if it is not `lxd-client`? Thanks.

**Comment by stgraber** [comment]
All "lxc-<blah>" commands come from the low level set of LXC tools (no LXD daemon involved), all "lxc <blah>" commands are API commands for LXD.

So the "lxc" command comes from the lxd-client package, the "lxc-*" commands come from the lxc1 package.

The "lxc" command will only show you containers managed by a LXD daemon, the "lxc-*" commands will only show you containers that are NOT managed by a LXD daemon.
