### ISSUE TITLE
Particular reason for using farjump/go-libudev and not jochenvg/go-udev?

### ISSUE THREAD

**Issue by gibmat** [lxc/lxd#9504]
# Issue description

Was there a particular reason why LXD chose to use github.com/farjump/go-libudev rather than the upstream (github.com/jochenvg/go-udev) of that fork? Both of those repositories appear identical, and it's nice to not depend on unneeded forks of libraries.

This was noticed while reviewing dependencies needed to cleanly package LXD for Debian.

**Comment by stgraber** [comment]
Sent a fix!
