### ISSUE TITLE
LXD depends on dead version of juju/httprequest

### ISSUE THREAD

**Issue by gibmat** [lxc/lxd#9506]
# Issue description

LXD has a single include of github.com/juju/httprequest, but that repo seems to be dead (https://github.com/juju/httprequest/issues/59). Would it be possible to switch to the upstream version of that library, https://github.com/go-httprequest/httprequest ?

This was noticed while reviewing dependencies needed to cleanly package LXD for Debian, where go-httprequest/httprequest is already packaged as golang-gopkg-httprequest.v1.

**Comment by stgraber** [comment]
Seems to indeed be building fine with go-httprequest, so let's try that :)
