### ISSUE TITLE
Multiple GPU device passthrough doesn't work for VMs

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9508]
Whilst fixing an issue preventing multiple `usb` device passthrough in VMs (https://github.com/lxc/lxd/pull/9497) it was noticed that `gpu` devices on VMs also have the same issue.

@stgraber said https://github.com/lxc/lxd/pull/9497#issuecomment-963278299

> For containers, you can definitely do `lxc config device add BLAH gpu gpu` which then passes every single GPU on the host system. You can also use vendorid/productid matching to get multiple GPUs, same as USB.

So we should also support that sort of functionality for VMs, and where it doesn't make sense, clarify the docs and the validation.

The following `gpu` device types don't have any support for passing through multiple devices for VMs:

* `gpu_physical`: https://linuxcontainers.org/lxd/docs/master/instances#gpu-physical - this one appears to have an explicit check preventing multiple device pass-through (https://github.com/lxc/lxd/blob/master/lxd/device/gpu_physical.go#L236) so we should explore why this is here, and if correct, clarify in docs.
* `gpu_mdev`: https://linuxcontainers.org/lxd/docs/master/instances#gpu-mdev - this one appears to have an explicit check preventing multiple device pass-through (https://github.com/lxc/lxd/blob/master/lxd/device/gpu_mdev.go#L72-L74) so we should explore why this is here, and if correct, clarify in docs.
* `gpu_mig`: https://linuxcontainers.org/lxd/docs/master/instances#gpu-mig - this one appears to have an explicit check preventing multiple device pass-through (https://github.com/lxc/lxd/blob/master/lxd/device/gpu_mig.go#L106-L108) so we should explore why this is here, and if correct, clarify in docs. Also the docs say it supports only containers, but its validation code says its supports VMs too (https://github.com/lxc/lxd/blob/master/lxd/device/gpu_mig.go#L24). That needs clarifying.
* `gpu_sriov`: https://linuxcontainers.org/lxd/docs/master/instances#gpu-sriov - this one may not make sense to support multiple devices, but we should clarify that in the docs and in the validation (like `gpu_mig` does) to ensure not accidentally passing through the wrong gpu.

**Comment by C-Stout** [comment]
Hello, may I be assigned this issue so my virtualization group at UT Austin can work on this?

**Comment by stgraber** [comment]
Done!

**Comment by stgraber** [comment]
So looking into what @tomponline wrote and the state of the code, the actions to take here are:
 - Update device/gpu_mig.go to validate that it's only used with containers (MIG isn't supported on VMs)
 - In general clarify in the docs that while GPU passthrough in containers can match multiple GPUs at once, for VMs, a device can only match a single GPU

**Comment by stgraber** [comment]
@C-Stout hello, just wanted to check if you still intend to work on this or if we should unassign it so someone else can take a crack at it?
