### ISSUE TITLE
Add support for UUID selection of NVIDIA MIG devices

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#9518]
NVIDIA driver 470 and up have changed from the easy /gi/ci syntax for the device to a new obscure UUID.
To support this, we should add a `mig.uuid` option which takes a valid UUID (must start with MIG-).
When this is set, `mig.ci` and `mig.gi` must become invalid.

The UUID is then used as the device to be passed to nvidia-container.

**Comment by dillonsamra9** [comment]
Hi. I'm a CS student at UT Austin and am currently taking a Virtualization class. I would be happy to take a look at this issue?

**Comment by stgraber** [comment]
Sounds good, assigned it to you!

**Comment by stgraber** [comment]
For this one, I'd expect the following commits:
 - `api: gpu_mig_uuid` (modifies doc/api-extensions.md and shared/version/api.go)
 - `doc/instances: Add mig.uuid on MIG GPU` (adds the property to doc/instances.md)
 - `lxd/device/gpu: Add support for mig.uuid` (actually adds handling of `mig.uuid`, should validate the leading MIG-, should prevent it be set if either mig.ci or mig.gi is set and should override the UUID returned in RunConfig)

**Comment by VincentK-Titandc** [comment]
Since NVIDIA driver 470 does not work with old /gi/ci syntax (eg. MIG-GPU-2e4159a0-dab5-1747-e7b7-b3396fab58b4/7/0), required env var `NVIDIA_VISIBLE_DEVICES` can be overridden as a workaround until we get `mig.uuid` working:

```
  raw.lxc: |-
    lxc.environment = NVIDIA_VISIBLE_DEVICES=MIG-0ae0c875-8fc2-5295-8e5e-de3d2a52eb60
```

Hopefully raw settings are pushed at the very end of lxc.conf.

**Comment by stgraber** [comment]
@dillonsamra9 hello, just wanted to check if you still intend to work on this or if we should unassign it so someone else can take a crack at it?

**Comment by dillonsamra9** [comment]
@stgraber, yes you can assign this to someone else. Thanks for all of your help as I worked to contribute to this repo!

**Comment by VincentK-Titandc** [comment]
@stgraber alright then I'll take it.

**Comment by stgraber** [comment]
Done!
