### ISSUE TITLE
Running snapd inside lxd in 21.10 fails with: Permission denied errors from udev

### ISSUE THREAD

**Issue by mvo5** [lxc/lxd#9526]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 21.10
 * The output of "lxc info" or if that fails: [lxc-info.txt](https://github.com/lxc/lxd/files/7526933/lxc-info.txt)

# Issue description

In 21.10 our snapd lxd test is failing currently. I extracted a minimal reproducer in the script: [lxd-reproducer.sh.txt](https://github.com/lxc/lxd/files/7526960/lxd-reproducer.sh.txt)

# Steps to reproduce

```
#!/bin/sh

set -e
set -x

lxd.lxc stop my-ubuntu || true
lxd.lxc delete my-ubuntu  || true

lxd.lxc launch "ubuntu:21.10" my-ubuntu
lxd.lxc exec my-ubuntu echo hello

lxd.lxc exec my-ubuntu -- apt autoremove --purge -y snapd ubuntu-core-launcher
lxd.lxc exec my-ubuntu -- apt install -y snapd
lxd.lxc exec my-ubuntu -- systemctl daemon-reload
lxd.lxc exec my-ubuntu -- systemctl restart snapd.service
lxd.lxc exec my-ubuntu -- snap wait system seed.loaded

lxd.lxc exec my-ubuntu -- snap install test-snapd-sh
```
The errors I see with that are:
```
...
+ lxd.lxc exec my-ubuntu -- systemctl daemon-reload
+ lxd.lxc exec my-ubuntu -- systemctl restart snapd.service
+ lxd.lxc exec my-ubuntu -- snap wait system seed.loaded
+ lxd.lxc exec my-ubuntu -- snap install test-snapd-sh
error: cannot perform the following tasks:
- Setup snap "core" (11993) security profiles (cannot run udev triggers: exit status 1
udev output:
LNXSYSTM:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/uevent': Permission denied
...
```

This *could* be related to https://github.com/snapcore/snapd/pull/11039 or our switch to cgroups v2 so it might be something that we need to fix on the snapd side. So any hints are appreciated.

# Information to attach

Happy to attach more output but it should be fairly easy to reproduce on a 21.10 system.

**Comment by stgraber** [comment]
`udevadm trigger` changed in 21.10 to return errors for conditions that didn't use to trigger one.

After some discussions upstream, the compromise made to still have LXD behave was that their systemd unit (systemd-udev-trigger.service) would be configured to ignore non-zero return values from udevadm. I believe snapd needs to do the same here, call `udevadm trigger` but not fail when it returns non-zero.

**Comment by brauner** [comment]
There should be a proper fix in upstream systemd for this:
- discussion: https://github.com/systemd/systemd/pull/18559
- fix: https://github.com/systemd/systemd/pull/18684

**Comment by brauner** [comment]
To get the old behavior you can pass `--quiet` to `udevadm`.

**Comment by mvo5** [comment]
You guys rock, thank you so much! I think we can close this one then.
