### ISSUE TITLE
Remove use of legacy protobuf library

### ISSUE THREAD

**Issue by gibmat** [lxc/lxd#9531]
# Issue description

(I'll prefix this by saying I'm not very familiar with golang's protobuf libraries, although I've spent a good chunk of today learning about the legacy and new libraries....)

LXD is currently using both the legacy/deprecated (github.com/golang/protobuf) and new (github.com/protocolbuffers/protobuf-go) versions of the protobuf library. However, the legacy version is only used in one file (`lxd/bgp/server.go`), that's using the deprecated `ptypes` library methods. (The upstream [pull request](https://github.com/golang/protobuf/pull/1217) has comments in the diff indicating switching to the new methods should be very easy.)

Could you please remove LXD's use of the legacy protobuf library? That will help trim down its dependency tree, and prevent possible issues when mixing the old and new protobuf libraries.

(I initially found this issue in a library down in LXD's dependency tree while preparing to package it for Debian, but the same mixing of protobuf library versions exists in LXD.)

**Comment by stgraber** [comment]
I tried to do so but couldn't as the `gobgp` package itself relies on the specific use of `ptypes`.

**Comment by stgraber** [comment]
I suspect we may need https://github.com/osrg/gobgp to take the first step and move away from ptypes, then we can do the same on our side. The rest of our protobuf usage was already updated to the new packages.

**Comment by gibmat** [comment]
Ah, got it. I'll open an issue with them to make that request.

**Comment by stgraber** [comment]
Closing as not actionable on our side currently. Also Go is complaining every time I update our gomod, so I already have a constant reminder of this ;)

Once gobgp is fixed, our build will almost certainly start failing due to type mismatch, we'll then correct it and that will take care of it.

**Comment by gibmat** [comment]
gobgp has tagged a couple 3.0.0-rc releases that moves to the new protobuf library (https://github.com/osrg/gobgp/issues/2485). I've verified from a very simple standpoint that LXD 4.21 compiles with changes made to `lxd/bgp/server.go`, but as I don't have any BGP stuff setup locally, I can't test to ensure nothing's inadvertently broken LXD.

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/pull/9704
