### ISSUE TITLE
Autostart based on last state

### ISSUE THREAD

**Issue by knutov** [lxc/lxd#9545]
As for now (latest LXD 4.20 from snap) all containers with enabled autostart starts:

1. when server starts and snapd starts
2. when LXD in snap refreshed to any new LXD version or when snapd restarts

The second case often is not desired behavior if container was stopped manually. The worst case as an example - multiple containers with routed network on different servers with the same public ip for CT - when LXD refreshes on some server in this case it starts stopped containers on current server (if autostart is enabled for them) and all traffic for this IP is going to the wrong server to container which was stopped and not supposed to be running.

Is it possible to change autostart behavior to be based on last state? I suppose `volatile.last_state.power` can be used as source for last state.

This can also be connected with https://github.com/lxc/lxc/issues/4029 as an alternative way to monitor the situation and autostart stopped containers which last state was "running".

Also, I suppose some ARP checks must be done during CT start and containers should not be starting if the same public ip is already running somewhere. At least for routed/macvlan/ipvlan network with public IPs. Should I open different issue about it?

**Comment by stgraber** [comment]
snap refreshes do not restart containers, `snap restart lxd` would do it though but we usual advice people against doing that.

LXD default autostart is based on last state.  What you're describing suggests that you actually have `boot.autostart` set to `true` which would have LXD always start the instance every time it starts itself.

Just leave `boot.autostart` unset and it will follow the last state.

**Comment by stgraber** [comment]
Key                                         | Type      | Default           | Live update   | Condition                 | Description
:--                                         | :---      | :------           | :----------   | :----------               | :----------
boot.autostart                              | boolean   | -                 | n/a           | -                         | Always start the instance when LXD starts (if not set, restore last state)

**Comment by knutov** [comment]
So, may be some bug occures somewhere here.

My setup:

server1: ct1, routed network, public ipv4, boot.autostart=1
server2: ct2, routed network, same public ipv4, boot.autostart=1

lxc start ct1 # now all traffic goes to ct1 at server1
lxc stop ct1
lxc start ct2 # now all traffic for the same ip goes to ct2 at server2
after some time and, I suppose, new version of LXD from snap with autorefresh enabled
and now I can see both CT is running and traffic goes to ct1 at server1 while it should not be started and ct2 with this ip must be available.

Last time it happened about yesterday nearly the same time the new LXD version arrived from snap.

How to debug this issue?

**Comment by knutov** [comment]
oh, I did not notice  that!

> Just leave boot.autostart unset and it will follow the last state.

I suppose I understand this setting wrong before, I think it will solve the issue. Thanks!

**Comment by knutov** [comment]
But ARP checks still should be done, I think. I will open different issue with bash code to reproduce that.

**Comment by stgraber** [comment]
For the ARP side of things, I'd like @tomponline's opinion, but in general, we don't prevent users from shooting themselves in the foot or doing what feels like odd setups.

What if you're trying to show a class what happens when you get a MAC or IP conflict on a network?

**Comment by knutov** [comment]
@stgraber How exactly can I do it?

How it looks like described in https://github.com/lxc/lxd/issues/9545#issuecomment-973317307

cisco c4948efs used before both servers.

**Comment by knutov** [comment]
So it does not look like ip conflict, rather ip stealing

**Comment by tomponline** [comment]
As @stgraber in general none of the LXD NIC types prevent IP conflicts (in principle it would be possible, for example, to use the `bridged` NIC type with the `ipv{n}.address` setting to setup a static DHCP allocation that conflicts with another host on the network that has had their IP configured manually).

However `routed` and `ipvlan` NIC types are somewhat different in that they alone take a specified `ipv{n}.address` setting and setup ARP/NDP proxy entries on the host.

We could add an IP neighbour detection feature before starting the instance and preventing starting in that case. However it would require that the instance start be slowed down (as we would be waiting for an absence of response rather than a positive one to allow the instance to start). For that reason I suspect we would want it under a NIC level option with warnings about slowed instance start time.

**Comment by knutov** [comment]
@tomponline 

> it would require that the instance start be slowed down

It don't took much time in real life I think. I'm still using OpenVZ 6 on some legacy projects and there are ARP checks in OpenVZ and they are fast enough.

With OpenVZ ct will start without working network in case ip is already used if I recall correctly, but I'd prefer do not start at all in such case if it is possible.
 
> as we would be waiting for an absence of response rather than a positive one to allow the instance to start

btw, why not invert this logic?

It's faster do not start in case of response (it's nearly instant) and do not wait for "no responce" (even if timeout still can be configured to small enough time)?

**Comment by tomponline** [comment]
> it's nearly instant

We would need to define how long "nearly instant" is and wait that long.

**Comment by knutov** [comment]
1.5 second looks fine (but may be it can be done faster):

```
# time arp
...
real	0m0.104s
user	0m0.002s
sys	0m0.000s

# time arping -c1 x.x.x.234 # not exists 
ARPING x.x.x.234 from x.x.x.2 eno1
Sent 1 probes (1 broadcast(s))
Received 0 response(s)

real	0m1.019s
user	0m0.011s
sys	0m0.000s

# time arping -c1 x.x.x.82 # exists
ARPING x.x.x.82 from x.x.x.2 eno1
Unicast reply from x.x.x.82 [00:25:90:FC:D2:A4]  322.530ms
Sent 1 probes (1 broadcast(s))
Received 1 response(s)

real	0m1.016s
user	0m0.000s
sys	0m0.011s
```

**Comment by tomponline** [comment]
Yep that sounds fine, but 1.5s is quite a long time with respect to a container start time, so I do think it should be optional (perhaps configurable timeout). We'd also need to figure out how to do this from go, as don't really want to be running a process for each IP specified on the NIC. 

Can you open an issue https://github.com/lxc/lxd/issues here?

**Comment by knutov** [comment]
OpenVZ 6 definitely do it instantly, they do

```
ARPING=$(/sbin/arping -q -c 2 -w ${ARPING_WAIT:-3} -D -I ${parent_device} ${IPADDR})

if [ $? = 1 ]; then
    ARPINGMAC=$(echo $ARPING |  sed -ne 's/.*\[\(.*\)\].*/\1/p')
    net_log $"Error, some other host ($ARPINGMAC) already uses address ${IPADDR}."
    return 1
fi
```

it's from `/etc/sysconfig/network-scripts/ifup-aliases` from OpenVZ 6, may be just make the same?

**Comment by tomponline** [comment]
That takes about 2s:

```
time sudo arping -q -c 2 -w -3 -D -I enp4s0 192.168.1.200
..	100% packet loss (0 extra)

real	0m2.116s
user	0m0.003s
sys	0m0.003s
```

**Comment by knutov** [comment]
strange, but even 4s on centos/openvz6, but...

```
# time vzctl start 2037
Starting container...
Container is mounted
Adding IP address(es): x.x.x.82
Setting devices
Container start in progress...

real	0m1.174s
user	0m0.044s
sys	0m0.056s
```

I will attach the full code from OpenVZ a little bit later, may be some optimization for this process is possible and used by them.

**Comment by tomponline** [comment]
Likely ARPING_WAIT is coming from somewhere set to 1.
