### ISSUE TITLE
ARP check to avoid duplicate addresses on routed nictype

### ISSUE THREAD

**Issue by knutov** [lxc/lxd#9547]
This is feature request, as requested in https://github.com/lxc/lxd/issues/9545#issuecomment-973976440 :

It is possible to run multiple containers on the same server or on the neighbor server with the same public ip with routed/macvlan/ipvlan network.

Traffic for this public ip will be routed to the **last** **started** container which is ip stealing in fact and it is usually unwanted/unexpected behavior.

> Example:
> 
> server1: ct1, routed network, public ipv4
> server2: ct2, routed network, same public ipv4
> 
> lxc start ct1 # now all traffic goes to ct1 at server1
> lxc stop ct1
> lxc start ct2 # now all traffic for the same ip goes to ct2 at server2
> lxc start ct1 # now all traffic goes to ct1 at server1 again but should not to - ip is already used on ct2

I suppose it's better to do ARP checks (may by optional) and do not start container at all in the case IP is already used.

`arping` can be used to check if IP is already used in this network. 

For example, OpenVZ 6 do these checks in `/etc/sysconfig/network-scripts/ifup-eth` [ifup-eth.txt](https://github.com/lxc/lxd/files/7570030/ifup-eth.txt) and [ifup-aliases.txt](https://github.com/lxc/lxd/files/7569944/ifup-aliases.txt)

```bash
echo $"Determining if ip address ${ipaddr[$idx]} is already in use for device ${REALDEVICE}..."
if ! ARPING=$(/sbin/arping -c 2 -w ${ARPING_WAIT:-3} -D -I ${REALDEVICE} ${ipaddr[$idx]}) ; then
        ARPINGMAC=$(echo $ARPING |  sed -ne 's/.*\[\(.*\)\].*/\1/p')
        net_log $"Error, some other host ($ARPINGMAC) already uses address ${ipaddr[$idx]}."
        exit 1
fi
```

**Comment by knutov** [comment]
`arp -f` can speedup the process in case ip is used: "If you use the -f option, your arping will stop as soon as it has confirmed that the system is responding"

```
# time arping -f -c2 x.x.x.36 # ip is used and in arp table (`arp -a`) on current server - instant
ARPING x.x.x.36 from x.x.x.2 eno1
Unicast reply from x.x.x.36 [AC:1F:6B:17:64:15]  0.687ms
Sent 1 probes (1 broadcast(s))
Received 1 response(s)

real	0m0.014s
user	0m0.001s
sys	0m0.000s

# time arping -f  x.x.x.63 # ip is used, not in arp table (arp -a) on current server - tooks 0.5s
ARPING x.x.x.63 from x.x.x.2 eno1
Unicast reply from x.x.x.63 [0C:C4:7A:B5:19:8A]  559.182ms
Sent 1 probes (1 broadcast(s))
Received 1 response(s)

real	0m0.583s
user	0m0.005s
sys	0m0.000s


# time arping -f -c2 x.x.x.99 # ip is not used: tooks 2s
ARPING x.x.x.99 from x.x.x.2 eno1
Sent 2 probes (2 broadcast(s))
Received 0 response(s)

real	0m2.023s
user	0m0.000s
sys	0m0.009s 
```

**Comment by tomponline** [comment]
Yes, we would expect to stop waiting after a positive response was received. But my point is that in a "normal" start sequence (where hopefully the NIC's IPs are not already in use), there will be no positive response, and so we need to decide how long to wait for an absence of a response.

In the example above, in the normal scenario where the IP is not used, `arping` wait for 2s.
So this would delay openvz startup by 2s, so I suspect they are passing an argument to get arping to wait less time, probably 1s.

**Comment by knutov** [comment]
Yes, it will slow down normal startup, but it's still much better than chance of bad scenario where ip stealing occurs.

Adding commandline option to `lxc start` and config key like `boot.check_arp` will make it comfortable for all users I think.

btw, is it possible to use something like https://pkg.go.dev/github.com/j-keck/arping with smaller timeouts and making it in parallel with something? It can speedup normal startup then.

**Comment by stgraber** [comment]
If we are to do this, I would only do it for routed as it's the only case in which we can be sure the host is on the same network as the guest. For macvlan/ipvlan, the instance could be in a different VLAN with no guarantee that the host has any reach to it.

Will re-title to match.
