### ISSUE TITLE
Unable to install httpd in fedora 22 unprivileged container

### ISSUE THREAD

**Issue by unikmhz** [lxc/lxd#955]
There is some trouble when combining Fedora 22 and LXD. When trying to install httpd I get this:
```
dnf install httpd
[...]
Running transaction
  Installing  : httpd-2.4.16-1.fc22.x86_64                                                                                                                                                                                               1/1 
Error unpacking rpm package httpd-2.4.16-1.fc22.x86_64
error: unpacking of archive failed on file /usr/sbin/suexec;55bfd703: cpio: cap_set_file
httpd-2.4.16-1.fc22.x86_64 was supposed to be installed but is not!
[...]
```
I found out later that this is an incompatibility between certain file capabilities and running unprivileged containers. But no fix/workaround was in sight.

Info:
* Distro: Ubuntu 14.04
* Kernel: 3.19.0-25-generic (from vivid lts backports)
* LXC: 1.1.2 (from stable PPA)
* LXD: 0.14 (from stable PPA)
* LXD storage: LVM thin pool (lvm2 package from some backports PPA, needed for lvcreate -k flag)

Applied profile:
```
name: default
config:
  limits.memory: 4G
  raw.lxc: |
    lxc.cgroup.cpu.shares = 1024
    lxc.cgroup.blkio.weight = 500
    lxc.pts = 1024
    lxc.tty = 4
devices:
  eth0:
    nictype: bridged
    parent: br.lxc
    type: nic
```
Can you please hint at what I need to do next to at least work around the issue?
Thanks.

**Comment by stgraber** [comment]
So it's actually a Linux kernel security limitation which is blocking you there, there's unfortunately nothing that LXD can do about this :(

The right way to fix this would be to have fedora's package manager use a fallback method such as setuid in those cases and possibly not fail so dramatically.

The only workaround I can offer is to create the container as a privileged container (create a profile with security.privileged set to 1 and create a container with it) but that container will not be very trustable so you should restrict root access to it to only people you'd trust with root access to the host.

As there's unfortunately nothing we can do about this in LXD, I'm going to close this issue.
