### ISSUE TITLE
Snapshot schedule list not working

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#9553]
# Required information

```
$ snap list lxd
Name  Version  Rev    Tracking       Publisher   Notes
lxd   4.20     21902  latest/stable  canonical✓  -
```
# Issue description

Specifying more than one schedule alias doesn't work.

# Steps to reproduce

```
lxc profile set default snapshots.schedule '@daily,@startup'
```

The above should work according to the documentation but it errors out with:

```
Error: Schedule must be of the form: <minute> <hour> <day-of-month> <month> <day-of-week>
```

**Comment by stgraber** [comment]
Fixed already in the PR I opened :)

For now, if you use `, ` as separator instead of `,` it will work.
