### ISSUE TITLE
Lxc copy to remote ignores profile

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#9554]
LXD v. 4.20
Profiles:
source server: pl1
target trusted server: pl2

`lxc copy container -p pl2 --stateless --project x targetserver:`

> Error: Failed instance creation: Requested profile ‘pl1’ doesn’t exist

Expected behavior:
 lxc copy [<remote>:]<source>[/<snapshot>] [[<remote>:]<destination>] [flags]
Flags:
  -p, --profile          Profile to apply to the new instance

passing -p as flag works when instance is copied locally:
We have a container c1 with profile p1

```
Local:
lxc copy c1 c2 -p p2
creates a new container with profile p2.
```
```
Remote:
Same command for copying a local container to a remote host dosent work:
lxc copy c1 -p p2 targetserver:
> Error: Failed instance creation: Requested profile ‘p1’ doesn’t exist
```
It tries to create a container at remote by using it's original profile p1 rather applying the profile p2 passed as flag.

Perhaps passing a different profile as -c would work, hasnt try yet:
  -c, --config           Config key/value to apply to the new instance

Another error is reported when passing the flag -p at container local copy, where the profile is same as old profile:
lxc copy c1 c2 -p pl
Error: Failed creating instance record: Duplicate profile found in request

**Comment by tomponline** [comment]
Please can you clarify what the expected behaviour is? Thanks

**Comment by stgraber** [comment]
Sounds like the issue here is that we're appending with `-p blah` instead of replacing the entire set of profiles as happens on init/launch. I think it'd make sense to line up behavior and so we should make sure that when passed, `-p` replaces any existing profile on the instance.
