### ISSUE TITLE
API get Instance with more in-depth information

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#9555]
LXD v. 4.20

Whilst
`GET /1.0/instances?recursion=2`
delivers very detailed information including recursion 2 of networks/snapshots/backups…

`GET /1.0/instances/containerx?recursion=2`
is a bit sparse.

Fetching a single container out of GET /1.0/instances?recursion=2 output rather inconvenient, due to size of output in case numerous containers inside project.

It would be easier, getting same output for  a single instance when GET /1.0/instances/containerx?recursion=2
than querying like this:
```
GET /1.0/instances/containerx?recursion=2
GET /1.0/instances/containerx/state?recursion=2
GET /1.0/instances/containerx/snapshots?recursion=2
GET /1.0/instances/containerx/backups?recursion=2
```
to get same result.

**Comment by presztak** [comment]
@stgraber If this is not problem I can work on this as well.

**Comment by stgraber** [comment]
Yep!
