### ISSUE TITLE
Running VM snapshot on dir pool copies config.mount incorrectly

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9557]
Snapshotting running VM on `dir` storage pool causes the snapshot to be unusable due to copying the `config.mount` directory, thus preventing starting of the VM when restored/copied to a new instance.

Reported by @brauner

**Comment by stgraber** [comment]
@tomponline as you mentioned elsewhere, moving the mount point to the devices directory should avoid this issue.

**Comment by tomponline** [comment]
@stgraber excellent will do thanks.
