### ISSUE TITLE
Security docs have broken/missing link to anchor in RBAC sub-heading

### ISSUE THREAD

**Issue by sparkiegeek** [lxc/lxd#9566]
# Required information
Issue in [the security docs](https://linuxcontainers.org/lxd/docs/master/security), sourced from [security.md](../tree/master/doc/security.md)

Firefox 94.0
# Issue description

The Security docs, along with other LXD documentation has an inline Table of Contents linking to sub-sections via the headers.

Clicking the `Role Based Access Control (RBAC)` header does not jump the viewport to the associated header.

Notably the link is to [#role-based-access-control-rbac](https://linuxcontainers.org/lxd/docs/master/security#role-based-access-control-rbac) but the anchor includes the parentheses `<a class="anchor" href="#role-based-access-control-(rbac)"></a>`.

Manually adjusting the URL to include the parentheses jumps the viewport as expected.

**Comment by ru-fu** [comment]
This is unfortunately a known issue in the tool we're using to build the documentation. We're currently looking into other means of building the docs, which will fix the issue.

**Comment by sparkiegeek** [comment]
> This is unfortunately a known issue in the tool we're using to build the documentation. 

Ah, ok - could you link to it here?

> We're currently looking into other means of building the docs, which will fix the issue.

Ack. Thanks - could we consider retitling the section in the meantime?

**Comment by stgraber** [comment]
Right, it's a documentation builder bug, not something that we can change from our side easily and considering we're transitioning to Sphinx right now, it's not really worth changing the doc just for a few days.

**Comment by stgraber** [comment]
This has been sorted out now.
