### ISSUE TITLE
Disk device with a custom volume source should refuse to accept shift option

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9584]
Current the setting is ignored because custom volumes can be used by multiple instances and we don't want some to use shift and some not. But this is confusing.

**Comment by stgraber** [comment]
Check should be that if a disk entry has `pool` set, then `shift` should not be allowed to be set.

**Comment by markylaing** [comment]
> rrent the setting is ignored because custom volumes can be use

I think I'm probably missing something but it looks like this check is already performed? https://github.com/lxc/lxd/blob/master/lxd/device/disk.go#L254

**Comment by tomponline** [comment]
Indeed. @brauner when you said in IRC "that shift=true currently doesn't work with custom storage volumes" do you have a reproducer of how you managed to specify it? Thanks

**Comment by stgraber** [comment]
Indeed looks like it's already handled. I suspect we ought to tweak that error a tiny bit and suggest `security.shifted=true` on the volume?
