### ISSUE TITLE
Clarify `LOOPDEV` in btrfs resize documentation

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#9596]
Hi there,

I stumbled over https://github.com/lxc/lxd/blob/master/doc/storage.md#growing-a-loop-backed-btrfs-pool

```
sudo truncate -s +5G /var/lib/lxd/disks/<POOL>.img
sudo losetup -c <LOOPDEV>
sudo btrfs filesystem resize max /var/lib/lxd/storage-pools/<POOL>/
```

Could we add some explanation of what this LOOPDEV is?

`lxc storage list` displays the <POOL>.img but not the LOOPDEV.

Best,
Sven

**Comment by stgraber** [comment]
It's whatever is listed for your `.img` in `losetup -a`
