### ISSUE TITLE
Add more memory information

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#9608]
The `/1.0/resources` endpoint reveals a lot of information about the hardware, would it be possible to extend the `memory` details with the "version" (I.E "ddr4" / "ddr3") and the clock speed?

Feels abit empty without it;
![Screenshot from 2021-12-01 17-46-25](https://user-images.githubusercontent.com/12494629/144286372-5a2d15d2-c630-473c-b3ed-4afa20923374.png)

**Comment by stgraber** [comment]
I don't think that's possible. For the resources API we can only rely on things available in /sys, in this case:
 - /sys/devices/system/node
 - /sys/devices/system/memory

The memory type and clock speed isn't something that's directly known by the Linux kernel (or at least not exposed to userspace). On some platforms (those with suitable ACPI tables), you can pull that information through DMI but this won't work on architectures without ACPI and either requires calling out to `dmidecode` or implementing a binary parser to make sense of the raw DMI tables exposed by the kernel.
