### ISSUE TITLE
README links not working

### ISSUE THREAD

**Issue by dillonsamra9** [lxc/lxd#9623]
Documentation issue: After moving the installing.md to /docs, the link in README.md appears to have not been updated. I see where this happened with the link to contributing.md and security.md there are "symbolic link" files in the main directory for them, but for installing.md, when I click on the "Installing LXD" link under the "Installing LXD from packages" section of README.md, I am taken to a 404 not found page.

I would be happy to make the quick fix of either also adding a symbolic link for installing.md in the main directory, or updating all of the broken links in README.md to include docs/<file>.md in the path.

**Comment by stgraber** [comment]
Currently it's really recommended to view the docs through https://linuxcontainers.org/lxd/docs/master/ which won't have that problem.

We're in the middle of a transition to a new tool to generate the docs and in this case, we can either have README.md functional on Github or have the resulting page functional on the documentation...

Moving forward the plan I believe is to separate doc/index.md and README.md to be two separate pages and avoid such issues entirely.

@ru-fu

**Comment by ru-fu** [comment]
> Moving forward the plan I believe is to separate doc/index.md and README.md to be two separate pages and avoid such issues entirely.

Yes, https://github.com/lxc/lxd/pull/9588 will fix this issue. But it will not work with our current doc tool, so we need to wait with merging that one.
