### ISSUE TITLE
Typo in doc/api/extensions.md

### ISSUE THREAD

**Issue by dillonsamra9** [lxc/lxd#9651]
While working on [9518](https://github.com/lxc/lxd/issues/9518) I saw a typo in the gpu_mig section: 
"This adds support for NVIDIA MIG. It introduces the mig gputype and **_associaetd_** config keys."

**Comment by stgraber** [comment]
Oh oops, want to send a PR to fix it?

**Comment by dillonsamra9** [comment]
Yeah I'll take care of it
