### ISSUE TITLE
Links from README.md to installing.md, security.md and contributing.md are broken when viewed from github

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9665]
Since our `README.md` file became a symlink to `doc/readme.md` the relative links to `installing.md`, `security.md` and `contributing.md` are broken when viewed from the homepage at https://github.com/lxc/lxd.

This is because, whilst github respects the symlink for `README.md` -> `doc/readme.md` for viewing the file, it doesn't respect the links in it to, say, `installing.md` which instead just presents a blank page with the text "doc/installing.md" (non clickable).

This is very confusing for new and existing users alike.

Related to https://github.com/lxc/lxd/pull/9624 and https://github.com/lxc/lxd/issues/9623

**Comment by ru-fu** [comment]
The only thing that has changed is the added link to installing.md - the other two links have been there for a while and they always linked to the redirect (thus: did not work).

This is an issue, of course, but it will be fixed with https://github.com/lxc/lxd/pull/9588 once we move to the new doc system.

**Comment by tomponline** [comment]
Odd, I've used those links in the past and they worked, do you know when they got broken by any chance?

Can we merge just this part https://github.com/lxc/lxd/pull/9588/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 early so we don't knowingly leave our homepage in a broken state?

**Comment by ru-fu** [comment]
> Odd, I've used those links in the past and they worked, do you know when they got broken by any chance?

The readme redirect was added 4 years ago, so I would assume it's been a while. ;)
The links work if you are in the doc folder, however. So if you check the history it will look like they worked - until you go to the root folder of the repo at that time.

> Can we merge just this part https://github.com/lxc/lxd/pull/9588/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 early so we don't knowingly leave our homepage in a broken state?

Not sure which part you mean, the link just shows the full commit for me?
I don't think we can merge part of it without breaking our documentation. :(

**Comment by tomponline** [comment]
> The readme redirect was added 4 years ago, so I would assume it's been a while. ;)

Oh wow, thats not good! :( I must have just used the installing.md link which worked until recently.



> Not sure which part you mean, the link just shows the full commit for me?

Ah I thought the link would take you to the specific page in that commit, basically can we just merge the new standalone README.md and contributing.md, do they depend on sphinx?

**Comment by ru-fu** [comment]
> Ah I thought the link would take you to the specific page in that commit, basically can we just merge the new standalone README.md and contributing.md, do they depend on sphinx?

They don't, but it would mean duplicating them, since we cannot reuse the content in the docs. So we would have the same files in two locations.
Then we can also just copy installing.md, security.md and contributing.md to the root folder instead of having a symbolic link.

**Comment by tomponline** [comment]
Sounds good. But I am a bit confused, isn't your PR https://github.com/lxc/lxd/pull/9588 proposing to do that already (move the content back to their own files in root rather than "docs")? Is it just that the includes won't work on the equivalent doc/ page until we move to sphinx?

**Comment by ru-fu** [comment]
The idea of the PR is to move the content that we need in the GitHub root folder (namely README.md and contributing.md) to the GitHub root folder, and include the content that we also want in the docs from those files (single source). And we cannot do the single-source part without Sphinx.

**Comment by tomponline** [comment]
OK that makes sense, and sounds great.

But given that the github repo home page is in many ways our "store front" (for want of a better phrase) it would seem to me to be preferential to have some short-term duplication (until sphinx can be deployed to remove that duplication) rather than have broken links on the github repo home page.

What do you think @ru-fu and @stgraber ?

**Comment by stgraber** [comment]
@tomponline we're days away from the cut over to Sphinx

**Comment by tomponline** [comment]
This is fixed now, thanks @ru-fu
