### ISSUE TITLE
Installing from source / development setup issues

### ISSUE THREAD

**Issue by markylaing** [lxc/lxd#9666]
I encountered a few problems with setting up a development environment. I may have missed things in the documentation however, so I'll put the issues here for discussion around where/what we can improve.

# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 20.04.3 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.11.0-41-generic
   * LXC version: 4.0.6-0ubuntu1~20.04.1
   * LXD version: N/A
   * Storage backend in use: btrfs

# Issue description

1. `dnsmasq` failed to start up when running a local build of `lxd` for the first time. This was because port 53 being used by `systemd-resolved`.
2. The `uidmap` package should not be installed.
3. Some packages must be legacy versions: `iptables`, `ip6tables`, `ebtables`.
4. It's not possible to run lxd from an integrated terminal (say vscode) because apparmor doesn't allow it (you can check this by grepping dmesg).

It might be useful for new contributors to have a development set up guide which helps get you started. More experienced developers can use as much or as little as they like. 

# Steps to reproduce

Follow the [installing from source](https://linuxcontainers.org/lxd/docs/master/installing) documentation.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
@ru-fu might know such improvements to a development setup guide would go?

**Comment by ru-fu** [comment]
> @ru-fu might know where such improvements to a development setup guide would go?

Anything that is wrong or missing in the [Installing LXD](https://linuxcontainers.org/lxd/docs/master/installing) documentation should be fixed there.
If we need a more comprehensive "here's how to get started" guide for new developers, it should go in the Getting started section, either as a new guide or as an extension/cleanup to [Getting Started Developing](https://linuxcontainers.org/lxd/docs/master/contributing#getting-started-developing).

**Comment by tomponline** [comment]
Sounds good @ru-fu thanks

**Comment by markylaing** [comment]
> 1. I'm confused, we say to install `dnsmasq-base` which does not come with the `dnsmasq` service for this very reason, how did you end up with the full `dnsmasq` package?
> 2. We don't seem to be asking for it to be installed anymore?
> 3. For those, as I mentioned in our 1:1, I'd prefer that we have our testsuite detect the nft wrappers and skip them automatically
> 4. Was that with the snap version of vscode or with the deb version of vscode? I'd suspect this is an issue that's specific to the snap version of vscode

1. I may have installed `dnsmasq` while trying to resolve the the issue but `dnsmasq` wasn't using port 53, that was `systemd-resolved`. I had to turn off the [DNS stub listener](https://www.freedesktop.org/software/systemd/man/resolved.conf.html#DNSStubListener=).
2. I didn't knowingly install `uidmap`. Do you think it would be useful to add a note for new contributors (say under https://github.com/lxc/lxd/blob/master/doc/contributing.md?plain=1#L124) to mention that the package is incompatible?
3. That sounds good.
4. Yep it's the snap version.

**Comment by stgraber** [comment]
1) That's odd. LXD's use of dnsmasq is designed to work with the systemd stub resolver on localhost otherwise we'd hit this problem on every single system where LXD would get installed. LXD itself never binds localhost, it runs its dnsmasq processes only on the bridge interfaces it creates.

2) We shouldn't recommend removing it as that may actually break other software. Instead we should say that if the newuidmap/newgidmap tools are present on the system and that /etc/subuid and /etc/subgid exist, that we need them configured to allow the root user a contiguous range of at least 10M uid/gid.

**Comment by tomponline** [comment]
> 2\. We shouldn't recommend removing it as that may actually break other software. Instead we should say that if the newuidmap/newgidmap tools are present on the system and that /etc/subuid and /etc/subgid exist, that we need them configured to allow the root user a contiguous range of at least 10M uid/gid.

This can be added to this section https://github.com/lxc/lxd/blob/master/doc/installing.md#machine-setup as an extension of https://github.com/lxc/lxd/pull/9601

**Comment by stgraber** [comment]
With the caveat that this does not apply to snap users as we completely ignore subuid on those systems. So it's limited to those installing from source and to some other distros.

**Comment by tomponline** [comment]
> 

Yeah that whole section doesn't apply to snap users, so worth adding that.
