### ISSUE TITLE
btrfs ContainerCopy should always create a subvolume for the copy

### ISSUE THREAD

**Issue by mikemccracken** [lxc/lxd#967]
If the btrfs driver is being used (so $LXDDIR is IN a subvolume), but the source of a copy is not itself a subvolume (perhaps because the source was created before setting up the btrfs directory, then storageBtrfs.ContainerCopy() falls back to making an rsync copy of the source into a new non-btrfs plain dir.

Falling back to copying, and not attempting to convert the source is correct, but since in this case we can create a new subvolume for the copy, we should do so.

**Comment by mikemccracken** [comment]
@pcdummy are you interested in working on this?

**Comment by pcdummy** [comment]
Will do mike :+1:
