### ISSUE TITLE
Containers with routed IPv4 addresses no longer able to forward traffic in 4.21 candidate

### ISSUE THREAD

**Issue by tim-seoss** [lxc/lxd#9678]
# Required information

 * Distribution: Debian
 * Distribution version: 11 
 * The output of "lxc info":
 
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 172.19.32.2:8443
  - '[2001:xxxx:xxxx:32::x]:8443'
  - 172.19.198.14:8443
  - '[2001:xxxx:xxxxx::x]:8443'
  - 172.18.254.14:8443
  - 172.18.255.250:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICETCCAZagAwIBAgIRAJhm3cg4rK0NDOopfMQhJ9UwCgYIKoZIzj0EAwMwODEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEYMBYGA1UEAwwPcm9vdEByb3Vu
    ZGFib3V0MB4XDTIwMDcxNDE2MjExNVoXDTMwMDcxMjE2MjExNVowODEcMBoGA1UE
    ChMTbGludXhjb250YWluZXJzLm9yZzEYMBYGA1UEAwwPcm9vdEByb3VuZGFib3V0
    MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEXkE+7940P1h2P4DB6DcxZWFwqjCzK+BA
    5OI2ZbDhMBptS8WFlHNvR9AhPqQ4HOcLtxoiZZ28PB2pT9nvDD2WZw9rOlwEV6iK
    FMGBCu5GhEWchhvxlMV0cQCqzf+S50O3o2QwYjAOBgNVHQ8BAf8EBAMCBaAwEwYD
    VR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAtBgNVHREEJjAkggpyb3Vu
    ZGFib3V0hwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMDA2kAMGYC
    MQDO7ORDnsIgLNrPJrJwTTINp4bfIjQl0Qgq2Wcyx8gKeYQ1Kh9yppJWZslWLdLx
    HDACMQCG8Bl4rNGXFWfoyQR4jbPsM9sCfZr9bqECEjV3TzFsgQi+ApWhsziRRT7W
    V0w8OSk=
    -----END CERTIFICATE-----
  certificate_fingerprint: 43d88ef13eaea6855b2e2831860086c0171c873a5290adea16a3a9bd93027275
  driver: lxc | qemu
  driver_version: 4.0.11 | 6.1.0
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.10.0-9-amd64
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Debian GNU/Linux
  os_version: "11"
  project: default
  server: lxd
  server_clustered: false
  server_name: roundabout
  server_pid: 3814
  server_version: "4.21"
  storage: dir
  storage_version: "1"
  storage_supported_drivers:
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.07(2) (2019-11-30) / 1.02.167 (2019-11-30) / 4.43.0
    remote: false
  - name: ceph
    version: 15.2.14
    remote: true
  - name: btrfs
    version: 5.4.1
    remote: false
  - name: cephfs
    version: 15.2.14
    remote: true

# Issue description

Following a recent upgrade to a candidate build, containers which have routed IPv4 addresses, e.g. the following:
```
devices:
  ethPub:
    host_name: ethPubPostbox
    ipv4.address: 172.19.32.26
    ipv6.address: 2001:xxxx:xxxx:32::26
    name: ethPub
    nictype: routed
    parent: vlan10
    type: nic
```

... have lost IPv4 connectivity (except for traffic to/from the lxd server itself).  Running the following on the lxd server restores connectivity:

    sysctl -w net.ipv4.conf.ethPubPostbox.forwarding=1

IPv6 connectivity is still OK.

```
root@roundabout:~# lxc info postbox --show-log
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Name: postbox
Status: RUNNING
Type: container
Architecture: x86_64
PID: 11012
Created: 2021/02/23 09:00 GMT
Last Used: 2021/12/11 11:04 GMT

Resources:
  Processes: 57
  Disk usage:
    root: 1.79GiB
  CPU usage:
    CPU usage (in seconds): 20
  Memory usage:
    Memory (current): 1.35GiB
  Network usage:
    ethPub:
      Type: broadcast
      State: UP
      Host interface: ethPubPostbox
      MAC address: 00:16:3e:ad:22:d2
      MTU: 1500
      Bytes received: 16.52kB
      Bytes sent: 8.45kB
      Packets received: 86
      Packets sent: 87
      IP addresses:
        inet:  172.19.32.26/32 (global)
        inet6: 2001:xxxx:xxxx:32::26/128 (global)
        inet6: fe80::216:3eff:fead:22d2/64 (link)
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)

Log:

lxc postbox 20211211110433.824 ERROR    cgroup2_devices - cgroups/cgroup2_devices.c:bpf_program_load_kernel:332 - Operation not permitted - Failed to load bpf program: (null)
lxc postbox 20211211110433.840 WARN     conf - conf.c:lxc_map_ids:3579 - newuidmap binary is missing
lxc postbox 20211211110433.840 WARN     conf - conf.c:lxc_map_ids:3585 - newgidmap binary is missing
lxc postbox 20211211110433.841 WARN     conf - conf.c:lxc_map_ids:3579 - newuidmap binary is missing
lxc postbox 20211211110433.841 WARN     conf - conf.c:lxc_map_ids:3585 - newgidmap binary is missing
```

**Comment by tomponline** [comment]
Thanks for testing this. I believe this may be related to the move sway from liblxc's router implementation (needed to support routed nics with vms) and some differences between the minimum sysctls needed for ipv4 vs ipv6 functionality.
