### ISSUE TITLE
Ignore project information other than project.default in metrics

### ISSUE THREAD

**Issue by xehrad** [lxc/lxd#9679]
# Required information

 * Distribution: Ubuntu
 * Distribution version:  20.04
 * LXC version: 4.20
 * LXD version: 4.20

# Issue description

When I try to get lxc metrics from **/1.0/metrics**, the result contains only **project.default** information, there is no other **project**.

**Comment by stgraber** [comment]
I'm unable to reproduce this, here I'm definitely getting data over many many projects.

One thing that's worth noting is that the metrics API only returns information for running instances that are hosted on the server being queried, it will not show you entries for stopped instances and will not aggregate data across a cluster.

**Comment by xehrad** [comment]
thnx dear stephane

So how do I get specific project data?
For example, by adding the project name at the end of the endpointt: /1.0/metrics?**project=test**
Currently only **"project default"** metrics is available

**Comment by stgraber** [comment]
The metrics endpoint does not normally filter by project, it returns data for all running instances on the system.

If you have running instances on a system that don't show up in `lxc query /1.0/metrics` then look at the LXD log for error.

**Comment by xehrad** [comment]
oops, I misunderstood that the lxc cluster metric is received from one node of lxc, while
 **All nodes of cluster** must be define as targets for prometheus.
thnx dear stephane :)
