### ISSUE TITLE
fuidshift binary accidentally included in source

### ISSUE THREAD

**Issue by gibmat** [lxc/lxd#9680]
The recent release of v4.21 appears to contain a pre-compiled fuidshift binary; looks like it was accidentally included in commit fbd6af0. (Noticed while updating my preliminary LXD packaging for Debian.)

**Comment by stgraber** [comment]
Doh, not sure how that happened (or was missed in review)...

**Comment by stgraber** [comment]
Sent a PR to remove it. The file wasn't at a usual location for a binary build, so wouldn't have been caught by .gitignore, I guess it must have been @ru-fu running a manual `go build` or similar combined with Github not making it super obvious when a binary file is included (just a one line entry in a diff...).

It's a bit unfortunate as that effectively grows the repo size by around 7MB indefinitely (at least for those not using shallow clones).

**Comment by ru-fu** [comment]
This is super weird, since I've never run any go builds, and I don't even have that file on my local branch. But then, I was also not the last one to force-push to that branch. ;)

**Comment by stgraber** [comment]
Hmm, you're right, it most likely was me who pushed that one then... Would also explain why we didn't see it in review if it happened during the merge...

Still no idea how I'd end up with the idmap tool at that location... None of our makefile entries do that.

I'll have to check if we can't put some check in place to flag commits growing the repo by more than a MB. If caught early enough I could have force pushed to get rid of it before anyone would have updated their local copies...

**Comment by tomponline** [comment]
Could we add to .gitignore too?

**Comment by stgraber** [comment]
That would make sense if we had something like a test or makefile that would build in that location but we don't.

**Comment by tomponline** [comment]
Yeah it shouldn't end up there normally. But was thinking we could add it there as protection anyway.

**Comment by stgraber** [comment]
I guess we can do it for all commands.
