### ISSUE TITLE
Add progress indicator for 'lxc export' command

### ISSUE THREAD

**Issue by pajot** [lxc/lxd#9711]
The `lxc export` command runs silently even as it performs multiple background tasks.

Exports can sometimes take hours. Having a progress indicator is particularly important in cases such as this in order to detect hangs and not waste time.

Currently, the only feedback provided by the command is a completion message such as

`Backup exported successfully!`

**Comment by presztak** [comment]
@stgraber Can I work on this one?

**Comment by stgraber** [comment]
For sure!

I'm not sure where the problem is exactly, I suspect it's either on the client side that we didn't plumb the operation logic to show progress or on the server side that something isn't passing the operation all the way through to the storage layer.
