### ISSUE TITLE
Forwarded lifecycle events are not filtered by project

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9718]
As part of my work on implementing event hub member role I was researching how LXD propagates event project info (given that the `api.Event` type that is relayed doesn't contain a `project` field). **It turns out it doesn't**, and a local event lifecycle event that has project info will have it stripped when forwarded to other cluster members, causing the lifecycle event to appear in all listeners' streams.

Reproducer:

On member-a:
```
lxc project create test
lxc project switch test
lxc monitor --type=lifecycle
```

On member-b:
```
lxc project switch default
lxc init images:ubuntu/focal c1 --target member-b
```

Expected:
No lifecycle event appears in the `lxc monitor` output event on member A (as its listening in project test).

Actual:
Lifecycle event should not appear as it should be filtered by project.

I've tracked the issue down to this function:

https://github.com/lxc/lxd/blob/master/lxd/events/events.go#L113

Where it accepts a forwarded event (by this point the project info has already been stripped because the event forwarding mechanism has no support for it) and this function then re-injects the event into the local event stream without a group so it is delivered to all listeners.

In addition to that, there is a problem in the `client` package that connects to a LXD server to register a new event listener connection.

https://github.com/lxc/lxd/blob/master/client/lxd_events.go#L29-L42

The problem is that if the same client calls `getEvents()` with a different argument value of `allProjects`, only the first request will actually open a new connection to the server with the requested mode, subsequent requests will re-use the connection. So if the first request specified all project events, and the subsequent call specified only the current project, then it would still receive events from all projects.

**Comment by tomponline** [comment]
There's 2 issues here that are interconnected:

1. Project filtering is done at the server, whereas the rest of the event filter (types) is done on the client.
2. Event stream connections are re-used by the client despite different project filtering preferences.

The event hubs will expect to relay events for all projects, so will not require server-side filtering of events by project, but will need to have the project info stored in the event (or an envelope) so it can re-inject the event with the correct project info.

In addition to that the LXD client should either open a connection per requested projected (and all projects) rather than sharing them, or implement a way to setup additional server-side subscriptions for particular projects, and have events delivered containing the project info so they can be delivered to the correct event listener target.

**Comment by tomponline** [comment]
The simplest way to solve this is to add a `Project` field to the `api.Event` struct (or perhaps `Group` as the rest of the event system seems to reference group rather than project, even though project is what is stored in group. Perhaps we should also take this opportunity to replace "group" references with "project" in the code as well).

As well as allowing project info in an event to be relayed between servers, it would also allow the client's `getEvents` function to be clever about filtering events by specific projects if it had initially started an all-projects listener, and subsequently was called again for another specific project. The client could filter the events locally for that specific listener target.

**Comment by tomponline** [comment]
The other possible approach (if adding new fields to the `api.Event` is undesirable) is to add a intra-cluster event relay route on the `/internal` URL prefix using an internal event struct that contains the new field, for use with forwarding events between cluster members.

**Comment by tomponline** [comment]
@stgraber would you have any problem with adding a `Project` (or `Group`?) field to the `api.Event` struct?

**Comment by stgraber** [comment]
@tomponline I think a `Project string` field would make sense given that we support `?project=XYZ` as well as `all-projects=true` on the endpoint.

**Comment by tomponline** [comment]
Making a start on this.
