### ISSUE TITLE
Adding multiple bridged NICs connected to same managed network breaks static IP allocation

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9719]
If you have a managed LXD network, say `lxdbr0` that provides DHCP and SLAAC functionality to the network.

Then add 2 NICs to the instance both connected to the same network, e.g.

```
lxc config device add c1 eth0 network=lxdbr0 ipv4.address=192.168.1.2
lxc config device add c2 eth1 network=lxdbr0
```

Adding the 2nd NIC will wipe out the static IP allocation in dnsmasq of the first NIC.

This is a plausible configuration as when using nesting (or VM with containers) you may want to pass into additional NICs connected to the same network to be subsequently used inside another container or as an OVN uplink network (without having IPs configured in the outer instance).

This problem occurs because the dnsmasq host config file LXD generates expects 1 file containing 1 line per instance, but really we need to have that per-instance file support 1 line per NIC.

**Comment by stgraber** [comment]
I think we can sort that one by renaming the `dnsmasq.hosts` file to be `<instance>.<device>` rather than just `<instance>`

**Comment by tomponline** [comment]
And deal with deleting the old dnsmasq.hosts `<instance>` file.

**Comment by stgraber** [comment]
Yeah, we'll likely need a patch to do a one time transition. And will need to make sure that we clear the right files when a device is deleted (or changed to not be relevant) as well as when the instance itself is deleted.
