### ISSUE TITLE
Unvendor usbid library

### ISSUE THREAD

**Issue by gibmat** [lxc/lxd#9727]
# Issue description
While continuing to work on the LXD package for Debian, I noticed that the usbid library in `shared/` is a subset of the github.com/google/gousb library. Reviewing the git history for LXD, it looks like the only significant change is tweaking the loading of USB IDs from the library-supplied database to looking for a system-level database file.

Would it be possible to switch to using the upstream gousb library, or are the USB ID mappings it ships with too old? (Or maybe there was some other reason at the time which isn't apparent to me.) It's a pretty easy change to update `lxd/resources/usb.go` to use the upstream library directly.

**Comment by stgraber** [comment]
Just looked into that one again now and it looks like it was a mix of things that caused us to go down the route of having a much smaller version of this logic and have it limited to just parsing the distro provided usb info:
 - Upstream version imports the main `gousb` package, this package uses `libusb` and so imports `C` and uses cgo. The `lxd/resources` package is used externally by tools which must be static, so we don't allow any dependencies of `lxd/resources` to contain code requiring cgo.
 - The upstream usbid package parses the entire database on module init. This is fine for most tools using their logic, but for us, it's problematic as the `lxd` binary serves many different roles (based on subcommand) and the high CPU and memory footprint of parsing and expanding the entire USB database every time was bad enough to show up in our performance tests.
 - We want our users to get the same output in `lsusb` and through the LXD resources API as that's generally what we'll have them run whenever we need additional data. Having both run from different databases is problematic.

So this is really a minimal version of that upstream usbid package and one we may wind up trimming down further as needed. It's intended to parse the distro USB id database and give us data for each vendor and product as well as USB class names. Everything else we don't care about and can rip out of it (and diffing the upstream package, largely did).

**Comment by stgraber** [comment]
So I don't think we'll be fixing this one as it's not a vendored tree so much as a fork+minimalized version to satisfy our needs as far as memory footprint, load time and avoiding cgo use. I'll add a README.md in that fork to explain that and close the issue as a result.

**Comment by gibmat** [comment]
Thanks for that explanation -- seems reasonable to me! :+1:
