### ISSUE TITLE
 lxc image copy --auto-update  overrides --public

### ISSUE THREAD

**Issue by hadmut** [lxc/lxd#9730]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:

config:
  core.https_address: :8443
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.164.144:8443
  - '[fdfc:8e00:2464:1:201:c0ff:fe21:3400]:8443'
  - '[2a02:8109:98c0:3c0:201:c0ff:fe21:3400]:8443'
  - 172.20.0.1:8443
  - 172.19.0.1:8443
  - 172.18.0.1:8443
  - 172.17.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFZzCCA0+gAwIBAgIQOSiDDEGR4LfgpSvDUt4UhTANBgkqhkiG9w0BAQsFADAz
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRMwEQYDVQQDDApyb290QG1p
    bmkzMB4XDTE4MTAxMDE5MzY1NFoXDTI4MTAwNzE5MzY1NFowMzEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBtaW5pMzCCAiIwDQYJ
    KoZIhvcNAQEBBQADggIPADCCAgoCggIBAN4Ak1jAOkDGbJxXhpeEfjUis9AzaGVu
    cyH9fD6i3AypDVlACWJYqZpe4vWlWMw6nLtFud43Nw7yVGvoD5ab9BQTyTkWVzxd
    FQjvJ5NIPZ7HTJmcFb5KG6yrhgUNE2TYPMsj25H7QdweIl9cnP/+opoMz4sprn9W
    TW8wQ8iHsT6iVZiQdlc8drmAoebBdyWcggHc6LLnGUKw0A8rEVIWPGxm6VHorf68
    Q6oZ2EA6WsjwW4Wp0K6YIDRJwE7GR6fhMesfdT0VddiGcw1c5NkR/szeb56cOiS+
    AAUy8nXwyQR/oH1wCd3HGL+VIYddLXMxtv+Neu6iMV+UuH+jhO3T+xDXEv/o7SRl
    Xp+WyAKfXEgOAVWmQrFw8bbXtMv2Wo6qq3ppp/HErz4MeEEcvLaNNJW3FYjidJxA
    0ncTFOVWbtuspgG1JYGl+lucHOU+pPC/L0XWhnnomODJiea0iqCnmwxqaS/iu5s8
    eGUBFePzckM5bRxO6CG+k5J0fg6Nv+dSpMYF6QuVU9BLXsaCK1xtfArDxYDTnzV6
    eDffJDuGzShU23UMC9EmzeUOGVlVm0LH1GVdIvd9vZUt2gqX2Xtpv364nF4SbRsJ
    ByznHP9S3itbxvJz5ZzQVQrYN8wnkCwoRmJdS2UO3EbxWUmLL08deGkMAd96sVoc
    t+SomS76cStNAgMBAAGjdzB1MA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMEAGA1UdEQQ5MDeCBW1pbmkzhwTAqKSchxD9
    /I4AJGQAAQIBwP/+ITQAhxAqAoEJmIAtwAIBwP/+ITQAhwSsEQABMA0GCSqGSIb3
    DQEBCwUAA4ICAQBfsbxwgqrr9GfaPkfy2B/9pm2wgkYQfHo5gSGo7qSZzC6qabWU
    awF2ItM5s22NVZjuRDQm5MA+MlIPfpptdaUHk76xcu+QprmHvKu0Lw/aGXNt1Pnp
    hoSIgYv0zxc4MS2z4x2xUrdFNeGd2xTlggLHvKd8JbfPo+GyRxkoHz89iwIWv2R+
    VefccAyjRiKiPv/FykHI/18VsEtE27LC3UWrHRIWzv2E6sxKZMy60+fLgCnst8Tz
    gXz1rjVqzDFTOq8UL+d/bTbP3c2L4BFnItBetGA5K/vOlvF6kWXCSNHdtAT4rsxD
    rwZCtwHLSsxlWg+3cWv3UwKha4rZW4c3Gzi7mpChSIrWb0UL3QGPUWhAjZnv/lMe
    WygR5YDvN5A+wm2RY5GdYhQB8kQUEBOcxr2VV4Jh32X8y/Pj0Ug6DQfmXi/GCWCg
    6vfiBTlnmMky/9h6ZnUavwGzHumBA640WjzduIBR+6beZW9xxttjItaBb1g/Fi+/
    TFAZ5x+w2BWP3JHky8pCrLBqy0svlrgeTS5JJmMW/dC3NC+HYvpwxv4l7DbQz8Gy
    U1hjE1F5dQnXuFR7YGIxY8nbQ/9gGgThZsg3Xp0dyaFnvA916mZ6LJwlznFNbDnK
    dWZbDrZgBdLAitbSBP2CuiW3KI3/qXQ2batrKLT/Xh2+2Z3EIaxz1UCUkw==
    -----END CERTIFICATE-----
  certificate_fingerprint: bb54e104142bb7254715d373ebc1f77ef072284070f19fbff7f438faf69f48d5
  driver: lxc | qemu
  driver_version: 4.0.11 | 6.2.0
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-91-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: mini3
  server_pid: 554359
  server_version: "4.21"
  storage: dir
  storage_version: "1"
  storage_supported_drivers:
  - name: btrfs
    version: 5.4.1
    remote: false
  - name: cephfs
    version: 15.2.14
    remote: true
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.07(2) (2019-11-30) / 1.02.167 (2019-11-30) / 4.41.0
    remote: false
  - name: zfs
    version: 0.8.3-1ubuntu12.13
    remote: false
  - name: ceph
    version: 15.2.14
    remote: true

# Issue description

I have a central lxd node which is supposed to be the only one to download LXD images over the internet and keep them up to date, and offer them to other machines in the same network as public images

Therefore, I do enter commands like

lxc image copy images:alpine/3.15 local: --copy-aliases --public --auto-update

which works like expected: Image downloaded and made public, offered to other machines. Works. 

But once an update is downloaded automatically, the "public" property is dropped, and thus the image is not available for other machines anymore. 

# Steps to reproduce

 1. lxc image copy images:alpine/3.15 local: --copy-aliases --public --auto-update
 2. check lxc image list to verify that the image is "public"
 3. wait for an auto-update to run
 4. check lxc image list again to see that the image is not "public" anymore

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by presztak** [comment]
@stgraber Can I try to fix this?

**Comment by stgraber** [comment]
Sure!
