### ISSUE TITLE
Add last modified dates on files API

### ISSUE THREAD

**Issue by Hye-Dev** [lxc/lxd#9738]
It would be great if we were able to get the last modified date in something like a header or in the body when requesting a file from the LXD API. Maybe something for the new file management in 5.0?

**Comment by stgraber** [comment]
Yeah, it will definitely be in the new websocket based file implementation as we expect to return enough `stat` info to satisfy a FUSE filesystem. As part of the switch to the new API internally, we should also be able to somewhat cheaply return it as a header on the old API.

**Comment by stgraber** [comment]
Assigning it to @tomponline to do as part of the new files API work.

**Comment by Hye-Dev** [comment]
I was looking at the new SFTP file code, and it looks like you added some useful information. I was wondering if we could also get information about directories using the new API?
