### ISSUE TITLE
Snapshot expiry datetime is returned differently to what is written

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9747]
When creating a snapshot the default expiry time is Go's zero date time (`0001-01-01 00:00:00+00:00`), however when read back from the database it is returned as a different time:

```
lxc storage volume create zfs vol1
lxc storage volume snapshot zfs vol snap0
```

Read back from database via LXD (via Go) show the expiry date as `0000-12-31T23:58:45-00:01` (this shows as in LMT timezone if inspected via logging the returned time.Time variable). Using `t.UTC()` will convert it to the correct `0001-01-01 00:00:00+00:00` value. So it looks like the timezone is being stored or retrieved incorrectly.

```
lxd sql global 'select * from storage_volumes_snapshots'
+-----+-------------------+-------+-------------+---------------------------+
| id  | storage_volume_id | name  | description |        expiry_date        |
+-----+-------------------+-------+-------------+---------------------------+
| 548 | 546               | snap0 |             | 0000-12-31T23:58:45-00:01 |
+-----+-------------------+-------+-------------+---------------------------+
```

Shutting down LXD and then consulting the offline readonly DB snapshot seems to suggest it is being stored correctly in the database:

```
sqlite3 /var/lib/lxd/database/global/db.bin
sqlite> select * from storage_volumes_snapshots;
548|546|snap0||0001-01-01 00:00:00+00:00
```

Furthermore when editing the snapshot volume, because the value returned to the user is different from what is apparently stored in the DB, the resulting value stored in the DB is different from the previous value.

Whoops, looks like `set` doesn't work for snapshots, will open another bug, separately.
```
lxc storage volume set zfs vol1/snap0 expires_at 0000-12-31T23:58:45-00:01
Error: not found
```

OK lets try another approach:

```
lxc storage volume edit zfs vol1/snap0
description: ""
expires_at: 0000-12-31T23:58:45-00:01
name: snap0
config: {}
content_type: filesystem
```

Exit without changing the value (but will result in the record being updated).

```
lxc storage volume show zfs vol1/snap0
description: ""
expires_at: 0000-12-31T23:58:15-00:01
name: snap0
config: {}
content_type: filesystem
```

Hrm, so the displayed expiry date is not the desired `0001-01-01 00:00:00+00:00`, nor `0000-12-31T23:58:45-00:01` that was previously displayed, but now its `0000-12-31T23:58:15-00:01`. Its moved back in time by 30s.

Lets try that again:

```
lxc storage volume edit zfs vol1/snap0
description: ""
expires_at: 0000-12-31T23:58:15-00:01
name: snap0
config: {}
content_type: filesystem
```

```
lxc storage volume show zfs vol1/snap0
description: ""
expires_at: 0000-12-31T23:57:45-00:01
name: snap0
config: {}
content_type: filesystem
```

Yep, its moved back by another 30s.

Whilst we're at it:

```
lxc storage volume get zfs vol1/snap0 expires_at
```

Yep thats broken too. Will include as part of the earlier additional bug report.

Right lets try something else, setting an expiry time manually via `lxc storage volume edit` to ``

That is displayed correctly:

```
lxc storage volume show zfs vol1/snap0
description: ""
expires_at: 2022-01-04T14:00:00Z
name: snap0
config: {}
content_type: filesystem
```

But now if I specify a Zulu time in the summer of GMT, e.g. 2022-08-04T14:00:00Z I get something different:

```
lxc storage volume show zfs vol1/snap0
description: ""
expires_at: 2022-08-04T15:00:00+01:00
name: snap0
config: {}
content_type: filesystem
```

Oh so now its been shifted in the future by 1 hour (presumably because although the time was provided in GMT, its being displayed in local BST time). This is confirmed by using `sqlite3` and it shows it stored as `2022-08-04 14:00:00+00:00`.

Interestingly, editing this and re-saving doesn't shift the time like it did with the zero time value, suggesting that the issue here is due to incompatibilities between DST in the timezones being used in dqlite or go.

**Comment by tomponline** [comment]
Tracked down the issue to go-dqlite:

https://github.com/canonical/go-dqlite/blob/4123028456df7f817eda59fa4f3672de725724a1/internal/protocol/message.go#L537-L550

Added some logging and we can see the zero time being retrieved from the database and then converted to local:

```
fmt.Printf("tomp %s %s %s\n", value, t.String(), t.In(time.Local))
```

```
tomp 0001-01-01 00:00:00+00:00 0001-01-01 00:00:00 +0000 UTC 0000-12-31 23:58:45 -0001 LMT
```

**Comment by tomponline** [comment]
Commit that introduced this broken behaviour:

https://github.com/canonical/go-dqlite/commit/34867b2d19d5ecba78e4b787a0f3030a08c01f16

**Comment by tomponline** [comment]
I think the issue here is that go-dqlite behaves like go-sqlite3 with the `?_loc=auto` connection argument passed, but only in the retrieval direction and not in the write direction (go-sqlite3 also always writes out timezone info and ignores `?_loc` setting since https://github.com/mattn/go-sqlite3/commit/7b0d180ce9aa2473631426dbc011e34b435d5c65).

However this results in datetimes being altered compared to what they were inputted.

I believe we should by default only use `time.ParseInLocation` with UTC and not attempt to convert to local time.
This way if a time has timezone info it will be returned as-is, and if not, will be treated as UTC.

https://github.com/mattn/go-sqlite3/blob/2b131e01c1cb65fbcbb56f7e73821a96ae661517/sqlite3.go#L2170-L2181

Then we could also implement the `_loc` connection string argument to support on-the-fly conversion of datetimes to the specified timezone or the system timezone.

What do you think @stgraber @MathieuBordere ?

**Comment by stgraber** [comment]
Yeah, treating things as UTC in the DB is probably safest. With dqlite, we could have a mix of systems across multiple timezones, so having things rely on the local timezone is quite dangerous.
