### ISSUE TITLE
Cannot use lxc storage volume set on snapshot volumes

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9748]
Should be possible to do `lxc storage volume set <pool> <volume>/<snapshot> expires_at <datetime>`

**Comment by stgraber** [comment]
That would be because `expires_at` is a property of a storage volume snapshot, not a config.
`lxc storage volume set` only updates key/value pairs within the `config` map.

**Comment by tomponline** [comment]
As discussed on IRC, we should detect if the volume is a snapshot and refuse to modify the config with an error saying snapshots are readonly. Rather than erroring with "not found" as it does currently.

**Comment by stgraber** [comment]
I've got that mostly implemented here
