### ISSUE TITLE
lxc storage volume get doesn't work

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9749]
`lxc storage volume get zfs vol1 name` or `lxc storage volume get zfs vol1/snap0 name` doesn't work.

But content is available via `lxc storage volume show`.

**Comment by stgraber** [comment]
Isn't that expected?

`lxc storage volume get` and `lxc storage volume set`, just like all our other get/set commands only considers the `config` map, it doesn't consider properties of the volume itself.

**Comment by tomponline** [comment]
Oh right, yes ofcourse, this is a special field not a config field. Yep my bad.
