### ISSUE TITLE
nvidia-smi does not show correct processes in a container

### ISSUE THREAD

**Issue by ywwynm** [lxc/lxd#9755]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-163-generic
   * LXC version: 3.0.3
   * LXD version: 3.0.3
   * Storage backend in use: zfs

# Issue description

`nvidia-smi` in one container does not show correct processes that are using GPU, whether these processes are from the same container or another one. But we can see the correct memory usage for every GPU.

For Docker, we can use Nvidia-Docker along with `--pid=host` to fix this in a Docker container. Do we have similar method to do it for lxd?

**Comment by stgraber** [comment]
pid=host effectively turns off the PID namespace in a Docker container, making it, not a container anymore.

This isn't an option for LXD as unprivileged containers absolutely need their own PID namespace or no process permission will work.

The issue as mentioned in the related thread on the nvidia-docker repo is a kernel one. The NVIDIA driver should be able to convert and filter the PIDs that it returns through SMI.

Until that happens, you're unfortunately out of luck...

**Comment by ywwynm** [comment]
@stgraber Thanks for the reply.

And to those who may be concerned about this problem, I find a way to retrieve the GPU usage information (especially about which container is using which GPU) from the container machine. There are 5 steps:

1. Execute `nvidia-smi` in a script(e.g. python).
2. Parse the results and get important information that you want, such as GPU memory usage, processes information, etc. An example script can be found in [nvidia-htop](https://github.com/peci1/nvidia-htop).
3. Get the PIDs, and for each of them, execute `cat /proc/$PID/cgroup` in the script. If the string "lxc" is contained in the output, we know that this process is a container process. Then, we can get the name of the container from the output.
4. If we also want to know the correlated PID in the container, we can execute 'cat /proc/$PID/status` and find the line that starts with 'NSpid:'. The last number of this line is the PID in the container.
5. To retrieve these information in a container, we can create a simple HTTP server in the host and provide a RESTful API for retrieving. Then in the container, we can access the API through a web browser or wget or curl.
