### ISSUE TITLE
Slow lxc copy

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxd#9761]
* Distribution: Ubuntu
 * Distribution version: 20.04
 * Kernel version: 5.4.0-91-generic
 * LXC version: 4.0.11
 * LXD version: 4.21
 * Storage backend in use: dir

# Issue description
`lxc copy` to remote node takes few times more time than common rsync. 
For ex.,
```
root@test:~# time lxc copy ct6269 yxzyBUDd:ct6269 --stateless

real	1m12.513s
user	0m0.266s
sys	0m0.122s
root@test:~# lxc stop ct6269
root@test:~# time lxc copy ct6269 yxzyBUDd:ct6269 --refresh

real	0m3.770s
user	0m0.381s
sys	0m0.073s
```

At the same time, rsync of same CT to same remote node takes almost 2.5 times less time
```
root@test:~# time rsync -a /var/lib/lxd/storage-pools/default/containers/ct6269 10.10.10.11:/root/

real	0m31.216s
user	0m22.719s
sys	0m6.545s
root@test:~# lxc stop ct6269
root@test:~# time rsync -a /var/lib/lxd/storage-pools/default/containers/ct6269 10.10.10.11:/root/

real	0m1.678s
user	0m0.433s
sys	0m0.367s
```

Could you tell me , please, why this is happening and if I can somehow speed up lxc copy?
Thank you in advance!

**Comment by stgraber** [comment]
Do you get the same timing when using `-ar --devices --numeric-ids --partial --sparse --xattrs --compress --compress-level=2` ?

**Comment by kautMaks** [comment]
> Do you get the same timing when using `-ar --devices --numeric-ids --partial --sparse --xattrs --compress --compress-level=2` ?

Yes
```
root@test:~# time rsync -ar --devices --numeric-ids --partial --sparse --xattrs --compress --compress-level=2 /var/lib/lxd/storage-pools/default/containers/ct6269 10.10.10.11:/root/

real	1m11.364s
user	1m13.968s
sys	0m5.121s
root@test:~# time rsync -ar --devices --numeric-ids --partial --sparse --xattrs /var/lib/lxd/storage-pools/default/containers/ct6269 10.10.10.11:/root/

real	0m31.298s
user	0m22.911s
sys	0m6.517s
```

Seem like compress is the reason. 
Is it possible to turn it off for lxc copy?

**Comment by kautMaks** [comment]
Maybe it is possible to add an arguments to `lxc copy` for controlling compression?

**Comment by tomponline** [comment]
You should be able to disable this by setting `rsync.compression=false` on the storage pool hosting the instances.

See https://linuxcontainers.org/lxd/docs/master/storage/ and ttps://github.com/lxc/lxd/pull/7977/

**Comment by tomponline** [comment]
Also see https://discuss.linuxcontainers.org/t/how-to-disable-rsync-compression-for-lxc-copy-100-cpu-and-slow-for-local-network-transfer/9028 for discussions on speeding up rsync.

**Comment by kautMaks** [comment]
@tomponline Thanks! I'll try it.
