### ISSUE TITLE
sqlite3 v3.37 breaks schema v19 upgrade

### ISSUE THREAD

**Issue by gibmat** [lxc/lxd#9767]
Initially reported in #9736, although it was closed while fixing a different issue. I'm creating a new issue, rather than reopening the old one to hopefully keep things untangled. It is easy to reproduce with LXD v4.21 -- just build against the current version of sqlite3 and run the tests.

-----

The [upstream changelog](https://www.sqlite.org/releaselog/3_37_2.html) for sqlite3 v3.37 documents a change in behavior:

> When adding columns that contain a CHECK constraint or a generated column containing a NOT NULL constraint, the ALTER TABLE ADD COLUMN now checks new constraints against preexisting rows in the database and will only proceed if no constraints are violated.

This is causing the `updateFromV19()` method in `lxd/db/cluster/update.go` to fail, and is showing up as a couple new test failures:

```
=== RUN   TestImportPreClusteringData
    migration_test.go:60: 
        	Error Trace:	migration_test.go:60
        	Error:      	Received unexpected error:
        	            	failed to apply update 19: CHECK constraint failed
        	            	failed to ensure schema
        	            	github.com/lxc/lxd/lxd/db.OpenCluster
        	            		/build/lxd-4.21/_build/src/github.com/lxc/lxd/lxd/db/db.go:247
        	            	github.com/lxc/lxd/lxd/db_test.TestImportPreClusteringData
        	            		/build/lxd-4.21/_build/src/github.com/lxc/lxd/lxd/db/migration_test.go:59
        	            	testing.tRunner
        	            		/usr/lib/go-1.17/src/testing/testing.go:1259
        	            	runtime.goexit
        	            		/usr/lib/go-1.17/src/runtime/asm_amd64.s:1581
        	Test:       	TestImportPreClusteringData
--- FAIL: TestImportPreClusteringData (0.34s)

=== RUN   TestUpdateFromV19
    update_test.go:598: 
        	Error Trace:	update_test.go:598
        	Error:      	Received unexpected error:
        	            	failed to apply given update: failed to apply update 19: CHECK constraint failed
        	Test:       	TestUpdateFromV19
--- FAIL: TestUpdateFromV19 (0.17s)
```

-----

The relevant bit of affected code in LXD is here, where a table is altered to add a column with a consistency check:

```
func updateFromV19(tx *sql.Tx) error {
	// The column has a not-null constraint and a default value of
	// 0. However, leaving the 0 default won't effectively be accepted when
	// creating a new, due to the check constraint, so we are sure to end
	// up with a valid value.
	_, err := tx.Exec("ALTER TABLE nodes ADD COLUMN arch INTEGER NOT NULL DEFAULT 0 CHECK (arch > 0)")
```

The code then goes through and updates any existing entries in the table that don't have a proper arch set, ensuring that the table is consistent prior to the method returning. However, the change to sqlite3 immediately enforces the consistency check and is the root cause of the failure.

Frustratingly, there doesn't seem to be a supported way of adding a new column, updating the data, and then applying a consistency check. From what I've seen in some online searches, it looks like the only real way to do this would be to modify the existing table (without a consistency check), update all existing values, create a new table (with the consistency check), copy data from the existing table to the new one, delete the old table, and then rename the new table. Ugh.....

It appears that this is an intentional new feature of sqlite3 >= 3.37, so some update is going to have to be made to LXD.

**Comment by tomponline** [comment]
Maybe one for @markylaing ?

**Comment by tomponline** [comment]
Thanks for digging into the detail on this @gibmat

**Comment by markylaing** [comment]
> Maybe one for @markylaing ?

@tomponline sure :+1:

**Comment by tomponline** [comment]
Thanks, this one is probably higher priority than https://github.com/lxc/lxd/pull/9758 (as its fixing a breakage rather than an improvement), so if you get to a break point with that one then would be worth looking at this. Thanks
