### ISSUE TITLE
official image repo is unavailable

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#9772]
```
$ lxc image ls official:
Error: Failed to fetch https://images.linuxcontainers.org:8443/1.0: 503 Service Unavailable
```

Which is actually:
```
| official        | https://images.linuxcontainers.org:8443  | lxd           | tls         | YES    | NO     | NO     |
```

Should it still be available or is it replaced with something else?

**Comment by stgraber** [comment]
The `lxd` protocol on that image server has been deprecated for quite a while and fully retired some months ago.
https://discuss.linuxcontainers.org/t/update-to-our-image-servers/12515

Doing `lxc remote remove official` followed by `lxc remote add official https://images.linuxcontainers.org --protocol=simplestreams --public` should do the trick.

**Comment by tomposmiko** [comment]
Alright, thank you.
