### ISSUE TITLE
Implement server-side API filtering for storage volumes

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#9798]
Reported at https://discuss.linuxcontainers.org/t/list-storage-volumes-but-not-their-snapshots/13125

It'd be convenient if one could use API level filtering to have LXD only list storage volume of a specific type as well as being able to opt out of getting snapshots listed. This would likely be done through our API filtering syntax which we currently have on /1.0/instances.

Once that's in place, we can have `lxc storage volume list` get some filtering arguments similar to `lxc list` allowing for something like `lxc storage volume list my-pool type=custom snapshot=false`

**Comment by presztak** [comment]
@stgraber Can I work on this issue?

**Comment by stgraber** [comment]
Done!
