### ISSUE TITLE
4.22 release no longer buildable from source on Debian Stable, but Testing OK

### ISSUE THREAD

**Issue by kkremitzki** [lxc/lxd#9800]
# Required information

 * Distribution: Debian
 * Distribution version: 11 (bullseye)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.10.0-10-amd64
   * LXC version: 1:4.0.6-2
   * LXD version: 4.22
   * Storage backend in use: ZFS (N/A)

# Issue description

The lxd-4.22 tag is no longer buildable from source on Debian Stable following [the provided instructions](https://github.com/lxc/lxd/blob/master/doc/installing.md). This functioned as expected with lxd-4.21, and continues to work on Debian Testing/Unstable.

# Steps to reproduce

 1. Follow `installing.md` instructions for source build of lxd-4.22 tag on a Debian Stable system
 2. Upon issuing `make`, note the following error:
```
root@server:/usr/local/go/src/github.com/lxc/lxd# make
CC="cc" CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)" go install -v -tags "libsqlite3"  ./...
github.com/osrg/gobgp/v3/pkg/server
# github.com/osrg/gobgp/v3/pkg/server
../../../../pkg/mod/github.com/osrg/gobgp/v3@v3.0.0-rc4/pkg/server/server.go:113:24: undefined: net.ErrClosed
make: *** [Makefile:33: build] Error 2
```
3. Repeat steps on Debian Testing; `make` succeeds as expected
4. Repeat steps on Debian Stable with lxd-4.21; `make` succeeds as expected

# Information to attach

 - Debian Stable golang version: 2:1.15~1
 - Debian Testing/Unstable golang version: 2:1.17~1

**Comment by stgraber** [comment]
Oh right I'll fix the announcement but one thing we did in this release is raise the minimal Go, LXC and kernel versions.

You need a minimal of Go 1.16 to build the LXD daemon now. That was forced on us by changes in the upstream net packages. For a few releases now we were pinning a specific older commit for it but that's a very bad idea from a security standpoint so we had to raise the minimal Go version.

**Comment by stgraber** [comment]
https://linuxcontainers.org/lxd/docs/master/requirements/ has the minimal requirements.

**Comment by kkremitzki** [comment]
Ah, cool, I had suspected it was something like that but I didn't see anything mentioning it in the release announcement. Thanks for the prompt response. 👍

**Comment by stgraber** [comment]
I've updated the announcement now.

**Comment by tomponline** [comment]
bullseye backports seems to have 1.17 https://packages.debian.org/search?keywords=golang&searchon=names&section=all&suite=bullseye-backports FWIW
