### ISSUE TITLE
Cannot create snapshots, error "invalid ID"

### ISSUE THREAD

**Issue by rodalpho** [lxc/lxd#9831]
# Required information

 * Distribution: ubuntu
 * Distribution version:Ubuntu 20.04.3 LTS
 * The output of "lxc info" or if that fails: lxc info output attached

# Issue description
I can't take snapshots of my containers. This worked last week, nothing changed since then. Running snap LXD:
lxd                4.22             22277  latest/stable    canonical✓  -

08:58:01 root@myhost:~# lxc snapshot vpn auto-backup
Error: Failed creating instance snapshot record "auto-backup": Failed initialising instance: Failed creating storage record for snapshot: Insert volume snapshot: invalid ID

# Steps to reproduce

 1. Step one
  see above

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`): nothing relevant
 - [ ] Container log (`lxc info NAME --show-log`): attached
 - [ ] Container configuration (`lxc config show NAME --expanded`): attached
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log): attached
 - [ ] Output of the client with --debug: attached
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue): monitor output attached
[lxc_info_vpn.txt](https://github.com/lxc/lxd/files/7926077/lxc_info_vpn.txt)
[lxc_info_output.txt](https://github.com/lxc/lxd/files/7926078/lxc_info_output.txt)
[lxc_config_vpn.txt](https://github.com/lxc/lxd/files/7926079/lxc_config_vpn.txt)
[lxd.log.txt](https://github.com/lxc/lxd/files/7926082/lxd.log.txt)
[lxc_monitor_output.txt](https://github.com/lxc/lxd/files/7926083/lxc_monitor_output.txt)
[lxc_client_debug.txt](https://github.com/lxc/lxd/files/7926139/lxc_client_debug.txt)

**Comment by stgraber** [comment]
Hmm, ` 22277` should be the one with the fixes for that kind of issue...

Can you show `lxd sql global .dump | grep sequence` ?

**Comment by rodalpho** [comment]
Sure:

`DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('schema',52);
INSERT INTO sqlite_sequence VALUES('config',1);
INSERT INTO sqlite_sequence VALUES('cluster_groups',1);
INSERT INTO sqlite_sequence VALUES('projects',1);
INSERT INTO sqlite_sequence VALUES('images',1);
INSERT INTO sqlite_sequence VALUES('images_aliases',1);
INSERT INTO sqlite_sequence VALUES('nodes',1);
INSERT INTO sqlite_sequence VALUES('images_nodes',1);
INSERT INTO sqlite_sequence VALUES('profiles',1);
INSERT INTO sqlite_sequence VALUES('images_properties',7);
INSERT INTO sqlite_sequence VALUES('images_source',0);
INSERT INTO sqlite_sequence VALUES('instances',57);
INSERT INTO sqlite_sequence VALUES('instances_backups',0);
INSERT INTO sqlite_sequence VALUES('instances_config',22660);
INSERT INTO sqlite_sequence VALUES('instances_devices',2290);
INSERT INTO sqlite_sequence VALUES('instances_devices_config',4180);
INSERT INTO sqlite_sequence VALUES('instances_profiles',1264);
INSERT INTO sqlite_sequence VALUES('instances_snapshots',13);
INSERT INTO sqlite_sequence VALUES('instances_snapshots_config',294);
INSERT INTO sqlite_sequence VALUES('instances_snapshots_devices',10);
INSERT INTO sqlite_sequence VALUES('instances_snapshots_devices_config',30);
INSERT INTO sqlite_sequence VALUES('networks',0);
INSERT INTO sqlite_sequence VALUES('networks_acls',0);
INSERT INTO sqlite_sequence VALUES('networks_config',0);
INSERT INTO sqlite_sequence VALUES('networks_forwards',0);
INSERT INTO sqlite_sequence VALUES('networks_forwards_config',0);
INSERT INTO sqlite_sequence VALUES('networks_nodes',0);
INSERT INTO sqlite_sequence VALUES('networks_peers',0);
INSERT INTO sqlite_sequence VALUES('networks_peers_config',0);
INSERT INTO sqlite_sequence VALUES('networks_zones',0);
INSERT INTO sqlite_sequence VALUES('networks_zones_config',0);
INSERT INTO sqlite_sequence VALUES('nodes_config',0);
INSERT INTO sqlite_sequence VALUES('operations',4037);
INSERT INTO sqlite_sequence VALUES('profiles_config',3);
INSERT INTO sqlite_sequence VALUES('profiles_devices',6);
INSERT INTO sqlite_sequence VALUES('profiles_devices_config',15);
INSERT INTO sqlite_sequence VALUES('projects_config',4);
INSERT INTO sqlite_sequence VALUES('storage_pools',1);
INSERT INTO sqlite_sequence VALUES('storage_pools_config',4);
INSERT INTO sqlite_sequence VALUES('storage_pools_nodes',1);
INSERT INTO sqlite_sequence VALUES('storage_volumes',1);
INSERT INTO sqlite_sequence VALUES('storage_volumes_backups',0);
INSERT INTO sqlite_sequence VALUES('storage_volumes_config',0);
INSERT INTO sqlite_sequence VALUES('storage_volumes_snapshots_config',0);
INSERT INTO sqlite_sequence VALUES('warnings',4);`

**Comment by stgraber** [comment]
That `storage_volumes` key looks suspiciously low...

Can you run:
```
lxd sql global "UPDATE sqlite_sequence SET seq = (SELECT max(max(coalesce(storage_volumes.id, 0)), max(coalesce(storage_volumes_snapshots.id, 0))) FROM storage_volumes, storage_volumes_snapshots) WHERE name='storage_volumes';"
```

And see if that solves it?

**Comment by stgraber** [comment]
That's the exact same SQL statement as was pushed as a fix last week, so if that sorts it out, we'll have to put that into the weird update fluke category as your version of the snap should have effectively applied this fix twice by now...

**Comment by rodalpho** [comment]
That did _not_ fix the error-- but now I get a new one.

`
Error: Failed creating instance snapshot record "auto-backup": Failed initialising instance: Failed creating storage record for snapshot: sql: Scan error on column index 0, name "seq": converting NULL to int64 is unsupported
`

**Comment by stgraber** [comment]
Hmm, that's weird...

Can you show `lxd sql global "SELECT * FROM storage_volumes"` and `lxd sql global "SELECT * FROM storage_volumes_snapshots"` ?

**Comment by rodalpho** [comment]
Sure:

`
#lxd sql global "SELECT * FROM storage_volumes"
+-----+------------------------------------------------------------------+-----------------+---------+------+-------------+------------+--------------+
| id  |                               name                               | storage_pool_id | node_id | type | description | project_id | content_type |
+-----+------------------------------------------------------------------+-----------------+---------+------+-------------+------------+--------------+
| 2   | 38219778c2cf02521f34f950580ce3af0e4b61fbaf2b4411a7a6c4f0736071f9 | 1               | 1       | 1    |             | 1          | 0            |
| 3   | nzb                                                              | 1               | 1       | 0    |             | 1          | 0            |
| 7   | plex                                                             | 1               | 1       | 0    |             | 1          | 0            |
| 9   | 2a7896bae0f2322559e5b9452b0adf58a5a76f7b772fa6906c825407ea6c3386 | 1               | 1       | 1    |             | 1          | 0            |
| 14  | vpn                                                              | 1               | 1       | 0    |             | 1          | 0            |
| 25  | docker                                                           | 1               | 1       | 0    |             | 1          | 0            |
| 292 | adguard                                                          | 1               | 1       | 0    |             | 1          | 0            |
| 315 | mosaic                                                           | 1               | 1       | 0    |             | 1          | 0            |
| 420 | home                                                             | 1               | 1       | 0    |             | 1          | 0            |
+-----+------------------------------------------------------------------+-----------------+---------+------+-------------+------------+--------------+

# lxd sql global "SELECT * FROM storage_volumes_snapshots"
+----+-------------------+------+-------------+-------------+
| id | storage_volume_id | name | description | expiry_date |
+----+-------------------+------+-------------+-------------+
+----+-------------------+------+-------------+-------------+
`

**Comment by stgraber** [comment]
`lxd sql global "UPDATE sqlite_sequence SET seq = 420"`

**Comment by rodalpho** [comment]
That fixed the issue, thank you!

**Comment by kevinmoilar** [comment]
Had the same problem, this fixed it https://github.com/lxc/lxd/issues/9831#issuecomment-1020751652 thanks!

**Comment by rodalpho** [comment]
I would suggest being careful running commands like that, as the "420" he set the sequence to probably came from one of the previous queries I ran for him. Don't know if that could mess up someone else's config.

**Comment by kevinmoilar** [comment]
fair point. @stgraber what would you suggest for someone landing here with the same problem?

**Comment by stgraber** [comment]
We pushed the fix to all snap users already. If not using the snap, then you can use `lxd sql` to identify the highest id across both tables and set the sequence to that value.

**Comment by kevinmoilar** [comment]
Thanks @stgraber  We are using snap and did update twice around January 20th.

**Comment by stgraber** [comment]
The latest fix should have come out yesterday.
