### ISSUE TITLE
sudo lxd --debug --group lxd cant start virtual machine

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#9838]
As the title, LXD 4.22, the error message is

`project=default instance=test-vm err="lstat /usr/share/OVMF: no such file or directory"`

But it appears to be there?

```
$ ls /usr/share/OVMF
OVMF_CODE.fd  OVMF_CODE.ms.fd  OVMF_CODE.secboot.fd  OVMF_VARS.fd  OVMF_VARS.ms.fd  OVMF_VARS.snakeoil.fd
```

**Comment by stgraber** [comment]
Is that with the LXD snap or some other kind of package or build?

**Comment by turtle0x1** [comment]
LXD snap

**Comment by stgraber** [comment]
Oh, but you're manually starting LXD, so that'd be why.

**Comment by stgraber** [comment]
When LXD is started through the init scripts, a bunch more environment variables get detected and initialized, in this case, you're missing LXD_OVMF_PATH

**Comment by stgraber** [comment]
Try `export LXD_OVMF_PATH=/snap/lxd/current/share/qemu` that should get you closer to what happens when the snap starts the daemon.

**Comment by turtle0x1** [comment]
Am I doing it right `sudo export LXD_OVMF_PATH=/snap/lxd/current/share/qemu; sudo lxd --debug --group lxd`? 

It fails to start with the same  error. 

I also notice another one this time `instanceType=virtual-machine instance=test-vm project=default devName=eth0 err="Failed to remove interface \"tap15fc89e2\": Failed to run: ip link delete dev tap15fc89e2: "`.

Is there a better way of doing what I'm doing?

**Comment by stgraber** [comment]
No, maybe try `sudo LXD_OVMF_PATH=/snap/lxd/current/share/qemu lxd --debug --group lxd`

**Comment by turtle0x1** [comment]
Thats done it, thanks :)
