### ISSUE TITLE
Is it up to the client to close sockets after control closed?

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#9853]
If you do `lxc exec alpine bash` the shell doesn't "connect" (as expected) and the behaviour from LXD in this case appears to be close the control socket but not the other sockets (which will still establish successfully)

I'm not sure if the control socket is deemed important for operation but if the control socket is closed by the server shouldn't the others as well?

**Comment by stgraber** [comment]
I'll let @tomponline answer that one as he's been the one changing some of that logic recently :)

**Comment by tomponline** [comment]
@turtle0x1 do you have a reproducer showing the channels left open? Running `lxc exec alpine bash` will exit quickly and cause all channels/connections to be closed.

**Comment by tomponline** [comment]
Also, by the looks of things we would shut down all established connections on command exit:

https://github.com/lxc/lxd/blob/5cc57a293988f30ccb74c6ae959c2447efcb1716/lxd/instance_exec.go#L128-L148

**Comment by turtle0x1** [comment]
This time executing "ash" on a ubuntu VM
```
{
  method: 'POST',
  uri: 'https://localhost:8443/1.0/instances/test-vm/exec?project=default',
  rejectUnauthorized: false,
  json: true,
  body: {
    command: [ 'ash' ],
    environment: { HOME: '/root', TERM: 'xterm', USER: 'root' },
    'wait-for-websocket': true,
    interactive: true,
    height: 24,
    width: 83
  }
}
```

5 seconds after the control socket closed this is the state of the  of the sockets (the uuid is just LXDMosaic tracking).

Note how the "readyState" of "control" is "3" for closed and "0" is set  to "1" for open
```
{
  'a636ddd0-8844-11ec-9cad-397a0112b317': {
    '0': WebSocket {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      readyState: 1,
      protocol: '',
      _binaryType: 'nodebuffer',
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: '',
      _closeTimer: null,
      _closeCode: 1006, // Ignore this, its set to 1006 on init by node / the library it seems
      _extensions: {},
      _receiver: [Receiver],
      _sender: [Sender],
      _socket: [TLSSocket],
      _isServer: false,
      _redirects: 0,
      url: 'wss://localhost:8443/1.0/operations/655531d7-a533-47e0-bb1a-e1c29e25ab8e/websocket?secret=1701ade462a847e5f74855e00aec76742e6de03c9d05ed383a34d75571b0e0e3',
      _req: null,
      [Symbol(kCapture)]: false
    },
    control: WebSocket {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      readyState: 3,
      protocol: '',
      _binaryType: 'nodebuffer',
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: '',
      _closeTimer: null,
      _closeCode: 1006, // Ignore this, its set to 1006 on init by node  / the library it seems
      _extensions: {},
      _receiver: [Receiver],
      _sender: [Sender],
      _socket: [TLSSocket],
      _isServer: false,
      _redirects: 0,
      url: 'wss://localhost:8443/1.0/operations/655531d7-a533-47e0-bb1a-e1c29e25ab8e/websocket?secret=ec06d02d504fa00894a8c2f59f45135331ea0022c763ee1622b65503ac0b771d',
      _req: null,
      [Symbol(kCapture)]: false
    }
  }
}
```

**Comment by turtle0x1** [comment]
Short of producing a slightly involved node program just for this example im not sure how else I can make a quick example other than the above due to the nature of the problem (I'll learn to build and debug LXD "any day now")

**Comment by turtle0x1** [comment]
Okay I built from source and its not happening on master (using `bash` against `ash`) but it doesn't look like anything has changed (how odd)

**Comment by stgraber** [comment]
What version were you initially testing against?

But yeah, I don't think we've changed anything related to closing websockets in 4.22

**Comment by turtle0x1** [comment]
Initially found in SNAP 4.22 now testing against 30e08e31fa0ff8ada69770d147d69fa993d18c37 before @tomponline [pushed some fixes](https://github.com/lxc/lxd/commits/master?before=9e7ab44242f0bbae1ab9b947e2df2eda8227f6b2+35&branch=master).

30e08e31fa0ff8ada69770d147d69fa993d18c37 the bug appears

Master doesn't exhibit the behaviour

SNAP 4.22 does exhibit the behaviour

Not sure where to go from here

**Comment by stgraber** [comment]
All of those predate 4.22 though so it's hard to explain why master would be unaffected but 4.22 would have the issue.

**Comment by turtle0x1** [comment]
I came to the same conclusion, ill do some more testing tomorrow evening. Maybe i'm wrong.
