### ISSUE TITLE
Can a single operation effect multiple entities?

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#9854]
If we look at a message from the operations socket it may include the key `metadata.resources.instances`.

This key is currently an "array",  but can any one operation actually effect multiple entities? or is this future proofing? (Ignore the fact Ive used a command that would obviously have a 1 to 1 relation with operations)

For ease here is the output;

![ops](https://user-images.githubusercontent.com/12494629/151715766-ae93ab35-28fa-4f3b-9c21-98dcbd20ff54.png)

**Comment by stgraber** [comment]
It's mostly future proofing though I believe we at least report both image and instance at creation time.

I don't think we do it correctly currently but the bulk state update API probably ought to use this to indicate all the instances affected.
