### ISSUE TITLE
Progress % create_backup_progress operation

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#9855]
Can we get a progress % on `create_backup_progress` operation message or is it speculative until completion?

**Comment by stgraber** [comment]
It's a streaming speculative one.

We stream the rsync or zfs/btrfs output which comes without progress into a tar writer that also doesn't give us progress and through a compressor that similarly can't give us progress :)

**Comment by stgraber** [comment]
Basically how it works in LXD is that whenever we setup an io.Writer we wrap it into a ProgressTracker and if we know the target size, we set that property.

Our ProgressTracker is then in charge of updating the operation. If it knows the target size, you get a percentage progress, if it doesn't know it, then you just get the amount transferred and the speed.
