### ISSUE TITLE
LXD with QEMU 6.2.0 (and 7.0.0-rc3) breaks during migration

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9875]
From a comment from @stgraber to track this: "First fails the dumpvm and if retried crashes the whole thing."

Upstream bug: https://gitlab.com/qemu-project/qemu/-/issues/975

**Comment by tomponline** [comment]
```
stgraber@dakara:~$ lxc snapshot v1 --stateful
Error: Migration call failed
stgraber@dakara:~$ lxc snapshot v1 --stateful
Error: Monitor is disconnected
```

```
qemu-system-x86_64: qemu_savevm_state_complete_precopy_non_iterable: bdrv_inactivate_all() failed (-1)
qemu-system-x86_64: ../block.c:6521: bdrv_inactivate_recurse: Assertion `!(bs->open_flags & BDRV_O_INACTIVE)' failed.
```

**Comment by tomponline** [comment]
On QEMU master QEMU fails to start with seccomp failure if using sandbox mode:
```
[165363.141401] audit: type=1326 audit(1646673398.233:809): auid=4294967295 uid=0 gid=0 ses=4294967295 subj=? pid=2880207 comm="qemu-system-x86" exe="/snap/lxd/x2/bin/qemu-system-x86_64" sig=31 arch=c000003e syscall=56 compat=0 ip=0x7fd86ad930bf code=0x80000000
```

Disabling sandbox mode still has the original issue on master branch:
```
qemu-system-x86_64: qemu_savevm_state_complete_precopy_non_iterable: bdrv_inactivate_all() failed (-1)
qemu-system-x86_64: ../block.c:6757: bdrv_inactivate_recurse: Assertion `!(bs->open_flags & BDRV_O_INACTIVE)' failed.
```

**Comment by stgraber** [comment]
> syscall 56 is mpx, can you double check that with gdb?

syscall 56 on x86_64 is clone, isn't it?

**Comment by bonzini** [comment]
> syscall 56 on x86_64 is clone, isn't it?

uff yes, I checked 32-bit by mistake. Do you know what flag it is that QEMU is blocking (in the case of FORBID_CLONE_FLAG) or not finding (in the case of REQUIRE_CLONE_FLAG)?

**Comment by stgraber** [comment]
@bonzini 

```
3042087 clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fb2d10f74d0) = 56
3042087 +++ killed by SIGSYS (core dumped) +++
```

**Comment by bonzini** [comment]
Thanks. Sandboxing that prevents forking child processes is disabled by default, are you using `-sandbox enable,spawn=deny`? If so what's the backtrace leading to the `clone` call?

**Comment by stgraber** [comment]
Ah, that'd make sense, so something changed recently in master which now requires a temporary sub-process.
We were running with `on,obsolete=deny,elevateprivileges=allow,spawn=deny,resourcecontrol=deny`
I'll flip that to `spawn=allow`. We have apparmor preventing execution of random binaries anyway so the seccomp profile is more of an extra safety net :)

With that changed, `master` now behaves the same as `6.2.0`, so we still get a qemu crash on migration but otherwise things seem fine.

**Comment by bonzini** [comment]
> something changed recently in master which now requires a temporary sub-process

That isn't expected AFAIR, so please do provide a backtrace.

**Comment by stgraber** [comment]
Looking at strace output here, the call which would have previously been blocked by seccomp is:
```
3386293 clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f4591fdf4d0) = 3386305
```

This call is made right after the seccomp policy is put in place:
```
3386293 seccomp(SECCOMP_SET_MODE_STRICT, 0x1, NULL) = -1 EINVAL (Invalid argument)
3386293 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_TSYNC, NULL) = -1 EFAULT (Bad address)
3386293 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_LOG, NULL) = -1 EFAULT (Bad address)
3386293 seccomp(SECCOMP_GET_ACTION_AVAIL, 0, [SECCOMP_RET_LOG]) = 0
3386293 seccomp(SECCOMP_GET_ACTION_AVAIL, 0, [SECCOMP_RET_KILL_PROCESS]) = 0
3386293 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_SPEC_ALLOW, NULL) = -1 EFAULT (Bad address)
3386293 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_NEW_LISTENER, NULL) = -1 EFAULT (Bad address)
3386293 seccomp(SECCOMP_GET_NOTIF_SIZES, 0, {seccomp_notif=80, seccomp_notif_resp=24, seccomp_data=64}) = 0
3386293 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_TSYNC_ESRCH, NULL) = -1 EFAULT (Bad address)
3386293 seccomp(SECCOMP_GET_ACTION_AVAIL, 0, [SECCOMP_RET_KILL_PROCESS]) = 0
3386293 prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) = 0
3386293 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_TSYNC|SECCOMP_FILTER_FLAG_TSYNC_ESRCH, {len=36, filter=0x56463420be50}) = 0
3386293 openat(AT_FDCWD, "/var/snap/lxd/common/lxd/logs/v1/qemu.log", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
3386293 dup2(5, 2)                      = 2
3386293 close(5)                        = 0
3386293 stat("/snap/lxd/x2/bin/pc-bios", 0x7ffce4a79390) = -1 ENOENT (No such file or directory)
3386293 pipe([5, 6])                    = 0
3386293 clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f4591fdf4d0) = 3386305
```

That sub-process then itself just does:
```
3386305 set_robust_list(0x7f4591fdf4e0, 24 <unfinished ...>
3386305 <... set_robust_list resumed>)  = 0
3386305 rt_sigprocmask(SIG_SETMASK, ~[ILL FPE SEGV RTMIN RT_1], [], 8) = 0
3386305 clone(child_stack=0x7f4591e7a4f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[3386306], tls=0x7f4591e7e700, child_tidptr=0x7f4591e7e9d0) = 3386306
3386305 rt_sigprocmask(SIG_SETMASK, [],  <unfinished ...>
3386305 <... rt_sigprocmask resumed>NULL, 8) = 0
3386305 close(5)                        = 0
3386305 fcntl(6, F_GETFD)               = 0
3386305 fcntl(6, F_SETFD, FD_CLOEXEC)   = 0
3386305 setsid()                        = 3386305
3386305 clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f4591fdf4d0) = 3386307
3386305 munmap(0x7f4591e7f000, 897024 <unfinished ...>
3386305 <... munmap resumed>)           = 0
3386305 exit_group(0)                   = ?
3386305 +++ exited with 0 +++
```

With that last process, `3386307` becoming the long-running emulator process.

This looks like mostly normal daemonization logic to me. We do run QEMU with `-daemonize`, just a bit confused by what may have changed in master to cause this to no fail unless we change spawn to allow.

**Comment by stgraber** [comment]
The older QEMU would do:
```
3402327 seccomp(SECCOMP_SET_MODE_STRICT, 0x1, NULL) = -1 EINVAL (Invalid argument)
3402327 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_TSYNC, NULL) = -1 EFAULT (Bad address)
3402327 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_LOG, NULL) = -1 EFAULT (Bad address)
3402327 seccomp(SECCOMP_GET_ACTION_AVAIL, 0, [SECCOMP_RET_LOG]) = 0
3402327 seccomp(SECCOMP_GET_ACTION_AVAIL, 0, [SECCOMP_RET_KILL_PROCESS]) = 0
3402327 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_SPEC_ALLOW, NULL) = -1 EFAULT (Bad address)
3402327 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_NEW_LISTENER, NULL) = -1 EFAULT (Bad address)
3402327 seccomp(SECCOMP_GET_NOTIF_SIZES, 0, {seccomp_notif=80, seccomp_notif_resp=24, seccomp_data=64}) = 0
3402327 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_TSYNC_ESRCH, NULL) = -1 EFAULT (Bad address)
3402327 seccomp(SECCOMP_GET_ACTION_AVAIL, 0, [SECCOMP_RET_KILL_PROCESS]) = 0
3402327 brk(0x556b8ca86000)             = 0x556b8ca86000
3402327 prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) = 0
3402327 seccomp(SECCOMP_SET_MODE_FILTER, SECCOMP_FILTER_FLAG_TSYNC|SECCOMP_FILTER_FLAG_TSYNC_ESRCH, {len=39, filter=0x556b8ca69ae0}) = 0
3402327 openat(AT_FDCWD, "/var/snap/lxd/common/lxd/logs/v1/qemu.log", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
3402327 dup2(5, 2)                      = 2
3402327 close(5)                        = 0
3402327 stat("/snap/lxd/22619/bin/pc-bios", 0x7ffcc05e1ba0) = -1 ENOENT (No such file or directory)
3402327 pipe([5, 6])                    = 0
3402327 clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f65ddfc64d0) = 3402339
```

So at the syscall level, no difference but the newer QEMU triggers seccomp while the older doesn't, so maybe something changed in the seccomp profile itself?

**Comment by bonzini** [comment]
Yes:

```
    commit 5a2f693f07a1e93ada5277b2fb1530b2698be0fa
    Author: Daniel P. Berrangé <berrange@redhat.com>
    Date:   Thu Jul 29 13:32:37 2021 +0100

    seccomp: fix blocking of process spawning
    
    When '-sandbox on,spawn=deny' is given, we are supposed to block the
    ability to spawn processes. We naively blocked the 'fork' syscall,
    forgetting that any modern libc will use the 'clone' syscall instead.
    
    We can't simply block the 'clone' syscall though, as that will break
    thread creation. We thus list the set of flags used to create threads
    and block anything that doesn't match this exactly.
    
    Acked-by: Eduardo Otubo <otubo@redhat.com>
    Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>
```

**Comment by stgraber** [comment]
Ok, so based on that commit, then it seems expected that the combination of `-daemonize` and `-sanbox on,spawn=false` would trigger seccomp and cause qemu to be killed?

**Comment by bonzini** [comment]
Yes, it is expected.

**Comment by stgraber** [comment]
Ok, cool, I'll send a fix for that then, it's an easy enough change ;)

**Comment by stgraber** [comment]
Re-testing the migration logic with 7.0.0-rc3 now to see if we can move forward to a newer qemu :)

**Comment by tomponline** [comment]
@stgraber I didnt get chance to try this on Jammy's QEMU yet either.

**Comment by stgraber** [comment]
Got an updated snap with QEMU 7.0.0-rc3, at least building it was easy, LXD reports its version as 6.2.93.

Unfortunately QEMU is still broken.

```
stgraber@dakara:~$ lxc init images:ubuntu/20.04/cloud v1 --vm
Creating v1
stgraber@dakara:~$ lxc config device override v1 root size.state=2GiB
Device root overridden for v1
stgraber@dakara:~$ lxc config set v1 migration.stateful=true
stgraber@dakara:~$ lxc start v1
stgraber@dakara:~$ lxc exec v1 -- uptime
 22:05:54 up 0 min,  0 users,  load average: 0.07, 0.02, 0.00
stgraber@dakara:~$ lxc snapshot v1 --stateful
Error: Migration call failed
stgraber@dakara:~$ lxc snapshot v1 --stateful
Error: Monitor is disconnected
```

The first attempt at `lxc snapshot v1 --stateful` caused this in the log:
```
qemu-system-x86_64: qemu_savevm_state_complete_precopy_non_iterable: bdrv_inactivate_all() failed (-1)
```

The second attempt caused this:
```
qemu-system-x86_64: ../block.c:6757: bdrv_inactivate_recurse: Assertion `!(bs->open_flags & BDRV_O_INACTIVE)' failed.
```

Which crashed QEMU completely and caused the VM to die.
Nothing relevant showed up in dmesg, so this wasn't caused by an obvious seccomp or apparmor policy issue.

**Comment by stgraber** [comment]
The snap in question is at https://dl.stgraber.org/lxd/lxd-qemu-7.0.0-rc3.snap and can be installed with:
```
snap install lxd-qemu-7.0.0-rc3.snap --dangerous
```

**Comment by stgraber** [comment]
@tomponline can I let you take it from there, likely chat with @bonzini to try and sort this out prior to the QEMU 7.0 release?

**Comment by tomponline** [comment]
Yep confirmed seeing same thing with Ubuntu Jammy QEMU 6.2 packages:

```
lxc info v1 --show-log
...
qemu-system-x86_64: qemu_savevm_state_complete_precopy_non_iterable: bdrv_inactivate_all() failed (-1)
qemu-system-x86_64: Unable to write to file: Broken pipe
qemu-system-x86_64: ../../block.c:6521: bdrv_inactivate_recurse: Assertion `!(bs->open_flags & BDRV_O_INACTIVE)' failed.
```

**Comment by tomponline** [comment]
@bonzini requested upstream bug be opened https://gitlab.com/qemu-project/qemu/-/issues/975

**Comment by tomponline** [comment]
LXD calls QMP `getfd` to pass a file handle with `fdname` = `migration`,
and then calls the `migrate` QMP command with `uri` = `fd:migration`.

We then repeatedly call `query-migrate` QMP command with a 1s sleep between calls, checking the status of the migration process. We see the `Return.Status` value returned as "failed".

This triggers the error.

See

https://github.com/lxc/lxd/blob/master/lxd/instance/drivers/qmp/commands.go#L194-L229

**Comment by tomponline** [comment]
@stgraber FYI @bonzini says "that's very unlikely, the release is basically ready" WRT to getting the fix into the 7.0 release.

**Comment by tomponline** [comment]
This looks like the candidate commit that introduce the issue:

https://github.com/qemu/qemu/commit/a13de40a05478e64726dd9861135d344837f3c30

Need to confirm though.

But it returns `-EPERM` which is the error value we are seeing returned from `qemu_savevm_state_complete_precopy_non_iterable` (which calls `bdrv_inactivate_recurse`).

Additionally the commit message explains it was trying to fix the crash caused by the same assert we see when calling `lxc snapshot` the 2nd time:

> This commit fixes a crash when we do migration during backup: prior to
the commit nothing prevents all nodes inactivation at migration finish
and following backup write to the target crashes on assertion
"assert(!(bs->open_flags & BDRV_O_INACTIVE));" in
bdrv_co_write_req_prepare().

**Comment by tomponline** [comment]
@stgraber confirmed that reverting https://gitlab.com/qemu-project/qemu/-/commit/a13de40a05478e64726dd9861135d344837f3c30 fixes it for us.

**Comment by tomponline** [comment]
@stgraber we have made some good progress:

> So the problem is that open("/var/lib/lxd/virtual-machines/v1/qemu.nvram", O_RDONLY) fails with EACCES, i.e. QEMU doesn't have the permission to (re)open this file.
> bdrv_inactivate_recurse() ignores this error because we're only trying to give up permissions, but later inactivating the block node fails because we aren't allowed to have the permissions any more on an inactive child node. I think this is actually the correct behaviour.
> So the remaining question is why opening the file fails. This may be related to the sandboxing used.

I have confirmed that because `/var/lib/lxd/virtual-machines/v1` is chmod 700, and we use `-runas lxd`, it cannot re-open this file.
Chmodding `/var/lib/lxd/virtual-machines/v1` to 711 after starting the VM (its reset each time its started), allows the stateful snapshot to be taken! :)

However it seems to leave the qemu process running but unresponsive.

I'm thinking trying to pass /var/lib/lxd/virtual-machines/v1/qemu.nvram via an fdset may help.

**Comment by tomponline** [comment]
I think it needs to write to `/var/lib/lxd/virtual-machines/v1/qemu.nvram` during stateful snapshot. Setting it to 717 fixes stateful snapshot.

**Comment by tomponline** [comment]
Ive VM starting with FD via /dev/fd/ , but it tries to reopen the file so it needs it to be writable by lxd user. I'm going to try next with an fdset and qmp as the function that's failing has special DUP handling for fdset paths.
