### ISSUE TITLE
ubuntu xenial container no longer start on jammy host

### ISSUE THREAD

**Issue by woutervb** [lxc/lxd#9921]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Jammy
 * lxc info                                                              1 ✘  12:46:35 
config:
  core.https_address: '[::]'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
- instance_get_full
- qemu_metrics
- gpu_mig_uuid
- event_project
- clustering_evacuation_live
- instance_allow_inconsistent_copy
- network_state_ovn
- storage_volume_api_filtering
- image_restrictions
- storage_zfs_export
- network_dns_records
- storage_zfs_reserve_space
- network_acl_log
- storage_zfs_blocksize
- metrics_cpu_seconds
- instance_snapshot_never
- certificate_token
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.20.10:8443
  - 10.194.202.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICCzCCAZCgAwIBAgIRAMwWEuDoCo+JfMT3I0Jb/fgwCgYIKoZIzj0EAwMwNjEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEBoeXBl
    cmlvbjAeFw0yMjAyMTQwMDEyMDRaFw0zMjAyMTIwMDEyMDRaMDYxHDAaBgNVBAoT
    E2xpbnV4Y29udGFpbmVycy5vcmcxFjAUBgNVBAMMDXJvb3RAaHlwZXJpb24wdjAQ
    BgcqhkjOPQIBBgUrgQQAIgNiAATpDSDggxD8NAoeuEo81U49imLE5kM+zS8U5kTr
    nhONNu80Vd1+p2E0DGeGCnEjctk+1HV9rjqfT8rYjuxdPf5rG/8+K/MKrUs0iOwb
    0VdA3SOhJxsLLla+pd3Y8rZBj6+jYjBgMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUE
    DDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMCsGA1UdEQQkMCKCCGh5cGVyaW9u
    hwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMDA2kAMGYCMQCLKtVo
    0jANPF2gsaEGZUYn4UHB3GXcVAclX5K94bdrSH8PSwDmbptEKeveGRZFgSICMQCz
    wjMbWihLKiggs7ETYfIKxHQVDbAxH8HvH+tpQk3LUD6x//xP4SRIWSxgGf4NEns=
    -----END CERTIFICATE-----
  certificate_fingerprint: af00db6fe034f9ee2cfc821a539fe03feb3ceae59c19fc8ed89e3c864990d056
  driver: lxc | qemu
  driver_version: 4.0.12 | 6.1.1
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.15.0-18-lowlatency
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "22.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: hyperion
  server_pid: 3653
  server_version: "4.23"
  storage: btrfs | zfs
  storage_version: 5.4.1 | 2.0.6-1ubuntu3
  storage_supported_drivers:
  - name: ceph
    version: 15.2.14
    remote: true
  - name: btrfs
    version: 5.4.1
    remote: false
  - name: cephfs
    version: 15.2.14
    remote: true
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.07(2) (2019-11-30) / 1.02.167 (2019-11-30) / 4.45.0
    remote: false
  - name: zfs
    version: 2.0.6-1ubuntu3
    remote: false

# Issue description

When attempting to launch an xenial container (or vm) it fails, hanging at `/sbin/init`, similar symptoms as as #5831. Other containers (bionic / focal) don't have this problem.

Container can be accessed using exec, and there is only a single `/sbin/init` process

# Steps to reproduce
1. lxc launch ubuntu:xenial
2. lxc exec <random-name given above> -- bash
This will show a single process

Following the steps from #5831 (creating and mounting the systemd cgroup) results in the following message on start:
```lxc launch ubuntu:xenial                                                ✔  12:44:05 
Creating the instance
Instance name is: eager-gopher
Starting eager-gopher
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart eager-gopher /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/eager-gopher/lxc.conf: 
Try `lxc info --show-log local:eager-gopher` for more info
```
and
```lxc info --show-log local:eager-gopher                              INT ✘  12:58:44 
Name: eager-gopher
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2022/02/16 12:44 AEST
Last Used: 2022/02/16 12:44 AEST

Log:

lxc eager-gopher 20220216024416.464 WARN     conf - conf.c:lxc_map_ids:3588 - newuidmap binary is missing
lxc eager-gopher 20220216024416.464 WARN     conf - conf.c:lxc_map_ids:3594 - newgidmap binary is missing
lxc eager-gopher 20220216024416.465 WARN     conf - conf.c:lxc_map_ids:3588 - newuidmap binary is missing
lxc eager-gopher 20220216024416.465 WARN     conf - conf.c:lxc_map_ids:3594 - newgidmap binary is missing
lxc eager-gopher 20220216024416.487 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_mount:1771 - No such file or directory - Failed to create cgroup at_mnt 23()
lxc eager-gopher 20220216024416.487 ERROR    conf - conf.c:lxc_mount_auto_mounts:851 - No such file or directory - Failed to mount "/sys/fs/cgroup"
lxc eager-gopher 20220216024416.487 ERROR    conf - conf.c:lxc_setup:4391 - Failed to setup remaining automatic mounts
lxc eager-gopher 20220216024416.487 ERROR    start - start.c:do_start:1275 - Failed to setup container "eager-gopher"
lxc eager-gopher 20220216024416.488 ERROR    sync - sync.c:sync_wait:34 - An error occurred in another process (expected sequence number 4)
lxc eager-gopher 20220216024416.495 WARN     network - network.c:lxc_delete_network_priv:3617 - Failed to rename interface with index 0 from "eth0" to its initial name "veth67b9f745"
lxc eager-gopher 20220216024416.495 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:877 - Received container state "ABORTING" instead of "RUNNING"
lxc eager-gopher 20220216024416.495 ERROR    start - start.c:__lxc_start:2074 - Failed to spawn container "eager-gopher"
lxc eager-gopher 20220216024416.495 WARN     start - start.c:lxc_abort:1039 - No such process - Failed to send SIGKILL via pidfd 19 for process 225491
lxc eager-gopher 20220216024421.567 WARN     conf - conf.c:lxc_map_ids:3588 - newuidmap binary is missing
lxc eager-gopher 20220216024421.567 WARN     conf - conf.c:lxc_map_ids:3594 - newgidmap binary is missing
lxc 20220216024421.576 ERROR    af_unix - af_unix.c:lxc_abstract_unix_recv_fds_iov:218 - Connection reset by peer - Failed to receive response
lxc 20220216024421.576 ERROR    commands - commands.c:lxc_cmd_rsp_recv_fds:127 - Failed to receive file descriptors for command "get_state"
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
That's expected. In fact, LXD 4.23 will refuse to start the container instead of letting it start and then fail.
Ubuntu 16.04, CentOS 7 and similarly old distros will not boot on a system which exclusively uses cgroup2.

**Comment by woutervb** [comment]
And why does it also fail to work when passing the --vm option?

looking to `lxc info --show-log` does seem to indicate some permissions are wrong with the default lxd snap:
```
Name: xenial-vm
Status: RUNNING
Type: virtual-machine
Architecture: x86_64
PID: 68679
Created: 2022/02/16 14:19 AEST
Last Used: 2022/02/16 14:20 AEST

Resources:
  Processes: -1
  Disk usage:
    root: 25.72MiB
  Network usage:
    eth0:
      Type: broadcast
      State: UP
      Host interface: tapd8108935
      MAC address: 00:16:3e:bb:0c:77
      MTU: 1500
      Bytes received: 48.25kB
      Bytes sent: 17.13kB
      Packets received: 382
      Packets sent: 195
      IP addresses:
        inet:  10.194.202.185/24 (global)

Log:

warning: tap: open vhost char device failed: Permission denied
warning: tap: open vhost char device failed: Permission denied
```

**Comment by cjwatson** [comment]
Booting with `systemd.unified_cgroup_hierarchy=false` works around this by going back to cgroup1 mode.

**Comment by stgraber** [comment]
The VM works but 16.04 does not have a LXD agent so you won't be able to use lxc exec with it, instead you'll need to use cloud-init to inject an SSH key and then get in that way.
