### ISSUE TITLE
non interactive token generation

### ISSUE THREAD

**Issue by aivanise** [lxc/lxd#9926]
would it be possible to make config trust add token non-interactive? Right now it always asks for a token name from the console.

I'd like to be able to script something like

`token=$(ssh server lxc config trust add --token tokename)
`
so if a user has ssh access to the server he can get it added as a remote without interaction

thank you

**Comment by stgraber** [comment]
@monstermunchkin I thought we said we'd make `lxc config trust add --name something` work to handle that, can you send a PR which makes it work?
