### ISSUE TITLE
Can't change interface eth0 settings

### ISSUE THREAD

**Issue by reversecipher** [lxc/lxd#996]
Container interface eth0 settings seems to get overwritten by profile settings. Using lxc config edit for example to change interface parent bridge doesn't seem to take effect but making the change in default profile does. This works when editing any other interface.

**Comment by pcdummy** [comment]
Will try and fix.

**Comment by pcdummy** [comment]
This doesn't work - the interface remains:

    lxc init ubuntu/trusty/amd64 foo
    lxc config device remove foo eth0
    lxc config show foo

This works:
    lxc config device add foo eth1 nic nictype=bridged parent=lanbr0
