### ISSUE TITLE
Allow for http metric endpoint

### ISSUE THREAD

**Issue by vosdev** [lxc/lxd#9971]
With the new metrics now available for the LXD daemon, I would like to use this with plain HTTP instead of having to play with certs/trusts

So I would like to request `core.metrics_address` to have support for http://

**Comment by simondeziel** [comment]
Would it work for you if instead of doing plain HTTP, the client certificate was made optional? This way, prometheus would still use HTTPS but without the administrative overhead of dealing with certificates.

**Comment by vosdev** [comment]
That would work! Users could then skip TLS verification as a whole using `insecure_skip_verify: true`
