### ISSUE TITLE
Increasing default.img storage zfs size is faulty when you look with lxc storage show default

### ISSUE THREAD

**Issue by cemzafer** [lxc/lxd#9972]
# Required information

 * Distribution: ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.13.0-30-generic
   * LXC version: 4.23
   * LXD version: 4.23
   * Storage backend in use: zfs

# Issue description

Increasing default.img size looks faulty when you look with ```lxc storage show default```
# Steps to reproduce

1. Increase the default.img which is zfs filesystem.
2. Restart systemctl snap.lxd.daemon 
3. "lxc storage show default" command shows the previous size.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
That's normal. The size property is a read only property containing the size that was requested at creation time, it does not reflect any manual increases you may have done.

lxc storage info has the details about the live used and free space for a pool.
