### ISSUE TITLE
LXD Snap pkg - Parallel Install support

### ISSUE THREAD

**Issue by snappyguide** [lxc/lxd#9974]
Snap parallel install feature on LXD package didn't work, referring: https://snapcraft.io/docs/parallel-installs

I get following error:
root@srv1:~$ sudo snap set system experimental.parallel-instances=true
root@srv1:~$ sudo snap install lxd_foo
error: cannot perform the following tasks:
- Set automatic aliases for snap "lxd_foo" (cannot enable alias "lxc" for "lxd_foo", already enabled for "lxd")

Is there any plans to support snap parallel install for lxd?

**Comment by stgraber** [comment]
No, there isn't. Unlike normal snaps, LXD manages global system resources (security profiles, storage pools, networks, ...), having multiple copies of LXD running on the same system will result in a lot of weirdness and problems that we don't want to deal with.
