### ISSUE TITLE
Total Memory fix of Grafana Dashboard

### ISSUE THREAD

**Issue by felix-engelmann** [lxc/lxd#9978]
# Required information

https://grafana.com/grafana/dashboards/15726

# Issue description

The grafana dashboard does not show the correct total memory in the overview.

Currently it sums the total memory over all containers. This is incorrect if there are multiple containers on the same host.

Instead of calculating the total by
```
sum(lxd_memory_MemTotal_bytes{job="$job",project="$project"})
```

it should only take one container per instance (which is a lxd host):

```
sum(topk by (instance) (1,lxd_memory_MemTotal_bytes{job="$job",project="$project"}))
```
that takes the maximum total memory for one container on each instance.

PS: Thanks for exposing the metrics and creating the dashboard. Is it possible to maintain the json in a git, so it is easier to create PRs.

**Comment by felix-engelmann** [comment]
It's even more tricky to get the lxd_memory_MemFree_bytes correct in an overview.

**Comment by stgraber** [comment]
The dashboard assumes that all containers have memory limits set.
If you do not, then you indeed do need a change like the one you're suggesting.

However applying this change to the default dashboard would then completely break any deployment where instance or project memory limits are in place.

**Comment by stgraber** [comment]
@simondeziel does that make sense? ^
