### ISSUE TITLE
Allow core.https.address to bind multiple addresses or selected NIC

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#9996]
The choice right now is either one IP Address or wildcard (*) which causes lxd listening on whatever a host binds on all interface.
That in in some cases could be a wide range/large blocks of private and public IPv4/Ipv6.

By allowing selected multiple addresses in a non-clustered mixed infrastructure, neighbor hosts could communicate via intranet whilst remote servers access over a specific IP Address or NIC. 
core.https.address : 127.0.0.1:7443,192.168.1.101:8443,8.8.8.8:8443
core.https.address : eno1:8443,eno4:8443

**Comment by stgraber** [comment]
I've been thinking about this for a little bit now and I don't think we'll be doing this.

Binding an interface isn't something that Linux really supports in the first place (especially through Go), so you effectively need to monitor and re-bind addresses. It also means you need to support situations where you may have the same address on multiple interfaces with additional interfaces being added/removed.

For the more general binding of multiple specific addresses, the difficulty is in dealing with overlaps when using wildcards, things like `:8443` covering that port on all addresses and families, `0.0.0.0:8443` doing the same but only for the ipv4 family, `[::]:8443` being the same as `:8443` unless your kernel has some sysctl disabled (making it differ between distros), ...

Additionally, LXD needs to expose a list of addresses to clients which can be passed to other servers.

So in general, I'd recommend using `:8443` in your case combined with good old fashion firewalling in front to restrict who can connect to it.
